### ISSUE TITLE
network connectivity to exposed ports from a sub-dind broken on 172.18.0.1/24 network

### ISSUE THREAD

**Issue by vikstrous** [moby/moby#32842] opened 2017-04-26 11:32 UTC
**Description**

Connections to exposed ports on sub-dind containers are failing on the  172.18.0.1/24 network, but working on other networks/ip ranges.

**Steps to reproduce the issue:**

```
docker network create testnet --subnet 172.18.0.1/24
docker run -d --name outer --privileged --net testnet docker:dind
IP=$(docker inspect outer --format '{{.NetworkSettings.Networks.testnet.IPAddress}}')
docker exec -it outer docker run -d -p 8000:80 nginx
docker exec -it outer wget -O - $IP:8000
# success
docker exec -it outer docker run -d --privileged -p 8001:2375 docker:dind
docker exec -it outer wget -O - $IP:8001
# fail
```
This happens only on one network. If I create a network with a different ip range it works as expected. The ip range that's failing is: 172.18.0.1/24 and the one that's passing is: 172.19.0.1/24

This is what the failure looks like:

```
[ec2-user@ip-10-0-1-89 ~]$ docker exec -it outer wget -O - 172.18.0.2:8001
Connecting to 172.18.0.2:8001 (172.18.0.2:8001)
wget: can't connect to remote host (172.18.0.2): Host is unreachable
```

I can still repro after restarting docker or the host.

**Describe the results you received:**
Can't connect to exposed port from outer dind or host

**Describe the results you expected:**
Can connect to exposed port from outer dind and host

**Additional information you deem important (e.g. issue happens only occasionally):**
I repro'd the same issue on another machine running a different kernel and it failed a little differently. It just timed out when trying to connect instead:

```
docker exec -it outer wget -O - $IP:8001
Connecting to 172.18.0.2:8001 (172.18.0.2:8001)
wget: can't connect to remote host (172.18.0.2): Operation timed out
```

The kernel version here is 4.8.17. Same behaviour here. If the ip range is different, it works, if it's 172.18.0.0/24, it fails.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 68
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.20-10.30.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.306 GiB
Name: ip-10-0-1-89
ID: RPMY:ISSO:YWQR:6GRS:PLRD:377R:UYHX:LGZ4:PO6V:QYQZ:TBLV:GCXZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 28
 System Time: 2017-04-26T11:12:03.149086272Z
 EventsListeners: 0
Username: viktorstanchev
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
aws, physical

**Comment by fcrisciani** [comment] 2017-04-26 16:23
In the case of Dind (docker in docker) there is 2 level of abstraction:
host <--> docker level 1 <---> docker level 2
On the host the docker0 bridge that is used for default bridge connectivity uses 172.17.0.0/24 network.
On the docker level 1 instead the docker0 bridge uses the 172.18.0.0/24.
That is the reason why you are seeing that failure

**Comment by thaJeztah** [comment] 2017-04-30 04:59
@fcrisciani so, this is not a bug? (didn't follow the entire issue; wondering if this could be closed)

**Comment by fcrisciani** [comment] 2017-04-30 18:48
nope, the 172.18.0.0/16 is used as default network inside dind, so reusing it for a separate network creates overlapping issues

**Comment by thaJeztah** [comment] 2017-05-01 22:04
Thanks, let me close this issue then 👍

**Closed by thaJeztah** 2017-05-01 22:04 UTC
Labels: area/networking, version/17.03
