### ISSUE TITLE
load build context: failed to solve: changes out of order: ".git/HEAD" "" - 4.27.1 Docker Desktop on Windows

### ISSUE THREAD

**Issue by christophwille** [moby/moby#47343] opened 2024-02-06 13:29 UTC
### Description

Works on 4.26.1, fails on 4.27.1:

```
[+] Building 0.0s (0/0)  docker:default
2024/02/06 13:45:13 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 1.5s (7/23)                                                                                 docker:default
=> [sampleapp] load build definition from Dockerfile                                                      0.1s
=> => transferring dockerfile: 2.27kB                                                                             0.0s
=> [sampleapp] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0                                      1.1s
=> [sampleapp] load metadata for mcr.microsoft.com/dotnet/sdk:8.0                                         1.0s
=> [sampleapp] load .dockerignore                                                                         0.0s
=> => transferring context: 464B                                                                                  0.0s
=> CANCELED [migrator build  1/13] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:8e77ad6fb7c33c17f026424d3bef05ea  0.2s
=> => resolve mcr.microsoft.com/dotnet/sdk:8.0@sha256:8e77ad6fb7c33c17f026424d3bef05ea2ee15d1621e28f312adeab4dc1  0.0s
=> => sha256:8e77ad6fb7c33c17f026424d3bef05ea2ee15d1621e28f312adeab4dc1005866 1.08kB / 1.08kB                     0.0s
=> => sha256:8746ffe502765a361e9f5d26db9f50c1ecb663f36c5f346c86604fe53fcd2bfa 2.22kB / 2.22kB                     0.0s
=> => sha256:ea16e660e11b5e456ec640b0fe18b7251284459eb47e3ab3226e9a8bc52ccaba 5.68kB / 5.68kB                     0.0s
=> CANCELED [migrator base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:8.0@sha256:1d6ca86c35975c08bd63a066f190fb7b  0.2s
=> => resolve mcr.microsoft.com/dotnet/aspnet:8.0@sha256:1d6ca86c35975c08bd63a066f190fb7bd68fbc2d675d70b2728d458  0.1s
=> => sha256:25c31e01c3df304cdc33dde0ff5fa118dd09b544316bc245aad85cb9b56c3ff3 1.58kB / 1.58kB                     0.0s
=> => sha256:b785b5c118da9b26fdc1a29f4a0f5e402a5289da3c742458c0286c9b4b4235b9 2.72kB / 2.72kB                     0.0s
=> => sha256:1d6ca86c35975c08bd63a066f190fb7bd68fbc2d675d70b2728d458921743a24 1.08kB / 1.08kB                     0.0s
=> ERROR [sampleapp] load build context                                                                   0.1s
=> => transferring context: 28B                                                                                   0.0s
------
> [sampleapp] load build context:
------
failed to solve: changes out of order: ".git/HEAD" ""
```

### Reproduce

This is a bit complicated as it is an internal docker-compose file; but basically all it does is:

```
  sampleapp:
    image: sampleapp
    build:
      context: ../../
      dockerfile: ./sampleapp/Dockerfile
    container_name: sampleapp
    networks:
      - internal
    environment:
      - ConnectionStrings__DefaultDbConnection=${DB_CONNECTION_STRING}
    depends_on:
      mssql.init:
        condition: service_completed_successfully
```

Dockerfile is a standard file generated by Visual Studio for an ASP.NET project. Seems like COPY is the culprit?

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:24:09 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.418GiB
 Name: docker-desktop
 ID: 570cc2bf-ab77-4e4b-a00d-e7112e79c782
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

**Comment by thaJeztah** [comment] 2024-02-06 13:50
Thanks for reporting; this looks like a duplicate of 

- https://github.com/docker/compose/issues/11452
- https://github.com/docker/compose/issues/11421
- https://github.com/moby/moby/issues/47231

Which was a bug in docker compose, and a fix for that was included in docker compose [v2.24.5](https://github.com/docker/compose/releases/tag/v2.24.5), which is available on GitHub (and deb/rpm packages for Linux), and will be included in the upcoming Docker Desktop 4.27.3 patch release.


I'll ask @crazy-max to have a quick peek though, to confirm this specific case would be addressed as well (error is the same, but just in case there's a difference)

**Comment by crazy-max** [comment] 2024-02-06 13:56
This will be fixed in DD 4.27.2 that will ship latest compose. More info https://github.com/docker/compose/pull/11426

**Comment by crazy-max** [comment] 2024-02-06 13:58
@glours Not sure where this `server: error reading preface from client` line comes from in compose:

```
[+] Building 0.0s (0/0)  docker:default
2024/02/06 13:45:13 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 1.5s (7/23)                                                                                 docker:default
=> [sampleapp] load build definition from Dockerfile 
```

Don't recall of a report or encountering this in buildx.

**Comment by Makentosh** [comment] 2024-02-07 13:42
Docker Desktop 4.27.1 (136059) 
have the same problem

2024/02/07 15:35:17 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
2024/02/07 15:35:17 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
2024/02/07 15:35:17 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 1.8s (15/24)                                                                                docker:default
 => [vue internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 245B                                                                               0.0s

**Comment by rishabhbeni** [comment] 2024-02-10 17:07
I am using 25.0 version of docker compose and still facing this issue. I've tried few workarounds but nothing seems to work. I get the error everytime: 

 > [shopping.api internal] load build context:
------
failed to solve: changes out of order: ".git/HEAD" ""

**Comment by christophwille** [comment] 2024-02-10 17:26
4.27.2 works for me now

**Comment by crazy-max** [comment] 2024-02-11 09:23
Closing since it should be fixed with Docker Desktop 4.27.2 (Compose 2.24.5)

**Closed by crazy-max** 2024-02-11 09:23 UTC
Labels: area/builder, status/0-triage, kind/bug, area/builder/buildkit, version/25.0

**Comment by firehyperx** [comment] 2024-02-12 08:02
Hello, I've upgraded to DD 4.27.2 and the issues still persists for me.
![image](https://github.com/moby/moby/assets/23186892/bf906527-0777-4dd2-b72a-edc116ad262b)

**Comment by crazy-max** [comment] 2024-02-12 08:05
@firehyperx This doesn't look related. Can you show full logs please? Don't see the actual error message in your screenshot.

**Comment by firehyperx** [comment] 2024-02-12 08:07
@crazy-max Hey thank you for the reply. I get the error **http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed**.

Full logs are here:

PS C:\Users\aljazb\Desktop\GRnet\api-grnet\api-dev> docker-compose build web
2024/02/12 08:58:34 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
2024/02/12 08:58:34 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 1.8s (6/13)                                                                                                                                                                                                                                                            docker:default
 => [web internal] load build definition from Dockerfile                                                                                                                                                                                                                                      0.0s
 => => transferring dockerfile: 268B                                                                                                                                                                                                                                                          0.0s
 => [web internal] load metadata for docker.io/library/python:3.6-stretch                                                                                                                                                                                                                     0.5s
 => [web internal] load .dockerignore                                                                                                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                               0.0s
 => CACHED [web 1/9] FROM docker.io/library/python:3.6-stretch@sha256:654dd3f75f34c7075c118de1d7733613983140ab63bebdd2a5857e50b300924b                                                                                                                                                        0.0s
 => [web internal] load build context                                                                                                                                                                                                                                                         0.0s
 => => transferring context: 20.77kB                                                                                                                                                                                                                                                          0.0s
 => ERROR [web 2/9] RUN apt-get update                                                                                                                                                                                                                                                        1.2s
------
 > [web 2/9] RUN apt-get update:
0.346 Ign:1 http://deb.debian.org/debian stretch InRelease
0.351 Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
0.377 Ign:3 http://deb.debian.org/debian stretch-updates InRelease
0.397 Ign:4 http://security.debian.org/debian-security stretch/updates Release
0.410 Ign:5 http://deb.debian.org/debian stretch Release
0.441 Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
0.441 Ign:7 http://deb.debian.org/debian stretch-updates Release
0.474 Ign:8 http://deb.debian.org/debian stretch/main all Packages
0.479 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.505 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.517 Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
0.539 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.556 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.574 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.603 Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
0.604 Ign:8 http://deb.debian.org/debian stretch/main all Packages
0.640 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.642 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.672 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.680 Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
0.702 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.717 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.732 Ign:8 http://deb.debian.org/debian stretch/main all Packages
0.756 Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
0.762 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.792 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.800 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.834 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.837 Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
0.866 Ign:8 http://deb.debian.org/debian stretch/main all Packages
0.877 Err:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.877   404  Not Found
0.896 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.931 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.963 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.994 Ign:8 http://deb.debian.org/debian stretch/main all Packages
1.026 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
1.056 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
1.089 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
1.121 Ign:8 http://deb.debian.org/debian stretch/main all Packages
1.151 Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
1.151   404  Not Found
1.182 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
1.212 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
1.212   404  Not Found
1.216 Reading package lists...
1.223 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
1.223 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
1.223 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
1.223 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
1.223 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
1.223 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
1.223 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c apt-get update" did not complete successfully: exit code: 100

**Comment by crazy-max** [comment] 2024-02-12 08:19
This is not related to the original issue and doesn't seem to be the root cause of your actual issue when downloading packages:

```
1.223 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
1.223 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
1.223 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
```

Looks like debian stretch repo is not a thing anymore (probably because EOL for a couple of years now): http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages

You should bump to latest stable (bookworm).

> ```
> 2024/02/12 08:58:34 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
> 2024/02/12 08:58:34 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
> ```

Seems this output comes from compose. Can you report at https://github.com/docker/compose please? Thanks.
