### ISSUE TITLE
docker export &import error

### ISSUE THREAD

**Issue by ArmorHerO** [moby/moby#34150] opened 2017-07-18 07:36 UTC
**Description**

**Steps to reproduce the issue:**
1.docker export  example > example.tar
2.cat example.tar|docker import - example
3.docker run -tid example
 

**Describe the results you received:**
return err : msg="Handler for POST /v1.26/containers/create returned error: No command specified"
**Describe the results you expected:**
the container start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 50.93 GiB
Name: anloq-test
ID: OJJG:QKI5:RLTA:UPO2:UMVW:M4X3:CBNG:B35S:D6HZ:NXB4:LWSK:TRTS
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xuejipeng
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.0.122:5000
 127.0.0.0/8
Registry Mirrors:
 http://52dca062.m.daocloud.io
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):physical**

**Comment by thaJeztah** [comment] 2017-07-18 12:47
This is expected, but may need better documentation.

The `docker export` command only exports the containers filesystem (see https://docs.docker.com/engine/reference/commandline/export/); the container's _configuration_ (command to run, environment variables set, and other runtime options) are not exported.

When _importing_ the archive, an image is created with the filesystem you exported, but defaults for all configuration options.

You _can_ set specific options using the `--change` on `docker import` (see https://docs.docker.com/engine/reference/commandline/import/).

If you want to create an image of a container, and preserve its configuration, use `docker commit`.

Perhaps you're interested in opening an enhancement request in the https://github.com/docker/cli/issues issue tracker (where these reference docs live)?

I'm closing this issue because this is not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2017-07-18 12:47 UTC
Labels: version/1.13
