### ISSUE TITLE
Docker upgrade to v25 breaks kubernetes apiserver and core components

### ISSUE THREAD

**Issue by krishnakc1** [moby/moby#47215] opened 2024-01-25 10:38 UTC
### Description

Until docker-ce v24.0.7, kubernetes image components are successfully run by kubelet. With the upgrade of docker-ce to v25.0, kubelet cannot start up the main components of k8s with an error stating ID and size unknown

`
kubelet[21094]: E0125 07:46:51.645034   21094 remote_image.go:94] ImageStatus failed: Id or size of image "k8s.gcr.io/kube-proxy:v1.17.12" is not set
kubelet[21094]: E0125 07:46:51.645064   21094 kuberuntime_image.go:85] ImageStatus for image {"k8s.gcr.io/kube-proxy:v1.17.12"} failed: Id or size of image "k8s.gcr.io/kube-proxy:v1.17.12" is not set
E0125 07:46:51.645109   21094 kuberuntime_manager.go:809] container start failed: ImageInspectError: Failed to inspect image "k8s.gcr.io/kube-proxy:v1.17.12": Id or size of image "k8s.gcr.io/kube-proxy:v1.17.12" is not set
Error syncing pod 3ed55839-d24d-482a-a2ea-5fa52af9a07a ("kube-proxy-r6kxl_kube-system(3ed55839-d24d-482a-a2ea-5fa52af9a07a)"), skipping: failed to "StartContainer" for "kube-proxy" with ImageInspectError: "Failed to inspect image \"k8s.gcr.io/kube-proxy:v1.17.12\": Id or size of image \"k8s.gcr.io/kube-proxy:v1.17.12\" is not set"
`

kubernetes version(older one) 1.17, but I have seen this happening in latest version of k8s in 1.29 as well in k3s for some images

The change that is causing this problem is https://github.com/moby/moby/pull/45469

### Reproduce

Use an existing kubernetes cluster in bare metal. Upgrade docker-ce to 25.0.0 and wait for kubelet to start the containers.

### Expected behavior

kubelet starts up all the kubernetes components as pods

### docker version

```bash
lient: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:12:51 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:11:50 2024
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 3.10.0-1160.105.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.638GiB
 Name: be-bld-k8s-master-01
 ID: SHTP:ERBH:6FET:GEXX:FR3C:2R5G:ZNU4:GBAR:PXQ5:Z5UH:HVAC:IWE5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://bbr1lhaproxy.clear2pay.com:8080
 HTTPS Proxy: http://bbr1lhaproxy.clear2pay.com:8080
 No Proxy: .fnfis.com,.clear2pay.com,localhost,127.0.0.1,10.58.203.132,10.58.203.133
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Downgrading docker to 24.0.7 works but it is not an option

For some reasons, I cannot upgrade kubernetes to later versions but if there is a way to remediate this problem, it helps with the latest version of docker

**Comment by thaJeztah** [comment] 2024-01-25 12:36
See my comments on https://github.com/moby/moby/issues/47207#issuecomment-1909866259

> > ImageInspectError: Failed to inspect image "k8s.gcr.io/kube-proxy:v1.17.12": Id or size of image "k8s.gcr.io/kube-proxy:v1.17.12" is not set
> 
> (coming from https://github.com/kubernetes/kubernetes/blob/v1.17.12/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L809)
> 
> @krishnakc1 what API version is it using? That change should not change response for existing API versions (API versions before v1.44);
> 
> ```shell
> docker pull busybox:latest
> latest: Pulling from library/busybox
> 9ad63333ebc9: Pull complete
> Digest: sha256:6d9ac9237a84afe1516540f40a0fafdc86859b2141954b4d643af7066d598b74
> Status: Downloaded newer image for busybox:latest
> docker.io/library/busybox:latest
> ```
> 
> On API v1.43, the `VirtualSize` field is returned:
> 
> ```shell
> curl -s --unix-socket /var/run/docker.sock http://whatever/v1.43/images/busybox:latest/json | jq .VirtualSize
> 4261566
> ```
> 
> On API v1.44, the field is omitted;
> 
> ```shell
> curl -s --unix-socket /var/run/docker.sock http://whatever/v1.44/images/busybox:latest/json | jq .VirtualSize
> null
> ```
> 
> The `Size` field is present in both;
> 
> ```shell
> curl -s --unix-socket /var/run/docker.sock http://whatever/v1.43/images/busybox:latest/json | jq .Size
> 4261566
> 
> 
> curl -s --unix-socket /var/run/docker.sock http://whatever/v1.44/images/busybox:latest/json | jq .Size
> 4261566
> ```
> 
> Note that unversioned API calls have been deprecated since docker 1.13 in 2017 (originally meant to be removed in the v17.12 release, but that's not done yet); https://docs.docker.com/engine/deprecated/#api-calls-without-a-version





> Don't know if there's an option to manually configure kubelet to use a specific API version; if it's using the docker API client, then _possibly_ it can be overridden using the `DOCKER_API_VERSION` env-var, which then would have to be set for the kubelet process; see https://pkg.go.dev/github.com/docker/docker/client#EnvOverrideAPIVersion 
>
> But otherwise, this sounds like a bug in kubelet (not using API version-negotiation), or maybe newer versions of it do support that?

**Comment by thaJeztah** [comment] 2024-01-25 12:37
Also https://github.com/moby/moby/issues/47207#issuecomment-1910111771

> Looks like the change to move away from the deprecated `VirtualSize` in cri-dockerd was made just a few days ago: [Mirantis/cri-dockerd#300](https://github.com/Mirantis/cri-dockerd/pull/300)

**Comment by neersighted** [comment] 2024-02-05 13:58
Closing this for now as a duplicate of #47207, which tracks a cri-dockerd bug that requires a release.

**Closed by neersighted** 2024-02-05 13:58 UTC
Labels: kind/question, version/25.0
