### ISSUE TITLE
curl within default ingress not working

### ISSUE THREAD

**Issue by port22** [moby/moby#32880] opened 2017-04-27 06:52 UTC
I am new to swarm mode, attracted by the propagated feature of implemented hostname resolution, which is not working, but maybe I am doing something wrong.

It's easy to reproduce what I want.
Take a fresh installation like ubuntu 16.04 server or  
    `docker-machine create -d virtualbox`,  
init a single-node swarm, then start an nginx service and try to curl the service name from within the created container-replica (curl was post-installed):

    # docker swarm init --advertise-addr 10.0.2.15
    # docker service create --name loadbal -p 80:80 nginx
    # docker exec -ti loadbal.1.wgiron3dtha4ar1gbwt4xderk curl -I loadbal
    curl: (6) Could not resolve host: loadbal
    # docker exec -ti loadbal.1.wgiron3dtha4ar1gbwt4xderk curl -I http://10.255.0.6/
    curl: (7) Failed to connect to 10.255.0.6 port 80: Connection timed out
    # docker exec -ti loadbal.1.wgiron3dtha4ar1gbwt4xderk curl -I http://10.0.2.15/
    HTTP/1.1 200 OK

Well, curl'ing the swarm-manager-ip works, but from what I understood, a swarm service container should be able to resolve another service as a hostname by the name of the service, like "nginx", when they're on the same network (i am using the predefined ingress overlay network here, right?). 

Since you want to be able to obsolete ip addresses (because they 're dynamic -- we want it portable, right?), we want to start services with names like "php" and "apache" for addressing them in an nginx upstream configuration like:

    upstream php    {  server php;    }
    upstream apache {  server apache; }

I know of docker-nginx-proxy, but that's not an option.
We want to scale services horizontally and not wanting to touch the nginx config everytime we scale.

Here's the `network inspect ingress` (truncated):

    "Containers": {
                "cace73f30d37672fb831e8e37b7cac681361ca84868c5656503490648247b712": {
                    "Name": "loadbal.1.wgiron3dtha4ar1gbwt4xderk",
                    "EndpointID": "a2b10aa8e2e3e6e90150a1a28c7e297165ff7e82468a50d6d4a0f3702d9b7e2c",
                    "IPv4Address": "10.255.0.6/16"
                },
    "Peers": [
                {
                    "Name": "swarm-master-b25d443fc723",
                    "IP": "10.0.2.15"
                }

**Comment by cpuguy83** [comment] 2017-04-27 20:53
No the ingress network is special.
Try with a custom network.

**Comment by thaJeztah** [comment] 2017-04-27 21:05
Yes, the ingress network, by design, doesn't allow services that are attached to it to communicate with each other. To allow services to communicate, they need to share the same network, e.g.;


```bash
docker network create -d overlay mynet

docker service create --name foo --network=mynet nginx:alpine
docker service create --name bar --network=mynet nginx:alpine
```

I'll close this issue because I don't think there's a bug at hand here, but feel free to continue the discussion or ask if you need more info

**Closed by thaJeztah** 2017-04-27 21:05 UTC
Labels: area/swarm, status/more-info-needed

**Comment by port22** [comment] 2017-04-28 07:03
> they need to share the same network

That's not clear enough. My created services are indeed attached to the same network: the overlay network "ingress". Tried it with "--network ingress" too.

The documentation should be adjusted like  "Created services have to be attached to a new custom network". I did not read anywhere that services can not communicate via ingress, did I overlook it anywhere?
