### ISSUE TITLE
Capabilities are not preserved when using multi-stage builds

### ISSUE THREAD

**Issue by nrvnrvn** [moby/moby#38132] opened 2018-11-02 11:08 UTC
**Description**

I was chasing the goal of creating a minimal image (`FROM scratch`) with a single binary in it with `setcap cap_net_bind_service=+ep` set on it to be able to run it on behalf of an unpriviliged user with the ability to bind to a port under `1024`. The problem is that `COPY --from=0 /binary` does not preserve the capabilities.

**Steps to reproduce the issue:**
```
FROM debian

COPY binary /binary

RUN apt-get update &&\
    apt-get -y install libcap2-bin
RUN setcap cap_net_bind_service=+ep /binary

FROM scratch

COPY --from=0 /binary /binary

EXPOSE 42
ENTRYPOINT ["/binary"]
```
**Describe the results you received:**

```
$ docker run --user 777777:777777 b0349be0eb06
listen tcp :42: bind: permission denied
$
```

**Describe the results you expected:**

```
$ docker run --user 777777:777777 b0349be0eb06
Yay!
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Capabilities are implemented on Linux using extended attributes ([xattr(7)](
https://jlk.fjfi.cvut.cz/arch/manpages/man/xattr.7)) in the security namespace.

Extended attributes are copied automatically by `cp -a`, but some other programs require a special flag: `rsync -X`

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      true

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 12
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: NSSO:G273:ZCLQ:6PTC:PETU:AHC6:CWF5:5GF3:YZGO:KSIW:6SET:ADNP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 57
 System Time: 2018-11-02T11:05:32.308233495Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment] 2018-11-02 12:05
Could you try export DOCKER_BUILDKIT=1 ?

**Comment by nrvnrvn** [comment] 2018-11-02 12:40
@AkihiroSuda it works!

**Comment by thaJeztah** [comment] 2019-02-14 10:16
Looks like this is a duplicate of https://github.com/moby/moby/issues/35699, so let me close this one

**Closed by thaJeztah** 2019-02-14 10:16 UTC
Labels: area/builder, platform/desktop
