### ISSUE TITLE
Lock-free container proposal

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#30225] opened 2017-01-17 22:31 UTC
## Problem
The container object is used all over the code base as a place to store container configuration (both user config and config resolved by the daemon), runtime data.
Likewise the container's mutex (which is really the `State` object's mutex) is also exposed all over the place.

The container mutex is locked when both reading and writing to the container (as expected). The mutex is also locked during certain container operations. Because of this, reading and writing to the container object is very much tied to typically very slow operations, and as we've found operations that tend to be buggy (see netlink failures). This has led to a number of cases causing deadlocks.

## Goal
Issues with a container should never prevent a user from querying the engine in any way, including the problem container itself.

## Proposal
Make the container a lock-free object.
Swamkit already has a really nice model for this for storing each of it's object types using github.com/hashicorp/go-memdb. This same model should work for containers... see https://github.com/docker/swarmkit/tree/master/manager/state/store
This provides for indexing, filtering, partial matching (can drop usage of truncindex), and change notifications.

Essentially this means instead of passing around a single pointer object that each function reads from/writes to, we make (deep) copies. The object database contains the single source of truth, anything that needs to modify the container will need to modify it by committing changes back to the object store. The container object itself should not require any mutex since each object would only have 1 reader or writer at a time.

Because we'll be passing around copies, we need to make sure there is no "live" state being copied... for instance https://github.com/docker/docker/blob/f19a293dd741583c66001799435f784f2af455e0/container/state.go#L32... or for that matter https://github.com/docker/docker/blob/f19a293dd741583c66001799435f784f2af455e0/container/state.go#L18

Work to be done:

1. (#28483) Move "live" state off the container object (or at least contain it)
2. Implement deep copy support for the container object and each of the objects it uses.
3. Replace `MemoryStore` with go-memdb object store
    - Also requires replacing exec store
    - Needs to implement versioning on the container data (does not need to persist)
    - Implement notifications for changes to container state
4. Add locking (per ID) at the container manager level (currently Daemon) to ensure that stateful actions against the container (start/stop/pause etc) are synchronized.

You can see a POC form of this here: https://github.com/docker/docker/compare/master...cpuguy83:container_memdb

For step 1, this is implemented in the mentioned PR.

Step 2 is a little tricky, I do have a package to handle this (https://github.com/cpuguy83/go-generate/tree/master/deepcopy), but would prefer to use swarmkit's deep copy (generated from protobuf)... this is tricky because container uses so many different types and it may be difficult to force them to use protobufs.

**Comment by tonistiigi** [comment] 2017-01-18 01:03
@aaronlehmann What's your thoughts on this as you've worked with swarmkit/store a lot?

To me this seems bit unnecessarily complicated. I don't think the main reasons this pattern was used in swarmkit apply in here. The indexing support is clean but our use case is very simple and no way a performance/maintainance problem.

The main reasons for the concurrency issues in daemon pkg are that we lock everything for a long period in startup and cleanup instead of atomically changing states. We also do not have a safe way to switch between or interrupt states. The issue isn't only about the contention between list and update instructions, we have lots of unsafe api calls and the reason for them is this same global container lock(in many cases we just don't call it because it would deadlock or block ps). We need starting, stopping(and probably reserved) state and a way to interrupt running state to make it safe. If this is not solved we will just turn the data races to a logical issues. The public state could be snapshotted and behind a synchronization control but because the fields that can be changed are very limited and behind a simple struct I don't know if we need so generic solution with huge deepcopy.

**Comment by aaronlehmann** [comment] 2017-01-18 01:09
First some comments on the code:

- I think you need a lock around `Update`, as swarmkit has. Otherwise write transactions can happen concurrently, and the last one to call `Commit` will win, overwriting the other's data. Think of `Txn` as returning a copy-on-write snapshot. You can make changes to that snapshot without affecting the live data, and then calling `Commit` swaps it into place.

- I'm not sure whether `Batch` is useful in this context. In swarmkit we use it to break up long iterated updates that would otherwise block raft writes for a long time.

I'll take a look now and see if I think go-memdb is appropriate for this application.

**Comment by cpuguy83** [comment] 2017-01-18 01:12
Yes, originally implemented batch to handle specific cases in engine (see `ApplyAll`), but indeed it turned out to not be useful and I wouldn't be using it.

**Comment by aaronlehmann** [comment] 2017-01-18 01:22
The deep copy stuff is kind of ugly :(

Unfortunately I don't have a good sense of the locking challenges around container objects and whether the complexity of switching to this copy-on-write, transactional model is justified.

**Comment by stevvooe** [comment] 2017-01-18 02:19
@cpuguy83 The key to this is the transactional interface in swarmkit. It makes the scope of a modification much more clear and allows identifying long-running or runaway transactions. `bolt` provides an excellent model for this. I would avoid `Batch`, as that is really to deal with the long round trip times that may come with a raft transaction. Albeit, this can be a nice tool if you need a bunch of "mini-transactions". It can be abused in the hands of inexperience.

That said, there may be some exploration into a kind of "reactor" (or even multi-reactor) pattern, where operations are dispatched and queued from the central daemon thread. This is good for models that need to take a "pre-lock", do something or fail, then register the result permanently. https://dave.cheney.net/2016/11/13/do-not-fear-first-class-functions and there is some application in the swarmkit agent, although I didn't collect it into a pattern (there is probably a pattern there but every operation was slightly different for the use case).

I'd also recommend avoiding autogenerated `deepcopy` for a bespoke implementation. It is a lot easier to maintain and much easier to debug when things go sideways. You can see https://github.com/docker/swarmkit/pull/1763 which attempts to address some of our problems.

I would think the first step would be to clarify what is on disk vs. "live". Centralizing object storage around `cznic/ql` or `boltdb` would be instrumental in defining what the actual disk state should be.

On the whole, I think this is a great idea for docker.

**Comment by AkihiroSuda** [comment] 2017-06-28 00:30
https://github.com/moby/moby/issues/31273 was merged.
can we close this?

**Comment by AkihiroSuda** [comment] 2017-08-07 06:06
ping @cpuguy83

**Comment by AkihiroSuda** [comment] 2019-01-17 08:37
ping @cpennington @fabiokung Can we close this issue?

**Closed by AkihiroSuda** 2019-01-17 08:37 UTC
Labels: area/daemon, kind/enhancement
