### ISSUE TITLE
docker swarm leave doesn't unregister from swarm

### ISSUE THREAD

**Issue by chrisbecke** [moby/moby#46382] opened 2023-08-31 10:13 UTC
### Description

When I execute `docker swarm leave` on a healthy worker node, the node detaches from the swarm. However, querying the node list from a manager still shows the node.

### Reproduce

`compose.yml`
```yaml
volumes:
  certs:

services:
  manager:
    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: ''
    privileged: true
    deploy:
      replicas: ${MANAGERS-1}
    volumes:
    - certs:/certs
  
  worker:
    image: docker:dind
    privileged: true
    deploy:
      replicas: ${WORKERS-3}
    volumes:
    - certs:/certs
```

1. `docker compose up`
2. `docker compose exec manager docker swarm init`
3. `docker compose exec worker docker swarm join --token ...`
4. `docker compose exec --index 2 worker docker swarm join --token ...`
5. `docker compose exec --index 3 worker docker swarm join --token ...`
6. `docker compose exec worker docker swarm leave`
7. `docker compose exec manager docker node ls`

```bash
❯ docker compose exec manager docker node ls
ID                            HOSTNAME       STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
ftao2bz8vk657mzh2vh9sj0cr     0e8326a651a9   Down      Active                          24.0.5
sialrszxcxctwwc2m40r0edzp *   15bffd3bc518   Ready     Active         Leader           24.0.5
yjw15e0lr1et2h8vpc1wew7dn     a64749486658   Ready     Active                          24.0.5
r1nibjhu4gcy7xv9del6nnday     db55c040dd10   Ready     Active                          24.0.5
```

### Expected behavior

The logs from the `docker compose up` terminal show that all nodes receive multiple messages that the node has left. I expect `docker node ls` on the manager node to no longer show the departed node.

i.e. instead of seeing a Down node, I expect to see this:
```bash
❯ docker compose exec manager docker node ls
ID                            HOSTNAME       STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
sialrszxcxctwwc2m40r0edzp *   15bffd3bc518   Ready     Active         Leader           24.0.5
yjw15e0lr1et2h8vpc1wew7dn     a64749486658   Ready     Active                          24.0.5
r1nibjhu4gcy7xv9del6nnday     db55c040dd10   Ready     Active                          24.0.5
```

### docker version

```bash
❯ docker compose exec manager docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:34:32 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:56 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
❯ docker compose exec manager docker info   
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.3
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: sialrszxcxctwwc2m40r0edzp
  Is Manager: true
  ClusterID: i4du6nagk1tt5bdyaico4p9jy
  Managers: 1
  Nodes: 4
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.19.0.2
  Manager Addresses:
   172.19.0.2:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Alpine Linux v3.18 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.64GiB
 Name: 15bffd3bc518
 ID: 3c74a212-8c2b-4b75-adf2-1f58a6bda88c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment] 2023-08-31 12:40
Ah, yes, so this is the expected behavior, and it's mentioned in the docs; https://docs.docker.com/engine/reference/commandline/swarm_leave/

> The node will still appear in the node list, and marked as down. It no longer affects swarm operation, but a long list of down nodes can clutter the node list. To remove an inactive node from the list, use the node rm command.

Perhaps there's other parts of the docs that describe it as well (if not, then probably some information needs to be added).

To explain "why"; in a swarm cluster, only _managers_ can make changes to cluster state. When joining a node, the node requires a join-token to join the cluster, but after that, it has no permissions to alter state of the cluster.

When you `docker swarm leave` from a worker node, the node removes its local state of the cluster, and disconnects, but from the manager's perspective, the node is still part of the cluster (but "behaving badly"). This approach also allows monitoring state of nodes overall; a node could be offline for other reasons, which may need intervention.

To _remove_ the node from the lister, you need `docker node rm` (https://docs.docker.com/engine/reference/commandline/node_rm/), which must be executed from a manager node (as that changes the state of the cluster).

**Comment by thaJeztah** [comment] 2023-08-31 12:42
I'll close this ticket, as it's not a bug, but feel free to continue the conversation!

**Closed by thaJeztah** 2023-08-31 12:42 UTC
Labels: kind/question, area/docs, area/swarm

**Comment by chrisbecke** [comment] 2023-08-31 15:52
> To explain "why"; in a swarm cluster, only managers can make changes to cluster state. 

I'd argue this is not true. The node initially added itself to the cluster. There should - if just for symmetry - be a way for a node to cleanly remove itself.

Take the example of using Auto Scaling groups in the cloud to provision and deprovision swarm nodes dynamically. A node can be passed enough parameters to join a swarm successfully on their first boot. but in response to its deprovision event cannot clean themselves up.

**Comment by neersighted** [comment] 2023-09-01 16:10
I seemed to remember this was intentional, and looking at the code, it clearly is; that being said, it seems possible that a worker could notify the manager about a graceful leave... cc @dperny

If this is something useful to consider, we should probably move this to moby/swarmkit.

**Comment by thaJeztah** [comment] 2023-09-01 20:42
Yes, there's definitely options to improve things for automated setups; here's some links to prior discussions;

- one-time join-tokens (allow the token to be distributed to a node, but make sure it cannot be reused); https://github.com/moby/moby/pull/24770#issuecomment-240880401
- similar: token expiry; https://github.com/moby/moby/issues/29489
- and this was more of a "blanket" issue for this https://github.com/moby/moby/issues/26743
- https://github.com/moby/moby/issues/24103

w.r.t. workers allowing themselves to be removed; _perhaps_ this could be done similarly with a "leave token"; having access to that token would allow a worker to make a (one time) change to it's state in the cluster (i.e. "leave")

Then again, the question is if scaling _should_ be left to the nodes, or remain a responsibility of the managers; the general design of swarm is to treat workers as "unprivileged", so that a compromised worker cannot take control of the cluster (it may compromise the worker-node _itself_, but can't take over the entire cluster.

A different option for this could be to have the ability to have a way to integrate hooks into the manager workflow, allowing the manager to remove the worker from the swarm cluster, after which it can remove the machine from the cluster. (or vice versa). This would allow for the manager to add more workers when scaling services (and if it fails to schedule loads due to insufficient resources available in the cluster).
