### ISSUE TITLE
Pushed image had 0 B in tags tab

### ISSUE THREAD

**Issue by Mykolaichenko** [moby/moby#34818] opened 2017-09-12 08:56 UTC
**Description**

After pushing to private Docker registry based on hub.docker.com pull is not working. I think because in tags tab it show that layer had 0 B. 

**Steps to reproduce the issue:**
1. push image to private registry on docker hub 
2. pull this image 
3. error shown 

**Describe the results you received:**
```
Olegs-MacBook-Pro:devops-repo mukolaich$ sudo docker push blah/operations:firstimagepush
The push refers to a repository [docker.io/blah/operations]
a8335887ce67: Pushed 
da15840837f4: Pushed 
d06a37a890ae: Pushed 
2129167a11e8: Pushed 
970cd93c8668: Pushed 
0e4384a78519: Pushed 
19df2652bcca: Pushed 
ab994d815712: Pushed 
afe4d6aca423: Pushed 
beefb269d809: Pushed 
d67147469f34: Pushed 
cc60afbae362: Pushed 
a71ea5da57b2: Pushed 
54fd3415c465: Pushed 
d1b99036d3a6: Pushed 
5bb046ac7d57: Pushed 
a09947e71dc0: Pushed 
9c42c2077cde: Pushed 
625c7a2a783b: Pushed 
25e0901a71b8: Pushed 
8aa4fcad5eeb: Pushed 
firstimagepush: digest: sha256:47da3a83c47258c32a7e89c69827e6d0cece9be0631c648557deb37a7e402ff8 size: 4711
```
```
Olegs-MacBook-Pro:devops-repo mukolaich$ docker pull blah/operations:firstimagepush
Error response from daemon: manifest for blah/operations:firstimagepush not found
Olegs-MacBook-Pro:devops-repo mukolaich$ docker pull blah/operations
Using default tag: latest
Error response from daemon: manifest for blah/operations:latest not found
Olegs-MacBook-Pro:devops-repo mukolaich$ 
```

**Describe the results you expected:**
successful pull 

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by Mykolaichenko** [comment] 2017-09-14 08:56
It here any update or somebody with same problem?

**Comment by thaJeztah** [comment] 2017-09-14 09:40
You mention the repository is private; could it be you reached the maximum number of private repositories in your plan? I seem to recall that in that case pushing works, but the pushed image is not accessible.

If you log in to Docker Hub, you should see "Private Repositories:Using X of Y" at the top on your dashboard.

**Comment by Mykolaichenko** [comment] 2017-09-15 18:19
@thaJeztah yep, thats is. Thanks for help.

**Comment by Mykolaichenko** [comment] 2017-09-15 18:23
@thaJeztah in my opinion it may be more understandable error; just not only simple `manifest not found`
for me it looks like something goes wrong, and only magic there) many thanks

**Comment by thaJeztah** [comment] 2017-09-15 21:29
The "manifest not found" is the same error that's returned for non existing repositories; that's on purpose to prevent people from discovering names of private repositories (e.g. GitHub does the same if you try to access a private repository that you don't have access to)

I did bring this issue up with the Docker Hub team, and asked if it would be possible to return an error if you try to push an image and you reached your quota; currently that wasn't possible, but I'll keep an eye on possible improvements there.

Let me close this issue, because this is resolved and not a bug in the code maintained in this repository, but feel free to continue the conversation

**Closed by thaJeztah** 2017-09-15 21:29 UTC
Labels: area/distribution, version/17.06
