### ISSUE TITLE
Docker ignores --log-opt (1.12.6)

### ISSUE THREAD

**Issue by yamnicz3k** [moby/moby#31515] opened 2017-03-03 13:41 UTC
**Description**
For _json-file_ logging driver options are ignored.

**Steps to reproduce the issue:**
1. Install RHEL7.3
2. Configure docker to use _json-file_ logging driver
3. Runs container with _--log-opt max-size=100k --log-opt max-file=2_

**Describe the results you received:**
```
# ls -l
total 1055824
-rw-r----- 1 root root 1081127027 Mar  3 14:17 25c24257d4713a6f5fb21dc063d6bc62a15571f643b2ec10943b2352468b800f-json.log
-rw-rw-rw- 1 root root       4570 Mar  3 12:46 config.v2.json
-rw-rw-rw- 1 root root       1117 Mar  3 12:46 hostconfig.json
-rw-r--r-- 1 root root         13 Mar  3 12:46 hostname
-rw-r--r-- 1 root root        223 Mar  3 12:46 hosts
-rw-r--r-- 1 root root         59 Mar  3 12:46 resolv.conf
-rw-r--r-- 1 root root         71 Mar  3 12:46 resolv.conf.hash
drwxrwxrwt 2 root root         40 Mar  3 12:46 shm
```

**Describe the results you expected:**
100k logfile size. :)

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 25
 Running: 11
 Paused: 0
 Stopped: 14
Images: 57
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: vg1-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 11.95 GB
 Data Space Total: 42.74 GB
 Data Space Available: 30.78 GB
 Metadata Space Used: 3.912 MB
 Metadata Space Total: 1.065 GB
 Metadata Space Available: 1.061 GB
 Thin Pool Minimum Free Space: 4.273 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: active
 NodeID: dad1q44mvuh8thifz6vxiv0nj
 Is Manager: true
 ClusterID: 1bv8swnokj5rc93jd4ipyr2aq
 Managers: 5
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.11.12.15
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.42 GiB
Name: app-04.somedomain.com
ID: 2MNJ:IYA2:KAXC:O4Q2:P27G:YVJV:VZRF:SS2W:7IGB:2LBE:OYY6:O2LC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 235
 Goroutines: 19736
 System Time: 2017-03-03T14:25:06.938459812+01:00
 EventsListeners: 9
Registry: https://index.docker.io/v1/
Insecure Registries:
 10.11.12.13:5000
 10.11.12.13:5043
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware

**Comment by thaJeztah** [comment] 2017-03-03 14:33
I'm not able to reproduce this;

```
ls -lha /var/lib/docker/containers/f8a116e0f337c75c33317d273344db7d46a5e48480e435066adfe265f3efff5a           2017-03-03 14:31:53

total 40
drwx------    3 root     root        4.0K Mar  3 14:31 .
drwx------    3 root     root        4.0K Mar  3 14:31 ..
-rw-rw-rw-    1 root     root        2.6K Mar  3 14:31 config.v2.json
-r--------    1 root     root         991 Mar  3 14:31 f8a116e0f337c75c33317d273344db7d46a5e48480e435066adfe265f3efff5a-json.log
-rw-r-----    1 root     root        1.0K Mar  3 14:31 f8a116e0f337c75c33317d273344db7d46a5e48480e435066adfe265f3efff5a-json.log.1
-rw-rw-rw-    1 root     root        1.1K Mar  3 14:31 hostconfig.json
-rw-r--r--    1 root     root          13 Mar  3 14:31 hostname
-rw-r--r--    1 root     root         174 Mar  3 14:31 hosts
-rw-r--r--    1 root     root         170 Mar  3 14:31 resolv.conf
-rw-r--r--    1 root     root          71 Mar  3 14:31 resolv.conf.hash
drwxrwxrwt    2 root     root          40 Mar  3 14:31 shm
```


```
docker inspect --format '{{ json .HostConfig.LogConfig }}' f8a116e0f337c75c33317d273344db7d46a5e48480e435066adfe265f3efff5a
{"Type":"json-file","Config":{"max-file":"2","max-size":"1k"}}
```

If you inspect the container, what does it show? (see the above command)

**Comment by magibney** [comment] 2017-08-08 16:37
Encountered this (or similar) problem when specifying `--log-opt max-size=50m` when creating services via `docker service create`. Config options worked fine when specified with `docker run` for individual containers. 

As a workaround, explicitly specifying `--log-driver json-file` in `docker service create` caused `--log-opt` configuration options to be registered correctly with the service and passed along to container tasks.

**Comment by thaJeztah** [comment] 2017-08-08 16:57
@magibney could you open a new issue for that? I'm able to reproduce that, but it may be it's by design (i.e., the default logging driver is taken from the daemon configuration; in a swarm situation, each node may be configured different, and the provided `--log-opt` may not be valid for the default logging driver on that node).

_if_ it's by design, the UX for it should definitely be improved though 👍

**Comment by thaJeztah** [comment] 2017-08-08 16:58
Let me close this issue, because I'm not able to reproduce the original issue being reported here, and didn't hear back from the reporter

**Closed by thaJeztah** 2017-08-08 16:58 UTC
Labels: area/logging, kind/bug, status/more-info-needed, version/1.12

**Comment by Asher-Shoshan** [comment] 2018-01-03 17:01
I'm having the exact same issue.  Logs are not rotated.  i.e log-opt in daemon.json is not respected.
Running Docker 1.12.6 + Kubernetes 1.8 on top.

**Comment by nelsonfassis** [comment] 2018-01-19 22:40
@thaJeztah can we reopen this issue?
I am also having it. I have a cluster where docker logs to json just fine, same docker version and same docker daemon.json. 
On my other cluster, even after specifying on docker daemon.json log-driver as json-file, when I get docker info | grep 'Logging Driver' it still shows as Journald and it prevents me from working with my logs the way I need.

**Comment by thaJeztah** [comment] 2018-01-20 01:05
@nelsonfassis Docker 1.12.6 has reached end of life in March of last year, and is no longer maintained. This issue has already been fixed in more recent versions of docker, so there's nothing to reopen
