### ISSUE TITLE
Not able to send SIGQUIT signal to application running inside docker container

### ISSUE THREAD

**Issue by kunaldas1** [moby/moby#37007] opened 2018-05-07 05:32 UTC
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
I am running a fastcgi server application inside docker container and trying to send SIGQUIT signal to to the application for gracefully terminate.
But the signal is not coming to fastcgi application inside container.
Can anybody please give me the steps to send SIGQUIT signal to  fastcgi application running inside container

**Steps to reproduce the issue:**
1. Running the container using
    ```
    $ run -it --stop-signal SIGQUIT --name test fcgi_image
    ```

2. Trying to get the SIGQUIT signal by below command.

    ```
    $ docker exec test kill -SIGQUIT 1
    ```

**Describe the results you received:**

SIGQUIT signal is not coming to fastcgi application running inside docker container 

**Describe the results you expected:**
SIGQUIT signal should get forwarded to the fastcgi application running inside docker container

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703GiB
Name: localhost.localdomain
ID: T6CG:UYO4:PTQO:B43D:VVRI:I54V:EXWL:QMEU:MIK2:CAOT:5G2H:YNCV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-05-07 12:14
How is the container's main process started? Is the `fast_cgi` process the container's main process, or is it started through a shell? Note that `PID 1` on Linux is special, and not all processes will handle signals when running as PID 1; see the [run reference documentation](https://docs.docker.com/engine/reference/run/#foreground);

> Note: A process running as PID 1 inside a container is treated specially by Linux: it ignores any signal with the default action. So, the process will not terminate on `SIGINT` or `SIGTERM` unless it is coded to do so.

If you use a shell-script to start your container's main process, make sure to `exec` the process at the end, so that it becomes the main process; If you cannot do that, and _must_ use a shell as main process in the container, the Dockerfile reference also has some examples how to trap signals; https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example


I'm not able to reproduce this using an `nginx:alpine` container;

Using `docker exec` to stop the process:

```bash
docker run -d --stop-signal=SIGQUIT --name test nginx:alpine
docker exec test kill -SIGQUIT 1

docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
a720c544562a        nginx:alpine        "nginx -g 'daemon of…"   10 seconds ago      Exited (0) 2 seconds ago                       test
```

Or `docker stop` to signal the process through docker:

```bash
docker run -d --stop-signal=SIGQUIT --name test nginx:alpine
docker stop test
```

```bash
tail /var/log/messages

May  7 11:57:46 localhost dockerd: time="2018-05-07T11:57:46.311038141Z" level=debug msg="Calling GET /_ping"
May  7 11:57:46 localhost dockerd: time="2018-05-07T11:57:46.312141805Z" level=debug msg="Calling POST /v1.37/containers/test/stop"
May  7 11:57:46 localhost dockerd: time="2018-05-07T11:57:46.312215868Z" level=debug msg="Sending kill signal 3 to container cf4281274f600042c2aa716783e760f92852482180143dfaf91740311606d867"
May  7 11:57:46 localhost dockerd: time="2018-05-07T11:57:46Z" level=debug msg="event published" module="containerd/events" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
May  7 11:57:46 localhost dockerd: time="2018-05-07T11:57:46.357837611Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/exit
May  7 11:57:46 localhost dockerd: time="2018-05-07T11:57:46Z" level=info msg="shim reaped" id=cf4281274f600042c2aa716783e760f92852482180143dfaf91740311606d867 module="containerd/tasks"
May  7 11:57:46 localhost dockerd: time="2018-05-07T11:57:46Z" level=debug msg="event published" module="containerd/tasks" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
```

Also note that:

- Docker CE 17.06 is a very old version of Docker that reached End Of Life in September of last year, and is no longer maintained
- Based on your kernel version (`3.10.0-229.14.1.el7.x86_64`) you seem to be running an obsolete version of CentOS 7. CentOS uses a rolling release model, which means that only the _current_ version of CentOS is supported (i.e., when CentOS 7.2 was released, CentOS 7.1 became obsolete, and so on)
- You're running the `overlay` storage driver on an XFS filesystem without `d_type` support; this combination is problematic, and can cause problems

I highly recommend to update both your distro and docker version to a currently supported version, and to either reformat the filesystem, or switch to a different storage driver.


Based on the above, I suspect this is an issue with the image you're using; given that the docker version you're running, and the distro version are no longer supported, I'll close this issue, but feel free to continue the conversation.

**Closed by thaJeztah** 2018-05-07 12:14 UTC
Labels: version/17.06
