### ISSUE TITLE
CMD command with changed SHELL not working

### ISSUE THREAD

**Issue by omron93** [moby/moby#35832] opened 2017-12-19 10:52 UTC
**Description**

When default shell is changed using `SHELL` instruction in one image, shell version of `CMD` command is not working in different image which is based on it.

**Steps to reproduce the issue:**
1. Two Dockerfiles
```bash
$ cat Dockerfile
FROM centos:centos7
SHELL ["/usr/bin/bash", "-c"]
RUN echo "echo 'Default cmd!'" > /usr/bin/default-cmd && chmod a+x /usr/bin/default-cmd
ENV PREFIX=/usr/bin/
CMD ["/usr/bin/ls"]
$ cat Dockerfile.2 
FROM myimage
CMD $STI_SCRIPTS_PATH/default-cmd
```
2. `$ docker build -t myimage -f Dockerfile . && docker build -t myimage2 -f Dockerfile.2 .`
3. `$ docker inspect myimage2`

**Describe the results you received:**

`docker inspect myimage2` contains in `Config` section:
```
"Cmd": [
                "/usr/bin/bash",
                "-c",
                "#(nop) "
            ],
```

**Describe the results you expected:**

`docker inspect myimage2` contains in `Config` section:
```
"Cmd": [
                "/usr/bin/bash",
                "-c",
                " $STI_SCRIPTS_PATH/default-cmd"
            ],
```

I get this result when `SHELL` command is removed from `Dockerfile`.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens only when shell CMD is used in image based on image which sets the default SHELL. If `CMD $STI_SCRIPTS_PATH/default-cmd` is in `Dockerfile` (from the example) it is working fine.

**Output of `docker version`:**

```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-7.gitae7d637.fc25.x86_64
 Go version:      go1.7.6
 Git commit:      ae7d637/1.12.6
 Built:           Tue Jul 18 16:18:12 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-7.gitae7d637.fc25.x86_64
 Go version:      go1.7.6
 Git commit:      ae7d637/1.12.6
 Built:           Tue Jul 18 16:18:12 2017
 OS/Arch:         linux/amd64

```

**Output of `docker info`:**

```
Containers: 275
 Running: 0
 Paused: 0
 Stopped: 275
Images: 367
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:4-917507-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 31.98 GB
 Data Space Total: 107.4 GB
 Data Space Available: 4.922 GB
 Metadata Space Used: 76.39 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.071 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /mnt/second/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /mnt/second/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp selinux
Kernel Version: 4.13.16-100.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 11.43 GiB
Name: localhost.localdomain
ID: NDFK:VOWZ:PILM:626J:Y23Y:J63I:YPFN:ZHQY:U6OK:KXOL:TWSP:5YA4
Docker Root Dir: /mnt/second/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.centos.org/v1/
Insecure Registries:
 registry.centos.org
 172.30.0.0/16
 127.0.0.0/8
Registries: registry.centos.org (insecure), brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888 (secure), registry.access.redhat.com (secure), registry.fedoraproject.org (secure), docker.io (secure)
```

**Comment by thaJeztah** [comment] 2017-12-19 11:54
Looks like you're running an unofficial Docker version (looks like you're running the Red Hat fork of Docker, which contains a lot of modifications). Also Docker 1.12 reached end of life a long time ago and is no longer maintained.

This issue no longer reproduces on current versions of docker;

Build image `myimage` and `myimage2`:

```bash
$ docker build -t myimage -<<'EOF'
FROM centos:centos7
SHELL ["/usr/bin/bash", "-c"]
RUN echo "echo 'Default cmd!'" > /usr/bin/default-cmd && chmod a+x /usr/bin/default-cmd
ENV PREFIX=/usr/bin/
CMD ["/usr/bin/ls"]
EOF


$ docker build -t myimage2 -<<'EOF'
FROM myimage
CMD $STI_SCRIPTS_PATH/default-cmd
EOF
```

Verify that the CMD correctly uses `/usr/bin/bash`, and the `CMD` from the last Dockerfile is set;

```bash
$ docker inspect --format '{{json .Config.Cmd }}'  myimage2
["/usr/bin/bash","-c","$STI_SCRIPTS_PATH/default-cmd"]
```

I recommend installing a current version of the official Docker packages to resolve the problem; https://docs.docker.com/engine/installation/linux/docker-ce/fedora/

I'm closing this issue because this is resolved, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-19 11:54 UTC
Labels: area/builder, version/1.12

**Comment by omron93** [comment] 2017-12-20 08:53
Thanks for quick answer and explanation of the problem.
