### ISSUE TITLE
COPY does not respect WORKDIR in previous stages

### ISSUE THREAD

**Issue by vlk-charles** [moby/moby#35650] opened 2017-11-30 11:28 UTC
**Description**

Not sure if this is intended or a bug, but when I `COPY --from`, the `<src>` path is always relative to `/`. This seems counter-intuitive.

**Steps to reproduce the issue:**
1. Save the following `Dockerfile`:
```
FROM alpine AS stage1
RUN echo 'This is in /.' >somefile
WORKDIR /root
RUN echo 'This is in WORKDIR.' >somefile

FROM alpine
COPY --from=stage1 somefile .
```
2. `docker build -t bugtest .`
3. `docker run --rm bugtest cat somefile`

**Describe the results you received:**
```
This is in /.
```

**Describe the results you expected:**
```
This is in WORKDIR.
```

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 184
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-58-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 25.51GiB
Name: ubuntu1
ID: ZSC7:3VAV:U3JD:XIUN:OLEV:HS2T:GTYX:RE6E:WQHC:4CDB:WGWI:IQKF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical host.

**Comment by thaJeztah** [comment] 2017-11-30 15:54
Yes, this is the expected behavior; the `FROM alpine` line starts a new build stage, and starts with a clean `alpine` image (thus not inheriting the `WORKDIR` from the previous stage.

I believe there was a bug at some point where the workdir wasn't reset; perhaps you ran into that before, and thought it was the correct behavior?

I'll close this issue, because this works as designed, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-30 15:54 UTC
Labels: area/builder, version/17.09

**Comment by vlk-charles** [comment] 2017-12-01 00:41
You may have misunderstood me. I did not mean that the second image should inherit the `WORKDIR`. What I was saying is that when you use `COPY --from=stage1`, you can specify a relative source path and that the path should be relative to `stage1`'s `WORKDIR`, as that is the image that is being copied from. In other words, I would expect the source path to be relative to `stage1`'s `WORKDIR` and the destination path to the current stage's `WORKDIR`.

**Comment by vlk-charles** [comment] 2017-12-01 00:47
I think the example above shows it quite well. `stage1` creates two files, `/somefile` and `/root/somefile`, and the `WORKDIR` is set to `/root` . Then `somefile` is copied from this image, which resolves to the former file rather than the latter, independently of `WORKDIR`.

**Comment by vlk-charles** [comment] 2017-12-04 17:37
I realized one thing today. `COPY`'s behavior is not consistent with that of `docker cp`. `docker cp` does not take `WORKDIR` into account at all, which [the documentation](https://docs.docker.com/engine/reference/commandline/cp/) mentions correctly. That however means that `COPY` and `docker cp` behave the same for the source path but differently for the destination path.

**Comment by thaJeztah** [comment] 2017-12-04 20:42
In general I'm not fond of preserving the `WORKDIR`, and making `COPY --from` know about the `WORKDIR` that happened to be set in the previous stage (or image) that was copied from (and the complexity that may add to that). It doesn't feel like a big burden to specify an absolute path to copy from, instead of a relative path, and relying on the `WORKDIR` of the other image; just my 0.02c though.

**Comment by vlk-charles** [comment] 2017-12-05 10:45
Do you think something should be done about the inconsistency between `COPY` and `docker cp`? Why would one copy to `WORKDIR` and the other to `/`? `RUN` and `docker run` both execute in `WORKDIR`.

**Comment by thaJeztah** [comment] 2017-12-06 04:16
While I've never been a "fan" of `COPY` following `WORKDIR`, it does make sense in the Dockerfile;

```Dockerfile
RUN something in the current workdir (default `/`)
COPY something to the current work-dir
WORKDIR (change the workdir for steps after this)
RUN something in the current workdir
COPY something to the current work-dir
```

`docker cp` is just copying from the container's filesystem, not part of the build, and does not require the container to be running; changing this to follow the `WORKDIR` would be a huge breaking change.

`RUN` is not the equivalent to `docker run`. `docker run` is a combination of `docker create` and `docker start`, and starts the container with the configuration that was set in the image (which includes the `ENTRYPOINT`, `CMD`, and `WORKDIR` that's configured.

**Comment by vlk-charles** [comment] 2017-12-06 12:34
So since this looks like it will keep working the way it does now, I will turn my eyes to the documentation. I think the [documentation for `WORKDIR`](https://docs.docker.com/engine/reference/builder/#workdir) could be improved. Right now it says:

"The `WORKDIR` instruction sets the working directory for any `RUN`, `CMD`, `ENTRYPOINT`, `COPY` and `ADD` instructions that follow it in the `Dockerfile`."

I would argue that `WORKDIR` does not affect `CMD`/`ENTRYPOINT`. `CMD` always does the same thing no matter if there are any `WORKDIR`s set before it. What `WORKDIR` does affect instead is `docker run`. `CMD` and `WORKDIR` both affect `docker run` but `WORKDIR` does not directly affect `CMD` itself. Here is a simple demonstrative example:
```
FROM alpine
CMD pwd
WORKDIR /some/new/dir
```
When this image is run, the output is of course `/some/new/dir`. Swapping the `CMD` and `WORKDIR` lines makes no difference as they do not affect each other.

I would completely remove those two instructions' mention from the sentence. Instead, I think it would not hurt to explicitly mention that it affects `docker run` too. And since it is hard to have too much documentation, I would like it to more specifically describe its effect on `COPY` (`<dest>` only) and `docker cp` (none).
