### ISSUE TITLE
Docker shouldn't try v1 after v2 response 401

### ISSUE THREAD

**Issue by ghost** [moby/moby#17169] opened 2015-10-19 09:31 UTC
### Docker version

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
```

After v2 api returns 401 error indicating the resource docker is requiring is not authorized, the docker client will continue to try v1 api and after this failed, the client will report resource not found

![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-19%20%E4%B8%8B%E5%8D%885.25.51.png?t=1445246769477)

![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-19%20%E4%B8%8B%E5%8D%885.22.50.png?t=1445246674893)

docker client should only try v1 api after v2 api returns 4xx. Now the error message is confusing

Although this happens in docker version 1.8.3, I believe many version have this problem

**Comment by farmerworking** [comment] 2015-10-19 10:26
### docker version

	Client:
	 Version:      1.8.3
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   f4bf5c7
	 Built:        Mon Oct 12 05:37:18 UTC 2015
	 OS/Arch:      linux/amd64
	
	Server:
	 Version:      1.8.3
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   f4bf5c7
	 Built:        Mon Oct 12 05:37:18 UTC 2015
	 OS/Arch:      linux/amd64
	 
### docker info
	Client:
	 Version:      1.8.3
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   f4bf5c7
	 Built:        Mon Oct 12 05:37:18 UTC 2015
	 OS/Arch:      linux/amd64
	
	Server:
	 Version:      1.8.3
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   f4bf5c7
	 Built:        Mon Oct 12 05:37:18 UTC 2015
	 OS/Arch:      linux/amd64
	root@i-m903up73:~/registry_auth/deploy/registry# docker info
	Containers: 4
	Images: 180
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 189
	 Dirperm1 Supported: true
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.16.0-41-generic
	Operating System: Ubuntu 14.04.2 LTS
	CPUs: 1
	Total Memory: 993.8 MiB
	Name: i-m903up73
	ID: ZMBV:RGFO:PTY2:Z45B:5N2B:GDFX:NNL2:26ID:XJ4Y:U3K3:642J:2OQV
	Debug mode (server): true
	File Descriptors: 27
	Goroutines: 43
	System Time: 2015-10-19T17:33:57.154216214+08:00
	EventsListeners: 0
	Init SHA1: 70b0cda2ecbf0d9fb1879ed198a66ad09a3dc50c
	Init Path: /usr/lib/docker/dockerinit
	Docker Root Dir: /var/lib/docker
	WARNING: No swap limit support
	
### uname -a
	Linux i-m903up73 3.16.0-41-generic #55~14.04.1-Ubuntu SMP Sun Jun 14 18:43:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### steps to reproduce the issue:

1. directory structure 

![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-19%20%E4%B8%8B%E5%8D%885.44.25.png?t=1445247938790)  
2. docker-compose.yml content

	dockerauth:
	  image: cesanta/docker_auth:stable
	  ports:
	    - "5001:5001"
	  volumes:
	    - /root/auth_oss/auth_server/config:/config:ro
	    - /var/log/docker_auth:/logs
	    - /root/auth_oss/auth_server/ssl:/ssl
	  command: /config/auth_config.yml
	  restart: always
	registry:
	  image: registry:2
	  ports:
	    - "443:5000"
	  volumes:
	    - /root/auth_oss/auth_server/ssl:/ssl
	    - /root/auth_oss/docker_registry/data:/var/lib/registry
	  restart: always
	  environment:
	    - REGISTRY_AUTH=token
	    - REGISTRY_AUTH_TOKEN_REALM=https://registry.acs.aliyun.com:5001/auth
	    - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
	    - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
	    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/domain.crt
	    - REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/domain.crt
	    - REGISTRY_HTTP_TLS_KEY=/ssl/domain.key	    
3. create self signed certificate and use registry.acs.aliyun.com as CC
4. auth_config.yml
![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-19%20%E4%B8%8B%E5%8D%885.52.06.png?t=1445248350627)
5. docker login -u admin -p 123 -e y https://registry.acs.aliyun.com
6. docker pull hello-world
7. docker tag hello-world registry.acs.aliyun.com/hussein/hello-world
6. docker push registry.acs.aliyun.com/hussein/hello-world
7. docker rmi registry.acs.aliyun.com/hussein/hello-world
8. docker login -u hussein -p 123 -e y https://registry.acs.aliyun.com
9. docker pull registry.acs.aliyun.com/hussein/hello-world

### unexpected result
![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-19%20%E4%B8%8B%E5%8D%885.25.51.png?t=1445246769477)

### docker daemon log
![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-19%20%E4%B8%8B%E5%8D%885.22.50.png?t=1445246674893)

**Comment by thaJeztah** [comment] 2015-10-20 05:19
ping @RichardScothern @dmp42 PTAL

**Comment by RichardScothern** [comment] 2015-10-21 17:54
This looks like the culprit

https://github.com/docker/docker/blob/master/registry/registry.go#L190
```
func shouldV2Fallback(err errcode.Error) bool {
	logrus.Debugf("v2 error: %T %v", err, err)
	switch err.Code {
	case v2.ErrorCodeUnauthorized, v2.ErrorCodeManifestUnknown:
		return true
	}
	return false
}
```

**Comment by tiborvass** [comment] 2015-10-21 18:30
@RichardScothern @farmerworking Thanks for the report. Although it would theoretically make sense to do that, here's the situation:

- We do not want to differentiate between private repositories and non-existing ones
- Currently, the registry chose `401` for both cases, whereas traditionally (e.g. Github) uses `404` for both cases.

So I personally would close this issue and open one (if not already there), that would change the return code from 401 to 404 for both non-existing and private repositories. However, then you'd have to manage backwards compatibility in a way.

Let me know if you agree

**Comment by farmerworking** [comment] 2015-10-22 04:58
I agree using 404 for non-existing one but can't understand your advise upon private repositories.

If a private repository exists but the user has no access, return 401 I think is very reasonable
If the private repository doesn't exist, 404 would be the semantic response

Fallback from v2 to v1 should only work for 404 which may indicate the v2 api is not available

**Comment by thaJeztah** [comment] 2015-10-22 05:03
I think the thought behind returning a 404 for private repo's is that you don't want to disclose that a repository exists if someone doesn't have access to it.

**Comment by farmerworking** [comment] 2015-10-22 05:18
Oh, I see. But that doesn't help us solve the problem in the first place.

How about making the API `/v2/` skip the authentication procedure and will not fallback once this API's response status is 200

**Comment by thaJeztah** [comment] 2015-10-22 05:25
Actually, docker 1.8.3 introduced a `--disable-legacy-registry` option; see https://github.com/docker/docker/pull/16385

**Comment by farmerworking** [comment] 2015-10-22 05:38
For environment where private registry as a service to users, the owner of this private registry has no control of the users' docker, this workaround isn't convenient

In my opinion, this is what fallback strategy should do. It should be fixed instead of walk around.

**Comment by hjacobs** [comment] 2015-11-03 21:53
I agree with @farmerworking: we also operate our own private Docker Registry (written in Clojure, https://github.com/zalando-stups/pierone) and are on the verge to migrate to v2. API v2 is already implemented and works, but the Docker client does behave "well" (similar issue with v2 and auth is #17317).

**Comment by sanmai-NL** [comment] 2016-04-19 14:07
Me and @WillemElbers just encountered this issue with Docker Engine 1.11 when pulling and image from a private registry without being authenticated. 

* When authorization fails for the v2 API,  the v1 API is attempted by the client irrespective of  `--disable-legacy-registry`.
* The v1 API returns a HTTP 404. Instead of inappropriately returning 404 just to not disclose the existence of an image, 401 should be returned for any request for which authentication failed. That also prevent the information leak but will not result in confusing error message `Error: image foo not found`  on the client side.

These are both bugs.

**Comment by thaJeztah** [comment] 2016-04-19 14:28
@sanmai-NL can you open a separate issue for `--disable-legacy-registry` not working correctly?

What kind of setup are you using for your registry? Is this https://github.com/docker/distribution ? Which version?

**Comment by WillemElbers** [comment] 2016-04-28 10:59
Apologies for the delay in this reply. Our private repository is running the "registry:2.1.1" image from the docker distribution project.

**Comment by sudhaker** [comment] 2016-05-13 02:20
Workaround @ 
https://github.com/MarvAmBass/docker-nginx-registry-proxy/blob/master/docker-registry.conf

**Comment by sanmai-NL** [comment] 2017-02-20 07:45
@thaJeztah: has this issue been fixed in the meantime, perhaps?

**Comment by thaJeztah** [comment] 2017-02-24 10:35
@sanmai-NL this is with docker 1.13.1;

**With `--disable-legacy-registry`**;

From Docker Hub;

```
docker pull thajeztah/foobar
```

```
DEBU[0003] Calling POST /v1.26/images/create?fromImage=thajeztah%2Ffoobar&tag=latest
DEBU[0003] Trying to pull thajeztah/foobar from https://registry-1.docker.io v2
ERRO[0011] Not continuing with pull after error: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

INFO[0011] Ignoring extra error returned from registry: unauthorized: authentication required
INFO[0011] Translating "denied: requested access to the resource is denied" to "repository thajeztah/foobar not found: does not exist or no pull access"
ERRO[0011] Handler for POST /v1.26/images/create returned error: repository thajeztah/foobar not found: does not exist or no pull access
```

From a local registry;

```
docker pull localhost:5000/foobar
```

```
DEBU[0168] Calling POST /v1.26/images/create?fromImage=localhost%3A5000%2Ffoobar&tag=latest
DEBU[0168] Trying to pull localhost:5000/foobar from https://localhost:5000 v2
WARN[0168] Error getting v2 registry: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
ERRO[0168] Attempting next endpoint for pull after error: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
DEBU[0168] Trying to pull localhost:5000/foobar from http://localhost:5000 v2
ERRO[0168] Attempting next endpoint for pull after error: manifest unknown: manifest unknown
INFO[0168] Translating "manifest unknown: manifest unknown" to "manifest for localhost:5000/foobar:latest not found"
ERRO[0168] Handler for POST /v1.26/images/create returned error: manifest for localhost:5000/foobar:latest not found
```


**Without `--disable-legacy-registry`**;

```
docker pull localhost:5000/foobar
```

```
DEBU[0004] Calling POST /v1.26/images/create?fromImage=localhost%3A5000%2Ffoobar&tag=latest
DEBU[0004] Trying to pull localhost:5000/foobar from https://localhost:5000 v2
WARN[0004] Error getting v2 registry: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
ERRO[0004] Attempting next endpoint for pull after error: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
DEBU[0004] Trying to pull localhost:5000/foobar from http://localhost:5000 v2
ERRO[0004] Attempting next endpoint for pull after error: manifest unknown: manifest unknown
DEBU[0004] Trying to pull localhost:5000/foobar from https://localhost:5000 v1
DEBU[0004] attempting v1 ping for registry endpoint https://localhost:5000/v1/
DEBU[0004] Fallback from error: Get https://localhost:5000/v1/_ping: http: server gave HTTP response to HTTPS client
ERRO[0004] Attempting next endpoint for pull after error: Get https://localhost:5000/v1/_ping: http: server gave HTTP response to HTTPS client
DEBU[0004] Trying to pull localhost:5000/foobar from http://localhost:5000 v1
DEBU[0004] [registry] Calling GET http://localhost:5000/v1/repositories/foobar/images
ERRO[0004] Not continuing with pull after error: Error: image foobar:latest not found
```


I don't see it falling back to the V1 API if `--disable-legacy-registry` is enabled

**Comment by sanmai-NL** [comment] 2017-02-24 18:33
@thaJeztah:
Perhaps @WillemElbers can confirm whether he still has this issue. Otherwise, I would assume it is fixed now and close the issue.

**Comment by thaJeztah** [comment] 2023-09-18 10:41
Support for v1 registries was removed, so this should no longer be an issue.

**Closed by thaJeztah** 2023-09-18 10:41 UTC
Labels: area/distribution, version/1.8
