### ISSUE TITLE
Question: why ARG not supports `ARG <key> <value>` syntax like ENV in Dockerfile

### ISSUE THREAD

**Issue by k8scat** [moby/moby#42341] opened 2021-04-30 09:19 UTC

**Comment by thaJeztah** [comment] 2021-05-01 11:47
For `ARG`, the `<value>` is optional, and means that the build-arg does not have a default value and should be obtained from either a "global" ARG, through a `--build-arg`, or from a previously set `ENV`.

Without `=` (so `ARG NAME VALUE`), the syntax would be ambiguous;

```dockerfile
ARG NAME VALUE
```

The above could now either mean

- "Define two `ARGS` (one named `NAME`, one named `VALUE`) both without a default value"
- or: "Define a single `ARG` named `NAME` with default value `VALUE`"

We recommend using the `<key>=<value>` for both `ARG` _and_ `ENV`, as it's less ambiguous, and also allows you to set multiple args or envs in a single instruction;

```dockerfile
# define three args without default values
ARG ONE TWO THREE

# combination (ONE doesn't have a default, the others do)
ARG ONE TWO=two-default THREE=three-default

# multiple env vars
ENV FOO="" BAR="hello" BAZ="world"

# or, formatted over multiple lines, but in a single `ENV` instruction
ENV FOO="" \
    BAR="hello" \
    BAZ="world"

```

**Comment by thaJeztah** [comment] 2021-05-01 11:47
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-05-01 11:47 UTC
Labels: area/builder, kind/question
