### ISSUE TITLE
Dry run for volume prune

### ISSUE THREAD

**Issue by adhulipa** [moby/moby#39418] opened 2019-06-26 05:28 UTC
This issue is a sub-task of the work being tracked in #30623
This issue very specifically tracks the feature to enable `dryRun` mode for the volume prune command.

Example of desired behavior:
```
root@ee0fb66c4f18:/var/lib/docker/volumes/178f849c6110911b7a9155a69cfee6863f290f29240c87fa1676d2830a1aea12/_data# docker volume prune -n
Will Delete Volumes:
178f849c6110911b7a9155a69cfee6863f290f29240c87fa1676d2830a1aea12
7aea8a44fc0b213eca32e8255c4985d5a66012f30897579deaa46bbea1c7863c

Estimated reclaimable space: 1.767MB
root@ee0fb66c4f18:/var/lib/docker/volumes/178f849c6110911b7a9155a69cfee6863f290f29240c87fa1676d2830a1aea12/_data#
```
```
root@ee0fb66c4f18:/var/lib/docker/volumes/178f849c6110911b7a9155a69cfee6863f290f29240c87fa1676d2830a1aea12/_data# docker volume prune --filter label=banana -n
Will Delete Volumes:
7aea8a44fc0b213eca32e8255c4985d5a66012f30897579deaa46bbea1c7863c

Estimated reclaimable space: 0B
```

**Comment by adhulipa** [comment] 2019-06-26 06:17
https://github.com/moby/moby/pull/39419

**Comment by Nassiel** [comment] 2022-08-21 21:20
https://github.com/moby/moby/issues/30623#issuecomment-1221622815 same for volumes

**Comment by thaJeztah** [comment] 2023-10-19 12:22
- closing as duplicate of https://github.com/moby/moby/issues/30623

**Closed by thaJeztah** 2023-10-19 12:22 UTC
Labels: kind/feature
