### ISSUE TITLE
Does docker have anything to do with GCC and glibc?

### ISSUE THREAD

**Issue by KeithTt** [moby/moby#34323] opened 2017-07-31 10:03 UTC
Will docker be influenced if I upgrade gcc and libc?

**Comment by thaJeztah** [comment] 2017-07-31 14:46
Not any different than other software installed on your machine; docker, when installed from the `.deb` or `.yum` packages, is dynamically linked, so uses some share libraries;

```
ldd /usr/bin/dockerd
	linux-vdso.so.1 =>  (0x00007ffc32f1f000)
	libapparmor.so.1 => /lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007f71d9ede000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f71d9e59000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f71d9c3b000)
	libseccomp.so.2 => /lib/x86_64-linux-gnu/libseccomp.so.2 (0x00007f71d99fd000)
	libdevmapper.so.1.02.1 => /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 (0x00007f71d97a4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f71d93d9000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f71d91b7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f71d8faf000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f71d8d8c000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f71d8aab000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558793705000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f71d8a8b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f71d8781000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f71d8511000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f71d830d000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f71d80f8000)
```

So unless there's a breaking change in the version of those libraries, upgrading should not be a problem.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-07-31 14:46 UTC
Labels: kind/question
