### ISSUE TITLE
unable to write to /proc/self/loginuid with docker 1.2.0, container ubuntu trusty

### ISSUE THREAD

**Issue by apergos** [moby/moby#8244] opened 2014-09-25 22:14 UTC
This is another version of the sshd failure bug.
Host OS: fedora 20
Container OS: ubuntu 14.04
Kernel: 3.15.8-200.fc20.x86_64
libpam in container: 1.1.8-1ubuntu2

/proc is mounted rw, checking from within the container, but when I try to sshd in, I get the following complaint:
Sep 25 18:22:07 b1c7606d8b13 sshd: pam_loginuid(sshd:session): Error writing /proc/self/loginuid: Operation not permitted

Checking the ubuntu patches for pam_loginuid.c, I see that it tries to check whether the process is running in the host namespace or not, by comparing the contents of /proc/self/uid_map to "         0          0 4294967295\n" and if they do not match then the process is assumed to be running in a user namespace, where writes may fail, and thus the write error would be ignored.

This must not happen for some reason, and indeed when I cat /proc/self/uid_map manually from within the container, it shows  0 0 4294967295  rather than some variant like 0 1000 1000

What am I missing here? Note that I build docker from the stock trusty image, i.e. "FROM ubuntu:14.04", and it is not running with any special options or configuration.

I could comment out the reference to the pam module in the pam sshd settings but I'd rather get to the underlying cause.  Thanks.

**Comment by jfrazelle** [comment] 2015-01-14 23:45
can you try with the latest docker build you can download the binary from master.dockerproject.com

**Comment by jfrazelle** [comment] 2015-01-19 23:25
closing, let me know you you believe this has been closed in error

**Comment by udomsak** [comment] 2015-03-04 17:43
@jfrazelle  The problem still even Docker version 1.5 and way to fix is remove pam_loginuid  
otherwise  you cant' login via SSH key

**Comment by jfrazelle** [comment] 2015-03-04 18:48
I reopened can you please give exact steps to reproduce

**Comment by udomsak** [comment] 2015-03-05 07:21
@jfrazelle  Ok you can test by ssh with Public-key access  

- I try to fix with pam_loginuid.so PAM session still not work getlogin() can't get properly value  for /proc/self/loginuid 

- Also  check version or upgrade Ubuntu and relate package version for avoiding problem of PAM and  Openssh but still not work.   
 
- Normal PC and Full-VM ( Virtualbox ) i work fine. so that i think problem may come from docker side  

- Conclusion for lazy fix just remove pam_loginuid from PAM  now i can back to login via Public-key. 



Ref: ( May or May not relate problem but talking to same error )
===
https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1067779
http://goo.gl/VW6y6c  (  PAM login with openssh  ) 

- May be nature of LXC and  Docker ? :) 

http://www.linuxweblog.com/blogs/sandip/20090203/setloginuid-failed-opening-loginuid
```
ssh -i ~/root/.ssh/id_rsa  root@127.0.0.1 -p  51382  
```

Server Side
=========

``` 
Mar  4 17:31:27 0d723ba69a80 sshd[3773]: Server listening on 0.0.0.0 port 22.
Mar  4 17:31:27 0d723ba69a80 sshd[3773]: Server listening on :: port 22.
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: Accepted publickey for root from 172.17.42.1 port 51382 ssh2: RSA a5:b1:f7:2f:b0:fb:42:3e:e5:7a:05:63:9c:2c:10:04
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: pam_loginuid(sshd:session): Error writing /proc/self/loginuid: Operation not permitted
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: pam_loginuid(sshd:session): set_loginuid failed
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: pam_unix(sshd:session): session opened for user root by (uid=0)
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: pam_env(sshd:session): Unable to open env file: /etc/default/locale: No such file or directory
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: pam_loginuid(sshd:session): Error writing /proc/self/loginuid: Operation not permitted
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: pam_loginuid(sshd:session): set_loginuid failed
Mar  4 17:31:31 0d723ba69a80 sshd[3776]: error: PAM: pam_open_session(): Cannot make/remove an entry for the specified session
```

Client Side ( This happen with Ubuntu 13.04  also 14.04 - 14.10 have little bit change but same result )   
========
```
ssh -C -tt -vvv -o ControlMaster=no -o ControlPersist=60s -o ControlPath="/home/udomsak/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=49159 -o IdentityFile="/home/udomsak/.ssh/id_rsa" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1425473999.86-187531347153343 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1425473999.86-187531347153343 && echo $HOME/.ansible/tmp/ansible-tmp-1425473999.86-187531347153343'
OpenSSH_6.2p2 Ubuntu-6ubuntu0.4, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Control socket "/home/udomsak/.ansible/cp/ansible-ssh-127.0.0.1-49159-root" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 49159.
debug2: fd 3 setting O_NONBLOCK
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug3: timeout: 10000 ms remain after connect
debug3: Incorrect RSA1 identifier
debug3: Could not load "/home/udomsak/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /home/udomsak/.ssh/id_rsa type 1
debug1: Checking blacklist file /usr/share/ssh/blacklist.RSA-2048
debug1: Checking blacklist file /etc/ssh/blacklist.RSA-2048
debug1: identity file /home/udomsak/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2p2 Ubuntu-6ubuntu0.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2 pat OpenSSH*
debug2: fd 3 setting O_NONBLOCK
debug3: put_host_port: [127.0.0.1]:49159
debug3: load_hostkeys: loading entries for host "[127.0.0.1]:49159" from file "/home/udomsak/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /home/udomsak/.ssh/known_hosts:97
debug3: load_hostkeys: loaded 1 keys
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: mac_setup: found hmac-md5-etm@openssh.com
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
debug2: mac_setup: found hmac-md5-etm@openssh.com
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 22:b2:68:79:0a:c2:02:f7:8a:9b:62:58:52:f3:c3:89
debug3: put_host_port: [127.0.0.1]:49159
debug3: put_host_port: [127.0.0.1]:49159
debug3: load_hostkeys: loading entries for host "[127.0.0.1]:49159" from file "/home/udomsak/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /home/udomsak/.ssh/known_hosts:97
debug3: load_hostkeys: loaded 1 keys
debug1: Host '[127.0.0.1]:49159' is known and matches the ECDSA host key.
debug1: Found key in /home/udomsak/.ssh/known_hosts:97
debug1: ssh_ecdsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/udomsak/.ssh/id_rsa (0x7f7582d69b50), explicit
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey
debug3: authmethod_lookup publickey
debug3: remaining preferred: ,gssapi-keyex,hostbased,publickey
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/udomsak/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug2: input_userauth_pk_ok: fp a5:b1:f7:2f:b0:fb:42:3e:e5:7a:05:63:9c:2c:10:04
debug3: sign_and_send_pubkey: RSA a5:b1:f7:2f:b0:fb:42:3e:e5:7a:05:63:9c:2c:10:04
debug1: read PEM private key done: type RSA
debug1: Enabling compression at level 6.
debug1: Authentication succeeded (publickey).
Authenticated to 127.0.0.1 ([127.0.0.1]:49159).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: packet_set_tos: set IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug1: Sending environment.
debug3: Ignored env XDG_VTNR
debug1: Sending env LC_PAPER = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env XDG_SESSION_ID
debug1: Sending env LC_ADDRESS = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug1: Sending env LC_MONETARY = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env ANDROID_HOME
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env XDG_SESSION_COOKIE
debug3: Ignored env GOBIN
debug3: Ignored env depot_tools
debug1: Sending env LC_NUMERIC = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env OLDPWD
debug3: Ignored env NINJA
debug3: Ignored env ANT_HOME
debug3: Ignored env ANT_OPTS
debug3: Ignored env USER
debug3: Ignored env LS_COLORS
debug1: Sending env LC_TELEPHONE = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env SUDO_USER
debug3: Ignored env SUDO_UID
debug3: Ignored env USERNAME
debug3: Ignored env VIRTUAL_ENV
debug3: Ignored env PATH
debug3: Ignored env MAIL
debug1: Sending env LC_IDENTIFICATION = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env PWD
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env node_webkit
debug1: Sending env LC_MEASUREMENT = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env PS1
debug3: Ignored env XDG_SEAT
debug3: Ignored env HOME
debug3: Ignored env SUDO_COMMAND
debug3: Ignored env SHLVL
debug3: Ignored env LANGUAGE
debug3: Ignored env GOROOT
debug3: Ignored env LOGNAME
debug3: Ignored env LESSOPEN
debug3: Ignored env GOPATH
debug3: Ignored env XDG_RUNTIME_DIR
debug3: Ignored env DISPLAY
debug3: Ignored env SUDO_GID
debug3: Ignored env ATOM_SHELL
debug1: Sending env LC_TIME = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env LESSCLOSE
debug1: Sending env LC_NAME = th_TH.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env XAUTHORITY
debug3: Ignored env COLORTERM
debug3: Ignored env MONGO_DATA
debug3: Ignored env _
debug1: Sending command: /bin/sh -c mkdir -p $HOME/.ansible/tmp/ansible-tmp-1425473999.86-187531347153343 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1425473999.86-187531347153343 && echo $HOME/.ansible/tmp/ansible-tmp-1425473999.86-187531347153343
debug2: channel 0: request exec confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.11.0-26-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

0 packages can be updated.
0 updates are security updates.

Last login: Wed Mar  4 13:00:01 2015 from 172.17.42.1
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug2: channel 0: rcvd eow
debug2: channel 0: close_read
debug2: channel 0: input open -> closed
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug2: channel 0: rcvd close
debug3: channel 0: will not send data after close
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

Connection to 127.0.0.1 closed.
Transferred: sent 3848, received 2816 bytes, in 0.5 seconds
Bytes per second: sent 8316.4, received 6086.0
debug1: Exit status 254
debug1: compress outgoing: raw data 1060, compressed 554, factor 0.52
debug1: compress incoming: raw data 350, compressed 295, factor 0.84
```

**Comment by Windforce17** [comment] 2022-10-28 06:08
I font some solutions after search in google.
1. Disable PAM in ssd config.(UsePAM no)
2. Disable  pam_loginuid.so in  /etc/pam.d/sshd.
3. add AUDIT_CONTROL in docker --cap-add flag.

**Comment by thaJeztah** [comment] 2023-09-17 23:11
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 23:11 UTC
Labels: area/runtime, kind/bug
