### ISSUE TITLE
Allow variable interpolation in `COPY --from`

### ISSUE THREAD

**Issue by maxmoehl** [moby/moby#45419] opened 2023-04-27 05:43 UTC
### Description

I'm adding the go SDK to my image by copying it out of the official image. Instead of hard-coding the go version in the Dockerfile I'd like to have a `ARG` for it like so:

```
FROM debian:bullseye

ARG GO_VERSION
COPY --from=golang:${GO_VERSION} /usr/local/go/ /usr/local/go/
```

But when trying to build the image, I get the following error:
```
$ docker image build --build-arg GO_VERSION=1.20.3 .
[+] Building 0.1s (3/3) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 142B
 => [internal] load .dockerignore
 => => transferring context: 2B
 => CANCELED [internal] load metadata for docker.io/library/debian:bullseye
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "golang:${GO_VERSION}": invalid reference format
```

Would it be possible to support variable interpolation for the `--from` argument of the `COPY` operation?

**Comment by thaJeztah** [comment] 2023-04-27 09:28
- this is a duplicate of https://github.com/moby/moby/issues/34482, which has more details on this.


For your use-case, you can use an "alias" stage to prepare the version of Go to copy from;



```dockerfile
# syntax=docker/dockerfile:1

ARG GO_VERSION=latest

# golang image to use, defaults to "latest"
FROM golang:${GO_VERSION} AS go

FROM debian:bullseye
COPY --from=go /usr/local/go/ /usr/local/go/
```


I'll close this ticket as it duplicates #34482 but feel free to continue the conversation.

**Closed by thaJeztah** 2023-04-27 09:28 UTC
Labels: area/builder, kind/feature, impact/dockerfile

**Comment by maxmoehl** [comment] 2023-04-27 09:29
Thanks! Sorry that I missed the other ticket :/

**Comment by thaJeztah** [comment] 2023-04-27 09:42
No worries! I happened to know there was a ticket for this (but had to search for it 😂)
