### ISSUE TITLE
Docker build cache does not ignore uid/gid on ADD or COPY

### ISSUE THREAD

**Issue by jtprobst** [moby/moby#32816] opened 2017-04-25 16:19 UTC
The uid/gid of a file (on the build host's filesystem) seem to have an effect on the hash of a file when it is added through ADD or COPY. This seems superfluous since the ownership of the added file is reset to uid=gid=0 in the Docker image.

This behaviour may lead to the Docker build cache being busted in continuous integration environments, if uid/gid are different across different build nodes.

For a minimum working example, please consider the following example where an image is built twice, the second time with different ownership of a COPY'd file.

Please note
* The hashes of the added file are different as per `docker history`
* The ownership is reset to uid=gid=0 inside the image, as stated in the [documentation for ADD](https://docs.docker.com/engine/reference/builder/#copy) ("All new files and directories are created with a UID and GID of 0.")

```bash
$ ls -lah
total 8,0K
drwxrwxr-x 1 jprobst jprobst   36 Apr 25 18:08 .
drwxrwxrwx 1 jprobst jprobst 6,4K Apr 25 17:15 ..
-rw-rw-r-- 1 jprobst jprobst   44 Apr 25 18:08 Dockerfile
-rwxrwxrwx 1 jprobst jprobst    5 Apr 25 17:15 test.txt

$ cat Dockerfile 
FROM ubuntu:16.04

COPY test.txt /test.txt

$ docker build -t demo .
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM ubuntu:16.04
 ---> 104bec311bcd
Step 2/2 : COPY test.txt /test.txt
 ---> ea497fe942a0
Removing intermediate container 16753a7ab82b
Successfully built ea497fe942a0

$ docker history demo
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
ea497fe942a0        17 seconds ago      /bin/sh -c #(nop) COPY file:db60da90f31b3b...   5B                  
104bec311bcd        4 months ago        /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B                  
<missing>           4 months ago        /bin/sh -c mkdir -p /run/systemd && echo '...   7B                  
<missing>           4 months ago        /bin/sh -c sed -i 's/^#\s*\(deb.*universe\...   1.9kB               
<missing>           4 months ago        /bin/sh -c rm -rf /var/lib/apt/lists/*          0B                  
<missing>           4 months ago        /bin/sh -c set -xe   && echo '#!/bin/sh' >...   745B                
<missing>           4 months ago        /bin/sh -c #(nop) ADD file:7529d28035b43a2...   129MB               

$ sudo chown 1001:1001 test.txt

$ ls -lah
total 8,0K
drwxrwxr-x 1 jprobst jprobst   36 Apr 25 18:08 .
drwxrwxrwx 1 jprobst jprobst 6,4K Apr 25 17:15 ..
-rw-rw-r-- 1 jprobst jprobst   44 Apr 25 18:08 Dockerfile
-rwxrwxrwx 1    1001    1001    5 Apr 25 17:15 test.txt

$ docker build -t demo .
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM ubuntu:16.04
 ---> 104bec311bcd
Step 2/2 : COPY test.txt /test.txt
 ---> 43cb126c18bb
Removing intermediate container 4e729efe09bb
Successfully built 43cb126c18bb

$ docker history demo
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
43cb126c18bb        14 seconds ago      /bin/sh -c #(nop) COPY file:f9b82392428347...   5B                  
104bec311bcd        4 months ago        /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B                  
<missing>           4 months ago        /bin/sh -c mkdir -p /run/systemd && echo '...   7B                  
<missing>           4 months ago        /bin/sh -c sed -i 's/^#\s*\(deb.*universe\...   1.9kB               
<missing>           4 months ago        /bin/sh -c rm -rf /var/lib/apt/lists/*          0B                  
<missing>           4 months ago        /bin/sh -c set -xe   && echo '#!/bin/sh' >...   745B                
<missing>           4 months ago        /bin/sh -c #(nop) ADD file:7529d28035b43a2...   129MB               

$ docker run -t demo ls -lah /test.txt
-rwxrwxrwx 1 root root 5 Apr 25 15:15 /test.txt
```

**Comment by tonistiigi** [comment] 2017-04-27 00:09
I agree the current behavior doesn't make much sense but there have been plenty of discussions about relaxing the restrictions of `COPY/ADD` and we couldn't support that then because we need to compute the cache key before the `COPY` commands for optimization.

In this case I would maybe consider instead setting the uid/gid already to 0 on the client side. We are switching from one list of users to another so these uid-s on the client side don't make much sense in the container anyway(they can make sense for API usage). wdyt @dnephin @duglin

**Comment by duglin** [comment] 2017-04-27 17:24
If we change the uid to zero on the client will that result in a change of behavior with the new ability to access the context via a mount during the build? The uids on those files will now be different, right?

**Comment by tonistiigi** [comment] 2017-04-27 18:36
@duglin We don't have this ability yet. Actually, it may make even more sense then as otherwise if you mount user context you will have files with weird uids there, that always need to be chowned by the user.

**Comment by duglin** [comment] 2017-04-27 18:46
yea, wasn't implying it made sense, I just didn't want to change existing behavior w/o considering the impact.

**Comment by dnephin** [comment] 2017-05-01 14:39
I think we already set all files to 755 on the windows client, so setting uid/gid sounds like a similar idea. I'm fine with it. I agree that breaking the cache when the user running the build has a different id doesn't make much sense.

**Comment by thaJeztah** [comment] 2017-05-01 23:13
Wasn't there discussion about _preserving_ the uid/gid when `ADD` / `COPY` files? If we reset now, that would block having that as an option in future.

**Comment by tonistiigi** [comment] 2017-05-01 23:20
@thaJeztah Do you have a link? The API would still support that.

**Comment by thaJeztah** [comment] 2017-05-01 23:31
@tonistiigi hm, must to a search for that discussion (there may have been a couple)

**Comment by jtprobst** [comment] 2017-06-23 08:50
@thaJeztah Are you referring to these discussions: https://github.com/moby/moby/issues/29853 and https://github.com/moby/moby/pull/28499?

**Comment by jackric** [comment] 2017-07-11 16:30
Bumping this because I want #28499

**Comment by shouze** [comment] 2017-07-15 13:56
Guys, today docker builds is cool and work as expected ** on the same machine ** since we have:
- Efficient build contexts with `.dokerignore` (almost since the begining, can not figure out with PR)
- `mtime ignored during COPY` https://github.com/moby/moby/pull/12031
- `multi stage builds` https://github.com/moby/moby/pull/31257
- `--cache-from` to avoid cache busting https://github.com/moby/moby/pull/26839

But ... it's almost a pity when you build and push pictures on some ci machine / cluster and then pull them locally and get disappointed when at the first rebuild cache gets invalidated even if changes you've made should not trigger so much invalidations.

So yes discussions are running after few months and 2 options seems to compete:
- `RUN --mount` https://github.com/moby/moby/issues/32507
- `COPY --chown` https://github.com/moby/moby/issues/30110

I guess to 2 could be implemented at some point, the more pragmatic one is definitely `COPY --chown`

it would of course transform this:
```Dockerfile
COPY app ./app
USER root
RUN chown -R node:node ./app
USER node
```

into this:
```Dockerfile
COPY --chown node:node app ./app
```

But the best thing would be to get it fix this #32816 too, so much time avoided to build again & again, would be a very big win.

**Comment by shouze** [comment] 2017-07-15 13:58
Also, I'm ok to help making this feature a reality if you can point me to source code parts to look after.

**Comment by shouze** [comment] 2017-07-15 14:02
And yes... also it would be really great to be able to have some diagnose/logging feature to enable on demand when you build an image and you can't figure out why your cache gets invalidated and you don't know why:
- Do I've missed to add some exclusions in my .dockerignore?
- Do I need to make split/order build steps in my Dockerfile?
- Is it another issue related to some ADD/COPY hashing algorithm?
- ...

**Comment by shouze** [comment] 2017-08-21 10:03
ping @tonistiigi @dnephin @estesp @duglin as https://github.com/moby/moby/pull/34263 getting to be merged but won't solve this issue, can you confirm me that here the issue resides in the remotecontext part of the builder?

For example in that part that would take into account remote uid/gid during the build the compute the hash, whilst it should ignore it?
https://github.com/moby/moby/blob/361a473121f2cd4e688a3bb71fbeff00aaf674d7/builder/remotecontext/filehash.go#L13-L33

**Comment by shouze** [comment] 2017-08-21 10:22
And can you confirm me that this is the same kind of issue than https://github.com/moby/moby/pull/12031? (a lot of refactoring has occured since)

**Comment by shouze** [comment] 2017-08-21 10:23
So, having a fix for 17.09 would be... so great, plz tell me, I'm here to help.

**Comment by tonistiigi** [comment] 2017-08-21 17:36
As I commented in https://github.com/moby/moby/issues/32816#issuecomment-297575456, I think the better fix is to reset the uid/gid to 0 on the cli when walking the source directory. This will let us support maintaining the original values in the future.

**Comment by shouze** [comment] 2017-08-21 17:58
@tonistiigi do you mean like it's done [in cli by adding Dockerfile in build context?](https://github.com/docker/cli/blob/0b050a599f04d8401c04493f9c7f787b74fd6511/cli/command/image/build/context.go#L336-L351)

**Comment by tonistiigi** [comment] 2017-08-21 18:08
@shouze No, by adding `ChownOpts` support to `TarWithOptions` and calling it in
https://github.com/docker/cli/blob/0b050a599f04d8401c04493f9c7f787b74fd6511/cli/command/image/build.go#L244 . Equivalent needed for `--stream`.

**Comment by shouze** [comment] 2017-08-21 23:30
@tonistiigi ok so I need first to patch archive pkg in moby/moby to add `ChownOps` to `TarWithOptions` then upgrade the archive vendor pkg in docker/cli and use this new patched archive package.

I've quickly looked at archive pkg, can you plz confirm me that the patch would look something like that?
https://gist.github.com/shouze/53f3e65ec50ec2226cc5f121be23d74f

**Comment by tonistiigi** [comment] 2017-08-21 23:35
@shouze Correct. In your patch you don't want to chown any local files of the user(actually the path in the patch doesn't exist as well), instead you need to reset the uid/gid properties in the tar header in `addTarFile`.

**Comment by shouze** [comment] 2017-08-21 23:39
Thx! Yes, I was concluding that I need to make changes inside `addTarFile`.

**Comment by shouze** [comment] 2017-08-22 00:11
@tonistiigi so here's a new revision of my path on archive pkg, still need to read the code to get familiar with all the concepts, am I close to the right implementation? Thx for your help & your patience 👼 
https://gist.github.com/shouze/53f3e65ec50ec2226cc5f121be23d74f

**Comment by tonistiigi** [comment] 2017-08-22 00:14
@shouze Push to your fork so I can add comments to the code

**Comment by shouze** [comment] 2017-08-22 00:23
Here's the begining of a PR https://github.com/moby/moby/pull/34590

**Comment by shouze** [comment] 2017-09-14 08:13
Hi guys, fixed by (now merged & tagged 17.10) https://github.com/docker/cli/pull/513 & https://github.com/moby/moby/pull/34590 except in the case of the recently introduced --stream (still experimental) feature. `--stream` will be fixed soon too, needs some fsutil/buildkit updates & fixes first.

**Comment by thaJeztah** [comment] 2017-09-14 09:18
Thanks @shouze - let me close this issue 👍

**Closed by thaJeztah** 2017-09-14 09:18 UTC
Labels: area/builder, kind/bug

**Comment by koreno** [comment] 2020-07-29 14:48
What's the latest on this issue - is there a workaround/solution to cache busting due to ownership change?
I'm currently on docker 19.3

**Comment by thaJeztah** [comment] 2020-08-10 12:49
@koreno are you still seeing this problem? And, are you sure it's related to permissions, and not (e.g.) extended attributes?

I'm trying to reproduce the problem on Docker 19.03.12, and am not able to;

Create a directory to play in

```bash
mkdir repro-32816 && cd repro-32816
```

Create a file, owned by `123:456`

```bash
touch test.txt && sudo chown 123:456 test.txt
```

Create a Dockerfile to build;

```bash
cat > Dockerfile -<<EOF
FROM busybox
COPY test.txt /test.txt
EOF
```

Build with both buildkit and non-buildkit, and verify permissions in the image

```bash
DOCKER_BUILDKIT=0 docker build -t foo .
Sending build context to Docker daemon  7.246MB
Step 1/2 : FROM busybox
 ---> 018c9d7b792b
Step 2/2 : COPY test.txt /test.txt
 ---> 1ce12750fb36
Successfully built 1ce12750fb36
Successfully tagged foo:latest

docker run --rm foo sh -c 'ls -lan /test.txt'
-rw-r--r--    1 0        0                0 Aug 10 12:40 /test.txt
```

```bash
DOCKER_BUILDKIT=1 docker build -t foo .
[+] Building 0.1s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                          0.0s
 => => transferring dockerfile: 79B                                                           0.0s
 => [internal] load .dockerignore                                                             0.0s
 => => transferring context: 2B                                                               0.0s
 => [internal] load metadata for docker.io/library/busybox:latest                             0.0s
 => [internal] load build context                                                             0.0s
 => => transferring context: 29B                                                              0.0s
 => CACHED [1/2] FROM docker.io/library/busybox                                               0.0s
 => [2/2] COPY test.txt /test.txt                                                             0.0s
 => exporting to image                                                                        0.0s
 => => exporting layers                                                                       0.0s
 => => writing image sha256:21f44e2a80df5f7efd3c50093c6b6b7f3584a31a2a27ab4441b0e139702f2f25  0.0s
 => => naming to docker.io/library/foo                                                        0.0s

docker run --rm foo sh -c 'ls -lan /test.txt'
-rw-r--r--    1 0        0                0 Aug 10 12:40 /test.txt
```

Change ownership of the file on the host to `234:456`

```bash
sudo chown 234:456 test.txt
```

Build with both BuildKit enabled and disabled, check that the `COPY` step is "cached", and that permissions in the image are reset to `0:0`;

```bash
DOCKER_BUILDKIT=0 docker build -t foo .
Sending build context to Docker daemon  7.246MB
Step 1/2 : FROM busybox
 ---> 018c9d7b792b
Step 2/2 : COPY test.txt /test.txt
 ---> Using cache
 ---> 1ce12750fb36
Successfully built 1ce12750fb36
Successfully tagged foo:latest

docker run --rm foo sh -c 'ls -lan /test.txt'
-rw-r--r--    1 0        0                0 Aug 10 12:40 /test.txt
```


```bash
DOCKER_BUILDKIT=1 docker build -t foo .
[+] Building 0.1s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                          0.0s
 => => transferring dockerfile: 36B                                                           0.0s
 => [internal] load .dockerignore                                                             0.0s
 => => transferring context: 2B                                                               0.0s
 => [internal] load metadata for docker.io/library/busybox:latest                             0.0s
 => [1/2] FROM docker.io/library/busybox                                                      0.0s
 => [internal] load build context                                                             0.0s
 => => transferring context: 27B                                                              0.0s
 => CACHED [2/2] COPY test.txt /test.txt                                                      0.0s
 => exporting to image                                                                        0.0s
 => => exporting layers                                                                       0.0s
 => => writing image sha256:21f44e2a80df5f7efd3c50093c6b6b7f3584a31a2a27ab4441b0e139702f2f25  0.0s
 => => naming to docker.io/library/foo                                                        0.0s


docker run --rm foo sh -c 'ls -lan /test.txt'
-rw-r--r--    1 0        0                0 Aug 10 12:40 /test.txt
```

**Comment by koreno** [comment] 2020-08-12 17:55
Hmm, I guess I misdiagnosed my problem...
Ultimately I'm trying to reuse images as caches for builds on other hosts, but some arbitrary changes invalidate the cache and I can't figure out quite what it is.
I'm assuming permission bits are part of the hash. Does the order in which files are listed in a directory matter?
Is there any canonical solution to this "distributed CI" caching problem?

**Comment by ben-z** [comment] 2020-10-20 23:32
I'm seeing the same issue with the setgid bit:

```
mkdir test-dir
cat > Dockerfile -<<EOF
FROM busybox
COPY test-dir /test-dir
heredoc> EOF

docker build -t foo .
chmod g+s test-dir
docker build --cache-from foo -t foo-cached . # does not use the cache
```

Is this intended behaviour? In the container the setgid bit doesn't seem to be preserved.

**Comment by griffous** [comment] 2021-09-01 07:48
I spent an entire day on this same problem too, so here are some notes for the next person who finds themselves looking at this bug with the same scenario in mind.

Our centralised builders (Kubernetes buildkit pods) would consistently hash/cache ADDs one way when our CI system (GitlabCI) initiated builds, but _another way_ (consistently, but different to GitlabCI builds) when I initiated builds from local machines.
This was while using the exact same git commit, the same buildkit builder instance, and I even ran the docker client/buildx/bake in a common docker container, in an attempt to isolate/exclude any host-machine differences.

I still experienced a cache break each time I alternated between CI and local builds.

My solution was to add run these two commands prior to the `docker buildx bake` command, on each run:
```
# Ensure that the filesystem permissions are consistent across all umasks, all git checkouts:
find . -type f -executable -not -perm 777 -exec chmod 777 {} \;
find . -type f -not -executable -not -perm 666 -exec chmod 666 {} \;
```

I learned that the only part of file permissions which git actually saves is the "execute bit". When git creates files, it uses the operating systems `umask` to default all of the other octects in the permission mask.

On our CI system, the git checkout created files with "execute on", into file system with a 777 mask, whereas my local machine was making 775 files. Both are "executable" as far as git is concerned, but when Docker hashes each files during ADD operations, the difference in mask was triggering cache breaks.

By "normalising" the permissions with the commands above, I now get consistent caching across both CI and local environments.
It's true that this isn't a "Docker bug", but WOW was this tricky to track down! It would be _really helpful_ if some kind of debug mode would print why the hashing implementation decided that there was a miss.

I hope this helps someone else :)

**Comment by max-sixty** [comment] 2021-09-03 18:49
Thanks @griffous , that's v insightful.

Unfortunately it didn't help us, as we only build from GitLab. But it shares a common theme — being able to understand why there's a cache miss would be really helpful.

In our case we used to miss on an `ADD` (could never work out why), and now we miss from the very first stage. Does anyone have any techniques for trying to understand why there's a miss?
