### ISSUE TITLE
How to achive that moby sends the portainer authentification with every call?

### ISSUE THREAD

**Issue by atix1906** [moby/moby#36549] opened 2018-03-09 15:39 UTC
I am trying to automate the update of docker-compose.yml files with a go program in a secure way by using the authentification of portainer.

Is there any chance you could help me figure out how to achive that whenever I make a call with moby the authentification info for portainer is beeing send along?

In this [repo](https://github.com/atix1906/PortainerGoDockerTest) I am trying to figure it out. I managed to get access to portainer via the [api ](https://app.swaggerhub.com/apis/deviantony/Portainer/1.16.3/) and also got the docker sdk and api [example ](https://docs.docker.com/develop/sdk/#choose-the-sdk-or-api-version-to-use) running. 
Since I'm new to docker, portainer and go I am now stuck and it would be very kind if I could get a little guidance.

So I guess my question is, how to securly implement the connection between moby and portainer?

**Comment by thaJeztah** [comment] 2018-03-09 15:44
Thanks for asking, but we try not to use the GitHub issue tracker general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-03-09 15:44 UTC
