### ISSUE TITLE
Update paused due to failure or early termination of task

### ISSUE THREAD

**Issue by MLescaudron** [moby/moby#34245] opened 2017-07-25 12:38 UTC
Hi,
**Description**

After 10-15 min of inactivity on a server, when I update a service with this command :  
`docker service update --image pseudo/image:tag --with-registry-auth service_name --detach=false`

I have this error every time: 
```
overall progress: 0 out of 4 tasks 
1/4: preparing [=================================>                 ] 
2/4:   
3/4:   
4/4:   
service update paused: update paused due to failure or early termination of task usuj4mrmk7x7z2a1vpvob569n
```

And if I restart the command again, it works ...
And if I leave for 15min and I start again, I have to run again the command twice.

I don't know why and it's very frustrating.

**Steps to reproduce the issue :**

I'm using private image with a nodejs express server. I'm using 1 docker swarm cluster and 1 node on a different machine.

The command to deploy : 
`docker stack deploy --with-registry-auth --compose-file dev.compose.yml custom_name`

dev.compose.yml
```
version: "3.3"

services:
  server:
    image: pseudo/image:tag
    ports:
      - 8080:8080
    depends_on:
      - mongo
    deploy:
      mode: replicated
      replicas: 4
  mongo:
    image: mongo:3.4.6
    logging:
      driver: none
```

Docker version : 
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Any idea of what am I doing wrong ?

**Comment by cpuguy83** [comment] 2017-07-25 13:14
If I had to guess, your `server` service is not handling the case where `mongo` is not running yet.
`depends_on` is not supported on `stack deploy` (it's compose-only).

**Comment by MLescaudron** [comment] 2017-07-25 18:42
Hum ok, so what's the workaround ?
remove depends_on ? Are they another ways to tell compose depends_on ?

**Comment by cpuguy83** [comment] 2017-07-25 19:01
The issue (I'm assuming) is that your `server` service is relying on `depends_on` to start the containers in sequence and exits if the dependent service is not available on start, which cannot be guaranteed on the swarm (and is ignored by stack-deploy).

Insead the `server` service should keep trying to connect to the dependent service until it is available.

**Comment by thaJeztah** [comment] 2017-07-26 10:38
A simple example of retry logic can be found in the official [WordPress image](https://github.com/docker-library/wordpress/blob/0a5405cca8daf0338cf32dc7be26f4df5405cfb6/php5.6/apache/docker-entrypoint.sh#L190-L201); `depends_on` only resolves the initial _deploy_ of a service, but won't handle failures of a dependency (i.e., the `mongo` service) after the stack is deployed. For that reason, the recommendation is to have each service handle failures during its entire lifecycle.

I don't think there's a bug at hand here, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-26 10:38 UTC
Labels: area/swarm, version/17.06

**Comment by vide** [comment] 2017-09-22 08:17
@thaJeztah sorry for probably hijacking the thread but I've got a similar error during a rolling update of a swarm cluster where most of the containers in the service were updated but not the last one, and inspecting the service gave me an `update paused due to failure or early termination of task TASK_ID". How can I debug TASK_ID to know what was the reason for the update being paused? And how can I restart it from the same point?

**Comment by getvivekv** [comment] 2018-03-29 12:58
Just hit the same issue with our cluster. Unsure what triggers it as the message is not descriptive enough. You could however, restart the update simply by running 

`docker service update {service_name}`

**Comment by amalcp** [comment] 2019-01-14 11:49
Hi,
The same happened on my swarm cluster as well. most of the time, the docker deploy gets stuck with the message **update paused due to failure or early termination of task**.

**Docker version 18.09.0, build 4d60db4**

- To reproduce the issue deploy the stack using 
  docker stack deploy -c compose-deploy.yml --with-registry-auth MyService

Pasting the information.
===================
[root@master-01 ~]# docker service inspect --pretty MyService

ID:		r6naxdhcd5f7h16xkh40qmcwl
Name:		MyService
Labels:
 com.docker.stack.image=nexus.hi.com/cheerios/MyService:819
 com.docker.stack.namespace=MyService
 feature.description=Frontend-proxy
Service Mode:	Replicated
 Replicas:	4
UpdateStatus:
 State:		paused
 Started:	26 minutes ago
 Message:	update paused due to failure or early termination of task ntbj1z5su31lyp1lhha91brai
Placement:
UpdateConfig:
 Parallelism:	1
 Delay:		10s
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
===================

Docker-composeFile
===================
nginx-proxy:
    image: {{nginx_proxy_image}}
    hostname: {{nginx_hostname}}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - myservice
    deploy:
      replicas: 4
      labels:
        feature.description: "Frontend-proxy"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: "/usr/sbin/nginx"
===================

And if I have issued **docker service update myservice**, all the replicas will get updated with the latest image.

I have tried many things, none got worked. 
Any help will be highly appreciated

**Comment by thaJeztah** [comment] 2019-01-15 13:18
Not sure if it's related, but might want to try upgrading to docker 18.09.1, and containerd.io 1.2.2. There were some deadlocks in containerd, perhaps those prevent the tasks from being terminated

**Comment by till** [comment] 2020-01-14 21:52
FWIW, `systemctl status -l docker` told me that a bind was off. And then I realised that I moved the `data-root` to another partition, but did not update the bind on the service.

**Comment by gypark** [comment] 2024-01-17 00:40
In my case, while I was updating a service to deploy a new image, updating suddenly stopped with the same message `update paused due to failure or early termination of task TASK_ID`

I had executed update command again, and it finally succeeded.

I don't know if this is related, but that service is set to deploy 12 replicas, and I have had no problem at all with the other several services of 3 replicas, respectively, for a few years. Only updating the service in question had failed twice, every time after increasing the number of replicas.

Docker version is 19.03.12
