### ISSUE TITLE
regression on --hostname option

### ISSUE THREAD

**Issue by lazedo** [moby/moby#31423] opened 2017-02-28 15:27 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
contaner-id not included in hostname generation anymore

**Steps to reproduce the issue:**
1. docker run -it --rm  --hostname=.lx.labs.com debian:jessie bash -c 'echo $HOSTNAME && hostname'
2.
3.

**Describe the results you received:**
.lx.labs.com
.lx.labs.com

**Describe the results you expected:**
{containerid}.lx.labs.com
{containerid}.lx.labs.com

**Additional information you deem important (e.g. issue happens only occasionally):**
this used to work, not sure which version it stopped. still have containers running where hostnames were set this way.

**Output of `docker version`:**
```
root@docker-03:~# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
root@docker-03:~# docker info
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 96
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 114
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: zwtkwrynvnkvis6mjckyu9weg
 Is Manager: false
 Node Address: 192.168.16.73
 Manager Addresses:
  192.168.16.71:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.87 GiB
Name: docker-03
ID: GQ4D:DZFT:4FYF:4EHP:QWJK:QNVX:KW5A:WERK:CB22:KLML:LCOB:TL2O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-02-28 15:37
I suspect this changed a year ago in docker 1.11 (https://github.com/docker/docker/pull/20200), but AFAIK, making `.foo.bar` set the hostname to `<container-id>.foo.bar` was a bug, and not by design.

**Comment by lazedo** [comment] 2017-02-28 16:01
@thaJeztah thanks for looking into this. AFAICS that pull request changed the behavior but it didn't give an alternative. i don't see a way to set a container domain name. do you have an alternative ?

**Comment by thaJeztah** [comment] 2017-02-28 16:21
There's currently no option in the CLI to set the domain name separately from the hostname (see https://github.com/docker/docker/issues/27067); the API does have this option, but it's not "patched through" to the CLI.

I don't think there's a strong objection against adding such flag, so if someone is interested in implementing it, it's likely accepted

**Comment by justincormack** [comment] 2017-03-01 00:00
The domain name issue is quite complicated alas, due to the several meanings of domain name in Linux, but we should fix it.

**Comment by lazedo** [comment] 2017-07-31 18:23
@thaJeztah @justincormack Hi, any update on this ? adding a --domainname to the cli would be great

**Comment by thaJeztah** [comment] 2017-09-19 11:20
Let's close this one in favour of https://github.com/moby/moby/issues/27067, which is discussing adding a separate flag to set the domainname.

**Closed by thaJeztah** 2017-09-19 11:20 UTC
Labels: area/networking, version/1.13
