### ISSUE TITLE
awslogs: dockerd keeps trying to create already created log group for containerlogs causing the throttling exception for CreateLogStream API call

### ISSUE THREAD

**Issue by vbhatt91** [moby/moby#48522] opened 2024-09-18 07:49 UTC
### Description

After the docker version upgrade to 25.0.6 noticing the 'Log stream already exists' info multiple times. It is  causing the throttling exception for CreateLogStream API call.

### Reproduce

Enable the awslogs agent on ECS optimized image and enable the awslogs log driver in ECS task definition with docker version  25.0.6.

### Expected behavior

Log stream already created should not trigger a new log stream creation API by the dockerd. 

### docker version

```bash
Client:
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.22.5
 Git commit:        5dc9bcc
 Built:             Mon Jul 29 17:21:34 2024
 OS/Arch:           linux/amd64
 Context:           default
```

### docker info

```bash
Client:
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.22.5
 Git commit:        5dc9bcc
 Built:             Mon Jul 29 17:21:34 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.6
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       b08a51f
  Built:            Mon Jul 29 17:22:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.11
  GitCommit:        4bccb38cc9cf198d52bebf2b3a90cd14e7af8c06
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment] 2024-09-18 08:49
cc @austinvazquez - looks like probably one of your builds, and related to awslogs

**Comment by vbhatt91** [comment] 2024-09-18 11:27
Adding more context that with previous docker version 20.X , there is no such issues reported.

**Comment by thaJeztah** [comment] 2024-09-18 11:41
Possible candidates;

- docker 23.0; github.com/aws/aws-sdk-go v1.31.6 https://github.com/moby/moby/commit/ace606fd75bd906fcadb47e8c23118ebbb591539 / https://github.com/moby/moby/pull/43288
- docker 24.0; github.com/aws/aws-sdk-go v1.37.0 https://github.com/moby/moby/commit/2cc6a86fd3f3fb6f27ffd93382e6ee4633f699e0 / https://github.com/moby/moby/pull/44516
- :warning: docker 24.0; github.com/aws/aws-sdk-go-v2 v1.16.13 (github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs v1.15.17) https://github.com/moby/moby/commit/c12d7b6d210032fb35d7b9a7edc38b1bb72be500 / https://github.com/moby/moby/pull/44087
- docker 24.0; github.com/aws/aws-sdk-go-v2 to v1.24.1 (no change in cloudwatchlogs) https://github.com/moby/moby/commit/999f90ac1c9652dd34bd594c297d4fb1499c8857 / https://github.com/moby/moby/pull/47373
- :x: (not yet in 25.0) docker 26.0; github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs v1.32.0 https://github.com/moby/moby/commit/70a4a9c96981c1705169577e87ffabfbb2436497 / https://github.com/moby/moby/pull/47373


My prime suspect would be the update to AWS SDK v2;

- https://github.com/moby/moby/pull/44087

**Comment by vbhatt91** [comment] 2024-09-18 11:50
It looks like error is coming as per the code mentioned [here](https://github.com/moby/moby/blob/627bbd3fa48b186170931404c9637ade9b854774/daemon/logger/awslogs/cloudwatchlogs.go#L493-L524). 

But I do not see any logic to skip if the log group OR log stream already created.

**Comment by thaJeztah** [comment] 2024-09-18 13:01
Good one; it looks like an option was added in https://github.com/moby/moby/commit/d10046f228e4152b12bb6ce7db0008f227b95790;

- https://github.com/moby/moby/pull/42132

Not sure if that's exactly what's needed for your case (as in; I _think_ that option disables creating altogether, and not "create if not exist, otherwise skip").

I also noticed that I left a comment that it was possibly never added to the documentation (but haven't checked if it was added in the meantime); https://github.com/moby/moby/pull/42132#issuecomment-882606980

**Comment by thaJeztah** [comment] 2024-09-18 13:15
> I think that option disables creating altogether, and not "create if not exist, otherwise skip"

Ugh; ignore me; looks like that's already the case, so it doesn't fail (ignores the "already exists"), for the _stream_ but because of that may run into the throttling issue https://github.com/moby/moby/blob/627bbd3fa48b186170931404c9637ade9b854774/daemon/logger/awslogs/cloudwatchlogs.go#L521-L525

Same for group; https://github.com/moby/moby/blob/627bbd3fa48b186170931404c9637ade9b854774/daemon/logger/awslogs/cloudwatchlogs.go#L481-L485


Right, so basically the request in this ticket would be to, instead of "opportunistically" create the stream and group (then gracefully handle the error), to instead check if the stream exists before trying to create it.

I'm not familiar enough with the API to know if that would still result in throttling (querying if the stream exists); also not sure if doing so could result in possible race conditions (TOCTOU); i.e. is it possible for the stream or group it to exist, but removed before the container tries to use it? (or is there some "lease" mechanism to get a claim on it?)

**Comment by austinvazquez** [comment] 2024-09-18 14:45
Hi @vbhatt91, thanks for the report. The challenge with checking at runtime for stream already exists is the default TPS for read is **less** than the create API. (ref: [create API doc](https://github.com/aws/aws-sdk-go-v2/blob/de2c35f1c49b22b5a06f4bcb3914f662f994a171/service/cloudwatchlogs/api_op_CreateLogStream.go#L14-L22), [read API doc](https://github.com/aws/aws-sdk-go-v2/blob/de2c35f1c49b22b5a06f4bcb3914f662f994a171/service/cloudwatchlogs/api_op_DescribeLogStreams.go#L15-L24))

So adding logic to check for stream already exists would likely cause more issues than it would resolve. Let me take the action to open a PR for adding the `awslogs-create-stream` to documentation. This may be a workaround for your use case; the result is the docker daemon will skip stream creation entirely and will expect the log stream to already exist.

**Comment by austinvazquez** [comment] 2024-09-18 15:48
@vbhatt91, I opened https://github.com/docker/docs/pull/20928 and cc: you there. PTAL.

**Comment by thaJeztah** [comment] 2024-10-03 19:00
closing, because https://github.com/docker/docs/pull/20928 is merged, and should be published on docs.docker.com soon

**Closed by thaJeztah** 2024-10-03 19:00 UTC
Labels: area/logging, status/0-triage, kind/bug, version/25.0

**Comment by Shubhranshu153** [comment] 2025-02-18 23:33
Trying to understand the root cause of this issue, all though it says it is due to repeated attempts to create the log streams, i am not sure why its trying to do repeated log stream creations. The call to create log streams is probably coming from create container, restart containers or exec containers. Seeking inputs into any cases where repeated call can be made to these functionalities.
