### ISSUE TITLE
docker build  process stucks.

### ISSUE THREAD

**Issue by jackymail** [moby/moby#34903] opened 2017-09-20 07:56 UTC
I wanna to contribute to the moby community,and follow the instructions in the  following link: https://docs.docker.com/opensource/project/set-up-dev-env/#task-2-start-a-development-container

after running  the command "make BIND_DIR=. shell",and the process proceed to the 11th step,the 
build process begin to stuck and never move on.
 Using cache
 ---> a8625d2ebc04
Step 10/47 : ENV GO_VERSION 1.8.3
 ---> Using cache
 ---> b153244d2e72
Step 11/47 : RUN curl -fsSL "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" 	| tar -xzC /usr/local
 ---> Running in 25a91533effb

-->

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-10-24 11:06
Thanks for reporting; I am not able to reproduce this problem; could this be cause by a networking issue (or slow networking) in your setup?

Given that this doesn't look like a bug, I'm closing this issue, but we can continue the conversation here if you still have this problem.

**Closed by thaJeztah** 2017-10-24 11:06 UTC
Labels: area/builder
