### ISSUE TITLE
LetsEncrypt and Docker Swarm

### ISSUE THREAD

**Issue by pjebs** [moby/moby#35607] opened 2017-11-27 08:21 UTC
For some reason, I can't get Docker swarm's built in load balancer to have a SSL connection.

Am I missing something or is that by design?

If it's by design, is the best solution forward to create an independent service which is just a NGINX as a reverse proxy and somehow get LetsEncrypt to work on it and automatically renew certificates?

**Comment by thaJeztah** [comment] 2017-11-30 05:22
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)


If you think there's a bug, provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.


I'm closing this issue because of the above, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-11-30 05:22 UTC
Labels: area/swarm
