### ISSUE TITLE
Image corruption after Docker save and then docker import 

### ISSUE THREAD

**Issue by sbezverk** [moby/moby#34921] opened 2017-09-21 17:28 UTC
After building an image and testing it, I run "docker save -o ~/image.tar" and then restore it "docker import  ~/image.tar image:v1.0" the resulting image seems to be corrupted as no any binaries can be found.

**Steps to reproduce the issue:**
1. build image 
2. docker save -o ~/image.tar
3. docker import  ~/image.tar image:v1.0

**Describe the results you received:**

[root@kube-3 kubernetes]# docker run -ti 10d5b1d93de5 bash 
/usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n".

**Describe the results you expected:**
[root@kube-3 kubernetes]# docker run -ti e265eca41ec3  bash
[root@7563932c1e27 /]# 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
[root@kube-3 kubernetes]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Sep  7 18:00:07 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Sep  7 18:00:07 2017
 OS/Arch:         linux/amd64
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-09-21 17:33
This is because you're combining the wrong commands: `docker save` is the counterpart to `docker load`, whereas `docker export` is the counterpart to `docker import`. They both output a tar, but in a different format.

We looked at verifying if the right type of tar was provided, but this caused a huge amount of overhead, so was decided not to implement.

closing, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-09-21 17:33 UTC
Labels: area/runtime, version/1.12

**Comment by sbezverk** [comment] 2017-09-21 18:05
@thaJeztah you were right, thanks..

**Comment by thaJeztah** [comment] 2017-09-21 19:07
You're welcome! You're not the first one to make this mistake, but unfortunately we cannot realistically improve the situation (as explained above)

**Comment by sbezverk** [comment] 2017-09-21 19:31
Maybe as a suggestion,  when user runs docker import --help or docker load --help or docker same --help or docker export --help, the help would have a sort of note stating that reverse function would be "blah". In this case at least user have a clue what command as reverse action exists.

**Comment by thaJeztah** [comment] 2017-09-21 19:56
Yes, I think that would help; I actually think that was discussed at some point, but I don't think I have seen a pull request implementing it.

If you have thoughts on wording for that, perhaps you're interested in opening a pull request? The files containing the description are located here: https://github.com/docker/cli/tree/master/cli/command/image (or open an issue in that repository to track)?

**Comment by sbezverk** [comment] 2017-09-21 20:13
Sure, I will push PR for review..

**Comment by sbezverk** [comment] 2017-09-22 15:26
https://github.com/docker/cli/pull/550
