### ISSUE TITLE
Containers not removed after docker stack rm

### ISSUE THREAD

**Issue by gouravgupta92** [moby/moby#32620] opened 2017-04-14 07:04 UTC
Hi,

I am using `Docker version 17.03.0-ce, build 60ccb22`.
I had deployed one service using `docker stack deploy -c stack_file.yml STACK_NAME`.

To remove stack i am using `docker stack rm STACK_NAME`.
After running this command i am not able to see stack name in `docker stack ls` and services of stack is also not present in `docker service ls`.
but some containers related to stack services are still present, now if i am trying to remove the container using `docker rm` its again restarting those containers due to resiliency.

How to stop those dangling containers.

**Comment by vdemeester** [comment] 2017-04-14 09:51
/cc @aaronlehmann @dnephin 

@gouravgupta92 could you provide more information about your setup ? (like `docker info`, `docker node ls`, the compose file if possible, etc..)

**Comment by gouravgupta92** [comment] 2017-05-22 06:33
these are the setup configurations : 

output of ```docker info```
```
Containers: 430
 Running: 49
 Paused: 0
 Stopped: 381
Images: 125
Server Version: 17.03.1-ce
Storage Driver: devicemapper
 Pool Name: vgpool-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 94.88 GB
 Data Space Total: 123.7 GB
 Data Space Available: 28.81 GB
 Metadata Space Used: 34.6 MB
 Metadata Space Total: 218.1 MB
 Metadata Space Available: 183.5 MB
 Thin Pool Minimum Free Space: 12.37 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 56
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: sqcyhkxht42axyia3kgyihk20
 Is Manager: true
 ClusterID: pdd77r1ffau5m0dcyciit54rh
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.73.96.121
 Manager Addresses:
  10.73.53.144:4000
  10.73.96.121:4000
  10.73.96.215:4000
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: BLFUTIAPL279.ad.test.com
ID: 6LS2:RTLU:2VGN:KOPX:KHWC:QM54:4GT3:BNH4:Q4KL:3ZPP:FGJT:JJIH
Docker Root Dir: /datadisk/paas/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://paas2:123++++@10.68.248.34:80
Https Proxy: http://paas2:123++++@10.68.248.34:80
No Proxy: .testapp.dev,.testapp.qa,.testapp.aqua,10.73.97.3,10.73.97.4,10.73.97.5,ad.test.com,10.73.96.121,,10.73.96.214,,10.73.96.215
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


output for ```docker node ls```
```
ID                           HOSTNAME                       STATUS  AVAILABILITY  MANAGER STATUS
4lhviefqpqttasxy2c3zltkti    BLFUTIAPL859.ad.test.com  Down    Active        Unreachable
qourzshjrinf895nsdmiv47u9    BLESESAPL293.ad.test.com  Down    Active        Leader
sqcyhkxht42axyia3kgyihk20 *  BLFUTIAPL279.ad.test.com  Ready   Active        Reachable



compose file : 

```
version: "3"
services:
  mongo:
    image: registry.evfapp.dev/alpine-mongo
    networks:
      - refapp
    ports:
      - "27017"

  web:
    entrypoint: sh tools/startup.sh
    image: registry.evfapp.dev/testapp:latest
    depends_on:
      - mongo
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 60s
    environment:
      VIRTUAL_HOST: "https://testapp.evfapp.dev,testapp.evfapp.dev"
      SERVICE_PORTS: "3000"
      FORCE_SSL: "yes"
    networks:
      - refapp
      - router_network
    healthcheck:
      test: "curl http://0.0.0.0:3000/login"
      interval: 1m30s
      timeout: 3s
      retries: 5

networks:
  refapp:
  router_network:
    external: true
```

**Comment by thaJeztah** [comment] 2017-05-22 11:09
Are you always able to reproduce this?

> now if i am trying to remove the container using docker rm its again restarting those containers due to resiliency.

This sounds odd; containers are only re-created if there's still a service monitoring them, so I'm wondering what would be restarting/recreating them

**Comment by gouravgupta92** [comment] 2017-05-22 11:14
I am not able to reproduce it as it happened twice or thrice in last 15 days..
It was a strange issue, since service is not there but container related to service is present.

**Comment by thaJeztah** [comment] 2017-05-22 12:28
@dongluochen any idea how this could happen?

**Comment by aaronlehmann** [comment] 2017-05-22 17:50
cc @dperny

**Comment by ph-One** [comment] 2017-11-07 18:35
I regularly have "left-overs" when performing `docker stack rm`; to the point where I've scripted the pruning/removal of `containers`, `networks`, and `volumes` used by my stack(s). Really makes a mess of CI/CD jobs...

```
CONTAINER ID      IMAGE          COMMAND             CREATED        STATUS
68608f138038      <image_id>     "/usr/local/b..."   5 hours ago    Exited (137) 10 minutes ago
```

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 201
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: q7hju98s9qwqdbci9ubnuzr0q
 Is Manager: true
 ClusterID: k9bef0fm31eo8vkwpntqikh4j
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.77.241
 Manager Addresses:
  192.168.77.241:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.10-200.fc26.x86_64
Operating System: Fedora 26 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 46.85GiB
ID: ADML:HU2R:SHNO:L5D7:UZNH:4SNS:JQHA:THR6:EJBQ:UTDY:JT7C:Y2PW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 150
 System Time: 2017-11-07T13:24:39.714159256-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by harry75369** [comment] 2017-11-10 06:00
Same problem here. I have to do `docker rm $(docker ps -a -q)` every time after stack removal.

**Comment by mysteryegg** [comment] 2018-01-05 14:54
I recently started encountering this on a CentOS 7.4 cluster running docker 17.12.0-ce, build c97c6d6. The master has leftover stopped containers, and the other nodes have leftover running containers. I am attaching the relevant journalctl output from the master. Note that the non-zero exit is due to an invalid configuration file mounted in my prometheus container and not a consequence of the rm command.

[docker-stack-rm.log](https://github.com/moby/moby/files/1606896/docker-stack-rm.log)

**Comment by Hermain** [comment] 2018-01-16 12:27
I have also encountered it with 17.12.0 on ubuntu 16.04 on a one node swarm.

**Comment by deeky666** [comment] 2018-01-17 15:25
I am facing this, too with 17.12.0. From the syslog it looks like tasks cannot be removed because the connected network cannot be found somehow:

```
time="2018-01-05T09:04:29.158277900-05:00" level=error msg="network foo_monitoring remove failed: network foo_monitoring not found" module=node/agent node.id=v46mxv2to41857nvynf70f20p
time="2018-01-05T09:04:29.158331300-05:00" level=error msg="remove task failed" error="network foo_monitoring not found" module=node/agent node.id=v46mxv2to41857nvynf70f20p task.id=7nwrjdo801ntvjh98pqy9v227
```

**Comment by foleymic** [comment] 2018-01-25 01:21
I'm not sure that the original problem on this ticket, reported with 17.03 is the same as the issue I'm seeing on multiple environments, which is exactly the same issue described above since 17.09.  @vdemeester, can we get the `need more info` label removed from this ticket, unless there is anything more specific you need?

**Comment by richardjq** [comment] 2018-01-31 14:03
+1
Docker version 17.12.0-ce, build c97c6d6 on RHEL 7.4.

`docker stack rm` removes the stack and the service, but leaves orphan containers running in the swarm. 

Comparing `docker inspect` between a container that is legitimately part of the swarm and an orphaned container shows that the orphans now have `"Isolation": "",` (as opposed to the normal "default") as if it were started using `docker run`.

This is causing serious problems with our ability to redeploy/restart services in the swarm.

**Comment by foleymic** [comment] 2018-01-31 14:21
@richardjq I've started tracking this issue here: https://github.com/moby/moby/issues/35933#issuecomment-361726397

**Comment by richardjq** [comment] 2018-01-31 14:28
@foleymic #35933 seems similar, but I'm not experiencing the "hang" effect described there.

I _am_ running docker-in-docker when I issue the `docker stack rm` and `docker stack deploy` commands (if that makes a difference).

**Comment by foleymic** [comment] 2018-01-31 14:43
@richardjq - when you say docker-in-docker, I assume you mean that only the client is running inside the docker container and the daemon is on the host (e.g. you are mounting docker.sock into your container  `-v /var/run/docker.sock:/var/run/docker.sock`)?  I don't think that would make a difference, but good to know.

Regarding the **hang** issue, I'm not seeing that every time, maybe 25% of the time when a container that was created through a `stack deploy` command is left running versus exited.  When I see that, I usually have to issue a kill -15 on the PID to regain control.  Note that not all docker commands are hanging, just the ones that have to work against this container (e.g. `inspect`) - `docker ps`.   

Anyway, it's probably a good idea to watch both of these tickets - I suggested #35933 because it's getting more activity.

**Comment by michaelsbradleyjr** [comment] 2018-01-31 15:30
I'm experiencing the same with Docker for Mac `18.02.0-ce-rc1-mac50 (22256) (Channel: edge) 8b4cf93981`.

Related, `stack rm` leaves behind orphan volumes for which `docker volume inspect` provides no information to tie them to a specific stack. That means that deleting them one-by-one after `stack rm` is problematic – how to know which one/s to delete? `docker volume prune` works, but that's a bit drastic and would remove volumes that I may not want to remove, even if they're not associated at the time with a running container.

**Comment by richardjq** [comment] 2018-01-31 17:59
@foleymic - yes, that's correct. I'm mounting in docker.sock in order to issue docker commands to the cluster.

**Comment by photostu** [comment] 2018-02-05 20:26
+1 on this being incredibly problematic, trying to run 48 replicas across 8 machines, just discovered this was happening today. super bummed

**Comment by photostu** [comment] 2018-02-06 18:38
As a workaround, I have found the following to be helpful:
Before you attempt to stack rm, spin down all of your replicas with service update --replicas 0 <servicename>
For me, I have a lot of a particular service running and attempted to spin down from 48->0, this mostly worked, I still had some services running, so then I did another spin down to ->1 this brought it down to 1, then I spun down to 0 ok, then I could perform a stack rm properly. You may have to play with spinning down replicas depending upon your setup. Hope this helps someone out!

**Comment by aselvan** [comment] 2018-02-09 23:59
I found a workaround that works for me but I am not sure this is an option for others. The wrapper script in my image catches SIGTERM, in the handler, besides doing the cleanup needed for my app, I made it sit around 15 sec so... I believe that is the time docker waits between the delivery of SIGTERM and a force SIGKILL. When it sends SIGKILL it removes the container. This is a hack but I am hoping this bug is fixed soon. I am on `17.12.0-ce`.

**Comment by jmarcos-cano** [comment] 2018-02-22 18:32
Im experiencing the same issue 17.12.0-ce in CentOS 7 (kernel 3.10.0-693.11.6.el7.x86_64) have almost 16 swarms out there, and time by time im seeing this dangling containers. It is blocking our CI/CD pipeline because it happens when:

- Update service version (new deployment)
- Remove the entire stack

I can not attach or exec any commands in the containers, can not remove or the stop the containers, service is not there, stack is not there but network is still there, I can not remove network due to

`Error response from daemon: network dispatch_default id t3ah1ufnpa89cmc9nwj1hc2jb has active endpoints`

the only solution for me is to restart the service (after demoting the node and removing the node from the swarm), but that is not something I want to do in production environments.

**Comment by dperny** [comment] 2018-02-22 19:36
There's a decent chance this is related to the issue that will be fixed by docker/swarmkit#2499, but there's a chance it won't. We should see if this is still happening after that patch goes in.

**Comment by cambierr** [comment] 2018-02-23 20:11
Just as a temporary workaround, I wrote this script that I just to "clean" orphaned containers:
```bash
docker node ls --format '{{.ID}}' | xargs docker node inspect --format '{{.Status.Addr}}' | while read node; do

  echo "Processing node $node"

  ssh -n $node "docker ps -a --filter 'is-task=true' --format '{{.ID}} {{.Label \"com.docker.stack.namespace\"}}'" | while read container; do
    
    id=$(echo $container | cut -d ' ' -f1)
    stack=$(echo $container | cut -d ' ' -f2)
    
    found=$(docker stack ls | grep $stack | wc -l)
    
    if [ $found == "0" ]; then
        echo "no stack $stack found for container $id"
        ssh -n $node "docker rm -f $id"
    else
        echo "found stack $stack for container $id"
    fi

  done
done
```

I wrote it in a few minutes so it's far from being perfect (understand: "do not use it for sensitive swarms") but feel free to use it...

**Comment by jmarcos-cano** [comment] 2018-02-28 04:10
after reading the release notes, Im wondering if this related to task_reaper https://github.com/docker/swarmkit/pull/2477/files
?

**Comment by adammbalogh** [comment] 2018-09-20 11:08
Same here.

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by StephenOTT** [comment] 2018-10-03 21:56
Same... This seems like a very significant issue? of continually orphaned containers...

**Comment by gerbil** [comment] 2018-10-05 06:14
Same on Centos
`
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

**Comment by dtitov** [comment] 2018-10-25 12:15
Same problem, MacOS.
Engine: 18.06.1-ce.
Any update?

**Comment by sido420** [comment] 2018-11-11 03:37
same issue on Server Version: 18.06.1-ce
Kernel Version: 4.13.0-46-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64

**Comment by olljanat** [comment] 2018-11-12 21:40
@drnic / @sido420 do you get any warnings/errors from ```docker stack rm``` command when this happens?

**Comment by olljanat** [comment] 2018-11-15 13:36
Ahaa so it is network removal issue. That issue and possible solutions to it have been explained on:
 https://gist.github.com/dperny/86bb33f195e4a3c27bbc497372652994

Afaik swarm team is working on it but it is not easy thing to solve.

**Comment by thaJeztah** [comment] 2018-11-15 14:03
`docker stack rm` triggers a `docker service rm` (and `docker network rm`).  Those are executed _asynchronously_, so although the `docker stack rm` returns "immediately", the removal is still happening in the background (as part of the reconciliation loop of the swarm cluster)

The solution for that would be to implement a `--detach=false` option, to make the `docker stack rm` "interactive", and for the command to wait for the services/networks to be actually removed (see https://github.com/docker/cli/issues/373)

**Comment by iNevd** [comment] 2019-01-19 05:39
The left containers cannot remove, inspect, exec

the only way to remove it is

"find the <process id> for this container, then kill -9 <process id>"


Docker version : 18.09.0 linux/amd64

PS: this problem will hung up [standalone swarm](https://github.com/docker/swarm/blob/1d9a0d06e2137ca9e10414d11b5ea47c504d5278/cluster/engine.go#L877)

**Comment by olljanat** [comment] 2019-01-19 06:12
@iNevd this is over two years old issue which contains discussion about multiple different issues which have similar symptoms but most likely different root cause. (On original message user was able stop and remove containers with docker stop/rm)

So can you plz create new issue where you share all the details which Linux you are using, if you have some special configurations and especially which kind of workloads you are using which with issue occurs? (and of course all details which asked on template).

**Comment by carlwain74** [comment] 2019-06-11 16:41
I'm running latest docker-ce on Ubuntu 16.04 and I occasionally see this happen and it happens to random containers in my stack.

`(aws) [root@ip-10-232-103-105 SAFR]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: y5r1xksrf6gly5fzjsvv130ed
 Is Manager: true
 ClusterID: z2z92jmoysdqy5wpmplyw86co
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.232.103.105
 Manager Addresses:
  10.232.103.105:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.466GiB
Name: ip-10-232-103-105.us-west-2.compute.internal
ID: YIE5:V4UZ:AGNW:E4C7:UKXC:3CQN:Y5UJ:UO7E:WFSC:NSHV:SMNK:L7VR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine`

**Comment by krhubert** [comment] 2019-10-07 14:43
any news on that one?

**Comment by thaJeztah** [comment] 2019-10-07 15:03
No change, but if someone is interested in implementing a `--detach` flag in the docker cli (https://github.com/docker/cli), that could resolve the issue (see https://github.com/moby/moby/issues/32620#issuecomment-439050180)

**Comment by pro-gramming** [comment] 2021-09-19 07:04
> r

Hey  richardjq,
Were you able to work your way out this issue? Please do let me know.

**Comment by pro-gramming** [comment] 2021-09-19 07:04
> +1
> Docker version 17.12.0-ce, build c97c6d6 on RHEL 7.4.
> 
> `docker stack rm` removes the stack and the service, but leaves orphan containers running in the swarm.
> 
> Comparing `docker inspect` between a container that is legitimately part of the swarm and an orphaned container shows that the orphans now have `"Isolation": "",` (as opposed to the normal "default") as if it were started using `docker run`.
> 
> This is causing serious problems with our ability to redeploy/restart services in the swarm. What do we need to do to get the more-info-needed tag removed and get this assigned? (I'm willing to provide all of the details I can)

Hey richardjq,
Were you able to work your way out this issue? Please do let me know.

**Comment by bsousaa** [comment] 2023-05-02 09:27
I'm closing this issue since it is quite old and impacts an old version of Moby. Please open a new issue if it happens with a recent version.

> `docker stack rm` triggers a `docker service rm` (and `docker network rm`). Those are executed _asynchronously_, so although the `docker stack rm` returns "immediately", the removal is still happening in the background (as part of the reconciliation loop of the swarm cluster)
> 
> The solution for that would be to implement a `--detach=false` option, to make the `docker stack rm` "interactive", and for the command to wait for the services/networks to be actually removed (see [docker/cli#373](https://github.com/docker/cli/issues/373))

**Closed by bsousaa** 2023-05-02 09:27 UTC
Labels: status/more-info-needed, area/swarm, area/stack
