### ISSUE TITLE
Stack deploy not allowing ENV variables for integer values

### ISSUE THREAD

**Issue by jaredm4** [moby/moby#32212] opened 2017-03-29 20:20 UTC
**Description**
Cannot supply value for `replicas` from environment variables during `docker stack deploy`, as it complains the environment variable is not an integer (and no documented way to force an integer).

**Steps to reproduce the issue:**
1. Create compose version 3.1 file with a service with a deploy & replica section, where the value for replicas is using a variable, with or without a default (see provided sample config).
2. Run a stack deploy with a provided environment variable, or use the default value for the variable in the compose file.

**Describe the results you received:**

```
$ REPLICAS=1 docker stack deploy -c test-compose.yml test
services.redis.deploy.replicas must be a integer
# or with the default value:
$ docker stack deploy -c test-compose.yml test
services.redis.deploy.replicas must be a integer
```

**Describe the results you expected:**

To accept that the fact that REPLICAS environment variable is a string, but verify and allow the value if it can be treated as an integer. Same for variables that have a default value.

**Additional information you deem important (e.g. issue happens only occasionally):**

My test-compose.yml from above.

```
version: '3.1'

services:
  redis:
    image: redis
    deploy:
      replicas: ${REPLICAS:-1}
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 79
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 134
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: wrkh6nb5hoelqjjy0qkx62xrj
 Is Manager: true
 ClusterID: q5a1qw2bcj8cn7gmwsdgp19i9
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: YKZ3:M2MK:CKR6:ZC65:RDXM:22SB:WFXC:32T2:AD55:QQXF:C4FR:43FO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 130
 System Time: 2017-03-29T20:18:03.330922883Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running Docker for Mac stable, OS X  10.11.6

**Comment by dnephin** [comment] 2017-03-29 21:44
Yes, this is unfortunate, but it's also an issue with the Compose implementation.

**Comment by jaredm4** [comment] 2017-03-29 21:57
How does Docker recommend people to do a stack deploy update when they need to change their compose file originally used to deploy said stack? I know I can use `docker service update` to do automate common changes like image:tag or replica counts, but if someone adds a new service to the compose file that I need to re-deploy, it's going to re-set the number of replicas on the existing services.

That was my goal with setting up this workflow: a) find current number of replicas for each service. b) stack deploy, using env vars to  ensure the same number of replicas are up and running.

If I go the route of `docker stack deploy` (resetting replica amount to default), then `service update --replicas X`, it could be very disruptive.

**Comment by GabKlein** [comment] 2017-05-09 13:36
I don't know how complected it would be to force the casting of a string into an integer but it seems achievable. @dnephin could you point us toward the right direction so we can propose a fix?

**Comment by cpuguy83** [comment] 2017-05-09 13:45
@jaredm4 Maybe not understanding the issue, but you can specify the number of replicas in the compose file and `docker stack deploy` again.

You should not have to `docker service update`, you only update the yaml file and redeploy. Docker handles making the right API requests.

**Comment by DBLaci** [comment] 2017-05-09 14:00
The problem is the ENV is always string, and the replica has to be integer (type). The fix is to simply cast the replica to integer if it is string (because of the ENV, or "2" in the compose file)

**Comment by dnephin** [comment] 2017-05-09 14:49
The only proposal I've seen to fix this is to use the jsonschema to determine the type of a field. When the config is being traversed to perform interpolation we could traverse the jsonschema at the same time, and pass in the expected type for values.

**Comment by rreinurm** [comment] 2017-05-23 09:40
Should this issue to be recreated under docker/cli project?

**Comment by samattridge** [comment] 2017-07-28 15:21
Is this issue likely to receive any attention?  It's unfortunately causing me pain too.

**Comment by jaredm4** [comment] 2017-07-28 17:18
@samattridge I don't know if there's been any churn on Docker's side, but I ended up writing a solution into my deploy tool to find/replace any environment var that ended in _REPLICAS prior to handing it off to Docker Swarm. I don't like the solution, but it works and allows me to just strip that code out when Docker CE finally supports those values.

**Comment by rreinurm** [comment] 2017-07-30 11:01
Should continue discussion here as cli is in separated repo https://github.com/docker/cli/issues/229

**Comment by thaJeztah** [comment] 2017-07-30 13:08
> Is this issue likely to receive any attention? It's unfortunately causing me pain too.

I someone wants to work on this, and has a clean way to implement, it'll likely be accepted

**Comment by samattridge** [comment] 2017-07-31 09:29
Thanks @jaredm4.  I'll do the same.  And thanks @rreinurm. I'll make sure I comment any additional information on this in the cli repo.

**Comment by thaJeztah** [comment] 2017-07-31 09:39
let's close this issue here, and continue in https://github.com/docker/cli/issues/229

**Closed by thaJeztah** 2017-07-31 09:39 UTC
Labels: area/bundles, platform/desktop, version/17.03
