### ISSUE TITLE
Feature request: exclude/ignore files/folders with docker build command

### ISSUE THREAD

**Issue by ORESoftware** [moby/moby#37159] opened 2018-05-26 22:43 UTC
I am looking at these docs for `docker build`:
https://docs.docker.com/engine/reference/commandline/build/

Essentially, I need more than one `.dockerignore` file. So one thing I can do is specify the contents of dockerignore at the command line. Something like:

```bash
docker build --exclude="node_modules" -f Dockerfile.r2g -t "$tag" .
```

or

```bash
docker build --ignore="node_modules" -f Dockerfile.r2g -t "$tag" .
```

However this does not seem to be possible yet.

**Comment by ORESoftware** [comment] 2018-05-26 22:44
this is related to:
https://github.com/moby/moby/issues/12886

and:
https://stackoverflow.com/questions/40904409/how-to-specify-different-dockerignore-files-for-different-builds-in-the-same-pr

**Comment by thaJeztah** [comment] 2018-05-26 23:45
As you mentioned, this is largely a duplicate of https://github.com/moby/moby/issues/12886, so let me close this one so that the discussion doesn't diverge; feel free to participate in the discussion there

You may be interested in https://github.com/moby/moby/issues/37129 as well

**Closed by thaJeztah** 2018-05-26 23:45 UTC
Labels: area/builder
