### ISSUE TITLE
image_load returns 200 even when error occurs for "no space left on device"

### ISSUE THREAD

**Issue by lucastheisen** [moby/moby#40220] opened 2019-11-16 19:52 UTC
Currently attempting to use ansibles [`docker_image` module](https://docs.ansible.com/ansible/latest/modules/docker_image_module.html#requirements) (which in turn uses do [Docker SDK for python](https://github.com/docker/docker-py)) and was was seeing success in our log, but the image never got updated.  After much digging, we finally discovered the cause was that the [Docker API call](https://docs.docker.com/engine/api/v1.30/#operation/ImageLoad) is supposed to return a 500 on failure, but instead returns a 200.  Details are described in [this other issue](https://github.com/docker/docker-py/issues/1488#issuecomment-554666565).

**Steps to reproduce the issue:**
1. Fill up filesystem 
2. Invoke the [ImageLoad](https://docs.docker.com/engine/api/v1.30/#operation/ImageLoad) endpoint
3. See HTTP 200

**Describe the results you received:**
HTTP 200

**Describe the results you expected:**
HTTP 500

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-957.27.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 3.699 GiB
Name: example.local
ID: 2UGF:JTKQ:JC6Y:5YIB:NGUF:ESNS:RWQQ:MPIY:3S4S:WHU5:7MPB:EHLR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2019-11-24 01:07
Have you tried to reproduce this on a recent version of Docker? 1.13 is nearly 3 years old.

**Comment by thaJeztah** [comment] 2019-11-25 21:36
Looks like a duplicate of https://github.com/moby/moby/issues/34416. I have a PR to improve this, but there were some issue with that implementation; https://github.com/moby/moby/pull/34425

the problem likely also is that the endpoint can use chunked encoding, so a header is already returned before the entire file has been sent to the daemon.

I'll close this one as duplicate of https://github.com/moby/moby/issues/34416

**Closed by thaJeztah** 2019-11-25 21:36 UTC
