### ISSUE TITLE
Image config file has wrong image 

### ISSUE THREAD

**Issue by tomkcook** [moby/moby#38762] opened 2019-02-20 11:55 UTC
**Description**
When building an image with `docker build .`, the JSON configuration file inside the resulting image contains the wrong image ID in the `config.Image` and `container_config.Image` fields.

**Steps to reproduce the issue:**
This script reproduces the issue:

```
#!/bin/bash

touch f1 f2 f3

cat > Dockerfile <<EOF
FROM scratch
COPY f1 /f1
COPY f2 /f2
COPY f3 /f3
EOF


docker build -f Dockerfile .

IMAGE=$(docker images | head -2 | tail -1 | awk '{print $3}')
docker save ${IMAGE} > image.tar
CONFIGFILE=$(tar xOf image.tar manifest.json | jq '.[0].Config')
CONFIGFILE=${CONFIGFILE#\"}
CONFIGFILE=${CONFIGFILE%\"}
CONFIGID=$(tar xOf image.tar ${CONFIGFILE} | jq '.config.Image')

echo "Docker image ID is ${IMAGE} but config file has image ${CONFIGID}"
echo "Image history:"
docker history ${IMAGE}
```

**Describe the results you received:**
The image ID in the image JSON configuration is different to the image ID docker uses for the image.  The one in the JSON file is in fact the ID of the parent image.

**Describe the results you expected:**
I expected that the JSON would contain the correct image ID in the `config.Image` field.

**Additional information you deem important (e.g. issue happens only occasionally):**
None.

**Output of `docker version`:**
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.1
 Git commit:        e68fc7a
 Built:             Fri Jan 25 14:33:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:49:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
$ docker info
Containers: 62
 Running: 0
 Paused: 0
 Stopped: 62
Images: 520
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.49GiB
Name: newt
ID: TXYZ:BBF3:KHVB:3ZYD:TXO6:RCQH:E7HG:HEUP:5F5C:VATF:NFHB:DUP6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical system on x86_64 hardware.

**Comment by thaJeztah** [comment] 2019-02-20 12:51
Thanks for reporting, and thanks for the useful reproduction script.

I'll ask @tonistiigi to confirm, but wondering if this expected, and if the `Config` is the configuration here that was used for the container that ran to _produce_ the final image (so, that container uses the "parent" image)

One interesting bit though is that when the build is done through buildkit _first_, the property is empty (`null`), but after the same build is done without buildkit (and then ran with buildkit again), it is propagated.

```bash
bash-4.4$ DOCKER_BUILDKIT=1 ./repro.sh 
[+] Building 0.5s (8/8) FINISHED                                                                                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                                                                                       0.2s
 => => transferring dockerfile: 91B                                                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                          0.3s
 => => transferring context: 2B                                                                                                                                                                                                            0.0s
 => [internal] load build context                                                                                                                                                                                                          0.1s
 => => transferring context: 69B                                                                                                                                                                                                           0.0s
 => [internal] helper image for file operations                                                                                                                                                                                            0.0s
 => CACHED [1/3] COPY f1 /f1                                                                                                                                                                                                               0.0s
 => CACHED [2/3] COPY f2 /f2                                                                                                                                                                                                               0.0s
 => CACHED [3/3] COPY f3 /f3                                                                                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                                                    0.0s
 => => writing image sha256:0a630c5560c767063281c8166febb07a6edc64a3ded73b4cfdb0a00adad13fa7                                                                                                                                               0.0s
Docker image ID is 0a630c5560c7 but config file has image null
Image history:
IMAGE               CREATED             CREATED BY               SIZE                COMMENT
0a630c5560c7        8 minutes ago       COPY f3 /f3 # buildkit   0B                  buildkit.dockerfile.v0
<missing>           8 minutes ago       COPY f2 /f2 # buildkit   0B                  buildkit.dockerfile.v0
<missing>           8 minutes ago       COPY f1 /f1 # buildkit   0B                  buildkit.dockerfile.v0
bash-4.4$ DOCKER_BUILDKIT=0 ./repro.sh 
Sending build context to Docker daemon  23.55kB
Step 1/4 : FROM scratch
 ---> 
Step 2/4 : COPY f1 /f1
 ---> 121e8389c310
Step 3/4 : COPY f2 /f2
 ---> 7cfe0c4e0313
Step 4/4 : COPY f3 /f3
 ---> 9c803a534797
Successfully built 9c803a534797
Docker image ID is 9c803a534797 but config file has image "sha256:7cfe0c4e031397ea1b43e3793e5b0fc2d4f2476fb5d4813b974900c7a0983451"
Image history:
IMAGE               CREATED                  CREATED BY                                      SIZE                COMMENT
9c803a534797        Less than a second ago   /bin/sh -c #(nop) COPY file:bdf601b54c39c981…   0B                  
7cfe0c4e0313        1 second ago             /bin/sh -c #(nop) COPY file:9e5f6554005235cc…   0B                  
121e8389c310        1 second ago             /bin/sh -c #(nop) COPY file:27f346c874cdb1c7…   0B                  
bash-4.4$ DOCKER_BUILDKIT=1 ./repro.sh 
[+] Building 0.1s (8/8) FINISHED                                                                                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                                                                                       0.0s
 => => transferring dockerfile: 91B                                                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                                                                            0.0s
 => [internal] load build context                                                                                                                                                                                                          0.0s
 => => transferring context: 69B                                                                                                                                                                                                           0.0s
 => [internal] helper image for file operations                                                                                                                                                                                            0.0s
 => CACHED [1/3] COPY f1 /f1                                                                                                                                                                                                               0.0s
 => CACHED [2/3] COPY f2 /f2                                                                                                                                                                                                               0.0s
 => CACHED [3/3] COPY f3 /f3                                                                                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                                                    0.0s
 => => writing image sha256:0a630c5560c767063281c8166febb07a6edc64a3ded73b4cfdb0a00adad13fa7                                                                                                                                               0.0s
Docker image ID is 9c803a534797 but config file has image "sha256:7cfe0c4e031397ea1b43e3793e5b0fc2d4f2476fb5d4813b974900c7a0983451"
Image history:
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
9c803a534797        11 seconds ago      /bin/sh -c #(nop) COPY file:bdf601b54c39c981…   0B                  
7cfe0c4e0313        12 seconds ago      /bin/sh -c #(nop) COPY file:9e5f6554005235cc…   0B                  
121e8389c310        12 seconds ago      /bin/sh -c #(nop) COPY file:27f346c874cdb1c7…   0B                                 
```

**Comment by tomkcook** [comment] 2019-02-20 14:59
> wondering if this expected, and if the `Config` is the configuration here that was used for the container that ran to _produce_ the final image

It's easy to confirm that this is not the case.  Consider this modified reproduction script:

```
#!/bin/bash

touch f1 f2 f3

cat > Dockerfile <<EOF
FROM scratch
COPY f1 /f1
COPY f2 /f2
COPY f3 /f3
LABEL x="y"
EOF

docker build -f Dockerfile .

IMAGE=$(docker images | head -2 | tail -1 | awk '{print $3}')
docker save ${IMAGE} > image.tar
CONFIGFILE=$(tar xOf image.tar manifest.json | jq '.[0].Config')
CONFIGFILE=${CONFIGFILE#\"}
CONFIGFILE=${CONFIGFILE%\"}
CONFIGID=$(tar xOf image.tar ${CONFIGFILE} | jq '.config.Image')
LABELS=$(tar xOf image.tar ${CONFIGFILE} | jq '.config.Labels')
echo "Container label configuration: ${LABELS}"

echo "Docker image ID is ${IMAGE} but config file has image ${CONFIGID}"
echo "Image history:"
docker history ${IMAGE}
```

The config file in the saved image has the label produced by the last line of the dockerfile, but the image ID in the config file is the ID of the image _before_ the label is applied.

**Comment by tonistiigi** [comment] 2019-02-20 15:40
Image means the ID of an image for a container that executed this step in the legacy build. Image ID is the sha256 of the config (so ID can never exist in the config itself as any modification changes the ID).

> One interesting bit though is that when the build is done through buildkit _first_, the property is empty (`null`), 

Buildkit does not fill this value (nor containerconfig) cause it doesn't run a Docker container for commands. Mostly these fields are leakage from container/image using the same data type in old implementation. There is nothing in the codebase that actually uses this value.

> but after the same build is done without buildkit (and then ran with buildkit again), it is propagated.

You are checking the wrong image in your last example, not the one that BuildKit reports.

**Comment by thaJeztah** [comment] 2023-11-13 11:51
- This is a duplicate of https://github.com/moby/moby/issues/17780
- Documentation was improved in https://github.com/moby/moby/pull/43461, but we may consider removing the `ContainerConfig` from the API response if it wasn't used (i.e., when BuildKit was used to produce the image)

**Closed by thaJeztah** 2023-11-13 11:51 UTC
Labels: area/api, area/builder
