### ISSUE TITLE
centos7x / rel7x - rpm -qi [either docker, docker-latest, or docker-engine]

### ISSUE THREAD

**Issue by johanwasserman** [moby/moby#31463] opened 2017-03-01 20:57 UTC
Products that rely on the "Provides" tag for the docker engine installed, fail to install.
Please include the following in your centos and rel packages;
"Provides: [either docker, docker-latest, or docker-engine]"

**Steps to reproduce the issue:**
`$ rpm -qi docker-engine
Name        : docker-engine
Version     : 1.13.1
Release     : 1.el7.centos
Architecture: x86_64
Install Date: Sat 25 Feb 2017 07:33:23 AEDT
Group       : Tools/Docker
Size        : 67793232
License     : ASL 2.0
Signature   : RSA/SHA512, Wed 08 Feb 2017 19:32:31 AEDT, Key ID f76221572c52609d
Source RPM  : docker-engine-1.13.1-1.el7.centos.src.rpm
Build Date  : Wed 08 Feb 2017 17:41:49 AEDT
Build Host  : 1b0d6163fdc2
Relocations : (not relocatable)
Packager    : Docker <support@docker.com>
Vendor      : Docker
URL         : https://dockerproject.org
Summary     : The open-source application container engine
Description :
...`

"Provides: docker" or "Provides: docker-latest" or "Provides: docker-engine" not included in the output

**Output of `docker version`:**
```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
$ docker info
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.16 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical - airgapped

**Comment by cpuguy83** [comment] 2017-03-01 21:06
I don't think `Provides` is required here.

See https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec#L95 for example.

**Comment by thaJeztah** [comment] 2017-03-01 21:07
I'm not too familiar with these, but given that the package is named `docker-engine`, does it also have to include a `Provides: docker-engine`? That seems a bit double.

The `docker-latest` package is really a Red Hat invention, if packages are depending that package, that sounds like something that needs to be fixed in those packages.

Would you be interested in opening a pull request for discussion? The spec for the RPM packages can be found here; https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec

/cc @vieux @andrewhsu

**Comment by andrewhsu** [comment] 2017-03-02 19:06
When creating an RPM, you do not need a `Provides:` entry with the same name as the RPM. Yum will be able to recognize that a package of that name also `Provides` that ability.

What situation is this causing a problem for you? Are you trying to install another package that is looking to satisfy a docker dependency? If so, what is this package so I may inspect the dependency requirements.

**Comment by flx42** [comment] 2017-03-02 19:14
I think the problem is rather than `docker-ce` **doesn't** seem to `Provides` the `docker-engine` package.
Our deb package was depending on `docker-engine (>= 1.9.0)` and is now broken, it's possible to solve it by doing `docker-engine (>= 1.9.0) | docker-ce | docker-ee` (but it could also have been solved).
AFAIK we have no way to fix that for RPMs since you can't have multiple options for a dependency.

**Comment by josegonzalez** [comment] 2017-04-21 16:39
@flx42 I stole my Dokku fix from [cockpit](https://github.com/cockpit-project/cockpit/pull/6340/files) for RPM and depend upon `/usr/bin/docker`. It means we cannot depend on a minimum docker version, so I would recommend doing version detection within your `post-install` hook and blowing up the install appropriately.

If all three - or four, I don't recall how many renames docker has done over the years with their packaging - packages had a new patch release that required some metapackage - that could be provided wherever those repositories were - that could work, as we could then just depend on the metapackage.

I make a small plea from the kind docker/moby folks to stop renaming the docker deb/rpm packages. It's hella annoying to deal with and breaks any dependency management that downstream project maintainers have. It feels as though I have to deal with this every year, and our users don't know any better so we're always left with the bill.

**Comment by cpuguy83** [comment] 2017-04-21 17:50
I agree we should make CE and EE packages so that they provide `docker-engine`.

**Comment by thaJeztah** [comment] 2017-08-17 15:21
ping @seemethere @andrewhsu what's the status on this one?

**Comment by vdemeester** [comment] 2018-02-14 13:53
gentle ping @andrewhsu @seemethere 👼

**Comment by thaJeztah** [comment] 2023-09-17 20:35
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 20:35 UTC
Labels: area/project, version/1.13, area/packaging
