### ISSUE TITLE
What is the relationship between moby/moby and docker/engine and docker/docker-ce

### ISSUE THREAD

**Issue by ryanlyy** [moby/moby#38063] opened 2018-10-19 07:22 UTC
-----
**Description**
I found there is no branch/tag update from last year on moby/moby project. and docker/engine and docker/cli is forked from moby/moby. from docker/docker-ce components.conf, the upsteam of docker-ce is docker/engine and docker/ci instead of moby/moby.

So does this mean moby/moby project is not maintained?  

Thanks,
Ryan

**Comment by thaJeztah** [comment] 2018-10-19 10:53
the moby/moby repository (this repository) is where all development and maintenance of the engine codebase is done. This repository is an "upstream" for Docker's products (docker ce, docker ee), but other projects or products can also use it as an upstream; for that reason, tags and branches that are specific for Docker's products are not created in this repository.

The docker/engine repository is a fork of moby/moby, but no development takes place in that repository. The docker/engine repository is used to;

- tag releases
- create long-lived release-branches for each release
- backport (cherry-pick) fixes from the upstream (moby/moby) repository to release branches

Occasionally, bug-fixes may first be created in the docker/engine repository, and later upstreamed to moby/moby.


The docker/docker-ce repository is a repository where all the components that are  part of the docker-ce packages come together; that repository is used by the release team to build the packages. No development takes place in that repository, other than creating release-branches, tagging releases, and updating the "components";

- [components/cli](https://github.com/docker/docker-ce/tree/v18.06.1-ce/components/cli) (collected from the https://github.com/docker/cli repository)
- [components/engine](https://github.com/docker/docker-ce/tree/v18.06.1-ce/components/engine) (collected from the https://github.com/docker/engine repository)
- [components/packaging](https://github.com/docker/docker-ce/tree/v18.06.1-ce/components/packaging) (packaging scripts, collected from the https://github.com/docker/docker-ce-packaging repository)

**Comment by thaJeztah** [comment] 2018-10-19 10:54
Please keep in mind that the GitHub issue tracker is not intended as a general discussion forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-10-19 10:54 UTC
Labels: kind/question
