### ISSUE TITLE
it's possible to delete an attachable overlay network while containers on it still exist

### ISSUE THREAD

**Issue by vikstrous** [moby/moby#27639] opened 2016-10-21 18:34 UTC
**Description**

It's possible to delete an attachable overlay network while containers on it still exist.

**Steps to reproduce the issue:**

```
docker network create -d overlay --attachable testnet
docker run -it -d --net testnet --name testcontainer alpine sh
docker network rm testnet
docker network ls
```

**Describe the results you received:**

```
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
...          
a5u9jwds4ntw        testnet             overlay             local 
```

**Describe the results you expected:**
The network shouldn't be deleted. Also, the scope should be swarm.

```
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
...          
a5u9jwds4ntw        testnet             overlay             swarm
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Starting another container on that network fails (but creating it succeeds):

```
docker run -it -d --net testnet --name testcontainer2 alpine sh
9439f15f9207c737481c432bb03d004c78a4cf23929f946cedaa8c227194e518
docker: Error response from daemon: Could not attach to network testnet: rpc error: code = 5 desc = network testnet not found.
```

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.1-cs1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   24231a4
 Built:        Mon Sep 19 00:55:12 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   94cd7ed
 Built:        Mon Oct  3 20:41:39 2016
 OS/Arch:      linux/amd64
```

This is happening on every build of docker with attachable networks AFAIK.

**Output of `docker info`:**

```
$ docker info
Containers: 79
 Running: 22
 Paused: 0
 Stopped: 57
Images: 2135
Server Version: 1.13.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: dfa9b146qgf4ud3qq4vw1niow
 Is Manager: true
 ClusterID: 816g9kn1i9vsf75hgd7ylpdys
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  External CAs:
    cfssl: https://172.17.0.1:12381/api/v1/cfssl/sign
 Node Address: 172.17.0.1
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.7.3
Operating System: NixOS 17.03pre91207.2b0eace (Gorilla)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53 GiB
Name: thisisfine
ID: 4XB6:RAOL:2UT7:W3TT:JBSR:ILHC:LREA:HUVU:5U7V:TI7E:WUT2:WQTS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 213
 Goroutines: 446
 System Time: 2016-10-21T11:33:16.710100545-07:00
 EventsListeners: 2
Username: viktorstanchev
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 172.17.0.1
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by sanimej** [comment] 2016-11-02 05:26
@mavenugo [swarmkit #1724](https://github.com/docker/swarmkit/pull/1724) should fix this issue, correct ?

**Comment by mavenugo** [comment] 2016-11-02 15:40
> @mavenugo swarmkit #1724 should fix this issue, correct ?

Yes. But ideally we would also need https://github.com/docker/swarmkit/issues/440 to go with it.

**Comment by wsong** [comment] 2016-11-02 19:04
I have (finally) been able to repro this issue even when deleting containers before deleting the network. Simply run the following script on a *Swarm-mode* node:

```bash
#!/bin/sh

networkid=$(docker network create -d overlay --attachable testnet)
docker create --name testcontainer busybox:latest sleep 24h
docker network connect --alias asdf $networkid testcontainer && docker start testcontainer
docker rm -f testcontainer && docker network rm testnet
docker network ls
```

On my machine (Docker engine 1.12.2-cs2), the last `docker network ls` shows a local overlay network.

One thing that's odd is that this only occurs if you use the network ID when running `docker network connect`; everything works if you connect with the network name.

**Comment by mavenugo** [comment] 2016-11-03 16:24
Thanks @wsong It seems https://github.com/docker/docker/issues/1724 addresses the above issue as well. But, it doesn't answer why a container removal doesn't result in task attachment object to be destroyed.

@mrjana I tried the above reproduction (https://github.com/docker/docker/issues/27639#issuecomment-257967036) with the patch for https://github.com/docker/docker/issues/1724 and it fails the `network rm` with `network is in use` error whereas the network should be free by now from the task attachment.

**Comment by mavenugo** [comment] 2016-11-03 22:41
@wsong The issue that you reproduced (https://github.com/docker/docker/issues/27639#issuecomment-257967036) is different from this issue. Can you pls open a new one ?

**Comment by wsong** [comment] 2016-11-03 22:45
Opened https://github.com/docker/docker/issues/28051.

**Comment by trapier** [comment] 2017-09-29 04:08
@vikstrous: not possible to delete an attachable network these days if it still has endpoints attached.  ok to close?

**Comment by thaJeztah** [comment] 2017-11-01 22:23
Looks like this is resolved indeed;

```bash
$ docker network create -d overlay --attachable testnet
6i8q65imwyfy3bb27y91gm2hn

$ docker run -it -d --net testnet --name testcontainer alpine sh
ba88e47afca1ccc2cb75779cac04592bb0cebfda1e43d89e7c0bd7a4e4e185d5

$ docker network rm testnet
Error response from daemon: rpc error: code = FailedPrecondition desc = network 6i8q65imwyfy3bb27y91gm2hn is in use by task aoiojr3uruehaw79k6edys06s
```


I'll go ahead and close, but ping me if it's still an issue

**Closed by thaJeztah** 2017-11-01 22:23 UTC
Labels: area/networking, kind/bug, version/master
