### ISSUE TITLE
Splitting Docker windows base images

### ISSUE THREAD

**Issue by AJreddy89** [moby/moby#36844] opened 2018-04-12 17:08 UTC
The docker image sizes on windows are pretty large and I would like to split the base images.

For example, the docker image size for SQL on windows is 9.45 GB, which is huge as it is built on top of windowsservercore operating system. Is there a best practice to separate the windowsservercore layers from docker sql image, so that I can optimize the image size?

**Comment by thaJeztah** [comment] 2018-04-14 02:12
Images that are based on the same base-image will share the layers, so if you already have the windowsservercore image on your machine, pulling the SQL image will only pull the layers that are added in that image.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-04-14 02:12 UTC
Labels: area/images, kind/question, platform/windows
