### ISSUE TITLE
error during connect on windows host

### ISSUE THREAD

**Issue by laurencefass** [moby/moby#32886] opened 2017-04-27 08:46 UTC
**Description**

**Steps to reproduce the issue:**
1.  run command line as admin.
2. docker ps
3.

**Describe the results you received:**

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\laurence\Desktop\My Downloads\ConsoleZ>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.29/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

C:\Users\laurence\Desktop\My Downloads\ConsoleZ>docker --version
Docker version 17.05.0-ce-rc1, build 2878a85

C:\Users\laurence\Desktop\My Downloads\ConsoleZ>

**Describe the results you expected:**

docker ps to return correct info

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker --version
Docker version 17.05.0-ce-rc1, build 2878a85
```

**Output of `docker info`:**

```
C:\Users\laurence\Desktop\My Downloads\ConsoleZ>docker info
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.29/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VB 5.18
windows 10 VB host

**Comment by friism** [comment] 2017-04-27 14:35
Is Windows 10 running inside Virtualbox? Docker won't work that way, since Hyper-V is required to run Docker Windows containers on Windows 10 (but not on Windows Server 2016) and VirtualBox doesn't supported nested virtualization.

**Comment by thaJeztah** [comment] 2017-04-29 02:23
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-04-29 02:23 UTC

**Comment by laurencefass** [comment] 2017-05-01 09:20
running windows 10 host running a docker toolbox. im seeing this message from the docker quickstart console on the w10 host. looks like a bug.

**Comment by thaJeztah** [comment] 2017-05-01 21:30
For docker toolbox specific options, the best location to report is https://github.com/docker/toolbox/issues, but check if there's an existing issue. In this case, if sounds like the environment variables are not setup properly; Docker Toolbox uses a tcp/ip connection to connect the client to the daemon running in the VM, if no environment variable is set (`DOCKER_HOST`), the client will try to connect using the default (socket) connection, which will fail
