### ISSUE TITLE
Cannot save/tar a container using docker-save

### ISSUE THREAD

**Issue by b3nis** [moby/moby#40503] opened 2020-02-11 20:32 UTC
**Description**

When trying to use command:
`docker save nextcloud:latest > nextcloud-app-20200211.tar`
I get the following error:
`Error response from daemon: file integrity checksum failed for "usr/local/etc/php/php.ini-development"`
When I tried command:
`docker save nextcloud:latest > /dev/null && echo 'OK' || echo 'Corrupted'`
I get the following:
```
Error response from daemon: file integrity checksum failed for "usr/local/etc/php/php.ini-development"
Corrupted
```
I have tried editing the file to rewrite it to disk without any success.
It's working for my other containers (4 in total).

**Steps to reproduce the issue:**
1. Run: `docker save nextcloud:latest > /dev/null && echo 'OK' || echo 'Corrupted'`

**Describe the results you received:**
See above.

**Describe the results you expected:**
A working tar file.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**
```

```
```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-29-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.686GiB
 Name: home
 ID: FMRU:55PL:5HUU:XJDW:55D6:MIKF:ZYI2:AZNW:IHYV:RDAY:CEN2:RWHF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

Big thanks in advance!

PS. I love Docker and what you are doing!

**Comment by thaJeztah** [comment] 2020-02-11 20:55
We you only encountering this issue with that particular image?

Also (so that we can try reproduce) is this the `nextcloud` image from docker hub (https://hub.docker.com/_/nextcloud)?

If so (given that `:latest` is a "rolling tag") could you post the "digest" of that image?

You can find the digest using `docker images --digests` which should show a column showing the digest

**Comment by b3nis** [comment] 2020-02-11 21:21
@thaJeztah 
All other containers works flawless when using docker-save. And you are totally correct on docker container (Nextcloud docker, the "original" and latest).

Digest:
```
REPOSITORY                               TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
nextcloud                                latest              sha256:c19beadca36fb6d059c35a58cfddbd7de41f7bc5e508693958578f65c553ed81   b81821f761f0        9 days ago          724MB
mariadb                                  latest              sha256:6f80d059050b80fd8bd951323f6e4a7dde36d62e355cf01b92d26c34d3f702f6   1f9cfa8dc305        13 days ago         356MB
jrcs/letsencrypt-nginx-proxy-companion   latest              sha256:a8d369d84079a923fdec8ce2f85827917a15022b0dae9be73e6a0db03be95b5a   d4955d798195        2 months ago        94.2MB
jwilder/nginx-proxy                      alpine              sha256:283063685150bfe60c47c892f14aa982daac1043a09dffcad1ac3035beb1bf5a   1aa571816748        3 months ago        54.5MB
```

**Comment by thaJeztah** [comment] 2020-02-11 21:59
The problem doesn't reproduce on my system;

```
docker pull nextcloud@sha256:c19beadca36fb6d059c35a58cfddbd7de41f7bc5e508693958578f65c553ed81

docker save nextcloud@sha256:c19beadca36fb6d059c35a58cfddbd7de41f7bc5e508693958578f65c553ed81 > nextcloud-app-20200211.tar
```

Given, I'm on 19.03.5, not 19.03.3 (but I don't see a change in between that could explain issues there; https://github.com/moby/moby/compare/v19.03.3...v19.03.5), and not on kernel 5.3

My primary suspect would be either something wrong with that image (corruption happening somehow to the actual file; have you had a situation where you ran out of disk space?). Do you happen to have anti-virus/malware software running on that machine? (we've also had cases where realtime protection blocked access to files, causing weird issues).

**Comment by b3nis** [comment] 2020-02-11 22:16
Thanks @thaJeztah,

- Same digest I can see - always something!
- No, haven't used more than 10% av my 250GB SSD
- No anti-virus
- Same error no matter if the container is running or not
- Tried docker system prune -a (same issue)
- I have also tried rebooting (same issue)

Something else I can try? Also, when rebuilding an image - what will happen to my settings/customizations? Gone?

**Comment by thaJeztah** [comment] 2020-02-12 11:15
> Also, when rebuilding an image - what will happen to my settings/customizations? Gone?

`docker save` will save an _image_, so either that image has been pulled from docker hub, built using `docker build`, or committed from a container (`docker run .....`, then `docker commit` the container).

Images created using `docker build` or `docker commit` will only be present in your local image cache, unless you have pushed them to a registry (which is recommended to anything that needs to be preserved; the local image cache should generally be considered just that: a "cache", and ephemeral).

As to changes you made to containers; those are also only available locally. Overall, the recommended approach is to consider containers ephemeral, and not making changes to containers, but instead using a Dockerfile to build an image with the changes needed to run a container. (filesystem) changes made to the container at runtime should either be "ephemeral" (e.g. temp files written by the container's process), or written to a "named volume" if they are meant to be preserved beyond the container's lifecycle (e.g. data storage of a database).

If your problem is caused by a corrupted image, you could try removing the image (`docker image rm nextcloud:latest`) and pulling it again. However, if there's existing containers using the image, it's possible that the image layers won't be actually removed from the filesystem when your `docker image rm` the image (and in that case those layers won't be pulled again).

**Comment by b3nis** [comment] 2020-02-12 15:58
![Error](https://user-images.githubusercontent.com/54119148/74351982-2519f200-4db8-11ea-8d4b-26046bff76aa.png)
Thanks a lot @thaJeztah ! 
I still don't really get how all the Docker things connect. In the attached printscreen:

1. I run the check and it complains about a file.
2. I located the file - but it can be find in many locations (ignore the /4BACKUP/ since that is my backup). I guess it's used by many containers? But the folder names don't align with the ID of the container.

This is surely because of me lacking knowledge how everything is connected. Also, shouldn't I just be able to recreate the file - or what is the integrity check actually do?

Again, big thanks!

**Comment by thaJeztah** [comment] 2020-02-12 16:28
The error is produced when constructing the tar, which performs an integrity check of the file; https://github.com/moby/moby/blob/58c2615208962a458ed94f4b6262eb27e5e021cd/vendor/github.com/vbatts/tar-split/tar/asm/assemble.go#L84-L90

> I guess it's used by many containers? 

OverlayFS uses multiple directories, which are then "stacked" (overlayed) to form the final version. At least a "lowerdir" (read-only mount for the version of the files in the image), and an "upperdir" (writable layer that holds changes that are made in the container at runtime); if the image has multiple layers (each could have a variant of the file), then a directory exists for each layer, all of which are mounted as "lowerdirs"

> But the folder names don't align with the ID of the container.

That's correct, I don't think there's a relation between those and the container, but you can find the paths of the overlayfs directories in `docker inspect` (output formatted for readability);

```bash
docker inspect --format '{{ json .GraphDriver}}' mycontainer
```
```json
{
  "Data": {
    "LowerDir": "/var/lib/docker/overlay2/6c36dba21bf56ccbb92bccc8d44fcc09c1c69861329765fa1509bd0560250957-init/diff:/var/lib/docker/overlay2/6e525e478f120a0825480c185c2739ec3ae48f4773c251f48c35c52833ca8cdb/diff:/var/lib/docker/overlay2/ed04faa909fd25ca0009f8a0ccf0d7831a7bbb0285e91538922aeedc8817876e/diff",
    "MergedDir": "/var/lib/docker/overlay2/6c36dba21bf56ccbb92bccc8d44fcc09c1c69861329765fa1509bd0560250957/merged",
    "UpperDir": "/var/lib/docker/overlay2/6c36dba21bf56ccbb92bccc8d44fcc09c1c69861329765fa1509bd0560250957/diff",
    "WorkDir": "/var/lib/docker/overlay2/6c36dba21bf56ccbb92bccc8d44fcc09c1c69861329765fa1509bd0560250957/work"
  },
  "Name": "overlay2"
}
```

> Update: I just realized that the issue might have been that I have edit that file and now it's checking against something and since the file is changed - it throws that error message? In other words: I have changed a file that I shouldn't?

Files inside `/var/lib/docker` are designed to be exclusively used/accessed by the docker daemon, and should not be modified; editing the file could definitely cause issues as the modified file's content no longer matches the expected content

**Comment by b3nis** [comment] 2020-02-12 23:32
Thanks again @thaJeztah ! You really take the time to explain things - and I am grateful!

Alright, I guess the easiest thing to try will be to restore the file. So (hopefully) one last questions - do you have any pointers how to do that? I could create another docker container (on another computer with same of everything) and copy it over - or what is best practice?

**Comment by thaJeztah** [comment] 2020-02-12 23:38
Hm good one; safest way would be to delete the image and pull it again. I think metadata (created/modified date and such) may also be taken into account when verifying, so not sure if it's gonna be easy to restore it

**Comment by b3nis** [comment] 2020-02-15 14:33
Hi again @thaJeztah !

I did a exact same setup in a VM and tested the corruption test before and after editing the file that I shouldn't have touched. And yes, exact same result.

- Not editing the file = no problem med corruption
- Edited the file = docker-save complains about corruption on that file

So case closed and, again, thank you! It's because of people like you that we, less knowledgable, learn and develop our skills!

**Closed** 2020-02-15 14:33 UTC
Labels: area/distribution, area/images, status/more-info-needed, version/19.03
