### ISSUE TITLE
Updating dependency package repo

### ISSUE THREAD

**Issue by mrturkmen06** [moby/moby#39938] opened 2019-09-16 11:21 UTC
**Description**

When I have tried to integrate google modules into my project which uses this repo to manage docker containers, I have faced with following complain 

![Complain ! ](https://user-images.githubusercontent.com/13614433/64953875-4ff13000-d884-11e9-9b82-0754a11ff1f8.png)

So, I am proposing change in that particular file by creating pull request. 

**Steps to reproduce the issue:**
1. Use this repo as dependency in an go project 
2. Then, try to create `go.mod` file to control dependencies of your project  
3. At the end, there will be complain which will be similar to given SS. 

**Describe the results you received:**

**Describe the results you expected:**

There should not be complain about the imported packages when google modules integrated. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2019-09-16 11:27
Looks like a duplicate of https://github.com/moby/moby/issues/39056; let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2019-09-16 11:27 UTC
