### ISSUE TITLE
Deleting concurrently the same network twice lead to an inconsistent network state

### ISSUE THREAD

**Issue by normanv** [moby/moby#25148] opened 2016-07-27 21:25 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 30
 Running: 25
 Paused: 0
 Stopped: 5
Images: 238
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local btrfs
 Network: null host bridge
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32 GiB
Name: lxc1
ID: N4S2:OALX:7VFW:HIF4:YBOJ:U67H:LZTW:BHZE:C43C:XG7U:A2JC:7OBN
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker is running inside LXC version 2.0.3

**Steps to reproduce the issue:**
1. You might want to have few docker networks (about 30) to have a response time of few seconds when creating and deleting networks to reproduce this issue easily
2. Create a Docker network : `docker network create --subnet 192.168.1.0/24 net1`
3. Open 2 shells. Run `docker network rm net1` in the first shell and run `docker network rm net1` in the second shell before the first command returns.

**Describe the results you received:**
- The first command will return with no errors. The second command will take more time and return with : `Error response from daemon: error deleting network endpoint count from store: Key not found in store`.
- An entry to this network's gateway interface will remain in /var/lib/docker/network/files.local-kv.db :
  `{"AddressIPv4":"192.168.1.1/24","BridgeName":"br-362e892873c5","DefaultBindingIP":"\u003cnil\u003e","DefaultBridge":false,"DefaultGatewayIPv4":"\u003cnil\u003e","DefaultGatewayIPv6":"\u003cnil\u003e","EnableICC":true,"EnableIPMasquerade":true,"EnableIPv6":false,"ID":"362e892873c582c087dfbd5fada639bfa4e5632355449618753725ddd9cab4be","Mtu":0}`
- This will cause the creation of a network using the same subnet to fail :
  `docker network create --subnet 192.168.1.0/24 net2`
  `response from daemon: cannot create network br-a7ec776a014a (19fd4f79367b60973f574c3e871c746f6721f2d4f081297240ec1b8248c241bd): conflicts with network 362e892873c582c087dfbd5fada639bfa4e5632355449618753725ddd9cab4be (br-362e892873c5): networks have overlapping IPv4` 
- Running `docker network rm net1` will return `Error response from daemon: network net1 not found`

**Describe the results you expected:**
- The second `docker network rm` command should do nothing and return a warning telling the user that Docker is already deleting this network
- The local-kv.db should remain consistent with the actual Docker network state

**Additional information you deem important (e.g. issue happens only occasionally):**
It is unlikely that this issue will happen with a human interacting with Docker but quite likely when a piece of software talks with the Docker API and assume that each API call is atomic (that was our case) but may be this assumption is wrong ?

Thank you for your help =)

**Comment by thaJeztah** [comment] 2016-07-27 21:47
Are you still able to reproduce this on Docker 1.11.2 ?

**Comment by normanv** [comment] 2016-07-27 22:37
I can't reproduce it on 1.11.2 on a physical host (I got other trouble running 1.11 inside lxc that I haven't time to investigate now). 

Is this issue known and fixed in 1.11.2 ? I was not able to find anything about it in 1.11.2 release note. Is there any patch that I would be able to apply to 1.10.3 ?

**Comment by thaJeztah** [comment] 2016-07-27 22:59
no I don't know a particular patch; and it would most likely be a patch in libnetwork. Is there a reason for running docker inside LXC?

**Comment by akerouanton** [comment] 2023-08-16 09:44
I'm not able to reproduce this issue, so let me close it.

**Closed by akerouanton** 2023-08-16 09:44 UTC
Labels: kind/bug, area/networking, version/1.10
