### ISSUE TITLE
COPY instruction fails as build prefixes a 'docker/tmp/docker-builder507693913' to dir path

### ISSUE THREAD

**Issue by saifikhan** [moby/moby#34049] opened 2017-07-11 02:08 UTC
COPY instruction fails as build prefixes a 'docker/tmp/docker-builder507693913' to dir path

**Steps to reproduce the issue:**

Write a Dockerfile as shown below

```
FROM pritunl/archlinux:2017-07-01

LABEL "maintainer"="Rust Bangalore Community, rustox@googlegroups.com"

ARG P01=rustup-1.5.0-1-x86_64.pkg.tar.xz

ARG SDIR=/var/cache/pacman/pkg
ARG DDIR=/var/cache/pacman/pkg

COPY $SDIR/$P01  $DDIR/$P01

RUN /usr/bin/pacman --upgrade $P01

CMD ["/usr/bin/bash"]
```

**Describe the results you received:**

```
Sending build context to Docker daemon  159.2kB
Step 1/8 : FROM pritunl/archlinux:2017-07-01
 ---> b222423578c1
Step 2/8 : LABEL "maintainer" "Rust Bangalore Community, rustox@googlegroups.com"
 ---> Using cache
 ---> 4a30d6f800cd
Step 3/8 : ARG P01=rustup-1.5.0-1-x86_64.pkg.tar.xz
 ---> Running in b6c918601f06
 ---> 12ec19de9f76
Removing intermediate container b6c918601f06
Step 4/8 : ARG SDIR=/var/cache/pacman/pkg
 ---> Running in 26c83c812f30
 ---> 17a10567097a
Removing intermediate container 26c83c812f30
Step 5/8 : ARG DDIR=/var/cache/pacman/pkg
 ---> Running in 4414f5b7b52b
 ---> 227ef6f1bd13
Removing intermediate container 4414f5b7b52b
Step 6/8 : COPY $SDIR/$P01 $DDIR/$P01
COPY failed: stat /home/saifi/docker/tmp/docker-builder507693913/var/cache/pacman/pkg/rustup-1.5.0-1-x86_64.pkg.tar.x: no such file or directory
```

**Describe the results you expected:**

the package rustup-1.5.0-1-x86_64.pkg.tar.x should have been copied from $SDIR to $DDIR inside the image as part of the build process.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Sat Jul  8 20:56:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Sat Jul  8 22:56:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.9-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.847GiB
Name: strikr
ID: FMIR:W3ZI:X7AT:3BET:UUZ3:PVEU:HT3D:63WG:XU3E:QLIR:EVS6:7QGV
Docker Root Dir: /home/saifi/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 25
 System Time: 2017-07-11T07:40:34.683004483+05:30
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker on physical box.

```
$ cat  /etc/systemd/system/docker.service.d/override.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --debug --log-level debug --log-driver syslog --graph /home/saifi/docker -H tcp://0.0.0.0:2375 -H unix:///home/saifi/docker.sock 
```

**Comment by max8hine** [comment] 2017-07-11 05:09
+ 1

The same error occurs in the Node.js official image.

- Dockerfile:
```
FROM node:onbuild

WORKDIR /app
RUN ls -a

RUN npm install nodemon -g

COPY backend/package.json /app
RUN npm install
RUN apt-get update
RUN apt-get install -y vim

COPY backend /app
EXPOSE 8888

CMD ["npm", "start"]
```

**Comment by thaJeztah** [comment] 2017-07-11 05:11
I'm not able to reproduce;

```bash

$ mkdir repro-34049 && cd repro-34049
$ mkdir var/cache/pacman/pkg
$ touch var/cache/pacman/pkg/rustup-1.5.0-1-x86_64.pkg.tar.xz

$ cat > Dockerfile -<<"EOF"
FROM scratch
ARG P01=rustup-1.5.0-1-x86_64.pkg.tar.xz

ARG SDIR=/var/cache/pacman/pkg
ARG DDIR=/var/cache/pacman/pkg

COPY $SDIR/$P01  $DDIR/$P01
EOF


$ docker build -t repro-34049 .

Sending build context to Docker daemon  4.608kB
Step 1/5 : FROM scratch
 --->
Step 2/5 : ARG P01=rustup-1.5.0-1-x86_64.pkg.tar.xz
 ---> Running in 1d8847e8637f
 ---> 80fbdf378fb7
Removing intermediate container 1d8847e8637f
Step 3/5 : ARG SDIR=/var/cache/pacman/pkg
 ---> Running in 134a65dd308c
 ---> ae022e4cf25e
Removing intermediate container 134a65dd308c
Step 4/5 : ARG DDIR=/var/cache/pacman/pkg
 ---> Running in ee371bae8625
 ---> 1bbc679c5f66
Removing intermediate container ee371bae8625
Step 5/5 : COPY $SDIR/$P01 $DDIR/$P01
 ---> edc16f99869d
Removing intermediate container 4e881a093d55
Successfully built edc16f99869d
Successfully tagged repro-34049:latest
```

> COPY instruction fails as build prefixes a 'docker/tmp/docker-builder507693913' to dir path

The path you're seeing there is the temp directory that the _daemon_ uses for the build context it received. This is the `tmp` directory inside docker's data-directory, which defaults to `/var/lib/docker`, but in your configuration was changed to `/home/saifi/docker`.


Looking at your Dockerfile, I suspect this is the same situation as  https://github.com/moby/moby/issues/27134#issuecomment-314160579.

Source paths in `COPY` and `ADD` Dockerfile instructions are relative to the _build context_, not to your local filesystem. So the `COPY` instruction;

```dockerfile
COPY /var/cache/pacman/pkg/rustup-1.5.0-1-x86_64.pkg.tar.xz /var/cache/pacman/pkg/rustup-1.5.0-1-x86_64.pkg.tar.xz
```

Means;

copy the file `rustup-1.5.0-1-x86_64.pkg.tar.xz` from the `var/cache/pacman/pkg/` subdirectory in the build-context (`.` - the current directory).

Closing this because this is not a bug, but feel free to ask for more information

**Closed by thaJeztah** 2017-07-11 05:11 UTC
Labels: area/builder, version/17.06

**Comment by thaJeztah** [comment] 2017-07-11 05:15
@max8hine you are using the `:onbuild` version of the node image, so besides the instructions you put in your Dockerfile, the following steps are also executed:

https://github.com/nodejs/docker-node/blob/f131cc81c04968f1a60092c5efef54ea276d8b20/8.1/onbuild/Dockerfile#L8-L10

```dockerfile
ONBUILD ARG NODE_ENV
ONBUILD ENV NODE_ENV $NODE_ENV
ONBUILD COPY package.json /usr/src/app/
ONBUILD RUN npm install && npm cache clean --force
ONBUILD COPY . /usr/src/app
```

So if you only have your `package.json` in the `backend/` subdirectory and not in the current directory (`.`), it will fail. If looks like you are looking for the `node` image, not the `:onbuild` variant

**Comment by max8hine** [comment] 2017-07-11 05:34
Thank you @thaJeztah, it is solved my problem.
I should dig deeper and it was a silly question.

**Comment by thaJeztah** [comment] 2017-07-11 06:10
You're welcome!

**Comment by Elufimov** [comment] 2017-07-13 13:43
Hi @thaJeztah ! I have the same problem but I am sure that my src path is correct.
```
FROM microsoft/dotnet:1.1-runtime
ADD bin /app
WORKDIR /app
```

```
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM microsoft/dotnet:1.1-runtime
 ---> 011ee6ef24a2
Step 2/3 : ADD bin /app
ADD failed: stat /var/lib/docker/tmp/docker-builder299770601/bin: no such file or directory
```

```
ls -l
total 11
...
-rw-r--r--  1 elufimov  staff    175 Jul 13 17:37 Dockerfile
-rw-r--r--  1 elufimov  staff   4759 Jul 13 11:07 Program.cs
-rw-r--r--  1 elufimov  staff  11525 Jul 13 11:07 README.MD
drwxr-xr-x  4 elufimov  staff    136 Jul 13 16:57 bin
drwxr-xr-x  6 elufimov  staff    204 Jul 13 16:45 obj
```
```
docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 11
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: WZHJ:FTYC:LEE2:7BPZ:YEIM:2KZ6:AHDW:Y6F3:ARPX:QOAJ:A2MI:Y3ZQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2017-07-13T13:41:26.65229263Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-07-13 16:36
@Elufimov be sure to check if the path you're building from is shared with the VM that the daemon is running in; https://docs.docker.com/docker-for-mac/#file-sharing (or if you're on Windows; https://docs.docker.com/docker-for-windows/#shared-drives)

**Comment by Elufimov** [comment] 2017-07-13 18:55
@thaJeztah Yes, I use /Users sub directory as always. And I did not have this problem before.

**Comment by Elufimov** [comment] 2017-07-13 19:03
Is there anything I can do for tracing this problem?

**Comment by Elufimov** [comment] 2017-07-14 06:27
1) I switched to stable docker for mac, but it did not work
2) I coped files to other directory and it works!
```
 ⚙  elufimov@Michael  ~/Documents/Projects/Temp/test  docker build .
Sending build context to Docker daemon  17.04MB
Step 1/3 : FROM microsoft/dotnet:1.1-runtime
 ---> 97264b828741
Step 2/3 : COPY bin/Debug/netcoreapp1.1/publish /app
 ---> Using cache
 ---> 2c41477fa536
Step 3/3 : WORKDIR /app
 ---> Using cache
 ---> 2d62e7f1566e
Successfully built 2d62e7f1566e
```
```
 ⚙  elufimov@Michael  ~/Documents/Projects/Temp/test  ls -l
total 24
-rw-r--r--  1 elufimov  staff   162 Jul 14 10:26 Dockerfile
-rw-r--r--  1 elufimov  staff  4759 Jul 13 11:07 Program.cs
drwxr-xr-x  4 elufimov  staff   136 Jul 13 16:57 bin
```

**Comment by Elufimov** [comment] 2017-07-14 07:56
I am so sorry. There is only one problem and it is my inattention. I have `.dockerignore` who ignore everything.

**Comment by rajiv180984** [comment] 2017-12-07 12:56
I faced this issue, I was not able to copy zeppelin [1GB] directory into docker conatiner. and getting issue "COPY failed: stat /var/lib/docker/tmp/docker-builder977188321/zeppelin-0.7.2-bin-all: no such file or directory"
    
    I am using docker Version: 17.09.0-ce and resolved issue by following steps.
    Step 1: copy zeppelin directory [which i want to copy into docker package]into directory contain "Dockfile" 
    Step 2: edit Dockfile and add command [location where we want to copy]
    ADD ./zeppelin-0.7.2-bin-all /usr/local/  
    Step 3: go to directory which contain DockFile and run command [alternatives also available]
    docker build .
    
    Step 4:  docker image created Successfully with logs
    Step 5/9 : ADD ./zeppelin-0.7.2-bin-all /usr/local/
     ---> 3691c902d9fe
    Step 6/9 : WORKDIR $ZEPPELIN_HOME
     ---> 3adacfb024d8 ....
    Successfully built b67b9ea09f02
