### ISSUE TITLE
Docker buildkit incorrectly parallelized ONBUILD COPY instructions

### ISSUE THREAD

**Issue by vdboor** [moby/moby#42845] opened 2021-09-13 09:04 UTC
**Description**

The `ONBUILD COPY --from=build-image` doesn't wait until the build image is successfully build.
Hence the copy command fails because the expected files aren't present yet.

To reproduce:

`base/Dockerfile`:

```
FROM alpine
ONBUILD RUN echo 1111 > /hello
```

`runtime/Dockerfile`:

```
FROM alpine
ONBUILD COPY --from=base-image /hello /
ONBUILD RUN cat /hello && echo runtime
```

`Dockerfile`:

```
FROM test/base as base-image

RUN sleep 1
RUN echo 2222 >> /hello

FROM test/runtime
RUN cat /hello && echo "final"
```

Build the base images:

```
docker build -t test/base base/
docker build -t test/runtime runtime/
```

Build the project image: `docker build .`

```
docker build --progress=plain .
#1 [internal] load build definition from Dockerfile
#1 sha256:f28b4f90c21e4d2ea0a23ca82e502e14ddf0c6629b9494c18381a708f34db9d6
#1 transferring dockerfile: 156B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:f3609c129a44f62b35a562c78225ac7e0c947303423bfde34d6bf62020919e5f
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/test/runtime:latest
#3 sha256:094226d35ecfc11729c8b7495cf33590f3e9085575c954b4a80f118518805d8b
#3 DONE 0.0s

#4 [stage-1 1/2] FROM docker.io/test/runtime
#4 sha256:555c4dd9ba60441b8552ee9eb7b7487b86c7f62da21dffdea83a937ba6db1dee
#4 DONE 0.0s

#5 [base-image 1/3] FROM docker.io/test/base:latest
#5 sha256:8ee1f2f1b143f7eaf590ccecc7b2df5dd1a60852a61f727d4af433f999f9a800
#5 CACHED

#6 [stage-1 2/2] COPY --from=base-image /hello /
#6 sha256:9ebdd73131b7ba8e040531c39c61f62d2228acc043da6f7f2b9ef245a3fa8c76
#6 ERROR: "/hello" not found: not found
------
 > [stage-1 2/2] COPY --from=base-image /hello /:
------
failed to compute cache key: "/hello" not found: not found
```

Workaround is using the old build engine:

```
DOCKER_BUILDKIT=0 docker build .
Sending build context to Docker daemon  5.632kB
Step 1/5 : FROM test/base as base-image
# Executing 1 build trigger
 ---> Running in 4042c8546360
Removing intermediate container 4042c8546360
 ---> 92c502b467a6
Step 2/5 : RUN sleep 1
 ---> Running in b8adeb8f1cd5
Removing intermediate container b8adeb8f1cd5
 ---> 8dedcd27d098
Step 3/5 : RUN echo 2222 >> /hello
 ---> Running in c132e8d0d7b8
Removing intermediate container c132e8d0d7b8
 ---> f6f08429f153
Step 4/5 : FROM test/runtime
# Executing 2 build triggers
 ---> Running in d40c1588178b
11111
2222
runtime
Removing intermediate container d40c1588178b
 ---> dd6ba63de21c
Step 5/5 : RUN cat /hello && echo "final"
 ---> Running in 95e18fb8c009
11111
2222
final
Removing intermediate container 95e18fb8c009
 ---> 55b4dc836867
Successfully built 55b4dc836867
```

**Output of `docker version`:**

Docker desktop 20.10.8 on macOS 11.5.2

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment] 2021-09-14 12:56
Thanks for reporting (and the clear reproduction steps); This looks like a duplicate of https://github.com/moby/buildkit/issues/816 in the BuildKit repository; I'll close this ticket in favor of that one, to prevent the conversation from diverging, but feel free to participate on that ticket 👍

**Closed by thaJeztah** 2021-09-14 12:56 UTC
