### ISSUE TITLE
Windows Containers memory leak 

### ISSUE THREAD

**Issue by alex-codefresh** [moby/moby#39476] opened 2019-07-09 08:33 UTC
**Description**

We use Windows Containers for our CI and we have builds running quite frequently one after another.

With every such run, Paged Pool grows infinitely until it exceeds all the available virtual memory of the system. Even if the builds are not running and the docker engine is stopped, the Paged Pool memory won't go down in time.

[Poolmon](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/poolmon) utility in combination with [strings.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/strings)  show the following drivers allocating the most of the Paged Pool memory:  _ntfs.sys, bindflt.sys, fltMgr.sys_

**Steps to reproduce the issue:**
1. Create a Windows 1809 machine with docker 18.09.2 installed
2. Run the following Powershell commands:

```
git clone https://github.com/angular/angular.git
cd .\angular\
git checkout 50c4ec66871aa7aa24d92f5
docker build -f .\.codefresh\Dockerfile.win-1809 --build-arg node_version=10.13.0 --build-arg yarn_version=1.13.0 -t node-bazel-windows .\.codefresh\
while ($true) { docker run --rm -u ContainerAdministrator -v ${pwd}:C:/test -w C:/test --entrypoint cmd node-bazel-windows /s /c 'yarn install --frozen-lockfile --non-interactive --network-timeout 100000 --no-progress & copy .codefresh\bazel.rc %ProgramData%\bazel.bazelrc & yarn bazel test --build_tag_filters=-ivy-only --test_tag_filters=-ivy-only,-browser:chromium-local //... & yarn bazel test --define=compile=aot --build_tag_filters=-no-ivy-aot,-fixme-ivy-aot --test_tag_filters=-no-ivy-aot,-fixme-ivy-aot,-browser:chromium-local //...' }
```
3. Observe the tests running in the loop and see the Paged Pool memory growing.

**Describe the results you received:**

Paged Pool grows infinitely until it exceeds all the available virtual memory of the system

**Describe the results you expected:**

Paged Pool doesn't grow infinitely

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is reproducible with 1903 and docker 18.09.6 as well and not only with this project code. We tried this with a few Node.js projects using yarn and got the same result.

**Output of `docker version`:**

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        1ac774dfdd
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       1ac774dfdd
  Built:            02/10/2019 04:13:25
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 332
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.316)
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 62.54GiB
Name: EC2AMAZ-JGQFRJ4
ID: 2WJ3:3ZQC:Y53M:YH2T:6S3G:XS5B:K6DQ:JRGL:YXIK:7LOA:U4W5:BTRK
Docker Root Dir: D:\
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**

The issue has been reproduced on AWS instances and on Azure VMs

**Comment by thaJeztah** [comment] 2019-07-14 10:32
ping @jterry75 @jhowardmsft ptal

/cc @ddebroy

**Comment by sunnyshines2008** [comment] 2019-07-26 01:10
We are also seeing similar issue where docker on windows has memory leakage and it seems that docker reserves some memory and when container is restarted it reserve additional memory but never returns it completely.

Please tell us if we should open a separate bug for our usecase. More details below:

**Steps to reproduce the issue:**
1.Restart docker containers and let them come up properly and wait for system memory to usage to become constant.
3. Keep doing step 1 again and again and you will see that slowly system memory usage will keep going up til 90%.

**Describe the results you expected:**
Reserved memory should be returned/reused when container is restarted

**Mitigation:**
Use below command to release the reserved memory by docker.
Restart-Service docker

**Output of `docker version`:** We have seen the issue with 18.09.3 as well as with 18.09.6
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       142dfcedca
  Built:            02/28/2019 06:31:15
  OS/Arch:          windows/amd64
  Experimental:     false

**Output of docker info:**

Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 18.09.3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.503)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15GiB
Name: dc62ae6d440eca8
ID: KS33:34VM:ORJM:5TW7:M4ZA:BDOG:G3C2:F7U6:ICW5:NUKE:EURX:BJSW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):
GCP windows VM

**Comment by carpenterjc** [comment] 2019-10-10 14:15
I am also observing this issue. One common factor I can see between our environment and the two highlighted here is using kernel version 17763. 
I also found a reference to memory leaks and storage drivers in this version of windows.

https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/Server-2019-Windows-1809-spaceport-sys-non-paged-pool-memoryleak/m-p/531312

We are currently upgrading our infrastructure, but has anyone noticed this issue on latter versions of the kernel?

We have a forced a kernel dump and have identified the leak comes from "Io Symbolic Links , Binary: nt!io" essentially allocated by the kernel.

**Comment by mkoziel2000** [comment] 2020-04-30 21:16
We are seeing the same thing with bindflt.sys eating away at our memory until the machine stops responding.  Creating a performance file using xperf and loading it into Windows Performance Analyzer doesn't reveal much as to which process is causing the driver to not give up memory.  Various processes like git.exe, msbuild.exe, nunit-console.exe show up as processes that run against the driver (our Windows containers experiencing this issue are running build processes internally).  Most of the allocation being held seems to be registered at block 0x00, which I can only assume is originating within the driver itself.  The Pool tags we see as being most problematic are "BFsh", "FMsl", "BFsc", "BFnc".

**Comment by Drewster727** [comment] 2020-09-22 18:52
I am seeing this issue as well, and have no way of resolving it. I'm currently rebooting my swarm windows nodes nightly as a workaround.

Memory usage increase (0-1 percent scale):
![image](https://user-images.githubusercontent.com/4528753/93924174-ff53b480-fcd9-11ea-9f76-f06393ab715f.png)

dockerd process page file byte increase:
![image](https://user-images.githubusercontent.com/4528753/93924114-ec40e480-fcd9-11ea-9b51-46c29e72a2cf.png)

I think the two are related... eventually the node just goes offline and I have to hard reboot it at the VMware level.

**Docker info:**
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.12
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: a05kae3zox90n2vzduxz8bg7v
  Is Manager: false
  Node Address: <redacted>
  Manager Addresses:
   <redacted>
 Default Isolation: process
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows Server Datacenter Version 1909 (OS Build 18363.836)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.999GiB
 Name: <redacted>
 ID: MDUM:SZHB:6R7W:SMHB:ZCON:AMNH:7G4J:HKCW:WVJ5:ZARC:X64H:5SZ3
 Docker Root Dir: E:\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

@thaJeztah is there anything we can do to prevent this?

**Comment by lowenna** [comment] 2020-09-22 19:16
@Drewster727 Although I no longer work at Microsoft, and am therefore no longer authoritative having been retired almost a year now, I can reasonably safely state that I would highly recommend you moved to an even newer OS if possible. There are many, many, many fixes which resolved a lot of memory-leak issues which have not/will not be back-ported via Windows update. Only in the next OS release. I do however feel your pain, trust me on that!

**Comment by Drewster727** [comment] 2020-09-22 19:55
@lowenna thanks for the response! We're using Windows Server Datacenter Version 1909 (OS Build 18363.836)
1909 is pretty recent, is it not? What version should we target for windows server core?
Thanks!

**Comment by batiati** [comment] 2021-04-07 22:38
> We're using Windows Server Datacenter Version 1909 (OS Build 18363.836)
> 1909 is pretty recent, is it not? What version should we target for windows server core?

[KB5000808](https://support.microsoft.com/en-us/topic/march-9-2021-kb5000808-os-build-18363-1440-6989940a-252d-48f3-a2a7-a42bf19fa2c8) seems to have solved this issue; I was running into the same problem with docker + k8s on Windows Server 1909.
The Paged and Nonpaged Pool memory looks fair normal now after this update.

**Comment by thaJeztah** [comment] 2021-04-08 11:26
Thanks for the update @batiati. Let me go ahead and close this issue as "resolved". If people on this thread are unable to upgrade to a newer version of windows with the fix, I'd recommend opening a support ticket with Microsoft to request backporting the fix (if possible 😅).

**Closed by thaJeztah** 2021-04-08 11:26 UTC
Labels: area/kernel, platform/windows

**Comment by richardgavel** [comment] 2021-04-19 15:05
@thaJeztah I am still having trouble with memory leaks in a similar scenario (CI/CD). I am using version 19041 run short-lived containers (process isolation) and seeing a gradual increase in the Memory Pool Nonpages Bytes. In about 3 days, it's jumped 7.5 GB. I am also using the latest Docker engine (Install-Package Docker -ProviderName DockerMsftProvider -RequiredVersion 20.10.4 -Force)

**Comment by batiati** [comment] 2021-09-25 10:32
> [KB5000808](https://support.microsoft.com/en-us/topic/march-9-2021-kb5000808-os-build-18363-1440-6989940a-252d-48f3-a2a7-a42bf19fa2c8) seems to have solved this issue; I was running into the same problem with docker + k8s on Windows Server 1909.
> The Paged and Nonpaged Pool memory looks fair normal now after this update.

I'm sorry for reporting this as solved, but it's not.
Please refer to #42487

**Comment by andyfisher100** [comment] 2023-04-18 10:24
> @thaJeztah I am still having trouble with memory leaks in a similar scenario (CI/CD). I am using version 19041 run short-lived containers (process isolation) and seeing a gradual increase in the Memory Pool Nonpages Bytes. In about 3 days, it's jumped 7.5 GB. I am also using the latest Docker engine (Install-Package Docker -ProviderName DockerMsftProvider -RequiredVersion 20.10.4 -Force)

I believe this is the same issue im having too

**Comment by ilyasahmedglb** [comment] 2023-08-27 14:21
I believe this is the same issue im having too. memory increase gradually. i m using windows 2022 server standard.
running docker 20.0 ver. container memory getting increase gradually.

**Comment by Mlekow** [comment] 2024-01-31 09:13
Same issue too using Server 2022 (20348.1850) with docker 20.10.6

**Comment by andyfisher100** [comment] 2024-01-31 09:59
For what it's worth, I had a support ticket open with Microsoft for a while but eventually the issue was solved. Some things for people to try

Make sure you use the latest version of docker (24.0.x). instructions can be found here https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1
Note: Docker enterprise (EE) now requires a license from miranrtis. If you don't have a license you should installed CE/Moby

Obviously make sure you OS is patched with the latest windows updates

One thing I did notice before installing the windows update that fixed my issue was we had 2 machines that did not have a memory leak. I recently realised that these 2 machines had a page file configured on the drive where we ran docker from (using D: drive whilst OS is on C:). All of the other machines that shown the memory leak, at the time, did not have a page file configured on the docker drive

**Comment by thaJeztah** [comment] 2024-01-31 10:45
@andyfisher100 could you post your comment in https://github.com/moby/moby/issues/42487 as well (if that's indeed the same issue)?
