### ISSUE TITLE
About Privileged and CAP control

### ISSUE THREAD

**Issue by theidforgithub** [moby/moby#42644] opened 2021-07-16 05:58 UTC
Hi, 

My project uses docker to setup the environment.

The project need some privilege to get and set something.

It used to add the '--privileged' flag to accomplish it.

I want to make the container safer by remove '--privileged' and add
'--cap-add' flags.

Before I search which CAPS I need to set, I added '--cap-add all' to test
if something went wrong.

And I got this, "*buffer: vlib_physmem_shared_map_create:
pmalloc_map_pages: page allocated on wrong node, numa node 1 status 0:
Operation not permitted*".

I checked the code on the github, and noticed that "--add-cap=all" and
"--privileged" are different things.

After check deeply, I found that they both use "GetAllCapabilities"
which will give them full capability list.

Is it a bug or anything I missed ? Look forward to hearing from you.

Thank you for your reading.

**Comment by thaJeztah** [comment] 2021-07-19 08:18
`--privileged` does various things (besides granting `--cap-add=ALL`. When running with `--privileged`;

- seccomp is disabled (`--security-opt seccomp=unconfined`)
- AppArmor is disabled (`--security-opt apparmor=disabled`)
- SELinux is disabled (`--security-opt label=disabled`)
- [MaskedPaths](https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/oci/defaults.go#L98-L109) are disabled, allowing the container direct access to those paths on the host (see [daemon/oci_linux.go#L681-L690](https://github.com/moby/moby/blob/bf11970fd50d0c2ffcc1ed323fd255ef009af745/daemon/oci_linux.go#L681-L690))
- [ReadOnlyPaths](https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/oci/defaults.go#L110-L116) are disabled, giving the container write access to those paths on the host (see [daemon/oci_linux.go#L681-L690](https://github.com/moby/moby/blob/bf11970fd50d0c2ffcc1ed323fd255ef009af745/daemon/oci_linux.go#L681-L690))
- Possibly other things I did not think of

To see what's still blocking your container, it may help to start with (in turn) disabling seccomp, apparmor, and selinux. If it's seccomp, you may be able to create a custom profile that allows specific syscalls that are blocked by default.

**Comment by thaJeztah** [comment] 2021-07-19 08:19
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2021-07-19 08:19 UTC
Labels: kind/question

**Comment by theidforgithub** [comment] 2021-07-19 08:22
Thank for your quickly reply.

Now, I know which direction I could follow to make my container work.

I sent the email to docker.com before, now I know the right way to get support, thank you again !!
