### ISSUE TITLE
Allow "registry-mirrors" of gcr.io and other popular registries

### ISSUE THREAD

**Issue by myeyre** [moby/moby#41456] opened 2020-09-16 08:11 UTC
Our servers inside corporate network can not connect to internet directly, and https proxy is not an option, so we use nexus to make registry proxies of popular registries like Docker Hub, gcr.io and etc.  

Currently we can set "registry-mirrors" of Docker Hub through daemon.json, then we can pull images from proxy directly using same image name:

`docker pull mysql:8`

But for registries like gcr, we must address proxy url in pull command:

`docker pull nexus_ip:registry_port/google_containers/pause:3.2`

while pulling same image on internet:

`docker pull k8s.gcr.io/google_containers/pause:3.2`

It's a bit of inconvenience, cause some scripts or config files should be rewrite for intranet environment, while they where written on internet env.

How about allowing "registry-mirrors" of gcr.io and other popular registries?

Currently "registry-mirrors" setting:

`{
  "registry-mirrors": ["https://mirror.of.dockerhub"]
}`

We could change it to:

`{
  "registry-mirrors": {
  "https://hub.docker.com/": "https://mirror.of.dockerhub",
  "k8s.gcr.io": "mirror.of.gcr"
  }
}`

Is this possible? Could this be done?

**Comment by tao12345666333** [comment] 2020-09-17 00:38
please see SUSE's patch https://github.com/SUSE/docker/commit/8175dcf169ffebf84f85a2c17d4f7152aaf78100

**Comment by thaJeztah** [comment] 2020-09-17 15:06
Looks like a duplicate of https://github.com/moby/moby/issues/18818

(also see https://github.com/moby/moby/pull/34319)

let me close this one in favour of https://github.com/moby/moby/issues/18818 to not have the conversation diverge more 👍

**Closed by thaJeztah** 2020-09-17 15:06 UTC
Labels: area/distribution, kind/enhancement
