### ISSUE TITLE
SIGWINCH let httpd quits unexpectly.

### ISSUE THREAD

**Issue by chenliu1993** [moby/moby#40871] opened 2020-04-29 07:54 UTC
**Description**

Hi experts,
    I am using docker for Linux to start a httpd container. After httpd is started, then I adjust the windows size of my terminal. Once I change the size, httpd quits with the log
```
[Wed Apr 29 07:43:17.442814 2020] [mpm_event:notice] [pid 1:tid 140100469269632] AH00492: caught SIGWINCH, shutting down gracefully
```
**Steps to reproduce the issue:**
1. docker run -it --name httpd httpd
2. modify the size of your terminal. just shrink it would take effect.

**Describe the results you received:**
httpd quits

**Describe the results you expected:**
httpd shouldn't quit

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-109.gitcccb291.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      cccb291/1.13.1
 Built:           Tue Mar  3 17:21:24 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-109.gitcccb291.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      cccb291/1.13.1
 Built:           Tue Mar  3 17:21:24 2020
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1062.18.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 1.777 GiB
Name: master
ID: FENS:6ORS:M6MO:LNDL:Y2YU:VSMU:HWBX:IBRS:ILB2:XAHP:2DTN:BTX5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am running docker in a centos minimal install vm, and ssh through mac's temrinal.

**Comment by thaJeztah** [comment] 2020-04-29 08:07
This is because apache abuses `SIGWINCH` as a signal to gracefully shutdown; see [What is in Apache 2 a “caught SIGWINCH” error?](https://stackoverflow.com/questions/780853/what-is-in-apache-2-a-caught-sigwinch-error), and this issue; https://github.com/docker-library/httpd/issues/9

Apache doesn't expect to be running interactively, and when you resize the window, Apache handles that signal to do a "graceful" shutdown.

You can run the container detached (`-d`), and either run `docker logs <your container>` to view the apache logs, or `docker exec -it <your container>` to open a shell in the container that's running in the background.

This is not a bug in docker, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2020-04-29 08:07 UTC
Labels: kind/question
