### ISSUE TITLE
Ports are not working in combination with add-host / extraHosts

### ISSUE THREAD

**Issue by chrismay2** [moby/moby#38085] opened 2018-10-26 07:00 UTC
**Description**
When I expose a port and at the same time add an extra host the port is not available. This is reproducible when using command line as well as the docker API. I stumpled one the issue when trying to debug a Java application.
 
**Steps to reproduce the issue:**
1. docker run -it --rm -p 8000:8000 my_java_app:latest
--> port 8000 is available
2. docker run -it --rm -p 8000:8000 --add-host=mysql-host:172.17.0.1 my_java_app:latest
--> port 8000 is NOT available

**With Docker API:**
```
var body = {
    Image: "my-java-app:latest",
    ExposedPorts: { "8000/tcp": {} },
    HostConfig: {
        PortBindings: {	"8000/tcp": [{ "HostPort": "8000" }]}
    }
}
```
--> port 8000 is available

```
var body = {
    Image: "my-java-app:latest",
    ExposedPorts: { "8000/tcp": {} },
    HostConfig: {
        PortBindings: {	"8000/tcp": [{ "HostPort": "8000" }]},
	ExtraHosts: [ "mysql-host:" + hostIp ],
    }
}
```
--> port 8000 is NOT available

**Describe the results you received:**
see above

**Describe the results you expected:**
I expect the port to be open, independently if I use extra hosts or not

**Additional information you deem important (e.g. issue happens only occasionally):**
I verified this behaviour when debugging remotely from another machine. I can't assure that the same holds true when trying to access the port from within the host.

**Output of `docker version`:**
Client:
 Version:           0.0.0-20181025010344-36e4073
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        36e4073
 Built:             Thu Oct 25 07:28:59 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          0.0.0-20181025010344-36e4073
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       36e4073
  Built:            Thu Oct 25 07:00:35 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Output of `docker info`:**
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 0.0.0-20181025010344-36e4073
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d6de12e2f362cb9dc49ad957911996d3de59b338
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.762GiB
Name: localhost.dmpos
ID: BMCY:RUUR:NBYR:4TZQ:6PVI:UHA4:LS5U:TLBZ:GBNA:XMFP:PLKV:B2RX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by thaJeztah** [comment] 2018-10-30 13:33
I'm not able to reproduce this issue; could this be something with the application you're running in the container using `mysql-host` to configure something?


```bash
docker run -d --rm -p 8000:80 --name foobar nginx:alpine

curl localhost:8000
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...

docker kill foobar 
```

```bash
docker run -d --rm -p 8000:80 --add-host=mysql-host:172.17.0.1 --name foobar nginx:alpine

curl localhost:8000
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```

**Comment by chrismay2** [comment] 2018-10-31 08:02
Hmm, when I use your commands, it works for me as well. 
There must be some additional side condition, but I can't say what it is.
In any case it is not a general docker issue but something specific to my situation.  I will have to investigate further or otherwise live with a work-around.
So if you want to close the issue it is OK with me. I case I come up with something more specific we can reopen the issue again.

**Comment by thaJeztah** [comment] 2021-06-30 19:39
Closing per the above

**Closed by thaJeztah** 2021-06-30 19:39 UTC
Labels: area/networking, status/more-info-needed
