### ISSUE TITLE
docker container can't ping outside net

### ISSUE THREAD

**Issue by feiyuewuyue** [moby/moby#35260] opened 2017-10-20 09:17 UTC
hi：
     my system version is centos 6.9，my docker version is 1.7.1.When I run new container by bridge mode,my  physical machine can't ping the container ip. I have seted net.ipv4.ip_forward = 1

**Comment by thaJeztah** [comment] 2017-10-20 13:00
@feiyuewuyue CentOS 6 is not a supported platform for current versions of Docker, and Docker 1.7.1 has reached EOL. There's not much that can be done in this repository because of that.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-20 13:00 UTC
