### ISSUE TITLE
Containers in Standalone Swarm has a unrealistic disk space utilization.

### ISSUE THREAD

**Issue by hard-fault** [moby/moby#36399] opened 2018-02-24 03:32 UTC
```
[root@ip-172-31-46-216 CIBO-Scripts]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1  8.0G  7.1G  956M  89% /
devtmpfs        7.6G     0  7.6G   0% /dev
tmpfs           7.6G     0  7.6G   0% /dev/shm
tmpfs           7.6G   17M  7.6G   1% /run
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
tmpfs           1.6G     0  1.6G   0% /run/user/1000
/dev/nvme1n1     99G  5.6G   88G   6% /disk
tmpfs           1.6G     0  1.6G   0% /run/user/0
overlay         8.0G  7.1G  956M  89% /var/lib/docker/overlay2/26f9f654feb134999cf089985fe7b70054d98a60fe92d0483875fb1b359bca37/merged
shm              64M     0   64M   0% /var/lib/docker/containers/3a1c7f8c8428ef0a9e71c4432b5b8ab059c2ea031da50934e0d6911b32ca8c68/shm
overlay         8.0G  7.1G  956M  89% /var/lib/docker/overlay2/085d600d55d8332015026ea7f536684d5938bc19324677b7b1fff85a440913e6/merged
shm              64M     0   64M   0% /var/lib/docker/containers/4280c73134e3603e9e27846b1cfdd77ecd3dbdf8d8848ddf0d1264120e52444d/shm
overlay         8.0G  7.1G  956M  89% /var/lib/docker/overlay2/3fed5f592e2ff69812851040c6851a5b4ff734fcf6e1c1e6bad4837c1896499d/merged
shm              64M     0   64M   0% /var/lib/docker/containers/7175d27054da2c3c89ff5d82c642b9a0b556bce623f936a801f38052bb83968f/shm
overlay         8.0G  7.1G  956M  89% /var/lib/docker/overlay2/ffd63946fe0061fe64d4e6330e7c9b12904f97319ca68a9a119e98d18c361803/merged
shm              64M     0   64M   0% /var/lib/docker/containers/8fbcc8721f510d79b76cd2b4d01d4e919cf477cc7848acb2e6a0524a3e527ef2/shm
overlay         8.0G  7.1G  956M  89% /var/lib/docker/overlay2/7612a0fbcffa49bf62afb477e6b284d1bf292c1a32610b07c93acf59eef0cbae/merged
shm              64M     0   64M   0% /var/lib/docker/containers/8dee6c29cd7dd210ccedb819f0c1c39b0ed7872b2f646a57009c88706ef6594a/shm
```

**Comment by cpuguy83** [comment] 2018-02-24 10:39
In the future, please fill in the issue template so we have some idea as to what the issue is.

Assuming you are referring to the multiple entries for different containers with  the same size and usage, this is how overlay works since it sits on top of the existing filesystem.

Closing because this is not a bug and is working as expected, but feel free to discuss. Thanks!

**Closed by cpuguy83** 2018-02-24 10:39 UTC

**Comment by thaJeztah** [comment] 2018-02-24 10:40
Containers are not VMs; unlike VMs, containers don't get their own set of resources assigned, but share resources (including CPU, Memory, Disk) with other processes (and thus other containers) on the same host. You can _restrict_ resources (don't use more than xx CPU, xx Memory), and depending on the storage driver you're using, you can apply disk quota.

Having said the above: 

The GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

If you _do_ suspect there's a bug, please provide the information that's requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'm closing this issue because this is not a bug, but feel free to comment

**Comment by thaJeztah** [comment] 2018-02-24 10:41
oh, whoops, @cpuguy83 already closed 😊
