### ISSUE TITLE
RUN instruction which touches a file duplicates into new layer

### ISSUE THREAD

**Issue by theimpostor** [moby/moby#47399] opened 2024-02-16 22:12 UTC
### Description

If a RUN instruction in a Dockerfile touches (but does not modify timestamps or attributes) a file, that file gets duplicated into the current layer resulting in a larger image.

### Reproduce

```
❯ cat Dockerfile
FROM fedora:39

# the file modification time and contents of libpython3.12.so.1.0 do not change
# yet a layer 6.69 MB in size is created.
# Does't matter if the 'touch -m' option (don't change access time) is used instead
RUN touch -r /usr/lib64/libpython3.12.so.1.0 /usr/lib64/libpython3.12.so.1.0
```
```
❯ docker build --no-cache -t touched .
[+] Building 0.3s (6/6) FINISHED                                                                                                                            docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                        0.0s
 => => transferring dockerfile: 376B                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/fedora:39                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                             0.0s
 => CACHED [1/2] FROM docker.io/library/fedora:39                                                                                                                           0.0s
 => [2/2] RUN touch -r /usr/lib64/libpython3.12.so.1.0 /usr/lib64/libpython3.12.so.1.0                                                                                      0.2s
 => exporting to image                                                                                                                                                      0.0s
 => => exporting layers                                                                                                                                                     0.0s
 => => writing image sha256:a2a07f58a3e740a30cb17c9184593199cc6a442d15f6c8c8a05a5d2d7b590b36                                                                                0.0s
 => => naming to docker.io/library/touched                                                                                                                                  0.0s
```
```
❯ docker history touched
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
a2a07f58a3e7   13 seconds ago   RUN /bin/sh -c touch -r /usr/lib64/libpython…   6.69MB    buildkit.dockerfile.v0
<missing>      2 months ago     /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B
<missing>      2 months ago     /bin/sh -c #(nop) ADD file:cee2cb1288ac4fde7…   177MB
<missing>      11 months ago    /bin/sh -c #(nop)  ENV DISTTAG=f39container …   0B
<missing>      2 years ago      /bin/sh -c #(nop)  LABEL maintainer=Clement …   0B
```
```
❯ dive touched --ci
  Using default CI config
Image Source: docker://touched
Fetching image... (this can take a while for large images)
Analyzing image...
  efficiency: 96.3654 %
  wastedBytes: 13375472 bytes (13 MB)
  userWastedPercent: 200.0000 %
Inefficient Files:
Count  Wasted Space  File Path
    2         13 MB  /usr/lib64/libpython3.12.so.1.0
Results:
  FAIL: highestUserWastedPercent: too many bytes wasted, relative to the user bytes added (%-user-wasted-bytes=2 > threshold=0.1)
  SKIP: highestWastedBytes: rule disabled
  PASS: lowestEfficiency
Result:FAIL [Total:3] [Passed:1] [Failed:1] [Warn:0] [Skipped:1]
```

### Expected behavior

The new layer should be 0 bytes in size since nothing has changed from the previous layer.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.27.2 (137060)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/shoda/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5-desktop.1
    Path:     /Users/shoda/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/shoda/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/shoda/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/shoda/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/shoda/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/shoda/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/shoda/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.4.1
    Path:     /Users/shoda/.docker/cli-plugins/docker-scout

Server:
 Containers: 21
  Running: 0
  Paused: 0
  Stopped: 21
 Images: 85
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.62GiB
 Name: docker-desktop
 ID: 15cba345-4ab6-4e5a-adfb-c4711350c69d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by vvoland** [comment] 2024-02-19 10:14
Unfortunately that's expected and it's not possible to efficiently represent (in a portable way) with a separate layer using the [current image layer spec](https://github.com/opencontainers/image-spec/blob/v1.0/layer.md).

**Comment by thaJeztah** [comment] 2024-02-19 10:21
I think this is currently expected with overlayfs, and is how overlayfs works.

Here's the same example, but not using a container, just an overlayfs mount on the host;

First, creating a directory to work in, and the required "lower", "upper", "work" directories, as well as a "container" directory, which will be the mount-point for overlay-filesystem used as the container's "rootfs". The "lower" dir is the read-only "image" layer(s) of the container. The "upper" dir is the equivalent of the container's writable layer, and will contain files that end up in a new layer;

```bash
mkdir repro-47399 && cd repro-47399

mkdir lower upper work container

mkdir -p lower/usr/lib64

echo "hello-world" > lower/usr/lib64/libpython3.12.so.1.0
```


Directory tree looks like this;

```bash
tree
.
├── container
├── lower
│   └── usr
│       └── lib64
│           └── libpython3.12.so.1.0
├── upper
└── work
    └── work

7 directories, 1 file
```

Mount the overlay filesystem for the container;

```bash
mount -t overlay overlay -olowerdir=./lower,upperdir=./upper,workdir=./work ./container
```


The container now shows the same files as the image (as expected), and the "upper" dir is empty, as there's no changes made to the container;

```bash
tree
.
├── container
│   └── usr
│       └── lib64
│           └── libpython3.12.so.1.0
├── lower
│   └── usr
│       └── lib64
│           └── libpython3.12.so.1.0
├── upper
└── work
    └── work

9 directories, 2 files
```


Now, `touch` the file inside the container;

```bash
touch -r container/usr/lib64/libpython3.12.so.1.0 container/usr/lib64/libpython3.12.so.1.0
```

Note that a file is added to the `upper` dir;

```bash
tree
.
├── container
│   └── usr
│       └── lib64
│           └── libpython3.12.so.1.0
├── lower
│   └── usr
│       └── lib64
│           └── libpython3.12.so.1.0
├── upper
│   └── usr
│       └── lib64
│           └── libpython3.12.so.1.0
└── work
    └── work

11 directories, 3 files
```

And, while the modified date is the same, it does have a new inode (it's a new file);

```bash
tree -D --inodes
.
├── [ 258542 Feb 19  9:46]  container
│   └── [ 258546 Feb 19  9:49]  usr
│       └── [ 258548 Feb 19  9:49]  lib64
│           └── [ 258550 Feb 19  9:49]  libpython3.12.so.1.0
├── [ 258542 Feb 19  9:49]  lower
│   └── [ 258546 Feb 19  9:49]  usr
│       └── [ 258548 Feb 19  9:49]  lib64
│           └── [ 258550 Feb 19  9:49]  libpython3.12.so.1.0
├── [ 258543 Feb 19  9:46]  upper
│   └── [ 258551 Feb 19  9:49]  usr
│       └── [ 258552 Feb 19  9:49]  lib64
│           └── [ 258554 Feb 19  9:49]  libpython3.12.so.1.0
└── [ 258544 Feb 19  9:52]  work
    └── [ 258547 Feb 19  9:55]  work

11 directories, 3 files
```

**Comment by thaJeztah** [comment] 2024-02-19 10:22
It might be possible to optimize for this situation, but this would require doing a full scan of files in the writable layer and, when creating the image-layer, scanning all files to compare them with their equivalent in the underlying layers, but (depending on the number of files) this could bring a significant overhead, so this would need to be looked into. There's an existing ticket related to that;

- https://github.com/moby/moby/issues/35280

Let me closed this one as a duplicate of the one above.

**Closed by thaJeztah** 2024-02-19 10:22 UTC
Labels: area/builder, area/builder/classic-builder, area/builder/buildkit

**Comment by theimpostor** [comment] 2024-02-20 15:30
Bummer. Thank you for the detailed explanation.
