### ISSUE TITLE
Connections to ports published to secondary interface fail with source IP routing

### ISSUE THREAD

**Issue by nosnilmot** [moby/moby#35251] opened 2017-10-19 14:42 UTC
On a Linux system with dual network interfaces, where source IP routing is configured, ports published to the secondary interface are unusable as connections timeout.

**Steps to reproduce the issue:**
1. Configure Linux system with 2 network interfaces and source IP routing - eg. Amazon Linux on AWS configures this by default when setup with eth0 & eth1
2. Run any container and publish port to secondary IP address
3. Attempt to connect to published port

**Describe the results you received:**
Connections to ports published to secondary IP address/interface timeout

**Describe the results you expected:**
Connections to ports published to secondary IP address/interface succeed

**Additional information you deem important (e.g. issue happens only occasionally):**
See below for detailed network information

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.51-10.52.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.5 MiB
Name: ip-172-62-0-26
ID: V23S:MLND:IKOY:EQFO:PZE2:UNOH:2U5Z:LKVU:3CE5:GTEC:EGX3:4MKV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Environment: AWS
OS: Amazon Linux 2017.09
Docker version: 17.03.2-ce, build 7392c3b/17.03.2-ce

ip addr show
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:8d:48:82:26:ca brd ff:ff:ff:ff:ff:ff
    inet 172.62.0.26/26 brd 172.62.0.63 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a05:d018:9c7:5500:5f3:8dda:d582:ec13/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::8d:48ff:fe82:26ca/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:92:ce:a7:8d:70 brd ff:ff:ff:ff:ff:ff
    inet 172.62.0.220/27 brd 172.62.0.223 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::92:ceff:fea7:8d70/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:06:a4:62:b9 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:6ff:fea4:62b9/64 scope link 
       valid_lft forever preferred_lft forever
```

ip route show
```
default via 172.62.0.1 dev eth0 
default via 172.62.0.193 dev eth1  metric 10001 
169.254.169.254 dev eth0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
172.62.0.0/26 dev eth0  proto kernel  scope link  src 172.62.0.26 
172.62.0.192/27 dev eth1  proto kernel  scope link  src 172.62.0.220 
```

ip rule show
```
0:	from all lookup local 
32765:	from 172.62.0.220 lookup 10001 
32766:	from all lookup main 
32767:	from all lookup default 
```

ip route show table 10001
```
default via 172.62.0.193 dev eth1 
172.62.0.192/27 dev eth1  proto kernel  scope link  src 172.62.0.220 
```

Run sample app with no specific IP binding (default all / 0.0.0.0/0)
```
[root@ip-172-62-0-26 ~]# docker run -d -p 5000:5000 training/webapp:latest python app.py
3a0fe9dd3899ad33e30c3c7d61cfed7897edf3f8eabd17746386782dd9f5125a
```
Success connecting to eth0/primary IP address:
```
[root@ip-172-62-0-26 ~]# curl --connect-timeout 5 http://172.62.0.26:5000/
Hello world!
```
Failure/timeout connecting to eth1/secondary IP address:
```
[root@ip-172-62-0-26 ~]# curl --connect-timeout 5 http://172.62.0.220:5000/
curl: (28) Connection timed out after 5001 milliseconds
```
Does not help if binding explicitly to secondary IP address:
```
[root@ip-172-62-0-26 ~]# docker run -d -p 172.62.0.220:5000:5000 training/webapp:latest python app.py
418ce0023166f055795f7af28cc3d67ef13a4093dbb53256391c1389ee4e3e05

[root@ip-172-62-0-26 ~]# curl --connect-timeout 5 http://172.62.0.220:5000/
curl: (28) Connection timed out after 5001 milliseconds
```

netstat -tlpn
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      2830/sshd           
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      2860/sendmail       
tcp        0      0 0.0.0.0:35193               0.0.0.0:*                   LISTEN      2598/rpc.statd      
tcp        0      0 172.62.0.220:5000           0.0.0.0:*                   LISTEN      6493/docker-proxy   
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      2577/rpcbind               
tcp        0      0 :::22                       :::*                        LISTEN      2830/sshd                 
tcp        0      0 :::56013                    :::*                        LISTEN      2598/rpc.statd      
tcp        0      0 :::111                      :::*                        LISTEN      2577/rpcbind              
```

iptables rules:
```
[root@ip-172-62-0-26 ~]# iptables -L -nv
Chain INPUT (policy ACCEPT 54 packets, 3732 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 33 packets, 3504 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:5000

Chain DOCKER-ISOLATION (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

iptables NAT rules
```
[root@ip-172-62-0-26 ~]# iptables -t nat -L -nv
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    3   514 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 1 packets, 76 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    7   420 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 1 packets, 76 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:5000

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            172.62.0.220         tcp dpt:5000 to:172.17.0.2:5000
```

Removing the source IP routing (ip route flush table 10001) allows these connections to succeed from the host, but is not an acceptable solution as the routing is required for correct behaviour of other network traffic.

**Comment by nosnilmot** [comment] 2017-11-08 11:42
This issue still exists in Docker 17.06.2:

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Tue Oct 17 18:33:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   402dd4a/17.06.2-ce
 Built:        Tue Oct 17 18:34:10 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 1
 Paused: 0
 Stopped: 9
Images: 1
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.51-10.52.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.5MiB
Name: ip-172-62-0-26
ID: V23S:MLND:IKOY:EQFO:PZE2:UNOH:2U5Z:LKVU:3CE5:GTEC:EGX3:4MKV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by nosnilmot** [comment] 2017-11-10 10:55
Same issue with 17.09 too:

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.51-10.52.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.5MiB
Name: ip-172-62-0-26
ID: V23S:MLND:IKOY:EQFO:PZE2:UNOH:2U5Z:LKVU:3CE5:GTEC:EGX3:4MKV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-11-10 11:42
ping @fcrisciani @mavenugo  PTAL

**Comment by nosnilmot** [comment] 2017-12-28 13:36
Same issue with 17.12 too:

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:38 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 3
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.51-10.52.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.5MiB
Name: ip-172-62-0-26
ID: V23S:MLND:IKOY:EQFO:PZE2:UNOH:2U5Z:LKVU:3CE5:GTEC:EGX3:4MKV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ddebroy** [comment] 2018-01-06 08:00
I took a look at this. Here is what is needed to get packets to route back properly through other interfaces like eth1 given the system is set up in a way described exactly like the above:

1. Set rp_filter to loose mode (2) from strict mode as mentioned in https://access.redhat.com/solutions/53031: 
```
echo 2 > /proc/sys/net/ipv4/conf/default/rp_filter
echo 2 > /proc/sys/net/ipv4/conf/all/rp_filter
```
2. Mark connections and transfer the mark to response packets from containers (both docker run with published ports as well as swarm mode services):
```
iptables -t mangle -A PREROUTING -i eth1 -j CONNMARK --set-mark 1
iptables -t mangle -A PREROUTING -i docker0 -j CONNMARK --restore-mark
iptables -t mangle -A PREROUTING -i docker_gwbridge -j CONNMARK --restore-mark
```
3. Set routing rules based on the above mark to reference the source based routing tables already set up:
```
ip rule add iif docker0 fwmark 1 table 10001
ip rule add iif docker_gwbridge fwmark 1 table 10001
```
4. Flush the routing cache:
```
ip route flush cache
```

At this point, you should be able to reach the published ports from containers/services across all interfaces of a host.

**Comment by thaJeztah** [comment] 2018-01-06 13:29
@ddebroy any changes needed in libnetwork for this?

**Comment by ddebroy** [comment] 2018-01-08 07:36
If the user/admin is okay with executing the steps above (or something roughly similar to the above based on the names associated with the custom policy routing tables for the interfaces), no changes in libnetwork is needed. 

If we want the above steps to be automated as part of docker installation, then we need to enhance libnetwork to add the iptable rules, probe for the custom routing tables corresponding to each interface and create ip rules referencing them. The probing heuristics might be a bit tricky.

Maybe we can start with some documentation/guidance for multi nic hosts with a detailed example as above and add the automation later if there is a lot of community demand for it?

**Comment by nosnilmot** [comment] 2018-01-08 09:23
Thanks for taking a look at this. I would prefer to have docker/libnetwork handle the necessary configuration automatically if possible, but obviously first step would be to get manual configuration working.

Unfortunately, simply executing the above steps verbatim does not get this working for me. I did try disabling source validation entirely (rp_filter = 0), but that did not appear to help. What additional information could I usefully provide?

FYI, this configuration is the default multi-nic configuration for Amazon Linux on AWS EC2 instances, so I'm surprised it has not come up before.

**Comment by thaJeztah** [comment] 2018-01-08 10:25
@ddebroy does libnetwork currently take these steps for the primary interface? Should it do those steps _by default_, or "on demand" (i.e. once someone publishes a port on `<other-interface>:<port>`)?

**Comment by ddebroy** [comment] 2018-01-09 22:12
@thaJeztah the primary interface (e.g. eth0 in the above setups) does not need to be subjected to any special steps (like the ones mentioned for eth1, etc.) since the proper routing happens automatically for them. This is because in the main routing table, the default gateway route for eth0 has a low metric and therefore the kernel chooses to route packet over eth0 by default.

**Comment by ddebroy** [comment] 2018-01-10 00:05
@nosnilmot when testing the steps I mentioned above, I was issuing `curl` from a separate VM that could reach the host VM (with multiple NICs hosting the containers) over either NIC's address. 

Example from Ubuntu VM1 with IP 172.31.39.180 to Amazon Linux VM2 with IP 172.31.96.42 and 172.31.111.217:
```
ubuntu@ip-172-31-39-180:~$ curl http://172.31.96.42:80
<!DOCTYPE html>
<html>
...
</html>

ubuntu@ip-172-31-39-180:~$ curl http://172.31.111.217:80
<!DOCTYPE html>
<html>
...
</html>
```
Re-reading your test steps, it seems like you are trying to test reachability of the containers on the same VM? If that is what you need you need to add a route to the containers on the special routing table for eth1 on the container host:
```
ip route add table 10001 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
```

**Comment by ddebroy** [comment] 2018-01-11 20:58
@nosnilmot let us know if the above steps gives you the desired result. If so, we can close this issue. 
 
Performing the above changes automatically by docker is not something we should implement in docker. Primary reason for that is loosening the rp_table setting goes against security best practice (set by default by distros) that admin should explicitly invoke.

**Comment by thaJeztah** [comment] 2018-01-16 18:36
Thanks @ddebroy - looks like this is a configuration issue, and not a bug. I'll close this issue here, because there's nothing actionable in this repository, but if someone thinks this would be good to add to the documentation; feel free to open a pull request in the docs repo: https://github.com/docker/docker.github.io

**Closed by thaJeztah** 2018-01-16 18:36 UTC
Labels: area/networking, version/17.03

**Comment by ccding** [comment] 2019-05-27 05:27
Got exactly the same problem, and the above solution doesn't work.

I am on EC2 ubuntu 16.04, Docker version 18.09.6
