### ISSUE TITLE
Exposed port can be changed if container is connected to another network

### ISSUE THREAD

**Issue by olukas** [moby/moby#42991] opened 2021-11-05 12:41 UTC
If container is connected to second network then exposed port is changed if the name of second network is lexicographically ordered before the name of original network.

The issue is really confusing if the names of network are not set explicitly (i.e. if some random id is generated) because it looks like the mapped ports are changed randomly (it's hard to realize it depends on the name of network).

This issue can be related to https://github.com/moby/moby/issues/40740.

Output of `docker version`:
```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~18.04.2
 Built:             Fri Oct  1 21:47:31 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~18.04.2
  Built:            Fri Oct  1 13:28:27 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~18.04.3
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~18.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Steps to reproduce:**
Create 2 networks `net1` and `net2` and run docker container which is connected to `net2`:
```
docker network create net1 > /dev/null
docker network create net2 > /dev/null
docker run --name test1 -it -d --network net2 -p 5701 hazelcast/hazelcast:5.0 > /dev/null
```
Run `docker ps` to see mapped port (`0.0.0.0:49224->5701/tcp`):
```
CONTAINER ID   IMAGE                     COMMAND      CREATED         STATUS         PORTS                                         NAMES
a4539db0449e   hazelcast/hazelcast:5.0   "hz-start"   4 seconds ago   Up 2 seconds   0.0.0.0:49224->5701/tcp, :::49224->5701/tcp   test1
```
Connect docker container do network `net1`:
```
docker network connect net1 test1 > /dev/null
```
Run `docker ps` to see mapped port (`0.0.0.0:49225->5701/tcp`):
```
CONTAINER ID   IMAGE                     COMMAND      CREATED              STATUS              PORTS                                         NAMES
a4539db0449e   hazelcast/hazelcast:5.0   "hz-start"   About a minute ago   Up About a minute   0.0.0.0:49225->5701/tcp, :::49225->5701/tcp   test1
```

**Comment by thaJeztah** [comment] 2021-11-05 14:57
Thanks for reporting; reading through https://github.com/moby/moby/issues/40740, I think this is a duplicate of that ticket, so let me close this one to prevent the conversation from diverging.

In general, I would recommend mapping a specific port if the port is important for your use-case; I know there has been earlier discussions about making the random port "stick, but there's many scenarios where the random port may change (and a new random port assigned), e.g. after a reboot and/or restart of the container.

**Closed by thaJeztah** 2021-11-05 14:57 UTC
Labels: kind/enhancement, area/networking
