### ISSUE TITLE
"make generate" No rule to make target

### ISSUE THREAD

**Issue by wangxf1987** [moby/moby#35897] opened 2017-12-29 03:59 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

modified the objects.proto file, and then run  the command "make generate",
some errors like this:
"make generate" No rule to make target

**Steps to reproduce the issue:**
1. cd moby
2. run "make generate"
3. above stop have occur: No rule to make target

**Describe the results you received:**
 No rule to make target

**Describe the results you expected:**
run "make generate" and the result is normal

**Additional information you deem important (e.g. issue happens only occasionally):**
the folder is correct ?
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vdemeester** [comment] 2018-01-02 08:00
@wangxf1987 which protos did you change ? The error message speaks for itself, there is no `generate` target in the `moby` `Makefile`. Most likely, the `protos` changed are in a dependency (in `vendor/` folder) and thus should be done upstream.

**Comment by wangxf1987** [comment] 2018-01-02 08:32
@vdemeester I want to change the objects.proto. And use command,
`protoc -I=vendor --go_out=vendor/github.com/docker/swarmkit/api/objects.pb.go vendor/github.com/docker/swarmkit/api/objects.proto` that regenerate it. but the result show the path is error,
`gogoproto/gogo.proto: File not found.
github.com/docker/swarmkit/api/types.proto: Import "gogoproto/gogo.proto" was not found or had errors.
github.com/docker/swarmkit/api/specs.proto: Import "github.com/docker/swarmkit/api/types.proto" was not found or had errors.
github.com/docker/swarmkit/api/specs.proto: Import "gogoproto/gogo.proto" was not found or had errors.
github.com/docker/swarmkit/api/specs.proto:22:9: "Annotations" is not defined.
github.com/docker/swarmkit/api/specs.proto:47:9: "NodeRole" is not defined.
github.com/docker/swarmkit/api/specs.proto:64:9: "Annotations" is not defined.
github.com/docker/swarmkit/api/specs.proto:75:9: "UpdateConfig" is not defined.
github.com/docker/swarmkit/api/specs.proto:78:9: "UpdateConfig" is not defined.`
I do that in the moby root folder, How should i set the path parameters.
Thx!!!

**Comment by thaJeztah** [comment] 2018-01-02 11:12
@wangxf1987 yes, those files are vendored in, and actually part of SwarmKit (see the path: `vendor/github.com/docker/swarmkit/api/objects.pb.go`), which comes from the https://github.com/docker/swarmkit repository.

Vendored files are "upstream" dependencies, and no changes should be made to those files in this repository. Changes in vendored files need to  be made upstream, after which the updated versions are pulled in from upstream.

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-01-02 11:12 UTC

**Comment by wangxf1987** [comment] 2018-01-03 03:53
@thaJeztah Thanks for your relay, I cloned the repo from https://github.com/docker/swarmkit. It's need to changed the objects.proto in the api folder, and then run command `make generate` in the root of swarmkit. It's does work. But I still have some issues, why the swarmkit master version can not run the protobuf version 3.5.1 ?
BTW, The swarmkit project must be place in the GOPATH.
