### ISSUE TITLE
Feature Request: Show image/volume details before approving their prunes

### ISSUE THREAD

**Issue by avimanyu786** [moby/moby#42556] opened 2021-06-23 07:34 UTC
In the current methodology, the user cannot view image(s) that is/are going to be removed before approval.

Example:
```
user@server:~$ docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N]
```
Similarly with volumes, the same scenario is noticeable.

Example:
```
user@server:~$ docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N]
```
I've had this use case in the past when using external volumes, that were removed even when being used by running containers. They got removed even it that scenario. This could have been avoided if the volume names were shown earlier before approval.

Images' example for requested revision:
```
user@server:~$ docker image prune -a
WARNING! This will remove the following images without at least one container associated to them:
1. nextcloud:20.0.2 pulled on 05-14-2021
2. ghost:4.6.4 pulled on 05-14-2021
3. php:7.4.20 pulled on 05-14-2021
Are you sure you want to continue? [y/N]
```
Volumes' example for requested revision:
```
user@server:~$ docker volume prune
WARNING! This will remove the following local volumes not used by at least one container:
1. nextcloud created on 05-14-2021
2. ghost created on 05-14-2021
3. php created on 05-14-2021
Are you sure you want to continue? [y/N]
```

Hence I believe that showing the volume or image names beforehand is a better approach than showing their names after removal. It would be a much safer and reliable approach, especially a relief when working in production environments.

**Comment by thaJeztah** [comment] 2021-06-23 13:12
Thanks for reporting; this looks like a duplicate of https://github.com/moby/moby/issues/30623 (and https://github.com/moby/moby/issues/39418)

Let me close this ticket to prevent the discussion from diverging, but feel free to participate on https://github.com/moby/moby/issues/30623

**Closed by thaJeztah** 2021-06-23 13:12 UTC
Labels: area/cli, kind/enhancement
