### ISSUE TITLE
Cannot create network of type ipvlan: legacy plugin: plugin not found

### ISSUE THREAD

**Issue by stephan2012** [moby/moby#34717] opened 2017-09-04 07:56 UTC
**Description**

Cannot create a Docker network of type _ipvlan_.

**Steps to reproduce the issue:**

```
# docker network create -d ipvlan -o ipvlan_mode=l3 --subnet=192.168.0.0/16 --ip-range=192.168.1.0/24 --aux-address="exclude_host=192.168.1.1" -o parent=eth1 test    
Error response from daemon: legacy plugin: plugin not found
```

**Describe the results you received:**
`docker network create` terminates with the error shown above. The command succeeds for _macvlan_ networks.

**Describe the results you expected:**
ipvlan network should have been created.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
# docker info
Containers: 43
 Running: 43
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.06.1-ce
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available
 Parent Dataset: apppool/docker
 Space Used By Parent: 1534119936
 Space Available: 96001773568
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay store/weaveworks/net-plugin:2.0.1
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: owuxxijlvuxv1fgbr7pg9uov9
 Is Manager: true
 ClusterID: bxv0d01o9vbv7h7cpsmhdpu1d
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.197.80.151
 Manager Addresses:
  10.197.80.151:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.1.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 62.75GiB
Name: hseecwebapp1d
ID: IYVD:DKL5:GZOZ:THBQ:Z4RQ:EYCT:54YV:QO6W:2VMH:JW7B:SJM5:VRRO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.company.com:8080
Https Proxy: http://proxy.company.com:8080
No Proxy: localhost,127.0.0.1,.intern.company.com
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM running on VMware vSphere 6.5

**Comment by stephan2012** [comment] 2017-09-04 19:59
After starting `dockerd` with option `--experimental=true` a somewhat more helpful message is shown:

```
docker network create -d ipvlan --subnet=172.31.0.0/16 --ip-range=172.31.1.0/24 --aux-address="exclude_host=172.31.1.1" -o parent=eth1 ipvlan31                   
Error response from daemon: kernel version failed to meet the minimum ipvlan kernel requirement of 4.2, found 3.10.0
```

Lokks like bad luck with CentOS 7.3 and RHEL 7.4.

**Comment by xdexter** [comment] 2017-09-18 14:16
+1

**Comment by thaJeztah** [comment] 2017-09-18 15:53
Yes, this is expected: IP vlan networks are still an experimental feature; https://github.com/docker/docker-ce/blob/v17.06.2-ce/components/cli/experimental/vlan-networks.md#ipvlan-network-driver, so the driver is only known when the daemon is started with experimental features enabled.

Without the `--experimental` flag, the driver won't be found by the daemon, so it will attempt to look for a plugin that offers the driver; that's why the error message is shown.

I'm closing this, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-09-18 15:53 UTC
Labels: area/networking, kind/experimental, version/17.06
