### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by ahmedbokhari7** [moby/moby#40834] opened 2020-04-19 13:33 UTC
when i build my docker file i get this error although target directory is there in my java project
can some plz help
''''''''''''''''''''''''''''''''''''''''''''''''''
my docker file is below:
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.in28minutes.rest.webservices.restfulwebservices.RestfulWebServicesApplication"]

and when i build it by typing docker build . i get the issue which is pasted below

sending build context to Docker daemon 84.99kB
Step 1/7 : FROM openjdk:8-jdk-alpine
---> a3562aa0b991
Step 2/7 : VOLUME /tmp
---> Using cache
---> c8ca5e3ac388
Step 3/7 : ARG DEPENDENCY=target/dependency
---> Using cache
---> 1a1a2a4a5db1
Step 4/7 : COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY failed: stat /var/lib/docker/tmp/docker-builder997333669/target/dependency/BOOT-INF/lib: no such file or directory

**Comment by thaJeztah** [comment] 2020-05-27 21:15
The error is that you'e trying to copy a file to the image from `target/dependency/BOOT-INF/lib` in your build context (probably your current directory), and that directory / file is missing, which makes the build fail.

Make sure that file/directory exists and is not ignored in your `.dockerignore`

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 21:15 UTC
