### ISSUE TITLE
Compose v3 launch order

### ISSUE THREAD

**Issue by frimdo** [moby/moby#33891] opened 2017-06-30 08:23 UTC
**Docker compose v3 depends-on does not affect creation order of services**

My compose file looks something like this:
```
version: "3"
services:
  semaphore:
    image: semaphore
    deploy:
      replicas: 1
    ports:
      - "8080:3000"
    networks:
      - semaphore_network
    depends_on:
      - mysql
      - etcd

  etcd:
    image: elcolio/etcd:latest
    deploy:
      replicas: 1
    networks:
      - semaphore_network
    command: -name etcd -discovery=${ETCD_DISCOVERY:-UNSET}

  mysql-galera:
    image: perconalab/percona-xtradb-cluster:5.6
    deploy:
      replicas: 3
    networks:
      - semaphore_network
    depends_on:
      - etcd
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - DISCOVERY_SERVICE=etcd:2379
      - XTRABACKUP_PASSWORD=mypassword
      - CLUSTER_NAME=galera
networks:
  semaphore_network:
    driver: overlay
```
As we can see, the launch order should be 1. etcd, 2. mysql, 3. semaphore. But when I do stack deploy, I get:
```
docker stack deploy -c semaphore.yml semaphore
Creating service semaphore_semaphore
Error response from daemon: network semaphore_semaphore_network not found
```

Now we can see 2 errors: 
1. semaphore_semaphore is being created first
2. the network, that should be created before all services is not started yet...

**Output of `docker version`:** 
```
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
# docker info
Containers: 11
 Running: 6
 Paused: 0
 Stopped: 5
Images: 35
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: it8bharqefr1k8xsmonscngsy
 Is Manager: true
 ClusterID: jbxeizda8htiwan1pth2c7kl5
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 81.2.254.225
 Manager Addresses:
  81.2.254.225:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1000MiB
Name: DominikFriml3
ID: W7MT:HWZR:4O2T:OAWW:OSQK:47FN:LXEK:INEG:EC5P:WIFO:2B34:BARB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by dnephin** [comment] 2017-06-30 16:33
Can you include the output of `docker network ls` ? I think there might be a non-swarm scoped network with the same name which is breaking the network creation.

`depends_on` is ignored in `stack deploy` (https://docs.docker.com/compose/compose-file/#depends_on). This is by design. Order of startup should not matter for services.

**Comment by frimdo** [comment] 2017-06-30 19:13
Oh - for some reason, the network from previous stack test was not deleted. Thank you.

Speaking of startup order: How do I make services not dependent? For example when I have an app depending on DB, do I have to write waiting script (script that waits for DB service to be ready), or let there enough restart attempts? Or is there some better way?

**Comment by dnephin** [comment] 2017-06-30 19:30
An entrypoint script that waits for the database is one option. The best way is to have the application code start up even if the database is unavailable, and reconnect to the DB when the app receives a request.

**Comment by frimdo** [comment] 2017-06-30 20:46
So for packing an existing app, that I can not edit to this behaving, you recommend entrypoint script?

**Comment by thaJeztah** [comment] 2017-07-02 23:33
This is a duplicate of https://github.com/moby/moby/issues/31333, which has some additional information on this subject. I'll close this issue to prevent the discussion from diverging

**Closed by thaJeztah** 2017-07-02 23:33 UTC
Labels: area/bundles, kind/enhancement

**Comment by StefanScherer** [comment] 2018-04-05 07:12
I got the same error today with Docker 18.03.0-ce. My fault, I was to fast running `docker stack rm test` and `docker stack deploy -c stack.yml test`
It takes some seconds util the swarm networks have been deleted. :-)
