### ISSUE TITLE
TIOCSCTTY failed on UNKNOWN-bash: cannot set terminal process group (-1): Inappropriate ioctl for device

### ISSUE THREAD

**Issue by venantius** [moby/moby#2780] opened 2013-11-20 05:20 UTC
Issue is related to an error message I get if I try to do `login -f root` as my entry command, e.g. by doing `docker run -i -t venantius/raring-nginx login -f root`

Full message looks like this:

```
root@belial:~/dockerfiles/raring-nginx# docker run -i -t venantius/raring-nginx login -f root

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

Welcome to Ubuntu 13.04 (GNU/Linux 3.8.0-33-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
TIOCSCTTY failed on UNKNOWN-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
-bash: no job control in this shell
(core-dev)[root@18c1227222b4:~] 05:17:25 $
```

This is on Ubuntu 12.04, container ubuntu 13.04, Docker version 0.6.6. Spawning a new issue from https://github.com/dotcloud/docker/issues/2424 so that I can actually close that one up.

**Comment by jfrazelle** [comment] 2015-02-25 21:56
I think this can be closed now @thaJeztah can you still reproduce, ill leave open for now :)

**Comment by thaJeztah** [comment] 2015-02-25 23:50
@jfrazelle I'm still getting this error;

```bash
docker run -it --rm ubuntu:14.04 login -f root

# Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law.
# TIOCSCTTY failed on /dev/console-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
# -bash: no job control in this shell

```

Doing the same in a Dockerfile works;

```bash

cat << EOF > Dockerfile
FROM ubuntu:14.04
CMD login -f root
EOF

docker build -t foobar .
docker run -it --rm foobar

# Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law.

```

However, https://github.com/docker/docker/issues/2780#issuecomment-51642641 might give what most users need and I haven't seen reports recently, it could be treated as a corner-case, so not sure if it's worth time spending on?

**Comment by jfrazelle** [comment] 2015-02-25 23:52
ah ok cool good to know

**Comment by jfrazelle** [comment] 2015-02-25 23:52
idk i put black-belt but lmk if you think differently

**Comment by gimoh** [comment] 2015-09-01 11:04
@crosbymichael my use-case for running login is recording demos of interactive TTY sessions emulating different users; ``docker run`` doesn't set the environment for everything to work (e.g. HOME, LANG, etc.), sure you can put everything in a Dockerfile but these are things the guest OS already knows how to take care of so I'd rather avoid duplicating everything in the Dockerfile

**Comment by mzedeler** [comment] 2016-07-02 23:02
The reason that this works when adding it to the `Dockerfile` as opposed to providing it to the `run` command is because there is a shell process in between:

    docker run -it --rm ubuntu:14.04 login -f root
    apt-get install psmisc && pstree

Outputs this:

    login---bash---pstree

With `Dockerfile` command section:

    docker run -ti --rm $((echo FROM ubuntu:14.04; echo CMD login -f root) | docker build -q -)
    apt-get install psmisc && pstree

Outputs this:

    sh---login---bash---pstree

The `sh` process sets up a lot of environment variables that `login` needs.

**Comment by cpuguy83** [comment] 2016-08-12 20:23
Really strange issue...

This reproduces the issue:
```Dockerfile
FROM ubuntu
ENTRYPOINT ["/bin/bash", "-c", "login -f root"]
```

This does not:
```Dockerfile
FROM ubuntu
ENTRYPOINT ["/bin/sh", "-c", "login -f root"]
```

This also reproduces the issue:
```Dockerfile
FROM ubuntu
ENTRYPOINT ["login", "-f", "root"]
```

This also reproduces the issue:
```Dockerfile
FROM ubuntu
ENTRYPOINT ["/bin/sh", "-c", "exec login -f root"]
```

What this really tells me is `login` wants to be wrapped in a shell... why it doesn't like bash I don't know... maybe `/bin/bash -c` does an exec but `/bin/sh -c` does not?

**Comment by vdemeester** [comment] 2018-02-14 14:37
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉 

PS: I couldn't reproduce with your dockerfiles @cpuguy83 😛

**Closed by vdemeester** 2018-02-14 14:37 UTC
Labels: area/cli, exp/expert, kind/bug
