### ISSUE TITLE
How to change docker's *default* container naming and host alias?

### ISSUE THREAD

**Issue by leonsoft** [moby/moby#34400] opened 2017-08-04 00:50 UTC
**Description**
Everytime docker generates a random container name and host alias (a hash) if you do not designate them, which are long and do not make much sense to me, difficult to remember and type.

**Describe the results you expected:**
I hope both container names and host alias are h1, h2... by default (**without** --name or -h).   

**Is it possible (how to) configure that?**

**Comment by thaJeztah** [comment] 2017-08-04 00:54
no you cannot change the auto-generated names; if you want to give meaning to your container names, it's best to name them yourself. 

naming containers (when connected to a custom network) also enables service discovery (i.e., other containers in the same network can connect to the container by _name_)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-08-04 00:54 UTC

**Comment by leonsoft** [comment] 2017-08-04 01:51
Can this be an enhancement request?
