### ISSUE TITLE
Restart policy "always" doesn't seem to work

### ISSUE THREAD

**Issue by jonso4** [moby/moby#33306] opened 2017-05-19 17:22 UTC
**Description**

On both Linux and Windows, creating a container with "--restart=always" doesn't seem to properly make the container restart. If I manually "docker kill" or "docker stop" the container, it doesn't restart. Likewise, if container start times out (as it sometimes does on Windows), the container is created, but won't restart. I have verified that "docker inspect" shows the correct restart policy.

**Steps to reproduce the issue:**
1. docker run -d --restart=always <my_image> <my_long_running_command>
2. docker kill <container_id>

**Describe the results you received:**
The container is created, but not started. The container's restart count is 0.

**Describe the results you expected:**
The container should be restarted, or actively trying to restart.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1188.amd64fre.rs1_release_sec.170407-2025)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 48
Total Memory: 127.9 GiB
Name: 
ID: 
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2017-05-19 20:01
Hello, thanks for reporting!

This is working as expected.
Since you are taking manual intervention using the normal docker API's the restart policy is disabled until the next time the container is started.
If you just want it to restart there is `docker restart`, or you could call `kill` on the process.

Closing as this is working as designed.
Thanks again!

**Closed by cpuguy83** 2017-05-19 20:01 UTC
Labels: platform/windows, version/17.03

**Comment by jonso4** [comment] 2017-05-22 16:05
I mentioned in the original comment that when the Windows container seems to fail to start due to a system timeout, I see the same behavior. Is this also by design?

**Comment by cpuguy83** [comment] 2017-05-22 16:06
@jonso4 Yes. If there is some issue in the actual startup process restarts are not enabled.
