### ISSUE TITLE
which linux release can compile lvm2(static library: libdevmapper.a), centos 7 compile lvm2(./configure --enable-static_link) failed

### ISSUE THREAD

**Issue by y123456yz** [moby/moby#34865] opened 2017-09-15 12:32 UTC
#./configure --enable-static_link
#make device-mapper
make[1]: Entering directory `/root/yyz/docker/src/docker/LVM2.2.02.171/tools'
gcc -c -I. -I../include -I../tools -DHAVE_CONFIG_H  -Wall -Wcast-align -Wfloat-equal -Wformat-security -Winline -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wpointer-arith -Wredundant-decls -Wshadow -Wundef -Wwrite-strings -Wclobbered -Wempty-body -Wignored-qualifiers -Wlogical-op -Wtype-limits -Wsync-nand -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wstrict-prototypes -Wuninitialized -Wjump-misses-init -Wmissing-parameter-type -Wold-style-declaration -Woverride-init -O2  -fPIC   dmsetup.c -o dmsetup.o
gcc -O2  -fPIC -O2  -L../libdm -L../lib -L../libdaemon/client  -L../libdm \
      -o dmsetup dmsetup.o -ldevmapper -lrt 
gcc -O2  -fPIC -O2  -L../libdm -L../lib -L../libdaemon/client -static -L../libdm/ioctl \
      -o dmsetup.static dmsetup.o -ldevmapper -lm -lpthread -lselinux -lsepol   -lrt 
/bin/ld: cannot find -lselinux
/bin/ld: cannot find -lsepol
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libpthread.a(libpthread.o): In function `sem_open':
(.text+0x6823): warning: the use of `mktemp' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
make[1]: *** [dmsetup.static] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/root/yyz/docker/src/docker/LVM2.2.02.171/tools'
make: *** [tools.device-mapper] Error 2

# yum list | grep libselinux
libselinux.x86_64                       2.5-6.el7                      @base    
libselinux-devel.x86_64                 2.5-6.el7                      @base    
libselinux-python.x86_64                2.5-6.el7                      @base    
libselinux-utils.x86_64                 2.5-6.el7                      @base    
libselinux.i686                         2.5-6.el7                      base     
libselinux-devel.i686                   2.5-6.el7                      base     
libselinux-ruby.x86_64                  2.5-6.el7                      base     
libselinux-static.i686                  2.5-6.el7                      base     
libselinux-static.x86_64                2.5-6.el7                      base   

# uname -a
Linux ob-slave-465.gz01 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

if I want to compile lvm2(libdevmapper.a), which linux release can do?
thanks.

**Comment by thaJeztah** [comment] 2017-09-15 12:47
I don't think these can be statically compiled, but @kolyshkin was looking at this recently, perhaps he can give more information 

Given that this is not a bug, and LVM is not maintained in this repository, I'll close this issue, bug feel free to continue the conversation

**Closed by thaJeztah** 2017-09-15 12:47 UTC

**Comment by y123456yz** [comment] 2017-09-15 13:09
@thaJeztah 
thanks for you answer.

when I compile docker code, it failed, as following:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bundles/17.05.0-ce already exists. Removing.

---> Making bundle: binary (in bundles/17.05.0-ce/binary)
Building: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
Created binary: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
Building: bundles/17.05.0-ce/binary-daemon/dockerd-17.05.0-ce  
# github.com/docker/docker/pkg/devicemapper  
could not determine kind of name for C.dm_task_deferred_remove  


root@5a8aa24b7ee0:/go/src/github.com/docker/docker# find / -name libdevmapper.*
/usr/lib/libdevmapper.so

root@5a8aa24b7ee0:/go/src/github.com/docker/docker# strings /usr/lib/libdevmapper.so | grep dm_task_deferred_remove  

dm_task_deferred_remove   exist in my /lib, why compile failed, thanks.
if I need a static library(libdevmapper.a)?

**Comment by y123456yz** [comment] 2017-09-15 13:13
@thaJeztah

if need libdevmapper.a, but it also failed when Icompile lvm2(./configure --enable-static_link) .
how can I resolve this problem.

thanks.

**Comment by thaJeztah** [comment] 2017-09-15 13:21
It looks like you're using a different version of LVM than is used for 17.05? https://github.com/moby/moby/blob/v17.05.0-ce/Dockerfile#L84-L98, also for current versions of Docker you may want to look in this repository to build 17.06 or up; https://github.com/docker/docker-ce/tree/17.06

Are you building inside a container or on the host? What distro and hardware are you on?

**Comment by thaJeztah** [comment] 2017-09-15 13:22
Note that devicemapper won't work for static builds; when building a static binary, those parts are only used so that the build completes, but devicemapper likely won't work with a static binary

**Comment by y123456yz** [comment] 2017-09-15 13:38
@thaJeztah 
I do as you give url.
but compile LVM2.2.02.103 failed.

I do as following:
mkdir -p /usr/local/lvm2
curl -fsSL "https://mirrors.kernel.org/sourceware/lvm2/LVM2.2.02.103.tgz" | tar -xzC /usr/local/lvm2 --strip-components=1
 cd /usr/local/lvm2
./configure --enable-static_link

curity -Wredundant-decls -Wpointer-arith  -fPIC  -O2 dmsetup.c -o dmsetup.o
gcc  -fPIC  -O2  -O2 -L../libdm -L../lib -L../libdaemon/client -L../libdm \
      -o dmsetup dmsetup.o -ldevmapper  
gcc  -fPIC  -O2  -O2 -L../libdm -L../lib -L../libdaemon/client -static -L../libdm/ioctl \
      -o dmsetup.static dmsetup.o -ldevmapper -lselinux -lsepol   
/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lsepol
collect2: error: ld returned 1 exit status
make[1]: *** [dmsetup.static] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/local/lvm2/tools'
make: *** [tools.device-mapper] Error 2

**Comment by y123456yz** [comment] 2017-09-15 13:40
SO, I want to kown which linux release can compile lvm2.

**Comment by y123456yz** [comment] 2017-09-15 13:45
I use the newest lvm2 version to compile, but also failed

**Comment by thaJeztah** [comment] 2017-09-15 13:47
The Dockerfile in the repository uses Debian Jessie

**Comment by thaJeztah** [comment] 2017-09-15 13:49
But if you want to build an RPM and a non-static build, look at https://github.com/docker/docker-ce/blob/17.06/components/packaging/rpm/centos-7/Dockerfile.x86_64, and the readme in the packaging repository; https://github.com/docker/docker-ce-packaging/blob/master/rpm/README.md

**Comment by kolyshkin** [comment] 2017-09-15 17:47
LVM2 can't really be compiled statically because one of it's dependencies, libudev (which is part of systemd sources now), can't be compiled statically. Now, there's a fork of libudev called libeudev and it can be compiled statically -- although the resulting binary didn't work well for me so I gave up on libeudev and the whole "static dockerd binary with device mapper" thing.

In general, complicated static libraries (and binaries) should be avoided if possible, as modern systems are designed with shared libraries in mind. Is there any specific reason you want a static binary?

**Comment by y123456yz** [comment] 2017-09-16 03:15
@kolyshkin  @thaJeztah 

maybe we need static libdevmapper library(libdevmapper.a) ,if we compile docker code .

when I compile docker code, it failed, as following:
root@95998b956698:/go/src/github.com/docker/docker# hack/make.sh binary  

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# GITCOMMIT = 89658be-unsupported
# The version you are building is listed as unsupported because
# there are some files in the git repository that are in an uncommitted state.
# Commit these changes, or add to .gitignore to remove the -unsupported from the version.
# Here is the current list:
 M api/common.go
 M api/server/httputils/httputils.go
 M api/server/router/container/container.go
 M api/server/router/container/container_routes.go
..............
..............
---> Making bundle: binary (in bundles/17.05.0-ce/binary)
Building: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
Created binary: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
Building: bundles/17.05.0-ce/binary-daemon/dockerd-17.05.0-ce
github.com/docker/docker/pkg/devicemapper
could not determine kind of name for C.dm_task_deferred_remove



root@5a8aa24b7ee0:/go/src/github.com/docker/docker# find / -name libdevmapper.*
/usr/lib/libdevmapper.so

root@5a8aa24b7ee0:/go/src/github.com/docker/docker# strings /usr/lib/libdevmapper.so | grep dm_task_deferred_remove

dm_task_deferred_remove exist in my libdevmapper.so, but compile failed

so, Maybe we need static library(libdevmapper.a) ,when we compile docker code for getting docker bin(docked   docker-containerd  docker-containerd-ctr ....)

**Comment by y123456yz** [comment] 2017-09-16 03:32
@kolyshkin @thaJeztah
I want to use the docker's function of devicemapper Deferred Removal and Deferred Deletion. and I need to change the docker' code to compile the changed code.
so I must upgrade lVM2.

but I can not compile the docker's code , compile failed everytime.

**Comment by y123456yz** [comment] 2017-09-16 04:10
when I compile lvm2 static library as following:
root@ob-xxx-xxx.gz01:~./configure --enable-static_link   --disable-selinux 
................
[ -s command.d ] || rm -f command.d
make[1]: Leaving directory `/root/yyz/docker/src/docker/LVM2.2.02.171/tools'
make[1]: Entering directory `/root/yyz/docker/src/docker/LVM2.2.02.171/tools'
gcc -c -I. -I../include -I../tools -DHAVE_CONFIG_H  -Wall -Wcast-align -Wfloat-equal -Wformat-security -Winline -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wpointer-arith -Wredundant-decls -Wshadow -Wundef -Wwrite-strings -Wclobbered -Wempty-body -Wignored-qualifiers -Wlogical-op -Wtype-limits -Wsync-nand -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wstrict-prototypes -Wuninitialized -Wjump-misses-init -Wmissing-parameter-type -Wold-style-declaration -Woverride-init -O2  -fPIC   dmsetup.c -o dmsetup.o
gcc -O2  -fPIC -O2  -L../libdm -L../lib -L../libdaemon/client  -L../libdm \
      -o dmsetup dmsetup.o -ldevmapper -lrt 
gcc -O2  -fPIC -O2  -L../libdm -L../lib -L../libdaemon/client -static -L../libdm/ioctl \
      -o dmsetup.static dmsetup.o -ldevmapper -lm -lpthread    -lrt 
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libpthread.a(libpthread.o): In function `sem_open':
(.text+0x6823): warning: the use of `mktemp' is dangerous, better use `mkstemp'
make[1]: Leaving directory `/root/yyz/docker/src/docker/LVM2.2.02.171/tools'
root@ob-slave-xxx.gz01:~/xxx/docker/src/docker/LVM2.2.02.171$ 
root@ob-slave-xxx.gz01:~/xxx/docker/src/docker/LVM2.2.02.171$ 
root@ob-slave-xxx.gz01:~/xxx/docker/src/docker/LVM2.2.02.171$ find ./ -name libdevmapper.so
./libdevmapper.so
./libdm/libdevmapper.so
./libdm/ioctl/libdevmapper.so
root@ob-slave-xxx.gz01:~/yyz/docker/src/docker/LVM2.2.02.171$ find ./ -name libdevmapper.a
./libdm/ioctl/libdevmapper.a


after replace the old libdevmapper.so and the old libdevmapper.a， I compile docker code again, as following:
root@989cce215d19:/go/src/github.com/docker/docker# hack/make.sh binary  
.............
bundles/17.05.0-ce already exists. Removing.

---> Making bundle: binary (in bundles/17.05.0-ce/binary)
Building: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
Created binary: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
Building: bundles/17.05.0-ce/binary-daemon/dockerd-17.05.0-ce
# github.com/docker/docker/cmd/dockerd
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-453347312/000011.o: In function `mygetgrouplist':
/usr/local/go/src/os/user/getgrouplist_unix.go:15: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-453347312/000011.o: In function `mygetgrgid_r':
/usr/local/go/src/os/user/lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-453347312/000011.o: In function `mygetgrnam_r':
/usr/local/go/src/os/user/lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-453347312/000011.o: In function `mygetpwnam_r':
/usr/local/go/src/os/user/lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-453347312/000011.o: In function `mygetpwuid_r':
/usr/local/go/src/os/user/lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
./libdevmapper.a(libdm-common.o): In function `_is_selinux_enabled':
libdm-common.c:(.text+0x577): undefined reference to `is_selinux_enabled'
./libdevmapper.a(libdm-common.o): In function `_selabel_lookup':
libdm-common.c:(.text+0x5b1): undefined reference to `selabel_lookup'
libdm-common.c:(.text+0x619): undefined reference to `selabel_open'
./libdevmapper.a(libdm-common.o): In function `dm_prepare_selinux_context':
libdm-common.c:(.text+0x251a): undefined reference to `setfscreatecon'
libdm-common.c:(.text+0x252d): undefined reference to `freecon'
libdm-common.c:(.text+0x25f2): undefined reference to `freecon'
./libdevmapper.a(libdm-common.o): In function `dm_set_selinux_context':
libdm-common.c:(.text+0x26a8): undefined reference to `lsetfilecon'
libdm-common.c:(.text+0x26bb): undefined reference to `freecon'
libdm-common.c:(.text+0x2773): undefined reference to `freecon'
./libdevmapper.a(libdm-common.o): In function `selinux_release':
libdm-common.c:(.text+0x2791): undefined reference to `selabel_close'
./libdevmapper.a(libdm-string.o): In function `dm_size_to_string':
libdm-string.c:(.text+0x11d0): undefined reference to `nearbyint'
libdm-string.c:(.text+0x11e5): undefined reference to `floor'
collect2: error: ld returned 1 exit status


I compiled docker failed again. from the wrong info ,we can see that we need libdevmapper.a(static library) when we compile docker.


now, I  do not know how to compile docker code for the newest LVM2.
I need to use the Deferred Removal and Deferred Deletion of LVM2.

**Comment by linuxdaxia** [comment] 2017-09-16 04:18
+1

I have the same problem.

**Comment by y123456yz** [comment] 2017-09-16 05:33
/*
#cgo LDFLAGS: -L. -ldevmapper
#include <libdevmapper.h>
*/
import "C"

const LibraryDeferredRemovalSupport = true 

I want to know that the following need static library(libdevmapper.a) or  dynamic library (libdevmapper.so)?
#cgo LDFLAGS: -L. -ldevmapper

**Comment by y123456yz** [comment] 2017-10-18 03:57
@thaJeztah

can you open this issue.

**Comment by kolyshkin** [comment] 2017-10-18 04:25
There is no way to have a static build of dockerd with devmapper graph driver. Use a dynamic binary.

**Comment by y123456yz** [comment] 2017-10-18 04:42
when use dynamic binary, docker compile failed!

**Comment by kolyshkin** [comment] 2017-10-19 00:05
> when use dynamic binary, docker compile failed!

I don't see any attempt to compile a dynamic binary above. `hack/make.sh binary` compiles a static binary, you need to use `hack/make.sh dynbinary`.

> could not determine kind of name for C.dm_task_deferred_remove

Make sure you don't have two different versions of libdevmapper.h on your system -- it seems to be the cause.

**Comment by y123456yz** [comment] 2017-10-31 04:03
@kolyshkin  @thaJeztah 
when I compile docker by "hack/make.sh dynbinary",  it compile success, but the some bin file can not find, as following:

root@d094b8365f71:/go/src/github.com/docker/docker/bundles/17.05.0-ce# ls dynbinary
root@d094b8365f71:/go/src/github.com/docker/docker/bundles/17.05.0-ce# ls dynbinary-client/
docker  docker-17.05.0-ce  docker-17.05.0-ce.md5  docker-17.05.0-ce.sha256
root@d094b8365f71:/go/src/github.com/docker/docker/bundles/17.05.0-ce# ls dynbinary-   
dynbinary-client/ dynbinary-daemon/ 
root@d094b8365f71:/go/src/github.com/docker/docker/bundles/17.05.0-ce# ls dynbinary-daemon/
dockerd  dockerd-17.05.0-ce  dockerd-17.05.0-ce.md5  dockerd-17.05.0-ce.sha256
root@d094b8365f71:/go/src/github.com/docker/docker/bundles/17.05.0-ce# 
root@d094b8365f71:/go/src/github.com/docker/docker/bundles/17.05.0-ce# 


I can not find “docker-containerd  docker-containerd-ctr   docker-containerd-shim  docker-init             docker-proxy  docker-runc ”

thanks again.

**Comment by y123456yz** [comment] 2017-12-20 09:31
@kolyshkin 
At last, I resolve this problem by dynbinary-compile，thanks again.
