### ISSUE TITLE
after systemd-journal restart , dockerd log lost

### ISSUE THREAD

**Issue by chenk008** [moby/moby#39272] opened 2019-05-26 15:13 UTC
After systemd-journal restart , dockerd log lost.I cann't see any dockerd log

https://github.com/moby/moby/issues/19728
https://github.com/moby/moby/pull/22460  has ignore SIGPIPE.

Is it Related?

**Comment by thaJeztah** [comment] 2019-05-27 05:29
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed** 2019-05-27 05:29 UTC

**Comment by thaJeztah** [comment] 2019-05-27 05:31
If you do think there's a bug; please provide the information and steps to reproduce as requested in the issue template

**Comment by chenk008** [comment] 2019-05-27 10:12
The systemd-journald was killed for systemd-watchdog.And it started after a while.
I cann't see any more dockerd's log.I think it blame systemd-journald losing the stdout/stderr socket.

systemd version:219

Close it.
Thank  you.
