### ISSUE TITLE
Consider not to delete named volumes by default when running system prune

### ISSUE THREAD

**Issue by kuhnroyal** [moby/moby#31757] opened 2017-03-11 13:02 UTC
**Description**
Consider not deleting manually named volumes by default when running `docker system prune`.
I now there is potentially a label filter coming soon but I am not sure that is enough.
A lot of people are using external named volumes with docker-compose and deleting those by default seems very risky to me.

**Describe the results you expected:**
By default only delete images without a manually given name.
Add a flag to delete all volumes, just like there is for images.

**Output of `docker version`:**

```
Docker version 17.03.0-ce, build 60ccb22
docker-compose version 1.11.2, build dfed245
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 78
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 159
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-74-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.737 GiB
Name: orchestra
ID: L6ZS:PQC7:KLDK:TJZP:3LIL:K3JF:B3TZ:7WJO:VNFK:REUC:PXVT:X7FE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-03-13 15:23
Distinguishing based on "named" or "not named" is a bit difficult. In the current implementation, volumes always have a _name_ (i.e., volumes don't have a separate _id_), only the name can be randomly generated, or manually provided. I do see where you're coming from, but we need to think of a solution to allow "locking" volumes to prevent them from being removed.

/cc'ing @cpuguy83 for more thoughts on this.

**Comment by cpuguy83** [comment] 2017-03-13 16:28
We could definitely handle this for new volumes, not sure how we could do it for older ones.

**Comment by cpuguy83** [comment] 2017-03-13 16:29
We have discussed before about applying some kind of retention policy rather than relying on something being explicitly named or not... but then an error in the retention policy could lead to some bad situations as well.

**Comment by EugenMayer** [comment] 2017-07-28 09:00
this is so much needed. We are currently implementing a shell alias to override volume prune in production to ensure named volumes are not deleted.

This whole thing should really need to be though through, since deleting named volumes could be, highly possible, a dataloss.

Really would love to see this moving on and be part of the discussion. I am also happy to let volume prune /system prune be like it is and add a new parameter, --safe, which does ensure that nothing stupid happens on productions systems. I just would, long term, expect this to be the default an probably make it possible to make it a default using system settings

**Comment by thaJeztah** [comment] 2017-07-28 09:09
This is actually implemented already, and will be included in docker 17.06.1 and 17.07; `docker system prune` now keeps volumes, unless a `--volumes` flag is passed.

If you're not on that version yet, I suggest running `docker container prune`, `docker image prune` etc separately.

I'll close this issue because this should be resolved, but feel free to continue the conversation

**Comment by KarolBuchta** [comment] 2017-07-28 09:12
Great

**Comment by EugenMayer** [comment] 2017-07-28 09:15
@thaJeztah that does not actually do what i really was talking about and i do not think this issue should be closed.

It is very common, that dangling volumes will happen during container upgrades, since anon volumes will stay, and will be recreated by design.

so there is a strong need to clean up exactly those, since your drive will run full.

So having `docker volume prune` in a cleanup way is very important BUT if you put that into cron, and then, out of any reason, you have a stack outage during that happening, or you are running a stack-upgrade, you delete named volumes with live data.

So instead of just leaving out volumes in system prune, rather think about how we can prune only anon volumes instead as a safe flag, for system prune and volume prune

**Comment by thaJeztah** [comment] 2017-07-28 09:46
Oh you're right - this was about the anonymous volumes

**Comment by chxzqw** [comment] 2018-03-21 23:26
Hi any update on this topic please ?

Is it possible to put on some certain labels on the volume to prevent deletion from `docker volume prune` ?

**Comment by jcraigk** [comment] 2018-07-11 04:32
In case this helps anyone, this is what I use to prune unnamed volumes.  It removes all except those with at least one underscore (_) in its name (since anonymously named volumes do not include underscores and named ones always do in my experience).

```bash
docker volume rm $(docker volume ls -q | awk '!/_/' | tr '\n' ' ')
```

**Comment by cpuguy83** [comment] 2018-07-11 04:40
You can put a label on a volume and set that as a default filter in your config.json for the Docker client.

**Comment by mesuutt** [comment] 2019-07-04 22:09
I filtered unnamed containers with volume name length, because some volume names not has underscore:

 `docker volume rm $(docker volume ls -q | awk -F, 'length($0) == 64 { print }')`

**Comment by MythicManiac** [comment] 2020-10-03 16:51
Just want to drop by and say @mesuutt's solution is still the best one I've come across so far, thanks for posting it.

I also find it a bit weird there's no difference between manually created named volumes and automatically created anonymous volumes, because more often than not you want to get rid of just the anonymous volumes.

**Comment by cpuguy83** [comment] 2020-10-03 18:58
I agree, it's a terrible situation.
If you remove a container with "-v" it will remove the anon volumes attached to it.
It may be worthwhile to just always remove them when the container is removed.

This architecture has improved significantly since the original issue.

I feel like volume prune is pretty much a terrible idea as a whole except that we have these anonymous volumes... if we just stop keeping those around there is no reason to prune volumes.

**Comment by juan-ferrer-toribio** [comment] 2021-10-06 07:18
A more precise command:
`
docker volume rm $(docker volume ls -q -f driver=local -f dangling=true | awk '$0 ~ /^[a-f0-9]*$/ && length($0) == 64 { print }')
`

**Comment by cristik** [comment] 2022-01-25 18:10
Just building up onto @juan-ferrer-toribio's command, we can move the length check to the regex itself, to get a little bit more concise command. Also we can `xargs` instead of subshell-ing:
```bash
docker volume ls -q -f driver=local -f dangling=true | awk '$0 ~ /^[0-9a-f]{64}$/ { print }' | xargs docker volume rm
```

**Comment by thaJeztah** [comment] 2023-09-25 14:58
- This was implemented in https://github.com/moby/moby/pull/44216

**Closed by thaJeztah** 2023-09-25 14:58 UTC
Labels: kind/enhancement, area/volumes
