### ISSUE TITLE
Docker import fails to properly identify image architecture

### ISSUE THREAD

**Issue by HouzuoGuo** [moby/moby#38798] opened 2019-02-26 06:47 UTC
**Description**

The image architecture information is lost through a pair of `docker save` and `docker import` command. In addition to the incorrect architecture, `docker import` does not offer a way to alter image architecture, resulting in a useless imported image.

In the repro-steps, I'll use my ARMv7 32-bit image `hzgl/diagnosis-toolbox-armv7` as example.

**Steps to reproduce the issue:**
1. docker pull hzgl/diagnosis-toolbox-armv7
2. docker save -o test hzgl/diagnosis-toolbox-armv7
3. docker import test
4. docker image inspect "imported image ID"

**Describe the results you received:**

Observe that the image architecture came up as "amd64" instead of "arm" in the inspection result. Subsequently, due to the incorrect architecture record, the image fails to launch.

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.1
 Git commit:        e68fc7a
 Built:             Fri Jan 25 14:33:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:49:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 51
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: zrt980y3nub1py9fixw6ylin1
 Is Manager: true
 ClusterID: ikdem9m3s8d7267va734rl3rl
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-1011-azure
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.788GiB
Name: houzuo-guo-ability-edge-workspace
ID: D4IW:IAYU:I4Y2:P2H5:DOXT:LXUY:PT7O:XJBB:NF2N:JULF:AEMP:DQOH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: hzgl
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

X86-64 Ubuntu 18.04 virtual machine running on Hyper-V.

**Comment by thaJeztah** [comment] 2019-03-01 23:22
Thanks for reporting; this is because you're using `docker import` (which is the counterpart of `docker export`). 

`docker export` saves the filesystem layer of a container, but does not save any other information, and `docker import` is to load a filesystem and create a new image from that (which also can be used to create a new base-image).

`docker save` / `docker load` on the other hand, save (and load) the actual docker image, including its configuration.

I verified that with those commands, the information is preserved:

```bash
docker image pull hzgl/diagnosis-toolbox-armv7    

# (or docker save, which is an alias for docker image save)
docker image save -o test hzgl/diagnosis-toolbox-armv7   

# remove the original image
docker image rm hzgl/diagnosis-toolbox-armv7    

# load the saved image
docker image load -i test

8173237b52d4: Loading layer [==================================================>]  71.23MB/71.23MB
f9ea0020b31c: Loading layer [==================================================>]  15.87kB/15.87kB
318f75c7806d: Loading layer [==================================================>]  11.26kB/11.26kB
76c291cb7a07: Loading layer [==================================================>]  3.584kB/3.584kB
ed617d97877b: Loading layer [==================================================>]  3.547MB/3.547MB
2197571dd4e6: Loading layer [==================================================>]  23.77MB/23.77MB
e07dd4921946: Loading layer [==================================================>]  527.5MB/527.5MB
e2b079c6e292: Loading layer [==================================================>]  3.072kB/3.072kB
Loaded image: hzgl/diagnosis-toolbox-armv7:latest
```

Verify the OS and architecture;

```
docker image inspect --format '{{.Os}}/{{.Architecture}}' hzgl/diagnosis-toolbox-armv7
linux/arm
```



I'm closing this issue, because this is not a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2019-03-01 23:22 UTC
Labels: area/distribution

**Comment by HouzuoGuo** [comment] 2019-03-02 07:12
Thanks for the hint
