### ISSUE TITLE
 Delete container conflicts with PHP FPM process 

### ISSUE THREAD

**Issue by jschunlei** [moby/moby#40659] opened 2020-03-10 08:30 UTC
**Description**

**Steps to reproduce the issue:**
1. `docker stop iair-web && docker rm -f -v iair-web`

there are some linux,  Only the linux with native overlay diff: false has problems

**Describe the results you received:**

```
Error response from daemon: Driver overlay2 failed to remove root filesystem 8d2bce88ecc9120f1f983e20f7e23704a90426b9202eac0bc7edeafd40245f24: remove /home/docker/overlay2/89f45fe045dbbd6773cbb2ff724514b5baeb63d7f0956d6936f3a1785a2f87ff/merged: device or resource busy
```

Every time it's a PHP FPM process conflict

```
/proc/$php-fpm_pid/mountinfo contain the remove container information
```

```
[root@SZV1000346835 ~]# cat /proc/22906/mountinfo
143 140 202:1 / / rw,relatime shared:125 master:1 - ext3 /dev/xvda1 rw,data=ordered
147 143 0:5 / /dev rw,nosuid shared:127 master:2 - devtmpfs devtmpfs rw,size=3979696k,nr_inodes=994924,mode=755
148 147 0:17 / /dev/shm rw,nosuid,nodev shared:128 master:3 - tmpfs tmpfs rw,size=3776732k,nr_inodes=944183
151 147 0:11 / /dev/pts rw,nosuid,noexec,relatime shared:129 master:4 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
154 147 0:13 / /dev/mqueue rw,relatime shared:130 master:24 - mqueue mqueue rw
155 147 0:33 / /dev/hugepages rw,relatime shared:135 master:25 - hugetlbfs hugetlbfs rw
156 143 0:3 / /proc rw,nosuid,nodev,noexec,relatime shared:138 master:5 - proc proc rw
158 156 0:35 / /proc/fs/nfsd rw,relatime shared:139 master:27 - nfsd nfsd rw
159 156 0:14 / /proc/sys/fs/binfmt_misc rw,relatime shared:140 master:22 - autofs systemd-1 rw,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct
160 143 0:16 / /sys rw,nosuid,nodev,noexec,relatime shared:143 master:6 - sysfs sysfs rw
161 160 0:15 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:146 master:7 - securityfs securityfs rw
163 160 0:19 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:149 master:8 - tmpfs tmpfs ro,size=3776732k,nr_inodes=944183,mode=755
164 163 0:20 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:151 master:9 - cgroup cgroup rw,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
165 163 0:22 / /sys/fs/cgroup/net_cls rw,nosuid,nodev,noexec,relatime shared:152 master:10 - cgroup cgroup rw,net_cls
166 163 0:23 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:153 master:11 - cgroup cgroup rw,blkio
168 163 0:24 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:155 master:12 - cgroup cgroup rw,hugetlb
169 163 0:25 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:156 master:13 - cgroup cgroup rw,cpuacct,cpu
171 163 0:26 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:157 master:14 - cgroup cgroup rw,cpuset
173 163 0:27 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:158 master:15 - cgroup cgroup rw,perf_event
174 163 0:28 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:159 master:16 - cgroup cgroup rw,devices
176 163 0:29 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:160 master:17 - cgroup cgroup rw,memory
177 163 0:30 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:161 master:18 - cgroup cgroup rw,freezer
178 160 0:21 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:162 master:19 - pstore pstore rw
179 160 0:31 / /sys/kernel/config rw,relatime shared:163 master:20 - configfs configfs rw
180 160 0:7 / /sys/kernel/debug rw,relatime shared:164 master:23 - debugfs debugfs rw
181 160 0:44 / /sys/fs/fuse/connections rw,relatime shared:165 master:189 - fusectl fusectl rw
183 143 0:18 / /run rw,nosuid,nodev shared:166 master:21 - tmpfs tmpfs rw,size=3776732k,nr_inodes=944183,mode=755
184 183 0:36 / /run/user/0 rw,nosuid,nodev,relatime shared:167 master:119 - tmpfs tmpfs rw,size=747156k,mode=700
186 183 0:37 / /run/user/989 rw,nosuid,nodev,relatime shared:168 master:123 - tmpfs tmpfs rw,size=747156k,mode=700,uid=989,gid=984
187 183 0:39 / /run/user/1005 rw,nosuid,nodev,relatime shared:169 master:131 - tmpfs tmpfs rw,size=747156k,mode=700,uid=1005,gid=1100
188 183 0:43 / /run/user/1020 rw,nosuid,nodev,relatime shared:170 master:147 - tmpfs tmpfs rw,size=747156k,mode=700,uid=1020,gid=1100
189 183 0:75 / /run/user/1000 rw,nosuid,nodev,relatime shared:171 master:196 - tmpfs tmpfs rw,size=747156k,mode=700,uid=1000,gid=100
190 183 0:109 / /run/user/1021 rw,nosuid,nodev,relatime shared:172 master:210 - tmpfs tmpfs rw,size=747156k,mode=700,uid=1021,gid=1100
191 183 0:3 / /run/docker/netns/b5ec5e41004c rw,nosuid,nodev,noexec,relatime shared:173 master:5 - proc proc rw
192 183 0:3 / /run/docker/netns/caa19a1d260f rw,nosuid,nodev,noexec,relatime shared:174 master:5 - proc proc rw
193 183 0:3 / /run/docker/netns/27f4fd5cb277 rw,nosuid,nodev,noexec,relatime shared:175 master:5 - proc proc rw
195 183 0:3 / /run/docker/netns/824676247e43 rw,nosuid,nodev,noexec,relatime shared:176 master:5 - proc proc rw
196 183 0:3 / /run/docker/netns/e9c2f9e75d26 rw,nosuid,nodev,noexec,relatime shared:177 master:5 - proc proc rw
197 183 0:3 / /run/docker/netns/8cd1a602b988 rw,nosuid,nodev,noexec,relatime shared:178 master:5 - proc proc rw
198 143 0:34 / /var/lib/nfs/rpc_pipefs rw,relatime shared:179 master:26 - rpc_pipefs sunrpc rw
199 143 253:0 / /home rw,relatime shared:180 master:28 - ext4 /dev/mapper/vghome-lvhome rw,data=ordered
200 199 0:38 / /home/filedist/itinerary rw,relatime shared:181 master:96 - nfs 10.162.19.204:/data/filedist/itinerary rw,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.162.19.204,mountvers=3,mountport=20048,mountproto=udp,local_lock=all,addr=10.162.19.204
203 199 253:0 /docker/containers /home/docker/containers rw,relatime shared:182 - ext4 /dev/mapper/vghome-lvhome rw,data=ordered
204 203 0:54 / /home/docker/containers/ec9bc4590390513f35d49c40e0f92c27239d86c1cea1dd2a1299520464bdc70c/shm rw,nosuid,nodev,noexec,relatime shared:183 - tmpfs shm rw,size=65536k
207 203 0:111 / /home/docker/containers/476ad4df70fcae52430ccab786b35464c2a35158d850384636706902cb98f005/shm rw,nosuid,nodev,noexec,relatime shared:184 - tmpfs shm rw,size=65536k
214 203 0:41 / /home/docker/containers/f5cdd9a37491e31ffb18634be24e6e4c9882f84ca8ea654b90a37c5f8d24c425/shm rw,nosuid,nodev,noexec,relatime shared:187 - tmpfs shm rw,size=65536k
219 203 0:65 / /home/docker/containers/cace987013c27690eda693649145309bd0d034f6292b7549ce526c0392f4240e/shm rw,nosuid,nodev,noexec,relatime shared:195 - tmpfs shm rw,size=65536k
220 203 0:77 / /home/docker/containers/7313a8b9930aab274088dbf03395687951aff49f2cd4ef5a20ea0d95de2e6f70/shm rw,nosuid,nodev,noexec,relatime shared:198 - tmpfs shm rw,size=65536k
221 203 0:89 / /home/docker/containers/840f19d4cb961277c5d9ca4b85961549fe3e8a7605cf521265f64492591b2066/shm rw,nosuid,nodev,noexec,relatime shared:202 - tmpfs shm rw,size=65536k
222 199 253:0 /docker/overlay2 /home/docker/overlay2 rw,relatime shared:206 - ext4 /dev/mapper/vghome-lvhome rw,data=ordered
225 222 0:53 / /home/docker/overlay2/b0da24ef8764d6f2833f680168f6b551d4469916242f67f628ce8f90734f4255/merged rw,relatime shared:207 - overlay overlay rw,lowerdir=/home/docker/overlay2/l/DLB4CREL5RZIJN7HHSOMJ4SHQO:/home/docker/overlay2/l/ZNDH2XBO4VANJACEXUT3LIOBLR:/home/docker/overlay2/l/YWF5YTAQN2M5UX33T65EL6EAO6:/home/docker/overlay2/l/TPXYOYPUZPC2RWWJYU54N246JH:/home/docker/overlay2/l/NW2DYGH2LJ3BRY2UYKODYQWADN:/home/docker/overlay2/l/5EXBMFWGAS7QIW6J6U4S6O2BWD:/home/docker/overlay2/l/MOMQNDHSXQOQIYX53WDSAO5T4Y:/home/docker/overlay2/l/74XKGREEALIPOKEAIQMCUL2Y6K:/home/docker/overlay2/l/TAQUO465J33EHXFX435LR2KFH5:/home/docker/overlay2/l/LRYMKZ4TO7MQKPPLHYLFSQGR6R:/home/docker/overlay2/l/TBK5FNLYXCOCJ6U3MTQ7RSU467:/home/docker/overlay2/l/A26CLT4UC7SUOWDP264FFPC6IV:/home/docker/overlay2/l/RETMHVDMOSOYKUISQJCOLBSJHG:/home/docker/overlay2/l/UQKCEIQ5LTIE2UL5BFOBJTWAYJ:/home/docker/overlay2/l/YCC7LCAJGPXQUCOKW7AEWOIHKF:/home/docker/overlay2/l/WV2PUQ5TG5OFNWOZXER7BYLUQL:/home/docker/overlay2/l/JNAFN7CIZJUMPLK3FFLEJTV5D4:/home/docker/overlay2/l/4SSXZDBJBGLLFFGCKPGAC7JBZ2:/home/docker/overlay2/l/YEUYLQSH3MUFPWD4LCPSLA633H,upperdir=/home/docker/overlay2/b0da24ef8764d6f2833f680168f6b551d4469916242f67f628ce8f90734f4255/diff,workdir=/home/docker/overlay2/b0da24ef8764d6f2833f680168f6b551d4469916242f67f628ce8f90734f4255/work
226 222 0:110 / /home/docker/overlay2/02f2a337e891e8ded3912cb5a70c758d6087031d68dc4e20d7e09414ca3850ee/merged rw,relatime shared:208 - overlay overlay rw,lowerdir=/home/docker/overlay2/l/TJG6FPDYBRX4YS3JB6URA7KGSV:/home/docker/overlay2/l/D3JT6P5AGK33UNGOQX4UIWTFRJ:/home/docker/overlay2/l/6MRJ5DBMBDXTSRINMZ3V5ZW5PU:/home/docker/overlay2/l/6ISWBYHEBMGH2CRLJISAHEJW55:/home/docker/overlay2/l/AX3GZ7L6OY7US7WXDOOFDBCT4Z:/home/docker/overlay2/l/MGDJ4FKLKQAECOPTMYSCKYRDP2:/home/docker/overlay2/l/Q3TDSFL6A4LKFKFXGYVIIZYCIN:/home/docker/overlay2/l/5U7PHY3XIIRVI2KSLPP3CSRFL3:/home/docker/overlay2/l/H3RR2BP6R6AF5VXGLLMPQWCVMX:/home/docker/overlay2/l/TB5WMCVCBY5TCDRZMIGAAHRKN4:/home/docker/overlay2/l/NQPPNHUIS4I3LRF4A47EHVTPQJ:/home/docker/overlay2/l/YEUYLQSH3MUFPWD4LCPSLA633H,upperdir=/home/docker/overlay2/02f2a337e891e8ded3912cb5a70c758d6087031d68dc4e20d7e09414ca3850ee/diff,workdir=/home/docker/overlay2/02f2a337e891e8ded3912cb5a70c758d6087031d68dc4e20d7e09414ca3850ee/work
229 222 0:40 / /home/docker/overlay2/0aa6182d89361d2bb9724b52f63accf18c22d859570478388fd6dce99cf1fc18/merged rw,relatime shared:209 - overlay overlay rw,lowerdir=/home/docker/overlay2/l/ADQAKGQNZAD376GDIMUS5Z5SJK:/home/docker/overlay2/l/TN4SENU4EHBBIUQQ67D64DKVXT:/home/docker/overlay2/l/K3KD2Y6P3OJXTFPRAWZTZXOP3H:/home/docker/overlay2/l/6ELQJGVUDBTG5NJ6F422ZTMHCE:/home/docker/overlay2/l/KIMIOVSN5JNHN5JU4V3AEMYBHY,upperdir=/home/docker/overlay2/0aa6182d89361d2bb9724b52f63accf18c22d859570478388fd6dce99cf1fc18/diff,workdir=/home/docker/overlay2/0aa6182d89361d2bb9724b52f63accf18c22d859570478388fd6dce99cf1fc18/work
232 222 0:64 / /home/docker/overlay2/81a94d5368576c73f3ad7fab317df2316d4ba03eda4d7ea9d7efcfd59d2462b2/merged rw,relatime shared:211 - overlay overlay rw,lowerdir=/home/docker/overlay2/l/LSYEKDDVZIGVOUEK356UD6YJUG:/home/docker/overlay2/l/7JQCQQNSMYBCQGKQTIRU67IER7:/home/docker/overlay2/l/PDLYFIIGE64SHFVLHZH2CRKQCT:/home/docker/overlay2/l/6ELQJGVUDBTG5NJ6F422ZTMHCE:/home/docker/overlay2/l/KIMIOVSN5JNHN5JU4V3AEMYBHY,upperdir=/home/docker/overlay2/81a94d5368576c73f3ad7fab317df2316d4ba03eda4d7ea9d7efcfd59d2462b2/diff,workdir=/home/docker/overlay2/81a94d5368576c73f3ad7fab317df2316d4ba03eda4d7ea9d7efcfd59d2462b2/work
249 222 0:76 / /home/docker/overlay2/37673bf2a5d954472711b10e6b33754d1828e02ab37ee11962cf32dec77ae4b6/merged rw,relatime shared:212 - overlay overlay rw,lowerdir=/home/docker/overlay2/l/7J7DWPJI5JD33JIL6YRGDKNS4Z:/home/docker/overlay2/l/QKEBVZQJV5GXCIFSREN53V4VOV:/home/docker/overlay2/l/GL7V6JHS34UJSAANPTLXFHVY3S:/home/docker/overlay2/l/6ELQJGVUDBTG5NJ6F422ZTMHCE:/home/docker/overlay2/l/KIMIOVSN5JNHN5JU4V3AEMYBHY,upperdir=/home/docker/overlay2/37673bf2a5d954472711b10e6b33754d1828e02ab37ee11962cf32dec77ae4b6/diff,workdir=/home/docker/overlay2/37673bf2a5d954472711b10e6b33754d1828e02ab37ee11962cf32dec77ae4b6/work
318 222 0:88 / /home/docker/overlay2/1837ff9131fd692ce1a6a36410c1c50f1c88a44a871c588b76fc2599b109e0bb/merged rw,relatime shared:213 - overlay overlay rw,lowerdir=/home/docker/overlay2/l/4FEAAISVKL5HOCPAXOZHLWP4XA:/home/docker/overlay2/l/GCPOS6EU4SJE3HECWFCZ4AGK74:/home/docker/overlay2/l/JBB4KXXJR6QYGZDQNYGUCAW36I:/home/docker/overlay2/l/6ELQJGVUDBTG5NJ6F422ZTMHCE:/home/docker/overlay2/l/KIMIOVSN5JNHN5JU4V3AEMYBHY,upperdir=/home/docker/overlay2/1837ff9131fd692ce1a6a36410c1c50f1c88a44a871c588b76fc2599b109e0bb/diff,workdir=/home/docker/overlay2/1837ff9131fd692ce1a6a36410c1c50f1c88a44a871c588b76fc2599b109e0bb/work
322 143 202:1 /tmp/systemd-private-476d3d6dad5c4719bc5819ccf4021002-php-fpm.service-h9iPQZ/tmp /tmp rw,relatime shared:226 master:1 - ext3 /dev/xvda1 rw,data=ordered
346 143 202:1 /var/tmp/systemd-private-476d3d6dad5c4719bc5819ccf4021002-php-fpm.service-p1YmHn/tmp /var/tmp rw,relatime shared:230 master:1 - ext3 /dev/xvda1 rw,data=ordered
649 183 0:3 / /run/docker/netns/abe400e50be3 rw,nosuid,nodev,noexec,relatime shared:231 master:5 - proc proc rw
```

after   `systemctl restart php-fpm` ,  removing the container is ok
I don't know why

**Describe the results you expected:**
remove the container without any errors

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-102.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Mon Aug  5 15:09:42 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-102.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Mon Aug  5 15:09:42 2019
 OS/Arch:         linux/amd64
 Experimental:    false
```

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 34
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 7.125 GiB
Name: SZV1000346835
ID: RIIF:MVM4:X3WJ:UIUX:GNNL:KGRR:FWMQ:2HUD:DMZA:UAN4:PBSG:KQPD
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
**Output of `docker info`:**
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment] 2020-03-10 09:19
v1.13 is ancient. Please try v19.03?

**Comment by thaJeztah** [comment] 2020-03-10 10:21
1.13 is really old indeed, and many fixes went into the codebase since.

Looks like you're running the Red Hat fork of Docker, which has many modifications that are not in this repository.

I'll close this issue because of the above, but feel free to open a new ticket if you're able to reproduce on a current version of the official docker packages; https://docs.docker.com/install/linux/docker-ce/centos/

**Closed by thaJeztah** 2020-03-10 10:21 UTC
Labels: area/storage/overlay, version/1.13, version/unsupported
