### ISSUE TITLE
Can the PageSize of the container exceed that of the host

### ISSUE THREAD

**Issue by Ruilkyu** [moby/moby#41019] opened 2020-05-25 03:04 UTC

**Comment by thaJeztah** [comment] 2020-05-26 09:28
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-05-26 09:28 UTC
Labels: kind/question

**Comment by Ruilkyu** [comment] 2020-05-26 12:39
Sorry for asking such a naive question。

**Comment by thaJeztah** [comment] 2020-05-26 13:18
No worries; it's mostly because we wouldn't be able to answer all questions in this issue tracker, so using one of the other channels may give faster result, and allow you to interact with other users to discuss more in depth
