### ISSUE TITLE
How determine the libnetwork and cli sha1 used to build docker-ce-18.03.1

### ISSUE THREAD

**Issue by VPaulGrant** [moby/moby#37230] opened 2018-06-07 15:05 UTC
Hi, I'm trying to build docker-ce 18.03.1 from source, I've pulled
the docker-ce git repo, and built it using the sha1 for the tag from the 
docker-ce repo, but which sha1 do I use for libnetwork and cli to be
consistent with the official docker 18.03.1 release?

Thanks

**Comment by thaJeztah** [comment] 2018-06-09 16:44
The correct version of all dependencies are vendored, so if you build the source, those vendored packages should be used (for some dependencies, a branch is created in which fixes are cherry-picked for a specific release).

You can find which commit is used for each component (cli, engine) in their respective vendor.conf file; for example, this is the vendor.conf for the 18.03.1 engine component; https://github.com/docker/docker-ce/blob/v18.03.1-ce/components/engine/vendor.conf

The source of all vendored dependencies is in the vendor directory of each component; https://github.com/docker/docker-ce/tree/v18.03.1-ce/components/engine/vendor

I'll close this issue, because this is not a bug report or feature request, but feel free to continue the conversation

**Closed by thaJeztah** 2018-06-09 16:44 UTC

**Comment by VPaulGrant** [comment] 2018-06-14 17:55
Thanks!
