### ISSUE TITLE
Build fails ANY command COPY/ADD or mapping docker exec -v

### ISSUE THREAD

**Issue by UKSoft66** [moby/moby#34289] opened 2017-07-27 21:41 UTC
This error is around a bit longer, e.g. issue #27233 and many more.

Anyway, all the solutions bring nothing in my case cos building fails EVERY time when COPY ADD or a mapping via Docker exec -v is involved in the Dockerfile. Hundreds of tries and not even one success.
Every Dockerfile from the repository fails if it contain these commands.

All path are relative to the build context, some errors I can prevent with having ADD/COPY before RUN commands but that is just a workaround for shorter files, actually I try to build the official PHP
https://github.com/docker-library/php/blob/ddc7084c8a78ea12f0cfdceff7d03c5a530b787e/7.1/apache/Dockerfile
and that Dockerfile has >250 lines with an severe amount of directory actions, how shall I reorder that w/o being a Linux-crack?

What can I do to get that running? I read for a week EVERY article I could find about this issue, tried hundreds of builds, soon as there is a folder access like COPY ADD or a mapping via Docker exec -v comes the error. How can it even be that your Software has such bugs? (obviously not fully handled since 2 years?)

AGAIN: I tried ALL the tips out there and the only thing that works a bit is having ADD / COPY before RUN commands, but that is not always possible. All path ARE relative with the build context as root.
Every build w/o those commands works perfect. Resetting the service doesent help either, nor anything else mentioned in those articles.
So please save your and my time and do not repeat that, this must be something else.

INFOS: 
- running on Debian or Win10 makes NO difference.
- Docker 17.05.0-ce

**Comment by thaJeztah** [comment] 2017-07-27 22:20
No need to open multiple issues; this is a duplicate of https://github.com/moby/moby/issues/34288

**Closed by thaJeztah** 2017-07-27 22:20 UTC
Labels: area/builder

**Comment by UKSoft66** [comment] 2017-07-27 22:25
Sorry havent noticed that it was posted 2 times
