### ISSUE TITLE
Swarm node would not update a image with same name and tag

### ISSUE THREAD

**Issue by eromoe** [moby/moby#36401] opened 2018-02-24 09:32 UTC
env:
Docker version 17.09.0-ce, build afdb6d4
centos 7

1. I setup a private registry on manager node , let's says A manager node, B and C are usual nodes.
1. docker stack deploy xxx
1.  B and C pull some images from A

then
1. load a new image to private registry , had a same name and tag (I update an image without change tag)
1. docker stack deploy xxx
1. B and C would not update the image

PS: 
`docker pull nd2.csp.ali:5006/bidspy/demo:0.1` does update the image in B and C,  this problem only happen in swarm.

**Comment by thaJeztah** [comment] 2018-02-24 10:44
When reporting issues, please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

closing this issue because there's not enough information to look into this, but feel free to comment after I closed

**Closed by thaJeztah** 2018-02-24 10:44 UTC
Labels: area/distribution
