### ISSUE TITLE
Should pull fix eventual image layers corruption?

### ISSUE THREAD

**Issue by tjamet** [moby/moby#36135] opened 2018-01-29 10:55 UTC
**Description**

I have a (don't know how it got corrupted yet) corrupted image layer that happens to be inside the `openjdk:8-jdk-alpine` image (c.f. https://github.com/docker-library/openjdk/issues/162).

The purpose of this issue is to wonder if the `pull` command should consider image layers checksum and re-download corrupted layers or not?

**Steps to reproduce the issue:**
There is unfortunately no clearly identified step to reproduce the issue

**Describe the results you received:**
The corruption is visible when saving the image:

```
docker save openjdk:8-jdk-alpine -o /dev/null
Error response from daemon: file integrity checksum failed for "usr/lib/jvm/java-1.8-openjdk/lib/tools.jar"
```

as well as when running the image:

```
docker pull openjdk:8-jdk-alpine; docker run --rm -ti openjdk:8-jdk-alpine javac -help
8-jdk-alpine: Pulling from library/openjdk
Digest: sha256:c5c705b462abab858066d412b3f871865684d8f837571c98b68e78c505dc7549
Status: Image is up to date for openjdk:8-jdk-alpine
Error: Could not find or load main class com.sun.tools.javac.Main
```

**Describe the results you expected:**

```docker pull openjdk:8-jdk-alpine; docker run --rm -ti openjdk:8-jdk-alpine javac -help
8-jdk-alpine: Pulling from library/openjdk
Digest: sha256:c5c705b462abab858066d412b3f871865684d8f837571c98b68e78c505dc7549
Status: Image is up to date for openjdk:8-jdk-alpine
Usage: javac <options> <source files>
where possible options include:
  -g                         Generate all debugging info
  -g:none                    Generate no debugging info
  -g:{lines,vars,source}     Generate only some debugging info
  -nowarn                    Generate no warnings
  -verbose                   Output messages about what the compiler is doing
  -deprecation               Output source locations where deprecated APIs are used
  -classpath <path>          Specify where to find user class files and annotation processors
  -cp <path>                 Specify where to find user class files and annotation processors
  -sourcepath <path>         Specify where to find input source files
  -bootclasspath <path>      Override location of bootstrap class files
  -extdirs <dirs>            Override location of installed extensions
  -endorseddirs <dirs>       Override location of endorsed standards path
  -proc:{none,only}          Control whether annotation processing and/or compilation is done.
  -processor <class1>[,<class2>,<class3>...] Names of the annotation processors to run; bypasses default discovery process
  -processorpath <path>      Specify where to find annotation processors
  -parameters                Generate metadata for reflection on method parameters
  -d <directory>             Specify where to place generated class files
  -s <directory>             Specify where to place generated source files
  -h <directory>             Specify where to place generated native header files
  -implicit:{none,class}     Specify whether or not to generate class files for implicitly referenced files
  -encoding <encoding>       Specify character encoding used by source files
  -source <release>          Provide source compatibility with specified release
  -target <release>          Generate class files for specific VM version
  -profile <profile>         Check that API used is available in the specified profile
  -version                   Version information
  -help                      Print a synopsis of standard options
  -Akey[=value]              Options to pass to annotation processors
  -X                         Print a synopsis of nonstandard options
  -J<flag>                   Pass <flag> directly to the runtime system
  -Werror                    Terminate compilation if warnings occur
  @<filename>                Read options and filenames from file
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This specific image seems to have been somehow corrupted, without - yet? - the ability to understand how

**Output of `docker version`:**

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:05:58 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:13:12 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: WGMZ:MYN5:2BRJ:UEGK:XKYU:37RV:U6ZT:KWCK:SLOP:MINR:JMNU:ZYHG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2018-01-29T10:39:28.482351117Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am running docker for mac on edge channel and have switched from stable to edge.
It is mode likely that the corrupted image was already there before switching channels and updating the docker version.

**Comment by davidwheeler123** [comment] 2018-01-31 06:06
I also had corrupted file today, in openjdk:8-jre-alpine (rather than jdk). for me it was rt.jar. docker edge 18.02.0-ce-rc1-mac50, and it happened after I did a "remove all data" and then docker pull, so the image would have been pulled by this version of docker. happy to provide more info if required, except that I've already replaced the file with an uncorrupted version.

**Comment by thaJeztah** [comment] 2018-01-31 08:50
I think this is a Docker for Mac issue, I've seen some other reports with "image verification failed" in the latest edge release, so it may be best to open an issue in the Docker for Mac issue tracker (https://github.com/doker/for-mac/issues)

**Comment by tjamet** [comment] 2018-01-31 10:40
Yes, the corruption itself seems to be a docker for mac issue, my question is:
As docker is able to detect image corruption, wouldn't it be an idea to fix it during pull by downloading the image again when corruption is detected?
rationale is that it makes `docker pull` ensure that in the end, the images matches the server version

**Comment by thaJeztah** [comment] 2018-02-01 04:04
No, docker would skip the layer that got corrupted, because it already has the layer marked as "present" in the layer store.

The error message comes from https://github.com/moby/moby/blob/919104e6bb19b2e815236ee5cffa919c373f85e2/vendor/src/github.com/vbatts/tar-split/tar/asm/assemble.go#L84-L90, which occurs when re-assembling an archive from the extracted image layer, and if the result doesn't match the expected checksum.

So in this case, likely the workaround would be to `docker image rm` the image (assuming there's only one image referring the corrupted layer), and pulling it again.

But more importantly, the filesystem corruption should be addressed in Docker for Mac 😅

**Comment by Pure-AdamuKaapan** [comment] 2019-07-18 19:02
So I’m actually seeing some corruption issues in Docker on both Ubuntu and RHEL 7 machines as well. The digests for both the image itself and the layers are identical (we’re pulling using a digest specifically instead of a tag as well). However, trying to do a `docker save` confirms that something is corrupted (`Error response from daemon: file integrity checksum failed for "bin/ash"`). Removing and re-pulling the image doesn’t help either. This is currently crippling our functional tests as it's happening about 1 in 12 times (which ends up being once every test run, more or less).

**Comment by thaJeztah** [comment] 2019-07-18 19:51
@Pure-AdamuKaapan what version of docker are you running? Is this on any image, or a particular one? (can you post `docker version` and `docker info` output?

**Comment by Pure-AdamuKaapan** [comment] 2019-07-18 19:59
@thaJeztah It's a specific company-internal image, built from scratch and copying a couple binaries over (it's only two layers). We're testing with newer docker versions now, but at the moment the failures are happening with `Docker 17.09.0-ce` (which is definitely old, it's from 2017, so I'm testing updating right now).

`docker version`:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

`docker info`:
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: ******* [censored output]
ID: HQAK:XZ33:CRIY:6SNE:DKRU:VBSJ:AKRD:MONG:RXKN:BJYA:JFDE:AMRB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by Pure-AdamuKaapan** [comment] 2019-07-18 20:00
I'm upgrading our scripts to Docker 18.03.1 right now, I'll get back to you in a bit on results from that

**Comment by thaJeztah** [comment] 2019-07-18 20:22
Docker 18.03 also reached EOL, so Docker 18.09 or up would be recommended (but doesn't hurt to upgrade in small steps)

**Comment by Pure-AdamuKaapan** [comment] 2019-07-18 22:13
Confirmed the same thing is happening on 18.03.1-ce, I'll try with another higher version (probably highest available just for absolute certainty)

**Comment by Pure-AdamuKaapan** [comment] 2019-07-19 00:11
Confirmed 18.09.8-3 has the same issue.

`docker version`:
```
Client: Docker Engine - Community
 Version:           19.03.0-rc3
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.5
 Git commit:        27fcb77
 Built:             Thu Jun 20 02:02:37 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:10:42 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

`docker info`:
```
Client:
 Debug Mode: false

Server:
 Containers: 21
  Running: 17
  Paused: 0
  Stopped: 4
 Images: 7
 Server Version: 18.09.8
 Storage Driver: overlay
  Backing Filesystem: xfs
  Supports d_type: true
 Logging Driver: syslog
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-693.2.2.el7.x86_64
 Operating System: Red Hat Enterprise Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.702GiB
 Name: t-cockroach-operator-pr-24-20-40c7b-1.dev.purestorage.com
 ID: 3PXH:MRMP:3QIL:X4VH:GWMX:EYUR:TMIC:2YQ2:6R5O:37TB:Z726:UPNA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
WARNING: the overlay storage-driver is deprecated, and will be removed in a future release.
```

**Comment by Pure-AdamuKaapan** [comment] 2019-07-24 16:39
Just curious @thaJeztah , any ideas on what I might try from here given that it's not a Docker version issue?

**Comment by thaJeztah** [comment] 2019-07-24 22:13
No ideas that stand out immediately, other than (random thoughts); virus-protection blocking access to a file during `docker save`, perhaps an extended attribute on a file that gets lost; would be good if there was a way to reproduce for investigation.

**Comment by Pure-AdamuKaapan** [comment] 2019-07-24 23:43
I'll see if I can get a smaller reproducible case. In the meantime, are there any other logs that I could collect that might be helpful? File hashes, system logs, etc?

**Comment by Pure-AdamuKaapan** [comment] 2019-07-30 23:28
Alright, so this isn't necessarily "smaller" or "reproducible" still, but it's some more usable information. We decided to try dropping our image file (tarball) in manually to each of our nodes when we run the tests. We copy the file over and confirm that the hash is the exact same on the tarball on all nodes, and that after loading we can run a command in the image fine. Just to make sure we're on the same page, this is using `docker load`, not `docker pull` like the original issue.

After running our tests, at some point *something* happens with a (seemingly) random chance, and when I check back after the tests the image sometimes is corrupted, and somehow even *the original tarball* is corrupted, even though to the best of my knowledge it shouldn't still be referred to after loading?

I'm kinda at my wit's end on how to proceed from here since it's such a strange issue.

**Comment by thaJeztah** [comment] 2019-07-30 23:38
> and somehow even the original tarball is corrupted, even though to the best of my knowledge it shouldn't still be referred to after loading?

The tarball definitely won't be touched by docker after you loaded it, so that's really odd. Could it be an issue with the physical storage on that machine? Something else running on the machine that touches those files? (like the anti-virus software I mentioned?)

**Comment by Pure-AdamuKaapan** [comment] 2019-07-30 23:49
Okay, that's what I figured; if the tarball isn't supposed to be touched at all, then I know we'll need to look elsewhere. Our VMs don't have any antivirus on them. I'm gonna see if I can do some sort of check of the overall VM filesystem integrity, as well as maybe find out exactly what is modifying that file.

**Comment by Pure-AdamuKaapan** [comment] 2019-08-09 22:51
A quick update @thaJeztah : we've been testing various things in trying to solve this, one of them was switching to use `containerd` directly with Kubernetes instead of using `docker`, and the problem ("exec format error") occurred with just `containerd` as well. We're poking around our infrastructure to see what else might be the issue.

**Comment by sam-thibault** [comment] 2023-11-10 16:09
The original issue report is old, and we do not have a clear way to reproduce.  I will close this one as stale.

**Closed by sam-thibault** 2023-11-10 16:09 UTC
Labels: area/distribution, platform/desktop

**Comment by hesham1salem** [comment] 2026-08-24 12:15
I have The same issue Docker 29.2.1
