### ISSUE TITLE
Enable p2p for `docker pull`

### ISSUE THREAD

**Issue by gyliu513** [moby/moby#36228] opened 2018-02-07 07:07 UTC
**Description**
In a large scale cluster with 1000 nodes, if all of the nodes start to pull image, then the registry will be the bottle-neck, it is suggested to enable the registry support kind of p2p to improve the image pull performance.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-02-07 07:23
duplicate of https://github.com/moby/moby/issues/247, https://github.com/moby/moby/issues/36072, and https://github.com/moby/moby/issues/26852

**Closed by thaJeztah** 2018-02-07 07:23 UTC
Labels: area/distribution
