### ISSUE TITLE
docker stats does not show any information (only dashes)

### ISSUE THREAD

**Issue by mahnunchik** [moby/moby#33986] opened 2017-07-06 16:27 UTC
**Description**

docker stats does not show any information (only dashes)

```
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
5a747311e388        --                  -- / --             --                  --                  --                  --
70d97e3244fb        --                  -- / --             --                  --                  --                  --
0f3944c9e538        --                  -- / --             --                  --                  --                  --
6ca5a74de9ba        --                  -- / --             --                  --                  --                  --
```

**Steps to reproduce the issue:**
1. `docker stats`

**Describe the results you received:**
a lot of dashes

**Describe the results you expected:**
docker statistics

**Output of `docker version`:**

```
docker -v
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 61
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 62
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: avia
ID: HH3W:SAVA:WEZS:VBJB:YZ22:RQLW:LEUF:VVSO:E23E:RWCO:KVD2:MDIA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
uname -a
Linux avia 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment] 2017-07-06 20:42
I'm not able to reproduce this on Ubuntu 16.04, kernel 4.4.0-81, could it be kernel-version specific?

```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
92ccb4f50753        0.00%               1.348MiB / 1.953GiB   0.07%               788B / 0B           0B / 0B             2
608bd2eba387        0.00%               1.355MiB / 1.953GiB   0.07%               788B / 0B           0B / 0B             2
6f3b2edbdf52        0.00%               1.355MiB / 1.953GiB   0.07%               1.04kB / 0B         0B / 0B             2
17f5737b5591        0.00%               1.359MiB / 1.953GiB   0.07%               1.3kB / 0B          0B / 0B             2
```


```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-81-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: ubuntu-2gb-sfo2-01
ID: WJCE:ZPAW:JSG5:2DF4:7L67:MWZN:7DR4:5V22:UEMS:HGZH:GMJK:R7A4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by mahnunchik** [comment] 2017-07-07 03:32
This happens after some time (hour or two) of normal `stats`.

**Comment by thaJeztah** [comment] 2017-07-07 04:15
Are there any daemon logs that indicate something went wrong?

**Comment by hugochinchilla** [comment] 2017-08-10 14:07
I have a similar problem, but in my case it's cyclical, it shows stats for some time, then shows dashes, the stats, and so on.

![tty](https://user-images.githubusercontent.com/196416/29174152-b8cd8156-7de5-11e7-883b-f3457ae5b4d6.gif)

```
hchinchilla@turing ~$ uname -r
4.4.0-87-generic

hchinchilla@turing ~$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by ripcurld0** [comment] 2017-08-10 21:21
I believe this is a duplication of #34193

**Comment by ripcurld0** [comment] 2017-08-10 22:40
@thaJeztah I'm going to investigate this more.

**Comment by ripcurld0** [comment] 2017-08-11 10:56
@mahnunchik @hugochinchilla I need more details about when does it happen.
I noticed that I get a lot of dashes when I remove or start new containers.
Is that what's happening on your hosts too?

**Comment by kisshore** [comment] 2018-09-04 12:26
@thaJeztah 
Even i'm facing same issue.  This is when i try to delete kubernetes pod, then container stats turning like this.. I know why , because of some reason,  one of the process in docker container going to "Z" stat. Then these containers start behaving abnormally.( I suspect this is because of IO issues/disk issues).

```

# docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

# uname -r
3.10.0-862.3.3.el7.x86_64


#docker stats 87bb32150c0e
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
87bb32150c0e        --                  -- / --             --                  --                  --                  --


This command hangs.
#curl --unix-socket /var/run/docker.sock "http://localhost/containers/87bb32150c0e/stats?stream=0"


# docker exec  87bb32150c0e /usr/bin/ps -aux
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:240: creating new parent process caused "container_linux.go:1254: running lstat on namespace path \"/proc/48404/ns/ipc\" caused \"lstat /proc/48404/ns/ipc: no such file or directory\""


#journalctl -u docker | grep 87bb32150c0e
Sep 04 12:07:25 <host fqdn> dockerd[16955]: time="2018-09-04T12:07:25.986682303Z" level=error msg="collecting stats for 87bb32150c0e047334d67aabb27731390ad17d7e3fd51a103d7b10f1bb88b770: Could not get container for 2c0f4e77b220751fc224e85fd7b7034068ff614cd5cd2d7ae24e362968b1fe30"
Sep 04 12:07:26 <host fqdn> dockerd[16955]: time="2018-09-04T12:07:26.990257794Z" level=error msg="collecting stats for 87bb32150c0e047334d67aabb27731390ad17d7e3fd51a103d7b10f1bb88b770: Could not get container for 2c0f4e77b220751fc224e85fd7b7034068ff614cd5cd2d7ae24e362968b1fe30"
Sep 04 12:07:54 <host fqdn> dockerd[16955]: time="2018-09-04T12:07:54.423590054Z" level=info msg="Container 87bb32150c0e047334d67aabb27731390ad17d7e3fd51a103d7b10f1bb88b770 failed to exit within 30 seconds of signal 15 - using the force"
Sep 04 12:08:04 <host fqdn> dockerd[16955]: time="2018-09-04T12:08:04.424304834Z" level=info msg="Container 87bb32150c0e failed to exit within 10 seconds of kill - trying direct SIGKILL"
```

**Comment by glaudiston** [comment] 2019-07-02 16:42
I'm facing this issue on a machine with high load and swap usage.

**Comment by thaJeztah** [comment] 2019-07-02 18:03
The `stats` endpoint calculates an average over a time period; I think it shows `---` until it gets the first result; if your machine is under high load, perhaps it's taking long (or it's unable to get the average because of the high overall load)?

If it's swapping under normal circumstance, the machine is under-provisioned; swapping will have a huge impact on overall performance. Definitely make sure that (memory/cpu) limits are in place on your containers.

What version of docker are you running?

**Comment by glaudiston** [comment] 2019-07-02 18:55
Yes, the machine is under-provisioned. Actually the high load is caused because the `kswapd0` is using a lot of CPU, the machine has 8G of RAM and is using 5G on swap. I think it's not getting the average because of the high overall load as you suggested.

After some seconds some containers return stats, then the stats turn `--` again like the animated gif above but almost all time it's empty:
![Screenshot from 2019-07-02 15-45-20](https://user-images.githubusercontent.com/8269938/60538398-f5aeed00-9ce0-11e9-9422-869b7c1f69f1.png)

`Server Version: 17.06.0-ce`, I know it's old but it's on production and I need to justify the update.

Can you confirm that this issue was fixed in current version?

**Comment by das7pad** [comment] 2019-08-22 22:28
I am seeing a similar issue: cyclic missing/present stats

The node can be considered idle: system load 15min is at 0.1 with 6 'dedicated' threads, 3.5/8GB RAM used, disk latency (iostat await) below 10ms and no swap.

Another slightly less idle node, system load 15 at 0.3 with 2 'dedicated' threads, about 4/10GB RAM used, disk latency below 15ms and 1GB swap (33MB used), has a similar output.

docker version `19.03.1`, git `74b1e89` on CentOS 7.

**Comment by das7pad** [comment] 2019-08-22 22:55
I can also replicate the issue on ubuntu 18.04, same docker version/git sha.

spin up some dummy container:
```
for i in {1..30}; do docker run --rm --detach alpine sleep 50; done
```

and start `docker stats`

**Comment by yss14** [comment] 2020-09-09 08:09
@kisshore I got the exact same problem. How did you resolve it?

**Comment by FarhadF** [comment] 2020-12-01 10:16
same here, machine is not under provisioned.

```
top - 10:14:38 up 21:54,  2 users,  load average: 5,88, 5,36, 5,17
Tasks: 238 total,   3 running, 177 sleeping,   0 stopped,   0 zombie
%Cpu0  : 30,8 us,  5,2 sy,  1,0 ni, 61,2 id,  0,0 wa,  0,0 hi,  1,0 si,  0,7 st
%Cpu1  : 31,2 us,  4,9 sy,  0,0 ni, 62,8 id,  0,0 wa,  0,0 hi,  0,4 si,  0,7 st
%Cpu2  : 38,5 us,  5,2 sy,  0,0 ni, 55,2 id,  0,0 wa,  0,0 hi,  0,7 si,  0,3 st
%Cpu3  : 28,1 us,  6,7 sy,  0,0 ni, 64,2 id,  0,4 wa,  0,0 hi,  0,4 si,  0,4 st
%Cpu4  : 34,3 us,  4,3 sy,  0,4 ni, 60,4 id,  0,0 wa,  0,0 hi,  0,4 si,  0,4 st
%Cpu5  : 30,4 us,  7,1 sy,  0,4 ni, 57,2 id,  0,4 wa,  0,0 hi,  4,2 si,  0,4 st
%Cpu6  : 27,8 us,  5,7 sy,  0,4 ni, 62,6 id,  0,0 wa,  0,0 hi,  3,2 si,  0,4 st
%Cpu7  : 28,7 us,  7,3 sy,  0,0 ni, 62,2 id,  0,3 wa,  0,0 hi,  0,7 si,  0,7 st
KiB Mem : 15391700 total,  2312168 free,  4517752 used,  8561780 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 11158672 avail Mem 
```

```
Client:
 Debug Mode: false

Server:
 Containers: 37
  Running: 36
  Paused: 0
  Stopped: 1
 Images: 68
 Server Version: 19.03.6-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.203-156.332.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 14.68GiB
 Name: ip-10-100-51-191.eu-central-1.compute.internal
 ID: PEXN:3H5C:EIRL:PD7K:CR25:BZLF:H3WD:AGWZ:VEJA:MDTW:LUTS:7NRI
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 691
  Goroutines: 765
  System Time: 2020-12-01T10:15:05.504327679Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by nicbou** [comment] 2021-03-03 14:11
I have the same issue in `Docker version 17.12.0-ce, build c97c6d6`

**Comment by giacomoguiduzzi** [comment] 2022-04-04 09:44
I'm having the same issue now. I'm using docker stats through a Python script to collect CPU and memory usage of a container while a client sends request so to analyze its behaviour. I'm reading some values correctly, then a lot of values get dashes for a long time. It looks like it gets better when the container is under high load, while it shows dashes frequently when the container is nearly idle. 

I'm doing these tests on a Raspberry Pi 3 B with Raspbian.

---

`uname -a`
```
Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux
```

---

`docker version`
```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:14 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:32 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

---

`docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 47
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.63-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 923.2MiB
 Name: raspberrypi
 ID: CLKG:2NVX:AVJE:T7SY:A36Q:R7K4:AD2K:EV6L:VVL5:CGFA:XCIP:CFAN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by justshell** [comment] 2022-12-09 11:08
I have the same issue in Docker version 20.10.5, build 55c4c88

`uname -r`
5.4.0-132-generic

**Comment by sam-thibault** [comment] 2023-04-21 09:30
Has anyone reproduced this issue on 23.0?

**Comment by bsousaa** [comment] 2023-05-02 09:31
It looks like this issue went stale. Let me close it.

**Closed by bsousaa** 2023-05-02 09:31 UTC
Labels: status/more-info-needed
