### ISSUE TITLE
We should be able to specify a delay while running docker service scale service_name=X

### ISSUE THREAD

**Issue by JnMik** [moby/moby#33767] opened 2017-06-21 10:55 UTC
Hello people !

That would be really nice to be able to specify a delay when we scale a docker service.
There is multiple service out there that are just not ready to face racing conditions and scaling multiple containers at once can make a mess of them.

Here's some examples:

Cassandra: You can't have multiple cassandra node rejoining a cluster simultaneously or the bootstrap process will fail.

Applications running Serf in background for clustering features : Serf join command will sometimes hang if it tries to reach another container not fully booted yet, scaling containers too fast can cause that.

Sometimes applications runs migrations while bootstraping, but doesn't if the migrations are already there. Launching the whole stack of containers at once could cause all the containers to try to run the migrations simultaneously and crash.

I tried to workaround the problem using service update --update-parallelism and --update-delay but it doesn't work. So finally I found a workaround with ansible to manage the scaling one container at a time, and using "wait" role in between. I believe we could do better and add a proper way to do it

The idea is launched, any comments or objections ?

Thx !

**Comment by thaJeztah** [comment] 2017-09-25 19:55
May be a duplicate of https://github.com/moby/moby/issues/30194

**Comment by thaJeztah** [comment] 2023-09-18 12:59
I think the general idea for `docker service scale` was to make it a "convenience" / "porcelain" variant for `docker service update --replicas=xxx`, and advanced / additional options to be kept out of it.


Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-18 12:59 UTC
Labels: kind/feature, area/swarm
