### ISSUE TITLE
Unable to use reference filter in prune commands

### ISSUE THREAD

**Issue by jmreicha** [moby/moby#33142] opened 2017-05-10 17:19 UTC
**Description**

Docker prune commands are not taking `reference` into account when filtering.  I have tested with the volume and image subcommands, there may be others.

**Steps to reproduce the issue:**

1. Run a prune command

`docker pull alpine`
`docker image prune --filter reference=alpine`
`docker image ls`

**Describe the results you received:**

The filter isn't picking up the reference specified.

**Describe the results you expected:**

Expect the prune command to remove only the alpine image, but it doesn't remove any.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here's the full output of the image prune command:

```
docker image prune --filter reference=alpine
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
```

**Output of `docker version`:**

```
 docker version                                                                                                                                                                                      joshuareichardt@Joshuas-MacBook-Pro
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
docker info                                                                                                                                                                                         joshuareichardt@Joshuas-MacBook-Pro
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: R663:ASEF:JLSY:ZWUY:D46M:3X47:K4SY:67GO:2QGQ:NML4:JKEW:XIJV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 29
 System Time: 2017-05-10T17:14:49.298869229Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 localhost:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Docker for mac (17.05.0-ce-rc1-mac8)

**Comment by thaJeztah** [comment] 2017-05-15 16:18
The `docker system prune` and `docker image prune` commands currently only support filtering by "until" (timestamp); https://github.com/moby/moby/blob/17.05.x/docs/reference/commandline/image_prune.md, and 17.06 will add filtering by _label_, but no other filters are present currently, so this is expected.

There is an open pull-request that adds an error-message if an unsupported filter is provided; https://github.com/moby/moby/pull/33023

I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-05-15 16:18 UTC
Labels: area/api, platform/desktop, version/17.05

**Comment by jmreicha** [comment] 2017-05-15 16:54
So should I just open a new ticket with a feature request to add this feature then?
