### ISSUE TITLE
Ambiguous network names

### ISSUE THREAD

**Issue by talex5** [moby/moby#37479] opened 2018-07-17 13:12 UTC
**Description**

If multiple networks match the pattern given to the CLI, docker just picks one, which is risky. Also, `network inspect` and `network rm` may pick differently. e.g.

**Steps to reproduce the issue:**

```
tal@laptop ~> docker network create d
4ca33da619c1d2ecdc22b15027ab9f76555b7035e7299360b6d0c966fd1e9293

tal@laptop ~> docker network inspect d | grep Id
        "Id": "di5ama0dcf6tqjz84xd1y4f9s",

tal@laptop ~> docker network rm d
WARNING! Before removing the routing-mesh network, make sure all the nodes in your swarm run the same docker engine version. Otherwise, removal may not be effective and functionality of newly create ingress networks will be impaired.
```

**Describe the results you received:**

When multiple networks match the pattern provided, docker seems to pick one unpredictably.

**Describe the results you expected:**

I expected a warning that multiple networks matched and a request to provide the full Id.

**Output of `docker version`:**

```
Client:
 Version:	18.04.0-ce-rc2
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	f4926a2
 Built:	Thu Apr  5 05:39:27 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.04.0-ce-rc2
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	f4926a2
  Built:	Thu Apr  5 05:47:53 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
tal@laptop ~> docker info
Containers: 25
 Running: 0
 Paused: 0
 Stopped: 25
Images: 467
Server Version: 18.04.0-ce-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: kf2y9azn1wwgdytql7l9wc5z0
 Is Manager: true
 ClusterID: v1kgnyq1y0pax9j01rw0k7er1
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: NZFB:4BIS:L5PX:UGW2:J2G5:VLIJ:JYUT:TH34:DKPS:ZCVT:KNWA:SV5M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 150
 System Time: 2018-07-17T13:06:47.3233229Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 dtrt.hopto.org
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was on Docker for Mac.

**Additional information you deem important (e.g. issue happens only occasionally):**

I see a similar problem on `18.03.1-ce` on Linux:

```
$ docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
5c2938c60f1d        bridge               bridge              local
0930e47c122d        docker_gwbridge      bridge              local
5n1n35dyiwmz        elk_default          overlay             swarm
x2023tc3jq6v        foo                  overlay             swarm
0ddf38e4d327        host                 host                local
x9r9oaiemvfj        ingress              overlay             swarm
leeetpsvq7sk        monitoring_default   overlay             swarm
88ad8e487414        none                 null                local

$ docker network create 5
da938c559ce009b39c7fbd7772ef4a371d360729cd962dedf4ea736e43f5e6ee

$ docker network inspect 5 | grep Id
        "Id": "5n1n35dyiwmzshckermdlb0pk",

$ docker network rm 5
5

$ docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
5c2938c60f1d        bridge               bridge              local
0930e47c122d        docker_gwbridge      bridge              local
5n1n35dyiwmz        elk_default          overlay             swarm
x2023tc3jq6v        foo                  overlay             swarm
0ddf38e4d327        host                 host                local
x9r9oaiemvfj        ingress              overlay             swarm
leeetpsvq7sk        monitoring_default   overlay             swarm
88ad8e487414        none                 null                local
```

Note that, in this case, the network removed by `docker network rm 5` was NOT the one shown by `docker network inspect 5`!

**Comment by arm64b** [comment] 2018-07-23 08:53
Can't reproduce this issue on my `18.06.0-ce` linux/ubuntu 16.04...

**Comment by thaJeztah** [comment] 2018-07-23 11:36
Related issues; 

- https://github.com/moby/moby/issues/33561 docker network rm <name> doesn't remove duplicate networks
- https://github.com/moby/moby/issues/32689 Distinguishing between names and ids?
- https://github.com/moby/moby/pull/34509 Fix network name masking network ID on delete

Those should all be in 18.03 though; checking if there's other PR's that went into 18.05 or up around this

**Comment by akerouanton** [comment] 2024-12-06 10:08
This bug has been fixed some time in the past. When deleting a network, the Engine will check if there's an exact match with one of the network full name, or if the provided pattern partial match the ID of one of the network. If more than one network are found to match, the Engine will refuse to delete anything.

There was also a case where two networks with the same name could be created concurrently, leading to delete issues but this has been fixed too.

So let me close this ticket.

**Closed by akerouanton** 2024-12-06 10:08 UTC
Labels: area/networking, platform/desktop
