### ISSUE TITLE
Files in named volume disappear on mac beta

### ISSUE THREAD

**Issue by nkovacs** [moby/moby#24503] opened 2016-07-11 11:22 UTC
**Output of `docker version`:**

```
Docker version 1.12.0-rc3, build 91e29e8, experimental
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 144
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: MGAT:ZEGU:E4YU:J7FL:A4P6:LGF3:R7G4:54F3:UKRI:MCJ5:QGQF:DPEY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 66
 System Time: 2016-07-11T11:09:50.469715841Z
 EventsListeners: 8
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker mac beta 18 (build 9996)

**Steps to reproduce the issue:**
1. Clone the `disappearing-node_modules` branch of this repo: https://github.com/nkovacs/docker-mac-bug/tree/disappearing-node_modules
2. Follow the steps in the readme

**Describe the results you received:**
The node_modules directory is empty.

**Describe the results you expected:**
The node_modules directory is not empty.

**Additional information you deem important (e.g. issue happens only occasionally):**
This works fine on linux. Stopping the container and restarting it causes the files to reappear.

**Comment by thaJeztah** [comment] 2016-07-11 14:15
Hm, I'm unable to reproduce this, but there's some possible issues;

looking at the volumes you're defining, there's both bind-mounts and volumes;

```yaml
volumes:
    - .:/var/www/app
    - ./other:/var/www/other
    - nodemodules:/var/www/app/node_modules
```

the `/var/www/app` directory is bind-mounted from your local directory, `/var/www/other` is also a bind-mount, but from another directory, and `/var/www/app/node_modules` is a volume.

I wonder if there's a possible race condition here; if (e.g.) `/var/www/app/node_modules` is mounted *before* `/var/www/app` is mounted, then `node_modules` from the current directory is masking the `/var/www/app/node_modules` mount, and you may end up seeing files from the bind-mount instead of the named volume.

**Comment by nkovacs** [comment] 2016-07-11 14:39
I'm also having issues with inotify not working, but I wasn't able to reproduce it in this simplified example.

But it definitely requires the inotify watcher and a modification to cause the nodemodules volume to unmount. Just starting index.js and stopping it is not enough, neither is just modifying the file. The bug also doesn't happen when watching with inotifywait -m.

**Comment by nkovacs** [comment] 2016-07-11 14:56
I've found the culprit: It's the two lstat calls sane does: https://github.com/nkovacs/docker-mac-bug/commit/40352e9a8b76f27f3902267ac1cb24ea9af47dae

The bug only happens if both are in there.

**Comment by thaJeztah** [comment] 2016-07-11 15:17
ping @dsheets @justincormack perhaps one of you has an idea?

**Comment by dsheets** [comment] 2016-07-11 21:20
Hi @nkovacs, thanks for the bug report and excellent reproduction repo. I can reproduce the issue and I am currently testing a patch to fix it which will probably be in Beta 19 to be released later this week. With my patch, I can no longer reproduce the issue.

**Comment by nkovacs** [comment] 2016-07-12 09:32
Thanks. I figured out the other problem as well: https://github.com/docker/docker/issues/24527

**Comment by nkovacs** [comment] 2016-07-15 08:43
Hi
Is this fix in beta 19? I can still reproduce the issue.

**Comment by dsheets** [comment] 2016-07-15 10:43
No, I'm sorry to say that it missed Beta 19 due to additional QA being required on it.

**Comment by nkovacs** [comment] 2016-07-29 07:37
Hi
This is still broken in beta 21.

**Comment by thaJeztah** [comment] 2016-07-29 07:57
ping @dsheets

**Comment by dsheets** [comment] 2016-07-29 09:33
I am sad to say that you are correct. I can also reproduce this in beta 21 and have begun to isolate the issue (again). Thanks for your report and continued patience.

**Comment by dsheets** [comment] 2016-08-03 16:17
Beta 21.1 has now been released which should resolve this issue.

**Comment by thaJeztah** [comment] 2016-08-03 17:13
Thanks! I'll close this issue, but @nkovacs would be great if you could confirm it's fixed

**Closed by thaJeztah** 2016-08-03 17:13 UTC
Labels: kind/bug, platform/desktop, area/volumes

**Comment by nkovacs** [comment] 2016-08-03 17:50
Thanks, I'll check this and #24527 tomorrow.

**Comment by nkovacs** [comment] 2016-08-04 07:58
Confirmed, thank you

**Comment by thaJeztah** [comment] 2016-08-04 08:02
Awesome, thanks!
