### ISSUE TITLE
pids-limit can't limit pid num

### ISSUE THREAD

**Issue by xiayushidai** [moby/moby#45207] opened 2023-03-24 07:47 UTC
### Description

I create a container with pids-limit, the pids-limit is 150, But more than 150 PIDs were actually found.
such as： docker run --name=test -itd --pids-limit=150 $imageId sleep 1d

### Reproduce

1. create container with pids-limit=150
docker run --name=test -d --pids-limit=150 $imageId sleep 1d

2.  try to create 1200 pids
for n in (seq1200)
do
docker exec−d test sleep10000
done

3.  look at the value of pids.current for this container, not 150.
 cat /sys/fs/cgroup/pids/docker/$containerId/pids.current
153

### Expected behavior

 /sys/fs/cgroup/pids/docker/$containerId/pids.current is 150

### docker version

```bash
docker server and client is 20.10.21.
containerd is 1.6.9.
runc is 1.1.3.
```

### docker info

```bash
everything is default
```

**Comment by sam-thibault** [comment] 2023-03-24 10:44
Possible duplicate of:
- https://github.com/moby/moby/issues/45188

**Closed by sam-thibault** 2023-03-24 10:44 UTC
Labels: status/0-triage, kind/bug
