### ISSUE TITLE
stack deploy should wait for completion

### ISSUE THREAD

**Issue by hpbieker** [moby/moby#36973] opened 2018-04-30 18:19 UTC
When running docker service update, the process waits for the updates to finish. However, when running docker stack deploy, it always runs in attached mode.

Would it be possible to add an attached mode to docker stack deploy?

This will be usefull when the docker stack deploy command is initiated from a continuous deployment script. In this case, you typically want to fail the deployment if "docker stack deploy" failed to update the services.

**Comment by thaJeztah** [comment] 2018-04-30 20:25
Thanks for opening this issue; this looks to be a duplicate of https://github.com/moby/moby/issues/32367, but given that `docker stack deploy` is fully implemented client-side, the issue is now being tracked through https://github.com/docker/cli/issues/373

Let me close this issue to prevent the discussion from diverging, but feel free to participate in the linked issue 👍

**Closed by thaJeztah** 2018-04-30 20:25 UTC
Labels: area/bundles, area/swarm, kind/enhancement
