### ISSUE TITLE
xrdp in Docker stopped working

### ISSUE THREAD

**Issue by danchitnis** [moby/moby#44910] opened 2023-02-02 22:57 UTC
### Description

Hello, I just updated to the latest version of docker, and my [container-xrdp](https://github.com/danchitnis/container-xrdp) has stopped working. The same goes for [urdxp](https://github.com/danielguerra69/ubuntu-xrdp/). These containers have been working for some years now. The error seems that xrdp cannot open or listen to the port inside docker. I am unsure if this is related to the `AF_VSOCK ` issue mentioned [here](https://github.com/moby/moby/issues/44670). If so, how to get around it? Is there a possibility of installing older versions of docker?

### Reproduce

docker run -it -p 33890:3389 danchitnis/xrdp:fedora-xfce foo bar yes

### Expected behavior

Port 33890 should be open of local host, and RDP can connect to it

### docker version

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.83.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.55GiB
 Name: docker-desktop
 ID: JFSQ:DJQB:JXLU:U7TB:7MYA:D5TE:XOZC:IW73:FV5F:4XKM:OY2V:FEQY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by neersighted** [comment] 2023-02-03 01:56
This looks like it should be an issue on https://github.com/docker/for-win -- it doesn't relate to Moby itself (and indeed, you're not on the latest version of Moby as DD does not ship that version), but instead to the networking stack provided by Docker Desktop.

**Comment by neersighted** [comment] 2023-02-03 01:56
(Also, if you are paying for Docker Desktop, you should contact Docker Support with a diagnostics dump from inside DD; they may be able to let you know that there is already a fix coming as I know there are several networking regressions 4.17 is supposed to resolve.)

**Comment by danchitnis** [comment] 2023-02-03 13:04
Thanks, I saw it [here](https://docs.docker.com/engine/release-notes/23.0/) that's why I thought it might be related to moby. I will create an issue in DD.

**Comment by neersighted** [comment] 2023-02-03 13:44
Closing as this is tracked on Docker Desktop's repo now.

**Closed by neersighted** 2023-02-03 13:44 UTC
Labels: kind/duplicate
