### ISSUE TITLE
docker exec fail after kill docker-containerd

### ISSUE THREAD

**Issue by seven-eleven** [moby/moby#36558] opened 2018-03-12 10:49 UTC
**Description**
I killed docker-containerd. It was restored by dockerd. But I met a problem: docker exec failed.
I saw https://github.com/moby/moby/pull/36173. It can't help. My docke version is 17.12.1-ce, PR is in.

**Steps to reproduce the issue:**
1. Kill `pidof docker-containerd`
2. After docker-containerd restored, exec 'docker ps' to get a container
3. Exec 'docker exec -it xxx bash', error likes: grpc: the client connection is closing: failed precondition

**Describe the results you received:**
docker exec fail, return error: grpc: the client connection is closing: failed precondition

**Describe the results you expected:**
docker exec ok after reset docker-containerd

**Additional information you deem important (e.g. issue happens only occasionally):**
Dockerd args: /usr/bin/dockerd -H fd:// -s overlay2 --data-root=/data/docker --bip=10.10.2.10/24 --log-opt max-size=50m --live-restore

**Output of `docker version`:**

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:57 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:16:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:57 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:16:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
root@shd-t-docker-02:/var/log# docker info
Containers: 164
 Running: 81
 Paused: 0
 Stopped: 83
Images: 9
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.5-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.7GiB
Name: shd-t-docker-02
ID: 36KR:4EZJ:5VYA:PU4I:2PVK:5FK2:3CGI:2UUU:VTVC:YNZY:C5GC:72J5
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-03-12 12:57
Thanks for reporting; while part of the issue is resolved, there's still an outstanding to resolve. We're already tracking that  through https://github.com/moby/moby/issues/36367, so let me close this one to prevent the discussion from diverging.

Closing as a duplicate of https://github.com/moby/moby/issues/36367, but feel free to comment after I closed 👍

**Closed by thaJeztah** 2018-03-12 12:57 UTC
Labels: area/runtime
