### ISSUE TITLE
swarm: join-IP output differs from --advertise-addr

### ISSUE THREAD

**Issue by rdxmb** [moby/moby#34635] opened 2017-08-25 15:11 UTC
**Description**

docker swarm init prints the "join-message" with a another IP as given with `--advertise-addr`
(just playing around and got this confusing output.)

**Steps to reproduce the issue:**
1. Run Host as a swarm Manager
2. Add another IP to the Host
3. Recreate a swarm with `--force-new-cluster`

**Describe the results you received:**

```
docker swarm init --force-new-cluster
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on different interfaces (192.168.253.101 on ens33 and 172.21.0.184 on ens38) - specify one with --advertise-addr
1 root@docker1:~# docker swarm init --force-new-cluster --advertise-addr 192.168.253.101
Swarm initialized: current node (x84qfn62n4vvdltlq8czjve0x) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-3jvb5ap29wizrxnm5wd4xe99jicweyg6dmwfmf5zynm018w32c-9suc6dzlmin484dzcq6t5gcst 172.21.0.105:2377
```

**Describe the results you expected:**

```
docker swarm init --force-new-cluster
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on different interfaces (192.168.253.101 on ens33 and 172.21.0.184 on ens38) - specify one with --advertise-addr
1 root@docker1:~# docker swarm init --force-new-cluster --advertise-addr 192.168.253.101
Swarm initialized: current node (x84qfn62n4vvdltlq8czjve0x) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-3jvb5ap29wizrxnm5wd4xe99jicweyg6dmwfmf5zynm018w32c-9suc6dzlmin484dzcq6t5gcst 192.168.253.101:2377
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
0 root@docker1:~# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 276
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 271
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: x84qfn62n4vvdltlq8czjve0x
 Is Manager: true
 ClusterID: 3spz9ccme9k8m27txp3hakxj9
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.253.101
 Manager Addresses:
  172.21.0.105:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.936GiB
Name: docker1
ID: 2IEE:3M36:N3VT:TSMS:3XBL:D76W:TDL4:FZXF:CROD:HFHI:363R:JJE3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu is running on VMWare Workstation

**Comment by rdxmb** [comment] 2017-08-25 15:36
Update: even if the IP does not exist on the Docker Host anymore, the join-IP-output still remains to the old IP:

```
root@docker1:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:5d:5b:bc brd ff:ff:ff:ff:ff:ff
    inet 192.168.253.101/24 brd 192.168.253.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe5d:5bbc/64 scope link 
       valid_lft forever preferred_lft forever
3: docker_gwbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:fe:4f:37:38 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::42:feff:fe4f:3738/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:59:b5:a4:d8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/24 scope global docker0
       valid_lft forever preferred_lft forever
10: vethf1fc6b2@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default 
    link/ether 06:48:b7:b4:65:2b brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::448:b7ff:feb4:652b/64 scope link 
       valid_lft forever preferred_lft forever
17: vethcd142da@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default 
    link/ether 22:2a:f1:a2:a1:0f brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::202a:f1ff:fea2:a10f/64 scope link 
       valid_lft forever preferred_lft forever
19: veth94f552a@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default 
    link/ether 6a:cc:ed:11:23:0c brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::68cc:edff:fe11:230c/64 scope link 
       valid_lft forever preferred_lft forever
(reverse-i-search)`o': i p^C
130 root@docker1:~# docker swarm init --force-new-cluster
Swarm initialized: current node (x84qfn62n4vvdltlq8czjve0x) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-3jvb5ap29wizrxnm5wd4xe99jicweyg6dmwfmf5zynm018w32c-9suc6dzlmin484dzcq6t5gcst 172.21.0.105:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

0 root@docker1:~# ip a | grep 172.21.0.105
1 root@docker1:~# docker swarm init --force-new-cluster --advertise-addr 192.168.253.101
Swarm initialized: current node (x84qfn62n4vvdltlq8czjve0x) is now a manager.                                       
                                                                                                                    
To add a worker to this swarm, run the following command:                                                           
                                                                                                                    
    docker swarm join --token SWMTKN-1-3jvb5ap29wizrxnm5wd4xe99jicweyg6dmwfmf5zynm018w32c-9suc6dzlmin484dzcq6t5gcst 172.21.0.105:2377                                                                                                   
                                                                                                                    
To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.  
```

**Comment by thaJeztah** [comment] 2017-09-25 23:10
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/34306, which contains more information about this (also check some of the linked issues from that one).

I'll close this issue to prevent the discussion from diverging, but feel free to comment if I closed this by mistake 😅

**Closed by thaJeztah** 2017-09-25 23:10 UTC
Labels: area/swarm

**Comment by rdxmb** [comment] 2017-09-26 06:47
ok, thanks
