### ISSUE TITLE
pkg/promise - Refactor package

### ISSUE THREAD

**Issue by jessfraz** [moby/moby#11587] opened 2015-03-23 02:04 UTC
**Problem**

pkg/promise - Refactor package

**Solution**

The `pkg/promise` package is a single function package, without any tests or README.md. The goal of `pkg/` being to offer first-class packages for other projects to use, this one doesn't fit.

We need to either:
- Find other potential candidates from Docker to make it into this package, cover with tests, and add a README.md
- Remove the package as a whole and move the function to a different location (to be defined)

**Comment by mattetti** [comment] 2015-03-27 03:02
Hey @jfrazelle, @kytrinyx and I are looking at this issue and we are going to write a test but I have to voice my concerns about this package. This package is kinda useless and the test is just going to test go itself :p 

I'm not sure where it's being used and why but I'd suggest to change the API to pass the channel so the originator can select on the channel or create a future using a waitgroup.

```
type Future struct {
	wg  sync.WaitGroup
	val interface{}
}

func NewFuture(h func() interface{}) *Future {
	f := &Future{}
	f.wg.Add(1)

	go func() {
		f.val = h()
		f.wg.Done()
	}()

	return f
}

func InBackground(h func()) *Future {
	f := &Future{}
	f.wg.Add(1)

	go func() {
		h()
		f.wg.Done()
	}()

	return f
}

func InBackgroundAndReport(h func() error) *Future {
	f := &Future{}
	f.wg.Add(1)

	go func() {
		logger.CheckAndPrintError(h(), "while running a background task")
		f.wg.Done()
	}()

	return f
}

func (f *Future) Wait() {
	f.wg.Wait()
}

func (f *Future) Value() interface{} {
	f.Wait()
	return f.val
}
```

**Comment by kytrinyx** [comment] 2015-03-27 03:24
Here's a test, kind of:

```
package promise

import (
	"testing"
	"time"
)

func TestGo(t *testing.T) {
	now := time.Now().UnixNano()
	var v int64
	fn := func() error {
		time.Sleep(10)
		v = now
		return nil
	}
	<-Go(fn)

	if v != now {
		t.Errorf("expected fn() to set `v`")
	}
}
```

The problem is that this also passes if you remove the goroutine, which kind of defeats the purpose. I can't think of a good way to test it that ensures that the function is called within a goroutine.

Also, I hate the `Sleep` :)

**Comment by LK4D4** [comment] 2015-03-27 05:58
This package is not very impressive IMO. And I don't want to add anything to it. Check that function called in goroutine can be performed by check, that Go is not blocking.

**Comment by jfrazelle** [comment] 2015-03-27 06:00
Sorry I was just the poor soul who got stuck copy and pasting this issue
from a secret list of birthday issues we had :(

**Comment by jfrazelle** [comment] 2015-03-27 06:04
Let me find something fun for you all of you want :)

**Comment by mattetti** [comment] 2015-03-27 06:17
No worries at all, it was fun to look at, the next step is probably to refactor the code using this package and remove it entirely :)

**Comment by cpuguy83** [comment] 2015-03-27 06:41
@mattetti +1 on refactoring anything that's using this.

**Comment by stresler** [comment] 2015-03-27 15:10
I looked at this for a while at the Docker Birthday in NYC last night and was writing up something when we got kicked out at 9. 

I think that what this is doing is actually pretty important when running calls against the API with the cli. But unless you know that you need to block and wait for a success/error, then you'll just call the api and have a race condition and this doesn't do anything to fix that underlying issue. 

I'm relatively new to Go, but it seems like the API 'attach', 'exec' and 'start' calls should have some sort of flag that does this for you when you call them. 

I arrived at this by looking at the 8 places this is used in the code and seeing the same 'wait for a response of some sort' pattern a few times. Just seems like it should baked into those function calls instead of some random package that no one know when/how to use.

**Comment by kytrinyx** [comment] 2015-03-27 15:22
Yeah +1 on refactoring anything that's using it.

> seems like it should baked into those function calls 

Do you mean that those functions should block before returning? Or that the functionality should be inlined?

I don't actually understand how this is being used (being new to docker), so I would need to dig around a bit more to figure out what the use case is.

**Comment by stresler** [comment] 2015-03-27 15:30
In the 8 places this is used they pretty much all follow this pattern

```
func (container *Container) waitForStart() error {
	container.monitor = newContainerMonitor(container, container.hostConfig.RestartPolicy)

	// block until we either receive an error from the initial start of the container's
	// process or until the process is running in the container
	select {
	case <-container.monitor.startSignal:
	case err := <-promise.Go(container.monitor.Start):
		return err
	}

	return nil
}
```

Which is 
- Call for a container to do 'something' start, attach, exec, etc. 
- Redirect output from that call into a channel. 
- Select against the error channel and the success channel to see which you get. 
- proceed accordingly. 

This function makes that 'success' channel. It seems like if you don't create that channel and monitor it for success then it is possible that the function returns success /while it is waiting for the container to start or whatnot. 

To me, that is an issue with the 'start' call returning before it has it's own state for certain - or else this would indeed be a useless 'promise'.  But instead of fixing that in the start or attach commands, it's been fixed by telling these 8 commands to 'just wait until you get an answer yay or nay'. 

A refactor should address the functions that this is wrapping, which are multiple.

**Comment by kytrinyx** [comment] 2015-03-27 15:49
Aaah, so the callers of the api/client and the daemon are all code within the docker engine itself? That would certainly simplify this a bit.

@jfrazelle do you know if there is any chance that code outside of the docker engine would use the api client and daemon directly? If there is, it would be tricky to change the expected return value of these functions.

**Comment by stresler** [comment] 2015-03-27 15:51
(Again, I'm new too, so I may be off the mark here)

I know you can definitely call the Docker api  directly, so whatever is introduced shouldn't break those calls. Have a sane default to the current way they work.

**Comment by LK4D4** [comment] 2015-03-27 15:52
@kytrinyx You can ignore such concerns. People should vendor desired versions or change their packages on-the-fly. But I'm pretty sure that nobody uses that packages, because it won't even compile without docker Dockerfile. Only `pkg` packages can be used without hacks.

**Comment by kytrinyx** [comment] 2015-03-27 16:09
@LK4D4 that simplifies things, thanks!

**Comment by vdemeester** [comment] 2018-02-14 09:03
`pkg/promise` doesn't exists anymore, let's close this one 👼

**Closed by vdemeester** 2018-02-14 09:03 UTC
Labels: area/project, exp/expert, kind/enhancement
