### ISSUE TITLE
DNS Problem: Docker Swarm not refer to VM /etc/hosts

### ISSUE THREAD

**Issue by linyuadam** [moby/moby#34072] opened 2017-07-12 10:21 UTC
We are using Docker Swarm in a VM. And we add some hostname/ip mapping in VM /etc/hosts. But we found that container inside the Swarm network won't refer to VM /etc/hosts when resolving the DNS.

**Comment by cpuguy83** [comment] 2017-07-12 13:16
I think this is working as expected.
If you want to use the host's `/etc/hosts` file, then you should mount it (`--mount type=bind,source=/etc/hosts,target=/etc/hosts`).

Alternatively you can use `docker service create --host <host1>:<ip1> --host <host2>:<ip2>`

**Comment by thaJeztah** [comment] 2017-07-13 00:55
Yes, this is expected; container's should not (by default) share these settings with the host, thus the hosts's `/etc/hosts` is not used for containers.

The examples @cpuguy83 gave should allow you to do so, or perhaps better would be to set up a DNS server.

Closing this because this is not a bug but feel free to comment if you need more info

**Closed by thaJeztah** 2017-07-13 00:55 UTC
Labels: area/swarm
