### ISSUE TITLE
how to use iptable to filter the expose port in docker bridge mode ?

### ISSUE THREAD

**Issue by bingozhou** [moby/moby#34197] opened 2017-07-20 06:20 UTC
OS: centos 7
docker version :  docker-ce 17.06
network: default bridge mode 
firewall:  use iptables not default centos7 firewalld

how to add acl rule in iptable to let docker expose port only can access by internal network ?

Thank you .

Cause of  my server is in aliyun ,the public ip is  map to the internal ip ,when I use the command docker run -p private ip:port:port ,the internal ip port and public ip port all two can be telnet ok .So it is make my containers very unsafe .

**Comment by wenjianhn** [comment] 2017-07-21 08:10
# iptables -I DOCKER-USER ! --source 192.168.0.0/24 -j DROP

Suppose 192.168.0.0/24 is your private subnet.

**Comment by thaJeztah** [comment] 2017-07-22 11:51
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-07-22 11:51 UTC
Labels: area/networking, kind/question
