### ISSUE TITLE
exec_resize on an exited exec instance return 500

### ISSUE THREAD

**Issue by hongbin** [moby/moby#35561] opened 2017-11-21 16:29 UTC
**Description**

Call exec_resize return 500 if the exec instance finishes execution.

**Steps to reproduce the issue:**

```
$ docker run -d --name test nginx
$ cat > test.py <<EOF
import docker

container_id='test'
client = docker.APIClient(base_url='unix://var/run/docker.sock')
create_res = client.exec_create(
    container_id, 'ls', stdin=True, tty=True)
exec_id = create_res['Id']
client.exec_start(exec_id, False, False, False)
client.exec_resize(exec_id, height=100, width=100)
EOF
$ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    client.exec_resize(exec_id, height=100, width=100)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/exec_api.py", line 110, in exec_resize
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("rpc error: code = Unknown desc = containerd: process not found for container")
```

**Describe the results you received:**

I received 500 response.

**Describe the results you expected:**

I expect an 4xx response.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here is a snapshot of log in server side:
```
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.229040663Z" level=debug msg="Calling POST /v1.30/containers/test/exec"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.229176122Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"ls\"],\"Container\":\"test\",\"Privileged\":false,\"Tty\":true,\"User\":\"\"}"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.231375609Z" level=debug msg="Calling POST /v1.30/exec/266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e/start"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.231444040Z" level=debug msg="form data: {\"Detach\":false,\"Tty\":false}"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.231528622Z" level=debug msg="starting exec command 266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e in container 0d717293dc2dbd58d17fe06c3a207f4d4170dd58cc7a911aa795ce0c93f8f270"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.233078476Z" level=debug msg="attach: stdin: begin"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.233188759Z" level=debug msg="attach: stderr: begin"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.233223916Z" level=debug msg="attach: stdout: begin"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.295980963Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"start-process\", Id:\"0d717293dc2dbd58d17fe06c3a207f4d4170dd58cc7a911aa795ce0c93f8f270\", Status:0x0, Pid:\"266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e\", Timestamp:(*timestamp.Timestamp)(0xc421168cd0)}"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.296009501Z" level=debug msg="containerd: process exited" id=0d717293dc2dbd58d17fe06c3a207f4d4170dd58cc7a911aa795ce0c93f8f270 pid=266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e status=0 systemPid=12973
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.296048185Z" level=debug msg="libcontainerd: event unhandled: type:\"start-process\" id:\"0d717293dc2dbd58d17fe06c3a207f4d4170dd58cc7a911aa795ce0c93f8f270\" pid:\"266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e\" timestamp:<seconds:1511281433 nanos:295722318 > "
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.296735251Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"0d717293dc2dbd58d17fe06c3a207f4d4170dd58cc7a911aa795ce0c93f8f270\", Status:0x0, Pid:\"266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e\", Timestamp:(*timestamp.Timestamp)(0xc4211008b0)}"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.297072488Z" level=debug msg="attach: stderr: end"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.297096565Z" level=debug msg="attach: stdout: end"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.297185407Z" level=debug msg="attach: stdin: end"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.299189913Z" level=debug msg="Closing buffered stdin pipe"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.299475512Z" level=debug msg="Calling POST /v1.30/exec/266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e/resize?h=100&w=100"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.300042233Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: rpc error: code = Unknown desc = containerd: process not found for container" error_type="*status.statusError" module=api
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.300068970Z" level=error msg="Handler for POST /v1.30/exec/266f1f75d23c7e8f462c9a4d413a71b18719ca9ed9ac7564bd30c22d4c97ff7e/resize returned error: rpc error: code = Unknown desc = containerd: process not found for container"
Nov 21 16:23:53 testzun dockerd[7712]: time="2017-11-21T16:23:53.300084713Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: rpc error: code = Unknown desc = containerd: process not found for container" error_type="*status.statusError" module=api
```

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host kuryr macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796GiB
Name: testzun
ID: CDMS:AE4D:KXXN:NDM3:2R33:OS6F:2O7C:Z6XK:CMVK:YFDK:KYZ3:BCLH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 41
 System Time: 2017-11-21T16:28:57.211780408Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Cluster Store: etcd://10.0.0.3:2379
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM created by OpenStack. OS: Ubuntu 16.04

**Comment by thaJeztah** [comment] 2017-11-21 16:59
I'm able to reproduce this on Docker 17.09, but it looks to be resolved on 17.11;

Start container, and create exec;

```bash
$ docker run -d --name test nginx:alpine

$ curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/containers/test/exec" \
  -H "Content-Type: application/json" \
  -d '{"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["ls"],"Container":"test","Privileged":false,"Tty":true,"User":""}'
```

```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying /var/run/docker.sock...
* Connected to localhost (/Users/sebastiaan/Library/Containers/com.dock) port 80 (#0)
> POST /v1.30/containers/test/exec HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 132
> 
* upload completely sent off: 132 out of 132 bytes
< HTTP/1.1 201 Created
< Api-Version: 1.34
< Content-Length: 74
< Content-Type: application/json
< Date: Tue, 21 Nov 2017 16:51:16 GMT
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/17.11.0-ce-rc3 (linux)
< 
{"Id":"0efc2d8343d189b8921d76b8ceef31d6732c6eecf85c842284b04941f90022f7"}
* Connection #0 to host localhost left intact
```

Start the exec:


```bash
$ curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/exec/62935855705c3afd4ae9b84abcd07d77502dfb0f3d24e889a611757b4df5e795/start" \
  -H "Content-Type: application/json" \
  -d '{"Detach":false,"Tty":false}'


Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying /var/run/docker.sock...
* Connected to localhost (/Users/sebastiaan/Library/Containers/com.dock) port 80 (#0)
> POST /v1.30/exec/0efc2d8343d189b8921d76b8ceef31d6732c6eecf85c842284b04941f90022f7/start HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 28
> 
* upload completely sent off: 28 out of 28 bytes
< HTTP/1.1 200 OK
< Api-Version: 1.34
< Content-Type: application/vnd.docker.raw-stream
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/17.11.0-ce-rc3 (linux)
< Transfer-Encoding: identity
< Date: Tue, 21 Nov 2017 16:51:22 GMT
< Connection: close
< 
bin    etc    lib    mnt    root   sbin   sys    usr
dev    home   media  proc   run    srv    tmp    var
* Closing connection 0
```

Resize the exec


```bash
$ curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/exec/62935855705c3afd4ae9b84abcd07d77502dfb0f3d24e889a611757b4df5e795/resize?h=100&w=100" \
  -H "Content-Type: application/json"


*   Trying /var/run/docker.sock...
* Connected to localhost (/Users/sebastiaan/Library/Containers/com.dock) port 80 (#0)
> POST /v1.30/exec/0efc2d8343d189b8921d76b8ceef31d6732c6eecf85c842284b04941f90022f7/resize?h=100&w=100 HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 404 Not Found
< Api-Version: 1.34
< Content-Length: 27
< Content-Type: application/json
< Date: Tue, 21 Nov 2017 16:53:24 GMT
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/17.11.0-ce-rc3 (linux)
< 
{"message":"no such exec"}
* Connection #0 to host localhost left intact
```

**Comment by miaohb** [comment] 2017-11-27 02:37
root@ubuntudbs:/opt/stack/python-zunclient# python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    client.exec_resize(exec_id, height=100, width=100)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/exec_api.py", line 110, in exec_resize
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("rpc error: code = 2 desc = containerd: process not found for container")


root@ubuntudbs:/opt/stack/python-zunclient# docker --version
Docker version 17.06.0-ce, build 02c1d87

**Comment by ripcurld0** [comment] 2017-11-27 07:38
I'm closing this as this bug was resolved in `docker-17.11` as mentioned above.
Thank you so much for the bug report!

**Closed by ripcurld0** 2017-11-27 07:38 UTC
Labels: area/daemon, area/runtime, kind/bug, version/17.09

**Comment by edupo** [comment] 2018-03-26 11:21
I hit this bug. I updated to latest. Still same issue...

```bash
$ docker --version
Docker version 18.03.0-ce, build 0520e24
```

Error
```bash
panic: Error response from daemon: {"message":"no such exec"}
```

Relevant snippets
```go
	cli, err := client.NewClientWithOpts(
		client.WithHost(dockerHost),
		client.WithVersion("v1.37"),
		client.WithHTTPHeaders(defaultHeaders))
[...]
```
```go
	// Attaching to the exec
	hijack, err := c.Cli.ContainerExecAttach(context.Background(), execID,
		types.ExecStartCheck{Tty: true})
	if err == nil {
		defer hijack.Conn.Close()
	}
	if err != nil {
		panic(err)
	}

	// Resizing the container output
	tw, th, _ := terminal.GetSize(out)
	err = c.Cli.ContainerExecResize(context.Background(), execID,
		types.ResizeOptions{Height: uint(th), Width: uint(tw)})
	if err != nil {
		panic(err)
	}
```

**Comment by thaJeztah** [comment] 2018-03-26 11:42
@edupo is the exec'd process still running? Looking at my original example above, the `exec'd` process may already have exited on resize, replacing `ls` with `top` works though.

```bash
docker run -d --name test nginx:alpine
```

```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/containers/test/exec" \
  -H "Content-Type: application/json" \
  -d '{"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["top"],"Container":"test","Privileged":false,"Tty":true,"User":""}'
```

```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/exec/c95be2ec060fcc8d97f72ad914ebd2148e588fdea0b7861daf8c22c030192423/start" \
  -H "Content-Type: application/json" \
  -d '{"Detach":false,"Tty":false}'
```

(shows:)

```
Mem: 1576584K used, 470068K free, 45436K shrd, 522968K buff, 712768K cached
CPU:   0% usr   0% sys   0% nic  99% idle   0% io   0% irq   0% sirq
Load average: 0.02 0.01 0.00 2/323 13
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    7     1 nginx    S    14184   1%   2   0% nginx: worker process
    1     0 root     S    13736   1%   1   0% nginx: master process nginx -g daemon off;
```

In another terminal;

```bash
curl -v \                                                                                                                                                                   Mon Mar 26 13:37:40 2018
       --unix-socket /var/run/docker.sock \
       -X POST \
       "http://localhost/v1.30/exec/c95be2ec060fcc8d97f72ad914ebd2148e588fdea0b7861daf8c22c030192423/resize?h=100&w=100" \
       -H "Content-Type: application/json"
```

```
*   Trying /var/run/docker.sock...
* Connected to localhost (/Users/sebastiaan/Library/Containers/com.dock) port 80 (#0)
> POST /v1.30/exec/c95be2ec060fcc8d97f72ad914ebd2148e588fdea0b7861daf8c22c030192423/resize?h=100&w=100 HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 200 OK
< Api-Version: 1.37
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< Date: Mon, 26 Mar 2018 11:40:55 GMT
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/18.03.0-ce-rc4 (linux)
< 
* Connection #0 to host localhost left intact
```

**Comment by edupo** [comment] 2018-03-26 12:15
@ thaJeztah I'm pretty sure is still running since is an interactive `/bin/bash` and if I just disable the resize I get the control of the container.

It seems to me like a race:
- You are using curl from shell to execute both commands and maybe that adds some delay between each of them. I'm using go and the 2 commands are executed one after the other.
- The full code is [here](https://github.com/edupo/cali/blob/moby-35561/docker.go#L321). But does not work.
- _What is interesting_ is that it works after adding a simple `time.Sleep(5 * time.Second)`

So `ContainerExecAttach` returns immediately.

Now my question would be: Is this the expected behavior?

**Comment by thaJeztah** [comment] 2018-03-26 15:02
Yes, a race condition is definitely possible; possibly related to / similar to https://github.com/docker/cli/pull/847
