### ISSUE TITLE
Dockerfile: not recognizing ARG before the second FROM

### ISSUE THREAD

**Issue by Jamesits** [moby/moby#38379] opened 2018-12-16 14:53 UTC
**Description**

As per #32840, `ARG` can be used before `FROM`. However the `ARG` before the second `FROM` is ignored while the second image starts building, preventing user from building the second image from a runtime-provided base.

Maybe related to #34008.

**Steps to reproduce the issue:**

Run a `docker build .` on this:

```Dockerfile
ARG IMAGE1=ubuntu:18.04
FROM $IMAGE1 as target1

ARG IMAGE2=ubuntu:18.04
FROM $IMAGE2 as target2
```

**Describe the results you received:**

```
Sending build context to Docker daemon  2.048kB
Step 1/4 : ARG IMAGE1=ubuntu:18.04
Step 2/4 : FROM $IMAGE1 as target1
 ---> 93fd78260bd1
Step 3/4 : ARG IMAGE2=ubuntu:18.04
 ---> Running in d115a4efba34
Removing intermediate container d115a4efba34
 ---> c9f2d0c57d8a
Step 4/4 : FROM $IMAGE2 as target2
base name ($IMAGE2) should not be blank
```

**Describe the results you expected:**

Image `target2` should be built from `ubuntu:18.04`.

**Additional information you deem important (e.g. issue happens only occasionally):**

None.

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a215d7
 Built:             Mon Oct  8 12:00:00 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a215d7
  Built:            Mon Oct  8 12:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 33
 Running: 0
 Paused: 0
 Stopped: 33
Images: 158
Server Version: 18.06.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.17.1 
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: v0.1.3_catatonit (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.12.14-lp150.12.16-default
Operating System: openSUSE Leap 15.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63GiB
Name: [redacted]
ID: JZGB:EHV4:NI36:WZHY:KHXS:KLXF:OTI4:KISC:B34X:JHUR:VOJH:AKAN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running inside VMWare Workstation.

**Comment by thaJeztah** [comment] 2018-12-17 12:52
This is the expected behavior, and by design: `ARG` (and `ENV`) is scoped per build-stage, so changing (or defining) an `ARG` in one build-stage should not have side-effects for other buildstages.

One exception is `ARG`'s defined _before_ the first `FROM` (thus outside of any build-stage); such `ARG`'s are "global" and can be used in each `FROM` line;

```Dockerfile
# ARG defined before the _first_ FROM are not inside a buildstage, thus in the "global" space,
# and can be used in FROM for other stages
ARG IMAGE1=ubuntu:18.04
FROM $IMAGE1 as target1

# This ARG is declared inside the "target1" build-stage, so only accessible
# within the target1 stage.
ARG IMAGE2=ubuntu:18.04

# The "target1" stage ends at the FROM line, and because of that, the FROM does
# not have access to ARG's defined in the "target1" stage. It _can_ access globally
# defined ARGs though (such as IMAGE1)
FROM $IMAGE2 as target2

FROM foobar AS target3

# To _use_ the global `IMAGE1` ARG *inside* a buildstage,
# if has to be declared within the stage. If no default value is specified,
# it takes the default from the global ARG
ARG IMAGE1
```

I'll close this issue because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-12-17 12:52 UTC
Labels: area/builder

**Comment by Jamesits** [comment] 2018-12-19 02:18
@thaJeztah Okay I know. So is there any way to achieve what I wanted to do? i.e. using `ARG` (or anything else, but `sed`ing the file using some script is not an option here) to change the base of the second image.

**Comment by thaJeztah** [comment] 2018-12-19 10:58
If you want to be able to change them individually, yes.

If you want them to be the same in most cases, this could work:

```Dockerfile
ARG DEFAULT_IMAGE=ubuntu:18.04
ARG IMAGE1=$DEFAULT_IMAGE
ARG IMAGE2=$DEFAULT_IMAGE

FROM $IMAGE1 AS target1

FROM $IMAGE2 AS target1
```

Another trick is to alias images (in this case all targets will be switched to the same version);

```Dockerfile
ARG UBUNTU_VERSION=18.04

FROM ubuntu:${UBUNTU_VERSION} AS ubuntu

FROM ubuntu AS target1

FROM ubuntu AS target2
```
