### ISSUE TITLE
Support mirrors not only for dockerhub

### ISSUE THREAD

**Issue by justadogistaken** [moby/moby#42433] opened 2021-05-28 02:18 UTC
I wonder if the community plans to support mirrors for other endpoints, instead of dockerhub only.
```
{
"registry-mirrors":[
{
	"domain": "reg.test1.com",
	"mirrors": ["http://mirror.test1.com", "https://mirror.test2.com"]
},
{
	"domian": "*",
	"mirrors": ["http://mirror.test.com"]
}
]
}
```
with such a feature, the mirror.test.com can serve for all docker pull reg.a.com/repo/name:tag. Or the mirror.test1.com and mirror.test2.com able to serve for docker pull reg.test1.com/repo/name:tag.

In Addition, the feature may make registry(distribution) support multiple remote url cache [supporting multiple remote url cache](https://github.com/distribution/distribution/issues/3423)

**Comment by gaby** [comment] 2021-06-03 02:30
👍🏻 For this feature! We currently use `https://mirror.gcr.io` via daemon.json, but having it integrated into Docker Registry would be an excellent feature!

**Comment by liangyuanpeng** [comment] 2021-07-21 16:10
Looking forward to this feature.

**Comment by thaJeztah** [comment] 2021-07-21 16:24
This looks like a duplicate of https://github.com/moby/moby/issues/18818. Let me close this one to prevent the conversation from diverging

**Closed by thaJeztah** 2021-07-21 16:24 UTC
