### ISSUE TITLE
`docker start` fails with mkdir-file-exists error

### ISSUE THREAD

**Issue by paulmenzel** [moby/moby#25270] opened 2016-07-31 20:30 UTC
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ sudo docker info
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 256
Server Version: 1.11.2
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.88 GiB
Name: myhost
ID: NJB5:TOIZ:DXP7:USNB:HF4N:7AO3:DHP6:RZZ4:5WK2:345Z:FFZN:5NLS
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian 8.4 with systemd

**Steps to reproduce the issue:**
1. Restart Docker daemon (`sudo systemctl restart docker.service`) (in my case it was killed by itself because it was unresponsive (`systemd[1]: docker.service stop-sigterm timed out. Killing.`) – different error/problem)

**Describe the results you received:**

All containers couldn’t be started anymore with the error message below.

```
$ sudo docker start memcached
mkdir /run/containerd/b0588906e76e252481c879903d88663708b1a27c33d5082a1ee06656d01eb43a: file exists
```

After a restart of the system the container could be started again.

**Describe the results you expected:**

The container should start after a problem with the Docker daemon without the need to reboot the server.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a production server, so it’s not possible to try to reproduce this, that means, just killing the Docker deamon for fun.

This looks similar to #21702, which has been closed though, is supposedly fixed although other people comment that they still experience this.

**Comment by thaJeztah** [comment] 2016-07-31 20:48
Looks like there's possibly two issues with the same effect; the linked issue was closed because it was due to a old AppArmor profile; however in the case you're describing, this comment may be relevant in this case https://github.com/docker/docker/issues/21702#issuecomment-224677467

**Comment by thaJeztah** [comment] 2016-07-31 20:49
ping @crosbymichael @mlaventure

**Comment by tonistiigi** [comment] 2016-08-01 07:01
This should not be AppArmor issue #21702 as the path here is different. Have you tried the workaround in https://github.com/docker/docker/issues/21702#issuecomment-210142727 ?

**Comment by paulmenzel** [comment] 2016-08-01 07:20
@thaJeztah, @tonistiigi, thank you for your responses and hints. I did not try the workarounds, as I was not sure, if that’s safe. But I guess deleting stuff under `/run` is safe, if a container is stopped.

But as it’s a workaround, I am more interested in what the theories are, that the files under `/run` are not cleaned up by Docker itself. Is that expected if the Docker daemon is killed/stops working?

**Comment by mlaventure** [comment] 2016-08-01 14:46
This looks like a duplicate of #25246 

@paulmenzel could you share your daemon logs to check that it is the case?

**Comment by iongion** [comment] 2016-09-30 13:49
I found this to occur on Windows due to the fact that I use junctions:
```
cd %USERPROFILE%
mklink /J Workspace W:\Workspace
```

And then from a bash or batch session I `cd` into the `Workspace` dir but from `%USERPROFILE%` so that the workspace dir is in fact:
```
C:\Users\myuser\Workspace
```
When this is the case, `docker-compose up` gets confused(`docker-compose build` has no issue)
Solving the issue by avoiding it and cd-ing directly into the `W:\Workspace`

**Comment by Jwpe** [comment] 2016-11-10 13:20
I am also encountering this issue on CoreOS 1185.3.0. After the Docker daemon is restarted with `systemctl restart docker`, I am unable to launch certain containers using `docker-compose up` because a directory already exists in `/run/containerd/`. The only solution I have found so far is the workaround described in https://github.com/docker/docker/issues/21702#issuecomment-210142727, but this is obviously not a long-term fix as it requires manual intervention.

Happy to provide more details if necessary.

**Comment by mbentley** [comment] 2016-11-10 13:24
Does your systemd service file for docker have this?: https://github.com/docker/docker/pull/23636/files  See https://github.com/docker/docker/issues/25246#issuecomment-236941609

**Comment by Jwpe** [comment] 2016-11-10 13:41
It doesn't. I'm just using the generic Docker service file on CoreOS 1185.3.0. 

@mbentley I added the line with a drop-in file in `docker.service.d` - will this have the same effect?

**Comment by thaJeztah** [comment] 2016-11-10 13:44
@Jwpe @mbentley CoreOS controls containerd through a separate unit file. It's not the recommended setup, and can cause issues

**Comment by paulmenzel** [comment] 2016-11-10 13:44
@Jwpe, yes it should. You should be able to check it with `systemctl cat docker.service`.

**Comment by mbentley** [comment] 2016-11-10 13:48
Ah, I did not realize that @thaJeztah, thanks. I'm not familiar specifically with what CoreOS is doing differently but the behavior seems to be the same issue that the updated unit file resolved for other operating systems.

**Comment by thaJeztah** [comment] 2016-11-10 13:50
@mbentley they run two docker daemons (an "early daemon", and the "regular daemon", and control containerd separately as well)

**Comment by Jwpe** [comment] 2016-11-16 11:27
@thaJeztah is this something I should take up with the CoreOS maintainers then?

**Comment by thaJeztah** [comment] 2016-11-16 16:13
@Jwpe if you have a reproducible case, it may be worth reporting. I don't expect they change the way docker is setup, but having them look into your issue may be worth a try.

**Comment by TooDizzy** [comment] 2016-11-24 10:07
Encountered the same thing today on Windows running docker version 1.12.3.

The problem went away after I went in to the "Shared Drives" section of the Docker windows settings window and pressed the "Apply" button.

**Comment by atarikguney** [comment] 2016-11-28 18:04
In addition to what @TooDizzy said, I think it happened to me because I changed my Windows Directory password and Docker may have been using the old credentials and thereby failing. Once I clicked on "Apply", Docker asked me for the new credentials, and it started working properly after I supplied the new ones.

And the following is the place I am talking about:

![image](https://cloud.githubusercontent.com/assets/369188/20679950/40730e82-b55a-11e6-86e4-bf247c93d65b.png)

**Comment by hernandanielg** [comment] 2017-11-24 02:02
We have been facing this issue lately

On each docker daemon restart some containers fails to start throwing the following error
```
Nov  3 18:13:21 docker-host dockerd[188753]: time="2017-11-03T18:13:21.566523889Z" level=error msg="Failed to start container f04518ffe3743ca5a268e549fcf227d1ee3936fae0b9a7337d8622af95a846fc: mkdir /var/run/docker/libcontainerd/containerd/f04518ffe3743ca5a268e549fcf227d1ee3936fae0b9a7337d8622af95a846fc: file exists"
Nov  3 18:13:21 docker-host dockerd[188753]: time="2017-11-03T18:13:21.788546283Z" level=error msg="Failed to start container 1647d6928a504e31d9fbf91134a04c644adc27a8a75e43de6e3f2d553a7e7d42: mkdir /var/run/docker/libcontainerd/containerd/1647d6928a504e31d9fbf91134a04c644adc27a8a75e43de6e3f2d553a7e7d42: file exists"
Nov  3 18:13:22 docker-host dockerd[188753]: time="2017-11-03T18:13:22.240549137Z" level=error msg="Failed to start container ef7f22c3be4d9dceefa89e991cd2b647bbe1afbfe4360859dd0fc5a0d90b2c48: mkdir /var/run/docker/libcontainerd/containerd/ef7f22c3be4d9dceefa89e991cd2b647bbe1afbfe4360859dd0fc5a0d90b2c48: file exists"
```

After docker daemon starts containers are in status `Exited(255)`

If we try to start them we get the following error
```
root@docker-host:~# docker start some-container 
Error response from daemon: mkdir /var/run/docker/libcontainerd/containerd/404f894fcf42fcb901205e91636fb4aa85dfa0fe3e10a7bc0a1a53b2a1d609f5: file exists Error: failed to start containers: some-container
```

Workaround we have found until now is to:
* Deploy the container again `docker stop/rm/run`
Or 
* restart docker daemon

Do you guys have any suggestion how to overcome this situation?

Cheers

**Comment by thaJeztah** [comment] 2017-11-24 09:59
@hernandanielg what version of docker are you running, and on what platform? (i.e., output of `docker version` and `docker info`); also if you're running on a system that uses `systemd` as init, check this comment: https://github.com/moby/moby/issues/25246#issuecomment-236611395

**Comment by spronin-aurea** [comment] 2017-12-01 08:27
Recent findings by @eugene-dounar 

Done some logs and code analysis, here's what happens:
- Docker is restarted
- Containerd crashes multiple times while Docker is starting up. Each time dockerd automatically restarts containerd without interrupting it's own initialization process.
- If containerd crashes during "restore container" API call, in most cases it's able to create container config dir before crashing.
- On the dockerd side, any container restoration error marks container as "exited with 255", with no retries
- After failed restoration Docker tries to start containers again, but containerd fails, as the dir already exists

What needs to be fixed:

- Docker should retry container restoration in case of "connection unavailable" errors
- Containerd crash, which is not investigated yet

**Comment by thaJeztah** [comment] 2017-12-01 15:02
@spronin-aurea that situation is with live-restore enabled?

**Comment by spronin-aurea** [comment] 2017-12-01 15:20
@thaJeztah  yes.

We have this error on 17.09.

**Comment by karser** [comment] 2017-12-01 16:54
I'm having this issue on 17.10.0-ce, here is my [post on SO](https://stackoverflow.com/questions/47597538/cannot-create-container-error-processing-tar-file-symfony-app-in-docker)

**Comment by thaJeztah** [comment] 2017-12-01 18:17
@karser your issue looks different, that message is because files are missing in the container, not the container's root directory not being there

**Comment by thaJeztah** [comment] 2017-12-01 18:22
@spronin-aurea live-restore was a feature added in docker 1.12 (https://github.com/moby/moby/pull/23213), so the issue may be different, it may be good to open your case as a separate issue, and provide more details about your setup, and events leading up to that situation (e.g., was this after an upgrade of docker? because live-restore is only supported when upgrading between patch-releases of the same version, but not an upgrade between versions of docker). Also make sure to collect relevant system-, and daemon logs.

**Comment by thaJeztah** [comment] 2017-12-01 18:26
Looking at the discussion above, this issue has been collecting a lot of non-related issues; the original issue was reported a long time ago, with a version of docker that has reached end of life. 

To prevent multiple issues from being mixed up, I'm closing this issue:

If you are running into this issue on a current version, please open a new issue, and provide the details that are requested in the issue template when you open the issue; try to provide other relevant details (events leading up to the issue, logs, etc.)

**Closed by thaJeztah** 2017-12-01 18:26 UTC
Labels: area/runtime, version/1.11
