### ISSUE TITLE
Creating swarm service using ingress network

### ISSUE THREAD

**Issue by edesai** [moby/moby#33878] opened 2017-06-29 17:32 UTC
I am using 17.05 for my manager and worker nodes and am trying to create a new ingress network with custom subnet and then creating swarm service. But service doesn't seem to spawn any containers. I see some errors from docker logs. Seems like it keeps "looping over" Requesting Address from the new subnet. Can someone help out here?

Logs as below:

Jun 28 10:58:24 dockerd[19967]: time="2017-06-28T10:58:24.952553135-07:00" level=debug msg="Service xa3gd5xvpgatbwwhis1of9lp2 was scaled up from 0 to 1 instances" module=node node.id=b9zadh96hjod5zrx55lvsv19m
Jun 28 10:58:24 dockerd[19967]: time="2017-06-28T10:58:24.953912764-07:00" level=error msg="task allocation failure" error="service xa3gd5xvpgatbwwhis1of9lp2 to which this task lukp3bld3w35g560h5ufr6ae0 belongs has pending allocations" module=node node.id=b9zadh96hjod5zrx55lvsv19m
Jun 28 10:58:24  dockerd[19967]: time="2017-06-28T10:58:24.953963436-07:00" level=debug msg="RequestAddress(GlobalDefault/11.11.0.0/16, , map[])"
Jun 28 10:58:24  dockerd[19967]: time="2017-06-28T10:58:24.954710522-07:00" level=debug msg="RequestAddress(GlobalDefault/11.11.0.0/16, , map[])"
.
.
.
My steps of reproducing are:

docker network rm ingress

docker network create --driver overlay --ingress --subnet 11.11.11.1/16 --gateway 11.11.11.1 my-ingress
ikhelr9jnjllg8fr5xfk9p8bg

docker service create --network my-ingress ct:0.1
xa3gd5xvpgatbwwhis1of9lp2
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.

Observations:

docker service ls
ID NAME MODE REPLICAS IMAGE PORTS
xa3gd5xvpgat condescending_spence replicated 0/1 172.28.x.x:5000/ct:0.1
[root@edesai-redhat-7-3-dcnm ~]# docker service ls
ID NAME MODE REPLICAS IMAGE PORTS
xa3gd5xvpgat condescending_spence replicated 0/1 172.28.x.x:5000/ct:0.1

docker network ls
NETWORK ID NAME DRIVER SCOPE
e88846664160 bridge bridge local
fde9fb9ec622 docker_gwbridge bridge local
b3efd1b6e7f4 host host local
ikhelr9jnjll my-ingress overlay swarm
5e8e58b59631 none null local

docker network inspect ikhelr9jnjll
[
{
"Name": "my-ingress",
"Id": "ikhelr9jnjllg8fr5xfk9p8bg",
"Created": "2017-06-28T10:57:37.24037921-07:00",
"Scope": "swarm",
"Driver": "overlay",
"EnableIPv6": false,
"IPAM": {
"Driver": "default",
"Options": null,
"Config": [
{
"Subnet": "11.11.11.1/16",
"Gateway": "11.11.11.1"
}
]
},
"Internal": false,
"Attachable": false,
"Ingress": true,
"Containers": {
"ingress-sbox": {
"Name": "ingress-endpoint",
"EndpointID": "940a99930934e923499d9ba59e87e166f5c1333a7010411f0968a1335d43bb59",
"MacAddress": "02:42:0b:0b:00:02",
"IPv4Address": "11.11.0.2/16",
"IPv6Address": ""
}
},

**Comment by aaronlehmann** [comment] 2017-06-29 23:54
I believe we disallow explicitly attaching a service to an ingress network. Ingress networks are only used for publishing ports.

**Comment by edesai** [comment] 2017-06-29 23:59
Sure. I tried docker service create --network my-ingress ct:0.1 --publish target=8080 and it attaches the container to ingress network. Can I use "ingress" (being a special type of overlay network) for communication between containers within swarm rather than creating another overlay ?

**Comment by aaronlehmann** [comment] 2017-06-30 00:03
You should create a different overlay for communication within the swarm.

**Comment by edesai** [comment] 2017-06-30 00:08
Is there a particular reason why we need to create a different overlay when ingress is already a type of overlay network?

**Comment by thaJeztah** [comment] 2017-07-03 00:01
Correct, this is by design; the ingress network is special, as it's used when publishing ports (as you noticed), and part of the routing mesh (i.e. route traffic between nodes if there's no instance of a service running on the node where the request arrives). _Any_ service that publishes a port is connected to the ingress network. By design, services can only communicate if connected to the same  custom network; for this reason, services communicating with each other over the ingress network is not allowed.

Closing this, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-03 00:01 UTC
Labels: area/networking, area/swarm

**Comment by rnataraja** [comment] 2017-07-05 16:30
Interesting discussion. @thaJeztah @aaronlehmann, If a solution ensures that there is always a published port for its services, would that enable us to use this network for inter container communication. Our solution does not have the need for scaling to thousands of applications. A few hundred in the best case. We really want to avoid having to place a requirement for separate overlay network to communicate between containers. And attaching MAC vlans to swarm services means that the overlay network should not conflict with network reachability over the MAC Vlan subnets.

**Comment by thaJeztah** [comment] 2017-07-06 01:47
No, the ingress network won't be changed to allow inter-container communication, this was a deliberate choice as mentioned.

Can you explain what problem there is in adding a custom overlay network? Are you worried about performance because there's _two_ overlay networks, instead of one?

**Comment by rnataraja** [comment] 2017-07-06 05:08
@thaJeztah, performance is not the issue. From your explanation earlier, I understood the issue is particularly because there is no explicit way to attach ingress network to container and hence communication between a container with published port and a container without a publishced port is not possible. If I understood correctly so this is not the only reason.
Basically, Our servces will have connection to the MAC vlan interfaces along with an overlay for inter-container communication. And the ingress routing mesh works great in ensuring services are reachable from any where. It would have been good to re-use the same network for overlay. One less subnet to worry about, and with IPv4 thats a big deal.
If there is no way for using ingress to communicate between containers, we will have to split overlay subnet into two pieces.  
Btw, Is IPv6 supported on the ingress network?
Thanks in advance.

**Comment by thaJeztah** [comment] 2017-07-06 05:39
Oh, sorry, missed you wanted to use MACvlan; in that case, overlay networking is not used, nor the ingress network afaik; routing is all done outside of docker (but I may be mistaken); see https://docs.docker.com/engine/userguide/networking/get-started-macvlan/#macvlan-8021q-trunk-bridge-mode-example-usage

**Comment by rnataraja** [comment] 2017-07-06 05:51
one could write a netplugin to manage the MAC vlan interface inside a swarm service container. That works, I have one working.
