### ISSUE TITLE
docker run/build using echo commands hangs forever, centos 7

### ISSUE THREAD

**Issue by sereysethy** [moby/moby#40514] opened 2020-02-13 14:17 UTC
**Description**
Running `echo` during build or run an image, it hangs forever. And docker engine is stopped.

**Steps to reproduce the issue:**
```shell
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete 
Digest: sha256:9572f7cdcee8591948c2963463447a53466950b3fc15a247fcad1917ca215a2f
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/


^C^C^C^C^C^Cc^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```
**Describe the results you received:**
The container did not stop or build process did not finish. In the example I only use docker run, but docker build has the same problem.

**Describe the results you expected:**
The container should stop or build process should have succeeded

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:29:29 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:28:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 2
  Paused: 0
  Stopped: 6
 Images: 182
 Server Version: 19.03.6
 Storage Driver: overlay
  Backing Filesystem: extfs
  Supports d_type: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.12.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.795GiB
 Name: XXXXXXXX
 ID: XXXXXXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
WARNING: the overlay storage-driver is deprecated, and will be removed in a future release.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by prvak** [comment] 2020-02-13 16:17
We are having the same issue. It started after upgrade from 19.03.5 to 19.03.6. To work around it we had to downgrade containerd.io to 1.2.10.

**Comment by sereysethy** [comment] 2020-02-13 16:47
Yes exactly it started after I upgraded it to 19.03.6.

**Comment by prvak** [comment] 2020-02-13 17:08
@sereysethy I am not sure that it is related to `echo`. Even command with no output hangs:
```
# docker run --rm --entrypoint /bin/true debian
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by apyrgio** [comment] 2020-02-13 17:18
@prvak: Can you `docker inspect` the container that does not stop? I suppose you will see that the reported PID is `4294967295`.

**Comment by tiborvass** [comment] 2020-02-13 17:19
Thank you for the report. We're actively investigating. I personally couldn't reproduce but we got access to a machine that has the issue. If you have additional info here, we'll be actively monitoring this thread too. Thanks!

**Comment by prvak** [comment] 2020-02-13 17:22
@apyrgio Yes, the PID is `4294967295`.

**Comment by matti** [comment] 2020-02-13 18:00
I created a new ubuntu machine in multipass.io on mac and installed docker:

```
$ multipass start
$ multipass shell

$ wget -qO- https://get.docker.com/ | sudo sh
...
$ + sh -c docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:
...
ubuntu@primary:~$ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete
Digest: sha256:9572f7cdcee8591948c2963463447a53466950b3fc15a247fcad1917ca215a2f
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

^C^C^C^C^C^C^C
P^P^P^P^P^P^P^P
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C

LOLO
```

**Comment by sereysethy** [comment] 2020-02-13 19:31
That is what I got when I do `docker inspect`:
```
"Pid": 4294967295,
```

**Comment by tiborvass** [comment] 2020-02-14 01:33
We found the [issue in containerd 1.2.12](https://github.com/containerd/containerd/issues/4023) which seems to affect only some configurations of machines (likely related to single-core).

As a stopgap, we revoked containerd 1.2.12 packages while containerd does a 1.2.13 hotfix release.
Fresh installs should work as expected.

For users who hit this issue (thus have `containerd --version` showing 1.2.12) you can fix it by running:
- on yum based distros: `yum remove -y containerd.io && yum clean all && yum makecache && yum install -y containerd.io`
- on apt based distros: I couldn't figure out how to get rid of the apt cache in a way that installs containerd 1.2.10 instead of 1.2.12. It seems that apt-get clean is not enough. However, weirdly, I could get it to work by modifying the apt sources and running apt-get update. If you installed docker with the `curl -fsSL https://get.docker.com/ | sh` script I believe this worked for me: `service docker stop && service containerd stop && apt purge containerd.io docker-ce docker-ce-cli && rm -f /etc/apt/sources.list.d/docker.list && curl -fsSL https://get.docker.com/ | sh`

Please let us know if this worked for you and I'll update instructions if needed. Sincere apologies!

**Comment by sereysethy** [comment] 2020-02-14 10:02
it is working, I downgraded containerd.io.

**Comment by thaJeztah** [comment] 2020-02-14 13:13
> likely related to single-core

Preliminary testing looks to confirm that it's related to number of cores; single-core machines hit this issue, and 2 or more cores don't

**Comment by kamild1996** [comment] 2020-02-14 18:37
I'm trying to install Docker on Raspbian Buster and I'm getting this error.
Running @tiborvass's command: `service docker stop && service containerd stop && apt purge containerd.io docker-ce docker-ce-cli && rm -f /etc/apt/sources.list.d/docker.list && curl -fsSL https://get.docker.com/ | sh`
results in:
`E: Failed to fetch https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/containerd.io_1.2.12-1_armhf.deb  404  Not Found [IP: 54.230.228.63 443]`

**Comment by AnthonyMastrean** [comment] 2020-02-17 18:58
This is affecting GitLab CI pipelines using docker-in-docker and autoscaling configurations.

https://gitlab.com/gitlab-org/gitlab-runner/issues/6697

**Comment by tao12345666333** [comment] 2020-03-08 17:09
Docker CE v19.03.7 has been released https://github.com/docker/docker-ce/releases/tag/v19.03.7
I think we can close this.

**Closed** 2020-03-08 20:24 UTC
Labels: area/runtime, kind/bug, version/19.03
