### ISSUE TITLE
Docker not able to stop or kill container - failed to exit within 10 seconds of kill ..

### ISSUE THREAD

**Issue by antetna** [moby/moby#32938] opened 2017-04-30 17:51 UTC
**Description**

After some period of time if trying to stop running container or kill it I am not able to do any of those. 
docker damon waits even for hours but not able to kill or stop conatiner. If I do CTRL+C command and repeat steps I get always same stale command, waiting and waitign to complete.

**Steps to reproduce the issue:**
1. find container that has been running for a while
2.  docker stop container_id 
3. CTRL+C ( after some time becase container is still alive (docker ps) but shows unhealthy)
4. docker kill container_id 
5. wait .... wait.... wait... nothing, impossible to kill container

**Describe the results you received:**
No results from commands, just waiting for commands to complete or CTRL+C to exit commands

**Describe the results you expected:**
I expected container to be stopped or killed.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is very common issue I have on multiple hosts and containers.  Atlough pretty much similar OS and dokcer versions.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 17:45:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 17:45:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 77
 Running: 12
 Paused: 0
 Stopped: 65
Images: 6
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.5GiB
Name: lw703
ID: VWCN:TJ2G:TD7J:Z723:ZWQU:VCUE:ERKR:VS56:IVQE:FHQO:V5A7:5MIW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 384
 Goroutines: 238
 System Time: 2017-04-30T19:46:00.998596302+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It's physical server.  

Attached  is strace of docker kill command 
[strace_docker_kill.txt](https://github.com/moby/moby/files/966869/strace_docker_kill.txt)

docker daemon logs 

```
Apr 30 19:41:42 lw703 dockerd[16668]: time="2017-04-30T19:41:42.197959069+02:00" level=debug msg="Calling POST /v1.28/containers/7fb8372e77f9/stop"
Apr 30 19:41:42 lw703 dockerd[16668]: time="2017-04-30T19:41:42.198005661+02:00" level=debug msg="Sending kill signal 15 to container 7fb8372e77f9bf0a499d09dea8019f05865a71d7db8d83664ccc48d1efb44b79"
Apr 30 19:41:45 lw703 dockerd[16668]: time="2017-04-30T19:41:45.811575525+02:00" level=info msg="Container 7fb8372e77f9 failed to exit within 10 seconds of kill - trying direct SIGKILL"
Apr 30 19:41:52 lw703 dockerd[16668]: time="2017-04-30T19:41:52.198596159+02:00" level=info msg="Container 7fb8372e77f9bf0a499d09dea8019f05865a71d7db8d83664ccc48d1efb44b79 failed to exit within 10 seconds of signal 15 - using the force"
Apr 30 19:41:52 lw703 dockerd[16668]: time="2017-04-30T19:41:52.198659825+02:00" level=debug msg="Sending kill signal 9 to container 7fb8372e77f9bf0a499d09dea8019f05865a71d7db8d83664ccc48d1efb44b79"
Apr 30 19:42:02 lw703 dockerd[16668]: time="2017-04-30T19:42:02.199295454+02:00" level=info msg="Container 7fb8372e77f9 failed to exit within 10 seconds of kill - trying direct SIGKILL"
Apr 30 19:43:35 lw703 dockerd[16668]: time="2017-04-30T19:43:35.329663035+02:00" level=debug msg="starting exec command bab47f10e1c42706067c4c57ab66bb13bd8b3ba0881813608266488d4e016b2a in container 7fb8372e77f9bf0a499d09dea8019f05865a71d7db8d83664ccc48d1efb44b79"
Apr 30 19:47:03 lw703 dockerd[16668]: time="2017-04-30T19:47:03.533439282+02:00" level=debug msg="Calling POST /v1.28/containers/7fb8372e77f9/kill?signal=KILL"
Apr 30 19:47:03 lw703 dockerd[16668]: time="2017-04-30T19:47:03.533523370+02:00" level=debug msg="Sending kill signal 9 to container 7fb8372e77f9bf0a499d09dea8019f05865a71d7db8d83664ccc48d1efb44b79"
Apr 30 19:47:13 lw703 dockerd[16668]: time="2017-04-30T19:47:13.534294498+02:00" level=info msg="Container 7fb8372e77f9 failed to exit within 10 seconds of kill - trying direct SIGKILL"

```

**Comment by thaJeztah** [comment] 2017-05-01 23:22
What's running in those containers, and does the container's main process handle signals? The container's main process always runs as PID1 inside the container, and it's fairly common for software running as PID1 to handle signals difference, or even _ignore_ signals.

Note that the _strace_ won't give much information, because it gives information about the _client_, not the daemon (the client connects to the daemon over the remote API, so there's no direct connection with the runtime, thus the containers)

**Comment by antetna** [comment] 2017-05-02 08:57
I am running official Plex docker image from here:  https://github.com/plexinc/pms-docker
It looks to me S6-overlay is taking care of main process. Where to look for cause of this problem ? this is ps from container that's running just fine.

`
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    196     4 ?        Ss   May01   0:00 s6-svscan -t0 /var/run/s6/services
root        26  0.0  0.0    196     4 ?        S    May01   0:00 s6-supervise s6-fdholderd
root       192  0.0  0.0    196     4 ?        S    May01   0:00 s6-supervise plex
plex       194  0.0  0.0   4508    76 ?        Ss   May01   0:00 /bin/sh -c LD_LIBRARY_PATH=/usr/lib/plexmediaserver /usr/lib/plexmediaserver/Plex\ Media\ Server
plex       198  0.3  0.0 750000 36052 ?        Sl   May01   2:54 /usr/lib/plexmediaserver/Plex Media Server
plex       209  0.1  0.0 1789324 60548 ?       SNl  May01   1:11 Plex Plug-in [com.plexapp.system] /usr/lib/plexmediaserver/Resources/Plug-ins-995f1dead/Framework.bundle/Cont
plex       261  0.0  0.0 233512  1396 ?        Sl   May01   0:04 /usr/lib/plexmediaserver/Plex Tuner Service /usr/lib/plexmediaserver/Resources/Tuner/Private /usr/lib/plexmed
plex      1565  0.1  0.0  21576   752 ?        S    May01   1:28 Plex EAE Service
root      9756  0.0  0.0  19952  3256 ?        Ss   08:49   0:00 /bin/bash
root      9764  0.0  0.0  36128  2896 ?        R+   08:49   0:00 ps aux
`

Is there any way to kill container that gets stuck and doesn't repsond to signals from daemon ?

**Comment by sargun** [comment] 2017-06-22 17:01
If you run `docker inspect $CONTAINER`, and call `kill -9 $PID` for the leader pid of the container, does it respond?

**Comment by antetna** [comment] 2017-06-29 16:24
Killing lead PID stops all container processes and container from docker daemon point of view is also stopped which is most important thing.  
After some time managing containers like this and avoiding docker stop or docker kill commands I do not have problems with containers getting stuck on stop.

**Comment by spencercharest** [comment] 2017-08-09 21:26
I'm experiencing this issue as well. @antetna how did you solve this? I cannot kill the container with ```kill -9 $PID```

**Comment by thaJeztah** [comment] 2017-10-11 14:50
I'm closing this issue because it looks like the original reporter found a solution, and without a reproducible case, there's no need to keep this issue open.

**Closed by thaJeztah** 2017-10-11 14:50 UTC
Labels: area/runtime, status/more-info-needed, version/17.04

**Comment by qiankunli** [comment] 2017-12-06 09:10
@antetna how did you solve this?

**Comment by antetna** [comment] 2017-12-06 09:36
I do not trust docker stop anymore, because if this command fails it's very hard to recover from it. 
Try to kill lead PID process of container (docker inspect has info about it). Killing lead pid of container has much better success rate than docker stop.

**Comment by anandbej** [comment] 2017-12-12 10:17
`[
    {
        "Id": "9484f0a799b586446a0ccc66d6994c5b5fd0ba377bd62960d049754a38e28275",
        "Created": "2017-12-12T09:09:46.823873642Z",
        "Path": "/startup.sh",
        "Args": [
            "bash"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 4064,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-12-12T09:09:47.755060774Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:2b84cce6161954be751b8375796a5525394ddc9e2f9b3034aa74ab04958b7191",
        "ResolvConfPath": "/var/lib/docker/containers/9484f0a799b586446a0ccc66d6994c5b5fd0ba377bd62960d049754a38e28275/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/9484f0a799b586446a0ccc66d6994c5b5fd0ba377bd62960d049754a38e28275/hostname",
        "HostsPath": "/var/lib/docker/containers/9484f0a799b586446a0ccc66d6994c5b5fd0ba377bd62960d049754a38e28275/hosts",
        "LogPath": "/var/lib/docker/containers/9484f0a799b586446a0ccc66d6994c5b5fd0ba377bd62960d049754a38e28275/9484f0a799b586446a0ccc66d6994c5b5fd0ba377bd62960d049754a38e28275-json.log",
        "Name": "/kickass_hamilton",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8082/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ],
                "8100/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8100"
                    }
                ],
                "8983/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8983"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": null,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [],
        "Config": {
            "Hostname": "9484f0a799b5",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "80/tcp": {},
                "8082/tcp": {},
                "8100/tcp": {},
                "8983/tcp": {},
                "90/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": null,
            "Cmd": [
                "bash"
            ],
            "Image": "2b84cce61619",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/startup.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "99832209de6f2e98cc7755fccf3d8faa2c18f309d69fdcce445bb30939da56b2",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": null,
                "8082/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ],
                "8100/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8100"
                    }
                ],
                "8983/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8983"
                    }
                ],
                "90/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/99832209de6f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "d6cc94c74904d998ff38c6ab73428b5359029c4dea4327c25d3b989170f1818c",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "90b5424289288bb49fdba8257d47804da743b87e202d3b117056dcba75044ebc",
                    "EndpointID": "d6cc94c74904d998ff38c6ab73428b5359029c4dea4327c25d3b989170f1818c",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]
`


This is what I got from the `docker inspect $container_id`.

The Pid given is 4064.

But when I did `ps -ef | grep 4064` I didn't get any docker process.

This is what I got.

` ps -ef | grep 4064
root      4064  4048  0 09:09 ?        00:00:00 [bash]
message+  4389  4064  3 09:09 ?        00:02:10 [mysqld] <defunct>
root      7468  6828  0 10:05 pts/0    00:00:00 grep 4064
`

I took all these details while `docker stop container `command is still running. It has been runnings for an hour now.

@antetna is that the correct Pid?
Please help me with this.

**Comment by antetna** [comment] 2017-12-12 11:09
That should be correct Pid. 
If Pid is not in process list for your OS it means you already tried to stop that container using `docker stop`. I do it like this:
 - I never use docker stop
- I always examine container with docker inspect for lead pid and than I kill -9 that pid
`['sudo', '/usr/bin/docker', 'inspect', '--format', "'{{.State.Pid}}'", container_id]`

**Comment by anandbej** [comment] 2017-12-18 12:41
@antetna The method that you suggested, didn't work for me. 
I think you can use ` docker rm -f container_id `. It is working well for me but I think the whole container's instance will be deleted in this.(i.e) `docker ps -a` won't display the container. Please use with caution.

Thanks.

**Comment by PlugIN73** [comment] 2018-03-16 07:22
The same issue here:
```
Mar 16 07:14:12 evaluator3 dockerd[27857]: time="2018-03-16T07:14:12.899731592Z" level=info msg="Container 679813472f3d5dc082a55b7e3d62a16109115df69609cae50701fa9bcd4133f2 failed to exit within 10 seconds of signal 15 - using the force"
Mar 16 07:14:22 evaluator3 dockerd[27857]: time="2018-03-16T07:14:22.911874532Z" level=info msg="Container 679813472f3d failed to exit within 10 seconds of kill - trying direct SIGKILL"
```
```
alexander.v@evaluator3:~$ docker info
Containers: 137
 Running: 25
 Paused: 0
 Stopped: 112
Images: 404
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-1011-azure
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.785GiB
Name: evaluator3
ID: 64XT:4DUW:C2EP:UW5I:VFCF:XTJQ:IAIM:6U6K:OYKT:LB6H:NDA6:57SN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

I have 5 servers, but only one have this issue. Another servers the same, but runned on 4.13.0-1007-azure kernel.

**Comment by dcplaya** [comment] 2018-06-14 01:09
This happens to me once every 2 days or so. If someone can tell me what is needed, I can easily supply the logs to help track this down. The only way I know how to recover is to force a hardware reset!!

**Comment by youssefNM** [comment] 2018-10-25 12:34
Guys this issue is making us a real pain with AWS ECS, when the ECS agent tries to send signal to docker in order to stop containers (for example during new deployment) the containers hang and couldn't exit making the new containers fail to start.

**Comment by drewdogg** [comment] 2019-09-11 18:08
I have experienced this issue when the process in the container gets killed due to the host OOM killer.  The container status is Up, but the process is no longer running.  So, the docker daemon is in a bad state trying to kill a PID that doesn't exist when you run `docker stop CONTAINER`.  Removing the container with -f works, and you can create a new container with the same name.  However, you cannot start the new container becuase it gives the error "/usr/bin/docker-current: Error response from daemon: service endpoint with name \<name\> already exists."  The only fix is to restart the daemon.

**Comment by thaJeztah** [comment] 2019-09-11 18:18
>  gives the error "/usr/bin/docker-current: Error response from daemon: service endpoint with name <name> already exists." 

Based on the name of that binary (`docker-current`), I suspect you're not running the official docker packages, but the Red Hat fork of Docker, which may be outdated, and has a lot of modifications that are not in the official packages. If possible, you could try to uninstall that version, and install the official packages instead; https://docs.docker.com/install/linux/docker-ce/centos/

**Comment by drewdogg** [comment] 2019-09-11 19:03
Indeed, we are running an old version from the centos extras repo, and we are in the process of upgrading to a newer release.  It is possible the issue has alredy been fixed indirectly.

**Comment by Mideen** [comment] 2019-09-13 11:56
I am also having the same issue... I tried to restart and kill the container, but I can't. Even I tried to kill the container with PID. still, the container is stuck somewhere. I restarted the docker demean even though I can't kill the containers.

Docker info : 

> Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 29.29GiB
Name: 172.20.28.48
ID: 4CMR:3EBS:3L7F:MPHK:YM3M:H3WL:ES5O:K3Z7:M3P2:P3BL:MWDR:3V44
Docker Root Dir: /home/sas/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 52
 Goroutines: 74
 System Time: 2019-09-13T17:23:01.062868101+05:30
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
WARNING: bridge-nf-call-ip6tables is disabled

docker version:

> Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false


And I am using VM centos. Please help me to solve this issue.

**Comment by thaJeztah** [comment] 2019-09-13 21:25
Please make sure to be on a current version of Docker; Docker 18.06 has reached EOL a year ago

**Comment by mikebrow** [comment] 2020-10-15 16:46
@AkihiroSuda do you remember any known issues with using runc release rc10 under containerd v1.2.13

@antetna FYI containerd 1.2 is eol, https://containerd.io/releases/#support-horizon hoping you can move up

**Comment by Perevalov** [comment] 2022-02-18 13:34
The following steps helped me:
1. Check the container ids that are not able to being stopped via status: `sudo service docker status`
2. Go to `/var/lib/docker/containers`, find the directories that correspond to the ids of the problematic containers and remove them `sudo rm -r CONTAINERID`
3. Find the `PID` of the docker daemon `dockerd` by running `ps -ef | grep docker` and kill it `sudo kill -9 PID`
4. Reboot the machine, wait some time until the daemon is restarted.

After that should work.

**Comment by krishnakc1** [comment] 2023-01-31 09:58
Restarting docker daemon will help in this scenario, but it keeps ending up in this scenario randomly. What I do not understand how would docker get into this scenario. I have a kubernetes running based on docker container runtime with containerd. I use the latest docker 20.10.22

**Comment by duduxiao** [comment] 2023-03-03 03:31
All right,  I  have  this same issues.
> Docker version 20.10.23

**Comment by yaburan** [comment] 2023-10-12 21:38
Server Version: 19.03.14

The same issue.

None of the above kills the container.

strace -p <pid> shows nothing.
But now I can not kill strace either...

    PID TTY      STAT   TIME COMMAND
1712615 ?        Ds     0:00 postgres

syslog:
Oct 13 00:24:52 DEV dockerd[2506]: time="2023-10-13T00:24:52.857926754+03:00" level=info msg="Container 7c701f4ce1c5 failed to exit within 10 seconds of kill - trying direct SIGKILL"


Just server reboot helps.

At shutdown it reported:
systemd-shutdown[1]: Waiting for process: strace, postgres, rsync, rsync

It looks like an FS issue.

**Comment by pharapeti** [comment] 2025-03-03 03:21
Same issue
Docker version: 24.0.5
Docker Compose version: v2.24.7
