### ISSUE TITLE
Docker daemon can't run any container if docker.service has LogNamespace (journald namespace) configured

### ISSUE THREAD

**Issue by niko-lay** [moby/moby#41879] opened 2021-01-13 16:37 UTC
**Description**

**Steps to reproduce the issue:**

1. Install fresh ubuntu 20.04, ensure `systemd --version` 245 or greater 
2. Create new journald namespace  `cp /etc/systemd/journald.conf /etc/systemd/journald@docker.conf` and restart journald `systemctl restart systemd-journald`
3. edit docker unit `systemctl edit docker.service`  add strings 
``` 
[Service]
LogNamespace=docker
```
and restart `systemctl restart docker.service`
4. download any docker image and try  to run  container from it `docker pull alpine`

**Describe the results you received:**
```
$ docker run -it --rm alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.
```
can't start any container

**Describe the results you expected:**
started container 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-60-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.36GiB
 Name: xxxx
 ID: K6KI:YU52:NFSC:VY6C:Q3DL:CQWI:WM3I:ZD4L:5BKX:YLVL:SL6M:4TTA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on VM within proxmox cluster

**Comment by thaJeztah** [comment] 2021-01-13 18:38
Hmm, although that ticket is not directly related, I'm wondering if it relates to https://github.com/systemd/systemd/issues/16638#issuecomment-670029912

> We unfortunately cannot implement this. LogNamespace= requires mount namespaces, so that we can redefine where /dev/log points to for services, but mount namespaces are only available to privileged processes.

And if mount namespaces cause trouble here

**Comment by thaJeztah** [comment] 2021-01-13 18:42
Note that the error itself is produced by runc

Logs from the docker daemon from the failure (dockerd running with debug enabled);

```
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.449958352Z" level=debug msg="Registering POST, /plugins/{name:.*}/disable"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.450153226Z" level=debug msg="Registering POST, /plugins/pull"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.450264154Z" level=debug msg="Registering POST, /plugins/{name:.*}/push"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.450391342Z" level=debug msg="Registering POST, /plugins/{name:.*}/upgrade"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.450503165Z" level=debug msg="Registering POST, /plugins/{name:.*}/set"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.450610913Z" level=debug msg="Registering POST, /plugins/create"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.450708400Z" level=debug msg="Registering GET, /distribution/{name:.*}/json"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.450896739Z" level=debug msg="Registering POST, /grpc"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.451040499Z" level=debug msg="Registering GET, /networks"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.451143536Z" level=debug msg="Registering GET, /networks/"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.451287611Z" level=debug msg="Registering GET, /networks/{id:.+}"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.451451195Z" level=debug msg="Registering POST, /networks/create"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.451590980Z" level=debug msg="Registering POST, /networks/{id:.*}/connect"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.451756918Z" level=debug msg="Registering POST, /networks/{id:.*}/disconnect"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.451999768Z" level=debug msg="Registering POST, /networks/prune"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.452152715Z" level=debug msg="Registering DELETE, /networks/{id:.*}"
Jan 13 18:24:46 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:24:46.452590576Z" level=info msg="API listen on /run/docker.sock"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.589900380Z" level=debug msg="Calling HEAD /_ping"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.592431431Z" level=debug msg="Calling POST /v1.41/containers/create"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.592810022Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":null,
\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":null,\"HostConfig\":{\"AutoRemove\":true,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceW
riteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":[],\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"CgroupnsMode\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"Cpu
Count\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"DeviceReques
ts\":null,\"Devices\":[],\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory
\":0,\"KernelMemoryTCP\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"MaskedPaths\":null,\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"Ne
tworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyPaths\":null,\"ReadonlyRoot
fs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},
\"Hostname\":\"\",\"Image\":\"alpine\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":true,\"Platform\":null,\"StdinOnce\":true,\"Tty\":true,\"User\":\"\",\"Vol
umes\":{},\"WorkingDir\":\"\"}"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.625357381Z" level=debug msg="container mounted via layerStore: &{/var/lib/docker/overlay2/1461f69bcf41053c4a54c2dbe95a6
ce4a354c944bca947675e5778119babf0f4/merged 0x55aedf958360 0x55aedf958360}" container=bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b911a5
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.638501357Z" level=debug msg="Calling POST /v1.41/containers/bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b
911a5/attach?stderr=1&stdin=1&stdout=1&stream=1"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.639695755Z" level=debug msg="attach: stdin: begin"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.639983847Z" level=debug msg="attach: stdout: begin"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.640184528Z" level=debug msg="attach: stderr: begin"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.640904836Z" level=debug msg="Calling POST /v1.41/containers/bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b
911a5/wait?condition=removed"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.642171216Z" level=debug msg="Calling POST /v1.41/containers/bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b
911a5/start"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.643797620Z" level=debug msg="container mounted via layerStore: &{/var/lib/docker/overlay2/1461f69bcf41053c4a54c2dbe95a6
ce4a354c944bca947675e5778119babf0f4/merged 0x55aedf958360 0x55aedf958360}" container=bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b911a5
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.644660959Z" level=debug msg="Assigning addresses for endpoint friendly_newton's interface on network bridge"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.644809331Z" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.644955138Z" level=debug msg="Request address PoolID:172.17.0.0/16 App: ipam/default/data, ID: LocalDefault/172.17.0.0/1
6, DBIndex: 0x0, Bits: 65536, Unselected: 65533, Sequence: (0xc0000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:0 Serial:false PrefAddress:<nil> "
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.679233396Z" level=debug msg="Assigning addresses for endpoint friendly_newton's interface on network bridge"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.689051987Z" level=debug msg="Programming external connectivity on endpoint friendly_newton (1e663450e0def12fb6a64de39a2
4a423a58405720f554718bf273f5e9b65f9e0)"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.690035053Z" level=debug msg="EnableService bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b911a5 START"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.690229439Z" level=debug msg="EnableService bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b911a5 DONE"
Jan 13 18:25:16 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:16.695584846Z" level=debug msg="bundle dir created" bundle=/var/run/docker/containerd/bbe6122137a8e0d71f78b1f859aaac18db0e
8425764b446818b42bd1d1b911a5 module=libcontainerd namespace=moby root=/var/lib/docker/overlay2/1461f69bcf41053c4a54c2dbe95a6ce4a354c944bca947675e5778119babf0f4/merged
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.064550278Z" level=debug msg="sandbox set key processing took 107.181769ms for container bbe6122137a8e0d71f78b1f859aaac1
8db0e8425764b446818b42bd1d1b911a5"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.096424262Z" level=error msg="stream copy error: reading from a closed fifo"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.096699698Z" level=debug msg="attach: stdout: end"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.096716885Z" level=debug msg="attach: stdin: end"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.096726880Z" level=debug msg="attach: stderr: end"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.096751661Z" level=debug msg="attach done"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.107850256Z" level=debug msg="Revoking external connectivity on endpoint friendly_newton (1e663450e0def12fb6a64de39a24a4
23a58405720f554718bf273f5e9b65f9e0)"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.113239437Z" level=debug msg="DeleteConntrackEntries purged ipv4:0, ipv6:0"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.155736941Z" level=debug msg="Releasing addresses for endpoint friendly_newton's interface on network bridge"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.156039551Z" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.156232230Z" level=debug msg="Released address PoolID:LocalDefault/172.17.0.0/16, Address:172.17.0.2 Sequence:App: ipam/
default/data, ID: LocalDefault/172.17.0.0/16, DBIndex: 0x0, Bits: 65536, Unselected: 65532, Sequence: (0xe0000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:3"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.172626333Z" level=debug msg="Failed to remove 1461f69bcf41053c4a54c2dbe95a6ce4a354c944bca947675e5778119babf0f4 overlay:
 directory not empty" storage-driver=overlay2
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.174250889Z" level=error msg="bbe6122137a8e0d71f78b1f859aaac18db0e8425764b446818b42bd1d1b911a5 cleanup: failed to delete
 container from containerd: no such container"
Jan 13 18:25:17 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[21666]: time="2021-01-13T18:25:17.202267743Z" level=debug msg="Closing buffered stdin pipe"
```

**Comment by thaJeztah** [comment] 2021-01-13 18:44
Error is different when trying to run with `--network=host`;

```console
$ docker run -it --rm --network=host alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: EOF: unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by niko-lay** [comment] 2021-01-13 20:22
tested with docker 19.03.14, same issue
```
$ docker run -it --rm alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.
$ docker run -it --rm --network=host  alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: EOF: unknown.

$ docker version 
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683


```

**Comment by cpuguy83** [comment] 2021-01-13 20:44
> Internally, journal namespaces are implemented through Linux mount namespacing and over-mounting the directory that contains the relevant AF_UNIX sockets used for logging in the unit's mount namespace. Since mount namespaces are used this setting disconnects propagation of mounts from the unit's processes to the host, similar to how ReadOnlyPaths= and similar settings (see above) work. Journal namespaces may hence not be used for services that need to establish mount points on the host.

*In theory* it might work if you put both containerd and dockerd in the same logging namespace... but I am not sure... worth trying anyway.
Otherwise this option is explicitly incompatible with how the docker-ce packages configure the systemd services.

The issue is when using `LogNamespace`, `dockerd` and `containerd` end up in different, disconnected mount namespaces and the filesystem prepared by `dockerd` is not visible to `containerd`.

**Comment by thaJeztah** [comment] 2021-01-14 13:11
> In theory it might work if you put both containerd and dockerd in the same logging namespace... but I am not sure... worth trying anyway.

I tried that when reproducing, and that didn't seem to work;

```console
$ systemctl show -p LogNamespace docker.service
LogNamespace=docker
$ systemctl show -p LogNamespace containerd.service
LogNamespace=docker
```

However, with that change, containers started with containerd still worked;

```bash
$ ctr run --rm docker.io/library/alpine:latest foo /bin/sh -c 'echo hello foo'
hello foo
```

**Comment by cpuguy83** [comment] 2021-01-14 15:26
Yes, containerd is a direct parent of the container processes and as such the mount namespace of is also a parent.

With dockerd,it is not a parent since containerd is responsible for starting the container.

**Comment by thaJeztah** [comment] 2021-01-14 17:03
Yeah, I was hoping that putting them both in the same `LogNamespace` would put them also in the same mount namespace, but apparently that's not how it works.

I don't think there's much we can do here (if someone wants to contribute to the documentation to document this somewhere, feel free to open a pull request in https://github.com/docker/docker.github.io), so let me close this ticket

Feel free to continue the conversation though after I closed

**Closed by thaJeztah** 2021-01-14 17:03 UTC
Labels: area/systemd, kind/question, version/20.10
