### ISSUE TITLE
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type' with angular-cli.json

### ISSUE THREAD

**Issue by RogierIBM** [moby/moby#37478] opened 2018-07-17 12:42 UTC
**Description**
When trying to mount the file .angular-cli.json in a container. The error:

_'Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'_

is thrown.

While running `docker-compose up -d` with the following docker compose file: 

`version: "2"
services:
  client:
    build: client
    ports:
        - "4200:4200"
        - "49153:49153"
    volumes:
        - ./client/src:/usr/src/app/src
        **- ./client/.angular-cli.json:/usr/src/app/.angular-cli.json**
        - ./client/tslint.json:/usr/src/app/tslint.json
    command: sh -c "node_modules/.bin/ng lint && node_modules/.bin/ng serve --host 0.0.0.0"

  server:
    build: server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server/resources:/usr/src/app/resources
      - ./server/src:/usr/src/app/src
      - ./server/test:/usr/src/app/test
    depends_on:
      - db
    command: sh -c "npm start"

  private-db:
    container_name: db
    image: couchdb:2.1.1
    ports:
      - "5984:5984"
`

`ERROR: forclient_1  Cannot start service client: b'OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/Users/<user>/project/client/.angular-cli.json\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/f40c6b8add0010b2f77e48bbf65bb6ef6ca69e6d6cf82b47d614bfa581c16cda/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/f40c6b8add0010b2f77e48bbf65bb6ef6ca69e6d6cf82b47d614bfa581c16cda/merged/usr/src/app/.angular-cli.json\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'
`
The following expection is thrown.

When changing the file of the .angular-cli.json to .angularcli.json there is no issue. It looks like the '-' is making it a directory. 

Maybe this is just a silly mistake from my side, but this behavior is strange

**Output of `docker version`:**
```
Docker version 18.03.1-ce, build 9ee9f40
```

**Output of `docker info`:**

```
Containers: 17
 Running: 3
 Paused: 0
 Stopped: 14
Images: 83
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: K3B7:YSFG:EJSV:XL6T:AGIJ:HDCA:GYQH:3MR2:DFII:TQNT:LVDV:QAGC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 474
 Goroutines: 489
 System Time: 2018-07-17T12:40:43.4173377Z
 EventsListeners: 4
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by cpuguy83** [comment] 2018-07-17 17:12
You would get this error because the type of the object at the bind path differs from the path in the container (e.g. one is a file and one is a directory).

**Comment by heropoo** [comment] 2019-01-09 17:17
I have the same problem.Have you solved it yet?

**Comment by cpuguy83** [comment] 2019-01-09 17:36
I see all these thumbs downs and literally no comments.
This is the error you get when you try to bind mount a file to a dir or a dir to a file. This is not supported.

Docker will create a directory on the host if the specified path does not exist when using the `-v` syntax. To get around this use `--mount` instead.

Also note that volumes and mounts are mounted from the daemon, not the client. So if you are talking to a remote daemon (ie over the network or from a container), the daemon may not be able to see what you are seeing.

@heropoo Please check the source path (on the host) and the destination path (in the container).

Not a bug, so closing.

**Closed by cpuguy83** 2019-01-09 17:36 UTC
Labels: platform/desktop

**Comment by SonGokussj4** [comment] 2019-03-04 18:16
Hi. I had the same problem. Resolved by switching with line bellow. Yeah. Just switch the line with error with some other. I had 3 volumes. Switched the 2nd with 3rd and it works.

**Comment by Leigh-M** [comment] 2019-06-21 15:28
@SonGokussj4 could you please expand on your solution a little? I think there's a line missing that you reference? thanks
