### ISSUE TITLE
[Question] Accessing parent images' label during the build time

### ISSUE THREAD

**Issue by shyam334** [moby/moby#34734] opened 2017-09-06 04:01 UTC
Hello Guys,

Is there a way to access the labels of the parent docker image during the build time.
I had a need to rename some labels from the parent image. 
Atm I have to do a `pull` - `inspect` - `build`. Is there a better way to do this.

Thanks.

**Comment by thaJeztah** [comment] 2017-09-17 00:26
No, there's no other way to get those; labels are inherited from images that extend a parent image, but to know which labels are set on the parent, you'd need to inspect it like you did.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-09-17 00:26 UTC
Labels: kind/question
