### ISSUE TITLE
Stack deploy for docker-compose.yml

### ISSUE THREAD

**Issue by adawolfs** [moby/moby#31521] opened 2017-03-03 14:43 UTC
**Description**
Hello I'm trying to start and stack with a docker-compose file but replicas are not initialized

**Steps to reproduce the issue:**
**sudo docker stack deploy --compose-file=docker-compose.yml my_stack**

But when I list the services:
```
n2xwm703gz4t  my_stack_percona       replicated  0/1       localhost:5000/percona:latest
o176qp0mdq2v  registry               replicated  1/1       registry:2
udkxsbr5f4w0  my_stack_elastic       replicated  0/1       localhost:5000/percona:latest
ugm94ewwsfnp  my_stack_nginx-proxy   replicated  0/1       jwilder/nginx-proxy:latest
```
any service in the stack seems to be alive, but when I run
**sudo docker service ps  my_stack_nginx-proxy **
```
ID            NAME                         IMAGE                       NODE  DESIRED STATE  CURRENT STATE       ERROR  PORTS
jp8fr2shgjjj  liferay_stack_nginx-proxy.1  jwilder/nginx-proxy:latest        Running        New 20 minutes ago
```
It seems to be running but there is no NODE, and when I go to the nodes there is no service running
Can you help me with this? 
**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Comment by thaJeztah** [comment] 2017-03-03 14:51
Can you;

- add the output of `docker info`
- check if the daemon logs show anything useful
- `docker service inspect` your services to see if there's an error message in there

**Comment by thaJeztah** [comment] 2017-03-03 14:52
Perhaps you can add your docker-compose file as well (or a minimal compose-file to reproduce the issue)

**Comment by jpic** [comment] 2017-03-06 00:03
I think it's there: https://github.com/adawolfs/liferay_compose

**Comment by adawolfs** [comment] 2017-03-06 14:18
There is the info and the inspect for percona service 

This is my docker-stack file the images are provided by a local registry
https://github.com/adawolfs/liferay_compose/blob/master/docker-stack.yml

**docker info**
```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 47
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 134
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ajgs65gj2gjof06n0b11wx9wh
 Is Manager: true
 ClusterID: hxoq3tcorejqgya26tp0z5ggm
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.1
 Manager Addresses:
  192.168.99.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Name: DEATH
ID: W75C:C3H4:Y5SP:UL7H:UAV6:BNDG:IWSZ:E2ZG:7HMX:ND4B:CJLM:V4AS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```
**sudo docker inspect liferay_percona**
```
[
    {
        "ID": "13halp4jf2dwo364g2wm7wmde",
        "Version": {
            "Index": 24
        },
        "CreatedAt": "2017-03-06T14:11:01.449780941Z",
        "UpdatedAt": "2017-03-06T14:11:01.449780941Z",
        "Spec": {
            "Name": "liferay_percona",
            "Labels": {
                "com.docker.stack.namespace": "liferay"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "localhost:5000/percona",
                    "Labels": {
                        "com.docker.stack.namespace": "liferay"
                    },
                    "Env": [
                        "MYSQL_DATABASE=liferay",
                        "MYSQL_PASSWORD=liferay",
                        "MYSQL_ROOT_PASSWORD=root",
                        "MYSQL_USER=liferay",
                        "character-set-server=utf8mb4",
                        "collation-server=utf8mb4_unicode_ci"
                    ]
                },
                "Resources": {},
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "Networks": [
                {
                    "Target": "igvwp6519g7cjsqche9u6e0iq",
                    "Aliases": [
                        "percona"
                    ]
                }
            ],
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]

```

**Comment by thaJeztah** [comment] 2017-03-06 15:15
Your stack uses images from the `localhost:5000` registry; is a registry running on _each_ node? All nodes will independently `pull` the image when starting the service; if the image is not present locally, or the registry is not accessible, that will fail. Could that be related to this issue?

**Comment by adawolfs** [comment] 2017-03-06 15:33
I don't think because I'm running this in swarm mode and all the nodes can find the images

**Comment by nicemaker** [comment] 2017-07-01 12:18
I had the same, after a few minutes they were all running. The reason is that the images were not done with downloading yet.  I guess you had a different problem since localhost should be pretty fast. I thought I drop a line here in case someone else has my impatience.

**Comment by thaJeztah** [comment] 2017-07-01 21:50
I do not think there's a bug at hand here, but something in the setup. Without logs and further details, it's going to be difficult answering what's causing your issue. Possibly something in the setup of the local registry.

I'm closing this issue, because i don't think this is a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-01 21:50 UTC
Labels: area/bundles, area/swarm, status/more-info-needed, version/1.13
