### ISSUE TITLE
getting container labels support

### ISSUE THREAD

**Issue by shikhasriva** [moby/moby#37433] opened 2018-07-10 19:04 UTC
Is there a way to retrieve container labels at runtime without using docker.sock apis.
 Is this something in plan or or already supported 
@carrolp

**Comment by thaJeztah** [comment] 2018-07-10 19:43
Docker uses a client/server architecture, so to get information about a container, the API should be used.

It's possible to read the container configuration that's stored on disk (somewhere in /var/lib/docker), but files inside those directories are not intended for consumption by third parties 

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-07-10 19:43 UTC
