### ISSUE TITLE
Ports get allocated over the top of each other

### ISSUE THREAD

**Issue by rgbkrk** [moby/moby#9047] opened 2014-11-09 01:35 UTC
We create and destroy lots of Docker containers and let it pick the port

```
APIError: 500 Server Error: Internal Server Error ("Cannot start container 69015ad255d949afaad8d504df6ebd2fda0cdb2477fd74e1968e0ff26e8cee5c: Error starting userland proxy: listen tcp 127.0.0.1:50131: bind: address already in use")
```

Intermittently, we notice that docker chooses to provide a port that is already in use by another container.

We're actually using https://github.com/docker/docker-py for interfacing.

/cc @smashwilson @minrk

**Comment by dnephin** [comment] 2015-02-02 21:22
Also related to #6904, #9293. There are reports in #8714 of it still happening after 1.4.1

We've run into this issue quite a bit as well:

```
2015/02/02 12:22:26 Error response from daemon: Cannot start container 9622344: Error starting userland proxy: listen tcp 0.0.0.0:49371: bind: address already in use

2015/02/02 12:28:49 Error response from daemon: Cannot start container b6e0333: Error starting userland proxy: listen tcp 0.0.0.0:49377: bind: address already in use

2015/02/02 12:29:53 Error response from daemon: Cannot start container 9dc9d49: Error starting userland proxy: listen tcp 0.0.0.0:49379: bind: address already in use

2015/02/02 12:30:23 Error response from daemon: Cannot start container 9c9e787: Error starting userland proxy: listen tcp 0.0.0.0:49380: bind: address already in use

2015/02/02 12:31:54 Error response from daemon: Cannot start container 57728d9: Error starting userland proxy: listen tcp 0.0.0.0:49381: bind: address already in use
```

I think the problem is: https://github.com/docker/docker/blob/v1.4.1/daemon/networkdriver/portallocator/portallocator.go#L138

This type of operation is inherently racy, but I think the sequential strategy makes it worse. Before we used docker we were using a different strategy, which would still fail occasionally, but with a few retries would usually succeed (where as this seems to be failing even with 10 retries).

Instead of keeping track of the last port and incrementing, you can do something like this:

```python

port = 0
socket.bind(host, port)
_, available_port = socket.getsockname()
socket.close()
```

By binding to port 0 you get a randomly selected port which is not in use (then close it so it can be used again).  It's possible something else randomly selects that port again before it gets re-bound, but in practice this seems to happen a lot less frequently than trying to sequentially increment to the next port.

I also wonder why `49153` is being used as the minimum port value. If this were a lower value there would be a lot more available space which would further decrease collisions.

Is this something that's going to be fixed by #6810, or is it worth submitting a PR to use the random selection?

**Comment by pwaller** [comment] 2015-02-02 21:36
A non-racy fix might be to allocate to port 0, and then don't close it! Just pass the resulting socket down to [`NewProxy`](https://github.com/docker/docker/blob/04117e4021da9d7fcd376b345074b84ebbd4f0ce/daemon/networkdriver/portmapper/mapper.go#L55-L68).

**Comment by dnephin** [comment] 2015-02-02 21:38
That would be the best solution, if that's manageable

**Comment by LK4D4** [comment] 2015-02-02 21:45
I don't understand why this operation is racy, that function called always under global lock. But I like idea of using OS for finding port, also @erikh wrote implementation based on `/proc/net/<proto>` here: https://github.com/shykes/docker/blob/extensions/extensions/simplebridge/portmapper.go

**Comment by erikh** [comment] 2015-02-02 21:50
I wouldn’t rely on this implementation right now. Sorry to get your hopes up. :)

-Erik

**Comment by LK4D4** [comment] 2015-02-02 22:29
I wrote simple implementation on go:
https://gist.github.com/34da2bc68266242451cd
Also there is related #10238

**Comment by jfrazelle** [comment] 2015-02-26 23:28
is this still happening on 1.5 (userland proxy?)

**Comment by dnephin** [comment] 2015-02-27 19:06
I was only able to trigger this problem on a jenkins host that ran many builds, and we changed most of our builds to not use `ports`.  Once we upgrade that host to 1.5 I can try to reproduce.

**Comment by dubglan** [comment] 2015-04-01 06:33
We see docker run failing with:
```7a638d4e83e89ee5fce08c9551e402a4704bf4fa6b588baf157901bb85b6909e
time="2015-03-31T16:16:48-07:00" level="fatal" msg="Error response from daemon: Cannot start container 7a638d4e83e89ee5fce08c9551e402a4704bf4fa6b588baf157901bb85b6909e: Error starting userland proxy: listen tcp 0.0.0.0:49175: bind: address already in use"
```
Docker version is 1.5.0. Is there any additional signature we can check for to make sure it is this bug?

**Comment by edanShavit** [comment] 2015-05-12 11:57
We have been running docker 1.5.0 (build a8a31ef-dirty) with fleet 0.10.0 for about three weeks.
The problem is now harder to reproduce then in the previous versions, but we have manage to locate a service with the message:

May 11 12:59:43 runtime-e050b89c-6bdb-4900-b6f3-3a9ae7b8dfd7 bash[26410]: time="2015-05-11T12:59:43Z" level="fatal" msg="Error response from daemon: Cannot start container 2fa76d1b4a042b0813e9032fdcee77cd455a72c4490103a760a011d792bb4772: Error starting userland proxy: listen tcp 0.0.0.0:50476: bind: address already in use"

**Comment by aggieben** [comment] 2015-08-12 22:11
I see this in 1.7 on a gentoo metal host (i.e., not a VM), but not in a debian VM host.

**Comment by thaJeztah** [comment] 2015-08-15 18:48
@aggieben docker 1.7 added a new option to disable the userland proxy; add  `--userland-proxy=false` to your daemon options to disable it (hope that helps)

**Comment by rgbkrk** [comment] 2015-08-16 03:56
What does it mean when the user land proxy is disabled?

**Comment by erikh** [comment] 2015-08-16 09:38
I don’t think this matters here; this is the portmapper bugging out, which I imagine is being polished up with the libnetwork changes.
On August 15, 2015 at 11:48:07 AM, Sebastiaan van Stijn (notifications@github.com) wrote:

@aggieben docker 1.7 added a new option to disable the userland proxy; add --userland-proxy=false to your daemon options to disable it (hope that helps)

**Comment by thaJeztah** [comment] 2015-08-16 09:46
@erikh you may be right, I was skimming through issues and saw https://github.com/docker/docker/issues/9047#issuecomment-62291395, thought it was worth a try.

**Comment by ceecko** [comment] 2016-07-24 18:00
This issue still exists in 1.11.2

```
# docker info
Containers: 59
 Running: 51
 Paused: 0
 Stopped: 8
Images: 3
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: data-docker_thin
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 5.16 GB
 Data Space Total: 21.47 GB
 Data Space Available: 16.32 GB
 Metadata Space Used: 12.67 MB
 Metadata Space Total: 134.2 MB
 Metadata Space Available: 121.5 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 28.76 GiB
Name: eu-2.localdomain
ID: LF7S:JDSV:JYRT:PKF7:PZOR:22A5:3NL6:MD5J:A656:4VAO:HFS2:Y6VT
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Comment by akerouanton** [comment] 2023-07-24 09:26
AFAICT OP's original issue has been addressed at some point since 2014. Nonetheless, we still have an issue where dockerd could shadow a port bound by a local process. This is tracked by #44136.

Let met close this issue as it went stale.

**Closed by akerouanton** 2023-07-24 09:26 UTC
Labels: exp/expert, kind/bug, area/networking

**Comment by rgbkrk** [comment] 2023-08-12 13:32
Thanks for closing this, it's been a long time since I've needed this directly.
