### ISSUE TITLE
Container freezes while using git (./init-repository)

### ISSUE THREAD

**Issue by theshadowx** [moby/moby#16237] opened 2015-09-11 13:11 UTC
## Description of problem:

So, I want to install Qt 5.5 from git repository in arm based image resin/rpi-raspbian:wheezy
For that I follow this tutorial https://wiki.qt.io/Native_Build_of_Qt5_on_a_Raspberry_Pi
Everything went well until : 

```
cd qt5
./init-repository
```

so here is the output

```
root@d6ba17169ea4:/opt/qt5# ./init-repository
+ git submodule init qt3d qtactiveqt qtandroidextras qtbase qtcanvas3d qtconnectivity qtdeclarative qtdoc qtenginio qtgraphicaleffects qtimageformats qtlocation qtmacextras qtmultimedia qtqa qtquick1 qtquickcontrols qtrepotools qtscript qtsensors qtserialport qtsvg qttools qttranslations qtwayland qtwebchannel qtwebengine qtwebkit qtwebkit-examples qtwebsockets qtwinextras qtx11extras qtxmlpatterns
Submodule 'qt3d' (git://code.qt.io/qt/qt3d.git) registered for path 'qt3d'
Submodule 'qtactiveqt' (git://code.qt.io/qt/qtactiveqt.git) registered for path 'qtactiveqt'
Submodule 'qtandroidextras' (git://code.qt.io/qt/qtandroidextras.git) registered for path 'qtandroidextras'
Submodule 'qtbase' (git://code.qt.io/qt/qtbase.git) registered for path 'qtbase'
Submodule 'qtcanvas3d' (git://code.qt.io/qt/qtcanvas3d.git) registered for path 'qtcanvas3d'
Submodule 'qtconnectivity' (git://code.qt.io/qt/qtconnectivity.git) registered for path 'qtconnectivity'
Submodule 'qtdeclarative' (git://code.qt.io/qt/qtdeclarative.git) registered for path 'qtdeclarative'
Submodule 'qtdoc' (git://code.qt.io/qt/qtdoc.git) registered for path 'qtdoc'
Submodule 'qtenginio' (git://code.qt.io/qt/qtenginio.git) registered for path 'qtenginio'
Submodule 'qtgraphicaleffects' (git://code.qt.io/qt/qtgraphicaleffects.git) registered for path 'qtgraphicaleffects'
Submodule 'qtimageformats' (git://code.qt.io/qt/qtimageformats.git) registered for path 'qtimageformats'
Submodule 'qtlocation' (git://code.qt.io/qt/qtlocation.git) registered for path 'qtlocation'
Submodule 'qtmacextras' (git://code.qt.io/qt/qtmacextras.git) registered for path 'qtmacextras'
Submodule 'qtmultimedia' (git://code.qt.io/qt/qtmultimedia.git) registered for path 'qtmultimedia'
Submodule 'qtqa' (git://code.qt.io/qt/qtqa.git) registered for path 'qtqa'
Submodule 'qtquick1' (git://code.qt.io/qt/qtquick1.git) registered for path 'qtquick1'
Submodule 'qtquickcontrols' (git://code.qt.io/qt/qtquickcontrols.git) registered for path 'qtquickcontrols'
Submodule 'qtrepotools' (git://code.qt.io/qt/qtrepotools.git) registered for path 'qtrepotools'
Submodule 'qtscript' (git://code.qt.io/qt/qtscript.git) registered for path 'qtscript'
Submodule 'qtsensors' (git://code.qt.io/qt/qtsensors.git) registered for path 'qtsensors'
Submodule 'qtserialport' (git://code.qt.io/qt/qtserialport.git) registered for path 'qtserialport'
Submodule 'qtsvg' (git://code.qt.io/qt/qtsvg.git) registered for path 'qtsvg'
Submodule 'qttools' (git://code.qt.io/qt/qttools.git) registered for path 'qttools'
Submodule 'qttranslations' (git://code.qt.io/qt/qttranslations.git) registered for path 'qttranslations'
Submodule 'qtwayland' (git://code.qt.io/qt/qtwayland.git) registered for path 'qtwayland'
Submodule 'qtwebchannel' (git://code.qt.io/qt/qtwebchannel.git) registered for path 'qtwebchannel'
Submodule 'qtwebengine' (git://code.qt.io/qt/qtwebengine.git) registered for path 'qtwebengine'
Submodule 'qtwebkit' (git://code.qt.io/qt/qtwebkit.git) registered for path 'qtwebkit'
Submodule 'qtwebkit-examples' (git://code.qt.io/qt/qtwebkit-examples.git) registered for path 'qtwebkit-examples'
Submodule 'qtwebsockets' (git://code.qt.io/qt/qtwebsockets.git) registered for path 'qtwebsockets'
Submodule 'qtwinextras' (git://code.qt.io/qt/qtwinextras.git) registered for path 'qtwinextras'
Submodule 'qtx11extras' (git://code.qt.io/qt/qtx11extras.git) registered for path 'qtx11extras'
Submodule 'qtxmlpatterns' (git://code.qt.io/qt/qtxmlpatterns.git) registered for path 'qtxmlpatterns'
+ git config commit.template /opt/qt5/.commit-template
+ git clone --branch 5.5 git://code.qt.io/qt/qt3d.git qt3d
Cloning into 'qt3d'...
remote: Counting objects: 46884, done.
remote: Compressing objects: 100% (15325/15325), done.
Receiving objects: 100% (46884/46884), 60.62 MiB | 1.35 MiB/s, done.
remote: Total 46884 (delta 35804), reused 39982 (delta 31176)
Resolving deltas: 100% (35804/35804), done.
+ git config commit.template /opt/qt5/qt3d/../.commit-template
+ git config remote.gerrit.url ssh://codereview.qt-project.org/qt/qt3d.git
+ git config remote.gerrit.fetch +refs/heads/*:refs/remotes/gerrit/* /heads/
+ git clone --branch 5.5 git://code.qt.io/qt/qtactiveqt.git qtactiveqt
Cloning into 'qtactiveqt'...
remote: Counting objects: 3930, done.
remote: Compressing objects: 100% (1586/1586), done.
remote: Total 3930 (delta 2410), reused 3567 (delta 2240)
Receiving objects: 100% (3930/3930), 1.24 MiB | 1.01 MiB/s, done.
Resolving deltas: 100% (2410/2410), done.
+ git config commit.template /opt/qt5/qtactiveqt/../.commit-template
+ git config remote.gerrit.url ssh://codereview.qt-project.org/qt/qtactiveqt.git
+ git config remote.gerrit.fetch +refs/heads/*:refs/remotes/gerrit/* /heads/
+ git clone --branch 5.5 git://code.qt.io/qt/qtandroidextras.git qtandroidextras
Cloning into 'qtandroidextras'...
remote: Counting objects: 727, done.
remote: Compressing objects: 100% (383/383), done.
```

It stays with this output for hours, I tested these steps in the host and it works.
## Docker version`:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```
## Docker info :

```
Containers: 2
Images: 76
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 80
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-34-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.56 GiB
Name: theworldofshadows
ID: TJSO:HL66:IW2X:5N4S:VJIE:X76B:IY5L:TDHB:SBXG:67ZJ:USZS:FVU3
Username: theshadowx
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
## uname -a :

```
Linux theworldofshadows 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
## Environment details

```
Laptop alienware m17x R4 
```
## How reproducible:

```
$ docker pull resin/rpi-raspbian:wheezy
$ docker run -it -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static resin/rpi-raspbian:wheezy bash
$ apt-get update
$ apt-get upgrade -y
$ sudo apt-get install libfontconfig1-dev libdbus-1-dev libfreetype6-dev libudev-dev libicu-dev libsqlite3-dev libxslt1-dev libssl-dev libasound2-dev libavcodec-dev libavformat-dev libswscale-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev gstreamer-tools gstreamer0.10-plugins-good gstreamer0.10-plugins-bad libraspberrypi-dev libpulse-dev libx11-dev libglib2.0-dev libcups2-dev freetds-dev libsqlite0-dev libpq-dev libiodbc2-dev libmysqlclient-dev firebird-dev libpng12-dev libjpeg62-dev libgst-dev libxext-dev libxcb1 libxcb1-dev libx11-xcb1 libx11-xcb-dev libxcb-keysyms1 libxcb-keysyms1-dev libxcb-image0 libxcb-image0-dev libxcb-shm0 libxcb-shm0-dev libxcb-icccm4 libxcb-icccm4-dev libxcb-sync0 libxcb-sync0-dev libxcb-render-util0 libxcb-render-util0-dev libxcb-xfixes0-dev libxrender-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-glx0-dev libxi-dev libdrm-dev
$ cd /opt
$ git clone git://code.qt.io/qt/qt5.git
$ cd qt5
$ git checkout 5.5
$ ./init-repository
```
## Additional info:

this problem happened also in Docker 1.6

**Comment by theshadowx** [comment] 2015-09-14 17:30
## Workaround
As workaround, I made the git operations in the host and then when I ran the container I bound the folder containing Qt to /data and then copy the folder to /opt.

**Comment by gabm** [comment] 2017-05-31 07:52
Hey @theshadowx, did you find any solution for your problem? We experience a similar problem which is quite annoying :/ Unfortunately there are almost no resources in the web about this particular setup of arm + git.. in our case we have a qemu-aarch64, so it comes up there as well

**Comment by thaJeztah** [comment] 2017-05-31 11:57
I think this is indeed quite a corner-case situation with qemu et all, I'm closing this issue for that reason, but don't let me stop you continuing the discussion here 👍

**Closed by thaJeztah** 2017-05-31 11:57 UTC
Labels: version/1.8

**Comment by theshadowx** [comment] 2017-05-31 20:16
@gabm Unfortunately no, but I haven't on it since then.
I have just used the workaround I proposed.

**Comment by gabm** [comment] 2017-05-31 21:28
I thought so, just wrote you because its the only obvious source in the web that describes a similar problem.. We'll file a bug report in qemu as we could reproduce it on several systems now, even with the latest release. But I don't have too much hope though.. we couldn't really get any meaningful logs after all...

**Comment by xabarass** [comment] 2017-11-22 00:09
Hey, any luck with solving this issue? I have the same problem, git clone just hangs when run in qemu emulated environment. Interesting thing is that it doesn't happen every time on my setup.
