### ISSUE TITLE
Recover from error with pull of large image

### ISSUE THREAD

**Issue by marcpawl** [moby/moby#41305] opened 2020-08-01 16:11 UTC
Docker pull large image from Private registry, EOF error #37751

When the large image pull fails, the attempt to download starts all over from byte zero vs starting from the location that it ran into problems.

Which means that it tries repeatedly and then keeps failing.
Also consuming large quantities of band width.

**Comment by thaJeztah** [comment] 2020-08-03 07:54
Looks like a duplicate of https://github.com/moby/moby/issues/20862 and https://github.com/moby/moby/issues/4872, so let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2020-08-03 07:54 UTC
Labels: area/distribution, kind/enhancement
