### ISSUE TITLE
docker export container changes files ownership/groupship to root

### ISSUE THREAD

**Issue by ezplanet** [moby/moby#46249] opened 2023-08-16 19:04 UTC
### Description

When I export a container with
```
# docker export mycontainer -o mycontainer.tar
```

the ownership of the files is changed to root.

For example I have a container running postfix that in turns requires to run under its own user ID, also there are executables using setgid. When I backup the container using docker export as above and then I restore the image (or tar xpf the exported tar file), I find that every file that is supposed to belong to postfix was changed to root ownership, therefore the container created from the restored image is thus corrupted and postfix fails to start.

The last time an export was created correctly it was 29/07/2023, after that my Ubuntu 22.04.3 LTS distribution received a few updates and I found that backups created after have the ownership of postfix files changed to root.

This is a new issue that I have just discovered, and that I traced back as happening sometime after the 29/06/2023. Containers backups exported on or prior to this date have the correct file ownership. Sometimes after this date (the first recorded occurrence is on 6/8/2023) container exports no longer maintain their original uid and gid that are set too root.

### Reproduce

1.  create a new container and install postfix for example or any other service that requires to run under its own onwership
2. export the container with docker export mycontainer -o mycontainer.tar
3. untar the produced file with tar xpf mycontainer.tar
4. check that the file owned by a given user still have their original ownership.

### Expected behavior

The container's files exported with docker export should maintain their original user ID and group ID.

### docker version

```bash
Client:
 Version:           20.10.25
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.25-0ubuntu1~22.04.1
 Built:             Fri Jul 14 21:58:09 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.25-0ubuntu1~22.04.1
  Built:            Thu Jun 29 21:21:05 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:
 runc:
  Version:          1.1.7-0ubuntu1~22.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.25
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-79-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.28GiB
 Name: levante
 ID: ORRH:Z6FU:SC6U:PFZ7:UDAU:YWBS:3X7H:QG6I:BMJW:EIX7:N5UL:2NOK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Running on Ubuntu server 22.04.3 LTS

**Comment by thaJeztah** [comment] 2023-08-16 20:16
This looks like a duplicate of https://github.com/moby/moby/issues/46161, which is a bug in the packages created by Canonical / Ubuntu;

> This bug is being tracked at https://bugs.launchpad.net/ubuntu/+source/docker.io-app/+bug/2029523 . A fix was committed on 8/11.

If possible, I'd recommend using the official packages from download.docker.com (see https://docs.docker.com/engine/install/ubuntu), and a current version of the engine (24.0.x). 

I'll close this ticket as this is not a bug in the upstream source code, but feel free to continue the conversation.

**Closed by thaJeztah** 2023-08-16 20:16 UTC
Labels: version/20.10

**Comment by ezplanet** [comment] 2023-08-17 09:00
I removed docker.io package and dependencies distributed with Ubuntu Server 22.04.3 LTS and installed docker-ce (and dependencies). The issue was resolved. I will continue to use the official packages. Thank you.
