### ISSUE TITLE
Cannot Use & To Chain Steps in Dockerfile in Windows Server 1803 (RS4)

### ISSUE THREAD

**Issue by vikalyan** [moby/moby#37253] opened 2018-06-09 03:45 UTC
**Description**

We have existing `Dockerfile`s that use `&` character to chain command invocations. The simplest example is the following:

```
# escape=`
FROM microsoft/dotnet-framework:3.5-sdk-windowsservercore-1803

ENV COMPLUS_NGenProtectedProcess_FeatureEnabled=0
ENV COMPlus_TieredCompilation=1

RUN "DISM.EXE /Online /Cleanup-Image /CheckHealth"

ADD "https://download.microsoft.com/download/5/F/E/5FE505D0-E753-4F1A-B8D6-D9E73C0C28C7/NDP472-DevPack-ENU.exe" C:\netfx472ndp.exe 

RUN C:\netfx472ndp.exe /q & exit 0
    
RUN C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ngen update & `
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen update  & `
    exit 0
```

In Windows Server 1709 (RS3) and  prior versions, this `Dockerfile` will build as expected. 

On Windows Server 1803 (RS4) the same `Dockerfile` produces the following error:

```
At line:1 char:98
+ ... ogressPreference = 'SilentlyContinue'; C:\netfx472ndp.exe /q & exit 0
+                                                                  ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
   ception
    + FullyQualifiedErrorId : AmpersandNotAllowed
``` 

**Steps to reproduce the issue:**

1. Save the contents to a `Dockerfile`.
2. Execute ` docker build -m 8g -f .\DockerFile --no-cache --squash --force-rm .`
3. This will fail when the step where `&` is used.

**Describe the results you received:**

See above.

**Describe the results you expected:**

The `Dockerfile` should build correctly. Alternatively, there should be clear documentation on what needs to be done to enable use of chained commands in a single `RUN` instruction.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       17.06.2-ee-11
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    06fc007
 Built: Thu May 17 06:14:39 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-11
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   06fc007
  Built:        Thu May 17 06:17:26 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 55
Server Version: 17.06.2-ee-11
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 64GiB
Name: vikalyan-rs4tst
ID: S6M6:RE64:NLE3:DIPJ:ZJY6:DVQM:TRBR:LFOV:WQ6U:IYGI:UWXL:ZK37
Docker Root Dir: F:\DockerData
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2018-06-09T03:44:39.3303717Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details**

Fresh installation of Windows Server 1803 RS4 using a D16s_v3  Azure instance.

The guidance provided in the error does not work either. See output below:

````
Step 9/26 : RUN C:\netfx472ndp.exe /q "&" exit 0
 ---> Running in 01568107461a
At line:1 char:98
+ ... ogressPreference = 'SilentlyContinue'; C:\netfx472ndp.exe /q & exit 0
+                                                                  ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
   ception
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

**Comment by vikalyan** [comment] 2018-06-09 03:48
@jhowardmsft @patricklang @jstarks

**Comment by thaJeztah** [comment] 2018-06-09 04:05
This is expected; the image you're using is using PowerShell as a shell (not Bash, or a Linux Shell). The error is coming from PowerShell; https://social.technet.microsoft.com/Forums/windowsserver/en-US/7ac106e6-0b7e-4425-89d4-8e86d948f716/ampersand-not-allowed-the-amp-operator-is-reserved-for-future-use?forum=winserverpowershell

Closing this issue, because this is not a bug in the code in this repository, but feel free to continue the conversation

**Closed by thaJeztah** 2018-06-09 04:05 UTC
Labels: area/builder, platform/windows
