### ISSUE TITLE
intermittent docker push error 'unknown blob' 

### ISSUE THREAD

**Issue by tomek-cz** [moby/moby#36823] opened 2018-04-10 11:06 UTC
**Description**

As a part of pipeline, docker push is run pretty frequently, and occasionally (once per week) this ends with 'unknown blob' error.

**Steps to reproduce the issue:**
1. create a small image based on scratch (tiny image)
2. push the image with 'docker push'

**Describe the results you received:**
09-Apr-2018 05:40:02	+ docker --debug --log-level debug push myregistry:8888/docker-push-test:latest
09-Apr-2018 09:40:02	The push refers to a repository [myregistry:8888/docker-push-test]
09-Apr-2018 09:40:02	1630e5123c37: Preparing
09-Apr-2018 09:40:03	1630e5123c37: Pushed
09-Apr-2018 09:40:04	unknown blob   

The server-side logs show (I've parsed them with some python script to just show useful http request and reponse)
```
2018-04-09T09:40:02Z response completed (200) GET /v2/
2018-04-09T09:40:02Z response completed (202) POST /v2/docker-push-test/blobs/uploads/
2018-04-09T09:40:02Z response completed (202) PATCH /v2/docker-push-test/blobs/uploads/4846f762-040e-4b0f-845c-591ed135f8a2?_state=l-zmFONpksZguTbXo9rQBAKANhJzTQLqVZAY-RgSTaV7Ik5hb
WUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6IjQ4NDZmNzYyLTA0MGUtNGIwZi04NDVjLTU5MWVkMTM1ZjhhMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowMi41NTc1MDE3ODdaIn0%3D
2018-04-09T09:40:03Z response completed (201) PUT /v2/docker-push-test/blobs/uploads/4846f762-040e-4b0f-845c-591ed135f8a2?_state=OAmxXQdVPtrkNi_V7BxCoAX3CK8-b87bZxp1MciQd6F7Ik5hbWU
iOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6IjQ4NDZmNzYyLTA0MGUtNGIwZi04NDVjLTU5MWVkMTM1ZjhhMiIsIk9mZnNldCI6MTMxLCJTdGFydGVkQXQiOiIyMDE4LTA0LTA5VDA5OjQwOjAyWiJ9&digest=sha256%3A75c67c2af1
2e9460e33b2221eadb109f3771e9f0e7da47c6389ded5473d6ea4c
2018-04-09T09:40:03Z response completed (307) HEAD /v2/docker-push-test/blobs/sha256:75c67c2af12e9460e33b2221eadb109f3771e9f0e7da47c6389ded5473d6ea4c
2018-04-09T09:40:03Z response completed with error (404) HEAD /v2/docker-push-test/blobs/sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8
2018-04-09T09:40:03Z response completed (202) POST /v2/docker-push-test/blobs/uploads/
2018-04-09T09:40:03Z response completed (202) PATCH /v2/docker-push-test/blobs/uploads/bb7429e8-156a-4b1c-b253-a92df900c4b7?_state=54wHRsVUcLzDByKTlo7_pIrZ0SMKri4TKfA0Ib_JONx7Ik5hb
WUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6ImJiNzQyOWU4LTE1NmEtNGIxYy1iMjUzLWE5MmRmOTAwYzRiNyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowMy40MTk1NjAzOTFaIn0%3D
2018-04-09T09:40:04Z response completed (201) PUT /v2/docker-push-test/blobs/uploads/bb7429e8-156a-4b1c-b253-a92df900c4b7?_state=j_FYLXCkTGlalWfw4cO9j1r36kX3wPggLCwZmOHdQbB7Ik5hbWU
iOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6ImJiNzQyOWU4LTE1NmEtNGIxYy1iMjUzLWE5MmRmOTAwYzRiNyIsIk9mZnNldCI6MTUyNSwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowM1oifQ%3D%3D&digest=sha256%3A12
318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8
2018-04-09T09:40:04Z response completed with error (404) HEAD /v2/docker-push-test/blobs/sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8
```
regular logs (non-parsed)
```
Apr  9 09:40:02 registry-internal journal: time="2018-04-09T09:40:02Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=be038020-94da-4c26-b1f3-e45c4af80fe5 http.request.method=GET http.request.remoteaddr="x.x.x.x:40250" http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.285472ms http.response.status=200 http.response.written=2 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:02 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:02 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:02 registry-internal journal: time="2018-04-09T09:40:02Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=9d2a090f-0950-4018-82b5-a9bb3a8c5a81 http.request.method=POST http.request.remoteaddr="x.x.x.x:40252" http.request.uri="/v2/docker-push-test/blobs/uploads/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.duration=49.540852ms http.response.status=202 http.response.written=0 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:02 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:02 +0000] "POST /v2/docker-push-test/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:02 registry-internal journal: time="2018-04-09T09:40:02Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=f28efa16-2b5e-4cb0-9c07-c95cfda189db http.request.method=PATCH http.request.remoteaddr="x.x.x.x:40254" http.request.uri="/v2/docker-push-test/blobs/uploads/4846f762-040e-4b0f-845c-591ed135f8a2?_state=l-zmFONpksZguTbXo9rQBAKANhJzTQLqVZAY-RgSTaV7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6IjQ4NDZmNzYyLTA0MGUtNGIwZi04NDVjLTU5MWVkMTM1ZjhhMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowMi41NTc1MDE3ODdaIn0%3D" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.duration=83.908316ms http.response.status=202 http.response.written=0 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:02 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:02 +0000] "PATCH /v2/docker-push-test/blobs/uploads/4846f762-040e-4b0f-845c-591ed135f8a2?_state=l-zmFONpksZguTbXo9rQBAKANhJzTQLqVZAY-RgSTaV7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6IjQ4NDZmNzYyLTA0MGUtNGIwZi04NDVjLTU5MWVkMTM1ZjhhMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowMi41NTc1MDE3ODdaIn0%3D HTTP/1.1" 202 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:03 registry-internal journal: time="2018-04-09T09:40:03Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=d5a279e7-3763-40f5-ae46-3531ed37e74c http.request.method=PUT http.request.remoteaddr="x.x.x.x:40256" http.request.uri="/v2/docker-push-test/blobs/uploads/4846f762-040e-4b0f-845c-591ed135f8a2?_state=OAmxXQdVPtrkNi_V7BxCoAX3CK8-b87bZxp1MciQd6F7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6IjQ4NDZmNzYyLTA0MGUtNGIwZi04NDVjLTU5MWVkMTM1ZjhhMiIsIk9mZnNldCI6MTMxLCJTdGFydGVkQXQiOiIyMDE4LTA0LTA5VDA5OjQwOjAyWiJ9&digest=sha256%3A75c67c2af12e9460e33b2221eadb109f3771e9f0e7da47c6389ded5473d6ea4c" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.duration=397.394382ms http.response.status=201 http.response.written=0 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:03 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:02 +0000] "PUT /v2/docker-push-test/blobs/uploads/4846f762-040e-4b0f-845c-591ed135f8a2?_state=OAmxXQdVPtrkNi_V7BxCoAX3CK8-b87bZxp1MciQd6F7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6IjQ4NDZmNzYyLTA0MGUtNGIwZi04NDVjLTU5MWVkMTM1ZjhhMiIsIk9mZnNldCI6MTMxLCJTdGFydGVkQXQiOiIyMDE4LTA0LTA5VDA5OjQwOjAyWiJ9&digest=sha256%3A75c67c2af12e9460e33b2221eadb109f3771e9f0e7da47c6389ded5473d6ea4c HTTP/1.1" 201 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:03 registry-internal journal: time="2018-04-09T09:40:03Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=d187c7a3-1470-4c81-a293-8e9fd0625b40 http.request.method=HEAD http.request.remoteaddr="x.x.x.x:40258" http.request.uri="/v2/docker-push-test/blobs/sha256:75c67c2af12e9460e33b2221eadb109f3771e9f0e7da47c6389ded5473d6ea4c" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=76.566221ms http.response.status=307 http.response.written=0 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:03 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:03 +0000] "HEAD /v2/docker-push-test/blobs/sha256:75c67c2af12e9460e33b2221eadb109f3771e9f0e7da47c6389ded5473d6ea4c HTTP/1.1" 307 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:03 registry-internal journal: time="2018-04-09T09:40:03Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8 err.message="blob unknown to registry" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=80241ea9-c5e7-4ec4-94fc-9824323e3517 http.request.method=HEAD http.request.remoteaddr="x.x.x.x:40262" http.request.uri="/v2/docker-push-test/blobs/sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=7.887381ms http.response.status=404 http.response.written=157 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 vars.digest="sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8" vars.name=docker-push-test version=v2.4.0 
Apr  9 09:40:03 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:03 +0000] "HEAD /v2/docker-push-test/blobs/sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8 HTTP/1.1" 404 157 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:03 registry-internal journal: time="2018-04-09T09:40:03Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=e683c812-77fe-4da0-aa57-afa24fe545aa http.request.method=POST http.request.remoteaddr="x.x.x.x:40264" http.request.uri="/v2/docker-push-test/blobs/uploads/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.duration=34.452857ms http.response.status=202 http.response.written=0 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:03 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:03 +0000] "POST /v2/docker-push-test/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:03 registry-internal journal: time="2018-04-09T09:40:03Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=d3f60102-246b-4d17-9afd-b8ed08a869f8 http.request.method=PATCH http.request.remoteaddr="x.x.x.x:40266" http.request.uri="/v2/docker-push-test/blobs/uploads/bb7429e8-156a-4b1c-b253-a92df900c4b7?_state=54wHRsVUcLzDByKTlo7_pIrZ0SMKri4TKfA0Ib_JONx7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6ImJiNzQyOWU4LTE1NmEtNGIxYy1iMjUzLWE5MmRmOTAwYzRiNyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowMy40MTk1NjAzOTFaIn0%3D" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.duration=80.053549ms http.response.status=202 http.response.written=0 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:03 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:03 +0000] "PATCH /v2/docker-push-test/blobs/uploads/bb7429e8-156a-4b1c-b253-a92df900c4b7?_state=54wHRsVUcLzDByKTlo7_pIrZ0SMKri4TKfA0Ib_JONx7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6ImJiNzQyOWU4LTE1NmEtNGIxYy1iMjUzLWE5MmRmOTAwYzRiNyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowMy40MTk1NjAzOTFaIn0%3D HTTP/1.1" 202 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:04 registry-internal journal: time="2018-04-09T09:40:04Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=f993a8f7-8129-42d7-9d50-a9bfbcaf6dae http.request.method=PUT http.request.remoteaddr="x.x.x.x:40268" http.request.uri="/v2/docker-push-test/blobs/uploads/bb7429e8-156a-4b1c-b253-a92df900c4b7?_state=j_FYLXCkTGlalWfw4cO9j1r36kX3wPggLCwZmOHdQbB7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6ImJiNzQyOWU4LTE1NmEtNGIxYy1iMjUzLWE5MmRmOTAwYzRiNyIsIk9mZnNldCI6MTUyNSwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowM1oifQ%3D%3D&digest=sha256%3A12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.duration=591.468455ms http.response.status=201 http.response.written=0 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 
Apr  9 09:40:04 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:03 +0000] "PUT /v2/docker-push-test/blobs/uploads/bb7429e8-156a-4b1c-b253-a92df900c4b7?_state=j_FYLXCkTGlalWfw4cO9j1r36kX3wPggLCwZmOHdQbB7Ik5hbWUiOiJkb2NrZXItcHVzaC10ZXN0IiwiVVVJRCI6ImJiNzQyOWU4LTE1NmEtNGIxYy1iMjUzLWE5MmRmOTAwYzRiNyIsIk9mZnNldCI6MTUyNSwiU3RhcnRlZEF0IjoiMjAxOC0wNC0wOVQwOTo0MDowM1oifQ%3D%3D&digest=sha256%3A12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8 HTTP/1.1" 201 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:04 registry-internal journal: time="2018-04-09T09:40:04Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8 err.message="blob unknown to registry" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=26b8331a-c98b-410c-81fe-c2db85d1bda6 http.request.method=HEAD http.request.remoteaddr="x.x.x.x:40270" http.request.uri="/v2/docker-push-test/blobs/sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=7.96096ms http.response.status=404 http.response.written=157 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 vars.digest="sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8" vars.name=docker-push-test version=v2.4.0 
Apr  9 09:40:04 registry-internal journal: x.x.x.x - - [09/Apr/2018:09:40:04 +0000] "HEAD /v2/docker-push-test/blobs/sha256:12318ab38518d5ccf5b5b1fa0ef96eeb4576cd9dda5c2910af401b095ac896c8 HTTP/1.1" 404 157 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
Apr  9 09:40:04 registry-internal journal: time="2018-04-09T09:40:04Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="docker-registry:8888" http.request.id=033afcc5-5d75-431c-a130-540648edcd97 http.request.method=GET http.request.remoteaddr="x.x.x.x:40272" http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.216832ms http.response.status=200 http.response.written=2 instance.id=bd7193e3-fa83-4bf8-bb07-49c555c6a6a3 version=v2.4.0 

```

**Describe the results you expected:**
the image to be pushed successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
Only occasionally (once per week)

**Output of `docker version`:**

```
The docker host where the image is built and image pushed from:
Docker version 1.11.2, build b9f10c9
Docker hosting registry:
Docker version 1.12.6, build 85d7426/1.12.6
```

**Output of `docker info`:**
For the docker that the 'docker push' is issued from:
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 146
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-202:1-113246346-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 18.07 GB
 Data Space Total: 107.4 GB
 Data Space Available: 89.31 GB
 Metadata Space Used: 24.97 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.123 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.26 GiB
Name: myhost
ID: DLF2:NHOU:4IQC:BATN:VEVY:3KTH:MC7Q:XMHJ:T35T:JDN3:EMRT:ZDOY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS for all nodes 
S3 to store registry images

**Comment by danp60** [comment] 2019-03-26 06:56
Were you able to find a solution to this problem? I'm seeing similar intermittent issues and can't figure out whats going on.

**Comment by mneeharika** [comment] 2020-06-22 19:21
@tomek-cz , @danp60 , Did you find a way to get past this? We are also facing an intermittent issue during docker build/push with exception - dockerClientException: Could not build image: unknown blob.

**Comment by danp60** [comment] 2020-06-23 02:51
@mneeharika I never found a solution. Just retried with backoff to work around it 🤷

**Comment by mneeharika** [comment] 2020-06-23 09:37
Ok, thanks for the quick response @danp60 .

**Comment by thaJeztah** [comment] 2020-06-23 09:40
This issue was originally reported over 2 years ago, with (at least by now) a very old version of Docker that's no longer maintained. 

Looking at the error logs, the issue seems to be / could be on the registry side, not in the docker daemon (in which case it'd be better reported in the https://github.com/docker/distribution issue tracker). Unfortunately without a reproducible case, it will be difficult to look into this.

I'll close this issue for reasons above, but feel free to continue the conversation. If you have a  way to reproduce this issue and exact steps to reproduce, feel free to open a new ticket with those steps (and details that are requested in the issue template).

**Closed by thaJeztah** 2020-06-23 09:40 UTC
Labels: area/distribution, version/1.11
