### ISSUE TITLE
Cannot install systemd and upstart dependent packages using Dockerfile

### ISSUE THREAD

**Issue by LoveIsGrief** [moby/moby#31771] opened 2017-03-12 22:27 UTC
**Description**

For my project LoveIsGrief/videojs-soundcloud#21 I was trying to build a Dockerfile that installed all necessary packages in order to be as similar to travis-ci as possible (using their docker image as described [here](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image)). With this simpler Dockerfile, I run into problems

```Dockerfile
FROM travisci/ci-amethyst:packer-1487189177
RUN apt-get install pulseaudio -y
CMD /sbin/init
```

The `RUN` command is actually just part of a script I generate from the commands in `.travis.yml`. That's the one that fails.

**Steps to reproduce the issue:**
1. Use the Dockerfile above
2. `docker build --force-rm --tag vjs-soundcloud .`

**Describe the results you received:**

```
Setting up libpam-systemd:amd64 (204-5ubuntu20.24) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
invoke-rc.d: unknown initscript, /etc/init.d/systemd-logind not found.
dpkg: error processing package libpam-systemd:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 100
dpkg: dependency problems prevent configuration of policykit-1:
 policykit-1 depends on libpam-systemd; however:
  Package libpam-systemd:amd64 is not configured yet.

dpkg: error processing package policykit-1 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of pulseaudio:
 pulseaudio depends on libpam-systemd; however:
  Package libpam-systemd:amd64 is not configured yet.

dpkg: error processing package pulseaudio (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of pulseaudio-module-x11:
 pulseaudio-module-x11 depends on pulseaudio; however:
  Package pulseaudio is not configured yet.

dpkg: error processing package pulseaudio-module-x11 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because MaxReports is reached already
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 libpam-systemd:amd64
 policykit-1
 pulseaudio
 pulseaudio-module-x11
E: Sub-process /usr/bin/dpkg returned an error code (1)
Removing intermediate container f40c284b716b
The command '/bin/sh -c apt-get install pulseaudio -y' returned a non-zero code: 100
```

**Describe the results you expected:**

`pulseaudio` to be installed

**Additional information you deem important (e.g. issue happens only occasionally):**

As described on [travis's page](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image) running the image with `docker run --name travis-debug -dit quay.io/travisci/travis-ruby /sbin/init` allows an install of `pulseaudio`. 

Therefore a possible solution would be to run `/sbin/init` as the **CMD** for the temporary containers used to execute the `RUN`. I already tried `RUN /sbin/init` and that just failed and `RUN /sbin/init &` didn't help either.

**Output of `docker version`:**

```
Docker version 17.03.0-ce, build 3a232c8
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 41
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-38-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.72 GiB
Name: loneliverse
ID: BJ7I:XJEO:CWT2:K7D2:J4JA:VTL5:PQYX:BL5C:6Q57:S2O5:GNI6:J2ET
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by joarleymoraes** [comment] 2017-11-10 12:22
+1

**Comment by thaJeztah** [comment] 2017-12-04 04:44
Looks like the pulseaudio installer is attempting to install `libpam-systemd`, which attempts to connect to an init system. Containers are not VM's so there's no init system running, only the process you start (in this case, just a shell that runs the install, but nothing else).

Possibly this Dockerfile could help finding out how to install these packages without running into this issue; https://github.com/jessfraz/dockerfiles/blob/master/pulseaudio/Dockerfile

This is not a bug, so I'm closing this issue

Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Closed by thaJeztah** 2017-12-04 04:44 UTC
Labels: area/builder
