### ISSUE TITLE
Bind mounted secrets only updates with length of binded file

### ISSUE THREAD

**Issue by carlioth** [moby/moby#33602] opened 2017-06-09 06:58 UTC
**Description**

This was initially created here: https://github.com/docker/compose/issues/4908#issuecomment-307203724 with the the comment: 
> That's definitely an engine bug. Please report it on the moby/moby repo!

After I run docker-compose and my secrets has been bind mounted to /run/secrets, if I then update the bound file on my disk the file in the container only change to the length of the change I did. Example below:

**Steps to reproduce the issue:**
1. docker-compose up -d
2. docker exec -it container bash
3. cd /run/secrets
3. cat mysecret, will print 123456789
4. Change mysecret file on disk to ABC
5. cat mysecret, will now print 123

**Describe the results you received:**
The secret file doesn't change it's content, only it's length corresponding to the bound file.

**Describe the results you expected:**
Not sure in the context of bind mounted secrets, but I expect one of the two scenarios: 
- Either that the bound file didn't follow the changes made.
- That the file get's updated with the bound file.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 156
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 660
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: A6KM:WMON:AWPO:DLVL:XBRH:PWIP:HVCW:3AST:VTKD:AGFB:PMGK:2TKW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cpuguy83** [comment] 2017-06-09 12:54
What are bind-mounted secrets? Secrets would not be supported on compose unless it's doing something funky since these are swarm-specific.

ping @shin-

**Comment by thaJeztah** [comment] 2017-06-09 13:04
I think on docker-compose they are implemented by bind-mounting local files. Secrets should be immutable though (like with actual secrets in swarm mode), so editing the file on the host is not something that's really supported

**Comment by shin-** [comment] 2017-06-09 16:41
Yes, we emulate them using fairly regular bind mounts into the /run/secrets folder. I'm assuming the problem lies somewhere there, but I admit I haven't looked too much into it.

**Comment by thaJeztah** [comment] 2017-08-17 15:07
Looks like the problem is in docker-compose after all, so let me close this one here (ping me if incorrect @shin- )

**Closed by thaJeztah** 2017-08-17 15:07 UTC
Labels: version/17.03
