### ISSUE TITLE
Does docker support direct transfer mirrors to the storage system without going through the docker distribution?

### ISSUE THREAD

**Issue by xiongkun01** [moby/moby#40071] opened 2019-10-11 03:39 UTC
Does docker support direct transfer mirrors to the storage system without going through the Docker distribution？

**Comment by thaJeztah** [comment] 2019-12-27 15:57
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug report, but feel free to continue the conversation

**Closed by thaJeztah** 2019-12-27 15:57 UTC
Labels: kind/question
