### ISSUE TITLE
Privileged execution of nsenter does not allow changes to the file system

### ISSUE THREAD

**Issue by Ageraluon** [moby/moby#37161] opened 2018-05-27 12:37 UTC
**Description**
I am trying to mount CIFS shares with specific file permissions into the moby vm by running a privileged container from a windows host. (Described here: https://github.com/docker/for-win/issues/2042)

For this, the following approach seems feasible to me: https://hub.docker.com/r/irobie/moby-cifs-mount/. I am trying to reproduce being able to access the vm from a privileged container, mount a CIFS network share manually and access that share from another non-privileged external container.

When trying to modify the vm's file system however, access is denied in spite of executing from a privileged container

**Steps to reproduce the issue:**
1. from a windows host, run  `docker run -it --rm --privileged --pid=host alpine`
2. in the shell, run `apk update && apk add util-linux` in order to install nsenter
3. run `nsenter -t 1 -m -u -i -n sh -c "apk update"` in order to try and access the vm filesystem

**Describe the results you received:**

apk update does not have any access rights to the vm:

> ERROR: Unable to lock database: Read-only file system
> ERROR: Failed to open apk database: Read-only file system

**Describe the results you expected:**

I hope to be able to successfully run the command used in the start script from the abovementioned docker hub contribution:

`nsenter -t 1 -m -u -i -n sh -c " \
    apk update && \
    apk add inotify-tools && \
    mkdir -p $MOUNT && \
    (umount $MOUNT || /bin/true) && \
    mount -t cifs $SERVER $MOUNT -o $OPTIONS && \
    inotifywait -m $MOUNT \
    "`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 23
 Running: 7
 Paused: 0
 Stopped: 16
Images: 66
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d89013c
ID: 4VMA:4DBW:ZMLZ:IICS:U6KZ:FRNH:2CYB:IJ2G:4XO4:Z6RV:PUBV:OZJD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 64
 Goroutines: 110
 System Time: 2018-05-27T12:35:42.3018791Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-05-27 13:16
This is expected; the VM used by Docker for Windows and Docker for Mac is not intended to be tinkered with, and uses a readonly filesystem;

```bash
docker run -it --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i mount  

/dev/sr0 on / type iso9660 (ro,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=204668k,mode=755)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime,size=204668k)
tmpfs on /var type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1023328k,mode=755)
dev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=10240k,nr_inodes=248418,mode=755)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
....
```

closing, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-05-27 13:16 UTC
Labels: platform/desktop

**Comment by Ageraluon** [comment] 2018-05-27 20:58
@thaJeztah: Thank you for the clarification!

For mounting an external cifs volume, creating a folder anywhere inside the linux vm and mounting the share into it would suffice. What options do I have in order to accomplish that, if any? How are external volumes mounted into the vm from the windows host into a read-only filesystem? 

Thank you also for the pointer. Would I be able to create a mount somewhere in /dev or /proc for example? What nomenclature should I choose in order to not interfere with the 'normal' mounts or operations? 

The whole effort is done in order to be able to mount the share with a specific set of uid:gid/permissions that some linux containers require. Since /dev exists with a mode=755 option, would all mounts in /dev automatically have the same permission set?

Thank you for the input!

**Comment by Ageraluon** [comment] 2018-05-27 21:13
Furthermore, in order for this to work, I'd need to install the cifs-utils for the mount command to process windows shares properly. Is there anything of this sort already available on the moby vm?

**Comment by thaJeztah** [comment] 2018-05-28 12:17
For the actual mounting, there's no need to use nsenter. You can create a volume, and use the `--opt` to pass `mount` options; for example (from https://github.com/moby/moby/issues/28809#issuecomment-263577907);

```
docker volume create --opt type=nfs --opt device=:/foo --opt o=addr=1.2.3.4,rsize=1024,wsize=1024
```

So in your case, that would be something like;

```bash
docker volume create \
  --opt type=cifs \
  --opt device=//Server/Testvolume \
  --opt o=username=Testuser,password=Testpassword,file_mode=0777,dir_mode=077 \
  myvolume
```

However (as you noticed); this depends on what's available on the daemon host; `cifs` is not available in the Moby/LinuxKit VM, so you won't be able to use that.

**Comment by Ageraluon** [comment] 2018-05-28 20:34
@thaJeztah, thank you for your answer, this helps a lot!
To that I would still very much like to ask a couple questions if you don't mind:
- Would it be possible to add cifs capability to the moby vm in the docker for windows build?
- is that syntax with the --opt parameters valid on docker for windows? Or do you mean to execute 'docker volume create' in the moby vm/the privileged container in some form?
- If need be, it might be possible to work around the cifs restriction by emulating an nfs server on Windows:
  (http://blog.bobbyallen.me/2018/01/18/windows-server-2016-as-an-nfs-server-for-linux-clients/). I'll investigate further into this.

**Comment by Ageraluon** [comment] 2018-05-28 20:56
From: https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options

> The built-in local driver on Windows does not support any options.

That means the standard 'docker volume create' option can not be used in this scenario here, correct?

**Comment by thaJeztah** [comment] 2018-05-28 21:06
> Would it be possible to add cifs capability to the moby vm in the docker for windows build?

Good question; I'm not on the Docker for Desktop team, I wonder though if it's fixing the permissions issue, given that the files on your _Windows_ hosts still wouldn't be able to preserve those permissions (I think).

> is that syntax with the --opt parameters valid on docker for windows? Or do you mean to execute 'docker volume create' in the moby vm/the privileged container in some form?

The syntax should be valid on Docker for Windows, but (as mentioned), basically passes those options on to `mount` inside the VM, so depends on what's available there

> If cifs is not supported by moby, how does docker for windows mount volumes? Is there a different mechanism than CIFS/Samba that I could use here?

hm, not sure how it's set up; perhaps @rn can answer that 😅 

> That means the standard 'docker volume create' option can not be used in this scenario here, correct?

That section refers to "native Windows containers" on Windows (i.e., when you're running Windows containers on a Windows machine), in which case there's no "moby" VM, and the daemon runs directly on the Windows host.

**Comment by Ageraluon** [comment] 2018-05-28 22:28
> Good question; I'm not on the Docker for Desktop team, I wonder though if it's fixing the permissions issue, given that the files on your Windows hosts still wouldn't be able to preserve those permissions (I think).

That is fine with me, I am actually not as much concerned with permission preservation but more about the appearance inside linux containers. Currently on Docker for Windows, all files mounted via standard bind mount (docker run -v) are assigned UID 0 : GID 0 755 unix file permissions, which cannot be changed.
Since many linux docker projects involve processes that need file permissions to be changed, these projects cannot be run on a windows host without severe modifications. An example would be the apache server (also nextcloud, gitlab, ...) whose main processes are not allowed to be executed as root (at least not in the configuration you can pull from Docker hub), but if you run them as non-root they would not have access to shares that are mounted with the standard permission set of a volume on Docker for Windows (UID:0, GID:0, 755). That essentially makes it impossible for me to run most standard linux containers out of the box with files persisted in volumes.

> The syntax should be valid on Docker for Windows, but (as mentioned), basically passes those options on to mount inside the VM, so depends on what's available there

> That section refers to "native Windows containers" on Windows (i.e., when you're running Windows containers on a Windows machine), in which case there's no "moby" VM, and the daemon runs directly on the Windows host.

Thank you! I have not gotten this detail from the documentation. My understanding when reading was that the two drivers for Docker for Windows and Docker for Linux (standard docker) were referred to...

I've tried this syntax, and indeed the options are passed on to the mount command 👍 !
However, I am getting the following error when actually using that volume in a docker container:

```
docker volume create --opt type=cifs --opt device=//SERVER/Testvolume --opt o=username=Testuser,pas
sword=Testpassword,file_mode=0777,dir_mode=077 myvolume
```

> myvolume

`docker run -it --rm -v myvolume:/myvolume ubuntu /bin/bash`

> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/myvolume/_data': error while mounting volume with options: type='cifs' device='//SERVER/Testvolume' o='username=Testuser,password=Testpassword,file_mode=0777,dir_mode=077': invalid argument.

**Comment by rn** [comment] 2018-05-29 09:17
@Ageraluon it's a little more complicated than `nsenter`. `nsenter` get's you into the LinuxKit root namespace, which has a read-only filesystem so you won't be able to do much there. `dockerd` is actually running inside a `containerd` container. Too get there, first do something like:

```
docker run --rm -it --privileged --pid=host justincormack/nsenter1
```
This get's you into the LinuxKit root namespace, then:
```
 ctr -n services.linuxkit task exec -t --exec-id foo /bin/sh
```

This get's you into the container where `dockerd` is running. There you'll find that `mount.cifs` is available and you can start debugging the mount command.

**Comment by thaJeztah** [comment] 2018-05-29 09:59
To add a bit of information; when using the default (local) volume driver, `--opt type` is passed as `fstype`, and every `--opt o=` is passed as-is to Linux mount;

- volume [`Create()`](https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/volume/local/local.go#L178-L180) writes the options to a file in [`setOpts()`](https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/volume/local/local_unix.go#L58-L90)
- when mounting the volume ([`Mount()`](https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/volume/local/local.go#L316-L331) -> [`mount()`](https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/volume/local/local_unix.go#L74-L90)) , those options are passed through to the [`pkg/mount`](https://github.com/moby/moby/blob/53982e3fc1642f2605189cea48bc6de7b9318611/pkg/mount/mount.go#L66-L87) package,
- and used as options for `unix.Mount()`: https://github.com/moby/moby/blob/53982e3fc1642f2605189cea48bc6de7b9318611/pkg/mount/mounter_linux.go#L30-L53

**Comment by Ageraluon** [comment] 2018-05-29 22:20
Thank you @rn and @thaJeztah , that is exactly what I need! I really appreciate your support.

Using
` ctr -n services.linuxkit task exec -t --exec-id foo docker-ce /bin/sh`

Works for me and `mount.cifs` answers.

When creaing a volume using 

`docker volume create --opt type=cifs --opt device=//Someserver/Testvolume --opt o=username=Testuser,password=Testpassword,file_mode=0777,dir_mode=077 myvolume`

The opts.json created here: https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/volume/local/local.go#L186 does not show anything out of the ordinary:

`{"MountType":"cifs","MountOpts":"username=Testuser,password=Testpassword,file_mode=0777,dir_mode=0777","MountDevice":"//Someserver/Testvolume"}`

When running a container with that volume mounted using:

 `docker run -it --rm -v myvolume:/myvolume ubuntu /bin/bash`
 
 docker returns
 
 `Error response from daemon: error while mounting volume '/var/lib/docker/volumes/myvolume/_data': error while mounting volume with options: type='cifs' device='//Someserver/Testvolume' o='': invalid argument.`

Then

`tail /var/log/docker-ce.err.log`

shows the following:

```text
time="2018-05-29T19:30:22.122177400Z" level=debug msg="Revoking external connectivity on endpoint elegant_knuth (1450725bdd4bea100f68c5e0c39ddd73a596f3559a8cad9456e84b1ed7c7027d)"
time="2018-05-29T19:30:22.122193600Z" level=debug msg="Closing buffered stdin pipe"
time="2018-05-29T19:30:22.122851400Z" level=debug msg="DeleteConntrackEntries purged ipv4:0, ipv6:0"
time="2018-05-29T19:30:22.304591200Z" level=debug msg="Releasing addresses for endpoint elegant_knuth's interface on network bridge"
time="2018-05-29T19:30:22.304635300Z" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.4)"
time="2018-05-29T19:30:22.304659100Z" level=debug msg="Received set for ordinal 4, start 0, end 0, any false, release true, serial:false curr:5 \n"
time="2018-05-29T19:30:22.389526200Z" level=error msg="57d23130f3661ee374faf3db30aaf8f45af0d287d5b85acf23c3ad7b6c92d3ea cleanup: failed to delete container from containerd: no such container"
time="2018-05-29T19:30:22.412324200Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: invalid argument" error_type=syscall.Errno module=api
time="2018-05-29T19:30:22.412539400Z" level=error msg="Handler for POST /v1.37/containers/57d23130f3661ee374faf3db30aaf8f45af0d287d5b85acf23c3ad7b6c92d3ea/start returned error: error while mounting volume '/var/lib/docker/volumes/myvolume/_data': error while mounting volume with options: type='cifs' device='//Someserver/Testvolume' o='username=Testuser,password=Testpassword,file_mode=0777,dir_mode=077': invalid argument"
time="2018-05-29T19:30:22.412929300Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: invalid argument" error_type=syscall.Errno module=api
```

if I check the content of ` /var/lib/docker/volumes/myvolume/_data`, it is empty.

Removing this volume, then doing a "Manual mount" with the same intended syntax:

` mount -v -t cifs -o username=Testuser,password=Testpassword,file_mode=0777,d
ir_mode=0777 //Someserver/Testvolume /var/lib/docker/volumes/myvolume/_data`

However works flawlessly, and I am able to ls the testfile I have placed in the share. file_mode/dir_mode is respected. Additional syntax, like gid=33,uid=33 works and is respected.
digging deeper...

**Comment by Ageraluon** [comment] 2018-05-29 22:34
Wow, I think I found my root cause here!

My server computer name contains a dash '-' - symbol. While the manual mount command seems to accept that, creating that volume the standard docker way and having a dash in the device name seems to create an error when actually mounting the volume.

When replacing the server name with its IP address, the process seems to work just fine 👍 

My suspicion would be something that occurs in the unix.mount go package since I have not seen any deeper content-check regarding the device name syntax in the mount package:

https://github.com/moby/moby/blob/53982e3fc1642f2605189cea48bc6de7b9318611/pkg/mount/mounter_linux.go#L35 

Unfortunately, I am not able to do a live debug here (I've installed go but lack the knowledge as of now) and see where exactly the mount process fails.

According to [https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames](url) dashes should be allowed in the hostname though.

**Comment by thaJeztah** [comment] 2018-05-29 22:38
Would it be possible that it failed to resolve the server? I known that for cifs, a small code change was done to perform a DNS lookup.

Can the server's name be resolved through DNS?

**Comment by Ageraluon** [comment] 2018-05-29 22:47
interesting, from the dockerd containter, I get the following output:

`nslookup MY-SERVER`

```
nslookup: can't resolve '(null)': Name does not resolve

Name:      MY-SERVER
Address 1: 192.168.0.27 MY-SERVER.fritz.box
Address 2: 2a02:8109:b5bf:d645:f8eb:xxxx:xxxx:xxxx
Address 3: 2a02:8109:b5bf:d645:a568:xxxx:xxxx:xxxx
```

its interesting that the name does resolve, however nslookup is throwing an error...
