### ISSUE TITLE
Support retrieve output of an exec instance in detached mode

### ISSUE THREAD

**Issue by hongbin** [moby/moby#32047] opened 2017-03-23 15:55 UTC
**Description**
If I create an exec instance in detached mode, there is no API to retrieve its output.

**Steps to reproduce the issue:**
1. POST /containers/(id or name)/exec
2. POST /exec/(id)/start
{"Detach": true}

**Describe the results you received:**
I can use the API "GET /exec/(id)/json" to inspect the status of exec instance, but I couldn't retrieve its output.

**Describe the results you expected:**
There could be an API like "GET /exec/(id)/logs" to retrieve the output of the exec instance.

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 60
 Running: 13
 Paused: 0
 Stopped: 47
Images: 97
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 268
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.5 GiB
Name: ubuntu
ID: BFVC:B5JB:GZZ6:ZS66:6GWY:NXYE:IY2V:KKUH:F6KO:ZLQP:R3JR:6SCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None

**Comment by thaJeztah** [comment] 2021-12-10 16:48
I think this is a duplicate of https://github.com/moby/moby/issues/9527. Let me close this one in favour of https://github.com/moby/moby/issues/9527, to prevent the discussion from diverging 👍

**Closed by thaJeztah** 2021-12-10 16:48 UTC
Labels: kind/feature, version/1.12
