### ISSUE TITLE
can't pull through swarm with private repo

### ISSUE THREAD

**Issue by vikstrous** [moby/moby#21004] opened 2016-03-07 20:02 UTC
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 161
 Running: 16
 Paused: 0
 Stopped: 145
Images: 499
Server Version: 1.10.2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.3-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: compooter
ID: GKSI:YHZC:YPNI:PAGO:EYPD:AYME:K6BY:BAIH:EBKQ:SOAK:WUFP:6MJM
Debug mode (server): true
 File Descriptors: 154
 Goroutines: 207
 System Time: 2016-03-07T11:51:16.419781793-08:00
 EventsListeners: 2
 Init SHA1: 9694987fb2e02dd67336521f2ba5ad9680e9b5c4
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Cluster store: etcd://172.17.0.1:12379
Cluster advertise: 172.17.0.1:12376
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

local arch machine

List the steps to reproduce the issue:
1. docker login
2. use UCP's client bundle or configure your docker client to talk to swarm
3. docker pull a private repo

Describe the results you received:
404

Describe the results you expected:
success

Provide additional info you think is important:

I'm using UCP 1.0.0

When I run docker login I get an entry for `"https://index.docker.io/v1/"` in my config file.  It looks like something changed with the config file works, so now it expects an empty host string for hub. If I change my config file auth entry to `""` it pulls successfully.

It seems like the issue is that my docker client is not populating the empty auth entry key.

Somehow when I do a pull locally instead of over UCP is works.

**Comment by dhiltgen** [comment] 2016-03-07 21:43
I believe the root cause of this is related to how the ~/.docker/config.json file gets generated.  It appears that if you have an existing/old config, and do a `docker login` using 1.10, you get a new entry for auths ""

However, if you have no existing config, and do a `docker login` with a new client, you get just an auths entry for "https://index.docker.io/v1/"

If you attempt to pull locally (through the docker.sock) this works to pull private images.  It also works to pull through a DOCKER_HOST wired to the daemon.

If you point to swarm in the middle, it does not work when the config contains only https://index.docker.io/v1/ but does work when the config contains ""


Related to that, if you have an old config.json established with 1.9 or older, pulling through swarm fails until you perform a `docker login` using a 1.10 client.

**Comment by aaronlehmann** [comment] 2016-03-07 21:59
@dhiltgen: What steps cause the `""` auths entry to be created?

I tried running `docker login` on Docker 1.8.2, then copying this config.json file to a machine running Docker 1.10 and running `docker login` again. I only see the `https://index.docker.io/v1/` entry at each step in the process (which is the only exntry I expect to see).

**Comment by dhiltgen** [comment] 2016-03-07 22:02
I'm not 100% positive, but I think it has to do with the existence of a `~/.dockercfg` file

**Comment by dhiltgen** [comment] 2016-03-07 22:03
Based on my testing so far, I can't get pulls to work through swarm **unless** I have a "" entry.  (but there are a ton of variables here, so maybe there's some other thing going on.)

**Comment by neersighted** [comment] 2023-05-12 13:39
Closing as classic Swarm is deprecated.

**Closed by neersighted** 2023-05-12 13:39 UTC
Labels: version/1.10
