### ISSUE TITLE
Mount volume with Docker ONBUILD 

### ISSUE THREAD

**Issue by saturnism** [moby/moby#12827] opened 2015-04-27 20:33 UTC
Just used Maven image to turn Java source to image on build!  Maven will downloads all the dependencies into /root/.m2/repository directory.  But since the fs is not persistent, Maven will download all the dependencies on every single build.

It would be great if we can mount the repository directory when building - so that the dependencies don't need to be re-downloaded each time.

**Comment by vdemeester** [comment] 2015-04-28 09:37
Yep, agree but not sure that's the right place for this issue. Would probably be better [here](https://github.com/docker-library/official-images) or even better, [here](https://github.com/carlossg/docker-maven/tree/d92da50e1f7fe737741a1db732a58991703d5796).

**Comment by saturnism** [comment] 2015-05-04 01:29
hm, i don't think it's the image's issue in this case.  using `docker build` doesn't allow mounted volumes.

**Comment by thaJeztah** [comment] 2015-05-04 02:53
If I understand your use-case correctly, this looks like a duplicate of https://github.com/docker/docker/issues/3056 (and https://github.com/docker/docker/issues/10199)

@saturnism can you confirm that this is the case (and close this issue if I'm correct)?

**Comment by saturnism** [comment] 2015-06-27 15:19
pretty similar - but should work in ONBUILD too :)

**Comment by cpuguy83** [comment] 2015-06-28 19:23
Why is the dir not persistent?
This is completely the image's issue if they have placed a volume at the repo path.

**Comment by saturnism** [comment] 2015-09-14 00:35
actually, this is very specific to some build processes that pulls down dependencies.  rather than re-downloading the dependencies each build, dependencies are already versioned and static, it can be shared via a volume.

for example, when building w/ maven:onbuild, it will pull down many dependencies from maven central.  however, in a regular maven build environment, all of the dependencies are cached in ~/.m2/repository directory. 

it would be super nice if that' can be shared via a volume.

thanks,

**Comment by saturnism** [comment] 2015-09-14 18:14
This will also be super helpful when building on remote docker machines

**Comment by cyberjoac** [comment] 2016-09-14 08:35
+1

**Comment by gkozyryatskyy** [comment] 2016-12-27 15:14
@saturnism Do you use something like a "workaround" for this issue? How exactly you do that? =)

**Comment by gkozyryatskyy** [comment] 2016-12-27 15:43
same issues https://github.com/docker/docker/issues/17745
and seems like work going in https://github.com/docker/docker/issues/14080

**Comment by cpuguy83** [comment] 2020-03-23 16:33
With the buildkit builder you can mount cache mounts. Cache mounts can be just an empty dir that gets populated during the build, or it can even be an overlay from a pre-populated dir, from another build stage, etc.

https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#run---mounttypecache

Closing since this should resolve most cases.

**Closed by cpuguy83** 2020-03-23 16:33 UTC
Labels: area/builder, kind/feature
