### ISSUE TITLE
docker volume inspect : 'CreatedAt'

### ISSUE THREAD

**Issue by tscuite** [moby/moby#44364] opened 2022-10-27 07:55 UTC
### Description

docker volume inspect dongtai_mysql-vol
[
    {
        "CreatedAt": "2022-10-27T07:47:03Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "q",
            "com.docker.compose.version": "2.5.0",
            "com.docker.compose.volume": "mysql-vol"
        },
        "Mountpoint": "/var/lib/docker/volumes/q_mysql-vol/_data",
        "Name": "q_mysql-vol",
        "Options": null,
        "Scope": "local"
    }
]

### Reproduce

docker volume inspect xxxxxxxx

### Expected behavior

This time field should be constant as the volume is created. But he does change the time as he mounts different containers

### docker version

```bash
docker version
Client:
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:39:56 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:44:54 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 22
  Running: 14
  Paused: 0
  Stopped: 8
 Images: 131
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.130-118.517.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.76GiB
 Name: aws
 ID: LMMB:O4E6:CEBG:3UUG:XWJO:YFFS:7232:RSJL:HLER:AOQV:X37F:KZTF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: dongtaidotio
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by vvoland** [comment] 2022-10-27 09:54
I can reproduce this, but mounting volume is not enough for `CreatedAt` to change. It only changed for me when I created a file or modified file in the volume filesystem.
So it looks like the `CreatedAt` behaves more like `ModifiedAt`.

**Comment by bsousaa** [comment] 2022-12-20 11:43
This is a duplicate of https://github.com/moby/moby/issues/38274 as it is the same root cause. Related PR in progress https://github.com/moby/moby/pull/38276

**Closed by bsousaa** 2022-12-20 11:43 UTC
Labels: status/0-triage, kind/bug, area/volumes
