### ISSUE TITLE
flaky test DockerSwarmSuite.TestAPISwarmRaftQuorum

### ISSUE THREAD

**Issue by tophj-ibm** [moby/moby#35039] opened 2017-09-29 12:15 UTC
Seen failing a lot on all jobs, full log https://jenkins.dockerproject.org/job/Docker-PRs/45837/console
```
03:41:46 ----------------------------------------------------------------------
03:41:46 FAIL: docker_api_swarm_test.go:349: DockerSwarmSuite.TestAPISwarmRaftQuorum
03:41:46 
03:41:46 [d84bfca646cb5] waiting for daemon to start
03:41:46 [d84bfca646cb5] daemon started
03:41:46 
03:41:46 [d0e0a09fece41] waiting for daemon to start
03:41:46 [d0e0a09fece41] daemon started
03:41:46 
03:41:46 [dcf242eb7968d] waiting for daemon to start
03:41:46 [dcf242eb7968d] daemon started
03:41:46 
03:41:46 [d0e0a09fece41] exiting daemon
03:41:46 [dcf242eb7968d] exiting daemon
03:41:46 docker_api_swarm_test.go:374:
03:41:46     c.Assert(err.Error(), checker.Contains, "deadline exceeded")
03:41:46 ... obtained string = "Error response from daemon: rpc error: code = Unknown desc = raft: failed to process the request: node lost leader status"
03:41:46 ... substring string = "deadline exceeded"
03:41:46 
03:41:46 [d84bfca646cb5] exiting daemon
03:42:33 
03:42:33 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment] 2017-09-29 14:03
thanks! duplicate of https://github.com/moby/moby/issues/34988

**Closed by thaJeztah** 2017-09-29 14:03 UTC

**Comment by tophj-ibm** [comment] 2017-09-29 14:19
oops, thanks!
