### ISSUE TITLE
Docker load command does not return image name

### ISSUE THREAD

**Issue by srshanmug** [moby/moby#32741] opened 2017-04-20 11:50 UTC
docker version:
```
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

docker info:
```
docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 24
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.702 GiB
Name: a1.dcos
ID: J24V:L2J3:FEEX:VS3Z:GGKI:767Y:D2WE:GJCD:USFG:KCHY:5MXA:RD44
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

uname -a:
```
uname -a
Linux 1a15201441bd 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
Provide additional environment details (AWS, VirtualBox, physical, etc.):

This is a docker container running inside Vagrant mesos slave. Container is launched as a marathon app. 
Following volumes are mounted when deploying this marathon App
```json
"volumes": [
      {
        "containerPath": "/var/run/docker.sock",
        "hostPath": "/var/run/docker.sock",
        "mode": "RW"
      },
      {
        "containerPath": "/usr/local/bin/docker",
        "hostPath": "/usr/bin/docker",
        "mode": "RW"
      }
    ]
```

List the steps to reproduce the issue:
1. Create a tar file and copy it to docker container through boot script invoked in dockerfile
2. Issue docker load command through a script inside docker container
3. docker load -i "example.tar" command does not give back the loaded image name. 
The command returns nothing when image exists inside container.

Describe the results you received:

When image exists, issuing docker load command returns : Nothing
```
 [root@1a15201441bd]# docker load -i httpd.tar           
[root@1a15201441bd]# docker images
```
When image does not exist inside the container, issuing docker commad returns:
```
[root@1a15201441bd]# docker load -i httpd.tar 
5d6cbe0dbcf9: Loading layer 129.2 MB/129.2 MB
aa4c186185aa: Loading layer 3.584 kB/3.584 kB
5789daa1c37d: Loading layer  2.56 kB/2.56 kB
b7fac20846c1: Loading layer  5.12 kB/5.12 kB
10cd1ea92057: Loading layer 46.61 MB/46.61 MB
e70070ad9b01: Loading layer 9.824 MB/9.824 MB
73ff04cf8df5: Loading layer 3.584 kB/3.584 kB
[root@1a15201441bd ]# 
```

Describe the results you expected:

Docker load command should return "Loaded image: httpd:latest" when image does not already exist

Docker load command should return "The image xxx already exists..." when image does exist within the container.

Provide additional info you think is important:

Following alternatives were tried in this environment:

1. Instead of bash script executing docker load command, spotify docker java library was used to write a java class to 
call docker load api.
2. https://github.com/jenkinsci/docker/issues/196#issuecomment-179486312 - Installed docker engine (static executable) 
instead of mounting /usr/bin/docker from host.

Observation:

command: docker load -i httpd.tar

1. Works when issued directly on the mesos slave node where the container is running

2. Works when issued within a docker container run in docker compose

3. Does not work when issued within the docker container launched as a marathon app

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by thaJeztah** [comment] 2023-09-16 17:14
closing as duplicate of https://github.com/moby/moby/issues/18117

**Closed by thaJeztah** 2023-09-16 17:14 UTC
Labels: kind/enhancement, version/1.11, area/images
