### ISSUE TITLE
Problems setting a env_file as docker config

### ISSUE THREAD

**Issue by bd8392** [moby/moby#40717] opened 2020-03-18 19:43 UTC
Hi... sorry I don't know where to ask that...I've searched all the docs, bit didn't find a way to set an env_file (multiple environment variables) in a docker config for swarm...can someone here show me how to do it? Or tell me if this is even possible? Thank you!

**Comment by bd8392** [comment] 2020-03-19 17:36
Anyone an Idea? still didn't figure it out...

**Comment by thaJeztah** [comment] 2020-06-04 14:01
`env_file` is a client-side implementation, and effectively a shorthand for passing multiple `--env` variables. If you specify an `--env-file`  on `docker service create`, the `docker` cli parses the env-file, and converts it to `--env` options. After the service is deployed, that env-file is no longer used.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-06-04 14:01 UTC
Labels: area/stack, kind/question
