### ISSUE TITLE
More intuitive default tagging when building images

### ISSUE THREAD

**Issue by brianclements** [moby/moby#4817] opened 2014-03-23 08:34 UTC
When building a modified version of an image from a dockerfile, thereby replacing the previous version with something new, I feel like there is something that can be done about the HEAD^n containers that are now a type of "intermediate" and untagged container. Perhaps for a couple of generations they should follow the git nomenclature and actually be renamed like this:

```
image-name:latest
image-name:latest^2
image-name:latest^3
```

and then just start removing them past a certain generation? Keep the naming going forever?
or perhaps something more "common speak"

```
image-name:latest
image-name:previous
image-name:old
image-name:old+1
image-name:oldest
```

Also on failed builds, the last successful commit is already visible in `docker images`, but a half-run Dockerfile doesn't help very much, so why not just tag it what it is as "image-name:failed" so there is no question?

Another thing, right now referencing an image that has only 1 tag needs to be explicit unless that tag is "latest". In the spirit of tagging commits, shouldn't they just behave like true tags and point to the same commit if no other tags exist? `image-name` is hardwired to always be `image-name:latest` instead of just `image-name:whatever_tag_is_left`. And for those that use tagging for versioning, the word "latest" might not ever be used. But it would still be nice to have `image-name` always reference the newest image no?

lastly, image/tag wildcard support!

```
$ docker images
REPOSITORY            TAG
image-name                latest
image-name                previous
image-name                oldest
image-name                failed
$ docker rmi image-name:*
Deleted: as;dlfjas;ldfjas;ldfjas;a;slfd
x4
$ docker images
REPOSITORY              TAG
```

or

```
REPOSITORY            TAG
image-name1                latest
image-name1                oldest
image-name2                latest
image-name2                oldest
$ docker rmi *:oldest
Deleted: as;dlfjas;ldfjas;ldfjas;a;slfd
x2
$ docker images
REPOSITORY              TAG
image-name1                latest
image-name2                latest
```

and for the quitters!

```
$ docker rmi *:*
```

**Comment by jfrazelle** [comment] 2015-02-26 03:10
see also https://github.com/docker/docker/issues/5603 https://github.com/docker/docker/issues/9641

**Comment by jfrazelle** [comment] 2015-02-26 03:10
we need a way to merge all those

**Comment by brianclements** [comment] 2015-02-26 10:06
It's interesting, tagging has remained sort of untouched for a long time because there are two conflicting uses for them: to show a history of an image, and to show types of an image. Technically, as with git, they are one in the same. But that, I feel, is the main reason defining "default" tag behavior has been difficult to nail down. I tend to favor tags as history rather then type. If tagging assumptions are to be made and defaults implemented, then I think the only way that can be done is to really bias tagging as history instead of type.

At first glance, I think the TAG directive in the dockerfile (#5603) is the best idea to implement first. Because, you can just leave it out if you don't want it. But it still allows for all the custom tagging one desires. #9641 actually appears to be solvable by the first. It seems OP's priority would be to have consistent default tagging behavior in a development environment with multiple parties involved so that a single `docker build` will produce the appropriate tagging for that project without the need for an outside script or makefile just to store the tag name. Embedding those tags in the Dockerfile can keep track of that on a per Dockerfile/project basis, which I think is better then an additional file.

My concern in this report is this: on any typical day, what does the output of your `docker images` show in the tag column? For me right now, it was 95% "latest". In my experience, when information is that repetitive, it means it's not being used properly, or rather, I don't know how I want to use it.

Also for this discussion, I think we need to get specific about terms, so I'll give specific examples of workflow so we can all reproduce the same behavior and determine better what we're talking about. I feel like we are mixing "intermediate containers" and "untagged" and "replaced" etc.

### Case 1
The default tag. What happens when we build an image with no tag?

 1. make a dockerfile that does something
```
FROM busybox:latest
RUN touch /tmp/one
```
 2. `docker build -t app .` with no tags produces this:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
app                 latest              4dd4ff70965a        44 seconds ago      2.433 MB
busybox             latest              4986bf8c1536        8 weeks ago          2.433 MB
```
 This is version 1 of our app, and it is the latest version.
 3. modify our dockerfile
```
FROM busybox:latest
RUN touch /tmp/one
RUN touch /tmp/two
```
 4. `docker build -t app. ` with to tags does this:
```
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon
Step 0 : FROM busybox:latest
 ---> 4986bf8c1536
Step 1 : RUN touch /tmp/one
 ---> Using cache
 ---> 4dd4ff70965a
Step 2 : RUN touch /tmp/two
 ---> Running in 203202f0a51f
 ---> 373ac626bfc2
Removing intermediate container 203202f0a51f
Successfully built 373ac626bfc2
```
and shows this:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
app                 latest              373ac626bfc2        30 seconds ago      2.433 MB
busybox             latest              4986bf8c1536        8 weeks ago         2.433 MB
```
What happened to version 1? (image 4dd4ff70965a) Why is it being treated as trash by default? My ideas initially were to make it logical to see the succession. Calling something "latest" by default is useless if there is no history that's readily accessible. If I keep modifying my dockerfile and building again with no tag, that app:latest just keeps replacing my previous images; no easily reachable or obvious history or succession of that image.

I would love this in this situation:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
app                 latest              373ac626bfc2        30 seconds ago      2.433 MB
app                 previous            4dd4ff70965a        44 seconds ago      2.433 MB
```
and over time
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
app                 latest              45c118bb2039        8 seconds ago       2.433 MB
app                 previous            373ac626bfc2        30 seconds ago      2.433 MB
app                 oldest              4dd4ff70965a        44 seconds ago      2.433 MB
```
Or something similar.

### Case 2
The rename. What happens to previous images when we replace the image:tag?

Start with busybox:latest
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              4986bf8c1536        8 weeks ago         2.433 MB
```
 1. `docker run busybox:latest touch /tmp/one`
 2. `docker commit 615ba2ffc860 busybox:latest` then shows:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              36c74cf9cccc        About a minute ago       2.433 MB
```
Why is the original image trash? Again, my same reasoning and proposed solution as in case 1. I'd like to see succession and non-clobbering by default. 

### Case 3
The upgraded tag via pull. What happens to old images when replaced with a newer one via `docker pull`?

Here we fake a new version of busybox by doing the same thing we did in case 2:
 1. `docker run busybox:latest touch /tmp/one`
 2. `docker commit 615ba2ffc860 busybox:latest`
 3. `docker pull busybox:latest` will pull the original image back, stealing the tag and will untag the image that owned that before, ie. the previous version.
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              ee2d0a2735fc        About a minute ago   2.433 MB
busybox             latest              4986bf8c1536        8 weeks ago         2.433 MB
```
Same situation, different path to it. It occurred to me to commit and tag an image before, because I obviously felt it was important, why should a `docker pull` just blatantly destroy that? Overwriting latest I understand for sake of automation (always run "latest" tag in production etc.), but keeping a history doesn't negate that feature.

### Case 4
The upgrade tag via build. What happens to old images when replaced with a newer one via build?

It's pretty much the same as case 1 and 2: our new image replaces the old in `docker images`. This case has some more variability though if you incorporate the tagging via TAG directive within the dockerfile (which I +1 btw). So there has to be a priority within this case as well between:

 * TAG directive in dockerfile
 * no TAG in dockerfile, and no tag from the CLI
 * Conflict between TAG in dockerfile and tag via CLI
 * If you do supply a tag via CLI or TAG in dockerfile, do you double tag by default the newest image with "latest"? So that we keep a history going?

### General Comments

Of course we can always tag beforehand, but that is very dependent on your orchestration tool keeping track of that history for you. Why should docker care about it? Because I've heard talk of garbage collection at some point, and being conservative about image history and removing tags (so that it can be gc) makes docker a cordial custodian of your images that automatically keeps track of history by default instead of a more cutthroat purging of all that is old. This is especially handy for CLI usage without orchestration tools. I should just keep building, tagging, committing, pulling my images and the entire history be preserved via tags. On massive scale, with many individuals and programs manipulating the same images, the history could be very welcome. What about reverting back from latest in emergency? A history could encourage this behavior by default. Why do I have to dig around `docker history` for some image ID instead of a very easy "busybox:previous" tag for example that I can be confident about?

**Comment by odigity** [comment] 2015-10-14 17:26
I have the same complaint as the top post.  Googled to try to find a solution, found this issue -- which is still open with no activity for a while.

Is there anything new on this front in the last year?

Wouldn't it be easy to just add an option to `docker build` to tell it you don't want the previous version of the image kept?

**Comment by LK4D4** [comment] 2016-09-16 16:49
@aaronlehmann @tonistiigi @stevvooe Is this possible without major changes in design?

**Comment by aaronlehmann** [comment] 2016-09-16 17:29
There's already a lot of detailed discussion in the issue about the pros and cons. I'm not sure I have anything to add.

I don't think it's technically difficult to make the changes suggested here, but it's more of a design question.

**Comment by LK4D4** [comment] 2016-09-16 17:36
@aaronlehmann @stevvooe I wonder who can do design decision. Issue is pretty old, so if nobody will come with arguments I will close it.

**Comment by stevvooe** [comment] 2016-09-23 23:19
@LK4D4 In general, I agree with the sentiment, but I am not sure it is worth the engineering effort and compatibility breaks this would incur.

There is nothing wrong with the ideas here other than that tags don't really work anything like git tags. For this to work, we'd really need to introduce some sort of first-class tag concept, separate from what we call a tag today, which is just a name, really.

There are really two departures from the git data model:

1. There is non-zero cost to each revision in docker, unlike git.
2. The behavior of tags like `latest` is more akin to a branch, which requires another level of change history.

We can see this, somewhat, in features like `docker history`. In git, you walk a linked set of commits, which have a parent commit and a tree. Each tree is wholly independent and calculating diffs requires two trees. In docker, we are storing actual deltas, where each "tree" requires the tree before it to calculate the whole result and the links between these deltas are a part of the image config, which sits above everything.

Not to mention that each changeset has a runtime cost. This feature provides docker fast commit and startup, at the cost of a less rich history model. In git, one can look at merely the commit and tree to get at the content. Because each changeset in docker is pushed to the original change and each mounted layer has runtime cost, maintaining the history of all changes for an image isn't possible without drastic breaks.

The missing component here is lineage. In git, you have lineage of commits, maintained by a hard hash linked relationship. In docker, the naming lives outside this hash chain. We'd really have to bring it into that system to make this work in the same way.

The key change would be to have something similar to a commit object that tracks the tree at each image level. That tree could be represented by a set of layers, or whatever. The operation of pushing would be to then push this lineage (just hashes, not even names at this point) to "branches". These lineage objects (commits, really) could then be tagged and we'd have something very close to how git behaves.

__TL; DR__ Docker tags are git-inspired but lack the internal data structures to achieve some of the more advanced git-style features.

**Comment by thaJeztah** [comment] 2016-09-24 00:10
I think the original issue could be easily achieved with a script / external tooling

**Comment by stevvooe** [comment] 2016-09-27 21:35
> I think the original issue could be easily achieved with a script / external tooling

How would such a script maintain the relationship between the current version of `latest` and the last version of `latest`? How could these reconcile when `latest` forks on two separate machines? This behavior requires a three-way merge semantic with history of the _reference_, not the image.

**Comment by thaJeztah** [comment] 2016-09-27 21:41
@stevvooe I was thinking of `docker tag myimage:latest my image:latest-1`, or  `docker tag myimage:latest my image:previous` before running a build, or am I being naive?

**Comment by stevvooe** [comment] 2016-09-28 00:09
@thaJeztah Sure, that would provide a _similar_ behavior but the result is shallow. It will break down when two nodes disagree on what `latest-1` is.

Git's data structures really enable some cool stuff and reproducing that behavior cannot be done with data structures that support these operations under all conditions.

**Closed** 2024-01-09 21:43 UTC
Labels: area/builder, area/distribution, kind/feature
