### ISSUE TITLE
Untar re-exec error: exit status 1: output: unexpected EOF when "input/output error" on one file

### ISSUE THREAD

**Issue by arthurlogilab** [moby/moby#14792] opened 2015-07-21 10:43 UTC
If for some reason there is a input/output error on one of the files in a subdirectory of the place where one is building the docker image, doker build fails with a untar exit error message : 

```
$ docker -D build .
Sending build context to Docker daemon 141.8 kB
Sending build context to Docker daemon 
Error response from daemon: Untar re-exec error: exit status 1: output: unexpected EOF
$ docker -D build  .
DEBU[0000] Can't add file .hg/store/undo to tar: open .hg/store/undo: input/output error 
[snip]
DEBU[0000] Can't add file Dockerfile to tar: archive/tar: missed writing 8192 bytes 
[snip]
DEBU[0000] Can't close tar writer: archive/tar: missed writing 8192 bytes 
Sending build context to Docker daemon 141.8 kB
Sending build context to Docker daemon 
Error response from daemon: Untar re-exec error: exit status 1: output: unexpected EOF
$ docker --version
Docker version 1.7.1, build 786b29d
```

removing that IO error file solves the problem. 

Maybe docker could ignore those files, or have a better error message.

**Comment by arthurlogilab** [comment] 2015-07-21 10:52
```
arthur@ursa:~$ docker --version
Docker version 1.7.1, build 786b29d
arthur@ursa:~$ docker info
Containers: 32
Images: 372
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 436
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 5.71 GiB
Name: ursa
[snip]
WARNING: No swap limit support
arthur@ursa:~$ uname -a
Linux ursa 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by arthurlogilab** [comment] 2015-07-21 11:01
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Comment by thaJeztah** [comment] 2015-08-15 20:46
Are you still able to reproduce this on docker 1.8.1? I'm wondering if the EOF error  is related to https://github.com/docker/docker/pull/15040

**Comment by arthurlogilab** [comment] 2015-08-18 08:44
@thaJeztah is 1.8.1 distributed for ubuntu ? I seem to only get 1.7.1 at this point

**Comment by thaJeztah** [comment] 2015-08-18 09:12
@arthurlogilab 1.8.1 is distributed for ubuntu. Are you perhaps running Ubuntu 14.10? Ubuntu 14.10 is marked End-Of-Life by Ubuntu (see http://fridge.ubuntu.com/2015/07/23/ubuntu-14-10-utopic-unicorn-end-of-life-reached-on-july-23-2015/), and no longer supported. We no longer publish Docker for Ubuntu 14.10. So if you're running on 14.10, you should either upgrade to 15.04 or a long-term-support version (currently 14.04 LTS)

**Comment by arthurlogilab** [comment] 2015-08-18 09:19
@thaJeztah am running vivid with get.docker.io repositories

**Comment by thaJeztah** [comment] 2015-08-18 09:34
@arthurlogilab ah! there are new APT and YUM repositories now, providing dynamically linked binaries (which solves a number of other issues as well). Check this blog-post for more information;
https://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by arthurlogilab** [comment] 2015-08-18 09:47
I'm willing to try and reproduce but I don't know how to create a file that then doesn't exist and generates a IO error.

**Comment by garthk** [comment] 2015-10-08 05:25
Seen on OS X against a `docker-machine` image:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Fri Sep 11 01:46:35 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by Hildebrand** [comment] 2015-11-06 15:10
We were able to consistently reproduce this issue from within a Gradle Exec task. Eventually we found the issue to be a build context that included way too much (complete project source root directory). After changing the docker build context to an empty folder containing just the required assets and Dockerfile this issue was resolved.

**Comment by fbender** [comment] 2015-12-28 11:09
If anybody comes across this, check your permissions and file owners! I fixed this error by setting the file owner to the one in the `docker` group.

**Comment by bdart** [comment] 2016-01-19 21:43
Same here with 
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

I think it is because of the massive image stack. But I do not know why there are so many <none> when I build my images:
```
hhvm-composer            1.0                 31ee79f0a048        5 days ago          510.8 MB
<none>                   <none>              e11eb622bc71        5 days ago          510.8 MB
<none>                   <none>              2a2210677fff        5 days ago          510.8 MB
<none>                   <none>              1dc4cd0e8111        5 days ago          510.8 MB
<none>                   <none>              e20cfb489538        5 days ago          505.3 MB
<none>                   <none>              7947b296dcec        5 days ago          434.9 MB
<none>                   <none>              11bf6d97745c        5 days ago          433.3 MB
<none>                   <none>              ab0d6b4f6b2c        5 days ago          433.3 MB
debian                   jessie              140f9bdfeb97        12 days ago         125.1 MB
<none>                   <none>              523ef1d23f22        12 days ago         125.1 MB
hhvm                     1.0                 654f25e607db        3 months ago        433.3 MB
<none>                   <none>              78713e7f8ae5        3 months ago        433.3 MB
<none>                   <none>              3f05566268ae        3 months ago        433.3 MB
<none>                   <none>              62de98ab8f73        3 months ago        433.3 MB
<none>                   <none>              701b7d366dd8        3 months ago        433.3 MB
<none>                   <none>              c148bbc8dcf1        3 months ago        433.3 MB
<none>                   <none>              046b34d2f4d3        3 months ago        433.3 MB
<none>                   <none>              9176faf97599        3 months ago        126.4 MB
<none>                   <none>              3488622e840e        3 months ago        126.8 MB
<none>                   <none>              b2c8ddc41aad        3 months ago        126.4 MB
<none>                   <none>              55b6f523d380        3 months ago        126.4 MB
<none>                   <none>              688eb55989b5        3 months ago        126.8 MB
<none>                   <none>              8680728a3ea9        3 months ago        125.2 MB
<none>                   <none>              4989ae106bc1        3 months ago        126.4 MB
<none>                   <none>              30d885a6eab2        3 months ago        125.2 MB
<none>                   <none>              3d88cbf54477        3 months ago        125.2 MB
<none>                   <none>              7a42f1433a16        3 months ago        125.2 MB
nginx                    1.9.3               15fcaea98dd6        6 months ago        132.9 MB
<none>                   <none>              3b5c3f4c3b70        6 months ago        132.9 MB
<none>                   <none>              abc4a80afc71        6 months ago        132.9 MB
<none>                   <none>              bcbceb1f0c8c        6 months ago        132.9 MB
<none>                   <none>              9f15c123dc17        6 months ago        132.9 MB
<none>                   <none>              422936fdc3f7        6 months ago        132.9 MB
<none>                   <none>              97baf3700101        6 months ago        125.2 MB
<none>                   <none>              de2107968419        6 months ago        125.2 MB
<none>                   <none>              38e2388127fa        6 months ago        125.2 MB
<none>                   <none>              0e11c180ca22        6 months ago        125.2 MB
<none>                   <none>              8b5de14bc579        6 months ago        125.2 MB
<none>                   <none>              3d7d0c417e1d        6 months ago        125.2 MB
```

**Comment by thaJeztah** [comment] 2016-01-20 03:32
@bdart all those `<none> <none>` images are the *intermediate* images that make up an image, e.g. all the images below `nginx 1.9.3` are the "layers" that form `nginx:1.9.3`

**Comment by yucerjs** [comment] 2016-03-13 15:05
I got this error. I was using docker-compose. My normal cycle of use was:

1)  **docker-compose build** 
2) **docker-compose up**
3) <test here>
4) **docker-compose down**

In this process the number of dangling (<none>:<none>) images  was growing dramatically until It ran out of space.

**Comment by thaJeztah** [comment] 2018-05-22 17:31
This issue is over two years old, and there's no consistent way to reproduce this; for that reason I'll close this issue. If you're having this issue, and have a way to reproduce, please open a new issue instead.

**Closed by thaJeztah** 2018-05-22 17:31 UTC
Labels: area/builder, area/storage/aufs, kind/bug
