### ISSUE TITLE
COPY step fails on Windows when the size is greater than 20GB. 

### ISSUE THREAD

**Issue by yusuf-gunaydin** [moby/moby#37352] opened 2018-06-27 08:27 UTC
**Description**

Normally the default layer size for Windows is set as 127GB by default with #35925. However, on this line: https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/daemon/images/image_builder.go#L56 `CreateRWLayerOpts` is sent as nil. So the storage options are not in effect.

**Comment by thaJeztah** [comment] 2018-07-04 17:36
ping @johnstep @jhowardmsft PTAL

**Comment by jhowardmsft** [comment] 2019-03-22 05:00
I don't have enough info - docker info, docker version, exact command, dockerfile, associated files, and so on. Closing. Please re-open if it repros on current moby master. Note that there have been a few attempts to allow `--storage-opts` to be added to `docker build`. In each case, the project maintainers have pushed back and not accepted it (if I'm interpreting what you're saying).

**Closed by jhowardmsft** 2019-03-22 05:00 UTC
Labels: area/builder, platform/windows

**Comment by TBBle** [comment] 2020-11-05 07:45
We've just reproduced this, confirming that when a volume is mounted to be copied to, it's 20GB, even though `storage-opts` is set in the configuration:
```
  "storage-opts": [
    "size=400GB"
  ]
```
which correctly affects `RUN`.

We'd have had a reproduction case years ago, but it turns out the main repro case was hitting #40444.

I can't reopen this ticket though, so I'll probably open a new one unless a maintainer wants to reopen it for me? ^_^

**Comment by thaJeztah** [comment] 2020-11-05 11:02
@TBBle could that be fixed by https://github.com/moby/moby/pull/40256 ?

**Comment by TBBle** [comment] 2020-11-05 11:10
I don't think so. In fact, that PR confuses me, because as seen in my logs above, a `RUN` _does_ see the 400GB storage-opt specified in daemon.json, so I'm not sure what that PR is trying to do.

The problem, as pointed out in the original report, is that the `CreateRWLayer` call from the `COPY` operation doesn't pass any storage opts down. I've not yet worked out how to get the storage opts from the Daemon through to this point; the RUN works by packing the storage opts from the daemon into the Container spec, but there's no Container for `COPY`.

**Comment by thaJeztah** [comment] 2020-11-05 11:20
> Edit: Ah, that PR overlaps with a change I was investigating right now: The isWCOW value there doesn't appear to be true if platform is not explicitly set, so the 127GB override wasn't being applied for the simple case of docker build . in WCOW mode.

Ah, interesting; sounds like more fun because of the LCOW paths (I guess it doesn't set WCOW if it doesn't know if the image is gonna be Linux or Windows?) haven't checked all paths

Should we remove the `isWCOW` there? It would be a somewhat closer match to "linux" (where by default size is only restricted by physical disk space)
