### ISSUE TITLE
error during CreateContainer: failure in a  Windows system call: The data is invalid. (0xd)

### ISSUE THREAD

**Issue by nedumarans** [moby/moby#40843] opened 2020-04-21 12:09 UTC
Hi All,
we are trying to run a linux container on windows 2016 server (azure vm) release 1607. But After enabling all the necessary configuration and restart, getting following error while running the ubuntu container.

C:\Program Files\Docker\docker.exe: failed to register layer: failed to start service utility VM (applydiff 
a2fb3bcfd593349868225d6d2e573d4c7dc805f50e274409ddc826859a9bdbeb): container 
a2fb3bcfd593349868225d6d2e573d4c7dc805f50e274409ddc826859a9bdbeb_svm encountered an error during CreateContainer: failure in a 
Windows system call: The data is invalid. (0xd) extra info: {"SystemType":"container","Name":"a2fb3bcfd593349868225d6d2e573d4c7dc805f
50e274409ddc826859a9bdbeb_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","Linux
InitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}.
See 'C:\Program Files\Docker\docker.exe run --help'.

Not able to get any details about the root cause of this error message. Please help to fix this

**Comment by gomez34** [comment] 2020-04-27 13:12
@nedumarans I have the same problem in windows server 2019 Azure, have you managed to solve it?

**Comment by thaJeztah** [comment] 2020-06-04 13:39
note that LCOW is no longer supported on Windows Server < RS5 (Windows server 2019); https://github.com/moby/moby/pull/39108 (and https://github.com/moby/moby/issues/33850#issuecomment-478192332), and is not currently being worked on (see https://github.com/moby/moby/issues/39533)

**Comment by hartonoxu** [comment] 2020-11-12 08:32
> note that LCOW is no longer supported on Windows Server < RS5 (Windows server 2019); #39108 (and [#33850 (comment)](https://github.com/moby/moby/issues/33850#issuecomment-478192332)), and is not currently being worked on (see #39533)

@thaJeztah does it mean that we can't use LCOW on Windows Server 2016 anymore? Is there any alternative to run Linux Container on Windows Server 2016?

**Comment by thaJeztah** [comment] 2020-11-12 14:12
@hartonoxu support for LCOW on Windows Server 2016 was ready removed in Docker 19.03; https://github.com/moby/moby/blob/v19.03.13/pkg/system/init_windows.go#L19-L25. I don't think there's alternatives on Windows Server 2016. Windows Server 2016 is know to not be as stable as later versions when running containers, and afaik, WSL2 is not supported on it. If possible for your situation, Windows Server 2019 or up with WSL2 might be better alternatives.

**Comment by neersighted** [comment] 2023-01-14 22:15
Closing as won't fix -- this is by design/this code is being removed from Moby.

**Closed by neersighted** 2023-01-14 22:15 UTC
Labels: platform/windows, area/lcow
