### ISSUE TITLE
docker stack deploy completely ignores dns settings

### ISSUE THREAD

**Issue by mahnunchik** [moby/moby#34259] opened 2017-07-26 12:20 UTC
**Description**

`docker stack deploy` of compose file completely ignores dns settings.

**Steps to reproduce the issue:**

### Variant 1

1. Create docker machine:
```bash
$ docker-machine create --engine-opt dns=8.8.8.8 test-dns
```
2. Use the following docker-compose file:
```yml
version: '3'

services:
  busybox:
    command: "cat /etc/resolv.conf"
    image: busybox:latest
    deploy:
      restart_policy:
        max_attempts: 1
```

3. `docker stack deploy -c docker-compose.dns.yml dns`

### Variant 2

1. Create docker machine:
```
$ docker-machine create test-dns
```
2. Use the following docker-compose file:
```yml
version: '3'

services:
  busybox:
    command: "cat /etc/resolv.conf"
    image: busybox:latest
    dns:
      - 8.8.8.8
    deploy:
      restart_policy:
        max_attempts: 1
```

3. `docker stack deploy -c docker-compose.dns.yml dns`

**Describe the results you received:**

Container logs:
```
search office.local
nameserver 127.0.0.11
options ndots:0
```

**Describe the results you expected:**

```
nameserver 127.0.0.11
nameserver 8.8.8.8
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Valid for both variants.

`docker service inspect dns_busybox` shows the settings:

```json
                  "DNSConfig": {
                        "Nameservers": [
                            "8.8.8.8"
                        ]
                    }

```

`docker container inspect d6e6622742e5` shows the settings:

```json
            "Dns": [
                "8.8.8.8"
            ],

```

**Output of `docker version`:**

```bash
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```bash
$ docker info
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 3qrd5dlqyp2bxck2d1brt76uf
 Is Manager: true
 ClusterID: 3t4c4hwfonet7c7cp1528za2d
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.100.100
 Manager Addresses:
  192.168.100.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: swarm-master
ID: STCJ:VQ4P:L27S:FU52:BTAY:XHCL:B6HV:FJBH:AD4S:E7SZ:TPR5:BTXD
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 65
 Goroutines: 225
 System Time: 2017-07-26T12:15:38.756900949Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```bash
$ docker-machine -v
docker-machine version 0.12.2, build 9371605
```

`docker service update --dns-add=1.2.3.4` adds the record but didn't take any result.

**Comment by mahnunchik** [comment] 2017-07-27 10:46
I've reproduced this bug inside usual ubuntu 16.04.

**Comment by thaJeztah** [comment] 2017-07-27 11:45
This is the expected behaviour; when attached to a custom network, the 127.0.0.11 address is the embedded DNS for swarm service discovery; this DNS resolves the internal names (i.e., other containers and services attached to the same network).

Other DNS lookups are forwarded to the DNS server you configured; you'll see the same when using `docker service create`:

```bash
docker network create -d overlay testnet
docker service create --name repro-34259 --network testnet --dns 8.8.4.4 nginx:alpine
```

```bash
docker ps --filter name=repro-34259

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
2880fe04cfd5        nginx:alpine        "nginx -g 'daemon ..."   8 seconds ago       Up 6 seconds        80/tcp              repro-34259.1.0bxv48t59147k5zx68r07cka6
```

You can verify the DNS option is set;


```bash
docker inspect -f '{{.HostConfig.DNS}}' 2880fe04cfd5
[8.8.4.4]
```

And inside the container;

```bash
docker exec -it 2880fe04cfd5 sh

$ cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

$ ping google.com

PING google.com (216.58.211.110): 56 data bytes
64 bytes from 216.58.211.110: seq=0 ttl=37 time=0.387 ms
64 bytes from 216.58.211.110: seq=1 ttl=37 time=0.315 ms
64 bytes from 216.58.211.110: seq=2 ttl=37 time=0.307 ms
64 bytes from 216.58.211.110: seq=3 ttl=37 time=0.265 ms
^C
--- google.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.265/0.318/0.387 ms
```

**Comment by thaJeztah** [comment] 2017-07-27 11:46
I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-27 11:46 UTC
Labels: area/swarm, version/17.06

**Comment by mahnunchik** [comment] 2017-07-27 12:12
Hi @thaJeztah 

> Other DNS lookups are forwarded to the DNS server you configured; you'll see the same when using 

It seems embedded DNS doesn't forwarded lookups to **configured** DNS servers. It forwards lookups to default (it seems 8.8.8.8) DNS server.

```bash
$ docker service inspect test
```
```json
                        "Nameservers": [
                            "192.168.0.100",
                            "8.8.8.8"
                        ]

```
`192.168.0.100` is internal DNS server, it knows `internal.com` address.

```bash
$ docker exec -it 10b5e1acb484 bash
```

```bash
root@10b5e1acb484:/app# ping google.com
PING google.com (64.233.161.100): 56 data bytes
64 bytes from 64.233.161.100: icmp_seq=0 ttl=61 time=285.520 ms
64 bytes from 64.233.161.100: icmp_seq=1 ttl=61 time=285.209 ms
^C--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 285.209/285.365/285.520/0.156 ms
root@10b5e1acb484:/app# ping internal.com
ping: unknown host
root@10b5e1acb484:/app#
```

Ping of internal resource is unsuccessful.

**Comment by mahnunchik** [comment] 2017-07-27 12:15
When I try to ping resource known by both 8.8.8.8 and inernal DNS server `192.168.0.100` but with different IP addresses (public and private): ping shows only public IP.

It seems embedded DNS doesn't forward lookups to configured DNS servers.

**Comment by thaJeztah** [comment] 2017-07-27 13:27
Is your internal DNS server accessible from inside the boot2docker VM? The boot2docker VM is in the `192.168.100.x` IP-range, does the DNS server accept connections from that range?

**Comment by mahnunchik** [comment] 2017-07-27 13:54
`internal.com` is accessible through internal DNS server `192.168.0.100` from:

* Host machine because DHCP configuration
* VM (both boot2docker and simple ubuntu)
* Regular docker container `docker run alpine` because docker engine configured with `--engine-opt dns=192.168.0.100 --engine-opt dns=8.8.8.8` (inside both boot2docker and simple ubuntu)

But doesn't accessible from any container launched in swarm mode.

The boot2docker VM is in 192.168.100.x range.
The ubuntu VM is in 192.168.99.x range.

DNS server accepted connections from any ranges if connection from inside intranet.

**Comment by mahnunchik** [comment] 2017-07-31 09:44
Hi @thaJeztah 
is this issue confirmed or you need more info?

**Comment by thaJeztah** [comment] 2017-07-31 10:57
I'm not able to reproduce the issue. Here's what I did to reproduce;


Make sure the daemon has `debug` mode enabled; you can enable this by setting `"debug":true` in the [`daemon.json` configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file);

```bash
$ cat /etc/docker/daemon.json
{"debug":true}
```

(`SIGHUP`, or restart the daemon to (re)load the configuration)


Deploy a service from a docker-compose file, specifying `8.8.4.4` as DNS

```bash
$ mkdir repro-34259 && cd repro-34259

$ cat > docker-compose.yml <<"EOF"
version: '3'

services:
  myservice:
    image: nginx:alpine
    dns:
      - 8.8.4.4
EOF

$ docker stack deploy -c docker-compose.yml repro-34259
```

Verify the DNS is set on tasks for the service (in this case, `repro-34259_myservice.1.1ckw06pai3pv82izg8mbno7a4` was the name of the task);

```bash
$ docker inspect -f '{{.HostConfig.DNS}}' repro-34259_myservice.1.1ckw06pai3pv82izg8mbno7a4
[8.8.4.4]
```


`docker exec` into the container, and ping some external domain;

```bash
$ docker exec -it repro-34259_myservice.1.1ckw06pai3pv82izg8mbno7a4 sh
/ # ping www.github.com
PING www.github.com (192.30.253.113): 56 data bytes
64 bytes from 192.30.253.113: seq=0 ttl=37 time=0.641 ms
64 bytes from 192.30.253.113: seq=1 ttl=37 time=0.689 ms
64 bytes from 192.30.253.113: seq=2 ttl=37 time=0.701 ms
^C
--- www.github.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.641/0.677/0.701 ms
```

Check the daemon logs; you can see requests are forwarded to the external DNS

```bash
Jul 31 10:52:01 moby root: time="2017-07-31T10:52:01.956992625Z" level=debug msg="Calling POST /v1.30/exec/60a3e07cb7b5596a7df081ea8012fe0e03dacb4587d3b25bf52a5bdc6177a833/resize?h=31&w=118"
Jul 31 10:52:45 moby root: time="2017-07-31T10:52:45.446088867Z" level=debug msg="Name To resolve: www.github.com."
Jul 31 10:52:45 moby root: time="2017-07-31T10:52:45.446273959Z" level=debug msg="Name To resolve: www.github.com."
Jul 31 10:52:45 moby root: time="2017-07-31T10:52:45.446418896Z" level=debug msg="Query www.github.com.[28] from 172.18.0.3:54232, forwarding to udp:8.8.4.4"
Jul 31 10:52:45 moby root: time="2017-07-31T10:52:45.446485921Z" level=debug msg="Query www.github.com.[1] from 172.18.0.3:43498, forwarding to udp:8.8.4.4"
```

**Comment by mahnunchik** [comment] 2017-08-02 10:45
Hi @thaJeztah this issue is related to the `name` of external network .

### Steps before deploy

Configure docker machine:
```bash
docker-machine create --engine-opt dns=192.168.0.100 --engine-opt dns=8.8.8.8 test-dns
```
`192.168.0.100` is internal DNS server that knows `internal.com` domain name.

Create two similar networks with the different names:
```bash
$ docker network create --driver=overlay traefik
$ docker network create --driver=overlay other-traefik
```

### Ignores DNS settings

```yml
version: '3'
services:
  test:
    command: "ping internal.com"
    image: alpine
    networks:
      - traefik

networks:
  traefik:
    external: true
```
Debug output:
```
journalctl  -f| grep Query
Aug 02 10:40:52 example dockerd[26445]: time="2017-08-02T10:40:52.450352227Z" level=debug msg="Query internal.com.[28] from 10.0.0.3:58982, forwarding to udp:192.168.0.100"
Aug 02 10:40:52 example dockerd[26445]: time="2017-08-02T10:40:52.454477500Z" level=debug msg="Query internal.com.[1] from 10.0.0.3:49951, forwarding to udp:192.168.0.100"
Aug 02 10:40:54 example dockerd[26445]: time="2017-08-02T10:40:54.953098398Z" level=debug msg="Query internal.com.[1] from 10.0.0.3:35812, forwarding to udp:192.168.0.100"
Aug 02 10:40:54 example dockerd[26445]: time="2017-08-02T10:40:54.953771848Z" level=debug msg="Query internal.com.[28] from 10.0.0.3:55377, forwarding to udp:192.168.0.100"
Aug 02 10:40:56 example dockerd[26445]: time="2017-08-02T10:40:56.454258511Z" level=debug msg="Query internal.com.[28] from 172.18.0.3:44411, forwarding to udp:8.8.8.8"
Aug 02 10:40:56 example dockerd[26445]: time="2017-08-02T10:40:56.466154683Z" level=debug msg="Query internal.com.[1] from 172.18.0.3:58015, forwarding to udp:8.8.8.8"
Aug 02 10:40:58 example dockerd[26445]: time="2017-08-02T10:40:58.954331082Z" level=debug msg="Query internal.com.[1] from 172.18.0.3:51460, forwarding to udp:8.8.8.8"
Aug 02 10:40:58 example dockerd[26445]: time="2017-08-02T10:40:58.956975135Z" level=debug msg="Query internal.com.[28] from 172.18.0.3:38777, forwarding to udp:8.8.8.8"
```
First 4 requests was forwarded to the correct `192.168.0.100` DNS server, but last 4 to the incorrect.

### Works as expected

```yml
version: '3'
services:
  test:
    command: "ping internal.com"
    image: alpine
    networks:
      - other-traefik

networks:
  other-traefik:
    external: true
```

Debug output
```
journalctl  -f| grep Query
Aug 02 10:42:42 example dockerd[26445]: time="2017-08-02T10:42:42.427729451Z" level=debug msg="Query internal.com.[28] from 172.18.0.3:34248, forwarding to udp:192.168.0.100"
Aug 02 10:42:42 example dockerd[26445]: time="2017-08-02T10:42:42.428290054Z" level=debug msg="Query internal.com.[1] from 172.18.0.3:43646, forwarding to udp:192.168.0.100"
```

**Comment by mahnunchik** [comment] 2017-08-02 11:01
It is strange but...

Works:
```yml
version: '3'
services:
  test:
    command: "ping internal.com"
    image: alpine
    networks:
      - traefik

networks:
  traefik:
    external:
      name: other-traefik
```

Not works:

```yml
version: '3'
services:
  test:
    command: "ping internal.com"
    image: alpine
    networks:
      - other-traefik

networks:
  other-traefik:
    external:
      name: traefik
```

**Comment by thaJeztah** [comment] 2017-08-02 13:12
What happens if you run this without compose?

```
docker service create --name test --network other-traefik alpine ping internal.com
```

The code that handles this is here; https://github.com/moby/moby/blob/03ab20291b255662708b4932df60e7b483dc2b8e/vendor/github.com/docker/libnetwork/resolver.go#L414-L489, and basically loops through all the defined external DNS servers (maximum 3)

The forwarding message is printed at this line; https://github.com/moby/moby/blob/03ab20291b255662708b4932df60e7b483dc2b8e/vendor/github.com/docker/libnetwork/resolver.go#L437-L438

And after that, a number of things can happen;

- A timeout ([DNS didn't respond within 4 seconds](https://github.com/moby/moby/blob/03ab20291b255662708b4932df60e7b483dc2b8e/vendor/github.com/docker/libnetwork/resolver.go#L440-L441)) - in which case the logs should show something like;

```
DEBU[0010] Query internal.com.[1] from 172.21.0.3:33021, forwarding to udp:8.8.8.8
DEBU[0010] Read from DNS server failed, read udp 172.21.0.3:34906->8.8.8.8:53: i/o timeout
DEBU[0010] Read from DNS server failed, read udp 172.21.0.3:33021->8.8.8.8:53: i/o timeout
```

- More than [100 outstanding queries are running (started within 2 seconds)](https://github.com/moby/moby/blob/03ab20291b255662708b4932df60e7b483dc2b8e/vendor/github.com/docker/libnetwork/resolver.go#L448-L456), in which case the logs show something like;

```
ERROR[0010] More than 100 concurrent queries from 172.18.0.3:34248
```

- Sending [the request failed, or reading the request failed](https://github.com/moby/moby/blob/03ab20291b255662708b4932df60e7b483dc2b8e/vendor/github.com/docker/libnetwork/resolver.go#L458-L472) (which should also be logged)

- The DNS returned an [empty response](https://github.com/moby/moby/blob/03ab20291b255662708b4932df60e7b483dc2b8e/vendor/github.com/docker/libnetwork/resolver.go#L474)

- The DNS returned a response, but [not an `A` or `AAAA` record](https://github.com/moby/moby/blob/03ab20291b255662708b4932df60e7b483dc2b8e/vendor/github.com/docker/libnetwork/resolver.go#L478-L483)


The last two bullets are not logged, so would be the only option.

**Comment by mahnunchik** [comment] 2017-08-03 05:59
Hi @thaJeztah 

It seems it is network overlap...

```bash
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.511679363Z" level=debug msg="Name To resolve: internal.com."
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.512652310Z" level=debug msg="Query internal.com.[28] from 10.0.0.3:42046, forwarding to udp:10.0.0.100"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.513180581Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"start-container\", Id:\"ac6390dbfb8c7e184202bfc6b80e363ce3d856fe216e80627d58579471b2f423\", Status:0x0, Pid:\"\", Timestamp:(*timestamp.Timestamp)(0xc420b176c0)}"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.513731638Z" level=debug msg="miss notification: dest IP 10.0.0.3, dest MAC 02:42:0a:00:00:03"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.514312477Z" level=debug msg="miss notification: dest IP 10.0.0.100, dest MAC "
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.512243804Z" level=debug msg="Name To resolve: internal.com."
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.515536335Z" level=debug msg="Query internal.com.[1] from 10.0.0.3:35339, forwarding to udp:10.0.0.100"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.516908372Z" level=debug msg="EnableService ac6390dbfb8c7e184202bfc6b80e363ce3d856fe216e80627d58579471b2f423 START"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.516990949Z" level=debug msg="addServiceInfoToCluster START for test_2 8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.517339570Z" level=debug msg="addServiceBinding from addServiceInfoToCluster START for test_2 8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38 p:0xc422262800 nid:12j9au06zo91qvizwxc0mdvlt skey:{yvtibsxlvr0e2zkx4vy6gfkfn }"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.517643141Z" level=debug msg="libcontainerd: event unhandled: type:\"start-container\" id:\"ac6390dbfb8c7e184202bfc6b80e363ce3d856fe216e80627d58579471b2f423\" timestamp:<seconds:1501734576 nanos:512427055 > "
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.517691242Z" level=debug msg="Creating service for vip 10.0.0.2 fwMark 292 ingressPorts []*libnetwork.PortConfig(nil) in sbox bcad00f (ac6390d)"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.596821058Z" level=debug msg="addEndpointNameResolution 8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38 test_2 add_service:true sAliases:[] tAliases:[ac6390dbfb8c]"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.596911471Z" level=debug msg="addContainerNameResolution 8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38 test_2.1.wuikkyzc2176zp6niitw5fqgu"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.596948615Z" level=debug msg="8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38 (12j9au0).addSvcRecords(test_2.1.wuikkyzc2176zp6niitw5fqgu, 10.0.0.3, <nil>, true) addServiceBinding sid:8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597006348Z" level=debug msg="8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38 (12j9au0).addSvcRecords(ac6390dbfb8c, 10.0.0.3, <nil>, true) addServiceBinding sid:8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597045629Z" level=debug msg="8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38 (12j9au0).addSvcRecords(tasks.test_2, 10.0.0.3, <nil>, false) addServiceBinding sid:yvtibsxlvr0e2zkx4vy6gfkfn"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597069311Z" level=debug msg="8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38 (12j9au0).addSvcRecords(test_2, 10.0.0.2, <nil>, false) addServiceBinding sid:yvtibsxlvr0e2zkx4vy6gfkfn"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597103421Z" level=debug msg="addServiceBinding from addServiceInfoToCluster END for test_2 8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597173845Z" level=debug msg="addServiceInfoToCluster END for test_2 8086103cae98fcbd685dd65ee3a794c42b06c63613c2f9a934e03af0ba113c38"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597193694Z" level=debug msg="EnableService ac6390dbfb8c7e184202bfc6b80e363ce3d856fe216e80627d58579471b2f423 DONE"
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597322411Z" level=debug msg="state changed" module="node/agent/taskmanager" node.id=3l64jymy1qo3hrjs2gdc3x8yh service.id=yvtibsxlvr0e2zkx4vy6gfkfn state.desired=RUNNING state.transition="STARTING->RUNNING" task.id=wuikkyzc2176zp6niitw5fqgu
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.597980786Z" level=debug msg="(*Agent).UpdateTaskStatus" module="node/agent" node.id=3l64jymy1qo3hrjs2gdc3x8yh task.id=wuikkyzc2176zp6niitw5fqgu
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.600033187Z" level=debug msg="task status reported" module="node/agent" node.id=3l64jymy1qo3hrjs2gdc3x8yh
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.600730179Z" level=debug msg="waiting on events" module="node/agent/taskmanager" node.id=3l64jymy1qo3hrjs2gdc3x8yh service.id=yvtibsxlvr0e2zkx4vy6gfkfn task.id=wuikkyzc2176zp6niitw5fqgu
Aug 03 04:29:36 example dockerd[26445]: time="2017-08-03T04:29:36.626992334Z" level=debug msg="task status updated" method="(*Dispatcher).processUpdates" module=dispatcher node.id=3l64jymy1qo3hrjs2gdc3x8yh state.transition="STARTING->RUNNING" task.id=wuikkyzc2176zp6niitw5fqgu
Aug 03 04:29:37 example dockerd[26445]: time="2017-08-03T04:29:37.512922720Z" level=debug msg="miss notification: dest IP 10.0.0.100, dest MAC "
Aug 03 04:29:38 example dockerd[26445]: time="2017-08-03T04:29:38.512667046Z" level=debug msg="miss notification: dest IP 10.0.0.100, dest MAC "
Aug 03 04:29:39 example dockerd[26445]: time="2017-08-03T04:29:39.012748733Z" level=debug msg="Name To resolve: internal.com."
Aug 03 04:29:39 example dockerd[26445]: time="2017-08-03T04:29:39.012774800Z" level=debug msg="Name To resolve: internal.com."
Aug 03 04:29:39 example dockerd[26445]: time="2017-08-03T04:29:39.015285171Z" level=debug msg="Query internal.com.[1] from 10.0.0.3:44405, forwarding to udp:10.0.0.100"
Aug 03 04:29:39 example dockerd[26445]: time="2017-08-03T04:29:39.016668086Z" level=debug msg="Query internal.com.[28] from 10.0.0.3:60716, forwarding to udp:10.0.0.100"
Aug 03 04:29:40 example dockerd[26445]: time="2017-08-03T04:29:40.514152826Z" level=debug msg="Read from DNS server failed, read udp 10.0.0.3:42046->10.0.0.100:53: i/o timeout"
Aug 03 04:29:40 example dockerd[26445]: time="2017-08-03T04:29:40.514965207Z" level=debug msg="Query internal.com.[28] from 172.18.0.3:35480, forwarding to udp:8.8.8.8"
Aug 03 04:29:40 example dockerd[26445]: time="2017-08-03T04:29:40.519134695Z" level=debug msg="Read from DNS server failed, read udp 10.0.0.3:35339->10.0.0.100:53: i/o timeout"
Aug 03 04:29:40 example dockerd[26445]: time="2017-08-03T04:29:40.520815181Z" level=debug msg="Query internal.com.[1] from 172.18.0.3:41094, forwarding to udp:8.8.8.8"
Aug 03 04:29:43 example dockerd[26445]: time="2017-08-03T04:29:43.016020702Z" level=debug msg="Read from DNS server failed, read udp 10.0.0.3:44405->10.0.0.100:53: i/o timeout"
Aug 03 04:29:43 example dockerd[26445]: time="2017-08-03T04:29:43.017289500Z" level=debug msg="Query internal.com.[1] from 172.18.0.3:50669, forwarding to udp:8.8.8.8"
Aug 03 04:29:43 example dockerd[26445]: time="2017-08-03T04:29:43.018564107Z" level=debug msg="Read from DNS server failed, read udp 10.0.0.3:60716->10.0.0.100:53: i/o timeout"
Aug 03 04:29:43 example dockerd[26445]: time="2017-08-03T04:29:43.019618873Z" level=debug msg="Query internal.com.[28] from 172.18.0.3:40098, forwarding to udp:8.8.8.8"
```

The first created network `10.0.0.0` occupies the same ip range as the DNS server `10.0.0.100`.

Thank you for helping me catch this error.

**Comment by thaJeztah** [comment] 2017-08-03 06:24
Oh, that would explain; I considered that possibility, but your earlier examples showed `192.0.0.100`, not `10.0.0.100` for the DNS

**Comment by mahnunchik** [comment] 2017-08-03 07:10
Yep, I replaced the real ip and did not think that it could make a difference.

**Comment by mahnunchik** [comment] 2017-08-03 07:10
Yep, I replaced the real ip and did not think that it could make a difference.
