### ISSUE TITLE
Docker -device command line doesn't throw invalid argument error

### ISSUE THREAD

**Issue by ajbarb** [moby/moby#39319] opened 2019-06-04 17:38 UTC
I am trying to expose a device interface to a process isolated windows container. I am using 1903 container image and if I use the below command, the device is not exposed to the container:

**NOT WORKING:**
**docker run -it "--isolation=process" -device="class/86E0D1E0-8089-11D0-9CE4-08003E301F73" mcr.microsoft.com/windows:1903**

Expected result: docker.exe should throw an error if the **device** argument type is invalid.
Actual result: Container launches silently without error but the device interface is not exposed.

If I use the below command it works:

**WORKING:**
**docker run -it --device "class/86E0D1E0-8089-11D0-9CE4-08003E301F73" --isolation process mcr.microsoft.com/windows:1903**

Docker.exe silently launching the container and not throwing an error makes it hard to debug why the device interface is not exposed.

Docker version: 19.03 (Edge channel)
Container Isolation: Process
Windows container version: 1903

**Comment by thaJeztah** [comment] 2019-06-08 21:13
Reading on my phone, so just double checking, but the difference between the "working" and "non working" version is that the `-device` option uses as single hyphen (`-`) instead of two, correct?

**Comment by ajbarb** [comment] 2019-06-08 21:32
That is correct.

**Comment by thaJeztah** [comment] 2019-06-12 15:04
Ah, I know what's happening; here's a simplified example (on Linux, but should be similar on windows);


```bash
docker run -it -device="class/86E0D1E0-8089-11D0-9CE4-08003E301F73" --name example nginx:alpine
```

So, what's happening is that both `-d` (shorthand for `--detach`) and `-e` (shorthand for `--env`) are valid flags.

Shorthand (single-character, single hyphen (`-`)) flags can be concatenated, so `-i -t` can be written as `-it`. And that's what happens in this case;

So this:

```
-device="class/86E0D1E0-8089-11D0-9CE4-08003E301F73"
```

Is expanded to;

```
-d -e=evice="class/86E0D1E0-8089-11D0-9CE4-08003E301F73"
```

If you inspect the container, you'll see that that's what's set as an environment variable;

```bash
docker inspect --format '{{json .Config.Env}}' example

["vice=class/86E0D1E0-8089-11D0-9CE4-08003E301F73","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","NGINX_VERSION=1.15.12"]
```

So, it's not a bug, but I can see this being surprising 😅. I'll close this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2019-06-12 15:04 UTC

**Comment by shrivam13** [comment] 2025-02-07 19:09
> Ah, I know what's happening; here's a simplified example (on Linux, but should be similar on windows);
> 
> docker run -it -device="class/86E0D1E0-8089-11D0-9CE4-08003E301F73" --name example nginx:alpine
> So, what's happening is that both `-d` (shorthand for `--detach`) and `-e` (shorthand for `--env`) are valid flags.
> 
> Shorthand (single-character, single hyphen (`-`)) flags can be concatenated, so `-i -t` can be written as `-it`. And that's what happens in this case;
> 
> So this:
> 
> ```
> -device="class/86E0D1E0-8089-11D0-9CE4-08003E301F73"
> ```
> 
> Is expanded to;
> 
> ```
> -d -e=evice="class/86E0D1E0-8089-11D0-9CE4-08003E301F73"
> ```
> 
> If you inspect the container, you'll see that that's what's set as an environment variable;
> 
> docker inspect --format '{{json .Config.Env}}' example
> 
> ["vice=class/86E0D1E0-8089-11D0-9CE4-08003E301F73","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","NGINX_VERSION=1.15.12"]
> So, it's not a bug, but I can see this being surprising 😅. I'll close this issue because of the above, but feel free to continue the conversation

Hey,

I have a similar issue, can you please check what am I doing wrong? [Here](https://github.com/moby/moby/discussions/49412) Thank you
