### ISSUE TITLE
Docker keeps old replicas hanging around after redeploy of services

### ISSUE THREAD

**Issue by jektvik** [moby/moby#43721] opened 2022-06-13 22:19 UTC
**Description**

Docker keeps old replicas hanging around after redeploy of services

**Steps to reproduce the issue:**
I don't know how to reproduce it without sharing a ginormous amounts of setup and code. 
1. My app is deployed through Caprover.
2. It's configured to run as a single replica
3. Each subsequent deploy of new image, the old one stays around as additional replicas and wreacks havoc on my reverse proxy

**Describe the results you received:**
Replica count keeps rising on each new deploy.

**Describe the results you expected:**
Its configured to be only 1 replica, it should stay so after redeploy.

**Additional information you deem important (e.g. issue happens only occasionally):**

From the author of caprover:
> CapRover uses service update; the CLI equivalent is docker service update --image new-image-name srv-captain--someapp

```
ubuntu@ubuntu:~$ docker service ls | grep srv-captain--scandegrator
xw28vw035h42   srv-captain--scandegrator                 replicated   2/2        ghcr.io/jektvik/img-captain-scandegrator:8
```
and
```
ubuntu@ubuntu:~$ docker service inspect --pretty srv-captain--scandegrator

ID:             xw28vw035h42lyw89thq9bmxj
Name:           srv-captain--scandegrator
Service Mode:   Replicated
 Replicas:      1
UpdateStatus:
 State:         paused
 Started:       2 weeks ago
 Message:       update paused due to failure or early termination of task zf8p8xdkzyelp3svp4u8g65u9
Placement:
UpdateConfig:
 Parallelism:   0
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      start-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         ghcr.io/jektvik/img-captain-scandegrator:8
 Env:           NODE_ENV=production NODE_MODULES_CACHE=false NPM_CONFIG_PRODUCTION=false HOST=0.0.0.0 PORT=8080
Log Driver:
 Name:          json-file
 LogOpts:
  max-size:       512m

Resources:
Networks: captain-overlay-network
Endpoint Mode:  vip

```

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Output of `docker info`:**

```

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 166
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: qt9i942s9bcravvsucxt1xv56
  Is Manager: true
  ClusterID: oxbu0pjtmht8dgjel0fbkucur
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.0.62
  Manager Addresses:
   192.168.0.62:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1042-raspi2
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.703GiB
 Name: ubuntu
 ID: PAOI:EOTO:MQPN:6UZQ:UAII:TUYY:HURM:M6YH:QZIA:HRWC:AFDM:IQSL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a docker swarm made up of raspberry PIs

**Comment by thaJeztah** [comment] 2022-06-30 10:21
It looks like this is running an older version of the daemon (19.03), which is no longer maintained; if you are able to consistently reproduce this and have a test-environment, are you still able to reproduce this issue on a current version of Docker (20.10 or up)?

**Comment by jektvik** [comment] 2022-07-04 22:00
Went upgrading. Circumnavigated the globe in the meantime. Done upgrading (and restoring all that broke in the process). The issues seems to be gone now after the upgrade to 20.x. I guess it may be closed if 19 isn't maintained no more.

**Comment by sam-thibault** [comment] 2022-12-08 11:32
Right, version 19 is no longer supported.  We will close this one.  Thanks.

**Closed by sam-thibault** 2022-12-08 11:32 UTC
Labels: status/more-info-needed, area/swarm, version/19.03
