### ISSUE TITLE
The meaning and purpose of the volume field of the dockerfile file

### ISSUE THREAD

**Issue by cai-hd** [moby/moby#41843] opened 2020-12-28 08:33 UTC
**Description**

**Steps to reproduce the issue:**
1.When I run the container using the mysql:5.7.32 image, like this:

docker run -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7.32

When I run a new container every time. A new volume will be generated in the /var/lib/docker/volume directory,
I understand this because there is a data volume declared in the dockerfile file.

![image](https://user-images.githubusercontent.com/44453960/103201157-2a2d5480-492a-11eb-8caf-dfdf15c6a5e3.png)

But I have two questions.

What is the purpose of this anonymous volume ？
When I started the container, the volume generated was about 200MB. I deleted the container, but the volume still exists and I need to delete it manually. What is the meaning of this design?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:37:17 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:35:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 12
  Running: 6
  Paused: 0
  Stopped: 6
 Images: 5
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.11.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.777GiB
 Name: localhost.localdomain
 ID: ABQO:X3KQ:GF2Y:DEKY:N3ZM:6TEJ:UQ7J:YNXW:GUMP:NFJS:XDVE:J3VH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2021-01-07 21:40
Mostly historical/backwards compat.

You can usually safely remove with `docker rm -v <container>` and all the anonymous volumes will go away with it.

**Comment by thaJeztah** [comment] 2021-01-08 13:20
Generally, stateful data should be kept out of the container's filesystem, and stored in a volume. There's some reasons for that;

- performance: storing data in the container's copy-on-write filesystem can have a significant overhead (depends on the storage-driver that's used)
- persisting data beyond the container's lifecycle; when running (e.g.) a database container, you don't want the database to be gone if the container is removed. Storing the data in a volume allows the container to be removed (for example to replace the container with a new container, started from the a more current image with the latest patch version of mysql)

Some images define a volume location in the image's configuration to provide a useful "default"; so that a volume is automatically created if the user did not pass `-v / --volume xx` or `--mount` flags when starting the container; in that case, an anonymous volume is created; for persistent data, it is generally recommended to attach a _named_ volume instead (to give a meaningful name to the data that's stored).

"anonymous" volumes are generally used for "ephemeral" volumes; perhaps a container needs to have some space to write data, but the data does not have to be persisted (but using a volume could still have benefits for performance (skipping the copy-on-write filesystem)).
They can also be useful to allow running a container with `--read-only`; the container's filesystem will then be read-only, and (anonymous) volumes are attached to paths that must be writeable.

**Comment by thaJeztah** [comment] 2021-01-08 13:20
Let me close this ticket, because this looks like a question, not a bug-report or feature request, but feel free to continue the conversation

**Closed by thaJeztah** 2021-01-08 13:20 UTC
Labels: area/volumes, kind/question
