### ISSUE TITLE
Godoc for client package is down

### ISSUE THREAD

**Issue by davemachado** [moby/moby#36252] opened 2018-02-08 20:04 UTC
<img width="1104" alt="screen shot 2018-02-08 at 3 01 14 pm" src="https://user-images.githubusercontent.com/15134885/35995402-32453670-0ce1-11e8-848b-14d1cc3b1e38.png">
**Description**

Godoc is down for client reference

**Steps to reproduce the issue:**
1. https://godoc.org/github.com/docker/docker/client
2. view the empty chasm that is a 404 error

Other packages are listed fine on Godoc currently and I was able to view the docs just the other day perfectly fine, so I am guessing that something changed in the commits merged into `master` today...

**Comment by cpuguy83** [comment] 2018-02-08 20:09
I'm assuming this is caused by our change to use canonical import paths, combined with the GH redirect for github.com/docker/docker. 😟 

Thanks for reporting.

**Comment by yxwzaxns** [comment] 2018-02-09 09:38
When will it be fixed?

**Comment by davemachado** [comment] 2018-02-09 15:13
@cpuguy83 , I am happy to help with the import path work, but I'm not sure what can be done about the redirect... 😢

**Comment by cpuguy83** [comment] 2018-02-09 15:37
As I see it...

Before canonical import path change:
- godoc reported incorrect package names
- lots of people were importing the wrong package path (or trying to and opening issues when it didn't work)

After canonical import path change:
- importing from github.com/moby/moby gives a nice error message
- godoc is broken

---

I think godoc being completely broken is worse than import path issues.
Likely we should revert.

ping @moby/moby-maintainers

**Comment by dnephin** [comment] 2018-02-09 16:13
It's strange that godoc worked for github.com/docker/docker before the canonical imports, but not after. I think it needs more investigation before we revert, but if there is no solution I agree it's better to have godoc.

**Comment by cpuguy83** [comment] 2018-02-09 16:30
Before godoc used to redirect to moby/moby because that's what GH does.
Now with the canonical import pointing to docker/docker I think it's just confusing it.

**Comment by dnephin** [comment] 2018-02-09 20:29
This seems like a bug in godoc.org. `go get` works just fine.

I believe the problem is this line: 
https://github.com/golang/gddo/blob/9b12a26f3fbd7397dee4e20939ddca719d840d2a/gosrc/github.go#L131

It assumes that any mismatch is because of case, but it could be due to a direct. Changing this to use `strings.EqualFold()` fixes the problem. I'm going to submit a patch to see what they say.

**Comment by dnephin** [comment] 2018-02-14 22:11
This is fixed in godoc.org.

I see https://godoc.org/github.com/docker/docker/api/types is working again. Some urls (like https://godoc.org/github.com/docker/docker/client) may take some time to update because of github request limits.

**Closed by dnephin** 2018-02-14 22:11 UTC
Labels: area/docs

**Comment by davemachado** [comment] 2018-02-16 15:57
It's worth noting here that [https://godoc.org/github.com/docker/docker/client](https://godoc.org/github.com/docker/docker/client) works, but redirected [https://godoc.org/github.com/moby/moby/client](https://godoc.org/github.com/moby/moby/client) does not.

**Comment by thaJeztah** [comment] 2018-02-16 16:25
@davemachado can you explain what isn't working for you? Accessing that URL redirects me to the docker/docker godoc;

<img width="743" alt="screen shot 2018-02-16 at 17 24 58" src="https://user-images.githubusercontent.com/1804568/36317815-65fdecb0-133e-11e8-8546-4f8dcf294fb2.png">

**Comment by cpuguy83** [comment] 2018-02-16 16:28
First request to moby/moby/client failed for me, second request worked.

**Comment by davemachado** [comment] 2018-02-16 17:01
<img width="541" alt="screen shot 2018-02-16 at 11 57 27 am" src="https://user-images.githubusercontent.com/15134885/36319400-d06142ce-1310-11e8-941d-7d73c3d1ebfb.png">

It seems to be intermittent, since one attempt will work, then another won't, then it will again, etc. This is not an issue caused by this project (silly github redirects), but it may be something to look into it this problem persists.

**Comment by tiborvass** [comment] 2018-02-16 19:06
I can confirm the intermittent nature of the issue.
