### ISSUE TITLE
how to get image baseos From docker cli

### ISSUE THREAD

**Issue by duchuanLX** [moby/moby#42198] opened 2021-03-25 03:30 UTC
**Description**
how to get image baseos From docker cli

**Steps to reproduce the issue:**
1.docker inspect ，can not get dockefile From info
```json
[
    {
        "Id": "sha256:c4e2893b7f82e139179c1dbcbac9697c261bb59e881c9a059e12256985cf60fb",
        "RepoTags": [
            "daprio/dapr:0.11.3"
        ],
        "RepoDigests": [
            "daprio/dapr@sha256:0d5960ae41e5d76daeca88ac86c70872cbc89c23bbb36874ea36df4cac897152"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-10-23T21:24:10.876099805Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) COPY multi:19ccbd0a8167c01babf07e3b2ce85e262bc2303536a3e5ae0bb78a002cb31020 in / "
            ],
            "Image": "sha256:e70c3c997de26d23f581c175e5be727c101eaa32be5852ae4167cd99820d69e4",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "19.03.13",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "sha256:e70c3c997de26d23f581c175e5be727c101eaa32be5852ae4167cd99820d69e4",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 183751721,
        "VirtualSize": 183751721,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/d7e303a92c15e99ccc74cf6a83accc1a4d7cc2c3ce793e80f80f77d88e131be3/diff",
                "MergedDir": "/var/lib/docker/overlay2/07a1ba84332a01f2c93f4127fa714d564fb919f9fd336bca99dc8c1c09336d7f/merged",
                "UpperDir": "/var/lib/docker/overlay2/07a1ba84332a01f2c93f4127fa714d564fb919f9fd336bca99dc8c1c09336d7f/diff",
                "WorkDir": "/var/lib/docker/overlay2/07a1ba84332a01f2c93f4127fa714d564fb919f9fd336bca99dc8c1c09336d7f/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:7ed79e13378bb288ab47bde61204b9a0e55e7787d6f1fe86956b8e2848b62a55",
                "sha256:bbc01eb884baca56ae7d8162856a82304c53634f09fc14decf9997987d6f8705"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

2.
3.

**Describe the results you received:**
dockefile's From info

**Describe the results you expected:**
get image's baseos name

**Additional information you deem important (e.g. issue happens only occasionally):**
none

**Output of `docker version`:**
20.10.5

**Output of `docker info`:**
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 10
  Running: 0
  Paused: 0
  Stopped: 10
 Images: 52
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 5efdc0c5a42d7965141271448dba6af4e1429962
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-240.1.1.el8_3.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.648GiB
 Name: master
 ID: QZRR:ND22:UGDV:HH6U:HZ3L:EPXJ:X4CP:KMAP:INHI:KXEK:GGWB:IOIJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: duchuandj
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://****.mirror.aliyuncs.com/
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centos 7.6

**Comment by thaJeztah** [comment] 2021-03-26 01:19
That image may be a base image by itself; either from a mult-stage build, or by copying an existing rootfs tar ball into the image; if you look at `docker image history` for the image (or look ok docker hub); https://hub.docker.com/layers/daprio/dapr/0.11.3/images/sha256-31d92732d5b7d1eee0007b98fb47dcf5afbe88b6ff94302ff3b37d4763e22701?context=explore

You can see that the image was created from a COPY command with the rootfs.

![601C3ABF-32D8-4783-AB04-5A8FCBEC830E](https://user-images.githubusercontent.com/1804568/112563080-f357c500-8dd8-11eb-8590-22255600b4fe.jpeg)

**Comment by thaJeztah** [comment] 2021-03-26 01:20
I think the github repository is https://github.com/dapr/dapr/

And here's the dockerfile (multi stage build)  https://github.com/dapr/dapr/blob/master/docker/Dockerfile

and a related makefile; https://github.com/dapr/dapr/blob/master/docker/docker.mk

**Comment by thaJeztah** [comment] 2021-03-26 01:21
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2021-03-26 01:21 UTC
Labels: kind/question

**Comment by duchuanLX** [comment] 2021-03-26 09:16
> Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
> but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;
> 
> * the Docker Support Forums - https://forums.docker.com
> * the [Docker community Slack channel](http://dockr.ly/slack)
> 
> I'm closing this issue because this is not a bug, but feel free to continue the conversation


Maybe my expression is not clear enough,
How to get the baseos information of the docker image through the docker command.
Does the docker inspect command add a multi from field to display the From information in the dockerfile?
