### ISSUE TITLE
docker pull does download and extraction sequentially

### ISSUE THREAD

**Issue by Optiligence** [moby/moby#37957] opened 2018-10-03 04:02 UTC
Especially with larger images download and decompression can take a significant amount of time. 
It would be nice if those times wouldn’t add up unnecessarily. 
As far as i know the layers are compressed tar archives, where download and extraction can easily be piped. 

Is there a reason this is done sequentially? Are the uncompressed layers used for something?

**Comment by thaJeztah** [comment] 2018-10-03 13:16
What version of Docker are you running? Current versions of Docker will _pull_ layers in parallel, but extracting would still be done sequential; see https://github.com/moby/moby/issues/21814 for some background.

Decompression performance itself can be improved by installing `pigz` on the host; https://github.com/moby/moby/pull/35697, which (if installed) will be taken advantage of. 


The number of pulled (or pushed) being performed in parallel is configurable; by default 5 pulls, and 3 pushes are done concurrently, but this is configurable as a daemon option (either by setting a flag, or through a configuration option in the `daemon.json` configuration file);

https://docs.docker.com/engine/reference/commandline/dockerd/

```
      --max-concurrent-downloads int          Set the max concurrent downloads for each pull (default 3)
      --max-concurrent-uploads int            Set the max concurrent uploads for each push (default 5)
```

Also see https://github.com/moby/moby/issues/150, https://github.com/moby/moby/pull/1290, https://github.com/moby/moby/issues/25679

**Comment by Optiligence** [comment] 2018-10-06 01:39
Thanks for the infos. 

I use 18.06.1-ce on my own system and 17.09.0-ce on travis. 

I installed `pigz` but it doesn’t seem to change anything – time-wise. (It’s a little hard to measure, since the pull operation also includes the download)

Ftr: me using the word »sequentially« isn’t meant to be »using a single vs multiple cpu cores« but »waiting for the download to complete before decompression vs decompressing the data as it comes in«. 

To give perspective: the image i’m using for this has only 1 layer sized 750 MB. 

Probably ⅓ of the time is download and ⅔ extraction. That means piping these would decrease the time by 33% with the same CPU stress and however much ram is needed for the download on top of the decompression memory requirement while lifting load from the network (because that’s capped by the slower decompression).

**Comment by cpuguy83** [comment] 2018-10-06 18:06
"Extraction" in this case is extracting the layer data to the storage driver, which must be sequential.
This could potentially be optimized by storing the layers uncompressed and moving them to the storage driver, but this comes with a pretty large trade-off in storage requirements during pull.

**Comment by robin-thoni** [comment] 2020-04-07 09:03
> That won't be possible, because docker will do checksum verification of the compressed layer before it's being extracted

What about uncompressing during download, but also keeping the compressed archive too for checksum validation? At the end, it's using the same disk space, as for a moment, both compressed and uncompressed data will be on the disk. We're now 2020, I think we can consider connections way more reliable than two decades ago, especially if the registry is local. Defaulting to consider the archive as correct unless proven otherwise at the end of download can be a reasonable choice? Do you gather stats on failed checksum tests?


Also, is there anything preventing *uncompressing* in parallel? Consider the following case on the current implementation:
![Docker pull-Current](https://user-images.githubusercontent.com/9640353/78649118-e9317380-78b4-11ea-9203-dfeffee2f4a3.png)

We could "easily" win a lot of time by, either extracting while downloading:

![Docker pull-Extract Download prallel](https://user-images.githubusercontent.com/9640353/78649222-0f571380-78b5-11ea-8688-bb449f5fd476.png)

Or at least uncompressing multiple layers in parallel:

![Docker pull-Extract parallel](https://user-images.githubusercontent.com/9640353/78649214-0c5c2300-78b5-11ea-85a5-8659bf4d5a4f.png)

Of course, I made the assumption for those graphs that none of the tasks done in parallel are slowing down the other ones. That is probably wrong for uncompressing, above a certain amount of tasks, as it will use both CPU and IO. Downloading and extracting at the same time _might_ be ok on modern machines, though.

In anyway, sometimes, just *one* layer will take forever to download, ad during that time, docker could start uncompressing other layers, in order to hide this slowness.

Any thought?

**Comment by thaJeztah** [comment] 2020-04-07 10:17
containerd keeps the uncompress artefacts on disk when pulling images; dockerd currently uses its own image management, but that would change it switches to use the containerd image management / store

**Comment by robin-thoni** [comment] 2020-04-08 09:29
It's unclear to me what the outcome of your comment is. Are you saying Docker will change its image management system (soon?), and the behaviors we're talking about will be changed too? In that case, I guess this request shall be moved to containerd?

**Comment by thaJeztah** [comment] 2020-04-08 10:03
Docker will move to integrate with containerd's image management. I don't have an ETA for that, because the change is complicated to provide migration to the new store.

There's no plans to change the current implementation in docker itself.

> I guess this request shall be moved to containerd?

Possibly containerd already has your issue addressed; you can try how containerd handles image pulls using the `ctr` command line client, for example:

```bash
ctr image pull docker.io/library/ubuntu:20.04
```

Note that;

- containerd (and the `ctr` client) expects fully qualified image references (e.g. `docker.io/library/ubuntu:20.04` instead of `ubuntu:20.04`)
- the image that's pulled will be stored in containerd's image store (so won't be visible in `docker images` / `docker image ls`); to remove the image, use the `ctr image rm` subcommand)

**Comment by zhxqgithub** [comment] 2020-05-08 10:18
we have the same issue. Extracting so slowly however the download blob very quick. my docker version is 
```
Client: Docker Engine - Community
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        
 Built:             Mon May 13 13:00:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Mon May 13 13:00:56 2019
  OS/Arch:          linux/am
```

I get the profile from dockerd,found that the waste much time on 'compress/flate.(*decompressor).huffSym'
```
go tool pprof profile         
File: dockerd
Build ID: e43f143ab79cbdd1dae2e51375f8276aca644f9d
Type: cpu
Time: May 8, 2020 at 2:36pm (CST)
Duration: 30s, Total samples = 12.34s (41.13%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 9290ms, 75.28% of 12340ms total
Dropped 231 nodes (cum <= 61.70ms)
Showing top 10 nodes out of 138
      flat  flat%   sum%        cum   cum%
    2330ms 18.88% 18.88%     4220ms 34.20%  compress/flate.(*decompressor).huffSym
    1750ms 14.18% 33.06%     1750ms 14.18%  crypto/sha256.block
    1030ms  8.35% 41.41%     2080ms 16.86%  compress/flate.(*decompressor).moreBits
     990ms  8.02% 49.43%     6240ms 50.57%  compress/flate.(*decompressor).huffmanBlock
     980ms  7.94% 57.37%     1050ms  8.51%  bufio.(*Reader).ReadByte
     590ms  4.78% 62.16%      620ms  5.02%  syscall.Syscall
     520ms  4.21% 66.37%      520ms  4.21%  runtime.futex
     450ms  3.65% 70.02%      450ms  3.65%  runtime.memmove
     400ms  3.24% 73.26%      400ms  3.24%  hash/crc64.update
     250ms  2.03% 75.28%      250ms  2.03%  compress/flate.(*dictDecoder).writeByte (inline)
```


Is there huffSyn function has bug?

**Comment by Optiligence** [comment] 2020-05-10 18:41
@thaJeztah i wanted to try out `ctr` but i have no clue how to get a _fully qualified image reference_ for something on dockerhub.

**Comment by thaJeztah** [comment] 2020-05-10 18:45
Put `docker.io/` before the image name; so

`myname/myimage:latest` -> `docker.io/myname/myimage:latest`

if it's an official image from docker hub (eg "ubuntu", then you need to add `docker.io/library/` before it, so:

`ubuntu:18.04` -> `docker.io/library/ubuntu:18.04`

**Comment by Optiligence** [comment] 2020-05-10 19:18
huh, next to [docker.io/library/](docker.io/library/) i only tried putting various variations of [hub.docker.com/](hub.docker.com/)

[docker.io/](docker.io/) without `library` does indeed work

however, i’m not sure how to interpret what `ctr` is doing, as it only prints »unpacking« once at the end and that takes 2 minutes…

i assume it’s neither decompressing any layer _directly_ after downloading, let alone while downloading

if »unpacking« only means merging of already extracted layers, it would incredibly slow

**Comment by zhxqgithub** [comment] 2020-05-11 08:56
@thaJeztah  At last,we root cause why extracting blob slowly. The reason is that:
In my /proc/self/mountinfo ,there are about 3w+ /dev/shm mount infos. It is slowly when parseMountTable. 


the picture show the perf of /prco/self/exe process:
![image](https://user-images.githubusercontent.com/8119309/81541585-e7703980-93a5-11ea-8922-816857aeab06.png)





The image pulled normal when umount /dev/shm.

**Comment by thaJeztah** [comment] 2020-05-11 11:36
> there are about 3w+ /dev/shm mount infos. It is slowly when parseMountTable.

Is it expected that your machine had those `/dev/shm` mounts, or were they possibly leaking? I think it's a known issue that in situations `/dev/shm` mounts end up in other namespaces (which could be if a container mounts `/dev` or `/`), that those mounts can't be unmounted afterwards. https://github.com/moby/moby/pull/34087 was created to allow `/dev/shm` to be "private" by default (but this may not be an option if you're running kubernetes, as pods may be sharing `/dev/shm`)

/cc @kolyshkin (who should have more background on this; perhaps I phrased it incorrect)

**Comment by zhxqgithub** [comment] 2020-05-12 01:44
The docker leaking was excluded since we restart docker (also I drained the pod on this problem node)and found that the mount number of /dev/shm does not decreased. It was slowly when pulling image at the same time after restart docker. The leaking  were not expected  dut to creating by out component.

**Comment by sam-thibault** [comment] 2023-04-25 09:47
I will close this issue, since there is already the `max-concurrent-downloads` option to improve performance here.  As @cpuguy83 mentioned above:

> "Extraction" in this case is extracting the layer data to the storage driver, which must be sequential. This could potentially be optimized by storing the layers uncompressed and moving them to the storage driver, but this comes with a pretty large trade-off in storage requirements during pull.

**Closed by sam-thibault** 2023-04-25 09:47 UTC
Labels: area/distribution, kind/enhancement, area/performance
