### ISSUE TITLE
[libnetwork panic] Crash on startup with latest master builds

### ISSUE THREAD

**Issue by stgraber** [moby/moby#40634] opened 2020-03-06 14:24 UTC
The LXD team runs a daily test of Docker inside LXD privileged and unprivileged containers.
The source of the test is at: https://github.com/lxc/lxc-ci/blob/master/bin/test-lxd-docker
The jenkins output at: https://jenkins.linuxcontainers.org/job/lxd-test-docker/

Starting today (March 6th), we're seeing startup failures on Docker in both our tests.

The associated stacktrace is:

```
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: panic: interface conversion: interface {} is nil, not bool
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: goroutine 1 [running]:
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*networkConfiguration).UnmarshalJSON(0xc0004b92b0, 0xc0009bc1a0, 0x189, 0x189, 0x7fcf98
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:201 +0xb9a
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: encoding/json.(*decodeState).object(0xc0003fb080, 0x2df71a0, 0xc0004b92b0, 0x16, 0xc0003fb0a8, 0xc0009ab07b)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /usr/local/go/src/encoding/json/decode.go:667 +0x220d
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: encoding/json.(*decodeState).value(0xc0003fb080, 0x2df71a0, 0xc0004b92b0, 0x16, 0xc000ada4f8, 0x5705bb)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /usr/local/go/src/encoding/json/decode.go:429 +0x6f
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: encoding/json.(*decodeState).unmarshal(0xc0003fb080, 0x2df71a0, 0xc0004b92b0, 0xc0003fb0a8, 0x0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /usr/local/go/src/encoding/json/decode.go:179 +0x1fd
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: encoding/json.Unmarshal(0xc0009bc1a0, 0x189, 0x189, 0x2df71a0, 0xc0004b92b0, 0x2e753a0, 0xc0004b92b0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /usr/local/go/src/encoding/json/decode.go:106 +0x114
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*networkConfiguration).SetValue(0xc0004b92b0, 0xc0009bc1a0, 0x189, 0x189, 0x1, 0x1)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:231 +0x57
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*cache).kmap(0xc00000fec0, 0x2f87440, 0xc0004b8dd0, 0x0, 0x1b, 0xc000983080)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/cache.go:61 +0x33c
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*cache).list(0xc00000fec0, 0x2f87440, 0xc0004b8dd0, 0x0, 0x0, 0x0, 0x0, 0x0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/cache.go:164 +0x7e
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).List(0xc0009db680, 0xc000983080, 0x1b, 0x2f87440, 0xc0004b8dd0, 0x0, 0x0, 0x0, 0
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:517 +0x205
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).populateNetworks(0xc000167aa0, 0x5, 0x1ebbd5e)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:50 +0x1d7
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).initStore(0xc000167aa0, 0xc000af4660, 0x0, 0xc0005f60c0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:35 +0x211
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).configure(0xc000167aa0, 0xc000af4660, 0x2abde60, 0xc000af4390)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:388 +0x17f
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.Init(0x2f30740, 0xc000913380, 0xc000af4660, 0xc000af4660, 0x0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:163 +0x9c
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry.(*DrvRegistry).AddDriver(...)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go:72
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc000050a00, 0x9, 0x10, 0xc000831950, 0xc000af4330, 0xc000050a00, 0x9)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:220 +0x4f0
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc00000c5a0, 0xc0000d3080, 0xc000af4330, 0x0, 0x0, 0x0, 0x0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/daemon/daemon_unix.go:890 +0xa9
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/daemon.(*Daemon).restore(0xc00000c5a0, 0xc0007e7180, 0xc0009ce000)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/daemon/daemon.go:468 +0x50b
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/daemon.NewDaemon(0x2f5b540, 0xc0007e7180, 0xc0000d3080, 0xc000831950, 0x0, 0x0, 0x0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/daemon/daemon.go:1096 +0x2ab3
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: main.(*DaemonCli).start(0xc000831710, 0xc0007392c0, 0x0, 0x0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:199 +0x74c
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: main.runDaemon(...)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: main.newDaemonCommand.func1(0xc00082e500, 0xc0008316b0, 0x0, 0x3, 0x0, 0x0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7c
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc00082e500, 0xc00004e0d0, 0x3, 0x3, 0xc00082e500, 0xc00004e0d0)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:762 +0x462
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00082e500, 0x0, 0x0, 0x10)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:800
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]: main.main()
Mar 06 14:19:47 docker-1c285a5e-4ca2-4f9d-a8f9-5b88ed62a65a dockerd[1434]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x191
```

Hopefully between the time at which we've noticed this change and the stacktrace above, the issue can easily be tracked down.

We care about this use case as Travis-CI foreign architecture support runs on LXD and a lot of Travis jobs use Docker, so we're trying to catch things early by testing the master snapshots.

**Comment by AkihiroSuda** [comment] 2020-03-06 15:14
Potentially https://github.com/moby/moby/commit/cc2d166cfd6185059c729173f33db13eeab00695  might be causing  this, but doesn't seem to be related to libnetwork 🤔

**Comment by thaJeztah** [comment] 2020-03-06 15:29
ping @arkodg @selansen @euanh ptal

**Comment by arkodg** [comment] 2020-03-06 15:34
most likely fixed by https://github.com/moby/libnetwork/commit/44534f1a561892465216e4a7c3af3b05ab51bfdc

**Comment by AkihiroSuda** [comment] 2020-03-06 15:38
Bisected, caused by https://github.com/moby/moby/commit/feed3daecf6f86bf8fdc31320742828c02156ae9

**Comment by thaJeztah** [comment] 2020-03-06 16:00
@SamWhited ^^

**Comment by AkihiroSuda** [comment] 2020-03-12 19:43
Should be fixed in https://github.com/moby/libnetwork/pull/2511 (19.03: https://github.com/moby/libnetwork/pull/2520)

**Closed by AkihiroSuda** 2020-03-12 19:43 UTC
Labels: area/networking, kind/bug, priority/P0, version/master

**Comment by thaJeztah** [comment] 2020-03-12 19:45
19.03 will be fixed once https://github.com/moby/moby/pull/40617 is merged

**Comment by thaJeztah** [comment] 2020-03-12 19:46
actually; 19.03 never had the regression, so ignore that

**Comment by arkodg** [comment] 2020-03-12 19:46
@AkihiroSuda  and @thaJeztah  this issue is not seen and unrelated to 19.03

**Comment by arkodg** [comment] 2020-03-12 19:46
ah you beat me to it
