### ISSUE TITLE
extra_hosts doesn't work when buildkit is enabled

### ISSUE THREAD

**Issue by ahmedbilal** [moby/moby#43179] opened 2022-01-24 06:57 UTC

**Comment by thaJeztah** [comment] 2023-03-07 12:07
What version of Docker and Docker Compose are you running? This feature has been implemented in BuildKit in https://github.com/moby/buildkit/pull/553

I tried this with `docker build`, and that looks to be supported (`hello` shows up as host in `/etc/hosts`);

```dockerfile
FROM alpine
RUN cat /etc/hosts
```

With BuildKit disabled:

```bash
DOCKER_BUILDKIT=0 docker build --add-host "hello:192.168.1.1" --no-cache --progress=plain .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
---> b2aa39c304c2
Step 2/2 : RUN cat /etc/hosts
---> Running in bb85aa692d02
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.1.1	hello
172.17.0.2	bb85aa692d02
Removing intermediate container bb85aa692d02
```

With BuildKit enabled:

```bash
DOCKER_BUILDKIT=1 docker build --add-host "hello:192.168.1.1" --no-cache --progress=plain .

#2 [internal] load .dockerignore
#2 sha256:4366a99d44bf761e3531e1454b24703f6418ae51f32cee041f8b03362d5a04fe
#2 transferring context: 2B done
#2 ...

#1 [internal] load build definition from Dockerfile
#1 sha256:1cadf0074f9f233250c30a748d8f64808a1f1a43dab5b5be668345dd90d771f7
#1 transferring dockerfile: 68B 0.0s done
#1 DONE 0.3s

#2 [internal] load .dockerignore
#2 sha256:4366a99d44bf761e3531e1454b24703f6418ae51f32cee041f8b03362d5a04fe
#2 DONE 0.5s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 sha256:d4fb25f5b5c00defc20ce26f2efc4e288de8834ed5aa59dff877b495ba88fda6
#3 DONE 0.0s

#4 [1/2] FROM docker.io/library/alpine
#4 sha256:665ba8b2cdc0cb0200e2a42a6b3c0f8f684089f4cd1b81494fbb9805879120f7
#4 CACHED

#5 [2/2] RUN cat /etc/hosts
#5 sha256:2205c7ce7c884d6e34b465f352f8ddd55cb8a155ae146ff7382e335fe03587bc
#5 0.589 127.0.0.1	localhost buildkitsandbox
#5 0.589 ::1	localhost ip6-localhost ip6-loopback
#5 0.589 192.168.1.1	hello
#5 DONE 0.7s

#6 exporting to image
#6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#6 exporting layers 0.1s done
#6 writing image sha256:a3e6bd528dfc39e61733ef86525a2e9c61eae52557974c765837f4e4d01cbc73
#6 writing image sha256:a3e6bd528dfc39e61733ef86525a2e9c61eae52557974c765837f4e4d01cbc73 done
#6 DONE 0.1s
```


I also tried this with `docker compose` (v2.16), using this compose-file:

```yaml
services:
  foo:
    build:
      context: .
      extra_hosts:
        - "hello:192.168.1.1"
```

```bash
docker compose version
Docker Compose version v2.16.0

docker compose build --no-cache --progress=plain
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 31B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 0.0s

#4 [1/2] FROM docker.io/library/alpine
#4 CACHED

#5 [2/2] RUN cat /etc/hosts
#5 0.333 127.0.0.1	localhost buildkitsandbox
#5 0.333 ::1	localhost ip6-localhost ip6-loopback
#5 0.333 192.168.1.1	hello
#5 DONE 0.5s

#6 exporting to image
#6 exporting layers 0.1s done
#6 writing image sha256:aacec61a0afbbf8eb1b8683844726ecda858bc4ccde3cc84db1df533f1294f29 done
#6 naming to docker.io/library/compose-foo done
#6 DONE 0.1s
```

**Comment by thaJeztah** [comment] 2023-03-07 12:07
I'm closing this ticket, as I cannot reproduce this issue, but feel free to comment if you have more information

**Closed by thaJeztah** 2023-03-07 12:07 UTC
Labels: area/builder, status/more-info-needed, kind/bug, area/builder/buildkit
