### ISSUE TITLE
Support multiple container repositories with shared code.

### ISSUE THREAD

**Issue by tristanz** [moby/moby#12971] opened 2015-05-04 21:17 UTC
There is currently no easy way to build multiple containers from a single repository if containers share code.  This seems like a very common pattern:

```
docker-compose.yml
container1/
  - Dockerfile
container2/
  - Dockerfile
shared/
  - library
```

What is the recommended way to support this repository structure?

To list potential solutions and problems with them:
- Named dockerfiles (-f) do not support specifying separate dockerignores.
- Symlinks are not dereferenced as part of build context.
- Relative paths for ADD cannot escape build context.
- Copying files with a prebuild script breaks docker-compose flow.
- Splitting into multiple repositories and using submodules is painful at scale.
- Piping a dereferenced tar file into docker build does not work with docker-compose.
- Bind mounting instead of symlinks only works on Linux.

Does the docker core team have a proposal to address this so that we can push forward an implementation?

**Comment by bobby** [comment] 2015-05-06 00:54
+1, I just ran into this and am bending my dev workflow around this issue as we speak.  Is there a viable workaround that anyone can recommend?

**Comment by duglin** [comment] 2015-05-06 01:58
@tristanz I want to make sure we're on the same page w.r.t. the issues here.

First, given the structure you show in your example, that pattern should work as long as you kick off your build correctly and are willing to live with just one .dockerignore for all builds.  By that I mean: `docker build -f container1/Dockerfile .` where '.' is the root.  I don't know about the compose side of the problem but a set of stand-alone `docker build` commands should work.

**Comment by tristanz** [comment] 2015-05-06 05:24
@duglin I'm just looking for a "blessed" way, so that we can work out kinks.  If named dockerfiles (-f) is that way, then an --ignore-file option (#12886) seems worth pushing through.  I unfortunately can't just use a single .dockerignore since the entire repo is too large.  I'd need to have a per container .dockerignore.  I'd then build like: `docker build -f container1/Dockerfile -i container1/.dockerignore`.  I think that's a pretty good option.

**Comment by richburdon** [comment] 2015-09-06 22:25
@duglin I'm trying to resolve the same issue, but your suggestion doesn't work for me -- since ADD paths are relative to the Dockerfile. In any trivial test I get "no such file or directory" when trying to ADD paths from the root. Similarly relative paths are disallowed (for security reasons).

So I have the same problem: how can I factor out shared code to include into 2 different containers (e.g., Flask and Celery)?

**Comment by tristanz** [comment] 2015-09-06 23:11
@richburdon 

Potentially in the future: https://github.com/jlhawn/dockramp

Right now:  Tar things up yourself and pass it to the docker client.  

I personally have moved to have simple makefiles with things like so:

```
web:
	./bin/tar.sh web logger | docker build -t web -f web/Dockerfile -
```

tar.sh here is a hack to support not tarring stuff in .gitignore, but that's just an optimization:

```
#!/bin/bash

# Tar that ignores anything in .gitignore.  Note that bsdtar does not support
# --exclude-vcs and gnu-tar does not ignore matches in nested folders.  This is a 
# workaround.

# COPYFILE_DISABLE
# http://apple.stackexchange.com/questions/75989/why-does-osx-add-extra-filename-when-i-tar-a-directory
export COPYFILE_DISABLE=1 

filename=".gitignore"
cmd="tar -c"
while read -r line
do
    cmd="$cmd --exclude=$line"
done < "$filename"
$cmd $@
```

**Comment by LK4D4** [comment] 2016-11-28 19:48
@thaJeztah I'm not really familiar with compose. Maybe you have some info.

**Comment by timaschew** [comment] 2017-05-04 12:17
Are there any updates or other solutions?

**Comment by cpuguy83** [comment] 2017-05-04 12:32
Multi-stage builds seems like a valid way to handle this.

```Dockerfile
FROM img1 AS container1
COPY container1/* /somewhere
COPY shared/library /somewhere/library

FROM img2 AS container2
COPY container2/* /somewhere
COPY shared/library /somewhere/library
```

Then you can: 
```
docker build -t myContainer1 --target=container1 .
docker build -t myContainer2 --target=container2 .
```

Here `target=` would tells it to build some named stanza, which is named via the `FROM <img> AS <name>`
Note there's also a lot more you can do with multi-stage builds.

I think this satisfies this case and we can close? 🙏

**Comment by jrhdoty** [comment] 2018-07-09 03:51
@cpuguy83 , I believe this multi-stage build solution still causes the entire project directory (which may contain dozens or hundreds of independent buildable artifacts) to be loaded into the docker daemon. For a large monorepo this is infeasible. The problem is how to include multiple directories from the same level of the folder hierarchy in the docker context without including *all* folders at that level of the hierarchy.

```
/container-1-code
/container-2-code
/shared-lib
/large-shared-lib1
/large-shared-lib2
...
```

container-1 has a dependency on shared-lib and large-shared-lib1.
container-2 has a dependency on shared-lib and large-shared-lib2.

How can we limit the size of the docker context while still building multiple containers that share code? Using some other tooling to manually construct the required context like @tristanz TAR example above works in some cases but doesn't work with other useful tools e.g. docker-compose ([Issue 1209](https://github.com/docker/compose/issues/1209)). 

Dockeramp's 'no context uploads' approach looks like it may solve this problem but I haven't had a chance to experiment with it.

Please let me know if your proposal solves this problem and I'm misunderstanding it.

**Comment by cpuguy83** [comment] 2018-07-09 03:54
Docker has an experimental "--stream" flag which only copies what is requested in the Dockerfile to the daemon.

**Comment by thaJeztah** [comment] 2018-07-09 06:14
See this proposal https://github.com/moby/moby/issues/37129

 (I need to update it a bit based on the discussion there)

**Comment by thaJeztah** [comment] 2024-12-07 13:55
Looks like this is probably addressed by multiple context support;

- https://github.com/moby/buildkit/pull/2521

**Closed by thaJeztah** 2024-12-07 13:55 UTC
Labels: area/builder, kind/enhancement
