### ISSUE TITLE
Windows container logs getting mangled when written to disk

### ISSUE THREAD

**Issue by danfinn** [moby/moby#43514] opened 2022-04-21 15:02 UTC
We are running kubernetes in MS Azure.  Kubernetes version is 1.22.6.

Docker info from windows node:
```
Server:
 Containers: 15
  Running: 14
  Paused: 0
  Stopped: 1
 Images: 28
 Server Version: 20.10.9
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.2803)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4GiB
 Name: akswin000000
 ID: R7W5:SD3Q:6VDB:QK2A:EROA:ARXU:LNP7:3BMT:GI6P:YZRX:QNKZ:24PO
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

We use fluentd in our docker containers to monitor event logs and send them to STDOUT so that we can then capture these logs and ship them to elasticsearch.

If you view the container logs via kubectl or docker CLI commands the logs look like you would expect, here is a sample:
```
{"ProviderName":"Microsoft-Windows-LoadPerf","ProviderGUID":"","EventID":"1000","Level":"4","Task":"0","Opcode":"0","Keywords":"0x8000000000000000","TimeCreated":"2022/04/21 14:47:26.216129200","EventRecordID":"70","ActivityID":"","RelatedActivityID":"","ProcessID":"7808","ThreadID":"7964","Channel":"Application","Computer":"sample1-6bfc4cf5b4-hqvwq","UserID":"S-1-5-18","Version":"0","Description":"Performance counters for the WmiApRpl (WmiApRpl) service were loaded successfully. The Record Data in the data section contains the new index values assigned to this service.","EventData":["WmiApRpl","WmiApRpl","16","?"]}
{"ProviderName":"Service Control Manager","ProviderGUID":"","EventID":"1073748860","Level":"4","Task":"0","Opcode":"0","Keywords":"0x8080000000000000","TimeCreated":"2022/04/21 14:50:10.710553900","EventRecordID":"494","ActivityID":"","RelatedActivityID":"","ProcessID":"8300","ThreadID":"4524","Channel":"System","Computer":"sample1-6bfc4cf5b4-hqvwq","UserID":"","Version":"0","Description":"The RemoteRegistry service entered the stopped state.","EventData":["RemoteRegistry","stopped","?"]}
```

standard JSON logging which should be easily parsed by anything.  However the problem we are running into is that we are shipping the logs from how they get written to disk, under /var/log/containers.  Something (I suspect the docker log driver) is modifying these logs by adding escape and control characters.  When they get written to disk they look like this:

```
{"log":"{\"ProviderName\":\"Microsoft-Windows-LoadPerf\",\"ProviderGUID\":\"\",\"EventID\":\"1000\",\"Level\":\"4\",\"Task\":\"0\",\"Opcode\":\"0\",\"Keywords\":\"0x8000000000000000\",\"TimeCreated\":\"2022/04/21 14:47:26.216129200\",\"EventRecordID\":\"70\",\"ActivityID\":\"\",\"RelatedActivityID\":\"\",\"ProcessID\":\"7808\",\"ThreadID\":\"7964\",\"Channel\":\"Application\",\"Computer\":\"sample1-6bfc4cf5b4-hqvwq\",\"UserID\":\"S-1-5-18\",\"Version\":\"0\",\"Description\":\"Performance counters for the WmiApRpl (WmiApRpl) service were loaded successfully. The Record Data in the data section contains the new index values assigned to this service.\",\"EventData\":[\"WmiApRpl\",\"WmiApRpl\",\"16\",\"?\"]}\r\n","stream":"stdout","time":"2022-04-21T14:47:27.9395492Z"}
{"log":"{\"ProviderName\":\"Service Control Manager\",\"ProviderGUID\":\"\",\"EventID\":\"1073748860\",\"Level\":\"4\",\"Task\":\"0\",\"Opcode\":\"0\",\"Keywords\":\"0x8080000000000000\",\"TimeCreated\":\"2022/04/21 14:50:10.710553900\",\"EventRecordID\":\"494\",\"ActivityID\":\"\",\"RelatedActivityID\":\"\",\"ProcessID\":\"8300\",\"ThreadID\":\"4524\",\"Channel\":\"System\",\"Computer\":\"sample1-6bfc4cf5b4-hqvwq\",\"UserID\":\"\",\"Version\":\"0\",\"Description\":\"The RemoteRegistry service entered the stopped state.\",\"EventData\":[\"RemoteRegistry\",\"stopped\",\"?\"]}\r\n","stream":"stdout","time":"2022-04-21T14:50:11.9155008Z"}
```

As you can see, those 2 logs look quite different and this is wreaking havoc for our log parsing.  

I have opened up a support ticket with MS Azure on this as well and they are saying that we are seeing this because Windows nodes use Docker for container runtime which uses a different logging format than containerd.  Supposedly as of kubernetes 1.23 this will be fixed but I'm hoping to find a solution that doesn't require waiting on that.

**Comment by danfinn** [comment] 2022-04-21 16:09
I was somewhat suspecting that maybe fluentd was somehow causing this to happen so to rule that out I built a ltsc2019 container that uses [windows-container-tools](https://github.com/microsoft/windows-container-tools) to monitor logs and write them to STDOUT.  I see the same issue with this so I think this confirms that the issue is related to the way docker is logging on windows nodes.

**Comment by danfinn** [comment] 2022-06-24 17:33
Well this doesn't seem to be getting any attention but I have confirmed that this doesn't happen when running on containerd nodes.  Working on moving towards that as a way to solve this logging issue.

**Comment by thaJeztah** [comment] 2022-06-24 21:54
Thanks for opening this ticket; looking at your report, this is the expected behavior.

These files are the internal storage mechanism for the json-file logging driver, and meant a storage for the [`containers/{id}/logs`](https://docs.docker.com/engine/api/v1.41/#operation/ContainerLogs) API endpoint (which is used by the `docker logs` command). These files are designed to be exclusively accessed by the docker daemon, and not intended for external consumption (but we're aware that there are systems that may do so); see the [documentation for the json-file storage driver](https://docs.docker.com/config/containers/logging/json-file/)

> The json-file logging driver uses file-based storage. These files are designed to be exclusively accessed by the Docker daemon. Interacting with these files with external tools may interfere with Docker’s logging system and result in unexpected behavior, and should be avoided.

docker logging drivers capture the container's output on `STDOUT` and `STDERR` and are line-based; entries in the json-file log files on disk contain that output, as well as additional metadata used by docker internally (timestamp, metadata about the container), and the container's output may be split over multiple entries (partial messages), as there's a limit to the maximum size per entry, but gets reconstructed when reading back through the API.
The logging drivers make no assumption about the format of logs (output) of the container, so while your container may be printing output that's in a JSON format, from the logging driver's perspective, it's "a stream of output" that's captured and can be read back, and in case of the json-file logging driver, that output is stored in a file that uses JSON encoded entries as a storage mechanism.

To reconstruct the original output each entry would have to be unmarshalled;

```json
{
  "log": "LOG OUTPUT (json escaped string)",
  "stream": "stdout",
  "time": "2022-04-21T14:47:27.9395492Z"
}
```

The payload / log entry data can be found in the `log` field in the JSON, but may be split if the maximum length was exceeded, in which case no newline is present in the field. Where needed, characters will be escaped (https://www.json.org/json-en.html), so in case the log output happened to be JSON, quotes, and non-printable characters will be escaped (embedded JSON).

If the intent is to send container logs to a remote logging aggregator, you may be able to use one of the other logging drivers https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers, which allow sending logs directly to a remote service instead of scraping the json-file storage.

**Comment by thaJeztah** [comment] 2022-06-24 21:55
I'm closing this ticket as this is the expected behaviour, but hope the above helps, and feel free to continue the conversation

**Closed by thaJeztah** 2022-06-24 21:55 UTC
Labels: area/logging
