### ISSUE TITLE
Docker Stack: invalid mount target, must be an absolute path: /data/db

### ISSUE THREAD

**Issue by psyvision** [moby/moby#40255] opened 2019-11-26 10:26 UTC
**Description**

Using `docker deploy` to deploy a stack/service yields:

`invalid mount target, must be an sbsolute path: /data/db`

Whereas `docker run` works fine.

Sample docker service file (which doesn't work):

```
version: '3.7'

volumes:
  mongodata:

services:
  mongo:
    image: nexus.company.com:5000/mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR:/data/db
    volumes:
      - mongodata:/data/db
```

Sample docker run command (which works):

```
docker volume create --driver overlay mongovol
docker run -d -p 27018:27017 --name mongo_test -v mongovol:/data/db -e MONGO_DATA_DIR=/data/db nexus.company.com:5000/mongo:latest
```

**Describe the results you received:**

`docker service ps --no-trunc mongo_test_mongo` returns:

```
gp6ll2k7fmnu5zf41zz2f5cug   mongo_test_mongo.1       nexus.company.com:5000/mongo:latest   DockerNode1     Ready               Rejected 4 seconds ago   "invalid mount target, must be an absolute path: /data/db"
```

**Describe the results you expected:**

Expected service to start without error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        cde21d3829
 Built:             10/08/2019 17:59:26
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       cde21d3829
  Built:            10/08/2019 17:57:54
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 5
 Server Version: 19.03.3
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: 0chjrd13nbk3cf8ma4c2tyt3b
  Is Manager: true
  ClusterID: dpeyr5f0j8obmngh36cbs0far
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.1.2.62
  Manager Addresses:
   10.1.2.62:2377
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.805)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.999GiB
 Name: NXP-DockerMgr
 ID: RUTM:F6L6:KWFT:DVY7:V5ND:HTGG:UAZX:ZHIT:T434:BDPA:VCNQ:4KXE
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 4774
  System Time: 2019-11-26T10:24:03.0192289Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  nexus.company.com:5000
  nxp-dockermgr:5000
  127.0.0.0/8
 Registry Mirrors:
  http://nexus.company.com:5000/
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2019-11-26 11:15
Some things I notice;

1. You're deploying on a Windows machine; is that Mongo image a Windows image, or are you trying to deploy it using LCOW (Linux Containers On Windows)?
2. Looks like the `environment` section in your compose file may be using the wrong format; 
https://docs.docker.com/compose/compose-file/#environment


Environment variables can be either set as a "dictionary" (`key:value` pairs);

```yaml
environment:
  MONGO_DATA_DIR:/data/db
```

Or as an array (list of `key=value`)

```yaml
environment:
  - MONGO_DATA_DIR=/data/db
```

(currently it sets an environment variable named `MONGO_DATA_DIR:/data/db`, with an empty string as value)

If you're using LCOW to deploy this stack; note that LCOW is an experimental feature, and that feature is (still) incomplete, with known issues

Trying to reproduce Changing the compose-file from your example (I changed the image to use `nginx:alpine` just to have a basic image to run), but was not able to reproduce the problem on a Linux machine, running Docker 19.03.5;

```yaml
version: '3.7'

volumes:
  mongodata:

services:
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR:/data/db
    volumes:
      - mongodata:/data/db
```

```bash
docker stack deploy -c docker-compose.yml mongo_test

docker stack ps mongo_test

ID                  NAME                 IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
j5ilf0uue49v        mongo_test_mongo.1   mongo:latest        swarm-test01        Running             Running 49 seconds ago
```

**Comment by thaJeztah** [comment] 2019-11-26 11:21
I'm also not sure how this worked for you;

```bash
docker volume create --driver overlay mongovol
```

There is no `overlay` driver for volumes (and I don't see a volume-driver plugin named "overlay" installed on your machine) (did that command even run successfully?)

```bash
docker volume create --driver overlay mongovol
Error response from daemon: create mongovol: error looking up volume plugin overlay: plugin "overlay" not found
```

**Comment by psyvision** [comment] 2019-11-26 11:33
Apologies @thaJeztah the volume command was from memory at the time of writing the issue.  The actual command was just:

`docker volume create mongovol`

This is running LCOW and I am using the mongo linux image as opposed to their windows server core images.

I've updated to this compose file (environment changes) and still have the same issue:

```
version: '3.7'

volumes:
  mongodata:

services:
  mongo:
    image: nexus.dsllan.net:5000/mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodata:/data/db
```

Given it works for you on Linux I presume this is a Windows/LCOW issue.  Unfortunately we are not allowed Unix servers in our corporate environment.

**Comment by thaJeztah** [comment] 2019-11-26 11:47
I don't have access to a Windows machine (perhaps @StefanScherer is able to try and reproduce? 🤗 ), but yes, it's possible there's a bug in the translation of paths from windows to linux in LCOW mode.

I should warn that the future of the LCOW feature is still to be determined (also see https://github.com/moby/moby/issues/39533 and the discussion on https://github.com/moby/moby/issues/33850); AFAIK, Microsoft is not currently actively working on the functionality, and with recent developments on WSL2 (which is now being used for Docker Desktop on Windows), future direction may be more towards supporting WSL2 both for Desktop and "server".

**Comment by Ruilkyu** [comment] 2019-11-27 05:05
Thanks!

**Comment by thaJeztah** [comment] 2023-07-12 08:05
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223

**Closed by thaJeztah** 2023-07-12 08:05 UTC
Labels: kind/bug, area/stack, area/lcow, version/19.03
