### ISSUE TITLE
Unable to get published port for each replica of a service

### ISSUE THREAD

**Issue by testphreak** [moby/moby#34979] opened 2017-09-26 05:27 UTC
**Description**

I created a service with 5 replicas and published a random port as a node port. When I inspect each container (replica) for that service, I don't see the published port, shows `null` instead.

**Steps to reproduce the issue:**
1. Setup swarm
2. Create service in swarm with 5 replicas. Publish random port to target port 5900.
For example:
```
docker service create --name myService --publish 0:5900 --replicas 5
```
3. Once the service is up and inspecting the service shows all 5 replicas, inspect the replica/container.

**Describe the results you received:**

I see this under the network settings for each replica/container: 
```
"Ports": {
            "5900/tcp": null
        },
```

**Describe the results you expected:**

I expect each of my 5 replicas to have a unique host port mapped to the specific target port (5900).
```
"Ports": {
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5901"
                    }
                ]
            },
```

**Output of `docker version`:**

```
{
    "Version": "17.05.0-ce",
    "ApiVersion": "1.29",
    "MinAPIVersion": "1.12",
    "GitCommit": "89658be",
    "GoVersion": "go1.7.5",
    "Os": "linux",
    "Arch": "amd64",
    "KernelVersion": "4.4.0-77-generic",
    "BuildTime": "2017-05-04T22:10:54.638119411+00:00"
}
```

**Output of `docker info`:**

```
{
    "ID": "A6AW:GURB:IWNN:MJ36:VNI2:MYMS:WRQI:YV52:VTYU:GEIE:66SI:QWRM",
    "Containers": 2,
    "ContainersRunning": 2,
    "ContainersPaused": 0,
    "ContainersStopped": 0,
    "Images": 3,
    "Driver": "aufs",
    "DriverStatus": [
        [
            "Root Dir",
            "/var/lib/docker/aufs"
        ],
        [
            "Backing Filesystem",
            "extfs"
        ],
        [
            "Dirs",
            "28"
        ],
        [
            "Dirperm1 Supported",
            "true"
        ]
    ],
    "SystemStatus": null,
    "Plugins": {
        "Volume": [
            "local"
        ],
        "Network": [
            "bridge",
            "host",
            "macvlan",
            "null",
            "overlay"
        ],
        "Authorization": []
    },
    "MemoryLimit": true,
    "SwapLimit": true,
    "KernelMemory": true,
    "CpuCfsPeriod": true,
    "CpuCfsQuota": true,
    "CPUShares": true,
    "CPUSet": true,
    "IPv4Forwarding": true,
    "BridgeNfIptables": true,
    "BridgeNfIp6tables": true,
    "Debug": false,
    "NFd": 54,
    "OomKillDisable": true,
    "NGoroutines": 151,
    "SystemTime": "2017-09-25T22:21:44.34800383-07:00",
    "LoggingDriver": "json-file",
    "CgroupDriver": "cgroupfs",
    "NEventsListener": 2,
    "KernelVersion": "4.4.0-77-generic",
    "OperatingSystem": "Ubuntu 16.04.2 LTS",
    "OSType": "linux",
    "Architecture": "x86_64",
    "IndexServerAddress": "https://index.docker.io/v1/",
    "RegistryConfig": {
        "InsecureRegistryCIDRs": [
            "127.0.0.0/8"
        ],
        "IndexConfigs": {
            "docker.io": {
                "Name": "docker.io",
                "Mirrors": [],
                "Secure": true,
                "Official": true
            }
        },
        "Mirrors": []
    },
    "NCPU": 16,
    "MemTotal": 31606628352,
    "DockerRootDir": "/var/lib/docker",
    "HttpProxy": "",
    "HttpsProxy": "",
    "NoProxy": "",
    "Name": "ip-10-39-197-177",
    "Labels": null,
    "ExperimentalBuild": false,
    "ServerVersion": "17.05.0-ce",
    "ClusterStore": "",
    "ClusterAdvertise": "",
    "Runtimes": {
        "runc": {
            "path": "docker-runc"
        }
    },
    "DefaultRuntime": "runc",
    "Swarm": {
        "NodeID": "a9oa1v4i5k51vr67tyz2j6my6",
        "NodeAddr": "10.39.197.177",
        "LocalNodeState": "active",
        "ControlAvailable": true,
        "Error": "",
        "RemoteManagers": [
            {
                "NodeID": "a9oa1v4i5k51vr67tyz2j6my6",
                "Addr": "10.39.197.177:2377"
            }
        ],
        "Nodes": 1,
        "Managers": 1,
        "Cluster": {
            "ID": "wj5i3ufoi391r9hmn19pjr0gr",
            "Version": {
                "Index": 92
            },
            "CreatedAt": "2017-09-22T23:29:13.906955118Z",
            "UpdatedAt": "2017-09-25T23:29:20.154436554Z",
            "Spec": {
                "Name": "default",
                "Labels": {},
                "Orchestration": {
                    "TaskHistoryRetentionLimit": 5
                },
                "Raft": {
                    "SnapshotInterval": 10000,
                    "KeepOldSnapshots": 0,
                    "LogEntriesForSlowFollowers": 500,
                    "ElectionTick": 3,
                    "HeartbeatTick": 1
                },
                "Dispatcher": {
                    "HeartbeatPeriod": 5000000000
                },
                "CAConfig": {
                    "NodeCertExpiry": 7776000000000000
                },
                "TaskDefaults": {},
                "EncryptionConfig": {
                    "AutoLockManagers": false
                }
            }
        }
    },
    "LiveRestoreEnabled": false,
    "Isolation": "",
    "InitBinary": "docker-init",
    "ContainerdCommit": {
        "ID": "9048e5e50717ea4497b757314bad98ea3763c145",
        "Expected": "9048e5e50717ea4497b757314bad98ea3763c145"
    },
    "RuncCommit": {
        "ID": "9c2d8d184e5da67c95d601382adf14862e4f2228",
        "Expected": "9c2d8d184e5da67c95d601382adf14862e4f2228"
    },
    "InitCommit": {
        "ID": "949e6fa",
        "Expected": "949e6fa"
    },
    "SecurityOptions": [
        "name=apparmor",
        "name=seccomp,profile=default"
    ]
}
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS c3.4xlarge host

**Comment by thaJeztah** [comment] 2017-09-26 12:16
This is expected; when creating services, the _service_ port is published, and requests for that port are load-ballance to the tasks (containers) backing the service, ports for individual containers are not published.

If you run `docker service ls`, you'll see that the service's port is published as specified.

I'm closing this issue, because this is the expected behaviour, but feel free to continue the conversation

**Closed by thaJeztah** 2017-09-26 12:16 UTC
Labels: area/swarm

**Comment by testphreak** [comment] 2017-09-26 16:49
@thaJeztah Publishing the ports for individual containers of a service would be very helpful. One of the use cases is when you want to vnc into a container to see what is going on. A concrete example being say you are running tests against a browser inside a container and want to see exactly what happened when the test failed. 

At the moment when I do vnc to the container using the the `service` port, I am not sure which container it landed up in. So if I have 5 replicas, and vnc using the port, the browser may not be running on that container.

Could this be considered for a feature request? I think this would have a lot of value especially in testing/debugging scenarios.
