### ISSUE TITLE
docker: Error response from daemon: pull access denied for ndtar, repository does not exist or may require 'docker login'.

### ISSUE THREAD

**Issue by Sravanchitiprolu** [moby/moby#36915] opened 2018-04-20 12:26 UTC
I am facing this error  when I tries to run this command : docker run --rm -v $(pwd):/tmp ndtar

: docker: Error response from daemon: pull access denied for ndtar, repository does not exist or may require 'docker login'.

**Comment by rajudev** [comment] 2018-04-20 13:58
What does `pwd` returns to you?
My guess here is that you are not pulling the correct repository to run.

**Comment by yusuf-gunaydin** [comment] 2018-04-20 16:55
Are you sure you have an image on your local machine named `ndtar`? There is none on Docker Hub.

**Comment by Sravanchitiprolu** [comment] 2018-04-21 04:51
I had this thing in my local
REPOSITORY              TAG                
websphere-traditional   nd-prereq    

I have to copy this repository into Docker

**Comment by thaJeztah** [comment] 2018-04-21 14:43
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-04-21 14:43 UTC
Labels: area/distribution, kind/question
