### ISSUE TITLE
Make docker containers talk via localhost using forwarding ?

### ISSUE THREAD

**Issue by rnth** [moby/moby#37286] opened 2018-06-15 07:35 UTC
**Description**

I have two projects (seperate repos) and they are currently deployed in a single physical server (no dockerization yet). The problem is that they communicate using localhost.
After dockerization of the two individual projects how do i make interconnection work without changing codebase.

**Steps to reproduce the issue:**
NA

**Describe the results you received:**
ContainerA : curl containerB:port/service/app -> works A ok.
ContainerB : running

**Describe the results you expected:**
ContainerA : curl localhost:port/service/app -> to work A ok.
ContainerB : running

Could someone help me out with this networking and any implementation using iptables to forward calls from localhost:portX sitting in containerA -> containerB:portX

**Comment by zq-david-wang** [comment] 2018-06-15 19:12
I think  `docker run --network=container:[name/id]` can solve your problem.
To be specific, 
1. docker run --name=somename somesimpleimagewhichonlypausethere (some simple container with its own network interface does nothing but pause.) 
2. docker run --network=container:somename yourimageA
3. docker run --network=container:somename yourimageB

**Comment by rnth** [comment] 2018-06-19 04:17
Thanks. Will try it out.

**Comment by thaJeztah** [comment] 2018-06-19 05:27
Yes, looks like `--network=container:....` is what you're looking for; this makes both consumers share the same network-namespace, so `localhost` in each container is then shared.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-06-19 05:27 UTC
Labels: kind/question

**Comment by rnth** [comment] 2018-06-20 06:30
Well. Thanks so much. So this works great with indivudual docker run commands.
I am taking the liberty to put one more query here. Dont mind please. 

Just one more question. Is there any way to feed this nice configuration i.e (--network=container:name) in adocker-compose.yml
I tried it with both 
`...
network:
  - container:name
...`

`...
networks:
  - container:name
...`

Both occasion says 
> uses an undefined network "container:name"

**Comment by rnth** [comment] 2018-06-20 06:51
network-mode
