### ISSUE TITLE
Kali Linux GUI setup problem

### ISSUE THREAD

**Issue by mariokef** [moby/moby#41661] opened 2020-11-10 22:16 UTC
Today I have attempted at downloading kali Linux GUI. But at the final stage where I need to open it it always shows
Unable to contact settings server
Failed to execute child process “dbus-launch” (no such file or directory)

What do I do?
I was following NetworkChucks tutorial and I double checked I had done every step.

**Comment by thaJeztah** [comment] 2020-11-10 22:50
I don't think this issue tracker is the right location for that question (not even sure if your question is related to moby / docker: note that Kali Linux is not a distro we ship binaries for, or test on).

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

If you _do_ think there's a bug in Moby / Docker, create a ticket with the exact steps to reproduce the issue, as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Closing this ticket because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2020-11-10 22:50 UTC
Labels: kind/question

**Comment by Cyber-project** [comment] 2022-03-28 06:09
![IMG_20220328_103357.jpg](https://user-images.githubusercontent.com/60157722/160336292-ff82d496-c5f8-4789-a147-af0692d14b25.jpg)

Please help 
Its showing permission denied 
Installing kali Linux in window 11

Wp me - 8287715570 
Please

**Comment by thaJeztah** [comment] 2022-03-28 06:22
Again, not related to Docker ... in any way; if you have problems installing a Linux distro on WSL2, https://github.com/microsoft/WSL/issues may be a better place to ask.
