### ISSUE TITLE
Error starting daemon: error initializing graphdriver: devmapper: Device %device% is not a thin pool

### ISSUE THREAD

**Issue by jeekajoo** [moby/moby#21304] opened 2016-03-17 18:05 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:1-395536-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/mapper/docker-pool0
 Metadata file: /dev/mapper/docker-pool0
 Data Space Used: 186.7 MB
 Data Space Total: 48.31 GB
 Data Space Available: 48.13 GB
 Metadata Space Used: 1.683 MB
 Metadata Space Total: 17.05 GB
 Metadata Space Available: 17.04 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.87 GiB
Name: ip-172-16-11-30
ID: SGIG:VTD2:5Z25:WIHP:3DQS:TS25:HK53:BFM5:FILA:PRZF:ZKLH:TKT7
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2

**Steps to reproduce the issue:**
1) Setup a lvm thin pool

``` bash
PV=/dev/xvdf
VG=docker
LV=pool0

pvcreate $PV
vgcreate $VG $PV
lvcreate -y -l 5%VG -n $LV\meta $VG
lvcreate -y -l 90%VG -n $LV $VG
lvconvert -y --zero n --thinpool $VG/$LV --poolmetadata $VG/$LV\meta

lvs -a
  LV              VG     Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  [lvol0_pmspare] docker ewi-------  2.50g                                                    
  pool0           docker twi-a-t--- 45.00g             0.00   0.01                            
  [pool0_tdata]   docker Twi-ao---- 45.00g                                                    
  [pool0_tmeta]   docker ewi-ao----  2.50g       

dmsetup status
docker-pool0-tpool: 0 94363648 thin-pool 0 94/654336 0/737216 - rw no_discard_passdown queue_if_no_space 
docker-pool0_tdata: 0 94363648 linear 
docker-pool0_tmeta: 0 5234688 linear 
docker-pool0: 0 94363648 linear 
```

2) Try to run docker daemon with a devicemapper driver

**Describe the results you received:**

``` bash
systemctl stop docker ; rm -rf /var/lib/docker ; /usr/bin/docker daemon --debug --storage-driver 'devicemapper' --storage-opt 'dm.thinpooldev=/dev/mapper/docker-pool0' --storage-opt 'dm.fs=xfs' --storage-opt 'dm.use_deferred_removal=true'
DEBU[0000] docker group found. gid: 999                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Using default logging driver json-file       
DEBU[0000] [graphdriver] trying provided driver "devicemapper" 
DEBU[0000] devicemapper: driver version is 4.27.0       
DEBU[0000] devmapper: Deferred removal support enabled. 
DEBU[0000] devmapper: Generated prefix: docker-202:1-395273 
DEBU[0000] devmapper: Checking for existence of the pool docker-pool0 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: error initializing graphdriver: devmapper: Device docker-pool0 is not a thin pool 
```

**Describe the results you expected:**

No fatal error.

**Additional information you deem important (e.g. issue happens only occasionally):**

Problem does not occur if you use deprecated options: `dm.datadev` and `dm.metadatadev`

``` bash
systemctl stop docker ; rm -rf /var/lib/docker ; /usr/bin/docker daemon --debug --storage-driver 'devicemapper' --storage-opt 'dm.datadev=/dev/mapper/docker-pool0' --storage-opt 'dm.metadatadev=/dev/mapper/docker-pool0' --storage-opt 'dm.fs=xfs' --storage-opt 'dm.use_deferred_removal=true'
```

**Comment by Cletus-Doy-Shinda** [comment] 2016-05-10 04:37
Try changing:
`--storage-opt dm.thinpooldev=/dev/mapper/docker-pool0`
to:
`--storage-opt dm.thinpooldev=/dev/mapper/docker-pool0-tpool`

**Comment by svvac** [comment] 2016-05-13 12:10
Using the `-tpool` device works for me (debian jessie). Maybe this should be updated in the docs

**Comment by thaJeztah** [comment] 2016-05-13 13:45
@svvac some changes were made to the documentation recently, but perhaps you could check if there's incorrect information in there? https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/

The Markdown file used to generate that page can be found in this repository; https://github.com/docker/docker/blob/master/docs/userguide/storagedriver/device-mapper-driver.md

**Comment by lgibelli** [comment] 2016-06-28 15:32
+1 I had the same problem, using the -tpool device works for me (debian jessie).  Official docs are not updated yet.

**Comment by thaJeztah** [comment] 2016-06-28 19:41
@lgibelli would you be interested in opening a pull request to fix that part of the documentation if it's incorrect? Also note that for Jessie, you should be able to use aufs if you install the linux-image-extra packages

**Comment by lgibelli** [comment] 2016-07-03 07:33
@thaJeztah I'd rather not use aufs, Device Mapper (https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/) is the recommended storage driver for Docker.

I don't think this should be *fixed* in the documentation, using the -tpool device is just a workaround. It should be fixed in Docker. The documentation could mention this as a workaround.

**Comment by zim32** [comment] 2017-03-04 11:53
Made all steps mentioned in documentation and got the same issue. What should I do to fix this?

**Comment by justincormack** [comment] 2017-03-04 18:02
Device mapper is not the recommended storage driver for Docker, and that
page does not say that, it says it is the default for RHEL and derived
distros, and supported elsewhere. In general it is not recommended.


On 3 Jul 2016 00:33, "Luca Gibelli" <notifications@github.com> wrote:

@thaJeztah <https://github.com/thaJeztah> I'd rather not use aufs, Device
Mapper (https://docs.docker.com/engine/userguide/
storagedriver/device-mapper-driver/) is the recommended storage driver for
Docker.

I don't think this should be *fixed* in the documentation, using the -tpool
device is just a workaround. It should be fixed in Docker. The
documentation could mention this as a workaround.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/21304#issuecomment-230140029>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAdcPP6ULszQZS38-oWObnV2Ejfe-M4zks5qR2XAgaJpZM4HzNGO>
.

**Comment by zim32** [comment] 2017-03-04 18:37
After restart LVM want activate again. So I updated to new kernel and overlay2. Spend whole day to realize devicemapper is bad (

**Comment by kolyshkin** [comment] 2017-08-14 10:32
> After restart LVM dont want to activate again.

this might be caused by the missing thin_check binary. I have just came across the issue, and submitted a fix (https://github.com/moby/moby/pull/34486/commits/58a453f3f06c1daf34544da8aa16bb95e8e18010)

**Comment by HaiNguyen007** [comment] 2017-09-16 00:28
https://github.com/docker/docker.github.io/pull/386 (rollback to error?)

**Comment by meeca1218** [comment] 2017-11-13 19:11
Had no problem with docker 1.12 engine.  But could not install docker-CE working.  
dockerd: Error starting daemon: error initializing graphdriver: devmapper: Device docker-thinpool is not a thin pool
All thin pools (on other machines) work under older versions.
Besides, there is no docker-storage-setup anymore. 
Anyone has used download CE and installed it successfully ?  Thx.

**Comment by weskerfoot** [comment] 2019-09-14 16:15
I'm getting this error in `Docker version 19.03.2-ce, build 6a30dfca03` on Arch Linux

**Comment by bidetaggle** [comment] 2020-07-19 22:58
Same issue here with `Docker version 19.03.12-ce, build 48a66213fe` on Arch Linux.

I tried this command:

`systemctl stop docker ; rm -rf /var/lib/docker ; /usr/bin/docker daemon --debug --storage-driver 'devicemapper' --storage-opt 'dm.datadev=/dev/mapper/docker-pool0' --storage-opt 'dm.metadatadev=/dev/mapper/docker-pool0' --storage-opt 'dm.fs=xfs' --storage-opt 'dm.use_deferred_removal=true'`

But I get `unknown flag: --storage-driver` then the docker help show up.

**Comment by thaJeztah** [comment] 2020-07-20 10:45
The `daemon` subcommand no longer exists (the daemon is now a separate binary, named `dockerd`.

However, unless you have very specific reasons, I would not recommend using the device mapper storage driver (the driver is marked deprecated, but won't be removed (yet)). Generally, I'd recommend the default (`overlay2`) storage driver, which requires no configuration, and is more performant for most situations.

**Comment by thaJeztah** [comment] 2020-07-20 10:47
With the device mapper storage-driver being deprecated, I'm closing this issue

**Closed by thaJeztah** 2020-07-20 10:47 UTC
Labels: area/storage/devicemapper, version/1.10
