### ISSUE TITLE
Secondary DNS servers are ignored, 8.8.8.8 is not being added

### ISSUE THREAD

**Issue by Haarolean** [moby/moby#41041] opened 2020-05-28 12:16 UTC
**Description**

The secondary DNS server passed via `--dns` option is being ignored, `8.8.8.8` is not being added as a backup server, contradictory to official [documentation](https://docs.docker.com/config/containers/container-networking/).

**Steps to reproduce the issue:**
Could reproduce on clean debian. 
Ubuntu is affected just partially, if you specify both invalid DNS servers, it won't use `8.8.8.8`.
Bridge is important, it works fine without it.
In this example `1.255` is not a valid DNS server, meanwhile `1.1` is.
```
$ docker network create -d bridge test

$ docker run --rm --dns 192.168.1.255 --dns 192.168.1.1 --network test --name test -it debian sh
# ping google.com
ping: google.com: Temporary failure in name resolution

$ docker run --rm --dns 192.168.1.1 --dns 192.168.1.255 --network test --name test -it debian sh
# ping google.com
PING google.com (108.177.14.113) 56(84) bytes of data.
64 bytes from lt-in-f113.1e100.net (108.177.14.113): icmp_seq=1 ttl=46 time=17.4 ms
```
**Describe the results you received:**
Secondary server is ignored, 8.8.8.8 is not being added.

**Describe the results you expected:**
Secondary server is not ignored, additional 8.8.8.8 added.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:25 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.64GiB
 Name: debian-test
 ID: VVRQ:CXMQ:N7CI:7LQI:M5AT:NYEC:HAUO:BTNK:3KWO:33TS:SS2U:MKMF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Linux debian-test 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
Couldn't get any significantly useful information from daemon debug logs, nothing related.

**Comment by thaJeztah** [comment] 2020-05-28 15:09
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/41003, and is a regression in the v19.03.9 update, and will be fixed in v19.03.10. The fix is already in master (through https://github.com/moby/moby/pull/41008), and a backport for 19.03 is pending merge (https://github.com/moby/moby/pull/41009), after which the v19.03.10 release process is started.

I'll close this one because it's merged on master, but feel free to continue the conversation.

**Closed by thaJeztah** 2020-05-28 15:09 UTC
Labels: area/networking, kind/bug, version/19.03

**Comment by Haarolean** [comment] 2020-05-28 15:13
@thaJeztah thank you very much! I couldn't find this exact issue, just some near-related problems on forums, so decided to report it. I wonder if my DNS related issues (e.g. #41000) are related. Probably this weird thing started just after the update.

**Comment by thaJeztah** [comment] 2020-05-28 15:42
> I wonder if my DNS related issues (e.g. #41000) are related. Probably this weird thing started just after the update.

Hmm... in that issue you reported that it was also on 19.03.8 and older, so would not have a direct relation with this fix.

**Comment by Haarolean** [comment] 2020-05-29 16:01
@thaJeztah seems like it is. At least I could fix all the issues specifying DNS servers in compose files. My network was crazy before that.

Also, the part about 8.8.8.8 is still a problem. I got the docker updated to 19.03.10 (9424aeaee9).

```
$ docker run --rm --dns 192.168.1.255 --dns 192.168.1.254 --network test --name testt -it debian sh
# ping google.com
ping: google.com: Temporary failure in name resolution
```

**Comment by thaJeztah** [comment] 2020-06-04 17:55
192.168.1.254 is a valid DNS in your setup? Trying to reproduce;

```bash
curl -fsSL https://get.docker.com | sh
mkdir -p /etc/docker/
echo '{"debug":true}' > /etc/docker/daemon.json
systemctl reload docker
docker network create test
docker pull alpine

docker run --rm --dns 192.168.1.255 --dns 8.8.8.8 --network=test alpine ping -c1 google.com
PING google.com (74.125.143.139): 56 data bytes
64 bytes from 74.125.143.139: seq=0 ttl=44 time=4.597 ms

--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 4.597/4.597/4.597 ms
```

And related logs;

```
Jun  4 17:45:09 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:09.297340868Z" level=debug msg="Name To resolve: google.com."
Jun  4 17:45:09 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:09.297476318Z" level=debug msg="[resolver] query google.com. (AAAA) from 172.18.0.2:39409, forwarding to udp:192.168.1.255"
Jun  4 17:45:09 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:09.297955878Z" level=debug msg="Name To resolve: google.com."
Jun  4 17:45:09 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:09.298039218Z" level=debug msg="[resolver] query google.com. (A) from 172.18.0.2:54430, forwarding to udp:192.168.1.255"
Jun  4 17:45:09 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:09.299139097Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/start
Jun  4 17:45:11 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:11.799891865Z" level=debug msg="Name To resolve: google.com."
Jun  4 17:45:11 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:11.800027652Z" level=debug msg="[resolver] query google.com. (AAAA) from 172.18.0.2:38290, forwarding to udp:192.168.1.255"
Jun  4 17:45:11 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:11.800103751Z" level=debug msg="Name To resolve: google.com."
Jun  4 17:45:11 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:11.800153721Z" level=debug msg="[resolver] query google.com. (A) from 172.18.0.2:43329, forwarding to udp:192.168.1.255"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.297639399Z" level=debug msg="[resolver] read from DNS server failed, read udp 172.18.0.2:39409->192.168.1.255:53: i/o timeout"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.297871103Z" level=debug msg="[resolver] query google.com. (AAAA) from 172.18.0.2:39079, forwarding to udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.298742273Z" level=debug msg="[resolver] read from DNS server failed, read udp 172.18.0.2:54430->192.168.1.255:53: i/o timeout"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.298857304Z" level=debug msg="[resolver] query google.com. (A) from 172.18.0.2:58318, forwarding to udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.299717122Z" level=debug msg="[resolver] received A record \"108.177.126.102\" for \"google.com.\" from udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.299750987Z" level=debug msg="[resolver] received A record \"108.177.126.113\" for \"google.com.\" from udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.299766648Z" level=debug msg="[resolver] received A record \"108.177.126.100\" for \"google.com.\" from udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.299780023Z" level=debug msg="[resolver] received A record \"108.177.126.138\" for \"google.com.\" from udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.299794204Z" level=debug msg="[resolver] received A record \"108.177.126.139\" for \"google.com.\" from udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.299814605Z" level=debug msg="[resolver] received A record \"108.177.126.101\" for \"google.com.\" from udp:8.8.8.8"
Jun  4 17:45:13 ubuntu-s-1vcpu-2gb-ams3-01 dockerd[7384]: time="2020-06-04T17:45:13.303008027Z" level=debug msg="[resolver] received AAAA record \"2a00:1450:4013:c01::8a\" for \"google.com.\" from udp:8.8.8.8"
```

**Comment by Haarolean** [comment] 2020-06-04 18:01
Nah, both are invalid. There's a [point](https://docs.docker.com/config/containers/container-networking/):
```
If the container cannot reach any of the IP addresses you specify, Google’s public DNS server 8.8.8.8 is added, so that your container can resolve internet domains.
```
so it should work with both invalid, right?
