### ISSUE TITLE
systemctl start docker is failing

### ISSUE THREAD

**Issue by ackris** [moby/moby#34091] opened 2017-07-13 08:28 UTC
OS: CentOS 7
UName -a: Linux centos1 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I have installed the latest Docker CE version. 

Problem:
When I tried to execute `sudo systemctl start docker`, I am getting the following error:

```
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2017-07-13 13:45:01 IST; 8s ago
     Docs: https://docs.docker.com
  Process: 7283 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 7283 (code=exited, status=1/FAILURE)

Jul 13 13:45:01 centos1 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 13 13:45:01 centos1 systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 13:45:01 centos1 systemd[1]: Unit docker.service entered failed state.
Jul 13 13:45:01 centos1 systemd[1]: docker.service failed.
Jul 13 13:45:01 centos1 systemd[1]: docker.service holdoff time over, scheduling restart.
Jul 13 13:45:01 centos1 systemd[1]: start request repeated too quickly for docker.service
Jul 13 13:45:01 centos1 systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 13:45:01 centos1 systemd[1]: Unit docker.service entered failed state.
Jul 13 13:45:01 centos1 systemd[1]: docker.service failed.

```

As requested by @AkihiroSuda 
The logs of `journalctl -u docker`
```

-- Logs begin at Thu 2017-07-13 13:27:44 IST, end at Thu 2017-07-13 14:05:06 IST. --
Jul 13 12:29:54 centos1 systemd[1]: Starting Docker Application Container Engine...
Jul 13 12:29:55 centos1 dockerd[3952]: time="2017-07-13T12:29:55.172776004+05:30" level=info msg="libcontainerd: new containerd process, pid: 3978"
Jul 13 12:29:55 centos1 dockerd[3952]: time="2017-07-13T12:29:55.256116779+05:30" level=warning msg="overlay: the backing xfs filesystem is formatted 
Jul 13 12:29:55 centos1 dockerd[3952]: time="2017-07-13T12:29:55.256159270+05:30" level=info msg="[graphdriver] using prior storage driver: overlay"
Jul 13 12:29:55 centos1 dockerd[3952]: time="2017-07-13T12:29:55.269359710+05:30" level=info msg="Graph migration to content-addressability took 0.00 
Jul 13 12:29:55 centos1 dockerd[3952]: time="2017-07-13T12:29:55.270046544+05:30" level=warning msg="mountpoint for pids not found"
Jul 13 12:29:55 centos1 dockerd[3952]: time="2017-07-13T12:29:55.270236647+05:30" level=info msg="Loading containers: start."
Jul 13 12:29:56 centos1 dockerd[3952]: time="2017-07-13T12:29:56.159221104+05:30" level=info msg="Default bridge (docker0) is assigned with an IP addr
Jul 13 12:29:56 centos1 dockerd[3952]: time="2017-07-13T12:29:56.352378612+05:30" level=info msg="Loading containers: done."
Jul 13 12:29:56 centos1 dockerd[3952]: time="2017-07-13T12:29:56.375549923+05:30" level=info msg="Daemon has completed initialization"
Jul 13 12:29:56 centos1 dockerd[3952]: time="2017-07-13T12:29:56.375583263+05:30" level=info msg="Docker daemon" commit=02c1d87 graphdriver=overlay ve
Jul 13 12:29:56 centos1 dockerd[3952]: time="2017-07-13T12:29:56.398399872+05:30" level=info msg="API listen on /var/run/docker.sock"
Jul 13 12:29:56 centos1 systemd[1]: Started Docker Application Container Engine.
Jul 13 13:39:32 centos1 systemd[1]: Stopping Docker Application Container Engine...
Jul 13 13:39:32 centos1 dockerd[3952]: time="2017-07-13T13:39:32.146053054+05:30" level=info msg="Processing signal 'terminated'"
Jul 13 13:39:32 centos1 dockerd[3952]: time="2017-07-13T13:39:32.171737214+05:30" level=info msg="stopping containerd after receiving terminated"
Jul 13 13:39:33 centos1 systemd[1]: Stopped Docker Application Container Engine.
Jul 13 13:42:49 centos1 systemd[1]: Starting Docker Application Container Engine...
Jul 13 13:42:49 centos1 dockerd[6703]: time="2017-07-13T13:42:49.884531291+05:30" level=info msg="libcontainerd: new containerd process, pid: 6709"
Jul 13 13:42:50 centos1 dockerd[6703]: time="2017-07-13T13:42:50.971088640+05:30" level=error msg="File descriptor 9 (/dev/mapper/control) leaked on p
Jul 13 13:42:50 centos1 dockerd[6703]: Error starting daemon: error initializing graphdriver: /dev/sda1 has a filesystem already, use dm.directlvm_dev
Jul 13 13:42:50 centos1 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 13 13:42:51 centos1 systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 13:42:51 centos1 systemd[1]: Unit docker.service entered failed state.
Jul 13 13:42:51 centos1 systemd[1]: docker.service failed.
Jul 13 13:42:51 centos1 systemd[1]: docker.service holdoff time over, scheduling restart.
Jul 13 13:42:51 centos1 systemd[1]: Starting Docker Application Container Engine...
```

I followed [https://github.com/moby/moby/issues/12087](url), and tried to replicate the docker-selinux trick. The attempt has failed.

Where am i making a mistake? I have browsed extensively for a solution to this problem but to no avail. 

Regards
Aditya

**Comment by AkihiroSuda** [comment] 2017-07-13 08:35
`journalctl -u docker` shows more logs

**Comment by ackris** [comment] 2017-07-13 08:43
@AkihiroSuda , i have updated the query with journalctl logs

**Comment by cpuguy83** [comment] 2017-07-13 14:37
@ackris The logs are still cut off, but:

>  Error starting daemon: error initializing graphdriver: /dev/sda1 has a filesystem already, use dm.directlvm_dev

You should definitely read the full log line there.
Closing as this is not a Docker issue, but rather that the device specified in `dm.directlvm_device` already has a filesystem and can't be used without setting the force option.

**Closed by cpuguy83** 2017-07-13 14:37 UTC
Labels: kind/question

**Comment by Jayhello** [comment] 2018-01-26 01:51
As to me, I have get this error. 

`Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.`

Finally I found, it the `/etc/docker/daemon.json` error, for I add `registry-mirrors`

`
{
    "runtimes": {

        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }    
   
    # I forget to add a comma , here
    "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn"]
}
`

After i add it , then `systemctl restart docker`, I solved it.

**Comment by MrMetric** [comment] 2018-01-30 03:37
I had this problem on Arch when the installed Linux version did not match the running Linux version (a frequent source of issues)

**Comment by StephenLU0422** [comment] 2018-04-14 06:11
you can use the command 
```
journalctl  -u docker
```
check the log.
And fix it

**Comment by rogaha** [comment] 2018-04-17 03:28
```
root@sevenmob:/home/pi# journalctl  -u docker
Apr 17 03:17:07 sevenmob systemd[1]: docker.service: main process exited, code=dumped, status=4/ILL
Apr 17 03:17:07 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:17:07 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:17:08 sevenmob systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 17 03:17:08 sevenmob systemd[1]: Stopping Docker Application Container Engine...
Apr 17 03:17:08 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:17:10 sevenmob systemd[1]: docker.service: main process exited, code=dumped, status=4/ILL
Apr 17 03:17:10 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:17:10 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:17:10 sevenmob systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 17 03:17:10 sevenmob systemd[1]: Stopping Docker Application Container Engine...
Apr 17 03:17:10 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:17:13 sevenmob systemd[1]: docker.service: main process exited, code=dumped, status=4/ILL
Apr 17 03:17:13 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:17:13 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:17:13 sevenmob systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 17 03:17:13 sevenmob systemd[1]: Stopping Docker Application Container Engine...
Apr 17 03:17:13 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:17:13 sevenmob systemd[1]: docker.service start request repeated too quickly, refusing to start.
Apr 17 03:17:13 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:17:13 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:22:11 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:22:11 sevenmob systemd[1]: docker.service: main process exited, code=dumped, status=4/ILL
Apr 17 03:22:11 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:22:11 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:22:12 sevenmob systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 17 03:22:12 sevenmob systemd[1]: Stopping Docker Application Container Engine...
Apr 17 03:22:12 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:22:14 sevenmob systemd[1]: docker.service: main process exited, code=dumped, status=4/ILL
Apr 17 03:22:14 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:22:14 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:22:14 sevenmob systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 17 03:22:14 sevenmob systemd[1]: Stopping Docker Application Container Engine...
Apr 17 03:22:14 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:22:17 sevenmob systemd[1]: docker.service: main process exited, code=dumped, status=4/ILL
Apr 17 03:22:17 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:22:17 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:22:17 sevenmob systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 17 03:22:17 sevenmob systemd[1]: Stopping Docker Application Container Engine...
Apr 17 03:22:17 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:22:17 sevenmob systemd[1]: docker.service start request repeated too quickly, refusing to start.
Apr 17 03:22:17 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
Apr 17 03:22:17 sevenmob systemd[1]: Unit docker.service entered failed state.
Apr 17 03:22:46 sevenmob systemd[1]: Starting Docker Application Container Engine...
Apr 17 03:22:46 sevenmob systemd[1]: docker.service start request repeated too quickly, refusing to start.
Apr 17 03:22:46 sevenmob systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by rogaha** [comment] 2018-04-17 03:28
@thaJeztah  should we re-open it?

**Comment by rogaha** [comment] 2018-04-17 03:29
```
root@sevenmob:/home/pi# uname -a
Linux sevenmob 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
root@sevenmob:/home/pi# cat /etc/issue
Raspbian GNU/Linux 8 \n \l

root@sevenmob:/home/pi#
```

**Comment by thaJeztah** [comment] 2018-04-17 04:48
@rogaha "service failing to start" is quite generic, and looking at this issue, I already see three different issues being reported here, all of which have a different root cause, but leading to the daemon failing to start.

Could you open a new issue with details?

**Comment by alienflash01** [comment] 2018-07-27 07:01
I have the similar problems, and I use 'journalctl -u docker', I got ：
``` 
Jul 27 14:16:30 lg-ai-fanwei3.bj dockerd[6317]: time="2018-07-27T14:16:30.700210823+08:00" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
Jul 27 14:16:30 lg-ai-fanwei3.bj dockerd[6317]: Error starting daemon: error initializing graphdriver: driver not supported
Jul 27 14:16:30 lg-ai-fanwei3.bj systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 27 14:16:30 lg-ai-fanwei3.bj systemd[1]: Failed to start Docker Application Container Engine.
```
then I delete the line 'overlay' items in /etc/docker/daemon.json and i slove the problem

**Comment by noorkhan-92** [comment] 2019-05-04 07:13
@alienflash01 can you tell how to edit this json file. i am quite new to centOS...?

**Comment by yanghq168** [comment] 2019-05-30 02:57
I change the file  /etc/docker/daemon.json,i write wrong code as {
  "registry-mirrors": {
    "https://yourcode.mirror.aliyuncs.com"
  }
},it should be
{
  "registry-mirrors": [
    "https://yourcode.mirror.aliyuncs.com"
  ]
}
....and fix it ,hongquan yang

**Comment by ltao6688** [comment] 2021-04-12 08:10
[root@localhost ~]# sudo dockerd --debug
INFO[2021-04-12T16:04:16.038109821+08:00] Starting up                                  
DEBU[2021-04-12T16:04:16.039917683+08:00] Listener created for HTTP on unix (/var/run/docker.sock) 
DEBU[2021-04-12T16:04:16.039963575+08:00] Containerd not running, starting daemon managed containerd 
INFO[2021-04-12T16:04:16.055946913+08:00] libcontainerd: started new containerd process  pid=1514
INFO[2021-04-12T16:04:16.056009378+08:00] parsed scheme: "unix"                         module=grpc
INFO[2021-04-12T16:04:16.056018496+08:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-04-12T16:04:16.056040282+08:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2021-04-12T16:04:16.056053274+08:00] ClientConn switching balancer to "pick_first"  module=grpc
ERRO[2021-04-12T16:04:16.068413882+08:00] containerd did not exit successfully          error="signal: segmentation fault" module=libcontainerd
WARN[2021-04-12T16:04:17.056756764+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
WARN[2021-04-12T16:04:19.648577905+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
WARN[2021-04-12T16:04:23.441011627+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
WARN[2021-04-12T16:04:28.440429920+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
failed to start containerd: timeout waiting for containerd to start

**Comment by ltao6688** [comment] 2021-04-12 08:11
`[root@localhost ~]# sudo dockerd --debug
INFO[2021-04-12T16:04:16.038109821+08:00] Starting up                                  
DEBU[2021-04-12T16:04:16.039917683+08:00] Listener created for HTTP on unix (/var/run/docker.sock) 
DEBU[2021-04-12T16:04:16.039963575+08:00] Containerd not running, starting daemon managed containerd 
INFO[2021-04-12T16:04:16.055946913+08:00] libcontainerd: started new containerd process  pid=1514
INFO[2021-04-12T16:04:16.056009378+08:00] parsed scheme: "unix"                         module=grpc
INFO[2021-04-12T16:04:16.056018496+08:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-04-12T16:04:16.056040282+08:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2021-04-12T16:04:16.056053274+08:00] ClientConn switching balancer to "pick_first"  module=grpc
ERRO[2021-04-12T16:04:16.068413882+08:00] containerd did not exit successfully          error="signal: segmentation fault" module=libcontainerd
WARN[2021-04-12T16:04:17.056756764+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
WARN[2021-04-12T16:04:19.648577905+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
WARN[2021-04-12T16:04:23.441011627+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
WARN[2021-04-12T16:04:28.440429920+08:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
failed to start containerd: timeout waiting for containerd to start
`

**Comment by ltao6688** [comment] 2021-04-12 08:12
`[root@localhost ~]# journalctl -xe
-- 
-- The result is failed.
4月 12 16:00:43 localhost.localdomain systemd[1]: Unit containerd.service entered failed state.
4月 12 16:00:43 localhost.localdomain systemd[1]: containerd.service failed.
4月 12 16:00:48 localhost.localdomain systemd[1]: containerd.service holdoff time over, scheduling restart.
4月 12 16:00:48 localhost.localdomain systemd[1]: Stopped containerd container runtime.
-- Subject: Unit containerd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit containerd.service has finished shutting down.
4月 12 16:00:48 localhost.localdomain systemd[1]: Starting containerd container runtime...
-- Subject: Unit containerd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit containerd.service has begun starting up.
4月 12 16:00:48 localhost.localdomain kernel: traps: containerd[1322] trap int3 ip:55f4cc78d712 sp:7ffe8e16c338 error:0 i
4月 12 16:00:48 localhost.localdomain containerd[1322]: fatal: morestack on g0
4月 12 16:00:48 localhost.localdomain systemd[1]: containerd.service: main process exited, code=dumped, status=5/TRAP
4月 12 16:00:48 localhost.localdomain systemd[1]: Failed to start containerd container runtime.
-- Subject: Unit containerd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit containerd.service has failed.
-- 
-- The result is failed.
4月 12 16:00:48 localhost.localdomain systemd[1]: Unit containerd.service entered failed state.
4月 12 16:00:48 localhost.localdomain systemd[1]: containerd.service failed.
lines 2077-2106/2106 (END)
[root@localhost ~]# ^C
[root@localhost ~]# journalctl -xe^C
[root@localhost ~]# sudo systemctl stop docker
Warning: Stopping docker.service,`

**Comment by ltao6688** [comment] 2021-04-12 08:13
`[root@localhost ~]# journalctl -xe
-- 
-- The result is failed.
4月 12 16:00:43 localhost.localdomain systemd[1]: Unit containerd.service entered failed state.
4月 12 16:00:43 localhost.localdomain systemd[1]: containerd.service failed.
4月 12 16:00:48 localhost.localdomain systemd[1]: containerd.service holdoff time over, scheduling restart.
4月 12 16:00:48 localhost.localdomain systemd[1]: Stopped containerd container runtime.
-- Subject: Unit containerd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit containerd.service has finished shutting down.
4月 12 16:00:48 localhost.localdomain systemd[1]: Starting containerd container runtime...
-- Subject: Unit containerd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit containerd.service has begun starting up.
4月 12 16:00:48 localhost.localdomain kernel: traps: containerd[1322] trap int3 ip:55f4cc78d712 sp:7ffe8e16c338 error:0 i
4月 12 16:00:48 localhost.localdomain containerd[1322]: fatal: morestack on g0
4月 12 16:00:48 localhost.localdomain systemd[1]: containerd.service: main process exited, code=dumped, status=5/TRAP
4月 12 16:00:48 localhost.localdomain systemd[1]: Failed to start containerd container runtime.
-- Subject: Unit containerd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit containerd.service has failed.
-- 
-- The result is failed.
4月 12 16:00:48 localhost.localdomain systemd[1]: Unit containerd.service entered failed state.
4月 12 16:00:48 localhost.localdomain systemd[1]: containerd.service failed.`
