### ISSUE TITLE
Randomly cannot start Containers with "Clean up Error! Cannot destroy container" "mkdir ...-init/merged/dev/shm: invalid argument"

### ISSUE THREAD

**Issue by KekSfabrik** [moby/moby#22937] opened 2016-05-24 10:28 UTC
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 20
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-39-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 94.29 GiB
Name: srv-0
ID: IDQ4:CJPJ:HFBJ:FGEP:XDNE:N5I6:VTZQ:O7LB:7EGT:MSAT:RAZK:74FH
Docker Root Dir: /data/docker/mnt
Debug mode (client): false
Debug mode (server): false
Username: keks
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 my.company.environment=prod
 my.company.storage=hdd
 my.company.gateway=true
 my.company.name=srv-0
Cluster store: consul://192.168.10.1:8500
Cluster advertise: 192.168.10.1:2375
```

The running images are consul, gliderlabs/registrator and swarm:1.2.2

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical (hardware -> ubuntu 14.04.4 -> docker)

**Steps to reproduce the issue:**
1. docker run ubuntu:precise

**Describe the results you received:**
I set up the daemon on new machines to use a non-default graph directory (--graph option) among other things (only bound to local network etc):

```
DOCKER_OPTS="\
-H                  unix:///var/run/docker.sock \
-H                  tcp://192.168.10.1:2375 \
--storage-driver    overlay \
--cluster-store     consul://192.168.10.1:8500 \
--cluster-advertise 192.168.10.1:2375 \
--dns               192.168.10.1 \
--dns               127.0.0.1 \
--dns-search        service.consul \
--graph             /data/docker/mnt \
--ip                192.168.10.1 \
--label             my.company.environment=prod \
--label             my.company.storage=hdd \
--label             my.company.gateway=true \
--label             my.company.name=srv-0 \
--log-driver        json-file \
--log-opt           max-size=10m \
--log-opt           max-file=9 \
"
```

Apparently some Images "randomly" work and then don't - in this example I tried (re-)running an ubuntu image (which worked about 30min ago):

```
root@srv-0:/data/docker/bootstrap# docker run --rm -it alpine sh # there, alpine works
/ # ^C
root@srv-0:/data/docker/bootstrap# docker run --rm -it ubuntu # yet ubuntu somehow doesn't
docker: Error response from daemon: mkdir /data/docker/mnt/overlay/646f16d12c8b5060f8a9e65a5fdabcf3604a108dc6a1d8c0497f7f2689e47e4a-init/merged/dev/shm: invalid argument.
See 'docker run --help'.
root@srv-0:/data/docker/bootstrap# tail -n 2 /var/log/upstart/docker.log
time="2016-05-24T11:40:06.625413479+02:00" level=error msg="Clean up Error! Cannot destroy container ffbcc96da1d9611a8d200e094bac3f12319360fa439f5105953160e5be64cb36: No such container: ffbcc96da1d9611a8d200e094bac3f12319360fa439f5105953160e5be64cb36" 
time="2016-05-24T11:40:06.625465100+02:00" level=error msg="Handler for POST /v1.23/containers/create returned error: mkdir /data/docker/mnt/overlay/646f16d12c8b5060f8a9e65a5fdabcf3604a108dc6a1d8c0497f7f2689e47e4a-init/merged/dev/shm: invalid argument" 
root@srv-0:/data/docker/bootstrap# ll -h /data/docker/mnt/
total 28K
drwx--x--x   9 root root  131 May 23 08:30 ./
drwxr-xr-x  11 root root 4.0K May 23 08:12 ../
drwx------   5 root root 4.0K May 24 11:49 containers/
drwx------   3 root root   28 May 23 08:30 image/
drwxr-x---   3 root root   26 May 23 08:30 network/
drwx------ 133 root root  12K May 24 11:49 overlay/
drwx------   2 root root   10 May 24 11:22 tmp/
drwx------   2 root root   10 May 23 08:30 trust/
drwx------   4 root root 4.0K May 23 12:32 volumes/

```

The configuration is about the same on all 3 boxes (IPs are different obviously) and they all show the same symptoms (one of the boxes has no internet access and is only on the 192.168.10.0/24 network with the other 2 - i put the images on there using `docker save <images> | ssh docker load`). Like this on another machine:

```
root@srv-2:/data/docker/bootstrap# docker run --rm -it ubuntu:latest
root@b031c7a80b8d:/# exit
root@srv-2:/data/docker/bootstrap# docker run --rm -it ubuntu:trusty
docker: Error response from daemon: mkdir /data/docker/mnt/overlay/e37098a0043c2bd200b919c4cd466a1cfe98a03865b08be82efa215e32e92196-init/merged/dev/shm: invalid argument.
See 'docker run --help'.
```

**Describe the results you expected:**
A Container starting..

**Additional information you deem important (e.g. issue happens only occasionally):**
I have a big chain of images all based on my (modification/addon `FROM ubuntu:trusty`) ubuntu image - i re-built the entire chain yesterday so all images (ntp, squid, java-base and its descendants tomcat & karaf, postgresql, rabbitmq, redis, mongodb, ...) share the layers of my ubuntu base - i pushed that to my private registry (registry:2.3). My first instinct when i failed to run anything earlier today was to think i cocked up somewhere along that path but a `docker run ubuntu:trusty` (layers "Already exists") failed while a newly pulled ubuntu:latest didn't - so my next thought was that maybe the official trusty image was b0rked? 
However i can run either images on any other daemon (including one with the same 14.04.4 ubuntu, the same 3.19.0-39-generic kernel and overlay settings but in the default graph directory) so i'm guessing there's either some bug in the graph dir change (however there's still a single subfolder with a socket in /var/lib/docker/network/files/<randomname>.sock that was apparently generated (either by compose or the daemon)
`df -h` and `df -i` report there's plenty of space (1% in use on everything but /boot), the host fs is ext4 (ubuntu) and the partition used for graphdir xfs and is a LVM partition..

**Comment by HackToday** [comment] 2016-05-26 00:35
I can confirm it can be reproduced, and also I mentioned on https://github.com/docker/docker/issues/22771
but seems not get any attention.

**Comment by thaJeztah** [comment] 2016-05-26 12:31
Error looks similar to https://github.com/docker/docker/issues/20640

@HackToday your comment on https://github.com/docker/docker/issues/22771 didn't get attention, because it was not related to the actual issue reported there.

**Comment by aGGre55or** [comment] 2016-06-16 11:55
Everything is completely the same

**# docker version**
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**# docker info**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.2-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.55 GiB
Name: srv-docker
ID: L7PV:MJZR:MWAB:COXJ:IOEW:NH3O:RS4Y:GH72:SK4K:5QYS:NH2H:PRVE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

# docker build -t bld/java .
```
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM alpine:3.3
 ---> 184352182c50
Step 2 : MAINTAINER offer4job@outlook.com
error creating overlay mount to /var/lib/docker/overlay/0b5d2d3fd7de6109403f0984fd65b5eb67b5b2ed9132e3a99799bbe49a682d94-init/merged: invalid argument
```

docker 1.11.2 with overlay storage don't  work in CentOS  7.2.1511 :(((((((((((

**Comment by thaJeztah** [comment] 2016-06-16 21:25
@aGGre55or if you have a system to test on; Docker 1.12 will add a new "overlay2" driver, that fixes some of the limitations of the current overlay driver (but requires Kernel 4.0); https://github.com/docker/docker/pull/22126

The first release candidate for docker 1.12 is now available (see https://github.com/docker/docker/releases, or https://test.docker.com); interested to hear if the new driver resolves this issue

**Comment by HackToday** [comment] 2016-06-17 06:32
@thaJeztah I suggest if possible to debug the root issue here, I agree overlay2 is better, but overlay here failed seems not a good idea. 🚶

**Comment by buster** [comment] 2016-06-20 10:33
I have the same issue here:

Server Version: 1.12.0-rc2
Storage Driver: overlay2

Also not working with overlay driver.
Kernel is 4.6.0-1-amd64 #1 SMP Debian 4.6.1-1 (2016-06-06) x86_64 GNU/Linux.

**Comment by tj13** [comment] 2016-06-29 06:19
met the same issue on docker 1.10.3.
#docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.6.2-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: centosdev04.sit.caijj.net
ID: QINT:J7RX:ZZBH:VBSY:DVU3:LQFD:JLW7:GGHG:2G4S:GMXW:MFLL:WPXG
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
#uname -a
Linux centosdev04.sit.caijj.net 4.6.2-1.el7.elrepo.x86_64 #1 SMP Wed Jun 8 14:49:20 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

# docker run -m 100m --restart=always --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=9014:8080 --detach=true --name=cadvisor --privileged=true google/cadvisor
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay/2a02eefe4a9a4f3a5a05b2a246781a0b391b8108e41de899bd7e3206c4725e75-init/merged: invalid argument.
See 'docker run --help'.

**Comment by thaJeztah** [comment] 2016-06-29 17:52
@dmcgowan perhaps you have ideas?

**Comment by dmcgowan** [comment] 2016-06-29 20:21
I will try and setup an environment and test it out. The initial issue just appeared to be an xfs support issue since it was using 3.19.0-39-generic. The later issues are also xfs but getting a different message on a newer centos kernel, will see if can track down what is going on since we pointed to the rhel instructions to only use xfs in #10294.

**Comment by buster** [comment] 2016-06-30 13:12
I have this problem since a few days, and i think this is related to this: http://www.gossamer-threads.com/lists/linux/kernel/2439708

Unfortunately, i have XFS and the ftype is 0 per default.
And changing this would require reformatting all machines running docker.

Any idea how to solve this?

**Comment by thaJeztah** [comment] 2016-06-30 18:17
ping @rhvgoyal I see you were on that discussion that @buster linked above

**Comment by rhvgoyal** [comment] 2016-06-30 20:32
If your xfs was built with d_type=0, one will have to rebuilt it. Don't know of any workaround. Having said that, this issue does not seem to be d_type related to me.

**Comment by dmcgowan** [comment] 2016-06-30 22:34
Thanks @rhvgoyal and @buster for the extra information. Adding the kernel flag. 

I was able to test and confirm this works with 4.5 and not with 4.6 with ftype=0 on xfs.
See my test script here https://gist.github.com/dmcgowan/f01445186e59d19381d3bc7ca0c5324c.

### Results
#### 4.6.3-1-ARCH
- `mkfs -t xfs -m crc=0 -n ftype=0 -f /dev/loop0`<br>
`docker: Error response from daemon: error creating overlay mount to /tmp/tmp.8MfbWfl0lN/overlay/5b597886628faa4323251a510a571036ebafaa23e39775ac1965dbe7b01bd529-init/merged: invalid argument.`<br>
and in dmesg<br>
`overlayfs: upper fs needs to support d_type.` 
- `mkfs -t xfs -f /dev/loop0`<br>
Run works fine

#### 4.5.3-1-Arch
- `mkfs -t xfs -m crc=0 -n ftype=0 -f /dev/loop0`<br>
Run works fine

**Comment by buster** [comment] 2016-07-01 07:17
I am confused since i was using docker just fine for months (with XFS) and suddenly it stops working and the only fix is to reformat the whole system? Especially since this is the default setting creating XFS.
Are there other alternatives then overlayfs for Debian+XFS?

**Comment by thaJeztah** [comment] 2016-07-01 07:20
@buster have you always run on the same kernel version?

**Comment by buster** [comment] 2016-07-01 07:55
@thaJeztah nope, Debian updated the Kernel version a few days ago

**Comment by rhvgoyal** [comment] 2016-07-01 12:13
overlay is not supported with ftype=0. Thing is that we did not detect this and allowed this configuration and now we are detecting this and failing mounting. 

But that has this side affect of breaking existing users. Though existing configuration itself is bad and whiteouts can become visible.

**Comment by rhvgoyal** [comment] 2016-07-01 12:16
May be we should detect this bad configuration during mount and warn about it instead of failing mounting and that should allow existing configurations to work after upgrade.

**Comment by rhvgoyal** [comment] 2016-07-01 14:09
Ok, proposed a patch upstream to warn instead of error out if d_type is not supported.

http://marc.info/?l=linux-fsdevel&m=146738177911913&w=2

**Comment by fatg1988** [comment] 2017-11-01 12:30
`docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      linux/amd64
 Experimental: false`

`docker info
Containers: 33
 Running: 26
 Paused: 0
 Stopped: 7
Images: 30
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.11GiB
Name: xxx
ID: xxx
Docker Root Dir: /da/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

`docker run -d --privileged=true --name gitlab-runner --restart always  gitlab/gitlab-runner
docker: Error response from daemon: mkdir /da/docker/overlay/10bca507f5a9eeb31dd438b4afb44eddcefbd8b6c14fd72be21959c610ba4ea0-init/merged/dev/shm: invalid argument.`

**Comment by thaJeztah** [comment] 2017-11-01 12:47
@fatg1988 you are running an outdated version of Docker (17.04 has reached end-of-life), and based on the kernel version, a version of CentOS that's no longer supported as well (CentOS uses a rolling release model, and CentOS 7.4 is the current release, and the only version that's supported).

For RHEL and CentOS, only XFS as a backing system is supported;

The RHEL release notes mentions this; https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

> Only XFS is currently supported for use as a lower layer file system.
> ...
> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.
> ..
> Note that OverlayFS provides a restricted set of the POSIX standards. Test your application thoroughly before deploying it with OverlayFS.

If you cannot update your system or switch to another backing filesystem, you may want to use device mapper as an alternative see the documentation about [using device mapper as a storage driver](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/)

**Comment by thaJeztah** [comment] 2023-09-16 22:19
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 22:19 UTC
Labels: area/kernel, area/storage/overlay, kind/bug, version/1.11, version/1.12
