### ISSUE TITLE
Unable to remove containers 'device or resource busy'

### ISSUE THREAD

**Issue by le-ortega** [moby/moby#34198] opened 2017-07-20 06:44 UTC
**Description**
I have a Swarm cluster with a lot of services but I have an issue when I try to remove a service:
```Error response from daemon: driver "overlay" failed to remove root filesystem for 34d2340b73edd5466a675918c0f0d4567a68970d24065b45288c46926f4c8815: remove /var/lib/docker/overlay/edcb91e85162c7867a9816af6d24ca168c0506989069b728931b9586a578ff2e/merged: device or resource busy```

I have done many proofs and I have achieved a minimum environment to reproduce the problem always in an easy manner. Although I have a swarm cluster with 5 managers and 2 workers, the steps that I will detail right now have been performed in one of those nodes (manager1).

**Steps to reproduce the issue:**
I create a **cadvisor** container with the next command:
```
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
```

After this container is running, I create the next one (**node-exporter**):
```
docker run -d -p 9100:9100 \
  -v "/proc:/host/proc:ro" \
  -v "/sys:/host/sys:ro" \
  -v "/:/rootfs:ro" \
  --net="host" \
  quay.io/prometheus/node-exporter \
    -collector.procfs /host/proc \
    -collector.sysfs /host/sys \
    -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"
```

When both are running, I execute:
```
[root@CT-manager1 ~]# docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                    NAMES
afd35c0b08dd        quay.io/prometheus/node-exporter   "/bin/node_exporte..."   4 seconds ago       Up 3 seconds                                 determined_bell
34d2340b73ed        google/cadvisor:latest             "/usr/bin/cadvisor..."   11 seconds ago      Up 9 seconds        0.0.0.0:8080->8080/tcp   cadvisor
```

And I try to remove **cadvisor** container:
```
[root@CT-manager1 ~]# docker rm -f 34d2340b73ed
Error response from daemon: driver "overlay" failed to remove root filesystem for 34d2340b73edd5466a675918c0f0d4567a68970d24065b45288c46926f4c8815: remove /var/lib/docker/overlay/edcb91e85162c7867a9816af6d24ca168c0506989069b728931b9586a578ff2e/merged: device or resource busy
```

When I check the status of **cadvisor** container, it is "**Dead**":
```
[root@CT-manager1 ~]# docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS               NAMES
afd35c0b08dd        quay.io/prometheus/node-exporter   "/bin/node_exporte..."   4 minutes ago         Up 4 minutes                              determined_bell
34d2340b73ed        google/cadvisor:latest             "/usr/bin/cadvisor..."   4 minutes ago         Dead                                    cadvisor
```

For removing "**cadvisor**", I have to remove "**node-exporter**" container previously.

I see that both containers mount paths which are managed by docker.

**Describe the results you received:**
I can't remove some containers when cadvisor and node-exporter are running on my cluster. Also, I have written the minimum environment where it happens, but in my cluster with all services, I can't remove some data volumes and services (containers become to "dead" status) when cadvisor and node-exporter are running on it.

**Describe the results you expected:**
Remove containers and data volume properly when cadvisor and node-exporter are running.

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Output of `docker version`:**

```
[root@CT-manager1 ~]# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
[root@CT-manager1 ~]# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 33
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: a03vue0iqfzddw6h7u18kbimh
 Is Manager: true
 ClusterID: 4a6b4z8nlzgkosuabtu4zkwp9
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: x.x.x.x
 Manager Addresses:
  x.x.x.x:2377
  y.y.y.y:2377
  z.z.z.z:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.26GiB
Name: CT-manager1
ID: PCAS:DLFN:LUC3:BBN5:JRQ5:YXZM:RI7G:NTTZ:TSLR:7THN:VJXB:BXFM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This cluster runs in DigitalOcean.

**Comment by thaJeztah** [comment] 2017-07-20 09:18
This is a known problem when using cAdvisor, and more troublesome on older kernels (3.10); the cause of this is that cAdvisor here mounts various paths from the host into a container. Older kernels "leak" these mounts between namespaces, causing the mounts to appear "in use" (e.g., both containers mount `/`, and when removing one of them, the kernel reports the mount to be in use by the other container).

CentOS 7.4 / RHEL 7.4 will hopefully resolve this with a more recent kernel (or back ported patches), but to work around this problem, consider:

- if you need the `/` mount (cAdvisor _can_ run without, but won't report some information)
- configure the docker daemon to use `MountFlags=slave` (see https://github.com/moby/moby/pull/31490); you can do this with a "drop-in" / "override file";

Create a directory for your override file (if it does not yet exist);

```bash
$ mkdir -p /etc/systemd/system/docker.service.d
```

Create a drop-in unit file;


```bash
cat > /etc/systemd/system/docker.service.d/mountflags-slave.conf <<"EOF"
[Service]
# MountFlags "slave" helps to prevent "device busy" errors on RHEL/CentOS 7.3 kernels
MountFlags=slave
EOF
```

Reload the systemd configuration, and restart the docker service

```bash
$ systemctl daemon-reload
$ systemctl restart docker.service
```

Verify the new configuration is active

```bash
$ systemctl cat docker.service
```

Which should show both the main systemd unit file, and the drop-in (override) you created:

```
# /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service
Wants=network-online.target

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/docker.service.d/mountflags-slave.conf
[Service]
# MountFlags "slave" helps to prevent "device busy" errors on RHEL/CentOS 7.3 kernels
MountFlags=slave
```


I'm closing this issue, because this is a known problem, and there's already a [number of open issues on this](https://github.com/moby/moby/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20%22device%20or%20resource%20busy%22), but I hope the above helps, and feel free to continue the conversation.

**Closed by thaJeztah** 2017-07-20 09:18 UTC
Labels: version/17.06

**Comment by RakeshNagarajan** [comment] 2018-07-09 10:30
https://ekuric.wordpress.com/2015/10/09/docker-complains-about-cannot-remove-device-or-resource-busy/

Solution very clear

**Comment by CanYouGiveMeAName** [comment] 2021-05-12 03:11
I get tham question only when I rm container on multi goroution with go api.
