### ISSUE TITLE
How can I publush port just by docker-compose.yml  (swarm)?

### ISSUE THREAD

**Issue by eromoe** [moby/moby#36143] opened 2018-01-30 08:29 UTC
Hello,

I found it would not automatically publish ports which defined in docker-compose.yml

For example:
```
version: '3'
services:
  mongo:
    image: ${PRIVATE_REGISTRY}/${MONGO_IMAGE}
    restart: always
    ports:
      - 11081:27017

  postgres:
    image: ${PRIVATE_REGISTRY}/${POSTGRES_IMAGE}
    restart: always
    container_name: basin-postgres
    environment:
      POSTGRES_USER: basin
      POSTGRES_PASSWORD: basin_pa44
      POSTGRES_DB: demo
    ports:
      - 11085:5432
```

From
https://stackoverflow.com/questions/38141739/docker-deploy-wont-publish-port-in-swarm

I saw `docker service update my-service --publish-add 80:80`

But I wonder how can I set the publish port by `docker-compose.yml` ? 

I google it but found nothing. If there is a document about this, please provide it and the example in the swarm section  https://docs.docker.com/engine/swarm/services/

**Comment by talhajilal** [comment] 2018-09-12 16:12
I am also trying to find the same answer.

**Comment by thaJeztah** [comment] 2018-11-08 17:29
I'm not able to reproduce this;

```bash
docker stack deploy -c- test <<EOF
version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - 11081:80
EOF
```

After that stack is deployed, the port for the service is published;

```bash
docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
2ijtqh6qqkgx        test_web            replicated          1/1                 nginx:alpine        *:11081->80/tcp
```

And the service can be reached;

```bash
curl localhost:11081
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
```


Note, however, that when working with services, the container ports are not published directly, as networking connections go through a load-balancer for the service, and then get routed to the tasks (containers) backing the service. So if you look at `docker ps`, you'll see that the _container_ does not have ports published;

```bash
docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
deb2daf8b7c3        nginx:alpine        "nginx -g 'daemon of…"   2 minutes ago       Up 2 minutes        80/tcp              test_web.1.ul6x2ev5v1p634qxp7pfcw0ge
```

That is expected (as explained above).


I'll close this issue, because I'm not able to reproduce, and the ticket does not provide information about the version of docker that is used; feel free to comment though if you're able to reproduce this on the current version of docker, and have steps to reproduce the issue.

**Closed by thaJeztah** 2018-11-08 17:29 UTC
Labels: area/swarm

**Comment by Platypuschan** [comment] 2022-12-10 21:02
I think he meant the part with publishing ports, directly not over the routing mesh of docker... Curse me if i´m wrong...

```
docker service create \
  --mode global \
  --publish mode=host,target=80,published=8080 \
  --name=nginx \
  nginx:latest
```

The part with the "mode=host" the thing, but i don´t know how the syntax for the compose file.
