### ISSUE TITLE
One letter long names are not permitted

### ISSUE THREAD

**Issue by DamianFekete** [moby/moby#36040] opened 2018-01-17 13:37 UTC
Is there a reason to have this regexp in [names.go](https://github.com/moby/moby/blob/master/daemon/names/names.go)
```
const RestrictedNameChars = `[a-zA-Z0-9][a-zA-Z0-9_.-]`
```
instead of 
```
const RestrictedNameChars = `[a-zA-Z0-9][a-zA-Z0-9_.-]?`
``` 
which would allow names that are one char long?

_I couldn't find a duplicate issue._

**Comment by thaJeztah** [comment] 2018-01-17 14:11
Yes; reason is that (especially for volumes) single character names are ambiguous. The `-v` /`--volume` flag is quite "overloaded" in functionality (both "bind-mounts" and "named volumes" can be specified with that flag), and uses a colon-separated format.

Because of that (taking Windows into account) it's not possible to distinguish a host path from a named volume, for example:

```bash
docker run -it -v C:\Windows busybox
```

Could either mean:

- use named volume `C`, and mount it at `\Windows` inside the container, or
- create an anonymous volume for `C:\Windows` inside the container

And

```bash
docker run -it -v C:\Windows\foo:ro busybox
```

Which could mean:

- bind-mount `C:\Windows\foo` from the host at `ro` inside the container
- use named volume `C`, mount it at `\Windows\foo` inside the container, and make it read-only (`ro`)

For that reason (and some other corner-cases), single-letter names are not allowed.


Please note that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-01-17 14:11 UTC
