### ISSUE TITLE
Docker Compose BROKEN on 24.0.5

### ISSUE THREAD

**Issue by tidux** [moby/moby#46909] opened 2023-12-07 20:43 UTC
### Description

Docker Compose does not work with Moby Engine on Fedora 39 Silverblue or other immutable-desktop editions.  Manually placing the `docker-compose` binary in `$HOME/.docker/cli-plugins/docker-compose` does not work.

### Reproduce

1. install an immutable flavor of Fedora 39 (Silverblue, Kinoite, Sericea)
2. `rpm-ostree install moby-engine docker-compose`
3. reboot
4. `docker compose up -f docker-compose.yaml`
5. See `docker: 'compose' is not a docker command` error.

### Expected behavior

The docker-compose environment is brought up and runs.

### docker version

```bash
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.21.0
 Git commit:        %{shortcommit_cli}
 Built:             Sun Aug 27 16:45:40 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.0
  Git commit:       %{shortcommit_moby}
  Built:            Sun Aug 27 16:45:40 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.23
  GitCommit:        
 runc:
  Version:          1.1.8
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
WARNING: Plugin "/home/tidux/.docker/cli-plugins/docker-compose" is not valid: failed to fetch metadata: exit status 1

Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 24.0.5
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  selinux
  cgroupns
 Kernel Version: 6.5.11-300.fc39.x86_64
 Operating System: Fedora Linux 39.20231118.0 (Kinoite)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.07GiB
 Name: [haha nope not showing my laptop's hostname]
 ID: d8f47234-df51-4f65-a7ba-c6fde5d2a1cd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Comment by thaJeztah** [comment] 2023-12-07 20:58
Based on that output, this looks like an issue with the compose binary;

```
WARNING: Plugin "/home/tidux/.docker/cli-plugins/docker-compose" is not valid: failed to fetch metadata: exit status 1
```

Which could be an issue with the packages provided by your distro (I see you installed using the distro-packages, which are not built or maintained here in upstream)

- are you seeing the same issue when installing the packages from download.docker.com, or binaries downloaded from the docker compose github repository (https://github.com/docker/compose)?
- from the error message, it looks like the binary is failing; what does executing `/home/tidux/.docker/cli-plugins/docker-compose docker-cli-plugin-metadata` show?

> Install an immutable flavor of Fedora 39 (Silverblue, Kinoite, Sericea)

I'm not familiar with these distro flavours, but if "immutable" means read-only filesystems, then it's _possible_ that the compose plugin requires write access to some paths  (executing the  `/home/tidux/.docker/cli-plugins/docker-compose docker-cli-plugin-metadata`  command will hopefully produce a more useful error in that case)

I'll close this issue, because this issue is not related to the docker engine (docker daemon) maintained in this repository, and issues with compose are best reported with the distro packager, or in the compose issue tracker (https://github.com/docker/compose/issues), but I hope the above helps you find more information on the cause for your issue.

**Closed by thaJeztah** 2023-12-07 20:58 UTC
Labels: status/0-triage, kind/bug
