### ISSUE TITLE
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"

### ISSUE THREAD

**Issue by kingAndGithub** [moby/moby#35276] opened 2017-10-24 03:10 UTC
**currently， i am still facing the problem on docker 1.12.6 after systemctl restart docker.service
when i restart docker deamon and exec to into the container, the error is below:**

[root@jhou-swarm ~]# **systemctl restart docker.service**
[root@jhou-swarm ~]# **docker ps**
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
4a7673c5c604        mysql               "docker-entrypoint.sh"   50 seconds ago      Up 45 seconds       3306/tcp            kickass_mayer
bd304a1c0bd3        mysql               "docker-entrypoint.sh"   12 minutes ago      Up 12 minutes       3306/tcp            admiring_fermi
5d3148088779        mysql               "docker-entrypoint.sh"   3 days ago          Up 3 days           3306/tcp            stupefied_franklin
[root@jhou-swarm ~]# **docker exec -it 4a7673c5c604 bash**
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"

the system info is below:
 [root@jhou-swarm ~]# docker info
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 13
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-201770149-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.008 GB
 Data Space Total: 107.4 GB
 Data Space Available: 32.18 GB
 Metadata Space Used: 3.764 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 7.64 GiB
Name: jhou-swarm.novalocal
ID: VC6K:VIMW:PCQQ:QB3L:V4ER:EZCF:PTRB:YABJ:RAN5:FO6N:KKMZ:TWB2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 gcr.io
 127.0.0.0/8
Registries: docker.io (secure)

how can i fix it?

**Comment by kingAndGithub** [comment] 2017-10-24 03:20
@mlaventure can you help me see the issue, thanks very much

**Comment by kingAndGithub** [comment] 2017-10-24 03:22
Still has another problem that **the container would be exited after i attach the container**

**Comment by thaJeztah** [comment] 2017-10-24 19:53
This issue looks to only be reproducible on the Red Hat fork of Docker, not on the current official builds of Docker (see my comment on https://github.com/moby/moby/issues/29704#issuecomment-339038715). Docker 1.12.6 has reached end of life, and I have not seen this issue reported with any current version of the official docker packages, so I'll close this issue.

If you cannot upgrade to an official package of docker, and are running the Red Hat packages, please report your issue in their issue tracker: https://bugzilla.redhat.com/index.cgi

If you're encountering this problem on a _current version of docker_, please open a new issue and provide the information that's requested in the issue template.

Im closing this issue because of the above, but feel free to comment after I closed

**Closed by thaJeztah** 2017-10-24 19:53 UTC
Labels: area/runtime

**Comment by kingAndGithub** [comment] 2017-10-25 14:27
@thaJeztah Hi thaJeztah,
i tried to install the offical docker based on the page https://docs.docker.com/engine/installation/linux/docker-ce/centos/,  but it prompted out the error:

```
[root@jhou-swarm usr]# yum-config-manager     --add-repo     https://download.docker.com/linux/centos/docker-ce.repo
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 12] Timeout on https://download.docker.com/linux/centos/docker-ce.repo: (28, 'Connection timed out after 30186 milliseconds')
```
and if i import the file from https://download.docker.com/linux/centos/docker-ce.repo, it still prompted out the error:
````
[root@jhou-swarm usr]# yum install docker-ce -y
Loaded plugins: fastestmirror
https://download.docker.com/linux/centos/7/x86_64/stable/repodata/repomd.xml: [Errno 12] Timeout on https://download.docker.com/linux/centos/7/x86_64/stable/repodata/repomd.xml: (28, 'Connection timed out after 30139 milliseconds')
Trying other mirror.
https://download.docker.com/linux/centos/7/x86_64/stable/repodata/repomd.xml: [Errno 12] Timeout on https://download.docker.com/linux/centos/7/x86_64/stable/repodata/repomd.xml: (28, 'Connection timed out after 30036 milliseconds')
Trying other mirror.
```
`
Is my network rate not ok?

**Comment by thaJeztah** [comment] 2017-10-25 14:34
Sounds like something in your environment; if you try to directly download a package from https://download.docker.com/linux/centos/7/x86_64/stable/Packages/, does that work? Your system looks quite outdated in general (kernel `3.10.0-229.el7.x86_64` looks like an older version of CentOS), and I'd recommend keeping up to date, as CentOS uses a rolling release model (i.e., when CentOS 7.4 was released, al older CentOS releases are EOL'd and no longer receive (security) updates)

**Comment by kingAndGithub** [comment] 2017-10-26 10:05
@thaJeztah Hi thaJeztah,
 Sorry to disturb you again, but the system seems to be expanded out.

`[root@jhou-swarm ~]# docker run -d -t 196e0ce0c9fb bash
4b5bbe7ccc6103d46c7866ea9c46caa5ef600a100b0894ee736b9005d0df0d50
docker: Error response from daemon: failed to update the store state of sandbox: failed to update store for object type *libnetwork.sbState: json: cannot unmarshal object into Go struct field sbState.ExtDNS of type string.`

the docker version is below:
`[root@jhou-swarm ~]# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false`

my platform is below:
`[root@jhou-swarm ~]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)`

go version is below:
`[root@jhou-swarm ~]# go version
go version go1.8.3 linux/amd64`

and I have installed sandbox:
`[root@jhou-swarm ~]# rpm -qa | grep sandbox
selinux-policy-sandbox-3.13.1-166.el7_4.5.noarch
policycoreutils-sandbox-2.5-17.1.el7.x86_64`

so, what is your opinion.

**Comment by kingAndGithub** [comment] 2017-10-26 10:19
the kernel is that:
 3.10.0-693.5.2.el7.x86_64

**Comment by thaJeztah** [comment] 2017-10-26 13:55
hm, that's odd, looks like this relates to https://github.com/docker/libnetwork/blob/19ac3ea7f52bb46e0eb10669756cdae0c441a5b1/sandbox_store.go#L30-L35

Do you have live-restore enabled?

**Comment by kingAndGithub** [comment] 2017-10-27 01:47
yes, i enabled that.
but if don't enable live-restore, the response are the same.

**Comment by kingAndGithub** [comment] 2017-11-02 09:08
@thaJeztah I have updated the docker successfully by removing the file /var/lib/docker/network/files/local-kv.db.
besides, i update the linux kernel to centos 7.4 and docker to 1.17.6
