### ISSUE TITLE
ERRO[4334] error getting events from daemon: EOF  

### ISSUE THREAD

**Issue by BenjiKCF** [moby/moby#31220] opened 2017-02-21 14:50 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

Hello everyone, after following the google codelabs, [Codelabs](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/?utm_campaign=chrome_series_machinelearning_063016&utm_source=gdev&utm_medium=yt-desc#3) I have received an error  `ERRO[4334] error getting events from daemon: EOF`  after `Creating bottleneck at /tf_files/bottlenecks/roses/13231224664_4af5293a37.jpg.txt` 

Update:
I reran it and this shows up
`ERRO[53469] error getting events from daemon: EOF `

**Steps to reproduce the issue:**
1.
```
 python tensorflow/examples/image_retraining/retrain.py \
> --bottleneck_dir=/tf_files/bottlenecks \
> --how_many_training_steps 500 \
> --model_dir=/tf_files/inception \
> --output_graph=/tf_files/retrained_graph.pb \
> --output_labels=/tf_files/retrained_labels.txt \
> --image_dir /tf_files/flower_photos

```

**Describe the results you received:**
`ERRO[4334] error getting events from daemon: EOF`

**Describe the results you expected:**
`Finish the retraining`

**Output of `docker version`:**

`Docker version 1.13.1, build 092cba3`

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: UNXQ:IPAT:2ZHG:3443:M7XI:M3FW:W7Q7:G4HV:IKKW:W5TU:72TI:SH3G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-02-21T14:43:50.071749826Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS X with python 2.7, 
and this shows up
`W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Thank you so much`

**Comment by tomgs** [comment] 2017-03-02 15:51
Happened to me as well, different error codes though.

**Comment by BenjiKCF** [comment] 2017-03-22 06:55
Yes, the error code varies all the time.

**Comment by uncle-mo** [comment] 2017-03-23 00:10
I had this same issue. Having made the following changes I ran the script again and I didn't see the issue again.

In "Docker > Preferences" I increased the CPU's to 4 (from 2) as per the instructions here https://www.reddit.com/r/tensorflow/comments/5uhac5/docker_issues/

I also increased the RAM but I'm not sure if that was required.

**Comment by cazantyl** [comment] 2017-03-27 18:12
uncle-mo's answer fixed my issue. Just needed to bump the CPU's to 4

**Comment by pelly** [comment] 2017-06-02 12:10
Are there any plans to look at underlying issue? I'm getting a similar error and would like to keep the CPUs dedicated to 2.

**Comment by cpuguy83** [comment] 2017-06-02 12:56
Can you provide the daemon logs from when this occurs?

**Comment by pelly** [comment] 2017-06-02 13:10
Ah just had some inspiration - it happens when I sleep/wake the Macbook. I
can reproduce it reliably now by doing that.

Regarding daemon logs (might shed some more light on exactly what's
happening in sleep/wake)... Not exactly sure how to do that on a killed
container, is this right:

I committed it to a new image and ran /bin/bash on that.

But I can't find any logs under /var/logs on the container.

As far as I'm concerned the issue is "solved" for me (don't let computer
sleep), but I can dig into this more if you want.

**Comment by cpuguy83** [comment] 2017-06-02 13:40
@pelly This would be logs for the daemon itself, not the container.
@justincormack What's the best way to get daemon logs on docker4mac? (@pelly I'm assuming you are on Docker4Mac).

**Comment by thaJeztah** [comment] 2017-06-02 13:48
@cpuguy83 @pelly something like this should work;

```
docker run --rm -v /var/log:/logs alpine cat /logs/docker.log > daemon-logs
```

Which puts the logs in a local file named `daemon-logs`

**Comment by pelly** [comment] 2017-06-02 14:41
Here you go. For reference, here's how I generated the file:

1.) Start the container with two mapped dirs:
> docker run -it -v /var/log:/logs -v ~/docker_logs:/logs_output
busted_cron /bin/bash

2.) In container, tail and follow /logs/docker.log:
> tail -1000 -f /logs/docker.log > /logs_output/docker_log.log

3.) Sleep the computer. Wait 10 seconds. Wake the computer.

4.) Witness error message: "ERRO[0101] error getting events from daemon: EO
F"
(Note - error number is different every time)

5.) Docker log file is in ~/docker_logs/docker_log.log on host. (attached)

**Comment by pelly** [comment] 2017-06-02 15:51
Log file needed a supported extension (used .txt)
[docker_log.txt](https://github.com/moby/moby/files/1048185/docker_log.txt)

**Comment by cpuguy83** [comment] 2017-06-05 14:54
It looks like the daemon is restarting but I do not see why it would be restarting.
Is this on docker4mac? @pelly

**Comment by pelly** [comment] 2017-06-05 16:46
Yes docker4mac

**Comment by cancerberoSgx** [comment] 2017-10-18 20:56
same here I-m getting this error in a high performance task that exit with that same error and the docker daemon is restarted. Any workaround for this? Thanks

**Comment by thaJeztah** [comment] 2023-09-16 20:43
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 20:43 UTC
Labels: status/more-info-needed, area/daemon, version/1.13
