### ISSUE TITLE
IPv6 dadfailed in docker 1.7.1 containers

### ISSUE THREAD

**Issue by oszi** [moby/moby#15840] opened 2015-08-25 22:09 UTC
Description of problem:

IPv6 is broken in Docker 1.7.1 on CoreOS after upgrading from 1.6.2. The containers still get an assigned IPv6 address, the routes are also set up but the container interfaces are in dadfailed state. There are no address collisions as far I can see. The host has no IPv6 issues so `--net=host` works.

`docker version`:

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 2c2c52b-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 2c2c52b-dirty
OS/Arch (server): linux/amd64
```

`docker info`:

```
Containers: 9
Images: 104
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.5-coreos
Operating System: CoreOS 779.0.0
CPUs: 1
Total Memory: 493.6 MiB
Name: omega4
ID: KHST:DGXZ:3GMN:T7AL:LH7T:G6YW:ET5V:W3BL:DVD2:LYMT:EDBF:NFP2
```

`uname -a`:

Linux omega4 4.1.5-coreos #2 SMP Thu Aug 20 05:11:22 UTC 2015 x86_64
Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz GenuineIntel GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

DigitalOcean with IPv6 tunneling.

(The tunnel is set up before docker could start and worked with <=1.6.2.)

Custom docker daemon options:

```
--ipv6 --fixed-cidr-v6="2001::[...]/64" --bip="1.2.3.0/21" --dns="1.2.3.1" \
--userland-proxy=false
```

How reproducible:

Happens even after reboots, service restarts.

Steps to reproduce:
1. Boot CoreOS 779.0.0
2. Configure docker with the aforementioned options
3. Start any container
4. ping6 google.com

Actual Results:

```
# ip -6 addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
40: eth0@if41: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 
    inet6 2001::[...]/64 scope global tentative dadfailed 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe1e:2812/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever
```

Even the container's own address is unreachable:

```
# ping6 $(ip -6 addr show dev eth0 | egrep -o '2001:[0-9a-f:]+')
PING 2001::[...](2001::[...]) 56 data bytes
From ::1 icmp_seq=1 Destination unreachable: Address unreachable
From ::1 icmp_seq=2 Destination unreachable: Address unreachable
From ::1 icmp_seq=3 Destination unreachable: Address unreachable
From ::1 icmp_seq=4 Destination unreachable: Address unreachable
```

Expected Results:
Well... :)

Additional info:

sysctl configuration:

```
# Turn on Source Address Verification in all interfaces
net.ipv4.conf.default.rp_filter=1
net.ipv4.conf.all.rp_filter=1

# Enable SYN-flood protections
net.ipv4.tcp_syncookies=1

# Do not accept ICMP redirects
net.ipv4.conf.all.accept_redirects=0
net.ipv6.conf.all.accept_redirects=0

# Enable Packet Forwarding
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1

# IPv6 Privacy Extensions
net.ipv6.conf.default.use_tempaddr=1
net.ipv6.conf.all.use_tempaddr=1
```

**Comment by ross211** [comment] 2015-08-27 06:38
I think this is somehow being caused by --userland-proxy=false as I was having this issue too after setting this. I was able to reproduce it quite reliably only when that option was set.

**Comment by Nightling** [comment] 2015-08-27 16:32
Indeed @ross211, I can confirm.

**Comment by ross-w** [comment] 2015-09-17 03:21
Also seeing this issue here with --userland-proxy=false

**Comment by chrisnew** [comment] 2015-11-29 18:22
Same here with --userland-proxy=false. Interestingly, it worked well on my test setup in virtualbox. On production, it fails.

**Comment by novag** [comment] 2016-02-25 14:23
Has anyone done some deeper research yet? I'm experiencing the same problem after disabling the userland proxy.

**Comment by aboch** [comment] 2016-02-25 17:17
@novag 

That is interesting. FYI, since version 1.10.0, docker disables the DAD on containers' interfaces at the time it sets their IPv6 address.

```
root@36eaee1148d8:/# ip addr
<snip>
590: eth0@if591: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:14:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:2002::2/80 scope global nodad    <--- <---
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe14:2/64 scope link 
       valid_lft forever preferred_lft forever
root@36eaee1148d8:/# 
```

Can you share something more about your setup. 
Thanks.

**Comment by novag** [comment] 2016-02-26 12:53
Thanks. It seems that the nodad flag is set per IP. I'm assigning another (fixed) IP with the containers network namespace. Using the nodad flag for the IP works. What's going on that we need to disable the DAD?

Much more interesting is that even the link-local address is recognized as a duplicate:
> 14: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP > group default 
>     link/ether 02:42:ac:11:00:06 brd ff:ff:ff:ff:ff:ff
>     inet 172.17.0.6/16 scope global eth0
>        valid_lft forever preferred_lft forever
>     inet6 xxxx::yyyy scope global nodad  <-- fixed IP with nodad flag
>        valid_lft forever preferred_lft forever
>     inet6 xxxx::zzzz scope global nodad <-- docker assigned (IP pool)
>        valid_lft forever preferred_lft forever
>     inet6 fe80::42:acff:fe11:6/64 scope link tentative dadfailed 
>        valid_lft forever preferred_lft forever

I have only disabled the userland proxy and enabled IPv6 with an /80 IP range. In addition I assign fixed IP addresses to some containers.

**Comment by ab77** [comment] 2016-04-29 12:21
Replicated with `/64` prefix assigned to Docker bridge and user-land proxy set to `false`. Manually adding ipv6 addrs within containers requires `nodad` flag to be set, otherwise additional IPs are not functional. Link-local IP is in `dadfailed` state. Docker server version `1.11.1`.

**Closed** 2018-04-18 08:58 UTC
Labels: area/networking, version/1.7
