### ISSUE TITLE
[v27, swarm] Unable to set custom IPv6 subnets for overlay networks

### ISSUE THREAD

**Issue by benz0li** [moby/moby#48116] opened 2024-07-02 19:32 UTC
### Description

The update from v26 to v27 breaks IPv6 overlay networks with custom IPv6 subnets.

### Reproduce

Executing

```bash
docker network create \
  --driver overlay \
  --ipv6 \
  --opt encrypted \
  --subnet "10.0.100.0/24" \
  --subnet "fd14:8656:a32e:100::/64" \
  test
```

with v27 results in

```bash
docker network inspect test
```

```
[
    {
        "Name": "test",
        "Id": "3377xehtebjuraw2239sx45s8",
        "Created": "2024-07-02T19:20:43.501515055Z",
        "Scope": "swarm",
        "Driver": "",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "",
            "Options": null,
            "Config": null
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": null,
        "Labels": null
    }
]
```

### Expected behavior

Executing

```bash
docker network create \
  --driver overlay \
  --ipv6 \
  --opt encrypted \
  --subnet "10.0.100.0/24" \
  --subnet "fd14:8656:a32e:100::/64" \
  test
```

with v26 results in

```bash
docker network inspect test
```

```
[
    {
        "Name": "test",
        "Id": "879r7o2ko253ss4eg719woddl",
        "Created": "2024-07-02T19:25:56.412102964Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.100.0/24",
                    "Gateway": "10.0.100.1"
                },
                {
                    "Subnet": "fd14:8656:a32e:100::/64",
                    "Gateway": "fd14:8656:a32e:100::1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4141,4142",
            "encrypted": ""
        },
        "Labels": null
    }
]
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:50 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:50 2024
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: [redacted]
  Running: [redacted]
  Paused: [redacted]
  Stopped: [redacted]
 Images: [redacted]
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: [redacted]
  Is Manager: true
  ClusterID: [redacted]
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: [redacted]
  Manager Addresses:
   [redacted]:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  userns
  cgroupns
 Kernel Version: 6.1.0-22-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: [redacted]
 Total Memory: [redacted]
 Name: [redacted]
 ID: [redacted]
 Docker Root Dir: /var/lib/docker/165536.165536
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Ping @thaJeztah

**Comment by akerouanton** [comment] 2024-07-02 19:57
Hi @benz0li,

The output of `docker network inspect ...` is always empty for overlay networks that aren't referenced by any running container.

When an overlay network is created, the request is sent to the leader. It will store the network definition locally and in the distributed database shared by all managers. On that node, and IIRC on other manager nodes, your `docker network inspect` will succeed but show an almost-empty response (eg. IPAM options won't be visible, etc... but some props like `EnableIPv6` and `Attachable` will be correctly set).

When a container is scheduled, or `docker run` is called with an attachable network specified, that task / container will request the Swarm leader a network-node attachment. Then, the container is started as usual, and `docker network inspect` will show the full network state (be it on a leader, manager or worker node).

In your v26 output, I see properties like the `vxlanid_list` set. This indicates the network-node attachment has been made, and thus at least one container / task attached to that network is running on that specific node.

Since your report doesn't mention starting a container or checking if an attached task has been scheduled on that node, I believe this is the cause.

**Comment by benz0li** [comment] 2024-07-03 13:11
> The output of `docker network inspect ...` is always empty for overlay networks that aren't referenced by any running container.

I disagree.

> When an overlay network is created, the request is sent to the leader. It will store the network definition locally and in the distributed database shared by all managers. On that node, and IIRC on other manager nodes, your `docker network inspect` will succeed but show an almost-empty response (eg. IPAM options won't be visible, etc... but some props like `EnableIPv6` and `Attachable` will be correctly set).

Executing

```bash
docker network create \
  --driver overlay \
  --ipv6 \
  --opt encrypted \
  --subnet "10.0.100.0/24" \
  --subnet "fd14:8656:a32e:100::/64" \
  test
```

with a freshly installed v26 results in

```bash
docker network inspect test
```

```
[
    {
        "Name": "test",
        "Id": "6pc608btczrhvobekcg1a1c9s",
        "Created": "2024-07-03T12:56:22.717833685Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.100.0/24",
                    "Gateway": "10.0.100.1"
                },
                {
                    "Subnet": "fd14:8656:a32e:100::/64",
                    "Gateway": "fd14:8656:a32e:100::1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097,4098",
            "encrypted": ""
        },
        "Labels": null
    }
]
```

> In your v26 output, I see properties like the `vxlanid_list` set. This indicates the network-node attachment has been made, and thus at least one container / task attached to that network is running on that specific node.
> 
> Since your report doesn't mention starting a container or checking if an attached task has been scheduled on that node, I believe that's the cause (and not something related to IPv6).

I created a VM (QEMU), installed Debian 12 and followed [Install Docker Engine on Debian > Installation methods > Install using the `apt` repository](https://docs.docker.com/engine/install/debian/#install-using-the-repository): 1. Set up Docker's `apt` repository. Followed by

```bash
VERSION_STRING=5:26.1.4-1~debian.12~bookworm
sudo apt-get install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-buildx-plugin docker-compose-plugin
docker swarm init
```

and the `docker network create` and `docker network inspect` commands.

**Comment by benz0li** [comment] 2024-07-03 13:45
The following `docker-compose.yml`

```yml
services:
  debian:
    image: debian:latest
    networks:
      - test
    tty: true

networks:
  test:
    external: true
```

can be successfully deployed by executing `docker stack deploy -c docker-compose.yml test`.

**Comment by benz0li** [comment] 2024-07-03 13:51
After upgrading to v27 (latest), the service refuses to start.

```bash
docker service ps --no-trunc test_debian
```

```
ID                          NAME                IMAGE                                                                                   NODE          DESIRED STATE   CURRENT STATE          ERROR                                                          PORTS
v374u7q5pfc2r8ok0mnqdh30u   test_debian.1       debian:latest@sha256:1dc55ed6871771d4df68d393ed08d1ed9361c577cfeb903cd684a182e8a3e3ae                 Running         New 3 minutes ago                                                                     
z92olbcrzbqudj4dlzbxrqq1p    \_ test_debian.1   debian:latest@sha256:1dc55ed6871771d4df68d393ed08d1ed9361c577cfeb903cd684a182e8a3e3ae   docker-test   Shutdown        Failed 3 minutes ago   "No such container: test_debian.1.z92olbcrzbqudj4dlzbxrqq1p"   
si8ykfloi2zvbw9lqqi6kmo03    \_ test_debian.1   debian:latest@sha256:1dc55ed6871771d4df68d393ed08d1ed9361c577cfeb903cd684a182e8a3e3ae   docker-test   Shutdown        Failed 3 minutes ago   "No such container: test_debian.1.si8ykfloi2zvbw9lqqi6kmo03"
```

```bash
docker network inspect test
```

```
[
    {
        "Name": "test",
        "Id": "6pc608btczrhvobekcg1a1c9s",
        "Created": "2024-07-03T12:56:22.717833685Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.100.0/24",
                    "Gateway": "10.0.100.1"
                },
                {
                    "Subnet": "fd14:8656:a32e:100::/64",
                    "Gateway": "fd14:8656:a32e:100::1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097,4098",
            "encrypted": ""
        },
        "Labels": null
    }
]
```

**Comment by benz0li** [comment] 2024-07-03 13:58
Workaround for v27:

```bash
docker stack rm test
docker network rm test
```

```bash
docker network create \
  --driver overlay \
  --ipv6 \
  --opt encrypted \
  --subnet "10.0.100.0/24" \
  test
```

```bash
docker stack deploy -c docker-compose.yml test
```

---

```bash
docker network inspect test 
```

```
[
    {
        "Name": "test",
        "Id": "8n7ttp7xr30tvgqsdyzr7j3wi",
        "Created": "2024-07-03T15:52:50.49265536+02:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.100.0/24",
                    "Gateway": "10.0.100.1"
                },
                {
                    "Subnet": "fdf4:dd75:b5d5::/64",
                    "Gateway": "fdf4:dd75:b5d5::1/64"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "fbb6cd73c856f56c24cad9cf8e04b303c2a3909a4fac7204448a9eab335fc8d9": {
                "Name": "test_debian.1.da41osg29yg7hifovqwe8ran6",
                "EndpointID": "e7ef628942f4986c75bb0252fed79a5a91686eb515480e0bf19fc55cdb64d588",
                "MacAddress": "02:42:0a:00:64:03",
                "IPv4Address": "10.0.100.3/24",
                "IPv6Address": "fdf4:dd75:b5d5::3/64"
            },
            "lb-test": {
                "Name": "test-endpoint",
                "EndpointID": "579a4c24090300d10dfef7303607f35828b2b82c51e92f917e0bd96f6970407c",
                "MacAddress": "02:42:0a:00:64:04",
                "IPv4Address": "10.0.100.4/24",
                "IPv6Address": "fdf4:dd75:b5d5::2/64"
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097",
            "encrypted": ""
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "1172b2b28c9f",
                "IP": "10.0.2.15"
            }
        ]
    }
]
```

---

And this brings us back to https://github.com/moby/moby/issues/48116#issue-2387004816

**Comment by benz0li** [comment] 2024-07-03 14:22
One difference pops out:

* v26: `"Options": { "com.docker.network.driver.overlay.vxlanid_list": "4097,4098" }`
* v27: `"Options": { "com.docker.network.driver.overlay.vxlanid_list": "4097" }`

**Comment by akerouanton** [comment] 2024-07-04 13:24
Yeah, looks like I was wrong on what's the output of `docker network inspect`. I'm taking a look but I can't identify the root cause yet, and I might have found other bugs in the process.

**Comment by akerouanton** [comment] 2024-07-08 16:21
I'm still somewhat confused by this issue... I tried to play a bit with your repro and found a whole can of worms!

Swarm pretends it doesn't support IPv6 (see `(*cnmNetworkAllocator).allocateDriverState()`), but the check used to enforce that rely on a field that's never written. If you try to create an IPv6-only network, it will fail (ie. the leader will fail to make the IPAM allocation, leading to moby/moby#48137 and moby/moby#43615). But if I run your repro, no error is raised.

```console
# The following happens on both v26.1.0 and v27.0.3.
$ docker network create \
  --driver overlay \
  --ipv6 \
  --opt encrypted \
  --subnet "fd14:8656:a32e:100::/64" \
  --attachable test-v6only
jay2gmvmy14sayf1oddtqpw40

$ docker run --rm -it --network test-v6only alpine /bin/true
docker: Error response from daemon: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded.
```

If you try to put your network definition into a Compose file, it'll fail. I guess that's why you're defining it externally. That's because the compose file format used by `docker stack` doesn't support `enable_ipv6` (since Swarm isn't supposed to support IPv6 networks).

On v26.1.0, if I make the `test` network attachable and then run the loop below, I see four scenarios:

1. sometimes it works;
2. sometimes it produces the same error as above (ie. `context deadline exceeded`);
3. from time to time it produces an `Address already in use` error, which makes the network undeletable (eg. `network 1857f8avpfp7x04vfy0oso6nl is in use by task olpfj4yoofhyy8bxyo7tmjqtb`);
4. concurrency issue arise because of the tight loop -- `Error response from daemon: network with name test already exists` on `network create`, and then `network test not found` on subsequent `docker run` and `docker network rm`

AFAICT all these issues except the last one are related to the lack of proper IPv6 support.

```console
$ for i in $(seq 1 20); do
    echo "Attempt #${i}..."
    docker network create \
        --driver overlay \
        --ipv6 \
        --opt encrypted \
        --subnet "10.0.100.0/24" \
        --subnet "fd14:8656:a32e:100::/64" \
        --attachable test
    docker run --rm -it --network test alpine /bin/true
    docker network rm test
    echo ""
done
```

The `Address already in use` error can also be observed with `docker stack deploy` (on both v26.1.0 and v27.0.3 once patched), but it seems to not make the network undeletable for some reasons. Also, this error isn't as dramatic in that case as a simple `docker run`, since Swarm has a retry loop that will mitigate it.

Then, if I create a Swarm stack like yours, but with 4 replicas spread across two nodes, here's what I observe:

- There's no AAAA records created for that service and its tasks
- Cross-node communication isn't possible because the same IPv6 addresses are assigned to tasks scheduled on both nodes. If I scale that service to an odd number to make sure there's a task with a unique IP address across the cluster, I can't ping it because the overlay mesh doesn't support IPv6.

As for why this regression happen, I tracked it down to these two commits made in moby/moby#47727:

- https://github.com/moby/moby/pull/47727/commits/37a81cd04dcdf60f40cce2fa09498cc23172625c
- https://github.com/moby/moby/pull/47727/commits/115de5ff3d16dbec510923e166950556071693ee

The first commit splits both v4 and v6 address spaces. The 2nd commit introduces `PoolRequest` which now has a bool field `V6`. The PoolRequest built by `cnmallocator` never sets this field, which leads to the v6 subnet allocation being made from the v4 address space -- that's what makes it fail.

While the patch for this issue is rather simple, I start to question whether it's even worth fixing it since the overlay driver has no proper support for IPv6. As demonstrated here, many things are broken.

I think it'd be better to barf out early during network creation if a static IPv6 subnet is passed. And then lift that restriction when proper IPv6 support is implemented.

I'll bring that issue tomorrow during our weekly libnet maintainers call and see what others think.

**Comment by benz0li** [comment] 2024-07-08 20:52
I have been running a single-node docker swarm with dual-stack networks for years now.

For further information, see [Docker swarm + IPv6 + nftables](https://github.com/b-data/docker-swarm-ipv6-nftables). What this project is about:

*  nftables
*  Single-node docker swarm
*  Docker host: Public IPv4/IPv6 address
*  Docker networks: Private IPv4/IPv6 addresses only
*  Docker containers: Ability to connect to the internet using IPv6

What this project is **not** about:

*  IPv6 only
*  Multi-node docker swarm
*  Docker host: IPv6 Prefix Delegation (PD)
*  Docker networks: Using delegated public IPv6 addresses
*  Docker containers: Service deployment using delegated public IPv6 addresses

**Comment by benz0li** [comment] 2024-07-08 21:03
> * There's no AAAA records created for that service and its tasks

Yes. DNS resolution does **not** work on IPv6 networks; IMHO neither for `bridge` nor `overlay` networks.

**Comment by akerouanton** [comment] 2024-07-09 20:17
We discussed this issue with other maintainers today and we agree that it's _not_ a regression. The fact that static IPv6 subnet allocations were previously working was an unfortunate mistake.

Since the overlay driver doesn't behave correctly with such allocation (ie. no AAAA records, no cross-node communications), there's no point in using that driver specifically. You should instead attach your containers to a bridge network with that same subnet configured, in addition to your existing overlay network.

I'll close this ticket but feel free to continue the discussion.

**Closed by akerouanton** 2024-07-09 20:17 UTC
Labels: status/more-info-needed, kind/bug, area/networking, area/swarm, area/networking/ipv6, area/networking/d/overlay, version/27.0

**Comment by benz0li** [comment] 2024-07-12 08:53
> We discussed this issue with other maintainers today and we agree that it's _not_ a regression. The fact that static IPv6 subnet allocations were previously working was an unfortunate mistake.

🆗

> Since the overlay driver doesn't behave correctly with such allocation (ie. no AAAA records, no cross-node communications), there's no point in using that driver specifically. You should instead attach your containers to a bridge network with that same subnet configured, in addition to your existing overlay network.
> 
> I'll close this ticket but feel free to continue the discussion.

One last question regarding v27: Why does

```bash
docker network create \
  --driver overlay \
  --ipv6 \
  --opt encrypted \
  --subnet "10.0.100.0/24" \
  test
```

work – which successfully allocates a (random?) IPv6 subnetwork (as demonstrated in https://github.com/moby/moby/issues/48116#issuecomment-2206165794) – while

```bash
docker network create \
  --driver overlay \
  --ipv6 \
  --opt encrypted \
  --subnet "10.0.100.0/24" \
  --subnet "fdf4:dd75:b5d5::/64" \
  test
```

does not?

I do not depend on static IPv6 subnet allocation. But I find it rather odd that `--ipv6` without defining an IPv6 `--subnet` works while `--ipv6` with defining a static IPv6 `--subnet` does not.
