### ISSUE TITLE
Could not run docker container [operation not supported]

### ISSUE THREAD

**Issue by montygyanchandani** [moby/moby#35820] opened 2017-12-18 11:50 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
I am trying to run docker on Redhat Enterprise VM (In openstack) 
Host and VM  both are on Redhat Enterprice with same kernel version (3.10.0) 

Description:    Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:        7.2(x86_64)
Codename:       Maipo
Kernel version : 3.10.0

Due to limitaions in setup, i could only run docker daemon as binary.
I downloaded docker CE binary (17.09.0) 
https://docs.docker.com/engine/installation/linux/docker-ce/binaries/#install-static-binaries

**Able to Run the docker daemon successfully** 

```
root@test:/home/test>dockerd -D &
 WARN[2017-12-18T11:34:17.444067032Z] could not change group /var/run/docker.sock to docker: group docker not found
DEBU[2017-12-18T11:34:17.444174894Z] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[2017-12-18T11:34:17.445459714Z] libcontainerd: new containerd process, pid: 4082
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=2 memory=16041 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock
DEBU[2017-12-18T11:34:17.950883240Z] libcontainerd: containerd health check returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
WARN[2017-12-18T11:34:18.448939885Z] failed to rename /var/lib/docker/tmp for background deletion: rename /var/lib/docker/tmp /var/lib/docker/tmp-old: no such file or directory. Deleting synchronously
DEBU[2017-12-18T11:34:18.449760435Z] Using default logging driver json-file
DEBU[2017-12-18T11:34:18.449817320Z] Golang's threads limit set to 113940
DEBU[2017-12-18T11:34:18.454108860Z] [zfs] zfs command is not available: exec: "zfs": executable file not found in $PATH
DEBU[2017-12-18T11:34:18.461867662Z] Using graph driver overlay
DEBU[2017-12-18T11:34:18.463109040Z] Max Concurrent Downloads: 3
DEBU[2017-12-18T11:34:18.463157240Z] Max Concurrent Uploads: 5
INFO[2017-12-18T11:34:18.500288890Z] Graph migration to content-addressability took 0.00 seconds
WARN[2017-12-18T11:34:18.500640292Z] mountpoint for pids not found
INFO[2017-12-18T11:34:18.500964089Z] Loading containers: start.
DEBU[2017-12-18T11:34:18.501037843Z] Option Experimental: false
DEBU[2017-12-18T11:34:18.501061007Z] Option DefaultDriver: bridge
DEBU[2017-12-18T11:34:18.501084051Z] Option DefaultNetwork: bridge
DEBU[2017-12-18T11:34:18.501096799Z] Network Control Plane MTU: 1500
WARN[2017-12-18T11:34:18.503308531Z] Running modprobe nf_nat failed with message: ``, error: exit status 1
WARN[2017-12-18T11:34:18.504619765Z] Running modprobe xt_conntrack failed with message: ``, error: exit status 1
DEBU[2017-12-18T11:34:18.509739699Z] /usr/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
-----[ Ip tables ouput ] ---------
INFO[2017-12-18T11:34:18.572235875Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
DEBU[2017-12-18T11:34:18.572284977Z] Allocating IPv4 pools for network bridge (1c6fe6bf92abaaa8dfab18b89daa42f3b6fefcebe14f6624d2d95e01f28f03c9)
DEBU[2017-12-18T11:34:18.572297271Z] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false)
DEBU[2017-12-18T11:34:18.572394058Z] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[RequestAddressType:com.docker.network.gateway])
DEBU[2017-12-18T11:34:18.577722164Z] Did not find any interface with name docker0: Link not found
DEBU[2017-12-18T11:34:18.578648447Z] Setting bridge mac address to 02:42:d9:de:1a:0b
INFO[2017-12-18T11:34:18.610423656Z] Loading containers: done.
INFO[2017-12-18T11:34:18.628547189Z] Docker daemon                                 commit=afdb6d4 graphdriver(s)=overlay version=17.09.0-ce
INFO[2017-12-18T11:34:18.628919237Z] Daemon has completed initialization
INFO[2017-12-18T11:34:18.644721019Z] API listen on /var/run/docker.sock
```

**But could not run docker container** 

```
root@test:/home/test> docker run hello-world
DEBU[2017-12-18T11:36:41.528383793Z] Calling GET /_ping
DEBU[2017-12-18T11:36:41.530244947Z] Calling POST /v1.32/containers/create
DEBU[2017-12-18T11:36:41.530524849Z] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":[],"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","DeviceCgroupRules":null,"Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IOMaximumBandwidth":0,"IOMaximumIOps":0,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NanoCpus":0,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{},"WorkingDir":""}
DEBU[2017-12-18T11:36:41.534335012Z] FIXME: Got an API for which error does not match any expected type!!!: operation not supported  error_type=syscall.Errno module=api
ERRO[2017-12-18T11:36:41.535068458Z] Handler for POST /v1.32/containers/create returned error: operation not supported
DEBU[2017-12-18T11:36:41.535113348Z] FIXME: Got an API for which error does not match any expected type!!!: operation not supported  error_type=syscall.Errno module=api
docker: Error response from daemon: operation not supported.
See 'docker run --help'.
```

**Steps to reproduce the issue:**
Always

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@test:/home/test> docker version
DEBU[2017-12-18T11:37:19.296948749Z] Calling GET /_ping
DEBU[2017-12-18T11:37:19.297588200Z] Calling GET /v1.32/version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
root@test:/home/test> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.67GiB
Name:test.novalocal
ID: HBJN:4AVX:6SZU:TIWD:ORU6:WZSO:GALO:MM5Z:4BM2:C2GN:VUOM:OADA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
**output for check-config.sh**
```
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled
- CONFIG_IP_NF_NAT: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
    (cgroup swap accounting is currently enabled)
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_NETPRIO_CGROUP: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_IP_VS: enabled
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_RR: enabled
- CONFIG_EXT3_FS: enabled
- CONFIG_EXT3_FS_XATTR: enabled
- CONFIG_EXT3_FS_POSIX_ACL: enabled
- CONFIG_EXT3_FS_SECURITY: enabled
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
 - "overlay":
    - CONFIG_VXLAN: enabled
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: enabled
    - CONFIG_DUMMY: enabled
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: enabled
    - CONFIG_NF_CONNTRACK_FTP: enabled
    - CONFIG_NF_NAT_TFTP: enabled
    - CONFIG_NF_CONNTRACK_TFTP: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: missing
    - CONFIG_DM_THIN_PROVISIONING: missing
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```

**Comment by thaJeztah** [comment] 2017-12-18 12:24
I'm not able to reproduce this on a CentOS 7.4 machine; installed the Docker static binaries for 17.09.0, started the daemon, and I'm able to run containers; here's the output of `docker version` and `docker info`;

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.796GiB
Name: centos-2gb-ams3-01
ID: U53R:QGQS:UMZL:QFLC:AVLW:LXGN:YH4P:O43Z:RQB2:BIMO:3YTL:ROKQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 26
 System Time: 2017-12-18T12:15:18.206878313Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Some things worth noting;

- Docker 17.09.0 is not the latest 17.09 release; a 17.09.1 patch release is available, and contains various bug fixes.
- Your output shows kernel `3.10.0`; is this an official Red Hat kernel? What version of the kernel is this (especially the part _following_ 3.10.0 may be of interest, because a "vanilla" 3.10 kernel is missing a lot of functionality that's backported by Red Hat)
- Docker CE is not officially supported on RHEL, only on CentOS (although generally that should be exchangeable); however, the packages are only supported on the _current_ (7.4) version and related kernel.

> Due to limitaions in setup, i could only run docker daemon as binary. I downloaded docker CE binary (17.09.0)

If possible, I would definitely recommend installing the dynamically linked packages; if you need to install in a system without internet access, perhaps downloading the RPM

**Comment by thaJeztah** [comment] 2017-12-18 12:32
Based on the error message;

```
FIXME: Got an API for which error does not match any expected type!!!: operation not supported  error_type=syscall.Errno module=api
```

This may be related to `overlay` on an older kernel; if you start the daemon with a different storage driver, does it work successfully? e.g. when manually starting with vfs;

```
dockerd -D  --storage-driver=vfs
```

Note that `vfs` is _not recommended_ for anything other than debugging, however the `devicemapper` driver (which could be an alternative) cannot be used with the static binaries.

**Comment by montygyanchandani** [comment] 2017-12-19 03:17
Hi Mr Sebastiaan

Thanks for help.

from above command (dockerd  --storage-driver=vfs)
I could run the docker container 

root@test:/home/test> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

Mr Sebastiaan,

As suggested we cannot use VFS, so to solve this problem - (overlay on older kernel)
will this be solved with installing docker with RPM  or there is no other option other than kernel upgrade

Thanks.

**Comment by thaJeztah** [comment] 2017-12-19 16:33
Devicemapper should be able to work on these older kernel versions (that was the reason it's been the default for RHEL/CentOS in the past, because it was the only driver that could work on these old kernels).

Let me close this issue, because this is not really a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-12-19 16:33 UTC
Labels: area/daemon, status/more-info-needed, version/17.09
