### ISSUE TITLE
rpc error: code = 14 desc = grpc: the connection is unavailable

### ISSUE THREAD

**Issue by walteryoung** [moby/moby#34944] opened 2017-09-22 18:32 UTC
[docker.zip](https://github.com/moby/moby/files/1325480/docker.zip)

**Description**

During load testing, this error "grpc: the connection is unavailable" starts happening and fully prevents use of docker on the machine.
Specifically creating, starting, or deleting containers. 'docker ps' still lists containers but container manipulation fails.

**Steps to reproduce the issue:**
1. Run docker on AWS:
$ cat /etc/system-release
Amazon Linux AMI release 2017.03
2. Run a service using docker that creates and deletes containers at a relatively high volume. 
3. Attempt to create, start, or delete containers.

**Describe the results you received:**
Once the error occurs, docker is unable to create, start, or delete containers. Examples of the problems from docker logs:
```
time="2017-09-21T17:46:28.465619111Z" level=debug msg="libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable" 
time="2017-09-21T17:46:28.764166769Z" level=error msg="stream copy error: reading from a closed fifo\ngithub.com/docker/docker/vendor/github.com/tonistiigi/fifo.(*fifo).Read\n\t/builddir/build/BUILD/docker-17.03.2-ce/_build/src/github.com/docker/docker/vendor/github.com/tonistiigi/fifo/fifo.go:142\nbufio.(*Reader).fill\n\t/usr/lib/golang/src/bufio/bufio.go:97\nbufio.(*Reader).WriteTo\n\t/usr/lib/golang/src/bufio/bufio.go:472\nio.copyBuffer\n\t/usr/lib/golang/src/io/io.go:380\nio.Copy\n\t/usr/lib/golang/src/io/io.go:360\ngithub.com/docker/docker/pkg/pools.Copy\n\t/builddir/build/BUILD/docker-17.03.2-ce/_build/src/github.com/docker/docker/pkg/pools/pools.go:60\ngithub.com/docker/docker/container/stream.(*Config).CopyToPipe.func1.1\n\t/builddir/build/BUILD/docker-17.03.2-ce/_build/src/github.com/docker/docker/container/stream/streams.go:119\nruntime.goexit\n\t/usr/lib/golang/src/runtime/asm_amd64.s:2086" 
time="2017-09-21T17:46:28.764217695Z" level=error msg="Create container failed with error: grpc: the connection is unavailable" 
time="2017-09-21T17:46:28.840611360Z" level=error msg="Handler for POST /containers/7b17b740b546841710ebd400f2780272857998fc45eee56666a21d8f85d40749/start returned error: grpc: the connection is unavailable" 
time="2017-09-21T17:47:46.024940701Z" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing" 
time="2017-09-21T17:47:46.465561166Z" level=debug msg="libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable" 
time="2017-09-21T18:19:10.743182655Z" level=error msg="containerd: get exit status" error="containerd: process has not exited" id=b541757169067a72c3bf7d927c9cbd065f87c7d68826883e75374c74ab4ada5a pid=e5c4877186dd2de002e028e5423c04ae6c2b61c19f326c274608fd6be1ce23d4 systemPid=4973 
time="2017-09-21T18:53:26.786026415Z" level=error msg="Handler for DELETE /containers/deea848005c546146a16bf3cbde63d67f24e6943f6b8ba57a073aefbc8f1c946 returned error: Could not kill running container deea848005c546146a16bf3cbde63d67f24e6943f6b8ba57a073aefbc8f1c946, cannot remove - Cannot kill container deea848005c546146a16bf3cbde63d67f24e6943f6b8ba57a073aefbc8f1c946: rpc error: code = 14 desc = grpc: the connection is unavailable" 
```

**Describe the results you expected:**
Docker to continue working. Ability to manipulate containers. Docker to recover from an error state.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue seems to happen most commonly in a high-stress situation (We never experienced it until starting our load testing for our service.)

**Output of `docker version`:**
```
$ sudo docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64
 Experimental: false**Output of `docker info`:**
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
$ cat /etc/system-release
Amazon Linux AMI release 2017.03

The symptoms seem very similar to this issue: https://github.com/moby/moby/issues/31074#issuecomment-286180631
But @thaJeztah claimed the issue would be fixed in 17.03.1 and we are running 17.03.2ce.
I attached the raw docker logs from the machine that had the failure.

**Comment by thaJeztah** [comment] 2017-09-25 09:08
Can you;

- provide the output of `docker info ` as well?
- if possible, run the daemon in debug mode to see if the additional logging provides more information?
- check the system logs to see if the system ran out of memory?

The `the connection is unavailable` error message is quite generic, and basically means that the docker daemon was not able to communicate with containerd. This can have several causes, one of which (and likely if you're stress-testing), is that the host ran out of of resources (memory?), resulting in the kernel OOM-killing processes.

Please be aware that there are no official packages for Amazon Linux (those packages are built by Amazon), and docker is not tested on that distribution. Also, Docker 17.03 CE (Community Edition) reached end of life, thus won't receive any updates (docker 17.06 CE is still supported, but will soon be replaced with 17.09)

**Comment by samsun387** [comment] 2017-09-28 17:44
Looks like it's the same issue as https://github.com/moby/moby/issues/34377 . I ran into the exact issue in 17.03 and after upgraded to 17.06, it happens less frequent but I still hit it maybe once a week. 
I am running 40 containers per machine and each machine has 64G of memory. I also limit the the memory to 1000M per container but it would still happen

**Comment by emexelem** [comment] 2017-09-29 21:21
I'm having the same issue when running the official gitlab-ce image on an Azure D2S_V3 instance with Ubuntu 16.04.
After few hours, the container is reported as unhealthy (though gitlab is still running fine) and a docker exec on this container returns the error
`docker rpc error: code = 14 desc = grpc: the connection is unavailable`

Here's my docker-compose file : https://gist.github.com/emexelem/d56936aa474cbe4d161a434437324b5b

```
root@gitlab:~# docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS                   PORTS                                                            NAMES
3a42b6352fa5        gitlab/gitlab-ce:latest   "/assets/wrapper"   5 hours ago         Up 5 hours (unhealthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:2222->22/tcp   gitlab
root@gitlab:~# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@gitlab:~# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: 9048e5e50717ea4497b757314bad98ea3763c145)
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.0-1011-azure
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.777GiB
Name: gitlab
ID: LBY4:64OI:ED6F:PCWP:JTK6:73YH:CLAP:RZM5:RXVY:4NWI:5YVO:ECGO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

root@gitlab:~# journalctl
...
Sep 29 19:17:01 gitlab CRON[32936]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 29 19:17:01 gitlab CRON[32937]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Sep 29 19:17:01 gitlab CRON[32936]: pam_unix(cron:session): session closed for user root
Sep 29 19:17:23 gitlab python3[1234]: 2017/09/29 19:17:23.966877 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
Sep 29 19:18:20 gitlab dockerd[78958]: time="2017-09-29T19:18:20.660957686Z" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is c
Sep 29 19:18:20 gitlab dockerd[78958]: time="2017-09-29T19:18:20.661092187Z" level=error msg="Handler for GET /containers/3a42b6352fa57e4e2e1c575b303412a824b5da43007460beac6d2c18465b2187/top r
Sep 29 19:18:33 gitlab dockerd[78958]: time="2017-09-29T19:18:33.123195380Z" level=warning msg="Health check for container 3a42b6352fa57e4e2e1c575b303412a824b5da43007460beac6d2c18465b2187 erro
Sep 29 19:18:36 gitlab dockerd[78958]: time="2017-09-29T19:18:36.127686039Z" level=error msg="collecting stats for 3a42b6352fa57e4e2e1c575b303412a824b5da43007460beac6d2c18465b2187: rpc error:
Sep 29 19:18:37 gitlab dockerd[78958]: time="2017-09-29T19:18:37.127673780Z" level=error msg="collecting stats for 3a42b6352fa57e4e2e1c575b303412a824b5da43007460beac6d2c18465b2187: rpc error:

```

**Comment by emexelem** [comment] 2017-10-03 14:21
I've used latest install notes to upgrade docker engine to latest stable version. Now it's the docker daemon that becomes unresponsive, though the application running in the container (gitlab) is still running fine.
It might not be related but i have another service written in Go that is failing on this instance too, Telegraf, because of a 'fatal error: MHeap_AllocLocked - MSpan not free'. [I've opened this case in Telegraf project](https://github.com/influxdata/telegraf/issues/3299). This service is running at the host level, not in a Docker container.
To be noted that i have 2 other instances with a similar setup (but running different apps in Docker containers) and the problem with docker and telegraf can only be reproduced on this particular instance.

```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

ps uxf (truncated)
root      75017  0.0  0.0 117280  6592 ?        Sl   Oct02   0:00 docker-runc events --stats 68bb7151f16fab281c91c6c1e80be114d38259ba252c9c3ba841e7a2b3f67b40
root       5449  100  0.0 421904  5260 ?        Sl   Oct02 1243:26 docker-containerd-shim 68bb7151f16fab281c91c6c1e80be114d38259ba252c9c3ba841e7a2b3f67b40 /var/run/docker/libcontainerd/68bb7151f16fab281c91c6c1e80be114d3
root     103046  0.1  0.3 680712 63976 ?        Ssl  Oct02   1:08 /usr/bin/dockerd -H fd://
root     103461  0.0  0.0 108216  2792 ?        Sl   Oct02   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 443 -container-ip 172.18.0.2 -container-port 443
root     103472  0.0  0.0  59072  2892 ?        Sl   Oct02   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.2 -container-port 80
root     103485  0.0  0.0 108216  2888 ?        Sl   Oct02   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 2222 -container-ip 172.18.0.2 -container-port 22
root      52653  0.0  0.1 449832 17424 ?        Ssl  02:33   0:06  \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/
root      57284  0.0  0.0 127840  6688 ?        Sl   02:49   0:00      \_ docker-runc events --stats 68bb7151f16fab281c91c6c1e80be114d38259ba252c9c3ba841e7a2b3f67b40
root     103490  0.0  0.0 299028  7084 ?        Sl   Oct02   0:03 docker-containerd-shim 68bb7151f16fab281c91c6c1e80be114d38259ba252c9c3ba841e7a2b3f67b40 /var/run/docker/libcontainerd/68bb7151f16fab281c91c6c1e80be114d38
root     103511  0.0  0.0  18060  2932 ?        Ss   Oct02   0:00  \_ /bin/bash /assets/wrapper
root     103615  0.0  0.0   4400  1104 ?        S    Oct02   0:00      \_ runsvdir -P /opt/gitlab/service log: ............................................................................................................
root     103633  0.0  0.0   4248   656 ?        Ss   Oct02   0:00      |   \_ runsv sshd
root     103634  0.0  0.0   4392   716 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/sshd
root     103635  0.0  0.0  65524  5388 ?        S    Oct02   0:00      |   |   \_ /usr/sbin/sshd -D -f /assets/sshd_config -e
root     104007  0.0  0.0   4248   664 ?        Ss   Oct02   0:00      |   \_ runsv nginx
root     104021  0.0  0.0   4392   684 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/nginx
root     104023  0.0  0.0  53052  6024 ?        Ss   Oct02   0:00      |   |   \_ nginx: master process /opt/gitlab/embedded/sbin/nginx -p /var/opt/gitlab/nginx
root     104008  0.0  0.0   4248   648 ?        Ss   Oct02   0:00      |   \_ runsv prometheus
root     104045  0.0  0.0   4392   760 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/prometheus
root     104009  0.0  0.0   4248   656 ?        Ss   Oct02   0:00      |   \_ runsv redis
root     104020  0.0  0.0   4392   812 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/redis
root     104010  0.0  0.0   4248   760 ?        Ss   Oct02   0:00      |   \_ runsv sidekiq
root     104053  0.0  0.0   4392   680 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/sidekiq
root     104011  0.0  0.0   4248   644 ?        Ss   Oct02   0:00      |   \_ runsv logrotate
root     104038  0.0  0.0   4392   824 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/logrotate
root      31647  0.0  0.0   4512   788 ?        Ss   11:49   0:00      |   |   \_ /bin/sh /opt/gitlab/embedded/bin/gitlab-logrotate-wrapper
root      33861  0.0  0.0   4384   712 ?        S    11:59   0:00      |   |       \_ sleep 3000
root     104012  0.0  0.0   4248   672 ?        Ss   Oct02   0:00      |   \_ runsv postgresql
root     104030  0.0  0.0   4392   656 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/postgresql
root     104013  0.0  0.0   4248   660 ?        Ss   Oct02   0:00      |   \_ runsv gitaly
root     104036  0.0  0.0   4392   664 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/gitaly
root     104014  0.0  0.0   4248   672 ?        Ss   Oct02   0:00      |   \_ runsv unicorn
root     104040  0.0  0.0   4392   672 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/unicorn
root     104015  0.0  0.0   4248   680 ?        Ss   Oct02   0:00      |   \_ runsv redis-exporter
root     104024  0.0  0.0   4392   772 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/redis-exporter
root     104016  0.0  0.0   4248   752 ?        Ss   Oct02   0:00      |   \_ runsv postgres-exporter
root     104027  0.0  0.0   4392   684 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/postgres-exporter
root     104017  0.0  0.0   4248   660 ?        Ss   Oct02   0:00      |   \_ runsv gitlab-workhorse
root     104026  0.0  0.0   4392   812 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/gitlab-workhorse
root     104018  0.0  0.0   4248   664 ?        Ss   Oct02   0:00      |   \_ runsv node-exporter
root     104034  0.0  0.0   4392   820 ?        S    Oct02   0:00      |   |   \_ svlogd -tt /var/log/gitlab/node-exporter
root     104019  0.0  0.0   4248   644 ?        Ss   Oct02   0:00      |   \_ runsv gitlab-monitor
root     104032  0.0  0.0   4392   660 ?        S    Oct02   0:00      |       \_ svlogd -tt /var/log/gitlab/gitlab-monitor
root     103992  0.0  0.0  18044  2784 ?        S    Oct02   0:00      \_ /bin/bash /opt/gitlab/bin/gitlab-ctl tail
root     103993  0.0  0.1  96196 22820 ?        Sl   Oct02   0:00          \_ /opt/gitlab/embedded/bin/ruby /opt/gitlab/embedded/bin/omnibus-ctl gitlab /opt/gitlab/embedded/service/omnibus-ctl* tail
root     103998  0.0  0.0   4512   752 ?        S    Oct02   0:00              \_ sh -c find /var/log/gitlab -type f -not -path */sasl/* | grep -E -v '(config|lock|@|gzip|tgz|gz)' | xargs tail --follow=name --retry
root     104001  0.0  0.0   4684  1316 ?        S    Oct02   0:00                  \_ xargs tail --follow=name --retry
root     104002  0.0  0.0   4416   740 ?        S    Oct02   0:00                      \_ tail --follow=name --retry /var/log/gitlab/postgres-exporter/current /var/log/gitlab/gitlab-rails/api_json.log /var/log/gitlab/gi
root      33918  0.0  0.0 129504  7008 ?        Sl   01:19   0:00 docker-runc events --stats 68bb7151f16fab281c91c6c1e80be114d38259ba252c9c3ba841e7a2b3f67b40
root      43705  0.0  0.0 264676  4992 ?        Sl   02:00   0:00 docker-containerd-shim 68bb7151f16fab281c91c6c1e80be114d38259ba252c9c3ba841e7a2b3f67b40 /var/run/docker/libcontainerd/68bb7151f16fab281c91c6c1e80be114d38

first report of the failure in journalctl
Oct 02 08:15:51 gitlab dockerd[1440]: time="2017-10-02T08:15:51.554782745Z" level=info msg="containerd: 68bb7151f16fab281c91c6c1e80be114d38259ba252c9c3ba841e7a2b3f67b40:0cb2c68204058e4eb5d73f7dce6d5b5f762af0b4b5420e530c7b1d57d15ce15e (pid 10623) has become an orphan, killing it"
```

[Additional entries from journalctl in gist](https://gist.github.com/emexelem/adda63904bf131a8ca5dd15759166ef8)

**Comment by thaJeztah** [comment] 2017-10-03 15:45
If I understand correctly, the gitlab container is logging to a file (not stdout); Is the `/var/log` directory of the container marked as a volume or bind-mount?

**Comment by emexelem** [comment] 2017-10-03 16:09
Here's the docker compose file: https://gist.github.com/emexelem/d56936aa474cbe4d161a434437324b5b

```
volumes:
      - ${DOCKER_VOLUMES_BASE_FOLDER}/gitlab/config:/etc/gitlab
      - ${DOCKER_VOLUMES_BASE_FOLDER}/gitlab/logs:/var/log/gitlab
      - ${DOCKER_VOLUMES_BASE_FOLDER}/gitlab/data:/var/opt/gitlab
```

**Comment by dqminh** [comment] 2018-02-09 17:17
@thaJeztah also seeing this on some hosts running 17.03 in our clusters. Basically containerd was shutdown for some reason, but docker daemon never able to bring it back. There was also no logs in docker daemon ( we run at info level )

```
> sudo strace -fp $(pidof dockerd) -e trace=clone,execve,kill -s 1024

[pid 30797] execve("/usr/bin/docker-containerd", ["docker-containerd", "-l", "unix:///var/run/docker/libcontainerd/docker-containerd.sock", "--metrics-interval=0", "--start-timeout", "2m", "--state-dir", "/var/run/docker/libcontainerd/containerd", "--shim", "docker-containerd-shim", "--runtime", "docker-runc"], [/* 7 vars */]) = 0
[pid  8920] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8127, si_uid=0} ---
[pid  8920] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8127, si_uid=0} ---
[pid 30797] clone(Process 30798 attached
child_stack=0x7ff2e6fb5fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7ff2e6fb69d0, tls=0x7ff2e6fb6700, child_tidptr=0x7ff2e6fb69d0) = 30798
[pid 30797] clone(Process 30799 attached
child_stack=0x7ff2e67b4fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7ff2e67b59d0, tls=0x7ff2e67b5700, child_tidptr=0x7ff2e67b59d0) = 30799
[pid 30797] clone(Process 30800 attached
child_stack=0x7ff2e5fb3fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7ff2e5fb49d0, tls=0x7ff2e5fb4700, child_tidptr=0x7ff2e5fb49d0) = 30800
[pid 30799] clone(Process 30801 attached
child_stack=0x7ff2e57b2fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7ff2e57b39d0, tls=0x7ff2e57b3700, child_tidptr=0x7ff2e57b39d0) = 30801
[pid 30797] clone(Process 30802 attached
 <unfinished ...>
[pid 30801] clone( <unfinished ...>
[pid 30797] <... clone resumed> child_stack=0x7ff2e4e51fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7ff2e4e529d0, tls=0x7ff2e4e52700, child_tidptr=0x7ff2e4e529d0) = 30802
Process 30803 attached
[pid 30801] <... clone resumed> child_stack=0x7ff2dfffefb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7ff2dffff9d0, tls=0x7ff2dffff700, child_tidptr=0x7ff2dffff9d0) = 30803
[pid 30803] clone(Process 30804 attached
child_stack=0x7ff2df7fdfb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7ff2df7fe9d0, tls=0x7ff2df7fe700, child_tidptr=0x7ff2df7fe9d0) = 30804
[pid 30801] kill(23947, SIG_0)          = 0
[pid 30801] kill(13110, SIG_0)          = 0
[pid 30801] kill(17500, SIG_0)          = 0
[pid 30801] kill(3533, SIG_0)           = 0
[pid 30801] kill(3805, SIG_0)           = 0
[pid 30801] kill(9340, SIG_0)           = 0
[pid 30801] kill(15192, SIG_0)          = 0
[pid 30801] kill(10201, SIG_0)          = 0
[pid 30801] kill(28278, SIG_0)          = 0
[pid 30801] kill(7755, SIG_0)           = 0
[pid 30801] kill(24029, SIG_0)          = 0
[pid 30801] kill(2497, SIG_0)           = 0
[pid 30801] kill(14844, SIG_0)          = 0
[pid 30801] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=30797, si_uid=0} ---
[pid 30801] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_TKILL, si_pid=30797, si_uid=0} ---
[pid 30799] <... futex resumed> )       = ? <unavailable>
[pid 30804] +++ killed by SIGPIPE +++
[pid 30803] +++ killed by SIGPIPE +++
[pid 30802] +++ killed by SIGPIPE +++
[pid 30801] +++ killed by SIGPIPE +++
[pid 30800] +++ killed by SIGPIPE +++
[pid 30799] +++ killed by SIGPIPE +++
[pid 30798] +++ killed by SIGPIPE +++
[pid 30797] +++ killed by SIGPIPE +++
[pid  8920] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=30797, si_uid=0, si_status=SIGPIPE, si_utime=1, si_stime=2} ---
[pid  8169] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8127, si_uid=0} ---
[pid  2590] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8127, si_uid=0} ---
[pid  8334] kill(30797, SIG_0)          = -1 ESRCH (No such process)
[pid  8334] kill(30797, SIG_0)          = -1 ESRCH (No such process)
[pid  8334] clone(Process 31704 attached
child_stack=0, flags=SIGCHLD) = 31704
[pid 31704] execve("/usr/bin/docker-containerd", ["docker-containerd", "-l", "unix:///var/run/docker/libcontainerd/docker-containerd.sock", "--metrics-interval=0", "--start-timeout", "2m", "--state-dir", "/var/run/docker/libcontainerd/containerd", "--shim", "docker-containerd-shim", "--runtime", "docker-runc"], [/* 7 vars */]) = 0
[pid  8334] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8127, si_uid=0} ---
[pid  8334] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8127, si_uid=0} ---
[pid 31704] clone(Process 31726 attached
child_stack=0x7f76dd16ffb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f76dd1709d0, tls=0x7f76dd170700, child_tidptr=0x7f76dd1709d0) = 31726
```

You can see that it keeps executing the docker-containerd binary repeatedly here, but never succeeded, socket is not created locally, only pid is written to the filesystem.

**Comment by thaJeztah** [comment] 2018-02-12 13:33
@dqminh sounds similar to https://github.com/moby/moby/issues/36002 (that was with containerd 1.0.x - haven't tested the same scenario with older releases that still used the 0.2.x version of containerd)

**Comment by dqminh** [comment] 2018-02-26 18:16
@thaJeztah its abit different since `docker-containerd` is not even running in my environment. Will try to upgrade to 17.12.1 once its ready to see if its still happenning since 0.2.x is quite old now.

**Comment by iamtowne** [comment] 2018-07-31 05:26
how to deal with "system ran out of memory" 
I found information about "OOM" from the log of docker
but I did not run out of physical memory

**Comment by thaJeztah** [comment] 2020-03-10 09:37
closing, as this went stale, but feel free to open a new ticket if you're still running into this on a current version of docker

**Closed by thaJeztah** 2020-03-10 09:37 UTC
Labels: area/daemon, area/runtime, status/more-info-needed, version/17.03

**Comment by Boopathiraj** [comment] 2020-04-12 06:41
Same issue I came across. 
There were a connectivity issue between them.  I enabled specific route between the nodes and it works
