### ISSUE TITLE
How do I know the status of the container？

### ISSUE THREAD

**Issue by shenxiang11** [moby/moby#42826] opened 2021-09-07 10:39 UTC
How do I know the status of the container？

Mysql container for example：

mysqld: ready for connections.

**Comment by thaJeztah** [comment] 2021-09-07 11:26
That really depends on the container, so there's not a one-size-fits-all answer to that. You can use some of the solutions provided in https://docs.docker.com/compose/startup-order/ to check if a container is ready, or define a health check for the container that indicates if the container's process is ready to accept connections; https://docs.docker.com/engine/reference/builder/#healthcheck

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-09-07 11:26 UTC
Labels: kind/question
