### ISSUE TITLE
Feature Request: Docker Swarm Mode - Mesh Virtual IP/Host

### ISSUE THREAD

**Issue by patran** [moby/moby#33754] opened 2017-06-21 00:20 UTC
**Current**
Client App -port 8080-> Docker Swarm Manager -port 30000-> Docker Swarm Node -8080-> Application

**Proposal**
Would this be possible? 

Client App -port 8080-> Docker Swarm Manager -port X-> Docker Swarm Node -8080-> Application1
Client App -port 8080-> Docker Swarm Manager -port Y-> Docker Swarm Node -8080-> Application2
Client App -port 8080-> Docker Swarm Manager -port Z-> Docker Swarm Node -8080-> Application3

Outside of docker, on the same Linux host, virtual network interfaces can be used to achieve the same effect given just one physical network interface. 

Application1, Application2, and Application3 would bind to different virtual IP and hence, they can listen to the same port - 8080.

Client apps would connect to the specific virtual IP and port and get to the right application.

**Comment by thaJeztah** [comment] 2017-09-25 22:07
This is currently not possible, and looks like a duplicate of https://github.com/moby/moby/issues/26696. I'll close this one in favour of https://github.com/moby/moby/issues/26696

**Closed by thaJeztah** 2017-09-25 22:07 UTC
Labels: area/networking, area/swarm
