### ISSUE TITLE
Docker Swarm Resource/Memory leak

### ISSUE THREAD

**Issue by jkhongusc** [moby/moby#35826] opened 2017-12-18 18:25 UTC
**Description**

Docker Swarm memory leak using Docker for AWS

Every iteration of "docker stack deploy --compose-file hello.yml hello" and "docker stack rm hello": all masters lose some memory (<100kb) and all nodes running the container lose around 1-2MB of memory. Eventually a node will run out-of-memory; and the out-of-memory node becomes unresponsive. Sometimes ASG terminates node immediately; sometimes it takes ASG time (over 1 hour) to auto-terminate the node. I've run this test on various Docker configurations: 1 master, 3 masters, 1 master and 1 worker, 3 masters and 3 workers.

**Steps to reproduce the issue:**
I have reproduced this out-of-memory in many docker configurations of master/worker combinations. I've used micro instances (500MB RAM) up to large instances (8GB RAM).  Running on master-only configuration with less instance memory runs into out-of-memory condition faster.
1. Create docker compose file - hello.yml:
```
version: '3.0'

services:
  hellotest:
    image: hello-world
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 1
```
2. Create test shell script - test.sh
```
#!/bin/sh
##### globals #####
# how many times to loop through test
LOOPS=1000
 
starttime=`date`
echo start: $starttime
counter=1
while [ $counter -le $LOOPS ]
do
        echo loop number $counter
        # start docker
        cd /home/docker
        echo starting docker: docker stack deploy --compose-file test.yml hello${counter}
        docker stack deploy --compose-file test.yml hello${counter}
        sleep 5
        # stop docker
        echo stopping docker: docker stack rm hello${counter}
        docker stack rm hello${counter}
        sleep 5
        counter=$((counter+1))
done
 
endtime=`date`
```

3. Run shell script:
```
nohup ./test.sh &
```

**Describe the results you received:**

Eventually a node will run out-of-memory.  I have stopped tests prior to out-of-memory condition.  Docker swarm does not release the memory.  I have pruned all docker resources - docker system prune. 
dockerd seems to be the process that consumes (and does not release) the memory

**Describe the results you expected:**

Docker swarm to release memory of unused resources.  I have not seen the memory loss in non-swarm configurations.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time.  I had a collegue run the same tests on a Centos server with a Docker swarm configuration.  Same issue.

**Output of `docker-diagnose`:** 
right before out-of-memory condition

```
$  docker-diagnose
OK hostname=ip-172-31-36-46-us-west-2-compute-internal session=1511636693-K6FsbkUOfNCzcGE9wFIVxru763mUTd7i
OK hostname=ip-172-31-0-211-us-west-2-compute-internal session=1511636693-K6FsbkUOfNCzcGE9wFIVxru763mUTd7i
OK hostname=ip-172-31-21-134-us-west-2-compute-internal session=1511636693-K6FsbkUOfNCzcGE9wFIVxru763mUTd7i
Done requesting diagnostics.
Your diagnostics session ID is 1511636693-K6FsbkUOfNCzcGE9wFIVxru763mUTd7i
Please provide this session ID to the maintainer debugging your issue.
```

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**
Note: different swarm configuration to minimize OOM issue. Using 3 masters and 3 workers (masters never run a container)
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xv9kyc47y7zvb5jcnrnp9halq
 Is Manager: true
 ClusterID: nqjk0ujydp9rpmos2rtc1vfy1
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.31.13.86
 Manager Addresses:
  172.31.13.86:2377
  172.31.21.134:2377
  172.31.36.46:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.854GiB
Name: ip-172-31-13-86.us-west-2.compute.internal
ID: FOQM:QTJS:IIGR:NAMG:FANT:SMVW:KZJ7:QKXH:VCGU:YG2J:H5SR:D3U4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 387
 Goroutines: 524
 System Time: 2017-12-18T18:17:25.606928324Z
 EventsListeners: 0
Username: jkhongusc
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region=us-west-2
 availability_zone=us-west-2a
 instance_type=t2.medium
 node_type=manager
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using Docker for AWS cloudformation template with various Docker swarm configurations: 1 master, 3 masters, 1 master and 1 worker, 3 masters and 3 workers.

 I had a collegue run the same tests on Centos servers with a Docker swarm configuration.  Same issue, dockerd process uses up all system memory till system runs out of memory.

**Comment by thaJeztah** [comment] 2017-12-18 18:34
Just to be sure it's still an issue; Have you been able to test if the issue still reproduces on the latest patch release for 17.09 (17.09.1)?

Also, does the memory go down after some time? (Wondering if memory grows until the Go runtime's garbage collection kicks in)

**Comment by jkhongusc** [comment] 2017-12-18 19:15
> Have you been able to test if the issue still reproduces on the latest patch release for 17.09 (17.09.1)?

Sorry I dont know how to do that.  I run the standard D4AWS template - https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl - In there are pre-set AMIs.  In AWS-> EC2 console I even tried searching for Community AMIs "Moby Linux 17.09" and do not see any 17.09.1 releases.

> Also, does the memory go down after some time? (Wondering if memory grows until the Go runtime's garbage collection kicks in)

I have stopped in the middle of tests many times... up to a 24 hour pause and (system) memory is never released.  I am sure to prune all my docker resources; and this a test system which is only used for swarm testing.  I usually destroy the entire swarm and re-run the CFT to run new swarm tests.

**Comment by thaJeztah** [comment] 2017-12-18 19:30
Ah, yes, forgot that has to be handled in that template for Docker for AWS (perhaps we should have an issue in the https://github.com/docker/for-aws/issues issue tracker as well)

ping @ddebroy as well

**Comment by ddebroy** [comment] 2017-12-18 19:51
cc @FrenchBen. It looks like https://download.docker.com/aws/stable/17.09.1/Docker.tmpl is not there.

**Comment by dcharbonnier** [comment] 2018-01-25 22:04
Isn't this a duplicate of #35261 ?

**Comment by FrenchBen** [comment] 2018-01-25 22:15
@dcharbonnier looks like it, yes. @thaJeztah WDYT?

**Comment by thaJeztah** [comment] 2018-01-26 00:10
@FrenchBen looks like the fix for that is in Docker CE 17.12 (but not in 17.09.0 / 17.09.1)

**Comment by crazybaud** [comment] 2018-01-30 16:46
Like it seems unadvised to upgrade to 17.12 (#35933). Did you find a better solution than a dirty nightly restart ?

**Comment by thaJeztah** [comment] 2018-01-30 21:19
@crazybaud FWIW, the runc issue mentioned in https://github.com/moby/moby/issues/35933 will affect every version of docker; it's a bug in runc that has been in every version of runc, but is triggered by the recent patches for [Meltdown and Spectre](https://meltdownattack.com)

**Comment by sorenhansendk** [comment] 2018-01-31 13:20
@thaJeztah Will the release of Docker CE (v18.02.0-ce-rc1) help to fix the issue with runc? I can see in the changelog, that something with the **start** and **exec** command have been fixed: https://github.com/docker/docker-ce/releases/tag/v18.02.0-ce-rc1

**Comment by thaJeztah** [comment] 2018-02-01 04:07
@sorenhansendk yes, Docker 18.02.0-ce has an updated version of runc that should address the issue (https://github.com/moby/moby/pull/36097)

**Comment by sorenhansendk** [comment] 2018-02-01 07:37
@thaJeztah Ok. Will that also affect the command to stop containers?
My swarm sometimes don't shutting down old containers, if we deploy new verisons

**Comment by thaJeztah** [comment] 2023-09-17 19:46
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 19:46 UTC
Labels: area/swarm, version/17.09
