### ISSUE TITLE
can't remove container

### ISSUE THREAD

**Issue by yiv** [moby/moby#35164] opened 2017-10-11 09:45 UTC
I follow the official instruction to install the docker, [Get Docker CE for Ubuntu](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository)
this is my docker version
```
ubuntu@tpserver1:/data/docker/compose$ sudo docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker-compose.yml
```
version: '3'
services:
cockroach1:
    image: cockroachdb/cockroach:v1.0.6
    hostname: cockroach1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - /data/docker/data/cockroach/roach1:/cockroach/cockroach-data
    command: start --insecure
    networks:
      - cocknetwork
    restart: always
  cockroach2:
    image: cockroachdb/cockroach:v1.0.6
    hostname: cockroach2
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - /data/docker/data/cockroach/roach2:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always
  cockroach3:
    image: cockroachdb/cockroach:v1.0.6
    hostname: cockroach3
    ports:
      - "26259:26257"
      - "8082:8080"
    volumes:
      - /data/docker/data/cockroach/roach3:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always
networks:
  cocknetwork:
    driver: bridge
```

cockroach2 is down, but its status is still up, I can't stop it or remove it, I must restart the docker service to do so.

```
ubuntu@tpserver1:/data/docker/compose$ sudo docker exec -it compose_cockroach2_1 /bin/sh
rpc error: code = 2 desc = containerd: container not found

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,   

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose stop cockroach2
Stopping compose_cockroach2_1 ... done

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose rm cockroach2
No stopped containers

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,  
```

after asked help from gitter, Sheogorath @SISheogorath suggest I put stop and rm command in one line , I try like below, still not work
```
ubuntu@tpserver1:/data/docker/compose$ sudo docker stop compose_cockroach2_1 && sudo docker rm compose_cockroach2_1
compose_cockroach2_1
Error response from daemon: You cannot remove a running container 5b6550b3ec9bff0be8eea857de9a954b6d67e75f1f1fce483468b89e9b943270. Stop the container before attempting removal or force remove

ubuntu@tpserver1:/data/docker/compose$ sudo docker stop compose_cockroach2_1 && sudo docker rm compose_cockroach2_1
compose_cockroach2_1
Error response from daemon: You cannot remove a running container 5b6550b3ec9bff0be8eea857de9a954b6d67e75f1f1fce483468b89e9b943270. Stop the container before attempting removal or force remove
ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose stop cockroach2 && sudo docker-compose rm cockroach2
Stopping compose_cockroach2_1 ... done
No stopped containers

ubuntu@tpserver1:/data/docker/compose$ sudo docker-compose ps | grep cock
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
compose_cockroach1_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26257->26257/tcp,   
compose_cockroach2_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26258->26257/tcp,   
compose_cockroach3_1          /cockroach/cockroach.sh st    Up                            0.0.0.0:26259->26257/tcp,
```

**Comment by leberknecht** [comment] 2017-10-11 14:09
Do you have steps-to-reproduce for bringing the container in the "stopped but still up" state? Because i think this seems to be a problem that occurs quite ..."often but sporadically", and looks like no one has found a reliable way to reproduce this strange container state so far.
I might be wrong, but google brings a lot of hits for "cannot stop/kill container" (with no solution so far i think) and this sounds related.

**Comment by thaJeztah** [comment] 2017-10-11 14:55
First of all, I would recommend installing the latest patch release of Docker 17.06 (version 17.06.2); there have been various bug fixes in those patch releases (https://github.com/docker/docker-ce/releases/tag/v17.06.1-ce, https://github.com/docker/docker-ce/releases/tag/v17.06.2-ce)

This also looks like a duplicate of https://github.com/moby/moby/issues/32938, https://github.com/moby/moby/issues/33192, https://github.com/moby/moby/issues/31768, https://github.com/moby/moby/issues/32827, or possibly others. 

The TL;DR is that there are some possible causes, but more information would be needed to determine that; it's possible the container has already exited, but docker got out of sync, for example if the host runs out of memory and the kernel starts killing processes, bad things can happen, and it's possible docker therefore did not get notified the container was killed (https://github.com/moby/moby/issues/33192 is an example of that).

It's possible the does not directly respond to the stop-signal (e.g. a shell running as the main process in the container will ignore stop signals, thus requires to be forcibly killed, which will happen after 10 seconds or so).

Also check the linked issues, which contain some information on how to get more details about what's happening (e.g., check if the container is actually still running, or how to get a stack trace from the daemon to get more details).

With the current amount of information, it's going to be difficult to look into your specific case, as a reproduction steps are needed (also the output of `docker info` is currently missing in this report, which contains more details about your setup).

If you have a minimum case to reproduce, preferably without docker-compose or custom images, and logs or other information, that would be helpful.

**Comment by JannikZed** [comment] 2018-06-15 08:55
I'm having the same issue on a real regular basis. We are using kubernetes as an orchestrator on several bare metal servers and the problem happens on all nodes. Containers just get stuck removing and only a machine restart can help!
Following setup:

```
Server Version: 18.03.1-ce
Storage Driver: overlay2
CentOS Linux release 7.5.1804 (Core)
```
I can provide you with every piece of information you think is needed to further analyze the problem. It occurs pretty often and brings us to real issues in live ..

**Comment by thaJeztah** [comment] 2018-06-15 20:40
@JannikZed given that there's a big difference in your version and the version with which this issue was originally reported, and a difference in use (with/without kubernetes, which could play a role), could you open a new ticket with details? At least `docker version` and `docker info` full output, but to resolve this, logs (from the `dockerd` daemon, possibly system logs) would be useful, perhaps there's information in there that could help find what's causing this situation.

**Comment by thaJeztah** [comment] 2020-03-10 09:46
closing, as this one went stale

**Closed by thaJeztah** 2020-03-10 09:46 UTC
Labels: area/runtime, status/more-info-needed, version/17.06
