### ISSUE TITLE
no suitable node available for task

### ISSUE THREAD

**Issue by JaxLgj** [moby/moby#34932] opened 2017-09-22 06:17 UTC
**Description**

I just follow the Get started on https://docs.docker.com/get-started/part3/#scale-the-app and when I run the command "docker stack deploy -c docker-compose.yml getstartedlab". 
My service cannot start, and the status is pedding.
![cannotstart](https://user-images.githubusercontent.com/24977009/30731498-4cfe45fa-9fa0-11e7-8bba-998d53cee0d0.png)

**Output of `docker version`:**

```
E:\Docker>docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:47 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
E:\Docker>docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.06.2-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: s1ujo2ib00sszoed0zqqw43bv
 Is Manager: true
 ClusterID: 12dtho4zwkmfoli8wqwatovf4
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.16.50.84
 Manager Addresses:
  172.16.50.84:2377
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.903GiB
Name: DESKTOP-70DVVHK
ID: VIMW:VZ5E:HQAF:YHZD:AGXO:3B2Q:CNDK:7C3B:K4ZY:U6E5:CZBK:DYES
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 133
 System Time: 2017-09-22T14:11:10.1556983+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-09-22 10:05
Do you have an existing service or container that's using port 80? If so, docker will keep trying to deploy the service until the port becomes available

**Comment by thaJeztah** [comment] 2017-09-22 10:06
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-09-22 10:06 UTC
Labels: version/17.06
