### ISSUE TITLE
docker start failed

### ISSUE THREAD

**Issue by githubadmi** [moby/moby#33624] opened 2017-06-10 12:27 UTC
Hi,

I have to setup docker with devicemapper direct-lvm on Centos7.
[root@dockermanager ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@dockermanager ~]# rpm -qa | grep docker
docker-engine-17.05.0.ce-1.el7.centos.x86_64
[root@dockermanager ~]# rpm -qa | grep device
device-mapper-persistent-data-0.6.3-1.el7.x86_64

[root@dockermanager ~]# systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
[root@dockermanager ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─daemon.conf
   Active: failed (Result: start-limit) since Sat 2017-06-10 14:56:30 EDT; 5s ago
     Docs: https://docs.docker.com
  Process: 3126 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 3126 (code=exited, status=1/FAILURE)

Jun 10 14:56:30 dockermanager.example.com systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jun 10 14:56:30 dockermanager.example.com systemd[1]: Failed to start Docker Application Container Engine.
Jun 10 14:56:30 dockermanager.example.com systemd[1]: Unit docker.service entered failed state.
Jun 10 14:56:30 dockermanager.example.com systemd[1]: docker.service failed.
Jun 10 14:56:30 dockermanager.example.com systemd[1]: docker.service holdoff time over, scheduling restart.
Jun 10 14:56:30 dockermanager.example.com systemd[1]: start request repeated too quickly for docker.service
Jun 10 14:56:30 dockermanager.example.com systemd[1]: Failed to start Docker Application Container Engine.
Jun 10 14:56:30 dockermanager.example.com systemd[1]: Unit docker.service entered failed state.
Jun 10 14:56:30 dockermanager.example.com systemd[1]: docker.service failed.

Please help me to fix it.

**Comment by thaJeztah** [comment] 2017-06-10 13:11
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-06-10 13:11 UTC
