### ISSUE TITLE
tar command fails with OverlayFS storage driver but not with aufs

### ISSUE THREAD

**Issue by olalonde** [moby/moby#19647] opened 2016-01-24 22:11 UTC
Command to reproduce:

``` bash
docker run -it --rm heroku/cedar:14 /bin/bash -c "curl -sS https://install.meteor.com | /bin/sh"
```

On Docker v1.8.1, aufs storage driver, the command completes successfully:

``` bash
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.2.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

```

On Docker v1.8.3, overfayfs storage driver, the command fails:

``` bash
Downloading Meteor distribution
######################################################################## 100.0%
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/with/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/with/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/with: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/transformers/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/transformers/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/transformers: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/defs/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/defs/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/defs: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Installation failed.
```

More logs:

``` bash
core@deis-03 ~ $ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   cedd534-dirty
 Built:        Sat Dec  5 05:57:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   cedd534-dirty
 Built:        Sat Dec  5 05:57:26 UTC 2015
 OS/Arch:      linux/amd64
core@deis-03 ~ $ docker info
Containers: 11
Images: 69
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.2-coreos-r1
Operating System: CoreOS 835.9.0
CPUs: 1
Total Memory: 1.959 GiB
Name: deis-03
ID: SSCW:KJB5:3MI4:WCSV:RXKY:WG2W:HB7U:TRYL:36L4:ZDTC:5KUL:JIMD
```

Related issues: https://github.com/deis/deis/issues/4867 https://github.com/meteorhacks/meteord/issues/64 https://github.com/meteor/meteor/issues/5762

**Comment by AkihiroSuda** [comment] 2016-01-25 11:11
Could not reproduce in my two environments: 
* Docker 1.10.0-rc1, Kernel 4.2.0-25-generic (Ubuntu 15.10)
* Docker 1.6.2, Kernel 4.4.0-rc8 (vanilla)

@olalonde Could you please try newer CoreOS?

**Comment by olalonde** [comment] 2016-01-25 18:45
@AkihiroSuda doubt that will help, [CoreOS 835.9.0](https://coreos.com/releases/#835.9.0) was released two months ago. Are you sure you tested with OverlayFS and not AUFS storage driver?

**Comment by AkihiroSuda** [comment] 2016-01-26 01:55
Yes, I'm using OverlayFS. 
I'll try other environments including CoreOS later.
```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.0-rc1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.6 GiB
...
$ docker run -it --rm heroku/cedar:14 /bin/bash -c "curl -sS https://install.meteor.com | /bin/sh"`
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.2.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com
```

**Comment by AkihiroSuda** [comment] 2016-01-26 02:39
I confirmed that the bug is reproducible with CoeOS 935.0.0 (kernel 4.4.0-coreos-r2).

**Comment by thaJeztah** [comment] 2016-01-26 02:45
@olalonde can you report this issue in the CoreOS issue tracker? They have their own builds, and issues for those builds should be reported in the CoreOS issue tracker first.

I'll close this issue here, but happy to reopen if it turns out to be an issue here

**Comment by AkihiroSuda** [comment] 2016-01-26 04:21
Oh, it's even reproducible with Boot2Docker v1.10.0-rc1.

@thaJeztah This is not specific to CoreOS. So I think it's worth reopening and investigating here.

It seems that the the bug is highly reproducible with a fresh overlay partition, but not so much reproducible with aged one. I guess that's why I couldn't reproduce in some my aged environments (https://github.com/docker/docker/issues/19647#issuecomment-174474945)

**Comment by olalonde** [comment] 2016-01-26 05:28
@thaJeztah I'm fairly certain the bug is with OverlayFS actually, but couldn't figure out where to open an issue :) (maybe in the Linux Kernel issue tracker?)

**Comment by thaJeztah** [comment] 2016-01-26 07:41
Sure, I'll reopen :-)

Hm, not sure if reporting upstream will help with overlay; we're actually trying to get the upstream maintainer to apply some patches, but no response so far :cry:

**Comment by mitar** [comment] 2016-05-31 07:35
Interesting. I am getting this error sometimes for Docker hub automatic builds for my Meteor apps in exactly the same step, when install Meteor inside, which uses tar to extract files. But what is interesting is that sometimes it happens and sometimes it does not. Does Docker hub build images on different underlying configurations?

**Comment by thaJeztah** [comment] 2016-05-31 10:35
@mitar Docker Hub starts a fresh machine for each build to guarantee your builds are executed in a clean environment, and no artifacts are left around (see https://blog.docker.com/2015/11/upgraded-autobuild-docker-hub/). For what I've heard, they updated the configuration to address this issue, but if you're still seeing this, please contact support@docker.com; they should be able to look into that.

**Comment by mitar** [comment] 2016-05-31 11:33
Yes, I have just seen it. And it is crazy, so I compile the same commit to `latest` and `master`, and one succeeded while the other one failed. At the same time. 4 hours ago.

I will contact them.

**Comment by keyscores** [comment] 2016-07-01 16:41
+1 This seems to be a problem on Docker Cloud, as well as Docker Hub

**Comment by thaJeztah** [comment] 2016-07-01 16:50
@keyscores could you send an e-mail to support@docker.com?

**Comment by keyscores** [comment] 2016-07-09 18:41
@thaJeztah @borjaburgos I emailed 8 days ago. I still don't have a meaningful response from support@docker.com

**Comment by bkil-sandbox** [comment] 2016-07-15 18:16
I'm seeing the same problem:

https://cloud.docker.com/_/repository/docker/bkil/openwrt-image-generator/timeline
'master' (8935cf62)

**Comment by AkihiroSuda** [comment] 2016-07-22 23:52
Progress in https://github.com/coreos/bugs/issues/1095#issuecomment-233793361 :smile:

**Comment by thaJeztah** [comment] 2016-07-22 23:53
ping @dmcgowan ^^

**Comment by dmcgowan** [comment] 2016-07-26 20:41
@AkihiroSuda thanks for the pointer, looks similar to other inode change issues with OverlayFS. There is a relevant discussion going on here as well http://thread.gmane.org/gmane.linux.file-systems.union/879/focus=879. This likely effects both `overlay` and `overlay2` since it can occur anytime an extraction is done on an OverlayFS mount. Adding the kernel flag.

**Comment by bachp** [comment] 2016-08-29 07:53
As the gmane archive is down I wanted to check if this link points to the conversation mentioned above:
http://www.spinics.net/lists/linux-unionfs/msg00856.html

**Comment by dmcgowan** [comment] 2016-08-29 17:23
@bachp that is correct, thanks for updated link

**Comment by keyscores** [comment] 2016-10-27 20:55
Is this still an open issue? I know docker-hub and docker-cloud are having issues related to this.

**Comment by dmcgowan** [comment] 2016-10-27 21:07
@keyscores yes it is, the upstream overlayfs kernel maintainers are actively working on a solution and we will update here when there is a fix in a kernel release. Until then applications needs to be able to handle the non-posix compliance of overlayfs or use a posix complaint storage driver.

**Comment by keyscores** [comment] 2016-10-27 21:26
@dmcgowan  Ok thanks. I think you should reach out to your colleagues at docker cloud, to make doubly sure they are communicating this correctly. Docker's own infrastructure is not compliant with your fix.

**Comment by olalonde** [comment] 2016-10-27 22:52
@dmcgowan is it related to that issue? https://github.com/npm/npm/issues/9863#issuecomment-152342020 (EXDEV error)

**Comment by dmcgowan** [comment] 2016-10-27 23:03
@olalonde no, EXDEV on rename is different and should be handled by the application. If the application is failing because of it (like npm), then that is on npm to handle appropriately. Normally when an application gets EXDEV on rename, it should fallback to doing a copy.

This error is related to the inode for a file changing in a way that the application did not expect. Applications can be updated to handle this case (as was done with yum), but it is still considered a short coming of overlayfs. It caused by overlayfs changing the inode when a file is copied up. Opening a file for read does not cause a copy up, but if later the same file is open for write, then overlay will copy up. After the copy up the application sees the inode change and thinks that the file changed, causing an error.

**Comment by bachp** [comment] 2016-10-29 10:19
@dmcgowan Do you have a link to where this is discussed by upstream overlayfs maintainers? I'm only aware of the conversation that was linked above.

**Comment by justincormack** [comment] 2016-10-29 11:16
@dmcgowan  this seems to be resolved in recent kernels as far as I can tell, certainly cannot repro on Docker for Mac (overlay2, Linux 4.4.27).

**Comment by Iodun** [comment] 2016-11-25 20:34
I am still experiencing this problem regularly on CoreOS 1185.3.0
That is Docker 1.11.2 and Kernel 4.7.3.

**Comment by jasonkeene** [comment] 2016-11-26 18:36
I also am experiencing this issue on CoreOS stable (1185.3.0).

**Comment by jupiterkenji** [comment] 2016-11-27 06:25
I am also experiencing this issue on Ubuntu 16.04.1 LTS. Changing it to aufs works

**Comment by arno01** [comment] 2016-11-29 17:15
Did anyone try "overlay2" driver?

**Comment by dmcgowan** [comment] 2016-11-29 19:25
This bug applies to both overlay and overlay2. The root cause of the original bug is caused by non-standard behavior in overlayfs. Different versions of tar may be updated to handle this behavior and it could also have a race element causing it to only be exhibited sometimes. See this section of the overlayfs documentation.

```
Non-standard behavior
---------------------

The copy_up operation essentially creates a new, identical file and
moves it over to the old name.  The new file may be on a different
filesystem, so both st_dev and st_ino of the file may change.

Any open files referring to this inode will access the old data.
``` 

Luckily the overlayfs maintainers are working on addressing this behavior and we will update this issue when it has been fixed upstream.

**Comment by dmcgowan** [comment] 2016-11-29 19:27
@bachp most recent proposal to fix is here http://www.spinics.net/lists/linux-unionfs/msg01265.html

**Comment by tiborvass** [comment] 2017-01-14 02:12
I hit this today :(

**Comment by Bregor** [comment] 2017-01-17 21:19
Same here with relatively fresh kernel and docker and overlay2.

	# uname -a
	Linux kube06 4.8.17-040817-generic #201701090438 SMP Mon Jan 9 09:40:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


	# docker info
	Containers: 39
	 Running: 27
	 Paused: 0
	 Stopped: 12
	Images: 28
	Server Version: 1.12.6
	Storage Driver: overlay2
	 Backing Filesystem: extfs
	Logging Driver: json-file
	Cgroup Driver: cgroupfs
	Plugins:
	 Volume: local
	 Network: null overlay host bridge
	Swarm: inactive
	Runtimes: runc
	Default Runtime: runc
	Security Options: apparmor seccomp
	Kernel Version: 4.8.17-040817-generic
	Operating System: Ubuntu 16.04.1 LTS
	OSType: linux
	Architecture: x86_64
	CPUs: 2
	Total Memory: 3.859 GiB
	Name: kube06
	ID: BXB2:WQP3:GZ5I:JDBH:GWPO:ZSKQ:AHNM:XH77:V2RR:E2CO:TJ5X:6GUD
	Docker Root Dir: /var/lib/docker
	Debug Mode (client): false
	Debug Mode (server): false
	Registry: https://index.docker.io/v1/
	WARNING: No swap limit support
	Insecure Registries:
	 127.0.0.0/8

**Comment by samoht** [comment] 2017-01-31 18:03
Reported as well by @mfeblowitz in Docker for Mac https://github.com/docker/for-mac/issues/1219. Switching back to aufs fixed the issue...

**Comment by xinity** [comment] 2017-02-07 14:36
got the issue here using Docker for windows latest release.
switched back to aufs definitely solved it !

what's wrong with overlayfs2 implementation ?

**Comment by jasonkeene** [comment] 2017-02-07 20:17
@xinity It plays tricks that tar does not like.

**Comment by acathrow** [comment] 2017-04-26 14:22
Is there any update on this issue, ideally ETA for a fix.

**Comment by thaJeztah** [comment] 2017-04-28 23:24
@acathrow it's not a Docker bug, but an issue with the way overlay is implemented in the kernel; the thread to the kernel discussion seems to have stalled on december 6 though; http://www.spinics.net/lists/linux-unionfs/msg01321.html

**Comment by cameronbrunner** [comment] 2017-05-04 17:03
Looks like there is progress being made on this:

https://lwn.net/Articles/721470/

**Comment by AkihiroSuda** [comment] 2017-08-07 06:03
This information seems useful: https://github.com/coreos/bugs/issues/1095#issuecomment-318773389

> I think kernel 4.13's OVERLAY_FS_INDEX=y config should fix this. See https://lwn.net/Articles/725276/

**Comment by karanhiremath** [comment] 2017-09-12 18:00
Was running into this bug here today and [Docker 17.09.0-ce-rc1](https://github.com/docker/docker-ce/releases/tag/v17.09.0-ce-rc1) from the Edge channel ([Docker for Mac download here](https://download.docker.com/mac/edge/Docker.dmg)) ended up fixing the issue for me. Obviously be careful with the Edge channel releases as always but it looks like progress has been made in there.

**Comment by antis81** [comment] 2017-09-17 08:00
Ran into same issue on Xubuntu 16.04 host (inside a VirtualBox). Docker version: `17.06.2-ce`. For the moment, the `bsdtar` workaround should do.

**Comment by jouve** [comment] 2017-11-28 10:58
@AkihiroSuda using kernel > 4.13 fixed this issue for me.

**Comment by nelisbijl** [comment] 2019-01-03 11:32
This is an open issue for 2 years now. Any idea how much time/money is wasted, chasing this evident bug?

**Comment by AkihiroSuda** [comment] 2019-01-03 11:56
@nelisbijl Are you still seeing the issue with recent kernels?

**Comment by nelisbijl** [comment] 2019-01-03 12:21
2.0.0.0-mac81 (29211) on macOS Mojave 10.14.2
now using the bsdtar trick

**Comment by tahsmith** [comment] 2019-02-04 03:41
Still present on 2.0.0.2 (30215) (macOS 10.13.6)
Moreover, the "storage-driver" : "aufs" soln no longer seems to be accepted. Daemon does not start with that set.

**Comment by rpkyle** [comment] 2019-04-05 18:21
The `bsdtar` fix suggested above did not work for me on Mac OS 10.13.4, using Docker 2.0.0.3. 

Additionally, Docker removed support for `aufs` in Docker Community Edition 2.0.0.0-mac78 on 2018-11-19:

https://docs.docker.com/docker-for-mac/release-notes/

While it's less than ideal, for anyone currently stuck with no alternative solutions and wanting to _test builds_ on Mac OS, it's possible to switch storage drivers -- `vfs` worked for me. There are caveats, as noted on the page below:

> _The vfs storage driver is intended for testing purposes, and for situations where no copy-on-write filesystem can be used. Performance of this storage driver is poor, and is not generally recommended for production use._

It requires one line of JSON in the daemon config file:

```
"storage-driver" : "vfs"
```

The full list is here:

https://docs.docker.com/storage/storagedriver/select-storage-driver/

Adding this comment in case someone finds it helpful.

**Comment by Heermosi** [comment] 2019-04-24 01:18
Ran into the bug for weeks and finally reached this...
Runing in ubuntu xenial, with most up-to-date docker running(overlay2).
I'll try the bsdtar tricks. If anything else could work instead of tar, ....
Can any one explain what happened exactly inside the kernel? I must submit a report to my boss.

**Comment by ed-alertedh** [comment] 2019-05-24 05:29
I just hit this on Windows. I ended up uninstalling docker, then installing 18.06.1-ce-win73 (19507), then forcing aufs as storage driver (settings->Daemon->advanced, then add `"storage-driver": "aufs"` to the json config)

**Comment by rpkyle** [comment] 2019-12-09 23:34
I realize I never followed up with the solution which has worked for me. I've completely uninstalled the Docker GUI as it's unhelpful for my regular use given the issues noted above.

I ended up using VirtualBox, and running `docker-machine` using the instructions available here:

https://docs.docker.com/machine/get-started/

It's been working flawlessly for me, no more `tar` errors to resolve.

**Comment by thaJeztah** [comment] 2019-12-10 09:22
I'm no longer able to reproduce this on Docker Desktop "edge" (`2.1.6.0 (40807)`), which is using kernel 4.19.76. Is this still an issue on the "stable" channel of Docker Desktop?

**Comment by FrankSpierings** [comment] 2020-01-20 14:36
@

> I'm no longer able to reproduce this on Docker Desktop "edge" (`2.1.6.0 (40807)`), which is using kernel 4.19.76. Is this still an issue on the "stable" channel of Docker Desktop?

Yes, I am on Docker Desktop (OSX) `2.1.0.5 (40693)` and I just experienced this issue in a container. Replacing `/bin/tar` with `/usr/bin/bsdtar` resolved it.

**Comment by thaJeztah** [comment] 2020-03-10 09:11
Tried this again, and wasn't able to reproduce. Given that this is quite and old issue now, I'll close

```bash
docker run -it --rm heroku/cedar:14 /bin/bash -c "curl -sS https://install.meteor.com | /bin/sh"
Unable to find image 'heroku/cedar:14' locally
14: Pulling from heroku/cedar
c02c7df4a131: Pull complete
a3ed95caeb02: Pull complete
8b276b980349: Pull complete
b44e0afe276b: Pull complete
Digest: sha256:457bc14275dc871f81d23b40f7c69523c2bc6ff90977512ea966a0f2a5bff18a
Status: Downloaded newer image for heroku/cedar:14
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.9.2 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

Deploy and host your app with Galaxy:

  www.meteor.com/hosting
```

**Closed by thaJeztah** 2020-03-10 09:11 UTC
Labels: area/kernel, area/storage/overlay, status/more-info-needed, version/1.8
