### ISSUE TITLE
Swarm Mode container response times are 50x slower on RHEL 7 vs Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [moby/moby#27203] opened 2016-10-06 20:12 UTC
**Description**
Swarm Mode container response times are 50x slower on RHEL 7 vs Ubuntu 14.04.  My suspicion is that there is an issue with the performance of the overlay network.

**Steps to reproduce the issue:**
1. Deploy 2 independent Swarms.  One running on RHEL 7 (Red Hat Enterprise Linux Server release 7.2).  One running Ubuntu 14.04.4 LTS, Trusty Tahr.  3 masters with availability set to "drain".  5 workers. 
2. Deploy an HTTP Web Server container (Apache Tomcat works fine) as a Swarm service with replicas set to "1".
3. Perform a basic performance test against the HTTP home page using jMeter 3.0.  Measure overall response time and TCP connection time.  100 users (threads), 300 second ramp time, loop forever.  4 remote load drivers.  The jMeter test is configured to access Apache on each worker node using the Swarm PublishedPort for the service.  Define success as an HTTP 200 response and parse the HTML body for "If you're seeing this, you've successfully installed Tomcat"
4. Compare the results to running the container without Swarm (basic "docker run").

**Describe the results you received:**
Average response time on Ubuntu was 2ms.  Average response time on RHEL was 95ms.  While the median response times on both operatin systems were 2ms, the 90% difference was 3ms vs 200ms.  Additionally, the error rate on Ubuntu was 0.00% while on RHEL it was 0.48%.  The errors were all attributed to TCP timeouts (I set the jMeter TCP connection timeout to 2 seconds).  On the requests that did succeed, TCP connection time was occasionally between 800 and 1000ms.

Looking at the 5 worker nodes on RHEL, one node always performed extremely well (average response time was 2ms, 90% response time was 2ms, 99% response time was 5ms).  In all cases, that node was always the node running the Apache container.

**Describe the results you expected:**
Expected similar performance between Ubuntu and RHEL.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 21:52:38 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 21:52:38 2016
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Ubuntu
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /apps/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: 9q5pxjc1m3jgiexmk2k85h1f4
 Is Manager: true
 ClusterID: ez8ncqxk7bo6rerg9a3df1bbv
 Managers: 3
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.138.129.251
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.946 GiB
Name: worker1
ID: 2V3M:7TNZ:2RGC:RHED:NC2Y:K6SX:OUYW:VVE3:6NYL:J2TX:HWRF:BPBT
Docker Root Dir: /apps/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

```
RHEL:
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.2-rc2
Storage Driver: devicemapper
 Pool Name: docker-202:17-1048580-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 594.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 49.17 GB
 Metadata Space Used: 1.61 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /apps/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /apps/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: 9rb0krmxqhacrq1lr5m9mdw0g
 Is Manager: true
 ClusterID: ahzga5biu4xa488710cd71qej
 Managers: 3
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.138.130.76
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.789 GiB
Name: worker2
ID: D3AE:M3OE:GGNQ:UF6A:HT2P:VSOT:TXKR:WEWU:DXTI:VLDP:HIRZ:AOHY
Docker Root Dir: /apps/docker/
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 50
 Goroutines: 187
 System Time: 2016-10-06T16:08:29.471747297-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMs running on Citrix Xen hypervisors.   Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz.

**Comment by aluzzardi** [comment] 2016-10-13 22:29
@mrjana Could this be related to the kernel version?

/cc @dperny @aaronlehmann Should we run some automated benchmarking?

**Comment by rain10628** [comment] 2017-06-12 07:37
how did you see the response time

**Comment by thaJeztah** [comment] 2017-06-12 15:35
@fcrisciani could you have a quick look at this one? Looks like the original reporter's account has been deleted, so if there's not enough information to reproduce/investigate I suggest to close this one.

**Comment by thaJeztah** [comment] 2023-09-16 17:41
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 17:41 UTC
Labels: area/networking, area/performance, version/1.12, area/swarm
