### ISSUE TITLE
docker ps stuck due to dm_udev_wait stuck

### ISSUE THREAD

**Issue by coolljt0725** [moby/moby#27900] opened 2016-10-31 11:31 UTC
**Description**
Version: docker-1.9.1

After running for a few days, we found `docker ps` stuck, so I send `SIGUSR1` to daemon with 
`kill -SIGUSR1 $(cat /var/run/docker.pid)` and got the goroutine stacks.
and obviously the `docker ps` was stuck on acquiring lock of container
````
sync.(*Mutex).Lock(0xc208731b90)
\t/usr/lib/golang/src/sync/mutex.go:66 +0xd3
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc208078f00, 0xc208d54480, 0xc208ff9f80, 0xc208e2d4b0, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/list.go:114 +0x52
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc208078f00, 0xc2090e7b80, 0xc208e2d4b0, 0x0, 0x0, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/list.go:97 +0x1bc
github.com/docker/docker/daemon.(*Daemon).Containers(0xc208078f00, 0xc2090e7b80, 0x0, 0x0, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/list.go:84 +0xa5
github.com/docker/docker/api/server/router/local.(*router).getContainersJSON(0xc208b07680, 0x7f8aa9f6f6d8, 0xc2090e3650, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270, 0xc2090e3530, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/router/local/container.go:47 +0x3ba
github.com/docker/docker/api/server/router/local.*router.(github.com/docker/docker/api/server/router/local.getContainersJSON)·fm(0x7f8aa9f6f6d8, 0xc2090e3650, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270, 0xc2090e3530, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/router/local/local.go:109 +0x7b
github.com/docker/docker/api/server.func·004(0x7f8aa9f6f6d8, 0xc2090e3650, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270, 0xc2090e3530, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
github.com/docker/docker/api/server.func·003(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270, 0xc2090e3530, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:66 +0x10e
github.com/docker/docker/api/server.func·002(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270, 0xc2090e3530, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:49 +0x47c
github.com/docker/docker/api/server.func·001(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270, 0xc2090e3530, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:27 +0x1dc
github.com/docker/docker/api/server.func·007(0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/server.go:156 +0x265
net/http.HandlerFunc.ServeHTTP(0xc208b586c0, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270)
\t/usr/lib/golang/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208b0e690, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270)
\t/home/abuild/rpmbuild/BUILD/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc20800c780, 0x7f8aa9f6f6a0, 0xc208ca06e0, 0xc208ef8270)
\t/usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208ca0320)
\t/usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
\t/usr/lib/golang/src/net/http/server.go:1751 +0x35e
````
There must be a go routine had sustain the lock of a container and we found this stack
````
goroutine 109 [semacquire, 2968 minutes]:
sync.(*Mutex).Lock(0xc20806e188)
\t/usr/lib/golang/src/sync/mutex.go:66 +0xd3
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).lookupDeviceWithLock(0xc20806e180, 0xc208d52280, 0x40, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:400 +0x53
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).exportDeviceMetadata(0xc20806e180, 0xc208d52280, 0x40, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:2408 +0x60
github.com/docker/docker/daemon/graphdriver/devmapper.(*Driver).GetMetadata(0xc208799770, 0xc208d52280, 0x40, 0x4ac929, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:111 +0x5d
github.com/docker/docker/daemon/graphdriver.(*NaiveDiffDriver).GetMetadata(0xc2087b21c0, 0xc208d52280, 0x40, 0x0, 0x0, 0x0)
\t<autogenerated>:29 +0x7c
github.com/docker/docker/daemon.(*Daemon).getInspectData(0xc208078f00, 0xc208d54480, 0x0, 0xc208d54480, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/inspect.go:142 +0xddd
github.com/docker/docker/daemon.(*Daemon).ContainerInspect(0xc208078f00, 0xc208ff91b0, 0x40, 0x0, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/inspect.go:24 +0x142
github.com/docker/docker/api/server/router/local.(*router).getContainersByName(0xc208b07680, 0x7f8aa9f6f6d8, 0xc209013ce0, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380, 0xc209013bf0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/router/local/inspect.go:29 +0x3d7
github.com/docker/docker/api/server/router/local.*router.(github.com/docker/docker/api/server/router/local.getContainersByName)·fm(0x7f8aa9f6f6d8, 0xc209013ce0, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380, 0xc209013bf0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/router/local/local.go:112 +0x7b
github.com/docker/docker/api/server.func·004(0x7f8aa9f6f6d8, 0xc209013ce0, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380, 0xc209013bf0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
github.com/docker/docker/api/server.func·003(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380, 0xc209013bf0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:66 +0x10e
github.com/docker/docker/api/server.func·002(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380, 0xc209013bf0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:49 +0x47c
github.com/docker/docker/api/server.func·001(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380, 0xc209013bf0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:27 +0x1dc
github.com/docker/docker/api/server.func·007(0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/server.go:156 +0x265
net/http.HandlerFunc.ServeHTTP(0xc208b595e0, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380)
\t/usr/lib/golang/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208b0e690, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380)
\t/home/abuild/rpmbuild/BUILD/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc20800c780, 0x7f8aa9f6f6a0, 0xc2089559a0, 0xc208ef9380)
\t/usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208c1f040)
\t/usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
\t/usr/lib/golang/src/net/http/server.go:1751 +0x35e
````
There is a `docker inspect` stuck on getting `GetMetadata`(https://github.com/docker/docker/blob/v1.9.1/daemon/inspect.go#L142)  and `GetMetadata` stuck on  'lookupDeviceWithLock' which try to acquire `devices.Lock()`(https://github.com/docker/docker/blob/v1.9.1/daemon/graphdriver/devmapper/deviceset.go#L399). This make the lock of container being hold forever and docker ps  stuck.(https://github.com/docker/docker/blob/v1.9.1/daemon/inspect.go#L22)

So we should found why `devices.Lock` of devicemapper is not free and we found this 
````
goroutine 90 [syscall, 2968 minutes, locked to thread]:
github.com/docker/docker/pkg/devicemapper._Cfunc_dm_udev_wait(0xd4d6bdc, 0xc200000000)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/:194 +0x43
github.com/docker/docker/pkg/devicemapper.dmUdevWaitFct(0xd4d6bdc, 0xc208012000)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:264 +0x29
github.com/docker/docker/pkg/devicemapper.UdevWait(0xc2090d7a70, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:314 +0x44
github.com/docker/docker/pkg/devicemapper.activateDevice(0xc2090e2c60, 0x24, 0xc2090cd440, 0x59, 0xd3, 0x1900000000, 0x0, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:805 +0x859
github.com/docker/docker/pkg/devicemapper.ActivateDevice(0xc2090e2c60, 0x24, 0xc2090cd440, 0x59, 0xd3, 0x1900000000, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:766 +0x89
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).activateDeviceIfNeeded(0xc20806e180, 0xc2090cd380, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:536 +0x472
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).MountDevice(0xc20806e180, 0xc208ffa9b0, 0x45, 0xc2088979d0, 0x66, 0x0, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:2084 +0x4e9
github.com/docker/docker/daemon/graphdriver/devmapper.(*Driver).Get(0xc208799770, 0xc208ffa9b0, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:192 +0x440
github.com/docker/docker/daemon/graphdriver.(*NaiveDiffDriver).Get(0xc2087b21c0, 0xc208ffa9b0, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
\t<autogenerated>:28 +0xb1
github.com/docker/docker/daemon.(*Daemon).createRootfs(0xc208078f00, 0xc20900e480, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:1001 +0x33e
github.com/docker/docker/daemon.(*Daemon).Create(0xc208078f00, 0xc208f48960, 0xc208fa6c80, 0xc208b1265d, 0x6b, 0x0, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/create.go:96 +0x541
github.com/docker/docker/daemon.(*Daemon).ContainerCreate(0xc208078f00, 0xc208b1265d, 0x6b, 0xc208f48960, 0xc208fa6c80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/daemon/create.go:31 +0x223
github.com/docker/docker/api/server/router/local.(*router).postContainersCreate(0xc208b07680, 0x7f8aa9f6f6d8, 0xc208fda660, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860, 0xc208fda570, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/router/local/container.go:385 +0x27d
github.com/docker/docker/api/server/router/local.*router.(github.com/docker/docker/api/server/router/local.postContainersCreate)·fm(0x7f8aa9f6f6d8, 0xc208fda660, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860, 0xc208fda570, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/router/local/local.go:129 +0x7b
github.com/docker/docker/api/server.func·004(0x7f8aa9f6f6d8, 0xc208fda660, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860, 0xc208fda570, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
github.com/docker/docker/api/server.func·003(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860, 0xc208fda570, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:66 +0x10e
github.com/docker/docker/api/server.func·002(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860, 0xc208fda570, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:49 +0x47c
github.com/docker/docker/api/server.func·001(0x7f8aadd9fa28, 0xc20802afd0, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860, 0xc208fda570, 0x0, 0x0)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:27 +0x1dc
github.com/docker/docker/api/server.func·007(0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860)
\t/home/abuild/rpmbuild/BUILD/docker/.gopath/src/github.com/docker/docker/api/server/server.go:156 +0x265
net/http.HandlerFunc.ServeHTTP(0xc208be6140, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860)
\t/usr/lib/golang/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208b0e690, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860)
\t/home/abuild/rpmbuild/BUILD/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc20800c780, 0x7f8aa9f6f6a0, 0xc208b12780, 0xc208ef9860)
\t/usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208ca14a0)
\t/usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
\t/usr/lib/golang/src/net/http/server.go:1751 +0x35e

````
From the stack we can see that `devicemapper._Cfunc_dm_udev_wait`  lock the `devices.Lock` and never release(print the stack after few hours and this go routine stack still exists.)

ping @rhvgoyal  any thoughts?

The work around for us is to use `dmsetup udevcomplete_all` when we encounter this.

**Comment by rhvgoyal** [comment] 2016-10-31 13:36
@coolljt0725 check your logs and see if there is any instance of udev thread being killed due to OOM. We have noticed the instances of a udev thread being killed, that means udev rule never gets to call `dmsetup udevcomplete` and that means docker can hang. 

Unfortunately, there does not seem to be a very good solution. If somebody runs into this, doing `dmsetup udevcomplete_all` or completing a specific cookie might be ok.

**Comment by coolljt0725** [comment] 2016-11-01 02:04
@rhvgoyal  thanks, I found this 
````
Oct 29 10:00:02 host-192-168-2-88 systemd-udevd[337]: worker [20020] /devices/virtual/block/dm-61 timeout; kill it
Oct 29 10:00:02 host-192-168-2-88 systemd-udevd[337]: seq 3667 '/devices/virtual/block/dm-61' killed
Oct 29 10:00:02 host-192-168-2-88 sysmonitor[504]: [2016-10-29:10:00:02]sysmonitor[504]: systemd-udevd[337](parent:systemd[1]) send SIGKILL to systemd-udevd[20020]
Oct 29 10:00:05 host-192-168-2-88 sysmonitor[504]: [2016-10-29:10:00:05]sysmonitor[504]: systemd-udevd[337](parent:systemd[1]) send SIGTERM to systemd-udevd[20061]
Oct 29 10:00:10 host-192-168-2-88 salt-master[18112]: [WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
Oct 29 10:00:16 host-192-168-2-88 systemd-udevd[337]: worker [20020] terminated by signal 9 (Killed)

````
in the log, does this may cause the problem?

**Comment by rhvgoyal** [comment] 2016-11-01 12:52
@coolljt0725 this looks like the relevant message. Now question is that why did timeout take place in first place. Is this machine too loaded or were there temporary storage issues or something else. Are you able to reproduce it frequently. Are you able to reproduce it frequently.

If you are able to reproduce it, I think try diving little deeper and figure out why timeouts do happen. Is it because of cpu load or because of storage issues.

**Comment by estesp** [comment] 2016-11-01 13:08
This doesn't fix the root cause, but we (IBM) are also experiencing this hard lock/hang, and haven't been able to figure out the `dm_udev_wait` culprit, and I noticed this PR come in yesterday: #27895 to do more fine-grained locking in this scenario.

@rhvgoyal are there any tools or other ways to log the path outside of Docker related to the udev interactions?

**Comment by estesp** [comment] 2016-11-01 13:09
By the way, I see that @coolljt0725 is experiencing this on 1.9, but we continue to experience it even on the latest 1.12.x releases, so I don't think it is solved in recent versions.

**Comment by rhvgoyal** [comment] 2016-11-01 13:21
@estesp If this problem happens, it will happen both on 1.9 and 1.12. Because it is not caused by docker implementation but other interactions on system outside docker. (A udev worker thread is killed either due to OOM or because of timeout and it never gets to call `dmsetup udevcomplete`).

**Comment by rhvgoyal** [comment] 2016-11-01 13:33
cc @prajnoha

**Comment by rhvgoyal** [comment] 2016-11-01 13:37
Ok, peter has few ideas on collecting some logs when this problem happens again.

- Run docker daemon with debug logs enabled. (-D)
- Run `udevadm monitor --udev --env`. This might be very verbose, so I think part of the effort will first be trying to narrow down on a reproducer.
- Once problem has happened, collect system logs with `journalctl -b -o short-precise`
- One can also think of booting kernel with command line option `debug` and that might enable extra debug messages in kernel as well as systemd + udev.

**Comment by rhvgoyal** [comment] 2016-11-01 13:52
@estesp @coolljt0725 Want to mention that whenever dm_udev_wait() issues have happened, it has happened because there are issues elsewhere in the system. For example, storage being too slow, or system being too overloaded etc. All this debugging will only help to gather enough data to prove where was the issue in the system.

**Comment by estesp** [comment] 2016-11-01 13:54
@rhvgoyal sure..that makes sense, and thanks for the pointers to the log collection guidance--will pass along to the ops teams and see if we can get more detail.

**Comment by coolljt0725** [comment] 2016-11-02 01:51
@rhvgoyal  thanks.
  I'm not able reproduce it frequently, we are trying to reproduce it again to get more informatio with you ideas on collecting logs. 

>Is this machine too loaded or were there temporary storage issues or something else.

I'm not sure about this, I didn't find anything about this from the logs.

**Comment by hqhq** [comment] 2016-11-04 02:16
Similar issue as https://github.com/docker/docker/issues/27543

**Comment by thaJeztah** [comment] 2023-06-06 07:48
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637

**Closed by thaJeztah** 2023-06-06 07:48 UTC
Labels: area/storage/devicemapper
