### ISSUE TITLE
Links in user defined networks don't support full-SHA aliasing

### ISSUE THREAD

**Issue by GeorgeMac** [moby/moby#35573] opened 2017-11-22 13:16 UTC
**Description**

Docker create container, in a user defined network, when providing `--link` doesn't support the forwarding of a full container ID SHA to an alias. Yet it does support the short form.

**Steps to reproduce the issue:**
1. `docker network create foo`
2. `docker run -dit --rm --net "foo" -p "8000" python python3 -m http.server` # e.g. > f10b8d3ec65690692306e7825284603ad648b6610ec8ecf5df97e5921616a619
3. `docker run -it --rm --net "foo" --link "f10b8d3ec65690692306e7825284603ad648b6610ec8ecf5df97e5921616a619:server" ubuntu apt-get update && apt-get install -y curl && curl server:8000` # hostname not found
4. `docker run -it --rm --net "foo" --link "f10b8d3ec656:server" ubuntu apt-get update && apt-get install -y curl && curl server:8000` # spits out the root directory contents of f10b8d3ec656

**Describe the results you received:**

As the comments describe above. The linked python container is NOT reachable in step 3, where it is reachable in step 4.

You will need to substitute in the returned container ID from step 2 in to both step 3 (in full) and step 4 (in short).

**Describe the results you expected:**

My assumption would be that the container identifier provided to link could be in the form of `<name|short-SHA|long-SHA>` but I can't actually find any specific documentation which defines this.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce-rc4
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   587f1f0
 Built:        Thu Nov 16 01:17:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.11.0-ce-rc4
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   587f1f0
 Built:        Thu Nov 16 01:43:23 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 154
Server Version: 17.11.0-ce-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: XL3E:73IM:YSPH:M4II:UYES:MMDY:AWFB:QQFF:ZKUI:KLVC:6RMW:RBWU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 69
 System Time: 2017-11-22T13:13:20.765955985Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**

Hyperkit / Docker for Mac

**Comment by thaJeztah** [comment] 2017-11-22 15:30
I can reproduce this:

```bash
$ docker network create foo
7fb1aa868fcd3c3264e91188674cbdd1ec481082117e3c13f8a1969fff7ff67b

$ docker run -d --rm --net=foo nginx:alpine
7c1603eed6f3883bffe4ab27b4ba4e070e256fb10ee4161d052e15a204b92a57

$ docker run --rm --net=foo --link=7c1603eed6f3:server nginx:alpine ping -c1 server
PING server (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.078 ms

--- server ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.078/0.078/0.078 ms

$ docker run --rm --net=foo --link=7c1603eed6f3883bffe4ab27b4ba4e070e256fb10ee4161d052e15a204b92a57:server nginx:alpine ping -c1 server
ping: bad address 'server'
```


Checking the requests that are made by the client:


```
time="2017-11-22T15:13:17.870496862Z" level=debug msg="Calling POST /v1.34/containers/create"
time="2017-11-22T15:13:17.870716087Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"ping\",\"-c1\",\"server\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":true,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":[],\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":[\"7c1603eed6f3:server\"],\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"NetworkMode\":\"foo\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"alpine\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{\"foo\":{\"Aliases\":null,\"DriverOpts\":null,\"EndpointID\":\"\",\"Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"IPAMConfig\":null,\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"Links\":[\"7c1603eed6f3:server\"],\"MacAddress\":\"\",\"NetworkID\":\"\"}}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"
time="2017-11-22T15:13:44.181447100Z" level=debug msg="Calling POST /v1.34/containers/create"
time="2017-11-22T15:13:44.181695705Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"ping\",\"-c1\",\"server\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":true,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":[],\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":[\"7c1603eed6f3883bffe4ab27b4ba4e070e256fb10ee4161d052e15a204b92a57:server\"],\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"NetworkMode\":\"foo\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"alpine\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{\"foo\":{\"Aliases\":null,\"DriverOpts\":null,\"EndpointID\":\"\",\"Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"IPAMConfig\":null,\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"Links\":[\"7c1603eed6f3883bffe4ab27b4ba4e070e256fb10ee4161d052e15a204b92a57:server\"],\"MacAddress\":\"\",\"NetworkID\":\"\"}}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"
```

Both look to pass the right information;

<details>

```json
{
  "AttachStderr": true,
  "AttachStdin": false,
  "AttachStdout": true,
  "Cmd": [
    "ping",
    "-c1",
    "server"
  ],
  "Domainname": "",
  "Entrypoint": null,
  "Env": [],
  "HostConfig": {
    "AutoRemove": true,
    "Binds": null,
    "BlkioDeviceReadBps": null,
    "BlkioDeviceReadIOps": null,
    "BlkioDeviceWriteBps": null,
    "BlkioDeviceWriteIOps": null,
    "BlkioWeight": 0,
    "BlkioWeightDevice": [],
    "CapAdd": null,
    "CapDrop": null,
    "Cgroup": "",
    "CgroupParent": "",
    "ConsoleSize": [
      0,
      0
    ],
    "ContainerIDFile": "",
    "CpuCount": 0,
    "CpuPercent": 0,
    "CpuPeriod": 0,
    "CpuQuota": 0,
    "CpuRealtimePeriod": 0,
    "CpuRealtimeRuntime": 0,
    "CpuShares": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "DeviceCgroupRules": null,
    "Devices": [],
    "DiskQuota": 0,
    "Dns": [],
    "DnsOptions": [],
    "DnsSearch": [],
    "ExtraHosts": null,
    "GroupAdd": null,
    "IOMaximumBandwidth": 0,
    "IOMaximumIOps": 0,
    "IpcMode": "",
    "Isolation": "",
    "KernelMemory": 0,
    "Links": [
      "7c1603eed6f3:server"
    ],
    "LogConfig": {
      "Config": {},
      "Type": ""
    },
    "Memory": 0,
    "MemoryReservation": 0,
    "MemorySwap": 0,
    "MemorySwappiness": -1,
    "NanoCpus": 0,
    "NetworkMode": "foo",
    "OomKillDisable": false,
    "OomScoreAdj": 0,
    "PidMode": "",
    "PidsLimit": 0,
    "PortBindings": {},
    "Privileged": false,
    "PublishAllPorts": false,
    "ReadonlyRootfs": false,
    "RestartPolicy": {
      "MaximumRetryCount": 0,
      "Name": "no"
    },
    "SecurityOpt": null,
    "ShmSize": 0,
    "UTSMode": "",
    "Ulimits": null,
    "UsernsMode": "",
    "VolumeDriver": "",
    "VolumesFrom": null
  },
  "Hostname": "",
  "Image": "alpine",
  "Labels": {},
  "NetworkingConfig": {
    "EndpointsConfig": {
      "foo": {
        "Aliases": null,
        "DriverOpts": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAMConfig": null,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "Links": [
          "7c1603eed6f3:server"
        ],
        "MacAddress": "",
        "NetworkID": ""
      }
    }
  },
  "OnBuild": null,
  "OpenStdin": false,
  "StdinOnce": false,
  "Tty": false,
  "User": "",
  "Volumes": {},
  "WorkingDir": ""
}
```


```json
{
  "AttachStderr": true,
  "AttachStdin": false,
  "AttachStdout": true,
  "Cmd": [
    "ping",
    "-c1",
    "server"
  ],
  "Domainname": "",
  "Entrypoint": null,
  "Env": [],
  "HostConfig": {
    "AutoRemove": true,
    "Binds": null,
    "BlkioDeviceReadBps": null,
    "BlkioDeviceReadIOps": null,
    "BlkioDeviceWriteBps": null,
    "BlkioDeviceWriteIOps": null,
    "BlkioWeight": 0,
    "BlkioWeightDevice": [],
    "CapAdd": null,
    "CapDrop": null,
    "Cgroup": "",
    "CgroupParent": "",
    "ConsoleSize": [
      0,
      0
    ],
    "ContainerIDFile": "",
    "CpuCount": 0,
    "CpuPercent": 0,
    "CpuPeriod": 0,
    "CpuQuota": 0,
    "CpuRealtimePeriod": 0,
    "CpuRealtimeRuntime": 0,
    "CpuShares": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "DeviceCgroupRules": null,
    "Devices": [],
    "DiskQuota": 0,
    "Dns": [],
    "DnsOptions": [],
    "DnsSearch": [],
    "ExtraHosts": null,
    "GroupAdd": null,
    "IOMaximumBandwidth": 0,
    "IOMaximumIOps": 0,
    "IpcMode": "",
    "Isolation": "",
    "KernelMemory": 0,
    "Links": [
      "7c1603eed6f3883bffe4ab27b4ba4e070e256fb10ee4161d052e15a204b92a57:server"
    ],
    "LogConfig": {
      "Config": {},
      "Type": ""
    },
    "Memory": 0,
    "MemoryReservation": 0,
    "MemorySwap": 0,
    "MemorySwappiness": -1,
    "NanoCpus": 0,
    "NetworkMode": "foo",
    "OomKillDisable": false,
    "OomScoreAdj": 0,
    "PidMode": "",
    "PidsLimit": 0,
    "PortBindings": {},
    "Privileged": false,
    "PublishAllPorts": false,
    "ReadonlyRootfs": false,
    "RestartPolicy": {
      "MaximumRetryCount": 0,
      "Name": "no"
    },
    "SecurityOpt": null,
    "ShmSize": 0,
    "UTSMode": "",
    "Ulimits": null,
    "UsernsMode": "",
    "VolumeDriver": "",
    "VolumesFrom": null
  },
  "Hostname": "",
  "Image": "alpine",
  "Labels": {},
  "NetworkingConfig": {
    "EndpointsConfig": {
      "foo": {
        "Aliases": null,
        "DriverOpts": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAMConfig": null,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "Links": [
          "7c1603eed6f3883bffe4ab27b4ba4e070e256fb10ee4161d052e15a204b92a57:server"
        ],
        "MacAddress": "",
        "NetworkID": ""
      }
    }
  },
  "OnBuild": null,
  "OpenStdin": false,
  "StdinOnce": false,
  "Tty": false,
  "User": "",
  "Volumes": {},
  "WorkingDir": ""
}
```

</details>


But using the full ID doesn't seem to add a DNS entry;

```
time="2017-11-22T15:13:45.142935211Z" level=debug msg="Name To resolve: server."
time="2017-11-22T15:13:45.143027079Z" level=debug msg="Name To resolve: server."
time="2017-11-22T15:13:45.143074781Z" level=debug msg="[resolver] query server. (AAAA) from 172.18.0.3:46725, forwarding to udp:192.168.65.1"
time="2017-11-22T15:13:45.143102907Z" level=debug msg="[resolver] query server. (A) from 172.18.0.3:44573, forwarding to udp:192.168.65.1"
time="2017-11-22T15:13:45Z" level=debug msg="event published" module="containerd/events" ns=moby topic="/tasks/start" type=containerd.services.events.v1.TaskStart 
time="2017-11-22T15:13:45.144056499Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/start
time="2017-11-22T15:13:45.184049944Z" level=debug msg="[resolver] external DNS udp:192.168.65.1 did not return any AAAA records for \"server.\""
time="2017-11-22T15:13:45.184172039Z" level=debug msg="[resolver] external DNS udp:192.168.65.1 did not return any A records for \"server.\""
```

**Comment by thaJeztah** [comment] 2017-11-22 15:36
@GeorgeMac although this should be looked into; perhaps using a _name_ for your containers would be a better alternative; instead of using `--link` (which was the standard method using the "default" network), you can assign a name to your containers, and that name can be used as hostname for any container that you add to that network.


For example:

```bash
$ docker network create foo

$ docker run -d --net=foo --name hello-world nginx:alpine

$ docker run --rm --net=foo alpine ping -c1 hello-world
PING hello-world (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.084 ms

--- hello-world ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.084/0.084/0.084 ms
```

If needed, you can assign network-scoped aliases to a container as well, for example:

```bash
$ docker run -d --net=foo --name one --network-alias two --network-alias three nginx:alpine

$ docker run --rm --net=foo alpine ping -c1 one
PING one (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: seq=0 ttl=64 time=0.116 ms

--- one ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.116/0.116/0.116 ms

$ docker run --rm --net=foo alpine ping -c1 two
PING two (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: seq=0 ttl=64 time=0.096 ms

--- two ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.096/0.096/0.096 ms

$ docker run --rm --net=foo alpine ping -c1 three
PING three (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: seq=0 ttl=64 time=0.082 ms

--- three ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.082/0.082/0.082 ms
```

**Comment by GeorgeMac** [comment] 2017-11-22 16:01
@thaJeztah cheers for the suggestion :D 
I have a bit of a unique use-case over at https://github.com/codeship working on our docker-compose like product. Where I have been introducing user defined networks to isolate what we call "steps". Steps at codeship depend on a service definition from our compose like syntax. Steps can be created in parallel and each step runs any service graph it likes. So naming becomes an issue for us. We have to make sure we construct names which don't collide. Not that this is difficult, we actually do it, but when referencing containers internally, we have been using their IDs.

This seemed to work fine for legacy links. Though new world links gave the above behavior. I have worked around it for now, but truncating the ID to the first 12 chars. Just thought I would share my findings incase either the docs can be updated or this behavior supported :)

**Comment by thaJeztah** [comment] 2017-11-22 16:06
Thanks for the additional information 👍 I should've checked your profile before posting my steps :smile: (I encounter many users that are unfamiliar with the workings of custom networks, and "stick" to the `--link` option)

> Just thought I would share my findings incase either the docs can be updated or this behavior supported :)

And thanks for that! It's really appreciated (your reproduction steps made it easy to confirm the issue)

**Comment by GeorgeMac** [comment] 2017-11-22 16:08
Awesome :D No problemo! Happy to share my findings. We are slowly shifting our platform to adopt the new world treats docker has to offer 😂 Eventually we want to push people towards aliases and depends_on. This is actually our precursor step 👍

**Comment by thaJeztah** [comment] 2017-11-22 16:13
Be careful with `depends_on`: it's not supported in "swarm" services and the compose 3.x format; the problem with `depends_on` is that, although it works for _starting_ a stack, it does not provide benefits during the full lifecycle of a stack; i.e., when starting the stack, the `depends_on` would be taken into account, but what if the dependency services goes down _after that_? (Also what should the behaviour be of `depends_on` if I _stop_ the dependency service? Should all services that depend on it be stopped as well?)

The recommended approach is to make services resilient against failures; e.g., have a retry-loop to check if the dependency service is available, and a similar/same approach for the situation where the dependency service _becomes_ unavailable.

**Comment by GeorgeMac** [comment] 2017-11-22 17:03
That is great, thank you for the advice :D ! Supporting it is our next work stream. So I will add this to our discovery phase 👍

**Comment by yongtang** [comment] 2017-12-20 21:22
I think the issue is that `CreateOptionAlias` used name directly but `CreateOptionMyAlias` used short ID of the container to alias. Created a PR #35853 to give it a try to fix it.

**Comment by akerouanton** [comment] 2024-03-04 10:28
As we're in the process of fully removing legacy links (see this RFC: https://github.com/moby/moby/issues/47464), let me close this issue.

**Closed by akerouanton** 2024-03-04 10:28 UTC
Labels: kind/bug, area/networking, platform/desktop, status/confirmed, version/17.11
