### ISSUE TITLE
Docker does not run with unified cgroup hierarchy

### ISSUE THREAD

**Issue by xnox** [moby/moby#16238] opened 2015-09-11 15:08 UTC
When booting system with systemd 226, with systemd.unified_cgroup_hierarchy option, docker with native & lxc drivers fail.

**Comment by orivej** [comment] 2015-10-05 19:45
`+1`
To reproduce (with Linux 3.16 or newer):
```
mkdir /sys/fs/cgroup/unified
mount -t cgroup -o __DEVEL__sane_behavior cgroup /sys/fs/cgroup/unified
docker run --rm busybox
```
Docker 1.8.1 prints:
```
Timestamp: 2015-10-05 19:44:19.240101459 +0000 UTC
Code: System error

Message: no subsystem for mount

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@37
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@19
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: Error response from daemon: Cannot start container e218e2e9e406121a1732013d1388648da84b31bc8ad5342bc6e5b73216a2f857: [8] System error: no subsystem for mount
```

**Comment by thaJeztah** [comment] 2015-10-19 14:36
also see https://github.com/docker/docker/issues/16256

**Comment by thaJeztah** [comment] 2015-12-02 23:50
@xnox we recently merged a PR to change the default to `cgroupfs` for docker 1.10, see https://github.com/docker/docker/pull/17704

**Comment by mrunalp** [comment] 2015-12-17 00:29
@xnox We need to add support for this to runc/libcontainer before docker can support it.

**Comment by sols1** [comment] 2016-03-17 18:36
cgroup v2 (unified hierarchy) is now official in 4.5:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34a9304a96d6351c2d35dcdc9293258378fc0bd8

cgroup v2 should have more sensible behavior:

https://www.youtube.com/watch?v=PzpG40WiEfM

Any plans to support it by docker?

**Comment by mrunalp** [comment] 2016-03-17 18:40
@sols1 Thanks for the update. I think we will start adding support for it in runc first.

**Comment by mrunalp** [comment] 2016-03-17 18:41
@sols1 Looks like some stuff is still missing, but we can start looking.
```
 Unfortunately, cpu v2 interface hasn't made it yet due to the discussion around in-process hierarchical resource distribution and only memory and io controllers can be used on the v2 interface at the moment.
```

**Comment by sols1** [comment] 2016-03-17 20:00
Actually, I am not sure what exactly this mean because cgroup v2 (unified hierarchy) existed in kernel as experimental feature since 3.16 and it **_should_** include cpu v2 interface.

4.5 commit makes v2 official but still optional. In fact it is possible to mix and match: memory and io can be on v2 and cpu on v1.

**Comment by thaJeztah** [comment] 2019-01-30 07:59
Latest status can be found in https://github.com/opencontainers/runc/issues/654

**Comment by fcelda** [comment] 2019-10-23 16:02
Please, is there a single place where this feature is being tracked?

The opencontainers/runc#654 has been just closed but mentions there will be new tickets for the remaining tasks. Is runc the only component that needs work? What else needs to be done?

**Comment by AkihiroSuda** [comment] 2019-10-26 16:16
containerd needs to support cgroup2: https://github.com/containerd/cgroups/pull/102

**Comment by xnox** [comment] 2019-11-01 00:00
containerd needs to support cgroup2 moved on to https://github.com/containerd/cgroups/pull/103 right?

**Comment by AkihiroSuda** [comment] 2019-11-01 04:33
yes

**Comment by AkihiroSuda** [comment] 2019-11-05 09:24
PR: https://github.com/moby/moby/pull/40174

**Closed** 2020-01-09 19:09 UTC
Labels: area/daemon, area/kernel, kind/enhancement
