### ISSUE TITLE
Wrong platform used from previous run

### ISSUE THREAD

**Issue by marcpawl-arista** [moby/moby#44343] opened 2022-10-21 13:37 UTC
### Description

If you run an image with --platform, then run the same image again but without --platform, the platform for the first run is used.

### Reproduce

```bash
(docker run --platform=linux/amd64 ubuntu:focal uname -a) && (docker run --platform=linux/arm64 ubuntu:focal uname -a) && (test $(docker run  ubuntu:focal uname -p) == $(uname -p))

(docker run --platform=linux/arm64 ubuntu:focal uname -a) && (docker run --platform=linux/amd64 ubuntu:focal uname -a) && (test $(docker run  ubuntu:focal uname -p) == $(uname -p))
```

One of the two commands will fail on Ubuntu.
Setting DOCKER_DEFAULT_PLATFORM makes both commands pass.

### Expected behavior

Both commands should pass,  the default platform should be the system and the last image run should not change the behavior for the next run command.

### docker version

```bash
bsn@jenkins-w4:~$ docker version
Client: Docker Engine - Community
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:19 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:11 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
```

### docker info

```bash
bsn@jenkins-w4:~$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)

Server:
 Containers: 14
  Running: 0
  Paused: 0
  Stopped: 14
 Images: 8
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-191-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.37GiB
 Name: jenkins-w4
 ID: FPZI:LUCF:H2LH:46BL:NH3P:2OPY:KQV2:IGIT:63DM:LSZU:VJGL:P562
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: bsnjenkins
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker-cache.eng.bigswitch.com/
 Live Restore Enabled: true

WARNING: No swap limit support
```

**Comment by marcpawl-arista** [comment] 2022-10-21 18:00
also seen on Mac M1 
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by thaJeztah** [comment] 2022-10-21 20:09
I _think_ this may be the same as https://github.com/moby/moby/issues/44291, and due to QEMU user land emulation not changing the hardware architecture, see https://github.com/moby/moby/issues/44291#issuecomment-1276850101

**Comment by sam-thibault** [comment] 2022-12-06 11:27
Closing as a likely duplicate of #44291

**Closed by sam-thibault** 2022-12-06 11:27 UTC
Labels: status/0-triage, kind/bug
