### ISSUE TITLE
container object with an empty Mounts.Source

### ISSUE THREAD

**Issue by wdhif** [moby/moby#37979] opened 2018-10-05 15:12 UTC
**Description**

When using the `GET /containers/json` endpoint of the API, some mounts have an empty `source` field. This issue seem to happen only with some mounts (`Type: volume`or `Mode: rw`)

**Steps to reproduce the issue:**
1. Call the `GET /containers/json` endpoint of the API, using any client.

**Describe the results you received:**
A container object with an empty `Mounts.Source` field.

```
{
  u 'Status': u 'Up 2 months (healthy)',
  u 'Created': 1525100823,
  u 'Image': u 'IMAGE_NAME',
  u 'Mounts': [{
    u 'RW': True,
    u 'Name': u '',
    u 'Propagation': u '',
    u 'Destination': u '/root',
    u 'Driver': u 'local',
    u 'Source': u '',
    u 'Mode': u '',
    u 'Type': u 'volume'
  }, {
    u 'RW': False,
    u 'Propagation': u 'rprivate',
    u 'Destination': u '/test_directory',
    u 'Source': u '/test_directory',
    u 'Mode': u 'ro',
    u 'Type': u 'bind
  }]
}
```

**Describe the results you expected:**
A container object with a correct `Mounts.Source` field.

```
{
  u 'Status': u 'Up 2 months (healthy)',
  u 'Created': 1525100823,
  u 'Image': u 'IMAGE_NAME',
  u 'Mounts': [{
    u 'RW': True,
    u 'Name': u '',
    u 'Propagation': u '',
    u 'Destination': u '/root',
    u 'Driver': u 'local',
    u 'Source': u '/var/lib/docker/volumes/X/_data',
    u 'Mode': u '',
    u 'Type': u 'volume'
  }, {
    u 'RW': False,
    u 'Propagation': u 'rprivate',
    u 'Destination': u '/test_directory',
    u 'Source': u '/test_directory',
    u 'Mode': u 'ro',
    u 'Type': u 'bind'
  }]
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 104
 Running: 99
 Paused: 0
 Stopped: 5
Images: 14
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 4.14.19-X
Operating System: Debian GNU/Linux X
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 57.58GiB
Name: X
ID: X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by wdhif** [comment] 2018-10-06 16:36
After some tests, I can also say that the latest beta version (`18.09.0-beta3`) doesn't seem to have this issue. I don't know if it was a known issue in previous versions of Docker.

Here are the results
```
[{
  u 'Status': u 'Up 2 seconds',
  u 'Created': 1538843425,
  u 'Image': u 'ubuntu',
  u 'Labels': {},
  u 'NetworkSettings': {
    u 'Networks': {
      u 'bridge': {
        u 'NetworkID': u 'd99adb88e8f5dbfbe31ff02744361582e3cee800577ccc431f1851e03513a6e3',
        u 'MacAddress': u '02:42:ac:11:00:02',
        u 'GlobalIPv6PrefixLen': 0,
        u 'Links': None,
        u 'GlobalIPv6Address': u '',
        u 'IPv6Gateway': u '',
        u 'DriverOpts': None,
        u 'IPAMConfig': None,
        u 'EndpointID': u '413a4377972a73f11ea3f0503358345716da13307a14ddc8e3f7658ef0f2d25f',
        u 'IPPrefixLen': 16,
        u 'IPAddress': u '172.17.0.2',
        u 'Gateway': u '172.17.0.1',
        u 'Aliases': None
      }
    }
  },
  u 'HostConfig': {
    u 'NetworkMode': u 'default'
  },
  u 'ImageID': u 'sha256:cd6d8154f1e16e38493c3c2798977c5e142be5e5d41403ca89883840c6d51762',
  u 'State': u 'running',
  u 'Command': u 'sleep 99999',
  u 'Names': [u '/confident_wing'],
  u 'Mounts': [{
    u 'RW': True,
    u 'Name': u 'ubuntu_test',
    u 'Propagation': u '',
    u 'Destination': u '/ubuntu',
    u 'Driver': u 'local',
    u 'Source': u '/var/lib/docker/volumes/ubuntu_test/_data',
    u 'Mode': u 'z',
    u 'Type': u 'volume'
  }],
  u 'Id': u '3015f366406058f7ea3de6cfef1222d2584011e1fb8c3e7a4b5b1075de3270e6',
  u 'Ports': []
}]
```

```
# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.0-beta3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 99fc40fd6088baebe3c18b8f8093cd50d58815d6 (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871 (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.11-200.fc28.x86_64
Operating System: Fedora 28 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.497GiB
Name: wassim-thinkpad-t430.home
ID: HRPU:2EKD:PV7K:HGFG:PMGE:ANLE:AUV5:QTZP:J2OA:AQYG:LGSO:YYD7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

```
# docker version
Client:
 Version:           18.09.0-beta3
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        7718f80
 Built:             Thu Oct  4 23:54:33 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0-beta3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       7718f80
  Built:            Thu Oct  4 23:24:09 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thaJeztah** [comment] 2018-10-08 10:34
Are you consistently able to reproduce this on 18.03? (if so; do you have the steps to reproduce?)

Note that 18.03-ce reached EOL; does this also reproduce on 18.06-ce (current stable, although 18.09 should be released in the not-so-distant future)

**Comment by wdhif** [comment] 2018-10-09 14:28
Hi @thaJeztah . Thanks for the quick answer.

I've run some more tests. All the following tests are run on the same machine.
To generate my results, I used the following script:
```
#!/usr/bin/python

import docker
import json

client = docker.APIClient()
for container in client.containers():
    for mount in container['Mounts']:
        print(json.dumps(mount))
```
It will simply print all the mounts for all the containers in json (for readability purpose).

**Using 18.03.1-ce**
```
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/home/admin", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": false, "Propagation": "rprivate", "Destination": "/localscripts", "Source": "/usr/local/containers/mysql/localscripts", "Mode": "ro", "Type": "bind"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/root", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/var/lib/mysql", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": false, "Propagation": "rprivate", "Destination": "/localscripts", "Source": "/usr/local/containers/mysql/localscripts", "Mode": "ro", "Type": "bind"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/root", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/var/lib/mysql", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/home/admin", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
```
**Output of `docker version`:**
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Using 18.06.1-ce**
```
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/home/admin", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": false, "Propagation": "rprivate", "Destination": "/localscripts", "Source": "/usr/local/containers/mysql/localscripts", "Mode": "ro", "Type": "bind"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/root", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/var/lib/mysql", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/home/admin", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": false, "Propagation": "rprivate", "Destination": "/localscripts", "Source": "/usr/local/containers/mysql/localscripts", "Mode": "ro", "Type": "bind"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/root", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/var/lib/mysql", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
```
**Output of `docker version`:**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

I can confirm that I get the same issue on the two version.

**Step to reproduce**
1. Create a named volume.
2. Bind the volume to a container.
3. Using the API, list the volumes.
4. Some mounts won't have any source field.

**Comment by cpuguy83** [comment] 2018-10-09 16:59
@wdhif I believe this is intentional, because fetching the source is slow, and in particular may not even be available unless the volume is actually mounted on the host.

**Comment by wdhif** [comment] 2018-10-09 18:05
Hi @cpuguy83 . Thanks for the explanation, just to make sure it's the current case we are experiencing, I have run more tests and I have some interesting news.

I actually started testing this issue on another machine, I already tested 18.09.0-beta3 on another machine since I could not test it on the first machine (the one experiencing this issue).

To resume the situation:

**Machine 1**
18.03.1-ce => Issue
18.06.1-ce => Issue
18.09.0-beta3 => Untested

**Machine 2**
18.03.1-ce => No issue
18.06.1-ce => No issue
18.09.0-beta3 => No issue

I'm starting to think this issue come from something with the first machine. I'll link below the `docker info` outputs of the two machines.

**Machine 1 `docker info`**
```
Containers: 104
 Running: 99
 Paused: 0
 Stopped: 5
Images: 14
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 4.14.19-X
Operating System: Debian GNU/Linux X
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 57.58GiB
Name: X
ID: X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Machine 2 `docker info`**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.11-200.fc28.x86_64
Operating System: Fedora 28 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.497GiB
Name: wassim-thinkpad-t430.home
ID: HRPU:2EKD:PV7K:HGFG:PMGE:ANLE:AUV5:QTZP:J2OA:AQYG:LGSO:YYD7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

If I had to guess, I would say that this might be an issue with `overlay` vs `overlay2` maybe.
I will try to replicate this issue using a pretty similar machine as the first one, in `overlay2`.

**Comment by wdhif** [comment] 2018-10-10 09:33
Here is the test on a similar machine as machine 1, with overlay2:

```
{"RW": false, "Propagation": "rprivate", "Destination": "/localscripts", "Source": "/usr/local/containers/mysql/localscripts", "Mode": "ro", "Type": "bind"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/root", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/var/lib/mysql", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/home/admin", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": false, "Propagation": "rprivate", "Destination": "/localscripts", "Source": "/usr/local/containers/mysql/localscripts", "Mode": "ro", "Type": "bind"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/root", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/var/lib/mysql", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
{"RW": true, "Name": "X", "Propagation": "", "Destination": "/home/admin", "Driver": "local", "Source": "", "Mode": "", "Type": "volume"}
```

As you can see there is not much difference between the two results, so `overlay` doesn't seem to be the issue here.

**Output of `docker info`:**
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 4.14.61-X
Operating System: Debian GNU/Linux X
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 57.57GiB
Name: X
ID: X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Closed** 2020-08-07 09:52 UTC
Labels: status/more-info-needed
