### ISSUE TITLE
Docker build is able to pull, but docker pull fails with "no basic auth credentials"

### ISSUE THREAD

**Issue by ReSearchITEng** [moby/moby#34506] opened 2017-08-14 18:23 UTC
**Description**
While using docker daemon official images (docker:1.12.6-dind) and  and docker client 1.12.6 but from centos7.3.1611, it looks there is a compatibility break of api 1.24.

While docker *build is able to pull* from private registries, but running manually docker pull command fails with "no basic auth credentials"

I have tried with many docker:1.12.6 and 1.17, always with docker client 1.12.6 from centos.
(Note, with docker client 1.12.6 from docker.io/docker:1.12.6 it works). So the issue is between distributions.

What is more interesting is that there are 2 flows (docker build and docker pull) which I expected to have them behave the same (ideally both should end with success), but pull in build works and independent pull fails.
I am not aware of any workaround (please suggest one or other options).
I have logged also a but on centos, as it's clearly an issue with API.
https://bugs.centos.org/view.php?id=13676 

**Steps to reproduce the issue:**
1. run docker daemon from docker.io/docker:1.12.6-dind (or docker.io/docker:1.12.6)
2. connect and run docker client from docker.io/centos:centos7.3.1611 )
on client run: 
3 docker login registry01
4. docker pull registry01/img1 ##->> error: "no basic auth credentials"
5. docker build . ## succeeded to pull the private images without any issues!

**Describe the results you received:**
Docker server has been set in debug mode, to extract the below:
```
---------------
#docker pull registry01/img1.... gives:
--
time="2017-08-14T16:57:29.127123462Z" level=debug msg="Calling POST /v1.24/images/create?fromImage=registry01%2Fimg1&tag=latest"
time="2017-08-14T16:57:29.131383531Z" level=debug msg="hostDir: /etc/docker/certs.d/registry01"
time="2017-08-14T16:57:29.131414937Z" level=debug msg="Trying to pull registry01/img1-docker-builder-dind from https://registry01 v2"
time="2017-08-14T16:57:29.144814115Z" level=info msg="Attempting next endpoint for pull after error: Get https://registry01/v2/img1/manifests/latest: no basic auth credentials"
time="2017-08-14T16:57:29.144857168Z" level=error msg="Handler for POST /v1.24/images/create returned error: Get https://registry01/v2/img1/manifests/latest: no basic auth credentials"
------
#while docker build with line: FROM registry01/img1... works ok!
--
time="2017-08-14T16:57:52.770418143Z" level=debug msg="Calling POST /v1.24/build?buildargs=%7B%7D&buildbinds=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&ulimits=null"
time="2017-08-14T16:57:52.805475272Z" level=debug msg="hostDir: /etc/docker/certs.d/registry01"
time="2017-08-14T16:57:52.805511646Z" level=debug msg="Trying to pull registry01/img1-docker-builder-dind from https://registry01 v2"
time="2017-08-14T16:57:52.840324978Z" level=debug msg="Pulling ref from V2 registry: registry01/img1-docker-builder-dind:latest"
time="2017-08-14T16:57:52.851023845Z" level=debug msg="pulling blob \"sha256:3da02d3473da6d4fb36bf03ed08422dd2ea5bcc057877a510764ed219f5f9680\""
time="2017-08-14T16:57:52.850993957Z" level=debug msg="pulling blob \"sha256:c7cbcb13fe2e4814515532e848a258f44a06dd46e7d0883b0168b5c49fca2c2d\""
time="2017-08-14T16:57:52.851013616Z" level=debug msg="pulling blob \"sha256:845d34b6bc6add99b34fdad64de06531f74c8666a28d9b424a7bd78cf0a043bf\""
```

**Describe the results you expected:**
docker pull and docker build should behave identically for a specific setup.

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker build is able to pull, but docker pull fails with "no basic auth credentials"

It's interesting, as I expected to have them behave the same.

both server and client machine do have the proper ssl ca certs installed for of the registry, and docker login has been performed in advance with success:
docker login  --username ... 
Password:
Login Succeeded

OS for both server and client: RHEL/CentOS 7.3
Registry is based on latest nexus3 (3.4.0-02), and has an nginx in front with ssl termination. Never faced any issues with this configuration. Docker works in all situations but the one below.
From same registry, with docker daemon 1.12.6, docker pull works without issues.

There is a http/https proxy, and no_proxy is set accordingly, it's not the issue as it works in with daemon 1.12.6 in identical setup.

docker server 17.07.0-ce-rc2 -> I did try other 17.x versions, all are failing.
docker client 1.12.6 (did not try other versions)

docker pull from docker.io (no auth) are working fine.

**Output of `docker version`:**
```
docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Wed May 17 01:16:44 2017
 OS/Arch:         linux/amd64

Server:
 Version:         17.07.0-ce-rc2
 API version:     1.31
 Package version:
 Go version:      go1.8.3
 Git commit:      36ce605
 Built:           Mon Aug  7 23:48:34 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**
```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vms
OS for both server and client: RHEL/CentOS 7.3
PS: When running in the opposite direction, (centos daemon and docker:1.12.6 as docker client), it works.
PS: When running both docker daemon and client from centos:centos7.3.1611, it works fine
PS: When running both docker daemon and client from docker:1.12.6, it works fine.

**Comment by thaJeztah** [comment] 2017-09-21 14:40
The docker.io and centos packages are not the official builds, and the Red Hat fork of Docker contains [a huge amount of modifications](https://github.com/moby/moby/compare/v1.12.6...projectatomic:docker-1.12.6) that can definitely be responsible for this.

Can you try reproducing with the official builds (https://docs.docker.com/engine/installation/linux/docker-ce/centos/) for both client and server?

Note that docker 1.12.6 is EOL and no longer maintained

**Comment by ReSearchITEng** [comment] 2017-09-22 10:48
Hi,
I am not sure how this is connected, but if one switches host docker storage from devicemapper to overlay2, this problem disappeared. 
I don't see the logic in it, but maybe someone can explain.

**Comment by rxysm** [comment] 2017-11-10 14:01
I got that problem after upgraded to latest macOS HIGH SIERRA. 
So What i did:
`cd amazon-ecr-credential-helper && make docker TARGET_GOOS=darwin`

my docker config file look like:
`{
  "credsStore" : "ecr-login"
}`

And It works for me.

**Comment by thaJeztah** [comment] 2017-11-10 15:57
Thanks @rxysm - your case looks to be different from the one reported here, as you are using amazon's ECR, which requires a custom credential helper indeed.

I'm closing this issue, because the original issue reported here looks to be resolved

**Closed by thaJeztah** 2017-11-10 15:57 UTC
Labels: area/builder, area/distribution, status/more-info-needed, version/17.07, version/unsupported
