### ISSUE TITLE
Install.sh on travis is failing

### ISSUE THREAD

**Issue by alenkacz** [moby/moby#33921] opened 2017-07-02 07:33 UTC
All my builds using install.sh on travis are failing with following error

E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/precise/edge/source/Sources  404  Not Found
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/precise/edge/binary-amd64/Packages  404  Not Found

It was working few days ago.

**Comment by thaJeztah** [comment] 2017-07-02 07:44
ping @andrewhsu

**Comment by andrewhsu** [comment] 2017-07-03 00:51
@alenkacz Looks like you may be running the `install.sh` script on travis using an Ubuntu Precise image. Ubuntu Precise was [EoL as of 2017-04-28 ](https://wiki.ubuntu.com/Releases) and it was never supported on download.docker.com as a package to install. Perhaps try updating your travis setup to use a supported Ubuntu release like Trusty or Xenial?

**Comment by thaJeztah** [comment] 2017-07-03 01:12
Oh! You're right, I overlooked that. Support for Ubuntu precise (12.04) was removed in Docker 17.05 https://github.com/moby/moby/releases/tag/v17.05.0-ce

closing because this is not a bug, but feel free to comment after

**Closed by thaJeztah** 2017-07-03 01:12 UTC

**Comment by alenkacz** [comment] 2017-07-03 05:13
Oh, I missed that! Thanks

Btw. Maybe it makes sense to alter the install.sh script to communicate this a little bit better? :-)
