### ISSUE TITLE
error response from daemon Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by syscom-it** [moby/moby#36882] opened 2018-04-18 08:31 UTC
Hi

I am getting an error when I type the command - 

sudo docker run hello-world

Please help 

Thanks David

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Error response from daemon: Get https://registry-1.docker.io/v2/ : x509 : certificate signed by unknown authority.**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version 17.03.1-ce```

**Output of `docker info`:**

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am running gns3 on ubuntu version 14.04  Vmware workstation 12

**Comment by thaJeztah** [comment] 2018-04-30 12:47
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. 

The `certificate signed by unknown authority` error may be cause by circumstances in your environment, for example, if you're behind a corporate MITM proxy.

There are various existing issues mentioning this error, and those may provide more information; https://github.com/moby/moby/issues?utf8=✓&q=is%3Aissue+%22certificate+signed+by+unknown+authority%22

**Comment by syscom-it** [comment] 2018-04-30 13:09
Hi 

I am running Ubuntu 14.04 within VMware workstation on windows 10.

Everytime I try the command docker run hello-world I am getting the following error below:

docker: Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority.
See 'docker run --help'.

I am using Docker version 17.03.1-ce

Docker Info below

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: gns3vm
ID: 6HQX:DRIB:HHCH:JGHD:DYZ2:XRKL:4H2R:Z7V5:NHGJ:JVPO:ZA2C:6NBB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment] 2018-04-30 14:54
What do the daemon logs show? Also note that Docker 17.03 has reached end of life a year ago, so I no longer maintained

**Comment by oweson** [comment] 2018-09-18 13:01
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.cloudcheckr.com, cloudcheckr.com, not registry-1.docker.io

**Comment by thaJeztah** [comment] 2018-09-18 16:56
@oweson that looks like an issue in your environment; are you connecting from a company network, and do they use cloudcheckr.com ?


I'll go ahead and close this issue, because this doesn't look like a bug. Feel free to continue the conversation after I closed though

**Closed by thaJeztah** 2018-09-18 16:56 UTC
Labels: area/distribution, status/more-info-needed

**Comment by frak** [comment] 2018-10-10 15:43
I am adding this note here just in case: check your /etc/hosts file for an entry to registry-1.docker.io

I previously had to add an entry to get it to resolve and this is no longer their IP. Doh.

**Comment by pmdbt** [comment] 2020-07-07 05:06
@frak I'm running into this weird error here:

```
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.kneura.com, not registry-1-docker.io
```

Here is my /etc/hosts file:

```
127.0.0.1	localhost
::1		localhost
127.0.1.1	pop-os.localdomain	pop-os
34.228.211.243  registry-1.docker.io
```

What would I have to edit per your comment? Are you saying the 34.228.211.243 address has changed? If so, do you know the current valid one?

**Comment by thaJeztah** [comment] 2020-07-07 08:58
@pmdbt looks like you're connected through a MITM Proxy
