### ISSUE TITLE
How to map uncertain ports

### ISSUE THREAD

**Issue by Ruilkyu** [moby/moby#40241] opened 2019-11-25 03:28 UTC
Question:
When I run a program in docker, but the port exposed by the program is uncertain, how to map can be accessed by the outside world?

**Comment by thaJeztah** [comment] 2019-11-26 13:31
Unfortunately, port-mapping in docker won't be able to assist with that, as it expects the port to map to be specified _before_ the container is started, so if the software inside the container is picking a random port at _runtime_, this won't be possible.

Docker can _assign_ a random port to map (`-p <fixed-port-in-container>` will map the container's port to a port on the host's network interface in the ephemeral port range).

Alternatively, use `--network=host` to have the container run in the host's network stack, but this means that the container does not have its own networking namespace (thus doesn't have its own IP-address, not does it have any networking isolation from the host).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2019-11-26 13:31 UTC
Labels: kind/question

**Comment by Ruilkyu** [comment] 2019-11-27 05:07
Thanks!
