### ISSUE TITLE
Slow docker build

### ISSUE THREAD

**Issue by nick-zh** [moby/moby#36109] opened 2018-01-25 07:14 UTC
For a few weeks now, it seems that my build hangs at the very start
doing docker-compose up --build in verbose mode, gives me the following, then it hangs (30 - 60s):
```
compose.service.build: Building mongodb
compose.cli.verbose_proxy.proxy_callable: docker build <- (pull=False, labels=None, target=None, nocache=False, container_limits={u'memory': None}, cache_from=None, extra_hosts=None, network_mode=None, tag=u'datapoolapi_mongodb', buildargs={}, rm=True, stream=True, path='/home/nick/projects/unity/datapool-api', dockerfile='docker/mongo/Dockerfile', forcerm=False, shmsize=None)
```
I have this for all the containers in my compose, not just mongo, cpu is high while hanging (maybe this is normal though)
Using debian (testing) 4.14.0-3-amd64

**Comment by thaJeztah** [comment] 2018-01-26 00:33
Wonder if this is related to https://github.com/moby/moby/pull/36097 (which relates to recent kernel / linux versions that have patches for [Meltdown and Spectre](https://meltdownattack.com)

Docker 18.02 will have that fix and release candidates are available for that in the "test" channel

**Comment by nick-zh** [comment] 2018-01-26 07:25
@thaJeztah thanks a lot for the hint, i went ahead and added test to my repo and installed docker 18.02.0-ce-rc1, still the same but since this was merged 2 days ago, i am not sure if it is already in the RC

**Comment by thaJeztah** [comment] 2018-01-26 08:33
Thanks for testing; I checked, and it looks like the fix is in 18.02; https://github.com/docker/docker-ce/commits/18.02/components/engine/vendor.conf so it’s likely a different issue then.

Can you reproduce the issue as well if you directly use `docker build` (not using docker compose)?

Output of `docker info` could also be useful (as well as logs that are relevant)

**Comment by nick-zh** [comment] 2018-01-26 09:03
@thaJeztah thx for the input. Very interesting, if i call docker build seperately it is fast as :zap:
let me know if i can provide more info to assist with this.

**Comment by nick-zh** [comment] 2018-01-26 09:54
Ok, so i added a .dockerignore file to exclude dirs form the context and it is a lot faster, overall i still think though, that is is slower in comparison because i never used a .dockerignore before and always included the whole project (which now i get is silly), but i guess it is hard to debug without further investigation what caused this
FYI: i had the same on 1.19.0 RC
I noticed that running container with mounts seems to have gotten slower, but thats probably a seperate issue

**Comment by thaJeztah** [comment] 2018-01-26 15:48
If you’re only having this with Docker compose, then it’s better to open an issue in that issue tracker; https://github.com/docker/compose/issues

**Closed** 2018-01-27 22:52 UTC
Labels: area/builder
