### ISSUE TITLE
`yum update -y` failing in the centos docker image in Docker v17.03.1-ce 

### ISSUE THREAD

**Issue by borntorock** [moby/moby#32345] opened 2017-04-04 10:21 UTC
Output of docker version:
 
```Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64
 Experimental: false

Output of docker info:
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.26 GiB
Name: 10.0.12.171
ID: AZ4O:TCQI:REWZ:HSKW:4QZ7:I3KV:NUYZ:2NP2:VOML:OACI:5U47:PEAP
Docker Root Dir: /mnt2/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 33
 System Time: 2017-04-04T10:13:11.023386767Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

output of sestatus:
```
SELinux status:                 disabled
```

Issue: We first created a centos docker image from this script https://github.com/docker/docker/blob/master/contrib/mkimage-yum.sh, then created a container with this centos docker image built, by simply executing the command:

```
docker run -itd centos:latest bash
```

Now after going inside the container via docker exec and then executing the command:
`yum update -y`

is throwing the below error message:
```
[root@047ab7fa7177 /]# yum update -y
Loaded plugins: fastestmirror
base                                                                                                                                                       | 3.6 kB  00:00:00     
extras                                                                                                                                                     | 3.4 kB  00:00:00     
updates                                                                                                                                                    | 3.4 kB  00:00:00     
(1/4): extras/7/x86_64/primary_db                                                                                                                          | 139 kB  00:00:00     
(2/4): base/7/x86_64/group_gz                                                                                                                              | 155 kB  00:00:02     
(3/4): base/7/x86_64/primary_db                                                                                                                            | 5.6 MB  00:00:04     
(4/4): updates/7/x86_64/primary_db                                                                                                                         | 3.9 MB  00:02:02     
Determining fastest mirrors
 * base: mirror.fibergrid.in
 * extras: mirror.fibergrid.in
 * updates: mirror.fibergrid.in
Resolving Dependencies
--> Running transaction check
---> Package audit.x86_64 0:2.6.5-3.el7 will be updated
---> Package audit.x86_64 0:2.6.5-3.el7_3.1 will be an update
---> Package audit-libs.x86_64 0:2.6.5-3.el7 will be updated
---> Package audit-libs.x86_64 0:2.6.5-3.el7_3.1 will be an update
---> Package bind-libs-lite.x86_64 32:9.9.4-38.el7_3 will be updated
---> Package bind-libs-lite.x86_64 32:9.9.4-38.el7_3.2 will be an update
---> Package bind-license.noarch 32:9.9.4-38.el7_3 will be updated
---> Package bind-license.noarch 32:9.9.4-38.el7_3.2 will be an update
---> Package device-mapper.x86_64 7:1.02.135-1.el7_3.1 will be updated
---> Package device-mapper.x86_64 7:1.02.135-1.el7_3.3 will be an update
---> Package device-mapper-libs.x86_64 7:1.02.135-1.el7_3.1 will be updated
---> Package device-mapper-libs.x86_64 7:1.02.135-1.el7_3.3 will be an update
---> Package firewalld.noarch 0:0.4.3.2-8.el7 will be updated
---> Package firewalld.noarch 0:0.4.3.2-8.1.el7_3.2 will be an update
---> Package firewalld-filesystem.noarch 0:0.4.3.2-8.el7 will be updated
---> Package firewalld-filesystem.noarch 0:0.4.3.2-8.1.el7_3.2 will be an update
---> Package kpartx.x86_64 0:0.4.9-99.el7 will be updated
---> Package kpartx.x86_64 0:0.4.9-99.el7_3.1 will be an update
---> Package libpciaccess.x86_64 0:0.13.4-2.el7 will be updated
---> Package libpciaccess.x86_64 0:0.13.4-3.el7_3 will be an update
---> Package libsemanage.x86_64 0:2.5-4.el7 will be updated
---> Package libsemanage.x86_64 0:2.5-5.1.el7_3 will be an update
---> Package nspr.x86_64 0:4.11.0-1.el7_2 will be updated
---> Package nspr.x86_64 0:4.13.1-1.0.el7_3 will be an update
---> Package nss.x86_64 0:3.21.3-2.el7_3 will be updated
---> Package nss.x86_64 0:3.28.2-1.6.el7_3 will be an update
---> Package nss-sysinit.x86_64 0:3.21.3-2.el7_3 will be updated
---> Package nss-sysinit.x86_64 0:3.28.2-1.6.el7_3 will be an update
---> Package nss-tools.x86_64 0:3.21.3-2.el7_3 will be updated
---> Package nss-tools.x86_64 0:3.28.2-1.6.el7_3 will be an update
---> Package nss-util.x86_64 0:3.21.3-1.1.el7_3 will be updated
---> Package nss-util.x86_64 0:3.28.2-1.1.el7_3 will be an update
---> Package openssh.x86_64 0:6.6.1p1-31.el7 will be updated
---> Package openssh.x86_64 0:6.6.1p1-33.el7_3 will be an update
---> Package openssh-clients.x86_64 0:6.6.1p1-31.el7 will be updated
---> Package openssh-clients.x86_64 0:6.6.1p1-33.el7_3 will be an update
---> Package openssh-server.x86_64 0:6.6.1p1-31.el7 will be updated
---> Package openssh-server.x86_64 0:6.6.1p1-33.el7_3 will be an update
---> Package openssl-libs.x86_64 1:1.0.1e-60.el7 will be updated
---> Package openssl-libs.x86_64 1:1.0.1e-60.el7_3.1 will be an update
---> Package policycoreutils.x86_64 0:2.5-9.el7 will be updated
---> Package policycoreutils.x86_64 0:2.5-11.el7_3 will be an update
---> Package polkit.x86_64 0:0.112-9.el7 will be updated
---> Package polkit.x86_64 0:0.112-11.el7_3 will be an update
---> Package python-firewall.noarch 0:0.4.3.2-8.el7 will be updated
---> Package python-firewall.noarch 0:0.4.3.2-8.1.el7_3.2 will be an update
---> Package python-perf.x86_64 0:3.10.0-514.2.2.el7 will be updated
---> Package python-perf.x86_64 0:3.10.0-514.10.2.el7 will be an update
---> Package selinux-policy.noarch 0:3.13.1-102.el7_3.7 will be updated
---> Package selinux-policy.noarch 0:3.13.1-102.el7_3.16 will be an update
---> Package selinux-policy-targeted.noarch 0:3.13.1-102.el7_3.7 will be updated
---> Package selinux-policy-targeted.noarch 0:3.13.1-102.el7_3.16 will be an update
---> Package systemd.x86_64 0:219-30.el7_3.6 will be updated
---> Package systemd.x86_64 0:219-30.el7_3.7 will be an update
---> Package systemd-libs.x86_64 0:219-30.el7_3.6 will be updated
---> Package systemd-libs.x86_64 0:219-30.el7_3.7 will be an update
---> Package systemd-sysv.x86_64 0:219-30.el7_3.6 will be updated
---> Package systemd-sysv.x86_64 0:219-30.el7_3.7 will be an update
---> Package tzdata.noarch 0:2016j-1.el7 will be updated
---> Package tzdata.noarch 0:2017b-1.el7 will be an update
---> Package xfsprogs.x86_64 0:4.5.0-8.el7 will be updated
---> Package xfsprogs.x86_64 0:4.5.0-9.el7_3 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

 Package                                            Arch                              Version                                            Repository                          Size

Updating:
 audit                                              x86_64                            2.6.5-3.el7_3.1                                    updates                            233 k
 audit-libs                                         x86_64                            2.6.5-3.el7_3.1                                    updates                             85 k
 bind-libs-lite                                     x86_64                            32:9.9.4-38.el7_3.2                                updates                            730 k
 bind-license                                       noarch                            32:9.9.4-38.el7_3.2                                updates                             83 k
 device-mapper                                      x86_64                            7:1.02.135-1.el7_3.3                               updates                            269 k
 device-mapper-libs                                 x86_64                            7:1.02.135-1.el7_3.3                               updates                            333 k
 firewalld                                          noarch                            0.4.3.2-8.1.el7_3.2                                updates                            386 k
 firewalld-filesystem                               noarch                            0.4.3.2-8.1.el7_3.2                                updates                             44 k
 kpartx                                             x86_64                            0.4.9-99.el7_3.1                                   updates                             67 k
 libpciaccess                                       x86_64                            0.13.4-3.el7_3                                     updates                             26 k
 libsemanage                                        x86_64                            2.5-5.1.el7_3                                      updates                            144 k
 nspr                                               x86_64                            4.13.1-1.0.el7_3                                   updates                            126 k
 nss                                                x86_64                            3.28.2-1.6.el7_3                                   updates                            873 k
 nss-sysinit                                        x86_64                            3.28.2-1.6.el7_3                                   updates                             58 k
 nss-tools                                          x86_64                            3.28.2-1.6.el7_3                                   updates                            496 k
 nss-util                                           x86_64                            3.28.2-1.1.el7_3                                   updates                             73 k
 openssh                                            x86_64                            6.6.1p1-33.el7_3                                   updates                            438 k
 openssh-clients                                    x86_64                            6.6.1p1-33.el7_3                                   updates                            642 k
 openssh-server                                     x86_64                            6.6.1p1-33.el7_3                                   updates                            440 k
 openssl-libs                                       x86_64                            1:1.0.1e-60.el7_3.1                                updates                            959 k
 policycoreutils                                    x86_64                            2.5-11.el7_3                                       updates                            841 k
 polkit                                             x86_64                            0.112-11.el7_3                                     updates                            167 k
 python-firewall                                    noarch                            0.4.3.2-8.1.el7_3.2                                updates                            301 k
 python-perf                                        x86_64                            3.10.0-514.10.2.el7                                updates                            4.0 M
 selinux-policy                                     noarch                            3.13.1-102.el7_3.16                                updates                            414 k
 selinux-policy-targeted                            noarch                            3.13.1-102.el7_3.16                                updates                            6.4 M
 systemd                                            x86_64                            219-30.el7_3.7                                     updates                            5.2 M
 systemd-libs                                       x86_64                            219-30.el7_3.7                                     updates                            369 k
 systemd-sysv                                       x86_64                            219-30.el7_3.7                                     updates                             63 k
 tzdata                                             noarch                            2017b-1.el7                                        updates                            443 k
 xfsprogs                                           x86_64                            4.5.0-9.el7_3                                      updates                            895 k

Transaction Summary

Upgrade  31 Packages

Total download size: 25 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
(1/31): audit-libs-2.6.5-3.el7_3.1.x86_64.rpm                                                                                                              |  85 kB  00:00:02     
(2/31): audit-2.6.5-3.el7_3.1.x86_64.rpm                                                                                                                   | 233 kB  00:00:02     
(3/31): bind-license-9.9.4-38.el7_3.2.noarch.rpm                                                                                                           |  83 kB  00:00:00     
(4/31): firewalld-filesystem-0.4.3.2-8.1.el7_3.2.noarch.rpm                                                                                                |  44 kB  00:00:00     
(5/31): kpartx-0.4.9-99.el7_3.1.x86_64.rpm                                                                                                                 |  67 kB  00:00:00     
(6/31): libpciaccess-0.13.4-3.el7_3.x86_64.rpm                                                                                                             |  26 kB  00:00:00     
(7/31): bind-libs-lite-9.9.4-38.el7_3.2.x86_64.rpm                                                                                                         | 730 kB  00:00:00     
(8/31): device-mapper-1.02.135-1.el7_3.3.x86_64.rpm                                                                                                        | 269 kB  00:00:00     
(9/31): nspr-4.13.1-1.0.el7_3.x86_64.rpm                                                                                                                   | 126 kB  00:00:00     
(10/31): libsemanage-2.5-5.1.el7_3.x86_64.rpm                                                                                                              | 144 kB  00:00:00     
(11/31): nss-sysinit-3.28.2-1.6.el7_3.x86_64.rpm                                                                                                           |  58 kB  00:00:00     
(12/31): device-mapper-libs-1.02.135-1.el7_3.3.x86_64.rpm                                                                                                  | 333 kB  00:00:00     
(13/31): nss-3.28.2-1.6.el7_3.x86_64.rpm                                                                                                                   | 873 kB  00:00:00     
(14/31): nss-util-3.28.2-1.1.el7_3.x86_64.rpm                                                                                                              |  73 kB  00:00:00     
(15/31): nss-tools-3.28.2-1.6.el7_3.x86_64.rpm                                                                                                             | 496 kB  00:00:00     
(16/31): openssh-clients-6.6.1p1-33.el7_3.x86_64.rpm                                                                                                       | 642 kB  00:00:00     
(17/31): openssh-6.6.1p1-33.el7_3.x86_64.rpm                                                                                                               | 438 kB  00:00:00     
(18/31): policycoreutils-2.5-11.el7_3.x86_64.rpm                                                                                                           | 841 kB  00:00:00     
(19/31): openssh-server-6.6.1p1-33.el7_3.x86_64.rpm                                                                                                        | 440 kB  00:00:00     
(20/31): python-firewall-0.4.3.2-8.1.el7_3.2.noarch.rpm                                                                                                    | 301 kB  00:00:00     
(21/31): selinux-policy-3.13.1-102.el7_3.16.noarch.rpm                                                                                                     | 414 kB  00:00:00     
(22/31): polkit-0.112-11.el7_3.x86_64.rpm                                                                                                                  | 167 kB  00:00:00     
(23/31): openssl-libs-1.0.1e-60.el7_3.1.x86_64.rpm                                                                                                         | 959 kB  00:00:00     
(24/31): systemd-libs-219-30.el7_3.7.x86_64.rpm                                                                                                            | 369 kB  00:00:00     
(25/31): systemd-sysv-219-30.el7_3.7.x86_64.rpm                                                                                                            |  63 kB  00:00:00     
(26/31): selinux-policy-targeted-3.13.1-102.el7_3.16.noarch.rpm                                                                                            | 6.4 MB  00:00:00     
(27/31): tzdata-2017b-1.el7.noarch.rpm                                                                                                                     | 443 kB  00:00:00     
(28/31): xfsprogs-4.5.0-9.el7_3.x86_64.rpm                                                                                                                 | 895 kB  00:00:00     
(29/31): systemd-219-30.el7_3.7.x86_64.rpm                                                                                                                 | 5.2 MB  00:00:01     
(30/31): firewalld-0.4.3.2-8.1.el7_3.2.noarch.rpm                                                                                                          | 386 kB  00:00:03     
(31/31): python-perf-3.10.0-514.10.2.el7.x86_64.rpm                                                                                                        | 4.0 MB  00:00:04     

Total                                                                                                                                             3.0 MB/s |  25 MB  00:00:08     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : audit-libs-2.6.5-3.el7_3.1.x86_64                                                                                                                             1/62 
  Updating   : 1:openssl-libs-1.0.1e-60.el7_3.1.x86_64                                                                                                                       2/62 
  Updating   : nspr-4.13.1-1.0.el7_3.x86_64                                                                                                                                  3/62 
  Updating   : nss-util-3.28.2-1.1.el7_3.x86_64                                                                                                                              4/62 
  Updating   : systemd-libs-219-30.el7_3.7.x86_64                                                                                                                            5/62 
  Updating   : systemd-219-30.el7_3.7.x86_64                                                                                                                                 6/62 
  Updating   : openssh-6.6.1p1-33.el7_3.x86_64                                                                                                                               7/62 
  Updating   : libsemanage-2.5-5.1.el7_3.x86_64                                                                                                                              8/62 
  Updating   : policycoreutils-2.5-11.el7_3.x86_64                                                                                                                           9/62 
  Updating   : selinux-policy-3.13.1-102.el7_3.16.noarch                                                                                                                    10/62 
  Updating   : systemd-sysv-219-30.el7_3.7.x86_64                                                                                                                           11/62 
  Updating   : 7:device-mapper-libs-1.02.135-1.el7_3.3.x86_64                                                                                                               12/62 
  Updating   : 7:device-mapper-1.02.135-1.el7_3.3.x86_64                                                                                                                    13/62 
  Updating   : nss-sysinit-3.28.2-1.6.el7_3.x86_64                                                                                                                          14/62 
  Updating   : nss-3.28.2-1.6.el7_3.x86_64                                                                                                                                  15/62 
  Updating   : python-firewall-0.4.3.2-8.1.el7_3.2.noarch                                                                                                                   16/62 
  Updating   : 32:bind-license-9.9.4-38.el7_3.2.noarch                                                                                                                      17/62 
  Updating   : firewalld-filesystem-0.4.3.2-8.1.el7_3.2.noarch                                                                                                              18/62 
  Updating   : firewalld-0.4.3.2-8.1.el7_3.2.noarch                                                                                                                         19/62 
  Updating   : 32:bind-libs-lite-9.9.4-38.el7_3.2.x86_64                                                                                                                    20/62 
  Updating   : nss-tools-3.28.2-1.6.el7_3.x86_64                                                                                                                            21/62 
  Updating   : kpartx-0.4.9-99.el7_3.1.x86_64                                                                                                                               22/62 
  Updating   : audit-2.6.5-3.el7_3.1.x86_64                                                                                                                                 23/62 
  Updating   : selinux-policy-targeted-3.13.1-102.el7_3.16.noarch                                                                                                           24/62 
libsemanage.semanage_commit_sandbox: Error while renaming /etc/selinux/targeted/active to /etc/selinux/targeted/previous. (Invalid cross-device link).
/usr/sbin/semodule:  Failed!
  Updating   : openssh-server-6.6.1p1-33.el7_3.x86_64                                                                                                                       25/62 
  Updating   : openssh-clients-6.6.1p1-33.el7_3.x86_64                                                                                                                      26/62 
  Updating   : polkit-0.112-11.el7_3.x86_64                                                                                                                                 27/62 
  Updating   : python-perf-3.10.0-514.10.2.el7.x86_64                                                                                                                       28/62 
  Updating   : xfsprogs-4.5.0-9.el7_3.x86_64                                                                                                                                29/62 
  Updating   : libpciaccess-0.13.4-3.el7_3.x86_64                                                                                                                           30/62 
  Updating   : tzdata-2017b-1.el7.noarch                                                                                                                                    31/62 
  Cleanup    : nss-tools-3.21.3-2.el7_3.x86_64                                                                                                                              32/62 
  Cleanup    : firewalld-0.4.3.2-8.el7.noarch                                                                                                                               33/62 
  Cleanup    : nss-sysinit-3.21.3-2.el7_3.x86_64                                                                                                                            34/62 
  Cleanup    : nss-3.21.3-2.el7_3.x86_64                                                                                                                                    35/62 
  Cleanup    : openssh-server-6.6.1p1-31.el7.x86_64                                                                                                                         36/62 
  Cleanup    : audit-2.6.5-3.el7.x86_64                                                                                                                                     37/62 
  Cleanup    : selinux-policy-targeted-3.13.1-102.el7_3.7.noarch                                                                                                            38/62 
  Cleanup    : selinux-policy-3.13.1-102.el7_3.7.noarch                                                                                                                     39/62 
  Cleanup    : policycoreutils-2.5-9.el7.x86_64                                                                                                                             40/62 
  Cleanup    : openssh-clients-6.6.1p1-31.el7.x86_64                                                                                                                        41/62 
  Cleanup    : openssh-6.6.1p1-31.el7.x86_64                                                                                                                                42/62 
  Cleanup    : polkit-0.112-9.el7.x86_64                                                                                                                                    43/62 
  Cleanup    : 32:bind-libs-lite-9.9.4-38.el7_3.x86_64                                                                                                                      44/62 
  Cleanup    : systemd-sysv-219-30.el7_3.6.x86_64                                                                                                                           45/62 
  Cleanup    : 32:bind-license-9.9.4-38.el7_3.noarch                                                                                                                        46/62 
  Cleanup    : firewalld-filesystem-0.4.3.2-8.el7.noarch                                                                                                                    47/62 
  Cleanup    : python-firewall-0.4.3.2-8.el7.noarch                                                                                                                         48/62 
  Cleanup    : tzdata-2016j-1.el7.noarch                                                                                                                                    49/62 
  Cleanup    : libsemanage-2.5-4.el7.x86_64                                                                                                                                 50/62 
  Cleanup    : nss-util-3.21.3-1.1.el7_3.x86_64                                                                                                                             51/62 
  Cleanup    : kpartx-0.4.9-99.el7.x86_64                                                                                                                                   52/62 
  Cleanup    : 7:device-mapper-1.02.135-1.el7_3.1.x86_64                                                                                                                    53/62 
  Cleanup    : 7:device-mapper-libs-1.02.135-1.el7_3.1.x86_64                                                                                                               54/62 
  Cleanup    : systemd-219-30.el7_3.6.x86_64                                                                                                                                55/62 
  Cleanup    : audit-libs-2.6.5-3.el7.x86_64                                                                                                                                56/62 
  Cleanup    : systemd-libs-219-30.el7_3.6.x86_64                                                                                                                           57/62 
  Cleanup    : nspr-4.11.0-1.el7_2.x86_64                                                                                                                                   58/62 
  Cleanup    : 1:openssl-libs-1.0.1e-60.el7.x86_64                                                                                                                          59/62 
  Cleanup    : python-perf-3.10.0-514.2.2.el7.x86_64                                                                                                                        60/62 
  Cleanup    : xfsprogs-4.5.0-8.el7.x86_64                                                                                                                                  61/62 
  Cleanup    : libpciaccess-0.13.4-2.el7.x86_64                                                                                                                             62/62 


Rpmdb checksum is invalid: dCDPT(pkg checksums): nspr.x86_64 0:4.13.1-1.0.el7_3 - u```
```

The error comes while updating the `selinux-policy-targeted-3.13.1-102.el7_3.16.noarch` package.
                                                                                                          
```
libsemanage.semanage_commit_sandbox: Error while renaming /etc/selinux/targeted/active to /etc/selinux/targeted/previous. (Invalid cross-device link).
/usr/sbin/semodule:  Failed!
```

Yes, we are launching container on centos 7.2 OS. 

Any idea / suggestion on how can we resolve this issue? Let me know, incase you need any other info.

**Comment by borntorock** [comment] 2017-04-04 10:27
@jpetazzo @NathanMcCauley @diogomonica @rhatdan Any idea on the proposed solution to resolve this.

**Comment by thaJeztah** [comment] 2017-04-04 10:37
The problem is here;

```
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
```

There's two things; running `overlay` on a backing filesystem without `d_type` support is cause for errors to occur. See the [Red Hat release notes](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.2_Release_Notes/index.html#technology-preview-file_systems)

> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.



The second issue is that yum can have issues with the overlay storage driver (see https://github.com/docker/docker/issues/10180; https://github.com/docker/docker/issues/10180#issuecomment-264960022). For that to work, you need to have the `yum-plugin-ovl`  package installed in the container, and `plugins=1` is set in your `/etc/yum.conf`

**Comment by thaJeztah** [comment] 2017-04-04 10:39
The "Invalid cross-device link" error is discussed here; https://github.com/docker/docker/issues/25409

**Comment by AkihiroSuda** [comment] 2017-06-02 23:13
Is this issue closable?

**Comment by thaJeztah** [comment] 2017-06-02 23:25
Yes, let's close this one

**Closed by thaJeztah** 2017-06-02 23:25 UTC
Labels: area/storage/overlay, version/17.03
