### ISSUE TITLE
Unorthodox EXPOSE list grinds docker to a halt, kills stdout

### ISSUE THREAD

**Issue by karalabe** [moby/moby#9021] opened 2014-11-07 09:16 UTC
Hi,

  I know this is something very very unorthodox to do, but that is really beyond the point in the context of this report. I was experimenting with exposing large sets of ports from a container. To keep things simple, lets export _all_ the ports.

  If I do this via docker run (i.e. `-expose 1-65535`) then everything works as expected, and perfectly. However, I'd like to be able to do this in a dockerfile (yes, I've seen the numerous issues raised about this). Currently dockerfiles do not support expose ranges, so what I did, was simple generate a list of _all_ ports in the range of 1-65535. I.e. `EXPORT 1 2 3 [...] 65535`

  The weird thing that I've noticed after doing this, is that after each docker build (just tuning the image), the whole docker installation was getting extremely slow. Simply listing the available images (maybe 10) took half a minute. Deleting an image took on the order of many minutes. However, after the unorthodox exposes have been removed from the images, docker was again very fast. I'm not familiar with docker's internals, but I cannot image what could cause a general slowdown in operations that don't even need to touch the exposed ports, just read a config file (i.e. docker images).

  A second bug that I've noticed, is that standard output from such an image was essentially dropped. Even a simple `echo hello` failed to output:

```
> docker run debian echo hello
hello
> docker run debian-exposed echo hello
[no output]
```

The dockerfile used to build debian-exposed is https://gist.github.com/karalabe/451f01479f8848973331#file-dockerfile

  To reiterate, I'm aware that this is not something I should be doing. Nonetheless, it is not something docker should be failing over either :)

Cheers,
  Peter
- OpenSuSE 13.2
-  3.16.6-2-desktop # 1 SMP PREEMPT Mon Oct 20 13:47:22 UTC 2014
- Client version: 1.3.1
  Client API version: 1.15
  Go version (client): go1.3.1
  Git commit (client): 4e9bbfa
  OS/Arch (client): linux/amd64
  Server version: 1.3.1
  Server API version: 1.15
  Go version (server): go1.3.1
  Git commit (server): 4e9bbfa

**Comment by jfrazelle** [comment] 2015-02-26 03:17
@dqminh any update on the fix :D

**Comment by dqminh** [comment] 2015-02-26 12:55
@jfrazelle oops so sorry for that. I completely forgot about it. I will try to rebase, test and open a PR for discussion asap.

**Comment by thaJeztah** [comment] 2023-08-15 14:16
Let em close this one as duplicate of https://github.com/moby/moby/issues/11185, which has more conversation

**Closed by thaJeztah** 2023-08-15 14:16 UTC
Labels: exp/expert, kind/enhancement, area/networking, version/1.3, area/networking/portmapping
