### ISSUE TITLE
When interactively running a shell in a container, tab completion hangs docker process

### ISSUE THREAD

**Issue by mrled** [moby/moby#35000] opened 2017-09-27 19:36 UTC
**Description**

When interactively running a shell in a container, pressing tab **twice** always hangs the Docker process, refusing to accept any more input until I ctrl-c to quick docker.

**Steps to reproduce the issue:**
1. `docker run --rm --interactive --tty alpine:latest /bin/sh`
2. `ls /[TAB] [TAB]`
3. Observe hang

**Describe the results you received:**

Docker hangs, displaying no more output and accepting no more input, until ctrl-c is pressed.

**Describe the results you expected:**

Docker not hanging, and passing the two tab keys to the shell to trigger tab completion of directories in `/`.

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 88
 Running: 9
 Paused: 0
 Stopped: 79
Images: 3273
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: soejo5vmcc4ej96mew13sagm5
 Is Manager: true
 ClusterID: kur4md32rysrf0ecfczlkhgnm
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: 7GTZ:FF4H:5JXH:TFXB:NV7A:Z5A6:5EMO:4IAM:Q6TC:2RJI:GZSV:R5WD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 101
 Goroutines: 231
 System Time: 2017-09-27T19:35:15.2499804Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running Docker CE on Windows 10 and using Hyper-V for the Docker engine container. I've seen the same behavior running from both `powershell` and `cmd` sessions.

**Comment by thaJeztah** [comment] 2017-09-27 19:42
I'm not able to reproduce this on Docker for Mac;

```
$ docker run --rm --interactive --tty alpine:latest /bin/sh
/ # ls /<tab>
.dockerenv  bin/        dev/        etc/        home/       lib/        media/      mnt/        proc/       root/       run/        sbin/       srv/        sys/        tmp/        usr/        var/
```

What shell are you using on the host? Powershell? CMD.exe? something else?

**Comment by mrled** [comment] 2017-09-27 19:47
I'm running in Powershell

**Comment by thaJeztah** [comment] 2017-09-27 20:35
Thanks for testing those

ping @friism @johnstep does this look familiar?

**Comment by friism** [comment] 2017-09-28 13:10
It works fine for me - @mrled are you using Powershell ISE?

![giphy](https://user-images.githubusercontent.com/126104/30968304-bba3a5f0-a413-11e7-99fb-7530ca25abe6.gif)

**Comment by johnstep** [comment] 2017-09-28 15:30
I cannot reproduce the problem either, Windows 10 (16299), same Docker version, cmd or powershell. PowerShell ISE doesn't work at all, in that no output is displayed.

@mrled Does Windows play the Critical Stop sound for you, on the first Tab?

**Comment by mrled** [comment] 2017-09-28 19:10
@friism nope, I'm using regular powershell.exe. However, now that you mention it, I was running that inside ConEmu. Apologies for not mentioning that earlier - ConEmu has become so normal to me that I forget it's third party software that should have been in my bug report.

I just tried from a non-ConEmu Powershell session, and interestingly, double-tab isn't causing a hang, but it is causing the Docker process to simply exit. Like this, where `PS>` indicates a Powershell prompt on my Docker host and `sh>` indicates a shell prompt inside the Docker container.

    PS> docker run --rm --interactive --tty alpine:latest /bin/sh
    sh> ls /[TAB] [TAB]
    PS>

Running this way, there's no kind of message or error or anything, it just exits. I tried in a non-ConEmu cmd session as well, with the same result - no hang, just an immediate exit. To summarize:

* Running from Powershell.exe: immediate exit
* Running from cmd.exe: immediate exit
* Running Powershell from ConEmu: hang until ctrl-c
* Running cmd from ConEmu: hang until ctrl-c

@johnstep Nope, Windows doesn't play any sound for me at all, under any of the sessions mentioned above.

**Comment by mnomansadiq** [comment] 2020-05-20 10:37
I am getting the same problem while using a docker desktop on mac. when I run a ubuntu container and start a shell, using a tab along with commands not working:
docker run --rm --interactive --tty ubuntu:latest /bin/sh

**Comment by thaJeztah** [comment] 2020-05-20 10:39
@mnomansadiq  `/bin/sh` does not do tab completion; try removing `/bin/sh` from the command you're running (to use the default `bash` shell in ubuntu), or replace it with `/bin/bash`

**Comment by thaJeztah** [comment] 2020-05-20 10:40
Looking at the discussion above, I don't think there's a  bug at hand here, so I'll close this ticket

**Closed by thaJeztah** 2020-05-20 10:40 UTC
Labels: platform/windows, version/17.06
