### ISSUE TITLE
Error when inspect image: Error response from daemon: readlink /var/lib/docker/overlay2/l:

### ISSUE THREAD

**Issue by hungnt1** [moby/moby#43178] opened 2022-01-24 02:58 UTC
**Description**

root@localhost:/home/mdt# docker image inspect {{image}}
[]
Error response from daemon: readlink /var/lib/docker/overlay2/l: invalid argument

root@localhost:/var/lib/docker/overlay2# docker image pull {{image}}
{{version}}: Pulling from ...
Digest: ....
Status: Image is up to date for {{image}}
{{image}}

**Steps to reproduce the issue:**
1. docker image inspect 
2. pull image and it say "Image is up to date"
3. pull new image and can inspect new image

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:47 2020
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:44 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 nvidia:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.140-tegra
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.863GiB
 Name: localhost
 ID: VND4:KWIF:RRIL:2M7V:XLUU:M2MU:DNES:EW4P:I64V:2YF5:QVXQ:4QEC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support

```

**Run on Jetson Nano Develop Kit**

**Comment by thaJeztah** [comment] 2023-10-13 22:00
let me close as duplicate of https://github.com/moby/moby/issues/35747

**Closed by thaJeztah** 2023-10-13 22:00 UTC
Labels: area/storage/overlay, platform/arm
