### ISSUE TITLE
service create kills the task when the image has HEALTHCHECK and it takes more than 25 seconds to start

### ISSUE THREAD

**Issue by bvis** [moby/moby#26498] opened 2016-09-12 17:37 UTC
I'm trying to launch a service based on Mysql and it initially takes more than 25 seconds to be ready, as it initialises databases structures or starts to replicate from a master.

To be sure that the tasks are not added to the IPVS until it is ready to serve consistent data I've added a HEALTHCHECK command to the image to be sure about it.

When I launch it as a container (docker run ...) I see it works perfectly. But when I launch it as a service (docker service create...) it seems that is docker who's killing the service at 25th second after launch the task.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:28:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 14
 Running: 3
 Paused: 0
 Stopped: 11
Images: 44
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 146
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rexray
 Network: bridge overlay host null
Swarm: active
 NodeID: akovrjb6nszez5yr11ym12fw0
 Is Manager: true
 ClusterID: 5bwdhzno4jlg4dow1t7y8u8hg
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.24.33
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.796 GiB
Name: swarm-cluster-1
ID: 7ORQ:S5FO:KMLZ:VT3P:PGB6:MB64:BTTF:SQMS:Q4CM:5Y7X:H3VP:ASSS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Test swarm cluster created in AWS using docker-machine.

**Steps to reproduce the issue:**

I've created a simple image for doing it. As docker hub still does not support HEALTHCHECK command I'm providing a repo.

It just has a health check script that defines the task as stable once it has more than 30 seconds from its creation.

```
git clone git@github.com:bvis/swarm-healthcheck-test.git
cd swarm-healthcheck-test
docker build -t swarm-healthcheck-test .
```

**Describe the results you received:**
When you launch it as a service:

```
docker service create --name test swarm-healthcheck-test
cjqegebcn1g44qtvjrs8ujiq5
watch -n 1 "docker service ps test"
ID                         NAME    IMAGE              NODE                 DESIRED STATE  CURRENT STATE             ERROR
7qljdhtxfc4744zfbczrkwwuj  test.1  swarm-healthcheck-test  swarm-cluster-1  Running        Starting 1 seconds ago
...
ID                         NAME    IMAGE              NODE                 DESIRED STATE  CURRENT STATE             ERROR
7qljdhtxfc4744zfbczrkwwuj  test.1  swarm-healthcheck-test  swarm-cluster-1  Running        Starting 19 seconds ago
...
ID                         NAME        IMAGE              NODE                 DESIRED STATE  CURRENT STATE         ERROR
5inlhe2qrwcryn3dioz4mixpe  test.1      swarm-healthcheck-test  swarm-cluster-1  Ready          Ready 1 seconds ago
89wriwa3a7zomv0tybd9tkr9v   \_ test.1  swarm-healthcheck-test  swarm-cluster-1  Shutdown       Failed 3 seconds ago  "task: non-zero exit (137): do"
```

And I've seen that it always happens on 25th second.

**Describe the results you expected:**
I expect to not to kill the task at 25th second, allowing to define a timeout as a parameter when creating the service or just don't kill it at all.

It works as expected when I launch the same image as a container.

```
docker run -d --name test swarm-healthcheck-test
watch -n 1 "docker ps | grep swarm-healthcheck" 

3689d7faaead  swarm-healthcheck-test  "/bin/sh -c /start.sh"   11 seconds ago      Up 11 seconds (health: starting) test
...
ce7f471f224b  swarm-healthcheck-test  "/bin/sh -c /start.sh"   16 seconds ago      Up 15 seconds (unhealthy)        test
...
ce7f471f224b  swarm-healthcheck-test  "/bin/sh -c /start.sh"   30 seconds ago      Up 29 seconds (unhealthy)        test
...
ce7f471f224b  swarm-healthcheck-test  "/bin/sh -c /start.sh"   About a minute ago  Up About a minute (healthy)      test
```

It works as expected!

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens always!

**Comment by cpuguy83** [comment] 2016-09-12 18:14
Unfortunately swarm doesn't support adjusting healthcheck values at runtime, however you can set these in the image... `HEALTHCHECK [opts] CMD ...`
Where `[opts]` are:

- `--interval =DURATION` (default: 30s)
- `--timeout=DURATION` (default: 30s)
- `--retries=N` (default: 3)

**Comment by bvis** [comment] 2016-09-12 20:59
Hi @cpuguy83, I think it's not related with this.

As you may see in the sample image I provided, the HEALTHCHECK instruction is already providing these values:

```
HEALTHCHECK --interval=5s --timeout=1s \
  CMD /health-check.sh
```
And they are not being affected by the observed behaviour when doing the "service create..."

**Comment by joskfg** [comment] 2016-09-13 10:05
Testing this issue I found a workaround. 

The problem is that the behaviour is not consistent between `docker run` and `docker swarm`. While in docker it uses `HEALTCHECK` to detect the Running point and after that it is used to mark as unhealthy and kill the container, in docker swarm it is used from the beginning to kill the container, so when `HEALTHCHECK` is repeated 3 times (default) without success, it marks the container to be killed.

The workaround is easy, define something like:
```
HEALTHCHECK --interval=5s --timeout=1s --retries=20 \
	CMD /health-check.sh
```
It increases a lot the amount of retries but you will be able to initialize it and the `HEACLTHCHECK` will continue working.

**Comment by bvis** [comment] 2016-09-13 10:42
Yes, but as you say this enforces me to define a policy that could allow me to start the service, but this health check policy is not correct when the service is running.

One possible option would be to apply another option for the starting status. For example:

    --starting-timeout=DURATION

In my example it could be something like:

```
HEALTHCHECK --interval=5s --timeout=1s --retries=3 --starting-timeout=600s \
    CMD /health-check.sh
```
This would allow me to start the service or scale it, and give 10 minutes to the new mysql slave to be up to date with the replication data. Once the slave is on Running state, then the current health check policy is applied.

**Comment by cpuguy83** [comment] 2016-09-13 14:16
@bvis How is your healthcheck setup?
If it's still provisioning you can use exit code 2 and docker will treat that as "starting" rather than "unhealthy"

**Comment by bvis** [comment] 2016-09-13 21:10
Before any change:

**Dockerfile**
```docker
FROM alpine:3.4

COPY health-check.sh /health-check.sh
COPY start.sh /start.sh

ENTRYPOINT /start.sh

HEALTHCHECK --interval=5s --timeout=1s \
  CMD /health-check.sh
```

**start.sh** (just an infinite loop)
```bash
#!/bin/sh

touch /init.pid

while :
do
  echo "."
  sleep 1
done
```

**health-check.sh**
```bash
#!/bin/sh

TTL=30

LAUNCHED=$(stat -c %Y /init.pid)
CURRENT=$(date +%s)

ALIVE=$(expr $CURRENT - $LAUNCHED)

if [ $ALIVE -lt $TTL ]; then
  exit 1
else
  exit 0
fi
```

 I'll show you more info to compare the output when the image is running as a service or as a container:

```
docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                            PORTS               NAMES
1c40b3ea7132        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   5 seconds ago       Up 3 seconds (health: starting)                       test.1.288amqasgupy0636uirosh0k3
7a0e6be4d554        swarm-healthcheck-test          "/bin/sh -c /start.sh"   5 seconds ago       Up 5 seconds (health: starting)                       test
docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                             PORTS               NAMES
1c40b3ea7132        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   15 seconds ago      Up 13 seconds (health: starting)                       test.1.288amqasgupy0636uirosh0k3
7a0e6be4d554        swarm-healthcheck-test          "/bin/sh -c /start.sh"   15 seconds ago      Up 15 seconds (unhealthy)                              test
docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
1c40b3ea7132        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   23 seconds ago      Up 21 seconds (unhealthy)                       test.1.288amqasgupy0636uirosh0k3
7a0e6be4d554        swarm-healthcheck-test          "/bin/sh -c /start.sh"   23 seconds ago      Up 22 seconds (unhealthy)                       test
docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
1c40b3ea7132        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   25 seconds ago      Up 23 seconds (unhealthy)                       test.1.288amqasgupy0636uirosh0k3
7a0e6be4d554        swarm-healthcheck-test          "/bin/sh -c /start.sh"   25 seconds ago      Up 25 seconds (unhealthy)                       test
docker ps --filter name=test
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      PORTS               NAMES
7a0e6be4d554        swarm-healthcheck-test   "/bin/sh -c /start.sh"   28 seconds ago      Up 27 seconds (unhealthy)                       test
docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                            PORTS               NAMES
fcfc464f0bbd        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   6 seconds ago       Up 3 seconds (health: starting)                       test.1.1vd5vixcf8gutgvh5uecvky1p
7a0e6be4d554        swarm-healthcheck-test          "/bin/sh -c /start.sh"   36 seconds ago      Up 36 seconds (healthy)                               test
```

@cpuguy83, I have tried your approach. It sounds a bit of a hack because in the docs it says:

> The command’s exit status indicates the health status of the container. The possible values are:

> 0: success - the container is healthy and ready for use
> 1: unhealthy - the container is not working correctly
> *2: reserved - do not use this exit code*

After change the exit code from 0 to 2 in the "if" in my health-check.sh the behaviour has been:

```
docker service create --name test swarm-healthcheck-test && docker run -d --name test swarm-healthcheck-test
2v9200ewyzyhf0d3x6ofilaxn
eba5c99b54c121571544250d9e2fd651a2540f82d9c9935ae539db4598e9f35e
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                            PORTS               NAMES
14c700f1948c        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   6 seconds ago       Up 5 seconds (health: starting)                       test.1.d3ztsykvqeiqu61t9r1a6hy2c
eba5c99b54c1        swarm-healthcheck-test          "/bin/sh -c /start.sh"   9 seconds ago       Up 7 seconds (health: starting)                       test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                             PORTS               NAMES
14c700f1948c        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   14 seconds ago      Up 13 seconds (health: starting)                       test.1.d3ztsykvqeiqu61t9r1a6hy2c
eba5c99b54c1        swarm-healthcheck-test          "/bin/sh -c /start.sh"   17 seconds ago      Up 16 seconds (unhealthy)                              test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
14c700f1948c        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   19 seconds ago      Up 17 seconds (unhealthy)                       test.1.d3ztsykvqeiqu61t9r1a6hy2c
eba5c99b54c1        swarm-healthcheck-test          "/bin/sh -c /start.sh"   22 seconds ago      Up 20 seconds (unhealthy)                       test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
14c700f1948c        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   20 seconds ago      Up 19 seconds (unhealthy)                       test.1.d3ztsykvqeiqu61t9r1a6hy2c
eba5c99b54c1        swarm-healthcheck-test          "/bin/sh -c /start.sh"   23 seconds ago      Up 22 seconds (unhealthy)                       test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
14c700f1948c        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   24 seconds ago      Up 22 seconds (unhealthy)                       test.1.d3ztsykvqeiqu61t9r1a6hy2c
eba5c99b54c1        swarm-healthcheck-test          "/bin/sh -c /start.sh"   27 seconds ago      Up 25 seconds (unhealthy)                       test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
14c700f1948c        swarm-healthcheck-test:latest   "/bin/sh -c /start.sh"   25 seconds ago      Up 24 seconds (unhealthy)                       test.1.d3ztsykvqeiqu61t9r1a6hy2c
eba5c99b54c1        swarm-healthcheck-test          "/bin/sh -c /start.sh"   28 seconds ago      Up 26 seconds (unhealthy)                       test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      PORTS               NAMES
eba5c99b54c1        swarm-healthcheck-test   "/bin/sh -c /start.sh"   29 seconds ago      Up 27 seconds (unhealthy)                       test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      PORTS               NAMES
eba5c99b54c1        swarm-healthcheck-test   "/bin/sh -c /start.sh"   31 seconds ago      Up 30 seconds (unhealthy)                       test
➜  ~ docker ps --filter name=test
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                    PORTS               NAMES
eba5c99b54c1        swarm-healthcheck-test   "/bin/sh -c /start.sh"   34 seconds ago      Up 32 seconds (healthy)                       test
```
It is not a consistent behaviour yet. :(

**Comment by cpuguy83** [comment] 2016-09-13 21:12
Oh maybe we took out exit code 2... I don't remember.

**Comment by bvis** [comment] 2016-10-27 23:32
Any idea about when this could be fixed?

**Comment by vdemeester** [comment] 2016-10-27 23:35
@cpuguy83 I think we did :sweat_smile: 
@bvis I think https://github.com/docker/docker/pull/27369 should fix this as you will be able to specify the timeout with `--health-timeout` when creating (or updating a service).

**Comment by cpuguy83** [comment] 2016-10-27 23:36
I don't think it really fixes it since we really need a grace period for startup which does not apply the the normal case, only startup.

**Comment by thaJeztah** [comment] 2016-10-29 00:34
ping @aaronlehmann

**Comment by aaronlehmann** [comment] 2016-10-31 17:11
I remember we originally allowed the health check command to return an indication that the application was starting up, and a different grace period should be applied.

This was removed before release for reasons that aren't clear to me.

**Comment by yongtang** [comment] 2016-11-02 16:22
See #24396 about the health state discussion. Also #26664 and #26673 are related.

**Comment by bvis** [comment] 2016-11-04 10:58
@yongtang yes, I'm aware of those tasks. But I don't know if this will be solved at some _near_ future. :(

**Comment by teohhanhui** [comment] 2017-03-31 05:27
So what's the workaround for now? Or is HEALTHCHECK effectively unusable with Swarm Mode?

**Comment by teohhanhui** [comment] 2017-03-31 07:06
So, if I understand correctly, #28938 will provide a workaround? :smile:

**Comment by thaJeztah** [comment] 2017-05-16 11:29
This issue should be resolved in Docker 17.05 with the introduction of `--health-start-period` (and `HEALTHCHECK --start-period` when defined in a Dockerfile), through this pull request: https://github.com/moby/moby/pull/28938.

I wrote up some simple examples to illustrate the functionality; https://github.com/moby/moby/pull/28938#issuecomment-301736698

**Closed by thaJeztah** 2017-05-16 11:29 UTC
Labels: area/swarm, kind/bug, version/1.12

**Comment by bvis** [comment] 2017-05-17 08:24
Thanks @thaJeztah ,
I've added the new flag to my sample image I created to reproduce the problem and it works as expected.
It seems to cover my use case. 👍  Thanks again.

**Comment by thaJeztah** [comment] 2017-05-17 08:43
Perfect; good to hear!
