### ISSUE TITLE
Dockerfile with comment on `FROM` line: "FROM requires either one or three arguments"

### ISSUE THREAD

**Issue by asottile** [moby/moby#36225] opened 2018-02-06 23:21 UTC
**Description**

A dockerfile cannot currently have a comment on a `FROM` line

**Steps to reproduce the issue:**
1. Make a dockerfile as follows:

```dockerfile
FROM ubuntu:xenial  # useful comment here
```
2. `docker build -t test .`

**Describe the results you received:**

```console
$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Error response from daemon: Dockerfile parse error line 1: FROM requires either one or three arguments
```

**Describe the results you expected:**

```
$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM ubuntu:xenial
 ---> 20c44cd7596f
Successfully built 20c44cd7596f
Successfully tagged test:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

```console
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```console
$ docker info
Containers: 27
 Running: 0
 Paused: 0
 Stopped: 27
Images: 36
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: asottile-VirtualBox
ID: MCDD:BXAL:Y4PM:SIA7:I73R:W3F6:C4IY:ZEP4:K44W:XLYA:USI2:FAMT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox, though I don't think it matters

**Comment by thaJeztah** [comment] 2018-02-06 23:46
Correct; comments in Dockerfiles can only be prefixed with white-space, but won't be seen as comment otherwise;

https://docs.docker.com/engine/reference/builder/#format

> Docker treats lines that begin with `#` as a comment, unless the line is a valid parser directive. A `#` marker anywhere else in a line is treated as an argument.


I'll close this issue because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-02-06 23:46 UTC
Labels: area/builder

**Comment by asottile** [comment] 2018-02-06 23:50
Ah perhaps confusing because this is valid:

```dockerfile
RUN echo hi # comment here
```

but that's due to the shell.

**Comment by thaJeztah** [comment] 2018-02-07 00:12
Correct, yes; anything after the `RUN` is handled by the shell, and in that case it's the shell treating it as a comment.

The mix of `Dockerfile` syntax with `shell` syntax is sometimes a bit confusing, and you're not the first being confused by that 😅
