### ISSUE TITLE
docker build fails with multi-stage and --pull

### ISSUE THREAD

**Issue by danielpanteleit** [moby/moby#33946] opened 2017-07-04 14:45 UTC
**Description**

**Steps to reproduce the issue:**
1. Dockerfile
```
FROM alpine as stage1

RUN echo "hello" > somefile

FROM alpine          

COPY --from=stage1 /somefile /

CMD cat /somefile
```
2. docker build --pull .

**Describe the results you received:**

```
Step 4/5 : COPY --from=stage1 /somefile /
invalid from flag value stage1: repository sha256 not found: does not exist or no pull access
```

**Describe the results you expected:**

The same result as without using `--pull`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 267
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 234
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: AKCO:4QMB:PGMG:SMFB:VWG5:MOED:VKB6:L2U6:EOJ4:E5C6:W6JN:4ENE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2017-07-04T14:43:52.523003135Z
 EventsListeners: 1
Http Proxy: ...
Https Proxy: ...
No Proxy: ...
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ekristen** [comment] 2017-07-05 03:03
I can confirm this bug.

**Comment by ekristen** [comment] 2017-07-05 22:39
@tonistiig since you did the original PR i thought I'd mention you on this.

**Comment by thaJeztah** [comment] 2017-07-13 09:45
This was reported in https://github.com/docker/for-mac/issues/1751, and is fixed on master through https://github.com/moby/moby/pull/33735

That fix will be backported to docker 17.06.1, which is worked on, and should be available soon

Closing this issue because this is already fixed, but thanks again for reporting; also feel free to continue the conversation :+1:

**Closed by thaJeztah** 2017-07-13 09:45 UTC
Labels: area/builder, version/17.06

**Comment by JackBurdick** [comment] 2017-07-19 18:27
I'm using the edge build for windows and am seeing this when building multistage images using the golang client. (Version 17.06.1-ce-rc1-win20 (12818))

The output I receive is ~;
`{"errorDetail":{"message":"invalid from flag value build-env: repository sha256 not found: does not exist or no pull access"},"error":"invalid from flag value build-env: repository sha256 not found: does not exist or no pull access"}`

Is there a workaround to use for now?   I know the below example isn't possible but is there anywhere we could discard the `sha256:` portion, I'm not familiar with how/where the `build-env` is parsed.
`COPY --from=build-env[7:] /src/goapp /app/` instead of `COPY --from=build-env /src/goapp /app/`

**Comment by thaJeztah** [comment] 2017-07-19 18:30
@JackBurdick no, there's no workaround, you can see the changes required to fix it in the pull request; https://github.com/moby/moby/pull/33735

**Comment by tonistiigi** [comment] 2017-07-19 18:32
@JackBurdick are you using `build --pull`? This issues only applies when that option is used.

**Comment by JackBurdick** [comment] 2017-07-19 18:47
No, well, actually I'm not entirely sure what's happening under the hood -- sorry.

I'm using the function found [here](https://godoc.org/github.com/docker/engine-api/client#Client.ImageBuild) -- everything goes fine until it attempts to COPY from the build-env -- where I get the following error;
`{"stream":"Step 6/8 : COPY --from=build-env /src/goapp /app/\n"}
{"errorDetail":{"message":"invalid from flag value build-env: repository sha256 not found: does not exist or no pull access"},"error":"invalid from flag value build-env: repository sha256 not found: does not exist or no pull access"}`

I'm looking at the mentioned PR -- but it looks like I already have the update on my local machine.

I'm not sure this makes sense, but on [line ~200](https://github.com/moby/moby/pull/33735/files#diff-77aa50fa42bcdf6c3bedc962a396b6ea) of `<..>\go\src\github.com\docker\docker\builder\dockerfile\dispatchers.go`, what if I added a LeftTrim to remove the sha256:, if that's even the issue?  Something like;
`imageRefOrID := fromFlag.Value
imageRefOrID = strings.TrimLeft(imageRefOrID, "sha256")
imageRefOrID = strings.TrimLeft(imageRefOrID, ":")`

Thank you for the prompt response!

**Comment by tonistiigi** [comment] 2017-07-19 19:11
If you are not setting `PullParent` to `true` in https://godoc.org/github.com/docker/engine-api/types#ImageBuildOptions then this might be something else. Please create a new issue then with a reproducing `Dockerfile` and version information. `17.06.1-ce-rc1` doesn't have that fix that was linked yet unfortunately, but it should be in final version/next rc.

Removing the `sha256:` is not a correct solution. `sha256:xxx` is a valid image ID but we should never pull by image ID, especially if the `build-env` is a local build stage.

**Comment by JackBurdick** [comment] 2017-07-19 19:27
@tonistiigi That was it!

Thank you for your help and the background information -- I had set `{PullParent:     true}`.  Removing this solved my issue and the image is now being built.

**Comment by sztwiorok** [comment] 2017-11-23 11:58
I have the same problem. 
Could someone tell me if I can use multi-stage build with --pull flag?
If I cannot use it this way, please explain why.

Thanks in advance!

**Comment by mmariani** [comment] 2017-11-23 12:47
This was fixed in Docker a few months ago.

**Comment by eliasbrange** [comment] 2018-06-14 12:28
This seems to be fixed when using multi stage builds in a single Dockerfile, but not when using multiple files. 

If I build an image locally from one file and name it `local-image` and then uses `COPY --from=local-image` it tries to force pull that image, which of course won't work. Doing mutliple stages in the same file with e.g. `FROM ... AS local-image` then it works.
