### ISSUE TITLE
"docker service logs" should be sorted by timestamp

### ISSUE THREAD

**Issue by shkrid** [moby/moby#33866] opened 2017-06-28 21:07 UTC
**Description**
`docker service logs` should be sorted by timestamp

**Describe the results you received:**
```
$ docker service logs swarm_gui --tail 20 --timestamps
2017-06-28T20:01:48.116581906Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info it worked if it ends with ok
2017-06-28T20:08:07.423422090Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info it worked if it ends with ok
2017-06-28T20:06:25.835096627Z swarm_gui.2.lozliiv26zw3@moby    | npm info it worked if it ends with ok
2017-06-28T20:01:48.116804870Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info using npm@2.14.4
2017-06-28T20:06:25.836041305Z swarm_gui.2.lozliiv26zw3@moby    | npm info using npm@2.14.4
2017-06-28T20:01:48.117112016Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info using node@v4.1.2
2017-06-28T20:08:07.424101516Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info using npm@2.14.4
2017-06-28T20:08:07.424317881Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info using node@v4.1.2
2017-06-28T20:06:25.836671164Z swarm_gui.2.lozliiv26zw3@moby    | npm info using node@v4.1.2
2017-06-28T20:01:48.300047887Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info prestart swarmVisualizer@0.0.1
2017-06-28T20:01:48.305296428Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info start swarmVisualizer@0.0.1
2017-06-28T20:08:07.617807278Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info prestart swarmVisualizer@0.0.1
2017-06-28T20:06:26.161040235Z swarm_gui.2.lozliiv26zw3@moby    | npm info prestart swarmVisualizer@0.0.1
2017-06-28T20:06:26.168182136Z swarm_gui.2.lozliiv26zw3@moby    | npm info start swarmVisualizer@0.0.1
2017-06-28T20:01:48.306771930Z swarm_gui.1.mwsnmqyifo5g@moby    |
2017-06-28T20:08:07.622771968Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info start swarmVisualizer@0.0.1
2017-06-28T20:08:07.624874160Z swarm_gui.3.z24pi5y9jpfx@moby    |
2017-06-28T20:06:26.170042176Z swarm_gui.2.lozliiv26zw3@moby    |
2017-06-28T20:01:48.306806027Z swarm_gui.1.mwsnmqyifo5g@moby    | > swarmVisualizer@0.0.1 start /app
2017-06-28T20:01:48.306810617Z swarm_gui.1.mwsnmqyifo5g@moby    | > node server.js
2017-06-28T20:01:48.306813068Z swarm_gui.1.mwsnmqyifo5g@moby    |
2017-06-28T20:08:07.624928888Z swarm_gui.3.z24pi5y9jpfx@moby    | > swarmVisualizer@0.0.1 start /app
2017-06-28T20:06:26.170084612Z swarm_gui.2.lozliiv26zw3@moby    | > swarmVisualizer@0.0.1 start /app
2017-06-28T20:08:07.624934776Z swarm_gui.3.z24pi5y9jpfx@moby    | > node server.js
2017-06-28T20:01:48.594351091Z swarm_gui.1.mwsnmqyifo5g@moby    | undefined
2017-06-28T20:08:07.624937193Z swarm_gui.3.z24pi5y9jpfx@moby    |
2017-06-28T20:06:26.170088874Z swarm_gui.2.lozliiv26zw3@moby    | > node server.js
2017-06-28T20:06:26.170091237Z swarm_gui.2.lozliiv26zw3@moby    |
2017-06-28T20:08:07.975379275Z swarm_gui.3.z24pi5y9jpfx@moby    | undefined
2017-06-28T20:06:26.493911257Z swarm_gui.2.lozliiv26zw3@moby    | undefined
```
**Describe the results you expected:**
```
$ docker service logs swarm_gui --tail 20 --timestamps
2017-06-28T20:01:48.116581906Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info it worked if it ends with ok
2017-06-28T20:01:48.116804870Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info using npm@2.14.4
2017-06-28T20:01:48.117112016Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info using node@v4.1.2
2017-06-28T20:01:48.300047887Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info prestart swarmVisualizer@0.0.1
2017-06-28T20:01:48.305296428Z swarm_gui.1.mwsnmqyifo5g@moby    | npm info start swarmVisualizer@0.0.1
2017-06-28T20:01:48.306771930Z swarm_gui.1.mwsnmqyifo5g@moby    |
2017-06-28T20:01:48.306806027Z swarm_gui.1.mwsnmqyifo5g@moby    | > swarmVisualizer@0.0.1 start /app
2017-06-28T20:01:48.306810617Z swarm_gui.1.mwsnmqyifo5g@moby    | > node server.js
2017-06-28T20:01:48.306813068Z swarm_gui.1.mwsnmqyifo5g@moby    |
2017-06-28T20:01:48.594351091Z swarm_gui.1.mwsnmqyifo5g@moby    | undefined
...
2017-06-28T20:06:25.835096627Z swarm_gui.2.lozliiv26zw3@moby    | npm info it worked if it ends with ok
2017-06-28T20:06:25.836041305Z swarm_gui.2.lozliiv26zw3@moby    | npm info using npm@2.14.4
2017-06-28T20:06:25.836671164Z swarm_gui.2.lozliiv26zw3@moby    | npm info using node@v4.1.2
2017-06-28T20:06:26.161040235Z swarm_gui.2.lozliiv26zw3@moby    | npm info prestart swarmVisualizer@0.0.1
2017-06-28T20:06:26.168182136Z swarm_gui.2.lozliiv26zw3@moby    | npm info start swarmVisualizer@0.0.1
2017-06-28T20:06:26.170042176Z swarm_gui.2.lozliiv26zw3@moby    |
2017-06-28T20:06:26.170084612Z swarm_gui.2.lozliiv26zw3@moby    | > swarmVisualizer@0.0.1 start /app
2017-06-28T20:06:26.170088874Z swarm_gui.2.lozliiv26zw3@moby    | > node server.js
2017-06-28T20:06:26.170091237Z swarm_gui.2.lozliiv26zw3@moby    |
2017-06-28T20:06:26.493911257Z swarm_gui.2.lozliiv26zw3@moby    | undefined
...
2017-06-28T20:08:07.423422090Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info it worked if it ends with ok
2017-06-28T20:08:07.424101516Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info using npm@2.14.4
2017-06-28T20:08:07.424317881Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info using node@v4.1.2
2017-06-28T20:08:07.617807278Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info prestart swarmVisualizer@0.0.1
2017-06-28T20:08:07.622771968Z swarm_gui.3.z24pi5y9jpfx@moby    | npm info start swarmVisualizer@0.0.1
2017-06-28T20:08:07.624874160Z swarm_gui.3.z24pi5y9jpfx@moby    |
2017-06-28T20:08:07.624928888Z swarm_gui.3.z24pi5y9jpfx@moby    | > swarmVisualizer@0.0.1 start /app
2017-06-28T20:08:07.624934776Z swarm_gui.3.z24pi5y9jpfx@moby    | > node server.js
2017-06-28T20:08:07.624937193Z swarm_gui.3.z24pi5y9jpfx@moby    |
2017-06-28T20:08:07.975379275Z swarm_gui.3.z24pi5y9jpfx@moby    | undefined
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 38
 Running: 3
 Paused: 0
 Stopped: 35
Images: 130
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 415
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 86pxfphstvmoffw6q9mo98r8k
 Is Manager: true
 ClusterID: x36csyrrl8vay1zwrjfn9blm3
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  172.17.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: TUZX:CVMS:RV4M:QM5Y:QVXT:7ZY3:LP4I:4WV5:TEOW:2C4C:F3H5:XI2K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 61
 Goroutines: 205
 System Time: 2017-06-28T20:25:38.558095597Z
 EventsListeners: 4
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker-for-mac

**Comment by thaJeztah** [comment] 2017-06-28 21:54
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/33673, so I'll close this one to prevent the discussion from diverging. Please continue the discussion on the other issue 👍

**Closed by thaJeztah** 2017-06-28 21:54 UTC
Labels: area/swarm, version/17.06
