### ISSUE TITLE
Docker swarm need  `start node` command 

### ISSUE THREAD

**Issue by eromoe** [moby/moby#35740] opened 2017-12-08 02:17 UTC
Hello,

I don't know why, but I find two swarm nodes status are down and I can't create service on `Down` node: 

```
➜  /root docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
h5kvzzs28gng3js6hv4d1z8km *   node-1              Ready               Active              Leader
2sim5rgb3xjzt0ngxiu7e2z78     node-2              Down                Active
qprz18g07e4ibs6q484p3omqx     node-3              Down                Active
```

Both  `docker swarm` and `docker node` don't provide a command to start down node .

**Comment by thaJeztah** [comment] 2017-12-08 02:27
`nodes` are the daemons running on a machine, not the machine itself; the `Down` state indicates that the manager / current node was not able to connect with the other node; this may be due to a networking issue, or the other machine being physically down.

The manager does not control the "state" of the other nodes (i.e., it cannot (re)start machines or daemons).

I notice that the `STATUS` column is not mentioned in the documentation; https://docs.docker.com/engine/swarm/manage-nodes/#list-nodes perhaps you can open an issue for that in the documentation issue tracker? You can use this link to open an issue for that; https://github.com/docker/docker.github.io/issues/new?assignee=mistyhacks&body=File:%20[engine/swarm/manage-nodes.md](https://docs.docker.com/engine/swarm/manage-nodes/),%20CC%20@mistyhacks


I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-12-08 02:27 UTC
Labels: area/swarm
