### ISSUE TITLE
Forward TERM variable to exec env

### ISSUE THREAD

**Issue by freesteph** [moby/moby#47029] opened 2024-01-05 13:41 UTC
### Description

Docker sets the `TERM` variable to `xterm`. In some embed environments, `TERM=dumb` is set in the host, which needs to be forwarded into the container otherwise the display might be scrambled, etc.

A more precise comment on the relevant pull request: https://github.com/moby/moby/pull/26461/files#r95084867

### Reproduce

1. `export TERM=dumb`;
2. `docker run -it alpine sh`
3. `env | grep "TERM"`

The value of `TERM` is now `xterm`.

### Expected behavior

Docker should try and use the existing `TERM` value, in this case `dumb`. Or maybe just the `dumb` value if it's set, I'm not sure how lax it should be.

### docker version

```bash
Docker version 24.0.7, build afdd53b
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     /Users/steph/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     /Users/steph/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/steph/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/steph/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     /Users/steph/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     /Users/steph/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/steph/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/steph/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/steph/.docker/cli-plugins/docker-scout

Server:
 Containers: 19
  Running: 5
  Paused: 0
  Stopped: 14
 Images: 40
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.5.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.663GiB
 Name: docker-desktop
 ID: 1acf2a23-42d5-4b07-9600-038408ecf200
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2024-01-05 14:05
This looks like a duplicate of https://github.com/moby/moby/issues/42323

Containers (and exec) by default don't inherit environment-variables from the host, as they're their own environment. ISTR `xterm` was used as the most portable option, but if you want to inherit your current environment, you can use the `--env` / `-e` option and pass only the _name_ of the environment variable (without value and without `=`); doing so will make the CLI lookup the value for the given environment variable from the current environment;


```bash
docker run -dit --name mycontainer alpine

TERM=dumb docker exec -e TERM mycontainer sh -c 'echo $TERM'
dumb
```

I'll close this ticket as a duplicate of https://github.com/moby/moby/issues/42323, but feel free to participate in the conversation on that ticket.

**Closed by thaJeztah** 2024-01-05 14:05 UTC
Labels: kind/feature, version/24.0
