### ISSUE TITLE
Question: Overhead in debug mode

### ISSUE THREAD

**Issue by ggaurav10** [moby/moby#35305] opened 2017-10-26 10:52 UTC
When docker is run with debug mode enabled, how much is the overhead?
What features, except pprof, are enabled as part of debug mode?
I am on an older version in which 'docker debug' subcommand is not present.

Thanks.

**Comment by cpuguy83** [comment] 2017-10-26 13:10
It's just a lot of extra logging.
The pprof stuff is always loaded, regardless if there is an endpoint available to get the data.

**Comment by thaJeztah** [comment] 2017-10-26 13:56
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-10-26 13:56 UTC
Labels: kind/question
