### ISSUE TITLE
Container can not start after docker engine upgrade from 17.03.1-ce to 17.06.0-ce-rc3

### ISSUE THREAD

**Issue by BSWANG** [moby/moby#33688] opened 2017-06-15 05:41 UTC
**Description**

Container can not start after docker engine upgrade from 17.03.1-ce to 17.06.0-ce-rc3

**Steps to reproduce the issue:**
1. At docker 17.03.1-ce, docker run -itd --name test --restart always nginx
2. upgrade docker engine to 17.06.0-ce-rc3
3. docker start test

**Describe the results you received:**
```
Error response from daemon: oci runtime error: container with id exists: 23f59a891ed34914345852ce0b39493a2e6750aabff26457194721730652a532
Error: failed to start containers: test
```

**Describe the results you expected:**
Container will restart automation after upgrade, and can be start by `docker start` command.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce-rc3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:18:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce-rc3
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:17:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 17.06.0-ce-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: nyzcah84bhar0e20lfvyfszq0
 Is Manager: true
 ClusterID: 4s0b9dwtroj8nlc0x5iaetek7
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.33.229
 Manager Addresses:
  192.168.33.229:2377
  192.168.33.230:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-63-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954GiB
Name: c1273bf40ae9c40e9a5f4ed1080f89c1a-node1
ID: 35LF:OVBC:A5RH:HVMY:2PDQ:YZFK:3267:BHJJ:4Y3Y:2IXU:2VSD:KE7F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
  xxx
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tiborvass** [comment] 2017-06-16 00:38
Confirmed

**Comment by tiborvass** [comment] 2017-06-16 01:27
@BSWANG 谢谢你 for testing our RC and finding this bug.

This also happens from 17.05 to 17.06. Does not happen with static binaries, nor when taking directly the deb files from either apt.dockerproject.org or download.docker.com.

Still investigating.

**Comment by andrewhsu** [comment] 2017-06-16 03:21
@BSWANG curious to know how did you install docker-ce 17.03.1 and how did you upgrade to 17.06.0 rc3?

**Comment by andrewhsu** [comment] 2017-06-16 04:26
We've found some kind of workaround for now...if you explicitly stopp the docker daemon before installing a new package, the service will be able to start up again. To stop the docker daemon:
```
$ service docker stop
```

**Comment by tiborvass** [comment] 2017-06-16 05:15
Note the additional `Started Docker Application Container Engine.` line in the middle, when installing docker 17.05 through get.docker.com: https://gist.github.com/tiborvass/5ca50b6a67c7441dbfe865d3ab61c6f8

**Comment by thaJeztah** [comment] 2017-06-16 08:34
Is this related to https://github.com/moby/moby/pull/33335 ?

**Comment by cpuguy83** [comment] 2017-06-16 14:21
@thaJeztah I don't think so.
Looks like a change to the runtime spec, possibly.

**Comment by BSWANG** [comment] 2017-06-23 04:58
@cpuguy83 @thaJeztah @tiborvass I have test it on the `17.06.0-rc5` version. And not reproduce this issue.

**Comment by thaJeztah** [comment] 2017-06-23 05:33
Thanks for testing! This should be resolved by https://github.com/docker/docker-ce-packaging/pull/20 and https://github.com/docker/docker-ce-packaging/pull/24 indeed.

I'll close this issue, but feel free to continue the conversation :+1:

**Closed by thaJeztah** 2017-06-23 05:33 UTC
Labels: area/runtime, priority/P0, version/17.06

**Comment by BSWANG** [comment] 2017-06-23 07:33
@thaJeztah Thank you very much.

**Comment by AndrewCsoka** [comment] 2017-06-29 14:32
Hi guys,

We're seeing the same issue when upgrading between stable versions (from 17.03.0-ce to 17.06.0-ce)

We use the live restore feature as we run docker in production, so stopping the containers as a workaround isn't ideal. We think that this is why the fix in  docker/docker-ce-packaging#20 doesn't work for us.

Is there any further info you need? Can you suggest anything so we can upgrade without restarting containers?

Cheers

**Comment by cpuguy83** [comment] 2017-06-29 14:59
@AndrewCsoka Can you paste the logs you are seeing in a new issue in docker/for-linux?

**Comment by AndrewCsoka** [comment] 2017-06-29 15:43
Have done. Thanks!

**Comment by 0xquad** [comment] 2017-11-15 00:07
I've just run into this problem on a Gentoo system that I've updated. Not related to Moby, but Docker itself exhibits this error when restarting containers in 17.06 that were created in 17.03.

* Is it an actual issue with Docker?
* What was the actual fix (other than stopping the daemon before the upgrade) at the Docker level? Gentoo has no deb/rpm packages, but rather compiles packages from sources.

My problem is that I can't easily downgrade to 17.03 as Gentoo already removed the version from the package tree, so I'm stuck with 17.06.2, 17.09.0 or 17.10.0 and they all fail. I understand that it may well be a Gentoo issue at this point, but I'd very much like to help fix this (and not lose my containers!) and understand what's happening.

**Comment by cpuguy83** [comment] 2017-11-15 01:13
@0xquad There is no official Docker for Gentoo. I'd say the issue is likely related to missing some packaging steps: https://github.com/docker/docker-ce/pull/117/files

**Comment by 0xquad** [comment] 2017-11-15 03:06
Hi @cpuguy83 and thanks.
I've managed to revert back to 17.03 manually to save my containers.

Under these circumstances, containers will fail to start again in 17.03 **the first time**, but will actually start the **second time**. Very weird.

Nonetheless, as I'm not really sure how to handle the upgrade, I've masked out all versions above 17.03 for now (and the corresponding versions of contained and docker-runc, which are two different packages).

**Comment by raarts** [comment] 2017-11-30 10:14
I've just upgraded from 17.03 to 17.06 on AWS, and I'm seeing the same problem. Container was created with `restart: always`. Had to docker rm -f the containers. This was the cwspear/docker-local-persist-volume-plugin, and I created it as a service using ansible: 

```- name: make sure the persist volume driver runs on every node
  docker_service:
    project_name: driver-local-persist
    definition:
      version: '3'
      services:
        driver-persist:
          image: cwspear/docker-local-persist-volume-plugin
          volumes:
          - /run/docker/plugins/:/run/docker/plugins
          - /plugin-data:/var/lib/docker/plugin-data
          - /data:/data
          restart: always
          deploy:
            mode: global
  tags: services
```
Funny enough containers created manually on the cli with `docker service` had no problems.
