### ISSUE TITLE
Cannot run hello-world after fresh installation

### ISSUE THREAD

**Issue by mengyuqiao** [moby/moby#44155] opened 2022-09-19 16:26 UTC
### Description

It worked a few months ago. But After I downloaded rshim for my Bluefield-2, docker cannot work anymore. I tried reinstalling docker but still got the same error. I also tried to stop the rshim service but didn't help.
```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown.
ERRO[0000] error waiting for container: context canceled
```

### Reproduce

1. docker run hello-world

### Expected behavior

run container successfully

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:37 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.10.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 36
  Running: 0
  Paused: 0
  Stopped: 36
 Images: 4
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-124-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 125.6GiB
 Name: kiwi
 ID: KT6L:4UVB:XX52:SJLN:J5PR:P7PQ:7ACW:CMUX:FNU3:Z42B:YFCO:6VB3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Additional Info

Ubuntu Version
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by kk456852** [comment] 2022-09-19 18:39
can not reproduce on m1 mac arm64 with Tag v20.10.18

**Comment by thaJeztah** [comment] 2022-09-26 10:41
The error itself comes from runc (the OCI runtime); 

> ```
> docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown.
> ERRO[0000] error waiting for container: context canceled
```


> But After I downloaded rshim for my Bluefield-2, docker cannot work anymore

If that's https://github.com/Mellanox/rshim, then it looks like that's installing kernel modules; have you reported this issue in the project(s) related to that software?

**Comment by thaJeztah** [comment] 2022-10-11 09:42
Closing this for now, as I don't think this is a bug in docker itself, but feel free to continue the conversation if you have more information.

**Closed by thaJeztah** 2022-10-11 09:42 UTC
Labels: area/kernel, status/more-info-needed, kind/bug, version/20.10
