### ISSUE TITLE
How to cleanup and manage overlay2 docker ?

### ISSUE THREAD

**Issue by rifkiriza** [moby/moby#41558] opened 2020-10-16 06:17 UTC
**Description**
Hi, I have a running docker container and my free disk space is infinitely decreases everyday. I have done as below :

**Output of `docker system df`:**

```
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              1                   1                   2.072GB             0B (0%)
Containers          1                   1                   12.66GB             0B (0%)
Local Volumes       0                   0                   0B                  0B
Build Cache         0                   0                   0B                  0B
```

**Output of `du --max-depth=1 -hc /var/lib/docker/overlay2/`:**

```
4.0K    /var/lib/docker/overlay2/l
205M    /var/lib/docker/overlay2/693a1e847468523f0d3cd2c90b190b8a23315d4e2581b7ea22785584415f3a9b
281M    /var/lib/docker/overlay2/64a9656875d0cf9c420d8dc58757e4f3fc6a7b8b66386c6bffeb2828af76fa1e
148M    /var/lib/docker/overlay2/f4612f13964de2437a9ebf264d895a0891aa7b4a232f5d20f16131f6eada18c6
85M     /var/lib/docker/overlay2/70b99605aa78817cac753c01cf4132b9698bece265a01751d4da1341d1f13be7
196K    /var/lib/docker/overlay2/9bd95ced09a685efd19bdee9efd0a97786ea8dcddeb2982928d3c27db773de59
418M    /var/lib/docker/overlay2/970856795dfd597524d694830c85246dd1f5cbc88de7364abe4eaba7ea27bd9e
16K     /var/lib/docker/overlay2/5490f4a0bdb240773b432c5bb593ee7cb195d3afc1a0e566a34ced4056ed98c4
419M    /var/lib/docker/overlay2/b600a8a8691217a3ce7a1cfa9b6b2784e67ee4f5b8b91e2840657d7f00b0cff9
452M    /var/lib/docker/overlay2/89aacbad54ddf4dc1b8e0accbadb9e85a600ff41c1e1cb13ff6b3c470f78b18e
8.0K    /var/lib/docker/overlay2/2ee426d956d3f9b4e9729c1e7df27ba3c29e533e2080a0fef71c508ae44e884d-init
16G     /var/lib/docker/overlay2/2ee426d956d3f9b4e9729c1e7df27ba3c29e533e2080a0fef71c508ae44e884d
18G     /var/lib/docker/overlay2/
18G     total
```

**Output of `docker system prune --all`:**

```
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all images without at least one container associated to them
  - all build cache

Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
```

**Output of `du -shc /var/lib/docker/overlay2/`:**

```
18G     /var/lib/docker/overlay2/
18G     total
```

How to cleanup and manage overlay2 docker ?

**Comment by thaJeztah** [comment] 2020-10-16 12:32
Looks like you have 1 container running, and that container is using 12GB, so because the container is running, it cannot be removed (including the image it's using, which is 2GB)

```
Images              1                   1                   2.072GB             0B (0%)
Containers          1                   1                   12.66GB             0B (0%)
```

So the space that's used is likely because something in the container is generating output that's written to the container's filesystem. Perhaps you have a process running in the container that's writing logs to a file (instead of to `stdout` / `stderr`)

To find what files are added in the container's filesystem since it was started, you can use `docker diff <name of the container>`, which would output something like;

```
C /run
A /run/nginx.pid
C /var
C /var/cache
C /var/cache/nginx
A /var/cache/nginx/uwsgi_temp
A /var/cache/nginx/client_temp
A /var/cache/nginx/fastcgi_temp
A /var/cache/nginx/proxy_temp
A /var/cache/nginx/scgi_temp
```

A description of the letters in the first column can be found in the documentation; https://docs.docker.com/engine/reference/commandline/diff/#extended-description

If it's indeed caused by log files, I would recommend to;

- change the container's process to log to stdout/stderr. the container's `stdout`/`stderr` output is captured by docker's logging drivers, which allows you to view those logs using `docker container logs <container name>` (or `docker logs`) commands Also see https://docs.docker.com/config/containers/logging/configure/
- when creating the container, be sure to enable log-rotation, otherwise the container's logs will only grow. You can use the `local` logging driver, which will rotate by default (`docker run --log-driver=local .......`)
- Use volume(s) for data generated by the container that must persist beyond the container's lifecycle (i.e., when you remove the container, the data should be kept). See https://docs.docker.com/storage/ and https://docs.docker.com/storage/volumes/


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-10-16 12:32 UTC
