### ISSUE TITLE
Docker volume command overrides permission on the folder inside the container.

### ISSUE THREAD

**Issue by sampcoug** [moby/moby#38508] opened 2019-01-07 23:14 UTC
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2019-01-08 00:16
Closing since there are zero details here. If you want to add details please ping and I will re-open.

As is, volumes take the uid/gid from the directory in the container image IF the volume is empty. If it is not empty the UID/GID from the volume will not change.
This is by design. It would be nice to be able to change the UID/GID when we mount the volume but this is not possible without something like bindfs (a FUSE filesystem driver).

**Closed by cpuguy83** 2019-01-08 00:16 UTC

**Comment by sampcoug** [comment] 2019-01-08 18:03
I apologize for not being clearer on the issue earlier, I have a task to share data between a Docker container and host system using volumes so I am running the following command inside my Terraform script to set the volume. 
`ExecStart=/usr/bin/docker run -v /var/log/xxx/xxxx:/var/log/xxx/xxxx`
However, this command overrides the permission on the Docker container directory /var/log/xxx/xxxx, and its causing the log to not write on the folder. I have set permission on the container directory using the docker file using the command below:
`RUN chmod 7xx /var/log/xxx/xxxx`
I tried adding the command above to the Docker Entry point file but it didn't seem to work. Is there a way to reset the volume permissions back to how it was set in the docker file. This is really becoming a blocker for me. Any help would be really appreciated.

**Comment by cpuguy83** [comment] 2019-01-08 18:07
@sampcoug The permissions will come from the host dir in this case. `-v /foo:/bar` is telling docker to take host dir `/foo` and put it at `/bar`.
There is not currently any way to tell Linux to change the UID/GID at mount time.

You could do this with bindfs (on the host) by using bindfs to mount to a different location with the uid/gid you want then using that new path as the host path, but performance will be abysmal.
