### ISSUE TITLE
Docker overlay storage driver unable to delete directories from underlying image layer

### ISSUE THREAD

**Issue by g000444555** [moby/moby#35257] opened 2017-10-20 07:44 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

The issue is similar to [overlayfs: Can't delete file moved from base layer to newly created dir even on ext4 #9572](https://github.com/moby/moby/issues/9572)

However, the route cause isn't the same, because `d_type` is enabled in my case.

**Steps to reproduce the issue:**

For example, manually running the container and trying to delete a directory results in the following error

    $ docker run --rm -it arm64v8/ubuntu:latest bash
    root@95f2e1ed7888:/# rm -rf /usr/share/doc
    rm: cannot remove '/usr/share/doc/sed': Directory not empty
    rm: cannot remove '/usr/share/doc/libpam-modules': Directory not empty
    rm: cannot remove '/usr/share/doc/util-linux': Directory not empty
    rm: cannot remove '/usr/share/doc/mawk': Directory not empty
    rm: cannot remove '/usr/share/doc/gnupg': Directory not empty
    rm: cannot remove '/usr/share/doc/apt': Directory not empty
    rm: cannot remove '/usr/share/doc/libreadline6': Directory not empty
    rm: cannot remove '/usr/share/doc/adduser/examples/adduser.local.conf.examples': Directory not empty
    rm: cannot remove '/usr/share/doc/passwd': Directory not empty
    rm: cannot remove '/usr/share/doc/mount': Directory not empty
    rm: cannot remove '/usr/share/doc/procps': Directory not empty

If the directory is empty, then `rm -rf` won't complain but won't delete it either, for example

    root@95f2e1ed7888:/# ls -la /usr/share/doc/zlib1g
    total 8
    drwxr-xr-x 1 root root 4096 Oct 20 07:29 .
    drwxr-xr-x 1 root root 4096 Oct 20 07:29 ..
    root@95f2e1ed7888:/# rm -rf /usr/share/doc/zlib1g
    root@95f2e1ed7888:/# ls -la /usr/share/doc/zlib1g
    total 8
    drwxr-xr-x 1 root root 4096 Oct 20 07:29 .
    drwxr-xr-x 1 root root 4096 Oct 20 07:29 ..

On the other hand, `rmdir` for an empty directory reports the following error

    root@95f2e1ed7888:/# ls -la /usr/share/doc/zlib1g
    total 8
    drwxr-xr-x 1 root root 4096 Oct 20 07:29 .
    drwxr-xr-x 1 root root 4096 Oct 20 07:29 ..
    root@95f2e1ed7888:/# rmdir /usr/share/doc/zlib1g
    rmdir: failed to remove '/usr/share/doc/zlib1g': Invalid argument

**Output of `docker version`:**

    $ docker version
    Client:
     Version:      17.10.0-ce
     API version:  1.33
     Go version:   go1.9.1
     Git commit:   f4ffd2511c
     Built:        Thu Oct 19 00:10:43 2017
     OS/Arch:      linux/arm64
    
    Server:
     Version:      17.10.0-ce
     API version:  1.33 (minimum version 1.12)
     Go version:   go1.9.1
     Git commit:   f4ffd2511c
     Built:        Thu Oct 19 00:11:05 2017
     OS/Arch:      linux/arm64
     Experimental: false

**Output of `docker info`:**

    $ docker info
    Containers: 7
     Running: 1
     Paused: 0
     Stopped: 6
    Images: 95
    Server Version: 17.10.0-ce
    Storage Driver: overlay
     Backing Filesystem: extfs
     Supports d_type: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: bridge host macvlan null overlay
     Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
    Swarm: active
     NodeID: mjm8vu1ixmw1ls25dk7gomiva
     Is Manager: true
     ClusterID: lnspgxtrca8d4lm3kfv7zbz77
     Managers: 3
     Nodes: 3
     Orchestration:
      Task History Retention Limit: 5
     Raft:
      Snapshot Interval: 10000
      Number of Old Snapshots to Retain: 0
      Heartbeat Tick: 1
      Election Tick: 3
     Dispatcher:
      Heartbeat Period: 5 seconds
     CA Configuration:
      Expiry Duration: 3 months
      Force Rotate: 0
     Autolock Managers: false
     Root Rotation In Progress: false
     Node Address: 192.168.1.11
     Manager Addresses:
      192.168.1.11:2377
      192.168.1.12:2377
      192.168.1.13:2377
    Runtimes: runc
    Default Runtime: runc
    Init Binary: docker-init
    containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
    runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
    init version: 949e6fa
    Security Options:
     seccomp
      Profile: default
    Kernel Version: 3.14.79-27-ARCH
    Operating System: Arch Linux ARM
    OSType: linux
    Architecture: aarch64
    CPUs: 4
    Total Memory: 1.928GiB
    Name: alarm-docker-manager-host
    ID: Y5ZZ:5G3O:KIE2:MSQX:7MBB:XWOZ:CYLL:2SSY:GTMB:YCBG:4TTT:EJVN
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    Experimental: false
    Insecure Registries:
     127.0.0.0/8
    Live Restore Enabled: false

Not sure if this is relevant, however note that the underlying partition is encrypted with LUKS on LVM.

Digging into the issue further, the permissions of the directory I try to delete are ok

    root@95f2e1ed7888:/# ls -lah /usr/share
    total 160K
    drwxr-xr-x  1 root root 4.0K Oct 19 05:39 .
    drwxr-xr-x  1 root root 4.0K Oct 19 05:39 ..
    drwxr-xr-x  2 root root 4.0K Oct 19 05:39 adduser
    drwxr-xr-x  3 root root 4.0K Oct 19 05:39 apport
    drwxr-xr-x  2 root root 4.0K Oct 19 05:39 base-files
    drwxr-xr-x  2 root root 4.0K Oct 19 05:39 base-passwd
    drwxr-xr-x  3 root root 4.0K Oct 19 05:39 bash-completion
    drwxr-xr-x  6 root root 4.0K Oct 19 05:39 bug
    drwxr-xr-x  2 root root 4.0K Oct 19 05:39 common-licenses
    drwxr-xr-x  4 root root 4.0K Oct 19 05:39 dbus-1
    drwxr-xr-x  2 root root 4.0K Oct 19 05:39 debconf
    drwxr-xr-x  2 root root 4.0K Oct 19 05:39 debianutils
    drwxr-xr-x  2 root root 4.0K Apr 12  2016 dict
    drwxr-xr-x  1 root root 4.0K Oct 20 07:29 doc
    ...

Also, the directory is not being used by another process

    root@95f2e1ed7888:/# lsof /usr/share/doc

Moreover, running the container with sudo has same effect

    $ sudo docker run --rm -it arm64v8/ubuntu:latest rm -rf /usr/share/doc
    rm: cannot remove '/usr/share/doc/sed': Directory not empty
    rm: cannot remove '/usr/share/doc/libpam-modules': Directory not empty
    rm: cannot remove '/usr/share/doc/util-linux': Directory not empty
    rm: cannot remove '/usr/share/doc/mawk': Directory not empty
    rm: cannot remove '/usr/share/doc/gnupg': Directory not empty
    rm: cannot remove '/usr/share/doc/apt': Directory not empty
    rm: cannot remove '/usr/share/doc/libreadline6': Directory not empty
    rm: cannot remove '/usr/share/doc/adduser/examples/adduser.local.conf.examples': Directory not empty
    rm: cannot remove '/usr/share/doc/passwd': Directory not empty
    rm: cannot remove '/usr/share/doc/mount': Directory not empty
    rm: cannot remove '/usr/share/doc/procps': Directory not empty

Finally, more debugging information in regards to this issue can be found at https://stackoverflow.com/questions/46824425/docker-is-unable-to-delete-a-directory-when-building-images

**Comment by g000444555** [comment] 2017-10-20 08:31
Note that the same issue applies when deleting newly created files in the writable container layer while building a docker image (e.g. https://github.com/gogits/gogs/issues/4828)

**Comment by thaJeztah** [comment] 2017-10-20 17:27
I'm not able to reproduce this on an Ubuntu 16.04 machine using overlay. This may be an issue with Arch linux, which is known to have problems sometimes due to their rolling release model (and not a supported distro); did you install docker from the official packages, or from the Arch repository?

**Comment by g000444555** [comment] 2017-10-21 05:58
I installed `docker` from the official repository for Arch Linux ARM (https://archlinuxarm.org/packages/aarch64/docker):

    sudo pacman -Syu
    sudo pacman -S docker libtool docker-compose

Unlike the AUR (Arch User Repository), which is maintained by users, the above repository is supported by distro maintainers.

Note that I also had the same issue with the previous docker version 17.09.0-ce.

The Arch package is using the official docker sources, as can be observed from the package description at https://archlinuxarm.org/packages/aarch64/docker/files/PKGBUILD:

    "git+https://github.com/docker/docker-ce.git#tag=v$pkgver-ce
    "git+https://github.com/opencontainers/runc.git#commit=$_RUNC_COMMIT"
    "git+https://github.com/containerd/containerd.git#commit=$_CONTAINERD_COMMIT"
    "git+https://github.com/docker/libnetwork.git#commit=$_LIBNETWORK_COMMIT"
    "git+https://github.com/krallin/tini.git#commit=$_TINI_COMMIT"
    "git+https://github.com/spf13/cobra.git"
    "git+https://github.com/cpuguy83/go-md2man.git"
        
I just recently switched from Ubuntu 16.04 to ArchLinux.

Running Ubuntu 16.04 on the exact same hardware (ODROID-C2, ARM64 architecture), I was able to build the same docker images without encountering problems with the rm commands.

The differences I remember were that the Ubuntu 16.04 version used AUFS instead of overlay, and an older version of docker (17.03.0-ce).

As far as I am concerned there isn't an officially supported list of distros for docker and it should run on all distros subject to compatible kernel version, isn't that the case?

I will ping the package maintainer to see if I can get some more clues.

It would be unfortunate if I can't use docker with ArchLinux as it seems like I finally found a distro "done right".

**Comment by thaJeztah** [comment] 2017-10-21 11:20
> As far as I am concerned there isn't an officially supported list of distros for docker and it should run on all distros subject to compatible kernel version, isn't that the case?

here's an overview with supported distros for the official packages; https://docs.docker.com/engine/installation/#server 

Arch linux is not a supported platform, and your best point for support would be the maintainers for the package you installed.

Also note that kernel 3.14 is quite old (and I think even reached EOL; https://www.kernel.org/releases.html), if I'm not mistaken, kernel 3.16 or above is required for the overlay storage driver (kernel 4.x is highly recommended, as it supports the overlay2 storage driver).

I'll close this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-21 11:20 UTC
Labels: area/storage/overlay, status/more-info-needed, version/17.10, version/unsupported

**Comment by g000444555** [comment] 2017-10-22 06:45
Thank you for the link with the supported distros (I should have known that) and the very important hints for fixing the issue.

Indeed, as documented here https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/, kernel 3.14 is too old for the overlay driver (3.18 or newer is required). Therefore, the package should not be built with the overlay driver but the older AUFS.

I have reported the issue to the ArchLinux ARM maintainers at [issue with the docker package](https://archlinuxarm.org/forum/viewtopic.php?f=15&t=12160). However, the ARM maintainers in particular, not talking about the official ArchLinux team, seem very unresponsive. Therefore, I think the solution will be to create a package that fixes the issue and release it into the AUR. The information you provided is very important for the fix. Mainline kernel support is underway for ODROID-C2 but had some issues the last time I checked. If sticking to the old kernel 3.14, then compiling the package with AUFS instead of the overlay driver might be the solution.

**Comment by AkihiroSuda** [comment] 2018-01-25 02:51
probably same one: https://github.com/moby/moby/issues/36103

**Comment by xieqihui** [comment] 2019-06-04 10:45
I got the same problem with the following `docker info`:
```
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
```

The problem got sovled after I upgrade kernel version to 3.10.0-957.12.1.el7
