### ISSUE TITLE
Docker v17.05ce unexpected EOF with docker push

### ISSUE THREAD

**Issue by gdeverlant** [moby/moby#33421] opened 2017-05-27 15:37 UTC
**Description**

unexpected EOF with docker push

**Steps to reproduce the issue:**
docker push server1:5000/custom/drone-arm32:0.7.1

**Describe the results you received:**

```
The push refers to a repository [server1:5000/custom/drone-arm32]
023bd260410b: Pushing  426.5kB/19.71MB
42aa7a217cde: Preparing
62217892ac60: Preparing
3c8f602fa744: Preparing
c6a684c1ce4d: Preparing
261415ca5a44: Waiting
8171e1c4de03: Waiting
649713aa1d7f: Waiting
11a1caa71f1d: Waiting
unexpected EOF
```

**Describe the results you expected:**
Normal behavior

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by gdeverlant** [comment] 2017-05-28 13:55
The problem seem to be the image I used with FROM

FROM resin/rpi-raspbian:jessie

when I changed the image to 

FROM resin/rpi-raspbian:jessie-20170525

the push succeeded

**Comment by thaJeztah** [comment] 2017-05-29 14:33
The `unexpected EOF` message can have various reasons, one of which is if your machine runs out of disk space.

It looks like you resolve the issue for now, but if you're still having this issue and suspect it's a _bug_, not something in your setup, please post the information that was requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- relevant log files
- provide the _exact_ steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'll close this issue for now

**Closed by thaJeztah** 2017-05-29 14:33 UTC
Labels: area/distribution, platform/arm, status/more-info-needed

**Comment by gdeverlant** [comment] 2017-05-30 00:17
It is impossible that it's a problem from disk space issue.
There is a 500 GB HD and it is not even full:

```
Filesystem               Size  Used Avail Use% Mounted on
/dev/root                 29G  4.3G   23G  16% /
devtmpfs                 445M     0  445M   0% /dev
tmpfs                    471M   84K  471M   1% /dev/shm
tmpfs                    471M   14M  458M   3% /run
tmpfs                    5.0M     0  5.0M   0% /run/lock
tmpfs                    471M     0  471M   0% /sys/fs/cgroup
/media/500GB;/mnt/dummy  487G   37G  425G   8% /mnt/virtual
/dev/sda1                458G   33G  402G   8% /media/500GB
none                     487G   37G  425G   8% /mnt/virtual/var/lib/docker/aufs/mnt/92e724f7d85adee2e1e6d0e5b4a7695545d11ecc17f1de19e56476881a06c6f1
shm                       64M     0   64M   0% /mnt/virtual/var/lib/docker/containers/bfcff4c75c246f2346d72b25afe2a35c7aab0caea21c89626d18540871ef8a09/shm
none                     487G   37G  425G   8% /mnt/virtual/var/lib/docker/aufs/mnt/8b172c10dbe66932f87534170a2e2e1ced036619eb3d2b41775eee20b1841e9a
none                     487G   37G  425G   8% /mnt/virtual/var/lib/docker/aufs/mnt/ecb4d1ecde69930bcbba648fbcc71e5aa8bae737e513f886c52a2e322c4cf0a8
none                     487G   37G  425G   8% /mnt/virtual/var/lib/docker/aufs/mnt/ade69e11a97474058f278cdf55ce9c2885a6728bb14b21a08baafdc3bf472754
shm                       64M     0   64M   0% /mnt/virtual/var/lib/docker/containers/72b0213ca513c6708549896652090a426065ab6fd4412b6a0ad45e2ccff38f43/shm
shm                       64M     0   64M   0% /mnt/virtual/var/lib/docker/containers/64d6ea0a6ace660fa0a4946e9011911ae9ff2706f83fc958e487430524342657/shm
shm                       64M     0   64M   0% /mnt/virtual/var/lib/docker/containers/5fe55983fed2b217cede35e1d3e7a83f22078f9248525512f21d981060d10e15/shm
tmpfs                     95M     0   95M   0% /run/user/1000
```
