### ISSUE TITLE
Exported shell variable undefined in next steps

### ISSUE THREAD

**Issue by mkatrenik** [moby/moby#34152] opened 2017-07-18 08:19 UTC
**Description**

Shell variable exported in RUN directive is undefined in next step

**Steps to reproduce the issue:**

Given following `Dockerfile`
```
FROM busybox
RUN export TMP=foo
RUN echo $TMP
```

when builded with `docker build -t foo .`

**Describe the results you received:**
Line `RUN echo $TMP` prints nothing

**Describe the results you expected:**
Line `RUN echo $TMP` should print foo

**Additional information you deem important (e.g. issue happens only occasionally):**
Bug appeared after upgrade to 17.06

**Output of `docker version`:**
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 141
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: iklynzmzfmx9ltiu6ezg49c3o
 Is Manager: true
 ClusterID: r4g8sul588lhwefrtoi68vljt
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: T2IJ:P7P5:T7LH:OR6W:FTOE:FJ4P:C64Y:EBUG:OOLT:UIJI:NLQR:6VGS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 139
 System Time: 2017-07-18T08:17:30.317118453Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-07-18 08:29
Yes, this is expected (but may be surprising if you're new to Docker).

Each `RUN` instruction in a Dockerfile is executed in  a new container, thus a new shell session. The `export` command in the first `RUN` is thus only active in _that_ shell session; the next `RUN` starts in a new session, and does not get the exported environment variable.

- use `ENV` to set an environment variable that's available in all `RUN` steps following that (Docker will set the environment variable the moment the (shell) session for the `RUN` is started)
- combine multiple `RUN` statements into a single one if they're related


I'm closing this issue because it's not a bug, but feel free to continue the conversation if you need more information 👍

**Closed by thaJeztah** 2017-07-18 08:29 UTC
Labels: area/builder, version/17.06

**Comment by mkatrenik** [comment] 2017-07-18 08:34
My actual use case is `RUN export TMP=$(mktemp)`, I cannot do this with ENV so I guess this or some alternative is not possible any more?

**Comment by thaJeztah** [comment] 2017-07-18 08:48
Other than combining those steps, that won't be possible. The "builder" is not aware of the environment variables present in a shell environment; i.e., if I `export FOO=blah`, that environment variable is only known in _that_ shell. Docker does not know about the environment variable, so cannot "transfer" the variable to the next container.

As a result, you also won't be able to use that exported `TMP` variable in other Dockerfile instructions (e.g. you won't be able to do `COPY foo $TMP`)

There is some discussion around this in this pull request; https://github.com/moby/moby/pull/29048, but trying to get the environment variables back from a `RUN` statement has a lot of technical implications, so there's no consensus if it will be implemented.

**Comment by thaJeztah** [comment] 2017-07-18 08:59
For the `mktemp` example; why not use a fixed path? Given that build-steps are cached, using `mktemp` will only be evaluated once, so it won't be different with each `docker build`, _unless_ a step before it busted the cache.

In addition; if the `tmp` dir is used to temporarily store data that will be removed in a later `RUN` instruction, it's best to combine those steps anyway, otherwise you'll end up with a big image; e.g. (assuming `package.tar` is 100MB)

```Dockerfile
RUN export TMP=$(mktemp)

# Add 100MB
RUN curl -o $tmp/foo.tar https://example.com/package.tar

# Add 100+MB for the extracted files
RUN tar -xvf $tmp/foo.tar 

# Add xx bytes to mark the tar file as deleted
RUN rm $tmp/foo.tar

# Add 100+MB for the moved extracted files, and marking the original files as "deleted"
RUN mv $tmp/foo/* /my-app/

```

So your total image size will be 400MB, while combining all those steps in a single `RUN` would make it 100MB
