### ISSUE TITLE
File mount does not update on host with changes from container

### ISSUE THREAD

**Issue by tarinnn** [moby/moby#41049] opened 2020-06-01 06:47 UTC
In my container I run a python script that writes files to a mounted volume. My problem is that the changes are updated only in the container volume but not on the host. When I update the volume on the host I can see the changes also in the container directory. I also have this problem only in Ubuntu, when I run the same image on windows the update works in both directions. 

This is my docker run:

    `sudo docker run --name mycontainer -it -p 2375:2375 --cap-add=NET_RAW --cap-add=NET_ADMIN --mount source=/home/docker/container_data/my_data1,target=/my_data1/data,type=bind --mount source=/home/docker/container_data/my_data2,target=/my_data2/data,type=bind ImageName`

Here the docker info:

```
    Server:
     Containers: 8
      Running: 2
      Paused: 0
      Stopped: 6
     Images: 18
     Server Version: 19.03.6
     Storage Driver: overlay2
      Backing Filesystem: extfs
      Supports d_type: true
      Native Overlay Diff: true
     Logging Driver: json-file
     Cgroup Driver: cgroupfs
     Plugins:
      Volume: local
      Network: bridge host ipvlan macvlan null overlay
      Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
     Swarm: inactive
     Runtimes: runc
     Default Runtime: runc
     Init Binary: docker-init
     containerd version:
     runc version:
     init version:
     Security Options:
      apparmor
      seccomp
       Profile: default
     Kernel Version: 4.15.0-96-generic
     Operating System: Ubuntu 18.04.4 LTS
     OSType: linux
     Architecture: x86_64
     CPUs: 8
     Total Memory: 15.62GiB
     Name: -server
     ID: CWBP:....
     Docker Root Dir: /var/lib/docker
     Debug Mode: false
     Registry: https://index.docker.io/v1/
     Labels:
     Experimental: false
     Insecure Registries:
      127.0.0.0/8
     Live Restore Enabled: false
```

Here the docker version:

```
Client:
     Version:           19.03.6
     API version:       1.40
     Go version:        go1.12.17
     Git commit:        369ce74a3c
     Built:             Fri Feb 28 23:45:43 2020
     OS/Arch:           linux/amd64
     Experimental:      false
   Server:
     Engine:
      Version:          19.03.6
      API version:      1.40 (minimum version 1.12)
      Go version:       go1.12.17
      Git commit:       369ce74a3c
      Built:            Wed Feb 19 01:06:16 2020
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          1.3.3-0ubuntu1~18.04.2
      GitCommit:
     runc:
      Version:          spec: 1.0.1-dev
      GitCommit:
     docker-init:
      Version:          0.18.0
      GitCommit:
```

**Comment by thaJeztah** [comment] 2020-06-02 11:50
- Are the daemon and CLI running on the same machine?
- What setup are you running on? I see you mentioned "Windows"; are you running Docker in WSL2?
- Is `/home/docker/` a regular directory? Is it on the same filesystem? Is it a mount?
- From the output of your docker info, I see `1.3.3-0ubuntu1~18.04.2` as containerd version; is this an official Docker package you installed? (https://docs.docker.com/engine/install/ubuntu/), or did you install a package that was built and distributed through the Ubuntu package repositories? (we don't build or maintain those versions, and I've seen reports where there's issues related to how they're built)

**Comment by tarinnn** [comment] 2020-06-03 07:45
@thaJeztah 

- I'm not sure what you mean, sorry, I just started with docker...
- I'm running docker on Ubuntu:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04

- /home/docker/ is regular directory on the host

- this is how Docker was installed:
sudo apt-get remove docker docker-engine docker.io
sudo apt install docker.io
sudo systemctl start docker
sudo systemctl enable docker

**Comment by thaJeztah** [comment] 2020-06-03 08:39
The `docker.io` packages is a package built and maintained by Ubuntu. Can you try if you're seeing the same problem with the official packages? Installation instructions can be found here; https://docs.docker.com/engine/install/ubuntu/

You can use the [convenience script](https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script), but may have to [uninstall](https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions) the distro package first;

```bash
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```

**Comment by tarinnn** [comment] 2020-06-04 11:59
Sorry, I just found out that the problem was WinSCP. now showing me the created files. Thank you for the support, I think you can close this issue.

**Comment by thaJeztah** [comment] 2020-06-04 12:03
Good to hear you managed to find the cause 👍 

closing this one

**Closed by thaJeztah** 2020-06-04 12:03 UTC
Labels: status/more-info-needed, version/19.03
