### ISSUE TITLE
Docker has an error restarted and solved . 

### ISSUE THREAD

**Issue by tongpaopao** [moby/moby#36462] opened 2018-03-02 03:31 UTC
```
Mar  1 22:41:04 master3 kernel: dockerd: page allocation stalls for 12583ms, order:0, mode:0x14201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=(null)
Mar  1 22:41:04 master3 kernel: dockerd cpuset=/ mems_allowed=0
Mar  1 22:41:04 master3 kernel: CPU: 3 PID: 21284 Comm: dockerd Not tainted 4.14.14-1.el7.elrepo.x86_64 #1
Mar  1 22:41:19 master3 kernel: dockerd: page allocation stalls for 11845ms, order:0, mode:0x14201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=(null)
Mar  1 22:41:19 master3 kernel: dockerd cpuset=/ mems_allowed=0
Mar  1 22:41:19 master3 kernel: CPU: 0 PID: 14514 Comm: dockerd Not tainted 4.14.14-1.el7.elrepo.x86_64 #1
Mar  1 22:41:25 master3 dockerd: time="2018-03-01T22:41:16.739976469+08:00" level=info msg="killing and restarting containerd" module=libcontainerd pid=12995
Mar  1 22:41:26 master3 dockerd: time="2018-03-01T22:41:26.515335536+08:00" level=error msg="failed to get event" error="rpc error: code = Internal desc = transport is closing" module=libcontainerd namespace=moby
Mar  1 22:41:26 master3 dockerd: time="2018-03-01T22:41:26.561003858+08:00" level=warning msg="failed to delete process" container=ba93313c1ec4be8ccf5b8e062d35dc2c4f147ff347b627105805e006ebe3d280 error="transport is closing: unknown" module=libcontainerd namespace=moby process=704fe25ccb543134c0fabde9a84de410cef2ca236bfc98013eec6201ae1346bb
Mar  1 22:41:26 master3 dockerd: time="2018-03-01T22:41:26.607611564+08:00" level=error msg="failed to get event" error="rpc error: code = Internal desc = transport is closing" module=libcontainerd namespace=moby-plugins
Mar  1 22:41:26 master3 dockerd: time="2018-03-01T22:41:26.633047137+08:00" level=error msg="containerd did not exit successfully" error="signal: killed" module=libcontainerd
Mar  1 22:41:26 master3 dockerd: time="2018-03-01T22:41:26.670029264+08:00" level=error msg="stream copy error: reading from a closed fifo"
Mar  1 22:41:26 master3 dockerd: time="2018-03-01T22:41:26.670073291+08:00" level=error msg="stream copy error: reading from a closed fifo"
Mar  1 22:41:26 master3 dockerd: time="2018-03-01T22:41:26.670219629+08:00" level=error msg="Error running exec 5d949455ef007f5bd3a7c07238b827866b2b802d881e9e32a48d53cef54f18ae in container: transport is closing: unknown"
Mar  1 22:41:31 master3 dockerd: time="2018-03-01T22:41:26.695197614+08:00" level=error msg="stream copy error: reading from a closed fifo"
Mar  1 22:41:31 master3 dockerd: time="2018-03-01T22:41:26.695255811+08:00" level=error msg="stream copy error: reading from a closed fifo"
Mar  1 22:41:31 master3 dockerd: time="2018-03-01T22:41:26.695344934+08:00" level=error msg="Error running exec b08b8c9aeb3cdddb30e71bf511714c54bad6f4ec4ad449bb6a9ef9b81732d323 in container: transport is closing: unknown"
Mar  1 22:41:34 master3 dockerd: time="2018-03-01T22:41:34.045638395+08:00" level=error msg="stream copy error: reading from a closed fifo"
Mar  1 22:41:34 master3 dockerd: time="2018-03-01T22:41:34.059704415+08:00" level=info msg="libcontainerd: started new docker-containerd process" pid=21962
Mar  1 22:41:34 master3 dockerd: time="2018-03-01T22:41:34.060031531+08:00" level=error msg="stream copy error: reading from a closed fifo"
Mar  1 22:41:35 master3 dockerd: time="2018-03-01T22:41:34.060159251+08:00" level=error msg="Error running exec 6e5b6e810f58fb6d293c174228f95700daebba7050d5d1fabd70e55611134683 in container: connection error: desc = \"transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused\": unknown"

**Comment by thaJeztah** [comment] 2018-03-05 19:43
When reporting issues, please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'm closing this issue because of the above, but feel free to comment after I closed

**Closed by thaJeztah** 2018-03-05 19:43 UTC
