### ISSUE TITLE
failed to register layer: open XXX: no such file or directory

### ISSUE THREAD

**Issue by Nebulazhang** [moby/moby#38051] opened 2018-10-16 12:42 UTC
**Description**
When I pull my image and I found it failed.
`failed to register layer: open /var/lib/docker/aufs/layers/03e95f6f05d4037c285734fc9b12de5e8384528df4e20f80feccd73ba4fa2d53: no such file or directory`
And I restart docker , no help.
And I rm -f /var/lib/docker/aufs/layers/ ant try again, but  it still failed

I don't know what happend

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.671 GiB
Name: VM-0-117-ubuntu
ID: TSHX:Q5TJ:HTIM:TLHY:7C6A:DWIV:PUEN:E7QF:RIE3:AET3:N52O:QPLB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-10-16 17:55
Note that docker 1.12 is by now a very old version of Docker that reached end of life in January 2017, and is no longer maintained; are you able to reproduce this on a current version?

I notice you're running on a 4.x kernel; I would also recommend switching to the overlay2 storage driver instead of aufs; if you do a clean install, overlay2 should be selected as default storage driver, but you may have to clean `/var/lib/docker` (beware: doing so will remove all your containers and images).


I'll close this issue, because docker 1.12 is no longer supported, but feel free to continue the conversation

**Closed by thaJeztah** 2018-10-16 17:55 UTC
Labels: version/1.12

**Comment by Nebulazhang** [comment] 2018-10-17 06:52
@tabakhase Thanks for your solution,   I clean `/var/lib/docker` and it runs OK. And can you tell why did this happen?

**Comment by cwiggs** [comment] 2022-01-18 23:42
@thaJeztah I'm running into this issue as well but I'm running a newer version of Docker, and using overlay2.

```
$ docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.15.14
 Git commit:        f0df350
 Built:             Wed Nov 17 03:05:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.14
  Git commit:       b0f5bc3
  Built:            Wed Nov 17 03:06:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0
  GitCommit:        84113eef6fc27af1b01b3181f31bbaf708715301
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 39
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: amazon-ecs-volume-plugin local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: 84113eef6fc27af1b01b3181f31bbaf708715301
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.238-182.422.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.501GiB
 Name:  <removed sensitive info>
 ID: 6RXH:AIXO:4KHB:4KOD:ECO3:M6NI:LGO2:KYWC:LERW:44Q6:YBDH:NSUO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: <removed sensitive info>
 HTTPS Proxy:  <removed sensitive info>
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Can we re-open this issue since it looks like it still exists with newer versions of Docker, and with overlay2?
