### ISSUE TITLE
New state of 'nil' is invalid

### ISSUE THREAD

**Issue by mrAndersen** [moby/moby#32223] opened 2017-03-30 09:36 UTC
Hi there. I have very strange problem. Running docker on windows 10 native, without any sort of VMs such as those created with docker-machine.

Initially the problem was that file_get_contents on my symfony project being called on ANY file returns empty string. To investigate this issue, i logged inside container and executed php - a and file_get_contents on selected file - the result was

`php > var_dump(sizeof(file_get_contents("https://www.cybersport.ru/upload/comments_img/3a3/goblaksilent.jpg")));
php shell code:1:
int(1)
php > echo(file_get_contents("https://www.cybersport.ru/upload/comments_img/3a3/goblaksilent.jpg"));
ExifMM*
      New state of 'nil' is invalid.`

And this is very strange. Because my colleague running same container on MAC or Ubuntu does not have any issue with this. Also i tried to disable xdebug, but no luck with that.

Docker version 17.03.1-ce, build c6d412e
Microsoft Windows [Version 10.0.10586]

**Comment by AkihiroSuda** [comment] 2017-03-30 09:55
Seems dupe of https://github.com/docker/docker/issues/22345#issuecomment-270457501

**Comment by thaJeztah** [comment] 2017-06-01 13:18
According to the last comment there; https://github.com/moby/moby/issues/22345#issuecomment-270457501, the best way forward is to open an issue in https://github.com/Azure/go-ansiterm

> Probably the best thing to do is to open this issue against https://github.com/Azure/go-ansiterm as that is the emulator repo used by docker client when running on down-level operating systems. However, as I mentioned above, I'm not aware of anyone actively maintaining it these days, or whether it makes sense for someone to really invest a significant amount of time working on it and bringing it up to the level needed to support mc (if indeed it can be done with the legacy console itself on Windows prior to Windows 10, hence the efforts may be futile, but I'm not sure). The alternate, of course, is to use a Windows 10 client (and a docker client 1.13 I believe is required for native console on-by-default if present, but that may have be turned on in 1.12 - would have to dig back in the docker repo to verify that for sure. It wasn't in 1.11 which is what this issue was opened against).


What shell are you using? `CMD.exe`, PowerShell, or something else?

**Comment by thaJeztah** [comment] 2023-09-16 15:45
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 15:45 UTC
Labels: area/cli, platform/windows, status/more-info-needed
