### ISSUE TITLE
Unrecognized input header: 99

### ISSUE THREAD

**Issue by npcode** [moby/moby#21902] opened 2016-04-09 06:51 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   da0985f
 Built:        Thu Apr  7 06:14:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   7e9c6bd
 Built:        Wed Mar  2 00:15:12 UTC 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 85
 Running: 62
 Paused: 0
 Stopped: 23
Images: 100
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 9
 node002: 11.222.236.56:2375
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.185 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:45:53Z
 node003: 11.222.235.122:2375
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.185 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:46:00Z
 node004: 11.222.233.157:2375
  └ Status: Healthy
  └ Containers: 9
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.185 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:45:45Z
 node005: 11.222.239.54:2375
  └ Status: Healthy
  └ Containers: 9
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.178 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:45:57Z
 node006: 11.222.237.54:2375
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.185 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:45:34Z
 node007: 11.222.235.121:2375
  └ Status: Healthy
  └ Containers: 9
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.185 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:45:52Z
 node008: 11.222.232.158:2375
  └ Status: Healthy
  └ Containers: 9
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.178 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:45:56Z
 node009: 11.222.238.55:2375
  └ Status: Healthy
  └ Containers: 9
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.185 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:45:35Z
 node010: 11.222.236.55:2375
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.185 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.2, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-04-09T06:46:11Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 4.4.2
Operating System: linux
Architecture: amd64
CPUs: 36
Total Memory: 73.65 GiB
Name: 4b18a651aff1
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Steps to reproduce the issue:**
1. Run `docker run ubuntu ls`

**Describe the results you received:**

`Unrecognized input header: 99`

**Describe the results you expected:**

The result of `ls`

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker deamon of each swarm host is v1.10.3 but client is v1.11.0-dev. It works fine if the client is v1.10.3.

**Comment by cpuguy83** [comment] 2016-04-11 14:03
Is this only with swarm?

**Comment by npcode** [comment] 2016-04-11 15:47
@cpuguy83 Yes. Without swarm, I could see this error:

`Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)`

**Comment by cpuguy83** [comment] 2016-04-11 16:22
@npcode This looks like you have a client built from master talking to docker 1.10.x

**Comment by npcode** [comment] 2016-04-11 16:31
@cpuguy83 Yes, you are right.

**Comment by cpuguy83** [comment] 2016-04-11 16:32
@npcode This bug was only fixed in docker 1.10.3, and it is a daemon side bug.

**Comment by thaJeztah** [comment] 2016-04-12 09:23
@npcode can you try upgrading your daemons to 1.10.3, and see if you're still able to reproduce?

**Comment by npcode** [comment] 2016-04-12 09:33
@thaJeztah My daemons are already 1.10.3. Do you mean 1.11.0-dev? It works fine with 1.11.0-dev daemons.

**Comment by thaJeztah** [comment] 2016-04-12 09:37
@npcode oh, sorry, I probably misinterpreted @cpuguy83's comment (and didn't scroll up)

**Comment by cpuguy83** [comment] 2016-04-12 14:58
@npcode Please provide the `docker info` output from the docker node (not via Swarm).

**Comment by npcode** [comment] 2016-04-14 09:59
@cpuguy83 Here it is:
```
Containers: 10
 Running: 5
 Paused: 0
 Stopped: 5
Images: 11
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.4.2
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: dev-p002.ncl
ID: VCJ7:UB6S:MHXH:N5FN:AVGC:VOWW:XW4Q:VPMR:EZ2N:L6AH:IYOA:YA3V
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: consul://11.222.236.191:8500
Cluster advertise: 11.222.236.56:2375
```

**Comment by calavera** [comment] 2016-04-15 16:30
Can you double check that the daemon version is 1.10.3 final? It looks like this commit is missing in that version:

https://github.com/docker/docker/commit/a483ccc5dfb176178dec74ae7bbdc87a949c743e

Or swarm is doing something wrong with the stream.

**Comment by npcode** [comment] 2016-04-18 01:59
@calavera Yes. In every node `docker version` says the version is 1.10.3.

**Comment by npcode** [comment] 2016-04-18 06:43
This problem still exist with docker client 1.12.0-dev, swarm/1.2.0 and docker daemon 1.11.0.

**Comment by monochromec** [comment] 2016-04-20 16:45
Still present in 1.10.3-1 (Arch x86_64) with the same swarm config described above.

**Comment by cpuguy83** [comment] 2016-04-20 16:59
This is likely swarm sending an unexpected response, then.

**Comment by npcode** [comment] 2016-04-21 00:53
@cpuguy83 Docker client seems to expect the response starts with 0(stdin), 1(stdout) or 2(stderr) but swarm responses "client is newer than server (client API version: 1.24, server API version: 1.22)" which starts with 'c'(ascii code 99). So the client displays the error "Unrecognized input header: 99".

**Comment by monochromec** [comment] 2016-04-21 03:54
Interesting as this concerns the most basic of use cases: running hello-world against a swarm.

Is somebody from upstream looking at this? I suppose it's not the best of experiences for novices trying to set up a swarm for the first time and running into this problem right away.

**Comment by schmunk42** [comment] 2016-04-26 11:39
Same error here when running an `nginx` container.
Node has `swarm:1.2.0` running on docker `1.9.0`. 
swarm-master is `1.1.3` running on `1.10.3`.

Can I downgrade the API version on the swarm master?

**Comment by thaJeztah** [comment] 2016-04-26 11:43
ping @vieux ^^

**Comment by schmunk42** [comment] 2016-04-26 11:50
These are my swarm versions...

```
root@PAUL-roj:/repo/stacks# docker ps -f name=swarm -a
docker ps -f name=swarm -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
42abc259d47c        swarm:1.2.0         "/swarm join --heartb"   11 minutes ago      Up 11 minutes       2375/tcp            PAUL-hz2/swarm-agent
13725150fe73        swarm:1.1.3         "/swarm join --heartb"   14 hours ago        Up 14 hours         2375/tcp            PAUL-hz-1-121/swarm-agent
18babad924a5        swarm:1.1.3         "/swarm join --heartb"   3 weeks ago         Up 11 days          2375/tcp            PAUL-ssl1/swarm-agent
51749f32054e        swarm:1.1.3         "/swarm join --heartb"   3 weeks ago         Up 3 weeks          2375/tcp            PAUL-p3/swarm-agent
7142d8d072b0        swarm:1.1.3         "/swarm join --heartb"   3 weeks ago         Up 3 weeks          2375/tcp            PAUL-p5/swarm-agent
cc57d7e06a42        swarm:1.1.3         "/swarm join --advert"   3 weeks ago         Up 3 weeks                              PAUL-m2/swarm-agent
e6fb2ec8e17c        swarm:1.1.3         "/swarm manage --tlsv"   3 weeks ago         Up 3 weeks                              PAUL-m2/swarm-agent-master
```

Corresponding machine versions

```
docker-machine ls
NAME            ACTIVE      DRIVER      STATE     URL                         SWARM              DOCKER    ERRORS
PAUL-hz2        -           generic     Running   tcp://111.222.192.171:2376                       v1.9.0    
PAUL-hz-1-121   -           generic     Running   tcp://111.222.161.121:2376                      v1.11.0   
PAUL-m2         * (swarm)   amazonec2   Running   tcp://222.33.250.130:2376    PAUL-m2 (master)   v1.10.3   
PAUL-p3         -           amazonec2   Running   tcp://111.222.118.112:2376    PAUL-m2            v1.9.1    
PAUL-p5         -           amazonec2   Running   tcp://111.222.107.195:2376    PAUL-m2            v1.9.1    
PAUL-ssl1       -           amazonec2   Running   tcp://111.222.38.57:2376      PAUL-m2            v1.10.3   
```


If a container ends up on a `1.10` node events are sent

```
root@PAUL-roj:/repo/stacks# docker events
docker events
2016-04-26T11:45:01.285514522Z container kill 14de51dda7f27c32e7ebef34353e1e61d4a0ee5b27f5c031bf8fe0ebdeeabf2e (node.ip=222.33.250.130, node.name=PAUL-m2, com.docker.swarm.id=ac15d5cb40635b2561bf58b11f4158293a88d98751a182691f55e97c5632f48f, image=nginx, name=nauseous_yalow, node.addr=222.33.250.130:2376, node.id=XW7I:JSCM:3Z4O:R3OK:ZTCM:HLOL:DRAQ:GBAS:XHHT:AXB6:4FUA:CMHR)
2016-04-26T11:45:01.306062359Z container die 14de51dda7f27c32e7ebef34353e1e61d4a0ee5b27f5c031bf8fe0ebdeeabf2e (node.name=PAUL-m2, com.docker.swarm.id=ac15d5cb40635b2561bf58b11f4158293a88d98751a182691f55e97c5632f48f, image=nginx, name=nauseous_yalow, node.addr=222.33.250.130:2376, node.id=XW7I:JSCM:3Z4O:R3OK:ZTCM:HLOL:DRAQ:GBAS:XHHT:AXB6:4FUA:CMHR, node.ip=222.33.250.130)
2016-04-26T11:45:01.451780071Z network disconnect 5256dadbaaee6ca2bfe10a87f715fbed616bbe039a3dce5fa4cffdc1b1251b14 (type=bridge, container=14de51dda7f27c32e7ebef34353e1e61d4a0ee5b27f5c031bf8fe0ebdeeabf2e, name=bridge, node.addr=222.33.250.130:2376, node.id=XW7I:JSCM:3Z4O:R3OK:ZTCM:HLOL:DRAQ:GBAS:XHHT:AXB6:4FUA:CMHR, node.ip=222.33.250.130, node.name=PAUL-m2)
```

But on a `1.9` node I just get this "event"

```
2016-04-26T11:42:08.095856776Z    (node.addr=111.222.107.195:2376, node.id=L3TC:POU2:JXUM:FUJS:EASB:WCDO:OW6M:B6C4:ZWHJ:MMD5:5OLL:B3SJ, node.ip=111.222.107.195, node.name=PAUL-p5)
2016-04-26T11:42:08.496530763Z    (node.addr=111.222.107.195:2376, node.id=L3TC:POU2:JXUM:FUJS:EASB:WCDO:OW6M:B6C4:ZWHJ:MMD5:5OLL:B3SJ, node.ip=111.222.107.195, node.name=PAUL-p5)
```

:(

**Comment by thaJeztah** [comment] 2016-04-26 12:01
@schmunk42 please don't report different issues as a comment. docker 1.10 received a massive feature update in the docker events system (see https://github.com/docker/docker/pull/18888), and those features aren't in 1.9 yet. Having said that, could you open your comment as an issue in the https://github.com/docker/swarm/issues issue-tracker, because I think it has to be solved there

**Comment by schmunk42** [comment] 2016-04-26 12:09
Sorry, I didn't meant to report a different issue, but more details about the error.
Basically the fact, that I *also got no event*, when I got the error `Unrecognized input header: 99`.

**Comment by isodude** [comment] 2016-07-19 09:13
Still present in 
Docker version 1.12.0-rc4, build e4a0dbc, experimental and Docker version 1.11.2, build b9f10c9 on the swarm nodes.
It should be noted that I did not intentionally install experimental version of docker. I installed it on Mac OS X so I assume that the experimental version is needed.

**Comment by mikegcoleman** [comment] 2016-08-24 03:29
Just ran into this myself

`$ docker run hello-world
Unrecognized input header: 99

$ docker version
Client:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      ucp/1.1.2
 API version:  1.22
 Go version:   go1.6.2
 Git commit:   bbb5902
 Built:        Mon Jul 18 18:01:57 UTC 2016
 OS/Arch:      linux/amd64`

**Comment by Haybu** [comment] 2016-09-21 05:43
getting the same, with docker client API version 1.24 and server API version 1.22

**Comment by mayli** [comment] 2016-10-27 00:30
```
$ docker run hello-world
Unrecognized input header: 99
$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   bb80604
 Built:        Sun Oct 16 07:57:31 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   eaa53c7
 Built:        Fri May 27 17:25:03 UTC 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2016-10-27 00:51
For those running into this;

- make sure you run the current version of swarm
- if you're using a newer client, override the API version to use through the `DOCKER_API_VERSION` environment variable https://docs.docker.com/engine/reference/commandline/cli/#/environment-variables

We are working on improving detection of supported API versions (so that the client automatically falls back to an older version), but the above instructions should help you further

**Comment by liyaka** [comment] 2016-12-20 21:09
Get this error with docker 1.13 rc4 on RHEL 7 swarm mode
(I have the same system running smoothly on Ubuntu 14.04)
Some of the services stuck with "pending" status forever and others run as expected.
When I run `docker service logs` for a pending service I see only one line:
`Unrecognized input header: 69`

**Comment by thaJeztah** [comment] 2016-12-20 21:52
Yes, please open a new issue. The issue mentioned here is for "classic" swarm

**Comment by thaJeztah** [comment] 2016-12-20 21:55
FWIW, ASCII 69 is capital `E`, so probably something starting with `Error`, so may be worth checking server logs in debug mode. @liyaka

**Comment by thaJeztah** [comment] 2017-03-22 16:33
@ncode is this still an issue?

**Comment by barrachri** [comment] 2017-06-16 23:53
Having the same issue.

**Comment by barrachri** [comment] 2017-06-16 23:54
```
 [88] → docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```
 [89] → docker info
Containers: 23
 Running: 7
 Paused: 0
 Stopped: 16
Images: 49
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: kb250wz2r9a1al46ftievfk6j
 Is Manager: true
 ClusterID: rj7qxi8ueue86sd2wusap133q
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: AUNS:DNHM:XSIS:AFRX:45PH:XMQV:G2D7:OTKJ:N7IO:AEGU:JOMM:GV26
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 106
 Goroutines: 225
 System Time: 2017-06-16T23:54:10.615775774Z
 EventsListeners: 8
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-06-17 09:48
Closing, because of inactivity, and docker has API version negotiation now, which should help with this

**Closed by thaJeztah** 2017-06-17 09:48 UTC
Labels: status/more-info-needed
