### ISSUE TITLE
Comments are not being respected

### ISSUE THREAD

**Issue by jdnrg** [moby/moby#37841] opened 2018-09-13 17:18 UTC
# Given a Dockerfile like this 
```
from centos
# this comment1 is ignored '
VOLUME /tmp # this comment2 is not ignored but does not fail ]
VOLUME /tmp # this comment3 is not ignored but does not fail [
VOLUME /tmp # this comment4 is not ignored and fails "
VOLUME /tmp # this comment5is not ignored and fails '

```

# error 
```
docker build .
Sending build context to Docker daemon  3.072kB
Step 1/5 : from centos
 ---> 5182e96772bf
Step 2/5 : VOLUME /tmp # this comment2 is not ignored but does not fail ]
 ---> Using cache
 ---> 1650827afaec
Step 3/5 : VOLUME /tmp # this comment3 is not ignored but does not fail [
 ---> Using cache
 ---> b99b0fedfbd2
Step 4/5 : VOLUME /tmp # this comment4 is not ignored and fails "
failed to process "\"": unexpected end of statement while looking for matching double-quote

```

# version

```
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd
```

**Comment by thaJeztah** [comment] 2018-09-13 17:51
Dockerfile comments must start at the start of a line, any other position is considered regular input.

In your example, multiple volumes will be defined in the image; for example, this line;

```Dockerfile
VOLUME /tmp # this comment2 is not ignored but does not fail ]
```

Will create these volumes;

- `/tmp`
- `/#` 
- `/this`
- `/comment2`
- `/is`
- `/not`
- `/ignored`
- `/but`
- `/does`
- `/not`
- `/`fail`
- `]`

Which will be visible if you inspect the image;

```
            "Volumes": {
                "#": {},
                "/tmp": {},
                "]": {},
                "but": {},
                "comment2": {},
                "does": {},
                "fail": {},
                "ignored": {},
                "is": {},
                "not": {},
                "this": {}
            },
```

This is not a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2018-09-13 17:51 UTC
Labels: area/builder

**Comment by jdnrg** [comment] 2018-09-13 18:28
Thank you for the clarification, hope this will help the next guy.
