### ISSUE TITLE
docker pull image ignore locally self built images

### ISSUE THREAD

**Issue by andyxning** [moby/moby#33074] opened 2017-05-08 03:37 UTC
I have `docker tag busybox:latest mine:demo` in my local dev env. When doing `docker pull mine:demo`, it seems that docker will ignore locally built image and try to connect to docker hub. This is confusing and finally output some error

> Error response from daemon: repository mine not found: does not exist or no pull access

docker version:
> Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 17:45:49 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 17:45:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by cpuguy83** [comment] 2017-05-08 15:15
This is because image naming and transport are coupled together.
Saying you want to `pull mine:demo` means you are looking for an image named `mine:demo` on the default registry, which is tied to docker hub currently.

How come you are trying to pull an image you have local already?

**Comment by thaJeztah** [comment] 2017-05-08 15:17
The `docker pull` command is _meant_ to pull an image from a registry; even if an image with that name is available locally, because there may be a more recent version of the image. The registry is intended to be the source of truth here

```
docker pull --help

Usage:	docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry
```

I'll close this issue because I this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-05-08 15:17 UTC
Labels: area/distribution, status/more-info-needed, version/17.04

**Comment by andyxning** [comment] 2017-05-08 15:27
@thaJeztah @cpuguy83 
Web cache is working like this:
* check if local cache is available
* if available, we should check whether it is up to date with origin by using http Etag or 
* if local cache is up to date, it is fine to use local cache. Otherwise, we need to get new resource content to update local cache.

Can `docker pull` work like this.

**Comment by thaJeztah** [comment] 2017-05-08 15:35
just `docker run` should do that; if there's no local image, try to pull it, otherwise use the local version. If won't check if there's a newer version of the image though.

However, `docker pull` always checks with the remote registry (or a local pull-through mirror, if configured).

> If local cache is up to date, it is fine to use local cache. 

I'm not sure that translates directly; what is "up to date" if there's an image/resource in the local cache that does not exist on the _actual_ server?

**Comment by andyxning** [comment] 2017-05-09 01:33
@thaJeztah Thanks for you explanation.

>I'm not sure that translates directly; what is "up to date" if there's an image/resource in the local cache that does not exist on the actual server?

This may be application orthogonal. Web browser may choose to use local cache, while docker can choose to stop run the instance and provide some error info about this.
