### ISSUE TITLE
make "container ls" filter syntax accept negations

### ISSUE THREAD

**Issue by fjakop** [moby/moby#34736] opened 2017-09-06 07:30 UTC
Using docker-ce 17.06 `docker container ls` will not accept the same filter syntax as e.g. `docker container prune`.

    docker container ls --filter "label=foobar"

produces the expected results whereas

    docker container ls --filter "label!=foobar"

yields 

    Error response from daemon: Invalid filter 'label!'

The very same negation syntax works with `docker container prune` so imho it should be working with `ls` also.

    docker version
    Client:
     Version:      17.06.1-ce
     API version:  1.30
     Go version:   go1.8.3
     Git commit:   874a737
     Built:        Thu Aug 17 22:51:12 2017
     OS/Arch:      linux/amd64
    
    Server:
     Version:      17.06.1-ce
     API version:  1.30 (minimum version 1.12)
     Go version:   go1.8.3
     Git commit:   874a737
     Built:        Thu Aug 17 22:50:04 2017
     OS/Arch:      linux/amd64
     Experimental: false

**Comment by thaJeztah** [comment] 2017-09-20 23:41
This looks to be a duplicate of https://github.com/moby/moby/issues/13533; let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2017-09-20 23:41 UTC
Labels: kind/enhancement, version/17.06
