### ISSUE TITLE
docker build fails on Windows 10

### ISSUE THREAD

**Issue by raj-o** [moby/moby#40851] opened 2020-04-22 14:30 UTC
docker build .
Sending build context to Docker daemon  3.248GB
Step 1/16 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> fdf6432edbdc
Step 2/16 : LABEL maintainer sumit.x.kumar@oracle.com
 ---> Running in 278d34409243
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2020-04-24 06:40
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.


Also, are you running Windows bare metal, in a VM, in the Cloud? And what version of Windows are you running?

Closing this issue because there's not enough information, but we can reopen if more information becomes available

**Closed by thaJeztah** 2020-04-24 06:40 UTC
Labels: platform/windows, status/more-info-needed

**Comment by raj-o** [comment] 2020-04-24 06:52
PS C:\Users\rajibdut\Desktop\DockerFiles> docker info
Client:
 Debug Mode: false

Server:
 Containers: 39
  Running: 0
  Paused: 0
  Stopped: 39
 Images: 2
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.778)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.76GiB
 Name: RAJIBDUT-IN
 ID: MOHA:MC7F:QQFU:XAU6:QQB4:XMNS:N5MC:2J5J:VMHO:3OMQ:LWZK:KFEE
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 44
  System Time: 2020-04-24T12:19:06.2295491+05:30
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

PS C:\Users\rajibdut\Desktop\DockerFiles> docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\Users\rajibdut\Desktop\DockerFiles>

I am running on Windows 10 laptop.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362

The simple way to reproduce it is:

PS C:\Users\rajibdut\Desktop\DockerFiles> docker build --isolation=hyperv .
Sending build context to Docker daemon  3.248GB
Step 1/16 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> fdf6432edbdc
Step 2/16 : LABEL maintainer sumit.x.kumar@oracle.com
 ---> Running in 2b1088341dee
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)

**Comment by thaJeztah** [comment] 2020-04-24 10:00
Is this only during build? Does `docker run -it --isolation=hyperv mcr.microsoft.com/windows/servercore:ltsc2019` work?

**Comment by raj-o** [comment] 2020-04-24 10:03
docker run -it --isolation=hyperv mcr.microsoft.com/windows/servercore:ltsc2019 
Works fine.

**Comment by raj-o** [comment] 2020-04-24 10:07
Here are first few lines of dockerfiles.

+++++++++++
# Base image
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# maintained by XXXXXXX
LABEL maintainer XXXXXXX

#copy golden db image after taking it from OTN
COPY /db_home.zip c:/data/db_home.zip
+++++++++++

If I comment LABEL, it fails on COPY
