### ISSUE TITLE
Contents of the windows certificate store no longer added to MobyVM

### ISSUE THREAD

**Issue by nlowe** [moby/moby#35977] opened 2018-01-10 20:22 UTC
**Description**

Extra `Trusted Root Certification Authorities` from the windows certificate store are no longer added to the MobyVM ca-certificates store in recent versions of docker-ce.

**Steps to reproduce the issue:**
1. Install docker-ce for windows
2. Start docker in linux container mode
3. Attempt to pull from or login to a private registry whose certificate is signed by an extra CA added to the `Trusted Root Certification Authorities` Store

**Describe the results you received:**

```bash
Error response from daemon: Get https://my.registry/v2/: x509: certificate signed by unknown authority
```

**Describe the results you expected:**

```bash
Login Succeeded
```

**Additional information you deem important (e.g. issue happens only occasionally):**

If you start the docker daemon in windows container mode, you can login and push/pull images to/from this registry successfully.

**Output of `docker version`:**

<details>
<summary>Working</summary>

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

</details>

<details>
<summary>Broken</summary>

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

</details>

**Output of `docker info`:**

<details>
<summary>Working</summary>

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: 3725:YPWW:A3WM:KDZ5:D5XN:LXBF:J57Z:ZLFI:FNEK:AF5B:OSRQ:ZRY5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 25
 System Time: 2018-01-10T20:10:30.4549742Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

</details>

<details>
<summary>Broken</summary>

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d102f05
ID: LDU6:6RMV:U5FG:R4ZD:LTLL:54FJ:IFFS:GKYP:EBJ6:6AEB:KN6B:M6BP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 35
 System Time: 2018-01-10T20:13:52.5306543Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Windows 10 machine. I did not see anything interesting in the docker logs but if you need something specific, please let me know. I believe the last version I used when this was working was `17.09.0-ce` or `17.09.1-ce`. I do not have the installer on hand at the moment to verify this though.

**Comment by nlowe** [comment] 2018-01-10 20:28
I found an old installer for `17.09.0-ce` and was able to login. I'm looking to see if I have one for `17.09.1-ce`

**Comment by tomthetommy** [comment] 2018-01-12 11:12
UPDATE: Version 17.12.0-ce-win47 (15139) has been released to fix this issue.

Confirmed the issue is resolved.

**Comment by thaJeztah** [comment] 2018-01-12 11:36
Thanks for the update @tomthetommy - let me go ahead and close this

In this case, this looks to be an issue specific to "Docker for Windows", so if you run into a similar issue in future, it's best to report this in the Docker for Windows issue-tracker; https://github.com/docker/for-win/issues 

Closing, but feel free to continue the conversation, and thanks for reporting 👍

**Closed by thaJeztah** 2018-01-12 11:36 UTC
Labels: platform/desktop, version/17.06

**Comment by nlowe** [comment] 2018-01-12 13:14
Thanks for the quick turnaround on this. It looked like the issue was with the moby vm so I wasn't quite sure what repo to open the issue against. I'll test the fix when I get in the office this morning.

**Comment by nlowe** [comment] 2018-01-12 14:48
I verified that extra certificates added to my Trusted Root store are used to verify registry certificates when operating in linux container mode. Thanks for the quick fix!
