### ISSUE TITLE
BuildKit: `docker build -t /tmp/Dockerfile .` tries to access other files in `/tmp`

### ISSUE THREAD

**Issue by kbulygin** [moby/moby#40660] opened 2020-03-10 08:53 UTC
**Description**

I preprocess Dockerfiles and put results to `/tmp`, then run `docker build`. When directory with Dockerfile contains a file which is not accessible to the current user (in my case it's `drwx------ 2 root root ... /tmp/pulse-.../`), `docker build` fails. The issue is experienced with BuildKit but not with the default builder.

(As a workaround, I now put Dockerfiles to separate directories.) 

**Steps to reproduce the issue:**

Run the following script:
```bash
#!/bin/bash

set -eux -o pipefail

[ $# = 0 ]

cd /tmp
mkdir testing
cd testing

{ echo 'FROM scratch'; echo 'COPY empty .'; } >Dockerfile

mkdir -m700 secret
sudo chown root:root secret

mkdir build
cd build

touch empty
export DOCKER_BUILDKIT
for DOCKER_BUILDKIT in '' 1; do
  docker build -f /tmp/testing/Dockerfile -t temporary . || echo "[exit $?]"
done
```

**Describe the results you received:**
```bash
+ '[' 0 = 0 ']'
+ cd /tmp
+ mkdir testing
+ cd testing
+ echo 'FROM scratch'
+ echo 'COPY empty .'
+ mkdir -m700 secret
+ sudo chown root:root secret
+ mkdir build
+ cd build
+ touch empty
+ export DOCKER_BUILDKIT
+ for DOCKER_BUILDKIT in '' 1
+ docker build -f /tmp/testing/Dockerfile -t temporary .
Sending build context to Docker daemon  2.074kB
Step 1/2 : FROM scratch
 ---> 
Step 2/2 : COPY empty .
 ---> Using cache
 ---> ecfc77bfe2e5
Successfully built ecfc77bfe2e5
Successfully tagged temporary:latest
+ for DOCKER_BUILDKIT in '' 1
+ docker build -f /tmp/testing/Dockerfile -t temporary .
[+] Building 0.0s (2/2) FINISHED                                                                                                                                                              
 => ERROR [internal] load build definition from Dockerfile                                                                                                                               0.0s
 => => transferring dockerfile: 82B                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                          0.0s
------
 > [internal] load build definition from Dockerfile:
------
failed to solve with frontend dockerfile.v0: failed to resolve dockerfile: failed to build LLB: error from sender: open /tmp/testing/secret: permission denied
+ echo '[exit 1]'
[exit 1]
```

**Describe the results you expected:**

I expected `docker build` to succeed, like without `secret`:
```bash
...
+ docker build -f /tmp/testing/Dockerfile -t temporary .
[+] Building 0.1s (5/5) FINISHED                                                                                                                                                              
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 69B                                                                                                                                                      0.0s
 => [internal] load build context                                                                                                                                                        0.0s
 => => transferring context: 26B                                                                                                                                                         0.0s
 => CACHED [1/1] COPY empty .                                                                                                                                                            0.0s
 => exporting to image                                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                                  0.0s
 => => writing image sha256:e9d8504ab4460ae3168c53a65b1a9175780499f0477200d47da0f14d50f138e3                                                                                             0.0s
 => => naming to docker.io/library/temporary                                                                                                                                             0.0s
```

In general, I expected no user data to be used outside the referenced Dockerfile and the building directory. E.g., if I simply had lots of unrelated data in `/tmp`, I guess the building would be slow for no apparent reason.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:32 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 42
  Running: 28
  Paused: 0
  Stopped: 14
 Images: 155
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: journald
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: qai193ap23u7450vo6atj86dn
  Is Manager: true
  ClusterID: 6a98n2v9nh1m6m5aa0ju839xf
  Managers: 3
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: ...
  Manager Addresses:
   ...
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
  userns
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.35GiB
 Name: host
 ID: CO2V:GL7M:6JCU:O22Q:QZVK:4BDS:ZR3Q:4VGJ:DI3W:EH6Y:4KSY:3AGR
 Docker Root Dir: /var/lib/docker/1000.998
 Debug Mode: false
 Username: kbulygin
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical.

**Comment by thaJeztah** [comment] 2020-03-10 10:16
My main suspect would be https://github.com/moby/buildkit/pull/901, which added support for a per-dockerfile `.dockerignore`. I guess BuildKit will look for a `Dockerfile.dockerignore` file (or, if I read your example correctly, a `.dockerignore`, as the same directory is the build-context?) to be present, and fails doing so.

**Comment by thaJeztah** [comment] 2020-03-10 10:17
Actually, I just recalled there's a tracking issue for this, and the problem is in the docker cli; https://github.com/docker/cli/issues/2249. Perhaps you copy your reproduction steps to that issue?

Let me close this one in favour of https://github.com/docker/cli/issues/2249, so that the discussion doesn't diverge.

Thanks for reporting!

**Closed by thaJeztah** 2020-03-10 10:17 UTC
Labels: area/builder, kind/bug, version/19.03

**Comment by kbulygin** [comment] 2020-03-10 12:28
@thaJeztah Thanks for finding a related issue! My issue is a duplicate, so I think my reproduction steps are not needed there.
