### ISSUE TITLE
Where is located the raw logs from a container?

### ISSUE THREAD

**Issue by menosprezzi** [moby/moby#36846] opened 2018-04-12 19:24 UTC
I need to access the logs from a container to do some rotate management.
In others linux based OS, docker stores log output in `/var/lib/docker/containers/`, but this path doesnt exists in Moby. Why? And where is located that file if even docker says it located in with `docker inspect --format='{{.LogPath}}' $INSTANCE_ID` command?

**Comment by cpuguy83** [comment] 2018-04-12 22:01
That's where it is located. However it would be best to configure docker to do the rotation. You can set this up at the daemon level which basically sets the defaults for all new containers but does not affect existing ones.
Or you can do this per container.
"--log-opt max-size=100mb --log-opt max-files=5" as an example. Docker will automatically rotate the files out when the log reaches 100mb. Also note that as of 18.04 there is support to enable compression as well.

**Comment by cpuguy83** [comment] 2018-04-12 22:02
Closing since this is not a bug, but feel free to discuss. Thanks!

**Closed by cpuguy83** 2018-04-12 22:02 UTC

**Comment by filipedf** [comment] 2018-04-12 22:24
@cpuguy83 Thanks for the support. 

As a coworker of @menosprezzi, i can give more data to the discussion. We are using the `Moby Linux 17.09.0-ce-aws1 stable (ami-147a936e)` on AWS. I defined a logrotate  in `deamon.json`, but since i could not restart the deamon ([related issue](https://github.com/docker/for-aws/issues/34)), i just sent a `SIGHUP` to the `dockerd` process.

But when i tried to access the log folder, to check the effect of the rotate, the OS reported ` No such file or directory`

I apologize because I think the best place of this issue would be the repository [docker/for-aws](https://github.com/docker/for-aws) but since the discussion started here, I will not miss the opportunity

**Comment by cpuguy83** [comment] 2018-04-13 00:06
Docker for AWS is a little funky. TTY's don't necessarily give you the real rootfs.... definitely best in the for-aws repo.
