### ISSUE TITLE
do you implement ‘docker run‘ command

### ISSUE THREAD

**Issue by zhaomin1993** [moby/moby#41968] opened 2021-02-03 10:17 UTC
do you implement ‘docker run‘ command？if implement,where it is,thanks

**Comment by thaJeztah** [comment] 2021-02-03 12:47
The `docker` CLI is maintained in a separate repository; the `run` command is implemented in this file; https://github.com/docker/cli/blob/70a00157f161b109be77cd4f30ce0662bfe8cc32/cli/command/container/run.go#L31-L32

Note that the `run` command is a combination of various actions, so it calls multiple API endpoints, depending on the options (e.g., a sequence of `docker image pull`, `docker container create`, `docker container start`, `docker container attach`)


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2021-02-03 12:47 UTC
Labels: kind/question
