### ISSUE TITLE
docker restart can cause service duplicates...

### ISSUE THREAD

**Issue by sblackstone** [moby/moby#33862] opened 2017-06-28 14:42 UTC
I ran "docker restart <containerid>" on a node in a swarm for a service..

The process restarts but the swarm also creates a new duplicate replica of that service.

```
donuts@docker01:~$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by dengqingpei1990** [comment] 2017-06-29 02:50
I think you should use `docker service update --force <service_name>` to restart a swarm mode service instead of using `docker restart` as `docker restart` is used for standalone containers not for swarm mode services

**Comment by sblackstone** [comment] 2017-06-29 04:27
Perhaps it should be an error condition?

**Comment by thaJeztah** [comment] 2017-06-29 04:35
Yes, this is expected. As @dengqingpei1990 explains, you should not manually stop/start containers that are part of a service (thus managed by docker). When creating a service, docker creates containers ("tasks") to back that service. Docker monitors the tasks, and if a task fails/stops, creates a new container to replace the one that stopped.

When running `docker restart <some container>`, effectively you're doing `docker stop <container>` followed by `docker <start container>`; docker sees that the container stopped, and starts a new container to replace it. It then stops managing the old container (it's not removed directly, so that you can inspect it, for example, to investigate why it failed).

There's an existing issue I opened a while back about disallowing stop/start/restart managed containers https://github.com/moby/moby/issues/23704. which contains some background information as well https://github.com/moby/moby/issues/23704#issuecomment-229847731

I'm closing this issue, because this is not a bug, but feel free to comment after I closed. Also feel free to participate in the discussion on the issue I linked

**Closed by thaJeztah** 2017-06-29 04:35 UTC
Labels: version/17.03

**Comment by dengqingpei1990** [comment] 2017-06-30 01:14
Shall we have a `docker service stop/start` command?

In some cases we only just want to stop services for few hours to do some maintenance and after that we'll start these services again. The only way I can do is to run a `docker service rm` to delete one service and create a new one soon afterwards. This is not so convenient and there is a lot of work to do if this service have huge configurations to be specified.

Also `docker service restart/rollback` is necessary. They are much more understandable than `docker service update --force/--rollback` 
@thaJeztah I do not know if I have made it clear. Sorry for my poor English. :)

**Comment by thaJeztah** [comment] 2017-06-30 01:23
For maintenance, you can always `docker service scale myservice=0` (or `docker service update --replicas=0`) and scale up afterwards
