### ISSUE TITLE
Docker re-pushes layers it has already said it pushed.

### ISSUE THREAD

**Issue by ghost** [moby/moby#27665] opened 2016-10-23 11:49 UTC
**Description**

Docker seems to have succeeded in uploading a chunk. It even says 'Pushed'. Then, when it restarts after a failure, it seems to forget, and starts re-loading all over again.

**Steps to reproduce the issue:**
1. Run: 'Docker push' on my machine
2.
3.

**Describe the results you received:**
On feature of the pushes that makes them take so long is that they seem to upload an entire segment. for example:

```
67aca2b232ea: Pushing [================================================>  ]   170 MB/177 MB
3ac0d1046245: Pushing [==================================================>] 86.27 MB/86.27 MB
```

Then, a few minutes later ( this is happening now, 11:18GMT, if you're looking in your log files) this:

```
67aca2b232ea: Pushing [==================================================>] 180.6 MB
3ac0d1046245: Pushing [==================================================>] 86.27 MB/86.27 MB
2c2153fbd032: Pushing [==================================================>] 8.102 MB
```

Then it looks like it's worked:

```
67aca2b232ea: Pushed
```

Then::

```
Sun 23 Oct 2016 13:27:42 SAST Run time:  0  days  1  hours  23  minutes  0  seconds
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

When I restart, with the same image, though:

```
67aca2b232ea: Pushing [=>                                                 ] 5.407 MB/177 MB
```

**Describe the results you expected:**
I'd hope the push would have worked, and, when it said 'pushed' it meant it, and didn't push again.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.1, build 6f9534c
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 32
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 10.73 GiB
Name: moby
ID: 6GPR:LWMN:B4KJ:DJJ4:SBOE:FZTP:7CU7:OVRG:4EMB:66CP:N7FP:AECM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 101
 System Time: 2016-10-23T11:46:25.961751259Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS/X:
Darwin Psyche.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

VirtualBox: [ not being used ]
Version 5.1.8 r111374 (Qt5.5.1)

**Comment by fustbariclation** [comment] 2016-10-24 06:17
Here's another example, today. The first shows '67aca2b232ea: Pushed'. Then, after a restart, '67aca2b232ea: Pushing [===========>                                       ] 42.25 MB/177 MB'.

It keeps doing this. 

> Mon Oct 24/10/2016 06:40:1477284032:N _mbsetupuser console Oct 23 17:04 peterbrooks console Oct 23 17:10 peterbrooks ttys000 Oct 23 17:10 peterbrooks ttys001 Oct 23 17:10 peterbrooks ttys002 Oct 23 17:10 Psyche.local
> The push refers to a repository [docker.synapse.org/syn7364819/blue]
> cbb4ded5a547: Pushed 
> 89d8ed9d3ad5: Pushed 
> 416488357c47: Pushed 
> 86c1ae136168: Pushed 
> 67aca2b232ea: Pushed 


after restart:

> Mon Oct 24/10/2016 08:09:1477289356:N _mbsetupuser console Oct 23 17:04 peterbrooks console Oct 23 17:10 peterbrooks ttys000 Oct 23 17:10 peterbrooks ttys001 Oct 23 17:10 peterbrooks ttys002 Oct 23 17:10 Psyche.local
> The push refers to a repository [docker.synapse.org/syn7364819/blue]
> cbb4ded5a547: Pushed 
> 89d8ed9d3ad5: Pushed 
> 416488357c47: Pushed 
> 86c1ae136168: Pushed 
> 67aca2b232ea: Pushing [===========>                                       ] 42.25 MB/177 MB

**Comment by thaJeztah** [comment] 2016-10-24 06:23
Are you seeing this problem as well when pushing to docker hub? What kind of registry are you running? The open source registry, or a third party registry?

**Comment by stevvooe** [comment] 2016-10-24 22:00
This looks like a duplicate.

**Comment by thaJeztah** [comment] 2016-10-24 22:16
Most likely a duplicate of https://github.com/docker/docker/issues/22188

**Comment by stevvooe** [comment] 2016-10-24 23:54
@thaJeztah #22188 is different. I have seen something similar to this, but I guess we can investigate separately, as I cannot find the other issue.

**Comment by fustbariclation** [comment] 2016-10-25 08:56
I am pushing this, as you can see, to synapse.org.

I'm going to try it to docker hub as well, and I'll let you know the result. I did try it before, and had a similar problem, but I didn't make a record of it, so I'll do it again.

**Comment by stevvooe** [comment] 2016-10-26 00:12
@fustbariclation Compare with a local registry at version 2.5.

**Comment by thaJeztah** [comment] 2021-06-30 17:30
Closing this because of age

**Closed by thaJeztah** 2021-06-30 17:30 UTC
Labels: area/distribution, status/more-info-needed
