### ISSUE TITLE
Cannot unshare without CAP_SYS_ADMIN, despite `/proc/sys/kernel/unprivileged_userns_clone`

### ISSUE THREAD

**Issue by staticfloat** [moby/moby#43086] opened 2021-12-16 01:22 UTC
**Description**

When running on a recent Linux kernel with the unprivileged user namespaces patches applied, I would expect that I can `unshare -U` without needing `CAP_SYS_ADMIN`.  However, I find that I cannot inside of docker.

**Steps to reproduce the issue:**

This does not work:
```
$ docker run --security-opt apparmor:unconfined -ti ubuntu /bin/bash -c "unshare -U"
unshare: unshare failed: Operation not permitted
```

While this does:
```
$ docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined -ti ubuntu /bin/bash -c "unshare -U"
$ 
```

Note that unprivileged namespaces are enabled:
```
$ cat /proc/sys/kernel/unprivileged_userns_clone 
1
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.2
 Built:             Mon Nov  1 00:34:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~20.04.2
  Built:            Fri Oct 22 00:45:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.3
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 32
  Running: 2
  Paused: 0
  Stopped: 30
 Images: 83
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-89-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.8GiB
 Name: kholin
 ID: KIAR:2M22:6OKX:HAIT:XWVI:6CVZ:L3SW:4UAE:42D5:AHKN:OZWL:QXCA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: staticfloat
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by AkihiroSuda** [comment] 2021-12-16 05:57
You need `--security-opt seccomp=unconfined` in addition to `--security-opt apparmor=unconfined`

**Comment by slonopotamus** [comment] 2023-09-23 08:55
I believe this is a duplicate of #42441.

**Closed** 2023-09-23 10:16 UTC
Labels: kind/question, kind/duplicate
