### ISSUE TITLE
Linear performance degradation as #networks  increases 

### ISSUE THREAD

**Issue by ezrasilvera** [moby/moby#19981] opened 2016-02-03 21:18 UTC
As part of Swarm testing I performed a comparison test to measure the network creation time done directly on the Docker engine.
It seems that the Docker engine itself has some linear increasing overhead when creating a network (I was using overlay networks). This seems like a significant overhead especially now that we can have hundreds of networks on the system.
While this is related to creating a network, I also noticed that the # of networks impacts other operations like create container, deleet network, etc..
![engine_nw](https://cloud.githubusercontent.com/assets/13567561/12797324/0c402862-cacc-11e5-996c-1b5c1aba0dd2.png)

**Comment by LK4D4** [comment] 2016-02-03 21:27
@ezrasilvera I think it can be a kernel-related issue, but I'll try to profile what we can do in userland.
ping @mrjana @mavenugo

**Comment by ezrasilvera** [comment] 2016-02-03 21:48
@LK4D4 probably need to also test with different plugins to see whether it is specific the  VXLAN kernel driver

**Comment by mavenugo** [comment] 2016-02-03 21:53
thanks @ezrasilvera. the numbers here are for pure `network create` using overlay drivers ?
Does that also include running containers on these overlay networks ?
If it is just network creates, overlay driver doesn't create bridges & hence it cannot be a kernel issue.

could you also share such data for bridge network ?

**Comment by ezrasilvera** [comment] 2016-02-03 22:17
@mavenugo You are correct this is just NW create so indeed no driver involvement yet. I also tested starting containers where you also see impact of the number of networks (even if there isn't any container attach to them) - i.e., creating a single container while there are 200 networks takes longer then creating the same container in the presence of only 1 NW in the system.
I'll try to run the these tests again and post the results

**Comment by ezrasilvera** [comment] 2016-02-11 20:49
I went through the libnetwork code and I think I located a possible issue. I analyzed the "network remove" operation that suffer from the same effect and I think the create has similar issue.
When you try to remove a network you basically need to update a specific key/value in the KV store, however the daemon GetNetwork() is doing so by using the controller WalNetworks() which in turn list/get all the networks from the KV and go through them to match the requested NW. 
Obviously such operation is linear with the number of networks and will not scale well.

**Comment by estesp** [comment] 2016-03-03 19:55
The Docker API checks for [name conflicts before doing the create](https://github.com/docker/docker/blob/master/api/server/router/network/network_routes.go#L83).  Given the KV datastore in the libnetwork controller is keyed on ID it takes a linear walk of all stores to verify no name clash. Deleting by name (versus ID) has a similar linear search, although it can be better because once the ID is found, that search ends, whereas a known non-clashing name will search all stores.

Are we agreeable to creating an index of sorts on the controller side--at least a simple `networks[name] = (bool)exists` to make O(1) by-name lookups which seem to be required for create/delete by name? Otherwise the daemon has to cache this information, and because of the distributed model this seems untenable on the daemon side..

**Comment by thaJeztah** [comment] 2016-03-04 00:26
Also related https://github.com/docker/docker/issues/18864

**Comment by jainvipin** [comment] 2016-05-01 17:27
@estesp thanks!
@mavenugo see the same with remote (global) drivers...

**Comment by erikh** [comment] 2016-05-01 18:23
You might be able to do this atomically by just writing the key with the `SetOptions` done right in etcd, unless you're writing to multiple places within the schema.

Not as sure what consul can do, but setting `PrevExist` to `PrevNoExist` in the options for `Set` will accomplish this with very little modification to your etcd client implementation. The write will only succeed if the key does not already exist.

**Comment by mavenugo** [comment] 2016-05-02 15:28
I didnt spend much time on this issue. Fetching the list of networks (in order to perform conflict check) is a bulk / single operation and that should not ideally cause such linear performance issue. The only possibility is the fact that instead of the bulk operation, if there is some operation that hits the KVStore Get request for each network. That can result in this situation. I will look into this and share my findings.

**Comment by estesp** [comment] 2016-05-05 17:53
Something strange is going on with list; not sure what yet. See #22322

**Comment by mavenugo** [comment] 2016-05-06 11:19
@estesp I dont think these are related (though I can see the symptoms are similar).

**Comment by JamieGarside** [comment] 2016-05-25 08:14
@mrjana we've actually been noticing similar behaviour to this. After a quick look through, it seems that the network clash checking, and actually all network operations do hit the K/V store for each network.

Many of these functions use [`WalkNetworks`](https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/libnetwork/controller.go#L581), which eventually calls [`getNetworksFromStore`](https://github.com/docker/docker/blob/14b5a50f0a95a2b8f3ed7ab7469bbab02189a09c/vendor/src/github.com/docker/libnetwork/store.go#L141). This itself goes and fetches all network from the store, and looks up the endpoint_count key for each one.

This problem is exaggerated by the fact that the Zookeeper K/V store driver doesn't support listing all the children of a key in a single operation, and hence must issue a get request for each child of the /networks key.

Moreover, because [`FindNetwork`](https://github.com/docker/docker/blob/14b5a50f0a95a2b8f3ed7ab7469bbab02189a09c/daemon/network.go#L24) always searches by name first, which requires the `WalkNetworks` function from earlier (referenced from https://github.com/docker/docker/blob/14b5a50f0a95a2b8f3ed7ab7469bbab02189a09c/vendor/src/github.com/docker/libnetwork/controller.go#L589), then you can't even optimise by specifying the network ID rather than the name.

**Comment by rachit1arora** [comment] 2017-09-23 04:17
Any recommendations on this issue? How to resolve it?

**Comment by mefyl** [comment] 2018-04-25 13:43
I have tried reproducing this without success. On a 100 nodes cluster, I created 200 networks, and even attached containers from other nodes to each one to make *sure* they were registered in the KV store. Network creation time stays constant (~80ms), so does attached container creation (~750ms).

Docker version is `17.06.2-ee-8-dev`.

**Comment by thaJeztah** [comment] 2018-04-25 22:40
Thanks @mefyl - let me close this issue for now, as it looks like this has been addressed

**Closed by thaJeztah** 2018-04-25 22:40 UTC
Labels: area/networking, kind/performance
