### ISSUE TITLE
--iptables=false don't work in 1,7.1

### ISSUE THREAD

**Issue by tom916** [moby/moby#15357] opened 2015-08-06 07:29 UTC
## uname -a

```
Linux test.com 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 14.04 LTS 
```
## docker version

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```
## docker -D info

```
Containers: 66
Images: 52
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 184
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 2.905 GiB
Name: test.com
ID: F7MG:35JZ:KSOD:G7IZ:E34D:IOQR:E6NP:OE73:CK34:4KRJ:G4SR:VZIL
WARNING: No swap limit support
```
## I want to disable iptables ,so I disabled some so,then I found docker.io also use iptalbes ,and blocked

```
# add in /etc/modprobe.d/blacklist-firewire.conf

blacklist xt_conntrack
blacklist ipt_MASQUERADE
blacklist iptable_nat
blacklist nf_conntrack_ipv4
blacklist nf_defrag_ipv4
blacklist nf_nat_ipv4
blacklist nf_nat
blacklist nf_conntrack
blacklist nf_conntrack_ipv4


root       985     1  0 15:20 ?        00:00:00 /usr/bin/docker -d -b br0 --icc=true --ip-forward=false --iptables=false
root      2059   985  0 15:20 ?        00:00:00 /sbin/iptables --wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
```

**Comment by cpuguy83** [comment] 2015-08-06 14:29
Is this an exact duplicate of your previous issue that was on 1.5?
When I stop docker, flush all iptables rules, and then start docker with `--iptables=false`, iptables remains empty.
Adding containers with port specs, links, etc, still no new rules in iptables.

**Comment by tom916** [comment] 2015-08-07 06:49
@ cpuguy83 

To reproduce this problem，you need 
first add those in /etc/modprobe.d/blacklist.conf

```
blacklist xt_conntrack
blacklist ipt_MASQUERADE
blacklist iptable_nat
blacklist nf_conntrack_ipv4
blacklist nf_defrag_ipv4
blacklist nf_nat_ipv4
blacklist nf_nat
blacklist nf_conntrack
blacklist nf_conntrack_ipv4
```

second set DOCKER_OPTS , I had add a brage br0 

```
DOCKER_OPTS="-b br0 --icc=true --ip-forward=false --iptables=false"
```

third reboot ，cause set blacklist need restart 

and the reason you failed may be ,you just add blacklist and not reboot

**Comment by SqiSch** [comment] 2016-01-28 15:14
+1. Running into exactly the same problem.

**Comment by akerouanton** [comment] 2024-03-04 10:02
This issue went stale, so let me close it.

**Closed by akerouanton** 2024-03-04 10:02 UTC
Labels: area/networking, version/1.7
