### ISSUE TITLE
docker compose config or run: validating docker-compose.override.yml failed environment array items[0,1] must be unique

### ISSUE THREAD

**Issue by jliebert** [moby/moby#47122] opened 2024-01-19 22:05 UTC
### Description

docker compose run or config failed with error:
validating docker-compose.override.yml failed environment array items[0,1] must be unique

### Reproduce

Two docker-compose file in web directory:

web/docker-compose.yml:

```
services:
  web:
    image: traefik/whoami
    environment:
      TEST: 2
```

web/docker-compose.override.yml

```
services:
  web:
    environment:
      TEST: ${TEST}
```
```
web$ TEST=1 docker compose config 
```
```
name: web
services:
  web:
    environment:
      TEST: "1"
    image: traefik/whoami
    networks:
      default: null
networks:
  default:
    name: web_default
```
# OK
```
web$ TEST=2 docker compose config
```
```
validating /app/web/docker-compose.override.yml: services.web.environment array items[0,1] must be unique
```
# KO

### Expected behavior

- docker compose config should display config without failed about override of variable with same value.
- docker compose run should run the container without failed about override of variable with same value. 

I should override TEST environment value with whatewer independently of parent docker-compose.yml value.
This work perfectly before on 24.0.X. (<25.0.0)

### docker version

```bash
Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 107
  Running: 8
  Paused: 0
  Stopped: 99
 Images: 228
 Server Version: 25.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.31GiB
 Name: j8
 ID: QKMX:4L6O:ZDPM:HLXD:OUH3:LAL7:GK6C:QFTD:IYAR:WLS3:43QA:6M7M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.17.0.0/16, Size: 24
   Base: 172.18.0.0/16, Size: 24
```

### Additional Info

Bug on Ubuntu 22.0.4 with:
docker-buildx-plugin              0.12.1-1~ubuntu.22.04~jammy                            amd64
docker-ce                                  5:25.0.0-1~ubuntu.22.04~jammy                          amd64
docker-ce-cli                             5:25.0.0-1~ubuntu.22.04~jammy                          amd64
docker-ce-rootless-extras      5:25.0.0-1~ubuntu.22.04~jammy                          amd64
docker-compose-plugin         2.24.1-1~ubuntu.22.04~jammy                            amd64

Bug on Debian 11 with:
docker-buildx-plugin           0.12.1-1~debian.11~bullseye    amd64     
docker-ce                      5:25.0.0-1~debian.11~bullseye  amd64       
docker-ce-cli                  5:25.0.0-1~debian.11~bullseye  amd64       
docker-ce-rootless-extras      5:25.0.0-1~debian.11~bullseye  amd64 
docker-compose-plugin          2.24.1-1~debian.11~bullseye    amd64

**Comment by thaJeztah** [comment] 2024-01-20 00:18
Thanks for reporting; this looks to be an issue with Docker Compose, which is a separate project, and not maintained here.

It looks like this issue was already reported, and a fix was implemented (but not yet released)

- https://github.com/docker/compose/issues/11371
- https://github.com/compose-spec/compose-go/pull/533

I'll close this ticket here, as there's nothing actionable in this repository, and it looks like the issue is already addressed in the compose repository.

**Closed by thaJeztah** 2024-01-20 00:18 UTC
Labels: status/0-triage, kind/bug
