### ISSUE TITLE
running docker export creates corrupted tar 

### ISSUE THREAD

**Issue by slapers** [moby/moby#33730] opened 2017-06-19 08:28 UTC
**Description**

Exporting a container which has node and npm packages installed results in a corrupted tar.
A lot of files seem to have lost their path information and are in the root of the filesystem. 
Also tar warns about a corrupted tar archive.

**Steps to reproduce the issue:**
```
docker pull node
docker run -it --name ngcli node npm install --unsafe-perm -g @angular/cli
docker export ngcli -o exported_ngcli.tar
```

**Describe the results you received:**

```
tar -tvf exported_ngcli.tar
..
..
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Error exit delayed from previous errors.
```

A lot of files that were in `/usr/local/lib/node_modules` are now in the /
```
tar -tvf exported_ngcli.tar | egrep '\spackage.json'
-rw-r--r--  0 501         20          2011 Jun 19 10:01 package.json
-rw-r--r--  0 503         20          1981 Jun 19 10:01 package.json
-rw-r--r--  0 501         20          2017 Jun 19 10:01 package.json
-rw-r--r--  0 501         20          2313 Jun 19 10:01 package.json
-rw-r--r--  0 501         20          1350 Jun 19 10:01 package.json
```

**Describe the results you expected:**

A correct tar.

**Additional information you deem important (e.g. issue happens only occasionally):**

I don't seem to have the issue on docker on linux with aufs.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 16
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: ZBBU:FIKL:LJOT:7G4O:WLJM:MO5C:G6GF:2YXC:SR2D:JUOE:CDUV:7GWF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-06-19T08:05:12.3368167Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: slapers
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aaronlehmann** [comment] 2017-07-11 23:52
ping @dmcgowan

**Comment by thaJeztah** [comment] 2017-07-11 23:56
I think there's another issue tracking this, and this was due to Go not supporting long paths. Let me try and find the issue

**Comment by thaJeztah** [comment] 2017-07-11 23:58
Yes, looks like this is a duplicate of https://github.com/moby/moby/issues/29360, which was marked as related to https://github.com/golang/go/issues/17630

**Comment by thaJeztah** [comment] 2017-07-12 00:02
Let me close this issue as it's a duplicate of https://github.com/moby/moby/issues/29360. Please continue the discussion over there 👍

**Closed by thaJeztah** 2017-07-12 00:02 UTC
Labels: area/distribution, version/17.03
