### ISSUE TITLE
Unable to restart network service within the container

### ISSUE THREAD

**Issue by hard-fault** [moby/moby#35574] opened 2017-11-22 14:42 UTC
I have started the container with following flags:
--cap-add=NET_ADMIN 
--cap-add=NET_RAW 
--priveleged=true

despite that I am not allowed to restart the service.

[root@bde8d93f7d6c /]# systemctl restart network
Failed to get D-Bus connection: Operation not permitted

**Comment by ripcurld0** [comment] 2017-11-22 14:53
@hard-fault can you copy-paste `docker info` and `docker version` output alongside with kernel version and Linux distribution?

**Comment by thaJeztah** [comment] 2017-11-22 15:03
> Failed to get D-Bus connection: Operation not permitted

This error is because running `systemctl restart network` will try to interact with `systemd`. Containers are not VM's, and unless you have your container setup to use `systemd` as an init process to start multiple services, systemd won't be available inside the container.

Think of containers as a "sandboxed" process; you run a single process, and that's sandboxed using namespaces, cgroups. In addition, with docker networking, networking functions a bit different from a regular host; see https://docs.docker.com/engine/userguide/networking/, and https://www.slideshare.net/Docker/docker-networking-deep-dive for more information as to how things are done under the hood.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-22 15:03 UTC
Labels: status/more-info-needed

**Comment by hard-fault** [comment] 2017-11-23 08:05
Thanks for the suggestions Sebastian.

I integrated the systemd into my container using this link - https://github.com/docker-library/docs/tree/master/centos#systemd-integration 

and started the container as mentioned and with all the necessary flags(aforementioned).

I am able to change the default gateway.
[root@temp /]# ip route show
default via 172.19.0.1 dev eth0 
172.19.0.0/24 dev eth0 proto kernel scope link src 172.19.0.6 
[root@temp /]# route add default gw 172.19.0.5
[root@temp /]# route delete default gw 172.19.0.1
[root@temp /]# ip route show
default via 172.19.0.5 dev eth0 
172.19.0.0/24 dev eth0 proto kernel scope link src 172.19.0.6 

But I am still not able to restart the network.

[root@temp /]# systemctl restart network
Failed to get D-Bus connection: Operation not permitted
