### ISSUE TITLE
Ability to change volume labels after creation

### ISSUE THREAD

**Issue by EliRibble** [moby/moby#33745] opened 2017-06-20 15:49 UTC
I have some volumes that have contents that are automatically generated. I'd like to keep the MD5 of the contents in the label on the volume. Unfortunately, I can't change the labels on a volume after its created. It would be nice to be able to change volume labels after creation time, or to know why its not feasible to do so

**Comment by thaJeztah** [comment] 2017-09-25 16:57
looks like this is a duplicate of https://github.com/moby/moby/issues/25291, so let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2017-09-25 16:57 UTC
Labels: area/volumes, kind/feature
