### ISSUE TITLE
moby 26.1.5 postinstall fails on linux/arm64

### ISSUE THREAD

**Issue by hellt** [moby/moby#48987] opened 2024-11-28 18:07 UTC
### Description

when installing moby 26.1.5 via devcontainer feature defined like this:

```json
"features": {
        "ghcr.io/devcontainers/features/docker-outside-of-docker:1": {
            "version": "26.1.5",
            "dockerDashComposeVersion": "none"
        },
```

I get the following in the installation log

```
 [2024-11-28T17:57:04.286Z] #51 23.16 Get:2 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main arm64 moby-cli arm64 26.1.5-debian12u1 [15.9 MB]

[2024-11-28T17:57:13.297Z] #51 32.05 Setting up moby-cli (26.1.5-debian12u1) ...
  #51 32.06 Error while loading /var/lib/dpkg/info/moby-cli.postinst: Exec format error
  #51 32.06 dpkg: error processing package moby-cli (--configure):
  #51 32.06  installed moby-cli package post-installation script subprocess returned error exit status 1
```

If this is a MSFT packaging problem I apologize

### Reproduce

create a devcontainer json file with the moby docker in docker or docker outside docker like this

```json
"features": {
        "ghcr.io/devcontainers/features/docker-outside-of-docker:1": {
            "version": "26.1.5",
            "dockerDashComposeVersion": "none"
        },
```

### Expected behavior

postinstall script doesn't fail on linux arm64

### docker version

```bash
NA
```

### docker info

```bash
NA
```

**Comment by thaJeztah** [comment] 2024-11-28 18:40
cc @cpuguy83

**Comment by hellt** [comment] 2024-11-28 19:39
I have tested 26.1.4/26.1.3 and 24.0.9, all of them fail on the postinstall script, that is likely having a non linux/arm64 binary in it

**Comment by thaJeztah** [comment] 2024-11-28 20:04
I _think_ those packages are built using this repository; https://github.com/Azure/moby-packaging


@cpuguy83 may be able to confirm (he works at Azure on packaging Microsoft's packages), but don't expect him to be around die to thanksgiving. A quick peek at that repository shows this as post install script for the CLI (not daemon) package https://github.com/Azure/moby-packaging/blob/a89212c50d501ebbb9a1cd3fe074170f7f6cc0c4/packages/moby-cli/postinstall/deb/postinstall#L5

Nothing architecture dependent in the script, unless the failure happens in the "addgroup". That said, ISTR that a bad shebang or newline endings also can produce an obscure error

**Comment by hellt** [comment] 2024-11-28 20:32
thanks @thaJeztah 
indeed, nothing too arch-dependent. The devcontainer repo is half alive it seems, so I don't expect to get any feedback there. I will wait for Brian or anyone from the azure team to have some time to have a look at that.

**Comment by hellt** [comment] 2024-11-29 07:56
Thank you for the pointer @thaJeztah 
it urged me to look into the postinst scripts for various packages that were available for selection from the [msft azure repo](https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod/pool/main/m/moby-cli/)

What I found out is that all arm64 version from 24.0.5 till 27.1.2 has the following postinstall script:

```bash
  #!/bin/sh
  set -e
  
  if ! grep -q "^docker:" /etc/group
  then
    addgroup --system docker
  fi
```

This script fails on linux/arm64 with the following error:

```
[2024-11-28T17:57:13.297Z] #51 32.05 Setting up moby-cli (26.1.5-debian12u1) ...
  #51 32.06 Error while loading /var/lib/dpkg/info/moby-cli.postinst: Exec format error
  #51 32.06 dpkg: error processing package moby-cli (--configure):
  #51 32.06  installed moby-cli package post-installation script subprocess returned error exit status 1
```

Then I took the `moby-cli_23.0.7+azure-debian12u1_arm64.deb` package for inspection, and there I found a different postinst script:

```bash
#!/bin/sh
set -e

case "$1" in
  configure)
    if ! grep -q "^docker:" /etc/group
    then
      addgroup --system docker
    fi
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.
```

and this one works! So apparently it is the `--configure` flag that is not handled in the newer version? Why is that? I don't have enought deb packaging experience to figure out what puts this argument in the first place.

**Comment by thaJeztah** [comment] 2024-11-29 09:10
> and this one works! So apparently it is the --configure flag that is not handled in the newer version? Why is that? I don't have enought deb packaging experience to figure out what puts this argument in the first place.


Interesting! The core functionality of both of those scripts is the same, but  (my knowledge is somewhat limited on all the nitty-gritty details) the `postinst` can be called in different stages of the install process, in which case it gets a different argument passed, and the `addgroup` should probably only be executed on one of those (`configure`), which is what that last variant is meant to do.

Here's the variant of the [`postinst` script that we ship with the `docker-ce` packages](https://github.com/docker/docker-ce-packaging/blob/50cb52e8d5ba0148d112f2886885425ca726668b/deb/common/docker-ce.postinst) (although we only ship it as part of the "daemon" (`docker-ce`) packages, not as part of the CLI package(s) - something we  could consider);

```bash
#!/bin/sh
set -e

case "$1" in
	configure)
		if [ -z "$2" ]; then
			if ! getent group docker > /dev/null; then
				groupadd --system docker
			fi
		fi
		;;
	abort-*)
		# How'd we get here??
		exit 1
		;;
	*)
		;;
esac

#DEBHELPER#
```

Worth noting that deb helpers may be adding additional scripts to that; i.e. this is what actually ends up in our package;

<details>

```bash
#!/bin/sh
set -e

case "$1" in
	configure)
		if [ -z "$2" ]; then
			if ! getent group docker > /dev/null; then
				groupadd --system docker
			fi
		fi
		;;
	abort-*)
		# How'd we get here??
		exit 1
		;;
	*)
		;;
esac

# Automatically added by dh_apparmor/3.0.8-3
if [ "$1" = "configure" ]; then
    APP_PROFILE="/etc/apparmor.d/docker-ce"
    if [ -f "$APP_PROFILE" ]; then
        # Add the local/ include
        LOCAL_APP_PROFILE="/etc/apparmor.d/local/docker-ce"

        test -e "$LOCAL_APP_PROFILE" || {
            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
        }

        # Reload the profile, including any abstraction updates
        if aa-enabled --quiet 2>/dev/null; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
        fi
    fi
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/init/docker.conf 5:24.0.5-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/docker" ]; then
		update-rc.d docker defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native docker $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'docker.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'docker.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'docker.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'docker.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'docker.socket' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'docker.socket'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'docker.socket' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'docker.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'docker.service' 'docker.socket' >/dev/null || true
	fi
fi
# End automatically added section
```

</details>

Looking at the variants you found, I actually wonder if the second one is _too_ restrictive (as it exits with a non-zero status on _anything_ other than `configure`), but perhaps that's by design (not sure); if you search, you'll find many similar examples, but those tend to add more accepted arguments (without exiting with a failure); https://grep.app/search?q=postinst%20called%20with%20unknown%20argument

**Comment by hellt** [comment] 2024-11-29 09:21
indeed, I think existing with rc=1 on the post install is likely a too drastic measure.

What still trips me is that the same postinstall script that doesn't work during the buildx on linux/arm64 works fine on linux/amd64. As if the postinst is called without an argument there...

Anyway, it seems we will need to wait for @cpuguy83 to comment on this and hopefully a fix or a workaround will be applied.

**Comment by cpuguy83** [comment] 2024-12-02 17:10
The difference between the scripts is the newer packages are not built with debbuild, the packaging is created by fpm (honestly, we plan to bring this back to debbuild soon).

I cannot reproduce the issue in a simple debian container (arm64, of course).
Also FWIW, we do run some smoke tests to make sure packages install properly and commands execute for every build.

Given the error (`exec format error`) I suspect the machine is either not arm64 or it has other non-compatible binaries on the system that it doesn't know how to execute.

**Comment by thaJeztah** [comment] 2024-12-07 13:30
Let me close the ticket here, as it's not something that can be addressed in this repository, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2024-12-07 13:30 UTC
Labels: status/0-triage, kind/bug

**Comment by hellt** [comment] 2024-12-07 13:43
Yes, I was just about to close it myself, since the error was fully on me.

The problem was that my build setup in gh actions was missing the Setup QEMU step:

```yaml
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
```

Unfortunately, I've lured myself in a rabbit hole by chasing all angles, but this one. The successful build of 23.0.7+azure led me to believe that something is wrong with the package, and not the build setup.

A good lesson, though. Maybe a clear(er) error message from the buildx action would help me to save a considerable amount of time, but it is what it is.
Sorry for the turbulence, hopefully this might help others who also forget to setup qemu when doing the multi arch builds

**Comment by thaJeztah** [comment] 2024-12-07 14:05
Good to hear it's resolved for you! For the better error messages; might be tricky; not sure what a good solution would be for that 🤔. For build; I _think_ buildkit may already be tracking what platforms it detected (native / emulation) but not exactly sure if it uses those for reporting errors
