### ISSUE TITLE
multi-stage builds seem to persist the USER across stages

### ISSUE THREAD

**Issue by yomimono** [moby/moby#33550] opened 2017-06-06 19:45 UTC
**Description**

When an early stage is an image which sets `USER`, this will be retained in later stages of the build.

**Steps to reproduce the issue:**
1. use the following `Dockerfile`:
```
# any image which sets USER will probably do; here's an arbitrary one
FROM ocaml/opam:alpine-3.5_ocaml-4.04.0 as ocaml

FROM scratch

COPY --from=ocaml /bin/sh /
CMD ["/sh"]
```
2. to `docker build`
3. and then try to `docker run`

**Describe the results you received:**

```
user@whale:~/minim$ cat Dockerfile 
FROM ocaml/opam:alpine-3.5_ocaml-4.04.0 as ocaml

FROM scratch

COPY --from=ocaml /bin/sh /
CMD ["/sh"]
user@whale:~/minim$ docker build -t minim .
Sending build context to Docker daemon  53.76kB
Step 1/4 : FROM ocaml/opam:alpine-3.5_ocaml-4.04.0 as ocaml
 ---> 71e233abdbbf
Step 2/4 : FROM scratch
 ---> 
Step 3/4 : COPY --from=ocaml /bin/sh /
 ---> Using cache
 ---> 9fe76f919a20
Step 4/4 : CMD /sh
 ---> Using cache
 ---> f01e19719430
Successfully built f01e19719430
Successfully tagged minim:latest
user@whale:~/minim$ docker run -it minim:latest
docker: Error response from daemon: linux spec user: unable to find user opam: no matching entries in passwd file.
```

**Describe the results you expected:**

Probably some other kind of problem, since I'm copying something into `FROM scratch` and trying to run it without any of the things it's likely to need for a working system (and also probably with the wrong arguments).  But not a user mismatch error from the Docker daemon.

**Additional information you deem important (e.g. issue happens only occasionally):**

Intermediate stages also seem to have unexpected behavior with `USER`.

**Output of `docker version`:**

```
user@whale:~/minim$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
user@whale:~/minim$ docker info
Containers: 58
 Running: 0
 Paused: 0
 Stopped: 58
Images: 235
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.4.55-11.pvops.qubes.x86_64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 571.8MiB
Name: whale
ID: KXMM:2JAQ:EZ6J:AILY:QUYJ:OQPR:OW2O:6YGK:AGZX:TJNB:GMOO:EDL5
Docker Root Dir: /home/user/var-lib-docker
Debug Mode (client): false
Debug Mode (server): false
Username: [redacted]
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Sent from my QubesOS machine (the VM in question is Debian 8)

**Comment by thaJeztah** [comment] 2017-06-06 20:18
ping @tonistiigi

**Comment by tonistiigi** [comment] 2017-06-06 20:22
This was fixed with https://github.com/moby/moby/pull/33179 Please test with `17.06-rc1` to confirm.

https://github.com/linuxkit/linuxkit/issues/1807#issuecomment-301154483 has some workarounds for `v17.05`.

**Closed by tonistiigi** 2017-06-06 20:22 UTC
Labels: area/builder, version/17.05

**Comment by bmitch3020** [comment] 2017-06-06 23:49
I can confirm that 17.06-rc1 works. Note to the OP, you'll also need to copy over /lib because the shell is not statically compiled in that image.

```
$ docker run -it --rm ocaml/opam:alpine-3.5_ocaml-4.04.0
~ $ ldd /bin/sh
        /lib/ld-musl-x86_64.so.1 (0x5561e9ac3000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x5561e9ac3000)
~ $ exit
```

Here's the Dockerfile I used:

```
FROM ocaml/opam:alpine-3.5_ocaml-4.04.0 as ocaml
FROM scratch
COPY --from=ocaml /bin/sh /
COPY --from=ocaml /lib /lib
CMD ["/sh"]
```

Built and tested:

```
$ docker build -t multi-scratch-user-test -f df.multi-scratch-user .         
Sending build context to Docker daemon  23.36MB
Step 1/5 : FROM ocaml/opam:alpine-3.5_ocaml-4.04.0 as ocaml
 ---> 71e233abdbbf
Step 2/5 : FROM scratch
 ---> 
Step 3/5 : COPY --from=ocaml /bin/sh /
 ---> Using cache
 ---> ee2389d8e10f
Step 4/5 : COPY --from=ocaml /lib /lib
 ---> 251d036f8fd7
Removing intermediate container 66256096fc57
Step 5/5 : CMD /sh
 ---> Running in dea61f22e310
 ---> 0dc7cbb1282d
Removing intermediate container dea61f22e310
Successfully built 0dc7cbb1282d
Successfully tagged multi-scratch-user-test:latest

$ docker run -it --rm multi-scratch-user-test                                
/ # echo "hello world"
hello world
/ # exit
```

Running on RC1:

```
$ docker version
Client:
 Version:      17.06.0-ce-rc1
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Thu May 25 07:38:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Thu May 25 07:37:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
