### ISSUE TITLE
docker build using -f to specify the Dockerfile location fails on Windows

### ISSUE THREAD

**Issue by deviantony** [moby/moby#33370] opened 2017-05-24 09:49 UTC
Hi there, I'm facing an issue when trying to build an image on my Windows server 2016 machine.

On Linux, I can type `docker build -t myimage -f build/linux/Dockerfile .` and the image is built without trouble.

![test2](https://cloud.githubusercontent.com/assets/5485061/26397200/c751d9f0-4075-11e7-95ba-918f04795353.png)

But on Windows, it seems that it cannot locate the Dockerfile:

![test1](https://cloud.githubusercontent.com/assets/5485061/26397212/d20beb42-4075-11e7-929e-f68830fc238e.png)

I've tried to search for existing issues about this without success.

Docker version on Windows 1.13 (I might retry later with latest version).

**Comment by thaJeztah** [comment] 2017-05-24 12:54
Can you provide more information about the exact version you're running, as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue?

- provide the output of `docker version`
- provide the output of `docker info`

**Comment by thaJeztah** [comment] 2017-05-24 12:55
Also /cc @jhowardmsft @johnstep @tonistiigi PTAL

**Comment by deviantony** [comment] 2017-05-24 12:59
Woops sorry about that.

![capture du 2017-05-24 14 59 13](https://cloud.githubusercontent.com/assets/5485061/26404275/993b472e-4091-11e7-9756-c2497caf9008.png)

**Comment by deviantony** [comment] 2017-05-24 19:08
So we figured out the problem, I had a `.dockerignore` in my directory with the following content:

```
*
!dist
```

Seems that adding `!build` inside the file fixes my issue on Windows. Anyone have a sane explanation to that? :)

Feel free to close the issue.

**Comment by friism** [comment] 2017-05-24 19:12
That's not supposed to be a problem:

> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY commands do not copy them to the image.

 - https://docs.docker.com/engine/reference/builder/#dockerignore-file

**Comment by thaJeztah** [comment] 2017-05-24 19:16
Hm, yes, that's odd, as you should be able to exclude the `Dockerfile`, but it would still send it

@duglin any thoughts?

**Comment by duglin** [comment] 2017-05-24 19:45
My guess is that the slashes might be messing up the Dockerfile filename comparision.  I'll try to take a look in a bit.

**Comment by johnstep** [comment] 2017-05-24 21:21
I reproduce the issue on 17.04, but it seems to be fixed in 17.05.

**Comment by thaJeztah** [comment] 2018-07-04 19:08
Looks to be resolved https://github.com/moby/moby/issues/33370#issuecomment-303855389, so let me go ahead and close

**Closed by thaJeztah** 2018-07-04 19:08 UTC
Labels: area/builder, kind/bug, platform/windows, version/1.13
