### ISSUE TITLE
Cannot login in secure Docker registry 

### ISSUE THREAD

**Issue by MaxCCC** [moby/moby#36206] opened 2018-02-05 14:55 UTC
**Description**

I've running a docker registry in Artifactory on https://server/artifactory.
When I bypass the reverse proxy I'm able to login on the registry using:
`$ docker login http://server:8081`

Now it's forbidden to bypass the reverse proxy. So I need to trust the cert inside my docker machine before I can login in my docker registry.

```
$ docker login https://server/artifactory
Error response from daemon: Get https://server/v2/: x509: certificate signed by unknown authority
```

Now I've created a folder certs:  `/var/lib/boot2docker/certs/` and copied my rootca.pem in it. Rebooted the machine:
Now I get the following error after a `docker login`:
`Error response from daemon: login attempt to https://server/v2/ failed with status: 404 Not Found
`
Same error happens when I try to import my ca.crt inside` /etc/docker/certs.d/hostname-registry/ca.crt`

Where do I have to import my root CA? Is this enough to accept the certs and to make authenticating possible?

**Steps to reproduce the issue:**
1. Create docker machine
2. Try to login (x509)
3. SCP root CA to /var/lib/boot2docker/certs
4. reboot

**Describe the results you received:**
After docker login:  `failed with status: 404 Not Found`

**Describe the results you expected:**
200 logged in.

**Additional information you deem important (e.g. issue happens only occasionally):**
happening in docker machine

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker@docker-mazda:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.86-boot2docker
Operating System: Boot2Docker 17.06.2-ce (TCL 7.2); HEAD : ff16afa - Wed Sep  6 00:17:25 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: docker-xxx
ID: 3ONM:U6BR:LEXA:MMIX:B2PQ:BFBO:MOSM:6MOP:IRTT:PYLQ:XVBX:JWQD
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 26
 System Time: 2018-02-05T14:54:26.04178883Z
 EventsListeners: 0
Http Proxy: http://xxx
Https Proxy: http://xxx
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Comment by cpuguy83** [comment] 2018-02-05 15:09
`https://server/v2/ failed with status: 404 Not Found`

This error is from your registry.
Maybe check the logs on that?

In any case, this looks like a configuration issue and not a bug, so closing.
Feel free to discuss, though. Thanks! 🙇

**Closed by cpuguy83** 2018-02-05 15:09 UTC
Labels: area/distribution, version/17.06
