### ISSUE TITLE
cpu load is too high 

### ISSUE THREAD

**Issue by xidianwlc** [moby/moby#21880] opened 2016-04-08 08:24 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
[web@BJ-M5-DOCKER-7-94 scripts]$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 13
 Running: 12
 Paused: 0
 Stopped: 1
Images: 50
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:2-4298188768-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.381 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104 GB
 Metadata Space Used: 5.714 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82 (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.7 GiB
Name: TEST-DOCKER
ID: L3OP:PULS:CPKH:OIKP:UXWL:DVKH:ZCW7:3AFY:NKK6:ZNML:Y6QA:QXA5
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 group=test
 env=online
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS Linux release 7.1.1503 (Core) 
mpstat -P ALL 5 10 

```
10:53:15 AM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
10:53:20 AM  all   21.33    0.00    4.39    0.00    0.01    1.82    0.00    0.00    0.00   72.45
10:53:20 AM    0   46.19    0.00    5.98    0.00    0.00    3.09    0.00    0.00    0.00   44.74
10:53:20 AM    1    6.45    0.00    2.42    0.00    0.00    0.20    0.00    0.00    0.00   90.93
10:53:20 AM    2   45.08    0.00    6.15    0.00    0.00    3.69    0.00    0.00    0.00   45.08
10:53:20 AM    3    3.64    0.00    1.21    0.00    0.00    0.00    0.00    0.00    0.00   95.15
10:53:20 AM    4   44.99    0.00    5.52    0.00    0.00    3.27    0.00    0.00    0.00   46.22
10:53:20 AM    5    5.86    0.00    2.02    0.00    0.00    0.00    0.00    0.00    0.00   92.12
10:53:20 AM    6   42.59    0.00    5.76    0.00    0.00    3.29    0.00    0.00    0.00   48.35
10:53:20 AM    7    3.03    0.00    0.81    0.00    0.00    0.00    0.00    0.00    0.00   96.16
10:53:20 AM    8   41.10    0.00   11.86    0.00    0.00    4.70    0.00    0.00    0.00   42.33
10:53:20 AM    9    3.43    0.00    3.03    0.00    0.00    0.40    0.00    0.00    0.00   93.13
10:53:20 AM   10   45.21    0.00    6.72    0.00    0.00    3.87    0.00    0.00    0.00   44.20
10:53:20 AM   11    4.45    0.00    1.82    0.00    0.00    0.00    0.00    0.00    0.00   93.72
10:53:20 AM   12   44.20    0.00    6.52    0.00    0.20    3.26    0.00    0.00    0.00   45.82
10:53:20 AM   13    8.50    0.00    3.85    0.00    0.00    0.00    0.00    0.00    0.00   87.65
10:53:20 AM   14   44.63    0.00    7.44    0.00    0.00    3.72    0.00    0.00    0.00   44.21
10:53:20 AM   15    7.66    0.00    5.24    0.00    0.00    0.81    0.00    0.00    0.00   86.29
10:53:20 AM   16   34.76    0.00    4.91    0.00    0.00    3.48    0.00    0.00    0.00   56.85
10:53:20 AM   17    1.21    0.00    0.61    0.00    0.00    0.00    0.00    0.00    0.00   98.18
10:53:20 AM   18   32.64    0.00    5.37    0.00    0.00    3.31    0.00    0.00    0.00   58.68
10:53:20 AM   19    5.25    0.00    5.25    0.00    0.00    0.61    0.00    0.00    0.00   88.89
10:53:20 AM   20   35.89    0.00    6.43    0.00    0.00    3.73    0.00    0.00    0.00   53.94
10:53:20 AM   21    0.80    0.00    1.00    0.00    0.00    0.00    0.00    0.00    0.00   98.20
10:53:20 AM   22   31.16    0.00    8.76    0.00    0.00    3.67    0.00    0.00    0.00   56.42
10:53:20 AM   23    0.20    0.00    0.20    0.00    0.00    0.00    0.00    0.00    0.00   99.60
10:53:20 AM   24   33.61    0.00    5.60    0.00    0.00    2.70    0.00    0.00    0.00   58.09
10:53:20 AM   25    2.82    0.00    2.42    0.00    0.00    0.20    0.00    0.00    0.00   94.56
10:53:20 AM   26   34.23    0.00    4.15    0.00    0.00    2.49    0.00    0.00    0.00   59.13
10:53:20 AM   27    6.52    0.00    7.33    0.00    0.00    1.02    0.00    0.00    0.00   85.13
10:53:20 AM   28   35.27    0.00    5.39    0.00    0.00    3.32    0.00    0.00    0.00   56.02
10:53:20 AM   29    2.01    0.00    1.61    0.00    0.00    0.20    0.00    0.00    0.00   96.18
10:53:20 AM   30   33.54    0.00    5.32    0.00    0.00    3.48    0.00    0.00    0.00   57.67
10:53:20 AM   31    0.80    0.00    0.60    0.00    0.00    0.00    0.00    0.00    0.00   98.59
```

from the result we can find that it only use the even CPU

**Steps to reproduce the issue:**
1. use docker-compose to manager at least 10 container, in container use supervisor to manager  20 python tornado process
2. exec docker-compose up -d  --force-recreate
3. use top to see the cpu load is very high
4. if requests the tornado process then the cpu load is also very high and only use even cpu

**Describe the results you received:**
docker-compose up -d --restart  can make cpu load very high
docker only use even cpu is very strange

**Describe the results you expected:**
docker-compose up make cpu load less than 5

**Comment by cpuguy83** [comment] 2016-04-08 13:47
What is consuming the CPU?

**Comment by xidianwlc** [comment] 2016-04-09 05:32
In the application of the huge amount of request, if the implementation of the restart operation will lead to increased server load

**Comment by phobologic** [comment] 2016-06-14 22:31
We are seeing this as well on our hosts across the board - we upgraded from docker 1.7 to docker 1.11.2 in our production environment and noticed that docker is consistently using 40% of the CPU now, whereas before it was much lower.


**Output of `docker version`:**

```
ubuntu@ip-10-128-20-210:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```


**Output of `docker info`:**

```
ubuntu@ip-10-128-20-210:~$ docker info
Containers: 142
 Running: 7
 Paused: 0
 Stopped: 135
Images: 19
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 602
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-87-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
Name: ip-10-128-20-210
ID: 7XYB:JYC6:MVBM:NKXR:NZIJ:GW52:VQF5:W3WT:QX35:XAQU:C436:2OTE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is running on `c4.2xlarge` instances in `us-east-1` in AWS, using ECS.  We run `Ubuntu 14.04LTS`.

**Steps to reproduce the issue:**
Run instances in docker 1.11.2 

**Describe the results you received:**
Average CPU usage, when containers are running, is very high.  At around 35-40% average across our instances.

**Describe the results you expected:**
The docker CPU usage used to be much lower, in the 2-5% range.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is from our 1.7 AMI (we sitll have a few hosts running it):

https://www.dropbox.com/s/rmq4qmt43grhql5/Screenshot%202016-06-14%2015.24.34.png?dl=0

This is the average for our 1.11.2 AMI:

https://www.dropbox.com/s/497rgcb4gii76dk/Screenshot%202016-06-14%2015.25.42.png?dl=0

**Comment by cpuguy83** [comment] 2016-06-14 22:46
@phobologic can you let us know what API endpoints you are hitting? What do your container configs look like? What logging driver are you using?

If you could enable debug mode it would be great to collect some pprof info as well.

**Comment by phobologic** [comment] 2016-06-14 23:05
@cpuguy83 @ejholmes is working on getting some pprof information, so we should have it soon.  Thanks.

**Comment by ejholmes** [comment] 2016-06-15 01:16
As an update, I generated a [cpu](https://dl.dropboxusercontent.com/u/1906634/GitHub/cpu.pdf) and [memory](https://dl.dropboxusercontent.com/u/1906634/GitHub/memory.pdf) profile (with --alloc_space flag) on a Docker host running in production.

Looks like a majority of CPU is spent in GC. And looking at the memory profile, most of the garbage is generated from `ContainerTop` and also [github.com/vbatts/tar-split](https://github.com/vbatts/tar-split) (which I'm not sure what is using, `git grep` fails me).

**Comment by ejholmes** [comment] 2016-06-15 02:25
Turns out, this was caused by a broken Docker integration in an agent we were running on hosts. Stopping that agent dropped CPU back to normal levels.

I think we can close this.

**Comment by cpuguy83** [comment] 2016-06-15 02:26
👍 Thanks for the awesome report!

**Comment by vanloswang** [comment] 2016-09-18 09:59
Does anyone meet this situation, the CPU usage of the command 'docker load' is too high? almost 100% while the load task proccessing. The version of docker is 1.10.3

**Comment by michelvocks** [comment] 2016-09-18 11:55
@vanloswang 
`docker load` extracts all data/layers from a file and saves/converts it to the disk. I think this is the expected behaviour to use as much as possible resources to finish this job as fast as possible. 

Do you noticed any bad results from this (like crashing processes, a node restart or something else)?

**Comment by LK4D4** [comment] 2016-11-28 19:12
This is kinda old and contains THREE different reports. Original report about high load average  when running tornado(similar to #22032).
@xidianwlc I wonder if it's still an issue and we can get better script to reproduce problem.

**Comment by thaJeztah** [comment] 2023-09-16 14:46
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 14:46 UTC
Labels: area/performance, version/1.10, area/daemon
