### ISSUE TITLE
Failed XFS detection in v19.03.7

### ISSUE THREAD

**Issue by filip-havlicek** [moby/moby#40667] opened 2020-03-11 12:03 UTC
**Description**
It's not possible to start last Docker version (v19.03.7 at the moment) with XFS an disk quota enabled (overlay2.size).
It ends with this error message:
```
Mar 11 11:24:10 docker dockerd[11974]: failed to start daemon: error initializing graphdriver: Storage Option overlay2.size only supported for backingFS XFS. Found <unknown>
```
After downgrade to previous version, Docker successfully starts.

**Steps to reproduce the issue:**
This bug occured on our bare-metal servers.
I created Vagrantfile which you can easily re-use (or just copy&paste commands to some generic Debian Stretch installation):

```
$script = <<-SCRIPT
apt-get -qq update
apt-get -y install xfsprogs curl apt-transport-https
dd if=/dev/zero of=/docker.img bs=512MB count=4
device=$(losetup --show -f /docker.img)
mkfs.xfs "$device"
mkdir -p /data/docker
echo "$device /data/docker xfs pquota 0 2" >>/etc/fstab
mount -a
mkdir /etc/docker
cat <<EOF >/etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "data-root": "/data/docker",
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.size=500M"
  ],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "bridge": "none",
  "iptables": false,
  "ip-forward": false,
  "ip-masq": false
}
EOF
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
apt-get -qq update
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.hostname = "docker"
  config.vm.provision "shell", inline: $script
end
```
Connect to installed machine (`vagrant ssh`) and try to install `v19.03.7` of `docker-ce` package. Simultaneously check the logs in the second terminal (`journalctl -f`).
```
apt-get install docker-ce=5:19.03.7~3-0~debian-stretch docker-ce-cli=5:19.03.7~3-0~debian-stretch containerd.io
```
You can try to start it manually and check the logs.
```
systemctl start docker
```
Downgrade to previous version, which successfully starts.
```
apt-get install docker-ce=5:19.03.6~3-0~debian-stretch docker-ce-cli=5:19.03.6~3-0~debian-stretch
```

**Comment by thaJeztah** [comment] 2020-03-11 12:09
Thanks for reporting; this looks to be a duplicate of https://github.com/moby/moby/issues/40626, which was fixed on master in https://github.com/moby/moby/pull/40650, and is being back ported to the 19.03 branch through https://github.com/moby/moby/pull/40652 for an upcoming patch release of 19.03

Let me go ahead and close this one, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-03-11 12:09 UTC
Labels: area/storage/overlay, kind/bug, version/19.03

**Comment by filip-havlicek** [comment] 2020-03-11 12:12
@thaJeztah That's great, thank you.
