### ISSUE TITLE
Cannot connect to Docker container via SSH from host

### ISSUE THREAD

**Issue by tomcummings84** [moby/moby#33382] opened 2017-05-24 18:25 UTC
**Description**

**Steps to reproduce the issue:**
1. tried to ssh with host ip username:hostip
2. tried to ssh with set container ip username:containerip
3. tried to use -i ~/.ssh/mykey.pub at end of command
4. tried to use -p 2222 for my port set 

**Describe the results you received:**
Connection refused
Permission denied (publickey)

**Describe the results you expected:**
connect via SSH and coda 2 to docker container 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
lient:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
"HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "mynetdoc",
            "PortBindings": {
                "22/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "2222"
                    }
                ],
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ]
            },
"Config": {
            "Hostname": "06637364b12c",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "22/tcp": {},
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "Image": "dev_ubuntu0",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9a0a9a375d446ed3f674c567dd47bd142cf1317a769c68829bbb8accded284c9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "2222"
                    }
                ],
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/9a0a9a375d44",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "mynetdoc": {
                    "IPAMConfig": {
                        "IPv4Address": "172.18.0.22"
                    },
                    "Links": null,
                    "Aliases": [
                        "06637364b12c"
                    ],
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS : Ubuntu 16.04 main, then containers in this

**PLEASE LET ME KNOW IF YOU NEED ANY MORE INFO**

**Comment by tomcummings84** [comment] 2017-05-24 18:56
This was used to create the container ::: ubuntu@ip-(IP)~$ sudo docker run -it --net mynetdoc --ip 172.18.0.22 -p 8080:80 -p 4443:443 -p 2222:22 --name dev_ubuntu0 dev_ubuntu0

**Comment by anonymuse** [comment] 2017-05-24 20:26
Can you also please post the full SSH commands used with `-vvvv` if there's any extra output?

**Comment by tomcummings84** [comment] 2017-05-24 20:34
ssh -p 2222 ubuntu@172.18.0.22 -i ~/.ssh/toContainer.pub -vvvv
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "172.18.0.22" port 2222
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 172.18.0.22 [172.18.0.22] port 2222.
debug1: connect to address 172.18.0.22 port 2222: Connection refused
ssh: connect to host 172.18.0.22 port 2222: Connection refused


ssh root@172.18.0.22 -i ~/.ssh/toContainer.pub -vvvv
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "172.18.0.22" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 172.18.0.22 [172.18.0.22] port 22.
debug1: connect to address 172.18.0.22 port 22: Connection refused
ssh: connect to host 172.18.0.22 port 22: Connection refused

**Comment by sbko** [comment] 2017-05-25 18:29
1) you need to use private key to connect
2) is your public key in ~/.ssh/authorized_keys in container
3) why do you need to ssh? if you just need to have access to container's terminal you can do something like: `docker exec -it container_name /bin/bash` or /bin/sh

**Comment by tomcummings84** [comment] 2017-05-25 18:40
1. yes I have created the pairs for connecting
2. yes authorized keys file is in the container 
3. I need to connect to the container for DeployHQ and if possible for coda 2 to edit my files

**Comment by sbko** [comment] 2017-05-25 18:58
based on 

> tried to use -i ~/.ssh/mykey.pub at end of command
you're using public key instead of private key to ssh. you need to use private.

have you tried to use `docker exec` instead of ssh?

**Comment by tomcummings84** [comment] 2017-05-26 19:47
will this help....

Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 7
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1017-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 486.7 MiB
Name: ip-172-31-30-176
ID: N3M2:QM62:OVKL:Q2ZO:ASDD:477K:JHTY:LW6C:RPUM:X54R:34RH:NYFQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment] 2017-11-01 14:04
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-11-01 14:04 UTC
Labels: kind/question, platform/arm, version/17.03
