### ISSUE TITLE
docker: Error response from daemon: shim error: json: cannot unmarshal array into Go struct field processState.capabilities of type specs.LinuxCapabilities.

### ISSUE THREAD

**Issue by CarstenCarsten** [moby/moby#34200] opened 2017-07-20 11:12 UTC
**Description**

When I try to run a freshly created image, I get a strange error message.

**Steps to reproduce the issue:**
1. docker run --rm -it myimage:latest

**Describe the results you received:**
docker: Error response from daemon: shim error: json: cannot unmarshal array into Go struct field processState.capabilities of type specs.LinuxCapabilities.

**Describe the results you expected:**
The image should be started

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.29 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Sat Jul  8 20:56:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 69
 Running: 2
 Paused: 0
 Stopped: 67
Images: 183
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-254:1-11141689-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 38.37GB
 Data Space Total: 107.4GB
 Data Space Available: 31.83GB
 Metadata Space Used: 47.53MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.1GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.141 (2017-06-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: 
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4 (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.9-1-ARCH
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56GiB
Name: digital0190
ID: H6ZT:I3T2:G5TL:S6N5:E344:GCJV:KQCF:VQHP:PZP6:ND7G:KCY4:VXCZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

```

it runs on my physical machine

**Comment by thaJeztah** [comment] 2017-07-20 11:24
duplicate of https://github.com/docker/for-linux/issues/61

There are no official packages for Arch Linux; the version of Docker you're running on Arch linux is not maintained here.

The problem here is that the Arch package ships the wrong version of RunC, which is incompatible with Docker 17.06; see the output of `docker info` (Possibly other changes on configuration that may affect docker);

```
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4 (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
```

I recommend opening an issue with the Arch linux packagers

I'm closing this issue because there's nothing that can be done here, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-20 11:24 UTC
Labels: version/17.05

**Comment by seblu** [comment] 2017-07-23 21:33
The correct version of runc is not the one specified here: https://github.com/docker/docker-ce/blob/v17.06.0-ce/components/engine/hack/dockerfile/binaries-commits ?

**Comment by thaJeztah** [comment] 2017-07-23 23:17
@seblu Sorry, I see i didn't mention that but that's for docker 17.06; the daemon in the docker info reported here is 17.05, but using the RunC version for docker 17.06

**Comment by seblu** [comment] 2017-07-23 23:46
So, there is no issue with the runc version in the package?

The user issue was probably because he didn't restart the docker.service. That should be done manually on Arch.

**Comment by mimoralea** [comment] 2017-07-24 03:39
I had the same issue. A `sudo systemctl daemon-reload && sudo systemctl restart docker` fixed it.
