### ISSUE TITLE
-v How to follow new file when logrotate happend 

### ISSUE THREAD

**Issue by lovemyliwu** [moby/moby#34605] opened 2017-08-23 02:39 UTC
**Description**

create container with `-v /tmp/test.txt:/tmp/test_in_container.txt`, then we can `tail -F /tmp/test_in_container.txt` in container to get new line message. But after host logrotate `/tmp/test.txt`, in container we can not follow the new file `/tmp/test.txt`

**Steps to reproduce the issue:**
1. touch /tmp/test.txt
2. docker run --rm -v /tmp/test.txt:/tmp/test_in_container.txt ubuntu tail -F /tmp/test_in_container.txt
3. echo "hi1" >> /tmp/test.txt 
4. mv /tmp/test.txt /tmp/test.txt.1
5. touch /tmp/test.txt
6. echo "hi2" >> /tmp/test.txt

**Describe the results you received:**

container only get hi1 message

**Describe the results you expected:**

container also get hi2 message

**Comment by fntlnz** [comment] 2017-08-23 10:26
That's because you're mounting the file descriptor, not the path.
In fact if you try to write to `/tmp/test.txt.1` you can verify that.

From the documentation of [Shard Subtrees](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) in the kernel:



> 7) FAQ
	Q1. Why is bind mount needed? How is it different from symbolic links?
		symbolic links can get stale if the destination mount gets
		unmounted or moved. Bind mounts continue to exist even if the
		other mount is unmounted or moved.

**Comment by fntlnz** [comment] 2017-08-23 21:56
Closing this since it's the expected behavior

**Comment by fntlnz** [comment] 2017-08-23 21:56
Feel free to reopen if you have any questions

**Closed by fntlnz** 2017-08-23 21:56 UTC

**Comment by lovemyliwu** [comment] 2017-08-24 02:56
@fntlnz do you know how to mounting the path?

**Comment by fntlnz** [comment] 2017-08-28 17:07
You can't do that.
The neat thing to do in this case would be to write your logs to stdout and let a docker's logging driver do the rest. https://docs.docker.com/engine/admin/logging/overview/

If you can't do that the only solution that comes in mind is to don't move the file is to avoid moving the file but just its content.

For example `man 8 logrotate` can do that by using the `copytruncate` option

```
       copytruncate
              Truncate  the  original log file to zero size in place after creating a copy, instead of moving the old log file and optionally creating a new one.  It can be used when some program cannot be told to close its logfile and thus might
              continue writing (appending) to the previous log file forever.  Note that there is a very small time slice between copying the file and truncating it, so some logging data might be lost.  When this option is used, the create  option
              will have no effect, as the old log file stays in place.
```

**Comment by fntlnz** [comment] 2017-08-28 18:32
You can't do that.
The neat thing to do in this case would be to write your logs to stdout and let a docker's logging driver do the rest. https://docs.docker.com/engine/admin/logging/overview/

If you can't do that the only solution that comes in mind is to don't move the file is to avoid moving the file but just its content.

For example `man 8 logrotate` can do that by using the `copytruncate` option

```
       copytruncate
              Truncate  the  original log file to zero size in place after creating a copy, instead of moving the old log file and optionally creating a new one.  It can be used when some program cannot be told to close its logfile and thus might
              continue writing (appending) to the previous log file forever.  Note that there is a very small time slice between copying the file and truncating it, so some logging data might be lost.  When this option is used, the create  option
              will have no effect, as the old log file stays in place.
```

**Comment by lovemyliwu** [comment] 2017-08-29 02:16
@fntlnz OK, I see, thank you very much!
