### ISSUE TITLE
Provide dry-run option for docker system prune command

### ISSUE THREAD

**Issue by cs-shadow** [moby/moby#35901] opened 2017-12-29 17:19 UTC
`docker sytem prune` can be quite useful to get rid of stale images and containers but it is not easy to see exactly what it is going to delete. It is possible that there is a needle in the haystack the user wants to keep around. So, it might be useful to provide a `--dry-run` option that would do nothing except to print what the list of containers/images/volumes would have been deleted if the dry-run option was not provided.

If we go ahead with this option, it would also make sense to add the same option to other similar commands like `docker container prune`, `docker image prune` etc.

What do others think? I'd be happy to attempt a patch for this but would first like to get some feedback from others about the idea itself.

**Comment by thaJeztah** [comment] 2017-12-29 20:52
Looks like this is a duplicate of https://github.com/moby/moby/issues/30623, so let me close this one

**Closed by thaJeztah** 2017-12-29 20:52 UTC
