### ISSUE TITLE
Improvement for docker subcommand's help messages

### ISSUE THREAD

**Issue by wenchma** [moby/moby#18385] opened 2015-12-03 06:32 UTC
Description of problem:

I take `docker ps --help` subcommand for an example:

```
$ docker ps --help

Usage:  docker ps [OPTIONS]

List containers

  -a, --all=false       Show all containers (default shows just running)
  --before=             Show only container created before Id or Name
  -f, --filter=[]          Filter output based on conditions provided
  --format=             Pretty-print containers using a Go template
      ...
```

the available conditions of `--filter` should be printed for user guide, in fact, new user maybe not know.
I think the above should be printed as follows:

```
-f, --filter=[]          Filter output based on conditions provided
                         exited=<int> - containers with exit code of <int>
                         label=<key> or label=<key>=<value>
                         status=(created|restarting|running|paused|exited)
                         name=<string> - container's name
                         id=<ID> - container's ID
...
```

There are also other subcommands:

```
$ docker run --help

Usage:      docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
...
--name=                         Assign a name to the container
--net=default                   Set the Network for the container
--oom-kill-disable=false        Disable OOM Killer
...
```

docker create --help  on --net option.

`docker version`

```
    Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`

```
    Containers: 21
Images: 82
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 15.67 GiB
Name: docker
ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
WARNING: No swap limit support
```

`uname -a`

```
Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

**Comment by thaJeztah** [comment] 2023-08-15 14:05
Let me close this one as duplicate of https://github.com/moby/moby/issues/18797, which has more discussion.

**Closed by thaJeztah** 2023-08-15 14:05 UTC
Labels: area/cli, kind/enhancement, version/1.9, area/ux
