### ISSUE TITLE
aufs default storage backend limits CPU usage to 3%

### ISSUE THREAD

**Issue by ghost** [moby/moby#20885] opened 2016-03-02 23:17 UTC
The default storage backend of aufs on Ubuntu Xenial with current Docker Master static binary _greatly_ limits IO performance (e.g. when compiling a buildroot based project, which involves lots of autoconf and ccache) to the extent that on my 80 hardware thread ppc64le box, it limits CPU usage to around 3-5% of the machine, spending 42% of time in aufs_read_lock (according to perf). When using overlay, I can easily get above 25% CPU usage with the same workload, peaking to 90+%.

$ ~/docker-1.11.0-dev version
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.4.2 gccgo (GCC) 5.3.0
 Git commit:   64a4605
 Built:        Sat Feb 13 03:54:16 2016
 OS/Arch:      linux/ppc64le

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.4.2 gccgo (GCC) 5.3.0
 Git commit:   64a4605
 Built:        Sat Feb 13 03:54:16 2016
 OS/Arch:      linux/ppc64le

$ ~/docker-1.11.0-dev info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.11.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null bridge host
Kernel Version: 4.4.0-8-generic
Operating System: Ubuntu 16.04
OSType: linux
Architecture: ppc64le
CPUs: 80
Total Memory: 7.933 GiB
Name: stewart-xenial
ID: 7XCT:ZSZU:VS46:AUXB:A4AO:53OC:AUHN:QM7H:2PP3:GXHH:OAQ5:ZICJ
Debug mode (client): false
Debug mode (server): false
WARNING: No swap limit support

NOTE: above is with overlay, not the default aufs

**Comment by unclejack** [comment] 2016-03-04 19:04
This seems to be about scalability issues in the aufs code.

@sfjro Is this issue something you'd be interested in taking a look at?

**Comment by sfjro** [comment] 2016-03-05 00:19
unclejack:
> This seems to be about scalability issues in the aufs code.
>
> @sfjro Is this issue something you'd be interested in taking a look at?

Could you provide a reproducible sample workload?
While I don't have ppc64le machine, if I can reproduce and confirm the
problem on my test environment, I will be able to dive into the problem.
Note that I am not a Docker user, and a simple shell script is better
for me than a docker-file.


J. R. Okajima

**Comment by stewart-ibm** [comment] 2016-03-05 01:43
The exact use case I'm using is building firmware for OpenPower machines, which is here: https://github.com/open-power/op-build/tree/master-next (build dependencies and instructions are there for Ubuntu and Fedora).

The machine I've been running on is a 20 core (2x 10 core) box with 8 threads per core (so, 160 hardware threads) in a KVM guest with 8 GB total ram, 2GB per 5 core NUMA node (so a bit more demanding on IO than would be... the KVM host only has 256GB RAM and I'm being nice to other users by not using too much of it).

I'd expect similar problems to be exhibited on other larger systems.

See also: https://sthbrx.github.io/blog/2015/10/30/docker-just-stop-using-aufs/ which was a post by colleagues of mine who were also hitting this last year.

**Comment by sfjro** [comment] 2016-03-05 02:45
Stewart Smith:
> The exact use case I'm using is building firmware for OpenPower machines, which is here: https://github.com/open-power/op-build/tree/master-next (build dependencies and instructions are there for Ubuntu and Fedora).

Hmm, I need to know more details about "build" in both of your case and
your colleague's docker-just-stop-using-aufs case.
docker-just-stop-using-aufs mentioned about open(2) and
stat(2). Generally, when I think about aufs performance, open/stat are
issued by git(1), especially git-status and others.

As you might know, git compares the current file status and the cached
one under .git. Here "status" means struct stat members. Generally the
Unix file indentity is determined by st_{dev,ino} pairs, and git is
using them too.
While overlayfs provides the same indentity to the layer's, aufs
provides its own virtual identity. For instance,

When fileA is managed by git, git keeps the cached status in
proj.git/.git/index and the index contains fileA's identity.
- /layer/ro has 0x0801 for its st_dev
- /layer/ro/proj.git/fileA has 100 for its st_ino
- /layer/ro/proj.git/.git/index contains {0x0801,100} as fileA's
  identity
- mount /u as /layer/rw + /layer/ro, /u is either overlayfs or aufs
- we can see the contents of /u/proj.git/.git/index is equivalent to
  /layer/ro/proj.git/.git/index
then
- overlayfs provides {0x0801,100} for fileA's identity, which is
  equivalent to /layer/ro/proj.git/fileA.
- aufs provides {0x0802,110} for fileA's identity, which is different
  from /layer/ro/proj.git/fileA.

In this situation, if you run git-status, git-diff or something, the
behaviour of git differs a little.
- git issues stat(2) and gets st_{dev,ino} pair.
- git compares the gotten pair and the one in the index file.
- when they are different from each other, git opens the file, reads all
  data, compares it with the cached data, and finds there is nothing
  changed.
- if the gotten pair is equal to the one in the index file, then
  open/read/compare steps will be skipped.

this issue can happen when you copy the git working tree to somewhere
else. All files identity will be changed by the copy and the cached
identity in index file will be oboleted.
Once you complete git-status or something, the index file will be
updated, and open/read/compare steps will not happen anymore.
This behaviour of git can be controlled by git's configuration
core.checkstat.

Is this your case? Could you (or your colleague) identify which process
and which systemcall took so long time?
The simple way to confirm this git's behavaiour will be these.
- set git's core.checkstat
- run git on both of overlayfs and aufs, and count the number of
  open/stat.
- run git twice on aufs, and count the number of open/stat.
- etc...


J. R. Okajima

**Comment by sfjro** [comment] 2016-03-18 16:33
sfjro@users.sourceforge.net:
>
> Stewart Smith:
> > The exact use case I'm using is building firmware for OpenPower machines, which is here: https://github.com/open-power/op-build/tree/master-next (build dependencies and instructions are there for Ubuntu and Fedora).
>
> Hmm, I need to know more details about "build" in both of your case and
> your colleague's docker-just-stop-using-aufs case.
> docker-just-stop-using-aufs mentioned about open(2) and
> stat(2). Generally, when I think about aufs performance, open/stat are
> issued by git(1), especially git-status and others.

It seems that you are reporting a different isssue from your colleague's
docker-just-stop-using-aufs case.
- his case: cpu usage is high and spin_lock consumes CPU heavily.
- your case: cpu usage is low and aufs_read_lock takes long time.

For his case, it is unclear which spin_lock consumes CPU so heavily. And
I posted a question whether git is related or not.

For your case, the only thing which conflicts aufs_read_lock() is
aufs_write_lock() (it is a rw-semaphore). The use of aufs_write_lock()
is very limited. Only these cases.
- pseudo-link maintenance
- mount/unmount/remount
- bottom half of hidden inotify
- re-initialize whiteout
- truncating XINO

I don't know which is the cause of your case. But if it is true that
aufs_read_lock() takes very long time, then it means chaging your
configuration or mount options may improve the situation, I guess.

I have tried reproducing your problem, but could not confirm
successfully.

----------------------------------------
$ /usr/bin/time make -s -j8 --directory=/home/jro/tmp/op-build/buildroot O=/home/jro/tmp/op-build/output
	:::
	(long output)
	:::
WARNING: no hash file for linux-4.2.tar.xz
[7m>>> linux 4.2 Extracting[m
[7m>>> linux 4.2 Patching[m
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file drivers/usb/host/xhci.c.rej
Patch failed!  Please fix linux-0002-Revert-usb-xhci-stop-everything-on-the-first-call-to.patch!
package/pkg-generic.mk:120: recipe for target '/home/jro/tmp/op-build/output/build/linux-4.2/.stamp_patched' failed
make: *** [/home/jro/tmp/op-build/output/build/linux-4.2/.stamp_patched] Error 1
Command exited with non-zero status 2
2445.62user 133.64system 13:37.51elapsed 315%CPU (0avgtext+0avgdata 555972maxresident)k
8inputs+10631808outputs (0major+148061341minor)pagefaults 0swaps
$
----------------------------------------

On my test system, make failed due to an incorrect patch. It doesn't
matter here for now. /usr/bin/time reporeted the CPU usage is 315% which
is not bad. This system has 8 logical cores and make(1) partially
stopped its parallel behaviour. I don't think over 300% is bad.

Anyway, for your case, it is important and will be a first step to
identify the process and the systemcall which makes aufs_read_lock
taking long time.


J. R. Okajima

**Comment by daxtens** [comment] 2016-03-30 02:42
As requested on the blog, here's what you need to reproduce my setup:

Dockerfile:
```
# build and test php

FROM ubuntu:15.04

ENV DEBIAN_FRONTEND noninteractive
ENV http_proxy	    http://proxy:3128/
ENV https_proxy	    http://proxy:3128/

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y wget build-essential lsof unzip devscripts\
    	    apache2-dev \
	    dh-apache2 \
	    dh-systemd  \
	    libsystemd-daemon-dev  \
	    autoconf  \
	    automake  \
	    bison \
	    chrpath \
	    debhelper  \
	    dpkg-dev  \
	    flex \
	    freetds-dev \
	    libapr1-dev  \
	    libbz2-dev \
	    libcurl4-openssl-dev  \
	    libdb-dev \
	    libedit-dev  \
	    libenchant-dev \
	    libevent-dev  \
	    libexpat1-dev  \
	    libfreetype6-dev \
	    libgcrypt11-dev \
	    libgd-dev \
	    libglib2.0-dev \
	    libgmp3-dev \
	    libicu-dev \
	    libjpeg-dev  \
	    libkrb5-dev \
	    libldap2-dev \
	    libmagic-dev \
	    libmhash-dev  \
	    libmysqlclient-dev  \
	    libpam0g-dev \
	    libpcre3-dev  \
	    libpng-dev  \
	    libpq-dev \
	    libpspell-dev \
	    librecode-dev \
	    libsasl2-dev \
	    libsnmp-dev \
	    libsqlite3-dev \
	    libssl-dev \
	    libtidy-dev \
	    libtool  \
	    libwrap0-dev \
	    libxmltok1-dev \
	    libxml2-dev \
	    libvpx-dev \
	    libxslt1-dev  \
	    systemtap-sdt-dev  \
	    language-pack-de  \
	    mysql-server  \
	    netbase \
	    netcat-openbsd  \
	    re2c \
	    unixodbc-dev \
	    zlib1g-dev \
	    tzdata \
	    libapparmor-dev

RUN mkdir /inputs
#php7 debian dir
COPY debian		/inputs/debian

COPY docker_run.sh	/inputs/docker_run.sh
COPY build_debs.sh	/inputs/build_debs.sh
COPY build_php5.sh	/inputs/build_php5.sh
COPY build_php7.sh	/inputs/build_php7.sh
COPY perf		/inputs/perf

RUN mkdir /tmp/build
WORKDIR /tmp/build
CMD /inputs/docker_run.sh
```

You don't need to actually run the tests; the problem shows up during the compilation stage. Here is the file you need for that.

build_php5.sh
```
#!/bin/bash
set -euo pipefail

# first, we need old bison. 
cd /tmp && wget http://mirror.aarnet.edu.au/pub/gnu/bison/bison-2.7.1.tar.gz && tar -xf bison-2.7.1.tar.gz && cd bison-2.7.1 && \
    wget -O build-aux/config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' && \
    wget -O build-aux/config.sub  'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' && \
    ./configure && make -j${CPUS} && make install


cd /tmp/build
wget https://github.com/php/php-src/archive/PHP-5.6.zip
unzip PHP-5.6.zip
cd php-src-PHP-5.6
./buildconf --force

# try to match debian's build of cli

export CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -fsigned-char -fno-strict-aliasing"

# I've changed openssl path, pcre path and removed db4 so it builds.
COMMON_CONFIG=" --sysconfdir=/etc \
                --localstatedir=/var \
                --mandir=/usr/share/man \
                --disable-debug \
                --with-regex=php \
                --disable-rpath \
                --disable-static \
                --with-pic \
                --with-layout=GNU \
                --with-pear=/usr/share/php \
                --enable-calendar \
                --enable-sysvsem \
                --enable-sysvshm \
                --enable-sysvmsg \
                --enable-bcmath \
                --with-bz2 \
                --enable-ctype \
                --without-gdbm \
                --with-iconv \
                --enable-exif \
                --enable-ftp \
                --with-gettext \
                --enable-mbstring \
                --with-pcre-regex \
                --enable-shmop \
                --enable-sockets \
                --enable-wddx \
                --with-libxml-dir=/usr \
                --with-zlib \
                --with-kerberos=/usr \
                --with-openssl \
                --enable-soap \
                --enable-zip \
                --with-mhash=yes \
                --with-system-tzdata \
                --with-mysql-sock=/var/run/mysqld/mysqld.sock \
"

./configure 	--prefix=/usr --disable-cgi \
		--with-config-file-path=/etc/php5/cli \
		--with-config-file-scan-dir=/etc/php5/cli/conf.d \
		${COMMON_CONFIG} \
		--without-mm \
		--disable-pdo \
		--without-mysql --without-sybase-ct \
		--without-mssql --without-sqlite3 --enable-pcntl \
		--with-libedit=shared &&
make -j${CPUS} &&
make install

```

Just delete the other COPY lines and make build_php5.sh the CMD.
You'll need to run with docker run --env CPUS=something. 
I have been running on ppc64le, so I was using CPUS=40 or CPUS=160 depending on whether I was running on a VM or a full machine.

**Comment by sfjro** [comment] 2016-04-01 06:28
Daniel Axtens:
> You don't need to actually run the tests; the problem shows up during the compilation stage. Here is the file you need for that.
>
> build_php5.sh
	:::

Thanx for the dockerfile and the script.
The important part in the script is the parellel make, the number of
jobs (-jN). right?
I've tried reproducing by building linux kernel with 8, 80 and 800
jobs.

o test env
- kernel version: v4.5 with aufs4.5 module
- aufs mount option: noatime,noxino,udba=none,noplink,dirperm1
  Note: by these options, aufs drops several features and its behaviour
  towards to overlayfs's. Of course their behaviours are not 100%
  equivalent.
- no virtual machine nor docker.
- the upper wrirable layer is ext2 on disk.
- using the same layers, run "make -s -jN clean" and "make -s -jN" under
  the vanilla linux kernel source tree.

o time make -s clean
-j8
overlayfs:	1.68user 30.64system 0:09.58elapsed 337%CPU
aufs:		1.70user 35.67system 0:11.61elapsed 321%CPU
-j80
overlayfs:	1.66user 32.86system 0:09.88elapsed 349%CPU
aufs:		1.82user 35.96system 0:11.56elapsed 326%CPU
-j800
overlayfs:	1.76user 32.68system 0:09.90elapsed 347%CPU
aufs:		1.81user 35.77system 0:11.45elapsed 328%CPU

o time make -s
-j8
overlayfs:	104.39user 136.23system 0:49.60elapsed 485%CPU
aufs:		103.72user 183.83system 0:56.19elapsed 511%CPU
-j80
overlayfs:	111.60user 136.46system 0:49.54elapsed 500%CPU
aufs:		110.95user 183.83system 0:56.04elapsed 526%CPU
-j800
overlayfs:	112.01user 137.85system 0:49.79elapsed 501%CPU
aufs:		113.16user 186.32system 0:57.44elapsed 521%CPU

About the aufs performance comparing overlayfs's, I already know that
aufs consumes more CPU time in kernel space, and I am working on it.

My point is
- aufs doesn't limit CPU usage to around 3-5% (Stewart's case)
- aufs doesn't spent over 70% of kenel CPU time in open and stat
  (Daniel's case)

So for these two cases, I am afraid there might be something incorrect
around the configuration or mount options.

Here is my current considertation about your cases.
Stewart's case:
	aufs limits CPU usage to around 3-5% of the machine, spending
	42% of time in aufs_read_lock.
This may be a common issue about read-write semaphore. It is known that
CPU usage is heavily damaged on the many core systems.
And I am trying another lock algorithm instead of rw_semaphore.

Daniel's case:
	Why are open and stat slow?
Currently I can only guess GIT's behaviour as I wrote previously. Does
cc1 really issue open and stat so much? Hmm, this symptom is a mystery
for me now.

For the aufs performance, I have these plans other than rw_semaphore
(aufs_read_lock).
- reduce the number of the internal stat within the internal iterate_dir
  (when the fstype of the layer is some specific ones only)
- memory free using RCU
- lookup in RCU-walk mode
- with new mount option, replace iunique() by get_next_ino()


J. R. Okajima

**Comment by daxtens** [comment] 2016-04-04 05:11
Hi,

I don't know that those are the same mount options that Docker uses - I'll see if I can check. 

In my case I use a virtual machine with 40 hardware threads, so that may have more to do with the issue than the flags to make -j.

I can provide you with the output from `perf record` if that would be helpful?

**Comment by sfjro** [comment] 2016-04-05 01:24
Hi,

Daniel Axtens:
> I don't know that those are the same mount options that Docker uses - I'll see if I can check. 

You can specify aufs mount options by "mount -o remount,brabra..."
anytime.


> I can provide you with the output from `perf record` if that would be helpful?

I am afraid it would not be so helpful. Additional files as vmlinux,
modules, or /proc/kallsyms might be also necessary to get the correct
symbols. Moreover I believe you know how to use perf and it is
correct.


J. R. Okajima

**Comment by thaJeztah** [comment] 2023-04-21 00:00
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS

**Closed by thaJeztah** 2023-04-21 00:00 UTC
Labels: area/storage/aufs, area/kernel, version/master
