### ISSUE TITLE
Container cannot mount a path containing blank characters

### ISSUE THREAD

**Issue by pditommaso** [moby/moby#17967] opened 2015-11-13 15:13 UTC
When trying to mount a path containing a blank character Docker returns a 255 exit status. 

To replicate the issue: 

```
mkdir 'hello world'
cd 'hello world'
docker run  -v "$PWD":"$PWD" busybox env
```

System and Docker versions 

```
$ uname -a
Linux box683 3.14.28-031428-generic #201501081937 SMP Thu Jan 8 19:39:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux 


$ docker version
Client:
 Version:      1.9.0-circleci
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4f5fc17
 Built:        Wed Nov  4 16:20:58 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-circleci
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4f5fc17
 Built:        Wed Nov  4 16:20:58 UTC 2015
 OS/Arch:      linux/amd64


$ docker info
Containers: 47
Images: 42
Server Version: 1.9.0-circleci
Storage Driver: btrfs
Execution Driver: lxc-1.0.7
Logging Driver: json-file
Kernel Version: 3.14.28-031428-generic
Operating System: Ubuntu precise (12.04.5 LTS) (containerized)
CPUs: 2
Total Memory: 240.2 GiB
Name: box683
ID: P52W:JTUZ:K2GY:NH5L:CV6W:BAM3:7SDK:POOS:ES2N:DW3R:TX4B:SSPO
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 40
 System Time: 2015-11-13T15:12:39.584080565Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by clnperez** [comment] 2015-11-13 18:57
Have you tried this on different environments/shells? It works for me on Fedora 22 using bash.

**Comment by crosbymichael** [comment] 2015-11-13 18:57
from testing, this is an lxc bug, this works fine with the native exec driver.

**Comment by thaJeztah** [comment] 2015-11-26 12:55
not able to reproduce with the native driver; also note that the lxc driver has been deprecated and will be removed in 1.10. Are you able to test if this reproducible with the native driver, a particular reason for using lxc?

**Comment by pditommaso** [comment] 2015-11-26 12:59
Actually this happened to me when running Docker in the [CircleCI](http://circleci.com) environment. I will ask on their community

**Comment by thaJeztah** [comment] 2015-11-26 13:07
Ah, yes, they're using lxc currently

**Comment by thaJeztah** [comment] 2023-08-07 14:05
Let me close this one as we removed LXC long time ago.

**Closed by thaJeztah** 2023-08-07 14:05 UTC
Labels: version/unsupported
