### ISSUE TITLE
Error response from daemon: cannot join secure network: encryption keys not present.

### ISSUE THREAD

**Issue by evorta** [moby/moby#35942] opened 2018-01-06 00:10 UTC
**Description**

I have a 3 node docker standalone swarm setup. They have ETCD as the K,V store. It all works fine unencrypted.

I can create a encrypted network on the swarm, via command:

```
docker swarm network create --opt encrypted --driver overlay encrypted-network
```

3. When i try to run something on the swarm with that network:
```
docker run -d --name test --network=encrypted-network 192.168.99.101:5000/hello-world:latest
```
it throws an error:

> docker: Error response from daemon: Error response from daemon: cannot join secure network: encryption keys not present.

**Steps to reproduce the issue:**
1.Create a docker standalone network using ETCD as the store.
2.Create a overlay without encyption, ensure it all works together via just pinging between some hello-worlds.
3.then create encypted overlay and try again, you'll find yourself at my spot.

**Describe the results you received:**
Simple output but poking around in code, I can't see it other than it can't find keys, I can't see the keys anywhere in the ETCD output for the json that is shared between all swarm nodes.

**Describe the results you expected:**
It should just communicate, I get it may not work due to other issues as suggested by issue: 
https://github.com/moby/moby/issues/30766 but the last guy that posted has the same issue as me but it's not the same issue as the rest of that post. I can't even get to the point where it runs and I can then test encrypted packets are moving around.

**Additional information you deem important (e.g. issue happens only occasionally):**
It never works correctly, it always bombs out during run with the keys issue.

**Output of `docker info`: ON SWARM MODE PORT 3376 ** 

```
Client:
 Version:      17.09.1-ce
 API version:  1.24 (downgraded from 1.32)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.8
 API version:  1.22 (minimum version )
 Go version:   go1.7.1
 Git commit:   48d86b1
 Built:        2017-07-11T17:45:23+0000
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker version`: ON DOCKERD 2376 ** 

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`: ON SWARM MODE PORT 3376 ** 

```
Containers: 37
 Running: 36
 Paused: 0
 Stopped: 1
Images: 34
Server Version: swarm/1.2.8
Role: replica
Primary: 192.168.99.100:3376
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 3
 chicago: 192.168.99.102:2376
  └ ID: OBGR:INWJ:2NAO:DLAX:WQVQ:XDKA:SYKE:SKA4:3NJF:M3DC:X4GW:CTES|192.168.99.102:2376
  └ Status: Healthy
  └ Containers: 12 (12 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 512.7 MiB
  └ Labels: kernelversion=4.4.0-103-generic, operatingsystem=Ubuntu 16.04.3 LTS, ostype=linux, storagedriver=overlay2
  └ UpdatedAt: 2018-01-05T11:24:02Z
  └ ServerVersion: 17.11.0-ce
 melbourne: 192.168.99.100:2376
  └ ID: OBGR:INWJ:2NAO:DLAX:WQVQ:XDKA:SYKE:SKA4:3NJF:M3DC:X4GW:CTES|192.168.99.100:2376
  └ Status: Healthy
  └ Containers: 13 (12 Running, 0 Paused, 1 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 512.7 MiB
  └ Labels: kernelversion=4.4.0-103-generic, operatingsystem=Ubuntu 16.04.3 LTS, ostype=linux, storagedriver=overlay2
  └ UpdatedAt: 2018-01-05T11:24:07Z
  └ ServerVersion: 17.11.0-ce
 sydney: 192.168.99.101:2376
  └ ID: OBGR:INWJ:2NAO:DLAX:WQVQ:XDKA:SYKE:SKA4:3NJF:M3DC:X4GW:CTES|192.168.99.101:2376
  └ Status: Healthy
  └ Containers: 12 (12 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 512.7 MiB
  └ Labels: kernelversion=4.4.0-103-generic, operatingsystem=Ubuntu 16.04.3 LTS, ostype=linux, storagedriver=overlay2
  └ UpdatedAt: 2018-01-05T11:23:53Z
  └ ServerVersion: 17.11.0-ce
Plugins:
 Volume: 
 Network: 
 Log: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Kernel Version: 4.4.0-103-generic
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 1.502GiB
Name: e8d4e1bb0acf
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
Experimental: false
Live Restore Enabled: false
```

**Output of `docker info`: ON DOCKERD MODE PORT 2376 ** 

```
Containers: 13
 Running: 12
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.3MiB
Name: melbourne
ID: OBGR:INWJ:2NAO:DLAX:WQVQ:XDKA:SYKE:SKA4:3NJF:M3DC:X4GW:CTES
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 135
 Goroutines: 167
 System Time: 2018-01-05T22:24:56.322372403+11:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Experimental: false
Cluster Store: etcd://192.168.99.100:2379
Cluster Advertise: 192.168.99.100:2376
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of ETCD store ** 

```
                                 {
                                    "key":"/docker/network/v1.0/network/996e5613aaaf5854dd910ec4ec084587857b141e0a7bc018cb56c1965e9cb0b2",
                                    "value":"{\"addrSpace\":\"GlobalDefault\",\"attachable\":false,\"configFrom\":\"\",\"configOnly\":false,\"created\":\"2018-01-05T21:36:01.472902605+11:00\",\"enableIPv6\":false,\"generic\":{\"com.docker.network.enable_ipv6\":false,\"com.docker.network.generic\":{\"encrypted\":\"true\"}},\"id\":\"996e5613aaaf5854dd910ec4ec084587857b141e0a7bc018cb56c1965e9cb0b2\",\"inDelete\":false,\"ingress\":false,\"internal\":false,\"ipamOptions\":null,\"ipamType\":\"default\",\"ipamV4Config\":\"[{\\\"PreferredPool\\\":\\\"\\\",\\\"SubPool\\\":\\\"\\\",\\\"Gateway\\\":\\\"\\\",\\\"AuxAddresses\\\":null}]\",\"ipamV4Info\":\"[{\\\"IPAMData\\\":\\\"{\\\\\\\"AddressSpace\\\\\\\":\\\\\\\"GlobalDefault\\\\\\\",\\\\\\\"Gateway\\\\\\\":\\\\\\\"10.0.1.1/24\\\\\\\",\\\\\\\"Pool\\\\\\\":\\\\\\\"10.0.1.0/24\\\\\\\"}\\\",\\\"PoolID\\\":\\\"GlobalDefault/10.0.1.0/24\\\"}]\",\"labels\":{},\"name\":\"encypted-network\",\"networkType\":\"overlay\",\"persist\":true,\"postIPv6\":false,\"scope\":\"global\"}",
                                    "modifiedIndex":3789,
                                    "createdIndex":3789
                                 }
                              ],
                              "modifiedIndex":12,
                              "createdIndex":12
                           },
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual boxes running ubuntu 16.04. I recreate the whole stack from scratch, ETCD runs in docker too! it's fine as overlay networks cleanly show up in there.

**Comment by thaJeztah** [comment] 2018-01-06 01:22
Looks like you're running "classic" ("standalone") swarm, not "swarm mode" (the built-in orchestration feature).

Standalone swarm does not have key management, thus cannot manage encrypted networks; see the ["swarm" documentation](https://docs.docker.com/swarm/networking/#create-a-network);

> `--opt encrypted` is a feature only available in Docker Swarm mode. It’s not supported in Swarm standalone. Network encryption requires key management, which is outside the scope of Swarm.


For documentation on Swarm _mode_; look here in the documentation: https://docs.docker.com/engine/swarm/

If this is a new installation, I'd recommend using Swarm mode, instead of standalone Swarm. Swarm mode does not require an external k/v store, or running the 'swarm' image, and can simply be enabled using `docker swarm init`, after which nodes can be joined using `docker swarm join`

Closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-01-06 01:22 UTC
Labels: area/swarm, version/17.11

**Comment by evorta** [comment] 2018-01-06 03:40
Hi,

Thanks buddy, simple case of should have ready the docs a few more times, I'm busy converting it all to docker swarm mode...

Thanks for your help on this one :)
