### ISSUE TITLE
Login to AWS, Tag and Push a Docker Image to AWS using bash shell script that is started from a java class

### ISSUE THREAD

**Issue by Betzen** [moby/moby#34524] opened 2017-08-15 16:03 UTC
Hello I am trying to push a docker image via shell command programming to AWS EC2 Container Service. But I am having trouble doing that and I am getting the following error messages:

error getting credentials - err: exec: "docker-credential-osxkeychain": executable file not found in $PATH, out: ``
no basic auth credentials

This error message is returned from my java class. If I start the shell script form the terminal i am having no problems only if I start it form my java class. I created an config.js file an added osxkeychain to it because i thought this might save the problem. 

This is my Dockerfile:

```
FROM java:7
COPY . /Users/betzenben/Desktop/OGC/Projects/Getting_started/Docker/Directory
WORKDIR /Users/betzenben/Desktop/OGC/Projects/Getting_started/Docker/Directory
RUN javac Time_app.java
CMD ["java", "Time_app"]
Run : ~/Users/betzenben/Desktop/OGC/Projects/Getting_started/Docker/Directory/config.json 
```

And this my config.json file

```
{
    "apps": [
         {
         "credsStore": "osxkeychain"
         }
    ]
}
```
And just in case it is needed my shell script code and my java class that calls the shell script.

```
#!/bin/sh

echo “test1”
getLoginKey="/usr/local/bin/"
getLoginKey+="$(/usr/local/bin/aws ecr get-login --no-include-email --region us-west-2)"
echo “test2”
echo "${getLoginKey}" 

executeLoginKey="$(eval $getLoginKey)"
echo “test3”
sleep 2
echo "${executeLoginKey}" 


tagImage="$(/usr/local/bin/docker tag time_app:latest .....id......dkr.ecr.us-west-2.amazonaws.com/time_a:latest)"
pushImage="$(/usr/local/bin/docker push .....id.......dkr.ecr.us-west-2.amazonaws.com/time_a:latest)"
wait
echo “test4”
sleep 5
echo "${pushImage}" 
echo "Image Pushed" 
```
Java Code:

```
package awstest;

import java.io.*;

public class Main {

  public static void main(String[] args) throws InterruptedException, IOException {
	 
	Process p1 = Runtime.getRuntime().exec("chmod +x /Users/betzenben/Desktop/tag_push_image_AWS.sh");

	BufferedReader stdInput1 = new BufferedReader(new InputStreamReader(p1.getInputStream()));
    BufferedReader stdError1 = new BufferedReader(new InputStreamReader(p1.getErrorStream()));

    System.out.println("STDOUT:\n");
    String s1 = null;
    while ((s1 = stdInput1.readLine()) != null) {
      System.out.println(s1);
    }
    System.out.println("STDERR:\n");
    while ((s1 = stdError1.readLine()) != null) {
      System.out.println(s1);
    }

    Process p = Runtime.getRuntime().exec("/Users/betzenben/Desktop/tag_push_image_AWS.sh");

    BufferedReader stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
    BufferedReader stdError = new BufferedReader(new InputStreamReader(p.getErrorStream()));

    System.out.println("STDOUT:\n");
    String s = null;
    while ((s = stdInput.readLine()) != null) {
      System.out.println(s);
    }
    System.out.println("STDERR:\n");
    while ((s = stdError.readLine()) != null) {
      System.out.println(s);
    }
  }
}
```

**Comment by thaJeztah** [comment] 2017-08-15 19:39
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2017-08-15 19:39 UTC
Labels: area/builder, area/distribution
