### ISSUE TITLE
Problems with arch linux (pacman) with CentOS 7 as host. 

### ISSUE THREAD

**Issue by Pablohn26** [moby/moby#32188] opened 2017-03-28 22:53 UTC
When we have CentOS 7 as host and run arch linux with docker, pacman has internal problems that make the container unusable (error manipulating its filesystem). This is reproducible only with CentOS 7, I have tested with Fedora, Ubuntu and Debian and it does not happen. 

The first error that I get is

> error: could not remove database entry

but it seems related with another internal error. 

**Steps to reproduce the issue:**
1. sudo docker run -it base/archlinux bash 
2. (inside the container) pacman -Syy
3. (inside the container) pacman -S curl

**Describe the results you received:**

several error with package

```
[root@localhost ~]# sudo service docker start
Redirecting to /bin/systemctl start  docker.service
[root@localhost ~]# sudo docker run -it base/archlinux bash 
Unable to find image 'base/archlinux:latest' locally
latest: Pulling from base/archlinux
384413af9e0b: Pull complete 
89ac87e0893f: Pull complete 
81de40084381: Pull complete 
Digest: sha256:6b8a1dca0d72472a7e9a328484e70181a95edd131d25ef0405416f929a06401e
Status: Downloaded newer image for base/archlinux:latest
[root@da366adb8491 /]# pacman -Syy
:: Synchronizing package databases...
 core                                                                                                                 123.8 KiB   235K/s 00:01 [########################################################################################] 100%
 extra                                                                                                               1679.7 KiB  3.00M/s 00:01 [########################################################################################] 100%
 community                                                                                                              3.8 MiB  9.27M/s 00:00 [########################################################################################] 100%
[root@da366adb8491 /]# pacman -S curl
warning: curl-7.53.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) curl-7.53.1-1

Total Download Size:   0.84 MiB
Total Installed Size:  1.35 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 curl-7.53.1-1-x86_64                                                                                                 857.0 KiB   812K/s 00:01 [########################################################################################] 100%
(1/1) checking keys in keyring                                                                                                                 [########################################################################################] 100%
(1/1) checking package integrity                                                                                                               [########################################################################################] 100%
(1/1) loading package files                                                                                                                    [########################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [########################################################################################] 100%
(1/1) checking available disk space                                                                                                            [########################################################################################] 100%
:: Processing package changes...
error: could not remove database entry curl-7.53.1-1
error: could not create directory /var/lib/pacman/local/curl-7.53.1-1/: File exists
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.
[root@da366adb8491 /]# pacman -Syy
pacman: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
[root@da366adb8491 /]# 
```

**Describe the results you expected:**

package installed

```
0 pablo:1@~$ sudo service docker start
[sudo] password for pablo: 
Redirecting to /bin/systemctl start  docker.service
0 pablo:1@~$ docker run -it base/archlinux bash 
/usr/bin/docker-current: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See '/usr/bin/docker-current run --help'.
125 pablo:1@~$ sudo docker run -it base/archlinux bash 
125 pablo:1@~$ sudo docker run -it base/archlinux bash 
Unable to find image 'base/archlinux:latest' locally
Trying to pull repository docker.io/base/archlinux ... 
sha256:6b8a1dca0d72472a7e9a328484e70181a95edd131d25ef0405416f929a06401e: Pulling from docker.io/base/archlinux

384413af9e0b: Pull complete 
89ac87e0893f: Pull complete 
81de40084381: Pull complete 
Digest: sha256:6b8a1dca0d72472a7e9a328484e70181a95edd131d25ef0405416f929a06401e
Status: Downloaded newer image for docker.io/base/archlinux:latest
[root@789822b12808 /]# pacman -Syy
:: Synchronizing package databases...
 core                     123.8 KiB   236K/s 00:01 [######################] 100%
 extra                   1679.7 KiB  3.02M/s 00:01 [######################] 100%
 community                  3.8 MiB  5.39M/s 00:01 [######################] 100%
[root@789822b12808 /]# pacman -S curl
warning: curl-7.53.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) curl-7.53.1-1

Total Download Size:   0.84 MiB
Total Installed Size:  1.35 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 curl-7.53.1-1-x86_64     857.0 KiB   814K/s 00:01 [######################] 100%
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) reinstalling curl                            [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

It only happens with CentOS 7.

**Output of `docker version`:**
```
[root@localhost ~]# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
[root@localhost ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.6 MiB
Name: localhost.localdomain
ID: AKEQ:ISA6:PM72:DIK6:AC2P:J7Z2:SN3X:HY6W:5ABR:BMQM:ZOWM:EM7B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

tested on CentOS 7 with VirtualBox and KVM.

**Comment by ichernev** [comment] 2019-05-16 20:09
I can confirm this is happening.

CentOS 7 host, kernel stock and kernel-ml (5.1.2-1.el7.elrepo.x86_64) from elrepo both exhibit the problem.
docker-ce Docker version 18.09.6, build 481bc77156, and stock docker version 1.13.1 -- either way same problem.

Just fetch `archlinux/base:latest`, and try `pacman -Syu`. The filesystem is corrupted -- you can run `ls -R  /var/lib/pacman/local/` and it will crash with `No such file or directory`.

**Comment by kolyshkin** [comment] 2019-05-16 23:24
@ichernev I was not able to reproduce this on Ubuntu host. Same with CentOS 7 (kernel 3.10.0-957.5.1.el7.x86_64). Perhaps your host FS is corrupted in some way? Check host kernel messages, docker log...

> [root@kir-ce75-gd ~]# docker run -it archlinux/base:latest bash
> ....
> [root@23ee313cf453 /]# pacman -Syu
> ....
> :: Proceed with installation? [Y/n] Y
> ....
> (10/10) Rebuilding certificate stores...
> [root@23ee313cf453 /]# ls -l /var/lib/pacman/local/
> total 4
> drwxr-xr-x 2 root root 44 May  2 15:53 acl-2.2.53-1
> -rw-r--r-- 1 root root  2 May  2 15:53 ALPM_DB_VERSION
> drwxr-xr-x 2 root root 59 May  2 15:53 archlinux-keyring-20190123-2
> drwxr-xr-x 2 root root 59 May  2 15:53 argon2-20171227-3
> drwxr-xr-x 2 root root 44 May  2 15:53 attr-2.4.48-1
> ...

[root@kir-ce75-gd ~]# docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     true

**Comment by kolyshkin** [comment] 2019-05-16 23:25
> The filesystem is corrupted -- you can run ls -R /var/lib/pacman/local/ and it will crash with No such file or directory.

This is not a "crash", it's the absence of a directory. I suggest you to reproduce it while running pacman under strace (as in `strace -Fft -o out pacman -Syu`), and report your results to archlinux forums.

**Comment by thaJeztah** [comment] 2019-05-23 00:52
I see the original report uses overlay without `d_type`, which is known to cause problems;

```
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
```

Let me close this issue because the original report is really old now, and likely a result of that problem; if you have details on your case though and still suspect there's a bug, feel free to open a new issue with details and steps to reproduce

**Closed by thaJeztah** 2019-05-23 00:52 UTC
Labels: version/17.03
