### ISSUE TITLE
docker selinux enabled - relabeling content in /usr is not allowed

### ISSUE THREAD

**Issue by karthikus** [moby/moby#40092] opened 2019-10-15 06:10 UTC
**Description**

I have Docker on Centos7 with selinux set to enforcing on the host and Docker daemon is started with --selinux-enabled flag. When I try to write to /usr/* path from within the container, I get "relabeling content in /usr is not allowed" 

**Steps to reproduce the issue:**
1. Set selinux to enforcing on a CentOS 7 machine.
2. Enable selinux in docker (I set selinux-enabled: true in /etc/docker/daemon.json); Restart docker daemon.
3. Run the following command to write to /usr/* path from inside the container
```
docker run -it   -v /usr/local/xya/log:/usr/local/xya/log:z centos/systemd touch /usr/local/xya/log/test 
```
**Describe the results you received:**

docker: Error response from daemon: error setting label on mount source '/usr/local/xya/log': relabeling content in /usr is not allowed.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:58:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:56:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 4
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 3.10.0-862.3.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.51GiB
 Name: mdc-test-5.novalocal
 ID: U64V:TIBE:FIMD:P7XR:N4NU:SPKT:2GZH:P76M:5XH4:5YM5:F27Q:SFMT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by cpuguy83** [comment] 2019-10-15 17:04
It looks like relabling of that path is explicitly not allowed in go-selinux: https://github.com/opencontainers/selinux/blob/992bcc9e3a609d42e1a40d1b1bcfd52febe4d75a/go-selinux/label/label_selinux.go#L194

Honestly this labeling option is pretty terrible and is likely to be deprecated. I would recommend labeling it with the label you need using `chcon`

Closing since this appears to be by design, but feel free to discuss.
Thanks! 🙇 😇

**Closed by cpuguy83** 2019-10-15 17:04 UTC
