### ISSUE TITLE
Docker 1.11.1 fails to unmount/remove device mapper volumes and freezes

### ISSUE THREAD

**Issue by anosulchik** [moby/moby#24446] opened 2016-07-08 11:33 UTC
Please see this comment: https://github.com/docker/docker/issues/20401#issuecomment-231337800

I've opened new issue since #20401 is related to docker 1.9.1 while the problem described in commend is relevant to docker 1.11.1.

**Comment by cpuguy83** [comment] 2016-07-08 13:18
This is fixed on 1.11.2
Please update and test.

Closing for now, but please do comment if it's still a problem after 1.11.2.

**Comment by anosulchik** [comment] 2016-07-12 10:42
@cpuguy83 The problem still exists in 1.11.2. I've updated docker to suggested version and was able to reproduce the problem in the same was as at 1.11.1 -- after a few hours of starting and stopping containers docker hangs.

```
[root@es-staging2-node1 ~]# docker -v
Docker version 1.11.2, build b9f10c9

[root@es-staging2-node1 ~]# docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 1.418 GB
 Data Space Total: 23.35 GB
 Data Space Available: 21.94 GB
 Metadata Space Used: 1.442 MB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 23.72 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.10-22.54.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.679 GiB
Name: es-staging2-node1
ID: 3YNS:DHJF:LC3P:5JXS:AP54:OCDG:C7XR:ZO3B:UO5M:D7CE:XFHK:PNPZ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

While docker produces 99% iowait device mapper shows hundeds of unmounted volumes:

```
[root@es-staging2-node1 ~]# dmsetup ls | wc -l
166
```

```
[root@es-staging2-node1 ~]# dmsetup ls
docker-202:1-263208-aafa8e73a2084444b562eaae28d49180b24ab5150c80ae36191c1423b03ff752	(253:56)
docker-202:1-263208-551097fa7c89315c8775f78459144ed4173df5268bdbb79e60a6bca045a0b84b	(253:132)
docker-202:1-263208-38cf22a22363fc0da89c977b468298cf1e9f9c73e8de8f73cf7392455980c04b	(253:72)
docker-202:1-263208-1bca8ae068067939f702bdc2a2159983ae27b3681269df9159e55e5791357630	(253:97)
docker-202:1-263208-605525cdae72640cfad19b5ce5379261966b8d08bf241bdae4d55a9ce91de216	(253:44)
docker-202:1-263208-65f290a596bb4122b176075523db1385f846eaaa757a36e0eed0d5e4c924cc25-init	(253:34)
docker-202:1-263208-d25a8e6d5b77fb5b05e34c8c90ec31876da189f80a59f3766f4433932635dfe3-init	(253:129)
docker-202:1-263208-0072a084dafe5feb6573849d96732704b8b58d524d01e4eec54a54ca2c4e7c77-init	(253:99)
docker-202:1-263208-b282a46e26bb3e4fb1c4624ff93596c5bb20f7fb73e610b1d28f76ba06c257b0	(253:28)
...
...
...
```

**/var/log/docker**
```
2016/07/12 09:58:35 http: multiple response.WriteHeader calls
time="2016-07-12T09:58:35.730373559Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/07/12 09:58:35 http: multiple response.WriteHeader calls
time="2016-07-12T09:58:35.730955146Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/07/12 09:58:35 http: multiple response.WriteHeader calls
```

```
time="2016-07-12T06:14:16.564894152Z" level=error msg="Handler for POST /v1.17/containers/create returned error: open /var/lib/docker/containers/023c54fd71fd752d7571c8824cc4685858d76be15b41161ef04c84a80b179c5a/config.v2.json: no such file or directory"
time="2016-07-12T06:14:16.565008676Z" level=error msg="Handler for DELETE /v1.17/containers/ecs-es-staging2-37-internalecs-emptyvolume-source-fa8ec483c2f7d9a09901 returned error: Driver devicemapper failed to remove root filesystem 023c54fd71fd752d7571c8824cc4685858d76be15b41161ef04c84a80b179c5a: mount still active"
```

**Comment by thaJeztah** [comment] 2016-07-12 11:42
ping @rhvgoyal ptal

**Comment by rhvgoyal** [comment] 2016-07-12 13:28
@anosulchik Made couple of observations in other issue. Would be good if you can respond to that here.

**Comment by rhvgoyal** [comment] 2016-07-12 13:35
I think error "mount still active" comes from mounted_layer.go. It does not come from devicemapper graph driver. So I think that particular error is not related to devicemapper graph drvier. Some kind of issue in generic layer w.r.t. releasing of mount points. Reference counting or something else.

**Comment by rhvgoyal** [comment] 2016-07-12 13:37
ReleaseRWLayer()
  m.deleteReference()
     rl.release()
           return error "mount still active"

So looks like we tried to remove a device while it is still being used somewhere. Somebody will have to look into it and fix it.

**Comment by anosulchik** [comment] 2016-07-12 15:06
@rhvgoyal Thanks for your input. Please let me know if you need any info further from my end.

**Comment by rhvgoyal** [comment] 2016-07-12 15:50
Is there a simple reproducer for the problem.

**Comment by anosulchik** [comment] 2016-07-12 16:57
@rhvgoyal At docker 1.11.1 it was possible reproduce the problem faster with options below. At 1.11.2 it doesn't help to get docker hang faster so still have to wait a few hours.

```
--storage-opt dm.use_deferred_removal=false --storage-opt dm.use_deferred_deletion=false
```

**Comment by thaJeztah** [comment] 2016-07-12 17:15
ping @cpuguy83 do you think we should open a new issue, given that this may not be an issue with just device mapper?

**Comment by anosulchik** [comment] 2016-07-14 10:23
Here's the script to reproduce the problem:

```
$ cat ~/docker.hang.sh
#!/bin/bash

while ((1==1));do
  echo "$(date): Starting test container"
  container=$(docker run -d \
    -e APPLICATION_NAME=none \
    -e APPLICATION_LOGFILE_PATTERN=none \
    -e APPLICATION_LOGFILE_FORMAT=none \
    -e SPLUNK_SERVER_HOST=none \
    -e SPLUNK_INDEX=none \
    -e SPLUNK_SERVER=none \
    -e SPLUNK_SERVER_PORT=none \
  -d anosulchik/splunkforwarder622)
  echo "$(date): stopping test container $container"
  docker stop $container && sleep 5
done
```

Disregard docker image that I'm using here, you may image with any application that writes to container's storage.

Today it took 1.5 hours to make docker hanged and reproduce the problem, script's output:

```
Thu Jul 14 08:27:43 UTC 2016: Starting test container
Thu Jul 14 08:27:43 UTC 2016: stopping test container 2180b20d296e894c9e8e4870c8226f0201500fc5814e06127c144d7b504a840b
2180b20d296e894c9e8e4870c8226f0201500fc5814e06127c144d7b504a840b
Thu Jul 14 08:27:59 UTC 2016: Starting test container
Thu Jul 14 08:28:00 UTC 2016: stopping test container 913a24df859d4004d803b82253547d212140b473072a4f185de748aab5a99442
913a24df859d4004d803b82253547d212140b473072a4f185de748aab5a99442
Thu Jul 14 08:28:15 UTC 2016: Starting test container
Thu Jul 14 08:28:15 UTC 2016: stopping test container 304dc3890e8bb166b63b7c6e36b10f5ce05675e6a62e3f662884d43fb5bf6357
304dc3890e8bb166b63b7c6e36b10f5ce05675e6a62e3f662884d43fb5bf6357
Thu Jul 14 08:28:31 UTC 2016: Starting test container
...
...
...
Thu Jul 14 09:58:13 UTC 2016: Starting test container
Thu Jul 14 10:03:22 UTC 2016: stopping test container 05a989316b838a7a9b48e9f90454775810713b26916baf11e584bec01a7a6105
```

**Comment by anosulchik** [comment] 2016-07-14 10:24
@rhvgoyal You may use this script to reproduce the problem.

**Comment by anosulchik** [comment] 2016-07-15 16:31
Guys, any news on this? Thanks.

**Comment by rhvgoyal** [comment] 2016-07-18 13:07
I am hoping that docker folks dealing with reference counting and layer store will have a  look at this issue first. Once that issue is taken care of, then I can look at it from devicemapper point of view, if need be.

**Comment by cpuguy83** [comment] 2016-07-18 13:10
@anosulchik What other options are you starting the daemon with?

**Comment by cpuguy83** [comment] 2016-07-18 13:10
Also, anything in dmesg?

**Comment by anosulchik** [comment] 2016-07-18 14:27
@cpuguy83 Docker daemon is started with the following options:

```
/usr/bin/docker daemon --default-ulimit nofile=1024:4096 --storage-driver devicemapper --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true --storage-opt dm.fs=ext4
```

dmesg doesn't contains suspicious except thousands of lines like below:

```
[2335638.098417] EXT4-fs (dm-6): mounted filesystem with ordered data mode. Opts: (null)
[2335638.285218] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2335734.137629] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2335734.195324] EXT4-fs (dm-6): mounted filesystem with ordered data mode. Opts: (null)
[2335734.370785] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2335830.201252] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2335830.254588] EXT4-fs (dm-6): mounted filesystem with ordered data mode. Opts: (null)
[2335830.429189] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2335926.399523] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2335926.469650] EXT4-fs (dm-6): mounted filesystem with ordered data mode. Opts: (null)
[2335926.652077] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2336022.577094] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2336022.631752] EXT4-fs (dm-6): mounted filesystem with ordered data mode. Opts: (null)
[2336022.816912] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2336118.816499] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
[2336118.881850] EXT4-fs (dm-6): mounted filesystem with ordered data mode. Opts: (null)
[2336119.067871] EXT4-fs (dm-5): mounted filesystem with ordered data mode. Opts: (null)
```

**Comment by cpuguy83** [comment] 2016-07-18 17:10
@anosulchik Thanks for the extra info!
Can you send `SIGUSR1` to the stuck docker daemon and collect the stack trace that it generates from the daemon logs?

**Comment by anosulchik** [comment] 2016-07-20 08:55
Sure, I'm about to reproduce the problem again with that script I've posted earlier and will get back once collected trace logs.

**Comment by anosulchik** [comment] 2016-07-20 15:45
As written above I've tried to reproduced the problem with the script suggested some time ago. This time I created test instances with latest docker 1.11.2 and after 7 hours of running script docker is still alive, no abandoned volumes in `dmsetup ls` or error messages in logs. Here's more info about docker that I've tried:

```
[root@es-staging2-node3 ~]# docker -v
Docker version 1.11.2, build b9f10c9/1.11.2
[root@es-staging2-node3 ~]# docker info
Containers: 1428
 Running: 0
 Paused: 0
 Stopped: 1428
Images: 2
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 20.2 GB
 Data Space Total: 23.35 GB
 Data Space Available: 3.156 GB
 Metadata Space Used: 64.52 MB
 Metadata Space Total: 75.5 MB
 Metadata Space Available: 10.98 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.14-24.50.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.679 GiB
Name: es-staging2-node3
ID: HW2N:HQHR:NOVI:B43X:JIKK:BQMO:FAJZ:K2GV:G6AL:5RKQ:OJYN:2EOL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

Looks like I have to create test instance with 1.11.1 to reproduce the problem. Will provide that info soon.

**Comment by anosulchik** [comment] 2016-08-04 08:42
Today I got the problem described in this issue at newest docker 1.11.2 again, symptoms are similar -- docker hangs after containers are stopping/starting for some time. Please see  requested trace logs from docker.

```
[root@kibana-staging2-0 ~]# docker info
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 4
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 1.733 GB
 Data Space Total: 23.35 GB
 Data Space Available: 21.62 GB
 Metadata Space Used: 2.277 MB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 22.89 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.14-24.50.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.679 GiB
Name: kibana-staging2-0
ID: YOZX:IPAW:6ACO:4R6A:GFQO:45R3:RU3T:HEN4:U2XE:VK7D:ZVZP:LSJ4
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
[root@kibana-staging2-0 ~]# date
Thu Aug  4 08:42:19 UTC 2016
[root@kibana-staging2-0 ~]# uptime
 08:42:20 up 8 days, 20:00,  1 user,  load average: 4.64, 3.96, 3.12
```
[dump.txt](https://github.com/docker/docker/files/401205/dump.txt)

**Comment by anosulchik** [comment] 2016-08-04 08:44
Some more info about issue:

```
[root@kibana-staging2-0 ~]# tail -10 /var/log/docker
time="2016-08-04T08:42:55.255001652Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/08/04 08:42:55 http: multiple response.WriteHeader calls
time="2016-08-04T08:42:55.255273735Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/08/04 08:42:55 http: multiple response.WriteHeader calls
time="2016-08-04T08:42:55.255484038Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/08/04 08:42:55 http: multiple response.WriteHeader calls
time="2016-08-04T08:42:55.255701589Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/08/04 08:42:55 http: multiple response.WriteHeader calls
time="2016-08-04T08:42:55.255899107Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/08/04 08:42:55 http: multiple response.WriteHeader calls
[root@kibana-staging2-0 ~]# dmsetup ls
docker-202:1-263223-5d26ce896faf466701f16d64949c2c70c1507145e652c0ad7bf4306b58b0d77b-init	(253:6)
docker-docker--pool	(253:2)
docker-202:1-263223-1e1a8aae7a5ff44901b4cca8c1ecc2a3220aeedd3fecb2f4d8addcd07380e756	(253:7)
docker-202:1-263223-4582dab249d77a8c8540d71889555d5479d34073f4053b22b8ee39c694411a20	(253:10)
docker-202:1-263223-4582dab249d77a8c8540d71889555d5479d34073f4053b22b8ee39c694411a20-init	(253:11)
docker-202:1-263223-a6c6d13a70a4a7cd30d43faefa5805a22576a42f3e447fc1948db2ec7edc210e	(253:3)
docker-docker--pool_tdata	(253:1)
docker-202:1-263223-5d26ce896faf466701f16d64949c2c70c1507145e652c0ad7bf4306b58b0d77b	(253:4)
docker-docker--pool_tmeta	(253:0)
docker-202:1-263223-1e1a8aae7a5ff44901b4cca8c1ecc2a3220aeedd3fecb2f4d8addcd07380e756-init	(253:13)
```

```
[root@kibana-staging2-0 ~]# iostat -kx
Linux 4.4.14-24.50.amzn1.x86_64 (kibana-staging2-0) 	08/04/2016 	_x86_64_	(1 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.68    0.00    0.69    8.65    0.84   89.14

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await  svctm  %util
xvda              0.00     0.43    0.01    1.93     0.19    11.38    11.93     0.00    1.48   0.40   0.08
xvdcz             0.10     0.27   48.20    0.22  2434.08     4.76   100.73     0.27    5.66   1.85   8.97
dm-0              0.00     0.00    0.00    0.12     0.00     0.49     8.00     0.00    6.50   3.36   0.04
dm-1              0.00     0.00   48.30    0.37  2434.08     4.26   100.21     0.31    6.44   1.84   8.97
dm-2              0.00     0.00   48.30    0.37  2434.08     4.26   100.21     0.31    6.44   1.84   8.97
dm-3              0.00     0.00    0.00    0.00     0.01     0.00    71.85     0.00    2.56   2.05   0.00
dm-10             0.00     0.00    0.01    0.00     0.07     0.01    14.99     0.00  127.36  30.48   0.03
dm-11             0.00     0.00    0.00    0.00     0.02     0.01     8.04     0.00  170.56  29.87   0.02
dm-7              0.00     0.00    0.00    0.00     0.02     0.00     8.08     0.00  108.56  39.20   0.02
dm-13             0.00     0.00    0.00    0.00     0.02     0.00     8.08     0.00  111.71  41.06   0.02
dm-4              0.00     0.00    0.00    0.00     0.00     0.00     9.48     0.00   99.49  22.29   0.00
dm-5              0.00     0.00    0.00    0.00     0.00     0.00     8.00     0.00   40.41  41.22   0.00
```

/dev/xvdcz is used by docker and device mapper.

**Comment by alanferrier-iwin** [comment] 2016-08-26 10:22
We ran the anosulchik's docker.hang.sh script on docker 1.11.2 and experienced a docker hangup after 6 hours.

However, we've put in place a cronjob to tidy up obsolete containers and images:

0 * * * * /usr/bin/docker rm $(/usr/bin/docker ps -aq); /usr/bin/docker rmi $(/usr/bin/docker images -q)

With this in place we've been running docker.hang.sh for 3 days without issue.

**Comment by rhvgoyal** [comment] 2016-08-26 13:56
We are seeing issues with container removal in general due to mount points leaking into various name spaces and that results in Dead containers. I am also considering a cron job to cleanup Dead containers at regular intervals.

Something like.

*/30 * * * * docker rm $(docker ps -aq -f status=dead)

**Comment by tehlers320** [comment] 2016-09-07 02:01
@rhvgoyal we are using https://github.com/meltwater/docker-cleanup which should be removing dead container.  Did your cron work?

Has anybody looked into the kernel messages 
```

Sep  5 10:00:18 ip-10-2-88-245 kernel: [27652.941286] device-mapper: thin: Deletion of thin device 7 failed.
Sep  5 10:10:04 ip-10-2-88-245 kernel: [28239.425133] device-mapper: thin: Deletion of thin device 293 failed.
Sep  5 10:10:04 ip-10-2-88-245 kernel: [28239.510784] device-mapper: thin: Deletion of thin device 291 failed.
Sep  5 10:10:05 ip-10-2-88-245 kernel: [28240.290630] device-mapper: thin: Deletion of thin device 223 failed.
Sep  5 10:10:05 ip-10-2-88-245 kernel: [28240.402819] device-mapper: thin: Deletion of thin device 180 failed.
Sep  5 10:10:05 ip-10-2-88-245 kernel: [28240.491063] device-mapper: thin: Deletion of thin device 178 failed.
Sep  5 10:10:05 ip-10-2-88-245 kernel: [28240.582998] device-mapper: thin: Deletion of thin device 174 failed.
Sep  5 10:10:05 ip-10-2-88-245 kernel: [28240.687042] device-mapper: thin: Deletion of thin device 172 failed.
Sep  5 10:10:05 ip-10-2-88-245 kernel: [28240.771059] device-mapper: thin: Deletion of thin device 159 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28240.868743] device-mapper: thin: Deletion of thin device 154 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28240.976813] device-mapper: thin: Deletion of thin device 112 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.063155] device-mapper: thin: Deletion of thin device 107 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.159256] device-mapper: thin: Deletion of thin device 105 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.255258] device-mapper: thin: Deletion of thin device 74 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.347079] device-mapper: thin: Deletion of thin device 72 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.447247] device-mapper: thin: Deletion of thin device 68 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.547353] device-mapper: thin: Deletion of thin device 57 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.658720] device-mapper: thin: Deletion of thin device 25 failed.
Sep  5 10:10:06 ip-10-2-88-245 kernel: [28241.739274] device-mapper: thin: Deletion of thin device 19 failed.
Sep  6 16:10:18 ip-10-2-88-245 kernel: [136253.147963] device-mapper: thin: Deletion of thin device 77 failed.
Sep  6 20:00:18 ip-10-2-88-245 kernel: [150053.104578] device-mapper: thin: Deletion of thin device 147 failed.
Sep  6 22:10:08 ip-10-2-88-245 kernel: [157843.719955] device-mapper: thin: Deletion of thin device 167 failed.
Sep  6 22:10:08 ip-10-2-88-245 kernel: [157843.798637] device-mapper: thin: Deletion of thin device 165 failed.
Sep  7 00:50:18 ip-10-2-88-245 kernel: [167452.988335] device-mapper: thin: Deletion of thin device 163 failed.
```

**Comment by smoebody** [comment] 2016-12-20 11:50
this seems to be the reason why i cannot remove old containers, see #27381

**Comment by thaJeztah** [comment] 2023-06-06 07:55
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637

**Closed by thaJeztah** 2023-06-06 07:55 UTC
Labels: area/storage/devicemapper, kind/bug, version/1.11
