### ISSUE TITLE
Shared named volume contents caching issue

### ISSUE THREAD

**Issue by 1605200517** [moby/moby#34439] opened 2017-08-08 15:11 UTC
**Description**

**Steps to reproduce the issue:**
1. Setup a Docker stack with a container introducing a shared volume (A) and one another container using it (B)
2. Deploy stack with a name say "foo"
3. Change contents of the shared volume for the image of A, remove stack,  deploy the stack again 
4. Verify contents of the shared volume as seen from B

**Describe the results you received:**
B would see new contents

**Describe the results you expected:**
B sees still the old contents

**Additional information you deem important (e.g. issue happens only occasionally):**
Workaround: 
1. Remove stack we named "foo"
2. Deploy same docker-compose.yml constellation but label it as "baz"
3. Check shared volume's contents as seen from container B.
4. Old contents is gone, welcome new contents!

**Output of `docker version`:**
current CE versions both Windows and Linux

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Two quite different system setups, same behaviour

**Comment by cpuguy83** [comment] 2017-08-08 15:44
Can you provide a full example stack?

**Comment by thaJeztah** [comment] 2018-05-07 14:04
Closing because we need more information to reproduce, but happy to reopen once provided

**Closed by thaJeztah** 2018-05-07 14:04 UTC
Labels: area/stack, area/volumes, status/more-info-needed
