### ISSUE TITLE
Killing a container that has processes in TASK_UNINTERRUPTIBLE state.

### ISSUE THREAD

**Issue by CMajeri** [moby/moby#37886] opened 2018-09-20 00:54 UTC
Hello docker guys,

A while back I hit an issue in my containers which caused PID1 to be stuck in D state.
So the containers became completely unresponsive, and as a result, the container wouldn't die.

So I wrote a small kernel driver that's meant to block processes in D state forever (or until there's a write to the device) to try it out in a more controlled environment. You can find the code here: https://github.com/CMajeri/blocking-char-device

My findings are that if there's a process in D state in the container, whether it be PID 1 or not, docker will never consider the container dead until the process is actually dead.

Is there a way that docker can deal with this? Does anyone have a workaround?

Thanks!

Here's `docker info` and `docker version`.
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 173
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version: 1556cce7e5c5349fdffeb123c092a7681769866a (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 1556cce7e5c5349fdffeb123c092a7681769866a-dirty (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 4.18.7-200.fc28.x86_64
Operating System: Fedora 28 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 15.53 GiB
Name: skywalker
ID: ELMU:AXYR:EGWH:4SV4:FFRI:FZZG:QW73:XSRX:STNQ:NGVM:CKDL:O3LM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Registries: docker.io (secure), registry.fedoraproject.org (secure), quay.io (secure), registry.access.redhat.com (secure), registry.centos.org (secure), docker.io (secure)

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-61.git9cb56fd.fc28.x86_64
 Go version:      go1.10.3
 Git commit:      1556cce-unsupported
 Built:           Wed Aug  1 17:21:17 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-61.git9cb56fd.fc28.x86_64
 Go version:      go1.10.3
 Git commit:      1556cce-unsupported
 Built:           Wed Aug  1 17:21:17 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by thaJeztah** [comment] 2018-10-30 22:55
ping @mlaventure @crosbymichael ptal

**Comment by mlaventure** [comment] 2018-10-31 14:57
I don't think there's much `docker` can do in that case. If the container is stuck in an `uninterruptible sleep`, like the name of the state suggest it's not interruptible and still alive. So IMHO marking the container as alive is the correct behavior there.

**Comment by olljanat** [comment] 2018-12-27 18:01
Derek add label: version/unsupported

**Comment by olljanat** [comment] 2018-12-27 18:02
@CMajeri 1.13.1 is very old and unsupported version. Plz try upgrade to Docker CE 18.09 and try again.

**Comment by thaJeztah** [comment] 2018-12-27 18:16
Based on the above, looks like this is the expected behavior, so let me close this one;

> I don't think there's much docker can do in that case. If the container is stuck in an uninterruptible sleep, like the name of the state suggest it's not interruptible and still alive. So IMHO marking the container as alive is the correct behavior there.

Feel free to continue the conversation though

**Closed by thaJeztah** 2018-12-27 18:16 UTC
Labels: area/runtime, status/more-info-needed, version/1.13, version/unsupported
