### ISSUE TITLE
Containers restart on leader change

### ISSUE THREAD

**Issue by sunilthemaster** [moby/moby#37165] opened 2018-05-28 17:45 UTC
I have 18 node cluster (3 manager & 15 worker).

Suddenly one fine day, leader changed and due to this all services restarted. This disturbed whole docker stack services and few services started behaving weird. 

I have storm supervisor which when gets restarted, moves topologies as an when supervisor container comes up and so most of topologies goes to a single supervisor - resulting in choking of container.

Ideally when leader changes, nothing must happen to existing services. 

**This issue is happening randomly and not on all environments**

**Output of `docker version`:**
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 71
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: cs9af7opvq5i5f0vpaa7j93yb
 Is Manager: true
 ClusterID: 14gun0wu2921u4rij5p3w95u9
 Managers: 3
 Nodes: 18
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.13.153
 Manager Addresses:
  172.31.13.153:2377
  172.31.6.8:2377
  172.31.8.94:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.857 GiB
Name: ip-172-31-13-153
ID: OII5:RSIH:V6UD:HQ5S:FWBH:UCWZ:ZRQJ:5ETS:G7WK:BSIS:AEGP:D445
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region=us-east-2
 availability_zone=us-east-2a
 instance_type=t2.medium
 node_type=manager
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2018-05-29 08:38
- Docker 17.03 reached end of life in June last year, and hasn't been maintained since; do you have a way to reproduce this, and are you able to reproduce this on a current version of Docker?
- Did you collect logs from around the time this happened, and did they provide any useful information?

**Comment by vinaykumar-rm** [comment] 2018-05-31 07:16
Here are the logs.
Manager switch logs
`May 25 23:00:01 ip-10-248-168-74 CRON[6771]: (root) CMD (/usr/local/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --disk-path=/mnt/local --from-cron)
May 25 23:00:40 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:40.447087630Z" level=error msg="agent: session failed" error="rpc error: code = 13 desc = transport is closing" module="node/agent"
May 25 23:00:40 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:40.462758951Z" level=info msg="2d887c223c76b859 [term: 81] received a MsgApp message with higher term from 41c1c978cc19b1a8 [term: 82]"
May 25 23:00:40 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:40.462810820Z" level=info msg="2d887c223c76b859 became follower at term 82"
May 25 23:00:40 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:40.462826915Z" level=info msg="raft.node: 2d887c223c76b859 changed leader from 510d4e4e869a584 to 41c1c978cc19b1a8 at term 82"
May 25 23:00:47 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:47.560799765Z" level=error msg="agent: session failed" error="rpc error: code = 13 desc = transport is closing" module="node/agent"
May 25 23:00:47 ip-10-248-168-74 kernel: [25685778.479501] IPVS: __ip_vs_del_service: enter
May 25 23:00:47 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:47Z" level=info msg="Firewalld running: false"
May 25 23:00:49 ip-10-248-168-74 kernel: [25685779.924315] IPVS: __ip_vs_del_service: enter
May 25 23:00:49 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:49Z" level=info msg="Firewalld running: false"
May 25 23:00:49 ip-10-248-168-74 kernel: [25685780.255293] IPVS: __ip_vs_del_service: enter
May 25 23:00:49 ip-10-248-168-74 kernel: [25685780.424165] IPVS: __ip_vs_del_service: enter
May 25 23:00:49 ip-10-248-168-74 kernel: [25685780.472541] IPVS: __ip_vs_del_service: enter
May 25 23:00:49 ip-10-248-168-74 kernel: [25685780.524322] IPVS: __ip_vs_del_service: enter
May 25 23:00:50 ip-10-248-168-74 kernel: [25685781.145946] IPVS: __ip_vs_del_service: enter
May 25 23:00:49 ip-10-248-168-74 dockerd[7888]: message repeated 4 times: [ time="2018-05-25T23:00:49Z" level=info msg="Firewalld running: false"]
May 25 23:00:50 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:50Z" level=info msg="Firewalld running: false"
May 25 23:00:51 ip-10-248-168-74 kernel: [25685781.992449] IPVS: __ip_vs_del_service: enter
May 25 23:00:51 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:51Z" level=info msg="Firewalld running: false"
May 25 23:00:52 ip-10-248-168-74 kernel: [25685783.074096] IPVS: __ip_vs_del_service: enter
May 25 23:00:52 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:52Z" level=info msg="Firewalld running: false"
May 25 23:00:52 ip-10-248-168-74 kernel: [25685783.125224] IPVS: __ip_vs_del_service: enter
May 25 23:00:53 ip-10-248-168-74 kernel: [25685784.052697] IPVS: __ip_vs_del_service: enter
May 25 23:00:52 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:52Z" level=info msg="Firewalld running: false"
May 25 23:00:53 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:53Z" level=info msg="Firewalld running: false"
May 25 23:00:54 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:54.903206639Z" level=error msg="agent: session failed" error="rpc error: code = 13 desc = transport is closing" module="node/agent"
May 25 23:00:55 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:55Z" level=info msg="Firewalld running: false"
May 25 23:00:55 ip-10-248-168-74 kernel: [25685785.823372] IPVS: __ip_vs_del_service: enter
May 25 23:00:55 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:55Z" level=info msg="Firewalld running: false"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.500465440Z" level=info msg="2d887c223c76b859 is starting a new election at term 82"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.500551542Z" level=info msg="2d887c223c76b859 became candidate at term 83"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.500561309Z" level=info msg="2d887c223c76b859 received vote from 2d887c223c76b859 at term 83"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.500586196Z" level=info msg="2d887c223c76b859 [logterm: 82, index: 119199] sent vote request to 510d4e4e869a584 at term 83"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.500602619Z" level=info msg="2d887c223c76b859 [logterm: 82, index: 119199] sent vote request to 41c1c978cc19b1a8 at term 83"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.500763670Z" level=info msg="raft.node: 2d887c223c76b859 lost leader 41c1c978cc19b1a8 at term 83"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.511755343Z" level=info msg="2d887c223c76b859 received vote from 41c1c978cc19b1a8 at term 83"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.511781894Z" level=info msg="2d887c223c76b859 [quorum:2] has received 2 votes and 0 vote rejections"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.511800788Z" level=info msg="2d887c223c76b859 became leader at term 83"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.511817011Z" level=info msg="raft.node: 2d887c223c76b859 elected leader 2d887c223c76b859 at term 83"`

And after that we are continuously getting below error.

`May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.749160173Z" level=error msg="failed allocating task ejul9jf5kxaga2wufql5j0igm during init" error="failed during networktask allocation for task ejul9jf5kxaga2wufql5j0igm: failed to allocate network IP for task ejul9jf5kxaga2wufql5j0igm network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.751143199Z" level=error msg="failed allocating task ly3w0873em7zvvfr4hrqvh4wr during init" error="failed during networktask allocation for task ly3w0873em7zvvfr4hrqvh4wr: failed to allocate network IP for task ly3w0873em7zvvfr4hrqvh4wr network 1k9ofctnf1svwguhibd516und: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.752065001Z" level=error msg="failed allocating task pdpx1wkcw5f9mjn9avx88b79y during init" error="failed during networktask allocation for task pdpx1wkcw5f9mjn9avx88b79y: failed to allocate network IP for task pdpx1wkcw5f9mjn9avx88b79y network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.752348253Z" level=error msg="failed allocating task q0tcanikn13qtytwawsvk3g24 during init" error="failed during networktask allocation for task q0tcanikn13qtytwawsvk3g24: failed to allocate network IP for task q0tcanikn13qtytwawsvk3g24 network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.752580518Z" level=error msg="failed allocating task qkol2u04zlk0indb6a5nz1rqc during init" error="failed during networktask allocation for task qkol2u04zlk0indb6a5nz1rqc: failed to allocate network IP for task qkol2u04zlk0indb6a5nz1rqc network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.752828777Z" level=error msg="failed allocating task qs34cka0zx3j1yabmvy954pxs during init" error="failed during networktask allocation for task qs34cka0zx3j1yabmvy954pxs: failed to allocate network IP for task qs34cka0zx3j1yabmvy954pxs network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.753230790Z" level=error msg="failed allocating task rskrp7160binwonjycp921i2h during init" error="failed during networktask allocation for task rskrp7160binwonjycp921i2h: failed to allocate network IP for task rskrp7160binwonjycp921i2h network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.753281193Z" level=error msg="failed allocating task rxu2bkncukucvpv25rqsimqo6 during init" error="failed during networktask allocation for task rxu2bkncukucvpv25rqsimqo6: failed to allocate network IP for task rxu2bkncukucvpv25rqsimqo6 network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.753596100Z" level=error msg="failed allocating task sasenpn766af0patmkdfjfw3l during init" error="failed during networktask allocation for task sasenpn766af0patmkdfjfw3l: failed to allocate network IP for task sasenpn766af0patmkdfjfw3l network 1k9ofctnf1svwguhibd516und: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.754287547Z" level=error msg="failed allocating task u8nagdijlnm2zfg8ykm2ok1md during init" error="failed during networktask allocation for task u8nagdijlnm2zfg8ykm2ok1md: failed to allocate network IP for task u8nagdijlnm2zfg8ykm2ok1md network 1k9ofctnf1svwguhibd516und: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.754438551Z" level=error msg="failed allocating task ufuik7n95a672o230424dvh7j during init" error="failed during networktask allocation for task ufuik7n95a672o230424dvh7j: failed to allocate network IP for task ufuik7n95a672o230424dvh7j network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.754628922Z" level=error msg="failed allocating task v00m53xbnkhhxjl9p6layz6h5 during init" error="failed during networktask allocation for task v00m53xbnkhhxjl9p6layz6h5: failed to allocate network IP for task v00m53xbnkhhxjl9p6layz6h5 network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.754814322Z" level=error msg="failed allocating task v4b0yhl5shi7366ljp3w9ixg0 during init" error="failed during networktask allocation for task v4b0yhl5shi7366ljp3w9ixg0: failed to allocate network IP for task v4b0yhl5shi7366ljp3w9ixg0 network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
May 25 23:00:56 ip-10-248-168-74 dockerd[7888]: time="2018-05-25T23:00:56.755003372Z" level=error msg="failed allocating task ve4qrc6mn9d02walc2l3pfe3p during init" error="failed during networktask allocation for task ve4qrc6mn9d02walc2l3pfe3p: failed to allocate network IP for task ve4qrc6mn9d02walc2l3pfe3p network guwfasqpxqgq0dc0ewbi7cmz1: could not allocate IP from IPAM: Address already in use"
`
We have multiple services running in swarm cluster and few of them will recover from this failure but some of them will be in ready state and never come in running state, unless we restart those service.

**Comment by thaJeztah** [comment] 2018-05-31 12:48
Perhaps @ctelfer has some thoughts (I think he was looking into some things around IPAM / allocator), but it will be a long shot; the code base has been moving on for over a year since the 17.03 release, so the issue you run into may already have been addressed.

**Comment by sunilthemaster** [comment] 2018-06-01 12:48
Any workaround for 17.03 version? I have the code in production, so its tough to upgrade docker there. 
Also i will setup a new env. with latest version and try same test there. Hoping its resolved in newer version

**Comment by sam-thibault** [comment] 2023-04-21 09:48
This is an old issue.  I will close it as stale.  If you encounter this issue on a current engine release, please open a new issue.

**Closed by sam-thibault** 2023-04-21 09:48 UTC
Labels: status/more-info-needed, area/networking, area/swarm, version/17.03
