### ISSUE TITLE
docker inspect Examples Incorrect When Overlay Used

### ISSUE THREAD

**Issue by ossie-git** [moby/moby#35887] opened 2017-12-28 01:49 UTC
Just a heads up that the examples over here - https://docs.docker.com/engine/reference/commandline/inspect/#extended-description are incorrect if an overlay network is used.  The Go template extracts 2 IPs in this case (one from the ingress layer and the second the one used by the container) and concatenates them.  Here is an example:

```
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container1
10.255.0.2110.0.1.9
```

The above is on Docker 17.12

```
$ docker version
Client:
 Version:       17.12.0-ce-rc2
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    f9cde63
 Built: Tue Dec 12 06:38:26 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc2
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   f9cde63
  Built:        Tue Dec 12 06:45:30 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by ydjainopensource** [comment] 2018-01-25 01:51
Hi I am a newbie who would love to contribute. I am able to reproduce this issue. I would love to fix this issue. Can someone assign me this?

**Comment by thaJeztah** [comment] 2018-01-25 05:08
Feel free to go ahead and work on this! The markdown file used to generate that page is actually in another repository, and can be found here; https://github.com/docker/cli/blob/master/docs/reference/commandline/inspect.md

**Comment by ydjainopensource** [comment] 2018-01-31 12:40
@thaJeztah

 Internally every docker object which can be inspected has a `runInspect`
 function which is initially called.
 `runInspect` then calls `Inspector.inspect()` with the specified format as one of the passed parameters

 The format passed through is then converted into Go template by the
 `NewTemplateInspectorFromString` function in `inspector.go`
 which is used for formatting the response.

 Since in the above format no white space is specified, both the
 IP addresses are joined without white space.


 See [Golang Template Package Documentation](https://golang.org/pkg/text/template/)

**Comment by ydjainopensource** [comment] 2018-01-31 12:41
To output with a new line the correct command is

 > docker inspect --format='{{range .NetworkSettings.Networks}}{{println .IPAddress}}{{end}}' container1

 To output with a space the correct command is
 

>  docker inspect --format='{{range .NetworkSettings.Networks}} {{.IPAddress}} {{end}}'

 Note the space after '.IPAddress}}'.

**Comment by ydjainopensource** [comment] 2018-02-05 13:54
@thaJeztah Should I work on changing this behavior ? Or can this issue be closed now?

**Comment by thaJeztah** [comment] 2018-02-06 03:23
Perhaps you want to open a PR to improve the examples in the documentation?

**Comment by ydjainopensource** [comment] 2018-02-08 15:34
@thaJeztah I have created a PR [here](https://github.com/docker/docker.github.io/pull/5960)
Can you assign me to another beginner friendly issue?
Thanks in advance

**Comment by thaJeztah** [comment] 2018-02-15 11:54
Thanks! Let me close this issue. The list of "beginner" issues may be a bit out of date (https://github.com/moby/moby/labels/exp%2Fbeginner), but let me know if you found something you think you want to work on (also issues that aren't labeled), then I can check if that issue is still relevant

Also feel free to message me on the docker community slack

**Closed by thaJeztah** 2018-02-15 11:54 UTC
Labels: area/docs, exp/beginner
