### ISSUE TITLE
Possible mistake in docs regarding -v and --mount

### ISSUE THREAD

**Issue by whatisaphone** [moby/moby#37539] opened 2018-07-26 18:32 UTC
**Description**

The documentation on [this page](https://docs.docker.com/storage/bind-mounts/#choosing-the--v-or---mount-flag), under "Differences between -v and --mount behavior", says that there is only one difference between them, but I believe I have found a second: `-v` lets you use a path rooted in your home directory, but `--mount` does not.

**Steps to reproduce the issue:**

```
$ docker run -it --rm -v ~/.bashrc:/.bashrc alpine:3.7 wc /.bashrc
       99       438      3106 /.bashrc

$ docker run -it --rm --mount type=bind,source=~/.bashrc,target=/.bashrc alpine:3.7 wc /.bashrc
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '~/.bashrc' mount path must be absolute.
See 'docker run --help'.
```

**Describe the results you received:**
See above. Also note that the error message is misleading, as `~/.bashrc` ***is*** an absolute path, just one that requires expansion.

**Describe the results you expected:**
As per the docs, I expected the results to be the same using each flag.

**Output of `docker version`:**

I tested this on two hosts:

<details>
  <summary>Linux</summary>
  <pre>$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false</pre>
</details>
<details>
  <summary>Windows -> docker-machine -> VirtualBox</summary>
  <pre>Client:
 Version:       18.03.0-ce
 API version:   1.35 (downgraded from 1.37)
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:20:43 2018
  OS/Arch:      linux/amd64
  Experimental: false</pre>
</details>
<br>

**Output of `docker info`:**
<details>
  <summary>Linux</summary>
  <pre>$ docker info
Containers: 30
 Running: 16
 Paused: 0
 Stopped: 14
Images: 83
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 253
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: www1
ID: ZOCF:S4GP:GBXC:T4H6:4WUI:7IL2:N5DD:Q3YG:TC2B:XVHQ:LHLQ:QDBP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support</pre>
</details>
<details>
  <summary>Windows -> docker-machine -> VirtualBox</summary>
  <pre>Containers: 18
 Running: 3
 Paused: 0
 Stopped: 15
Images: 71
Server Version: 17.12.1-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 140
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.119-boot2docker
Operating System: Boot2Docker 17.12.1-ce (TCL 8.2.1); HEAD : 42357fc - Wed Feb 28 17:52:00 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: jumpseat
ID: 3PNK:6ERH:XDMX:62LX:DFYJ:IYVI:LNBU:ZNGV:UJ3E:SEMM:ONMY:PWAG
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 49
 Goroutines: 72
 System Time: 2018-07-26T18:14:00.698145994Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false</pre>
</details>
<br>

My question is: Is this a mistake on my part or a bug? Is there some flag I need to pass along with `--mount` to maintain the behavior of `-v`? Should it be possible to mount relative to homedir, or should the docs be updated to note this additional difference?

(Note: My use-case requires doing this via docker-compose, so the shell workaround `--mount type=bind,source=$HOME/...` is not an option.

**Comment by MrQubo** [comment] 2018-09-21 05:38
It's not a bug, it's just how tilde expansion works in bash. E.g. see [http://wiki.bash-hackers.org/syntax/expansion/tilde](http://wiki.bash-hackers.org/syntax/expansion/tilde).

**Comment by whatisaphone** [comment] 2018-09-21 11:02
Good catch. My original issue was with docker-compose, and the above was my attempt at a minimal repro. If I quote the path, docker does indeed behave the same with both `-v` and `--mount`.

Here's a repro with docker-compose:

## Works

```yaml
version: '3.5'
services:
  a:
    image: alpine:3.7
    volumes:
      - ~/.bashrc:/.bashrc
    command: wc .bashrc
```

```
Recreating 88f12d6a06f7_temp_a_1 ... done
Attaching to temp_a_1
a_1  |         8        23       240 .bashrc
```

## Broken

```yaml
version: '3.5'
services:
  a:
    image: alpine:3.7
    volumes:
      - type: bind
        source: ~/.bashrc
        target: /.bashrc
    command: wc .bashrc
```

```
Recreating temp_a_1 ... error

ERROR: for temp_a_1  Cannot create container for service a: invalid mount config for type "bind": invalid mount path: '~/.bashrc' mount path must be absolute

ERROR: for a  Cannot create container for service a: invalid mount config for type "bind": invalid mount path: '~/.bashrc' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
```

I had assumed docker-compose volume config was just a thin layer over docker volume config, but it appears docker-compose does its own expansion… sometimes. [The docs](https://docs.docker.com/compose/compose-file/#long-syntax-3) indicate that relative paths can be used in both short and long syntax. So the error message above, coming directly from docker, is misleading – it's basically saying that `docker-compose` failed to expand the mount path into an absolute path. And as per the docs, relative paths can indeed be used, e.g. I can do this:

```
    volumes:
      - type: bind
        source: .
        target: /here
```


I guess my next step is to upgrade to the latest docker-compose and see if I can still repro. If so, I will file an issue directly against docker-compose.

**Comment by thaJeztah** [comment] 2018-09-21 11:16
Yes, this doesn't look like a bug to me (at least, not in the "engine", possibly there's things in docker-compose) if improvements to the docs are still needed, it's best to report those in the docs repository; https://github.com/docker/docker.github.io

**Comment by thaJeztah** [comment] 2018-09-21 11:16
Closing this here, but feel free to continue the conversation

**Closed by thaJeztah** 2018-09-21 11:16 UTC
Labels: version/17.05
