### ISSUE TITLE
Windows 10 Creator's Update Broke Docker for Windows?

### ISSUE THREAD

**Issue by vikalyan** [moby/moby#33068] opened 2017-05-07 05:03 UTC
This item was created after discussing this problem over in [Docker for Windows Issue #703](https://github.com/docker/for-win/issues/703). Bringing it to the attention of @jhowardmsft 

### Expected behavior
On Windows 10, after updating to the Creators Update, Docker can continue to start and run containers as before the update.

### Actual behavior
On Windows 10 Creators Update, container startup fails with the following error code: 0xc0370106

### Information
I am using Azure container registry. The image I am using is a custom image. I am using Windows containers. 

```
Docker Community Edition Version 17.03.1-ce-win5 (10743)
Channel: stable
b18e2a5

Windows 10 Enterprise Version 1703 (Build number 15063.0)
```
Output of docker info:-

```
D:\cdpx\pipeline-engine\output\bin\windows>docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.91 GiB
Name: vikalyan-hp
ID: 6U2M:2IFF:WJVW:GONX:GBCE:T4TY:G55T:YV4I:BTYQ:PUIW:GEAH:3MNH
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 22
 System Time: 2017-05-03T22:07:54.2492939-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
Azure Container registry is "cdpxtest.azurecr.io" and image name is "samples/wsmobile".

### Steps to reproduce the behavior

If I start the container with a simple invocation of docker run such as 

    docker run -t -d --name FOO "cdpxtest.azurecr.io/samples/wsmobile"

the container starts up and runs fine. 

However, a more complex invocation that involves passing in volumes to map and resources to provision, fails. Example:-

```
docker run  -v "d:\mysource":"C:\source":rw      -v "c:\drop":"C:\temppriordrop":ro      -v "c:\credentials":"C:\tempcredentials":ro      -v "c:\scripts":"C:\tempscripts":ro      --memory 3000m      --cpu-count 1    --env-file "c:\credentials\environment.info"          -t -d --name "FOO"      "cdpxtest.azurecr.io/samples/wsmobile"
2d8c5f024893ba24974c26a70950374f2ab1388d2a04b95b57489db8dc71a37c
C:\Program Files\Docker\docker\resources\bin\docker.exe: Error response from daemon: container 2d8c5f024893ba24974c26a70950374f2ab1388d2a04b95b57489db8dc71a37c encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106).
```

This exact same invocation used to work before the Creator's update several times for the past few weeks. 

After attempting to see which particular option was causing the container to not start, it looks like the bind mount of the source folder is causing the container startup to fail. Not sure why this happens. The source folder existed prior to installing the creators update as well. 

So I tried a few more debugging steps:

1. Copied the folder from D: to C:. No luck.
2. Created an empty folder in C: - That worked. A difference between the other folders and the source folder is that the ones in C: that did mount were not empty.
3. I also checked security permissions. Since the host is not a domain joined net
work, I thought maybe something to do with file ACLs? Not sure.
4. I am using Windows containers.

The container image doesn't have a C:\source at all. Also, this was working before. Same image, same invocation etc.

**Comment by friism** [comment] 2017-05-07 16:51
cc @jstarks @jhowardmsft

**Comment by jhowardmsft** [comment] 2017-05-08 18:38
@vikalyan That error is coming from below docker - HCS or GCS. Does this work on a Windows Server container? (Windows 10 only supports Hyper-V containers, so that must be the above scenario).  How can I attempt to repro this locally? You might want to ping `ContainerTriage` DL internally.

**Comment by vikalyan** [comment] 2017-05-18 01:34
@jhowardmsft Yes, this used to work both on Windows Server 2016 and Windows 10. I am surprised that Windows 10 supports only Hyper-V containers or perhaps I just didn't notice? I thought that Docker for Windows required an explicit --provider=hyperv argument to use Hyper-V instead of Windows containers? In any case, the key point is this used to work before the Creator's update and stopped after. Will ping ContainerTriage internally as well.

**Comment by friism** [comment] 2017-05-18 01:58
@vikalyan Docker has different defaults based on platform capabilities. On Windows 10, the default is Hyper-V isolation, on WS2016 it's process isolation

**Comment by jhowardmsft** [comment] 2017-05-18 02:35
For the platform defaults, this has been the case since RTM. Windows 10 only supports Hyper-V containers. 2016 supports Windows Server containers (a clue is in the name) and is the default, plus Hyper-V containers

**Comment by vikalyan** [comment] 2017-05-18 17:58
@jhowardmsft @friism Not a problem. Looks like this might be a Hyper-V provider specific problem then. Switched to Windows Server 2016 for development box (production uses Server already) and no issues since then.

**Comment by thaJeztah** [comment] 2017-05-22 15:37
should this issue be closed?

**Comment by vikalyan** [comment] 2017-05-23 01:35
@thaJeztah Yes please. Appears to be Windows container implementation related.

**Comment by thaJeztah** [comment] 2017-05-24 15:56
Thanks! Closing

**Closed by thaJeztah** 2017-05-24 15:56 UTC
Labels: platform/desktop, platform/windows

**Comment by cowlinator** [comment] 2020-06-23 00:20
@thaJeztah , @vikalyan , 

I understand that there is a Windows issue here, and that there is a workaround that involves switching the host to be Windows Server 2016.  

But the issue here was not resolved.  Why was this closed?  Does this mean that Windows 10 is just simply not supported for docker?  Can someone weigh in here?

**Comment by thaJeztah** [comment] 2020-06-23 08:10
@cowlinator this issue was closed over 3 years ago, very likely on a different version of Windows 10 than you have installed now (and a different version of Docker), so the underlying issue may be different. If you suspect there's a bug and you have steps to reproduce, please open a new ticket with detailed information.
