### ISSUE TITLE
Docker network failures with more than 1002 containers

### ISSUE THREAD

**Issue by gbouv** [moby/moby#44973] opened 2023-02-10 14:54 UTC
### Description

I trying to deploy a lot of containers and connect all of them to a single docker network, and it turns out there seem to be a hard limit at 1002 containers which I cannot really explain. Past this limit (>=1003), containers continue to start fine, but they cannot communicate with each other anymore.

I was able to repro the issue with very simple scripts using the `docker/getting-started` image and testing the connection between containers using `nc -zv <IP> 80`

Note that I am 99.9% certain we're not resource constrained. The simplest proof is that I can start 1010 standalone containers. As long as I don't play with network, docker operates just fine.

Sorry if this has already been raised. I couldn't find anything doing my research

### Reproduce

1. Get a large box. It's easy to hit memory limits, file descriptor limits, etc. I'm currently using an AWS ubuntu server:
```
Linux <HOSTNAME_REDACTED> #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
type `c5a.8xlarge` (i.e. 32 vCPU, 64Gb memory)

2. Make sure to bump a few limits to make sure you don't get contrained by the OS:
```bash
ulimit -n 1048576 && ulimit -u 1048576 # file descriptors and processes
sysctl -w net.ipv4.neigh.default.gc_thresh3=4096 # for the ARP table
sysctl fs.inotify.max_user_instances=1048576
```

3. create a docker network. I chose to use a /20 network, which technically allows 4096 IPs
```bash
docker network create --subnet 65.28.128.0/20 --gateway 65.28.128.1 docker-issue
```

4. start 1002 `docker/getting-started` containers connected to the network. This takes a few minutes, but not the end of the world
```bash
for (( i=0; i < 1002 ; i++ )); do
        docker container create --name "container-$i" --net 'docker-issue' docker/getting-started
        docker container start "container-$i"
done
```

5. We have 1002 containers, so everything should work just fine, we can test connection of each container to, for example, the first one. Get the first container IP first, and then test the connection to all other containers:
```bash
docker exec container-0 ifconfig # double check container-0 IP. It should be `65.28.128.2` given the network subnet above

for (( i=1; i < 1002; i++ )); do
        echo "container-$i"
        docker exec "container-$i" sh -c "nc -zv 65.28.128.2 80"
done
```
This should return successfully with a bunch of:
```
container-1
65.28.128.2 (65.28.128.2:80) open
container-2
65.28.128.2 (65.28.128.2:80) open
container-3
...
...
container-1000
65.28.128.2 (65.28.128.2:80) open
container-1001
65.28.128.2 (65.28.128.2:80) open
```

6. Now add one single additional container
```bash
docker container create --name 'container-2002' --net 'docker-issue' docker/getting-started
docker container start 'container-2002'
```

7. Rerun the test loop:
```bash
# go all the way up to 1003 (excluded) here, even though things should fail earlier in the loop
for (( i=1; i < 1003; i++ )); do
        echo "container-$i"
        docker exec "container-$i" sh -c "nc -zv 65.28.128.2 80"
done
```
It fails immediately (you can Ctrl+C as the entire will take a lot of time to run, but the point is made):
```
container-1
nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
container-2
nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
container-3
nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
container-4
nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
container-5
```

### Expected behavior

Given that the network is `/20` I would expect things to work fine all the way up to 4094 hosts. I can't really explain why things get messy at 1002 specifically.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:47:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:47:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 1003
  Running: 1003
  Paused: 0
  Stopped: 0
 Images: 51
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-1028-aws
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.13GiB
 Name: ip-172-31-24-12
 ID: 7STL:3PQ4:P2SZ:OMZZ:HUJE:JILR:3V45:GS7O:QL6I:2DPS:NLAW:NRCG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Another thing to note, it really seem to be a _per docker network_ kind of thing. For example, I was able to create 2 networks, connect 1001 containers to each (so, 2002 containers in total), and everything was working fine.

**Comment by polarathene** [comment] 2023-05-11 10:22
Docker _may_ have something going on that prevents you from adding the full 1023 network devices to the bridge before you get a failure, but **21 more containers probably isn't much more of an improvement**.

Maybe someone who knows how to investigate this better will chime in with why that happens (_since the `/sys/class/net/<bridge name>/brif` matches the container count, should be room to spare?_).

Otherwise, considering the benefit of trying to resolve that is minimal, if it doesn't warrant the time to investigate further, **consider closing**?

---

## Reproduced

Reproduced on a Vultr VPS running Ubuntu 23.04 with 6.2 kernel and Docker 23.0.6 (_with IPv4 subnet replaced as `172.20.0.0/20`_). Almost 8GB of RAM is required to comfortably run that many container instances of the image.

```console
# From container:
$ docker exec "container-42" sh -c "nc -zv 172.20.0.2 80"
nc: 172.20.0.2 (172.20.0.2:80): Host is unreachable

# From host:
$ curl 172.20.0.2
curl: (7) Failed to connect to 172.20.0.2 port 80 after 3071 ms: Couldn't connect to server

# Host failure differs from containers:
$ nc -zv 172.20.0.2 80
nc: connect to 172.20.0.2 port 80 (tcp) failed: No route to host
```

I'm not sure why it starts to fail after 1002 containers are connected to the network.

---

## Bottlenecks that follow

Regardless of docker, you would still run into another issue fairly quickly as [a bridge interface is limited to 1024 "ports"](https://github.com/torvalds/linux/blob/80e62bc8487b049696e67ad133c503bf7f6806f7/net/bridge/br_private.h#L28) (_each veth [interface added is considered a bridge "port"](https://hechao.li/2018/01/31/linux-bridge-part2/) - mentioned in the "Add an Interface" section_).

This would result in receiving a failure when adding a 1024th container into the network:

```
Error response from daemon: failed to create endpoint container-1023 on network docker-issue: adding interface veth72b78a8 to bridge br-cdccdac89948 failed: exchange full
Error: failed to start containers: container-1023
```

```console
# Count the number of interfaces attached to the bridge:
$ ls -1 /sys/class/net/br-cdccdac89948/brif | wc -l
1023
```

While this can be resolved, you'll run into more issues along the way.

IBM has a [blogpost about running 10k containers, and the various bottlenecks you'll run into and how to resolve them](https://www.ibm.com/cloud/blog/docker-insane-scale-on-ibm-power-systems) (_see [this **related moby issue** for advice](https://github.com/moby/moby/issues/1320#issuecomment-22346764) for alternatives to avoid changing `BR_MAX_PORTS` which requires compiling a kernel_).

---

## Potential alternative / workaround

Below uses `/24` subnets, but since you're limited to 253 IP per `/24`, you may prefer managing `/22` subnets with the current 1002 container limit in mind?

I have seen mentions of connecting bridge networks with a veth pair, but I am not experienced with this to understand why or how that'd work. In my own testing, it didn't seem relevant, and the containers could reach each other across networks if `iptables: false` and handling anything else that was in the way like disabling UFW as a quick fix. Perhaps connecting bridge networks would work with some extra config to support it :man_shrugging: 

This is a temporary example based on what I've seen advised (_for linking non-docker bridge networks_):

```bash
# Set bridge name so you don't have to lookup the ID via `docker network ls`
# /24 subnet provides 253 addresses per network
docker network create \
  --subnet=172.21.0.0/24 \
  --opt 'com.docker.network.bridge.name=bridge-a' \
  bridge-a

docker network create \
  --subnet=172.21.1.0/24 \
  --opt 'com.docker.network.bridge.name=bridge-b' \
  bridge-b

# Create a veth pair, name them whatever you like:
ip link add veth0 type veth peer name veth1
# Add one to each bridge:
ip link set veth0 master bridge-a
ip link set veth1 master bridge-b
# Bring them up (no IP assigned):
ip link set veth0 up
ip link set veth1 up
```

References:
- https://linux-blog.anracom.com/tag/linux-bridge-linking/ (_Section: "Linking of two Linux bridges with each other"_)
- https://stackoverflow.com/questions/32496080/how-many-virtual-interfaces-can-be-added-to-default-lxcbr0-bridge-provided-by-lx/32811257#32811257
- https://unix.stackexchange.com/questions/700447/linux-bridge-what-does-master-mean-in-the-ip-link-set/700629#700629
- https://unix.stackexchange.com/questions/255484/how-can-i-bridge-two-interfaces-with-ip-iproute2/255489#255489
- https://serverfault.com/questions/988736/possible-to-list-members-of-a-network-bridge/989852#989852

Something like [weave](https://github.com/weaveworks/weave) may also be more suitable for you? Or a different network driver from bridge, I often see macvlan advised :man_shrugging:

**Comment by polarathene** [comment] 2023-05-11 10:32
## Solution

**Issue can now be closed**

In the old moby issue referenced was [this comment](https://github.com/moby/moby/issues/1320#issuecomment-314874536), which a reply implied it was unrelated and the link itself didn't have content anymore. After posting my response above, I thought to do a search on the link title, and it seems the question was just relocated to `superuser.com` :tada: 

https://superuser.com/questions/1229292/why-i-can-only-ping-1001-interface-out-of-1023-that-are-connected-to-a-linux-bri/1229641#1229641

This will temporarily fix it for you: `sysctl net.core.netdev_max_backlog=1024`

---

Now you'll hit the 1024 limit for bridges, unless you figure out how to link bridges apparently which I attempted to investigate :sweat_smile:

**Comment by akerouanton** [comment] 2023-05-23 12:41
For the record, I tried to reproduce this issue with the help of [cilium/pwru](https://github.com/cilium/pwru) and I can confirm 22 ARP frames are dropped by the kernel with the reason: `SKB_DROP_REASON_CPU_BACKLOG`.

```console
$ docker network create testnet
$ for i in $(seq 1 1023); do { docker run --rm -d --network testnet --name test${i} alpine /bin/sleep infinity; } & done
$ wait
$ ping -c 1 172.18.4.0
$ ping 172.18.0.2 &
$ sudo pwru --output-meta --filter-func kfree_skb_reason | grep ping
0xffff9c3b552ed000      7           [ping] kfree_skb_reason(SKB_DROP_REASON_CPU_BACKLOG) netns=4026533703 mark=0x0 ifindex=48 proto=608 mtu=1500 len=28
... And 20 more dropped packets with proto=608 and ifindex decreasing by two each time ...
0xffff9c385b3b7e00      7           [ping] kfree_skb_reason(SKB_DROP_REASON_CPU_BACKLOG) netns=4026532408 mark=0x0 ifindex=6 proto=608 mtu=1500 len=28
```

I don't think there's much we can do here except document (/cc @dvdksn):

* The default `netdev_max_backlog` limit at 1000, how to increase it (ie. `sysctl -w net.core.netdev_max_backlog=1024`)  ;
* The limit of 1023 interfaces per bridge and the error message dockerd/cli returns (ie. `Error response from daemon: failed to create endpoint container-1023 on network docker-issue: adding interface veth72b78a8 to bridge br-cdccdac89948 failed: exchange full`) ;

**Comment by akerouanton** [comment] 2023-07-10 18:42
Since we added a section about this limitation to the bridge netdriver docs ([see here](https://docs.docker.com/network/drivers/bridge/#connection-limit-for-bridge-networks)), there's nothing more we can do. So let me close this issue.

**Closed by akerouanton** 2023-07-10 18:42 UTC
Labels: status/0-triage, kind/bug, area/networking, version/23.0

**Comment by dgtlmoon** [comment] 2024-09-11 08:19
Hello from 2024 - I want to say these instructions are still 100% relative.

Here's some archive.org links to some invaluable information that arent around anymore

https://web.archive.org/web/20221128011825/https://sseelam.blogspot.com/

https://web.archive.org/web/20220820004219/https://www.ibm.com/cloud/blog/docker-insane-scale-on-ibm-power-systems  <-- the best one

Happily running on my own custom `5.15.0-119-generic #129+BRPORTBITS11` for now

**Comment by Osama2035** [comment] 2025-05-20 02:30
Osam a

**Comment by Osama2035** [comment] 2025-05-20 02:31
> ### وصف
> أحاول نشر العديد من الحاويات وربطها جميعًا بشبكة Docker واحدة، وتبين لي وجود حد أقصى يبلغ 1002 حاوية، وهو أمر لا أستطيع تفسيره. بعد تجاوز هذا الحد (>=1003)، تستمر الحاويات في العمل بشكل جيد، لكنها لا تتواصل مع بعضها البعض.
> 
> تمكنت من إصلاح المشكلة باستخدام نصوص بسيطة للغاية باستخدام `docker/getting-started`الصورة واختبار الاتصال بين الحاويات باستخدام`nc -zv <IP> 80`
> 
> لاحظ أنني متأكد بنسبة 99.9% من أننا لسنا مقيدين بالموارد. أبسط دليل على ذلك هو أنني أستطيع تشغيل 1010 حاويات مستقلة. طالما أنني لا أتعامل مع الشبكة، فإن Docker يعمل بشكل جيد.
> 
> أعتذر إن كان هذا قد طُرح سابقًا. لم أجد أي شيء أثناء بحثي.
> 
> ### تكاثر
> 1. احصل على صندوق كبير. من السهل تجاوز حدود الذاكرة، وحدود وصف الملفات، وما إلى ذلك. أستخدم حاليًا خادم AWS Ubuntu:
> 
> ```
> Linux <HOSTNAME_REDACTED> #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> النوع `c5a.8xlarge`(أي 32 وحدة معالجة مركزية افتراضية، وذاكرة 64 جيجابايت)
> 
> 2. تأكد من تجاوز بعض الحدود للتأكد من عدم تقييدك بواسطة نظام التشغيل:
> 
> ulimit -n 1048576 && ulimit -u 1048576 # file descriptors and processes
> sysctl -w net.ipv4.neigh.default.gc_thresh3=4096 # for the ARP table
> sysctl fs.inotify.max_user_instances=1048576
> 3. إنشاء شبكة Docker. اخترتُ استخدام شبكة /20، والتي تسمح تقنيًا باستخدام 4096 عنوان IP.
> 
> docker network create --subnet 65.28.128.0/20 --gateway 65.28.128.1 docker-issue
> 4. بدء تشغيل 1002 `docker/getting-started`حاوية متصلة بالشبكة. يستغرق هذا بضع دقائق، ولكنه ليس نهاية العالم.
> 
> for (( i=0; i < 1002 ; i++ )); do
>         docker container create --name "container-$i" --net 'docker-issue' docker/getting-started
>         docker container start "container-$i"
> done
> 5. لدينا 1002 حاوية، لذا كل شيء يعمل بشكل جيد. يمكننا اختبار اتصال كل حاوية بالحاوية الأولى مثلاً. احصل على عنوان IP للحاوية الأولى أولاً، ثم اختبر الاتصال بجميع الحاويات الأخرى:
> 
> docker exec container-0 ifconfig # double check container-0 IP. It should be `65.28.128.2` given the network subnet above
> 
> for (( i=1; i < 1002; i++ )); do
>         echo "container-$i"
>         docker exec "container-$i" sh -c "nc -zv 65.28.128.2 80"
> done
> يجب أن يعود هذا بنجاح مع مجموعة من:
> 
> ```
> container-1
> 65.28.128.2 (65.28.128.2:80) open
> container-2
> 65.28.128.2 (65.28.128.2:80) open
> container-3
> ...
> ...
> container-1000
> 65.28.128.2 (65.28.128.2:80) open
> container-1001
> 65.28.128.2 (65.28.128.2:80) open
> ```
> 
> 6. الآن قم بإضافة حاوية إضافية واحدة
> 
> docker container create --name 'container-2002' --net 'docker-issue' docker/getting-started
> docker container start 'container-2002'
> 7. أعد تشغيل حلقة الاختبار:
> 
> # go all the way up to 1003 (excluded) here, even though things should fail earlier in the loop
> for (( i=1; i < 1003; i++ )); do
>         echo "container-$i"
>         docker exec "container-$i" sh -c "nc -zv 65.28.128.2 80"
> done
> يفشل الأمر على الفور (يمكنك الضغط على Ctrl+C لأن العملية بأكملها ستستغرق الكثير من الوقت للتشغيل، ولكن تم توضيح النقطة):
> 
> ```
> container-1
> nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
> container-2
> nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
> container-3
> nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
> container-4
> nc: 65.28.128.2 (65.28.128.2:80): Host is unreachable
> container-5
> ```
> 
> ### السلوك المتوقع
> بما أن الشبكة تعمل، `/20`أتوقع أن تعمل بشكل جيد حتى 4094 مضيفًا. لا أستطيع تفسير سبب فوضى الشبكة عند 1002 مضيفًا تحديدًا.
> 
> ### إصدار Docker
> Client: Docker Engine - Community
>  Version:           23.0.0
>  API version:       1.42
>  Go version:        go1.19.5
>  Git commit:        e92dd87
>  Built:             Wed Feb  1 17:47:51 2023
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          23.0.0
>   API version:      1.42 (minimum version 1.12)
>   Go version:       go1.19.5
>   Git commit:       d7573ab
>   Built:            Wed Feb  1 17:47:51 2023
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.16
>   GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
>  runc:
>   Version:          1.1.4
>   GitCommit:        v1.1.4-0-g5fd4c4d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ### معلومات الحاوية
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.10.2
>     Path:     /usr/libexec/docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.15.1
>     Path:     /usr/libexec/docker/cli-plugins/docker-compose
>   scan: Docker Scan (Docker Inc.)
>     Version:  v0.23.0
>     Path:     /usr/libexec/docker/cli-plugins/docker-scan
> 
> Server:
>  Containers: 1003
>   Running: 1003
>   Paused: 0
>   Stopped: 0
>  Images: 51
>  Server Version: 23.0.0
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Using metacopy: false
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: systemd
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
>  runc version: v1.1.4-0-g5fd4c4d
>  init version: de40ad0
>  Security Options:
>   apparmor
>   seccomp
>    Profile: builtin
>   cgroupns
>  Kernel Version: 5.15.0-1028-aws
>  Operating System: Ubuntu 22.04.1 LTS
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 32
>  Total Memory: 62.13GiB
>  Name: ip-172-31-24-12
>  ID: 7STL:3PQ4:P2SZ:OMZZ:HUJE:JILR:3V45:GS7O:QL6I:2DPS:NLAW:NRCG
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> ### معلومات إضافية
> ملاحظة أخرى، يبدو أن الأمر يتعلق _بشبكة خاصة بكل حاوية_ . على سبيل المثال، تمكنتُ من إنشاء شبكتين، وربط 1001 حاوية بكل منهما (أي 2002 حاوية إجمالاً)، وكان كل شيء يعمل بشكل جيد.

https://github.com/moby/moby/issues/44973#issue-1579815716
