### ISSUE TITLE
Multiple network with the same name can be created with API parameter CheckDuplicate=ture

### ISSUE THREAD

**Issue by KevinTHU** [moby/moby#33037] opened 2017-05-05 07:49 UTC
reference #29268
**Description**
Multiple network with the same name can be created by calling docker network create NAME simultaneously.
I have check that docker network CLI has set the API parameter CheckDuplicate=ture.

**Steps to reproduce the issue:**
$ ( docker network create test-net & docker network create test-net ); docker network ls

**Describe the results you received:**
$ ( docker network create test-net & docker network create test-net ); docker network ls
e03262ffa37e0c9546a49e684d6f58906bfeba04a2a62d09d6df8c2391f03f86
83ca3d11ba82f82325b1539b2e7f8d5e67be75b68d02c117ff2f0c2861fea72f
NETWORK ID          NAME                                                 DRIVER              SCOPE           
83ca3d11ba82        test-net                                             bridge              local               
e03262ffa37e        test-net                                             bridge              local 

**Describe the results you expected:**
$ ( docker network create test-net & docker network create test-net ); docker network ls
e03262ffa37e0c9546a49e684d6f58906bfeba04a2a62d09d6df8c2391f03f86
Error response from daemon: network with name test already exists
NETWORK ID          NAME                DRIVER              SCOPE                  
e03262ffa37e        test                bridge              local

**Additional information you deem important (e.g. issue happens only occasionally):**
issue happens only occasionally

**Output of `docker version`:**
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 130
 Running: 5
 Paused: 0
 Stopped: 125
Images: 464
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 201.7 GB
 Data Space Total: 1.1 TB
 Data Space Available: 897.8 GB
 Metadata Space Used: 58.34 MB
 Metadata Space Total: 10.74 GB
 Metadata Space Available: 10.68 GB
 Thin Pool Minimum Free Space: 110 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: vlcp overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.6 GiB
Name: kvm-yz-dev-073-003-004
ID: CED3:DJX6:VW6I:LJLX:CEVJ:Z4L2:FYPX:KTIQ:CTO2:4JRD:U7L3:WN4L
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 86
 Goroutines: 103568
 System Time: 2017-05-05T15:49:26.699282035+08:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: zk://100.73.3.4:2181,100.73.3.5:2181,100.73.3.6:2181
Cluster Advertise: 100.73.3.4:2375
Insecure Registries:
 jdocker.me
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2017-10-11 14:29
This is documented in the API reference https://docs.docker.com/engine/api/v1.31/#operation/NetworkDelete

<img width="1147" alt="screen shot 2017-10-11 at 16 27 52" src="https://user-images.githubusercontent.com/1804568/31446979-2abdd7d4-aea1-11e7-8c15-6ed687471061.png">

The underlying issue is that this is by design (see https://github.com/moby/moby/issues/18864#issuecomment-167006094). I'm closing this issue in favour of https://github.com/moby/moby/issues/18864, so that the conversation doesn't diverge

**Closed by thaJeztah** 2017-10-11 14:29 UTC
Labels: area/networking, version/1.12
