### ISSUE TITLE
Pulling a Docker image on Windows Server 1709 fails

### ISSUE THREAD

**Issue by akunaatrium** [moby/moby#36092] opened 2018-01-23 09:28 UTC
Pulling a Docker image on Windows Server 1709 results in the following error:
```
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\docker\windowsfilter\f9c77790f5b889adf48e5f792007be56639d6a8c12e48ce1ce78be19fe02b8de\UtilityVM\Files\Windows\WinSxS\amd64_microsoft-windows-dns-client-minwin_31bf3856ad364e35_10.0.16299.15_none_b877dfb2944a0d10\dnsrslvr.dll: Access is denied.
```

I don't know how to reproduce it with a minimum amount of steps or how to create the image that would fail to pull. It is possible to pull the image on a clean machine (with Docker installed) but if the machine configuration reaches to some unknown state, pulling the image returns the error mentioned above.

I hope this error message itself is informative enough for the Docker or Windows developers that might help either resolving the underlying issue or at least provide an actual description of why the error happens, so that I (and maybe others) could work around it.

**Steps to reproduce the issue:**
Unknown

**Describe the results you received:**
The error message above.

**Describe the results you expected:**
Docker image pulled successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens only when the system has reached to a specific unknown configuration state.

**Output of `docker version`:**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:09:12 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.10.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5GiB
Name: test345
ID: B7YR:TIDP:F5G4:CPLZ:JJG3:ZKEO:55LD:DMGY:YQOX:BGDV:AY3J:LQ47
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM in Azure (Windows Server 2016, version 1709)

**Comment by sandersaares** [comment] 2018-02-13 18:52
I am also encountering this. The filename referenced is the same as in the OP although the ID is different:

```
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\docker\windowsfilter\6064acd38a41dd3afe490067296b1dc47340e0b4a20cb94765120bb202e0986b\UtilityVM\Files\Windows\WinSxS\amd64_microsoft-windows-dns-client-minwin_31bf3856ad364e35_10.0.16299.15_none_b877dfb2944a0d10\dnsrslvr.dll: Access is denied. 
```

No obvious reason for it - the same images being started in containers here are building just fine on other Windows 1709 machines from where they are pushed.

**Comment by sandersaares** [comment] 2018-02-14 06:13
Seems to occur when pulling containers that use different versions of windowsservercore:1709 (different KB numbers).

**Comment by darrenstahlmsft** [comment] 2018-03-15 22:35
We understand the problem and will have a fix ready soon. See https://github.com/Microsoft/hcsshim/issues/155.

This is caused by a running container holding the source of hard links created in the new KB update open.

There are two possible workarounds while waiting for the fix:

- Pull the failing image while no containers are running on the host
- Base the new container image off the same base image as the running container. I.E. base all images off `1709_KB4088776` instead of `1709`

**Comment by chlowell** [comment] 2018-03-20 18:59
@darrenstahlmsft Any timeline on shipping a fix?

**Comment by darrenstahlmsft** [comment] 2018-04-02 23:28
I don't have anything I can share yet, but a fix will be coming soon!

**Comment by jhowardmsft** [comment] 2018-11-08 19:51
@darstahl I know you're far detached from this these days, but do you know if a fix ever went in (platform possibly for RS5)?

**Comment by darstahl** [comment] 2018-11-08 22:33
IIRC This was fixed in https://github.com/Microsoft/hcsshim/pull/167 by using `fileDispositionInformationEx` which allows deletions of symlinks to files in use by other containers. I must've missed closing this issue and the related hcsshim issue when that release went out. There is not a required platform update (the failure is by design when not using fileDispositionInformationEx)

**Comment by jhowardmsft** [comment] 2018-11-08 22:51
Thanks Darren!

**Closed** 2018-11-08 22:58 UTC
Labels: platform/windows, version/17.10
