### ISSUE TITLE
The 'bash' binary file was changed / destroyed in container

### ISSUE THREAD

**Issue by zjxpsetp** [moby/moby#26513] opened 2016-09-13 03:00 UTC
**Output of `docker info`:**

root@root:~# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-57775-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.96 GB
 Data Space Total: 107.4 GB
 Data Space Available: 20.38 GB
 Metadata Space Used: 3.83 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.829 GiB
Name: doctor
ID: MBX4:LN2T:RZ3I:OZYJ:T57U:KR3A:CKCJ:IDXZ:NVAN:HQOE:MDXA:TAUJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
(paste your output here)

```

Hi,

We build docker image based on 'ubuntu'. And found sometimes get error "standard_init_linux.go:175: exec user process caused "exec format error" when restart docker container.

And today we found more details about this problem:
when we run shell script in container but get "bash  cannot execute binary file: Exec format error". It seems that the binary file was changed and destoryed by docker.
```

**Comment by justincormack** [comment] 2016-09-13 10:10
Please give enough information to reproduce the problem. Without seeing your `Dockerfile` it is impossible to have any idea how you are removing the `bash` file or what you are doing.

**Comment by zjxpsetp** [comment] 2016-09-13 15:16
Hi, here is my dockerfile. And worked well in docker 1.6 - 1.9, we just upgrade to 1.12 and find some problems in this version.

FROM  xxx.xxx.xxx.xxx:5000/backendbase

ADD ./redis.conf /etc/redis/redis.conf
ADD ./mbus.conf /etc/supervisor/conf.d/mbus.conf
ADD ./xxxxxx.tar /opt
RUN chmod -R 655 /opt/xxxxxx/
ADD ./start.sh /opt/start.sh
ADD ./id_rsa /opt/id_rsa

RUN useradd -s /bin/bash -d /home/hub -m hub &&   \
    echo hub:passw0rd | /usr/sbin/chpasswd

EXPOSE 4568

ENTRYPOINT ["sh", "/opt/start.sh"]

The start.sh is a shell script start with "/bin/bash". 

It is hard to reproduce this defect. Because it is always fine when we start the container. And may find this error when we try to restart it after run several days.

**Comment by mikeprice99** [comment] 2016-09-14 10:16
to help debug would also be handy to see the backendbase dockerfile.

**Comment by zjxpsetp** [comment] 2016-09-15 14:46
FROM ubuntu:14.04

ADD ruby-2.1.6 /tmp/ruby-2.1.6
RUN dpkg --configure -a && cd /tmp/ruby-2.1.6 && ./configure --prefix=/usr/local && make && make install && gem install bundler && cd /tmp && rm -rf ruby-2.1.6*
    
ADD ./Gemfile /opt/Gemfile
RUN cd /opt && bundle install

@mikeprice99

**Comment by thaJeztah** [comment] 2021-06-30 17:24
Closing this because of age

**Closed by thaJeztah** 2021-06-30 17:24 UTC
Labels: status/more-info-needed
