### ISSUE TITLE
Unable to locate package docker-ce on debian-stretch

### ISSUE THREAD

**Issue by xnathanh** [moby/moby#35863] opened 2017-12-22 20:08 UTC
someone can help?cant install docker on stretch(debian 9)
```
rock64@rock64:~$ sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
>    $(lsb_release -cs) \
>    stable"

rock64@rock64:~$ sudo apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Hit:2 http://ppa.launchpad.net/ayufan/rock64-ppa/ubuntu bionic InRelease                          
Hit:4 https://download.docker.com/linux/debian stretch InRelease                                  
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease                              
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease                      
Hit:6 http://cdn-fastly.deb.debian.org/debian stretch Release
Reading package lists... Done                      
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:10 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:10 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:10 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:10 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:10 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:10 and /etc/apt/sources.list.d/docker.list:1

rock64@rock64:~$ apt-cache search docker-ce

rock64@rock64:~$ cat /etc/apt/sources.list
deb http://cdn.debian.net/debian/ stretch main contrib non-free
deb-src http://cdn.debian.net/debian/ stretch main contrib non-free
deb http://security.debian.org/ stretch/updates main contrib non-free
deb-src http://security.debian.org/ stretch/updates main contrib non-free
deb http://cdn.debian.net/debian/ stretch-updates main contrib non-free
deb http://ppa.launchpad.net/ayufan/rock64-ppa/ubuntu bionic main
# deb-src http://ppa.launchpad.net/ayufan/rock64-ppa/ubuntu bionic main
deb-src http://cdn.debian.net/debian/ stretch-updates main contrib non-free
# deb-src [arch=amd64] https://download.docker.com/linux/debian stretch stable
deb [arch=amd64] https://download.docker.com/linux/debian stretch stable edge
# deb-src [arch=amd64] https://download.docker.com/linux/debian stretch stable edge

rock64@rock64:~$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

rock64@rock64:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch
```

**Comment by thaJeztah** [comment] 2017-12-24 01:15
packages are there; https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/, but I see some error messages that you defined the repositories both in `/etc/apt/sources.list` and in `/etc/apt/sources.list.d/docker.list`. Not sure if that's the cause, but it may be worth checking both files, and cleaning up what you no longer need.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-24 01:15 UTC

**Comment by xnathanh** [comment] 2017-12-25 00:55
docker is runing on my arm64 system now ,thank you very much
