### ISSUE TITLE
CentOS 7 Fail push to private insecure registry

### ISSUE THREAD

**Issue by zxf969175364** [moby/moby#26184] opened 2016-08-31 04:53 UTC
Hello! I have a problem.
### Output of docker version:

```
Client:
   Version:      1.12.0
   API version:  1.24
   Go version:   go1.6.3
   Git commit:   8eab29e
   Built:        Thu Jul 28 23:54:00 2016
   OS/Arch:      linux/amd64

Server:
   Version:      1.12.0
   API version:  1.24
   Go version:   go1.6.3
   Git commit:   8eab29e
   Built:        Thu Jul 28 23:54:00 2016
   OS/Arch:      linux/amd64
```
### Output of docker info:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
 Images: 1
 Server Version: 1.12.0
 Storage Driver: devicemapper
 Pool Name: docker-253:1-403651-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 67.57 MB
 Data Space Total: 107.4 GB
 Data Space Available: 37.8 GB
 Metadata Space Used: 704.5 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices istrongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host null overlay
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Security Options: seccomp
 Kernel Version: 3.10.0-327.28.3.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.797 GiB
 Name: iZ114wjqanaZ
 ID:      M3XZ:UD47:QJJ5:CTTL:DFSE:LAIB:5MVD:AMY2:2FUR:UT     QW:NDGI:KKKJ
 Docker Root Dir: /var/lib/docker
 Debug Mode (client): false
 Debug Mode (server): false
 Registry: https://index.docker.io/v1/
 Insecure Registries:
  139.196.198.242:6666
  127.0.0.0/8
```
### not to exist:

/etc/sysconfig/docker `OPTIONS='--selinux-enabled=true --insecure-registry=139.196.198.242:6666'`

/etc/default/docker  `DOCKER_OPTS='--selinux-enabled=true --insecure-registry=139.196.198.242:6666'`

/etc/docker/daemon.json `{ "insecure-registries":["139.196.198.242:6666"]`
### Executed locally windows docker:

`docker push 139.196.198.242:6666/mongo`
or
`docker login 139.196.198.242:6666`

return `http: server gave HTTP response to HTTPS client`

**Comment by cpuguy83** [comment] 2016-08-31 13:53
`--insecure-registry` just means that the server's TLS certificate authority is not trusted locally.
Docker will refuse to pass credentials to a non-TLS enabled registry.

**Comment by thaJeztah** [comment] 2016-09-27 00:11
Looks like a duplicate of https://github.com/docker/docker/issues/26781

ping @runcom ?

**Comment by stevvooe** [comment] 2016-10-11 23:01
@thaJeztah This may not be related to #26781.

**Comment by thaJeztah** [comment] 2023-09-16 14:21
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 14:21 UTC
Labels: area/distribution, kind/bug, version/1.12
