### ISSUE TITLE
when i run httpbin on my raspberry pi 3B+ get  err

### ISSUE THREAD

**Issue by 1225358814** [moby/moby#38334] opened 2018-12-08 10:19 UTC
```
Status: Downloaded newer image for kennethreitz/httpbin:latest
standard_init_linux.go:190: exec user process caused "exec format error

root@raspberrypi:/home/pi#  docker run -p 80:80 kennethreitz/httpbin
standard_init_linux.go:190: exec user process caused "exec format error"
```
but on mac os
```
➜  ~ docker run -p 80:80 kennethreitz/httpbin
[2018-12-08 10:06:57 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2018-12-08 10:06:57 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2018-12-08 10:06:57 +0000] [1] [INFO] Using worker: gevent
[2018-12-08 10:06:57 +0000] [10] [INFO] Booting worker with pid: 10
```
why have that stranger bug
 
**Additional environment details (AWS, VirtualBox, physical, etc.):**
 raspberry pi 3B+ latest_system version

**Comment by thaJeztah** [comment] 2018-12-08 15:56
Such errors occur if the image you're trying to run is not built for the architecture you're running it on. In this case, the image (https://hub.docker.com/r/kennethreitz/httpbin/) is only available for amd64, not for arm, and amd64 (x86_64) images won't be able to run on ARM hardware.

Some images, such as the [official busybox image](https://hub.docker.com/_/busybox/) are published as "multi-arch" images, which means that the image can be pulled (and run) on different architectures (for busybox; amd64, arm32v5, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-12-08 15:56 UTC
Labels: kind/question, platform/arm
