### ISSUE TITLE
[EU GDPR] [Feature Request] Provide log rotation option based on time

### ISSUE THREAD

**Issue by ghost** [moby/moby#36909] opened 2018-04-20 02:53 UTC
**Description**

For the EU GDPR and other privacy laws, keeping logs only a limited amount of time (rather than a limited amount of overall data, like docker's `--log-opt max-buffer-size` allows) is essential to avoid fines for unnecessarily keeping sensitive data beyond a reasonable time window required for potential investigation of technical incidents.

Since this will affect a lot of those people who are using the docker engine directly (rather than an orchestrator like kubernetes) to run containers and manage their logs, I propose an option is added to handle this, e.g. `--log-opt max-buffer-days` or something. To handle this, docker would internally need to separate the log by days, so it can throw away not only based on overall log size but also based on age.

Sorry if such an option already exists, I made this ticket because I wasn't able to find it.

Edit: please note detailed "throw away granularity"/small interval, or a super exact throw away time (beyond not exceeding the interval) is really not required for this option to fulfill this use case. So I don't think any advanced detail intervals or making sure it's not thrown away a day *early* in some corner cases is important, and the simplest implementation that doesn't have horrible performance is probably good enough.

**Comment by erikgrinaker** [comment] 2018-04-20 18:31
This is a duplicate of #36909, I've updated the title with `[EU GDPR]`.

**Closed** 2018-04-21 19:17 UTC
Labels: area/logging, kind/feature, kind/duplicate
