### ISSUE TITLE
Docker Container No route to host error

### ISSUE THREAD

**Issue by saffikhan** [moby/moby#36514] opened 2018-03-07 14:36 UTC
Hello,
I have the following docker:

> docker --version
> Docker version 17.12.0-ce, build c97c6d6

And when I do a CURL to an external URL, it fails:

> inside-container$> curl -u username -p https://countries.c1.com/countries/v1/countries
> curl: (7) Failed to connect to 10.10.20.30 port 443: No route to host

> inside-container$> ping countries.c1.com
> PING countries.c1.com (10.10.20.30): 56 data bytes
> 64 bytes from 10.10.20.30: icmp_seq=0 ttl=250 time=2.919 ms
> --- countries.c1.com ping statistics ---
> 1 packets transmitted, 1 packets received, 0% packet loss
> round-trip min/avg/max/stddev = 2.919/2.919/2.919/0.000 ms

So host can be resolved but can't do a curl. When I run the same curl statement from outside of the docker container (e.g docker host or laptop) it works fine!

Any hint pointing me to the right direction would be very much appreciated!

I am not sure what kind of configuration might be relevant. I will provide anything later on if requested.

**Comment by thaJeztah** [comment] 2018-03-07 15:03
Please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is a support question, but feel free to continue the conversation

**Closed by thaJeztah** 2018-03-07 15:03 UTC
