### ISSUE TITLE
docker deamon restart results in out of memory condition in the server (Docker 1.13)

### ISSUE THREAD

**Issue by benramki** [moby/moby#29800] opened 2016-12-30 22:53 UTC
**Description**

Whenever the docker daemon is retarted (systemctl restart docker), it results in a out of memory condition 

Running Docker 1.13.0-rc3

During test, when docker service is restarted, for whatever reasons, it generates udev events for cdrom and the IMPORT action fails resulting in creation of many systemd-udev threads. This hogs the memory.
[root@BaseVM ~]# ps aux --sort -rss | grep systemd
root       553  0.0  0.2  45416 10464 ?        Ss   14:06   0:00 /usr/lib/systemd/systemd-journald
root         1  0.1  0.1  43592  3932 ?        Ss   14:06   0:01 /usr/lib/systemd/systemd --system --deserialize 22
dbus       856  0.0  0.0  26864  2048 ?        Ss   14:06   0:00 /bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root      2615  0.0  0.0  43264  1940 ?        Ss   14:11   0:00 /usr/lib/systemd/systemd-udevd
root       868  0.0  0.0  26400  1724 ?        Ss   14:06   0:00 /usr/lib/systemd/systemd-logind
root      7994  0.0  0.0  43264  1148 ?        S    14:30   0:00 /usr/lib/systemd/systemd-udevd
root      7995  0.0  0.0  43264  1148 ?        S    14:30   0:00 /usr/lib/systemd/systemd-udevd
root      7998  0.0  0.0  43264  1084 ?        S    14:30   0:00 /usr/lib/systemd/systemd-udevd
root      7999  0.0  0.0  43264  1048 ?        S    14:30   0:00 /usr/lib/systemd/systemd-udevd
root      8186  0.0  0.0 112648   976 pts/0    S+   14:30   0:00 grep --color=auto systemd
when run with 4GB memory, system runs into low memory ( due to many systemd-udev threads) resulting is systemd being shutdown along with random processes being killed.

**Steps to reproduce the issue:**
1.  install docker 1.13-rc3 in the system
2.  systemctl restart docker
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-12-30 23:03
Could you add the information about your setup, as requested in the issue template?

- fulll output of `docker version`
- full output of `docker info`
- any relevant (daemon) configuration flags
- what are you running in your containers? How many containers are running etc

**Comment by thaJeztah** [comment] 2016-12-30 23:04
Also note that docker 1.13.0-rc4 was released with various bug fixes

**Comment by benramki** [comment] 2017-01-26 00:04
Hi, We are able to reproduce this with Docker 1.13 as well. Adding more details asap.

**Comment by vilasd** [comment] 2017-01-26 00:07
[root@BaseVM ~]# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

================
[root@BaseVM ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 7.76 GB
 Data Space Total: 65.28 GB
 Data Space Available: 57.52 GB
 Metadata Space Used: 2.564 MB
 Metadata Space Total: 683.7 MB
 Metadata Space Available: 681.1 MB
 Thin Pool Minimum Free Space: 6.527 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: BaseVM
ID: 7J3K:XLJH:X33C:FPXQ:WY44:FORW:Y4OO:HVWG:GEXF:ZLWK:KH65:RCI3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: wilkins
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
======================
This is our container which is running

==============

[root@BaseVM ~]# docker inspect px-enterprise
[
    {
        "Id": "baca6de117364d6a43ad0cb35d736c47c26a329ba618722e7080b3e3473ca76c",
        "Created": "2017-01-25T20:06:04.649919983Z",
        "Path": "/docker-entry-point.sh",
        "Args": [
            "-daemon",
            "--tracefiles",
            "9000"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "transport is closing",
            "StartedAt": "2017-01-25T22:11:26.419020708Z",
            "FinishedAt": "2017-01-25T22:21:34.473321022Z"
        },
        "Image": "sha256:a1f61341f18cc2da7f153ab13b8fafbd043c8ea3923c195626efd0657c4918f6",
        "ResolvConfPath": "/var/lib/docker/containers/baca6de117364d6a43ad0cb35d736c47c26a329ba618722e7080b3e3473ca76c/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/baca6de117364d6a43ad0cb35d736c47c26a329ba618722e7080b3e3473ca76c/hostname",
        "HostsPath": "/var/lib/docker/containers/baca6de117364d6a43ad0cb35d736c47c26a329ba618722e7080b3e3473ca76c/hosts",
        "LogPath": "/var/lib/docker/containers/baca6de117364d6a43ad0cb35d736c47c26a329ba618722e7080b3e3473ca76c/baca6de117364d6a43ad0cb35d736c47c26a329ba618722e7080b3e3473ca76c-json.log",
        "Name": "/px-enterprise",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt:/mnt:shared",
                "/var/cores:/var/cores",
                "/run/docker/plugins:/run/docker/plugins",
                "/dev:/dev",
                "/etc/pwx:/etc/pwx",
                "/var/lib/osd:/var/lib/osd:shared",
                "/usr/src:/usr/src",
                "/opt/pwx/bin:/export_bin:shared",
                "/var/run/docker.sock:/var/run/docker.sock"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "host",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "19",
                "DeviceName": "docker-253:0-203211058-75b5c1e211f055082f5034385718d55ca1a38355d36b38fc830659a3505369e3",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt",
                "Destination": "/mnt",
                "Mode": "shared",
                "RW": true,
                "Propagation": "shared"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/osd",
                "Destination": "/var/lib/osd",
                "Mode": "shared",
                "RW": true,
                "Propagation": "shared"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/usr/src",
                "Destination": "/usr/src",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/cores",
                "Destination": "/var/cores",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/dev",
                "Destination": "/dev",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/etc/pwx",
                "Destination": "/etc/pwx",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/opt/pwx/bin",
                "Destination": "/export_bin",
                "Mode": "shared",
                "RW": true,
                "Propagation": "shared"
            },
            {
                "Type": "bind",
                "Source": "/run/docker/plugins",
                "Destination": "/run/docker/plugins",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "BaseVM",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOTRACEBACK=crash",
                "GOMAXPROCS=64",
                "PXMOD_SOURCE=/home/px-fuse",
                "PXMOD_VERSION=2"
            ],
            "Cmd": [
                "-daemon",
                "--tracefiles",
                "9000"
            ],
            "Image": "portworx/px-base-enterprise:dev",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/docker-entry-point.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "68b3d5e65d2c4fd346f0eddf9aa33469b4e512ef931655ece0d2bb0850995323",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "6e1cb04dc4416fc4f0ae6e37bd865f35eaaa1b9ece55c1f1944538bc38fedd3d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
======================================
This is the only container running at the point when docker was restarted. And system-udevd hogs the memory

Here is the journalctl -xl | grep docker log file

[docker.txt](https://github.com/docker/docker/files/731244/docker.txt)

**Comment by vilasd** [comment] 2017-01-26 00:25
[dmesg.txt](https://github.com/docker/docker/files/731268/dmesg.txt)
Dmesg log from system

**Comment by thaJeztah** [comment] 2017-01-26 01:46
Not sure, I do notice that the minimum requirements for that image is 4GB (16GB recommended); http://docs.portworx.com/get-started-px-enterprise.html, and a lot of failed attempts to reach the plugin. The killed processes seem to all be related to mount, indeed, 
Did this same setup work correctly on docker 1.12?

/cc @anusha-ragunathan for (legacy) plugins

**Comment by vilasd** [comment] 2017-01-26 06:22
Same setup work correctly with docker 1.12.

**Comment by anusha-ragunathan** [comment] 2017-01-26 17:32
Feature to restore volumes on daemon restart was newly added in 1.13. Daemon log shows error in restoring volumes, because the plugin container (px-enterprise) has not been started yet. However, this shouldnt cause OOM. I'll look more.

**Comment by anusha-ragunathan** [comment] 2017-01-26 18:32
Looks like there were 7 volumes created using the `px-enterprise` containerized plugin. When the daemon was restarted, daemon tried to restore the volumes, but failed because the plugin was not running. This is expected and harmless.

Note that `px-enterprise` failed to start as seen in daemon logs:

bin/docker inspect -f {{.State.Running}} px-enterprise
Jan 25 14:57:47 BaseVM dockerd[23430]: time="2017-01-25T14:57:47.007951337-08:00" level=error msg="Error setting up exec command in container px-enterprise: Container baca6de117364d6a43ad0cb35d736c47c26a329ba618722e7080b3e3473ca76c is not running

As @thaJeztah pointed out, the host memory is 3.703 GiB and the container minimum recommended is 4G, its natural that OOM is killing random processes.

Does the issue happen all the time? If yes, it would be good to avoid kernel overcommitment and repeat the experiment. To avoid memory overcommittment, set this in /etc/sysctl.conf and restart your VM:
vm.overcommit_memory = 2
vm.overcommit_ratio = 80

Another option is to repeat experiment on a VM with 16G RAM.

https://www.kernel.org/doc/Documentation/sysctl/vm.txt

**Comment by cpuguy83** [comment] 2017-01-27 00:19
Note that f2d384fca6fa08da13fdc01c7991e8e35b081198 fixes a deadlock here during volume restore, effectively preventing the daemon from booting up (in 1.13) in some circumstances.

This should be fixed in 1.13.1

**Comment by anusha-ragunathan** [comment] 2017-01-27 16:08
In this issue, the daemon boots fine, the container doesnt due to memory limits.

**Comment by anusha-ragunathan** [comment] 2017-01-27 16:31
Did the suggested workaround (avoiding memory overcommit) fix the issue?

**Comment by thaJeztah** [comment] 2017-02-14 00:08
ping @benramki did @anusha-ragunathan's suggestion help? Are you still able to reproduce this issue on docker 1.13.1 (which was released)

**Closed** 2021-06-30 18:55 UTC
Labels: status/more-info-needed, version/1.13
