### ISSUE TITLE
Multi-stage builds: target name can't be uppercase

### ISSUE THREAD

**Issue by douglasmiranda** [moby/moby#36956] opened 2018-04-26 20:56 UTC
**Description**

When using multi-stage builds, I can name a stage with an uppercase string `BUILDER`, for example.

**Steps to reproduce the issue:**

Dockerfile

```Dockerfile
FROM alpine AS BUILDER

RUN touch file.txt

FROM alpine AS DEV

CMD ["ls"]
```

Let's build this image stopping at `DEV` stage. [more about stopping at a specific stage](https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage)

```
$ docker build --target=DEV -t devimagex .
Sending build context to Docker daemon  2.048kB
Error response from daemon: failed to reach build target DEV in Dockerfile
```

But even **without** rename the target to lowercase in the Dockerfile, I can achieve the desired behavior by building setting the `--target` as lowercase `dev`.

```
docker build --target=dev -t devimagex .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM alpine AS BUILDER
 ---> 3fd9065eaf02
Step 2/4 : RUN touch file.txt
 ---> Using cache
 ---> c3cb5e472065
Step 3/4 : FROM alpine AS DEV
 ---> 3fd9065eaf02
Step 4/4 : CMD ["ls"]
 ---> Using cache
 ---> fd71f6b3c81c
Successfully built fd71f6b3c81c
Successfully tagged devimagex:latest
```

**More info:**

* Dockerfile instructions are not case-sensitive, but it's a convention to use them as UPPERCASE. A target name it's not an instruction so I should use lowercase.
* Since a target name can be used as an image to subsequent stages, it's another reason to use them as lowercase since image names are required to be lowercase. (although target names are just a reference to the id of that temporary stage image, right?)

BUT, the thing is, we CAN name a stage with an uppercase string, and it works inside the Dockerfile, but when used with `docker build --target=` or even in Docker Compose, I must refer to them as lowercase even though it's uppercase in the Dockerfile.

So, maybe a solution better than put in the docs more info about this, is to throw a better error message than: `Error response from daemon: failed to reach build target DEV in Dockerfile`

Since enforcing this to change on Dockerfiles now could break a lot, maybe enforce when using  `docker build --target`, something like: `Error response from daemon: failed to reach build target DEV in Dockerfile. Target names must be lowercase`.

Or, if that's not a big of a deal, just allow uppercase on Docker command line and Docker Compose.

```
docker build --target=DEV ...
```

I hope I didn't miss something.

Docs related:
* https://docs.docker.com/engine/reference/builder/#from
* https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage
* https://docs.docker.com/compose/compose-file/#target

---

**Output of `docker version`:**
<details>
  <summary>Click to expand</summary>

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```
</details>

---

**Output of `docker info`:**
<details>
  <summary>Click to expand</summary>

```
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 207
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: EUQE:3BXM:4ESD:MFIT:QAA6:DKAJ:2JQU:F5JM:GBK6:ZXAR:NZBI:WPUK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 57
 System Time: 2018-04-26T20:18:21.1274233Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
</details>

**Comment by thaJeztah** [comment] 2018-04-26 21:16
Thanks for reporting!

ping @tonistiigi

**Comment by arm64b** [comment] 2018-04-27 10:36
I also reproduce this on AArch64 platform, after investigation, I found the root cause is, when the code parses the stage target name, it will convert the stage name into lower case order to check the sanity. Fixing should be effortless, we just need to reserve the original stage name. I can submit a PR to address this issue...

**Comment by arm64b** [comment] 2018-05-02 11:38
@douglasmiranda , the fix has been merged, you can test it with the latest code to see if the issue is disappeared 💯

**Comment by thaJeztah** [comment] 2018-05-02 11:41
closing as this should be resolved through https://github.com/moby/moby/issues/36960 thanks!

**Closed by thaJeztah** 2018-05-02 11:41 UTC
Labels: area/builder, kind/bug, platform/desktop
