### ISSUE TITLE
How to restart with docker-compose

### ISSUE THREAD

**Issue by ORESoftware** [moby/moby#40003] opened 2019-09-27 21:02 UTC
Not sure if this is the right place to file a ticket for docker-compose.
But I have this issue with restarting docker containers upon reboot of an AWS EC2 instance:

https://stackoverflow.com/questions/58141265/how-to-auto-restart-a-docker-compose-cluster-when-ec2-instance-reboots

the restart: always setting doesn't seem to do anything with docker-compose.yml. Whereas this works:

```
docker run -d -p 27017:27017 \
    --restart unless-stopped \
    'mongo:4.0' 
```

**Comment by tao12345666333** [comment] 2019-09-29 08:45
I have already replied to your question on stackoverflow. :)

**Comment by thaJeztah** [comment] 2019-09-30 14:44
Thanks @tao12345666333 !

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, and I see the question is answered on StackOverflow, but feel free to continue the conversation

**Closed by thaJeztah** 2019-09-30 14:44 UTC
Labels: kind/question
