### ISSUE TITLE
docker rm -f <container> fails if there are two containers mounting the same directory from the host filesystem.

### ISSUE THREAD

**Issue by anpartha** [moby/moby#35673] opened 2017-12-01 19:53 UTC
**Description**
If there are two containers that mount the same directory. docker rm -f <container> fails when you try and delete the container that was created first. This is when we use devicemapper as the docker storage.

```
ps -aef | grep docker
root     27607     1  9 19:11 ?        00:00:12 /usr/bin/dockerd --storage-driver devicemapper --raw-logs
```

Please note that this was not an issue with an earlier version of docker 17.03 or 17.05

```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              14.04               d6ed29ffda6b        9 days ago          221MB
```
**Steps to reproduce the issue:**
1. Create two containers of the standard ubuntu 14.04 image mounting / as /hostroot

```
docker run -d -t -v /:/hostroot ubuntu:14.04 /bin/bash
ad34fc70cef633645240a782e276d7fb0cc5691abd2eeb9e20cf3886995fbdb0

docker run -d -t -v /:/hostroot ubuntu:14.04 /bin/bash
a5e4ce128483382c882953a12a54e2bc156b09e7fd0cc49a21342bb8dec7b1b2
```

2.Remove the first container

```
docker rm -f ad
Error response from daemon: driver "devicemapper" failed to remove root filesystem for ad34fc70cef633645240a782e276d7fb0cc5691abd2eeb9e20cf3886995fbdb0: failed to remove device 089022c4968c61a02d8bd0b9c4a8f5224bcb5c6f433f177b5074e1ec92976dec: Device is Busy
```

**Describe the results you received:**
Unable to delete the container that was created first.

**Describe the results you expected:**
Expect that the container can be deleted. This used to work with 17.03 and 17.05 versions.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-252:0-644769-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 578.4MB
 Data Space Total: 107.4GB
 Data Space Available: 27.93GB
 Metadata Space Used: 1.073MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: anpartha-1404
ID: 3DAZ:EGCG:M3LY:VHGS:GFA3:YW3Y:HA7Z:YEMT:AVWE:IHD3:HS46:QARS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld0** [comment] 2017-12-03 12:02
cc @cpuguy83 @thaJeztah

**Comment by thaJeztah** [comment] 2017-12-04 04:34
Looks like a duplicate of https://github.com/moby/moby/issues/27381

The problem likely is due to the first container's root mount leaking into the second container's mount, because both bind-mount `/` into the container (so, effectively the first container's mount, which is somewhere in `/var/lib/docker/...` is now also accessible inside container two, at `/hostroot/var/lib/docker/...`.

Now, container1's root filesystem cannot be removed, because container2 still uses container1's mount, so docker is not able to remove it.

The discussion on https://github.com/moby/moby/issues/27381 provides some ways to handle this situation, but some of those may have to be handled different, because Ubuntu 14.04 does not use systemd as an init system, so does not allow you to set the `MountFlags` option in the systemd unit file.

Let me close this issue because this is a duplicate of https://github.com/moby/moby/issues/27381, but feel free to comment after I closed

**Closed by thaJeztah** 2017-12-04 04:34 UTC
Labels: version/17.09

**Comment by anpartha** [comment] 2017-12-04 20:54
I was able to recreate this issue in RHEL 7.3. Changed the systemd service file with MountFlags=slave and it still seems to have the same issue. Could you pls. take a look?

```
[root@localhost ~]# cat /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service
Wants=network-online.target

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
MountFlags=slave
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target
[root@localhost ~]# systemctl daemon-reload
[root@localhost ~]# systemctl start docker
[root@localhost ~]# docker run -d -t -v /:/hostroot ubuntu:14.04 /bin/bash
397a78eab640319f87120d93d9d226721150c9295487b5a2a68f8d0d38a65c6e
[root@localhost ~]# docker run -d -t -v /:/hostroot ubuntu:14.04 /bin/bash
73bba2066f5f97d9e54dcea5d4f79792b062bbd343ecaa57e3093aabf48cfe85
[root@localhost ~]# docker rm -f 39
Error response from daemon: driver "overlay" failed to remove root filesystem for 397a78eab640319f87120d93d9d226721150c9295487b5a2a68f8d0d38a65c6e: remove /var/lib/docker/overlay/611039cb965c332d5e8a52571ba1e36fb782226c459757f87834ec4032c99570/merged: device or resource busy
```

**Comment by kolyshkin** [comment] 2017-12-05 02:14
@anpartha in RHEL+dm case, please upgrade your kernel to a one from RHEL 7.4 (`3.10.0-693.`..) and make sure that after starting docker `cat /proc/sys/fs/may_detach_mounts` shows `1`. If it doesn't, you can set it to 1 manually (either with `echo` or, if you want it to persist after a reboot, by edititng `/etc/sysctl.conf` or a file in `/etc/sysctl.conf.d/`. Newer versions of Docker should set this to 1 automatically on daemon startup.

Same appears true for RHEL+overlay case.

I will see it later what happens on Ubuntu with devmapper.

**Comment by anpartha** [comment] 2017-12-07 22:57
@kolyshkin Many of our customers are on RHEL 7.2 and 7.3. We will not be able to convince them to move to RHEL 7.4. Is there a workaround for the other RHEL versions that we can employ?

**Comment by thaJeztah** [comment] 2017-12-07 23:03
Afaik, it's a kernel issue, and fixed in modern kernels; RHEL back ported it to their 3.10.x kernels for RHEL 7.4, but made the fix optional (through the `may_detach_mounts`) for backward compatibility.

**Comment by kolyshkin** [comment] 2017-12-08 21:35
@anpartha no known workaround other than to upgrade to a kernel from RHEL 7.4. Note you don't have to upgrade the whole system, just the kernel from 7.4 is sufficient.
