### ISSUE TITLE
Container stops after logs are piped to failing command

### ISSUE THREAD

**Issue by LelandSindt** [moby/moby#31373] opened 2017-02-27 04:05 UTC
**Description**

When `docker logs <container>` is piped to a command that fails the container hangs, and docker has to be restarted to recover. 

**Steps to reproduce the issue:**
```
$ docker run -d --name=failure alpine /bin/sh -c "while true; do date; done"
642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
59247
```
--- wait ?30+ seconds?
```
$ docker logs failure --tail 10
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017

$ docker logs failure |grep -10
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

$ docker logs failure --tail 10
```
....nothing.... 
ctrl+c
```
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
165360
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
165360

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
642305b0dc0        alpine              "/bin/sh -c 'while..."   52 seconds ago      Up 51 seconds                           failure

$ docker stop failure
failure

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
642305b0dc0        alpine              "/bin/sh -c 'while..."   About a minute ago   Up About a minute                       failure

$ systemctl restart docker
$ docker ps --all |grep failure
642305b0dc0        alpine                  "/bin/sh -c 'while..."    2 minutes ago       Exited (137) 22 seconds ago                                    failure
```

**Describe the results you received:**
When `docker logs <container>` is piped "|" to a command that fails... the container fails and the docker service must be restarted.

**Describe the results you expected:**
The command should fail, but the container should not be effected. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 19
 Running: 1
 Paused: 0
 Stopped: 18
Images: 39
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.678 GiB
Name: x1
ID: YY5M:Q3IW:GK7S:C3F2:JGQN:UZ7F:BP2F:MC4T:5U7J:6QAT:VVQC:DCCF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04, Physical Host, 8GB Ram, 4CPU

**Comment by catinthesky** [comment] 2017-02-27 12:08
From code checking, it seems the problem was caused by introducing this line in file (daemon/logger/jsonfilelog/read.go):
    51   // lock so the read stream doesn't get corrupted due to rotations or other log data written while we read
 52   // This will block writes!!!
 53   l.mu.Lock()

Which would make lock can not be released if the docker client input parameter having error as suggested above or interrupt the log's output,  this would block the code going forward next time when even correct log command issued.

**Comment by thaJeztah** [comment] 2017-02-27 12:12
ping @cpuguy83 ptal

**Comment by cpuguy83** [comment] 2017-02-28 03:33
Hmm, yeah looks bad.
Would you like to open a PR to remove the lock, or I guess unlock once we've opened all the files we need.

**Comment by catinthesky** [comment] 2017-02-28 10:06
Checked the lasted code in the master branch, this problem already has been fixed by this section of code (daemon/logger/jsonfilelog/read.go):
140     select {
141     case <-logWatcher.WatchClose():
142       return
143     case logWatcher.Msg <- msg:
144     }
So using the above to replace below statement in the same file( daemon/logger/jsonfilelog/read.go) in tag v1.13.1 would be OK:
141     logWatcher.Msg <- msg

**Comment by cpuguy83** [comment] 2017-02-28 14:06
Ah, yes that's right.

However I still think this is a problem as it seems like slow log readers can effectively block the writer which is not ideal.

**Comment by catinthesky** [comment] 2017-02-28 23:13
Though from my checking it seems displaying logs (while logReader obtained lock) does not block container writing into it's log file (say: containerId-json.log) which using different locks, also checked, when showing a little long logs, 2 "docker logs" can show at the console (not blocking from client's output perspective).   not sure, if there were some other problematic scenarios for such a lock.
maybe I'm wrong,  it seems the lock of no much use, how about removing it with a PR.

**Comment by thaJeztah** [comment] 2017-03-09 11:58
ping @cpuguy83 are more fixes needed on master? And do we need a fix in the 17.03.x branch?

**Comment by cpuguy83** [comment] 2017-03-09 13:51
Locked on writes here: https://github.com/docker/docker/blob/master/daemon/logger/jsonfilelog/jsonfilelog.go#L92

Locked on reads here: https://github.com/docker/docker/blob/master/daemon/logger/jsonfilelog/read.go#L53

Should probably unlock here: https://github.com/docker/docker/blob/master/daemon/logger/jsonfilelog/read.go#L78

**Comment by catinthesky** [comment] 2017-03-10 07:41
How about a PR for this by me ?

**Comment by catinthesky** [comment] 2017-03-10 07:50
How about I create a PR for this ?

**Comment by thaJeztah** [comment] 2017-03-22 12:39
@catinthesky looks like nobody started working on this, so if you're still interested, yes, please 👍

**Comment by catinthesky** [comment] 2017-03-23 01:17
#dibs

**Comment by catinthesky** [comment] 2017-03-24 07:15
Code committed, not very clear of why jenkins CI failed which should  irrelevant of this commit.

**Closed** 2017-07-06 01:21 UTC
Labels: area/logging, kind/bug, version/1.13
