### ISSUE TITLE
docker to many open files error 

### ISSUE THREAD

**Issue by kinglion811** [moby/moby#40231] opened 2019-11-20 04:43 UTC
```
dockerd: time="2019-11-20T00:22:49.778215372+08:00" level=error msg="invalid image access: \"sha256:0317ca374854b710e0e18eae5f0342c6ca5f3698a56838943837d47dc5c        bd684\", error: \"failed to get digest sha256:0317ca374854b710e0e18eae5f0342c6ca5f3698a56838943837d47dc5cbd684: open /media/disk1/docker/image/overlay/imagedb/content/sha256/0317ca37485        4b710e0e18eae5f0342c6ca5f3698a56838943837d47dc5cbd684: too many open files\"
```

```
docker info 
Containers: 13
 Running: 7
 Paused: 0
 Stopped: 6
Images: 216
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340-dirty (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-1.0.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.6GiB
Name: bjlt-hg13.sy
ID: MAHE:DNSQ:NAT2:K2ZX:U5UV:AGFH:GRFK:KREJ:PGCF:DT3O:VA62:QHWX
Docker Root Dir: /media/disk1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
```

**Comment by kinglion811** [comment] 2019-11-21 02:32
@thaJeztah

**Comment by thaJeztah** [comment] 2019-11-21 09:13
Thanks for reporting, but unfortunately there's not a lot of information to go on.

I suspect this could be related to the use of the legacy `overlay` (not `overlay2`) storage driver being used. The legacy overlay storage driver has known issues with excessive inode use, a problem that the `overlay2` does not have;

From the docs; https://docs.docker.com/storage/storagedriver/overlayfs-driver/#overlayfs-and-docker-performance

> Inode limits. Use of the legacy overlay storage driver can cause excessive inode consumption. This is especially true in the presence of a large number of images and containers on the Docker host. The only way to increase the number of inodes available to a filesystem is to reformat it. To avoid running into this issue, it is highly recommended that you use overlay2 if at all possible.


However, it looks like you're running

- a very old version of CentOS 7 (either a very old 3.10.x kernel version or a custom build of the 3.10 kernel, which is not supported)
- a version of Docker that reached EOL last year (Docker 18.06 is no longer supported or maintained).
- you're running a non-standard version of runc, which was built with modifications (the `-dirty` at the end of the commit: `69663f0bd4b60df09991c08812a60108003fa340-dirty` indicates runc was built from a modified source)


I recommend upgrading to a current CentOS 7 version (and kernel), upgrading Docker to the current release (19.03.x), and use the `overlay2` storage driver instead.

Without steps to reproduce the problem, there's not much we can do here, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2019-11-21 09:13 UTC
