### ISSUE TITLE
feature request min/max replicas

### ISSUE THREAD

**Issue by omerh** [moby/moby#32054] opened 2017-03-23 21:12 UTC
Add the possibility to have a 
`docker service create/update --min-replicas 1 --max-replicas 5` 
upon creating or updating a service, based on cpu limit or service response latency etc...

**Comment by anonymuse** [comment] 2017-03-24 17:26
Hi @omerh. This reminds me of autoscaling groups. Can you provide some more color around how' you'd use this feature, or why you'd think it was useful? It would be good to have that context.

**Comment by omerh** [comment] 2017-03-26 07:55
I am planning to use couple of autoscaling groups in AWS.
mostly based on instance CPU or ELB latency based.
As for now, I am planning to push a scaling event to lambda to do rebalance to the cluster. (I Think that it be nice that Docker swarm manager would rebalance upon node count change)

The only thing missing is how can I expand service replica, I feel that setting replica limits is a great feature for autoscaling.

**Comment by adityacs** [comment] 2017-04-05 18:45
+1.
Autoscaling would be a great feature. Based on average cpu utilization over last 5mins, memory utilization over last 5mins and network traffic. The target utilization can be defined alongside "docker service create". Based on this decide the replicas and scale the containers.

**Comment by omerh** [comment] 2017-04-06 09:35
The solution we do now is using AWS Autoscale groups.
Each different group adds Docker engine lable upon adding a new instance and the docker service create runs with global mode with constraint.

```
docker service create --name global_autoscale --mode global --constraint 'engine.labels.type == scale' nginx
``` 

But it will be better to have this kind of feature using swarm manager using the resource manager

**Comment by adityacs** [comment] 2017-04-06 15:56
yeah, docker already has the resource usage metrics from "stats". Just an integration with scaling should solve this problem.

**Comment by mqasim1983** [comment] 2017-04-12 21:20
+1

**Comment by omerh** [comment] 2017-10-22 18:51
Any progress here?

**Comment by boreys** [comment] 2017-11-05 18:22
+1

**Comment by thaJeztah** [comment] 2017-11-15 10:51
This looks to be a duplicate of https://github.com/moby/moby/issues/26259 ?

**Comment by omerh** [comment] 2017-12-24 14:15
@thaJeztah is this being discussed?

**Comment by thaJeztah** [comment] 2017-12-24 14:34
I don't think this is currently being worked on; this is not an easy feature to implement, and would require a more extended design, and discussion.

Given that this is very closely related to (or duplicate of) https://github.com/moby/moby/issues/26259, which has more discussion, I'll close this one in favor of https://github.com/moby/moby/issues/26259, to prevent the discussion from diverging

**Closed by thaJeztah** 2017-12-24 14:34 UTC
Labels: area/swarm, kind/feature
