### ISSUE TITLE
HPE Docker Plugin: plugin socket file created in wrong location instead of /run/docker/plugins/<plugin>.sock

### ISSUE THREAD

**Issue by wdurairaj** [moby/moby#33379] opened 2017-05-24 17:01 UTC
**Description**

HPE Docker volume plugin image is created using Dockerfile located in https://github.com/hpe-storage/python-hpedockerplugin 

Due to the incorrect socket file location (after start of the plugin), the volume operations like
`$ docker volume ls` fails

This problem is not recreatable with containerized version of plugin generated using the docker-compose.yml as given in this template.. https://github.com/hpe-storage/python-hpedockerplugin/blob/master/quick-start/docker-compose.yml.example

- To create the image of the legacy plugin
- invoke ./containerize.sh
- Update the image:  in docker-compose.yml with the image:tag generated in previous step.
- run docker-compose up.. the plugin path location is right.

**Steps to reproduce the issue:**
[steps to reproduce.txt](https://github.com/moby/moby/files/1026350/steps.to.reproduce.txt)

config.json which is used for packaging the plugin is 
[config.json.txt](https://github.com/moby/moby/files/1026334/config.json.txt)

**Describe the results you received:**
Plugin socket file is present in /run/docker/plugins/<plugin_id>/  folder 

**Describe the results you expected:**
Plugin socket file is expected in /run/docker/plugins/  folder 

**Additional information you deem important (e.g. issue happens only occasionally):**
I need to create a symbolic link to make the `$ docker volume ls ` operations command to function properly.
```
Eg.

root@csimbe01b6:/run/docker/plugins/hpe# ln -s ../132b37a2c9e02d53e06b2874f10228540853155292570ff939ba131bc53e53ad/hpe.sock hpe.sock
root@csimbe01b6:/run/docker/plugins/hpe# docker volume ls
DRIVER                          VOLUME NAME
sandanar/hpedockerplugin:test   test_vol1


Without the symbolic link it displays these kind of error messages in /var/log/syslog

e02d53e06b2874f10228540853155292570ff939ba131bc53e53ad
May 24 10:42:41 csimbe01b6 dockerd[18382]: time="2017-05-24T10:42:41.064790802-06:00" level=warning msg="Volume driver sandanar/hpedockerplugin:test returned an error while trying to query its capabilities, using default capabilties: VolumeDriver.Capabilities: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"
May 24 10:42:42 csimbe01b6 dockerd[18382]: time="2017-05-24T10:42:42.054578352-06:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/hpe/hpe.sock/VolumeDriver.List: Post http://%2Frun%2Fdocker%2Fplugins%2Fhpe%2Fhpe.sock/VolumeDriver.List: dial unix /run/docker/plugins/hpe/hpe.sock: connect: no such file or directory, retrying in 2s"
May 24 10:42:44 csimbe01b6 dockerd[18382]: time="2017-05-24T10:42:44.055154335-06:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/hpe/hpe.sock/VolumeDriver.List: Post http://%2Frun%2Fdocker%2Fplugins%2Fhpe%2Fhpe.sock/VolumeDriver.List: dial unix /run/docker/plugins/hpe/hpe.sock: connect: no such file or directory, retrying in 4s"
```
Inside the plugin container the iscsid utility fails to start 

```
docker@csimbe01b6:~/python-hpedockerplugin/hpedockerplugin$ sudo docker-runc exec -t 132b37a2c9e02d53e06b2874f10228540853155292570ff939ba131bc53e53ad /bin/sh
/python-hpedockerplugin # /usr/sbin/iscsid start
/python-hpedockerplugin # ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c ./plugin-start
    7 root       0:00 {plugin-start} /bin/sh ./plugin-start
   19 root       0:03 {twistd} /usr/bin/python /usr/bin/twistd --nodaemon hpe_plugin_service
   36 root       0:00 {privsep-helper} /usr/bin/python /usr/bin/privsep-helper --config-file /etc/hpedockerplugin/hpe.conf --privsep_context
   83 root       0:00 /bin/sh
   92 root       0:00 ps -ef

```

**Output of `docker version`:**

```
root@csimbe01b6:/run/docker/plugins/hpe# docker version
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 20:06:11 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 20:06:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@csimbe01b6:/run/docker/plugins/hpe# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

```

**Output of `docker info`:**

```
root@csimbe01b6:/run/docker/plugins/hpe# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.1-ee-3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local hpe
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 94.38 GiB
Name: csimbe01b6
ID: CGOA:WX75:NIJP:ENGH:KEHM:YBT2:XX3Z:EY76:W6PZ:OU6D:E6MD:MOWM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical node

**Comment by cpuguy83** [comment] 2017-05-24 17:22
```
    {
      "source": "/run/docker/plugins",
      "destination": "/run/docker/plugins",
      "type": "bind",
      "options": [
        "rbind","rw"
      ]
    },
```

This, I suspect, is the cause.
You do not need to bind-mount the host `/run/docker/plugins` dir.

**Comment by wdurairaj** [comment] 2017-05-24 18:45
Thanks for that input. I will try the same. 

Do you have any inputs on the iscsid startup issue inside the plugin container ?

**Comment by cpuguy83** [comment] 2017-05-24 20:17
I don't have any insight on iscsid, but maybe https://github.com/blockbridge/blockbridge-demo/tree/master/iscsid could help?

Are you getting any errors?

**Comment by cpuguy83** [comment] 2017-05-25 01:06
Closing since this doesn't look like a Docker issue, but feel free to continue the discussion.
Thanks!

**Closed by cpuguy83** 2017-05-25 01:06 UTC
Labels: area/builder, version/17.03

**Comment by wdurairaj** [comment] 2017-05-25 16:35
Removing that volume binding did'nt solve the problem yet.

```
 {
      "source": "/run/docker/plugins",
      "destination": "/run/docker/plugins",
      "type": "bind",
      "options": [
        "rbind","rw"
      ]
    },

```

**Comment by cpuguy83** [comment] 2017-05-25 16:55
@wdurairaj What do you mean?
`/run/docker/plugins` should not be bound in the container at all.

**Comment by wdurairaj** [comment] 2017-05-25 18:43
@cpuguy83 . Let me clarify.. i removed the /run/docker/plugins completely from the config.json, created plugin and redeployed.. Still i saw the hpe.sock file is formed under /run/docker/plugins/<plugin_id> and not as expected in /run/docker/plugins/hpe.sock

**Comment by wdurairaj** [comment] 2017-05-26 17:20
i have re-imaged the docker host. After this i'm not seeing the socket issue.

**Comment by rajulm** [comment] 2019-07-22 20:04
Hey wdurairaj@, I am facing the same issue. I am trying to create the docker plugin in Java language. I am seeing the same issue where it is trying to look for the .sock file in ```/run/docker/plugins/<plugin-id>.<plugin>.sock``` rather than the expected location ```/run/docker/plugins/<plugin>.sock```. Did you make any changes in the config.json file? Did you start seeing the .sock file in location ```/run/docker/plugins/<plugin-id>```? Or did it started looking at the location ```/run/docker/plugins`` ` location?
