### ISSUE TITLE
'exec -i containerid sh -c read a' is flaky on Windows under docker test

### ISSUE THREAD

**Issue by jhowardmsft** [moby/moby#15274] opened 2015-08-03 22:44 UTC
See PR https://github.com/docker/docker/pull/14697. One of the reasons this test was failing so many times was that when running under docker test, the exec'd process exits almost immediately. My best guess at this time is that the daemon sees something on stdin, so it exits normally (debug spew on the daemon seems to indicate this is the case). 

While TestInspectExecID has been modified to workaround this issue, there probably should still be some investigation into why the specific command above fails when under docker test, and only from Windows targeting a Linux daemon. And probably a new explicit test written.

**Comment by LK4D4** [comment] 2016-09-13 17:50
@jhowardmsft still flaky I believe?

**Comment by jhowardmsft** [comment] 2016-09-13 18:01
Yeah I haven't done anything to look further

**Comment by thaJeztah** [comment] 2019-09-03 15:51
test was renamed to `TestExecInspectID`  in https://github.com/moby/moby/commit/a9379b4af227f1966b71ee255fc8bcf272ffe43c

**Comment by thaJeztah** [comment] 2019-09-03 15:52
Looks like this is a duplicate of https://github.com/moby/moby/issues/21034, which was closed (and I can't see of recent reports of this issue, so closing this one for now)

**Closed by thaJeztah** 2019-09-03 15:52 UTC
Labels: area/runtime, area/testing, platform/windows
