### ISSUE TITLE
[Warning] One or more build-args [http_proxy] were not consumed

### ISSUE THREAD

**Issue by mpalmer** [moby/moby#33950] opened 2017-07-04 23:28 UTC
**Description**

Running `docker build --build-arg=http_proxy=<something> .` with a `Dockerfile` that does not contain `ARG http_proxy` emits the above warning.

**Steps to reproduce the issue:**

Run `docker build --build-arg=http_proxy=<something> .` with a `Dockerfile` that does not contain `ARG http_proxy`.

**Describe the results you received:**

The line

    [Warning] One or more build-args [http_proxy] were not consumed

was emitted as part of the build process.

**Describe the results you expected:**

The line

    [Warning] One or more build-args [http_proxy] were not consumed

not to be emitted as part of the build process.

**Additional information you deem important (e.g. issue happens only occasionally):**

The documentation for the `ARG` instruction at https://docs.docker.com/engine/reference/builder/#arg says:

> Docker has a set of predefined ARG variables that you can use without a corresponding ARG instruction in the Dockerfile.

> * HTTP_PROXY
> * http_proxy
> * HTTPS_PROXY
> * https_proxy
> * FTP_PROXY
> * ftp_proxy
> * NO_PROXY
> * no_proxy

>To use these, simply pass them on the command line using the flag:

>     --build-arg <varname>=<value>

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 319
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.0-0.bpo.2-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.36GiB
Name: mistress
ID: XCA5:PLPV:KBPE:SY63:O254:RZ3S:4UQS:C73M:KYHC:ASCI:25HL:GOQP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://127.0.0.1:3128/
Username: womble
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine.

**Comment by thaJeztah** [comment] 2017-07-04 23:34
This is a duplicate of https://github.com/moby/moby/issues/33067, and is fixed through https://github.com/moby/moby/pull/33114, which is part of Docker 17.06 - can you try upgrading to docker 17.06?

**Comment by thaJeztah** [comment] 2017-07-04 23:35
Closing because this should be fixed, but let me know if you're still able to reproduce with 17.06, and I'll reopen

**Closed by thaJeztah** 2017-07-04 23:35 UTC
Labels: area/builder, version/17.05

**Comment by mpalmer** [comment] 2017-07-05 00:32
Sorry I didn't find the dupe, didn't search hard enough.

> can you try upgrading to docker 17.06?

Apparently not:

```
$ apt-cache policy docker-engine
docker-engine:
  Installed: 17.05.0~ce-0~debian-stretch
  Candidate: 17.05.0~ce-0~debian-stretch
  Version table:                                  
 *** 17.05.0~ce-0~debian-stretch 500              
        500 http://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
        100 /var/lib/dpkg/status                  
     17.04.0~ce-0~debian-stretch 500              
        500 http://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
(etc etc etc)
```

I'll live with the warning for now, I guess.  Thank `$DEITY` it got downgraded from a fatal error a while ago...

**Comment by thaJeztah** [comment] 2017-07-05 03:20
@mpalmer you need to use the new repositories; the repository apt.dockerproject.org will not get new packages; download.docker.com will be the repository from now on.

https://docs.docker.com/engine/installation/linux/docker-ce/debian/
