### ISSUE TITLE
query a docker registry (hub.docker.com) using go docker client without docker daemon dependency

### ISSUE THREAD

**Issue by amokkara** [moby/moby#43069] opened 2021-12-07 05:05 UTC
Is it possible to run this client with out a docker daemon running? i want to run this program in a docker container. But it wont be able to access docker daemon from  a container. I just want to query a docker registry (ex: hub.docker.com) and check if image exists
how to do this without docker deamon running

@samuelkarp 
@AkihiroSuda 
@thaJeztah 

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2021-12-07 09:14
The API client in this repository is meant to interact with the Docker API (which is provided by the docker daemon), so it will expect the docker daemon to be running / available. That said, for example the `docker manifest` commands work client side, so you could (to some extend) use those, e.g. `docker manifest inspect` (but it may not be the fastest solution, as it's collecting info for all variants);

```bash
docker manifest inspect hello-world:latest
# output for the manifest

docker manifest inspect hello-world:nosuchtag
no such manifest: docker.io/library/hello-world:nosuchtag
```

(code for the manifest subcommands is in https://github.com/docker/cli/blob/8b85274d265815a4ed278bb664c22bb5e32ff237/cli/command/manifest/inspect.go)

Docker Hub implements the OCI distribution spec, which is a documented API (see https://github.com/opencontainers/distribution-spec), so you should be able to use various other tools to interact with the registry, e.g.;

- https://github.com/moby/moby/blob/master/contrib/download-frozen-image-v2.sh (script to pull images with `bash` and `jq`
- https://github.com/regclient/regclient
- https://github.com/containers/skopeo


You should even be able to check if images exist using just cURL and jq;

Get auth token for pulls on the `library/hello-world` image repo (assuming the image you want to check is public);

```bash
token="$(curl -fsSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/hello-world:pull" | jq --raw-output '.token')"
```

Do a HEAD request for the image manifest of the `latest` tag (which exists)

```bash
curl -fsSL \
    -I \
    -H "Authorization: Bearer $token" \
    -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
    -H 'Accept: application/vnd.docker.distribution.manifest.list.v2+json' \
    -H 'Accept: application/vnd.docker.distribution.manifest.v1+json' \
    "https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
```

Which prints something like;

```
HTTP/1.1 200 OK
content-length: 2562
content-type: application/vnd.docker.distribution.manifest.list.v2+json
docker-content-digest: sha256:cc15c5b292d8525effc0f89cb299f1804f3a725c8d05e158653a563f15e4f685
docker-distribution-api-version: registry/2.0
etag: "sha256:cc15c5b292d8525effc0f89cb299f1804f3a725c8d05e158653a563f15e4f685"
date: Tue, 07 Dec 2021 08:59:51 GMT
strict-transport-security: max-age=31536000
ratelimit-limit: 100;w=21600
ratelimit-remaining: 100;w=21600
docker-ratelimit-source: 213.127.30.1
```

Try the same with a tag that doesn't exist (`library/hello-world:nosuchtag`)

```bash
curl -fsSL \
    -I \
    -H "Authorization: Bearer $token" \
    -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
    -H 'Accept: application/vnd.docker.distribution.manifest.list.v2+json' \
    -H 'Accept: application/vnd.docker.distribution.manifest.v1+json' \
    "https://registry-1.docker.io/v2/library/hello-world/manifests/nosuchtag"
```

Which will give a 404;

```
HTTP/1.1 404 Not Found
content-type: application/json
docker-distribution-api-version: registry/2.0
date: Tue, 07 Dec 2021 09:01:46 GMT
content-length: 103
strict-transport-security: max-age=31536000
ratelimit-limit: 100;w=21600
ratelimit-remaining: 100;w=21600
docker-ratelimit-source: 213.127.30.1

curl: (22) The requested URL returned error: 404
```

**Comment by thaJeztah** [comment] 2021-12-07 09:14
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2021-12-07 09:14 UTC
Labels: kind/question

**Comment by amokkara** [comment] 2021-12-07 09:19
@thaJeztah I tried asking this in github but couldnt get a proper response. Had no other option but to disturb you guys. But this is what I was looking for. Thanks for detailed answer. appreciate it

**Comment by amokkara** [comment] 2021-12-16 17:49
@thaJeztah @AkihiroSuda Pl help!
 im having hard time understanding how image push works

`var authConfig = types.AuthConfig{
		Username:      "amokkara",
		Password:      "dummy",
		ServerAddress: "https://docker.repo.dummy.dummy.com",
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*120)
	defer cancel()

	authConfigBytes, _ := json.Marshal(authConfig)
	authConfigEncoded := base64.URLEncoding.EncodeToString(authConfigBytes)
	opts := types.ImagePushOptions{RegistryAuth: authConfigEncoded}
	ioreader , err := dockerClient.ImagePush(ctx,"docker.repo.dummy.dummy.com/amokkara/ads-nodeinfo-controller:test",opts)
	if err != nil {
		return err
	}
        defer ioreader.close()
	io.Copy(os.Stdout, ioreader)

	return nil`
	
	
	Im trying to push large image to remote registry (~500 mb)
	How to know when image is pushed?
	And in my case, the code above, im getting "file already closed" error on ioreader and cant fine image pushed into repo..can you please help
