### ISSUE TITLE
GET /containers/{id}/stats returns invalid time format

### ISSUE THREAD

**Issue by vdvarlamov** [moby/moby#40975] opened 2020-05-15 12:01 UTC
https://docs.docker.com/engine/api/v1.40/#operation/ContainerStats
"read": "2015-01-08T22:57:31.547920715Z"
In fact: "read":"2020-03-04T14:59:28.0520539+03:00".
![image](https://user-images.githubusercontent.com/47747798/82048203-e3515e00-96bc-11ea-999d-65ebbdfb1bba.png)

Host - Windows Server 2019
https://github.com/docker/for-win/issues/5942

**Comment by wangyumu** [comment] 2020-05-19 02:05
"2015-01-08T22:57:31.547920715Z" is UTC time, "2020-03-04T14:59:28.0520539+03:00" is localtime with TimeZone, they are all correct, pls refer to  https://www.ietf.org/rfc/rfc3339.txt .

It looks different time fields use different formats in docker API, not a bug on windows platform.

Tested on Linux with 19.03, `SystemTime` use localtime too:

```
$ curl --unix-socket /var/run/docker.sock http:/v1.40/containers/b5e78317e9e6/stats 2>/dev/null  |  jq .read
"2020-05-19T01:14:39.520493663Z"
"2020-05-19T01:14:40.52875888Z"
^C
$ curl --unix-socket /var/run/docker.sock http:/v1.40/info 2>/dev/null | jq .SystemTime 
"2020-05-19T09:14:46.830031636+08:00"
```

**Comment by thaJeztah** [comment] 2020-05-19 06:34
Looks like the issue is answered (thanks!)

Let me close this one, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-19 06:34 UTC
Labels: area/api, version/19.03
