### ISSUE TITLE
api: filter map doesn't recognize 'reference' attribute

### ISSUE THREAD

**Issue by m0ddixx** [moby/moby#44161] opened 2022-09-21 11:02 UTC
### Description

I stumbled across a weird bug while using the Docker.Dotnet API Client.
While debugging i found that just passing the simple request `http://localhost:2375/images/json?all=1&filters={%22reference%22:{%22postgres:11.14%22:true}}` results into this error response:
```json
{"message":"invalid filter 'reference'"}
```
Since the request looks valid from the specification, I think there must be something wrong with parsing the filter attributes.

### Reproduce

1. form a image list request with a reference filter like `http://localhost:2375/images/json?all=1&filters={%22reference%22:{%22postgres:11.14%22:true}}`

### Expected behavior

The request should output a valid JSON list of images with the specified filter.

### docker version

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          22.06.0-beta.0-372-gd3bb8227ce.m
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.18.4
  Git commit:       d3bb8227ce
  Built:            Thu Aug 25 16:48:56 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 22.06.0-beta.0-372-gd3bb8227ce.m
 Storage Driver: stargz
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 24.82GiB
 Name: docker-desktop
 ID: 2731c276-4d01-4168-b7b2-6214cca7bfdb
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 43
  Goroutines: 47
  System Time: 2022-09-21T10:53:43.35399671Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by thaJeztah** [comment] 2022-09-21 11:15
Thanks for reporting; I see you have enabled the [experimental containerd integration feature](https://docs.docker.com/desktop/containerd/) in Docker Desktop, and it looks like this is one of the options that has not yet been implemented; https://github.com/moby/moby/issues/43847

It looks like this has not been listed under the "known issues" on that page, so that's something we should address in the documentation. /cc @bsousaa 


In the meantime, let me close this as duplicate of https://github.com/moby/moby/issues/43847


Thanks again for reporting! If you find other issues related to the containerd integration, also feel free to provide feedback through the "Give feedback" form in the Docker Desktop preference panel, which should help getting the people working on this feature to be notified 👍 

<img width="754" alt="Screenshot 2022-09-21 at 13 12 57" src="https://user-images.githubusercontent.com/1804568/191490140-3e72c8a6-14ac-4a7a-b1f3-f7f975242073.png">

**Closed by thaJeztah** 2022-09-21 11:15 UTC
Labels: status/0-triage, kind/bug, containerd-integration
