### ISSUE TITLE
Volumes created via docker CLI with UCP managed swarm can't be inspected or removed.

### ISSUE THREAD

**Issue by govint** [moby/moby#35334] opened 2017-10-30 12:58 UTC
**Description**

**Steps to reproduce the issue:**
I have docker UCP 2.2.3 (trial) installed and with a two node swarm running docker EE each,
root@(none):/vol# docker version
Client:
 Version:      17.06.2-ee-4
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   dd2c358
 Built:        Thu Oct 12 16:16:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ee-4
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   dd2c358
 Built:        Thu Oct 12 16:15:47 2017
 OS/Arch:      linux/amd64
 Experimental: false

The client CLI and UCP version is this,
root@photon-machine [ ~ ]# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   02c1d87
 Built:        Tue Aug 15 18:54:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      ucp/2.2.3
 API version:  1.30 (minimum version 1.20)
 Go version:   go1.8.3
 Git commit:   b3f6755b6
 Built:        Wed Sep 13 22:59:16 UTC 2017
 OS/Arch:      linux/amd64
 Experimental: false

Whats happening is I have a volume plugin installed on the manager and the single worker node. 

I'm able to create volumes with the managed plugin

The volume can be used to run a container that attaches the volume

"docker volume inspect" and "docker volume rm" both fail with a "No such volume" error.

Its almost like UCP isn't tracking the volume as associated with the plugin. This happens with any new or old volume.

1. Create a volume
root@photon-machine [ ~ ]# docker volume create -d vsphere newEEVol_13
newEEVol_13

2. Try inspecting the volume
root@photon-machine [ ~ ]# docker volume inspect newEEVol_13
[]
Error: No such volume: newEEVol_13

But on the worker node I can inspect the volume perfectly well,
root@(none):/vol# docker volume inspect newEEVol_13
[
    {
        "Driver": "vsphere:latest",
        "Labels": {
            "com.docker.swarm.whitelists": "[\"node==(none)\"]",
            "com.docker.ucp.access.label": "/",
            "com.docker.ucp.collection": "swarm",
            "com.docker.ucp.collection.root": "true",
            "com.docker.ucp.collection.swarm": "true"
        },
        "Mountpoint": "/mnt/vmdk/newEEVol_13/",
        "Name": "newEEVol_13",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "13MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Mon Oct 30 12:43:49 2017",
            "created by VM": "worker2-VM2.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]

3. Try attaching the volume to a container
root@photon-machine [ ~ ]# docker run --rm -it -v newCEVol_13:/mnt centos
[root@29f120d0d6ae /]#

4. Try removing the volume
root@photon-machine [ ~ ]# docker volume rm newEEVol_13
Error response from daemon: No such volume

**Describe the results you received:**
The volumes are getting created, but can't be inspected or removed.

**Describe the results you expected:**
Docker CLI talking to UCP and UCP UI are both seeming to report the same behavior - both are unable to retrieve volume meta-data or remove volumes.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ee-4
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   dd2c358
 Built:        Thu Oct 12 16:16:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ee-4
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   dd2c358
 Built:        Thu Oct 12 16:15:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 2
 Paused: 0
 Stopped: 9
Images: 10
Server Version: 17.06.2-ee-4
Storage Driver: aufs
 Root Dir: /vol/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: t94bb4v2h0n30qav9ez186slh
 Is Manager: false
 Node Address: 10.161.118.140
 Manager Addresses:
  10.161.99.84:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86GiB
Name: (none)
ID: NINK:HV2F:IRM2:6JJU:XBVA:DW7J:CV5S:OARB:J4UL:O7S3:4LBA:7AVE
Docker Root Dir: /vol/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
[docker-support-20171030-12-45-22.zip](https://github.com/moby/moby/files/1427260/docker-support-20171030-12-45-22.zip)

**Comment by cpuguy83** [comment] 2017-10-30 13:50
@govint This is a UCP issue (or probably more precisely a classic swarm issue), so closing here as there isn't really anything to do here.

**Closed by cpuguy83** 2017-10-30 13:50 UTC
Labels: version/17.06

**Comment by cpuguy83** [comment] 2017-10-30 13:55
I opened an internal issue on UCP to track this.

**Comment by thaJeztah** [comment] 2017-10-30 14:18
may be a duplicate of https://github.com/moby/moby/issues/34664 as well

**Comment by cpuguy83** [comment] 2017-10-30 16:41
> This should be fixed in 2.2.4 and 3.0.0

**Comment by govint** [comment] 2017-11-13 17:37
@cpuguy83 @thaJeztah can you'll please update whether the issue on UCP/swarm is fixed as discussed above. I'm still seeing the issue in UCP 2.2.4 , volume plugins that create _local_ volumes don't seem to have the issue reported here.

**Comment by thaJeztah** [comment] 2017-11-13 17:41
@govint I don't have full insight in other fixes; perhaps @wsong may know more

**Comment by wsong** [comment] 2017-11-13 17:49
There was a bug in UCP where volumes with non-local drivers could not be inspected or remove. In UCP 2.2.4, you can remove those volumes, but you still can't inspect them.

You actually can't inspect any volume on UCP where the volume exists with the same name on multiple nodes; the reason for this is that there isn't an easy way to show the volumes' data if they have the same name but different labels, options, etc. Instead, UCP just returns an error if there are multiple volumes of this sort.

However, in UCP 2.2.4+, you remove volumes, even if multiple volumes exist with the same name on multiple nodes. If you remove that volume, it'll just remove it on every node.

**Comment by govint** [comment] 2017-11-13 18:54
@wsong, thanks for the detailed explanation, on UCP 2.2.4 I can create the volumes and attach those, but inspect and remove fails. Your saying post-2.2.4 we should have the fix. Any idea by when we can expect this to be available. Thanks again.

**Comment by wsong** [comment] 2017-11-13 19:06
Sorry, I should've been a bit more explicit. On UCP 2.2.4, you should be able to remove volumes, but not inspect them.

What is the error message you're getting when you're trying to remove the volumes? And what does `docker volume ls` show?

**Comment by govint** [comment] 2017-11-13 19:41
@wsong, below is what I'm seeing with UCP 2.2.4 via the CLI (happens with the UI too). I'm using a two node swarm cluster:
# docker node ls
ID                            HOSTNAME                    STATUS              AVAILABILITY        MANAGER STATUS
fuqp8g9jh2po3zerb00ro46t3 *   sc-rdops-vm02-dhcp-52-237   Ready               Active              Leader
t94bb4v2h0n30qav9ez186slh     (none)                      Ready               Active


1. Create volume
# docker volume create -d vsphere test_delete_vol_1
test_delete_vol_1

2. List
# docker volume ls
DRIVER              VOLUME NAME
vsphere             test_delete_vol_1@sharedVmfs-0
vsphere             test_delete_vol_1@sharedVmfs-0

3. Inspect volume
# docker volume inspect test_delete_vol_1
[]
Error: No such volume: test_delete_vol_1

4. Remove volume
# docker volume rm test_delete_vol_1
Error response from daemon: No such volume

My plugin logs don't show either a Get() or Remove() call being received from Docker daemon/containerd on either of the swarm nodes.

**Comment by wsong** [comment] 2017-11-13 20:07
Can you also post the `docker volume inspect` output for each of those volumes on each node? You can SSH into each node directly to get that info.

For `docker volume rm` to work, the labels on both volumes must be identical.

Also, as described above, `docker volume inspect` is not intended to work.

**Comment by govint** [comment] 2017-11-14 03:45
@wsong, the labels are different on the cluster nodes, but I didn't set these by myself though,

Node 1 - this is the node thru which all commands seem to go thru always (from plugin logs)

docker volume inspect test_delete_vol_1
[
    {
        "Driver": "vsphere",
        "Labels": {
            "com.docker.swarm.whitelists": "[\"node==(none)\"]",
            "com.docker.ucp.access.label": "/",
            "com.docker.ucp.collection": "swarm",
            "com.docker.ucp.collection.root": "true",
            "com.docker.ucp.collection.swarm": "true"
        },
        "Mountpoint": "/mnt/vmdk/test_delete_vol_1/",
        "Name": "test_delete_vol_1",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "13MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Mon Nov 13 19:34:13 2017",
            "created by VM": "worker2-VM2.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]


Node 2
docker volume inspect test_delete_vol_1
[
    {
        "Driver": "vsphere",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/test_delete_vol_1/",
        "Name": "test_delete_vol_1",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "13MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Mon Nov 13 19:34:13 2017",
            "created by VM": "worker2-VM2.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]

**Comment by wsong** [comment] 2017-11-14 17:05
If the labels are different, then removal won't work. The reason for this is that we use the collection labels (e.g. `com.docker.ucp.collection`) to determine what collection the volume is part of.

When UCP creates a volume, it adds these collection labels to the volume automatically. Every volume is a part of a collection, and users can have permissions assigned for these collections; admins can use this functionality to allow certain users to view or create containers, volumes, etc. on a per-collection basis. You can learn more here: https://docs.docker.com/datacenter/ucp/2.2/guides/access-control/

In our volume removal code, we say that if there are multiple volumes with the same name on different nodes, they must all be part of the same collection before we'll remove them. That is not the case here, because the first volume is in the `swarm` collection but the second volume is unlabelled.

In this case, it looks like the `vsphere` volume driver automatically creates volumes on other nodes, but does not attach labels to them. This essentially means that the `vsphere` volume driver is going around UCP and creating volumes directly, which means that UCP can't delete them through its access control model. You should delete those volumes by talking to the nodes directly.

**Comment by govint** [comment] 2017-11-16 10:44
@wsong, thanks for your help, I recreated a new swarm cluster and its behaving as you have described. But I'm running the nodes with docker 17.06.0-ce vs. a docker EE release on Photon OS.

I'm able to create/inspect/rm the volumes (yes, inspect works). The labels on the volumes are all the same as you mentioned as well on each of the five swarm nodes.

1. UCP
docker version
Client:
 Version:      17.07.0-ce
 API version:  1.30 (downgraded from 1.31)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:43:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      ucp/2.2.4
 API version:  1.30 (minimum version 1.20)
 Go version:   go1.8.3
 Git commit:   168ec746e
 Built:        Thu Nov  2 17:15:16 UTC 2017
 OS/Arch:      linux/amd64
 Experimental: false

2. Each node is installed as below:
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   02c1d87
 Built:        Tue Aug 15 18:54:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   02c1d87
 Built:        Tue Aug 15 18:55:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

3. Swarm nodes:
docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
fwih17g4insk8ylopzyrnhnhk *   photon-machine1     Ready               Active              Leader
hgvifgiv7ah8vuzbj1hdo4449     photon-machine3     Ready               Active
jxlfa0lnlyj6d0gbc01vdauzo     photon-machine4     Ready               Active
oaes58gnje9jy5bsrlksyle08     photon-machine5     Ready               Active
zcwgv99u028zwob9c7k8vfgqb     photon-machine2     Ready               Active

4. Create, inspect and remove a volume:

docker volume create -d vsphere photonvol-6
photonvol-6

docker volume inspect photonvol-6
[
{
"Driver": "vsphere",
"Labels": {
"com.docker.swarm.whitelists": "["node==photon-machine2|photon-machine1|photon-machine3|photon-machine4|photon-machine5"]",
"com.docker.ucp.access.label": "/",
"com.docker.ucp.collection": "swarm",
"com.docker.ucp.collection.root": "true",
"com.docker.ucp.collection.swarm": "true"
},
"Mountpoint": "/mnt/vmdk/photonvol-6/",
"Name": "photonvol-6",
"Options": {},
"Scope": "global",
"Status": {
"access": "read-write",
"attach-as": "independent_persistent",
"capacity": {
"allocated": "13MB",
"size": "100MB"
},
"clone-from": "None",
"created": "Thu Nov 16 10:34:08 2017",
"created by VM": "Photon-2.0-11",
"datastore": "sharedVmfs-0",
"diskformat": "thin",
"fstype": "ext4",
"status": "detached"
}
}
]

docker volume rm photonvol-6
photonvol-6
