### ISSUE TITLE
docker: Error response from daemon: containerd: container did not start before the specified timeout

### ISSUE THREAD

**Issue by contactlp** [moby/moby#35923] opened 2018-01-03 18:49 UTC
Details about docker and machine is attached.
```
~> docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   78d1802
 Built:        Tue May 30 18:21:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   78d1802
 Built:        Tue May 30 18:21:18 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
~> docker info
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 14
Server Version: 17.04.0-ce
Storage Driver: devicemapper
 Pool Name: docker-254:0-4340587-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.492GB
 Data Space Total: 107.4GB
 Data Space Available: 9.527GB
 Metadata Space Used: 13.14MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.134GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2015-05-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Init Binary:
containerd version:  (expected: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73)
runc version: N/A (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
Kernel Version: 3.12.74-60.64.40-default
Operating System: SUSE Linux Enterprise Server 12 SP1
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 504.6GiB
Name: test
ID: 26NX:F5Q6:QVD6:W4RT:HCRR:FFO6:PURG:BVDV:CV2A:QXA3:K5ON:SXFG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: IPv4 forwarding is disabled
```

```
~> cat /etc/*release
NAME="SLES"
VERSION="12-SP1"
VERSION_ID="12.1"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
```

```
~> uname -r
3.12.74-60.64.40-default
```
I have been using this contaienr for a year now, but after a reboot, it stopped working
```
~> docker start luigid
Error response from daemon: containerd: container did not start before the specified timeout
Error: failed to start containers: luigid

~> docker rm luigid
Error response from daemon: Driver devicemapper failed to remove root filesystem 1115ca3e81577a58b06ed1c0cb9d04600d63506f3427a069eb57851a876cc031: failed to remove device e0111da58ac68b86d0af576644e908242b442f006917202acdc8edd27fe2e98e: devicemapper: Error running RemoveDevice dm_task_run failed
```
Since I was not able to remove the container, I did following and it suprisingly work and after that I was able to remove the container (dont ask me how did that work , I got help from another github issue)
`~> sudo ls /var/lib/docker/devicemapper/mnt/`
After removing the container I tried to run following and got the error.
```
~> docker run -d -v luigid_state:/luigi/state --name luigid -h luigid --restart=always -p 127.0.0.1:8082:8082 localhost:5000/luigid
WARNING: IPv4 forwarding is disabled. Networking will not work.
3282e2e4c31ba06a95c039fa6e8bbc3dc6572e3e8d47355fc86410c05655ec49
docker: Error response from daemon: containerd: container did not start before the specified timeout.
```
 docker demon log

```
Jan 03 12:59:09 carp dockerd[5975]: time="2018-01-03T12:59:09.578000319-06:00" level=warning msg="IPv4 forwarding is disabled. Networking will not work"
Jan 03 12:59:09 carp dockerd[5975]: time="2018-01-03T12:59:09.586312841-06:00" level=warning msg="Security options with `:` as a separator are deprecated and will be completely unsupported in 17.04, use `=` instead."
Jan 03 12:59:39 carp dockerd[5975]: time="2018-01-03T12:59:39.591598581-06:00" level=error msg="Create container failed with error: containerd: container did not start before the specified timeout"
Jan 03 12:59:39 carp dockerd[5975]: time="2018-01-03T12:59:39.636236902-06:00" level=error msg="devmapper: Error unmounting device 917c8361747b18cbf5952042e345ee27ec79b3be0ad24d927121d36e9a7ae46b: devicemapper: Error running RemoveDevice dm_task_run failed"
Jan 03 12:59:39 carp dockerd[5975]: time="2018-01-03T12:59:39.636266013-06:00" level=error msg="Error unmounting container 18117dd47fd65540dddf23e36d712c37e2ddcc0375bb943b1f72410cfce04c3c: devicemapper: Error running RemoveDevice dm_task_run failed"
Jan 03 12:59:39 carp dockerd[5975]: time="2018-01-03T12:59:39.636758011-06:00" level=error msg="Handler for POST /v1.28/containers/logspout/start returned error: containerd: container did not start before the specified timeout"
```

**Comment by sergey-safarov** [comment] 2018-01-04 10:49
Reproduced on `17.07.0-ce` and on `17.12.0-ce`

**Comment by cpuguy83** [comment] 2018-01-04 15:23
Have you tried upgrading? 17.04 is many months old and out of support.
I also believe there have been a number of bugs fixed related to this containerd timeout issue.

The latest "stable" release is 17.12 (also the latest release, period) which is hot off the press. "17.09" is the last "stable" release and is supported for another month.

**Comment by thaJeztah** [comment] 2018-01-04 15:26
Looks like you are running Docker CE on SUSE, which is not a supported platform (there are no Docker CE packages for SUSE, only for Docker EE https://docs.docker.com/engine/installation/linux/docker-ee/suse/

You are most likely running a package that's built by SUSE, also based on this output;

```
containerd version:  (expected: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73)
runc version: N/A (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
```

We can't provide support for those packages, and it's best to either install an up to date version of Docker EE, or contact SUSE support for this.

I'm closing this issue because of the above, but feel free to discuss

**Closed by thaJeztah** 2018-01-04 15:26 UTC
Labels: status/more-info-needed, version/17.04
