### ISSUE TITLE
Docker json-file logging driver hangs when rotating files on Windows

### ISSUE THREAD

**Issue by inosvaruag** [moby/moby#39274] opened 2019-05-28 01:21 UTC
**Description**

Docker json-file logging driver hangs when rotating files on Windows. Once a container gets in hung state, no more log entries are saved for it unless docker or the container is restarted.

PS> Get-EventLog -LogName Application -Source Docker shows the following error messages:

```
Failed to log msg "" for logger json-file: error removing oldest log file: remove C:\ProgramData\docker\containers\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae-json.log.1: The process cannot access the file because it is being used by another process.
```

(REPEATED UNTIL MITIGATED) 
```
Failed to log msg "" for logger json-file: error closing file: close C:\ProgramData\docker\containers\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae-json.log: file already closed.
```

The issue does not happen every time but happens quite frequently.

**Steps to reproduce the issue:**
0. Run a Windows 2019 OS VM with docker using named pipes.
1. Run a docker container on the VM which outputs some log entries. Set this container to use json-file logging driver with 1M file size and 2 file-limit.
2. Create another docker container which is has the docker named pipe mounted. Run periodic ContainerLogs API call for the container in step 1 in this container.
3. Let the setup run until Event log entries start showing the error messages described above. Once this state is reached, no more logs are captured in the json files.

**Describe the results you received:**
1. Container logs stop getting captured on log file rotation.

**Describe the results you expected:**
1. Container logs should not get stuck.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue does not occur every time. But it happens very frequently when multiple containers are running on multiple VMs.

**Output of `docker version`:**

```
> docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       142dfcedca
  Built:            02/28/2019 06:31:15
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.09.3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.316)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15GiB
Name: dc48a85165fcf24
ID: KCKO:GJP5:M7R3:IE45:2LVF:FCYR:MOBJ:DFS7:BBV6:L4XV:DRZY:ZA5M
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 2019 VM on GCP
Mitigations = restart affected container, or restart docker service on Windows.

**docker inspect output on a container which got into this state**
```
> docker inspect e9b
[
    {
        "Id": "e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae",
        "Created": "REDACTED",
        "Path": "REDACTED",
        "Args": [
           "REDACTED"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3648,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-05-28T00:52:02.4274538Z",
            "FinishedAt": "2019-05-28T00:52:00.7740957Z"
        },
        "Image": "sha256:b301392b301239e154b21e03c8b77c03abd14e8ab3459835036a411998b60fd8",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae\\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae-json.log",
        "Name": "REDACTED",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "REDACTED"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "2",
                    "max-size": "1m"
                }
            },
            "NetworkMode": "nat",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "REDACTED",
                "Destination": "REDACTED",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "REDACTED",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "REDACTED",
            ],
            "Image": "REDACTED",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [],
            "OnBuild": null,
            "Labels": {
                "agent.config": "REDACTED",
                "agent.managed": "true"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "93a8f0003991defdec723729ef537a49ecab734ede99e070a8dd1181ff79137e",
                    "EndpointID": "8d8509776404f0d0532d5afe3132c5a4a63e94e0b5fcb94751d53f24e29e1f9a",
                    "Gateway": "REDACTED",
                    "IPAddress": "REDACTED",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:02:1c:ff",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by olljanat** [comment] 2019-06-01 18:18
Yes, this is definitely bug.

Simplified way to reproduce.
1. Start container with command:
```
docker run --rm --name test --detach=true `
 --log-driver json-file --log-opt max-file=2 --log-opt max-size=1b `
 mcr.microsoft.com/windows/nanoserver:1809 ping -t 127.0.0.1
```
2. Follow log with command `docker logs -f test` and close it after couple of seconds.
3. Look Docker logs with `Get-EventLog -LogName Application -Source Docker -Newest 10` and see that Docker does not survive from situation.

I will look if I can find some reason to this.

**Comment by olljanat** [comment] 2019-06-01 18:18
Derek add label: kind/bug

**Comment by olljanat** [comment] 2019-06-02 15:41
Found that it looks to be actually Golang bug/missing feature https://github.com/golang/go/issues/32088
so let's see if they will add that `syscall.FILE_SHARE_DELETE` flag so this can be very easily solved to by including that flag to https://github.com/moby/moby/blob/916eabd459fe707b5c4a86377d12e2ad1871b353/daemon/logger/loggerutils/logfile.go#L559

**Comment by networkimprov** [comment] 2019-06-02 17:55
Easiest short-term fix is to patch /usr/lib/go/src/syscall/syscall_windows.go:
```
var Open_FileShareDelete = false              // add 1 line
func Open(...) (...) {
	...
	sharemode := ...
	if Open_FileShareDelete {             // add 3 lines
		sharemode |= FILE_SHARE_DELETE
	}
```
Add `func init() { syscall.Open_FileShareDelete = true }` in a Windows-specific project file.

Also rename syscall_windows.go to syscall_windows_patched.go so it won't disappear on a Go update.

**Comment by inosvaruag** [comment] 2019-06-10 23:48
Hi Folks,

Thanks for investigating and responding on this issue. Who is the right reviewer/decision maker for getting this approach approved?

**Comment by olljanat** [comment] 2019-06-11 03:47
Above workaround would need very dirty hacks to build scripts which I'm quite sure that they this project maintainers would not approve. So IMO it need to be fixed on Golang side. I just got test code implemented to there https://github.com/golang/go/issues/32088#issuecomment-500576874 so they can use it to verify that this use case can be fixed with it.

Unfortunately that most probably will take a while before we will have new Golang version (based on https://github.com/golang/go/wiki/Go-Release-Cycle we can have Golang 1.4 earliest on end of January assuming that fix is implement still during summer) and after that fix need to be implemented in Moby side.

@inosvaruag so I highly recommend that you stay on default JSON driver settings which does not use log rotate until then. If you need log cleanup then you can quite easily create example PowerShell script which first shutdown Docker then remove those logs from disk example on every night (btw I highly recommend nightly reboots anyway because of other weaknesses on Windows containers/Windows itselves).

cc @thaJeztah

**Comment by thaJeztah** [comment] 2019-06-12 10:54
Thanks for linking that Golang issue, @olljanat. Interesting. Thinking if we'd be able to have a workaround, but I guess that'd be very hacky (reverse the sequence of events; copy the current file to a "rotated" file, then truncate the current log-file?)

**Comment by olljanat** [comment] 2019-06-19 20:11
> Thinking if we'd be able to have a workaround, but I guess that'd be very hacky (reverse the sequence of events; copy the current file to a "rotated" file, then truncate the current log-file?)

Yea that would work but then we probably would need include some max size limit for those log files as currently it is possible that user set max size example to 10 GB (I have no idea why anyone would do that but it is possible) which would cause issues.

**Comment by thaJeztah** [comment] 2019-09-12 06:43
Pull request was opened in Golang to address https://github.com/golang/go/issues/32088 (https://github.com/golang/go/issues/32088#issuecomment-498041616) ; https://go-review.googlesource.com/c/go/+/194957/

**Comment by olljanat** [comment] 2019-10-03 18:35
@thaJeztah afaiu this now only fixed on Windows build >=1903 like I mentioned on https://github.com/moby/moby/pull/39974#issuecomment-534644914

But that can be easily verified by repeating these this test https://github.com/moby/moby/issues/39274#issuecomment-497966709

**Comment by olljanat** [comment] 2019-10-22 16:23
Derek reopen

**Comment by olljanat** [comment] 2019-10-22 16:28
@thaJeztah @cpuguy83 I repeated test now on Windows Server 2019 using latest binaries from master and it leaves stuck to error loop:
```
time="2019-10-22T16:22:30.702498000Z" level=error msg="Failed to log msg \"\" for logger json-file: error closing file: close C:\\ProgramData\\docker\\containers\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22-json.log: file already closed"
time="2019-10-22T16:22:30.708500300Z" level=error msg="Failed to log msg \"\" for logger json-file: error closing file: close C:\\ProgramData\\docker\\containers\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22-json.log: file already closed"
time="2019-10-22T16:22:30.713859400Z" level=error msg="Failed to log msg \"\" for logger json-file: error closing file: close C:\\ProgramData\\docker\\containers\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22-json.log: file already closed"
time="2019-10-22T16:22:30.714500000Z" level=error msg="Failed to log msg \"\" for logger json-file: error closing file: close C:\\ProgramData\\docker\\containers\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22-json.log: file already closed"
time="2019-10-22T16:22:30.715511700Z" level=error msg="Failed to log msg \"\" for logger json-file: error closing file: close C:\\ProgramData\\docker\\containers\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22\\865e8abc535471d1487ec5ec0bb7a23b2404003d81da4572ebda9d7db15dcc22-json.log: file already closed"
```
so I re-opened this one.

**Comment by thaJeztah** [comment] 2019-10-22 16:32
boo! 😕

Thanks for reporting though! 🤗

**Closed** 2022-05-19 20:50 UTC
Labels: area/logging, platform/windows, kind/bug, version/18.09
