### ISSUE TITLE
Failed to load container ...: EOF

### ISSUE THREAD

**Issue by 63Alexey63** [moby/moby#33601] opened 2017-06-09 05:05 UTC
**docker info:**
```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 49
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-67152639-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 107.4 GB
 Data Space Total: 107.4 GB
 Data Space Available: 0 B
 Metadata Space Used: 19.21 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.128 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 3.702 GiB
Name: as21428
ID: RGNY:VIKW:EFF6:7U25:4DDZ:VZKD:7IXI:EP7I:MMJD:ZI4E:OKOH:ZI2N
Registries: docker.io (secure)
```
**docker version:**
```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64
```

Container with CentOS. Inside the container, `yum update` was run. During the upgrade, the place is out and the container is frozen. The place in the main system was cleaned, but the container did not continue updating. After the system is rebooted, the container is not displayed. 
Log

`Journalctl -u docker.service`

```
Jun 09 07:48:04 as21428 docker-current [1139]: ..time = "2017-06-09T07: 48: 04.234926081 + 04: 00" level = error msg = "Failed to load container 37f195e5aa79f640a2b950d685bdae37f62f643b606cf97adfafa069c56cd57b: EOF"
Jun 09 07:48:04 as21428 docker-current [1139]: .time = "2017-06-09T07: 48: 04.235679874 + 04: 00" level = error msg = "Failed to load container 4b0a10ab2ccb1c35743306af50338c570aa8555d503db8278fcf618ca24bda73: EOF"
Jun 09 07:48:04 as21428 docker-current [1139]: ..... time = "2017-06-09T07: 48: 04.316905298 + 04: 00" level = error msg = "Failed to load container ae903d397bc4be2c701f89c5e2582a7a4eb3d6e5d8b6e06a86067faaa5f3bb3e: EOF "
Jun 09 07:48:04 as21428 docker-current [1139]: .time = "2017-06-09T07: 48: 04.318148213 + 04: 00" level = error msg = "Failed to load container aeb7edea585277177b2043d337052a01a2c15de555b73b3d2b5d0f904d0df81b: EOF"
Jun 09 07:48:04 as21428 docker-current [1139]: .time = "2017-06-09T07: 48: 04.335625340 + 04: 00" level = error msg = "Failed to load container bf82529e002b651ebfccedb2b124326c5b547380e534e9439d5fa4660c22f90d: EOF"
Jun 09 07:48:04 as21428 docker-current [1139]: .time = "2017-06-09T07: 48: 04.336236145 + 04: 00" level = error msg = "Failed to load container d3f9bdef8e9d72585fe2b7687bbe2238be4d8cfdf4ade27c163aba672282443e: EOF"
Jun 09 07:48:04 as21428 docker-current [1139]: .time = "2017-06-09T07: 48: 04.349049287 + 04: 00" level = error msg = "Error unmounting container 5ec844b2c156b05c84abbf2ca578c243f78c91474c3d1626ae3cffbf9343340b: not mounted"
Jun 09 07:48:04 as21428 docker-current [1139]: time = "2017-06-09T07: 48: 04.357311406 + 04: 00" level = error msg = "failed to register link for container 65c103e00c76ce535d466ece785daf100676873accdd3501b6ad6abe87aaa010: Could not get container For
Jun 09 07:48:04 as21428 docker-current [1139]: time = "2017-06-09T07: 48: 04.357600359 + 04: 00" level = error msg = "failed to register link for container e9f9eb13615cb0671539ad018523a9167189c63a39c3833a3d1b30a1282e0431: Could not get container For
Jun 09 07:48:04 as21428 docker-current [1139]: time = "2017-06-09T07: 48: 04.35766
```
`var/lib/docker/containers`  - 12 containers

`docker ps -a` - show only 6 container

**Comment by cpuguy83** [comment] 2017-06-09 12:28
This is a very old version of Docker and also not the official docker packaging.
There's not much we can do to troubleshoot this and much of the codebase has changed significantly since 1.10 was released.

Closing since there's not really anything we can do here.
If you can reproduce on 17.03+ we can look at that.

Thanks, sorry there's not really anything we can do here.

**Closed by cpuguy83** 2017-06-09 12:28 UTC
Labels: version/1.10
