### ISSUE TITLE
[SDK] ImageBuild: No tags are generated when the response is not read.

### ISSUE THREAD

**Issue by tttoad** [moby/moby#48599] opened 2024-10-07 22:33 UTC
### Description

When I use the SDK to build an image, the label is not generated if the response is not read.

### Reproduce

```go
// not REPOSITORY:TAG  like  <none>       <none>    a6fce21df75c   11 seconds ago   540MB
_ , err := d.cli.ImageBuild(ctx, reader, types.ImageBuildOptions{
		Tags: []string{"ccc:123"},
	})

// ccc  123    320d9ff4600f   6 seconds ago   752MB
resp, err := d.cli.ImageBuild(ctx, reader, types.ImageBuildOptions{
		Tags: []string{"ccc:123" },
	})
	if err != nil {
		return err
	}
	_, _ = io.ReadAll(resp.Body)

```

### Expected behavior

Whether or not the response results are read should not affect the image build.

### docker version

```console
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
// SDK
github.com/docker/docker v27.3.1+incompatible
```

### docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 20
  Running: 0
  Paused: 0
  Stopped: 20
 Images: 16
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.124-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: QCST:VWPI:BTEZ:N7IL:WLKZ:HHXG:FUQR:UBON:23PM:JZSZ:IGZD:XCNK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Registry Mirrors:
  https://***.com/
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2024-10-18 21:24
Let me close this ticket, because it's not a bug, but I opened https://github.com/moby/moby/pull/48696 to add some logs.


Also feel free to continue the conversation.

**Closed by thaJeztah** 2024-10-18 21:24 UTC
Labels: area/builder, status/0-triage, kind/bug, version/20.10, area/builder/classic-builder, area/go-sdk
