### ISSUE TITLE
Local volumes don't respect "--storage-opt size=..." (overlay2 + xfs pquota)

### ISSUE THREAD

**Issue by TimoRoth** [moby/moby#41328] opened 2020-08-07 20:14 UTC
**Description**

When having a local volume in a container, it does not respect the --storage-opt size=... for that volume.

**Steps to reproduce the issue:**
1. Create image with local volume, like "VOLUME /root"
2. Create container based on said image, with --storage-opt size=1G on xfs pquota backed overlay2 storage
3. See that volume does not respect size limit.

**Describe the results you received:**

```
# cat Dockerfile
FROM ubuntu:latest
VOLUME /root
# docker build -t testimg .
[...]
# docker run -ti --rm --storage-opt size=1G testimg /bin/bash
root@ba57cfd3fad0:/# df /
Filesystem     1K-blocks  Used Available Use% Mounted on
overlay          1048576     8   1048568   1% /
root@ba57cfd3fad0:/# df /root
Filesystem      1K-blocks     Used  Available Use% Mounted on
/dev/vdb1      1073216496 21790140 1051426356   3% /root
root@ba57cfd3fad0:/# exit
```

**Describe the results you expected:**

I'd have expected to see the same size limit imposed on /root than there is on /.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 62
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 14
 Total Memory: 62.82GiB
 Name: oggm-hub
 ID: 7GHN:5QBB:O36B:UQYK:RBNH:MBHU:YYXB:MFKT:DACK:LFER:PNP5:IBG5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Standard Ubuntu 20.04 with installation via official docker repositories.

**Comment by thaJeztah** [comment] 2020-08-07 20:28
This is expected. The storage-opt is for the container's (overlay) filesystem. Volumes are not part of that and won't be affected by that configuration. (volumes can also be shared by multiple containers, in which case each container could have its own storage-opt set).

I'm closing this issue, because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-08-07 20:28 UTC

**Comment by TimoRoth** [comment] 2020-08-07 20:35
It should be technically absolutely possible to set the xfs proj quota on the volumes local mountpoint, the same way it's done on the underlaying overlay2 mountpoints.

The use case of this is that I want to have one per-user container that has /home as a volume, which is then given to all containers of that user via --volumes-from.
But in doing so, it allows the users to fill up the entire disk, which I so far am preventing via the size storage-opt.

So what's basically needed is a way to specify a size-limit for specific volumes of an image, that is then enforced the same way the storage opt is.

**Comment by thaJeztah** [comment] 2020-08-07 21:17
That would be an option for the volume itself (so `docker volume create --opt ....`). The local volume driver does not have support for  this, but there may be volume driver plugins that have options for that.

Note that although the local driver itself doesn't have this feature, the options are passed as `--opt` on `docker volume create` are passed through to the `mount` command, so if it's possible to restrict size through that, that could be an option, similar to the following to create a volume with a custom storage path

```
docker volume create --opt type=none --opt device=/some/host/path --opt o=bind myvolume
```

Or examples in https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options to use `nfs` or `btrfs` for the volume.


There is a feature request for adding a dedicated option for this in https://github.com/docker/for-linux/issues/178 (and earlier discussions in https://github.com/moby/moby/issues/37858 and https://github.com/moby/moby/issues/16670, but there are no plans currently to implement this in the local driver.
