### ISSUE TITLE
NFS with local volume driver produces EPERM

### ISSUE THREAD

**Issue by mahnunchik** [moby/moby#34543] opened 2017-08-17 10:53 UTC
**Description**

Local NFS volume could not be used because it is failed on `chown` command.

**Steps to reproduce the issue:**
1. Create volume
```bash
docker volume create --driver local \
  --opt type=nfs \
  --opt o=addr=10.0.10.20,rw \
  --opt device=:/data/test/ \
  foo
```

**Describe the results you received:**
```bash
$ docker run -it --rm -v foo:/data/db mongo:3
docker: Error response from daemon: chown /var/lib/docker/volumes/foo/_data: operation not permitted.
```

```bash
$ docker run -it --rm -v foo:/data/db:nocopy mongo:3
chown: changing ownership of '/data/db': Operation not permitted
```

**Describe the results you expected:**

Volume is useful.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 190
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 238
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 7dfmz7i722lqlm0hf2pe0oxgz
 Is Manager: true
 ClusterID: yanmcql34st5fyvi7mk34co8i
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.0.0.109
 Manager Addresses:
  10.0.0.108:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-91-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69GiB
Name: evlasenko-desktop
ID: A3AW:NXVA:WYZD:CGLL:4OJ5:7MDI:AGAA:FT6F:7ERX:6IHU:TJGQ:YL6H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by cpuguy83** [comment] 2017-08-17 13:26
I've changed the title to reflect the issue.

**Comment by cpuguy83** [comment] 2017-08-17 13:30
This was a regression in 17.06 and should be fixed in 17.06.1 which is due soon.
The commit that should fix it is here: https://github.com/docker/docker-ce/commit/b0efd8dda5c29885d441bed21cac680f5a3420dc

Can you test the 17.06.1-rc in the test channel?

**Comment by cpuguy83** [comment] 2017-08-17 14:34
It looks like this is not a docker issue:

In the first case you are not using `nocopy`, so docker will try to copy the content from the image into the volume as normal (which does a `chown` operation, unsupported by your nfs server).

In the 2nd case, the mongo image is actually doing a chown and causing the same basic error.

If you don't want to support chown on the NFS server you'll need to change the image to not chown.
Otherwise you will need to use `no_root_squash` on the nfs export config on the nfs server.

**Comment by mahnunchik** [comment] 2017-08-17 15:23
Hi @cpuguy83 

Do I understand correctly that you recommend:
1. Do not use official images mongo/redis/elastic
1. Or turn off root squashing?

**Comment by cpuguy83** [comment] 2017-08-17 15:28
@mahnunchik That would be the two options. Since the official image is trying to chown and your volume implementation doesn't allow chowning in it's current form.

**Comment by mahnunchik** [comment] 2017-08-18 11:02
I've faced with the following behaviour after change `no_root_squash` on the server. 

```bash
docker volume create --driver local \
  --opt type=nfs \
  --opt o=addr=10.0.10.20,rw \
  --opt device=:/data/test-volume-1/ \
  foo

docker run -it --rm -v foo:/data/db mongo:3
```
Outputs
```
foo
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=dba4beddaec2
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] db version v3.4.7
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] git version: cf38c1b8a0a8dca4a11737581beafef4fe120bcd
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] modules: none
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] build environment:
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten]     distmod: debian81
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-08-18T10:51:17.988+0000 I CONTROL  [initandlisten] options: {}
2017-08-18T10:51:24.004+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to lock file: /data/db/mongod.lock No locks available. Is a mongod instance already running?, terminating
2017-08-18T10:51:24.004+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2017-08-18T10:51:24.004+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2017-08-18T10:51:24.004+0000 I CONTROL  [initandlisten] now exiting
2017-08-18T10:51:24.004+0000 I CONTROL  [initandlisten] shutting down with code:100
```
Mongo is able to `chmod` directory and create lock file, but fails to start...

Local NFS mount works as expected.

```bash
mount 10.0.6.47:/data/stage/test-volume-2/ /test/test-volume-2

docker run \
  -it \
  --rm \
  --mount type=bind,source=/test/test-volume-2,target=/data/db \
  mongo:3
```
Outputs:
```
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=fcde0820ff31
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] db version v3.4.7
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] git version: cf38c1b8a0a8dca4a11737581beafef4fe120bcd
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] modules: none
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] build environment:
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten]     distmod: debian81
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-08-18T10:53:52.207+0000 I CONTROL  [initandlisten] options: {}
2017-08-18T10:53:52.218+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7007M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] 
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] 
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] 
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] 
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-08-18T10:53:53.156+0000 I CONTROL  [initandlisten] 
2017-08-18T10:53:53.179+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2017-08-18T10:53:53.210+0000 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-08-18T10:53:53.210+0000 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-08-18T10:53:53.218+0000 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
2017-08-18T10:53:53.222+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
2017-08-18T10:53:53.222+0000 I NETWORK  [thread1] waiting for connections on port 27017
```
### Output of docker version:
```
$ docker version 
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by cpuguy83** [comment] 2017-08-18 12:58
This is just another issue with the NFS server.
See https://serverfault.com/questions/61594/what-does-no-locks-available-mean

You probably want to Google the error.

Closing as this is not a Docker issue.

**Closed by cpuguy83** 2017-08-18 12:58 UTC
Labels: version/17.06

**Comment by mahnunchik** [comment] 2017-08-18 13:37
@cpuguy83 if it is NFS error why second approach works without any problems?

```
mount 10.0.10.20:/data/stage/test-volume-2/ /test/test-volume-2

docker run \
  -it \
  --rm \
  --mount type=bind,source=/test/test-volume-2,target=/data/db \
  mongo:3
```

**Comment by cpuguy83** [comment] 2017-08-18 13:43
@mahnunchik The local driver is only passing through the mount options to the kernel. It literally does nothing else other than validation that the key's `type` and `device` exists.

I would check with what options your mount command mounted with.

**Comment by mahnunchik** [comment] 2017-08-21 04:47
Hi @cpuguy83 

### Volume

```bash
docker volume create --driver local \
  --opt type=nfs \
  --opt o=addr=10.0.10.20,rw \
  --opt device=:/data/test-volume-1/ \
  foo

docker run -it --rm -v foo:/data/db mongo:3
```

Produces:

```
:/data/test-volume-1/ on /var/lib/docker/volumes/foo/_data type nfs (rw,relatime,vers=3,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.0.10.20,mountvers=3,mountproto=tcp,local_lock=none,addr=10.0.10.20)
```

### Local mount

```bash
mount 10.0.10.20:/data/stage/test-volume-2/ /test/test-volume-2

docker run \
  -it \
  --rm \
  --mount type=bind,source=/test/test-volume-2,target=/data/db \
  mongo:3
```
Produces:

```
10.0.10.20:/data/test-volume-2 on /test/test-volume-2 type nfs4 (rw,relatime,vers=4.0,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.0.0.100,local_lock=none,addr=10.0.10.20)
```

**Comment by mahnunchik** [comment] 2017-08-23 07:16
Hi @cpuguy83 do you have any ideas why it works in one case and doesn't work in another?

**Comment by cpuguy83** [comment] 2017-08-23 08:08
I would start by specifying vers=4 instead of the default 3. If that's not it, check the rest of the options.

**Comment by mahnunchik** [comment] 2017-08-23 09:01
Hi @cpuguy83 

Exactly!

```
docker volume create --driver local \
  --opt type=nfs \
  --opt o=addr=10.0.10.20,rw,nfsvers=4 \
  --opt device=:/data/stage/test-volume-1/ \
  foo
```

Works as expected.

Why docker uses version 3 by dafault?

**Comment by cpuguy83** [comment] 2017-08-23 11:01
It doesn't use anything by default. It's what the kernel module sets by default.

**Comment by mahnunchik** [comment] 2017-08-23 11:05
The following command:
```
mount 10.0.10.20:/data/stage/test-volume-2/ /test/test-volume-2
```
without any additional options sets NFS version to 4.

**Comment by cpuguy83** [comment] 2017-08-23 11:08
The mount command does a lot of stuff, including executing a mount helper "mount.nfs"

I mentioned it before, but docker literally doesn't do anything with your options except validate that it has at least two specific fields. Other than that it is passed directly to the kernel.

**Comment by mahnunchik** [comment] 2017-08-23 11:15
Thank you for the clarification.

It would be nice to have mentioned in the documentation that it is better to specify NFS version `addr=10.0.10.20,rw,nfsvers=4`.
