### ISSUE TITLE
docker exec rpc issue on docker container restart

### ISSUE THREAD

**Issue by amolrajoba** [moby/moby#29704] opened 2016-12-26 12:24 UTC
**Description**

I am facing following rpc issue when i restart any container with 'docker restart <container_id>' command , this doesn't happen when i do 'docker stop <container_id>' and 'docker start <container_id>'

**Steps to reproduce the issue:**
1. docker restart <container_id>
2. docker exec -it  <container_id> bash

**Describe the results you received:**
```
docker exec -it <container_id> bash  
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:51:24 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:51:24 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 28
 Running: 24
 Paused: 0
 Stopped: 4
Images: 33
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-8:4-26869764-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.84 GB
 Data Space Total: 107.4 GB
 Data Space Available: 95.53 GB
 Metadata Space Used: 24.65 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.123 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.74 (2012-03-06)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge weavemesh null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.38-aff15
Operating System: Debian GNU/Linux 7 (wheezy)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 126.1 GiB
Name: soccer-node-01.adv.austin
ID: OKUZ:N6DE:MNWB:IEFF:7KT2:7JTG:QWWE:3DYI:ZKPT:TFBK:Q26X:FZK4
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
These are physical servers.

**Comment by tonistiigi** [comment] 2016-12-27 02:35
cc @mlaventure

**Comment by mlaventure** [comment] 2017-01-03 15:47
@amolrajoba if you can reproduce it consistently, could you activate the debug logs in the daemon, reproduce it an provide the daemon logs?

You can add `debug: true` to `/etc/docker/daemon.json` and send a `SIGHUP` to the daemon pid.

I had no luck reproducing it locally so far. Can you double check that the container is actually running after the restart operation too?

Thanks

**Comment by jayenashar** [comment] 2017-01-07 22:53
Having a similar issue since last night, but I haven't restarted my containers.  I added `debug: true` to `/etc/docker/daemon.json` and sent a `SIGHUP` to the `/usr/bin/dockerd` daemon pid.  Not sure where the debug log is supposed to appear.

docker exec -ti web bash

```
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"
```

docker info hangs


docker version

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64
```

i did upgrade some packages (debian i386 on physical machine with amd64 kernel) last night, but i don't see how they are relevant:

```
man-db:i386 2.7.0.2-5
mime-support:all 3.58
desktop-file-utils:i386 0.22-1
gnome-icon-theme:all 3.12.0-1
hicolor-icon-theme:all 0.13-1
shared-mime-info:i386 1.5-2~bpo8+1
fontconfig:i386 2.11.0-6.3+deb8u1
libc-bin:i386 2.19-18+deb8u6
menu:i386 2.1.47
libpcsclite1:i386 1.8.13-1+deb8u1
libpcsclite1:amd64 1.8.13-1+deb8u1
uno-libs3:i386 5.2.4-2~bpo8+1
ure:i386 5.2.4-2~bpo8+1
fonts-opensymbol:all 2:102.7+LibO5.2.4-2~bpo8+1
libvncclient0:i386 0.9.9+dfsg2-6.1+deb8u2
libvncserver0:i386 0.9.9+dfsg2-6.1+deb8u2
librpmio3:i386 4.12.0.2+dfsg1-1~bpo8+1
librpm3:i386 4.12.0.2+dfsg1-1~bpo8+1
librpmbuild3:i386 4.12.0.2+dfsg1-1~bpo8+1
librpmsign3:i386 4.12.0.2+dfsg1-1~bpo8+1
rpm-common:i386 4.12.0.2+dfsg1-1~bpo8+1
rpm2cpio:i386 4.12.0.2+dfsg1-1~bpo8+1
debugedit:i386 4.12.0.2+dfsg1-1~bpo8+1
rpm:i386 4.12.0.2+dfsg1-1~bpo8+1
inkscape:i386 0.91-12~bpo8+2
xserver-xorg-video-intel:i386 2:2.99.917+git20161206-1~bpo8+1
libreoffice-common:all 1:5.2.4-2~bpo8+1
libreoffice-style-galaxy:all 1:5.2.4-2~bpo8+1
libreoffice-style-tango:all 1:5.2.4-2~bpo8+1
libreoffice-style-oxygen:all 1:5.2.4-2~bpo8+1
libreoffice-core:i386 1:5.2.4-2~bpo8+1
libreoffice-base-drivers:i386 1:5.2.4-2~bpo8+1
libreoffice-base-core:i386 1:5.2.4-2~bpo8+1
libreoffice-base:i386 1:5.2.4-2~bpo8+1
libreoffice-calc:i386 1:5.2.4-2~bpo8+1
libreoffice-draw:i386 1:5.2.4-2~bpo8+1
libreoffice-impress:i386 1:5.2.4-2~bpo8+1
libreoffice-kde:i386 1:5.2.4-2~bpo8+1
python3-uno:i386 1:5.2.4-2~bpo8+1
libreoffice-java-common:all 1:5.2.4-2~bpo8+1
libreoffice-sdbc-hsqldb:i386 1:5.2.4-2~bpo8+1
libreoffice-report-builder-bin:i386 1:5.2.4-2~bpo8+1
libreoffice-math:i386 1:5.2.4-2~bpo8+1
libreoffice-writer:i386 1:5.2.4-2~bpo8+1
libreoffice-avmedia-backend-gstreamer:i386 1:5.2.4-2~bpo8+1
libreoffice:i386 1:5.2.4-2~bpo8+1
libreoffice-help-en-us:all 1:5.2.4-2~bpo8+1
libc-bin:i386 2.19-18+deb8u6
man-db:i386 2.7.0.2-5
python-xmltodict:all 0.9.0-1
ansible:all 2.2.0.0-1~bpo8+1
```

**Comment by justincormack** [comment] 2017-01-07 23:11
i386 is an untested and unsupported environment, all the docker packages
are 64 bit. You can probably strace it to see what is going wrong.

**Comment by jayenashar** [comment] 2017-01-07 23:42
oddly it hangs with `strace`.  i know i386 is unsupported but it's been working since september when i installed 1.12.0.  my system is more like multiarch than pure i386, and i have the required amd64 dependencies.  it's very strange since the containers run fine, i just can't `exec` in the running container.  `run` a new one works fine.

**Comment by mlaventure** [comment] 2017-01-09 17:59
Unfortunately `runc` is not compatible with `strace` and will often hangs (see https://github.com/opencontainers/runc/issues/1025)

**Comment by amolrajoba** [comment] 2017-01-13 09:13
@mlaventure  i can't make debug active on production environment. 

I will try to simulate environment somewhere else to provide you the debug log

**Comment by sluther** [comment] 2017-01-16 22:00
I'm having this issue too. I'm running docker inside of a vagrant VM running Ubuntu Trusty.

`vagrant@vagrant-ubuntu-trusty-64:/vagrant$ docker-compose exec mysql bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"`

I enabled debug mode. Here is my log:

`time="2017-01-16T21:59:39.327504998Z" level=debug msg="Calling GET /v1.22/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dvagrant%22%2C+%22com.docker.compose.service%3Dmysql%22%2C+%22com.docker.compose.oneoff%3DFalse%22%2C+%22com.docker.compose.container-number%3D1%22%5D%7D&size=0"
time="2017-01-16T21:59:39.330145621Z" level=debug msg="Calling POST /v1.22/containers/0dc457a46e46500ff60d8e23a7f4b639bdf956af211aaf24a597af617458e503/exec"
time="2017-01-16T21:59:39.330230780Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"bash\"],\"Container\":\"0dc457a46e46500ff60d8e23a7f4b639bdf956af211aaf24a597af617458e503\",\"Privileged\":false,\"Tty\":true}"
time="2017-01-16T21:59:39.333375451Z" level=debug msg="Calling POST /v1.22/exec/20cd0841c310773f6adf64601262fd3e12f092a0b027df4de685f6c048b66c6b/start"
time="2017-01-16T21:59:39.333444356Z" level=debug msg="form data: {\"Detach\":false,\"Tty\":true}"
time="2017-01-16T21:59:39.333550092Z" level=debug msg="starting exec command 20cd0841c310773f6adf64601262fd3e12f092a0b027df4de685f6c048b66c6b in container 0dc457a46e46500ff60d8e23a7f4b639bdf956af211aaf24a597af617458e503"
time="2017-01-16T21:59:39.333777237Z" level=debug msg="attach: stdin: begin"
time="2017-01-16T21:59:39.333873792Z" level=debug msg="attach: stdout: begin"
time="2017-01-16T21:59:39.335760477Z" level=debug msg="Calling GET /v1.22/exec/20cd0841c310773f6adf64601262fd3e12f092a0b027df4de685f6c048b66c6b/json"
time="2017-01-16T21:59:39.338942494Z" level=debug msg="Calling POST /v1.22/exec/20cd0841c310773f6adf64601262fd3e12f092a0b027df4de685f6c048b66c6b/resize?h=25&w=80"
time="2017-01-16T21:59:39.433481672Z" level=error msg="Error running exec in container: rpc error: code = 13 desc = invalid header field value \"oci runtime error: exec failed: container_linux.go:247: starting container process caused \\\"process_linux.go:75: starting setns process caused \\\\\\\"fork/exec /proc/self/exe: no such file or directory\\\\\\\"\\\"\\n\""
time="2017-01-16T21:59:39.433592861Z" level=debug msg="Closing buffered stdin pipe"
time="2017-01-16T21:59:39.433667337Z" level=debug msg="attach: stdin: end"
time="2017-01-16T21:59:39.433684285Z" level=debug msg="attach: stdout: end"
time="2017-01-16T21:59:39.435091403Z" level=error msg="Handler for POST /v1.22/exec/20cd0841c310773f6adf64601262fd3e12f092a0b027df4de685f6c048b66c6b/resize returned error: rpc error: code = 2 desc = containerd: process not found for container"
time="2017-01-16T21:59:39.437753473Z" level=debug msg="Calling GET /v1.22/exec/20cd0841c310773f6adf64601262fd3e12f092a0b027df4de685f6c048b66c6b/json"`

**Comment by sluther** [comment] 2017-02-17 08:06
I found out that if I issue `docker-compose stop mysql && docker-compose start mysql`, the issue goes away. If I try `docker-compose restart mysql` however, once the error pops up, it remains until stopping and starting.

**Comment by cesarjorgemartinez** [comment] 2017-02-22 18:13
I'm having this issue too.
With centos 7, docker 1.12.5 (currently), last packages updates
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"

Trying to access a container (docker exec container ls) previouly started
Container type:
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

**Comment by sluther** [comment] 2017-02-22 20:13
@cesarjorgemartinez what happens when you stop and then start the container again? I'm curious if that fixes the issue for you as well.

**Comment by wallnerryan** [comment] 2017-02-23 02:03
Happened to me with 1.12.6 on centos 7. Container stop then start fixes it for me as well, but restart does not as stated above @sluther

**Comment by sluther** [comment] 2017-02-23 02:46
As I suspected, there is an issue in the restart process. Something in there is different from what happens when a container is stopped and then started again.

**Comment by cesarjorgemartinez** [comment] 2017-02-23 09:27
I need to stop and start. Restart is failed.
When try restart, I see in /var/log/messages:
dockerd-current: time="" level=error msg="Error unmounting container ...: Device is Busy"
Any ideas to workaround apart from stop and start container?

**Comment by cesarjorgemartinez** [comment] 2017-02-24 09:00
I detected and fixed the problem.
Is a bug with docker exec bash -c "text". Should check the docker exec well and take corrections in the version of docker 12 for centos.
If we use a big bash -c "text", cannot parse correctly and breaks things in docker disk devices.
I was doing this:
A="$(cat file1)"
sudo docker exec container /bin/bash -c "if ! grep 'xxx' /file2;then echo \"$A\" >> /file2;fi"

**Comment by chicol** [comment] 2017-03-18 08:07
I have the same issue with centos7,docker 1.12.5.
I have two docker envirment with different storage dirve.
The one with direct-lvm devicemapper drive can reproduced this issue, and another one with loop-lvm is ok.

Here is my configuration:
`Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64
[root@server15 ~]# docker info
Containers: 29
 Running: 29
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 11.47 GB
 Data Space Total: 385.6 GB
 Data Space Available: 374.1 GB
 Metadata Space Used: 4.133 MB
 Metadata Space Total: 4.056 GB
 Metadata Space Available: 4.052 GB
 Thin Pool Minimum Free Space: 38.56 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 24
Total Memory: 62.75 GiB
Name: server15
ID: W66J:W5OW:X2VZ:DBGR:BMZN:OIEY:R2IR:SP22:NWP5:ST57:5TWB:SJN3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 docker.zifang.com
 127.0.0.0/8
Registries: docker.io (secure)`

when i issue cmd "docker restart <container>", /var/log/message display as following:
`Mar 18 16:04:24 server15 dockerd-current: time="2017-03-18T16:04:24.865892889+08:00" level=info msg="{Action=restart, Username=root, LoginUID=0, PID=15858}"
Mar 18 16:04:34 server15 dockerd-current: time="2017-03-18T16:04:34.886656197+08:00" level=info msg="Container 8da7038fa888c97a38ab048fa995d83a2e3da3f2711b790a425ea534e4969e54 failed to exit within 10 seconds of signal 15 - using the force"
Mar 18 16:04:34 server15 systemd: Scope libcontainer-15865-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:34 server15 systemd: Scope libcontainer-15865-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:34 server15 systemd: Scope libcontainer-15870-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:34 server15 systemd: Scope libcontainer-15870-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:34 server15 systemd: Scope libcontainer-15886-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:34 server15 systemd: Scope libcontainer-15886-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:34 server15 journal: #033]0;@8da7038fa888:/#007#033[?1034h[root@8da7038fa888 /]# 
Mar 18 16:04:34 server15 dockerd-current: time="2017-03-18T16:04:34.949124370+08:00" level=warning msg="failed to close stdin: rpc error: code = 2 desc = containerd: container not found"
Mar 18 16:04:34 server15 kernel: docker0: port 1(vethce66dca) entered disabled state
Mar 18 16:04:34 server15 kernel: docker0: port 1(vethce66dca) entered disabled state
Mar 18 16:04:34 server15 NetworkManager[986]: <info>  [1489824274.9725] manager: (veth9adf9ee): new Veth device (/org/freedesktop/NetworkManager/Devices/34)
Mar 18 16:04:34 server15 kernel: device vethce66dca left promiscuous mode
Mar 18 16:04:34 server15 kernel: docker0: port 1(vethce66dca) entered disabled state
Mar 18 16:04:34 server15 NetworkManager[986]: <info>  [1489824274.9798] device (veth9adf9ee): driver 'veth' does not support carrier detection.
Mar 18 16:04:34 server15 NetworkManager[986]: <info>  [1489824274.9801] device (vethce66dca): driver 'veth' does not support carrier detection.
Mar 18 16:04:34 server15 kernel: XFS (dm-7): Unmounting Filesystem
Mar 18 16:04:35 server15 kernel: XFS (dm-7): Mounting V5 Filesystem
Mar 18 16:04:35 server15 kernel: XFS (dm-7): Ending clean mount
Mar 18 16:04:35 server15 kernel: device vethfcd9646 entered promiscuous mode
Mar 18 16:04:35 server15 kernel: IPv6: ADDRCONF(NETDEV_UP): vethfcd9646: link is not ready
Mar 18 16:04:35 server15 kernel: docker0: port 1(vethfcd9646) entered forwarding state
Mar 18 16:04:35 server15 kernel: docker0: port 1(vethfcd9646) entered forwarding state
Mar 18 16:04:35 server15 NetworkManager[986]: <info>  [1489824275.1355] manager: (vethfc9deca): new Veth device (/org/freedesktop/NetworkManager/Devices/35)
Mar 18 16:04:35 server15 NetworkManager[986]: <info>  [1489824275.1373] manager: (vethfcd9646): new Veth device (/org/freedesktop/NetworkManager/Devices/36)
Mar 18 16:04:35 server15 systemd: Scope libcontainer-15922-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:35 server15 systemd: Scope libcontainer-15922-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:35 server15 systemd: Started docker container 8da7038fa888c97a38ab048fa995d83a2e3da3f2711b790a425ea534e4969e54.
Mar 18 16:04:35 server15 systemd: Starting docker container 8da7038fa888c97a38ab048fa995d83a2e3da3f2711b790a425ea534e4969e54.
Mar 18 16:04:35 server15 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethfcd9646: link becomes ready
Mar 18 16:04:35 server15 NetworkManager[986]: <info>  [1489824275.2622] device (vethfc9deca): driver 'veth' does not support carrier detection.
Mar 18 16:04:35 server15 NetworkManager[986]: <info>  [1489824275.2625] device (vethfcd9646): link connected
Mar 18 16:04:35 server15 NetworkManager[986]: <info>  [1489824275.2626] device (docker0): link connected
Mar 18 16:04:35 server15 systemd: Scope libcontainer-15953-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:35 server15 systemd: Scope libcontainer-15953-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:04:50 server15 kernel: docker0: port 1(vethfcd9646) entered forwarding state

Mar 18 16:06:36 server15 dockerd-current: time="2017-03-18T16:06:36.788111972+08:00" level=info msg="{Action=exec, Username=root, LoginUID=0, PID=15983}"
Mar 18 16:06:36 server15 dockerd-current: time="2017-03-18T16:06:36.789128015+08:00" level=info msg="{Action=start, Username=root, LoginUID=0, PID=15983}"
Mar 18 16:06:36 server15 dockerd-current: time="2017-03-18T16:06:36.789901615+08:00" level=info msg="{Action=resize, Username=root, LoginUID=0, PID=15983}"
Mar 18 16:06:36 server15 systemd: Scope libcontainer-15999-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:06:36 server15 systemd: Scope libcontainer-15999-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar 18 16:06:36 server15 dockerd-current: time="2017-03-18T16:06:36.842007858+08:00" level=error msg="Error running exec in container: rpc error: code = 13 desc = invalid header field value \"oci runtime error: exec failed: container_linux.go:247: starting container process caused \\\"process_linux.go:75: starting setns process caused \\\\\\\"fork/exec /proc/self/exe: no such file or directory\\\\\\\"\\\"\\n\""
Mar 18 16:06:36 server15 dockerd-current: time="2017-03-18T16:06:36.842542440+08:00" level=error msg="Handler for POST /v1.24/exec/4ebd2ae951ccce6ece09f73c1bd14547cf7401f87ad0b0407cb569001a2f0370/resize returned error: rpc error: code = 2 desc = containerd: process not found for container"`

**Comment by thaJeztah** [comment] 2017-03-18 11:51
@chicol looks like you're running the Red Hat fork of docker; are you seeing the same problem when running the official package (https://docs.docker.com/engine/installation/linux/centos/, or https://docs.docker.com/v1.12/engine/installation/linux/centos/)?

**Comment by chicol** [comment] 2017-03-20 02:20
@thaJeztah It's ok with official package, thanks.

**Comment by thaJeztah** [comment] 2017-03-21 17:44
There's a lot of different use cases reported here; is this still an issue for anyone here, or is it resolved for everyone?

**Comment by wallnerryan** [comment] 2017-03-22 15:39
We still see it often. CentOS 7. Our management plane restarts containers during any reconfiguration and only happens it seems after restart. Also, at this time, we cannot upgrade docker.

```
Containers: 38
 Running: 38
 Paused: 0
 Stopped: 0
Images: 37
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 11.37 GB
 Data Space Total: 99.61 GB
 Data Space Available: 88.24 GB
 Metadata Space Used: 5.407 MB
 Metadata Space Total: 1.044 GB
 Metadata Space Available: 1.039 GB
 Thin Pool Minimum Free Space: 9.961 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.6 GiB
Name: oscont110
ID: 4AH6:JMUN:NNRM:AX7D:RGRO:PY34:NKUG:QNMQ:SVD7:IFC4:272K:QFCK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2017-03-22 15:59
@wallnerryan do you have a simple-as-possible way to reproduce?

**Comment by wallnerryan** [comment] 2017-03-24 11:29
No, it seems that a `docker restart` sometimes causes this, but a stop and subsequent start dont always fix needing a restart of the daemon. I will try and find a reproducible example.

**Comment by sluther** [comment] 2017-03-24 16:02
@thaJeztah This is still happening for me. I've provided as much information as I'm able to. As I mentioned, my solution was to switch to using `docker-compose stop` and `docker-compose start`, instead of `docker-compose restart`.

**Comment by panuhorsmalahti** [comment] 2017-03-29 08:20
Happening to me too on RHEL and RHEL's Docker version 1.12.5, build 047e51b/1.12.5 on Linux 3.10.0-514.6.1.el7.x86_64.

**Comment by spathare21** [comment] 2017-05-05 04:16
I am also getting same issue while

docker exec -it container_name bash. 

rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""

**Comment by thaJeztah** [comment] 2017-05-05 23:52
@spathare21 are you sure `bash` is installed in that container? If not, that message is simply telling you that `bash` is not installed, try using `sh` instead

**Comment by holstvoogd** [comment] 2017-05-08 14:47
I've ran into this after restarting the docker deamon (with live-restore).
After stopping the 'broken' containers and starting them again, all is well.

I'm on Docker version 1.12.6, build 7392c3b/1.12.6

**Comment by derbeneviv** [comment] 2017-05-22 14:01
same here
centos7/docker 1.12.6
`docker info
Containers: 12
 Running: 9
 Paused: 0
 Stopped: 3
Images: 20
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-100689086-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.154 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.48 GB
 Metadata Space Used: 4.633 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 15
Total Memory: 147.4 GiB
Name: system-monitor
ID: S2VC:FF5S:QVPY:25LE:7T5F:OK6V:TXWW:ULO4:YG4P:3EJG:G7LB:5KPQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
`

**Comment by cristianokbc** [comment] 2017-08-11 14:13
Same here. RHEL 7.2

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 3.672 GB
 Data Space Total: 21.36 GB
 Data Space Available: 17.69 GB
 Metadata Space Used: 1.503 MB
 Metadata Space Total: 54.53 MB
 Metadata Space Available: 53.02 MB
 Thin Pool Minimum Free Space: 2.136 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: syslog
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host bridge null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.656 GiB
Name: sbcdf97f.bcnet.bcb.gov.br
ID: KMNO:UD6L:6GN6:7IS6:RIYL:G46R:46OE:T7NY:OY7T:JYAH:Y6CA:EH5N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Comment by elianka** [comment] 2017-08-12 01:08
+1

**Comment by carlosoliv** [comment] 2017-08-18 19:56
+1

**Comment by thaJeztah** [comment] 2017-09-18 18:56
It looks like everyone reporting this issue now is running the Red Hat fork of Docker; are you able to reproduce this issue on an official version of docker (https://docs.docker.com/engine/installation/)?

**Comment by ilovers** [comment] 2017-09-30 09:24
+1

**Comment by bgaillard** [comment] 2017-10-02 17:47
Hi, I also encountered this problem today. 

In our case it seems that one of our developers changed the end of line of the Bash script which was executed. The script we executed was a Bash script but the developer accidentally changed end of lines to Windows end of lines. 

Replacing end of line to Unix ones solved the problem in our case.

```
dos2unix my-script.sh
```

Hope this helps.

**Comment by kingAndGithub** [comment] 2017-10-24 03:27
**i still have the problem on centos7.2 and the docker info is 1.12.6 after i restart the docker deamon:**
### rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"

**Comment by thaJeztah** [comment] 2017-10-24 15:53
It looks like all people reporting this now are running (the Red Hat Fork of) 1.12.6. Docker 1.12.6 has reached end of life, and I have not seen this issue reported with any current version of the official docker packages, so I'll close this issue.

If you cannot upgrade to an official package of docker, and are running the Red Hat packages, please report your issue in their issue tracker: https://bugzilla.redhat.com/index.cgi

If you're encountering this problem on a current version of docker, please open a new issue and provide the information that's requested in the issue template. I'm locking the conversation on this issue to prevent it from collecting unrelated issues, or problems that have already been resolved.

**Closed by thaJeztah** 2017-10-24 15:53 UTC
Labels: area/runtime, status/more-info-needed, version/1.12
