### ISSUE TITLE
Docker ignores `net.ipv4.ip_local_port_range`

### ISSUE THREAD

**Issue by dluc** [moby/moby#36070] opened 2018-01-20 01:16 UTC
**Description**

After setting `net.ipv4.ip_local_port_range` to `15000 65000`, docker instances still see and use the default value `32768	60999`

**Steps to reproduce the issue:**
1. Create a VM in Azure
2. Install Docker (`Docker version 18.01.0-ce, build 03596f5`)
3. Check the current port range: `cat /proc/sys/net/ipv4/ip_local_port_range` returns `32768	60999`
4. Change the port range: `sysctl -w net.ipv4.ip_local_port_range="15000 65000"`
5. Reboot (just in case)
6. Check the current port range: `cat /proc/sys/net/ipv4/ip_local_port_range` returns `15000 65000`
7. Run a Docker image and connect to it with `docker exec -it <id> /bin/bash`
8. Check the port range: `cat /proc/sys/net/ipv4/ip_local_port_range` returns `32768	60999`

**Describe the results you expected:**

The last step should return the `15000 65000` setting inherited from the host.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried to build a Docker image where `/etc/sysctl.conf` contains the desired configuration (`net.ipv4.ip_local_port_range=15000 65000`), but the result is still the same.

**Output of `docker version`:**

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:11:05 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:09:37 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65GiB
Name: vm-zknxc
ID: YIRN:DT74:E5U2:2ZMB:CGV2:KNX6:USKA:VZDS:LCCA:ZES3:U5CP:SEM7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure VM, Standard D4 v3 (4 vcpus, 16 GB memory)

**Comment by thaJeztah** [comment] 2018-01-20 02:01
Yes, that's expected. Containers have their own networking namespace, and these systctls are namespaced.

You can use the `--sysctl` option (see [Configure namespaced kernel parameters (sysctls) at runtime](https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime)) to configure this for the container's networking namespace, e.g.:

Without `--sysctl`;

```bash
$ docker run --rm busybox cat /proc/sys/net/ipv4/ip_local_port_range
32768	60999
```

And with:

```bash
$ docker run --rm --sysctl net.ipv4.ip_local_port_range="15000 65000" busybox cat /proc/sys/net/ipv4/ip_local_port_range
15000	65000
```


Closing this issue, because this is not a bug, but feel free to continue the conversation :+1:

**Closed by thaJeztah** 2018-01-20 02:01 UTC

**Comment by dluc** [comment] 2018-01-20 02:43
Thank you @thaJeztah that worked and fortunately Docker Compose supports that too, now I only need to upgrade DC (the Docker extension for Azure VM installs DC 2.0, and sysctls was introduced in 2.1).
