### ISSUE TITLE
Docker does not start 

### ISSUE THREAD

**Issue by r-a-x** [moby/moby#34104] opened 2017-07-14 00:32 UTC
**Description**
I installed the docker, and it was running perfectly, but one day I started getting the error after starting the docker. I uninstalled the docker deleted its conf file and still the issue persists.

After running
 ```
systemctl restart docker
```
I started getting <b>Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details</b>.

and the output of 
```
systemctl status docker.service 
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Fri 2017-07-14 05:35:02 IST; 5min ago
     Docs: https://docs.docker.com
  Process: 15149 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 15149 (code=exited, status=1/FAILURE)

Jul 14 05:35:02 iblldevrahulb systemd[1]: Failed to start Docker Application Container Engine.
Jul 14 05:35:02 iblldevrahulb systemd[1]: docker.service: Unit entered failed state.
Jul 14 05:35:02 iblldevrahulb systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 14 05:35:02 iblldevrahulb systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 14 05:35:02 iblldevrahulb systemd[1]: Stopped Docker Application Container Engine.
Jul 14 05:35:02 iblldevrahulb systemd[1]: docker.service: Start request repeated too quickly.
Jul 14 05:35:02 iblldevrahulb systemd[1]: Failed to start Docker Application Container Engine.
![docker](https://user-images.githubusercontent.com/8466045/28193387-ebda1394-6859-11e7-8b1d-ccdb7ef7795f.png)

**Results expected:**
Docker Startup

**Results got:**
 Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details

**Output of `docker version`:**

```
 Docker version 17.06.0-ce, build 02c1d87

```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```

**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
**

**Comment by milindchawre** [comment] 2017-07-17 05:10
@r-a-x can you check this comment it might help https://github.com/moby/moby/issues/33931#issuecomment-313244745

**Comment by cpuguy83** [comment] 2017-07-17 15:12
Please provide the docker logs `journalctl -fu docker`

**Comment by tsunaminoai** [comment] 2017-07-21 20:39
I've run into the same issue. The host that the docker service was running on rebooted and the docker service will no longer start. Logs are the same as above. No indication as to underlying issue.

> root@rin tsunami $ systemctl status docker.service
> * docker.service - Docker Application Container Engine
>    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Fri 2017-07-21 16:27:48 EDT; 52s ago
>      Docs: https://docs.docker.com
>   Process: 3327 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
>  Main PID: 3327 (code=exited, status=1/FAILURE)
>       CPU: 164ms
> 
> Jul 21 16:27:48 rin systemd[1]: docker.service: Unit entered failed state.
> Jul 21 16:27:48 rin systemd[1]: docker.service: Failed with result 'exit-code'.
> Jul 21 16:27:48 rin systemd[1]: docker.service: Service hold-off time over, scheduling restart.
> Jul 21 16:27:48 rin systemd[1]: Stopped Docker Application Container Engine.
> Jul 21 16:27:48 rin systemd[1]: docker.service: Start request repeated too quickly.
> Jul 21 16:27:48 rin systemd[1]: Failed to start Docker Application Container Engine.
> Jul 21 16:27:48 rin systemd[1]: docker.service: Unit entered failed state.
> Jul 21 16:27:48 rin systemd[1]: docker.service: Failed with result 'exit-code'.


> root@rin tsunami $ journalctl -fu docker
> -- Logs begin at Fri 2017-07-21 16:16:28 EDT. --
> Jul 21 16:31:02 rin systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
> Jul 21 16:31:02 rin systemd[1]: Failed to start Docker Application Container Engine.
> Jul 21 16:31:02 rin systemd[1]: docker.service: Unit entered failed state.
> Jul 21 16:31:02 rin systemd[1]: docker.service: Failed with result 'exit-code'.
> Jul 21 16:31:02 rin systemd[1]: docker.service: Service hold-off time over, scheduling restart.
> Jul 21 16:31:02 rin systemd[1]: Stopped Docker Application Container Engine.
> Jul 21 16:31:02 rin systemd[1]: docker.service: Start request repeated too quickly.
> Jul 21 16:31:02 rin systemd[1]: Failed to start Docker Application Container Engine.
> Jul 21 16:31:02 rin systemd[1]: docker.service: Unit entered failed state.
> Jul 21 16:31:02 rin systemd[1]: docker.service: Failed with result 'exit-code'.

**Comment by Xqua** [comment] 2017-09-11 16:26
Exact same issue.

Tried to wipe /var/lib/docker  too...
No effect..

**Comment by krishnaghatti** [comment] 2017-09-12 06:06
seeing similar behaviour.

**Comment by r-a-x** [comment] 2017-09-12 06:53
I found that there are two ways to have config files in docker files, and I was using both at the same time. so If you use only one way to configure docker it should work. I will update more details soon.

**Comment by michaelkrog** [comment] 2017-10-05 13:41
I am seeing same behaviour. Have 5 nodes installed with same ubuntu version and same docker version. I have worked fine for months.

I just upgradeded them all to 17.09 during a period when the whole swarm had lost physical access to each other. Now the master cannot start the docker daemon anymore and I get the exact same output as above(no real info). All the other nodes still works fine.

Tried to wipe /var/lib/docker and reinstall docker, but it does not help.

**Comment by cpuguy83** [comment] 2017-10-05 13:46
@MichaelCurrie 

> Please provide the docker logs journalctl -fu docker

**Comment by cpuguy83** [comment] 2017-10-05 13:47
Please do not post a "me too" unless you can post logs from journalctl: `journalctl -fu docker`

**Comment by michaelkrog** [comment] 2017-10-05 13:51
Ok.. Finally.  

Its the same issue as @r-a-x 
I use daemon.json to open up for secure remote access. But when docker-ce is installed it will by default have `ExecStart=/usr/bin/dockerd -H fd://` in /lib/systemd/system/docker.service. 

If I change that to `ExecStart=/usr/bin/dockerd` then it starts again.

The output from `journalctl -fu docker` when the error occurs is this:
```
-- Logs begin at Thu 2017-10-05 15:43:10 CEST. --
Oct 05 15:49:30 engine1 systemd[1]: Starting Docker Application Container Engine...
Oct 05 15:49:30 engine1 dockerd[2067]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [fd://], from file: [fd:// tcp://0.0.0.0:2376])
Oct 05 15:49:30 engine1 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Oct 05 15:49:30 engine1 systemd[1]: Failed to start Docker Application Container Engine.
Oct 05 15:49:30 engine1 systemd[1]: docker.service: Unit entered failed state.
Oct 05 15:49:30 engine1 systemd[1]: docker.service: Failed with result 'exit-code'.
Oct 05 15:49:30 engine1 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Oct 05 15:49:30 engine1 systemd[1]: Stopped Docker Application Container Engine.
Oct 05 15:49:30 engine1 systemd[1]: docker.service: Start request repeated too quickly.
Oct 05 15:49:30 engine1 systemd[1]: Failed to start Docker Application Container Engine.
```

That the double config prevents the daemon from starting I think must be something new between 17.05 and 17.09. I did not have the issue when on 17.05 with the same config.

**Comment by cpuguy83** [comment] 2017-10-05 13:55
@michaelkrog Thanks!!!

So yes if a config from the CLI flags conflicts with the config json, it will error out. But this is not new and has happened since the daemon config from file was introduced.

What distrois this on? Do you have any custom systemd unit files for docker? Is this a normal install from RPM, installed from docker-machine, something else?

**Comment by michaelkrog** [comment] 2017-10-05 14:12
This is ubuntu 16.04. It has been installed directly on the host via physical access.

It is a pretty plain installation. The nodes are used for nothing but docker and I have not tangled with systemd besides changing `/lib/systemd/system/docker.service`.

**Comment by cpuguy83** [comment] 2017-10-05 15:10
> besides changing /lib/systemd/system/docker.service

I assume this change is the above mentioned change to make docker start?

**Comment by michaelkrog** [comment] 2017-10-05 22:29
Correct!

**Comment by thaJeztah** [comment] 2017-10-06 00:00
Looks like the issues reported were due to the configuration, so I'll close this issue as it's not a bug,

**Closed by thaJeztah** 2017-10-06 00:00 UTC

**Comment by michaelkrog** [comment] 2017-10-10 07:21
@thaJeztah I agree that it was a config issue, but is there a reason that the default installation has a flag for listening on `fd://` instead of using daemon.json on ubuntu? I think it would less confusing for those who want to have secure remote access.

**Comment by masonb81** [comment] 2018-01-26 08:46
I had this issue, it was a typo in  my /etc/docker/daemon.json file

**Comment by MrMetric** [comment] 2018-01-30 03:40
I had this problem on Arch when the installed Linux version did not match the running Linux version (a frequent source of issues)

**Comment by yonathanF** [comment] 2018-03-05 05:17
@MrMetric I'm having the same issue (also on Arch). How did you resolve it?

**Comment by MrMetric** [comment] 2018-03-06 19:16
You can see if you have this issue by checking if the running kernel version reported by `uname -r` does not match the installed version reported by `pacman -Q linux`. Issues relating to a kernel version mismatch can often be solved by installing the old kernel from pacman's cache (`pacman -U /var/cache/pacman/pkg/linux-VERSION-x86_64.pkg.tar.xz`). You might need to restart the misbehaving program (in this case, the Docker daemon). If that does not work, install the new kernel again and reboot.

My advice is to always reboot when you have updated the kernel. If you can not reboot, do not update the kernel. If you do not reboot, your flash drives or other USB-connected external storage devices will not work, and other things will mysteriously stop working (for example, a while ago, it caused a graphics driver issue and I could not start my OpenGL program).

@yonathanF I hope that helps!

**Comment by yonathanF** [comment] 2018-03-06 21:16
Thanks for the help! Learned "reboot after a kernel update"  the hard way. Rebooting fixed the issue.

**Comment by eastpav** [comment] 2018-08-14 06:40
I have the same problem. And  /etc/docker/daemon.json existed. delete it , and systemctl start docker.service works.

**Comment by siyavashvafshar** [comment] 2018-08-14 15:43
Hi guys, I had same problem finally executed /usr/bin/dockerd to start docker daemon manually , it failed and at the end of log there was this message :
"Your Linux kernel version 2.6.32-042stab130.1 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer"
if you see something like this , just upgrade to newer kernel and it will be solved.

**Comment by rstacruz** [comment] 2018-09-10 05:58
Having this issue too! To those stumbling upon this, try to start Docker directly like so:

```
sudo /usr/bin/dockerd
```

It should show you a bit more information on why it may be failing.

**Comment by ivnilv** [comment] 2018-11-05 13:40
> You can see if you have this issue by checking if the running kernel version reported by `uname -r` does not match the installed version reported by `pacman -Q linux`. Issues relating to a kernel version mismatch can often be solved by installing the old kernel from pacman's cache (`pacman -U /var/cache/pacman/pkg/linux-VERSION-x86_64.pkg.tar.xz`). You might need to restart the misbehaving program (in this case, the Docker daemon). If that does not work, install the new kernel again and reboot.
> 
> My advice is to always reboot when you have updated the kernel. If you can not reboot, do not update the kernel. If you do not reboot, your flash drives or other USB-connected external storage devices will not work, and other things will mysteriously stop working (for example, a while ago, it caused a graphics driver issue and I could not start my OpenGL program).
> 
> @yonathanF I hope that helps!

That worked on Manjaro Linux 18/Arch.

The only thing is , I had to go to the Manjaro Settings Manager and actually Remove all other kernels, leaving just the one reported by `uname -r`.

Thanks a lot !

**Comment by TechMaster** [comment] 2018-11-09 11:20
I removed /etc/docker/daemon.json then it works again !
sudo rm /etc/docker/daemon.json

**Comment by Codelica** [comment] 2018-11-25 19:44
Ran into this with Ubuntu 18.  As mentioned, the conflict between the ExecStart line in /lib/systemd/system/docker.service and my daemon.json for "hosts" was the issue.  In Ubuntu 18, docker.service has unix:// and in my daemon.json I had fd:// and a tcp socket.  Changing my config from fd:// to unix:// allowed docker to start.

**Comment by DanielChan27** [comment] 2019-12-11 08:35
> I have the same problem. And /etc/docker/daemon.json existed. delete it , and systemctl start docker.service works.

it really works，I think it was my fault by execing `systemctl enable docker.service` duplicatly.

**Comment by johanastborg** [comment] 2020-06-15 13:08
Had the same problem, but I solved it by:
`sudo rm -rf /var/run/docker.pid`

**Comment by WSMathias** [comment] 2020-07-08 18:38
> Had the same problem, but I solved it by:
> `sudo rm -rf /var/run/docker.pid`
Only this one worked (ubuntu 20.04)

**Comment by karl-gustav** [comment] 2020-09-09 19:22
I solved it by running `sudo chmod 666 /var/run/docker.sock`

Got the solution here: [www.digitalocean.com/...](https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket)

**Comment by thaJeztah** [comment] 2020-09-09 19:34
@karl-gustav I'd strongly discourage giving "world" permissions to the docker socket; anyone that has access to that socket effectively has full `root` access on the host; in your case; _every_ user will get root access; see "docker daemon attack surface" in the docs https://docs.docker.com/engine/security/security/

**Comment by Vickey-Wu** [comment] 2020-09-22 06:27
> I removed /etc/docker/daemon.json then it works again !
> sudo rm /etc/docker/daemon.json

it work for me

**Comment by Bill0412** [comment] 2020-12-02 02:54
> /etc/docker/daemon.json
![image](https://user-images.githubusercontent.com/33972245/100822127-ae57fd80-348c-11eb-8909-fab05b399ea3.png)
I had to remove the storage-driver option in order to restart the service.

**Comment by fbbfnc** [comment] 2021-04-04 09:02
Same problem here. 

Output of `sudo /usr/bin/dockerd` is

`sudo /usr/bin/dockerd
INFO[2021-04-04T11:00:56.804925946+02:00] Starting up
INFO[2021-04-04T11:00:56.808891300+02:00] parsed scheme: "unix"                         module=grpc
INFO[2021-04-04T11:00:56.809008383+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-04-04T11:00:56.809111611+02:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2021-04-04T11:00:56.809165726+02:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2021-04-04T11:00:56.814091650+02:00] parsed scheme: "unix"                         module=grpc
INFO[2021-04-04T11:00:56.814253733+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-04-04T11:00:56.814371337+02:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2021-04-04T11:00:56.814436337+02:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2021-04-04T11:00:56.939360006+02:00] [graphdriver] using prior storage driver: overlay2
WARN[2021-04-04T11:00:57.017053387+02:00] Your kernel does not support cgroup memory limit
WARN[2021-04-04T11:00:57.017680781+02:00] Your kernel does not support CPU realtime scheduler
WARN[2021-04-04T11:00:57.018039947+02:00] Your kernel does not support cgroup blkio weight
WARN[2021-04-04T11:00:57.018374998+02:00] Your kernel does not support cgroup blkio weight_device
WARN[2021-04-04T11:00:57.018712185+02:00] Your kernel does not support cgroup blkio throttle.read_bps_device
WARN[2021-04-04T11:00:57.019045413+02:00] Your kernel does not support cgroup blkio throttle.write_bps_device
WARN[2021-04-04T11:00:57.019244579+02:00] Your kernel does not support cgroup blkio throttle.read_iops_device
WARN[2021-04-04T11:00:57.019436037+02:00] Your kernel does not support cgroup blkio throttle.write_iops_device
INFO[2021-04-04T11:00:57.020251243+02:00] Loading containers: start.
WARN[2021-04-04T11:00:58.693627866+02:00] Could not retrieve networks from local store during ipam allocation for existing networks: failed to get networks for scope local: invalid character '\x00' in string literal
ERRO[2021-04-04T11:00:59.175748058+02:00] getNetworkFromStore for nid 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 failed while trying to build sandbox for cleanup: network 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 not found
INFO[2021-04-04T11:00:59.175869568+02:00] Removing stale sandbox 18dbbeec823436cac34a431d8902151e9d017905e7c420253365e9d94a0d23f0 (37254f74cf8025519fe260be19264e2e581de121ee9d5a963c64646663897dc5)
WARN[2021-04-04T11:00:59.178651435+02:00] Failed getting network for ep 6ae5645b43f368b8584874e1e458540c4bc0a3a674edcfeaba1bb501381619cb during sandbox 18dbbeec823436cac34a431d8902151e9d017905e7c420253365e9d94a0d23f0 delete: network 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 not found
ERRO[2021-04-04T11:00:59.178754039+02:00] Failed to delete sandbox 18dbbeec823436cac34a431d8902151e9d017905e7c420253365e9d94a0d23f0 while trying to cleanup: could not cleanup all the endpoints in container 37254f74cf8025519fe260be19264e2e581de121ee9d5a963c64646663897dc5 / sandbox 18dbbeec823436cac34a431d8902151e9d017905e7c420253365e9d94a0d23f0
ERRO[2021-04-04T11:00:59.619237209+02:00] getNetworkFromStore for nid 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 failed while trying to build sandbox for cleanup: network 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 not found
INFO[2021-04-04T11:00:59.619658302+02:00] Removing stale sandbox 9e4575575a9b2a4b92bf72a0b2ee9064976cda35eb6488bfe71b97d1496c54bd (0bd05e5a7ef008bd36c3e8e1c15a1cdd63df396bd91fa34d2ecd1a4efdbc8cbf)
WARN[2021-04-04T11:00:59.622631158+02:00] Failed getting network for ep e6a392bbd4aced05b90bc87d27d8d42f6a48eeacaf94a40c1411fe12cb20d094 during sandbox 9e4575575a9b2a4b92bf72a0b2ee9064976cda35eb6488bfe71b97d1496c54bd delete: network 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 not found
ERRO[2021-04-04T11:00:59.622988345+02:00] Failed to delete sandbox 9e4575575a9b2a4b92bf72a0b2ee9064976cda35eb6488bfe71b97d1496c54bd while trying to cleanup: could not cleanup all the endpoints in container 0bd05e5a7ef008bd36c3e8e1c15a1cdd63df396bd91fa34d2ecd1a4efdbc8cbf / sandbox 9e4575575a9b2a4b92bf72a0b2ee9064976cda35eb6488bfe71b97d1496c54bd
ERRO[2021-04-04T11:01:00.076174761+02:00] getNetworkFromStore for nid 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 failed while trying to build sandbox for cleanup: network 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 not found
INFO[2021-04-04T11:01:00.076593197+02:00] Removing stale sandbox 9fd7554cda4b5e1b697f5f41e94bc2b97cb14a2834b8640b78ffc940edda4e1b (a0aca44cb6204b2be72a54735d5eaaae0d8013742a25e461f2c81b8011cc1182)
WARN[2021-04-04T11:01:00.079421783+02:00] Failed getting network for ep 36f3b79412451a1e61f9659e357cd00d8cde6790d12027e306cd053e0f347042 during sandbox 9fd7554cda4b5e1b697f5f41e94bc2b97cb14a2834b8640b78ffc940edda4e1b delete: network 7a092bc040f2f5ad450ac21bb49d9f2e0838425ae1eb9a27d097ca0746c5a7b3 not found
ERRO[2021-04-04T11:01:00.079765376+02:00] Failed to delete sandbox 9fd7554cda4b5e1b697f5f41e94bc2b97cb14a2834b8640b78ffc940edda4e1b while trying to cleanup: could not cleanup all the endpoints in container a0aca44cb6204b2be72a54735d5eaaae0d8013742a25e461f2c81b8011cc1182 / sandbox 9fd7554cda4b5e1b697f5f41e94bc2b97cb14a2834b8640b78ffc940edda4e1b
WARN[2021-04-04T11:01:00.082540837+02:00] Could not get list of networks during endpoint cleanup: failed to get networks for scope local: invalid character '\x00' in string literal
WARN[2021-04-04T11:01:00.508330401+02:00] couldn't roll back driver network on network none creation failure: failed to update store for object type *libnetwork.network: invalid character '\x00' in string literal
INFO[2021-04-04T11:01:00.511446955+02:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
failed to start daemon: Error initializing network controller: Error creating default "null" network: failed to update store for object type *libnetwork.network: invalid character '\x00' in string literal`



While output of `journalctl -fu docker` is the following:

`-- Logs begin at Sun 2021-04-04 10:04:44 CEST. --
apr 04 10:53:03 raspberrypi dockerd[2274]: failed to start daemon: Error initializing network controller: Error creating default "null" network: failed to update store for object type *libnetwork.network: invalid character '\x00' in string literal
apr 04 10:53:03 raspberrypi systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
apr 04 10:53:03 raspberrypi systemd[1]: docker.service: Failed with result 'exit-code'.
apr 04 10:53:03 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
apr 04 10:53:05 raspberrypi systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
apr 04 10:53:05 raspberrypi systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
apr 04 10:53:05 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
apr 04 10:53:05 raspberrypi systemd[1]: docker.service: Start request repeated too quickly.
apr 04 10:53:05 raspberrypi systemd[1]: docker.service: Failed with result 'exit-code'.
apr 04 10:53:05 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.`

Can you help me?

**Comment by ayesha-evamp** [comment] 2022-12-23 09:31
how did you use one conf file.
what's the commands

**Comment by cedgnans** [comment] 2024-01-31 12:32
jnnnnnj
