### ISSUE TITLE
rm -rf fails with 'invalid argument' while building on overlayfs, CentOS 7.1

### ISSUE THREAD

**Issue by lewispeckover** [moby/moby#15314] opened 2015-08-05 00:04 UTC
I'm unable to build docker images on an up-to-date CentOS 7.1 machine using ext4-backed overlayfs.
An `rm -rf` of a non-empty directory that was created on a previous layer seems to fail consistently.

`docker version`:

> Client version: 1.7.1
> Client API version: 1.19
> Go version (client): go1.4.2
> Git commit (client): 786b29d
> OS/Arch (client): linux/amd64
> Server version: 1.7.1
> Server API version: 1.19
> Go version (server): go1.4.2
> Git commit (server): 786b29d
> OS/Arch (server): linux/amd64

`docker info`:

> Containers: 29
> Images: 53
> Storage Driver: overlay
> Backing Filesystem: extfs
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.10.0-229.7.2.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> CPUs: 2
> Total Memory: 5.671 GiB
> Name: pc
> ID: PM6K:ISNN:YYZM:XB5X:754X:J6TK:ZUEG:AQWJ:35HA:FRHR:HZEV:KCY4

`uname -a`:

> Linux pc 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

> Physical

How reproducible:

> 100%

Steps to Reproduce:

> docker build - <<EOF
> FROM busybox
> RUN mkdir /tmp/a; touch /tmp/a/b
> RUN rm -rf /tmp/a
> EOF

Actual Results:

> Step 0 : FROM busybox
> ---> 8c2e06607696
> Step 1 : RUN mkdir /tmp/a; touch /tmp/a/b
> ---> Running in 9843f87a09d2
> ---> 30abf7fd2fce
> Removing intermediate container 9843f87a09d2
> Step 2 : RUN rm -rf /tmp/a
> ---> Running in 4dc963dfb9a8
> rm: can't remove '/tmp/a': Invalid argument
> The command '/bin/sh -c rm -rf /tmp/a' returned a non-zero code: 1

Expected Results:

> Successful build

**Comment by Pensu** [comment] 2015-08-05 06:09
It works fine on ubuntu 14.04 with ovaerlayfs. May be, you can try upgrading your kernel?

```
root@ubuntu:~# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@ubuntu:~# docker build .
Sending build context to Docker daemon 982.5 MB
Sending build context to Docker daemon 
Step 0 : FROM busybox
latest: Pulling from busybox
cf2616975b4a: Pull complete 
6ce2e90b0bc7: Pull complete 
8c2e06607696: Already exists 
busybox:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:38a203e1986cf79639cfb9b2e1d6e773de84002feea2d4eb006b52004ee8502d
Status: Downloaded newer image for busybox:latest
 ---> 8c2e06607696
Step 1 : RUN mkdir /tmp/a; touch /tmp/a/b
 ---> Running in 4879bc1d0f02
 ---> 7c24446f9cb0
Removing intermediate container 4879bc1d0f02
Step 2 : RUN rm -rf /tmp/a
 ---> Running in 11469f761368
 ---> 90cb3abd8ff6
Removing intermediate container 11469f761368
Successfully built 90cb3abd8ff6
```

**Comment by cpuguy83** [comment] 2015-08-05 14:16
Also, rm -rf against stuff in a previous layer doesn't make sense, since all the layers are required to make the image, the lower layer is still kept.

**Comment by cpuguy83** [comment] 2015-08-05 14:17
Not that this isn't an issue...

**Comment by lewispeckover** [comment] 2015-08-05 16:17
@cpuguy83 Apologies if I've misunderstood, but the example I provided is very simplified for the purposes of the bug report. In my particular use case, I'm hitting this while doing some cleanup of various files after a package installation. (a RUN yum install.. followed by a RUN rm -rf ...).
I think this pattern does make sense and will be present in quite a lot of dockerfiles.

**Comment by cpuguy83** [comment] 2015-08-05 16:19
@lewispeckover yum is a known issue with overlay.

**Comment by lewispeckover** [comment] 2015-08-05 16:22
@cpuguy83 This is not at all related to the rpm db issues that yum has though, which, as I understand it, are due to it's unusual way of double-opening the db files.

**Comment by LK4D4** [comment] 2015-10-16 16:17
@cpuguy83 @lewispeckover so, can we say that it was fixed in kernel?

**Comment by andrey01** [comment] 2016-08-10 08:43
Seems like that has been fixed in the latest CentOS kernels:

```
] uname -r
3.10.0-327.18.2.el7.x86_64

] docker build - <<EOF
FROM busybox
RUN mkdir /tmp/a; touch /tmp/a/b
RUN rm -rf /tmp/a
EOF
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> 2b8fd9751c4c
Step 2 : RUN mkdir /tmp/a; touch /tmp/a/b
 ---> Using cache
 ---> cef03d9cb0a5
Step 3 : RUN rm -rf /tmp/a
 ---> Using cache
 ---> d2aa44ea8cd7
Successfully built d2aa44ea8cd7

```

**Comment by justincormack** [comment] 2016-09-19 21:54
This works on a modern kernel, so I think you will have to file an issue with Red Hat.

**Comment by m4ce** [comment] 2017-02-22 14:36
I had the same issue. It can be solved by formatting the underlying XFS filesystem with ftype=1. See https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html for more information.

```
$ ~/docker/test% uname -a
Linux hkgdev01 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ ~/docker/test% cat Dockerfile
FROM busybox
RUN mkdir /tmp/a; touch /tmp/a/b
RUN rm -rf /tmp/a
$ ~/docker/test% docker build -t test .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> 7968321274dc
Step 2 : RUN mkdir /tmp/a; touch /tmp/a/b
 ---> Running in c32da72a770e
 ---> bd3bbe3cfd11
Removing intermediate container c32da72a770e
Step 3 : RUN rm -rf /tmp/a
 ---> Running in 9a8d92c028a5
 ---> ed378a7113ae
Removing intermediate container 9a8d92c028a5
Successfully built ed378a7113ae
```

**Comment by thaJeztah** [comment] 2017-05-19 22:36
Yes, this looks like the issue with ftype not being set on XFS. The current version of Docker shows this information in the output of `docker info`;

```
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
```

Running overlay (or overlay2) on XFS without `d_type` is known to cause issues. Docker currently "allows" it for backward-compatibility, but will block it in future, you'll see a warning being logged about this as well when starting the daemon;

```
overlay: the backing xfs filesystem is formatted without d_type support,
which leads to incorrect behavior. Reformat the filesystem with ftype=1
to enable d_type support.
Running without d_type support will no longer be supported in Docker 17.12.
```

Also see these issues, which contain some information https://github.com/moby/moby/issues/10294, https://github.com/moby/moby/issues/29873.

The RHEL release notes mentions this; https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.
> Note that OverlayFS provides a restricted set of the POSIX standards. Test your application thoroughly before deploying it with OverlayFS.

I'll go ahead and close this, but feel free to comment

**Closed by thaJeztah** 2017-05-19 22:36 UTC
Labels: area/kernel, area/storage/overlay, version/1.7

**Comment by hc000** [comment] 2017-05-30 23:12
@thaJeztah i'm having this issue, even when not using xfs with overlay and d_type is true

```Server Version: 17.03.1-ce
Storage Driver: overlay
Backing Filesystem: extfs
Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs```

**Comment by thaJeztah** [comment] 2017-05-30 23:25
@hc000 what distro are you running on? I know on RHEL/CentOS, only XFS can be used as an underlying filesystem; https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html, not sure if that's related - do you have steps to reproduce?

> Only XFS is currently supported for use as a lower layer file system.

**Comment by otherjason** [comment] 2017-07-26 12:59
@thaJeztah I can concur with @hc000; I'm seeing this same issue on CentOS 7.2. I selected overlayfs as the storage driver in my Docker config file and started to see this problem.

```
[user@kaiser ~]$ uname -a
Linux kaiser 3.10.0-327.36.2.el7.x86_64 #1 SMP Mon Oct 10 23:08:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
```

**Comment by thaJeztah** [comment] 2017-07-26 20:18
@otherjason see my comment above; you probably need XFS as backing system; also CentOS used a rolling release model, which means that now CentOS 7.3 replaced 7.2 and 7.2 is EOL

**Comment by gummeah** [comment] 2017-09-28 08:12
@hc000 @otherjason update kernel from CentOS updates repository, if you didn't it already. 3.10.0-327 has problems with overlayfs AFAIK. It was fixed in later versions. 3.10.0-514 is fine, for example.
