### ISSUE TITLE
Permission Denied for bind mounts

### ISSUE THREAD

**Issue by CalamariAce** [moby/moby#41992] opened 2021-02-06 04:49 UTC
The following dockerfile fails to build:

```
FROM ubuntu:focal as base-image
RUN /bin/bash -c "mkdir foo bar; mount --bind foo bar"
```

Command line execution:

```
$ sudo docker build .
mount: /bar: permission denied.
```

Appamor is disabled and I don't see any permission denied errors in kernel logs or other system logs.

What option(s) do I need to set for docker to allow this to succeed?

**Output of `docker version`:**

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Dec 18 12:21:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Thu Dec 10 13:23:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.4
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:    
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 45
  Running: 8
  Paused: 0
  Stopped: 37
 Images: 280
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: journald
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-64-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Baremetal

**Comment by thaJeztah** [comment] 2021-02-09 11:00
This is expected; the default capabilities that containers get don't allow mounting (you'll likely need `CAP_SYS_ADMIN` to perform mounts). Build containers (containers started during `docker build`) do not have these capabilities.

Even if it would be possible to perform `mount` in a build-step as part of the Dockerfile, that mount would only be available for the duration of the `RUN` in which the mount is created. Every `RUN` after that step (and the final image) won't have the mount, so it won't be very useful to allow.

Can you describe what you're trying to do with the `mount` during build? Would alternatives (e.g., create a symlink to the actual path) work for your use-case? Are you trying to specify a "temporary" mount to prevent files from being included in the image?

**Comment by thaJeztah** [comment] 2021-02-09 11:01
Let me go ahead and close this ticket, because it's not a bug-report, but feel free to continue the conversation

**Closed by thaJeztah** 2021-02-09 11:01 UTC
Labels: area/builder, kind/question, status/more-info-needed

**Comment by CalamariAce** [comment] 2021-02-09 11:51
I'm using docker to build host ISO images. The build tool I use (multistrap) chroots into a subdirectory where the ISO is built. However, certain debian packages require /procfs and /sysfs to exist in the chroot path to install properly. I can bind-mount these into the chroot path, if executed as part of a `docker run --privileged` operation. I was hoping to accomplish the same through `docker build`, so that the docker container itself will hold the target host image.

Appreciate any thoughts on this. Thanks.

**Comment by thaJeztah** [comment] 2021-02-09 12:11
> I'm using docker to build host ISO images. The build tool I use (multistrap) chroots into a subdirectory where the ISO is built.

Gotcha; yes, that's a very specific use-case which, for sure, `docker build` did not account for. Permissions on build-containers are kept minimal ("default") for reproducibility and portability of the image.

> However, certain debian packages require /procfs and /sysfs to exist in the chroot path to install properly

Do you know exactly what the packages are looking for? When using buildkit as builder, it's possible to mount (e.g.) a `tmpfs` using `RUN --mount ...` (see https://github.com/moby/buildkit/blob/v0.8.1/frontend/dockerfile/docs/syntax.md#run---mounttypecache). Not sure if that would be enough to "trick" such packages.

>  if executed as part of a `docker run --privileged` operation

Slightly orthogonal to your question, but if possible, try to avoid `--privileged`, and instead use more fine-grained controls (e.g. `--cap-add SYS_ADMIN`, which unfortunately is still _really_ broad, but that's a general "linux" problem for that capability).
The `--privileged` option is _highly_ insecure, and effectively disables all security that containers provide (which allows a container to actually modify your host, and/or get full `root` access on the host).

**Comment by CalamariAce** [comment] 2021-02-09 13:13
I'm also building QCOW2's, but I'm not aware of an alternative to `--privileged` which will pass in the /dev/nbd* block devices (or /dev/loop* or other virtual device equivalents) where the boot loader is installed, and the drive is partitioned and formatted. In my reading of the docs, only `--privileged` will allow the block devices to be passed to the container.

I guess it sounds to me like I should probably just build my image outside of docker all together.
