### ISSUE TITLE
Proposal: ExecKill

### ISSUE THREAD

**Issue by lizelive** [moby/moby#43208] opened 2022-02-03 05:52 UTC
Killing an exec instance is challenging, especially because ExecInspect returns the host pid of the process not the container pid.
Propose adding operation to the engine API to fix this.

```yaml
/exec/{id}/kill:
    post:
      summary: "Kill an exec instance"
      description: |
        Send a POSIX signal to an exec instance, defaulting to killing to the
        exec instance.
      operationId: "ExecKill"
      responses:
        204:
          description: "no error"
        404:
          description: "no such exec instace"
          schema:
            $ref: "#/definitions/ErrorResponse"
          examples:
            application/json:
              message: "No such Exec: ba6a6982fcd041862ae85a4fb7e437cc9ba67634318c7ce80c93f8f26d46d2ab"
        409:
          description: "exec instace is not running"
          schema:
            $ref: "#/definitions/ErrorResponse"
          examples:
            application/json:
              message: "exec instace ba6a6982fcd041862ae85a4fb7e437cc9ba67634318c7ce80c93f8f26d46d2ab is not running"
        500:
          description: "server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "ID of the exec instace"
          type: "string"
        - name: "signal"
          in: "query"
          description: "Signal to send to the exec instace as an integer or string (e.g. `SIGINT`)"
          type: "string"
          default: "SIGKILL"
      tags: ["Exec"]

```

**Comment by thaJeztah** [comment] 2022-02-03 09:47
Thanks for opening; this looks like a duplicate of https://github.com/moby/moby/issues/35703 and work is in progress on an implementation in https://github.com/moby/moby/pull/41548

I'll close this as duplicate of https://github.com/moby/moby/issues/35703

**Closed by thaJeztah** 2022-02-03 09:47 UTC
