### ISSUE TITLE
Unable to build binary

### ISSUE THREAD

**Issue by justadogistaken** [moby/moby#42403] opened 2021-05-20 12:32 UTC
**Description**
make binary failed, the fail info are:

```
root@6e1f5fc2742d:/go/src/github.com/docker/docker# GOOS=linux GOARCH=amd64 hack/make.sh binary

Removing bundles/

---> Making bundle: binary (in bundles/binary)
Building: bundles/binary-daemon/dockerd-dev
GOOS="linux" GOARCH="amd64" GOARM=""
# github.com/docker/docker/vendor/github.com/moby/buildkit/cache/contenthash
vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:490:14: root.Seek undefined (type *iradix.Node has no field or method Seek)
vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:519:15: root.Seek undefined (type *iradix.Node has no field or method Seek)
vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:624:15: root.Seek undefined (type *iradix.Node has no field or method Seek)
vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:642:16: root.Seek undefined (type *iradix.Node has no field or method Seek)
```

**Steps to reproduce the issue:**
1. clone moby
2. go mod init
3. go mod tidy
4. go mod vendor
5. make binary

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
I saw the moby's buildkit depends a project github.com/hashicorp/go-immutable-radix.
and github.com/moby/buildkit/cache/contenthash/checksum.go used a func named Seek, which is from go-immutable-radix, but go-immutable-radix removed the func already, so I can't build binary. Is there any way to fix this? 
**Output of `docker version`:**
tags/v20.10.6
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2021-05-20 12:39
We don't use go modules for this project currently; the vendor directory should contain the versions of the dependencies that are needed to build, and for some dependencies, a "replace" is used, for example, the `go-immutable-radix` dependency uses a replace (last column in the vendor.conf file); https://github.com/moby/moby/blob/d086c52c9a3c9e7f77541056d36df81445d13a03/vendor.conf#L157


To build, skip steps `2` - `4` in your reproduction steps (so clone the repository and `make binary`)


Let me close this ticket because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2021-05-20 12:39 UTC

**Comment by justadogistaken** [comment] 2021-05-20 12:44
Thank you, really helped me out.
