### ISSUE TITLE
Docker service ls reports service as gone, even though containers are still running

### ISSUE THREAD

**Issue by KevinLapagna** [moby/moby#35142] opened 2017-10-09 16:11 UTC
**Description**
If you remove a service, where the associated containers do not stop immediately, the service is displayed as gone, but the containers are still running. That is a problem for automated tasks, because with the service handle gone, there is no (easy) way to find out if all the containers on all the nodes have stopped running.

**Steps to reproduce the issue:**
* Start a service with a process that doesn't stop immediately (ignore SIGTERM for example)
* Remove the service
* Check running services and running containers to see the discrepancy.

For example like this:
`bug.sh`
```
#!/bin/bash

set -e

function show_running {
  echo "=== show running services and containers at `date` ==="
  echo "=== services ==="
  docker service ls
  echo "=== containers ==="
  docker ps
  echo ""
}

docker service create --detach=false --name term term:0.1
show_running
docker service rm term
## same problem with scale
#docker service scale term=0
sleep 1
show_running
sleep 10
show_running
```

**Describe the results you received:**
The command `docker service ls` doesn't show the the service anymore.
The command `docker ps` still shows a container that belonged to the service.

**Describe the results you expected:**
The command `docker service ls` should only delist the service once all containers of that service on all nodes are gone.

**Additional information you deem important (e.g. issue happens only occasionally):**
This seems to have the same underlying problem as #34574.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 186
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:4-656957-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.159GB
 Data Space Total: 107.4GB
 Data Space Available: 5.605GB
 Metadata Space Used: 6.636MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.141GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: mzt4xci2w7sru087hp97ik9ps
 Is Manager: true
 ClusterID: oimp6rpzsczb2g3hethib4fyz
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-35-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.618GiB
Name: xxxx
ID: XPQ4:NRMY:JMPX:D7H7:DMU2:DDGX:7GC6:5RJP:VOS2:KNSJ:GF27:BQD4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details**
Simple container that takes a while to stop

`term.sh`
```
#!/bin/bash

_term() {
	echo "Caught SIGTERM signal!"
	echo "Going to exit in 15 seconds."
	sleep 15
	exit 0
}

trap _term SIGTERM SIGINT

while true
do
	echo "I'm running forever! `date`"
	sleep 1
done
```

`Dockerfile`
```
FROM alpine:3.6
RUN apk add --no-cache bash
COPY term.sh /term.sh
CMD /term.sh
```

**Comment by KevinLapagna** [comment] 2017-10-09 16:16
Here is the output of the `bug.sh` mentioned in the bug report.
```
$ ./bug.sh 
image term:0.1 could not be accessed on a registry to record
its digest. Each node will access term:0.1 independently,
possibly leading to different nodes running different
versions of the image.

huxn3fiesic65txa9e0dqlo7o
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged 
=== show running services and containers at Mon Okt  9 18:13:33 CEST 2017 ===
=== services ===
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
huxn3fiesic6        term                replicated          1/1                 term:0.1            
=== containers ===
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS               NAMES
a028b7bccd60        term:0.1            "/bin/sh -c /term.sh"   7 seconds ago       Up 5 seconds                            term.1.kbti19v4ra6bgon632kietl9o

term
=== show running services and containers at Mon Okt  9 18:13:34 CEST 2017 ===
=== services ===
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
=== containers ===
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS               NAMES
a028b7bccd60        term:0.1            "/bin/sh -c /term.sh"   8 seconds ago       Up 6 seconds                            term.1.kbti19v4ra6bgon632kietl9o

=== show running services and containers at Mon Okt  9 18:13:44 CEST 2017 ===
=== services ===
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
=== containers ===
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

```

**Comment by thaJeztah** [comment] 2017-10-09 18:24
Thanks for reporting! Yes, I think this is a duplicate of https://github.com/moby/moby/issues/34574

It's even easier to reproduce using just;

```
docker service create -t --name noterm busybox
```

Then `docker service rm noterm`.


The problem is because the `docker service rm` (similar to `docker service create` being asynchronously) does not wait for all tasks to be removed, before  removing the service (or marking it "removed")

Let's continue the conversation in https://github.com/moby/moby/issues/34574 I can update the description on that issue to more clearly describe the issue.

**Closed by thaJeztah** 2017-10-09 18:24 UTC
Labels: area/builder, area/swarm, version/17.09
