### ISSUE TITLE
dockerignore file does not respect / at the beginning of the pattern

### ISSUE THREAD

**Issue by mitar** [moby/moby#33425] opened 2017-05-28 22:13 UTC
**Description**

Based on [documentation for dockerignore file](https://docs.docker.com/engine/reference/builder/#dockerignore-file) I was lead to expect that `/foo` and `foo` patterns match equally, a folder `foo` in the context root. But it seems this is not true.

**Steps to reproduce the issue:**

I have the following `.dockerignore` file:

```
/.git
/.idea
/.gitignore
/.gitmodules
/.dockerignore
/Dockerfile
/docker-compose.yml
**/*.pyc
**/__pycache__
**/*.swp
**/*.sublime-*
/datasets/*
```

`datasets` directory contains gigabytes of data.

**Describe the results you received:**

When I run:

```
docker build -t testimage .
```

The context sent to Docker daemon is huge.

The same happens if I try:

```
/.git
/.idea
/.gitignore
/.gitmodules
/.dockerignore
/Dockerfile
/docker-compose.yml
**/*.pyc
**/__pycache__
**/*.swp
**/*.sublime-*
datasets
```

But if I try:

```
.git
.idea
.gitignore
.gitmodules
.dockerignore
Dockerfile
docker-compose.yml
**/*.pyc
**/__pycache__
**/*.swp
**/*.sublime-*
datasets/*
```

Context sent is small as expected.

**Describe the results you expected:**

That the context is small for all variations of `.dockerfile` contents above.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 58
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855 GiB
Name: moby
ID: LCXW:QNBF:FEIN:FTYE:U7BQ:W3VI:N2IH:WNVQ:RFMT:PKET:VEM7:L3WB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 57
 System Time: 2017-05-28T21:56:26.67475541Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ripcurld0** [comment] 2017-05-30 10:02
working on this.

**Comment by thaJeztah** [comment] 2017-05-30 11:42
Looks like this is a duplicate of https://github.com/moby/moby/issues/30676, and there's an open pull request for this here: https://github.com/moby/moby/pull/32088

I'll go ahead and close this to prevent the discussion from diverging, but feel free to comment if this is not a duplicate 😅

**Closed by thaJeztah** 2017-05-30 11:42 UTC
Labels: area/builder, version/17.03

**Comment by mitar** [comment] 2017-05-30 17:06
Probably just removing `/` at the beginning as described in #30676 will probably help here as well. But I worry about why it didn't work when I had only `datasets` without `/`, but some other patterns had `/` at the beginning. Why other patterns made `datasets` do not match as well.

But yes, removing `/` will take care of this as well.
