### ISSUE TITLE
how to handle with defect docker process and start docker daemon

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#35392] opened 2017-11-03 06:35 UTC
I stop docker and find restart failed:
```
[root@003 ~]# systemctl status docker -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since 五 2017-11-03 13:54:39 CST; 49min ago
     Docs: https://docs.docker.com
 Main PID: 227124
   CGroup: /system.slice/docker.service
           ‣ 227124 [dockerd]

11月 03 13:39:38 skydata_003 dockerd[227124]: time="2017-11-03T13:39:38.064779113+08:00" level=info msg="libcontainerd: new containerd process, pid: 227135"
11月 03 13:40:15 skydata_003 dockerd[227124]: time="2017-11-03T13:40:15.217399770+08:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = Internal desc = transport is closing"
11月 03 13:40:16 skydata_003 dockerd[227124]: time="2017-11-03T13:40:16.067626583+08:00" level=info msg="libcontainerd: new containerd process, pid: 227190"
11月 03 13:50:09 skydata_003 systemd[1]: docker.service stop-sigterm timed out. Killing.
11月 03 13:51:39 skydata_003 systemd[1]: docker.service still around after SIGKILL. Ignoring.
11月 03 13:53:09 skydata_003 systemd[1]: docker.service stop-final-sigterm timed out. Killing.
11月 03 13:54:39 skydata_003 systemd[1]: docker.service still around after final SIGKILL. Entering failed mode.
11月 03 13:54:39 skydata_003 systemd[1]: Stopped Docker Application Container Engine.
11月 03 13:54:39 skydata_003 systemd[1]: Unit docker.service entered failed state.
11月 03 13:54:39 skydata_003 systemd[1]: docker.service failed.

```
`dockerd --debug` is holding
```
[root@003 ~]# dockerd --debug
DEBU[2017-11-03T14:33:09.681737158+08:00] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[2017-11-03T14:33:09.681898779+08:00] libcontainerd: previous instance of containerd still alive (227190) 
DEBU[2017-11-03T14:33:10.182622803+08:00] libcontainerd: containerd health check returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
DEBU[2017-11-03T14:33:10.682653414+08:00] libcontainerd: containerd health check returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
DEBU[2017-11-03T14:33:11.182518651+08:00] libcontainerd: containerd health check returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
^C
[root@003 ~]# ps aux | grep docker 
root     142386  1.3  0.0      0     0 ?        Zs   12:09   1:54 [dockerd] <defunct>
root     142396  0.0  0.0      0     0 ?        Zs   12:09   0:04 [docker-containe] <defunct>
root     142585  0.2  0.0      0     0 ?        Zsl  12:10   0:25 [dockerd] <defunct>
root     142783  0.2  0.0      0     0 ?        Zsl  12:10   0:19 [dockerd] <defunct>
root     142794  0.0  0.0      0     0 ?        Zs   12:10   0:04 [docker-containe] <defunct>
root     151766  0.0  0.0      0     0 ?        Zs   12:20   0:03 [docker-containe] <defunct>
root     162496  0.0  0.0      0     0 ?        Z    12:29   0:00 [docker-proxy] <defunct>
root     162524  0.0  0.0      0     0 ?        Z    12:29   0:00 [docker-containe] <defunct>
root     163237  0.0  0.0      0     0 ?        Z    12:30   0:00 [docker-containe] <defunct>
root     163381  0.0  0.0      0     0 ?        Z    12:30   0:00 [docker-containe] <defunct>
root     163558  0.0  0.0      0     0 ?        Z    12:30   0:00 [docker-containe] <defunct>
root     163775  0.0  0.0      0     0 ?        Z    12:30   0:00 [docker-containe] <defunct>
root     164565  0.0  0.0      0     0 ?        Z    12:31   0:00 [docker-proxy] <defunct>
root     164578  0.0  0.0      0     0 ?        Z    12:31   0:00 [docker-proxy] <defunct>
root     164591  0.0  0.0      0     0 ?        Z    12:31   0:00 [docker-proxy] <defunct>
root     164621  0.0  0.0      0     0 ?        Z    12:31   0:00 [docker-containe] <defunct>
root     164697  0.0  0.0      0     0 ?        Z    12:31   0:00 [docker-containe] <defunct>
root     165584  0.0  0.0      0     0 ?        Z    12:31   0:00 [docker-containe] <defunct>
root     219824  0.0  0.0      0     0 ?        Z    13:31   0:00 [docker-exporter] <defunct>
root     227124  0.0  0.0      0     0 ?        Zsl  13:39   0:00 [dockerd] <defunct>
root     227190  0.0  0.0      0     0 ?        Zs   13:40   0:00 [docker-containe] <defunct>
root     227862  0.0  0.0 207544 11276 ?        Sl   13:48   0:00 docker ps
root     230503  0.0  0.0 205880 13084 ?        Sl   14:24   0:00 docker ps
root     231227  0.0  0.0 112652  1012 pts/1    S+   14:33   0:00 grep --colour=auto docker

```

**Comment by thaJeztah** [comment] 2017-11-06 15:28
Looks like there's a lot of `<defunct>` processes on your machine (https://askubuntu.com/a/201308), which can have many causes. I suggest checking your system logs and daemon logs to see if there's anything that gives more information why those processes became defunct.

Your report doesn't contain any information about the system you're  running on (distro, distro version, kernel version), docker version installed, and/or how to reproduce, and debugging your setup is really beyond the purpose of this issue tracker.

Keep in mind that the GitHub issue tracker is not intended as a general support forum, but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because of the above, but feel free to comment.

**Closed by thaJeztah** 2017-11-06 15:28 UTC
