### ISSUE TITLE
Strange characters in service logs when accessing with remote API

### ISSUE THREAD

**Issue by jsalonen** [moby/moby#32794] opened 2017-04-24 19:31 UTC
**Strange characters appear in docker service logs when they are obtained using remote API**

**Steps to reproduce the issue:**
1. Create single-host swarm (`docker swarm init`)
2. Create service that outputs to logs (`docker service create --name hello-world --replicas 2 hello-world`)
3. Obtain logs using remote API (`curl --unix-socket /var/run/docker.sock http://localhost/services/hello-world/logs?stdout=1`)

**Describe the results you received:**

Strange characters appear in the beginning of each line. Example output:

```
Hello from Docker!
KThis message shows that your installation appears to be working correctly.

;To generate this message, Docker took the following steps:
3 1. The Docker client contacted the Docker daemon.
J 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
M 3. The Docker daemon created a new container from that image which runs the
C    executable that produces the output you are currently reading.
O 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.
```

**Describe the results you expected:**

Would expect the logs to not contain strange characters. For example using Docker CLI these characters don't appear (`docker service logs hello-world`).

**Additional information you deem important (e.g. issue happens only occasionally):**

n/a

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 45
 Running: 10
 Paused: 0
 Stopped: 35
Images: 281
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: v0aae4u4vey61erujuq6rfve6
 Is Manager: true
 ClusterID: 4fwd0876eyemtisdbkx1yesoz
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: 4LDE:ONBU:5EB6:5JDJ:CWTM:E6KH:RS7B:LMNB:YI6K:VTNK:VGIF:7XU5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 129
 Goroutines: 277
 System Time: 2017-04-24T19:30:06.71978097Z
 EventsListeners: 12
No Proxy: *.local, 169.254/16
Username: jsalonen
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using Docker for Mac.

**Comment by allencloud** [comment] 2017-04-25 11:28
ping @dperny

**Comment by dperny** [comment] 2017-04-25 20:14
This is actually not broken! By default, logs over the wire are multiplexed using a package formerly known as `github.com/docker/docker/pkg/stdcopy`. This prepends a bit of data containing the message stream a log message belongs to (stdout or stderr) and the length of the log mess that belongs to that stream.

This is really poorly documented (which is partly my fault, now that I have also touched this part of the code) but a recent refactoring has abstracted the function that does this encoding to here, which is slightly better than the ad-hoc way things were before:

https://github.com/moby/moby/blob/master/api/server/httputils/write_log_stream.go

To demux this stream, there is a function in that same `stdcopy` package that is used to copy messages to two different stream represented stdout and stderr. Additionally, a third stream called `Systemerr` is muxed in and contains and errors that may have come from the logger AFTER it started. Those errors will cause `stdcopy` to stop and return the contents of the `Systemerr` message as a string.

I'm sorry this is so poorly documented. I hope this clarifies things a bit. Right now, there is no way to deliberately instruct the logging system to NOT multiplex streams, besides starting the container with a TTY (which has its own pitfalls in service logs right now).

**Comment by dperny** [comment] 2017-04-25 20:17
So, tl;dr, working as intended, just poorly documented.

If you're at all interested in contributing to the project @jsalonen, either documentation or a quick CLI tool that you can pipe the output of `curl` too would be a great place to start.

**Comment by thaJeztah** [comment] 2017-04-25 21:59
The stream format is documented in the API docs here; https://docs.docker.com/engine/api/v1.28/#operation/ContainerAttach.

I'll close this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-04-25 21:59 UTC
Labels: area/swarm, platform/desktop, version/17.05

**Comment by jsalonen** [comment] 2017-04-30 21:57
@dperny @thaJeztah Thanks for the explanation, all the extra characters now make perfectly sense.

Documentation-wise, I think it might make sense to somehow note the specific output format (current documentation says just `string`).

Also is `text/plain; charset=utf8` good MIME type for multiplexed log data? I specifically ended up in trouble because I interpreted the current response as UTF-8 encoded string. If you take those 4 bytes that hold SIZE field, they will get mapped to arbitrary unicode code points. Perhaps some binary type such as `application/octet-stream` would be closer?
