### ISSUE TITLE
Docker image layer reuse

### ISSUE THREAD

**Issue by zvikagart** [moby/moby#33559] opened 2017-06-07 07:23 UTC
We are trying to maximize layer reuse / minimize layer pushes and pulls in our fleet of docker engines v1.13.1 with a private registry v2.6.0.
The questions I have revolve around optimizing layer push/pull and understanding how engine and registry interact to prevent redundant pushes and pulls.
I’m seeing an inconsistent docker engine behavior regarding image layer reuse:
- sometimes pulling layers it already pulled before
- sometimes pushing layers that already exist in the target registry

Here’s an example:
A custom image is built on top of a base image. Other than the top most layer, the custom image shares all layers with the base image. Yet, when pushing the custom image to our registry, sometimes all layers are pushed, even though the registry should have all layers since I pulled the base image from it.
Here's an example log of a pull-build-push sequence, plus the relevant docker version, info and registry log:
https://gist.github.com/zvikagart/efa5b95f42ceebf3359b399ec5920a90

We have a docker registry HA setup with 2 registry servers running with the following configuration: 
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: ***
    secretkey: ***
    region: us-east-1
    bucket: ***
    v4auth: true
  delete:
    enabled: true
http:
  addr: :5000
  debug:
    addr: :5001
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

I tried the same pull-build-push sequence against docker hub registry and didn't experience any issue. All shared layers were skipped ("Layer already exists") during push.

Also, I came across this docker issue: https://github.com/docker/distribution/issues/1464#issuecomment-184836772 
It mentions a docker engine v2 metadata cache:

> Docker maintains a cache of layer digests that remote registries already have, to avoid unnecessary layer uploads. The size of this cache is limited, so it's not guaranteed to prevent these uploads.

1. What is the size of this v2 metadata cache and what is the policy that evacuates entries from it?
2. How does this relate to the registry v2 API where docker engine is able to check for a layer existence via a HEAD request (https://docs.docker.com/registry/spec/api/#pushing-an-image) before uploading?
3. Will the engine always make the layer existence check?
4. Is there a misconfiguration you notice in our registry (is `inmemory` blob descriptor cache an issue)?

**Comment by thaJeztah** [comment] 2017-06-07 08:58
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

Could you try one of those instead? I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-06-07 08:58 UTC

**Comment by zvikagart** [comment] 2017-06-07 09:11
I tried the forum:
https://forums.docker.com/t/docker-daemon-image-layer-reuse/33124
Also tried IRC, not Slack channel, and no answers.
I understand the rules and was reluctant to create an issue here, but that was my last resort :)
I'll try the slack channel and see if I get some answers.

**Comment by thaJeztah** [comment] 2017-06-07 09:26
We do try to answer short questions on GitHub where possible, but resources are limited, so it's best discussed on on of the other channels. It's worth trying the #docker-distribution channel on community Slack for the questions about the registry and image distribution.

Having said the above, people can still comment on this issue, so may be able to add information
