### ISSUE TITLE
Question about environment var inherited from parent image

### ISSUE THREAD

**Issue by justlooks** [moby/moby#33242] opened 2017-05-17 07:17 UTC
i build a image A , and a image B , B is build from A , and i set a environment var a in image A, question is when i run container of B ,how can i set the env var a?

**Comment by thaJeztah** [comment] 2017-05-17 12:32
If an environment variable is set through an `ENV` instruction in the Dockerfile, that environment variable is preserved in the image, and images using the image as a "base" image; Environment variables set in a `RUN` statement only exist during that `RUN` instruction. Using the following;

image "myimage:a":

```Dockerfile
FROM alpine
ENV hello=world
ENV world=foo
RUN export foo=bar
```

image "myimage:b":

```Dockerfile
FROM myimage:a

# override the $world environment variable
ENV world=something
```

In this example, running `myimage:b` has these environment variables;

```bash
$ docker run --rm myimage:b env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=7c6ac365d28b
hello=world
world=something
HOME=/root
```

- `$hello` is inherited from `myimage:a`
- `$world` is overridden in `myimage:b`
- `$foo` is not present, because it was only available in the `RUN` statement
- (`$PATH`, `$HOSTNAME` and `$HOME` are automatically set)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-05-17 12:32 UTC

**Comment by thaJeztah** [comment] 2018-06-20 02:41
@gaui `ENV` vars are not "inherited" between stages unless a stage is using `FROM <another-stage>`; if you suspect there's a bug at hand, it's better to open a new ticket with details (docker version you're using), and minimal steps to reproduce (if possible, a minimal Dockerfile that shows the problem)

**Comment by gaui** [comment] 2018-06-20 02:45
@thaJeztah Ok thank you, it's clear now. 😃

**Comment by alivannikov** [comment] 2021-01-11 11:39
> $foo is not present, because it was only available in the RUN statement

@thaJeztah Isn't it so that RUN command is applied to image during image build time (in opposite to CMD which is kind of runtime thing executed at the moment when container created from image). So if I do `RUN mkdir ...` it will create a layer in docker image. In analogy to this I think it is quite logical to expect that env vars set with RUN are also built-in into the image?

**Comment by thaJeztah** [comment] 2021-01-11 11:43
`RUN` executes a command, and after the command has run, filesystem changes that were made by the command are committed as an image layer. Changes that are in memory only are not part of that, and thus not committed. Setting an environment variable in a shell only affects that shell, and is only present in memory.

**Comment by alivannikov** [comment] 2021-01-11 12:09
@thaJeztah Thank you for clarification. Could you please give some insights how `ENV` works internally then? Does it create some special file with vars to be set, and actual execution of `export` commands by docker runtime delayed until container is created?

**Comment by thaJeztah** [comment] 2021-01-11 12:31
`ENV` updates the image configuration, which is used as template when starting a container from that image. That configuration is used by the runtime to set up the container, and when starting the container's main process;

```console
$ docker image pull busybox

$ docker image inspect --format '{{ json .Config.Env}}' busybox
["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
```

**Comment by thaJeztah** [comment] 2021-01-11 12:33
See https://github.com/opencontainers/image-spec/blob/v1.0.1/config.md for more details on the OCI image specification, and https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#process for the "runtime" configuration (definition to create/start a container)

**Comment by amrsa1** [comment] 2023-02-05 20:51
how to inherit these env varaible for the base image to a docker compose file e.g
base image has env variable START
how i can use this START in a docker compose for example 

child image
```
    command:
      - bash
      - -c 
      - |
          $START
```
