### ISSUE TITLE
docker bind-mounts should have strategy if mount source is not available

### ISSUE THREAD

**Issue by typoworx-de** [moby/moby#47616] opened 2024-03-22 10:08 UTC
### Description

Currently using docker bind-mounts will always create an empty directory if the source for the mount does not exist. In some cases this may be the desired behaviour, but in other cases this can cause trouble.

The most impacting trouble is for any docker service that tries to bind-mount docker.sock for any management. This is for example used by portainer, portainer-agent, traefik. In this case trying to start/restart docker will lead to impacting issues, as docker in some cases does not create docker.sock before the services/containers are going to start. So the docker.sock is replaced by docker bind-mount of a service/container to create a directory, which then makes the whole docker-engine and all it's services unusable and non-functional. See #30348 and bug-report #47615

Additionally to the docker-engine bug we should be able to control such behaviour. There should be a strategy for docker/docker-compose how to handle this. I believe these modes would be fine:
- ignore (keep mount target empty)
- directory
- file
- socket

**Comment by vvoland** [comment] 2024-03-22 10:18
You can use the long `--mount` syntax instead - it doesn't create an empty directory if the source doesn't exist.

See: https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior

As for adding the modes - I don't think we want to add this, our preference is to make the user responsible for making sure the source exists. As much as we'd like to change the default behavior of `-v`, I don't think it's a realistic option due to backwards compatibility and users expecting it to work like it did for years.

**Comment by neersighted** [comment] 2024-03-22 10:18
This already exists today; you can `docker run --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock`, and you will get an error if that path does not exist on the host, instead of implicit directory creation.

Regarding the socket, I suspect that using systemd socket activation will help, but there is still some definite raciness there. I'm not sure it makes sense to block container startup until the HTTP handler is ready, but perhaps that is work for a future day. In any case, using the mounts API should be the solution here.

Regarding the strategy idea, I'm not sure it makes sense. The only mode that might make sense (if we expose options in the CLI) is `file`; `socket` is a nonsense case as a socket is never re-used; it has to be explicitly bound by the program listening/accepting on the other side.

For now I am closing this issue as a duplicate of the linked issue.

**Closed by neersighted** 2024-03-22 10:18 UTC
Labels: status/0-triage, kind/feature, area/volumes
