### ISSUE TITLE
CpuShares default value in docker inspect is 0

### ISSUE THREAD

**Issue by wdhif** [moby/moby#35452] opened 2017-11-09 17:22 UTC
The default `CpuShares` value is 1024, I can check this value for a container using in my cgroup (`/sys/fs/cgroup/cpu/docker/*/cpu.shares`).

For a new container, the value is indeed 1024. But when I check this value using `docker inspect`, it appears to be 0.

After a `docker update`, the `docker inspect` value and the cgroup are correctly updated.

Why the first value of the `docker inspect` is 0 ?

**Steps to reproduce the issue:**
1. Create a new container
2. Check the cpu.shares in the cgroup (1024)
3. Use `docker inspect` to check CPU Shares (0)

**Describe the results you received:**
`docker inspect` gives me a CPU Shares value of 0

**Describe the results you expected:**
`docker inspect` should give me a CPU Shares value of 1024

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.765GiB
Name: vps472717
ID: 3MC7:ADIG:GMAE:6EEK:6KKH:UZ6H:UAC7:EBA7:2TAL:7OPJ:DHPP:DD7D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2017-11-09 17:50
The `0` value here indicates "use the default as is set by the daemon"; this is currently not configurable, but having a `0` value allows making this possible in future, similar to what's used for;

```
      --cpu-rt-period int                     Limit the CPU real-time period in microseconds
      --cpu-rt-runtime int                    Limit the CPU real-time runtime in microseconds
```

See the documentation here; https://docs.docker.com/engine/reference/run/#cpu-share-constraint

### CPU share constraint

> By default, all containers get the same proportion of CPU cycles. This proportion can be modified by changing the container’s CPU share weighting relative to the weighting of all other running containers.

> To modify the proportion from the default of 1024, use the `-c` or `--cpu-shares` flag to set the weighting to `2` or higher. If `0` is set, the system will ignore the value and use the default of `1024`.


I'm closing this issue because it's not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-11-09 17:50 UTC
Labels: version/17.09

**Comment by wdhif** [comment] 2017-11-09 18:21
Ok, I see. I was expecting a default value of 1024 but I understand the design choice. Thanks for the quick answer.

**Comment by thaJeztah** [comment] 2017-11-09 18:33
You're welcome! It's a valid question, and it's known to be not entirely consistent (some options _do_ show default values if their default can be set client-side)

**Comment by wdhif** [comment] 2017-11-09 19:18
Well, if I can afford, I think the value should stay consistent with the cgroup. It is pretty hard to guess that's it's an intended behaviour. But it's just my opinion :)

**Comment by thaJeztah** [comment] 2017-11-09 20:39
The problem here is that the client doesn't know about cgroups defined on the daemon host (taking into account that the daemon may have a custom ` --cgroup-parent` defined). Some discussion around this in https://github.com/moby/moby/issues/18797#issuecomment-229808209

For `service create` defaults are added through the API (see https://github.com/moby/moby/pull/32284), but this may be non-trivial in this case

**Comment by wdhif** [comment] 2017-11-09 22:08
I see it's a complex issue, thanks again for the answer.

**Comment by thaJeztah** [comment] 2021-09-29 15:32
Not a quick one to answer; docker sets up the cgroup configuration, but after that it's all handled by the kernel.

Some docs can be found here; https://docs.docker.com/config/containers/resource_constraints/

But for nitty-gritty details, refer to the Linux kernel manpages and docs, e.g. https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/Documentation/scheduler/sched-design-CFS.rst and https://kernel.googlesource.com/pub/scm/linux/kernel/git/glommer/memcg/+/cpu_stat/Documentation/cgroups/cpu.txt

**Comment by BLasan** [comment] 2021-09-29 15:43
> Not a quick one to answer; docker sets up the cgroup configuration, but after that it's all handled by the kernel.
> 
> Some docs can be found here; https://docs.docker.com/config/containers/resource_constraints/
> 
> But for nitty-gritty details, refer to the Linux kernel manpages and docs, e.g. https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/Documentation/scheduler/sched-design-CFS.rst and https://kernel.googlesource.com/pub/scm/linux/kernel/git/glommer/memcg/+/cpu_stat/Documentation/cgroups/cpu.txt

Thanks for the documents :) So, what docker and orchestration tools like K8s do is modify the cgroup values accordingly and let the kernel to handle the processes right? Really hard to find out how this exactly works. All these about the time slices allocated by the CFS scheduler to the processes

**Comment by thaJeztah** [comment] 2021-09-30 15:18
> So, what docker and orchestration tools like K8s do is modify the cgroup values accordingly and let the kernel to handle the processes right?

"mostly yes", for runtimes, that is. Containers are regular processes, just like any other process running on Linux, but with sandboxes applied.

After defining the sandbox, runtimes (docker, containerd, runc) will take themselves out of the equation as much as possible. They set up the container's rootfs (filesystem), cgroups and other constraints (seccomp profile, capabilities), setting up stdio, mounts, networking, etc. After that they limit themselves to what's needed to operate the container (monitor if the process is running, and act on that (restart, remove), capture stdout/stderr if requested), but it's the kernel's responsibility to handle the limits that are set for the container.

For "and orchestration tools like K8s", _it depends_. k8s is an orchestrator, and besides just starting containers / pods, it has many features in the "orchestration" bit. Depending on the setup, it may do monitoring of its own related to that. For example, k8s could be using auto-scaling and decide that a service (container / pod) is rescheduled to another node if the CPU load on a node is reaching a certain threshold.

**Comment by BLasan** [comment] 2021-09-30 16:02
> > So, what docker and orchestration tools like K8s do is modify the cgroup values accordingly and let the kernel to handle the processes right?
> 
> "mostly yes", for runtimes, that is. Containers are regular processes, just like any other process running on Linux, but with sandboxes applied.
> 
> After defining the sandbox, runtimes (docker, containerd, runc) will take themselves out of the equation as much as possible. They set up the container's rootfs (filesystem), cgroups and other constraints (seccomp profile, capabilities), setting up stdio, mounts, networking, etc. After that they limit themselves to what's needed to operate the container (monitor if the process is running, and act on that (restart, remove), capture stdout/stderr if requested), but it's the kernel's responsibility to handle the limits that are set for the container.
> 
> For "and orchestration tools like K8s", _it depends_. k8s is an orchestrator, and besides just starting containers / pods, it has many features in the "orchestration" bit. Depending on the setup, it may do monitoring of its own related to that. For example, k8s could be using auto-scaling and decide that a service (container / pod) is rescheduled to another node if the CPU load on a node is reaching a certain threshold.

Yuh. Main problem is the `cpu.share` of the cgroups. If we consider two containes with `cpu.shares` 1024, 2048, the ratio will be 1:2. And if we configure `cpu.share` as 10, 20 still it'll get the same ratio. Are these two approaches same since `cpu.share` is a relative count?

**Comment by BLasan** [comment] 2021-10-01 03:14
@thaJeztah I would like to contribute to docker source code. How could I start as a newbie? Are there any good first issues?
