### ISSUE TITLE
Request to create new release(s) for Go modules compatibility

### ISSUE THREAD

**Issue by mcurtiss** [moby/moby#39056] opened 2019-04-10 22:53 UTC
Hey Folks,
I couldn't find this discussed elsewhere, so I'm asking here: Would it be possible to create a new release (and hopefully restart the process of creating regular new [releases](https://github.com/moby/moby/releases))?

Background: Apparently there hasn't been a new release since June 2017 (v17.03.2-ce).  I wouldn't really care about this, except that the Go language is moving to adopt [modules](https://blog.golang.org/using-go-modules) (i.e. versioned releases of packages), and `go` uses the latest github release as the default version of a module to fetch. So by not updating releases here (AFAICT), it makes it confusing (though not impossible) to use Go modules with moby.

More background/repro is in this [golang issue](https://github.com/golang/go/issues/31370) I filed.

**Comment by faraazahmad** [comment] 2019-04-15 20:02
would this be related to why i am unable to `get get github.com/docker/docker/client`?

**Comment by cpuguy83** [comment] 2019-04-15 22:15
Releases are handled through github.com/docker/engine currently.
You should target the branch/tag for the release you are wanting to support.

The other part of this is Docker does not follow semver, and while generally we do try to not break the package level API's it does happen from time to time.
This does not follow with the go modules method of versioning and will require manual management.

**Comment by faraazahmad** [comment] 2019-04-16 04:33
So should I `github.com/docker/engine` ?

**Comment by monkeyWie** [comment] 2019-07-22 10:20
Hey,so we have solution?

**Comment by ldez** [comment] 2019-08-04 16:37
As the go modules will become the default/standard for Go projects, is it Docker/Moby will reevaluate its versioning policy?

**Comment by cpuguy83** [comment] 2019-08-04 17:02
Changing the versioning will not fix any problems caused by modules.
The fact that there are non-semver versions alone breaks automatic version selection.
That plus the fact that semver just does not make sense for the engine.

Having a library in a client lib in a separate repo which is semver kind of makes sense, but is hugely difficult to maintain.

For those wondering if there is a solution, yes! Use a "replace" directive and specify the docker/engine repo and tag that you want.

**Comment by ldez** [comment] 2019-08-04 17:09
the "replace" directive is not transitive (if a project depends of a lib that specify the replace directive, the replace will not apply to the project), so it's a unstable solution.

But I understand your point.

**Comment by ldez** [comment] 2019-08-04 18:31
Sorry to bother you, are you planning to replace the `vendor.conf` file with `go.mod`?
Even if you do not use semver.

**Comment by cpuguy83** [comment] 2020-02-07 03:37
On the maintainers call today we discussed making client a dedicated module with its own tags (ie client/ will get its own go.mod and special tags client/<version>) which, in theory, should work with go get.

**Comment by johanbrandhorst** [comment] 2020-04-02 16:30
To users of go.dev and the official docker client, this versioning is very confusing: https://pkg.go.dev/github.com/docker/docker/client?tab=versions. Apparently the latest version it `1.13.1`, while @master is currently detected as `v1.4.2-0.20200331113714-bd81cf28590c`. A separate module for the client would be greatly appreciated to fix this confusion.

**Comment by cpuguy83** [comment] 2020-04-02 16:42
I'll bring this up again today.  Really someone (a maintainer) just needs to do the work, but I'm definitely worried about breaking other consumers.
Basically, who are we going to break by making this change (I'm greater than 50% positive that it will break people)... is the number it will break higher or lower than the number of people currently feeling pain.

Another thing that is problematic is if we keep the current repo structure then we need 2 modules, one for api/types and one for client, and then we have to keep this things in sync somehow... or just move everything under a single package tree and break everyone.

**Comment by johanbrandhorst** [comment] 2020-04-02 21:08
I think the majority of the Go ecosystem is getting behind modules (no evidence other than my own experience), and while that might certainly not be a majority of users right now, it will be sooner or later. I'm not sure how adding the module would risk breaking current users?

> Another thing that is problematic is if we keep the current repo structure then we need 2 modules, one for api/types and one for client, and then we have to keep this things in sync somehow... or just move everything under a single package tree and break everyone.

Do they need to be kept in sync? If the dependency relationship is a simple arrow (one depends on the other), then it should be possible to version them independently. I'm by no means an expert, but it also should be possible to experiment a little (as long as you're not cutting any new releases imminently).

**Comment by leitzler** [comment] 2020-04-02 21:17
Just to add some numbers to Johan’s comment (I hope you don’t mind): https://github.com/golang/go/issues/38158#issuecomment-606750795. It looks indeed like quite a lot of the public repos have migrated to modules already!

**Comment by cpuguy83** [comment] 2020-04-02 21:17
We don't use dep either, but also aren't using modules :)

**Comment by leitzler** [comment] 2020-04-02 21:21
> We don't use dep either, but also aren't using modules :)

I know, the comment include a lot of relevant numbers that can give a hint of modules adoption rate, regardless of earlier dependency management :)

**Comment by SimSmith** [comment] 2020-05-08 12:48
The Go Developer Survey 2019 also gives some additional numbers.
Among the respondents, 89% were using Go Modules.
https://blog.golang.org/survey2019-results

**Comment by RX14** [comment] 2020-05-12 09:26
the "replace" workaround mentioned above doesn't seem to work with newer versions.

I tried adding `replace github.com/docker/docker => github.com/docker/docker v19.03.8` but go changes this to `replace github.com/docker/docker => github.com/docker/docker v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible`

**Comment by cpuguy83** [comment] 2020-05-12 22:21
Are you sure it's a problem? The first part of `-aa6a9891b09c+incompatible` is the commit for 19.03.8

**Comment by thaJeztah** [comment] 2020-05-12 22:51
The strange version is because go modules doesn't support release branches, and assumes releases are only done from master; it therefore finds a branch point on the master branch (and only those that it assumes are SemVer), and picks that as "the version" to use for generating a pseudo-version.

As @cpuguy83 explained, it's the commit (last part) that's the actual version that go mod uses

**Comment by rodrigocollavo** [comment] 2020-05-25 12:51
FYI, the problem with go mod fetching v17.12.xxx instead of v19.03.xxx is related to the trailing zero not following semver compliance, that's why go fetches the nearest valid version (all v19 and v18 versions have a traling zero on the minor version number).

Is there any workaround for gomod? I'm not able to find a solution for this using go mod

**Comment by johanbrandhorst** [comment] 2020-05-25 12:58
```go
module xxx

go 1.14

require (
	github.com/docker/docker v1.4.2-0.20200213202729-31a86c4ab209
)
```

This version works for me. You might even be able to tweak it to a specific commit yourself.

**Comment by rodrigocollavo** [comment] 2020-05-25 13:09
yes, but source code differs a lot from current master branch (19.x)

**Comment by thaJeztah** [comment] 2020-05-25 13:34
Specify the tag of the release you want to use in your `go.mod`, and go modules will pick the correct commit. If will _show_ the confusing "pseudo version" but the commit will match.

Make sure to specify the version though, otherwise go modules will pick a very old version  (v1.13.1), which it thinks is the current "stable" release. Here's a quick example;

```bash
mkdir foobar && cd foobar
```

Add a main.go

```go
package main

import (
        "fmt"

        "github.com/docker/docker/api"
)

func main() {
       fmt.Println("the API version is", api.DefaultVersion)
}
```

Initialize your module;

```bash
go mod init foobar
# go: creating new go.mod: module foobar
```

Specify the version of docker/docker you want to use in your `go.mod`;

```bash
echo "require github.com/docker/docker v19.03.9" >> go.mod
```

Build the binary and verify that the correct API version is used. In this case, go downloads the module (the pseudo version it generates and downloads uses `v17.12.0-ce-rc1`, but the commit (`811a247d06e8 ` matches v19.03.9: https://github.com/moby/moby/releases/tag/v19.03.9)

```bash
go build
# go: downloading github.com/docker/docker v17.12.0-ce-rc1.0.20200514230353-811a247d06e8+incompatible

./foobar
# the API version is 1.40
```

**Comment by yeukhon** [comment] 2022-09-30 14:21
If people still have this issue, just go to `go.mod` and update the version to whatever is found in https://pkg.go.dev/github.com/docker/docker/client?tab=versions (or whatever is latest in the release tag page).

Example:
```
github.com/docker/docker v20.10.18+incompatible
```

I am no expert so I don't know whether it is `go.mod`'s architectural, intented limitation, or it is really the moby maintainer needing to comply with semver compliance. Well, I am using go 1.16, maybe this is a non-problem in a more modern version of Go *shrug*

**Comment by thaJeztah** [comment] 2023-09-17 23:07
not fully there yet, but at least the version format is more compatible (still needs `+incompatible`)

let me close this one for now

**Closed by thaJeztah** 2023-09-17 23:07 UTC
Labels: kind/question
