### ISSUE TITLE
Is SSL3 protocol supported in Azure Kubernetes Service

### ISSUE THREAD

**Issue by siddharth1991** [moby/moby#41996] opened 2021-02-08 06:45 UTC
We are running windows 2019 Server Core OS image in our container. By default my container supports all the following protocols
TLS
TLS1.1
TLS1.2

My application is using ssl3 for some request. I want to enable ssl3 on the container

I tried editing the registry on container, but it requires a restart for windows to recognize change in registry related to ssl3. Since in docker, there is no concept of restarting windows inside container, how can I enable ssl3 protocol on windows docker 2019 image.
Can i use init containers for changing windows registry. If so, how?
I am also to any other options

Extra Information
I am using following command to know ssl3 is not there on windows 2019 Server OS container.
**nmap --script ssl-enum-ciphers -p 443 mysite.com --unprivileged**
I am getting following output
![image](https://user-images.githubusercontent.com/4918817/107184807-44695080-6a07-11eb-9d97-603ad7914296.png)

**Comment by thaJeztah** [comment] 2021-02-09 11:05
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

Given that this question looks to be specific for Azure, perhaps Azure support would be a better location for this.

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-02-09 11:05 UTC
Labels: kind/question, platform/windows
