### ISSUE TITLE
Service Logs fails on scale down

### ISSUE THREAD

**Issue by JonasKs** [moby/moby#33222] opened 2017-05-16 12:04 UTC
**Description**
Scaling down a service and calling for the logs will make logs fail, with errors from the service. 
@dperny asked me to create a own issue for this [here](https://github.com/moby/moby/issues/33203#issuecomment-301618701). 

**Steps to reproduce the issue:**
1) `docker service create  --name my-web --publish 9091:80 --replicas 2 nginx`
2) Generate some log and traffic: `httperf --server <server ip> --port <nginx port> --num-conns 1000 --rate 10 --hog`
3) Scale up and down. I used a simple bash script resulting in this with 5 second delays between each:
```
my-web scaled to 8
my-web scaled to 17
my-web scaled to 7
```
4) Get log-lines while doing this.  `docker service logs my-web | wc -l`

**Describe the results you received:**
```
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
589
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
623
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
error from daemon in stream: Error grabbing logs: rpc error: code = 2 desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: rpc error: code = 13 desc = grpc: failed to unmarshal the received message proto: illegal wireType 7

661
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0xd45620, 0xc4203bd300)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
strings.Repeat(0xe44138, 0x1, 0xffffffffffffffff, 0xc4203bd2f0, 0xd)
	/usr/local/go/src/strings/strings.go:420 +0x49
github.com/docker/docker/cli/command/service.(*taskFormatter).format(0xc420451260, 0x7fe81f680028, 0xc420012258, 0xc42046a019, 0x19, 0xc42046a04f, 0x19, 0xc42046a082, 0x19, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:204 +0x4d5
github.com/docker/docker/cli/command/service.(*logWriter).Write(0xc420451290, 0xc42045e008, 0xf9, 0x8001, 0x404, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:243 +0x392
github.com/docker/docker/pkg/stdcopy.StdCopy(0x15158e0, 0xc420451290, 0x15158e0, 0xc4204512c0, 0x1516ca0, 0xc42045c080, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/stdcopy/stdcopy.go:174 +0x36f
github.com/docker/docker/cli/command/service.runLogs(0xc4203b37a0, 0xc42037b340, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:147 +0x70e
github.com/docker/docker/cli/command/service.newLogsCommand.func1(0xc4203fb680, 0xc420436280, 0x1, 0x1, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:50 +0x6d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203fb680, 0xc42000c1f0, 0x1, 0x1, 0xc4203fb680, 0xc42000c1f0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x26d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42007fd40, 0xc4203b6240, 0xc42035bef0, 0xc4200264c8)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x377
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42007fd40, 0xc42007fd40, 0x1517260)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/usr/src/docker/.gopath/src/github.com/docker/docker/cmd/docker/docker.go:169 +0xcb

```

**Describe the results you expected:**
The log to just increase, and not bug up. Doing the same without scaling down has no issues.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have not been able to scale up/down with my script without having this issue, though I'm not entirely sure if it happens on first attempt on scale down. 

**Output of `docker version`:**
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: n9svkw9tmii4bsapyuwc7kfuy
 Is Manager: true
 ClusterID: 862oj158u0rlkgbekg73rqrhn
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.1.0.118
 Manager Addresses:
  10.1.0.118:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: manager-project2
ID: LKPP:MZU6:2WDY:Q4TS:34WD:BEZT:CQYL:D6PJ:GYK2:QFHG:PITJ:L4WY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack cloud node, with two joined nodes as workers to the swarm.

**Comment by thaJeztah** [comment] 2017-05-16 13:16
ping @dperny

**Comment by aaronlehmann** [comment] 2017-05-16 19:22
The problem is this line of code:

```
padding := strings.Repeat(" ", f.padding-getMaxLength(task.Slot))
```

`padding` is based on how many digits the replica count has. But more replicas may be added later (and even without any scaling, slot numbers are not guaranteed to be contiguous). So the subtraction in the line above can underflow.

**Comment by dperny** [comment] 2017-05-16 20:37
don't close this issue after docker/cli#98 is merged. i feel like there is more to this problem.

**Comment by aaronlehmann** [comment] 2017-05-18 22:51
There is a similar issue at #33203. Can we unify them, or is the remaining problem something separate?

I noticed the `error from daemon in stream: Error grabbing logs: rpc error: code = 2 desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: rpc error: code = 13 desc = grpc: failed to unmarshal the received message proto: illegal wireType 7`... that's really strange, but it may be related to https://github.com/docker/swarmkit/pull/2186

**Comment by dperny** [comment] 2017-05-18 23:51
@aaronlehmann I think the wiretype error must be related to that swarmkit issue with gogoproto, because it looks like alienspeak to me. That error is the reason I didn't want to close this issue. If we can confirm that's the problem, then we can close this.

**Comment by dperny** [comment] 2017-05-18 23:52
@JonasKs were all 3 of your nodes on 17.05?

**Comment by JonasKs** [comment] 2017-05-19 01:22
@dperny, yes. Same setup as the manager.

**Comment by aaronlehmann** [comment] 2017-06-09 20:37
Fixed by https://github.com/docker/swarmkit/pull/2186 and https://github.com/docker/cli/pull/98.

**Closed by aaronlehmann** 2017-06-09 20:37 UTC
Labels: area/logging, area/swarm, kind/bug, priority/P1, version/17.05
