### ISSUE TITLE
Windows Server 2016 hanging after Docker installation

### ISSUE THREAD

**Issue by sinqinc** [moby/moby#32276] opened 2017-03-31 17:53 UTC
Hi,

I'm trying to install Docker on Windows Server 2016 with Desktop Experience using the following commands 

`Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
Install-Package -Name docker -ProviderName DockerMsftProvider
`
After the required reboot, the server is completely hanging. I can "login" but it take a few hours to get in. I can't execute anything. CMD, Powershell nothing get executed.

The server is running in a IaaS provider under KVM (ClougSigma)  without the nested virtualization activated. 
Docker is running fine on our Linux servers. We don't want to use Hyper-V container but it seems to install and start some Hyper-V services.

**Comment by friism** [comment] 2017-03-31 20:20
I think you might get better results asking ClougSigma.

The Module won't install Hyper-V, but it does install the "Containers" feature: https://github.com/OneGet/MicrosoftDockerProvider/blob/developer/DockerMsftProvider.psm1#L595

If you want to experiment, consider trying a manual installation to see if that works better: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon

**Comment by sinqinc** [comment] 2017-03-31 21:02
I already asked CloudSigma and got that response 

##############
Dear Sebastien,

Can you please share with us, which Docker version did you install? Did you follow the Microsoft official tutorial? If you use the official Microsoft tutorial, please know that this version is for physical machines and this is known issue that it doesn't work on virtual ones. For Windows 2016 in virtual environment, please use Docker Toolbox - https://www.docker.com/products/docker-toolbox  This is fully functional version of the Docker.

However the issue is with the fact that the Windows OS is run within a virtual environment. While said environment is KVM and KVM does have support for nested virtualization, the feature itself is disabled in our infrastructure for security reasons. The prerequisites which MS have posted assume that nested virtualization is left intact, however this is not the case in our cloud. 
Hence the colleagues suggested to use Docker Toolbox instead. Please try that and let us know if the results are satisfactory. 

Thank you for contacting us and please inform us if the issue was resolved with Docker toolbox.



##############


I will try To manually install docker to find out where it could hang but the response of CloudSigma doesnt help.

**Comment by friism** [comment] 2017-03-31 21:13
@sinqinc the response from CloudSigma is incorrect. I've personally installed and run Docker for Windows Server 2016 on AWS EC2, Azure and Google Compute Engine and it runs great. All of those platforms use virtualization and none of them (currently) support nested virtualization.

Docker Toolbox is not what you want, I'm guessing, since it only lets you run Linux containers on Windows.

**Comment by sinqinc** [comment] 2017-03-31 21:27
Toolbox is not what I want.

I thought that it could be HyperV because Two services are started. Vmcompute and vmms are started probably to support hyperV isolation which i dont need.

**Comment by friism** [comment] 2017-03-31 21:31
I think vmcompute is also for process-isolated containers: https://github.com/docker/docker/blob/1c7a3d3e6c03e911775d8bed8675d5bc5dc1cfcd/daemon/daemon_windows.go#L242

Maybe @johnstep has an idea

**Comment by johnstep** [comment] 2017-04-01 00:29
Yes, vmcompute and vmms are also started for process (Windows Server) containers. It is confusing since the same service manages both, but you can definitely run process containers without nested virtualization.

@sinqinc Have you tried manual installation yet? I believe that once you have the Containers feature installed, `dockerd.exe` should work if you just run it, even without installing it as a service. If that fails, try running it in debug mode (`dockerd.exe -D`) and see if the output has any helpful information.

**Comment by sinqinc** [comment] 2017-04-01 00:39
@johnstep I just tried the manual installation. I tried to start the service but it failed since it need the Containers feature. I installed the feature and after the reboot the server hanged. 

I will try to install the feature then reboot. After I will install docker without  installing it as service and start it in debug mode. I hope I will get some informations.

**Comment by sinqinc** [comment] 2017-04-01 00:58
![img_0181](https://cloud.githubusercontent.com/assets/16611527/24573677/7dd7c56e-1654-11e7-80ae-a24ea6e8c8a4.PNG)

I installed Containes feature then I rebooted. 

I installed docker and started dockerd in debug mode. 

The docker client did not connect to the deamon and the deamon seems to be completly frozen.

**Comment by sinqinc** [comment] 2017-04-01 01:06
I just got the following error :
```

time="2017-04-01T01:58:31.221990800+01:00" level=error msg="Error during layer Store.Cleanup(): open C:\\ProgramData\\do
cker\\windowsfilter: The system cannot find the file specified."
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : In
valid pointer

```

Could it be a network driver error since i'm using virtIO?

**Comment by sinqinc** [comment] 2017-04-01 18:13
I've rebooted the server and the server hanged again so I reverted the snapshot and did the manual install again.

I've runned dockerd -D -b "none" and the deamon didn't froze.

I runned dockerd -D again "Hyper-V network adapter" and found a new Device in the Device manager.

This likely the device that break the server.

Do you have any advice on how I should configure docker ?

I don't think I need that network adapter.

**Comment by sinqinc** [comment] 2017-04-04 15:23
@friism @johnstep  I changed the network adapter to IntelPro instead of the KVM adapter and Dockerd doesn'T fail. The system doesn't hang too. Since that adapter is limited to 1Gb instead of 10Gb it's a workaround.

**Comment by friism** [comment] 2017-04-04 18:40
@sinqinc thanks for posting the workaround.

I'm pinging @dineshgovindasamy, @kallie-b and @JMesser81 in case they're interested in helping troubleshoot KVM networking problems.

**Comment by drnybble** [comment] 2017-04-10 15:16
I am installing Docker on a Server 2016 VM running under VMWare and am seeing similar behaviour. The VM seems to boot up but is very slow. Nothing on the desktop works, I just have a busy icon spinning.

**Comment by sinqinc** [comment] 2017-04-12 14:12
@drnybble Using a e1000 or something similar is working for me. The VirtIO driver is complety hanging the system.

**Comment by thaJeztah** [comment] 2017-06-13 00:06
ping  @dineshgovindasamy, @kallie-b and @JMesser81

**Comment by JMesser81** [comment] 2017-06-13 21:21
@drnybble/ @sinqinc   - Is this issue still active?

**Comment by sinqinc** [comment] 2017-06-14 00:56
Yes we can't use docker on Windows 2016 on KVM with VirtIo drivers

**Comment by JMesser81** [comment] 2017-06-14 03:21
We had a similar issue recently reported where WinNAT service was not started and this prevented HNS from creating the default nat network. Please check:
_PS C:\> Get-Service WinNAT_
if it's not running, 
_PS C:\> Start-Service WinNAT_

If that fails, please collect traces using the script here: 
https://github.com/Microsoft/Virtualization-Documentation/blob/live/windows-server-container-tools/CleanupContainerHostNetworking/WindowsContainerNetworking-LoggingAndCleanupAide.ps1

WindowsContainerNetworking-LoggingAndCleanupAide.ps1 -CaptureTraces
<repro - restart docker daemon>

zip up traces and attach

**Comment by taha** [comment] 2017-09-12 11:29
Any updates on this? I'm facing the same issue where my Windows Server 2016 hangs completely after installing docker. I also have the Red Hat VirtIO Ethernet Adapter as the single adapter on my VPS and doubt I'd be able to change it.

@drnybble did you manage to find a workaround?

cc @sinqinc

**Comment by mbentley** [comment] 2017-10-02 23:28
I can also reproduce this; using a Red Hat VirtIO ethernet adapter makes the system completely unusable but e1000 is fine.

**Comment by JMesser81** [comment] 2017-10-03 01:51
traces?

**Comment by mbentley** [comment] 2017-10-03 01:55
I’ll have to try it tomorrow on another VM I can leave in a bad state as any action easily takes 100x longer.

**Comment by mbentley** [comment] 2017-10-03 16:40
So I don't get the full output, only here as Docker can't start:

```
PS C:\Users\Administrator\Desktop> .\net.ps1 -CaptureTraces

Status   Name               DisplayName
------   ----               -----------
Running  Docker             docker
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

But here is the logs that it did collect when I attempted to start Docker:
[20171003_163418_PreCleanupState_NSHBXCJA.zip](https://github.com/moby/moby/files/1353065/20171003_163418_PreCleanupState_NSHBXCJA.zip)

As you can see, the daemon doesn't start:
```
PS C:\Users\Administrator> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
PS C:\Users\Administrator> start-service docker
PS C:\Users\Administrator> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

And when I run the daemon manually from the CLI, you can see it hangs:
```
PS C:\Users\Administrator> dockerd
time="2017-10-03T12:16:31.454414500-04:00" level=info msg="Windows default isolation mode: process"
time="2017-10-03T12:16:31.481757600-04:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-10-03T12:16:31.481757600-04:00" level=info msg="Loading containers: start."
time="2017-10-03T12:16:31.482733400-04:00" level=info msg="Restoring existing overlay networks from HNS into docker"
```

Hopefully that helps.

**Comment by JMesser81** [comment] 2017-10-03 21:34
Can you please try and restart HNS service?
PS C:\> Restart-Service HNS

Then try and restart daemon. 

If that doesn't work, please stop HNS service, delete the old HNS.data file (C:\ProgramData\Microsoft\Windows\HNS\HNS.data) and C:\ProgramData\Docker\swarm directory and then restart the both HNS and Docker services

**Comment by mbentley** [comment] 2017-10-06 20:24
Sorry for the delay.  Looks like HNS is stuck in `Stopping` in the Services management console.

```
PS C:\Users\Administrator> restart-service hns
restart-service : Service 'Host Network Service (hns)' cannot be stopped due to the following error: Cannot stop hns service on computer '.'.
At line:1 char:1
+ restart-service hns
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Restart-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.RestartServiceCommand
```

**Comment by srelf-ukcloud** [comment] 2017-10-26 22:26
Im also experiencing this on KVM running under openstack on RHEL using the virt-io drivers. Any news or more information people need providing.

**Comment by friism** [comment] 2017-10-26 23:00
@srelf-ukcloud @sinqinc @drnybble in addition to posting on this issue (which is great for discoverability and getting lots of folks looking at the problem) I encourage you to also open support tickets with Microsoft support. You're running Docker Enterprise Edition on Windows Server, and that is supported by Microsoft (who can escalate if required).

**Comment by drnybble** [comment] 2017-10-27 12:43
@friism It is not really clear that you are supposed to contact Microsoft. It would be great to spell this out somewhere in the Docker store. For instance, https://docs.docker.com/docker-for-windows/faqs/#what-if-i-have-problems-or-questions tells you to log issues on github but doesn't mention contacting Microsoft support.

**Comment by srelf-ukcloud** [comment] 2017-10-27 12:57
Hey all, sooo i spent some time last night working on this. I managed to fix it for me, buy installing the latest virt-io driver for the network card from virt-io-win-0.1.141...
![image](https://user-images.githubusercontent.com/24570050/32104972-b1154950-bb1e-11e7-870f-49d66d0e3f8c.png)

Seems to have resolved the problem for me. YMMV of course.

**Comment by mbentley** [comment] 2017-10-31 17:18
Thanks @srelf-ukcloud!  I confirmed that using the 0.1.141 virtio network drivers do work properly with Docker installed and running.

**Comment by thaJeztah** [comment] 2017-10-31 17:43
Looks like this is resolved, and not an issue in the docker code. Closing this issue, but feel free to discuss

**Closed by thaJeztah** 2017-10-31 17:43 UTC
Labels: platform/windows
