### ISSUE TITLE
There is no option to attach to a running container in a swarm mode

### ISSUE THREAD

**Issue by groyee** [moby/moby#33914] opened 2017-07-01 19:27 UTC
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

In the old  swarm there was an option to attach to a running container.

`docker exec -it CONTAINER_ID bash`

With the current swarm this is no more possible unless you first ssh to the running machine. Isn't the whole point of swarm services and tasks that you shouldn't care on which physical host the container is actually running?

**Comment by vovimayhem** [comment] 2017-07-05 05:35
That's actually not attaching to a running process, but rather running a new command (`bash`) in a swarm service's running container...

...anyways... that's precisely what I'm looking for, a way to run commands in a swarm service's container *from my docker client*, instead of SSH'ing my way into whatever server is running a container for the service, and then run `docker exec` in that server...

I suspect that it is not a current feature at all... is there some discussion regarding how to achieve this??

**Comment by groyee** [comment] 2017-07-05 12:42
For now I wrote this script.

Assuming you are running on a machine where you can access all your nodes with docker-machine ssh.



```
#! /bin/bash


TASKID=$(d service ps prod --format '{{.ID}}' --filter "name=$1")
HOST=$(d service ps prod --format '{{.Node}}' --filter "name=$1")
CONTAINER_ID=$(docker inspect $TASKID  --format '{{.Status.ContainerStatus.ContainerID}}')

eval $(docker-machine env $HOST)
docker exec -it $CONTAINER_ID bash
```

You pass to this script, the name of the **Task** you want to connect to.

But this is just a workaround....

**Comment by thaJeztah** [comment] 2023-09-16 20:20
- closing as duplicate of https://github.com/moby/moby/issues/27552

**Closed by thaJeztah** 2023-09-16 20:20 UTC
Labels: kind/feature, area/swarm, version/17.06
