### ISSUE TITLE
Downloading image over slow connection results in `unexpected EOF`.

### ISSUE THREAD

**Issue by LukeusMaximus** [moby/moby#35686] opened 2017-12-04 10:44 UTC
**Description**

Attempting to pull a particular image from our private registry results in this final output:
```
$ docker pull REDACTED
latest: Pulling from REDACTED
60730f960363: Already exists 
f7d512d82502: Already exists 
a7cad26d0357: Already exists 
25bb6f291ceb: Already exists 
630ceed02486: Already exists 
ba91036e1da2: Pull complete 
3afae30efbfe: Pull complete 
b8ed963194d7: Downloading [==================================================>]  29.06MB/29.06MB
208731f42878: Downloading [=============================>                     ]  79.48MB/136.6MB
d8f65ebf5058: Downloading [==================================================>]  3.417MB/3.417MB
3ddc9bb22fe8: Downloading [==================================================>]  31.46MB/31.46MB
16e6b025d0cc: Download complete 
46a45138fab4: Download complete 
2ac332f39267: Download complete 
unexpected EOF

```
When the dynamic output goes through a few phases:
1. `208731f42878` is downloading. `b8ed963194d7` and `d8f65ebf5058` have "Retrying" countdowns.
2. `b8ed963194d7` and `d8f65ebf5058` decide to start downloading when the 20 second retry countdown reaches 0 (is this Docker's largest retry timeout?). They then display 100% downloaded but never display "Download complete". `208731f42878` is still downloading.
3. `3ddc9bb22fe8` starts downloading, this reaches 100% and `208731f42878` is still downloading.
4. The remaining three images complete their downloads very quickly, then "unexpected EOF" is printed and the program exits  

**Steps to reproduce the issue:**
Ultimately, I'm unsure what causes this issue. However this only started happening recently when our internet connection was downgraded due to an office move. I therefore suggest:
1. Attempt to pull an image with layers of largely varying sizes (some layers roughly 1/4 the size of some others) over a connection with low bandwidth.

**Describe the results you received:**
The larger download `208731f42878` appears to block the smaller downloads until the biggest retry timeout expires (due to lack of bandwidth?), at which point Docker bizarrely assumes that the download is now 100% complete for both downloads.

The issue is observed on every attempt to pull this image.

**Describe the results you expected:**
The downloads at 100% should instead read "Download complete" instead of having full progress bars.
Docker pull should wait for still downloading images to finish before doing whatever it is that causes the "unexpected EOF".

**Additional information you deem important (e.g. issue happens only occasionally):**
This started happening after an office move which resulted in degraded bandwidth.

**Output of `docker version`:**
```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 5
 Paused: 0
 Stopped: 6
Images: 127
Server Version: 17.11.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 316
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-40-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54GiB
Name: luke-thinkpad
ID: JIYB:V3WA:TB4U:7QDB:S7Y4:2R2U:7XLY:C4LK:W4GL:2DFT:CZZ3:24LJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker installed on own laptop. Private registry on AWS.

**Comment by LukeusMaximus** [comment] 2017-12-04 13:14
Setting `max-concurrent-downloads: 1` produced this:
```
$ docker pull REDACTED
latest: Pulling from REDACTED
60730f960363: Already exists 
f7d512d82502: Already exists 
a7cad26d0357: Already exists 
25bb6f291ceb: Already exists 
630ceed02486: Already exists 
ba91036e1da2: Pull complete 
3afae30efbfe: Pull complete 
b8ed963194d7: Downloading [==================================================>]  29.06MB/29.06MB
208731f42878: Waiting 
d8f65ebf5058: Waiting 
3ddc9bb22fe8: Waiting 
16e6b025d0cc: Waiting 
46a45138fab4: Waiting 
2ac332f39267: Waiting 
unexpected EOF
```
The image `b8ed963194d7` exhausts all of the iterations of the retry timer as it did before, then produces this full progress bar, then declares unexpected EOF.

**Comment by LukeusMaximus** [comment] 2017-12-04 15:30
Strangely, this issue only occurs with this specific image. We cannot reproduce it on other images. However, multiple people have confirmed that they encounter the same issue when downloading this image and that it's not just me going gradually insane.

**Comment by thaJeztah** [comment] 2017-12-05 04:55
Is there sufficient disk space on the machine? Anything useful in the system and/or daemon logs (preferably with the daemon in debug mode)?

**Comment by LukeusMaximus** [comment] 2017-12-05 14:36
There's certainly enough disk space. The logs show nothing extra regarding blob download. Just "pulling blob xxxx" and "Download failed, retrying: unexpected EOF" messages.

**Comment by sandersaares** [comment] 2017-12-13 05:42
I can confirm I have occasionally seen this type of failure in failed automated build logs, though quite rarely - I only recall a few instances and none recently enough for me to still have logs.

**Comment by LukeusMaximus** [comment] 2017-12-13 15:49
Since opening this, we've switched to Google Container Registry from the Docker one. We've not had any problems since then. Maybe the problem lies in that project. Should this issue be closed?

**Comment by thaJeztah** [comment] 2017-12-13 15:57
It could relate to the configuration of the registry (or the storage driver used for it), but without logs, it's hard to tell.

Yes, closing this issue because there's no reproducible case now to investigate

**Closed by thaJeztah** 2017-12-13 15:57 UTC
Labels: area/distribution, version/17.11
