### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): write file : no space left on device

### ISSUE THREAD

**Issue by gbenmansour** [moby/moby#32811] opened 2017-04-25 13:42 UTC
**Description**
I'm using docker on windows 7 via docker toolbox , when trying to pull a big image of 4 Go I get the following output 
latest: Pulling from preintv2
50655cf8037a: Extracting [==================================================>] 4.055 GB/4.055 GB
failed to register layer: Error processing tar file(exit status 1): write file : no space left on device

What I find unusual is that when I type df -h :

$ df -h
Filesystem            Size  Used Avail Use% Mounted on
C:/Program Files/Git  239G  187G   52G  79% /
U:                    3,0T  2,5T  494G  84% /u
V:                     20G  8,4G   11G  44% /v
X:                     14G  2,2G   11G  17% /x
Z:                     16G   37K   16G   1% /z

in the partition /u the size is 3.0T I don't know from where it comes , in my windows C:/ partition it remains only 80Go .

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
time="2017-04-25T15:39:42+02:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
time="2017-04-25T15:22:02+02:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: CYXK:K7TN:O3OZ:SVML:FCLM:PLSB:SL4P:2ZF4:7VF2:H6UM:W2YI:FIW6
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 26
 System Time: 2017-04-25T13:22:02.240737949Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by jphuynh** [comment] 2017-04-25 13:59
It looks similar to #9755 and #10613. Can you try to run `df -i` as explained the issues I mentioned?

**Comment by cpuguy83** [comment] 2017-04-28 04:13
You're also using Docker in a VM which has a max size that is smaller than your windows partitions.

**Comment by thaJeztah** [comment] 2017-04-29 02:35
This doesn't look like a bug, and indeed because the VM has a smaller disk assigned, so the "out of space" is most likely because the VM is out of space.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-04-29 02:35 UTC
Labels: version/17.04

**Comment by vivekreddychagam544** [comment] 2018-02-24 09:27
plz tell me the salutation to this     Service 'bb-db' failed to build: failed to register layer: Error processing tar file(exit status 1): write /opt/mssql/lib/sqlservr.sfp: no space left on device

**Comment by ombits** [comment] 2018-03-12 17:06
@vivekreddychagam544 : kindly run : run docker rmi $(docker images -q --filter "dangling=true")

as mention https://github.com/moby/moby/issues/9755

**Comment by vardhmanandroid2015** [comment] 2018-11-12 07:46
I face similar issue almost on daily basis. 
Best way is to check how much space can be reclaimed due to unused images.
docker system df
If RECLAIMABLE amount is greater than zero (that would definitely the case) then run command
docker system prune -a
this command will cleaned up all the unused space. 

This command will clean up-
        - all stopped containers
        - all networks not used by at least one container
        - all images without at least one container associated to them
        - all build cache

**Comment by 1wpro2** [comment] 2019-12-06 06:21
I have just encountered the same issue. Having increased the disk size allocation sorted it out.

**Comment by flavienbwk** [comment] 2020-05-06 23:40
Have the problem. Running Docker rootless, my storage is :

```
/dev/vda1       18990856 2845112  15257124  16% /
```

**Comment by sparklecast1** [comment] 2020-06-24 18:10
i also have the problem.
# free -h
              total        used        free      shared  buff/cache   available
Mem:           2.8G        307M        1.7G        8.6M        823M        2.3G
Swap:          3.0G          0B        3.0G

# df -h
Filesystem           Size  Used Avail Use% Mounted on
devtmpfs             1.4G     0  1.4G   0% /dev
tmpfs                1.5G     0  1.5G   0% /dev/shm
tmpfs                1.5G  8.6M  1.4G   1% /run
tmpfs                1.5G     0  1.5G   0% /sys/fs/cgroup
/dev/mapper/cl-root   26G  2.0G   25G   8% /
/dev/sda1           1014M  178M  837M  18% /boot
tmpfs                287M     0  287M   0% /run/user/0

**Comment by magzim21** [comment] 2022-01-20 22:39
I've got this error doing `docker-compose pull`
`docker system prune -a` and `docker rmi $(docker images -q --filter "dangling=true")` did not help.

I've pulled each image individually - that was the fix ✅
