### ISSUE TITLE
Docker iptables chain rules disappear after some time 

### ISSUE THREAD

**Issue by dstrbad** [moby/moby#48530] opened 2024-09-19 08:26 UTC
### Description

On our Debian GNU/Linux 11 (bullseye), ARM64 server we lose networking on all our containers. Nothing is reachable from within containers. We noticed that for unknown reason iptables/nftables DOCKER chain rules disappear. 

Only fix is to recreate network using docker compose command. We have multiple instances running the same setup and this behavior occurs at random times on random instances. 

Any suggestions how to approach this issue?

Thank you!

### Reproduce

No known steps to reproduce at the moment.

### Expected behavior

Networking constantly uninterrupted. 

### docker version

```bash
docker version
Client: Docker Engine - Community
 Version:           24.0.1
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        6802122
 Built:             Fri May 19 18:05:49 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.1
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       463850e
  Built:            Fri May 19 18:05:49 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 24.0.1
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 5.10.104-cip3
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.889GiB
 Name: ASC-POD-TJIV-TJ2-OV35
 ID: 066ba618-6a40-4b2d-826f-69f022e03599
 Docker Root Dir: /home/host/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info
**nftables** related log from `/var/log/syslog`

```
Sep 16 14:35:15 HOST kernel: [   21.409838] Bridge firewalling registered
Sep 16 14:35:17 HOST dockerd-rootless.sh[1017]: time="2024-09-16T14:35:17.131022551+02:00" level=info msg="skipping firewalld management for rootless mode"
Sep 16 15:17:45 HOST systemd[1]: Stopping nftables...
Sep 16 15:17:45 HOST systemd[1]: nftables.service: Succeeded.
Sep 16 15:17:45 HOST systemd[1]: Stopped nftables.
Sep 16 15:17:45 HOST systemd[1]: Starting nftables...
Sep 16 15:17:45 HOST systemd[1]: Finished nftables.
Sep 16 15:22:46 HOST systemd[1]: Finished nftables.
Sep 16 15:22:48 HOST tailscaled[362]: router: using firewall mode pref
Sep 16 15:22:51 HOST kernel: [   15.313822] Bridge firewalling registered
Sep 16 15:22:56 HOST dockerd-rootless.sh[1044]: time="2024-09-16T15:22:56.533450573+02:00" level=info msg="skipping firewalld management for rootless mode"
Sep 16 15:45:52 HOST systemd[1]: Finished nftables.
```

**nft list ruleset**

```
table inet filter {
}
table ip nat {
        chain prerouting {
                type nat hook prerouting priority filter; policy accept;
                iifname "eno2" tcp dport 102 counter packets 0 bytes 0 dnat to 192.168.200.2:102
        }

        chain postrouting {
                type nat hook postrouting priority srcnat; policy accept;
                oifname "eno1" masquerade
        }

        chain DOCKER {
                iifname "docker0" counter packets 0 bytes 0 return
        }

        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                oifname != "docker0" ip saddr 172.17.0.0/16 counter packets 0 bytes 0 masquerade
        }

        chain PREROUTING {
                type nat hook prerouting priority dstnat; policy accept;
                fib daddr type local counter packets 3957 bytes 300556 jump DOCKER
        }

        chain OUTPUT {
                type nat hook output priority -100; policy accept;
                ip daddr != 127.0.0.0/8 fib daddr type local counter packets 20 bytes 1200 jump DOCKER
        }
}
table ip filter {
        chain DOCKER {
        }

        chain DOCKER-ISOLATION-STAGE-1 {
                iifname "docker0" oifname != "docker0" counter packets 0 bytes 0 jump DOCKER-ISOLATION-STAGE-2
                counter packets 0 bytes 0 return
        }

        chain DOCKER-ISOLATION-STAGE-2 {
                oifname "docker0" counter packets 0 bytes 0 drop
                counter packets 0 bytes 0 return
        }

        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                counter packets 0 bytes 0 jump DOCKER-USER
                counter packets 0 bytes 0 jump DOCKER-ISOLATION-STAGE-1
                oifname "docker0" ct state related,established counter packets 0 bytes 0 accept
                oifname "docker0" counter packets 0 bytes 0 jump DOCKER
                iifname "docker0" oifname != "docker0" counter packets 0 bytes 0 accept
                iifname "docker0" oifname "docker0" counter packets 0 bytes 0 accept
        }

        chain DOCKER-USER {
                counter packets 0 bytes 0 return
        }
}
table ip6 filter {
}
table ip6 nat {
}
```

**Comment by akerouanton** [comment] 2024-09-19 09:49
Hi @dstrbad, thanks for reporting.

I've a few observations. I see you're using nft, but the Engine doesn't support that. It uses `iptables` binaries (either `iptables-legacy` or `iptables-nft`). We'll add support for `nftables` in the near future, but for the time being your whole system has to stick with `iptables`.

I see you're also using tailscale. Did you opt-in for the `auto` or `nftables` firewall modes as per documented here https://tailscale.com/kb/1294/firewall-mode#how-to-set-the-firewall-mode?

I see you're running Docker in rootless mode, but it seems `nft list ruleset` was called from the host netns. Is that correct?

And finally, I see two weird logs there:

- `skipping firewalld management for rootless mode` should be logged only once, when the Engine starts.
- `Bridge firewalling registered` -> that comes from the init function in the `br_netfilter` kernel module (see [here](https://github.com/torvalds/linux/blob/de848da12f752170c2ebe114804a985314fd5a6a/net/bridge/br_netfilter_hooks.c#L1346)). But more interestingly, the monotic time between brackets is lower in the 2nd instance (`kernel: [   21.409838]` vs `kernel: [   15.313822]`), which seems to indicate the server rebooted.

Are you sure your server wasn't rebooted around 15:17? Is that all the logs you have between 14:35 and 15:17?

**Comment by dstrbad** [comment] 2024-09-19 10:01
Hi @akerouanton 

1) on this host we do have tailscale, on most of them we don't use it. We opt-in for the `auto`

2) that's correct, `nft list ruleset` was called from the host

3) yes, that's what's strange, based on `uptime` and monitoring service we use device wasn't rebooted

4) here's the bigger `/var/log/syslog` snippet
```
Sep 16 14:35:04 HOST systemd[1]: Finished nftables.
Sep 16 14:35:06 HOST tailscaled[361]: router: using firewall mode pref
Sep 16 14:35:15 HOST kernel: [   21.409838] Bridge firewalling registered
Sep 16 14:35:17 HOST dockerd-rootless.sh[1017]: time="2024-09-16T14:35:17.131022551+02:00" level=info msg="skipping firewalld management for rootless mode"
Sep 16 15:17:45 HOST systemd[1]: Stopping nftables...
Sep 16 15:17:45 HOST systemd[1]: nftables.service: Succeeded.
Sep 16 15:17:45 HOST systemd[1]: Stopped nftables.
Sep 16 15:17:45 HOST systemd[1]: Starting nftables...
Sep 16 15:17:45 HOST systemd[1]: Finished nftables.
Sep 16 15:22:46 HOST systemd[1]: Finished nftables.
Sep 16 15:22:48 HOST tailscaled[362]: router: using firewall mode pref
Sep 16 15:22:51 HOST kernel: [   15.313822] Bridge firewalling registered
Sep 16 15:22:56 HOST dockerd-rootless.sh[1044]: time="2024-09-16T15:22:56.533450573+02:00" level=info msg="skipping firewalld management for rootless mode"
Sep 16 15:45:52 HOST systemd[1]: Finished nftables.
Sep 16 15:45:55 HOST tailscaled[372]: router: using firewall mode pref
Sep 16 15:45:58 HOST kernel: [   15.219472] Bridge firewalling registered
Sep 16 15:46:04 HOST dockerd-rootless.sh[1039]: time="2024-09-16T15:46:04.094495210+02:00" level=info msg="skipping firewalld management for rootless mode"
Sep 16 15:51:20 HOST systemd[1]: Finished nftables.
Sep 16 15:51:22 HOST tailscaled[340]: router: using firewall mode pref
Sep 16 15:51:31 HOST kernel: [   19.804020] Bridge firewalling registered
Sep 16 15:51:32 HOST dockerd-rootless.sh[1012]: time="2024-09-16T15:51:32.154703291+02:00" level=info msg="skipping firewalld management for rootless mode"
Sep 16 16:12:51 HOST systemd[1]: Finished nftables.
Sep 16 16:12:53 HOST tailscaled[351]: router: using firewall mode pref
Sep 16 16:13:01 HOST kernel: [   20.651411] Bridge firewalling registered
Sep 16 16:13:03 HOST dockerd-rootless.sh[1024]: time="2024-09-16T16:13:03.384228995+02:00" level=info msg="skipping firewalld management for rootless mode"
Sep 16 16:34:03 HOST systemd[1]: Stopping nftables...
Sep 16 16:34:03 HOST systemd[1]: nftables.service: Succeeded.
Sep 16 16:34:03 HOST systemd[1]: Stopped nftables.
Sep 16 16:34:03 HOST systemd[1]: Starting nftables...
Sep 16 16:34:03 HOST systemd[1]: Finished nftables.
Sep 16 16:34:07 HOST systemd[1]: Stopping nftables...
Sep 16 16:34:07 HOST systemd[1]: nftables.service: Succeeded.
Sep 16 16:34:07 HOST systemd[1]: Stopped nftables.
Sep 16 16:34:07 HOST systemd[1]: Starting nftables...
Sep 16 16:34:07 HOST systemd[1]: Finished nftables.
Sep 16 16:35:31 HOST systemd[1]: Finished nftables.
Sep 16 16:35:33 HOST tailscaled[366]: router: using firewall mode pref
Sep 16 16:35:40 HOST kernel: [   18.783099] Bridge firewalling registered
Sep 16 16:35:41 HOST dockerd-rootless.sh[898]: time="2024-09-16T16:35:41.535841965+02:00" level=info msg="skipping firewalld management for rootless mode"
```

**Comment by akerouanton** [comment] 2024-09-19 10:27
> on this host we do have tailscale, on most of them we don't use it. We opt-in for the auto

Make sure you use `iptables` modes for now.

> here's the bigger /var/log/syslog snippet

systemd / journald don't write to `/var/log/syslog` themselves, so I guess you have something like `rsyslog` running. Are you sure it doesn't filter some logs? Could you instead take a look at `journalctl --since '2024-09-16 14:30:00' --until '2024-09-16 16:36:00`?

**Comment by dstrbad** [comment] 2024-09-19 12:28
> Make sure you use iptables modes for now.

sure, thanks!

> systemd / journald don't write to /var/log/syslog themselves, so I guess you have something like rsyslog running. Are you sure it doesn't filter some logs? Could you instead take a look at journalctl --since '2024-09-16 14:30:00' --until '2024-09-16 16:36:00?

log attached

[2024-09-16_14-30-00--16-36-00.log](https://github.com/user-attachments/files/17058999/2024-09-16_14-30-00--16-36-00.log)

**Comment by akerouanton** [comment] 2024-09-19 12:38
@dstrbad Okay, so your server rebooted multiple times in that time frame:

```
$ grep -nri "Booting Linux on physical CPU" ~/Downloads/2024-09-16_14-30-00--16-36-00.log | wc -l
       6
```

Also these logs seem to indicate you're running two daemons, one in 'rootful' mode, and the other in rootless mode:

```
Sep 16 16:35:39 HOST dockerd[808]: time="2024-09-16T16:35:39.144568324+02:00" level=info msg="Starting up"
Sep 16 16:35:39 HOST dockerd-rootless.sh[898]: time="2024-09-16T16:35:39.159555709+02:00" level=info msg="Starting up"
```

**Comment by dstrbad** [comment] 2024-09-19 13:40
Huh, that's strange but yes, you're right.

- do you have any explanation why just sometimes we have manifestation where there is no docker chain rules?

- sorry for ingorance, but we're not allowed to run two daemons? could this be the cause of the issues?

Thank you!

**Comment by dstrbad** [comment] 2024-09-20 15:28
Thanks a lot, will dig into it.

**Comment by akerouanton** [comment] 2024-10-07 06:33
@dstrbad Were you able to investigate further?

**Comment by dstrbad** [comment] 2024-10-07 11:11
@akerouanton a bit, but still unable to reproduce, although:
1) this happens after hard reboots, not always. we confirmed that we're having them on multiple devices
2) "rootless" and "rootfull" were enabled in parallel, we resolved this and only rootless is active
3) we fully removed all custom stuff related to iptables and migrated it to nft 

I guess this issue can be closed for now since we can't reproduce it and it seems like some edge case we're facing rarely.

**Comment by akerouanton** [comment] 2024-10-07 12:30
Okay, let me close it but feel free to ping me if you're able to come up with a reproducer.

**Closed by akerouanton** 2024-10-07 12:30 UTC
Labels: status/more-info-needed, kind/bug, area/networking, version/24.0
