### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by gopal86** [moby/moby#36428] opened 2018-02-27 15:26 UTC
when i am running 

> sudo docker run -p 127.0.0.1:5601:5601 \
>     -v $(pwd)/credentials.cfg:/mordred-override.cfg \
>     -t grimoirelab/full

I am getting this error :- 
`
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/home/vallabh/Study/Gsoc/CHAOSS/credentials.cfg\\\" to rootfs \\\"/var/lib/docker/overlay2/e8414840253368cc56ef1da4ff299813e917d6e62996efa7760a857e65b78855/merged\\\" at \\\"/var/lib/docker/overlay2/e8414840253368cc56ef1da4ff299813e917d6e62996efa7760a857e65b78855/merged/mordred-override.cfg\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`

Can anyone help me out to solve this issue ?

**Comment by thaJeztah** [comment] 2018-03-01 00:35
This is the error;

    Ae you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

If the path you're trying to bind-mount in the container (`home/vallabh/Study/Gsoc/CHAOSS/credentials.cfg`) does not exist on the host where the daemon runs, docked will create an empty directory with that name, and mount it in the container.

If a file exists at the target path inside the container (`/mordred-override.cfg`), mounting will fail because you cannot mount a directory on top of a file.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-03-01 00:35 UTC
