### ISSUE TITLE
docker daemon 1.12.6 hung: docker ps not responding

### ISSUE THREAD

**Issue by g0194776** [moby/moby#35596] opened 2017-11-24 19:20 UTC
Hi guys,

   This is a VM(CentOS7) which running with docker 1.12.6. We're using devicemapper as file system currently BUT what I guessed that the devicemapper DOES NOT the main reason occurs docker daemon unresponsive.

   Before it happens, We've met a remote NFS driver hangs.

[docker-daemon-unresponsive_10.202.40.230.log](https://github.com/moby/moby/files/1502417/docker-daemon-unresponsive_10.202.40.230.log)

**Comment by swade1987** [comment] 2017-11-25 14:30
Do you have swap disabled on your nodes?

**Comment by thaJeztah** [comment] 2017-11-25 15:05
Docker 1.12 has reached EOL in March, and is no longer maintained.

Also, when reporting a bug, be sure to provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-25 15:05 UTC

**Comment by g0194776** [comment] 2017-11-26 13:37
@swade1987 Why do I need to disable the swap? best practices? 

Thanks a lot.

**Comment by swade1987** [comment] 2017-11-27 09:05
@g0194776 because from what I have seen Docker and swap don't play nicely.
