### ISSUE TITLE
UDP/TCP sockets are not scaling inside Windows container

### ISSUE THREAD

**Issue by artisticcheese** [moby/moby#34355] opened 2017-08-01 14:31 UTC
**Description**

Trying to query UDP inside windows container will fail after about 20 fast UDP queries
**Steps to reproduce the issue:**
1. Run following powershell in container
2.
```
Function QueryNTP
{
    $server = "pool.ntp.org"
    [Byte[]]$NtpData = , 0 * 48
    $NtpData[0] = 0x1B    # NTP Request header in first byte  
    $Socket = New-Object -TypeName Net.Sockets.Socket -ArgumentList ([Net.Sockets.AddressFamily]::InterNetwork,
        [Net.Sockets.SocketType]::Dgram,
        [Net.Sockets.ProtocolType]::Udp)
    $Socket.SendTimeOut = 2000  # ms
    $Socket.ReceiveTimeOut = 2000   # ms

    Try
    {
        $Socket.Connect($Server, 123)
    }
    Catch
    {
        Write-Error -Message "Failed to connect to server $Server"
        Throw 
    }

    Try
    {
        [Void]$Socket.Send($NtpData)      # Send request header
        [Void]$Socket.Receive($NtpData)   # Receive 48-byte NTP response
    }
    Catch
    {
        Write-Error -Message "Failed to communicate with server $Server"
        Throw
    }
    $Socket.Shutdown('Both') 
    $Socket.Close()
    return $NtpData[0]
}
1..1000 | ForEach-Object {QueryNTP}
```
3.

**Describe the results you received:**
Socket inside Windows container will fail after about 20 or so queries
```
PS C:\inetpub\logs\logfiles\host\W3SVC1> .\udp-client.ps1
28
28
28
28
28
28
28
28
28
28
QueryNTP : Failed to communicate with server pool.ntp.org
At C:\inetpub\logs\logfiles\host\W3SVC1\udp-client.ps1:36 char:27
+ 1..1000 | ForEach-Object {QueryNTP}
+                           ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,QueryNTP

Exception calling "Receive" with "1" argument(s): "A connection attempt failed because the connected party did not
properly respond after a period of time, or established connection failed because connected host has failed to respond"
At C:\inetpub\logs\logfiles\host\W3SVC1\udp-client.ps1:25 char:9
+         [Void]$Socket.Receive($NtpData)   # Receive 48-byte NTP respo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SocketException
```

**Describe the results you expected:**
Shall succeed since it works just fine on the host 

**Additional information you deem important (e.g. issue happens only occasionally):**
All the time
**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 60
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 63.92GiB
Name: CND70637PKZBook
ID: USBG:5JH4:XBR7:SDUP:YOWD:7NRG:XA2E:NCGB:R7TT:RITI:YW3N:AB52
Docker Root Dir: D:\images
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 40157
 System Time: 2017-08-01T09:31:26.4906816-05:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

**Comment by friism** [comment] 2017-08-02 15:41
cc @msabansal

**Comment by artisticcheese** [comment] 2017-08-02 18:31
This seems to be affecting TCP sockets too. As far as I'm concerned this is major issue since the rest of perfomance inside container depends on TCP/UDP sockets to perform well. Test for TCP sockets is below.  


```
Function Send-TCPMessage
{ 
    Param ( 
        [Parameter(Mandatory = $true, Position = 0)]
        [ValidateNotNullOrEmpty()] 
        [string] 
        $EndPoint
        , 
        [Parameter(Mandatory = $true, Position = 1)]
        [int]
        $Port
        , 
        [Parameter(Mandatory = $true, Position = 2)]
        [string]
        $Message
    ) 
    Process
    {
        # Setup connection 
        $IP = [System.Net.Dns]::GetHostAddresses($EndPoint) 
        $Address = [System.Net.IPAddress]::Parse($IP) 
        $Socket = New-Object System.Net.Sockets.TCPClient($Address, $Port) 
        $socket.ReceiveTimeout = 2000;
        #$socket.SendTimeout = 2000;
        # Setup stream wrtier 
        $Stream = $Socket.GetStream() 
        $Writer = New-Object System.IO.StreamWriter($Stream)

        # Write message to stream
        $Message | % {
            $Writer.WriteLine($_)
            $Writer.Flush()
            Write-Output "Sending message "
        }
    
        # Close connection and stream
        $Stream.Close()
        $Socket.Close()
    }
}
1..1000 | ForEach-Object {Send-TCPMessage -Port 80 -Message $_ -EndPoint www.microsoft.com }
```

**Comment by msabansal** [comment] 2017-08-18 17:39
@artisticcheese I was busy with other issues. Following up on this case now.

**Comment by artisticcheese** [comment] 2017-08-18 17:56
There is official case filed with Microsoft support on this issue. You might want to check who is working on this. `117080416144787`

**Comment by JMesser81** [comment] 2017-08-21 02:46
@artisticcheese  - Thanks for reporting. I'm following up internally. FYI... I can repro these symptoms for both UDP and TCP on both my host (Windows 10) as well as within a HyperV server container.

**Comment by artisticcheese** [comment] 2017-08-26 17:00
Here is how perfomance looks like side by side
https://youtu.be/jlg4ZiDr1T8

**Comment by artisticcheese** [comment] 2017-09-26 14:46
This is confirmed issue with Windows containers and will be fixed in next version of windows. 

```
    •    Symptom - containers get timeouts when regularly opening TCP/UDP sockets
    •    Cause - current code defect
    •    Resolution - fix to be included in future version of windows
    •    More Information - no charge for case

```

**Comment by foragerr** [comment] 2017-10-07 04:37
@artisticcheese Are you able to share if you're seeing this with the default windows NAT networking? Wondering if transparent mode is any better.

**Comment by artisticcheese** [comment] 2017-10-07 12:10
Yes, this only with default NAT network.

**Comment by artisticcheese** [comment] 2018-05-13 19:40
FYI, Issue with horribly TCP sockets and timeouts with UDP sockets are still present in both 1709 and 1803. Image at https://hub.docker.com/r/artisticcheese/34355issue/ contains reproduction steps for both UDP failures and TCP slow performance.

To reproduce TCP issue issue `docker run --rm artisticcheese/34355issue:1803 powershell .\prep\tcpsocket.ps1` which will try to connect 100 times using TCP sockets to www.microsoft.com and for UDP `docker run --rm artisticcheese/34355issue:1803 powershell .\prep\udpsocket.ps1` which will fail after about 10 queries.

**Comment by thaJeztah** [comment] 2018-05-13 20:19
ping @JMesser81 @msabansal was a root cause identified on the Windows side for this?

**Comment by artisticcheese** [comment] 2018-05-13 21:31
Case number ` 117080416144787 ` if you want to follow up on this internally and below is last I heard from Microsoft representative on this. Issue was identified with microsoft networking stack on host.

```
Greg,

TCP
There is a failure in the SblNat module that is causing the outgoing SYN to be dropped when being received on the local machine’s external NIC.

[9]0004.004C::?2017?-?09?-?08 13:02:46.891 [Microsoft-Windows-WinNat]NAT instance H10ec4534-e3f3-4526-ad73-6993cfd9b121 failed to allocate a TCP  port dynamically because all ports in the instance's external address pool are in use. 
[9]0004.004C::?2017?-?09?-?08 13:02:46.891 [Microsoft-Windows-WinNat]NAT dropped IPv4 TCP  packet which arrived over INTERNAL  interface 11 in compartment 1 with reason: Failed to create a session object . 
[9]0004.004C::?2017?-?09?-?08 13:02:46.891 [Microsoft-Windows-TCPIP]TCPIP: Network layer (Protocol Unknown , AddressFamily = IPV4 ) dropped 1 packet(s). SourceAddress = 0.0.0.0    . DestAddress = 0.0.0.0    . Reason = 265. 


UDP
There is a similar failure in the SlbNat module that is causing the outgoing UDP packet to be dropped when being received on the local machine’s external NIC.

[9]0004.004C::?2017?-?09?-?08 16:08:24.157 [Microsoft-Windows-WinNat]NAT instance H10ec4534-e3f3-4526-ad73-6993cfd9b121 failed to allocate a UDP  port dynamically because all ports in the instance's external address pool are in use.
[9]0004.004C::?2017?-?09?-?08 16:08:24.157 [Microsoft-Windows-WinNat]NAT dropped IPv4 UDP  packet which arrived over INTERNAL  interface 11 in compartment 1 with reason: Failed to create a session object .
[9]0004.004C::?2017?-?09?-?08 16:08:24.158 [Microsoft-Windows-TCPIP]TCPIP: Network layer (Protocol Unknown , AddressFamily = IPV4 ) dropped 1 packet(s). SourceAddress = 0.0.0.0    . DestAddress = 0.0.0.0    . Reason = 265.

Thank you for pointing out the symptoms of these issues, my team will look into this further

```

**Comment by JMesser81** [comment] 2018-06-07 22:39
@artisticcheese 

We made multiple improvements to container networking performance in Windows Server version 1803 (RS4) and have tried to backport as many fixes as possible to Windows Server version 1709 (RS3). We also have some exciting improvements with Receive Segment Coalescing (RSC) which will further boost network performance in Windows Server 2019 (RS5). 

I was hopeful that all known perf issues would be gone but it sounds like you're still hitting this with recent builds. Let me check on the status of this issue internally  and see if there are any further updates to share. Thanks for the case number.

cc @davidschott

**Comment by JMesser81** [comment] 2018-06-11 18:17
Looks like this case was closed internally since the problem was believed to be resolved with Windows Server version 1803 and the latest Windows 10 client build. Please open a new case with Microsoft support. We'll also try and get the investigation going again on our side.

**Comment by cod7alex** [comment] 2018-06-12 15:04
Does it affect Windows Server 2016 images?

**Comment by artisticcheese** [comment] 2018-06-12 15:08
It affects every single windows container without regard of host versin or version of docker.

**Comment by rogersillito** [comment] 2018-06-20 09:43
I got here from [Issue 1214](https://github.com/docker/for-win/issues/1214), where [there was a query about the relationship between that issue and this one](https://github.com/docker/for-win/issues/1214#issuecomment-337283898), but that suggestion wasn't followed up (and the issue has gone quiet since October 2017).   Do you know if these are related issues?   I ran the UDP & TCP test scripts above and can also replicate this issue in my container environments. 

[I posted a comment on that other issue](https://github.com/docker/for-win/issues/1214#issuecomment-398429745) as I'm seeing what appears to be the same problem; which is a major blocker for our required use case.

**Comment by artisticcheese** [comment] 2018-06-20 13:01
If you want to see if issue the same or not run your container on bridge instead of NAT network and see if issue happening or not. This issue happens only on NAT network.

**Comment by rogersillito** [comment] 2018-06-20 15:45
@artisticcheese thanks for that - I tried running in a transparent network and the problem is gone, so it's likely to be the same issue.   The good news is I should be able to use that network type instead, so hopefully problem solved.

**Comment by JMesser81** [comment] 2018-06-26 18:18
@artisticcheese - I have a repro for both UDP and TCP on the latest insider build candidate (17704, RS5 Pre-release). I'm collecting traces and my dev team will be investigating shortly. 

For reference,  my setup is running Windows Server 17704 inside a VM. The VM is attached to an external vSwitch with direct connectivity to Microsoft CORP Network with 4 procs and 2048MB of memory. I then use the default (nat) network (internal vSwitch with WinNAT/ICS) and run the two tests - QueryNTP and Send-TCPMessage referenced above. 


I periodically see this error on the TCP test:
_Sending message
You cannot call a method on a null-valued expression.
At C:\Send-TCPMessage.ps1:37 char:9
+         $Stream.Close()
+         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Send-TCPMessage.ps1:38 char:9
+         $Socket.Close()
+         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull__

The UDP test might not be great sending to pool.ntp.org but I do see these errors as well: 

_28
28
QueryNTP : Failed to communicate with server pool.ntp.org
At C:\QueryNTP.ps1:36 char:27
+ 1..1000 | ForEach-Object {QueryNTP}
+                           ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,QueryNTP

Exception calling "Receive" with "1" argument(s): "A connection attempt failed because the connected party did not
properly respond after a period of time, or established connection failed because connected host has failed to respond"
At C:\QueryNTP.ps1:25 char:9
+         [Void]$Socket.Receive($NtpData)   # Receive 48-byte NTP respo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SocketException_

**Comment by artisticcheese** [comment] 2018-06-26 18:29
TCP and UDP issues are manifest differently. TCP manifests as very slow throughtput and UDP manifests as timeouts.

**Comment by harishsrini** [comment] 2018-06-28 02:37
The # of ports we allocate by default on the NAT side is 10 and the failures are due to this. Fortunately we have a registry setting that can be used to increase the # of default ports which will enable better scale. 

Set the below key and limit it to a value less than 0xFFFF
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinNat | REG_DWORD | PortChunkSize .

Please make this change and retry your scenario and let us know if it gets better.

**Comment by artisticcheese** [comment] 2018-06-28 03:07
Is it setting on host or container?

**Comment by harishsrini** [comment] 2018-06-28 16:57
The setting is on the Host. I will give this a try today and get back to you. Also are you running this on RS5 or RS4?

**Comment by artisticcheese** [comment] 2018-06-28 17:00
I'm running on LTSC 2016. So this registry entry only existent on later version of OSes?

**Comment by harishsrini** [comment] 2018-06-28 20:39
I am not sure the OS version for LTSC 2016. Do you mind dumping the output of winver?

**Comment by artisticcheese** [comment] 2018-06-28 20:41
Just normal Windows 2016 (original) 1607

**Comment by JMesser81** [comment] 2018-06-28 22:41
We have made a lot of fixes in Windows NAT (WinNAT) since Windows Server version 1803 (and Windows 10 April 2018 update) - internally known as RS4. I would recommend you upgrade to that build and re-test with the registry keys mentioned. Or even better, get a Windows Insider Preview build for Windows Server 2019!  https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver

**Comment by JMesser81** [comment] 2018-06-28 22:42
We will not be backporting these performance-related improvements to previously released versions so it is best to upgrade to Windows Server version 1803 (for now) and then move to WS2019 when it becomes available later this year.

**Comment by artisticcheese** [comment] 2018-06-28 22:46
So to summarize, fix for this issue was released in Windows 1803 and not enabled by default. Fix consists of registry entry which needs to be modified on host. Is it correct statement?

**Comment by JMesser81** [comment] 2018-06-28 23:13
There were multiple fixes to WinNAT released in 1803 - all enabled by default - including:
1) static port mappings were being deleted prematurely before being used
2) incorrect byte order (network byte-order vs host byte-order) in data path
3) general performance improvements

The most recent WinNAT network performance-related issue seen when running these test scripts and images (which still repro'd on 1803 and WS2019 pre-release builds) were caused by random packet drops due to the limited ports present for use by default with NAT when multiple connections were made. We increased this upper limit to 1000 by adjusting the registry key value and it scaled well in our test systems when using the test scripts provided with no observable packet drops. 

We do not plan to change the default number of ports used by NAT at this time and so users will need to increase the PortChunkSize (upper limit is 0xFFFF).

**Comment by artisticcheese** [comment] 2018-06-29 01:31
Confirming.  Setting registry setting and reboot solves the issue with TCP performance. Increase in performance 10x times (3s vs 35s). 
I'm questioning wisdom of not putting higher value as default setting since this issue is not very evident but is in fact limits performance of application running inside containers compared to running those directly on the host despite the promise from Microsoft that overhead of running inside container in process isolation is minimal. In this specific case we get hit 10x increase in latency.

**Comment by harishsrini** [comment] 2018-07-02 03:37
Thanks @artisticcheese 

As far as changing the default value is concerned, we will evaluate this internally and take the next steps. Thanks again for your feedback!

**Comment by gustavo-armenta** [comment] 2018-10-26 18:53
@harishsrini @JMesser81 @artisticcheese 
I noticed this exact performance problem after enabling canary tests and monitoring. My web application was failing very often to connect to SQL database with error System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The semaphore timeout period has expired.).
When doing tcp trace analysis, the container sends the tcp packet, the host does not respond with an ack, the container tries again 3 seconds later, and the host responds with 2 acks.
We moved to 1803, set the reg key PortChunkSize=1000, and reboot all nodes. The failures connecting to SQL database were resolved but the website takes 4-10 seconds to complete operations that in the on-premise datacenter without containers complete in less than 3 seconds.
Are there any other tweaks to improve performance of containers orchestrated by Service Fabric? We could do a skype session, you can find me as Gustavo_Armenta@Dell.com

**Comment by artisticcheese** [comment] 2018-10-26 19:02
Website perfomance might be a different issue from TCP scaling. You probably need to enable application insights or other profiler and find out which part of flow slows you down. It might not be network stack.  Make sure for example are using optimized .NET images (https://github.com/dotnet/announcements/issues/33)

**Comment by gustavo-armenta** [comment] 2018-10-26 19:15
[dotnet-framework-4.7.1-1709](https://github.com/Microsoft/dotnet-framework-docker/blob/master/4.7.1/runtime/windowsservercore-1709/Dockerfile)
[dotnet-framework-4.7.2-1803](https://github.com/Microsoft/dotnet-framework-docker/blob/master/4.7.2/runtime/windowsservercore-1803/Dockerfile)

I am using dotnet-framework-4.7.2-1803 which is not calling "ngen update". This might help!

**Comment by artisticcheese** [comment] 2018-10-26 19:18
That is strange, Microsoft either screwed up and did not put what it's supposed to put there or optimization is in by default in 1803 (like they promised in their post).

**Comment by JMesser81** [comment] 2018-10-31 00:32
@artisticcheese @gustavo-armenta  - we recently found some issues with MTU size causing some latency issues. Can you check the MTU size of your container endpoint interfaces and the physical (virtual if running in a VM) network adapter?

**Comment by gustavo-armenta** [comment] 2018-10-31 01:33
@harishsrini @JMesser81 @artisticcheese
it would be more useful to customers if Microsoft could provide an executable to run UDP/TCP performance tests to official Microsoft endpoints in every azure region, to "simple and easy to deploy"  services in same virtual network, and to user provided endpoints.

From container
```
C:\>netsh interface ipv4 show interfaces
Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
 18          75  4294967295  connected     Loopback Pseudo-Interface 2
 19        5000        1500  connected     vEthernet (Ethernet)
```

From VM
```
C:\>netsh interface ipv4 show interfaces
Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 10          10        1500  connected     Ethernet 3
  5        5000        1500  connected     vEthernet (nat)
```

**Comment by bboerst** [comment] 2018-11-16 14:51
My team has been closely following this issue over the past few months because we, too, are experiencing these NAT performance issues inside of our Win containers (Windows 2016.

My MTU configurations are:

From container:
```
PS C:\> netsh interface ipv4 show interfaces

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
 23          75  4294967295  connected     Loopback Pseudo-Interface 2
 24         500        1500  connected     vEthernet (Container NIC 03eef8f7)
```

From host AWS EC2 instance:
```
PS C:\> netsh interface ipv4 show interfaces

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
  2          15        1500  connected     vEthernet (HNS Internal NIC)
 15          15        1500  connected     Ethernet 3
 19          15        1500  connected     vEthernet (APIPA)
```

Any guidance on what these _should_ be? or do these look ok?

**Comment by artisticcheese** [comment] 2019-01-25 15:55
Guys at Microsoft. This is completely horrible. 
1. Recently released Windows 2018 still has port chunk size default to 10 which requires customers to manually increase for any sort of heavly SQL use. I don't even know how it can be set to 10 and at the same time connection pool for SQL to be set to 100. This shall be reevaluated. 
2. 1803 and 2019 dotnetframework images are both missing .NET optimization.
3. There is problems with latency as mentioned above which I do confirm on our application in talking/connecting to SQL server on 2019 box

What shall we do in the meantime? 
Host
```
PS C:\windows\system32> netsh interface ipv4 show interfaces

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 21        5000        1500  connected     vEthernet (nat)
  2          10        1450  connected     vEthernet (Ethernet 4)
```
Container
```
Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
 63          10        1450  connected     vEthernet (62e477be3cb7e97419541961d6ee4a17f0ac68e8cd38649741a5646b69eeb0c0)
 56          75  4294967295  connected     Loopback Pseudo-Interface 7
```

**Comment by gustavo-armenta** [comment] 2019-01-25 16:13
@artisticcheese 
I was able to get good connectivity doing these changes.
1.  The SqlCredential object is instantiated using a ConnectionString and a SqlCredential object. If you create a new SqlCredential object every time, then every SqlConnection goes to a new Pool opening new TCP connections all the time and not releasing connections fast. The solution is to cache the SqlCredential object
2. We use EntityFramework, make sure you are not calling ObjectContext.DatabaseExists() as it opens a separate connection to master database that is not closed correctly
3. Migrated to Windows Server 2019 and set PortChunkSize to max value of 2048

**Comment by artisticcheese** [comment] 2019-01-25 16:16
@gustavo-armenta So you latency in making calls to SQL were resolved by optimizing code? Why would not it affect your application when it was not inside container?

**Comment by gustavo-armenta** [comment] 2019-01-25 18:53
@artisticcheese 
the app outside containers is using Windows Authentication, inside containers is using SQL Authentication.

**Closed** 2019-01-25 22:02 UTC
Labels: area/networking, platform/windows, version/17.06

**Comment by artisticcheese** [comment] 2019-08-01 15:49
@JMesser81 I'm working with client currently which has consistent communication breakdown on TCP layer in Windows 2019. It manifests itself in consistent retranmissions and lack of ACK on receiving side. We already stopped using Application Gateway in Azure thinking issue was due to Application Gateway, moved to basic LB and issue still happens. PortChunkSize set to high value as well. Do we still need to invest time into trying to troubleshoot this issue or there are known issues in TCP stack on Windows 2019 which needs to be addressed?

**Comment by artisticcheese** [comment] 2019-08-01 17:59
Here is network capture showing that client retransmits packets continuous but never received inside container. Both client and server pcap is attached.
![image](https://user-images.githubusercontent.com/13176884/62315916-01b2d980-b45c-11e9-8756-f1bdcfc6c399.png)
https://1drv.ms/u/s!AqhhsryB84SOj_BcYqk7_MpEwrddSw?e=zYGhFW

**Comment by ryanjwh** [comment] 2019-08-13 00:12
Hi everyone, we're still fighting with this issue on WIndows 2019 running in Amazon ECS. Our containers open a ton of outbound connections to a variety of services and APIs we have in the normal course of answering API calls from clients. Because of this, our containers end up using a lot of outbound ephemeral source ports.

In 2016 1809 would could only set PortChunkSize to 1000 max, anything higher and the instance wouldn't boot. This cause our applications to suffer issues frequently due to WinNat running out of ports for the containers to use, so we had to cycle our containers and instances often.

In 2019 we were able to set PortChunkSize to 2000, and it made things a little better but didn't fix the problem completely. However, we've tried setting PortChunkSize to > 2000 and when we do that, it breaks something in Docker and containers won't start on the instances. We get errors during the container startup script adding a default route to the AWS metadata endpoint(s) saying the object already exists, and the container continuously crashes and restarts in a tight loop. Once we drop the instance's PortChunkSize back to 2000 and reboot, containers start just fine.

So, we're at a hard limit, which prevents us from giving our containers more ephemeral ports to use for outbound connections.

Thoughts?

**Comment by msabansal** [comment] 2019-08-13 01:19
Ping @daschott and @dineshgovindasamy  to see if they can help here

**Comment by daschott** [comment] 2019-09-04 04:47
Can you try to install https://support.microsoft.com/en-us/help/4512534 and see if it helps?

**Comment by daschott** [comment] 2019-09-04 05:02
@ryanjwh there is a few recent fixes for issues that may be relevant to the path you are hitting. One of them is above (HNS not reserving host ports correctly sometimes), and another is soon to come in 2-3 months. The other issue (not released a fix yet) can result in running out of ports when sending many outbound DNS requests in a short time interval. Will loop back here once that fix is available.

**Comment by thaJeztah** [comment] 2019-09-04 06:44
@ddebroy FYI ^^

**Comment by artisticcheese** [comment] 2019-09-04 13:17
August update mentioned above broke my swarm.

**Comment by ryanjwh** [comment] 2019-09-17 20:51
Hi @daschott thanks for the head's up, sorry just saw this. We'll investigate internally updating our ECS AMI to include this update and let you know.

**Comment by daschott** [comment] 2019-09-30 19:49
KB4516077 also contains another significant perf fix. Please try it out as well.

**Comment by daschott** [comment] 2019-10-01 20:00
The KB4516077 release note is not fully comprehensive of every issue that was resolved and does not mention this fix. I'll look at getting in touch with responsible team to include this fix in the RelNote. Either way reading back over this issue the fix may not be applicable to you after all. Even though it is very significant improvement it is *not* applicable to WinNAT, but every other container networking mode :( If you are looking for perf we still recommend you don't use WinNAT, but I understand the convenience and simplicity makes it hard to use different container networking modes which require much more work.

The other fix I mentioned in the comment [above](https://github.com/moby/moby/issues/34355#issuecomment-527740886) is still few months out. Current proposed release ETA is November.

**Comment by daschott** [comment] 2020-03-17 23:44
There is a cumulative update [KB4541331](https://support.microsoft.com/en-us/help/4541331/windows-10-update-kb4541331) which was just released for Windows Server 2019.

This KB relaxes the MAX_EXCLUSION_SIZE limit on port pool reservations and enables setting a value greater than 2048 for the PortChunkSize registry key without network connectivity loss to VMs/Containers using default switch (as well as any other tech leveraging WinNAT).

@artisticcheese FYI please let us know if this helps.
