### ISSUE TITLE
Since 17.12 docker CE - HEALTHCHECK no longer inherits WORKDIR (PWD==/) while in 17.09 HEALTHCHECK it was inherited from WORKDIR (PWD==WORKDIR).

### ISSUE THREAD

**Issue by artms** [moby/moby#35913] opened 2018-01-02 17:48 UTC
**Description**
Since 17.12 docker CE - HEALTHCHECK no longer inherits WORKDIR (PWD==/) while in 17.09 HEALTHCHECK it was inherited from WORKDIR (PWD==WORKDIR) in Dockerfile. Which might break containers which were expecting Healthcheck to execute commands while being in WORKDIR

1. Build simple docker image, simple Dockerfile:
```
FROM busybox
WORKDIR /root

HEALTHCHECK CMD env
```

```
docker build .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM busybox
 ---> 6ad733544a63
Step 2/3 : WORKDIR /root
 ---> Using cache
 ---> d2147f9d3cd8
Step 3/3 : HEALTHCHECK CMD env
 ---> Running in b465b176cf95
Removing intermediate container b465b176cf95
 ---> 12344e707666
Successfully built 12344e707666
```

2. Start docker container in 17.12:
```
docker run -ti --rm --name busy docker_build_id
~ # pwd
/root

```
3. Check for healthcheck output:
```
[
    {
        "Id": "af70cb836acbfad56e804e4b3d1210d0e97a25d145a7a19cd02eb5488a6e6323",
        "Created": "2018-01-02T15:42:26.283916609Z",
        "Path": "sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 25724,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-01-02T15:42:26.654086Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-01-02T17:42:56.654412529+02:00",
                        "End": "2018-01-02T17:42:56.700667346+02:00",
                        "ExitCode": 0,
                        "Output": "HOSTNAME=af70cb836acb\nSHLVL=1\nHOME=/root\nPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\nPWD=/\n"
                    },

```
4. PWD is "/" not WORKDIR which was "/root"

Same workflow executed on 17.09 yields:
```
[
    {
        "Id": "3fc05daafccb7884926756f68c04aef64944cdc0be2ad88fcbc18c30c94353f3",
        "Created": "2018-01-02T17:38:53.011840641Z",
        "Path": "sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 27262,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-01-02T17:38:53.314761685Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-01-02T19:39:23.315050864+02:00",
                        "End": "2018-01-02T19:39:23.355276833+02:00",
                        "ExitCode": 0,
                        "Output": "HOSTNAME=3fc05daafccb\nSHLVL=1\nHOME=/root\nPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\nPWD=/root\n"
                    }
                ]
            }
```

**Describe the results you received:**
WORKDIR is no longer set for healtchecks which might break assumptions which worked in previous versions. Release notes is not mentioning such breaking changes.

**Describe the results you expected:**
Release notes should mention breaking change or healthcheck should have same WORKDIR as exec

**Additional information you deem important (e.g. issue happens only occasionally):**
Probably caused by: https://github.com/moby/moby/issues/33753
**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
and
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```
**Output of `docker info`:**
N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical (affects AWS based machines also)

**Comment by thaJeztah** [comment] 2018-01-02 18:01
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/35843, which was a regression introduced by https://github.com/moby/moby/pull/35661, and already fixed in master through https://github.com/moby/moby/pull/35845

I'll close this one,  but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-01-02 18:01 UTC
Labels: area/builder, version/17.09
