### ISSUE TITLE
could not create session key: disk quota exceeded - Ubuntu 18.04

### ISSUE THREAD

**Issue by Kramerican** [moby/moby#38454] opened 2018-12-30 13:58 UTC
**Description**

I get this error trying to `docker run hello-world` inside an LXD container with docker configured to use vfs

Reposting here as per comment on original github issue: https://github.com/docker/for-linux/issues/519#issuecomment-450352270

**Steps to reproduce the issue:**
1. Follow instructions on how to install docker-ce
2. Then remove overlay dependency https://github.com/docker/for-linux/issues/475
3. Then configure to use vfs https://docs.docker.com/storage/storagedriver/vfs-driver/#how-the-vfs-storage-driver-works
4. When using docker-compose I had to tell it where the daemon lived: 
`export DOCKER_HOST=http+unix://var/run/docker.sock`

**Describe the results you received:**

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused "could not create session key: disk quota exceeded"": unknown.
> ERRO[0000] error waiting for container: context canceled

**Describe the results you expected:**

Hello World should just work, no?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 37
Server Version: 18.09.0
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 251.8GiB
Name: dockertest
ID: Z2D5:ZNAN:EY6V:56RR:EYCO:IMHZ:TWFP:KARO:TX7S:R5BA:RMBH:4A3K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

There's LOTS of free disk space on the server (120GB) - underlying storage is ZFS.

**Comment by SimonRichardson** [comment] 2019-06-11 15:24
I also ran into this and for other people also looking for a solution whilst searching, you need to up the `kernel.keys.maxkeys` and `kernel.keys.root_maxkeys` to a large number. By default it's `200`, but a realistic number should be `50000`.

**Comment by thaJeztah** [comment] 2019-06-11 17:29
Thanks yes, the check-config.sh script (which can be used for troubleshooting) also checks for this; https://github.com/moby/moby/blob/cf5d4aa1ad2e1e46dc222241f8a9fbbb9a54d17c/contrib/check-config.sh#L348-L361

looks like this is a duplicate of https://github.com/moby/moby/issues/22865, so let me close, but feel free to continue the conversation

**Closed by thaJeztah** 2019-06-11 17:29 UTC
