### ISSUE TITLE
Issues about /proc/meminfo  in docker using lxcfs，when lxcfs is restarted

### ISSUE THREAD

**Issue by jshachm** [moby/moby#33729] opened 2017-06-19 07:51 UTC
when use lxcfs to get correct /proc/meminfo in docker, I crash a problem. 
run command like 
docker run --rm -i -t  -m 200m -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo ubantu:mytag 

I got the correct memory info. However, when  the lxcfs restarts , I can`t get the meminfo unless  restart the container .Because I need to remount it into the docker! What I found it couldn't be done at all!

Anyone has ideas about  how to get  correct meminfo in docker without injectors and restarting the container? 
A lot of thank you !

**Comment by thaJeztah** [comment] 2017-07-25 23:41
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-07-25 23:41 UTC

**Comment by vazhnov** [comment] 2018-02-14 16:19
@jshachm, please try next time:

```bash
kill -s USR1 $(pidof lxcfs)
```
this is described in https://github.com/lxc/lxcfs/blob/master/README.md
