### ISSUE TITLE
Command 'docker login' does not work

### ISSUE THREAD

**Issue by Aragur** [moby/moby#41771] opened 2020-12-10 10:21 UTC
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

Docker crashes after command ```docker login```

**Steps to reproduce the issue:**
1. Run ```docker login```

**Describe the results you received:**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55a136904406]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x55a138346e00, 0xc00034a1a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55a1382b6201, 0xc00005af80, 0xc00041b968)
        /go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
github.com/docker/cli/cli/command/registry.runLogin(0x55a138346e00, 0xc00034a1a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc000244840, 0x55a1393515c8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000244840, 0xc000252f30, 0x0, 0x0, 0xc000244840, 0xc000252f30)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000573080, 0xc000252f30, 0x1, 0x1)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc00034a1a0, 0x55a1382b8f40, 0xc0000ce010)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3
```

**Describe the results you expected:**
I should be able to login :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:49 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:58 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-13-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 11.73GiB
 Name: v2202011133880133864
 ID: M3MB:RTMT:TGLN:CJSU:6PKI:XSGP:AADE:SNDO:I5LB:KQRQ:2FIL:6EOG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical root Server. (Fresh install)

**Comment by thaJeztah** [comment] 2020-12-10 15:28
Thanks for reporting! Looks like the panic happens here; https://github.com/docker/cli/blob/v20.10.0/cli/command/registry.go#L128

```go
	authconfig.Username = strings.TrimSpace(authconfig.Username)
```

So authconfig is nil at that point 🤔 


@Aragur just to get more information (I tried reproducing, but I didn't get a panic); did the panic happen directly after you ran `docker login`? (so you didn't type a username/password yet?) Are you using a credentials helper?

**Comment by Aragur** [comment] 2020-12-10 15:32
@thaJeztah 
Thanks for your answer.
I haven't entered anything.
The first time I ran this command I got this panic as well.

**Comment by thaJeztah** [comment] 2020-12-10 16:13
I tried installing docker 20.10 on Debian 10 ("buster") (this was a fresh install);

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:49 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:58 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@debian-s-1vcpu-2gb-ams3-01:~# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-cloud-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.951GiB
 Name: debian-s-1vcpu-2gb-ams3-01
 ID: YRXB:XMJJ:6V42:5WHX:2HV7:ZTZ6:BAG5:CYZQ:IXGV:X4P7:4LXM:C7MU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

🤔 Looking at differences in config; slightly different kernel version

@Aragur was this a fresh install or an upgrade? 

> I'm using the stock Debian installation, i don't know if this uses a credential helper.

The default package for debian (https://docs.docker.com/engine/install/debian/) don't include a credentials helper, but it's possible that one was installed if you installed (e.g.) debian's "docker-compose" package.

Did you install from the Docker packages from download.docker.com, or is this from debian distro's packages?


Also, could you check

- if there's a legacy `~/.dockercfg` file present? (or only a file in `~/.docker/config.json`)?
- could you post the content of your `~/.docker/config.json`? **IMPORTANT** ⚠️  remove the value for `"auth":` (if set) because if no credentials-helper is used, that containers your credentials

**Comment by Aragur** [comment] 2020-12-10 16:18
> @Aragur was this a fresh install or an upgrade?
Yes it was a completly fresh install using the latest debian.iso

> The default package for debian (https://docs.docker.com/engine/install/debian/) don't include a credentials helper, but it's possible that one was installed if you installed (e.g.) debian's "docker-compose" package.
Yes I have installed docker-compose via `apt install docker-compose`

> Did you install from the Docker packages from download.docker.com, or is this from debian distro's packages?
I used this guide https://docs.docker.com/engine/install/debian/ to install it via `apt install`

> if there's a legacy ~/.dockercfg file present? (or only a file in ~/.docker/config.json)?
`cat: /root/.dockercfg: No such file or directory`

> could you post the content of your ~/.docker/config.json?
`cat: /root/.docker/config.json: No such file or directory`

**Comment by thaJeztah** [comment] 2020-12-10 17:02
> Yes I have installed docker-compose via `apt install docker-compose`

Thanks; let me check what happens when doing so; I've seen various reports with the debian and ubuntu packages for docker-compose being either outdated, or causing issues (unfortunately we don't have `.deb` / `.rpm` packages for compose, but you can download the binaries; https://docs.docker.com/compose/install/)

> So there is no config.json is this a problem?

No, that's not a problem; if the file doesn't exist, it's created

> So this is a problem with the credential-manager shipping with docker-compose

Hmm.. yes, that's what I was afraid of 😞. So yes, I'd recommend installing our upstream compose packages using the instructions in that link I posted.

**Comment by philipkozeny** [comment] 2021-01-07 12:28
Had the same issue with `docker login` on Debian 10.7, docker from the official docker repo. Solved it by manually creating a file in `/root/.docker/config.json`. Neither the file nor the `.docker` folder existed before that.

**Comment by thaJeztah** [comment] 2021-01-07 13:27
I found the likely reason for the panic; fix is in https://github.com/docker/cli/pull/2918 (not merged yet)

**Comment by thaJeztah** [comment] 2021-01-08 12:57
This should be fixed by https://github.com/docker/cli/pull/2918 on master (and will be in an upcoming 20.10.x patch release)

**Closed by thaJeztah** 2021-01-08 12:57 UTC
Labels: area/cli, kind/bug, version/20.10

**Comment by antarr** [comment] 2021-01-27 00:21
I'm still running into this on Big Sur

**Comment by thaJeztah** [comment] 2021-01-27 11:43
Yes, the fix was merged after docker 20.10.2, so is not yet in a patch release.

**Comment by owl1n** [comment] 2021-01-31 17:16
`Docker version 20.10.2, build 2291f61` - still error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x558e18fc1d76]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x558e1ac02ce0, 0xc000302750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x558e1ab72101, 0xc000594ba0, 0xc000553968)
	/go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
github.com/docker/cli/cli/command/registry.runLogin(0x558e1ac02ce0, 0xc000302750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc00031e840, 0x558e1bc0d448, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00031e840, 0xc000255f50, 0x0, 0x0, 0xc00031e840, 0xc000255f50)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00024c2c0, 0xc000255f50, 0x1, 0x1)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc000302750, 0x558e1ab74de0, 0xc000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3
```

**Comment by thaJeztah** [comment] 2021-02-01 10:16
@owl1n see my comment above yours

> Yes, the fix was merged after docker 20.10.2, so is not yet in a patch release.

**Comment by matteoventuri7** [comment] 2021-02-07 23:09
Hi.
I'm running docker 20.10.3 on Debian 10 but docker login error occurred.
`root@debian:~# docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:38 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`
`root@debian:~# docker login registry.example.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5579263644d6]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x557927da7480, 0xc000536ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x557927d16800, 0xc0002773a0, 0xc00062f968)
        /go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
github.com/docker/cli/cli/command/registry.runLogin(0x557927da7480, 0xc000536ea0, 0x7fff99106e32, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc00015e840, 0xc0002767d0, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00015e840, 0xc000203610, 0x1, 0x1, 0xc00015e840, 0xc000203610)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000519b80, 0xc000203600, 0x2, 0x2)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc000536ea0, 0x557927d19540, 0xc000010028)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3
`

**Comment by moovs** [comment] 2021-02-08 15:06
Remove ` rm ~/.docker/config.json` file resolved issue!

**Comment by matteoventuri7** [comment] 2021-02-08 16:35
I have not that file. I have added that file with inside default code and now it works.

**Comment by webmozart** [comment] 2021-02-17 16:07
I'm still experiencing this on Ubuntu, Docker version 20.10.3, build 48d30b5.

**Comment by vvinjamu** [comment] 2021-02-17 19:36
I had a similar issue and docker login and docker logout showed the following errors:

**Problem:**
sudo docker login error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x563267da7f56]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x5632699e8c60, 0xc00056dad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x563269958001, 0xc000659140, 0xc0003a1968)
        /go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
github.com/docker/cli/cli/command/registry.runLogin(0x5632699e8c60, 0xc00056dad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc00064c840, 0x56326a9f3448, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00064c840, 0xc000658f30, 0x0, 0x0, 0xc00064c840, 0xc000658f30)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0002198c0, 0xc000658f30, 0x1, 0x1)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc00056dad0, 0x56326995ada0, 0xc000010020)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

**sudo docker logout error:**
Removing login credentials for https://index.docker.io/v1/
WARNING: could not erase credentials:
https://index.docker.io/v1/: error erasing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

**Solution:**
The following helped to solve my above issues.
sudo apt -V install gnupg2 pass

**Comment by owl1n** [comment] 2021-02-18 15:03
> @owl1n see my comment above yours
> 
> > Yes, the fix was merged after docker 20.10.2, so is not yet in a patch release.

I can see request was merged. But still error on login command. Maybe someone know workaround for this issue?

**Comment by webmozart** [comment] 2021-02-18 17:48
FYI I had this issue on 18.04 because I simultaneously had `docker-ce` from the Docker Apt repository and `docker-compose` (+ dependencies) from the Ubuntu Apt repository installed. Removing `docker-compose` and installing it through `curl` (as officially recommended) fixed the issue for me.

**Comment by alexander171294** [comment] 2021-02-25 13:33
> I had a similar issue and docker login and docker logout showed the following errors:
> **system config:**
> Ubuntu 18.04.5 LTS
> 
> **docker --version**
> Docker version 20.10.3, build 48d30b5
> 
> **Problem:**
> sudo docker login error:
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x563267da7f56]
> 
> goroutine 1 [running]:
> github.com/docker/cli/cli/command.ConfigureAuth(0x5632699e8c60, 0xc00056dad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x563269958001, 0xc000659140, 0xc0003a1968)
> /go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
> github.com/docker/cli/cli/command/registry.runLogin(0x5632699e8c60, 0xc00056dad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> /go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
> github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc00064c840, 0x56326a9f3448, 0x0, 0x0, 0x0, 0x0)
> /go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
> github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00064c840, 0xc000658f30, 0x0, 0x0, 0xc00064c840, 0xc000658f30)
> /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
> github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0002198c0, 0xc000658f30, 0x1, 0x1)
> /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
> github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
> /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
> main.runDocker(0xc00056dad0, 0x56326995ada0, 0xc000010020)
> /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
> main.main()
> /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3
> 
> **sudo docker logout error:**
> Removing login credentials for https://index.docker.io/v1/
> WARNING: could not erase credentials:
> https://index.docker.io/v1/: error erasing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
> 
> **Solution:**
> The following helped to solve my above issues.
> sudo apt -V install pass gnupg2
> 
> **final comments:**
> The above packages should be part of the docker dependencies package list.

this works for me: `sudo apt -V install pass gnupg2`

**Comment by pgchatela** [comment] 2021-02-26 09:18
I am still having the error on 20.10.3:

**system:** Ubuntu 18.04.5 LTS
**docker version:** Docker version 20.10.3, build 48d30b5

```
docker login ghcr.io
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55e372d62346]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x55e3749a32e0, 0xc000434a90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55e374912600, 0xc0005effe0, 0xc0005a7968)
        /go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
github.com/docker/cli/cli/command/registry.runLogin(0x55e3749a32e0, 0xc000434a90, 0x7ffcae88a91c, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc0005e18c0, 0xc0005ef420, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005e18c0, 0xc0000e7570, 0x1, 0x1, 0xc0005e18c0, 0xc0000e7570)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000121b80, 0xc0000e7560, 0x2, 0x2)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc000434a90, 0x55e3749153a0, 0xc0000f4010)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3
```

I already have pass and gnupg2 installed and up-to-date so the solution in https://github.com/moby/moby/issues/41771#issuecomment-780800641 does not work for me.

**Comment by TuemmlerKon** [comment] 2021-03-04 10:18
I had the same issue till now, I created the file /root/.docker/config.json with the following content:
`{
        "auths": {
                "https://index.docker.io/v1/": {},
        }
}`

**Comment by sven-mvolution** [comment] 2021-03-04 14:24
TuemmlerKon's [solution](https://github.com/moby/moby/issues/41771#issuecomment-790502878) works for me too.
**uname -a**: `Linux raspberrypi 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux`
**docker -v**: `Docker version 20.10.3, build 48d30b5`
