### ISSUE TITLE
Binaries no longer bering updated on https://master.dockerproject.org

### ISSUE THREAD

**Issue by andyfisher100** [moby/moby#45081] opened 2023-02-28 11:39 UTC
### Description

Microsoft specifies in their documentation, [for installing Docker CE/Moby on windows server 2022](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1), to use a powershell script that installs the latest version of docker from https://master.dockerproject.org

However it seems that the versions on this domain are no longer being updated. Is there a different URL?

### Reproduce

Run the powershell script to install Docker CE/Moby as mentioned in Microsoft documentation https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1

### Expected behavior

Binaries are kept up to date and the latest supported version is installed

### docker version

```bash
Client:
 Version:           master-dockerproject-2022-03-26
 API version:       1.42
 Go version:        go1.17.8
 Git commit:        dd7397342a
 Built:             Sun Mar 27 00:09:40 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          master-dockerproject-2022-03-26
  API version:      1.42 (minimum version 1.24)
  Go version:       go1.18
  Git commit:       8941dcfcc5
  Built:            Sun Mar 27 00:05:42 2022
  OS/Arch:          windows/amd64
  Experimental:     false
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: master-dockerproject-2022-03-26
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Microsoft Windows Server Version 21H2 (OS Build 20348.1547)
 OSType: windows
 Architecture: x86_64
 CPUs: 44
 Total Memory: 95.87GiB
 Name: EM-BLD-05
 ID: QCSH:6QXS:QPP2:ESOP:TTDU:TT6C:OOPW:3AXE:2L5K:5H5J:WUMO:TWB5
 Docker Root Dir: D:\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment] 2023-03-02 08:32
Thanks for reporting; this looks like a duplicate of https://github.com/moby/moby/issues/40378

> However it seems that the versions on this domain are no longer being updated. Is there a different URL?

Those binaries were always only intended for testing purposes (they were straight builds from master, and untested), so I definitely wouldn't recommend installing them for any other purpose. We were aware of Microsoft referencing that domain in parts of their documentation, and had conversations in the past with them to change that, but looks like that never fully completed. Looks like there's still a public discussion as well in this ticket;

- https://github.com/microsoft/Windows-Containers/issues/256

If you're looking for binaries; binary releases for Windows can be found on download.docker.com; https://download.docker.com/win/static/stable/x86_64/

Or for a commercially supported engine for Windows Server; https://www.mirantis.com/docker-engine-enterprise-support/


I'll close this ticket as it duplicates https://github.com/moby/moby/issues/40378, but feel free to continue the conversation

**Closed by thaJeztah** 2023-03-02 08:32 UTC
Labels: status/0-triage, kind/bug
