### ISSUE TITLE
Experimental: deploy vs stack deploy inconsistency

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#24799] opened 2016-07-19 15:33 UTC
It might be by design, but it feels a little inconsistent to have `docker deploy` and `docker stack deploy` (first one is an alias for the 2nd).

/cc @dnephin @icecrime @thaJeztah

**Comment by dnephin** [comment] 2016-07-19 15:56
How is it inconsistent?

**Comment by vdemeester** [comment] 2016-07-19 16:25
@dnephin inconsistent might not be the right term but it felt a little weird to have both.
What is the rationale to have `deploy` as a top level command (other than ease of use/shortcut which mihgt be a valid reason) ? Is it obvious that deploy is for stack files and not for services, plugins (*deploy this plugin accross the cluster*) or something else in the future ?

Most of the top-level commands are container, image and system (`events`, `info`, …) related and we tend to want to move them to subcommand (`docker image push …`). That's why I'm asking 👼 and we have time to think about it as it's in the experimental channel.

**Comment by dnephin** [comment] 2016-07-19 16:34
I think even with the move of things into `docker images`, and `docker container` we will probably still keep `docker run`, and `docker build`, so `deploy` could be the equivalent for stacks.

**Comment by thaJeztah** [comment] 2016-09-20 18:43
Was this fixed in the CLI refactor?

**Comment by dnephin** [comment] 2016-09-20 19:00
No, this is still by design.

**Comment by xeor** [comment] 2016-09-23 07:49
I just found this issue because I thought they was for different things.
Aliases are fine, but at least mark them clearly as "aliase for ..." in `--help`..

**Comment by thaJeztah** [comment] 2016-09-23 08:46
The aliases are mentioned in `docker stack deploy`, but not the other way round;

```

Usage:	docker stack deploy [OPTIONS] STACK

Create and update a stack from a Distributed Application Bundle (DAB)

Aliases:
  deploy, up

Options:
      --file string          Path to a Distributed Application Bundle file (Default: STACK.dab)
      --help                 Print usage
      --with-registry-auth   Send registry authentication details to Swarm agents
```

@dnephin does Cobra support that?

**Comment by dnephin** [comment] 2016-09-23 15:02
I think it might work if we just set them in `Aliases`, I'll try it out.

**Comment by dnephin** [comment] 2016-09-23 15:27
#26859

**Closed** 2017-04-22 13:04 UTC
Labels: area/bundles, kind/experimental, kind/question, priority/P3
