### ISSUE TITLE
docker plugin inspect <plugin> command returns incorrect Docker version information.

### ISSUE THREAD

**Issue by sumitshatwara** [moby/moby#35081] opened 2017-10-04 08:35 UTC
**Description**
`docker plugin inspect` command returns incorrect Docker version information.

**Steps to reproduce the issue:**
1. Install hpe docker volume plugin from store or install sshfs plugin.
```
docker plugin install store/hpestorage/hpedockervolumeplugin:2.0 --disable --alias hpe
```
2. Set the required parameters for plugin and enable the plugin.
```
docker plugin set hpe certs.source=tmp/
docker plugin enable hpe
```
3. Inspect the plugin.
```
docker plugin inspect hpe
```

**Describe the results you received:**
Incorrect Docker version "17.05.0-ce" was displayed as "DockerVersion" parameter.

```
$ docker plugin inspect hpe
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "HPE Docker Volume Plugin",
            "DockerVersion": "17.05.0-ce",
            "Documentation": "https://github.com/hpe-storage/python-hpedockerplugin/tree/master/quick-start",
.
.
.
```

**Describe the results you expected:**
DockerVersion was expected as "17.06.1-ee-2"

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue was observed for SSHFS volume plugin as well.

```
$ docker plugin inspect vieux/sshfs
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "sshFS plugin for Docker",
            "DockerVersion": "17.06.1-ce",
            "Documentation": "https://docs.docker.com/engine/extend/plugins/",
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.1-ee-2
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:15:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ee-2
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:14:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.06.1-ee-2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.8GiB
Name: csimbe13-b13
ID: FWY7:RCID:RQYW:ZBFH:2BX3:O2I4:RPMU:5SZL:KXCP:XZZX:IQF2:257S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.houston.hpecorp.net:8080/
Https Proxy: http://proxy.houston.hpecorp.net:8080/
No Proxy: 10.50.9.20,localhost,127.0.0.1,localaddress,.localdomain.com,.hpecorp.net,.hp.com,.hpcloud.net
Username: sumit7990
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Blade Server

**Comment by thaJeztah** [comment] 2017-10-04 09:46
This is the expected behaviour; the `DockerVersion` property shows the version of Docker that was used to build the plugin, not the version of Docker you're running the plugin on.

See the API reference for details about the information that is returned by `docker plugin inspect`; https://docs.docker.com/engine/api/v1.31/#operation/PluginInspect

<img width="976" alt="screen shot 2017-10-04 at 11 45 23" src="https://user-images.githubusercontent.com/1804568/31169629-8f6e84ec-a8f9-11e7-85c4-7104da386ad0.png">


I'm closing this issue, because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-04 09:46 UTC
Labels: area/plugins, version/17.06

**Comment by sumitshatwara** [comment] 2017-10-04 09:54
@thaJeztah ... Thanks for looking into this and for your information.

**Comment by thaJeztah** [comment] 2017-10-04 10:10
You're welcome!
