### ISSUE TITLE
Upgraded to 18.03.0-ce mounting in containers fails even with --cap-add=SYS_ADMIN

### ISSUE THREAD

**Issue by fadams** [moby/moby#36686] opened 2018-03-24 12:07 UTC
As the title says, when I upgraded to 18.03.0-ce the ability to call mount inside a container fails even with --cap-add=SYS_ADMIN

My system is Linux Mint 18.3 and the issue is definitely an interaction with apparmor.

If I do 
```
--security-opt apparmor=unconfined
```
it works fine, and similarly if I create a custom apparmor profile explicitly enabling mount (the default Docker one denies mount) then again it works fine.

So there is an easy workaround, but OTOH I'm pretty sure that before I upgraded my previous Docker 17.12 install worked without these tweaks so I think may have had something in the code around --cap-add=SYS_ADMIN that somehow overrode the apparmor deny mount???

So has something changed? Googling for this stuff suggests this issue crops up on and off fairly regularly, but I'm fairly sure I'm not imagining 17.12 not needing apparmor set to unconfined.

**Comment by thaJeztah** [comment] 2018-03-24 13:48
Could you show the exact steps to reproduce? Are you using `docker exec` to perform the mount? If so, that could be due to a bug in 17.12, where AppArmor profiles were not active on `exec`

**Comment by cpuguy83** [comment] 2018-03-24 14:09
Yeah, the apparmor profile has always blocked mounting.

**Comment by fadams** [comment] 2018-03-24 16:50
Hmm, I probably can't easily reproduce it quickly. I only really noticed it today, I've been trying something out and it was working OK on a Mint 18.3 VM I've been using elsewhere, but not on one I've just fired up at home.

As far as I'm aware apparmor is enabled by default on Mint 18.3, so the only difference I can think of between the two is that I upgraded my home system to docker 18.03.

The exec thing is interesting, I'm actually running systemd, so in my main docker run it's doing /sbin/init, but how I've noticed the weirdness is when I exec into the container.

That said, sure I exec in and run top and see that not everything I expect to see is running, but it's the main `docker run` that is actually running systemd not the exec, so it's the main docker run that would be doing any mounts.

I'll take a look at my other VM next week when I have access to it and see if apparmor is actually running on that box (though I can't think why it wouldn't be) and then I'll upgrade the docker version on that to see what happens, but as I say I'm pretty sure it's not my imagination that it was working on 17.12 but not on 18.03, though stranger things have happened.

**Comment by thaJeztah** [comment] 2018-03-24 18:48
Keep us posted; if we have a way to reproduce, that’ll be helpful to verify if there’s a bug at hand (or _fixed_, and the old behavior was wrong 😅)

**Comment by fadams** [comment] 2018-03-28 14:55
Hi,
An update. So I got back to the other machine I've been working with and it turns out that one was actually Linux Mint 18.1 not 18.3 and it looks like apparmor wasn't enabled by default on 18.1.

My bad, I've mostly been using 18.3 with apparmor and missed that one, sorry!

Too many variables being juggled, I'm clearly getting too old for that :o)

**Comment by ripcurld** [comment] 2018-03-28 15:02
@fadams thank you for that. I'm closing this ticket since it's not a bug or an issue with Moby but feel free to continue the conversation.

**Closed by ripcurld** 2018-03-28 15:02 UTC
