### ISSUE TITLE
`docker cp` for copying image files to file system (not running container)

### ISSUE THREAD

**Issue by alias1** [moby/moby#34592] opened 2017-08-22 04:42 UTC
It would be great if we could copy a file from an image to the local filesystem in the same way that we can copy to/from a running container.

Eg.
```
docker cp SOMECONTAINERREFERENCE:/foo/bar /local/foo/bat
```

I'm not sure what the best syntax would be for referencing the container (since it would need to handle `/`'s, which might be confused with filesystem) Perhaps even just a `--fromContainer` type flag would be sufficient?

I know that it can currently by done by making a temporary container, but that doesn't work well for super-minimal images (eg. `FROM scratch`)

```
# From: https://forums.docker.com/t/is-there-a-way-to-copy-a-file-from-an-image-to-the-local-filesystem-without-running-a-container/2841

docker run --name temp-container-name image-name /bin/true
docker cp temp-container-name:/path/to/manifest /local/path/to/manifest
docker rm temp-container-name
```

Currently it can be worked around by doing something like this, though it's obviously less than ideal:
```
TEMPCONT="fooTemp$(date +%s)"
docker run --name $TEMPCONT devalias/gobuster
docker export $TEMPCONT | tar -xvzf - gobuster
docker rm $TEMPCONT
```

**Comment by thaJeztah** [comment] 2017-09-20 22:43
This is a duplicate of https://github.com/moby/moby/issues/16079 (which may contain some useful information).

> I know that it can currently by done by making a temporary container, but that doesn't work well for super-minimal images (eg. `FROM scratch`)

Copying from any image should work; there's no need to _start_ the container, just _creating_ a container is sufficient. For example:


```bash
# use the container's ID so that we don't have to come up with a name for it
CID=$(docker create <image-name>)
docker cp ${CID}:/path/to/manifest /local/path/to/manifest
docker rm ${CID}
```

I'm closing this one because it's a duplicate, but feel free to comment if you need more information

**Closed by thaJeztah** 2017-09-20 22:43 UTC
