### ISSUE TITLE
search path for pulling images

### ISSUE THREAD

**Issue by Haritha113** [moby/moby#38970] opened 2019-03-29 04:29 UTC
I am using Ubuntu 16.04.4 LTS ,Docker version 18.09.2.
I have one local registry in host,i pushed images to that registry. I am pulling images from local registry in other machine.
This is working fine.
	 sudo docker pull docker:5000/sampleimage

But, if i try to pull image (in other machine) which is not in my local registry, i am facing Error Response.
	sudo docker pull docker:5000/alpine

Here, alpine image is not existing in my local registry. Is it possible to check pull image functionality in the following three phases 
	
	1. in the machine where you are pulling images
	2. in local registry (if image not found in machine)
	3. in Docker hub (if image not found in local registry)

**The scenario will be like this Does docker support a configuration to search a sequence of registries to pull image similar to "apt install" command of ubuntu which will look out for source urls in /etc/apt/sources.list**
 
Is there any way to do configuration for this scenario ?

**Comment by thaJeztah** [comment] 2019-04-01 20:31
You're likely looking for something like this; https://docs.docker.com/registry/recipes/mirror/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-04-01 20:31 UTC
Labels: area/distribution, version/18.09
