### ISSUE TITLE
 docker can't get a tty or pty

### ISSUE THREAD

**Issue by sandyskies** [moby/moby#33818] opened 2017-06-25 08:23 UTC
-->

**Description**

**Steps to reproduce the issue:**
1,

```
docker run -ti aaedd3e26833 bash 

```
2,  
[root@350580241b8e /]# tty
/10
```
 
**Describe the results you received:**
```
/10
```
**Describe the results you expected:**
```
tty return a tty or pty like /dev/pty/*
```

**Additional information you deem important (e.g. issue happens only occasionally):**
always
**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: xfs
 Dirs: 163
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.10.104.xxxxxx
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.3 GiB
Name: xxxxxxxxxxxxxxxxx
ID: VTSE:3AJP:MWYG:XSRO:VLHA:7RUN:S5KP:SDB4:HVDP:5HT3:24XC:VW52
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centos 6 with 3.10.x kernel version.

**Comment by unclejack** [comment] 2017-07-03 10:47
There are a few issues with this setup. CentOS 6 isn't supported for containers. The original libraries and kernel weren't particularly adequate to run containers. The newer kernel you're running on that distribution is also not officially supported by the CentOS project on CentOS 6.

The version of Docker you're using is very old. If you have a very good reason to stick to Docker 1.12.x, you might want to upgrade to CentOS 7.

Please keep in mind Docker CE 17.03.1 and 17.06 exist now. You might want to try to reproduce the issue with those on CentOS 7. I couldn't reproduce the issue here. I'm getting a pts as expected.

I'll close this issue now because:
1. CentOS 6 is unsupported for running containers by the CentOS community - each user is on their own
2. CentOS 6 with kernel 3.10 or any other kernel is unsupported by the CentOS project/community - it can be installed, but it's unofficial
3. Docker 1.12.2 is really old, unsupported and many other versions have been released since

Please feel free to continue the discussion.

**Closed by unclejack** 2017-07-03 10:47 UTC
Labels: version/1.12
