### ISSUE TITLE
How to create seprate volume for each docker swarm container

### ISSUE THREAD

**Issue by RashidAli48** [moby/moby#41006] opened 2020-05-21 08:51 UTC
I need to create separate logs for each running container in the docker swarm cluster. Currently all container writing logs in same volume.

**Comment by thaJeztah** [comment] 2020-05-26 14:56
you could use a template for the volume name (see https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates), for example;


```bash
docker service create --name foo --mount "type=volume,src={{.Service.Name}}.{{.Task.Slot}},target=/foo" nginx:alpine
```

However, for logging, the recommended approach is to have containers log to stdout/stderr, which will be captured by docker and sent to the logging driver you're using (which could be syslog, or sending logs to a remote logging aggregator); https://docs.docker.com/config/containers/logging/configure/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-26 14:56 UTC
Labels: area/swarm, kind/question
