### ISSUE TITLE
1.13rc3 static ip addresses

### ISSUE THREAD

**Issue by yellowmegaman** [moby/moby#29176] opened 2016-12-06 13:29 UTC
**Description**

Some services i use, require static ip addresses, but instead of manualy adding them, i'd like to have an option below.

**Steps to reproduce the issue:**
1. docker service create --name=someservice nginx:latest
2. restart all/some nodes

**Describe the results you received:**
all containers got new ip

**Describe the results you expected:**
some option ( if not out of the box) for setting docker-dhcp lease per container id.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-202:1-263647-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 631.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 8.215 GB
 Metadata Space Used: 1.835 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 1b5xsu6ys0k6yjyszu3qtp04u
 Is Manager: true
 ClusterID: 9k72vaabjxl175012or013hn4
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.50.222
 Manager Addresses:
  172.31.50.222:2377
  172.31.54.237:2377
  172.31.60.184:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.674 GiB
Name: ip-172-31-50-222
ID: U2WW:7VP2:KGSJ:46MX:XKHY:JIOU:3ZSR:6T4A:OCE4:MV7U:O26B:6WG7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Baremetal/AWS.

Thanks a lot in advance! Really hoping there's some way of achieving this already, that i did not find.

**Comment by jmzwcn** [comment] 2016-12-11 10:34
As linux dhcp, write "dhcp lease" into a temp file?

**Comment by galindro** [comment] 2017-01-20 13:54
Guys,
   There is an ETA for this?

**Comment by ventz** [comment] 2017-01-20 14:53
I have another ticket about the same thing:

https://github.com/docker/docker/issues/29816

**Comment by thaJeztah** [comment] 2023-09-17 18:48
- closing as duplicate of https://github.com/moby/moby/issues/24170

**Closed by thaJeztah** 2023-09-17 18:48 UTC
Labels: kind/enhancement, area/networking, area/swarm, version/1.13
