### ISSUE TITLE
docker checkpoint restore error

### ISSUE THREAD

**Issue by wekay102200** [moby/moby#38946] opened 2019-03-27 06:04 UTC
**Description**
when i restore docker checkpoint.it occur error below.
docker version is:17.06.0-ce
criu version is:3.6

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1066-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.94GiB
Name: ip-172-31-15-124
ID: 4KSW:L5MH:PPVE:OT24:PVBQ:NI3K:YF6Q:PUHL:OFSQ:I55Y:KKKJ:WFAO
Docker Root Dir: /mnt/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

```
(00.142525)      1: mnt: Start with 0:/tmp/.criu.mntns.SDt9Je
(00.142533)      1: mnt:        Mounting overlay @/tmp/.criu.mntns.SDt9Je/12-0000000000/ (0)
(00.142612)      1: mnt: 170:/tmp/.criu.mntns.SDt9Je/12-0000000000/ private 1 shared 0 slave 0
(00.142692)      1: mnt:        Mounting proc @/tmp/.criu.mntns.SDt9Je/12-0000000000/proc (0)
(00.142756)      1: Error (criu/mount.c:1818): mnt: Can't mount at /tmp/.criu.mntns.SDt9Je/12-0000000000/proc: No such file or directory
(00.142764)      1: mnt: Start with 0:/tmp/.criu.mntns.SDt9Je
(00.209618) Error (criu/mount.c:2980): mnt: Can't remove the directory /tmp/.criu.mntns.SDt9Je: No such file or directory
(00.209636) Error (criu/cr-restore.c:2171): Restoring FAILED.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2019-03-27 11:47
Note that Docker CE 17.06 reached EOL in september 2017, and is no longer maintained; are you still able to reproduce this on a current version of Docker?

I'll close this ticket because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2019-03-27 11:47 UTC

**Comment by wekay102200** [comment] 2019-03-28 09:53
@thaJeztah i have try the lastes docker version.but it doesn't support the checkpoint function.
so i have to use old docker version to use the checkpoint function.

**Comment by wekay102200** [comment] 2019-03-28 09:53
@thaJeztah i have try the lastest docker version.but it doesn't support the checkpoint function.
so i have to use old docker version to use the checkpoint function.

**Comment by thaJeztah** [comment] 2019-03-28 10:07
```
docker --version 
Docker version 18.09.3, build 774a1f4


docker checkpoint --help 
Usage:	docker checkpoint COMMAND

Manage checkpoints

Commands:
  create      Create a checkpoint from a running container
  ls          List checkpoints for a container
  rm          Remove a checkpoint

Run 'docker checkpoint COMMAND --help' for more information on a command.
```

**Comment by wekay102200** [comment] 2019-04-17 08:40
@thaJeztah 
i have use docker 18.09.5 to create docker checkpoint.but it occur error below.
Error response from daemon: Cannot checkpoint container fe48b9133fd7: write /var/lib/containerd/io.containerd.content.v1.content/ingest/69aa461676dbcb46501724ef996ac694a401867558bac7532f21dbc9d63add8b/data: no space left on device: unknown

my disk space is enough.
ubuntu@ip-172-31-12-253:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             15G     0   15G   0% /dev
tmpfs           3.0G  8.6M  3.0G   1% /run
/dev/xvda1       49G   32G   18G  65% /
tmpfs            15G     0   15G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            15G     0   15G   0% /sys/fs/cgroup
tmpfs           3.0G     0  3.0G   0% /run/user/1000
