### ISSUE TITLE
Docker on Windows -> seems like I can't connect to docker online repository

### ISSUE THREAD

**Issue by jakubsuchybio** [moby/moby#22567] opened 2016-05-07 05:49 UTC
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
PS C:\WINDOWS\system32> docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Fri Apr 29 14:13:26 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
PS C:\WINDOWS\system32> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.6-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: docker
ID: *CENZORED (precaution)*
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- I am Beta user of Docker on Windows (using Hyper-V)

**Steps to reproduce the issue:**
1. Install docker via https://beta.docker.com/docs/ for Windows with Hyper-V functionality enabled
2. Type in powershell with Administration privilegies `docker run hello-world`

**Describe the results you received:**

```
PS C:\WINDOWS\system32> docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 10.0.75.1:53: no such host.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

**Describe the results you expected:**
I don't know what to expect. I guess search and install of docker container called hello-world :) for first time use and testing the docker platform.

**Additional information you deem important (e.g. issue happens only occasionally):**
- I tried adding to hosts file IP that I get from `ping registry-1.docker.io` 
  with address `cdn-registry-1.docker.io` which was suggested in #3203, but it didn't help.
- My Hyper-V runs fine with some Windows 10 VMs running.
  ![image](https://cloud.githubusercontent.com/assets/6567287/15088891/eb387f08-13f9-11e6-98e8-65ec1d4a8def.png)

**Comment by thaJeztah** [comment] 2016-05-07 09:51
thanks for reporting, let me forward this to the Docker for Windows team

**Comment by rneugeba** [comment] 2016-05-07 16:09
Hi @jakubsuchybio,

thanks for reporting the issue. Could you provide a bit more information? Firstly, the logs would be very useful. You can access them via the whale icon in the systray (right-click and then logs). Seocnd, there seems to be an issue with the networking setup. Could you also provide the output from the following command, executed in an elevated powershell (ie ran as administrator):
- `Get-NetIpAddress`
- `Get-NetNat`
- `Get-VMNetworkAdapter MobyLinuxVM`

Thanks

**Comment by jakubsuchybio** [comment] 2016-05-07 17:24
Hmm, going through the log and looking, that it tries to resolve DNS on my home Windows Server, I tried to change DNS to google DNS 8.8.8.8 and it seems to be working.
```docker run hello-world``` gives me:
```
PS C:\WINDOWS\system32> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world

4276590986f6: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:4f32210e234b4ad5cac92efacc0a3d602b02476c754f13d517e1ada048e5a8ba
Status: Downloaded newer image for hello-world:latest

Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

However I would like to know how to configure my DNS server on my Windows Server to get it running with it. So here is the information:

After removing hello-world image and cleaning old log I ran ```docker run hello-world``` and it gives this log:
http://pastebin.com/E5u2ASgp

**Here are the commands:**
- ```Get-NetIPAddress```:
```
PS C:\WINDOWS\system32> Get-NetIPAddress


IPAddress         : fe80::7460:b076:485f:1167%41
InterfaceIndex    : 41
InterfaceAlias    : vEthernet (DockerNAT)
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::cd55:f5e8:4fc:671c%14
InterfaceIndex    : 14
InterfaceAlias    : vEthernet (Internal Ethernet Port Windows Phone Emulator Internal Switch)
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::556a:c489:5978:4d4e%4
InterfaceIndex    : 4
InterfaceAlias    : vEthernet (BIO-SWITCH)
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::e97a:910d:1039:a12a%15
InterfaceIndex    : 15
InterfaceAlias    : VMware Network Adapter VMnet8
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::e0d7:a7bf:2b7e:c6c2%26
InterfaceIndex    : 26
InterfaceAlias    : VMware Network Adapter VMnet1
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:10.0.75.1%45
InterfaceIndex    : 45
InterfaceAlias    : isatap.{7A798902-5AB3-4BA4-A544-8D49BB328B59}
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:192.168.253.1%22
InterfaceIndex    : 22
InterfaceAlias    : isatap.{5FA41BD9-F998-4EFF-B6D5-F4CB8E2CB589}
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:192.168.40.1%20
InterfaceIndex    : 20
InterfaceAlias    : isatap.{FC33B884-7AB7-41C2-BE06-79BF76E0D05B}
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::7d74:a6b9:c38e:334a%27
InterfaceIndex    : 27
InterfaceAlias    : Ethernet 2
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:169.254.80.80%18
InterfaceIndex    : 18
InterfaceAlias    : isatap.{534E3E60-AA15-4FB4-9170-14AF53A12CEB}
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : ::1
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : WellKnown
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:192.168.88.13%23
InterfaceIndex    : 23
InterfaceAlias    : isatap.*CENZORED* (My public IP address)
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 10.0.75.1
InterfaceIndex    : 41
InterfaceAlias    : vEthernet (DockerNAT)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 169.254.80.80
InterfaceIndex    : 14
InterfaceAlias    : vEthernet (Internal Ethernet Port Windows Phone Emulator Internal Switch)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 16
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 192.168.88.13
InterfaceIndex    : 4
InterfaceAlias    : vEthernet (BIO-SWITCH)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Dhcp
SuffixOrigin      : Dhcp
AddressState      : Preferred
ValidLifetime     : 7.23:54:23
PreferredLifetime : 7.23:54:23
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 192.168.253.1
InterfaceIndex    : 15
InterfaceAlias    : VMware Network Adapter VMnet8
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Dhcp
SuffixOrigin      : Dhcp
AddressState      : Preferred
ValidLifetime     : 00:23:51
PreferredLifetime : 00:23:51
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 192.168.40.1
InterfaceIndex    : 26
InterfaceAlias    : VMware Network Adapter VMnet1
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Dhcp
SuffixOrigin      : Dhcp
AddressState      : Preferred
ValidLifetime     : 00:23:59
PreferredLifetime : 00:23:59
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 169.254.51.74
InterfaceIndex    : 27
InterfaceAlias    : Ethernet 2
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 16
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Tentative
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 127.0.0.1
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 8
PrefixOrigin      : WellKnown
SuffixOrigin      : WellKnown
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore
```

- ```Get-NetNat```:
```
PS C:\WINDOWS\system32> get-netnat


Name                             : DockerNAT
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 10.0.75.0/24
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True
```

- ```Get-VMNetworkAdapter MobyLinuxVM```:
```
PS C:\WINDOWS\system32> Get-VMNetworkAdapter MobyLinuxVM

Name            IsManagementOs VMName      SwitchName MacAddress   Status                      IPAddresses
----            -------------- ------      ---------- ----------   ------                      -----------
Network Adapter False          MobyLinuxVM DockerNAT  00155D580D03 {Degraded, ProtocolVersion} {10.0.75.2}
```

**Comment by elboletaire** [comment] 2016-07-27 14:17
I've just installed the docker for windows beta (using HyperV) and got the same issue. I'm not using custom DNS, instead I use the default given by my router.

Changing them in docker options to 'fixed', and using the default one provided (google's 8.8.8.8), allowed me to start using docker.

**Comment by georanma** [comment] 2016-07-30 20:46
I had a similar issue with the new stable release. Once I updated my subnet address, this was no longer an issue. This is not really mentioned in the documentation for set up.

**Comment by thaJeztah** [comment] 2016-07-30 21:37
ping @londoncalling ^^

**Comment by summerfang** [comment] 2016-09-04 16:55
I am user to install the stable version of docker for windows in Win10. I met different issue but similar since the effort message are: 
PS C:\Users\xxxxxx> docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Network timed out while trying to connect to https://index.dock
er.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a
proxy..
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

I tried to set the DNS to 8.8.8.8, it doesn't work and response the same issue.

**Comment by Ming0668866** [comment] 2016-09-10 16:58
I got the same issue on windows10, after uninstalled Docker for Windows and delete Hyper-V virtual Ethernet Adapter  on Device Manager panel, reinstall Docker for Windows. the issue dispeared.
Hope this is helpful for someone.

**Comment by iaracy** [comment] 2016-09-13 19:12
I had the same problem (unable to connect to the network, and download anything) with V 1.12 stable- 
-->i.e.  I was unable to run "docker run hello-world"  successfully.
Once I installed V 1.12.1-beta25 "docker run hello-world"  run successfully.

Hope this helps

**Comment by friism** [comment] 2016-09-14 21:48
@summerfang we've improved the networking in the latest betas, could you try installing beta26? https://docs.docker.com/docker-for-windows/

**Comment by brogan89** [comment] 2016-09-15 03:41
Thank you @friism it was racking my brain this issue. Funny how the beta works but the stable doesn't.

**Comment by iaracy** [comment] 2016-09-15 05:56
Initial result is that beta26 seems also to overcome the issue.

**Comment by aalexgabi** [comment] 2016-09-24 09:14
Similar issue:
```
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\Users\user> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.942 GiB
Name: moby
ID: IUPP:YX2Z:XTHD:B7DR:BBU2:JLDI:W2VY:EGY5:XU2X:TNLC:G4XV:ZEGD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2016-09-24T07:06:34.6090611Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
PS C:\Users\user> docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 192.168.65.9:53: server misbehaving.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\Users\user> docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 192.168.65.9:53: server misbehaving.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\Users\user> Get-NetIpAddress


IPAddress         : fe80::3c1a:32d7:43a:d560%31
InterfaceIndex    : 31
InterfaceAlias    : Local Area Connection* 4
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::7541:c15b:aba:455e%22
InterfaceIndex    : 22
InterfaceAlias    : vEthernet (DockerNAT)
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:10.0.75.1%7
InterfaceIndex    : 7
InterfaceAlias    : isatap.{B01B92D1-377A-4B14-9667-BFD5E6FB5722}
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:10.1.3.135%3
InterfaceIndex    : 3
InterfaceAlias    : isatap.{3C64A074-B530-46E8-82B1-84CF3C66E40E}
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::c528:6f2e:e3bf:ea53%4
InterfaceIndex    : 4
InterfaceAlias    : VirtualBox Host-Only Network
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::ffff:ffff:fffe%9
InterfaceIndex    : 9
InterfaceAlias    : Teredo Tunneling Pseudo-Interface
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::5efe:192.168.0.31%5
InterfaceIndex    : 5
InterfaceAlias    : isatap.netgear.com
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Deprecated
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : fe80::f96f:96d:bd4d:f20c%11
InterfaceIndex    : 11
InterfaceAlias    : Ethernet
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : ::1
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 128
PrefixOrigin      : WellKnown
SuffixOrigin      : WellKnown
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 10.1.3.135
InterfaceIndex    : 31
InterfaceAlias    : Local Area Connection* 4
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 32
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 10.0.75.1
InterfaceIndex    : 22
InterfaceAlias    : vEthernet (DockerNAT)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 192.168.56.1
InterfaceIndex    : 4
InterfaceAlias    : VirtualBox Host-Only Network
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 192.168.0.31
InterfaceIndex    : 11
InterfaceAlias    : Ethernet
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Dhcp
SuffixOrigin      : Dhcp
AddressState      : Preferred
ValidLifetime     : 22:39:19
PreferredLifetime : 22:39:19
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 127.0.0.1
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 8
PrefixOrigin      : WellKnown
SuffixOrigin      : WellKnown
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore
PS C:\Users\user> Get-NetNat
PS C:\Users\user> Get-VMNetworkAdapter MobyLinuxVM
Get-VMNetworkAdapter : Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
At line:1 char:1
+ Get-VMNetworkAdapter MobyLinuxVM
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VMNetworkAdapter], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMNetworkAdapter

PS C:\Users\user>
```

**Comment by GhostRussia** [comment] 2016-09-27 18:59
On macOS the same problem.

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: ABCZ:RN4P:ZLY7:4M6Q:46AQ:CZWM:RZFD:2RNI:5SBY:Z4CD:NNMJ:FE4U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-09-27T18:51:44.885295382Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
```
<img width="907" alt="2016-09-28 03 58 03" src="https://cloud.githubusercontent.com/assets/12181586/18887620/cb6851ec-852f-11e6-9734-9028ae5fd440.png">

**Comment by MitchDresdner** [comment] 2016-12-22 14:22
Having same network problems, Windows 10 professional:

Pulling from repositories worked on Tuesday with initial install, stopped working on Wed (too much eggnog??).  Cleared out all containers and images to start over but am unable to pull for repository or run docker login.

docker run -it ubuntu bash

Unable to find image 'ubuntu:latest' locally
Pulling repository docker.io/library/ubuntu
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error while pulling image: Get https://index.docker.io/v1/repos
itories/library/ubuntu/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:54934->[::1]:53: read: connection refused.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
ping us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com

Pinging us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com [54.85.12.131] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

--
docker login

Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: MitchD
Password:
Error response from daemon: Get https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:46422->[::1]:53: read: connection refused


-- Additional info

nslookup index.docker.io

Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com
Addresses:  52.73.159.23
          52.207.178.113
          54.85.12.131
Aliases:  index.docker.io
          elb-io.us-east-1.aws.dckr.io

--

docker version

Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

--
docker info

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.919 GiB
Name: moby
ID: RQ3A:HLU2:SV7F:KKMC:7PZ3:F4L5:G5HC:RUXU:ID3L:SIRL:35P4:23ZI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2016-12-21T23:21:19.840021Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8

**Comment by MitchDresdner** [comment] 2016-12-22 16:00
Found the right place to change DNS settings, in the Docker app windows tray icon.

All is working again.

**Comment by silkentrance** [comment] 2017-10-25 14:46
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon

**Comment by thaJeztah** [comment] 2017-10-25 15:00
Yes, this looks to be a configuration issue, not a bug, and a troubleshooting section for people running D4W has been added in https://github.com/docker/pinata/pull/4666.

I'll close this issue because of the above

**Closed by thaJeztah** 2017-10-25 15:00 UTC
Labels: kind/bug, platform/desktop, version/1.11
