### ISSUE TITLE
docker stack deploy startup order/dependencies

### ISSUE THREAD

**Issue by DrPyser** [moby/moby#40364] opened 2020-01-10 21:07 UTC
**Description**

It seems there is no support for managing dependencies between services in a stack when using `docker stack deploy`, as there is in docker-compose(using `depends_on`).
The [compose file reference](https://docs.docker.com/compose/compose-file/#depends_on) says 
> The depends_on option is ignored when deploying a stack in swarm mode with a version 3 Compose file.

However, there is no warning when using `docker stack deploy` with a compose file using `depends_on`.

it seems to me this feature is pretty important for a declarative approach to service deployment and orchestration. It is a pretty common requirement that some services should only be started after others(and only if those dependencies are successfully deployed).
It is also non-trivial for application developers to handle this on top of swarm. The only way I can see is using something like [`wait-for-it`](https://github.com/vishnubob/wait-for-it) scripts for all services in the dependency graph, which would require implementing custom images for each service, which can add operational complexity(we would need to maintain more custom images, and keep them up to day with the base images). 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by cpuguy83** [comment] 2020-01-11 05:33
What do you do with your service when for whatever reason you can't connect to a dependency while the service is running?

**Comment by DrPyser** [comment] 2020-01-11 06:24
Retry? So yes, retrying until it works might get the job done.
Downsides,
* we now have to consider failure as normal and expected, instead of rare and unexpected, and make sure the retry policy is configured appropriately for both the expected failures on startup, and anormal failures. For example, (delay, max attemps) must match the startup behavior of dependencies("oh, so after running multiple tests, it might take up to 10 seconds for that database service to be up? I need to make sure this web service will try long enough to handle the worst case, but still start quickly enough in the best case").
* initial deployments generate scary, messy status reports, hard to differentiate between normal startup behavior and actual problems. 
* lots of work being done blindly doing things that are doomed to fail. resources being wasted scheduling, creating and starting containers that will just fail and eventually be removed. Could be problematic in systems under heavy load
* Repeated startup failures of some services might have undesirable side-effects that need to be dealt with, such as superfluous error log output or error events being sent

Individually, they might be minor annoyances, but I think they combine to result in a less than ideal devops experience.

I think that accomplishing goals cleanly and efficiently, with a minimal resource footprint, and capturing adequately the intent of the user, should be design goals for any software systems. Not to say that there aren't tradeoffs to consider, of course.

**Comment by thaJeztah** [comment] 2020-01-13 13:41
This looks like a duplicate of https://github.com/moby/moby/issues/31333, which already has quite some comments, so let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2020-01-13 13:41 UTC
Labels: area/stack
