### ISSUE TITLE
Adding hosts for windows containers (--add-host, extra_hosts) does not work

### ISSUE THREAD

**Issue by hamid-riahi** [moby/moby#36227] opened 2018-02-07 04:38 UTC
**Expected behavior**

Either docker run --add-host argument or docker compose extra_hosts option should add host entry to etc/host for windows containers.

**Actual behavior**

Neither docker run --add-host argument nor docker compose extra_hosts option does add host entry to etc/host for windows containers.

**Steps to reproduce the behavior**

**Not working example for windows container**

Run docker run -it --add-host me:127.0.0.1 microsoft/nanoserver
Run ping me

**Additional working example for linux container**

Run docker run -it --add-host me:127.0.0.1 ubuntu
Run apt-get update
Run apt-get install iputils-ping
Run ping me

**Comment by thaJeztah** [comment] 2018-02-07 04:53
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`

**Comment by hamid-riahi** [comment] 2018-02-07 05:08
Oh Sorry:

**docker version:**

Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

**docker info:**

Containers: 14
 Running: 13
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1770.amd64fre.rs1_release.170917-1700)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: EC2AMAZ-JSG13TE
ID: VZIV:QABT:63VB:KUOW:4FOR:BTTB:QULZ:U7KS:CIZK:QWTU:63SI:65EG
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment] 2018-02-07 05:54
That looks like a really old version of Docker 1.12 (cs - commercially supported); are you still reproducing this on a current version?

Be aware that primary support for Docker CS, and Docker EE (Enterprise Edition) on Windows is handled by Microsoft support, so if you’re still able to reproduce this on a current version, it may be worth opening a ticket there (as they’re able to escalate issues if needed)

**Comment by thaJeztah** [comment] 2018-02-07 19:18
Let me close this issue here, because the Docker Enterprise Edition and CS (Commercially Supported) packages are not maintained in this repository, but feel free to continue the conversation

**Closed by thaJeztah** 2018-02-07 19:18 UTC
Labels: platform/windows, status/more-info-needed
