### ISSUE TITLE
Deploy service on specific node/nodes

### ISSUE THREAD

**Issue by Pierpaolo1992** [moby/moby#33714] opened 2017-06-16 12:48 UTC
I have created 3 VM using docker-machine. These VM , named MANAGER, WORKER1 and WORKER2, runs docker engine version;

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
I want to deploy a service on only, for example, MANAGER and WORKER1 nodes.
I've initialized swarm (VM MANAGER is the swarm leader) and then  the two others VM (WORKER1 and WORKER2) joins to the swarm. 

Then i pull in each VM a docker image, named for example MYIMAGE; then inside MANAGER VM i run:

`
docker service create --name cdn-dash  -e contraint.node==NEWMANAGER --replicas 2 -e constraint.node==WORKER1 --publish mode=host,target=80,published=9500,protocol=tcp MYIMAGE`

I expect that two service tasks are deployed on MANAGER and WORKER1 VMs.. but the result is then there is a service task on WORKER1 and another one on WORKER2.. why?

I have the same issue if i want to deploy a service task (service with 1 replica) only on a specifici node with `costraint.node` flag

**Comment by thaJeztah** [comment] 2017-06-16 13:31
Unlike "standalone" swarm, docker services use the `--constraint` flag to set constraints; https://github.com/docker/cli/blob/1fa8221743c829986894127ec5fbd1ea611329f1/docs/reference/commandline/service_create.md#specify-service-constraints---constraint

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-06-16 13:31 UTC
Labels: area/swarm, version/17.05

**Comment by Pierpaolo1992** [comment] 2017-06-16 13:44
Thanks your your answer, @thaJeztah . I've noted that it's not possibile to create a service in `global `mode with node constraint. Am i right?

**Comment by thaJeztah** [comment] 2017-06-16 14:25
constraints on global services should now be possible, possibly not on "node" filtering, but I haven't tried
