### ISSUE TITLE
Timeout in mesh network

### ISSUE THREAD

**Issue by jomagam** [moby/moby#24234] opened 2016-07-01 19:58 UTC
**Output of `docker version`:**

```
balazs@d-101:~$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:09:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:09:07 2016
 OS/Arch:      linux/amd64

balazs@d-103:~$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:09:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:09:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
balazs@d-101:~$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: active
 NodeID: b6cg1dq1d8cf9nz3t5ddppwp5
 IsManager: Yes
 Managers: 1
 Nodes: 4
 CACertHash: sha256:0aee809534d64e1c33f279ed5a007e266ec68f23636e6e692a0274d4b2f5f900
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.86 GiB
Name: d-101
ID: ZNJZ:Z5BT:TMCF:D56E:G5GK:2TOR:SXTS:4G5D:6LDL:PNGD:W2VH:DTC2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
balazs@d-101:~$ 
balazs@d-103:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: active
 NodeID: cot0zmtbftpswpyvkxmvcf0vt
 IsManager: No
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.86 GiB
Name: d-103
ID: ZNJZ:Z5BT:TMCF:D56E:G5GK:2TOR:SXTS:4G5D:6LDL:PNGD:W2VH:DTC2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have a cluster of 4 nodes that are running. They are on my local machine running on virtualbox.

**Steps to reproduce the issue:**
1. Create a swarm of the 4 hosts. d-101 is the manager, d-10[234] are the workers
2. Create a VIP service that only runs on one of the nodes; it was running on d-101. It's an nginx image with one more file created in documentroot.
3. use curl to text nginx

**Describe the results you received:**
When using the IP address of a node that does not have the container running, I get a timeout exactly every other time. 

```
balazs@d-103:~$ time curl -vs http://192.168.0.103/balazs.html
* Hostname was NOT found in DNS cache
*   Trying 192.168.0.103...
* Connected to 192.168.0.103 (192.168.0.103) port 80 (#0)
> GET /balazs.html HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.0.103
> Accept: */*
>   
< HTTP/1.1 200 OK
* Server nginx/1.11.1 is not blacklisted
< Server: nginx/1.11.1
< Date: Fri, 01 Jul 2016 19:33:39 GMT
< Content-Type: text/html
< Content-Length: 7
< Last-Modified: Fri, 01 Jul 2016 17:27:31 GMT
< Connection: keep-alive
< ETag: "5776a803-7"
< Accept-Ranges: bytes
<
BALAZS
* Connection #0 to host 192.168.0.103 left intact

real    0m0.008s
user    0m0.000s
sys 0m0.004s
balazs@d-103:~$ time curl -vs http://192.168.0.103/balazs.html
* Hostname was NOT found in DNS cache
*   Trying 192.168.0.103...
* connect to 192.168.0.103 port 80 failed: Connection timed out
* Failed to connect to 192.168.0.103 port 80: Connection timed out
* Closing connection 0

real    2m7.274s
user    0m0.000s
sys 0m0.004s
```

**Describe the results you expected:**
There should be no timeout

**Additional information you deem important (e.g. issue happens only occasionally):**
Output of netowork|service inspect-s: 

```
balazs@d-101:~$ uname -a
Linux d-101 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
balazs@d-101:~$ ifconfig 
docker0   Link encap:Ethernet  HWaddr 02:42:90:a7:1f:8a  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker_gwbridge Link encap:Ethernet  HWaddr 02:42:50:83:af:ec  
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:50ff:fe83:afec/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3504 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4756 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:743394 (743.3 KB)  TX bytes:371204 (371.2 KB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:27:77:11  
          inet addr:192.168.0.101  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe27:7711/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:168180 errors:0 dropped:0 overruns:0 frame:0
          TX packets:249356 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:18698777 (18.6 MB)  TX bytes:360086254 (360.0 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:19270 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19270 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2422652 (2.4 MB)  TX bytes:2422652 (2.4 MB)

veth01ee234 Link encap:Ethernet  HWaddr c6:93:1a:27:39:fc  
          inet6 addr: fe80::c493:1aff:fe27:39fc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:1296 (1.2 KB)

veth4470c78 Link encap:Ethernet  HWaddr 92:8d:a4:6d:51:54  
          inet6 addr: fe80::908d:a4ff:fe6d:5154/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3400 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4852 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:784026 (784.0 KB)  TX bytes:378980 (378.9 KB)

veth801f481 Link encap:Ethernet  HWaddr 2a:6c:48:e2:29:b0  
          inet6 addr: fe80::286c:48ff:fee2:29b0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:648 (648.0 B)

balazs@d-101:~$ docker service ls
ID            NAME    REPLICAS  IMAGE    COMMAND
4ptzrqcol3bw  balazs  2/6       mynginx  
balazs@d-101:~$ docker service inspect balazs
[
    {
        "ID": "4ptzrqcol3bwz7x80b62apmy6",
        "Version": {
            "Index": 1018
        },
        "CreatedAt": "2016-07-01T18:19:12.018964857Z",
        "UpdatedAt": "2016-07-01T18:19:12.021595705Z",
        "Spec": {
            "Name": "balazs",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "mynginx"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {}
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 6
                }
            },
            "UpdateConfig": {},
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {},
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 80
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "1uma8h1366itzkhqcxflgb62g",
                    "Addr": "10.255.0.7/16"
                }
            ]
        }
    }
]
balazs@d-101:~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
6fdf6f6fb3eb        bridge              bridge              local               
af5cb8802375        docker_gwbridge     bridge              local               
018d972f40a6        host                host                local               
1uma8h1366it        ingress             overlay             swarm               
5a3b134c2a9c        none                null                local               
balazs@d-101:~$ for i in 6fdf6f6fb3eb  af5cb8802375  018d972f40a6 1uma8h1366it 5a3b134c2a9c; do echo "NETWORK:$i"; docker network inspect $i ;done
NETWORK:6fdf6f6fb3eb
[
    {
        "Name": "bridge",
        "Id": "6fdf6f6fb3ebf551218f21ca8f57b04c9ea1700309aa9d283de13f2b0b80d1d6",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
NETWORK:af5cb8802375
[
    {
        "Name": "docker_gwbridge",
        "Id": "af5cb8802375ed4d9251bbf2ffb4fdfd47bfc105ce597d28394186bb6789c7e0",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "324f938c02c4407754d3dcfb4624513c65d0ca698534f86bbf37e588c6591c4f": {
                "Name": "gateway_324f938c02c4",
                "EndpointID": "2d3ded25ba9520b4e0930cca5b49e9246573218da1b3b70f83bb687ce4765551",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "73ab91497600c26efb78c5be810b8a5cd2a1db2af1f18f1cb9839f3c94e8152b": {
                "Name": "gateway_73ab91497600",
                "EndpointID": "c73ee78a318344139be865110d7c9690e7efbd35ce7f5037ab7e7c1b4500054d",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "ingress-sbox": {
                "Name": "gateway_ingress-sbox",
                "EndpointID": "216271adae8f7621b070d79ce42a4a71860b1ebf7a45d05616fa715b653ea643",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.enable_icc": "false",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.name": "docker_gwbridge"
        },
        "Labels": {}
    }
]
NETWORK:018d972f40a6
[
    {
        "Name": "host",
        "Id": "018d972f40a6391e782bdd12628e01b32e6787775a88f7b2c15d0f668999f4f8",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
NETWORK:1uma8h1366it
[
    {
        "Name": "ingress",
        "Id": "1uma8h1366itzkhqcxflgb62g",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.255.0.0/16",
                    "Gateway": "10.255.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "324f938c02c4407754d3dcfb4624513c65d0ca698534f86bbf37e588c6591c4f": {
                "Name": "balazs.1.3y0azie1uozfmp3v83lvo0bsw",
                "EndpointID": "d4e8543533711337cb514e4d1ad7e4ce4a76eeaf62d08a6f4d3ca30b091391fa",
                "MacAddress": "02:42:0a:ff:00:0a",
                "IPv4Address": "10.255.0.10/16",
                "IPv6Address": ""
            },
            "73ab91497600c26efb78c5be810b8a5cd2a1db2af1f18f1cb9839f3c94e8152b": {
                "Name": "balazs.6.7589h3umwzpb9bt3mha8jszyi",
                "EndpointID": "0faac45074c3a8124c6dcb73c06e56709059e79c6d3b26e3e215fb907a223d50",
                "MacAddress": "02:42:0a:ff:00:08",
                "IPv4Address": "10.255.0.8/16",
                "IPv6Address": ""
            },
            "ingress-sbox": {
                "Name": "ingress-endpoint",
                "EndpointID": "29306674588c700269c14b2a10d4e383de1013821e05127a0baaa26ccd6e43d0",
                "MacAddress": "02:42:0a:ff:00:03",
                "IPv4Address": "10.255.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "256"
        },
        "Labels": {}
    }
]
NETWORK:5a3b134c2a9c
[
    {
        "Name": "none",
        "Id": "5a3b134c2a9c0f884610d21492eed54e3cb67c02a0ef96f852b2a7a952cec28a",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
balazs@d-101:~$ cat dtest1/Dockerfile 
FROM nginx
RUN echo BALAZS > /usr/share/nginx/html/balazs.html
balazs@d-101:~$ 




balazs@d-103:~$ ifconfig 
docker0   Link encap:Ethernet  HWaddr 02:42:e7:10:5a:ca  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker_gwbridge Link encap:Ethernet  HWaddr 02:42:be:4f:a5:8c  
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:beff:fe4f:a58c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:141 errors:0 dropped:0 overruns:0 frame:0
          TX packets:216 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:11469 (11.4 KB)  TX bytes:15952 (15.9 KB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:56:ce:71  
          inet addr:192.168.0.103  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe56:ce71/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:252512 errors:0 dropped:0 overruns:0 frame:0
          TX packets:177423 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:189225314 (189.2 MB)  TX bytes:24085151 (24.0 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2282 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2282 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:200592 (200.5 KB)  TX bytes:200592 (200.5 KB)

vetha33021c Link encap:Ethernet  HWaddr c6:a3:b1:f3:c7:b2  
          inet6 addr: fe80::c4a3:b1ff:fef3:c7b2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:117 errors:0 dropped:0 overruns:0 frame:0
          TX packets:232 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:11499 (11.4 KB)  TX bytes:17248 (17.2 KB)

balazs@d-103:~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
d36fd62f1423        bridge              bridge              local               
478bb9764b1f        docker_gwbridge     bridge              local               
018d972f40a6        host                host                local               
1uma8h1366it        ingress             overlay             swarm               
5a3b134c2a9c        none                null                local               
balazs@d-103:~$ for i in d36fd62f1423  478bb9764b1f 018d972f40a6 1uma8h1366it  5a3b134c2a9c; do echo "NETWORK:$i"; docker network inspect $i ;done
NETWORK:d36fd62f1423
[
    {
        "Name": "bridge",
        "Id": "d36fd62f14239abe9b316419f47c1bd16eea61f2a61f75445fdaa1f0bbf9f998",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
NETWORK:478bb9764b1f
[
    {
        "Name": "docker_gwbridge",
        "Id": "478bb9764b1f5cd29eb7342fac3318a31b949dee41a1fd38850b5a2b70e10ae9",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "ingress-sbox": {
                "Name": "gateway_ingress-sbox",
                "EndpointID": "3a01efdb77df2bd2e0184352d9a7651c6eaba9df43332631fbc4b3918084ee79",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.enable_icc": "false",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.name": "docker_gwbridge"
        },
        "Labels": {}
    }
]
NETWORK:018d972f40a6
[
    {
        "Name": "host",
        "Id": "018d972f40a6391e782bdd12628e01b32e6787775a88f7b2c15d0f668999f4f8",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
NETWORK:1uma8h1366it
[
    {
        "Name": "ingress",
        "Id": "1uma8h1366itzkhqcxflgb62g",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.255.0.0/16",
                    "Gateway": "10.255.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "ingress-sbox": {
                "Name": "ingress-endpoint",
                "EndpointID": "8c167241f0fc11e14eb80dcf5461c6f147cace4fd1f526a7fe893bc366578a81",
                "MacAddress": "02:42:0a:ff:00:05",
                "IPv4Address": "10.255.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "256"
        },
        "Labels": {}
    }
]
NETWORK:5a3b134c2a9c
[
    {
        "Name": "none",
        "Id": "5a3b134c2a9c0f884610d21492eed54e3cb67c02a0ef96f852b2a7a952cec28a",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```

**Comment by jomagam** [comment] 2016-07-01 21:43
This might have something to do with me manually stopping a container in the swarm. I was able to reproduce it by setting replicas to 1, then stop-ing and rm-ing that container. A new container is created as expected, but requets to any of the nodes that do not have a container are timing out.

**Comment by mrjana** [comment] 2016-07-02 00:40
@jomagam Thanks for testing 1.12rc2 and reporting the issue. I did try your simple repro using docker master code and could not reproduce. It is possible that this issue got fixed in the recent version of the code. You can either try docker master or wait for rc3(which is probably around the corner) and try it out and let us know?

**Comment by jomagam** [comment] 2016-07-02 02:14
Sure, I'll try with rc3. I've tested basic setups since and can reproduce this randomly without doing semi-nasty things like manually stopping containers.

**Comment by thaJeztah** [comment] 2016-07-02 04:14
@jomagam RC3 was just released for testing https://github.com/docker/docker/releases/tag/v1.12.0-rc3

**Comment by ginkel** [comment] 2016-07-11 19:10
I am seeing random connection timeouts with rc3, so while my scenario is most likely not identical to @jomagam's I'm quite certain that there are still unfixed bugs. My setup described in #24486 also sporadically triggers these timeouts and also involves deleting and re-creating containers.

**Comment by michaelkrog** [comment] 2016-07-15 09:08
I am also seeing timeouts. I have 1 master and 2 nodes. All of them Ubuntu 16.04 with Docker 1.12-rc4.

I have 3 services; 2 (`edge` , `proxy`) based on the official nginx image and 1 `webservice`as a Spring Boot app. The are all in the same overlay network. The request flow is `edge`-> `proxy` -> `webservice` and `edge` has a PublishedPort(80).

If all services have 1 replica on node2, then all is fine.

Then, if I scale proxy=2, a new proxy instance will start on node1, but this replica wont be able to connect to the `webservice` instance on node2. The `proxy` replica on node2 works fine. The docker log on node1 outputs this:
```
Jul 15 10:59:29 engine9 dockerd[966]: peerdbupdate in sandbox failed for ip 10.255.0.5 and mac 02:42:0a:ff:00:05: couldn't find the subnet "10.255.0.5/16" in network "60gj1rfdfs65mun7urqj58izl"
Jul 15 10:59:29 engine9 dockerd[966]: peerdbupdate in sandbox failed for ip 10.255.0.7 and mac 02:42:0a:ff:00:07: couldn't find the subnet "10.255.0.7/16" in network "60gj1rfdfs65mun7urqj58izl"
Jul 15 10:59:29 engine9 dockerd[966]: peerdbupdate in sandbox failed for ip 10.255.0.3 and mac 02:42:0a:ff:00:03: couldn't find the subnet "10.255.0.3/16" in network "60gj1rfdfs65mun7urqj58izl"
```

**Comment by dariko** [comment] 2016-07-26 11:51
i have the same issue, both in rc4 and in the last version from master.dockerproject (commit [bad654b](https://github.com/docker/docker/commit/bad654b)).

The issue for me seems to appear after a few scaling attempts.

```
Jul 26 13:40:28 d1 dockerd[8530]: time="2016-07-26T13:40:28.427936224+02:00" level=info msg="Failed to delete real server 10.0.0.10 for vip 10.0.0.2 fwmark 256: no such file or directory"
Jul 26 13:40:52 d1 dockerd[8530]: peerdbupdate in sandbox failed for ip 10.255.0.4 and mac 02:42:0a:ff:00:04: couldn't find the subnet "10.255.0.4/16" in network "2k4hdg8kyhdejscdamy8jqe8s"
```

**Comment by thaJeztah** [comment] 2016-07-26 11:58
ping @mrjana ptal ^^

**Comment by jomagam** [comment] 2016-07-26 12:05
I have the same issues in rc4 as well. You do a few scaling events, and afterwards things go downhill fast. Do people who have this issue all use virtualbox, like I do ? Maybe the issue is somehow related to that, because otherwise I can't imagine how some have problem reproducing.

**Comment by michaelkrog** [comment] 2016-07-26 12:22
@jomagam I had the issue on physical machines. (Asrock Q1900 with Ubuntu 16.04 & Docker 1.12 RC4)

**Comment by itatabitovski** [comment] 2016-07-27 11:30
I have also noticed this on RC5

```
Jul 27 11:27:41 node-3 dockerd[2675]: peerdbupdate in sandbox failed for ip 10.255.0.4 and mac 02:42:0a:ff:00:04: couldn't find the subnet "10.255.0.4/16" in network "05br48wjst2tnc7jluciksk7h"
Jul 27 11:27:41 node-3 dockerd[2675]: peerdbupdate in sandbox failed for ip 10.255.0.5 and mac 02:42:0a:ff:00:05: couldn't find the subnet "10.255.0.5/16" in network "05br48wjst2tnc7jluciksk7h"
Jul 27 11:27:41 node-3 dockerd[2675]: peerdbupdate in sandbox failed for ip 10.255.0.3 and mac 02:42:0a:ff:00:03: couldn't find the subnet "10.255.0.3/16" in network "05br48wjst2tnc7jluciksk7h"
```

**Comment by icecrime** [comment] 2016-09-19 22:37
Can any of you please confirm that the bug still occurs with 1.12.1 (or at least with a non-RC release of 1.12.0)? In the meantime, I'll remove this one from the 1.12.2 milestone.

Ping @mrjana FYI (please let us know if you know for sure that this one was fixed, and when!).

**Comment by thaJeztah** [comment] 2023-09-16 14:04
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 14:04 UTC
Labels: kind/bug, area/networking, version/1.12
