### ISSUE TITLE
No safe method for removing images during build stages.

### ISSUE THREAD

**Issue by iorubs** [moby/moby#33396] opened 2017-05-25 11:21 UTC
**Description**
There might be a solution for this somewhere, I just can't seem to find it.

None of the methods I found for cleaning images, are safe to use while another image is building.

Some Examples:
docker system prune
docker image prune
docker rmi $(docker images -q)
docker rmi $(docker images -f dangling=true -q)
docker rmi $(docker images | awk '/days/ {print $3}')
....
and a billion other variants.

This becomes an issue in shared build environments (used by many people, from different teams for many different projects),  I know the standard is to have every build job clean up after itself but it would be nice to have a periodic job that will blow stuff away without breaking ongoing builds.

**Steps to reproduce the issue:**
1. Start building some images (used compose to build multiple)
2. keep running any of the image clean up commands, Eg. "docker image prune".

**Describe the results you received:**

docker image prune:
Deleted Images:
deleted: sha256:36bdf39886f98309d4cc294c752120301799303f0db47b316be2d1d1971730da

build result:
ERROR: Service 'elasticsearch' failed to build: No such image: sha256:36bdf39886f98309d4cc294c752120301799303f0db47b316be2d1d1971730da

**Describe the results you expected:**
Expected it to remove only unwanted images not images that might still be required by an ongoing build.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Docker version 17.05.0-ce, build 89658be
Same happens in version 1.12.

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: E3FI:UKK5:ZLDU:EEBQ:LV7S:AA3R:7BTI:CUSN:ZHQ7:I3KA:S6YX:5BYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 29
 System Time: 2017-05-25T10:32:57.010400819Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment] 2017-05-31 10:55
Thanks for reporting; it looks like this is a duplicate of https://github.com/moby/moby/issues/29011 (also see my comment here: https://github.com/moby/moby/issues/29011#issuecomment-264148868)

Let me close this issue to prevent the discussion from diverging; you can subscribe to the linked issue to stay informed on updates. Also feel free to comment here if you think I closed this by mistake 😅

**Closed by thaJeztah** 2017-05-31 10:55 UTC
Labels: area/builder, area/images
