### ISSUE TITLE
DNS Cache flush on host system not reflected in Docker containers.

### ISSUE THREAD

**Issue by illeatmyhat** [moby/moby#41097] opened 2020-06-12 03:37 UTC
DNS was not resolving on my host system for `raw.githubusercontent.com`, which caused issues in Docker.
After resetting the DNS cache in OSX Catalina, I was able to access `raw.githubusercontent.com` in the host.
However, the DNS resolution issues persisted in Docker.
I attempted restarting Docker and restarting my computer, but neither resolved the issues.
Finally, I purged all of my Docker data using the Troubleshoot UI, and the DNS resolution issue was solved.

**Steps to reproduce the issue:**
1. Cause a DNS resolution issue at the host
2. Resolve the DNS resolution issue at the host
3. Observe the DNS resolution issue persist in a container.
4. Resolve the DNS resolution issue in Docker by cleaning/purging data using the Troubleshoot UI.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 12
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.779GiB
 Name: docker-desktop
 ID: XFMM:4G5V:ATOL:5452:A22N:KJWA:SDNR:WKAQ:77WQ:QKWE:376B:PQY3
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 54
  System Time: 2020-06-12T03:29:58.495188136Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS X Catalina

**Comment by djs55** [comment] 2020-06-15 13:16
Thanks for your report. The DNS resolution in Docker Desktop uses the host resolver, via [DNSServiceRef](https://developer.apple.com/documentation/dnssd/dnsserviceref?language=objc). I believe the host has a cache in the `mDNSResponder` process which can be [flushed manually](https://help.dreamhost.com/hc/en-us/articles/214981288-Flushing-your-DNS-cache-in-Mac-OS-X-and-Linux). I don't think there's a cache in the Docker stack itself (although I could be wrong).

You should be able to see the DNS queries and responses from the VM with a command like:
```
$ docker run -it --net=host djs55/tcpdump -n -i eth0 port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
13:14:51.821165 IP 192.168.65.3.51819 > 192.168.65.1.53: 63020+ [1au] A? www.google.com. (55)
13:14:51.822475 IP 192.168.65.1.53 > 192.168.65.3.51819: 63020 1/0/0 A 216.58.204.36 (48)
```

Could you reproduce the problem and add the DNS requests and responses to the ticket?

**Comment by christhomas** [comment] 2022-03-29 11:21
I'm also running into problems where I can resolve hostnames on my local machine but inside docker containers dns is failing to resolve and I'm unable to flush the cache or do anything that doesn't involve restarting docker, which is annoying and wasteful cause if I'm in the middle of a setup, I don't wanna restart the daemon, lose my entire state and then bring it back up just cause a dns name doesn't resolve. Can we please have an option for docker daemon that allows us to restart or flush the dns cache or trigger some kind of reload, cause it's coming up a lot on a daily basis

**Comment by gldraphael** [comment] 2022-08-03 07:25
Just ran into this.

```dockerfile
 > [base 2/5] RUN apt-get update     && apt-get install -y --no-install-recommends         ca-certificates                 libc6         libgcc1         libgssapi-krb5-2         libicu63         libssl1.1         libstdc++6         zlib1g     && rm -rf /var/lib/apt/lists/*:
#0 0.528 Err:1 http://deb.debian.org/debian buster InRelease
#0 0.528   Something wicked happened resolving 'deb.debian.org:80' (-5 - No address associated with hostname)
#0 0.530 Err:2 http://deb.debian.org/debian-security buster/updates InRelease
#0 0.530   Something wicked happened resolving 'deb.debian.org:80' (-5 - No address associated with hostname)
#0 0.532 Err:3 http://deb.debian.org/debian buster-updates InRelease
#0 0.532   Something wicked happened resolving 'deb.debian.org:80' (-5 - No address associated with hostname)
#0 0.535 Reading package lists...
#0 0.541 W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Something wicked happened resolving 'deb.debian.org:80' (-5 - No address associated with hostname)
#0 0.541 W: Failed to fetch http://deb.debian.org/debian-security/dists/buster/updates/InRelease  Something wicked happened resolving 'deb.debian.org:80' (-5 - No address associated with hostname)
#0 0.541 W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Something wicked happened resolving 'deb.debian.org:80' (-5 - No address associated with hostname)
#0 0.541 W: Some index files failed to download. They have been ignored, or old ones used instead.
#0 0.546 Reading package lists...
#0 0.552 Building dependency tree...
#0 0.552 Reading state information...
#0 0.553 Package ca-certificates is not available, but is referred to by another package.
#0 0.553 This may mean that the package is missing, has been obsoleted, or
#0 0.553 is only available from another source
#0 0.553
#0 0.553 E: Package 'ca-certificates' has no installation candidate
#0 0.553 E: Unable to locate package libgssapi-krb5-2
#0 0.553 E: Unable to locate package libicu63
#0 0.553 E: Unable to locate package libssl1.1
#0 0.553 E: Couldn't find any package by glob 'libssl1.1'
#0 0.553 E: Couldn't find any package by regex 'libssl1.1'
------
failed to solve: executor failed running [/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends         ca-certificates                 libc6         libgcc1         libgssapi-krb5-2         libicu63         libssl1.1         libstdc++6         zlib1g     && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

I see the above error with `docker compose build` but not with `docker build --network host`.

Unfortunately this prints nothing:

```txt
~ ❯  docker run -it --net=host --entrypoint /usr/bin/tcpdump djs55/tcpdump -n -i eth0 port 53
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
```

Will update if I figure something.

**Comment by sam-thibault** [comment] 2023-05-09 09:56
I will close this issue on moby since this is likely specific to Docker Desktop.  Consider opening an issue on docker/for-mac ot docker/for-win if you are still encountering this issue.

**Closed by sam-thibault** 2023-05-09 09:56 UTC
Labels: status/more-info-needed, area/networking, platform/desktop, version/19.03
