### ISSUE TITLE
Certain files on disk do not sync with files in program memory

### ISSUE THREAD

**Issue by cratter49** [moby/moby#35678] opened 2017-12-02 01:38 UTC
**Description and Steps to reproduce the issue:**

I'm experiencing quite an odd error regarding files failing to be created on a Docker container with a custom Jupyter notebook server image mounted.

The context for this issue is there is a Tornado based web server running which at some point initiates a Node.js script via Python code based off of user activity. This Node.js script then launches an instance of headless Chrome, scrapes data from the web page that the browser points to, and then writes that data to new files within the Docker container. This Node.js script can be initiated multiple times in parallel. When this happens the majority of the files that are to be created and written to do show up within the Docker filesystem but a few do not which triggers failures in my program. FYI all of the files being written to by the multiple Node.js processes have unique paths. I've ensured that the file exists during the runtime of the program but it seems that the filesystem on disk does not sync with certain files for some reason. This error has me baffled.

I've ran this exact use case dozens of times and have seen the same behavior. I've run this use case on systems with 64 GB of memory and on systems with CPU's that contain 8 cores and have seen the issue which eliminates the idea that the problem could be related to a lack of system resources. Additionally, I decided to try and write the file to disk within Python by outputting the web page data from the Node.js script and picking it up from Python to eliminate the concern that the error could be from Node.js. Because of this I have come to believe that the problem could be originating from Docker somehow.

Any ideas as to what could be causing such mysterious behavior?

**Describe the results you received:**

The majority of the files were created and written to disk but some were not and resided in program or disk controller's memory.

**Describe the results you expected:**

All files should have been created and written to disk.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 120
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 196
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.803GiB
Name: default
ID: VY6A:ALCD:MOX2:OB6I:JJ23:SXWI:6LMY:2JZA:Q7RO:X5IZ:AW5G:JF33
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 61
 Goroutines: 80
 System Time: 2017-12-02T01:36:58.313089883Z
 EventsListeners: 0
Username: djwisema
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Using VirtualBox to host the VM

**Comment by thaJeztah** [comment] 2017-12-02 05:23
If you're using bind-mounted directories; this likely is something specific to Docker for Mac, and best reported through the Docker for Mac issue tracker (https://github.com/docker/for-mac/issues)

When reporting an issue, make sure to include the exact steps to reproduce, otherwise it's unlikely it can be looked into.

Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-02 05:23 UTC
Labels: version/17.06
