### ISSUE TITLE
the application in container is good in one node and bad in the other two nodes

### ISSUE THREAD

**Issue by jieerliansan** [moby/moby#35434] opened 2017-11-08 03:10 UTC
**Description**

**Steps to reproduce the issue:**
1.create service  in swarm cluster with three nodes
2.replice 3 tasks
3.access the container‘s ip to visit the web application

**Describe the results you received:**
I access the ip addresses,but one is good,the other two show error 404.

**Describe the results you expected:**
The three node has the same docker version,and the same ubuntu version.
I create the service with the same image,i described the same result in all cluster nodes.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 47
 Running: 47
 Paused: 0
 Stopped: 0
Images: 932
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10620
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: lrpb6ia00elyaksa3m7pu6ijo
 Is Manager: true
 ClusterID: 795pwkejqkrzmrdp5r8lizla2
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.138.52.1
 Manager Addresses:
  10.138.52.1:2377
  10.138.53.1:2377
  10.138.61.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-123-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 251.8 GiB
Name: hrfw007
ID: 5XVE:6MLN:MMM5:Y6IT:B3YO:G6LC:J64X:UFN7:C3MQ:66DK:S4R7:B36G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 10.138.23.225:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-11-08 13:02
You'd only be able to access a container if it's running on the same host as where you're trying to access the container's IP address from.

If you are creating a service, and publish the service's port, then you can access that service using the external IP-address of the host. Docker will use the internal load-balancer to route traffic to the containers (tasks) backing the service.

You can read more about the networking model for Swarm services here; https://docs.docker.com/engine/swarm/networking/, and the routing mesh; https://docs.docker.com/engine/swarm/ingress/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2017-11-08 13:02 UTC
Labels: version/17.03
