### ISSUE TITLE
Overlay network is in use by a task that does not exist

### ISSUE THREAD

**Issue by tisoft** [moby/moby#36498] opened 2018-03-06 12:48 UTC
**Description**

On our docker swarm cluster, we have some overlay networks that can't be deleted, because they appearently are in use by a task. I can't find the task, though.

**Steps to reproduce the issue:**

I don't know how to reproduce the issue. The networks have been created by docker-compose on a legacy swarm that is running on top of this docker swarm cluster. Usually this works fine, we just have 6 networks that were created that way, that can't be deleted anymore.

**Describe the results you received:**
```
[root@XXX ~]# docker network rm gerrit8837_default
Error response from daemon: rpc error: code = FailedPrecondition desc = network n4iawrsr18263xbqznepzu9r5 is in use by task 1yf3gempke5fpr0kvt1g3t82k
[root@XXX ~]# docker inspect 1yf3gempke5fpr0kvt1g3t82k
[
    {
        "ID": "",
        "Version": {},
        "CreatedAt": "0001-01-01T00:00:00Z",
        "UpdatedAt": "0001-01-01T00:00:00Z",
        "Labels": null,
        "Spec": {
            "ForceUpdate": 0
        },
        "Status": {
            "Timestamp": "0001-01-01T00:00:00Z",
            "ContainerStatus": {},
            "PortStatus": {}
        }
    }
]

```

**Describe the results you expected:**

i would expect either the network to be deleted, or at least some information in the inspect command about the task.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
[root@XXX ~]# docker inspect gerrit8837_default
[
    {
        "Name": "gerrit8837_default",
        "Id": "n4iawrsr18263xbqznepzu9r5",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": null,
            "Config": null
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4102"
        },
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "gerrit8837"
        }
    }
]
```

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 443
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:6-29360274-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/vgdocker/data
 Metadata file: /dev/vgdocker/metadata
 Data Space Used: 52.51GB
 Data Space Total: 102GB
 Data Space Available: 49.49GB
 Metadata Space Used: 56.38MB
 Metadata Space Total: 5.365GB
 Metadata Space Available: 5.308GB
 Thin Pool Minimum Free Space: 10.2GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 20pg5xwvfaann32pgdiobbhyn
 Is Manager: true
 ClusterID: jn2hmqyygkoacfwzwmk12fkdr
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 1
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.57.84.129
 Manager Addresses:
  XXX.XXX.XXX.135:2377
  XXX.XXX.XXX.136:2377
  XXX.XXX.XXX.180:2377
  XXX.XXX.XXX.181:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: XXX.example.com
ID: OHTV:LUXF:W2CD:NT7D:KC6M:3HO5:PSYJ:7YF7:SMYK:WRCQ:4LCE:OYOM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://web-proxy.emea.example.com:8080/
HTTPS Proxy: http://web-proxy.emea.example.com:8080/
No Proxy: example.com
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-03-06 13:51
The task you're seeing is most likely a manually started container that's attached to the network (I see the network is created with the `--attachable` option). Docker creates dummy tasks for those containers, and those can indeed not be inspected (or reveal no information).

There's a pull request that improves this here: https://github.com/moby/moby/pull/35246

To resolve your situation, check if there's a regular (non-service) container running on one of your hosts that is attached to the network

**Comment by thaJeztah** [comment] 2018-03-08 15:23
Thanks @cuericlee - that could work for situations where there's an _actual_ orphaned task attached, but in cases where a manually container is attached to the network, the correct approach would be to detach that container (or remove it).

This issue looks like a duplicate of https://github.com/moby/moby/issues/31068, so let me close this one

**Closed by thaJeztah** 2018-03-08 15:23 UTC
Labels: area/networking, area/swarm
