### ISSUE TITLE
docker service ps gives all the services starting with the same name

### ISSUE THREAD

**Issue by getvivekv** [moby/moby#35766] opened 2017-12-11 16:52 UTC
```
root@us-n-m-1:~# docker service ps us-int-soss
ID                  NAME                     IMAGE                                                                                                                    NODE                        DESIRED STATE       CURRENT STATE            ERROR               PORTS
kb79gy2ba3xz        us-int-soss.1            446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1904-08e140dc702f291f24daff363c343708bd90ebd5        us-n-w-3.mytest.cloud    Running             Running 56 seconds ago                       
ufuy8ewkkh15        us-int-soss-cron.1       446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:cron-us-int-release-1904-08e140dc702f291f24daff363c343708bd90ebd5   us-n-m-1.mytest.cloud    Running             Running 3 hours ago                          
8j52umpo3qn1         \_ us-int-soss-cron.1   446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:cron-us-int-release-1903-1e5080096936ba22dc83026df6a7000db2807b19   us-n-m-2.mytest.cloud    Shutdown            Shutdown 3 hours ago                         
vpono7gxah26         \_ us-int-soss-cron.1   446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:cron-us-int-release-1900-1c7195d96414962a6962f8fd233d11cb57cfe98f   us-n-m-3.mytest.cloud    Shutdown            Shutdown 6 hours ago                         
v3o7i9i4buva         \_ us-int-soss-cron.1   446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:cron-us-int-release-1900-1c7195d96414962a6962f8fd233d11cb57cfe98f   us-n-m-1.mytest.cloud    Shutdown            Shutdown 9 hours ago                         
phkxi83bcihw         \_ us-int-soss-cron.1   446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:cron-us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f   us-n-m-2.mytest.cloud    Shutdown            Shutdown 10 hours ago                        
9houg23mw91k        us-int-soss.1            446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        ubameggp7z57eqg7gccl28fog   Shutdown            Assigned 18 hours ago                        
ioymcf2q3tmv         \_ us-int-soss.1        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        f5e3ld2783s2odog7kfldun2d   Shutdown            Running 18 hours ago                         
qjwy71jg3zt8         \_ us-int-soss.1        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        y14dz7eef23sbm9q04x4tv7hc   Shutdown            Running 26 hours ago                         
4ujguhuvykbh         \_ us-int-soss.1        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        hx4tufkx8pq13xijidrif3fqg   Shutdown            Running 42 hours ago                         
q6tq46ujfsxw         \_ us-int-soss.1        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        othmml0mafxswpqinj7fimmtv   Shutdown            Running 44 hours ago                         
6eywkk5buujs        us-int-soss.2            446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1904-08e140dc702f291f24daff363c343708bd90ebd5        us-n-w-4.mytest.cloud    Running             Running 11 seconds ago                       
57w5gkz5vu2x         \_ us-int-soss.2        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1904-08e140dc702f291f24daff363c343708bd90ebd5        us-n-w-2.mytest.cloud    Shutdown            Running 11 seconds ago                       
kf9jh4zyknv1         \_ us-int-soss.2        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        ubameggp7z57eqg7gccl28fog   Shutdown            Assigned 18 hours ago                        
ccygsno2duj2         \_ us-int-soss.2        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        f5e3ld2783s2odog7kfldun2d   Shutdown            Running 18 hours ago                         
5dkd39l2fugk         \_ us-int-soss.2        446106882122.dkr.ecr.us-east-1.amazonaws.com/s1-soss:us-int-release-1899-1c7195d96414962a6962f8fd233d11cb57cfe98f        othmml0mafxswpqinj7fimmtv   Shutdown            Running 44 hours ago                         
root@us-n-m-1:~# 

```

There are two services
us-int-soss
us-int-soss-cron

Expectation
----------------
when running `docker service ps us-int-soss` my expectation is only to get the service status of the 'us-int-soss' service. 

Actual Result
----------------
I am getting all the services starting with the same name. 

Docker Details
----------------

```
root@us-n-m-1:~# docker -v 
Docker version 17.06.2-ce, build cec0b72
root@us-n-m-1:~# 
```

```
root@us-n-m-1:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 6k048ctsq8ddshwvz2hi4i81b
 Is Manager: true
 ClusterID: vk7g05i19hplvrckdm3sx3i57
 Managers: 3
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.24.23.30
 Manager Addresses:
  172.24.19.158:2377
  172.24.19.231:2377
  172.24.23.30:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1022-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858GiB
Name: us-n-m-1.mycloud.cloud
ID: AAEF:WHL4:HDZ6:Z3JN:BKGR:CZ3N:54XF:LXX5:LUMD:W6A3:RWP6:SD4O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
root@us-n-m-1:~# 

```

**Comment by thaJeztah** [comment] 2017-12-13 02:02
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/32556, and was fixed in https://github.com/docker/cli/pull/72, which is part of Docker 17.07 and up.

Closing this issue, but feel free to discuss

**Closed by thaJeztah** 2017-12-13 02:02 UTC
Labels: area/swarm
