### ISSUE TITLE
list dependencies of a service

### ISSUE THREAD

**Issue by hichamuntitled** [moby/moby#36596] opened 2018-03-14 17:07 UTC
Let's say we have the following stack file:

```
version: "3"
services:
  ubuntu:
    image: ubuntu
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    entrypoint:
      - tail
      - -f
      - /dev/null
    logging:
      driver: "json-file"
    ports:
      - "80:80"
    networks:
      - webnet
  web:
    image: httpd
    ports:
      - "8080:8080"
    hostname: "apache"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    depends_on:
      - "ubuntu"
    networks:
      - webnet
networks:
  webnet:
```
When I run `docker service inspect mystack_web` the output generated does not show any reference to the _depends_on_ entry.

Is that okay? and how can I print the dependencies of a given docker service?

**Docker version**
```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by thaJeztah** [comment] 2018-03-14 18:46
Correct, `depends_on` is not supported for Swarm services, so including it in your compose file will have no effect when using `docker stack deploy` (I think a warning is also printed when deploying)
 https://docs.docker.com/compose/compose-file/#depends_on

<img width="939" alt="screen shot 2018-03-14 at 19 45 22" src="https://user-images.githubusercontent.com/1804568/37424214-4222c55e-27c0-11e8-9d00-ad8c18c942cd.png">

Closing because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-03-14 18:46 UTC
Labels: area/swarm
