### ISSUE TITLE
Removing containers with /dev mounted RW deletes host's device nodes

### ISSUE THREAD

**Issue by kdomanski** [moby/moby#17865] opened 2015-11-10 13:34 UTC
I wasn't able to reliably reproduce the issue with normal usage, but I get it when using [dokku](https://github.com/progrium/dokku). Removing application containers seem to be removing device nodes mounted by `-v /dev:/dev:rw`, essentially disabling the host.

journald contains entries like this (with different device names):
`Nov 10 09:16:10 zyxasdas dockerd[593]: time="2015-11-10T09:16:10.746542467Z" level=error msg="HTTP Error" err="Cannot destroy container 152d9a61af0e: Driver overlay failed to remove root filesystem 152d9a61af0e4ebf7446e04d9b27fb6ea775fc5b5447f9dc7cea13bfd2f74dd0: remove /var/lib/docker/overlay/152d9a61af0e4ebf7446e04d9b27fb6ea775fc5b5447f9dc7cea13bfd2f74dd0/merged/dev/hugepages: device or resource busy" statusCode=500`

Version 1.7 works fine. 1.8, 1.9 and master do not.
Using `git bisect` I was able to determine that the issue is introduced with commit c32dde5b

```
$ uname -a
Linux zyxasdas 4.2.2-coreos-r1 #2 SMP Wed Oct 28 07:11:11 UTC 2015 x86_64 Intel(R) Celeron(R) 2957U @ 1.40GHz GenuineIntel GNU/Linux
```

```
$ docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   fb2bae5
 Built:        Tue Nov 10 13:04:03 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   fb2bae5
 Built:        Tue Nov 10 13:04:03 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 14
Images: 367
Server Version: 1.10.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.2-coreos-r1
Operating System: CoreOS 835.2.0+2015-11-06-1226
CPUs: 2
Total Memory: 1.813 GiB
Name: zyxasdas
ID: N662:MHAF:ECPX:UEP7:I4Q4:5BC6:L4E2:LYF2:7IAW:Q6ZC:IMKI:MPJL
```

**Comment by coolljt0725** [comment] 2015-11-10 14:16
ping the patch author @jlhawn  to take a look

**Comment by hinnerk** [comment] 2015-11-11 17:05
Hey, any news on this @jlhawn ? I too am using dokku and suddenly had an empty `/dev/` on my host machine. That's one scary thing to happen!

**Comment by jlhawn** [comment] 2015-11-11 17:36
That is very strange indeed. I can't think of why that commit (c32dde5b) would cause this issue as it only affects `docker cp` and doesn't even hook up the new code to any API endpoints, and it certainly never removes anything.

@calavera as you are more familiar with the volumes subsystem, do you have any idea how something like this may be occurring?

**Comment by kdomanski** [comment] 2015-11-12 15:55
I just double checked.
The issue is present at commit c986f85f `Merge pull request #13171 from jlhawn/archive_copy`.
The issue is absent at commit 879f440a `Merge pull request #14833 from icecrime/14756_update_lint_script` (parent commit).

**Comment by tiff** [comment] 2015-11-13 09:38
experiencing the same issue here.

**Comment by tiborvass** [comment] 2015-11-13 12:48
@kdomanski would you mind providing a reproducible script? That would facilitate fixing this issue.

**Comment by kdomanski** [comment] 2015-11-16 08:02
@tiborvass Working on it.

**Comment by kdomanski** [comment] 2015-11-16 10:51
on CoreOS beta (835.4.0)
```
#!/usr/bin/env bash

set -eu

yes | ssh-keygen -t rsa -N "" -f "$HOME/.ssh/id_rsa"
sudo docker pull kdomanski/dokku:latest
sudo mkdir -p /data/dokku/.ssh
sudo mkdir -p /config/ssh
sudo touch /data/dokku/.ssh/authorized_keys
echo $(hostname) | sudo tee /config/hostname
cat "$HOME/.ssh/id_rsa.pub" | sudo tee /config/ssh/key01
sudo docker rm -f dokku || true
sudo docker run -d --name dokku \
  -v /data/dokku:/data \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /config:/config:ro \
  -v /etc/ssh/:/etc/ssh/:ro \
  -v /usr/share/ssh/:/usr/share/ssh/:ro \
  -v $(which docker):$(which docker):ro \
  -v /lib64:/lib64:ro \
  -p 8022:22 \
  -e DOCKER_GID=$(getent group docker | cut -f3 -d':') \
  kdomanski/dokku:latest
sleep 5
rm -rf ~/rails-hello-world || true
git clone https://github.com/experimental-platform/rails-hello-world ~/rails-hello-world
cd ~/rails-hello-world
git remote add dokku ssh://dokku@localhost:8022/rails-hello-world
git push dokku master

# needs a few tries to break the system
for i in $(seq 1 10); do
  sudo docker exec -i dokku dokku ps:rebuildall
done
```

Cannot reproduce on Ubuntu.

**Comment by kdomanski** [comment] 2015-11-16 13:55
Correction: can reproduce on Ubuntu when using overlayfs

**Comment by hinnerk** [comment] 2015-11-24 08:57
@tiborvass @jlhawn any news on this?

**Comment by kdomanski** [comment] 2015-12-02 09:49
@tiborvass have you been able to reproduce the issue?

**Comment by hinnerk** [comment] 2015-12-10 09:08
@tiborvass do you need any help reproducing it?

**Comment by hinnerk** [comment] 2016-01-04 10:55
@tiborvass ping

**Comment by thaJeztah** [comment] 2016-01-04 12:17
@hinnerk apologies for the delay; I know @tiborvass has had some days off during the Holidays, but I think he'll be available again this week.

**Comment by hinnerk** [comment] 2016-01-05 16:35
I'm sad to see that this bug was now moved to a later milestone as that probably means that we're tied to an old docker version for the foreseeable future now. Is there anything we can do to help you fix this bug?

**Comment by thaJeztah** [comment] 2016-01-05 18:22
Reason it's moved is that we won't be releasing a 1.9.2 release (see our [patch-release process](https://github.com/docker/docker/blob/master/project/PATCH-RELEASES.md#deciding-if-a-patch-release-should-be-done)).

I'll ask if help is needed; thanks for offering

**Comment by calavera** [comment] 2016-01-06 23:23
@kdomanski sorry for the back and forth but I fail to see how your script mounts `/dev`. Is dokku who mounts it internally?

If you give me your public ssh key, I can add you to an ubuntu server I booted to try to reproduce this without much success.

**Comment by kdomanski** [comment] 2016-01-07 00:10
@calavera 
The image `kdomanski/dokku:latest` contains a plugin like this
https://github.com/experimental-platform/platform-dokku/blob/development/plugins/protonet-storage/docker-args-deploy
it mounts `/dev` for every deployed application.

Here's a key: http://domanski.co/raider.pub

**Comment by anusha-ragunathan** [comment] 2016-01-09 00:05
How is the dokku container removed? Does the cleanup remove contents of /dev? Is there a cleanup script we can look at? What happens when you mount some other volume (such as -v /data/dokku:/data) as read-write, run privileged container and intentionally delete data?

**Comment by kdomanski** [comment] 2016-01-12 01:32
@anusha-ragunathan @tiborvass @hinnerk 
Strangely enough, I cannot reproduce with any recent build of Docker, even when building the same versions that allowed me to reproduce the bug back in November.

Most notably, I can still reproduce on CoreOS "835.4.0" but not on "835.5.0" even though the only difference between these releases is an update to Ignition.

**Comment by kdomanski** [comment] 2016-01-12 02:36
I can also reproduce on Ubuntu 15.04 but not 15.10, which once again might be correlated with build date.

Maybe an unvendored dependency has something to do with it?

There is no cleanup procedure, the containers are simply being destroyed. Once an "affected" container is present I can trigger the removal of `/dev/` even by a simple `docker rm`.

**Comment by jfrazelle** [comment] 2016-01-12 17:32
I will try to reproduce, but the safest way to mount devices is with `--device`, the commit sha you mention does not look related :/ I am going to try to repro, but I think we can remove from milestone, let me know though if you see then when using `--device` instead

**Comment by kdomanski** [comment] 2016-01-12 18:59
@jfrazelle With `--device` the directory contents are not updated when plugging/unplugging devices.

**Comment by jfrazelle** [comment] 2016-01-12 19:04
yes, this is true.. what is your use case? are you creating devices in a
container?

**Comment by kdomanski** [comment] 2016-01-12 19:19
I'm using devices with containerized apps and I want to be able to plug/unplug devices without restarting the container.

**Comment by jfrazelle** [comment] 2016-01-12 19:24
what happens if you start the dokku container itself with -v /dev mounted, fwict from your script it is not running that way

**Comment by jfrazelle** [comment] 2016-01-12 19:26
since dokku is all bash and you are running it in a container, it is mounting that container's devices as /dev, because it is shelling out _in the container_

**Comment by kdomanski** [comment] 2016-01-12 19:37
Dokku merely wraps the docker client, the mounts are done by host's docker engine.

**Comment by jfrazelle** [comment] 2016-01-12 19:41
I cant repro when i mount /dev in the dokku container

**Comment by jfrazelle** [comment] 2016-01-12 19:48
can you?

**Comment by kdomanski** [comment] 2016-01-12 20:02
Yes, I can. On what distribution are you trying to reproduce?

**Comment by jfrazelle** [comment] 2016-01-12 20:49
15.10, ubuntu, oh wait let me try different graphdrivers

**Comment by jfrazelle** [comment] 2016-01-12 21:22
hmm i cant reproduce at all :(

**Comment by kdomanski** [comment] 2016-01-12 21:24
As I wrote, I cannot reproduce on 15.10, but I can on 15.04. But only with overlayfs.

**Comment by jfrazelle** [comment] 2016-01-12 21:25
ya I read too fast sorry

**Comment by anusha-ragunathan** [comment] 2016-01-12 22:01
@kdomanski I can reproduce this with docker 1.9.1 running on Ubuntu 15.04 with overlayfs. Although I had docker daemon debugging turned on, there was very little useful information there. Since, this behaviour is not observed in other docker images, dokku images are probably manipulating /dev in non-standard ways.

I've attached the dokku output from the repro case
[dokku.txt](https://github.com/docker/docker/files/88037/dokku.txt)

Follow on questions:
- Performing a "dokku ps:rebuildall" results in several operations. Can you review dokku.txt output and determine which of these steps manipulate /dev?
- Which /dev devices are you using in the dokku container? What are you writing to it? Can you mount explicitly those /dev devices that are being used, instead of all /dev?
- Is /dev on outer container exported to the inner containers? If yes, how?
- What does "dokku ps:rebuildall"  do?
- Finally can you provide a simplistic repro environment with a more standard image, without the dokku sauce?

**Comment by kdomanski** [comment] 2016-01-12 23:46
@anusha-ragunathan 
 - `dokku ps:rebuildall` was merely a convenience tool to recreate the app container several times - I wasn't sure if I can trigger the problem every single time.
 - It seems that the first creation of app container with `git push` is sufficient to create a container which is somehow affected. Merely removing it afterwards with `docker rm` is sufficient to wipe `/dev/`. `dokku ps:rebuildall` isn't really needed.
 - The dokku container or the app containers used here should not be using any devices at all, except for `/dev/null` and similar. I'm merely mounting `/dev/` here as a minimal reproducible case.
 - I do need entire `/dev/`
 - Containers aren't nested. Dokku container controls the host's daemon through mounted `/var/run/docker.sock`. App containers created by dokku get the host's `/dev` mounted by `-v /dev:/dev`
 - I wasn't able to reproduce the issue without dokku.
 - Literally the same docker source code built at a later date seems to be free of the issue. Only binaries built around early November seem to be affected. Please check mtime in packages at https://apt.dockerproject.org

**Comment by hinnerk** [comment] 2016-03-10 12:55
Sorry to bother but is this on anyones radar?

**Comment by thaJeztah** [comment] 2016-03-10 16:16
@hinnerk are you running on Ubuntu 15.04, or another version? Wondering if this is an issue with 15.04 (reading the discussion above) and Ubuntu 15.04 is EOL

**Comment by hinnerk** [comment] 2016-03-11 12:01
@thaJeztah we're have that issue with **CoreOS**. Additionally we can *reproduce using Ubuntu*, on which 15.04 is one of the releases that allow us to reproduce. So, no, this bug is neither dependent on Ubuntu nor fixed in any way.

**Comment by calavera** [comment] 2016-03-11 21:32
We'd really appreciate if you could provide a way to reliable reproduce this. So far, our attempts to reproduce it have not taken us anywhere.

**Comment by runcom** [comment] 2016-05-17 09:36
do either https://github.com/docker/docker/pull/22069 or https://github.com/docker/docker/pull/22009 fix this issue?

**Comment by justincormack** [comment] 2016-07-14 10:00
The dokku plugin linked that mounted `/dev` and was `--privileged` now no longer does this, due to this issue, so this will not be replicatable any more. We cannot guarantee that `--privileged` does not mess with the host system, as it does what it says and gives you full root access to the host system, allowing you to break anything, so I am going to remove the bug and P1 tags. If anyone can replicate this feel free to post (I think it must require an obscure combination of shared mounts and lazy unbinds, but it is very unclear).

**Closed** 2020-05-13 22:31 UTC
Labels: version/master
