### ISSUE TITLE
20.10.20: Unable to pull postgres:11.2

### ISSUE THREAD

**Issue by joschi** [moby/moby#44366] opened 2022-10-27 15:28 UTC
### Description

After upgrading to Docker Desktop 4.13.0 (89412) with Docker Engine 20.10.20, downloading the `postgres:11.2` image using the [CreateImage](https://docs.docker.com/engine/api/v1.41/#tag/Image/operation/ImageCreate) operation in the Docker API and combining the image name and tag in the `fromImage` parameter is failing with the following error message:
```
unknown image in /images/create?fromImage=postgres%3A11.2
```

### Reproduce

```
# echo -e "POST /images/create?fromImage=postgres%3A11.2 HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 27 Oct 2022 15:16:25 GMT
Content-Length: 65

unknown image in /images/create?fromImage=postgres%3A11.2
```

Similar to how [`docker-java`](https://github.com/docker-java/docker-java) is executing the `pull` action.

### Expected behavior

Docker Daemon should download the provided image.

This is working with other tags of the same image:
```
❯ echo -e "POST /images/create?fromImage=postgres%3A11 HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.41
Content-Type: application/json
Date: Thu, 27 Oct 2022 15:19:46 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/20.10.20 (linux)

{"status":"Pulling from library/postgres","id":"11"}
{"status":"Pulling fs layer","progressDetail":{},"id":"45f14b91a40f"}
[...]
{"status":"Waiting","progressDetail":{},"id":"72d72d727faf"}
[...]
{"status":"Downloading","progressDetail":{"current":758,"total":1663},"progress":"[======================\u003e                            ]     758B/1.663kB","id":"d076a31c93ca"}
[...]
^C
```

It's also working when splitting `fromImage` and `tag` parameters:
```
❯ echo -e "POST /images/create?fromImage=postgres&tag=11.2 HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.41
Content-Type: application/json
Date: Thu, 27 Oct 2022 15:22:02 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/20.10.20 (linux)

{"status":"Pulling from library/postgres","id":"11.2"}
[...]
^C
```

Older versions can download the image without any issue (`11.2-alpine` here, but also fails with `11.2`):
```
HTTP/1.0 200 OK
Api-Version: 1.41
Content-Type: application/json
Date: Thu, 27 Oct 2022 15:23:14 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/20.10.13 (linux)

{"status":"Pulling from library/postgres","id":"11.2-alpine"}
{"status":"Digest: sha256:ac1494b4cd5c0c6a85209e645fbb84ea186b55fa8c3678ef66dd9e4edf2b0195"}
{"status":"Status: Image is up to date for postgres:11.2-alpine"}
```

### docker version

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.13.0 (89412)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:16 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 6
  Running: 3
  Paused: 0
  Stopped: 3
 Images: 111
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 7.765GiB
 Name: docker-desktop
 ID: L4O4:PMKL:7KFT:ZO7W:HIYG:I3AU:QUGC:L6IR:WX42:6LN6:WLYJ:6G4J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

We ran into the issue while using https://github.com/revolut-engineering/jooq-plugin which is using [docker-java 3.2.8](https://github.com/docker-java/docker-java/tree/3.2.8).

**Comment by thaJeztah** [comment] 2022-10-27 16:03
Do you see the same happen when using the CLI? I just tried on a Linux machine with docker 20.10.21 (which should have o additional changes in this area), and couldn't reproduce the issue there. If this only happens on Docker Desktop, it may be best to open a ticket in https://github.com/docker/for-mac/issues

**Comment by joschi** [comment] 2022-10-27 19:08
> Do you see the same happen when using the CLI?

No, `docker pull postgres:12.1` is working fine but this is using the `imageFrom` _and_ `tag` properties under the hood, like the working example I've posted before.

```
❯ echo -e "POST /images/create?fromImage=postgres&tag=11.2 HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.41
Content-Type: application/json
Date: Thu, 27 Oct 2022 15:22:02 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/20.10.20 (linux)

{"status":"Pulling from library/postgres","id":"11.2"}
[...]
^C
```

**Comment by joschi** [comment] 2022-10-27 19:58
@thaJeztah I've tried to reproduce the issue with Debian Bullseye but it seems to work there. 🤷 

I'll open an issue in [docker/for-mac/issues](https://github.com/docker/for-mac/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). Thanks!

```
root@debian:~# uname -a
Linux debian 5.10.0-19-arm64 #1 SMP Debian 5.10.149-2 (2022-10-21) aarch64 GNU/Linux
root@debian:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

## Docker 20.10.19

```
root@debian:~# echo -e "POST /images/create?fromImage=postgres%3A11.2 HTTP/1.0\r\n" | nc.openbsd -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.41
Content-Type: application/json
Docker-Experimental: false
Ostype: linux
Server: Docker/20.10.19 (linux)
Date: Thu, 27 Oct 2022 19:43:50 GMT

{"status":"Pulling from library/postgres","id":"11.2"}
{"status":"Pulling fs layer","progressDetail":{},"id":"29b80961214d"}
[...]
{"status":"Digest: sha256:85d0c745dc4f4627184da8945a36ac773762ec5d2ba1c1821cc7334b736e6e00"}
{"status":"Status: Downloaded newer image for postgres:11.2"}
```

<details>
<summary>docker version && docker info</summary>

```
root@debian:~# dpkg -l docker-ce
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                        Architecture Description
+++-==============-==============================-============-====================================================
ii  docker-ce      5:20.10.19~3-0~debian-bullseye arm64        Docker: the open-source application container engine
```

```
root@debian:~# docker version
Client: Docker Engine - Community
 Version:           20.10.19
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        d85ef84
 Built:             Thu Oct 13 16:45:42 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.19
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       c964641
  Built:            Thu Oct 13 16:44:07 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
root@debian:~# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.19
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-arm64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 3.823GiB
 Name: debian
 ID: SFOB:EQOE:CWHS:BEMW:6PH7:MJCV:EVZT:JXPD:YCVI:PDMB:R6KM:UD7C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
</details>

## Docker 20.10.20

```
root@debian:~# echo -e "POST /images/create?fromImage=postgres%3A11.2-alpine HTTP/1.0\r\n" | nc.openbsd -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.41
Content-Type: application/json
Docker-Experimental: false
Ostype: linux
Server: Docker/20.10.20 (linux)
Date: Thu, 27 Oct 2022 19:54:29 GMT

{"status":"Pulling from library/postgres","id":"11.2-alpine"}
{"status":"Pulling fs layer","progressDetail":{},"id":"6f37394be673"}
[...]
{"status":"Pull complete","progressDetail":{},"id":"dd936443c289"}
{"status":"Digest: sha256:ac1494b4cd5c0c6a85209e645fbb84ea186b55fa8c3678ef66dd9e4edf2b0195"}
{"status":"Status: Downloaded newer image for postgres:11.2-alpine"}
```

<details>
<summary>docker version && docker info</summary>

```
root@debian:~# dpkg -l docker-ce
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                        Architecture Description
+++-==============-==============================-============-====================================================
ii  docker-ce      5:20.10.20~3-0~debian-bullseye arm64        Docker: the open-source application container engine
```

```
root@debian:~# docker version
Client: Docker Engine - Community
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:19:53 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:16 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
root@debian:~# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-arm64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 3.823GiB
 Name: debian
 ID: SFOB:EQOE:CWHS:BEMW:6PH7:MJCV:EVZT:JXPD:YCVI:PDMB:R6KM:UD7C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
</summary>

**Comment by thaJeztah** [comment] 2022-10-27 20:31
Thanks! Let me close the issue here

**Closed by thaJeztah** 2022-10-27 20:31 UTC
Labels: status/0-triage, kind/bug

**Comment by gesellix** [comment] 2022-11-05 20:48
This also happens on Docker Desktop for Windows, see the version details below. Do you think this is a Docker Desktop specific issue or could it have a common cause? According to the release notes of Moby 20.10.20 some changes happened in the area around parsing and interpreting image references when pulling by `image:tag@digest`. I'm happy to create an issue in the docker/for-win repo, similar to the one at docker/for-mac, if you want me to.

Docker Version:

```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:28:44 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.13.1 (90346)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Docker Info:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.62GiB
 Name: docker-desktop
 ID: LSCK:ICON:Y7SS:6XSK:THKR:KDW4:CQDO:SMHD:B72K:ZVI5:ZV2D:Q7U2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by gesellix** [comment] 2022-11-05 20:59
... doesn't fail on a Windows GitHub Runner, though, apparently another argument pointing towards Docker Desktop:

```
# docker version

Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:08:16 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:03:04 2022
  OS/Arch:          windows/amd64
  Experimental:     false

# docker info

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.12.2)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.21
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Windows Server 2022 Datacenter Version 2009 (OS Build 20348.1129)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7GiB
 Name: fv-az206-120
 ID: OSYC:5BQ6:HZ6L:KOFN:L5NU:DWPF:XUA5:5F74:EEIM:SJNI:RCFG:QW2R
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Username: ***
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by gesellix** [comment] 2022-11-06 09:36
I'm trying to better understand the error by pulling the images through a temporary container (not sure if this is putting Docker Desktop out of the equation). See the following examples and how the responses/error messages are formatted:

## example 1: trying to pull a non-existing image (failing, correct behaviour)

```
# docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock alpine:edge ash -c "apk add netcat-openbsd && echo -e 'POST /images/create?fromImage=registry:2222 HTTP/1.0\r\n' | nc -U /var/run/docker.sock"
HTTP/1.0 404 Not Found
Api-Version: 1.41
Content-Type: application/json
Date: Sat, 05 Nov 2022 22:40:31 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/20.10.20 (linux)

{"message":"manifest for registry:2222 not found: manifest unknown: manifest unknown"}
```

## example 2: trying to pull an existing image (existing remotely, but the pull via api fails)

```
# docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock alpine:edge ash -c "apk add netcat-openbsd && echo -e 'POST /images/create?fromImage=registry:2.8.1 HTTP/1.0\r\n' | nc -U /var/run/docker.sock"
HTTP/1.0 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sat, 05 Nov 2022 22:40:54 GMT
Content-Length: 57

unknown image in /images/create?fromImage=registry:2.8.1
```

The response headers are also different... another indication that Docker Desktop has an issue and not Moby? I supposed when testing from the perspective of a temporary container, Docker Desktop wouldn't be involved 🤔
