### ISSUE TITLE
Docker version 17.12.1-ce mounts /dev/snd devices as group root - breaks alsa applications

### ISSUE THREAD

**Issue by fadams** [moby/moby#36457] opened 2018-03-01 17:04 UTC
In Docker version 17.12.0-ce when using `--device=/dev/snd` in docker run the devices are mounted owned by root but in group audio - this can be seen by doing `ls -al /dev/snd` in a container that uses `--device=/dev/snd`.

I've just upgraded to Docker version 17.12.1-ce via my distro updater and my application has stopped working, upon investigation I noticed that when doing `ls -al /dev/snd` the devices have both owner and group as root, which is the most likely culprit. This was proved by execing into the container as  uid 0 and manually doing `chown root:audio *` in /dev/snd

Don't know if other devices are affected by this though I'd be surprised if it was just /dev/snd

**Comment by thaJeztah** [comment] 2018-03-01 17:26
Looks like a duplicate of https://github.com/moby/moby/issues/36446 (which will be resolved through https://github.com/moby/moby/pull/36449), and is caused by a bug in runc 1.0.0-rc4 and up: opencontainers/runc#1742 and is fixed in opencontainers/runc#1743, which is part of runc 1.0.0-rc5

**Closed** 2018-03-05 10:44 UTC
Labels: area/runtime, kind/bug

**Comment by thaJeztah** [comment] 2018-03-05 11:50
Fix has been merged to master, and will be included in nightly builds of docker soon (e.g. https://download.docker.com/linux/ubuntu/dists/xenial/pool/nightly/amd64/). I also opened a ticket to request including the fix in the upcoming 18.03 Docker release (but it's up to the release team to decide if it will be included 😅 )
