### ISSUE TITLE
Global scoped volume's labels and options are found only on specific daemon 

### ISSUE THREAD

**Issue by shyr** [moby/moby#33973] opened 2017-07-06 06:33 UTC
**Description**

Labels and options of global scoped volume can be displayed only on the daemon where volume is created, when we do `docker volume inspect`.

**Steps to reproduce the issue:**
1. With swarm mode cluster and global volume plugin, create global scoped volume with label and option.
``` shell
[irteamsu@cdev-r01n001.shipdock ~]$ docker volume create --name test1 --driver=ceph --label color="red" --opt shape="circle"
test1
```
2. We can find the volume's infomation including labels and options on that node.
```shell
[irteamsu@cdev-r01n001.shipdock ~]$ docker volume inspect test1
[
    {
        "Driver": "ceph:latest",
        "Labels": {
            "color": "red",
            "com.navercorp.ceph.x-project-id": "e8d83c491663412394943e9c23e32e10"
        },
        "Mountpoint": "/var/lib/ceph/mount/test1",
        "Name": "test1",
        "Options": {
            "shape": "circle",
            "x-project-id": "e8d83c491663412394943e9c23e32e10"
        },
        "Scope": "global"
    }
]
```
3. But on the other nodes, we can not find label and option.
```bash
[irteamsu@cdev-r01n002.shipdock ~]$ docker volume inspect test1
[
    {
        "Driver": "ceph:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/ceph/mount/test1",
        "Name": "test1",
        "Options": {},
        "Scope": "global"
    }
]
```

**Describe the results you received:**
`docker volume inspect` for global volume responded without label and options.

**Describe the results you expected:**
`docker volume inspect` for "global" scoped volume should respond including labels and options, because it's "global scoped".

**Additional information you deem important (e.g. issue happens only occasionally):**
When we do `docker volume inspect` for global scoped volume, docker find label and option at `VolumeStore` which belongs to docker daemon. You can find this at [here](https://github.com/moby/moby/blob/17.05.x/volume/store/store.go#L470~L529).
It seems that is the reason why docker respond differently depends on daemon. But I think label and option for global volume should be consistent on every node in the same cluser.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 120
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:3-4833289-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.135GB
 Data Space Total: 107.4GB
 Data Space Available: 86.18GB
 Metadata Space Used: 8.835MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.139GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home1/docker/devicemapper/devicemapper/data
 Metadata loop file: /home1/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ibi1duxpatz4wr9u4yfm7oxsy
 Is Manager: true
 ClusterID: l6owmr4eios63jokbkmoztnzn
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.113.248.226
 Manager Addresses:
  10.113.248.225:2377
  10.113.248.226:2377
  10.113.250.228:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.388GiB
Name: dev-dcluster001.ncl
ID: RJ5K:LO2K:332T:WKGJ:2ZME:N4ZX:ZNUF:LR3K:QJLX:FYBC:YM2M:S3C6
Docker Root Dir: /home1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-07-08 10:36
Thanks for reporting; this is actually a duplicate of https://github.com/moby/moby/issues/26948. I'm closing this one to prevent the discussion from diverging, but feel free to comment after I closed

**Closed by thaJeztah** 2017-07-08 10:36 UTC
Labels: area/volumes, version/17.05
