### ISSUE TITLE
Initializing docker compose volumes

### ISSUE THREAD

**Issue by gittycat** [moby/moby#20390] opened 2016-02-17 09:23 UTC
With Docker 1.10.0, Named volumes are now initialized from the docker container that they are first mounted on. https://github.com/docker/docker/issues/18670

This means that after doing `docker run -v data:/usr/lib alpine /bin/true`, a volume named `data` is created which contains whatever the alpine image has at `/usr/lib`.

This isn't clear with docker compose. In the following docker-compose file for instance, we don't know which service will initialize the volume `data`.

```
version: '2'
services:
    app1:
        image: imageA
        volumes:
            - data:/var/myapp
    app2:
        image: imageB
        volumes:
            - data:/var/myapp
volumes:
    data:
```

There are hacks to get around this (creating services only for the purpose of initializing volumes) but is there any plan to have a simpler and more elegant way to specify how a volume is initialized?

**Comment by cpuguy83** [comment] 2016-02-17 14:36
It is fairly simple as it is right now -- the first thing that attaches the volume will "initialize" it, and it can only be initialized if nothing else is attached to the volume.

If you do `volumes_from` in `app2`, that would satisfy the requirement in this example... I understand that's not necessarily the best approach in cases where you have multiple volumes and don't necessarily want to share them all.

What do the compose folks think? ping @dnephin

**Comment by dnephin** [comment] 2016-02-18 23:20
I would personally really like to see a tool specifically designed for this purpose. Instead of just copying files from a path in one container it would let you define a container, a command, and a target named volume, and you could run it to initialize, update, or export some named volume.  I don't think that functionally really fits in any of the current tools.

**Comment by LK4D4** [comment] 2016-09-14 19:00
@cpuguy83 @dnephin What do you think we should do with this issue?

**Comment by dnephin** [comment] 2016-09-14 19:19
My position hasn't changed from the above comment:

> I would personally really like to see a tool specifically designed for this purpose

I think docker does enough to initialise volumes, anything more elaborate is a less common use case and can be built into a separate tool.

**Comment by ambrons** [comment] 2017-01-30 21:11
With the introduction of compose V3 the `volumes_from` has been deprecated and no longer usable in a compose file especially when doing a `docker stack deploy`.  So the issue of having a container initialize a volume is back.

For some context we are using a docker container to copy items from S3 into a docker compose defined volume and want several instances to have access to it.  The problem is that `depends_on` doesn't adequately solve this issue.  Looks like introduced recently is a `HEALTHCHECK` property, but this seems like a huge hack to write a healthcheck for a container initializing a volume.

**Comment by JacobBrownAustin** [comment] 2018-05-09 22:16
Is there any solution to this problem yet?

**Comment by cpuguy83** [comment] 2018-05-09 22:51
You can pre-create a volume and populate as needed.
You can also put the seed volume data into the image for the container that is consuming it.

Typically wouldn't only one container have data at the volume path location?

**Comment by thaJeztah** [comment] 2023-09-25 14:55
I think the best option for these cases is to use the `nocopy` option (https://github.com/moby/moby/pull/21223); this would define which services should (or should not) be taken into account for copying data into the volume if it's empty; https://docs.docker.com/compose/compose-file/05-services/#volumes, but perhaps improvements can be made in compose (https://github.com/docker/compose), and there's a (still pending) proposal to be able to mount an image as a (read-only volume (https://github.com/moby/moby/issues/30449)


I'm closing this ticket,  but feel free to continue the conversation.

**Closed by thaJeztah** 2023-09-25 14:55 UTC
Labels: area/volumes
