### ISSUE TITLE
Install fails on Debian due to invalid APT source list

### ISSUE THREAD

**Issue by kaptajnen** [moby/moby#21459] opened 2016-03-24 00:00 UTC
The docker install script at get.docker.com creates the following invalid apt source list

`deb c https://apt.dockerproject.org/repo debian-jessie main`

It seems to me the issue is the brackets are not escaped on this line in the script where an attempt to include the system architecture is made
`$sh_c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"`

It results in the following error:

```
E: Malformed line 1 in source list /etc/apt/sources.list.d/docker.list (URI pars                                                                                                      e)
E: The list of sources could not be read.
```

Steps to reproduce:
1. Execute `curl -fsSL https://get.docker.com/ | sh` on a Debian machine

**Comment by HackToday** [comment] 2016-03-24 00:11
hi, could you execute on your machine about this and paste the result here ?
`echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo`

**Comment by kaptajnen** [comment] 2016-03-24 00:20
It looks like this:
```
$ echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo
deb c https://apt.dockerproject.org/repo
```

**Comment by HackToday** [comment] 2016-03-24 01:39
strange, what kind of shell do you use ?

And also could it possible for you to provide full info about operation system release and version ? Is it official os or customized ?

**Comment by kaptajnen** [comment] 2016-03-24 02:46
It's just bash. I'm using whatever image digital ocean provides so I'm not sure if it's modified in any way. It just says Debian 8.3.

**Comment by andras-tim** [comment] 2016-03-25 09:56
A missing escaping will solve this issue:
``` diff
--- a   2016-03-10 22:54:58.000000000 +0100
+++ b   2016-03-25 10:50:59.067434122 +0100
@@ -411,7 +411,7 @@
                        set -x
                        $sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"
                        $sh_c "mkdir -p /etc/apt/sources.list.d"
-                       $sh_c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"
+                       $sh_c "echo deb \[arch=$(dpkg --print-architecture)\] https://apt.dockerproject.org/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"
                        $sh_c 'sleep 3; apt-get update; apt-get install -y -q docker-engine'
                        )
                        echo_docker_as_nonroot
```

**Comment by HackToday** [comment] 2016-03-25 13:09
@andras-tim  My only curious how it work in ubuntu while not work on Debian ?  My ubuntu seems can work.

**Comment by andras-tim** [comment] 2016-03-25 15:15
@HackToday The original script was not run on my Ubuntu 14.04, but there is a mistake:

* When I want to install docker first, I got same error, what could I solve with my patch. - The `docker.list` was contained `deb h https://...` line, and this was not solved by multiple retries.
* But now, I removed the whole docker from my system with prune, removed the `docker.list` file too, and I tried to reproduce this issue with `curl -fsSL https://get.docker.com/ | sh -x` for send some debug output, but it's substituted properly with my arch...

I have not add my user to *docker* group, and the script was run as normal user (not sudo) when the problem was ocurred.
So, I'm a bit confusing now, but when that caused forgot to create debug info. Sorry.

**Comment by andras-tim** [comment] 2016-03-25 15:32
Wow! I can reproduce the problem! Have to reboot the machine after the docker was purged, and the `docker.list` was removed.

There are the detailed output of the script *- script was run as user*
> ```
> + url=https://get.docker.com/
> + do_install
> + uname -m
> + command_exists docker
> + command -v docker
> + id -un
> + user=tia
> + sh_c=sh -c
> + [ tia != root ]
> + command_exists sudo
> + command -v sudo
> + sh_c=sudo -E sh -c
> + curl=
> + command_exists curl
> + command -v curl
> + curl=curl -sSL
> + repo=main
> + [ https://test.docker.com/ = https://get.docker.com/ ]
> + [ https://experimental.docker.com/ = https://get.docker.com/ ]
> + lsb_dist=
> + dist_version=
> + command_exists lsb_release
> + command -v lsb_release
> + lsb_release -si
> + lsb_dist=Ubuntu
> + [ -z Ubuntu ]
> + [ -z Ubuntu ]
> + [ -z Ubuntu ]
> + [ -z Ubuntu ]
> + [ -z Ubuntu ]
> + [ -z Ubuntu ]
> + echo Ubuntu
> + tr [:upper:] [:lower:]
> + lsb_dist=ubuntu
> + command_exists lsb_release
> + command -v lsb_release
> + lsb_release --codename
> + cut -f2
> + dist_version=trusty
> + [ -z trusty ]
> + check_forked
> + command_exists lsb_release
> + command -v lsb_release
> + set +e
> + lsb_release -a -u
> + lsb_release_exit_code=2
> + set -e
> + [ 2 = 0 ]
> + [ -r /etc/debian_version ]
> + [ ubuntu != ubuntu ]
> + export DEBIAN_FRONTEND=noninteractive
> + did_apt_get_update=
> + grep -q aufs /proc/filesystems
> + cat /sys/module/apparmor/parameters/enabled
> + [ Y = Y ]
> + command -v apparmor_parser
> + echo apparmor is enabled in the kernel and apparmor utils were already installed
> apparmor is enabled in the kernel and apparmor utils were already installed
> + [ ! -e /usr/lib/apt/methods/https ]
> + [ -z curl -sSL ]
> + set -x
> + sudo -E sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
> Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.6eRsSFvRTm --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/alessandro-strada-ppa.gpg --keyring /etc/apt/trusted.gpg.d/atareao-atareao.gpg --keyring /etc/apt/trusted.gpg.d/brightbox-ruby-ng.gpg --keyring /etc/apt/trusted.gpg.d/bumblebee-stable.gpg --keyring /etc/apt/trusted.gpg.d/daniel_pavel-solaar.gpg --keyring /etc/apt/trusted.gpg.d/deluge-team-ppa.gpg --keyring /etc/apt/trusted.gpg.d/dlech-keepass2-plugins-beta.gpg --keyring /etc/apt/trusted.gpg.d/dlech-keepass2-plugins.gpg --keyring /etc/apt/trusted.gpg.d/ermshiperete-monodevelop.gpg --keyring /etc/apt/trusted.gpg.d/fingerprint-fingerprint-gui.gpg --keyring /etc/apt/trusted.gpg.d/inizan-yannick-mono.gpg --keyring /etc/apt/trusted.gpg.d/jfswitz-released.gpg --keyring /etc/apt/trusted.gpg.d/jtaylor-keepass.gpg --keyring /etc/apt/trusted.gpg.d/libreoffice-ppa.gpg --keyring /etc/apt/trusted.gpg.d/linuxgndu-sqlitebrowser.gpg --keyring /etc/apt/trusted.gpg.d/mc3man-trusty-media.gpg --keyring /etc/apt/trusted.gpg.d/mdoyen-homebank.gpg --keyring /etc/apt/trusted.gpg.d/mqchael-pipelight.gpg --keyring /etc/apt/trusted.gpg.d/nilarimogard-webupd8.gpg --keyring /etc/apt/trusted.gpg.d/pipelight-stable.gpg --keyring /etc/apt/trusted.gpg.d/plexapp-plexht.gpg --keyring /etc/apt/trusted.gpg.d/saltstack-salt.gpg --keyring /etc/apt/trusted.gpg.d/steam.gpg --keyring /etc/apt/trusted.gpg.d/stebbins-handbrake-releases.gpg --keyring /etc/apt/trusted.gpg.d/stvs-tomate.gpg --keyring /etc/apt/trusted.gpg.d/thefanclub-grive-tools.gpg --keyring /etc/apt/trusted.gpg.d/tualatrix-ppa.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-java.gpg --keyring /etc/apt/trusted.gpg.d/xorg-edgers-ppa.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
> gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
> gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
> gpg: Total number processed: 1
> gpg:              unchanged: 1
> + sudo -E sh -c mkdir -p /etc/apt/sources.list.d
> + dpkg --print-architecture
> + sudo -E sh -c echo deb [arch=amd64] https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
> + sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
> E: Malformed line 1 in source list /etc/apt/sources.list.d/docker.list (URI parse)
> E: The list of sources could not be read.
> Reading package lists...
> E: Malformed line 1 in source list /etc/apt/sources.list.d/docker.list (URI parse)
> E: The list of sources could not be read.
> E: The package lists or status file could not be parsed or opened.
> ```

And the results in **/etc/apt/sources.list.d/docker.list**:
```
deb h https://apt.dockerproject.org/repo ubuntu-trusty main
```

**Comment by andras-tim** [comment] 2016-03-25 16:18
I have debugged this problem.

Every time, when you use the current command wrapper (`$sh_c`) for run commands as root, you should pay attention to proper escaping.

**And there is the difference!**
* started script as root: `sh_c='sh -c'`
* started script as normal user: `sh_c='sudo -E sh -c'`


**In other hand, the shell handles different the simple and double quotes.**

Basically, this script has been written in such a way that uses `$sh_c` with **single quoted** commands when it's possible. But there used some variables, what requires **double quotes**.

**So, I think, my original patch was right, but I added some extra changes to avoid future problems:**

``` diff
--- install2.sh 2016-03-25 16:52:40.771401325 +0100
+++ install3.sh 2016-03-25 16:57:39.251406687 +0100
@@ -409,9 +409,9 @@
                        fi
                        (
                        set -x
-                       $sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"
-                       $sh_c "mkdir -p /etc/apt/sources.list.d"
-                       $sh_c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"
+                       $sh_c 'apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D'
+                       $sh_c 'mkdir -p /etc/apt/sources.list.d'
+                       $sh_c "echo deb \[arch=$(dpkg --print-architecture)\] https://apt.dockerproject.org/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"
                        $sh_c 'sleep 3; apt-get update; apt-get install -y -q docker-engine'
                        )
                        echo_docker_as_nonroot
```

**Comment by HackToday** [comment] 2016-03-26 00:21
Sorry, I did not catch that.
From my ubuntu machine, I executed as below

```
ubuntu@testsecomp:~$ sudo -E sh -c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo"
deb [arch=amd64] https://apt.dockerproject.org/repo
ubuntu@testsecomp:~$ sh -c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo"
deb [arch=amd64] https://apt.dockerproject.org/repo
ubuntu@testsecomp:~$ sudo passwd 
Enter new UNIX password: 
Retype new UNIX password: 
passwd: password updated successfully
ubuntu@testsecomp:~$ su
Password: 
root@testsecomp:/home/ubuntu# sh -c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo"
deb [arch=amd64] https://apt.dockerproject.org/repo
root@testsecomp:/home/ubuntu# sudo -E sh -c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo"
deb [arch=amd64] https://apt.dockerproject.org/repo

```

Seems all is OK

**Comment by yoshiokatsuneo** [comment] 2016-06-03 04:34
@HackToday The problem happens when we have a file with one of filename "a", "r", "c", "h", "=", "a", "m", "d", "6", "4" on the current directory. In such case, shell expand "[arch=amd64]" to "a" (if file "a" exists.).
I got the error because I tend to create temporary file with filename "a"...

**Comment by kaptajnen** [comment] 2016-06-03 16:19
@yoshiokatsuneo Thanks, that was the problem. I had a directory named "c" which caused it to break.

**Comment by amitkumarj441** [comment] 2016-10-19 13:08
@kaptajnen I'm also getting the same error on Ubuntu 16.04 and finally tested and here is the test result:

`curl -fsSL https://get.docker.com/ | shapparmor is enabled in the kernel and apparmor utils were already installed
+ sudo -E sh -c apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: /tmp/tmp.1mD6pokU68/gpg.1.sh --keyserver
hkp://ha.pool.sks-keyservers.net:80
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server ha.pool.sks-keyservers.net
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ break
+ sudo -E sh -c apt-key adv -k 58118E89F3A912897C070ADBF76221572C52609D >/dev/null
+ sudo -E sh -c mkdir -p /etc/apt/sources.list.d
+ dpkg --print-architecture
+ sudo -E sh -c echo deb \[arch=amd64\] https://apt.dockerproject.org/repo ubuntu-xenial main > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]   
Hit:2 http://in.archive.ubuntu.com/ubuntu xenial InRelease                    
Get:3 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]        
Get:4 https://apt.dockerproject.org/repo ubuntu-xenial InRelease [30.2 kB]
Get:5 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages [2,478 B]             
Hit:6 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease  
Fetched 223 kB in 2s (88.0 kB/s)
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  aufs-tools cgroupfs-mount git git-man liberror-perl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  aufs-tools cgroupfs-mount docker-engine git git-man liberror-perl
0 upgraded, 6 newly installed, 0 to remove and 208 not upgraded.
Need to get 23.2 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Get:1 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 aufs-tools amd64 1:3.2+20130722-1.1ubuntu1 [92.9 kB]
Get:2 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 docker-engine amd64 1.12.2-0~xenial [19.3 MB]
Get:3 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 cgroupfs-mount all 1.2 [4,970 B]
Get:4 http://in.archive.ubuntu.com/ubuntu xenial/main amd64 liberror-perl all 0.17-1.2 [19.6 kB]
Get:5 http://in.archive.ubuntu.com/ubuntu xenial/main amd64 git-man all 1:2.7.4-0ubuntu1 [735 kB]
Get:6 http://in.archive.ubuntu.com/ubuntu xenial/main amd64 git amd64 1:2.7.4-0ubuntu1 [3,006 kB]
Fetched 23.2 MB in 26s (879 kB/s)
Selecting previously unselected package aufs-tools.
(Reading database ... 173151 files and directories currently installed.)
Preparing to unpack .../aufs-tools_1%3a3.2+20130722-1.1ubuntu1_amd64.deb ...
Unpacking aufs-tools (1:3.2+20130722-1.1ubuntu1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../cgroupfs-mount_1.2_all.deb ...
Unpacking cgroupfs-mount (1.2) ...
Selecting previously unselected package docker-engine.
Preparing to unpack .../docker-engine_1.12.2-0~xenial_amd64.deb ...
Unpacking docker-engine (1.12.2-0~xenial) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17-1.2_all.deb ...
Unpacking liberror-perl (0.17-1.2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.7.4-0ubuntu1_all.deb ...
Unpacking git-man (1:2.7.4-0ubuntu1) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.7.4-0ubuntu1_amd64.deb ...
Unpacking git (1:2.7.4-0ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (229-4ubuntu7) ...
Setting up aufs-tools (1:3.2+20130722-1.1ubuntu1) ...
Setting up cgroupfs-mount (1.2) ...
Setting up docker-engine (1.12.2-0~xenial) ...
Setting up liberror-perl (0.17-1.2) ...
Setting up git-man (1:2.7.4-0ubuntu1) ...
Setting up git (1:2.7.4-0ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for systemd (229-4ubuntu7) ...
Processing triggers for ureadahead (0.100.0-19) ...
+ sudo -E sh -c docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker computer101

Remember that you will have to log out and back in for this to take effect!
`

**Comment by vdemeester** [comment] 2018-02-14 13:15
Given the time of no activities I'm gonna close this issue as I think it's probably fixed.

**Closed by vdemeester** 2018-02-14 13:15 UTC
Labels: area/project, kind/bug
