### ISSUE TITLE
docker-compose in swarm mode ports long syntax bindaddress

### ISSUE THREAD

**Issue by silvio-dizmo** [moby/moby#34212] opened 2017-07-21 13:55 UTC
since docker-compose 3.2 you can apparently use

ports:
  - target: 80
    published: 8080
    protocol: tcp
    mode: host

But what if I about -p 127.0.0.1:8080:80? Is there some way to have both mode and bindaddress?

**Comment by silvio-dizmo** [comment] 2017-07-21 13:57
relevant documentation
https://docs.docker.com/compose/compose-file/#ports

**Comment by thaJeztah** [comment] 2017-07-21 23:40
Looks like this is a duplicate of https://github.com/moby/moby/issues/26696; IP-address is not (yet) supported in the long format (see the implementation in https://github.com/moby/moby/pull/27917).

Let me close this one as it looks to be a duplicate of https://github.com/moby/moby/issues/26696, and to prevent the discussion from diverging, but feel free to comment after I closed

**Closed by thaJeztah** 2017-07-21 23:40 UTC

**Comment by silvio-dizmo** [comment] 2017-07-24 06:41
I was unaware that there were implementational things missing for this feature and I can see that this might not make much sense except for localhost. Anyway it seems it is currently (17.06) impossible to make a swarm service that can only be accessed from localhost. Since the firewall rules are currently also not working properly #1827.

**Comment by silvio-dizmo** [comment] 2017-07-24 11:27
I was unaware that there were implementational things missing for this feature and I can see that this might not make much sense except for localhost. Anyway it seems like it is currently (17.06) impossible to make a swarm service that can only be accessed from localhost. Since the firewall rules are currently also not working properly #1827.
