### ISSUE TITLE
after i change the docker default devicemapper mode(from loop-lvm to direct-lvm ),image can't run anymore!

### ISSUE THREAD

**Issue by AgainstWind** [moby/moby#34055] opened 2017-07-11 10:00 UTC
error log：

container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: \""
/usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: \\\"\"\n".

**Comment by thaJeztah** [comment] 2017-07-13 09:08
switching from loop-lvm to direct-lvm is not just a matter of setting that option; see the instructions in https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production - be aware that you'll be creating a new storage for this, so the existing images and container won't be accessible after switching.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is a support question not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-07-13 09:08 UTC
Labels: area/runtime
