### ISSUE TITLE
BuildKit Builds Cannot Address Image Ids

### ISSUE THREAD

**Issue by paulistoan** [moby/moby#42848] opened 2021-09-13 18:41 UTC
**Description**

BuildKit builds are unable to use image ids in the `FROM` line

**Steps to reproduce the issue:**
Run the following:
```
export DOCKER_BUILDKIT=1

docker build --iidfile iid -<<QEND
FROM public.ecr.aws/amazonlinux/amazonlinux:latest
RUN yum install -y python3-pip
RUN pip3 install requests
QEND

docker build -<<QEND
FROM $(cat iid)
RUN pip3 install flask
QEND
```

Notice that removing `export DOCKER_BUILDKIT=1` makes the build succeed.

**Describe the results you received:**
```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Describe the results you expected:**
Expected build command to succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.15.14
 Git commit:        f0df350
 Built:             Tue Aug 17 16:01:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.14
  Git commit:       b0f5bc3
  Built:            Tue Aug 17 16:02:23 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0
  GitCommit:        %runc_commit
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: %runc_commit
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.243-185.433.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 983.3MiB
 Name: ip-172-31-86-74.ec2.internal
 ID: E26I:XNMF:BD5B:QPEK:WOGO:LXYM:6PW3:KSA5:3ZFD:4AXO:ZK55:CPMU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

Running in AWS EC2

**Comment by thaJeztah** [comment] 2021-09-14 11:24
Thanks for reporting; I think this is a duplicate of https://github.com/moby/buildkit/issues/2204 in the BuildKit repository; let me close this one to prevent the conversation from diverging (but feel free to participate on that ticket)

**Closed by thaJeztah** 2021-09-14 11:24 UTC
Labels: kind/enhancement, area/builder/buildkit
