### ISSUE TITLE
question about stopsignal and container

### ISSUE THREAD

**Issue by chenliu1993** [moby/moby#40821] opened 2020-04-15 23:37 UTC
**Description**

hi experts, I found that there is a STOPSIGNAL field in Dockerfile, and a --stop-signal in docker run command. I noticed that this is added because some container's pid 1 process uses such process as their kill signal. 
I found this feature is added in https://github.com/moby/moby/pull/15307/commits.
For example. httpd container points SIGWINCH as its stop signal in Dockerfile, and once pid 1 process recieves SIGWINCH then it will gracefully terminate itself.
But I got confused SIGWINCH is used to resize the terminal, when docker uses -t, there must be a resizepty request sent to the pid 1 process, that means there is a SIGWINCH signal sent to the pid 1 process. if in this way, httpd will exit. But actually httpd successfully run. Why this happens?
I think may be some parts of my understanding of resize pty or stop siganl in docker is wrong. 
What is the wrong part?
Thank you.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2020-04-16 12:33
How is your `httpd` process started? If it's running as PID1, then it's not running as a child-process of a shell, so I don't think `-t` will send `SIGWINCH` to the `httpd` process.

The `--stop-signal` is only used when docker kills the container; instead of the default signal (`SIGTERM`), it will send `SIGWINCH`. Then, if the process does not terminate after (by default) 10 seconds, docker will forcibly kill the container (`SIGKILL`) to terminate it.

**Comment by thaJeztah** [comment] 2020-04-16 12:34
Also please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-04-16 12:34 UTC
Labels: kind/question

**Comment by chenliu1993** [comment] 2020-04-17 01:47
Thank you for the reminding and explanation here.

I have also posted a issue in Docker Forum. the httpd is running as PID 1 in container but not PID1 in host.

Actually I am using libcontainer to start a container. 
And I could find this is the part which sends the SIGWINCH to the process.
```
unix.IoctlSetWinsize(int(proc.TermMaster.Fd()), unix.TIOCSWINSZ, winsize);
```
the `proc` here is the actual process which is httpd.

Each time I start the httpd with terminal, it quits on receciving a SIGWINCH since with terminal a resize pty request will be sent. But docker doesn't have this problem. That's the reason why I am confused.

**Comment by chenliu1993** [comment] 2020-04-17 10:20
https://github.com/docker-library/httpd/issues/9 this may solve my problem. So thank you.
