### ISSUE TITLE
NoSuchFileException issues when using process isolation

### ISSUE THREAD

**Issue by Barsonax** [moby/moby#40351] opened 2020-01-07 08:39 UTC
We are using docker to dockerize our sitecore environment. I have noticed that when I use process isolation that we get a NoSuchFileException in solr when rebuilding the index (to be more precise at the end of the rebuild). This does not happen when we use hyper v isolation which makes me suspect this is a bug that is somehow related to docker itself.

**Steps to reproduce the issue:**
I haven't be able to reproduce this outside of sitecore. The steps to reproduce this in sitecore can be found in this issue: https://github.com/Sitecore/docker-images/issues/182. Any help on how to reproduce this outside of sitecore would be appreciated.

**Describe the results you received:**
A java.nio.file.NoSuchFileException

**Describe the results you expected:**
No exception

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**
```
Client:
 Debug Mode: false

Server:
 Containers: 26
  Running: 0
  Paused: 0
  Stopped: 26
 Images: 106
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.535)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.9GiB
 Name: RICKAVIVA-LAPTOP
 ID: FG5Z:IV46:GB2A:4NK3:R5P3:PVLM:BNSD:5WXS:ILKZ:RXSZ:LMPO:SGMX
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 27
  System Time: 2020-01-07T09:36:46.7323022+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment] 2020-01-07 10:06
What base-image are you using? When using process isolation on Windows, the base-image should match the kernel version of the host (because the Windows kernel does not have a stable API)

**Comment by Barsonax** [comment] 2020-01-07 10:11
Iam using a 1903 image atm. 

> When using process isolation on Windows, the base-image should match the kernel version of the host (because the Windows kernel does not have a stable API)

Since 1909 (which is the windows version iam using) this is no longer the case and it should be possible for instance to run a 1903 image (but not older though) on 1909. However if it turns out this is causing it then it might not be a bug in docker but in windows.

**Comment by thaJeztah** [comment] 2020-01-07 10:15
Yes, (for what I've been told) it should be largely possible to do that, but perhaps there are still corner-cases.

I'm not on Windows myself, but perhaps @StefanScherer @simonferquel would be able to tell

**Comment by StefanScherer** [comment] 2020-01-07 11:10
Correct, process isolation seems to work for the 1903 images on a 1909 windows 10 host. The official compatibility tables don't show this yet (https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-1909%2Cwindows-10-1909).
I've looked into the other issue description, tested a bit with docker-compose and simple container images mounting folders. It's hard to tell where the problem is, but my guess if it's really not an application problem then it's something in windows itself.

@Barsonax Maybe you can investigate a bit more with sysinternals process monitor to see what happens in the containerized java process. With process isolation you can use process monitor on the host as described here: http://stefanscherer.github.io/find-dependencies-in-windows-containers/

**Comment by Barsonax** [comment] 2020-01-27 08:08
Excuses for the late reaction (vacation and other stuff). I will try to investigate a bit with the process monitor @StefanScherer

**Comment by Barsonax** [comment] 2020-01-27 08:45
Iam unable to reproduce this anymore. My guess is that Microsoft found the bug already and patched it recently.

**Comment by thaJeztah** [comment] 2020-01-27 12:25
Thanks for the update, @Barsonax. Let me close this one for now, but feel free to continue the conversation (or if you are able to reproduce again)

**Closed by thaJeztah** 2020-01-27 12:25 UTC
Labels: area/kernel, platform/windows, status/more-info-needed, version/19.03

**Comment by perosb** [comment] 2021-01-15 12:14
We seeing this on different configurations.
Win 2004/2009 also tried java 15.

For an other developer on win 2004 it doesn't happen.


We're would MS have fixed this issue?

**Comment by perosb** [comment] 2021-01-19 14:07
We are actually also getting this for a different application running dotnet core 5 "dotnet watch -p project.csproj" so not just java.
