### ISSUE TITLE
Moby won't pull from docker Hub

### ISSUE THREAD

**Issue by LarsBoosBechtle** [moby/moby#38761] opened 2019-02-20 09:40 UTC
Hi.
I can't pull with `moby` and with `docker pull` natively the sources from docker/desktop-host-tools.
It says that i can't access them.
I tried it with `docker login && docker pull docker/desktop-host-tools:current` but i didn't work.
Have you a hint for me?

I work with Windows 10, Docker for Windows, Go, Moby, Git, Linuxkit and tried the tut https://tippexs.github.io/docker/tutorial/2017/05/19/docker-mlkit-windows-setup.html .
I want to build a new docker host image with newer kernel due to some issues i'll have on other machines.
For this reason i took the linuxkit.yml from the docker-for-win.iso as template.

Example:
> C:\docker-desktop>docker login
Authenticating with existing credentials...
Login Succeeded

> C:\docker-desktop>moby build -format tar linuxkit.yml
Extract kernel image: linuxkit/kernel:4.19.20
Add init containers:
Process init image: linuxkit/init:3f1e5c32d6ca9e83a7ea7ad9854da2032971a83f
Process init image: linuxkit/runc:v0.5
Process init image: linuxkit/containerd:v0.5
Process init image: linuxkit/ca-certificates:v0.5
Process init image: linuxkit/getty:v0.5
Process init image: linuxkit/memlogd:ba4fcf55c35a3833546a1e39125bf0fa940327b0
Process init image: docker/desktop-host-tools:current
Pull image: docker/desktop-host-tools:current
[31mFATA[0m[0005] Failed to build init tarball from docker/desktop-host-tools:current: Could not pull image docker/desktop-host-tools:current: Error response from daemon: pull access denied for docker/desktop-host-tools, repository does not exist or may require 'docker login'

**Comment by thaJeztah** [comment] 2019-02-20 09:52
That image is not a public image, so you won't be able to pull it, that's why it's producing that error. I'm not exactly sure what it contains, but those may be the closed-source parts of Docker Desktop.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2019-02-20 09:52 UTC
Labels: area/distribution, platform/desktop
