### ISSUE TITLE
Docker vesion 2.2.0.4 plz help me Nat ping ip 172.18.x.x

### ISSUE THREAD

**Issue by huylong** [moby/moby#40696] opened 2020-03-15 13:40 UTC
Window 10 pro
docker Docker vesion 2.2.0.4

I use route /P add 172.0.0.0 MASK 255.0.0.0 10.0.75.2 with my computer but it not working when i use cmd ping 172.18.x.x time out. PLZ help me fix

**Comment by thaJeztah** [comment] 2020-03-17 20:17
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-03-17 20:17 UTC
