### ISSUE TITLE
Adding files during build fails when deduplication is used

### ISSUE THREAD

**Issue by Rainmaker52** [moby/moby#37026] opened 2018-05-09 20:13 UTC
Reporting after https://github.com/docker/for-win/issues/2016 got closed.

**Description**

Adding files to an image using an ADD directive in the Dockerfile, fails when those files are located on a deduplicated volume.

**Steps to reproduce the issue:**

From powershell:
  1. 
```
PS D:\> Copy-Item -Recurse C:\Windows\servicing D:\Temp\
PS D:\> Copy-Item -Recurse C:\Windows\servicing D:\Temp\dedupme
PS D:\> Set-Content -Path D:\Temp\Dockerfile -Value @"
>> FROM microsoft/windowsservercore
>> ADD . \TempTest
>> "@
PS D:\> cd \temp
PS D:\temp> docker build .
Sending build context to Docker daemon  58.37kB
Step 1/2 : FROM microsoft/windowsservercore
 ---> ad6116672030
Step 2/2 : ADD . \TempTest
 ---> 78784d9f34f7
Successfully built 78784d9f34f7

```
  2.  Now, add reparse points to the files and try again.
```
PS D:\temp> Start-DedupJob -Type Optimization -Volume D: -Wait

Type               ScheduleType       StartTime              Progress   State                  Volume
----               ------------       ---------              --------   -----                  ------
Optimization       Manual                                    100 %      Completed              D:


PS D:\temp> docker build .
ERRO[0000] Can't add file \\?\D:\temp\dedupme\CbsApi.dll to tar: readlink \\?\D:\temp\dedupme\CbsApi.dll: The system cannot find the file specified.
ERRO[0000] Can't add file \\?\D:\temp\dedupme\CbsMsg.dll to tar: readlink \\?\D:\temp\dedupme\CbsMsg.dll: The system cannot find the file specified.
ERRO[0001] Can't add file \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~en-US~10.0.17134.1.cat to tar: readlink \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~en-US~10.0.17134.1.cat: The system cannot find the file specified.
ERRO[0001] Can't add file \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~~10.0.17134.1.cat to tar: readlink \\?\D:\temp\dedupme\Packages\Microsoft-OneCore-Common-DriverClasses-Core-Package~31bf3856ad364e35~amd64~~10.0.17134.1.cat: The system cannot find the file specified.

```

**Describe the results you received:**
Most of the files (presumably, each file that has been "optimized" by the deduplication process) reports an error such as 
> ERRO[0013] Can't add file \\?\D:\temp\servicing\Packages\Package_220_for_KB4135051~31bf3856ad364e35~amd64~~10.0.1.1.cat to tar: readlink \\?\D:\temp\servicing\Packages\Package_220_for_KB4135051~31bf3856ad364e35~amd64~~10.0.1.1.cat: The system cannot find the file specified.

**Describe the results you expected:**
I would expect the files to be added, regardless of whether or not the underlying volume is deduplicated.

**Output of `docker version`:**
```
Docker version 18.03.1-ce, build 9ee9f40
```

**Output of `docker info`:**
```
Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 32
Server Version: 18.03.1-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88GiB
Name: hp840
ID: BOBD:JIFO:XSFI:XYDK:727W:AUOX:DBLN:KIG6:6VTN:E3P2:6F3L:D4L6
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 21
 System Time: 2018-05-09T22:13:09.5594224+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2018-05-10 00:54
ping @johnstep PTAL - could be related to recent changes in hcsshim

**Comment by jhowardmsft** [comment] 2018-05-10 02:01
Has this ever worked? I'm very doubtful it has anything to do with the recent changes @thaJeztah is referring to.

**Comment by thaJeztah** [comment] 2018-05-10 08:09
> I'm very doubtful it has anything to do with the recent changes

@salah-khan mentioned that, but yes, definitely possible this was never supported

> How recent are those recent changes?

They're in the 18.03.1 patch release, but perhaps best to wait for confirmation if it's actually supported, or something that has to be implemented

**Comment by Rainmaker52** [comment] 2018-06-18 01:15
It's been a while since I updated this. I just wanted to add to this that I've had a similar problem with Bash On Linux On Windows (or the Windows Subsystem for Linux), which didn't show executable files that have been deduplicated.

See https://github.com/Microsoft/WSL/issues/2439.

Unfortunately, I'm not sure what exactly was changed there to make it work.

**Comment by johnstep** [comment] 2018-06-25 21:11
We expect the problem is that the dedup.sys filter driver is unable to resolve the reparse points to the file chunks within the silo (container) context, possibly because it's attached to the silo. We are looking into it and will update once we know more.

**Comment by salah-khan** [comment] 2018-06-29 04:56
This error is occurring because deduplication uses a new reparse tag and Readlink iin syscall_windows.go doesn't now hoe to interpret it.

The code calls through to the default tag which returns the error.
	switch rdb.ReparseTag {
	case IO_REPARSE_TAG_SYMLINK:
		data := (*symbolicLinkReparseBuffer)(unsafe.Pointer(&rdb.reparseBuffer))
		p := (*[0xffff]uint16)(unsafe.Pointer(&data.PathBuffer[0]))
		s = UTF16ToString(p[data.SubstituteNameOffset/2 : (data.SubstituteNameOffset+data.SubstituteNameLength)/2])
		if data.Flags&_SYMLINK_FLAG_RELATIVE == 0 {
			if len(s) >= 4 && s[:4] == `\??\` {
				s = s[4:]
				switch {
				case len(s) >= 2 && s[1] == ':': // \??\C:\foo\bar
					// do nothing
				case len(s) >= 4 && s[:4] == `UNC\`: // \??\UNC\foo\bar
					s = `\\` + s[4:]
				default:
					// unexpected; do nothing
				}
			} else {
				// unexpected; do nothing
			}
		}
	case _IO_REPARSE_TAG_MOUNT_POINT:
		data := (*mountPointReparseBuffer)(unsafe.Pointer(&rdb.reparseBuffer))
		p := (*[0xffff]uint16)(unsafe.Pointer(&data.PathBuffer[0]))
		s = UTF16ToString(p[data.SubstituteNameOffset/2 : (data.SubstituteNameOffset+data.SubstituteNameLength)/2])
		if len(s) >= 4 && s[:4] == `\??\` { // \??\C:\foo\bar
			s = s[4:]
		} else {
			// unexpected; do nothing
		}
	default:
		// the path is not a symlink or junction but another type of reparse
		// point
		return -1, ENOENT
	}

@jhowardmsft, who would be best to look at this?

**Comment by salah-khan** [comment] 2018-07-18 21:11
@thaJeztah  I have a working fix for this. I'm in the process of creating the PR etc.

**Comment by thaJeztah** [comment] 2018-07-18 23:11
sounds great, thanks!

**Comment by kolyshkin** [comment] 2018-10-08 20:39
OK, the underlying issue (treating all reparse points as symlinks) is fixed in Go 1.11 (https://go-review.googlesource.com/86556 aka golang/go@e83601b, fixing golang/go#22579). So, it should be fixed in latest moby/moby as well as in docker-ce 18.09.

@Rainmaker52 is it possible for you to try docker-ce 18.09 to check if it fixes the issue? It should be available from https://store.docker.com/editions/community/docker-ce-desktop-windows, **EDGE channel**. Make sure to verify the version (it should say 18.09 and go 1.11)

**Comment by kolyshkin** [comment] 2018-10-08 20:41
@thaJeztah if we want to fix it for earlier releases, I see two ways:
1. Backport https://github.com/golang/go/commit/e83601b to go version used for builds
2. Backport everything that allows go 1.11 to be used, and switch to it.

Neither way seems easy to me, but the first one _appears_ easier.

**Comment by kolyshkin** [comment] 2018-10-09 00:37
> @Rainmaker52 is it possible for you to try docker-ce 18.09 to check if it fixes the issue?

Please disregard -- 18.09 still uses Go 1.10.4 and so the bug is not fixed there.

**Comment by cmorty** [comment] 2019-07-26 05:57
As Golang is now at 1.12 (https://docs.docker.com/engine/release-notes/#19030 ) this should be fixed, right? Anyone tested this?

**Comment by thaJeztah** [comment] 2019-08-27 22:45
@ameyag could you check if this is resolved?

**Comment by thaJeztah** [comment] 2019-08-28 07:59
Thanks! I'll go ahead and close this issue 👍

**Closed by thaJeztah** 2019-08-28 07:59 UTC
Labels: area/builder, platform/windows
