### ISSUE TITLE
Script is not receiving SIGTERM signal

### ISSUE THREAD

**Issue by trajano** [moby/moby#33319] opened 2017-05-21 17:50 UTC
Similar to https://github.com/moby/moby/issues/2436 but trying to do it on a Windows 10 Host which is running Hyper-V.

In my DockerFile I have

    CMD ["/config/startServer.sh"]

The key lines in startServer.sh

    #!/bin/bash

    unregisterHost() {
        echo "unregistering"
        /opt/ibm/wlp/bin/collective unregisterHost $(hostname) # ... other params
        exit
    }
    trap unregisterHost TERM
    /usr/sbin/sshd -D

I also tried with

    exec /usr/sbin/sshd -D

I did a `docker stop <container>` while I was looking at `docker logs -f <container>` and didn't see `unregistering`.  It also didn't unregister the server from the WebSphere collective.

Running the command using `docker exec <anothercontainer> unregisterHost <dropped container>` will properly deregister.  So I am sure it's not the command itself.

Is it because I am on Widnows 10 Hyper-V?

**Comment by thaJeztah** [comment] 2017-05-22 12:52
Processes running as PID1 usually behave different than when running _not_ as PID1. Many processes ignore `SIGTERM` / `SIGKILL` when running as PID1, also see https://docs.docker.com/engine/reference/run/#foreground

> **Note**: A process running as PID 1 inside a container is treated specially by Linux: it ignores any signal with the default action. So, the process will not terminate on `SIGINT` or `SIGTERM` unless it is coded to do so.

This behaviour is thus expected. You _can_ work around this, by using the `--init` option that was introduced in docker 1.13 / 17.03 (https://github.com/moby/moby/pull/26061), which adds a tini init-process in the container, making the script itself no longer running as `PID1`

I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-05-22 12:52 UTC
Labels: area/builder

**Comment by trajano** [comment] 2017-05-22 12:54
So what is the equivalent of this in docker-compose?

**Comment by thaJeztah** [comment] 2017-05-22 12:59
I don't think it's supported yet in the `docker-compose` file format; could you open an issue for that here; https://github.com/docker/cli/issues ?

**Comment by trajano** [comment] 2017-05-22 13:00
There's a note in https://docs.docker.com/engine/reference/builder/#entrypoint which is one of the things that gave me the idea on trapping `SIGTERM`

>The shell form prevents any CMD or run command line arguments from being used, but has the disadvantage that your ENTRYPOINT will be started as a subcommand of /bin/sh -c, which does not pass signals. This means that the executable will not be the container’s PID 1 - and will not receive Unix signals - so your executable will not receive a SIGTERM from docker stop <container>.

Is that out of date then so `docker stop` will no longer send a `SIGTERM` no matter what?

**Comment by thaJeztah** [comment] 2017-05-22 13:26
No, it's not outdated, because if you run another process that _does_ handle SIGTERM/SIGKILL, it won't receive it, because a shell doesn't forward those signals.

In you're case, the shell / script _does_ receive the signal, but decides to ignore it because it's running as `PID1`. Same result, but different cause

**Comment by trajano** [comment] 2017-05-22 15:12
So it seems no matter what SIGTERM will not be sent, there's no `--init` support but  even when I added tini manually

```
ENV TINI_VERSION v0.14.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
```

And verify that it is running

```
D:\p\jee\src\docker>docker exec 0808edb2f143  ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0   4368   640 ?        Ss   15:04   0:00 /tini -- /config/startServer.sh
root          7  0.0  0.1  65520  6192 ?        S    15:05   0:00 /usr/sbin/sshd -D
root         47 16.5 11.7 3802248 472456 ?      Sl   15:05   0:55 /opt/ibm/java/jre/bin/java -javaagent:/opt/ibm/wlp/bin/tools/ws-javaagent.jar -Djava.awt.headless=true -Xmx1024m -jar /opt/ibm/wlp/bin/tools/ws-server.jar defaultServer
root        319  0.0  0.0  34424  2816 ?        Rs   15:10   0:00 ps aux
```
I still do not see the `echo` message (the above was with `sshd -D` running in `exec) when I do a `docker stop`

**Comment by trajano** [comment] 2017-05-22 16:46
Anyway I found out a way of doing all of this now. I'll write a post about it so people can try to set up a "clean shutdown" script.

**Comment by woky** [comment] 2019-01-27 12:20
@thaJeztah How come shell doesn't forward SIGTERM when you explicitly `trap` for it? I'm not intending to uncover what's been successfully swept under the rug. I'm genuinely curious.

**Comment by woky** [comment] 2019-01-27 12:38
For those who stumble here seeking true enlightenment:

From: `zshoptions(1)`
```
       TRAPS_ASYNC
              While  waiting for a program to exit, handle signals and run traps immediately.  Otherwise the trap is run after a child process has exited.  Note this does not affect the
              point at which traps are run for any case other than when the shell is waiting for a child process.
```

From: `bash(1)`
```
      If bash is waiting for a command to complete and receives a signal for which a trap has been set, the trap will not be executed until the command completes.  When bash is waiting
       for  an  asynchronous  command via the wait builtin, the reception of a signal for which a trap has been set will cause the wait builtin to return immediately with an exit status
       greater than 128, immediately after which the trap is executed.
```

The solution is to let shell commands on background via `&` and `wait` them, e.g.:
```
tail -f /var/log/foo.log &
wait $!
```
Then, shell will execute traps.
