### ISSUE TITLE
Slow container API calls when exposing large port range

### ISSUE THREAD

**Issue by shauser** [moby/moby#41834] opened 2020-12-22 12:42 UTC
**Description**
If a container which exposes a large range of ports has been created, the processing times for `docker ps` and `docker inspect` (only on this image) becomes unreasonably slow. This has a compounding effect if `docker-compose` is used, since it currently lists and inspects all containers for calls such as `docker-compose ps`.

**Steps to reproduce the issue:**
1. Create image with `EXPOSE 1025-65535`
2. `docker run` 5 instances
3. Call `docker ps` / `GET /v1.40/containers/json`

**Describe the results you received:**
API call takes ~0.5s per container.

**Describe the results you expected:**
API call should not have a notable performance impact for exposed ports. If this is expected behavior, the documentation for EXPOSE should contain a note the impact of using large port ranges.

**Output of `docker version`:**

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.1
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 334
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.61GiB
 Name: dev-vm
 ID: 2ASE:I6ZQ:XYBC:TU6Z:THAF:F6GN:LUYK:YFQC:XWFB:4XSC:4AUQ:WZVU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Report from a system running on VMware Workstation, but the problem has been reproduced on a bare metal system.

**Comment by thaJeztah** [comment] 2020-12-22 13:11
Thanks for reporting; this is a known issue, and looks like a duplicate of https://github.com/moby/moby/issues/11185. Depending on your use-case, disabling the userland-proxy may give some improvements, or alternatively use `host` network mode (but there are some security implications when using host-mode networking).

Let me close this as a duplicate of https://github.com/moby/moby/issues/11185, to prevent the discussion from diverging, but feel free to continue the conversation after I closed

**Closed by thaJeztah** 2020-12-22 13:11 UTC
Labels: area/networking, area/performance, kind/performance, version/19.03
