### ISSUE TITLE
Not all partial log lines are flagged as Partial

### ISSUE THREAD

**Issue by someword** [moby/moby#32970] opened 2017-05-02 18:01 UTC
**Description**

It is my understanding that when a container log message get's split into pieces each piece will get an bool attribute called `Partial` set.   Here is where that happens https://github.com/moby/moby/blob/dc20f2abd494e880c25d9e8669a10ead90cdbaf5/daemon/logger/copier.go#L98-L104

In my experience I don't see all of the message pieces get the `Partial` attribute.    It may just be that the last piece is not getting the attribute.

**Steps to reproduce the issue:**
I'm using the journald log driver and asking for the logs in JSON format where I should see the journald label `CONTAINER_PARTIAL_MESSAGE` on the partial messages.    The journald labeling is happening here https://github.com/moby/moby/blob/5eca7f7c5d7678f6548cd7d90199d67ce98d4c98/daemon/logger/journald/journald.go#L110-L112.

1.  Run a container that creates a log line over 16K
docker run -it perl perl -e 'print "START" ;print "X" x 24000; print "END\n"'
2.  Find the container id and ask journald for the container logs which include the label `CONTAINER_PARTIAL_MESSAGE` 
journalctl CONTAINER_ID=28b940872ade -o json --no-pager |jq 'select(.CONTAINER_PARTIAL_MESSAGE == "true")'

In my situation only the first piece has the `Partial` attribute.

**Describe the results you received:**
Only the first message piece has the `Partial` attribute.

**Describe the results you expected:**
I expect each log piece that comprises a single log message to be labeled as `Partial`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   092cba3
 Built:        Wed Mar  1 23:26:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   092cba3
 Built:        Wed Mar  1 23:26:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 60
 Running: 54
 Paused: 0
 Stopped: 6
Images: 21
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.1-coreos
Operating System: Container Linux by CoreOS 1339.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
Name: ip-10-21-2-118.ec2.internal
ID: ZC3O:SR2K:JQEQ:TFII:UBD3:4MCL:BQHU:NX72:DHB2:HI6M:5BAE:WO32
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We are running CoreOS on AWS instances.  Systemd and OS versions below.

```
core@ip-10-21-2-118 ~ $ systemctl --version
systemd 231
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
core@ip-10-21-2-118 ~ $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1339.0.0
VERSION_ID=1339.0.0
BUILD_ID=2017-03-01-2346
PRETTY_NAME="Container Linux by CoreOS 1339.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by thaJeztah** [comment] 2017-05-02 21:09
IIUC; you have a message that's (e.g.) 24K. The first 16K is written to a log entry with the "partial" label set, but the second isn't? I think that's by design; as the label indicates that the message should be combined with the next message. However the _second_ message should not be combined with the next (third) message.

**Comment by someword** [comment] 2017-05-02 21:30
@thaJeztah 
Maybe I am misunderstanding the intent.    This came up in the context of a discussion with @cpuguy83  here https://github.com/moby/moby/pull/32947#issuecomment-298697886

I had incorrectly stated that the `Partial` attribute only get's set to the first log piece and @cpuguy83 thought it should be applied to all pieces of a given message.    In further testing with log lines 56K in size I see that it's only the last piece which does not get the `Partial` attribute.

So if this is intent then please close and sorry for the confusion!

**Comment by thaJeztah** [comment] 2017-05-02 21:44
Ah, yes, I understand the confusion 👍 

Yes, all parts are marked as "partial" (as an indication they need to be combined with the "next" log entry). The last entry does not have the "partial" label; it basically marks the "end" of the message.

Let me close the issue, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-05-02 21:44 UTC
Labels: area/logging, version/1.13
