### ISSUE TITLE
Failed to fetch https://download.docker.com/linux/ubuntu/dists/\/xenial/binary-amd64/Packages  404  

### ISSUE THREAD

**Issue by deviant-studio** [moby/moby#36902] opened 2018-04-19 14:12 UTC
Hi! I'm trying to install Docker on Ubuntu 16.04 with this script:
`curl -fsSL https://test.docker.com | sh`

And this error have occurred:
```
# Executing docker install script, commit: 92d5116
+ sudo -E sh -c apt-get update -qq >/dev/null
W: The repository 'https://download.docker.com/linux/ubuntu \ Release' does not have a Release file.
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/\/xenial/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by thaJeztah** [comment] 2018-04-19 17:09
Looks like you may have copied a backslash when adding the package repository; `\/` (https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository)

check the package repository configuration (`/etc/apt/sources.list`)

It should contain a line that looks look something like;

```
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
```
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-04-19 17:09 UTC

**Comment by thaJeztah** [comment] 2018-04-19 17:17
Actually, the package repository is now configured in a separate file, so if you also find an entry for the docker package repository in `/etc/apt/sources.list`, you should remove that entry.

The file that contains the configuration can be found in `/etc/apt/sources.list.d/docker.list`, and should look (for the "test" channel);

```
cat /etc/apt/sources.list.d/docker.list 
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial test
```

**Comment by deviant-studio** [comment] 2018-04-19 18:58
i just recreated my ec2 instance from scratch and the same script executed successfully. i have no idea what it was.

**Comment by SheilenManna** [comment] 2019-10-18 19:40
TY @thaJeztah :) :) Removing the entry helped. Ty

**Comment by caroso1222** [comment] 2020-07-13 13:18
Not sure if this is relevant but I landed here looking for this error

```
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Fixed it by running this command, as proposed [here](https://stackoverflow.com/questions/41133455/docker-repository-does-not-have-a-release-file-on-running-apt-get-update-on-ubun#comment99414198_43639310).

```
sudo rm /etc/apt/sources.list.d/docker*
```

That file contained the entry `deb [arch=amd64] ...`.
