### ISSUE TITLE
Linking to a container by name which was renamed before fails.

### ISSUE THREAD

**Issue by retrospectacus** [moby/moby#31392] opened 2017-02-27 19:35 UTC
**Description**

If you have two linked containers, rename the target container and bring up a replacement with the old name, then delete and recreate the source container linking to the new target, no link is created.

In my use case, the target container failed. I wanted to keep it around for investigation but also to get back up and running ASAP. So I renamed it and started a replacement, but then replacing my dependent containers, they would not link to the new target.

**Steps to reproduce the issue:**
For the example I used postgres and redis images. However I believe any image will work. In my environment A0 is my application and B0 is nginx.
Create two named containers A0 & B0 with a link from B0 to A0. (hopefully the names ease understanding; unfortunately names must be >1 character)
1. `docker run -d --name=A0 postgres`
2. `docker run -d --name=B0 --link=A0 redis`
You can see in `docker inspect B0` the link: `"/A0:/B0/A0"`
Rename container A0.
3. `docker stop A0`
4. `docker rename A0 A1`
You can inspect B0 again and the link there has been renamed: `"/A1:/B0/A0"`
Start a replacement container A0
5. `docker run -d --name=A0 postgres`
Delete and re-create B0 to point to the new A0.
6. `docker rm -f B0`
7. `docker run -d --name=B0 --link=A0 redis`
Now inspect again B0 for links.

**Describe the results you received:**
```
            "Links": null,
```
Also verified inside the container that the link is not present - "host not found" error, etc.

**Describe the results you expected:**
```
            "Links": [
                "/A0:/B0/A0"
            ],
```

**Additional information you deem important (e.g. issue happens only occasionally):**
- This will occur if B0 existed and was linked to A0 *at any point before* the rename, and the replacement B0 is also named B0. I.e. you can run step 6 directly before step 3 and the bug will still occur.
- It will not occur if the replacement B0 is given a different name.
- Unable to reproduce on docker version 1.9.1 - link is created as expected.

**Output of `docker version`:**

```
Docker version 1.13.0, build 49bf474
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: ip-172-31-6-208
ID: DFBJ:SEF4:QF2O:3RZM:GQ5L:TYEF:PQGB:XNLN:6DZA:R55T:FUCK:UZXZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2 instance (not using ECS)

**Comment by ChenMin46** [comment] 2017-07-31 06:35
This also happens in 17.05.0-ce

**Comment by ripcurld0** [comment] 2017-07-31 07:34
I think it's a duplicate of https://github.com/moby/moby/issues/34307

**Comment by ripcurld0** [comment] 2017-07-31 14:14
OK, I have investigate this and in a second thought it's not related to #34307. It has to do with the [memDB](https://github.com/moby/moby/blob/master/container/view.go#L190).

@yastij would you like to take that?

**Comment by ripcurld0** [comment] 2017-08-01 10:39
OK, I am taking this since I have done some work.

**Closed** 2017-09-26 16:41 UTC
Labels: area/daemon, exp/beginner, kind/bug, status/claimed
