### ISSUE TITLE
SLUB: Unable to allocate memory on node -1 (gfp=0x0)

### ISSUE THREAD

**Issue by xingxing9688** [moby/moby#35545] opened 2017-11-20 01:35 UTC
docker --version    1.12.6  
centos 7.2  3.10.0-514.el7.x86_64

[8642044.803394] unregister_netdevice: waiting for lo to become free. Usage count = 1
[8643296.448116] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643296.448122]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643296.448125]   node 0: slabs: 663, objs: 20964, free: 0
[8643296.448955] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643296.448958]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643296.448959]   node 0: slabs: 663, objs: 20964, free: 0
[8643296.572765] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643296.572770]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643296.572772]   node 0: slabs: 664, objs: 20996, free: 0
[8643296.983699] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643296.983704]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643296.983706]   node 0: slabs: 666, objs: 21032, free: 0
[8643296.991188] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643296.991193]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643296.991195]   node 0: slabs: 667, objs: 21036, free: 0
[8643297.914971] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643297.914975]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643297.914977]   node 0: slabs: 668, objs: 21068, free: 0
[8643298.067295] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643298.067301]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643298.067302]   node 0: slabs: 670, objs: 21104, free: 0
[8643299.719059] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643299.719064]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643299.719066]   node 0: slabs: 676, objs: 21296, free: 0
[8643299.814665] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643299.814670]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643299.814672]   node 0: slabs: 677, objs: 21328, free: 0
[8643306.410617] ___slab_alloc: 1 callbacks suppressed
[8643306.410621] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643306.410623]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643306.410625]   node 0: slabs: 695, objs: 21792, free: 0
[8643308.914526] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643308.914530]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643308.914532]   node 0: slabs: 1145, objs: 73280, free: 0
[8643308.914539] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643308.914540]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643308.914541]   node 0: slabs: 1145, objs: 73280, free: 0
[8643308.914543] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643308.914544]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643308.914546]   node 0: slabs: 1145, objs: 73280, free: 0
[8643308.915498] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643308.915501]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643308.915503]   node 0: slabs: 1145, objs: 73280, free: 0
[8643308.915506] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643308.915508]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643308.915510]   node 0: slabs: 1145, objs: 73280, free: 0
[8643309.907108] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643309.907114]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643309.907116]   node 0: slabs: 1147, objs: 73408, free: 0
[8643309.907122] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643309.907124]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643309.907125]   node 0: slabs: 1147, objs: 73408, free: 0
[8643309.907130] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643309.907132]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643309.907133]   node 0: slabs: 1147, objs: 73408, free: 0
[8643309.917466] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643309.917470]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643309.917472]   node 0: slabs: 1147, objs: 73408, free: 0
[8643320.817919] ___slab_alloc: 44 callbacks suppressed
[8643320.817924] SLUB: Unable to allocate memory on node -1 (gfp=0x8020)
[8643320.817938]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643320.817943]   node 0: slabs: 1229, objs: 78656, free: 0
[8643320.817949] SLUB: Unable to allocate memory on node -1 (gfp=0x8020)
[8643320.817951]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643320.817952]   node 0: slabs: 1229, objs: 78656, free: 0
[8643320.818655] SLUB: Unable to allocate memory on node -1 (gfp=0x8020)
[8643320.818658]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643320.818659]   node 0: slabs: 1229, objs: 78656, free: 0
[8643320.818667] SLUB: Unable to allocate memory on node -1 (gfp=0x8020)
[8643320.818668]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643320.818669]   node 0: slabs: 1229, objs: 78656, free: 0
[8643320.818671] SLUB: Unable to allocate memory on node -1 (gfp=0x8020)
[8643320.818673]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643320.818674]   node 0: slabs: 1229, objs: 78656, free: 0
[8643329.455130] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[8643329.455135]   cache: kmalloc-1024(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 1024, buffer size: 1024, default order: 3, min order: 0
[8643329.455137]   node 0: slabs: 798, objs: 24780, free: 0
[8643346.280827] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643346.280832]   cache: kmalloc-256(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 256, buffer size: 256, default order: 1, min order: 0
[8643346.280834]   node 0: slabs: 2112, objs: 67344, free: 0
[8643347.466141] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.466146]   cache: kmalloc-256(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 256, buffer size: 256, default order: 1, min order: 0
[8643347.466148]   node 0: slabs: 2112, objs: 67328, free: 0
[8643347.479637] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.479642]   cache: kmalloc-256(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 256, buffer size: 256, default order: 1, min order: 0
[8643347.479644]   node 0: slabs: 2115, objs: 67424, free: 0
[8643347.594132] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.594136]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643347.594138]   node 0: slabs: 1312, objs: 83968, free: 0
[8643347.594147] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.594148]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643347.594149]   node 0: slabs: 1312, objs: 83968, free: 0
[8643347.594152] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.594154]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643347.594155]   node 0: slabs: 1312, objs: 83968, free: 0
[8643347.594157] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.594159]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643347.594160]   node 0: slabs: 1312, objs: 83968, free: 0
[8643347.594163] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.594172]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643347.594173]   node 0: slabs: 1312, objs: 83968, free: 0
[8643347.594176] SLUB: Unable to allocate memory on node -1 (gfp=0x0)
[8643347.594178]   cache: kmalloc-64(1793:c8edefa90517e21bc691deef20c17220af0f0ac69962cc51007d372e7dd40256), object size: 64, buffer size: 64, default order: 0, min order: 0
[8643347.594179]   node 0: slabs: 1312, objs: 83968, free: 0

**Comment by thaJeztah** [comment] 2017-11-21 21:19
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'm closing this issue, because there's no context to what you posted

**Closed by thaJeztah** 2017-11-21 21:19 UTC
