### ISSUE TITLE
Changing docker0 network with bip option: cannot set .0 as ending ip network address

### ISSUE THREAD

**Issue by Yivan** [moby/moby#40392] opened 2020-01-17 19:09 UTC
Hello,

We have computers where just installing docker set the default bridge network to 172.17.0.0/16 (the more of them) and on some others computers this network is set to 172.18.0.0/24.
Docker don't seems consistent on this (this was the exactly same installation process, using Vagrant deployment).
No problem, i think this is because of some internal mechanism.

The problem is we wanted to set 172.17.0.0/24 for all, so we have set in daemon.json :

```
"bip": "172.17.0.0/24"
```

**Docker cannot restart with this `"bip": "172.17.0.0/24"` setting.**
But if we set `"bip": "172.17.0.1/24"`, it works.

_For information, we tested on several computers having already the native 172.17.0.0/24 and they can't either, this is not a problem of adresse availability on the computer. The only other network on all computers is eth0 with a 10.xx.xx.xx network. So there is no network/ip overlap._

Question 1 please, the bug:
**Is it a bug that we cannot set `"bip": "172.17.0.0/24"` but only `"bip": "172.17.0.1/24"` ?**
As result we cannot have the 172.17.0.0 IP address if we use `bip` option (so only starting from 172.17.0.1). But native configuration have it.

Question 2 please, impact :
Is it a problem for docker or all will work ok with `172.17.0.1/24` instead `172.17.0.0/24` ?

Thanks a lot.

**Comment by cpuguy83** [comment] 2020-01-19 15:29
--bip sets the bridge IP and subnet.
Since .0 is not a valid /24 ip, it is rejected.
This is working as intended.

So yes, if you want the bridge to have .1 with a /24 subnet, you should use 17.17.0.1/24.

Closing since it does not look like an issue but feel free to comment.
Thanks!

**Comment by Yivan** [comment] 2020-01-19 17:29
@cpuguy83 Thanks a lot for your fast answer on this subject.

So if this is not a bug, how to achieve to configure the same configuration than default one please ?

A `docker network inspect bridge` on native installation without any customization give:
```
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
```

But if we force so it is fixed with `"bip": "172.17.0.0/16"` it don't work like i explained, and with `"bip": "172.17.0.1/16"` the command `docker network inspect bridge` return:

 ```
            "Config": [
                {
                    "Subnet": "172.17.0.1/16",
                    "Gateway": "172.17.0.1"
                }
            ]
```

So how to force "Subnet": "172.17.0.0/16" ? when using `bip` parameter ?

Thanks again.

**Comment by cpuguy83** [comment] 2020-02-10 22:41
You don't. This is most likely only a difference in presentation.
I'll re-open because this should be the same.

Ping @arkodg

**Closed** 2020-02-12 11:41 UTC
Labels: area/networking, kind/bug

**Comment by Yivan** [comment] 2020-02-12 13:06
Great thanks for the fix !
Best regards.
