### ISSUE TITLE
Docker service crash when firewall is stopped or started

### ISSUE THREAD

**Issue by alangaytan** [moby/moby#34939] opened 2017-09-22 12:54 UTC
I have two machines and I make a docker swarm cluster with them, then I created a service with 5 replicas to verify that the load balancer is working good but I noticed the firewall was blocking the two machines so I added the required ports:

```
firewall-cmd --zone=public --add-port=2377/tcp --permanent
firewall-cmd --zone=public --add-port=7946/tcp --permanent
firewall-cmd --zone=public --add-port=7946/udp --permanent
firewall-cmd --zone=public --add-port=4789/tcp --permanent
```

Everything is working good, my only doubt is when the firewall is stopped or started then docker stop working and I don't know why this happen?

Can someone explain me the behavior of this? Is it possible to avoid this behavior or this is a normal behavior?

Thanks in advance

**Comment by thaJeztah** [comment] 2017-09-22 16:05
Docker creates firewall rules when starting up, and when containers are created/removed (ports published). If another process removes those rules, docker is not aware of those rules being removed, therefore things may break.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-09-22 16:05 UTC
Labels: area/swarm

**Comment by alangaytan** [comment] 2017-09-22 22:20
ok thanks for the information, so as I understand this behavior is expected?

**Comment by thaJeztah** [comment] 2017-09-22 22:29
If "docker stop working" means; networking not working, then yes, that can be expected
