### ISSUE TITLE
Calling fork() exists container

### ISSUE THREAD

**Issue by l33** [moby/moby#20971] opened 2016-03-05 01:51 UTC
Output of `docker version`:

```
Docker version 1.8.2, build 0a8c2e3
```

Output of `docker info`:

```
Containers: 5
Images: 11
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: default
ID: OZRR:B36X:THQQ:BQYW:TNRH:KTSY:SBCK:SCTN:XQT3:BPJC:EWYO:KTU5
Debug mode (server): true
File Descriptors: 11
Goroutines: 18
System Time: 2016-03-05T01:44:18.165050564Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Physical Box running Debian Wheezy

List the steps to reproduce the issue:

```
$ docker run -ti --rm debian:wheezy su -
Unable to find image 'debian:wheezy' locally
wheezy: Pulling from library/debian

4d690fa98655: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:3319ebf616335a0e8aae3ea15a7a4a4f24ebb46a660c2c2567a68c83857a21ce
Status: Downloaded newer image for debian:wheezy
root@4f2cd03bcdae:~# perl -e 'if (fork){print "Hi...\n"; sleep 1}else{sleep 5;print "... bye!\n"}'
Hi...
root@4f2cd03bcdae:~# ... bye!
$
```

Describe the results you received:
Calling `fork()` in docker container will end the container as soon as the second part of the `fork()` exists.

Describe the results you expected:
Container should still be usable after calling fork.

Provide additional info you think is important:
This only happens when entering the container using `su`.

**Comment by thaJeztah** [comment] 2016-10-19 20:42
The script exits, so the main container's process is done. This is expected behavior, so closing

**Comment by l33** [comment] 2016-10-20 19:54
How does the example differ from simply calling `true` in the shell? Docker does not exit in that case. It also does not exit if it was called using `bash` instead of `su`. How does that make a difference? @thaJeztah , could you please explain?

**Comment by mlaventure** [comment] 2016-10-20 22:01
@l33 

Actually it's my fault, didn't read your example correctly when we were discussing it.

It seems to still occur on master, reopening.

**Comment by mlaventure** [comment] 2016-10-20 22:12
The issue seems to only occur when the entrypoint is `su`

**Comment by thaJeztah** [comment] 2016-10-20 23:03
@mlaventure is this one of the issues `gosu` resolves? https://github.com/tianon/gosu

**Comment by mlaventure** [comment] 2016-10-20 23:17
@thaJeztah using `gosu root:root bash -l` seems to indeed work properly

ping @tianon

**Comment by mlaventure** [comment] 2017-03-03 19:28
re-pinging @tianon 

Do you have any idea what's the root cause? Given that `gosu` seems to work, I'm hoping you do :angel:

**Comment by tianon** [comment] 2017-03-06 17:59
Hmm, I'd guess that it's something to do with `su` running as PID 1 -- it's probably waiting for `SIGCHLD` since in normal operation, it should only _ever_ get `SIGCHLD` from its direct child, but here it's getting `SIGCHLD` from the grandchild too.

Can you try running it again with `--init` and see if it still fails? (`docker run --init ... su -`)

**Comment by tianon** [comment] 2017-03-06 18:00
(That, or something _really_ weird with the TTY, but that seems a lot less likely.)

The reason `gosu` would work where `su` doesn't is that `gosu` doesn't stay resident -- when you do `gosu <someone> bash`, the only thing left running is `bash`. :+1:

**Comment by sam-thibault** [comment] 2023-11-10 12:30
This is an old issue.  I will close it as stale.

**Closed by sam-thibault** 2023-11-10 12:30 UTC
Labels: area/runtime, kind/bug

**Comment by l33** [comment] 2023-11-10 14:29
> Hmm, I'd guess that it's something to do with `su` running as PID 1 -- it's probably waiting for `SIGCHLD` since in normal operation, it should only _ever_ get `SIGCHLD` from its direct child, but here it's getting `SIGCHLD` from the grandchild too.
> 
> Can you try running it again with `--init` and see if it still fails? (`docker run --init ... su -`)

Yes, that worked. Newer versions of `su` starting from Debian Buster also work without `--init`.
