### ISSUE TITLE
Music stops when Docker commits on Ubuntu 14.04

### ISSUE THREAD

**Issue by aalexgabi** [moby/moby#8279] opened 2014-09-29 14:10 UTC
This is may sound weird, but something doesn't seem right.

Steps to reproduce:
1. Use Ubuntu 14.04
2. Use Google Chrome
3. Visit soundcloud.com
4. Play a song
5. Build a Docker image

Each time Docker commits music should stop. Same behavior with 1.0.1 and .1.2.0

**Comment by 2m** [comment] 2015-01-08 13:17
Spotify Web App stops playing music for a second or two when starting or stopping container on Arch linux with docker 1.4.1.

**Comment by janza** [comment] 2015-01-22 21:03
Same here, Archlinux docker 1.4.1
Spotify web player pauses for a few seconds, but Grooveshark works just fine. Both use flash.

```
docker info:

Storage Driver: overlay
Execution Driver: native-0.2
Kernel Version: 3.18.3-1-ck
Operating System: Arch Linux
CPUs: 4
Total Memory: 7.489 GiB

**Comment by 2m** [comment] 2015-01-28 13:53
Noticed that Spotify Web App stops only when committing a `RUN` instruction like so:
`echo "FROM ubuntu:14.04\nRUN echo 'Stop The MUSIC!'" | docker build -`

Other instructions are fine.

**Comment by jfrazelle** [comment] 2015-01-28 15:47
Do you know if the spotify web app uses flash. I think I found the
commonality between all other things were flash apps. I'm just waiting for
this to happen to @crosbymichael since he is all linux now and uses spotify.

**Comment by 2m** [comment] 2015-01-28 15:51
When starting Spotify Web App without flash installed it says:
> To enjoy Spotify, please install Adobe Flash. It's free.

So I presume it does use flash.

**Comment by crosbymichael** [comment] 2015-01-28 17:21
Humm, I have not been able to reproduce yet.  I run 14.10 and spotify all day, hopefully i'll get something soon.  If you encounter this could you check`dmesg` to see if anything looks weird?

**Comment by 2m** [comment] 2015-01-28 18:12
On ArchLinux with docker `1.4.1, build 5bc2ff8` the output of dmesg when running `echo "FROM ubuntu:14.04\nRUN echo 'Stop The MUSIC!'" | docker build -` is:
``` log
[248397.300844] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: discard
[248397.473024] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: discard
[248397.590284] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: discard
[248397.611792] device veth700ab2d entered promiscuous mode
[248397.611899] IPv6: ADDRCONF(NETDEV_UP): veth700ab2d: link is not ready
[248397.665800] eth0: renamed from vethf02ad96
[248397.691285] IPv6: ADDRCONF(NETDEV_CHANGE): veth700ab2d: link becomes ready
[248397.691324] docker0: port 1(veth700ab2d) entered forwarding state
[248397.691343] docker0: port 1(veth700ab2d) entered forwarding state
[248397.779788] docker0: port 1(veth700ab2d) entered disabled state
[248397.779924] EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: discard
[248397.781057] device veth700ab2d left promiscuous mode
[248397.781071] docker0: port 1(veth700ab2d) entered disabled state
[248398.242214] EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: discard
[248398.272284] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: discard
```

Note that I only see six `EXT4-fs...` messages in dmesg when running non-music-stopping docker commands.

**Comment by crosbymichael** [comment] 2015-01-28 18:16
Ya, that looks like a pretty standard dmesg output, humm.....

**Comment by erikh** [comment] 2015-01-29 07:12
is it a network interruption?

**Comment by dzschille** [comment] 2015-01-29 08:08
Spotify webplayer interrupted for ~3 seconds when starting or stopping a single container.
Ubuntu 14.04.1 and Docker version 1.4.1, build 5bc2ff8.

**Comment by 2m** [comment] 2015-01-29 09:47
> is it a network interruption?

If it is, it does not affect other connections. I tried pinging Google every 0.2 seconds while interrupting music using the above mentioned one liner. I did not see any anomalies in the ping responses.

**Comment by 2m** [comment] 2015-01-29 10:00
It seems to be network related after all. I tried running these commands in order that is provided in two terminals ([1] and [2]) and I added a comment if music pauses or not.
```
[1]$ docker run -it ubuntu:14.04 bash # music pauses
[2]$ sudo ip link set docker0 down    # music pauses
[2]$ sudo ip link set docker0 up      # music pauses
[2]$ sudo ip link set docker0 down    # music pauses
[2]$ sudo ip link set docker0 up      # music pauses
[1]$ exit                             # music pauses
[2]$ sudo ip link set docker0 down    # music pauses
[2]$ sudo ip link set docker0 up      # music is fine
[2]$ sudo ip link set docker0 down    # music is fine
[2]$ sudo ip link set docker0 up      # music is fine
```

**Comment by tpires** [comment] 2015-01-29 10:01
Happens to me since I can remember using Docker (a long time ago in a galaxy far far away).

Sometimes it stops and resumes the music, others just stops.
Also happens when using Spotify but with a less interrupted time.

**Comment by erikh** [comment] 2015-01-29 10:17
Oh interesting. Can you supply the arguments you use to run the daemon?

-Erik

**Comment by 2m** [comment] 2015-01-29 10:21
> Oh interesting. Can you supply the arguments you use to run the daemon?

``` bash
➜  ~  ps aux | grep docker
root     16980  0.0  0.1 1220204 45112 ?       Ssl  Jan26   1:47 /usr/bin/docker -d -H fd://
```

**Comment by erikh** [comment] 2015-01-29 10:27
Ok, last q: 

Can you run mtr with an extremely low interval against a local machine and watch this happen with your brctl commands? Trying to sort out what layer this is happening at.

-Erik

**Comment by 2m** [comment] 2015-01-29 10:39
Okay. I tried running `mtr` with interval `0.01` against `127.0.0.1` and `192.168.1.11` and I saw no lost packets while bringing `docker0` up and down while the music was still pausing.

**Comment by WiR3D-kNiGhT** [comment] 2015-01-30 08:42
Happens to me too, using Linux mint 17 and aufs, with ssd and latest docker from ppa

**Comment by 2m** [comment] 2015-02-12 14:22
Music is still stopping with Docker version `1.5.0`.

**Comment by tjmehta** [comment] 2015-02-21 02:28
> This is may sound weird ...

Literally.

**Comment by c0deaddict** [comment] 2015-03-02 10:39
+1

**Comment by andrewmichaelsmith** [comment] 2015-03-14 15:06
So in Ubuntu 14.04 when I am chromecasting youtube videos launch a container will consistently kill the chromecast stream.

**Comment by unclejack** [comment] 2015-03-18 15:55
This is a kernel problem. That means upgrading Docker to a newer or older version won't help and that a fix on the kernel side will most likely be required.

**Comment by unclejack** [comment] 2015-03-26 21:58
Has anyone reproduced this with overlay?

**Comment by janza** [comment] 2015-03-26 22:05
[Yes](https://github.com/docker/docker/issues/8279#issuecomment-71098120), I don't think it depends on the storage driver

**Comment by basvdlei** [comment] 2015-07-09 23:37
It's probably not a Docker issue, I suspect Flash weirdness. I can reproduce it on Debian Jessie (Kernel 3.16.0-4-amd64) with a test bridge interface and Spotify in Google Chrome (which uses Flash):
```sh
brctl addbr test0
ip link set test0 up
```

Strace on the google-chrome's pepper flash player shows threads being stopped and new ones started at the same time the bride interface is brought up or down, during which time the Spotify audio will pause.

**Terminal 1:**
```sh
strace -p `pgrep -f ppapi` -f -e trace=signal
Process 8624 attached with 19 threads
```

**Terminal 2:**
```sh
ip link set test0 down
```
The Spotify audio pauses for a few seconds, and the strace in terminal 1 shows threads being recycled.

**Terminal 1:**
```
[pid  9253] +++ exited with 0 +++
Process 9316 attached
[pid  9256] +++ exited with 0 +++
[pid  9252] +++ exited with 0 +++
[pid  9259] +++ exited with 0 +++
Process 9317 attached
Process 9318 attached
[pid  9318] +++ exited with 0 +++
Process 9319 attached
Process 9320 attached
[pid  9319] +++ exited with 0 +++
Process 9321 attached
Process 9322 attached
[pid  9322] +++ exited with 0 +++
[pid  9321] +++ exited with 0 +++
Process 9324 attached
Process 9325 attached
[pid  9325] +++ exited with 0 +++
```

**Comment by snth** [comment] 2015-07-23 10:00
I can reproduce this on Ubuntu 12.04 with Docker version 1.7.1. Music streaming stops when Docker builds images.

```
$ docker --version
Docker version 1.7.1, build 786b29d
$ uname -a
Linux aam-inv-tb1 3.13.0-58-generic #97~precise1-Ubuntu SMP Wed Jul 8 14:07:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by unclejack** [comment] 2015-07-23 10:07
Can anyone reproduce this when playing back an audio file located on the local machine, not when streaming?

**Comment by WiR3D-kNiGhT** [comment] 2015-07-23 13:43
@unclejack Not on Mint 17.2 with Quod Libet going to alsasink. 
If there are any particular outputs you want me to try I can.

**Comment by pwaller** [comment] 2015-11-16 09:56
I can also reproduce this on Ubuntu 14.04 and 15.10 (4.2.0). It's intermittent so not always easy to reproduce. Sometimes I have to wait a few minutes and come back and then I can reproduce it consistently. While it's possible to reproduce it, this does the trick:

```
while sleep 0.1; do sudo ip link set docker0 up; sleep 0.1; sudo ip link set docker0 down; done
```

@unclejack: can I ask from how you know that this is a kernel problem? Do you have a reference somewhere? Is the mechanism at all understood?

**Comment by Grokzen** [comment] 2015-11-23 12:24
Can confirm spotify web player still hangs when starting/stopping docker images. Using chrome and  `https://player.spotify.com` on Ubuntu 15.10 with `Docker version 1.9.1, build a34a1d5`

**Comment by davidsansay** [comment] 2015-12-28 16:24
Same issue with: 
- Linux Mint 17.1 Rebecca 64 bits
- Tidal on Chrome or on Firefox
- Docker version 1.9.1, build a34a1d5

```
docker run -i -t nginx /bin/bash
```

but if I run the image sharing the network it does not happen

```
docker run --net=host -i -t nginx /bin/bash
```

**Comment by andresmeidla** [comment] 2016-01-06 13:58
web player on Ubuntu 15.10, same issue.
does anyone know a workaround for this?

**Comment by andresmeidla** [comment] 2016-01-06 14:12
workaround: use the Spotify desktop client

**Comment by ronichoudhury** [comment] 2016-01-15 14:23
Same problem here.
- Arch Linux
- Spotify web client
- Docker version 1.9.1, build a34a1d5-dirty

**Comment by amias-channer** [comment] 2016-01-15 16:55
2 years later and this is still not fixed .... :-1:

**Comment by thaJeztah** [comment] 2016-01-16 07:08
@amias-channer feel free to open a PR, or submitting a kernel patch

**Comment by pwaller** [comment] 2016-02-06 16:52
Do we understand the root cause? from [@davidsansay's comment](https://github.com/docker/docker/issues/8279#issuecomment-167598687) it seems to imply it has to do with the network.

I note that I can reproduce this reliably (same platform, web player) using rkt: `sudo ./rkt run --interactive quay.io/coreos/alpine-sh`, so I guess this problem isn't limited to docker (and is probably a bug in spotify's web player).

**Comment by ncurran** [comment] 2016-02-07 08:42
yeah some but not all flash players have this problem and I can make it happen with just modprobe dummy....not a docker thing

**Comment by snth** [comment] 2016-02-08 06:06
I also experience this with the Simfy webplayer on Ubuntu 12.04 x86_64.

**Comment by davidsansay** [comment] 2016-03-17 15:43
I cannot reproduce the error with the Docker version 1.10.0, build 590d5108, on the same pc that had the issue 3 months ago.

**Comment by rijnhard** [comment] 2016-03-18 08:24
@davidsansay you are indeed correct, docker v1.10.3 from official docker ppa on mint 17.3 with kernel 3.19.0-32. can stop and start containers from docker-compose or standalone containers without any issues. it seems this got fixed with all the work that went into 1.10 on the networking side.

**Comment by leighman** [comment] 2016-03-21 09:01
Still a problem on Ubuntu 15.10 with docker 1.10.3

**Comment by TimDaub** [comment] 2016-03-22 09:16
> Still a problem on Ubuntu 15.10 with docker 1.10.3

Multiple devs in our company also have this problem with this setup.
Can this have more visibility? It's super annoying :notes: :cry:

**Comment by rijnhard** [comment] 2016-04-04 11:22
@leighman @TimDaub just out of curiosity which kernel is Ubuntu 15.10 on?

**Comment by ruudud** [comment] 2016-04-04 11:36
```
> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"

> uname -r
4.2.0-34-generic

```

**Comment by TimDaub** [comment] 2016-04-05 08:28
> @leighman @TimDaub just out of curiosity which kernel is Ubuntu 15.10 on?

```bash
➜  ~ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
➜  ~ uname -r
4.2.0-30-generic
➜  ~ uname -r
```

**Comment by leighman** [comment] 2016-04-07 08:18
I get it with 4.4.y series from http://kernel.ubuntu.com/~kernel-ppa/mainline/ as well

**Comment by 2m** [comment] 2016-04-28 12:19
No more music stops! I tried it with the docker command I [posted on this issue](https://github.com/docker/docker/issues/8279#issuecomment-71837580) more than a year ago and now it is fine:

```
➜  echo "FROM ubuntu:14.04\nRUN echo 'Stop The MUSIC!'" | docker build -
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
 ---> 8fa7f61732d6
Step 2 : RUN echo 'Stop The MUSIC!'
 ---> Using cache
 ---> a154d7179101
Successfully built a154d7179101
➜  uname -a
Linux 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux
➜  docker --version
Docker version 1.10.3, build 20f81dd
```

**Comment by thaJeztah** [comment] 2016-04-28 12:23
Do we know which kernel version(s) this was resolved in? Probably this issue can be closed then

**Comment by ruudud** [comment] 2016-04-28 13:07
Confirmed! No more glitches i Ubuntu 16.04

```
> uname -r
4.4.0-21-generic
```

**Comment by justincormack** [comment] 2016-08-08 22:01
Hmm, mixed reports that it is fixed on 4.4.x. Any more updates?

**Comment by franklimstrand** [comment] 2016-10-03 13:29
uname -r
4.4.0-38-generic

docker -v
Docker version 1.12.1, build 23cf638

'docker start' stops tidal playing (Chrome) for a couple of seconds.

**Comment by mickadoo** [comment] 2016-11-03 10:24
I'm on 4.4.0-45-generic and still when I start a docker container I keep losing the connection to the Spotify web player in Firefox.

**Comment by Ndr6** [comment] 2018-04-05 09:02
On linux 4.15.0-14 and Docker version 17.03.2-ce, build f5ec1e2
Music on firefox (tidal) restarts when using "docker run ..."

**Comment by thaJeztah** [comment] 2024-01-09 21:45
Looks like this one went stale; let me close it.

**Closed by thaJeztah** 2024-01-09 21:45 UTC
Labels: area/kernel, exp/expert, kind/bug
