### ISSUE TITLE
Help me please. How to run the Open WRT image on docker?

### ISSUE THREAD

**Issue by dockerPractice** [moby/moby#35458] opened 2017-11-10 05:10 UTC
/kind question
/sig docker
/sig openwrt

**What happened**:
I wrote the [standard_init_linux.go:195: exec user process caused "exec format error"] post in yesterday. I confirmed the answer, so I changed OS[raspbian → Hypriot] and docker[ce-17.10 → ce-17.05]. And I found the new Open WRT docker image from Docker hub like this.
`docker pull nmaas87/docker-openwrt`
Below is Dockerfile's code
```
FROM scratch
MAINTAINER nmaas87 - https://github.com/nmaas87

ADD openwrt-x86-generic-Generic-rootfs.tar.gz /

RUN mkdir /var/lock
USER root
CMD /sbin/init
```

**What you expected to happen**:
I want to run this image and construct the Open WRT environment.

**How to reproduce it (as minimally and precisely as possible)**:
First, I pulled the docker images for Open WRT by root .

I just want to set up Open WRT environment by Raspberry Pi3 on Raspbian with Docker..
What should I do?

**Anything else we need to know?**:

**Environment**:
- Docker version (use `docker version`):
```
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false
```
- Cloud provider or hardware configuration: `Raspberry Pi3`

- OS (use `uname -a`): `Linux black-pearl 4.4.50-hypriotos-v7+ #1 SMP PREEMPT Sun Mar 19 14:11:54 UTC 2017 armv7l GNU/Linux`

- Install tools: Docker-CE v17.05
- Others:

※ P.S : Could you recommend the way that how to set up Open WRT environment using docker images?

**Comment by thaJeztah** [comment] 2017-11-10 07:05
duplicate of your other issue https://github.com/moby/moby/issues/35447 - Docker (and containers in general) do not emulate hardware, so images you run have to match the host.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-11-10 07:05 UTC
Labels: area/builder, area/distribution, platform/arm, version/17.05

**Comment by dockerPractice** [comment] 2017-11-10 07:23
Sorry, I really don't know that..
Thanks for your advice.
