### ISSUE TITLE
Please implement IPv6 NAT as an available alternative option when using docker with IPv6 enabled

### ISSUE THREAD

**Issue by etc0de** [moby/moby#25407] opened 2016-08-04 13:06 UTC
Docker's current IPv6 behavior currently still has the following outstanding problems:
- it lacks -p/--publish and EXPOSE functionality similar to IPv4 (with non-EXPOSE'd ports being hidden, and -p/--publish only using the userland proxy which changes the source IP address to the userland proxy container which makes it near-useless for not all but some protocols because of security reasons - e.g. HTTP can deal with this with proxy headers, but other TCP-based protocols can't). This is a huge pitfall for many users of smaller servers who don't set up manual iptable rules but rely on docker to work as they have grown to expect it out of the box
- it always requires setting up an entire IPv6 prefix which _should_ always be available in theory, but in certain home networks it requires changing the router configuration to be able to trivially use a larger IPv6 prefix range from a single machine, and multiple lan / wlan interfaces on a laptop can make this task more complicated as well

Due to those and other reasons, it would be very nice if IPv6 NAT was added as han _option_ (**not** a full replacement for the current IPv6 default behavior) which could be enabled by the user if desired, to perfectly copy the current IPv4 NAT behavior and resolve all of the things listed above and provide an easy to use standard behavior that "just works".

Please note I agree NAT for IPv6 is often a terrible idea in a larger datacenter where you write custom routing and address assignments anyway - which is why NAT should be an option, not a replacement for the current behavior -, but for small servers and laptops where people just want a working default solution, it would be a big improvement.

There is a temporary implementation available from @robbertkl as a privileged container that modifies the iptables rules on the host with automated container discovery using dockergen: https://github.com/robbertkl/docker-ipv6nat . However, it would be neat if this functionality was integrated into docker itself like IPv4 NAT.

(I created this ticket out of a discussion in ticket #13481 where you can read up more details on the previous discussion)

**Comment by JonasT** [comment] 2016-08-04 13:54
I tried to collect some outstanding IPv6 issue tickets which I believe would be resolved with the availability of IPv6 NAT:

* #17666 (```-p/--publish``` forwards incorrect ip)

* #21951 (EXPOSE and publish need to behave similarly with IPv4 and IPv6 [Security design failure])

While those issues would still not necessarily be resolved for anyone not using NAT, this could be clearly documented and then everyone not choosing to use NAT would have clear knowledge that they are expected to do a bit more of effort for custom routing and firewall rules with iptables if they want to choose that approach. (people with non-NAT interests are mostly those running larger datacenters with custom routing setups anyway)

**Comment by justincormack** [comment] 2016-08-04 14:15
See also #13481 where this is discussed.

**Comment by narqo** [comment] 2016-08-04 16:34
Let me say that the issue is tightly coupled to docker/libnetwork#1183

**Comment by JonasT** [comment] 2016-11-07 12:52
Is there any progress on this? It would be nice if this was eventually added. As described above it's not really a revolutionary feature or anything that someone running a big data center setup would need, but it would really go a long way of making docker more easy to setup for beginners and small server owners.

**Comment by cpuguy83** [comment] 2016-11-07 13:29
ping @docker/core-libnetwork-maintainers

**Comment by michael-batz** [comment] 2017-01-28 16:23
Are there any news on that issue? This would be really a nice feature.

**Comment by mattlqx** [comment] 2017-02-15 04:44
A use-case for this feature would be for in Amazon EC2 since they have recently widely released IPv6 addressing. Unfortunately, they only allow you to assign individual IPv6 addresses (/128) to EC2 instances. You also cannot add routes for IPv6 subnets (for instance a /80 of the VPC's /56) to EC2 instances within the VPC's routing tables. These two limitations make IPv6 NAT the easiest solution for container connectivity on an EC2 instance.

**Comment by mostolog** [comment] 2017-03-08 16:06
Hi

Trying to deploy docker with IPv6, but have found a few issues.

IIUC, and according to https://docs.docker.com/engine/userguide/networking/default_network/ipv6/ setting **--ipv6** on docker daemon would enable IPv6 for docker.
As we haven't DHCP (for ipv6: SLAAC?), daemon fails to start, so **--fixed-cidr-v6** must be provided.

_/etc/systemd/system/docker.service.d/ipv6.conf_
```
...
ExecStart=
ExecStart=/usr/bin/dockerd --ipv6 --fixed-cidr-v6 2001:db8::/64
...
```

At this point, docker is able to start and containers will get valid IPv6 addresses but **containers aren't able to ping outside world/beyond docker host**.

It seems that as IPv6 doesn't have NAT, outgoing requests would be using internal docker IP/network, but target doesn't know where that network is located, so it cant "return".

So, to being able to go beyond host, **ndp_proxy** can be enabled
> sysctl net.ipv6.conf.eth0.proxy_ndp=1 

and a neighbour proxy must be declared for each specific IP
> ip -6 neigh add proxy 2001:db8::c009 dev eth0

So now, we are able to _ping6 www.google.com_ within container.

Adding each container IP manually as a neighbour - IMHO - its painful, horrible and kills a few cats each time is done. To avoid that [ndppd](https://github.com/DanielAdolfsson/ndppd) is suggested.

**Wouldn't it make sense docker adding and removing those neighbours automatically?**
Have anyone considered working on https://github.com/docker/libnetwork/pull/1316 ?

**Wouldn't IPv6 _NAT_ solve this issue also?**

Moreover, swarm mode provides HA for docker services. ie: any docker host can answer to a request, no matter if container is running on another hosts.
On the other hand, seems docker still needs a HAProxy to HA docker hosts.

**Is there any issue open to provide HA for docker hosts?** Maybe a daemon configuration for IPVS could be a good alternative to fix this. **Is anyone working on this?**

Anyway, setting IPv6 networks on daemon requires setting different networks on each host, and requires adding ip routes to being able to use IPv6 between docker on different containers.

May this comment be a request to improve docker IPv6 and swarm mode stack, I'll happily help testing anything you may need.
Regards

**Comment by aboch** [comment] 2017-03-08 16:45
@mostolog 

FYI, @CtrlZvi  has an open PR for automating the ndp_proxy programming: https://github.com/docker/libnetwork/pull/1316

**Comment by JonasT** [comment] 2017-03-09 11:54
Since it has been almost a year, is anyone looking into this? It would be really neat to have, given IPv6 has now some actual real world usage...

And as far as I am aware, without this there is still no neat way to easily run a docker dev environment with full IPv6 connectivity without *lots of pain*. You either have to manually add routing of some sort, or accept that EXPOSE doesn't work, publish doesn't work, running multiple microservices in separate containers on the same ip doesn't work... none of which is a problem in a production environment with a custom routing setup, but definitely on a dev machine where you just randomly throw up services to test and work on them.

**Comment by mostolog** [comment] 2017-03-10 07:47
Regarding swarm IPv6 connectivity, as described in https://docs.docker.com/engine/userguide/networking/default_network/ipv6/#docker-ipv6-cluster, some routes must be managed externally to docker.

As a temporary workaround to improve swarm and IPv6, and making it possible docker to create host's routes automatically, couldn't it use IPv4 connectivity to retrieve host IPv6 and docker networks IPv6's and send them to the manager?

- (nodeA) docker swarm init
- (nodeB) docker swarm join
- (A) get host IPv6 address and docker interfaces IPv6
- (A) as IPv4 connectivity is working, send that information to manager
- (B) send IPv6 information to manager
- (A and B) create routes to docker IPv6 networks using host IPv6 networks automatically (the way a user manually do) _ip router IPv6-docker-network via IPv6-docker-host_

**Comment by BenediktS** [comment] 2017-03-14 14:25
+1 for the request

1und1 servers only get one ipv6 address. I want all my dockers to use ipv6, but i don't want to start all ip6tables rules by hand (I think a "-p 443:443" at startup should do the trick). 

And even if i get more then one IPv6 address, i couldn't say "DNS your AAAA record is one of many xx:xx:xx/64  addresses. But i don't know which one." 
And i can't use "--net=host", because some other things won't work with "--net=host" (ie: rsyslog)

I consider docker ipv6 as broken, until this "feature" is implemented.

**Comment by jojoob** [comment] 2017-04-12 10:47
I also run into problems caused by the lack of the IPv6 NAT feature.

I have a postfix container running on a host. IPv6 is enabled and the SMTP port is exposed via `-p 25:25`. I expected that exposing ports with IPv6 will work like with IPv4. But a test via `telnet -6 localhost 25` on the host machine showed that docker act as a proxy to route the connection via the IPv4 bridge (postfix log shows a connection attempt from the IPv4 docker container gateway address instead of the IPv6 address of the docker host).
https://github.com/robbertkl/docker-ipv6nat solved the problem for me.

**Comment by chrisnew** [comment] 2017-04-12 18:46
@jojoob great finding! I just tried it out and it works like a charm.

**Comment by wrridgwa** [comment] 2017-05-12 20:41
I agree with @BenediktS. Without NAT/Masquerade/port forwarding available for IPv6, Docker doesn't support IPv6.

**Comment by wrridgwa** [comment] 2017-06-28 18:19
I am working on a patch for this. What kind of testing occurs to get through the Docker open source process?

**Comment by chrisnew** [comment] 2017-06-28 21:07
@wrridgwa you can propose your patch by opening a pull request where it should pass all tests. Also you should have a good test coverage as well as some documentation. Thanks for your commitment!

**Comment by wrridgwa** [comment] 2017-10-19 20:54
Here is a pull request with the fix: https://github.com/docker/libnetwork/pull/1992

**Comment by JonasT** [comment] 2017-10-20 11:34
Oh that's so neat!! Any chance this could get merged? ❤️

**Comment by pznamensky** [comment] 2017-11-28 08:33
Are there any news?

**Comment by wrridgwa** [comment] 2018-01-08 16:13
@pznamensky Still waiting for Docker people to move the pull request along.

**Comment by JonasT** [comment] 2018-02-19 15:05
It's a shame it's just sitting here, more or less finished. I have been waiting for this feature for years :cry:

**Comment by amjd** [comment] 2018-03-07 04:06
This is a really important feature for Docker and it's a shame it's not supported yet. Could the maintainers please take this on priority? A lot of people are blocked from using Docker with IPv6 in production because short of having a subnet on the host machine, all other ways seem to be temporary workarounds.

**Comment by JonasT** [comment] 2018-06-19 13:09
@b01t it's already implemented, but the docker people just don't *merge* it, which is disappointing.

**Comment by amjd** [comment] 2018-11-10 20:06
Hi, is there any plan to implement this? It's already been 2+ years since this issue was raised and a lot of users have requested this. I understand the project maintainers have their own priority, but could we get a comment on whether this is planned and if it is, when it's targeted?

**Comment by JonasT** [comment] 2018-11-10 20:49
@fcrisciani may I ping you on this? you indicated this would be considered for future plans, but that was many months ago

**Comment by KyronNextLevel** [comment] 2018-11-30 11:10
Hi. I have struggled for some weeks to understand why I couldn't ping the outside world with an ipv6 container. I had the **exactly same** issues as @mostolog 's ones. As an internship student, discovering docker by doing some tests in ipv6 containers is really painful... It feels like we can make this works only with error prone hacks at the moment... I have read some similar issues and I don't understand **why two years after**, this issue is still relevant and referenced. As @JonasT said, ipv6 support should be a priority and you have several companies wasting a lot of time to make it work.

**Closed** 2020-12-07 10:59 UTC
Labels: area/networking, kind/feature, status/needs-attention
