### ISSUE TITLE
`docker wait` hangs for non-existent containers

### ISSUE THREAD

**Issue by spiffxp** [moby/moby#33964] opened 2017-07-05 20:26 UTC
**Description**

`docker wait does-not-exist` hangs, where it used to immediately exit.  I'm running into this while attempting to build kubernetes via its `make quick-release` target.

I initially filed https://github.com/docker/for-mac/issues/1714 but have seen traffic that indicates it may be happening on linux as well

**Steps to reproduce the issue:**

1. Ensure there is no container named `does-not-exist` present
2. Run `docker wait does-not-exist`

**Describe the results you received:**
```
$ docker wait does-not-exist
# ... hangs, must Ctrl-C out
```

**Describe the results you expected:**
```
$ docker wait does-not-exist
Error response from daemon: No such container: does-not-exist
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true)
```

**Output of `docker info`:**

```
aaron@cloudtop:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 32
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855GiB
Name: moby
ID: H6EK:ZA2G:TBTX:2I5D:TXHW:5GDD:QJTP:QIIS:PMQW:QLJN:U442:35AW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2017-07-05T20:24:31.537901721Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Hardware: Macbook Pro
- OS: OS X 10.11.6
- Kernal (`uname -a`):
`Darwin cloudtop.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64`

May be related to https://github.com/moby/moby/pull/32237 landing

**Comment by thaJeztah** [comment] 2017-07-06 03:12
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/33948, and already resolve on master through https://github.com/moby/moby/pull/33293, which will be included in docker 17.06.1, that is currently being worked on.

I'll close this issue to not diverge the discussion, but feel free to comment after I closed;

Thanks again for reporting!

**Closed by thaJeztah** 2017-07-06 03:12 UTC
Labels: version/17.06
