### ISSUE TITLE
Docker build --force-rm does not work

### ISSUE THREAD

**Issue by thpica** [moby/moby#37311] opened 2018-06-19 16:00 UTC
**Description**

When building a docker fails, it does not cleanup intermediary images afterwards, despite force-rm being set to true.
This seems to be unrelated to client implementation as docker cli, docker compose and the python lib are affected. 

**Steps to reproduce the issue:**
1. Create the `Dockerfile` file:
    ```Dockerfile
    FROM alpine:latest
    RUN touch /test
    RUN exit 1

    ```
2. Create the `docker-compose.yml` file:
   ```yaml
   version: '3'
    services:
      test:
        build: ./
   ```
2. Build the docker using either of the following:
    - docker CLI
        ```sh
        docker build --force-rm .
        ```
    - docker-compose
        ```sh
        docker-compose build --force-rm
        ```
    - docker-py
       ```python
       import docker
       client = docker.APIClient(base_url='unix://var/run/docker.sock')
       for line in client.build(path='.', forcerm=True):
           print(line)
       ```

**Describe the results you received:**
<details><summary>As expected from the Dockerfile, the build fails</summary><p>

- docker CLI
    ```
    Step 1/3 : FROM alpine:latest
    ---> 3fd9065eaf02
    Step 2/3 : RUN touch /test
    ---> Using cache
    ---> 529523b0e9bf
    Step 3/3 : RUN exit 1
    ---> Running in 0c3339881ddd
    Removing intermediate container 0c3339881ddd
    The command '/bin/sh -c exit 1' returned a non-zero code: 1
    ```

- docker-compose
    ```
    Building test
    Step 1/3 : FROM alpine:latest
    ---> 3fd9065eaf02
    Step 2/3 : RUN touch /test
    ---> Using cache
    ---> 529523b0e9bf
    Step 3/3 : RUN exit 1
    ---> Running in 2e8cad66d92f
    Removing intermediate container 2e8cad66d92f
    ERROR: Service 'test' failed to build: The command '/bin/sh -c exit 1' returned a non-zero code: 1
    ```

- docker-py
    ```
    {"stream":"Step 1/3 : FROM alpine:latest"}
    {"stream":"\n"}
    {"stream":" ---\u003e 3fd9065eaf02\n"}
    {"stream":"Step 2/3 : RUN touch /test"}
    {"stream":"\n"}
    {"stream":" ---\u003e Using cache\n"}
    {"stream":" ---\u003e 529523b0e9bf\n"}
    {"stream":"Step 3/3 : RUN exit 1"}
    {"stream":"\n"}
    {"stream":" ---\u003e Running in 6744df31bd31\n"}
    {"errorDetail":{"code":1,"message":"The command '/bin/sh -c exit 1' returned a non-zero code: 1"},"error":"The command '/bin/sh -c exit 1' returned a non-zero code: 1"}
    ```
</p></details></br>

When issuing `docker images` in the docker CLI here is the result:
```
REPOSITORY  TAG     IMAGE ID        CREATED         SIZE
<none>      <none>  cf85c5cd141c    12 seconds ago  4.15MB
```

**Describe the results you expected:**

This image should not be there as it is the result of the failed build and should have been cleaned up with the `force-rm` parameter:
```
REPOSITORY  TAG     IMAGE ID        CREATED         SIZE
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:18:46 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:16:59 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 25
 Running: 5
 Paused: 0
 Stopped: 20
Images: 215
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-128-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.81GiB
Name: mldl3702
ID: RW7S:LAFR:ZOHU:VJQR:SJ5U:MDUO:INLN:LYQW:X7Z6:WP2C:JJRY:7VD7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
_None_

**Comment by thaJeztah** [comment] 2018-06-20 04:19
This is not a bug; the `--force-rm` flag (and `--rm` flag, that's enabled by default) remove the _containers_ that are used during build (see the flag description https://docs.docker.com/engine/reference/commandline/build/#options), but intermediate images will still be created for each successful step (and used as cache for subsequent builds).

In your example, the first `RUN` succeeded, and the result was committed to an image, which is the image that's shown in your output.

Closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-06-20 04:19 UTC
Labels: area/builder

**Comment by KostyaSha** [comment] 2018-11-27 11:34
@thaJeztah 1) from `image` build view point, if build fails, then no image layers are expected to be with `force-rm`. It's also impossible from API view point to know what image was kept in the end of build (beside parsing response stream that is not effective).
2) It's impossible to remove this image and on active build service `docker build --force-rm=true --rm=true --no-cache .` producing dangling layers that consuming space and making DoS. 
Either new flag should be added, either `force-rm` should really force rm everything that was related to image build during image build.

**Comment by KostyaSha** [comment] 2018-12-12 02:22
@thaJeztah please reopen
