### ISSUE TITLE
compose -f multiple yml files can cause storage conflict

### ISSUE THREAD

**Issue by pdl** [moby/moby#48584] opened 2024-10-04 20:50 UTC
### Description

I have two `docker-compose.yml` files, each in a different folder, representing a frontend and backend service. Each binds its `./src` folder to `/app/src` in its respective container, apparently.

The files in [my minimal repo](https://github.com/pdl/20241004-docker-bug) are:

```
README.md
backend/docker-compose.yml
backend/src/backend.txt
frontend/docker-compose.yml
frontend/src/frontend.txt
```

So we expect the following files to exist in the containers:

```
backend/src/backend.txt   -> /app/src/backend.txt  (in the backend container)
frontend/src/frontend.txt -> /app/src/frontend.txt (in the frontend container)
```

In fact, depending on how the services are started, both containers may have `backend/src` bound to `/app/src`.

### Reproduce

```bash
git clone git@github.com:pdl/20241004-docker-bug.git;
cd 20241004-docker-bug;

docker compose \
  -p docker-volume-bug \
  -f backend/docker-compose.yml \
  -f frontend/docker-compose.yml \
up;
```

Observed output:

```
frontend-1  | /app/src/backend.txt
backend-1   | /app/src/backend.txt
```

### Expected behavior

Output:

```
frontend-1  | /app/src/frontend.txt
backend-1   | /app/src/backend.txt
```

### docker version

```bash
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:20 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop  ()
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
$ docker info
Client:
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /usr/local/lib/docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 40
  Running: 11
  Paused: 0
  Stopped: 29
 Images: 41
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 7.607GiB
 Name: docker-desktop
 ID: 3d4166a0-7c12-4d9a-8924-952a92cda31a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///var/run/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Additional Info

See also readme in the linked repository.

This behaviour seems like a bug, or at least very surprising and I've not yet spotted anything in documentation to explain it.

**Comment by thaJeztah** [comment] 2024-10-11 19:18
First of all, this looks to be an issue related to docker compose, which is not maintained in this repository, and would be best to report in the Docker Compose issue tracker; https://github.com/docker/compose/issues

However, in this case, this looks like the expected behavior.

If you specify multiple compose files, you are performing a _merge_ (see https://docs.docker.com/compose/how-tos/multiple-compose-files/merge/). When merging multiple compose files;

- the first compose-file specified is the "base" compose file
- subsequent compose-files are merged with the base compose file
- the merged compose file is run, using the rules that apply to the location of that file.

The last part is important, because paths are evaluated _relative to_ the compose file; in the example from your reproducer repository, the first file specified is `backend/docker-compose.yml`, so paths are evaluated relative to that location (`backend/`);

```bash
docker compose \
-p docker-volume-bug \
-f backend/docker-compose.yml \
-f frontend/docker-compose.yml \
up
```

You can see the results of the merge if you use the [`docker compose config`](https://docs.docker.com/reference/cli/docker/compose/config/) command;

```bash
docker compose \
-p docker-volume-bug \
-f backend/docker-compose.yml \
-f frontend/docker-compose.yml \
config
```

Which outputs the result of the files merged (the output shows the absolute paths, but your can keep them relative using the `--no-path-resolution` option);

```yaml
name: docker-volume-bug
services:
  backend:
    command:
      - find
      - /app/src
      - -type
      - f
    image: debian:12-slim
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/thajeztah/triage/repro-48584/20241004-docker-bug/backend/src
        target: /app/src
        bind:
          create_host_path: true
  frontend:
    command:
      - find
      - /app/src
      - -type
      - f
    image: debian:12-slim
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/thajeztah/triage/repro-48584/20241004-docker-bug/backend/src
        target: /app/src
        bind:
          create_host_path: true
networks:
  default:
    name: docker-volume-bug_default
```

As can be seen in the output, the host path for both services was resolved relative to the base compose file (`/backend`), and `./src` relative to that means that both use `backend/src`.

I did write a proposal at some point to provide (pre-defined) variables that would allow removing ambiguity, but it has not yet been accepted by the compose-spec maintainers;

- https://github.com/compose-spec/compose-spec/issues/248

One solution for this is to create a basic compose-file at the root of your repository that can be used to merge both services; this can be very minimal, for example, only a `name` for the project, but it looks like it's even OK to have an empty file :smile:

`docker-compose.yml` at the root;

```yaml
# empty compose file
```

Then you can run this from the root of your repository;

```bash
docker compose \
-p docker-volume-bug \
-f docker-compose.yml \
-f backend/docker-compose.yml \
-f frontend/docker-compose.yml \
config
```

But that's the manual way! The compose file format also allows you to specify _includes_ (see the [`include` section in the compose file reference](https://docs.docker.com/reference/compose-file/include/)). So if you create the following `docker-compose.yml` at the root of your repository;

```yaml
include:
  - backend/docker-compose.yml
  - frontend/docker-compose.yml
```

Then all you need to run is `docker compose up`, without any arguments. Here's the same using `docker compose config`;

```bash
docker compose -p docker-volume-bug config
```

And the merged file that it produces;

```yaml
name: docker-volume-bug
services:
  backend:
    command:
      - find
      - /app/src
      - -type
      - f
    image: debian:12-slim
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/thajeztah/triage/repro-48584/20241004-docker-bug/backend/src
        target: /app/src
        bind:
          create_host_path: true
  frontend:
    command:
      - find
      - /app/src
      - -type
      - f
    image: debian:12-slim
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/thajeztah/triage/repro-48584/20241004-docker-bug/frontend/src
        target: /app/src
        bind:
          create_host_path: true
networks:
  default:
    name: docker-volume-bug_default
```

```bash
docker compose up
[+] Running 5/0
 ✔ Synchronized File Shares                                                                     0.0s
   ✔ /Users/thajeztah/triage/repro-48584/20241004-docker-bug/backend/src                        0.0s
   ✔ /Users/thajeztah/triage/repro-48584/20241004-docker-bug/frontend/src                       0.0s
 ✔ Container 20241004-docker-bug-frontend-1                                   Recreated         0.1s
 ✔ Container 20241004-docker-bug-backend-1                                    Recreated         0.1s
Attaching to backend-1, frontend-1
backend-1   | /app/src/backend.txt
frontend-1  | /app/src/frontend.txt
backend-1 exited with code 0
frontend-1 exited with code 0
```

**Comment by thaJeztah** [comment] 2024-10-11 19:19
I'm closing this ticket as this is not a bug, but hope the above helps, and feel free to continue the conversation.

**Closed by thaJeztah** 2024-10-11 19:19 UTC
Labels: area/cli, kind/question, status/0-triage, version/27.2

**Comment by pdl** [comment] 2024-10-15 12:16
Thankyou very much for your very kind explanation, which is very clear and will hopefully reach and be helpful to anyone else who was under this particular misapprehension!
