### ISSUE TITLE
Systemctl is not Running inside Ubuntu Docker Container 

### ISSUE THREAD

**Issue by venkat-koppisetti** [moby/moby#38319] opened 2018-12-05 06:17 UTC
**Systemctl is not Running inside Ubuntu Docker Container**

**Steps to reproduce the issue:**
1.  docker build -t test_img .
2.  docker run -itd --privileged --name test_cont test_img
3. docker exec -it test_cont bash

**Describe the results you received:**
root@0768c551c218:/# systemctl
Failed to connect to bus: No such file or directory

**Describe the results you expected:**
systemctl should work

**Additional information you deem important (e.g. issue happens only occasionally):**
The same is working for centos container using --cap-add sys_admin flag
**Output of `docker version`:**

root@EricssonAWS:test# docker --version
Docker version 18.06.1-ce, build e68fc7a

**Output of `docker info`:**

root@EricssonAWS:test# docker info
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 164
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-39-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 6.806GiB
Name: EricssonAWS
ID: 4ZVQ:UG23:43JV:EZSL:KOQ5:XD62:BNBV:XTKL:YZHI:N66U:BNTY:5AMN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running in Ubuntu based virtual box

root@EricssonAWS:test# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

[Dockerfile.txt](https://github.com/moby/moby/files/2647419/Dockerfile.txt)

**Comment by thaJeztah** [comment] 2018-12-05 12:19
This is expected; containers are not VMs; they're sandboxed processes, and as such, don't have an init (such as systemd) running to boot the container.

In your case, the sandboxed process is "bash", and that will be the only process that's running inside the container.

I'll close this issue because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-12-05 12:19 UTC
Labels: area/builder
