### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for FG3K6C3A15800021, not registry-1.docker.io

### ISSUE THREAD

**Issue by Mr-LiuDC** [moby/moby#33154] opened 2017-05-11 02:33 UTC
When I use command ：docker pull ubuntu:16.04
I got this error：
liudecai@my-ubuntu-server:~$ docker pull ubuntu:16.04
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for FG3K6C3A15800021, not registry-1.docker.io

I use Ubuntu Server 16.04 ，docker version is 17.03.1-ce
How can I solve this problem?

**Comment by thaJeztah** [comment] 2017-05-11 08:42
Are you behind a proxy-server? 

Can you provide the information that was [requested in the issue template](https://raw.githubusercontent.com/moby/moby/ff3f3d7941edee7d5a3b6b13f6c0ef6f2d58bc8b/.github/ISSUE_TEMPLATE.md)?

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by Mr-LiuDC** [comment] 2017-05-12 03:35
@thaJeztah  Yes, I'm behind a proxy-server of our company. Because the firewall or something ？

**Comment by thaJeztah** [comment] 2017-05-12 08:34
I suspect it's a man-in-the-middle proxy that modifies the SSL request. There are some instructions for configuring a proxy to be used by the docker daemon here; https://docs.docker.com/v1.13/engine/admin/systemd/#http-proxy, but it really depends on your environment how to properly set this up.

Given that this is not a bug, I'm closing this issue, but feel free to continue the discussion

**Closed by thaJeztah** 2017-05-12 08:34 UTC
Labels: area/distribution, status/more-info-needed

**Comment by Mr-LiuDC** [comment] 2017-05-16 01:32
@thaJeztah Thank you so much. It's work.

**Comment by Mr-LiuDC** [comment] 2017-05-16 01:35
@thaJeztah Thank you so much. It works.

**Comment by thaJeztah** [comment] 2017-05-16 11:41
Great! Thanks for the update!

**Comment by Htag** [comment] 2019-10-28 12:43
> I suspect it's a man-in-the-middle proxy that modifies the SSL request. There are some instructions for configuring a proxy to be used by the docker daemon here; https://docs.docker.com/v1.13/engine/admin/systemd/#http-proxy, but it really depends on your environment how to properly set this up.
> 
> Given that this is not a bug, I'm closing this issue, but feel free to continue the discussion

Link given is no longer working

**Comment by thaJeztah** [comment] 2019-10-28 17:10
@Htag updated the link to a more recent version
