### ISSUE TITLE
[Windows] different ENTRYPOINT + CMD behavior between docker versions

### ISSUE THREAD

**Issue by dgkanatsios** [moby/moby#40282] opened 2019-12-04 05:51 UTC
Dockerfile
```
FROM mcr.microsoft.com/windows/servercore:10.0.17763.437
COPY . .
COPY WindowsContainerStartupScript.ps1 C:\\scripts
WORKDIR c:\\assets
ENTRYPOINT powershell ls && 
CMD cmd /c tasklist
```
On docker build with 18.09.6, I get this for CMD and ENTRYPOINT

```
 "Cmd": [
                "cmd",
                "/S",
                "/C",
                "cmd /c tasklist"
            ],
            "ArgsEscaped": true,
            "WorkingDir": "C:\\assets",
            "Entrypoint": [
                "cmd",
                "/S",
                "/C",
                "powershell ls &&"
            ],
```

On docker build with 19.03.5, I get this

```
 "Cmd": [
                "cmd",
                "/S",
                "/C",
                "#(nop) ",
                "CMD [\"cmd /S /C cmd /c tasklist\"]"
            ],
            "ArgsEscaped": true,
            "WorkingDir": "C:\\assets",
            "Entrypoint": [
                "cmd /S /C powershell ls &&"
            ],
```

As you can see, the arguments on CMD and ENTRYPOINT are treated differently between versions.
The problem with the latest version is that an execution with `docker run myImage:myTag cmd /c anyCommand` will fail with the error

```
container 6dc24a8608a164d1570eac47c01355e0e1707098e8818184c1332824705b2687 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified
```

Is there any workaround/fix planned for that? The reason I'm using two ampersands is that I want to run a Powershell script before launching whatever is on CMD. Any alternative ways to do that?

Thanks!

**Comment by thaJeztah** [comment] 2019-12-09 13:14
Looks like a duplicate of https://github.com/moby/moby/issues/39731 / https://github.com/docker/for-win/issues/4386, and related to https://github.com/opencontainers/runtime-spec/pull/998

let me close this one as duplicate of https://github.com/moby/moby/issues/39731

**Closed by thaJeztah** 2019-12-09 13:14 UTC
