### ISSUE TITLE
unset docker environment variables

### ISSUE THREAD

**Issue by zyvas** [moby/moby#30236] opened 2017-01-18 08:50 UTC
before

```
ENV WORK_PATH /usr/src/inazuma
ENV INAZUMA_NSQ_TLS_KEYFILE $WORK_PATH/clientkey.pem
```

I hope I can easily configure the environment variables.

like,

```
$ if [ -f "clientkey.pem" ]; then  export INAZUMA_NSQ_TLS_KEYFILE="/usr/src/inazuma/clientkey.pem"; fi
```

but I only find that

```
ENV INAZUMA_NSQ_TLS_KEYFILE ${value:-$WORK_PATH/clientkey.pem}
```

The default is set to an empty string.

Actually, empty string is value of string type.

what's the best practices for unset docker environment variables ?

**Comment by thaJeztah** [comment] 2019-12-30 15:35
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-12-30 15:35 UTC
Labels: area/builder, kind/question
