### ISSUE TITLE
docker-machine deploys Ubuntu instance but Docker Daemon will not load.

### ISSUE THREAD

**Issue by dmccullo** [moby/moby#34095] opened 2017-07-13 16:45 UTC
**Description**

**Steps to reproduce the issue:**
1.When I deploy Docker machines with this command
docker-machine create --openstack-flavor-name s1.small --openstack-image-id 1b8a53f4-1986-492d-a6ad-4907b69fc76b --openstack-nova-network -d openstack Hostname
on Ubuntu 14.04 kernel 3.13.0-37-generic 
2.When i try to regenerate certs 
docker-machine regenerate-certs hostname 
3. When I change to Ubuntu 16.04 kernel 4.4.0-53-generic
docker-machine create --openstack-flavor-name s1.small --openstack-image-id 9d018c75-c18d-40bf-853f-6266d1267d0d --openstack-nova-network -d openstack HostnameUB16

**Describe the results you received:**
1. The instance gets deployed to openstack and during provisioning I get this error
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "208.75.74.38:2376": dial tcp 208.75.74.38:2376: getsockopt: connection refused

2. Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Installing Docker...
Error getting SSH command to check if the daemon is up: ssh command error:
command : sudo docker version
err     : exit status 1
output  : Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:16 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

3. Running pre-create checks...
Creating machine...
(HostnameUB16) Creating machine...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
**Describe the results you expected:**

Running on the same mac with all the same Openstack variables defined with the same openstack tenant using Centos 7 Kernel 3.10.0-514.10.2.el7.x86_64 i get 
Running pre-create checks...
Creating machine...
(HostnameCE) Creating machine...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with centos...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env HostnameCE
**Additional information you deem important (e.g. issue happens only occasionally):**
Docker.log entered for Ubuntu 14.04
ubuntu@Hostname:/var/log/upstart$ sudo tail docker.log
Error starting daemon: error initializing graphdriver: driver not supported
/var/run/docker.sock is up
time="2017-07-12T18:24:26.447506565Z" level=info msg="libcontainerd: new containerd process, pid: 10734"
Error starting daemon: error initializing graphdriver: driver not supported
/var/run/docker.sock is up
time="2017-07-12T18:24:26.528832633Z" level=info msg="libcontainerd: new containerd process, pid: 10784"
Error starting daemon: error initializing graphdriver: driver not supported
/var/run/docker.sock is up
time="2017-07-12T18:24:26.620341009Z" level=info msg="libcontainerd: new containerd process, pid: 10862"
Error starting daemon: error initializing graphdriver: driver not supported

Docker.logs for Ubuntu 16.04
**Output of `docker version`:**
Jul 13 15:20:44 HostnameUB16 systemd[1]: Starting Docker Application Container Engine...
Jul 13 15:20:44 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:44.664473778Z" level=info msg="libcontainerd: new containerd process, pid: 4534"
Jul 13 15:20:44 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:44.679879435Z" level=warning msg="failed to rename /var/lib/docker/tmp for background deletion: rename /var/lib/docker/tmp /
Jul 13 15:20:44 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:44.838203421Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 13 15:20:44 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:44.838710361Z" level=warning msg="Your kernel does not support swap memory limit"
Jul 13 15:20:44 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:44.839028871Z" level=warning msg="Your kernel does not support cgroup rt period"
Jul 13 15:20:44 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:44.839226345Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Jul 13 15:20:44 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:44.839810276Z" level=info msg="Loading containers: start."
Jul 13 15:20:45 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:45.240554465Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip ca
Jul 13 15:20:45 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:45.319481075Z" level=info msg="Loading containers: done."
Jul 13 15:20:45 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:45.331099182Z" level=info msg="Daemon has completed initialization"
Jul 13 15:20:45 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:45.331390694Z" level=info msg="Docker daemon" commit=02c1d87 graphdriver=overlay2 version=17.06.0-ce
Jul 13 15:20:45 HostnameUB16 systemd[1]: Started Docker Application Container Engine.
Jul 13 15:20:45 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:45.343944722Z" level=info msg="API listen on /var/run/docker.sock"
Jul 13 15:20:48 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:48.603258170Z" level=info msg="Processing signal 'terminated'"
Jul 13 15:20:48 HostnameUB16 systemd[1]: Stopping Docker Application Container Engine...
Jul 13 15:20:48 HostnameUB16 dockerd[4527]: time="2017-07-13T15:20:48.60414977Z" level=info msg="stopping containerd after receiving terminated"
Jul 13 15:20:48 HostnameUB16 systemd[1]: Stopped Docker Application Container Engine.
Jul 13 15:20:55 HostnameUB16 systemd[1]: Starting Docker Application Container Engine...
Jul 13 15:20:55 HostnameUB16 docker[5255]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 15:20:55 HostnameUB16 systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Unit entered failed state.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 13 15:20:55 HostnameUB16 systemd[1]: Stopped Docker Application Container Engine.
Jul 13 15:20:55 HostnameUB16 systemd[1]: Starting Docker Application Container Engine...
Jul 13 15:20:55 HostnameUB16 docker[5269]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 15:20:55 HostnameUB16 systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Unit entered failed state.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 13 15:20:55 HostnameUB16 systemd[1]: Stopped Docker Application Container Engine.
Jul 13 15:20:55 HostnameUB16 systemd[1]: Starting Docker Application Container Engine...
Jul 13 15:20:55 HostnameUB16 docker[5276]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 15:20:55 HostnameUB16 systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Unit entered failed state.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 13 15:20:55 HostnameUB16 systemd[1]: Stopped Docker Application Container Engine.
Jul 13 15:20:55 HostnameUB16 systemd[1]: docker.service: Start request repeated too quickly.
Jul 13 15:20:55 HostnameUB16 systemd[1]: Failed to start Docker Application Container Engine.
```
(paste your output here)
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false```

**Output of `docker info`:**

```
(paste your output here)
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 9
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.934GiB
Name: moby
ID: 5AXK:74Q6:SYRS:3O3F:J6UA:KBBP:IGKD:VRSS:UDSR:GHK3:T4OW:GOS6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-07-13T15:23:40.534570366Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack 
Docker-machine version docker-machine version 0.12.0, build 45c69ad

**Comment by thaJeztah** [comment] 2017-07-13 17:32
This is a docker-machine bug; can you try upgrading docker-machine to 0.12.2, and create a fresh machine? https://github.com/docker/machine/releases/tag/v0.12.2

I'll close this issue here, because this is  bug in docker-machine, but feel free to continue the conversation. If you're still able to reproduce on docker-machine 0.12.2, please open a new issue in the docker-machine issue tracker (https://github.com/docker/machine/issues

**Closed by thaJeztah** 2017-07-13 17:32 UTC
Labels: version/17.06
