### ISSUE TITLE
docker info and docker ps hangs for a few weeks

### ISSUE THREAD

**Issue by jonemeng** [moby/moby#33012] opened 2017-05-04 04:21 UTC
**Description**
when i use mesos chronos to schedule task ,for a few weeks docker daemon become hang

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 25
 Running: 24
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 23.71 GB
 Data Space Total: 107.4 GB
 Data Space Available: 83.66 GB
 Metadata Space Used: 10.39 MB
 Metadata Space Total: 10.74 GB
 Metadata Space Available: 10.73 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6 GiB
Name: bjsjs_110_46
ID: 3U4N:YSEI:U4UZ:2JMZ:UN2C:U6MG:UJ5X:K32T:AOMD:4XDF:AUGB:FVRB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 IP=10.134.110.46
 node=node-3
 network=nat
 ssd=1
 gpu=0
Cluster Store: consul://10.134.110.46:8500
Cluster Advertise: 10.134.110.46:2376
Insecure Registries:
 registry.service.consul:5000
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
kill -SIGUSR1 stack trace:
[dumpinfo.txt](https://github.com/moby/moby/files/975209/dumpinfo.txt)

**Comment by cpuguy83** [comment] 2017-05-04 12:56
@rhvgoyal Can you take a look? Seems that this is stuck on `dm_task_run`

```
goroutine 2445379 [syscall, 3132 minutes, locked to thread]:
github.com/docker/docker/pkg/devicemapper._C2func_dm_task_run(0x7f51c402e030, 0x7f5100000000, 0x0, 0x0)
	??:0 +0x4c
github.com/docker/docker/pkg/devicemapper.dmTaskRunFct(0x7f51c402e030, 0xc8234f8a80)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:96 +0x75
github.com/docker/docker/pkg/devicemapper.(*Task).run(0xc8232bced8, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:155 +0x37
github.com/docker/docker/pkg/devicemapper.SuspendDevice(0xc822349f20, 0x59, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:627 +0x99
github.com/docker/docker/pkg/devicemapper.CreateSnapDevice(0xc8244b8300, 0x1b, 0x8b48, 0xc822349f20, 0x59, 0x8b47, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:759 +0x92
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).createRegisterSnapDevice(0xc8203c8340, 0xc8212f8080, 0x40, 0xc8212f8540, 0x280000000, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:861 +0x550
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).AddDevice(0xc8203c8340, 0xc8212f8080, 0x40, 0xc82268c9b0, 0x45, 0x0, 0x0, 0x0)
	/root/rpm
Apr 17 10:12:31 bjsjs_110_46 dockerd[20348]: build/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:1887 +0xa5c
github.com/docker/docker/daemon/graphdriver/devmapper.(*Driver).Create(0xc8201847d0, 0xc8212f8080, 0x40, 0xc82268c9b0, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:131 +0x6f
github.com/docker/docker/daemon/graphdriver/devmapper.(*Driver).CreateReadWrite(0xc8201847d0, 0xc8212f8080, 0x40, 0xc82268c9b0, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:126 +0x86
github.com/docker/docker/daemon/graphdriver.(*NaiveDiffDriver).CreateReadWrite(0xc820086b80, 0xc8212f8080, 0x40, 0xc82268c9b0, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0)
```

**Comment by rhvgoyal** [comment] 2017-05-08 17:52
Is this reproducible? Without that it is very hard to say what might have caused this.

**Comment by jonemeng** [comment] 2017-05-09 03:02
yes,it's reproducible,when i use chronos to schedule task,a few weeks later docker must be hangs.About 30~40 container running in this docker daemon.

**Comment by jonemeng** [comment] 2017-05-09 09:21
i got some message when docker daemon hang.
May 09 15:18:40 bjsjs_110_46 kernel: INFO: task dockerd:14148 blocked for more than 120 seconds.
May 09 15:18:40 bjsjs_110_46 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May 09 15:18:40 bjsjs_110_46 kernel: dockerd         D 0000000000000000     0 14148      1 0x00000000
May 09 15:18:40 bjsjs_110_46 kernel:  ffff8810069c3ab0 0000000000000086 ffff881006d6e780 ffff8810069c3fd8
May 09 15:18:40 bjsjs_110_46 kernel:  ffff8810069c3fd8 ffff8810069c3fd8 ffff881006d6e780 ffff8810069c3bf0
May 09 15:18:40 bjsjs_110_46 kernel:  ffff8810069c3bf8 7fffffffffffffff ffff881006d6e780 0000000000000000
May 09 15:18:40 bjsjs_110_46 kernel: Call Trace:
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8163a909>] schedule+0x29/0x70
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff816385f9>] schedule_timeout+0x209/0x2d0
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8108e4cd>] ? mod_timer+0x11d/0x240
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8163acd6>] wait_for_completion+0x116/0x170
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff810b8c10>] ? wake_up_state+0x20/0x20
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff810ab676>] __synchronize_srcu+0x106/0x1a0
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff810ab190>] ? call_srcu+0x70/0x70
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff81219ebf>] ? __sync_blockdev+0x1f/0x40
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff810ab72d>] synchronize_srcu+0x1d/0x20
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa000318d>] __dm_suspend+0x5d/0x220 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa0004c9a>] dm_suspend+0xca/0xf0 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa0009fe0>] ? table_load+0x380/0x380 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa000a174>] dev_suspend+0x194/0x250 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa0009fe0>] ? table_load+0x380/0x380 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa000aa25>] ctl_ioctl+0x255/0x500 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8112483d>] ? call_rcu_sched+0x1d/0x20
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa000ace3>] dm_ctl_ioctl+0x13/0x20 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff811f1ef5>] do_vfs_ioctl+0x2e5/0x4c0
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff81640ec9>] ? __do_page_fault+0x1f9/0x420
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff811f2171>] SyS_ioctl+0xa1/0xc0
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff81645909>] system_call_fastpath+0x16/0x1b
May 09 15:18:40 bjsjs_110_46 kernel: INFO: task kworker/u66:0:28922 blocked for more than 120 seconds.
May 09 15:18:40 bjsjs_110_46 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May 09 15:18:40 bjsjs_110_46 kernel: kworker/u66:0   D ffff8803dd82c0e0     0 28922      2 0x00000000
May 09 15:18:40 bjsjs_110_46 kernel: Workqueue: kdmremove do_deferred_remove [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  ffff881b2149bcf0 0000000000000046 ffff881ae49aae00 ffff881b2149bfd8
May 09 15:18:40 bjsjs_110_46 kernel:  ffff881b2149bfd8 ffff881b2149bfd8 ffff881ae49aae00 ffff8803dd82c0d8
May 09 15:18:40 bjsjs_110_46 kernel:  ffff8803dd82c0dc ffff881ae49aae00 00000000ffffffff ffff8803dd82c0e0
May 09 15:18:40 bjsjs_110_46 kernel: Call Trace:
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8163b9e9>] schedule_preempt_disabled+0x29/0x70
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff816396e5>] __mutex_lock_slowpath+0xc5/0x1c0
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff81638b4f>] mutex_lock+0x1f/0x2f
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa0002e9d>] __dm_destroy+0xad/0x340 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa00047e3>] dm_destroy+0x13/0x20 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa0008d6d>] dm_hash_remove_all+0x6d/0x130 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa000b50a>] dm_deferred_remove+0x1a/0x20 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffffa0000dae>] do_deferred_remove+0xe/0x10 [dm_mod]
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8109d5fb>] process_one_work+0x17b/0x470
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8109e3cb>] worker_thread+0x11b/0x400
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff8109e2b0>] ? rescuer_thread+0x400/0x400
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff810a5aef>] kthread+0xcf/0xe0
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff810a5a20>] ? kthread_create_on_node+0x140/0x140
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff81645858>] ret_from_fork+0x58/0x90
May 09 15:18:40 bjsjs_110_46 kernel:  [<ffffffff810a5a20>] ? kthread_create_on_node+0x140/0x140

**Comment by rhvgoyal** [comment] 2017-05-09 17:22
This is an old bug which has been fixed. You need to get more recent kernel.

**Comment by thaJeztah** [comment] 2017-05-09 19:12
Let me go ahead and close this issue as it looks like it's not a bug in docker, but a kernel issue. Feel free to continue the discussion though

**Closed by thaJeztah** 2017-05-09 19:12 UTC
Labels: area/kernel, area/storage/devicemapper, version/1.12
