### ISSUE TITLE
moby `make all` fails on master in btrfs on arm64

### ISSUE THREAD

**Issue by vielmetti** [moby/moby#38307] opened 2018-12-02 05:10 UTC
**Description**

docker build for master succeeds on arm64 on Ubuntu 16.04 (Packet c1.large.arm) but fails on  Ubuntu 18.04 (AWS a1.medium). 

**Steps to reproduce the issue:**
1. check out master at `ad1354ffb423620c1a86de0c531c9d7a0f640365` on those machines
2. `make all`
3. make fails on a1.medium

**Describe the results you received:**

Log output follows. from a1.medium machine on AWS:

```
daemon/graphdriver/register/register_btrfs.go:7:4:warning: could not import github.com/docker/docker/daemon/graphdriver/btrfs (invalid package name: "") (unconvert)
pkg/loopback/attach_loopback.go:21:36:warning: undeclared name: LoNameSize (unconvert)
pkg/loopback/attach_loopback.go:22:11:warning: undeclared name: LoNameSize (unconvert)
pkg/loopback/attach_loopback.go:122:15:warning: undeclared name: LoFlagsAutoClear (unconvert)
pkg/loopback/attach_loopback.go:119:15:warning: undeclared name: loopInfo64 (unconvert)
pkg/loopback/ioctl.go:23:53:warning: undeclared name: loopInfo64 (unconvert)
pkg/loopback/ioctl.go:31:55:warning: undeclared name: LoopClrFd (unconvert)
pkg/loopback/ioctl.go:40:55:warning: undeclared name: LoopGetStatus64 (unconvert)
pkg/loopback/ioctl.go:38:15:warning: undeclared name: loopInfo64 (unconvert)
pkg/loopback/ioctl.go:47:39:warning: undeclared name: LoopSetCapacity (unconvert)
pkg/loopback/ioctl.go:37:45:warning: undeclared name: loopInfo64 (unconvert)
pkg/loopback/ioctl.go:24:55:warning: undeclared name: LoopSetStatus64 (unconvert)
pkg/loopback/ioctl.go:12:42:warning: undeclared name: LoopCtlGetFree (unconvert)
pkg/loopback/ioctl.go:20:39:warning: undeclared name: LoopSetFd (unconvert)
Makefile:116: recipe for target 'all' failed
```

**Describe the results you expected:**

Expected `make` to succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Tested on both Amazon AWS a1.medium (1x A72 cores) and Packet c1.large.arm (96x ThunderX cores).

**Comment by thaJeztah** [comment] 2018-12-02 09:33
Wondering if this file should have `linux,cgo` as build tags https://github.com/moby/moby/blob/master/daemon/graphdriver/btrfs/btrfs.go

Given that the "unsupported" has `!cgo` https://github.com/moby/moby/blob/master/daemon/graphdriver/btrfs/dummy_unsupported.go

@kolyshkin

**Comment by kolyshkin** [comment] 2018-12-03 23:55
@vielmetti Is this Ubuntu 18.04 / arm64?

From what I see, it looks like an incomplete build environment (missing cgo or some C library headers maybe), but it's not very clear from the output, so I need to repro this.

> Wondering if this file should have linux,cgo as build tags
> https://github.com/moby/moby/blob/master/daemon/graphdriver/btrfs/btrfs.go

`import "C"` implies `cgo`, so adding the tag is redundant. Source: https://golang.org/cmd/cgo/

**Comment by thaJeztah** [comment] 2018-12-07 00:46
> import "C" implies cgo, so adding the tag is redundant. Source: https://golang.org/cmd/cgo/

Ah, good one

**Comment by neersighted** [comment] 2023-01-22 20:02
I cannot reproduce this on any modern branch of the codebase; and #44761 should have improved the ease of building the Btrfs graphdriver quite a bit. I'm going to close this; please comment if you can still reproduce this issue.

**Closed by neersighted** 2023-01-22 20:02 UTC
Labels: area/storage/btrfs, area/packaging
