### ISSUE TITLE
Docker tty is not a tty with docker exec

### ISSUE THREAD

**Issue by MichaelBitard** [moby/moby#8755] opened 2014-10-24 15:49 UTC
When I enter a running docker with "docker exec -ti mydockerinstance /bin/bash"

tty returns: not a tty and tmux doesn't work.

I tried several things from https://github.com/docker/docker/issues/728:
   `docker exec -ti mydockerinstance sh -c "exec >/dev/tty 2>/dev/tty </dev/tty && /usr/bin/tmux -s /bin/bash"`
   `getty tty`
 but nothing succeded.

**Comment by jfrazelle** [comment] 2015-01-19 23:29
can you all let me know if this is still a relevant issue.

**Comment by MichaelBitard** [comment] 2015-01-20 08:37
Yes, it's still relevant.

```bash
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
```

**Comment by michaelsbradleyjr** [comment] 2015-01-23 21:11
I'm experiencing the same problem, docker `1.4.1`.

**Comment by cpuguy83** [comment] 2015-01-23 21:31
So, what image are you running, and with what run command, and what exec command?

**Comment by michaelsbradleyjr** [comment] 2015-01-23 21:44
@cpuguy83 I am running an image based on `ubuntu:14.04` via the most recent boot2docker. I have experienced the same problem with all previous versions of docker / boot2docker which I've used in recent months.

Here are the steps which can be used to reproduce the problem.

```shell
# on the docker host
docker run -it --rm --name foo ubuntu:14.04 bash
# inside the container
apt-get update
apt-get install tmux
tmux
```
In another terminal on the host:

```shell
docker exec -it foo bash
# inside the container
tmux ls
```
The latter command will fail, and tmux will crash in the original terminal, in some cases killing the container altogether and/or turning it into a container-zombie (in which case one must `boot2docker restart` and then `docker rm` to get rid of it).

**Comment by MichaelBitard** [comment] 2015-01-23 21:48
It seems that any image which has bash in it has the problem.

Step to reproduce:
```
docker run --name no_tty -dti ubuntu /bin/bash (or whatever)
docker exec -ti no_tty /bin/bash
tty -> not a tty
```

**Comment by michaelsbradleyjr** [comment] 2015-02-04 21:37
Any chance a fix for this bug will land in `1.5.0`?

**Comment by cpuguy83** [comment] 2015-02-05 16:25
So what is the purpose of using `docker exec` to fire up a tmux session?

**Comment by MichaelBitard** [comment] 2015-02-05 17:19
We use docker with ansible as a developer workstation, with this we have a
reproductible environment among all the developers
And as a developer, I use tmux. QED :)

If you are interested, here is a quickstarter
https://github.com/MichaelBitard/docker-ansible

Le Thu Feb 05 2015 at 5:27:03 PM, Brian Goff <notifications@github.com> a
écrit :

**Comment by michaelsbradleyjr** [comment] 2015-02-05 21:04
@cpuguy83 when working in "dev mode" with my containers, I generally pass `-it` to `docker run` and fire up tmux (i.e. when it seems useful to me to do so). It would be extremely useful (to me) to be able to fire up tmux in the context of `exec -it`, regardless of whether `-it` had been passed to `run`. At present, since the environment provided by `exec` is `not a tty` – even when invoked with `-it` flags (a pseudo-TTY is not actually allocated, apparently) – it's not possible to use it in this way. At the very least, perhaps the `--help` output of `exec` ought to be amended to indicate that it's `-it` option has limitations relative to `run -it`.

**Comment by razic** [comment] 2015-02-05 21:56
i also use docker for my development environment. this is why i run tmux
inside a container.

**Comment by dbabits** [comment] 2015-02-19 00:58
@michaelsbradleyjr +1 on Michael's comments.
To add a bit more to the use case:
I use a  docker image as my dev environment.

The connection to the host often drops.

The image itself is designed to run monit(proc monitor), not bash, and I connect to it by way of `-exec -ti bash`

Then I would like to `tmux attach` and be back to where I left off.

If somebody has a better suggestion how to accomplish this, I appreciate your comments.

**Comment by jmreicha** [comment] 2015-03-08 02:25
+1

**Comment by pikeas** [comment] 2015-03-11 08:55
+1!

**Comment by pwaller** [comment] 2015-03-18 11:16
I've just hit this. It's blocking me from sharing my environment with another developer in realtime, which is a problem.

**Comment by dbabits** [comment] 2015-03-18 22:16
This is what I do now:
run tmux on the docker host, not inside docker, and docker session in one of tmux's windows.
this achieves my goal explained above.

**Comment by pwaller** [comment] 2015-03-18 23:17
Unfortunately I run coreos and running tmux on the host is not desirable, because I don't want to modify the host image at all, just run docker images for everything. This bug impedes that.

On 18 March 2015 22:17:15 GMT+00:00, dbabits <notifications@github.com> wrote:
>This is what I do now:
>run tmux on the docker host, not inside docker, and docker session in
>one of tmux's windows.
>this achieves my goal explained above.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/docker/docker/issues/8755#issuecomment-83205365

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MichaelBitard** [comment] 2015-03-19 08:05
I have a workaround : 

```bash
docker exec -ti `your_container_id` script -q -c "/bin/bash" /dev/null
```

Ok, it's an ugly one, but with it you can use tmux when you use docker exec

**Comment by cyphar** [comment] 2015-03-23 21:31
Things like `sudo` and `su` are also broken by not having a tty in the container.

**Comment by mouchtaris** [comment] 2015-03-29 16:22
Also pacman in Arch fails with

    error: GPGME error: Inappropriate ioctl for device

because of TTY 404.

**Comment by Malet** [comment] 2015-04-08 09:38
Also having this issue (when trying to run tmux):

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by larsr** [comment] 2015-04-28 11:40
I also have this issue.  I want to share a GNU Screen session among two developers in the same dicker instance.  Thanks to @MichaelBitard  (Mars 19) for the temporary work-around!

**Comment by aidanhs** [comment] 2015-04-29 14:18
I can only assume that this is what means page up and down don't work in less.

**Comment by razic** [comment] 2015-05-11 19:18
Found another instance where this is a pain in the ass...

```bash
docker-machine ssh "docker run -ti ubuntu bash"
time="2015-05-11T19:15:20Z" level=fatal msg="cannot enable tty mode on non tty input"
FATA[0000] exit status 1
```

You can allocate TTY by wrapping the original command with `script`, as mentioned in the previous comments.

**Comment by razic** [comment] 2015-05-13 20:36
A super simple example to reproduce:

```
docker exec -ti $CONTAINER_NAME tty
=> not a tty
```

**Comment by LK4D4** [comment] 2015-05-13 22:12
Fun stuff that `test -t 0` returns zero in exec.

**Comment by LK4D4** [comment] 2015-05-13 22:26
So `isatty` returns 1 for `STDIN_FILENO`, but `ttyname` returns NULL.

**Comment by LK4D4** [comment] 2015-05-13 23:53
This is because there is no `/dev/pts/` files inside container mount namespace.

**Comment by cyphar** [comment] 2015-05-14 15:47
@LK4D4 It's because things like `su` run `readlink(2)` on the magic symlinks in `/proc/self/fd/` to see if they are a TTY. This is also done by `ttyname` AFAIK (I probably should test this). However, it is not *really* a good indicator of whether an `fd` is a `tty` if the symlinks inside `/proc/self/fd/` are not pointing to real locations on the filesystem.

**Comment by LK4D4** [comment] 2015-05-14 17:00
@cyphar Yup, it is really `tty`, but `tty` tool using `ttyname` first, so it fails.

**Comment by cyphar** [comment] 2015-05-15 15:23
I'd ask if we should send a whole bunch of upstream patches to fix this, but I have my doubts that they'd land (or even solve this problem for us in the next few years). Is there a way we can create the `pts` inside the container's mount namespace, so the `tty` magic symlinks aren't broken?

**Comment by LK4D4** [comment] 2015-05-15 15:37
@cyphar I think it is possible to do if mount outside `/dev/pts/<num>` to containers dev in `nsexec.c` like we mounting it to `/dev/console` for main process.
Or it is possible to use container's devpts, but we need somehow to take fd from inside mount namespace back to docker.

**Comment by andrefernandes** [comment] 2015-05-21 14:54
The docker Windows client (from Boot2Docker) runs ok ("docker run --rm -ti ...") on a Windows text prompt, but fails with this very same error when called from CygWin.

**Comment by thaJeztah** [comment] 2015-05-21 22:46
@andrefernandes that's a different issue. This issue is specifically for `docker exec`. What you're describing is probably (related to) this issue: https://github.com/docker/docker/issues/12469

**Comment by cyphar** [comment] 2015-05-21 23:16
@andrefernandes This is a server-side issue, it's because TTY allocation on the Linux host isn't being done by us correctly.

**Comment by senorsmile** [comment] 2015-05-28 21:32
Just found this issue after having issues with tmux and su.  Has anyone come up with any patches yet?

**Comment by razic** [comment] 2015-05-28 21:39
@senorsmile Did you read the previous comments? There are workarounds.

**Comment by senorsmile** [comment] 2015-05-28 21:57
I have read the previous work arounds, but haven't gotten any of them (yet)
to properly start up the container with what I need running while enabling
me to use things like tmux via docker exec.

**Comment by razic** [comment] 2015-05-28 22:04
There is definitely a working solution to this problem, however unideal it may be. I'm not sure why you can't get it to work, especially given that you haven't posted any of your actual code. You may have better luck asking a friend or sitting in IRC. If you want to send me an email with your code, I'll be more than happy to look at it and see if I can't figure out why it doesn't work for you.

**Comment by senorsmile** [comment] 2015-05-28 22:39
I have figured out what I was doing.  For some reason I kept reading that the docker RUN had to have the 'script /dev/null' call when starting the container.  But, that's not it.  It's only required for the docker exec.  The workaround is now working for me.  Thanks!

**Comment by linas** [comment] 2015-06-08 14:50
hitting this with lxc

**Comment by jfrazelle** [comment] 2015-06-08 15:09
That's impossible you can't use exec w lxc

**Comment by linas** [comment] 2015-06-08 16:04
if you say so.

**Comment by razic** [comment] 2015-06-08 17:00
@linas Can you expand a bit? I'm curious as to why there seems to be a misunderstanding with `exec` and `lxc`.

**Comment by linas** [comment] 2015-06-08 17:05
The lxc equivalent is "lxc-attach" and when you lxc-attach to a running container, there is no tty. Same error messages, same workaround.

**Comment by jfrazelle** [comment] 2015-06-08 17:42
That is not a bug with "docker exec" then... You cannot run docker exec with the lxc driver

**Comment by razic** [comment] 2015-06-08 18:40
Great, well at least we're getting somewhere. Perhaps we can use this as a clue to fix the underlying issue.

**Comment by cyphar** [comment] 2015-06-09 14:38
The underlying issue is that we allocate a PTY outside the container's mount namespace (so the PTY devices aren't inside the container's `/dev` partition), so the pseudomagical `/proc/self/fd/{0,1,2}` symlinks are "broken". This breaks the way that things like `su` check if it's being run in a TTY --`stat(ttyname(0));`.

**Comment by LK4D4** [comment] 2015-06-09 15:27
Yes, and for main process we mount pty inside as `/dev/console`.

**Comment by cyphar** [comment] 2015-06-10 09:28
@LK4D4 Which we don't do for `docker exec` processes, right?

**Comment by LK4D4** [comment] 2015-06-10 15:46
@cyphar No, it should be in `nsenter/nsexec.c` before joining mount namespace.

**Comment by cyphar** [comment] 2015-06-10 21:09
@LK4D4 If you're referring to `namespaces/nsenter/nsenter.c`, I don't think we do. We just `dup2` the console fd over `{0,1,2}` and we don't mount it in the child's namespace. If we do mount it in the child's namespace, we should be reopening the fd so that they point to a valid symlink.

**Comment by LK4D4** [comment] 2015-06-10 21:11
@cyphar Yeah, I mean that we should, but we don't :)

**Comment by cyphar** [comment] 2015-06-10 21:52
@LK4D4 Yup. If you want, I can write a PR to fix this. We actually can't mount it as `/dev/console`, we'd have to mount it under `/dev/pts/*`. We could do this in Go `startInExistingContainer` (`nsinit/exec.go`) by changing the console path to point inside the container and just update `namespace/nsenter/nsenter.c` to open after `fork(2)`ing. Or we could do the mount shenanigans inside `namespace/nsenter/nsenter.c` and not update the Go portion at all.

**Comment by jboesl** [comment] 2015-07-03 07:57
Just wanted to note I'm hitting this issue too with nano.

**Comment by pwaller** [comment] 2015-07-03 09:26
@cyphar I suspect that your suggestion of mounting it under `/dev/pts/*` won't work. For one, you'll find you can't bind mount anything in `/dev/pts` because it's a special filesystem which doesn't allow file creation. For two, even if you *could* bind mount it, if a process inside the container created lots of pseudoterminals, it could end up colliding. That's because the `devpts` filesystem is namespaced (due to the `newinstance` option) and maintains its own numbering. I now believe may be enough information in #11462 to fix this issue.

**Comment by tiangolo** [comment] 2015-09-24 21:47
I'm not sure this is the same problem I was trying to solve, but nevertheless I will share it with you. I guess it's only relevant if you are using Windows.

I wrote a simple workaround / quick fix to allow using Docker Toolbox from Babun, it may help some of you:

https://github.com/tiangolo/babun-docker

With that you can keep using your ```docker``` commands as normal.

And if you are using Cygwin, you should use Babun, a very improved version of Cygwin.

-----

You just have to run one command to setup everything. Although I encourage you to check the source code before running any script (including mine) in your terminal.

Inside, it installs and sets up winpty, and tries to start your default docker-machine VM and set up its environment.

Maybe it gets more relevant now since newer versions of Docker Toolbox come with Git 2.5, which uses mintty and has the same problem of "cannot enable tty mode on non tty input" as in Babun.

**Comment by runcom** [comment] 2015-10-30 13:08
@cyphar are you still working on nsexec to mount pts in exec?

**Comment by cyphar** [comment] 2015-10-31 00:56
@runcom, no sorry. I looked at it, from what I can see you'd need to come up with some way of accessing `ptmx` in the `devpts` of the container in the host so you can . Unfortunately, we create then unmount it.

**Comment by sjfloat** [comment] 2015-11-14 19:48
+1

**Comment by gentili** [comment] 2015-11-22 22:42
So I'm hitting this with centos:7 and ubuntu:14.04 containers, but *not* with centos:6 image

centos:6
```
docker2:~/git/docker⟫ docker run --name "foo" -ti centos:6 /bin/bash 
[root@238531079dc9 /]# tty
/11

docker2:~⟫ docker exec -ti "foo" /bin/bash
[root@238531079dc9 /]# tty
/dev/pts/13
```
ubuntu:14.04
```
docker2:~⟫ docker run --name "foo" -ti ubuntu:14.04 /bin/bash                                                               
root@2514de9fb217:/# tty
/dev/console

docker2:~⟫ docker exec -ti "foo" /bin/bash
root@2514de9fb217:/# tty
not a tty
```

So this looks like an issue with the contents of the image rather than docker itself.  Something about the lxc hooks in the user space libs or scripts?

**Comment by pwaller** [comment] 2015-11-23 09:42
@gentili: unfortunately your discovery only amounts to a difference between the behaviour of `tty` in centos6 vs ubuntu:14.04. There is still not a functional tty inside the `exec` - just do `ls -la /proc/self/fd/0` and see that it's a broken link pointing to a pts which doesn't exist.

If you run strace, you can see the difference in behaviour. Ubuntu does this:

```
readlink("/proc/self/fd/0", "/dev/pts/12", 4095) = 11
stat("/dev/pts/12", 0x7fffa84b3a10)     = -1 ENOENT (No such file or directory)
```

(Then it iterates over a load of devices in `/dev` before finally giving up). And CentOS:

```
readlink("/proc/self/fd/0", "/dev/pts/7", 4095) = 10
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 7), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8db98c3000
write(1, "/dev/pts/7\n", 11/dev/pts/7
)            = 11
```

**Comment by cyphar** [comment] 2015-11-23 12:18
@pwaller Precisely, because the actual bug we're dealing with is that certain standard libraries assume that the symlinks in `/proc/self/fds/` must be valid symlinks. Clearly CentOS does this properly (although, I don't like the fact that in `docker run` you get `/11` which is invalid), but we need to fix this for all containers.

**Comment by pwaller** [comment] 2015-11-23 12:37
Uh, is assuming `/proc/self/fds` is a valid symlink a bug? It seems not a bug to me, but a valid thing to do, if you want to know who your stdio is connected to under normal circumstances. My interpretation of the situation is that the problem here is that the pts doesn't exist inside the container (see also: #11462).

**Comment by cyphar** [comment] 2015-11-23 12:52
The actual value of the symlink doesn't affect whether or not it works as a PTY, AFAICS it's an unnecessary restriction (a bug). But yes, the problem that causes the `/proc/self/fds` symlinks to be invalid is due to the way we deal with the pts namespace. I just don't agree that the assumption is correct (I'm fairly sure a more accurate way to check that the output is a TTY is to attempt to use the TTY-specific `ioctl`s and see if the call fails).

**Comment by linas** [comment] 2015-11-23 16:30
Hey, lots of daemons dettach from their controlling terminal, and so their /proc/self/fds/0,1,2 will be closed.  The issue here is that there is a reasonable expectation that attaching to a running container should work; i.e. the std fd's will not be closed.  

Put it a different way: the issue is not whether `/bin/bash` is performing `stat` or testing for tty's with `ioctl` -- its that users expect to be able to get a tty and run bash in it, when attaching to a container, and when the users try this, they are disappointed that it didn't work.

**Comment by gentili** [comment] 2015-11-23 17:03
@linas Agreed.  docker exec --help says:
```
  -i, --interactive=false    Keep STDIN open even if not attached
  -t, --tty=false            Allocate a pseudo-TTY
```
So I don't think it's unreasonable to expect all the usual pty related machinery including /dev/pts/ to work as you'd expect.

**Comment by mrunalp** [comment] 2015-12-08 21:28
The problem is that the tty is created outside on the host and there is no reference to it in the container like how /dev/console is setup in the primary container. One options to fix this would be allocate and bind mount the devpts from the host in to the containers. I will try that out and report back.

**Comment by hervenicol** [comment] 2016-02-23 15:49
I came to open a bug because "**docker exec -t**" does not create the TERM variable, while "**docker run -t**" does.
I guess this is the same issue!

At least the doc could mention that "**-t**" has a slightly different effect with "**run**" and with "**exec**".

**Comment by cyphar** [comment] 2016-02-23 16:16
@hervenicol That is an entirely separate issue (please open a separate issue for it). This issue is about `docker exec` not creating a TTY (this is unrelated to environment variables).

**Comment by aidanhs** [comment] 2016-02-23 16:24
@hervenicol @cyphar you're looking for #9299

**Comment by hervenicol** [comment] 2016-02-23 16:43
Thanks aidanhs. I added my comments in :)

**Comment by linas** [comment] 2016-08-10 00:49
Quoting @brauner from lxc/lxc#554 "This is a known bug in glibc and @hallyn has send a fix to glibc (https://sourceware.org/ml/libc-alpha/2016-08/msg00307.html). It just needs to be applied."

Serge's fix is surprising and elegant.

**Comment by cyphar** [comment] 2016-08-10 08:33
While @hallyn's fix helps solve the `isatty()` problem, there are other issues that we have inside runC that mean that *even with that fix* we still need some work here.

**Comment by linas** [comment] 2016-08-10 10:24
What other issues? Are you saying that you built Serge's fix, tried `docker exec -ti mydockerinstance /bin/bash` or the tmux variant, and it still doesn't work?

**Comment by cyphar** [comment] 2016-08-10 10:56
runC doesn't create consoles inside the `devpts` of the container. I'm not entirely sure whether @hallyn's fix will fix tmux for Docker (but I know that lxc correctly handles the `devpts` problem -- I'm currently working on it in runC). I haven't tested it because custom-compiling `glibc` sounds like a bad idea. :wink:

There are also larger issues that are caused by the `devpts` handling in runC that will not be fixed by `glibc` (they have to be fixed within runC).

**Comment by linas** [comment] 2016-08-10 18:03
OK. Building glibc can be a pain if you've never done it before, but its not too bad. Its not like gcc.

**Comment by b-long** [comment] 2016-08-10 21:06
@cyphar I've never done it, so I can't really speak to it, but I did find some info on the sourceware wiki, section [**Compile normally, run under new glibc** ](https://sourceware.org/glibc/wiki/Testing/Builds#Compile_normally.2C_run_under_new_glibc) : 

> Use this if you want to be able to run your application easily with the newly built libc and then again with the system libc for comparison.
> 
> Compile your test program, and invoke it with the newly loader you built. This is also how the **`make check`** runs tests. Note: if the executable under test resides in the current directory, don't forget to use `./` before the name.
> 
> Use either testrun.sh in the build directory e.g.
> 
> ```
> $ cd $HOME/build/glibc
> $ ./testrun.sh /path/to/test/application
> ```
> 

Is that at all helpful?

**Comment by j16180339887** [comment] 2016-09-06 03:34
For those who use Cygwin:
C:\cygwin64\Cygwin.bat works for me.

**Comment by icecrime** [comment] 2016-09-10 01:03
Cc @crosbymichael!

**Comment by mrunalp** [comment] 2016-09-10 03:26
This should be fixed with runc 1018

**Comment by imamassi** [comment] 2016-10-14 01:27
For this issue, I just download winpty from https://github.com/rprichard/winpty/releases (the cygwin version one), then extract it to my git bash, then prefix 'winpty' to every command that have this issue . Maybe it'll help :).

**Comment by cyphar** [comment] 2016-10-14 03:37
@imamassi `script` will also work. The fix exists within runc (opencontainers/runc#1018) but because it's quite a large change it's not been merged yet. We're hoping to get it merged by the end of the month (in time for OCI 1.0-rc2).

**Comment by ninrod** [comment] 2016-10-24 20:13
I've just got hit by this. I run an emacs daemon and connect to it with emacsclient. emacsclient gets angrey at me saying: `emacsclient: could not get terminal name`. 

I connect to my docker container running emacs daemon through docker exec. Applying @MichaelBitard's solution (`docker exec -ti `your_container_id` script -q -c "/bin/bash" /dev/null`) sealed the deal. But there are some minor colors artifacts.

**Comment by fernandoacorreia** [comment] 2016-11-01 15:06
With a container based on `debian:8.6`, to get both color support (e.g. for `ls`) and `tmux` working I had to use:

```
docker exec -it my-container env TERM=xterm script -q -c "/bin/bash" /dev/null
```

**Comment by thaJeztah** [comment] 2016-11-02 00:41
@fernandoacorreia in docker 1.13, when you add `-t`, it will automatically set `TERM=xterm` see https://github.com/docker/docker/pull/26461

**Comment by gorivishal** [comment] 2016-12-07 22:01
+1
```
$ docker exec -it newimage bash << EOF
> echo "Test"
> EOF
```

**Comment by cyphar** [comment] 2016-12-07 23:05
opencotnainers/runc#1018 has been merged. This can be closed as soon as Docker vendors the latest commit of `runc`.

**Comment by razic** [comment] 2016-12-08 00:22
No way!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 🎊 🎉

**Comment by thaJeztah** [comment] 2016-12-08 12:30
ping @mlaventure ^^

**Comment by ninrod** [comment] 2016-12-08 13:36
hi @cyphar, little lost here. So will this be fixed in docker 1.13?

**Comment by cyphar** [comment] 2016-12-08 13:49
@ninrod No, because it's too late for the changes to be merged into 1.13 (the RCs have already been released). I would expect it will be fixed in 1.14 (when Docker starts using the newer version of runC).

**Comment by larsks** [comment] 2017-03-18 14:49
Does anyone know if the fix that @cyphar referenced [earlier](https://github.com/docker/docker/issues/8755#issuecomment-265602315) has made it into a Docker release? I'm running `Docker version 17.03.0-ce, build 60ccb22` and the connection created with `docker exec` is still not a tty, so programs that require a tty fail to run.

**Comment by cyphar** [comment] 2017-03-18 19:34
I believe that opencontainers/runc#1356 was also blocking this, since @crosbymichael mentioned that `docker exec` had some issues with the new console-handling code.

**Comment by mlaventure** [comment] 2017-03-20 16:04
the `containerd v0.2.x` branch in uncompatible with master runc. This change can't just be cherry-picked in the current version that `containerd` depends on.

We're mostly on maintenance mode on `v0.2.x` until `1.0` is ready, and given there seem to be a workaround, this is not critical enough IMHO.

But if someone is willing to do the update on the `v0.2.x` branch and test that again docker, a PR is more than welcome! :angel:

**Comment by crosbymichael** [comment] 2017-03-20 17:51
@mlaventure I think its a simple fix to change `v0.2.x` to support this.  We need the testing so its worthwhile to integrate it into that branch.

**Comment by ninrod** [comment] 2017-03-20 22:01
Sorry, can you verify if I follow correctly Is a fix for this expected to land in the next official docker release?

**Comment by razic** [comment] 2017-03-20 23:34
Hello everyone, I'm going to attempt to put some time into this, and see if I can get the fixes (wherever they may be required) in place, so we can close this issue once and for all. I'll report back here with an update as soon as possible.

**Comment by crosbymichael** [comment] 2017-03-21 16:53
@ninrod i cannot guarantee anything but we will try

**Comment by razic** [comment] 2017-03-21 17:03
I spent a couple hours on this last night, mostly to get over the learning curve. I think I understand the majority of what I need to complete this. Most of the work is actually already done, and @crosbymichael has graciously offered to provide guidance as necessary. I'll give another update later tonight.

**Comment by razic** [comment] 2017-03-22 05:09
Ok so a quick update; I think I can get this finished in a few days...

At this point I have my development environment up and running, such that I can iterate on the `containerd` codebase.

However, I've become stuck; I'll ping @crosbymichael tomorrow for help, but I can't seem to start an OCI bundle that was created via `runc spec` with `ctr containers start`... and I need to be able to use `ctr containers exec` to test my changes.

I'm using the docs here https://github.com/docker/containerd/blob/v0.2.x/docs/bundle.md to create the OCI bundle. I'm able to run the bundle using `runc start` (version v0.0.9), but as mentioned when trying to start the container using `ctr`, I get the following error:

```bash
$ ctr containers start redis $PWD
[ctr] rpc error: code = 2 desc = shim error: context deadline exceeded
```

Once I get this working, dropping in the changes should be as simple as consuming the https://github.com/crosbymichael/go-runc bindings that already support the new console functionality.

**Comment by ninrod** [comment] 2017-03-22 15:30
@razic this stuff is so advanced that I can't follow a word of what you've just said, but sounds promising. I'm eagerly waiting for this. Thanks for working on it.

**Comment by razic** [comment] 2017-03-24 22:01
Quick update... I was able to get a container running via `ctr`, so I think I may have gotten over that hump. I've been learning a lot about how the whole thing works (containerd-shim etc). I think I now have everything I need to be able to test my changes once I implement them. Will provide another update soon.

**Comment by crosbymichael** [comment] 2017-05-08 23:14
Fixed by #33007

**Closed by crosbymichael** 2017-05-08 23:14 UTC
Labels: area/runtime, exp/expert, kind/enhancement, status/claimed

**Comment by michaelsbradleyjr** [comment] 2017-05-08 23:16
And there was much rejoicing.

**Comment by ninrod** [comment] 2017-05-08 23:41
awesome!!!! please gentleman, in what docker version can I grab this fix?

**Comment by thaJeztah** [comment] 2017-05-09 12:49
This will be in 17.06

**Comment by LinusU** [comment] 2017-05-17 16:37
Will this land in an edge release before that? Was it landed in 17.05.0-ce-mac11? Any pointers on where to check this? :)

**Comment by thaJeztah** [comment] 2017-05-17 20:01
No, this won't be in 17.05, only 17.06 and upward

**Comment by LinusU** [comment] 2017-05-17 21:17
Okay, thank you! Is there a release date set? Sorry for asking so many questions :) tried googling first but didn't find it, maybe I just a missed it thoug...

**Comment by thaJeztah** [comment] 2017-05-17 21:35
The version is YY.MM, and we target first week of the month, so first week of June, with release candidates before that

**Comment by LinusU** [comment] 2017-05-18 09:31
Ah, that's great to know, thank you!

**Comment by zrml** [comment] 2017-05-19 10:27
Great news @thaJeztah !

**Comment by ninrod** [comment] 2017-06-20 23:18
Hi @thaJeztah, is 17.06 going to land in in june or will it be rescheduled for july? if so, will it be 17.07 instead? just wan't to be sure regarding the version that will have this fix landed.

**Comment by razic** [comment] 2017-06-28 22:48
```bash
zacharys-pro:dev razic$ docker run --rm -t -d ubuntu bash
83c292c8e2d13d1b1a8b34680f3fb95c2b2b3fef71d4ce2b6e12c954ae50965a
zacharys-pro:dev razic$ Docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
83c292c8e2d1        ubuntu              "bash"              2 seconds ago       Up 1 second                             xenodochial_bardeen
zacharys-pro:dev razic$ docker exec -ti xenodochial_bardeen tty
/dev/pts/1
zacharys-pro:dev razic$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

Great work everyone. Thank you very much.

**Comment by ninrod** [comment] 2017-06-28 23:57
is this released? where?

**Comment by razic** [comment] 2017-06-29 00:01
@ninrod I've included the version information in the output. This is fixed in version `17.06.0-ce`, which is the most current stable version. If you are using Docker for Mac, you can simply restart the application, and you should be prompted to upgrade.

**Comment by ninrod** [comment] 2017-06-29 00:44
Oh. but this is not ready yet for docker for windows, right?

**Comment by zrml** [comment] 2017-06-29 09:18
just tested it on Docker-for-Mac latest and it works. I'm a happy man :-)
