### ISSUE TITLE
/etc/hosts set IPv6 address (::1) even when IPv6 is disabled in container

### ISSUE THREAD

**Issue by hubo1016** [moby/moby#37616] opened 2018-08-09 09:57 UTC
**Description**

/etc/hosts set ::1 for localhost even when IPv6 is not enabled in the container (so ::1 is not set on `lo` interface). This is causing "network unreachable" or "cannot assign IP address" errors when connecting `localhost`.

**Steps to reproduce the issue:**

1. Use default configuration (ipv6 is not enabled)
2. Create a container
3. Use `ip addr show` to show addresses on `lo`
4. Use `cat /etc/hosts` to show hosts

**Describe the results you received:**

::1 set in /etc/hosts

**Describe the results you expected:**

::1 not set in /etc/hosts, or ::1 set on `lo` interface

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 39
 Running: 10
 Paused: 0
 Stopped: 29
Images: 932
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: docker-252:33-422369-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 68.7GB
 Data Space Total: 107.4GB
 Data Space Available: 38.68GB
 Metadata Space Used: 106.8MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.041GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.641GiB
Name: yz-
ID: BMJD:GZXY:5HPW:TFGK:EBLU:EGVT:AZSX:DQLU:4DFE:WS6X:PZX3:HB47
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 94
 Goroutines: 105
 System Time: 2018-08-09T17:56:15.344094193+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 jdocker.me
 127.0.0.0/8
Live Restore Enabled: true

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7.4

**Comment by rddesmond** [comment] 2019-03-05 15:33
Duplicates #35954

**Comment by thaJeztah** [comment] 2022-03-26 21:27
yes; duplicate of https://github.com/moby/moby/issues/35954

**Closed by thaJeztah** 2022-03-26 21:27 UTC
Labels: area/networking
