### ISSUE TITLE
docker build hanging on ubuntu 16.04.3 (kernel 4.10)

### ISSUE THREAD

**Issue by jenningsloy318** [moby/moby#34412] opened 2017-08-06 11:50 UTC
I have upgrade my box to ubuntu 16.04.3 which ships with kernel 4.10, now I have troubles when dealing with docker build the docker images. 

I have Dockerfile which contains the line `RUN apt update && apt install wget`, and this will result in haning after the packages downloaded. 

```
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [43.0 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [406 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.8 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [187 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [2931 B]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [209 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [762 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.3 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [647 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [17.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [4930 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [6231 B]
Fetched 24.2 MB in 2min 23s (169 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
8 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
   wget (1.17.1-1ubuntu1.2)
The following packages will be upgraded:
   apt (1.2.20 => 1.2.24)
   libapt-pkg5.0 (1.2.20 => 1.2.24)
2 upgraded, 7 newly installed, 0 to remove and 6 not upgraded.
Need to get 4110 kB of archives.
After this operation, 7298 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapt-pkg5.0 amd64 1.2.24 [707 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 apt amd64 1.2.24 [1043 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapt-inst2.0 amd64 1.2.24 [55.4 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 apt-utils amd64 1.2.24 [197 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libidn11 amd64 1.32-3ubuntu1.1 [45.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libssl1.0.0 amd64 1.0.2g-1ubuntu4.8 [1081 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 openssl amd64 1.0.2g-1ubuntu4.8 [492 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/main amd64 ca-certificates all 20160104ubuntu1 [191 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 wget amd64 1.17.1-1ubuntu1.2 [298 kB]

debconf: delaying package configuration, since apt-utils is not installed
```

and this will stuck and the intermediate docker images are still running when I ctrl+c to kill the current build process. and these container will not exit except restarting docker engine. 

also I have tried to build the docker images on ubuntu 16.04.2/16.04.1 (kernel 4.4/4.8), there is no such issue.

I tried docker engine from 1.12.1 ~1.12.6 ~ 17.03 ~17.05, all of them have same problems on 4.10 kernel but no issue on 4.8/4.4.

**Comment by thaJeztah** [comment] 2017-08-06 14:22
Can you add the output of `docker version` and `docker info`?

Are you using the overlay or overlay2 graph driver? If so, I suspect this may be a duplicate of (or related to) https://github.com/moby/moby/issues/33733 (see https://github.com/moby/moby/issues/33733#issuecomment-309929136). This may be due to a change in the default kernel configuration for kernel 4.10.

We're looking at addressing this automatically through https://github.com/moby/moby/pull/34342, but the other links may provide information on how to address this by updating the kernel configuration.

Let me know if that helps!

**Comment by jenningsloy318** [comment] 2017-08-07 02:06
Here is the info:
```
docker info
Containers: 51
 Running: 21
 Paused: 0
 Stopped: 30
Images: 92
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 259
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.10.0-27-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.79 GiB
Name: cnpvgl56588417
ID: RBIH:KI5N:HFUQ:JBTQ:ENOS:QLZV:T3T2:TGXT:VM5H:SWVO:ARDN:W33P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 193
 Goroutines: 120
 System Time: 2017-08-07T10:04:49.540662071+08:00
 EventsListeners: 0
Http Proxy: http://proxy:8080
Https Proxy: http://proxy:8080
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

and 
```
#docker version 
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
```
and OS info
```
#uname -a
Linux cnpvgl56588417 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AkihiroSuda** [comment] 2017-08-07 02:56
https://github.com/moby/moby/issues/34361 might be related? (AUFS+XFS)

**Comment by jenningsloy318** [comment] 2017-08-07 06:58
but I same docker engine, I can buid on kernel 4.4/4.8

**Comment by AkihiroSuda** [comment] 2017-08-07 07:11
Yes, #34361 seems recent regression in Ubuntu kernel 4.10, and your situation seems a dupe of #34361.

Can we close this issue and continue the discussion in #34361?

**Comment by thaJeztah** [comment] 2017-08-07 07:41
Let's close this one as a duplicate of https://github.com/moby/moby/issues/34361

Thanks!

**Closed by thaJeztah** 2017-08-07 07:41 UTC
Labels: area/builder, area/storage/aufs
