### ISSUE TITLE
Docker prune untags images in use

### ISSUE THREAD

**Issue by hakashya** [moby/moby#42761] opened 2021-08-19 08:34 UTC
**Description**

`docker system prune -f -a` untags the images having local tags, even when that image is in use by a running container.

**Steps to reproduce the issue:**
1. Download images with remote tags (using `docker pull`).
2. Tag the aforementioned image with a local tag, using `docker tag <image> localimage:localtag`
3. Create and run a container using that image, using `docker run`
4. Now run `docker system prune -f -a`
5. `docker ps` and `docker image ls` will now show that the local tags are missing, and is replaced with image ID instead.

**Describe the results you received:**
For `docker image ls`, we see that images with local tags are removed after pruning:
```
root@myVM:/# docker image ls
REPOSITORY                  TAG       IMAGE ID       CREATED        SIZE
localtag.azurecr.io/repro   node      c66552d59c4b   11 hours ago   907MB
localtag.azurecr.io/repro   nginx     dd34e67e3371   45 hours ago   133MB
localtag.azurecr.io/repro   alpine    021b3423115f   12 days ago    5.59MB
localtag.azurecr.io/repro   ubuntu    1318b700e415   3 weeks ago    72.8MB
```

For `docker ps`, we can see that the image tags are replaced with the image ID.
```
root@myVM:/# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS     NAMES
b058746daf9a   localtag.azurecr.io/repro:alpine   "/bin/sh"                11 minutes ago   Up 11 minutes             eloquent_blackburn
5c9e24b1a3c2   c66552d59c4b                       "docker-entrypoint.s…"   11 minutes ago   Up 11 minutes             vigorous_leavitt
c9e2b5f00c54   dd34e67e3371                       "/docker-entrypoint.…"   11 minutes ago   Up 11 minutes   80/tcp    unruffled_borg
c6e7530272b7   1318b700e415                       "bash"                   11 minutes ago   Up 11 minutes             inspiring_torvalds
```

**Describe the results you expected:**
For `docker image ls`, we should see:
```
root@myVM:/# docker image ls
REPOSITORY                  TAG       IMAGE ID       CREATED        SIZE
custom-node                 latest    c66552d59c4b   11 hours ago   907MB
localtag.azurecr.io/repro   node      c66552d59c4b   11 hours ago   907MB
servernginx                 latest    dd34e67e3371   45 hours ago   133MB
localtag.azurecr.io/repro   nginx     dd34e67e3371   45 hours ago   133MB
localtag.azurecr.io/repro   alpine    021b3423115f   12 days ago    5.59MB
osubuntu                    latest    1318b700e415   3 weeks ago    72.8MB
localtag.azurecr.io/repro   ubuntu    1318b700e415   3 weeks ago    72.8MB
localtag.azurecr.io/repro   hworld    d1165f221234   5 months ago   13.3kB

```
And for `docker ps`, we should be seeing:
```
root@myVM:/# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS         PORTS     NAMES
b058746daf9a   localtag.azurecr.io/repro:alpine   "/bin/sh"                6 minutes ago   Up 6 minutes             eloquent_blackburn
5c9e24b1a3c2   custom-node                        "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes             vigorous_leavitt
c9e2b5f00c54   servernginx                        "/docker-entrypoint.…"   7 minutes ago   Up 7 minutes   80/tcp    unruffled_borg
c6e7530272b7   osubuntu                           "bash"                   7 minutes ago   Up 7 minutes             inspiring_torvalds
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue can be consistently reproduced by following the above steps. 

The expectation to see the right tags (instead of the image ID) stems from the fact that pruning was supposed to remove containers and images not in use. However, it untags the containers that are still in use.

It is also worthy to note that `docker system prune -f -a` returns the following output, which specifies the untagging action:
```
root@myVM:/# docker system prune -f -a
Deleted Containers:
5354249855d28bc003c4af76f32597a22d3957fe30ee54a45dfdaf9a71c3b39e

Deleted Images:
untagged: custom-node:latest
untagged: localtag.azurecr.io/repro:hworld
untagged: localtag.azurecr.io/repro@sha256:1b26826f602946860c279fce658f31050cff2c596583af237d971f4629b57792
deleted: sha256:d1165f2212346b2bab48cb01c1e39ee8ad1be46b87873d9ca7a4e434980a7726
deleted: sha256:f22b99068db93900abe17f7f5e09ec775c2826ecfe9db961fea68293744144bd
untagged: osubuntu:latest
untagged: servernginx:latest

Total reclaimed space: 13.34kB
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1039-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: myVM
 ID: Y2OV:NR4I:4KZM:C4S3:26ZQ:7CDK:BIHV:4M6R:CARH:L6ZQ:ASAS:JYSK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Running on Azure IaaS Ubuntu VM (reproducible in other environments as well).

**Comment by thaJeztah** [comment] 2021-08-19 16:44
I think this may be a duplicate of https://github.com/moby/moby/issues/36295

**Closed** 2021-11-08 11:31 UTC
