### ISSUE TITLE
Swarm Mode publish IP address

### ISSUE THREAD

**Issue by calh** [moby/moby#29072] opened 2016-12-02 16:00 UTC
Feature request:  Swarm Mode publish IP address

Similar to the `docker run` publish feature, I'd really like to see docker services with the ability to expose an `ip:hostPort:containerPort` combination from the `docker service create` command line.

My use case, is that I'm using keepalived with a VRRP IP address, and I need to redirect ports directly into swarm's LVS load balancer.  I'm currently using a work-around with a `notify_master` script in keepalived that injects an iptables rule, similar to how docker < 1.10 did this.  It seems to work well enough, but it would be quite handy to have this feature directly from the docker command line.

Here's a quick example snippet of what I'm doing:

keepalived.conf:
```
virtual_address {
   192.168.1.10
}
notify_master "/etc/keepalived/notify.sh"
```

notify.sh:
```
iptables -t nat -A DOCKER-INGRESS \
  -d 192.168.1.10 ! -i docker0 -p tcp \
  -m tcp --dport 80 -j DNAT --to-destination 172.18.0.2:8080
```

It would be a lot easier if I could just  `docker service create --name web -p 192.168.1.10:80:8080` 

Thank you for considering this!

**Comment by thaJeztah** [comment] 2017-07-21 23:34
Looks like this is a duplicate of https://github.com/moby/moby/issues/26696, so let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2017-07-21 23:34 UTC
Labels: area/swarm
