### ISSUE TITLE
Maximum length of container/service labels?

### ISSUE THREAD

**Issue by bitsofinfo** [moby/moby#36104] opened 2018-01-24 16:50 UTC
What is the maximum number of characters permitted for a docker container/service `--label` length?

**Comment by thaJeztah** [comment] 2018-01-26 02:12
There is no maximum length, but there's been an issue where longer lines where not properly read when loading the Dockerfile (resolved through https://github.com/moby/moby/pull/35429); see https://github.com/docker/for-linux/issues/157 / https://github.com/docker/for-mac/issues/2208

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-01-26 02:12 UTC

**Comment by bitsofinfo** [comment] 2018-01-26 02:19
Thanks, only asked here because I could not see it documented in the docs anywhere.

**Comment by bitsofinfo** [comment] 2018-01-26 02:20
And just to clarify I'm speaking of labels applied to services/containers at runtime, not in the builds of images
