### ISSUE TITLE
Unable to detach from container

### ISSUE THREAD

**Issue by mikhirev** [moby/moby#35491] opened 2017-11-14 12:15 UTC
**Description**

When docker container is attached by `run` command without `-d`, `-i` and `-t` options, `attach` command or `start` command with `-a` option and without `-i` option, there's no way to detach except killing client with SIGKILL. `ctrl-pq` or other key sequences specified with `--detach-keys` don't work.

**Steps to reproduce the issue:**
1. `docker run debian:stable sleep 100`
2. Try typing `^P^Q`

**Describe the results you received:**

Client still attached to the container.

**Describe the results you expected:**

Client detached from the container.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.71GiB
Name: dmikhirev
ID: WZKK:5YLX:6S5Z:MJKU:A7JY:E32N:2ALR:QIND:JVGD:HZQO:6FEM:SN2P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2017-11-14 15:49
Yes, this is currently expected; since there is no `-i` or `-t` set on the `docker run`, there's nothing listening for the keystrokes, so they are not monitored.

I was discussing with @vdemeester and possibly it's possible to _listen_ for the keystrokes, without forwarding them to the container (if `-it` is not set), but that would have to be investigated / tested.

Let me close this issue, because this is currently the expected behavior, but feel free to open a feature request in the https://github.com/docker/cli repository, which is where this would have to be implemented.

**Closed by thaJeztah** 2017-11-14 15:49 UTC
Labels: version/17.05

**Comment by jcrben** [comment] 2019-02-08 07:59
It seems like this should be mentioned at https://docs.docker.com/engine/reference/commandline/attach/
