### ISSUE TITLE
docker-containerd-current can't be restart automatically when it is killed

### ISSUE THREAD

**Issue by ryanlyy** [moby/moby#33978] opened 2017-07-06 08:50 UTC
---------------------------------------------------
BUG REPORT INFORMATION
**Description**
In 1.12.6, when I kill docker-containerd-current, it can't be restarted by dockerd-current. it works in 1.11 and 1.13. is it broken in 1.12.6 or is there anything configured wrong?

**Steps to reproduce the issue:**
1. pkill -9 docker-containerd-current
2. ps -ef | grep docker-containerd-current

NOTE: systemctl restart docker can start docker-containerd-current.

**Describe the results you received:**
docker-containerd-current is not restarted after it is killed

**Describe the results you expected:**
docker-containerd-current can be restarted after it is killed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

[root@fedora docker]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-6.gitae7d637.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      ae7d637/1.12.6
 Built:           Mon Jan 30 16:15:28 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-6.gitae7d637.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      ae7d637/1.12.6
 Built:           Mon Jan 30 16:15:28 2017
 OS/Arch:         linux/amd64
**Output of `docker info`:**

[root@fedora docker]# docker info
Containers: 148
 Running: 77
 Paused: 0
 Stopped: 71
Images: 48
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-306843-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 12.49 GB
 Data Space Total: 107.4 GB
 Data Space Available: 94.88 GB
 Metadata Space Used: 27.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.12 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp
Kernel Version: 4.11.3-200.fc25.x86_64
Operating System: Fedora 25 (Server Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 12
Total Memory: 23.54 GiB
Name: fedora
ID: DGJF:OMRQ:CGVB:ZBUN:R27S:T5NM:W6VH:76ID:RJQP:LLIS:S4G3:JR5Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 430
 Goroutines: 339
 System Time: 2017-07-06T07:38:52.819258642-04:00
 EventsListeners: 1
Http Proxy: http://127.0.0.1:8000
Https Proxy: http://127.0.0.1:8000
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora

**Comment by thaJeztah** [comment] 2017-07-08 10:21
The `docker-current` package is the Red Hat fork of Docker, and contains many modifications from the code that is maintained here. Also, docker 1.12 is an old version of docker that is no longer supported.

I'm closing this issue because of the above, but let me know if you're able to reproduce this on the current version of the official docker packages (https://docs.docker.com/engine/installation/linux/docker-ce/fedora/), also feel free to continue the conversation after I closed the issue

**Closed by thaJeztah** 2017-07-08 10:21 UTC
Labels: version/1.12
