### ISSUE TITLE
Support "--from" for ADD in multi stage build

### ISSUE THREAD

**Issue by Zenithar** [moby/moby#36759] opened 2018-04-01 19:31 UTC
Hello,

It would be great to support "--from" like COPY but for ADD statement.
I build image in 2 separated images : 1 for compilation that output au rootfs archive, and another which ADD rootfs.tar as / from a scratch image.
I think that MSB is a good idea but ADD con't take "--from" parameter.

Sample Dockerfile used (https://gist.github.com/Zenithar/9209968).

Regards,

**Comment by Zenithar** [comment] 2018-04-01 19:42
I tried to do it like this
 
```Dockerfile
COPY --from=build /rootfs.tar.xz /
ADD /rootfs.tar.xz /
```
But it does not work.

**Comment by thaJeztah** [comment] 2018-05-08 19:26
@tonistiigi wdyt? Or would it make more sense to extract in an intermediate build stage ?

**Comment by tonistiigi** [comment] 2018-05-08 21:10
@thaJeztah I don't think this is needed. We should just keep the permissions on `COPY --from`, all these cases can be handled without specific magic syntax.

**Comment by thaJeztah** [comment] 2018-05-22 12:30
Opened a proposal for preserving ownership when copying between stages in a multi-stage build: https://github.com/moby/moby/issues/37123

**Comment by sschuberth** [comment] 2021-08-04 08:10
BTW, this seems to be a duplicate of https://github.com/moby/moby/issues/33811.

**Comment by thaJeztah** [comment] 2021-08-04 08:49
Ah, yes you're right, and that has a more detailed discussion; let me close this one in favor of https://github.com/moby/moby/issues/33811

**Closed by thaJeztah** 2021-08-04 08:49 UTC
Labels: area/builder, kind/feature
