### ISSUE TITLE
[Bug] Port forwarding doesn't happen correctly 17.04.0-ce

### ISSUE THREAD

**Issue by adityacs** [moby/moby#33221] opened 2017-05-16 11:06 UTC
When we create service with "-p $port:$port" port forwarding is not working when the container is created.

**Steps to reproduce the issue:**
use below compose file
```
version: '3'
services:
  portainer:
    image: portainer/portainer
    hostname: portainer
    networks:
     - ext-proxy
    ports:
     - "9000:9000"
    volumes:
     - portainer:/data
     - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock
    deploy:
      placement:
        constraints:
         - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

volumes:
  portainer:
    driver: convoy

networks:
  ext-proxy:
    external: true
```

**Describe the results you received:**
![image](https://cloud.githubusercontent.com/assets/7681197/26103058/6aa6fca6-3a55-11e7-8f1d-c975dffe48a6.png)

**Describe the results you expected:**

ports forwarded should visible

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr 26 23:09:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr 26 23:09:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.12-coreos
Operating System: Container Linux by CoreOS 1395.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.865GiB
Name: blrswarmdev002
ID: MPWK:IK7C:MQQJ:LBVI:M7AD:VPTO:6OGV:QTQ6:CZPP:PLCW:LJNJ:FHRR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 registry.igloo.vztelematics.in:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-05-16 12:21
This is the expected behaviour; when deploying `swarm` services, the ports of individual containers backing the service are not published, but published through a load-balancer. For that reason, the published ports do not show up for the _container_, but for the _service_.

For example;

```bash
$ docker service create --name web -p 80:80 nginx:alpine
muvukxhp14569pq3zwmsepfwf
```

When looking at the output of `docker ps`, the published port is not visible;

```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
03cc3fb0e5d9        nginx:alpine        "nginx -g 'daemon ..."   10 seconds ago      Up 9 seconds        80/tcp              web.1.pi7sb3lovwus2e5c9h68uer8y
```

Looking at the output of `docker service ls` on the other hand;

```bash
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
muvukxhp1456        web                 replicated          1/1                 nginx:alpine        *:80->80/tcp
```

Shows that the port is published. The `*:` in this case indicates that the port is published through the "routing mesh", and is available on any node in the swarm cluster.

I'll close this issue, because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-05-16 12:21 UTC
Labels: version/17.04

**Comment by adityacs** [comment] 2017-05-16 12:31
@thaJeztah Got it. Thanks
