### ISSUE TITLE
Legacy plugin openvswitch of type NetworkDriver is not supported in swarm mode

### ISSUE THREAD

**Issue by balioune** [moby/moby#33570] opened 2017-06-07 15:28 UTC
**Description**

I'm getting some error when installing ovs driver for libnetwork in one single host following this link http://docs.openvswitch.org/en/latest/howto/docker/

Network creation "docker network create -d openvswitch --subnet=192.168.1.0/24 foo" returns this error
"Error response from daemon: datastore for scope "global" is not initialized".

I initialize swarm mode using "docker swarm init" to solve that but the network creation fails again with this message
"Error response from daemon: rpc error: code = 3 desc = legacy plugin openvswitch of type NetworkDriver is not supported in swarm mode"

Any suggestion about what could cause these errors ?

**Output of `docker version`:**

```
docker --version
Docker version 17.03.1-ce, build c6d412e
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 992.2 MiB
Name: ubuntu-xenial
ID: YB2U:E2I2:XB5U:2XG5:FXLF:QB3I:6RK3:VOIT:EMCA:DSGB:D3G2:HGSQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Comment by thaJeztah** [comment] 2017-06-07 16:21
Yes, it looks like that plugin requires an external k/v store (configured using the `--cluster-store`, and related, options on the daemon).

Docker swarm mode uses a built-in cluster-store, which cannot be used together with the legacy external k/v.

I would suggest contacting the developer of that plugin to see if they're working on converting it to a v2 plugin. Alternatively, if you don't use Swarm mode (`docker service create` etc), disable swarm-mode, and configure an external k/v store/discovery service. However if you're only looking for overlay networking; docker swarm mode provides overlay networks out of the box, without requiring you to install a plugin.

I'm closing this issue, because this is not a bug in docker, but feel free to continue the conversation

**Closed by thaJeztah** 2017-06-07 16:21 UTC
Labels: area/networking, area/swarm

**Comment by balioune** [comment] 2017-06-08 12:16
Thanks for these information @thaJeztah.
I'm using the openvswitch driver  and if I understand, we can not use this driver in swarm cluster ?
Please cloud you tell me how to build external k/v store for docker hosts ?

**Comment by thaJeztah** [comment] 2017-06-08 12:36
And here's more information https://docs.docker.com/swarm/discovery/#use-tls-with-distributed-keyvalue-discovery

**Comment by balioune** [comment] 2017-06-08 14:23
Thanks @thaJeztah it works!

**Comment by balioune** [comment] 2017-06-09 13:23
@thaJeztah I would like to know is there a way to retrieve information of docker host from the consul server ?
