### ISSUE TITLE
Pulling images form the repository

### ISSUE THREAD

**Issue by rzvn2600** [moby/moby#34834] opened 2017-09-13 13:25 UTC
**Description**

**Steps to reproduce the issue:**
1. Searching the image with docker search

15mbp-12316:.kube razvang$ docker search ansible
NAME                                    DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
williamyeh/ansible                      Docker images for Ansible software, instal...   128                  [OK]
ansible/centos7-ansible                 Ansible on Centos7                              100                  [OK]
ansible/ubuntu14.04-ansible             Ubuntu 14.04 LTS with ansible                   86                   [OK]
ansible/ansible                         Images used for the automated testing of A...   78                   [OK]
generik/ansible                         Ansible in a docker on Alpine Linux includ...   13                   [OK]
leowmjw/ubuntu-ansible-tower            Ansible Tower on Ubuntu 14.04 (10 nodes Tr...   9
geerlingguy/docker-ubuntu1604-ansible   Ubuntu 16.04 LTS (Xenial) Docker container...   8                    [OK]
geerlingguy/docker-centos7-ansible      CentOS 7.x Docker container for Ansible pl...   3                    [OK]
hypoport/ansible                        A simple containerized Ansible environment      3                    [OK]
ansible/ansible-container-builder       The builder image for ansible-container. S...   2
ansiblecheck/ansiblecheck               A One Stop Solution For Checking Your Ansi...   2                    [OK]
weldpua2008/docker-ansible              Images ready for Ansible installation           2                    [OK]
scottmiller171/ansible-docker-images    Images with Ansible pre-installed               1                    [OK]
webdevops/ansible                       Ansible image for CentOS, Ubunty, Debian a...   1                    [OK]
cultureamp/docker-ansible               Ansible control machine as a container          1                    [OK]
trinitronx/ansible-base                 Base container for running ansible plays. ...   1
ju2wheels/ansible                       Various Linux distribution images with Ans...   0                    [OK]
platformengineering/ansible             Ansible images                                  0
ansibleplaybookbundle/s2i-apb           S2I builder image for Ansible-Playbook-Bundle   0                    [OK]
commonms/ansible                        Docker image for ansible.                       0                    [OK]
os33/concourse-ansible-resource                                                         0
teamidefix/ansible                                                                      0
hyperized/ansible-docker-image          Basic Ansible Docker images                     0                    [OK]
os33/ansible                            Container for doing ansible things              0
jcpowermac/alpine-ansible-ssh           OpenSSH and Ansible on Alpine                   0                    [OK]

2. Choosing an image that I want to pull and performing docker pull "image name"

15mbp-12316:.kube razvang$ docker pull ansible/ansible
Using default tag: latest
Error response from daemon: manifest for ansible/ansible:latest not found
15mbp-12316:.kube razvang$

3. Trying to pull another image, with simple single name definition like debian:

15mbp-12316:.kube razvang$ docker pull debian
Using default tag: latest
latest: Pulling from library/debian
219d2e45b4af: Pull complete
Digest: sha256:126052225b62db18c32f03a4462a92fad2ef243c6509371edb82a2298087b12c
Status: Downloaded newer image for debian:latest
15mbp-12316:.kube razvang$ docker search ansible

**Describe the results you received:**
While trying to pull the image, the daemon responded that the image it just searched is not found...

**Describe the results you expected:**

I expect to download the image from the search results

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
15mbp-12316:.kube razvang$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
15mbp-12316:.kube razvang$
```

**Output of `docker info`:**

```
15mbp-12316:.kube razvang$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
15mbp-12316:.kube razvang$ docker info
Containers: 106
 Running: 0
 Paused: 0
 Stopped: 106
Images: 77
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 5
Total Memory: 3.855GiB
Name: moby
ID: XB3Z:Q7FO:ZBOT:AS3I:G6BV:V6E3:PKCN:OH4T:NU5V:4PRF:GPMH:JCSV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-09-13T13:20:18.374450853Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

15mbp-12316:.kube razvang$```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am running the docker service on top of macos, using the official docker for macos

Same issue with docker running on linux 👍 

```
Run 'docker COMMAND --help' for more information on a command.
$ docker search ansible
NAME                                    DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
williamyeh/ansible                      Docker images for Ansible software, instal...   128                  [OK]
ansible/centos7-ansible                 Ansible on Centos7                              100                  [OK]
ansible/ubuntu14.04-ansible             Ubuntu 14.04 LTS with ansible                   86                   [OK]
ansible/ansible                         Images used for the automated testing of A...   78                   [OK]
generik/ansible                         Ansible in a docker on Alpine Linux includ...   13                   [OK]
leowmjw/ubuntu-ansible-tower            Ansible Tower on Ubuntu 14.04 (10 nodes Tr...   9
geerlingguy/docker-ubuntu1604-ansible   Ubuntu 16.04 LTS (Xenial) Docker container...   8                    [OK]
geerlingguy/docker-centos7-ansible      CentOS 7.x Docker container for Ansible pl...   3                    [OK]
hypoport/ansible                        A simple containerized Ansible environment      3                    [OK]
weldpua2008/docker-ansible              Images ready for Ansible installation           2                    [OK]
ansiblecheck/ansiblecheck               A One Stop Solution For Checking Your Ansi...   2                    [OK]
ansible/ansible-container-builder       The builder image for ansible-container. S...   2
cultureamp/docker-ansible               Ansible control machine as a container          1                    [OK]
webdevops/ansible                       Ansible image for CentOS, Ubunty, Debian a...   1                    [OK]
trinitronx/ansible-base                 Base container for running ansible plays. ...   1
scottmiller171/ansible-docker-images    Images with Ansible pre-installed               1                    [OK]
commonms/ansible                        Docker image for ansible.                       0                    [OK]
os33/concourse-ansible-resource                                                         0
hyperized/ansible-docker-image          Basic Ansible Docker images                     0                    [OK]
os33/ansible                            Container for doing ansible things              0
jcpowermac/alpine-ansible-ssh           OpenSSH and Ansible on Alpine                   0                    [OK]
ju2wheels/ansible                       Various Linux distribution images with Ans...   0                    [OK]
teamidefix/ansible                                                                      0
ansibleplaybookbundle/s2i-apb           S2I builder image for Ansible-Playbook-Bundle   0                    [OK]
platformengineering/ansible             Ansible images                                  0
$ docker pull ansible/ansible
Using default tag: latest
Pulling repository docker.io/ansible/ansible
Tag latest not found in repository docker.io/ansible/ansible
$ docker pull ansible
Using default tag: latest
Pulling repository docker.io/library/ansible
Error: image library/ansible not found
$
$
$
$
$ docker pull debian
Using default tag: latest
latest: Pulling from library/debian
219d2e45b4af: Pull complete
Digest: sha256:126052225b62db18c32f03a4462a92fad2ef243c6509371edb82a2298087b12c
Status: Downloaded newer image for debian:latest
$```

**Comment by thaJeztah** [comment] 2017-09-13 13:35
If you don't specify a "tag" when running `docker pull`, the default (`:latest`) tag is used.

The ansible/ansible image does not appear to have a `:latest` tag (see the overview of available tags for that image on Docker Hub here: https://hub.docker.com/r/ansible/ansible/tags/), therefore pulling fails:

```bash
$ docker pull ansible/ansible
Using default tag: latest
Error response from daemon: manifest for ansible/ansible:latest not found
```

If you _do_ specify an existing tag, pulling works:

```bash
$ docker pull ansible/ansible:ubuntu1604
ubuntu1604: Pulling from ansible/ansible
75c416ea735c: Pull complete
c6ff40b6d658: Pull complete
a7050fc1f338: Pull complete
f0ffb5cf6ba9: Pull complete
be232718519c: Pull complete
fb141ec14d10: Pull complete
825a37952279: Pull complete
d3e8a59090a7: Pull complete
d5ea719780eb: Pull complete
6a3e074ddf0e: Pull complete
2d61f94994fa: Pull complete
6da592d8469f: Pull complete
Digest: sha256:ff3898ac817a10ec7129f6483721a717ed0d98c6ba42c27be1472d73908568da
Status: Downloaded newer image for ansible/ansible:ubuntu1604
```

This issue is related to the image you're trying to pull, and because a non-existing tag is used. It's not a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2017-09-13 13:35 UTC
Labels: area/distribution, platform/desktop, version/17.06
