### ISSUE TITLE
Schrodinger's Container: A file both exists and doesn't

### ISSUE THREAD

**Issue by j00bar** [moby/moby#24753] opened 2016-07-18 13:31 UTC
```
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Swarm: 
 NodeID: 
 IsManager: No
Security Options:
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: boot2docker
ID: T2PN:ZJO3:232C:5XD3:QDIR:DZJZ:VVPV:EHD4:XSVQ:ZLSK:NTY4:63GR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 40
 System Time: 2016-07-17T18:20:18.753688777Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=xhyve
Insecure Registries:
 127.0.0.0/8
```

```
$ cat Dockerfile
FROM python:2.7

# Add the dockerproject repo
RUN apt-get update -y && \
    apt-get install -y apt-transport-https ca-certificates && \
    echo "deb https://apt.dockerproject.org/repo debian-jessie main">/etc/apt/sources.list.d/docker.list && \
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
    apt-get update -y && \
    apt-get install -y python-setuptools git python-pip docker-engine && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD builder.sh /usr/local/bin/builder.sh
RUN pip install -q --no-cache-dir 'ansible==2.1.0.0'
```

```
$ cat docker-compose.yml
ansible-container:
  image: "sha256:cf6161c67baec3d4e75c472f51175a7d5b9eb26b25530374e5efe70d582ef9ab"
  command: /usr/local/bin/builder.sh /usr/local/bin/ansible-playbook -i /tmp/working/hosts -c docker  --list-hosts main.yml
  environment:
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY
    - DOCKER_CERT_PATH=/docker-certs/
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.23
  volumes:
    - $DOCKER_CERT_PATH:/docker-certs/
    - /Users/jginsberg/Development/ansible/ansible-container/example:/ansible-container/
    - /var/folders/wg/d5z1m_tn7d31p142wgc800tw0000gp/T/tmpvUCVPU:/tmp/working/
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
```

The head-slamming-against-desk whiskey tango foxtrot:

```
$ docker-compose up
ERROR: for ansible-container  Container command '/usr/local/bin/builder.sh' not found or does not exist.
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
ansible-container-builder   latest              cf6161c67bae        22 seconds ago      839.3 MB
python                      2.7                 a047e3d0ae2b        5 weeks ago         688.1 MB
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
5b74e8e9f99d        cf6161c67bae        "/usr/local/bin/build"   About a minute ago   Created                                 ansible_ansible-container_1
$ docker run --rm -it cf6161c67bae /usr/local/bin/builder.sh ls -l /usr/local/bin/builder.sh
-rwxr-xr-x 1 root root 115 Jul 14 15:52 /usr/local/bin/builder.sh
$ docker run --rm -it cf6161c67bae /usr/local/bin/builder.sh cat /usr/local/bin/builder.sh
#!/bin/bash

# test '(! -f /src/requirements.txt)' || pip install --no-cache-dir -q -U -r /src/requirements.txt
$@
```

How can `builder.sh` both exist and not exist?

**Comment by j00bar** [comment] 2016-07-18 13:48
Even more fun. If in my `docker-compose.yml` I change the command to `/bin/bash`, I get:

```
ERROR: for ansible-container  Container command '/bin/bash' not found or does not exist.
```

**Comment by j00bar** [comment] 2016-07-18 13:50
I can't even...

```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
620f5ca52905        7fdfaee09d2a        "/bin/bash"         4 minutes ago       Created                                 ansible_ansible-container_1
$ docker start 620f5ca52905
Error response from daemon: Container command '/bin/bash' not found or does not exist.
Error: failed to start containers: 620f5ca52905
```

**Comment by thaJeztah** [comment] 2016-07-18 14:03
The `Container command ... not found or does not exist.` could be a false positive, as it's also output if there's something wrong with the script (see, for example, https://github.com/docker/docker/issues/20789, https://github.com/docker/docker/issues/23411, and https://github.com/docker/docker/issues/23571)

Docker 1.12 contains a change to give a better error message, and was merged in https://github.com/docker/docker/pull/22983/files#diff-3cb140026df40998ea29c5bcb6bb292eR150

Can you try if this is resolved in the 1.12 release candidates? https://github.com/docker/docker/releases (at least, if it returns an error message that may explain what the issue is?)

**Comment by justincormack** [comment] 2016-07-18 14:15
`builder.sh` not being able to be executed will also happen if `/bin/bash` is not found, so it is kind of the same issue. But I am not sure how bash is being uninstalled...

**Comment by justincormack** [comment] 2016-07-19 12:40
@j00bar not necessarily, wouldn't they be using `/bin/sh` which is not `bash` in Debian, it is `ash`.

**Comment by mikeprice99** [comment] 2016-07-20 10:45
Beware: you can get erroneous messages like the one you have if the script is saved in dos format: the line endings  will cause the #!/bin/bash to fail.

**Comment by j00bar** [comment] 2016-07-20 13:45
Version wrangling on my laptop between Docker for Mac and Docker Toolbox. I can say this does _not_ happen on 0.11 Toolbox. Trying out other versions...

**Comment by thaJeztah** [comment] 2023-08-15 14:08
I guess this is a duplicate of https://github.com/moby/moby/issues/29420. Let me close this one.

**Closed by thaJeztah** 2023-08-15 14:08 UTC
Labels: version/1.11
