### ISSUE TITLE
[Feature Request] Safe Restart Option Required

### ISSUE THREAD

**Issue by dhirschfeld** [moby/moby#39020] opened 2019-04-07 23:38 UTC
**Description**
I'm running `windows/servercore:1809` containers on a Windows Server 2019 VM running under VMWare with nested virtualization enabled.

Something in our configuration *regularly* causes docker to completely freeze the VM. Once this happens, it happens as soon as the containers are restarted.

To avoid container startup I have to boot into safe mode but I still can't do anything because if I manually start the daemon it restarts the containers and kills the VM.

As it is now, the only way I can get out of this cycle is to use [`ci-zap`](https://github.com/jhowardmsft/docker-ci-zap) to completely nuke the docker folder, after which I can start the daemon and everything is seemingly "fine" again.

Unfortunately, this means I lose all my containers and have to begin a long process of rebuilding everything from scratch.

It would be good if there were an option to start the daemon ***without restarting any containers***. This would hopefully allow me to recover by simply killing the existing containers and manually starting new containers without having to also nuke every image I have.

**Steps to reproduce the issue:**
No idea, sorry. Everything is working fine then the VM freezes and any attempt to restart the containers kills the VM. Without the ability to do a "safe restart" I'm unable to debug further and have to nuke my entire docker folder.

**Comment by dhirschfeld** [comment] 2019-04-07 23:38
***xref:*** https://github.com/moby/moby/issues/19118

**Comment by dhirschfeld** [comment] 2019-04-07 23:39
***xref:*** https://github.com/moby/moby/issues/18936

**Comment by thaJeztah** [comment] 2023-09-16 16:08
closing as (partial) duplicate of https://github.com/moby/moby/issues/18936

**Closed by thaJeztah** 2023-09-16 16:08 UTC
Labels: platform/windows
