### ISSUE TITLE
Docker 17.06.0-ce crash invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dcharbonnier** [moby/moby#34530] opened 2017-08-16 06:35 UTC
deploying a stack on the swarm with docker compose, missing auth
```
Aug 16 08:18:30 xx121431 dockerd[32528]: time="2017-08-16T08:18:30.066706459+02:00" level=info msg="Node join event for xx87063-b73b5ccb9421/163.000.000.000"
Aug 16 08:18:48 xx121431 dockerd[32528]: time="2017-08-16T08:18:48.063866774+02:00" level=info msg="Attempting next endpoint for pull after error: Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden"
Aug 16 08:18:48 xx121431 dockerd[32528]: time="2017-08-16T08:18:48.063929445+02:00" level=error msg="pulling image failed" error="Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden" module="node/agent/taskmanager" node.id=zgx0diy4fu0vvx4k1o664x3ou service.id=snxv3ytzyqi51aucxjaw0xr0t task.id=ze39b5m3g1mp44np24tgxj3nu
Aug 16 08:18:48 xx121431 dockerd[32528]: time="2017-08-16T08:18:48.876019778+02:00" level=info msg="Attempting next endpoint for pull after error: Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden"
Aug 16 08:18:48 xx121431 dockerd[32528]: time="2017-08-16T08:18:48.876088628+02:00" level=error msg="pulling image failed" error="Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden" module="node/agent/taskmanager" node.id=zgx0diy4fu0vvx4k1o664x3ou service.id=snxv3ytzyqi51aucxjaw0xr0t task.id=hirffsmnmvt6gbm78lybqyg8j
Aug 16 08:18:53 xx121431 dockerd[32528]: time="2017-08-16T08:18:53.431576503+02:00" level=info msg="Attempting next endpoint for pull after error: Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden"
Aug 16 08:18:53 xx121431 dockerd[32528]: time="2017-08-16T08:18:53.431632381+02:00" level=error msg="pulling image failed" error="Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden" module="node/agent/taskmanager" node.id=zgx0diy4fu0vvx4k1o664x3ou service.id=snxv3ytzyqi51aucxjaw0xr0t task.id=ohvrr3slz25371frvcrev1mql
Aug 16 08:18:54 xx121431 dockerd[32528]: time="2017-08-16T08:18:54.027798952+02:00" level=warning msg="deleteServiceInfoFromCluster NetworkDB DeleteEntry failed for 75b292a40f51fac45da5df30c9b2bd1b4cb4eb557f85af7c3a23fe1e76226834 wg8bcpbkdysin3vec1gub6e5b err:cannot delete entry as the entry in table endpoint_table with network id wg8bcpbkdysin3vec1gub6e5b and key 75b292a40f51fac45da5df30c9b2bd1b4cb4eb557f85af7c3a23fe1e76226834 does not exist"
Aug 16 08:18:54 xx121431 dockerd[32528]: time="2017-08-16T08:18:54.027893165+02:00" level=warning msg="rmServiceBinding deleteServiceInfoFromCluster api_streamer 75b292a40f51fac45da5df30c9b2bd1b4cb4eb557f85af7c3a23fe1e76226834 aborted c.serviceBindings[skey] !ok"
Aug 16 08:18:54 xx121431 dockerd[32528]: time="2017-08-16T08:18:54.327981229+02:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module="node/agent/taskmanager" node.id=zgx0diy4fu0vvx4k1o664x3ou service.id=snxv3ytzyqi51aucxjaw0xr0t task.id=ze39b5m3g1mp44np24tgxj3nu
Aug 16 08:18:54 xx121431 dockerd[32528]: time="2017-08-16T08:18:54.660600782+02:00" level=info msg="Attempting next endpoint for pull after error: Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden"
Aug 16 08:18:54 xx121431 dockerd[32528]: time="2017-08-16T08:18:54.660646253+02:00" level=error msg="pulling image failed" error="Get https://registry.example.com:443/v2/example/api/manifests/7cca4f810f7510984010c14b4da0c0f1b52e3e90: denied: access forbidden" module="node/agent/taskmanager" node.id=zgx0diy4fu0vvx4k1o664x3ou service.id=snxv3ytzyqi51aucxjaw0xr0t task.id=gyp41zsyozlf5vrcpa0rqwrca
Aug 16 08:18:54 xx121431 dockerd[32528]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 16 08:18:54 xx121431 dockerd[32528]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xdd6c28]
Aug 16 08:18:54 xx121431 dockerd[32528]: goroutine 682572 [running]:
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*network).setupSubnetSandbox(0xc4209ab4a0, 0xc42199ef00, 0xc420ae2200, 0xf, 0xc420ae2430, 0xf, 0x544b05, 0xc42225e1a0)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go:551 +0x78
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*network).initSubnetSandbox(0xc4209ab4a0, 0xc42199ef00, 0x465e00, 0xc42211f890, 0xc42211f888)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go:603 +0x1f6
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*network).joinSubnetSandbox.func1()
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go:295 +0x40
Aug 16 08:18:54 xx121431 dockerd[32528]: sync.(*Once).Do(0xc42137cdf0, 0xc42211f8d0)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /usr/local/go/src/sync/once.go:44 +0xbe
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*network).joinSubnetSandbox(0xc4209ab4a0, 0xc42199ef00, 0x0, 0x0, 0x40)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go:296 +0x65
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*driver).peerAdd(0xc4202002d0, 0xc4221df4e0, 0x19, 0xc4215443c0, 0x40, 0xc42225e1a0, 0x10, 0x10, 0xc42225e18c, 0x4, ...)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go:291 +0x33d
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*driver).EventNotify(0xc4202002d0, 0xc4221df401, 0xc4221df4e0, 0x19, 0xc422264400, 0x12, 0xc4215443c0, 0x40, 0xc421544400, 0x31, ...)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/joinleave.go:208 +0x4b5
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).handleDriverTableEvent(0xc42124b040, 0x18bc780, 0xc42124e190)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:814 +0x32e
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).(github.com/docker/docker/vendor/github.com/docker/libnetwork.handleDriverTableEvent)-fm(0x18bc780, 0xc42124e190)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:734 +0x3e
Aug 16 08:18:54 xx121431 dockerd[32528]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).handleTableEvents(0xc42051c400, 0xc421932b40, 0xc420ddb340)
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:775 +0xdf
Aug 16 08:18:54 xx121431 dockerd[32528]: created by github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).addDriverWatches
Aug 16 08:18:54 xx121431 dockerd[32528]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:734 +0x31b
Aug 16 08:18:54 xx121431 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 16 08:20:25 xx121431 systemd[1]: docker.service: State 'stop-sigterm' timed out. Killing.
Aug 16 08:20:25 xx121431 systemd[1]: docker.service: Unit entered failed state.
Aug 16 08:20:25 xx121431 systemd[1]: docker.service: Failed with result 'timeout'.
```

**Comment by thaJeztah** [comment] 2017-08-16 14:24
Thanks for reporting! We need some more information so that we can look into this, can you provide the information that was requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue?

- provide the output of `docker version`
- provide the output of `docker info`


Also, are you able to reproduce this issue, and if so, do you have a minimal example `docker-compose` file that shows this issue, so that we can use that to test, fix, and verify the issue?

Keep in mind that we don't have access to your private images or source code, so if possible, provide an example that uses just "standard" images.

**Comment by thaJeztah** [comment] 2017-08-16 14:27
ping @fcrisciani @abhinandanpb PTAL

**Comment by dcharbonnier** [comment] 2017-08-18 06:37
```
docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false


docker info
Containers: 18
 Running: 8
 Paused: 0
 Stopped: 10
Images: 10
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 115
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xxx
 Is Manager: true
 ClusterID: xxx
 Managers: 5
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: xxx
 Manager Addresses:
  xxx:2377
  xxx:2377
  xxx:2377
  xxx:2377
  xxx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-89-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 94.31GiB
Name: sd-121434
ID: 5G34:K5WH:45KC:JMKU:B7DV:M22C:AGMQ:OOAG:O6L6:5H6L:KEU2:27NQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by fcrisciani** [comment] 2017-08-21 22:23
@mavenugo is looking at this

**Comment by thaJeztah** [comment] 2017-11-02 14:18
ping @mavenugo was this looked into / resolved?

**Comment by AkihiroSuda** [comment] 2018-04-06 12:56
Is this already resolved?

**Comment by thaJeztah** [comment] 2018-04-06 22:09
It's been a long time since 17.06, and various fixes have gone in since; I haven't seen this issue reported since, so let me close this for now

**Closed by thaJeztah** 2018-04-06 22:09 UTC
Labels: area/networking, kind/bug, status/more-info-needed
