### ISSUE TITLE
Network problem in docker 17.09 with swarm mode

### ISSUE THREAD

**Issue by jeeffy** [moby/moby#35358] opened 2017-11-01 09:55 UTC
I create a service with
```
docker service create \
        -p 8080:80 \
        --mount type=bind,source=/var/docker/nginx/,target=/usr/share/nginx/html \
        --replicas 2 \
        --network qgsp-network \
        --name nginx \
        nginx;
```
Test the service with `curl 192.168.2.48:8080`, 50% requests are timeout. When I restart the service several times, sometimes, all requests are ok. Requests are hanged randomly, I'm confused for the case, and suspect network or vip has problem.
Test results of restart service 5 times
```
1st, all requests are ok. 
2nd, all requests are ok. 
3rd, 50% requests are failed. 
4th, all requests are ok. 
5th, all requests are ok. 
```
command of creating qgsp-network as follows:
```
docker network create --driver overlay qgsp-network
```

Result of port check with netcat is succeeded
```
nc -vuz 192.168.2.48  4789
nc -vz 192.168.2.48  2377
nc -vuz 192.168.2.48  7946
nc -vz 192.168.2.48  7946
```

Output of `docker info`:
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 26
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 101
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ilifz2ay0s5tn3c6m1nuxvbsh
 Is Manager: true
 ClusterID: 46dczj80n24y203xcyrwydkuc
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.2.47
 Manager Addresses:
  192.168.2.47:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.78GiB
Name: ubuntu-qgsp01
ID: RP4U:E3PW:AU5R:BLD2:2QDL:DA25:GY2P:YV67:IR2F:GEBZ:XVX3:XC72
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://20agqwyc.mirror.aliyuncs.com/
Live Restore Enabled: false
```

**Comment by jeeffy** [comment] 2017-11-01 09:59
Swarm cluster is created with 
```
docker swarm init --advertise-addr 192.168.2.47:2377
docker swarm join --token SWMTKN-1-0pi0eqi1t5hqm046n8fupoo2ba2fq98qd7g5ctelzwgv4lyjvu-cdfsw1ulfpj6ohsa74hqsxxxx 192.168.2.47:2377
```

**Comment by jeeffy** [comment] 2017-11-01 10:02
The directory `/var/docker/nginx/` is exist on ervery node.

**Comment by thaJeztah** [comment] 2017-11-01 15:39
- Is there anything in the daemon/system logs that may provide some insight? (ideally with the daemons running in debug mode).
- are both instances of the service running on the same node, or spread over both nodes?
- the requests that succeed; are they handled by the container that's running on the same node?

**Comment by jeeffy** [comment] 2017-11-02 02:00
Docker swarm cluster has 2 nodes(192.168.2.47 and 192.168.2.48). Container of the service is distributed on each node for 5 test above.
Today, I tested again, The requests were hanged at 9:04,
Logs on 192.168.2.47
```
Nov 02 09:04:11 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:11.618220340+08:00" level=info msg="Node join event for ubuntu-qgsp02-076adc943e78/192.168.2.48"
Nov 02 09:04:18 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:18.418656136+08:00" level=info msg="NetworkDB stats - Queue net:rn46ylxpba4yb9uhwnyp8k0n1 qLen:0 netPeers:2 netMsg/s:0"
Nov 02 09:04:18 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:18.418756292+08:00" level=info msg="NetworkDB stats - Queue net:cfbzu70ekzd91px8hpqtczma0 qLen:0 netPeers:2 netMsg/s:0"
Nov 02 09:04:18 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:18.418783047+08:00" level=info msg="NetworkDB stats - Queue net:f9leky6q9zlfag589q0v4866c qLen:0 netPeers:2 netMsg/s:0"
Nov 02 09:04:28 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:28.226518540+08:00" level=info msg="Node join event for ubuntu-qgsp02-076adc943e78/192.168.2.48"
Nov 02 09:04:36 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:36.679613453+08:00" level=error msg="Error removing service qgsp-manager: service qgsp-manager not found"
Nov 02 09:04:37 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:37.223029362+08:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 02 09:04:37 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:37.223070431+08:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 02 09:04:37 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:37.367461877+08:00" level=warning msg="Neighbor entry already present for IP 10.0.0.4, mac 02:42:0a:00:00:04"
Nov 02 09:04:37 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:37.367685606+08:00" level=warning msg="Neighbor entry already present for IP 10.255.0.6, mac 02:42:0a:ff:00:06"
Nov 02 09:04:41 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:41.620229192+08:00" level=info msg="Node join event for ubuntu-qgsp02-076adc943e78/192.168.2.48"
Nov 02 09:04:58 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:04:58.227585182+08:00" level=info msg="Node join event for ubuntu-qgsp02-076adc943e78/192.168.2.48"
Nov 02 09:05:11 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:05:11.621961275+08:00" level=info msg="Node join event for ubuntu-qgsp02-076adc943e78/192.168.2.48"
Nov 02 09:05:28 ubuntu-qgsp01 dockerd[43344]: time="2017-11-02T09:05:28.228644891+08:00" level=info msg="Node join event for ubuntu-qgsp02-076adc943e78/192.168.2.48"
```
Logs on 192.168.2.48
```
Nov 02 09:03:58 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:03:58.235330666+08:00" level=info msg="Node join event for ubuntu-qgsp01-7f2a79757970/192.168.2.47"
Nov 02 09:03:59 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:03:59.553426419+08:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 02 09:03:59 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:03:59.553460883+08:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 02 09:04:11 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:11.628400667+08:00" level=info msg="Node join event for ubuntu-qgsp01-7f2a79757970/192.168.2.47"
Nov 02 09:04:28 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:28.235983485+08:00" level=info msg="Node join event for ubuntu-qgsp01-7f2a79757970/192.168.2.47"
Nov 02 09:04:37 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:37.219669988+08:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 02 09:04:37 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:37.219917443+08:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 02 09:04:37 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:37.429843672+08:00" level=warning msg="Neighbor entry already present for IP 10.255.0.5, mac 02:42:0a:ff:00:05"
Nov 02 09:04:37 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:37.628477709+08:00" level=warning msg="Neighbor entry already present for IP 10.0.0.3, mac 02:42:0a:00:00:03"
Nov 02 09:04:41 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:41.629661529+08:00" level=info msg="Node join event for ubuntu-qgsp01-7f2a79757970/192.168.2.47"
Nov 02 09:04:43 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:43.776353637+08:00" level=info msg="NetworkDB stats - Queue net:f9leky6q9zlfag589q0v4866c qLen:0 netPeers:2 netMsg/s:0"
Nov 02 09:04:43 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:43.776411277+08:00" level=info msg="NetworkDB stats - Queue net:rn46ylxpba4yb9uhwnyp8k0n1 qLen:0 netPeers:2 netMsg/s:0"
Nov 02 09:04:43 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:43.776448312+08:00" level=info msg="NetworkDB stats - Queue net:cfbzu70ekzd91px8hpqtczma0 qLen:0 netPeers:2 netMsg/s:0"
Nov 02 09:04:58 ubuntu-qgsp02 dockerd[2639]: time="2017-11-02T09:04:58.236400705+08:00" level=info msg="Node join event for ubuntu-qgsp01-7f2a79757970/192.168.2.47"
```
Thanks, thaJeztah.

**Comment by jeeffy** [comment] 2017-11-02 02:13
I run the service with shell script as follows
```
docker service rm nginx 
docker service create \
        -p 8080:80 \
        --mount type=bind,source=/var/docker/nginx/,target=/usr/share/nginx/html \
        --replicas 2 \
        --network qgsp-network \
        --name nginx \
        nginx;
```
rm the service , and run immediately again, is it any wrong?

**Comment by jeeffy** [comment] 2017-11-02 03:37
The problem will be reduced if adding `sleep 5` in shell as following.
```
docker service rm nginx 
sleep 5
docker service create \
        -p 8080:80 \
        --mount type=bind,source=/var/docker/nginx/,target=/usr/share/nginx/html \
        --replicas 2 \
        --network qgsp-network \
        --name nginx \
        nginx;
```

**Comment by thaJeztah** [comment] 2017-11-02 13:15
This may be because the service commands are asynchronous; i.e., `docker service rm` will return immediately, but the tasks backing the service are not yet deleted. Docker will keep working in the background to reconcile the actual state with the  desired state.

Thinking out loud; possible reasons why requests fail;

- Perhaps the task is not removed from the DNS until the container itself is stopped / removed
- Tasks from the "previous" service (the one being removed) still exist, and interfere with the newly created service.

Some existing issues that may be relevant here;

- Service's task ip not remove from service's vip backend, cause network connection issues https://github.com/moby/moby/issues/33790 (this sounds quite similar; perhaps it's a duplicate of your issue)
- Zero-downtime deployments with rolling upgrades https://github.com/moby/moby/issues/30321
- (related to the above) Delete service info from cluster when service is disabled https://github.com/docker/libnetwork/pull/1824


ping @abhi PTAL if you think this is a duplicate of https://github.com/moby/moby/issues/33790

**Comment by thaJeztah** [comment] 2023-09-17 20:27
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 20:27 UTC
Labels: area/networking, area/swarm
