### ISSUE TITLE
Remote API: rename container responds with HTTP 400, should be HTTP 409

### ISSUE THREAD

**Issue by davidxia** [moby/moby#35472] opened 2017-11-13 01:27 UTC
**Description**

Remote API: rename container responds with HTTP 400, should be HTTP 409. This happens on both 17.10 and 17.09.

**Steps to reproduce the issue:**
Create two containers.
Rename one container. (For example, to "foo".)
Using the remote API, POST to /containers/(id or name)/rename?name=foo, i.e. rename the second container to the same name as the first.

**Describe the results you received:**
The request fails with HTTP 400 bad request.

{"message":"Error when allocating new name: Conflict. The container name \"/1afabc65711aace8-6bf9bc24d807db13\" is already in use by container \"ca4a1c2132f5debe445c791216bae7c7d0ecacee62b1f5393df2ec21501b37e5\". You have to remove (or rename) that container to be able to reuse that name."}

**Describe the results you expected:**
The request fails with HTTP 409 Conflict, message name already assigned, as described in the [remote API docs][api-doc].

  [api-doc]: https://docs.docker.com/engine/api/v1.33/#operation/ContainerRename

**Output of `docker version`:**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:43 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 288
 Running: 1
 Paused: 0
 Stopped: 287
Images: 121
Server Version: 17.10.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 729
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: lpzh1yir70ysu8q5y5h1pzug1
 Is Manager: true
 ClusterID: rxvk8l7smfzkcfy99g03q91ce
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: true
 Root Rotation In Progress: false
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.93-boot2docker
Operating System: Boot2Docker 17.10.0-ce (TCL 7.2); HEAD : 34fe485 - Wed Oct 18 17:16:34 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955GiB
Name: 17.10.0
ID: ORAB:O2DJ:HFXW:BCAA:RCAU:3UTJ:JTY2:3G4Z:VMQJ:4DY3:425W:HM5A
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 216
 Goroutines: 331
 System Time: 2017-11-13T01:24:12.130585157Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

A similar issue was [reported here ](https://github.com/moby/moby/issues/21016) before.

**Comment by thaJeztah** [comment] 2017-11-15 15:19
Thanks for reporting; this looks to be a duplicate of https://github.com/moby/moby/issues/35021, and fixed on master by https://github.com/moby/moby/pull/35022

That patch is included in the upcoming Docker 17.11; here's on docker-ce 17.11-rc2:

```bash
$ docker create --name c1 busybox
$ curl --unix-socket /var/run/docker.sock -v -XPOST -H"Content-Type: application/json" -d'{"Image":"busybox"}' 'http://localhost/containers/create?name=c1'

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying /var/run/docker.sock...
* Connected to localhost (/Users/sebastiaan/Library/Containers/com.dock) port 80 (#0)
> POST /containers/create?name=c1 HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 19
>
* upload completely sent off: 19 out of 19 bytes
< HTTP/1.1 409 Conflict
< Api-Version: 1.34
< Content-Length: 229
< Content-Type: application/json
< Date: Wed, 15 Nov 2017 15:21:55 GMT
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/17.11.0-ce-rc2 (linux)
<
{"message":"Conflict. The container name \"/c1\" is already in use by container \"8f7014dd021fc5001a2748ca8a2742bbf13e0560b3cd455e4e48e664136a6b1a\". You have to remove (or rename) that container to be able to reuse that name."}
* Connection #0 to host localhost left intact
```

I also opened an internal backport request for docker 17.09 for consideration.


I'm closing this issue because this is already addressed on master, but feel free to comment after I closed 👍

**Closed by thaJeztah** 2017-11-15 15:19 UTC
Labels: version/17.10

**Comment by davidxia** [comment] 2017-11-15 16:32
Sorry didn’t see that issue. Thanks for checking.
-- 
David Xia
davidxia.com

**Comment by thaJeztah** [comment] 2017-11-15 16:37
No worries, GitHub search can be terrible at finding things :smile:
