### ISSUE TITLE
`"invalid mount config for type "bind": bind source path does not exist"`

### ISSUE THREAD

**Issue by dvohra** [moby/moby#34237] opened 2017-07-24 20:10 UTC
**Description**

A service with a `bind` mount does not get created even though the host directory for the `bind` mount exists on each of the hosts. Issue occurs with managed service Docker for AWS (tested only with CE Stable) but not with a Swarm started by creating 3 individual nodes, initializing the Swarm and joining nodes to Swarm. 

**Steps to reproduce the issue:**
1. Create a Docker for AWS Swarm (eg. 1 manager 2 worker nodes)
  2. Login into each Swarm instance and create a directory on each host for the bind mount.
`sudo mkdir -p /etc/mysql/scripts`
3. Create a service with the bind mount.

```
docker service create \
   --env MYSQL_ROOT_PASSWORD='mysql' \
   --replicas 1 \
  --mount type=bind,src="/etc/mysql/scripts",dst="/scripts" \
  --name mysql \
      mysql

```

**Describe the results you received:**
Service does not get created.

```
~ $ docker service ps --no-trunc mysql
ID                          NAME                IMAGE                                                                                  NODE                            DESIRED STATE       CURRENT STATE             ERROR                                                                     PORTS
x4k047clllkskm4j1uteeqm27   mysql.1             mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-16-11.ec2.internal    Ready               Rejected 2 seconds ago    "invalid mount config for type "bind": bind source path does not exist"   
u3edkaozfnuakfj1a0qn9wth5    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-16-11.ec2.internal    Shutdown            Rejected 7 seconds ago    "invalid mount config for type "bind": bind source path does not exist"   
q6zqonfae1csnlzeaxbvuu3lk    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-16-11.ec2.internal    Shutdown            Rejected 12 seconds ago   "invalid mount config for type "bind": bind source path does not exist"   
1mo10gigap8j7rik6bx97nk2h    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-35-209.ec2.internal   Shutdown            Rejected 17 seconds ago   "invalid mount config for type "bind": bind source path does not exist"   
b2iupkrkg20jsra9dld45gdid    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-35-209.ec2.internal   Shutdown            Rejected 22 seconds ago   "invalid mount config for type "bind": bind source path does not exist"   
```

**Describe the results you expected:**
Service gets created.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
~ $ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
~ $ docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: o0h7o09a61ico7n1t8ooe281g
 Is Manager: true
 ClusterID: y20lilgtj80ezqawscmr5a79x
 Managers: 1
 Nodes: 5
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for AWS CE Stable.

**Comment by thaJeztah** [comment] 2017-07-24 20:17
have you tried specifying the path without quotes? I think the quotes (being _part_ of the flag's value) may be taken as literal values

**Comment by dvohra** [comment] 2017-07-24 20:27
Same error message without quotes on directory paths. 

Being a managed service on which the `ssh` login command logs directly into the Swarm mode shell, is the directory created from the client shell on the _host_ or the _client shell_ to the host?

**Comment by thaJeztah** [comment] 2017-07-24 20:32
Oh, I missed the `Docker for AWS` part; IIRC, the SSH daemon is running in a container, but perhaps @kencochrane can enlighten me there

**Comment by dvohra** [comment] 2017-07-24 20:37
If the client shell is not the host, the issue is expected. 

And feature request is for Docker for AWS to add direct access to host without which `bind` mount is not usable on Docker for AWS.

**Comment by kencochrane** [comment] 2017-07-24 20:56
@dvohra is this a duplicate of https://github.com/docker/for-aws/issues/74 if so, you can close this one, and we can discuss over there.

**Comment by dvohra** [comment] 2017-07-24 20:58
@kencochrane either is fine though a few replies have been posted on moby/moby and cross-reference would be required for docker/for-aws.

**Comment by kencochrane** [comment] 2017-07-24 20:59
since this is docker for aws related, best to have the discussion over there, this way if anyone else has a similar issue they will be able to easily find it.

**Closed** 2017-07-24 20:59 UTC
Labels: area/swarm

**Comment by dvohra** [comment] 2017-07-24 21:02
Thanks @thaJeztah as @kencochrane has confirmed `ssh` logs into a container and not the host. The issue may be closed on both moby/moby and docker/for-aws and a feature request added.

**Comment by dvohra** [comment] 2017-07-25 01:06
@thaJeztah. The discussion is continued on https://github.com/docker/for-aws/issues/74

**Comment by thaJeztah** [comment] 2017-07-25 01:09
Thanks both!
