### ISSUE TITLE
Proposal: env-file support for Dockerfile build

### ISSUE THREAD

**Issue by 0xdevalias** [moby/moby#32455] opened 2017-04-09 00:30 UTC
Currently we are able to [set individual ENV variables](https://docs.docker.com/engine/reference/builder/#env) in the `Dockerfile`.

`docker-compose` allows us to source an [env-file](https://docs.docker.com/compose/env-file/) to set multiple variables at once, in a nice format.

A rails project I'm working on `ADD`'s the `.env` file to pass through the environment variables, and then sources them into the app using [dotenv](https://github.com/bkeepers/dotenv).

It would make more sense to me to set these default ENV variables during the docker build stage, and have them persist in the image that way. Unfortunately, the only way i've been able to see to do that currently is to manually copy out all of the entries from the `.env` file, and format them to fit into the `Dockerfile`'s `ENV` format, which is time consuming and error prone.

I would like to be able to set something like the following within my `Dockerfile`:

```
# .env
FOO=BAR
BAR=BAZ

# Dockerfile
ENV-FILE .env
```

I would see this as being equivalent in functionality to:

```
# Dockerfile
ENV FOO=BAR BAR=BAZ
```

**Comment by davidrdz93** [comment] 2017-12-12 21:58
This would be a nice feature!!

**Comment by thaJeztah** [comment] 2017-12-13 01:52
Actually, this is a duplicate of https://github.com/moby/moby/issues/28617, which has more discussion already, so let me close this one in favour of https://github.com/moby/moby/issues/28617

**Closed by thaJeztah** 2017-12-13 01:52 UTC
Labels: area/builder
