### ISSUE TITLE
Segmentation fault when running bash in a CentOS 6 container

### ISSUE THREAD

**Issue by bbc2** [moby/moby#34301] opened 2017-07-28 17:09 UTC
**Description**

Running bash in a CentOS 6 container fails with a segmentation fault.

**Steps to reproduce the issue:**

Install Docker CE on Debian Buster (currently Debian Testing) and run

```bash
docker run -ti centos:6 bash
```

**Describe the results you received:**

No output but it fails immediately with a 139 error code.  In the system logs I can see:

```
Jul 28 18:55:00 star kernel: bash[2018] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffd38083248 ax:ffffffffff600400 si:7ffd38084f7b di:0
Jul 28 18:55:00 star kernel: bash[2018]: segfault at ffffffffff600400 ip ffffffffff600400 sp 00007ffd38083248 error 15
```

**Describe the results you expected:**

An interactive bash prompt.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue doesn't occur on Debian Stretch (same storage driver and Docker version).

It also doesn't occur with CentOS 7 images.

It also doesn't occur with other commands like `dash`.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:16:12 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.0-1-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.12GiB
Name: star
ID: 4ZNG:TB5B:MFRP:FC5V:GHPE:SPXM:Q26I:PFZZ:CDX7:VBMZ:BFGC:DOHO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The bug occurs on a physical machine.  I also reproduced it on a laptop with the same version of Debian.

**Comment by thaJeztah** [comment] 2017-07-31 14:04
This looks like a duplicate of https://github.com/docker/for-linux/issues/58, and is due to a kernel configuration change in debian. Can you try if this resolves your issue; https://github.com/docker/for-linux/issues/58#issuecomment-315150740 ?

/cc @ijc @justincormack should an issue be reported with Debian?

**Comment by bbc2** [comment] 2017-07-31 14:39
Yes, I confirm passing `vsyscall=emulate` to the kernel resolves it for me. Thank you for the pointer!

**Comment by ijc** [comment] 2017-08-01 11:00
@thaJeztah I don't think Debian will back out this change again. Perhaps a wishlist bug against the kernel package asking to add an entry to the `NEWS.Debian.gz` of the linux-image-amd64 metapackage (which will be displayed on upgrade in the default setup I believe) would be justified, from http://sources.debian.net/src/linux-latest/83/debian/linux-image.NEWS/ it seems like the sort of thing which would be appropriate.

@bbc2 perhaps you would be able to do that? (just run `reportbug kernel` on the affected Debian system and follow the prompts)

**Comment by thaJeztah** [comment] 2017-08-01 11:04
If we cannot automate this change during install; at least we should document it in our installation documentation https://github.com/docker/docker.github.io/blob/master/engine/installation/linux/docker-ce/debian.md

**Comment by thaJeztah** [comment] 2020-03-10 08:53
closing this one, as it's pretty old now, and likely a corner-case. feel free to open a PR in the documentation repository if you have suggestions for adding this in the documentation; https://github.com/docker/docker.github.io/issues

**Closed by thaJeztah** 2020-03-10 08:53 UTC
Labels: area/kernel, status/more-info-needed, version/17.06
