### ISSUE TITLE
log file tail cut off

### ISSUE THREAD

**Issue by elvizlai** [moby/moby#35799] opened 2017-12-14 10:37 UTC
**Description**

When I tried using filebeat/fluentd or tail the raw log file in path `/var/lib/docker/containers/*/*-json.log`. I found that when log-stream is large, it will cut off into multi log output, which leads invalid JSON. Any way to fix this ?

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-918978-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/vda1
 Metadata file: /dev/vda1
 Data Space Used: 21.47GB
 Data Space Total: 107.4GB
 Data Space Available: 85.9GB
 Metadata Space Used: 25.12MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.122GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702GiB
Name: ali-dev-01.17mei.com
ID: RX2D:B2UH:EOSG:7W4T:6YF5:2NE2:EIY7:5RIE:OQTM:CZ4C:F3C3:IHDK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://3z5xu1ec.mirror.aliyuncs.com/
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-12-18 12:01
Can you be more specific, and show what you're seeing? more specifically;

> I found that when log-stream is large, it will cut off into multi log output,

Do you mean that the original log-entry as is output by the container is split into multiple log-entries, or that the JSON of the JSON-log file itself is invalid?

(Note that those files are not designed to be accessed directly, but as a storage mechanism for the JSON file logging-driver, and should be accessed through either the `docker container logs` command, or through the API)

**Comment by elvizlai** [comment] 2017-12-19 09:50
Yes, the original log-entry split into multiple log-entries. I need collect origin log into elasticsearch.

**Comment by thaJeztah** [comment] 2017-12-19 13:24
Yes, that's expected; there's a maximum size/length for log-entries. Log-entries that are larger than that size as marked as "partial" messages; https://github.com/moby/moby/blob/e1ada0b885b31de0bb0e79b4d99ae4d48b65f721/daemon/logger/copier.go#L109-L115

Logging drivers are responsible for handling partial messages, for the jsonfile logging driver this is done by omitting a newline at the end to the log-message; https://github.com/moby/moby/blob/16f7cd674902b69b97692de2a83915a1a6be2cdb/daemon/logger/jsonfilelog/jsonfilelog.go#L108-L110

(similarly, the journald logging driver adds additional metadata that the message is a partial message; https://github.com/moby/moby/blob/16f7cd674902b69b97692de2a83915a1a6be2cdb/daemon/logger/journald/journald.go#L110-L112).

If should be possible to reconstruct the original message with that information, but the best solution for this would likely to develop a logging-driver plugin for elasticsearch, instead (also see https://github.com/moby/moby/issues/25694, https://github.com/moby/moby/issues/14949)

I'm closing this issue, because this is the expected behaviour, and (as mentioned earlier), these log-files are not intended for consumption by other software, but feel free to continue the conversation.

**Closed by thaJeztah** 2017-12-19 13:24 UTC
Labels: area/logging, status/more-info-needed, version/17.05
