### ISSUE TITLE
Can't stop Docker containers - Error during connect - Docker Toolbox

### ISSUE THREAD

**Issue by pablosistemas** [moby/moby#32275] opened 2017-03-31 17:41 UTC
I'm trying to integrate VSTS with Docker to run automated tests, and I want to dockerize my databases to maintain a consistent database state among tests without take care of cleanup step, running a new container with no modifications. But I have receiving a lot of errors from Docker for containerize a SQL Server database. Frequently my containers hangs, and I can't stop or remove these containers without reboot the Boot2Docker VM. I have receiving a error message for any Docker command after that error. Even a simple *docker ps* or *docker version* didn't work after a container hangs, giving me the following error message:

 - error during connect: Post *https://192.168.99.100:2376/v1.26/containers/container-name/stop: dial tcp 192.168.99.100:2376*: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

If I reopen the Docker QuickStart Terminal after this issue, I receive the following error description:

 - Error getting IP address: ssh command error: command : ip addr show
   err     : exit status 255

Because of that, I have to manually stop the *default* docker machine and reopen Docker Quickstart.

I have using a container released by Microsoft SQL Server to evaluate my solution, so a believe this container should work properly. So, to test my environment, I created a simple app with netcat server just to send several connections and evaluate whether for any reason my operating system, or Docker Toolbox, or anything related with, were causing these problems, but testing this simple docker server with several threads sending a lot of messages in several iterations my solution work properly with none errors.
Dockerfile:

```
    FROM centos:latest
    RUN yum install nc -y
    EXPOSE 1433CMD nc -l -k 1433 > /out.netcat
    CMD nc -l -k 1433 > /out.netcat
```

Are there any released solution for these problems, or even an way to avoid it? Looking for solutions in Google, I couldn't identify any solution, I just identified that there are others with the same errors. Can Docker be used to containerize databases?

Environment:

  ```
  $ docker version
    time="2017-03-31T10:23:50-03:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
    Client:
    Version:      1.13.1
    API version:  1.26
    Go version:   go1.7.5
    Git commit:   092cba3
    Built:        Wed Feb  8 08:47:51 2017
    OS/Arch:      windows/amd64

    Server:
    Version:      17.03.0-ce
    API version:  1.26 (minimum version 1.12)
    Go version:   go1.7.5
    Git commit:   3a232c8
    Built:        Tue Feb 28 07:52:04 2017
    OS/Arch:      linux/amd64
    Experimental: false

    $ docker info
    time="2017-03-31T10:27:10-03:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
    Containers: 2
    Running: 0
    Paused: 0
    Stopped: 2
    Images: 25
    Server Version: 17.03.0-ce
    Storage Driver: aufs
    Root Dir: /mnt/sda1/var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs: 25
    Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
    Volume: local
    Network: bridge host macvlan null overlay
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Init Binary: docker-init
    containerd version: 977c511eda0925a723debdc94d09459af49d082a
    runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
    init version: 949e6fa
    Security Options:
    seccomp
    Profile: default
    Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
    OSType: linux
    Architecture: x86_64
    CPUs: 1
    Total Memory: 3.491 GiB
    Name: default
    ID: 56MH:QSVM:SCCQ:DKVC:HBNI:AYJK:UCQN:2UJZ:A4NV:KOZQ:XC67:EEPY
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): true
    File Descriptors: 14
    Goroutines: 22
    System Time: 2017-03-31T13:27:08.809341202Z
    EventsListeners: 0
    Username: pablogoulart
    Registry: https://index.docker.io/v1/
    Labels:
    provider=virtualbox
    Experimental: false
    Insecure Registries:
    127.0.0.0/8
    Live Restore Enabled: false

```
 docker logs:

```
This is an evaluation version.  There are [164] days left in the evaluation period.
    RegQueryValueEx HADR for key "Software\Microsoft\Microsoft SQL Server\MSSQL\MSSQLServer\HADR" failed.
    2017-03-31 12:30:40.77 Server      Microsoft SQL Server vNext (CTP1.4) - 14.0.405.198 (X64)
            Mar 11 2017 01:54:12
            Copyright (C) 2016 Microsoft Corporation. All rights reserved.
            on Linux (CentOS Linux 7 (Core))
    2017-03-31 12:30:40.78 Server      UTC adjustment: 0:00
    2017-03-31 12:30:40.78 Server      (c) Microsoft Corporation.
    2017-03-31 12:30:40.78 Server      All rights reserved.
    2017-03-31 12:30:40.78 Server      Server process ID is 4116.
    2017-03-31 12:30:40.78 Server      Logging SQL Server messages in file 'C:\var\opt\mssql\log\errorlog'.
    2017-03-31 12:30:40.79 Server      Registry startup parameters:
             -d C:\var\opt\mssql\data\master.mdf
             -l C:\var\opt\mssql\data\mastlog.ldf
             -e C:\var\opt\mssql\log\errorlog
    2017-03-31 12:30:41.29 Server      SQL Server detected 1 sockets with 1 cores per socket and 1 logical processors per socket, 1 total logical processors; using 1 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
    2017-03-31 12:30:41.34 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
    2017-03-31 12:30:41.37 Server      Detected 2860 MB of RAM. This is an informational message; no user action is required.
    2017-03-31 12:30:41.37 Server      Using conventional memory in the memory manager.
    2017-03-31 12:30:41.51 Server      Default collation: SQL_Latin1_General_CP1_CI_AS (us_english 1033)
    2017-03-31 12:30:41.76 Server      Buffer pool extension is already disabled. No action is necessary.
    2017-03-31 12:30:41.97 Server      InitializeExternalUserGroupSid failed. Implied authentication will be disabled.
    2017-03-31 12:30:41.98 Server      Implied authentication manager initialization failed. Implied authentication will be disabled.

```

**Comment by friism** [comment] 2017-03-31 18:47
> Can Docker be used to containerize databases?

Yes.

To determine whether the problem is caused by the combination of Docker/Boot2Docker/VirtualBox/Windows, consider trying to reproduce with Docker running on a bare-metal Linux host or on AWS, Digital Ocean or similar.

Consider moving this issue to the Docker Toolbox project if you believed it's related to Toolbox: https://github.com/docker/toolbox/

If you think the problem is specific to the SQL Server container images, open an issue here: https://github.com/Microsoft/mssql-docker

If you identified reports of similar issues, please include links.

**Comment by pablosistemas** [comment] 2017-03-31 22:02
Ok, I will reproduce my project in a real Linux and I will report any
problems.
Also, I will post this issues in proper places.
Thank you by your reply.
If I find any solution I will update the issue.

Best,
Pablo

**Comment by pablosistemas** [comment] 2017-04-06 15:38
I've tried on a personal Fedora installation and until now I've found any problem with containers hanging. But trying on a recommended VM on Azure (Docker on Ubuntu Server) I faced the same problem. I did some changes in my docker images before the tests, among them, I guaranteed that database process is executing purely on PID 1 without a script bash, to avoid the problem described on the Dockerfile reference that ENTRYPOINTS with bash calls could cause problems because parent process do not pass any signal to child on fork call, including docker stop.
Fedora kernel version: 4.8.6-300.fc25.x86_64
Ubuntu Server (Azure) kernel version: 4.4.0-72-generic
I found in other issues comments relating Docker with kernel version. Is there any proper kernel version that Docker high matured?

**Comment by thaJeztah** [comment] 2017-11-01 18:08
> Is there any proper kernel version where Docker has high maturity?

The Ubuntu kernels are well maintained, and using an up-to-date version of their kernel should work well. For production, it may be preferable to stick to the LTS versions (Ubuntu 16.04), as other releases have a relatively short support cycle.

Although historically Ubuntu used AUFS as the default storage driver, on newer versions, and installations that use kernel 4.x, the overlay2 storage driver is now the default; that storage driver is performant, part of the mainline kernel (thus; no kernel-modules required), and proven to be stable. Be aware though, that overlayFS does not support the full POSIX specification. This won't be a problem for most software, but there are exceptions (most of which won't be problematic, as writing persistent data to a volume takes care of that). You can find more information about the overlay storage driver here; https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/, and an overview of other storage drivers here: https://docs.docker.com/engine/userguide/storagedriver/

For processes doing lots of filesystem writes, it's generally recommended to use a volume to bypass the overhead of the copy-on-write filesystem used for containers. This applies especially to databases, where you'd want your data to persist beyond the lifecycle of the container itself (i.e., this allows you to destroy a container, replace it with an updated version, and re-attach the volume to keep your data).

> Can Docker be used to containerize databases?

Yes, running databases in a container should not be a problem. A process running "inside a container" effectively _runs on the host_, but with additional restrictions added to make the process more secure, and have more control over what resources it has access to, and the amount of resources it can use.

Containers are not "magic" though; you need to make sure that there's sufficient resources for the process to run (i.e., a database may require sufficient memory; if not enough physical memory is available, swap may me used, which can severly affect performance). Also make sure to restrict the amount of resources that's available to the container (at minimum, use the `--memory` option); the docker daemon, and other processes on the host also need resources; if you don't restrict the amount of resources on a container, the process can take unlimited resources, which may lead to other processes failing to work properly. See https://docs.docker.com/engine/admin/resource_constraints/, and https://docs.docker.com/engine/reference/run/ in the documentation, which contains more infomation about restricting resources.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-11-01 18:08 UTC
Labels: area/builder, version/17.03
