### ISSUE TITLE
Will this work with a read only system like LibreELEC?

### ISSUE THREAD

**Issue by Suffice** [moby/moby#42727] opened 2021-08-10 06:00 UTC
I'm trying to run this command:

`docker run -v /path/to/root:/var/ -v /path/filebrowser.db:$HOME/File_Browswer/database.db -v /path/.filebrowser.json:/$HOME/File_Browswer/.filebrowser.json -p 80:80 filebrowser/filebrowser`

And I get this error:

`docker: Error response from daemon: error while creating mount source path '/path/to/root': mkdir /path: read-only file system.`

No matter what I try changing root to it doesn't seem to work. I'm not sure if I'm doing something wrong here or if it is just not compatible.

**Comment by thaJeztah** [comment] 2021-08-10 11:36
Bind-mounts are performed from the host where the daemon runs. If ` /path/to/root` doesn't exist on the host where the daemon runs, and you're using the shorthand `-v <host-path>:<container-path>` syntax, the docker daemon will create the `<host-path>` directory (again, on the host were the daemon runs), which will fail if that path is read-only. Make sure the location exists before starting the container.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-08-10 11:36 UTC
Labels: kind/question
