### ISSUE TITLE
docker daemon hang on Ubuntu 16.04.2 LTS   with docker version 1.12.6

### ISSUE THREAD

**Issue by huxos** [moby/moby#34618] opened 2017-08-24 03:53 UTC
docker daemon hang with after  long uptime.
### the docker info output 

```
Containers: 24
 Running: 12
 Paused: 0
 Stopped: 12
Images: 99
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.10.0-27-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.9 GiB
Name: kube-system-1
ID: MNJL:7RR3:YPLL:LWF3:GRPG:IEKL:5S35:ZMG2:YFZI:VLOI:L7DN:HJ32
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

### the dump output whit `kill -USR1`

[https://gist.githubusercontent.com/huxos/e36c41f150ee98520727253c53d67584/raw/0c811b1ae675d7a71010dfcd2bae2f7091c65674/gistfile1.txt](https://gist.githubusercontent.com/huxos/e36c41f150ee98520727253c53d67584/raw/0c811b1ae675d7a71010dfcd2bae2f7091c65674/gistfile1.txt)

**Comment by thaJeztah** [comment] 2017-09-25 15:46
Docker 1.12 has reached end of life; are you still able to reproduce this on a current version of docker?

closing this because 1.12 is no longer maintained, but feel free to comment if you have steps to reproduce on a current version

**Closed by thaJeztah** 2017-09-25 15:46 UTC
