### ISSUE TITLE
http://docker.***.com/#/nodes  page  is null

### ISSUE THREAD

**Issue by renjw234** [moby/moby#40233] opened 2019-11-21 13:44 UTC
I  build a swarm  and join about 20 computer.
when i click the nodes butten  I  can see nothing,the page is nothing.
then  i login in the manager machine .   i  find  a container  and the tag name "unknown"   .
so i delete the container   .and   I  can see the nurmol  page  which  contain  20 machice.

**Comment by thaJeztah** [comment] 2019-11-21 13:59
Could you provide the exact steps to reproduce? It's not clear to me where you "click" to interact with nodes; is this in Docker Enterprise / UCP?

**Comment by renjw234** [comment] 2019-11-21 14:45
please  see  this picture  .  swarmpit is 1.8             and  i   click  the red  place    name  "nodes"   and i can see nothing   until  i  delete the "unknow" container






At 2019-11-21 21:59:12, "Sebastiaan van Stijn" <notifications@github.com> wrote:


Could you provide the exact steps to reproduce? It's not clear to me where you "click" to interact with nodes; is this in Docker Enterprise / UCP?

**Comment by thaJeztah** [comment] 2019-11-21 15:44
Looks like this is something you should report in the swarmpit issue tracker, not here. https://github.com/swarmpit/swarmpit

**Comment by thaJeztah** [comment] 2019-12-10 15:56
closing this issue here

**Closed by thaJeztah** 2019-12-10 15:56 UTC
Labels: status/more-info-needed
