### ISSUE TITLE
docker build --add-host is not working

### ISSUE THREAD

**Issue by arehmandev** [moby/moby#34078] opened 2017-07-12 14:58 UTC
I have just recently run:

docker build --add-host=docker:10.180.0.1 -t abs .
docker run -it abs sh
cat /etc/hosts

**The new entry is not found in the hosts file** - I have tried this on various images (alpine, jboss/wildfly). This was performed on Docker for Mac.

Interestingly this works though:
docker run -it --add-host=docker:10.180.0.1 abs sh
cat /etc/hosts

**Comment by thaJeztah** [comment] 2017-07-12 15:04
I just replied on the other issue https://github.com/moby/moby/pull/30383#issuecomment-314797629  ;

> the host that's added with this flag is only used during the build; it deliberately should not persist in the image

This is working as designed, so i'll close this, but feel free to continue the discussion

**Closed by thaJeztah** 2017-07-12 15:04 UTC
Labels: area/builder, platform/desktop

**Comment by jpuck** [comment] 2018-01-19 23:38
@thaJeztah thanks for the answer! I think your one sentence should be added to the [documentation][docs] for clarification.

What I was looking for was the `--add-host` flag for the `run` command.

```
docker run --add-host=docker:10.180.0.1 -it abs sh
cat /etc/hosts
```

[docs]:https://docs.docker.com/edge/engine/reference/commandline/build/#add-entries-to-container-hosts-file-add-host

**Comment by thaJeztah** [comment] 2018-01-20 01:27
@jpuck could you elaborate?  it's documented in the `docker run` command line reference; https://docs.docker.com/edge/engine/reference/commandline/run/#add-entries-to-container-hosts-file-add-host

**Comment by thaJeztah** [comment] 2018-01-20 01:28
oh! you meant my sentence: perhaps you're interested in contributing, and opening a pull request? the markdown file used to generate that page in the documentation can be found here; https://github.com/docker/cli/blob/master/docs/reference/commandline/build.md

**Comment by Hokwang** [comment] 2018-12-04 06:39
@thaJeztah is this still true ? can you answer my question? (https://stackoverflow.com/questions/53555902/question-for-docker-build-add-host-command)

and is there a no way to add hosts for users who use images I created ?

**Comment by thaJeztah** [comment] 2018-12-11 12:09
@Hokwang the same is still true https://github.com/moby/moby/issues/34078#issuecomment-314798584 / https://github.com/moby/moby/pull/30383#issuecomment-314797629

It's by design; the `--add-host` feature during build is designed to allow overriding a host during build, but _not_ to persist that configuration in the image.

If it would persist in the image;

- the image would not be portable (i.e., only work in your specific environment)
- images would be able to spoof DNS (what if an image contained `google.com 123.123.123.123` ?)

The person _running_ an image should remain in control over overriding hosts, not the image author; it's a runtime configuration.

Possible solutions For your situation;

- Run an internal DNS; you can set the default DNS server to use in the daemon; that way every container started will automatically use the configured DNS by default
- Use docker compose and provide a `docker-compose.yml` to your developers. The docker compose file allows you to specify all the options that should be used when starting a container, so developers could just `docker compose up` to start the container with all the options they need to set.
