### ISSUE TITLE
Oddities with env vars when using the API

### ISSUE THREAD

**Issue by scottrobertson** [moby/moby#33507] opened 2017-06-03 17:16 UTC
I am using the Docker API gem for Ruby. However, I have confirmed that the library itself is not causing this issue by debugging the raw requests being sent to the API.

I have the following code:

```
container = image.run("sh script.sh", {
  'Env' => [
    "FILE_NAME=thishas17chars123",
    "FILE_NAME_OTHER=thishas18chars123",
    "FILE_NAME_OTHER_OTHER=thishas19chars1234",
  ]
})
```

Inside the script.sh i am simply running `printenv`. Here is the response to that:

```
HOME=/root
"FILE_NAME_OTHER=thishas18chars123
BPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
)FILE_NAME_OTHER_OTHER=thishas19chars1234
PWD=/
FILE_NAME=thishas17chars123
```

As you can see, any env var with more than 17 chars is prepending random things to the beginning of the env var key, including PATH. 

If i run this with:

```
docker run -e FILE_NAME='thishas17chars123' -e FILE_NAME_OTHER='thishas18chars123' -e FILE_NAME_OTHER_OTHER='thishas19chars1234' image sh script.sh
```

It's fine and i get the following:

```
HOME=/root
FILE_NAME_OTHER=thishas18chars123
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FILE_NAME_OTHER_OTHER=thishas19chars1234
PWD=/
FILE_NAME=thishas17chars123
``` 

The ENV var part of request that is being sent to the API is as follows:

```
"Env":["FILE_NAME=thishas17chars123","FILE_NAME_OTHER=thishas18chars123","FILE_NAME_OTHER_OTHER=thishas19chars1234"]
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

and

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 5
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: db1
ID: TSHG:4KKB:D3YW:TNMO:CFWK:MEA3:5XCQ:RP4Y:LUHE:JW7L:NQBW:BUNT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

and 

```
Containers: 122
 Running: 0
 Paused: 0
 Stopped: 122
Images: 81
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: JBZS:LA75:ITSX:2SFP:D4YJ:R7WQ:4YE2:HZZH:HS7W:EWQL:7OBG:ZL7K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-06-03T17:14:51.601351064Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: scottrobertson
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I have tried this on Ubuntu 16.04 on Digital Ocean, and also on Docker for Mac.

**Comment by scottrobertson** [comment] 2017-06-03 17:19
@GordonTheTurtle you have tagged this as Desktop, but I just want to be clear that this is happening on Ubuntu Server too.

**Comment by ripcurld0** [comment] 2017-06-04 10:28
@scottrobertson can you please provide the entire API request (headers, body)?
It will be easier for me to debug this.

Thanks.

**Comment by scottrobertson** [comment] 2017-06-04 11:40
Hey @ripcurld0 thanks for getting back to me. Trying to find the cleanest way to debug this via the Docker API library. Just before the request is sent, I have dumped the request object. It's as follows:

```
:method: :post
:path: "/v1.16/containers/create"
:query: {}
:headers:
  Content-Type: application/json
  User-Agent: Swipely/Docker-API 1.33.4
:expects:
- 200
- 201
- 202
- 203
- 204
- 301
- 304
:idempotent: false
:body: '{"Image":"sha256:dac67688827aeea3986bab4ad45f2cebd289aedbb644a6a6b332bf0f2d5a07eb","Env":["DB_USER=postgres","DB_HOST=127.0.0.1","DB_PORT=57247","DB_PASS=56","FILE_NAME=127.0.0.1_postgres_hi_1496576262.sql","BACKUP_PROVIDER=local","DIRECTORY=/tmp/containerdb_backups/postgres-50"],"HostConfig":{"Binds":["/tmp/containerdb_backups/postgres-50:/backups"]},"Cmd":["printenv"]}'
{"Id":"ff895ae7a8a80a0ade7a657e6e89ef33e5a6a13139db4278150f653bea439d2d","Warnings":null}
```

One thing i am noticing is that it's using `/v1.16`. Not sure if that is significant or not.

**Comment by ripcurld0** [comment] 2017-06-04 11:47
thanks @scottrobertson
continue investigating.

**Comment by scottrobertson** [comment] 2017-06-04 11:47
@ripcurld0 i just updated the latest reply with all of the requests it makes, including the response of printenv

**Comment by scottrobertson** [comment] 2017-06-04 11:57
To confirm, i switched it to use API Version v1.17 and the issue is still present. 

Does anyone know of a way to monitor the Remote API request logs on Mac? And if not, is there a way to do it on Ubuntu? Google is not being much help.

**Comment by scottrobertson** [comment] 2017-06-04 18:41
I have tried both Socket and HTTP connections. Same issue.

**Comment by thaJeztah** [comment] 2017-06-04 21:53
@scottrobertson are you also able to reproduce with plain cURL (see @ripcurld0's example)? Given that it works correctly with the docker cli (which also uses the same API), and with cURL, I wonder if it's a bug in the docker API, or something odd with Ruby.

FWIW if your daemon is in debug mode, API requests can be seen in the daemon logs, so it would be worth comparing those between requests made with the cli, curl, and ruby

**Comment by scottrobertson** [comment] 2017-06-04 21:58
@thaJeztah I am unsure how to test using curl since I have not (and don't really want to) changed the Remote API to use HTTP.

**Comment by scottrobertson** [comment] 2017-06-04 22:01
I have reopened https://github.com/swipely/docker-api/issues/486 to see if we can work out if it's a ruby/gem issue too. I have debugged right down to the Excon (the HTTP library) level, and it's fine until then.

**Comment by thaJeztah** [comment] 2017-06-04 22:26
@scottrobertson if you have a recent version of curl, you can connect using the socket, otherwise, running curl in a container and bind-mounting the socket should work. See my reproduction steps in this issue; https://github.com/moby/moby/issues/33501#issuecomment-305939009

**Comment by scottrobertson** [comment] 2017-06-04 22:33
@thaJeztah thanks. I can confirm it's totally fine when running via curl.

**Comment by thaJeztah** [comment] 2017-06-04 22:42
Ok, so either something odd in Ruby, or there's something particular in those requests from Ruby  that is not handled by the docker API (no idea whatsoever what could trigger it, just thinking out loud - encoding issue, or (e.g.) chunked requests)

When testing; are you testing on Docker for Mac, or on Ubuntu? If there's a difference, it's worth knowing that Docker for Mac proxies socket requests on the host to the socket inside the VM; I'm not aware of current issues in the proxy, but it's worth excluding that possibility.

(Also see the linked issue; if bind-mounting the socket in the container, I _think_ the proxy is skipped)

**Comment by scottrobertson** [comment] 2017-06-04 23:00
I have tried it on both Docker for Mac and Ubuntu 16.04 :) 

I will do some debugging tomorrow with the Excon gem (the HTTP library that the Docker API library is using).

**Comment by scottrobertson** [comment] 2017-06-04 23:04
To rule it out, I tried Ruby 2.3.3 and 2.4.1. Both have the same issue.

**Comment by ripcurld0** [comment] 2017-06-05 07:54
Reproduced it successfully:
```bash
$ curl -XPOST -H "Content-Type: application/json" localhost:2375/v1.16/containers/create -d'{"Image":"sha256:c75bebcdd211f41b$
a460c7bf82970ed6c75acaab9cd4c9a4e125b03ca113798","Env":["FILE_NAME=thishas17chars123","FILE_NAME_OTHER=thishas18chars123","FILE_NAME_OTHER_OTHER=thishas19chars1234"],"Cmd":["p$
intenv"]}'
{"Id":"0af263a2da391f3ec0b3281fa5938604e1e5e1e82594cd7c7ab2abdd12ecf842","Warnings":null}
$ curl -XPOST -H "Content-Type: application/json" localhost:2375/v1.16/containers/0af263a2da391f3ec0b3281fa5938604e1e5e1e8259cd7c7ab2abdd12ecf842/start
$ curl -XGET -H "Content-Type: application/json" localhost:2375/v1.16/containers/0af263a2da391f3ec0b3281fa5938604e1e5e1e82594cd7c7ab2abdd12ecf842/logs?stdout=1&stderr=1
[1] 815
root@eef64b24a6a9:/go/src/github.com/docker/docker# BPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=0af263a2da39
FILE_NAME=thishas17chars123
"FILE_NAME_OTHER=thishas18chars123
)FILE_NAME_OTHER_OTHER=thishas19chars1234

HOME=/root
```

**Comment by scottrobertson** [comment] 2017-06-05 08:27
Awesome, thanks. So what are you doing differently that time? Struggling to see the difference.

**Comment by ripcurld0** [comment] 2017-06-05 08:35
I used to do `docker logs`, but this time I `curl`-ed to `containers/{id}/logs`.
I guess `"` and `)` has something to do with determining the extra bytes to read. However, I might be wrong.

I am continuing investigating this, though.

**Comment by ripcurld0** [comment] 2017-06-05 09:08
@scottrobertson @thaJeztah it seems like the problem is in the container configurations.

@scottrobertson you should attach a standard stream to a `Tty` to read the data clearly.
In other words, when creating a new container, set `Tty` to `true`:
```json
{
 "Image":"sha256:c75bebcdd211f41b3a460c7bf82970ed6c75acaab9cd4c9a4e125b03ca113798",
 "Tty": true,
 "Env":[
            "FILE_NAME=thishas17chars123",
            "FILE_NAME_OTHER=thishas18chars123",
            "FILE_NAME_OTHER_OTHER=thishas19chars1234"
           ],
 "Cmd":["printenv"]
}
```

**Comment by scottrobertson** [comment] 2017-06-05 09:21
@ripcurld0 that works! Thank you.

Isn't that just for output? Why would that effect the reading of env vars inside the container?

To be clear, what sparked this is because `$FILE_NAME_OTHER` didn't exist when it had more than 17 chars.

**Comment by ripcurld0** [comment] 2017-06-05 09:26
Yes it is. My guess it effects that because you want to communicate with the container and you have to do that through a TTY.

**Comment by scottrobertson** [comment] 2017-06-05 09:34
Yeah that makes sense. Does this ticket need to stay open? I feel like this could be super confusing for people. Surprised it has not come up before.

**Comment by thaJeztah** [comment] 2017-06-05 11:43
The logs API endpoint is a multiplexed stream of stdout and stderr, and uses a wire format with the first couple of bytes encoding extra information; IIRC, the format with a TTY attached is slightly different, which may explain this. Also see https://github.com/moby/moby/pull/33494

**Comment by ripcurld0** [comment] 2017-06-05 12:09
@thaJeztah I was looking for that PR to reference it here. Thank you so much.

**Comment by ripcurld0** [comment] 2017-06-06 14:28
@thaJeztah What is needed to close this issue?

**Comment by ripcurld0** [comment] 2017-11-12 08:28
Closing this as it seems like resolved.

**Closed by ripcurld0** 2017-11-12 08:28 UTC
Labels: kind/question, platform/desktop, version/17.03
