### ISSUE TITLE
docker container ls --format="{{ json .Ports }}" incorrectly encoding \u003e instead of ">"

### ISSUE THREAD

**Issue by DazWilkin** [moby/moby#32120] opened 2017-03-26 22:48 UTC
Discovered format={{ json . }}
https://docs.docker.com/engine/admin/formatting/#json

The port mappings are incorrectly [en|de]coded

E.g.
```
"0.0.0.0:8080-\u003e8080/tcp"
```
Instead of
```
"0.0.0.0:8080->8080/tcp"
```
**Repro**

```
docker container ls --format="{{ json .Ports }}"
docker ps --format="{{ json .Ports }}
```

**Describe the results you received:**

String include unicode (`\u003e`) instead of "`>`"
```
"0.0.0.0:9000-\u003e9000/tcp"
"0.0.0.0:8080-\u003e8080/tcp"
```

**Describe the results you expected:**

jq works as expected
```
docker container ls --format="{{ json . }}" | jq .Ports
"0.0.0.0:9000->9000/tcp"
"0.0.0.0:8080->8080/tcp"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 16
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 118
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: [REDACTED]
 Is Manager: true
 ClusterID: [REDACTED]
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.156
 Manager Addresses:
  192.168.1.156:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.31 GiB
Name: [REDACTED]
ID: [REDACTED]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: [REDACTED]
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by gianarb** [comment] 2017-03-27 09:22
I can confirm, I have the same problem with Docker For Mac

```bash
$ docker run -d -p 80:80 nginx
$ docker container ls -a --format="{{ json .Ports }}"
"0.0.0.0:80-\u003e80/tcp, 443/tcp"
```

```
10:22 $ docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: YRCF:2KYL:PGQJ:MFYS:D7JP:JPTW:525H:CAQN:HX5M:LAVJ:5YD7:VE3K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 32
 System Time: 2017-03-27T09:22:26.234462137Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```
10:22 $ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by ripcurld0** [comment] 2017-03-27 14:53
It seems like json.Marshal does HTML escape:
https://github.com/golang/go/issues/8592
https://github.com/golang/go/issues/3127

**Comment by thaJeztah** [comment] 2017-03-27 15:02
Yes, the characters are JSON encoded, and probably use unicode notation for these (if I remember correctly, there was an option to have more "readable" escaping, which was added to the JSON-files logs at some point), but I'll have to search for that one

**Comment by thaJeztah** [comment] 2017-03-27 15:24
This was the pull request I had in mind https://github.com/docker/docker/pull/27060 (and the associated issue https://github.com/docker/docker/issues/27021)

**Comment by dockercore** [comment] 2017-03-27 15:28
docker

**Comment by dockercore** [comment] 2017-03-27 15:30
➜  ~ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by dockercore** [comment] 2017-03-27 15:32
[root@dockercore ~]# docker info
Containers: 52
 Running: 20
 Paused: 0
 Stopped: 32
Images: 258
Server Version: 17.03.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-919020-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 42.88 GB
 Data Space Total: 107.4 GB
 Data Space Available: 24.78 GB
 Metadata Space Used: 60.89 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.087 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 7egjckmfee686t21ungi86hqy
 Is Manager: true
 ClusterID: acjxcvhu9f96omfo4eex47kt4
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.170.178.15
 Manager Addresses:
  10.170.178.15:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.26 GiB
Name: iZ256nsa3keZ
ID: 2F63:XW3D:2BFR:46IC:6M3S:HGAY:GBUL:FA2K:I52A:3MHK:VBOM:EPOK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by ripcurld0** [comment] 2017-03-27 15:35
@thaJeztah that's fine but it looks like this won't compile in Go < 1.7.
Should we still use the `SetEscapeHTML` function?

**Comment by ripcurld0** [comment] 2017-03-27 15:38
OK, we might use these two:
https://github.com/docker/docker/pull/27060/commits/0fa20ad13b0b5c6d1bf8a8285717c07697d079ba
https://github.com/docker/docker/pull/27139/commits/d1d505fa701bfe28a59afee8158994cf33ef043c

can I call #dibs on this?

**Comment by thaJeztah** [comment] 2017-03-27 15:38
@dockercore there's no need to add more version/info output. The issue is "confirmed", but being looked into as to what the right approach is for resolving this. Also, if you post info, please add some context; randomly adding `docker version` and `docker info` without any context is usually only adding noise, and not helpful.

@ripcurld0 good question; I see a follow-up PR was created (https://github.com/docker/docker/pull/27139) to keep 1.6 compatibility, although we may want to consider deprecating that, now that go 1.8 is around the corner

**Comment by thaJeztah** [comment] 2017-03-27 15:39
And, yes, feel free to #dibs :)

**Closed** 2017-05-09 21:54 UTC
Labels: area/cli, kind/bug, status/claimed, version/17.03
