### ISSUE TITLE
Docker show crashed in /etc/init.d/docker status

### ISSUE THREAD

**Issue by qaz25323100** [moby/moby#23628] opened 2016-06-16 16:09 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   4dc5990
 Built:        
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `uname -rv`:**

```
4.4.6-gentoo #5 SMP Thu Jun 16 11:52:34 CST 2016 Intel(R) Core(TM) i5-4340M CPU @ 2.90GHz
```

**Output of `sudo ./check-config.sh`:**

```
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-4.4.6-gentoo ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: missing
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: missing
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: enabled
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: missing
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: missing
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```

**Steps to reproduce the issue:**
1.

```
sudo /etc/init.d/docker status
 * status: crashed * 
```

**Comment by nathanleclaire** [comment] 2016-06-16 16:37
If you restart the service does it work?

What configuration are you attempting to launch the daemon with?

What's the in log indicating the cause of the crash? (frequently `/var/log/docker.log` or `sudo journalctl -u docker.service` on systemd)

**Comment by qaz25323100** [comment] 2016-06-17 00:40
yep.
```
 $ sudo /etc/init.d/docker status
 * status: crashed
 $ sudo /etc/init.d/docker restart
 * Stopping docker ...                                                                                         [ ok ]
 * Starting docker ...                                                                                         [ ok ]
 $ sudo /etc/init.d/docker status
 * status: crashed
```

I did't set the configuration yet.

**Output of /var/log/docker.log:**
```
time="2016-06-17T08:39:46.908257301+08:00" level=info msg="New containerd process, pid: 3906\n" 
time="2016-06-17T08:39:47.946375894+08:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed" 
time="2016-06-17T08:39:47.946441166+08:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed" 
time="2016-06-17T08:41:41.961796311+08:00" level=info msg="previous instance of containerd still alive (3906)" 
time="2016-06-17T08:41:41.988239604+08:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed" 
time="2016-06-17T08:41:41.988302403+08:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed"
```

**Comment by archenroot** [comment] 2018-02-12 11:32
I am in similar situation, docker was running, I stopped and created new daemon.json file, it didn't work due to some issue with network configuration:
```
time="2018-02-12T12:02:17+01:00" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." module=containerd type=io.containerd.runtime.v1                                                                                                                            
time="2018-02-12T12:02:17+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." module=containerd type=io.containerd.grpc.v1                                                                                                                                  
time="2018-02-12T12:02:17+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1                                                                                                                                
time="2018-02-12T12:02:17+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1                                                                                                                          
time="2018-02-12T12:02:17+01:00" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"                                                                                                                          
time="2018-02-12T12:02:17+01:00" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc" 
time="2018-02-12T12:02:17+01:00" level=info msg="containerd successfully booted in 0.002984s" module=containerd 
time="2018-02-12T12:02:17.864042055+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2018-02-12T12:02:17.864787503+01:00" level=info msg="Loading containers: start."
Error starting daemon: Error initializing network controller: Error creating default "bridge" network: auxilairy address: (DefaultGatewayIPv4:0.0.0.0) must belong to the master pool: 172.17.29.0/24

```

Ok, I tried to change it and finally even removed the daemon.json file completely, but cannot start docker anymore, no valuable log available :-)
```
mobile-server /etc/docker # docker version
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Jan 24 11:48:52 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

check-config.sh output:
```
mobile-server /etc/docker # sh /usr/share/docker/contrib/check-config.sh
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled
- CONFIG_IP_NF_NAT: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
    (cgroup swap accounting is currently enabled)
- CONFIG_LEGACY_VSYSCALL_EMULATE: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_IP_VS: enabled
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_RR: enabled
- CONFIG_EXT3_FS: enabled
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled
  - "ipvlan":
    - CONFIG_IPVLAN: enabled
  - "macvlan":
    - CONFIG_MACVLAN: enabled
    - CONFIG_DUMMY: enabled
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: enabled
    - CONFIG_NF_CONNTRACK_FTP: enabled
    - CONFIG_NF_NAT_TFTP: enabled
    - CONFIG_NF_CONNTRACK_TFTP: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled
  - "zfs":
    - /dev/zfs: present
    - zfs command: available
    - zpool command: available

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```
Some tries to start:
```
mobile-server /etc/docker # /etc/init.d/docker status
 * status: crashed
mobile-server /etc/docker # /etc/init.d/docker start 
 * WARNING: docker has already been started
mobile-server /etc/docker # /etc/init.d/docker stop 
 * Stopping docker ...
 * Failed to stop docker                                                                                                                                                               [ !! ]
 * ERROR: docker failed to stop
mobile-server /etc/docker # /etc/init.d/docker restart
 * Stopping docker ...
 * Failed to stop docker                                                                                                                                                               [ !! ]
 * ERROR: docker failed to stop
mobile-server /etc/docker # 
```
After these commands no message in docker.log, only some info in messages:
```
Feb 12 12:20:44 mobile-server /etc/init.d/docker[24419]: status: crashed
Feb 12 12:20:46 mobile-server /etc/init.d/docker[24422]: WARNING: docker has already been started
Feb 12 12:20:49 mobile-server /etc/init.d/docker[24426]: ERROR: docker failed to stop
Feb 12 12:20:52 mobile-server /etc/init.d/docker[24453]: ERROR: docker failed to stop
Feb 12 12:21:27 mobile-server /etc/init.d/docker[24535]: WARNING: docker has already been started
Feb 12 12:21:30 mobile-server /etc/init.d/docker[24542]: ERROR: docker failed to stop

```
But I found a docker unix socket:
```
mobile-server /var/run # ls -la |grep docker
drwx------  6 root root    120 Feb 12 12:02 docker
srw-rw----  1 root docker    0 Feb 12 12:02 docker.sock

```
I deleted both entries, but no help. something somewhere is still telling docker not to start, will need to examine startup scripts, attached is strace from command /etc/init.d/docker start if it can help realize what is wrong. Usually after I reboot machine all works, this is not first time I experience this situation.
[docker-start.strace.txt](https://github.com/moby/moby/files/1716125/docker-start.strace.txt)

**Comment by archenroot** [comment] 2018-02-12 11:37
I have now received system updates where is also set of upgraded components of docker:
```
# required by app-emulation/docker-18.02.0::gentoo
# required by @selected
# required by @world (argument)
=app-emulation/containerd-1.0.1 ~amd64
# required by app-emulation/docker-18.02.0::gentoo
# required by @selected
# required by @world (argument)
=app-emulation/docker-runc-1.0.0_rc4_p20180122 ~amd64
# required by app-emulation/docker-18.02.0::gentoo
# required by @selected
# required by @world (argument)
=app-emulation/docker-proxy-0.8.0_p20180112 ~amd64

and docker itself is going to upgrade as well to:
# required by app-emulation/docker-18.02.0::gentoo
# required by @selected
# required by @world (argument)
=app-emulation/containerd-1.0.1 ~amd64
# required by app-emulation/docker-18.02.0::gentoo
# required by @selected
# required by @world (argument)
=app-emulation/docker-runc-1.0.0_rc4_p20180122 ~amd64
# required by app-emulation/docker-18.02.0::gentoo
# required by @selected
# required by @world (argument)
=app-emulation/docker-proxy-0.8.0_p20180112 ~amd64
```
So I will try to upgrade and test again.

**Comment by thaJeztah** [comment] 2023-06-06 07:52
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637

**Closed by thaJeztah** 2023-06-06 07:52 UTC
Labels: area/storage/devicemapper, version/1.11
