### ISSUE TITLE
Unable to fork: Cannot allocate memory

### ISSUE THREAD

**Issue by ninchan8328** [moby/moby#23342] opened 2016-06-07 14:28 UTC
Hi Docker Expert,

root@myserver:~# docker --version
Docker version 1.10.1, build 9e83765
root@myserver:~# docker-compose --version
docker-compose version 1.7.1, build 0a9ab35

I am using the docker-compose v2 to spin up multiple containers and its been working fine until today I see a weird problem that when I try to run command (docker exec) on one of the container, it return Cannot allocate memory, but the other container that created in the same docker-compose file worked fine. Any idea?

root@myserver:~# docker exec jenkinsci_server01_1 ls
nsenter: Unable to fork: Cannot allocate memory
root@myserver:~# docker exec jenkinsci_server02_1 ls
bin
dev
etc
home
lib
lib64
lost+found
media
mnt
opt
proc
root
sbin
selinux
srv
sys
tmp
usr
var
workspace

Memory info:
cat /proc/meminfo
MemTotal: 6112100 kB
MemFree: 638020 kB
MemAvailable: 3580192 kB
Buffers: 104184 kB
Cached: 2841936 kB
SwapCached: 15492 kB
Active: 2332772 kB
Inactive: 2013724 kB
Active(anon): 700092 kB
Inactive(anon): 1026608 kB
Active(file): 1632680 kB
Inactive(file): 987116 kB
Unevictable: 192 kB
Mlocked: 192 kB
SwapTotal: 6291452 kB
SwapFree: 5960096 kB
Dirty: 2268 kB
Writeback: 0 kB
AnonPages: 1394356 kB
Mapped: 429496 kB
Shmem: 326324 kB
Slab: 916848 kB
SReclaimable: 575768 kB
SUnreclaim: 341080 kB
KernelStack: 22720 kB
PageTables: 52304 kB
NFS_Unstable: 0 kB
Bounce: 0 kB
WritebackTmp: 0 kB
CommitLimit: 9347500 kB
Committed_AS: 11739424 kB
VmallocTotal: 34359738367 kB
VmallocUsed: 161396 kB
VmallocChunk: 34359478128 kB
HardwareCorrupted: 0 kB
AnonHugePages: 473088 kB
HugePages_Total: 0
HugePages_Free: 0
HugePages_Rsvd: 0
HugePages_Surp: 0
Hugepagesize: 2048 kB
DirectMap4k: 83904 kB
DirectMap2M: 6207488 kB

**Comment by ninchan8328** [comment] 2016-06-09 15:12
anyone?

**Comment by codingwangfeng** [comment] 2017-06-29 08:35
up

**Comment by thaJeztah** [comment] 2017-06-29 08:40
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-06-29 08:40 UTC

**Comment by codingwangfeng** [comment] 2017-06-30 03:55
hi, yesterday we meet this problem. it is like is,
error msg:
`-bash: fork:cannot allocate memory
`
I google it then got following two points:

1. the msg tell us memory, but I think it is a ambiguous log output. It is about fork not malloc, so it is perhaps a memory pool or array table is limited. Not the machine RES.
2. kernel.pid_max ，n=`ps -eLf |wc -l`，please check the 2 number of your env.  if n > kernel.pid_max please reset kernel.pid_max to bigger
