### ISSUE TITLE
The bridge network can't automatically configure the gateway successfully upon system startup.

### ISSUE THREAD

**Issue by hongyi-zhao** [moby/moby#41618] opened 2020-11-01 23:55 UTC
Hi,

On Ubuntu 20.04, I noticed that the bridge network can't automatically configure the gateway successfully upon system startup as shown below:
```
werner@X10DAi-01:~$ ip a s docker0
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:66:57:28:7c brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
werner@X10DAi-01:~$ docker inspect bridge 
[
    {
        "Name": "bridge",
        "Id": "7fc0c73c26353ad35bf6bb8b031939372d8e1e6bdafa05ec1529b83483f405de",
        "Created": "2020-11-02T07:35:59.776045078+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

```

OTOH, this problem will be fixed with the following command:

```
werner@X10DAi-01:~$ sudo systemctl restart docker
werner@X10DAi-01:~$ docker inspect bridge 
[
    {
        "Name": "bridge",
        "Id": "b7e8a8e72601b065cac843d6d4304a85eaa12d54f49f7f8d9becf10298663e43",
        "Created": "2020-11-02T07:53:25.081832089+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

```

The OS/docker info for my case:
```

werner@X10DAi-01:~$ docker version 
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
werner@X10DAi-01:~$ docker info 
Client:
 Debug Mode: false

Server:
 Containers: 15
  Running: 0
  Paused: 0
  Stopped: 15
 Images: 50
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 88
 Total Memory: 251.8GiB
 Name: X10DAi-01
 ID: 2YEO:XZF6:4KDC:XXSO:2WLQ:DRAE:EQWX:ID2C:376M:P7S2:G4KC:BN4U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://127.0.0.1:8080/
 HTTPS Proxy: http://127.0.0.1:8080/
 No Proxy: localhost,127.0.0.1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
werner@X10DAi-01:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```

I'm very confused on this phenomenon, any hints will be highly appreciated.

Regards,
HY

**Comment by thaJeztah** [comment] 2020-11-02 15:16
Thanks for reporting; this looks like a duplicate of https://github.com/moby/moby/issues/26799, which (if I see that discussion) has not been looked into yet 😞. From that description, looks like it's only happening the first time the daemon is started

**Comment by thaJeztah** [comment] 2023-09-17 22:06
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 22:06 UTC
Labels: kind/bug, area/networking
