### ISSUE TITLE
Docker daemon crash 

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#35575] opened 2017-11-22 15:22 UTC
The sock is not available in a container :

`Provider connection error Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?, retrying in 10.20560755s`

[logs.txt](https://github.com/moby/moby/files/1496491/logs.txt)

Docker swarm version

> $ docker version
> Client:
>  Version:      17.11.0-ce
>  API version:  1.34
>  Go version:   go1.8.3
>  Git commit:   1caf76c
>  Built:        Mon Nov 20 18:37:39 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.11.0-ce
>  API version:  1.34 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   1caf76c
>  Built:        Mon Nov 20 18:36:09 2017
>  OS/Arch:      linux/amd64
>  Experimental: false
>

**Comment by sylvainmouquet** [comment] 2017-11-22 15:43
Another stacktrace

[logs2.txt](https://github.com/moby/moby/files/1496570/logs2.txt)

**Comment by thaJeztah** [comment] 2017-11-22 15:55
Could you provide steps to reproduce?

**Comment by thaJeztah** [comment] 2017-11-22 16:25
Thanks!

**Comment by thaJeztah** [comment] 2017-11-22 16:26
ping @mlaventure @tonistiigi @simonferquel PTAL

**Comment by sylvainmouquet** [comment] 2017-11-22 16:43
The problem not occurs with version 17.10-ce

**Comment by mlaventure** [comment] 2017-11-22 16:49
Go is complaining of a concurrent map writes (in the second log, the first one is truncated, so the cause of the panic is unknown), but the only write I can see if always behind a lock :thinking: 

Will try to have a longer look later.

**Comment by tonistiigi** [comment] 2017-11-22 17:13
@mlaventure `container.ExecCommands` is locked but `d.execCommands` is not. Is there a way to avoid this pattern where multiple specific locks are needed by the caller and exec store has some public methods that are safe to be called concurrently and some that are not. Seems fragile.

**Comment by mlaventure** [comment] 2017-11-22 17:41
Oh indeed, good catch.

I agree this pattern is quite annoying. We'd need to find a way to sync the `Exec` call with the `ProcessEvents` of the daemon (the of handling the `ExitEvent`). We only get the pid back from the `containerd` so it needs to be registered by then or we'll leak the exec config. 

I think the `byPid` can be removed, from memory I initially added it when the process-id wasn't returned by `containerd` and forgot to remove it when we started to get this field back.

**Comment by thaJeztah** [comment] 2018-07-11 20:56
@mlaventure looks like this can be closed (fixed by https://github.com/moby/moby/issues/35575, correct?)

**Comment by mlaventure** [comment] 2018-07-13 16:44
Indeed, Closing it.

Thanks!

**Closed by mlaventure** 2018-07-13 16:44 UTC
Labels: area/daemon, area/swarm, kind/bug
