### ISSUE TITLE
standard_init_linux.go:195: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by dockerPractice** [moby/moby#35447] opened 2017-11-09 08:29 UTC
/kind bug
/kind error
/sig docker
/sig openwrt

**What happened**:
I can't run this command in Raspberry Pi3 Raspbian docker.
`# docker run -i -t openwrt-x86-generic-rootfs /bin/ash`

**What you expected to happen**:
I want to run that command, and setting Open WRT environmant

**How to reproduce it (as minimally and precisely as possible)**:
First, I pulled the docker images for Open WRT by root .

```
# docker import http://downloads.openwrt.org/attitude_adjustment/12.09/x86/generic/openwrt-x86-generic-rootfs.tar.gz openwrt-x86-generic-rootfs
```
And then, I checked my images
```
# docker images

REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
openwrt-x86-generic-rootfs   latest              9015fa51eb3f        48 seconds ago      5.28MB
<none>                       <none>              e4205a844e2b        19 minutes ago      5.28MB
```
So, I run this command, but printed error massage like this
```
# docker run -i -t openwrt-x86-generic-rootfs /bin/ash

standard_init_linux.go:195: exec user process caused "exec format error"
```
I just want to set up Open WRT environment by Raspberry Pi3 on Raspbian with Docker..
What should I do?

**Anything else we need to know?**:

**Environment**:
- Docker version (use `docker version`):
```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:13:44 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:06:18 2017
 OS/Arch:      linux/arm
 Experimental: false
```
- Cloud provider or hardware configuration: `Raspberry Pi3 on Raspbian`

- OS (use `uname -a`): `Raspbian GNU/Linux 9 (stretch)`

- Kernel (e.g. `uname -a`): `Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux`

- Install tools: Docker-CE v17.10
- Others:

※ P.S : Could you recommend the way that how to set up Open WRT environment using docker images?

**Comment by dockerPractice** [comment] 2017-11-09 08:52
한국인 없나요 한국인...

**Comment by AkihiroSuda** [comment] 2017-11-09 12:38
한국인이 아니지만, ARM 위에서 x86 의 바이너리는 돈작 할수 없는데

**Comment by AkihiroSuda** [comment] 2017-11-09 12:41
(you can't run x86 binaries on ARM)

**Comment by thaJeztah** [comment] 2017-11-09 12:44
Yes, looks like you're trying to run binaries for a different architecture, which won't work.

Let me close this issue, because this is not a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2017-11-09 12:44 UTC
Labels: kind/question, platform/arm, version/17.10

**Comment by dockerPractice** [comment] 2017-11-10 00:38
Could you recommend the Open WRT Image on my docker environment?

**Comment by thaJeztah** [comment] 2017-11-10 00:44
no idea; sounds like a better question for the Open WRT community; this showed up when Googling; https://forum.openwrt.org/viewtopic.php?id=28100
