### ISSUE TITLE
docker pull http_proxy / https_proxy dynamically (not in systemd)

### ISSUE THREAD

**Issue by azhurbilo** [moby/moby#39851] opened 2019-09-02 18:35 UTC
**Description**

Now to enable HTTP_PROXY / HTTPS_PROXY to pull images from proxy, you need add it to systemd configuration and **restart dockerd daemon**
https://docs.docker.com/engine/reference/commandline/pull/#proxy-configuration

It's blocker for Production envs due to several points:
1. Daemon restart lead to containers restart
2. When proxy server is down you need change it to other proxy as fast as possible

**Describe the results you expected:**

docker cli (docker-compose) should use values from env vars

```
export HTTP_PROXY=xxx
export HTTPS_PROXY=xxx
docker pull XXX
docker-compose pull
```

**Comment by thaJeztah** [comment] 2019-09-30 15:21
I don't think this would work, because (afaik) updating the environment variable won't be picked up by an already running process

@kolyshkin

**Comment by joshuafc** [comment] 2020-08-19 06:09
any update?

**Comment by thaJeztah** [comment] 2021-05-18 11:32
looks like this is a duplicate of https://github.com/moby/moby/issues/37335 - let me close this one to prevent the conversation from diverging

**Closed by thaJeztah** 2021-05-18 11:32 UTC
Labels: area/distribution, kind/enhancement
