### ISSUE TITLE
WSL2: files in a bind mounted folder can be accessed with case insensitivity

### ISSUE THREAD

**Issue by stellirin** [moby/moby#40164] opened 2019-11-01 10:26 UTC
A file in a bind mounted folder is accessed with case insensitivity.

This was found when debugging why a file added to a container image could not be read, but the same file accessed through a bind mounted folder could be read. (The application had a configuration error with incorrect case used for a file name.)

**Steps to reproduce the issue:**
Save the below shell script as `test.sh` somewhere on the Windows file system:

```sh
#!/bin/sh

function file_exists() {
    local TEST_FILE_PATH=$1
    local TEST_FILE_NAME=$(basename $1)
    if [ -f "${TEST_FILE_PATH}" ]
    then
        echo "File '${TEST_FILE_NAME}' exists."
    else
        echo "File '${TEST_FILE_NAME}' does not exist."
    fi
}

ls -l /folder/

file_exists "/folder/test.sh"
file_exists "/folder/Test.sh"
```
Run the following from a WSL2 bash shell:
```
docker run --volume="${PWD}:/folder" alpine /folder/test.sh
```

**Describe the results you received:**

```
total 4
-rwxr-xr-x    1 1000     1000           348 Nov  1 10:09 test.sh
File 'test.sh' exists.
File 'Test.sh' exists.
```

**Describe the results you expected:**

```
total 4
-rwxr-xr-x    1 1000     1000           348 Nov  1 10:09 test.sh
File 'test.sh' exists.
File 'Test.sh' does not exist.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 2
  Paused: 0
  Stopped: 8
 Images: 841
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.75-microsoft-standard
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.24GiB
 Name: AFA-PC
 ID: HYRF:XWKO:AYX5:6IRX:7IBY:V5NG:XEEW:ZE67:XWMT:OUGV:EKKX:3MLF
 Docker Root Dir: /var/data/docker-desktop/default/daemon-data
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 61
  System Time: 2019-11-01T11:21:37.3389283+01:00
  EventsListeners: 1
 Username: afaincentage
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2019-12-11 12:09
@StefanScherer @simonferquel ptal

**Comment by simonferquel** [comment] 2019-12-11 14:17
What is your working directory when executing this?

**Comment by stellirin** [comment] 2019-12-11 17:18
Good question, I didn't think to test the difference between the VM file system and the host file system.

*VM file system*
```
$ cd ~/moby/40164/
$ docker run --volume="${PWD}:/folder" alpine /folder/test.sh
total 4
-rwxr-xr-x    1 1000     1000           347 Dec 11 17:11 test.sh
File 'test.sh' exists.
File 'Test.sh' does not exist.
```

*Host file system*
```
$ cd /c/moby/40164/
$ docker run --volume="${PWD}:/folder" alpine /folder/test.sh
total 0
-rwxr-xr-x    1 1000     1000           347 Dec 11 17:12 test.sh
File 'test.sh' exists.
File 'Test.sh' exists.
```

**Comment by thaJeztah** [comment] 2019-12-11 17:38
Good call indeed! Looks like that's the expected behavior; should we close this issue?

**Comment by simonferquel** [comment] 2019-12-11 17:53
Yes it is expected. The 9p filesystems where windows files are mounted is case insensitive.

**Comment by stellirin** [comment] 2019-12-11 18:41
Very easy to overlook this, especially as Windows 10 does now track the unix file permissions. Fortunately a quick search finds that we _can_ enable case sensitivity on a Windows folder, and it does propagate as expected:

```
C:\moby\40164>fsutil.exe file setCaseSensitiveInfo C:\moby\40164
Case sensitive attribute on directory C:\moby\40164 is enabled.

C:\moby\40164>wsl.exe
/c/moby/40164$ docker run --volume="${PWD}:/folder" alpine /folder/test.sh
total 0
-rwxr-xr-x    1 1000     1000           347 Dec 11 17:11 test.sh
File 'test.sh' exists.
File 'Test.sh' does not exist.
```

**Comment by thaJeztah** [comment] 2019-12-11 18:54
Thanks! Let me go ahead and close; perhaps something to add to the documentation though

**Closed by thaJeztah** 2019-12-11 18:54 UTC
Labels: platform/windows, version/19.03
