### ISSUE TITLE
--net=host fails for Docker-in-Docker with sysbox

### ISSUE THREAD

**Issue by spikecurtis** [moby/moby#45681] opened 2023-06-02 05:15 UTC
### Description

If we run Docker in Docker with the outer container using the [sysbox](https://github.com/nestybox/sysbox) container runtime, then in the inner container if we use `--net=host` it fails like:

```
$ docker run -it --rm --net=host alpine:latest whoami
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
8a49fdb3b6a5: Pull complete 
Digest: sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11
Status: Downloaded newer image for alpine:latest
docker: Error response from daemon: failed to create default sandbox: permission denied.
```

git-bisecting, I've determined that https://github.com/moby/moby/commit/0246332954e3872995faa951d4bbe530eaac7d8f introduces the bug.

I think the relevant code is

```
func createNetworkNamespace(path string, osCreate bool) error {
	if err := createNamespaceFile(path); err != nil {
		return err
	}

	do := func() error {
		return mountNetworkNamespace(fmt.Sprintf("/proc/self/task/%d/ns/net", unix.Gettid()), path)
	}
	if osCreate {
		return unshare.Go(unix.CLONE_NEWNET, do, nil)
	}
	return do()
}
```

~When you use `--net=host`, osCreate=false and so `do()` is called without `unshare`.  I think what's happening is that there is a subtle bug where `unix.Gettid()` is called to fill out the `/proc/` path, but without `unshare` the actual system call happens on a different thread.  On a "regular" Docker install, with the daemon running in the root namespace, Linux lets this mount system call succeed, but inside sysbox, mounting the network namespace of one thread from a different thread is forbidden.~

When I change the mount call to use `/proc/thread-self/ns/net` instead, things work fine.  ~PR coming shortly.~

### Reproduce

1. Install Docker and [sysbox](https://github.com/nestybox/sysbox)
2. Run a generic Linux inner container, e.g. Ubuntu, with the sysbox container runtime
3. In the inner container, install Docker v24
4. In the inner container, `docker run -it --rm --net=host alpine:latest whoami`

### Expected behavior

```
$ docker run -it --rm --net=host alpine:latest whoami
root
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 31
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-1095-gke
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.81GiB
 Name: dogfood
 ID: b35b4709-efd9-43f2-804f-5c95ddc10fb9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.gcr.io/
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Additional Info

docker version and docker info are for the _inner_ Docker daemon

**Comment by dmarteau** [comment] 2023-06-06 08:17
Same issue with Sysbox 5.2.0 and Docker 23.0.6

**Comment by jpeeler** [comment] 2023-06-08 00:12
For awareness @ctalledo. Also had problems with 24.0.2, so upgraded sysbox.

Docker 23.0.4 works with Sysbox 0.6.1.

**Comment by neersighted** [comment] 2023-06-09 18:33
If this reproduces on 23.0.6, it can't be https://github.com/moby/moby/commit/0246332954e3872995faa951d4bbe530eaac7d8f, as that commit was only ever taken on the 24.0 branch.

**Comment by ctalledo** [comment] 2023-06-09 19:04
I've not had a chance to look into this, but while Sysbox does emulate portions of `/proc` inside a Sysbox container, it does not do any such emulation for `/proc/thread-self/ns/net` or `/proc/self/...` or `/proc/<pid>/...`. In other words, if a programs inside a Sysbox container accesses those `/proc` subdirs, the access goes directly to the Linux kernel.

The one difference of course between regular Docker-in-Docker and running Docker-in-Docker with Sysbox, is that the latter is an unprivileged (i.e., user-namespaced) container but it's not clear to me why that would matter in this case.

**Comment by spikecurtis** [comment] 2023-06-20 08:55
I've gotten back to looking at this, and experimented with bind-mounting different `/proc` targets from within a user namespace.

Example go program

```
package main

import (
	"runtime"
	"fmt"
	"syscall"
	"os"
)

func main() {
	runtime.LockOSThread()
	fmt.Printf("uid: %d\n", syscall.Getuid())
	basePath := fmt.Sprintf("/proc/self/task/%d/ns/net", syscall.Gettid())
	fmt.Println(basePath)
	lnPath := "/var/namespace/test"
	f, err := os.Create(lnPath)
	if err != nil {
		fmt.Printf("failed to create %s: %s\n", lnPath, err)
		os.Exit(1)
	}
	f.Close()
	err = syscall.Mount(basePath, lnPath, "bind", syscall.MS_BIND, "")
	if err != nil {
		fmt.Printf("failed to bind-mount %s: %s\n", basePath, err)
		os.Exit(1)
	}
	runtime.UnlockOSThread()
}
```

I tried this from Ubuntu with kernel 5.15.0-67-generic.

When running from within a user namespace, this fails for both `/proc/thread-self/ns/net` and `/proc/self/task/<tid>/ns/net` unless I also run in a mount namespace, e.g. 

```
unshare --user --mount --map-root-user ./bmount
```

With both user and mount namespace, both `/proc` paths succeed, with user namespace only, both paths fail.

**Comment by nudgegoonies** [comment] 2023-08-07 12:03
I can confirm for Sysbox 0.6.2, Docker 24.0.5 on Debian 11. Docker daemon on our gitlab-runner hosts and docker client within our build images is 24.0.5. Our temporary workaround is using Docker 23.0.6 for the dind rather than 24.0.5.

**Comment by dmarteau** [comment] 2023-10-09 16:56
I don't know if this is related but using Sysbox wth Docker 24.0.+  in sysbox container prevent attaching overlay networks to any service (swarm or standalone containers with the `--attachable` option).  

- Reverting to 23.0.6 in sysbox container is fine (host docker is 24.0.6)
- Same containerd version 1.6.24 in Sysbox container and on host.

**Comment by cruizba** [comment] 2023-10-20 13:50
This is happening to me too.

It is easily reproducible with this command:

```
docker run -it --runtime=sysbox-runc cruizba/ubuntu-dind:jammy-24.0.6 docker run -it --network=host ubuntu
```

Host:
- Ubuntu 22.04
- Sysbox: 0.6.2
- Docker version: 
```
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```
  
  DinD image:
  - Ubuntu: 22.04
  - Docker version:
  ```
  Client:
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:30:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.3
  GitCommit:        7880925980b188f4c97b462f709d0db8e8962aff
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ctalledo** [comment] 2023-11-20 05:08
Hi folks, FYI the problem was a bug in the way Sysbox was intercepting mount system calls when the mount path has the form /proc/self/task/<tid>/.....

It's now fixed in Sysbox upstream; see [here](https://github.com/nestybox/sysbox/issues/712#issuecomment-1818235589) for more info.

I think we can close this ticket now (the problem is in Sysbox, not in Moby).

**Closed** 2023-11-20 07:59 UTC
Labels: status/0-triage, kind/bug, area/networking, version/24.0

**Comment by ctalledo** [comment] 2023-12-02 20:49
Hi @xabru,

> Does it mean that you have to build sysbox from source to solve this problem?

Yes, until a we do a new Sysbox release; we expect to do a new one by mid December.
