### ISSUE TITLE
docker export create empty file

### ISSUE THREAD

**Issue by cmskzhan** [moby/moby#35884] opened 2017-12-27 10:53 UTC
My container doesn't seem to be exported properly when stopped. Below is the container

$ docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                    PORTS               NAMES
4cd18933814b        docker.io/jupyter/datascience-notebook   "tini -- start-notebo"   14 hours ago        Exited (0) 13 hours ago                       notebook

$ docker export notebook > notebookFromhome.tar
$ ll
total 3
-rw-rw-r--. 1 sroot sroot **1024** Dec 27 10:06 notebookFromhome.tar

Environment is as below:
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-67275855-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
...
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-693.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
...
ID: NMOX:V573:NPTB:H2F7:YGZT:VCEA:RBBQ:7RGP:P5F3:4NRB:DRS6:I75T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

Tried -o option, tried use containerID same result. 

However, it works if I start the container.

**Comment by Dayanand-Chinchure** [comment] 2018-01-04 12:23
Can you please share the image name here. Thanks !

**Comment by thaJeztah** [comment] 2018-01-04 14:59
Looks like you're running the Red Hat fork of Docker, which has a lot of modifications from the official packages. Also note that Docker 1.12.6 has reached end of life in March of last year, and is no longer maintained, nor supported.

I'm not able to reproduce this problem on a current version of Docker;

```bash
$ docker run -d jupyter/datascience-notebook --name notebook
$ docker export notebook > notebookFromhome.tar

$ ls -lah
total 11605424
drwxr-xr-x  3 sebastiaan  staff   102B Jan  4 15:55 .
drwxr-xr-x  4 sebastiaan  staff   136B Jan  4 15:55 ..
-rw-r--r--  1 sebastiaan  staff   5.5G Jan  4 15:47 notebookFromhome.tar
```

Closing this issue because of the above, but let me know if you have more information, and if you're still able to reproduce on a current official build of docker (https://docs.docker.com/engine/installation/linux/docker-ce/centos/)

**Closed by thaJeztah** 2018-01-04 14:59 UTC
