### ISSUE TITLE
Leaked mounts in /run/docker/runtime-runc/moby/

### ISSUE THREAD

**Issue by fasaxc** [moby/moby#41358] opened 2020-08-14 15:10 UTC
**Description**

Using docker as the runtime for kubernetes, after churning lots of pods and then draining the node, have lots of leftover mounts of this form:
```
/dev/xvda1 on /run/docker/runtime-runc/moby/c93ca768678d40f0aa4da68d142da202c7be7fc7f9dead3d93e702cf179c6e76/runc.DWyZhD type ext4 (ro,relatime,discard)
/dev/xvda1 on /run/docker/runtime-runc/moby/4d9b63f00b2ef89941290f73e678c387e9fb883d714fd58383644df27e360981/runc.FoxVRl type ext4 (ro,relatime,discard)
/dev/xvda1 on /run/docker/runtime-runc/moby/f2882ae48993450f884f0e9f5f8d95372bc3bcaf04dc6699ec88d7513e898199/runc.PjjaFr type ext4 (ro,relatime,discard)
...
```

Examining the mounted file, as root, it seems to be the `runc` binary

**Steps to reproduce the issue:**
1. Create 10+ node kubernetes cluster
2. Churn thousands of pods
3.

**Describe the results you received:**

Initial symptom was that systemd was pegged at 85+% CPU, after some digging with strace, found that it was looping examining mounts.  /proc/1/mountinfo showed 1800 mounts even though there were only 2 containers left after draining the node.

**Describe the results you expected:**

All mounts cleaned up.

**Additional information you deem important (e.g. issue happens only occasionally):**

`docker system prune` didn't seem to help.

**Output of `docker version`:**

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:     
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 4
  Paused: 0
  Stopped: 3
 Images: 24
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1021-aws
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: ip-172-16-101-121.us-west-2.compute.internal
 ID: 2EAL:2BTH:4HDO:NHOX:YGYC:ISWP:AILR:C6OB:U464:HYJM:HLJA:P2KI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was on AWS, Ubuntu 20.04, kernel
```
$ uname -a
Linux ip-172-16-101-121.us-west-2.compute.internal 5.4.0-1021-aws #21-Ubuntu SMP Fri Jul 24 09:42:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Searching the docker log with 
```
mount | grep --perl -o '[0-9a-f]{20,}' | xargs -n 1 -I {}  grep {} docker.log
```
the only hits I get are of this form
```
Aug 14 09:39:05 ip-172-16-101-121.us-west-2.compute.internal dockerd[5728]: time="2020-08-14T09:39:05.305501175Z" level=error msg="ab9089c8fa9f8ec515c236d37e6a7252899059247aa06aabcabc2ac530896d83 cleanup: failed to delete container from containerd: no such container"
Aug 14 09:39:05 ip-172-16-101-121.us-west-2.compute.internal dockerd[5728]: time="2020-08-14T09:39:05.305550422Z" level=error msg="Handler for POST /containers/ab9089c8fa9f8ec515c236d37e6a7252899059247aa06aabcabc2ac530896d83/start returned error: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"read init-p: connection reset by peer\\\"\": unknown"
```
(there are lots of hits for those IDs)

in the containerd log, I see hits of this form for those IDs:
```
Aug 14 09:38:46 ip-172-16-101-121.us-west-2.compute.internal containerd[4176]: time="2020-08-14T09:38:46.051777051Z" level=info msg="shim reaped" id=ab9089c8fa9f8ec515c236d37e6a7252899059247aa06aabcabc2ac530896d83
```

**Comment by thaJeztah** [comment] 2020-08-14 15:18
From the output of your `docker info` and `docker version`, it looks like you have the distro-packaged version of docker and containerd installed. If you have a test environment to reproduce in; are you able to reproduce with the official packages as well? (https://docs.docker.com/engine/install/ubuntu/)

**Comment by fasaxc** [comment] 2020-08-14 15:52
@thaJeztah I've installed that version on one of the nodes, we're going to reboot our cluster to see if this node performs better.

It looks like the default configuration of your repo has a different backend?  I don't see any moby/runc mounts any more.

**Comment by thaJeztah** [comment] 2020-08-17 12:00
Thanks for giving it a try!

> It looks like the default configuration of your repo has a different backend? I don't see any moby/runc mounts any more.

Possible. I know there's various differences between the (ubuntu/debian) distro packages and the official packages provided by Docker. At least, the distro packages currently ship with different versions of containerd (version 1.3.x instead of 1.2.x) and runc. While we plan to upgrade to containerd 1.3 or up at some point, and containerd 1.3 and 1.4 _should be_ fully compatible, there might be some differences.

Another area where the distro packages differ is in the versions of build-time Go dependencies that are used. Both Docker / Moby, containerd, and runc are quite specific on the versions of dependencies to use (either in their `go.mod` or `vendor.conf` file). "pinning" dependencies to specific versions (sometimes as granular as pinning to a specific git-commit) is done because at times there are incompatibilities with other versions, or if bug/security-fixes are backported to dependencies.
Distro packages are quite opinionated in how dependency management is handled, and tend to ignore those versions (in favour of a single managed version for any dependency). This unfortunately has often led to subtle, sometimes hard to reproduce bugs.

So, while it's definitely possible there's a bug at hand in our codebase, it would help us to know if the bug also reproduces in the packages we maintain (in case it's related to the way the distro-packages are built/configured).

**Comment by fasaxc** [comment] 2020-08-17 12:39
Don't think I got a repro in either case (nodes configured with your repo or not).  I think the nodes were overloaded in the first test run that we did, which may have made the issue more likely.

**Comment by thaJeztah** [comment] 2020-08-17 13:09
No worries; let me close this ticket for now, but if you happen to get a reproducer, feel free to comment, then I can reopen 👍

**Closed by thaJeztah** 2020-08-17 13:09 UTC
Labels: area/runtime, status/more-info-needed, version/19.03, version/unsupported
