### ISSUE TITLE
[docker.pkg.github.com] Docker pull is not working on 20.10 RC1

### ISSUE THREAD

**Issue by nigurr** [moby/moby#41687] opened 2020-11-18 06:17 UTC
Installed latest docker 20.10 RC1 and trying to pull images from private registry is not working.
It's working for certain private registry server and not working for others (not sure what logs will help you out more)

**Steps to reproduce the issue:**
1. docker login `https://docker.pkg.github.com` -u name -p token
2. docker pull docker.pkg.github.com/github/xxxx/backend:latest

**Describe the results you received:**

```docker: Error response from daemon: manifest for docker.pkg.github.com/github/xxxx/backend:latest not found: manifest unknown: Docker image reference backend:sha256:d3exxxxxxxxx5 not found under repo "github".```

**Describe the results you expected:**

same image pull with docker 19.x works without an issue.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```Client: Docker Engine - Community
 Version:           20.10.0-rc1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        5cc2396
 Built:             Tue Nov 17 22:51:53 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0-rc1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       131bf7e
  Built:            Tue Nov 17 22:50:10 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.0-rc1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-7630-generic
 Operating System: Pop!_OS 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.79GiB
 Name: pop-os
 ID: LNMV:YDEA:GDHT:NAN3:BG2Z:ISUJ:JVDA:ZTYN:B5XL:VCFI:FQYG:QWHN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Comment by cpuguy83** [comment] 2020-11-18 20:12
Thanks. Looks like we need a fallback in https://github.com/moby/moby/pull/41607/commits/e4cf1c733677ff77e51101e2de542373b449b471 for registries that aren't doing pull by digest.

This is, I expect, the same issue as described here: https://github.com/containerd/containerd/issues/3291

This should work with ghcr.

**Comment by tianon** [comment] 2020-11-18 21:24
> Thanks. Looks like we need a fallback in e4cf1c733677ff77e51101e2de542373b449b471 for registries that aren't doing pull by digest.

I'm not sure that makes sense -- this is a pretty special case, and I think there are good reasons this _wasn't_ fixed in `containerd` (in https://github.com/containerd/containerd/issues/3291).

There are essentially two relevant specifications here -- the original Docker Registry API spec and the OCI distribution spec.  Both are pretty clear that `GET` on a digest to the `/manifests/` endpoint should succeed, and IMO having `HEAD` return sucessfully with a valid `Docker-Content-Digest` is supporting evidence that this *should* be supported.

What I would suggest instead is that if it is too difficult for `docker.pkg.github.com` to support pull-by-digest, it should probably be returning a 405 on `HEAD` requests for manifests (which would transparently solve this issue since we would then fallback to `GET` instead, and likely fix `containerd`'s resolver/fetcher too).

Given that https://github.com/containerd/containerd/issues/3291 wasn't actually resolved, users will see similar failures if they try to use those same images in a Kubernetes environment with `containerd` as the runtime, so I think there's really still a pretty good incentive to do *something* here, even if it isn't as optimistic as "adding support for pull-by-digest" -- just responding that `HEAD` isn't supported will solve a large percentage of cases and feels like it should be lower effort.

**Comment by nigurr** [comment] 2020-11-19 03:37
I can confirm that `docker pull ghcr.io/xxx` works with latest version.
From the context of original https://github.com/containerd/containerd/issues/3291 issue, github package registry implemented the right spec with ghcr.io and old `docker.pkg.github.com` seems to be in-compatible docker 20.10

Is it best to throw out warning for older spec registry in 20.10 and break it later?

**Comment by tianon** [comment] 2020-11-19 03:48
> Is it best to throw out warning for older spec registry in 20.10 and break it later?

Well, that's where this gets dicey - that registry only incidentally worked on 19.03.  It isn't using an older spec, it's noncompliant with *either* relevant spec, as-is.  Even detecting it is going to amount to a special case in the Docker code for this one specific registry, which doesn't make sense IMO given this registry is failing because it doesn't implement the spec correctly (*and* this registry is supposed to be phased out in usage anyhow, from what I understand).

**Comment by HarryWeppner** [comment] 2020-11-20 15:28
I had reported in docker/for-mac#5079 as pulling from our internal, private registry broke after upgrading from Docker Engine `20.10.0 beta1` to Docker Engine `20.10.0-rc1`.

How can I verify that it is the same issue as reported here?

**Comment by tianon** [comment] 2020-11-20 16:17
The error message you're getting looks very different, so I don't think it is this *exact* issue (but could still be somewhat related).

If you could try pulling your image in `containerd` (easiest way is via `ctr`), that might help narrow it down or provide more detail, but it sounds like a new issue might be appropriate.

**Comment by HarryWeppner** [comment] 2020-11-24 05:48
@tianon - this is the failure mode we are observing with 20.10 RC1 (registry, repo, and tag redacted).

Full [`ctr images pull` command output](https://github.com/moby/moby/files/5587647/ctr-images-pull.log)

```
/ # ctr images pull <private-registry>/<repo>:<tag>
ctr images pull <private-registry>/<repo>:<tag>
<private-registry>/<repo>:<tag>: resolving      |--------------------------------------|
elapsed: 0.1 s                                total:   0.0 B (0.0 B/s)
...
<private-registry>/<repo>:<tag>: resolving      |--------------------------------------|
elapsed: 1.3 s                                total:   0.0 B (0.0 B/s)
<private-registry>/<repo>:<tag>:                                     resolved       |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:206ee1bc2e316698bc99ee8a1201221332e2571ccf463382d97c19ff8fd8de39: downloading    |--------------------------------------|    0.0 B/5.5 KiB
elapsed: 1.4 s                                                                    total:   0.0 B (0.0 B/s)
...
<private-registry>/<repo>:<tag>:                                     resolved       |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:206ee1bc2e316698bc99ee8a1201221332e2571ccf463382d97c19ff8fd8de39: downloading    |--------------------------------------|    0.0 B/5.5 KiB
elapsed: 11.9s                                                                    total:   0.0 B (0.0 B/s)
ctr: failed to copy: httpReaderSeeker: failed open: could not fetch content descriptor sha256:206ee1bc2e316698bc99ee8a1201221332e2571ccf463382d97c19ff8fd8de39 (application/vnd.docker.distribution.manifest.v2+json) from remote: not found
```

**Comment by tianon** [comment] 2020-11-24 15:50
Interesting, from that output it does seem similar (apparent 404 on the pull by digest).

Do you know which registry implementation that registry is using? (Specific could provider, SaaS, some open source registry, etc?)

**Comment by HarryWeppner** [comment] 2020-11-25 05:35
@tianon checking into that on our end. Is there anything that would resemble a changelog that would provide some additional insight into the client changes for RC1?

**Comment by nigurr** [comment] 2020-11-25 06:22
> @tianon checking into that on our end. Is there anything that would resemble a changelog that would provide some additional insight into the client changes for RC1?

Possibly easiest way to test is, do the image pull using docker 19.x stable version from another client machine.
If it doesn't work, it would be mostly server (private registry) issue. Otherwise, it would be changes in docker 20 rc1 cause the issue.

**Comment by HarryWeppner** [comment] 2020-11-25 07:37
> Possibly easiest way to test is, do the image pull using docker 19.x stable version from another client machine.
> 
> If it doesn't work, it would be mostly server (private registry) issue. Otherwise, it would be changes in docker 20 rc1 cause the issue. 

We've already done that bisect - it _is_ caused by the upgrade to RC1.

The question is whether it accidentally worked before or not. That's what we are trying to figure out now.

**Comment by thaJeztah** [comment] 2020-11-25 16:52
The change in RC1 related to this is https://github.com/moby/moby/pull/41607

> The question is whether it accidentally worked before or not. That's what we are trying to figure out now.

Yes, the docker.pkg.github.com registry is known to not be compliant with the distribution specification (https://github.com/opencontainers/distribution-spec), and only implements parts of the specification. Previously, it "mostly" worked, because it implemented _just_ enough of the specification to make `docker pull` work, but it failed for many other cases either with docker (https://github.com/moby/moby/issues/40403, https://github.com/moby/moby/issues/34153), containerd (https://github.com/containerd/containerd/issues/3291), and many other runtimes/projects (see the issues linked to/from https://github.com/containerd/containerd/issues/3291 - you may have to "unfold" some comments, as the GitHub UI is hiding them).

IIRC, the missing part is that docker.pkg.github.com does not support pull by digests, which previously was not hit by default on `docker pull`, but now is (since https://github.com/moby/moby/pull/41607), causing the pull to fail.

**Comment by HarryWeppner** [comment] 2020-11-25 18:08
@thaJeztah thanks - your summary was very much appreciated.

After an initial investigation, it appears that our registry, too, does not (currently) support a pull by digest.

**Comment by Alvise88** [comment] 2020-12-01 10:30
[Gitlab container dependency](https://docs.gitlab.com/ee/user/packages/dependency_proxy/) has the same problem with 20.10 RC1:

`
docker pull ${DOCKER_HUB_PROXY}/docker:19.03.13
`

Error response from daemon: manifest for <proxy_url>/docker:19.03.13 not found: manifest unknown: manifest unknown

**Comment by thaJeztah** [comment] 2020-12-01 11:50
@Alvise88 thanks for reporting that; do you know if that issue has been reported with GitLab as well?

**Comment by tianon** [comment] 2020-12-01 18:55
> [Gitlab dependency proxy](https://docs.gitlab.com/ee/user/packages/dependency_proxy/) has the same problem with 20.10 RC1:
> 
> `docker pull ${DOCKER_HUB_PROXY}/docker:19.03.13`
> 
> Error response from daemon: manifest for <proxy_url>/docker:19.03.13 not found: manifest unknown: manifest unknown

> @Alvise88 thanks for reporting that; do you know if that issue has been reported with GitLab as well?

@tmaczukin :pray: perhaps you know of the appropriate place to report this (or whether it's already tracked)?

(For some context, Docker 20.10 RC1 was updated to use a very similar separated resolver/fetcher process for pulling images as what's used in `containerd` and it appears that GitLab's Dependency Proxy doesn't support pull-by-digest?)

This should also affect containerd (since it also resolves images to digests so it can fetch-by-digest in the same way), so should be verifiable with `ctr images pull` / `ctr content fetch` as well.

**Comment by tmaczukin** [comment] 2020-12-02 15:21
@tianon I don't know if it's already tracked, but the issue tracker at https://gitlab.com/gitlab-org/gitlab/-/issues would be the place to report this and request a fix/improvement.

**Comment by tianon** [comment] 2020-12-03 19:51
https://gitlab.com/gitlab-org/gitlab/-/issues/290388 seemed like a really closely related discussion (since this would affect any pulling via `containerd` from https://docs.gitlab.com/ee/user/packages/dependency_proxy/), so I've left a comment there. :+1:

(Thank you!!)

**Closed** 2020-12-05 01:49 UTC
Labels: area/images, version/20.10

**Comment by nigurr** [comment] 2020-12-07 05:41
@AkihiroSuda @tianon @thaJeztah Sorry for tagging.
But with latest RC2, this is still not working. Can we re-open or should I create new issue?

```
docker pull docker.pkg.github.com/github/ixxxxxxxxxx/backend:latest
Error response from daemon: manifest for docker.pkg.github.com/github/xxxxxxxxxx/backend:latest not found: manifest unknown: Docker image reference insights-backend:sha256:9a760 not found under repo "github"
not found: manifest unknown: Docker image reference backend:sha256:9a760 not found under repo "github"
```

Switching to 19.x works

**Comment by AkihiroSuda** [comment] 2020-12-07 05:42
https://github.com/moby/moby/pull/41749 is not included in RC2

**Comment by nigurr** [comment] 2020-12-07 05:43
Sorry missed out. I did notice just now that its released 2 days earlier to fix. My apologies
