### ISSUE TITLE
WindowsRS5 CI is borked

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#38114] opened 2018-10-31 09:41 UTC
For example on https://github.com/moby/moby/pull/38103; https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/237/console

```
23:11:20 INFO: Base image for tests is microsoft/windowsservercore
23:11:20 INFO: Loading windowsservercore .tar from disk into the daemon under test. This may take some time...
23:12:08 
23:12:08 
23:12:08 ERROR: Failed 'ERROR: Failed to load c:\baseimages\windowsservercore.tar into daemon under test' at 10/30/2018 23:12:08
23:12:08 At C:\gopath\src\github.com\docker\docker\hack\ci\windows.ps1:705 char:21
23:12:08 + ...             Throw $("ERROR: Failed to load $readBaseFrom`:\baseimages ...
23:12:08 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

These scripts were last updated in https://github.com/moby/moby/pull/37715, but I'm not sure if that's related, or if it's something with the machines.

ping @ddebroy @jhowardmsft @johnstep PTAL

**Comment by AkihiroSuda** [comment] 2018-11-08 04:09
What's current status?

**Comment by thaJeztah** [comment] 2018-11-08 08:00
No change, but I'll try to ping some people to see if someone can look into this, or otherwise just remove the RS5 CI

**Comment by jhowardmsft** [comment] 2018-11-08 17:03
I've been OOF (surgery) and only just back. I'll try to look at it today or tomorrow. I think it's somehow relating to when the CI script moved into the repo.

**Comment by thaJeztah** [comment] 2018-11-08 17:06
Welcome back @jhowardmsft 🎉

**Comment by jhowardmsft** [comment] 2018-11-09 19:54
Making progress. I have a manual workaround, but I'd probably need to do that every few days which isn't sustainable. There's a leak somewhere in the platform. I'm trying to repro on a newer OS version and involve the relevant kernel folks.

**Comment by jhowardmsft** [comment] 2018-11-09 19:54
(Should add a couple of nodes are currently back and working as of this moment)

**Comment by thaJeztah** [comment] 2018-11-09 20:14
Thanks @jhowardmsft - would this be something we could do with a cronjob?

**Comment by jhowardmsft** [comment] 2018-11-09 20:18
What's cron 😆 This is Windows 😇. No, it's a kernel leak.

**Comment by jhowardmsft** [comment] 2018-11-12 17:02
Quick update - being tracked internally by VSO#19599026. I've got it down to a minimal repro. Unfortunately, once the system is in this state, a reboot appears to be the only solution as kernel resources are locked exclusively - it appears that it relates to a silo not completely exiting. There's at least one CI test which I know to hit this condition. As a temporary measure, I'll disable that test, and possibly one of three others (still narrowing down) which seem to also sometimes cause it. That will at least make the CI servers resilient and not have to be cleaned up every few days due to leaks. Investigation is now with the kernel team here to find the bug and hopefully we can get a fix in a future Windows update.

**Comment by olljanat** [comment] 2018-12-18 21:06
@jhowardmsft I found that all three RS5 CI servers was on state that all builds was failing.

So I did some investigations about this with my PR #38391
* Added commit https://github.com/moby/moby/commit/2c9e03daf1f1d842006de4f505fbefec6cdb580b to get more detailed errors out from it. They was:
```
18:07:46 docker : re-exec error: exit status 1: output: write \\?\D:\control\tmp\hcs008067931\Files\go.zip: There is not enough 
18:07:46 space on the disk.
18:07:46 At C:\gopath\src\github.com\docker\docker\hack\ci\windows.ps1:461 char:39
18:07:46 + ... sure-Command { docker build -t docker -f Dockerfile.windows . | Out-H ...
18:07:46 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:07:46     + CategoryInfo          : NotSpecified: (re-exec error: ...ce on the disk.:String) [], RemoteException
18:07:46     + FullyQualifiedErrorId : NativeCommandError
```
and
```
18:45:51 INFO: Base image for tests is microsoft/windowsservercore
18:45:52 INFO: Loading windowsservercore .tar from disk into the daemon under test. This may take some time...
18:46:41 docker-3fcffea1dc.exe : re-exec error: exit status 1: output: BackupWrite \\?\D:\CI\CI-3fcffea1dc\daemon\windowsfilter\
18:46:41 3610ea027b15254dbd127fad6cc562b9ed03a20979723c04edf904585e775393\Files\Windows\Boot\Fonts\jpn_boot.ttf: There is not 
18:46:41 enough space on the disk.
18:46:41 At C:\gopath\src\github.com\docker\docker\hack\ci\windows.ps1:710 char:17
18:46:41 + ...             & "$env:TEMP\binary\docker-$COMMITHASH" "-H=$($DASHH_CUT) ...
18:46:41 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:46:41     + CategoryInfo          : NotSpecified: (re-exec error: ...ce on the disk.:String) [], RemoteException
18:46:41     + FullyQualifiedErrorId : NativeCommandError
```
* I used to couple of versions of commit https://github.com/moby/moby/commit/ff5b4444deb3a2394ad1f328e2db42a00844f4b1 to get all three nodes rebooted.
* Then I reset #38391 back to state where it only contains needed commit and saw that build was now working on RS5. When looking for log more carefully I can see that first Nuke after reboot works just fine:
```
19:39:50 INFO: Commit hash is dd82172cc4
19:39:50 INFO: Nuke-Everything...
19:39:50 INFO: Container count on control daemon to delete is 0
19:39:51 INFO: Nuking d:\CI
19:55:51 INFO: Zapped successfully
19:55:51 INFO: Location for testing is d:\CI\CI-dd82172cc4
19:55:51 INFO: Validating GOLang consistency in Dockerfile.windows...
```
but after all tests have been run second Nuke fails (but it does no fail test):
```
20:40:10 INFO: Tidying pidfile d:\CI\CI-dd82172cc4\docker.pid
20:40:10 INFO: Nuking d:\CI
20:40:12 ERROR:  hcsshim::DestroyLayer - Win32 API call returned error r1=0x80070020 err=The process cannot access the file because it is being used by another process.id=CI flavour=0
20:40:12 
20:40:12 INFO: executeCI.ps1 exiting at Tue Dec 18 20:40:12 CUT 2018. Duration 01:00:22.9026065
20:40:12 
20:40:12 Set build name.
20:40:12 New build name is '#38391'
20:40:13 [PostBuildScript] - Executing post build scripts.
20:40:13 Notifying endpoint with url 'https://leeroy.dockerproject.org/notification/jenkins'
20:40:14 Finished: SUCCESS
```
* Finally create PR proposal #38392 which would reboot these RS5 servers after each CI build. It is ugly solution of course but IMO would be better than randomly failing CI builds.


Also just to add also here same what I said on https://github.com/moby/moby/pull/38376#issuecomment-448295761 that **rebuild/windowsRS5-process** label does not work.

**Comment by johnstep** [comment] 2018-12-23 07:20
This appears to be an issue related to the fontdrvhost package directory. After a full, successful run, I saw 20 instances of open file handles in the system process to the `Windows\System32\config\systemprofile\AppData\Local\Packages\microsoft.windows.fontdrvhost` directory in one of the test images, and the same count for each of its subdirectories, recursively (`AC`, `AC\INetCache`, `AC\INetCookies`, `AC\INetHistory`, and `AC\Temp`).

**Comment by thaJeztah** [comment] 2018-12-23 08:33
Thanks @johnstep

**Comment by thaJeztah** [comment] 2019-01-03 23:36
Awesome, thanks! (and thanks to the team!)

**Comment by jhowardmsft** [comment] 2019-01-04 00:06
OK, nodes 2 and 3 are redeployed and online. 4 is on it's way. 1 I'll have to do this evening.

**Comment by olljanat** [comment] 2019-01-04 05:32
@jhowardmsft I do not want to spoil the party here but I can see from [this build](https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/982/console) which I just started that OS build is now 17763.55 (was 17763.1 earlier) but it looks to be that removing data from CI folder still fails:
```
05:15:28 INFO: Nuking d:\CI
05:15:29 ERROR:  hcsshim::DestroyLayer - Win32 API call returned error r1=0x80070020 err=The process cannot access the file because it is being used by another process.id=CI flavour=0
```

**Comment by jhowardmsft** [comment] 2019-01-04 17:42
@olljanat That's actually still an older build. It's the .253 machines you want to be looking at. But no, in a full CI run, it's not fixed. Back to the kernel team....

**Comment by jhowardmsft** [comment] 2019-01-07 16:32
Further update - the storage folks have found a leak in the filter driver which could likely be the cause. I'll deploy a private fix on the servers later this week once I have a binary and have done some validation locally.

**Comment by jhowardmsft** [comment] 2019-01-07 20:40
With a private on a local run. I'll patch the servers this afternoon. Hence closing this.

![image](https://user-images.githubusercontent.com/10522484/50792324-636de500-1279-11e9-8e30-b664a8b37acc.png)

**Closed by jhowardmsft** 2019-01-07 20:40 UTC
Labels: area/testing, kind/bug, platform/windows

**Comment by thaJeztah** [comment] 2019-01-07 21:11
![zap zap zap](https://media.giphy.com/media/WmkqburJqXziM/giphy.gif)

**Comment by olljanat** [comment] 2019-01-11 12:01
@jhowardmsft good. Do you know KB number for hotfix already? Will it be released on February?

**Comment by jhowardmsft** [comment] 2019-01-11 15:02
It’s not available publically. I don’t think realistically it will be available until April or May at the earliest. That is a best guess only, not a commitment. Will update here when I know more, but bear in mind I have no control of servicing Windows and timelines.
