### ISSUE TITLE
Setting OOM score for ready process caused "write /proc/5578/oom_score_adj: invalid argument"

### ISSUE THREAD

**Issue by alfonsoperez** [moby/moby#25099] opened 2016-07-27 00:04 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 16
 Running: 7
 Paused: 0
 Stopped: 9
Images: 72
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 332
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: Z3AR:3OHB:47FY:H22B:IWGM:IFLR:T7SP:IRUW:SOSA:43U6:D77Z:B2HP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 55
 Goroutines: 82
 System Time: 2016-07-27T00:02:38.724549572Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: alfonsoperez
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker for mac

**Steps to reproduce the issue:**
1.  `docker-compose ..../docker-compose.yml up web`

**Describe the results you received:**

```
ERROR: for web  oci runtime error: process_linux.go:295: setting oom score for ready process caused "write /proc/5578/oom_score_adj: invalid argument"
```

**Describe the results you expected:**

Starting the container

**Additional information you deem important (e.g. issue happens only occasionally):**

Tried restarting docker / removing the containers several times

**Comment by justincormack** [comment] 2016-07-27 10:48
Sorry, we would need more information about your compose file to be able to replicate this.

**Comment by alfonsoperez** [comment] 2016-07-27 15:17
Hi @justincormack , here you go.

```
web:
  image: xxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxx/xxxx:xxxx
  command: bundle exec foreman start web -f /pocket_change/Procfile -p 3000
  env_file: env
  volumes:
    - ../..:/pocket_change
  volumes_from:
    - bundle
  ports:
    - "3000:3000"
  environment:
    DATABASE_URL: postgis://postgres@postgres/pocket_change_development
    REDSHIFT_DATABASE_URL: redshift://xxxxxx:xxxxxxxx@xxxxxxx.xxxxxxx.us-east-1.redshift.amazonaws.com:5439/dev
    OPENREDIS_URL: redis://redis:6379
    RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    RABBITMQ_MANAGEMENT_URL: http://rabbitmq:15672/api
  links:
    - postgres
    - redis
    - rabbitmq

approvals:
  image: xxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxx/xxxxxxx:development
  ports:
    - "7070:7070"
  environment:
    NODE_ENV: development

subscription:
  image: xxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxxxxx/xxxxxx
  ports:
    - "9090:9090"
  environment:
    NODE_ENV: development

nervecenter:
  image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxxxxx/xxxxxx:development
  ports:
    - "8090:8090"
  environment:
    NODE_ENV: development

authfilter:
  image: xxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxx/authfilter
  ports:
    - "3456:80"
  environment:
    AUTH_SERVICE_HOST: authservice
    AUTH_SERVICE_PORT: 8443
    APP_HOST: web
    APP_PORT: 3000
    APP_PROTOCOL: 'http'
  links:
    - authservice
    - web

authservice:
  image: xxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxxxx/auth-service
  environment:
    DATABASE_URL: postgres://postgres:@postgres/development
  ports:
    - "8080:8080"
    - "8443:8443"
  links:
    - postgres

postgres:
  image: mdillon/postgis:9.5
  ports:
    - "5432:5432"
  volumes_from:
    - postgresdata

rabbitmq:
  image: rabbitmq:3.4.4-management
  ports:
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:2.8.19
  ports:
    - "6379:6379"

bundle:
  image: busybox
  volumes:
    - /bundle

postgresdata:
  image: busybox
  volumes:
    - ../pgdata:/var/lib/postgresql/data
```

Thanks

**Comment by justincormack** [comment] 2016-07-28 13:51
Ok, odd you are not setting the `oom_score_adj` directly anywhere? Does this happen for you with all compose files? eg something simpler?

**Comment by justincormack** [comment] 2016-07-28 13:54
It is possible that this is an issue with Docker for Mac specifically actually. We are just about to do a release later today, and it is just possible that it will be fixed (hopefully). However it is a bit odd, as no one else has reported this, and it doesnt show in our tests, and nothing is unusual about your compose file, so I am a little unsure at this point...

**Comment by thaJeztah** [comment] 2016-07-28 14:14
@justincormack we've had a similar issue with the Swarm API always setting a value for some properties, although it doesn't look like its related here

**Comment by justincormack** [comment] 2016-07-28 14:32
@thaJeztah it is odd as this is a numerical field with a default `0` which would be valid, I think, rather than a string field I think (from memory), so it shouldn't matter if it is set.

**Comment by thaJeztah** [comment] 2016-07-28 14:53
@justincormack hm, I know the default for "not set" changed a few times; could it be `-1` for "not set" in the API?

**Comment by justincormack** [comment] 2016-07-28 15:03
-1 is valid too, it accepts negative values too in this case...

**Comment by justincormack** [comment] 2016-08-01 08:04
Also reported not on desktop editions here https://github.com/docker/docker/issues/25277

**Comment by justincormack** [comment] 2016-08-01 08:12
Ok, from the other issue here is a minimal Dockerfile that replicates this

```
FROM scratch

ENV $USER_HOME=/etc/myApp

RUN chmod +x /
```

**Comment by justincormack** [comment] 2016-08-01 08:26
It is quite odd, first there seems to be variable expansion in the `ENV` line, if you use `ENV $PATH=hello` it doesn't give the `oom` error.

Then
```
FROM scratch
ENV =/etc/myApp
RUN ["."]
```
Gives the error, so it looks related to a parsing issue for `ENV`.

minimal example is
```
FROM scratch
ENV =
RUN .
```

**Comment by justincormack** [comment] 2016-08-01 08:45
Ok, the process having the `oom_score` set has exited by this point, hence the error. My guess is that the environment being passed is being treated as a null pointer and this is causing the issue at a guess, so it is a parsing issue in `ENV` (well, multiple issues, as there should not be expansion going on either, as well as with handling `=` with nothing on the left.

**Comment by justincormack** [comment] 2016-08-01 09:01
Ok so the issue here is `ENV =` or `ENV =...` ie an empty left hand side anywhere in an `ENV` line causes this error.

**Comment by pdzwart-atlassian** [comment] 2016-08-26 01:16
Still hitting this with an unintentionally referenced variable name during declaration:

        ENV ${TGTBINARY} ${GOBIN}/${TGT}

This is with 1.12.1:

	…
        Step 12 : ENV ${TGTBINARY} ${GOBIN}/${TGT}
	 ---> Running in 15b85d6e7bc9
	 ---> b20a1dc6d883
	Removing intermediate container 15b85d6e7bc9
	Step 13 : ENV DEBBUILDDIR /tmp/debbuild/${TGT}
	 ---> Running in b1fe65976419
	 ---> f50ca7b7cf04
	Removing intermediate container b1fe65976419
	Step 14 : ENV DEBBUILDCONTROL foo/DEBIAN/control
	 ---> Running in a7d23bae50c1
	 ---> 95073051572a
	Removing intermediate container a7d23bae50c1
	Step 15 : RUN mkdir -pv ${DEBBUILDDIR}
	 ---> Running in 4bed89d8e88c
	oci runtime error: process_linux.go:295: setting oom score for ready process caused "write /proc/8016/oom_score_adj: invalid argument"
	make: *** [terraform-provider-vtm-builder] Error 1
	pdzwart@CLI-26204:~/Documents/Source/foo[11:12:09](0,2)$ docker version
	Client:
	 Version:      1.12.1
	 API version:  1.24
	 Go version:   go1.6.3
	 Git commit:   23cf638
	 Built:        Thu Aug 18 17:52:38 2016
	 OS/Arch:      darwin/amd64

	Server:
	 Version:      1.12.1
	 API version:  1.24
	 Go version:   go1.6.3
	 Git commit:   23cf638
	 Built:        Thu Aug 18 17:52:38 2016
	 OS/Arch:      linux/amd64
	pdzwart@CLI-26204:~/Documents/Source/foo[11:13:10](0,0)$

**Comment by thaJeztah** [comment] 2016-09-20 17:52
PR is probably https://github.com/docker/docker/issues/22578 to fix this

**Comment by mixman** [comment] 2016-10-02 16:56
This can also be triggered by passing `-e $ENV=` to docker.

**Comment by bfosberry** [comment] 2016-10-19 22:53
I came across the issue when I had added some badly decrypted data to the Env array via the API, containing non-utf characters:

Here is an example container environment with the issue:

```
               "DOCKER_TLS_VERIFY=1",
               "�1�x��\u003e�m\u001cR\u001b\u0002?�D\u0000",
               "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
               "LANG=C.UTF-8",
```

**Comment by yongtang** [comment] 2016-11-05 19:00
The issue 
```
Setting OOM score for ready process caused "write /proc/5578/oom_score_adj:
invalid argument"
```
Related to Dockerfile:
```
FROM scratch
ENV =
RUN .
```
should have been fixed by #25300 (not in 1.12.3 but likely to be in 1.13)


However, there are still some other issues.

If the environment variable name is empty, then `docker run` will throw out the same error:
```
ubuntu@ubuntu:~/docker$ docker run -e =A busybox true
docker: Error response from daemon: invalid header field value "oci runtime error: 
container_linux.go:247: starting container process caused \"process_linux.go:295:
setting oom score for ready process caused \\\"write /proc/83582/oom_score_adj:
invalid argument\\\"\"\n".
ubuntu@ubuntu:~/docker$ 
ubuntu@ubuntu:~/docker$ docker run -e = busybox true
docker: Error response from daemon: invalid header field value "oci runtime error: 
container_linux.go:247: starting container process caused \"process_linux.go:295:
setting oom score for ready process caused \\\"write /proc/83692/oom_score_adj:
invalid argument\\\"\"\n".
```

**Comment by yongtang** [comment] 2016-11-05 19:16
Created a PR #28098 to fix the issue related to `docker run -e = busybox`:

```
docker: Error response from daemon: invalid header field value "oci runtime error: 
container_linux.go:247: starting container process caused \"process_linux.go:295:
setting oom score for ready process caused \\\"write /proc/83692/oom_score_adj:
invalid argument\\\"\"\n".
```

**Comment by yongtang** [comment] 2016-11-09 14:15
@mixman The `-e =` should have been fixed in the master.

**Comment by yongtang** [comment] 2016-11-09 14:16
@bfosberry Can you give it a try for the current master and see if the issue is resolved? If the issue still exist, can you post the non-utf char in hex format? I am not able to see what the value is for:
```
"�1�x��\u003e�m\u001cR\u001b\u0002?�D\u0000",
```

**Comment by vikstrous** [comment] 2017-01-23 22:01
looks like this is fixed?

**Comment by jonathan-kosgei** [comment] 2017-09-14 06:44
Ran into this issue with Kubernetes setting an env var from a secret.
The fix was to base64 encode the secret value.

**Comment by thaJeztah** [comment] 2017-09-14 09:28
Looks like the original issue reported here is indeed fixed;

```bash
$ docker run -e = busybox true
invalid argument "=" for e: invalid environment variable: =
See 'docker run --help'.

$ docker run -e =A busybox true
invalid argument "=A" for e: invalid environment variable: =A
See 'docker run --help'.
```

If you still think there's an issue to resolve, open a new ticket with details and steps to reproduce 👍

**Closed by thaJeztah** 2017-09-14 09:28 UTC
Labels: area/runtime, kind/bug, priority/P3, version/1.12
