### ISSUE TITLE
x509: certificate is valid for *.downlynk.com

### ISSUE THREAD

**Issue by Meeeeow** [moby/moby#32960] opened 2017-05-02 10:18 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
`docker pull` command always failed, error message is : 

`Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.downlynk.com, not registry-1.docker.io`

**Steps to reproduce the issue:**
1. Run `docker pull finalduty/archlinux:weekly`
2. Docker not pull from registry-1.docker.io rather than registry server in daemon.json
2. Got a error message

**Describe the results you received:**
Command failed

**Describe the results you expected:**
Start download image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 7
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797GiB
Name: ci
ID: UGPR:M6BJ:357U:DPNV:VST4:EFAH:2X5Q:Y37P:AFGU:6VNY:BJKU:L76L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://docker.mirrors.ustc.edu.cn/
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
QingCloud

**Comment by kevin-wang-cy** [comment] 2017-05-05 09:18
I got the same issue of this:
{quote}
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.downlynk.com, not registry-1.docker.io
{quote}

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 24
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.661 GiB
Name: xxx-xx-xxx1
ID: 5MZG:FRRE:2YQQ:GJAM:RRPG:SYM3:LAHC:KFGT:FUTF:CNAJ:IYWO:SXQF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xxxxx
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

But it works on my another docker host, same version of docker.

**Comment by thaJeztah** [comment] 2017-06-07 23:35
Although I cannot place the `downlynk.com` domain, I highly suspect the network you're on is using a MITM proxy. If this is a corporate network, I suggest to contact the network admin to ask for more information.

If you're behind a proxy, this part of the documentation shows how to configure the daemon for using a proxy; https://docs.docker.com/engine/admin/systemd/#httphttps-proxy

Given that this is a configuration issue, or something in your environment, not a bug, I'm closing this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2017-06-07 23:35 UTC
Labels: area/distribution, version/17.04

**Comment by Meeeeow** [comment] 2017-06-09 03:52
It's not a corporate network, it's data center's network, no any proxy setup on that server

**Comment by thaJeztah** [comment] 2017-06-09 06:46
May I ask if this is in China? Is it possible this relates to the GFW?

**Comment by Meeeeow** [comment] 2017-06-09 06:58
Yes, i'm not sure, as i know, they have three way to block user request: TCP reset / DNS pollution / IP block, no one will cause such issue.

@kevin-wang-cy And you? Could you tell us your network environment info?

**Comment by liaoya** [comment] 2017-07-22 07:49
I find quite interesting point.

   [vagrant@localhost ~]$ ping docker.mirrors.ustc.edu.cn
   PING mirrors.ustc.edu.cn (202.141.160.110) 56(84) bytes of data.
   64 bytes from registry-1.docker.io (202.141.160.110): icmp_seq=1 ttl=53 time=205 ms
   64 bytes from registry-1.docker.io (202.141.160.110): icmp_seq=2 ttl=53 time=129 ms
   64 bytes from registry-1.docker.io (202.141.160.110): icmp_seq=3 ttl=53 time=51.2 ms

I find the link <https://lug.ustc.edu.cn/wiki/mirrors/help/docker?s[]=docker>, this link is Chinese. It seems that a famous Chinese university try to setup an reverse proxy for docker hub.

But I failed and my error is

   Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.mirrors.ustc.edu.cn, mirrors.ustc.edu.cn, not registry-1.docker.io
