### ISSUE TITLE
docker push image to registry v2:error parsing HTTP 405 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>405 Not Allowed</title

### ISSUE THREAD

**Issue by jkzhao** [moby/moby#34657] opened 2017-08-29 06:43 UTC
**Description**

When I created registry v2, and the frontend use nginx, I push image to the registry, then error is:
```
[root@node1 docker]# docker push registry2.wisedu.com/centos:v1
The push refers to a repository [registry2.wisedu.com/centos]
b362758f4793: Pushing [==================================================>]  192.5MB/192.5MB
error parsing HTTP 405 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>openresty/1.9.7.3</center>\r\n</body>\r\n</html>\r\n"
```

The nginx access.log is:
```
registry2.wisedu.com 172.16.7.151 [29/Aug/2017:14:34:39 +0800] 1503988479.444 "GET /v2/ HTTP/1.1" 401 200 "-" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.5.2-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \x5C(linux\x5C))" 0.000 -
registry2.wisedu.com 172.16.7.151 [29/Aug/2017:14:34:39 +0800] 1503988479.460 "HEAD /v2/centos/blobs/sha256:74f0853ba93b37c8152648905c48965c774d5a7d2de1967aef86ef0144561f62 HTTP/1.1" 404 0 "-" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.5.2-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \x5C(linux\x5C))" 0.003 0.003
registry2.wisedu.com 172.16.7.151 [29/Aug/2017:14:34:39 +0800] 1503988479.557 "POST /v2/centos/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.5.2-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \x5C(linux\x5C))" 0.088 0.088
```

**Steps to reproduce the issue:**
1. Run:
```
[root@node1 certs.d]# docker login registry2.wisedu.com
Username (jkzhao): 
Password: 
Login Succeeded
```

2. `[root@node1 certs.d]# docker tag centos registry2.wisedu.com/centos:v1`
3. `[root@node1 certs.d]# docker push registry2.wisedu.com/centos:v1`

**Describe the results you received:**

```
[root@node1 certs.d]# docker push registry2.wisedu.com/centos:v1
The push refers to a repository [registry2.wisedu.com/centos]
b362758f4793: Pushing [==================================================>]  192.5MB/192.5MB
error parsing HTTP 405 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>openresty/1.9.7.3</center>\r\n</body>\r\n</html>\r\n"
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
[root@node1 certs.d]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-70191505-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 370.2MB
 Data Space Total: 107.4GB
 Data Space Available: 26.64GB
 Metadata Space Used: 794.6kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.5.2-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: node1
ID: W6GY:FUO7:XG7S:JU6H:AP6N:NPWC:TFCV:N6FW:7PN3:OA5O:ADE4:T3RK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://6101v8g5.mirror.aliyuncs.com/
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
virtual machine

**Comment by ripcurld0** [comment] 2017-08-29 07:31
@jkzhao can you describe in details how you setup/configured/executed the registry and the nginx containers?

**Comment by jkzhao** [comment] 2017-08-29 07:39
@ripcurld0 
start registry:
```
[root@spark32 ~]# docker run -d -p 5000:5000 --name wisedu_registry registry:2
```

Nginx configuration:
```
upstream docker-registry {
        server 127.0.0.1:5000;
    }
    server {
        listen 443;
        server_name registry2.wisedu.com;

        access_log  logs/registry.access.log  main;

        ssl on;
        ssl_certificate /opt/ssl/spark32.crt;
        ssl_certificate_key /opt/ssl/spark32.key;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        chunked_transfer_encoding on;

        location / {
            auth_basic "Docker";
            auth_basic_user_file /usr/local/openresty/nginx/conf/docker-registry.htpasswd;
            proxy_pass http://docker-registry;
        }

        location /_ping {
            auth_basic off;
            proxy_pass http://docker-registry;
        }

        location /v1/_ping {
            auth_basic off;
            proxy_pass http://docker-registry;
        }
    }
```

**Comment by ripcurld0** [comment] 2017-08-29 07:43
@jkzhao do you run the nginx as a container too?

**Comment by jkzhao** [comment] 2017-08-29 07:45
No, Nginx is deployed in host.

**Comment by jkzhao** [comment] 2017-08-29 07:48
@ripcurld0 
Nginx access.log display：
```
"POST /v2/my-ubuntu/blobs/uploads/ HTTP/1.1" 202 0
```
Just server gave no response,
```
error parsing HTTP 405 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>405 Not Allowed</title>
```

**Comment by ripcurld0** [comment] 2017-08-29 07:49
Yes, I'm just trying to reproduce this to understand exactly what is going on.
In general, It was expected the response from the registry to be JSON but the body is HTML.

**Comment by thaJeztah** [comment] 2017-09-21 13:39
This looks like a duplicate of https://github.com/moby/moby/issues/15636 (specifically, this comment: https://github.com/moby/moby/issues/15636#issuecomment-132713350).

Your nginx server is not configured to forward the required headers, which causes this issue. See the [Important/Required HTTP-Headers](https://docs.docker.com/registry/deploying/#importantrequired-http-headers) section in the documentation, the [gotchas](https://docs.docker.com/registry/recipes/nginx/#gotchas) section in the NGINX recipe, and the [example configuration file](https://docs.docker.com/registry/recipes/nginx/#setting-things-up) on the same page.

I'm closing this issue, because I think this is a configuration issue, and not a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2017-09-21 13:39 UTC
Labels: area/distribution, version/17.06
