### ISSUE TITLE
How to optimize the microsoft/windowsservercore

### ISSUE THREAD

**Issue by sharathj007** [moby/moby#36593] opened 2018-03-14 14:53 UTC
am using the below commands to create a docker base image to run my application which needs visual studio redistribute package and java JDK in windows server 2016. My concern here is by using the microsoft/windowsservercore the base image size itself 10.4 GB, by including JDK and my project dependencies in dockerfile which create an image size of 11.8 GB.
DO ANY ONE CAN HELP ME TO REDUCE THE SIZE OF THE BASE IMAGE OR HOW CAN I OPTIMIZE THE SIZE HERE WILL BE VERY MUCH HELPFUL.

NOTE: I have tried creating an image using microsoft/nanoserver but which has the minimal features and didn't allow to install the visual studio redistributable package as part the image container which is very much required to run my application.
########################################################
FROM microsoft/windowsservercore

COPY THE INSTALLATION FILES INTO THE CONTAINER
ADD ./source c:/source

INSTALLING VC++ REDISTRIBUTABLE PACKAGE
untitled

RUN C:\source\vc_redist.x64.exe /quiet /install

RUN powershell.exe -command \

INSTALLING JAVA JDK
./source/jdk.cmd; \

SETTING UP ENVIRONMENT PATH VARIABLES FOR JDK FOLDER
./source/Environmentvariable.ps1; 
##########################################################

**Comment by thaJeztah** [comment] 2018-03-14 14:57
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-03-14 14:57 UTC
Labels: area/builder, platform/windows
