### ISSUE TITLE
erro ao criar container docker

### ISSUE THREAD

**Issue by ThiagoSantos1986** [moby/moby#46776] opened 2023-11-05 04:03 UTC
### Description

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: cgroup namespaces aren't enabled in the kernel: unknown.

### Reproduce

docker run hello-world

### docker version

```bash
version 24.0.7
```

### docker info

```bash
..
```

### Additional Info

instalei o docker atraves de um servidor OMV

**Comment by thaJeztah** [comment] 2023-11-06 10:37
Please provide more information as requested in the [issue-template](https://github.com/moby/moby/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) that was shown when you opened this issue.

- provide the full output of `docker version`
- provide the full output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by ThiagoSantos1986** [comment] 2023-11-09 04:52
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-eb33fdc5-6127-414d-944d-d02415aa708c/docker/port/port.yml' --env-file '/srv/dev-disk-by-uuid-eb33fdc5-6127-414d-944d-d02415aa708c/docker/port/port.env' --env-file '/srv/dev-disk-by-uuid-eb33fdc5-6127-414d-944d-d02415aa708c/docker/global.env' up -d  portainer 2>&1':  Container portainer  Starting
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: cgroup namespaces aren't enabled in the kernel: unknown

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-eb33fdc5-6127-414d-944d-d02415aa708c/docker/port/port.yml' --env-file '/srv/dev-disk-by-uuid-eb33fdc5-6127-414d-944d-d02415aa708c/docker/port/port.env' --env-file '/srv/dev-disk-by-uuid-eb33fdc5-6127-414d-944d-d02415aa708c/docker/global.env' up -d  portainer 2>&1':  Container portainer  Starting
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: cgroup namespaces aren't enabled in the kernel: unknown in /usr/share/openmediavault/engined/rpc/compose.inc:921
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(620): OMVRpcServiceCompose->{closure}('/tmp/bgstatusGz...', '/tmp/bgoutputhz...')
#1 /usr/share/openmediavault/engined/rpc/compose.inc(924): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#2 [internal function]: OMVRpcServiceCompose->doServiceCommand(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('doServiceComman...', Array, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Compose', 'doServiceComman...', Array, Array, 1)
#6 {main}

**Comment by Sanjib8830** [comment] 2023-11-09 14:08
Issue may be due to Control group (cgroups) which may not enabled in your Linux Kernel.
1. Check the Linux kernel version using below command
uname -r
Make sure, your running kernel version should support cgroup namespaces.

2. Update the kernel Parameters:
check the bootloader configuration file and update with the follwing namespace as 1.
sudo nano /etc/default/grub
GRUB_CMDLINE_LINUX="cgroup_namespace=1"
sudo update-grub

3. Reboot your system.
sudo reboot

**Comment by ThiagoSantos1986** [comment] 2023-11-09 15:51
root@rk322x-box:~# docker run hello-world
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: cgroup namespaces aren't enabled in the kernel: unknown.
ERRO[0002] error waiting for container:

**Comment by carlonchosando** [comment] 2024-03-04 04:39
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install 'openmediavault-diskstats' 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  openmediavault-diskstats
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.4 kB of archives.
After this operation, 106 kB of additional disk space will be used.
Err:1 http://packages.openmediavault.org/public shaitan/main amd64 openmediavault-diskstats all 6.0.5-1
  Could not resolve 'packages.openmediavault.org'
E: Failed to fetch http://packages.openmediavault.org/public/pool/main/o/openmediavault-diskstats/openmediavault-diskstats_6.0.5-1_all.deb  Could not resolve 'packages.openmediavault.org'
E: Internal Error, ordering was unable to handle the media swap

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install 'openmediavault-diskstats' 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  openmediavault-diskstats
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.4 kB of archives.
After this operation, 106 kB of additional disk space will be used.
Err:1 http://packages.openmediavault.org/public shaitan/main amd64 openmediavault-diskstats all 6.0.5-1
  Could not resolve 'packages.openmediavault.org'
E: Failed to fetch http://packages.openmediavault.org/public/pool/main/o/openmediavault-diskstats/openmediavault-diskstats_6.0.5-1_all.deb  Could not resolve 'packages.openmediavault.org'
E: Internal Error, ordering was unable to handle the media swap in /usr/share/openmediavault/engined/rpc/pluginmgmt.inc:250
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(620): Engined\Rpc\PluginMgmt->Engined\Rpc\{closure}('/tmp/bgstatusGH...', '/tmp/bgoutputJa...')
#1 /usr/share/openmediavault/engined/rpc/pluginmgmt.inc(253): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#2 [internal function]: Engined\Rpc\PluginMgmt->install(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('install', Array, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Plugin', 'install', Array, Array, 1)
#6 {main}

**Comment by thaJeztah** [comment] 2024-03-04 07:43
Closing this ticket as there's nothing actionable here, and it's becoming a "show me a random command that failed" thread.

**Closed by thaJeztah** 2024-03-04 07:43 UTC
Labels: status/0-triage, status/more-info-needed, kind/bug, version/24.0
