### ISSUE TITLE
Docker Search not working for private repos

### ISSUE THREAD

**Issue by alexmwu** [moby/moby#14660] opened 2015-07-15 18:46 UTC
Description of problem:
This causes docker-compose errors, but I believe that this is a docker issue.
When doing a `docker search <organization-name>` (after an appropriate `docker login`), only public repos are shown. This also means that `docker-compose up`s will fail (not sure if relevant). However, manually docker pulling with organization-name/repo-name works.

`docker version`:

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

`docker info`:

```
Containers: 3
Images: 97
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: docker-vagrant
ID: <not sure if should be displayed>
Username: alexmwu
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`uname -a`:
`Linux docker-vagrant 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Virtualbox through Vagrant

How reproducible:
fails every time

Steps to Reproduce:
1. `docker login`
2. `docker search <organization-name>` - This will fail to find private repos
3. `docker-compose up` will fail since it cannot find private repos.
4. `docker pull <organization-name/<private-repo-name>` (works)

Actual Results:

```
$ docker-compose up
Creating repo_name_1...
Pulling image org-name/repo-name:latest...
Pulling repository org-name/repo-name
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 199, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Error: image org-name/repo-name:latest not found
```

Expected Results:
A `docker search` and `docker-compose` success (lists private repos and starts containers, respectively)

Additional info:
I am not sure if this is a bug or a new feature. Either way, any help would be appreciated.

**Comment by tiborvass** [comment] 2015-07-16 15:33
So the docker part should be solved by #14521 (which was merged), but I just tested master and I still couldn't search private repos from the hub, so I wonder if there is anything the hub team needs to do? /cc @kencochrane @stevvooe

**Comment by dmp42** [comment] 2015-07-16 19:12
The hub does not provide private repos search functionality as far as I know (and neither do the open-source registry).

AFAIK, this is two fold:

 * fix compose, since it's assuming non-existent functionality, and this is the root of the problem here
 * longer term investigate with the Hub team how to do that

**Comment by stevvooe** [comment] 2015-07-16 19:43
This use case needs to be added in docker/distribution#206. The "new" search system should support this kind of thing.

**Comment by thaJeztah** [comment] 2015-08-15 21:43
ping @aanand is there something on the docker-compose side to be done?

**Comment by aanand** [comment] 2015-08-17 11:04
I'm willing to be convinced otherwise, but it's hard to believe both issues have the same source. `docker-compose up` is doing the same thing behind the scenes as `docker pull` - a POST to `/images/create`. Compose never touches the search endpoint.

@alexmwu We've fixed a few bugs with registry authentication recently. If you're using Compose 1.3.3 or later, please post in https://github.com/docker/compose/issues/75 with your Compose and Docker versions.

**Comment by dmp42** [comment] 2015-08-17 16:44
Thanks for the clarification @aanand
Then I assume the OP has an issue with private images?

**Comment by aanand** [comment] 2015-08-18 11:08
@dmp42 My suspicion is that the problem is with failing registry authentication, which (with private Hub images) manifests as a 404.

**Comment by dmp42** [comment] 2015-08-18 16:18
@alexmwu do you have an update on this?

**Comment by alexmwu** [comment] 2015-08-19 14:42
Yeah, it's an issue with private images. A `docker pull` of the docker-compose images then a `docker-compose up` works.

**Comment by alexmwu** [comment] 2015-08-19 14:51
@aanand Just updated compose to 1.4.0. This seems to have been an issue on the compose side, then. Thanks for the help everyone.

**Comment by javapapo** [comment] 2016-04-14 10:07
+1 (especially searching the private images, since pull works why not search)

**Comment by Hossrod** [comment] 2017-06-19 18:02
# **+1**
Really need this.

**Comment by zacaro** [comment] 2017-10-26 10:02
Yup, the community really need this feature.

**Comment by thaJeztah** [comment] 2023-09-16 20:47
> The hub does not provide private repos search functionality as far as I know (and neither do the open-source registry).

I think that's still the case; closing this ticket as there's not much that can be addressed in this repository

**Closed by thaJeztah** 2023-09-16 20:47 UTC
Labels: area/distribution, version/1.7
