### ISSUE TITLE
Docker/Moby has stopped git tagging source code at release time

### ISSUE THREAD

**Issue by sjpotter** [moby/moby#37271] opened 2018-06-12 22:37 UTC
Its getting difficult to build golang software that import's docker as one can't easily match releases as Docker has seemingly stopped tagging releases in git.

Can this be remedied either going back and forward in time or at least just forward?

**Comment by thaJeztah** [comment] 2018-06-12 23:54
The Moby repository is an upstream for Docker; Docker CE bundles the engine (moby), Docker CLI, containerd, and runc, and is released from the Docker CE repository; in that repository you'll find tags for each Docker release; https://github.com/docker/docker-ce/releases/

**Comment by sjpotter** [comment] 2018-06-13 00:20
How is one supposed to use this with golang?  I.e. dep/vendor it into ones code.  Is their a recommended way to it?  It seems impossible just based on released as is.

**Comment by thaJeztah** [comment] 2018-06-13 00:37
Correct, that repository is designed for releasing, not as a source for vendoring; you can vendor from this repository, or use the workaround mentioned in https://github.com/moby/moby/issues/33989#issuecomment-314909233

Changes are being made in the release process (no ETA, but should be soon), and an intermediate repository is used where Docker releases of the engine are tagged before being included in the docker-ce repository; release branches will also be created in that repository for situations where patches are backported. The repository has been created, but isn't in active use yet; https://github.com/docker/engine

**Comment by thaJeztah** [comment] 2018-06-13 00:38
Given that this is a duplicate of https://github.com/moby/moby/issues/33989, I'll close this issue to prevent the discussion from diverging, but feel free to participate in that discussion

**Closed by thaJeztah** 2018-06-13 00:38 UTC
