### ISSUE TITLE
github.com/Sirupsen/logrus has moved

### ISSUE THREAD

**Issue by mcandre** [moby/moby#33993] opened 2017-07-06 20:28 UTC
References to github.com/Sirupsen/logrus should be replaced with github.com/sirupsen/logrus. Projects that depend on docker / moby are currently breaking due to the case discrepancy.

**Comment by thaJeztah** [comment] 2017-07-08 09:58
looks like this is a duplicate of https://github.com/moby/moby/issues/33641. I'll close this issue to prevent the discussion from diverging

**Closed by thaJeztah** 2017-07-08 09:58 UTC
