### ISSUE TITLE
Shared memory of multiple dockers

### ISSUE THREAD

**Issue by Ruilkyu** [moby/moby#40721] opened 2020-03-19 10:59 UTC
Sir, our program runs in multiple dockers, but to load the same data into memory, is there any way for these docker containers to share memory?

**Comment by thaJeztah** [comment] 2020-03-19 11:38
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)
- StackOverflow

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-03-19 11:38 UTC
Labels: kind/question
