### ISSUE TITLE
Remove a being commit container should not be permitted.

### ISSUE THREAD

**Issue by charlihappy2016** [moby/moby#29654] opened 2016-12-22 08:31 UTC
Description
Version: docker-1.11.2

Steps to reproduce the issue:
1. Commit a stop container
2. At the same time remove this container

The expected result should be:
When container is in commit operation, the delete should not be allowed.

**Comment by gianarb** [comment] 2016-12-22 08:46
@charlihappy2016 the image created when the commit is completed is it working? Or the commit fails?
Thanks

**Comment by coolljt0725** [comment] 2016-12-22 08:54
@gianarb  I tried (with devicemapper graphdriver), the commit is completed, but removing failed with error.

```
$ docker commit 943a5d04c85f
sha256:662917bef212abbcde83f00131052dbf3991c1f282126887a0c760287dbd1b79

```

```
$ docker rm 943a5d04c85f
Error response from daemon: Driver devicemapper failed to remove root filesystem 943a5d04c85fb77031bdec727c8341062f6f0034ea204f2a19eafd52ec292c5b: Device is Busy

```

**Comment by thaJeztah** [comment] 2016-12-22 10:09
As requested in your other issue; please provide the information that was asked for in the issue report template that was shown when opening your issue; https://github.com/docker/docker/issues/29653#issuecomment-268765358, as it may help to identify possible causes, and to reproduce what you're seeing.

**Comment by charlihappy2016** [comment] 2016-12-23 09:30
@gianarb The image works well. But the container removes failed.

**Comment by YummyPeng** [comment] 2016-12-23 09:52
I also tried (with devicemapper graphdriver and docker-1.11.2), `docker commit` is always completed without any error message, and the image created can work well (maybe there are some files lost but I haven't found) .

But `docker rm` always returns an error like @coolljt0725 showed above. If I add `-f` to `docker rm`, then the container can be deleted. However, without `-f`, the status of the container being deleted will become `DEAD`, but I could remove it with `docker rm` again successfully.

So I don't think there is any problem, all behaviors seem intended.

**Comment by charlihappy2016** [comment] 2016-12-23 10:52
	Docker version and info
# Docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

# Docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.861 GiB
Name: ubuntu
ID: XC5Y:RVTS:DCNV:MHBG:47SE:QPHU:GMJS:AYIQ:6526:IUNQ:YUDW:RNOT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
 127.0.0.0/8

	Execute commands:
1.	Commit testimage by container 94434112ab85:
docker commit 94434112ab85 tsetimage
2. During that process delete the container : 
docker rm 94434112ab85
3. the remove result is fail with the log;
[root@localhost ~]# docker rm 94434112ab85
Error response from daemon: Driver devicemapper failed to remove root filesystem 94434112ab85d530e4e1607eda7de43fcf6d2bf6a8d3897df51f416697d7f450: Device is Busy 
4.the commit result is:
[root@localhost ~]# docker commit 94434112ab85 tsetimage 
sha256:847c20f6e50230249fb423129fd0cf921640cb479a89ba76a21d8aec40d14c9e

**Comment by thaJeztah** [comment] 2016-12-23 11:03
Ok, so I think I start to understand, but to be sure; the container you are committing; was it _running_ when you committed it, or _stopped_ ?

`docker rm` should fail if the container is either _running_ (or "paused", which is what happens during commit), but will "proceed" if the container is stopped. I don't think we keep track of a "commit" being in progress, so that would explain why it tries to remove the container (but fails, because the filesystem is in use by the commit action).

@mlaventure @coolljt0725 any thoughts on this? is there a way for the daemon to track if a container is being "committed"?

**Comment by coolljt0725** [comment] 2016-12-24 01:42
@thaJeztah  I don't think there is  way to track if a container is being committed. Should we add a new field to container metadata to track this? or can we use `Lock` to lock container both on container removing and committing?

**Comment by thaJeztah** [comment] 2016-12-24 15:55
@coolljt0725 adding more locking sounds dangerous (@cpuguy83?), possibly a new state could be an option.

**Comment by thaJeztah** [comment] 2016-12-24 15:56
I haven't checked yet if `docker image prune` handles this different btw

**Comment by mlaventure** [comment] 2016-12-24 22:32
I'd say a new state is better too. `prune` would have the exact same issue as it just call the same rm routine

**Comment by cpuguy83** [comment] 2016-12-24 23:01
I wouldn't lock the container.
I'd also like to no add a new state.
Maybe instead block at the fs layer.

**Comment by cpuguy83** [comment] 2016-12-24 23:57
And by "fs layer", I mean as in the layer store. Not the literal filesystem :)

**Closed** 2017-09-22 07:41 UTC
Labels: area/daemon, area/images, kind/enhancement
