### ISSUE TITLE
docker: Error response from daemon: failed to start service utility VM (createreadwrite): hcsshim::CreateComputeSystem adfe45ea5c63ae7988860fe96561ff2a1406cf07c28959a224e725952c013a3b_svm: The request is not supported.

### ISSUE THREAD

**Issue by INaCloud** [moby/moby#40902] opened 2020-05-04 22:50 UTC
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2020-05-07 10:04
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'm closing this ticket because there's not enough information to act on, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-07 10:04 UTC
Labels: platform/windows, status/more-info-needed
