### ISSUE TITLE
[ rootless, Fedora 33 ]: `failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /dev/initctl: no such file or directory` when pulling layer: `e69ec1c7b788`

### ISSUE THREAD

**Issue by cerulis64** [moby/moby#41821] opened 2020-12-18 18:27 UTC
**Description**
I am running Fedora 33, with the *Docker Daemon running as a non-privileged user* (rootless) and I am attempting to use the `openjdk` and the `maven` image to develop Java applications. However, on pulling the openjdk image with `docker pull openjdk` and `docker pull maven`, Docker downloads and extracts all the layers except `e69ec1c7b788` (`maven` and `openjdk` both contain this particular layer), where it instead hangs at `42.05MB/42.05MB` (extracting) for a few seconds, before producing an error (`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /dev/initctl: no such file or directory`) and exiting (i am assuming docker is using the system call called `lchown`, because `/usr/bin/lchown` does not exist). However, when I instead *ran the daemon as root*, and ran `sudo docker pull openjdk`, the layer that previously refused to pull (`e69ec1c7b788`) pulled successfully and I was able to run the images. I have not hit a similar issue with any layer other than `e69ec1c7b788`, which makes me wonder if something in that particular layer hits a bug in rootless docker daemon, causing the pull to fail. I searched `e69ec1c7b788` on `https://github.com/moby/moby` and did not find any issues relating to this layer.

**Steps to reproduce the issue:**
1. Install Fedora 33
2. Remove old versions of docker and remove `podman`:
```
sudo dnf remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine
```
3. `sudo dnf -y install dnf-plugins-core`
4. Add the docker-ce repo:
```
sudo dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
```
5. Install the latest version of docker: `sudo dnf install docker-ce docker-ce-cli containerd.io`
6. workaround for rootless on fedora (#41230): `sudo dnf install -y policycoreutils-python-utils && sudo semanage permissive -a iptables_t`
7. Install rootless docker: `dockerd-rootless-setuptool.sh install` (to enable the unit, run `sudo systemctl --user enable docker`)
8. Run the command: `docker pull openjdk`. You should see the error here.

**Describe the results you received:**
```
~ % docker pull openjdk; echo "$?"
Using default tag: latest
latest: Pulling from library/openjdk
e69ec1c7b788: Extracting  42.05MB/42.05MB
2259f1956e49: Download complete 
86b5c7ae0cae: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /dev/initctl: no such file or directory
1
```

**Describe the results you expected:**
```
~ % docker pull openjdk; echo "$?"
Using default tag: latest
latest: Pulling from library/openjdk
e69ec1c7b788: Pull complete 
2259f1956e49: Pull complete 
86b5c7ae0cae: Pull complete 
Digest: sha256:3ee42b89555f1563024c10132dda0693be1f14145f46de5d0e6151628e82b5da
Status: Downloaded newer image for openjdk:latest
docker.io/library/openjdk:latest
0
```

**Additional information you deem important (e.g. issue happens only occasionally):**
- `docker pull openjdk` gets stuck on `42.05MB/42.05MB` for a few seconds before throwing an error and exiting
- as far as I know, this only happens with a specific layer: `e69ec1c7b788`, which is in the `openjdk` image from `docker.io/library/openjdk:latest`
- I tested: `openjdk:alpine`, `openjdk:buster`, `gradle`, `alpine`, `archlinux`, `debian`, `fedora`, `clearlinux`, `mariadb`, `nginx`, `httpd`, `node`, `ubuntu`, `mysql`, `python`, `busybox`, `redis`, `postgres`, `docker`, `nextcloud`, `couchbase`, `drupal`, `groovy`, `swift`, `elixir`, `clojure`, and none of them contained layer `e69ec1c7b788` or produced the error. could there be something about that particular layer that makes it "special" and hit a bug in rootless docker?
- pulling the `maven` image failed at layer `e69ec1c7b788` (this is the exact same layer as the one that errored in the `openjdk` image). `maven` and `openjdk` both have layer `e69ec1c7b788` causing both to fail.
- I am running rootless docker daemon
- the error does not appear if i run the daemon as root, and `e69ec1c7b788` layer pulls correctly

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:35:49 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:33:13 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.1
 Storage Driver: btrfs
  Build Version: Btrfs v5.9 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.9.13-200.fc33.x86_64
 Operating System: Fedora 33 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.22GiB
 Name: whirlwind
 ID: N4MA:7CNW:3ST7:BNUX:GHJT:SF7G:UVTM:CL3W:3DNJ:3GOO:5D5T:BHJ3
 Docker Root Dir: /home/cerulis/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No cpuset support
WARNING: Support for cgroup v2 is experimental
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical installation on a laptop running Fedora 33.

**Comment by cerulis64** [comment] 2020-12-18 22:29
At first glance, this may seem similar to [pull errors stated in the Docker documentation](https://docs.docker.com/engine/security/rootless/#docker-pull-errors):
- Documentation: `docker: failed to register layer: Error processing tar file(exit status 1): lchown <FILE>: invalid argument`

**Comment by AkihiroSuda** [comment] 2020-12-19 04:40
Closing as a duplicate of #41803. Thanks for reporting anyway.

**Closed by AkihiroSuda** 2020-12-19 04:40 UTC

**Comment by cerulis64** [comment] 2020-12-21 00:58
oops

I reported it because it seems like what they said was something about `Error processing tar file` while mine was `ApplyLayer exit status 1 stdout`.

After further testing, it seems like that was due to them using overlay2 while I was using btrfs.
