### ISSUE TITLE
Help: The Volume is Read-Only When use `--cap-add=SYS_ADMIN`

### ISSUE THREAD

**Issue by oclarms** [moby/moby#36409] opened 2018-02-26 11:41 UTC
**Description**
The Volume is Read-Only When use `--cap-add=SYS_ADMIN`

**Steps to reproduce the issue:**
1. docker pull centos/systemd
2. docker run -d --cap-add="SYS_ADMIN" -v /Users:/home/macOS --name=test centos/systemd
3. docker exec -it test /bin/bash

**Describe the results you received:**
```
cd /home/macOS; touch a
touch: cannot touch 'a': Read-only file system
```

**Describe the results you expected:**
/home/macOS can be written.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
docker inspect test
```
The '/home/macOS' is RW.
```
        ...
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users",
                "Destination": "/home/macOS",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "c5a942e2e6af149e9ef459c98b4bcd87568d81ce6e6d97bc656098d71d5afb1a",
                "Source": "/var/lib/docker/volumes/c5a942e2e6af149e9ef459c98b4bcd87568d81ce6e6d97bc656098d71d5afb1a/_data",
                "Destination": "/sys/fs/cgroup",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ]
        ...
```
**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: FOUD:BMMH:3MQ6:FTBW:ZCPG:R7ZU:MDKY:447M:SMVK:NUP6:RNRK:NPME
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 49
 System Time: 2018-02-26T11:33:23.152687273Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
macOS High Sierra  version 10.13.3

Somebody have any idea? Thanks

**Comment by thaJeztah** [comment] 2018-02-26 16:29
The `/Users` directory on macOS is only writable by `root`;

```
$ ls -la /Users
total 0
drwxr-xr-x    7 root        admin    238 Dec 21  2016 .
```

If you try doing the same using `/Users/<your-username>` or any other directory inside `Users` that you have write permissions on, this should likely work.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-02-26 16:29 UTC
Labels: area/distribution, platform/desktop

**Comment by oclarms** [comment] 2018-02-27 02:05
@thaJeztah , i using other directory,  it's working.  thank you.

**Comment by thaJeztah** [comment] 2018-02-27 11:56
You're welcome!
