### ISSUE TITLE
Docker : starting container failed: Address already in use

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#34581] opened 2017-08-21 08:33 UTC
Hello,

With docker swarm i try to create a container and i have the error 'Address already in use' : 

```
$ docker service scale service_name=0
$ docker service scale service_name=1
$ docker service ps service_name
=>  "starting container failed: Address already in use"
```

I use an overlay network 
For solving this problem i scale to 2 and after one is up i downscale to 1 : 
```
$ docker service scale service_name=2
$ docker service ls
=> service_name 1/2
$ docker service scale service_name=1
$ docker service ls
=> service_name 1/2
```

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
```

```
$ docker info
docker info
Containers: 36
 Running: 21
 Paused: 0
 Stopped: 15
Images: 16
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 214
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: qyz7ndi2jamggj6mz8rufd8ue
 Is Manager: true
 ClusterID: x9hlh1e7wbq2dfluwkb7iqgmy
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.99.60.204
 Manager Addresses:
  10.99.60.204:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: name
ID: FMUN:Q7ED:UUGO:J5ZE:3GFE:IPFB:WHB6:NCGW:WATZ:UGKR:DBOI:L6II
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by akalipetis** [comment] 2017-08-22 16:35
I think this is a duplicate of #34163

**Comment by cpuguy83** [comment] 2017-08-25 16:45
Yep, looks like a dup. Thanks!

**Closed by cpuguy83** 2017-08-25 16:45 UTC
Labels: area/swarm, version/17.06

**Comment by mbenedettini** [comment] 2017-09-12 12:57
@sylvainmouquet thanks for the work around, scaling up to 2 and then downscaling to 1 saved me.
