### ISSUE TITLE
Docker 19.03 doesn't support OCI image

### ISSUE THREAD

**Issue by msyihchen** [moby/moby#39727] opened 2019-08-12 18:13 UTC
**Description**

Docker 17.09 and 18.06 are able to pull down OCI image, Docker 19.03 is not able to.
When docker client sends /v2/\<repo\>/manifests/\<tag\> request, 
* In docker 17.09, it doesn't contain "application/vnd.oci.image.manifest.v1+json" in the request accept header, so it receives a docker v2 format manifest, which is supported natively by docker.
* In docker 18.06, it contains "application/vnd.oci.image.manifest.v1+json" in the request accept header, it receives an OCI format manifest, it looks like docker is able to handle it correctly. Docker client converts it into docker v2 format.
* In docker 19.03, it contains "application/vnd.oci.image.manifest.v1+json" in the request accept header, it receives an OCI format manifest, docker client is not able to handle it. So it gives this error message: Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''

**Steps to reproduce the issue:**
1. Create a container registry in Azure, use podman build an OCI image and use podman to push it. In Azure portal, 
2. Docker client 17.09 and 18.06 are able to pull it down. Docker client 19.03 is not able to.

**Describe the results you received:**
Docker client 19.03 gives the following error:
Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''

**Describe the results you expected:**
Docker pull should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Output of `docker info`:**

Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.18.0-1024-azure
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: testpodmanyihchen
 ID: X3OI:UE7F:NMDF:WHSI:PRN2:UNPZ:Z24D:5CHF:5YMJ:2U2L:OSEF:U726
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: yc993
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 amd64

**Comment by bitfactory-henno-schooljan** [comment] 2019-09-10 11:55
It looks like this regression has not yet been fixed in 19.03.2.

**Comment by mvala** [comment] 2019-09-24 09:41
Same problem here. i had to downgrade docker to 18.09.9

**Comment by georgepapas-afterpay** [comment] 2019-10-10 00:29
Hello,

Any movement/updates on this issue?

**Comment by georgepapas** [comment] 2019-10-10 00:31
Hello

Any movement on this issue?

Cheers

**Comment by cpuguy83** [comment] 2019-10-10 00:57
Looking into this.

**Comment by cpuguy83** [comment] 2019-10-10 01:04
If you happen to have a public image with an OCI manifest I can test with that'd be immediately helpful.

**Comment by cpuguy83** [comment] 2019-10-10 01:21
Fairly certain it's related to this change: https://github.com/docker/distribution/commit/1d47ef7b801369dc2ca257732ea91d39089ecebc

Which breaks some code we have in moby which uses `DeserializedManifest` type to unmarshal an oci manifest.

**Comment by georgepapas** [comment] 2019-10-10 01:40
> If you happen to have a public image with an OCI manifest I can test with that'd be immediately helpful.

try `georgepapas/oci-test`

**Comment by cpuguy83** [comment] 2019-10-10 16:58
@georgepapas That appears to be private.

**Comment by jonjohnsonjr** [comment] 2019-10-10 18:21
@cpuguy83 here's one: [`gcr.io/jonjohnson/oci-image`](https://gcr.io/jonjohnson/oci-image:latest)

Should be public:
```
$ curl https://gcr.io/v2/jonjohnson/oci-image/manifests/latest
{
   "schemaVersion": 2,
   "config": {
      "mediaType": "application/vnd.oci.image.config.v1+json",
      "size": 458,
      "digest": "sha256:dbd9343fe273b7c9542c5ffd8223d1d31c002d22bc8b10d54ee739b5e03626c0"
   },
   "layers": [
      {
         "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
         "size": 654467,
         "digest": "sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff"
      }
   ]
}
```

**Comment by cpuguy83** [comment] 2019-10-10 21:32
Some progress:

```
# docker pull gcr.io/jonjohnson/oci-image
DEBU[2019-10-10T21:30:33.792040800Z] Calling GET /_ping                           
Using default tag: latest
DEBU[2019-10-10T21:30:33.796111100Z] Calling POST /v1.30/images/create?fromImage=gcr.io%2Fjonjohnson%2Foci-image&tag=latest 
DEBU[2019-10-10T21:30:33.802003600Z] hostDir: /etc/docker/certs.d/gcr.io          
DEBU[2019-10-10T21:30:33.802149400Z] Trying to pull gcr.io/jonjohnson/oci-image from https://gcr.io v2 
DEBU[2019-10-10T21:30:34.084117000Z] Pulling ref from V2 registry: gcr.io/jonjohnson/oci-image:latest 
DEBU[2019-10-10T21:30:34.084940100Z] pulling blob "sha256:dbd9343fe273b7c9542c5ffd8223d1d31c002d22bc8b10d54ee739b5e03626c0" 
DEBU[2019-10-10T21:30:34.086025400Z] pulling blob "sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff" 
latest: Pulling from jonjohnson/oci-image
dbd9343fe273: Pulling fs layer 
dbd9343fe273: Extracting [==================================================>]     458B/458B
dbd9343fe273: Extracting [==================================================>]     458B/458B
e8d8785a314f: Downloading [>                                                  ]  7.534kB/654.5kB
e8d8785a314f: Download complete 
DEBU[2019-10-10T21:30:34.434853500Z] Cleaning up layer ee511181c95e38233e02611aa8afde41df1fc0bf372c697b1689b6e63688c7c7: Error processing tar file(exit status 1): unexpected EOF 
INFO[2019-10-10T21:30:34.436135800Z] Attempting next endpoint for pull after error: failed to register layer: Error processing tar file(exit status 1): unexpected EOF 
failed to register layer: Error processing tar file(exit status 1): unexpected EOF
```

Is this a good image?

**Comment by jonjohnsonjr** [comment] 2019-10-10 21:40
> Is this a good image?

Seems to work for me:

```
$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:34:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker pull gcr.io/jonjohnson/oci-image
Using default tag: latest
latest: Pulling from jonjohnson/oci-image
e8d8785a314f: Pull complete 
Digest: sha256:86eb40b064b5a9310dbe501cdc3a454da382eb64c92d4b62179aace383b5db0f
Status: Downloaded newer image for gcr.io/jonjohnson/oci-image:latest
```

**Comment by cpuguy83** [comment] 2019-10-10 21:45
Yeah issue is in my code, thanks.

**Comment by georgepapas** [comment] 2019-10-10 22:21
```
$ docker version && docker pull gcr.io/jonjohnson/oci-image

Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Using default tag: latest
Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''```

**Comment by cpuguy83** [comment] 2019-10-10 22:44
Ok here is a patch if you'd like to give it a try: https://github.com/moby/moby/pull/40070

**Closed** 2019-10-14 04:07 UTC
Labels: area/distribution, kind/bug

**Comment by Kubend** [comment] 2019-12-13 06:19
Error starting daemon: Devices cgroup isn't mounted

**Comment by Kubend** [comment] 2019-12-13 06:20
/usr/bin # dockerd & /usr/bin # WARN[2019-12-13T05:33:43.962483660Z] could not change group /var/run/docker.sock to docker: group docker not found INFO[2019-12-13T05:33:43.972918200Z] libcontainerd: started new containerd process pid=11564 INFO[2019-12-13T05:33:43.973473840Z] parsed scheme: "unix" module=grpc INFO[2019-12-13T05:33:43.973672660Z] scheme "unix" not registered, fallback to default scheme module=grpc INFO[2019-12-13T05:33:43.974266800Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0 }] module=grpc INFO[2019-12-13T05:33:43.974498520Z] ClientConn switching balancer to "pick_first" module=grpc INFO[2019-12-13T05:33:43.974982640Z] pickfirstBalancer: HandleSubConnStateChange: 0x44209d03d0, CONNECTING module=grpc INFO[0000] starting containerd revision=468a545b9edcd5932818eb9de8e72413e616e86e version=v1.1.2 INFO[0000] loading plugin "io.containerd.content.v1.content"... type=io.containerd.content.v1 INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"... type=io.containerd.snapshotter.v1 WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" INFO[0000] loading plugin "io.containerd.snapshotter.v1.aufs"... type=io.containerd.snapshotter.v1 WARN[0000] failed to load plugin io.containerd.snapshotter.v1.aufs error="modprobe aufs failed: "modprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" INFO[0000] loading plugin "io.containerd.snapshotter.v1.native"... type=io.containerd.snapshotter.v1 INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"... type=io.containerd.snapshotter.v1 INFO[0000] loading plugin "io.containerd.snapshotter.v1.zfs"... type=io.containerd.snapshotter.v1 WARN[0000] failed to load plugin io.containerd.snapshotter.v1.zfs error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"... type=io.containerd.metadata.v1 WARN[0000] could not use snapshotter zfs in metadata plugin error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" WARN[0000] could not use snapshotter btrfs in metadata plugin error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" WARN[0000] could not use snapshotter aufs in metadata plugin error="modprobe aufs failed: "modprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" INFO[0000] loading plugin "io.containerd.differ.v1.walking"... type=io.containerd.differ.v1 INFO[0000] loading plugin "io.containerd.gc.v1.scheduler"... type=io.containerd.gc.v1 INFO[0000] loading plugin "io.containerd.service.v1.containers-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.service.v1.content-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.service.v1.diff-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.service.v1.images-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.service.v1.leases-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.service.v1.namespaces-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.service.v1.snapshots-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.monitor.v1.cgroups"... type=io.containerd.monitor.v1 INFO[0000] loading plugin "io.containerd.runtime.v1.linux"... type=io.containerd.runtime.v1 INFO[0000] loading plugin "io.containerd.service.v1.tasks-service"... type=io.containerd.service.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.containers"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.content"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.diff"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.events"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.healthcheck"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.images"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.leases"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.namespaces"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.snapshots"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.tasks"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.version"... type=io.containerd.grpc.v1 INFO[0000] loading plugin "io.containerd.grpc.v1.introspection"... type=io.containerd.grpc.v1 INFO[0000] serving... address="/var/run/docker/containerd/containerd-debug.sock" INFO[0000] serving... address="/var/run/docker/containerd/containerd.sock" INFO[0000] containerd successfully booted in 0.007964s INFO[2019-12-13T05:33:44.037192880Z] pickfirstBalancer: HandleSubConnStateChange: 0x44209d03d0, READY module=grpc WARN[2019-12-13T05:33:44.055363740Z] unable to modify root key limit, number of containers could be limited by this quota: open /proc/sys/kernel/keys/root_maxkeys: no such file or directory INFO[2019-12-13T05:33:44.069505680Z] parsed scheme: "unix" module=grpc INFO[2019-12-13T05:33:44.069597200Z] scheme "unix" not registered, fallback to default scheme module=grpc INFO[2019-12-13T05:33:44.069762620Z] parsed scheme: "unix" module=grpc INFO[2019-12-13T05:33:44.069785500Z] scheme "unix" not registered, fallback to default scheme module=grpc ERRO[2019-12-13T05:33:44.074558960Z] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. storage-driver=overlay2 INFO[2019-12-13T05:33:44.077780460Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0 }] module=grpc INFO[2019-12-13T05:33:44.077981520Z] ClientConn switching balancer to "pick_first" module=grpc INFO[2019-12-13T05:33:44.077954420Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0 }] module=grpc INFO[2019-12-13T05:33:44.078067840Z] ClientConn switching balancer to "pick_first" module=grpc INFO[2019-12-13T05:33:44.078249520Z] pickfirstBalancer: HandleSubConnStateChange: 0x442003b7f0, CONNECTING module=grpc INFO[2019-12-13T05:33:44.078282380Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420630390, CONNECTING module=grpc INFO[2019-12-13T05:33:44.079067860Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420630390, READY module=grpc ERRO[2019-12-13T05:33:44.079864740Z] AUFS was not found in /proc/filesystems storage-driver=aufs INFO[2019-12-13T05:33:44.081833940Z] pickfirstBalancer: HandleSubConnStateChange: 0x442003b7f0, READY module=grpc ERRO[2019-12-13T05:33:44.084306660Z] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. storage-driver=overlay ERRO[2019-12-13T05:33:44.084462420Z] Failed to built-in GetDriver graph devicemapper /var/lib/docker INFO[2019-12-13T05:33:44.085688620Z] Graph migration to content-addressability took 0.00 seconds WARN[2019-12-13T05:33:44.085839360Z] Failed to parse cgroup information: Failed to parse cgroup information: open /proc/self/cgroup: no such file or directory INFO[2019-12-13T05:33:44.087039780Z] stopping event stream following graceful shutdown error="context canceled" module=libcontainerd namespace=plugins.moby INFO[2019-12-13T05:33:44.087220880Z] stopping healthcheck following graceful shutdown module=libcontainerd INFO[2019-12-13T05:33:44.088222280Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420630390, TRANSIENT_FAILURE module=grpc INFO[2019-12-13T05:33:44.088358420Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420630390, CONNECTING module=grpc Error starting daemon: Devices cgroup isn't mounted

**Comment by cpuguy83** [comment] 2019-12-14 16:02
@Kubend I'm not sure why you are commenting on this issue. Your error is not the same at all.
Most likely your issue is caused because you are using unified cgroup hierarchy (default in Fedora 31) which is not currently supported.

If you are using Fedora 31, you can use this and docker _should_ work:

```
sudo dnf install grubby
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
```
