### ISSUE TITLE
Dns resolved failed when start docker in binary mode

### ISSUE THREAD

**Issue by guanglinlv** [moby/moby#16099] opened 2015-09-06 03:22 UTC
Hi dockers,

I started docker binary in command line, like

 `/usr/bin/docker-1.8.1 daemon -s devicemapper --dns dns-b-address &`

then i try to pull my image,like 

`/usr/bin/docker-18.1 pull private-registry.domain.com/namespace/image:latest`

it report a dns resolved error `Error while pulling image: dia tcp lookup private-registry.domain.com on dns-a-address:53:no such host`

my /etc/resolv.conf is : 

``` shell
# Generated by NetworkManager
search domain.com
nameserver dns-a-address # Can not serve private-registry.domain.com
nameserver dns-b-address # can serve private-registry.domain.com
```

it seems `--dns` flag is not working for docker binary mode. because it will work correctly when i start docker as a systemd service( or service docker start).

did anyone has encounterd the likely problem? 

I'm not sure this issue is duplicate or not, so i include following BUG REPORT INFORMATION, if it's duplicate please notify me and close it. thanks.
## docker version 

``` shell
INFO[0020] GET /v1.20/version                           
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```
## docker info

``` shell
INFO[0024] GET /v1.20/info                              
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:1-1707756-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 37.96 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.2
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.859 GiB
Name: docker-centos-7.novalocal
ID: CLCZ:NKHK:FUSX:UPFX:RKPU:AQBD:VULC:THR5:7OEK:SDGW:UXPR:Y3ZF
```
## uname -a

``` shell
Linux docker-centos-7.novalocal 4.0.2 #1 SMP Mon Jun 8 13:56:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
## reproduce
1. download binary version from docker https://get.docker.com/builds/Linux/x86_64/docker-latest.
2. configure `/etc/resolv.conf`:

``` shell
# Generated by NetworkManager
search domain.com
nameserver dns-a-address # Can not serve private-registry.domain.com
nameserver dns-b-address # can serve private-registry.domain.com
```
1. run docker -d --dns  dns-b-address
2. docker pull pull private-registry.domain.com/namespace/image:latest
## Error informations

``` shell
Error while pulling image: private-registry.domain.com/namespace/image:latest : dia tcp lookup private-registry.domain.com on dns-a-address:53:no such host
```
## expect

docker will use the nameserver specified by `--dns` option or try next nameserver listed in `/etc/resolv.conf`

Thanks.

**Comment by udomsak** [comment] 2015-09-06 16:39
@GordonTheTurtle 

# docker version:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

#Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

```
# docker info:
```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 2.929 GiB
Name: node01
ID: QSYI:IILR:JI3B:7AQX:YXQ2:2TJ6:T7CT:HCC4:SRDP:EDHK:DJOT:7DQC


```
# uname -a:
```
Linux node01 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

# Enviorntment run. 

- KVM on Fedora core22 host os.  

# Reproduce


List the steps to reproduce the issue:
1 download binary version from docker https://get.docker.com/builds/Linux/x86_64/docker-latest.
2.run ``` docker -d --dns 8.8.8.8 ```  or  ``` docker -d  ``` 
3. docker pull ubuntu:14.04 

## docker said not found index.io
```
root@node01:~# docker pull ubuntu:14.04
Pulling repository docker.io/library/ubuntu
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.
root@node01:~# 

```
## Error log from docker daemon 

```
ERRO[0146] Couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH 
INFO[0151] GET /v1.20/version                           
INFO[0154] GET /containers/json                         
INFO[0155] GET /version                                 
INFO[0181] GET /v1.20/info                              
INFO[0184] GET /containers/json                         
INFO[0193] GET /v1.20/version                           
INFO[0214] GET /containers/json                         
INFO[0215] GET /version                                 
INFO[0238] GET /v1.20/info                              
INFO[0244] GET /containers/json                         
INFO[0274] GET /containers/json                         
INFO[0275] GET /version                                 
INFO[0304] GET /containers/json                         
INFO[0334] GET /containers/json                         
INFO[0335] GET /version                                 
INFO[0364] GET /containers/json                         
INFO[0394] GET /containers/json                         
INFO[0395] GET /version                                 
INFO[0424] GET /containers/json                         
INFO[0454] GET /containers/json                         
INFO[0455] GET /version                                 
INFO[0484] GET /containers/json                         
INFO[0491] POST /v1.20/images/create?fromImage=ubuntu%3A14.04 
INFO[0501] Trust graph fetch failed: Get https://dvjy3tqbc323p.cloudfront.net/trust/official.json: dial tcp: lookup dvjy3tqbc323p.cloudfront.net on 192.168.122.1:53: read udp 192.168.122.1:53: i/o timeout 
INFO[0514] GET /containers/json                         
INFO[0515] GET /version                                 
INFO[0516] Trust graph fetch failed: Get https://dvjy3tqbc323p.cloudfront.net/trust/official.json: dial tcp: lookup dvjy3tqbc323p.cloudfront.net on 192.168.122.1:53: read udp 192.168.122.1:53: i/o timeout 

```
I saw some one open this issue but closed because he use vagrant instead.  I use docker by binary release cause can't connect to download from docker apt site. (  06-09-2015 ). 

Thank you. :)

**Comment by cpuguy83** [comment] 2015-10-02 15:14
Are you able to use curl to access these URLs?
i/o timeout is very different from name resolution.

**Comment by guanglinlv** [comment] 2015-10-15 08:14
@cpuguy83 ,
sorry for late response.yes,i did access these URLs with curl tools.i think docker must use a wrong DNS address.

**Comment by martina-if** [comment] 2015-10-22 15:29
Hi, I think the man page of docker is not very clear regarding the --dns option. 

It says "Force Docker to use specific DNS servers". This option works for both daemon and CLI modes of running the docker command, but it means that it will hardcode this dns nameserver in the file /etc/resolv.conf when running containers. It does not mean that it will use that dns when the daemon has to resolve a name. It's for the containers.

What I believe you need is to use your private dns (dns-b-address) as your primary nameserver in /etc/resolv.conf and make this server forward the public names to a public dns (dns-a-address).

I suggest a PR to clarify this on the man page or close the issue.

**Comment by guanglinlv** [comment] 2015-10-26 08:29
@martina-if 
ugh,you are right about `--dns` option .but if i raise docker as a systemd service not binary, docker damon can resolve correctly with my private dns(dns-b-address). puzzled...

**Comment by martina-if** [comment] 2015-10-26 08:48
@guanglinlv You could start the daemon with systemd and then list the process with ps (```ps aux | grep docker```) and see exactly what binary and what arguments is it using to start docker. You might have extra options defined in /etc/default/docker (example file for ubuntu) that are only used when you run it with systemd.

You might also be running different versions. systemd is probably using /usr/bin/docker while you start /usr/bin/docker-1.8.1.

**Comment by thaJeztah** [comment] 2024-01-09 21:56
Let me close this one, as it went stale

**Closed by thaJeztah** 2024-01-09 21:56 UTC
Labels: area/networking, version/1.8
