### ISSUE TITLE
Escaping double quotes in dockerfile for windows images

### ISSUE THREAD

**Issue by pweibel** [moby/moby#34013] opened 2017-07-07 16:12 UTC
I've got 2 use cases which stopped working with the latest version of docker. But unfortunately I can't say with which version it started.

Use Case 1:
I generate a config file for an asp.net page with a custom console application. Therefore I have the key/values for the config file in the parameter:
```
RUN C:\\deployment\\tool.exe -value "ConnectionString=\"Server=localhost;Database=Test;User Id=sa;Password=password\";Title=\"Test\"" -dir C:\inetpub\wwwroot\Test
```

Use Case 2:
I generate also a json file with the tool. Also here I pass the json content as parameter:
```
RUN C:\\deployment\\tool.exe -value "{\""Title\"":\""Unknown\"",\""Packages\"":[{\""Id\"":\""Test\"",\""Version\"":\""*\"",\""Configuration\"":\""Release\""}]}" -dir C:\inetpub\wwwroot\Test
```

Both cases generate now powershell errors. I can't find a way to get it working again.

**Comment by thaJeztah** [comment] 2017-07-08 06:24
What base image are you building from? Docker 1.12 added an `escape` directive to the Dockerfile format; this allows you to use a different escape character for instructions in the Dockerfile (e.g., use backtick  (\`) , instead of back-slashes if PowerShell is used as shell instead of `cmd.exe`; see https://docs.docker.com/engine/reference/builder/#escape (this feature was added in https://github.com/moby/moby/pull/22268)

It's now also possible to override the default shell (e.g., use `bash` instead of `sh` on Linux, or `PowerShell` instead of `cmd.exe` on Windows) using the `SHELL` Dockerfile instruction https://docs.docker.com/engine/reference/builder/#shell this feature was also added in Docker 1.12 (through pull request https://github.com/moby/moby/pull/22489)

Possibly the base image you're building from was updated to use these features, or the options were set, but not yet supported on your version of Docker

Based on the above, I suspect this is not a bug, however, without more information it's not possible to tell

Can you;

- tell which version of Docker you were running before
- provide the output of `docker version` and `docker info`
- provide a full example of a Dockerfile to reproduce the issue
  - keep the reproduction case as simple as possible, just the minimal steps to reproduce the issue
  - take into account that we don't have access to private images, or source code :smile:

**Comment by pweibel** [comment] 2017-07-08 08:27
The docker files were created and tested with the docker engine 1.13 on windows 10 and windows server 2016 (engine 1.12.2).
The error messages occur now on the current docker version 17.06-ce. I retested it today on windows server 2016 (azure) and it still work there.

Windows 10 (local desktop machine):
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: true

Containers: 69
 Running: 0
 Paused: 0
 Stopped: 69
Images: 18
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.94GiB
Name: pcname
ID: QD7F:4MP5:TCC3:E6UV:6EP6:CNCL:RMFJ:NXDD:U3FF:HCNL:TZIW:ID62
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 42
 System Time: 2017-07-08T10:19:53.1730172+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Windows 2016:
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7 GiB
Name: srvAzure
ID: 7UME:3X4E:3EDE:U7OG:TLEE:7D5W:VH54:KM65:FGT4:SZAV:LWW7:5SMB
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by pweibel** [comment] 2017-07-08 14:53
Here the demo docker file which is running on windows server 2016, but failing on windows 10 with the latest docker version:
```
FROM microsoft/aspnet:latest

RUN echo "{\""Title\"":\""Unknown\"",\""Packages\"":[{\""Id\"":\""Test\"",\""Version\"":\""*\"",\""Configuration\"":\""Release\""}]}"

RUN echo "ConnectionString=\"Server=localhost;Database=Test;User Id=sa;Password=password\";Title=\"Test\""
```

**Comment by thaJeztah** [comment] 2017-07-08 18:33
Can you verify that both servers have the same version of the `microsoft/aspnet:latest` image? `:latest` is a rolling tag, so _currently_, latest points to https://github.com/Microsoft/aspnet-docker/blob/master/4.7/Dockerfile#L3 (thus using PowerShell), but previously `:latest` could've been https://github.com/Microsoft/aspnet-docker/blob/master/3.5/Dockerfile (which uses `CMD.exe`).

I do see that two months ago, the `microsoft/aspnet:4.6.2` image changed from `CMD.exe` to `PowerShell.exe` (which is kind of surprising to do for an existing tag); https://github.com/Microsoft/aspnet-docker/commit/6f15ac6c51872c30bb94436b6d12c1622ca9f7f7

Actually, I see someone commented about that on the pull request; https://github.com/Microsoft/aspnet-docker/pull/29#discussion_r123203828

**Comment by pweibel** [comment] 2017-07-09 19:00
Is there a way to find out the version of the image locally?

I used the command docker image inspect microsoft/aspnet.

There I can't see the version of the installed image. But I see the Created info:
Windows 10: 2017-06-14 (DockerVersion: 17.03.1-ee-3)
Windows Server 2016: 2017-03-14 (DockerVersion: 17.03.0-ce)

**Comment by thaJeztah** [comment] 2017-07-09 20:31
The "digest" of both images should match if they're the same image (`docker images --digests` to show the image digest)

It may be easier to look at `docker history --no-trunc <your image>`, which would show all the steps that were used to create the image

**Comment by thaJeztah** [comment] 2017-07-09 20:33
If this is indeed the cause; I suggest opening an issue in the issue tracker for that image; making such a breaking change without changing the tag is not really best practice

**Comment by pweibel** [comment] 2017-07-10 06:14
I think there are 2 problems:
- Breaking Change in the image of microsoft/aspnet with the Shell-Change
- Unclear how to escape double quotes with the shell configuration (docker + powershell + dockerfile)

**Comment by thaJeztah** [comment] 2020-03-10 08:51
closing this one; the initial issue looks to be related to changes in the base image. As to better documentation around escaping; perhaps someone could open a ticket for the documentation (or a pull request); https://github.com/docker/docker.github.io/issues

**Closed by thaJeztah** 2020-03-10 08:51 UTC
Labels: area/builder, area/docs, exp/beginner, platform/windows, status/more-info-needed
