### ISSUE TITLE
docker picking "nfs" driver when it should have picked "local" driver

### ISSUE THREAD

**Issue by devendra-nvidia** [moby/moby#31261] opened 2017-02-22 20:45 UTC
**Description**
1. Lets say docker image is created with VOLUME instruction to create a mount point /myvol
2. We spin up a container with following run command.
    docker run -ir --name test  --entrypoint /bin/bash {myimage}
   We notice that docker user local volume driver and creates a directory /myvol on the host and mounts inside the container.
4. We spin up the container with following run command
  docker run -ir --name test --volume-driver=nfs -v 10.0.2.15/shome:/shome -v /myvol:/myvol --entrypoint /bin/bash {myimage}
  we notice that the /myvol is mounted using local driver and /shome is mounted using nfs driver.
5. We spin up the container with following run command
  docker run -ir --name test --volume-driver=nfs -v 10.0.2.15/shome:/shome --entrypoint /bin/bash {myimage}
  we notice that the run command fails. Docker tries to mount /myvol using nfs driver instead of local driver. This seems little ambiguous. What is the expected behaviour in this case?

**Steps to reproduce the issue:**
1. Get following environment ubuntu 14.04.5 , docker-engine: 1.11.0-0~trusty, docker-volume-netshare: 0.32

2. Create an image from following Docker file
FROM busybox
RUN mkdir /myvol
RUN echo "hello world" > /myvol/greeting
VOLUME /myvol

3. docker build -t volume:yes .

4. docker run --rm -it --name crash --volume-driver=nfs -v 10.0.2.15/shome:/mount  -v /myvol:/myvol --entrypoint /bin/bash volume:yes

5. docker run --rm -it --name crash --volume-driver=nfs -v 10.0.2.15/shome:/mount --entrypoint /bin/bash volume:yes

**Describe the results you received:**
1. Step 4 succeeds. Verify that the nfs driver is used to mount 10.0.2.15/shomre and local driver is used to mount /myvol
2. step 5 fails. If the docker-engine is running in debug mode then we can see that docker used nfs driver to mount /myvol (exposed via container layer)

**Describe the results you expected:**
 I am expecting in step 5, docker uses local driver and creates a mount point on the host.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
OS/Arch: linux/amd64
```

**Output of `docker info`:**

```
Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.6 MiB
Name: ubuntu
ID: EXTJ:BNAT:LAGI:CITE:I2N5:LUEF:JWGU:6TPM:7FPQ:2Q5R:2B44:Q5JV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 28
 System Time: 2017-02-22T12:40:35.866031702-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.): virtualbox**

**Comment by thaJeztah** [comment] 2017-02-22 20:57
> step 5 fails. If the docker-engine is running in debug mode then we can see that docker used nfs driver to mount /myvol (exposed via container layer)

Correct; the `--volume-driver` option is applied to _all_ volumes, including volumes that are implicitly created if the image that is run has a `VOLUME` declaration. In that case, docker will create an anonymous volume, using the `nfs` driver (which probably fails), and bind-mount that volume in the container.

The reason you're not having that problem in step 4, is that you're using an absolute path (`/myvol:/myvol`) for the left-hand part of the volume option, so a bind-mounted host directory is used, not a volume.

From the output of your `docker info`, I don't see a `nfs` volume driver plugin installed; does it actually work in step 4?

**Comment by thaJeztah** [comment] 2017-02-22 20:59
The discussion on https://github.com/docker/docker/issues/16069 may be relevant here as well

**Comment by blackgold** [comment] 2017-02-22 21:10
yup I verified just now and I can see docker-volume-netshare plugin is running.  I ran step 5 and  following is docker log output for step5
```
time="2017-02-22T13:01:18.722869418-08:00" level=debug msg="Calling GET /v1.23/info" 
time="2017-02-22T13:05:27.782101592-08:00" level=debug msg="Calling POST /v1.23/containers/create?name=crash" 
time="2017-02-22T13:05:27.782422290-08:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":[\"/bin/sh\"],\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioBps\":0,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioIOps\":0,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SandboxSize\":0,\"SecurityOpt\":null,\"ShmSize\":0,\"StorageOpt\":null,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"nfs\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"volume:yes\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":true,\"StdinOnce\":true,\"Tty\":true,\"User\":\"\",\"Volumes\":{\"10.0.2.15/shome/mount\":{}},\"WorkingDir\":\"\"}" 
time="2017-02-22T13:05:27.782998622-08:00" level=error msg="Handler for POST /v1.23/containers/create returned error: Invalid volume spec \"10.0.2.15/shome/mount\": Invalid volume destination path: '10.0.2.15/shome/mount' mount path must be absolute." 
time="2017-02-22T13:05:39.359321586-08:00" level=debug msg="Calling POST /v1.23/containers/create?name=crash" 
time="2017-02-22T13:05:39.359651635-08:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":[\"/bin/sh\"],\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":[\"10.0.2.15/shome:/mount\"],\"BlkioBps\":0,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioIOps\":0,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SandboxSize\":0,\"SecurityOpt\":null,\"ShmSize\":0,\"StorageOpt\":null,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"nfs\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"volume:yes\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":true,\"StdinOnce\":true,\"Tty\":true,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}" 
time="2017-02-22T13:05:39.376106342-08:00" level=debug msg="nfs implements: VolumeDriver" 
time="2017-02-22T13:05:39.376238311-08:00" level=debug msg="Registering new volume reference: driver \"nfs\", name \"10.0.2.15/shome\""
time="2017-02-22T13:05:39.382434025-08:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/0838fb07e187a3a548c2cb3cd68013fbb489962641e499664f9bbeb6ad05368d" 
time="2017-02-22T13:05:39.383544675-08:00" level=debug msg="Registering new volume reference: driver \"nfs\", name \"fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f\"" 
time="2017-02-22T13:05:39.385524437-08:00" level=debug msg="copying image data from 335db711c024b94a9086edea78e6a61b917f8ad03c438e65a7e1fa9e28d29971:/mount, to 10.0.2.15/shome" 
time="2017-02-22T13:05:39.385631192-08:00" level=debug msg="copying image data from 335db711c024b94a9086edea78e6a61b917f8ad03c438e65a7e1fa9e28d29971:/myvol, to fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f" 
time="2017-02-22T13:05:39.396274682-08:00" level=debug msg="Removing volume reference: driver nfs, name fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f" 
time="2017-02-22T13:05:39.397981724-08:00" level=error msg="Handler for POST /v1.23/containers/create returned error: VolumeDriver.Mount: exit status 32" 
```

**Comment by blackgold** [comment] 2017-02-22 21:14
There is a issue opened with docker-volume-netshare  plugin here https://github.com/ContainX/docker-volume-netshare/issues/50
Following is the fns plugin log output. It fails resolving hostname as it's in unexpected format.

```
time="2017-02-22T13:01:07-08:00" level=info msg="Starting NFS Version 3 :: options: 'nfsvers=3,fsc,noatime,hard,intr,proto=tcp,timeo=600,retrans=10,sec=sys'" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Entering Get: {10.0.2.15/shome map[]}" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Entering Create: name: 10.0.2.15/shome, options map[]" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Create volume -> name: 10.0.2.15/shome, map[]" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Host path for 10.0.2.15/shome (10.0.2.15/shome) is at /var/lib/docker-volumes/netshare/nfs/10.0.2.15/shome" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Entering Get: {fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f map[]}" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Entering Create: name: fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f, options map[]" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Create volume -> name: fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f, map[]" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Host path for fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f (fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f) is at /var/lib/docker-volumes/netshare/nfs/fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Entering Mount: {fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f }" 
time="2017-02-22T13:05:39-08:00" level=info msg="Mounting NFS volume fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f: on /var/lib/docker-volumes/netshare/nfs/fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Mounting with NFSv3 - src: fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f:, dest: /var/lib/docker-volumes/netshare/nfs/fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f" 
time="2017-02-22T13:05:39-08:00" level=debug msg="exec: mount -v -t nfs -o nfsvers=3,fsc,noatime,hard,intr,proto=tcp,timeo=600,retrans=10,sec=sys fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f: /var/lib/docker-volumes/netshare/nfs/fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f\n" 
2017/02/22 13:05:39 mount.nfs: Failed to resolve server fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f: Name or service not known

time="2017-02-22T13:05:39-08:00" level=debug msg="Entering Remove: name: fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f, resolved-name: fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f, options map[]" 
time="2017-02-22T13:05:39-08:00" level=debug msg="Delete volume: fd52d47a2b61546aaab685afe7f04a0a731f7920df38fe2cc458313508f3482f, connections: 0" 
```

**Comment by thaJeztah** [comment] 2017-02-22 21:27
Yes, that's expected; that plugin encodes the nfs location/settings in the name of the volume. The random name of the "anonymous" volume therefore fails (as it's in the right format); which you noticed.

Note that you don't actually need a plugin to use nfs; you can create a volume that uses nfs using the local volume driver; see https://github.com/docker/docker/blob/v1.13.1/docs/reference/commandline/volume_create.md#driver-specific-options

Doing so, you can create the volume first (giving it any name you'd like), and then use it as a named volume on the container. You won't need the `--volume-driver` option, and don't run into this issue

**Comment by thaJeztah** [comment] 2017-06-07 16:56
Let me close this issue, because this is not a bug, and I think the question is answered

**Closed by thaJeztah** 2017-06-07 16:56 UTC
Labels: area/builder, version/1.11
