### ISSUE TITLE
Filters broken in 17.06 API

### ISSUE THREAD

**Issue by ymoses** [moby/moby#34121] opened 2017-07-15 06:34 UTC
Hi,
Since I upgraded to 17.06, I can't prune stopped containers with name-based filters. (The same error happened with other kinds of filters).

For example: 

> $ docker container prune --filter name=foobar
> WARNING! This will remove all stopped containers.
> Are you sure you want to continue? [y/N] y
> Error response from daemon: Invalid filter 'name'

This still works in older versions.

**Comment by thaJeztah** [comment] 2017-07-15 08:07
This is not a bug; `docker system prune` (as of version 17.06) only supports `label`, and `until` filters; https://github.com/docker/docker-ce/blob/v17.06.0-ce/components/cli/docs/reference/commandline/system_prune.md#filtering

the `name` filter never was supported, but there was no validation in earlier versions of docker, so unknown filters were silently ignored;

Here's on Docker 17.05 CE

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```


Create two containers, `foo`, and `bar`

```bash
$ docker run --name foo busybox
$ docker run --name bar busybox
```

These exit immediately, so both are stopped now;

```bash
$ docker ps -a

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
5c1a08f74928        busybox             "sh"                4 seconds ago       Exited (0) 3 seconds ago                       bar
020b13ef4feb        busybox             "sh"                9 seconds ago       Exited (0) 8 seconds ago                       foo
```

Run `docker system prune`, "filter by name"

```bash
$ docker system prune --filter name=foo
WARNING! This will remove:
	- all stopped containers
	- all volumes not used by at least one container
	- all networks not used by at least one container
	- all dangling images
Are you sure you want to continue? [y/N] y
Deleted Containers:
5c1a08f74928bd2fa4d90c47852cb415fd726a369901ff1232e886fff5525b17
020b13ef4feb9e31a51ec024b619aa72d4a826966979a256f06bfc7903ed3c20

Total reclaimed space: 0B
```

Both containers are deleted, because there's no validation on valid filters,
thus the invalid `name` filter is silently ignored.

As a result, all containers were removed, not just the `name` fillter

```bash
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

On docker 17.05, "any" filter could be provided;

```bash
$ docker system prune -f --filter kjhasdkjhdskjhad=kjhasdkjhasdkjhads
Total reclaimed space: 0B
```

**Comment by thaJeztah** [comment] 2017-07-15 08:07
Closing, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-15 08:07 UTC

**Comment by ymoses** [comment] 2017-07-16 07:52
Thanks for the clarification!
