### ISSUE TITLE
docker inspect <container-id> returns blank IP address

### ISSUE THREAD

**Issue by varunu28** [moby/moby#35750] opened 2017-12-08 22:40 UTC
The docker container is running

```
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
51759b362a9f        starbucks           "/bin/sh -c 'java ..."   3 hours ago         Up 3 hours                              starbucks

```
But the docker inspect gives a blank IP address

```
docker inspect

[
    {
        "Id": "51759b362a9f03b59d1f671437b08a183a7f6a31348df9626ecddef945b96271",
        "Created": "2017-12-08T19:54:19.522141601Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "java -cp /srv/starbucks-all.jar api.StarbucksServer"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3185,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-12-08T19:54:19.7915843Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:5727c5c2f3629ff5b9c012ca3ef610538169b0ba8878eaa241a9123331a91d54",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/51759b362a9f03b59d1f671437b08a183a7f6a31348df9626ecddef945b96271/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/51759b362a9f03b59d1f671437b08a183a7f6a31348df9626ecddef945b96271/hostname",
        "HostsPath": "/mnt/sda1/var/lib/docker/containers/51759b362a9f03b59d1f671437b08a183a7f6a31348df9626ecddef945b96271/hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/51759b362a9f03b59d1f671437b08a183a7f6a31348df9626ecddef945b96271/51759b362a9f03b59d1f671437b08a183a7f6a31348df9626ecddef945b96271-json.log",
        "Name": "/starbucks",
        "RestartCount": 0,
        "Driver": "aufs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "default",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9090/tcp": {}
            },
            "Tty": true,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/docker-java-home",
                "JAVA_VERSION=8u151",
                "JAVA_DEBIAN_VERSION=8u151-b12-1~deb9u1",
                "CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "java -cp /srv/starbucks-all.jar api.StarbucksServer"
            ],
            "ArgsEscaped": true,
            "Image": "starbucks",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9a68c978cd53798aad7773234eb77a62c67dca9733b778f3598217aad51d088b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "599fbd5dd40dbc693e18b2630984b21aa814a2992365d56e80167b397d43a36c",
                    "EndpointID": "fa78d711e81fd235978763893b27e2286a96019b53ea04149f8930ec6193ca03",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

```
docker version:

Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:39:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
```
docker info

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.11.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.100-boot2docker
Operating System: Boot2Docker 17.11.0-ce (TCL 7.2); HEAD : e620608 - Tue Nov 21 18:11:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.7MiB
Name: default
ID: 554U:OMCF:I323:4HSV:E3KL:DKIA:UJKJ:4KUN:P5EV:RUBN:G6LP:HF7B
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 38
 System Time: 2017-12-08T22:28:57.813206534Z
 EventsListeners: 0
Username: varunu28
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```

**Comment by thaJeztah** [comment] 2017-12-09 06:48
This is expected; from the output; the container is running in host-mode networking (`--network=host`); in that mode, the container does not have its own networking namespace, and shares the networking namespace with the host. Basically (from a networking perspective) it's the equivalent of running the process directly on the host, outside of a container.

When running in the hosts networking namespace, containers

- don't get their own IP-address (it's the same IP-address as the host itself)
-` localhost` of the container is the same as `localhost` of the host
- there is no "portmapping"; any port that's exposed by the container is directly accessible

I'm closing this issue, because this is not a bug, but feel free to discuss

**Closed by thaJeztah** 2017-12-09 06:48 UTC
Labels: platform/arm, version/17.11

**Comment by ShubhasisMathur** [comment] 2018-03-14 18:21
Hello Jeztah, 
I am also facing the same issue. My docker container is returning no ip address. This container is having a nginx image. 
I am using Amazon ECS. Because the ip address is blank, my EC2 instance is not resolving the hostnameip:80. Is there a way to give ip address to the container so that nginx image gets executed on "the hostname:80"

**Comment by sl5net** [comment] 2018-03-22 14:19
i am using wordpress_(started by docker pull wordpress --platform linux)
BTW
https://piratenpad.de/p/docker_pull_wordpress_--platform_linux
what/how is the use of a docker without a IP-Adress?

**Comment by westfly** [comment] 2021-03-04 01:07
> Hello Jeztah,
> I am also facing the same issue. My docker container is returning no ip address. This container is having a nginx image.
> I am using Amazon ECS. Because the ip address is blank, my EC2 instance is not resolving the hostnameip:80. Is there a way to give ip address to the container so that nginx image gets executed on "the hostname:80"

Alternatively you can use Network Mode: host where the task will share the IP of the EC2 instance and will be accessible on the instance IP port 80
