### ISSUE TITLE
Possible Btrfs volume corruption during downgrade of 23.0 to 20.10

### ISSUE THREAD

**Issue by droans** [moby/moby#44903] opened 2023-02-02 16:27 UTC
### Description

Running Ubuntu 22.04, filesystem of partition is btrfs.

I experienced similar issues to #44901 when I updated this morning. I rebooted, hoping that would fix the issue, but it did not. 

In order to get my containers working again, I then downgraded to v20.10.22~3-0. Unfortunately, sometime between the initial install and the downgrade, my `/home` btrfs partition experienced corruption. All of the corrupted files belong to Docker volumes. 

I cannot tell for certain when the corruption occurred, but the last Bash command available after I restarted was the reboot. 

### Reproduce

1. Same steps as #44901 
2. sudo reboot
3. sudo apt upgrade
4. sudo apt install --reinstall docker-ce=5:20.10.23~3-0~ubuntu-jammy

### docker version

```bash
Client:
  Version:           23.0.0
  API version:       1.41 (downgraded from 1.42)
  Go version:        go1.19.5
  Git commit:        e92dd87
  Built:             Wed Feb  1 17:47:51 2023
  OS/Arch:           linux/amd64
  context:           default

Server:
  Engine:
    Version:          20.10.23
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.18.10
    Git commit:       6051f14
    Built:            Thu Jan 19 17:42:57 2023
    OS/Arch:          linux/amd64
    Experimental:     false
  containerd:
    Version:          1.6.16
    GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
  runc:
    Version:          1.1.4
    GitCommit:        v1.1.4-0-g5fd4c4d
  docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0

Apologies if there are any mistakes - I am writing everything manually since I can't use the browser on my server.
```

### docker info

```bash
Client:
  Context:    default
  Debug Mode: false
  Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.10.2
      Path:     /usr/libexec/docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.3.3
      Path:     /home/michael/.docker/cli-plugins/docker-compose
    scan: Docker Scan (Docker Inc.)
      Version:  v0.23.0
      Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
  Containers: 66
    Running: 51
    Paused: 0
    Stopped: 15
Images: 83
Server Version: 20.10.23
Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
Logging Driver: json-file
Cgroup Driver: systemd
Cgroup Version: 2
Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia
Default Runtime: runc
Init Binary: docker-init
containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
runc version: v1.1.4-0-g5fd4c4d
init version: de40ad0
Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
Kernel Version: 5.15.0-58-gemeroc
Operating System: Ubuntu 22.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.27GiB
Name: server
ID: C76W:X04M:4JRJ:WZ32:M0AC:C6DS:HYHS:F3X0:ITKF:W7NI:BZEG:M55A
Docker Root Dir: /var/lib/docker
Debug Mode: false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
  127.0.0.0/8
Live Restore Enabled: false
```

**Comment by satmandu** [comment] 2023-02-02 16:46
Also may be connected to this: https://github.com/moby/moby/issues/44905

`journalctl -xeu docker.service` may give you more information about why docker failed.

**Comment by droans** [comment] 2023-02-02 16:58
Little update. I accidentally allowed Docker to reattempt the upgrade, which of course failed again. However, after I rebooted, my filesystem is working properly.

I think my issue here is stemming from the versions being mismatched. Unfortunately, I don't know which versions are all required.

**Comment by droans** [comment] 2023-02-02 19:46
One more update - the downgrade doesn't appear to be the issue. 

I completely purged Docker and all Docker directories from my computer. I then ran the Docker installer script which grabbed and installed fine.

However... Each time Docker starts, the drive is forced into read-only mode and btrfs reports failed checksums and data corruption. If I disable Docker and restart, there is no issue. Yet, again, if I start the service up, the issues reappear.

**Comment by neersighted** [comment] 2023-02-02 19:59
As the author of https://github.com/moby/moby/pull/44761, I'm immediately wondering if something broke due to moving to the kernel headers. However, the structures they define are more-or-less identical, so it's hardly a smoking gun.

**Comment by droans** [comment] 2023-02-02 20:11
Looking at the [deprecated](https://docs.docker.com/engine/deprecated/) section in the docs, it says that btrfs is targeted for removal.

I don't know if Docker set the volumes up as btrfs or as overlay2 initially. I wonder if a change in storage driver during the update caused corruption.

**Comment by neersighted** [comment] 2023-02-02 22:14
Ah, I should have looked closer at your initial `docker info` -- you're using the `overlay2` storage driver, and not the `btrfs` storage driver.

I don't think Docker can be involved here -- if you are able to reproduce in a standalone VM with Btrfs, that would be quite interesting. However I don't think overlay2 can do anything that could result in a corrupt Btrfs volume, as it only uses the overlay kernel module + standard system calls (nothing Btrfs-specific). As such, I suspect you have some underlying filesystem issue that you only noticed during install/upgrade of Docker CE, or that the overlay kernel module perturbs.

**Comment by droans** [comment] 2023-02-02 22:31
Correct. Although, in fairness, the majority of my partition is used for various container data, mostly Plex transcoding data and MariaDB databases. 

However, it is still extraordinarily odd that the issue only started appearing after the failed update and only when Docker is running.

**Comment by neersighted** [comment] 2023-02-02 22:37
I would suggest you take the Btrfs filesystem offline and examine it; I have been unable to reproduce the issue you are having in a VM with the same kernel version, making the same version jump during upgrade.

My best hypothesis is that bind mounting from the Btrfs filesystem is triggering some corruption check that didn't run until that point. That being said, you're saying that if you stay on the 20.10 branch Btrfs never thinks the filesystem is unhealthy?

**Comment by droans** [comment] 2023-02-02 22:54
Sorry for the confusion - no. It seemed like rolling back introduced the issue, but that's only because Docker wouldn't start on v23.

I'm going to attempt to run `btrfs scrub` from a bootable USB. 

I did have Timeshift set up to backup root and home to a different disk, but it really didn't like the idea of restoring them. I tried manually copying the Docker data directories to the root of the different drive but it ran into the same corrupted drive errors partway through. 

I'm guessing that's likely because of the corruption issues, though.

**Comment by droans** [comment] 2023-02-02 23:01
Okay, scrub goes faster than I thought. 

No errors were found at all. Side note, the second drive I referred to above is also btrfs. 

I'm at a complete loss. I'm going to attempt to copy over all the Docker data to a third drive which uses XFS.

**Comment by droans** [comment] 2023-02-03 14:11
@neersighted 

I got myself a new nVME drive and formatted the partition to XFS instead.

Some of the data for the Docker containers still appears corrupted, but I am able to at least go through my Docker logs to locate broken files and restore them from a working backup. 

My best guess is something funky happened during the install, whether due to Docker or something else, and the filesystem either didn't write certain data it thought it did or screwed up writing it. This would explain why non-Docker data was fine while databases and Plex cache was most effected - the former wasn't being touched at the time while the latter is constantly being utilized. 

I can't pretend to understand how Docker interacts with the filesystems and Docker volumes nor do I have a strong understanding on the inner workings of btrfs, so I can't speculate beyond that.

Feel free to close this issue unless you have more questions. If it occurs with someone else, I can send an image of the partition or the drive itself after scrubbing sensitive data.

**Comment by neersighted** [comment] 2023-02-03 14:21
Docker doesn't do anything special -- a volume mount is just a `mount --bind`. That is to say, the kernel is basically aliasing amount. File access happens exactly like outside of a container -- we're just poking holes in the filesystem namespace to allow access to paths outside the container root.

The fact that you had workloads running constantly is probably the most plausible explanation here. Thanks for investigating, we'll call this closed as non-reproducible/likely unrelated for now.

**Closed by neersighted** 2023-02-03 14:21 UTC
Labels: area/storage, status/0-triage, status/more-info-needed, kind/bug, version/23.0
