### ISSUE TITLE
Moby logs

### ISSUE THREAD

**Issue by saranyav-pulsesecure** [moby/moby#42118] opened 2021-03-07 04:55 UTC
whenever I'm restarting the containers I'm getting the below-mentoined logs in /var/log/docker.log
but I want to change the file into a different folder say /myapp/docker.log. So how to do that.. 

Logs:
time="2021-03-06T10:24:19.731471817Z" level=info msg="shim containerd-shim started" address="unix:///run/containerd/s/<container_id>" debug=false pid=12928
time="2021-03-06T10:24:20.512778801Z" level=info msg="shim containerd-shim started" address="unix:///run/containerd/s<containerd>" debug=false pid=13129

**Comment by thaJeztah** [comment] 2021-03-07 20:31
The docker/moby daemon itself doesn't write its logs to a file, but only writes to stdout/stderr. Assuming you're running the docker daemon with systemd, you'd have to configure systemd / journald to write it to a different location.

If you're running thorough openrc, there's an environment variable you can set; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/contrib/init/openrc/docker.confd#L6

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-03-07 20:31 UTC
Labels: kind/question

**Comment by saranyav-pulsesecure** [comment] 2021-03-08 16:57
Yaa.. got it. Thanks 
is it possible to change the log location while installing?

**Comment by thaJeztah** [comment] 2021-03-08 18:22
> is it possible to change the log location while installing?

No, no such option (as that would mean installing `<some package>` (docker in this case) would change configuration of `journald`. Not sure if that's possible at all
