### ISSUE TITLE
Dockerfile FROM Tag

### ISSUE THREAD

**Issue by vaibhav-gadgil-sp** [moby/moby#34964] opened 2017-09-25 09:42 UTC
I am creating a dockerfile for my application, which runs as a service. This application runs on a windows machine and dotnet-framework is required for this application. I am trying to start my application as a docker container on windows host machine.

I have a host machine having Windows Server 2016 installed on it. Windows server 2016 by default comes with a dotnet-framework. I have created my docker file successfully. Building docker image from dockerfile and running the container using this images is also successful.

My concern is, I am creating my dockerfile using the base image for microsoft dotnet framework.
   "FROM microsoft/dotnet-framework:latest"
Because of this base image the size of my docker image is becoming huge (around 11 GB). 

Is there any way using which I can build my docker images without using the base image for microsoft/dotnet-framework? In other words can I create my docker file without FROM tag?

**Comment by thaJeztah** [comment] 2017-09-25 10:45
> Is there any way using which I can build my docker images without using the base image for microsoft/dotnet-framework? In other words can I create my docker file without FROM tag?

No, you cannot, if your image requires the dot net framework. When building images, you build them so that they don't rely on packages available on the host (i.e., you'd be able to run an image without having to install specific (versions of) packages on the host; this is actually one of the biggest advantages of running containers: as images take care of dependency management, and make sure the environment inside the container is reproducible - users of your images don't have to prepare hosts and install packages for your application to run.

However, please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-09-25 10:45 UTC
Labels: area/builder, platform/windows
