### ISSUE TITLE
Docker inspect Template parsing error

### ISSUE THREAD

**Issue by Timunas** [moby/moby#36470] opened 2018-03-02 19:01 UTC
**Description**

Started a docker compose environment and tried to docker inspect a container and retrieve its IP Address using the command below

```docker inspect -f "{{.NetworkSettings.Networks.1scix3z5s7j_default.IPAddress}}" fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d```

After inspecting the container it seems to be everything fine in the command:

```docker inspect  fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d
[
    {
        "Id": "fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d",
        "Created": "2018-03-02T18:44:53.691288638Z",
        "Path": "nginx",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 8983,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-03-02T18:44:54.280166169Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-03-02T18:46:18.447499832Z",
                        "End": "2018-03-02T18:46:18.514554655Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   612  100   612    0     0   129k      0 --:--:-- --:--:-- --:--:--  149k\n<!DOCTYPE html>\n<html>\n<head>\n<title>Welcome to nginx!</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>Welcome to nginx!</h1>\n<p>If you see this page, the nginx web server is successfully installed and\nworking. Further configuration is required.</p>\n\n<p>For online documentation and support please refer to\n<a href=\"http://nginx.org/\">nginx.org</a>.<br/>\nCommercial support is available at\n<a href=\"http://nginx.com/\">nginx.com</a>.</p>\n\n<p><em>Thank you for using nginx.</em></p>\n</body>\n</html>\n"
                    },
                    {
                        "Start": "2018-03-02T18:46:19.521106719Z",
                        "End": "2018-03-02T18:46:19.56852869Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   612  100   612    0     0   131k      0 --:--:-- --:--:-- --:--:--  149k\n<!DOCTYPE html>\n<html>\n<head>\n<title>Welcome to nginx!</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>Welcome to nginx!</h1>\n<p>If you see this page, the nginx web server is successfully installed and\nworking. Further configuration is required.</p>\n\n<p>For online documentation and support please refer to\n<a href=\"http://nginx.org/\">nginx.org</a>.<br/>\nCommercial support is available at\n<a href=\"http://nginx.com/\">nginx.com</a>.</p>\n\n<p><em>Thank you for using nginx.</em></p>\n</body>\n</html>\n"
                    },
                    {
                        "Start": "2018-03-02T18:46:20.574852473Z",
                        "End": "2018-03-02T18:46:20.639889634Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   612  100   612    0     0   130k      0 --:--:-- --:--:-- --:--:--  149k\n<!DOCTYPE html>\n<html>\n<head>\n<title>Welcome to nginx!</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>Welcome to nginx!</h1>\n<p>If you see this page, the nginx web server is successfully installed and\nworking. Further configuration is required.</p>\n\n<p>For online documentation and support please refer to\n<a href=\"http://nginx.org/\">nginx.org</a>.<br/>\nCommercial support is available at\n<a href=\"http://nginx.com/\">nginx.com</a>.</p>\n\n<p><em>Thank you for using nginx.</em></p>\n</body>\n</html>\n"
                    },
                    {
                        "Start": "2018-03-02T18:46:21.646908503Z",
                        "End": "2018-03-02T18:46:21.712502533Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   612  100   612    0     0   936k      0 --:--:-- --:--:-- --:--:--  597k\n<!DOCTYPE html>\n<html>\n<head>\n<title>Welcome to nginx!</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>Welcome to nginx!</h1>\n<p>If you see this page, the nginx web server is successfully installed and\nworking. Further configuration is required.</p>\n\n<p>For online documentation and support please refer to\n<a href=\"http://nginx.org/\">nginx.org</a>.<br/>\nCommercial support is available at\n<a href=\"http://nginx.com/\">nginx.com</a>.</p>\n\n<p><em>Thank you for using nginx.</em></p>\n</body>\n</html>\n"
                    },
                    {
                        "Start": "2018-03-02T18:46:22.717136514Z",
                        "End": "2018-03-02T18:46:22.761222116Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   612  100   612    0     0   131k      0 --:--:-- --:--:-- --:--:--  149k\n<!DOCTYPE html>\n<html>\n<head>\n<title>Welcome to nginx!</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>Welcome to nginx!</h1>\n<p>If you see this page, the nginx web server is successfully installed and\nworking. Further configuration is required.</p>\n\n<p>For online documentation and support please refer to\n<a href=\"http://nginx.org/\">nginx.org</a>.<br/>\nCommercial support is available at\n<a href=\"http://nginx.com/\">nginx.com</a>.</p>\n\n<p><em>Thank you for using nginx.</em></p>\n</body>\n</html>\n"
                    }
                ]
            }
        },
        "Image": "sha256:e10659f9be04f937f8073d2562b3e6da1062de0ecf3624b9f71e10f44e6e9950",
        "ResolvConfPath": "/var/lib/docker/containers/fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d/hostname",
        "HostsPath": "/var/lib/docker/containers/fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d/hosts",
        "LogPath": "/var/lib/docker/containers/fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d/fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d-json.log",
        "Name": "/1scix3z5s7j_container3_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "1scix3z5s7j_default",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/6d2db268cb93a996dabbfb6fbe01732937aca7b33008da4b7f4c75fed39b992f-init/diff:/var/lib/docker/overlay2/b704af430abfd619dbfa25eaf956dee6515b67180980e856868b7e7a9720ccc9/diff:/var/lib/docker/overlay2/1341ee4ea0757b256823a1e9ecf8d861a938a8fa90680e42d78f01941fbe429e/diff:/var/lib/docker/overlay2/916580c0ba5f2ca310d223b376888ad81f8ea61a63ccf978aebfbd99b5d8f159/diff:/var/lib/docker/overlay2/ce387382ba03803190274d2679ecd9dad78db7aab9c1b37abab6f39d858017dc/diff",
                "MergedDir": "/var/lib/docker/overlay2/6d2db268cb93a996dabbfb6fbe01732937aca7b33008da4b7f4c75fed39b992f/merged",
                "UpperDir": "/var/lib/docker/overlay2/6d2db268cb93a996dabbfb6fbe01732937aca7b33008da4b7f4c75fed39b992f/diff",
                "WorkDir": "/var/lib/docker/overlay2/6d2db268cb93a996dabbfb6fbe01732937aca7b33008da4b7f4c75fed39b992f/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "fea5b383ac92",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.13.8-1~stretch",
                "NJS_VERSION=1.13.8.0.1.15-1~stretch"
            ],
            "Cmd": [
                "nginx",
                "-g",
                "daemon off;"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "curl -f http://localhost:80 || exit 1"
                ],
                "Interval": 1000000000,
                "Timeout": 5000000000
            },
            "ArgsEscaped": true,
            "Image": "1scix3z5s7j_container3",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "b31af72141b69543112684ddc1ae43f256e39100eb7fc934e02031c380417deb",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "1scix3z5s7j",
                "com.docker.compose.service": "container3",
                "com.docker.compose.version": "1.17.1",
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "1c9653b3c3d1d962b77abce813781d5c464f48f36c92c9c7751bbfb95355f021",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32917"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/1c9653b3c3d1",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "1scix3z5s7j_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "container3",
                        "fea5b383ac92"
                    ],
                    "NetworkID": "0d16d844220cfd33341f8e8195e8e161384307a79526e355497b994322cc0b61",
                    "EndpointID": "b0b17566b605d1bb02070607a0ba8f1502ef33f950bf2920d3940815825d05c5",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:03",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

But I get this error:

`Template parsing error: template: :1: bad number syntax: ".1s"`

I believe that this only happens for network names started with numbers.

**Steps to reproduce the issue:**
1. Start a docker-compose project with network name first characther equal to a number
2. Try to docker inspect the container using a GO template with the network name

**Describe the results you received:**

It gave a template parsing error

**Describe the results you expected:**
Expected to retrieve the IP Address with success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:33 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:15:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false

```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 65
Server Version: 18.02.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-36-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31GiB
Name: Laptop-749
ID: WZVE:HR5Q:3GYH:WNS6:FJCQ:TGHD:UMU5:PPWM:7Z77:QSBV:G2SW:HI77
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 47
 Goroutines: 61
 System Time: 2018-03-02T18:59:21.411842469Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-03-03 14:32
Thanks for reporting! `.NetworkSettings.Networks` is a "map", so to get individual items from that map, you need to access it by their "index" (see https://stackoverflow.com/a/26152110/1811501);

```
docker run -d --name foo nginx:alpine
```

Get all properties for the "bridge" network;

```bash
docker inspect --format '{{index .NetworkSettings.Networks "bridge"}}' foo

{<nil> [] [] 59e59cd8cbaff159b19adfcf55b2f34974afa6207be9e88319c66678e40cda67 0b622d47c6888e30b6c138d1345af7b4e766a4097f0930f696bbc68d66bc4f83 172.17.0.1 172.17.0.5 16   0 02:42:ac:11:00:05 map[]}
```

Output all properties as JSON (need to put the `index ....` part in brackets here, so that the _result_ of that action is passed to the `json` formatter);

```bash
docker inspect --format '{{json (index .NetworkSettings.Networks "bridge")}}' foo
{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"59e59cd8cbaff159b19adfcf55b2f34974afa6207be9e88319c66678e40cda67","EndpointID":"0b622d47c6888e30b6c138d1345af7b4e766a4097f0930f696bbc68d66bc4f83","Gateway":"172.17.0.1","IPAddress":"172.17.0.5","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:05","DriverOpts":null}
```

And to get just the `.IPAddress` property from the result of the `index ...`;

```bash
docker inspect --format '{{(index .NetworkSettings.Networks "bridge").IPAddress}}' foo
172.17.0.5
```

Note that this is not a bug, so I'll close this issue, but I think we could have some additional examples in the "formatting" section of the documentation; https://docs.docker.com/config/formatting/

@Timunas would you be interested in opening an issue in the documentation issue tracker (https://github.com/docker/docker.github.io/issues), or perhaps even a pull-request to add more examples (there are links on each page of the documentation that enable you to  either open an issue ("request docs changes"), or a pull request ("edit this page")

Closing, but feel free to continue the conversation, per the above 👍

**Closed by thaJeztah** 2018-03-03 14:32 UTC
Labels: platform/arm

**Comment by Timunas** [comment] 2018-03-03 16:10
Thank you for the quick reply and help. I was thinking that probably it would be a template issue. 
But didn't know where to ask for help or search for info.

I opened an issue for documentation. Thanks.

**Comment by thaJeztah** [comment] 2018-03-03 19:36
Saw the issue, thanks!
