### ISSUE TITLE
Add "tasks" to the event stream

### ISSUE THREAD

**Issue by trajano** [moby/moby#40853] opened 2020-04-23 00:38 UTC
**Description**

The /events endpoint does not have a filter for `task`.  This means to determine if a container would be ready to accept work for the service, the system needs to poll the task periodically to see if the service is running (or if had crashed).

**Steps to reproduce the issue:**

https://docs.docker.com/engine/api/v1.40/#operation/SystemEvents

**Describe the results you received:**

I did not see `type=task` as a possible filter

**Describe the results you expected:**

I expected to see `type=task` as a possible filter

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2020-04-24 06:35
This looks like a duplicate of https://github.com/moby/moby/issues/37403. There's been implementations for that in https://github.com/moby/moby/pull/37441 and https://github.com/moby/moby/pull/38214, but there's been reasons for not implementing it (see the discussion on https://github.com/moby/moby/pull/38214)


> This means to determine if a container would be ready to accept work for the service

If the service has a health check defined, I don't think traffic will be routed to the task if it's not healthy yet.

> the system needs to poll the task periodically to see if the service is running (or if had crashed).

Why would you need to do that? If a container that's backing a service crashes, swarm would already start up a new one as part of it's reconciliation loop

**Comment by thaJeztah** [comment] 2020-04-24 06:36
Let me close this issue as a duplicate of https://github.com/moby/moby/issues/37403, but feel free to continue the conversation

**Closed by thaJeztah** 2020-04-24 06:36 UTC
Labels: area/swarm, kind/enhancement
