### ISSUE TITLE
'docker login' always 'succeeds'

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [moby/moby#34084] opened 2017-07-12 19:29 UTC
**Description**

**Steps to reproduce the issue:**
1. docker login -u BadUser -p BadPwd

**Describe the results you received:**
"Login Succeeded"  always

**Describe the results you expected:**
"Login Succeeded" should be returned only when the login is authenticated against some repository, not every time.   Personally I think that if a repository is not provided, then docker login should authenticate against docker hub (https://hub.docker.com).  If I use 'docker login docker.io' then I get the behaviour I'd expect with just 'docker login'.  

If you do not wish to have the code authenticate to docker.io by default, then at the very least the "Login Succeeded" message should be changed.  You've not logged in, you've only stored credentials in ~/.docker/config.json.  The "Login Succeeded" should only be shown when an authentication completes.  If the credentials are just stored, then just say something like "Credentials recorded for later use." or something along those lines.

The current behaviour is very misleading, I thought I'd successfully logged in to docker.io when I had not.

**Additional information you deem important (e.g. issue happens only occasionally):**

It appears that the creds are always saved in the local ~/.docker/config.json, but again not being validated against docker.io (docker hub) as expected.

**Output of `docker version`:**

```
docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.x86_64
 Go version:      go1.7.6
 Git commit:      88a4867/1.12.6
 Built:           Mon Jun 19 17:26:57 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.x86_64
 Go version:      go1.7.6
 Git commit:      88a4867/1.12.6
 Built:           Mon Jun 19 17:26:57 2017
 OS/Arch:         linux/amd64

```

**Output of `docker info`:**

```
# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 15
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-50409418-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.334 GB
 Data Space Total: 107.4 GB
 Data Space Available: 17.71 GB
 Metadata Space Used: 2.236 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay bridge host null
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-682.el7.x86_64
Operating System: Employee SKU
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 1.796 GiB
Name: rhelbz.localdomain
ID: YELI:2VOK:2ZIH:RK5L:F235:OVN6:TEZX:NWLF:DKGY:5YNS:QJL6:5Y5K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: BadUser
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 127.0.0.0/8
Registries: registry.access.redhat.com (secure), docker.io (secure)

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-07-12 20:39
This is a bug in the Red Hat fork of Docker; here's on an official 1.12.6 version;

```bash
docker login -u BadUser -p BadPwd
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

Closing this, because this is not a bug in docker, but in the Red Hat fork, so not something we can fix here, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-07-12 20:39 UTC
Labels: area/distribution, version/1.12

**Comment by TomSweeneyRedHat** [comment] 2017-07-13 22:10
DOH!  Thanks for the 411, will see what we can do in that fork then.  Sorry about that, shoulda tried in latest first.

**Comment by thaJeztah** [comment] 2017-07-14 04:45
No worries, good luck debugging! :smile:
