### ISSUE TITLE
ARG is needed before it's actual usage

### ISSUE THREAD

**Issue by Antiarchitect** [moby/moby#41069] opened 2020-06-04 11:02 UTC
**Description**
Simple Dockerfile when all stages that do not depend on CACHE_IMAGE are moved on top still require ARG to be set even if it has the default value.

**Steps to reproduce the issue:**
```
FROM ruby:2.7.1 AS ruby

ARG CACHE_IMAGE=busybox:1.31.1

FROM ${CACHE_IMAGE} AS cache
```

```
export DOCKER_BUILDKIT=1
docker build . --target ruby
```

**Describe the results you received:**
```
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                 0.1s
 => => transferring dockerfile: 96B                                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                                    0.1s
 => => transferring context: 2B                                                                                                                                                                      0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: base name (${CACHE_IMAGE}) should not be blank
```

**Describe the results you expected:**
Target `ruby` builds successfully

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:14:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:44 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:                                                                                                                                                                                           [0/1948]
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 38
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.6.14-300.fc32.x86_64
 Operating System: Fedora 32 (Thirty Two)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.57GiB
 Name: localhost.localdomain
 ID: P5EM:M6NC:P7AY:35ET:CJUH:AITQ:CENP:LJB7:4IOL:ZQMC:YVJG:F7OK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: antiarchitect
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical workstation

**Comment by thaJeztah** [comment] 2020-06-04 11:08
Looks like a duplicate of https://github.com/moby/moby/issues/40830


See this comment (and the ones below that) for more details; https://github.com/moby/moby/issues/40830#issuecomment-622949605


Let me close this one as it looks like a duplicate, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-04 11:08 UTC
Labels: area/builder
