### ISSUE TITLE
why? Running Java is bad version/17.05

### ISSUE THREAD

**Issue by haqiaolong** [moby/moby#35624] opened 2017-11-28 03:29 UTC
Hello, my application is a Java, only to set up a cpuset performance, if not is to set the default host auditing, this will frequently switch CPU, lead to low performance, do you have any good solution?

**Comment by thaJeztah** [comment] 2017-11-28 03:34
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-28 03:34 UTC
