### ISSUE TITLE
Install docker 17-04CE with CURL

### ISSUE THREAD

**Issue by cristhianbicca** [moby/moby#33201] opened 2017-05-15 14:05 UTC
Install version 17-04 via curl -sSL https://get.docker.com/ | Sh is it possible?

**Comment by thaJeztah** [comment] 2017-05-15 14:58
The script at get.docker.com is intended as an "express" install method, and always installs the latest "edge" release available.

To install a specific version, follow the installation instructions for your platform/distro; https://docs.docker.com/engine/installation/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-05-15 14:58 UTC

**Comment by cristhianbicca** [comment] 2017-05-15 16:35
Yes.
