### ISSUE TITLE
The way the contents of the two containers are shared.

### ISSUE THREAD

**Issue by njuptlzf** [moby/moby#42729] opened 2021-08-10 11:31 UTC
**Description**
**Prerequisite**: The two applications are not packaged into a mirror. Start two containers, java and business using java.

1. I know that **root file system isolation is one of the principles of containers**. But I also want to ask, can I share the contents of a container through a **shared file system** without using mount? Is there a feasible theoretical basis?

2. In addition, I know that a feasible way is: the java container uses ` -v and cp` to copy java to node; the business container uses `--volumes-from` or `-v` to use java.
docker run `-v` will overwrite the content of the container with the content of the node. Is there a way to **revers** it? That is, -v realizes that the content of the container covers the content of the node. In this way we can reduce the steps of `cp`. Is there a feasible theoretical basis for this idea?

Hope you all leave a brainstorm.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2021-08-10 11:40
The usual way would be for the "java" container to expose an API, and the "business using java" to call that API. If actual _files_ need to be shared between containers (e.g., static assets), then a volume might be a good solution for that.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)
- [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-08-10 11:40 UTC
Labels: kind/question
