### ISSUE TITLE
How to migrate docker data from zfs to overlay2

### ISSUE THREAD

**Issue by rnz** [moby/moby#42321] opened 2021-04-25 09:58 UTC
I have docker swarm with many services backed on zfs storage driver with many clones/snaps. 
How to migrate all data to overlay2?

**Comment by thaJeztah** [comment] 2021-04-28 08:56
I don't think there's a way to fully "migrate" to a different storage driver and preserve the information; some information that may help (but really depends on your situation, and be sure to understand the steps, and if possible try in a testing environment first);

- make sure you have pushed image that you  have built locally to a registry
- for container that are not part of a service; generally, containers should not contain "stateful" information (which should be in volumes), but make sure you have backed up information inside containers, and know how to re-create them
- have backed up data in volumes (or are using a volume-driver plugin that uses remote storage / shared filesystem)

For nodes in a swarm cluster, you should be able to;

- (temporarily) add a new node to the cluster
- drain the node that you want to migrate (https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/)
    - when draining the node, swarm will move all swarm services that are running on the node to other nodes in the cluster
- after draining the node, you can stop the daemon on the node, configure it to use a different storage driver (probably remove existing state from `/var/lib/docker`. If you want to remove all state from `/var/lib/docker`, you may want that node to leave the swarm (`docker swarm leave`), and re-join the swarm after updating.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-04-28 08:56 UTC
Labels: area/storage, kind/question
