### ISSUE TITLE
[question] container hold a deleted file

### ISSUE THREAD

**Issue by wrfly** [moby/moby#38955] opened 2019-03-27 14:53 UTC
**Description**

After delete the file outside (in the host), the container can still get the file contants, read or write to it.

**Steps to reproduce the issue:**
1. create a text file
2. run a container and mount it with `-v /path/file.txt:/file.txt`
3. delete the file (`/path/file.txt`)
4. the container can still read or write to the "deleted file"

**Describe the results you received:**

Container still hold the file even no process are reading it.

**Describe the results you expected:**

The file mounted dispeared.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 88
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 206
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.42GiB
Name: robot
ID: SIZG:IHGP:F4V7:YIDS:GVJ4:C457:AATX:GTYG:7AV3:MSUZ:OCYN:FFGU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: wrfly
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
```

![Screenshot from 2019-03-27 22-51-50](https://user-images.githubusercontent.com/7827389/55086213-f41ec900-50e2-11e9-9c46-7baaba6f7fd4.png)

**Comment by thaJeztah** [comment] 2019-03-27 16:38
That's expected, and the way bind-mounts work; even though docker mounts the file using its name, it's actually using the files `inode`;

```bash
echo something > myfile.txt
touch mymountedfile.txt
mount --bind myfile.txt mymountedfile.txt

cat mymountedfile.txt 
something
```

Which can be seen if you use `ls -li` (first column shows the inode):


```bash
ls -li myfile.txt mymountedfile.txt
64005 -rw-r--r-- 1 root root 25 Mar 27 16:25 myfile.txt
64005 -rw-r--r-- 1 root root 25 Mar 27 16:25 mymountedfile.txt
```

After deleting the original file, the mounted version still holds on to the file's inode:


```bash
rm myfile.txt

ls -li myfile.txt mymountedfile.txt
ls: cannot access 'myfile.txt': No such file or directory
64005 -rw-r--r-- 0 root root 25 Mar 27 16:25 mymountedfile.txt
```



In general, care should be taken when bind-mounting single files, as there's some pitfalls when doing so;

- if you're using the short-hand (`-v <host-path>:<container-path>`) syntax, and the _file_ you're bind-mounting doesn't exist on the host where the daemon runs, the daemon will auto-create the host-path, and create a _directory_ with the given name (as it doesn't know if you're trying to bind-mount a directory or a host)
- when interacting with the file on the host (including _removing_ the file, as you noticed), you may run into some unexpected behaviour; another situation is (e.g.) if you try to _edit_ the file on the host; many editors do not update the file in-place, but remove the old file, and write a _new_ file in its place. In that case, the container would still see the "old" file, and not the new version with updated content.

If possible, bind-mount a _directory_ instead (in which you put the file that you need to mount inside the container), or even better, (depending on your use-case); include the file as part of your image, or  use `--config` or `--secret` when deploying services.


I'm closing this issue, because this doesn't appear to be a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-03-27 16:38 UTC
Labels: version/17.05

**Comment by wrfly** [comment] 2019-03-27 17:00
Thanks Jeztah, my question is exactly:
> After deleting the original file, the mounted version still holds on to the file's inode

And I run `sudo find / -inum <the_ori_inode>` in the system, nothing found after I deleted the host file, that's quite odd to me(I mean I cannot understand that since inside the container I can see the file, stat the file and write to the file), but where is the file?

Things different when you mount a directory, when I run `-v /host/dir:/dir`, and all the changes can be found inside the container (eg. create a new file) and even I rename the original directory. But when I delete the directory in the host, I will get an error when I try to enter the `/dir`:

![Screenshot from 2019-03-28 00-50-12](https://user-images.githubusercontent.com/7827389/55095668-7f07bf80-50f3-11e9-8378-a2ba9df3d65d.png)

![Screenshot from 2019-03-28 00-51-42](https://user-images.githubusercontent.com/7827389/55095789-b5ddd580-50f3-11e9-8579-43b283277948.png)

And when I entered that "deleted" dir, useing `lsof` in host, I got:

![Screenshot from 2019-03-28 00-54-59](https://user-images.githubusercontent.com/7827389/55096073-2e449680-50f4-11e9-95e2-db203bb9c5a5.png)

And when I leave the `/dir`, cannot find the "deleted dir" via `lsof`.

Still quite curious about what happend during this and where is the "deleted file" and "deleted dir".

Plus, since using `stat <file>`, there is only **one link** (`Links: 1`), how could it be when I delete one file and the container can still hold that, because there is no process reading or writing to the file, right?
(We can see that directory's `Links` is 2, that make sense.)

**Comment by thaJeztah** [comment] 2019-03-27 18:43
That's because the file is mounted in the container's mount namespace, and invisible on the host;

```bash
echo something > myfile.txt
docker run -d --name test -v $(pwd)/myfile.txt:/myfile.txt nginx:alpine
rm myfile.txt

mount | grep myfile.txt

# get the container's PID
docker inspect --format '{{.State.Pid}}' test
7316

# join the container's namespace, and show mounts:
nsenter --all --target=7316 /bin/sh -c 'mount | grep myfile.txt'
/dev/vda1 on /myfile.txt type ext4 (rw,relatime,data=ordered)
```

**Comment by wrfly** [comment] 2019-03-28 03:57
Wow, thanks a lot!

That's saying if I mount a file (not a directory) to a namespace, then if the namespace exists then the mounted file will never be deleted unless deleting the file inside the namespace.

And I just tried that if I delete the file, then the container will not restart successfully, daemon let me check the file exist, that's because restart causes a `unmount -> mount` operation, right?

But I still wonder where is the "deleted" file and why cannot see the file in the host but can see it in the container, because "Everything is a file" in Linux, if there is a file in container then there must be a file outside, am I right?

**Comment by wrfly** [comment] 2019-03-28 04:20
I found an excellent project about namespaces. If any have the same question with me, please see: https://github.com/teddyking/ns-process

**Comment by thaJeztah** [comment] 2019-03-28 10:09
> then if the namespace exists then the mounted file will never be deleted unless deleting the file inside the namespace.

I think the file will be gone once it's unmounted (i.e. the container is stopped/restarted)
