### ISSUE TITLE
Docker reports 'The requested compute system operation is not valid in the current state' after an executing a force 'docker rm -f ID' commands

### ISSUE THREAD

**Issue by georgyturevich** [moby/moby#37562] opened 2018-07-30 18:43 UTC
Hello,

I discovered that if we use `docker rm -f ID` then Docker reporst a vcompute error inside logs 'The requested compute system operation is not valid in the current state'
This issue can be a reason of the #37395 error. I also notice that after we see this error then `docker run` performance decreases two times (e.g from 5 to 10 seconds)

**Steps to reproduce the issue:**
1. Configure debug logging by putting `{"debug": true}` to `C:\ProgramData\docker\config\daemon.json
2. Create a script `run_many_containers.ps1` with the following content:
```
workflow Run-ManyContainersInParallel
{
  $IRange = 1..4
  while($True) { `
    foreach -parallel ($I in $IRange)
    {
      $CName = "test_iis_$I";
      $Ports = "$(11000+$I)`:80"; `
      echo "Starting $CName $(date)";
      docker run --name $CName -p $Ports -d microsoft/iis ping -t localhost;
      echo "Started $CName $(date). Sleeping ...";
      sleep 5;
      $cid = docker inspect --format "{{.Id}}" $CName
      echo "$(date): Removing $CName $cid ..."
      docker rm -f $cid
      echo "$(date): Removed $CName $cid."
    }
  } 
}

echo "Pulling the image"
docker pull microsoft/iis
 
echo "Removing containers"
docker rm -f $(docker ps -q)

Run-ManyContainersInParallel
```
3. In a first Powershell console run script `run_many_containers.ps1`
4. In a second Powershell console run following snippet
```
New-EventLog -LogName Application -Source docker
while($True) { Get-EventLog -LogName Application -Source docker -Newest 2000 | findstr /i error; Sleep 5 }
```
5. This snippet will show you the following errir after a few minutes when the `microsoft/iis` image pull completed:
```
18207 Jul 30 18:10  Information docker                          2 Result: {"Error":-1070137083,"ErrorMessage":"The requested compute system operation is not valid in the current state."}
``` 

When the script tried to remove containers I also saw following error for the `Get-ComputeProcess` cmdlet
```
PS C:\Users\georgy> Get-ComputeProcess
Get-ComputeProcess : The requested compute system operation is not valid in the current state. (Exception from
HRESULT: 0xC0370105)
At line:1 char:1
+ Get-ComputeProcess
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ComputeProcess], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.HostCompute.PowerShell.Cmdlets.Get
   ComputeProcess
```

**Describe the results you expected:**

I did not expect any vcompute errors inside debug logs

**Additional information you deem important (e.g. issue happens only occasionally):**
I was able to reproduce it on a `Standard B4ms (4 vcpus, 16 GB memory)` Azure virtual machine (Docker 17.06.2-ee-8) and `t2.xlarge (4 vcpus, 16 GB memory)` (Docker 18.03.1-ee-2)  AWS instance

### Output for `Standard B4ms (4 vcpus, 16 GB memory)` Azure virtual machine (Docker 17.06.2-ee-8)

**Output of `docker version`:**

```
Client:
 Version:       17.06.2-ee-8
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    4e8ed51
 Built: Fri Mar 30 01:37:46 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-8
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   4e8ed51
  Built:        Fri Mar 30 01:47:12 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 17.06.2-ee-8
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2312.amd64fre.rs1_release.180607-1919)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16GiB
Name: docker-win-test
ID: X2SC:ONNG:LXUX:VB3T:J47J:NJYW:SVRP:A6IH:LQM6:OMFP:IECP:MVE3
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 41
 System Time: 2018-07-30T18:37:59.5076428Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Output for `t2.xlarge (4 vcpus, 16 GB memory)` (Docker 18.03.1-ee-2)  AWS instance

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ee-2
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   ebbcd7e
 Built:        Tue Jul 10 21:32:32 2018
 OS/Arch:      windows/amd64
 Experimental: false

Server:
 Engine:
  Version:      18.03.1-ee-2
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.2
  Git commit:   ebbcd7e
  Built:        Tue Jul 10 21:49:06 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.03.1-ee-2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2395.amd64fre.rs1_release_inmarket.180714-1932)
Operating System: Windows Server 2016 Datacenter Version 1607 (OS Build 14393.2395)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16GiB
Name: EC2AMAZ-0HP94CL
ID: 4HAX:W2Y2:ZA4I:J3IV:FHRA:6DLJ:7S2R:L3BQ:4OKJ:AQ32:AWDZ:ZXEM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 44
 System Time: 2018-07-30T18:39:26.0368318Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thanks!

**Comment by georgyturevich** [comment] 2018-07-30 18:48
Hi @johnstep @jhowardmsft , I appreciate if you can have a look. I can reproduce this issue in 100% cases. Thanks!

**Comment by georgyturevich** [comment] 2018-07-31 18:14
@jhowardmsft Hi John,

By RS4 you mean Windows Server 1803 ?

We have been using Windows Server 2016 (RS1) on our servers since 2016 and have hundreds of images built for this version and used by production/QA/dev/ci containers. Probably in future we will initiate a migration of all this stuff to Windows Server 2019 but it will not be soon and will take a lot of time. So I assume we will continue use RS1 at least a few quarters (may be years) and validating of 1803 (RS4) is not very useful for us.


For my personal interest I tried to run my script on RS4. I did not see the errors from vmcompute but the following HNS error regularly (every 1-3 minute) appeared in logs
I tried this script on 
```
   67544 Jul 31 15:06  Error       docker                          1 Failed to save endpoint d150793 to store: failed to update store for object type *windows.hnsEndpoint: open C:\ProgramData\docker/network/files/local-kv.db.lock: The process cannot access the file because it is being used by another process.
```


Also I saw following errors a few times:
Cli error
```
docker : C:\Program Files\Docker\docker.exe: Error response from daemon: hcsshim::PrepareLayer failed in Win32: The device is not ready. (0x15) layerId=7eb10a1dbc5254fdfa56823558c1f6fbafbeb708d69d188278797fd78e4cde30 flavour=1.
At Run-ManyContainersInParallel:10 char:10
+
    + CategoryInfo          : NotSpecified: (C:\Program File...de30 flavour=1.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : [localhost]
```
Event log errors:
```
  79689 Jul 31 15:10  Error       docker                          1 hcsshim::PrepareLayer failed in Win32: The device is not ready. (0x15) layerId=7eb10a1dbc5254fdfa56823558c1f6fbafbeb708d69d188278797fd78e4cde30 flavour=1
   79696 Jul 31 15:10  Information docker                         12 FIXME: Got an API for which error does not match any expected type!!!: hcsshim::PrepareLayer failed in Win32: The device is not ready. (0x15) layerId=7eb10a1dbc5254fdfa56823558c1f6fbafbeb708d69d188278797fd78e4cde30 flavour=1
   79695 Jul 31 15:10  Error       docker                          1 Handler for POST /v1.37/containers/7eb10a1dbc5254fdfa56823558c1f6fbafbeb708d69d188278797fd78e4cde30/start returned error: hcsshim::PrepareLayer failed in Win32: The device is not ready. (0x15) layerId=7eb10a1dbc5254fdfa56823558c1f6fbafbeb708d69d188278797fd78e4cde30 flavour=1
```
   
Cli error 
```
   docker : C:\Program Files\Docker\docker.exe: Error response from daemon: hcsshim::PrepareLayer failed in Win32: The device is not ready. (0x15) layerId=75739ff5bf4873ad7edb5d2ffa27c85ce5052340db89099e216382cdd6358058 flavour=1.
At Run-ManyContainersInParallel:10 char:10
+
    + CategoryInfo          : NotSpecified: (C:\Program File...8058 flavour=1.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : [localhost]
```

Event log errors:
```
  222053 Jul 31 15:49  Information docker                         12 FIXME: Got an API for which error does not match any expected type!!!: hcsshim::PrepareLayer failed in Win32: The device is not ready. (0x15) layerId=75739ff5bf4873ad7edb5d2ffa27c85ce5052340db89099e216382cdd6358058 flavour=1
  222052 Jul 31 15:49  Error       docker                          1 75739ff5bf4873ad7edb5d2ffa27c85ce5052340db89099e216382cdd6358058 cleanup: failed to delete container from containerd: no such container
```

I performed my tests on t4.xlarg 4 cpus 16 Gb memory  instance. 

*`docker info` output:*

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.03.1-ee-2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter Version 1803 (OS Build 17134.165)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16GiB
Name: EC2AMAZ-SBURDP3
ID: RNFP:UDN7:DS4K:E45N:UUEY:4THV:4RBI:3CIS:AXVK:6W2M:PRLR:CTJK
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 39
 System Time: 2018-07-31T16:04:58.6042112Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thanks!

**Comment by georgyturevich** [comment] 2018-07-31 18:20
@jhowardmsft I also found that if we run containers in parallel, then stop them in paralle and then rm in parallel by following workflow, then it does not make a vmcompute error

```
workflow Run-ManyContainersInParallel
{
    $IRange = 1..12

    while($True) {
        foreach -parallel -throttlelimit 4 ($I in $IRange)
        {
          $CName = "test_iis_$I";
          $Ports = "$(11000+$I)`:80"; `
          echo "Starting $CName $(date)";
          docker run --name $CName -p $Ports -d microsoft/iis ping -t localhost;
          echo "Started $CName $(date)";
        }   
    
    
        $cids = docker ps -q --no-trunc
        foreach  -parallel -throttlelimit 4  ($cid in $cids)
        {
          echo "$(date): Stopping $cid ..."
          docker stop $cid
          echo "$(date): Stopped $cid. Sleeping ..."
        }


        foreach -parallel -throttlelimit 4 ($cid in $cids)
        {
          echo "$(date): Removing $cid ..."
          docker rm $cid
          echo "$(date): Removed $cid"
        }
    }
}
```

But if we try to stop and remove in a single block in parallel foreach then it the error appears
```
workflow Run-ManyContainersInParallel
{
    $IRange = 1..12

    while($True) {
        foreach -parallel -throttlelimit 4 ($I in $IRange)
        {
          $CName = "test_iis_$I";
          $Ports = "$(11000+$I)`:80"; `
          echo "Starting $CName $(date)";
          docker run --name $CName -p $Ports -d microsoft/iis ping -t localhost;
          echo "Started $CName $(date)";
        }   
    
    
        $cids = docker ps -q --no-trunc
        foreach  -parallel -throttlelimit 4  ($cid in $cids)
        {
          echo "$(date): Stopping $cid ..."
          docker stop $cid
          echo "$(date): Stopped $cid."
          echo "$(date): Removing $cid ..."
          docker rm $cid
          echo "$(date): Removed $cid."        
        }

    }
}
```

So, I assume that the issue is somewhere in stop/deleting a container.

Thanks!

**Comment by jhowardmsft** [comment] 2018-08-01 21:16
@georgyturevich I can answer bits and pieces here. I know you have an ongoing case with support which is the right avenue to follow. The failed to save endpoint issue is tracked by https://github.com/docker/libnetwork/issues/1950. To get a fix into EE, that would require Docker Inc. to take a fix, and re-vendor libnetwork into their codebase. (Note to my knowledge, there is no fix in libnetwork or the moby/moby repos today).

The best I can realistically do is to attempt to run your scripts against latest RS5/Windows Server 2019 builds, and the public moby/moby codebase. If I find issues there and can come up with fixes, I can point your CSS contact to fixes that need pulling into EE via Docker Inc, or in the case of platform issues, the same for trying to get backpoint platform fixes.

**Comment by jhowardmsft** [comment] 2018-08-03 17:11
The "PrepareLayer failed in Win32: The device is not ready. (0x15)" errors can be repro'd on RS5 as well. These are being investigated internally, although it doesn't seem to affect RS1.

**Comment by jhowardmsft** [comment] 2018-08-03 17:14
The RS1 "The requested compute system operation is not valid in the current state." errors are believed to be internal VSO bug 11606552. @georgyturevich - your CSS contact will probably follow up asking for additional tracing.

**Comment by jhowardmsft** [comment] 2018-08-06 16:04
Verified - the "Device is not ready" issue seen on RS4 and RS5 is a bug we are now tracking internally and the cause is known. It does not affect RS1 code.

**Comment by jhowardmsft** [comment] 2018-08-17 17:57
The remaining two issues are both platform bugs and are being worked on externally. There's no fix to moby/moby, hence closing this issue.

**Closed by jhowardmsft** 2018-08-17 17:57 UTC
Labels: area/distribution, platform/windows
