### ISSUE TITLE
Improve DX for pulling images (resumable pull)

### ISSUE THREAD

**Issue by Nefcanto** [moby/moby#48539] opened 2024-09-22 11:09 UTC
### Description

After a couple of years working with the Docker, this is what I have experienced:

1. Non-resumable part download; A part that is 700MBs goes to 650, then for some reason disconnects, then we see the retry counter, and then it starts over.
2. Non-resumable image download; An image that is 5GBs and has 20 layers (parts) would be downloaded up to 90%, then simply fails and we have no way to resume it.
3. Hanging at the last bit; A part that is 700MBs is downloaded 700MBs, but we don't see the **Extracting** message and it just hangs there forever until the entire image that is downloaded 100% fails.
4. The Internet disconnects and the image fails very soon. 
5. Image is downloaded 99%, and we see *connection reset by peer*.

These are very painful. All of these problems reduce the possibility of chaos engineering for docker.

Please address these issues. Please provide resumability at the part, and at the image level. Please provide easier more robust ways to get an image.

**Comment by thaJeztah** [comment] 2024-09-23 15:21
Thanks for opening this ticket. This is likely a (partial at least) duplicate of;

- https://github.com/moby/moby/issues/26146
- https://github.com/moby/moby/issues/20862
- https://github.com/moby/moby/issues/4872

This is a known limitation, but also one that's non-trivial to resolve for various reasons; some of those reasons are actively being worked on with the containerd image-store integration (which handles "content" (compressed layers as distributed through the registry) separate from "images"), but there's still other parts to address (cleaning up of interrupted downloads, as well as the reverse; garbage-collecting unreferenced content).

I'm closing this ticket as duplicate of the ones linked above to prevent the discussions from diverging.

**Closed by thaJeztah** 2024-09-23 15:21 UTC
Labels: area/distribution, status/0-triage, kind/feature

**Comment by Nefcanto** [comment] 2024-09-24 08:24
@thaJeztah developers were asking you to do that from 2016 and you've still not done it in 8 years? That shows the Docker's respect for the community. I realized that you will never do it. Thank you.

**Comment by Nefcanto** [comment] 2024-10-06 11:21
![docker](https://github.com/user-attachments/assets/eab72048-b1bb-4485-8794-eba9defe12ca)

**Comment by Nefcanto** [comment] 2024-10-16 06:42
![Image](https://github.com/user-attachments/assets/0e7baff2-4fcd-4eb2-9e86-d819dcd905e2)

Hangs on `84.71`. Then restarts it from 0. Then hangs. Then restarts. Annoying loop.

**Comment by Nefcanto** [comment] 2024-12-07 16:35
![Image](https://github.com/user-attachments/assets/946c555a-9495-43f3-8ed8-c6e4e72e5701)

It's so annoying. 100% downloaded and failed and starts all over again.
