### ISSUE TITLE
Cannot delete image, "no such repository"

### ISSUE THREAD

**Issue by DanielYWoo** [moby/moby#16936] opened 2015-10-12 10:31 UTC
I have three images cannot be deleted:

```
docker.io/ubuntu     14.04       d2a0ecffe6fa       3 months ago        188.3 MB
docker.io/centos     centos6    a005304e4e74    3 months ago        203.1 MB
docker.io/centos     latest        7322fbe74aa5     3 months ago        172.2 MB
```

When I try to remove them, I always get error messages like this

```
[druser@iapp04 ~]$ docker rmi -f d2a0ecffe6fa
Error response from daemon: No such repository: ubuntu
Error: failed to remove images: [d2a0ecffe6fa]
```

Environment Info

```
[druser@iapp04 ~]$ uname -a
Linux iapp04 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[druser@iapp04 ~]$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:25:19 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:25:19 UTC 2015
 OS/Arch:      linux/amd64
[druser@iapp04 ~]$ docker info
Containers: 27
Images: 69
Storage Driver: devicemapper
 Pool Name: docker-253:5-537385792-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/app029/docker-data
 Metadata file: /dev/app029/docker-md
 Data Space Used: 2.787 GB
 Data Space Total: 214.7 GB
 Data Space Available: 212 GB
 Metadata Space Used: 5.636 MB
 Metadata Space Total: 5.369 GB
 Metadata Space Available: 5.363 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 32
Total Memory: 62.65 GiB
Name: iapp04
ID: K7V7:NOTM:3E3X:4Z45:OMSE:Y2KE:OYQY:WNZU:OBRB:ZVCJ:ONWH:OXXD
WARNING: bridge-nf-call-iptables is disabled
```

**Comment by DanielYWoo** [comment] 2015-10-13 03:43
Forgot to mention, the problematic images are pulled from docker.io with 1.6.x.

**Comment by mikebrow** [comment] 2015-10-13 19:43
#investigating

**Comment by mikebrow** [comment] 2015-10-15 21:29
I've reproduced this error.  

[mbrown@MikeCentOSVM ~]$ uname -a
Linux MikeCentOSVM 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

1) install down level of docker as suggest by `centos` using the  `yum install docker`  load up few images... rmi an image checks out fine...
2) uninstall docker using `yum erase docker`  (note: I expected it to remove the repository but it did not)
3) install latest `docker-engine` using instructions https://docs.docker.com/installation/centos/#install-with-yum
4) `docker images`
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker.io/hello-world   latest              975b84d108f1        45 hours ago        960 B
docker.io/centos        latest              ce20c473cd8a        45 hours ago        172.3 MB
docker.io/ubuntu        latest              a005e6b7dd01        3 days ago          188.3 MB
5) `docker rmi -f 975b84d108f1`
Error response from daemon: No such repository: hello-world
Error: failed to remove images: [975b84d108f1]

**Comment by mikebrow** [comment] 2015-10-16 16:35
#dibs

**Comment by thaJeztah** [comment] 2023-08-07 14:09
Looks like this issue was fixed in https://github.com/moby/moby/pull/17503

**Closed by thaJeztah** 2023-08-07 14:09 UTC
Labels: status/claimed, version/1.8
