### ISSUE TITLE
How to send email when healthcheck exit with status 1

### ISSUE THREAD

**Issue by youngbloood** [moby/moby#38027] opened 2018-10-12 09:40 UTC
If i want to send a email to my email address when the healthckeck exit with status 1. How should config it.

**Comment by thaJeztah** [comment] 2018-10-19 11:35
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-10-19 11:35 UTC
Labels: kind/question

**Comment by youngbloood** [comment] 2018-10-20 02:29
Ok. Thanks for your advice.
