### ISSUE TITLE
The status viewed by docker ps and docker inspect is inconsistent

### ISSUE THREAD

**Issue by silenceper** [moby/moby#43127] opened 2022-01-06 09:01 UTC
**Description**
The process has exited, but it is still in the up state through `docker ps`, but it is in the exit state through `docker inspect`.
This task cannot be viewed through the ctr command

**Steps to reproduce the issue:**
Can't reproduce
**Describe the results you received:**

docker ps:
```
7d4705988f17        b02919968354                                                "bash /start"   10 months ago       Up 10 months                            test
```
docker inspect 
```
[
    {
        "Id": "7d4705988f178c34e6ef220b13f9a518c5f429d98e02913e81a09302f738957f",
        "Created": "2021-03-10T12:23:00.462067545Z",
        "Path": "bash",
        "Args": [
            "/start"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-03-10T12:23:00.636434891Z",
            "FinishedAt": "2021-03-11T12:16:58.105190803Z"
        },
...
```

`ctr -n moby -a /var/run/docker/containerd/containerd.sock task ls |grep 7d4705988f17` is empty

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:33:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:41:08 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 111
 Running: 89
 Paused: 0
 Stopped: 22
Images: 22
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.107
Operating System: CentOS Linux release 7.2 (Final)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.6GiB
Name: xxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine```
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2022-01-06 15:10
It looks like you're running a very old version of docker that reached EOL over three years ago. I know some fixes were included in later versions of docker around this, so I would recommend (if possible) to try if it still reproduces on current versions of docker (20.10.x at time of writing).

I'm closing this ticket for now, as this version of Docker reached EOL and is no longer supported, but feel free to open a ticket if you have ways to reproduce the issue on current versions.

**Closed by thaJeztah** 2022-01-06 15:10 UTC
Labels: version/18.06
