### ISSUE TITLE
error creating overlay failed to mount overlay: permission denied

### ISSUE THREAD

**Issue by m2khosravi** [moby/moby#40904] opened 2020-05-05 05:56 UTC
Hello, I wanna change docker storage drive to overlay2 for use Kubernetes

daemon.json :
```
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
```
but the service cannot start
```
journalctl -b -u docker.service:

level=error msg="failed to mount overlay: permission denied" storage-drive
May 05 05:35:32 master1 dockerd[492]: failed to start daemon: error initializing graphdriver: driver not supported
```

**Comment by thaJeztah** [comment] 2020-05-07 10:03
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because of the above, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-05-07 10:03 UTC
Labels: area/storage/overlay, status/more-info-needed
