### ISSUE TITLE
Pulling from local registry can full pull from a remote one

### ISSUE THREAD

**Issue by krojew** [moby/moby#36953] opened 2018-04-26 10:22 UTC
**Description**

I have an image which is pushed to both local running registry (registry:2) and a remote one. When I pull the image on a fresh Docker installation from the local registry, and then do a pull again from the remote one, I expect nothing to be pulled on the second attempt. Instead, docker happily pulls the same layers again.

**Steps to reproduce the issue:**
1. Push an image to local registry and a remote one.
2. Clear all docker data.
3. Pull from the local registry.
4. Pull from the remote one.

**Describe the results you received:**

Docker pulls all layers from both registries.

**Describe the results you expected:**

Docker only pulls from the local one, and doesn't pull anything the second time, since the layers are already there.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:09 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:36 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-39-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.82GiB
Name: krojew-ThinkPad-P50
ID: KA6M:X62Y:AOSG:4ACH:U3AE:BORB:NWL5:DSDY:5PPG:Y5AG:YXMP:EO5Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: krojew
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical machine

**Comment by remeika** [comment] 2019-10-04 03:13
I was unable to reproduce this issue using Docker version `19.03.2`. Here are the steps to took to attempt to repro:

Run a local docker registry:

```shell
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
89800dec0c41e39d111fcce3d79435b80a3aabe82804b0c997a6a4d17fe7d8ad
```

Download any old image:

```shell
$ docker pull ubuntu:16.04
16.04: Pulling from library/ubuntu
16c48d79e9cc: Pull complete 
3c654ad3ed7d: Pull complete 
6276f4f9c29d: Pull complete 
a4bd43ad48ce: Pull complete 
Digest: sha256:6239ca16d54d8edd38788aacde7c6426e5999ffbbd7e97ac3cf04d474341d079
Status: Downloaded newer image for ubuntu:16.04
docker.io/library/ubuntu:16.04
```

Push to my local repo:

```shell
$ docker tag  ubuntu:16.04 localhost:5000/my-ubuntu
$ docker push localhost:5000/my-ubuntu
The push refers to repository [localhost:5000/my-ubuntu]
9acfe225486b: Pushed 
90109bbe5b76: Pushed 
cb81b9d8a6c9: Pushed 
ea69392465ad: Pushed 
latest: digest: sha256:c0ae44d97c088026f44b1a4ef9da06d3fa8e771b95d95bffbcbddea6d1e450b7 size: 1150
```

Push it to a remote:

```shell
$ docker push remeika/test:16.04
The push refers to repository [docker.io/remeika/test]
9acfe225486b: Mounted from library/ubuntu 
90109bbe5b76: Mounted from library/ubuntu 
cb81b9d8a6c9: Mounted from library/ubuntu 
ea69392465ad: Mounted from library/ubuntu 
16.04: digest: sha256:c0ae44d97c088026f44b1a4ef9da06d3fa8e771b95d95bffbcbddea6d1e450b7 size: 1150
```

Delete the image locally:

```shell
$ docker image remove ubuntu:16.04
Untagged: ubuntu:16.04
Untagged: ubuntu@sha256:6239ca16d54d8edd38788aacde7c6426e5999ffbbd7e97ac3cf04d474341d079
$ docker image remove localhost:5000/my-ubuntu
Untagged: localhost:5000/my-ubuntu:latest
Untagged: localhost:5000/my-ubuntu@sha256:c0ae44d97c088026f44b1a4ef9da06d3fa8e771b95d95bffbcbddea6d1e450b7
$ docker image remove remeika/test:16.04
Untagged: remeika/test:16.04
Untagged: remeika/test@sha256:c0ae44d97c088026f44b1a4ef9da06d3fa8e771b95d95bffbcbddea6d1e450b7
Deleted: sha256:657d80a6401dd332f0ba86438f3b10270b4bfb082fe26986ce82062bc2527b49
Deleted: sha256:c1d1d9da605b9e8df0daa35dfb5ddef3ea2b452574137fbb425f43bee509568c
Deleted: sha256:60db3f0c5d2057f1ca71270cc137c60313f74ae466a7765e12b6a88ba82023fc
Deleted: sha256:d912b5e4480d3517f2ef887b11aa5cd0cc29c5671423ade238d8540c139cb98e
Deleted: sha256:ea69392465ad72ace1216ca2f49a372c7d6f10ec031ab53a94a17699c9ab4185
```

Pull from local:

```shell
$ docker pull localhost:5000/my-ubuntu
Using default tag: latest
latest: Pulling from my-ubuntu
16c48d79e9cc: Pull complete 
3c654ad3ed7d: Pull complete 
6276f4f9c29d: Pull complete 
a4bd43ad48ce: Pull complete 
Digest: sha256:c0ae44d97c088026f44b1a4ef9da06d3fa8e771b95d95bffbcbddea6d1e450b7
Status: Downloaded newer image for localhost:5000/my-ubuntu:latest
localhost:5000/my-ubuntu:latest
```

Pull from remote. **This operation respected the existing layers downloaded from the local repo**:

```shell
$ docker pull remeika/test:16.04
16.04: Pulling from remeika/test
Digest: sha256:c0ae44d97c088026f44b1a4ef9da06d3fa8e771b95d95bffbcbddea6d1e450b7
Status: Downloaded newer image for remeika/test:16.04
docker.io/remeika/test:16.04
```

@krojew Can you please verify whether you still see this behavior using docker engine 19?

**Comment by thaJeztah** [comment] 2019-11-03 10:25
let me close this one

**Closed by thaJeztah** 2019-11-03 10:25 UTC
Labels: area/distribution, kind/question, version/18.03
