### ISSUE TITLE
docker filesystems - problems with deleting files

### ISSUE THREAD

**Issue by kaniapm** [moby/moby#25731] opened 2016-08-15 21:25 UTC
**Output of `docker version`:**

Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 92
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-93-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54 GiB
Name: elx7422cj3f
ID: 7AOI:FPDV:PKOM:BLNC:EJSA:J37R:F2BR:6ICJ:KKTS:5NX7:2MQS:WYQG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: kaniapm
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

$ uname -a
Linux elx7422cj3f 3.13.0-93-generic #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I have two Dockerfiles. In every Dockerfile I create temporary directory /tmp/docker-cache, copy a file and at the end I remove this temporary directory (with all the content).
However if one of my Dockerfiles is build base on another Dockerfiles, remove of directory does not remove anything and also does not fail. 

See output from first build:

```
docker build -t ekanpio/base --no-cache .
Sending build context to Docker daemon 3.584 kB
Step 1 : FROM centos
 ---> 970633036444
Step 2 : ARG JDK_FILENAME=jdk-8u101-linux-x64.rpm
 ---> Running in a87b4c561992
 ---> 1665650c43c8
Removing intermediate container a87b4c561992
Step 3 : ARG JDK_RPM_URL=http://download.oracle.com/otn-pub/java/jdk/8u101-b13/$JDK_FILENAME
 ---> Running in 0caa5b466fd5
 ---> 5e47e3c6b501
Removing intermediate container 0caa5b466fd5
Step 4 : ARG JDK_DIR=/usr/java/jdk1.8.0_101
 ---> Running in b08dce362a41
 ---> 0c7159514a2c
Removing intermediate container b08dce362a41
Step 5 : RUN mkdir /tmp/docker-cache
 ---> Running in d5080ee53f64
 ---> c82d6728aa4e
Removing intermediate container d5080ee53f64
Step 6 : RUN curl -s -kLb "oraclelicense=a" $JDK_RPM_URL --output /tmp/docker-cache/$JDK_FILENAME
 ---> Running in c655cff4fd36
 ---> 7d3fcef40e30
Removing intermediate container c655cff4fd36
Step 7 : RUN rpm -i /tmp/docker-cache/$JDK_FILENAME
 ---> Running in 3f1125713e74
Unpacking JAR files...
    tools.jar...
    plugin.jar...
    javaws.jar...
    deploy.jar...
    rt.jar...
    jsse.jar...
    charsets.jar...
    localedata.jar...
 ---> 65d93ea7c47e
Removing intermediate container 3f1125713e74
Step 8 : RUN rm -rf                                          $JDK_DIR/*src.zip                               $JDK_DIR/lib/missioncontrol                     $JDK_DIR/lib/visualvm                           $JDK_DIR/lib/*javafx*                           $JDK_DIR/jre/lib/plugin.jar                     $JDK_DIR/jre/lib/ext/jfxrt.jar                  $JDK_DIR/jre/bin/javaws                         $JDK_DIR/jre/lib/javaws.jar                     $JDK_DIR/jre/lib/desktop                        $JDK_DIR/jre/plugin                             $JDK_DIR/jre/lib/deploy*                        $JDK_DIR/jre/lib/*javafx*                       $JDK_DIR/jre/lib/*jfx*                          $JDK_DIR/jre/lib/amd64/libdecora_sse.so         $JDK_DIR/jre/lib/amd64/libprism_*.so            $JDK_DIR/jre/lib/amd64/libfxplugins.so          $JDK_DIR/jre/lib/amd64/libglass.so              $JDK_DIR/jre/lib/amd64/libgstreamer-lite.so     $JDK_DIR/jre/lib/amd64/libjavafx*.so            $JDK_DIR/jre/lib/amd64/libjfx*.so
 ---> Running in 5c9ea8679c8d
 ---> 8567e2cdebc4
Removing intermediate container 5c9ea8679c8d
Step 9 : RUN rm -rf /tmp/docker-cache
 ---> Running in 8e6ae8fa6a56
 ---> 59fe9b17a623
Removing intermediate container 8e6ae8fa6a56
Step 10 : RUN ls -al /tmp
 ---> Running in ef91b5b24c58
total 32
drwxrwxrwt  9 root root 4096 Aug 15 17:05 .
drwxr-xr-x 32 root root 4096 Aug 15 17:05 ..
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .ICE-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .Test-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .X11-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .XIM-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .font-unix
-rwx------  1 root root  827 Jul 29 14:05 ks-script-6A9C2c
 ---> 8136a27b50e3
Removing intermediate container ef91b5b24c58
Successfully built f9e7536c5ff2
```

Remove of directory /tmp/docker-cache works fine (Step 9). Next command is not listing docker-cache directory which is correct (Step 10).

However the build of next image based on the previous one fails:

```
docker build -t ekanpio/app --no-cache .
Sending build context to Docker daemon   260 MB
Step 1 : FROM ekanpio/base
 ---> f9e7536c5ff2
Step 2 : RUN ls -al /tmp
 ---> Running in 9f11eec1ce4a
total 32
drwxrwxrwt  9 root root 4096 Aug 15 17:05 .
drwxr-xr-x 32 root root 4096 Aug 15 17:12 ..
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .ICE-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .Test-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .X11-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .XIM-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .font-unix
-rwx------  1 root root  827 Jul 29 14:05 ks-script-6A9C2c
 ---> cbf317fc0b49
Removing intermediate container 9f11eec1ce4a
Step 3 : RUN mkdir /tmp/docker-cache
 ---> Running in 30fd020a6ca2
 ---> 33c0e1367ed7
Removing intermediate container 30fd020a6ca2
Step 4 : COPY dependencies/jboss-as-dist.zip /tmp/docker-cache/
 ---> 309c062bd4bf
Removing intermediate container aa8354203e4c
Step 5 : RUN rm -rf /tmp/docker-cache
 ---> Running in 7292ca7f1e71
 ---> 8b29092e4d6e
Removing intermediate container 7292ca7f1e71
Step 6 : RUN ls -al /tmp/docker-cache
 ---> Running in 2ca74bf67bdf
total 253908
drwxr-xr-x  2 root root      4096 Aug 15 17:12 .
drwxrwxrwt 11 root root      4096 Aug 15 17:12 ..
-rw-r--r--  1 root root 259992826 Aug 15 16:26 jboss-as-dist.zip
 ---> 2895be7b4b00
Removing intermediate container 2ca74bf67bdf
Step 7 : RUN ls -al /tmp/
 ---> Running in 5ff50f55d491
total 36
drwxrwxrwt 11 root root 4096 Aug 15 17:12 .
drwxr-xr-x 35 root root 4096 Aug 15 17:12 ..
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .ICE-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .Test-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .X11-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .XIM-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .font-unix
drwxr-xr-x  2 root root 4096 Aug 15 17:12 docker-cache
-rwx------  1 root root  827 Jul 29 14:05 ks-script-6A9C2c
 ---> f7c9f2668716
Removing intermediate container 5ff50f55d491
Successfully built f7c9f2668716
```

As you see remove directory run fine (Step 5) but this directory is still listed by the next command (Step 6).

If I modify the second Dockerfile to be based on centos it works as expected.

```
docker build -t ekanpio/app --no-cache .
Sending build context to Docker daemon   260 MB
Step 1 : FROM centos
 ---> 970633036444
Step 2 : RUN ls -al /tmp
 ---> Running in 0c73da85a475
total 32
drwxrwxrwt  7 root root 4096 Jul 29 14:05 .
drwxr-xr-x 22 root root 4096 Aug 15 17:11 ..
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .ICE-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .Test-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .X11-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .XIM-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .font-unix
-rwx------  1 root root  827 Jul 29 14:05 ks-script-6A9C2c
 ---> 3df37a849b35
Removing intermediate container 0c73da85a475
Step 3 : RUN mkdir /tmp/docker-cache
 ---> Running in f8e6ce1ddd4a
 ---> ffa6f35d012d
Removing intermediate container f8e6ce1ddd4a
Step 4 : COPY dependencies/jboss-as-dist.zip /tmp/docker-cache/
 ---> f1ff4ec1ac16
Removing intermediate container f04c8f6fc2a7
Step 5 : RUN rm -rf /tmp/docker-cache
 ---> Running in c7042179cc1b
 ---> a092b36479ab
Removing intermediate container c7042179cc1b
Step 6 : RUN ls -al /tmp/docker-cache
 ---> Running in fe6b13bab57e
ls: cannot access /tmp/docker-cache: No such file or directory
The command '/bin/sh -c ls -al /tmp/docker-cache' returned a non-zero code: 2
```

The step 6 fails because the directory /tmp/docker-cache was removed as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

Even more strange thing can be observed if I run the second image:

```
docker run -t -i --rm ekanpio/app /bin/bash
[root@f8d274ecec7f /]# ls -al /tmp/docker-cache/
total 253912
drwxr-xr-x  2 root root      4096 Aug 15 17:12 .
drwxrwxrwt 11 root root      4096 Aug 15 17:12 ..
-rw-r--r--  1 root root 259992826 Aug 15 16:26 jboss-as-dist.zip
[root@f8d274ecec7f /]# rm /tmp/docker-cache/jboss-as-dist.zip 
rm: remove regular file '/tmp/docker-cache/jboss-as-dist.zip'? y
[root@f8d274ecec7f /]# ls -al /tmp/docker-cache/
total 8
drwxr-xr-x  2 root root 4096 Aug 15 21:18 .
drwxrwxrwt 12 root root 4096 Aug 15 21:18 ..
[root@f8d274ecec7f /]# rm -rf /tmp/docker-cache/
[root@f8d274ecec7f /]# ls -al /tmp/
total 36
drwxrwxrwt 11 root root 4096 Aug 15 21:19 .
drwxr-xr-x 36 root root 4096 Aug 15 21:18 ..
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .ICE-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .Test-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .X11-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .XIM-unix
drwxrwxrwt  2 root root 4096 Jul 29 14:04 .font-unix
drwxr-xr-x  2 root root 4096 Aug 15 17:12 docker-cache
-rwx------  1 root root  827 Jul 29 14:05 ks-script-6A9C2c
[root@f8d274ecec7f /]# ls -al /tmp/docker-cache/
total 253912
drwxr-xr-x  2 root root      4096 Aug 15 17:12 .
drwxrwxrwt 11 root root      4096 Aug 15 21:19 ..
-rw-r--r--  1 root root 259992826 Aug 15 16:26 jboss-as-dist.zip
[root@f8d274ecec7f /]# 
```

If I issue command rm /tmp/docker-cache/jboss-as-dist.zip the file is being removed as expected.
If I remove the whole directory then removed previously file appears again as a phoenix from the ashes.

**Comment by thaJeztah** [comment] 2016-08-16 00:08
You mentioned that it works if you use a different base image; is it possible that your `ekanpio/app` base image has a `VOLUME` defined?

If not, then possibly this could be an issue with "whiteout" files (in the layered filesystems, such as aufs, that docker uses, removing a file basically *writes* a file that says "this file is no longer there". (see, for example https://github.com/docker/docker/issues/9093)

**Comment by kaniapm** [comment] 2016-08-16 08:04
I do not define any `VOLUME` on my image.
This is my base Dockerfile - https://gist.github.com/kaniapm/bb70e3bda4004a9cde10dd0d29eb2c0b
and my app Dockerfile - https://gist.github.com/kaniapm/8b92e0ee8a2af7adcafad06762399cba

**Comment by thaJeztah** [comment] 2016-08-16 08:08
@kaniapm thanks, that's useful

**Comment by robinsmidsrod** [comment] 2017-06-21 16:11
I'm having this same issue with a Dockerfile I'm trying to build. The issue is completely consistent, and it seems to be related to deleting folders, not files. If I have folder a with file b inside it, I can delete file b and it goes away. When I then try delete folder a I get no error, folder a continue to exist and file b inside folder a has reappeared. I'm doing this as a non-root user inside the container, and this happens after having set USER <username> and SHELL to [ "/bin/bash", "--login", "-c" ].

Any ideas how to debug this?

**Comment by thaJeztah** [comment] 2017-06-21 22:44
@robinsmidsrod can you add the output of `docker version` and `docker info`, and a minimal Dockerfile to reproduce?

**Comment by thaJeztah** [comment] 2017-06-21 23:55
I see I never replied to the original issue; I simplified the steps to this;

```bash
$ docker build --no-cache -t repro-25731 -<<EOF
FROM busybox
RUN ls -l /tmp
RUN mkdir /tmp/docker-cache
RUN rm -rf /tmp/docker-cache
RUN ls -l /tmp
RUN mkdir /tmp/docker-cache
RUN echo "foo" > /tmp/docker-cache/jboss-as-dist.zip
RUN rm -rf /tmp/docker-cache
RUN ls -l /tmp/docker-cache
RUN ls -l /tmp/
EOF
```

Testing this on Docker 17.05, running Ubuntu 14.04 with a 4.4 kernel;

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
 
```
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 47
 Server Version: 17.05.0-ce
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 33
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
 runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
 init version: 949e6fa
 Security Options:
  apparmor
 Kernel Version: 4.4.0-78-generic
 Operating System: Ubuntu 14.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 992.5MiB
 Name: ubuntu-1gb-sfo2-01
 ID: P6UI:NP22:M5S6:ZXVQ:42ME:JY5G:PM4M:RQZU:VBMW:HNPC:5TAG:VTCF
 Docker Root Dir: /var/lib/docker
 Debug Mode (client): false
 Debug Mode (server): false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

 WARNING: No swap limit support
```

The build works as expected; the build successfully removes the `/tmp/docker-cache` directory (causing the error in the build-step);

```
Sending build context to Docker daemon  2.048kB
Step 1/10 : FROM busybox
 ---> c30178c5239f
Step 2/10 : RUN ls -l /tmp
 ---> Running in 5c3562f416fa
total 0
 ---> f38c5910d6e0
Removing intermediate container 5c3562f416fa
Step 3/10 : RUN mkdir /tmp/docker-cache
 ---> Running in 577c28263536
 ---> 9e7c39740f69
Removing intermediate container 577c28263536
Step 4/10 : RUN rm -rf /tmp/docker-cache
 ---> Running in d51168543e24
 ---> a2f53b23ae5f
Removing intermediate container d51168543e24
Step 5/10 : RUN ls -l /tmp
 ---> Running in e2773b52650e
total 0
 ---> 6bc1cb7e0310
Removing intermediate container e2773b52650e
Step 6/10 : RUN mkdir /tmp/docker-cache
 ---> Running in c02eb076409e
 ---> e2b09ce33168
Removing intermediate container c02eb076409e
Step 7/10 : RUN echo "foo" > /tmp/docker-cache/jboss-as-dist.zip
 ---> Running in b02435828eda
 ---> 48313e2a9817
Removing intermediate container b02435828eda
Step 8/10 : RUN rm -rf /tmp/docker-cache
 ---> Running in f23c47418e2a
 ---> f713670e65f9
Removing intermediate container f23c47418e2a
Step 9/10 : RUN ls -l /tmp/docker-cache
 ---> Running in 04b6b8e9a3f0
ls: /tmp/docker-cache: No such file or directory
The command '/bin/sh -c ls -l /tmp/docker-cache' returned a non-zero code: 1
```

_However_, doing the same steps on _exactly_ the same Docker version, but on Ubuntu 14.04 on a 3.13 kernel (I notice it doesn't have `Dirperm1` support, which is the case for older aufs versions);

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 17.05.0-ce
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 0
  Dirperm1 Supported: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
 runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
 init version: 949e6fa
 Security Options:
  apparmor
 Kernel Version: 3.13.0-121-generic
 Operating System: Ubuntu 14.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 993.9MiB
 Name: ubuntu-1gb-sfo2-01
 ID: NY3I:BHKM:WDPG:K7XJ:K4LG:4Y67:PFCA:73MW:GVFE:TZR3:T647:BHEA
 Docker Root Dir: /var/lib/docker
 Debug Mode (client): false
 Debug Mode (server): false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

 WARNING: No swap limit support
```
 
The result of building the app image is different;
 
```
Sending build context to Docker daemon  2.048kB
Step 1/10 : FROM busybox
 ---> c30178c5239f
Step 2/10 : RUN ls -l /tmp
 ---> Running in 892a4ed11395
total 0
 ---> b34926fd7354
Removing intermediate container 892a4ed11395
Step 3/10 : RUN mkdir /tmp/docker-cache
 ---> Running in f73315f8685f
 ---> 0186fb1b873d
Removing intermediate container f73315f8685f
Step 4/10 : RUN rm -rf /tmp/docker-cache
 ---> Running in 72938f37800b
 ---> 70449deda8c0
Removing intermediate container 72938f37800b
Step 5/10 : RUN ls -l /tmp
 ---> Running in f52a15163844
total 0
 ---> 3da867af02ff
Removing intermediate container f52a15163844
Step 6/10 : RUN mkdir /tmp/docker-cache
 ---> Running in 4b53bd9811a0
 ---> 1e0bf978ba60
Removing intermediate container 4b53bd9811a0
Step 7/10 : RUN echo "foo" > /tmp/docker-cache/jboss-as-dist.zip
 ---> Running in 07377f4b20d9
 ---> 67f675a3eab7
Removing intermediate container 07377f4b20d9
Step 8/10 : RUN rm -rf /tmp/docker-cache
 ---> Running in 8d3a776cfba4
 ---> e295bfd66ca3
Removing intermediate container 8d3a776cfba4
Step 9/10 : RUN ls -l /tmp/docker-cache
 ---> Running in 5ffb7c6269f4
total 4
-rw-r--r--    1 root     root             4 Jun 21 23:50 jboss-as-dist.zip
 ---> e615562c91fb
Removing intermediate container 5ffb7c6269f4
Step 10/10 : RUN ls -l /tmp/
 ---> Running in ecc50409efb9
total 4
drwxr-xr-x    2 root     root          4096 Jun 21 23:50 docker-cache
 ---> bbbc579574e8
Removing intermediate container ecc50409efb9
Successfully built bbbc579574e8
Successfully tagged repro-25731:latest
```
 
The directory is indeed not removed

**Comment by thaJeztah** [comment] 2017-06-22 01:18
Debugging this issue with @tonistiigi, and this looks to be a bug in the `aufs` kernel module in Ubuntu (the 3.13 kernel); we are able to reproduce this outside of docker;

Steps to reproduce;

```
mkdir -p repro-25731 && cd repro-25731

mkdir -p l0/tmp
mkdir -p l1/tmp/docker-cache
mkdir -p l2/tmp
touch l2/tmp/.wh.b
mkdir -p l3/tmp/docker-cache
mkdir -p l4/tmp/docker-cache
echo bar> l4/tmp/docker-cache/jboss-as-dist.zip
mkdir l5
mkdir merged
mount -t aufs -o br=l5=rw:l4=ro+wh:l3=ro+wh:l2=ro+wh:l1=ro+wh:l0=ro+wh none merged

rm -rf merged/tmp/docker-cache
ls -la l5/tmp
umount merged
```

On the 4.40 kernel, a whiteout file is created in `l5/tmp`; therefore, the directory is not showing up ("it is deleted").

On the 3.13 kernel on the other hand, the whiteout file is not created when removing the directory;

```bash
$ mkdir repro-25731 && cd repro-25731
$ mkdir -p l0/tmp
$ mkdir -p l1/tmp/docker-cache
$ mkdir -p l2/tmp
$ touch l2/tmp/.wh.b
$ mkdir -p l3/tmp/docker-cache
$ mkdir -p l4/tmp/docker-cache
$ echo bar> l4/tmp/docker-cache/jboss-as-dist.zip
$ mkdir l5
$ mkdir merged
$ mount -t aufs -o br=l5=rw:l4=ro+wh:l3=ro+wh:l2=ro+wh:l1=ro+wh:l0=ro+wh none merged
$
$ rm -rf merged/tmp/docker-cache
$ ls -la l5/tmp
total 8
drwxr-xr-x 2 root root 4096 Jun 22 01:07 .
drwxr-xr-x 5 root root 4096 Jun 22 01:07 ..
```

**Comment by thaJeztah** [comment] 2017-06-22 01:41
versions of `aufs` on both;

3.13 kernel;

```
filename:       /lib/modules/3.13.0-121-generic/kernel/ubuntu/aufs/aufs.ko
alias:          fs-aufs
version:        3.13-20140303
description:    aufs -- Advanced multi layered unification filesystem
author:         Junjiro R. Okajima <aufs-users@lists.sourceforge.net>
license:        GPL
srcversion:     C49AD67DE7CBA62B47D8AD0
depends:
intree:         Y
vermagic:       3.13.0-121-generic SMP mod_unload modversions
signer:         Magrathea: Glacier signing key
sig_key:        C4:E2:50:F6:9A:26:06:B1:27:88:41:A1:0F:28:4E:B9:1F:D5:61:22
sig_hashalgo:   sha512
parm:           brs:use <sysfs>/fs/aufs/si_*/brN (int)
```

4.40 kernel;

```
modinfo aufs
filename:       /lib/modules/4.4.0-78-generic/kernel/fs/aufs/aufs.ko
alias:          fs-aufs
version:        4.x-rcN-20160111
description:    aufs -- Advanced multi layered unification filesystem
author:         Junjiro R. Okajima <aufs-users@lists.sourceforge.net>
license:        GPL
srcversion:     BD1C47D04FE5C2D88F63AAB
depends:
intree:         Y
vermagic:       4.4.0-78-generic SMP mod_unload modversions
parm:           brs:use <sysfs>/fs/aufs/si_*/brN (int)
parm:           allow_userns:allow unprivileged to mount under userns (bool)
```

**Comment by thaJeztah** [comment] 2017-06-22 01:59
@sfjro do you know if there's a fix for this in a more recent 3.x aufs version (so that we could ask ubuntu to update / cherry-pick the fix)?

@kaniapm if possible, I would recommend upgrading to one of the more recent Ubuntu kernels, but I understand this may not be possible in your situation.

**Comment by sfjro** [comment] 2017-06-22 02:21
Hello Sebastiaan,

Sebastiaan van Stijn:
> @sfjro do you know if there's a fix for this in a more recent 3.x aufs version (so that we could ask ubuntu to update / cherry-pick the fix)?

I've read https://github.com/moby/moby/issues/25731 now.
As you might know, aufs3 for linux-v3.14...v3.17 were unsupported since
Oct 2015. So my first reaction is simply "upgrade your system."  But I
may be able to help if you really want it. Provide me these info.

(from aufs README file)
----------------------------------------
When you have any problems or strange behaviour in aufs, please let me
know with:
- /proc/mounts (instead of the output of mount(8))
- /sys/module/aufs/*
- /sys/fs/aufs/* (if you have them)
- /debug/aufs/* (if you have them)
- linux kernel version
  if your kernel is not plain, for example modified by distributor,
  the url where i can download its source is necessary too.
- aufs version which was printed at loading the module or booting the
  system, instead of the date you downloaded.
- configuration (define/undefine CONFIG_AUFS_xxx)
- kernel configuration or /proc/config.gz (if you have it)
- behaviour which you think to be incorrect
- actual operation, reproducible one is better
- mailto: aufs-users at lists.sourceforge.net

Usually, I don't watch the Public Areas(Bugs, Support Requests, Patches,
and Feature Requests) on SourceForge. Please join and write to
aufs-users ML.
----------------------------------------

Last but not least, keep in mind that I am not a docker developer.


J. R. Okajima

**Comment by thaJeztah** [comment] 2017-06-22 04:24
Thanks @sfjro I'll have a look at obtaining that information; I realise that version of aufs is quite outdated; it looks to be the version that's shipped with Ubuntu 14.04, which is an LTS release. This complicates things a bit (i.e., we try to avoid telling users to install a "custom" aufs version instead of the package that's shipping with their distro), but if we're able to find the patch that needs to be applied, possibly the Ubuntu kernel maintainers are willing to ship that patch with an upcoming kernel update.

**Comment by robinsmidsrod** [comment] 2017-06-22 19:42
@thaJeztah I am indeed running Ubuntu 14.04 with a 3.13 kernel, so it seems like my issue is exactly what you've described. You mentioned that a 4.4 kernel fixed the issue. Is there a 4.4 kernel package available for Ubuntu 14.04 that is easily installed without a lot of hocus pocus?

**Comment by thaJeztah** [comment] 2017-06-22 23:57
@robinsmidsrod I think a fresh installation of Ubuntu 14.04.5 will now by default use kernel 4.40 (see https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes). A quick Google search gave me this answer to upgrade the kernel to use the "xenial" (Ubuntu 16.04) kernel; https://askubuntu.com/a/753372

**Comment by thaJeztah** [comment] 2023-04-20 23:59
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS

**Closed by thaJeztah** 2023-04-20 23:59 UTC
Labels: area/storage/aufs, area/kernel, kind/bug, version/1.12
