### ISSUE TITLE
Cannot run any image in windows insider server 1709 16278

### ISSUE THREAD

**Issue by isanych** [moby/moby#35462] opened 2017-11-10 11:39 UTC
docker run with any windows image produce _The operating system of the container does not match the operating system of the host_ error
```
>docker run --rm microsoft/nanoserver:1709
docker: Error response from daemon: container 328b4c258cd92c95f8292166c057285d2f2c00bd6b63dea224e7af172f1f9d83 encountered an error during CreateContainer: failure in a Windows system call: The operating system of the container does not match the operating system of the host. (0xc0370101) extra info: {"SystemType":"Container","Name":"328b4c258cd92c95f8292166c057285d2f2c00bd6b63dea224e7af172f1f9d83","Owner":"docker","VolumePath":"\\\\?\\Volume{128ee33b-89d0-4280-8cb0-b84ea076eead}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\328b4c258cd92c95f8292166c057285d2f2c00bd6b63dea224e7af172f1f9d83","Layers":[{"ID":"7541bb32-0440-51ec-aa3e-247ff32e14c","Path":"C:\\ProgramData\\docker\\windowsfilter\\ea999e6af4850485b00ffdaa3fea978bb5f89f1c31459e557badf47b173a3bfc"},{"ID":"fe099182-58a0-5ca3-a4ab-354d3162d59c","Path":"C:\\ProgramData\\docker\\windowsfilter\\21c302de2e86aad67ca2bda5963a76424c691ec049889953975f77988e5379aa"}],"HostName":"328b4c258cd9","HvPartition":false,"EndpointList":["81b586e4-c841-47ee-9f7b-bade58ee67b7"],"AllowUnqualifiedDNSQuery":true}.
```

**Description**

I'm getting this error with any container (including microsoft/nanoserver and microsoft/nanoserver:1709) and with any docker version I tried:

- EE stable
- EE preview
- CE 17.09
- latest binaries from https://master.dockerproject.org/windows/x86_64/dockerd.exe

**Steps to reproduce the issue:**
1. Install Windows Insider Server 1709 https://blogs.windows.com/windowsexperience/2017/09/05/announcing-windows-server-insider-preview-build-16278/ (I'm not aware about other free ways to get Server 1709)
2. Install any docker
3. Run any image

**Output of `docker version`:**

```
Client:
 Version:      master-dockerproject-2017-11-09
 API version:  1.35
 Go version:   go1.8.5
 Git commit:   458ce53
 Built:        Thu Nov  9 23:49:23 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-11-09
 API version:  1.35 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   a4bdb30
 Built:        Thu Nov  9 23:53:28 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: master-dockerproject-2017-11-09
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16278 (16278.1000.amd64fre.rs3_release.170825-1441)
Operating System: Windows Server Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: WIN-447DPV82V22
ID: CEFS:L4OD:AJOD:7HXW:AGAI:EVGX:LI74:HCDG:JQNY:MUZC:3EXK:DHJK
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual windows server 1709 16278 running in ESXi 6.5

**Comment by thaJeztah** [comment] 2017-11-10 12:21
This looks like a duplicate of https://github.com/moby/moby/issues/35247. Let me close this one to prevent the discussion from diverging, but feel free to participate on the linked issue

**Closed by thaJeztah** 2017-11-10 12:21 UTC
Labels: platform/windows
