### ISSUE TITLE
hang on `docker stop`

### ISSUE THREAD

**Issue by andybalholm** [moby/moby#18758] opened 2015-12-17 23:51 UTC
When we stop our Discourse Docker container with `docker stop app` or `service docker restart`, it hangs. One or more `runsv` processes inside the container hang, consuming 100% CPU. top shows the CPU usage as "system" usage, so they are hung inside the kernel somewhere. Because of this, they can't be killed even with SIGKILL; we need to reboot the server.

This is a regression that showed up after we did some routine updates on the server (the ones that Ubuntu nags you to do). The packages that were upgraded included the kernel and Docker.

```
root@mail:~# uname -a
Linux mail.daystar.io 3.13.0-73-generic #116-Ubuntu SMP Fri Dec 4 15:31:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@mail:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
root@mail:~# docker info
Containers: 34
Images: 131
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 230
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-73-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 12
Total Memory: 51.08 GiB
Name: mail.daystar.io
ID: 5PHA:QONL:U6TH:2IPO:AVNK:LMCW:R6XT:AVZZ:KNGC:T4TF:SX5S:5DHN
WARNING: No swap limit support

```

**Comment by SamSaffron** [comment] 2015-12-18 00:00
note we are not noticing these hangs when using overlay

**Comment by andybalholm** [comment] 2015-12-18 00:12
Is there a way to switch my container from aufs to overlay?

**Comment by SamSaffron** [comment] 2015-12-18 00:15
http://blog.cloud66.com/docker-with-overlayfs-first-impression/ 

not all of it is applicable but the switches for running docker are...

**Comment by tgxworld** [comment] 2015-12-18 00:50
Description of problem:
`docker stop` container hangs.

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 1
Images: 13
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-21-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 15.6 GiB
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`uname -a`:
`Linux gx-pc 4.2.0-21-generic #25-Ubuntu SMP Wed Dec 2 18:42:25 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Physical Machine

How reproducible:
Consistently

Steps to Reproduce:
1. `docker pull tgxworld/runsv`
2. `docker run --name test tgxworld/runsv ./boot`
3. `docker stop test`
,
Actual Results:
Docker hangs on `docker stop test`. No output when running with `-D` flag.

Expected Results:
Container is stopped.

Additional info:
### Files for container 
https://github.com/tgxworld/runsv


### Logs from daemon
```
INFO[2113] POST /v1.21/containers/create?name=test      
INFO[2113] POST /v1.21/containers/ad439f090f88ab0cc095070a8d36a5326f30580c094d2323e959307d68a4165a/attach?stderr=1&stdout=1&stream=1 
INFO[2113] POST /v1.21/containers/ad439f090f88ab0cc095070a8d36a5326f30580c094d2323e959307d68a4165a/start 
INFO[2113] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4] 
INFO[2113] IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844] 
INFO[2121] POST /v1.21/containers/ad439f090f88ab0cc095070a8d36a5326f30580c094d2323e959307d68a4165a/kill?signal=WINCH 
INFO[2121] POST /v1.21/containers/ad439f090f88ab0cc095070a8d36a5326f30580c094d2323e959307d68a4165a/kill?signal=WINCH 
INFO[2126] POST /v1.21/containers/test/stop?t=10        
INFO[2136] Container ad439f090f88ab0cc095070a8d36a5326f30580c094d2323e959307d68a4165a failed to exit within 10 seconds of SIGTERM - using the force 
INFO[2146] Container ad439f090f88 failed to exit within 10 seconds of kill - trying direct SIGKILL 
```
### htop output
![screenshot from 2015-12-18 08-43-25](https://cloud.githubusercontent.com/assets/4335742/11886317/9ab0560a-a563-11e5-8c2e-35f18eb0a662.png)

**Comment by thaJeztah** [comment] 2015-12-19 00:06
Could this be the same issue as https://github.com/docker/docker/issues/18500 and https://github.com/docker/docker/issues/18180?

**Comment by andybalholm** [comment] 2015-12-19 00:13
I doubt it. This one is 100% CPU usage, and I don't think the others are.

**Comment by thaJeztah** [comment] 2015-12-19 00:16
@andybalholm actually, they are, though thinking now that it's not on "stop", just during the process

**Comment by Blaisorblade** [comment] 2016-01-13 05:20
In case the questions are indeed open, I do think it's #18180; that takes a SIGKILL to a process doing an AUFS write, and I suspect that's caused by the offending images in this thread.

Discourse users figured their containers have an incorrect init process, as discussed on [this Discourse forum thread](https://meta.discourse.org/t/runsv-hanging-on-docker-container-shutdown/36844/30); I believe that's just triggering a few `SIGKILL` more, maybe because `docker stop` gives up waiting, but I'm not so keen to confirm that. I have confirmed that changing the init process (using `tini`) and fiddling with how processes are terminated works around the bug.

To trigger the upstream AUFS bug for #18180, a process needs to be at the wrong point with `fatal_signal_pending` being true — that means the process got a `SIGKILL`, [it seems](https://github.com/torvalds/linux/blob/8c930204ce76eddeb2e1af66a75f0ab2506c76e2/include/linux/sched.h#L2915-L2923)).

The other evidence for the kernel bug is kernel stack trace for a hang I've seen — it's on a mutex inside AUFS code, similarly to e.g. https://github.com/docker/docker/issues/18180#issuecomment-170267519. I'm guessing the mutex is taken by the other kernel thread, running an infinite loop inside AUFS.
https://meta.discourse.org/t/from-discourse-smtp-address-in-discourse-docker-to-var-www-discourse-config-discourse-conf/37841?u=blaisorblade

**Comment by thaJeztah** [comment] 2016-01-13 05:34
If it's indeed #18180, I think we should close this, because that's not something we can fix (note that boot2docker has been updated with a fix, which will be in the next boot2docker update.

For ubuntu, this will depend on https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1533043 being accepted

**Comment by xuyungit** [comment] 2016-01-26 10:36
I encountered the same problem after switching to overlay.
xuyun@xuyun-workpc:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

docker info
Containers: 4
Images: 131
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 7.672 GiB
Name: xuyun-workpc
ID: OI5K:OD3L:U44C:4ZWM:N3LZ:BARZ:KDEQ:5DIY:LLBE:UKHP:VBEN:AY6L
WARNING: No swap limit support

uname -a
Linux xuyun-workpc 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xuyungit** [comment] 2016-01-26 10:51
After restart the machine, docker ps -a shows the container is in 'Dead' status, and docker logs shows:
docker logs 5969
Error response from daemon: open /var/lib/docker/overlay/59694504b3e88365c9323237c4418c51350941e7498de05584cc37d69f139d09/lower-id: no such file or directory

**Comment by Blaisorblade** [comment] 2016-01-26 11:27
@xuyungit: having done some analysis here (suggesting this one is aufs-specific), I'd recommend filing that as a new standalone bug report (with a link), even though some symptoms might be similar — other symptoms appear rather different.

**Comment by SamSaffron** [comment] 2016-01-27 05:35
@thaJeztah @jfrazelle having just worked around this issue I think docker can (and should) workaround this problem. 

The gist of what happens is: 

- You have a container with N processes
- `docker stop` is issued
- pid 1 gets a TERM 
- pid 1 exists but other pids are still running some may have got TERMs
- In some weird kernel linux container condition the orphan processes are not torn down and trigger a failure mode in the kernel.

Instead I thing the "semantics" of `docker stop` should be changed to:

1. Send TERM to pid 1, wait up to 10 seconds for pid 1 to finish. (if not finished send a QUIT)  
2. Check if any other pids are still running in the container, if there are 
   a. In parallel send TERM + wait for up to 5 seconds for each of the remaining pids. If it is still running send a QUIT and wait. 
3. Stop container

This will change the semantics a bit on docker stop, but, on the other hand, introduce some sort of documented behavior for orphans and make `stop` much more reliable even if kernel or aufs has bugs.

**Comment by Blaisorblade** [comment] 2016-01-27 19:59
- [ ] a
- [ ] b
- [ ] c

**Comment by sleaze** [comment] 2016-03-14 18:46
@SamSaffron I am completely onboard with your proposal, I've been experiencing these failures with the exact same conditions you describe and it's a huge pain!  Causes my Jenkins test pipeline to get stuck and I suspect may even be causing the VM to freeze up requiring a reboot.

**Comment by Nokel81** [comment] 2016-04-21 15:05
I get this as well. I have a machine with 2 cpus and when I do a graceful stop on the ongoing containers it hangs and I need to manually stop the vm via virtualbox to stop it. This resualts in me having to start/stop the vm twice before the ports are exposed.

**Comment by ApsOps** [comment] 2016-12-15 11:09
I'm hitting this on `v1.12.1`.

`docker stop` hangs forever with these logs, any process starts using 100% CPU.
```
time="2016-12-15T11:02:30.280574522Z" level=info msg="Container 7d45eb7c499fa82a2e087f0eb20dc41dcd73ed83801a327d35d359b0f0d28d09 failed to exit within 10 seconds of signal 15 - using the force"
time="2016-12-15T11:02:40.281334541Z" level=info msg="Container 7d45eb7c499f failed to exit within 10 seconds of kill - trying direct SIGKILL"
time="2016-12-15T11:03:52.427456023Z" level=info msg="Container 7d45eb7c499fa82a2e087f0eb20dc41dcd73ed83801a327d35d359b0f0d28d09 failed to exit within 30 seconds of signal 15 - using the force"
time="2016-12-15T11:04:02.428313157Z" level=info msg="Container 7d45eb7c499f failed to exit within 10 seconds of kill - trying direct SIGKILL"
```

**Comment by thaJeztah** [comment] 2016-12-15 11:13
@ApsOps do those containers eventually get stopped? `failed to exit within 10 seconds of signal 15 - using the force` means that the process in the container may not be handling the stop signal; docker will force killing the container if the process does not handle that. Those errors in itself do not indicate there's a bug.

**Comment by ApsOps** [comment] 2016-12-15 11:16
@thaJeztah that's the thing. These containers are never stopped.

**Comment by thaJeztah** [comment] 2016-12-15 11:27
@ApsOps If you're using the AUFS storage driver, may sound like https://github.com/docker/docker/issues/18180, which mostly occurs with JAVA processes; that's a kernel issue, and is resolved by updating your kernel https://github.com/docker/docker/issues/18180#issuecomment-193708192

**Comment by ApsOps** [comment] 2016-12-15 11:52
@thaJeztah Ah, thanks a lot! I think that's it. This is indeed a Java process.
We run EC2 instances in an ASG, so restart is not possible (using Ubuntu 14.04 right now). I guess I'll have to create new AMIs.

**Comment by thaJeztah** [comment] 2023-09-16 14:56
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 14:56 UTC
Labels: area/kernel, version/1.9
