### ISSUE TITLE
/dev/console of docker implementation breaks systemd >= 231

### ISSUE THREAD

**Issue by DirkTheDaring** [moby/moby#27202] opened 2016-10-06 19:07 UTC
Hi guys,

I heard bad reports abouts that systemd and docker folks cannot get along. 
Hope this is not the case. With fedora-25 (alpha, now approaching beta)  systemd stopped working correctly within a docker container as process 1, if it configured to log to  /dev/console. It worked until fedora 24 because  systemd actually contained a bug, which made docker "just work." Now with the technically more correct implementation /dev/console stopped working with docker, which actually needs now work the docker guys. 
Please have a look at 

https://github.com/systemd/systemd/pull/4262

It contains a technical sound description of Lennart, what needs to investigated/changed into docker to make it work again in the comments to the broken /dev/console

Without any change, systemd will stop working from this point  which is, not a systemd, but a docker issue, from a technical point of view.

**Comment by LK4D4** [comment] 2016-10-06 19:50
ping @mrunalp 
Probably something for you. I'm not sure if it's possible to run systemd in a container with vanilla docker.
Let me know if you understand educated guess of Lennart there and thread overall.

**Comment by mitchcapper** [comment] 2016-10-06 19:53
https://github.com/systemd/systemd/pull/4262#issuecomment-252044406 is the primary relevant comment in the ticket.

**Comment by justincormack** [comment] 2016-10-06 20:30
@LK4D4 yes, `systemd` does run in vanilla Docker if set up correctly.

**Comment by mrunalp** [comment] 2016-10-06 20:42
Yeah, it should work with some tweaks like mounting --tmpfs at /run --tmpfs at /tmp, bind mounting /sys/fs/cgroup/systemd read write and setting signal to SIGRTMIN+3. I'll take a look at the systemd report to see what's happening with /dev/console.

**Comment by DirkTheDaring** [comment] 2016-10-06 20:56
Yes systemddefinitly runs in fedora 22,23,24.

Although it is broken now for fedora 25, when you try to run it in
"serious" environment, which needs all output routed to /dev/console
(which in turn is collected by kubernetes and elk). See ticket for why.

Actually if you use some of Lennarts tricks he provides with machine
manager it works with  docker with something like

dnf install --installroot=destdir  <yourpackages>

cd destdir
tar  -c .| docker import master.fedora-24-full

Here is a docker recipe, which I use, there are so many broken systemd
recipes for docker out there. Note e.g. the STOPSIGNAL statement, and
also the disabling of certain services which are not needed in a container.

---------------------------------------------------------------

FROM master.fedora-24-full
MAINTAINER <baldur@email.de>

# A systemd container will probably never run correctly under MacOS (sorry!)
# * /sys/fs/cgroup is needed  until kernel work for cgroups is completed
(started at 4.6 ongoing)
# * tty is needed to output on for docker logs
# * SYS_ADMIN capability is needed for systemd in order to be able to
change user ids for services
#
# Example how to run the image from docker
# docker run -d --tty  --security-opt=seccomp:unconfined --cap-add
SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro --hostname
systemd-fedora.prod.cloud --name systemd-fedora.prod.cloud 
images.fedora-24-full.systemd
#
# To follow logs
# docker logs -f systemd-fedora.prod.cloud

# Tell systemd service that it is running in a docker container
# https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/
# Section "Environment Variables/1"
ENV container docker

# Turn off services which usually are only needed for
# handling hardware or desktop/virtual machine operation
# Some services like sshd may require turning on stuff
# but this can be seen in the logs if a requirement
# for a service fails
# Nothing else done by the standard images!

RUN for service in\
 console-getty.service\
 dbus.service\
 dbus.socket\
 dev-hugepages.mount\
 getty.target\
 sys-fs-fuse-connections.mount\
 systemd-logind.service\
 systemd-remount-fs.service\
 systemd-udevd\
 systemd-vconsole-setup.service\
 dnf-makecache.timer\
 ;do systemctl mask $service; done


# systemd complains in newer versions if this is not set
# probably not needed if journal persistence is not used
RUN chattr +C /var/log/journal

# Redirect the logging of journald purely to console
# which enables docker logs  to catch everything
# also any persistence of the log in the container
# is turned off
#
ADD install/journald.conf /etc/systemd/journald.conf
# Turn of [OK] messages and log coloring
ADD install/system.conf   /etc/systemd/system.conf

# Required for systemd: This should go away at some time
VOLUME [ "/sys/fs/cgroup" ]

# Terminate systemd with the proper signal (inits shutdown)
# "--stop-signal=$(kill -l RTMIN+3)
STOPSIGNAL 37


# We should return tu /sbin/init at some time
CMD    [ "/usr/sbin/init" ]

# NOTE: Run container with "--stop-signal=$(kill -l RTMIN+3)" option to

----------------------------------------------


Am 06.10.2016 um 22:43 schrieb Mrunal Patel:

**Comment by keszybz** [comment] 2016-10-07 12:58
@DirkTheDaring: for various services that you disable, some of them have been split out into systemd-udev.rpm in F25+, so you can just not install that rpm. You'll save some space and bother.

**Comment by crosbymichael** [comment] 2016-10-12 20:59
From reading the stuff it does not seem to be a problem handling signals but that we close the ptymaster when the copy returns because systemd closes the stdin.

@DirkTheDaring do you have an easy way to help verify a fix if I create a patch?

**Comment by mrunalp** [comment] 2016-10-12 21:21
@crosbymichael That's my read of the problem as well. One solution that I read about was detecting that the slave is being opened using inotify.

**Comment by crosbymichael** [comment] 2016-10-12 22:28
@DirkTheDaring can you give us more infomration about the exact command that you are running?  Are you using the `-i` or `-t` flag?

**Comment by DirkTheDaring** [comment] 2016-10-12 22:58
I will be happy about anything which makes my parch go away


Am 2016-10-13 00:29, schrieb Michael Crosby:

**Comment by crosbymichael** [comment] 2016-10-13 17:10
@DirkTheDaring can you share your `docker run` command line?

**Comment by DirkTheDaring** [comment] 2016-10-13 17:23
for commandline see the dockerfile  here. the master image was build with a 
dnf installroot ....  
and then uploaded to docker.
It basically what you install as fedorua-minimal.


```
FROM master.fedora-25-full

# * /sys/fs/cgroup is needed until kernel work for cgroups is completed (started at 4.6 ongoing)
# * tty is needed to create output for docker logs
# * SYS_ADMIN capability is needed for systemd in order to be able to change user ids for services
#
# Example how to run the image from docker
# docker run -d --tty  --security-opt=seccomp:unconfined --cap-add SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro --hostname systemd-fedora.prod.cloud --name systemd-fedora.prod.cloud  images.fedora-25-full.systemd
#
# To follow logs
# docker logs -f systemd-fedora.prod.cloud

# Tell systemd service that it is running in a docker container
# https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/
# Section "Environment Variables/1"
ENV container docker

# Turn off services which usually are only needed for
# handling hardware or desktop/virtual machine operation
# Some services like sshd may require turning on stuff
# but this can be seen in the logs if a requirement
# for a service fails
# Nothing else done by the standard images!

RUN for service in\
 console-getty.service\
 dbus.service\
 dbus.socket\
 dev-hugepages.mount\
 getty.target\
 sys-fs-fuse-connections.mount\
 systemd-logind.service\
 systemd-remount-fs.service\
 systemd-udevd\
 systemd-vconsole-setup.service\
 dnf-makecache.timer\
 ;do systemctl mask $service; done


# systemd complains in newer versions if this is not set
# probably not needed if journal persistence is not used
RUN chattr +C /var/log/journal

# Redirect the logging of journald purely to console
# which enables docker logs  to catch everything
# also any persistence of the log in the container
# is turned off
#
ADD install/journald.conf /etc/systemd/journald.conf
# Turn off [OK] messages and log coloring
ADD install/system.conf   /etc/systemd/system.conf

# Required for systemd: This should go away at some time
VOLUME [ "/sys/fs/cgroup" ]

# Terminate systemd with the proper signal (inits shutdown)
# "--stop-signal=$(kill -l RTMIN+3)
STOPSIGNAL 37

CMD  [ "/sbin/init" ]


```

**Comment by crosbymichael** [comment] 2016-10-13 18:04
@DirkTheDaring is there anyway you can just push this image so that I can pull it so I have the same base image created from dnf?

**Comment by DirkTheDaring** [comment] 2016-10-13 18:22
you can try this to create the image:
```
#!/bin/sh
function create_repo
{
  local REPO_SHORT_NAME=$1
  local REPO_NAME=$2
  local REPO_VAR=$3
cat<<EOF
[$REPO_SHORT_NAME]
name=$REPO_NAME
failovermethod=priority
metalink=https://mirrors.fedoraproject.org/metalink?repo=$REPO_VAR\$releasever&arch=\$basearch
enabled=1
metadata_expire=6h
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-\$releasever-\$basearch
skip_if_unavailable=False
EOF

}

OS_VERSION=24

mkdir -p /var/lib/build/fedora-$OS_VERSION/full/etc/yum.repos.d
mkdir -p /var/lib/build/fedora-$OS_VERSION/01

create_repo fedora          "Fedora \$releasever - \$basearch" "fedora-" >/var/lib/build/fedora-$OS_VERSION/full/etc/yum.repos.d/fedora.repo
create_repo updates         "Fedora \$releasever - \$basearch - Updates" "updates-released-f" >/var/lib/build/fedora-$OS_VERSION/full/etc/yum.repos.d/fedora-updates.repo
create_repo updates-testing "Fedora \$releasever - \$basearch - Test Updates" "updates-testing-f" >/var/lib/build/fedora-$OS_VERSION/full/etc/yum.repos.d/fedora-updates-testing.repo

cat<<EOF >/var/lib/build/fedora-$OS_VERSION/full/dnf.conf
[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=true
cachedir=/var/lib/build/fedora-$OS_VERSION/full/var/cache/yum/$basearch/$releasever
reposdir=/var/lib/build/fedora-$OS_VERSION/full/etc/yum.repos.d
pluginconfpath=/var/lib/build/fedora-$OS_VERSION/full/etc/dnf/plugins
EOF

dnf -y -c /var/lib/build/fedora-$OS_VERSION/full/dnf.conf --releasever=$OS_VERSION --nogpg --installroot=/var/lib/build/fedora-$OS_VERSION/full/01 '--disablerepo=*' --enablerepo=fedora --enablerepo=updates --enablerepo=updates-testing install bash rootfiles vim-minimal sssd-client e2fsprogs dnf dnf-yum fedora-release procps-ng
```

**Comment by crosbymichael** [comment] 2016-10-17 16:54
@DirkTheDaring What is your exact `docker version` output.  I cannot even get the Dockerfile to build so I'm guessing you have the RH version with patches that I don't have.

**Comment by DirkTheDaring** [comment] 2016-10-17 18:21
what kind of error do you get ? i am actually using the docker rpm from the docker site

# docker --version
Docker version 1.12.1, build 23cf638
# rpm -qf /usr/bin/docker
docker-engine-1.12.1-1.fc24.x86_64

# cat /etc/fedora-release
Fedora release 24 (Twenty Four)

**Comment by crosbymichael** [comment] 2016-10-17 18:29
@DirkTheDaring ok, whats the output of `docker info`?  It could be how you have journald configured on your daemon. I don't have that logger enabled and was getting an error on build when it was looking for journald

**Comment by DirkTheDaring** [comment] 2016-10-17 18:31
# docker info
Containers: 51
 Running: 40
 Paused: 0
 Stopped: 11
Images: 1500
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v4.5.2
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.5-200.fc24.x86_64
Operating System: Fedora 24 (Cloud Edition)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 31.16 GiB
Name: production.fritz.box
ID: 4JDQ:ZMCA:Y5BF:VL7D:BOJ5:PDJI:XYX4:YKJE:MIG7:2HK7:NL2S:LZ6N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by crosbymichael** [comment] 2016-10-31 16:45
@DirkTheDaring I have tried following your scripts but I have been unable to reproduce the issue.  If you could build a small reproducible image that you can push and that I can download and replicate the problem you are having that would help very much.  You were adding various files in the build that I didn't have to configure systemd and journald, I tried to replicate them but still having issues reproducing.

**Comment by DirkTheDaring** [comment] 2016-11-01 07:55
I put it here
`curl -O  https://kaupon.de/images.fedora-25-full.systemd.tar.gz`

md5sum:
`0f5cc2dc7dc3e9bb21fb309c00c63948  images.fedora-25-full.systemd.tar.gz`

**Comment by DirkTheDaring** [comment] 2016-11-01 08:03
i tested it with  the new 1.12.3 - still the same problem

**Comment by DirkTheDaring** [comment] 2016-11-15 15:59
Any news?

**Comment by rhatdan** [comment] 2016-11-29 15:09
@mrunalp Have you been able to figure out anything?

**Comment by runcom** [comment] 2016-11-29 15:40
@crosbymichael since you've been asking, the following simple `docker run` triggers this issue (by not showing any output):
```sh
$ docker run --rm -ti -e container=docker -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp fedora:rawhide /usr/sbin/init
Unable to find image 'fedora:rawhide' locally
rawhide: Pulling from library/fedora
7b6448343582: Pull complete
Digest: sha256:b8dd62c42b48b2ccecb3f6396784ff8c11eabc0fb9cab84070ace36fae1c8e30
Status: Downloaded newer image for fedora:rawhide
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

**Comment by mrunalp** [comment] 2016-11-29 15:54
/sys/fs/cgroup/systemd needs to be mounted rw.

**Comment by runcom** [comment] 2016-11-29 16:06
> /sys/fs/cgroup/systemd needs to be mounted rw.

@mrunalp I can't get that running w/ `-v /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd:rw` either

**Comment by mrunalp** [comment] 2016-11-29 16:08
Yeah it won't fix this issue.

**Comment by DirkTheDaring** [comment] 2016-11-29 20:20
Example to start it, if the image is named "images.fedora-25-full.systemd".
Do not try this on a Mac - this doesn't work at all with cgroups.

`docker run -d --tty  --security-opt=seccomp:unconfined --cap-add SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro --hostname systemd-fedora.prod.cloud --name systemd-fedora.prod.cloud  images.fedora-25-full.systemd`

**Comment by mrunalp** [comment] 2016-11-29 23:30
okay, so this is what I did to run httpd under systemd with docker upstream latest code and fedora 24 based image.
Dockerfile:
```
FROM fedora:24
ENV container docker
RUN dnf install -y httpd procps-ng && dnf clean all && systemctl enable httpd
STOPSIGNAL SIGRTMIN+3
EXPOSE 80
CMD [ "/sbin/init" ]
```
Starting the container:
```
[root@home docker]# ./bundles/1.14.0-dev/dynbinary-client/docker run --security-opt=seccomp:unconfined --cap-add SYS_ADMIN -v /sys/fs/cgroup/systemd:/sys/fs/cgroup/sy
stemd --tmpfs /run --tmpfs /tmp -it --rm fedora-httpd 
systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD 
+IDN)
Detected virtualization docker.
Detected architecture x86-64.
Running with unpopulated /etc.

Welcome to Fedora 24 (Twenty Four)!

Set hostname to <fcf064ef8783>.
Initializing machine ID from random generator.
Failed to populate /etc with preset unit settings, ignoring: No such file or directory
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Reached target Encrypted Volumes.
[  OK  ] Reached target Swap.
[  OK  ] Reached target Local File Systems.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Listening on Journal Socket.
[  OK  ] Created slice System Slice.
         Starting Rebuild Journal Catalog...
         Starting Journal Service...
         Starting Rebuild Dynamic Linker Cache...
         Starting First Boot Wizard...
         Starting Load/Save Random Seed...
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target Paths.
[  OK  ] Listening on Process Core Dump Socket.
[  OK  ] Reached target Slices.
[  OK  ] Started Rebuild Journal Catalog.
[  OK  ] Started First Boot Wizard.
[  OK  ] Started Load/Save Random Seed.
         Starting Create System Users...
[  OK  ] Started Rebuild Dynamic Linker Cache.
[  OK  ] Started Create System Users.
         Starting Update is Completed...
[  OK  ] Started Journal Service.
[  OK  ] Started Update is Completed.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Started Flush Journal to Persistent Storage.
 Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[  OK  ] Reached target System Initialization.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Started dnf makecache timer.
[  OK  ] Reached target Timers.
[  OK  ] Reached target Basic System.
         Starting Permit User Sessions...
         Starting The Apache HTTP Server...
[  OK  ] Started D-Bus System Message Bus.
[  OK  ] Started Permit User Sessions.
[  OK  ] Started The Apache HTTP Server.
[  OK  ] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.
```

One can exec into this container and curl localhost:80
```
[root@home dockerfiles]# docker exec -it 659 sh
sh-4.3# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 23:24 ?        00:00:00 /sbin/init
root        21     1  0 23:24 ?        00:00:00 /usr/lib/systemd/systemd-journald
dbus        27     1  0 23:24 ?        00:00:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root        29     1  0 23:24 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache      30    29  0 23:24 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache      32    29  0 23:24 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache      33    29  0 23:24 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache      37    29  0 23:24 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache      41    29  0 23:24 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
root        62     0  0 23:24 ?        00:00:00 sh
root        68    62  0 23:24 ?        00:00:00 ps -ef
sh-4.3# curl localhost:80
...

I expect this to fail when one switches image to fedora:latest or fedora:rawhide.

**Comment by mrunalp** [comment] 2016-11-29 23:40
It does come up with fedora:latest but fails using fedora:rawhide as base image. One can see that /proc/1/fd/{0,1} are duped to /dev/null in rawhide vs pointing to console in 24. Interestingly they point to /dev/null in fedora:latest but systemd is still able to come up.

**Comment by DirkTheDaring** [comment] 2016-12-02 07:30
Please have a look at the related/initial discussion:
https://github.com/systemd/systemd/pull/4262#issuecomment-254887097

**Comment by DirkTheDaring** [comment] 2016-12-09 10:48
any news on this issue?

**Comment by paralin** [comment] 2017-01-07 22:38
I'm also watching this now - see:

 - https://bugzilla.redhat.com/show_bug.cgi?id=1373780#c4
 - https://github.com/systemd/systemd/pull/4262
 - http://stackoverflow.com/questions/38551965/get-log-of-a-systemd-journald-in-a-docker-container-to-docker-logs/39064790?noredirect=1#comment70260498_39064790

Should be easy enough to fix. The question is what the ramifications of ignoring SIGHUP are.

**Comment by DirkTheDaring** [comment] 2017-01-21 13:23
Retested  on new docker version. /dev/console is still broken.
docker --version
Docker version 1.13.0, build 49bf474

**Comment by vans163** [comment] 2017-04-04 19:55
Docker version 1.12.6, build ae7d637/1.12.6

Same issue. Fedora 24 works fine, Fedora 25 and rawhide is broken, the container runs but no output to stdout.

Following the basic steps here you can reproduce it https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/#more-427152.

You also may need to deal with SELinux if following that blog post and you get permission errors.

**Comment by datawolf** [comment] 2017-04-15 03:59
Same issue. Fedora 24 works fine, Fedora rawhide is broken.


## docker version:

```bash
root@ubuntu:~# docker version
Client:
 Version:      17.06.0-dev
 API version:  1.30
 Go version:   go1.7.5
 Git commit:   41f4c3c
 Built:        Fri Apr 14 09:41:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   41f4c3c
 Built:        Fri Apr 14 09:41:19 2017
 OS/Arch:      linux/amd64
 Experimental: false

```


## reproduce steps:

### Dockefiles

Dockerfile.24 

```
FROM fedora:24
ENV container docker
RUN dnf install -y httpd procps-ng && dnf clean all && systemctl enable httpd
STOPSIGNAL SIGRTMIN+3
EXPOSE 80
CMD [ "/sbin/init" ]
```

Dockerfile.rawhide 

```
FROM fedora:rawhide
ENV container docker
RUN dnf install -y httpd procps-ng && dnf clean all && systemctl enable httpd
STOPSIGNAL SIGRTMIN+3
EXPOSE 80
CMD [ "/sbin/init" ]
```

### build docker images

```bash
# docker build -t fedora-httpd:24 -f Dockerfile.24 .
# docker build -t fedora-httpd:rawhide -f Dockerfile.rawhide .
```

###  Run

```
# docker run --security-opt=seccomp:unconfined --cap-add SYS_ADMIN -v /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd --tmpfs /run --tmpfs /tmp -it --rm fedora-httpd:24
```

This works fine. but 

```
# docker run --security-opt=seccomp:unconfined --cap-add SYS_ADMIN -v /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd --tmpfs /run --tmpfs /tmp -it --rm fedora-httpd:rawhide
```
 is broken, the container runs but no output to stdout.

### simple debug

I apply the following patch on `containerd-shim`,

```go
diff --git a/containerd-shim/process_linux.go b/containerd-shim/process_linux.go
index f42af57..a9e3786 100644
--- a/containerd-shim/process_linux.go
+++ b/containerd-shim/process_linux.go
@@ -5,6 +5,7 @@ package main
 import (
        "fmt"
        "io"
+       "os"
        "os/exec"
        "syscall"
        "time"
@@ -49,7 +50,13 @@ func (p *process) openIO() error {
                if err != nil {
                        return err
                }
-               go io.Copy(master, stdin)
+               go func() {
+                       f, _ := os.Create("/root/shim1.log")
+                       fmt.Fprintf(f, "LOG1:\n")
+                       defer f.Close()
+                       io.Copy(master, stdin)
+                       fmt.Fprintf(f, "io.Copy(master,stdin) returned\n")
+               }()
                stdoutw, err := fifo.OpenFifo(ctx, p.state.Stdout, syscall.O_WRONLY, 0)
                if err != nil {
                        return err
@@ -60,7 +67,11 @@ func (p *process) openIO() error {
                }
                p.Add(1)
                go func() {
+                       f1, _ := os.Create("/root/shim2.log")
+                       fmt.Fprintf(f1, "LOG2:\n")
+                       defer f1.Close()
                        io.Copy(stdoutw, master)
+                       fmt.Fprintf(f1, "io.Copy(stdout,master) returned\n")
                        master.Close()
                        stdoutr.Close()
                        stdoutw.Close()
```

When run container with `fedora-httpd:rawhide`, the log output 

```
root@ubuntu:~# cat shim1.log 
LOG1:
root@ubuntu:~# cat shim2.log 
LOG2:
io.Copy(stdout,master) returned
```
This means that when systemd call `make_stdio_null` and the `pty mater` of docker side get an `EIO`, and then `io.Copy(stdoutw, master)` returns. 


Any ideas to fix this issue? @DirkTheDaring @mrunalp @justincormack

**Comment by datawolf** [comment] 2017-04-17 14:15
More info:
With the following patch,  we can get the output of the `Fedora rawhide`, but the shim can not exit.
Because when poll the `pty master`, it always get `syscall.EPOLLOUT|syscall.EPOLLHUP`, and the` for` loop can not exit.

```go
diff --git a/containerd-shim/process_linux.go b/containerd-shim/process_linux.go
index f42af57..9f82dea 100644
--- a/containerd-shim/process_linux.go
+++ b/containerd-shim/process_linux.go
@@ -5,6 +5,7 @@ package main
 import (
        "fmt"
        "io"
+       "os"
        "os/exec"
        "syscall"
        "time"
@@ -49,7 +50,13 @@ func (p *process) openIO() error {
                if err != nil {
                        return err
                }
-               go io.Copy(master, stdin)
+               go func() {
+                       f, _ := os.Create("/root/shim1.log")
+                       fmt.Fprintf(f, "LOG1:\n")
+                       defer f.Close()
+                       io.Copy(master, stdin)
+                       fmt.Fprintf(f, "io.Copy(master,stdin) returned\n")
+               }()
                stdoutw, err := fifo.OpenFifo(ctx, p.state.Stdout, syscall.O_WRONLY, 0)
                if err != nil {
                        return err
@@ -60,7 +67,69 @@ func (p *process) openIO() error {
                }
                p.Add(1)
                go func() {
-                       io.Copy(stdoutw, master)
+                       f1, _ := os.Create("/root/shim2.log")
+                       fmt.Fprintf(f1, "LOG2:\n")
+                       defer f1.Close()
+                       epollFd, _ := syscall.EpollCreate1(0)
+                       syscall.EpollCtl(epollFd, syscall.EPOLL_CTL_ADD, int(master.Fd()),
+                               &syscall.EpollEvent{Events: syscall.EPOLLIN | syscall.EPOLLOUT, Fd: int32(master.Fd())})
+                       events := make([]syscall.EpollEvent, 16)
+                       var exit bool
+                       for {
+                               exit = false
+                               n, _ := syscall.EpollWait(epollFd, events, -1)
+                               for _, ev := range events[:n] {
+                                       if ev.Events == syscall.EPOLLIN || ev.Events == syscall.EPOLLOUT {
+                                               buf := make([]byte, 32*1024)
+                                               for {
+                                                       nr, er := master.Read(buf)
+                                                       if nr > 0 {
+                                                               nw, ew := stdoutw.Write(buf[0:nr])
+                                                               if ew != nil {
+                                                                       break
+                                                               }
+                                                               if nr != nw {
+                                                                       break
+                                                               }
+                                                       }
+                                                       if er != nil {
+                                                               break
+                                                       }
+                                               }
+                                       }
+                                       if ev.Events == syscall.EPOLLIN|syscall.EPOLLHUP {
+                                               fmt.Fprintf(f1, "\tepoll hup and in\n")
+                                               break
+                                       }
+                                       if ev.Events == syscall.EPOLLOUT|syscall.EPOLLHUP {
+                                               fmt.Fprintf(f1, "\tepoll hup and out\n")
+                                               break
+                                       }
+
+                                       if ev.Events == syscall.EPOLLHUP {
+                                               fmt.Fprintf(f1, "\tepoll hup\n")
+                                               exit = true
+                                               break
+                                       }
+                                       if ev.Events == syscall.EPOLLRDHUP {
+                                               fmt.Fprintf(f1, "\tepoll hup\n")
+                                               exit = true
+                                               break
+                                       }
+
+                                       if ev.Events&syscall.EPOLLERR != 0 {
+                                               fmt.Fprintf(f1, "\tepoll err\n")
+                                               exit = true
+                                               break
+                                       }
+
+                               }
+                               if exit == true {
+                                       fmt.Fprintf(f1, "exit epoll\n")
+                                       break
+                               }
+                       }
+                       fmt.Fprintf(f1, "io.Copy(stdout,master) returned\n")
                        master.Close()
                        stdoutr.Close()
                        stdoutw.Close()
```

Does any knows how to hack it? thanks.

**Comment by crosbymichael** [comment] 2017-05-09 00:00
Does anyone know why systemd needs `--tty` to run?  Just don't add it and let it mknod a `/dev/console` right?

**Comment by paralin** [comment] 2017-05-09 01:50
So that the logs can be seen in Docker?

**Comment by TomasTomecek** [comment] 2017-05-09 12:15
systemd doesn't need `--tty` to run, I just tried it:

```
docker run -e 'container=docker' --privileged -d --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd:rw registry.fedoraproject.org/fedora:26 /sbin/init
```

(didn't work without `--privileged`, not sure which particular capability is needed)

The command above works reasonably well:

```
[root@8ed22f651971 /]# systemd-cgls
Control group /system.slice/docker-8ed22f651971024ada1c359f8af4b7229fdad891a0cd983e84925ebf54b1ac6b.scope:
-.slice
├─36 bash
├─86 systemd-cgls
├─87 [systemd-cgls]
├─init.scope
│ └─1 /sbin/init
└─system.slice
  ├─dbus.service
  │ └─28 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  ├─system-getty.slice
  │ └─getty@tty1.service
  │   └─75 /sbin/agetty --noclear tty1 linux
  ├─systemd-logind.service
  │ └─27 /usr/lib/systemd/systemd-logind
  └─systemd-journald.service
    └─14 /usr/lib/systemd/systemd-journald
```

The issue is obvious: with this method it's impossible to get systemd output via `docker logs`.

systemd doesn't create `/dev/console` (the behavior @crosbymichael mentions):
```
[root@8ed22f651971 /]# ll /dev/console
ls: cannot access '/dev/console': No such file or directory
```

Is this upstream project interested in implementing behaviour Lennart is describing in first paragraph of this [comment](https://github.com/systemd/systemd/pull/4262#issuecomment-299031323)? Or is the better fix what @cyphar proposes in [this comment](https://github.com/systemd/systemd/pull/4262#issuecomment-298952433)?

**Comment by paralin** [comment] 2017-05-09 12:18
You need CAP_MKNOD and seccomp=unconfined I believe.

**Comment by TomasTomecek** [comment] 2017-05-09 13:41
Still not creating (I'm able to do it myself though):

```
[root@cfdb0158c7ad /]# ll /dev/console
ls: cannot access '/dev/console': No such file or directory

[root@cfdb0158c7ad /]# mknod -m 600 /dev/console c 5 1

[root@cfdb0158c7ad /]# ll /dev/console
crw------- 1 root root 5, 1 May  9  2017 /dev/console
```

**Comment by cpuguy83** [comment] 2018-07-05 17:33
Closing since it looks like this was fixed in the console library being used (https://github.com/containerd/console/pull/10).
Feel free (as always) to correct me here.

Thanks all!

**Closed by cpuguy83** 2018-07-05 17:33 UTC
Labels: area/runtime, area/systemd, status/more-info-needed
