### ISSUE TITLE
Link of clean up in run is not correct

### ISSUE THREAD

**Issue by iblancasa** [moby/moby#34209] opened 2017-07-21 10:36 UTC
**Description**

The link of the "docker run" clean up command is not correct. The link is "https://docs.docker.com/engine/reference/run/#clean-up---rm" and should be "https://docs.docker.com/engine/reference/run/#clean-up--rm".

**Steps to reproduce the issue:**
1. Go to https://docs.docker.com/engine/reference/run/
2. Click the link
3. It doesn't work
4. Check https://docs.docker.com/engine/reference/run/#clean-up--rm

**Describe the results you received:**
The link doesn't work

**Describe the results you expected:**
The link should work

**Additional information you deem important (e.g. issue happens only occasionally):**
I notice that if I change the markdown code to have only one "-", the link of the markdown is broken.

**Output of `docker version`:**
It is the online documentation of 17.06

**Output of `docker info`:**
It is the online documentation of 17.06

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None

**Comment by thaJeztah** [comment] 2017-08-12 11:10
Thanks for reporting! I marked this one for my todo's as I suspected the creation of anchor-id's changed with the new tooling used for the documentation, but noticed there's actually a different problem causing this.

The `--rm` flag is an option with _two_ dashes; the anchor ("fragment") for this _should be_ `#clean-up--rm`, however it looks like there's a configuration issue with the tooling generating the docs, and it replaces `--` with an em-dash (`–`);

<img width="459" alt="screen shot 2017-08-12 at 13 06 09" src="https://user-images.githubusercontent.com/1804568/29240133-1327b98a-7f5f-11e7-8cc0-497200a83558.png">

This causes both the link to not work, and is confusing because it now looks like the option is `-rm` (single dash), which is incorrect:

```bash
$ docker run -rm busybox
unknown shorthand flag: 'r' in -rm
See 'docker run --help'.
```

We had similar issues with the old tooling in the past, but could fix that by changing the configuration (see https://github.com/docker/docs-base/issues/66, https://github.com/docker/docs-base/issues/189) which was fixed by updating the configuration https://github.com/docker/docs-base/pull/190

Let me open an issue in the documentation issue tracker for this 👍

**Comment by johndmulhausen** [comment] 2017-08-14 20:40
Just wrap the bits you don't want converted into en-dashes in backticks, i.e. `--rm` vs --rm. This is expected behavior.

**Comment by thaJeztah** [comment] 2023-09-16 22:06
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 22:06 UTC
Labels: kind/bug, area/docs, status/claimed
