### ISSUE TITLE
Memory access limits aren't available via compose files

### ISSUE THREAD

**Issue by wheelybird** [moby/moby#39483] opened 2019-07-10 10:58 UTC
**Description**

The only resource limit for memory that you can pass via compose files is "memory".  Other limits are available via the command-line (https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory).
This means that it's not possible to apply these limits to Swarm services when using compose files to define the services.

The compose schema at 
https://github.com/docker/compose/blob/7ae632a9ee7530fcf81e212baa3e588f477ea862/compose/config/config_schema_v3.7.json shows that resource limits are limited (ha!) to "memory" and "cpu"

**Steps to reproduce the issue:**
1. Add "memory-swap" to the deploy: resources: limits: block in compose.
2. Try deploying the service

**Describe the results you received:**
`memory-swap Additional property memory-swap is not allowed`

**Describe the results you expected:**
That the limits which can be passed via the cli are accepted by compose.

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 127
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: l8hgak0hicao4h5a2b2vw5jrj
 Is Manager: true
 ClusterID: i1cfbjimxou9zs4lnepdnh4ls
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.43.106.72
 Manager Addresses:
  10.43.106.72:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-151-generic
Operating System: elementary OS 0.4.1 Loki
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.67GiB
Name: mootleberry
ID: DVYX:LEUX:EU5N:GEUC:JEJR:DZW3:5FPU:54QF:TWTM:RKB2:MYJD:YWI6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: wheelybird
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
All environments.

**Comment by thaJeztah** [comment] 2019-07-14 10:16
Thanks for reporting; looks like this is a duplicate of https://github.com/moby/moby/issues/34654, which is being worked on in https://github.com/moby/moby/pull/37872

There's also an "epic" to track features not (yet) supported for swarm services; https://github.com/moby/moby/issues/25303

I'll close this one because of the above, but feel free to continue the conversation if I closed this in error

**Closed by thaJeztah** 2019-07-14 10:16 UTC
Labels: area/swarm, kind/enhancement
