### ISSUE TITLE
No commands can clean up /var/lib/docker/aufs/diff

### ISSUE THREAD

**Issue by jmikkola** [moby/moby#37724] opened 2018-08-28 00:07 UTC
**Description**

`/var/lib/docker/aufs/diff` consumes 39G of space, as reported by `du -sh`.

Commands to clear out docker containers like `docker system prune -af` do not reduce the size of this directory.

**Steps to reproduce the issue:**
1. Use docker for a while
2. Watch disks slowly fill up

**Describe the results you received:**

`docker system prune -af` prints `Total reclaimed space: 0B`

**Describe the results you expected:**

`/var/lib/docker/aufs/diff` to reduce in size.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 961
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 3.16.0-6-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 36
Total Memory: 59.09GiB
Name: production-jenkins-agent-010
ID: PP2U:LM5Y:PYCX:MXUS:F5JU:HGQF:TC6G:F7S2:7IVT:3FVR:JEIW:5E6D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is running on an instance in AWS.

**Comment by Blasterdick** [comment] 2019-03-20 12:51
@jmikkola were you able to resolve this? If so, how? And what was the root cause? Thanks in advance.

**Comment by monteno-m** [comment] 2019-04-02 03:50
@jmikkola Any update on this or how you solved it?

**Comment by serban-sre** [comment] 2020-01-30 07:33
Here it works, although the `Total reclaimed space: 2.522GB` reported is not accurate. Before the docker `system prune -af` I had around 22GB in the `/var/lib/docker/aufs/diff`

```
test-VirtualBox diff # docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:39 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:27:01 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

>

**Comment by richfromm** [comment] 2021-04-16 00:17
Fwiw, my system was full, with 30.4 GB in `/var/lib/docker/aufs/diff`, and `docker image prune --all` and `docker volume prune` had been no help to me.

I tried `docker system prune --all --force --volumes`, as suggested at https://github.com/moby/moby/issues/21925#issuecomment-629982899 , and it freed up 31.1 GB

**Comment by thaJeztah** [comment] 2023-04-20 23:56
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS

**Closed by thaJeztah** 2023-04-20 23:56 UTC
Labels: area/storage/aufs
