### ISSUE TITLE
what the means of BLOCK I/O

### ISSUE THREAD

**Issue by ZhiqinYang** [moby/moby#35130] opened 2017-10-09 02:18 UTC
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
225cdf4609a3        9.76%               102.2 MiB / 762.9 MiB   13.39%              0 B / 0 B           12.5 MB / 0 B       43
 
anybody help? what the means of BLOCK IO? 
I run cadivor in docker, I saw it grow up to 10G and the cadvisor can't works!

**Comment by thaJeztah** [comment] 2017-10-09 15:34
That column refers to the amount of data that the container wrote/read to block devices in the that particular timeframe (1 second); see http://researcher.ibm.com/researcher/files/il-AVISHAY/01-block_io-v1.3.pdf, https://www.linux.com/blog/linux-block-io-tracing

I see the documentation is a bit sparse on this (https://docs.docker.com/engine/reference/commandline/stats/#options), so if you think the documentation should be improved, please open an issue in the documentation issue tracker; https://github.com/docker/docker.github.io/issues

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-09 15:34 UTC
Labels: kind/question
