### ISSUE TITLE
Client too new error with swarm API V1.27

### ISSUE THREAD

**Issue by sarunac** [moby/moby#32746] opened 2017-04-20 18:21 UTC
Hi,
I have the following docker environment. It runs UCP2.1.1.

Docker version:
Client:
 Version:      1.13.1-cs3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   95c9d22
 Built:        Thu Mar 30 20:09:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1-cs3
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   95c9d22
 Built:        Thu Mar 30 20:09:37 2017
 OS/Arch:      linux/amd64
 Experimental: false

I have downloaded the client certificate bundle from UCP Web interface and I use it with my API calls,

When I run a api call to retrieve tasks or nodes as shown below, I get the following error,
 # /usr/bin/curl --cert cert.pem --key key.pem --cacert ca.pem https://<swarmip:port>/v1.27/tasks
your client is too new (API version 1.27). The newest supported API version is 1.26.0

Here is the docker info details,

#docker info
Containers: 22
 Running: 12
 Paused: 0
 Stopped: 10
Images: 56
Server Version: 1.13.1-cs3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 391
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 95sxtijlsc34zg249lut2x1hi
 Is Manager: true
 ClusterID: 57sgghalus2ouuzusdf1u1mj7
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  External CAs:
    cfssl: https://<swarmp-ip>:12381/api/v1/cfssl/sign
 Node Address: <swarmp-ip>
 Manager Addresses:
  <swarmp-ip>:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.89 GiB
Name: r18-u34-svr1
ID: C5EV:LXD6:YSYP:IXB3:FZKH:RKZJ:5OYS:SDSN:RRAK:FD3G:IHAK:FJJT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: <username>
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

However if I back tag the version v1.26 and run it, I can retrieve the task and node details.

Is this the expected behavior? Are the /tasks and /nodes endpoint supported on v1.27 ?

**Comment by thaJeztah** [comment] 2017-09-17 17:50
Those endpoints are supported, but may have a different response, or support different options in newer versions of docker (and the API). Docker 1.13.1 supports up until API 1.26; a matrix showing which API version matches which version of Docker can be found in the API reference https://docs.docker.com/engine/api/v1.31/#section/Versioning

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-09-17 17:50 UTC
Labels: version/1.13
