### ISSUE TITLE
Docker beta17 for Mac, com.docker.hyperkit crashing   

### ISSUE THREAD

**Issue by webts** [moby/moby#24320] opened 2016-07-05 05:57 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Wed Jun 29 10:03:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 16
 Running: 6
 Paused: 0
 Stopped: 10
Images: 38
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 235
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: QITI:OSYJ:75MS:AAS7:57WF:4OCH:Y6WF:77WU:FG4C:KZU3:5MMG:5X7Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 77
 System Time: 2016-07-05T05:48:44.197722916Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: ******
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
Unsure of exact steps to reproduce, I believe it happens when container is doing heavy processing 

**Describe the results you received:**
Docker crashes, Mac OS dialog appears with crash report
Docker reboots  

**Additional information you deem important (e.g. issue happens only occasionally):**
has been happening since beta15
see file bellow
[docker-crash.docx](https://github.com/docker/docker/files/347139/docker-crash.docx)

**Comment by justincormack** [comment] 2016-07-05 08:56
Hi, there are some known issues which will be fixed in the release that will be out shortly, but if you do not have a way to reproduce it is hard to specifically work on this issue, but we do try to do load tests and see if we can reproduce similar crashes. The crash dump looks interesting though, will take look.

**Comment by webts** [comment] 2016-07-07 00:54
thanks, will continue to try and get exact steps to reproduce and will let you know if the next version improves the issue.

**Comment by thaJeztah** [comment] 2023-04-21 00:31
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-04-21 00:31 UTC
Labels: version/1.12, platform/desktop
