### ISSUE TITLE
Feature: log-driver json-file with log-opt tag and contextual parsing of labels/envs

### ISSUE THREAD

**Issue by ajohnstone** [moby/moby#19803] opened 2016-01-28 12:08 UTC
--log-opt tag="{{.ImageName}}/{{.Name}}/{{.ID}}" is not supported by  log-driver json-file.
Ideally the behaviour should be consistent between all drivers. Additionally the "log-opt label" and "log-opt env" do not seem to parse the labels and/or env.

E.g.

```
$ sudo docker daemon -D  --log-driver=json-file --log-opt labels="com.photobox.full"

$ docker run --label="com.photobox.full={{.ImageName}}/{{.Name}}/{{.ID}}" -it ubuntu bash -c "echo ${RANDOM}"

$ cat /var/lib/docker/containers/7a821670f0c2147d2040888652f6155a09560d219de2520ce046bbd88a8c1e50/*.log
{"log":"\u001b]0;root@7a821670f0c2: /\u0007root@7a821670f0c2:/# echo $RANDOM\r\n","stream":"stdout","attrs":{"com.photobox.full":"{{.ImageName}}/{{.Name}}/{{.ID}}"},"time":"2016-01-28T11:39:43.824583496Z"}
{"log":"12186\r\n","stream":"stdout","attrs":{"com.photobox.full":"{{.ImageName}}/{{.Name}}/{{.ID}}"},"time":"2016-01-28T11:39:43.824700942Z"}

```

This would help with things like amazon ecs that controls the launching of docker containers.

```
docker version; docker info
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
Containers: 29
Images: 1473
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1535
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-39-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 7.682 GiB
Name: andrew-office
ID: VRUJ:C7UG:LKAO:Q7AG:U3KK:SYDQ:GUUO:BC5C:2MWG:5LZS:H6ZK:FPXZ
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 25
 System Time: 2016-01-28T12:41:11.380077965Z
 EventsListeners: 0
 Init SHA1: 6bd1e8a0cd16ab554af196c6ab421437489d902f
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

**Comment by addykim** [comment] 2016-01-28 17:57
Agreed. It also seems that syslog and fluentd has a similar feature already, so why not the default JSON-file loggger. 

In my use case I'm having a log forwarder read from /var/lib/docker/containers/*/*-json.log and it's not helpful to have the logs and the container ID but not the container name. Maybe there's a better way to do it but the other options such as syslog and fluentd means you don't have access to the logs via `docker-compose logs [container-name]`.

**Comment by ajohnstone** [comment] 2016-01-28 22:33
Just to clarify my use case, it is the same as @addykim, thus raising this ticket.

1. Amazon ECS agent adds docker container labels to each container launched.
  * com.amazonaws.ecs.task-arn
  * com.amazonaws.ecs.container-name
  * com.amazonaws.ecs.task-definition-family
  * com.amazonaws.ecs.task-definition-version
2. I've customised the docker daemon to log specific labels (https://gist.github.com/ajohnstone/219a2e2699f1f1c3256c).
3. File beats ships the docker logs from within a container with access to the logs to logstash over tcp. (https://www.elastic.co/products/beats/filebeat)
4. Logstash filters the input, remapping the fields appropriately. E.g. https://gist.github.com/ajohnstone/655fd2dbf59339c7484a
5. Additional fields at the instance level are added at the filbeats shipper for each instance.

**Comment by youngpm** [comment] 2016-05-10 00:30
I can second that it is inconvenient that the json driver doesn't support tags; would make filebeat much more useful!

**Comment by jessesuen** [comment] 2016-05-25 08:23
I was surprised to learn json-file did not not support tags. I was planning to feed /var/lib/containers/*/*-json.logs to ELK, but without container names, json-file is not useful. Switching the log driver to something else, loses our ability to perform 'docker logs' and is pretty annoying.

**Comment by thaJeztah** [comment] 2016-05-25 14:23
Part of this (option to include environment-variables and labels) has been implemented in https://github.com/docker/docker/pull/21889, and will be in the next (1.12) release. There's no `--log-opt tag=` option yet.

**Comment by paltryeffort** [comment] 2016-11-07 09:49
Any updates to this? Docker 1.12.2 still doesn't support tags for json-file and vars like {{.Name}} are still not parsed when used in labels.

**Comment by thaJeztah** [comment] 2016-11-07 10:46
@paltryeffort I don't think I've seen someone opening a pull request / contribution to implement this, but contributions are welcome. Templating features for "swarm mode" is being worked on in https://github.com/docker/docker/pull/28025

**Comment by yeruisen** [comment] 2016-11-17 07:18
It is essential that this feature can implemented without delay.

**Comment by bitsofinfo** [comment] 2016-11-17 16:15
+1

**Comment by nfedyk** [comment] 2016-11-17 17:06
+1

**Comment by ripcurld00d** [comment] 2016-11-17 19:08
#dibs

**Comment by ripcurld0** [comment] 2017-02-13 18:49
@thaJeztah @stevvooe 
what should we do with this issue?

**Comment by stevvooe** [comment] 2017-02-14 02:16
@ripcurld0 No clue. I cannot tell what the actual proposal is or the problem that is trying to be solved nor am I understanding why https://gist.github.com/ajohnstone/219a2e2699f1f1c3256c is insufficient. Perhaps, I am lost of the term "tag", since what I am seeing presented here isn't an image tag.

Is the goal to add contextual templating to the log message output?

It would be good to provide some indication of the scope of the feature and what it does before embarking.

**Comment by ripcurld0** [comment] 2017-02-14 07:34
I guess since there is not enough information and since this ticket is more than 1 year old, we should close it.
WDYT?

**Comment by ajohnstone** [comment] 2017-02-14 08:31
The behaviour at the time I wrote this was that the log-opt-tag was not consistent between all log drivers. And that it does not work with json-file.

So the request was:

Make consistent with log-file so that it is consistent with other logging drivers.

I'm unsure if it has been solved since I wrote the ticket.

The context being was to add metadata to the logs with contextual information.

the ticket is old and I currently solve in a different way

**Comment by paltryeffort** [comment] 2017-02-14 09:13
Please don't close this issue. I'd like to use tags for json-file output. I can't use labels because vars like {{.Name}} are not parsed. I'd like to use the json-file driver like this documentation suggests:

https://docs.docker.com/engine/admin/logging/log_tags/

**Comment by thaJeztah** [comment] 2017-02-14 21:42
@paltryeffort can you describe how you're consuming the logs? Are you using `docker logs` or interacting directly with the json-log files that are written in `/var/lib/docker` ?

What's your expectation of this feature? Would you be able to describe a bit more in depth what your use-case looks like?

**Comment by youngpm** [comment] 2017-02-14 23:00
@thaJeztah One use case is around what is mentioned above at https://github.com/docker/docker/issues/19803#issuecomment-176456217; if you're running containers on some host and using the json-log driver, you can use [filebeat](https://www.elastic.co/products/beats/filebeat) to watch the logs in `/var/lib/docker` and forward them on to the rest of the elastic stack.  

Tags would be quite nice to have as they let you add more information to the json blobs that are being forwarded along, e.g. add a tag for `staging` or `production` and so on.

**Comment by stevvooe** [comment] 2017-02-16 03:14
So, the https://docs.docker.com/engine/admin/logging/log_tags/ describes a feature called "Log Tags" (sorry, really had never heard of this) but the json-log driver doesn't not implement this?

That sounds like a reasonable feature request.

As aside, what was confusing here is the the original feature request showed some arbitrary propagation of a label, rather than the tag example from the documentation. It looks like `tag` is a logging option that is implemented and propagated on a per driver basis, include the propagation of the template context in the logger. That "Log Tags" doc was really enlightening!

@thaJeztah Is there a reason this _wasn't_ implemented before? We do need to be careful not to introduce a feature that requires a template evaluation for every log message. From what I can see in the docs, it looks like this can be calculated once on container creation and propagated from there.

**Comment by thaJeztah** [comment] 2017-02-23 20:57
@stevvooe my assumption is that it wasn't implemented because the json-file logging driver doesn't really have features to use it by itself; basically the actual files are stored inside `/var/lib/docker` and anything inside that should be considered exclusive access for the docker daemon.

**Comment by jmreicha** [comment] 2017-03-15 22:17
Any update on this?

**Comment by ripcurld0** [comment] 2017-03-15 22:40
@jmreicha @thaJeztah @stevvooe there is my closed PR https://github.com/docker/docker/pull/28669
Let me know if it's still relevant. I guess I will have to rebase but it's not a problem.

**Comment by bonczj** [comment] 2017-04-27 13:20
I am also interested in the status of this. It would help simplify my deployment stack. One of our goals is to ensure we can always use the 'docker logs' and 'docker-compose logs' commands to quickly view what is happening with a given container or set of containers. For this, we need to continue to use the json-file logger. I will note that we are still on 1.12.x for compatibility reasons.

Part of the problem is an open source ecosystem that is constantly evolving. At least in my case, the end goal is to have all of the docker logs available in Elasticsearch and viewable through Kibana. An interesting note is that in more recent versions of ES + Kibana, each service now requires basic authentication.

### Option 1 - filebeat
Filebeat can be installed on the docker host and can be configured to read the log files from /var/lib/docker/containers/*/*-json.log.  I have configured filebeat to write directly to ES and the information is available in Kibana. As noted above, only the container ID is available which limits the usefulness of this approach.

### Option 2 - fluentbit + files
Fluentbit is a lightweight version of Fluentd. It can be configured on the docker host to read the container log files and write to Elasticsearch. Note, that in the latest version of Fluentbit, it cannot write to the latest Elasticsearch + Kibana as it does not yet support the authentication. An issue was opened for this recently. Even once working, I suspect this will have the same problem with only the container ID being available in the search results.

### Option 3 - fluentbit + fluentd log driver
This breaks our desire to be able to use the 'docker logs' command. It is usable in that the resulting entries in Elasticsearch do container the container name. This works well with older versions of ES + Kibana that do not require authentication at least until the opened feature/issue has been resolved.


There are other options, but from what I'm seeing so far, we end up with at least one of the following problems.

- Cannot use 'docker logs' command
- Cannot see the container name in the resultant search in ES + Kibana

Really, the only way I have see so far to allow both of the above is for the docker daemon to support the --log-opt tag='{{.Name}}' option (both from CLI and configuration file).

**Comment by bonczj** [comment] 2017-04-27 13:58
There is an alternative to updating the json-file log driver, but I don't think it would work out well. The alternative would be to allow us to define multiple log drivers. Then we could define a json-file logger so that 'docker logs' still works and also send a copy of each log over one of the protocol-based drivers such as fluentd where the container name is already supplied.

This has the side effect of increasing processing and memory in the docker daemon, which I would suggest should be avoided. I did not say it was a good alternative.

**Comment by bonczj** [comment] 2017-04-27 16:01
I am seeing a surprising lack of consistency between the log drivers while they are being initialized. I thought about just creating a PR to resolve the problem. I read through the PR from @ripcurld0 and also several other drivers. I think the change could be simplified and actually be more consistent with the gelf, journald and fluentd drivers.

In the constructor for several of the other drivers, container information is being retrieved. An example of this would be https://github.com/moby/moby/blob/master/daemon/logger/gelf/gelf.go, line #62. A different implementation for only ContainerID is seen in https://github.com/moby/moby/blob/master/daemon/logger/fluentd/fluentd.go, line #131. 

In both cases, container specific information is grabbed in the constructed and then added to the logging subsystem so that it can be used by whoever is going to parse those logs. At first glance, it appears that a similar mechanism could be used in the json-file logger and would actually avoid the need for the (confusing) --log-opt tags= option.

**Comment by olivibernard** [comment] 2017-04-28 09:42
@bonczj I have the exact same problem. I really need it.

**Comment by bonczj** [comment] 2017-04-28 21:47
I am working on a PR for it. I'll have to continue fighting with github on why even after I add my public cert and sign the commit, the commit is still listed as unverified. That will be a battle for early next week.

If anyone is interested in seeing what I have done, it is under PR #32926.

**Comment by bonczj** [comment] 2017-05-18 16:41
And update to my last comment. The particular change I have made is more feature enhancement than defect, so I will not be able to get it to merge to the 1.12.x line.

I will work on a similar change against master which then has a chance of making it a new release going forward.

**Comment by Evertvz** [comment] 2017-07-07 13:58
Hello @bonczj 

Thank you for your efforts on this. Can you share a new PR link for the master branch part?

**Comment by bonczj** [comment] 2017-07-12 13:19
@Evertvz Thank you for the reminder. Work picked back up for awhile, but I'm back looking at implementing on master. I've narrowed the extra data that will be logged to just the ContainerID and ContainerName to keep the size of the logs down a bit.

**Comment by bonczj** [comment] 2017-07-12 14:15
If any of the log maintainers are watching (and everyone else), I have a few options and would appreciate input. For anyone interested, Option 1 is written and I'm updating the various tests. Options 2 and 3 require a few more changes, but nothing that appears to be too drastic.

**Option 1** - Include ContainerID/ContainerName as extra attributes
This option is straight forward to implement as well as consume. Every JSON log entry would contain both the ContainerID and ContainerName. This does consume a bit more disk space. A downside is that the ContainerID/ContainerName are part of the attrs section of the log entry.

Example: {"log":"line1\n","stream":"src1",**"attrs":{"_container_id":"a7317399f3f857173c6179d44823594f8294678dea9999662e5c625b5a1c7657","_container_name":"test-container"}**,"time":"0001-01-01T00:00:00Z"}

Option 2 - Include ContainerID and ContainerName as top level attributes
This option would be very similar to Option 1. The main difference is that the new data would not be part of the attrs object in the log statement.

Example: {"log":"line1\n","stream":"src1",**"_container_id":"a7317399f3f857173c6179d44823594f8294678dea9999662e5c625b5a1c7657","_container_name":"test-container"**,"time":"0001-01-01T00:00:00Z"}

Option 3 - Utilize the log tag configuration to define values to log
Currently the JSON logger does not parse the tag values (see loggerutils.ParseLogTag). This option allows the operator to define the attributes that they want to have logged and would not enforce the containerName is logged for everyone. The default tag format would log the containerID still.  Going this route, the output would likely look something like Option 2.

**Comment by ElMoselYEE** [comment] 2017-07-12 14:59
As a consumer, my vote is Option 3 as it's consistent with other log drivers and the most flexible so users get only what they want.

**Comment by bonczj** [comment] 2017-07-12 17:19
I tend to agree @ElMoselYEE . I'll stash what I have and move to the tag based approach.

**Comment by bonczj** [comment] 2017-07-12 19:50
The tag-based solution is pretty straight forward. If you do not specify a tag (default), then there is no change to the data format. Only if you specify a [log tag](https://docs.docker.com/engine/admin/logging/log_tags/) will the JSON log file change to include tag information.

To give an example, if you specify a log tag of "_{{.ID}}/{{.Name}}_", then the output will look something like the following. This from from a unit test and the only new item is the tag attribute which contains the ContainerID (first 12 characters) and ContainerName.

`{"log":"line2\n","stream":"src2","tag":"a7317399f3f8/test-container","time":"0001-01-01T00:00:00Z"}
`

I do not intend to have the tag value displayed as part of the docker logs command. It requires a container ID already, so anything in the tag would be readily available from other docker CLI commands for that container.

**Comment by michaelburn** [comment] 2017-10-19 09:42
Any Update on this? I also need this feature as described by bonczj.

My Usecase is consuming the container-logs by filebeat. I'm not able to use other log-drivers because the receiver runs in containers and should consume it's own logfiles.

**Comment by nsaud01** [comment] 2017-11-03 20:22
+1000

**Closed** 2018-01-22 23:02 UTC
Labels: area/logging, kind/enhancement, status/claimed, version/1.9
