### ISSUE TITLE
Default Docker Log File Directory in Mac

### ISSUE THREAD

**Issue by linyuadam** [moby/moby#34349] opened 2017-08-01 06:44 UTC
What is the default Docker log file directory in Mac? My Mac does not have /var/lib/docker directory

**Comment by thaJeztah** [comment] 2017-08-01 19:01
On Docker for Mac, the daemon runs in a very thin virtual machine. The logs are stored inside that machine.

If you want to access the daemon logs, you can bind-mount the `/var/log` directory in a container, e.g.;


```
docker run -it --rm -v /var/log:/var/log alpine sh
```

And inside the container;

```
tail -f /var/log/docker.log
```

To get container logs, just use the `docker logs` command

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-08-01 19:01 UTC
