### ISSUE TITLE
docker start <container_name> returns "container <hash> already exists"

### ISSUE THREAD

**Issue by mbonaci** [moby/moby#36145] opened 2018-01-30 14:53 UTC
**Description**
`docker start` returns `Error response from daemon: container <hash>: already exists`
This happened after I installed the latest upgrade.
The only other change I did was to remove check from "Enable kubernetes" and apply that change (from docker preferences window).

**Describe the results you received:**
```
dps -a
IMAGE                                                 NAMES                PORTS                                            COMMAND                  STATUS
jetty                                                 infallible_hodgkin                                                    "/docker-entrypoint.…"   Exited (0) 2 weeks ago
jetty                                                 gallant_perlman                                                       "/docker-entrypoint.…"   Exited (1) 2 weeks ago
docker.elastic.co/elasticsearch/elasticsearch:5.6.3   st-es                0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   "/bin/bash bin/es-do…"   Exited (255) 18 minutes ago
appbaseio/mirage                                      mystifying_meitner   0.0.0.0:3030->3030/tcp                           "http-server '-p 303…"   Exited (255) 2 months ago
appbaseio/dejavu                                      heuristic_jones      0.0.0.0:1358->1358/tcp                           "http-server '-p 135…"   Exited (255) 2 months ago
mongo                                                 mongo                0.0.0.0:27017->27017/tcp                         "docker-entrypoint.s…"   Exited (255) 5 weeks ago
zookeeper                                             st-zk                2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp       "/docker-entrypoint.…"   Exited (255) 18 minutes ago
mysql:5.5                                             st-mysql             0.0.0.0:3306->3306/tcp                           "docker-entrypoint.s…"   Exited (255) 18 minutes ago
% 
% 
% docker start st-mysql
Error response from daemon: container "fa0db3388ad6eb043d8632039c152f58afb68dbb6a2c5a3a7721420a56518477": already exists
Error: failed to start containers: st-mysql
```
**Output of `docker version`:**

```
Client:
 Version:	18.02.0-ce-rc1
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	5e1d90a
 Built:	Thu Jan 25 00:33:50 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce-rc1
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	5e1d90a
  Built:	Thu Jan 25 00:40:43 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 32
Server Version: 18.02.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 157
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: TLZO:G2VR:E4RK:4L5T:7QZ3:56R3:WSBW:Z7XW:LQMW:AXRE:5QZU:Z3HA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 45
 System Time: 2018-01-30T14:51:16.971310166Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by john3exonets** [comment] 2018-01-30 15:07
+1   ...and my ``docker version`` command has the same output.

**Comment by john3exonets** [comment] 2018-01-30 15:32
it also won't let me run a new container either.  It pulls the image down, gives no errors, but doesn't start it.  If I try to start it with ``docker start {name}``  it returns the container name like it started it, but a ``docker ps`` shows it not running.  A ``docker ps -a`` shows that the container ran for a few seconds, but exited.  A ``docker logs {name}`` of the new app shows no output. A ``docker logs {old container name}`` shows some weird errors -- and a change to the log format:

```
[ 2018-01-25 13:57:17.4652 46/7fd366ee5780 agents/HelperAgent/Main.cpp:643 ]: PassengerHelperAgent online, listening at unix:/tmp/passenger.1.0.22/generation-175/request
[ 2018-01-25 13:57:17.4738 51/7fb1159d3780 agents/LoggingAgent/Main.cpp:321 ]: PassengerLoggingAgent online, listening at unix:/tmp/passenger.1.0.22/generation-175/logging
[ 2018-01-25 13:57:17.4741 43/7f026fcef780 agents/Watchdog/Main.cpp:728 ]: All Phusion Passenger agents started!
[Thu Jan 25 13:57:17.475279 2018] [mpm_event:notice] [pid 22:tid 140059055343488] AH00489: Apache/2.4.7 (Ubuntu) Phusion_Passenger/4.0.37 configured -- resuming normal operations
[Thu Jan 25 13:57:17.475427 2018] [core:notice] [pid 22:tid 140059055343488] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
App 128 stdout:
App 128 stderr: /usr/bin/env: python: No such file or directory
[ 2018-01-26 01:39:16.0911 46/7fd366dee700 Pool2/SmartSpawner.h:301 ]: Preloader for /var/www/tracks started on PID 128, listening on unix:/tmp/passenger.1.0.22/generation-175/backends/preloader.128
App 145 stdout:
App 152 stdout:
[ 2018-01-27 15:25:55.6608 51/7fb1159d3780 agents/LoggingAgent/Main.cpp:289 ]: Caught signal, exiting...
```

You can see right when the update happened, as the timestamp format changed.  The Ruby app I was running (Tracks) now starts to complain about Python (??) and gets a signal to stop.  The ``SmartSpawner`` log record is also new.

**Comment by cpuguy83** [comment] 2018-01-30 16:14
@john3exonets Was docker properly shutdown when you upgraded?
What version did you upgrade from?

**Comment by mbonaci** [comment] 2018-01-30 17:12
I think I upgraded from the latest version before this one (if I remember correctly, the latest upgrade I did was week or 2 ago). 
Same as @john3exonets, I can also confirm that all containers that were stopped at the time of upgrade work fine and all that were started have this issue.

> Was docker properly shutdown when you upgraded?

Docker prompted me to upgrade and I said yes in that dialog and the rest was done by Docker.

**Comment by john3exonets** [comment] 2018-01-30 18:21
@cpuguy83 As far as I know....It said it was shutting it down to do the upgrade, so I didn't really think about it.

**Comment by cpuguy83** [comment] 2018-01-30 18:22
OK, so this is all docker4mac?

**Comment by john3exonets** [comment] 2018-01-30 18:22
Correct

**Comment by cpuguy83** [comment] 2018-01-30 22:23
Ok, I'm investigating a number of cases where this can happen.

The main issue comes down to the fact that in the pre-1.0 containerd API, a container `Create` API request would actually run the container.
With containerd 1.0, there are two layers of abstraction
1. The container object, which is metadata
2. The task object which is the runtime state of a container

To simplify integration with containerd 1.0, docker is not currently using the container object/metadata stuff and basically just deletes the container from containerd when the container is stopped/exits/whatever.

So it seems in some case (or cases) moby is not able to cleanup the container object from containerd.
Most likely this is incorrect error handling in moby.

**Comment by rastographics** [comment] 2018-01-30 23:39
This may help shed light...
I came across this issue today.

Installed Docker on a Windows 10 machine that has never had docker before.

Version 18.02.0-ce-rc1 (Edge channel)

Running this command:
`docker run -d --hostname my-rabbit --name super-rabbit -p 8090:15672 -p 8091:5672 rabbitmq:3-management`

If I stop the docker service, or restart my computer, or stop the container manually, it is impossible to get it started again.

`docker start super-rabbit` always give this error:
`Error response from daemon: container "<containerId>: already exists" Error failed to start containers:`

**Comment by achimnol** [comment] 2018-01-31 07:04
Another bump here!
I got the same issue with the exactly same version of Docker for Mac (git commit 5e1d90a).
Strangely, some of my containers starts fine, but others don't, regardless of which docker-compose configuration they belong to.
I have enabled Kubernetes support and no other kubernetes contexts on the system.

**Comment by CageFox** [comment] 2018-01-31 09:03
Same issue with new version on mac

**Comment by issei-m** [comment] 2018-02-01 14:52
Same issue here:

```
$ docker ps -a 

CONTAINER ID    IMAGE        COMMAND             CREATED        STATUS                         PORTS                                       NAMES
xxxxxxxxx       foo_image    "/entrypoint.py"    7 hours ago    Exited (255) 54 seconds ago    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp    foo-container
```

then:

```
$ docker start xxxxxxxxx
Error response from daemon: container "xxxxxxxxx...": already exists
Error: failed to start containers: foo-container
```

**Comment by john3exonets** [comment] 2018-02-01 15:08
Does anyone have the build number of the previous release, so we could at least (in theory) rollback to that version and keep working??

**Comment by rastographics** [comment] 2018-02-01 17:50
@john3exonets I completely uninstalled docker (edge channel) and installed the latest Stable channel version 17.12.0-ce and this issue has gone away for me. I'm on Windows 10.

**Comment by esavich** [comment] 2018-02-03 05:04
same issue wit docker4mac
```
▶ docker -v
Docker version 18.02.0-ce-rc1, build 5e1d90a
```
```
▶ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS                      NAMES
ec0c7d0409d6        memcached:alpine    "docker-entrypoint.s…"   4 days ago          Exited (255) 2 days ago   0.0.0.0:11211->11211/tcp   my-memcache
298ff55e4058        redis:alpine        "docker-entrypoint.s…"   4 days ago          Exited (255) 2 days ago   0.0.0.0:6379->6379/tcp     my-redis

~
▶ docker start my-memcache
Error response from daemon: container "ec0c7d0409d613549a1afcb7491cd75667aca7f7eb04deeaab7407c90ef0af87": already exists
Error: failed to start containers: my-memcache

~                                                                                                                                                                   ⍉
▶ docker start my-redis
Error response from daemon: container "298ff55e4058ef157c8e865122de28c738787e2ebe5a39dbd26a2302b5b76f49": already exists
Error: failed to start containers: my-redis
```

**Comment by achimnol** [comment] 2018-02-03 09:55
Yeah, I also rolled back to the stable channel after resetting everything. No more this issue there, but I lost the experimental kubernetes cluster...

**Comment by john3exonets** [comment] 2018-02-03 20:41
Latest edge channel version (Version 18.02.0-ce-rc2-mac51 (22446)) has the same issue.

**Comment by mryusazeeme** [comment] 2018-02-04 06:58
I have the same issue today after i upgrade to the latest Docker version 18.02.0-ce-rc2, build f968a2c.
I'm using Fedora 27. 
Any workaround to solve this?

**Comment by cmilanf** [comment] 2018-02-04 14:18
Same issue here, I have Kubernetes enabled.

```
Client:
 Version:       18.02.0-ce-rc2
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    f968a2c
 Built: Thu Feb  1 00:03:45 2018
 OS/Arch:       windows/amd64
 Experimental:  true
 Orchestrator:  kubernetes

Server:
 Engine:
  Version:      18.02.0-ce-rc2
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   f968a2c
  Built:        Thu Feb  1 00:10:36 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by john3exonets** [comment] 2018-02-04 15:18
FYI for those looking to rollback:  If you know the build number of the release you want to roll back to....and don't have the file in your 'Downloads'....you can always just download a prior release -- if you know the build number.  

For me this was '18.01.0-cd-mac48 (22026)' (the version I was running before the upgrade introduced this bug), so the URL to re-download was:
```
https://download.docker.com/mac/edge/22026/Docker.dmg
```
You can replace ``edge`` with ``stable`` to get access to the Stable builds.

Stop Docker if it is currently running, and just install over it....everything is working again for me.  I'll run this version until I see that this bug has been fixed.  I wrote a quick bash script, based on another Github issue about accessing older build, to surf the download server for available builds and print them out. PM me if you are interested in a copy.

**Comment by vvoody** [comment] 2018-02-05 06:21
Rollback to build 22026, 22256 not work. Finally, first edge build with Kubernetes `21669` saves me.

https://download.docker.com/mac/edge/21669/Docker.dmg

**Comment by djl394922860** [comment] 2018-02-05 08:15
QAQ，Same issue here,i do not want to rm those containers.....What am I supposed to do? 

[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                        PORTS                    NAMES
ac69cf988335        portainer/portainer   "/portainer"             44 hours ago        Exited (255) 18 minutes ago   0.0.0.0:9002->9000/tcp   upbeat_chatterjee
8ba0cb8b2471        webapi                "dotnet run"             2 days ago          Exited (255) 18 minutes ago   0.0.0.0:12345->80/tcp    webapi
9c1312852573        blog                  "dotnet BlogFuck.dll"    2 days ago          Exited (255) 18 minutes ago   0.0.0.0:9001->80/tcp     blog
7a3226bc3dc7        video                 "dotnet VideoFuck.dll"   2 days ago          Exited (255) 18 minutes ago   0.0.0.0:9000->80/tcp     video

[root@localhost ~]# docker container start blog
Error response from daemon: container "9c1312852573ecd1dbf6e5e9c57a3d9b3eabc3c5714bde863ffcfcbb55dc9f99": already exists
Error: failed to start containers: blog

[root@localhost ~]# docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 45
Server Version: 18.02.0-ce-rc2
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.686GiB
Name: localhost.localdomain
ID: DHJ5:NBEK:CKUF:VBRK:2E76:RYSW:5H7V:7NKH:B5JZ:3UXR:YWI5:OOGP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://v3pmkic6.mirror.aliyuncs.com/
Live Restore Enabled: false

**Comment by vvoody** [comment] 2018-02-05 08:25
@djl394922860 Hi, try to reinstall older build of Docker for Mac. For me, only 21669 fixes.

https://download.docker.com/mac/edge/22256/Docker.dmg
https://download.docker.com/mac/edge/22026/Docker.dmg
https://download.docker.com/mac/edge/21669/Docker.dmg

**Comment by ianzhengnan** [comment] 2018-02-05 08:46
I get same issue on my virtual machine Centos7.

Error response from daemon: container "120e8424d507b645fb99cb7e471f228bfbf754129a0340abfc0736e587e4fa24": already exists
Error: failed to start containers: mongodb


Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 4
Server Version: 18.02.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.631GiB
Name: localhost.localdomain
ID: FUXA:XIF5:GKUA:FZIC:EKWH:3YRV:7LUS:EWQU:3BKF:YTXH:B2QN:2EIP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by jamesfry** [comment] 2018-02-05 16:28
Same here with Version 18.02.0-ce-rc2-mac51 (22446).

When rolling back to Version 17.12.0-ce-mac45 (21669) attempting to start my container gave this error:

```
docker start <container-name>
Error response from daemon: id already in use
Error: failed to start containers: <container-name>
```

However, restarting the same container worked fine.

**Comment by onechillindude** [comment] 2018-02-05 17:42
I had the same problem with Version 18.02.0-ce-rc2-mac51 (22446).  Used advice from @john3exonets to roll back to Version 18.01.0-ce-mac48 (22026).  Everything appears to be working fine now.

**Comment by rexthk** [comment] 2018-02-07 05:51
I countered the same problem with 18.02.0-ce-rc2-mac51 (22446). I have to prune the container, and re-run it.

**Comment by Mobe91** [comment] 2018-02-07 09:50
For me it happens when I run `docker-compose start` or `docker-compose restart`.
```
Cannot restart container 684ff6ca43d9e6f5d7e59d35b1d1405333c148acde611a4029557774b1ce4e5a: container "684ff6ca43d9e6f5d7e59d35b1d1405333c148acde611a4029557774b1ce4e5a": already exists
Cannot restart container 1ae813e769085d2924b3683d20975df20364ee9f79f02e4ef45ab569b938d172: container "1ae813e769085d2924b3683d20975df20364ee9f79f02e4ef45ab569b938d172": already exists
Cannot restart container 0fb3485557f416bcb89a48c680f78858aced3adafb99d2722913def7407e5a45: container "0fb3485557f416bcb89a48c680f78858aced3adafb99d2722913def7407e5a45": already exists
Cannot restart container d49c2b7c1a2d49124e71088982b65fa01ad299602007f0b4c9978e765a347eac: container "d49c2b7c1a2d49124e71088982b65fa01ad299602007f0b4c9978e765a347eac": already exists
```

Container already exists? You don't say! That's why I want to start/restart it!

```
Client:
 Version:       18.02.0-ce-rc1
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    5e1d90a
 Built: Thu Jan 25 00:34:00 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce-rc1
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   5e1d90a
  Built:        Thu Jan 25 00:40:43 2018
  OS/Arch:      linux/amd64
  Experimental: true

docker-compose version 1.18.0, build 8dd22a96
docker-py version: 2.6.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by Rid** [comment] 2018-02-07 13:57
Same issue here:

Ubuntu 17.10

```
Client:
 Version:	18.02.0-ce-rc2
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	f968a2c
 Built:	Thu Feb  1 00:07:51 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce-rc2
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	f968a2c
  Built:	Thu Feb  1 00:06:21 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by cpuguy83** [comment] 2018-02-08 16:01
One way I have found to reproduce this is:

1. Start daemon
2. run container `docker run -d --name test busybox top`
3. `kill -9 <dockerd pid>`
4. Kill container process and corresponding containerd-shim process
5. Start daemon
6. `docker start test`

This would conceivably be repro'd on a reboot where dockerd was not able to properly shutdown the container on exit.
The key here is that the process exits while dockerd is not processing events (i.e. when it's down) and the shim is also killed.

The one weird thing here is that it is strange that in d4mac it seems common that docker has not processed a container exit... assuming this is happening on shutdown but again I don't know why the container shutdown is not caught.

Unfortunately an automated test for this is not all that simple since it does require killing the containerd-shim.
I will work up a fix for this case and get it backported to 17.12.

I'm not sure that I could get something in time for the Docker 18.02 release...

**Comment by cpuguy83** [comment] 2018-02-08 19:17
Fixed in #36249

**Closed** 2018-02-12 10:36 UTC
Labels: area/runtime, kind/bug, platform/desktop, status/needs-attention

**Comment by funkyfuture** [comment] 2018-02-14 13:05
i'm not sure whether this is the same issue, but i'm experiencing this after an upgrade from `18.01.0-1` to `18.02.0-1` on Arch Linux and a following reboot for the first time.

**Comment by cpuguy83** [comment] 2018-02-15 14:50
@arnekick 
```
docker-containerd-ctr --namespace moby --address /run/docker/containerd/docker-containerd.sock c rm b62020cb44e1ed3307195ca4402cdf23ed817c35c52a30da858909398898c8b6
```

**Comment by arnekick** [comment] 2018-02-15 15:58
I get this as a response

bash: docker-containerd-ctr: command not found

**Comment by cpuguy83** [comment] 2018-02-15 16:06
@arnekick If you are on mac/windows you'll need to run that command in a container.

Should be able to do something like:

```
 docker run -it --rm -v /:/host alpine /host/usr/local/bin/docker-containerd-ctr  --namespace moby --address /host/run/docker/containerd/docker-containerd.sock c rm b62020cb44e1ed3307195ca4402cdf23ed817c35c52a30da858909398898c8b6
```

**Comment by arnekick** [comment] 2018-02-15 16:13
then i get this 
Unable to find image 'alpine:latest' locally

**Comment by rezrov** [comment] 2018-02-16 16:43
@cpuguy83 Thanks for that workaround, worked for me and saved me a lot of time.

@arnekick Perhaps you need to pull alpine:latest manually?

`docker pull alpine:latest`

**Comment by sleeyax** [comment] 2018-02-17 17:11
I was facing the same issue when I shut down my computer without stopping the running container correctly. I ran `docker rm <container>` before `docker run [OPTIONS] <image>` and then I was able to start and stop the container again. This whole 'problem' wasn't a thing in the previous version (v18.01.0-ce) though.

**Comment by Zelgadis87** [comment] 2018-02-25 10:00
@cpuguy83 On Windows, I get the following error when trying your workaround:

> docker run -it --rm -v /:/host alpine /host/usr/local/bin/docker-containerd-ctr  --namespace moby --address /host/run/docker/containerd/docker-containerd.sock c rm "11060259da8b94cca3b12289ec533c68e0af261e576ce91dbf39e172ec7ae20e"
>
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/host/usr/local/bin/docker-containerd-ctr\": stat /host/usr/local/bin/docker-containerd-ctr: no such file or directory": unknown.

Entering in the container with bash reveals that the host folder is indeed missing from container. I should probably mount a different folder on Windows, but I can't find the docker-container-ctr command anywhere.

Any help would be appreciated
Thanks

**Comment by cpuguy83** [comment] 2018-02-27 20:28
Thanks for the additional work-around, this is perfect.

**Comment by BransonGitomeh** [comment] 2018-02-27 22:09
i run protainer and manually delete the containers, worked

**Comment by chamav** [comment] 2018-03-10 16:03
my solution for all containers:
`docker-containerd-ctr --address /run/docker/containerd/docker-containerd.sock --namespace moby c rm $(docker ps -aq --no-trunc)`

**Comment by mribichich** [comment] 2018-03-15 15:59
In case someone is on CoreOS the workarounds didn't work for me.

I then realized that I had to changed the address to: `/run/docker/libcontainerd/docker-containerd.sock`

And since I didn't have `docker-containerd-ctr` and found `ctr` to work the same (maybe they are the same)

So I end up doing this: `sudo ctr --namespace moby --address /run/docker/libcontainerd/docker-containerd.sock c rm ...`

**Comment by nachopro** [comment] 2018-03-20 18:52
Hi, today after computer crashed my containers was never wake up again :(

```
$ sudo docker start dev-mysql dev-redis dev-rabbit
Error response from daemon: container "xxxxxxxxx": already exists
Error response from daemon: container "xxxxxxxxx": already exists
Error response from daemon: container "xxxxxxxxx": already exists
Error: failed to start containers: dev-mysql, dev-redis, dev-rabbit
```

I'm using Docker version 18.02.0-ce, build fc4de447b5 @ ArchLinux 1 mos ago without any problem.

Any suggestion is welcome;

**Comment by Trejjam** [comment] 2018-03-20 18:57
Rollback to 18.01 (or stable) and disable auto update in pacman/yaourt

**Comment by cpuguy83** [comment] 2018-03-20 19:05
@nachopro  There are several work-arounds posted in this issue.

**Comment by Eyshika** [comment] 2019-07-10 21:05
@cpuguy83 having same problem .. I stopped my docker container, then stopped service of aws and now when i do `docker ps -a` i dont see my container but it is still inside `/var/lib/docker/containers/`, how to fix it, how to get my data and container back ?

> P.S. am using AWS EC2 machine

**Comment by cpuguy83** [comment] 2019-07-10 21:18
@Eyshika Please make sure you are on a recent version of Docker. Also see the work-arounds posted above. The patch to fix this is in 18.09.3 and higher.

**Comment by Eyshika** [comment] 2019-07-10 21:22
@cpuguy83 yes i am using recent version and I tried your method posted above on doing `kill -9 docker pid` it gives error

**Comment by cpuguy83** [comment] 2019-07-10 21:26
@Eyshika What is the output of `docker version`? Also you probably need to use `sudo`

**Comment by cpuguy83** [comment] 2019-07-10 21:27
Sorry, the `kill -9` bit is for reproducing the problem, not how to work around it.

**Comment by Eyshika** [comment] 2019-07-10 21:27
@cpuguy83  Version:           18.06.1-ce

**Comment by cpuguy83** [comment] 2019-07-10 21:28
18.06 is older and does not have the fix.

**Comment by Eyshika** [comment] 2019-07-10 21:30
@cpuguy83 so there is no way i can get my container and data back ?

**Comment by cpuguy83** [comment] 2019-07-10 21:32
@Eyshika You can upgrade or you can do:

```
 docker run -it --rm -v /:/host alpine /host/usr/local/bin/docker-containerd-ctr  --namespace moby --address /host/run/docker/containerd/docker-containerd.sock c rm b62020cb44e1ed3307195ca4402cdf23ed817c35c52a30da858909398898c8b6
``` 
Where that long ID is the ID reported as already existing when you try to start the container.

**Comment by Eyshika** [comment] 2019-07-10 21:36
@cpuguy83 is host the name of host or complete id ? SInce my host is aws ec2

**Comment by cpuguy83** [comment] 2019-07-10 21:37
@Eyshika The only thing you should need to change is the ID at the very end.

**Comment by Eyshika** [comment] 2019-07-10 21:41
@cpuguy83 >docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/host/usr/local/bin/docker-containerd-ctr\": stat /host/usr/local/bin/docker-containerd-ctr: no such file or directory": unknown.

**Comment by cpuguy83** [comment] 2019-07-11 21:35
@Eyshika Well, the `docker run` command I gave you makes assumptions about where the `ctr` binary is. Please take my example and adapt to your system.

**Comment by fzhan** [comment] 2019-07-17 05:54
I'm upgrading from 18.06 to 18.09, this bug still exists.

`a43cef2cfbe7        70833a8f6da0        "/usr/sbin/init /usr…"   7 weeks ago         Exited (255) 24 hours ago `

`docker start a43cef2cfbe7
Error response from daemon: OCI runtime create failed: container with id exists: a43cef2cfbe7327b09347c50d60b1c531759d17cde3ff3542400f245580791c1: unknown
Error: failed to start containers: a43cef2cfbe7
`
`ctr --namespace moby --address /run/containerd/containerd.sock c ls` show no such id a43cef2cfbe7327b09347c50d60b1c531759d17cde3ff3542400f245580791c1

**Comment by cpuguy83** [comment] 2019-07-17 06:15
That sounds like a different issue.
Your error seems to be that runc says the container with that id exists, but the issue described here is containerd reporting the error.
Could you open a new issue?

**Comment by lowi82** [comment] 2020-02-12 01:13
> 
> 
> That sounds like a different issue.
> Your error seems to be that runc says the container with that id exists, but the issue described here is containerd reporting the error.
> Could you open a new issue?



> 
> 
> @Eyshika You can upgrade or you can do:
> 
> ```
>  docker run -it --rm -v /:/host alpine /host/usr/local/bin/docker-containerd-ctr  --namespace moby --address /host/run/docker/containerd/docker-containerd.sock c rm b62020cb44e1ed3307195ca4402cdf23ed817c35c52a30da858909398898c8b6
> ```
> 
> Where that long ID is the ID reported as already existing when you try to start the container.



> 
> 
> That sounds like a different issue.
> Your error seems to be that runc says the container with that id exists, but the issue described here is containerd reporting the error.
> Could you open a new issue?

I was careful and executed with the correct 

> 
> 
> @Eyshika Well, the `docker run` command I gave you makes assumptions about where the `ctr` binary is. Please take my example and adapt to your system.

I did adapt to my system and ran : 
docker run -it --rm -v /:/host alpine /usr/bin/docker-containerd-ctr/  --namespace moby --address /var/snap/docker/current/run/docker/containerd/docker-containerd.sock c rm [CONTAINER ID]

I got this error: 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/usr/bin/docker-containerd-ctr/\": stat /usr/bin/docker-containerd-ctr/: no such file or directory": unknown.

**Comment by se-teryoshkin** [comment] 2020-06-07 21:11
@fzhan 
It helps me:
sudo rm -r /var/lib/docker/runtime-runc/moby/<Container_ID>

**Comment by cupen** [comment] 2020-10-22 10:55
I noticed the same problem after upgrade docker from `19.03.1` to `19.03.13`.

I kill a process named `containerd-shim -namespace moby ..........` which find by:
```bash
ps aux | grep 9d79aca9890ed973309a6c25882fcf7d54dacb76a455a1ee3c8f922edfbc5e02
```

Then I delete a directory.
```bash
sudo rm -r /var/run/docker/runtime-runc/moby/9d79aca9890ed973309a6c25882fcf7d54dacb76a455a1ee3c8f922edfbc5e02
```
It works now. Thanks everyone.

My env
* centos 7.6
* docker 19.03.13 (after upgrade)

**Comment by 303linuxgroup** [comment] 2021-11-25 07:40
Now my device also has this problem:
CentOS8.0
linux4.19.163
docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:53:39 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by thaJeztah** [comment] 2021-11-29 11:38
@303linuxgroup  not related; that error tells that you're trying to create two containers with the same name. That doesn't look like a bug, but a user-error (container names must be unique). Remove the old container before creating a new container with the same name.
