### ISSUE TITLE
Allow a failed push to retry from where it left off

### ISSUE THREAD

**Issue by somatronicon** [moby/moby#42615] opened 2021-07-09 21:37 UTC
During the 5GB push of a FS layer (right at the end in fact), my connection was interrupted due to a flaky 4G connection; while the retry logic did work, it started over from 0 bytes which really got my blood boiling. Can you introduce some logic which allows a retry to pickup where the last push left off (for each FS layer: compare hash, then the number of bytes the registry has if any, and start from there)? Even if it were time-boxed where in-complete layers were removed after X seconds/minutes to facilitate this sort of behavior that'd be cool with me 👍

**Comment by thaJeztah** [comment] 2021-07-09 21:48
Thanks for reporting; this looks to be a duplicate of https://github.com/moby/moby/issues/4872, which already has some comments, so let me close this one in favor of that one (feel free to re-post your comment there)

**Closed by thaJeztah** 2021-07-09 21:48 UTC
Labels: area/distribution, kind/enhancement
