### ISSUE TITLE
Error response from daemon: can't initialize raft node: rpc error: code = 2 desc = could not connect to prospective new cluster member using its advertised address: rpc error: code = 14 desc = grpc: the connection is unavailable

### ISSUE THREAD

**Issue by konikris** [moby/moby#32992] opened 2017-05-03 16:55 UTC
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by konikris** [comment] 2017-05-03 16:57
I'm trying to run the Docker swarm with 3 nodes (Manager Nodes)- Two nodes I'm able to add, howerver when i'm trying to add the third node to the cluster, I'm facing the below issue:

docker -v
Docker version 1.13.1-cs3, build 95c9d22
[root@UCP-LOCAL ~]# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.13.1-cs3
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: UCP-LOCAL
ID: LG4Y:55L4:E7IS:ZDHI:U73Z:5D5P:EFWZ:L6Q3:3HVU:CWFF:2TU6:XFHI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: konikris
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


Please help me to resolve this issue

Thanks
Vamsi

**Comment by thaJeztah** [comment] 2017-05-04 02:22
It looks like you're running the CS (commercially supported) version of Docker with UCP; if you have a support contract, it's best to contact support directly

**Comment by christoph-hipp** [comment] 2017-06-19 11:26
This affects also the ce version

**Comment by christoph-hipp** [comment] 2017-06-19 11:41
I have 5 (master) nodes running and want to join another node. I get this not really understandable error message.
Is this a known bug?
Is there a workaround?

Thanks!

Node to join...

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by cpuguy83** [comment] 2017-06-19 12:26
@christoph-hipp The meat of the error is this:

> could not connect to prospective new cluster member using its advertised address

And

> the connection is unavailable

This would appear to mean that the new member is not accessible via the address defined in `--advertise-addr` passed in via `docker swarm join`. If you didn't pass in a `--advertise-addr` then you may need to.

**Comment by aumana** [comment] 2017-08-14 10:10
I have the same issue, but with a twist. I have three laptops all connected to the same network:
-192.168.0.110 Docker version 17.06.0-ce, build 02c1d87 ubuntu
-192.168.0.108 Docker version 17.06.0-ce, build 02c1d87 mac
-192.168.0.114 Docker version 17.06.0-ce, build 02c1d87 debian
 and I  want to create a swarm. In the first laptop I initialize the swarm by:

<docker swarm init --advertise-addr 192.168.0.110>

I get the swarm init standard output:

<Swarm initialized: current node (g17zp5sz47g7g8zypvt9qgvna) is now a manager.

To add a worker to this swarm, run the following command:
<
    docker swarm join \
    --token SWMTKN-1-169gjmbu9rad8u4vh9ppy9s7j41wwhzgejshautvjyemc6cqqb-85mo3jo8sccrtftas2y7cbce7 \
    192.168.0.110:2377
>
To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.>

If I now copy the join statement to a terminal in the third laptop (.114) I get:
<
 Error response from daemon: rpc error: code = 14 desc = grpc: the connection is unavailable
>
but if I ssh to the laptop instead of working in a terminal window and issue the command in the ssh session I get 

<
docker swarm join \
     --token SWMTKN-1-169gjmbu9rad8u4vh9ppy9s7j41wwhzgejshautvjyemc6cqqb-85mo3jo8sccrtftas2y7cbce7 \
     192.168.0.110:2377
This node joined a swarm as a worker.
>
With the second laptop (.108) it doesn't work any way, if I ssh I get the following

<
docker swarm join \
    --token SWMTKN-1-169gjmbu9rad8u4vh9ppy9s7j41wwhzgejshautvjyemc6cqqb-8m60z2hvnsh9udpeyfm2az2jy \
    192.168.0.110:2377
Error response from daemon: manager stopped: can't initialize raft node: rpc error: code = 2 desc = could not connect to prospective new cluster member using its advertised address: rpc error: code = 4 desc = context deadline exceeded
>
And directly on the laptop

<
docker swarm join --token SWMTKN-1-06b87yoisch8g0f71jwyskslt9diare58rkr38mco0hwoho6xh-2na3hvuzi9f11de5thnzlykpm 192.168.0.108:2377
Error response from daemon: Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the “docker info” command to see the current swarm status of your node.
>
and never connects 

With the two that I was able to join with ssh all works perfect, I have deployed stacks, added and removed services etc and all works perfectly. But I have not been able to have the three laptops in a swarm

In the ideal world I would want to have laptop2 .108 as the manager and the other two as workers

**Comment by aumana** [comment] 2017-08-14 10:46
docker info
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 83
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 113
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: g17zp5sz47g7g8zypvt9qgvna
 Is Manager: true
 ClusterID: pz36azzb92y5ibxipcw349ehb
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.0.110
 Manager Addresses:
  192.168.0.110:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-89-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.06GiB
Name: gregorio-Precision-5510
ID: 6MTZ:IAHG:FRD5:ZC6S:2VQL:HXPC:Q5UY:5XTG:O4KR:35RL:UQTO:6JJA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2017-08-14 15:56
Sounds like a connectivity issue between those machines / laptops. Think of;

- firewalls being set on those machines
- swarm mode does _not_ support dynamic IP-addresses, so if the IP-address of one of the laptops changes, the swarm may no longer function.
- are the ubuntu and debian machines running bare metal, or is docker running inside a VM?

I suspect this is an issue with the setup, not a bug

**Comment by aumana** [comment] 2017-08-16 10:13
It could be, do you know which ports should  I check? i am using docker-machine to create instances in was  from those laptops and all work fine. 
The IPs are static but there is more than one network device in each of the laptops, maybe that could be confusing docker?
Yes all are bare metal, no VMs.

**Comment by thaJeztah** [comment] 2017-08-16 11:55
The ["Open protocols and ports between the hosts"](https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts) section in the documentation shows which ports and protocols need to be open between nodes.

> The IPs are static but there is more than one network device in each of the laptops

Yes, this can potentially be an issue; when initialising the swarm, uses the `--advertise-add` option (`docker swarm init --advertise-addr=<desired ip>`), that way nodes know which IP-address to connect to if multiple addresses exist.

Same for joining; use `docker swarm join --advertise-addr`

**Comment by aumana** [comment] 2017-08-16 12:01
I have been looking all around the documentation and found the problem, it looks like swarm mode is available on mac but only as single node. This comes from [FAQS](https://docs.docker.com/docker-for-mac/faqs/#can-i-use-docker-for-mac-with-new-swarm-model)

>  Can I use Docker for Mac with new swarm mode?
Yes, you can use Docker for Mac to test single-node features of swarm mode introduced with Docker Engine 1.12, including initializing a swarm with a single node, creating services, and scaling services. Docker “Moby” on Hyperkit will serve as the single swarm node. You can also use Docker Machine, which comes with Docker for Mac, to create and experiment a multi-node swarm. Check out the tutorial at Get started with swarm mode.

**Comment by sylvainmouquet** [comment] 2017-10-17 10:07
I have found a solution for this error in my platform.
The ports was available in tcp and udp the telnet and the netcat was ok.
The problem was with the proxy. I have added the IP of each nodes in the NO_PROXY value for docker and all is OK.

**Comment by thaJeztah** [comment] 2017-10-25 15:09
I'm closing this issue because this looks like a configuration issue, not a bug

**Closed by thaJeztah** 2017-10-25 15:09 UTC
Labels: area/swarm

**Comment by henshitou** [comment] 2018-05-10 13:41
the workaround about this issue:
1. mark out the proxy from the docker proxy define file /etc/systemd/system/docker.service.d/docker.conf or /etc/systemd/system/docker.service.d/docker_proxy.conf
2. reload the deamon with " systemctl daemon-reload "
3. Re-excute the command "docker swarm join --token xxxx manageip " , if there are more than one ip , you should plus "--advertise-addr + IP"

**Comment by Prit1104** [comment] 2019-04-01 07:06
@henshitou i cannot find /etc/systemd/system/docker.service.d/docker.conf or /etc/systemd/system/docker.service.d/docker_proxy.conf in my system. I cannot connect node as manager.

**Comment by thaJeztah** [comment] 2019-04-01 10:10
Docker 18.09.4 has a fix for situations where a proxy is configured, and where it would attempt to use that proxy for connecting workers/managers to the swarm cluster; in 18.09.4 it should no longer be needed to explicitly exclude manager nodes using `NO_PROXY`.

**Comment by Huynhvuong** [comment] 2019-04-01 16:35
Could you help me to configure proxy in Docker for Mac @thaJetah?

**Comment by thaJeztah** [comment] 2019-04-01 16:51
Proxy configuration on Docker for Mac is documented here; https://docs.docker.com/docker-for-mac/#proxies

**Comment by andyfisher100** [comment] 2019-05-24 09:39
If you are running this in a windows environment, verify the port 2377 is configured in windows defender firewall or turn off windows defender firewall. This is for the current manager and also the node you are trying to join. 

Turned out the node i was trying to register did not have windows firewall configured so it was registering to the swarm but appearing offline as the current managers could not talk back

**Comment by LionelBergen** [comment] 2019-10-29 18:09
I found a workaround after disabling firewall didn't work:
Join the node as a worker, then promote to manager (for some reason worker does not get the same error)

**Comment by kassi** [comment] 2020-04-18 17:20
@LionelBergen doesn't work for me. I'm trying to promote the laptop (Docker for Mac) this way from the Leader (NAS). The swarm leader says everything is fine although `docker node ls` leaves the "Manager Status" field empty for the laptop (is this normal?).
`docker node ls` on the Mac however still tells me
```
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

So I guess I can't use the Mac (quote from @aumana) although it's 2.5 years old.
Now I wonder how I can update my container/stack running on the NAS from the development machine?!

**Comment by dermanov-ru** [comment] 2022-12-10 22:38
i have problem with similar error. 

i have two nodes behind hardware firewall. nodes has local network.

1. node A - 192.168.100.2
2. node B - 192.168.100.3

lets init manager on A

`docker swarm init --listen-addr=192.168.100.2`

all is ok. lets gets  mager join token

`docker swarm join-token manager`

then run join on B

`docker swarm join --token TOKEN 192.168.100.2`

```
Error response from daemon: manager stopped: 
can't initialize raft node: rpc error: code = Unknown desc = could not connect to prospective new cluster member 
using its advertised address: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, 
latest connection error: connection error: 
desc = "transport: Error while dialing dial tcp 192.168.100.1:2377: connect: connection refused"
```

by this word `can't initialize raft node` i found this discussion.

and my problem solves this reciept: add `--advertise-addr`
https://github.com/moby/moby/issues/32992#issuecomment-309424619
thanks @cpuguy83 !

then i run on B

` docker swarm join --advertise-addr 192.168.100.3 --token TOKEN 192.168.100.2`

and all is ok now

`This node joined a swarm as a manager.`

as i understand, the 2377 port was opened only inside local network. and without `--advertise-addr ` param, docker try to reach node A with wrong way (throuth its public ip or some thing like this) and gets bloced by firewall.

Hope, it will be userfull. Cheers.

**Comment by beliciobcardoso** [comment] 2023-07-12 11:33
Here it only worked, when I initialized the "swarm" with --listen-addr=ip_manager

sudo docker swarm init --listen-addr=172.16.10.19

ubuntu@srv-work01:~$ sudo docker swarm join --token SWMTKN-1-4s5ohqye1p71fcme8jdk39oul61nkkjamgbvgczku19x4gnbz5-344jr0h1y4pv9ismvgc6hzk9x 172.16.10.19:2377
This node joined a swarm as a worker.

ubuntu@srv-main:~$ docker node  ls
ID                                                  HOSTNAME     STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
ymwke8iz5t04p67gyvow0sp60 *   srv-main          Ready     Active                Leader                     24.0.4
17j9peedizijep5vt93ldi80b             srv-work01      Ready     Active                                               24.0.4

**Comment by karthikprasath21** [comment] 2024-10-21 00:33
This issue only occurs when joining a node as a manager using public IP.
 issue never occur when a private IP is used to create a token in leader (docker swarm join-token manager private_ipaddress)
