### ISSUE TITLE
docker rmi could have a --deep option?

### ISSUE THREAD

**Issue by timepieces141** [moby/moby#11139] opened 2015-03-03 21:44 UTC
When we pull down a select group of docker images and fire up a cluster of containers based on them, on our project we tend to refer to them by their name:tag. When we choose to dynamically clean up the pulled images, we have to do some bash magic to determine the Image ID of a given name:tag before calling `docker rmi`. But it would be really nice to be able to call `docker rmi --deep [name:tag]` and docker would remove not just the local tag, but all tag references and the image. Currently if you are removing using name:tag, you have to delete each tag, and the last one deletes the actual image (understandable default behavior).

This would be handy for CI/CD workflows that run integration/system tests on dynamically produced and tagged docker image clusters.

Just food for thought...

**Comment by estesp** [comment] 2015-03-03 21:46
See #11058; not the exact same, but I noted in the comments that in a sense that "fix" is a proposal for something similar to what you are asking, although in that case it is by ID with -f that will do a "deep" rm.

**Comment by timepieces141** [comment] 2015-03-03 22:43
It is a similar issue, but keep in mind the behavior I am looking for already exists, just by ID. `docker rmi [image_id]` without any flags will remove the image *and* any tagged references, and is the behavior I want. I would just like that extended to referring to the image by `name:tag`.

Maybe a better way to describe it would be: `docker rmi [image_id|name]` would remove the image *and* any tagged references(current behavior for image, new behavior for name), and a *new* command, say `docker untag [name:tag]`, could be added to maintain the current behavior of `docker rmi [name:tag]` that just removes the tag reference to the named image.

**Comment by terencechow** [comment] 2016-09-25 01:32
Was gonna work on this but it seems that this recommended feature is pretty much the intended behaviour.

Whenever `[name:tag]`  points to a unique image then `docker rmi [name:tag]` has the same functionality as `docker rmi [image_id]` (which is what @timepieces141 asked for).

When `[name:tag]`  points to a duplicate image then `docker rmi [name:tag]` will untag the aliased image and remove it from your image list, while `docker rmi [image_id]` will give an error saying you can't remove the image because it is referenced in more than 1 repo.

Hence in the second scenario, `docker rmi image_id` doesn't give the intended behaviour that @timepieces141 was asking for anyways and I think the current behaviour is pretty logical, i.e. it removes a duplicate image from your list which just has a different tag name. 

I'd recommend closing this.

**Comment by thaJeztah** [comment] 2023-09-16 14:14
I think this would be mostly covered by `docker system prune` and `docker image prune`.

Either way, 
let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 14:14 UTC
Labels: kind/feature, area/images
