### ISSUE TITLE
Container is in docker ps list but it has actually killed

### ISSUE THREAD

**Issue by keyingliu** [moby/moby#35781] opened 2017-12-13 08:38 UTC
**Description**
After docker kill a container, the container is still in `docker ps` list, but the related container process has exited (the container is not in runc list), after restart docker, the container is gone. 

**Steps to reproduce the issue:**
from docker inspect, I found there are more than 200 thousand execID items.

**Describe the results you received:**

**Describe the results you expected:**
After `docker kill` the container, the container should not in `docker ps` list. The container info should be synced between docker daemon and runc.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 24
 Running: 16
 Paused: 0
 Stopped: 8
Images: 20
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 8.562 GB
 Data Space Total: 1.15 TB
 Data Space Available: 1.141 TB
 Metadata Space Used: 3.203 MB
 Metadata Space Total: 5.763 GB
 Metadata Space Available: 5.76 GB
 Thin Pool Minimum Free Space: 115 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 64
Total Memory: 377.6 GiB
Name: node-r6bwz
ID: GK4I:P5OH:5TG6:XUW3:V5NR:JPCQ:VWHS:KFIP:O7A2:3BWQ:JG6P:CFCG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-01-06 01:31
It looks like you're running the Red Hat fork of Docker, not the official packages. Also, docker 1.12 is very old, and reached end of life in March last year, and is thus no longer maintained.

Are you able to reproduce this issue on a current version of the official packages? https://docs.docker.com/engine/installation/linux/docker-ce/centos/

I'll close this issue because of the above, but feel free to comment after I closed

**Closed by thaJeztah** 2018-01-06 01:31 UTC
Labels: version/1.12, version/unsupported
