### ISSUE TITLE
docker ps Error

### ISSUE THREAD

**Issue by behzadENG** [moby/moby#41034] opened 2020-05-27 09:41 UTC
hi guys,
i have a problem with the version of docker , when i run this command i got error. please help me.
thank you in advance.
root@root:~/Desktop/Mydocker/visits/frontend# _docker ps_
**Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39**

**Comment by thaJeztah** [comment] 2020-05-27 10:01
Without more details, I can't tell for sure, but this looks like a duplicate of https://github.com/docker/cli/issues/2533, and is a regression in 19.03.9 that will be fixed in 19.03.10

To work around this issue, either 

- make sure your daemon is up to date (API version 1.39 indicates that your daemon is running Docker 18.09, which reached EOL, so recommended to update)
- temporarily "pin" the CLI to use an older API version if you're connected to an old daemon using the `DOCKER_API_VERSION` environment variable, for example, `DOCKER_API_VERSION=1.39`
- temporarily downgrade the CLI you have installed


This issue is fixed on master and will be in the upcoming 19.03.10 patch release, so I'll close this issue, but feel free to continue the conversation

**Comment by Billyzou0741326** [comment] 2020-05-27 10:02
It seems to be the same problem as discussed [here](https://github.com/kubernetes-sigs/kubespray/issues/6160#issue-620669743)

**Closed by thaJeztah** 2020-05-27 10:01 UTC
Labels: area/cli, kind/bug, version/19.03
