### ISSUE TITLE
Docker API ignores .dockerignore

### ISSUE THREAD

**Issue by githubsaturn** [moby/moby#48637] opened 2024-10-11 00:55 UTC
### Description

.dockerignore is not respected when an image is built with the API (not CLI).

### Reproduce

1. clone this example repo: https://github.com/githubsaturn/test-dockerignore
2. run `rm -rf .git` to remove the .git content
3. [OPTIONAL] inspect the content of `build_context.tar`. You will see there is a `.git` directory as well as `.dockerignore` file, with some other files.
4. Run `sudo ./build_image.sh` this script builds an image, but instead of using Docker CLI, uses the API.
5. Observe that the `.git` directory in the tar file was copied over to the docker image.

### Expected behavior

Docker API should behave same as Docker CLI, i.e. ignore the content of .dockerignore

### docker version
```
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info
```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 31
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: p1289bfkll5du89xoxhgi4jvr
  Is Manager: true
  ClusterID: 80cwbgy5cu7nhu3yf47swyh68
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 127.0.0.1
  Manager Addresses:
   127.0.0.1:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-45-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.25GiB
 Name: kasra-ASUS-TUF-Dash-F15-FX517ZC-FX517ZC
 ID: 4cb852f9-5202-489d-b2ea-ba8f90378e21
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

RE: https://github.com/caprover/caprover/issues/2157

**Comment by thaJeztah** [comment] 2024-10-11 20:58
Thanks for reporting (and for providing the reproducer script).


This is the expected behavior; `.dockerignore` is used on the _client_ side to exclude content from being included in the build-context.


When using the "classic builder" or the REST API (the `/build` endpoint), the client produces a tar with the build-context, and the `.dockerignore` is used to exclude files from that tar; https://github.com/docker/cli/blob/21eea1e0034038fcc0f96dce0d213c304e22c6d9/cli/command/image/build.go#L254-L275

```go
	if buildCtx == nil {
		excludes, err := build.ReadDockerignore(contextDir)
		if err != nil {
			return err
		}

		if err := build.ValidateContextDirectory(contextDir, excludes); err != nil {
			return errors.Wrap(err, "error checking context")
		}

		// And canonicalize dockerfile name to a platform-independent one
		relDockerfile = filepath.ToSlash(relDockerfile)

		excludes = build.TrimBuildFilesFromExcludes(excludes, relDockerfile, options.dockerfileFromStdin())
		buildCtx, err = archive.TarWithOptions(contextDir, &archive.TarOptions{
			ExcludePatterns: excludes,
			ChownOpts:       &idtools.Identity{UID: 0, GID: 0},
		})
		if err != nil {
			return err
		}
	}
```


When using BuildKit (which is now the default), things are slightly different. BuildKit uses a grpc API and uses an interactive session where the daemon requests content from the client. In this case, it's still the client that excludes files when requested (through the `.dockerignore`), but instead of unconditionally sending all files to the daemon, only files used in the Dockerfile are sent (e.g. a `COPY single-file.txt .`) will only send `single-file.txt`, even if the build-context on the client side contains other files.


I should add that there's a (still "labs" / "preview") [`COPY --exclude` feature added in the Dockerfile syntax](https://docs.docker.com/reference/dockerfile/#copy---exclude) that's used to exclude files from a specific `COPY` (or `ADD`), but that option requires BuildKit as builder. it's _possible_ to use BuildKit through the REST API, but still requires additionsl steps, and I _think_ there were some issues with that approach; see 

- https://github.com/moby/moby/issues/48112

**Comment by thaJeztah** [comment] 2024-10-11 20:58
I'm closing this ticket, as this is not a bug (per above), but feel free to continue the conversation.

**Closed** 2024-10-11 20:59 UTC
Labels: area/builder, kind/question, area/builder/classic-builder, version/27.3
