### ISSUE TITLE
Dockerfile with VOLUME statement appears to break named pipes (and the whole directory) in linux.

### ISSUE THREAD

**Issue by novas0x2a** [moby/moby#43584] opened 2022-05-12 01:10 UTC
**Description**

Dockerfile with VOLUME statement appears to break named pipes (and the whole directory) in linux.

**Steps to reproduce the issue:**
Using this dockerfile:
```dockerfile
FROM debian:stable-slim@sha256:bd53ab674a48598863d4902d867fab6fa8f1da4f67a2d14b32785398e40c5f18
RUN mkdir /jail
RUN touch /jail/a
RUN mknod /jail/b p
RUN touch /jail/c
RUN ls -l /jail
VOLUME ["/jail"]
```
Building it: 
```sh
$ docker build -t tmp . && docker run tmp ls /jail
Sending build context to Docker daemon   16.9kB
Step 1/7 : FROM debian:stable-slim@sha256:bd53ab674a48598863d4902d867fab6fa8f1da4f67a2d14b32785398e40c5f18
 ---> e324495662f3
Step 2/7 : RUN mkdir /jail
 ---> Using cache
 ---> f8f1470e4e13
Step 3/7 : RUN touch /jail/a
 ---> Using cache
 ---> 8949073c9107
Step 4/7 : RUN mknod /jail/b p
 ---> Using cache
 ---> 5123c6d91bd6
Step 5/7 : RUN touch /jail/c
 ---> Using cache
 ---> 62e536c46985
Step 6/7 : RUN ls -l /jail
 ---> Running in a002458ba45e
total 0
-rw-r--r-- 1 root root 0 May 12 01:01 a
prw-r--r-- 1 root root 0 May 12 01:01 b
-rw-r--r-- 1 root root 0 May 12 01:01 c
Removing intermediate container a002458ba45e
 ---> 9d93321b4a57
Step 7/7 : VOLUME ["/jail"]
 ---> Running in af62bfd7c81a
Removing intermediate container af62bfd7c81a
 ---> 3c6fa588fe4f
Successfully built 3c6fa588fe4f
Successfully tagged tmp:latest
a

```

**Describe the results you received:**
only the file `a` is listed from the `docker run`, whereas all three files are listed during `docker build`

**Describe the results you expected:**
i expected three files:
- `a` (a normal file)
- `b` (a named pipe)
- `c` (a normal file)

**Additional information you deem important (e.g. issue happens only occasionally):**
This is cut down from a larger case involving a chroot tarball. Our observation is that it seems like the files in the directory are listed asciibetically, and any file that appears later in the list in that directory disappears after we build it.

If I comment out the `VOLUME` statement, I see what I expected (all three files).

**Output of `docker version`:**

```Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.1
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

**Output of `docker info`:**

```Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 133
  Running: 0
  Paused: 0
  Stopped: 133
 Images: 626
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.0-1032-oem
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.45GiB
 Name: r91395ed
 ID: RCZK:TITQ:KOA5:IHFG:SJXN:4P5Z:YLRS:MYL3:MFMI:WR6S:5TS6:JHI5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: novas0x2a
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical (my laptop).

**Comment by scentoni** [comment] 2022-05-12 23:31
This works in Docker 17.06.2:
```
[root@sv3-orca-0412p06 ~]# cat >Dockerfile <<EOF
> FROM repo.splunk.com/debian:10
> RUN mkdir /jail
> RUN touch /jail/a
> RUN mknod /jail/b p
> RUN touch /jail/c
> RUN ls -l /jail
> VOLUME ["/jail"]
> EOF
[root@sv3-orca-0412p06 ~]# docker build -t tmp - < Dockerfile
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM repo.splunk.com/debian:10
 ---> 4906f6b1e440
Step 2/7 : RUN mkdir /jail
 ---> Running in 71ee97aab3b3
 ---> a600f8e3875d
Removing intermediate container 71ee97aab3b3
Step 3/7 : RUN touch /jail/a
 ---> Running in f35d627e8e67
 ---> 81e547dd87a4
Removing intermediate container f35d627e8e67
Step 4/7 : RUN mknod /jail/b p
 ---> Running in dd4c6fb41667
 ---> 8f27741a1ddf
Removing intermediate container dd4c6fb41667
Step 5/7 : RUN touch /jail/c
 ---> Running in 0ea364ec7f45
 ---> eaf188929bfe
Removing intermediate container 0ea364ec7f45
Step 6/7 : RUN ls -l /jail
 ---> Running in 5e1dd6e54021
total 0
-rw-r--r-- 1 root root 0 May 12 23:25 a
prw-r--r-- 1 root root 0 May 12 23:25 b
-rw-r--r-- 1 root root 0 May 12 23:25 c
 ---> f51653c87a9e
Removing intermediate container 5e1dd6e54021
Step 7/7 : VOLUME /jail
 ---> Running in 0322d66940da
 ---> f6074bf939a2
Removing intermediate container 0322d66940da
Successfully built f6074bf939a2
Successfully tagged tmp:latest
[root@sv3-orca-0412p06 ~]# docker run --rm tmp ls -l /jail
total 0
-rw-r--r-- 1 root root 0 May 12 23:25 a
prw-r--r-- 1 root root 0 May 12 23:25 b
-rw-r--r-- 1 root root 0 May 12 23:25 c
```
but not in Docker Engine 19.03.18:
```
<skipping redundant lines>
ubuntu@ip-10-224-187-208:~$ docker run --rm tmp ls -l /jail
total 0
-rw-r--r-- 1 root root 0 May 12 23:21 a
```

**Comment by scentoni** [comment] 2022-05-12 23:50
I think the problem is in assembling the container from the image, not building the image from the Dockerfile. If I copy the image from one system to the other, what matters is where I run `docker run`, not where I run `docker build`.

**Comment by xinfengliu** [comment] 2022-05-30 10:18
This has been fixed in https://github.com/containerd/continuity/pull/197
and taken into moby:
https://github.com/moby/moby/blob/2a35b01336289b6210e2acbcab5d6d98d24f7594/vendor/github.com/containerd/continuity/fs/copy.go#L157-L165 
https://github.com/moby/moby/pull/43547

**Comment by cpuguy83** [comment] 2022-09-30 21:35
Nice, thanks for linking the PR's.
Closing this since it should be resolved now.

**Closed by cpuguy83** 2022-09-30 21:35 UTC
Labels: area/builder, area/volumes
