### ISSUE TITLE
Docker container runtime 19.3.12 for Kubernetes restarts on its own

### ISSUE THREAD

**Issue by shanyu** [moby/moby#41385] opened 2020-08-25 07:03 UTC
**Description**

We are using kubeadm to deploy Kubernetes cluster using the docker container runtime. While the cluster is running some user applications, occasionally, we see all pods on the same Kubernetes node got restarted. We couldn't determine the reason why the pods restarted.

So we looked at syslog for the Kubernetes node, saw something like this:
```
Aug 24 06:43:12 spe-azg5-29 kubelet[53676]: I0824 06:43:12.347369   53676 kubelet.go:1822] skipping pod synchronization - [container runtime is down, PLEG is not healthy: pleg was last seen active 9m38.109613609s ago; threshold is 3m0s]
Aug 24 06:43:12 spe-azg5-29 kubelet[53676]: I0824 06:43:12.471873   53676 log.go:172] http: TLS handshake error from 100.64.1.2:59496: EOF
…
Aug 24 06:43:12 spe-azg5-29 kubelet[53676]: E0824 06:43:12.487917   53676 desired_state_of_world_populator.go:298] Error processing volume "data" for pod "compute-0-0_test(fe26cc3d-b257-408b-90b9-5799314aa81c)": error processing PVC "test"/"data-compute-0-0": failed to fetch PVC test/data-compute-0-0 from API server. err=persistentvolumeclaims "data-compute-0-0" is forbidden: User "system:node:spe-azg5-29" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "test": no relationship found between node "spe-azg5-29" and this object
…
Aug 24 06:43:14 spe-azg5-29 dockerd[53129]: time="2020-08-24T06:43:14.756318942-07:00" level=info msg="Container 44c4ac11695f8cc0daf6b4b7f8ef6b4819fc7a058ce1eaf29fe0411414a602ab failed to exit within 2 seconds of signal 15 - using the force"
…
Aug 24 06:43:15 spe-azg5-29 containerd[2068]: time="2020-08-24T06:43:15.638637578-07:00" level=info msg="shim reaped" id=44c4ac11695f8cc0daf6b4b7f8ef6b4819fc7a058ce1eaf29fe0411414a602ab
…
Aug 24 06:43:16 spe-azg5-29 kernel: [1179989.156690] cni0: port 5(vethcf53bfe0) entered disabled state
Aug 24 06:43:16 spe-azg5-29 kernel: [1179989.193167] device vethcf53bfe0 left promiscuous mode
```

We checked that it is not caused by unattended-upgrades of docker packages.

We also ruled out memory or disk issue, this is no oom_killer involved.

**Steps to reproduce the issue:**
We don't have a reliable repro. We occasionally see this problem.

**Describe the results you received:**
Docker container runtime is down then restarted, for no reason, causing all pods to restart.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 22
  Paused: 0
  Stopped: 1
 Images: 22
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-186-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 80
 Total Memory: 503.8GiB
 Name: spe-azg5-29
 ID: E6WQ:PBIS:AYZ3:PUYN:YXLP:2GII:MGEJ:6GAT:V5NO:GV5Q:FULU:QPHA
 Docker Root Dir: /data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
kubectl get node spe-azg5-29 -o jsonpath="{.status.nodeInfo.containerRuntimeVersion}"
docker://19.3.12

**Comment by thaJeztah** [comment] 2020-09-08 14:18
With just the information in this ticket, I think this will be difficult to look into; from the logs, I see that docker is running, but somehow kubelet was having issues to communicate, and (because of that?) triggered a shutdown of containers.

A quick google gave me some older issues that mention a similar error https://github.com/kubernetes/kubernetes/issues/61117, https://github.com/kubernetes/kubernetes/issues/45419 (likely others as well), but those do not provide a consistent reason for the problem (other than either nodes running out of resources and/or networking issues)

From the above, I don't think there's anything actionable right now, and I'll close this issue for now, but feel free to continue the conversation, and we can reopen if there's a way to reproduce the problem, and if there's more clarity if this is an issue in docker or kubernetes

**Closed by thaJeztah** 2020-09-08 14:18 UTC
Labels: status/more-info-needed, version/19.03
