### ISSUE TITLE
support  of  GPU schedule

### ISSUE THREAD

**Issue by WanLinghao** [moby/moby#35457] opened 2017-11-10 02:12 UTC
Does docker support GPU schedule?
Currently you can constrain  container's memory consuming by --memory option.
I was thinking if docker also support similar feature of GPU.
For example, my pc has two GPUs which GPU A has tow cores, GPU B has four cores. Now I want to run an container by using just one core of GPU B. 
Is it possible for current docker?

**Comment by thaJeztah** [comment] 2017-11-10 12:02
GPU support is not yet available, but is being worked on currently, see:

- "Add Support for Swarmkit Generic Resources" https://github.com/moby/moby/issues/33439
- Design document: https://github.com/docker/swarmkit/blob/master/design/generic_resources.md
- https://github.com/moby/moby/pull/35326
- https://github.com/docker/swarmkit/pull/2347
- https://github.com/docker/cli/pull/429

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to comment after that

**Closed by thaJeztah** 2017-11-10 12:02 UTC
