### ISSUE TITLE
can all docker daemon share one data-root

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#37008] opened 2018-05-07 06:19 UTC
Backgroud:
All docker daemon need to use same images which means one image need storage on each server, it waste too much disk space.
Then, i want to use `overlay2` storage and make data-root on cephfs, so that one image could storage one times not X times, and no need to pull X times.

Step:
1. install docker-ce(17.09.0-ce) on centos7.4, kernel is 3.10.0-693.el7.x86_64
**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
2. change docker daemon json
```
{
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
```
3. link /var/lib/docker to /cephfs/docker
4. start docker daemon

The first daemon start:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: <unknown>
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
```
but the second failed, i use debug mdoe to start:
```
DEBU[2018-05-07T06:14:40.290021136Z] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[2018-05-07T06:14:40.291205051Z] libcontainerd: new containerd process, pid: 2346 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=8 memory=7821 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[2018-05-07T06:14:40.792099664Z] libcontainerd: containerd health check returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
DEBU[2018-05-07T06:14:41.305143374Z] Using default logging driver json-file       
DEBU[2018-05-07T06:14:41.305209004Z] Golang's threads limit set to 55980          
DEBU[2018-05-07T06:14:41.308379703Z] [graphdriver] trying provided driver: overlay2 
WARN[2018-05-07T06:14:41.310515236Z] Using pre-4.0.0 kernel for overlay2, mount failures may require kernel update 
DEBU[2018-05-07T06:14:41.313701046Z] backingFs=<unknown>,  projectQuotaSupported=false 
DEBU[2018-05-07T06:14:41.313730128Z] Using graph driver overlay2                  
DEBU[2018-05-07T06:14:41.314753144Z] Max Concurrent Downloads: 3                  
DEBU[2018-05-07T06:14:41.314779955Z] Max Concurrent Uploads: 5                    
DEBU[2018-05-07T06:14:42.346387003Z] Cleaning up old mountid : start.             
Error starting daemon: error while opening volume store metadata database: timeout
```
Is it supported?
If not, is there any good partice about similar situation?

**Comment by thaJeztah** [comment] 2018-05-07 09:26
No this is not something you should do; The data-root is designed to be exclusively accessed by a single daemon; if you use a shared filesystem that's used by multiple daemons, you _will_ run into issues. For example, the daemon tracks which images are in use by a container, and multiple daemons won't keep track on what's being used by containers run by other daemons; this could lead to an image being removed by another container. The directory also keeps state (IP-addresses in use, containers running, etc etc). For those reasons you should _never_ share the data-root between daemons.

The ["run multiple daemons"](https://docs.docker.com/engine/reference/commandline/dockerd/#run-multiple-daemons) mentions this (probably other sections in the documentation as well);

> `--data-root` is the path where persisted data such as images, volumes, and cluster state are stored. The default value is `/var/lib/docker`. To avoid any conflict with other daemons, set this parameter separately for each daemon.

(also read http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/, which touches this subject).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-05-07 09:26 UTC
Labels: version/17.09

**Comment by daixiang0** [comment] 2018-05-07 13:34
Is there any good partice about the situation that multiple daemons use same iamges?
If each image is about 1G, disk space waste too much.
Or i can offer a shared filesystem which you can consider as  space less, which fs can be supported?

**Comment by thaJeztah** [comment] 2018-05-07 13:40
It's not really possible without significant changes in the code-base (and adding a lot of complexity); as mentioned: those daemon's won't know what's still being used by other daemons, so if one daemon pulls an image, the other daemon's won't know it's being pulled (so don't "see" the image in the list of images that's available locally), and if a daemon _removes_ an image, the other daemons will fail (because an image that they expected to be there is suddenly gone).
