### ISSUE TITLE
Error parsing reference: "/certs:certs" is not a valid repository/tag.

### ISSUE THREAD

**Issue by docvel** [moby/moby#33418] opened 2017-05-27 08:36 UTC
root@vel:/certs# docker run -d -p 5000:5000 --restart=always --name registry -v pwd /certs:certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/dockerregistry.crt -e REGISTRY_HTTP_TLS_KEY=/certs/dockerregistry.key registry:2
## ****docker: Error parsing reference: "/certs:certs" is not a valid repository/tag**.**

---------------------------------------------------
GENERAL SUPPORT INFORMATION
---------------------------------------------------

  

---------------------------------------------------
 
-->

**Description**
Try to create local registry.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
root@vel:/certs# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64

```
(paste your output here)
```

**Output of `docker info`:**
root@vel:/certs# docker info
Containers: 45
 Running: 0
 Paused: 0
 Stopped: 45
Images: 33
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 211
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-22-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.9 MiB
Name: vel
ID: V3OM:KT4Y:XD4T:B446:ILF5:7EUI:CBM5:H36G:VJ33:P6YA:TJNU:4FJA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```
(paste your output here)
```root@vel:/certs# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64


**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ocravel VM, ubuntu OS

**Comment by thaJeztah** [comment] 2017-05-27 09:28
Looks like you have a typo in your command, and there's backtics missing around `pwd`. Should probably be;

    -v `pwd`/certs:certs

or

    -v `pwd`:/certs


This is not a bug, so I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2017-05-27 09:28 UTC
Labels: version/1.12

**Comment by docvel** [comment] 2017-05-27 11:00
Hi Sebastian,

                        Thanks for your reply. please see the below output.


root@vel:/certs# docker run -d -p 5000:5000 --restart=always --name
registry -v 'pwd' /certs:certs -e
REGISTRY_HTTP_TLS_CERTIFICATE=/certs/dockerregistry.crt -e
REGISTRY_HTTP_TLS_KEY=/certs/dockerregistry.key registry:2
docker: Error parsing reference: "/certs:certs" is not a valid
repository/tag.
See 'docker run --help'.

root@vel:/certs# docker run -d -p 5000:5000 --restart=always --name
registry -v 'pwd':certs -e
REGISTRY_HTTP_TLS_CERTIFICATE=/certs/dockerregistry.crt -e
REGISTRY_HTTP_TLS_KEY=/certs/dockerregistry.key registry:2
docker: Error response from daemon: Invalid bind mount spec "pwd:certs":
Invalid volume destination path: 'certs' mount path must be absolute..
See 'docker run --help'.

Thanks in advance.

**Comment by docvel** [comment] 2017-05-27 11:02
Thanks in advance.

**Comment by docvel** [comment] 2017-05-27 11:10
Oops it works. Wonderful support Sebastian.  Its my type error again, i missed / in before certs.
 -v 'pwd':/certs

Thanks a lot.

**Comment by thaJeztah** [comment] 2017-05-29 09:44
Glad to hear it worked!
