### ISSUE TITLE
Unable to remove files previously committed with AUFS

### ISSUE THREAD

**Issue by cezarsa** [moby/moby#24309] opened 2016-07-04 14:04 UTC
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 170
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 360
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: active
 NodeID: 78qac8zxq26vyrlkrka1q3avq
 IsManager: Yes
 Managers: 1
 Nodes: 2
 CACertHash: sha256:6b5ff90da4f2edd0f0a9ce6396e83eaff9feeb5ce748a977b1ed87b9ff35cc82
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: K5CM:ZNO2:AA47:2TML:FOIX:SBC4:ZMG7:7IVJ:PDGZ:AWGF:YOZM:PFEC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: cezarsa
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on virtualbox

**Steps to reproduce the issue:**
1. With the following Dockerfile:

```
$ cat Dockerfile
FROM busybox
RUN mkdir /x && echo "hey" > /x/a
RUN rm -rf /x && mkdir /x && echo "hey2" > /x/a
RUN rm -rf /x && mkdir /x
CMD ["cat", "/x/a"]
```
1. Build it `docker build -t aufsbug .`
2. Run it `docker run --rm aufsbug`

**Describe the results you received:**

The string `hey2` is printed.

**Describe the results you expected:**

The error message `cat: can't open '/x/a': No such file or directory` should have been shown. Because the `/x/a` file wasn't supposed to be there anymore.

**Additional information you deem important (e.g. issue happens only occasionally):**

You can reproduce it only on AUFS. I also tested it on stable 1.11.2 and the bug is also there.

This issue is related seems related to #9093 which was closed as solved some time ago.

**Comment by justincormack** [comment] 2016-07-04 14:37
Yes, it looks like the same issue, but lets not reopen the old one.

**Comment by AkihiroSuda** [comment] 2016-07-07 10:46
The issue is even reproducible with Boot2Docker v1.9.1 (kernel 4.1.13).
I think the issue is not new and perhaps the issue of AUFS (it should create `.wh.a`, but it does not)

Someone seems to have already experienced a similar issue (in Japanese) https://github.com/yokogawa-k/aufs-directories-undeletable-bug

**Comment by AkihiroSuda** [comment] 2016-07-07 11:41
I think this is an issue of AUFS: it seems ignoring `latest_br/.wh..wh..opq` if `second_latest_br` has both `a` and `.wh..wh..opq`.
```
root@ws01:/var/lib/docker/aufs/layers# for f in *;do echo ===$f===; cat $f; done                                                                                              
===0d986b64c893b9f7791542b81a1addd65cc1e4c832e56bc6857256268980b245===
===155dbe40572e7ba6a0cad572ac5f5d55464c4f8bc0930b04b5ab388b96fd0460===
0d986b64c893b9f7791542b81a1addd65cc1e4c832e56bc6857256268980b245
===591234462d716ee83504d334ed88fac9b2100e98b6503e3f91fd50b4a9a8e6e3===
155dbe40572e7ba6a0cad572ac5f5d55464c4f8bc0930b04b5ab388b96fd0460
0d986b64c893b9f7791542b81a1addd65cc1e4c832e56bc6857256268980b245
===9e2200f27fc3ac91da25b4b9b91b2e6411d28e887a89eb1bae136f880cd6214f===
591234462d716ee83504d334ed88fac9b2100e98b6503e3f91fd50b4a9a8e6e3
155dbe40572e7ba6a0cad572ac5f5d55464c4f8bc0930b04b5ab388b96fd0460
0d986b64c893b9f7791542b81a1addd65cc1e4c832e56bc6857256268980b245

root@ws01:/var/lib/docker/aufs/diff# find 155dbe40572e7ba6a0cad572ac5f5d55464c4f8bc0930b04b5ab388b96fd0460
155dbe40572e7ba6a0cad572ac5f5d55464c4f8bc0930b04b5ab388b96fd0460
155dbe40572e7ba6a0cad572ac5f5d55464c4f8bc0930b04b5ab388b96fd0460/x
155dbe40572e7ba6a0cad572ac5f5d55464c4f8bc0930b04b5ab388b96fd0460/x/a <-- hey

root@ws01:/var/lib/docker/aufs/diff# find 591234462d716ee83504d334ed88fac9b2100e98b6503e3f91fd50b4a9a8e6e3
591234462d716ee83504d334ed88fac9b2100e98b6503e3f91fd50b4a9a8e6e3
591234462d716ee83504d334ed88fac9b2100e98b6503e3f91fd50b4a9a8e6e3/x
591234462d716ee83504d334ed88fac9b2100e98b6503e3f91fd50b4a9a8e6e3/x/a <-- hey2
591234462d716ee83504d334ed88fac9b2100e98b6503e3f91fd50b4a9a8e6e3/x/.wh..wh..opq <-- this seems causing the issue

root@ws01:/var/lib/docker/aufs/diff# find 9e2200f27fc3ac91da25b4b9b91b2e6411d28e887a89eb1bae136f880cd6214f
9e2200f27fc3ac91da25b4b9b91b2e6411d28e887a89eb1bae136f880cd6214f
9e2200f27fc3ac91da25b4b9b91b2e6411d28e887a89eb1bae136f880cd6214f/x
9e2200f27fc3ac91da25b4b9b91b2e6411d28e887a89eb1bae136f880cd6214f/x/.wh..wh..opq
```


The issue is not new. I confirmed it is even reproducible with Boot2Docker v1.9.1 (kernel 4.1.13, AUFS v4.1-20151116)

You can also reproduce the issue without Docker: https://github.com/AkihiroSuda/test24309-without-docker

**Comment by thaJeztah** [comment] 2023-04-21 00:03
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS

**Closed by thaJeztah** 2023-04-21 00:03 UTC
Labels: area/storage/aufs, kind/bug, version/1.12
