### ISSUE TITLE
Docker hostname not replicated in internal DNS

### ISSUE THREAD

**Issue by interone-ms** [moby/moby#36333] opened 2018-02-16 11:16 UTC
**Description**

Docker, when using custom networks, does not replicate the hostnames of containers to other containers in the same network - only the container name.

**Steps to reproduce the issue:**
1. Create a new network: `docker network create test --subnet 172.19.0.1/24`
2. Launch a new dummy container: `docker run -t -d --net=test --name=foo --hostname=bar debian bash`
3. Verify that the hostname got set correctly: `docker exec -it foo hostname`
4. Launch a second dummy container: `docker run -t -d --net=test --name=baz --hostname=banana debian bash`
5. Try to ping the first container from the second: `docker exec -it baz ping bar` and `docker exec -it baz ping foo`

**Describe the results you received:**

Name resolution for `bar` failed while name resolution for `foo` succeeds.

**Describe the results you expected:**

Name resolution for `bar` works.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
# docker info
Containers: 19
 Running: 15
 Paused: 0
 Stopped: 4
Images: 42
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 212
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.55GiB
Name: XXXX
ID: QNW6:NWHU:3MOM:I2C7:2WU6:LHCF:KTB2:IVD6:JXNC:2OIV:NI6O:CA4H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Comment by thaJeztah** [comment] 2018-02-19 14:21
Correct; `--hostname` is local to the container, and only sets the hostname inside the container, not on the network / inside the embedded DNS.

The container _name_ is registered in the DNS, and you can add additional entries using the `--network-alias` and/or `--link` options.

Closing this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-02-19 14:21 UTC
Labels: area/networking
