### ISSUE TITLE
im trying to run sudo command on docker quick start terminal but im getting an error called sudo command not found how to solve this  problem in using a vm i.e linux 2.6/3.x/4.x

### ISSUE THREAD

**Issue by mujeebrehmankhan** [moby/moby#33442] opened 2017-05-31 06:32 UTC
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:** sudo command not found

**Describe the results you expected:**...
```
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`: 
```
Containers: 16
 Running: 2
 Paused: 0
 Stopped: 14
Images: 6
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: efstf6tzsuq6jv9nlrvfi7vaw
 Is Manager: true
 ClusterID: 7sz8wtugord5l4pttvhh7ha79
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.100
 Manager Addresses:
  192.168.99.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: default
ID: UUTO:EBMF:LW5S:C2NR:M5YF:EG7U:JQOZ:RIYN:AAFW:B672:4YCL:47MP
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 48
 Goroutines: 166
 System Time: 2017-05-31T06:23:25.27951711Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by techninja1008** [comment] 2017-05-31 07:17
Windows does not have sudo, and you don't need to have administrative privileges for Docker on Windows as it uses TCP rather than UNIX sockets.

Solution: Remove sudo from the command

**Comment by thaJeztah** [comment] 2017-05-31 09:21
Correct, as @techninja1008 mentions; the `sudo` command is only used on Linux, not on Windows

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-05-31 09:21 UTC
Labels: kind/question, version/17.04

**Comment by mujeebrehmankhan** [comment] 2017-06-01 08:32
thank you for the reply and suggestion on my post @thaJeztah @techninja1008
