### ISSUE TITLE
can't list iptables chains' rules in container with SELINUX=Enforcing

### ISSUE THREAD

**Issue by kidfrom** [moby/moby#41048] opened 2020-05-31 18:51 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

running `$ iptables -L` in docker container resulted in error.

**Steps to reproduce the issue:**
1. SELINUX=Enforcing in `/etc/selinux/config`, `touch ./autorelabel` and `shutdown -r now`
2. Enforcing to Docker Container by ad this code to file `/etc/docker/daemon.jso`, and then `systemctl restart docker`
```
{
  "selinux-enabled": true
}
```
2. Create a test image
Dockerfile
```
FROM alpine:3.12
RUN apk --update --no-cache add \
          iptables
CMD ["/bin/sh"]
```
Then, run `$ docker run -ti --rm --cap-add=ALL test iptables -L``

**Describe the results you received:**

iptables lists the chains' rules.

**Describe the results you expected:**

```
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.4 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

tail -n 100 /var/log/messages

```
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered blocking state
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered disabled state
May 31 18:33:42 odoo kernel: device veth619673e entered promiscuous mode
May 31 18:33:42 odoo kernel: IPv6: ADDRCONF(NETDEV_UP): veth619673e: link is not ready
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered blocking state
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered forwarding state
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered disabled state
May 31 18:33:42 odoo systemd-udevd[5020]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 31 18:33:42 odoo systemd-udevd[5020]: Could not generate persistent MAC address for vethfbb93cf: No such file or directory
May 31 18:33:42 odoo NetworkManager[948]: <info>  [1590950022.3425] manager: (vethfbb93cf): new Veth device (/org/freedesktop/NetworkManager/Devices/42)
May 31 18:33:42 odoo NetworkManager[948]: <info>  [1590950022.3436] manager: (veth619673e): new Veth device (/org/freedesktop/NetworkManager/Devices/43)
May 31 18:33:42 odoo systemd-udevd[5021]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 31 18:33:42 odoo systemd-udevd[5021]: Could not generate persistent MAC address for veth619673e: No such file or directory
May 31 18:33:42 odoo dockerd[1422]: time="2020-05-31T18:33:42.394206040Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/f4860cea81c2e1f578fe838e39a2aefde24988d1140325dece845ec887d98f91/shim.sock" debug=false pid=5026
May 31 18:33:42 odoo kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
May 31 18:33:42 odoo kernel: eth0: renamed from vethfbb93cf
May 31 18:33:42 odoo kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth619673e: link becomes ready
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered blocking state
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered forwarding state
May 31 18:33:42 odoo NetworkManager[948]: <info>  [1590950022.5861] device (veth619673e): carrier: link connected
May 31 18:33:42 odoo NetworkManager[948]: <info>  [1590950022.5864] device (docker0): carrier: link connected
May 31 18:33:42 odoo dockerd[1422]: time="2020-05-31T18:33:42.876209936Z" level=error msg="Handler for POST /v1.39/containers/f4860cea81c2e1f578fe838e39a2aefde24988d1140325dece845ec887d98f91/resize returned error: cannot resize a stopped container: unknown"
May 31 18:33:42 odoo dockerd[1422]: time="2020-05-31T18:33:42.890783250Z" level=error msg="Handler for POST /v1.39/containers/f4860cea81c2e1f578fe838e39a2aefde24988d1140325dece845ec887d98f91/resize returned error: cannot resize a stopped container: unknown"
May 31 18:33:42 odoo dockerd[1422]: time="2020-05-31T18:33:42.906295020Z" level=error msg="Handler for POST /v1.39/containers/f4860cea81c2e1f578fe838e39a2aefde24988d1140325dece845ec887d98f91/resize returned error: cannot resize a stopped container: unknown"
May 31 18:33:42 odoo dockerd[1422]: time="2020-05-31T18:33:42.952210165Z" level=info msg="shim reaped" id=f4860cea81c2e1f578fe838e39a2aefde24988d1140325dece845ec887d98f91
May 31 18:33:42 odoo dockerd[1422]: time="2020-05-31T18:33:42.962096468Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 31 18:33:42 odoo kernel: vethfbb93cf: renamed from eth0
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered disabled state
May 31 18:33:42 odoo systemd-udevd[5098]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 31 18:33:42 odoo NetworkManager[948]: <info>  [1590950022.9761] manager: (vethfbb93cf): new Veth device (/org/freedesktop/NetworkManager/Devices/44)
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered disabled state
May 31 18:33:42 odoo kernel: device veth619673e left promiscuous mode
May 31 18:33:42 odoo kernel: docker0: port 1(veth619673e) entered disabled state
May 31 18:33:42 odoo NetworkManager[948]: <info>  [1590950022.9948] device (veth619673e): released from master device docker0
May 31 18:33:47 odoo systemd[1]: Created slice User Slice of UID 0.
May 31 18:33:47 odoo systemd[1]: Started /run/user/0 mount wrapper.
May 31 18:33:47 odoo systemd[1]: Starting User Manager for UID 0...
May 31 18:33:47 odoo systemd[1]: Started Session c9 of user root.
May 31 18:33:47 odoo systemd-logind[867]: New session c9 of user root.
May 31 18:33:48 odoo systemd[5107]: Starting D-Bus User Message Bus Socket.
May 31 18:33:48 odoo systemd[5107]: Reached target Timers.
May 31 18:33:48 odoo systemd[5107]: Reached target Paths.
May 31 18:33:48 odoo setroubleshoot[4991]: SELinux is preventing /usr/sbin/unix_chkpwd from using the siginh access on a process. For complete SELinux messages run: sealert -l 2012b6c5-46f7-49e8-870e-f450e876f820
May 31 18:33:48 odoo platform-python[4991]: SELinux is preventing /usr/sbin/unix_chkpwd from using the siginh access on a process.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that unix_chkpwd should be allowed siginh access on processes labeled chkpwd_t by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'unix_chkpwd' --raw | audit2allow -M my-unixchkpwd#012# semodule -X 300 -i my-unixchkpwd.pp#012
May 31 18:33:48 odoo systemd[5107]: Listening on D-Bus User Message Bus Socket.
May 31 18:33:48 odoo systemd[5107]: Reached target Sockets.
May 31 18:33:48 odoo systemd[5107]: Reached target Basic System.
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.10
 API version:       1.39
 Go version:        go1.13.10
 Git commit:        9424aeaee9
 Built:             Thu May 28 22:18:06 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 18.09.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 4.18.0-147.8.1.el8_1.x86_64
 Operating System: CentOS Linux 8 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 821.3MiB
 Name: odoo
 ID: FWBI:3ZXJ:T4LZ:G3C4:66HL:Z2VC:CJJL:BF25:EU2Q:XR6Q:UAXH:QURH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by cpuguy83** [comment] 2020-05-31 19:41
That's not surprising.
Instead of cap-add use --privileged...
Or you can disable SELinux on the container. "--security-pot label:disabled".... or add a custom SELinux label that would give it the access you want.

Closing since this is working as intended.

**Closed by cpuguy83** 2020-05-31 19:41 UTC

**Comment by kidfrom** [comment] 2020-05-31 20:17
@cpuguy83 Hi, this is the [stackoverflow thread](https://stackoverflow.com/questions/62119759/cant-list-iptables-chains-rules-in-container-with-selinux-enforcing) I created, I list all of the tests I did, please feel free to check.

I believe this is an actual bug.

I also try `--privileged` and `--security-opt label:disable`.
```
$ docker run -ti --rm --cap-add=ALL --privileged --security-opt label:disable test iptables -L
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.4 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```
