### ISSUE TITLE
--cpus does not affect 'nproc'

### ISSUE THREAD

**Issue by jdmarshall** [moby/moby#42356] opened 2021-05-05 22:06 UTC
--cpuset-cpus will adjust the result of nproc, but --cpus has no effect

**Steps to reproduce the issue:**
Run any image, in this case in docker desktop for OS X

**Describe the results you received:**
marshalj$  docker run -it --cpuset-cpus="1" alpine nproc
1
marshalj$  docker run -it --cpus 2 alpine nproc
4

**Describe the results you expected:**
marshalj$  docker run -it --cpuset-cpus="1" alpine nproc
1
marshalj$  docker run -it --cpus 2 alpine nproc
2

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 34
  Running: 0
  Paused: 0
  Stopped: 34
 Images: 24
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 2.923GiB
 Name: docker-desktop
 ID: AQPX:N6A4:XG2N:UBQ3:LLVM:3R5A:DKXG:JDGH:K262:USSA:JOMP:3OBV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2021-05-06 11:32
This is expected; they're not using the same mechanisms. The `--cpus` option uses CFS (Completely Fair Scheduler) to constraint CPU use, whereas `--cpuset-cpu` restricts the container access to specific CPUs. See the [CPU section](https://docs.docker.com/config/containers/resource_constraints/#cpu) in the documentation.

The `--cpus` option is a shorthand for setting `--cpu-period` and `--cpu-quota`. The `--cpus` option uses the `NanoCPUs` field at the API level, which is used to calculate values for `--cpu-period` and `--cpu-quota`; see the `getCPUResources` function; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/daemon/daemon_unix.go#L154-L160

The flag description could probably be more descriptive to mention that it's a short-hand, or to mention that it's using the CFS to restrict.


Let me close this ticket, because this is not a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2021-05-06 11:32 UTC
Labels: kind/question

**Comment by jdmarshall** [comment] 2021-05-06 19:00
cpuset locks the processes to a particular CPU, which makes moving to new (or mixed) servers a challenge. It also makes blue-green deployments challenging to implement because you have to decide the cpu list at deployment time, and every second deployment needs a different answer.

Lots and lots of software needs to determine thread counts based on core count, most of us need a solution that works on Linux, OS X, and/or Windows, and while many programming languages implement some sort of call to determine the number of cores, most of those are not compatible with cgroups.  Grovelling around in sys also means I have to make sure we haven't changed the resolution of the slices to something else so that it looks like I have 4 cores when in fact I have 2 with very small timeslices.

**Comment by felipecrs** [comment] 2024-06-01 17:38
FWIW: https://github.com/felipecrs/cgroup-scripts
