### ISSUE TITLE
HEALTHCHECK directive produces high CPU usage in Windows containers

### ISSUE THREAD

**Issue by artisticcheese** [moby/moby#34309] opened 2017-07-29 22:20 UTC
**HEALTHCHECK directive produces high CPU usage in Windows containers**

I have following healthcheck as part of my image
`$a = (Invoke-WebRequest 'http://www.microsoft.com' -usebasicparsing -MaximumRedirection 0 -errorAction SilentlyContinue).StatusCode; if ($a -eq 301) {exit 0 } else {exit 1}`
This is very simple poweshell script which checks return code and then exits. This code produces 100% CPU usage for 4 seconds while it's running. Running it manually from console does not show this behavior.

**Steps to reproduce the issue:**
1. Add `Healthcheck` to dockerfile as noted above
2. Run image and you will see CPU spikes to 100% every 15 seconds
3.

**Describe the results you received:**
High CPU utilization non-stop on otherwise idle container 

**Describe the results you expected:**
Shall not consume that much CPU

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens all the time. See XPERF capture as well as perfmon showing those spikes
```
{
    "Start": "2017-07-30T09:26:31.1945566-06:00",
    "End": "2017-07-30T09:26:34.5867868-06:00",
    "ExitCode": 1,
    "Output": ""
},
{
    "Start": "2017-07-30T09:27:04.5889064-06:00",
    "End": "2017-07-30T09:27:07.9451318-06:00",
    "ExitCode": 1,
    "Output": ""
},
{
    "Start": "2017-07-30T09:27:37.9462347-06:00",
    "End": "2017-07-30T09:27:41.3324669-06:00",
    "ExitCode": 1,
    "Output": ""
},
{
    "Start": "2017-07-30T09:28:11.3335719-06:00",
    "End": "2017-07-30T09:28:14.6968079-06:00",
    "ExitCode": 1,
    "Output": ""
}
```

![image](https://user-images.githubusercontent.com/13176884/28749098-3056b80e-7482-11e7-826b-ffdee60f81ef.png)
![image](https://user-images.githubusercontent.com/13176884/28749099-3a41e3ac-7482-11e7-9c0d-1920d3d78a9a.png)

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: active
 NodeID: vlhyuyihsmg6uilgeepwxzma3
 Is Manager: false
 Node Address: 10.44.129.134
 Manager Addresses:
  10.44.129.228:2377
  10.44.129.229:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1480.amd64fre.rs1_release.170706-2004)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8 GiB
Name: DNVAPPCNTNR2
ID: OFXF:SR7T:KULK:SCCZ:4J4A:MH4O:WQVH:SBD5:KAFY:J76I:S4F5:4FQT
Docker Root Dir: E:\images
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by artisticcheese** [comment] 2017-07-29 23:17
You can see this if you use following container `artisticcheese\healthcheck` it runs the same scripts in healthcheck and in entrypoint. You can see that HEALTHECK one is super heavy on CPU while entry point barely registers on CPU.

**Comment by thaJeztah** [comment] 2017-07-30 10:31
ping @friism @johnstep

**Comment by thaJeztah** [comment] 2017-07-31 21:02
Yes looks like a duplicate of https://github.com/moby/moby/issues/33096 let's close this one

(thanks for reporting!)

**Closed by thaJeztah** 2017-07-31 21:02 UTC
Labels: area/builder, area/daemon, platform/windows, version/17.03
