### ISSUE TITLE
Feature request: keep files timestamp if copy to container

### ISSUE THREAD

**Issue by gebele** [moby/moby#23511] opened 2016-06-14 10:41 UTC
As you describe the cp command behaves like cp -a I miss timestamps I work with for some files. I would really appreciate the --preserve implementation cp -p for that. Or at least an implementation of the files timestamp out of cp -p e.g. a command like: cp -t.

**Comment by thaJeztah** [comment] 2019-12-30 15:04
Looks like this is a duplicate of (or very similar to) https://github.com/moby/moby/issues/17175. Closing this one

**Closed by thaJeztah** 2019-12-30 15:04 UTC
Labels: area/builder, kind/enhancement
