### ISSUE TITLE
Syslog entry: "superfluous response.WriteHeader call" in Docker 25.x

### ISSUE THREAD

**Issue by jamescarppe** [moby/moby#47448] opened 2024-02-26 04:03 UTC
### Description

When retrieving the logs for a container (via `docker logs` for example), a log entry is made in `/var/log/syslog`:

```
Feb 26 16:54:53 be-docker dockerd[410]: 2024/02/26 16:54:53 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)
```

This appears to have been introduced alongside the OpenTelemetry addition in Docker 25.0.0 as this log message is not created on previous versions of Docker (for example 24.0.6).

### Reproduce

1. Install Docker 25.x
2. Create a container (any will do)
3. Monitor `/var/log/syslog` (via `tail -f` for example)
4. While monitoring, run `docker logs containername` 
5. Note the entry in syslog

### Expected behavior

No "superfluous response" message.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:17 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:17 2024
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 33
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: gelf
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-171-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.925GiB
 Name: be-docker
 ID: HJDW:MIDK:VVF2:ZZC5:CCHA:6KOE:CCZU:TXJ3:2YUM:2KHI:NKJX:7ID3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: jcarppe
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Additional Info

While a single log line entry doesn't seem like much, when using a separate tool (such as Portainer) to view container logs that auto-refreshes, this can result in repeated syslog entries.

**Comment by rwillert** [comment] 2024-03-01 20:55
docker compose stats will also create syslog messages

**Comment by LaXiS96** [comment] 2024-03-18 21:54
This line currently accounts for 8% of my total server syslog/journal logs (out of about 120k lines).
Please either suppress it if it's innocuous or fix the underlying problem, it's hard to look at system logs with this spam (journalctl does not support filters; inverse grepping works but breaks --follow for example).

**Comment by Shadok** [comment] 2024-04-04 07:56
It would be nice to have a way to disable telemetry either. 
I didn't find a way to do that.

**Comment by cpuguy83** [comment] 2024-04-04 20:13
Telemetry is disabled by default.
Its only enabled if the OTLP env vars are set.
IIRC you should also be able to forcibly disable it with `OTEL_SDK_DISABLED=1`, although I don't know if this may be triggered even with tracing disabled (or effectively no-ops).

**Comment by Herrminator** [comment] 2024-04-04 22:29
> IIRC you should also be able to forcibly disable it with `OTEL_SDK_DISABLED=1`, although I don't know if this may be triggered even with tracing disabled (or effectively no-ops).

Not in Go 😢 : open-telemetry/opentelemetry-go#3559

**Comment by cpuguy83** [comment] 2024-04-04 22:51
our tracing code supports this explicitly.
If the var is set we don't setup tracing.

**Comment by Herrminator** [comment] 2024-04-05 08:40
Ah, I see. Thank you!

But as [you suspected](https://github.com/moby/moby/issues/47448#issuecomment-2038126365), it doesn't seem to have any effect.
BTW, in our environment, those syslog entries seem to happen every time, a container does a health check.

**Comment by krissetto** [comment] 2024-04-11 16:30
I've done a bit of research into this issue with the help of @laurazard, here's the situation so far:

What seems to be happening is that the OTEL wrapper is unaware of any calls that are made to the underlying ResponseWriter.WriteHeader() func it is wrapping.   

In scenarios where the underlying `ResponseWriter` already has it's header set (and, therefore, `wroteHeader == true` in the underlying net/http `response` struct):

- The wrapper's safety check seen here will fail, meaning a call to the wrapper's `Write()` func will end up calling the wrapper's `WriteHeader()` func

    https://github.com/moby/moby/blob/f9dfd139ec0d169cf0cf6b534fad7d98137fcc23/vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/wrap.go#L76-L79
 
- The wrapper's `WriteHeader()` func is responsible for setting `w.wroteHeader = true` 
  (**Note**: this value is set on the otel `respWriterWrapper` struct)  
    https://github.com/moby/moby/blob/f9dfd139ec0d169cf0cf6b534fad7d98137fcc23/vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/wrap.go#L93-L99
    
- The wrapper's `WriteHeader()` func also calls `WriteHeader()` on the underlying `ResponseWriter` implementation, causing the `superfluous response.WriteHeader call` error to be logged [from the stdlib implementation](https://github.com/golang/go/blob/a73af5d91c4c335fb44ae99517d4c41d5f3960e0/src/net/http/server.go#L1155-L1159)


As a general question i've been having: should the otel wrapper be this opinionated? 

---

In the case of `docker compose stats`, as the example i used to reproduce the issue, we seem to call `Flush()` on the raw `http.ResponseWriter` (not yet wrapped by otel) here:

https://github.com/moby/moby/blob/f9dfd139ec0d169cf0cf6b534fad7d98137fcc23/daemon/stats.go#L47-L53

I'm not sure if we can (or should) change that implementation as a fix for this issue (the commit where this is included on our side is from quite a while back, see [here](https://github.com/krissetto/moby/commit/ae4ee974e80c5d650fdcbc0a6f5ab3245a7f1689#diff-b645c599465cae12a8a20d67c47bc131c486fa13133f8d8e6d8bfec511b5efd1)).

**Comment by thaJeztah** [comment] 2024-04-11 17:55
Related to the above (at least from a discussion earlier today); https://github.com/krissetto/moby/commit/c0391bf5545afef5e675138556c39e4c0e9bf91b was (I think) where the "write headers early" was added)

We also discussed briefly; what if we would make the writer we pass on a wrapped writer that ignores writing headers (as we know we already sent headers, so anything after us was not expected to send any)

**Comment by laurazard** [comment] 2024-04-11 18:23
To add a little more info, the "early call" was originally added in https://github.com/krissetto/moby/commit/1cbf5a54dae86e34d8e65508c5640b17cda0eed8.

**Comment by krissetto** [comment] 2024-04-14 13:12
Opened a quick [draft pr](https://github.com/moby/moby/pull/47715) that should fix the double log when running `docker logs` and `docker compose stats`, but we might need to fix other areas where responses are streamed as well

**Comment by cpuguy83** [comment] 2024-05-03 00:24
@krissetto I think the simplest fix here may be best, which is to just call `wf.Write([]byte{})` before calling `Flush` here: https://github.com/moby/moby/blob/a73e63cfa6890bc68ea552288d53735ae99d6587/daemon/stats.go#L51

Same for logs.

**Comment by cpuguy83** [comment] 2024-05-03 16:55
Opened an issue over in the otelhttp repo: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5438

In the meantime we can change from using direct flush calls to writing an empty value so it triggers otelhttp.
Also I think we can skip the otelhttp wrapper when we we aren't recording traces.

**Closed** 2024-05-16 21:12 UTC
Labels: status/0-triage, kind/bug, area/metrics, area/metrics/otel, version/25.0

**Comment by aboryslawski** [comment] 2024-09-23 16:26
Seems like this resurfaced in https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.30.0?

**Comment by thaJeztah** [comment] 2024-09-23 17:17
@aboryslawski I don't think we're on that version yet; https://github.com/moby/moby/blob/c7e42d855ec41c28702a1f6f6c2c28ecc7bd9424/vendor.mod#L102

What version of docker are you running? If you're on a version that should be fixed, but you're seeing this issue, it's better to open a new ticket with details.

**Comment by aboryslawski** [comment] 2024-09-24 15:50
Thank you for your response. Now that I think about it, my error might be unrelated to this thread.
