### ISSUE TITLE
host is down when docker service create --limit-memory 

### ISSUE THREAD

**Issue by ghost** [moby/moby#27576] opened 2016-10-20 06:46 UTC
when the worker node is 1.12.2, the is a bug that the worker node will down(every time),

cmd:  docker  service create --network wdswarm --replicas 1 --limit-memory 1G hub.mydomain.com/apps/myapp
if I use 1.12.1 on the worker node,then every thing is ok.

some times I can read some message from /var/log/message before it down:

Oct 19 13:44:52 sa-docker0-ct1 kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)
Oct 19 13:44:52 sa-docker0-ct1 kernel:  cache: kmalloc-1024(0:7c93edd4f3bda2243fa4c5d8a9159956077079a34ced3e7a0bb021bb3ddd283c), object size: 1024, buffer size: 1024, default order: 3, min order: 0
Oct 19 13:44:52 sa-docker0-ct1 kernel:  node 0: slabs: 9, objs: 288, free: 0
Oct 19 13:44:52 sa-docker0-ct1 kernel:  node 1: slabs: 12, objs: 384, free: 0
Write failed: Broken pipe

uname command
[work@sa-docker0-ct2.db01:~]$ uname -a
Linux sa-docker0-ct2.db01 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 1.12.2
Storage Driver: btrfs
 Build Version: Btrfs v3.19.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: active
 NodeID: 4jolh9lphlr6w4ljo2xd136u2
 Is Manager: false
 Node Address: 10.16.27.182
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 94.21 GiB
Name: sa-docker0-ct2.db01
ID: PRF7:4BZR:PDJU:OMF4:HOH3:M7M5:RGIX:L7JF:3VUY:G4HB:YDQ5:EK42
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

some tips,when I increase 1G to 10G, the worker node is ok

**Comment by justincormack** [comment] 2016-10-20 10:34
That looks like a kernel issue, not a docker issue. It is odd that it seems to happen on 1.12.2 but not 1.12.1 though.

**Comment by bridgeunions** [comment] 2016-10-21 03:01
thank you for reply,it's also weird if I limit memory <=3g then the host down， when I increase it >= 4g then every thing is ok.
when I search the error,I found this link https://bugs.schedmd.com/show_bug.cgi?id=2846, it looks like they are similar

**Comment by drdeimos** [comment] 2016-12-17 21:06
Hello.
I get same message from `1.12.1-0~xenial` version (Just now check on `1.12.5` version).
On `1.12.1-0~xenial` this symptoms these symptoms not reproduced
Symptoms:

- In dmesg:

```der: 0, min order: 0
[22743.694240]   node 0: slabs: 55, objs: 3520, free: 0
[22743.694241] SLUB: Unable to allocate memory on node -1 (gfp=0x2080020)
[22743.694242]   cache: kmalloc-64(1938:35dfc345b7a53470886d0b3798f7591449e3d5ec5ad5200cc647e2472c1ef33c), object size: 64, buffer size: 64, default order: 0, min order: 0
[22743.694243]   node 0: slabs: 55, objs: 3520, free: 0
[22743.694244] DMAR: Allocating 4-page iova for 0000:00:1f.2 failed
[22743.701102] ata1.00: exception Emask 0x0 SAct 0x1 SErr 0x0 action 0x0
[22743.701121] ata1.00: failed command: READ FPDMA QUEUED
[22743.701134] ata1.00: cmd 60/20:00:c0:3d:ba/00:00:58:00:00/40 tag 0 ncq 16384 in
                        res 40/00:f4:a0:3d:ba/00:00:58:00:00/40 Emask 0x40 (internal error)
[22743.701166] ata1.00: status: { DRDY }
[22743.702227] ata1.00: configured for UDMA/133
[22743.702241] ata1: EH complete
```

- in docker-stat app use all container memory:

```# docker stats --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O             PIDS
35dfc345b7a5        10.88%              127.8 MiB / 128 MiB   99.87%              3.943 GB / 1.002 GB   6.999 GB / 5.464 MB   5
```

BUT,
of these 128 megabytes is less than half of the RSS, the rest of the cache filesystem:

```
drdeimos@visor ~ $ sudo ps -eo user,pid,rss,size,vsize,comm|grep -E 'USER|docker|trans'
USER       PID   RSS  SIZE    VSZ COMMAND
root     15770 49008 676972 755820 dockerd
root     15777 17524 534960 550232 docker-containe
root     15946  3968 188500 197252 docker-proxy
root     15993  3408 34888  43640 docker-proxy
root     16043  5908 347776 356396 docker-containe
debian-+ 16114 40512 451532 549512 transmission-da  # this is app in container
```

System info:

```
$ uname -a
Linux visor 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.43 GiB
Name: visor
ID: YFJ6:VNUX:UTWA:FH5S:KZYW:3E5E:GGLF:SRDR:YAN5:IEDI:SLQW:H3HG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:          15799       12929        1191           2        1678        2506
Swap:          4095           0        4095
```

I'm use ext4 filesystem.

Steps to reproduce: run in container app (like transmission-daemon) with huge disk read to fill the system read cache

**Comment by drdeimos** [comment] 2016-12-17 21:08
Container build with docker file:
```
FROM ubuntu:16.04

RUN sed -i 's/archive\.ubuntu\.com/mirror.yandex.ru/' /etc/apt/sources.list

RUN  echo "deb http://ppa.launchpad.net/transmissionbt/ppa/ubuntu `cat /etc/*release|awk -F= '/^UBUNTU_CODENAME/ {print $2}'` main" \
  > /etc/apt/sources.list.d/transmissionbt-ubuntu-ppa-xenial.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A37DA909AE70535824D82620976B5901365C5CA1

RUN groupadd -g 1501 sambashare
RUN useradd -M -u 1500 -g 1501 -s /bin/false debian-transmission

RUN export DEBIAN_FRONTEND=noninteractive && apt-get -y update && apt-get install -y transmission-daemon

CMD /usr/bin/transmission-daemon -f --config-dir /app/conf/

EXPOSE 9091
EXPOSE 52000
USER debian-transmission
```
And run with:

```
docker run --name 'ser-transmission' \
  -d \
  -p 192.168.240.1:9091:9091 \
  -p 0.0.0.0:52000:52000 \
  -m 128M \
  -v /docker/ser-transmission/conf:/app/conf \
  -v /share/archive/Downloads:/share/Downloads \
  -v /share/archive/Video:/share/Video \
  -v /share/archive/Music:/share/Music \
  -u debian-transmission \
  ser-transmission
```

**Comment by drdeimos** [comment] 2017-03-04 00:02
My problem was solved by kernel update to 4.9 version + overlayfs.
May be it just kernel SLUB allocator bug

**Comment by thaJeztah** [comment] 2017-03-04 01:10
Thanks for the update @drdeimos, let me go ahead and close this issue

**Comment by thaJeztah** [comment] 2017-03-04 01:12
oh, wait, you were not the original reporter :smile:
looks like the @ghost account was deleted on GitHub, so guess that's ok

**Comment by jpiper** [comment] 2018-03-24 08:10
I've just bumped into the same issue trying to run a beefy Kafka install in docker (via kubernetes) with a memory limit. Other applications are fine but kafka makes the entire node hard lockup!

My kernel is 4.1.12-112.14.15.el7uek.x86_64 and docker is 17.12.1-ce


```
[872338.588586] SLUB: Unable to allocate memory on node -1 (gfp=0x8020)
[872338.817343] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[872338.817345]   cache: kmalloc-256(255:2cb79029be5b5466fd679edb12b9130c8c9e64b33b7a4807464a472aef70161f), object size: 256, buffer size: 256, default o
rder: 1, min order: 0
[872338.817347]   node 0: slabs: 299, objs: 9568, free: 0
[872338.817348]   node 1: slabs: 125, objs: 4000, free: 42
[872338.817353] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[872338.817354]   cache: kmalloc-256(255:2cb79029be5b5466fd679edb12b9130c8c9e64b33b7a4807464a472aef70161f), object size: 256, buffer size: 256, default o
rder: 1, min order: 0
[872338.817355]   node 0: slabs: 299, objs: 9568, free: 0
[872338.817355]   node 1: slabs: 125, objs: 4000, free: 42
[872338.955797] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[872338.955799]   cache: kmalloc-256(255:2cb79029be5b5466fd679edb12b9130c8c9e64b33b7a4807464a472aef70161f), object size: 256, buffer size: 256, default o
rder: 1, min order: 0
[872338.955800]   node 0: slabs: 301, objs: 9632, free: 0
[872338.955802]   node 1: slabs: 125, objs: 4000, free: 42
[872338.955808] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[872338.955808]   cache: kmalloc-256(255:2cb79029be5b5466fd679edb12b9130c8c9e64b33b7a4807464a472aef70161f), object size: 256, buffer size: 256, default o
rder: 1, min order: 0
[872338.955809]   node 0: slabs: 301, objs: 9632, free: 0
[872338.955810]   node 1: slabs: 125, objs: 4000, free: 42
[872339.157850] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[872339.157852]   cache: kmalloc-256(255:2cb79029be5b5466fd679edb12b9130c8c9e64b33b7a4807464a472aef70161f), object size: 256, buffer size: 256, default o
rder: 1, min order: 0
[872339.157853]   node 0: slabs: 305, objs: 9760, free: 0
[872339.157855]   node 1: slabs: 125, objs: 4000, free: 42
[872339.157860] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[872339.157861]   cache: kmalloc-256(255:2cb79029be5b5466fd679edb12b9130c8c9e64b33b7a4807464a472aef70161f), object size: 256, buffer size: 256, default o
rder: 1, min order: 0
[872339.157862]   node 0: slabs: 305, objs: 9760, free: 0
[872339.157862]   node 1: slabs: 125, objs: 4000, free: 42
[872339.541021] SLUB: Unable to allocate memory on node -1 (gfp=0x20)
[872339.541023]   cache: kmalloc-256(255:2cb79029be5b5466fd679edb12b9130c8c9e64b33b7a4807464a472aef70161f), object size: 256, buffer size: 256, default o
rder: 1, min order: 0
[872339.541024]   node 0: slabs: 308, objs: 9856, free: 0
[872339.541025]   node 1: slabs: 125, objs: 4000, free: 42
[872349.154748] NMI watchdog: Watchdog detected hard LOCKUP on cpu 24
```
...

```[872349.154898] Call Trace:
[872349.154901]  <NMI>  [<ffffffff8173d34a>] dump_stack+0x63/0x81
[872349.154904]  [<ffffffff81738059>] panic+0xda/0x218
[872349.154908]  [<ffffffff81087adf>] nmi_panic+0x3f/0x40
[872349.154911]  [<ffffffff81146761>] watchdog_overflow_callback+0xd1/0xe0
[872349.154914]  [<ffffffff8118925c>] __perf_event_overflow+0x9c/0x260
[872349.154916]  [<ffffffff81189e44>] perf_event_overflow+0x14/0x20
[872349.154919]  [<ffffffff81039ba2>] intel_pmu_handle_irq+0x1f2/0x4c0
[872349.154924]  [<ffffffff81342e41>] ? ioremap_page_range+0x291/0x410
[872349.154927]  [<ffffffff811d7a84>] ? vunmap_page_range+0x1d4/0x2f0
[872349.154933]  [<ffffffff8140782a>] ? ghes_copy_tofrom_phys+0x12a/0x210
[872349.154934]  [<ffffffff814079b0>] ? ghes_read_estatus+0xa0/0x190
[872349.154938]  [<ffffffff8102fefb>] perf_event_nmi_handler+0x2b/0x50
[872349.154941]  [<ffffffff8101c2a1>] nmi_handle+0x91/0x170
[872349.154943]  [<ffffffff8101c83a>] default_do_nmi+0x4a/0x140
[872349.154944]  [<ffffffff8101ca24>] do_nmi+0xf4/0x170
[872349.154947]  [<ffffffff8174c078>] end_repeat_nmi+0x19f/0x1ce
[872349.154950]  [<ffffffff81745b3f>] ? _raw_spin_lock_irqsave+0x7f/0xe0
[872349.154951]  [<ffffffff81745b3f>] ? _raw_spin_lock_irqsave+0x7f/0xe0
[872349.154953]  [<ffffffff81745b3f>] ? _raw_spin_lock_irqsave+0x7f/0xe0
[872349.154959]  <<EOE>>  <IRQ>  [<ffffffff814d7c78>] scsi_end_request+0x108/0x1e0
[872349.154961]  [<ffffffff814d9d86>] scsi_io_completion+0x116/0x670
[872349.154963]  [<ffffffff814d05ff>] scsi_finish_command+0xcf/0x130
[872349.154965]  [<ffffffff814d9412>] scsi_softirq_done+0x132/0x160
[872349.154968]  [<ffffffff8131b600>] blk_done_softirq+0x90/0xc0
[872349.154972]  [<ffffffff8108c4eb>] __do_softirq+0xfb/0x320
[872349.154974]  [<ffffffff8108ca15>] irq_exit+0x125/0x130
[872349.154976]  [<ffffffff8174cfaa>] do_IRQ+0x5a/0xf0
[872349.154978]  [<ffffffff81746c52>] common_interrupt+0x192/0x192
[872349.154981]  <EOI>  [<ffffffff815c755c>] ? cpuidle_enter_state+0xcc/0x230
[872349.154983]  [<ffffffff815c752c>] ? cpuidle_enter_state+0x9c/0x230
[872349.154985]  [<ffffffff815c76f7>] cpuidle_enter+0x17/0x20
[872349.154987]  [<ffffffff810cf606>] cpu_startup_entry+0x236/0x320
[872349.154989]  [<ffffffff81053eda>] start_secondary+0x17a/0x1e0

```

**Comment by jpiper** [comment] 2018-03-24 10:36
And likewise, when I remove the memory limit on the container everything works as expected. I'm not able to upgrade my kernel, so my current workaround is to remove the memory limit.

**Comment by thaJeztah** [comment] 2018-03-26 10:41
Yes, this looks like a kernel issue, and there's not much we can do there. For that reason, I'm closing this issue, but feel free to discuss

**Closed by thaJeztah** 2018-03-26 10:41 UTC
Labels: area/kernel, area/swarm
