### ISSUE TITLE
Cannot remove the images: Error: No such image:

### ISSUE THREAD

**Issue by jianzhangbjz** [moby/moby#40687] opened 2020-03-13 08:58 UTC
**Description**
 I want to remove some docker images but failed.

**Steps to reproduce the issue:**
1. List the images
```console
[jzhang@dhcp-140-36 ~]$ docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-base                  latest              f779ab8af41a        11 months ago       224MB
registry                               2                   f32a97de94e1        12 months ago       25.8MB
registry                               latest              f32a97de94e1        12 months ago       25.8MB
registry                               latest              f32a97de94e1        12 months ago       25.8MB
openshift/origin-console-operator      latest              232610553dac        12 months ago       297MB
fedora                                 latest              d7372e6c93c6        12 months ago       275MB
hello-world                            latest              fce289e99eb9        14 months ago       1.84kB
ansibleplaybookbundle/postgresql-apb   latest              634dc89fb0c8        16 months ago       627MB
ansibleplaybookbundle/apb-tools        latest              cf6ab89bec61        19 months ago       665MB
ansibleplaybookbundle/apb-tools        canary              630c86dc4342        20 months ago       604MB
```

2. Get the `Error: No such image:`, but they did there, why?
```console
[jzhang@dhcp-140-36 ~]$ docker rmi -f $(docker images -qa)
Error: No such image: f779ab8af41a
Error: No such image: f32a97de94e1
Error: No such image: f32a97de94e1
Error: No such image: f32a97de94e1
Error: No such image: 232610553dac
Error: No such image: d7372e6c93c6
Error: No such image: 634dc89fb0c8
Error: No such image: cf6ab89bec61
Error: No such image: 630c86dc4342
```
3.

**Describe the results you received:**

**Describe the results you expected:**
Remove these images successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
[jzhang@dhcp-140-36 ~]$ docker version
Client: Docker Engine - Community
 Version:           19.03.0-rc3
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        27fcb77
 Built:             Thu Jun 20 02:02:49 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       27fcb77
  Built:            Thu Jun 20 02:01:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2020-06-04 14:05
I'm not able to reproduce this on a current version of docker. I see you have a _really_ old pre-release of docker 19.03 installed; make sure to update to the latest patch release of docker (19.03.11 at time of writing), and containerd.io (1.2.13 at time of writing).

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-04 14:05 UTC
Labels: kind/question
