### ISSUE TITLE
 Terminal start error

### ISSUE THREAD

**Issue by xingxing9688** [moby/moby#35659] opened 2017-12-01 09:03 UTC
Docker version 1.12.6, build 78d1802
centos 7.2  3.10.0-327.4.5.el7.x86_64  
Dec 01 16:50:15 paas-slave-20-37 systemd[1]: Starting Docker Application Container Engine...
Dec 01 16:50:15 paas-slave-20-37 dockerd[32749]: time="2017-12-01T16:50:15.469896672+08:00" level=info msg="libcontainerd: new containerd process, pid: 32756"
Dec 01 16:50:16 paas-slave-20-37 dockerd[32749]: time="2017-12-01T16:50:16.511664187+08:00" level=warning msg="devmapper: Base device already exists and has file... ignored."
Dec 01 16:50:16 paas-slave-20-37 dockerd[32749]: time="2017-12-01T16:50:16.534517114+08:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""

journalctl --no-pager -u docker  
Dec 01 16:36:23 paas-slave-20-37 systemd[1]: Starting Docker Application Container Engine...
Dec 01 16:36:23 paas-slave-20-37 dockerd[31411]: time="2017-12-01T16:36:23.692897033+08:00" level=info msg="libcontainerd: new containerd process, pid: 31418"
Dec 01 16:36:24 paas-slave-20-37 dockerd[31411]: time="2017-12-01T16:36:24.735230374+08:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."

**Comment by thaJeztah** [comment] 2017-12-01 23:03
When reporting issues, please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.


Docker 1.12.6 is an outdated version, and has reached end-of-life in March, and is no longer maintained.

Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because of the above, but feel free to comment

**Closed by thaJeztah** 2017-12-01 23:03 UTC
