### ISSUE TITLE
How to remove RPM files really after installed 

### ISSUE THREAD

**Issue by ryanlyy** [moby/moby#37055] opened 2018-05-14 06:26 UTC
**Description**

When building image, mostly we need to copy a lot of RPM files into image, and installed then rm -rf those RPMS. but in fact, these RPMs are still in our image. if there are a lot of RPM files needed to be copied to image, then it will make image bigger size.

**Steps to reproduce the issue:**
The Dockerfile is following:
```
[root@foss-ssc-2 rpm]# cat Dockerfile
FROM centos:latest

COPY iperf3-3.1.3-1.fc24.x86_64.rpm /
RUN rpm -i /iperf3-3.1.3-1.fc24.x86_64.rpm && rm -rf /iperf3-3.1.3-1.fc24.x86_64.rpm
[root@foss-ssc-2 rpm]#
```
In faces, those rpms are not deleted. they still exist in upper layer.
**Describe the results you received:**
RPMs are not deleted from image disk whatever any layer after checking the zip file in each layer.

**Describe the results you expected:**
RPMs are really deleted from image disk. 

Or is there any command we can like ADD for zip file:
1. Copy RPM to image
2. rpm -i
3. delete RPMs

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@foss-ssc-2 rpm]# docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
[root@foss-ssc-2 rpm]# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 18.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-135521931-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 535.5MB
 Data Space Total: 107.4GB
 Data Space Available: 39.93GB
 Metadata Space Used: 1.245MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.67-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 35.35GiB
Name: foss-ssc-2
ID: GOXJ:5T7K:J5B4:YCKM:URSD:QPGF:LKBM:TNR4:SKJ7:RLBD:7O4C:R22P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://127.0.0.1:8000/
HTTPS Proxy: https://127.0.0.1:8000/
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-ip6tables is disabled
[root@foss-ssc-2 rpm]#

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
[root@foss-ssc-2 rpm]# docker build -t testrpm:1.0 -f ./Dockerfile .
Sending build context to Docker daemon  81.41kB
Step 1/3 : FROM centos:latest
 ---> e934aafc2206
Step 2/3 : COPY iperf3-3.1.3-1.fc24.x86_64.rpm /
 ---> Using cache
 ---> 19d1795d21ff
Step 3/3 : RUN rpm -i /iperf3-3.1.3-1.fc24.x86_64.rpm && rm -rf /iperf3-3.1.3-1.fc24.x86_64.rpm
 ---> Running in 86130786c1ae
Removing intermediate container 86130786c1ae
 ---> 5aec8102e6a0
Successfully built 5aec8102e6a0
Successfully tagged testrpm:1.0
[root@foss-ssc-2 rpm]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
testrpm             1.0                 5aec8102e6a0        4 seconds ago       219MB
ubuntu              latest              452a96d81c30        2 weeks ago         79.6MB
centos              latest              e934aafc2206        5 weeks ago         199MB
[root@foss-ssc-2 rpm]# docker save -o testrpm.tar testrpm:1.0
[root@foss-ssc-2 rpm]# ls
Dockerfile  iperf3-3.1.3-1.fc24.x86_64.rpm  testrpm.tar
[root@foss-ssc-2 rpm]# tar xvf testrpm.tar
5aec8102e6a08095faae1d89fbb2838e7475761238d1ec13585bada0c6e17229.json
9285fabe50dbe5861329257581d87da4dbbbe0818b6327d8f72a397f6642b7d0/
9285fabe50dbe5861329257581d87da4dbbbe0818b6327d8f72a397f6642b7d0/VERSION
9285fabe50dbe5861329257581d87da4dbbbe0818b6327d8f72a397f6642b7d0/json
9285fabe50dbe5861329257581d87da4dbbbe0818b6327d8f72a397f6642b7d0/layer.tar
b53edde7b6409578a23167bbb8cb505ffe22b37708d40e64b07bc02f1edfef4b/
b53edde7b6409578a23167bbb8cb505ffe22b37708d40e64b07bc02f1edfef4b/VERSION
b53edde7b6409578a23167bbb8cb505ffe22b37708d40e64b07bc02f1edfef4b/json
b53edde7b6409578a23167bbb8cb505ffe22b37708d40e64b07bc02f1edfef4b/layer.tar
f280d212e1053cfeaee3b5f9048bd26a7ab646bc159f988756954377d9dfc7c1/
f280d212e1053cfeaee3b5f9048bd26a7ab646bc159f988756954377d9dfc7c1/VERSION
f280d212e1053cfeaee3b5f9048bd26a7ab646bc159f988756954377d9dfc7c1/json
f280d212e1053cfeaee3b5f9048bd26a7ab646bc159f988756954377d9dfc7c1/layer.tar
manifest.json
tar: manifest.json: implausibly old time stamp 1970-01-01 08:00:00
repositories
tar: repositories: implausibly old time stamp 1970-01-01 08:00:00
[root@foss-ssc-2 rpm]# tar tvf 9285fabe50dbe5861329257581d87da4dbbbe0818b6327d8f72a397f6642b7d0/layer.tar| grep rpm
-rw-r--r-- 0/0           78686 2017-08-16 20:06 iperf3-3.1.3-1.fc24.x86_64.rpm
[root@foss-ssc-2 rpm]# tar tvf 9285fabe50dbe5861329257581d87da4dbbbe0818b6327d8f72a397f6642b7d0/layer.tar
-rw-r--r-- 0/0           78686 2017-08-16 20:06 iperf3-3.1.3-1.fc24.x86_64.rpm
[root@foss-ssc-2 rpm]# tar tvf b53edde7b6409578a23167bbb8cb505ffe22b37708d40e64b07bc02f1edfef4b/layer.tar
drwxr-xr-x 0/0               0 2018-05-14 14:12 etc/
-rw-r--r-- 0/0           11516 2018-05-14 14:12 etc/ld.so.cache
---------- 0/0               0 2018-05-14 14:12 .wh.iperf3-3.1.3-1.fc24.x86_64.rpm
drwxr-xr-x 0/0               0 2018-04-03 02:38 usr/
dr-xr-xr-x 0/0               0 2018-05-14 14:12 usr/bin/
-rwxr-xr-x 0/0           11264 2016-06-09 04:27 usr/bin/iperf3
dr-xr-xr-x 0/0               0 2018-05-14 14:12 usr/lib64/
lrwxrwxrwx 0/0               0 2018-05-14 14:12 usr/lib64/libiperf.so.0 -> libiperf.so.0.0.0
-rwxr-xr-x 0/0          135776 2016-06-09 04:27 usr/lib64/libiperf.so.0.0.0
drwxr-xr-x 0/0               0 2018-04-03 02:39 usr/share/
drwxr-xr-x 0/0               0 2018-05-14 14:12 usr/share/doc/
drwxr-xr-x 0/0               0 2018-05-14 14:12 usr/share/doc/iperf3/
-rw-r--r-- 0/0           12786 2016-06-07 02:18 usr/share/doc/iperf3/LICENSE
-rw-r--r-- 0/0            8764 2016-06-07 02:18 usr/share/doc/iperf3/README.md
-rw-r--r-- 0/0           13103 2016-06-07 02:18 usr/share/doc/iperf3/RELEASE_NOTES
drwxr-xr-x 0/0               0 2018-04-03 02:38 usr/share/man/
drwxr-xr-x 0/0               0 2018-05-14 14:12 usr/share/man/man1/
-rw-r--r-- 0/0            2807 2016-06-09 04:27 usr/share/man/man1/iperf3.1.gz
drwxr-xr-x 0/0               0 2018-05-14 14:12 usr/share/man/man3/
-rw-r--r-- 0/0            1143 2016-06-09 04:27 usr/share/man/man3/libiperf.3.gz
drwxr-xr-x 0/0               0 2018-04-03 02:38 var/
drwxr-xr-x 0/0               0 2018-04-03 02:38 var/cache/
drwx------ 0/0               0 2018-05-14 14:12 var/cache/ldconfig/
-rw------- 0/0            9840 2018-05-14 14:12 var/cache/ldconfig/aux-cache
drwxr-xr-x 0/0               0 2018-04-03 02:39 var/lib/
drwxr-xr-x 0/0               0 2018-04-03 02:39 var/lib/rpm/
-rw-r--r-- 0/0          929792 2018-05-14 14:12 var/lib/rpm/Basenames
-rw-r--r-- 0/0          278528 2018-05-14 14:12 var/lib/rpm/Dirnames
-rw-r--r-- 0/0            8192 2018-05-14 14:12 var/lib/rpm/Group
-rw-r--r-- 0/0           12288 2018-05-14 14:12 var/lib/rpm/Installtid
-rw-r--r-- 0/0           16384 2018-05-14 14:12 var/lib/rpm/Name
-rw-r--r-- 0/0        15179776 2018-05-14 14:12 var/lib/rpm/Packages
-rw-r--r-- 0/0         1650688 2018-05-14 14:12 var/lib/rpm/Providename
-rw-r--r-- 0/0           81920 2018-05-14 14:12 var/lib/rpm/Requirename
-rw-r--r-- 0/0           24576 2018-05-14 14:12 var/lib/rpm/Sha1header
-rw-r--r-- 0/0           16384 2018-05-14 14:12 var/lib/rpm/Sigmd5
-rw-r--r-- 0/0          352256 2018-05-14 14:12 var/lib/rpm/__db.001
-rw-r--r-- 0/0           98304 2018-05-14 14:12 var/lib/rpm/__db.002
-rw-r--r-- 0/0         1318912 2018-05-14 14:12 var/lib/rpm/__db.003
[root@foss-ssc-2 rpm]#
```

**Comment by thaJeztah** [comment] 2018-05-14 08:41
Correct; this is how layered filesystems (and Docker images) work: you cannot remove files that were added/created in previous layers. When removing a file that was added in a previous layer, a "whiteout" file is added to the image layer that _marks_ the file from a previous layer as deleted, but it won't make the image's size smaller.

Possible solutions (depending on your situation);

- Use a multi-stage build: start a new build-stage, to which you only copy the files that are needed for your final image
-  Use the experimental `--squash` feature

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-05-14 08:41 UTC
Labels: area/builder

**Comment by ryanlyy** [comment] 2018-05-17 01:57
@thaJeztah I think this is feature request. for general COPY file, it is ok to using multi-stage build. For RPM, it is different, after installed it is really not used. so seems it is better to have cmd like ADD for zip file to do add rpm and install it and rm it. that is what ADD do for zip file.

Thanks,
Ryan

**Comment by rcjsuen** [comment] 2018-05-26 14:53
> so seems it is better to have cmd like ADD for zip file to do add rpm and install it and rm it. that is what ADD do for zip file.

I feel like people are going to ask for `ADD` to support all sorts of file formats if this precedence is set for `.rpm` files.
