### ISSUE TITLE
aufs au_opts_parse docker  unknown option dirperm1 when try swarm

### ISSUE THREAD

**Issue by aimbin** [moby/moby#31408] opened 2017-02-28 08:40 UTC
I am trying swarm on v1.13 by  with one master and 2 worker (all VM).
After I finished start the service (simple tomcat, export port 8080) , i try view the index page one by one in WebBrowser to verify.  The master doing fine.
But when view http://worker1:8080/snake/. The worker VM(both 2) go like to restart and stuck in console by waiting input.  The page can not open by ERR_CONNECTION_ABORTED.
The message says: aufs au_opts_parse:1155:dockerd[1830] unknown option dirperm1

---------------------------------------

Other info:
1. After the VM console input "Enter", the VM can be connected by SSH,  type docker ps, the original container has gone, none container running, The master start  2 containers to replace the failed instance in worker-node. 
2. I can start single container in the 2 worker node, and can view by WebBrowser.
3. All the 3 node is ubuntu 14.04,  master's ubuntu image not same with worker.
4. I reinstall the woker with another ununtu image, the problem still.  
    PS: I can't get master image now to reinstall the worker.

--------------------------------------------------------------

The docker info of worker:
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: yzh2knqaatcgbm8l46cgutg8t
 Is Manager: false
 Node Address: 192.168.1.1
 Manager Addresses:
  192.168.1.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.777 GiB
Name: SZX1000270222
ID: F5BM:B3US:G7IZ:IKH3:LHR3:5ZMY:NRDG:47YI:WB3O:7HHJ:FPIG:Z6L2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Experimental: false
Insecure Registries:
 docker-hub.tools.****.com
 docker.tools.****.com
 127.0.0.0/8
Registry Mirrors:
 http://**.167.187.**:***/
Live Restore Enabled: false

-----------------------------------------------
Master docker info:

Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: xrdsfi01b1v1hlo59hcbzz22d
 Is Manager: true
 ClusterID: 97n5wv0s65ey8rsm29t16pm8e
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.2
 Manager Addresses:
   192.168.1.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-101-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.65 GiB
Name: SZX1000258876
ID: L63R:CWVW:5BCL:CVOS:QAWU:Z2AS:V4UV:7QFC:SOWH:FWHG:Y6BV:3AUY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 docker.tools.****.com
 docker-hub.tools.****.com
 127.0.0.0/8
Registry Mirrors:
 http://192.168.1.10:24482/
Live Restore Enabled: false

**Comment by thaJeztah** [comment] 2017-02-28 14:53
The `au_opts_parse` message is because Ubuntu 14.04 is using an old version of aufs, and does not support dirperm1 (see https://docs.docker.com/engine/reference/builder/#known-issues-run), updating to Ubuntu 16.04 should resolve that message.

> type docker ps, the original container has gone

Is the container still there, but stopped? Try `docker ps -a`; also are you sure the container was scheduled on _that_ node in the swarm, and not another node?

The information included in your report doesn't give a lot of information to work with;

- can you provide the _exact_ steps to reproduce?
- can you reduce the steps to reproduce to a minimal example? Is this issue reproducible with "any" image, or only with the tomcat image?
- have you checked the system and daemon logs on these nodes to see if they contain anything useful?

**Comment by aimbin** [comment] 2017-03-01 02:20
@thaJeztah 
Thank you. 
(0) Is the container still there, but stopped?  and not another node?
The container not there.   I check every node, each one has a container. Nodes=3, service-scale=3.
(1) Can you provide the exact steps to reproduce?
       [1]Start the service by swam with 3 nodes, then check the url in WebBrowser
       [2]Master's URL  is OK, when try worker URL, the page can not open, waiting until timeout.
       [3]The VM can not connected by SSH, and it is in restart. Check the console log, it says AUFS error.
       [4]The both worker node container not exist after restarted, master start 2 new container in itself instead.
(2)  or only with the tomcat image?  
      I have not test other image yet.
(3) have you checked the system and daemon logs
     Not yet, and I'v reinstall the VM by other ubuntu14.04 image. The new image has lower version docker, and I update to 1.13, the woker node works well.

**Comment by thaJeztah** [comment] 2021-06-30 19:00
Closing because of age. The aufs driver is also marked deprecated now

**Closed by thaJeztah** 2021-06-30 19:00 UTC
Labels: area/storage/aufs, status/more-info-needed
