### ISSUE TITLE
Setting DNS does not work with MACVLAN networks

### ISSUE THREAD

**Issue by kladkogex** [moby/moby#31645] opened 2017-03-08 12:02 UTC
When  using MACVLAN --dns-flag does not work at all!

How much funding do you guys need to start fixing simple things?

**Comment by thaJeztah** [comment] 2017-03-08 14:00
There's no need to get hostile. Docker is an open source project, and of the [more than 1600 contributors](https://github.com/docker/docker/graphs/contributors), most are not paid, or affiliated with docker. We have community guidelines, written down here; https://github.com/docker/docker/blob/master/CONTRIBUTING.md#docker-community-guidelines. Consider this your first warning.

Now, if you want your issue resolved, more information is needed. Could you please provide the information that was requested in the issue template when you opened this issue (https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md);

- output of `docker version` and `docker info`
- steps to reproduce
- how you determined that the `dns` flag did not function

Without that information it's gonna be difficult to look into your issue, confirm the issue (or if it's resolved).

**Comment by fntlnz** [comment] 2017-07-02 15:28
Closing this for now since no information were provided. 
@kladkogex please feel free to re-open anytime you want if you can help us going trough this.

**Closed by fntlnz** 2017-07-02 15:28 UTC
Labels: area/networking, status/more-info-needed
