### ISSUE TITLE
docker build file permissions under the directory（Docker 构建目录下的文件权限）

### ISSUE THREAD

**Issue by lanmingle** [moby/moby#32940] opened 2017-05-01 08:51 UTC
目录：
dockerfile 
文件1
文件2

复制到目录 A

在构建之前把文件1/2同时授权用户（如：docker 用户，chown -hR "$customer":"$customer" "$workdir/$image"）
授权可执行文件1（chmod +x "$workdir/$image/$shell"）

执行 docker 构建命令。。。构建完成。

运行容器，进入到目录 A ，查看这些文件，这些文件的用户全是 root，但是可执行权限存在。

请问能把这些权限同时复制进构建的镜像中嘛？

Google：

table of Contents:
Dockerfile
File 1
File 2

Copy to directory A

(Such as: docker user, chown -hR "$ customer": "$ customer" "$ workdir / $ image") before the build,
Authorize executable file 1 (chmod + x "$ workdir / $ image / $ shell")

Execute the docker build command. The The Build completed.

Run the container, enter the directory A, view these files, the user of these files are all root, but the executable permissions exist.

Is it possible to copy these permissions into the mirror of the building?

**Comment by thaJeztah** [comment] 2017-05-01 23:18
Files copied by `COPY` and `ADD` are currently always owned by `root` (inside the container); also see the discussion on https://github.com/moby/moby/issues/30110, which is a bit related.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-05-01 23:18 UTC
Labels: area/builder
