### ISSUE TITLE
Add node 18.09 to cluster with docker 17.03

### ISSUE THREAD

**Issue by CharcoGreen** [moby/moby#39198] opened 2019-05-10 07:41 UTC
I have this problem with a cluster.

We are currently working with the docker version 17.03.1ce with two nodes in production. We want to update to version 18.09 ++. We are currently performing tests adding a node with version 18.09 as worker of this cluster. The idea is to perform a controlled migration to the new version. But we encountered some problems.

Our cluster consists of a manager and a worker with docker version 17.03.1.

The problem that we find is that: when adding this new node, it is able to work but only when it does not have to create a new network. I explain:
S.O
```
CentOS Linux release 7.6.1810 (Core)
```
Manager:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Worker1
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Nuevo Nodo:
Worker2 
```
Client:
 Version:           18.09.6 && 18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6 && 18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
I´m creating a new network
```
docker network create -d overlay --subnet 20.1.0.0/16 hiredis
```
This service don´t work at node 18.09.3 ++
```
docker service create   \ 
 --replicas 9 \
 --name redis_Barna2  \
 --network hiredis  \
--constraint 'node.labels.datacenter==barcelona' \
redis:3.0.6
```
This is workin at new node
```
docker service create \
--replicas 9 \
--name redis_Barcelona \
--network hiredis \
--constraint 'node.labels.datacenter==barcelona' \
 redis:3.0.6
```
```
$ docker node ps worker2
ID                         NAME               IMAGE                                                                                 NODE                        DESIRED STATE  CURRENT STATE            ERROR                                                                 PORTS
taxxn0waf9hz6nqq5yihir40y  redis_Barna2.2     redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Shutdown       Rejected 17 minutes ago  "node is missing network attachments, ip addresses may be exhausted"
hrmbwq686xrjyo0n8th5l9n17  redis_Barcelona.2  redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Running        Running 36 minutes ago                                        
82dmxj6vcifqkfavwfazye9i7  redis_Barna2.3     redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Shutdown       Rejected 17 minutes ago  "node is missing network attachments, ip addresses may be exhausted"
0nag3hj874fuq2mu8j8170ekm  redis_Barna2.5     redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Shutdown       Rejected 17 minutes ago  "node is missing network attachments, ip addresses may be exhausted"
j8syt7kmcxvbeps3qrigv7ukf  redis_Barna2.6     redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Shutdown       Rejected 17 minutes ago  "node is missing network attachments, ip addresses may be exhausted"
r4e298knjxmo06g8j56dprmtl  redis_Barcelona.6  redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Running        Running 36 minutes ago                                        
mhro3qeubkey2o83mny0vl572  redis_Barcelona.7  redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Running        Running 36 minutes ago                                        
l9zna7jc64nwn7y6o4k29mgz0  redis_Barna2.8     redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Shutdown       Rejected 17 minutes ago  "node is missing network attachments, ip addresses may be exhausted"
hauwrgacpwwtgscv07fse9a0y  redis_Barcelona.8  redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Running        Running 36 minutes ago                                        
t7xar0lvqew1785qa6ivsf46s  redis_Barcelona.9  redis:3.0.6@sha256:6a692a76c2081888b589e26e6ec835743119fe453d67ecf03df7de5b73d69842   swarmPreM2-17-172-16-1-243  Running        Running 36 minutes ago                                        
swarmPreM2-17-172-16-1-243  Shutdown       Rejected 15 hours ago    "node is missing network attachments, ip addresses may be exhausted"
```

```
# journalctl  worker2

May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.302281414Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=uq6srty5wao7qa0fgegkspaf9
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.303087980Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.303418224Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=uq6srty5wao7qa0fgegkspaf9
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.303898715Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.308530115Z" level=error msg="fatal task error" error="node is missing network attachments, ip addresses may be exhausted" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 task.id=wes9e9vh3mszmiccdztzlndog
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.308598884Z" level=debug msg="state changed" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 state.desired=RUNNING state.transition="PREPARING->REJECTED" task.id=wes9e9vh3mszmiccdztzlndog
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.309108634Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=wes9e9vh3mszmiccdztzlndog
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.309565751Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.310158381Z" level=error msg="fatal task error" error="node is missing network attachments, ip addresses may be exhausted" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 task.id=w4bohpti56cf6s1zepyis87nm
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.310206265Z" level=debug msg="state changed" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 state.desired=RUNNING state.transition="PREPARING->REJECTED" task.id=w4bohpti56cf6s1zepyis87nm
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.310232614Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=wes9e9vh3mszmiccdztzlndog
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.310626514Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.311513161Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=w4bohpti56cf6s1zepyis87nm
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.311913298Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.312160509Z" level=error msg="fatal task error" error="node is missing network attachments, ip addresses may be exhausted" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 task.id=k937mjaawk6sp30dz0gl7mkct
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.312219526Z" level=debug msg="state changed" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 state.desired=RUNNING state.transition="PREPARING->REJECTED" task.id=k937mjaawk6sp30dz0gl7mkct
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.312905514Z" level=error msg="fatal task error" error="node is missing network attachments, ip addresses may be exhausted" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 task.id=ruibwlyejor1l5k1gk5ec9pyn
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.312971159Z" level=debug msg="state changed" module=node/agent/taskmanager node.id=sn9rhboechwei7j2nimgts2k2 service.id=qon3c0apt3j9l4gc1ns3oe978 state.desired=RUNNING state.transition="PREPARING->REJECTED" task.id=ruibwlyejor1l5k1gk5ec9pyn
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.313046672Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=ruibwlyejor1l5k1gk5ec9pyn
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.313787164Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.314261295Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=w4bohpti56cf6s1zepyis87nm
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.314669190Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.315700054Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=k937mjaawk6sp30dz0gl7mkct
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.316105482Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.317116521Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=ruibwlyejor1l5k1gk5ec9pyn
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.317522131Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.318267224Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=k937mjaawk6sp30dz0gl7mkct
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.318661211Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436234912Z" level=debug msg="(*worker).Update" len(assignments)=5 module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436270133Z" level=debug msg="(*worker).reconcileSecrets" len(removedSecrets)=0 len(updatedSecrets)=0 module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436283255Z" level=debug msg="(*worker).reconcileConfigs" len(removedConfigs)=0 len(updatedConfigs)=0 module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436308206Z" level=debug msg="(*worker).reconcileTaskState" len(removedTasks)=0 len(updatedTasks)=5 module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436326360Z" level=debug msg=assigned module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.desiredstate=SHUTDOWN task.id=wes9e9vh3mszmiccdztzlndog
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436382714Z" level=debug msg=assigned module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.desiredstate=SHUTDOWN task.id=w4bohpti56cf6s1zepyis87nm
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436408988Z" level=debug msg=assigned module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.desiredstate=SHUTDOWN task.id=ruibwlyejor1l5k1gk5ec9pyn
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436430239Z" level=debug msg=assigned module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.desiredstate=SHUTDOWN task.id=k937mjaawk6sp30dz0gl7mkct
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.436452905Z" level=debug msg=assigned module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.desiredstate=SHUTDOWN task.id=uq6srty5wao7qa0fgegkspaf9
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.439305625Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=wes9e9vh3mszmiccdztzlndog
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.439873059Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.440680555Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=uq6srty5wao7qa0fgegkspaf9
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.441180878Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.441993172Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=ruibwlyejor1l5k1gk5ec9pyn
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.442457538Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.443348466Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=k937mjaawk6sp30dz0gl7mkct
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.443741793Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.444670265Z" level=debug msg="(*Agent).UpdateTaskStatus" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 task.id=w4bohpti56cf6s1zepyis87nm
May 10 07:33:45 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:45.445043810Z" level=debug msg="task status reported" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2
May 10 07:33:46 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:46.797182489Z" level=debug msg="sending heartbeat to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377} with timeout 5s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:33:46 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:46.797918048Z" level=debug msg="heartbeat successful to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377}, next heartbeat period: 4.691321222s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:33:51 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:51.489441403Z" level=debug msg="sending heartbeat to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377} with timeout 5s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:33:51 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:51.490141331Z" level=debug msg="heartbeat successful to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377}, next heartbeat period: 5.426978363s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:33:56 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:56.917390529Z" level=debug msg="sending heartbeat to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377} with timeout 5s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:33:56 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:56.918206235Z" level=debug msg="heartbeat successful to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377}, next heartbeat period: 4.715791107s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:33:57 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:57.690729122Z" level=debug msg="swarmPreM2-17-172-16-1-243(ded85d4d0f84): Initiating bulk sync with node swarmPreM1-17-7c1c5d047cd3"
May 10 07:33:57 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:57.690803359Z" level=debug msg="swarmPreM2-17-172-16-1-243(ded85d4d0f84): Initiating unsolicited bulk sync for networks [v7689re6vu96kdqm2n8i4rn6m] with node swarmPreM1-17-7c1c5d047cd3"
May 10 07:33:57 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:57.691963479Z" level=debug msg="memberlist: Stream connection from=172.16.1.186:43764"
May 10 07:33:57 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:33:57.692531394Z" level=debug msg="swarmPreM2-17-172-16-1-243(ded85d4d0f84): Bulk sync to node swarmPreM1-17-7c1c5d047cd3 took 1.154779ms"
May 10 07:34:01 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:34:01.634211009Z" level=debug msg="sending heartbeat to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377} with timeout 5s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:34:01 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:34:01.634992573Z" level=debug msg="heartbeat successful to manager {avjlfs3auzl9kso84c21ad0ty 172.16.1.186:2377}, next heartbeat period: 4.951442198s" method="(*session).heartbeat" module=node/agent node.id=sn9rhboechwei7j2nimgts2k2 session.id=k3tesodprinjwg26wwerr1c1k sessionID=k3tesodprinjwg26wwerr1c1k
May 10 07:34:01 swarmPreM2-17-172-16-1-243 dockerd[6545]: time="2019-05-10T07:34:01.775768900Z" level=debug msg="memberlist: Stream connection from=172.16.1.186:43766"
```

**Comment by olljanat** [comment] 2019-05-13 21:49
@CharcoGreen 17.03 is very old version which have not been supported on long time. 
So I suggest that you first upgrade all nodes example to 17.09 then 18.03 and finally 18.09.

It is also recommend to upgrade all nodes on short period of time especially what comes to swarm managers.

**Comment by CharcoGreen** [comment] 2019-05-16 08:55
@olljanat  thanks for your reply .

 I thought it could be an easier process, but I see that we should have the most up-to-date cluster.
I'm going to perform tests with different versions, maybe the rise to 18.09 is very strong.

Thanks for your help.

**Comment by CharcoGreen** [comment] 2019-05-16 11:52
Hi, I´m do test with cluster on 17.03 docker version and now work with the new node but in docker version 18.03. For the moment this may a solution for the best upgrade of cluster.

![image](https://user-images.githubusercontent.com/23292578/57851768-acaee200-77e1-11e9-9902-da51a74c075d.png)

**Comment by thaJeztah** [comment] 2019-05-21 16:08
Running mixed versions is only supported while upgrading the cluster, and it's generally advised to not make changes to the cluster state while in that situation (i.e., don't deploy new services, create networks etc), which may be more important if there's a bigger difference between versions (upgrading to intermediate versions may be best, instead of skipping versions)

**Comment by thaJeztah** [comment] 2019-05-21 16:09
I'll close this ticket, because this looks like a support question, not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-05-21 16:09 UTC
Labels: area/networking, area/swarm, version/17.03
