### ISSUE TITLE
How to increase the partition size of /var/lib/docker (docker ce 17, centos)

### ISSUE THREAD

**Issue by zenglian** [moby/moby#35381] opened 2017-11-02 10:00 UTC
It's running out of space with a few containers and images. Want to expand it from 20G to 100G.
$df
/dev/xvda3                                                207710036   29473308  167662600  15% /
/dev/xvda5   25165824   19947980          0 100% /var/lib/docker

**Comment by thaJeztah** [comment] 2017-11-02 11:50
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to comment after that

**Closed by thaJeztah** 2017-11-02 11:50 UTC
