### ISSUE TITLE
LCOW: RUN in dockerfile causes a non-zero error code to be returned when running windows containers and specifying --platform=linux

### ISSUE THREAD

**Issue by aiecee** [moby/moby#40844] opened 2020-04-21 12:55 UTC
**Description**

In windows container mode.

```
FROM nginx:alpine 
RUN echo 'Hello, world!'
```

With the command `docker build --platform=linux .` causes the error:

```
The command '/bin/sh -c echo 'Hello, world!'' returned a non-zero code: 4294967295: failed to shutdown container: container 6cbc4a04ed480477822110ec902e99d2919870e80c267977444bc2e3d71bd124 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 6cbc4a04ed480477822110ec902e99d2919870e80c267977444bc2e3d71bd124 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)
```

This works perfectly fine when running using linux containers and also worked fine until recent updates to both docker and windows.

**Steps to reproduce the issue:**

1. Start with a simple dockerfile `FROM nginx:alpine RUN echo 'Hello, world!'` (Also happens using 'mcr.microsoft.com/dotnet/core/sdk:3.1-alpine')

2. `docker build --platform=linux .`
 
3. Error!

This also occurs when specifying the platform in a docker-compose file

**Describe the results you received:**

```bash
$ docker build --platform=linux .
Sending build context to Docker daemon  61.39MB
Step 1/5 : FROM nginx:alpine
alpine: Pulling from library/nginx
aad63a933944: Already exists
b14da7a62044: Pull complete
Digest: sha256:b942ebabfeff14ec6a7cb7a4826fe1d2e8dd8b7db5e651b81e4bc9cd6c6e91dc
Status: Downloaded newer image for nginx:alpine
 ---> 29b49a39bc47
Step 2/5 : RUN echo 'Hello, world!'
 ---> Running in 6cbc4a04ed48
Hello, world!
The command '/bin/sh -c echo 'Hello, world!'' returned a non-zero code: 4294967295: failed to shutdown container: contai
ner 6cbc4a04ed480477822110ec902e99d2919870e80c267977444bc2e3d71bd124 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 6cbc4a04ed480477822110ec902e99d2919870e80c267977444bc2e3d71bd124
encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)
```

**Describe the results you expected:**

The image to be built with the output of "Hello, World!"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 182
 Server Version: 19.03.8
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.778)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.9GiB
 Name: 
 ID: QF7S:UCNS:IUEH:EI4N:SKRN:NNGH:PB2E:C2HD:NPR7:W7HK:7ZLX:LVZC
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 33
  System Time: 2020-04-21T13:51:25.1446626+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by bplasmeijer** [comment] 2020-04-22 08:16
### Description

encountered an error during hcsshim::System::waitBackground: failure in in **windows container mode**. on fast ring and latest 1909 release.

## Steps to reproduce the issue:

```
docker run -it mcr.microsoft.com/powershell:lts-alpine-3.10
```
![image](https://user-images.githubusercontent.com/116467/79955918-bd4eea00-847f-11ea-8c04-a27801dacef6.png)

## Describe the results you received:

```
PS /> exit
time="2020-04-22T09:58:24+02:00" level=error msg="Error waiting for container: failed to shutdown container: container
69fc778d98e49bc2cd3f6e54612ff27bb7663cbe891b2a152d707f9620e4d08a encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 69fc778d98e49bc2cd3f6e54612ff27bb7663cbe891b2a152d707f9620e4d08a encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)"
PS C:\Users\bartp>
```
![image](https://user-images.githubusercontent.com/116467/79956020-dbb4e580-847f-11ea-9c7b-01af53364e6d.png)

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

### docker version
Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     true

### docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 359
 Server Version: 19.03.8
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19608 (19608.1000.amd64fre.rs_prerelease.200410-1438)
 Operating System: Windows 10 Pro Version 2004 (OS Build 19608.1006)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.88GiB
 Name: PCI
 ID: KUM5:H6SV:J3EE:5FI3:Q5PL:TA2W:ZRIS:CNBG:52AF:EL3B:F7DB:H6SG
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 35
  System Time: 2020-04-22T10:03:27.9886332+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

---

PS /> exit
time="2020-04-22T10:13:36+02:00" level=error msg="Error waiting for container: failed to shutdown container: container 55b3e99dc6bfda03d6e0be4ec000f5c6c3ee29e8d973389b0d3f1dbaea6cdaf4 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 55b3e99dc6bfda03d6e0be4ec000f5c6c3ee29e8d973389b0d3f1dbaea6cdaf4 encountered an error during hcsshim::System::waitBackground: failure
in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)"

docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     true

docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 377
 Server Version: 19.03.8
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.752)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.81GiB
 Name: LT-BAP-T-NL
 ID: AVXB:O6GT:DLC7:DZXN:OF46:3QIY:GANI:BMDV:R2TY:LN27:ZH44:YZ6X
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 49
  System Time: 2020-04-22T10:13:53.2893047+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  10.170.40.126
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

cc: @StefanScherer m @simonferquel

**Comment by MythreyaK** [comment] 2020-11-20 06:01
[Similar issue](https://github.com/docker/for-win/issues/9541#issue-745009277).

**Comment by thaJeztah** [comment] 2023-07-12 08:02
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223

**Closed by thaJeztah** 2023-07-12 08:02 UTC
Labels: platform/windows, kind/experimental, area/lcow
