### ISSUE TITLE
cache public layers from private registry

### ISSUE THREAD

**Issue by dimuskin** [moby/moby#35400] opened 2017-11-03 15:43 UTC
Hei,

I have docker configured with registry mirror:

```
{
  "registry-mirrors": [
    "https://docker-cache.XXXXXXX.com/"
  ],
  "debug": true,
}
```

no problem when I try to pull from public repository, docker download each layer from cache server.
But when I try pull image from private registry which contains layers from public hub, it will never connects to cache.

Referring to the documentation: https://docs.docker.com/registry/recipes/mirror/
`
Gotcha
It’s currently not possible to mirror another private registry. Only the central Hub can be mirrored.
`

Is it normal behavior? docker also dont use cache for public layers? and connect to dockerhub bypassing registry mirror?

Best Regards.

**Comment by thaJeztah** [comment] 2017-11-04 02:14
Yes, I think this is the expected behaviour; `docker pull` will attempt to pull an _image_ from the mirror; if the image is not found, it will continue with the next registry, and pull from there.

Note that there's an active conversation to implement private registry mirrors; https://github.com/moby/moby/pull/34319

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-11-04 02:14 UTC
Labels: area/distribution, kind/question

**Comment by dimuskin** [comment] 2017-11-06 10:04
@thaJeztah  thanks for the answer and for the advice
