### ISSUE TITLE
The command '/bin/sh -c apt-get update' returned a non-zero code: 100

### ISSUE THREAD

**Issue by HusseyTyler** [moby/moby#40363] opened 2020-01-10 16:23 UTC
I am brand new to docker and Linux, so I dont really know everything that I am doing. However, I am simply trying to create a docker image.

This is the code I am running
`FROM ubuntu:18.04

RUN apt-get update`
I used the command
`docker build . -t test
`
And this is my output
`Sending build context to Docker daemon  33.79kB
Step 1/4 : FROM tensorflow/tensorflow:2.0.0-py3
 ---> 90f5cb97b18f
Step 2/4 : RUN apt-get update
 ---> Running in 684fb4ae45f2
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists...
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 2h 56min 18s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 2h 57min 6s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 2h 58min 15s). Updates for this repository will not be applied.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
`
I am running Ubuntu 18.04

Any suggestions are greatly appreciated.

**Comment by thaJeztah** [comment] 2020-01-10 16:39
```
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 2h 56min 18s). Updates for this repository will not be applied.
```

Looks like your machine's clock may not be set correctly; https://askubuntu.com/questions/1096930/sudo-apt-update-error-release-file-is-not-yet-valid

Verify if the machine's clock is set correct (if you're running on Docker for Mac, or running Docker in a VM, it may be the clock of the VM that's not synced; this can happen if your computer was in "sleep" model).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-01-10 16:39 UTC
