### ISSUE TITLE
Unexpected EOF when trying to start non-existing container

### ISSUE THREAD

**Issue by tejksat** [moby/moby#41598] opened 2020-10-28 08:32 UTC
**Description**

When trying to start a non-existing Docker container daemon does not reply with `404` as it is declared in [Docker Engine API Reference](https://docs.docker.com/engine/api/v1.40/#operation/ContainerStart) but it rather unexpectedly interrupts the connection.

**Steps to reproduce the issue:**
1. Run `curl -v --unix-socket /var/run/docker.sock -X POST http:/v1.24/containers/non-existing/start`
    _or_
2. Run `docker start non-existing` in Terminal.

**Describe the results you received:**
1.
```
*   Trying /var/run/docker.sock:0...
* Connected to v1.24 (docker.sock) port 80 (#0)
> POST /containers/non-existing/start HTTP/1.1
> Host: v1.24
> User-Agent: curl/7.71.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host v1.24 left intact
curl: (52) Empty reply from server
```
2.
```
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/non-existing/start: EOF
Error: failed to start containers: non-existing
```

**Describe the results you expected:**
1.
```
*   Trying /var/run/docker.sock:0...
* Connected to v1.24 (docker.sock) port 80 (#0)
> POST /containers/non-existing/start HTTP/1.1
> Host: v1.24
> User-Agent: curl/7.71.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Api-Version: 1.40
< Content-Type: application/json
< Date: Wed, 28 Oct 2020 08:24:46 GMT
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/19.03.13 (linux)
< Transfer-Encoding: chunked
<
{"message":"No such container: non-existing"}
* Connection #0 to host v1.24 left intact
```

2.
```
Error response from daemon: No such container: non-existing
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 38
  Running: 22
  Paused: 0
  Stopped: 16
 Images: 195
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: WTP6:BLYV:IM42:YEVO:XJJ6:D5UK:V2UO:WZDI:LMJM:BNNI:7O2B:BXA2
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 47
  System Time: 2020-10-28T08:13:36.787602854Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment] 2020-10-28 15:44
Thanks for reporting, and for the clear reproduction steps!

This looks to be an issue specific to Docker for Mac, and from a quick test, I suspect this is  in the API proxy that's used on Docker Desktop.

I'm able to reproduce your issue, but when I skip the Docker Desktop API proxy, the issue doesn't reproduce. To skip the API proxy, I start a container and bind-mount the "raw" (non-proxied) socket (`/var/run/docker.sock.raw`) in the container; in that container, I install curl, and make the request from your example;

```bash
docker run -it --rm -v /var/run/docker.sock.raw:/var/run/docker.sock alpine sh -c 'apk add --quiet --no-cache curl && curl -v --unix-socket /var/run/docker.sock -X POST http:/v1.24/containers/non-existing/start'

*   Trying /var/run/docker.sock:0...
* Connected to v1.24 (/var/run/docker.sock) port 80 (#0)
> POST /containers/non-existing/start HTTP/1.1
> Host: v1.24
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Api-Version: 1.41
< Content-Type: application/json
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/20.10.0-beta1 (linux)
< Date: Wed, 28 Oct 2020 15:42:14 GMT
< Content-Length: 46
<
{"message":"No such container: non-existing"}
* Connection #0 to host v1.24 left intact
```

Doing the same, but mounting the _proxied_ API, the issue reproduces;

```bash
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock alpine sh -c 'apk add --quiet --no-cache curl && curl -v --unix-socket /var/run/docker.sock -X POST http:/v1.24/containers/non-existing/start'

*   Trying /var/run/docker.sock:0...
* Connected to v1.24 (/run/host-services/docker.proxy.sock) port 80 (#0)
> POST /containers/non-existing/start HTTP/1.1
> Host: v1.24
> User-Agent: curl/7.69.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host v1.24 left intact
curl: (52) Empty reply from server
```

**Comment by thaJeztah** [comment] 2020-10-28 15:45
Given that this issue is specific to Docker for Mac, could you perhaps open a ticket in the Docker for Mac issue tracker? https://github.com/docker/for-mac/issues

Unfortunately, I can't migrate this issue there, because it's in a different GitHub organization 😓

**Comment by thaJeztah** [comment] 2020-10-28 15:56
I also checked if the issue was because you're using an older API version, but I also checked if the issue was because you're using the old (non-standard) `http:/` cURL notation (without host), or if it's related to using quite an old API version, so trying both _without_ API version, and with the current (v1.39) API version, but all of these produced the same result;

```bash
curl -v --unix-socket /var/run/docker.sock -X POST http://localhost/v1.24/containers/non-existing/start
curl -v --unix-socket /var/run/docker.sock -X POST http://localhost/containers/non-existing/start
curl -v --unix-socket /var/run/docker.sock -X POST http://localhost/v1.39/containers/non-existing/start
```

I would recommend using the "normal" `http://localhost/v<API version>/` notation though, if you're using a current version of cURL. The old syntax _might_ work, but `v1.24` may be interpreted as hostname, and because of that you're using the latest version of the API instead of the specified version.

I will check why the documentation uses the old notation (I recall I fixed that at some point, but perhaps it was accidentally reverted in a rewrite)

**Comment by tejksat** [comment] 2020-10-28 16:14
@thaJeztah thank you for these cool details and the quick response! I have created the issue in Docker for Mac project: https://github.com/docker/for-mac/issues/5025. I have taken into account your suggestion to use standard cURL notation with the host in it.

**Comment by thaJeztah** [comment] 2020-10-28 16:37
Thank you!

I found where I made my previous docs changes for curl, and turned out to be in another repository, so working on a pull request now to update the examples on docs.docker.com (so thanks as well for pointing to those 😅)

**Comment by thaJeztah** [comment] 2020-10-28 16:59
opened https://github.com/docker/docker.github.io/pull/11651 for the docs

let me close this issue in favour of https://github.com/docker/for-mac/issues/5025

**Closed by thaJeztah** 2020-10-28 16:59 UTC
Labels: area/api, kind/bug, platform/desktop, version/19.03
