### ISSUE TITLE
PANIC due to a nil pointer derefence or illegal memory address during whatever  looks to be an internal "clean networks up" operation.

### ISSUE THREAD

**Issue by vatine** [moby/moby#42645] opened 2021-07-16 07:22 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**Description**

Docker daemon crashed with a nil pointer dereference or invalid memory address. Thankfull, systemd restarted it essentially at once, but it is still not great when this happens.

**Steps to reproduce the issue:**
I have no reproduction steps, apart from possibly "let it run for a while". Looking at the logs, I can see that we saw this happening 21 times over 4 hours.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
This is the relevant logs from journald:

```
<redacted> dockerd[90949]: panic: runtime error: invalid memory address or nil pointer dereference
<redacted> dockerd[90949]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5599e4acc8b8]
<redacted> dockerd[90949]: goroutine 1129 [running]:
<redacted> dockerd[90949]: github.com/armon/go-radix.recursiveWalk(0x0, 0xc004815e08, 0xc004815c00)
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:519 +0x28
<redacted> dockerd[90949]: github.com/armon/go-radix.recursiveWalk(0xc0012349f0, 0xc004815e08, 0xc004815cc0)
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
<redacted> dockerd[90949]: github.com/armon/go-radix.recursiveWalk(0xc0018c8bd0, 0xc004815e08, 0x19)
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
<redacted> dockerd[90949]: github.com/armon/go-radix.(*Tree).WalkPrefix(0xc003680650, 0xc000c87540, 0x1a, 0xc004815e08)
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:473 +0xdb
<redacted> dockerd[90949]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapTableEntries(0xc0034ebd40)
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:396 +0x3c5
<redacted> dockerd[90949]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState(0xc0034ebd40)
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:362 +0x2d
<redacted> dockerd[90949]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState-fm()
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:170 +0x2c
<redacted> dockerd[90949]: github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0xc0034ebd40, 0x12a05f200, 0xc00069d2c0, 0xc003680a90)
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:256 +0x10a
<redacted> dockerd[90949]: created by github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit
<redacted> dockerd[90949]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x830
<redacted> systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 21 Feb 2021 18:18:35 +0100
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Feb 21 17:18:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 25
 Running: 5
 Paused: 0
 Stopped: 20
Images: 10
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: zu5gu3fv2t2ywadvullbjd68d
 Is Manager: true
 ClusterID: wxpnvlw4v261yqyypostfkzd7
 Managers: 6
 Nodes: 6
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: <ip>
 Manager Addresses:
  <ip>:2377
  <ip>:2377
  <ip>:2377
  <ip>:2377
  <ip>:2377
  <ip>:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-14-cloud-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 36
Total Memory: 58.96GiB
Name: ip-10-155-0-9
ID: JDJ2:PJB5:GP6R:WLUT:YEYG:447J:YC52:PCNP:GJUO:NJX6:U4JY:CDYB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: <redacted>
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, Debian

**Comment by vatine** [comment] 2021-07-16 09:52
Just noticed that this was using a pretty old version. Looks like the latest version I can get on there, then observe. If this is a resolution, I will close this.

**Comment by vatine** [comment] 2021-07-16 10:00
Output from upgraded docker:

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment] 2021-07-16 10:00
This looks like a old version of Docker, which is no longer maintained (docker 18.09 reached EOL quite some time ago); if you're unable to update, at least be sure to have the latest patch release of 18.09 (18.09.9 was the last patch release).

That said; from the output of `docker version`, I suspect you're running a version of docker that was packaged by your distro (not a package from docker's download.docker.com package repository), and was built with incompatible build-time dependencies.

This repository pins (and "vendors") dependencies to version that are known to be compatible;  https://github.com/moby/moby/blob/v18.09.9/vendor.conf#L42, which sometimes requires older dependencies to be used. Often distro packagers ignore these versions, and assume SemVer can be used to update dependencies to later versions, which can result in unexpected behavior.

In this case, later versions of the `github.com/armon/go-radix` dependency are known to have a change in behavior, which can result in these issues; see https://github.com/moby/libnetwork/pull/2581 / https://github.com/armon/go-radix/pull/12, which looks to be the issue you're running into.

I recommend to (if possible) install a current version of docker from Docker's official package repository; https://docs.docker.com/engine/install/debian/ and/or report an issue with the package maintainers of your distro. I noticed we did not have a tracking issue for this, so I opened https://github.com/moby/moby/issues/42646 to allow building with more current versions of the dependency in future.


I'm closing this ticket because docker 18.09 reached EOL, and (if my assumptions above are correct), this issue should not be reproducible with builds that use the correct dependency versions, but feel free to continue the conversation.

**Comment by thaJeztah** [comment] 2021-07-16 10:01
Ah, whoops, I was writing my reply, and didn't see your last comments; I hope the issue is fixed for you after installing the current version 👍

**Closed by thaJeztah** 2021-07-16 10:00 UTC
Labels: version/18.09

**Comment by vatine** [comment] 2021-07-16 10:02
I should have some decent data on this comes tomorrow.

**Comment by vatine** [comment] 2021-07-17 05:54
This looks to have gone away with an upgrade.

**Comment by thaJeztah** [comment] 2021-07-17 08:39
Thanks for the update; good to hear
