### ISSUE TITLE
Network boot on raspberry + nfs mount error

### ISSUE THREAD

**Issue by teddy-dubal** [moby/moby#32964] opened 2017-05-02 14:07 UTC
**Description**

Hi , 
I use network boot to setup a cluster of raspberry pi 3 ([tutotial here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md)) , but i can't lanch my container

**Steps to reproduce the issue:**
1. Setup network boot on a raspberry pi 3
2. docker run armhf/hello-world

**Describe the results you received:**

```
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/4b95b3f6376d76b51530af79ea72530de99dc8051ce313b5ab53f296cc6a56ae-init/merged: invalid argument.
```

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: nfs
 Supports d_type: false
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.4.50-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 925.5MiB
Name: bsb-1-1
ID: AM3N:6LU2:MARO:B54H:J7G7:XX7Q:QRWT:FI66:SYHE:2NQP:BZII:IKIZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay2: the backing nfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Running without d_type support will not be supported in future releases.
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* Raspberry pi 3 (client)
* Raspberry pi 3 (nfs server)

**Comment by teddy-dubal** [comment] 2017-05-16 09:27
up. Nobody can give me an advice , about this issue

**Comment by thaJeztah** [comment] 2017-05-16 13:15
The problem is in this warning;

```
WARNING: overlay2: the backing nfs filesystem is formatted without d_type support, which leads to incorrect behavior.
Running without d_type support will not be supported in future releases.
```

Without `d_type` support (without the device being formatted with fstype=1, see https://github.com/moby/moby/issues/27358#issuecomment-254066211, https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html)

Having said that, I'm not sure this will actually work on `nfs`. NFS is know to be troublesome in many cases, and not really supported to store your /var/lib/docker directory.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this setup is not supported, and may be better discussed with other in the above locations, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-05-16 13:15 UTC
Labels: platform/arm, version/17.04

**Comment by alexellis** [comment] 2017-05-19 21:37
I have this same issue when attempting to start Docker on a "Pi Cloud" service. @teddy-dubal did you get any further with this?

**Comment by alexellis** [comment] 2017-05-19 21:44
@thaJeztah I created the following post - https://forums.docker.com/t/error-using-nfs-as-graph-driver-root/32527

Is there anyone we can ask for advise / expertise?

**Comment by reyem** [comment] 2017-09-17 20:10
I'm also running a raspberry with nfs and run into the issue. As far as I understood:

* storage driver "overlay" and "overlay2" do need **Supports d_type: true**.

Run "docker info" and you will see if it is supported on your file system. In my case 'docker info' shows **Supports d_type: false**. Changing the storage driver of docker works in my case. I followed this manual to **change it to VFS**: 
https://docs.docker.com/engine/userguide/storagedriver/vfs-driver/#configure-docker-with-the-vfs-storage-driver

Hope this helps somebody looking for a solution.

With this I can use docker on my raspberry pi having an nfs file system. (although I cannot say much about the consequences. VFS seems not to be the most recommended option)

**Comment by teddy-dubal** [comment] 2017-10-05 15:19
@reyem thanks , i will try to night

**Comment by alexellis** [comment] 2017-10-05 15:40
I would recommend you avoid VFS:

> .. and there is no copy-on-write support.

I got past this by creating a loopback filesystem, formatting it as ext4 and mounting it at /var/lib/docker.

**Comment by alexellis** [comment] 2017-12-24 13:08
An alternative which I need to find time to fully test and reproduce in a guide/blog is to use an iSCSI target on another RPi or machine and have that mounted as the root file-system. This way it can be ext4 rather than NFS and still use netboot.

**Comment by alexdrl** [comment] 2018-11-17 15:54
@alexellis how did you do the loopback on for the ext4 filesystem?

**Comment by alexellis** [comment] 2018-11-18 10:56
Create a filesystem as a loopback file then mount it and point Docker at that. You should be able to do this onto the NFS mount too. Just googled this for you - https://www.thegeekdiary.com/how-to-create-virtual-block-device-loop-device-filesystem-in-linux/
