### ISSUE TITLE
engine-api: client.ContainerInspect() returns an empty Networks map

### ISSUE THREAD

**Issue by liranschour** [moby/moby#32309] opened 2017-04-03 07:28 UTC
I am running on current master. When I call client.ContainerInspect(context.Background(), id) I get a valid ContainerJSON but with an empty map of Networks in the NetworkSettings. The container is connected to a single network however and when I call to the cli: $ docker inspect workload-A
I get the following:
```
[
    {
        "Id": "f347b90ab2f6cc4465e42445230c0d01310629f2eeb40a503d2a044ae40dc006",
         ....
"NetworkSettings": {
            "Bridge": "",
            ...
            "Networks": {
                "net1": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "f347b90ab2f6"
                    ],
                    "NetworkID": "b836e737d38e11e1ecb89fc91026ba607a77f72c7740f440a2bd34cc87b9cb7f",
                    "EndpointID": "70cf18cf5802d9271d26d9912b96833c4aba12a4a0c9dd296eeed314fead962c",
                    "Gateway": "169.254.1.1",
                    "IPAddress": "192.168.84.195",
                    "IPPrefixLen": 32,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "ee:ee:ee:ee:ee:ee"
                }
            }
        }
   }
]
```
Is this behavior is expected? How can I fill up Networks map?

Thanks.

**Comment by thaJeztah** [comment] 2019-12-30 16:42
I'm not able to reproduce this issue, so it may have been fixed; I just patched the docker cli to use the `ContainerInspect()` function (instead of `ContainerInspectWithRaw()` which is normally used); https://github.com/docker/cli/blob/6f8070deb2207aa255fd2ae8a1e305e3d79797f6/cli/command/container/inspect.go#L39-L47

```patch
diff --git a/cli/command/container/inspect.go b/cli/command/container/inspect.go
index 4f50e2a0..af6f7e7b 100644
--- a/cli/command/container/inspect.go
+++ b/cli/command/container/inspect.go
@@ -2,10 +2,11 @@ package container

 import (
        "context"
+       "encoding/json"
+       "fmt"

        "github.com/docker/cli/cli"
        "github.com/docker/cli/cli/command"
-       "github.com/docker/cli/cli/command/inspect"
        "github.com/spf13/cobra"
 )

@@ -40,8 +41,14 @@ func runInspect(dockerCli command.Cli, opts inspectOptions) error {
        client := dockerCli.Client()
        ctx := context.Background()

-       getRefFunc := func(ref string) (interface{}, []byte, error) {
-               return client.ContainerInspectWithRaw(ctx, ref, opts.size)
+       c, err := client.ContainerInspect(ctx, opts.refs[0])
+       if err != nil {
+               return err
        }
-       return inspect.Inspect(dockerCli.Out(), opts.refs, opts.format, getRefFunc)
+
+       out, err := json.Marshal(c)
+       if err != nil {
+               return err
+       }
+       fmt.Println(string(out))
 }
```


With that in place, I created a network, created a container using it, and inspected the container


```bash
docker network create net1

docker run -d --rm --name foo --network=net1 nginx:alpine


docker container inspect foo | jq .
```

Which produced a JSON with the network information present;


```json
    "Networks": {
      "net1": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": [
          "a78c987d5bb3"
        ],
        "NetworkID": "77c47efe3fb03b53f76cffdfae37a93662f5c3bd33b8abdf93223a3c8c94e342",
        "EndpointID": "43139041eba98ff0dce7350386f4358e95636bce98036dfe7fd7dee6d9b4e944",
        "Gateway": "172.21.0.1",
        "IPAddress": "172.21.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:15:00:02",
        "DriverOpts": null
      }
    }
```


closing this issue

**Closed by thaJeztah** 2019-12-30 16:42 UTC
