### ISSUE TITLE
volume device: path containing spaces is not working

### ISSUE THREAD

**Issue by michaelsbradleyjr** [moby/moby#36012] opened 2018-01-15 01:34 UTC
**Description**

**Steps to reproduce the issue:**
1. Create a `docker-stack.yml` file with an entry in `volumes:` that specifies a device path using an environment variable:

```yaml
version: '3.5'

services:
  app:
    ...
    volumes:
      - app_data:/some/path

volumes:
  app_data:
    driver: local
    driver_opts:
      device: "${PROJECT_DIR}/"
      o: bind
      type: none
```

2. Try to deploy it.

**Describe the results you received:**

If `$PROJECT_DIR` is a valid path (w.r.t. host) but contains spaces, the volume will not mount. If it does *not* contain spaces, it mounts correctly. 

**Describe the results you expected:**

Paths containing spaces work correctly when used in `configs:`, so I would expect them to work for `device:` paths as well.

**Output of `docker version`:**

```
Docker version 17.12.0-ce, build c97c6d6
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 97
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 81
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 6ihn75g8egezjuqoyxq6tbeqs
 Is Manager: true
 ClusterID: m4joz9gwgxosgi6jnym2cqejb
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: ABSO:3X62:OTBK:HUQR:5JL6:MWYO:MHCQ:PLY2:2BZZ:6OHR:IRBM:U3ET
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 151
 System Time: 2018-01-15T01:29:47.526721789Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macOS 10.12.6, using Docker for Mac Version 17.12.0-ce-mac45 (21669), Channel: edge, dfde464b63.

**Comment by thaJeztah** [comment] 2018-01-15 14:58
You'll have to escape the path so that spaces are escaped.

The `driver_opts` are options specific to a driver, and those are passed as-is to the driver. Docker itself does not transform, or validate those options as it doesn't know what those options do; https://github.com/moby/moby/blob/0bcdeaefcfb47e7c75ec0cf78c029e002ae3e880/api/types/volume/volumes_create.go#L18-L20

This is also documented in the compose-file reference; https://docs.docker.com/compose/compose-file/#driver_opts

>  Those options are driver-dependent - consult the driver’s documentation for more information. Optional.

Closing this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-01-15 14:58 UTC
Labels: platform/desktop

**Comment by michaelsbradleyjr** [comment] 2018-01-15 15:28
Thanks, @thaJeztah. A few questions:

Can you explain what you mean by "escape the path?" I tried a few different things in that regard and nothing worked. I probably failed to do something simple, and am about to trying running it through `printf "%q`", but I want to make sure I have the correct idea.

I read the Compose file reference section on driver_opts (more than once), but didn't glean anything from it that helped me; where can one look to find more information about a *particular* driver, e.g. `local`? I don't recall finding any links to drivers in my searching around before filing this issue.

Thanks again for your feedback, much appreciated.

**Comment by thaJeztah** [comment] 2018-01-15 16:17
You can try using backslashes for spaces (as you would on the command-line) (but I haven't tried - the backslashes may need to be double-escaped);

```
/foo\ path\ with\ spaces/subdir/subdir/
```

**Comment by michaelsbradleyjr** [comment] 2018-01-15 16:24
I tried manually adding backslashes, didn't work, will try double-escaped next. I tried running the path-with-spaces through `printf "%q"` (which introduces backslashes) and setting that as the variable value, didn't work. In both cases, I'm seeing errors in the output of `docker stack ps` like:

Rejected less than a second ago "error while mounting volume with options: type='none' device='/my/path/with/spaces/a\ b\ c/project/' o='bind': no such file or directory". The directory definitely exists, so it's not a case of simple user error.

**Comment by michaelsbradleyjr** [comment] 2018-01-15 16:32
Tried all sorts of variants with quotes, no quotes, double-escaped, and so on. Nothing works. If a path without spaces is used instead, works like a hose.  It's possible the local driver itself has a limitation or bug re: paths containing spaces. What's the right place–context to a file report?

**Comment by thaJeztah** [comment] 2018-01-15 16:35
> The directory definitely exists, so it's not a case of simple user error.

Note that mounts always work from the _daemon_ host, not from your client. On Docker for Mac, the daemon runs inside a LinuxKit VM, and paths from your host are shared with that VM, but on a slightly different location than on your local (macOS) machine (if I'm not mistaken, the path is something like: `/host_mnt/<path on your mac>`.

When using the -v <hostpath>:<container-path>` or `--mount source=...,target=...` options, Docker for Mac automatically translates those to the correct path, but (as mentioned) the same doesn't happen with driver options, so likely that may be related

You can check if the path you're trying to mount exists inside the VM by starting a container that mounts the VM's host:

```
docker run -it --rm -v /:/host/ alpine sh
```

That should show you the VM's filesystem inside the `/host` path inside the container

**Comment by michaelsbradleyjr** [comment] 2018-01-15 16:38
Path definitely exists inside the vm, checked it in the manner you suggested, and I can read/write files on that path.

**Comment by michaelsbradleyjr** [comment] 2018-01-15 16:48
This works too:

```shell
cd "/my/path/with/spaces/a b c/project"
docker run -it --rm -v "$PWD":/host/ alpine sh
```

In the container, I'm seeing everything I expect to see under `/host/`.

**Comment by thaJeztah** [comment] 2018-01-15 17:01
I tried this, and this seems to work for me;

Create a directory and test file;

```bash
mkdir -p ~/test/repro-36012/foo\ bar\ baz/
cd ~/test/repro-36012/
echo 'hello' > foo\ bar\ baz/bla.txt 
```


Create a compose file:

```bash
cat > docker-compose.yml -<<'EOF'
version: '3.5'

services:
  app:
    image: nginx:alpine
    volumes:
      - app_data:/some/path

volumes:
  app_data:
    driver: local
    driver_opts:
      device: "/Users/sebastiaan/test/repro-36012/foo\ bar\ baz/"
      o: bind
      type: none
EOF
```

Deploy stack:

```bash
docker stack deploy -c docker-compose.yml repro36012

Creating network repro36012_default
Creating service repro36012_app
```

And verify the directory is mounted;

```bash
docker exec repro36012_app.1.9y4log3gyl3fskthjzw4bhynv cat /some/path/bla.txt 
hello
```

**Comment by michaelsbradleyjr** [comment] 2018-01-15 19:33
Just to follow-up:

The only things that needed to be changed:

1. redirect that output of `docker-compose config ...` to a temp file rather than capture it into a variable.
2. `cat` that temp file and pipe to `--compose-file -` rather than piping an `echo` of the variable.

I didn't need to employ backslashes or anything else. Even though I was using `"$(...)"` when capturing and echoing the output of `docker-compose` to/from a variable, there must have been something subtle happening to the path-with-spaces. Anyway, it's working now, thanks again.

**Comment by thaJeztah** [comment] 2018-01-15 19:37
Good to hear you got it working!
