### ISSUE TITLE
Image tags are reduced to a single tag after pushing/pulling

### ISSUE THREAD

**Issue by maarten-kieft** [moby/moby#34679] opened 2017-08-30 14:51 UTC
**Description**
I have created an image with 2 tags like _1.0_ and _latest_. When I push & pull it to/from the docker hub it has only 1 tag remaining. It has only the tag from which I pulled it from.

**Steps to reproduce the issue:**
1. Build a new image with 2 tags: 
`docker build -t myusername/myimage:latest -t myusername/myimage:1.0`
2. Inspecting the image which we just build
`docker inspect [id of the image]`
3. Push the image to docker hub:
`docker push myusername/myimage:latest`
`docker push myusername/myimage:1.0`
4. Pull it
`docker pull myusername/myimage:latest`
5. Inspecting the image we just pulled
`docker inspect [id of the image]`

**Describe the results you received:**
Locally where the image is created
`"RepoTags": ["myusername/myimage:1.0","myusername/myimage:latest"]`
On the machine where the image is pulled
`"RepoTags": ["myusername/myimage:latest"]`

**Describe the results you expected:**
I expected that the repo tags don't change. So when I pull and inspect it would be:
`"RepoTags": [ "myusername/myimage:1.0","myusername/myimage:latest"]`

**Additional information you deem important (e.g. issue happens only occasionally):**
I build the image on windows with linux containers. I pull the image on a raspberry pi. _When I remove the image from the machine where I create it (so on the windows machine) and pull it from the hub there I see the same results_

**Output of `docker version`:**
Windows
```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:48:20 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
Linux raspeberry pi
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/arm

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/arm

```
**Output of `docker info`:**
Windows
```
Containers: 27
 Running: 0
 Paused: 0
 Stopped: 27
Images: 204
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 187
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 973.8MiB
Name: moby
ID: YC75:5RVU:ARNC:FH3G:HYPX:ABQU:X7GL:3ASA:Y3RS:22YU:SICN:ZE6S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Linux raspeberry pi
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-v7+
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 925.8 MiB
Name: lago
ID: JUF6:H3UE:4DFU:GZ7H:QIXT:2HZV:35OS:GB56:FUIA:VLG7:YSKR:BJBH
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by maarten-kieft** [comment] 2017-08-31 18:38
Updated issue with all required info

**Comment by maarten-kieft** [comment] 2017-09-12 17:09
Any update on this?

**Comment by thaJeztah** [comment] 2017-09-12 18:22
This is expected, but may be a bit confusing: when pulling an image you explicitly ask docker to pull the tag you specified (e.g. `myimage:foo`). The other tag is not pulled on the machine you pulled from,  so won't be available there. 

If you pull the other tag (`docker pull myimage:bar`), the repotags should be visible for both tags in the image inspect.

Keep in mind that tags are _mutable_; most notably, the `:latest` tag usually is a tag that's used to indicate the current version of an image (by convention, but it's fully up to the image's author), so if a more recent `:latest` image was pushed, your `1.0` and `:latest` tags may be referring to different images when pulled on the other machine.

I'll close this issue, because this is not a bug, but feel free to continue the conversation if you need more information

**Closed by thaJeztah** 2017-09-12 18:22 UTC
Labels: area/builder, area/distribution, platform/arm, version/17.06

**Comment by maarten-kieft** [comment] 2017-09-13 06:56
Thanks @thaJeztah for the explanation. I was already suspecting it, but I couldn't figure out for sure. The problem that I'm now facing is that I would like to let pull people the latest version in my documentation so I refer to the latest tag. But during the life time of the image / container, I have no idea if the latest is still the latest without pulling.

I thought that was the reason you could apply multiple tags to an image. So beside it had the latest tag it would also contain a version specific tag (like 1.4) Why should I apply multiple tags ? Only for pushing it multiple times?

**Comment by thaJeztah** [comment] 2017-09-13 09:38
There's various uses for having multiple tags for an image, for example:

- tag an image both by a version number (`:v1.0.0`) and a git-commit (`: f5ec1e2936dcbe7b5001c2b817188b095c700c27`)
- provide "granular" versioning for your images (e.g., `:v1` pointing to latest `v1.x.x` version, `:v1.0` for the latest `:v1.0.x` version, and `v1.0.0` pointing to _exactly_ version 1.0.0)
- having a `:latest` tag to refer to the most up-to-date "stable" version of your image

Although there are some "conventions" that are widely used, _how_ you use those tags are completely up to you.

The `:latest` tag is a convenience ("run `docker pull myimage` to get the image I tagged `:latest`, which is likely what you're looking for"), however, also has a downside: `:latest` _today_ may be different than `:latest` _tomorrow_, so you don't know what you're running, which results in a non-reproducible environment.

For that reason, in production, it's recommended to specify exactly which version of an image you want to be running; this can be either through using the exact tag (`image:v1.0.0`), or even better (since tags are mutable, so `:v1.0.0` be updated), by using an "immutable" reference; use the image's digest (`image@sha256:<hash>`), which is what is done when deploying a service with `docker service create..`. Doing so allows you to first _test_ an image in your staging environment before deploying to production, and have the guarantee that production is running exactly the same version of the image that you tested.

**Comment by maarten-kieft** [comment] 2017-10-27 07:51
For other readers: I ended up using a combination of tags and labels. Labels allow me to write down the version, so I know which version the latest actually is.
