### ISSUE TITLE
Docker interactive console often freezes on Windows when printing large output

### ISSUE THREAD

**Issue by sandersaares** [moby/moby#32984] opened 2017-05-03 06:03 UTC
**Description**

When a large amount of text is written to standard output by something executed in a `docker run -it` session, the console freezes in the middle of printing the output and no further input or output takes place in that console.

**Steps to reproduce the issue:**

1. `docker run -it --rm microsoft/windowsservercore powershell`
1. `Get-WMIObject Win32_Process`

Reproduces most of the time.

**Describe the results you received:**

Console freezes in the middle of listing the command output.

**Describe the results you expected:**

Command output is printed and I am able to continue using my interactive session.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens very often when nontrivial amounts of output are printed (several pages are almost guaranteed to freeze it).

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Wed Apr 12 19:43:25 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Wed Apr 12 19:43:25 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 17.05.0-ce-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 23.92GiB
Name: jose
ID: 7YUR:ZJ6B:47ZU:ZJ2G:SNCO:FDE3:QMAX:BXBK:F3H2:3RYF:NRM2:VRVD
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine.

**Comment by friism** [comment] 2017-05-03 13:48
cc @jhowardmsft @johnstep

**Comment by jhowardmsft** [comment] 2017-05-04 03:01
Yes, known. It's specific to Hyper-V containers. There's a platform fix due in 5B (very soon). There's another issue which is a duplicate of this (possibly in D4W).

**Closed by jhowardmsft** 2017-05-04 03:01 UTC
Labels: platform/windows, version/17.05

**Comment by jhowardmsft** [comment] 2017-05-04 03:02
Dup of https://github.com/docker/for-win/issues/199
