### ISSUE TITLE
Cpu usage not displayed with $docker start

### ISSUE THREAD

**Issue by gouravrattihalli** [moby/moby#36948] opened 2018-04-25 17:50 UTC
**Description**

I'm working on container migration in Mesos and stumbled upon a bug. 
When I restore a container, with `docker create` and then `docker start`, the docker stats does not show up CPU usage. Top shows cpu usage for the process running inside the container, so I believe docker stats is unable to pull up the information. `docker stats` shows CPU usage if I start the container with `docker run`.

**Steps to reproduce the issue:**
1. `docker create`
2. `docker start`
3. `docker stats`

**Output of `docker version`:**

Docker Version: I'm not using the latest docker since custom "checkpoint-dir" is broken.
 
```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker stats`:**
![screenshot from 2018-04-25 13-38-50](https://user-images.githubusercontent.com/19934308/39262944-dd71e032-488e-11e8-9a5b-489f59898a2b.png)

**Comment by thaJeztah** [comment] 2018-04-25 18:29
I'm not able to reproduce this on a current version of Docker; is there anything in the logs that may be helpful (preferably in debug mode)?

Note that docker CE 17.06 has reached EOL long time ago, so no more fixes will be included for that version of docker (Docker EE (Enterprise Edition) 17.06 is still actively maintained)

**Comment by gouravrattihalli** [comment] 2018-04-25 18:51
Hi,
I don't think the problem exists in the current version of docker. My only reason to use docker CE 17.06, is the ability to provide custom "checkpoint-dir" which is required for restoring containers. "checkpoint-dir" seems to be broken in the current version of docker. Please let me know if I'm wrong about this.

**Comment by thaJeztah** [comment] 2018-04-25 19:01
Custom checkpoint dirs in 17.06 CE are prefixed by the container-id (see https://github.com/moby/moby/issues/34601), which got reverted in https://github.com/moby/moby/pull/35694, however checkpoint support is being fully redesigned in containerd 1.0+, and is not compatible with the old, experimental implementation.

**Comment by cpuguy83** [comment] 2018-04-26 10:40
`docker run` is exactly the same as `docker create` + `docker start`.
It's the same exact 2 API calls.

**Comment by gouravrattihalli** [comment] 2018-04-26 15:47
@cpuguy83 Yes I know and it works perfectly fine if I use `docker create`+`docker start` for regular containers. But if I start with checkpoints the problem occurs.

**Comment by cpuguy83** [comment] 2018-04-26 16:41
I see, that makes more sense to me now.

**Comment by thaJeztah** [comment] 2021-06-30 19:17
Closing as this went stale

**Closed by thaJeztah** 2021-06-30 19:17 UTC
Labels: kind/experimental, status/more-info-needed, version/17.06
