### ISSUE TITLE
docker build --pull 403 Forbidden with buildkit+invalid mirror config

### ISSUE THREAD

**Issue by fhaefemeier** [moby/moby#44939] opened 2023-02-06 21:30 UTC
### Description

After upgrade to version 23.0 a working `docker build` call is no longer working. It ends up with the error message
```
 => ERROR [internal] load metadata for docker.io/library/rust:1.67                                                                                                                                                   30.0s
------
 > [internal] load metadata for docker.io/library/rust:1.67:
------
rust:1.67: pulling from host <registry mirror> failed with status code [manifests 1.67]: 403 Forbidden
```
`<registry mirror>` is a pull through cache registry using Nexus. Docker daemon log shows the line
```
level=info msg="trying next host" error="failed to do request: Head \"https://registry-1.docker.io/v2/library/rust/manifests/1.67\">
```
Registry mirror seems to  be ignored. Due to network restriction `*.docker.io` is not directly accesable from the build host.
`docker pull` is working as expected. 

After downgrade back to 20.10.23 everything is working as before. 

### Reproduce

1. Install / Upgrade to docker 23.0.0
2. Configure pull through cache as registry mirror in daemon
3. Create dockerfile with a base image which isn't pulled yet
4. docker build --pull -f ./Dockerfile .

### Expected behavior

`docker build --pull` pull the base image from registry mirror and build the image.

### docker version

```bash
Can't get the correct information because of downgrade the version and forgot to call it before.
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 212
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  selinux
  cgroupns
 Kernel Version: 6.1.9-200.fc37.x86_64
 Operating System: Fedora Linux 37 (Thirty Seven)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.757GiB
 Name: docker-runner
 ID: VFI2:A2IA:7ETO:NABG:I5WC:BWOH:2M3H:WAQV:IAAV:IFOO:WQJV:3YLW
 Docker Root Dir: /srv/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.examples.dev/
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2023-02-07 00:26
Is the build using BuildKit on 20.10 as well, or is it using the legacy builder in that case?

**Comment by thaJeztah** [comment] 2023-02-07 00:29
if 20.10 is using the legacy (non-BuildKit) builder, possibly its related to authenticating. ISTR @tonistiigi mentioned that the CLI will connect to docker hub for an access token (which may not work if `*.docker.io` is blocked at the network level) 🤔

**Comment by neersighted** [comment] 2023-02-07 19:50
Also, could you please test 23.0.0 with `DOCKER_BUILDKIT=0`?

**Comment by fhaefemeier** [comment] 2023-02-08 20:28
> Is the build using BuildKit on 20.10 as well, or is it using the legacy builder in that case?

Comparing to my test below, I would say 20.10 use the legacy build.  
Calling `docker build --pull ...` with 20.10 it works, with `DOCKER_BUILDKIT=1` don't. The only difference to below it fails fast.
```
$ docker build --pull -f Dockerfile.pull .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM rust:1.67
1.67: Pulling from library/rust
Digest: sha256:a906d23028fbd5623395ea1e78dacaa3ed33627ee42e9fc38d34788a42985116
Status: Downloaded newer image for rust:1.67
 ---> 4de395b392b4
Successfully built 4de395b392b4
$ env DOCKER_BUILDKIT=1 docker build --pull -f Dockerfile.pull .
[+] Building 0.1s (3/3) FINISHED                                                                                                                                                                                           
 => [internal] load build definition from Dockerfile.pull
 => => transferring dockerfile: 122B
 => [internal] load .dockerignore
 => => transferring context: 2B
 => ERROR [internal] load metadata for docker.io/library/rust:1.67
------
 > [internal] load metadata for docker.io/library/rust:1.67:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 1.67]: 403 Forbidden
```

> Also, could you please test 23.0.0 with `DOCKER_BUILDKIT=0`?

I tested both. First failed, second was successful
```
$ docker build --pull -f Dockerfile.pull .
[+] Building 30.1s (3/3) FINISHED
 => [internal] load build definition from Dockerfile.pull
 => => transferring dockerfile: 116B
 => [internal] load .dockerignore
 => => transferring context: 2B
 => ERROR [internal] load metadata for docker.io/library/rust:1.67
------
 > [internal] load metadata for docker.io/library/rust:1.67:
------
Dockerfile.pull:1
--------------------
   1 | >>> FROM rust:1.67
   2 |     
--------------------
ERROR: failed to solve: rust:1.67: pulling from host docker.examples.dev failed with status code [manifests 1.67]: 403 Forbidden
```
```
$ env DOCKER_BUILDKIT=0 docker build --pull -f Dockerfile.pull .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM rust:1.67
1.67: Pulling from library/rust
Digest: sha256:a906d23028fbd5623395ea1e78dacaa3ed33627ee42e9fc38d34788a42985116
Status: Downloaded newer image for rust:1.67
 ---> 4de395b392b4
Successfully built 4de395b392b4
```
```
$ docker version
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:47:38 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:44:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by neersighted** [comment] 2023-02-08 20:44
Okay, I think changing the title is actually a mistake, as this is not net-new for 23.0, but reproduces on 20.10. The only reason that this is a sharper edge now is because BuildKit is on by default in 23.0.

**Comment by thaJeztah** [comment] 2023-02-09 09:00
@tonistiigi is that with access to docker hub blocked?

>  Due to network restriction `*.docker.io` is not directly accesable from the build host.

**Comment by thaJeztah** [comment] 2023-02-09 09:08
I saw a mention of a `BUILDKIT_NO_CLIENT_TOKEN=true` env-var  in https://github.com/docker/buildx/issues/1613#issuecomment-1423421335 which (I think) is to prevent the client from trying to get an access token from docker hub (https://github.com/moby/moby/issues/44939#issuecomment-1419988135).

@fhaefemeier does it work if you set that env-var when running the build?


```bash
BUILDKIT_NO_CLIENT_TOKEN=true docker build --pull -f ./Dockerfile .
```

**Comment by tonistiigi** [comment] 2023-02-09 09:17
@thaJeztah The error shows `HEAD` request against the manifest endpoint. The client makes no requests to there in any `build` command conditions. The client can only do auth requests to get short-lived tokens.

> is that with access to docker hub blocked?
> Due to network restriction *.docker.io is not directly accesable from the build host.

If you have configured a mirror that doesn't have the data and you also do not have access to `docker.io` for the fallback then where is the data supposed to come from?

It might be that this has nothing to do with mirrors but containerd pull libraries vs Nexus registry. Considering GCR is working fine, the mirror code should be fine.

**Comment by fhaefemeier** [comment] 2023-02-09 19:56
@thaJeztah I will test your request tomorrow.

@tonistiigi What do you mean with "Hmm, fallback seems to be working for me." and why do you extend the title with "invalid mirror config". In my environment the mirror is proper configured. The mirror hostname `docker.examples.dev` is not the real one, I masked it. 

Before I upgrade, `docker build --pull` are working as expected with exact the same configuration. The mirror server (Nexus) has well access to hub and the build environment has access to the mirror. Only access to `*.docker.io` directly is forbidden from the build environment. There are two different systems with different but working network access.

BTW, `docker pull ...` is working well. Both versions...

> If you have configured a mirror that doesn't have the data and you also do not have access to docker.io for the fallback then where is the data supposed to come from?

Because I tested several times this scenario the image is cached in Nexus! No need to access hub from Nexus anymore... but as written above Nexus has access to docker.io and can take images from there... 

I will test tomorrow the different scenarios with debug enabled in the daemon. Please give me advise if I should enable or set additional parameters to support your analysis.

**Comment by fhaefemeier** [comment] 2023-02-12 17:37
After several tests and from different point of views let me summarize the facts:

1.  buildkit (`DOCKER_BUILDKIT=1`) use different workflow to pull an unknown image compared to `DOCKER_BUILDKIT=0` or pull command. First a HEAD call is done against the mirror URL. This fails and it falls back to call `*.docker.io` directly. The reason: The reverse proxy configuration which handle the mirror calls does not expect HEAD requests in this context.

1.  Root cause of `403 Forbidden` (reported first) is a check if `user_agent is docker` in the reverse proxy config. Otherwise the call is denied. As I can see in the debug log of the daemon user agent is set to `containerd`.

So I have to go back and reconfigure/adjust the reverse proxy before further investigation. I assume the issue will no longer happen and for now the issue can be closed from my side.

I have to thank @thaJeztah and @tonistiigi for your time and input.

**Comment by neersighted** [comment] 2023-02-12 18:00
This does confirm that the issue is a misbehaving mirror. Behaving differently based on user agent is definitely a way to get into trouble -- the direction we are going will likely result in more and more pull code using the containerd client instead of the legacy distribution client, as I understand it.

I'm going to close this for now, but please do comment back if the diagnosis you provided turns out to be incorrect.

**Closed by neersighted** 2023-02-12 18:00 UTC
Labels: status/0-triage, kind/bug, area/builder/buildkit, version/23.0
