### ISSUE TITLE
Failed to start docker process - Kubernetes node

### ISSUE THREAD

**Issue by azharudheen** [moby/moby#41351] opened 2020-08-13 15:22 UTC
Step 1. kubectl get nodes -o wide
k8s-xxxxxxxxxxx NotReady agent 314d v1.13.4 x.x.x.x. Ubuntu 16.04.6 LTS 4.15.0-1092-azure docker://Unknown

Now the question is why docker://Unknown

Logged in to VM and run systemctl restart docker and systemctl status docker ==== > Nothing worked out

When docker is restarted, we see the below error: 

Aug 13 14:50:28 k8s-xxxxxxxxxxx dockerd[32071]: time="2020-08-13T14:50:28.238289148Z" level=error msg="Failed to restore container d8c1fd34d485d0ccdb61c609705d1e43ca97bd7ab70f64b2cd2029c2a3b89499 with containerd: error getting containerd task for container: failed to open stdout fifo: error creating fifo /var/run/docker/containerd/d8c1fd34d485d0ccdb61c609705d1e43ca97bd7ab70f64b2cd2029c2a3b89499/init-stdout: no such file or directory"

Only rebooting or redeploying the Azure VM brings back things to normal. But again after sometime (same day or after a day or 2), we get the same error again.

**Comment by thaJeztah** [comment] 2020-08-13 17:30
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

**Comment by thaJeztah** [comment] 2020-08-24 12:50
Closing this ticket as there's not enough information for anything actionable

**Closed by thaJeztah** 2020-08-24 12:50 UTC
Labels: status/more-info-needed
