### ISSUE TITLE
os.renames moved a directory from one place to another place in a container, but files in it disappeared.

### ISSUE THREAD

**Issue by zhangzhen** [moby/moby#35214] opened 2017-10-16 13:12 UTC
A flask-based backend is wrapped in a python3-alpine container. This backend has a job to move a upload directory /data/uploads/A to another directory /data/projects/B using os.renames. The directory /data is linked to a host directory /data. Moving a directory works well on docker version 1.12 with the aufs storage driver, but the directory can be moved but files in it get lost on the latest docker-ce with the overlay2 storage driver. Could one help me solve this problem?

Cheers,
Zhen Zhang

**Comment by thaJeztah** [comment] 2017-10-17 12:36
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by lzubiaur** [comment] 2017-10-17 14:42
I can't reproduce the issue. I can move directories with `os.rename` without losing any files on the latest docker using the overlay2 driver running in VirtualBox. 

As @thaJeztah said you should provide the steps to reproduce the issue or it will be difficult to solve it.

```
docker@default:~/dev$ docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: default
ID: GNHQ:VFMY:2IJJ:3J3H:NEIW:UJ6M:ECDB:MHUE:PU3Q:LUJO:SY62:U6EX
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 27
 System Time: 2017-10-17T14:33:32.804105635Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Dockerfile

```
FROM alpine:3.5
WORKDIR /app
RUN apk add --no-cache python
CMD ["python", "app.py"]
```

**Comment by zhangzhen** [comment] 2017-10-18 02:38
I found that this issue is not caused by docker. My frontend is based upon vue. vue-dropzone is used to upload files. Frontend code is built with webpack and deployed to server with docker-compose. This issue is caused by accidentally posting a removefile request right after submitting a runtask with uploaded files.
Thank you for your help!

**Comment by thaJeztah** [comment] 2017-10-23 16:05
Thanks for the update @zhangzhen, I'll close this issue then 👍

**Closed by thaJeztah** 2017-10-23 16:05 UTC
Labels: status/more-info-needed
