### ISSUE TITLE
Docker exec command not generating .sh file

### ISSUE THREAD

**Issue by chanduBS** [moby/moby#34201] opened 2017-07-20 12:15 UTC
i have run the "**docker exec -it <docker-image> bash**"
and i tried to execute the file.:  **sh <fileame.sh>**
filename.sh is not available in the path , it showing File "**Can't Open filename.sh**" Error.

Any solution?

**Comment by thaJeztah** [comment] 2017-07-20 13:01
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

When asking your question there, I recommend providing more information as well, because the current information is not enough to help;

- What image are you running (and `exec`-ing into?) if this is not a public image, provide a minimal Dockerfile to illustrate your problem
- What version of Docker are you using, and what platform are you running on (output of `docker info`, `docker version`)
- Your `docker exec` command looks incomplete; the format is `docker exec -it <container-name> <command to run>`; either `command` or `container-name` is missing

I'm going to close this issue because this is not a bug, but feel free to continue the conversation if you need more info

**Closed by thaJeztah** 2017-07-20 13:01 UTC
