### ISSUE TITLE
Unable to Join a Docker Swarm

### ISSUE THREAD

**Issue by kalaga20** [moby/moby#30584] opened 2017-01-31 07:43 UTC
**Description**

**Steps to reproduce the issue:**
1.run: docker swarm init --advertise-addr "MANAGER-IP" on Manager Node.
2.run: docker swarm join-token worker to show the join command
3.On Another node(Worker), run the join command

**Describe the results you received:**
Error response from daemon: remote CA does not match fingerprint. Expected: e90670e77a50fdc77f3169ff0b1d314a3d4954baff73947f73c754fbe9c695a8

**Describe the results you expected:**
This node joined a swarm as a worker.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
**Manager Node**
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Worker Node**
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
**Manager Node**
Containers: 10
 Running: 1
 Paused: 0
 Stopped: 9
Images: 324
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-8:16-3932275-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 16.17 GB
 Data Space Total: 107.4 GB
 Data Space Available: 31.8 GB
 Metadata Space Used: 20.97 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /u01/HomeDir/hadoop/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /u01/HomeDir/hadoop/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: onz791qlievuu3ud697qq7a0y
 Is Manager: true
 ClusterID: trz1fzwdo00mlb7aec31nk4u5
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.18.228.235
 Manager Addresses:
  172.18.228.235:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.829 GiB
Name: mydomain
ID: UXEJ:VUXY:BUDI:7X7Q:GJUS:YLFM:E6Q3:FYLI:BV5P:HJHO:7IUV:5BWC
Docker Root Dir: /u01/HomeDir/hadoop/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://myproxy.com/
Username: kalaga20
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Worker Node**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-8:17-3670114-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.282 GB
 Data Space Total: 107.4 GB
 Data Space Available: 70.25 GB
 Metadata Space Used: 3.457 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /u01/Homedir/devops/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /u01/Homedir/devops/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.797 GiB
Name: mymachine
ID: URAX:JLIX:MMJM:J6QN:NC43:VFHM:2RPQ:24UL:P5A2:6MBV:7AJ4:BJ5U
Docker Root Dir: /u01/Homedir/devops/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://myproxy.com/
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Nranc** [comment] 2017-04-04 10:22
Are there any updates?

**Comment by rakshazi** [comment] 2017-09-18 18:51
Same problem here, any updates?

**Comment by thaJeztah** [comment] 2017-09-18 20:29
@rakshazi are you also using a proxy (I see @kalaga20 is using a proxy); if so, I highly suspect this issue may be due to a MITM proxy replacing certificates.

**Comment by kmurudi** [comment] 2017-11-03 00:09
same issue faced.

**Comment by thaJeztah** [comment] 2017-12-30 15:42
Is this still an issue on the current (17.12) release of docker? Also; is the problem resolved if you add the managers to `NO_PROXY`?

**Comment by rakshazi** [comment] 2017-12-30 17:59
For me issue was resolved by using correct interface (eth1 - private network - instead of eth0 - public network)

**Comment by thaJeztah** [comment] 2017-12-30 18:34
thanks @rakshazi, reading back this issue, I don't think there's a bug at hand here, and nothing actionable, so let me close this one

**Closed by thaJeztah** 2017-12-30 18:34 UTC
Labels: area/swarm, status/more-info-needed, version/1.13

**Comment by thaJeztah** [comment] 2018-12-19 12:39
ping @marcosnils - this a known issue? I'm not sure how networking is rigged up on PWD

**Comment by marcosnils** [comment] 2018-12-19 13:22
@MrGoodfix @thaJeztah make sure to use the output from the command that you run in the terminal in the `node2` and not the example snippet that you see in the documentation

Check the sentence that states:
 
>In the output of your swarm init, you are given a command in the middle that looks like docker swarm join -token SWMTKN-X-abcdef..... which you use to join workers nodes to the swarm. You are also given a second command docker swarm join-token manager for adding additional managers.

You're probably using the `docker swarm join` command that's listed in the doc which is just an example.

**Comment by chjaniet** [comment] 2019-02-12 08:17
Hi I am getting the same error similar to "kalaga20".  I'm using the output from the command that run in the terminal shown by the system.
Environment:
Two Debian VM running in VMware workstation
Both Debian version: debian 9.5 stretch
Docker version 18.06.1-ce

Any help, please. Thanks
![debian core client-2019-02-08-16-06-46](https://user-images.githubusercontent.com/44694126/52621073-56c85680-2ee1-11e9-91da-fc49d47109df.png)

**Comment by codification-io** [comment] 2019-02-22 00:28
This has just happened to me. I have used my 'join swarm' command to create a cluster of 6 nodes -- 3 managers, and 3 workers. I'm trying to add a 7th node for dtr, so first I use the exact same join script as I use for my workers and I get the fingerprint error.

In my case, this seems to be caused by having a node restart then rejoin on the same ip address. It appears that docker-ee doesn't like this any more than ssh likes it (and I suspect it's for the same reasons).

**Comment by smarkm** [comment] 2019-06-01 11:05
Hi @chjaniet, the token and IP address are host `swarmclient`? if you want to join `swarmclient` to an exists swarm you need to execute the command that the swarm show you on host `swarmclient`

**Comment by Joginder22** [comment] 2020-06-23 11:56
Same issue faced with  Version: 19.03.6-ce. 

Earlier it was working fine. I was using terraform and aws user_data to spin-up swarm cluster. Today somehow the same cluster is not coming up stating same error.

**Comment by Dostoevskey** [comment] 2023-05-24 13:50
Hi there! 
The same issue was faced on 24.0.1. My setup is 3 "bare metal" Linux machines connected to the same physical LAN. 
The third node can't join - got back: 
`$ docker swarm join --token SWMTKN-1-3ak4ddp15zk0bugbc544k3p2deboes12j1hynr65ysry5ll1sb-829pg5cze63toozpc3w4vwm8q 192.168.0.152:2377
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.`


```
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: gfy434xcdg7zwftn5ajv19ah3
  Is Manager: true
  ClusterID: k8g00uxv2ecna7l0z3gfmiqgs
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.0.152
  Manager Addresses:
   192.168.0.152:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-42-generic
 Operating System: Ubuntu 22.04.2 2023.04.04 LTS (Cubic 2023-04-04 14:48)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.73GiB
 Name: us-alienware
 ID: f85bcf7b-0616-46f2-8c8e-1ac91ec1a277
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by cazacubogdan** [comment] 2023-11-01 13:40
> For me issue was resolved by using correct interface (eth1 - private network - instead of eth0 - public network)

And what exactly did you do to solve this?
