### ISSUE TITLE
"docker build" requires exactly 1 argument.

### ISSUE THREAD

**Issue by sjwl** [moby/moby#38368] opened 2018-12-13 21:34 UTC
**Description**

**Steps to reproduce the issue:**
1. cd to location of Dockerfile
2. `docker build`

**Describe the results you received:**
`"docker build" requires exactly 1 argument.`

**Describe the results you expected:**
treat `docker build` as `docker build .`

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by RaviTezu** [comment] 2018-12-14 09:34
@sjwl @GordonTheTurtle  I would like to take this up.

**Comment by thaJeztah** [comment] 2018-12-14 10:21
This is by design; `docker build` requires you to specify the path to build from. Automatically assuming the current directory will be a breaking change, and can result in situations where the location of the build-context was accidentally left out, e.g.

```
docker build ${ENV_VAR_THAT_WASNT_SET}
```

So, I don't think we should change this.


@tonistiigi

**Comment by thaJeztah** [comment] 2018-12-14 10:47
@RaviTezu if you're looking for something to work on; this one just came up; https://github.com/moby/moby/issues/38351 🤗

**Comment by thaJeztah** [comment] 2018-12-17 13:02
I'll close this ticket, because of the above, but feel free to continue the conversation.

**Closed by thaJeztah** 2018-12-17 13:02 UTC
Labels: area/builder, kind/enhancement
