### ISSUE TITLE
I wonder, how can I make container for raspAP?

### ISSUE THREAD

**Issue by dockerPractice** [moby/moby#35605] opened 2017-11-27 00:55 UTC
I use Raspbian-Stretch-Light, Hypriot OS on RaspberryPi3, because of constructing AP on Docker Container. So I found the Dockerfile that using raspAP package.
Like this(it was modified just a little bit by me),

    # FROM resin/rpi-raspbian:wheezy
    FROM armv7/armhf-ubuntu:yakkety
    # FROM hypriot/rpi-node:8.1.3-onbuild
    
    MAINTAINER Gary Ritchie <gary@garyritchie.com>
    
    # RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0x908332071dd2e32e
    # RUN echo "deb http://deb.best-hosting.cz/debian/ wheezy main" > /etc/apt/sources.list.d/best-hosting.list
    
    #RUN wget https://archive.raspbian.org/raspbian.public.key -O - | sudo apt-key add -
    
    ########
    # RUN echo "deb http://archive.raspbian.org/raspbian wheezy main contrib non-free" > /etc/apt/sources.list
    # RUN echo "deb-src http://archive.raspbian.org/raspbian wheezy main contrib non-free" >> /etc/apt/sources.list
    
    # RUN echo "deb http://httpredir.debian.org/debian wheezy main" > /etc/apt/sources.list
    # RUN echo "deb http://httpredir.debian.org/debian wheezy-updates main" >> /etc/apt/sources.list
    # RUN echo "deb http://security.debian.org wheezy/updates main" >> /etc/apt/sources.list
    
    RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -q -y install \
            nano \
            sudo \
            net-tools \
            wireless-tools \
            lighttpd \
            php-cgi \
            git \
            && apt-get clean
    RUN lighty-enable-mod fastcgi-php
    RUN /etc/init.d/lighttpd restart
    
    # AP stuff
    RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -q -y install \
            wget \
            unzip \
            hostapd \
            bridge-utils \
    #       rfkill \
            hostap-utils \
            iw \
            dnsmasq \
            wpasupplicant \
            && apt-get clean
            # wicd-cli \
    
    ## Add the following to the end of /etc/sudoers:
    
    RUN echo 'www-data ALL=(ALL) NOPASSWD: ALL\n%www-date ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/www-data
    
    RUN chmod 0440 /etc/sudoers.d/www-data
    RUN git clone https://github.com/billz/raspap-webgui /var/www/ap
    RUN chown -R www-data:www-data /var/www
    
    EXPOSE 80
    EXPOSE 100
    
    ENTRYPOINT ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]

and I used Makefile for build. Like this,

    # makefile

    raspap: .build
            touch /etc/dnsmasq.conf
    ## volume-mount all the networking things
            -@docker rm -f $@ > /dev/null
            docker run -d \
                    --restart=always \
                    --net="host" \
                    --privileged \
                    --name raspap \
                    -p 80:80 \
                    -v /etc/network/interfaces:/etc/network/interfaces \
                    -v /etc/hosts:/etc/hosts \
                    -v /etc/dnsmasq.conf:/etc/dnsmasq.conf \
                    -v /etc/wpa_supplicant:/etc/wpa_supplicant \
                    -v /etc/hostapd:/etc/hostapd \
                    raspap
    
    build: .build
    
    .build: Dockerfile
            docker build --rm=true -t raspap .
            @docker inspect -f '{{.Id}}' raspap > .build
    
    clean:
            docker rm -f raspap
    
    .PHONY: clean

In the end, I finished to make container but the container restarted infinitely and there is no port forwarding like this...

result [# docker ps]

    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                            PORTS               NAMES
    2b363a63d00d        raspap              "lighttpd -D -f /e..."   12 minutes ago      Restarting (255) 35 seconds ago                       raspap

But the container port is not forwarding, you see. How can I make container with port forwarding?

**Comment by dockerPractice** [comment] 2017-11-27 01:02
In addition, I erased the docker run option [--net="host"] and then succeeded to port forwarding.
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS                         NAMES
9e2d7f0d5e82        raspap              "lighttpd -D -f /e..."   8 seconds ago       Up Less than a second   0.0.0.0:80->80/tcp, 100/tcp   raspap
```
But it couldn't be connected to Web service and still restarted infinitely ..

**Comment by thaJeztah** [comment] 2017-11-30 05:24
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to comment

**Closed by thaJeztah** 2017-11-30 05:24 UTC
Labels: area/builder, kind/question, platform/arm
