### ISSUE TITLE
Cannot communicate with host through gateway IP when userland-proxy: false

### ISSUE THREAD

**Issue by ryan-shaw** [moby/moby#40518] opened 2020-02-13 22:59 UTC
**Description**

When disabling userland-proxy can no longer get to services exposed through the networks gateway address.

**Steps to reproduce the issue:**
1. Create a container on default bridge network that exposes a port
e.g. `docker run -d --name nginx -p 80:80 nginx`
2. Create network
`docker network create --gateway 172.18.0.1 --subnet 172.18.0.1/24  test_net`
3. Create a container on the named network 
e.g. `docker run -it --rm --network=test_net byrnedo/alpine-curl http://172.18.0.1`
this should be succesful
4. Disable userland-proxy and repeat above and the curl will no longer succeed.

I've tried this on multiple machines (AWS, Scaleway, local) and all have the same behaviour.

**Describe the results you received:**
To be able to communicate with host machine through gateway IP when userland proxy is disabled

**Describe the results you expected:**
Could not communicate with host

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 122
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-45-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: ubuntu
 ID: GIIG:5SU7:2GKU:TAEX:SAZJ:LO7C:B2MZ:5PRS:JXKK:MPCX:6MEF:PJZI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by polarathene** [comment] 2023-05-04 05:50
Reproduced, seems to be effectively the same issue as https://github.com/moby/moby/issues/38784 (_which goes more into detail to what's causing it_)

---

While this issue uses the attached network gateway, that doesn't seem to matter and you could query a different docker network gateway like the `docker0` one added into `/etc/hosts` via [`docker run --add-host=host.docker.internal:host-gateway ...`](https://stackoverflow.com/questions/70725881/what-is-the-equivalent-of-add-host-host-docker-internalhost-gateway-in-a-comp).

If the service is on the host, and not another docker network, it'll be reached fine regardless of the gateway address. Otherwise the related issue `iptables` routing rules seem to apply intentional isolation?

---

> The current behaviour were it is only the docker ports that are forbidden makes no sense.

It is due to the rules docker adds to manage it's own NAT I think?

It makes sense in that you can reach all ports on the bridged interface, but not those for docker networks where the ports might be mapped to. In that sense it is preventing you from reaching any of those container networks ports. So reaching the host ports not related to containers is expected, not being able to access containers via published ports is not.

**Comment by akerouanton** [comment] 2023-07-24 09:50
This is indeed a duplicate of #38784, so let me close this one in favor of the other.

**Closed by akerouanton** 2023-07-24 09:50 UTC
Labels: kind/question, area/networking, version/19.03, area/networking/portmapping
