### ISSUE TITLE
Support process health check?

### ISSUE THREAD

**Issue by FX-HAO** [moby/moby#34991] opened 2017-09-27 04:24 UTC
I'm running a single process on a container and I need a way to do a health check.
I though something like `["CMD-SHELL", "ps ax | grep -v grep | grep sidekiq || exit 1"]` could work. Then I attached to the docker container and it worked. But when i put it in docker-compose it didn't.

**Comment by thaJeztah** [comment] 2017-09-27 13:32
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-09-27 13:32 UTC
Labels: area/bundles, kind/question
