### ISSUE TITLE
Executables in tmpfs mounts can't execute

### ISSUE THREAD

**Issue by skycoop** [moby/moby#35890] opened 2017-12-28 17:05 UTC
**Description**
Executable files inside a `tmpfs` mount are not actually executable, despite having execute permissions for all users.

**Steps to reproduce the issue:**
1. Create a container using a `tmpfs` mount
2. Create an executable file inside the mount
3. Attempt to execute it

**Describe the results you received:**
```
docker run --rm -it --mount type=tmpfs,dst=/tmp/test ubuntu:16.04 bash
root@71f347cc91b8:/# echo -e '#!/usr/bin/env bash\necho "Foo!"' > /tmp/test/foo.sh
root@71f347cc91b8:/# chmod +x /tmp/test/foo.sh
root@71f347cc91b8:/# /tmp/test/foo.sh
bash: /tmp/test/foo.sh: Permission denied
root@71f347cc91b8:/# ls -la /tmp/test/
total 8
drwxrwxrwt 2 root root   60 Dec 28 16:52 .
drwxrwxrwt 3 root root 4096 Dec 28 16:52 ..
-rwxr-xr-x 1 root root   32 Dec 28 16:52 foo.sh
```

**Describe the results you expected:**
I expected the script to run, which it does if I swap out the mount for a volume
```
docker run --rm -it --mount type=volume,src=tmpfs-test,dst=/tmp/test ubuntu:16.04 bash
root@0049ea1e5273:/# echo -e '#!/usr/bin/env bash\necho "Foo!"' > /tmp/test/foo.sh
root@0049ea1e5273:/# chmod +x /tmp/test/foo.sh
root@0049ea1e5273:/# /tmp/test/foo.sh
Foo!
root@0049ea1e5273:/# ls -la /tmp/test/
total 12
drwxr-xr-x 2 root root 4096 Dec 28 16:46 .
drwxrwxrwt 3 root root 4096 Dec 28 16:59 ..
-rwxr-xr-x 1 root root   32 Dec 28 16:59 foo.sh
```

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `docker version`:**
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**
```
Containers: 23
 Running: 0
 Paused: 0
 Stopped: 23
Images: 303
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 711
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-42-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.37GiB
Name: sophon.workstations.amp
ID: LATD:Z32F:P3NA:DC4Y:NXPS:KDH7:LQGE:ETIS:OL6B:YIO3:W5XV:AONH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare metal Ubuntu 16.04 install

**Comment by skycoop** [comment] 2017-12-28 17:21
OK. It's because the `tmpfs` was mounted with the `noexec` flag set. If I use `--tmpfs`, I can specify `--tmpfs /tmp/test:exec`. Is there a way to accomplish this with `--mount`?

**Comment by thaJeztah** [comment] 2017-12-29 16:19
Looks like a duplicate of https://github.com/moby/moby/issues/32131; the `exec` / `noexec` option is not yet implemented for `--mount type=tmpfs`.

Is there a specific reason you want to use tmpfs for this? Although tmpfs may _seem_ like a good choice to get better performance, it may not actually be;

- tmpfs size is limited by "physical memory (RAM)" + swap size; if RAM is depleted, files in tmpfs will be swapped out to disk (causing performance to degrade)
- tmpfs can deplete memory
- compared to writing to other filesystems (i.e. write to disk), overall, tmpfs will only gain performance on first _write_ or _read_. Modern filesystems are smart, and cache writes and reads; so in many cases there may be _no_ actual difference in performance, and _if_, that performance difference is usually only on the first access for a file (after which it's kept in cache)

tmpfs is mostly targeted for situations where many fast, random writes (and small files) are needed

Some information around this can be found [here](https://rwmj.wordpress.com/2012/09/12/tmpfs-considered-harmful/) and [here](https://lwn.net/Articles/499410/)


Closing this issue because it's a duplicate of https://github.com/moby/moby/issues/32131, but feel free to comment after I closed

**Closed by thaJeztah** 2017-12-29 16:19 UTC

**Comment by skycoop** [comment] 2017-12-29 17:33
Sorry I didn't see that issue. The use case for us is to have files whose lifespan is tied to that of the container. 

I just created an issue asking for better documentation of the differences between `--tmpfs` and `--mount type=tmpfs` (see https://github.com/docker/docker.github.io/issues/5640). That should hopefully prevent someone else from running into the same issue 🙂

**Comment by thaJeztah** [comment] 2017-12-29 17:37
> The use case for us is to have files whose lifespan is tied to that of the container.

I think you'd have two options for that;

- don't use a volume for those; this is the easiest solution, and works well if those files are not write intensive (i.e., not a database that does a lot of writes and is performance critical)
- use an anonymous volume; docker will create a randomly named volume before the container starts, and (if the container is started with `--rm`) removes it when the container is removed

**Comment by simonvpe** [comment] 2018-01-16 14:57
+1 on this.

We need a tmpfs mount with "exec" but currently it seems impossible to achieve this with docker swarm mode since docker swarm doesn't support the --tmpfs flag, and the --mount flag doesn't support setting the exec flag.

**Comment by thaJeztah** [comment] 2018-01-17 00:07
@simonvpe see the issue I linked to; https://github.com/moby/moby/issues/32131
