### ISSUE TITLE
"docker swarm leave" does not clear node info

### ISSUE THREAD

**Issue by ityangchen** [moby/moby#33217] opened 2017-05-16 07:05 UTC
**Description**

**Steps to reproduce the issue:**
1.create swarm cluster
2.join a worker node 
3.join a manager node 

**Describe the results you received:**
on worker node:

```
-bash-4.2# docker swarm leave
Node left the swarm.
```

on manager node:

```
-bash-4.2# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
aunykbyvgtxmobev7k89y5o6f     node-209            Ready               Active              
hnp5jyhx6dbzm3m2o09h8h9f9     node-208            Ready               Active              
ohf4ps6u5pglrdbl2ckz0klpd     node-207            Ready               Active              
plteylkhzlqnvcw7gepruiozc *   node-206            Ready               Active              Leader
-bash-4.2# 
-bash-4.2# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS

aunykbyvgtxmobev7k89y5o6f     node-209            Down                Active

              
hnp5jyhx6dbzm3m2o09h8h9f9     node-208            Ready               Active              
ohf4ps6u5pglrdbl2ckz0klpd     node-207            Ready               Active              
plteylkhzlqnvcw7gepruiozc *   node-206            Ready               Active              Leader
```

**Describe the results you expected:**

```
-bash-4.2# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
aunykbyvgtxmobev7k89y5o6f     node-209            Ready               Active              
hnp5jyhx6dbzm3m2o09h8h9f9     node-208            Ready               Active              
ohf4ps6u5pglrdbl2ckz0klpd     node-207            Ready               Active              
plteylkhzlqnvcw7gepruiozc *   node-206            Ready               Active              Leader
-bash-4.2# 
-bash-4.2# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS         
hnp5jyhx6dbzm3m2o09h8h9f9     node-208            Ready               Active              
ohf4ps6u5pglrdbl2ckz0klpd     node-207            Ready               Active              
plteylkhzlqnvcw7gepruiozc *   node-206            Ready               Active              Leader
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
-bash-4.2# docker version
Client:
 Version:      17.05.0-ce
 EulerVersion: 17.05.0.1
 API version:  1.29
 Go version:   go1.7.4
 Git commit:   f50dccd
 Built:        Thu May 11 07:51:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 EulerVersion: 17.05.0.1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   f50dccd
 Built:        Thu May 11 07:51:53 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
-bash-4.2# docker version
Client:
 Version:      17.05.0-ce
 EulerVersion: 17.05.0.1
 API version:  1.29
 Go version:   go1.7.4
 Git commit:   f50dccd
 Built:        Thu May 11 07:51:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 EulerVersion: 17.05.0.1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   f50dccd
 Built:        Thu May 11 07:51:53 2017
 OS/Arch:      linux/amd64
 Experimental: false
-bash-4.2# 
-bash-4.2# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-16877249-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 225.2MB
 Data Space Total: 107.4GB
 Data Space Available: 3.041GB
 Metadata Space Used: 864.3kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: plteylkhzlqnvcw7gepruiozc
 Is Manager: true
 ClusterID: u1jh84744098ze9cheo412ssl
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.175.107.206
 Manager Addresses:
  10.175.107.206:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: f23da5862b42e3317c5a42197ce85f50c458c0da (expected: 9048e5e50717ea4497b757314bad98ea3763c145)
runc version: 18c1280cf0812d8b19c0423dc6409e37b2e75684-dirty (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: 5f21c08
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.49.58.45.x86_64
Operating System: AntOS 0.1 (SP1)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.273GiB
Name: node-206
ID: UC7I:S4FG:QYYZ:LTO4:5P6G:VBSH:GCDD:SPNG:JVGJ:KPOC:K7IV:KRRA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 50
 Goroutines: 177
 System Time: 2017-05-16T15:09:15.49049917+08:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-05-16 13:50
This is expected; a node can _leave_ the swarm, but does not _remove_ itself from the list of nodes. Only a manager node can remove a node from the swarm, using `docker node rm` (if you're removing a _manager_ node, it should first be demoted to a worker through `docker node demote`).

Also see the command line reference for `docker swarm leave`; https://docs.docker.com/engine/reference/commandline/swarm_leave/#extended-description

> The node will still appear in the node list, and marked as down. It no longer affects swarm operation, but a long list of down nodes can clutter the node list. To remove an inactive node from the list, use the node rm command.

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-05-16 13:50 UTC
Labels: area/swarm, version/17.05
