### ISSUE TITLE
Removed Container Still Attached to Network

### ISSUE THREAD

**Issue by dsanders11** [moby/moby#33156] opened 2017-05-11 06:30 UTC
**Description**

I've got a removed container tying up an endpoint name in the bridged network, and I can't remove the container from the network since the container no longer exists.

The issue could most likely be resolved by clearing everything out and starting it up again but due to #32613 that would result in data loss so I'm avoiding that. Using a different name for the container allows it to be started but this is not ideal.

**Steps to reproduce the issue:**
1. `docker run --name=foobar ...`

**Describe the results you received:**

Error on container start: `docker: Error response from daemon: endpoint with name foobar already exists in network bridge.`

Inspecting the network bridge (non-relevant containers trimmed): 

```
docker network inspect e798022be800
[
    {
        "Name": "bridge",
        "Id": "e798022be800fc9deebdecc29d0cb895a0cdb56f550da571111d7f82f3d63822",
        "Created": "2017-05-05T22:03:13.333103921Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "Containers": {
            "5ef2b1a30a90a73eee7ab80db3019b1067d844e009f694441c40fb6aec683947": {
                "Name": "foobar",
                "EndpointID": "88a592be8ee9d7c7f16fc5b2b9efe2e8fb458b318b151d6b4373671463254772",
                "MacAddress": "02:42:ac:11:00:05",
                "IPv4Address": "172.17.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

Attempting to disconnect the non-existent container:

```
docker network disconnect e798022be800 5ef2b1a30a90a73eee7ab80db3019b1067d844e009f694441c40fb6aec683947
Error response from daemon: No such container: 5ef2b1a30a90a73eee7ab80db3019b1067d844e009f694441c40fb6aec683947
```

**Describe the results you expected:**

Non-existent containers should not be still connected to a network.

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker was upgraded then the daemon was restarted, allowing the containers to continue running since live restore is enabled.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker2-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 5.161GB
 Data Space Total: 12.23GB
 Data Space Available: 7.074GB
 Metadata Space Used: 2.212MB
 Metadata Space Total: 125.8MB
 Metadata Space Available: 123.6MB
 Thin Pool Minimum Free Space: 611.3MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.795GiB
Name: ip-172-31-22-109.us-west-2.compute.internal
ID: HS2S:5VZ6:KMAR:QCGS:U22B:LM4J:QMZM:BCVH:NH53:6FFK:XTR6:W7LH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by dsanders11** [comment] 2017-05-11 07:53
May be a duplicate of #31643, which is using swarm mode, while my case is not.

**Comment by thaJeztah** [comment] 2017-05-11 08:39
Have you tried the `-f` / `--force` option on `docker network disconnect`? `docker network disconnect <network> <endpoint-id>`, so in your case;

```
docker network disconnect bridge 88a592be8ee9d7c7f16fc5b2b9efe2e8fb458b318b151d6b4373671463254772
```

**Comment by dsanders11** [comment] 2017-05-11 21:43
I had tried force and the error changed to saying endpoint didn't exist instead of container, even though I was still using the container ID. I didn't try using the end point ID instead of the container ID.

Unfortunately I don't have Docker still in this state to try. Shortly later the whole thing took a bath and I had to restart the machine, which knocked the network back into a normal state.

**Comment by thaJeztah** [comment] 2017-05-23 23:52
Actually I was mistaken, I don't think endpoint ID is supported (I thought we did for this case), however using `--force` should allow you to resolve the situation.

Given that a restart resolved it, i'll go ahead and close this issue 👍

**Closed by thaJeztah** 2017-05-23 23:52 UTC
Labels: area/networking, version/17.05

**Comment by optical** [comment] 2018-04-26 22:11
Was the root cause of this issue addressed in a later release? I am running Docker version 17.05.0-ce, build 89658be and have just run into this exact issue.

The workaround was to forcibly disconnect the orphaned container from the bridge network as mentioned. This stung us a little in production, so I am interested in finding a solution that wouldn't require manual intervention.

**Comment by LiranV** [comment] 2018-05-16 13:38
I've encountered the same issue.
Running `docker network disconnect --force bridge <Container ID or Endpoint ID>` didn't work.
But running the same command with the container name (`foobar` in the OP case) instead of the ID worked just fine.

**Comment by romero-vincent** [comment] 2018-07-12 21:37
Ran into the same problem with stale containers.

When simply `docker network disconnect --force` don't work due to stale (long gone) containers. Try to use:

`docker network prune` 

It sweeps thru docker networks that are unused by containers -- stale containers leave unused networks, thus `prune`-ing works

**Comment by Azleal** [comment] 2019-05-30 09:15
the same problem, I docker-compose up and down several times and then found certain contain can't start due to port errors. I dig it up and find that the in the network still existing the containers that are stopped. cause nothing show in `docker ps -a`. 
and any method mentioned above doesn't work. at last I have to `service docker restart` to solve this problem

**Comment by uy-rrodriguez** [comment] 2020-12-03 17:35
This issue is still happening with Docker version 19.03.2, build 6a30dfc
I was running `docker-compose exec` commands in a service and when doing `docker-compose down` it couldn't remove the network.
I used docker "rm" commands to remove all containers and images, then docker "prune" to remove everything dangling.

Still, when doing `docker network inspect` on the problematic network, it shows the following endpoint:
```
        "Containers": {
            "79b1f5b06cf6bdde53c790d3fd5f4a34c78f73dde57dc898cfcd3008af07112a": {
                "Name": "app_1_59bca08935ef",
                "EndpointID": "b3dd3f21f17354bdcbf7098a7d4469c5917c61123d610fcc151fffd511d41b11",
                "MacAddress": "02:42:c0:a8:10:03",
                "IPv4Address": "192.168.16.3/20",
                "IPv6Address": ""
            }
        },
```

Doing `docker container inspect` with the Container ID above, it shows:
```
[]
Error: No such container: 79b1f5b06cf6bdde53c790d3fd5f4a34c78f73dde57dc898cfcd3008af07112a
```

Executing `docker network disconnect --force <network id> <container id>`:
```
Error response from daemon: endpoint 79b1f5b06cf6bdde53c790d3fd5f4a34c78f73dde57dc898cfcd3008af07112a not found
```

The same as above but using the Endpoint ID:
```
Error response from daemon: endpoint b3dd3f21f17354bdcbf7098a7d4469c5917c61123d610fcc151fffd511d41b11 not found
```

Without using `--force` and with the container ID:
```
Error response from daemon: No such container: 79b1f5b06cf6bdde53c790d3fd5f4a34c78f73dde57dc898cfcd3008af07112a
```

After all that, I run `docker network rm <network id>` again:
```
Error response from daemon: error while removing network: network app_default id f4306127ee9527af3e802f6dbc32bdf944ce834547bb61d57cc2f6502e1974ca has active endpoints
```

Is there any other solution than restarting the `docker` service? There are situations where we cannot simply restart the service for many reasons, like when the server is shared by other systems.

**Comment by Avamander** [comment] 2026-05-03 15:39
Fairly sure this still hasn't been actually resolved and actually shouldn't be a closed issue.

**Comment by robmry** [comment] 2026-05-03 16:49
> Fairly sure this still hasn't been actually resolved and actually shouldn't be a closed issue.

Do you have a way to provoke / demonstrate the problem, or any ideas about what might have triggered it? Which version are you using? Do you have daemon logs from when the  problem started?

It might be best to create a new issue to describe the details (and link it to this one).

**Comment by Avamander** [comment] 2026-05-03 18:24
It's just that once in a while tearing a container down results in a stale network entrypoint, after which recreating them fails (because of that entry). I can't pin down the exact moment where a container breaks in such a way. I've never seen it affect a Docker host that isn't busy though, so maybe it's caused by some slowdown or some other system hiccup? This also means that there isn't a long history of verbose logs kept for those hosts because it's not worth it.

In any case, it would be very useful to have a workaround for this. Right now nothing can be done to get rid of the broken/stale endpoint on the network except restarting the daemon. Which is very painful (because again, it seems to affect only very busy hosts).

Currently using 27.5.1, but I've seen it a few times on older versions.
