### ISSUE TITLE
docker image tags not appearing on host when pulled by a service

### ISSUE THREAD

**Issue by nicolaselkhoury** [moby/moby#37533] opened 2018-07-26 10:52 UTC
**Description**

I am running a Docker swarm (Docker v18.03.0-ce) on three ubuntu machines. When I create a Docker service, running the command docker images, does not display the tag of the image downloaded, whereas it is shown when listing the services running. 

Assume I created a service based on the Alpine image, as such:

`docker service create --name test alpine:latest sleep 3600`

listing the images on the host running an instance of this service returns what follows:
`Repository Tag`

`alpine    <none>`

The tag is listed as <none> instead of latest.

However, listing the services, the tag is outputted as it should be:
`docker service ls` returns the following:

`ID                  NAME                  MODE                REPLICAS            IMAGE
<Service ID>        test                  replicated          1/1                 alpine:latest`

Notice how the image has the latest tag, as opposed to <none> when outputting the images of the host machine.

The question is why is this happening? why are the images on the host machine without a tag when pulled by a service?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
18.03.0-ce
```

**Output of `docker info`:**

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: id
 Is Manager: true
 ClusterID: id
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: addr
 Manager Addresses:
  addr1:2377
  addr2:2377
  addr3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1061-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858GiB
Name:
ID: OIZB:MNZT:NMLG:5DOU:TEXH:SONS:6X4J:E6O4:WP7L:ZLH7:6WI6:DKDQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The instances of the swarm are ubuntu 16.04 machines hosted on AWS

**Comment by caub** [comment] 2018-08-24 10:47
experiencing same issue
``
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
mongo                                           <none>              7efb1adc67ca        36 hours ago        368MB
gcr.io/foo/bar                               <none>                 e6fe5114ebdb        2 days ago          274MB
```

when doing `docker ps` or `docker service ls` the tags are visible, it's just `docker images` that's not working

**Comment by LeartS** [comment] 2018-10-17 18:33
Can confirm the bug, excerpt of `docker info`:
```
Server Version: 18.06.1-ce                                                                                                                                                                                                                    
Storage Driver: overlay2                                                                                                                                                                                                                      
 Backing Filesystem: extfs                                                                                                                                                                                                                    
 Supports d_type: true                                                                                                                                                                                                                        
 Native Overlay Diff: true                                                                                                                                                                                                                    
Logging Driver: json-file                                                                                                                                                                                                                     
Cgroup Driver: cgroupfs                                                                                                                                                                                                                       
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
```

On a swarm cluster, I have several stack definitios that use images from a private registry, like so:
```
[...]
services:
  odoo:
    image: docker.repo.localmonks.net/odoo:ipi.prod
[...]
```

`docker service ls` correctly shows the image tag:
```
root@docker-be-prod-manager01:/opt/45-odoo-ipi-prod# docker service ls
ID                  NAME                  MODE                REPLICAS            IMAGE                                       PORTS
g5aixnuvqheh        odoo-ipi-prod_odoo    replicated          1/1                 docker.repo.localmonks.net/odoo:ipi.prod    *:4500->8069/tcp, *:4501->8072/tcp              
```

And so does `docker container ls` on the node running the service:
```
CONTAINER ID        IMAGE                                       COMMAND                 CREATED             STATUS              PORTS                NAMES
edb0c284bfac        docker.repo.localmonks.net/odoo:ipi.prod    "/entrypoint.sh odoo"   16 minutes ago      Up 16 minutes       8069/tcp, 8071/tcp   odoo-ipi-prod_odoo.1.6aus8lhgoqyn3smra0380i8rq
```

But `docker image ls` shows no tag:
```
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
docker.repo.localmonks.net/odoo   <none>              4730cb6e4edf        3 hours ago         892MB
```

**Comment by thaJeztah** [comment] 2018-10-30 12:52
This is a duplicate of https://github.com/moby/moby/issues/28908, and https://github.com/moby/moby/issues/31574 - the discussion on those issues contains quite some information about the reason why, but the TL;DR is that when deploying services, the image is pinned to a _digest_ (immutable identifier for an image); this guarantees that all instances of a service are running exactly the same version. The image is then _pulled_ by digest, so the corresponding "tag" won't be visible (unless an image with a tag that matches that digest happens to be present on the host).

I'm closing this one in favor of the ones I linked to, but feel free to participate in the discussion on those issues though

**Closed by thaJeztah** 2018-10-30 12:52 UTC
Labels: area/swarm
