### ISSUE TITLE
"Max open files" limit of containers do not match with the limit in dockerd systemd unit file

### ISSUE THREAD

**Issue by Cycatz** [moby/moby#44547] opened 2022-11-29 15:09 UTC
### Description

The max open files limit `NOFILE` of dockerd is 1048576, which is defined in dockerd's systemd unit file.
```sh
$ cat /proc/$(pidof dockerd)/limits | grep "Max open files"
Max open files            1048576              1048576              files
```
```
$ systemctl show docker | grep LimitNOFILE
LimitNOFILE=1048576
LimitNOFILESoft=1048576
```

However, inside the container, the value of the limit is a very large number — 1073741816:
```
$ docker run --rm ubuntu bash -c "cat /proc/self/limits" | grep  "Max open files"
Max open files            1073741816           1073741816           files
```

It may cause the program iterate all available fds until the limit is reached; for example, the `xinetd` program sets the number of file descriptors using `setrlimit(2)` at initialization, which causes unnecessary waste of CPU resources and time on closing 1073741816 fds.

```
root@1b3165886528# strace xinetd
execve("/usr/sbin/xinetd", ["xinetd"], 0x7ffd3c2882e0 /* 9 vars */) = 0
brk(NULL)                               = 0x557690d7a000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffee17ce6f0) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb14255c000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
close(12024371)                         = -1 EBADF (Bad file descriptor)
close(12024372)                         = -1 EBADF (Bad file descriptor)
close(12024373)                         = -1 EBADF (Bad file descriptor)
close(12024374)                         = -1 EBADF (Bad file descriptor)
close(12024375)                         = -1 EBADF (Bad file descriptor)
close(12024376)                         = -1 EBADF (Bad file descriptor)
close(12024377)                         = -1 EBADF (Bad file descriptor)
close(12024378)                         = -1 EBADF (Bad file descriptor)
```

The similar issue is also mentioned in #38814.

### Reproduce

1. Show the `NOFILE` limit of dockerd: `cat /proc/$(pidof dockerd)/limits | grep "Max open files"`
2. Show the `NOFILE` limit of the container: `docker run --rm ubuntu bash -c "cat /proc/self/limits" | grep  "Max open files"`
3. (optional) Run or strace `xinetd` program and see whether the program hangs for a long time and the high CPU load

### Expected behavior

The value of "Max open files" limit (`NOFILE`) inside container should be the value defined in the systemd daemon configuration file, which is `1048576`.

### docker version

```bash
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.19.2
 Git commit:        baeda1f82a
 Built:             Thu Oct 27 21:30:31 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.2
  Git commit:       3056208812
  Built:            Thu Oct 27 21:29:34 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f.m
 runc:
  Version:          1.1.4
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., 2.12.2)

Server:
 Containers: 34
  Running: 3
  Paused: 0
  Stopped: 31
 Images: 37
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.0.5-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 19.5GiB
 Name: desktop.staque.xyz
 ID: 22LQ:DKOU:G6N2:YSQN:DVLJ:EDA6:W7BN:I5M4:IXLZ:AGGS:PCGO:7MEU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: cycatz
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

My systemd version: 
```sh
$ systemctl --version
systemd 251 (251.7-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by thaJeztah** [comment] 2022-11-29 15:47
I guess in this case the limit set in dockerd's unit file will affect processes (and containers) that are running as a child-process of dockerd, which would be the case if systemd is started as a child-process of docker (so not through its own systemd unit); admitted that's no longer a common scenario.

And if containerd is running as its own systemd service, processes (and containers) running as child process of containerd (more factually, the shim), will inherit containerd's configuration.

```bash
ps auxf | grep -E '[d]ocker|[c]ontainerd|[n]ginx'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         642  0.0  4.2 1274252 42100 ?       Ssl  10:24   0:16 /usr/bin/containerd
root         698  0.0  7.5 1390336 75148 ?       Ssl  10:24   0:02 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root        2027  0.0  0.9 712200  9400 ?        Sl   15:36   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id fe2d6c6e0af3b239d0a20af248343bc6e7e76b9d79520c27fabc1d45f0c68344 -address /run/containerd/containerd.sock
root        2047  0.0  0.4   6316  4468 ?        Ss   15:36   0:00  \_ nginx: master process nginx -g daemon off;
systemd+    2097  0.0  0.1   6772  1792 ?        S    15:36   0:00      \_ nginx: worker process
```

**Comment by Cycatz** [comment] 2022-11-29 16:22
@thaJeztah   I just confirmed that processes in container are indeed running as child process of `containerd-shim-runc-v2` as yours:
```
root        4290  0.0  0.4 3743764 93760 ?       Ssl  Nov29   0:05 /usr/bin/dockerd -H fd://
root        4778  0.0  0.0 1230148 15192 ?       Sl   Nov29   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 22222 -container-ip 172
root        4784  0.0  0.0 1156672 11172 ?       Sl   Nov29   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 22222 -container-ip 172.18.0
root       13319  0.0  0.0 1156672 15260 ?       Sl   Nov29   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 10004 -container-ip 172
root       13326  0.0  0.0 1230404 13292 ?       Sl   Nov29   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 10004 -container-ip 172.22.0
root       13340  0.0  0.0 1156672 15248 ?       Sl   Nov29   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1234 -container-ip 172.
root       13347  0.0  0.0 1230148 15220 ?       Sl   Nov29   0:00  \_ /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 1234 -container-ip 172.22.0.
root        4800  0.0  0.0 720476 14272 ?        Sl   Nov29   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id da5a956d2e0b251d425438a4e685644005c
root       13362  0.0  0.0 720732 19180 ?        Sl   Nov29   0:02 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 1b3165886528e8ce18bd30213888babfbc2
root       13383 21.3  0.0 8394192 3100 ?        Ss   Nov29  14:23  \_ /usr/sbin/xinetd -dontfork
```

Wow! It turned out that the root cause that setting the limit in the dockerd system unit file didn't affect the processes (or containers) is because dockerd no longer spawn container processes by itself.

However, if the the limit specified in the systemd unit file doesn't affect container processes, who set the limit to this very large number?
```
$ docker run --rm ubuntu bash -c "cat /proc/self/limits" | grep  "Max open files"
Max open files            1073741816           1073741816           files
```

**Comment by Cycatz** [comment] 2022-12-01 17:14
> The kernel (or systemd); see https://github.com/containerd/containerd/pull/7566#issuecomment-1285417325

Thanks! Let me summarize: 
1. Now containers are spawned by containerd, not by dockerd
2. [Containerd systemd unit file](https://github.com/containerd/containerd/blob/ae6c244995a786801e50a1bde0a3b38439acbfc2/containerd.service#L35) specify `LimitNOFILE=infinity
`, making the "Max open files" limit of containers have a very large number 1073741816 maximum available fds.

**Comment by thaJeztah** [comment] 2022-12-01 17:41
Yes, the limit always was intended to be `infinity`, but some versions of systemd didn't accept that special value; the "infinity" limit used to be `1048576` so it was set to that value, but newer kernels (or systemd) raised this to `1073741816`, so the `infinity` value is either `1048576 ` or `1073741816` (depending on your distro).

**Comment by neersighted** [comment] 2023-02-27 16:40
I'm closing this for now as a answered question; whether or not we should set these limits ourselves is discussed in https://github.com/moby/moby/issues/38814.

**Closed by neersighted** 2023-02-27 16:40 UTC
Labels: status/0-triage, kind/bug

**Comment by kwenzh** [comment] 2023-08-11 02:02
> Yes, the limit always was intended to be `infinity`, but some versions of systemd didn't accept that special value; the "infinity" limit used to be `1048576` so it was set to that value, but newer kernels (or systemd) raised this to `1073741816`, so the `infinity` value is either `1048576 ` or `1073741816` (depending on your distro).

the same issue  in kernel 4.18, but in kernel 3.10 is ok

**Comment by rrauenza** [comment] 2024-10-03 20:01
FYI, since it wasn't explicitly mentioned, one workaround (rocky9):

```
$ cat /etc/systemd/system/containerd.service.d/override.conf
[Service]
LimitNOFILE=10240
```

**Comment by krlmlr** [comment] 2024-10-09 21:03
Thanks, Rich, confirmed on rhel9 in a very similar scenario. As a shell sequence:

```sh
sudo mkdir -p /etc/systemd/system/containerd.service.d
echo -e '[Service]\nLimitNOFILE=102400' | sudo tee /etc/systemd/system/containerd.service.d/override.conf
```

**Comment by andrewbelcher** [comment] 2025-01-29 10:55
Just for anyone else who comes across this issue, it can be worked around at a per project level with the following `.ddev/docker-compose.local.yaml`:
```yaml
services:
  db:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
```
17GB and death is now 280MB. Limits may need varying based on the project...
