### ISSUE TITLE
Issue with distribution and /etc/docker not readable

### ISSUE THREAD

**Issue by vieux** [moby/moby#15379] opened 2015-08-06 22:09 UTC
(I opened the issue in docker/docker as @dmp42 told me :p)

I'm currently trying to implement `search` in swarm, and, unlike the engine, swarm can me started as an unprivileged user.

The issue is, I start swarm as my user and when I do a search, the distribution pkg is going to look into `/etc/docker/certs.d/docker.io` to see if there is such a cert.

I don't have such a cert on my machine, but at /etc/docker is `drwx------` I get an error:  `open /etc/docker/certs.d/docker.io: permission denied` and it aborts.

I think the distribution pkg should skip the error as `/etc/docker/certs.d/docker.io` is not mandatory.

**Comment by vieux** [comment] 2015-08-06 22:10
ping @stevvooe @dmcgowan @dmp42 @RichardScothern @aaronlehmann

**Comment by stevvooe** [comment] 2015-08-06 22:36
The distribution pkg does not do cert lookups. This is likely the transport implementation in the docker/pkg/registry package.

Docker really shouldn't doing cert assembly. I'm confused why we don't just use the system cert chain.

**Comment by cpuguy83** [comment] 2015-09-15 16:42
+1, should only ever rely on the system cert chain, not sure why we added the `/etc/docker/certs.d`, also this is frequently trouble for people trying to setup a registry with docker.

**Comment by dmcgowan** [comment] 2015-09-15 16:49
@cpuguy83 I partially agree. I agree we should just rely on the system cert chain and not attempt to assemble per endpoint. However the `/etc/docker/certs.d` directory is also used for client certificates which is a valuable feature and is better as endpoint specific. For this specific issue, when not running as root certificates should be looked for under `~/.docker`. This is already being done for client side operations such as trust content lookups.

**Comment by stevvooe** [comment] 2015-09-17 14:52
@dmcgowan This isn't exactly the source of this particular issue, but I do agree with @cpuguy83. While `/etc/docker/certs.d`does have its uses, it leads to more confusion, as it is very unfamiliar.

Either way, we should check `~/.docker` for these certs.

**Comment by thaJeztah** [comment] 2015-11-02 13:58
is someone working on this?

**Comment by stevvooe** [comment] 2015-11-02 19:20
@thaJeztah Not that I know. The bug here is not actually in distribution. The bug is in docker's integration of the distribution code and was already there for quite some time.

@vieux I would argue that it doesn't make much sense to have `/etc/docker/certs.d/docker.io` not be readable by anyone. What are we protecting by not allowing others to read the client trusted certificates? These aren't a secret and are ready available publicly. I would just suggest making this directory readable by others (just make sure to not add write). 755 for directories and 644 for the files in this directory should be sufficient.

I'm not sure what the way forward here is. It was a really bad design mistake to ever have docker use a separate cert chain. It is the source of constant user issues and confusion.

The problem is that removing this extra certificate chain means we can't just remove code, but we have to update loads of companion documentation circling around this broken concept. Even more complex is that each operating system has a different way of adding and removing client certificates from the local certificate chain. Effectively, a very simple change to undo a bad design mistake will result in a lot of extra work in dealing with the user fallout and documentation problems. This is not glamorous work, nor is there much reward for it.

**Comment by LK4D4** [comment] 2016-09-13 23:59
@thaJeztah should we proceed here?

**Comment by thaJeztah** [comment] 2016-09-14 15:03
This issue is quite old now, @vieux is this still being worked on from the Swarm side, or should we close?

**Comment by stevvooe** [comment] 2016-09-15 01:48
@thaJeztah There are a few fixes that probably need to happen to address this issue (and similar cert management issues):

1. Leverage the system cert pool. Go 1.7 added [`x509.SystemCertPool`](https://golang.org/pkg/crypto/x509/#SystemCertPool). This will get rid of a large number of annoyances.
2. Extend the system cert pool with `/etc/docker/certs.d` and `~/.docker/certs.d`, providing selective extension of docker only certs.
3. Ensure that there is some control over which registries a daemon will trust. When you open up to the system cert pool, you start trusting anything the system cert pool has.
4. Shore up the code that reads the actual directories.

**Comment by cpuguy83** [comment] 2016-09-15 13:46
@stevvooe Wouldn't it already take the system cert pool into account, provided you didn't provide a custom pool?

**Comment by stevvooe** [comment] 2016-09-15 19:49
@cpuguy83 The registry cert pool does not inherit the system cert pool, as far as know. That could have changed. cc @dmcgowan

**Comment by dmcgowan** [comment] 2016-09-16 01:23
This should be fixed for 1.13. Go 1.7 is now used to build and submitted https://github.com/docker/go-connections/pull/21 to get the ball rolling.

**Comment by thaJeztah** [comment] 2016-09-16 13:44
Let me assign you @dmcgowan :smiling_imp:

**Comment by sam-thibault** [comment] 2023-09-14 10:52
This is an old issue and fixed by Go update mentioned above.  Marking done.

**Closed by sam-thibault** 2023-09-14 10:52 UTC
Labels: area/distribution
