### ISSUE TITLE
Format of `--constraint` can cause errors

### ISSUE THREAD

**Issue by pf-curtis-mitchell** [moby/moby#32315] opened 2017-04-03 12:33 UTC
**Description**

When trying to add a `--constraint` to a `docker service create` command, the format of the constraint can cause confusing errors. This appears to be similar to #30914. But, it works in v1.13.x and has issues in v17.03.

**Steps to reproduce the issue:**

Create a service using `docker service create --name hello --constraint 'node.role == manager' dockercloud:hello-world`

**Describe the results you received:**

error message: `Error response from daemon: rpc error: code = 2 desc = constraint expected one operator from ==, !=`

**Describe the results you expected:**

The service should be created successfully with the constraint.

**Additional information you deem important (e.g. issue happens only occasionally):**

If I change the command to `docker service create --name hello --constraint 'node.role==manager' dockercloud:hello-world` (notice the spacing in the constraint), the error message reads `Error response from daemon: rpc error: code = 2 desc = key ''node.role' is invalid`.

However, `docker service create --name hello --constraint node.role==manager dockercloud:hello-world` works. Note: I removed the single quotes and the spaces.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 1
 Paused: 0
 Stopped: 9
Images: 169
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 367
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 23jjrpvwiburopieo22qla812
 Is Manager: true
 ClusterID: 69gi2ali8tuxwu5ej7ojmv1gs
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837 GiB
Name: moby
ID: SINV:PZQK:6DYM:4GNX:LGHJ:ON5C:SDTN:YO2G:36QQ:VLYX:BT2H:EFRP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Windows

**Comment by thaJeztah** [comment] 2017-04-03 12:47
I am not able to reproduce this on docker 17.03.1-ce on Linux, or docker 17.04.0-rc2 on Docker for Mac. Perhaps this is because the Windows shell does not strip the single quotes (like is done on Linux). I tried both

```
docker service create --name hello --constraint 'node.role == manager' nginx:alpine
```

and

```
docker service create --name hello --constraint 'node.role==manager' nginx:alpine
```

and both started the service succesfully. "inspecting" the service gave me;

```
docker service inspect --format '{{.Spec.TaskTemplate.Placement}}' hello
{[node.role == manager] []}
```

second call;

```
docker service inspect --format '{{.Spec.TaskTemplate.Placement}}' hello
{[node.role==manager] []}
```

What shell are you using to run those commands? PowerShell, CMD.exe?

ping @johnstep PTAL - anything we can/should do about this? Is this caused by the shell?

**Comment by pf-curtis-mitchell** [comment] 2017-04-03 12:50
CMD.exe - wrapped by [Cmder](http://cmder.net)

**Comment by pf-curtis-mitchell** [comment] 2017-04-03 12:57
It does appear to be shell-related @thaJeztah. The commands work from the bash shells provided by Cmder.

**Comment by thaJeztah** [comment] 2017-04-03 13:11
Right, so what I _think_ happens, is that `Bash` strips quotes, but `CMD.exe` doesn't, therefor the literal `'` quotes end up in the value for `--constraint`.

I'm not running a Windows machine here, so don't have a way to test what the "proper" way is for providing quotes (although they're not needed in this case; it will be interesting to know still)

**Comment by thaJeztah** [comment] 2023-09-17 19:03
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 19:03 UTC
Labels: platform/windows, platform/desktop, area/swarm, version/17.03
