### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference (`daemon.(*Daemon).ContainerExecResize`)

### ISSUE THREAD

**Issue by RtypeStudios** [moby/moby#48128] opened 2024-07-04 01:38 UTC
### Description

I'm currently running rootless-docker on:

Hypervisor:

`pve-manager/8.2.4/faa83925c9641325`

OS:

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

Docker: 

`Using Docker version 24.0.1, build 6802122`

I have IPV6 disabled at the kernel level using this in grub: "ipv6.disable=1" (I'm just testing now with enabling IPV6 to see if the issue still occurs)

Randomly (every couple days) , I receive this error: 

```
Jul 02 10:16:17 serenity dockerd-rootless.sh[892]: time="2024-07-02T10:16:17.181550578+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" err>
Jul 02 10:16:17 serenity dockerd-rootless.sh[892]: time="2024-07-02T10:16:17.181616771+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error=>
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: time="2024-07-02T11:51:42.195210752+08:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: time="2024-07-02T11:51:42.197037455+08:00" level=error msg="Error running exec 5a19c6769988f0fe9170e96aec3869c18fa7dfe63a9bb19e81f0470b475f3185 in container: >
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: time="2024-07-02T11:51:42.197621271+08:00" level=error msg="failed to close container stdin" container=3f85c87aef2714994a78fef07233bb6e64ad69bbc5c8438de873ef9>
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: 2024/07/02 11:51:42 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: goroutine 94592 [running]:
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: net/http.(*conn).serve.func1()
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /usr/local/go/src/net/http/server.go:1854 +0xbf
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: panic({0x45eaa0, 0x38208f0})
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /usr/local/go/src/runtime/panic.go:890 +0x263
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: github.com/docker/docker/daemon.(*Daemon).ContainerExecResize(0x437a80?, {0xc000dfc551?, 0x7e2031?}, 0x44, 0xd2)
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /go/src/github.com/docker/docker/daemon/resize.go:51 +0x159
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: github.com/docker/docker/api/server/router/container.(*containerRouter).postContainerExecResize(0xc001d9b480, {0x0?, 0xc00073d548?}, {0x1da1aa7?, 0x10?}, 0xc0>
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /go/src/github.com/docker/docker/api/server/router/container/exec.go:175 +0x14e
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1({0xb8dcb8, 0xc0014f41b0}, {0xb8c6e0?, 0xc001c2f420?}, 0x36c900?, 0xc00>
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /go/src/github.com/docker/docker/api/server/middleware/experimental.go:26 +0x15b
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1({0xb8dcb8, 0xc0014f4180}, {0xb8c6e0, 0xc001c2f420}, 0x0?, 0xc00073d7a0?)
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x4d7
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1({0xb8dcb8, 0xc0014f4180}, {0xb8c6e0?, 0xc001c2f420?}, 0xc002572b00, 0xc001a6b610?)
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x649
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1({0xb8c6e0, 0xc001c2f420}, 0xc002572a00)
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /go/src/github.com/docker/docker/api/server/server.go:53 +0x1ce
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: net/http.HandlerFunc.ServeHTTP(0xc002572900?, {0xb8c6e0?, 0xc001c2f420?}, 0xc00073d9e8?)
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /usr/local/go/src/net/http/server.go:2122 +0x2f
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0007975c0, {0xb8c6e0, 0xc001c2f420}, 0xc002572800)
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: net/http.serverHandler.ServeHTTP({0xc001e6e660?}, {0xb8c6e0, 0xc001c2f420}, 0xc002572800)
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /usr/local/go/src/net/http/server.go:2936 +0x316
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: net/http.(*conn).serve(0xc00245d5f0, {0xb8dcb8, 0xc001bda3c0})
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /usr/local/go/src/net/http/server.go:1995 +0x612
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: created by net/http.(*Server).Serve
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]:         /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

This then leads to all containers being inaccessible from an outside the machine via HTTP. 

As a background: I'm using Traefik as a reverse proxy to several differ containers.

The only way to restore functionality is to restart the whole machine

Not sure if this is related, but after a while (3-4 hours) all DNS requests start to fail:

```
Jul 02 20:09:41 serenity dockerd-rootless.sh[892]: time="2024-07-02T20:09:41.414248514+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error>
Jul 02 20:09:41 serenity dockerd-rootless.sh[892]: time="2024-07-02T20:09:41.414286266+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" er>
Jul 02 20:15:06 serenity dockerd-rootless.sh[892]: time="2024-07-02T20:15:06.309479346+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" erro>
Jul 02 22:42:10 serenity dockerd-rootless.sh[892]: time="2024-07-02T22:42:10.915102039+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error=">
Jul 02 22:42:10 serenity dockerd-rootless.sh[892]: time="2024-07-02T22:42:10.915155831+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>l.\tIN\t AAAA" erro>
Jul 02 22:42:13 serenity dockerd-rootless.sh[892]: time="2024-07-02T22:42:13.417797027+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" erro>
Jul 02 22:42:13 serenity dockerd-rootless.sh[892]: time="2024-07-02T22:42:13.417851916+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error=">
Jul 02 22:42:14 serenity dockerd-rootless.sh[892]: time="2024-07-02T22:42:14.915746426+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error=">
Jul 02 22:42:14 serenity dockerd-rootless.sh[892]: time="2024-07-02T22:42:14.915774498+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" erro>
Jul 02 23:09:54 serenity dockerd-rootless.sh[892]: time="2024-07-02T23:09:54.843820496+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read udp>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.431956718+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" error="read ud>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.431994923+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read udp 1>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.432006568+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" error="r>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.432030874+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" error="r>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.432037285+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.432041756+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.432482339+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" error="read udp 19>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.432485894+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read udp 192.1>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.433903762+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read udp 192>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.433949397+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" error="read udp >
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.433974851+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="re>
Jul 03 02:00:41 serenity dockerd-rootless.sh[892]: time="2024-07-03T02:00:41.433934619+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" error=>
Jul 03 05:09:54 serenity dockerd-rootless.sh[892]: time="2024-07-03T05:09:54.337777862+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read udp>
Jul 03 10:32:17 serenity dockerd-rootless.sh[892]: time="2024-07-03T10:32:17.762844565+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t A" error="read udp 1>
Jul 03 10:32:17 serenity dockerd-rootless.sh[892]: time="2024-07-03T10:32:17.762891027+08:00" level=error msg="[resolver] failed to query DNS server: 10.0.2.3:53, query: ;<REDACTED>.\tIN\t AAAA" error="read ud
````

This is a list of all of the times the error has occurred:
```
Jun 14 14:07:51 serenity dockerd-rootless.sh[563172]: goroutine 6336494 [running]:
Jun 28 03:30:30 serenity dockerd-rootless.sh[950]: goroutine 6564761 [running]:
Jun 28 15:31:17 serenity dockerd-rootless.sh[2415150]: goroutine 145875 [running]:
Jun 28 15:44:09 serenity dockerd-rootless.sh[2571445]: goroutine 2278 [running]:
Jun 28 15:50:27 serenity dockerd-rootless.sh[2586040]: goroutine 1455 [running]:
Jun 28 16:41:24 serenity dockerd-rootless.sh[2594442]: goroutine 4921 [running]:
Jun 28 16:47:21 serenity dockerd-rootless.sh[2612830]: goroutine 1113 [running]:
Jun 28 16:52:42 serenity dockerd-rootless.sh[2617945]: goroutine 1239 [running]:
Jun 28 17:05:24 serenity dockerd-rootless.sh[2632941]: goroutine 1205 [running]:
Jun 28 17:15:04 serenity dockerd-rootless.sh[2644005]: goroutine 1172 [running]:
Aug 05 13:59:40 serenity dockerd-rootless.sh[1012]: goroutine 5906097 [running]:
Aug 07 08:16:25 serenity dockerd-rootless.sh[1397588]: goroutine 519011 [running]:
Apr 28 12:22:15 serenity dockerd-rootless.sh[966]: goroutine 1008363 [running]:
Jun 18 12:52:15 serenity dockerd-rootless.sh[885]: goroutine 650175 [running]:
Jun 18 14:35:35 serenity dockerd-rootless.sh[886]: goroutine 11657 [running]:
Jun 26 12:29:39 serenity dockerd-rootless.sh[984]: goroutine 698711 [running]:
Jun 26 12:29:43 serenity dockerd-rootless.sh[984]: goroutine 698736 [running]:
Jun 26 13:16:14 serenity dockerd-rootless.sh[984]: goroutine 738468 [running]:
Jun 26 14:21:53 serenity dockerd-rootless.sh[984]: goroutine 758738 [running]:
Jun 26 16:05:21 serenity dockerd-rootless.sh[984]: goroutine 831477 [running]:
Jun 26 21:16:17 serenity dockerd-rootless.sh[984]: goroutine 1034079 [running]:
Jun 26 21:40:55 serenity dockerd-rootless.sh[984]: goroutine 1054103 [running]:
Jun 27 19:24:32 serenity dockerd-rootless.sh[984]: goroutine 453947 [running]:
Jun 27 19:25:02 serenity dockerd-rootless.sh[984]: goroutine 454350 [running]:
Jun 27 19:25:22 serenity dockerd-rootless.sh[984]: goroutine 454588 [running]:
Jul 02 11:51:42 serenity dockerd-rootless.sh[892]: goroutine 94592 [running]:
```

### Reproduce

No idea what is causing this, happens randomly from what I can tell.

### Expected behavior

No exception thrown and no need to restart system.

### docker version

```bash
Client:
 Version:           24.0.1
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        6802122
 Built:             Fri May 19 18:02:46 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.1
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       463850e
  Built:            Fri May 19 18:05:49 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          1.1.0
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /tmp/rootlesskit1557563545
 slirp4netns:
  Version:          1.0.1
  GitCommit:        6a7b16babc95b6a3056b33fb45b74a6f62262dd4
```

### docker info

```bash
Client:
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 23
  Running: 23
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 24.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 5.15.0-113-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 9.7GiB
 Name: serenity
 ID: fb3e0bcf-4b4a-4eb2-ad16-dde19190a036
 Docker Root Dir: /home/su/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by vvoland** [comment] 2024-07-04 09:18
Looks like it has already been fixed in https://github.com/moby/moby/pull/45641
And backported to 24.0.3: https://github.com/moby/moby/pull/45643

Can you reproduce this issue on the latest version?

**Comment by RtypeStudios** [comment] 2024-07-04 12:11
Thank you for the quick reply and your support, I've applied the update. If you don't hear back in a few days the issue is fixed and you can close this.

**Closed** 2024-07-08 16:28 UTC
Labels: status/0-triage, status/more-info-needed, kind/bug, version/24.0
