### ISSUE TITLE
unable to add second manager node within a local network

### ISSUE THREAD

**Issue by rajrawoor** [moby/moby#38350] opened 2018-12-11 15:33 UTC
I am trying to set up a docker swarm in my local network. I am able to do the docker swarm init on the ubnutu server. However, I am unable to add my MAC as a second manager node . 
I can add the MAC a worked node but cannot join the swarm as  a manager.  The second node needs to be a manager because I am trying to set a hyperledger fabric on multi hosts. 

I am using docker 1.18 on both machines . 
Please help

**Comment by thaJeztah** [comment] 2018-12-17 13:01
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-12-17 13:01 UTC
Labels: area/swarm, kind/question
