### ISSUE TITLE
Docker run works behind proxy, and Docker build does not

### ISSUE THREAD

**Issue by julianonunes** [moby/moby#24697] opened 2016-07-15 18:51 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 11
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.459 GiB
Name: moby
ID: 6NAS:3AQW:EXQJ:5S6Y:OHL7:6V2Y:IKMK:ZDI6:7BSA:QO7E:3L7S:EEEG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: 10.0.75.1:7777
Https Proxy: 10.0.75.1:7777
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 Pro - Hyper-V
Dell Latitude 3540

**Steps to reproduce the issue:**
1. docker run -it ruby bash
2. Configure http_proxy and https_proxy env variables
3. execute apt-get update (it should run fine)

part that don't work
4. create a Dockerfile with this content

```
FROM ruby:latest
RUN apt-get update -qq  && apt-get install -y build-essential libmysqlclient-dev nodejs

```
1. docker build .

**Describe the results you received:**

```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ruby:latest
 ---> e4b689e9dc8b
Step 2 : MAINTAINER Juliano Nunes
 ---> Using cache
 ---> 28ba78d36e99
Step 3 : RUN apt-get update -qq  && apt-get install -y build-essential libmysqlclient-dev nodejs
 ---> Running in 9d1f43f218e9
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.deb
ian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package build-essential
E: Unable to locate package nodejs
The command '/bin/sh -c apt-get update -qq  && apt-get install -y build-essential libmysqlclient-dev nodejs' returned a
non-zero code: 100
```

**Describe the results you expected:**

It should run apt-get update/install and build the image.

**Additional information you deem important (e.g. issue happens only occasionally):**
- I have set in my Windows host the environment variables HTTP_PROXY and HTTPS_PROXY to make tools like GIT work behind a proxy.
- My company uses a proxy with NTLM authentication, then I use Fiddler as a tunnel (Internet Options is set to use 127.0.0.1:7777 as the proxy)

**Comment by cpuguy83** [comment] 2016-07-15 19:25
@julianonunes You need to set `docker build --build-arg HTTP_PROXY=foo`

**Comment by julianonunes** [comment] 2016-07-15 19:30
I've tried `docker build --build-arg HTTP_PROXY=http://127.0.0.1:7777` and `docker build --build-arg HTTP_PROXY=http://10.0.75.1:7777`.

**Comment by thaJeztah** [comment] 2016-07-15 21:21
would this require configuring the proxy in the Docker for Windows preferences? https://docs.docker.com/docker-for-windows/#/proxies

**Comment by julianonunes** [comment] 2016-07-15 22:46
It was set on Docker for Windows preferences too. Actually I tried with and without it.

**Comment by thaJeztah** [comment] 2016-07-15 22:50
Alright, was worth a try :smile:

**Comment by mhodas** [comment] 2016-07-16 16:25
Would you please try, if you did not already, `docker build --build-arg http_proxy="http://10.0.75.1:7777"`?

**Comment by julianonunes** [comment] 2016-07-16 16:32
You mean with quotes? This problem happens only when I'm at work, so I'll be able to try just monday.

**Comment by mhodas** [comment] 2016-07-16 16:45
Quotes are probably unnecessary, they are just precaution. Variable names (http_/https_proxy) should be in the lower case and are case-sensitive. `docker build --build-arg "..."` works against my company's proxy (squid) for building at least debian based images. As each docker build step is done by making-committing-destroying intermediate container it cannot inherit any variables from system (if it did, it would make builds non-portable).

**Comment by dgageot** [comment] 2016-07-27 13:56
@julianonunes Thanks for reporting the issue. When you configure the HTTP/HTTPS proxies in Docker for Desktop GUI, multiple things happen:

+ The docker daemon is configured with these proxies so that it can pull images
+ Every `docker run` command automagically gets `HTTP_PROXY`, `http_proxy`, `HTTPS_PROXY` and `https_proxy` added to the environnement variables.
+ It should have been the same for `docker build` but **it's been forgotten**. That's the bug you are seeing.

By the way, because of the magic env rewriting, you don't need to set those env variables on you windows host.

ping @dave-tucker Can you confirm what I'm saying?

**Comment by julianonunes** [comment] 2016-07-27 14:04
Thanks for the feedback @dgageot.

**Comment by dave-tucker** [comment] 2016-08-04 22:32
@dgageot yes this sounds about right to me. I'll see what it will take to add support for this to build too

**Comment by justincormack** [comment] 2016-08-15 09:59
@dave-tucker see https://github.com/docker/docker/issues/4962

**Comment by dave-tucker** [comment] 2016-08-15 10:46
@julianonunes did you try @mhodas's suggestion of exporting `--build-args`? I'd use both the upper and lowercase forms as some applications look for one and not the other - `HTTP_PROXY` and `http_proxy`

**Comment by julianonunes** [comment] 2016-08-15 11:18
@dave-tucker, after @dgageot's comment I didn't check it again, but I'll try once more (though I think I was using both the upper and lowercase forms).

**Comment by wefine** [comment] 2016-09-20 03:26
Hi, @dave-tucker, @julianonunes , I have the same problem with 1.12.1 and try with google, but cannot work,  do you have any solution? Tks.

`Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
`

**Comment by chandan5** [comment] 2016-10-12 08:32
I had the same problem as mentioned by @julianonunes . I am using Docker for Mac.
It got solved by using `docker build --build-arg HTTP_PROXY=foo`
Thanks! @cpuguy83 😃 
It would be great if someone can make a patch for build to use same proxy as run. 😄

**Comment by mpekalski** [comment] 2016-10-12 09:01
I have the same problem and setting env variables globally or within the docker image did not help.

```

Reading package lists...
W: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/jessie/InRelease

W: Failed to fetch http://cdn-fastly.deb.debian.org/debian-security/dists/jessie/updates/InRelease

W: Failed to fetch http://repos.mesosphere.io/debian/dists/wheezy/InRelease

W: Failed to fetch http://repos.mesosphere.io/debian/dists/wheezy/Release.gpg  Unable to connect to my_proxy:

W: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/jessie/Release.gpg  Unable to connect to my_proxy:

W: Failed to fetch http://cdn-fastly.deb.debian.org/debian-security/dists/jessie/updates/Release.gpg  Unable to connect to my_proxy:

W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by mpekalski** [comment] 2016-10-12 14:32
What helped in my case was setting up `HTTP_PROXY, http_proxy, HTTPS_PROXY, https_proxy`  in docker file (I build my image form a file not repository) and setting up
```
[Service]
Environment="HTTP_PROXY=...."
Environment="http_prosy=...."
Environment="HTTPS_PROXY=...."
Environment="https_proxy=...."
```
in 

`/etc/systemd/system/docker.service.d/http-proxy.conf`

and then running 
```
sudo systemctl daemon-reload
sudo service docker restart
```

I do not know if that is of a matter here, but I used proxy server IP addresses in docker file and domain names in docker file.

**Comment by bnegrao** [comment] 2016-10-26 14:37
To solve the problem with curl in docker build, I added the following inside the Dockerfile:
```
ENV http_proxy=http://infoprx2:8080
ENV https_proxy=http://infoprx2:8080
RUN apt-get update && apt-get install -y curl vim
```
Note that the ENV statement is BEFORE the RUN statement.

and in order to make the docker daemon able to access the internet  (I use kitematic with boot2docker), I added the following into /var/lib/boot2docker/profile :
```
export HTTP_PROXY=http://infoprx2:8080
export HTTPS_PROXY=http://infoprx2:8080
```

**Comment by LTheobald** [comment] 2016-11-14 15:01
I'm also having the same issues with `docker build` on Ubuntu. This is a new PC behind a corporate firewall so at first something like `docker pull hello-world` didn't work. The solution to this was creating a drop in file at `/etc/systemd/system/docker.service.d/http-proxy.conf` which contained: 
```
[Service]
Environment="HTTP_PROXY=http://my.proxy.address"
```
And with this I can download images. But when I try to build my own, I get issues. For example, I'm using a simple Dockerfile:
```
FROM ubuntu
RUN apt-get update
```
And that will fail because it can't talk to the update sites:

**docker version**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**docker info**
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 8
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.12 GiB
Name: devleet
ID: P7YV:PZFR:FMPN:3I4I:LNB3:BJFH:KG4S:YEWY:DHZE:CWLO:ZNM5:VWKI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://my.proxy.address
Https Proxy: https://my.proxy.address
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by jgumbley** [comment] 2017-01-06 12:34
Would be interested in a fix to this. Using Docker for Windows, setting corporate proxy settings via the UI provided, a command of the form:

` docker run -it alpine env`

Validated the HTTP_PROXY etc. is being set within the container.

However, using docker compose, the value is not set.

(I understand this may be because docker-compose is calling docker-build, rather than docker run)

Surely this is a simple fix and nobbles a fairly useful feature of docker for windows (the proxy stuff)? Any ideas when we'll see it? Using the beta channel at present.

**Comment by softwarevamp** [comment] 2017-01-12 03:32
ENV http_proxy=$HTTP_PROXY
    ENV https_proxy=$HTTPS_PROXY

rocks!

**Comment by softwarevamp** [comment] 2017-01-12 03:37
+1

**Comment by cosmocracy** [comment] 2017-01-27 19:07
+1 ... major hindrance for those of us trying to advocate use of Docker within corporate boundaries... 

(Thanks, @bnegrao, I've had the best success so far by adding ```ENV http_proxy ...``` entries directly to my Dockerfile.  Not a good practice but it works.)

**Comment by cpuguy83** [comment] 2017-01-27 19:19
Why are we adding `ENV http_proxy`?
What is the actual problem here because I'm seeing multiple cases, but all seem like they would be fixed by `--build-arg http_proxy=foo`

**Comment by ashahba** [comment] 2017-01-28 07:41
I'm on Debian Jessie and facing the same issue, while the same docker proxy setup works on CentOS 7.2.

**Comment by antonin42** [comment] 2017-02-06 17:08
+1

**Comment by Bpatewar** [comment] 2017-02-14 01:20
+1 
I have tried these instruction https://docs.docker.com/engine/admin/systemd/#/http-proxy but it is of no use. I have also tried setting proxy inside docker file which also not working for. Can any body suggest a better alternative.

**Comment by thaJeztah** [comment] 2017-02-14 02:37
@Bpatewar have you tried setting the `HTTP_PROXY` variable during build using `--build-arg` ?

**Comment by Bpatewar** [comment] 2017-02-14 19:16
I colud solve it by setting http_proxy by using ip address of proxy server and not the url.  My friend told reason for this is most of the images are by default set to use googles DNS server to resolve the url address. and thats why using url address for http_proxy fails.

**Comment by thaJeztah** [comment] 2017-02-14 21:37
That would make sense, yes, as containers have their own DNS configuration (I _think_ build-time containers would also respect the `--dns` flag that's set on the daemon)

**Comment by arroyo** [comment] 2017-02-25 03:35
had a very similar issue, adding the proxy settings to /etc/systemd/system/docker.service.d/http-proxy.conf worked

thanks @mpekalski !

**Comment by aelmanaa** [comment] 2017-03-31 01:55
For docker-compose up , you can set the http_proxy in docker-compose.yml ; Example:

version: '2'
services:
  parse-server:
    build:
      context: ./parse-server/
      args:
          - http_proxy
    ports:

**Comment by ashahba** [comment] 2017-03-31 02:08
Ok, it seems like setting up "DOCKER_OPTS" in "/etc/default/docker" solved my issue:

`DOCKER_OPTS="--dns <MY_CORPORATTE_DNS> --dns 8.8.8.8 --dns 8.8.4.4"`

and restart the docker service.
I can build on both Debian Jessie and Ubuntu 14.04 successfully.

Here are my docker versions:
```
ashahba@ashahba2:~$ sudo docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by ashahba** [comment] 2017-03-31 02:10
and of course since I have proxies setup here is how I build my image:

**Comment by maicoqb** [comment] 2017-04-06 19:52
Hi guys, I'm using a workaround to avoid this problem.
I edited my `~/.bash_profile` and added these lines to create an alias to `docker build`:
```
alias docker_build="docker build \
--build-arg http_proxy=$http_proxy \
--build-arg https_proxy=$https_proxy \
--build-arg no_proxy=$no_proxy \
--build-arg HTTP_PROXY=$http_proxy \
--build-arg HTTPS_PROXY=$https_proxy \
--build-arg NO_PROXY=$no_proxy "
```
Then now I use `build_docker --other-options .` to build my images.

I hope this helps somebody. :smile:

**Comment by meralaz** [comment] 2017-04-14 19:12
Hi, I don't know the cause but just being outside the office network makes it work. Incase it is an option for anyone to run it being outside your office network.

**Comment by maicoqb** [comment] 2017-04-17 14:33
@meralaz the problem is not only the office network, the problem is to build behind proxys. Some users need to use his networks behind proxys for many reasons, then this bug needs to be fixed to allow users use this without this ugly kludges.

**Comment by fschuh** [comment] 2017-04-27 10:00
Are there any plans to fix this? This issue has been reported almost a year ago and it's still present.
I'm having a hard time convincing people to use Docker in my company because of the hassles with corporate proxies.
We do build images behind proxies as well.
Please extend your HTTP_PROXY automagic to docker build.

**Comment by fschuh** [comment] 2017-04-27 10:49
Are there any plans to fix this? This issue has been reported almost a year ago and it's still present.
I'm having a hard time convincing people to use Docker in my company because of the hassles with corporate proxies.
We do build images behind proxies as well.
Please extend your HTTP_PROXY automagic to docker build.

**Comment by cpuguy83** [comment] 2017-04-27 14:47
The only thing docker does wrt HTTP_PROXY make sure the external communications it does goes through the proxy. In the container you'd still need to set proxy vars.
The builder has special args for handling `HTTP_PROXY` that's been passed through to `--build-arg`.

Not sure what else to do here.

**Comment by maicoqb** [comment] 2017-04-27 17:10
I've been using docker behind proxy for at least 1 month.
And to avoid that problem when executing containers, I needed to create a shell script to encapsulate some configurations, including this proxy configuration, in every container run.

My scripts seems like this:
> /usr/local/bin/composer
```shell
#!/bin/sh
docker run \
--tty \
--interactive \
--rm \
--user $(id -u):$(id -g) \
--volume /etc/passwd:/etc/passwd:ro \
--volume /etc/group:/etc/group:ro \
--volume ~/.ssh:/root/.ssh \
--volume ~/.composer:/composer \
--volume $(pwd):/app \
-w /app \
-e HTTP_PROXY=$http_proxy \
-e HTTPS_PROXY=$https_proxy \
composer "$@"
```

I know that this is not the solution to that problem, and I really think that this is not a problem but a functionality to avoid mistaken configurations. But this is a workaround that works for me.

I hope this can help you.

**Comment by bpattewar** [comment] 2017-04-27 17:30
The issue is that even we give proxy by HTTP_PROXY , docker container try
to resolves it using DNS entries which are set inside docker container.
Because of DNS entries in container are
values of public domain server and not from the corporate DNS server
entries, it fails to resolve it.  Is there a way that you allow to
configure DNS entry along with http_proxy value

**Comment by cpuguy83** [comment] 2017-04-28 00:42
For me DNS entries are set based on the host's `/etc/resolv.conf` just like for `docker run`.
Is it not doing that for you?

**Comment by bpattewar** [comment] 2017-04-28 00:46
For me it fail to resolve www.abc-proxy.com , so I have put ipaddress
instead of URL so it is working.

**Comment by LTheobald** [comment] 2017-04-28 10:36
You should be able to tell Docker about your DNS. For example, I have a systemd drop in that contains:

    [Service]
    Environment="http_proxy=http://my-proxy.com:8080/" "https_proxy=http://my-proxy.com:8080/" "no_proxy=localhost"
    ExecStart=
    ExecStart=/usr/bin/dockerd -H fd:// --dns 10.121.0.9

Then when in an image, it uses the appropriate DNS.

**Comment by sudharkrish** [comment] 2017-08-09 00:36
Thanks to user by the name bpattewar.

His way of resolution worked for me(cut-paste below)

I colud solve it by setting http_proxy by using ip  address of proxy server and not the url.  My friend told reason for this  is most of the images are by default set to use googles DNS server to  resolve the url address. and thats why using url address for http_proxy  fails.
--

**Comment by neethuabu** [comment] 2017-10-19 18:09
I am using windows7 and docker toolbox. My daemon is running fine. But my build of base image is failing saying docker daemon is not running. I suspect this is proxy. I have tried using --build-args it did not work
For daemon I had to setup proxy separately and the same looks like is not being used by build. Did anyone solve this problem on windows?

**Comment by rfboykin** [comment] 2017-12-05 16:39
I'm also experiencing this issue- setting the http_proxy build-arg to the ip address as suggested above does not fix the issue for me. 

I have an added complication of having a proxy that requires authentication. I've tried qualifying the hostname and ip address of the proxy with the credentials (i.e `<username>:<password>@<proxy_address>:<proxy_port>`

I'm using windows 10 and the ubuntu shell. I'm able to pull docker images successfully, but cannot build for the reasons described above (specifically, fetches to the alpine download page fail) . Any advice or support would be greatly appreciated!!

**Comment by thaJeztah** [comment] 2017-12-06 22:27
@rfboykin if you're running Docker for Windows; have you tried the configuration in the settings panel as well? https://docs.docker.com/docker-for-windows/#proxies

**Comment by arafique** [comment] 2018-01-16 22:16
@thaJeztah I have set up my proxies as per the https://docs.docker.com/docker-for-windows/#proxies instruction but these properties are not propagating to my docker container. I am facing same problem as mentioned by @rfboykin 

Please see https://stackoverflow.com/questions/48272933/docker-at-windows-10-proxy-propagation-to-containers-not-working

**Comment by thaJeztah** [comment] 2018-01-17 00:30
@arafique can you open an issue for that in the Docker for Windows issue tracker? The code responsible for automatically setting those environment variables is not maintained in this repository, and specific to Docker for Mac / Docker for Windows; the issue tracker is: https://github.com/docker/for-win/issues

**Comment by arafique** [comment] 2018-01-19 04:38
@thaJeztah Thanks

**Comment by javabrett** [comment] 2018-01-29 00:18
I haven't seen this logged in the other project yet, but it looks OK to me on `Version 17.12.0-ce-mac49 (21995)`.

(docker command-line version for above Mac version):

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

Given this `Dockerfile`:

```
FROM alpine
RUN env | grep -i proxy
```
Running:

```
docker build --no-cache \
  --build-arg http_proxy=http://proxy \
  --build-arg https_proxy=https://proxy \
  --build-arg no_proxy=no-proxy \
  --build-arg HTTP_PROXY=HTTP://PROXY \
  --build-arg HTTPS_PROXY=HTTPS://PROXY \
  --build-arg NO_PROXY=NO-PROXY \
  --build-arg my-proxy=my-proxy \
  .
```
Produces output:
```
 ---> Running in 9122fffc2c81
HTTPS_PROXY=HTTPS://PROXY
no_proxy=no-proxy
NO_PROXY=NO-PROXY
https_proxy=https://proxy
http_proxy=http://proxy
HTTP_PROXY=HTTP://PROXY
```
Is that sufficient, or is something-else being looked-for here?

**Comment by phlechev** [comment] 2018-02-06 14:25
@rfboykin @arafique You can workaround that by installing locally some authentication proxy like cntlm. You configure it with your real proxy and credentials and then you change docker http_proxy to point to the cntlm proxy.

**Comment by thaJeztah** [comment] 2018-02-13 17:04
Docker 17.07 and up also allows you to configure default proxies for containers in the CLI configuration file (`~/.docker/config.json`) see https://github.com/docker/cli/pull/93 - those proxies are automatically used as `--env` when running a container, and `--build-arg` during build.

**Comment by nevmerzhitsky** [comment] 2018-02-13 17:31
I faced up with a strange issue for `https://` proxy/URLs. On Host OS http and https proxies work fine with google.com, but in `docker build` only http proxy/URL works. My proxy is the different server in the network.

Host machine:
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

# env | sort | grep -i proxy
http_proxy=http://10.242.12.202:30100
HTTP_PROXY=http://10.242.12.202:30100
https_proxy=https://10.242.12.202:30100
HTTPS_PROXY=https://10.242.12.202:30100

# wget http://google.com
--2018-02-13 20:21:52--  http://google.com/
Connecting to 10.242.12.202:30100... connected.
Proxy request sent, awaiting response... 302 Found
Location: http://www.google.ru/?gfe_rd=cr&dcr=0&ei=sB6DWtuVEZHEsAHI_InYCw [following]
--2018-02-13 20:21:52--  http://www.google.ru/?gfe_rd=cr&dcr=0&ei=sB6DWtuVEZHEsAHI_InYCw
Connecting to 10.242.12.202:30100... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                        [ <=>                                            ]  11.83K  --.-KB/s    in 0s

2018-02-13 20:21:52 (343 MB/s) - ‘index.html’ saved [12112]

# wget https://google.com
--2018-02-13 20:22:07--  https://google.com/
Connecting to 10.242.12.202:30100... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://www.google.ru/?gfe_rd=cr&dcr=0&ei=vx6DWvXkM5LCsAGBp6zYDw [following]
--2018-02-13 20:22:07--  https://www.google.ru/?gfe_rd=cr&dcr=0&ei=vx6DWvXkM5LCsAGBp6zYDw
Connecting to 10.242.12.202:30100... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

index.html.1                      [ <=>                                            ]  11.67K  --.-KB/s    in 0.001s

2018-02-13 20:22:08 (19.2 MB/s) - ‘index.html.1’ saved [11947]
```

My Docker:
```
# docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

# cat ~/.docker/config.json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://10.242.12.202:30100",
     "httpsProxy": "https://10.242.12.202:30100"
   }
 }
}

# systemctl show --property=Environment docker
Environment=HTTP_PROXY=http://10.242.12.202:30100 http_proxy=http://10.242.12.202:30100 HTTPS_PROXY=https://10.242.12.202:30100 https_proxy=https://10.242.12.202:30100
```

My `Dockerfile`:
```
FROM alpine

RUN env | sort
RUN ping -c1 -W2 google.com || true
RUN wget http://google.com
RUN wget https://google.com
```

Test:
```
# docker build --no-cache .
Sending build context to Docker daemon  27.65kB
Step 1/5 : FROM alpine
 ---> 3fd9065eaf02
Step 2/5 : RUN env | sort
 ---> Running in 017a716d443a
HOME=/root
HOSTNAME=017a716d443a
HTTPS_PROXY=https://10.242.12.202:30100
HTTP_PROXY=http://10.242.12.202:30100
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
http_proxy=http://10.242.12.202:30100
https_proxy=https://10.242.12.202:30100
Removing intermediate container 017a716d443a
 ---> de62ddad1e3d
Step 3/5 : RUN ping -c1 -W2 google.com || true
 ---> Running in 2771a1840c35
PING google.com (173.194.73.100): 56 data bytes

--- google.com ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
Removing intermediate container 2771a1840c35
 ---> b2d0eae6974b
Step 4/5 : RUN wget http://google.com
 ---> Running in 0a74748ff516
Connecting to 10.242.12.202:30100 (10.242.12.202:30100)
index.html           100% |*******************************| 11911   0:00:00 ETA

Removing intermediate container 0a74748ff516
 ---> 956d7662e551
Step 5/5 : RUN wget https://google.com
 ---> Running in 24142c8db6cb
Connecting to 10.242.12.202:30100 (10.242.12.202:30100)
```

And it hangs or will finish with timeout error.

**Comment by thaJeztah** [comment] 2018-02-13 17:51
Both HTTPS and HTTP proxies are running on the same IP-address, and port?

**Comment by nevmerzhitsky** [comment] 2018-02-13 17:58
exactly!

13 февр. 2018 г. 20:54 пользователь "Sebastiaan van Stijn" <
notifications@github.com> написал:

**Comment by thaJeztah** [comment] 2018-02-13 18:18
It could be an alpine/busybox issue; do you see the same if you run an Ubuntu image, or install curl in the Alpine image?

Docker doesn’t sit between your container and the proxy (other than having set up the networking namespace)

**Comment by nevmerzhitsky** [comment] 2018-02-13 20:24
> It could be an alpine/busybox issue; do you see the same if you run an Ubuntu image, or install curl in the Alpine image?

Big thank you! I try to play with SSL in `alpine` but fail, then I found the issue https://github.com/docker-library/official-images/issues/2773 which may relate but it didn't help me. Then I switched to `ubuntu:16.04` image and install `wget` manually - the problem disappears.

**Comment by thaJeztah** [comment] 2018-02-13 20:34
Right, so the problem likely is that the default `wget` in Alpine is in fact `busybox`; here you can see that it's a symlink to busybox:

```bash
docker run --rm alpine ls -la /usr/bin/wget
lrwxrwxrwx    1 root     root            12 Jan  9 19:37 /usr/bin/wget -> /bin/busybox
```

You can try installing an actual `wget` in alpine to see if that issue was fixed (the busybox version will get replaced with an actual `wget` binary);

```bash
docker run --rm alpine sh -c 'apk add --no-cache -q wget && ls -la /usr/bin/wget' 
-rwxr-xr-x    1 root     root        494784 Nov  9 20:19 /usr/bin/wget
```

If the proxy works correctly with the actual `wget`, then it's likely busybox

**Comment by lgathy** [comment] 2018-02-16 12:58
@rfboykin @neethuabu +anybody still having this issue on Windows with Docker Toolbox and command line tools, this is what worked for me: use Kitematic, set proxy for it as described here: https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes 
This should also cover cases where you need authentication for the proxy. After that start the Docker CLI from Kitematic. All proxy settings are inherited inside that shall, so command line tools will work.

**Comment by thaJeztah** [comment] 2018-02-19 12:33
Reading through the discussion above, I'm closing this issue; as explained above, configuration of the proxy to use for the _daemon_ is separate from proxies to use inside a _container_ (including containers used during _build_).

Docker 17.07 and up allow you to configure a default proxy, using the CLI configuration file (https://github.com/moby/moby/issues/24697#issuecomment-365333298);

> Docker 17.07 and up also allows you to configure default proxies for containers in the CLI configuration file (`~/.docker/config.json`) see https://github.com/docker/cli/pull/93 - those proxies are automatically used as `--env` when running a container, and `--build-arg` during build. 

Which makes configuring this easier.

w.r.t. the busybox/alpine issue mentioned above; that's not an issue with the code that's maintained in this repository, and out of our hands.

Based on the above, I'm closing this issue

**Closed by thaJeztah** 2018-02-19 12:33 UTC
Labels: area/builder, platform/desktop, version/1.12

**Comment by weihongliang233** [comment] 2023-12-15 23:28
For those using Docker Desktop for Windows, The `--build-arg` works. But you have to use `http://host.docker.internal:{your port}` instaed of `http://127.0.0.1:{your port}`.

**Comment by Ali-Flt** [comment] 2024-02-01 20:22
You may need to run
```
export http_proxy=...
export https_proxy=...
```
before running the docker build command.
