### ISSUE TITLE
`docker load -i file.tar.gz` broken on master

### ISSUE THREAD

**Issue by friism** [moby/moby#34030] opened 2017-07-09 23:44 UTC
```
> docker load -i .\CBaseOs_rs_prerelease_16237.1001.170701-0549_amd64fre_NanoServer_en-us.tar.gz
Windows does not support legacy loading of images
```

```
docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   b227c56
 Built:        Sat Jul  8 23:49:24 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

(this is the master-build as of today)

If I attempt the same operation using Docker CE 17.06 I get:

```
PS C:\Users\friism\Downloads> docker load -i .\CBaseOs_rs_prerelease_16237.1001.170701-0549_amd64fre_NanoServer_en-us.tar.gz
open C:\Users\friism\AppData\Local\Temp\docker-import-550341122\Files\json: The system cannot find the file specified.
```

The image is a Microsoft pre-release image.

cc @johnstep @patricklang @jhowardmsft

**Comment by thaJeztah** [comment] 2017-07-09 23:52
Looks like this was added in https://github.com/moby/moby/commit/42c5c1a9ec14f00d5a5367131493cbd6de7d72b0, which is part of https://github.com/moby/moby/pull/33241

ping @johnstep, @crosbymichael as well

**Comment by jhowardmsft** [comment] 2017-07-10 15:07
Are you guys normally given a .tar.gz rather than a converted .tar for prerelease builds?

**Comment by jhowardmsft** [comment] 2017-07-10 16:42
It looks like the wrong thing has been distributed on connect. The `.tar.gz` is a container layer off the build system, not a docker image. You would need a conversion utility to convert to a `.tar` docker image. I'm following up with @friism offline.

**Comment by jhowardmsft** [comment] 2017-07-10 16:42
Hence closing this issue here. It's not a bug in docker.

**Closed by jhowardmsft** 2017-07-10 16:42 UTC
Labels: platform/windows, version/master

**Comment by thaJeztah** [comment] 2017-07-10 19:14
Thanks @jhowardmsft !
