### ISSUE TITLE
Containers have duplicate Mac addresses

### ISSUE THREAD

**Issue by deluxestyle** [moby/moby#48595] opened 2024-10-07 16:55 UTC
### Description

Two containers got after a docker service restart the same MAC address. This caused a lot of network issues. 
it happened only twice after the restart. Not always 
Containers are in the same bridge network

### Reproduce

Restart of host or docker service

### Expected behavior

Each container should have it’s own MAC address 

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:11 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 10
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-26-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.58GiB
 Name: DietPi
 ID: 9fb2b93b-d4a0-470f-bfb8-c5496e5161db
 Docker Root Dir: /mnt/dietpi_userdata/docker-data
 Debug Mode: false
 Username: wtanzer
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by deluxestyle** [comment] 2024-10-07 18:19
I can reproduce it
as soon I restart the docker deamon multiple containser have now duplicate mac addresses

`
docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "94a8264ec20f5912e17b26cffa1a9e2816e81a26b7860dd7f240adb6d6f5fe18",
        "Created": "2024-10-07T20:16:34.114417562+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "29f1f78078b4435dc29363c94d0db0d0ec731248b5ec25755f1e5933ce0a3727": {
                "Name": "victoriametrics",
                "EndpointID": "95c95e3651416d2e0d9a106af265bf0424c9ca9d4c9b16089c4126e3aaacfd13",
                "MacAddress": "02:42:ac:11:00:08",
                "IPv4Address": "172.17.0.8/16",
                "IPv6Address": ""
            },
            "32683c4f98daf7b95997879c33535ef562529fd6940bca0c0d0d727d40836a45": {
                "Name": "wud",
                "EndpointID": "20495f440381bf23d4888b9cc33facc3baae6fbb072d1e403127e50bf451bf55",
                "MacAddress": "02:42:ac:11:00:06",
                "IPv4Address": "172.17.0.6/16",
                "IPv6Address": ""
            },
            "362db5ad3326607c113bd8199affd437e31739b658efe27ee260eb56fc00c5d8": {
                "Name": "pihole",
                "EndpointID": "207d7614c665f05bb7d0626d83ebc4a0ed5b02ab49b9268d5927c370d06aa8ad",
                "MacAddress": "02:42:ac:11:00:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": ""
            },
            "3c9af1a4e67a4b4d1b2d1bfe522b0b4444babbb7f6194b2c6d4cd2f5b1d50c85": {
                "Name": "portainer",
                "EndpointID": "96e20d1edf16f081d63608d5c81fc0320a72904be47255f32c8855929141b800",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            },
            "5929c7f569c8a22b577b785809c3a09d15ce2b592656dbaa3e939aa0398aa76f": {
                "Name": "mosquitto",
                "EndpointID": "c11fdded35c874bf5d0863bb6a6236f5b62974b21be4e2b03e38c5176bba1bcf",
                "MacAddress": "02:42:ac:11:00:07",
                "IPv4Address": "172.17.0.7/16",
                "IPv6Address": ""
            },
            "65d3698682ec7054b1d4bd23574949f777bfc316138a3e911314828103f8a3c8": {
                "Name": "zigbee2mqtt",
                "EndpointID": "35ba7b908205a127d612548a90c6b0dc38e6325d00a0a0bddfce9678e9280f54",
                "MacAddress": "02:42:ac:11:00:07",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "bd04280e2e40bfeadb4ce96860f9165762dc5525ab8b3e862b65da5a3114ac4e": {
                "Name": "nginx-proxy-manager",
                "EndpointID": "b370dcf241dc02da7cf905d30828381515e81b3f96ea74d5cc7f2bde33fa4588",
                "MacAddress": "02:42:ac:11:00:09",
                "IPv4Address": "172.17.0.9/16",
                "IPv6Address": ""
            },
            "c4464d042b28e4d2bc503aac6790aa0298f844a42a37f1b0d08a8288e217d6db": {
                "Name": "vaultwarden",
                "EndpointID": "6e486b857c03b62779d84e78b518f1d37061a33ecc9e06c4b427c155bb58ca45",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

`

**Comment by akerouanton** [comment] 2024-10-07 19:37
Thanks for reporting!

By any chance, are you using Portainer?

**Comment by thaJeztah** [comment] 2024-10-07 20:06
I see at least a portainer container in the output (`"Name": "portainer"`)

**Comment by deluxestyle** [comment] 2024-10-07 20:09
yes, I'm using portainer. but mostly just for monitoring the containers

**Comment by akerouanton** [comment] 2024-10-07 20:49
Oh, woops didn't pay attention to container names! 🙈 

Okay, so portainer is in use. Did you use its Edit / Duplicate feature somehow, or any other Portainer's feature that could cause it to (re)create container(s) on your behalf?

Could you tell us when you created these containers (eg. with what Docker version), and whether you tried to recreate them from scratch (ie. `docker rm` + `docker run` / `docker compose up`) since you noticed this bug?

**Comment by deluxestyle** [comment] 2024-10-07 20:58
Ah. In the end every Container was recreated with portainer as soon a new Image is available. 
I update all containers with Portainer

I have no clue with docker version I had when the containers have been created

**Comment by unfixa1** [comment] 2024-10-08 03:12
When multiple containers are in the same bridge network, Docker should assign a unique MAC address to each container. If there is a problem with the network configuration, it may cause duplicate MAC addresses.
You can create a custom bridge network and connect the container to it. Custom networks usually provide better management of container network configuration.
docker network create my_custom_network
docker run --network my_custom_network ...

In addition, you can actually use [servbay](servbay.com) to replace docker, which is better than docker and mamp on mac.

**Comment by akerouanton** [comment] 2024-10-08 06:25
Okay, just as I thought. You're hitting the same issue as described in: https://github.com/moby/moby/issues/48082#issuecomment-2228713351.

Basically, the issue comes from Portainer - it can't know whether the MAC address was assigned by the Engine, or if it's user-supplied, so it reuses it unconditionnally. In the latter case, it's totally fine to reuse it, but in the former case, that leads to duplicate MAC addresses.

We might consider improving our API to better seperate user-supplied config, and container state (see https://github.com/moby/moby/issues/48168). Or maybe we should improve the way we manage MAC addreses, to detect such case.

I'm going to close this ticket as a duplicate of https://github.com/moby/moby/issues/48082, but feel free to continue the conversation.

**Closed by akerouanton** 2024-10-08 06:25 UTC
Labels: status/0-triage, kind/bug, area/networking, version/27.3

**Comment by deluxestyle** [comment] 2024-10-08 07:06
Thank you. 
I guess then I will not use portainer for updates anymore

**Comment by Nuke142** [comment] 2024-10-18 11:21
Same
