### ISSUE TITLE
Don't now how to configure Traefik-EE on Docker Enterprise on my Sles 15 machine.

### ISSUE THREAD

**Issue by Gio5775** [moby/moby#40424] opened 2020-01-29 15:38 UTC
Hey i just installed Traefik-EE on Docker enterprise and was able to reach the Dashboard of Traefik-EE. But i don't see any routing configuration.
Now i would like to configure Traefik-EE but i don't now how. I try to create a traefik.toml or a config.toml file. The biggest issue that i have is i don't now how to insert it to traefik-EE. 

Would be nice if some one could help me. Thanks

**Comment by thaJeztah** [comment] 2020-01-29 15:51
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)


For this question, perhaps the traefik issue tracker (https://github.com/containous/traefik) or their forums (https://community.containo.us) is more suitable

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-01-29 15:51 UTC
