### ISSUE TITLE
Force dockerd to resync /var/lib/docker/image

### ISSUE THREAD

**Issue by ilya-zuyev** [moby/moby#42336] opened 2021-04-28 21:17 UTC
Hi guys, I'm making some experiments with dockerd on my linux machine. I'm trying to run two instances of dockerd and share `/var/lib/docker/image` between them. The idea is to build an image using daemon1 and see it in daemon2. Surprisingly, it works, but I have to restart daemon2 to sync the changes. Wondering, if there's a way to force the daemon to reread the images repo on disk without the full restart. 
And yes, I know, the whole idea is a _very_ dirty hack :)

**Comment by thaJeztah** [comment] 2021-05-03 14:24
No, this is not currently possible. The `/var/lib/docker` directory is designed to be exclusively accessed by a single daemon; while some things "may work", there are many pitfalls where sharing the storage may cause problems, and could lead to data-loss (e.g., each daemon would be  performing reference counting separately, not being aware that other daemons could be using data that's not referenced by that daemon).

There's been some discussion in containerd (https://github.com/containerd/containerd/issues/2267) for shared storage, and potentially containerd could provide this to an extend (using its namespaced storage), but dockerd currently does not yet use those parts of containerd.

Let me close this ticket, because this is not a scenario that `/var/lib/docker` was designed for, but feel free to continue the conversation

**Closed by thaJeztah** 2021-05-03 14:24 UTC
Labels: area/daemon, area/images, kind/question
