### ISSUE TITLE
[1.9.0-rc3] docker is four times slower than before

### ISSUE THREAD

**Issue by AndyBerman** [moby/moby#17448] opened 2015-10-28 19:25 UTC
Testing  docker 1.9.0-rc3 performance.

Both "build" and "run" commands are at least 4 times longer than earlier versions of Docker.

Running "time docker run busybox date" takes over 2 seconds with 1.9.0-rc3 (after the busybox image is pulled locally).

It takes .5 seconds on other versions of Docker.

Builds are also much much slower.

Running on RHEL7 3.10.0-229.14.1.el7.x86_64

[aberman@r10a-docker-aberman test]$ docker version
Client:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:42:24 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:42:24 UTC 2015
 OS/Arch:      linux/amd64

[aberman@r10a-docker-aberman test]$ docker info
Containers: 45
Images: 676
Server Version: 1.9.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-253:9-18882145-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/docker_dg/data
 Metadata file: /dev/docker_dg/metadata
 Data Space Used: 19.03 GB
 Data Space Total: 102 GB
 Data Space Available: 82.98 GB
 Metadata Space Used: 34.11 MB
 Metadata Space Total: 5.365 GB
 Metadata Space Available: 5.33 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 2
Total Memory: 3.703 GiB
Name: r10a-docker-aberman
ID: PQPG:GZQZ:64RB:2YJR:ONJI:SZUK:Q2WC:V4WJ:DNEK:NXPY:K4DF:QUXZ

[aberman@r10a-docker-aberman test]$ uname -a
Linux r10a-docker-aberman 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Aug 25 11:21:22 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment] 2015-10-28 19:28
I see this is with devicemapper.
What version were you running before?

**Comment by AndyBerman** [comment] 2015-10-28 19:36
We've always used Devicemapper, but we have recently switched from loopback
to direct-lvm for it.

We've tested 1.6, 1.8 and 1.9 on both loopback and direct-lvm and never saw
this slowness.

**Comment by thaJeztah** [comment] 2015-10-30 10:32
ping @vbatts @rhvgoyal

**Comment by rhvgoyal** [comment] 2015-10-30 12:27
@AndyBerman  Can we try couple of things to narrow it down a bit.

- Can you try any other storage graph driver (say -s overlay) and see if you notice the same degree of slowness. Don't compare devicemapper and overlay. Just compare the performance of overlay between 1.8 and 1.9 and see if there are changes. I am trying to figure out if this slowness is due to devicemapper or some changes in generic docker layer.

- If we determine that slowness is due to devicemapper, then only big change in 1.9 has been deferred device deletion. I see you have that disabled. Now my other suspicion will be locking changes I had made. In that case we can try some git bisect or go back to commit previous to deferred device deletion feature and see if slowness is still there or not.

Anyway, can we first try it with any other graphdriver and see if performance regression is there or not. In the mean time I will also give it a try on my machine and see if container startup time has changed between 1.8 and 1.9.

**Comment by AndyBerman** [comment] 2015-10-30 14:21
We tested 3 times for overlay and devicemapper for 1.8 and 1.9

There was a very slight slowdown from overlay for Docker 1.8 to overlay for Docker 1.9
There's more of a slowdown from devicemapper for Docker 1.8 to devicemapper for Docker 1.9

Bottom line is that overlay is much faster than devicemapper for Docker 1.8 and especially 1.9

----------------------------------------------------------------------------
docker 1.8.3 (devicemapper loopback)
----------------------------------------------------------------------------

[root@r10a-docker7e sysconfig]# docker info
Containers: 5
Images: 185
Storage Driver: devicemapper
Pool Name: docker-253:4-3670017-pool
Pool Blocksize: 65.54 kB
Backing Filesystem: extfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 5.153 GB
Data Space Total: 107.4 GB
Data Space Available: 100.3 GB
Metadata Space Used: 8.552 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.139 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 1
Total Memory: 2.782 GiB
Name: r10a-docker7e
ID: MOQH:YKG6:QR56:Y6AC:HI2I:XHSJ:6FKD:SANM:RTDK:BUYQ:LDIS:KXPT
Http Proxy: gatekeeper.mitre.org:80
Https Proxy: gatekeeper.mitre.org:80
[root@r10a-docker7e sysconfig]# docker version
Client:
Version:      1.8.3
API version:  1.20
Go version:   go1.4.2
Git commit:   f4bf5c7
Built:        Mon Oct 12 06:06:01 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.8.3
API version:  1.20
Go version:   go1.4.2
Git commit:   f4bf5c7
Built:        Mon Oct 12 06:06:01 UTC 2015
OS/Arch:      linux/amd64

[root@r10a-docker7e sysconfig]# time docker run busybox date
Fri Oct 30 13:49:54 UTC 2015

real    0m0.860s
user    0m0.021s
sys     0m0.007s
[root@r10a-docker7e sysconfig]# time docker run busybox date
Fri Oct 30 13:50:01 UTC 2015

real    0m1.191s
user    0m0.019s
sys     0m0.008s
[root@r10a-docker7e sysconfig]# time docker run busybox date
Fri Oct 30 13:50:03 UTC 2015

real    0m1.273s
user    0m0.019s
sys     0m0.008s

----------------------------------------------------------------------------
docker 1.8.3 (overlay)
----------------------------------------------------------------------------

[root@r10a-docker7e ~]# docker info
Containers: 0
Images: 0
Storage Driver: overlay
Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 1
Total Memory: 2.782 GiB
Name: r10a-docker7e
ID: MOQH:YKG6:QR56:Y6AC:HI2I:XHSJ:6FKD:SANM:RTDK:BUYQ:LDIS:KXPT
Http Proxy: gatekeeper.mitre.org:80
Https Proxy: gatekeeper.mitre.org:80
[root@r10a-docker7e ~]# docker version
Client:
Version:      1.8.3
API version:  1.20
Go version:   go1.4.2
Git commit:   f4bf5c7
Built:        Mon Oct 12 06:06:01 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.8.3
API version:  1.20
Go version:   go1.4.2
Git commit:   f4bf5c7
Built:        Mon Oct 12 06:06:01 UTC 2015
OS/Arch:      linux/amd64

[root@r10a-docker7e ~]# time docker run busybox date
Fri Oct 30 13:59:03 UTC 2015

real    0m0.347s
user    0m0.021s
sys     0m0.011s
[root@r10a-docker7e ~]# time docker run busybox date
Fri Oct 30 13:59:06 UTC 2015

real    0m0.276s
user    0m0.019s
sys     0m0.010s
[root@r10a-docker7e ~]# time docker run busybox date
Fri Oct 30 13:59:08 UTC 2015

real    0m0.344s
user    0m0.014s
sys     0m0.014s

----------------------------------------------------------------------------
docker 1.9.0-rc3 (overlay)
----------------------------------------------------------------------------

[root@r10a-docker7e ~]# docker info
Containers: 3
Images: 2
Server Version: 1.9.0-rc3
Storage Driver: overlay
Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 1
Total Memory: 2.782 GiB
Name: r10a-docker7e
ID: MOQH:YKG6:QR56:Y6AC:HI2I:XHSJ:6FKD:SANM:RTDK:BUYQ:LDIS:KXPT
Http Proxy: gatekeeper.mitre.org:80
Https Proxy: gatekeeper.mitre.org:80

[root@r10a-docker7e ~]# docker version
Client:
Version:      1.9.0-rc3
API version:  1.21
Go version:   go1.4.2
Git commit:   2100b94
Built:        Wed Oct 28 01:42:24 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.9.0-rc3
API version:  1.21
Go version:   go1.4.2
Git commit:   2100b94
Built:        Wed Oct 28 01:42:24 UTC 2015
OS/Arch:      linux/amd64

[root@r10a-docker7e ~]# time docker run busybox date
Fri Oct 30 14:05:29 UTC 2015

real    0m0.523s
user    0m0.052s
sys     0m0.018s
[root@r10a-docker7e ~]# time docker run busybox date
Fri Oct 30 14:05:32 UTC 2015

real    0m0.445s
user    0m0.049s
sys     0m0.013s
[root@r10a-docker7e ~]# time docker run busybox date
Fri Oct 30 14:05:34 UTC 2015

real    0m0.369s
user    0m0.046s
sys     0m0.014s

**Comment by rhvgoyal** [comment] 2015-10-30 14:28
@AndyBerman I did some testing on F22. Tested docker 1.9 and 1.8 with devicemapper driver. Ran `time docker run busybox date` and I don't see that 400% slowdown. 

Docker 1.8
---------------
$ time docker run busybox date
Fri Oct 30 14:20:16 UTC 2015

real    0m1.153s
user    0m0.029s
sys     0m0.033s

$ time docker run busybox date
Fri Oct 30 14:20:20 UTC 2015

real    0m1.373s
user    0m0.029s
sys     0m0.025s

$ time docker run busybox date
Fri Oct 30 14:20:25 UTC 2015

real    0m1.192s
user    0m0.034s
sys     0m0.025s

Docker 1.9
---------------
$ time docker run busybox date
Fri Oct 30 13:42:24 UTC 2015

real    0m1.332s
user    0m0.060s
sys     0m0.029s

$ time docker run busybox date
Fri Oct 30 13:42:31 UTC 2015

real    0m1.328s
user    0m0.040s
sys     0m0.032s

**Comment by tiborvass** [comment] 2015-11-07 01:37
I also can't reproduce this. Any updates @AndyBerman @rhvgoyal ?

**Comment by AndyBerman** [comment] 2015-11-07 03:40
We upgraded to the latest release (1.9.0) and we're still seeing it.

I tried splitting "run" into "create" & "start" to see if it was just one
of them being slower, but they are both much slower.

**Comment by rhvgoyal** [comment] 2015-11-09 14:22
@AndyBerman As I am not seeing problem on my setup, its hard to figure out what's going on. can you try two things.

- Move away from loop devices and use proper block devices and setup an lvm thin pool and use that.
- Enable debugging of docker daemon. And upload the logs of "docker start" somewhere. Both for 1.8 and 1.9. I will like to compare these two and see if something is pops out.

**Comment by AndyBerman** [comment] 2015-11-09 17:59
We've been using devicemapper thin pool for all of our Docker 1.8 and 1.9 testing.
Times have changed a bit and now docker 1.9 is about half the speed of docker 1.62-cs5 for the "docker run busybox date" command.   (1.4 seconds vs .7).

Here is part of daemon log for 1.9 if you don't mind taking a quick look at it.  We're not using 1.8 any more.

Nov 09 11:36:36 r10a-docker-aberman systemd[1]: Starting Docker Application Container Engine...
Nov 09 11:36:36 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:36.855062896-05:00" level=debug msg="Server created for HTTP on fd ()"
Nov 09 11:36:36 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:36.855853912-05:00" level=debug msg="[graphdriver] trying provided driver \"devicemapper\""
Nov 09 11:36:36 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:36.862101630-05:00" level=debug msg="devicemapper: driver version is 4.29.0"
Nov 09 11:36:36 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:36.862456853-05:00" level=debug msg="Generated prefix: docker-253:9-18882145"
Nov 09 11:36:36 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:36.862502399-05:00" level=debug msg="devmapper: Checking for existence of the pool docker-253:9-18882145-pool"
Nov 09 11:36:36 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:36.862906973-05:00" level=debug msg="Pool doesn't exist. Creating it."
Nov 09 11:36:36 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:36.865978647-05:00" level=info msg="API listen on /var/run/docker.sock"
Nov 09 11:36:37 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:37.098245308-05:00" level=debug msg="[deviceset] loadDeviceFilesOnStart()"
Nov 09 11:36:37 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:37.099538890-05:00" level=debug msg="Loading data for file /var/lib/docker/devicemapper/metadata/008e6fff6061ad4d5e4ca0c6059f0e9076322892597d1c73201d58fdbcd324ea"
Nov 09 11:36:37 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:37.099812084-05:00" level=debug msg="Loading data for file /var/lib/docker/devicemapper/metadata/00e90969189ff86c9abc1e193883ce29c63f594ff164ebef269f7e03f82aad59"
Nov 09 11:36:37 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:37.099920209-05:00" level=debug msg="Loading data for file /var/lib/docker/devicemapper/metadata/0114405f9ff12fb7b012d0f7eb2f958c6ab8638061f67bc0a12cfc308ed31ee4"
Nov 09 11:36:37 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:37.100017898-05:00" level=debug msg="Loading data for file /var/lib/docker/devicemapper/metadata/0152d85f0ad4e571b6c3116f5b3b7c023d87947a0a2bf9330e47d553a4497408"
Nov 09 11:36:37 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:37.100110678-05:00" level=debug msg="Loading data for file /var/lib/docker/devicemapper/metadata/01c5026c459656f6f000b37815db6fb3db6997f45a41686858d2d0f1cfa72b93"
Nov 09 11:36:37 r10a-docker-aberman docker[27802]: time="2015-11-09T11:36:37.100218223-05:00" level=debug msg="Loading data for file /var/lib/docker/devicemapper/metadata/028167fb340658c4a8afdbe13582a1d2e058b1b1512c0a20def7430da6468ab8"

**Comment by rhvgoyal** [comment] 2015-11-09 18:09
@AndyBerman yes you are using thin pool but that thin pool is built on top of loop devices. We don't recommend using loop devices for thin pool. Instead use a real block device and setup thin pool on top of that. See docker -storage-setup here.

https://github.com/projectatomic/docker-storage-setup

The logs you have pasted above are from docker daemon initialization time. I am looking for logs when you do "docker start <container>"

**Comment by AndyBerman** [comment] 2015-11-09 18:23
Below is what we did to setup the docker storage.  I thought this was using
block devices:

   1. pvcreate /dev/sdb
   2. vgcreate docker_dg /dev/sdb
   3. lvcreate --wipesignatures y -n data docker_dg -l 95%VG
   4. lvcreate --wipesignatures y -n metadata docker_dg -l 5%VG
   5. dd if=/dev/zero of=/dev/docker_dg/metadata bs=1M count=10

Sorry about the logs, here you go:

Nov 09 13:21:42 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:42.401968799-05:00" level=debug msg="Calling POST
/v1.21/containers/3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33/start"
Nov 09 13:21:42 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:42.402055239-05:00" level=info msg="POST
/v1.21/containers/3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33/start"
Nov 09 13:21:42 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:42.404744853-05:00" level=debug
msg="activateDeviceIfNeeded(3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.076293321-05:00" level=debug msg="Assigning
addresses for endpoint lonely_sammet's interface on network bridge"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.076417503-05:00" level=debug
msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.591133387-05:00" level=debug msg="Releasing
addresses for endpoint lonely_sammet's interface on network bridge"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.591243765-05:00" level=debug
msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.599748501-05:00" level=debug msg="[devmapper]
UnmountDevice(hash=3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.599823177-05:00" level=debug msg="[devmapper]
Unmount(/var/lib/docker/devicemapper/mnt/3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.671246658-05:00" level=debug msg="[devmapper]
Unmount done"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.671349751-05:00" level=debug msg="[devmapper]
deactivateDevice(3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.671481458-05:00" level=debug msg="[devmapper]
removeDevice
START(docker-253:9-18882145-3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.705172040-05:00" level=debug msg="[devmapper]
removeDevice
END(docker-253:9-18882145-3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.705254342-05:00" level=debug msg="[devmapper]
deactivateDevice
END(3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)"
Nov 09 13:21:43 r10a-docker-aberman docker[27802]:
time="2015-11-09T13:21:43.705296477-05:00" level=debug msg="[devmapper]
UnmountDevice(hash=3379e70187c36273f3df9b7df01bf25fd9d9012da9d030178c591ae2f0e48a33)
END"

**Comment by tiborvass** [comment] 2015-11-30 09:51
@AndyBerman @rhvgoyal any updates on this?

@AndyBerman Are you still seeing this with 1.9.1?

**Comment by AndyBerman** [comment] 2015-11-30 13:07
Yes, even with 1.9.1, I'm still seeing run times four times slower.

**Comment by duglin** [comment] 2016-02-16 19:01
@AndyBerman is this still an issue?

**Comment by AndyBerman** [comment] 2016-02-17 18:14
Yes, and it's also that way in docker 1.10.
This command:  time docker run busybox hostname

​takes about .6 seconds on Docker 1.6, vs. 1.1 seconds ​on Docker 1.9/1.10.

**Comment by biji** [comment] 2016-05-05 17:21
I'm using Fedora 24 , building, running is very slow. Very high disk io up to 60MB/s. Setup is using thinpool lvm. 

Then I try to save image and load it to docker on Ubuntu 15.04. Running there super fast, very low disk io

Thanks

**Comment by AkihiroSuda** [comment] 2020-03-05 07:59
Closing as outdated. Also, devicemapper was deprecated.

**Closed by AkihiroSuda** 2020-03-05 07:59 UTC
Labels: area/storage/devicemapper, priority/P3, version/1.9
