### ISSUE TITLE
docker network rm <name> doesn't remove duplicate networks

### ISSUE THREAD

**Issue by larsnystrom** [moby/moby#33561] opened 2017-06-07 08:26 UTC
**Description**

Due to #20648 docker sometimes creates duplicate networks with the same name. Running `docker network rm <name>` only removes one of them. This also affects `docker-compose down`, see https://github.com/docker/compose/issues/4890.

**Steps to reproduce the issue:**
1. Run `docker-compose up <service1> & docker-compose up <service2>` 
2. Check that there are two networks with `docker network ls`.
3. `docker network rm <network_name>` will only remove one of the networks.

**Describe the results you received:**

`docker network rm <network>` removes one network with the specified name.

**Describe the results you expected:**

`docker network rm <network>` should remove all networks with the specified name.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 112
 Running: 4
 Paused: 0
 Stopped: 108
Images: 1568
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.786 GiB
Name: moby
ID: PR5M:KFV7:C5HM:7FMM:MSVL:LZS2:BY6T:STVM:OUUU:4OTZ:KXAA:IE74
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 50
 System Time: 2017-06-07T08:23:56.16651591Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on docker for mac on macOS Sierra 10.12.5
Version 17.03.1-ce-mac12 (17661)
Channel: stable
d1db12684b

**Comment by thaJeztah** [comment] 2017-06-07 11:13
Yes, this should probably create an _error_ instead of picking the first occurrence.

To easily reproduce; create two networks with duplicate names (using the API);


```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  -XPOST \
  "http://localhost/v1.30/networks/create" \
  -H "Content-Type: application/json" \
  -d '{"Name":"i-am-not-unique", "CheckDuplicate":false}'

curl \
  --unix-socket /var/run/docker.sock \
  -XPOST \
  "http://localhost/v1.30/networks/create" \
  -H "Content-Type: application/json" \
  -d '{"Name":"i-am-not-unique", "CheckDuplicate":false}'
```

(second call shows a warning):

```json
{"Id":"74d8acd9e4a31834de4dd4e9563e7edf628bc7a1f046d246fc63b37837221646","Warning":"Network with name i-am-not-unique (id : 3a9c8f5b1887bd702fc24429380afc7e1dfc4502a887eab17f10f1cb47f8dab1) already exists"}
```

You should now have two networks with the same name;

```bash
$ docker network ls

NETWORK ID          NAME                DRIVER              SCOPE
556cfae3a2ce        bridge              bridge              local
13cf280a1bbf        host                host                local
3a9c8f5b1887        i-am-not-unique     bridge              local
74d8acd9e4a3        i-am-not-unique     bridge              local
d9e4c03728a0        none                null                local
```

Inspecting the network by name correctly shows an error;

```bash
$ docker network inspect i-am-not-unique
[]
Error response from daemon: network i-am-not-unique is ambiguous (2 matches found based on name)
```

However, _removing_ the network silently ignores the second network, and removes the first one;

```bash
$ docker network rm i-am-not-unique
i-am-not-unique
```

Removing the network should print an error, and provide instructions to use the network's _ID_ instead of _name_ to specify which network to remove


We can probably resolve this two ways;

1. Perform a network lookup (lookup network-ID based on name), then use the network ID to delete the network. Looking up the network by name already produces an error. From an API perspective, using ID instead of Name is cleaner as well 😇 
2. We would still have to prevent the `DELETE` action if it's ambiguous, so doing a check daemon-side would be needed as well

**Comment by yongtang** [comment] 2017-06-07 16:47
I think this issue is related to #30897 (which handles the uniqueness of network name). Let me update the #30897.

**Comment by thaJeztah** [comment] 2017-06-07 17:47
Oh, yes, forgot about that one :+1:

**Comment by yongtang** [comment] 2017-06-08 16:47
Created related issue docker/cli#167 , that may need to be addressed.

**Comment by thaJeztah** [comment] 2017-08-17 15:19
Linking https://github.com/moby/moby/pull/34509, which is slightly related

**Comment by moltar** [comment] 2019-04-30 02:51
If anyone stumbles on this, here is a quick fix:

```
docker network rm $(docker network ls -f name="${COMPOSE_PROJECT_NAME}_default" -q)
```

My use case was in CI environment, and I couldn't simply manually remove the offending duplicate network.

The above scripts it.

**Comment by EdwardIII** [comment] 2021-01-28 14:35
I'm seeing `Error response from daemon: network duplicate-network_default is ambiguous (2 matches found on name)` when trying to bring up two containers with GNU parallel, I think maybe it's related to this?

I've put an example here: https://github.com/EdwardIII/docker-duplicate-network-bug

Version info:

```
docker-compose version 1.27.4, build 40524192
Docker version 20.10.0, build 7287ab3
Docker for Mac 3.0.3 (51017)
```

**Comment by thaJeztah** [comment] 2021-01-28 16:48
@EdwardIII related, but probably on the "create" / attach side; looks like https://github.com/moby/moby/issues/20648

**Comment by akerouanton** [comment] 2023-09-12 17:27
> Describe the results you expected:
> 
> docker network rm <network> should remove all networks with the specified name.

This issue has worsened since OP reported it. If you happen to have networks with duplicated name, you have to delete them by their ID.

Starting with the next release, it won't be possible to create networks with duplicate names  (even when doing concurrent API calls). As such, I think there's nothing more we can do here, so let me close it.

**Closed by akerouanton** 2023-09-12 17:27 UTC
Labels: kind/bug, area/networking, platform/desktop, status/accepted, version/17.03
