### ISSUE TITLE
Changing even 1 swarm manager node IP address completely breaks Swarm forever, this is insane

### ISSUE THREAD

**Issue by doctorpangloss** [moby/moby#41043] opened 2020-05-29 01:39 UTC
This would be the single most urgent Swarm issue. There must be 14 issues related to this. So many people ticket it.

**Comment by thaJeztah** [comment] 2020-06-02 12:55
Please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'll close this ticket because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-02 12:55 UTC
Labels: area/swarm, status/more-info-needed

**Comment by doctorpangloss** [comment] 2020-06-28 14:37
Related issues: https://github.com/docker/machine/issues/806 https://github.com/docker/for-linux/issues/523 https://github.com/moby/moby/issues/34306 https://github.com/docker/swarmkit/issues/642 https://github.com/docker/swarmkit/pull/2199 https://github.com/moby/moby/issues/34635

For people finding this issue via keywords on Google hopefully:

 - You use any version of Docker since Swarm was introduced as a built-in feature of the CLI. (i.e. you have a `docker swarm` command).
 - You try to change the IP address of any manager node.
 - You will observe your swarm will not work reliably anymore, with various networking issues between workers and nodes; additionally
 - You will not be able to add a new manager and your swarm will be permanently unexpandable to more managers if you change the IP address of a single-manager swarm.

The issue has been around since at least 2017, and possibly since the day Swarm has been introduced. In my opinion, with Swarm being abandoned and the related issues not being addressed, you should probably not use Swarm anymore and migrate to Kubernetes.

**Comment by doctorpangloss** [comment] 2020-06-28 14:41
@thaJeztah I was just surfacing the urgency of these older issues, despite being years old. It's definitely not a matter of "the bug is so old, it must not be that important" - it's something people reference when they say Swarm is abandoned and that it is not reliable. As a result of the bug since I last filed it, I had to recreate my swarm this morning, seeing no other alternative.
