### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by UttamChavan** [moby/moby#36080] opened 2018-01-21 06:43 UTC
Hi Team,
When i am running below command i am getting below issue please help me out .

```
docker run -d -p 5000:5000 -v /home/user/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/dockerrepo.crt -e REGISTRY_ HT
TP_TLS_KEY=/certs/dockerrepo.key -v /home/user/auth:/auth -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" -e REGISTRY_AUTH_HTP
ASSWD_PATH=/auth/htpasswd  registry:2
docker: invalid reference format: repository name must be lowercase
```

Thanks,
Uttam Chavan

**Comment by Mike-Dunton** [comment] 2018-01-26 16:57
Do you have an extra space ?
```
-e REGISTRY_AUTH_HTP
ASSWD_PATH=/auth/htpasswd
```

**Comment by SamuelKnoch** [comment] 2018-02-26 15:04
Try to add double quotes
`-e "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/dockerrepo.crt"`

**Comment by thaJeztah** [comment] 2018-02-26 15:14
Looks like there's a space in the name of one or more of your environment variables:

```
REGISTRY_ HTTP_TLS_KEY=/certs/dockerrepo.key
```

(there's a space after `REGISTRY_`)

In any case, I don't think there's a bug at hand here; this looks like a typo somewhere in the command you're running.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-02-26 15:14 UTC
Labels: kind/question

**Comment by amitthanki** [comment] 2020-03-04 12:50
version: '2.2'

services:
  api:
    image: person13:tag
    build:
      context: .
      dockerfile: Services/Person.api/Dockerfile
    ports:
      - "5100:80"
    networks:
      - apiServices


  gateway:
    image: gateway13:tag
    build:
      context: .
      dockerfile: APIGateway/mobile.gateway/Dockerfile
    ports:
      - "5101:80"
    networks:
      - gatewayServices

networks:
  apiServices:
  gatewayServices:  
    driver: nat 
   
Error:-
ERROR: no such image: api/Person1: invalid reference format: repository name must be lowercase

I don't have api/Person1 image in my system..

Please help...
