### ISSUE TITLE
service update wouldn't update image reference

### ISSUE THREAD

**Issue by achempion** [moby/moby#40862] opened 2020-04-27 18:55 UTC
The command `docker service update --image name:tag` will ask registry if tag reference updated and update the running service with a new reference in case of a change.

The issue here is that local image tag reference wouldn't update.
 
References for image tag and image running with the same tag in docker swarm wouldn't match.

Here is an example:
```sh
# check the current tag reference
$ docker inspect registry.example.com/website:latest | jq .[0].RepoDigests[0]
"registry.example.com/website@sha256:70913f70267ccd8181d9e980e944e88dbcd8d59dab22b3e3452e7a93c7d7dd5d"

# inspect running container reference
$ docker service inspect production_website | jq .[0].Spec.TaskTemplate.ContainerSpec.Image
"registry.example.com/website:latest@sha256:70913f70267ccd8181d9e980e944e88dbcd8d59dab22b3e3452e7a93c7d7dd5d"

# perform the update
$ docker service update --image registry.example.com/website:latest --with-registry-auth production_website

# check the current reference again, nothing changed
$ docker inspect registry.example.com/website:latest | jq .[0].RepoDigests[0]
"registry.example.com/website@sha256:70913f70267ccd8181d9e980e944e88dbcd8d59dab22b3e3452e7a93c7d7dd5d"

# running container reference had updated
docker service inspect production_website | jq .[0].Spec.TaskTemplate.ContainerSpec.Image
"registry.example.com/website:latest@sha256:e832383b6a9ccd93f786ed8cfb27fb561a1b19b74e09b0abc390dc1cf6ec0d1b"
```

**Comment by thaJeztah** [comment] 2020-04-29 09:02
Yes, this is expected; when deploying the service, docker resolves the digest for `name:tag`, and then deploys the service using that digest (`name@sha256:aabbccdd`). When running (or pulling) an image by digest, no local tag is created for that pulled image. If no local image exists with a tag that matches that digest, the image will be listed with tag `<none>`; for example;

```
docker pull busybox@sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12

docker images --digests

REPOSITORY                      TAG                    DIGEST                                                                    IMAGE ID            CREATED             SIZE
busybox                         <none>                 sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12   be5888e67be6        2 weeks ago         1.22MB
```

If, on the other hand, I would have a local image that matches that digest, that tag is shown in the output;

```
docker pull busybox:latest

latest: Pulling from library/busybox
Digest: sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest

docker images --digests

REPOSITORY                      TAG                    DIGEST                                                                    IMAGE ID            CREATED             SIZE
busybox                         latest                 sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12   be5888e67be6        2 weeks ago         1.22MB
```


While it would _technically_ be possible to also tag that image, there's some reasons why it's not done (some of them mentioned in https://github.com/moby/moby/issues/28908).


I'll close this issue, because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-04-29 09:02 UTC
Labels: area/images, area/swarm
