### ISSUE TITLE
Retry loop when pulling a container image

### ISSUE THREAD

**Issue by HarshaSuranjith** [moby/moby#38150] opened 2018-11-07 09:31 UTC
**Description**

After installing, attempted to run hello-world container.

It identifies the container image and starts pulling the image. But abruptly terminates and retries the download and terminates again. This behavior is repeated in a loop.

Similar behaviour is observed when attempting to run other containers as well.

**Steps to reproduce the issue:**
1. Install docker for Windows on [ Windows 10 Enterprise Version 1803 (OS Build 17134.285) ]
2. then ``` docker run hello-world```

**Describe the results you received:**

```
PS C:\Users\harshaa> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
e46172273a4e: Retrying in 2 seconds
1f7d468f830c: Retrying in 2 seconds
35655e48c5c5: Download complete
8159aad5f944: Download complete 
```
Small layers complete download, But when layer size is larger download starts and terminates around 4 MB and this retry attempt repeats. 

**Describe the results you expected:**
Pull and run hello world container

**Additional information you deem important (e.g. issue happens only occasionally):**
Fresh installation on windows 10

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:36:40 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise Version 1803 (OS Build 17134.285)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88GiB
Name: HarshaA
ID: NNTE:NFCV:52EO:3LOM:OCP6:737J:TVVS:Y6UB:WQM5:63LW:FFZ7:SS5V
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2018-11-07T14:55:12.1776111+05:30
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by HarshaSuranjith** [comment] 2018-11-14 09:48
@GordonTheTurtle any update ??

**Comment by thaJeztah** [comment] 2018-11-14 10:21
Could be a networking issue in your environment; do the daemon logs show anything useful?

**Comment by andradf** [comment] 2019-05-14 15:25
Still experiencing this issue. Is there a fix or a known workaround?

**Comment by olljanat** [comment] 2019-05-14 20:24
@andradf we need more details to be able to understand issue. Can you share full info of your setup (questions which you can see if you start creating new issue)?

I just tested on both Linux and Win Srv 2019 with Docker 18.09 where `docker run hello-world` looks working correctly.

**Comment by thaJeztah** [comment] 2019-05-22 18:17
I suspect this is something in the environment where docker is running, not a bug. Given that we don't have a way to reproduce this, I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2019-05-22 18:17 UTC
Labels: platform/desktop
