### ISSUE TITLE
inotify does not work when mounting volumes to docker daemons running in virtual machines

### ISSUE THREAD

**Issue by retrohacker** [moby/moby#18246] opened 2015-11-25 21:19 UTC
### Description of problem:

Many tools used for local development include restart scripts which watch the file system and restart the app when a change occurs. Virtual machines do not propagate filesystem events from mounted volumes, preventing containers with mounted volumes running in virtual machines from seeing these events (read, boot2docker via docker-machine).

Many of us use Docker as a tool for rapidly iterating on code, using [restart scripts](https://github.com/wblankenship/ground-control/blob/master/dockerfiles/graph.sh) watching mounted volumes. But this workflow breaks down when sharing our tooling with team members who run OSx or Windows (since they are relying on virtual machines).

While this is a shortcoming with Virtualbox and similar virtualization tools, the maintainers have stated they will not be implementing fs events on mounted volumes. For more background, refer to the `Additional Info` section below.

Since it appears that the virtual machines will not be supporting this anytime soon, would it be worth solving this at the docker level?
### Proposed Solution

A popular current solution is to rsync the contents of the volume on loop to the virtualmachine and mount the volume from there, avoiding the shared volume all together. This is essentially polling and is expensive.

I propose that the docker tooling take on this responsibility. When running `docker run` with a mounted volume on a remote docker daemon do the following:
1. sync the contents of the volume to the remote daemon
2. Mount the remote directory to the container.
3. Establish a recursive `inotify`/`kqueue`/`ReadDirectoryChangesW` on the local directory.
4. When a change to the directory is detected, re-run sync.

This avoids the need of shared volumes for the virtual machine, allowing for the use of filesystem watches within containers
### Downsides to the proposed solution
1. Requires a daemon like process to establish and maintain `inotify` events during the lifetime of the remote container.
2. Potentially expensive operation when syncing large files.
3. May fill remove VM's hard disk with synced files.
4. Need to implement a form of garbage collection for remote directories when the container is removed.
### docker version`

```
Docker version 1.9.0 build 76d6bc9
```
### docker-machine -v

```
docker-machine version 0.5.0 (04cfa58)
```
### docker info

```
Containers: 0
Images: 4457
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4712
 Dirperm1 Supported: true
Execution Driver: native-0.2
aLogging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 31.37 GiB
Name: BigBlu
ID: ABYD:SSMM:VFCM:VX2N:ZJA3:IDFP:6UA2:67XD:5J5J:IDSX:UXYB:63PW
Username: wblankenship
Registry: https://index.docker.io/v1/
```
### uname -a

```
Linux BigBlu 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
```
### Environment details (AWS, VirtualBox, physical, etc.):

vboxmanage --version

```
4.3.18_Debianr96516
```
### How reproducible:

100%
### Steps to Reproduce:
1. `docker machine create -d virtualbox inotify`
2. `eval "$(docker machine env inotify)"`
3. `touch test`
4. docker run -v ${PWD}/test:/usr/src/test -it debian:jessie bash -c "apt-get update && apt-get install -y inotify-tools && inotifywait /usr/src/test"
5. Finally, open another terminal and `touch test`
### Actual Results:

Script doesn't exit
### Expected Results:

`inotifywait` should have returned `test OPEN` and the script exited.
### Additional Info:

Closed tickets on the Virtualbox bug tracker referring to this short coming:
- https://www.virtualbox.org/ticket/10660
- https://www.virtualbox.org/ticket/14234

This may be a duplicate issue, I searched around across the docker, swarm, and machine repos and found nothing. Here are similar issues that I found:
- https://www.virtualbox.org/ticket/14234
- https://github.com/docker/docker/issues/4023
- https://github.com/docker/docker/issues/1044
- https://github.com/docker/docker/issues/4213
- https://github.com/docker/machine/issues/179

This seems to be the state of the art solution currently, from @brikis98 et. al.:

https://github.com/brikis98/docker-osx-dev

**Comment by thaJeztah** [comment] 2015-11-25 21:38
I wonder if using a [volume-driver/plugin](https://docs.docker.com/engine/extend/plugins/) in stead of making this part of the core functionality would be a solution. I.e. in stead of bind-mounting the local directory, create a volume first (`docker volume create`), with a suitable plugin and use that (e.g. https://github.com/gondor/docker-volume-netshare).

I fully realize this is a big PITA for development use of docker, just thinking if there's a solution that would work for dev on VirtualBox, but doesn't overload the core functionality of docker for all other uses.

**Comment by cpuguy83** [comment] 2015-11-25 22:19
Also see: https://github.com/cpuguy83/docker-compose-reloader
This uses fs events on the local system and orchestrates the docker API.

I don't think this is the right place for such a feature.

**Comment by wblankenship** [comment] 2015-11-25 23:39
@thaJeztah I like the idea of creating a special volume driver for this and agree that my current proposal is a rather jarring change to the current way volumes work.

@cpuguy83 your script is a great approach, and I have seen some people working towards doing this for their projects. I have some problems with it though:

* Most projects already ship with tools that implement complex restart logic. It isn't practical to re-implement that logic for every project that uses Docker. (gulp, babel, etc)
* Docker specific restart logic separates the restart logic from the codebase, meaning we have to ship 2 scripts: one for users using docker, one for users not using docker.
* A full restart of a container can prevent many of the optimizations these tools use.
* Docker specific restart logic ends up baking too much knowledge of the infrastructure into the restart script. Depending on which files change, different services need to be restarted. This is opposed to each service having a script that handles watching for pertinent changes.

**Comment by blaggacao** [comment] 2015-11-27 04:18
+1 for @thaJeztah idea, I've been waiting for this a long time and also see a good chance in using the volume api. I think `rsync

**Comment by thaJeztah** [comment] 2015-11-27 07:45
@blaggacao I see that plugin is not yet listed in the plugins page, might be worth creating a PR to add it there so that it's easier to find for people; https://github.com/docker/docker/blob/master/docs/extend/plugins.md

**Comment by wblankenship** [comment] 2015-11-27 17:13
@blaggacao that plugin is a great find! It looks like it doesn't maintain a live rsync between the host and the container during runtime though (just once when starting the container and once when stopping the container) but this may be a great jumping off point for this volume.

Perhaps @h0tbird has some thoughts on this as well?

**Comment by blaggacao** [comment] 2015-11-27 22:26
@synack should be in the loop as well, he did this continuous scanning like this: https://github.com/synack/docker-rsync/blob/master/main.go#L67-L71

**Comment by h0tbird** [comment] 2015-11-28 09:31
I think I understand the problem. Are you suggesting I add live rsync to `docker-volume-rsync`? If that is the case, what about something like this:

```
docker volume create \
--driver rsync \
--name   mycode \
--opt    mode=<pull|push> \
--opt    interval=<seconds> \
--opt    user=<username> \
--opt    password=<password> \
--opt    remote-host=<my-workstation> \
--opt    remote-path=<path-to-mycode> \
--opt    push-back=<true|false> \
--opt    pull-back=<true|false> \
--opt    rsync-opts=<rsync-options>
```

```
docker run -d -v mycode:/path/to/code busybox ls /path/to/code
```

**Comment by blaggacao** [comment] 2015-11-28 23:08
That would be a solution indeed, however, without knowing the details, connecting to the os' file system api might be more efficient, than interval checking.  A popular go library is this one: https://github.com/emcrisostomo/fswatch

**Comment by duro** [comment] 2016-02-11 03:56
@h0tbird or @blaggacao Did this ever go anywhere? We are looking for a cross platform way to rsync into a docker host, and have been using https://github.com/synack/docker-rsync up until now. It does not support Windows, and I just joined a team that has developers across OSX, Windows, and Linux.

**Comment by h0tbird** [comment] 2016-02-11 13:25
@duro sorry I don't have time to code it.

**Comment by retrohacker** [comment] 2016-02-11 16:54
@duro I haven't had time to code it yet.

For now, I've been using [nodemon's legacy watcher](https://github.com/remy/nodemon#application-isnt-restarting). It supports non-node applications and it doesn't rely on file system events.

If you go with this solution and you have large directories (like `node_modules` in Node.js) that rarely change, I would recommend adding them to nodemon's exclude list. Checking all of those files for changes is extremely taxing.

**Comment by jeremyVignelles** [comment] 2016-06-28 20:10
Hi,
What is the status of this in the new Docker for Windows?
Since it uses Hyper-V, I don't know how volumes mounting works internally. Is it still a network share?

**Comment by thaJeztah** [comment] 2016-06-28 21:53
@friism ^^

**Comment by blaggacao** [comment] 2016-07-10 01:19
@jeremyVignelles It uses cifs/samba however I've read something somewhere, that they (either MS or Docker) are working on getting some file metadata correct so that inotify etc. works. (inotify and sama do not like each other yet.)

**Comment by jeremyVignelles** [comment] 2016-07-10 07:49
That would be really nice, but I doubt this will be available in the next few month, because of the need to implement this new protocol on both ends...
If you have more information, please let me know.

**Comment by justincormack** [comment] 2016-07-10 09:16
It is on the roadmap but we do not have a timeline yet, we are exploring
the different options for making it work.

**Comment by zx1986** [comment] 2016-07-18 03:45
Does this is solved in Docker for Mac?

**Comment by jeremyVignelles** [comment] 2016-07-18 05:11
@zx1986 : according to the demo of docker for mac that was made at the dockercon 2016, yes, this is solved in docker for mac.

**Comment by parhamdoustdar** [comment] 2016-07-23 14:23
Is there a way other than using ctrl+C in Docker on Windows to get this to work while this is being implemented?

**Comment by dcosson** [comment] 2016-07-29 05:39
Since I don't see it mentioned here yet, unison might be a better tool than rsync for this since it's designed for 2-way syncing. I got this [unison vagrant plugin](https://github.com/dcosson/vagrant-unison2) working a few months ago and it's been solid for our team, syncing a fairly large repo into the vagrant vm that we mount as a docker volume.

It is possible to generate conflicts with either unison or rsync, which probably means exposing some way to resolve them which adds complexity. But with the growing popularity of hot reloading this really seems like a must for docker to support.

**Comment by BretFisher** [comment] 2016-08-10 04:02
In Mac, like @jeremyVignelles says above, this has been solved in `docker run` with Docker for Mac's release, where filesystem events will fire inside and out of container.

**Comment by rjsteinert** [comment] 2016-08-15 21:42
@jeremyVignelles @BretFisher I just installed Docker for Mac and gave it a try. No luck.

**Comment by rjsteinert** [comment] 2016-08-15 22:19
@jeremyVignelles @BretFisher Nvm, it works! But there is chatter on the forum about it not working all the time.

**Comment by BretFisher** [comment] 2016-08-15 22:59
I know it won't work if you've enabled swarm mode and use `docker service create` but I've always seen it work with `docker run`. You've got evidence of it otherwise @rjsteinert ?

**Comment by thaJeztah** [comment] 2016-08-15 23:05
> I know it won't work if you've enabled swarm mode and use `docker service create`

That should not make a difference for bind-mounted directories, as it's using the same API / options to start the containers that are backing the service. However, during development, there's not many reasons to us `docker service create` to spin up a single container for local development

**Comment by BretFisher** [comment] 2016-08-16 02:46
@thaJeztah Here's our bug report, same issue on two Docker Captain's machines plus others: https://github.com/docker/for-mac/issues/148.

I agree swarm mode on Mac is mostly an edge case, but in our use case we're talking to the swarm api to create swarm containers with mounts that need fs-events in/out.

Semi related: your excellent `run` vs `service` epic https://github.com/docker/docker/issues/25303

**Comment by thaJeztah** [comment] 2016-08-16 09:59
@BretFisher thanks for that, I wasn't aware of that bug

**Comment by mrkongo** [comment] 2016-08-21 19:04
Sorry for this little response, maybe this has nothing to do, but I would say it anyway, because maybe the time of creation of files can help:

https://translate.google.com/translate?hl=it&sl=ja&tl=en&u=http%3A%2F%2Fqiita.com%2Fpocari%2Fitems%2F456052a291381895f8b3

**Comment by asolopovas** [comment] 2016-12-06 10:54
Any news about this on Windows?

**Comment by blaggacao** [comment] 2016-12-14 21:53
I'm betting on Windows Subsystem for Linux, currently in beta.

**Comment by tframesqui** [comment] 2017-01-24 10:00
This issue still happening? There is no volume or something we could use to avoid this on windows? I'm facing this sync issue in all my development environments who shares data between windows/continers.

**Comment by friism** [comment] 2017-01-24 14:36
>  There is no volume or something we could use to avoid this on windows?

Sorry, no: https://docs.docker.com/docker-for-windows/troubleshoot/#/inotify-on-shared-drives-does-not-work

What framework are you using? There's probably a polling mode that you can use as a workaround.

**Comment by tframesqui** [comment] 2017-01-24 15:45
My apps are most Python with Django.

**Comment by friism** [comment] 2017-01-24 18:08
@tframesqui and what's supposed to be auto-reloading your app? If you get rid of pyinotify, it looks like it'll poll: https://docs.djangoproject.com/en/1.10/ref/django-admin/#runserver

**Comment by tframesqui** [comment] 2017-01-26 10:18
@friism I was forgetting something very simple... Thank you for the obvious question: "what's supposed to be auto-reloading your app?". While i'm ussing uWsgi, I'd have to put py-autoreload on uwsgi for my development environment. Now it's all working and reloading very quickly.

**Comment by cglewis** [comment] 2017-04-24 22:03
are there any plans to make this work for `docker-machine` using osx client and virtualbox b2d server?

currently this setup (using latest toolbox install on osx **doesn't** work):
```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I can confirm that using the latest Docker for Mac **does** work (version info below), but would like to see both of these install paths work for fs events.

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by friism** [comment] 2017-04-24 23:17
@cglewis we're not currently planning to make it work with Toolbox. Part of the genesis of Docker for Mac was that making stuff like this work in Toolbox was hard.

Is there are reason you need it in Toolbox and `docker-machine`?

**Comment by thaJeztah** [comment] 2017-04-24 23:50
@cglewis inotify not working in VirtualBox is a limitation of VirtualBox guest additions, and was closed as a "won't fix" by the VirtualBox team (see the issues linked from the top description) - as @friism explained, this was one of the reasons for Docker to develop Docker for Mac, which does not have that limitation

**Comment by cglewis** [comment] 2017-04-25 00:25
@thaJeztah I see, that's unfortunate.

@friism yeah, my reason is that I'm creating something that uses docker engines, but doesn't guarantee how they are setup or installed.  so ideally, running a container with the various ways that docker clients/servers can be installed for current versions (toolbox with virtualbox included, since it still has a current release) would behave the same way, but it doesn't.  this makes the end user experience difficult or frustrating if they chose one install path over another.  if I could guarantee all end users only installed say, Docker for Mac, then it wouldn't be a problem.  however, since I can't guarantee that and because there are multiple acceptable installation paths currently that result in the same container at runtime behaving differently, it is a problem.

since this is also a virtualbox issue that they're not going to address, I guess the best I can do is tell end users to not use toolbox.

**Comment by thaJeztah** [comment] 2017-05-02 22:52
I'm going ahead and close this issue;

- for docker for mac, inotify is supported (issue about it not working for _services_ is tracked in https://github.com/docker/for-mac/issues/148)
- for docker for windows, inotify currently isn't supported, but is something that is best reported in the docker for windows issue tracker (https://github.com/docker/for-win/issues)
- for docker toolbox, unfortunately, this cannot be supported, as it depends on VirtualBox implementing it (and is closed as a "won't fix") - which is one of the reasons Docker for Mac was developed.

**Closed by thaJeztah** 2017-05-02 22:52 UTC
Labels: kind/feature

**Comment by nhooey** [comment] 2018-03-13 22:47
It looks like [inotify-proxy](https://github.com/sillypog/inotify-proxy) is a workaround to this problem.

**Comment by nhooey** [comment] 2018-03-13 23:07
@retrohacker Could you mention in the description of this bug that [inotify-proxy](https://github.com/sillypog/inotify-proxy) is a workaround for this problem?
