### ISSUE TITLE
Add support for docker service exec

### ISSUE THREAD

**Issue by s4ke** [moby/moby#45916] opened 2023-07-08 19:48 UTC
### Description

We are big Docker Swarm fans, but something that is hard to grasp for newcomers is that the docker cli does not support a way to execute directly into a task of a service. Currently you have to figure out which node the task is running on and then point your docker cli to that node to exec into the task.

This requires at least SSH access to all nodes which is not ideal and also is not really automated.

In the last few weeks I toyed around with the idea of adding this functionality myself. Here is the hacky way I did it with the current Features of Docker swarm:

1. Determine which node the task is running on
2. Deploy a docker socket proxy (with tecnativa/docker-socket-proxy) service via the manager you are connected to with a shared attachable network into the swarm onto every node of the swarm
3. Run a regular docker container in the current docker context (any manager) attached to a shared network of the docker socket proxy that enumerates all docker socket proxies until it has found the proper node
4. Run a docker exec against that docker socket proxy

Obviously (2) and (3) could be optimized by deploying only a proxy to the actually relevant node, but for a PoC it works out.

You can find the working PoC here: https://github.com/neuroforgede/docker-swarm-proxy

Now I was wondering whether support for this could be added without jumping through these extra hoops as described above to the core project. I definitely think that the approach I took for the PoC can not be replicated into moby/moby as it is indeed a bit hacky, but I think the UX is actually kinda nice.

What do you think?

**Comment by ieugen** [comment] 2023-07-10 00:32
Would love to see this kind of feature in Docker Swarm. 
It will greatly increase the usability of Docker Swarm IMO.

**Comment by thaJeztah** [comment] 2023-07-10 06:09
- looks like this is a duplicate of https://github.com/moby/moby/issues/27552
- and the related ticket in the SwarmKit issue tracker; https://github.com/moby/swarmkit/issues/1895

I'll close this one in favor of https://github.com/moby/moby/issues/27552, to prevent the discussion from diverging, but feel free to participate on that ticket

**Closed by thaJeztah** 2023-07-10 06:09 UTC
Labels: area/cli, status/0-triage, kind/feature, area/swarm, kind/duplicate

**Comment by s4ke** [comment] 2023-07-10 07:36
okay, will move the discussion to the tickets you mentioned.

**Comment by thaJeztah** [comment] 2023-07-10 16:54
Thanks! I may touch-up the other ticket a bit (as the description is a bit poor), but I noticed that it was already linked to in various places, so better to continue using that one 😅
