### ISSUE TITLE
Libsystem-journal0 not found

### ISSUE THREAD

**Issue by jakirpatel** [moby/moby#35743] opened 2017-12-08 08:55 UTC
Docker Version:

 docker version
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

```
Dockerfile: 
```
FROM jenkins/jenkins:lts
EXPOSE 8080 50000
USER root

# Install prerequisites for Docker

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y sudo maven iptables libsystemd-journal0 init-system-helpers libapparmor1 lib$
ENV DOCKER_VERSION=docker-ce_17.03.0~ce-0~ubuntu-trusty_amd64.deb
ENV KUBERNETES_VERSION=v1.8.3

# Set up Docker
RUN wget https://download.docker.com/linux/ubuntu/dists/trusty/pool/stable/amd64/$DOCKER_VERSION
RUN dpkg -i $DOCKER_VERSION

# Set up Kubernetes
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

# Configure access to the Kubernetes Cluster
ADD kubernetes/config ~/.kube
ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]





```

The required package Libsystem-journal0 not found.

**Comment by thaJeztah** [comment] 2017-12-09 11:41
This is not a docker issue; you're attempting to install Ubuntu packages, but the Jenkins image is based on debian stretch;

```bash
$ docker build -t repro-35743 -<<'EOF'
FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y libsystemd-journal0
EOF
```
```
Get:7 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9531 kB]
Fetched 10.1 MB in 18s (554 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libsystemd-journal0
```


Running in an Ubuntu 14.04 image, you'll see that this works;

```bash
$ docker build -t repro-35743 -<<'EOF'
FROM ubuntu:14.04
RUN apt-get update && apt-get install -y libsystemd-journal0
EOF
```

```
The following NEW packages will be installed:
  libsystemd-journal0
...

dpkg-preconfigure: unable to re-open stdin: 
Fetched 50.9 kB in 0s (137 kB/s)
Selecting previously unselected package libsystemd-journal0:amd64.
(Reading database ... 11571 files and directories currently installed.)
Preparing to unpack .../libsystemd-journal0_204-5ubuntu20.25_amd64.deb ...
Unpacking libsystemd-journal0:amd64 (204-5ubuntu20.25) ...
Setting up libsystemd-journal0:amd64 (204-5ubuntu20.25) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
Removing intermediate container 426dd159dd40
 ---> f61709d40c1b
Successfully built f61709d40c1b
Successfully tagged foobar:latest
```

Are you intending to run a Docker daemon inside the image, or do you only need the client? (If you want to run "Docker in Docker", make sure to read this article: http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

If you only need the client; Installing the static binaries is likely an easier solution (because you don't need all the dependencies that the Docker daemon needs); https://docs.docker.com/engine/installation/linux/docker-ce/binaries/. The Docker CLI does API version negotiation, so the latest release of the client can also connect to older versions of Docker

```Dockerfile
FROM jenkins/jenkins:lts
ENV DOCKER_VERSION=17.09.1-ce
USER root
RUN curl -SL -o ./docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz \
 && tar xzvf ./docker.tgz \
 && cp ./docker/docker /usr/local/bin \
 && rm -r ./docker \
 && rm ./docker.tgz
USER jenkins
```

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-09 11:41 UTC
Labels: area/builder, version/1.12
