### ISSUE TITLE
Docker 23.0.0 build fails with some base images

### ISSUE THREAD

**Issue by idkw** [moby/moby#44961] opened 2023-02-08 17:16 UTC
### Description

I just updated to docker 23.0.0 and encountered a weird bug while buiding an image base on `node:18-buster`. 

With some base images a build may fail consistently when running a RUN command after a WORKDIR command. I'm not sure if this is a bug in docker 23.0.0 that may break a lot of builds or if this is only related the `node:18-buster` image.

### Reproduce

I looked into the [image history](https://github.com/docker-library/repo-info/commits/79c6f55fb0e82f555f5dc5550009d4075ce0205c/repos/node/remote/18-buster.md) to make a simple reproducer : 

- Dockerfile with an older base image that doesn't work
```
FROM node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4
WORKDIR /app
RUN pwd
```

```
docker build . --no-cache --progress=plain
```

```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 139B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4
#3 DONE 0.0s

#4 [1/3] FROM docker.io/library/node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4
#4 resolve docker.io/library/node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4 done
#4 DONE 0.0s

#5 [2/3] WORKDIR /app
#5 CACHED

#6 [3/3] RUN pwd
#6 0.227 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
#6 ERROR: process "/bin/sh -c pwd" did not complete successfully: exit code: 1
------
 > [3/3] RUN pwd:
#6 0.227 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
------
Dockerfile:3
--------------------
   1 |     FROM node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4
   2 |     WORKDIR /app
   3 | >>> RUN pwd
--------------------
```

- Dockerfile with a more recent base image that works
```
FROM node@sha256:284743725e464089636cb636009f8050a02e2cfb2f85603c8402cc9135213c87
WORKDIR /app
RUN pwd
```

```
docker build . --no-cache --progress=plain
```

```
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 139B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node@sha256:284743725e464089636cb636009f8050a02e2cfb2f85603c8402cc9135213c87
#3 DONE 0.0s

#4 [1/3] FROM docker.io/library/node@sha256:284743725e464089636cb636009f8050a02e2cfb2f85603c8402cc9135213c87
#4 DONE 0.0s

#5 [2/3] WORKDIR /app
#5 CACHED

#6 [3/3] RUN pwd
#6 0.245 /app
#6 DONE 0.3s

#7 exporting to image
#7 exporting layers done
#7 writing image sha256:f84561a50442e5b436eae6c58b0a5be5aa413df50189f318ecef97b88afe2e42 done
#7 DONE 0.0s

```

- Finally what is even crazier is the first base image that breaks can be "repaired" by adding a random `RUN` instruction before the `WORKDIR` instruction.
```
FROM node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4
RUN echo "WTF"
WORKDIR /app
RUN pwd
```

```
docker build . --no-cache --progress=plain
```

```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 154B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4
#3 DONE 0.0s

#4 [1/4] FROM docker.io/library/node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4
#4 resolve docker.io/library/node@sha256:1f0a8fd387451630d24724c967c83e1653fc3c97265ed05580e589fbe02058d4 done
#4 CACHED

#5 [2/4] RUN echo "WTF"
#5 0.242 WTF
#5 DONE 0.2s

#6 [3/4] WORKDIR /app
#6 DONE 0.0s

#7 [4/4] RUN pwd
#7 4.835 /app
#7 DONE 4.9s

#8 exporting to image
#8 exporting layers 0.0s done
#8 writing image sha256:6d77ace62998e2ba92ae3718ad4fcdbb4fa4145451438b606455116fc3654a53 done
#8 DONE 0.0s
```

### Expected behavior

The build should not break like this.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:47:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:47:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-58-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.36GiB
 Name: valentin-XPS-13-9305
 ID: A4LU:CBWK:2HNK:KPRL:BMAQ:RMW3:HGO2:UMPL:IXHV:C2XS:D75E:N5K3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2023-02-08 17:22
Thanks for reporting; this looks to be a duplicate of https://github.com/moby/moby/issues/44943 (and other issues linked to/from that ticket).

Let me close this one in favour or https://github.com/moby/moby/issues/44943

**Closed by thaJeztah** 2023-02-08 17:22 UTC
Labels: area/builder, status/0-triage, kind/bug, area/builder/buildkit, version/23.0
