### ISSUE TITLE
[client-go] data race during APIVersionNegotiation

### ISSUE THREAD

**Issue by gtomitsuka** [moby/moby#47947] opened 2024-06-11 11:01 UTC
### Description

A service I own at my company programmatically manages a pool of sandbox workers using the Docker Client for Go. Upgrading the Docker Client for Go to v26.x (specifically, the latest – v26.1.4) has made our tests (with `-race`) fail due to a data race. I'm not sure if this function was ever meant to be thread-safe, but I wanted to share this FYI, in case it's not expected behaviour.

In practice, it still works since the writes made by both calls to `negotiateAPIVersionPing()` are identical. Explicitly calling `cli.NegotiateAPIVersion(context.Background())` before the first potential critical zone seems to fix it, but it'd be good to document if the function is generally considered not to be thread-safe.

```
WARNING: DATA RACE
Write at 0x00c000156d9a by goroutine 12:
  github.com/docker/docker/client.(*Client).negotiateAPIVersionPing()
      /go/pkg/mod/github.com/docker/docker@v26.1.4+incompatible/client/client.go:364 +0x194
  github.com/docker/docker/client.(*Client).checkVersion()
      /go/pkg/mod/github.com/docker/docker@v26.1.4+incompatible/client/client.go:274 +0x18d
  github.com/docker/docker/client.(*Client).ContainerCreate()
      /go/pkg/mod/github.com/docker/docker@v26.1.4+incompatible/client/container_create.go:31 +0x108
  github.com/textqllabs/compute-engine/pkg/orchestrator.(*DockerOrchestrator).launchWorker()
      /usr/src/app/pkg/orchestrator/docker.go:88 +0x7e4
  github.com/textqllabs/compute-engine/compute/pkg/orchestrator.(*DockerOrchestrator).LaunchWorkers.func1()
      /usr/src/app/pkg/orchestrator/docker.go:52 +0x11e

Previous read at 0x00c000156d9a by goroutine 10:
  github.com/docker/docker/client.(*Client).checkVersion()
      /go/pkg/mod/github.com/docker/docker@v26.1.4+incompatible/client/client.go:269 +0x91
  github.com/docker/docker/client.(*Client).NewVersionError()
      /go/pkg/mod/github.com/docker/docker@v26.1.4+incompatible/client/errors.go:70 +0x7b
  github.com/docker/docker/client.(*Client).ContainerCreate()
      /go/pkg/mod/github.com/docker/docker@v26.1.4+incompatible/client/container_create.go:35 +0x147
  github.com/textqllabs/compute-engine/pkg/orchestrator.(*DockerOrchestrator).launchWorker()
      /usr/src/app/pkg/orchestrator/docker.go:88 +0x7e4
  github.com/textqllabs/compute-engine/pkg/orchestrator.(*DockerOrchestrator).LaunchWorkers.func1()
      /usr/src/app/pkg/orchestrator/docker.go:52 +0x11e
```

### Reproduce

Minimal working example, test with `go run -race main.go`:
```go
package main

import (
  "context"
  "github.com/docker/docker/api/types/container"
  "github.com/docker/docker/client"
  "sync"
)

func main() {
  var wg sync.WaitGroup
  
  ctx := context.Background()
  cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
  if err != nil {
    panic(err)
  }
  
  for range 2 {
    wg.Add(1)
    go func() {
      defer wg.Done()
      _, err := cli.ContainerCreate(
        ctx,
        &container.Config{
	        Image: "hello-world",
	        Labels: map[string]string{
		        "key": "value",
	        },
        },
        &container.HostConfig{
	        RestartPolicy: container.RestartPolicy{Name: "no"},
      }, nil, nil, "")
      
      if err != nil {
      panic(err)
      }
    }()
  }
  
  wg.Wait()
  println("success")
}
```

### Expected behavior

APIVersionNegotiation should only be attempted once, with a Lock preventing concurrent negotiation attempts.

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:18:14 2024
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:18:14 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-1022-gcp
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 31.28GiB
 Name: dev-env
 ID: 967a3920-b7f9-4514-854c-235cf402b777
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Reproduced on multiple Arm/x86-based Ubuntu 22.04 systems, as well as macOS Sonoma 14.5.

**Comment by gtomitsuka** [comment] 2024-06-11 11:05
I'm happy to implement a solution, if this is indeed not expected behavior.

**Comment by vvoland** [comment] 2024-06-11 12:08
IIRC, there was an attempt to solve it with: https://github.com/moby/moby/pull/43738
But I think that PR fell out of our radar due to large blast area.

cc @corhere  @thaJeztah

**Comment by corhere** [comment] 2024-06-11 21:30
- duplicate of #43729

**Closed by corhere** 2024-06-11 21:30 UTC
Labels: status/0-triage, kind/bug
