### ISSUE TITLE
Facing issues while installing docker in RHEL7

### ISSUE THREAD

**Issue by Manigunner** [moby/moby#34994] opened 2017-09-27 09:46 UTC
RHEL7.x Version

1. Running the wget and curl get.docker.com commands in RHEL7 : wget -qO- https://get.docker.com , curl -ssl https://get.docker.com | sh
2.
3.

**Describe the results you received:**
Seeing the logs as " Executing docker install script commit:716f7ca
Either your platform is not easily detectable  or its not supported by the installer script, Please visit the following url for more information  : https://docs.docker.com/engine/installation

**Describe the results you expected:**
Docker installation should be completed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):  RHEL7.x Version OS installed under my Oracle Virtualbox 5.2.4

**Comment by thaJeztah** [comment] 2017-09-27 11:30
If you follow the link in that error message, you can read that RHEL 7 packages are only available for Docker EE (see the supported platforms for Docker CE and Docker EE here: https://docs.docker.com/engine/installation/#server)

Either get a Docker EE (Enterprise Edition) package from [https://store.docker.com](https://store.docker.com/search?offering=enterprise&operating_system=linux&platform=server&q=&type=edition), or (unsupported), try manually installing the CentOS package following the instructions here: https://docs.docker.com/engine/installation/linux/docker-ce/centos/

Closing this issue, because this is not a bug, but feel free to comment

**Closed by thaJeztah** 2017-09-27 11:30 UTC
