### ISSUE TITLE
No such network: "gwaas-qa" module=node/agent node.id=1701sbvw4vbkql5h804xfpoxu

### ISSUE THREAD

**Issue by swaroopkundeti** [moby/moby#35466] opened 2017-11-10 21:58 UTC
**Description**

**Steps to reproduce the issue:**
1. I don't know but Create 2 machines initiate swarm mode
2. add constraints to worker and add network
3. write compose file to deploy nginx on the created network

**Describe the results you received:**
<pre>
Nov 10 21:49:08 lspqproxl dockerd[13037]: time="2017-11-10T21:49:08.346846884Z" level=error msg="network gwaas-qa remove failed: No such network: gwaas-qa" module=node/agent node.id=1701sbvw4vbkql5h804xfpoxu
Nov 10 21:49:08 lspqproxl dockerd[13037]: time="2017-11-10T21:49:08.347482073Z" level=error msg="remove task failed" error="No such network: gwaas-qa" module=node/agent node.id=1701sbvw4vbkql5h804xfpoxu task.id=voi94iy6f95kw163dipvu3hos
Nov 10 21:49:11 lspqproxl dockerd[13037]: time="2017-11-10T21:49:11.345824154Z" level=warning msg="failed to deactivate service binding for container gwaas_qa_proxy.1.l0whdmd9oxzl2jw5jroanpwnp" error="No such container: gwaas_qa_proxy.1.l0whdmd9oxzl2jw5jroanpwnp" module=node/agent node.id=1701sbvw4vbkql5h804xfpoxu
Nov 10 21:49:11 lspqproxl dockerd[13037]: time="2017-11-10T21:49:11.854793910Z" level=error msg="fatal task error" error="Unable to complete atomic operation, key modified" module=node/agent/taskmanager node.id=1701sbvw4vbkql5h804xfpoxu service.id=at9fq2urwx4qwjhp9u38pujyl task.id=g5ykp7s0aukh0h2aontpyk2em
Nov 10 21:49:11 lspqproxl dockerd[13037]: time="2017-11-10T21:49:11.855997690Z" level=warning msg="Peer operation failed:Unable to find the peerDB for nid:6ba1oy1prmsu6jymw6pveun1o op:&{3 6ba1oy1prmsu6jymw6pveun1o  [] [] [] [] false false false DeleteNetwork}"</pre>

**Describe the results you expected:**
Should spin up a service 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
++++++++++++ Docker version on worker node ++++++++++++
# docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

++++++++++++ Docker version on Manager node +++++++++++
 docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
++++++++++ Docker info of worker node +++++++++++++
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.10.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 1701sbvw4vbkql5h804xfpoxu
 Is Manager: false
 Node Address: 172.23.65.250
 Manager Addresses:
  172.30.xxx.xx:2377
  172.30.xxx.xx:2377
  172.30.xxx.xx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: lspqproxlgwas01.nmrxprod.ad.numerex.com
ID: 2H5U:6O6L:OOBC:H5HD:4AHV:HVS5:OMCR:TUYH:NJAD:ZEGQ:EARG:J5NE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
++++++++++++ Docker info on manager node ++++++++++++++
docker info
Containers: 26
 Running: 0
 Paused: 0
 Stopped: 26
Images: 108
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 240
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ssvee3566wilbjqvfh0uyswoy
 Is Manager: true
 ClusterID: tdj3sjgq15goflsvjtm9zsz0p
 Managers: 3
 Nodes: 17
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.30.xxx.xx
 Manager Addresses:
  172.30.xxx.xx:2377
  172.30.xxx.xx:2377
  172.30.xxx.xx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953GiB
Name: lspibdsldco01.nmrxprod.ad.numerex.com
ID: 626B:SOMQ:GA64:QZXR:WVKA:WK2B:AMBW:N6UK:PIVS:NW6R:YUAC:UWCJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
** Aditional info **
<pre>
docker service ps gwaas_qa_proxy
ID                  NAME                   IMAGE                                                  NODE                                      DESIRED STATE       CURRENT STATE                     ERROR                              PORTS
hsqlj2um59lc        gwaas_qa_proxy.1       registry.nmrxprod.ad.numerex.com/gwaas/proxy-prod:qa   lspqproxlgwas01.nmrxprod.ad.numerex.com   Ready               Rejected less than a second ago   "Unable to complete atomic ope…"
rmqufg2gq89b         \_ gwaas_qa_proxy.1   registry.nmrxprod.ad.numerex.com/gwaas/proxy-prod:qa   lspqproxlgwas01.nmrxprod.ad.numerex.com   Shutdown            Rejected 4 seconds ago            "Unable to complete atomic ope…"
g1ckdrfdfj8q         \_ gwaas_qa_proxy.1   registry.nmrxprod.ad.numerex.com/gwaas/proxy-prod:qa   lspqproxlgwas01.nmrxprod.ad.numerex.com   Shutdown            Rejected 9 seconds ago            "Unable to complete atomic ope…"
nk992cd6j2o4         \_ gwaas_qa_proxy.1   registry.nmrxprod.ad.numerex.com/gwaas/proxy-prod:qa   lspqproxlgwas01.nmrxprod.ad.numerex.com   Shutdown            Rejected 14 seconds ago           "Unable to complete atomic ope…"
re0nx9zsbm55         \_ gwaas_qa_proxy.1   registry.nmrxprod.ad.numerex.com/gwaas/proxy-prod:qa   lspqproxlgwas01.nmrxprod.ad.numerex.com   Shutdown            Rejected 20 seconds ago           "Unable to complete atomic ope…"
</pre>

** Docker network inspect **
<pre>
docker network inspect gwaas-qa
[
    {
        "Name": "gwaas-qa",
        "Id": "6ba1oy1prmsu6jymw6pveun1o",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.1.0/25",
                    "Gateway": "192.168.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4114"
        },
        "Labels": null
    }
]
</pre>

**Comment by thaJeztah** [comment] 2017-11-11 00:34
Thanks for reporting; this looks to be a duplicate of https://github.com/moby/moby/issues/35310, so let me close this one to prevent the conversation from diverging (but feel free to comment after I closed 👍 )

**Closed by thaJeztah** 2017-11-11 00:34 UTC
Labels: area/networking, area/swarm, version/17.10

**Comment by ushuz** [comment] 2019-05-09 10:00
Still seeing this on 18.06.2
