### ISSUE TITLE
docker hang when i do like this

### ISSUE THREAD

**Issue by liaolinrong** [moby/moby#30091] opened 2017-01-12 09:40 UTC
when i do like this:
1. docker-compose up some containers

2.docker exec -it container_name bash
  in the container , i run a shell script backstage:
 ./myscript.sh &

  this script is:

#!/bin/bash
while :
do
  date >> /var/log/memliao.log
  free -m >> /var/log/memliao.log
  sleep 1
done

then i want to exit the container, type "exit", then Docker is hang. When I new a terminal and type "docker ps -a", the Docker is still hang.

**Comment by thaJeztah** [comment] 2017-01-12 13:50
This looks like a duplicate of https://github.com/docker/docker/issues/29700, especially https://github.com/docker/docker/issues/29700#issuecomment-271010181

> When I new a terminal and type "docker ps -a", the Docker is still hang.

Could you explain the "hang"? I'm not able to reproduce that, I can see the container running in the other shell (which is expected, typing `exit` from a `docker exec` session should not stop the container's main process, so the container stays running)

**Comment by liaolinrong** [comment] 2017-01-13 03:25
“hang“ I means I can not type anything in the shell when I type `exit` from a `docker exec` session, and can not `Ctrl + C`, and when I `docker ps -a` in another shell, it shows nothing and I can not type anything in this shell.

**Comment by liaolinrong** [comment] 2017-01-13 05:29
do like this will  reproduce:
1. docker-compose up some containers
2.docker exec -it container_name bash
in the container , i run a shell script backstage:
./myscript.sh &

this script is:

#!/bin/bash
while :
do
date >> /var/log/memliao.log
free -m >> /var/log/memliao.log
sleep 1
done

then i want to exit the container, type "exit",

3. new a shell,and `docker-compose down` in the docker-compose.yml directory, then it will timeout, then type `docker ps -a` will show nothing and can not type in again.

**Comment by liaolinrong** [comment] 2017-01-13 05:35
`systemctl restart docker` will resolve this problem.
My system:  CentOS Linux release 7.2.1511 (Core)
Docker version: Docker version 1.12.0, build 8eab29e

**Comment by liaolinrong** [comment] 2017-01-13 05:36
My kernel version: 
`uname -a
Linux docker71 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux'

**Comment by thaJeztah** [comment] 2020-03-10 08:58
closing; this one went stale

**Closed by thaJeztah** 2020-03-10 08:58 UTC
Labels: area/runtime, status/more-info-needed
