### ISSUE TITLE
Using layerstore and imagestore, outside of docker, for another use case.

### ISSUE THREAD

**Issue by pauldotknopf** [moby/moby#36024] opened 2018-01-15 19:24 UTC
Quick, about my use case: I want to use Dockerfiles to build images that can be booted bare-metal. There will be no concept of containers, or virtualization. I just want the image/layer store, with it's support for tagging and pushing to registries. There will be base Arch/VoidLinux/Gentoo/Ubuntu images that will help prepare the rootfs (squashfs) images to be booted (with tempfs overlay).

I created [a quick app](https://gist.github.com/pauldotknopf/b6e86dbd10cd310b22c59db3c13f197f) that utilizes my own layer/image store, outside of docker. It works as expected. I am hardcoding ```vfs```, but in the end, I'd use the more performant options built into docker.

My question, should I even be doing this? Is there something that I am not considering that would make this solution a no-go? Licensing?

I don't think I need a dameon process to handle the real work, I can probably do everything in the executable the user runs. I don't need long running processes or containers.

Thanks in advance!

**Comment by AkihiroSuda** [comment] 2018-01-16 04:30
You should use containerd: https://github.com/containerd/containerd
The current layer/image store is likely to be deprecated and will be replaced by containerd.

containerd is a daemon but you can also use it as a daemonless library.

You may also want to look into BuildKit: https://github.com/moby/buildkit

**Comment by thaJeztah** [comment] 2018-01-16 14:08
LinuxKit (https://github.com/linuxkit/linuxkit/) may be of interest to you as well.

Please keep in mind that the GitHub issue tracker is not intended as a general discussion forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Moby Project Forums - https://forums.mobyproject.org
- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-01-16 14:08 UTC
Labels: area/builder, kind/question
