### ISSUE TITLE
Forwarding networking information when publishing ports

### ISSUE THREAD

**Issue by mschwager** [moby/moby#28311] opened 2016-11-11 16:15 UTC
Hey!

I'm having some issues with a container handling non-standard published ports. I'm curious if anyone with more Docker (or Linux) experience than I has come up with a more elegant solution. It's a bit complicated to describe, so I'll just get on with it.

I'm running a Docker container with `nginx` inside that connects to a Unix socket for `php-fpm` functionality. **I'm running `nginx` on a high numbered port to avoid running it as root.** I'm also trying to mask this behavior by assigning the standard HTTPS port on the host to the high numbered `nginx` port within the container. The network diagram looks something like:

```
Client -> Host : 443 -> [ Nginx container : 4443 -> PHP-FPM : Unix socket ]
```

Where `[` and `]` denote being inside the container.

The problem is that the PHP logic thinks it's running on `SERVER_PORT` `4443`. So if a redirect were to occur, PHP would attempt to send the client to what it thinks its port is (`4443`). Something like:

* `Client -> GET <host>:443/url`
* `Host -> FORWARD <container:4443>/url`
* `Nginx -> FORWARD <unix-socket>/url while setting SERVER_PORT 4443`
* `PHP-FPM <- REDIRECT <host>:4443/redirect-url`
* `Client -> GET <host>:4443/redirect-url`
* `Host -> ERROR, not listening on 4443`

Now, this may seem like more of an `nginx` issue, but I'm asking here because I'm curious if there is any way to solve this at the Docker networking level. When publishing ports Docker is essentially acting as a proxy, but it lacks -- to my knowledge -- some critical proxying functionality. For example, in this situation one could use the semi-standard `X-Forwarded-Port` header to pass along the requested port, but I can't find any information around this functionality in Docker. I could imagine similar issues with "true" IP addresses and the `X-Real-IP` header.

Now my question, are there any native solutions within Docker for solving these kinds of issues? Also, would this kind of functionality even make sense for Docker, i.e. would you accept a pull request featuring this functionality? Finally, are you aware of **any** good solutions for this, even outside the realm of Docker?

One solution I could envision would involve setting the `SERVER_PORT` within `nginx`. For example, we could just set `fastcgi_param SERVER_PORT 443` if we know the Docker host port being published is `443`. This will have some unfortunate consequences though. The container will now have to be aware of how it's being run. We can no longer map arbitrary ports at container runtime to the internal `4443` port, we're tied to `443` (unless we change the image's `nginx` configuration). This solution will also have issues with upstream proxies. For example, if we have a proxy upstream from the Docker host, we will now also have issues if the proxy is not using `443` as it's port. Consider:

```
Client -> Proxy : 8443 -> Host : 443 -> [ Nginx container : 4443 -> PHP-FPM : Unix socket ]
```

In the presented solution we will now be unable to redirect since we've hardcoded the `SERVER_PORT` to `443`. We can skirt this issue by respecting the `X-Forwarded-Port` header and requiring it be sent if any upstream proxy is using a non-standard port. The `nginx` mapping would be something like the following:

```
map $http_x_forwarded_port $docker_host_port {
    default $http_x_forwarded_port;
    '' 443;
}
...
fastcgi_param SERVER_PORT $docker_host_port;
```

So there are potential alternative solutions, but they may not be as clean as a solution at the Docker networking layer.

Let me know what you think, or if you have any questions!

**Comment by thaJeztah** [comment] 2019-12-30 15:19
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-12-30 15:19 UTC
Labels: area/networking, kind/question
