### ISSUE TITLE
Docker.service start error

### ISSUE THREAD

**Issue by AarioAi** [moby/moby#35679] opened 2017-12-02 04:54 UTC
```
   -- Unit docker.service has begun starting up.
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23.396022007+08:00" level=info msg="libcontainerd: starte
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="starting containerd" module=con
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="changing OOM score to -500" mod
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.c
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.s
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=warning msg="failed to load plugin io.con
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.s
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.m
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=warning msg="could not use snapshotter bt
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.d
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.m
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.r
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="loading plugin "io.containerd.g
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg=serving... address="/var/run/doc
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg=serving... address="/var/run/doc
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: time="2017-12-02T12:30:23+08:00" level=info msg="containerd successfully booted
    Dec 02 12:30:23 VM_0_15_centos dockerd[11830]: Error starting daemon: error initializing graphdriver: /var/lib/docker contains
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: Failed to start Docker Application Container Engine.
    -- Subject: Unit docker.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    --
    -- Unit docker.service has failed.
    --
    -- The result is failed.
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: Unit docker.service entered failed state.
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: docker.service failed.
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: docker.service holdoff time over, scheduling restart.
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: start request repeated too quickly for docker.service
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: Failed to start Docker Application Container Engine.
    -- Subject: Unit docker.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    --
    -- Unit docker.service has failed.
    --
    -- The result is failed.
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: Unit docker.service entered failed state.
    Dec 02 12:30:23 VM_0_15_centos systemd[1]: docker.service failed.
```

I cant start docker.service after using `systemctl restart docker.service`.   Before doing this, the docker service works well on my servers.

I tried to add `{ "storage-driver": "devicemapper" }` to the `/etc/docker/daemon.json`. The docker service can be started. But the docker images and the containers are all missing.

```
    sh$ df -h
    [docker]# df -h
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/vda1        50G   18G   30G  38% /
    devtmpfs        1.9G     0  1.9G   0% /dev
    tmpfs           1.9G   24K  1.9G   1% /dev/shm
    tmpfs           1.9G  356K  1.9G   1% /run
    tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
    tmpfs           380M     0  380M   0% /run/user/0
    tmpfs           380M     0  380M   0% /run/user/1000
```

On the other hand, when I remove `{ "storage-driver": "devicemapper" }` from `/etc/docker/daemon.json`. And then I do `mv /var/lib/docker /var/lib/docker_cp`. The docker service can also be started. But all the docker images and containers are missing.

So how to start the docker service with exists images and containers?

```
   sh$ ls /var/lib/docker
    drwx--x--x   15 root root   4096 Dec  2 12:53 .
    drwxr-xr-x.  37 root root   4096 Dec  2 12:50 ..
    drwx------    2 root root   4096 Nov 13 00:50 builder
    drwx--x--x    3 root root   4096 Dec  2 12:12 containerd
    drwx------    8 root root   4096 Dec  2 11:42 containers
    drwx------    4 root root   4096 Dec  2 12:26 devicemapper
    -rw-r--r--    1 root root 187634 Dec  2 12:31 dockerd[11830]: time="2017-12-02T12:30:23.396022007+08:00" level=info msg="libcontainerd: starte
    drwx------    4 root root   4096 Dec  2 12:24 image
    drwxr-x---    3 root root   4096 Nov 13 00:50 network
    drwx------  133 root root  32768 Dec  2 12:53 overlay
    drwx------    4 root root   4096 Dec  2 12:53 plugins
    drwx------    2 root root   4096 Dec  2 12:53 runtimes
    drwx------    2 root root   4096 Nov 13 00:50 swarm
    drwx------    2 root root   4096 Dec  2 12:53 tmp
    drwx------    2 root root   4096 Nov 13 00:50 trust
    drwx------    2 root root   4096 Nov 13 00:50 volumes
```

**Comment by thaJeztah** [comment] 2017-12-02 05:25
Please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-02 05:25 UTC
