### ISSUE TITLE
Wrong systemd docker.service handling

### ISSUE THREAD

**Issue by pvizeli** [moby/moby#41772] opened 2020-12-10 12:27 UTC
**Description**

Based on systemd documentation: https://www.freedesktop.org/software/systemd/man/bootup.html

All applications/services need to boot inside multi-user and after this target is done, all services/applications are up and running. With the latest https://github.com/moby/moby/issues/41297 changes on the service files, it's not anymore possible to do the right way with systemd which leads to a lot of possible errors. Also, all defaults use `multi-user`.

Would also Fix: #41767

Please revert #41297. The issues which try to resolve with that PR comes from wrong systemd usage.

**Steps to reproduce the issue:**
1. Install docker 20.10
2. Try to use it with your service

**Describe the results you received:**

Not working application inside systemd.

**Describe the results you expected:**

Working systemd envoirement.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```

```

**Output of `docker info`:**

```

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian 10 / Baremetal & VM

**Comment by pvizeli** [comment] 2020-12-10 12:39
Also the service file use `WantedBy=multi-user.target` which is correct for an application (please don't change that) but at the same time it will be started after this.

**Comment by pvizeli** [comment] 2020-12-10 13:53
@IsaiahGrace you can fix your local issue with a `docker.service.d` and add this local to your installation. Not all using docker over a wifi and can't wait 6seconds until the network is online.

**Comment by thaJeztah** [comment] 2020-12-10 13:56
Thanks for reporting; let's close this one as duplicate of https://github.com/moby/moby/issues/41767 to not have the conversation diverge too much.

**Closed by thaJeztah** 2020-12-10 13:56 UTC
Labels: area/packaging, area/systemd, version/20.10

**Comment by thaJeztah** [comment] 2020-12-15 10:02
Docker 20.10.1 was released with an updated systemd unit file, and should fix this issue
