### ISSUE TITLE
[Feature Request] Make Moby's container export/import OCI compliant 

### ISSUE THREAD

**Issue by c4milo** [moby/moby#34187] opened 2017-07-19 14:36 UTC
I was surprised to find out I lost all my environment variables when I Docker exported and imported a container. It would be really useful and friendlier with the community to support OCI specs in order to retain the metadata defined in the Dockerfile.

**Comment by AkihiroSuda** [comment] 2017-07-19 14:39
See https://github.com/moby/moby/pull/33355 (though save/load rather than import/export)

**Comment by thaJeztah** [comment] 2017-07-20 06:19
Yes this is a duplicate of https://github.com/moby/moby/issues/25779, so let me close this one :+1:

**Closed by thaJeztah** 2017-07-20 06:19 UTC
Labels: area/builder
