### ISSUE TITLE
docker swarm node  network timeout

### ISSUE THREAD

**Issue by lidane2** [moby/moby#38962] opened 2019-03-28 09:36 UTC
master：10.96.116.241
node1：  10.96.116.241
node2:   10.96.117.2243

docker network create  --driver overlay --subnet=20.11.0.0/16 --gateway=20.11.0.2 --opt com.docker.network.mtu=1200  network1

docker service create --replicas 3 --name nginx \
 --network=network1\
 --with-registry-auth \
nginx:1.12.2

on  node2  docker  cannot curl  node1 docker

 node1：  10.96.116.241
node2:   10.96.117.2243   dot network subset ？

**Comment by thaJeztah** [comment] 2019-03-28 12:05
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2019-03-28 12:05 UTC
Labels: area/networking, area/swarm
