### ISSUE TITLE
ADD archive file with the --chown flag

### ISSUE THREAD

**Issue by nahsh** [moby/moby#35525] opened 2017-11-16 11:54 UTC
**Description**
Trying to ADD a tar.gz file with the new `--chown` flag. The flag was ignored.

**Steps to reproduce the issue:**
1. Write a Docker file with an ADD command of an archive tar.gz file
2. Build the image
3. Run the image with `--entrypoint=/bin/sh`
4. cd to the working directory, and ls -la

**Describe the results you received:**
The tar.gz file was extracted, as expected. But file and directoryies the ownership was wrong

**Describe the results you expected:**
The ownership should changed recursively, according to the `--chown` flag

**Output of `docker version`:**
```
Docker version 17.09.0-ce, build afdb6d4
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 70
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 118
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: VPWK:YWD2:UCME:FA7F:RKXW:WBM6:MMCZ:RCEL:25WG:TBO3:U2L2:MWGV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 31
 System Time: 2017-11-16T11:54:10.072089Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on MacOS 11

**Comment by thaJeztah** [comment] 2017-11-16 12:25
This is currently the expected behaviour; also see my comment here: https://github.com/moby/moby/pull/34263#issuecomment-343963040

The `--chown` option only changes permissions on the file you add. Archives themselves can have permissions set for individual files as well, which are preserved.

Automatically extracting archives only works for _local_ tar archives; is there a reason you're not adding the extracted files instead?

**Comment by nahsh** [comment] 2017-11-16 13:19
Thanks for your response. 

The user is not exits in local, but is created within the image. So the chown should be done within the image, rather than in the build machine.

**Comment by thaJeztah** [comment] 2017-11-16 14:07
On Linux, users don't have to _exist_ (Linux only looks at the numeric `uid` and `gid`, so `chown 123:456 some-file` always works, even if no user matching that uid/gid exists). However, docker by default resets those permissions and adds files as `root:root`.

But; back to my earlier comment: yes, you would still use the `--chown` flag to set the permissions to the desired user/group, but instead of doing

```Dockerfile
ADD --chown 123:456 local-tar.gz /somewhere
```

You would have the `local-tar.gz` extracted / uncompressed on your local filesystem, and add those files;

```Dockerfile
COPY --chown 123:456 /directory-with-extracted-files /target-directory-in-image
```

If those files don't change, the build cache will "skip" building that layer during build.

Building _may_ even be faster, because Docker can skip the "decompression" step; when building a Dockerfile, this is what happens (roughly):

- the docker cli collects all files in the build context, and adds them to a `.tar` archive
- the `.tar` archive is sent to the daemon
- the daemon extracts the `.tar` archive in a temp-directory
- each step in the Dockerfile is executed; a `COPY` or `ADD` copies the specified files from the temp-directory to the container
   - if `--chown` is set; those files are chown'ed to the specified user
   - if it's a local archive, the archive is extracted
- the result is committed to an image layer

While the `.tar` that's created is (by default) not compressed; for local daemons that should not be a bottleneck; sending the files to a local daemon is faster than compressing/decompressing (you _can_ enable `--compress` if you're using a remote daemon, and networking is a bottleneck).

If you add the files directly, the "if it's a local archive, the archive is extracted" step is skipped during build.

**Comment by thaJeztah** [comment] 2017-12-29 21:38
Looking at the original comment, this works as designed, so I'm closing this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2017-12-29 21:38 UTC
Labels: area/builder, kind/enhancement

**Comment by softwareplumber** [comment] 2018-01-11 10:16
It may work as desired, but since the archive file is deleted anyway changing its ownership is pointless, 'as designed' is kind of useless here. Respectfully submit that 100% of users using the --chown flag on an add with an archive will expect it to change the ownership of the generated files rather than the archive file.

**Comment by xyzzy42** [comment] 2018-08-09 19:34
I also got bit by this.  Usually the Docker container that created the archive used the same UID as the container than `ADD`ed the archive later, so no one noticed that --chown on an archive is basically useless.

Must agree with @shoftwareplumber that the as designed behavior isn't sensible here.  Add a directory, and the files in it are chown'ed, add an archive of the directory and the files are not.  Instead there is an invisible chown of a file that is never in the container.  It defeats the transparent decompression of archives.

**Comment by dmhursh** [comment] 2018-08-17 18:12
I also got bit by this.  I'm going to be a bit long winded because I think there is a bigger issue here that's being missed because of many small details.

I have a working Dockerfile that has some bad performance and bad, layer size induced transfer times.  It looks basically like :
``` Dockerfile
FROM base_image
ARG INSTALL_OWNER=installowner

ADD framework.tar.gz ${INSTALL_TREE}
RUN ${INSTALL_TREE}/bin/setupframework

ADD component1.tar.gz ${INSTALL_TREE}
ADD component2.tar.gz ${INSTALL_TREE}
.
.
.
ADD componentN.tar.gz ${INSTALL_TREE}

# Significantly increase runtime and create big layer
RUN chown -R ${INSTALL_OWNER}:${INSTALL_OWNER} ${INSTALL_TREE}

USER ${INSTALL_OWNER}
```
So I try something (that seemed) obvious :
``` Dockerfile
FROM base_image

ARG INSTALL_OWNER=installowner
USER ${INSTALL_OWNER}

ADD framework.tar.gz ${INSTALL_TREE}
RUN ${INSTALL_TREE}/bin/setupframework

ADD component1.tar.gz ${INSTALL_TREE}
ADD component2.tar.gz ${INSTALL_TREE}
.
.
.
ADD componentN.tar.gz ${INSTALL_TREE}
```
After some confusion I found some old github issues that explain this is failing as expected.  The developers agree that `USER` _should_ affect `ADD`, but at this point it would be a breaking change.  
Fortunately I also found there is a newer, different syntax to get the desired affect!
``` Dockerfile
FROM base_image

ARG INSTALL_OWNER=installowner
USER ${INSTALL_OWNER}:${INSTALL_OWNER}

ADD --chown=${INSTALL_OWNER}:${INSTALL_OWNER} framework.tar.gz ${INSTALL_TREE}
RUN ${INSTALL_TREE}/bin/setupframework

ADD --chown=${INSTALL_OWNER}:${INSTALL_OWNER} component1.tar.gz ${INSTALL_TREE}
ADD --chown=${INSTALL_OWNER}:${INSTALL_OWNER} component2.tar.gz ${INSTALL_TREE}
.
.
.
ADD --chown=${INSTALL_OWNER}:${INSTALL_OWNER} componentN.tar.gz ${INSTALL_TREE}
```
After some more confusion I find that `--chown` style arguments don't support variables.  It's desired but not implemented yet.  OK, that's not unreasonable, I'll hardcode for now …
``` Dockerfile
FROM base_image

# Give up for now and hard code it at integration time.
# ARG INSTALL_OWNER=installowner
USER installowner:installowner

ADD --chown=installowner:installowner framework.tar.gz ${INSTALL_TREE}
RUN ${INSTALL_TREE}/bin/setupframework

ADD --chown=installowner:installowner component1.tar.gz ${INSTALL_TREE}
ADD --chown=installowner:installowner component2.tar.gz ${INSTALL_TREE}
.
.
.
ADD --chown=installowner:installowner componentN.tar.gz ${INSTALL_TREE}
```
After more confusion I find that we fail, again by design, because the `--chown` here means to chown a temporary intermediate file that the user never even sees.  This is not documented, but is somehow assumed to be expected?

There is a use case here.  I've seen several other people trying to accomplish the same thing opening github issues.  There is quite a bit of non-intuitive behavior implemented and the answers always claim it's by design without really addressing the use case.

Ignoring my various foolish attempts, is there something I could put in a Dockerfile to get the desired behavior without the time & size overhead imposed by the manual recursive chown in the first example?  

In this case, some of the archives being unpacked are from third parties.  I'd like to not doctor their output.  Upstream cannot be expected to hard code the IDs I need.

Thanks!

**Comment by cbanek** [comment] 2018-11-14 03:35
I just got bit by this as well.  I think it makes sense to use chown to change the permissions of the contents of an archive, because we delete the original one (hence those permissions don't matter).   If people wanted to have custom permissions inside the archive they just wouldn't use chown.

**Comment by JohanMollevik** [comment] 2019-04-17 21:00
Can this be reopened? Or if not this then can another sane method be provided to set permissions of extracted archives. Sadly setting the permissions in the archive itself does not help. If the user only exist in the docker container the extracted archive will be owned by root.

**Comment by ahridin** [comment] 2020-01-27 21:22
I am using as workaround multi stage build: i.e. excracting archive in one phase and then using COPY from the temporary image (with extracted) in the next stage:

...
...
...
#------------------------------------------------------------------------------
# ===> Temporary image with locally extracted TAR (wokaround of limitation - unable "ADD tar with chown"
#------------------------------------------------------------------------------
FROM alpine AS **app_extracted**
ARG workdir="/opt/local/app"
WORKDIR "${workdir}"

ARG app="app/*.tar.gz"
ADD "${app}" "tar/scripts/*.sh" ./  
RUN file=$(find . *.tar.gz -maxdepth 0 -type f); tar -xzhf $file && rm -rf $file

#-----------------------------------------------------------------------------
# ===> multi-stage build  ===> Base product image (w/o configuration)
#-----------------------------------------------------------------------------
FROM base_img AS product_base

ARG workdir="/opt/local/app"
WORKDIR "${workdir}"

**COPY --chown=appuser:app --from=app_extracted ${workdir} ./**


...
....

**Comment by llamafilm** [comment] 2021-02-16 07:07
+1 for this.  I know tar archives can contain specific permissions for each file, but it would be great for this `--chown` flag to override that.  I was thinking about switching from COPY to ADD to reduce image size, but this issue actually makes ADD larger.

  For example:

```
FROM php:7.2-apache
WORKDIR /var/www/html
ADD v7.tar.gz .
RUN chown -R www-data:www-data ./*
```
This image is 501MB

```
FROM php:7.2-apache
WORKDIR /var/www/html/
COPY v7.tar.gz .
RUN tar xzf v7.tar.gz \
    && chown -R www-data:www-data ./* \
    && rm -f v7.tar.gz
```
This image is 467MB.

**Comment by pan3793** [comment] 2024-03-14 12:38
+1. highly suggest re-evaluating this feature request.

**Comment by karlhaworth** [comment] 2024-08-14 16:17
+1 re-evaluate this feature

**Comment by thaJeztah** [comment] 2024-08-14 16:29
I'm locking the conversation on this ticket, because this is a feature to be implemented in BuildKit; there's two tickets (maybe more) related to this in the BuildKit project;


- https://github.com/moby/buildkit/issues/1547
- https://github.com/moby/buildkit/issues/3700
