### ISSUE TITLE
containerd restarts on random docker hosts in a kubernetes cluster with 1000+ nodes

### ISSUE THREAD

**Issue by ligc** [moby/moby#35846] opened 2017-12-20 14:01 UTC
**Description**
We have a kubernetes cluster with 1000+ nodes running docker 1.12.6, everyday there will be several nodes on which the containerd are restarted, the nodes are totally random, we could not predict which one will be the next one. containerd restart is not a big deal, but because of the docker issue with --live-restore(https://github.com/moby/moby/issues/28470, https://github.com/moby/moby/issues/31479), the containerd restarts caused all the containers on the docker host be killed. 

**Steps to reproduce the issue:**

We have not found a way to reproduce this issue yet,  however, we will have several nodes out of the 1000+ nodes on which the containerd gets restarted by unknown reason every day.

**Describe the results you received:**

containerd restarts on random nodes.

**Describe the results you expected:**
containerd should be up and running without restarts.

**Additional information you deem important (e.g. issue happens only occasionally):**

We found a similar issue https://github.com/coreos/bugs/issues/1909, but we are not seeing the golang errors. It seems to me that the containerd in our environment was "killed" by some other process, we suspected the OOM killer, but there is no memory pressure on the nodes.

**Output of `docker version`:**

```
x1:~ # docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Oct 10 01:31:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Oct 10 01:31:43 2017
 OS/Arch:      linux/amd64
x1:~ # 

```

**Output of `docker info`:**

```
x1:~ # docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 21
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v3.16+20140829
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.12.28-4-default
Operating System: SUSE Linux Enterprise Server 12
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.813 GiB
Name: x1
ID: SV2H:OGVA:BZIN:EQCD:GGZU:ANAO:7MEE:UIRN:7NEP:MFH4:UNRX:FXG2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Insecure Registries:
 9.186.91.246
 x1.clusters.com
 x2.clusters.com
 127.0.0.0/8
x1:~ # 

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

When the containerd gets restarted, will get the following messages in /var/log/messages:

```
2017-12-20T21:49:32.545989+08:00 x1 dockerd[11541]: time="2017-12-20T21:49:32.544158764+08:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing"
2017-12-20T21:49:32.586928+08:00 x1 dockerd[11541]: time="2017-12-20T21:49:32.586752800+08:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 12 desc = unknown service types.API"
2017-12-20T21:49:32.587986+08:00 x1 bash[12601]: time="2017-12-20T21:49:32.587847867+08:00" level=error msg="containerd: notify OOM events" error="no init process found"
2017-12-20T21:49:32.588262+08:00 x1 bash[12601]: time="2017-12-20T21:49:32.588042753+08:00" level=error msg="containerd: notify OOM events" error="no init process found"
2017-12-20T21:49:32.588783+08:00 x1 dockerd[11541]: time="2017-12-20T21:49:32.588574552+08:00" level=warning msg="libcontainerd: unknown container 51b3f47e0c32bb190f088f2455649f4be058319192fda6495e8cfd88f3e9c36e"
2017-12-20T21:49:32.589028+08:00 x1 dockerd[11541]: time="2017-12-20T21:49:32.588958959+08:00" level=warning msg="libcontainerd: unknown container 74388f8c1b61a853b16568aa8f58d957273f8bf590c671a322c034eb50614ab3"
2017-12-20T21:49:32.589248+08:00 x1 dockerd[11541]: time="2017-12-20T21:49:32.589060799+08:00" level=warning msg="libcontainerd: unknown container a0810089174982445f8db52f5f8cb777b345f6bd2fa18479154e40a2e42ac749"
2017-12-20T21:49:32.589475+08:00 x1 dockerd[11541]: time="2017-12-20T21:49:32.589194167+08:00" level=warning msg="libcontainerd: unknown container e95b9cc8ddfe2f1f640da5532ce9f0366edf2da708b3a750c9482124b5c8372c"

```

Any suggestion on what the problem might be will be appreciated.

**Comment by thaJeztah** [comment] 2017-12-28 01:03
Docker 1.12 has reached end of life in March, and is no longer maintained; in addition, Docker CE (community edition) does not  support SLES; could it be you installed packages that are maintained by SUSE (if so, I suggest contacting them)

If you want to try if this issue still reproduces on a current version of Docker, it may be worth installing Docker Enterprise Edition (which is supported on SLES)

I'll have to close this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-28 01:03 UTC
Labels: version/1.12
