### ISSUE TITLE
Is there a way could let me only pull image JSON description (include the host-specific)? It's important.

### ISSUE THREAD

**Issue by Hui-Zhi** [moby/moby#23294] opened 2016-06-06 07:01 UTC
### Background:

As far as I know, the image JSON description only can be got by "docker inspect" after a pull request. If there's no image copy on local, there will have no image JSON description file for it (Please correct me if I'm wrong). But the image JSON description carry important information for container running, like the CPU/Memory requirement in the host-specific. In Cloud environment, like Kubernetes, if customers want to create a pod, need to write CPU/Memory or other requirements like volume requirements in the yaml file for the container information, but if there's a way could get image JSON description without download the image file, the scheduler could be aware of the container requirement without write it in yaml file.
### Solution:

Add a new command could let docker could only pull the image JSON description file, then the scheduler could know the container requirement without it's written in the yaml file.

Please let me know there already have a solution for this.

**Comment by runcom** [comment] 2016-06-06 11:23
Duplicate of https://github.com/docker/docker/pull/14258

However I wrote a tool you can read more here https://github.com/docker/docker/issues/17670#issuecomment-223536465 to achieve what you need

**Comment by cpuguy83** [comment] 2016-06-06 15:19
But the image does not carry cpu/memory requirements, this is considered host-specific information.

**Comment by Hui-Zhi** [comment] 2016-06-07 06:42
@cpuguy83 Yes, I think the host-specific information could benefit scheduler if could get it before pull the images, and Kubernetes only pull the images when the containers need to be run. So part of the host-specific information need to write into the pod yaml file.


@runcom Thanks for your reference. But somehow, the tool you recommended doesn't work for me, I'm using RHEL7.2, and cloned the latest code:

but it shows below error:
```
skopeo inspect docker://docker.io/busybox
FATA[0003] Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io: EOF

skopeo inspect docker://docker.io/busybox:latest
FATA[0001] invalid character '<' looking for beginning of value
```

**Comment by runcom** [comment] 2016-06-07 09:52
> @runcom Thanks for your reference. But somehow, the tool you recommended doesn't work for me, I'm using RHEL7.2, and cloned the latest code:

@Hui-Zhi you can install `skopeo` directly with `yum install skopeo` on a rhel7.2 after enabling repo extras

**Comment by Hui-Zhi** [comment] 2016-06-07 10:55
@runcom I really appreciate it, thank you very much! By the way, could this tool get the host specific information? Like the cpu/memory requirement?

**Comment by bsousaa** [comment] 2023-03-21 10:49
these two commands can be used to extract about the image JSON from the registry:
`docker manifest inspect` or `docker buildx imagetools inspect`

About CPU requirements please see https://github.com/moby/moby/issues/23294#issuecomment-223991400

**Closed by bsousaa** 2023-03-21 10:49 UTC
