### ISSUE TITLE
Docker streams full context when content size gt 512m

### ISSUE THREAD

**Issue by avkudryashov** [moby/moby#40372] opened 2020-01-14 07:18 UTC
**Description**
In case context content size is equal or larger than 512mb all data is being streamed instead of changed files only

**Steps to reproduce the issue:**
1. truncate -s 512M content
2. docker build --stream --tag test .  

Dockerfile
```
FROM nginx
ADD content /usr/share/nginx/
```
**Describe the results you received:**
Docker send full context in every build
```
anatoly@hp:~/test1$ truncate -s 512M content
anatoly@hp:~/test1$ docker build --stream --tag test .
Streaming build context to Docker daemon    537MB
Step 1/2 : FROM nginx
 ---> 540a289bab6c
Step 2/2 : ADD content /usr/share/nginx/
 ---> Using cache
 ---> 3575167999ad
Successfully built 3575167999ad
Successfully tagged test:latest
anatoly@hp:~/test1$ docker build --stream --tag test .
Streaming build context to Docker daemon    537MB
Step 1/2 : FROM nginx
 ---> 540a289bab6c
Step 2/2 : ADD content /usr/share/nginx/
 ---> Using cache
 ---> 3575167999ad
Successfully built 3575167999ad
Successfully tagged test:latest
```

**Describe the results you expected:**
Docker send full context only on first build
```
anatoly@hp:~/test1$ truncate -s 511M content
anatoly@hp:~/test1$ docker build --stream --tag test .
Streaming build context to Docker daemon    536MB
Step 1/2 : FROM nginx
 ---> 540a289bab6c
Step 2/2 : ADD content /usr/share/nginx/
 ---> Using cache
 ---> ce23df528d90
Successfully built ce23df528d90
Successfully tagged test:latest
anatoly@hp:~/test1$ docker build --stream --tag test .
Streaming build context to Docker daemon      71B
Step 1/2 : FROM nginx
 ---> 540a289bab6c
Step 2/2 : ADD content /usr/share/nginx/
 ---> Using cache
 ---> ce23df528d90
Successfully built ce23df528d90
Successfully tagged test:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 174
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 8t7p5bay5kxwdorm5rg7xh0r6
  Is Manager: true
  ClusterID: iufuxax69wrn7l8gab2tbjute
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.100.48.116
  Manager Addresses:
   10.100.48.116:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-74-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.56GiB
 Name: hp
 ID: N3LL:V4CM:SZ6O:2SZ6:QWVK:6WF4:ZZL3:ABVG:GZGR:XWFX:5BQI:4Q4C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: avkudryashov
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2020-01-14 16:13
Thanks for reporting, and for the clear reproduction steps.

First of all, note that the `--stream` option was an experimental feature, and will be removed in the next release of docker (see https://github.com/docker/cli/pull/2105).

For current versions of docker, using the next generation builder (buildkit) would be the recommended option, and uses streaming by default. BuildKit is not (yet) enabled by default, but you can enable it on the client side by setting the `DOCKER_BUILDKIT=1` environment variable before running `docker build`, or through the daemon configuration file (setting `{"features":{"buildkit": true}}` (see https://docs.docker.com/engine/reference/commandline/dockerd/)).

I was able to reproduce your issue on the classic (non-buildkit) builder, but tested the same scenario with buildkit, and it looks like this problem does not occur with buildkit enabled;

First build takes 10 seconds, which includes sending the build-context (notice the `=> => transferring context: 536.97MB `):

```bash
DOCKER_BUILDKIT=1 docker build --tag test .
[+] Building 10.6s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                0.1s
 => => transferring dockerfile: 79B                                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/nginx:latest                                                                                                                                                     0.0s
 => [internal] load build context                                                                                                                                                                                   6.1s
 => => transferring context: 536.97MB                                                                                                                                                                               6.1s
 => [1/2] FROM docker.io/library/nginx                                                                                                                                                                              0.0s
 => => resolve docker.io/library/nginx:latest                                                                                                                                                                       0.0s
 => [2/2] ADD content /usr/share/nginx/                                                                                                                                                                             1.4s
 => exporting to image                                                                                                                                                                                              2.9s
 => => exporting layers                                                                                                                                                                                             2.8s
 => => writing image sha256:2b4288f08f0380d843b83b9dd9c66eff86e3e44efe7d0170e40999fc4bb8e5f6                                                                                                                        0.0s
 => => naming to docker.io/library/test                                                                                                                                                                             0.0s
```

Second build completes in 100ms and only the Dockerfile itself is sent (`=> => transferring context: 32B`):

```bash
DOCKER_BUILDKIT=1 docker build --tag test .
[+] Building 0.1s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                0.0s
 => => transferring dockerfile: 31B                                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/nginx:latest                                                                                                                                                     0.0s
 => [internal] load build context                                                                                                                                                                                   0.0s
 => => transferring context: 32B                                                                                                                                                                                    0.0s
 => [1/2] FROM docker.io/library/nginx                                                                                                                                                                              0.0s
 => CACHED [2/2] ADD content /usr/share/nginx/                                                                                                                                                                      0.0s
 => exporting to image                                                                                                                                                                                              0.0s
 => => exporting layers                                                                                                                                                                                             0.0s
 => => writing image sha256:2b4288f08f0380d843b83b9dd9c66eff86e3e44efe7d0170e40999fc4bb8e5f6                                                                                                                        0.0s
 => => naming to docker.io/library/test                                                                                                                                                                             0.0s
```


Given that this problem is in an experimental feature that is replaced by buildkit, I'll close this ticket; I highly recommend giving buildkit a try as it is a complete rewrite of the builder (with many other improvements); thanks again for reporting though, and feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-01-14 16:13 UTC
Labels: area/builder, kind/experimental, version/19.03
