### ISSUE TITLE
container start commands should fail for containers managed by swarm

### ISSUE THREAD

**Issue by ddebroy** [moby/moby#36397] opened 2018-02-24 01:14 UTC
**Description**

If a swarm service is started with `--restart-condition none` and the container corresponding to a task for the service is stopped with `docker container stop` swarm will not spawn up a replacement container for the task. However the container that was stopped can be started using `docker container start`. The start succeeds but swarm does not reconcile it's state. This leads to a somewhat confusing state for users as they expect the `container start` to properly start the container and have swarm pick it up.

**Steps to reproduce the issue:**
1. Start swarm service with `--restart-condition none` 
2. `docker container stop` container corresponding to a task.
3. `docker container start` container from 2. 

**Describe the results you received:**

Step 3 above succeeds in starting the container but it does not really get picked up by swarm (and as a result cannot get it's name reconciled back into libnetwork).

**Describe the results you expected:**

`container start` should have errored out with starting the container managed by swarm as when that container is up it will be in a weird state and not detected by swarm.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:	17.06.2-ee-7-tp3
 API version:	1.30
 Go version:	go1.8.7
 Git commit:	ac2b9ac
 Built:	Mon Feb 12 23:03:09 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.06.2-ee-7-tp3
  API version:	1.30 (minimum version 1.12)
  Go version:	go1.8.7
  Git commit:	ac2b9ac
  Built:	Mon Feb 12 23:04:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Output of `docker info`:**

Containers: 34
 Running: 29
 Paused: 0
 Stopped: 5
Images: 24
Server Version: 17.06.2-ee-7-tp3
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: f8ol3f9rwp95erwnr5ckzmo93
 Is Manager: true
 ClusterID: u5fxvpxd6srllq9b8nf4oj4jz
 Managers: 1
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
  External CAs:
    cfssl: https://172.31.15.50:12381/api/v1/cfssl/sign
 Root Rotation In Progress: false
 Node Address: 172.31.15.50
 Manager Addresses:
  172.31.15.50:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 462c82662200a17ee39e74692f536067a3576a50
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 6.896GiB
Name: DeepDebroy-testkit-42AC30-rhel-0
ID: BB2L:4WL5:DV7R:2YZR:OT4S:II4T:3DOA:ZTLD:BJ5A:LPG3:5KSK:IRSH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 229
 Goroutines: 345
 System Time: 2018-02-23T20:15:21.617367604-05:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-02-24 10:36
This is a duplicate of https://github.com/moby/moby/issues/23704. The TL;DR is to don't mix "container commands" with containers that are managed by a service.

Also related: https://github.com/moby/moby/issues/24393, and https://github.com/moby/moby/pull/24411, which added an `is-task` filter option (which could be used to filter out containers that are part of a service, and should not be manually interacted with).

Closing this one as a duplicate of  https://github.com/moby/moby/issues/23704, but feel free to comment :smile:

**Closed by thaJeztah** 2018-02-24 10:36 UTC
Labels: area/swarm
