### ISSUE TITLE
Partially-built image not created if error occurs during build process

### ISSUE THREAD

**Issue by aldoshkind** [moby/moby#45012] opened 2023-02-16 08:00 UTC
### Description

There are no partially-built image in `image ls` if error occured during build process

### Reproduce

Use dockerfile:
```
FROM ubuntu:18.04
RUN exit -1
```

`docker build -t tmp .`

`docker image ls`

### Expected behavior

I expect to see partially-built image in output of `docker ls`. This is the behaviour of older versions of docker, for example 20.10.12, build e91ed57.

### docker version

```bash
# docker -v
Docker version 23.0.1, build a5ee5b1
```

### docker info

```bash
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 19
  Running: 0
  Paused: 0
  Stopped: 19
 Images: 177
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc io.containerd.runc.v2
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 4.15.0-204-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.4GiB
 Name: dmitry-desktop
 ID: BVFA:RFIJ:V3ZJ:VXPX:7Y75:T7LV:KVKI:RGWU:HLFK:E53Y:W2IW:E3U2
 Docker Root Dir: /docker/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  gitlab.vizorlabs.ru:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

### Additional Info

This feature is very handy for debugging build errors. Maybe it is not documented and thus is undefined behavior? Or maybe I do something wrong?
Please help!

**Comment by sam-thibault** [comment] 2023-02-16 10:57
This is the expected behavior now, and has the advantage of not polluting the local image store.  It does make debugging build issues more difficult.  The classic builder produced these intermediate images whereas BuildKit uses its own build cache.  You can upvote the [roadmap issue](https://github.com/docker/roadmap/issues/97) if you want to see this work prioritized.

Some related items:
- https://github.com/docker/roadmap/issues/97
- https://github.com/moby/moby/issues/40887
- https://github.com/docker/buildx/issues?q=label%3Aarea%2Fdebug+

I will close this ticket for now since this is expected.  Feel free to comment further if you wish.

**Closed by sam-thibault** 2023-02-16 10:57 UTC
Labels: status/0-triage, kind/bug

**Comment by aldoshkind** [comment] 2023-02-16 12:18
@sam-thibault thanks for reply!
Very sad :-/
Am I correct saying that at this moment the only way to get intermediate image is to use `DOCKER_BUILDKIT=0` while building image?
