### ISSUE TITLE
docker  network and iptables

### ISSUE THREAD

**Issue by nik786** [moby/moby#34870] opened 2017-09-16 06:41 UTC
jenkins container is running on port 8080 on remote server which ip is 52.xx.xx.xx
I want to route the traffic outside by which i can access dashboard from local browser

I have tried by below mentioned commands. But no luck
iptables -t nat -A PREROUTING -p tcp -m tcp -i eth0 --dport 80 -j REDIRECT --to-ports 8080
iptables -A FORWARD -i eth0 -m state --state NEW -m tcp -p tcp -d 172.17.0.2 --dport 8080 -j ACCEPT

I wish to get solution by iptables only
any help ??

**Comment by thaJeztah** [comment] 2017-09-16 10:33
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-09-16 10:33 UTC
