### ISSUE TITLE
Terminal width is limited to 80 characters in windows containers

### ISSUE THREAD

**Issue by artisticcheese** [moby/moby#36238] opened 2018-02-07 21:29 UTC
**Description**

When I run following command output is truncated to 80 characters. If I prepend it with any other command though then output is NOT truncated

Truncated
```
PS C:\Users\cloudadmin\Documents> docker run microsoft/windowsservercore:1709 powershell  resolve-dnsname www.google.com

Name                                           Type   TTL   Section    IPAddres
                                                                       s
----                                           ----   ---   -------    --------
www.google.com                                 AAAA   226   Answer     2607:f8b
                                                                       0:4006:8
                                                                       11::2004
www.google.com                                 A      226   Answer     172.217.
                                                                       10.100
```
Not Truncated
```
PS C:\Users\cloudadmin\Documents> docker run microsoft/windowsservercore:1709 powershell write-output asda ; resolve-dnsname www.google.com
asda

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
www.google.com                                 AAAA   251   Answer     2607:f8b0:4006:811::2004
www.google.com                                 A      251   Answer     172.217.10.100
```

**Steps to reproduce the issue:**
1. Run command `docker run microsoft/windowsservercore:1709 powershell  resolve-dnsname www.google.com`
2. 
3.

**Describe the results you received:**
Output is wrapped on 80s character

**Describe the results you expected:**
Output shall not be wrapped

**Additional information you deem important (e.g. issue happens only occasionally):**
All the time

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 21
 Running: 1
 Paused: 0
 Stopped: 20
Images: 6
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: Containerhost1
ID: W5PM:FKA4:3NOQ:6ZS3:6WWQ:5NT2:FBVI:AJJZ:DME3:IFUS:G63Q:ITGX
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

**Comment by thaJeztah** [comment] 2018-02-07 22:12
Looks like this is an issue with Docker EE; primary support for that is part of your Windows License, and handled through Microsoft Support; could you open a ticket with them?

I'll close the issue here, but feel free to comment after that

**Comment by artisticcheese** [comment] 2018-02-07 22:26
I don't understand this issue present in any edition of docker, why this one specifically needs to be escalated to Microsoft?

**Comment by thaJeztah** [comment] 2018-02-07 23:53
> I don't understand this issue present in any edition of docker, why this one specifically needs to be escalated to Microsoft?

The issue was first reported with a Docker EE version on Windows Server, for which support is handled by Microsoft, and the code for that is not maintained in this repository. If the issue is still reproducible on the current master version in this repository, I can reopen.

**Closed** 2021-06-27 12:09 UTC
Labels: platform/windows, version/17.06
