### ISSUE TITLE
"mount: only root can do that (effective UID is 427680)" with --userns=host

### ISSUE THREAD

**Issue by adrienkohlbecker** [moby/moby#34119] opened 2017-07-15 01:09 UTC
**Description**

I'm unable to run `mount` in a privileged container with user namespacing set to `host`, while namespacing is set to `default` at the daemon level

**Steps to reproduce the issue:**
1. Enable user namespaces in `/etc/docker/daemon.json`: `{ "userns-remap": "default" }`
2. `docker run -ti --rm --privileged --userns=host ubuntu:16.04 mount foo bar`

**Describe the results you received:**

This fails with `mount: only root can do that (effective UID is 427680)`

**Describe the results you expected:**

I expected the mount command to work since I disabled user namespaces and I'm running in a privileged container.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 41
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.4.0-1022-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675GiB
Name: i-0edcc913210db378b.ddbuild.io
ID: WW6U:2DDS:ZZNS:4KFT:QFU4:APHR:BM7K:AFSM:33PU:HFQ6:K2WG:VSYT
Docker Root Dir: /var/lib/docker/427680.427680
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Running on EC2 xenial AMI

**Comment by thaJeztah** [comment] 2017-07-15 01:16
ping @estesp

**Comment by estesp** [comment] 2017-07-15 02:51
Effectively a duplicate of #28986. On my Xenial personal Linux system (probably with more content installed than the ubuntu:16.04 base image) this affects the following 18 *setuid* binaries:
```
find /{usr/,}{s,}bin -perm -4000
/usr/sbin/pppd
/usr/sbin/userhelper
/usr/bin/gpasswd
/usr/bin/pkexec
/usr/bin/v4l-conf
/usr/bin/chfn
/usr/bin/newgrp
/usr/bin/passwd
/usr/bin/sudo
/usr/bin/chsh
/sbin/mount.ecryptfs_private
/bin/ping
/bin/ping6
/bin/mount
/bin/ntfs-3g
/bin/fusermount
/bin/su
/bin/umount
```

To reiterate the problem we find ourselves stuck in (until we have a user namespace-aware filesystem in Linux), the actual files in the image layers have been `chown`ed to the remapped range in use by the daemon. We must do this for the user namespaced process path (normal "user namespaces enabled" mode) to work at all. After creating this mode of the daemon, it was clear that users still wanted/needed a `--privileged` route, and what we have today is effectively a compromise. We can't re-chown the container content back to '0-based' ownership, as those same layers could be/are in use by other containers running inside a remapped user namespace range. So, we left it that user namespaces are off; you are real system root in this `--userns=host` case, but the filesystem underneath you does not match. In many cases, this is sufficient for what people want to accomplish, but setuid binaries are an obvious exception case.

One possible workaround is to have a small group of required binaries for this case in a host-based volume and use something like a `-v /root-owned-binaries/bin:/bin` when using `--userns=host` & `--privileged`.

There *is* work happening upstream to solve the filesystem issue, but a final determination and solution is still probably (many?) months away from being upstream and available in distros.

**Comment by thaJeztah** [comment] 2017-07-15 08:16
Thanks @estesp - I assumed that was (or something _like that_) the issue. Let me close this one, because it's a duplicate of https://github.com/moby/moby/issues/28986,, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-15 08:16 UTC
Labels: version/17.06
