### ISSUE TITLE
Plenty of memory consumed when using a port range

### ISSUE THREAD

**Issue by boldt** [moby/moby#34328] opened 2017-07-31 14:55 UTC
**Description**

Plenty of memory is consumed, when`docker run` is used with a a port range.

**Steps to reproduce the issue:**

I observed, that docker consumes a lot of memory when a port range is opened. As an example, I am using the following coturn server image:

* https://github.com/anastasiia-zolochevska/turn-server-docker-image
* https://github.com/anastasiia-zolochevska/turn-server-docker-image

Basically it is an Ubuntu 16.04 with coturn installed. First, I ran the container as described in the README:

```
sudo docker run \
  -d \
  --restart=always \
  --name coturn \
  -p 3478:3478 \
  -p 3478:3478/udp \
  zolochevska/turn-server username password realm
```

This consumes approx. 8 MB memory (comparing `free -h` before and after `doccker run`)

**Background (how TURN works)**: In the moment a TURN server receives a bind request, it binds a (random) UDP port. In case of coturn it is a port in the range 49152-65535. Thus, it is needed to publish this port range as well. 

Thus I ran the contaner as above with more and more published UDP ports (see below).

**Describe the results you received:**

| Port range                     | #ports | memory  |
|--------------------------------|--------|---------|
| -p 65435-65535:65435-65535/udp |  100   | 116 MB  |
| -p 65035-65535:65035-65535/udp |  500   | 602 MB  |
| -p 64035-65535:64035-65535/udp | 1500   | 1,6 GB  |

I can say, that every UDP port consumes approx. 1 MB memory. Opening the whole port range for coturn (65535-49152 = 16383 ports)  means, that 16GB of memory will be needed, 

That seems to be to much for me.

**Describe the results you expected:**

Much less memory consumed when publishing a port range.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: docker-4gb-fra1-01
ID: FELR:B6QG:6QUV:MMRL:KVJ5:E234:B5Q7:36RC:SGJ6:4VKA:CYJZ:NX4F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I used the Digitalocean one-click app *Docker 17.06.0-ce on 16.04* with 4 GB of ram.

**Comment by thaJeztah** [comment] 2017-07-31 18:13
Thanks for reporting! This is a known issue with the userland-proxy; a proxy is spun up for each port that is exposed, which hogs a lot of memory. If you need to expose a large number of ports, consider;

- disabling the user land proxy (unfortunately this is not yet the default, due to a kernel bug that affects some people; https://github.com/moby/moby/issues/5618)
- use `--network=host` to use the host's network stack

I'm closing this because this is a duplicate of https://github.com/moby/moby/issues/11185, please continue the conversation over there to prevent the discussion from diverging

**Closed by thaJeztah** 2017-07-31 18:13 UTC
Labels: kind/performance, version/17.06

**Comment by boldt** [comment] 2017-07-31 18:36
Thank for pointing me to #11185
