### ISSUE TITLE
Graph deletes are non-atomic, db refs deleted without deleting on-disk entities

### ISSUE THREAD

**Issue by ewindisch** [moby/moby#6354] opened 2014-06-11 12:32 UTC
In function graph.Delete,

```
func (graph *Graph) Delete(name string) error
```

The method `graph.idIndex.Delete(id)` is called before `graph.driver.Delete(id)`

It is non-atomic. If `graph.driver.Delete(id)` fails, the `graph.idIndex.Delete` has already occurred and the image is now apparently gone, but the extents may still exist on disk in whole or in part.

**Comment by vandekeiser** [comment] 2015-01-20 15:08
Still isn't fixed..
docker rmi -f $(docker images -aq) says "Error: failed to remove one or more images"
But then i can see that disk space use doesn't go back to baseline, and  /var/lib/docker/vfs/dir/ is not empty
If i rm /var/lib/docker/vfs/dir/, then df (almost) goes back to baseline

**Comment by FelikZ** [comment] 2015-02-01 16:06
@adamhadani could you post this script to github gists? It still an issue and while it is, this script is extremely useful

**Comment by adamhadani** [comment] 2015-02-05 21:34
@FelikZ  sure , there you go https://gist.github.com/adamhadani/807e68452b43636c2d5f

**Comment by soupdiver** [comment] 2015-02-12 11:36
I just came across the exact same problem and then discovered that there is the option `docker rm -v`. I had in my memory that volumes will be deleted automatically when no container has a reference anymore to it. Does the problem discussed here just related to the auto deletion of volumes or also to the explicit deletion?

**Comment by cpuguy83** [comment] 2015-02-12 15:03
@soupdiver There is no auto deletion of volumes at all. The only time a volume is deleted is if you explicitly `docker rm -v`.

**Comment by soupdiver** [comment] 2015-02-12 21:48
@cpuguy83 Ah okay ... I ever thought this part from the docs `Volumes persist until no containers use them` means that they will be deleted after the last container referencing to a volume is gone

**Comment by thaJeztah** [comment] 2015-02-12 22:05
@soupdiver if that's how it's written in the docs, I agree that's confusing. Can you add a link where in the docs you found that sentence? (Then I'll create a small PR to improve that)

**Comment by soupdiver** [comment] 2015-02-12 22:07
@thaJeztah It can be found in the user guide. https://docs.docker.com/userguide/dockervolumes/
Last point under **Data volumes**

**Comment by thaJeztah** [comment] 2015-02-12 22:13
@soupdiver thanks for pointing that out, I'll see if I can come up with a better description there!

**Comment by soupdiver** [comment] 2015-02-12 22:17
@thaJeztah Just for clarification: Is the current behaviour that volume directories are **not** deleted the normal behaviour since ever? I ever thought that they will be deleted after all references are gone and I barely remember that the docs explicitly said this when I started using Docker a time ago. But I'm not 100% sure about this

**Comment by thaJeztah** [comment] 2015-02-13 00:24
@soupdiver yes, this is normal behavior and "by design". Docker should *never* remove your data unless you explicitly tell it to (data is important). There *are* some difficulties with this (i.e., "orphaned" volumes), which is being worked on in https://github.com/docker/docker/pull/8484

I just created a PR that (hopefully) makes this a bit more clear, you can find it here: https://github.com/docker/docker/pull/10757

**Comment by soupdiver** [comment] 2015-02-13 00:34
@thaJeztah ok thanks! The PR really explains the behaviour more clearly

**Comment by dnephin** [comment] 2015-06-24 01:09
We've run into this problem on our jenkins ci server as well (docker 1.5). I think the discussion about volumes is actually a  tangent from the original issue.  The issue is not really about volumes, it's about image layers being left on-disk after a `docker rmi`.

For now we're able to identify and reclaim this lost space using this bash:
```bash
#!/bin/bash

set -eu

cd /var/lib/docker/aufs/diff

for image in $(du -s * 2> /dev/null | sort -nr | grep -v -- '-init' | cut -f 2); do
    echo "Inspecting or removing $image"
    docker inspect $image > /dev/null || rm -r $image;
done
```

**Comment by dnephin** [comment] 2015-09-01 02:20
+kind/bug
+system/storage (I think)

**Comment by vitalyisaev2** [comment] 2015-09-27 09:02
@adamhadani very nice job, thank you

**Comment by presidento** [comment] 2016-03-01 16:19
@dnephin We had the same issue.

But be careful: in Docker 1.10, these file names does not match with containers or images, so your script will remove everything from the diff folder. I could purge everything from every docker folder manually, but I don't know, how can we do this cleanup using docker >= 1.10.

**Comment by xiaods** [comment] 2016-09-21 16:53
this bug is outdate? anyone can handle it.

**Comment by LK4D4** [comment] 2016-09-21 17:04
I think it's duplicate of another bug from @cpuguy83

**Comment by vdemeester** [comment] 2018-02-14 14:47
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉

**Closed by vdemeester** 2018-02-14 14:47 UTC
Labels: area/storage, kind/bug
