### ISSUE TITLE
Provide option to DNS resolver: prefer target service with fewest hops

### ISSUE THREAD

**Issue by port22** [moby/moby#40842] opened 2020-04-21 08:38 UTC
Problem:
You have 5 Servers running in swarm mode, running a service `FOO` and a service `BAR` with multiple replicas each. Any FOO container will resolve BAR with all ip addresses on any host.

This is a showstopper in production, where multiple services are talking together before returning the first byte (TTFB) to a http request. It adds network latency of >1s in my case.

Optimally, services would only(preferably!) talk to services running on the same host.

If there was an option to the swarm dns resolver, that it either manages to find out the fewest hops from the source service to the target (and caches the answer), or, to hold/cache individual address-lists for every single host so it only returns target services tagged(?) with the source host. 
Or something like this, you understand the point... I know there is no fallback a records in dns, but dns sucks anyways...that's where swarm's dns resolver could really shine.

Albeit I understand:
- for most users this is not absolutely necessary and
- it diminishes the advantages and simplicity where you just run services so just any container will answer

But making this an option, only those would use it who need it.
How are you approaching lowest latency in production with swarm?

**Comment by thaJeztah** [comment] 2020-06-04 13:41
Looks like a duplicate of https://github.com/moby/moby/issues/32854. Let me close this one to not have the discussion diverge, but feel free to comment if you think I closed by mistake

**Closed by thaJeztah** 2020-06-04 13:41 UTC
Labels: area/networking, area/swarm, kind/feature
