### ISSUE TITLE
Segmentation Fault in Swarm

### ISSUE THREAD

**Issue by coughlanio** [moby/moby#35035] opened 2017-09-29 08:42 UTC
**Description**

Encountered a segmentation fault this evening in our swarm environment, forcing the docker daemon on one of our nodes to restart.

**Steps to reproduce the issue:**
1. Run a swarm service
2. :man_shrugging: 

**Describe the results you received:**

Segmentation fault.

**Describe the results you expected:**

No Segmentation fault.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
Sep 29 06:30:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:30:01.196700285Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:30:31 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:30:31.198286477Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:31:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:31:01.200051526Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:31:31 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:31:31.201748198Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:32:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:32:01.204480637Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:33:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:33:01.207387727Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:34:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:34:01.210787217Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:35:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:35:01.214222654Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:36:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:36:01.217369241Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:37:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:37:01.219562834Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:37:31 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:37:31.221348387Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: time="2017-09-29T06:38:01.223254438Z" level=info msg="Node join event for prod-algo-swarm-1-bfafd2df1b36/10.146.0
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcad160]
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: goroutine 3232831 [running]:
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).purgeSameNode(0xc42028e9c0, 0
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/delegate.go:65 +0x90
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).handleNodeEvent(0xc42028e9c0,
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/delegate.go:108 +0x184
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*delegate).MergeRemoteState(0xc420308230,
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/delegate.go:499 +0x27f
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).mergeRemoteState(0xc42093e1e0, 0x26
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]:         /go/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/net.go:989 +0x495
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).handleConn(0xc42093e1e0, 0x2625980,
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]:         /go/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/net.go:233 +0xa76
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]: created by github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).streamListen
Sep 29 06:38:01 prod-algo-swarm-2 dockerd[13215]:         /go/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/net.go:192 +0x114
Sep 29 06:38:01 prod-algo-swarm-2 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 29 06:38:01 prod-algo-swarm-2 systemd[1]: docker.service: Unit entered failed state.
Sep 29 06:38:01 prod-algo-swarm-2 systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ryri1m674ecv5h0yw2qocr5bm
 Is Manager: false
 Node Address: 10.146.0.6
 Manager Addresses:
  10.146.0.5:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-35-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.68GiB
Name: prod-algo-swarm-2
ID: N6WL:JHGC:TRIQ:KZJD:NHLR:SUEA:AXVG:R7WU:3CT2:Q24W:XDTQ:RRE5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

GCE Instance, two node swarm.

**Comment by thaJeztah** [comment] 2017-09-29 08:56
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/34591 - can you also try if updating to the latest patch release for 17.06 (17.06.2) resolves this?

Closing this for now, because it's a duplicate of https://github.com/moby/moby/issues/34591, please continue the conversation on that issue so that the discussion doesn't diverge

**Closed by thaJeztah** 2017-09-29 08:56 UTC
Labels: version/17.06
