### ISSUE TITLE
 Docker-ce 18.05: DOCKER_OPTS in /etc/default/docker does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by jodumont** [moby/moby#37401] opened 2018-07-06 07:26 UTC
as commented by @thaJeztah (https://github.com/moby/moby/issues/25357#issuecomment-237186744)

Ubuntu make an exception of itself by non using /etc/default/docker with systemd.

Every other Linux is use with Docker (_by heart Alpine, CentOS, Fedora, ..._) are able to read this file when you restart docker

why not Ubuntu ?

**Comment by thaJeztah** [comment] 2018-07-06 12:18
None of the official Docker packages for distros that use systemd use the `/etc/default/docker` file; you can customize your systemd configuration, and use a drop-in file to make it use `/etc/default/docker` (see this example; https://docs.docker.com/v1.12/engine/admin/systemd/#/custom-docker-daemon-options), but the recommendation is to use the `daemon.json` configuration file.

Closing this issue, because this is not a bug, and has been discussed in various other issues, but feel free to continue the conversation.

**Closed by thaJeztah** 2018-07-06 12:18 UTC
