### ISSUE TITLE
How can I upgrade docker and keep the configuration not changed. 

### ISSUE THREAD

**Issue by wpeng102** [moby/moby#36006] opened 2018-01-14 03:19 UTC
For example, I want upgrade docker from 17.03 to 17.09 in production env.  We need keep the docker configuration not changed.  
BTW, we have not config `--live-restore `, `systemctl stop docker`  will stop all the containers? In my env, after run `systemctl stop docker`, there has  one docker-containerd-shim process left. 
```
root     26907     1  0 08:13 ?        00:00:00  docker-containerd-shim 4de2ab526b8b44aabbb16dde330c9b41abfd5c6f807637060c9435cedad73dd0 /var/run/docker/libcontainerd/4de2ab526b8b44aabbb16dde330c9b41abfd5c6f807637060c9435cedad73dd0 docker-runc
```

**Comment by cpuguy83** [comment] 2018-01-14 12:43
Configurations need to be set either in a systemd drop-in or in /etc/docker/daemon.json

**Comment by thaJeztah** [comment] 2018-01-14 12:58
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-01-14 12:58 UTC
