### ISSUE TITLE
Feature Request: Please add support for extends when deploying a stack from a compose-file

### ISSUE THREAD

**Issue by marascha** [moby/moby#29304] opened 2016-12-10 20:21 UTC
In v1.13.0-rc3 it's not possible to deploy a stack using a compose-file that contains services extending other services using  _extends_.

**Example** 
compose.yml:
```
version: '3.0'
    services:
      service2:
        extends:
           file: ../common-services.yml
           service: service1
        deploy:
            replicas: 2
```
Docker  responses with the following error message when running 

> docker stack deploy --compose-file compose.yml my_stack
```
Compose file contains unsupported options:

extends: Support for `extends` is not implemented yet. Use `docker-compose config` to generate a configuration with all `extends` options resolved, and deploy from that.
```
The workaround with 'docker-compose config' is not really an option, as version 3.0 is not supported by docker-compose and _deploy_ is not available in version 2.1 of docker-compose.

It will be great if the support for extend could be added soon.

**Comment by vdemeester** [comment] 2016-12-12 14:52
@marascha it should be a workaround once 1.13 and docker-compose 1.10 are out (should be released really closed to each other). It's an hard one to support and we didn't to work on that before 1.13 code freeze :sweat:

**Comment by marascha** [comment] 2016-12-12 16:37
@vdemeester I see. But there will be support for _exentds_ in 1.14, right?

**Comment by shouze** [comment] 2017-02-15 11:37
@vdemeester @dnephin I wonder why - even  if not perfect - [docker libcompose](https://github.com/docker/libcompose) is not used in docker instead of the copied fork of [compose-file](https://github.com/docker/docker/commit/f5af9b9738892b5988f987ce5fbce6e31a10e768).

libcompose looks by far more advanced and has wider support of compose files parsing no? At least maybe both libs should converge soon?

**Comment by vdemeester** [comment] 2017-02-15 12:16
@shouze there is design and technical reasons for not having used `libcompose` (architecture, etc…). The compose integration in `docker/docker` only support composefile v3 (and swarm mode), and that's by design.

I'm gonna make sure both lib converge, but both have their values and "lifecycle" — i.e. `docker/docker` will never support composefile version lower than v3 for example, where `libcompose` aims to support the same thing `docker/compose` supports (and we are lagging behind :sweat:).

**Comment by shouze** [comment] 2017-02-15 12:20
ok fine I understand the point and the vision.

So maybe libcompose code  (even if incomplete/buggy) can be used to bring back the `extends` feature in compose file 3.x (would ❤️ to see it back in 3.2)?

**Comment by shouze** [comment] 2017-02-17 11:03
I've pushed somme reflexion about to bring back extends or not and I think there's an opportunity to make something great again 👼 https://github.com/docker/compose/issues/4315#issuecomment-280619398

**Comment by vdemeester** [comment] 2018-04-24 10:56
Closing this one in favor of https://github.com/moby/moby/issues/31101 (duplicates)

**Closed by vdemeester** 2018-04-24 10:56 UTC
Labels: area/bundles, kind/enhancement
