### ISSUE TITLE
cp: preserving permissions for '/bar': Invalid argument

### ISSUE THREAD

**Issue by wojas** [moby/moby#30245] opened 2017-01-18 13:36 UTC
**Description**

After upgrading Docker for Mac to 1.13.0-rc7-beta37 (15013) from rc6, my build fails with an error from cp about preserving permissions when using `-rp`.

**Steps to reproduce the issue:**
1. Create this Dockerfile:
```
FROM ubuntu:16.04
RUN mkdir /foo
RUN cp -rp /foo /bar
```
2. `docker build .`

**Describe the results you received:**

```
Step 1/3 : FROM ubuntu:16.04
 ---> bd3d4369aebc
Step 2/3 : RUN mkdir /foo
 ---> Running in c05ee1ef5f1c
 ---> 923b0c9d9e85
Removing intermediate container c05ee1ef5f1c
Step 3/3 : RUN cp -rp /foo /bar
 ---> Running in 86cc22d02c92
cp: preserving permissions for '/bar': Invalid argument
The command '/bin/sh -c cp -rp /foo /bar' returned a non-zero code: 1
```

**Describe the results you expected:**

From Docker 1.12.3 on a different machine (this also worked with 1.13.0-rc5 and rc6):

```
Step 1 : FROM ubuntu:16.04
 ---> 104bec311bcd
Step 2 : RUN mkdir /foo
 ---> Running in 799277a89b9c
 ---> d806168b8014
Removing intermediate container 799277a89b9c
Step 3 : RUN cp -rp /foo /bar
 ---> Running in 57ea33a071d3
 ---> 0700a4b77202
Removing intermediate container 57ea33a071d3
Successfully built 0700a4b77202
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This error appears after upgrading from 1.13.0-rc6 to rc7.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc7
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc7
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 99
 Running: 18
 Paused: 0
 Stopped: 81
Images: 594
Server Version: 1.13.0-rc7
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 696
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.3-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.934 GiB
Name: moby
ID: XKZB:LGXI:4HPS:6TPF:ZWNZ:JZAW:KG65:LFIP:SBM5:QMXF:23MQ:A6US
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 147
 Goroutines: 130
 System Time: 2017-01-18T13:34:10.833485639Z
 EventsListeners: 1
Username: wojas
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using Docker for Mac
```
Version 1.13.0-rc7-beta37 (15013)
Channel: Beta
f2c3d3454f
```

**Comment by wojas** [comment] 2017-01-18 14:06
Some context: this error happens when running the [OpenResty](https://openresty.org/en/) configure script. 

My temporary hacky workaround:
```
RUN echo '#!/bin/sh\n\
shift 1; /bin/cp -r "$@"' > /usr/local/bin/cp && chmod 755 /usr/local/bin/cp
RUN ./configure -j2
RUN rm -f /usr/local/bin/cp
```

**Comment by wojas** [comment] 2017-01-18 15:02
I narrowed the issue down to `cp -r --preserve=mode /foo /bar`, probably in the `copy_acl()` call in coreutils. It only happens on container filesystems, not in volumes. Maybe a bug in aufs?

**Comment by cpuguy83** [comment] 2017-01-18 15:16
@wojas For sure, aufs does not support ACL's.

**Comment by wojas** [comment] 2017-01-18 15:26
@cpuguy83 The call should not fail. If aufs does not support ACLs, there will not be any to copy, since the source dir is on the same filesystem.

This worked in older versions. It turns out that this also affect luarocks installation of lua-cjson-ol:
```
Error: Build error: Failed copying contents of 'lua' directory: Failed copying lua to /usr/local/lib/luarocks/rocks/lua-cjson-ol/1.0-1/lua
```

**Comment by cpuguy83** [comment] 2017-01-18 15:33
@wojas Most likely this is from the kernel update in the docker4mac upgrade.
Ping @justincormack

**Comment by wojas** [comment] 2017-01-19 17:42
I cannot reproduce this after resetting Docker for Mac. Since nobody else seems to be having this issue, it's probably due to some random filesystem corruption. Closing issue.

**Comment by justincormack** [comment] 2017-01-19 18:00
@wojas If you reset the beta it will switch to using `overlay2` rather than `aufs` which may be what fixed the issue. We are preferring `overlay2` now as it has fewer issues. It could have been corruption, but less likely.

**Comment by wojas** [comment] 2017-01-19 18:10
@justincormack That might explain why it fixed the issue for me. Should this issue be reopened then? Anyone able to reproduce it on a newer kernel?

**Comment by justincormack** [comment] 2017-01-19 18:21
You can switch Docker for Mac back to aufs by adding `{"storage-driver": "aufs"}` in the daemon/advanced preferences pane in the Docker for Mac config. It would be odd if the kernel update has broken something, but it is possible.

There may still be a copy, if it is copying up. So it seems more likely it never worked with aufs.

**Comment by wojas** [comment] 2017-01-19 18:29
@justincormack Switched back to aufs and the issue came back, so it was not due to filesystem corruption. Reopening this issue.

**Comment by wojas** [comment] 2017-01-19 18:37
@justincormack About "So it seems more likely it never worked with aufs": I am very sure it worked with beta 35 and 36, since I have been actively working on this Dockerfile this week. I experienced the WORKDIR caching bug in beta 35, so I did a good amount of test builds that included the step that now triggers this bug. ;-)

**Comment by justincormack** [comment] 2017-01-19 18:42
we unfortunately did switch kernel versions a few times over those releases, we were on 4.8, then had an issue, reverted to 4.4, then switched to 4.9 as originally intended. It is possible there are some issues with the aufs patches against different recent kernel versions.

**Comment by mnunberg** [comment] 2017-01-20 01:37
FWIW I'm getting the exact same behavior. Encountered this when trying to build a package using cowbuilder for Ubuntu 16.04. Other versions of Deb/Ubuntu don't seem to do this.

```
mnunberg@mbp15II /tmp $ docker build .
Sending build context to Docker daemon 2.114 MB
Step 1/3 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
b3e1c725a85f: Pull complete 
4daad8bdde31: Pull complete 
63fe8c0068a8: Pull complete 
4a70713c436f: Pull complete 
bd842a2105a8: Pull complete 
Digest: sha256:7a64bc9c8843b0a8c8b8a7e4715b7615e4e1b0d8ca3c7e7a76ec8250899c397a
Status: Downloaded newer image for ubuntu:16.04
 ---> 104bec311bcd
Step 2/3 : RUN mkdir /foo
 ---> Running in d90e8183267e
 ---> 252b7fa90962
Removing intermediate container d90e8183267e
Step 3/3 : RUN cp -rp /foo /bar
 ---> Running in 63fe76c970fb
cp: preserving permissions for '/bar': Invalid argument
The command '/bin/sh -c cp -rp /foo /bar' returned a non-zero code: 1
```

**Comment by GeoffreyBooth** [comment] 2017-01-20 08:04
I’m seeing this issue, with a Dockerfile that’s from `jboss/wildfly:9.0.2.Final` which up a few levels is from `centos:7`.

The line that crashes the build is like:
```sh
cp --preserve=mode,ownership,timestamps --update --recursive a b
```

**Comment by thaJeztah** [comment] 2017-01-20 10:09
@wojas could you reopen this in the Docker for Mac issue tracker? (https://github.com/docker/for-mac/issues) It looks like this is not a bug in docker itself, but in the version/configuration of the kernel and aufs module in Docker for Mac.

It's better to have this issue in the Docker for Mac issue tracker, so that other users running on Docker for Mac can track progress as well.

Switching to the `overlay2` storage driver is my recommendation as well, as it's a default feature in recent kernels, and more actively maintained in the kernel.

**Comment by justincormack** [comment] 2017-01-20 10:54
Its not a Docker for Mac issue realky, it is an upstream aufs issue, we are
using the unmodified upstream, so may as well stay here...

**Comment by justincormack** [comment] 2017-01-20 14:43
Strangely it works with `FROM alpine` instead, the version of `cp` must be using a different syscall.

**Comment by justincormack** [comment] 2017-01-20 16:01
Confirm this did work in 4.4.x

**Comment by justincormack** [comment] 2017-01-20 16:10
On 4.9 the trace gives:
```
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "nodev\tsysfs\nnodev\trootfs\nnodev\tt"..., 1024) = 476
read(3, "", 1024)                       = 0
close(3)                                = 0
geteuid()                               = 0
stat("/bar", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/foo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/bar/foo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/foo", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getdents(3, /* 2 entries */, 32768)     = 48
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
utimensat(AT_FDCWD, "/bar/foo", [{1484927717, 203576439}, {1484927716, 0}], 0) = 0
getxattr("/foo", "system.posix_acl_access", 0x7fff6a3446e0, 132) = -1 ENODATA (No data available)
stat("/foo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getxattr("/foo", "system.posix_acl_default", 0x7fff6a3446e0, 132) = -1 ENODATA (No data available)
stat("/foo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
setxattr("/bar/foo", "system.posix_acl_access", "\2\0\0\0\1\0\7\0\377\377\377\377\4\0\5\0\377\377\377\377 \0\5\0\377\377\377\377", 28, 0) = 0
removexattr("/bar/foo", "system.posix_acl_default") = -1 EINVAL (Invalid argument)
open("/usr/lib/x86_64-linux-gnu/charset.alias", O_RDONLY|O_NOFOLLOW) = -1 ENOENT (No such file or directory)
write(2, "cp: ", 4cp: )                     = 4
write(2, "preserving permissions for '/bar"..., 37preserving permissions for '/bar/foo') = 37
write(2, ": Invalid argument", 18: Invalid argument)      = 18
write(2, "\n", 1
```

ie `ENODATA` for the xattr

**Comment by justincormack** [comment] 2017-01-20 16:15
Ah so it looks like `removexattr` is broken in 4.9

**Comment by justincormack** [comment] 2017-01-20 16:33
Sent a bug report to the aufs mailing list.

**Comment by justincormack** [comment] 2017-01-20 16:37
cc @sfjro

**Comment by sfjro** [comment] 2017-01-20 19:03
Hello Justin,

Thanx forwarding.
But I don't see the points. Who built your v4.4 and v4.9 aufs modules?
And how is your mount options?

There are some configurations and settings which affects the behaviour
in aufs around ACL.

- CONFIG_AUFS_XATTR (and CONFIG_FS_POSIX_ACL obviously)

- mount option "acl" (and the branch fs should support ACL too,
  obviously)

- mount option ICEX family (icexsec | icexsys | icextr | icexusr | icexoth | icex)
  ICEX stands for Ignore the error on copying\-up/down XATTR.
  When an internal copy\-up/down happens, aufs tries copying all XATTRs.
  Here an error can happen because of the XATTR support on the dst
  branch may different from the src branch. If you know how the branch
  supports or unsupports XATTR, you can specify these attributes.
  `icexsec' means to ignore an error on copying\-up/down XATTR categorized
  as "security" (for LSM and capability). And `icexsys,' `icextr,' and
  `icexusr,' are for "system" (for posix ACL), "trusted" and "user"
  categories individually.
  `icexoth' is for any other category. To be convenient, `icex` sets them
  all.
  See also linux/Documentation/filesystems/aufs/design/06xattr.txt.
(quoted from aufs manual)


Next time when you ask me something, give me these necessary info.
(from aufs README file)

5. Contact
----------------------------------------
When you have any problems or strange behaviour in aufs, please let me
know with:
- /proc/mounts (instead of the output of mount(8))
- /sys/module/aufs/*
- /sys/fs/aufs/* (if you have them)
- /debug/aufs/* (if you have them)
- linux kernel version
  if your kernel is not plain, for example modified by distributor,
  the url where i can download its source is necessary too.
- aufs version which was printed at loading the module or booting the
  system, instead of the date you downloaded.
- configuration (define/undefine CONFIG_AUFS_xxx)
- kernel configuration or /proc/config.gz (if you have it)
- behaviour which you think to be incorrect
- actual operation, reproducible one is better
- mailto: aufs-users at lists.sourceforge.net


J. R. Okajima

**Comment by domenic** [comment] 2017-01-20 22:08
Since the most recent Docker update I am also seeing this on Docker for Windows (in an Ubuntu-based container).

**Comment by clintonb** [comment] 2017-01-22 15:15
I also encounter this issue with an Ubuntu 16.04 base container. My attempts to use [`nodeenv`](https://github.com/ekalinin/nodeenv) to install a pre-built version of Node.js fails with numerous lines of the form `cp: preserving permissions for ‘/edx/app/discovery/nodeenvs/discovery/include/node/openssl/archs/linux-armv4’: Invalid argument`. I verified manually that `cp -a`, the command used by `nodeenv` fails when I run it manually.

If I downgrade to Ubuntu 12.04, the issue goes away.

I am using Docker for Mac 1.13.0-beta38 (15084).

```
$ docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 155
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 290
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.855 GiB
Name: moby
ID: DUZJ:AOF2:2EEL:V4B7:ZWZ3:QTCW:IN22:6IL3:SSMM:D7PS:OIR4:IPIN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-01-22T15:13:31.629210262Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: clintonb
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by justincormack** [comment] 2017-01-23 11:58
@sfjro sorry, I think my email partially bounced from mailing list not sure why

these are kernels I compiled myself, which are very close to vanilla 4.4.41 and 3.9.3, just a few small entirely unrelated patches. My xfs related config is

```
CONFIG_AUFS_FS=y
# CONFIG_AUFS_BRANCH_MAX_127 is not set
# CONFIG_AUFS_BRANCH_MAX_511 is not set
# CONFIG_AUFS_BRANCH_MAX_1023 is not set
CONFIG_AUFS_BRANCH_MAX_32767=y
CONFIG_AUFS_SBILIST=y
# CONFIG_AUFS_HNOTIFY is not set
# CONFIG_AUFS_EXPORT is not set
CONFIG_AUFS_XATTR=y
# CONFIG_AUFS_FHSM is not set
# CONFIG_AUFS_RDU is not set
# CONFIG_AUFS_SHWH is not set
# CONFIG_AUFS_BR_RAMFS is not set
# CONFIG_AUFS_BR_FUSE is not set
CONFIG_AUFS_BDEV_LOOP=y
# CONFIG_AUFS_DEBUG is not set
```

Docker has never set any of the aufs specific mount options, so not `acl` or `icex`, and this has not changed for 4.4 to 4.9.

I think this is the same issue that Yair Yarom on the mailing list also saw. I will test the patch you posted.

**Comment by justincormack** [comment] 2017-01-23 13:33
@sfjro I can confirm that the patch you posted to the mailing list does fix this issue.

@wojas we  will ship this with the next beta (due tomorrow) .

**Comment by sfjro** [comment] 2017-01-23 19:32
Justin Cormack:
> @sfjro I can confirm that the patch you posted to the mailing list does =
fix this issue.

Thanx.
The patch will be included in next aufs release.


J. R. Okajima

**Comment by digitalKiva** [comment] 2017-01-25 21:48
@justincormack would you happen to know the Docker beta version that this was fix was released in?  Also, when this will arrive in the next Docker stable release?

I experienced this same issue and am confused how my Docker daemon was configured to aufs when I didn't specifically change anything when I upgraded my stable version last week.  Thoughts?

**Comment by justincormack** [comment] 2017-01-25 23:07
Beta 39 which was released today has the fix. It will be in the next
stable, which should be next week.

The default is now overlay2 if you reset, you can override in the advanced
config by adding the json config.

**Comment by sfjro** [comment] 2017-01-28 04:00
sfjro@users.sourceforge.net:
> Justin Cormack:
> > @sfjro I can confirm that the patch you posted to the mailing list does =
> fix this issue.
>
> Thanx.
> The patch will be included in next aufs release.

The patch was refined and merged into today's aufs release. The newer is
better and recommended.


J. R. Okajima

**Comment by thaJeztah** [comment] 2017-01-28 14:55
ping @justincormack ^^ (thanks for the update @sfjro, much appreciated!)

**Comment by thaJeztah** [comment] 2023-04-20 23:58
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS

**Closed by thaJeztah** 2023-04-20 23:58 UTC
Labels: area/storage/aufs, platform/desktop, version/1.13
