### ISSUE TITLE
How to update the docker service file and change --privileged flag

### ISSUE THREAD

**Issue by Renukasonwane** [moby/moby#43391] opened 2022-03-17 10:53 UTC
One of my docker container is running in Privileged Mode (as shown below) -

`docker inspect <ContainerID> | grep 'Privileged' "Privileged": true,`

How to make the container as non-privileged and will removing "--privileged " from container service file will work ?

**Comment by thaJeztah** [comment] 2022-03-17 13:53
You need to create a new container without `--privileged`; it's not possible to change a container from privileged to non-privileged after it's created.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2022-03-17 13:53 UTC
Labels: kind/question
