### ISSUE TITLE
Cannot run Docker: "no space left on device" with plenty of space available

### ISSUE THREAD

**Issue by averri** [moby/moby#36473] opened 2018-03-02 19:56 UTC
Docker is reporting no space available even with plenty of space available, as evidence bellow.

```
[root@home]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/cos-root  500G   55G  446G  11% /
devtmpfs              2.9G     0  2.9G   0% /dev
tmpfs                 2.9G     0  2.9G   0% /dev/shm
tmpfs                 2.9G  297M  2.6G  11% /run
tmpfs                 2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/sda1             243M  162M   68M  71% /boot
/dev/dm-3              10G  424M  9.6G   5% /var/lib/docker/devicemapper/mnt/c5806dab4c68a1f619cfb9bad711ba77f4402b170da43657f92e0d461c7993c2
shm                    64M     0   64M   0% /var/lib/docker/containers/6d39082cc59ac91f58ccbc1888ed673ebfaade8a7fcd7028fb40241f4bf7750c/shm
/dev/dm-8              10G  379M  9.7G   4% /var/lib/docker/devicemapper/mnt/901a8bfcf6f5d148d3c6a0f1e169a4e57c45f090ab85247c62d20a91aae84b88
shm                    64M     0   64M   0% /var/lib/docker/containers/956beb8f2531564c7217d33a892f7404df7548e8a2841c251808e2a3c35e3405/shm
tmpfs                 581M     0  581M   0% /run/user/1000
tmpfs                 581M     0  581M   0% /run/user/1001
tmpfs                 581M     0  581M   0% /run/user/1002
tmpfs                 581M     0  581M   0% /run/user/1003
/dev/dm-7              10G  228M  9.8G   3% /var/lib/docker/devicemapper/mnt/642ba651036f4cbfd9e60dd405895d1b421fbf5a42260d303b4d32612378f4c2
shm                    64M     0   64M   0% /var/lib/docker/containers/dd43f6569cea512e2c870652936a444901de7baf05a25b77c7caad3e65f24641/shm
/dev/dm-2              10G  173M  9.9G   2% /var/lib/docker/devicemapper/mnt/72a82507d1d063c0a88d71027825899391c6eef00d098a5994419e4fe23fda90
shm                    64M     0   64M   0% /var/lib/docker/containers/f9321a9111297e71f5c99e53b3b1d91ae8d541416d204b5283406a51daafe251/shm
/dev/dm-4              10G  973M  9.1G  10% /var/lib/docker/devicemapper/mnt/4e4fda15c3169bd712b8d5c2ff1d9b78954de15e7f8c22ffabe1fac55115a4c6
shm                    64M     0   64M   0% /var/lib/docker/containers/b35138ccfe50437ef17c20b02706fa0b11ebadb3d54ddd26dd435b25f6cd5943/shm
```

Running Docker:

```
[root@home]# docker run ubuntu echo hello
docker: Error response from daemon: mkdir /var/run/docker/libcontainerd/0823930a8dba111dc94265d898c0b44b1ae4b179a9c6672bc12e8cec2eab6b1d: no space left on device.
```

Environment:
- OS: CentOS 7.4
- Docker:  version 17.05.0-ce, build 89658be

**Comment by dpyro** [comment] 2018-03-02 21:15
You probably have to increase the size of the base image @averri. If you're on macOS, for example: 
<img width="622" alt="screen shot 2018-03-02 at 15 15 09" src="https://user-images.githubusercontent.com/297124/36922154-8f2a6660-1e2c-11e8-9191-5ffacdeb4437.png">

**Comment by thaJeztah** [comment] 2018-03-03 14:12
Note that Docker 17.05 has reached end of life in June of last year, and hasn't been maintained since then.

Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by averri** [comment] 2018-03-04 17:45
Hi @thaJeztah, I can't reproduce the issue yet, but I have found lots of inodes associated with stdin/stdout/stderr. After removing them, the problem is gone.

```
# docker version
Client:                                   
 Version:      17.05.0-ce                 
 API version:  1.29                       
 Go version:   go1.7.5                    
 Git commit:   89658be                    
 Built:        Thu May  4 22:06:25 2017   
 OS/Arch:      linux/amd64                
                                          
Server:                                   
 Version:      17.05.0-ce                 
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5                    
 Git commit:   89658be                    
 Built:        Thu May  4 22:06:25 2017   
 OS/Arch:      linux/amd64                
 Experimental: false                      
```

```
# docker info                                                     
Containers: 15                                                                             
 Running: 6                                                                                
 Paused: 0                                                                                 
 Stopped: 9                                                                                
Images: 252                                                                                
Server Version: 17.05.0-ce                                                                 
Storage Driver: devicemapper                                                               
 Pool Name: docker-253:0-1075740924-pool                                                   
 Pool Blocksize: 65.54kB                                                                   
 Base Device Size: 10.74GB                                                                 
 Backing Filesystem: xfs                                                                   
 Data file: /dev/loop0                                                                     
 Metadata file: /dev/loop1                                                                 
 Data Space Used: 23.12GB                                                                  
 Data Space Total: 107.4GB                                                                 
 Data Space Available: 84.25GB                                                             
 Metadata Space Used: 40.7MB                                                               
 Metadata Space Total: 2.147GB                                                             
 Metadata Space Available: 2.107GB                                                         
 Thin Pool Minimum Free Space: 10.74GB                                                     
 Udev Sync Supported: true                                                                 
 Deferred Removal Enabled: false                                                           
 Deferred Deletion Enabled: false                                                          
 Deferred Deleted Device Count: 0                                                          
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data                            
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata                    
 Library Version: 1.02.140-RHEL7 (2017-05-03)                                              
Logging Driver: json-file                                                                  
Cgroup Driver: cgroupfs                                                                    
Plugins:                                                                                   
 Volume: local                                                                             
 Network: bridge host macvlan null overlay                                                 
Swarm: active                                                                              
 NodeID: 58gm53h32yd0dj8uvnqs4b0uq                                                         
 Is Manager: true                                                                          
 ClusterID: bx7t0b6g4vu85e6yoz4yvsnwg                                                      
 Managers: 1                                                                               
 Nodes: 1                                                                                  
 Orchestration:                                                                            
  Task History Retention Limit: 5                                                          
 Raft:                                                                                     
  Snapshot Interval: 10000                                                                 
  Number of Old Snapshots to Retain: 0                                                     
  Heartbeat Tick: 1                                                                        
  Election Tick: 3                                                                         
 Dispatcher:                                                                               
  Heartbeat Period: 5 seconds                                                              
 CA Configuration:                                                                         
  Expiry Duration: 3 months                                                                
 Node Address: 5.189.160.108                                                               
 Manager Addresses:                                                                        
  5.189.160.108:2377                                                                       
Runtimes: runc                                                                             
Default Runtime: runc                                                                      
Init Binary: docker-init                                                                   
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145                               
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228                                     
init version: 949e6fa                                                                      
Security Options:                                                                          
 seccomp                                                                                   
  Profile: default                                                                         
Kernel Version: 3.10.0-327.el7.x86_64                                                      
Operating System: CentOS Linux 7 (Core)                                                    
OSType: linux                                                                              
Architecture: x86_64                                                                       
CPUs: 2                                                                                    
Total Memory: 5.67GiB                                                                      
Name: vmi77191.contabo.host                                                                
ID: 2DT4:6HUA:EPDG:3E2G:MEWG:3QXG:BHCK:SSAN:FHGB:TTDZ:JQGG:MFXH                            
Docker Root Dir: /var/lib/docker                                                           
Debug Mode (client): false                                                                 
Debug Mode (server): false                                                                 
Registry: https://index.docker.io/v1/                                                      
Experimental: false                                                                        
Insecure Registries:                                                                       
 127.0.0.0/8                                                                               
Live Restore Enabled: false                                                                
                                                                                           
```

**Comment by cpuguy83** [comment] 2018-03-05 21:03
I believe this was a bug in 17.05 not cleaning up stdout/stderr correctly in all cases.
This should be fixed by 17.06+

Closing since this should be a resolved issue in newer versions of Docker.
If you upgrade and still have a problem (after removing the left-over stdout/stderr files... a reboot should take care of it) then let us know.

Thanks! 🙇 👼

**Closed by cpuguy83** 2018-03-05 21:03 UTC
Labels: area/storage/devicemapper, status/more-info-needed, version/17.05

**Comment by Shinoby1992** [comment] 2018-06-04 23:56
im running docker on a cloud engine linux server, now i got the same error with running 

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

i have running 50 container but its just 3 different images
1x image 1
1x image 2
50x image 3
now creating a new one via ssh getting me the error

```
docker: Error response from daemon: mkdir /var/lib/docker/overlay2/80b87cb3384f465cbc2f82c244b4183ea7c34090f152af26907faf914300c625-init: no space left on device.
See 'docker run --help'.
```

i tried
`sudo docker system prune`
but it cleaned 0 b

**Comment by vmorris** [comment] 2018-09-06 22:03
@Shinoby1992 you should open a new issue please.

**Comment by john612** [comment] 2018-10-18 14:11
You closed this? Wow it is still and issue. I am having the same issue and am running: docker version
Client:
 Version:      18.03.1-ol
 API version:  1.37
 Go version:   go1.9.4
 Git commit:   0d51d18
 Built:        Wed Aug 22 21:59:42 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ol
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0d51d18
  Built:        Wed Aug 22 22:03:05 2018
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by afridi26** [comment] 2020-04-15 16:34
Any updates for this issue.  I am facing the same problem. 

`Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false`

```
docker run ubuntu echo hello
docker: Error response from daemon: mkdir /var/run/docker/libcontainerd/3b8a865856018a3998764015602d4ccefd0205c132737e5b7235d6ca5418aaeb: **no space left on device.**

ERRO[0000] error waiting for container: context canceled

~$ docker: Error response from daemon: mkdir
```
