### ISSUE TITLE
docker stack deploy and automated Common Post-Deployment Tasks

### ISSUE THREAD

**Issue by nguyenthaialan** [moby/moby#35900] opened 2017-12-29 14:55 UTC
How to after docker stack deploy command run Common Post-Deployment Tasks in my CI???!!!
Something similar to the docker-compose exec.

**Comment by thaJeztah** [comment] 2017-12-29 15:44
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2017-12-29 15:44 UTC
