### ISSUE TITLE
Docker pull fails consistently in rootless mode

### ISSUE THREAD

**Issue by DaveDunne** [moby/moby#41891] opened 2021-01-18 20:55 UTC
Ubuntu 20.04.1 LTS - 64 Bit 

Simply docker pull fails all the time

91b65e469d9a: Extracting [==================================================>]  37.54MB/37.54MB
ebca2667abd2: Download complete 
7dcbb0d6b4db: Download complete 
2aa779b8c40d: Download complete 
d9523f88ad67: Download complete 
failed to register layer: Error processing tar file(exit status 1): lchown /dev/initctl: no such file or directory

**Steps to reproduce the issue:**

**Describe the results you received:**

91b65e469d9a: Extracting [==================================================>]  37.54MB/37.54MB
ebca2667abd2: Download complete 
7dcbb0d6b4db: Download complete 
2aa779b8c40d: Download complete 
d9523f88ad67: Download complete 
failed to register layer: Error processing tar file(exit status 1): lchown /dev/initctl: no such file or directory

tried everything under the sun to make it work. Changed to overlay from overlay2 ... played with many configurations of /etc/subuid and etc/subgid

**Describe the results you expected:**

expect docker pull to work 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
 

```
docker version
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:11:26 2020
 OS/Arch:           linux/amd64
 Context:           rootless
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
docker info
Client:
 Context:    rootless
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.0-62-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.52GiB
 Name: IEDUB-3WT9SQ2-LNX
 ID: S6QM:QDPQ:4QC2:HLUM:NJJE:GCO3:YUPT:65DM:BENU:HLQY:EDZ4:BZGL
 Docker Root Dir: /home/dave.dunne/.local/share/docker
 Debug Mode: true
  File Descriptors: 23
  Goroutines: 39
  System Time: 2021-01-18T20:49:37.979712108Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment] 2021-01-19 02:39
Probably duplicate of https://github.com/moby/moby/issues/41803 . I'll analyze the issue ASAP

**Closed by AkihiroSuda** 2021-01-19 02:39 UTC
Labels: area/rootless, kind/bug
