### ISSUE TITLE
docker ps <service> lists tasks for all services starting with service name <service>

### ISSUE THREAD

**Issue by dvohra** [moby/moby#34265] opened 2017-07-26 20:21 UTC
https://github.com/docker/for-aws/issues/77

From docker/for-aws

**Comment by thaJeztah** [comment] 2017-07-27 00:15
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/32556 and already fixed on master through https://github.com/docker/cli/pull/72 (which will be included in docker 17.06.1)

I'll close this issue because this has been resolved, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-27 00:15 UTC
Labels: area/cli, kind/bug, version/17.06
