### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by liondancer** [moby/moby#31353] opened 2017-02-24 23:10 UTC
**Description**
I am using [clusterdock](https://github.com/cloudera/clusterdock) project by cloudera. I ran it fine. I later tried to `docker cp` a directory into the container launched. Shortly after, I received an error:

```
Error response from daemon: Error processing tar file(exit status 1):
...
...
... file name too long
```

**Steps to reproduce the issue:**
1. Create directory
2. docker cp directory {containerId}:.

**Describe the results you received:**
```
$ docker cp clink 2eca:.
Error response from daemon: Error processing tar file(exit status 1): open /clink/jobs/target/streams/$global/assemblyOption/$global/streams/assembly/82b354e42adbb42665af515b27b02de840e038ee_2df49b1995a6c8135f35e880f8876f7513ab872d_da39a3ee5e6b4b0d3255bfef95601890afd80709/org/scalacheck/ArbitraryArities$$anonfun$arbTuple11$1$$anonfun$apply$99$$anonfun$apply$100$$anonfun$apply$101$$anonfun$apply$102$$anonfun$apply$103$$anonfun$apply$104$$anonfun$apply$105$$anonfun$apply$106$$anonfun$apply$107$$anonfun$apply$108$$anonfun$apply$109.class: file name too long
```

**Describe the results you expected:**
Expected a bit of a wait time because the file and sub directories under the directory I was trying to `cp` has a large size

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 6
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 10.73 GiB
Name: moby
ID: IE7J:ATKG:7X72:VYNR:6VCX:5KGQ:KRNJ:FCU2:WMR7:2HTM:UNRT:O45E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 28
 System Time: 2017-02-24T23:09:24.060543919Z
 EventsListeners: 1
Username: liondancer
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ricardobranco777** [comment] 2017-03-06 14:28
I'm still experiencing this bug on Docker 17.03.

**Comment by thaJeztah** [comment] 2017-03-06 15:26
Could this have the same root cause as https://github.com/docker/docker/issues/29360#issuecomment-266884524 (https://github.com/golang/go/issues/17630) ?

/cc @dmcgowan

**Comment by ricardobranco777** [comment] 2017-03-06 15:38
PD:
I could copy /tmp/$(perl -e 'print "a"x242')

**Comment by ricardobranco777** [comment] 2017-03-30 20:03
Should Docker revert to the copying logic used in Docker 1.12?

**Comment by thaJeztah** [comment] 2017-03-30 21:06
Actually, I just tried reproducing this, but could not reproduce;

```bash
$ docker run -dit --name test ubuntu
2fae2338834ca74d0f44e5645ff40e3a6c99dab43a040169cdf8fd50aa30383c

$ touch /tmp/$(perl -e 'print "a"x255')

$ docker cp /tmp/$(perl -e 'print "a"x255') test:.

$ docker exec test ls -l
total 64
-rw-r--r--   1 root root    0 Mar 30 20:53 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
drwxr-xr-x   2 root root 4096 Dec 13 20:24 bin
drwxr-xr-x   2 root root 4096 Apr 12  2016 boot
drwxr-xr-x   5 root root  360 Mar 30 21:02 dev
drwxr-xr-x   1 root root 4096 Mar 30 21:02 etc
drwxr-xr-x   2 root root 4096 Apr 12  2016 home
drwxr-xr-x   8 root root 4096 Sep 13  2015 lib
drwxr-xr-x   2 root root 4096 Dec 13 20:24 lib64
drwxr-xr-x   2 root root 4096 Dec 13 20:23 media
drwxr-xr-x   2 root root 4096 Dec 13 20:23 mnt
drwxr-xr-x   2 root root 4096 Dec 13 20:23 opt
dr-xr-xr-x 134 root root    0 Mar 30 21:02 proc
drwx------   2 root root 4096 Dec 13 20:24 root
drwxr-xr-x   1 root root 4096 Dec 15 17:45 run
drwxr-xr-x   1 root root 4096 Dec 15 17:45 sbin
drwxr-xr-x   2 root root 4096 Dec 13 20:23 srv
dr-xr-xr-x  13 root root    0 Mar 30 20:56 sys
drwxrwxrwt   2 root root 4096 Dec 13 20:24 tmp
drwxr-xr-x   1 root root 4096 Dec 15 17:45 usr
drwxr-xr-x   1 root root 4096 Dec 15 17:45 var
```

Running on 

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 514
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: drfinwj2um6lv0pbprh0gzzfm
 Is Manager: true
 ClusterID: 1nfnet5qybgsy264nxp3of5tk
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 2C2P:6SIF:XUDN:A7BY:VSFT:74G2:G563:DGRE:3VRC:VL3Z:NY6P:BBJY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 50
 Goroutines: 172
 System Time: 2017-03-30T21:01:03.357160974Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

What platform are you on? Can you post `docker version` and `docker info`?

**Comment by ricardobranco777** [comment] 2017-03-30 21:13
docker version:

> Client:
>  Version:      17.03.1-ce
>  API version:  1.27
>  Go version:   go1.7.5
>  Git commit:   c6d412e
>  Built:        Fri Mar 24 00:45:26 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.03.1-ce
>  API version:  1.27 (minimum version 1.12)
>  Go version:   go1.7.5
>  Git commit:   c6d412e
>  Built:        Fri Mar 24 00:45:26 2017
>  OS/Arch:      linux/amd64
>  Experimental: false
> 

docker info:

> Containers: 10
>  Running: 8
>  Paused: 0
>  Stopped: 2
> Images: 778
> Server Version: 17.03.1-ce
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 1007
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: bridge host macvlan null overlay
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
> runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
> init version: 949e6fa
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.8.0-45-generic
> Operating System: Ubuntu 16.04.2 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 32
> Total Memory: 31.39 GiB
> Name: cl01
> ID: RKD3:6ILX:UBKH:O3QK:77RE:47B7:7NQY:ZITT:5QLF:4DVS:3SDC:ZKFL
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Comment by ricardobranco777** [comment] 2017-03-30 21:22
@thaJeztah I see you're using the **overlay2** storage driver and I'm using AUFS (4.x-rcN-20160912).  I've just tested with the **overlay** driver provided by Ubuntu and it worked.  The problems seems to be with AUFS.

**Comment by thaJeztah** [comment] 2017-03-30 22:14
@ricardobranco777 ah, thanks for that information, that would explain the difference. I was also looking at your output, and thinking of `apparmor`, I recall an issue where apparmor caused issues with long paths (don't think it were filenames though).

> overlay2 is not present

hm, that's odd, it should be supported on kernel 4.x kernels, does it produce an error if you manually select that driver? If possible, I would definitely recommend overlay2 over overlay, it has all the "positives" and fixes the "running out of inodes" issue

**Comment by ricardobranco777** [comment] 2017-03-30 22:22
**overlay2** is present.  It's just the name of the kernel driver that confused me.  I edited that part.

Is there any chance that this will get fixed on AUFS or should we all migrate to overlay2?

**Comment by thaJeztah** [comment] 2017-03-30 22:26
Overlay is definitely what we set our eyes on, would be good if we knew why it fails on aufs though; if it's the aufs kernel module, or the aufs storage driver in docker. It could still be related to https://github.com/docker/docker/issues/31353#issuecomment-284428317 (which may be fixed with Go 1.8; which we're testing, but cannot switch to yet due to some incompatible changes)

**Comment by ricardobranco777** [comment] 2017-04-17 21:42
@thaJeztah Should we add the `area/storage/aufs` label to this issue?

**Comment by cayleylz** [comment] 2017-05-07 22:35
You should try using the program Long Path Tool, it´s an easy fix for this kind of problem

**Comment by ricardobranco777** [comment] 2017-06-28 18:19
This issue persists in Docker 17.06.0-ce despite the migration to Go 1.8.3.

**Comment by thaJeztah** [comment] 2023-04-20 23:58
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS

**Closed by thaJeztah** 2023-04-20 23:58 UTC
Labels: area/storage/aufs, version/1.13
