### ISSUE TITLE
Communication not happening using dummy interface inside the container

### ISSUE THREAD

**Issue by anannaya** [moby/moby#29388] opened 2016-12-14 05:04 UTC
We are using linux bridges which is connected to the container, Inside the container we add the dummy0 interface to add some routes. In Normal case like bare-metal/VM this working as expected.  
How it is different from docker container?
We use the privileged & add all capabilities for container.

**Comment by anannaya** [comment] 2016-12-15 13:16
Hi,

Do you see any issue for using the dummy interface inside the container on RHEL 7.2.?

Br,
Anand

**Comment by sanimej** [comment] 2016-12-15 14:22
Why is a dummy interface required to add static routes ? Can you show the exact commands you are using and elaborate on what you mean by `Communication not happening` ? Is it the communication between two containers on the same network ?

Also, include the `docker version` output.

**Comment by anannaya** [comment] 2016-12-15 14:27
[root@dockerhost modprobe.d]# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

yes.. We use the dummy0 to add the static routes.
One problem is that arp table is not getting updated for the dummy0 plumbed ip?

How the dummy driver behavior chnages inside the previleged container?
Please support on this.

**Comment by justincormack** [comment] 2016-12-15 19:20
Inside a network namespace there are no routes from outside except via `veth` pairs. The whole point is network isolation. If you want the same behaviour you can run with `--net=host` which will not isolate the container network at all. It is hard to know what to recommend without knowing what you are trying to achieve.

**Comment by anannaya** [comment] 2016-12-16 04:15
@justincormack  dummy driver is also part of network stack correct.?  I was able to create a interface and plumb the ip address also as well on the dummy interface. 
#ip link add dummy0 typ dummy
#ip a a 10.253.17.8/23 dev dummy0

I am trying to ping the ip address in the same network.  Some how i root cause the problem arp table is not ageeting updated.. Is it a expected behavior on the container environment?

**Comment by justincormack** [comment] 2016-12-16 04:20
Every container has its own network stack.

You really need to explain what you are doing in a fully reproducible way
from scratch, I don't know if your commands are in a container or not, and
how your environment is set up, so I am just guessing.

**Comment by anannaya** [comment] 2016-12-16 04:33
Hi @justincormack 

Background:
I am running the privileged container with all the capabilities on top the rhel7.2 custom image.
I have created the linux bridge "brctl" connected the veth interface inside the container using the nsenter.

After veth attach "eth0"  interface is visible inside the container. Example:
ip  plumbed on the eth0 is the static ip which is mainly used for containers communication. I have one clustering service inside the container which will plumb the virtual ip on the dummy interface depending on the Cluster Active status.

**Comment by anannaya** [comment] 2016-12-16 05:02
Please suggest me anything wrong with my setup.

**Comment by justincormack** [comment] 2016-12-16 05:08
Can you give an exact executable script to reproduce. I am still guessing
what you are actually doing.

**Comment by anannaya** [comment] 2016-12-16 05:55
I dont have the exact script, Below are simple command u can reproduce. All are on linux RHEL7.2

On DockerHost:
#docker run -td --privileged <imageName>
#brctl addbr <bridgename>
#brctl addif <bridgename> <interfacename>
#ip link add name <hostvethinterface> type veth peer name <containervethinterface>
#ip link set <hostvethinterface> up
#ip link set <containervethinterface> netns <pidof the container>
#nsenter -t <pidof the container> -n ip link set <containervethinterface name eth0
#brctl addif <bridgename><hostvethinterface>

Inside the Container:
#docker exec -it <containerid> bash
#ip addr add <ip0> dev eth0
#ip link add dev dummy0 type dummy
#ip addr add <ip1> dev dummy0

Now comes to the problem:
I am able to ping same network outside from the container through ip0 like
#ping -I <ip0> ipx

If i try to ping the ip from the dummy ip1 which is not working.
#ping -I <ip1> ipx

Pls suggest me why this behaviour.  If i plumb the <ip1> to eth0 ..it works... Why only on dummy interface it is not working?

**Comment by justincormack** [comment] 2016-12-16 06:10
Please be more exact.

You are saying that
#ping -l ipx
Is working but
#ping -l ipx
does not.

This is really hard to understand. I am sure it is clear to you but you
have to explain it to someone who can only see two identical pings.

With networking problems, unless you can write a script to reproduce them
or you provide detailed routing information you are unlikely to get anyone
to solve your issues.

**Comment by sanimej** [comment] 2016-12-16 06:17
@justincormack anannaya updated his previous comment.. 
```
Now comes to the problem:
I am able to ping same network outside from the container through ip0 like
#ping -I {ip0} ipx

If i try to ping the ip from the dummy ip1 which is not working.
#ping -I {ip1} ipx
```

Its not clear where `ipx` is. May be an IP in the host. But this is expected because `eth0` in the container is one end of the veth pair which he has connected to the bridge. But the `dummy` interface is not. So the packet originated from within the container has no way to each `ipx`.

**Comment by anannaya** [comment] 2016-12-16 06:20
@justincormack : thanks for the response
ok.. 
Example:
Inside the Conatiner:
ip addr add 10.255.14.98/24 dev eth0
ip link add dev dummy0 type dummy
ip addr add 10.255.14.99/24 dev dummy0
ip link set dummy0 up


Now i am trying to ping the one more container which has the ip address 10.255.14.100/24
#ping -I 10.255.14.98 10.255.14.100 (it works)
#ping -I 10.255.14.99 10.255.14.100 (not working) 

Please let me know if these steps are not clear.

**Comment by anannaya** [comment] 2016-12-16 06:21
@sanimej  I have updated in the above comment.. Please let me know..any info required.

**Comment by justincormack** [comment] 2016-12-16 06:31
These steps are not clear. When you say "ping" I have no idea if you mean
from the host or the container. I cannot see how your network is set up.

By a reproducible script, I mean an exact set of instructions I can run
which will make the exact set of containers run the same commands.


On 15 Dec 2016 22:20, "anannaya" <notifications@github.com> wrote:

@justincormack <https://github.com/justincormack> : thanks for the response
ok..
Example:
Inside the Conatiner:
ip addr add 10.255.14.98/24 dev eth0

ip link add dev dummy0 type dummy
ip addr add 10.255.14.99/24 dev dummy0
ip link set dummy0 up

Now i am trying to ping the one more container which has the ip address
10.255.14.100/24
#ping -I 10.255.14.98 10.255.14.100 (it works)
#ping -I 10.255.14.99 10.255.14.100 (not working)

Please let me know if these steps are not clear.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/29388#issuecomment-267525794>, or mute
the thread

**Comment by anannaya** [comment] 2016-12-16 06:34
ip address are plumbed inside the container.. I am pinging from the container..
Those are exact and clear each and every commands i have mentioned in the top container.

**Comment by justincormack** [comment] 2016-12-16 07:13
yes @sanimej comment details the issue.

**Comment by anannaya** [comment] 2016-12-16 07:19
I monted the /lib/modules/ inside the container ..Tried the modeprobe dummy.. rmmod dummy,insmod dummy inside the container.. Nothing helped.

**Comment by anannaya** [comment] 2016-12-16 08:36
@sanimej  and @justincormack  : Do you see any issue specific to container environment?

**Comment by anannaya** [comment] 2016-12-16 09:57
@thaJeztah  Do you still need any more info ?

**Comment by anannaya** [comment] 2016-12-19 06:11
Hi @sanimej  and @justincormack  ,

Do you see any issues here, ?dummy also part of same network stack..then it should also work inside the container as well.

Br,
Anand

**Comment by justincormack** [comment] 2016-12-19 07:04
Containers have their own network stack, so no it is not the same as
creating interfaces on the host.


On 19 Dec 2016 6:11 a.m., "anannaya" <notifications@github.com> wrote:

Hi @sanimej <https://github.com/sanimej> and @justincormack
<https://github.com/justincormack> ,

Do you see any issues here, ?dummy also part of same network stack..then it
should also work inside the container as well.

Br,
Anand

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/29388#issuecomment-267889414>, or mute
the thread

**Comment by anannaya** [comment] 2016-12-19 07:24
Yes.. I know that.. But dummy also part of network stack right?
Why isn't working ?

How do i overcome this issue.

**Comment by thaJeztah** [comment] 2017-10-31 21:14
Closing this issue, as I don''t think there's a bug at hand here, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-31 21:14 UTC
Labels: area/networking, status/more-info-needed
