### ISSUE TITLE
Mounting a Docker image into a container

### ISSUE THREAD

**Issue by mitar** [moby/moby#37114] opened 2018-05-21 02:37 UTC
This is a feature request. I would like to distribute some larger static files/assets as a Docker image so that it is easy for user to pull those optional files down the same way they would be pulling the app itself. But I cannot really find a good way to expose files from one Docker image to the other container? I think the  a way to mount a Docker image itself (or a directory in it) as a volume to other Docker container would be a great way to do it.

I know that there are volume plugins I could use, but I could not find any where I could to this or something similar? It seems like this could be a simple case to cover maybe. But ideally, this could also be something a part of Docker core.

**Comment by cpuguy83** [comment] 2018-05-21 15:14
I agree that being able to mount an image would be nice. At least the API to do this would be fairly simple, I'm not sure about the lower level bits without looking into it.

There is a way to do this today without any extra tooling. If you run a container with an empty volume, the content of the image at the volume path will be copied into the volume. This volume can then be used by whatever needs to access those static assets.

**Comment by thaJeztah** [comment] 2018-05-21 15:19
This looks like a duplicate of https://github.com/moby/moby/issues/30449 - let me close this one to prevent the discussion from diverging, but feel free to participate in the discussion over there :+1:

**Closed by thaJeztah** 2018-05-21 15:19 UTC

**Comment by mitar** [comment] 2018-05-21 16:36
> If you run a container with an empty volume, the content of the image at the volume path will be copied into the volume.

Oh, I didn't know that this happens. I thought a new empty volume will be mounted there. This is at least what happened to me in the past?

**Comment by cpuguy83** [comment] 2018-05-21 17:03
This has always been the bahavior for volumes, but does not happen for bind
mounts.

**Comment by mitar** [comment] 2018-05-21 17:26
Oh, so if I create an image with `VOLUME /data` and then after that if I put data inside Docker build process into `/data`, then does this mean that because during container run, volume is automatically created, that also data will be automatically put there? Is data copied from image or mounted into the volume?

**Comment by cpuguy83** [comment] 2018-05-21 17:52
`VOLUME /data` is the same as `-v /data`.
It causes each subsequent `RUN` command to create an anonymous volume which is and attach it to `/data`. If there was any data in `/data` it will be copied into this anonymous volume.

**Comment by mitar** [comment] 2018-05-21 23:43
Cool, it really works. but the issue is that it copies data over. Which in might case might mean 90 GB of data duplicated unnecessary. #30449 seems like it could resolve this.

Thanks!
