### ISSUE TITLE
Support for volume :z and :Z flags for swarm/stack deployment

### ISSUE THREAD

**Issue by eriklogtenberg** [moby/moby#36282] opened 2018-02-11 18:57 UTC
When I mount a docker volume (with the rbd-docker-plugin) on an SELinux enabled host, I require the :Z flag for the container to gain access to the volume.
In 2016 this flag was introduced: https://github.com/eclipse/che/pull/2921
Unfortunately, it seems that in Swarm/Stack deployment, this flag is not supported. I cannot find any such flags in the documentation: https://docs.docker.com/compose/compose-file/#volumes
When I apply the short syntax and just include the :Z flag like I would with `docker run`, it seemingly gets ignored and the volume isn't labelled, so the container doesn't get access.

Workarounds include:
- Disabling SELinux
- All very permissive SELinux policy like this: `allow container_t unlabeled_t:dir read;`
Workarounds are clearly not desirable.

Kind request to include support for :Z (and :z) flags for volume mounts in Swarm/Stack mode.

**Comment by cpuguy83** [comment] 2018-02-12 11:38
Support for this functionality is purposefully omitted.
If you intend to use a host dir in a container you should set it to the desired label on the host.

Closing since this is working as designed, but feel free to discuss.
Thanks! 🙇‍♂️👼

**Closed by cpuguy83** 2018-02-12 11:38 UTC

**Comment by eriklogtenberg** [comment] 2018-02-12 11:45
Thank you for replying. I do not understand your feedback though. The rbd-docker-plugin works by dynamically mapping a Ceph stored RBD device to a local device on the host (`/dev/rbd0` for instance) and giving access to that device to the container. If swarm decides to stop this container and spin up a new one on another host, the rbd-docker-plugin unmaps the RBD device on this host and maps on the other host.
Is this not how Docker Volumes are supposed to work?

In any case, the container has no access to this `/dev/rbd0` device unless it is labelled correctly, and since it's only created when the container is started, I cannot pre-emptively label it manually, nor do I think Swarm was intended to require such manual labor on every redeploy of a container.

**Comment by cpuguy83** [comment] 2018-02-12 14:17
@eriklogtenberg How does this work without swarm? The host path needs to be labeled properly.
The fact that the z/Z options exist was a mistake really and only really exist because `-v /foo:/bar` will `mkdir /foo` if it doesn't exist.
Swarm does not support auto-creation of host paths (also intentional).

The idea here is if you are mounting something in from the host then it must exist and it must be properly labeled since you created it.

I'm not sure how the rbd driver works, is it mounting in a device from the host?
