### ISSUE TITLE
"docker search" does not provide a way to filter on architecture.

### ISSUE THREAD

**Issue by pgayvallet** [moby/moby#36205] opened 2018-02-05 13:27 UTC
**Description**

Users on windows container mode (docker for windows) have to way to see if images displayed from `docker search` results are compatible with their architecture (see https://github.com/docker/for-win/issues/1658 for example)

**Steps to reproduce the issue:**
1. Install docker4win
2. Enable windows containers
3. Search for images using `docker search` (`Docker search mysql` is a good example)

```
docker search mysql
NAME DESCRIPTION STARS OFFICIAL AUTOMATED
mysql MySQL is a widely used, open-source relation… 5657 [OK]
mariadb MariaDB is a community-developed fork of MyS… 1755 [OK]
mysql/mysql-server Optimized MySQL Server Docker images. Create… 389 [OK]
hypriot/rpi-mysql RPi-compatible Docker Image with Mysql 78
zabbix/zabbix-server-mysql Zabbix Server with MySQL database support 75 [OK]
centurylink/mysql Image containing mysql. Optimized to be link… 58 [OK]
zabbix/zabbix-web-nginx-mysql Zabbix frontend based on Nginx web-server wi… 41 [OK]
tutum/mysql Base docker image to run a MySQL database se… 31
1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5 ubuntu-16-nginx-php-phpmyadmin-mysql-5 25 [OK]
mysql/mysql-cluster Experimental MySQL Cluster Docker images. Cr… 19
centos/mysql-57-centos7 MySQL 5.7 SQL database server 17
schickling/mysql-backup-s3 Backup MySQL to S3 (supports periodic backup… 16 [OK]
linuxserver/mysql A Mysql container, brought to you by LinuxSe… 14
zabbix/zabbix-proxy-mysql Zabbix proxy with MySQL database support 10 [OK]
centos/mysql-56-centos7 MySQL 5.6 SQL database server 7
openshift/mysql-55-centos7 DEPRECATED: A Centos7 based MySQL v5.5 image… 6
dsteinkopf/backup-all-mysql backup all DBs in a mysql server 3 [OK]
circleci/mysql MySQL is a widely used, open-source relation… 3
frodenas/mysql A Docker Image for MySQL 3 [OK]
cloudfoundry/cf-mysql-ci Image used in CI of cf-mysql-release 0
inferlink/landmark-mysql landmark-mysql 0 [OK]
openzipkin/zipkin-mysql Mirror of https://quay.io/repository/openzip… 0
cloudposse/mysql Improvedmysqlservice with support for m… 0 [OK]
ansibleplaybookbundle/mysql-apb An APB which deploys RHSCL MySQL 0 [OK]
astronomerio/mysql-sink MySQL sink 0 [OK]
```

4. try to pull the image found using previous search command      

```
docker pull mysql
Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for windows/amd64 in the manifest list entries
```

**Describe the results you received:**

cli list available mysql images. But none would be usable on my architecture, nor have I any way to see which one would be usable or not on my arch.

**Describe the results you expected:**

Either a way to filter results  by architecture, or a way to have the arch information available on the results list.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

```
 docker version
Client:
 Version:       18.02.0-ce-rc1
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    5e1d90a
 Built: Thu Jan 25 00:34:00 2018
 OS/Arch:       windows/amd64
 Experimental:  true
 Orchestrator:  kubernetes

Server:
 Engine:
  Version:      18.02.0-ce-rc1
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   5e1d90a
  Built:        Thu Jan 25 00:40:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Output of `docker info`:**

```
docker version
Client:
 Version:       18.02.0-ce-rc1
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    5e1d90a
 Built: Thu Jan 25 00:34:00 2018
 OS/Arch:       windows/amd64
 Experimental:  true
 Orchestrator:  kubernetes

Server:
 Engine:
  Version:      18.02.0-ce-rc1
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   5e1d90a
  Built:        Thu Jan 25 00:40:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
PS C:\Users\pierr\DEV\workspaces\gopath\src\github.com\docker\pinata\win> docker info
Containers: 21
 Running: 18
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 18.02.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d003e54
ID: T6SF:R42M:2VM4:UUZA:4EPC:VOPF:O6KK:7URW:ECH6:ZXRX:OOPN:LNFE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 116
 Goroutines: 112
 System Time: 2018-02-05T13:22:48.940231Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by duglin** [comment] 2018-02-05 13:39
try: http://soaphub.org/imagehub
"mysql" is a bad choice to test it since there are 10k results, so it takes a while to load, but if you try another image (or look for official ones) then the result set is smaller.

**Comment by pgayvallet** [comment] 2018-02-05 15:40
@duglin issue is not about how to find proper images to use for an arch, but specifically about the fact that `docker search` does not provide a way to filter/identify images for the user's arch.

**Comment by duglin** [comment] 2018-02-05 15:42
understood - was just providing an alternative since searching by OS and/or arch is nontrivial on dockerhub

**Comment by thaJeztah** [comment] 2023-09-17 19:49
- duplicate of https://github.com/moby/moby/issues/25417

**Closed by thaJeztah** 2023-09-17 19:49 UTC
Labels: area/distribution, platform/desktop, platform/arm
