### ISSUE TITLE
Image build fails and trapped into infinite loop

### ISSUE THREAD

**Issue by 22nishant** [moby/moby#41113] opened 2020-06-16 02:59 UTC
**Description**
While building the image using a Dockerfile given below, the build image process stuck into infinite loop and not exited successfully with providing error code. The only reason behind this issue is the command "RUN apt-get purge --allow-remove-essential --yes tar" written in the Dockerfile. 

I have verified this instruction on different base images available at Dockerhub. The base images which I tried are: ubuntu:18.04, ubuntu:16.04, ubuntu:latest, debian:buster-slim. This reported issue happened only with ubuntu:18.04 and ubuntu:16.04. However, in other cases, the images didn't built successfully and return a non zero code 100.

**Steps to reproduce the issue:**
1. Create a Dockerfile which has only two statements.
2. First statement in  Dockerfile correspond to base image selection by writing FROM statement and the base image will be either  ubuntu:18.04 or ubuntu:16.04.
3. Second statement correspond to writing the instruction to uninstall tar which is as such:
RUN apt-get remove --allow-remove-essential -y tar
4. Run the $docker build command to build the image by using Dockerfile written above.
  

**Describe the results you received:**
Docker build process trapped into infinite loop and displaying the information present at end infinitely:
```
$ sudo docker build -t image:v1 .

Sending build context to Docker daemon  49.15kB
Step 1/2 : FROM ubuntu:18.04
 ---> c3c304cb4f22
Step 2/2 : RUN apt-get purge --allow-remove-essential --yes tar
 ---> Running in 7ae2135d1b6e
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  adduser* apt* dash* debconf* dpkg* grep* gzip* init-system-helpers*
  libpam-modules* libpam-modules-bin* libpam-runtime* libpam0g* login* mount*
  passwd* perl-base* procps* sysvinit-utils* tar* util-linux*
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  apt adduser (due to apt) dash dpkg (due to dash) tar (due to dpkg) grep gzip
  init-system-helpers perl-base (due to init-system-helpers) login
  libpam0g (due to login) libpam-runtime (due to login)
  libpam-modules (due to login) mount util-linux (due to mount) sysvinit-utils
0 upgraded, 0 newly installed, 20 to remove and 0 not upgraded.
After this operation, 32.3 MB disk space will be freed.
(Reading database ... 4046 files and directories currently installed.)
Removing apt (1.6.12) ...
Removing adduser (3.116ubuntu1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing dash (0.5.8-2.10) ...
Removing 'diversion of /bin/sh to /bin/sh.distrib by dash'
dpkg-divert: error: rename involves overwriting '/bin/sh' with
  different file '/bin/sh.distrib', not allowed
dpkg: error processing package dash (--remove):
 installed dash package pre-removal script subprocess returned error exit status 2
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing login (1:4.5-1ubuntu2) ...
Removing passwd (1:4.5-1ubuntu2) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing sysvinit-utils (2.88dsf-59.10ubuntu1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing libpam-runtime (1.1.8-3.6ubuntu2.18.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
PAM configuration
-----------------

Pluggable Authentication Modules (PAM) determine how authentication,
authorization, and password changing are handled on the system, as well as
allowing configuration of additional actions to take when starting user
sessions.

Some PAM module packages provide profiles that can be used to automatically
adjust the behavior of all PAM-using applications on the system.  Please
indicate which of these behaviors you wish to enable.

  1. Create home directory on login

(Enter the items you want to select, separated by spaces.)

PAM profiles to enable: 
Use of uninitialized value $_[1] in join or string at /usr/share/perl5/Debconf/DbDriver/Stack.pm line 111.
No PAM profiles have been selected.

No PAM profiles have been selected for use on this system.  This would grant
all users access without authenticating, and is not allowed.  Please select at
least one PAM profile from the available list.

Pluggable Authentication Modules (PAM) determine how authentication,
authorization, and password changing are handled on the system, as well as
allowing configuration of additional actions to take when starting user
sessions.

Some PAM module packages provide profiles that can be used to automatically
adjust the behavior of all PAM-using applications on the system.  Please
indicate which of these behaviors you wish to enable.

  1. Create home directory on login

(Enter the items you want to select, separated by spaces.)

PAM profiles to enable: 
Use of uninitialized value $_[1] in join or string at /usr/share/perl5/Debconf/DbDriver/Stack.pm line 111.
No PAM profiles have been selected.

No PAM profiles have been selected for use on this system.  This would grant
all users access without authenticating, and is not allowed.  Please select at
least one PAM profile from the available list.

Pluggable Authentication Modules (PAM) determine how authentication,
authorization, and password changing are handled on the system, as well as
allowing configuration of additional actions to take when starting user
sessions.

Some PAM module packages provide profiles that can be used to automatically
adjust the behavior of all PAM-using applications on the system.  Please
indicate which of these behaviors you wish to enable.

  1. Create home directory on login

(Enter the items you want to select, separated by spaces.)

PAM profiles to enable: 
Use of uninitialized value $_[1] in join or string at /usr/share/perl5/Debconf/DbDriver/Stack.pm line 111.
No PAM profiles have been selected.

No PAM profiles have been selected for use on this system.  This would grant
all users access without authenticating, and is not allowed.  Please select at
least one PAM profile from the available list.

Pluggable Authentication Modules (PAM) determine how authentication,
authorization, and password changing are handled on the system, as well as
allowing configuration of additional actions to take when starting user
sessions.

Some PAM module packages provide profiles that can be used to automatically
adjust the behavior of all PAM-using applications on the system.  Please
indicate which of these behaviors you wish to enable.
```
```

$ cat Dockerfile

FROM ubuntu:18.04

RUN apt-get purge --allow-remove-essential --yes tar 
```

**Describe the results you expected:**

The expected result should be either build successfully if the instructions written in the Dockerfile has not any issue, otherwise, the docker build process should exit by giving the error code and display the message that image building is failed by employing the given Dockerfile. However, this expected result is produced in case of ubuntu:latest and debian:buster-slim base image but not in the case of ubuntu 18.04 and ubuntu:16.04.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried to execute the command "apt-get purge --allow-remove-essential --yes tar" directly inside the base image ubuntu:18.04, ubuntu:16.04 and ubutnu:latest. After running the command, it was asking some information about "PAM profile to enable". The execution of the coomand has been stopped by pressing ctrl+z and it was stopped successfullly. After that, I am unable to give any input from terminal and also unable to exit the container by using "exit" statement or by employing ctrl+c or ctrl+z. Lastly, the current terminal has been closed by employing only one option which is directly close the terminal by clicking on "cross" button. However this situation is not arisisng in the case of ubuntu:latest.

```
$ docker run -it --entrypoint "/bin/sh" ubuntu:18.04 
# apt-get purge --allow-remove-essential --yes tar
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  adduser* apt* dash* debconf* dpkg* grep* gzip* init-system-helpers* libpam-modules* libpam-modules-bin* libpam-runtime* libpam0g* login* mount* passwd* perl-base* procps* sysvinit-utils* tar* util-linux*
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  apt adduser (due to apt) dash dpkg (due to dash) tar (due to dpkg) grep gzip init-system-helpers perl-base (due to init-system-helpers) login libpam0g (due to login) libpam-runtime (due to login) libpam-modules (due to login)
  mount util-linux (due to mount) sysvinit-utils
0 upgraded, 0 newly installed, 20 to remove and 0 not upgraded.
After this operation, 32.3 MB disk space will be freed.
(Reading database ... 4046 files and directories currently installed.)
Removing apt (1.6.12) ...
Removing adduser (3.116ubuntu1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing dash (0.5.8-2.10) ...
Removing 'diversion of /bin/sh to /bin/sh.distrib by dash'
dpkg-divert: error: rename involves overwriting '/bin/sh' with
  different file '/bin/sh.distrib', not allowed
dpkg: error processing package dash (--remove):
 installed dash package pre-removal script subprocess returned error exit status 2
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing login (1:4.5-1ubuntu2) ...
Removing passwd (1:4.5-1ubuntu2) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing sysvinit-utils (2.88dsf-59.10ubuntu1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: this is an essential package; it should not be removed
Removing libpam-runtime (1.1.8-3.6ubuntu2.18.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
PAM configuration
-----------------

Pluggable Authentication Modules (PAM) determine how authentication, authorization, and password changing are handled on the system, as well as allowing configuration of additional actions to take when starting user sessions.

Some PAM module packages provide profiles that can be used to automatically adjust the behavior of all PAM-using applications on the system.  Please indicate which of these behaviors you wish to enable.

  1. Create home directory on login

(Enter the items you want to select, separated by spaces.)

PAM profiles to enable: 

No PAM profiles have been selected.

No PAM profiles have been selected for use on this system.  This would grant all users access without authenticating, and is not allowed.  Please select at least one PAM profile from the available list.

Pluggable Authentication Modules (PAM) determine how authentication, authorization, and password changing are handled on the system, as well as allowing configuration of additional actions to take when starting user sessions.

Some PAM module packages provide profiles that can be used to automatically adjust the behavior of all PAM-using applications on the system.  Please indicate which of these behaviors you wish to enable.

  1. Create home directory on login

(Enter the items you want to select, separated by spaces.)

PAM profiles to enable: 

No PAM profiles have been selected.

No PAM profiles have been selected for use on this system.  This would grant all users access without authenticating, and is not allowed.  Please select at least one PAM profile from the available list.

Pluggable Authentication Modules (PAM) determine how authentication, authorization, and password changing are handled on the system, as well as allowing configuration of additional actions to take when starting user sessions.

Some PAM module packages provide profiles that can be used to automatically adjust the behavior of all PAM-using applications on the system.  Please indicate which of these behaviors you wish to enable.

  1. Create home directory on login

(Enter the items you want to select, separated by spaces.)

PAM profiles to enable: [1] + Stopped                    apt-get purge --allow-remove-essential --yes tar
                                                                                                         # 
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 10
  Running: 3
  Paused: 0
  Stopped: 7
 Images: 96
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-53-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 22.11GiB
 Name: ubuntu
 ID: G5G7:FN4M:VYVX:7I7M:XO4Y:3KAA:PMP2:A5TK:WPOC:Y6RN:UINL:IXNA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker runs in ubutnu18.04 Virtual Machine. The details of OS is as follows:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
The detail of kernel is as follows:
```
$ uname -mrs
Linux 5.3.0-53-generic x86_64
```

**Comment by thaJeztah** [comment] 2020-06-16 10:54
Looks like that step cannot be performed non-interactive, as it requires a value to be passed;

```
No PAM profiles have been selected for use on this system.  This would grant all users access without authenticating, and is not allowed.  Please select at least one PAM profile from the available list.
```

I gave this a quick try to see if using `DEBIAN_FRONTEND=noninteractive` worked, but same result


```dockerfile
FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get purge --allow-remove-essential --yes tar
```

This is not an issue with the docker builder tough, but an issue with the software running inside the container. I found some earlier discussion on this in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=601825, and possibly http://manpages.ubuntu.com/manpages/bionic/man8/pam-auth-update.8.html provides some information to programmatically set a PAM profile.

I'm closing this issue because this is not a bug in Docker, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-16 10:54 UTC

**Comment by 22nishant** [comment] 2020-06-16 12:54
Thanks for your time! I do understand the steps cannot be performed because it requires some values from user. My analogy is as follows:
Consider the following Dockerfile:
-----------------------------------
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get upgrade

------------------------------------
If I want to build the image using the above Dockerfile, the build process will be failed and display error message and error code, for example, "returned a non-zero code: 1". It happens because 3rd instruction "RUN apt-get upgrade" requires a value which will be either "yes" or "no". if we replace the instruction "RUN apt-get upgrade" with "RUN apt-get upgrade --yes", then image build will be successful. 
Similar analogy, we can apply here also. The instruction I reported here which creates problem is "RUN apt-get purge --allow-remove-essential --yes tar". It requires some values from user, thus, in this case docker build process should be exited nicely and display error code.  Docker build process should have enough robustness to handle such instruction, instead of trapping inside infinite loop.

Even, we can consider this issue as dynamic code analysis problem where we attempt to fuzz the docker image build process with random inputs and check that the process is behaving as expected or not. Here, image build process has only two expectations. Either it will build the image successfully or it will exit successfully in case of the image building is failed. But in my case, it is behaving not as expectation and went inside infinite loop.

**Comment by thaJeztah** [comment] 2020-06-16 13:07
A container (in this case a container that's started as part of the build) exits it it's main process exits. In case of `docker build`, the build is terminated if the process exits with a non-zero exit status. In this case, the process does not exit, it keeps retrying, and as such, the container (and thus docker) has no way to know if it's just a long running process, or a (potential) problem situation.

On a side-note; it's generally not recommended to run `apt-get upgrade` in a Dockerfile; instead, make sure you always pull the latest version of the base-image (`docker build --pull`).

**Comment by 22nishant** [comment] 2020-06-16 13:44
I do agree with your point. I am summarizing the points you mentioned. Docker image is created layer wise and while building the image, multiple intermediate containers will be created and finally target container will be created. This is true for Dockerfile written in last comment also. If one want to experience with "apt-get upgrade" instruction return code, then write the instruction in a shell script and run that script. It will not return any error code and wait for providing some input. So, it is not the problem with the process running the instruction.
However, it is problem with intermediate container which is not exiting successfully and went inside infinite loop. I do understand that the problem is coming obviously due to the process which is running the instruction "RUN apt-get purge --allow-remove-essential --yes tar".  It doesn't mean that docker build will go inside infinite loop due to some intermediate container. If it has to go inside the infinite loop  due to improper instruction written in Dockerfile, then it should true for Dockerfile written in last comment. 

My point is that if docker build process is not providing any way to provide input to the process which is running inside intermediate container then it should not go inside infinite loop and stuck the process. The way docker build handle it for Dockerfile written in last comment should be consistent for any Dockerfile

On a side not, I have taken as an example of "RUN apt-get upgrade" instruction. We can take another example also like "RUN apt-get install curl". It also requires input while running and it will also exit successfully if "--yes" parameter is missing in the instruction. It will not go inside the infinite loop.

**Comment by thaJeztah** [comment] 2020-06-16 14:38
> My point is that if docker build process is not providing any way to provide input to the process which is running inside intermediate container then it should not go inside infinite loop and stuck the process

The issue in this case is that the `apt-get purge --allow-remove-essential --yes tar` does not (properly) handle running non-interactive; it attempts to purge the package, asks for input, either detects it's non-interactive, or continues because `--yes` is passed, then detects the input doesn't satisfy the requirements, and instead of failing (which it should), it tries again.

From Docker's perspective it's just a long (in this case "indefinitely") running process. Docker doesn't do a "loop"; it's still the same process that was started that's running.
