### ISSUE TITLE
docker-engine install hangs when linux-image-extra package missing

### ISSUE THREAD

**Issue by watchwithmike** [moby/moby#24478] opened 2016-07-09 03:33 UTC
**Summary**
`sudo apt-get install docker-engine` hangs when a suitable `linux-image-extra` package is not installed, .
**Step to reproduce the issue:**
1. Install Ubuntu 16.04
2. [Install Kernel 4.6.0](http://ubuntuhandbook.org/index.php/2016/05/install-linux-kernel-4-6-ubuntu-16-04/)
3.  Follow [Docker Engine installation instructions](https://docs.docker.com/engine/installation/linux/ubuntulinux/)
   - **Observe:** no `linux-image-extra` package available for `4.6.0-040600-generic`
   - **Observe:** `sudo apt-get install docker-engine` hangs.
4. While `dpkg` is hung:
   - **Observe:** `/bin/sh /var/lib/dpkg/info/docker-engine.postinst configure` is the hung process.
   - **Observe:** `sudo service docker status` shows the docker engine never finishes starting up.

As described in #23968, setting the `storage-driver` to `overlay` lets the docker service start up successfully.

**Possible Solutions**
When installing docker-engine check for the existence of the `linux-image-extra` package (or just `aufs`?):
- Update the startup script to include the `--storage-driver=overlay` flag.
- Update the startup script to create `/etc/docker/daemon.json` file to include the `storage-driver` setting.
- Prevent the docker service from starting with a message indicating required dependencies are missing.

**Comment by thaJeztah** [comment] 2016-07-09 19:57
/cc @tianon @kencochrane 

(thanks for opening a separate issue @watchwithmike)

**Comment by kencochrane** [comment] 2016-07-11 14:55
I think the best solution is to check if `linux-image-extra` or `aufs` is available, and if not, give a warning message saying they need to satisfy those requirements to continue, or use the overlay storage driver, and give a helpful tip on how to use overlay if they want.

This allows us to keep the script so it functions the same way, but gives people better error messages and tips on how to move forward if they are stuck.

What do others think?

**Comment by watchwithmike** [comment] 2016-07-11 17:07
I think this is great if the message occurs as part of the service start up rather than the install script.  The biggest thing is getting `dpkg` to exit gracefully which I think would happen after the warning message based on what your proposal.

**Comment by tianon** [comment] 2016-07-15 23:54
Whoa, this is a really bizarre one -- any more details in the Docker service logs? (either in `/var/log/docker.log` or `journalctl -u docker.service`, depending on whether your system uses systemd)

Docker should automatically determine that `aufs` is not available and fall back to `overlay` without any interaction. :disappointed:

**Comment by thaJeztah** [comment] 2016-07-16 00:02
@tianon I think this may be after a kernel update (people reporting this upgraded the default (4.2?) kernel to 4.6. Possibly the linux-image-extra package for 4.2 was still there, making the detection (during installation) go crazy.

^^ just some thoughts, perhaps it doesn't make sense at all :joy:

**Comment by gschlager** [comment] 2016-08-11 19:27
Same thing happens on Ubuntu 16.04 on [Linode](https://www.linode.com/) which currently uses Kernel 4.6 as default. There's no `linux-image-extra` package with `aufs` installed.

The installation of Docker 1.12 hangs because it wants to use `aufs`. Manually setting the storage driver to `overlay` or `overlay2` and restarting the aborted installation works. But that shouldn't be necessary. It should automatically use an available storage driver or at least show a warning and finish the installation.

**Comment by thaJeztah** [comment] 2016-08-11 19:45
It's strange that they have kernel 4.6 as a default, because that's not the standard kernel for Ubuntu 16.04. Possibly a `linux-image-extra-virtual` package works in that case (see https://github.com/docker/docker/pull/25614), although it's possible kernel 4.6 doesn't have a package yet for aufs (@tianon?)

> The installation of Docker 1.12 hangs because it wants to use aufs. ... But that shouldn't be necessary. It should automatically use an available storage driver

That should only happen if device mapper also isn't available on the server (which also should be available by default), however, I noticed there's a bug/inconsistency in the device mapper driver that doesn't properly check if dependencies are available, therefore it's not skipped as an unsupported driver, but attempts to initialize before failing, and erring out (resulting in `overlay` not being used 😞 ), see for that the discussion on https://github.com/docker/docker/pull/25411

**Comment by tianon** [comment] 2016-08-11 19:48
AUFS + 4.6 is possible (
https://github.com/sfjro/aufs4-standalone/tree/aufs4.6), but doesn't Linode
use custom kernel packages? (They used to IIRC.)

**Comment by gschlager** [comment] 2016-08-11 19:53
Yes, Linode uses a custom 4.6 kernel by default and there's no aufs  support compiled in. It's possible that devicemapper isn't working either. I'd have to check...

**Comment by tedivm** [comment] 2016-10-02 18:11
Yeah I can confirm that this bug is still present. This crappy packaging/testing of this package basically hangs apt.

**Comment by tedivm** [comment] 2016-10-02 18:14
@gschlager how do you change the storage driver before the package is finished installing?

**Comment by tedivm** [comment] 2016-10-02 18:25
Turns out all I needed to do was install `dmsetup`. It's shocking you guys haven't just added that to the package dependency list.

**Comment by izderadicka** [comment] 2016-10-08 13:55
I also hit this issue (on desktop) - I have to use 4.6 kernel because 4.4 Intel drivers issues.   This cannot install aufs modules from image-extra package.
I though that this might cause problems, but image-extra and aufs is marked as optional dependency.    
I'd expect some more decent behavior in that case then  that installation hangs up, which is pretty nasty.

I was able to get it running as described #23968.

**Comment by thaJeztah** [comment] 2017-05-24 14:30
With Docker 1.13 and up, the overlay and overlay2 drivers are put higher up in the priority list, as they don't require special setup on the host (see https://github.com/moby/moby/pull/27932). As a result, the `devicemapper` driver is only tried _after_ those drivers are tried, so this issue should no longer occur.

I'll close this issue for that reason

**Closed by thaJeztah** 2017-05-24 14:30 UTC
Labels: kind/bug
