### ISSUE TITLE
DOCKER_OPTS when docker is running on debian

### ISSUE THREAD

**Issue by chucky2305** [moby/moby#32707] opened 2017-04-19 09:25 UTC
After hours of trying i think i found out something interesting. I could be just an error by myself (in this case, just close this issue)

I ssh into a server in my company. On this server runs 
```
Description:    Debian
Release:        8.7
Codename:       jessie
```

So installed docker on this server. When i configured jenkins to connect via tls to another docker-container
i hat to give a "URL" to this container. But all my tries did not work. Here are just some things i tried to get it done:
tls://myserver.local:2375
tls://myserver.local:2375
unix:///var/run/docker.sock

The funny thing is: `unit:///var/run/docker.sock` should definetely work,.

Then I read that i should try to edit /etc/default/docker but nothing seemed to take affect.
This is my latest content if /etc/default/docker

```
# Docker Upstart and SysVinit configuration file

#
# THIS FILE DOES NOT APPLY TO SYSTEMD
#
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/admin/systemd/
#

# Customize location of Docker binary (especially for development testing).
#DOCKERD="/usr/local/bin/dockerd"

# Use DOCKER_OPTS to modify the daemon startup options.
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 -H tcp://0.0.0.0:2375 -H tcp://0.0.0.0:2376"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export DOCKER_TMPDIR="/mnt/bigdrive/docker-tmp"
```

Then I modified /lib/systemd/system/docker.service. 

But when i wanted to reload, to make this changes "active" i got errors.
`sudo systemctl daemon-reload`
So i tried to figure out what was wrong with my file, but i could not find the error and i tried to reconstruct the original state of this file. But i could not get i working again. 

After this i moved the docker.service file to __bak__docker.service.

Then i created a daemon.json file in /etc/docker. (At first i had to go sudo su to access /etc/docker)
And this is the content of my daemon.json

```
{
        "hosts": ["tcp://0.0.0.0:2376", "tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
}
```

And from this moment on, i could use the tcp://myserver.local:2375

Is this as designed, did i discover a bug or did i just mess up my whole system?

**Comment by chucky2305** [comment] 2017-04-19 10:35
@thaJeztah: I read your comments in many issues, that are somehow similar to mine. Maybe you could help me.

I restored my docker.service file with this content: https://github.com/moby/moby/blob/master/contrib/init/systemd/docker.service

After saving i executed
`sudo systemctl daemon-reload`
and then 
`sudo systemctl restart docker`

But i only get `Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.`

And `systemctl status docker.service` says:

```
docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: start-limit) since Mi 2017-04-19 12:34:52 CEST; 17s ago
     Docs: https://docs.docker.com
  Process: 17232 ExecStart=/usr/bin/docker -d (code=exited, status=125)
 Main PID: 17232 (code=exited, status=125)
```

**Comment by chucky2305** [comment] 2017-04-19 12:42
I still dont know what exactly broke my system but i got it all working by doing:

1. Using my backup from last night (before i broke my docker service configuration)
2. Created a folder `/etc/systemd/system/docker.service.d/`
3. Created a file inside this folder `/etc/systemd/system/docker.service.d/override.conf`
4. Place the following content inside `override.conf`
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd
```
5. Created a `daemon.json` in `/etc/docker` with following content:
```
{
    "hosts": ["tcp://0.0.0.0:2376", "tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"],
    "group": "docker"
}
```

It seems to work. Can somebody check what i did. Did i do something wrong or did i misconfigure something that will lead to errors sooner or later?

Kind regards,
Max

**Comment by cpuguy83** [comment] 2017-04-28 03:59
`/etc/default/docker` is specifically for sysv-init and upstart.
It's not supported with systemd.

I'm not sure what the override is for since this is what the main unit file would be running.

Closing because this is expected behavior, but feel free to discuss.

**Closed by cpuguy83** 2017-04-28 03:59 UTC
