### ISSUE TITLE
Disabling ipv6 causes static IPs to be reset to DHCP on docker swarm init or join

### ISSUE THREAD

**Issue by BrandonRoyal** [moby/moby#36157] opened 2018-01-31 00:09 UTC
**Description**
When attempting to configure Windows Server 2016 with **A) IPV6 Disabled** and **B) a static IP address set on the same NIC**, Docker is unable to properly persist the static IP configuration when initializing a swarm or joining an existing swarm.

**Steps to reproduce the issue:**
1. Setup clean Windows Server 2016 machine (running latest updates)
2. Disable IPV6 on Ethernet0 device
```
PS> Get-NetAdapterBinding -Name Ethernet0

Name                           DisplayName                                        ComponentID          Enabled
----                           -----------                                        -----------          -------
Ethernet0                      Link-Layer Topology Discovery Responder            ms_rspndr            True
Ethernet0                      Internet Protocol Version 4 (TCP/IPv4)             ms_tcpip             True
Ethernet0                      Hyper-V Extensible Virtual Switch                  vms_pp               False
Ethernet0                      File and Printer Sharing for Microsoft Networks    ms_server            True
Ethernet0                      Client for Microsoft Networks                      ms_msclient          True
Ethernet0                      QoS Packet Scheduler                               ms_pacer             True
Ethernet0                      Link-Layer Topology Discovery Mapper I/O Driver    ms_lltdio            True
Ethernet0                      Microsoft Network Adapter Multiplexor Protocol     ms_implat            False
Ethernet0                      Internet Protocol Version 6 (TCP/IPv6)             ms_tcpip6            True
```
```
PS> Disable-NetAdapterBinding -Name "Ethernet0" -ComponentID ms_tcpip6
```
3. Set Static IP using `sconfig`
```
===============================================================================
                         Server Configuration
===============================================================================

1) Domain/Workgroup:                    Workgroup:  WORKGROUP
2) Computer Name:                       WIN-HBAH0T3886S
3) Add Local Administrator
4) Configure Remote Management          Enabled

5) Windows Update Settings:             DownloadOnly
6) Download and Install Updates
7) Remote Desktop:                      Enabled (all clients)

8) Network Settings
9) Date and Time
10) Telemetry settings                  Enhanced
11) Windows Activation

12) Log Off User
13) Restart Server
14) Shut Down Server
15) Exit to Command Line

Enter number to select an option: 8
```
```
--------------------------------
    Network settings
--------------------------------


Available Network Adapters

Index#  IP address      Description

  1     172.16.229.173  Intel(R) 82574L Gigabit Network Connection
  6     172.17.176.1    Hyper-V Virtual Ethernet Adapter

Select Network Adapter Index# (Blank=Cancel):  1
```
```
--------------------------------
    Network Adapter Settings
--------------------------------


NIC Index               1
Description             Intel(R) 82574L Gigabit Network Connection
IP Address              172.16.229.173  fe80::bd80:1e2d:9b2b:e333
Subnet Mask             255.255.255.0
DHCP enabled            False
Default Gateway         172.16.229.2
Preferred DNS Server    172.16.229.2
Alternate DNS Server

1) Set Network Adapter Address
2) Set DNS Servers
3) Clear DNS Server Settings
4) Return to Main Menu


Select option:  2
DNS Servers

Enter new preferred DNS server (Blank=Cancel): 172.16.229.2
Enter alternate DNS server (Blank = none):
```
```
--------------------------------
    Network Adapter Settings
--------------------------------


NIC Index               1
Description             Intel(R) 82574L Gigabit Network Connection
IP Address              172.16.229.173  fe80::bd80:1e2d:9b2b:e333
Subnet Mask             255.255.255.0
DHCP enabled            True
Default Gateway         172.16.229.2
Preferred DNS Server    172.16.229.2
Alternate DNS Server

1) Set Network Adapter Address
2) Set DNS Servers
3) Clear DNS Server Settings
4) Return to Main Menu


Select option:  1


Select (D)HCP, (S)tatic IP (Blank=Cancel): S

Set Static IP
Enter static IP address: 172.16.229.173
Enter subnet mask (Blank = Default 255.255.255.0):
Enter default gateway: 172.16.229.2
Setting NIC to static IP...
```
Exit `sconfig`

4. Validate that DHCP is disabled on Ethernet0
```
PS> ipconfig /all
Windows IP Configuration

   Host Name . . . . . . . . . . . . : WIN-HBAH0T3886S
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter vEthernet (HNS Internal NIC):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-C9-B6-49
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::40d5:9114:760f:ab1e%12(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.17.176.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 201332061
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-22-01-A7-9C-00-0C-29-77-A4-7D
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Ethernet0:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) 82574L Gigabit Network Connection
   Physical Address. . . . . . . . . : 00-0C-29-77-A4-7D
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 172.16.229.199(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 172.16.229.2
   DNS Servers . . . . . . . . . . . : 172.16.229.2
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{AB62E291-F0E1-4F16-8375-C455C2AD747D}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #2
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{DE679C76-5C06-4D40-9C8E-683D76AABB47}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #3
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
```
_NOTE THAT DHCP ENABLED IS SET TO **FALSE**_

5. Initialize swarm
```
PS> docker swarm init --advertise-addr 172.16.229.173
```

**Describe the results you received:**
After initializing or joining a swarm, my primary network adapter resets to DHCP (and if I wasn't purposefully setting the same IP address for both DHCP and static IPs, it would also get a new IP address).
```
PS> ipconfig /all
Windows IP Configuration

   Host Name . . . . . . . . . . . . : WIN-HBAH0T3886S
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : localdomain

Ethernet adapter vEthernet (HNS Internal NIC):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-C9-B6-49
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::40d5:9114:760f:ab1e%12(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.17.176.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 201332061
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-22-01-A7-9C-00-0C-29-77-A4-7D
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter vEthernet (HNSTransparent):

   Connection-specific DNS Suffix  . : localdomain
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-0C-29-77-A4-7D
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 172.16.229.188(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Friday, February 2, 2018 5:37:47 AM
   Lease Expires . . . . . . . . . . : Friday, February 2, 2018 6:07:47 AM
   Default Gateway . . . . . . . . . : 172.16.229.2
   DHCP Server . . . . . . . . . . . : 172.16.229.254
   DNS Servers . . . . . . . . . . . : 172.16.229.2
   Primary WINS Server . . . . . . . : 172.16.229.2
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.localdomain:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : localdomain
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{AB62E291-F0E1-4F16-8375-C455C2AD747D}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #2
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
```
_NOTE THAT THE ETHERNET0 ADAPTER IS REPLACED WITH A VIRTUAL ADAPTER WITH THE SAME SUBNET, NEW IP ADDRESS AND DHCP SET TO **FALSE**_

**Describe the results you expected:**
Whether adapter is replaced or not, DHCP should remain disabled and IP Address should remain the same.

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: zg3ao6y13pgg64iuqh8jynhlh
 Is Manager: true
 ClusterID: wnwgacfdjeq78uor3pq0hu6u0
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.16.229.173
 Manager Addresses:
  172.16.229.173:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1944.amd64fre.rs1_release.171129-2100)
Operating System: Windows Server 2016 Datacenter Evaluation
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.999GiB
Name: WIN-HBAH0T3886S
ID: NDMX:3FYY:P4YH:V6KO:FITR:7WD6:QWOW:2SKC:RFZD:DA35:WRPU:FWTT
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Windows Server Version**

```
PS> Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" | % {"{0}.{1}.{2}.{3}" -f $_.CurrentMajorVersionNumber,$_.CurrentMinorVersionNumber,$_.CurrentBuildNumber,$_.UBR}
10.0.14393.1944
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Reproduced on VMware ESXi, VMware Fusion and VirtualBox

**Comment by carlfischer1** [comment] 2018-02-01 00:03
@dineshgovindasamy any ideas?

**Comment by BrandonRoyal** [comment] 2018-02-02 13:53
@dineshgovindasamy @johnstep I updated the issue description to show the full output of `ipconfig /all`.  @johnstep pointed out that the Ethernet0 adapter is being completely replaced.  Is that expected behavior?

**Comment by thaJeztah** [comment] 2018-02-07 01:14
This looks to be an issue with Docker EE; can you open a ticket with Microsoft, who are handling primary support, and can escalate if needed? It's worth trying if the issue also reproduces with a current Docker CE version, because there were various fixes that went in related to networking.

I'll close the issue here, but feel free to continue the conversation :+1:

**Closed by thaJeztah** 2018-02-07 01:14 UTC
Labels: area/swarm, platform/windows, version/17.06
