### ISSUE TITLE
docker: Error response from daemon: invalid argument.

### ISSUE THREAD

**Issue by rpandav** [moby/moby#32651] opened 2017-04-17 05:54 UTC
**Description**
Just installed docker and was trying to run the docker/whalesay image. Ran into the following error:

docker run docker/whalesay
docker: Error response from daemon: mkdir /var/lib/docker/overlay/a721883eda8a130b2f6744e89997351689e620c0d8680fa2c119dfa8dff59e74-init/merged/dev/shm: invalid argument.
See 'docker run --help'.

I've seen some defects which talk about overlay. I really don't understand what this means and neither does it explicitly state how to fix the problem. I'm new to using docker and gitHub so clear explanations would be greatly appreciated.

**Output of docker version:**

docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**
[root@ggnlabvm-juper5 ~]# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: ggnlabvm-juper5
ID: Q5J3:Z4ZJ:U54L:FKP6:RQGH:EHE5:KK62:YHDC:BMTY:DSZR:O4X2:QEAM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment] 2017-04-17 06:15
Could be caused by;

```
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
```

Running `overlay` on a backing filesystem without `d_type` support is cause for errors to occur. See the [Red Hat release notes](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.2_Release_Notes/index.html#technology-preview-file_systems)

> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.

**Comment by rpandav** [comment] 2017-04-17 10:59
So what needs to be done to enable d_type?

**Comment by thaJeztah** [comment] 2017-05-15 13:48
See the information I copied above, and the link. To enable `d_type` support, the XFS device has to be reformated

**Comment by thaJeztah** [comment] 2017-05-15 13:49
I'll close this issue, because running overlay in this configuration is known to result in problems. You can either fix that issue with the instructions I mentioned above, or select a different storage driver https://docs.docker.com/engine/userguide/storagedriver/selectadriver/, but feel free to continue the conversation

**Closed by thaJeztah** 2017-05-15 13:49 UTC
Labels: area/storage/overlay, version/17.03
