### ISSUE TITLE
RateLimiting container startup

### ISSUE THREAD

**Issue by j16sdiz** [moby/moby#20713] opened 2016-02-26 04:31 UTC
Please add an option to rate-limiting container startup. (when deamon startup / container fail+restart)

Reason:
- On rotational disk, starting lots of container at the same time actually slow down the process.
- Some container have external dependency. We want it retry/restart automagically when external service fail, but not that fast.

Similar Issue: #1073 #18936

**Comment by HackToday** [comment] 2016-02-26 05:00
how do you want to rate-limit containers?  It seems above requirement is not clear

**Comment by j16sdiz** [comment] 2016-02-26 06:17
@HackToday some kind of queue? guard by `beefsack/go-rate` ?
It doesn't matter..  I just want to lower the random disk seek when the machine is rebooted.

**Comment by HackToday** [comment] 2016-02-26 06:59
I think you need something use label or policy related to set container start sequence. Not quite understand rate limit means.

**Comment by j16sdiz** [comment] 2016-02-26 07:20
@HackToday not sequence, but rate -- like limit to 1 container per second.
Many container (e.g. database) need time to initialize / warm up after start. 
Just starting in the sequence does not help the disk trashing problem

**Comment by thaJeztah** [comment] 2023-09-16 16:07
- closing as (partial) duplicate of https://github.com/moby/moby/issues/18936

**Closed by thaJeztah** 2023-09-16 16:07 UTC
Labels: kind/feature, area/daemon
