### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by bryanlarsen** [moby/moby#35588] opened 2017-11-23 20:35 UTC
**Description**

Docker crashes under heavy load with fatal error: concurrent map writes

**Steps to reproduce the issue:**

~20 or so simultaneous docker builds, along with some docker-compose action.

**Describe the results you received:**

Docker crashes.   (backtrace attached)

**Describe the results you expected:**

It keeps working

**Additional information you deem important (e.g. issue happens only occasionally):**

it happened twice already today, upgraded to 17.11 this morning.

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.11.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data Space Used: 20.45MB
 Data Space Total: 427.2GB
 Data Space Available: 427.2GB
 Metadata Space Used: 516.1kB
 Metadata Space Total: 4.496GB
 Metadata Space Available: 4.496GB
 Thin Pool Minimum Free Space: 42.72GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-40-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.36GiB
Name: dev037
ID: G3I4:4LA6:2C4Y:LFJN:6R3M:KPS6:XELU:LEJO:T4KV:XQNF:E62X:MBUO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical.
Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

backtrace:  https://gist.github.com/bryanlarsen/e8eb30dabb37a429d9b82c1fb12e66de

**Comment by ZigmunD** [comment] 2017-11-24 08:13
Same here. Died one of swarm workers.

**Comment by thaJeztah** [comment] 2017-11-24 08:53
duplicate of https://github.com/moby/moby/issues/35575, which is tracking this issue

Thanks for reporting 👍 please subscribe to that issue to stay informed of updates

**Comment by thaJeztah** [comment] 2017-11-24 08:55
Actually, no, sorry, the trace is different; reopening, sorry for the noise

**Comment by thaJeztah** [comment] 2017-11-24 09:17
```
Nov 23 20:15:07 dev037 dockerd[3269]: goroutine 56447 [running]:
Nov 23 20:15:07 dev037 dockerd[3269]: runtime.throw(0x2a8410d, 0x15)
Nov 23 20:15:07 dev037 dockerd[3269]:         /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4202097d8 sp=0xc4202097b8
Nov 23 20:15:07 dev037 dockerd[3269]: runtime.mapassign(0x27991a0, 0xc42018eed0, 0xc4202098b8, 0x40)
Nov 23 20:15:07 dev037 dockerd[3269]:         /usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc420209878 sp=0xc4202097d8
Nov 23 20:15:07 dev037 dockerd[3269]: github.com/docker/docker/daemon.(*Daemon).registerExecPidUnlocked(0xc420318600, 0xc421186000, 0xc42597f500)
Nov 23 20:15:07 dev037 dockerd[3269]:         /go/src/github.com/docker/docker/daemon/exec.go:39 +0x218 fp=0xc420209918 sp=0xc420209878
Nov 23 20:15:07 dev037 dockerd[3269]: github.com/docker/docker/daemon.(*Daemon).ContainerExecStart(0xc420318600, 0x7f1162ea4ba0, 0xc4386f23c0, 0xc421e83000, 0x40, 0x0, 0x0, 0x3810a80, 0xc425b83100, 0x3810a80, ...)
Nov 23 20:15:07 dev037 dockerd[3269]:         /go/src/github.com/docker/docker/daemon/exec.go:256 +0xa64 fp=0xc420209d70 sp=0xc420209918
Nov 23 20:15:07 dev037 dockerd[3269]: github.com/docker/docker/daemon.(*cmdProbe).run(0xc42bbe7cbd, 0x7f1162ea4ba0, 0xc4386f23c0, 0xc420318600, 0xc421186000, 0x2, 0x2, 0xc4210c9708)
Nov 23 20:15:07 dev037 dockerd[3269]:         /go/src/github.com/docker/docker/daemon/health.go:94 +0x5a7 fp=0xc420209ea8 sp=0xc420209d70
Nov 23 20:15:07 dev037 dockerd[3269]: github.com/docker/docker/daemon.monitor.func1(0x3810a00, 0xc42bbe7cbd, 0x7f1162ea4ba0, 0xc4386f23c0, 0xc420318600, 0xc421186000, 0xc4386f2420, 0xed1a9234b, 0xc4341dfc1f, 0x3886ea0)
Nov 23 20:15:07 dev037 dockerd[3269]:         /go/src/github.com/docker/docker/daemon/health.go:198 +0xb0 fp=0xc420209f90 sp=0xc420209ea8
Nov 23 20:15:07 dev037 dockerd[3269]: runtime.goexit()
.....
```


Is this because `c.ExecCommands`, and `ec` are locked, but `d.ExecCommands` isn't?

i.e.; here `d.ExecCommands` isn't locked;

https://github.com/docker/docker-ce/blob/v17.11.0-ce/components/engine/daemon/exec.go#L255-L258

```go
	ec.Pid = systemPid
	d.registerExecPidUnlocked(c, ec)
	c.ExecCommands.Unlock()
	ec.Unlock()
```


And `d.registerExecPidUnlocked()` calls `d.ExecCommands.SetPidUnlocked()`:

https://github.com/docker/docker-ce/blob/v17.11.0-ce/components/engine/daemon/exec.go#L34-L40

```go
func (d *Daemon) registerExecPidUnlocked(container *container.Container, config *exec.Config) {
	logrus.Debugf("registering pid %v for exec %v", config.Pid, config.ID)
	// Storing execs in container in order to kill them gracefully whenever the container is stopped or removed.
	container.ExecCommands.SetPidUnlocked(config.ID, config.Pid)
	// Storing execs in daemon for easy access via Engine API.
	d.execCommands.SetPidUnlocked(config.ID, config.Pid)
}
```


Which does not lock either;

https://github.com/docker/docker-ce/blob/v17.11.0-ce/components/engine/daemon/exec/exec.go#L122-L128

```go
// SetPidUnlocked adds an association between a Pid and a config, it does not
// synchronized with other operations.
func (e *Store) SetPidUnlocked(id string, pid int) {
	if config, ok := e.byID[id]; ok {
		e.byPid[pid] = config
	}
}
```

ping @mlaventure @cpuguy83 @tonistiigi PTAL

**Comment by thaJeztah** [comment] 2017-11-24 09:36
opened https://github.com/moby/moby/pull/35591 for discussion 😅

**Closed** 2017-11-30 16:17 UTC
Labels: area/builder, kind/bug, version/17.11
