### ISSUE TITLE
Timeout on exposed port `:8080` after `docker stack deploy`

### ISSUE THREAD

**Issue by arvenil** [moby/moby#31516] opened 2017-03-03 14:00 UTC
**Description**

I'm trying to fire up basic example of `docker stack deploy` with `--compose-file` which only consist one replica of `nginx` and connect to it through exposed port `8080` via `curl`. It looks like port is mapped but I'm getting connection timeout.

**Steps to reproduce the issue:**

I've created repo with `Vagrantfile` and `docker-compose.yml` with all the steps for creating swarm and deployment.

```terminal
git clone git@github.com:arvenil/docker-swarm-test.git
cd docker-swarm-test
vagrant up
```

<details><summary>Vagrantfile</summary><p>

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

$swarm_workers = 1
# https://github.com/mitchellh/vagrant/issues/8322
$interface = "enp0s8"

Vagrant.configure("2") do |config|
  config.ssh.pty = true
  config.vm.box = "minimal/xenial64"
  config.vm.provision :docker

  config.vm.network "private_network",
    type: "dhcp"

  config.vm.define "swarm-manager" do |config|
    config.vm.hostname = "swarm-manager"
    config.vm.provision "shell", inline: <<-SHELL
        ifconfig #{$interface} | awk '/(cast)/ {print $2}' | cut -d: -f2 > /vagrant/swarm_manager_ip
        docker swarm init --advertise-addr $(cat /vagrant/swarm_manager_ip)
        docker swarm join-token -q worker > /vagrant/swarm_worker_token
        docker swarm join-token -q manager > /vagrant/swarm_manager_token
    SHELL
  end

  $swarm_workers.times do |n|
    config.vm.define "swarm-worker-#{n}" do |config|
      config.vm.hostname = "swarm-worker-#{n}"
      config.vm.provision "shell", inline: <<-SHELL
          docker swarm join --token=$(cat /vagrant/swarm_worker_token) $(cat /vagrant/swarm_manager_ip):2377
      SHELL
    end
  end

  config.vm.define "main", primary: true do |config|
    config.vm.hostname = "main"
    config.vm.provision "shell", inline: <<-SHELL
      set -x
      docker swarm join --token=$(cat /vagrant/swarm_manager_token) $(cat /vagrant/swarm_manager_ip):2377
      docker node update --availability drain main
      docker node ls
      curl --max-time 60 localhost:8080 | head -3
      docker stack deploy --compose-file /vagrant/docker-compose.yml app-swarm
      sleep 30 # maybe --wait until all services run option for stack deploy?
      docker service ls
      docker service ps app-swarm_nginx
      docker stack ps app-swarm
      curl --max-time 60 localhost:8080 | head -3
      set +x
    SHELL
  end
end
```

</p></details>

<details><summary>docker-compose.yml</summary><p>

```yaml
version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```
</p></details>

<details><summary>full log from running vagrant up</summary><p>

```terminal
$ vagrant up
==> main: Forcing shutdown of VM...
==> main: Destroying VM and associated drives...
==> swarm-worker-0: Forcing shutdown of VM...
==> swarm-worker-0: Destroying VM and associated drives...
==> swarm-manager: Forcing shutdown of VM...
==> swarm-manager: Destroying VM and associated drives...
Bringing machine 'swarm-manager' up with 'virtualbox' provider...
Bringing machine 'swarm-worker-0' up with 'virtualbox' provider...
Bringing machine 'main' up with 'virtualbox' provider...
==> swarm-manager: Importing base box 'minimal/xenial64'...
==> swarm-manager: Matching MAC address for NAT networking...
==> swarm-manager: Checking if box 'minimal/xenial64' is up to date...
==> swarm-manager: Setting the name of the VM: vagrant-docker-test_swarm-manager_1488547275583_39947
==> swarm-manager: Clearing any previously set network interfaces...
==> swarm-manager: Preparing network interfaces based on configuration...
    swarm-manager: Adapter 1: nat
    swarm-manager: Adapter 2: hostonly
==> swarm-manager: Forwarding ports...
    swarm-manager: 22 (guest) => 2222 (host) (adapter 1)
==> swarm-manager: Booting VM...
==> swarm-manager: Waiting for machine to boot. This may take a few minutes...
    swarm-manager: SSH address: 127.0.0.1:2222
    swarm-manager: SSH username: vagrant
    swarm-manager: SSH auth method: private key
    swarm-manager:
    swarm-manager: Vagrant insecure key detected. Vagrant will automatically replace
    swarm-manager: this with a newly generated keypair for better security.
    swarm-manager:
    swarm-manager: Inserting generated public key within guest...
    swarm-manager: Removing insecure key from the guest if it's present...
    swarm-manager: Key inserted! Disconnecting and reconnecting using new SSH key...
==> swarm-manager: Machine booted and ready!
==> swarm-manager: Checking for guest additions in VM...
==> swarm-manager: Setting hostname...
==> swarm-manager: Configuring and enabling network interfaces...
==> swarm-manager: Mounting shared folders...
    swarm-manager: /vagrant => /Users/kdz/projects/vagrant-docker-test
==> swarm-manager: Running provisioner: docker...
    swarm-manager: Installing Docker onto machine...
==> swarm-manager: Running provisioner: shell...
    swarm-manager: Running: inline script
==> swarm-manager: Swarm initialized: current node (ucufgwrbi31v3mb933tpu62v8) is now a manager.
==> swarm-manager:
==> swarm-manager: To add a worker to this swarm, run the following command:
==> swarm-manager:
==> swarm-manager:     docker swarm join \
==> swarm-manager:     --token SWMTKN-1-1x1slt167854ruxxfj70cwicmodg7j6sdjoze5d6je4e452glr-59cvk4bq3cqk9vnby4sz24l36 \
==> swarm-manager:     172.28.128.9:2377
==> swarm-manager:
==> swarm-manager: To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
==> swarm-worker-0: Importing base box 'minimal/xenial64'...
==> swarm-worker-0: Matching MAC address for NAT networking...
==> swarm-worker-0: Checking if box 'minimal/xenial64' is up to date...
==> swarm-worker-0: Setting the name of the VM: vagrant-docker-test_swarm-worker-0_1488547446295_47279
==> swarm-worker-0: Fixed port collision for 22 => 2222. Now on port 2200.
==> swarm-worker-0: Clearing any previously set network interfaces...
==> swarm-worker-0: Preparing network interfaces based on configuration...
    swarm-worker-0: Adapter 1: nat
    swarm-worker-0: Adapter 2: hostonly
==> swarm-worker-0: Forwarding ports...
    swarm-worker-0: 22 (guest) => 2200 (host) (adapter 1)
==> swarm-worker-0: Booting VM...
==> swarm-worker-0: Waiting for machine to boot. This may take a few minutes...
    swarm-worker-0: SSH address: 127.0.0.1:2200
    swarm-worker-0: SSH username: vagrant
    swarm-worker-0: SSH auth method: private key
    swarm-worker-0:
    swarm-worker-0: Vagrant insecure key detected. Vagrant will automatically replace
    swarm-worker-0: this with a newly generated keypair for better security.
    swarm-worker-0:
    swarm-worker-0: Inserting generated public key within guest...
    swarm-worker-0: Removing insecure key from the guest if it's present...
    swarm-worker-0: Key inserted! Disconnecting and reconnecting using new SSH key...
==> swarm-worker-0: Machine booted and ready!
==> swarm-worker-0: Checking for guest additions in VM...
==> swarm-worker-0: Setting hostname...
==> swarm-worker-0: Configuring and enabling network interfaces...
==> swarm-worker-0: Mounting shared folders...
    swarm-worker-0: /vagrant => /Users/kdz/projects/vagrant-docker-test
==> swarm-worker-0: Running provisioner: docker...
    swarm-worker-0: Installing Docker onto machine...
==> swarm-worker-0: Running provisioner: shell...
    swarm-worker-0: Running: inline script
==> swarm-worker-0: This node joined a swarm as a worker.
==> main: Importing base box 'minimal/xenial64'...
==> main: Matching MAC address for NAT networking...
==> main: Checking if box 'minimal/xenial64' is up to date...
==> main: Setting the name of the VM: vagrant-docker-test_main_1488547765296_71722
==> main: Fixed port collision for 22 => 2222. Now on port 2201.
==> main: Clearing any previously set network interfaces...
==> main: Preparing network interfaces based on configuration...
    main: Adapter 1: nat
    main: Adapter 2: hostonly
==> main: Forwarding ports...
    main: 22 (guest) => 2201 (host) (adapter 1)
==> main: Booting VM...
==> main: Waiting for machine to boot. This may take a few minutes...
    main: SSH address: 127.0.0.1:2201
    main: SSH username: vagrant
    main: SSH auth method: private key
    main:
    main: Vagrant insecure key detected. Vagrant will automatically replace
    main: this with a newly generated keypair for better security.
    main:
    main: Inserting generated public key within guest...
    main: Removing insecure key from the guest if it's present...
    main: Key inserted! Disconnecting and reconnecting using new SSH key...
==> main: Machine booted and ready!
==> main: Checking for guest additions in VM...
==> main: Setting hostname...
==> main: Configuring and enabling network interfaces...
==> main: Mounting shared folders...
    main: /vagrant => /Users/kdz/projects/vagrant-docker-test
==> main: Running provisioner: docker...
    main: Installing Docker onto machine...
==> main: Running provisioner: shell...
    main: Running: inline script
==> main: +++ cat /vagrant/swarm_manager_token
==> main: +++ cat /vagrant/swarm_manager_ip
==> main: ++ docker swarm join --token=SWMTKN-1-1x1slt167854ruxxfj70cwicmodg7j6sdjoze5d6je4e452glr-09mi5oz7euyuhn80qk7cf4zrf 172.28.128.9:2377
==> main: This node joined a swarm as a manager.
==> main: ++ docker node update --availability drain main
==> main: main
==> main: ++ docker node ls
==> main: ID                           HOSTNAME        STATUS  AVAILABILITY  MANAGER STATUS
==> main: on9yv9d5fhu4655phq75v0ccy    swarm-worker-0  Ready   Active
==> main: rw3ee7x7foiyjpj3ijduufdfr *  main            Ready   Drain         Reachable
==> main: ucufgwrbi31v3mb933tpu62v8    swarm-manager   Ready   Active        Leader
==> main: ++ head -3
==> main: ++ curl --max-time 60 localhost:8080
==> main:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> main:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8080: Connection refused
==> main: ++ docker stack deploy --compose-file /vagrant/docker-compose.yml app-swarm
==> main: Creating network app-swarm_default
==> main: Creating service app-swarm_nginx
==> main: ++ sleep 30
==> main: ++ docker service ls
==> main: ID            NAME             MODE        REPLICAS  IMAGE
==> main: 1nl7iwnae0kw  app-swarm_nginx  replicated  1/1       nginx:latest
==> main: ++ docker service ps app-swarm_nginx
==> main: ID            NAME               IMAGE         NODE           DESIRED STATE  CURRENT STATE           ERROR  PORTS
==> main: irsu68bgopea  app-swarm_nginx.1  nginx:latest  swarm-manager  Running        Running 16 seconds ago
==> main: ++ docker stack ps app-swarm
==> main: ID            NAME               IMAGE         NODE           DESIRED STATE  CURRENT STATE           ERROR  PORTS
==> main: irsu68bgopea  app-swarm_nginx.1  nginx:latest  swarm-manager  Running        Running 16 seconds ago
==> main: ++ head -3
==> main: ++ curl --max-time 60 localhost:8080
==> main:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> main:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
==> main: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
==> main: ++ set +x
```
</p>
</details>

**Describe the results you received:**

```
$ curl --max-time 60 localhost:8080
curl: (28) Operation timed out after 60003 milliseconds with 0 bytes received
```

**Describe the results you expected:**

```
html response from nginx
```

**Comment by thaJeztah** [comment] 2017-03-03 14:47
I'm not able to reproduce this on a ubuntu 16.04 droplet on digitalocean.

Can you

- add the output of `docker version` and `docker info`?
- check if the logs show anything useful?

Could this be because of the host only network?

**Comment by arvenil** [comment] 2017-03-03 15:35
```
vagrant@main:~$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```terminal
vagrant@main:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: i1c9aq8ezaluhwjik5yt51va2
 Is Manager: true
 ClusterID: 457z56xre2doicd65a95vnsby
 Managers: 2
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.28.128.5
 Manager Addresses:
  172.28.128.3:2377
  172.28.128.5:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3 MiB
Name: main
ID: ZX5Z:YHSN:XQY2:OH3G:SGVU:RAGX:SFN6:5K7L:IAWS:AYAH:6XDK:TUSC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
vagrant@main:~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
4cgxtwagmvsu        app-swarm_default   overlay             swarm
7875e96a8680        bridge              bridge              local
6870b833400f        docker_gwbridge     bridge              local
7e8e1e664241        host                host                local
1dih5vbawg3j        ingress             overlay             swarm
95ca82af4d6c        none                null                local
```
```terminal
vagrant@main:~$ docker service inspect app-swarm_nginx
[
    {
        "ID": "sf83hczla38kun7qhbagr2wz5",
        "Version": {
            "Index": 25
        },
        "CreatedAt": "2017-03-03T15:01:47.545955594Z",
        "UpdatedAt": "2017-03-03T15:01:47.552322081Z",
        "Spec": {
            "Name": "app-swarm_nginx",
            "Labels": {
                "com.docker.stack.namespace": "app-swarm"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest@sha256:52a189e49c0c797cfc5cbfe578c68c225d160fb13a42954144b29af3fe4fe335",
                    "Labels": {
                        "com.docker.stack.namespace": "app-swarm"
                    }
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "MaxAttempts": 0
                },
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "Networks": [
                {
                    "Target": "4cgxtwagmvsuzp4f3fi1g227p",
                    "Aliases": [
                        "nginx"
                    ]
                }
            ],
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 8080,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 8080,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 8080,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "1dih5vbawg3j670p25dteclb4",
                    "Addr": "10.255.0.6/16"
                },
                {
                    "NetworkID": "4cgxtwagmvsuzp4f3fi1g227p",
                    "Addr": "10.0.0.2/24"
                }
            ]
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by VERGiL1202** [comment] 2017-05-14 17:29
Did you manage to solve the problem? I have the same issue on my servers.
When testing on a digitalocean droplet it works.
<details>
<summary>running on my "problem"-server: docker service inspect test</summary>
<pre>[
    {
        "ID": "s2cdy59846x9jqvx65hhpixwx",
        "Version": {
            "Index": 2840
        },
        "CreatedAt": "2017-05-14T16:59:16.195154745Z",
        "UpdatedAt": "2017-05-14T17:26:25.775964077Z",
        "Spec": {
            "Name": "test_nginx",
            "Labels": {
                "com.docker.stack.namespace": "test"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest@sha256:12d30ce421ad530494d588f87b2328ddc3cae666e77ea1ae5ac3a6661e52cde6",
                    "Labels": {
                        "com.docker.stack.namespace": "test"
                    },
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {},
                "Networks": [
                    {
                        "Target": "nvjtqjueufg7a24qg9i7m64tg",
                        "Aliases": [
                            "nginx"
                        ]
                    }
                ],
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 808,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "PreviousSpec": {
            "Name": "test_nginx",
            "Labels": {
                "com.docker.stack.namespace": "test"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest@sha256:12d30ce421ad530494d588f87b2328ddc3cae666e77ea1ae5ac3a6661e52cde6",
                    "Labels": {
                        "com.docker.stack.namespace": "test"
                    }
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "MaxAttempts": 0
                },
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "Networks": [
                {
                    "Target": "nvjtqjueufg7a24qg9i7m64tg",
                    "Aliases": [
                        "nginx"
                    ]
                }
            ],
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 808,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 808,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 808,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "lv6mv4mos62tt2lsm1ivuvlzo",
                    "Addr": "10.255.0.2/16"
                },
                {
                    "NetworkID": "nvjtqjueufg7a24qg9i7m64tg",
                    "Addr": "10.0.0.2/24"
                }
            ]
        },
        "UpdateStatus": {
            "State": "completed",
            "StartedAt": "2017-05-14T17:26:14.748108265Z",
            "CompletedAt": "2017-05-14T17:26:25.775918412Z",
            "Message": "update completed"
        }
    }
]
</pre>
</details>
<details>
<summary>running on a digitalocean 16.04 droplet: docker service inspect test</summary>
<pre>
docker service inspect test_nginx
[
    {
        "ID": "af3n80oz3ncnm04cnptouo6s0",
        "Version": {
            "Index": 53
        },
        "CreatedAt": "2017-05-14T16:46:46.923249704Z",
        "UpdatedAt": "2017-05-14T16:59:46.916380725Z",
        "Spec": {
            "Name": "test_nginx",
            "Labels": {
                "com.docker.stack.namespace": "test"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest@sha256:12d30ce421ad530494d588f87b2328ddc3cae666e77ea1ae5ac3a6661e52cde6",
                    "Labels": {
                        "com.docker.stack.namespace": "test"
                    },
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {},
                "Networks": [
                    {
                        "Target": "vi0si2y2w7d4naclnetwiquxz",
                        "Aliases": [
                            "nginx"
                        ]
                    }
                ],
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 808,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "PreviousSpec": {
            "Name": "test_nginx",
            "Labels": {
                "com.docker.stack.namespace": "test"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest@sha256:12d30ce421ad530494d588f87b2328ddc3cae666e77ea1ae5ac3a6661e52cde6",
                    "Labels": {
                        "com.docker.stack.namespace": "test"
                    }
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "MaxAttempts": 0
                },
                "Placement": {},
                "Networks": [
                    {
                        "Target": "vi0si2y2w7d4naclnetwiquxz",
                        "Aliases": [
                            "nginx"
                        ]
                    }
                ],
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 8080,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 808,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 808,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "dqivvxglutmf0pnua43savawf",
                    "Addr": "10.255.0.4/16"
                },
                {
                    "NetworkID": "vi0si2y2w7d4naclnetwiquxz",
                    "Addr": "10.0.0.2/24"
                }
            ]
        },
        "UpdateStatus": {
            "State": "completed",
            "StartedAt": "2017-05-14T16:59:39.579459869Z",
            "CompletedAt": "2017-05-14T16:59:46.916351784Z",
            "Message": "update completed"
        }
    }
]
</pre>
</details>

I noticed that the `Networks` section is not embedded in the `TaskTemplate` on the digitalocean droplet.
I'm running on Docker 17.05.0-ce.

**Comment by neolectron** [comment] 2017-09-08 10:23
WOW @VERGiL1202 its the same for me. i'm using scaleway and I also have lot of trouble using stack deploy. do you have any fix for this since ?

**Comment by thaJeztah** [comment] 2023-09-17 19:27
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 19:27 UTC
Labels: area/networking, area/swarm
