### ISSUE TITLE
Inconsistent behaviour (?) of 'create' subcommand

### ISSUE THREAD

**Issue by rsommer** [moby/moby#41491] opened 2020-09-25 06:59 UTC
**Description**

While testing compatibility of different container runtimes, I came across the behaviour of `docker volume create`. While other docker `create` commands fail when a name is reused, `docker volume create` does not. Is this expected behaviour or a bug? podman for example does fail in that case.

**Steps to reproduce the issue:**
1. `docker volume create test`
2. `docker volume create test`
3. -> No error

**Describe the results you received:**
No error.

**Describe the results you expected:**
Error on second create like with `docker network create`, `docker service create` etc. 

**Additional information you deem important (e.g. issue happens only occasionally):**
This is more like a question of what the correct behaviour should be.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 47
  Running: 2
  Paused: 0
  Stopped: 45
 Images: 339
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: shftvx79hrj5sesdlkvro38f1
  Is Manager: true
  ClusterID: tb7rk5s3mmtq2lm14o9x7msco
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.42.64.11
  Manager Addresses:
   10.42.64.11:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 19.26GiB
 Name: notebook-ros
 ID: MTFO:VSD4:YSBU:2TLI:ISTS:4WXG:YDNX:UOZX:MAAY:EBD6:UEBN:4YWZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2020-09-25 13:53
Thanks for reporting; looks like this is a duplicate of https://github.com/moby/moby/issues/16068, which has a discussion on this topic.

Let me close this one to prevent the discussion from diverging, but feel free to participate on https://github.com/moby/moby/issues/16068

**Closed by thaJeztah** 2020-09-25 13:53 UTC
Labels: area/volumes, kind/question
