### ISSUE TITLE
help to solve this non zero code: 8 error

### ISSUE THREAD

**Issue by rishavjaiswal** [moby/moby#39304] opened 2019-06-03 14:13 UTC
after using docker build i am getting output as:
.
.
.
.
Complete!
The command '/bin/sh -c yum install -y wget java-1.8.0-openjdk     && cd /tmp && wget -q $KAFKA_BIN     && export K_TAR=/tmp/$(ls kafka* | head -1)     && mkdir -p /opt/apache/kafka/ && tar -zxf $K_TAR -C /opt/apache/kafka/     && cd /opt/apache/kafka && ln -s $(ls) current     && rm -rf $K_TAR' returned a non-zero code: 8

**Comment by thaJeztah** [comment] 2019-06-04 09:39
That error is coming from the container itself (the command running inside the container failed).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-06-04 09:39 UTC
Labels: area/builder
