### ISSUE TITLE
23.0.1 hangs indefinitely for centos:7 or opensuse/leap:15.2 image

### ISSUE THREAD

**Issue by aashipov** [moby/moby#45072] opened 2023-02-24 08:49 UTC
### Description

Arch Linux
Kernel Linux hp 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux
docker run --rm centos:7.9.2009 yum upgrade -y
or
docker run --rm opensuse/leap:15.2 zypper --non-interactive in mc
hang indefinitely
The only way to stop those containers - docker stop ... from a separate virtual terminal (or GUI like portainer-ce)
Similar behavior for Dockerfile with commands above

### Reproduce

docker run --rm centos:7.9.2009 yum upgrade -y
or
docker run --rm opensuse/leap:15.2 zypper --non-interactive in mc
watch setup 'freeze' / 'hang'

### Expected behavior

Execution of commands above pass without error in finite amount time

### docker version

```bash
Client:
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.20
 Git commit:        a5ee5b1dfc
 Built:             Sat Feb 11 13:58:04 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20
  Git commit:       bc3805a0a0
  Built:            Sat Feb 11 13:58:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640.m
 runc:
  Version:          1.1.4
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.3
    Path:     /home/user/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /home/user/.docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 6.1.12-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.61GiB
 Name: hp
 ID: YSXM:KZGO:4FBP:TH2A:EWM6:K7XV:VY6M:ZTLN:BFQA:V2P4:7FWJ:3QOA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Live Restore Enabled: false
```

### Additional Info

Filesystem seems irrelevant (XFS with d_type === true or ext4)

**Comment by thaJeztah** [comment] 2023-02-24 13:01
Packages for Arch Linux are not built by this project, but by the Arch Linux package maintainers; in some cases those packages have been built with different (versions of) build-time dependencies, or from modified source (e.g. in this case, the containerd packages look to have been built from an unclean git commit (`2456e983eb9e37e47538f59ea18f2043c9a73640.m`). But (with Arch Linux being a "bleeding edge" distro) at times there's also been issues caused by changes in the kernel.

It's still possible that there's an issue in the code in this repository, but I would recommend reporting the issue to the Arch Linux package maintainers as "first line of support" and to do the initial triage / investigating.

**Comment by aashipov** [comment] 2023-02-25 05:03
I did report the issue to Arch Linux team
Downgrade to 20.10.9 (docker package only, the rest of dependencies still 'bleeding edge') is a good enough 'fix'

**Comment by nightah** [comment] 2023-02-27 05:46
@thaJeztah I'm in no way affiliated with Arch Linux however, I also experienced this same issue.

I'm not entirely sure whether this bug report actually belongs in https://github.com/containerd/containerd or here so happy to be advised by you on how to proceed.

It seems that the issue manifests specifically in Arch Linux with Docker 23.0.1 with an overlay2 storage driver (perhaps all file level storage drivers but I have only tested overlay2) because of the containerd systemd service including the line:
```
LimitNOFILE=infinity
```

Looking at the difference between other Linux variants and the actual value that `infinity` would be representing it seems that Arch Linux `fs.nr_open` returns `1073741816` whereas Ubuntu Jammy instead returns `1048576` the value being different is due to [this systemd commit](https://github.com/systemd/systemd/commit/a8b627aaed409a15260c25988970c795bf963812).

To be clear if I install Docker 23.0.1 and update the containerd systemd service to include:
```
LimitNOFILE=1048576
```

Docker 23.0.1 appears to work fine. I'm not sure if that systemd change and the consequent change of `fs.nr_open` to `1073741816` also has an impact to Docker but setting the value to `1048576` in the docker systemd service doesn't appear to change anything.

Another thing I noticed which leads me to assume that this is only limited to file level storage drivers is that on another Arch Linux machine with Docker 23.0.1 but with ZFS as the storage driver the issues didn't seem to manifest.

**Comment by neersighted** [comment] 2023-02-27 16:30
This looks to be a potential duplicate of #45060 and #38814 as well. I think we should close it as a duplicate of https://github.com/containerd/containerd/pull/7566 and #38814 to centralize where we discuss container ulimits in containerd and Moby; does that sound reasonable?

**Comment by neersighted** [comment] 2023-03-03 00:44
Closing this as a duplicate :smile:

**Closed by neersighted** 2023-03-03 00:44 UTC
Labels: status/0-triage, status/more-info-needed, kind/bug, version/unsupported, version/23.0

**Comment by thaJeztah** [comment] 2023-03-03 13:38
>  I've noticed that in 20.10.23 containerd is forked from the Docker service

For 20.10, containerd _should_ also be running as a separate service, but there is a possible race condition if the containerd service isn't fully up. That was addressed in;

- https://github.com/docker/docker-ce-packaging/pull/297

(which is the systemd unit file that's used for the docker-ce 20.10 releases) but I don't know if the Arch packagers use the same unit files (they may be using their own variant in packaging)

**Comment by polarathene** [comment] 2023-05-10 03:43
> For 20.10, containerd _should_ also be running as a separate service

Not related to `docker run` AFAIK, but v23 did enable BuildKit by default, whereas previously `DOCKER_BUILDKIT=1` was required.

This does affect the `LimitNOFILE` applied being from `docker.service` (_`docker build` uses this in v23, unless setting `DOCKER_BUILDKIT=0`)_ or `containerd.service` (_default with prior versions_).
