### ISSUE TITLE
Container Cant be removed

### ISSUE THREAD

**Issue by rrravattu** [moby/moby#34652] opened 2017-08-28 12:40 UTC
Hello all,

Submitting a new issue because the solutions of the existing issues #21969 and #22260 do not solve my problem. Apologies if I m creating a duplicate. I am trying to remove a container because I am not able to run the docker after making changes. I got the error
"docker: Error response from daemon: Conflict. The container name "/elastic-search-staging" is already in use by container "cce70c23af7ad406a1d75d7d348c281add3e7e2047dfcf1e4c4ed8611f5fb619". You have to remove (or rename) that container to be able to reuse that name."

So I went ahead and stopped the container (checked the status and it says dead) and tried to remove it again. Now it says 
"Error response from daemon: driver "overlay" failed to remove root filesystem for cce70c23af7ad406a1d75d7d348c281add3e7e2047dfcf1e4c4ed8611f5fb619: remove /data/docker/overlay/c88afd486a60297706e1d939bd344f494823e87717d8e78de0e029a3e52c6dc4/merged: device or resource busy"

**Output of `docker version`:**

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 25
 Running: 8
 Paused: 0
 Stopped: 17
Images: 55
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: vm7357.vellance.net
ID: JJFN:NJDL:A2GB:YFX2:FLX2:RQOB:TUBN:7CQF:NSG7:VDEB:TRDL:4BFT
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by ripcurld0** [comment] 2017-08-28 12:49
@rrravattu can you provide the daemon logs?

**Comment by cpuguy83** [comment] 2017-08-28 13:25
Let's close this because this is exactly the same as #22260 which is still open.
Thanks!
In order to fix your current situation, the easiest thing is a reboot.

The issue is the mount has leaked into another mount namespace... likely another container by bind-mounting `/var/lib/docker` (or one of it's parents) into a container.

**Closed by cpuguy83** 2017-08-28 13:25 UTC
Labels: area/storage/overlay, version/17.06
