### ISSUE TITLE
docker logs -f stops when json-file rotates log file

### ISSUE THREAD

**Issue by tazle** [moby/moby#37646] opened 2018-08-15 12:37 UTC
**Description**

When Docker json-file log driver rotates the log file, applications streaming the log such as `docker logs -f` or logspout stop receiving new log events.

**Steps to reproduce the issue:**
1. Start container that produces logs: `docker run --rm -d alpine sh -c 'while true; do echo $(date); done'`
2. Start tailing logs: `docker logs -f <container-id>`
3. Observe log file size at `/var/lib/docker/containers/<container-id>/<container-id>-json.log`

**Describe the results you received:**

When the log file rotates, `docker logs -f` output stops.

**Describe the results you expected:**

I expect `docker logs -f` to continue outputting logs until terminated.

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems to be a duplicate of https://github.com/moby/moby/issues/23913 which was supposed to have been fixed through https://github.com/moby/moby/pull/24514 in 1.13.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.6
 Git commit:   9ee9f40
 Built:        Thu Apr 26 04:27:49 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.6
  Git commit:   9ee9f40
  Built:        Thu Apr 26 04:27:49 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 24
 Running: 5
 Paused: 0
 Stopped: 19
Images: 47
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 3641oiewax7rd3re6mbt0uhto
 Is Manager: true
 ClusterID: 3dg2kejti78ucxky28skve8cv
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.18.5.178
 Manager Addresses:
  172.18.5.136:2377
  172.18.5.178:2377
  172.18.5.248:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.59-coreos-r2
Operating System: Container Linux by CoreOS 1800.6.0 (Rhyolite)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: REDACTED
ID: EK5F:II7L:AE6M:JCUO:C4CT:TM5F:XL6Z:XL6P:FJ2M:2EBC:LC45:VJTJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 103
 Goroutines: 273
 System Time: 2018-08-15T12:35:17.758625842Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://REDACTED/
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

CoreOS stable channel on EC2.

**Comment by flosell** [comment] 2018-08-27 04:03
Can confirm this is happening (same docker version). I'm also seeing the same behaviour in the DataDog Agent collecting logs so the problem doesn't seem to be limited to the Docker CLI.

**Comment by asimtech12** [comment] 2018-08-28 07:48
Hi
workaround for this scenario is to include "--log-opt max-file=3" flag as well (3 is just a random number you have any number depending upon your need) so to make it work, 

do following
1- docker run --log-opt max-size=10m --log-opt max-file=3 --rm -d alpine sh -c 'while true; do echo $(date); done'
2- Start tailing logs: docker logs -f <container-id>
3- Observe log file size at /var/lib/docker/containers/<container-id>/<container-id>-json.log*

you will see 3 log files rotating at
/var/lib/docker/containers/<container-id>/<container-id>-json.log
 /var/lib/docker/containers/<container-id>/<container-id>-json.log.1
 /var/lib/docker/containers/<container-id>/<container-id>-json.log.2

and docker logs -f <container-id> is also pointing to the <container-id>-json.log, 

Thanks
Asim

**Comment by asimtech12** [comment] 2018-08-28 07:49
above issue is still reproducible if you have only one log file on which "docker logs -f <containerid>"point to.

but having more then one file log file seems to be working fine.

Thanks
Asim

**Comment by tazle** [comment] 2018-08-28 08:26
I'll test this. Thank you.

**Comment by tazle** [comment] 2018-08-28 13:44
The workaround seems to work for me as well.

**Comment by tazle** [comment] 2018-09-24 16:39
We have now run into this or a similar issue again, with logspout. For some reason, logspout stops receiving logs sometimes for some containers after a while, when using json-file logging with 5 log files of 10 MB each.

**Comment by tazle** [comment] 2018-09-24 16:40
We have now run into this or a similar issue again, with logspout. For some reason, logspout stops receiving logs sometimes for some containers after a while, when using json-file logging with 5 log files of 10 MB each.

**Comment by ylfforme** [comment] 2018-10-09 07:43
The workaround does not work for me, I already set max-file and max-size，bug docker logs -f sitll stuck

**Comment by hmtai** [comment] 2018-11-26 02:00
@ylfforme Can you can docker logs output when docker logs -f stuck？I can't see docker logs and my json.log is empty when my container run some days.

**Comment by achntrl** [comment] 2018-12-20 10:48
The problem with the `--log-opt max-file=1` is easy to replicate:

```bash
$ docker run --log-driver json-file \
  --log-opt max-size=10k \
  --log-opt max-file=1 \
  -d centos \
  bash -c "i=0; while ((++i)); do echo \$i hello world; sleep 0.1; done"
```

```console
$ docker logs -f <container_id>
1 hello world
2 hello world
# [...]
119 hello world
120 hello world
121 hello world
# ^ hangs here forever, after the log rotation
```

Note that subsequent calls to `docker logs -f <container_id>` works until the next log rotation (e.g. you can see `122 hello world` to `241 hello world` and then it hangs again)

Running the following command fixed the problem

```bash
$ docker run --log-driver json-file \
  --log-opt max-size=10k \
  --log-opt max-file=2 \    # <-- 2 here instead of 1
  -d centos \
  bash -c "i=0; while ((++i)); do echo \$i hello world; sleep 0.1; done"
```

I think the problem often occurs when one sets the `--log-opt max-size` flag without setting the `--log-opt max-file`. In that case, `--log-opt max-file` default to 1 ([see here](https://docs.docker.com/config/containers/logging/json-file/#options))

I tried reading the code but failed to grasp the source of the problem. However I found that comment: https://github.com/moby/moby/blob/916eabd459fe707b5c4a86377d12e2ad1871b353/daemon/logger/loggerutils/logfile.go#L305-L307 that might give pointers to someone fixing the bug

Btw, @flosell the Datadog Agent uses the `github.com/docker/docker/client` just like (I think) the docker CLI so that should be the same problem.

**Comment by thaJeztah** [comment] 2018-12-20 12:00
@cpuguy83 I seem to recall we did fix this in the past; could it be a regression?

**Comment by cpuguy83** [comment] 2018-12-20 17:34
Does this reproduce when max-file is 2?
I'd suggest we just bump the default max-file when max-size is provided to 2 from 1.

**Comment by achntrl** [comment] 2018-12-20 17:41
> Does this reproduce when max-file is 2?

No, `docker logs -f` command works as expected with `max-file=2`

Defaulting to 2 would be ok for our use case.

The only drawback I see for a general user, is that you expect your logs to take at most `max-size` on disk and yet, you can reach `max-size * 2`

**Comment by thaJeztah** [comment] 2018-12-20 19:09
Perhaps we could do something like (haven't checked into the code, so just thinking out loud);

- rename old file
- create new file
- attach to new file
- remove old one

**Comment by achntrl** [comment] 2018-12-20 23:09
That might work because that's more or less what it does for max-file >= 2, I'll give it a shot and open a PR if that's OK

**Comment by thaJeztah** [comment] 2018-12-20 23:11
That'd be great, thanks!

**Closed** 2022-05-19 20:50 UTC
Labels: area/logging, kind/bug, status/confirmed, version/18.03, version/18.09
