### ISSUE TITLE
`COPY --from=foo bar.tgz ...`

### ISSUE THREAD

**Issue by elibarzilay** [moby/moby#37112] opened 2018-05-20 23:00 UTC
It looks like `COPY` does not untar files when they're coming from a
previous stage.  It would be good if it would.

Use case: I'm trying to minimize an ubuntu image by creating a tgz with
some parts left out in one stage, then using the tgz in a scratch stage.
This is to avoid the problem of using `COPY` which loses ownership and
set[ug]id information.  The thing is that I cannot use `ADD` since it
doesn't have a `--from`; I cannot use `COPY` since it won't unpack the
tgz; and I cannot copy and *then* unpack the tgz since there is no
`/bin/sh` so a `RUN` fails too (complaining that there is no `/bin/sh`).

**Comment by arm64b** [comment] 2018-05-21 09:01
@elibarzilay 

Below Dockerfile can work well with `COPY --from` to copy a .tgz file:
```
FROM ubuntu AS foo
RUN tar -cvzf bar.tgz /usr/bin
FROM scratch
COPY --from=foo /bar.tgz /
```
`docker build -t tgz-test  .`

Can you paste your Dockerfile and the step how to reproduce it here?

**Comment by elibarzilay** [comment] 2018-05-21 20:18
@arm64b See my last sentence: the problem is that the tgz is not unpacked, and since it's scratch, it's impossible to `RUN` a command to unpack it.  (Also, if there was, then there would be a problem of having the tgz in its own layer consuming precious space.)

**Comment by arm64b** [comment] 2018-05-22 02:14
@elibarzilay  Don't know if it's expected behavior just copy (while not unpack) tgz file, then use other method to unpack it... 
ping @thaJeztah and @tonistiigi

**Comment by elibarzilay** [comment] 2018-05-22 04:16
@arm64b AFAICT, `COPY` doesn't unpack so I want `ADD`, but that doesn't support `--from`.  That's the reason I opened this issue.

**Comment by thaJeztah** [comment] 2018-05-22 12:29
This looks like a duplicate of https://github.com/moby/moby/issues/36759, but the actual issue is that ownership is not preserved when copying between stages https://github.com/moby/moby/issues/36759#issuecomment-387543600

I opened a proposal for that: https://github.com/moby/moby/issues/37123


Closing because this is a duplicate of https://github.com/moby/moby/issues/36759

**Closed by thaJeztah** 2018-05-22 12:29 UTC
Labels: area/builder, kind/enhancement
