### ISSUE TITLE
Docker upload progress bar is a lie

### ISSUE THREAD

**Issue by MichaelJCole** [moby/moby#29253] opened 2016-12-08 15:12 UTC
**Description**

**Steps to reproduce the issue:**
1.  Build and image
2.  Push that image

**Describe the results you received:**

```
# build and push
docker build -t $REPO:$VERSION . || exit
docker push $REPO:$VERSION
```

Shows a progress bar on the push.  It promises to upload x of 123mb, then uploads 146mb.  That's an extra 20mb.  You're off by 15%, and I'm staring at this damn upload progress bar like an idiot thinking it's done any second.

**Describe the results you expected:**

Either no progress bar - a spinner, or a progress bar that delivers on it's promise.  Or at least lies in the other direction.  Feel free to underpromise and overdeliver by adding 20% to the estimate.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.3, build 6b644ec
```

**Output of `docker info`:**

```
Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 698
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 338
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-21-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.59 GiB
Name: mc-desktop
ID: WQYL:6ONJ:SB3J:3CQS:UMVD:C2BC:5ARU:K65E:TCG3:V42Y:BMSY:B7HH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: michaelcole
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This happens when pushing to Docker Registry and AWS.

**Comment by thaJeztah** [comment] 2016-12-08 17:16
Looks like a duplicate of https://github.com/docker/docker/issues/21536

**Comment by thaJeztah** [comment] 2020-08-19 07:30
Let me close this one in favour of https://github.com/moby/moby/issues/21536

**Closed by thaJeztah** 2020-08-19 07:30 UTC
Labels: area/builder, area/distribution
