### ISSUE TITLE
Change of behavior of routing packets since docker v25

### ISSUE THREAD

**Issue by pseusys** [moby/moby#47145] opened 2024-01-21 04:29 UTC
### Description

In my [project](https://github.com/pseusys/SeasideVPN/tree/dev/whirlpool-algae-mvp), for testing purposes I have the following setup:
There are two containers, `client` and `server`. Both `client` and `server` are connected to an internal bridge network, `server`is also connected to a regular bridge network.
When `client` tries to connect to an external IP (e.g. 8.8.8.8), it can not resolve the address (since the container is connected to an internal network only). In that case the packet gets marked by `iptables -j MARK` then it is forwarded to a special ip routing table (using `ip rule fwmark lookup`) and then via this table it gets routed to `server` container and to internet from there.

This setup worked with docker 24, but since docker 25 no packets are being forwarded anymore and connection fails with error message `[Errno 101] Network is unreachable`. Unfortunately, I do not have an opportunity to try the same setup with two physical computers or virtual machines, so could you please help me finding out: which behavior is expected for two real machines?
Will my setup work for two physical computers instead of two containers (like in docker 24) or will it fail (like in docker 25)?

### Reproduce

Here's a little simplified setup of my issue:

`compose.yml`:

```yaml
version: "3.3"

services:
  client:
    build:
      dockerfile: Dockerfile
    privileged: true
    entrypoint: [ "/bin/sh", "client-startup.sh" ]
    networks:
      internal_network:
        ipv4_address: 10.65.0.65
    depends_on:
      - server

  server:
    build:
      dockerfile: Dockerfile
    privileged: true
    entrypoint: [ "/bin/sh", "server-startup.sh" ]
    networks:
      internal_network:
        ipv4_address: 10.65.0.87
      external_network:
        ipv4_address: 10.87.0.87


networks:
  internal_network:
    internal: true
    ipam:
      config:
        - subnet: 10.65.0.0/24
          gateway: 10.65.0.1
  external_network:
    ipam:
      config:
        - subnet: 10.87.0.0/24
          gateway: 10.87.0.1
```

`Dockerfile`:

```dockerfile
FROM alpine:3.18

RUN apk add --no-cache iptables

COPY ./*.sh ./
```

`client-startup.sh`:

```shell
#! /bin/sh

echo "setup iptables..."
iptables -t mangle -A OUTPUT --src "10.65.0.65" -o eth0 --dst "10.65.0.87" -j ACCEPT
iptables -t mangle -A OUTPUT -o eth0 ! --dst "10.65.0.0/24" -j MARK --set-mark 0x41
iptables -t mangle -A OUTPUT -o eth0 ! --dst "10.65.0.0/24" -j ACCEPT

echo "setup ip rule and route..."
ip rule add fwmark 0x41 lookup 65
ip route replace default via "10.65.0.87" table 65

echo "check connection..."
wget -T 5 -O - "8.8.8.8"

echo "check config..."
ip rule list
ip route show table 65
iptables -t mangle -vnL
```

`server-startup.sh`:

```shell
#! /bin/sh

echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
iptables -A FORWARD -i eth0 -j ACCEPT
iptables -A FORWARD -i eth1 -j ACCEPT

sleep infinity
```

### Expected behavior

After running `docker compose up --build client` I expect to see connection message, but see something like `wget: can't connect to remote host (8.8.8.8): Network unreachable` instead.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 928
 Server Version: 25.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Linux Mint 21.3
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.49GiB
 Name: ascension
 ID: ICV5:5ZVX:MTEJ:XVHM:C72A:IQ37:IU3B:RSAV:X625:WWPZ:PNGO:KS7W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Again, I'm not claiming that this or previous behavior is **correct**, I've just noticed (potentially undocumented?) change and would like to point that out. Also, if I'm doing something wrong, it would be great if you could spare a minute and give me an advice on what is the problem with my approach.

**Comment by thaJeztah** [comment] 2024-01-21 10:56
> Again, I'm not claiming that this or previous behavior is correct, I've just noticed (potentially undocumented?) change and would like to point that out

Thanks for reporting! Not sure either, but let me ping @akerouanton @robmry @corhere who may know 🤗 

I added this to the v25.0.1 milestone (more as a reminder) so that, in case it's an _unintended_ change, we could perhaps ship a patch (or update documentation to outline the behaviour)

**Comment by robmry** [comment] 2024-01-21 16:49
Thank you for the simplified example - it made this easy to look at ...

The difference between the two builds is that "internal" network bridges are no longer assigned a default gateway (https://github.com/moby/moby/pull/46603).

So, packets are dropped early - before the mangle OUTPUT chain.

Adding any default route to the client-startup.sh script restores the old behaviour. For example, the address that would have been added in the v24 build, `ip route add default via 10.65.0.1`.

But, then the packet is dropped anyway by the DOCKER-ISOLATION iptables rules on the host ...

```
Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-ISOLATION-STAGE-2  0    --  br87   !br87   0.0.0.0/0            0.0.0.0/0
    0     0 DROP       0    --  *      br65   !10.65.0.0/24         0.0.0.0/0
    8   480 DROP       0    --  br65   *       0.0.0.0/0           !10.65.0.0/24
```

The change was intended to make a connect to something that isn't on the internal network fail fast, because of the missing route, rather than on a timeout when there's no response.

(Have you done something-else to get the packet from the client container to the server?)

**Comment by pseusys** [comment] 2024-01-21 18:28
Ok, so as far as I understood in case of two **physical** computers my setup would work, and what I have seen is just a new limitation of Docker?

I haven't done anything else because that is the only way of forwarding ALL traffic without resetting default ip route (in default table) that I know.

Maybe there is another (better?) way to do this? Maybe I could restrict the `client` container from accessing at least some of the addresses without making `internal_network`, well, internal?
Otherwise it's not a big deal, I can continue with docker v24, but in that case I believe such a limitation should be described in Docker `internal` network attribute description.

**Comment by akerouanton** [comment] 2024-01-22 08:23
> Ok, so as far as I understood in case of two physical computers my setup would work, and what I have seen is just a new limitation of Docker?

You're currently expecting the default routing table to have a route to 0.0.0.0/0, but that's really up to the system administrator, or whichever software is used to configure the networking stack, to add one or not. In our case, the presence of such a route is an implementation detail and shouldn't be taken for granted. As such, I think your assumption is wrong and should be revised.

> Otherwise it's not a big deal, I can continue with docker v24, but in that case I believe such a limitation should be described in Docker internal network attribute description.

Thanks for calling this out. It looks like our release notes miss an entry about this change.

**Comment by thaJeztah** [comment] 2024-01-23 23:07
IIUC; the change was intentional, and releasee notes were updated in this PR;

- https://github.com/docker/docs/pull/19173

I'll go ahead and close this ticket, but feel free to comment if I closed by mistake, and there's still things to address 😅

**Closed by thaJeztah** 2024-01-23 23:07 UTC
Labels: status/0-triage, kind/bug, area/networking, version/25.0

**Comment by AJHoeh** [comment] 2024-01-24 13:20
> Thank you for the simplified example - it made this easy to look at ...
> 
> The difference between the two builds is that "internal" network bridges are no longer assigned a default gateway (#46603).
> 
> So, packets are dropped early - before the mangle OUTPUT chain.
> 
> Adding any default route to the client-startup.sh script restores the old behaviour. For example, the address that would have been added in the v24 build, `ip route add default via 10.65.0.1`.
> 
> But, then the packet is dropped anyway by the DOCKER-ISOLATION iptables rules on the host ...
> 
> ```
> Chain DOCKER-ISOLATION-STAGE-1 (1 references)
>  pkts bytes target     prot opt in     out     source               destination
>     0     0 DOCKER-ISOLATION-STAGE-2  0    --  br87   !br87   0.0.0.0/0            0.0.0.0/0
>     0     0 DROP       0    --  *      br65   !10.65.0.0/24         0.0.0.0/0
>     8   480 DROP       0    --  br65   *       0.0.0.0/0           !10.65.0.0/24
> ```
> 
> The change was intended to make a connect to something that isn't on the internal network fail fast, because of the missing route, rather than on a timeout when there's no response.
> 
> (Have you done something-else to get the packet from the client container to the server?)

Sooo, I'm not completely sure if I get it right (sorry, I have no clue about all this network/routing stuff) but does that mean that from now on I cannot access a service I run in a container attached to an internal network via its ip from the host machine anymore?

Until now I used to run a local jupyter server without internet connection using docker-compose files like this:

`version: '3'
services:
  jupyter:
    image: IMAGE_NAME
    networks:
      isolated:
        ipv4_address: 172.22.1.0
    expose:
      - "8888"
    ports:
      - "8888:8888"
networks:
  isolated:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.22.0.0/16`

**Comment by robmry** [comment] 2024-01-24 18:16
> Ok, so as far as I understood in case of two physical computers my setup would work, and what I have seen is just a new limitation of Docker?

It might be worth clarifying that it isn't a new limitation...

In v24, packets from your 'client' with a destination IP that wasn't on the internal network's subnet would have been dropped by the DOCKER-ISOLATION rules. The `wget` didn't establish a TCP connection, it sent SYN packets that were dropped, so it didn't get any response. (If you try the `wget` with an address that has an HTTP server, rather than Google's DNS server on `8.8.8.8`, you'll see that there's no response.)

The difference in v25 is that it will fail more quickly, lack of a default route means it doesn't have to wait for a timeout.

In v25, after manually adding any default route, packets will again get as far as the host's DOCKER-ISOLATION iptables rule, where they'll still be dropped. So, as with v24, the `wget` won't be able to establish a TCP connection.

> does that mean that from now on I cannot access a service I run in a container attached to an internal network via its ip from the host machine anymore?

It does, and that is a change ... but, if you want external access to the network, why are you creating it as internal?

You're also mapping port 8888 so, if you don't create the network as internal, you'll be able to access the Jupyter server on the host's addresses as well as the container's address.

**Comment by AJHoeh** [comment] 2024-01-25 07:53
Thanks for your answer! 

> It does, and that is a change ... but, if you want external access to the network, why are you creating it as internal?

I wanted container I could reach from the machine they are running on and which are at the same time cut from a direct internet connection. Using the internal flag seemed like the easiest option to achieve this but it is definitely possible I misunderstood what it exactly does (even though it seemed as it achieved exactly what I wanted)

**Comment by ap-wtioit** [comment] 2024-01-25 08:32
Just stumbled across the change in the docker internal networks. Wanted to document it here so people (me included) can find it later again.

Previous to docker 25 internal networks (at least on Debian and Ubuntu) would be reachable by the host (e.g. one could docker inspect a container and connect to it by it's IP directly from the host). In docker 25 this is no longer the case.

on docker 24:
```bash
docker network create test_internal --internal
# ouputs cceaff0b319d1ae0704b0c9d247344eb32cd425a818ab064a506d4358cb387f3
ip addr | grep -A 5 cceaff0
# outputs
# 325473: br-cceaff0b319d: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
#     link/ether 02:42:a6:ea:86:02 brd ff:ff:ff:ff:ff:ff
#     inet 172.23.201.129/26 brd 172.23.201.191 scope global br-cceaff0b319d
#        valid_lft forever preferred_lft forever
```

on docker25:
```bash
docker network create test_internal --internal
# ouputs 54cec9a6cb9f06f7effdd18075598422c545cb3099cd269a374a1e564e0af334
ip addr | grep -A 5 54cec9a
# outputs
# 155: br-54cec9a6cb9f: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
#     link/ether 02:42:4c:26:3a:c7 brd ff:ff:ff:ff:ff:ff
```

not sure if this is also covered by the note in https://github.com/docker/docs/pull/19173, at least to us it was unexpected.

**Comment by bananarne** [comment] 2024-02-04 22:29
> Thanks for your answer!
> 
> > It does, and that is a change ... but, if you want external access to the network, why are you creating it as internal?
> 
> I wanted container I could reach from the machine they are running on and which are at the same time cut from a direct internet connection. Using the internal flag seemed like the easiest option to achieve this but it is definitely possible I misunderstood what it exactly does (even though it seemed as it achieved exactly what I wanted)

Yeah, i used this as a feature, too. Is there a way to get the old behaviour?

**Comment by ap-wtioit** [comment] 2024-02-05 06:35
> Is there a way to get the old behaviour?

we have the following ansible tasks to call `ip addr add ... dev ...` on such interfaces:
```yaml
- name: get network info
  community.docker.docker_network_info:
    name: "{{network}}"
  register: network_info
- name: ip parameters
  set_fact:
    ip_addr: "{{network_info.network.IPAM.Config[0].Gateway}}/{{network_info.network.IPAM.Config[0].Subnet | regex_replace('.*/', '')}}"
    ip_dev: "br-{{network_info.network.Id[:12]}}"
- name: check ip addr
  command:
    argv: ["ip", "addr", "show", "{{ip_dev}}"]
  register: ip_addr_info
  changed_when: False
- name: make network accessible from host (only)
  become: True
  command:
    argv: ["ip", "addr", "add", "{{ip_addr}}", "dev", "{{ip_dev}}"]
  when: "'inet '+ ip_addr + ' ' not in ip_addr_info.stdout"
```
you can also manually do it, but beware if the network is recreated

but hoping that we get an official way to restore that behaviour.

**Comment by robmry** [comment] 2024-02-07 21:43
Thank you all for the good descriptions of your use-cases - we'll put back the address on the internal network's bridge, without adding back the default route in the container (so that containers will have IP connectivity to the bridge, on the host, but attempts to connect to an off-subnet address will still fail fast).

As this one issue's closed, and covers a few things - I'll use the linked issue https://github.com/moby/moby/issues/47329 to track the change.
