### ISSUE TITLE
Different port number are getting mapped on ipv4 and ipv6 for same expose port

### ISSUE THREAD

**Issue by gkhandake** [moby/moby#42442] opened 2021-05-31 06:25 UTC
**Description**

With docker version ` 20.10.6, build 370c289` observed that different port is assigned for same exposed port on ipv4 and ipv6. This is causing random failures in application with docker compose up which spawns many different apps containers

```
$ docker ps --format "{{.Ports}}"
0.0.0.0:49338->9999/tcp, :::49337->9999/tcp
0.0.0.0:49339->6379/tcp, :::49338->6379/tcp
0.0.0.0:49319->6379/tcp, :::49318->6379/tcp
```

**Steps to reproduce the issue:**
1. Install docker version '20.10.6, build 370c289'
2. use docker-compose up with multiple types of container and expose a port on each container

**Describe the results you received:**
1. Observe post docker compose up the ipv4 and ipv6 uses different ports 

**Describe the results you expected:**
1. the 1 port should be used for both ipv4 and ipv6 ports for a exposed port

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
20.10.6, build 370c289
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ncopa** [comment] 2021-06-11 13:24
This is observed on

```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:27 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

`docker ps` shows that the ssh `->22/tcp` ports gets different for ipv4 and ipv6.
```
bcfabeb4ee32   footloose-alpine   "/sbin/init"             23 minutes ago   Up 23 minutes   0.0.0.0:51501->22/tcp, :::51500->22/tcp, 0.0.0.0:51500->6060/tcp, :::51499->6060/tcp, 0.0.0.0:51499->6443/tcp, :::51498->6443/tcp, 0.0.0.0:51498->9443/tcp, :::51497->9443/tcp, 0.0.0.0:51497->10250/tcp, :::51496->10250/tcp   TestBasicSuite-controller0
```

This seems to happen after docker has been running a while (a few weeks) and/or have many left-over containers.

This happens in an 32 bit armv7 ubuntu lxc container on an aarch64 ubuntu host.

**Comment by gkhandake** [comment] 2021-06-16 12:28
Any update on this?

Even a simple docker run after keeping the daemon running for long time we can see this being reproduced:
```sh
# docker run --rm -it -p 6650 -p 8080 apachepulsar/pulsar-standalone:2.7.2
...
```
On another terminal:

```sh
# docker ps
CONTAINER ID   IMAGE                                  COMMAND            CREATED          STATUS          PORTS                                                                                              NAMES
883b78808f76   apachepulsar/pulsar-standalone:2.7.2   "supervisord -n"   24 seconds ago   Up 23 seconds   80/tcp, 0.0.0.0:49686->6650/tcp, :::49685->6650/tcp, 0.0.0.0:49685->8080/tcp, :::49684->8080/tcp   pedantic_zhukovsky

```

This causes the services to be not accessible e.g.
```sh
# curl --verbose http://localhost:49685/admin/v2/brokers/ready
* About to connect() to localhost port 49685 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 49685 (#0)
> GET //admin/v2/brokers/ready HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:49685
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by gkhandake** [comment] 2021-06-16 13:02
Update.. after daemon restart the ports are correctly assigned.. however we can not restart daemon frequently
```sh
# systemctl restart docker
...
# docker run --rm -it -p 6650 -p 8080 apachepulsar/pulsar-standalone:2.7.2
```

From another terminal
```sh
# docker ps
CONTAINER ID   IMAGE                                  COMMAND            CREATED          STATUS          PORTS                                                                                              NAMES
26792898aea6   apachepulsar/pulsar-standalone:2.7.2   "supervisord -n"   24 seconds ago   Up 23 seconds   80/tcp, 0.0.0.0:49158->6650/tcp, :::49158->6650/tcp, 0.0.0.0:49157->8080/tcp, :::49157->8080/tcp   angry_gates

# curl --verbose http://localhost:49157/admin/v2/brokers/ready
* About to connect() to localhost port 49157 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 49157 (#0)
> GET /admin/v2/brokers/ready HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:49157
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 16 Jun 2021 12:52:14 GMT
< broker-address: localhost
< Content-Type: application/json
< Content-Length: 2
< Server: Jetty(9.4.39.v20210325)
< 
* Connection #0 to host localhost left intact
ok
```

**Comment by nathwill** [comment] 2021-09-15 00:57
confirming that we're experiencing this as well, the same host port is getting mapped twice onto different container ports, resulting in randomly broken packet routing.

**Comment by dhs-rec** [comment] 2021-12-08 14:10
Same here. Any news?

**Comment by jonnybbb** [comment] 2021-12-08 15:48
Is there any workaround available, other than downgrading? Is there any logging available we could provide to you to further investigate the issue.

**Comment by f18m** [comment] 2022-01-26 09:48
Hi @thaJeztah ,
I've been reading your comments on https://github.com/moby/moby/pull/41805.
Do you know if there's any way to ask docker daemon to stop exposing ports over IPv6 and limit it to use only IPv4 ?

That would help a lot as a workaround to this bug (which was created almost 1year ago btw!!) 

Thanks!

**Comment by allwinchristopher** [comment] 2022-02-08 14:49
We have been frequently encountering the same port mapping issue with latest docker engine. If there are any further updates to this same thread please share us the info.

**Comment by tturbs** [comment] 2022-02-25 00:44
If task Endpoint's ports info tells more information like binding address or type, many of the problem could be handled.
Reference: https://github.com/aws/amazon-ecs-agent/pull/3112

**Comment by n1ngu** [comment] 2022-09-05 11:54
I am starting multiple testcontainers and the same port leads to different services if accessed via 127.0.0.1 or via ::1

This can be disastrous.

**Comment by n1ngu** [comment] 2022-11-22 15:46
@kiview I was using python's testcontainers package https://pypi.org/project/testcontainers , I will guess it was version 3.6.1 at that time, but I couldn't tell.

While it is clearly technically possible to bind an application to different port numbers on each internet protocol version, I know of no other software that does anything similar. Just as you could also bind to different ports on different IPv4 network interfaces, but you never would.

I guess there is some kind of event that introduces a leap between IP v4 and v6 ports sequences, which were intentionally aligned otherwise. This betrays very basic intuitions on how IP works and I honestly think this a bug beyond debate, not a corner case.

Darn, in a dual stack network this causes a simple `hostname:port` connection attempt to route to different applications depending on the IPv6 (in)capabilities of both the software and hardware involved in each connection!

**Comment by dhs-rec** [comment] 2022-11-23 06:56
> @n1ngu Can you share which version of Testcontainers are you using when you observe this issue? This seems to be related to [dotnet/Docker.DotNet#565](https://github.com/dotnet/Docker.DotNet/issues/565) as well.

No, it's not. It doesn't matter which container is used. We're seeing this on our custom (Linux) containers we use for building. And when it happens, I can try whatever image I want. The problem persists until Docker has been restarted.

**Comment by kiview** [comment] 2022-11-23 07:56
Thanks for sharing that you used the Python implementation @n1ngu. That confirms that this is likely no Testcontainers language implementation specific issue (e.g., the bug observed for .NET) but present in all Testcontainers implementations, regarding the assumptions about how Docker maps random ports. 

It would be great to get a confirmation from the Docker team whether this is a bug (which I would assume, since very unintuitive and likely caused by some race conditions and misaligned internal state) or it works as intended and we as a client integrating against Docker need to take care of it (our even our users).

**Comment by kiview** [comment] 2023-03-01 11:53
Looping back to this https://github.com/moby/moby/pull/41805#issuecomment-893349240 from @thaJeztah, shall we assume this behaviour works as intended and there are no guarantees about them being mapped onto the same port?

**Comment by n1ngu** [comment] 2023-03-01 11:59
> shall we assume this behaviour works as intended and there are no guarantees about them being mapped onto the same port?

No.

Loopback to https://github.com/moby/moby/issues/42442#issuecomment-1323880838

> Darn, in a dual stack network this causes a simple `hostname:port` connection attempt to route to different applications depending on the IPv6 (in)capabilities of both the software and hardware involved in each connection!

This is unacceptable behaviour. Period.

**Comment by dhs-rec** [comment] 2023-03-01 12:17
... since nearly two years now. When will this get fixed?

Since a service restart is required to get correct behaviour again, this is a `DoS` bug.

**Comment by thaJeztah** [comment] 2023-03-01 12:35
As to this being a "DoS" bug; this issue happens when using randomly selected ports from the ephemeral port range; for those, there are no guarantees in any form for those ports to be the same when (re)starting a container or service. If a stable, predictable port is important, then specifying the port-mapping is the correct approach.


As to; assigning the same (random) port for IPv4 and IPv6 mappings; contributions welcome if someone is interested in looking into this.

**Comment by dhs-rec** [comment] 2023-03-01 13:32
That's what this issue is all about: The port mapping for IPv4 and IPv6 start to differ after some time of operation (days, weeks), although a mapping IS specified. At this point, no containers can be started anymore unless the Docker service is restarted. This didn't happen in versions before 20.10.x.

**Comment by thaJeztah** [comment] 2023-03-01 13:59
>  although a mapping IS specified

I think the examples above only specify a port to be mapped, but not specify a fixed host port, e.g. this example;

```bash
docker run --rm -it -p 6650 -p 8080 apachepulsar/pulsar-standalone:2.7.2
```

Only specifies the container ports (`6650` and `8080`), but no host-port, so no fixed mapping. In this case, the host-port will be randomly selected from the ephemeral port range.

Does the issue also reproduce if you specify a host port? e.g.;

```bash
docker run --rm -it -p 1234:6650 -p 1235:8080 apachepulsar/pulsar-standalone:2.7.2
```

**Comment by dhs-rec** [comment] 2023-03-01 14:05
Yes, it does. This is what Jenkins does, for example, to map container port 22 to some port above 49000, like
`0.0.0.0:49206->22/tcp, :::49206->22/tcp`

**Comment by kiview** [comment] 2023-03-02 09:25
@dhs-rec Are you sure Jenkins specifies fixed port mappings? Do you know the part of the Jenkins code that handles this? Because mapping into the ephemeral port range looks like Docker port publishing rather than mapping. 

In Testcontainers, we need ports dynamically published into free ports into the ephemeral port range, but IPv4 and IPv6 port to be the same. We'd be happy to look into contributing such a fix for publishing random ports 👍

**Comment by dhs-rec** [comment] 2023-03-03 06:41
Good question. T.b.h., I don't know how the Jenkins Docker plugin handles this.

**Comment by m8719-github** [comment] 2023-05-02 20:27
If you run: `docker run -p 0.0.0.0::<container-port> ...` it does not map the IPv6 port

**Comment by martimors** [comment] 2024-01-05 15:40
I came here via https://github.com/dotnet/Docker.DotNet/issues/511, and I'm a bit at a loss what to do. Would you say this is a #wontfix on your end, and that the testcontainers project should choose random ports from a lower range, or is this still a bug worth fixing at this level?

**Closed** 2024-06-13 08:12 UTC
Labels: area/networking, version/20.10, area/networking/ipv6, area/networking/portmapping
