### ISSUE TITLE
docker swarm mode  service alternate acess or unrechable

### ISSUE THREAD

**Issue by Lenilying** [moby/moby#33977] opened 2017-07-06 07:52 UTC
**Description**

**Steps to reproduce the issue:**
1. docker exec -it  xxxx  /bin/sh into a container enviroment
2. then wget the api like  http://ask-product-service:8082/
3. the result output alternate connectioned or Connection refused

**Describe the results you received:**
/ # Connecting to ask-product-service:8082 (10.0.3.22:8082)
wget: server returned error: HTTP/1.1 405
^C
/ # wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02&commodityType=KC
[2]-  Done(1)                    wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02
/ # Connecting to ask-product-service:8082 (10.0.3.21:8082)
wget: can't connect to remote host (10.0.3.21): Connection refused
^C
/ # wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02&commodityType=KC
[1]-  Done(1)                    wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02
/ # Connecting to ask-product-service:8082 (10.0.3.22:8082)
wget: server returned error: HTTP/1.1 405
^C
/ # wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02&commodityType=KC
[2]-  Done(1)                    wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02
/ # Connecting to ask-product-service:8082 (10.0.3.21:8082)
wget: can't connect to remote host (10.0.3.21): Connection refused
^C
/ #
[1]+  Done(1)                    wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02
/ # ^C
/ # wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02&commodityType=KC
/ # Connecting to ask-product-service:8082 (10.0.3.22:8082)
wget: server returned error: HTTP/1.1 405
^C
/ #
[1]+  Done(1)                    wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02
/ # ^C
/ # wget http://ask-product-service:8082/product/commodity/find?commdityId=KC-KC01-KM01-MCSG02&commodityType=KC
/ # Connecting to ask-product-service:8082 (10.0.3.21:8082)
wget: can't connect to remote host (10.0.3.21): Connection refused
^C

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Lenilying** [comment] 2017-07-06 07:55
docker swarm mode   the tasks in the vip of a service is exsits a bad one?  can i reset the meta data in the docker manager under  raft

**Comment by thaJeztah** [comment] 2017-07-08 10:25
Please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code.
- provide relevant parts of the daemon and system logs, preferable with the docker daemon running in debug mode

Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'll close this issue for now, because there's not enough information, but we can reopen once provided

**Closed by thaJeztah** 2017-07-08 10:25 UTC
Labels: area/swarm

**Comment by Lenilying** [comment] 2017-07-11 10:03
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   8968bcd
 Built:        Fri May 26 08:24:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   8968bcd
 Built:        Fri May 26 08:24:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by Lenilying** [comment] 2017-07-11 10:04
docker info
Containers: 16
 Running: 11
 Paused: 0
 Stopped: 5
Images: 11
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: ossfs local acd nas
 Network: bridge host macvlan null overlay
Swarm: active
 Is Manager: true
 Managers: 3
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
 Expiry Duration: 3 months
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.6-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.795 GiB
Name: cff16a79e6c7144109b1778dc785a6f50-node4
ID: 73BH:WZEP:KUNP:7D52:QYA5:FHXO:DTU5:QWLK:2XH2:YQ72:QNS3:HV3V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
