### ISSUE TITLE
docker swarm service container connect different nodes

### ISSUE THREAD

**Issue by zsluedem** [moby/moby#35127] opened 2017-10-08 08:35 UTC
Now I have three machines A,B,C.  I set up the swarm mode among these three nodes.
And I start a service through swarm mode.

The service would start a container in A machine. I know the container is attached to two networks, the docker_gwbridge and the ingress.

below is the output  which i executed a command **ip addr** in the container:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.255.0.5/32 scope global lo
       valid_lft forever preferred_lft forever
37: eth0@if38: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 02:42:0a:ff:00:05 brd ff:ff:ff:ff:ff:ff
    inet 10.255.0.5/16 scope global eth0
       valid_lft forever preferred_lft forever
39: eth1@if40: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:13:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.3/16 scope global eth1
       valid_lft forever preferred_lft forever
```

I know i can connect the host machine through the docker_gwbridge which is  "172.19.0.1" pointing to A machine.
But What if I want to connect B or C machine directly?

I try to use the ingress network but it seemed I can't connect the external network through ingress.
I thought the 10.255.0.1 was pointing to A machine and 10.255.0.2 was pointing to B machine respectively.

I was looking for the solution from the Internet for quite a long time, but I can't find it.

So is there a way to connect other node machines  in swarm mode?

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 22
 Running: 3
 Paused: 0
 Stopped: 19
Images: 52
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: i8ixhnetqogvnqi69jlbbhlff
 Is Manager: true
 ClusterID: xaea4p60fr6d36f0pcn3af4rq
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.99.100
 Manager Addresses:
  192.168.99.100:2377
  192.168.99.101:2377
  192.168.99.102:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.26GiB
Name: cdh1
ID: HU2U:D7N6:KWQV:UTM5:7HJZ:EXKY:IH7D:UNKS:CRNO:URC2:ACWE:ABBK
Docker Root Dir: /data/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 cdh1:5000
 cdh2:5000
 cdh3:5000
 127.0.0.0/8
Registry Mirrors:
 https://docker.mirrors.ustc.edu.cn/
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-10-08 11:10
By default, service ports are published using the routing mesh; you can access a service's port on any node in the swarm, even if there's no instance of that service running on that node. The ingress network routes the traffic to a node where an instance of the service runs.

If you don't want to use the routing mesh and built-in loadbalancer, you can use "host mode" publishing of the port; in that case, the containers ports are only published on the node that the container runs. For example;

     --publish mode=host,target=80,published=8080


You can find more information in the documentation here; https://docs.docker.com/engine/swarm/services/#publish-ports

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-10-08 11:10 UTC
Labels: area/swarm, version/17.09

**Comment by zsluedem** [comment] 2017-10-08 12:43
@thaJeztah I think you misunderstand the question....
I want to connect to another node from the container which is not the running in THAT node. 
But it's fine, I'm going to ask in the forum.
Thanks all the same.

**Comment by thaJeztah** [comment] 2017-10-08 13:25
For containers to connect over an overlay network, both containers (/services) have to be connected to the same custom network. The "ingress" network does not allow connections between containers, because it's used purely for routing traffic between nodes (the routing mesh).

So, in short;

```bash
docker network create -d overlay mynetwork
docker service create --network=mynetwork --name one nginx:alpine
docker service create --network=mynetwork --name two nginx:alpine
```

Now any container part of service `one` can connect to service `two` using `two` as hostname.
