### ISSUE TITLE
Can't pull images from your Dockerfile into the container's Docker when using Docker in a container, because builds can't do priveleged actions and dockerd

### ISSUE THREAD

**Issue by adamnovak** [moby/moby#38698] opened 2019-02-09 00:01 UTC
**Description**

I'm trying to a Docker-in-Docker image as the base for a container, and pull some container images in that containerized Docker, and then make the system with those images pulled down a new container. The idea is to pre-load the images in the container to save on startup time.

(I'm taking this approach over docker:dind-as-a-service because I'm trying to containerize some code which itself expects to be able to run Docker containers and mount its local paths into them.)

My Docker file is something like this:

```
FROM docker:dind

RUN printf "dockerd & \n sleep 10 \n docker pull docker:dind" | sh
```

But `dockerd` can't start in the build container (because the container isn't privileged) and there's no way that I can find to start just enough of Docker to pull the images (which shouldn't require any special permissions).

See also: https://github.com/moby/moby/issues/1916 (which is about adding privileged command support to build). That's not quite the same as this issue; I'm looking to set up this Dockerfile with third-party automated builds, where I'm not likely to get privilege access inside the container. I just want the filesystem inside the container to have some already pulled and unpacked Docker images on it, which I can run when I am on my own infrastructure and I can grant privileged access.

Using https://github.com/moby/moby/blob/master/contrib/download-frozen-image-v2.sh would let me download the image data, but I'd still need to have `dockerd` running to actually put it in the correct place in the filesystem, so I'd have to do some setup when the container first starts in privileged mode somehow.

The recently merged rootless support https://github.com/moby/moby/pull/38050 is probably close to allowing me to do what I want, but I'm not sure how to use it to run `dockerd` as root and pointing to the "real" image storage locations, but with the necessary cgroup fakery. Also I don't think it has been released yet, so it's going to be hard to get ahold of.

**Steps to reproduce the issue:**
1. Make a Dockerfile like the one I show above, which tries to start up dockerd and pull an image.
2. Try to build the Dockerfile into a container: `docker build .` in the directory with the Dockerfile.
3. Observe 

**Describe the results you received:**

Here's the log:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM docker:dind
 ---> 3fadd0047bad
Step 2/2 : RUN printf "dockerd & \n sleep 10 \n docker pull docker:dind" | sh
 ---> Running in 4c2531174a4e
time="2019-02-08T22:48:32.780413921Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
time="2019-02-08T22:48:32.782693958Z" level=info msg="libcontainerd: started new containerd process" pid=21
time="2019-02-08T22:48:32.782758749Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-02-08T22:48:32.782778303Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-02-08T22:48:32.782879650Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-02-08T22:48:32.782926909Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-02-08T22:48:32.783032369Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4206e0080, CONNECTING" module=grpc
time="2019-02-08T22:48:32.923336675Z" level=info msg="starting containerd" revision=9754871865f7fe2f4e74d43e2fc7ccd237edcbce version=v1.2.2 
time="2019-02-08T22:48:32.923627694Z" level=error msg="failed to change OOM score to -500" error="write /proc/21/oom_score_adj: permission denied" 
time="2019-02-08T22:48:32.925968645Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." type=io.containerd.content.v1 
time="2019-02-08T22:48:32.926240683Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." type=io.containerd.snapshotter.v1 
time="2019-02-08T22:48:32.926714113Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
time="2019-02-08T22:48:32.926751122Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.aufs"..." type=io.containerd.snapshotter.v1 
time="2019-02-08T22:48:32.935192857Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "ip: can't find device 'aufs'\naufs                  241664  0 \nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
time="2019-02-08T22:48:32.935286166Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1 
time="2019-02-08T22:48:32.935747353Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1 
time="2019-02-08T22:48:32.936376313Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1 
time="2019-02-08T22:48:32.937230958Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
time="2019-02-08T22:48:32.937285815Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1 
time="2019-02-08T22:48:32.937508591Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
time="2019-02-08T22:48:32.937566907Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "ip: can't find device 'aufs'\naufs                  241664  0 \nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
time="2019-02-08T22:48:32.937607769Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
time="2019-02-08T22:48:32.953076820Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1 
time="2019-02-08T22:48:32.953197611Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1 
time="2019-02-08T22:48:32.953327181Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.953409351Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.953467380Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.953534775Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.953598969Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.953672236Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.953733871Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.953784058Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1 
time="2019-02-08T22:48:32.954484320Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2 
time="2019-02-08T22:48:32.954948044Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1 
time="2019-02-08T22:48:32.956467986Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1 
time="2019-02-08T22:48:32.956577322Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1 
time="2019-02-08T22:48:32.956721512Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.956774805Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.956821245Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.956869054Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.956940786Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.956995790Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.957041077Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.957086379Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.957132418Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1 
time="2019-02-08T22:48:32.957963366Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.958046100Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.958104596Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.958190489Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1 
time="2019-02-08T22:48:32.958769159Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock" 
time="2019-02-08T22:48:32.959010021Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock" 
time="2019-02-08T22:48:32.959069861Z" level=info msg="containerd successfully booted in 0.037104s" 
time="2019-02-08T22:48:32.968356266Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4206e0080, READY" module=grpc
time="2019-02-08T22:48:32.972433311Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-02-08T22:48:32.972461077Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-02-08T22:48:32.972636410Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-02-08T22:48:32.972652896Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-02-08T22:48:32.972707672Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-02-08T22:48:32.972767127Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-02-08T22:48:32.972852048Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42003bf50, CONNECTING" module=grpc
time="2019-02-08T22:48:32.973126569Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42003bf50, READY" module=grpc
time="2019-02-08T22:48:32.973403744Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-02-08T22:48:32.973496303Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-02-08T22:48:32.973761615Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4201ea230, CONNECTING" module=grpc
time="2019-02-08T22:48:32.974130788Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4201ea230, READY" module=grpc
time="2019-02-08T22:48:33.024820691Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2019-02-08T22:48:33.025372152Z" level=warning msg="Your kernel does not support swap memory limit"
time="2019-02-08T22:48:33.025492594Z" level=warning msg="Your kernel does not support cgroup rt period"
time="2019-02-08T22:48:33.025518285Z" level=warning msg="Your kernel does not support cgroup rt runtime"
time="2019-02-08T22:48:33.026485374Z" level=info msg="Loading containers: start."
time="2019-02-08T22:48:33.036817001Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nbridge                151552  1 br_netfilter\nstp                    16384  1 bridge\nllc                    16384  2 bridge,stp\nip: can't find device 'br_netfilter'\nbr_netfilter           24576  0 \nbridge                151552  1 br_netfilter\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
time="2019-02-08T22:48:33.042827058Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nnf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE\nnf_nat_h323            20480  0 \nnf_conntrack_h323      73728  1 nf_nat_h323\nnf_nat_pptp            16384  0 \nnf_nat_proto_gre       16384  1 nf_nat_pptp\nnf_conntrack_pptp      16384  1 nf_nat_pptp\nnf_nat_tftp            16384  0 \nnf_conntrack_tftp      16384  1 nf_nat_tftp\nnf_nat_sip             20480  0 \nnf_conntrack_sip       28672  1 nf_nat_sip\nnf_nat_irc             16384  0 \nnf_conntrack_irc       16384  1 nf_nat_irc\nnf_nat_ftp             16384  0 \nnf_conntrack_ftp       20480  1 nf_nat_ftp\nnf_nat_ipv4            16384  1 iptable_nat\nnf_nat                 32768  9 nf_nat_masquerade_ipv4,nf_nat_h323,nf_nat_pptp,nf_nat_proto_gre,nf_nat_tftp,nf_nat_sip,nf_nat_irc,nf_nat_ftp,nf_nat_ipv4\nnf_conntrack          131072 20 nf_conntrack_netlink,ipt_MASQUERADE,nf_nat_masquerade_ipv4,xt_conntrack,nf_nat_h323,nf_conntrack_h323,nf_nat_pptp,nf_conntrack_pptp,nf_conntrack_proto_gre,nf_nat_tftp,nf_conntrack_tftp,nf_nat_sip,nf_conntrack_sip,nf_nat_irc,nf_conntrack_irc,nf_nat_ftp,nf_conntrack_ftp,nf_conntrack_ipv4,nf_nat_ipv4,nf_nat\nlibcrc32c              16384  3 xfs,nf_nat,nf_conntrack\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
time="2019-02-08T22:48:33.047334211Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nxt_conntrack           16384  1 \nnf_conntrack          131072 20 nf_conntrack_netlink,ipt_MASQUERADE,nf_nat_masquerade_ipv4,xt_conntrack,nf_nat_h323,nf_conntrack_h323,nf_nat_pptp,nf_conntrack_pptp,nf_conntrack_proto_gre,nf_nat_tftp,nf_conntrack_tftp,nf_nat_sip,nf_conntrack_sip,nf_nat_irc,nf_conntrack_irc,nf_nat_ftp,nf_conntrack_ftp,nf_conntrack_ipv4,nf_nat_ipv4,nf_nat\nx_tables               40960  7 xt_addrtype,ipt_MASQUERADE,xt_conntrack,ipt_REJECT,xt_tcpudp,iptable_filter,ip_tables\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
time="2019-02-08T22:48:33.078964050Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
time="2019-02-08T22:48:33.080858723Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
time="2019-02-08T22:48:33.080930909Z" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
time="2019-02-08T22:48:33.083829464Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4201ea230, TRANSIENT_FAILURE" module=grpc
time="2019-02-08T22:48:33.084340596Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4201ea230, CONNECTING" module=grpc
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.2: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
The command '/bin/sh -c printf "dockerd & \n sleep 10 \n docker pull docker:dind" | sh' returned a non-zero code: 1
```

**Describe the results you expected:**

The Docker daemon should stay up even though it can't actually create any containers, and should be available to service requests to pull images and do other things that don't require special kernel permissions.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Note: this and `docker info` are for the non-containerized Docker doing the building.

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.787GiB
Name: hex
ID: L7UZ:47EN:IO6L:QF6P:ZDXG:Z4J4:G6BH:USNK:OKFL:BUBY:WYXN:7VEM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment] 2019-02-12 11:32
> The Docker daemon should stay up even though it can't actually create any containers, and should be available to service requests to pull images and do other things that don't require special kernel permissions.

This seems the scope of containerd rather than Docker, and containerd should be already able to do this.

**Comment by thaJeztah** [comment] 2023-09-14 10:58
I'll close this ticket, as this is a bit of an [XY problem](https://xyproblem.info); the docker engine requires privileged access (which `docker build` _by design_ does not allow (https://github.com/moby/moby/issues/1916)). _Possibly_ there are workarounds to run it as part of a `RUN` step in a Dockerfile, but that's mostly out of scope.

The underlying question seems to be "how do I build a (Docker-in-Docker) image with a `/var/lib/docker` directory that's pre-loaded with some images", and for that there may be other approaches (which could be to have a script "load" the images on start, or potentially to `COPY` files, but that would require experimenting).

Using other tools to pull images during build is also an option (but would still require loading the images into the daemon), and when using the containerd image store, it may be possible to seed containerd's content-store with artefacts that are pulled out-of-band.

I'll close this ticket, but feel free to continue the conversation.

**Closed by thaJeztah** 2023-09-14 10:58 UTC
Labels: area/builder, area/distribution
