### ISSUE TITLE
Bind a specific network interface for a particular overlay network

### ISSUE THREAD

**Issue by zero57** [moby/moby#34264] opened 2017-07-26 19:32 UTC
Hi, is there a way to bind a specific network interface for a particular overlay network? The reason for this is that DigitalOcean (as well as other cloud providers) offer private networking which allows you to communicate to other VMs within the same data center (region) without going over the public internet and being charged.

If I'm correct, the network interface that each overlay network created on a node goes over is specified when you join the swarm with `--advertise-addr`. Is it possible to somehow use this as a default, but in addition, when we create a new overlay network we can explicitly specify the network interface we want to use?

ie. `docker network create -d overlay --iface eth1 myoverlaynetwork` or `docker network create -d overlay --internal-ip PRIVATE_IP myoverlaynetwork`

In my opinion, this is not even an ideal approach to the problem because not every distribution names their network interfaces with ethX.

Ultimately, I want to define these overlay networks in a service stack config so I can `docker stack deploy` my services so that they go over the private network instead of the public internet.

Also, I have several services running in different regions/data centers, which communicate with each other through a global overlay network. The services that are running in the same region, however, should communicate through the private network interface which I am trying to do via another overlay network.

**Comment by der-datenpunk** [comment] 2017-09-29 15:06
same here! I need a way to bind ports of services to a specific network/interface.

**Comment by thaJeztah** [comment] 2017-10-31 13:38
Thanks for opening; this looks like a duplicate of https://github.com/moby/moby/issues/24317. I'll close this one to prevent the discussion from diverging, but feel free to participate in the discussion over there 👍

**Closed by thaJeztah** 2017-10-31 13:38 UTC
Labels: area/networking, kind/enhancement
