### ISSUE TITLE
Port ingress not open

### ISSUE THREAD

**Issue by cristhianbicca** [moby/moby#35688] opened 2017-12-04 13:27 UTC
Docker version 17.06.0-ce
Personally, I have a swarm cluster where I have 1 manager and 5 workers. I am having trouble connecting to services that are within the same network. When I ping a container that is on the same network as the other container, I get the following error:

``
[root]$ ping mymongo
``
``
ping: unknown host
``

When running a netstat -nltp on the server manager I realize that the only port that is open is the 2377.

On worker servers I get the following error in the logs:

``
level=error msg="Failed to join memberlist [192.192.0.2] on retry: 1 error(s) occurred:\n\n* Failed to join 192.192.0.2: dial tcp 192.192.0.2:7946: getsockopt: connection refused"
``

**Comment by thaJeztah** [comment] 2017-12-05 03:16
Looks like not all required ports are open between nodes, see: [Open protocols and ports between the hosts](https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts)

> ## Open protocols and ports between the hosts
>
> The following ports must be available. On some systems, these ports are open by default.
> 
> - TCP port 2377 for cluster management communications
> - TCP and UDP port 7946 for communication among nodes
> - UDP port 4789 for overlay network traffic
>
> If you are planning on creating an overlay network with encryption (`--opt encrypted`), you will also need to ensure ip protocol 50 (ESP) traffic is allowed.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-05 03:16 UTC
