### ISSUE TITLE
Docker compose 3.0 does not tag images pulled from Docker Trusted Registry

### ISSUE THREAD

**Issue by sneibar** [moby/moby#34101] opened 2017-07-13 19:45 UTC
**Description**
Docker compose 3.0 does not tag images pulled from Docker Trusted Registry even though [the documentation](https://docs.docker.com/compose/compose-file/#image) states "If the image does not exist, Compose attempts to pull it, unless you have also specified build, in which case it builds it using the specified options and tags it with the specified tag." 

**Steps to reproduce the issue:**
1. Push an image to Docker Trusted Registry 2.1.4
2. Add a worker node to a swarm that doesn't have this image pulled.
3. Deploy a stack via a docker-compose.yml referencing the DTR image.

**Describe the results you received:**
The output of docker images shows the image is not tagged.

192.168.1.14/ucpadmin/httpd &lt;none&gt; 42302c1a5e9b About an hour ago 251 MB

**Describe the results you expected:**
I would expect the tag to show up in the local repository.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ee-4
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   1e6d71e
 Built:        Fri May 19 20:25:35 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ee-4
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   1e6d71e
 Built:        Fri May 19 20:25:35 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```

Containers: 12
 Running: 9
 Paused: 0
 Stopped: 3
Images: 21
Server Version: 17.03.2-ee-4
Storage Driver: devicemapper
 Pool Name: docker-253:0-69902320-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.146 GB
 Data Space Total: 107.4 GB
 Data Space Available: 19.16 GB
 Metadata Space Used: 2.318 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 0sur2p12kwqwr8wx1vluptc5n
 Is Manager: true
 ClusterID: im2yqoa1dzi15ai90wzswclvr
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  External CAs:
    cfssl: https://192.168.1.15:12381/api/v1/cfssl/sign
 Node Address: 192.168.1.15
 Manager Addresses:
  192.168.1.15:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.6 MiB
Name: mitaka
ID: GEW6:7GKG:SGOK:CP53:DOMZ:OUTZ:SO4W:5EYO:SQRM:75AE:SCAW:26WV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-07-15 20:16
This is expected; when working with swarm services, the _digest_ if the image is resolved, and the service is pinned to that digest (e.g. `myimage@sha256:aabbcccdd`); doing this, there is a guarantee that all instances of a service are running exactly the same version of the image, which is not the case if the tag is used.

Those images are also _pulled_ by their digest, thus no tag shows up for the image.

I'm closing this, because it's not a bug, but happy to continue the conversation and provide more information if needed

**Closed by thaJeztah** 2017-07-15 20:16 UTC
Labels: version/17.03
