### ISSUE TITLE
docker pull failed

### ISSUE THREAD

**Issue by pwzgorilla** [moby/moby#35939] opened 2018-01-05 04:17 UTC
docker pull failed shows:
`
failed to register layer: devmapper: Thin Pool has 162710 free data blocks which is less than minimum required 163840 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior
`

`docker info` shows:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-100928529-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 96.57GB
 Data Space Total: 107.4GB
 Data Space Available: 10.8GB
 Metadata Space Used: 3.596MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.144GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994.1MiB
Name: mesos-master
ID: C6MB:25PU:DZIL:MGAV:35ML:SU7T:LFJN:XBZ7:ZNEV:BF42:MYEZ:TC4Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://fe8f4ada.m.daocloud.io/
Live Restore Enabled: false
```

`docker version` shows:
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment] 2018-01-05 13:34
I think the error message describes what the problem is; something is using space in your device mapper device, and you ran out of space;

```
 Data Space Used: 96.57GB
 Data Space Total: 107.4GB
```

If you have tried to cleanup containers using `docker rm --force`, chances are that docker failed to remove those containers if the device was busy, but older versions of Docker would still remove the container from the list of containers (which causes the actual container's data to be left behind).

Given that the output of `docker info` shows that you have no images or containers, you can try doing a "factory reset";

- stop the docker service (`systemctl stop docker`)
- remove the `/var/lib/docker` directory (`rm -r /var/lib/docker`)

**this will remove all your local images, containers, and volumes** so be sure that you have nothing important in there.

However; some things that stand out:

- Based on the kernel version, you are running a _very_ old version of CentOS: `3.10.0-123.el7.x86_64` is really old; CentOS uses a rolling release model, so the moment a new version is released, the previous version reaches "end of life". The current version of CentOS is 7.4
- Docker only supports current versions of CentOS, older versions are not supported, and are known to cause  problems
- Docker 17.05.0 is an "edge" (monthly) release, and has reached end-of-life in June of last year; that version is no longer maintained, and no longer supported
- You're using device mapper on "loop-lvm", which is _highly discouraged_. Running on loop-lvm will result in low performance, and high use of resources on your host. If you need to use device mapper, make sure to configure it with direct-lvm, as is [described in the documentation](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production)

Note that you can use the "overlay2" storage driver if you update your system to the latest version of CentOS (7.4) and kernel, and do a factory reset. The overlay2 storage driver does _not_ require manual setup (like the `direct-lvm` configuration), and will provide better performance than device mapper.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, and the version of docker (and CentOS) is no longer supported, but feel free to continue the conversation

**Closed by thaJeztah** 2018-01-05 13:34 UTC
Labels: area/distribution, version/17.05
