### ISSUE TITLE
--dns override not working in Macvlan

### ISSUE THREAD

**Issue by logicethos** [moby/moby#35328] opened 2017-10-28 17:44 UTC
This only occurs with the Macvlan driver:

```
docker run -it --net mymaclan --ip 192.168.0.100 --dns 8.8.8.8 ubuntu /bin/bash

# cat /etc/resolve.conf 
127.0.0.11

```
Version: 17.09.0-ce
Ubuntu 16.04.3 LTS

**Comment by thaJeztah** [comment] 2017-10-28 17:53
`127.0.0.11` is the IP-address of the embedded DNS server (see https://docs.docker.com/engine/userguide/networking/configure-dns/). The embedded DNS server provides service discovery (i.e. it allows you to resolve hostnames of other containers on the same network), and acts as a forwarder for external DNS servers you configured.

This is not a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-28 17:53 UTC

**Comment by logicethos** [comment] 2017-10-28 18:11
Hmm, ok, but I have a specific DNS server I wanted to connect to.  The container is a VPN server, and the DNS server it is to connect to is an ad-blocker.

**Comment by thaJeztah** [comment] 2017-10-28 18:40
So that should still work, the embedded DNS will forward queries to the DNS you configured

**Comment by logicethos** [comment] 2017-10-28 19:09
Yes your right.  Just been doing some experimenting with some alternative DNS servers.  --dns does indeed work. Thanks.

What would be a nice idea, is to have docker write into resolve.conf the --dns setting as a comment, just so you know it's been set in the embedded server.
