### ISSUE TITLE
docker COPY command broken when running script inside windows environment

### ISSUE THREAD

**Issue by nfrmtk** [moby/moby#47231] opened 2024-01-26 15:51 UTC
### Description

docker compose build command fails with correct Dockerfile using windows.
same command works inside wsl.
docker-compose.yml: 
```yaml

version: "3"

services:
  good:
    build:
      dockerfile: good/Dockerfile
    image: good
  bad:
    build:
      dockerfile: bad/Dockerfile
    image: bad
```

bad/Dockerfile:
```
FROM ubuntu:22.04
COPY bad/Dockerfile f.txt
ENTRYPOINT ls
```

good/Dockerfile:
```
FROM ubuntu:22.04
COPY docker-compose.yml f.yml
ENTRYPOINT ls
```

### Reproduce

[broken-docker.zip](https://github.com/moby/moby/files/14066659/broken-docker.zip)
docker compose build bad

### Expected behavior

image should be built correcrtly

### docker version

```bash
Client:                                     
 Cloud integration: v1.0.35+desktop.10      
 Version:           25.0.1                  
 API version:       1.44                    
 Go version:        go1.21.6                
 Git commit:        29cf629                 
 Built:             Tue Jan 23 23:10:35 2024
 OS/Arch:           windows/amd64           
 Context:           default                 
                                            
Server: Docker Desktop 4.27.0 (135262)      
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:46 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 50
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.57GiB
 Name: docker-desktop
 ID: eb533e72-1f7d-40d4-b655-9c30e145a156
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Additional Info

COPY works correclty when trying to transfer file from the folder of build context(see good/Dockerfile)
error messages apperaing when trying to build image are different when changing nest level of file being transfered via COPY.

**Comment by thaJeztah** [comment] 2024-01-26 16:22
Can you post the error-message you're getting? Are you only getting this error through `docker compose build` or also when using the same options and `docker build` ?

I know there were some fixes in Docker Compose 2.24.3 related to paths on Windows, so wondering if related in any way; 

- https://github.com/docker/compose/pull/11400
- https://github.com/docker/buildx/issues/2207#issuecomment-1908460460

**Comment by milas** [comment] 2024-01-26 17:00
I can reproduce this with DD 4.27 / Compose 2.24.3 on Windows 11.

```shell
$ docker compose build
2024/01/26 11:50:50 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 1.1s (9/11)                                                                                 docker:default
 => [good internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 99B                                                                                0.0s
 => [bad internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 95B                                                                                0.0s
 => [bad internal] load metadata for docker.io/library/ubuntu:22.04                                                0.7s
 => [good auth] library/ubuntu:pull token for registry-1.docker.io                                                 0.0s
 => [good internal] load .dockerignore                                                                             0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [bad internal] load .dockerignore                                                                              0.1s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [bad internal] load build context                                                                        0.1s
 => => transferring context: 33B                                                                                   0.0s
 => CANCELED [good 1/2] FROM docker.io/library/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e  0.2s
 => => resolve docker.io/library/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d431118c7dd06  0.1s
 => [good internal] load build context                                                                             0.2s
 => => transferring context: 2B                                                                                    0.0s
------
 > [bad internal] load build context:
------
failed to solve: changes out of order: "bad/Dockerfile" ""
```

It does NOT fail with `buildx build -f ./bad/Dockerfile .`.

The `changes out of order` is coming from https://github.com/crazy-max/fsutil/blob/376dc28ff40f6321cd3d1675590ca39ec6552909/validator.go#L59

**Comment by nfrmtk** [comment] 2024-01-26 23:54
Hello. Thanks for the replies.

> Can you post the error-message you're getting? Are you only getting this error through `docker compose build` or also when using the same options and `docker build` ?

In addition to the previous reply:
dockerfile
```
FROM ubuntu:22.04

COPY bad/a/b h.txt

ENTRYPOINT ls
```
gives following result when trying to execute docker compose build:
```powershell
PS C:\Users\nfrmtk\Downloads\broken-docker> docker compose build bad
2024/01/27 02:28:10 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
2024/01/27 02:28:10 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 0.7s (6/6) FINISHED                                                                         docker:default
 => [bad internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 93B                                                                                0.0s
 => [bad internal] load metadata for docker.io/library/ubuntu:22.04                                                0.6s
 => [bad internal] load .dockerignore                                                                              0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [bad internal] load build context                                                                              0.0s
 => => transferring context: 2B                                                                                    0.0s
 => CACHED [bad 1/2] FROM docker.io/library/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d4  0.0s
 => ERROR [bad 2/2] COPY bad/a/b h.txt                                                                             0.0s
------
 > [bad 2/2] COPY bad/a/b h.txt:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 39487139-b768-4da2-afc6-13b22c4860de::to427auqx9vhnffdswgoi2gjx: failed to walk /var/lib/docker/tmp/buildkit-mount2377300442/bad/a: lstat /var/lib/docker/tmp/buildkit-mount2377300442/bad/a: no such file or directory
```
the output doesn't depend on existance of directory bad/a/b


Also, you can get following error: 
```powershell
PS C:\Users\nfrmtk\Downloads\broken-docker> docker compose build bad
2024/01/27 02:42:43 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 0.4s (6/6) FINISHED                                                                         docker:default
 => [bad internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 101B                                                                               0.0s
 => [bad internal] load metadata for docker.io/library/ubuntu:22.04                                                0.3s
 => [bad internal] load .dockerignore                                                                              0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [bad internal] load build context                                                                              0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [bad 1/2] FROM docker.io/library/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d431118c7  0.0s
 => ERROR [bad 2/2] COPY a/b/c/d/e/f/g/h.txt f.txt                                                                 0.0s
------
 > [bad 2/2] COPY a/b/c/d/e/f/g/h.txt f.txt:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 39487139-b768-4da2-afc6-13b22c4860de::lwwjg3u6u1r608ksfatr9gtx0: "/a/b/c/d/e/f/g/h.txt": not found
```
by changing docker-compose.yml to following;
```yml
version: "3"

services:
  good:
    build:
      dockerfile: Dockerfile
      context: good
    image: good
  bad:
    build:
      context: ..
      dockerfile: broken-docker/bad/Dockerfile
    image: bad
```
and bad/Dockerfile to following:
```
FROM ubuntu:22.04
COPY broken-docker/bad/a/b/c/d/e/f/g/h.txt f.txt
ENTRYPOINT ls
```
The error message does not depend on existance of path on host pc.
All errors do disappear when building image using `docker build` with appropriate argumants(if the path exists on host machine, of course).

**Comment by crazy-max** [comment] 2024-01-29 12:53
> ```
> failed to solve: changes out of order: "bad/Dockerfile" ""
> ```

As discussed internally, this error seems fixed with https://github.com/tonistiigi/fsutil/pull/173/commits/c73d856a7200f96f999f9e5f226ec87907682cac but then we got:

```
docker compose build bad
[+] Building 0.0s (0/0)  docker:default
[+] Building 0.6s (6/6) FINISHED                                                                                                                                             docker:default
 => [bad internal] load build definition from Dockerfile                                                                                                                               0.0s
 => => transferring dockerfile: 95B                                                                                                                                                    0.0s
 => [bad internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                    0.5s
 => [bad internal] load .dockerignore                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
 => [bad internal] load build context                                                                                                                                                  0.0s
 => => transferring context: 58B                                                                                                                                                       0.0s
 => [bad 1/2] FROM docker.io/library/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d431118c7dd060a74                                                              0.0s
 => ERROR [bad 2/2] COPY bad/Dockerfile f.txt                                                                                                                                          0.0s
------
 > [bad 2/2] COPY bad/Dockerfile f.txt:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref b5835101-3195-42d3-8b06-35d8de84ee90::42dfx6gudjkmnoc7mowzwv84b: "/bad/Dockerfile": not found
```

The leading slash in `/bad/Dockerfile` is odd. I repro with Docker 25 and container builder with BuildKit 0.12.4 using compose. I don't repro with buildx 0.12.1 but repro with buildx master so seems another issue in fsutil with path separators similar to https://github.com/docker/buildx/issues/2207:

```
docker --debug buildx build -f bad/Dockerfile .
[+] Building 0.0s (0/0)  docker:default
[+] Building 1.0s (6/7)                                                                                                                                                      docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                   0.0s
 => => transferring dockerfile: 95B                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                        0.8s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
 => ERROR [internal] load build context                                                                                                                                                0.0s
 => => transferring context:                                                                                                                                                           0.0s
 => [1/2] FROM docker.io/library/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d431118c7dd060a74                                                                  0.0s
------
 > [internal] load build context:
------
ERROR: failed to solve: rpc error: code = Unknown desc = expected single entry "bad\\Dockerfile" but got "bad/Dockerfile"
8108 v0.12.0-rc2-109-gd0c4bed4 C:\Users\crazy\.docker\cli-plugins\docker-buildx.exe --debug buildx build -f bad/Dockerfile .
github.com/tonistiigi/fsutil.statFile.func1
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/followlinks.go:150
github.com/tonistiigi/fsutil.(*filterFS).Walk.func1
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/filter.go:365
github.com/tonistiigi/fsutil.(*fs).Walk.func1
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/fs.go:80
path/filepath.walkDir
        path/filepath/path.go:442
path/filepath.WalkDir
        path/filepath/path.go:532
github.com/tonistiigi/fsutil.(*fs).Walk
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/fs.go:49
github.com/tonistiigi/fsutil.(*filterFS).Walk
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/filter.go:184
github.com/tonistiigi/fsutil.statFile
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/followlinks.go:145
github.com/tonistiigi/fsutil.(*symlinkResolver).readSymlink
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/followlinks.go:105
github.com/tonistiigi/fsutil.(*symlinkResolver).append
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/followlinks.go:50
github.com/tonistiigi/fsutil.FollowLinks
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/followlinks.go:20
github.com/tonistiigi/fsutil.NewFilterFS
        github.com/tonistiigi/fsutil@v0.0.0-20230825212630-f09800878302/filter.go:88
github.com/moby/buildkit/session/filesync.(*fsSyncProvider).handle
        github.com/moby/buildkit@v0.13.0-beta1.0.20240126101002-6bd81372ad6f/session/filesync/filesync.go:107
github.com/moby/buildkit/session/filesync.(*fsSyncProvider).DiffCopy
        github.com/moby/buildkit@v0.13.0-beta1.0.20240126101002-6bd81372ad6f/session/filesync/filesync.go:72
github.com/moby/buildkit/session/filesync._FileSync_DiffCopy_Handler
        github.com/moby/buildkit@v0.13.0-beta1.0.20240126101002-6bd81372ad6f/session/filesync/filesync.pb.go:256
github.com/moby/buildkit/util/grpcerrors.StreamServerInterceptor
        github.com/moby/buildkit@v0.13.0-beta1.0.20240126101002-6bd81372ad6f/util/grpcerrors/intercept.go:33
github.com/moby/buildkit/session.NewSession.ChainStreamServer.func6.1.1
        github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.45.0/interceptor.go:487
github.com/moby/buildkit/session.NewSession.ChainStreamServer.func6.1.1
        github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49
github.com/moby/buildkit/session.NewSession.ChainStreamServer.func6
        github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58
google.golang.org/grpc.(*Server).processStreamingRPC
        google.golang.org/grpc@v1.58.3/server.go:1675
google.golang.org/grpc.(*Server).handleStream
        google.golang.org/grpc@v1.58.3/server.go:1755
google.golang.org/grpc.(*Server).serveStreams.func1.1
        google.golang.org/grpc@v1.58.3/server.go:986
runtime.goexit
        runtime/asm_amd64.s:1650
```

When vendoring https://github.com/tonistiigi/fsutil/compare/master...crazy-max:fsutil:ci-windows-gogo (same as https://github.com/tonistiigi/fsutil/pull/173 but keep gogo) I now get the `failed to calculate checksum` error:

```
docker --debug buildx build -f bad/Dockerfile .
[+] Building 0.0s (0/0)  docker:default
[+] Building 1.0s (7/7) FINISHED                                                                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                   0.0s
 => => transferring dockerfile: 95B                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                        0.8s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                                      0.1s
 => => transferring context: 126B                                                                                                                                                      0.0s
 => [1/2] FROM docker.io/library/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d431118c7dd060a74                                                                  0.0s
 => ERROR [2/2] COPY bad/Dockerfile f.txt                                                                                                                                              0.0s
------
 > [2/2] COPY bad/Dockerfile f.txt:
------
Dockerfile:2
--------------------
   1 |     FROM ubuntu:22.04
   2 | >>> COPY bad/Dockerfile f.txt
   3 |     ENTRYPOINT ls
   4 |
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref b5835101-3195-42d3-8b06-35d8de84ee90::mj5apzg5so4o4lllwbm0pav16: "/bad/Dockerfile": not found
199  /usr/local/bin/dockerd --containerd /run/containerd/containerd.sock --pidfile /run/desktop/docker.pid --swarm-default-advertise-addr=eth0 --host-gateway-ip 192.168.65.254
github.com/moby/buildkit/cache/contenthash.init
        /root/build-deb/engine/vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:27
runtime.doInit1
        /usr/local/go/src/runtime/proc.go:6740
runtime.doInit
        /usr/local/go/src/runtime/proc.go:6707
runtime.main
        /usr/local/go/src/runtime/proc.go:249
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650
```

**Comment by crazy-max** [comment] 2024-01-30 09:17
After debugging with dlv I see src and dest are wrong:

![image](https://github.com/moby/moby/assets/1951866/4de59587-a94d-421e-830c-75d2bb9bee4a)

A leading slash is added for both of them. It looks related to this change in `fsutil`: https://github.com/tonistiigi/fsutil/pull/167.

**Comment by danshome** [comment] 2024-01-30 09:19
Looks like a fix was just checked in that is possibly related...

https://github.com/tonistiigi/fsutil/pull/173/commits/819ba8450e943ed81ac17dc8aeab5a3ba7067aec

**Comment by crazy-max** [comment] 2024-01-31 11:13
Fixed by https://github.com/docker/compose/pull/11426

**Closed by crazy-max** 2024-01-31 11:13 UTC
Labels: area/builder, status/0-triage, status/more-info-needed, kind/bug, version/25.0

**Comment by aaomidi** [comment] 2024-02-13 15:45
> Fixed by https://github.com/docker/compose/pull/11426

Are you sure?

Docker Compose version 2.24.5 still exhibits the same problem, and I'm running into this issue on Linux and not Windows.

```
Build Failed: Custom build "bash -c \"set -eo pipefail;\\nexport KO_DEFAULTBASEIMAGE=ko.local/redacted/redacted/dev/signer/base;\\nexport VERSION_LDFLAGS=\\\"$(/home/amir/Projects/redacted/redacted/common/version/ldflags.sh)\\\";\\nIMAGE=$(ko publish --local ./signer);\\ndocker tag $IMAGE $EXPECTED_REF\"" failed: exit status 1

```

**Comment by thaJeztah** [comment] 2024-02-13 15:59
That looks like a very different error; here's the original errors (split up by each wrapped error);

```
failed to solve: changes out of order: "bad/Dockerfile" ""
```

And

```
failed to solve:
failed to compute cache key:
failed to calculate checksum of ref 39487139-b768-4da2-afc6-13b22c4860de::to427auqx9vhnffdswgoi2gjx:
failed to walk /var/lib/docker/tmp/buildkit-mount2377300442/bad/a:
lstat /var/lib/docker/tmp/buildkit-mount2377300442/bad/a:
no such file or directory
```

Compared to the error you posted;

```
Error: 
failed to publish images: 
error publishing ko://github.com/redacted/redacted/signer:
error loading image: 
error during connect: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.43/images/load?quiet=0": 
unable to calculate manifest: 
blob sha256:c44309996eeb7397249cc7726a975d99737e05eddcec5118e7d84f8c8b96a2aa not found
```

**Comment by aaomidi** [comment] 2024-02-13 15:59
Yep I think the source of this bug was https://github.com/moby/moby/issues/47210

Now to wait for package managers to catch up...
