### ISSUE TITLE
Can't build images

### ISSUE THREAD

**Issue by gedl** [moby/moby#22872] opened 2016-05-21 00:46 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-36-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.645 GiB
Name: cassandra
ID: 6G7E:OCPA:S4R4:OXSE:JPDL:6JGP:7O63:Z66Q:O37J:Z2LL:EFQD:L5U3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create Dockerbuild file according to the whalesay tutorial
2. Run docker build -t docker-whale .

**Describe the results you received:**
Step 1 : FROM docker/whalesay:latest
 ---> 6b362a9f73eb
Step 2 : RUN apt-get -y update && apt-get install -y fortunes
invalid id: 

**Describe the results you expected:**

I would expect the image to build 

**Additional information you deem important (e.g. issue happens only occasionally):**
running as /usr/bin/docker daemon -H fd:// --iptables=False --bridge=none

**Output of `docker network ls`:**

```
NETWORK ID          NAME                DRIVER
6ead2e77435f        VPN                 bridge              
bfbc07928f6e        VPN_THROTTLED       bridge              
84227598b5bb        host                host                
6b0c79764525        none                null 
```

(note there is not a network called bridge, perhaps because  I never ran docker without --bridge=none)

**Comment by jkirkby91** [comment] 2016-05-22 21:14
can you show the Dockerfile

**Comment by thaJeztah** [comment] 2016-05-22 21:23
@jkirkby91 I don't think the docker file is related in this case (you can see the steps it's running), possibly the `--bridge=none` in this case, but I haven't tried to reproduce yet.

**Comment by thaJeztah** [comment] 2016-05-22 21:39
Ok, confirmed; if the daemon has never been started before, and it's started with `--bridge=none`, then the default `bridge` network is not created.

To reproduce;

start a fresh machine (I used ubuntu 15.10 as the original report), and install the static binaries;

    curl https://get.docker.com/builds/Linux/x86_64/docker-1.11.1.tgz > docker.tgz
    tar -xvf docker.tgz
    mv docker/* /usr/bin/

start daemon with `--bridge=none`

    /usr/bin/docker daemon --debug --iptables=False --bridge=none &

notice that there's no "bridge" network

```
docker network ls
NETWORK ID          NAME                DRIVER
0486f8db5140        host                host
06c99cbfbafc        none                null
```

Do a build (using the "whales" image, but shouldn't matter what;

```Dockerfile
FROM docker/whalesay:latest
RUN apt-get -y update && apt-get install -y fortunes
CMD /usr/games/fortune -a | cowsay
```

Watch the build failing:
```
docker build -t docker-whale .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM docker/whalesay:latest
 ---> 6b362a9f73eb
Step 2 : RUN apt-get -y update && apt-get install -y fortunes
invalid id:
```

logs
```
DEBU[0007] Calling POST /v1.23/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&t=docker-whale&ulimits=null
DEBU[0007] [BUILDER] Cache miss: [/bin/sh -c apt-get -y update && apt-get install -y fortunes]
DEBU[0007] [BUILDER] Command to be executed: [/bin/sh -c apt-get -y update && apt-get install -y fortunes]
ERRO[0007] Couldn't run auplink before unmount /var/lib/docker/tmp/docker-aufs-union442469909: exec: "auplink": executable file not found in $PATH
ERRO[0007] Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/a52bbe882845fa702ae53675e13f66268fd293484864cc2c5fe14b7e82c4141a-init: exec: "auplink": executable file not found in $PATH
DEBU[0007] container mounted via layerStore: /var/lib/docker/aufs/mnt/a52bbe882845fa702ae53675e13f66268fd293484864cc2c5fe14b7e82c4141a
ERRO[0007] Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/a52bbe882845fa702ae53675e13f66268fd293484864cc2c5fe14b7e82c4141a: exec: "auplink": executable file not found in $PATH
```

**Comment by thaJeztah** [comment] 2016-05-22 21:43
Note that starting the daemon without `--bridge=none` creates the bridge network, but build is still failing, due to `--iptables=false` (and no iptables rules being present); this should not be a problem if you manually created those rules.

**Comment by thaJeztah** [comment] 2016-05-22 21:53
Marking this as bug, although I'm not sure what the expected outcome should be with `--bridge=none`, as this would tell docker to not create a bridge, thus  telling it to not create a bridge network

ping @mavenugo

**Comment by gedl** [comment] 2016-05-23 08:27
I don't see any problem with not having a default network. Some users, as me, don't want a bridge created nor a default network. Currently I am forced to have a docker specific bridge, so I can have a docker specific bridge network so I can build images. I will never launch a container inside that network, so this really only needlessly occupies a subnet that is never used, other than building images. 

Ideally, one would be able to build an image using the host's network. Is there any reason for this not to be possible ?

**Comment by thaJeztah** [comment] 2016-05-23 09:36
>  Ideally, one would be able to build an image using the host's network

see the discussion on https://github.com/docker/docker/issues/10324 and https://github.com/docker/docker/pull/20987

**Comment by gedl** [comment] 2016-05-23 12:44
@thaJeztah ok, I +1'd there.

However, I'm worrying that the "fix" for this specific bug is to always create a default network. In my opinion this should not be the case. Instead:

* --bridge=none specified -> no bridge, no default bridge network (sounds obvious)
* no --bridge specified -> docker0 bridge, educated random subnet, default bridge network on this subnet
* --bridge=existing_bridge -> default bridge network on existing bridge's subnet 

For the first case, if a bridge existed in the past but this current run of the daemon is with --bridge=none, then don't create the bridge pre-defined network (it won't work anyway, as there is no bridge. If users  create a bridge for docker to use afterwards, then they must create a bridge network as well if they wish to use it).

**Comment by AkihiroSuda** [comment] 2018-04-09 07:05
Is this still an issue?

**Comment by thaJeztah** [comment] 2023-09-16 22:53
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 22:53 UTC
Labels: kind/bug, area/networking, version/1.11
