### ISSUE TITLE
How do i share folder from container to host so i can edit container code in my host IDE?

### ISSUE THREAD

**Issue by laurencefass** [moby/moby#32258] opened 2017-03-31 11:11 UTC
**Description**

I want to edit my docker container source code in host IDE so I want to expose a folder in a docker container (via a share) in a named host folder. I dont want to mount a host folder into a container, but the other way around. I cant find any online documentation. If its not possible this seems like a serious limitation of docker and impairment to development on the host.  If its not possible, how may i best use my host machine to make live changes to source code in a container? Or am i limited to editing code in a container folder from the containers command line?

**Additional information you deem important (e.g. issue happens only occasionally):**
**Output of `docker version`:**
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 172
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.52-boot2docker
Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: CCJC:TFPL:MEEY:QXM3:JQLP:SGOM:H5YR:MLY2:P5DK:P3MF:F2SF:5ZGM
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 70
 System Time: 2017-03-31T10:47:19.838409976Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox 5+

**Comment by thaJeztah** [comment] 2017-03-31 12:39
"reverse mounting" a container's filesystem to the host is not something that's supported.

In general, making "live changes" in a container throws away the biggest
advantage of using containers; having a _reproducible_ way to run your
application. Instead of making changes to a container, you _replace_ the
container with a new version if updates are needed. This allows you to test,
and verify a container (image) before it's deployed, and also allows rolling
back to a previous version when needed.

During _development_, you can check out your source code from your source
control (Git, SVN) start a container and bind-mount your local source files into
the container; once changes are ready to deploy (and commited to your source
control), rebuild the image with the new version of the source, test, and
deploy the image.


Having said the above, some approaches that may work for you;

- use a [volume-driver plugin](https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins) (note; that listing is for "non managed" plugins; docker 17.03 adds support for managed plugins that can be installed through `docker plugin install`) that stores the files on a location that's accessible by the IDE. For example, the ["local-persist"](https://github.com/CWSpear/local-persist) plugin allows you to specify a custom path where volume files are stored. There's also [managed plugins](https://docs.docker.com/engine/extend/) that allow (e.g.) to use `sshfs` or `nfs` to share a filesystem with other hosts. Keep in mind that volumes are propagated the first time the container is run, so "pulling / starting" a new version of the container won't update those files
- use a "helper" container that shares a volume with the container you want to edit (this assumes the files you want to edit are in a volume). The "helper" container can run, e.g. an FTP or SSH server, allow you to access/synchronize the files.

**Comment by thaJeztah** [comment] 2018-05-07 12:33
This is largely a duplicate of some existing issues (listed below), so let me close this

- https://github.com/moby/moby/issues/19990 ("[feature] Allow for named volumes to specify host mount point")
- https://github.com/moby/moby/issues/26872 ("[FEATURE] Access container directory on the host")
- https://github.com/moby/moby/issues/29023 ("Feature request: Configurable source for volume")
- https://github.com/moby/moby/issues/34800 ("Mount volumes from container to host under specific paths")

**Closed by thaJeztah** 2018-05-07 12:33 UTC
Labels: area/volumes, kind/feature, version/17.03
