### ISSUE TITLE
Killing a container using systemd systemd-container-based container, doesn't pass the kill signal to docker

### ISSUE THREAD

**Issue by psaini79** [moby/moby#41414] opened 2020-09-03 22:49 UTC
**Description**

We are running systemd based container as our app need access to systemd and uses systemd to kill the container by using the following command:

```
systemctl halt --force
```

It works for 90% but not working on one of my system. 

**Steps to reproduce the issue:**
1. Dockerfile:
```
FROM oraclelinux:7-slim
RUN yum -y install systemd vim passwd  && \
 yum clean all && \
sync
USER root
WORKDIR /root
CMD ["/usr/sbin/init"]
```
2. Create Container
```
docker create -t -i \
 --privileged=false \
--volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
 --volume /etc/localtime:/etc/localtime:ro \
 --cpuset-cpus 1-2 \
 --memory 2G \
  --restart=always \
 --tmpfs=/run \
 --name test1 \
test1-slim
sleep 2
docker start test1
```
3. KIll the container. Login to the container using command `docker exec -i -t test1 /bin/bash`
```
systemctl halt --force
```

**Describe the results you received:**
You will see that container is not killed as show below:
```
docker inspect test1 | grep -i pid
 "Pid": 18844,
 "PidMode": "",
 "PidsLimit": null,

# ps 18844
 PID TTY STAT TIME COMMAND
 18844 ? Ss 0:00 */usr/lib/systemd/systemd-shutdown halt --log-level 6 --log-target kmsg --log-color*
```

**Describe the results you expected:**
It must exit the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
# rpm -qa | grep docker
docker-cli-19.03.11.ol-5.el7.x86_64
docker-engine-19.03.11.ol-5.el7.x86_64
```

**Output of `docker info`:**
```
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.11-ol
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.35-1902.305.4.el7uek.x86_64
 Operating System: Oracle Linux Server 7.8
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 251.6GiB
 Name: tes-server
 ID: 4XMH:UQLK:X3EO:WX5S:AWZY:HC2O:ZSBW:LUEZ:BSA5:J6ED:EC7Z:UYFF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: 
 HTTPS Proxy: 
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

Registries: 

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is a Bamremetal machine.

**Comment by cpuguy83** [comment] 2020-09-04 06:03
Signals are not forwarded from the cli with TTY enabled, which is most likely why that's happening.

**Comment by psaini79** [comment] 2020-09-04 17:09
@cpuguy83 

Thanks for the reply.
However, it didn't work if I try without a terminal. 

1) Check the Date
```
# date
Fri Sep  4 09:54:32 PDT 2020
```
2) Check the container PID
```
docker inspect test | grep -i pid
            "Pid": 20103,
            "PidMode": "",
            "PidsLimit": null,
```
3) Check the Docker uptime and other values
```
# docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                     PORTS               NAMES
d2de47c24689        test-1:1.0-slim   "/usr/sbin/init"         35 hours ago        Up About a minute                              test
# docker exec test ps 
  PID TTY          TIME CMD
    1 ?        00:00:00 systemd
   21 ?        00:00:00 systemd-journal
   37 ?        00:00:00 systemd-logind
   39 ?        00:00:00 smartd
   45 ?        00:00:00 gssproxy
   63 ?        00:00:00 crond
  180 ?        00:00:00 sshd
  248 ?        00:00:00 ps
```
4) Kill the container without terminal
```
# docker exec test systemctl halt --force
```
5) Check the container
```
# docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                     PORTS               NAMES
d2de47c24689        test-1:1.0-slim   "/usr/sbin/init"         35 hours ago        Up About a minute                              test
```
6) Check what container PID is executing
```
# ps 20103
  PID TTY      STAT   TIME COMMAND
20103 ?        Ss     0:00 /usr/lib/systemd/systemd-shutdown halt --log-level 6 --log-target kmsg --log-color
# date
Fri Sep  4 09:57:02 PDT 2020
```

I am not sure why the kill signal is not being passed to the docker process. What is stopping it to complete?

**Comment by thaJeztah** [comment] 2020-09-08 13:27
> Signals are not forwarded from the cli with TTY enabled, which is most likely why that's happening.

I don't think that's the issue in this case, because the `systemctl halt --force` is executed inside the container. 

> I am not sure why the kill signal is not being passed to the docker process. What is stopping it to complete?

In the end, the container's main (`PID 1`) process determines if the container is "running" or not; if running `systemctl halt --force` doesn't stop the main process, I suspect that some capability that's needed for that to run isn't available (IIRC to run systemd in a container, you may need `CAP_SYS_ADMIN` and an environment variable (`container=docker`) set on the container to make systemd aware it's running in a container. See the discussion on https://github.com/moby/moby/issues/28614 (and https://github.com/moby/moby/issues/28614#issuecomment-261724902)

It's also possible that the default seccomp profile is blocking something that's needed for that to work.


So, trying to reproduce; here's with a `centos:7` container;

```bash
docker run -d \
  --name=tmp \
  --cap-add=SYS_ADMIN \
  -e "container=docker" \
  -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --tmpfs /run \
  centos:7 /usr/sbin/init
```

And running `systemctl halt --force`

```bash
docker exec tmp systemctl halt --force
```

After that, the container is exited;

```bash
docker ps -a -n1
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                     PORTS               NAMES
ea12ea6532fe        centos:7            "/usr/sbin/init"         About a minute ago   Exited (0) 5 seconds ago                       tmp
```

From that, I don't think there's a bug at hand, but probably missing an option when creating the container; I'll go ahead and close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2020-09-08 13:27 UTC
