### ISSUE TITLE
lost docker images after changing storage-driver to { "storage-driver" : "aufs" }

### ISSUE THREAD

**Issue by bayetam** [moby/moby#34112] opened 2017-07-14 12:32 UTC
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
No result when execute  "docker images" command

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: ZJ3X:GLNU:OCWB:4SZC:X7UG:D6SK:CDXJ:7I4F:R5MQ:KKCZ:3U4A:UKGJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-07-14T12:33:59.100675877Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2017-07-14 13:41
This is expected. Images are stored in the storage driver, if you change drivers the images will be gone.
If you switch back to the old driver they will be back.

You can use `docker save` to grab all the images from the old storage driver and `docker load` to load them into the new one.

Closing since this is expected behavior, but feel free to continue discussion.
Thanks!

**Closed by cpuguy83** 2017-07-14 13:41 UTC
Labels: version/17.06

**Comment by bayetam** [comment] 2017-07-14 15:51
Thank's for your response!
