### ISSUE TITLE
getting shim error: open pid: no such file or directory after upgrade to 1.12.0-rc2

### ISSUE THREAD

**Issue by nicolaka** [moby/moby#23958] opened 2016-06-25 17:34 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 11
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 108
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.2 MiB
Name: dev1
ID: OXRP:6VZL:PLXK:Y7SU:EFEI:2KF5:PILP:UKXH:35MK:CUC6:VOP4:G75Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 23
 System Time: 2016-06-25T10:28:58.030664381-07:00
 EventsListeners: 0
Username: nicolaka
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

vagrant using virtualbox with ubuntu image

**Steps to reproduce the issue:**
1. Upgrade from 1.11.2 to 1.12.0-rc2
2.
3.

**Describe the results you received:**

```
# docker run -itd busybox
790841c4aa872069125e072f8afadc3e64b9e4db1632972984710a5161a7373a
docker: Error response from daemon: shim error: open pid: no such file or directory.
root@dev1:/home/vagrant# tail /var/log/upstart/docker.log
time="2016-06-25T10:23:11.950408524-07:00" level=debug msg="Assigning addresses for endpoint furious_payne's interface on network bridge"
time="2016-06-25T10:23:11.950968858-07:00" level=debug msg="RequestAddress(LocalDefault/2001:db8:cafe:1::/64, 2001:db8:cafe:1:0:242:ac11:2, map[])"
time="2016-06-25T10:23:11.971242081-07:00" level=debug msg="Programming external connectivity on endpoint furious_payne (5601d3a1076057b06f59e66427280d223e2cd100add9ae2e0b8a28e3f6780fc9)"
ERRO[0006] containerd: start container                   error=shim error: open pid: no such file or directory id=790841c4aa872069125e072f8afadc3e64b9e4db1632972984710a5161a7373a
time="2016-06-25T10:23:12.011882294-07:00" level=error msg="Create container failed with error: shim error: open pid: no such file or directory"
time="2016-06-25T10:23:12.014067070-07:00" level=debug msg="Revoking external connectivity on endpoint furious_payne (5601d3a1076057b06f59e66427280d223e2cd100add9ae2e0b8a28e3f6780fc9)"
time="2016-06-25T10:23:12.035810308-07:00" level=debug msg="Releasing addresses for endpoint furious_payne's interface on network bridge"
time="2016-06-25T10:23:12.035843643-07:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
time="2016-06-25T10:23:12.035870020-07:00" level=debug msg="ReleaseAddress(LocalDefault/2001:db8:cafe:1::/64, 2001:db8:cafe:1:0:242:ac11:2)"
time="2016-06-25T10:23:12.041521634-07:00" level=error msg="Handler for POST /v1.24/containers/790841c4aa872069125e072f8afadc3e64b9e4db1632972984710a5161a7373a/start returned error: shim error: open pid: no such file or directory"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This also happened when i upgraded to 1.11. I think it could be related to apparmor but I disabled the `docker` apparmor profile with same results:

```
# apparmor_status
apparmor module is loaded.
5 profiles are loaded.
5 profiles are in enforce mode.
   /sbin/dhclient
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/connman/scripts/dhclient-script
   /usr/sbin/ntpd
   docker-default <<<<<<<<<<
0 profiles are in complain mode.
2 processes have profiles defined.
2 processes are in enforce mode.
   /sbin/dhclient (1451)
   /usr/sbin/ntpd (5171)
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
# ln -s /etc/apparmor.d/docker
docker         docker-engine
# ln -s /etc/apparmor.d/docker /etc/apparmor.d/disable/
# apparmor_parser -R /etc/apparmor.d/docker
# aa-status
apparmor module is loaded.
4 profiles are loaded.
4 profiles are in enforce mode.
   /sbin/dhclient
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/connman/scripts/dhclient-script
   /usr/sbin/ntpd
0 profiles are in complain mode.
2 processes have profiles defined.
2 processes are in enforce mode.
   /sbin/dhclient (1451)
   /usr/sbin/ntpd (5171)
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
# service docker restart
docker stop/waiting
docker start/running, process 5715
# docker run -itd busybox
790841c4aa872069125e072f8afadc3e64b9e4db1632972984710a5161a7373a
docker: Error response from daemon: shim error: open pid: no such file or directory.
```

**Comment by tonistiigi** [comment] 2016-06-29 18:14
@mlaventure @crosbymichael runc doesn't seem to write pidfile even though it exits cleanly?

**Comment by thaJeztah** [comment] 2016-07-13 00:34
ping @mlaventure @crosbymichael PTAL

**Comment by mlaventure** [comment] 2016-07-13 18:22
Will try to reproduce

**Comment by mlaventure** [comment] 2016-07-13 18:42
no luck reproducing this so far unfortunately.

If you purge docker and reinstall it, does it still occur?

**Comment by crosbymichael** [comment] 2016-07-13 22:20
i cannot reproduce either

**Comment by thaJeztah** [comment] 2016-07-13 22:22
ping @nicolaka are you still able to reproduce, or should we close this for now?

**Comment by vikstrous** [comment] 2016-07-28 15:42
I got this too:
```
docker run --rm -it alpine sh
docker: Error response from daemon: shim error: open pid: no such file or directory.
```
Anything I should report before I restart docker and/or delete /var/lib/docker?

**Comment by vikstrous** [comment] 2016-07-28 16:01
I restarted the daemon and none of the containers came up.

I upgraded to rc5, then none of the containers that failed to start came up, but I was able to start new containers again. Looks like the issue is fixed.

**Comment by thaJeztah** [comment] 2016-07-28 18:07
@nicolaka have you still seen this happening on RC5, or should we close this?

**Comment by nicolaka** [comment] 2016-07-28 18:27
@thaJeztah unfortunately yes :(

```
root@dev1:/home/vagrant# docker version
Client:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:32:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:32:56 2016
 OS/Arch:      linux/amd64
root@dev1:/home/vagrant# service docker restart
docker stop/waiting
docker start/running, process 13896
root@dev1:/home/vagrant# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@dev1:/home/vagrant# docker run -it busybox
docker: Error response from daemon: shim error: open pid: no such file or directory.
root@dev1:/home/vagrant# tail /var/log/upstart/docker.log
time="2016-07-28T11:25:32.743346712-07:00" level=error msg="Create container failed with error: shim error: open pid: no such file or directory"
time="2016-07-28T11:25:32.743866107-07:00" level=debug msg="attach: stderr: end"
time="2016-07-28T11:25:32.743892432-07:00" level=debug msg="attach: stdin: end"
time="2016-07-28T11:25:32.743900929-07:00" level=debug msg="attach: stdout: end"
time="2016-07-28T11:25:32.743964690-07:00" level=debug msg="Closing buffered stdin pipe"
time="2016-07-28T11:25:32.745320605-07:00" level=debug msg="Revoking external connectivity on endpoint pensive_davinci (723a9139f614f9d710b8dcaa2eda7e59d47568a6c8d7d056111ab738d36fd121)"
time="2016-07-28T11:25:32.766294436-07:00" level=debug msg="Releasing addresses for endpoint pensive_davinci's interface on network bridge"
time="2016-07-28T11:25:32.766322387-07:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
time="2016-07-28T11:25:32.766342223-07:00" level=debug msg="ReleaseAddress(LocalDefault/2001:db8:cafe:1::/64, 2001:db8:cafe:1:0:242:ac11:2)"
time="2016-07-28T11:25:32.771547037-07:00" level=error msg="Handler for POST /v1.24/containers/b1397c3fa79f301cbaf3b71dab6f8d1ac3ecf633ab38437606daabd2c7160401/start returned error: shim error: open pid: no such file or directory"
```

It's non blocking for me because i'm not using this vm anymore.

**Comment by stelund** [comment] 2016-08-23 06:46
I got this error when trying 1.12.1 on an machine with 1.11 installed. I was not specifying runc to containerd so it used runc version 0.1.1. Swapping to docker's runc solved it.

Close it.

**Comment by chefarov** [comment] 2016-11-11 14:59
Same situation after installing docker-engine in ubuntu 16.04 with newer docker version:
```
$ sudo docker run hello-world
docker: Error response from daemon: shim error: open pid: no such file or directory.

```

```
$ docker --version
Docker version 1.12.3, build 6b644ec
```

```
$ uname -a
Linux dellov 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
sudo apt list --installed | grep docker

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

docker/xenial,now 1.5-1 amd64 [installed]
docker-compose/xenial,xenial,now 1.5.2-1 all [installed]
docker-engine/ubuntu-xenial,now 1.12.3-0~xenial amd64 [installed]
python-docker/xenial,xenial,now 1.8.0-0ubuntu1 all [installed,automatic]
python-dockerpty/xenial,xenial,now 0.3.4-1build1 all [installed,automatic]
```

**Comment by mlaventure** [comment] 2016-11-11 16:45
@chefarov could you provide the `docker-containerd --version` and `docker-runc --version` output?

Do you get the error with a simple `docker run alpine ls` ?

**Comment by chefarov** [comment] 2016-11-11 17:04
yes I get the same error with alpine.

```
$ docker run alpine ls
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
3690ec4760f9: Pull complete 
Digest: sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c
Status: Downloaded newer image for alpine:latest
docker: Error response from daemon: shim error: open pid: no such file or directory.

```

```
$ docker-containerd --version
containerd version 0.2.4 commit: b818e749726ba18e430bb825396c85408dfaf2a4
```

```
$ docker-runc --version
runc version 0.0.9
commit: 57d95c1291ef64936443446f21fdb11517b807b3
spec: 0.5.0-dev
```

**Comment by mlaventure** [comment] 2016-11-11 17:09
@chefarov if you're on 1.12.3

`docker-runc` commit should be `f59ba3cdd76fdc08c004f42aa915996f6f420899`

```
$ docker --version
Docker version 1.12.3, build 6b644ec
$ docker-runc --version
runc version 1.0.0-rc2
commit: f59ba3cdd76fdc08c004f42aa915996f6f420899
spec: 1.0.0-rc2-dev
``

**Comment by chefarov** [comment] 2016-11-11 20:07
Removing docker-runc, and building from source (github) solved it.
Thank you @mlaventure

**Comment by thaJeztah** [comment] 2023-09-18 07:42
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-18 07:42 UTC
Labels: area/runtime, kind/bug, version/1.12
