### ISSUE TITLE
 The published port on service creation is not published.

### ISSUE THREAD

**Issue by cedvdb** [moby/moby#33942] opened 2017-07-04 10:15 UTC
**Description**

The published port on service creation is not published.

```
$ docker service create --name webn -p 8080:80 nginx
k5f65kcul63cqkhq7o1q0dfq3
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
efa23eed9586        nginx               "nginx -g 'daemon ..."   9 seconds ago       Up 4 seconds        80/tcp              webn.1.l7egnktbbxeq4v5sprk0h7ygl

```

**Describe the results you received:**
`80/tcp `

**Additional information you deem important (e.g. issue happens only occasionally):**

When trying to init the swarm I had to choose between two ipv6 address. I tried with both of those:

```
$ docker swarm init 
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on interface enp2s0 (xxxx:xxxx:xxxx:xxx:xxxx:xxxx:xxxx:5450 and xxxx:xxxx:xxxx:xxx:xxxx:xxxx:xxxx:fbb8)
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.27 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   -snap-9b8ed5f
 Built:        Wed Jun  7 19:49:10 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
$ docker info
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 31
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: 
Swarm: active
 NodeID: zfuo5ve95fcdh9eeg8kuxmyms
 Is Manager: true
 ClusterID: i8azkacwtdsiz5o8ph4xw4r33
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 2a02:a03f:22fc:200:b17d:f4f4:af26:5450
 Manager Addresses:
  [2a02:a03f:22fc:200:b17d:f4f4:af26:5450]:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 4ab9917febca54791c5f071a9d1f404867857fcc)
runc version: N/A (expected: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe)
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-26-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.823GiB
Name: ced-System
ID: UWMH:3AVR:VQ6L:27UO:N6BL:QM6C:JCE6:2VTG:QUNO:QSUD:FXVF:EESH
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 47
 Goroutines: 188
 System Time: 2017-07-04T12:13:20.307771185+02:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

```

**Comment by thaJeztah** [comment] 2017-07-28 05:58
This is not a bug; swarm services by default purplish their ports through a built in load balancer; the container ports therefore aren't published directly (thus port mapping doesn't show in `docker ps`)

If you run `docker service inspect <your service>` you'll see the port mapping.

closing because this is not a bug, but happy to provide more information if needed

**Closed by thaJeztah** 2017-07-28 05:58 UTC
Labels: area/swarm, version/17.03
