### ISSUE TITLE
how to debug moby in windows

### ISSUE THREAD

**Issue by 13567436138** [moby/moby#40612] opened 2020-03-03 04:42 UTC
how to debug moby in windows

**Comment by thaJeztah** [comment] 2020-03-03 09:59
Please provide more details on what you're asking; keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-03-03 09:59 UTC
Labels: kind/question, status/more-info-needed
