### ISSUE TITLE
docker build fails to persist owner:group of files

### ISSUE THREAD

**Issue by ulidtko** [moby/moby#46233] opened 2023-08-14 17:12 UTC
### Description

Repro steps below. Apparently, posix file-ownership information gets lost in the layers between 2 consequitive RUN lines.

As a result, file ownership unexpectedly resets to `root:root`.

### Reproduce

* Try to build this Dockerfile (without BuildKit):

```Dockerfile
FROM ubuntu

RUN install -d --owner nobody /test && \
    ls -ld /test && echo '              ^^^^ owner set as intended; OK'

RUN ls -ld /test && echo '        WTF  ^^^^  ?!?'

USER nobody
RUN id; touch /test/foo # Permission denied ?!?
```

* `docker build .`

### Expected behavior

Image builds successfully: because the owner of `/test` is user `nobody`, the last line has enough permissions to create files under `/test` as `USER nobody`.

### Actual behavior ###

1. Between the first `RUN` line and the next one, `/test` changes owner from `nobody` to `root`:
     ```
    [...]
    drwxr-xr-x 2 nobody root 4096 Aug 14 16:58 /test
                  ^^^^ owner set as intended; OK
    Removing intermediate container 830505308a32
     ---> 44013eb22683
    Step 3/5 : RUN ls -ld /test && echo '        WTF  ^^^^ ^^^^  ?!?'
     ---> Running in 300d4ab3cb6c
    drwxr-xr-x 2 root root 4096 Aug 14 16:58 /test
             WTF  ^^^^  ?!?
    [...]
     ```
2. The last line evokes `touch: cannot touch '/test/foo': Permission denied` — but obviously per the Dockerfile writer intent, it shouldn't.

### docker version

```bash
Client:
 Version:           20.10.25
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.25-0ubuntu1~22.04.1
 Built:             Fri Jul 14 21:58:09 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.25-0ubuntu1~22.04.1
  Built:            Thu Jun 29 21:21:05 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:        
 runc:
  Version:          1.1.7-0ubuntu1~22.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 26
  Running: 2
  Paused: 0
  Stopped: 24
 Images: 114
 Server Version: 20.10.25
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-78-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.31GiB
 Name: HP-ProBook-G8
 ID: U5UJ:I3XM:7F2T:ZHYO:GMYD:BRT3:WMH7:XWZW:RZU5:GPUX:6JJG:O6BR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2023-08-14 17:25
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/46161, and https://github.com/docker/cli/issues/4481

It's a bug in the packages that are built by the Canonical / Ubuntu packagers; see https://github.com/moby/moby/issues/46161#issuecomment-1667255217

> Bug reported in https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/2029564
> 
> You can revert to previous release of docker.io on Ubuntu 22.04. You can also `apt-mark hold` this package to prevent any update to occur until it is fixed.


Note that Docker 20.10 is quite an old version of the Engine, and Docker no longer does releases for 20.10. If you don't have a specific reason to run an older version, I would recommend installing Docker from the official packages at download.docker.com (installation instructions for ubuntu can be found in https://docs.docker.com/engine/install/ubuntu/)


I'm closing this issue as a duplicate, and because this is not a bug in the source code maintained in this repository, but feel free to continue the conversation.

I should also mention that images built with that version of Docker will have the wrong permissions in them, so you may want to re-build images built with the faulty version.

**Closed by thaJeztah** 2023-08-14 17:25 UTC
Labels: kind/bug, area/packaging, version/20.10, kind/duplicate

**Comment by ulidtko** [comment] 2023-08-14 17:27
Thanks for quick triage @thaJeztah :pray:
