### ISSUE TITLE
Push to docker registry fails with error "no basic auth credentials"

### ISSUE THREAD

**Issue by rasheedamir** [moby/moby#35684] opened 2017-12-03 22:00 UTC
**Description**

We have a private docker registry (Nexus3) protected with basic authentication. We have verified the `config.json` by pushing to the registry from local machine but it fails from the Jenkins slave (k8s) pod when provided same `config.json`. It does seem a very basic issue but we have struggled a lot and yet aren't able to fix it.

**Steps to reproduce the issue:**

(ofc I have modified the auth token and the the registry url is not real one)

1. provide a config.json like following:

`cat /home/jenkins/.docker/config.json`

```
{
  "auths": {
    "https://docker.tools.app.com:443": {
      "auth" : "ZGRhZG2pbjpBbHRlcm6hdGl2ZWx5Tm9uc2Vuc2X="
    }
  }
}
```

2. Build a docker image

`docker build -t docker.tools.app.com:443/i18n:vf642fe9 .`

And the docker build is successful; as expected.

**Describe the results you received:**

It fails with error `no basic auth credentials`

**Describe the results you expected:**

We expected it to push to the registry.

**Additional information you deem important (e.g. issue happens only occasionally):**

- We have used the same config.json to push a docker image from local machine (Mac) and the push was successful.
- The k8s is running on CoreOS.

**Output of `docker version`:**

`docker version`

```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: 
 Go version:      go1.7.6
 Git commit:      d9ad3fc
 Built:           Thu Nov 30 10:52:56 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

`docker info`

```
Containers: 36
 Running: 19
 Paused: 0
 Stopped: 17
Images: 115
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.13.16-coreos-r1
Operating System: Container Linux by CoreOS 1520.9.0 (Ladybug)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-15-245-000-000.eu-best-1.compute.internal
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 10.0.0.0/8
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- AWS
- Kubernetes
- Jenkins on kubernetes

**Comment by thaJeztah** [comment] 2017-12-03 23:39
How do you provide the credentials to the jenkins pod? What version of the CLI is running inside that pod, or is Jenkins using the CLI on the host?

Note that Docker 1.12 has reached end of life in March, and hasn't been maintained since; in addition, CoreOS is not a supported platform, and the Docker packages on CoreOS are maintained/supported by CoreOS.

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-03 23:39 UTC
Labels: area/builder, version/1.12

**Comment by rasheedamir** [comment] 2017-12-04 07:15
Thanks for quick response @thaJeztah 

Please find answers inline below:

> How do you provide the credentials to the jenkins pod?
Here you can find it:

https://github.com/stakater/fabric8-pipeline-library/blob/deploy-node-app/vars/clientsTemplate.groovy#L60

> What version of the CLI is running inside that pod, or is Jenkins using the CLI on the host?
Its using the CLI on the host. You can see it here:

https://github.com/stakater/fabric8-pipeline-library/blob/deploy-node-app/vars/clientsTemplate.groovy#L64

> Note that Docker 1.12 has reached end of life in March, and hasn't been maintained since; in addition, CoreOS is not a supported platform, and the Docker packages on CoreOS are maintained/supported by CoreOS.
Thanks for the info; I didn't know that. I do think its something related to the structure of `config.json` but not sure what is the issue.

**Comment by thaJeztah** [comment] 2017-12-04 21:30
> Its using the CLI on the host. You can see it here:

That's bind-mounting the docker _socket_, so the container will have access to the docker _api_. Is a docker _cli_ used inside the container you're starting, or is something else used that connects to the docker api?

**Comment by rasheedamir** [comment] 2017-12-05 09:17
The docker cli is being used inside the container; and here are the commands which are are run:

https://github.com/stakater/fabric8-pipeline-library/blob/deploy-node-app/vars/performCanaryRelease2.groovy#L25-#L35

**Comment by thaJeztah** [comment] 2017-12-06 01:00
Looks like the Dockerfile installs the Red Hat fork of Docker; https://github.com/fabric8io-images/builder-clients/blob/9c7b90f08dab2f8179afb9d3b54a3846dbf89921/Dockerfile#L3-L4

Which gets me;

```bash
docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Does it work if you install the official Docker package inside the container? Given that you're probably only interested in the CLI, you could [install the static binaries](https://docs.docker.com/engine/installation/linux/docker-ce/binaries/#install-static-binaries), or copy the static CLI binary from the official Docker image;


```Dockerfile
FROM centos:7
COPY --from=docker:17.09 /usr/local/bin/docker /usr/local/bin
```

**Comment by rasheedamir** [comment] 2017-12-07 06:16
Great thanks @thaJeztah 

I was able to fix it by creating a slave (pod) with latest docker binaries.
