### ISSUE TITLE
DOCKER_LDFLAGS environment variable not updating ldflags on build

### ISSUE THREAD

**Issue by maggie0002** [moby/moby#44729] opened 2023-01-01 13:50 UTC
### Description

In the Make file there is a note that you can pass in LDFLAGS at build time via the Makefile:

https://github.com/moby/moby/blob/d109e429dd69bbfc2b575c11e66cbd98364a860b/Makefile#L27-L31

When I pass `make DOCKER_LDFLAGS="-s"` I was expecting it to acknowledge the flag and reduce the build size but it seems to be ignored.

If I manually add the flag to the LDFLAGS in the .go-autogen file it does reduce the build size.

```
LDFLAGS="-s ${LDFLAGS} \
	-X \"github.com/docker/docker/dockerversion.Version=${VERSION}\" \
	-X \"github.com/docker/docker/dockerversion.GitCommit=${GITCOMMIT}\" \
	-X \"github.com/docker/docker/dockerversion.BuildTime=${BUILDTIME}\" \
	-X \"github.com/docker/docker/dockerversion.IAmStatic=${IAMSTATIC:-true}\" \
	-X \"github.com/docker/docker/dockerversion.PlatformName=${PLATFORM}\" \
	-X \"github.com/docker/docker/dockerversion.ProductName=${PRODUCT}\" \
	-X \"github.com/docker/docker/dockerversion.DefaultProductLicense=${DEFAULT_PRODUCT_LICENSE}\" \
"
```
https://github.com/moby/moby/blob/d109e429dd69bbfc2b575c11e66cbd98364a860b/hack/make/.go-autogen#L3

### Reproduce

As above.

### Expected behavior

Build size on my Mac M2 is reduced to 53.1mb from 61.9 when manually adding the `-s` flag but isn't reduced when passing the environment variable to the make file. 

### docker version

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:41 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 29
  Running: 5
  Paused: 0
  Stopped: 24
 Images: 22
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 11.68GiB
 Name: docker-desktop
 ID: 6ASP:XA33:BF5S:EPYM:ZY4R:NU2R:GMQT:3S4A:L7CC:KWQ4:PHVT:NLW6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by bsousaa** [comment] 2023-01-03 11:31
Doesn't looks like this was introduced recently, but probably something we should fix. cc @crazy-max

**Comment by crazy-max** [comment] 2023-01-03 11:37
@maggie0002 We have merged https://github.com/moby/moby/pull/44546 recently, it should work as expected:

```
make DOCKER_LDFLAGS="-s"
docker buildx bake binary --print
{
  "group": {
    "default": {
      "targets": [
        "binary"
      ]
    }
  },
  "target": {
    "binary": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "APT_MIRROR": "cdn-fastly.deb.debian.org",
        "BUILDKIT_CONTEXT_KEEP_GIT_DIR": "1",
        "DEFAULT_PRODUCT_LICENSE": "",
        "DOCKER_BUILDTAGS": "",
        "DOCKER_DEBUG": "",
        "DOCKER_GITCOMMIT": "b9fe30dad4",
        "DOCKER_LDFLAGS": "-s",
        "DOCKER_STATIC": "1",
        "PACKAGER_NAME": "",
        "PLATFORM": "",
        "PRODUCT": "",
        "VERSION": ""
      },
      "target": "binary",
      "output": [
        "./bundles/binary"
      ]
    }
  }
}
```

**Comment by neersighted** [comment] 2023-01-30 15:47
I can no longer reproduce this on master -- please let us know if you think it's not fixed.

**Closed by neersighted** 2023-01-30 15:47 UTC
Labels: status/0-triage, kind/bug
