### ISSUE TITLE
go get with commit (go modules)

### ISSUE THREAD

**Issue by llitfkitfk** [moby/moby#37753] opened 2018-09-03 09:29 UTC
docker-ce v18.05.0 
https://github.com/docker/docker-ce/blob/v18.05.0-ce/components/cli/vendor.conf#L8

when execute `go get github.com/docker/docker`,
got correct result:
```
/home/demo # go get -v github.com/docker/docker@ed7b6428c133e7c59404251a09b7d6b02fa83cc2
go: finding github.com/docker/docker ed7b6428c133e7c59404251a09b7d6b02fa83cc2
go: downloading github.com/docker/docker v0.7.3-0.20180327123150-ed7b6428c133
go: finding github.com/docker/docker v1.13.1
go: downloading github.com/docker/docker v1.13.1
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
```

**However**

**docker-ce v18.06.0 ~ v18.06.1**

https://github.com/docker/docker-ce/blob/v18.06.1-ce/components/cli/vendor.conf#L10

when execute `go get github.com/docker/docker` 
got **error**: 
```
/home/demo # go get -v github.com/docker/docker@371b590ace0d4a329cd6a3328d31d33c4f77a780
go: finding github.com/docker/docker 371b590ace0d4a329cd6a3328d31d33c4f77a780
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
go get github.com/docker/docker@371b590ace0d4a329cd6a3328d31d33c4f77a780: unknown revision 371b590ace0d4a329cd6a3328d31d33c4f77a780
```

Expected:
The correct commit need to get with docker-ce v18.06.0 version

**Comment by cpuguy83** [comment] 2018-09-04 14:34
It's because the repo is here: https://github.com/docker/engine

**Comment by flyinprogrammer** [comment] 2018-09-07 20:09
So I barely know what I'm doing, but I made this little test project. If this is the "correct" way to do this, then oh goodness, this is very broken in my opinion.

https://github.com/flyinprogrammer/dewme

**Comment by cpuguy83** [comment] 2018-09-07 20:44
@flyinprogrammer More or less. The way go modules pick versions is different than what is traditional.
Perhaps it would be simpler if packages defined their own go.mod files... I haven't played around with it a ton yet.

**Comment by llitfkitfk** [comment] 2018-09-10 10:13
@flyinprogrammer 
Thanks

**Comment by andrewpillar** [comment] 2018-12-20 14:02
Do you know when/if the Docker SDK is going to support Go modules? Current work around I have is similar to what @flyinprogrammer showed.

**Comment by cpuguy83** [comment] 2018-12-20 14:10
Go modules works just fine, but you need to use the right repo.

**Comment by andrewpillar** [comment] 2018-12-20 14:12
Thanks.

**Comment by thaJeztah** [comment] 2018-12-20 20:37
Let me close this one, as it's not really a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-12-20 20:37 UTC
Labels: area/project, kind/question

**Comment by tankbusta** [comment] 2018-12-27 22:15
It's incredibly difficult to use the API/client code if we have to manually muck with go.mod as @flyinprogrammer demonstrated. 

Also "use the right repo" isn't very clear. Why is the repo `github.com/docker/engine` when the import string in https://github.com/docker/engine/blob/master/client/client.go#L42 points to `github.com/docker/docker/client` which is a redirect to `https://github.com/moby/moby`? As an outsider, this is very confusing.

**Comment by flyinprogrammer** [comment] 2018-12-31 00:14
> as it's not really a bug

I guess it's not a bug 😢but idk how this project or the other project is ever going to support something like this: https://github.com/golang/go/issues/26420 in the current form of this release process.

I would hope that Docker Inc. would be invested in a sane way for people to use these APIs.

**Comment by st3fan** [comment] 2019-04-18 02:35
Are you sure?

```
go get -v github.com/docker/engine@v18.09.5
go: finding github.com/docker/engine v18.09.5
go: downloading github.com/docker/engine v0.0.0-20190408150954-50ebe4562dfc
go: extracting github.com/docker/engine v0.0.0-20190408150954-50ebe4562dfc
go: finding github.com/docker/engine v1.13.1
go: downloading github.com/docker/engine v1.13.1
go: extracting github.com/docker/engine v1.13.1
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
```

I ask for v18.09.5 and I get v1.13.1. I'm also confused about what to do here.

**Comment by webern** [comment] 2019-07-07 00:29
So what is the go get statement that I should be using if I want to use this package?

`github.com/docker/docker/client`
