### ISSUE TITLE
`docker commit --change 'ENV X=...$X'` does not substitute image environment

### ISSUE THREAD

**Issue by asottile** [moby/moby#35580] opened 2017-11-22 18:51 UTC
## Description

I expect the following two things to be _roughly_ equivalent, however they are not.  My actual usecase involves `$PATH` augmentation and a more complex `commit` cycle, the "example" in this issue is a MVCE.  I've been careful in the example to quote properly -- this is not a substitution coming from the shell running `docker commit`.

### via dockerfile

```dockerfile
FROM ubuntu:xenial
ENV X=1
ENV X=2:$X
```

```bash
docker build -q -t test .
docker inspect test --format='{{.Config.Env}}'
```

```console
$ docker build -q -t test .
sha256:9e1a10d984e0e2457620c83175888546820272b82fb0103d65da273ab74dd732
$ docker inspect test --format='{{.Config.Env}}'
[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin X=2:1]
```

**Notice here that `X=2:1`**

### via `docker commit`

```dockerfile
FROM ubuntu:xenial
ENV X=1
```

```bash
docker build -q -t test .
CID=$(docker create test)
docker commit --change 'ENV X=2:$X' "$CID" test
docker rm  "$CID"
docker inspect test --format='{{.Config.Env}}'
```

```console
$ docker build -q -t test .
sha256:2d7a6b4f468a894a38a669f8c9a826cac17f2f6eb4ff7f1a7bc51d6e5950325a
$ CID=$(docker create test)
$ docker commit --change 'ENV X=2:$X' "$CID" test
sha256:7f9767be8464c4a48ad5c7545f7986c5b8a898ab1b64026ecaad2dfb0409146a
$ docker rm  "$CID"
8c7957c982bf4b34eb91d5268c9cfe96d2b49743b9342850c3d9d99f504996f2
$ docker inspect test --format='{{.Config.Env}}'
[X=2: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
```

**Notice here that `X=2:`** (the environment substitution from the parent is lost)

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 35
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-40-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.795GiB
Name: asottile-VirtualBox
ID: MCDD:BXAL:Y4PM:SIA7:I73R:W3F6:C4IY:ZEP4:K44W:XLYA:USI2:FAMT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

virtualbox, but I don't think it's important.

**Comment by thaJeztah** [comment] 2017-11-22 19:39
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/30538

Expansion of these variables is a feature of the "builder" component that's used during `docker build`. While `docker commit` allows you to change some values of the image, it's not a replacement for `docker build`. If you _do_ want to use it as a replacement, querying values of existing environment variables (for expansion) would have to be done by inspecting the image/container.

I'm closing this because this is a duplicate the expected behaviour, but feel free to discuss 👍

**Closed by thaJeztah** 2017-11-22 19:39 UTC
Labels: area/builder, version/17.09

**Comment by asottile** [comment] 2017-11-22 19:48
sounds good -- I'll follow up in that ticket!
