### ISSUE TITLE
How to Recovery From Swarm Mode Manager Status  Missing?

### ISSUE THREAD

**Issue by swift1911** [moby/moby#38004] opened 2018-10-10 16:02 UTC
My Swarm Cluster has been a wrong state,my state.json is empty and my manager status is empty too.So how to solve this?

![image](https://user-images.githubusercontent.com/9301003/46749558-96d7bc80-cce8-11e8-9581-bc9f49691624.png)

![image](https://user-images.githubusercontent.com/9301003/46749741-f9c95380-cce8-11e8-9a16-4a38ff19f8f1.png)

![image](https://user-images.githubusercontent.com/9301003/46749776-0f3e7d80-cce9-11e8-891b-50196d0f941f.png)

![image](https://user-images.githubusercontent.com/9301003/46749810-21b8b700-cce9-11e8-8958-37cd736a6535.png)

**Comment by thaJeztah** [comment] 2018-10-22 14:19
I'm not entirely sure what you mean with "in the wrong state"; if you encounter issues, and need to troubleshoot, I'd start with checking logs of each of the daemons. 

Please keep in mind though that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-10-22 14:19 UTC
