### ISSUE TITLE
Error in docker-ce_17.09.0-ce-0-ubuntu_amd64.deb installation in Lubuntu 17.04

### ISSUE THREAD

**Issue by beingyash** [moby/moby#35133] opened 2017-10-09 05:52 UTC
**Description** 
Docker noob here. Docker has stopped working from 07-10-2917 onwards as i installed some Lubuntu updates. There was no response for even `sudo docker --version` after those updates, however when i tried to make another clean install by removing docker and the left over files as suggested in Docker docs `sudo apt-get purge docker-ce` and then `sudo rm -rf /var/lib/docker` and then trying to install it again, initially from the stable repo (from the official docs) the installtion completed with a number of errors. So, i removed it downloaded the docker-ce_17.09.0-ce-0-ubuntu_amd64.deb file for installation which again gave the same errors during installation.

The error:
```sudo dpkg -i /home/z/Downloads/Deb\ Packages/docker-ce_17.09.0-ce-0-ubuntu_amd64.deb 
Selecting previously unselected package docker-ce.
(Reading database ... 162529 files and directories currently installed.)
Preparing to unpack .../docker-ce_17.09.0-ce-0-ubuntu_amd64.deb ...
Unpacking docker-ce (17.09.0~ce-0~ubuntu) ...
Setting up docker-ce (17.09.0~ce-0~ubuntu) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-10-09 10:22:14 IST; 6ms ago
     Docs: https://docs.docker.com
  Process: 6485 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 6485 (code=exited, status=1/FAILURE)
      CPU: 27ms

Oct 09 10:22:14 Z-ThinkPad systemd[1]: docker.service: Unit entered failed …ate.
Oct 09 10:22:14 Z-ThinkPad systemd[1]: docker.service: Failed with result '…de'.
Hint: Some lines were ellipsized, use -l to show in full
dpkg: error processing package docker-ce (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (232-21ubuntu7) ...
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 docker-ce
z@Z-ThinkPad:~$ systemctl staatus docker,service
Unknown operation staatus.
z@Z-ThinkPad:~$ systemctl staatus docker.service
Unknown operation staatus.
z@Z-ThinkPad:~$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-10-09 10:22:15 IST; 3min 45s ago
     Docs: https://docs.docker.com
  Process: 6887 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 6887 (code=exited, status=1/FAILURE)
      CPU: 30ms
```

After this installation `sudo docker --version` still provides the version of docker as `Docker version 17.09.0-ce, build afdb6d4` though rest of the docker cli commands produce an error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Additional information you deem important :**
Upon checking `systemctl status docker.service` following output is produced :
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-10-09 10:22:15 IST; 3min 45s ago
     Docs: https://docs.docker.com
  Process: 6887 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 6887 (code=exited, status=1/FAILURE)
      CPU: 30ms

Oct 09 10:22:15 Z-ThinkPad systemd[1]: docker.service: Unit entered failed state.
Oct 09 10:22:15 Z-ThinkPad systemd[1]: docker.service: Failed with result 'exit-code'.
Oct 09 10:22:15 Z-ThinkPad systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Oct 09 10:22:15 Z-ThinkPad systemd[1]: Stopped Docker Application Container Engine.
Oct 09 10:22:15 Z-ThinkPad systemd[1]: docker.service: Start request repeated too quickly.
Oct 09 10:22:15 Z-ThinkPad systemd[1]: Failed to start Docker Application Container Engine.
Oct 09 10:22:15 Z-ThinkPad systemd[1]: docker.service: Unit entered failed state.
Oct 09 10:22:15 Z-ThinkPad systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Output of `docker version`:**

`Docker version 17.09.0-ce, build afdb6d4`

**Output of `docker info`:**
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
`

**Comment by thaJeztah** [comment] 2017-10-09 16:26
It's hard to tell what's causing the problem; the logs printed in the `systemctl status` output are not the full logs, and some lines are truncated (`docker.service: Unit entered failed …ate`) so don't contain anything useful.

I sugest checking the full logs for docker and your system logs (using `journalctl -xe` or similar), to see if there's anything in there that may be helpful. You can also run the `check-config.sh` script (which can be found here: https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh), to see if anything is missing after you upgraded your system.

Be aware that Lubuntu is not an officially supported distro and, while based on Ubuntu, there may be differences.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

If you suspect there's a bug at hand, or a problem with the packages, please open an issue in the https:/github.com/docker/for-linux/issues issue tracker, which is for reporting bugs in Docker CE

I'll close this issue because I suspect this is not a bug, but an issue in your system's configuration, but feel free to comment after I closed

**Closed by thaJeztah** 2017-10-09 16:26 UTC

**Comment by Canalytic** [comment] 2017-10-11 03:33
I am getting this same error for 16.04 Ubuntu, so it might not be specific to Lubuntu

**Comment by beingyash** [comment] 2017-10-11 04:01
Thanks for the heads up @thaJeztah, i'll keep that in mind, though since i was clueless regarding the situation, i came here. However since i couldn't afford to lose anymore time, i just reinstalled the os and disabled updates this time. Everything's been fine since then.
@Canalytic If you are taking about the error after the installation, the one where it's unable to find the docker daemon, that could be for various reasons which you can definitely look around in the docker forums but if it's about the error during the installation, i suggest you start a thread in the forums or stackoverflow instead as @thaJeztah  pointed out.

**Comment by Canalytic** [comment] 2017-10-11 04:43
Thanks @beingyash .  It seems once I turned off my VPN I could install it ok.  I don't really understand why this is the case, but at least I have the environment setup now!

**Comment by gtzinos** [comment] 2017-11-15 11:41
Same problem there. Any workaround guys ? 

journalctl -xe output:

```
Nov 15 06:39:29 server systemd[1]: docker.service: Start request repeated too quickly.
Nov 15 06:39:29 server systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Nov 15 06:39:29 server systemd[1]: docker.socket: Unit entered failed state.
Nov 15 06:40:01 server CRON[20543]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 15 06:40:01 server CRON[20544]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Nov 15 06:40:01 server CRON[20543]: pam_unix(cron:session): session closed for user root
Nov 15 06:41:33 server systemd[1]: Starting Cleanup of Temporary Directories...
-- Subject: Unit systemd-tmpfiles-clean.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-tmpfiles-clean.service has begun starting up.
Nov 15 06:41:33 server systemd-tmpfiles[20550]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Nov 15 06:41:33 server systemd[1]: Started Cleanup of Temporary Directories.
-- Subject: Unit systemd-tmpfiles-clean.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-tmpfiles-clean.service has finished starting up.
--
-- The start-up result is done.
lines 2291-2318/2318 (END)
Nov 15 06:39:29 server systemd[1]: docker.service: Start request repeated too quickly.
Nov 15 06:39:29 server systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Nov 15 06:39:29 server systemd[1]: docker.socket: Unit entered failed state.
Nov 15 06:40:01 server CRON[20543]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 15 06:40:01 server CRON[20544]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Nov 15 06:40:01 server CRON[20543]: pam_unix(cron:session): session closed for user root
Nov 15 06:41:33 server systemd[1]: Starting Cleanup of Temporary Directories...
-- Subject: Unit systemd-tmpfiles-clean.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-tmpfiles-clean.service has begun starting up.
Nov 15 06:41:33 server systemd-tmpfiles[20550]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Nov 15 06:41:33 server systemd[1]: Started Cleanup of Temporary Directories.
-- Subject: Unit systemd-tmpfiles-clean.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-tmpfiles-clean.service has finished starting up.
--
-- The start-up result is done.
```

**Comment by Dexus** [comment] 2017-11-16 10:36
Please RUN the check script from https://github.com/moby/moby/issues/35133#issuecomment-335209169

and if you have no aufs use one of the other storage drivers.

/etc/docker/deamon.json:
```JSON
{
"storage-driver": "overlay"
}
```

That works for me, before I had the same problems.

**Comment by thaJeztah** [comment] 2017-11-16 12:27
Adding to the above: on a 4.x kernel definitely consider using `overlay2` instead of `overlay`
