### ISSUE TITLE
Docker log driver secondary? if fluentd daemon is gone where can find log?

### ISSUE THREAD

**Issue by Renz2018** [moby/moby#39244] opened 2019-05-21 03:47 UTC
If I use fluentd driver , container will send log to fluentd.
Someday my fluentd is failed, after a few hours , I restart fluentd
But fluentd log driver not continue send log to fluentd,
How can I find logs ???

**Comment by thaJeztah** [comment] 2019-05-26 00:02
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-05-26 00:02 UTC
