### ISSUE TITLE
Hit "Failed to start docker.service: Unit not found." issue

### ISSUE THREAD

**Issue by yuehliu** [moby/moby#40810] opened 2020-04-11 10:24 UTC
**Description**

**Steps to reproduce the issue:**
1. unarchive docker-19.03.8.tgz and copy binary file to /usr/bin
2. copy docker.service and docker.socket files to /usr/lib/systemd/system/, these two files are from other hosts which installed the same docker version
3. systemctl start docker => Failed to start docker.service: Unit not found.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
systemctl enable docker will be executed successfully

**Output of `docker version`:**
19.03.8
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment] 2020-04-11 11:08
`systemctl daemon-reload`

**Comment by thaJeztah** [comment] 2020-04-14 13:34
This looks like a support question, not a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2020-04-14 13:34 UTC
Labels: kind/question
