### ISSUE TITLE
FIXME: Got an API for which error does not match any expected type!!!

### ISSUE THREAD

**Issue by dragon9783** [moby/moby#38877] opened 2019-03-14 06:05 UTC
docker rm -f $(docker ps -af)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
kill containers failed

**Describe the results you expected:**
kill containers success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 31
 Running: 31
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54GiB
Name: supos103
ID: J7FJ:IGD3:GT2L:IUSY:5O4V:HBH4:ZDWH:62YZ:UM6I:4EDU:WWE3:C4LR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 registry.supos.ai
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker daemon log:
```
Mar 14 09:15:21 supos103 dockerd[1129]: time="2019-03-14T09:15:21.981733328+08:00" level=error msg="Handler for POST /v1.37/containers/4de08b91e26a/stop returned error: cannot stop container: 4de08b91e26a: Cannot kill container 4de08b91e26ada75f377df2a45b46a598bd0c652c759cde90eb918c8ac614c9f: connection error: desc = \"transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout\": unknown"
Mar 14 09:15:21 supos103 dockerd[1129]: time="2019-03-14T09:15:21.981858615+08:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unknown\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/errdefs.init\n\t/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs/errors.go:23\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/content.init\n\t<autogenerated>:1\ngithub.com/docker/docker/vendor/github.com/containerd/containerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/libcontainerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster/executor/container.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster.init\n\t<autogenerated>:1\ngithub.com/docker/docker/api/server/router/network.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:183\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337" error_type="*errors.fundamental" module=api
Mar 14 09:15:21 supos103 dockerd[1129]: time="2019-03-14T09:15:21.985533098+08:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unknown\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/errdefs.init\n\t/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs/errors.go:23\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/content.init\n\t<autogenerated>:1\ngithub.com/docker/docker/vendor/github.com/containerd/containerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/libcontainerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster/executor/container.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster.init\n\t<autogenerated>:1\ngithub.com/docker/docker/api/server/router/network.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:183\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337" error_type="*errors.fundamental" module=api
```

**Comment by imxyb** [comment] 2019-03-28 02:42
Are you execute `$ sudo dockerd --containerd /var/run/dev/docker-containerd.sock`?

**Comment by thaJeztah** [comment] 2019-04-01 13:35
Are you also still able to reproduce this on a current version of Docker? Note that Docker 18.03 reached EOL in June, so if there's something to be fixed, it won't be backported to 18.03

**Comment by fzu-huang** [comment] 2019-09-25 12:56
I also meet this problem on  docker-ce 18.06 ,  debian 9.1
### what happened
1. kubernetes pod keep `terminating`, I check chontainer and found that `docker ps` is ok but `docker inspect $containerID` is stucked.
2. run `systemdctl stop docker` ,also stucked, then I check `/var/log/daemon.log` , the log `FIXME: Got an API for which error does not match any expected type!!!` occured. 
3. I keep check log and found that dokcerd socket has been ` broken-pipe`  for  1 hour. And I suspect that this is related to systemd user manager, because I saw a lot of log with `Stopping User Manager for UID 0` and `Started User Manager for UID 0`

**Comment by thaJeztah** [comment] 2020-03-10 08:47
closing this one as it's quite old now, and no clear steps to reproduce

**Closed by thaJeztah** 2020-03-10 08:47 UTC
Labels: area/runtime, status/more-info-needed, version/18.03

**Comment by markmaker** [comment] 2022-12-20 13:10
I guess this happens when you execute docker without the proper access rights. In my case it resolved itself after I properly set the "docker" group up:

```
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
```

The first command may say 
`groupadd: group 'docker' already exists`
but that's OK.

The `FIXME:` should probably still be fixed, as the error is very cryptic and actually points to a secondary bug during error handling. 

Steps to reproduce:

- use a user that is not member of the docker group
- use a Dockerfile with multiple FROM clauses

```
FROM alpine as buildenv
WORKDIR .
RUN apk add \
  clang clang-dev alpine-sdk musl-dev

FROM buildenv as builder
WORKDIR .
RUN clang --version

```
Save as `Dockerfile.repro`. Executed as follows:

`docker -D build -f Dockerfile.repro -t repro .`

```
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!  error="Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.repro&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=repro&target=&ulimits=null&version=1\": dial unix /var/run/docker.sock: connect: permission denied" module=api status_code=-1
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.repro&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=repro&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by thaJeztah** [comment] 2022-12-20 14:52
Ah! So, yes, that debug message was mostly intended for the daemon-side; we use an `errdefs` package to classify errors, which allows the API to return a suitable status-code (e.g., `400` or `403`); any error that does not have a specific type assigned will default to a `500` ("internal server error"), which may not be _correct_ in many cases. There's many possible code paths for errors to occur, so the debug log is there for those code-path that were missed.

_However_ the same utility is used in the CLI as well, and in this case, no connection could be made with the API (due to the permissions issue); the client looks to set a default `-1` status code; https://github.com/moby/moby/blob/3e39ec60dab859f70577ea8561fe5bda5236749e/client/request.go#L133-L134

Probably this was there to indicate "we didn't get a status code", although the commit that added it doesn't explicitly call this out; https://github.com/moby/moby//commit/589df17a1a1dc649a4c3095cea6dd05e0c2a3bb5 (part of https://github.com/moby/moby/pull/18472).

There's not much the client can do in this case, so we shouldn't log the warning. That probably needs some further thinking, but at least (I think) we should change the logic, and

- don't log if statuscode is < 0 (maybe exclude 0 as well?)
- only print the log if we end up returning an `errdefs.Unknown` (other cases _seem_ to be "valid" as we  had a status-code, and were able to convert it)

https://github.com/moby/moby/blob/3e39ec60dab859f70577ea8561fe5bda5236749e/errdefs/http_helpers.go#L35-L51

**Comment by thaJeztah** [comment] 2022-12-20 14:53
Actually; I don't think we should be logging at all in this function; this utility is _only_ used on the client side. The counterpart on the daemon side is in https://github.com/moby/moby/blob/3e39ec60dab859f70577ea8561fe5bda5236749e/api/server/httpstatus/status.go#L68-L71.

For the client-side, this looks to have been a mistake on my side when I added the `FromStatusCode` utility. I implemented that to be the counterpart to `FromError` above, but in doing so also copied over the logging 🤦 🙈 😂 ; https://github.com/moby/moby/commit/1af30c50ca0ad81e2839ff4f2c5e70413f021d52 (part of https://github.com/moby/moby/pull/38689)

**Comment by markmaker** [comment] 2022-12-20 15:11
Just in case you have a minute to explain. 🤓

Why does it only seem to happen with two `FROM` clauses?

**Comment by thaJeztah** [comment] 2022-12-20 15:18
Not sure exactly (I would have to try to follow code-paths). Perhaps it triggers a second call to the API (perhaps to check if the image needs to be pulled) and only the second one is shown, although (from the top of my head) it would just send the build-context and have the daemon do that work 🤔 

Is this happening with the legacy builder, or with `DOCKER_BUILDKIT=1`?

**Comment by markmaker** [comment] 2022-12-20 15:25
My mistake. I thought it was the two FROM clauses, but it's actually the -D option that I must have forgotten on the simpler case I tested. So the following is actually sufficient to reproduce the FIXME message:

`docker -D run  hello-world`

> Is this happening with the legacy builder, or with DOCKER_BUILDKIT=1?

Sorry, I don't know what these are 🫣

**Comment by thaJeztah** [comment] 2022-12-20 15:38
Ah, right, so yes, `-D` (or `--debug`) enables debug logs on the CLI side, which will cause the debug log to be printed (otherwise it's not).

> Sorry, I don't know what these are 🫣

`docker build` is executed by the Docker Daemon (which does the actual "build"). The builder was originally implemented as a (fairly naive) chain of `docker run <RUN instruction> && `docker commit` commands (well, the "equivalent" of that on the daemon side). (each step in the Dockerfile would start a container, execute a command, and commit the results to a new image layer).

BuildKit is a full reimplementation of the builder, which allows for better caching of build-steps (Dockerfile instructions) and (in various cases) perform steps without even starting a container (metadata-only changes), which can result in faster, more optimised builds (in some cases _multiple times_ faster, but depends on the situation). 

BuildKit is a separate project (https://github.com/moby/buildkit), and _can_ run standalone, but is also included in the Docker Daemon (since Docker 18.09 I think?); BuildKit uses a gRPC API, and is not yet used by default (it will be in the next release), but to enable it, the CLI needs to switch to use the BuildKit API; the easiest way to do so is to set the `DOCKER_BUILDKIT=1` environment variable; setting that will make the CLI use BuildKit; so in your case;


```bash
export DOCKER_BUILDKIT=1

docker -D build -f Dockerfile.repro -t repro .
```

**Comment by markmaker** [comment] 2022-12-20 15:42
Oh, good to know, will certainly experiment with that, thanks!

**Comment by thaJeztah** [comment] 2022-12-20 15:43
Also look at https://docs.docker.com/go/buildkit/ for a starting point on BuildKit in the docker documentation.

**Comment by thaJeztah** [comment] 2022-12-20 15:46
^^ I should mention that some of that section is about running BuildKit standalone (which isn't needed if you have a current version of Docker installed).

**Comment by markmaker** [comment] 2022-12-20 16:36
Thanks. I have version 20.10.22, build 3a2c30b, it works! Not faster per se, but that's probably a question of the use case. 

Results: 0.624s with `DOCKER_BUILDKIT=1` vs. 0.180s on legacy. That's the fully cached build (installing many dev packets, then copying source code, then compiling C++).

I would need to figure out how to make it output all the stdout/stderr. 🤔

**Comment by thaJeztah** [comment] 2022-12-22 18:37
> Results: 0.624s with DOCKER_BUILDKIT=1 vs. 0.180s on legacy. That's the fully cached build (installing many dev packets, then copying source code, then compiling C++).

Hmm.. interesting; I wonder where that difference comes from. There's  a couple of things I _could_ think of

- BuildKit uses an interactive session between the client and the daemon to only send over files it needs, _possibly_ there's some extra work involved there
- it could be related to authentication
- BuildKit may check the image registry to verify the image has the correct checksum

Is this a public repository (so that we could look why it's slower)?

> I would need to figure out how to make it output all the stdout/stderr. 🤔

The default output from BuildKit tries to only output of build-steps while they're happening; if you want the full (less nice-looking, but more verbose) output, you can use the `--progress=plain` option. I also have an open feature request for logs (see https://github.com/moby/buildkit/issues/1837), and there's some work ongoing to provide the essentials for that (see https://github.com/moby/buildkit/pull/3339)

**Comment by markmaker** [comment] 2022-12-23 08:20
> Is this a public repository (so that we could look why it's slower)?

Thanks, no not public and very much work in progress. But I do understand the notion of "amortized cost". It is easy to understand how a smarter and more versatile solutions can have larger initial cost to set up all the smartness in the first place, so if there is nothing to do (all cached) there is higher cost. It is when real work needs to be done, but as little as possible (i.e. optimizing caching), where it will pay dividends. 

> --progress=plain

Thanks. I guess that'll be the default when BuildKit becomes the standard in upcoming versions, in order to not change behavior. 🤓

**Comment by thaJeztah** [comment] 2022-12-27 17:00
>  I guess that'll be the default when BuildKit becomes the standard in upcoming versions, in order to not change behavior. 🤓

The default is "auto", which switches between "plain" and "tty" based on wether a TTY is attached (so that, e.g., output in CI without a TTY attached will produce something sensible. There's also a `BUILDKIT_PROGRESS` environment-variable that allows overriding it (if setting the `--progress` flag is inconvenient to do).

The output won't be "compatible" (note that the output format is not a formal output); due to BuildKit's capability to build stages in parallel (where possible), and to de-duplicate steps (in some cases), progress output may appear in a different order than steps in the Dockerfile itself, which is why the `plain` output has a somewhat different format.
