### ISSUE TITLE
Swarm Mode 17.10-ce: Cannot allocate memory

### ISSUE THREAD

**Issue by lukeescude** [moby/moby#35243] opened 2017-10-18 18:15 UTC
We have Docker running in Swarm Mode across 6 hosts - All of them are Managers. There are 0 worker nodes.

We have about 50 containers running across all 6 nodes, nothing crazy, but recently we've been having a manager node lock up, and stop running completely.

There are two errors that pop up a lot during one of these lock-ups:
failed to retrieve docker-runc version: fork/exec /usr/bin/docker-runc: cannot allocate memory
failed to retrieve docker-init version: fork/exec /usr/bin/docker-init: cannot allocate memory

During the lock-up, the containers just freeze. They don't reschedule on another manager node, they just sit there and cease operation.

How should we go about diagnosing this issue?

Note: Each Manager has 16GB ram, but the containers only occupy about 3 of that or less. When this event occurs, the host is reporting no abnormal RAM usage.

**Comment by cpuguy83** [comment] 2017-10-18 20:31
Can you please fill out the issue template?
Are you sure the nodes are not out of memory while this happens but not after when you are checking?

> Swarm Mode across 6 hosts - All of them are Managers. There are 0 worker nodes.

This is a non-ideal configuration.
The more managers you have the slower the cluster is.
Generally you'd want 3, 5, or 7 managers. Extra managers are just for HA, there's really only ever 1 active at a time.
With 6 managers you get no more availability than you do with 5 managers... basically both you can only lose 2 managers and still work.

**Comment by lukeescude** [comment] 2017-10-18 20:39
We’re setting up some monitoring programs to collect data during an incident to be able to answer that question.

You are correct about the configuration - the purpose of this is because there are 3 managers in 2 geographically separate data centers. So if an entire DC goes down, the remaining single datacenter can still operate autonomously.

**Comment by cpuguy83** [comment] 2017-10-18 20:42
In this case the cluster will go down because it requires a majority of manager nodes to be up. To survive a 3-node failure, you'd need at least 7 manager nodes.

**Comment by lukeescude** [comment] 2017-10-18 20:46
3 managers don’t make a majority? ( 2 + 1 )

**Comment by cpuguy83** [comment] 2017-10-18 20:50
Maybe I'm misunderstanding your architecture, 3 managers out of 6 is not a majority.

**Comment by lukeescude** [comment] 2017-10-18 20:53
No I misunderstood the technology, you are correct.

For some reason I thought that the swarm could still operate with a minimum of 3 managers. So if you had 100, you could lose 97 and it’ll be fine. I was wrong though, offline nodes are still considered part of the swarm, so 3 wouldn’t operate in a 6 manager swarm.

In any case, I’ll reply back with info about RAM once we have some more data to work with.

**Comment by lukeescude** [comment] 2017-10-18 22:17
We have confirmed the host is NOT running out of RAM.

In fact the most RAM usage that CentOS is logging is 2.8G, which is on par with normal operation.

Does "memory" mean something besides RAM/vmem in docker language? Maybe we're not looking in the right place.

**Comment by cpuguy83** [comment] 2017-10-18 23:31
No. This is not a message from Docker but the kernel.

**Comment by lukeescude** [comment] 2017-10-18 23:34
Is there any way for the kernel to "think" it is running out of RAM when it actually isn't? We have a ton of metrics from different places that show us there was no shortage of RAM whatsoever.

**Comment by lukeescude** [comment] 2017-10-18 23:35
Plus, this crash has occurred in both datacenters on two different managers, both running a slightly different version of CentOS.

**Comment by thaJeztah** [comment] 2017-10-30 20:53
Let me close this issue for now, as this looks like a support question, not a bug report. If you have more information, and suspect there's a bug at hand, please open a new issue with details as requested in the issue template.

**Closed by thaJeztah** 2017-10-30 20:53 UTC

**Comment by lukeescude** [comment] 2017-11-11 14:54
This crash happened again - The O/S thinks it is running out of memory when it isn't.

We've increase the maximum of file descriptors/files open, maximum amount of sockets, etc. but the lock-up still occurs.

Is Docker not able to failover if it senses a loss of memory? The other swarm managers think the worker node is perfectly fine (Reachable, Available) even though it's very much not reachable.
