### ISSUE TITLE
docker-compose push image to registry not work

### ISSUE THREAD

**Issue by eromoe** [moby/moby#35868] opened 2017-12-25 02:10 UTC
I have three nodes swarm cluster - host01,host02,host03. 
host01 is manager. 

Now I am in host01

## version

```
[root@host01 scripts]# docker -v                      
Docker version 17.09.0-ce, build afdb6d4              
[root@host01 scripts]# docker-compose -v              
docker-compose version 1.17.1, build 6d101fb          
```

## compose file `test.yml`:

    version: '3'                                           
    services:                                              
      mongo:                                               
        image: ${PRIVATE_REGISTRY}/basin/mongo:3.0.15      
        restart: always                                    
        ports:                                             
          - 11081:27017                                    
                                                           
      postgres:                                            
        image: ${PRIVATE_REGISTRY}/basin/postgres:10.1     
        restart: always                                    
        container_name: basin-postgres                               

## `${PRIVATE_REGISTRY}` :

I publish registry on 5006, not 5000 

    [root@host01 scripts]# echo ${PRIVATE_REGISTRY}    
    host01:5006                                        

## Docker images on host01:

    basin/postgres                    10.1                599272bf538f        5 weeks ago         287MB      
    basin/postgres                    latest              599272bf538f        5 weeks ago         287MB      
    host01:5006/basin/postgres        10.1                599272bf538f        5 weeks ago         287MB      
    host01:5006/basin/postgres        latest              599272bf538f        5 weeks ago         287MB      
    basin/mongo                       3.0.15              7312593938b8        7 weeks ago         233MB      
    basin/mongo                       latest              7312593938b8        7 weeks ago         233MB      
    host01:5006/basin/mongo           3.0.15              7312593938b8        7 weeks ago         233MB      
    host01:5006/basin/mongo           latest              7312593938b8        7 weeks ago         233MB      
    basin/redis                       3.2.11              d3f696a9f230        7 weeks ago         99.7MB     
    basin/redis                       latest              d3f696a9f230        7 weeks ago         99.7MB     
    host01:5006/basin/redis           3.2.11              d3f696a9f230        7 weeks ago         99.7MB     
    host01:5006/basin/redis           latest              d3f696a9f230        7 weeks ago         99.7MB     
    host01:5006/basin/registry        2.6.2               a07e3f32a779        7 weeks ago         33.3MB     
    host01:5006/basin/registry        latest              a07e3f32a779        7 weeks ago         33.3MB     
    basin/registry                    2.6.2               a07e3f32a779        7 weeks ago         33.3MB     
    basin/registry                    latest              a07e3f32a779        7 weeks ago         33.3MB

## `/etc/docker/daemon.json`:

    [root@host01 scripts]# cat /etc/docker/daemon.json                                          
    {"registry-mirrors": ["http://host01:5006"], "insecure-registries" : [ "host01:5006"] }     

------------

`docker-compose -f test.yml push` printed nothing, query registry showed nothing be pushed:

    [root@host01 scripts]# curl -X GET http://${PRIVATE_REGISTRY}/v2/_catalog    
    {"repositories":[]}                                                          

But `docker push ${PRIVATE_REGISTRY}/basin/mongo:3.0.15` worked.

**Comment by romankd** [comment] 2017-12-26 20:04
hi @eromoe.
Have you try to login into registry by command line before pushing/pulling?

Try to replace ${PRIVATE_REGISTRY} with native value (host01:5006 in your case) in test.yml for a sec and run command.

Especially i am not a huge fun of compose tool, but i think there's not the problem with docker-compose.

**Comment by eromoe** [comment] 2017-12-27 01:08
1. the registry doesn't require login.
2. from https://docs.docker.com/engine/swarm/stack-deploy/  , it shows an example use docker-compose push image to registry running in a swarm node. 
3. docker-compose should support environment variable.  If not , that's another problem.

4. Without environment variable, still not work: 

```
➜  test docker images |grep nginx
jojomi/nginx-static                        latest                         295d9bd6b0f4        7 weeks ago         5.33MB
10.142.55.199:5006/basin/nginx             latest                         05a60462f8ba        13 months ago       181MB
nginx                                      1.11.5                         05a60462f8ba        13 months ago       181MB
```

compose file:
```
version: '3'
services:
  nginx:
    image: 10.142.55.199:5006/basin/nginx
    restart: always
    ports:
      - 11081:27017
```

`docker-compose -f test.yml push` nothing happened .

**Comment by thaJeztah** [comment] 2017-12-27 12:18
The `docker-compose push` command makes the assumption that you're pushing an image you built using the docker-compose file; https://docs.docker.com/compose/reference/push/

> The following assumptions are made:
> - You are pushing an image you have built locally
> - You have access to the build key

However, your Docker Compose file does not include a `build` directive.

Adding a build-directive to your compose-file will make Docker Compose enable pushing the image; e.g.

```yaml
version: '3'
services:
  nginx:
    image: localhost:5000/foobar/nginx:alpine
    build: .
    restart: always
    ports:
      - 11081:27017
```


```bash
$ docker-compose -f test.yml push
Pushing mongo (localhost:5000/foobar/nginx:alpine)...
The push refers to repository [localhost:5000/foobar/nginx]
9d5813b1f32c: Pushed
8c03181dc28f: Pushed
d4ae73dd2312: Pushed
6bc5936494e3: Pushed
alpine: digest: sha256:94a3611e66493d5903843b98427977ee083bdc6d7c4bda8d56d460a7c67a29ed size: 1153
```

I'm closing this issue, because this is an issue for Docker Compose (which has its own issue tracker: https://github.com/docker/compose/issues), but it looks to be working as designed, but perhaps the documentation could mention this (you can open an issue or pull-request using the "edit this page" or " Request docs changes" links on each page in the documentation)

**Closed by thaJeztah** 2017-12-27 12:18 UTC
Labels: area/distribution
