### ISSUE TITLE
Containers created with mode:global don't have {{.Task.Slot}}

### ISSUE THREAD

**Issue by mostolog** [moby/moby#34658] opened 2017-08-29 09:03 UTC
**Description**

Containers created with _**mode:global**_ don't have **{{.Task.Slot}}**

**Steps to reproduce the issue:**
1. Create an stack containing a service with _**replicas: 3**_ and _**hostname: 'myservice-{{.Task.Slot}}'**_. Deploy it
2. docker service ps would print task names like:
    mystack_myservice.1.o6ax5ex63j24xb670wrkdw9la
    while container hostnames would be like "myservice-1"
---

1. Create an stack containing a service with _**mode:global**_ and _**hostname: 'myservice-{{.Task.Slot}}'**_. Deploy it
2. docker service ps would print task names like:
    mystack_myservice.o6ax5ex63j24xb670wrkdw9la  (notice it lacks ".1")
    while container hostnames would be like "myservice-"

**Describe the results you received:**

Container names when using _**mode:global**_ doesn't have {{.Task.Slot}}

**Describe the results you expected:**

Although is set to global, each container could have a {{.Task.Slot}}

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: o6ax5ex63j24xb670wrkdw9la
 Is Manager: true
 ClusterID: wa2ceofyt5ofwb5bdpqo17lml
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: REDACTED
 Manager Addresses:
REDACTED
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.851GiB
Name: REDACTED
ID: REDACTED
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2017-09-25 16:48
Correct; this was by design, but there's a discussion about changing that in https://github.com/docker/swarmkit/issues/1554.

Let me close this one to prevent the discussion from diverging; feel free to participate in  https://github.com/docker/swarmkit/issues/1554

**Closed by thaJeztah** 2017-09-25 16:48 UTC
Labels: area/swarm, version/17.06
