### ISSUE TITLE
Docker and Firewall - I can't do anything. Really.

### ISSUE THREAD

**Issue by ScottBu** [moby/moby#27913] opened 2016-10-31 20:06 UTC
**Description**

I was working with Docker and Docker Compose for months, on a project, everything was working perfectly. Now that I finally want to put this website in production, nothing is working :).

Well, docker and docker compose are working if I don't install / use ufw or iptables. If I want to secure my server, I have to use them. At the second I use them, my website is down. The ports used by my docker-compose containers are : 80 (website) 443(https portal) 3306 (database)
I'm connecting in SSH to my dedicated sever, the port 22 is open.

**Steps to reproduce the issue:**
1. Installed Ubuntu 16.04, apt-get update & upgrade
2. Installed Docker and Docker Compose, last versions.
3. Created a repository with my docker compose file, exactly like the one I was using previously. Ran it, no errors. Everything is running.
4. Made sure that ufw is installed. Opened 22 443 3306 80, even 8080 and/or 8000, tried a lot of ports to be honest. Disabled ufw aswell, didn't change anything.
5. Read on Google all the issues people had with ufw and docker, changed the line DEFAULT_FORWARD_POLICY = ACCEPT.
Also changed Docker's opts : --iptables=false
Then did a service docker restart

iptables -S still gives me some Docker options, shouldn't it be gone with my "--iptables=false"?

Let's sum up and write all the things I tried :
 
In all the cases below, have in mind that : 
My docker and docker compose  containers are working well without firewall rules. I can access my website.
When I enable ufw, it's the end. If, after this, even without having added rules on ufw, I disable ufw, nothing work. And even if I remove and purge ufw, it's not working anymore. I have to make a new fresh server, yaaay.

- ubuntu 16.04 fully updated and upgraded is installed
- docker and docker compose, last versions
- The containers are running. 

I tried in this order : 

Install Ubuntu and immediately install docker and compose. Change, immediately, the docker OPTS and restart docker service.
Then, configure ufw and enable it. 
Disable it. Website still down.

Install Ubuntu, configure ufw. Install Docker and Compose, run the containers.
Install Ubuntu, configure ufw. Install Docker and Compose, run the containers. Change Docker OPTS, change ufw default forward policy.

I really, really need your help, I've been working on it for hours, days, weeks. 

**Describe the results you received:**
Website unreachable. ERR_CONNECTION_REFUSED

**Describe the results you expected:**
A functionnal website ? 👍 

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.822 GiB
Name: GamersIndustry
ID: GCOK:3GO4:YCW7:NOOY:N6LK:3HHD:IPZ6:A6HO:BWTR:OWHZ:L4OL:3TV2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by LK4D4** [comment] 2016-10-31 20:08
ping @mrjana @aboch @sanimej 
I know for sure that docker works with firewalld. I think ufw still breaks everything :(

**Comment by aboch** [comment] 2016-10-31 21:09
@ScottBu 

> iptables -S still gives me some Docker options, shouldn't it be gone with my "--iptables=false"?

The rules you see are probably from previous docker run. You need to remove them manually.
Setting the flag to false tells docker not to touch the iptables (not even for cleaning).

BTW, you may not want to disable iptables, because they are used by docker to make you container accessible from the outside world. People who `--iptables=false` usually have other tools or they manually take care of configuring the iptables.

If you stop the ufw as a service `sudo service ufw stop` its iptables rules won't be removed.
Make sure to `sudo ufw disable` instead, which will clean up anything that was installed by ufw.

I believe one reason why you can't access your containers when ufw is on is because it changes the default policy for the `INPUT` chain to DROP.

docker iptables programming works with the implicit assumption that chain's policy is ACCEPT.

Can you try to start ufw and docker w/o touching the iptables flag and then change the default policy for the INPUT chain to ACCEPT, just to confirm

`sudo iptables -P INPUT ACCEPT`

**Comment by ScottBu** [comment] 2016-11-01 09:44
@aboch 

Hi Alessandro,

I tried to remove the rules and the chains Docker created (iptables -F <chainname> and then -X), with success, but didn't change anything.

Yes I was using ufw disable :)

I just reinstalled everything, created my containers and then immediately did an iptables -P INPUT ACCEPT.

Still not working...
I'm just super super desesperate right now :')

**Comment by ScottBu** [comment] 2016-11-01 11:24
@aboch 

Well, I quickly ordered a sever at DigitalOcean. Installed 14.04. Installed Docker and Compose, ran them.
Set UFW with 80 22 443 3306, enabled it. Not working, the rules weren't being used and all my ports were open. I then changed iptables to false. netstat -a : only 22 80 443 3306 are open. Perfect.
Tried to access the website : it works.

So... Let's try again with 16.04 64bits... Be right back.

**Comment by ScottBu** [comment] 2016-11-02 08:24
New problems arrived, now I have Apache errors... without using Apache.
I'm going to create another topic and I will come back here to write all the solutions.

**Comment by amitkumarj441** [comment] 2016-11-02 19:25
@ScottBu Actually we're focusing on the firewall rules of the "main bridge" itself, but it supports injecting firewall rules into the containers' network namespaces as well.
Below are some of the rules:
It can be specified in the following five categories:

- container_to_container
- container_to_wider_world
- container_to_host
- wider_world_to_container
- container_internals

**Comment by pascalandy** [comment] 2016-11-22 00:15
I'm having an [issue](https://github.com/docker/docker/issues/27513) as well and I don't know if it's related to UFW but the overlay network is killing me.

I'll try to start from scratch without installing UFW.

Here is the bash script that configures this part:

```
echo && echo -e "$PIK_BLUE Setup firewall (UFW) - checkpoint 207" && echo
echo "checkpoint 207 $(date +%Y-%m-%d_%Hh%Mm%S)" >> log-install.txt && echo
### sudo apt-get update -q
sudo apt-get install -y -q ufw --no-install-recommends
#
### Have a clean start with iptables
iptables -F; iptables -X
echo 'y' | ufw reset
echo 'y' | ufw enable
ufw default deny incoming
ufw default deny forward
#
### Allow traffic from given ethernet nic
#ufw allow in on docker0
#
### Allow traffic from trusted ip
#ufw allow from 52.74.151.55
#
### Web ports
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
#
### Swarm manager
sudo ufw allow 997/tcp
sudo ufw allow 2375/tcp
sudo ufw allow 2376/tcp
sudo ufw allow 2377/tcp
sudo ufw allow 3375/tcp
sudo ufw allow 3376/tcp
#
### Swarm nodes
sudo ufw allow 7946/tcp
sudo ufw allow 7946/udp
sudo ufw allow 4789/tcp
sudo ufw allow 4789/udp
#
### Needed by Swarm --opt encrypted. Need to ensure protocol 50 (ESP) is open. https://docs.docker.com/engine/swarm/swarm-tutorial/
# sudo ufw allow 50/tcp
#
### Needed by GlusterFS
# sudo ufw allow 24007/tcp
# sudo ufw allow 24008/tcp	
# sudo ufw allow 49152/tcp	# brick #1
# sudo ufw allow 49153/tcp	# brick #2
#
### Needed by Portainer
# sudo ufw allow 9000/tcp
#
### Needed by Traefik
sudo ufw allow 8080/tcp
#
### Activate UFW
sudo ufw show added
sudo ufw status verbose
sudo ufw --force enable
sudo ufw reload
```

**Comment by etouraille** [comment] 2017-07-07 06:21
my solution, wich is not really a solution was to use : 
      
    `--network=host`

Behind a firewall.

**Comment by akerouanton** [comment] 2023-07-11 08:50
Looks like this issue is a duplicate of the many other issues related to iptables and ufw. I recently created a discussion trying to reference all those issues, and summarizing the current situation and the path forward: https://github.com/moby/moby/discussions/45524.

Let me close this one in favor of the others.

**Closed by akerouanton** 2023-07-11 08:50 UTC
Labels: kind/question, area/networking, version/1.12
