### ISSUE TITLE
Docker pull / push and custom DNS

### ISSUE THREAD

**Issue by florentvaldelievre** [moby/moby#12347] opened 2015-04-13 21:45 UTC
I noticed we can use --dns=XXX with docker command.
However, it does not seem to work with docker pull and push

```
docker --dns=172.17.42.1 pull registry.service.consul
FATA[0000] Error: issecure: could not resolve "registry.service.consul": lookup registry.service.consul: no such host
```

dig lookup:

```
dig @172.17.42.1 registry.service.consul SRV +short
1 1 5000 registry2.node.staging.consul
```

Is it only working with container and docker run ?
Thanks!

**Comment by dmp42** [comment] 2015-04-13 22:31
IIRC `--dns` is a daemon option (not client).
So, restart your docker daemon using --dns. (https://docs.docker.com/reference/commandline/cli/#daemon-dns-options)

**Comment by ahmetalpbalkan** [comment] 2015-04-14 01:50
@dmp42 client binary does not have a `--dns` option. 

However if I use **the daemon binary as client** with `--dns`, such as:

    docker -H example.com:4243 --dns 8.8.8.8 ps

so from the `docker -h` output for both cli/daemon binaries, it's not clear to me in this case if `--dns` will be used for:
* all the containers in the daemon by default
* for pulling the images by the daemon
* resolving the hostname for `GET /containers/list` request (for `ps`).

I think it's a docs problem,

**Comment by florentvaldelievre** [comment] 2015-04-14 06:26
Thanks.
However, i also tried to add --dns to the daemon args:

Daemon args
````
other_args="--dns 172.17.42.1 --insecure-registry registry.service.consul -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"

````
Restarted docker

Problem persists
````
docker pull registry.service.consul/xxx
FATA[0000] Error: issecure: could not resolve "registry.service.consul": lookup registry.service.consul: no such host

````

It seems to be only a container option. As @ahmetalpbalkan the doc is not really clear about it.

**Comment by gdm85** [comment] 2015-04-16 07:23
I think at some version Docker started using its own DNS (or maybe Go's?), because it's also ignoring overrides in ``/etc/hosts``

**Comment by wildsurfer** [comment] 2015-05-31 22:40
I have the same issue. Steps to reproduce (you will need docker-machine >= 1.3):

Let's imagine one server with `distribution` (ex. registry) and `dnsmasq` containers

```bash
$ docker-machine create -d virtualbox instrumental
$ eval "$(docker-machine env instrumental)"
$ docker run -d -it -p "5000:5000" registry:2.0
$ docker pull hello-world
$ docker tag hello-world localhost:5000/hello
$ docker push localhost:5000/hello
$ docker run -d -it -p "53:53/tcp" -p "53:53/udp" --cap-add=NET_ADMIN --add-host instrumental:$(docker-machine ip instrumental) andyshinn/dnsmasq
```

And now let's imagine other server that will use images from the first server.

```bash
$ docker-machine create -d virtualbox --engine-insecure-registry instrumental:5000 --engine-opt dns=$(docker-machine ip instrumental) webserver
```

Now let's try to pull the images

This will work:

```bash
$ eval "$(docker-machine env webserver)"
$ docker run -it busybox ping instrumental
```

While this **won't work**:

```bash
$ eval "$(docker-machine env webserver)"
$ docker pull instrumental:5000/hello
```

**Comment by sparkycrisse** [comment] 2015-06-16 11:31
Also experiencing issues with `docker push` using a hostname

Deamon arguments:
```
other_args=" --insecure-registry registry.server.com --insecure-registry <server ip>"
```

**This works:**
```
docker push <server ip>/express
```
**This gives an error:**
```
docker push registry.server.com/express
```
```
FATA[0030] Error response from daemon: v1 ping attempt failed with error: Get http://registry.server.com/v1/_ping: dial tcp: i/o timeout
```

**Comment by h0tbird** [comment] 2015-06-22 11:13
I am running on CentOS 7. This is my docker package:
```
[root@kvm-1 ~]# rpm -qa | grep docker-1
docker-1.6.0-11.0.1.el7.centos.x86_64
```
Which contains this Docker version:
```
[root@kvm-1 ~]# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64
```

I also have a custom DNS and a clean `/etc/hosts`:
```
[root@kvm-1 ~]# dig regi01 +short
172.20.3.176
[root@kvm-1 ~]# grep regi01 /etc/hosts
```

But docker is unable to resolve `regi01` when I push an image:
```
[root@kvm-1 ~]# docker push regi01:5000/zookeeper:latest
FATA[0002] Error response from daemon: v1 ping attempt failed with error: Get http://regi01:5000/v1/_ping: dial tcp: lookup regi01: no such host
```

On the other hand if I add a record to `/etc/hosts`:
```
[root@kvm-1 ~]# grep regi01 /etc/hosts
172.20.3.176 regi01
```

I am able to push images:
```
[root@kvm-1 ~]# docker push regi01:5000/zookeeper:latest
The push refers to a repository [regi01:5000/zookeeper] (len: 1)
Sending image list
Pushing repository regi01:5000/zookeeper (1 tags)
Image 9a235a4a6077 already pushed, skipping
Image 3715dde89228 already pushed, skipping
Image 41459f052977 already pushed, skipping
Image 6941bfcbbfca already pushed, skipping
Image d952e08d604e already pushed, skipping
Image c8723c614ba4 already pushed, skipping
Image c475b7709882 already pushed, skipping
Image fd44297e2ddb already pushed, skipping
Image 98e02b481865 already pushed, skipping
Image a0a347441ceb already pushed, skipping
Image 1f4a59fe655a already pushed, skipping
Image f1ad705612e7 already pushed, skipping
Pushing tag for rev [f1ad705612e7] on {http://regi01:5000/v1/repositories/zookeeper/tags/latest}
```

**Comment by magicrobotmonkey** [comment] 2015-12-02 14:27
I have a similar issue using mesos-dns and bind. My registries record is in bind. If I'm using my bind server directly in /etc/resolv.conf, docker can pull from my registry. If I use my bind server as a resolver for mesos-dns with mesos-dns in /etc/resolv.conf, everthing (dig, host, curl, etc)  _except_ docker can resolve my registry. It seems the docker daemons dns resolver is either very strict or broken.

**Comment by BenHall** [comment] 2016-02-07 00:17
I found that the Docker daemon needs to be rebooted before it will refresh it's hosts entries

**Comment by klausenbusk** [comment] 2016-03-07 23:15
Workaround `docker run --rm --dns 1.2.3.4 -v /var/run/docker.sock:/var/run/docker.sock docker pull foo.bar:bar`

**Comment by xdqyzy** [comment] 2016-04-13 20:25
For "no such host" issue, there might be issues in glibc before 2.20. If the Go program compiles statically against glibc or dynamically uses the bad glibc on the host, it will hit the issue.

https://github.com/golang/go/issues/3575
https://github.com/golang/go/issues/6336

**Comment by vperron** [comment] 2016-12-14 06:06
Agreed with @BenHall , restarting it makes it magically refresh the host entries.

**Comment by thaJeztah** [comment] 2023-09-16 16:29
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 16:29 UTC
Labels: area/distribution, kind/enhancement
