### ISSUE TITLE
Error response from daemon: open /var/lib/docker/tmp/docker-import-537484462/repo/.cpt_hardlink_dir_a920e4ddc233afddc9fb53d26c392319/json: no such file or directory

### ISSUE THREAD

**Issue by aillamsun** [moby/moby#19566] opened 2016-01-22 01:36 UTC
hi:
docker load < centos-7-x86_64-minimal.tar.gz

Response:Error response from daemon: open /var/lib/docker/tmp/docker-import-537484462/repo/.cpt_hardlink_dir_a920e4ddc233afddc9fb53d26c392319/json: no such file or directory

1,docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

2,docker info
Containers: 7
Images: 48
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-100825310-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.053 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.585 GB
 Metadata Space Used: 3.998 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.4.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.782 GiB
Name: master
ID: TYKI:7PMB:6GJV:QNJC:VVKI:NUIP:B6O4:LC6R:4MMB:WMEY:XAWW:DQPF
Username: sungang1120
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

3,uname -a

**Comment by HackToday** [comment] 2016-01-22 05:08
I think docker not support all kinds of tar.gz to be loaded. it need to meet related specification to be able to loaded.

Maybe @thaJeztah  know something about it.

**Comment by thaJeztah** [comment] 2016-01-22 21:14
This looks like a duplicate of https://github.com/docker/docker/issues/14870, can you check if that looks the same to you @sungang1120 ?

**Comment by clnperez** [comment] 2017-03-07 19:54
We ran into this trying to import some ppc64le images, and to get around it you can build a docker image and just add in the tarball:

```
FROM scratch
MAINTAINER <YOUR NAME>
ADD CentOS-7-ppc64le-rootfs-1611.tar.xz /
...
```
If I get some time I'll try to dig into this an confirm whether it was caused by symlinks. FYI, one of the images we saw it with is this one: http://download.opensuse.org/repositories/Virtualization:/containers:/images:/openSUSE-Tumbleweed/images/openSUSE-Tumbleweed-docker-guest-docker.ppc64le.tar.xz

**Comment by ivanperez-keera** [comment] 2017-03-26 14:15
Could it be the case that you are trying to _load_ a container, instead of _importing_ it? (I know it sounds silly, but I've made that mistake in the past and the error message very similar.)

**Comment by FreeWebber** [comment] 2017-04-21 16:21
Similar get
open /var/lib/docker/tmp/docker-import-115099829/bin/json: no such file or directory

When i done
sudo docker load < /home/lamp.tar.gz

Instad of:
zcat /home/lamp.tar.gz | sudo docker import - lampc

**Comment by danielpereira90** [comment] 2017-06-12 02:48
I've got a similar error and fixed it by creating the `tmp` folder inside `/var/lib/docker/`, which didn't exist

**Comment by johnnythecakes** [comment] 2017-06-13 18:32
fixed it for me thanks @danielpereira90

**Comment by dove-young** [comment] 2017-06-29 08:30
I've got similar problem at <code>Docker CE v17</code>

Create dir <code>/var/lib/docker/tmp/</code> does not work for me. Because the directory is there. 

```
[root@cfc-k8s-20 k8smon]# docker load -i k8smon0629.tar.gz
02658b5e0e10: Loading layer [==================================================>] 123.2 MB/123.2 MB
5a70b1a02339: Loading layer [==================================================>] 15.87 kB/15.87 kB
0f89582aebaa: Loading layer [==================================================>] 11.78 kB/11.78 kB
ffa5309fe008: Loading layer [==================================================>] 5.632 kB/5.632 kB
7510bd34aee9: Loading layer [==================================================>] 3.072 kB/3.072 kB
dc8dd8718e57: Loading layer [==================================================>] 1.024 kB/1.024 kB
30f272ac09a4: Loading layer [==================================================>] 38.57 MB/38.57 MB
6a9c247b9633: Loading layer [==================================================>] 283.8 MB/283.8 MB
2469d1ff66a5: Loading layer [==================================================>] 10.24 kB/10.24 kB
d19264579b0d: Loading layer [==================================================>] 8.637 MB/8.637 MB
7c3d696ba358: Loading layer [==================================================>] 3.889 MB/3.889 MB
1605e8895a2b: Loading layer [==================================================>] 492.5 kB/492.5 kB
6717b6cce541: Loading layer [==================================================>] 4.378 MB/4.378 MB
196ab0be9d91: Loading layer [==================================================>] 3.491 MB/3.491 MB
4740bf8b6140: Loading layer [==================================================>] 17.97 MB/17.97 MB
a04835fcb358: Loading layer [==================================================>] 905.7 kB/905.7 kB
b38daf022f86: Loading layer [==================================================>]  76.8 kB/76.8 kB
1b6437c4f9e0: Loading layer [==================================================>] 1.536 kB/1.536 kB
68e17e3eef9b: Loading layer [==================================================>] 46.08 kB/46.08 kB
9c498bc10db6: Loading layer [==================================================>] 3.072 kB/3.072 kB
5be19bb2ac22: Loading layer [==================================================>] 1.024 kB/1.024 kB
b3a78e34b025: Loading layer [==================================================>] 1.024 kB/1.024 kB
open /var/lib/docker/tmp/docker-import-590600475/repositories: no such file or directory
[root@cfc-k8s-20 k8smon]# ls /var/lib/docker/tmp/
[root@cfc-k8s-20 k8smon]#

[root@cfc-k8s-20 k8smon]# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@cfc-k8s-20 k8smon]#
```

**Comment by thaJeztah** [comment] 2017-06-30 01:43
open /var/lib/docker/tmp/docker-import-590600475/repositories: no such file or directory

@dove-young this may be if the archive is in the wrong format (e.g. trying to _import_ an archive that was created with `docker save`)

**Comment by helinwang** [comment] 2017-07-20 21:13
I got similar error: `open /var/lib/docker/tmp/docker-import-347673752/bin/json: no such file or directory`. Because I ran `docker load`, trying to import the output of `docker export`.
The correct way is to run `docker import` for the output of `docker export`. (`docker load` is for the output of `docker save`).
Better error message from docker would be more helpful.

**Comment by thaJeztah** [comment] 2017-07-20 21:46
> Better error message from docker would be more helpful.

We tried implementing that, but the only way to do so would be to extract/analyse the archive _twice_ (once to validate, once to perform the actual `docker load` / `docker import`). This resulted in way too much overhead, so was decided it was not worth doing (given that it would be addressing a user error, not a bug)

**Comment by thaJeztah** [comment] 2017-07-20 21:48
Following the discussion above, I think all cases reported here are due to using the wrong type of archive (mixing `docker save` / `docker load` with `docker export` / `docker import`). I'm closing this issue for that reason, as there's nothing actionable.

**Closed by thaJeztah** 2017-07-20 21:48 UTC
Labels: version/1.9

**Comment by parthaajayreddy** [comment] 2018-03-26 20:15
I separated the Base image layer from container image to optimize the image size and I am getting the below error 👍 
"open /var/lib/docker/tmp/docker-import-538518151/repositories: no such file or directory"

I used docker save to create tar file and docker load to extract the image from tar file.

**Comment by venuslowiu** [comment] 2018-04-09 01:44
Yes.
`docker import` is for the output of `docker export` 
`docker load` is for the output of` docker save`

**Comment by Yukippe** [comment] 2018-05-17 01:54
I got similar error. most of the time because image is damaged

**Comment by doudoubilly** [comment] 2018-05-27 01:54
@thaJeztah But I use docker save / docker load and get such result
"open /var/lib/docker/tmp/docker-import-451484639/repositories: no such file or directory"

**Comment by sonasingh46** [comment] 2018-05-28 19:31
@thaJeztah 
1. use `docker save -o [anyname.tar] [example/image:exampletag] `  
2. then `sudo scp anyname.tar docker@minikubeIP:/home/docker` (default password is `tcuser`)
3. then `minikube ssh`
4. then `cd /home/docker`
5. then `chmod 777 anyname.tar`
6 then `docker load -i anyname.tar`
It needs permission, so give it. It might help. ( If any command gives permission denied , use `sudo`)

**Comment by 15708432809** [comment] 2018-08-16 08:27
efvbsfbsbsvfsv

**Comment by eaglefinds** [comment] 2018-09-17 20:34
thank you load / import are two different things , it works how you created tar.

**Comment by SUYEgit** [comment] 2018-09-21 02:38
I believe this is due to docker installation. Try ```sudo docker run helloworld```first.

**Comment by ucookie** [comment] 2018-10-17 11:46
maybe you should check your "save machine" dcoker version, and your "load machine" docker version.
if they are matched

**Comment by paigeadelethompson** [comment] 2019-02-28 07:13
but I would really like to just load my tar file if thats ok ... fucks sake why do you need two save and export when you could just have one!

**Comment by paigeadelethompson** [comment] 2019-02-28 07:22
For anybody who is really disappointed like me all you need to do is create an empty .dockerenv file and and add it to your archive then docker import it.

**Comment by thaJeztah** [comment] 2019-02-28 10:54
> why do you need two save and export when you could just have one!

They're doing different things; `docker export` (or `docker container export`) exports a _container_ to a tarball, whereas `docker save` (or `docker image save`) exports an _image_.

**Comment by paigeadelethompson** [comment] 2019-02-28 11:10
..... yes I understand, and just to reiterate:
- made a tarball of very specific files, third text box down (
https://github.com/paigeadelethompson/netcrave_dockerfiles/blob/master/README.md#exporting-applicationsservices-and-their-runtime-dependencies
)
- I was able to docker import that tarball whereas I was not able to
without including the `.dockerenv` file
- assuming I can rely on this behavior I'm going to continue to use it in
order to build my skinny containers with fat binaries (the next phase in
this plan)

**Comment by Wang-Kai** [comment] 2019-04-10 02:10
> I've got a similar error and fixed it by creating the `tmp` folder inside `/var/lib/docker/`, which didn't exist

Hi @denieus  How do you change `tmp` inside `/var/lib/docker`?

**Comment by CGavrila** [comment] 2019-06-26 11:08
I have also had a similar issue because my image was of size 0B. I created the image using `docker save`, which did not complain that it does not exist.

**Comment by lflucasferreira** [comment] 2019-12-20 23:07
Just do the following:
**$ docker volume rm jenkins-data**

**Comment by ANASZAH** [comment] 2020-02-07 13:16
I ran md5 checksums on the images before and after I moved them across systems and they were different because i didn't have enough disk space.
Check only size.
or check use this cmd: `md5sum image.tar`
or check disk space: `df -h`

**Comment by fiantsev** [comment] 2020-08-20 09:05
in my case the problem was with copying tar archive from host Windows 10 machine into Hyper VM Ubuntu 18.04 (via Ctrl+C-> Ctrl-V of Enhanced session). The duplicated tar had wrong md5sum - so the mechanism seems broken. Finally i copied files between host and VM using rsync command in WSL. thanks @Anas-ZAHOURI for the tip

**Comment by battalcevik** [comment] 2020-11-20 08:41
Try restarting docker, it worked for me 

sudo service docker stop
sudo service docker start

**Comment by clark-cui** [comment] 2021-02-04 07:29
> I've got a similar error and fixed it by creating the `tmp` folder inside `/var/lib/docker/`, which didn't exist

thanks bro.It did work

**Comment by asechnaya** [comment] 2021-03-19 23:05
I have got a similar error.
In my case, I failed with end dir. It should be not "the_folder", but "/home/folder/the_folder"

**Comment by OtenMoten** [comment] 2021-08-11 13:08
> I've got a similar error and fixed it by creating the `tmp` folder inside `/var/lib/docker/`, which didn't exist

Works for me. But after I created the `tmp` directory I run into another error `ERROR: failed to register layer: symlink` which I solved with the help of [this guy here](https://stackoverflow.com/questions/44942790/docker-error-failed-to-register-layer-symlink).

**Comment by sfalihi** [comment] 2021-09-10 11:32
> there is a lot of reason. for my case i ran md5 checksums on the images before and after I moved them across systems and they were different because i didn't have enough disk space.
> 
> check sizes.
> or check use this cmd: `md5sum image.tar`
> or check disk space: `df -h`

Worked for me.
there was a problem transfering file from local to server.
what i did, was to first "zip" saved image and then transfer, unzip and load it on the server.

**Comment by ibrandiay** [comment] 2021-11-19 14:19
In my case, there was some missing data, it is solved by grouping all the rar files in a directory and using unrar x your_file.rar to extract them (docker hikvision image)

**Comment by Duoquote** [comment] 2022-12-12 12:27
In my case I used `gzip -d file.tar.gz | docker load` command which is pretty much invalid as the command extracts contents into `file.tar` returning an empty output to stdin, the command should have been `gzip -d file.tar.gz && docker load -i file.tar`.

**Comment by nagyzsolthun** [comment] 2023-02-23 17:40
After trying everything and more, I realized that the root-cause for me was copying the image to a drive without free space left :facepalm: 
```
scp image.tgz  pi@rpi.local:/media/usb/
image.tgz
cp: /media/usb//image.tgz: No space left on device
image.tgz        
```
This error message is very misleading.

**Comment by agowa** [comment] 2024-06-11 09:00
This error also occurs if the tar.gz file contains another tar file, I.E. if the file is tared twice and then gzip-ed.
