### ISSUE TITLE
Mounted volume lost its contents

### ISSUE THREAD

**Issue by tpyle** [moby/moby#43076] opened 2021-12-10 23:22 UTC
**Description**

We have a docker container which mounts a local directory into it, which contains a few files. This directory suddenly lost all of it contents, which caused the container to run into bugs. The host directory, however, still contains all files as expected.

Here is the relevant mount from docker inspect:
```json
{
    "Type": "bind",
    "Source": "/opt/xxxxxxxxxxx/nginx/auth",
    "Destination": "/etc/nginx/auth",
    "Mode": "rw",
    "RW": true,
    "Propagation": "rprivate"
}
```

Here are the directory contents from the host system:
```
$ ls -l nginx/auth/
total 32
-rw-r--r--. 1 smartlensuser smartlens    43 Apr 21  2021 admin.pwd
-rw-r--r--. 1 smartlensuser smartlens    94 Apr 21  2021 develop.pwd
-rw-r--r--. 1 smartlensuser smartlens   189 Apr 21  2021 external.pwd
-rw-r--r--. 1 smartlensuser smartlens 11931 Dec 10 09:24 nginx
-rw-r--r--. 1 smartlensuser smartlens    92 Apr 21  2021 support.pwd
-rw-r--r--. 1 smartlensuser smartlens   140 Apr 21  2021 system.pwd
```

Here are the directory contents from inside the container:
```
$ docker exec -it 10201d709c27 ls -l /etc/nginx/auth
total 0
```

Interestingly, if I run `df` on the container path, I get the correct filesystem, but from inside the directory I get the wrong one:
```
$ docker exec -it 10201d709c27 df /etc/nginx/auth
Filesystem              1K-blocks  Used Available Use% Mounted on
/dev/mapper/centos-root  10475520 71388  10404132   1% /etc/nginx/auth
```
```
root@10201d709c27:/etc/nginx/auth# df .
Filesystem              1K-blocks  Used Available Use% Mounted on
/dev/mapper/centos-root  10475520 71388  10404132   1% /etc/pki/nginx/core.crt
```

**Steps to reproduce the issue:**
I haven't been able to reliably reproduce this, although it has happened more than once. I have left the environment as is to provide details about it

**Describe the results you received:**
The mounted directory is empty

**Describe the results you expected:**
The mounted directory contains the files from the host system as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:32:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
 Images: 20
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.21.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.48GiB
 Name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is running inside of a HyperV Virtual Machine (CentOS 7.9)

**Comment by thaJeztah** [comment] 2022-01-11 11:39
Does the container have other mounts? e.g., could it be the container has a mount for `/etc/nginx` and that mount masked the nested (`/etc/nginx/auth`) mount?

Is it possible something on the host interacted with the `/opt/xxxxxxxxxxx/nginx/auth` path? (Bind-)mounts will be tied to the file descriptor when they're mounted, which means that, e.g. if the `/opt/xxxxxxxxxxx/nginx/auth` was empty at time the container was started, but replaced with a directory with content, then the container could still reference the "old" directory.

**Comment by tpyle** [comment] 2022-01-19 16:00
The container does have other mounts, although none located along the relevant mount path.

The directory wouldn't have been empty at the time that the container was created - I suppose its possible that it was replaced, would that result in this behavior?

**Comment by sam-thibault** [comment] 2022-12-08 11:43
Since I don't see steps to reproduce this and there are lots of factors involved here, I will close this for now.  If there is a straightforward repro case please add a comment and we can investigate further.  (Or if we see more people running into this issue)

**Closed by sam-thibault** 2022-12-08 11:43 UTC
Labels: status/more-info-needed
