### ISSUE TITLE
docker: Issues with Post-installation steps for Linux 

### ISSUE THREAD

**Issue by SyedShaQutub** [moby/moby#36981] opened 2018-05-02 07:35 UTC
Need to change the configurations of docker/daemon.json as stated in the website : https://docs.docker.com/install/linux/linux-postinstall/#upstart

but I'm not able to access this. console says permission denied !!

**Comment by thaJeztah** [comment] 2018-05-02 15:47
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-05-02 15:47 UTC
