### ISSUE TITLE
Docker daemon hangs when `docker kill` is stuck

### ISSUE THREAD

**Issue by richardpen** [moby/moby#32542] opened 2017-04-11 23:22 UTC
**Description**
Docker daemon hangs when `docker kill` is stuck.

**Steps to reproduce the issue:**
No solid steps to reproduce

**Describe the results you received:**
Docker ps, docker inspect, docker stop apis are all stuck.

**Describe the results you expected:**
Docker api calls should run independently and normally without being blocked for a long time by each other.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Related docker stack trace:

Go routine of docker kill which was stuck for 5652 minutes and it's holding the [container lock](https://github.com/docker/docker/blob/v1.12.6/daemon/kill.go#L59):
```
goroutine 29078374 [select, 5652 minutes]:
google.golang.org/grpc/transport.(*Stream).Header(0xc820f0a7e0, 0xc820f0a7e0, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/vendor/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7fbb72f03310, 0x2aa78a0, 0x0, 0x0, 0x0, 0x0, 0x7fbb72f03348, 0xc820419b20, 0x7fbb72f03370, 0xc820419b40, ...)
    /builddir/build/BUILD/docker-1.12.6/vendor/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7fbb72eb90b8, 0xc82000e6c8, 0x1e82790, 0x11, 0x1b565c0, 0xc8216e9d40, 0x1b56700, 0x2aa78a0, 0xc8203cb080, 0x0, ...)
    /builddir/build/BUILD/docker-1.12.6/vendor/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/docker/containerd/api/grpc/types.(*aPIClient).Signal(0xc820020230, 0x7fbb72eb90b8, 0xc82000e6c8, 0xc8216e9d40, 0x0, 0x0, 0x0, 0x440735, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/vendor/src/github.com/docker/containerd/api/grpc/types/api.pb.go:945 +0xec
github.com/docker/docker/libcontainerd.(*client).Signal(0xc820058ea0, 0xc82153cb80, 0x40, 0x9, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/libcontainerd/client_linux.go:209 +0x19c
github.com/docker/docker/daemon.(*Daemon).kill(0xc82015e820, 0xc8217cb680, 0x9, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/daemon/kill.go:156 +0x7c
github.com/docker/docker/daemon.(*Daemon).killWithSignal(0xc82015e820, 0xc8217cb680, 0x9, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/daemon/kill.go:84 +0x491
github.com/docker/docker/daemon.(*Daemon).killPossiblyDeadProcess(0xc82015e820, 0xc8217cb680, 0x9, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/daemon/kill.go:146 +0x5c
github.com/docker/docker/daemon.(*Daemon).Kill(0xc82015e820, 0xc8217cb680, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/daemon/kill.go:109 +0x109
github.com/docker/docker/daemon.(*Daemon).containerStop(0xc82015e820, 0xc8217cb680, 0x1e, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/daemon/stop.go:59 +0x49f
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc82015e820, 0xc82133aa27, 0x40, 0x1e, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/daemon/stop.go:28 +0x2bf
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop(0xc82013c5c0, 0x7fbb72f03610, 0xc821575f80, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0, 0xc821575d70, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/router/container/container_routes.go:168 +0x18b
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm(0x7fbb72f03610, 0xc821575f80, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0, 0xc821575d70, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/router/container/container.go:61 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7fbb72f03610, 0xc821575f80, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0, 0xc821575d70, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7fbb72f03610, 0xc821575f20, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0, 0xc821575d70, 0x0, 0x0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc82096a580, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0)
    /usr/lib/golang/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82013e5f0, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0)
    /builddir/build/BUILD/docker-1.12.6/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820abd6e0, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0)
    /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82005b980, 0x7fbb72e8b490, 0xc82316a1a0, 0xc8231e30a0)
    /usr/lib/golang/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820c1ee00)
    /usr/lib/golang/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/lib/golang/src/net/http/server.go:2137 +0x44e
```

There are lots of goroutines was blocked in state.go line [177](https://github.com/docker/docker/blob/v1.12.6/container/state.go#L177):
```
goroutine 29078460 [semacquire, 5652 minutes]:
sync.runtime_Semacquire(0xc821d68464)
        /usr/lib/golang/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc821d68460)
        /usr/lib/golang/src/sync/mutex.go:83 +0x1c4
github.com/docker/docker/container.(*State).IsRunning(0xc821d68460, 0xc8212240f7)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/container/state.go:177 +0x28
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc82015e820, 0xc8212240f7, 0x40, 0x1e, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/daemon/stop.go:24 +0xa8
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop(0xc82013c5c0, 0x7fbb72f03610, 0xc820e38960, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0, 0xc820e38810, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/router/container/container_routes.go:168 +0x18b
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm(0x7fbb72f03610, 0xc820e38960, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0, 0xc820e38810, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/router/container/container.go:61 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7fbb72f03610, 0xc820e38960, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0, 0xc820e38810, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7fbb72f03610, 0xc820e38930, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0, 0xc820e38810, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc82096a580, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0)
        /usr/lib/golang/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82013e5f0, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0)
        /builddir/build/BUILD/docker-1.12.6/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820abd6e0, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0)
        /builddir/build/BUILD/docker-1.12.6/_build/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82005b980, 0x7fbb72e8b490, 0xc820e23c70, 0xc820f137a0)
        /usr/lib/golang/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc821c9f880)
        /usr/lib/golang/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:2137 +0x44e
```

**Comment by danielqsj** [comment] 2017-04-14 09:50
+1

**Comment by vdemeester** [comment] 2017-04-14 09:55
@richardpen how did you install docker ? wihch disto, version, … ? (a `docker info` would be neat too, to know which storage driver were used, etc..)

Asking that because the output version doesn't look like the output from docker official binaries — the `Git Commit` part is not the same, probably meaning the docker version you are running contains unofficial patches.

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

```

**Comment by danielqsj** [comment] 2017-04-14 09:58
@vdemeester My environment is:
`[root@enn-yc-16 ~]# docker info
Containers: 45
 Running: 26
 Paused: 0
 Stopped: 19
Images: 79
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 35.98 GB
 Data Space Total: 950.2 GB
 Data Space Available: 914.2 GB
 Metadata Space Used: 11.67 MB
 Metadata Space Total: 9.999 GB
 Metadata Space Available: 9.988 GB
 Thin Pool Minimum Free Space: 95.02 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 3
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.4 GiB
Name: enn-yc-16
ID: OJBG:VT6A:DE2F:OQEU:O62B:YSQI:WFNN:UWZC:RQR3:AAPY:EED7:VOHQ
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled`

**Comment by danielqsj** [comment] 2017-04-14 10:04
@richardpen How do you get the goroutine stack trace?

**Comment by richardpen** [comment] 2017-04-14 23:02
@vdemeester This is running on [Amazon ECS Optimized AMI](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html) with docker 1.12.6
```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 58.72 MB
 Data Space Total: 9.437 GB
 Data Space Available: 9.378 GB
 Metadata Space Used: 69.63 kB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 25.1 MB
 Thin Pool Minimum Free Space: 943.7 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.1.13-19.30.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.308 GiB
Name: ip-172-31-25-109
ID: IISF:NZAK:EVJP:25X4:XUJ6:UI7J:WOXH:7EOX:N4KK:5M2M:HBSV:G6C3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
There is some patches applied to the official docker, but I don't think it existed in the code path reported above, you can get the srpm of the patched docker by running:
`docker run -v $(pwd):/rpm amazonlinux bash -c "cd /rpm; yum -y install docker; echo yes | get_reference_source -p docker  ; mv /usr/src/srpm/debug/docker* /rpm"`

@danielqsj You can get the stack trace of the daemon by sending the `SIGUSR` signal to Docker daemon, see document [here](https://docs.docker.com/engine/admin/#force-a-full-stack-trace-to-be-logged).

**Comment by comcast-david** [comment] 2017-07-03 13:20
+1

I was running a container that runs `fio` for exactly ten minutes with a relatively modest workload, then quits.  it was exercising the local overlay fs, not any attached volumes.  ~36 hours ago, the container "hung" after 9m4s of execution.

After running `docker kill` to stop the container, the daemon hung.  the container process was not running in a `ps aux` performed after running docker kill.  not sure whether the container was up or not prior to that.

```
$ docker info
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.9.16-coreos-r1
Operating System: Container Linux by CoreOS 1298.7.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.9 GiB
Name: dev-syseng-10-54-213-153
ID: M5VZ:27N4:UOBR:HPYR:MRQT:QK3C:6MLG:K64I:GUFN:P6DI:6R6G:3EEZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

interesting goroutines, based on the timing.  16 minutes is my `docker kill` command, and 2204 minutes are around the time my container locked up.

```
$ cat docker.log | grep minutes | grep -v ' 1 '
goroutine 47 [chan receive, 16 minutes]:
goroutine 474 [semacquire, 2204 minutes]:
goroutine 9590609 [semacquire, 2204 minutes]:
goroutine 1695704 [semacquire, 2204 minutes]:
```


```
goroutine 47 [chan receive, 16 minutes]:
github.com/docker/docker/pkg/signal.Trap.func1(0xc820386180, 0xc82023c000)
    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.12.6/work/docker-1.12.6/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:32 +0x71
created by github.com/docker/docker/pkg/signal.Trap

    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.12.6/work/docker-1.12.6/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:62 +0x2be


goroutine 474 [semacquire, 2204 minutes]:
sync.runtime_Syncsemacquire(0xc8213df850)
    /usr/lib/go1.6/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc8213df840)
    /usr/lib/go1.6/src/sync/cond.go:63 +0x9b
github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc8213df800, 0xc820ce9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.12.6/work/docker-1.12.6/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:134 +0xf7
bufio.(*Reader).fill(0xc821021ed0)
    /usr/lib/go1.6/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc821021ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go1.6/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadBytes(0xc821021ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go1.6/src/bufio/bufio.go:406 +0xa9
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc8213df880, 0x1dc3180, 0x6, 0x7fb5f3a20168, 0xc8213df800)
    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.12.6/work/docker-1.12.6/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:50 +0x14a
created by github.com/docker/docker/daemon/logger.(*Copier).Run
    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.12.6/work/docker-1.12.6/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:37 +0x12b

```
[docker.txt](https://github.com/moby/moby/files/1119642/docker.txt)

**Comment by thaJeztah** [comment] 2017-07-10 01:09
ping @fabiokung @cpuguy83 should this issue be resolved by the upcoming improvements in 17.07 ?

**Comment by cpuguy83** [comment] 2017-07-10 13:46
@comcast-david I do not think this is the goroutine that causing the blockage.
Do you have the full stack trace?

**Comment by cpuguy83** [comment] 2017-07-10 13:59
@comcast-david Scratch that, I see you pasted it at the bottom of your post.
This looks like a different issue in containerd.

I would of course also recommend upgrading to at least 17.03, the issue is *likely* fixed there, and there are now new patches coming for 1.12.
Ping @mlaventure, have you seen a stack trace like one from @comcast-david? Looks like a deadlock in the API client.

**Comment by mlaventure** [comment] 2017-07-11 10:08
I haven't seen a similar stack trace before. I don't seem to be able to pinpoint the thread hanging onto the lock in it. But it seems that the beginning of the stack is missing, so it's possible it was shown in that section.

**Comment by msavlani** [comment] 2017-11-16 19:47
@comcast-david  Was this resolved after upgrading to 17.03 ?
How did you fix or workaround this problem ?

**Comment by euank** [comment] 2018-04-12 19:48
I believe that this issue, based on the stack trace in the original post, is a duplicate of #35825. Per my comment there, I think this should be fixed in recent docker-ce versions.

**Comment by thaJeztah** [comment] 2018-04-12 22:48
Let me go ahead and close this, thanks all!

**Closed by thaJeztah** 2018-04-12 22:48 UTC
Labels: status/more-info-needed, version/1.12
