### ISSUE TITLE
Synchronous (interactive) docker stack deploy 

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#32367] opened 2017-04-05 01:42 UTC
Since we now do support synchronous and interactive service creation using `-d=false` (added in #31144), we should probably support the same in docker stack deploy.

The output would be slightly different:
While for services we should the progress of every single task, for stacks we'd display the overall progress of each service.

/cc @aaronlehmann @dnephin @vieux

**Comment by sirlatrom** [comment] 2017-05-16 20:40
I recall someone in the #swarm Slack channel mentioned `docker stack rm` as another candidate for a `--detach=false` flag, as they experienced `stack rm` followed 'too fast' by `stack deploy` would race for the creation/removal of networks, possibly other stack resources.

**Comment by soumyadipDe** [comment] 2017-05-29 08:20
+1..

**Comment by aluzzardi** [comment] 2017-05-30 03:30
/cc @aaronlehmann

Kinda thinking we should probably provide these options directly from the
client. It would make testing much easier

/cc @dperny

(We'd need something like a status channel for the CLI to display all the
magic)

**Comment by FrenchBen** [comment] 2017-08-28 19:08
Bump to adding `--detach` as a flag for `docker stack deploy`

**Comment by dnephin** [comment] 2017-08-28 19:24
Closing this issue as a duplicate of https://github.com/docker/cli/issues/373 , this will be implemented in docker/cli

**Closed by dnephin** 2017-08-28 19:24 UTC
Labels: area/cli, kind/feature
