### ISSUE TITLE
Docker container contact/communicate outside container/host

### ISSUE THREAD

**Issue by thalesfsp** [moby/moby#23388] opened 2016-06-08 22:22 UTC
Docker version:

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Fri Jun  3 08:34:52 2016
 OS/Arch:      linux/amd64
```

Docker info:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 63
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.11-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 3.857 GiB
Name: moby
ID: 5A2Z:3A6X:6NR5:7EH4:QSRM:4VTU:LX4A:IKDU:S7ZJ:S267:TCI3:2M3W
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 16
 Goroutines: 40
 System Time: 2016-06-08T22:18:19.350202838Z
 EventsListeners: 1
Username: retsly
Registry: https://index.docker.io/v1/
```
## Overview

I cannot curl a service running in host, for example an ExpressJS application listening in the port `3001`, from inside the container:

```
root@e19fc8e02595:/# curl localhost:3001
curl: (7) Failed to connect to localhost port 3001: Connection refused

root@e19fc8e02595:/# curl 0.0.0.0:3001
curl: (7) Failed to connect to 0.0.0.0 port 3001: Connection refused

root@e19fc8e02595:/# curl 172.25.8.25:3001
{"status":200} 
root@e19fc8e02595:/#
```

_Note: `172.25.8.25` is my WiFi IP._
## Pinata

```
$pinata list
These are advanced configuration settings to customize Docker.app on MacOSX.
You can set them via pinata set <key> <value> <options>.

🐳  hostname = docker
   Hostname of the virtual machine endpoint, where container ports will be
   exposed if using nat networking. Access it via 'docker.local'.

🐳  hypervisor = native (memory=4, ncpu=6)
   The Docker.app includes embedded hypervisors that run the virtual machines
   that power the containers. This setting allows you to control which the
   default one used for Linux is.

 ▸  native: a version of the xhyve hypervisor that uses the MacOSX
              Hypervisor.framework to run container VMs. Parameters:
              memory (VM memory in gigabytes), ncpu (vCPUs)


🐳  network = hostnet (docker-ipv4=192.168.65.2, host-ipv4=192.168.65.1)
   Controls how local containers can access the external network via the
   MacOS X host. This includes outbound traffic as well as publishing ports
   for external access to the local containers.

 ▸ hostnet: a mode that helps if you are using a VPN that restricts
              connectivity. Activating this mode will proxy container network
              packets via the Docker.app process as host socket traffic.
              Parameters: docker-ipv4 (docker node), host-ipv4 (host node)
 ▸     nat: a mode that uses the MacOS X vmnet.framework to route container
              traffic to the host network via a NAT.

🐳  filesystem = osxfs
   Controls the mode by which files from the MacOS X host and the container
   filesystem are shared with each other.

 ▸   osxfs: a FUSE-based filesystem that bidirectionally forwards OSX
              filesystem events into the container.


🐳  native/port-forwarding = true
   Expose container ports on the Mac, rather than the VM

 ▸    true: Container ports will be exposed on the Mac
 ▸   false: Container ports will be exposed on the VM

🐳  daemon = run 'pinata get daemon' or 'pinata set daemon [@file|-]>
   JSON configuration of the local Docker daemon. Configure any custom
   options you need as documented in:
   https://docs.docker.com/engine/reference/commandline/daemon/. Set it
   directly, or a @file or - for stdin.
```
## Possible duplicates, references, help
- https://forums.docker.com/t/beta-9-and-localhost-connection-via-net-host/10471
- https://forums.docker.com/t/docker-for-mac-beta-9-and-daemon-options/10449/9
- http://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
- http://stackoverflow.com/questions/29598504/how-to-connect-to-service-in-the-host-machine-from-inside-a-docker-container
- http://blog.michaelhamrah.com/2014/06/accessing-the-docker-host-server-within-a-container/

**Comment by justincormack** [comment] 2016-06-09 20:51
`localhost` in a container refers to the local network interface inside the container itself, for example if you have a service listening inside the container. To connect to a service on the host you need to connect to a routeable address on the host, eg its external IP address.

**Comment by themarcelor** [comment] 2016-06-12 18:42
I have a similar issue. No solution yet... still digging....
http://stackoverflow.com/questions/37777132/how-do-i-make-my-docker-container-communicate-with-another-node-through-a-2nd-in

**Comment by ccostel** [comment] 2017-03-01 01:14
Guys how the hell are people building api's with docker if this is not supported? I have spent over 3 hours on this issue.

**Comment by rdxmb** [comment] 2017-09-27 10:01
@ccostel If you need to communicate with the docker-API you can change the network of the container to the hosts' network. If you do not do that, your container runs in separate network. This is docker design, see https://docs.docker.com/engine/userguide/networking/. So there is no need to swear here!

**Comment by thaJeztah** [comment] 2017-09-27 11:36
This is indeed the expected behaviour for `localhost` inside a container. For Docker for Mac, an experimental feature is added to allow connections to non-containerised services running on the host (Mac); refer to the [Known Limitations, Use Cases, and Workarounds](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds) in the Docker for Mac documentation (under the _"I want to connect from a container to a service on the host"_ heading).

Closing this issue, because I think the original question is answered.

**Closed by thaJeztah** 2017-09-27 11:36 UTC
Labels: area/networking, kind/question, platform/desktop, version/1.11
