### ISSUE TITLE
ARG not working on Windows?

### ISSUE THREAD

**Issue by dhirschfeld** [moby/moby#35918] opened 2018-01-03 04:19 UTC
**Description**
When specifying an `ARG` in a Dockerfile on Windows it's not picking up the value of of the specified `--build-arg`

**Steps to reproduce the issue:**
```dockerfile
ARG PASSWORD="oooooooooooooooooooooooooo"
FROM microsoft/windowsservercore:1709
ENV PASSWORD=${PASSWORD}
RUN echo ${PASSWORD}
```

**Describe the results you received:**
```
PS C:\> docker build --no-cache --build-arg PASSWORD="XXXXXXXXXXXXXXXXX" -t test .
Sending build context to Docker daemon   7.68kB
Step 1/4 : ARG PASSWORD="oooooooooooooooooooooooooo"
Step 2/4 : FROM microsoft/windowsservercore:1709
 ---> be1324f21832
Step 3/4 : ENV PASSWORD=${PASSWORD}
 ---> Running in 62fc11f4cc89
Removing intermediate container 62fc11f4cc89
 ---> a33b15ad6df7
Step 4/4 : RUN echo ${PASSWORD}
 ---> Running in 2160ca2b51a3
${PASSWORD}                             !!!!!!!!!!!!!!  Expected: XXXXXXXXXXXXXXXXX  !!!!!!!!!!!!!!
Removing intermediate container 2160ca2b51a3
 ---> 7bb4d57b282c
Successfully built 7bb4d57b282c
Successfully tagged test:latest
```

**Describe the results you expected:**
I would expect `XXXXXXXXXXXXXXXXX` to be printed and for the resulting image to have a `PASSWORD` env variable set to that value. In the resulting image `PASSWORD` isn't set.

**Output of `docker version`:**
```
Client:
 Version:       master-dockerproject-2018-01-02
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    1a64b1b7
 Built: Tue Jan  2 23:51:11 2018
 OS/Arch:       windows/amd64
 Experimental:  false

Server:
 Engine:
  Version:      master-dockerproject-2018-01-02
  API version:  1.36 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c345c53
  Built:        Tue Jan  2 23:55:06 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 17
Server Version: master-dockerproject-2018-01-02
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 40
Total Memory: 255.9GiB
Name: MYSERVER
ID: LPJW:MQ7R:OOYP:3FRK:VUR2:U3MI:VU4V:CB3N:HTLF:ZEQB:BFCW:73UT
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
HTTPS Proxy: <SNIP>
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by dhirschfeld** [comment] 2018-01-03 04:27
Hmm, maybe I'm mis-understanding how `ARG` is supposed to work.

With `ARG` *after* the `FROM` is does work - i.e.
```dockerfile
FROM microsoft/windowsservercore:1709
ARG PASSWORD
ENV PASSWORD=${PASSWORD}
```
works, but
```dockerfile
ARG PASSWORD
FROM microsoft/windowsservercore:1709
ENV PASSWORD=${PASSWORD}
```
doesn't work.

If that's by design I guess this issue can be closed

**Comment by thaJeztah** [comment] 2018-01-03 19:58
Correct; the `ARG` is scoped per build-stage (i.e., each defined `ARG` is valid up-and-until the next `FROM` stage.

So, in the following

```Dockerfile
# Both FOOBAR and BARBAZ are known here, and inside the `FROM` instruction
ARG FOOBAR=123
ARG BARBAZ=456
FROM myimage:$FOOBAR

# Introduce the FOOBAR arg inside this build stage
# This also should inherit the default value as set above
ARG FOOBAR
RUN echo $FOOBAR

# But BARBAZ is not known here
RUN echo $BARBAZ
```

I'll close this issue, because this works by design, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-01-03 19:58 UTC
Labels: area/builder, platform/windows

**Comment by dhirschfeld** [comment] 2018-01-04 00:06
Thanks for the confirmation - it is in fact documented to behave as such. I just didn't read that properly.

For reference:
> *An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM.*

https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
