### ISSUE TITLE
The IP address of the host in ports is dropped when services are created

### ISSUE THREAD

**Issue by waterelder** [moby/moby#33277] opened 2017-05-18 21:29 UTC
**Description**
The IP address of the host in ports is dropped when services are created

**Steps to reproduce the issue:**

1. Set Ports with IP in the Catalog's `docker-compose.yml`, like below:

        

     > ports: "127.0.0.1:8081:80"

2. Create a Stack StackA from this Catalog.

**Results:**
The StackA's generated `docker-compose.yml` has wrong Ports config, like below:

>  ServiceA:
>    PORTS:
>    *:8081->80/tcp
> 

**Expected:**
The StackA's generated `docker-compose.yml` should have the same IP & ports with the Catalog's docker-compose.yml:

> ServiceA:
> PORTS:
>  "127.0.0.1:8081->80/tcp"

**Output of `docker version`:**

```
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: tn2h7ioe9nlvs026hqi0voks0
 Is Manager: true
 ClusterID: 7oj3o40gag5egmbrkf4x81y44
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 82.146.36.155
 Manager Addresses:
  82.146.36.155:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: proticketing
ID: 3I2K:P3HK:ELYN:B46Y:PT3T:EFBE:5T5Z:NZ6D:6OWL:F7LM:2DFC:IUNT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by thaJeztah** [comment] 2017-05-22 16:29
Correct, publishing on a specific IP-address is currently not supported for services. This is a duplicate of https://github.com/moby/moby/issues/32299, so let me close this one, but thanks for reporting

**Closed by thaJeztah** 2017-05-22 16:29 UTC
