### ISSUE TITLE
Docker Swarm mode leaves orphan containers

### ISSUE THREAD

**Issue by relgames** [moby/moby#35107] opened 2017-10-06 09:36 UTC
**Description**

We have 4 nodes running Docker in Swarm mode, 1 is a manager node.
3 nodes: 4 cores, 32 GB RAM. 
1 node (manager): 1 core, 2 GB RAM.

Trying to deploy 10 services from `docker-compose.yml`, using `docker stack deploy`.
I set memory requirements (min/max) for each service. 
Docker keeps moving containers between nodes, and sometimes it does not fully kills containers but leaves them running, and it causes "port is already used" error.

No services except Portainer:
```
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                        PORTS
xjfnyws3l8ip        portainer           replicated          1/1                 portainer/portainer:latest   *:9000->9000/tcp
```

But one node shows 2 containers still running:
```
# docker ps
CONTAINER ID        IMAGE                                                                                                                          COMMAND                  CREATED             STATUS              PORTS               NAMES
6e0a587f42f2        docker-stage.ipsoft.com/apollo-system-tests-all-rpms@sha256:8f457729e62feb7bb0046875d6a240587b8b55a7040d1f2684b82ff668197f20   "/apps/docker-entr..."   14 hours ago        Up 14 hours                             dmytro_apollo.1.e7v4u5zsj702tfwdrmo12s7w1
df483ee6e3b8        docker-stage.ipsoft.com/apollo-system-tests-all-rpms@sha256:8f457729e62feb7bb0046875d6a240587b8b55a7040d1f2684b82ff668197f20   "/apps/docker-entr..."   16 hours ago        Up 16 hours                             dmytro_apollo.1.ow5ehixqkybjzt1d2z8ja4tba
```

**Steps to reproduce the issue:**
1. Deploy 10 services. Our 9 services consume from 2 to 8 GB RAM, and 1 service requires 24 GB.
2. Keep it running. Docker starts to move containers by no reason.

**Describe the results you received:**
3. Eventually containers do not start because of "port is already in use"

**Describe the results you expected:**
First of all, it should not just kill my containers without a reason, loosing all state. 
Then, if it kills it, it should kill it, and not leave containers running and ports busy.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens under the load.

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.26 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   de56bf2
 Built:        Tue Sep  5 13:18:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log:
Swarm: active
 NodeID: swoh3ttkp5iwz7fvyv292facj
 Is Manager: true
 ClusterID: smgeva6ge495blkm0xde7ail3
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.140.175.121
 Manager Addresses:
  10.140.175.121:2377
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version: de56bf2b59f9ec008a752fcb4e9a8bf2f34d31ca (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: de56bf2b59f9ec008a752fcb4e9a8bf2f34d31ca (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker-latest/seccomp.json
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: Scientific Linux 7.4 (Nitrogen)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797GiB
Name: dyn-10-140-175-121.rnd.cloud.ipsoft.com
ID: 7HPR:DKHH:KFJE:E266:5QHC:BLBO:VUVC:S2V7:YZ2Y:JCAY:HCBT:LGIY
Docker Root Dir: /apps/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

All nodes run in OpenNebula.

**Comment by thaJeztah** [comment] 2017-10-06 22:27
Docker does not kill containers, unless you're updating a service, and it's replacing a container with a new one. What _can_ happen, is that your server is running out of resources (insufficient memory), and as a result, the kernel starts to kill processes to make  more memory available.

In such a situation, bad things happen;

- a container's process, thus a container is killed (least bad thing); docker should detect the container was killed, and starts a new container to replace it (which may be on a different node)
- if memory is really low, docker itself may be killed, or no longer be able to work; in that case it may fail to communicate with the (other) managers in the swarm. In that case, the other managers may report the node as "unavailable", and because they are not able to monitor the container state, think the container has failed, and start a new container to replace it.

You can `docker inspect` the exited containers to check if they were OOM-killed by the kernel, or check the system logs, which should also contain information if the kernel killed processes

Best practices are therefore;

- Always constraint resources (at least memory and cpu) for services
- Consider using memory/cpu _reservation_ for each service (in addition to _constraints_), so that containers are only started on nodes that still have the required amount of resources available
- When reserving resources, take into account that docker, and system processes also require resources 😇 
- Avoid using swap; when your system has to resolve to using swap, performance will drop drastically
- Ideally, don't put load on manager nodes (e.g. by putting the manager node in `drain` mode, or by using placement-constraints to not run services on the manager)

I notice your docker daemon is running on an old version of docker (1.13) docker 1.13 has reached EOL, and a lot of fixes went in newer releases; I recommend updating if possible

Also, if you suspect there's a bug, and you're still able to reproduce on a current version of docker;

- provide relevant daemon, and system logs 
- provide a minimal reproduction case, with the exact commands to reproduce the issue (take into account that we don't have access to your private images, or source code)

**Comment by relgames** [comment] 2017-10-08 16:49
As I said, I set memory requirements (min/max) for each service.
So it was not OOM killer.

I will try to reproduce with latest Docker.

**Comment by thaJeztah** [comment] 2017-11-02 14:21
closing this for now, but let us know if you're still running into this on a current version, and have more information available

**Closed by thaJeztah** 2017-11-02 14:21 UTC
Labels: area/swarm, status/more-info-needed, version/1.13
