### ISSUE TITLE
Cannot reach IPv6 public hosts from container

### ISSUE THREAD

**Issue by andreaskoch** [moby/moby#20559] opened 2016-02-21 14:48 UTC
I have [enabled IPv6 support](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/) on the docker daemon but I **cannot ping or connect to IPv6 hosts** from inside the docker containers. DNS is resolved but packets don't go through:

``` bash
docker run -it ubuntu bash -c "ip -6 addr show dev eth0; ip -6 route show; ping6 -c3 google.com"
```

or 

``` bash
docker run -it ubuntu bash -c "ip -6 addr show dev eth0; ip -6 route show; ping6 -c3 2001:4860:4860::8844"
```

Whereas pinging google.com via IPv4 works just fine:

``` bash
docker run -it ubuntu bash -c "ping -c3 google.com"
PING google.com (173.194.116.166) 56(84) bytes of data.
64 bytes from fra07s63-in-f6.1e100.net (173.194.116.166): icmp_seq=1 ttl=58 time=1.01 ms
64 bytes from fra07s63-in-f6.1e100.net (173.194.116.166): icmp_seq=2 ttl=58 time=0.736 ms
64 bytes from fra07s63-in-f6.1e100.net (173.194.116.166): icmp_seq=3 ttl=58 time=0.697 ms

--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 0.697/0.816/1.017/0.146 ms
```

`docker version`:

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 15
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: hagano-1
ID: WAY2:VQ3E:6ASO:CWYZ:5LJS:PCMX:XJB2:NNHY:CM36:7KGP:4WE3:EAZA
WARNING: No swap limit support
```

`uname -a`:

```
Linux hagano-1 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details:

Vanilla installation of a DigitalOcean Ubuntu 14.04.3 x64 cloud server with IPv6 enabled

How reproducible:
1. Enable IPv6 support in in `/etc/default/docker`:
   
   ```
   DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --ipv6"
   ```
2. Start a docker container and try to ping an IPv6 host:
   
   ``` bash
   docker run -it ubuntu bash -c "ip -6 addr show dev eth0; ip -6 route show; ping6 google.com"
   ```

Actual Results:

`ping6 -c5 google.com` from a docker container

```
PING google.com(fra07s63-in-x03.1e100.net) 56 data bytes

--- google.com ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4033ms

```

Expected Results:

`ping6 -c5 google.com` from the host

```
PING google.com(fra02s28-in-x05.1e100.net) 56 data bytes
64 bytes from fra02s28-in-x05.1e100.net: icmp_seq=1 ttl=59 time=0.847 ms
64 bytes from fra02s28-in-x05.1e100.net: icmp_seq=2 ttl=59 time=0.760 ms
64 bytes from fra02s28-in-x05.1e100.net: icmp_seq=3 ttl=59 time=0.949 ms
64 bytes from fra02s28-in-x05.1e100.net: icmp_seq=4 ttl=59 time=0.768 ms
64 bytes from fra02s28-in-x05.1e100.net: icmp_seq=5 ttl=59 time=0.747 ms

--- google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4003ms
rtt min/avg/max/mdev = 0.747/0.814/0.949/0.078 ms
```

Additional info:

I have also tried various different combinations of configurations as described in your [IPv6 with Docker](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/) guide. All with a similar outcome.
- Explicitly specifying IPv6 DNS servers `DOCKER_OPTS` leads to failing DNS resolution inside the container.
  
  ```
  DOCKER_OPTS="--dns 2001:4860:4860::8844 --dns 2001:4860:4860::8888 --dns 8.8.8.8 --dns 8.8.4.4 --ipv6=true"
  ```
  
  ``` bash
  docker run --rm -it ubuntu bash -c "cat /etc/resolv.conf"
  nameserver 2001:4860:4860::8844
  nameserver 2001:4860:4860::8888
  nameserver 8.8.8.8
  nameserver 8.8.4.4
  ```
  
  ``` bash
  docker run --rm -it ubuntu bash -c "ping6 google.com"
  unknown host
  ```
  
  Leaving the DNS server config out of the `DOCKER_OPTS` leads to the same result because docker will then use the IPv6 DNS servers of the host.
- This is an overview of my network and firewall configuration:
  
  ``` bash
  ip -6 route show
  2a03:b0c0:3:d0::/64 dev eth0  proto kernel  metric 256 
  fe80::/64 dev eth0  proto kernel  metric 256 
  fe80::/64 dev br-3acb67f59ab1  proto kernel  metric 256 
  fe80::/64 dev docker0  proto kernel  metric 256 
  fe80::/64 dev veth547230d  proto kernel  metric 256 
  default via 2a03:b0c0:3:d0::1 dev eth0  metric 1024 
  ```
  
  ``` bash
  iptables -L
  Chain INPUT (policy ACCEPT)
  target     prot opt source               destination         
  
  Chain FORWARD (policy ACCEPT)
  target     prot opt source               destination         
  DOCKER-ISOLATION  all  --  anywhere             anywhere            
  DOCKER     all  --  anywhere             anywhere            
  ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
  ACCEPT     all  --  anywhere             anywhere            
  ACCEPT     all  --  anywhere             anywhere            
  DOCKER     all  --  anywhere             anywhere            
  ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
  ACCEPT     all  --  anywhere             anywhere            
  ACCEPT     all  --  anywhere             anywhere            
  
  Chain OUTPUT (policy ACCEPT)
  target     prot opt source               destination
  
  Chain DOCKER (2 references)
  target     prot opt source               destination
  
  Chain DOCKER-ISOLATION (1 references)
  target     prot opt source               destination
  DROP       all  --  anywhere             anywhere
  DROP       all  --  anywhere             anywhere
  RETURN     all  --  anywhere             anywhere 
  ```
  
  ``` bash
  ip6tables -L
  Chain INPUT (policy ACCEPT)
  target     prot opt source               destination
  
  Chain FORWARD (policy ACCEPT)
  target     prot opt source               destination
  
  Chain OUTPUT (policy ACCEPT)
  target     prot opt source               destination
  ```

**Comment by andreaskoch** [comment] 2016-02-22 20:33
I can now narrow the problem down a bit: It seems that the problem has something to do with IPv6 routing in docker containers that don't have a public IPv6 address.

IPv6 connections work fine when I assign a routable /64 network to the `--fixed-cidr-v6` argument of the `DOCKER_OPTS`:

```
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --ipv6 --fixed-cidr-v6=2a01:7e01:e001:27::/64"
```

I have done this on a Linode server that has a full /64 IPv6 network allocated. DigitalOcean does not provide that option - they only provide 15 (!) :see_no_evil: configurable IPv6 addresses instead of the normally available 18446744073709551616 inside a /64 network.

When I remove `--fixed-cidr-v6=2a01:7e01:e001:27::/64` from the `DOCKER_OPTS` the container get local IPv6 address and loose connection to the outside IPv6 world.

So the good news is that there is **no problem when have a hoster that gives you a full /64 IPv6 network** to play with :smiley:

**Comment by justincormack** [comment] 2016-02-27 21:31
Yes Digital Ocean is a pain for ipv6. I think you can probably assign a smaller subnet to the bridge and get it to work, but it is a bit of a broken setup to start with and I haven't tried. I think I once saw a post about how to do it but can't find it now.

**Comment by matthughes** [comment] 2016-05-06 18:08
@andreaskoch @justincormack How do you know you have a 64 routeable network (linode) or not (digital ocean)?  

Running in a private Openstack, I *think* I have a /64 routeable network:

```
        inet6 fe80::f816:3eff:fec0:569b  prefixlen 64  scopeid 0x20<link>
        inet6 2001:558:fc18:1:f816:3eff:fec0:569b  prefixlen 64  scopeid 0x0<global>
```
However, when I try to add `--fixed-cidr-v6=2001:558:fc18:1::/64`, I lose my default routes.  Specifically, before adding that flag, I have this:

```
ip -6 route show
2001:558:fc18:1::/64 dev eth0  proto kernel  metric 256  expires 2591905sec
fe80::/64 dev eth0  proto kernel  metric 256
default via fe80::21c:73ff:fe3c:e354 dev eth0  proto ra  metric 1024  expires 1705sec hoplimit 64```

after, I have this:
```
ip -6 route show
2001:558:fc18:1::/64 dev eth0  proto kernel  metric 256  expires 2591833sec
2001:558:fc18:1::/64 dev docker0  metric 1024
fe80::/64 dev eth0  proto kernel  metric 256
fe80::/64 dev docker0  proto kernel  metric 256
```

**Comment by andreaskoch** [comment] 2016-05-07 09:45
I had the same problem. I also lost my default IPv6 route when I enabled IPv6 support for the docker daemon:

- The IPv6 address allocation for the containers worked,
- but they could not talk to the internet because the host lost its default route

After adding the IPv6 route manually I could get IPv6 working in docker on my Linode server (see: [my testlog](https://gist.github.com/andreaskoch/e9cb20ba7c480fe86fd28baafbd2de80#reboot--docker-stop--docker-start--add-ipv6-route---works)).

```bash
ip -6 route add default via fe80::1 dev eth0
```

But then I also lost the IPv4 support. And because my goal was to get IPv4 working **alongside** IPv6 I gave up for the time being.

I documented my tests at the time. Maybe the output is useful for someone with more experience in networking: https://gist.github.com/andreaskoch/e9cb20ba7c480fe86fd28baafbd2de80

**Comment by pyy** [comment] 2017-11-15 12:05
@andreaskoch  Thank you for your help. It works for my case.

Also I meet the ipv4 problem after I add ipv6 router manually. 
So I add ipv4 router manually as what I do for ipv6. It works again.

Before run docker:
```
# ip route show
default via 172.31.x.x dev eth0
....
```
After run docker:
```
# ip route add default via 172.31.x.x dev eth0
```

**Comment by enchained** [comment] 2018-04-17 13:18
Hi everyone. I came here from googling the issue, while having trouble accessing ipv6 addresses from inside of a container too. However I don't want to enable ipv6 for the whole Docker (neither I can, cause I'm on Synology and editing daemon config leads to docker package failing to run).

So I'm trying to setup another network bridge and add it to the container. Default bridge doesn't have ipv6 enabled. But new bridge requires to enter ipv6 Subnet and ipv6 Gateway (and optionally an ip range). Where can I find those things on the host system? I can see ipv6-ish things in ifconfig and ip route, but not sure what goes where, and primarily lack the knowledge of ipv6 networking 
Will appreciate any help!

**Comment by akerouanton** [comment] 2024-04-05 13:46
I can't reproduce the original issue and both the code and the IPv6 docs have evolved quite a lot since this issue was opened. So let me close it.

**Closed by akerouanton** 2024-04-05 13:46 UTC
Labels: area/networking, version/1.10, area/networking/ipv6
