### ISSUE TITLE
How to install Vim syntax as a standalone file?

### ISSUE THREAD

**Issue by mcandre** [moby/moby#38929] opened 2019-03-23 19:27 UTC
Hi, I want to automate the process of installing Docker syntax highlighting for Vim. Currently, I am using this line in my vim-plug configuration:

```vimrc
Plug 'docker/docker' , {'rtp': '/contrib/syntax/vim/'}
```

However, this takes several minutes to complete, as it depends on cloning the entire Docker repository, which is quite large. Is there a faster vim-plug configuration for Docker? I think I could grab the files manually, but I would like to keep this process automated.

**Comment by thaJeztah** [comment] 2019-03-27 13:33
I'm not aware of a different approach currently; the original scripts to build the `.deb` and `.rpm` packages had some preliminary code to install those files as part of the package (https://github.com/moby/moby/commit/eee1efcfd6c46dbdc5da02ca12722e399a56bb12#diff-fb14f724354623fee51dc7fb66ea3298R1), but that was never enabled.

With active development of the Dockerfile syntax being moved to the moby/buildkit repository, perhaps these files should be moved either to that repository (or a separate repository; I think the plan is to move the Dockerfile syntax to its own repo) (/cc @tonistiigi)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2019-03-27 13:33 UTC
Labels: area/builder, kind/question
