### ISSUE TITLE
manifest invalid error when pushing image to quay.io

### ISSUE THREAD

**Issue by vvoody** [moby/moby#39220] opened 2019-05-15 09:40 UTC
**Description**

Unable to push image to registry hosted at `quay.io` in docker-ce **19.03.0-beta4**.

**Steps to reproduce the issue:**
1. docker tag nginx quay.io/vvoody/test:nginx
2. docker push quay.io/vvoody/test:nginx

**Describe the results you received:**

```
The push refers to repository [quay.io/vvoody/test]
62491c1227dd: Pushed
b3f4f4d8f801: Pushed
2ddf52a320d2: Pushed
16174e87921f: Pushed
manifest invalid: manifest invalid
```

**Describe the results you expected:**

Image OK to push to `quay.io`.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue occurs when use docker-ce **19.03.0-beta4** to push image to **quay.io**. However, it's good for pushing to hub.docker.io.

And docker-ce 18.03.0 and 18.09.2 are also able to push image to quay.io.

Logs said `level=warning msg="failed to upload schema2 manifest: manifest invalid: manifest invalid"`.

I found https://github.com/moby/moby/issues/27580 reported for same `manifest invalid` issue. It looks resolved. And everything was good before I tried **19.03.0-beta4**.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.0-beta4
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        e4666eb
 Built:             Tue May 14 12:51:53 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       e4666eb
  Built:            Tue May 14 12:50:26 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0-beta2)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.0-beta4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-142-generic
 Operating System: Ubuntu 16.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 992MiB
 Name: ubuntu-xenial
 ID: f7ad9380-11fa-46a7-be23-348b3cc87628
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 21
  Goroutines: 34
  System Time: 2019-05-15T09:37:01.146190131Z
  EventsListeners: 0
 Username: vvoody
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 16.04 on VirtualBox.

**Comment by jacobmarble** [comment] 2019-05-15 14:46
I'm seeing the same problem as of about 12h ago. Specifically with quay.io. Maybe it's a quay.io issue?

MacOS 10.14.4
Docker Desktop 2.0.4.0 (edge)
Engine 19.03.0-beta3

**Comment by cpuguy83** [comment] 2019-05-15 16:11
Support for pushing to Quay was broken when this was merged https://github.com/moby/moby/pull/37874
That PR removed support for the schema1 manifest format which has been deprecated for a very long time and is insecure.

**Comment by cpuguy83** [comment] 2019-05-15 16:22
And of course Quay only supports schema1.

**Comment by jacobmarble** [comment] 2019-05-15 17:41
Maybe whoever figures out a workaround first can post here? I'm a little blind-sided by this.

**Comment by cpuguy83** [comment] 2019-05-15 18:16
Thanks for reporting, I'm poking some folks both at Quay and Docker, hopefully we can resolve this issue quickly.

**Comment by jacobmarble** [comment] 2019-05-15 18:36
I'm getting good results from Quay's support folks. Sounds like they have a beta ready for anyone that needs it. I'll share if/when we opt in.

**Comment by vvoody** [comment] 2019-05-16 14:52
@cpuguy83 and @jacobmarble, thanks for the information!

**Comment by jacobmarble** [comment] 2019-05-17 01:32
My organization has requested that Quay enable the Docker version 2 schema 2 feature beta for our namespace. I have successfully pushed images where I could not before. No changes on my end; `docker push` simply works but did not before.

**Comment by thaJeztah** [comment] 2019-05-23 00:54
let me close this one as this is not a bug, but due to quay still migrating to the current specs; feel free to continue the conversation though

**Closed by thaJeztah** 2019-05-23 00:54 UTC
Labels: area/distribution
