### ISSUE TITLE
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown

### ISSUE THREAD

**Issue by leejansq** [moby/moby#37009] opened 2018-05-07 06:51 UTC
**Description**
docker exec xxx ls:
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown

**Steps to reproduce the issue:**
occur very infrequently

**Describe the results you received:**
```
`docker ps` find that the container is running, 
Actually the container is exited( cat /proc/${Container.State.Pid}/stat: No such file or directory ) 
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
18.03.0-ce
```

**Output of `docker info`:**

```
Containers: 48
 Running: 11
 Paused: 0
 Stopped: 37
Images: 59
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.16.6-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.91GiB
...
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2018-05-07 10:38
Can you try updating to 18.03.1 ? The 18.03.1 patch release contains various fixes, which could be related.

**Comment by leejansq** [comment] 2018-06-11 11:17
still occur with updating to 18.03.1.
docker-containerd-ctr list tasks ,I found stopped container 
```
TASK                                                                PID        STATUS    
591c58b60f47c3e10e011d964ffd6fade5403f4e98ef229d37575cc389662f2c    10252      STOPPED
```

**Comment by nigelgbanks** [comment] 2018-07-27 10:44
I've seen this occur under 18.06.0-ce as well:

```
devel@typhoon-build:~$ docker ps
CONTAINER ID        IMAGE      COMMAND                  CREATED             STATUS              PORTS               NAMES
4fd1aabfab6d        ......   "/bin/bash -c make _…"   2 hours ago         Up 2 hours                              awesome_kilby
```

```
$ docker exec -ti awesome_kilby ps aux
cannot exec in a stopped state: unknown
```

```
$ docker inspect awesome_kilby
[
    {
        "Id": "4fd1aabfab6d69d62e96023dcd4e7d0136b1a7a8e5a99d369047c256eab107f5",
        "Created": "2018-07-27T09:12:15.623560324Z",
        "Path": "/bin/bash",
        "Args": [
            "-c",
            "make",
            "_setup-container",
            "&&",
            "make",
            "BUILD_DIRECTORY=build/container/Debug",
            "DOCUMENTATION=1",
            "sonar-analyze"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 37120,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-07-27T09:12:16.073428915Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:bb79f0660dc1a9fc92e9b93a6e4b62430a53b37ede9efa463c7367cc63e1620a",
        "ResolvConfPath": "/var/lib/docker/containers/4fd1aabfab6d69d62e96023dcd4e7d0136b1a7a8e5a99d369047c256eab107f5/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4fd1aabfab6d69d62e96023dcd4e7d0136b1a7a8e5a99d369047c256eab107f5/hostname",
        "HostsPath": "/var/lib/docker/containers/4fd1aabfab6d69d62e96023dcd4e7d0136b1a7a8e5a99d369047c256eab107f5/hosts",
        "LogPath": "/var/lib/docker/containers/4fd1aabfab6d69d62e96023dcd4e7d0136b1a7a8e5a99d369047c256eab107f5/4fd1aabfab6d69d62e96023dcd4e7d0136b1a7a8e5a99d369047c256eab107f5-json.log",
        "Name": "/awesome_kilby",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/bamboo/.ccache:/ccache",
                "/data/atlassian/bamboo/xml-data/build-dir/SBX-LINUX-JOB1:/typhoon"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": true,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/asound",
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/d78491106cb05d4241ae88adb268415a162f8e4d007dabce3e48cfa17ed423e0-init/diff:/var/lib/docker/overlay2/940e2615b9d9f91cff612800cdcd8bd537128e097251a95807f1802405f96a98/diff:/var/lib/docker/overlay2/a786b7714c21cfdc01f5f64902729540afc7d79e12d59c141606543fa414a6a0/diff:/var/lib/docker/overlay2/9a9bc70b5d6e0efcf869bb25ec5c8ad0abd52291d54472e1fa4936f8f896245d/diff:/var/lib/docker/overlay2/e0404298801c2e56c3e2c5ae2ff4f6c4fa6f8e43fec2d09fec6ed19339cd9a6a/diff:/var/lib/docker/overlay2/25f6a49f3d6d2ef3e9ca2a1bf992466778115b361c950096ff7e0b0c65e8f787/diff:/var/lib/docker/overlay2/8244fcaf70a7abc29f37a412d936f14fc2010fa9e84a57cc6d51c8e0f1c8f367/diff:/var/lib/docker/overlay2/f2667bc2fe7c8d5147035c37f9fbcb48326ff17bac3fe525fd4d278384c8b28a/diff:/var/lib/docker/overlay2/b22cae4df2e7983fadef0a431ae06633e0c03ba58ea56a309597cbc88910c16d/diff:/var/lib/docker/overlay2/fc8d0ff2e94ccf55d5e8ea269461388b45a2492c5196c67da12cb541fc381b98/diff:/var/lib/docker/overlay2/0e55a4184eea8878bd219dfee7f18b13ca1f3caed98ab770c98355416e7bc9d9/diff:/var/lib/docker/overlay2/6052c6f072ea1dd1f24e646d7f9e2f10f34a489d924c09d091df20d37ce5e84a/diff",
                "MergedDir": "/var/lib/docker/overlay2/d78491106cb05d4241ae88adb268415a162f8e4d007dabce3e48cfa17ed423e0/merged",
                "UpperDir": "/var/lib/docker/overlay2/d78491106cb05d4241ae88adb268415a162f8e4d007dabce3e48cfa17ed423e0/diff",
                "WorkDir": "/var/lib/docker/overlay2/d78491106cb05d4241ae88adb268415a162f8e4d007dabce3e48cfa17ed423e0/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/bamboo/.ccache",
                "Destination": "/ccache",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/data/atlassian/bamboo/xml-data/build-dir/SBX-LINUX-JOB1",
                "Destination": "/typhoon",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "4fd1aabfab6d",
            "Domainname": "",
            "User": "1002",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "BUILD_BRANCH=unknown",
                "BUILD_COMMIT=unknown",
                "BUILD_PLANKEY=unknown",
                "BUILD_NUMBER=unknown",
                "TYPHOON_VERSION=0.0.0",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/build-wrapper-linux-x86:/opt/sonar-scanner-3.2.0.1227-linux/bin",
                "HOME=/home",
                "CCACHE_DIR=/ccache/typhoon"
            ],
            "Cmd": [
                "/bin/bash",
                "-c",
                "make",
                "_setup-container",
                "&&",
                "make",
                "BUILD_DIRECTORY=build/container/Debug",
                "DOCUMENTATION=1",
                "sonar-analyze"
            ],
            "Image": "typhoon-docker.devtools.waters.com/typhoon-build:master-11",
            "Volumes": null,
            "WorkingDir": "/typhoon",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "branch": "master",
                "buildKey": "TYP-DOCKTYPBLD-BLD",
                "buildNumber": "11",
                "buildTimeStamp": "2018-07-05T09:38:58.630+01:00",
                "commit": "d7ffd2dc7e24dee3de08db8ed3168602e5bbfc79",
                "description": "Typhoon build environment."
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "7b9ff3ff33c87774b23a46cf60fa04d5787c0f729a26926481ddab643ad24a9d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/7b9ff3ff33c8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "7bd29ffbf00126766d740e4cf53aa40ef6b16478a75d3c7612e1d77e0218637c",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "ffa8ea3a93696a9f0374e89f6b323caf2427672ee258241b0412e8c92532d685",
                    "EndpointID": "7bd29ffbf00126766d740e4cf53aa40ef6b16478a75d3c7612e1d77e0218637c",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```
```
$ cat /proc/37120/stat
cat: /proc/37120/stat: No such file or directory
```

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 119
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.9GiB
Name: typhoon-build
ID: IPAY:RD26:3P6U:3VQ5:HB6Z:OY6W:R2VN:LTZD:LQ4Y:QTNM:QYWZ:ODVK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by nigelgbanks** [comment] 2018-07-27 10:49
hmm seems even doing things like:

```
$ docker run -ti --rm alpine ash
/ # exit
```

Causes the container to get into this state.

**Comment by thaJeztah** [comment] 2018-07-30 11:58
ping @crosbymichael @mlaventure @dmcgowan PTAL - looks like somehow dockerd and containerd state is out of sync?

**Comment by marenzo** [comment] 2018-10-14 11:49
happens to us as well. any update?

**Comment by thisisshi** [comment] 2018-10-31 00:32
seeing this as well

**Comment by konalegi** [comment] 2019-01-14 08:53
any updates?

**Comment by ccimmo** [comment] 2019-02-14 01:02
Got it too on Docker version 18.09.0, build 4d60db4 on Raspberry PI raspbian Stretch

**Comment by kirtangajjar** [comment] 2019-04-26 04:22
Even I have got this error. But the thing is even if I remove the container and start it again, it just stays in `created` state and does not proceed further

**Comment by lixianyang** [comment] 2019-05-06 10:44
docker version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
5月 06 18:37:05 k8s-worker2 dockerd[718]: time="2019-05-06T18:37:05.424828185+08:00" level=error msg="Handler for POST /v1.38/containers/af7331ee2a19a156aa8a24e9531908e6009a8df3bd2858e06f478b3baecd0c20/start returned error: OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 46\\\"\": unknown"
5月 06 18:41:28 k8s-worker2 dockerd[718]: time="2019-05-06T18:41:28+08:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/14759e87e23d98186b4e2d48556ea72907d02262117b87a77daabf3d81a9eb36/shim.sock" debug=false pid=34838
5月 06 18:41:49 k8s-worker2 dockerd[718]: time="2019-05-06T18:41:49+08:00" level=info msg="shim reaped" id=14759e87e23d98186b4e2d48556ea72907d02262117b87a77daabf3d81a9eb36
5月 06 18:42:17 k8s-worker2 dockerd[718]: time="2019-05-06T18:42:17+08:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/ce66964fd0d36153cb56adb27c301aef420d8a96d06bdfa05879c017ea034c12/shim.sock" debug=false pid=41729
5月 06 18:42:17 k8s-worker2 dockerd[718]: time="2019-05-06T18:42:17+08:00" level=info msg="shim reaped" id=ce66964fd0d36153cb56adb27c301aef420d8a96d06bdfa05879c017ea034c12
5月 06 18:42:17 k8s-worker2 dockerd[718]: time="2019-05-06T18:42:17.370821546+08:00" level=error msg="stream copy error: reading from a closed fifo"
5月 06 18:42:17 k8s-worker2 dockerd[718]: time="2019-05-06T18:42:17.370980518+08:00" level=error msg="stream copy error: reading from a closed fifo"
5月 06 18:42:17 k8s-worker2 dockerd[718]: time="2019-05-06T18:42:17.388641665+08:00" level=error msg="ce66964fd0d36153cb56adb27c301aef420d8a96d06bdfa05879c017ea034c12 cleanup: failed to delete container from containerd: no such container"
5月 06 18:42:17 k8s-worker2 dockerd[718]: time="2019-05-06T18:42:17.388681331+08:00" level=error msg="Handler for POST /v1.38/containers/ce66964fd0d36153cb56adb27c301aef420d8a96d06bdfa05879c017ea034c12/start returned error: OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 46\\\"\": unknown"
5月 06 18:43:12 k8s-worker2 dockerd[718]: time="2019-05-06T18:43:12.210677691+08:00" level=error msg="Error setting up exec command in container ce66964fd0d36153cb5: Container ce66964fd0d36153cb56adb27c301aef420d8a96d06bdfa05879c017ea034c12 is not running"
```

**Comment by thaJeztah** [comment] 2019-05-23 16:47
@lixianyang does not look like that issue is related; just from a quick glance, I think that's a kernel bug in the CentOS/RHEL kernels, where kernel-memory limits are broken; see https://github.com/opencontainers/runc/pull/1921. That issue is resolved in recent runc versions (part of Docker 18.09.1 and up https://github.com/docker/engine/pull/121)

**Comment by m2f0** [comment] 2020-01-14 13:14
@thaJeztah The error occurs to me. Versions:
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by thaJeztah** [comment] 2020-01-14 13:57
@m2f0 could you edit your comment, and add the output of `docker info` as well? Also; do you have a way to consistently reproduce the issue? Is there anything in the logs that could provide more details as to what happened?

**Comment by thaJeztah** [comment] 2020-03-10 09:56
closing, as this one went stale

**Comment by thaJeztah** [comment] 2020-03-10 09:57
@m2f0 if you have exact steps to consistently reproduce the issue, feel free to open a new issue with details

**Closed by thaJeztah** 2020-03-10 09:56 UTC
Labels: area/runtime, status/more-info-needed, version/18.03, version/18.06

**Comment by Mathiasdm** [comment] 2020-07-03 13:17
We have a number of build machines where we see this occur. My impression is that the issue occurs about once a day on our system (so: each day, there's probably around 1 machine with a hanging container).
Can that help the debugging effort? We can try to run additional debugging commands.

Some things that might have an impact:

- These are build machines with 32 or 40 cores
- Having a load of 50-100 is not uncommon on these machines
- The machines have spinning disks (when disk-intensive actions are ongoing and load is high, interactive sessions tend to get slow)

We can still do whatever we want with regard to 'docker bookkeeping'. A container that is no longer running (but still shows up in 'docker ps') can be renamed, for example.

One example container on our bldsrv033 machine:
`9148733866c4        <...>:image-126a148f18bdba61d0aac82b78103502206a7df387aab9af0f0fdaaa0a11b15a   "/usr/local/bin/dumb…"   9 days ago          Up 9 days           0.0.0.0:43701->8081/tcp   bldsrv033_15481_renametest
`
docker version:
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by orgads** [comment] 2021-01-31 16:37
Happened to us too, After OOM killer.

docker inspect:
```
[
    {
        "Id": "9b3043f16abc36d0c82fc609f530c62d2b25474a335b13d8782d6768c8a173ad",
        "Created": "2021-01-28T17:05:11.787491846Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "npm",
            "run",
            "start:prod"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 10659,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-01-30T14:49:23.77605117Z",
            "FinishedAt": "2021-01-30T14:49:19.412762798Z"
        },
        "Image": "sha256:736da07d5d33995e4c9db41017b0ff41e1682bf5a8d13218b2836b550134790b",
        "ResolvConfPath": "/var/lib/docker/containers/9b3043f16abc36d0c82fc609f530c62d2b25474a335b13d8782d6768c8a173ad/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/9b3043f16abc36d0c82fc609f530c62d2b25474a335b13d8782d6768c8a173ad/hostname",
        "HostsPath": "/var/lib/docker/containers/9b3043f16abc36d0c82fc609f530c62d2b25474a335b13d8782d6768c8a173ad/hosts",
        "LogPath": "",
        "Name": "/vag_vag-session-manager_1",
        "RestartCount": 5,
        "Driver": "overlay2",
        "Platform": "linux",
...
```

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1036-azure
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.352GiB
 Name: connector
 ID: 4GOI:SJIQ:YGLJ:KFKL:5RZL:TYTI:3QEU:BDFJ:VOA4:SPZP:QJTE:YG4U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by deepy** [comment] 2022-11-16 10:24
I don't have a way to reproduce this but it happened to me on `Docker version 20.10.17, build 100c701`

journalctl shows nothing but 

```
Nov 15 20:08:44 dockerd[5974]: time="2022-11-15T20:08:44.078321519Z" level=error msg="Failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=moby
Nov 15 20:08:44 dockerd[5974]: time="2022-11-15T20:08:44.090405678Z" level=info msg="Waiting for containerd to be ready to restart event processing" module=libcontainerd namespace=moby
```

**Comment by kong62** [comment] 2025-12-26 10:21
```
# docker exec -it aipusaas-cubejs-api /bin/sh
Error response from daemon: container 7123f057d7f16376439e501a59f463940b8a68ea717a11fffa5dc030939411dc is not running
```
or
```
# docker exec -it aipusaas-cubejs-api /bin/sh
cannot exec in a stopped state: unknown
```

but docker ps running:
```
# docker ps -a
CONTAINER ID   IMAGE                                                                                          COMMAND                  CREATED        STATUS       PORTS     NAMES
7123f057d7f1   harborproxy.xxxxx.io/proxy/app/aipusaas-cubejs-api:aipusaas-cubejs-api-20251225153626-0000000   "docker-entrypoint.s…"   25 hours ago   Up 5 hours             aipusaas-cubejs-api
```

docker version:
```
# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

# docker version
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:32:04 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:31:02 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
