### ISSUE TITLE
'Aliases' shown with inspect but not with golang client

### ISSUE THREAD

**Issue by eine** [moby/moby#33779] opened 2017-06-22 10:47 UTC
**Description**

`NetworkSettings.Networks[*].Aliases` content is shown with `docker inspect` but not with `moby/client.`

**Steps to reproduce the issue:**
1. Create the following `docker-compose.yml`:
```
version: '2'

services:
  compcont:
    image: friendlyhello
    networks:
      default:
      builds:
        aliases: [ "mycompcont" ]

networks:
  default:
    external:
      name: othernet
  builds:
    external:
      name: mynet
```
2. Create both networks and bring compose up:
```
$ docker network create mynet
$ docker network create othernet
$ docker-compose up
```
3. Inspect the container:
```
$ docker inspect test_compcont_1
...
        "NetworkSettings": {
...
            "Networks": {
                "mynet": {
...
                    "Aliases": [
                        "compcont",
                        "b41fa65b66dc",
                        "mycompcont"
                    ],
...
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                },
                "othernet": {
...
                    "Aliases": [
                        "compcont",
                        "b41fa65b66dc"
                    ],
...
                    "Gateway": "172.19.0.1",
                    "IPAddress": "172.19.0.2",
                }
            }
        }
...
```
4. Write a simple app with the client library:
```
package main

import (
  "context"
  "fmt"
  "github.com/docker/docker/api/types"
  "github.com/docker/docker/client"
)

func main() {
  cli, err := client.NewEnvClient()
  if err != nil { panic(err) }
	
  conts, err := cli.ContainerList(context.Background(), types.ContainerListOptions{All:true})
  if err != nil { panic(err) }
	
  for _, cont := range conts {
    fmt.Println(cont.Names)
    for k, n := range cont.NetworkSettings.Networks {
      fmt.Println("\t", k, "\t", n.Gateway, "\t", n.IPAddress, "\t", n.Aliases)
    }
  }
}
```
5. `go run main.go`

**Describe the results you received:**

```
$ go run main.go
[/test_compcont_1]
         othernet   172.19.0.1  172.19.0.2   []
         mynet       172.18.0.1  172.18.0.2  []
```

**Describe the results you expected:**

```
$ go run main.go
[/test_compcont_1]
         othernet   172.19.0.1  172.19.0.2   ["compcont", "b41fa65b66dc"]
         mynet       172.18.0.1  172.18.0.2  ["compcont", "b41fa65b66dc", "mycompcont"]
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I cannot switch from `docker/docker/client` to `moby/moby/client`:

```
$ go get github.com/moby/moby/client
# github.com/moby/moby/client
C:\Users\eine\go\src\github.com\moby\moby\client\service_create.go:38: cannot use distributionInspect.Descriptor.Digest (type "github.com/docker/docker/vendor/github.com/opencontainers/go-digest".Digest) as type "github.com/moby/moby/vendor/github.com/opencontainers/go-digest".Digest in argument to imageWithDigestString
C:\Users\eine\go\src\github.com\moby\moby\client\service_update.go:50: cannot use distributionInspect.Descriptor.Digest (type "github.com/docker/docker/vendor/github.com/opencontainers/go-digest".Digest) as type "github.com/moby/moby/vendor/github.com/opencontainers/go-digest".Digest in argument to imageWithDigestString
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: LDKB:3CJT:OB3Q:KFV3:5VPW:P63T:KGBQ:CWKE:O2AU:5Q54:7N2Y:DJA7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 51
 System Time: 2017-06-22T06:24:06.3841556Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by aaronlehmann** [comment] 2017-06-24 00:54
`inspect` uses the `ContainerInspectWithRaw` function rather than `ContainerList`. It looks like this route fills in some extra information in `NetworkSettings` that isn't filled in by `ContainerList`. I think `ContainerList` should be fixed to behave consistently with inspect.

**Comment by thaJeztah** [comment] 2017-06-24 04:52
I wonder if this was done for performance reasons; as it would have to fetch information for each network each container is attached to.

ping @sanimej perhaps you know

**Comment by 1138-4EB** [comment] 2017-06-24 15:39
@theJeztah, indeed, I want to retrieve information for each container and each network. Then, I don't mind to iterate over `ContainerList` or `NetworkList`. However, the latter seems to provide no info at all about aliases.

Anyway, I could make it work with either `ContainerInspectWithRaw` or `ContainerInspect`, as @aaronlehmann pointed:

```
for _, cont := range conts {
  fmt.Println(cont.Names, cont.ID)
	  
  m, err := cli.ContainerInspect(context.Background(), cont.ID)
  if err != nil { panic(err) }

  for k, n := range m.NetworkSettings.Networks {
    fmt.Println("\t", k, "\t", n.Gateway, "\t", n.IPAddress, "\t", n.Aliases)
  }
}
```

Then, concerning my issue, this can be closed. However, you might want to leave it open, to discuss if `ContainerList` should me fixed, or it should be just documented. I think that having both options for performance reasons can be useful.

**Comment by natemurthy** [comment] 2017-07-28 23:10
I'm experiencing similar problem just pulling `github.com/moby/moby/client` package:
```
$ go get -u github.com/moby/moby/client
# github.com/moby/moby/client
moby/moby/client/service_create.go:96: cannot use distributionInspect.Descriptor.Digest (type "github.com/docker/docker/vendor/github.com/opencontainers/go-digest".Digest) as type "github.com/moby/moby/vendor/github.com/opencontainers/go-digest".Digest in argument to imageWithDigestString
```
I'm using
```
$ go version
go version go1.8.3 linux/amd64
```

**Comment by thaJeztah** [comment] 2017-07-29 10:31
@natemurthy because packages will still be moved to their final destination, the import paths are still named `docker/docker`; try using github.com/docker/docker/client instead

**Comment by natemurthy** [comment] 2017-07-29 21:29
@thaJeztah That's what I ended up doing. When do you expect the full refactoring to `moby/moby` will be complete?

**Comment by thaJeztah** [comment] 2017-07-29 22:46
The current discussion is on the forums; https://forums.mobyproject.org/t/topic-find-a-good-and-non-confusing-home-for-the-remaining-monolith/37/73

**Comment by natemurthy** [comment] 2017-07-30 06:21
This is a bit unsettling. There's no dependency management solution in Go?
> I suggest, that until Go figures out dependency management, we provide a vendor/ folder in this library repository.

**Comment by thaJeztah** [comment] 2017-07-30 09:06
Go itself (`go get`) always assumes "latest"; no option to pin to a specific commit or tag/release. Also there's no "global" configuration file to (e.g.) alias packages, which is troublesome because the URL is encoded in the import paths.

Vendoring (although a good solution as it guarantees reproducible builds), does not solve all of those problems

**Comment by thaJeztah** [comment] 2023-09-17 19:23
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-17 19:23 UTC
Labels: area/api, area/networking, version/17.03
