### ISSUE TITLE
Can't start hello-world or existing containers: OCI runtime create failed: container_linux.go:344 starting container process caused "exec": stat: no such file or directory": unknown.

### ISSUE THREAD

**Issue by luckydonald** [moby/moby#38789] opened 2019-02-24 00:54 UTC
**Description**

**Steps to reproduce the issue:**
**Describe the results you received:**

```bash
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete
Digest: sha256:2557e3c07ed1e38f26e389462d03ed943586f744621577a99efb77324b0fe535
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/hello\": stat /hello: no such file or directory": unknown.
ERRO[0004] error waiting for container: context canceled
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
I have this problem with **every** existing container after upgrading from `18.01.0-ce` to `18.09.2`.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
$ docker info
Containers: 85
 Running: 0
 Paused: 0
 Stopped: 85
Images: 779
Server Version: 18.09.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1113
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58GiB
Name: las-pegasus
ID: ZTAL:K7MI:BLD7:ZPDJ:OH6Q:FOUT:Q2HU:OA67:AEIF:KUUB:PESA:PYPJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- docker on bare metal

**Comment by luckydonald** [comment] 2019-02-24 01:51
Downgrading docker-ce from `5:18.09.2~3-0~ubuntu-xenial` to `18.06.3~ce~3-0~ubuntu`,
and running `sudo rmdir /var/run/docker.sock` is getting it back to working.

**Comment by cpuguy83** [comment] 2019-02-24 02:03
Most likely this is because you have set "MountFlags" in your systemd unit file.

Because in 18.09 dockerd is no longer managing containerd (systemd is), the "MointFlags" option effectively puts docker and containerd in separate mount namespaces and do not have shared mount trees. This means when dockerd prepares a container's rootfs, containerd (which actually calls out to runc to execute the container, cannot see the rootfs mounts.

Can you check your systemd configs for docker?

**Comment by luckydonald** [comment] 2019-02-24 02:07
```ini
# cat /etc/systemd/system/docker.service.d/10-machine.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic
Environment=
```

**Comment by thaJeztah** [comment] 2019-02-25 13:57
> I didn't expected a `.minor` release to break that much...

Docker's releases are not using "semver"; the versions are using a `YY.MM.<NN>` pattern, corresponding with target-dates for the release, where `.NN` is used for patch releases (e.g. `18.09.3` was a patch release for the 18.09 release). Generally, versions should be compatible with older versions, but things may be deprecated between release, or configuration changes may be needed, which would be pointed out in the release notes; https://docs.docker.com/engine/release-notes/

w.r.t. the `MountFlags`; @luckydonald could you also check the output of `systemctl cat docker.service` ? It's possible that other override-files exist.

**Comment by cpuguy83** [comment] 2019-02-25 17:21
Also it's more of a packaging change than anything else. `docked` still operates as always, just that Docker CE is packaged such that containerd is managed by systemd and as such `dockerd` doesn't try to in this case.

Previously some people added `MountFlags=slave` to their systemd config in order to work around some issues when removing containers (`device or resource busy` errors), but this is no longer a problem and the option can be safely removed.

**Comment by luckydonald** [comment] 2019-03-01 23:30
>  @luckydonald could you also check the output of systemctl cat docker.service ? It's possible that other override-files exist.
@thaJeztah I downgraded to `18.06.3`, is that still relevant?

**Comment by thaJeztah** [comment] 2019-03-02 00:27
So the `MountFlags=slave` should not be there; that's what caused the problem on 18.09; if you remove that, 18.09 should work

**Comment by luckydonald** [comment] 2019-03-02 09:06
I realized they have different `--storage-driver overlay2`, would that be a problem or is the second one (`10-machine.conf`) just ignored?

**Comment by thaJeztah** [comment] 2019-03-02 09:31
Second one overrides the first one; if you want to maintain your local images and containers, you need to keep the same driver, but if you want to start fresh, I'd recommend the overlay2 driver

**Comment by cpuguy83** [comment] 2019-03-05 15:31
I'm going to close this because the issue is as mentioned, cannot use "MountFlags=slave"

**Closed by cpuguy83** 2019-03-05 15:31 UTC
