### ISSUE TITLE
Disbributing services with yml using remote api.

### ISSUE THREAD

**Issue by Namsulee** [moby/moby#34557] opened 2017-08-18 02:23 UTC
**Description**
I wonder how to create services with yml files using remote api.
'docker stack deploy' is dedicated with docker cli and there is no api to call  with yml file.
I knew docker-compose is another option to launch containers with yml file.
However, I don't want to take care docker-compose dependency.(I know libcompose)
'docker stack deploy' will create services by swarm, it would be easier to manage for me.
Also, DOCKER_HOST is set in my remote side and I can use remoe api all to request for dockerd.
Is there a way how to use docker stack deploy without cli, should I develope yml parser in my client?

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ij7fc2f203vddkjy7ob4q9esp
 Is Manager: true
 ClusterID: fp4p2rdim6mmlrey1hhfybm77
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 1
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-89-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.708GiB
Name: namsulee
ID: 3VEC:YWEK:CJVK:ABOZ:N2MK:X2X4:3XPC:RJ3R:MDNL:WCWW:JCOD:6AFM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.112.1.184:8080/
Https Proxy: http://10.112.1.184:8080/
No Proxy: localhost,127.0.0.1,docker-registry.your.corp
Username: namsulee
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.113.62.204:443
 13.124.64.10:443
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2017-08-18 13:13
You can re-use the existing yaml parser in https://github.com/docker/cli/tree/master/cli/compose

All the stack stuff is client side.

**Comment by thaJeztah** [comment] 2017-08-19 20:14
Goal is to eventually move the stacks server side, but no work is done yet to implement this; there's an issue for th roadmap here; https://github.com/moby/moby/issues/26876

**Comment by thaJeztah** [comment] 2017-08-19 20:15
let me close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-08-19 20:15 UTC
Labels: area/api, area/bundles, kind/question, version/17.05

**Comment by Namsulee** [comment] 2017-08-21 05:13
Do you mean by Goal is to eventually move the stacks server side', the engine of remote api will be covered the stack request like using dab?
