### ISSUE TITLE
Mac beta: inotify does not work if mount target has dash in directory name

### ISSUE THREAD

**Issue by nkovacs** [moby/moby#24527] opened 2016-07-12 09:31 UTC
**Output of `docker version`:**

```
Docker version 1.12.0-rc3, build 91e29e8, experimental
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 144
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: MGAT:ZEGU:E4YU:J7FL:A4P6:LGF3:R7G4:54F3:UKRI:MCJ5:QGQF:DPEY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 66
 System Time: 2016-07-11T11:09:50.469715841Z
 EventsListeners: 8
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker mac beta 18 (build 9996)

**Steps to reproduce the issue:**
1. Clone the `master` branch of this repo: https://github.com/nkovacs/docker-mac-bug
2. Run test.sh

**Describe the results you received:**
No inotify events are received

**Describe the results you expected:**
Inotify events should be received for all three files.

**Additional information you deem important (e.g. issue happens only occasionally):**
The bug does not occur if `/etc/go-cron` is changed to `/etc/gocron`, as can be seen in the `nodash` branch.

**Comment by justincormack** [comment] 2016-07-12 10:13
cc @dsheets

**Comment by dsheets** [comment] 2016-07-29 12:59
I confirm I can reproduce this and have started tracking down the cause.

**Comment by dsheets** [comment] 2016-08-03 16:17
Beta 21.1 has been released which should resolve this issue.

**Comment by thaJeztah** [comment] 2016-08-03 17:24
Thanks @dsheets I'll close this issue, but @nkovacs would be good if you could confirm it's resolved for you

**Closed by thaJeztah** 2016-08-03 17:24 UTC
Labels: kind/bug, platform/desktop, area/volumes

**Comment by nkovacs** [comment] 2016-08-04 07:57
Confirmed, thanks.

**Comment by thaJeztah** [comment] 2016-08-04 08:02
:dancer:

**Comment by mxl** [comment] 2016-11-17 12:33
@nkovacs I have run `test.sh` from https://github.com/nkovacs/docker-mac-bug and it prints only:

> app_1  | starting inotifywait
> app_1  | Setting up watches.
> app_1  | Watches established.

Could you test it too?

I'm asking because I'm having https://github.com/docker/docker/issues/24503 (mounted `node_modules` directory is becoming empty after I run `gulp`). 
I'm using Docker for Mac 1.12.3-beta30 (13798) on macOS Sierra 10.12.2 Beta (16C48b).

**Comment by thaJeztah** [comment] 2016-11-17 12:39
@mxl @nkovacs if there is a regression, we now have a dedicated issue tracker for docker for mac, so please open a new issue there; https://github.com/docker/for-mac/issues

**Comment by nkovacs** [comment] 2016-11-17 12:58
I can't reproduce it with 1.12.3-beta30 (13798) on Sierra 10.12.1 with the master branch of my repo. I get MODIFY events for all three files.

**Comment by mxl** [comment] 2016-11-17 13:25
@nkovacs I reseted Docker for Mac to defaults and then installed 1.12.3-beta30.1 (13946) update. The issue has gone.
