### ISSUE TITLE
Docker image rm sometimes leaves layers behind

### ISSUE THREAD

**Issue by davidmatson** [moby/moby#40785] opened 2020-04-06 17:33 UTC
Moving from docker/for-win#1580.

### Expected behavior
Layers used only by this image are removed.

### Actual behavior
Layers used only by this image are still stored in C:\ProgramData\Docker\windowsfilter\ and C:\ProgramData\Docker\image\windowsfilter\layerdb\sha256\.

In this case, the layers were deleted from C:\ProgramData\Docker\image\windowsfilter\distribution\diffid-by-digest\sha256 and C:\ProgramData\Docker\image\windowsfilter\distribution\v2metadata-by-diffid\sha256
but I have seen cases where these directories are also not cleaned up.

### Information
I'm running Docker Community Edition 17.12.0-ce-win47 (15139) on Windows 10 1709.
Diagnostic ID: DEF60AD9-E6D5-4F8D-B336-CCE3B89FD713/2018-01-18_12-02-31

### Steps to reproduce the behavior

  1. docker run on an image, and then exit the container.
  2. docker container prune -f
  3. Immediately do docker image rm <imageid> (of the image run in step 1)

The following error message appears, and the folders mentioned above are not cleaned up (and apparently there is no way to clean up other than manually deleted the orphaned folders):
Error response from daemon: rename C:\ProgramData\Docker\windowsfilter\064796a25f21d50a78c0960827128160ffc39bc82ddb9b195da42338aa5ee255 C:\ProgramData\Docker\windowsfilter\064796a25f21d50a78c0960827128160ffc39bc82ddb9b195da42338aa5ee255-removing: Access is denied.

Should there at least be some kind of command to find orphaned layers and delete them?

**Comment by TinoDidriksen** [comment] 2020-05-02 22:43
Just hit this on Linux (Ubuntu 20.04, kernel 5.4.0, docker 19.03.8, btrfs, using buildkit) when cleaning up from issue #40890 :
````
# docker rmi test
Untagged: test:latest
Deleted: sha256:c21a0d6ea8af5a46dcbae6fe911e3e4ceec323e661cb7c3e5e22c2fafa0b1347

# docker rmi test2
Untagged: test2:latest
Deleted: sha256:54dca18ee1c192ecbd31ef026575f8ae65f677e7b9ac856dd8c83c7e3cf32b2f

# docker system prune -f
Deleted build cache objects:
sha256:1e0c0cabe0bcfdf61a5bccd927c87b3ea92ffa70e40d1dd2fd56ba230f32eec2
7n2whc330qu5nrsk9r9a83avz
sbffgmapz59gg2boda3fauqa1
9vm45wjfqyi6bsbj1pjxpbr1s
vn6bztymovhoov3y318l4jmpn
sha256:c2cf4f20d331942ab5347db7660878d2a45ec4fb554c81920f4f4cf80afca932

Total reclaimed space: 3.34GB

# ll */random.gb
-rw-r--r-- 1 root root 1073741824 May  2 22:15 sfhqyffn0r97a0dzlh7izzdka/random.gb
````

Nothing in `docker images -a` could possibly reference the orphan subvolume `sfhqyffn0r97a0dzlh7izzdka` - all remaining images are from several days ago, and not with buildkit.

**Comment by thaJeztah** [comment] 2020-05-03 00:42
The issue with btrfs is likely not related to this ticket, but there are some existing issues about disk exhaustion with the btrfs driver; https://github.com/moby/moby/labels/area%2Fstorage%2Fbtrfs

**Comment by neersighted** [comment] 2023-02-03 21:15
Closing as a duplicate of #42521, which has much more discussion of the current state here.

**Closed by neersighted** 2023-02-03 21:15 UTC
Labels: platform/windows, area/images
