### ISSUE TITLE
docker failed to connect containerd.sock

### ISSUE THREAD

**Issue by nzb15555196162** [moby/moby#48052] opened 2024-06-25 06:31 UTC
### Description

Due to an abnormal power outage and start of centos7, the docker service failed to start,query Docker logs
![1](https://github.com/moby/moby/assets/18350673/92f75a88-401d-4f5d-b64e-bc01781217ba)

### Reproduce

abnormal power outage and start of centos7

### Expected behavior

docker service starts normally

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 35
  Running: 0
  Paused: 0
  Stopped: 35
 Images: 218
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.49GiB
 Name: kubesphere-kube-key-node1
 ID: Z4JI:SDOU:4XTR:JWDB:6EWB:LUI4:SS3G:ZUX5:XFHM:5TC4:4DN3:DGUW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://b4iilr3m.mirror.aliyuncs.com/
  https://ustc-edu-cn.mirror.aliyuncs.com/
  https://ccr.ccs.tencentyun.com/
  https://docker.m.daocloud.io/
  https://dockerproxy.com/
  https://docker.mirrors.ustc.edu.cn/
  https://mirror.baidubce.com/
  https://docker.nju.edu.cn/
 Live Restore Enabled: false
```

### Additional Info

i have seen other issues where the solution is to reinstall docker. In my case, docker is used as the CNI of kubernetes. Reinstallation affects the following points.
1. the version adaptation problem between docker and kubernetes may require reinstallation of kubernetes.
2. kubernetes is running the original business, so reinstallation has a greater impact

**Comment by vvoland** [comment] 2024-06-25 09:37
In this case the failure to connect the containerd socket is most likely caused by the containerd daemon not starting up at all.
Looking at the containerd logs might provide us with more useful information.

**Comment by nzb15555196162** [comment] 2024-06-29 17:13
> In this case the failure to connect the containerd socket is most likely caused by the containerd daemon not starting up at all. Looking at the containerd logs might provide us with more useful information.

Unfortunately, in order to quickly restore the cluster, we performed the following operations
1 Execute yum -y update
2 Then yum start docker
3 At this time, docker restarted successfully, but all containers no longer existed. We had to reinstall the kubernetes cluster and restore all containers, so all the on-site logs were gone. It was a pity that we could not find the specific cause and a better solution to restore the cluster

**Comment by nzb15555196162** [comment] 2024-06-29 17:20
So I'm closing this issue for now.

**Comment by nzb15555196162** [comment] 2024-07-04 10:48
Sorry to reopen this issue again, because i encountered this kind of problem again today, this time I want to find out the specific cause.
![2](https://github.com/moby/moby/assets/18350673/b6044256-c086-411d-a09f-028dfbdb1ac9)

**Comment by vvoland** [comment] 2024-07-04 10:57
Looks like the containerd bboltdb got corrupted. If it happened after a power outage like you mentioned in the original report, it's highly likely to be the cause of corruption.

Let me close the issue as it's not actionable on our end. If you think that the issue is unrelated to the data corruption after power outage, please file an issue in the containerd issue tracker: https://github.com/containerd/containerd/issues

**Closed by vvoland** 2024-07-04 10:57 UTC
Labels: kind/bug, version/20.10

**Comment by nzb15555196162** [comment] 2024-07-04 12:14
> Looks like the containerd bboltdb got corrupted. If it happened after a power outage like you mentioned in the original report, it's highly likely to be the cause of corruption.
> 
> Let me close the issue as it's not actionable on our end. If you think that the issue is unrelated to the data corruption after power outage, please file an issue in the containerd issue tracker: https://github.com/containerd/containerd/issues

ok, thanks

**Comment by thaJeztah** [comment] 2024-07-04 20:51
@nzb15555196162 note that the versions of docker, containerd, runc and CentOS that you're running are all EOL and no longer maintained; if possible I'd also recommend looking at upgrading your systems (but make sure to test before you deploy to any critical systems)

**Comment by Iceber** [comment] 2024-07-09 06:48
> Sorry to reopen this issue again, because i encountered this kind of problem again today, this time I want to find out the specific cause. ![2](https://private-user-images.githubusercontent.com/18350673/345803319-b6044256-c086-411d-a09f-028dfbdb1ac9.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDY0NzUsIm5iZiI6MTcyMDUwNjE3NSwicGF0aCI6Ii8xODM1MDY3My8zNDU4MDMzMTktYjYwNDQyNTYtYzA4Ni00MTFkLWEwOWYtMDI4ZGZiZGIxYWM5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA2MjI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MWRhNmY1OTRiMzc4OWM2MDkyMWJmYTA5MjYyYTQyNGQ5OTQ3MTU0YzFlODJjMDkyNjU5NGU1YzM5ODczZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0XFI5ABbQTWxepIVN2bxGugn5MpTOeFgCFjAya7WWo)

Like @vvoland  said, there is a high probability that the bboltdb data is corrupted due to a power outage. Is this screenshot reproduced using the power outage?
