### ISSUE TITLE
ARG not supported in COPY --from=base:${VALUE}

### ISSUE THREAD

**Issue by ericberberich** [moby/moby#36986] opened 2018-05-02 20:43 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue (F7593F70-B457-4953-9423-FF48CA69F581)

**Description**

Using 

```COPY --from=base:${VERSION} /dir/ /dir/```

**Describe the results you received:**

Error message
`invalid from flag value base:${VERSION}: invalid reference format`

**Describe the results you expected:**

A correct copy from `base:latest` if build with `--build-arg VERSION=latest`

### Information

Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)

F7593F70-B457-4953-9423-FF48CA69F581

**Comment by dimaspivak** [comment] 2018-05-04 01:13
This is issue is a duplicate of #35018.

**Closed** 2018-05-04 09:06 UTC
Labels: platform/desktop
