### ISSUE TITLE
Proposal: multi-stage docker build with --rm flag should remove builder container

### ISSUE THREAD

**Issue by DavidObando** [moby/moby#34513] opened 2017-08-15 01:32 UTC
**Description**

The help message I get after running `docker build --help` says, among other things:
```
      --rm                         Remove intermediate containers after a
                                   successful build (default true)
```
However, when I run a multi-stage build with the `--rm` flag I see the "builder" container remains in my list of containers.

**Steps to reproduce the issue:**
You can reproduce with the following simple files:
### Dockerfile
```Dockerfile
FROM golang:1.8 as vpbuilder
WORKDIR /go/src/vp
COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -a -o vp .

FROM alpine:3.4
WORKDIR /vp/
COPY --from=vpbuilder /go/src/vp/vp .
ENTRYPOINT ./vp
```

### main.go
```go
package main

import (
        "fmt"
)

func main() {
        fmt.Println("Hello, bug report!")
}
```

Then, execute the following command:
```bash
docker build --rm -t vp1 .
```

**Describe the results you received:**
After doing this, I see the following output when listing the images in my machine:
```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vp1                 latest              eb50ea43dd26        29 seconds ago      6.36MB
<none>              <none>              23fb11c60f86        31 seconds ago      700MB
golang              1.8                 6ce094895555        2 weeks ago         699MB
alpine              3.4                 f64255f97787        6 weeks ago         4.81MB
```
Note the second container that's listed doesnt' have a repository name or a tag, and is the "builder" container that I used in my Dockerfile.

**Describe the results you expected:**
Given that I called docker build with the `--rm` flag, I expected it to remove intermediate containers that may have been created in the process.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.8.0-59-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.72GiB
Name: daobando-u1
ID: S4FY:DU3O:TGZJ:XGVH:CQAO:TAW7:C3YS:KGYU:E2VD:RTWO:ZKXN:7JQP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-09-25 17:19
> Note the second container that's listed doesnt' have a repository name or a tag, and is the "builder" container that I used in my Dockerfile.

That's not what the `--rm` flag is for; the `--rm` flag (which is the default on `docker build`) removes intermediate _containers_ used during build. Each instruction (e.g., `RUN`) in a dockerfile starts a new container, after the instruction completes, the container exits, and is committed to an image. Then the _container_ is removed.

The _images_ you see are the _images_ that are the end result of a build-stage; I _think_ these are needed to make sure the build-cache of all the steps are preserved, but @tonistiigi may be able to tell more.

**Comment by thaJeztah** [comment] 2017-10-24 10:40
Closing this issue because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2017-10-24 10:40 UTC
Labels: area/builder, version/17.06

**Comment by alexindigo** [comment] 2017-11-02 17:17
@thaJeztah In many case those build containers are undesirable and there is no straight forward to track them down in delete in shared environments. Would be very helpful to have some kind flag to clean them up. Especially that usually that intermediate images are the heavy ones with all the build/test tooling. Or maybe allow to tag them so it would be easier to perform house cleaning.

Thank you.

**Comment by thaJeztah** [comment] 2017-11-02 17:21
Have you tried `docker image prune` ?

**Comment by alexindigo** [comment] 2017-11-02 17:39
It removes "all dangling images", so in shared environments (like Jenkins slave) it's more akin to shooting oneself in the foot. :)

**Comment by andreimcristof** [comment] 2018-01-04 10:59
A vote from me as well for this, would be useful to have e.g. something maybe like declaring in the `FROM` statement as intermediate, then a flag on docker build to remove intermediate images.

**Comment by B-Virtual** [comment] 2018-03-14 13:23
It would be very useful to have such a feature, when building I also create a 2GB intermediate image that has no use after I copied all the build output. So removing (or tagging) it with some sort of statement would be helpful.

**Comment by arcanericky** [comment] 2018-03-28 15:25
This would be useful to me as well. We don't use multi-stage builds in our shared / automated build environment because of this.

I agree, it's not a bug, but we could consider it a feature request.

**Comment by 7oku** [comment] 2018-05-03 10:03
Voting +1, as the build containers keep stacking up :/ In our example it's quite a lot compared to the resulting final image:

```
REPOSITORY                                                      TAG                                        IMAGE ID            CREATED             SIZE
finalimage                                                      latest                                     a9d4e932f24d        9 seconds ago       16.4MB
<none>                                                          <none>                                     88f0820e5b12        3 minutes ago       845MB
<none>                                                          <none>                                     8292c6c55f03        9 minutes ago       845MB
<none>                                                          <none>                                     f0f4a25fd5aa        10 minutes ago      795MB

```

**Comment by thaJeztah** [comment] 2018-05-03 13:48
> It removes "all dangling images"

It removes the untagged (intermediate) images, which are the images being discussed here

> in shared environments (like Jenkins slave) it's more akin to shooting oneself in the foot

Yes, in cases where other builds would use these images as cache, there could be situations where there's a race condition. Removing the image as part of the build would have the same race condition though.

Note that buildkit (which will be integrated; work is in progress for that) uses a different caching mechanism, so would not produce these intermediate images for caching.

> when building I also create a 2GB intermediate image that has no use after I copied all the build output.

If you are repeating the build, or have other builds that share the same build-steps; those images are used for the build-cache, so they definitely have a purpose.

If you don't want caching; `docker image prune` after build completes would clean them up.

**Comment by Robot1que** [comment] 2018-05-06 14:46
In all examples I've seen so far (books, articles, official documentation) for some reason multi-staged build is used to build source code inside build image and then copy the output into resulting image. The thing I do not understand - why do I need to create a new image when building the code? What I actually need is to run build commands inside a build image container to get the output and then stop and remove this container. Which makes me think that multi-staged build is not what I want.

So my conclusion is that the most optimal way to do builds and create image with app is to run a script that would run build image and mount a volume that contains the code, build it and output files into this volume so that it is preserved after container is removed. Then build an image that has a copy of an output. Does my logic make sense or do I miss something fundamental?

P.S.: I'm new to Docker.

**Comment by snehasankavaram** [comment] 2018-05-09 01:38
I agree that this should be a feature- the examples I've seen that discuss building lightweight docker containers for go binaries have an initial builder step with a large image and then transfer that binary to another smaller image (including the one in the [documentation](https://docs.docker.com/v17.09/engine/userguide/eng-image/multistage-build/)).  If this is a valid use case, it seems reasonable that there should then be a way to mark the larger container to be deleted at the end of the Dockerfile, since it is only being used as an intermediate step.

**Comment by B-Virtual** [comment] 2018-05-16 09:48
@ZachEddy that is a nice approach. That does the trick for me. I finally get these ghosts out of my TeamCity and dev machine in an automated way.

For Windows users that would be:
`for /F "tokens=*" %i in ('docker images -q --filter "label=stage=intermediate"') do docker rmi -f %i`

**Comment by thaJeztah** [comment] 2018-05-16 10:11
@B-Virtual instead of `docker rmi -f` (which will also remove images that are in use), you can use the [`--filter` option on `docker image prune`](https://docs.docker.com/engine/reference/commandline/image_prune/#filtering);

```
docker image prune --filter label=stage=intermediate
```
