### ISSUE TITLE
Service update intermittently fails with error 137, stuck on task 0 of n

### ISSUE THREAD

**Issue by george-freebirdrides** [moby/moby#35406] opened 2017-11-04 00:04 UTC
So we intermittently get these sorts of errors out of our CICD jobs in Circle where a simple rerun of the deployment will succeed, with no changes to the cluster, machines, etc.

```
Updating API service
hapi-fb4e7ede3b
overall progress: 0 out of 1 tasks
1/1:  
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
... snip...
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
service update paused: update paused due to failure or early termination of task mlp8buypzqlh6tzbno4m3nfj9
```

When looking at the tasks in the service, we'll see failures with non-zero exit (137), but no additional information. I've seen 137 referenced as a potential OOM termination, but we're sized for the necessary memory of the app and telemetry confirms we're within those boundaries.

Has anyone else seen this? Workarounds?

**Comment by thaJeztah** [comment] 2017-11-04 01:43
Exit code 137, is basically `kill -9` (128 + 9 = 137). This can either be if the process was killed by the kernel, due to an OOM, but also if docker attempted to stop the container (`SIGTERM`), but the container didn't stop within 10 seconds, after which the container is killed forcibly (`SIGKILL`)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-04 01:43 UTC

**Comment by george-freebirdrides** [comment] 2017-11-04 03:40
I believe you are incorrect - the 137 being a signal for kill -9 or OOM I'm already aware of. What is different is that these are subsequent calls with no changes to the cluster, the nodes or the available resources, which result in random success or failure, or just hang for significant periods of time on 0 of n # tasks. I am not asking for support - I am reporting a bug.
