### ISSUE TITLE
docker daemon running but docker.sock fails to communicate due to FD limit reached

### ISSUE THREAD

**Issue by unvaare** [moby/moby#42686] opened 2021-07-27 20:30 UTC
**Description**
I am facing this weird issue, that docker becomes unresponsive but the containers keep on running and none of the docker commands work any more and I keep getting: 
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

The issue gets resolved when I restart the docker service but comes back again after 24 hours. From the journalctl logs I can see when this happens, I frequently get 
```
level=error msg="stream copy error: reading from a closed fifo"
level=error msg="stream copy error: reading from a closed fifo"
level=warning msg="Health check for container b5939396784355880b46a32f53d0c966e7fd1cb30518b07fcb683fc4d1324198 error: context deadline exceeded: unknown"
dockerd[58015]: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 5ms

```
Not sure if the FD limit that's causing the issues, as i tried to increase the FD limit but still facing the same issue. 

**Output of `docker version`:**

```
Docker version 19.03.15, build 99e3ed8919
```

**Output of `docker info`:**

```
Server:
- Containers: 149
  Running: 70
  Paused: 0
  Stopped: 79
- Server Version: 19.03.15
- Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
- Logging Driver: json-file
- Cgroup Driver: cgroupfs
- Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
- Swarm: inactive
- Runtimes: runc
- Default Runtime: runc
- Init Binary: docker-init
- containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
- runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
- init version: fec3683
- Security Options:
  seccomp
   Profile: default
- Kernel Version: 3.10.0-1127.19.1.el7.x86_64
- Operating System: Red Hat Enterprise Linux
- OSType: linux
- Architecture: x86_64
- CPUs: 88
- Total Memory: 754.3GiB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2021-07-27 21:29
Looks like you're running an older version of the containerd.io package (1.4.3), and I recall some issues with older versions. Do you have a test-system on which you're able to reproduce, and that you can try updating on? Are you still seeing this on a current version of the containerd.io package (1.4.7) ?

Note that Docker 19.03 won't receive further updates, so if possible, I'd recommend updating to 20.10.x as well

**Comment by unvaare** [comment] 2021-07-28 01:02
> 
> 
> Looks like you're running an older version of the containerd.io package (1.4.3), and I recall some issues with older versions. Do you have a test-system on which you're able to reproduce, and that you can try updating on? Are you still seeing this on a current version of the containerd.io package (1.4.7) ?
> 
> Note that Docker 19.03 won't receive further updates, so if possible, I'd recommend updating to 20.10.x as well

Yes the containerd version is bit older as you identified:
containerd --version
containerd containerd.io 1.4.3 269548fa27e0089a8b8278fc4fc781d7f65a939b

is this a known issue that docker.sock gets chocked (may be due to file descriptors) after a 24 or so hours, we have exactly same version deployed on another server and it's working just fine there.

**Comment by thaJeztah** [comment] 2021-07-28 07:51
> is this a known issue that docker.sock gets chocked (may be due to file descriptors) after a 24 or so hours, we have exactly same version deployed on another server and it's working just fine there.

Not sure if there's a specific issue to point to (and/or if there's still an issue in specific setups/situations).

From your error, it looks like you're using health checks; each health check will perform a `docker exec` to check the health-status. It's possible that something causes the health-check to not terminate, causing a socket connection to remain open.

One bug in containerd 1.4.3 was related to wether or not debug logs were enabled, causing containerd to hang, which was fixed in [1.4.4](https://github.com/containerd/containerd/releases/tag/v1.4.4) through https://github.com/containerd/containerd/pull/4906

We've also had reports where some monitoring solutions didn't terminate connections, causing them to keep connections open (e.g. https://github.com/moby/moby/issues/22221#issuecomment-409327573)

**Comment by unvaare** [comment] 2021-07-29 19:29
Seems like that's the issue, I have been using grafana based monitoring tool to check the containers stats with some additional logging and it's making persistent connection through docker.sock and since the connection are not being closed, that could be the reason for socket running out FDs

**Comment by thaJeztah** [comment] 2021-07-29 19:52
Ah! That sounds a plausible reason for the issue, yes 👍 


Let me close this ticket, based on the above, but feel free to continue the conversation

**Closed by thaJeztah** 2021-07-29 19:52 UTC
Labels: version/19.03
