### ISSUE TITLE
goroutine/fd leak still present in 27.0.3

### ISSUE THREAD

**Issue by Yinette** [moby/moby#48236] opened 2024-07-25 06:27 UTC
### Description

Noticed issue #45052 while troubleshooting a system crash, and it seems to be the same issue in 27.0.3, however I could be wrong. I've collected pprof out of the running dockerd with about 5000~ threads, and it seems to be at least related to the linked issue.

To dump the goroutines i ran `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine --output pprof-goroutines-dockerd.gz`

### Reproduce

We have a set of containers that collect a "device" from a redis to query, if all "devices" have a container assigned to process their data, the surplus containers will exit gracefully with `0` and be restarted to repeat the process.

In this case, dockerd will exponentially spawn threads under the parent process until it reaches the max-threads limit in the Kernel, causing it to crash.

### Expected behavior

dockerd should not reach kernel process limits and crash.

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:29 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:29 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 19
  Running: 19
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-131-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.51GiB
 Name: [redacted]
 ID: 702f8011-d0a1-44ce-9087-f5ccf6a0b9f8
 Docker Root Dir: /usr/local/[redacted]/var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Additional Info

I was able to pull pprof for goroutines out of dockerd while it was running and obtain information about what it's getting stuck on:
![profile001](https://github.com/user-attachments/assets/73669766-b59c-486a-9dfd-2245dc32feb1)

```
(pprof) text
Showing nodes accounting for 10719, 100% of 10721 total
Dropped 130 nodes (cum <= 53)
Showing top 10 nodes out of 24
      flat  flat%   sum%        cum   cum%
      5487 51.18% 51.18%       5487 51.18%  runtime.gopark
      5232 48.80%   100%       5232 48.80%  syscall.Syscall6
         0     0%   100%       5220 48.69%  github.com/docker/docker/api/server/router/container.notifyClosed
         0     0%   100%       5220 48.69%  github.com/docker/docker/api/server/router/container.notifyClosed.func1
         0     0%   100%       5220 48.69%  github.com/docker/docker/daemon.(*Daemon).containerAttach.func2
         0     0%   100%       5220 48.69%  github.com/docker/docker/internal/unix_noeintr.EpollWait
         0     0%   100%         76  0.71%  github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read
         0     0%   100%         76  0.71%  github.com/docker/docker/pkg/pools.Copy
         0     0%   100%       5220 48.69%  golang.org/x/sys/unix.EpollWait
         0     0%   100%       5220 48.69%  internal/poll.(*FD).RawControl
```

**Comment by thaJeztah** [comment] 2024-07-25 06:32
did you mean to write v27.0.3? (https://github.com/moby/moby/pull/45052 is included in the v27.0 release; it has not been backported to older release branches. v24.0 is no longer maintained, so is unlikely to receive that patch).

**Comment by Yinette** [comment] 2024-07-25 06:32
Ah yes! My bad! Have been working on this for a few hours now. Will fix!

**Comment by thaJeztah** [comment] 2024-07-25 06:47
No worries; wanted to be sure 🤗 I started writing "but the patch isn't in 24.0.3" and then noticed your `docker version` output showed v27.0.3 😂

**Comment by thaJeztah** [comment] 2024-07-25 06:48
cc @cpuguy83 @vvoland @corhere

**Comment by cpuguy83** [comment] 2024-07-25 14:12
Are you sure you've closed the connection? If there's a ton of "notifyClosed" goroutines running then almost certainly it's because the client connections are still open.

Can you give a minimal reproduction?

**Comment by Yinette** [comment] 2024-07-25 22:41
Hey @cpuguy83, yes of course. I'll put together some reproduction steps for you. I've had to be vague due to the nature of the project that this runs, but will reproduce on a fresh system and put together the steps for you to try.

When you say client connections are still open, what in your experience would be doing that? From my very limited understanding of the API (from a cursory read over the source yesterday trying to troubleshoot this) it's related to what the containers are outputting e.g. `/dev/stdin`, `/dev/stderr`? Please correct my understanding if it's incorrect. (I'm a systems engineer not a go developer! Please accept my apologies!)

But with the system live, I can do further digging to see if I can find what could be keeping these open. Just gotta know what to look for :) Anything helps!

**Comment by cpuguy83** [comment] 2024-07-25 22:57
This would be an API user attached to the container stdio streams. The "client" is the API user.

**Comment by Yinette** [comment] 2024-07-25 23:02
Understood, I think I might have a lead on that path. The containers are using the `json-file` logging driver, I'll investigate down that way and see if that is being handled correctly by the compositor.

**Comment by Yinette** [comment] 2024-07-26 00:02
I think you're right... I've managed to match up individual socket fds between dockerd and the docker-compose process, which must be keeping it open after the container has exited.

The numbers line up:
```
# ll /proc/`pgrep dockerd`/fd | grep 'socket' | wc -l
8152

# ll /proc/`pgrep docker-compose`/fd | grep 'socket' | wc -l
8094
```

I'll collect some more information, and if it's not something we're doing wrong, I can open up an issue over with the compose plugin.

Thanks for your help!

**Comment by Yinette** [comment] 2024-07-26 00:33
Alright, I've got an update. I restarted the docker-compose service, and can see that the sockets counts are now sane again:

```
# ll /proc/`pgrep dockerd`/fd | grep 'socket' | wc -l
92

# ll /proc/`pgrep docker-compose`/fd | grep 'socket' | wc -l
36
```

However, dockerd still has its threads open:
```
# ll /proc/`pgrep dockerd`/task | wc -l
8401
```

Though interestingly, our ratio has changed in the goroutine pprof:
```
(pprof) top
Showing nodes accounting for 317, 100% of 317 total
Showing top 10 nodes out of 158
      flat  flat%   sum%        cum   cum%
       272 85.80% 85.80%        272 85.80%  runtime.gopark
        42 13.25% 99.05%         42 13.25%  syscall.Syscall6
```

I'll try replicate this separately to this system and provide you the steps to give it a try.

**Comment by Yinette** [comment] 2024-07-26 01:45
Was able to reproduce this on a separate VM, on direct observation, it does not appear that the threads leak on a 1:1 relationship with a container stopping/restarting, I think there is some thread recycling on dockerd's part until docker-compose exhausts that and new threads need to be spun up.

Reproduction steps:

1. create `docker-compose.yaml`
```yaml
---
services:
  occupied:
    image: container-used:latest
    logging:
       driver: "json-file"
       options:
         max-file: "5"
         max-size: "30m"
  
  surplus:
    restart: unless-stopped
    image: container-surplus:latest
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "30m"
```
2. create Dockerfile
```Dockerfile
FROM alpine:latest AS occupied

CMD ["sleep", "3600"]

FROM alpine:latest AS surplus

CMD ["sleep", "10"]
```

3. build images
```shell
docker build --target occupied -t container-used:latest .
docker build --target surplus -t container-surplus:latest .
```

4. start project
```shell
docker compose -f docker-compose.yaml --scale occupied=8 --scale surplus=2
```

5. concurrently with 4, observe total number of tasks/threads under dockerd:
```shell
watch -n1 "ls /proc/$DOCKERD_PID/task | wc -l"
```

6. concurrently with 4, observe unix socket fds under the `docker-compose` pid:
```shell
watch -n1 "lsof -p `pgrep docker-compose` | grep unix"
```

You will observe the following:
 - Docker compose will restart the exiting containers as they gracefully close.
 - In step 5, you will see the total number of threads under dockerd will begin to rise.
 - in step 6, you will see more unix sockets being added to the fd list for docker-compose process.
 - If you stop the docker-compose process, dockerd will keep its threads open.

This appears to be more of a docker-compose issue, but can pose an issue to dockerd if left unchecked, however form observation of this in a controlled environment, it feels like there's a level of goroutine recycling? I'm unsure if this behaviour constitutes a problem with dockerd, since dockerd is simply responding to demand from a client.

**Comment by cpuguy83** [comment] 2024-07-29 16:35
I'm not familiar with the compose codebase.
I did peek through it a bit, though.
It does look like they are relying on process exit to close file descriptors (and as such propagating the close to the daemon).
If compose is doing restarts in-process then that could be an issue.

Based on the attached goroutine dump, as best as I can tell, the client is keeping the connection alive, though admittedly there could be other stuff going on its hard to tell from a just a goroutine dump.

**Comment by Yinette** [comment] 2024-07-30 05:17
Thanks for your insight :) I'll continue to follow this over in the compose project, for now I'll close this as I can re-open as a new issue since we now have a bit more understanding of what's causing the thread leak.

**Comment by Yinette** [comment] 2024-09-06 01:42
Been over at the compose project, as they say, it's using the docker's client API to perform its tasks. Is it possible to have someone follow the steps I've outlined in the original report to investigate why the sockets are being held open and keep being spawned? @thaJeztah

If I can at least have someone who understands the codebase explain what's going on, if it's not an issue with moby, I can open a bug report in the appropriate place. I'm unfortunately at my knowledge limit with golang.

I'm also wondering if this is similar to #48144 however that seems to be a memory leak, rather than thread leak.

**Comment by thaJeztah** [comment] 2024-09-06 13:54
> Docker compose will restart the exiting containers as they gracefully close.

One thing worth noting there is that restarting probably is not handled by compose itself for these, but the engine will restart the container if it has a restart-policy set. If the container has a auto-remove set (similar to `docker run --rm ....`), the container would be deleted when it exits.


Both `docker compose` and the `docker run` / `docker exec` use the same API and same code, but for `docker run` / `docker exec`, the CLI itself would only live for the duration of the command; for `docker compose up`, compose would continue running, so for sure there's a higher likelyhood for runaway goroutines, which could still be a bug somewhere in the client code (but not rearing its head on a "short-lived" CLI), or it could be somewhere in the compose code, as it does indeed has various code-paths that watch for events and loop through containers.

I'm not very familiar with the compose code; I did have a quick peek as well, but there's quite some complexity involved, so not _impossible_ for it to somewhere handle an event, then create a new "attach" without terminating the previous?


cc @laurazard (I know you were looking into some things around re-attaching log streams, as well as handling exit-events, so in case you have any ideas from the top of your head).

**Comment by Yinette** [comment] 2024-09-09 01:34
Thank you! And yeah, from discussion over in compose project, it does appear to be only using the client API for docker and not anything special or custom beyond it's own handling.

If it helps, I notice this issue really only appears if you run your compose project *not* in daemon mode (`-d`), i.e. if you were running compose out of a systemd unit which was logging into journal from stdin/stderr of the project's containers.

My gut feeling is somewhere along the line a signal isn't handled properly, or sent properly leading to a pipe to remain open or in a semi-dormant state. I'm doing my best to try and isolate the behaviour with the available debugging tools, but my knowledge is quite limited in that area.

Appreciate all the help so far on this, happy to provide more details or dumps as I have this problem isolated into a purpose-made environment to try and track this down.

**Comment by laurazard** [comment] 2024-09-10 10:31
I can take a second to investigate/figure out if the fault lies in the Compose codebase or not. @Yinette can you share more about:

> If it helps, I notice this issue really only appears if you run your compose project not in daemon mode (-d), i.e. if you were running compose out of a systemd unit which was logging into journal from stdin/stderr of the project's containers.

FYI, `-d` for Compose does not mean stand for `--daemon` – it stands for `--detach`, and what it does is tell Compose to, instead of staying up and attached to the containers, instead do whatever it's told (`run`/`up`/`start`/etc.) and then exit.

If this only happens when running Compose without `-d`, then in this scenario Compose is still running/attached to the containers. I know Compose has some logic to reattach to running containers when they exit, which calls the daemon and likely runs into that `github.com/docker/docker/daemon.(*Daemon).containerAttach.func2` in the goroutine dump you've provided. I wonder if Compose is calling this a bunch without closing the previous streams for some case.

**Comment by laurazard** [comment] 2024-09-10 10:45
FWIW, this seems to happen regardless of `"json-file"` logging driver – I was considering that we might be handling this incorrectly in the engine, but the fact that this happens regardless points at that not being the case. On the other hand, I've also seen:

> However, dockerd still has its threads open:
> ```console
> $ ll /proc/`pgrep dockerd`/task | wc -l
> 8401
> ```

Which would indicate we're doing something wrong on this end too.

**Comment by laurazard** [comment] 2024-09-10 13:53
Right, that's true. Anyway, closing the issue here since this should be solved by https://github.com/docker/compose/pull/12112 and was being tracked over in https://github.com/docker/compose/issues/12023 regardless.

**Comment by laurazard** [comment] 2024-09-10 13:54
Thanks for all the information/digging in you did @Yinette!

**Closed by laurazard** 2024-09-10 13:53 UTC
Labels: status/0-triage, status/more-info-needed, kind/bug, version/27.0

**Comment by thaJeztah** [comment] 2024-09-10 14:02
Ah, nice! Thanks @laurazard !!

**Comment by Yinette** [comment] 2024-09-12 03:26
Thanks so much @laurazard ! This is a big headache off my plate :D
