### ISSUE TITLE
ISSUE: Can't stop containers (sometimes but often enough to test)

### ISSUE THREAD

**Issue by beetree** [moby/moby#19030] opened 2016-01-02 07:54 UTC
I run a cluster where docker containers _sometimes_ become "unstoppable". It happens a few times per day across the cluster, and when it happens the only solution is to stop the docker daemon, restart the host machine and then start the docker daemon again.

A regular stop command does not do the job (even when waiting for up to an hour):

```
# time docker stop --time=1 950677e2317f
^C
real    0m13.508s
user    0m0.036s
sys     0m0.008s
```

The daemon seems to properly escalate the stop of the container:

```
# journalctl -fu docker.service
-- Logs begin at Fri 2015-12-11 15:40:55 CET. --
Dec 31 23:30:33 m3561.contabo.host docker[9988]: time="2015-12-31T23:30:33.164731953+01:00" level=info msg="POST /v1.21/containers/950677e2317f/stop?t=1"
Dec 31 23:30:34 m3561.contabo.host docker[9988]: time="2015-12-31T23:30:34.165531990+01:00" level=info msg="Container 950677e2317fcd2403ef5b5ffad37204e880136e91f76b0a8682e04a93e80942 failed to exit within 1 seconds of SIGTERM - using the force"
Dec 31 23:30:44 m3561.contabo.host docker[9988]: time="2015-12-31T23:30:44.165954266+01:00"
```

The process that seems to be blocking the container stop can be seen on the host machine:

```
# ps aux | grep [1]1991
root     11991 84.3  0.0   5836   132 ?        R    Dec30 1300:19 bash -c (echo stop > /tmp/minecraft &)
# top -b | grep [1]1991
11991 root      20   0    5836    132     20 R  89.5  0.0   1300:29 bash
```

Please note that it is not a [Z]ombie process but rather a [R]unning process. Also note that it's consuming 84% of the cpu so it is actively doing _something_ and just leaving it is not an option.

Some base information about my setup:

```
# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

# docker info
Containers: 189
Images: 322
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 700
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-19-generic
Operating System: Ubuntu 15.10
CPUs: 24
Total Memory: 125.8 GiB
Name: m3561.contabo.host
ID: ZM2Q:RA6Q:E4NM:5Q2Q:R7E4:BFPQ:EEVK:7MEO:YRH6:SVS6:RIHA:3I2K

# uname -a
Linux m3561.contabo.host 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Worth noting is that stopping the docker daemon does not solve the issue as the process is still running also after the daemon is stopped. This may indicate that the issue is not related to Docker but rather to the kernel.

I've seen 20+ of these "stuck processes" and the only "theme" I have noticed is that it seems that they always involve some form of piping of data. Not sure if this is helpful in trying to understand what's going on here.

Happy to test anything to resolve this. `kill -9` on the host machine doesn't solve it. I can't run commands from within the container using `docker exec` so can't try killing the process from within.I can get plenty of information of the process from `/proc/`, just say what information you want and I'll get it. Unfortunately, I can't reproduce the issue (yet) but I regularly (every day) catch it in my live environment. Updating to a different docker version to "test if it solves it" is somewhat costly as it would involve updating the whole cluster, but if there is a good hypothesis that it will solve the issue I'll go through the work to do it, else my plan is to wait for next stable release until updating.

Really appreciate any help on this as the issue is severely lowering the reliability of the cluster as it requires several-per-day restarts of entire Nodes. Big thanks!

( [This stackoverflow post](https://stackoverflow.com/questions/34552232/cant-kill-processes-originating-in-a-docker-container) is a duplicate. )

UPDATE: (adding examples of crashed processes)

```
# ps aux | grep [1]8342
root     18342 92.0  0.0   5836   132 ?        R     2015 2279:07 bash -c (echo stop > /tmp/minecraft &)
```

```
# ps aux | grep [3]1572
root     31572 95.5  0.0   4448   104 ?        R     2015 2946:35 /bin/sh -c (redis-server &>redis.log &) && ./setup-wait.sh && sleep 3 && ./nodebb start && ./nodebb log && sleep infinity
```

/beetree

**Comment by thaJeztah** [comment] 2016-01-02 14:40
Do you know if this problem started occurring after upgrading the kernel to 4.2.0-19? Symptoms look familiar to https://github.com/docker/docker/issues/18500 (and  https://github.com/docker/docker/issues/18180), which is cause by a kernel bug in aufs; https://github.com/docker/docker/issues/18180#issuecomment-167042078. 

Note that you're mentioning that no zombie processes are created, however, is the process you're showing in your report creating other processes in the container?

**Comment by beetree** [comment] 2016-01-02 17:59
@thaJeztah Some of the nodes in my cluster are actually running an older kernel version (3.19.0-28). I'll start keeping statistics on the problem to verify that it only occurs on nodes with 4.2.0-19.

Thank you so much @thaJeztah for helping me out here. I've seen you across the repo and I hope you hear frequently enough how valuable your contributions are to the community!

**Comment by thaJeztah** [comment] 2016-01-02 18:37
@beetree oh, thank you :blush: doing what I can (which is sometimes simply pointing people to related issues). Thanks for your kind words :)

**Comment by beetree** [comment] 2016-01-03 05:50
In the cluster I run five different kernel versions, with 4.2.0-19 dominating (>50% of the nodes). Over the last 24 hours I've had 7 crashes that split up like this:

```
4.2.0-19: 5
4.2.0-21: 1
4.2.0-22: 1
3.19.0-28: 0
3.19.0-30: 0
```

It seems to me that some form of issue was introduced around 4.2.0-19 that is causing this.

What would be the best solution to this? Downgrade the kernel to 3.19?

/beetree

**Comment by beetree** [comment] 2016-01-03 09:28
Here is what I used to downgrade to 3.19 (ubuntu 15.04/10):

```
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.19.8-vivid/linux-headers-3.19.8-031908-generic_3.19.8-031908.201505110938_amd64.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.19.8-vivid/linux-headers-3.19.8-031908_3.19.8-031908.201505110938_all.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.19.8-vivid/linux-image-3.19.8-031908-generic_3.19.8-031908.201505110938_amd64.deb
dpkg -i linux-{image,headers}-3.19.*.deb
reboot
```
put GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 3.19.8-031908-generic" into /etc/default/grub. Then do `update-grub` followed by `reboot`.

**Comment by AkihiroSuda** [comment] 2016-01-03 21:10
@beetree 
Please refer to the discussion about 296291cd in #18180.

**Comment by beetree** [comment] 2016-01-04 01:54
I'm downgrading the cluster to 3.19, and it will take a few days as I'm discovering some other issues in 3.19 (so far I've been able of working around them).

That said, it doesn't feel right to downgrade the Kernel. That shouldn't be the long-term solution here...? Am I the only one experiencing this issue? If so, should I take the lead on trying to reproduce this and file a bug against the Linux kernel? I haven't done so before and frankly feel a bit uncomfortable about it...

/b3

**Comment by AkihiroSuda** [comment] 2016-01-04 02:06
@beetree You're hitting the bug because Canonical originally backported the commit 296291cd to the kernel 3.19 tree: http://kernel.ubuntu.com/git/ubuntu/ubuntu-vivid.git/commit/?id=6b08592b8acc677d5b9bb7986343fdd6e0ad3303

3.13.0-71 should work for you.

**Comment by beetree** [comment] 2016-01-04 04:36
@AkihiroSuda 3.19 *works* for me while 4.2 *does not* work. I haven't tested 3.13. Also, I'm not sure that my issue is the same as the discussion in #18180 . What makes you think it's similar?

**Comment by AkihiroSuda** [comment] 2016-01-04 04:43
@beetree Sorry, I misreaded about [Z]ombie processes.

**Comment by MHBauer** [comment] 2016-01-05 20:04
I'm gonna subscribe to this, because I encountered similar behavior with docker-machine vms while running the docker integration tests. I was mucking about in the code at the time, so the code was broken and in a bad state. The tests involved piping the output of commands. At one point I had top using 100% cpu, running, and not being killable at all. The only solution was to restart the vm. This was a month ago, and I don't have any of that left unfortunately.

**Comment by beetree** [comment] 2016-01-06 00:56
I've been running 3.19 for two days now across my cluster without issues
(of this type), to be compared to 4.20+ which was yielding 5-10 crashes per
day. I'm starting to get comfortable that this indeed is a kernel issue.

**Comment by thaJeztah** [comment] 2016-01-06 11:14
I'll label this "kernel", to make it easier to find.

**Comment by philwinder** [comment] 2016-02-17 12:08
We have the same problem when _any_ application crashes without a clean shutdown. This is a huge issue for our automated tests, which are completely unstable because of this.

Our container is based upon the `ubuntu:14.04` image. Does anyone know a simple work around for this without a Kernel patch?

**Comment by thaJeztah** [comment] 2016-02-17 13:40
> Our main container is based upon the ubuntu:14.04 image

I don't think that makes a difference here, because all containers share the kernel of the host

>  something is causing the crashed process to become a zombie and Docker cannot handle this, then locks up

If a process cannot be killed, Docker cannot do much about that; If your issue is the same as is discussed here, I think the only option is to install a different kernel.

**Comment by philwinder** [comment] 2016-02-17 14:07
@thaJeztah Thanks for the response. The issue here is that I am running docker-machine. So I don't really have any control over that. I'll just have to wait for an update. I have control over the build servers, but swapping kernels seem's overkill. If I can work around, I will wait for updates.

**Comment by beetree** [comment] 2016-02-18 06:05
I'm not overly familiar with "docker-machine". Is this an iso/image/ami/linux-distribution? If so, what's the kernel version?

If so, is docker-machine sanctioned/maintained by docker? Does docker officially support the underlying linux kernel?

/beetree

**Comment by philwinder** [comment] 2016-02-18 08:50
@beetree Check out https://docs.docker.com/machine/overview/
Yes it's official and maintained by docker. I'm currently on `docker-machine version 0.5.2 ( 0456b9f )`. I see there is a new minor release, so I will try that.

**Comment by thaJeztah** [comment] 2016-02-18 11:14
I think the version of boot2docker running in the virtual machine is important here; boot2docker 1.10 carries the kernel patch to fix the aufs issue; https://github.com/boot2docker/boot2docker/releases.

Running `docker-machine upgrade default` should download the latest boot2docker ISO and upgrade the machine; https://docs.docker.com/machine/reference/upgrade/

**Comment by ricardobranco777** [comment] 2016-03-02 22:53
Install the latest linux-generic-lts-vivid and/or linux-generic-lts-wily packages and the issue is fixed. The packages contains the fixes from the AUFS maintainer:

Check: apt-get changelog linux-image-4.2.0-30-generic / apt-get changelog linux-image-3.19.0-51-generic

  [ J. R. Okajima ]

  * SAUCE: ubuntu: aufs: tiny, extract a new func xino_fwrite_wkq()
    - LP: #1533043
  * SAUCE: ubuntu: aufs: for 4.3, XINO handles EINTR from the dying process
    - LP: #1533043

**Comment by AstraSerg** [comment] 2016-07-07 04:06
I found the way to reproduce the problem with garantee:
1 run gnu patch with -R option (needed to force patch to ask:
 Reversed (or previously applied) patch detected!  Assume -R? [n])
2 Press Ctrl+C Enter

Patch process will be in state like this:
# top -n1 -b | grep -B1 patch
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
29735 root      20   0       0      0      0 R  97.2  0.0  18:22.31 patch

**Comment by caub** [comment] 2018-06-02 07:50
I've another example:

```
$ d ps
CONTAINER ID        IMAGE                        COMMAND             CREATED              STATUS                  PORTS               NAMES
7121c9410bff        k8s.gcr.io/pause-amd64:3.1   "/pause"            1 second ago         Up Less than a second                       k8s_POD_etcd-minikube_kube-system_511a10f280d647f775de1628a57d333f_2
5b710562eec4        k8s.gcr.io/pause-amd64:3.1   "/pause"            About a minute ago   Up About a minute                           k8s_POD_kube-apiserver-minikube_kube-system_9344320a58287bb47ab09d551d2485f0_1
f2e626a67f7a        k8s.gcr.io/pause-amd64:3.1   "/pause"            About a minute ago   Up About a minute                           k8s_POD_kube-controller-manager-minikube_kube-system_a773829dd0dc9cfcb93d910823a6b96e_1
1c6ccc91981b        k8s.gcr.io/pause-amd64:3.1   "/pause"            About a minute ago   Up About a minute                           k8s_POD_kube-scheduler-minikube_kube-system_ea66a171667ec4aaf1b274428a42a7cf_1
```

Those container were related to minikube, which I tried uninstalling (from https://github.com/kubernetes/minikube/issues/1043#issuecomment-354453842)

```
caub@ins:~$ docker rm -f $(docker ps -aq --filter name=k8s)
7121c9410bff
5b710562eec4
f2e626a67f7a
1c6ccc91981b
b8b716b70b0b
35a54d7c260e
cbd0114a2cfb
0d8a80d6c81a
89817f189e4e
8180fa48fcd4
51c95c45db1e
ab9faaf2b54d
caub@ins:~$ d ps
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS               NAMES
bac3adb26e40        k8s.gcr.io/pause-amd64:3.1   "/pause"            3 seconds ago       Up 1 second                             k8s_POD_kube-controller-manager-minikube_kube-system_a773829dd0dc9cfcb93d910823a6b96e_0
417990a8d4e9        k8s.gcr.io/pause-amd64:3.1   "/pause"            3 seconds ago       Up 1 second                             k8s_POD_kube-scheduler-minikube_kube-system_ea66a171667ec4aaf1b274428a42a7cf_0
dc7d923aec2d        k8s.gcr.io/pause-amd64:3.1   "/pause"            3 seconds ago       Up 1 second                             k8s_POD_etcd-minikube_kube-system_511a10f280d647f775de1628a57d333f_0
9147aa8cf2b8        k8s.gcr.io/pause-amd64:3.1   "/pause"            3 seconds ago       Up 1 second                             k8s_POD_kube-apiserver-minikube_kube-system_9344320a58287bb47ab09d551d2485f0_0
caub@ins:~$ d kill bac3adb26e40
bac3adb26e40
caub@ins:~$ d ps
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS                  PORTS               NAMES
15c74696adaf        k8s.gcr.io/pause-amd64:3.1   "/pause"            2 seconds ago       Up Less than a second                       k8s_POD_kube-controller-manager-minikube_kube-system_a773829dd0dc9cfcb93d910823a6b96e_1
417990a8d4e9        k8s.gcr.io/pause-amd64:3.1   "/pause"            22 seconds ago      Up 20 seconds                               k8s_POD_kube-scheduler-minikube_kube-system_ea66a171667ec4aaf1b274428a42a7cf_0
dc7d923aec2d        k8s.gcr.io/pause-amd64:3.1   "/pause"            22 seconds ago      Up 20 seconds                               k8s_POD_etcd-minikube_kube-system_511a10f280d647f775de1628a57d333f_0
9147aa8cf2b8        k8s.gcr.io/pause-amd64:3.1   "/pause"            22 seconds ago      Up 20 seconds                               k8s_POD_kube-apiserver-minikube_kube-system_9344320a58287bb47ab09d551d2485f0_0
```
They are simply unkillable

**Comment by thaJeztah** [comment] 2023-09-16 23:06
Let me close this ticket for now, as it looks like it went stale.

**Closed** 2023-09-16 23:07 UTC
Labels: area/kernel, kind/bug, version/1.9
