### ISSUE TITLE
Difference in image extraction between Docker CE 17.05 and 17.06

### ISSUE THREAD

**Issue by vrevelas** [moby/moby#34092] opened 2017-07-13 10:57 UTC
**Description**

Image extraction between Docker CE 17.05 and 17.06 results in different root filesystems. I am able to reproduce the issue with both aufs and overlay2 storage drivers.

I ran into this issue with an image from a private repository. If the information that follows isn't enough to identify the issue, please let me know and I will attempt to create a public image that reproduces the behaviour described.

**Steps to reproduce the issue:**

Using Docker 17.06 CE

1. `docker-machine create --virtualbox-boot2docker-url "https://github.com/boot2docker/boot2docker/releases/download/v17.06.0-ce/boot2docker.iso" -d virtualbox --engine-insecure-registry internal_repo 1706ce`
2. `eval $(docker-machine env 1706ce)`
3. `docker run --rm -ti internal_repo/image ls /`

**Describe the results you received:**

```
#
0001-gyp-always-install-into-PRODUCT_DIR.patch
0002-gyp-apply-https-codereview.chromium.org-11361103.patch
0003-gyp-don-t-use-links-at-all-just-copy-the-files-inste.patch
2015-01-30.md
@@iterator
AUTHORS
AUTHORS.md
BufferList.js
CHANGELOG.md
CHANGES
CHANGES.md
CONTRIBUTING.md
COPYING.txt
CodecMalformedException.java

<~1000 output lines truncated>
```

**Describe the results you expected:**

Using Docker 17.05 CE

1. `docker-machine create --virtualbox-boot2docker-url "https://github.com/boot2docker/boot2docker/releases/download/v17.05.0-ce/boot2docker.iso" -d virtualbox --engine-insecure-registry internal_repo 1705ce`
2. `eval $(docker-machine env 1705ce)`
3. `docker run --rm -ti internal_repo/image ls /`

result:

```
INFORMIXTMP  artifacts	bin  boot  database  dev  etc  home  lib  lib64  media	mnt  nohup.out	nonexistent  opt  proc	root  run  sbin  selinux  shared  srv  sys  tmp  usr  var
```

**Additional information**

The filesystem in the 17.06 case is not completely flattened. It does contain the directories shown in the 17.05 output, and they do contain files.

An excerpt follows showing the result of comparing file checksums/locations between the 17.06 and 17.05 cases:

```
< 00564742e3c70905fdb4d3318b01c827  /node_modules/es5-ext/.lint
---
> 00564742e3c70905fdb4d3318b01c827  /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/.lint
145a146,147
> 00564742e3c70905fdb4d3318b01c827  /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/.lint
> 00564742e3c70905fdb4d3318b01c827  /usr/local/n/versions/node/7.0.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/.lint
322a325,327
> 00ac2be339a766e2df37641d0350c63e  /usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/glob/node_modules/path-is-absolute/package.json
> 00ac2be339a766e2df37641d0350c63e  /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/glob/node_modules/path-is-absolute/package.json
> 00ac2be339a766e2df37641d0350c63e  /usr/local/n/versions/node/7.0.0/lib/node_modules/npm/node_modules/read-package-json/node_modules/glob/node_modules/path-is-absolute/package.json
492a498,500
> 01028d57163f4901221a7a457774e202  /usr/lib/node_modules/npm/node_modules/init-package-json/node_modules/glob/node_modules/path-is-absolute/package.json
> 01028d57163f4901221a7a457774e202  /usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/glob/node_modules/path-is-absolute/package.json
> 01028d57163f4901221a7a457774e202  /usr/local/n/versions/node/7.0.0/lib/node_modules/npm/node_modules/init-package-json/node_modules/glob/node_modules/path-is-absolute/package.json
493a502
> 0103318a939e4c2198689f6f143e556d  /usr/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/formats/x509.js
495c504,505
< 0103318a939e4c2198689f6f143e556d  /x509.js
---

```
It can be seen that several files are missing.

`/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/.lint` under 17.05 moved to `/node_modules/es5-ext/.lint` in 17.06 and `/usr/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/formats/x509.js` in 17.05 moved to `/x509.js` in 17.06. File contents are unaffected.

Here is the output of `docker inspect internal_repo/image` for the 17.05 case:

```
[
    {
        "Id": "sha256:a126cdbff382390a94be039424f1db5f6022ecb4444f6c4ea78853cc774dee12",
        "RepoTags": [
            "internal_repo/image:latest"
        ],
        "RepoDigests": [
            "internal_repo/image@sha256:bc287cd9d506ede8ccd4d5c083ba71b60157b85af90188044860e2cffa5b996d"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-07-05T11:06:34.148937884Z",
        "Container": "d802f466bfefc17dce309a7ec63ea22929377e70f3105f03754d01f298aba457",
        "ContainerConfig": {
            "Hostname": "d802f466bfef",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": null,
            "Cmd": [
                "/bin/bash"
            ],
            "Image": "internal_repo/image",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "17.05.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "/bin/bash"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 3265786582,
        "VirtualSize": 3265786582,
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:3cb5cef9e16b6c2fc4c25591b64c3a37ee728e41a9dbb02be96e94ee0784536d",
                "sha256:cf19831f7cead5e80c994c75812f26e8010ad4d422b1693b73cd2b06e8890913",
                "sha256:092bf598ac10f3529cb9225e560c903aaae3ed524e9e793c74b5c1ea71cf26de"
            ]
        }
    }
]
```

The only difference in the output for 17.06 is

```
<         "Size": 3265786582,
<         "VirtualSize": 3265786582,
---
>         "Size": 3258003733,
>         "VirtualSize": 3258003733,
```
I have confirmed that in both the 17.05 and 17.06 cases that the `/var/lib/docker/tmp/GetImageBlob*` files created have identical sha256sums, which means the same layers are being pulled from the repo in both cases.

`/var/log/docker.log` does not show any usual errors or output when extracting in either case. Output from the 17.06 case:

```
time="2017-07-13T09:19:18.115570865Z" level=debug msg="Downloaded 515ece5796b4 to tempfile /mnt/sda1/var/lib/docker/tmp/GetImageBlob669060717" 
time="2017-07-13T09:19:19.312413910Z" level=debug msg="Downloaded c10ec98cceed to tempfile /mnt/sda1/var/lib/docker/tmp/GetImageBlob298385640" 
time="2017-07-13T09:21:35.851669441Z" level=debug msg="Downloaded a697c759d873 to tempfile /mnt/sda1/var/lib/docker/tmp/GetImageBlob421049798" 
time="2017-07-13T09:22:55.763161662Z" level=debug msg="Applied tar sha256:3cb5cef9e16b6c2fc4c25591b64c3a37ee728e41a9dbb02be96e94ee0784536d to b60e75153572e514ebc5fa9f6f4589a3306f42d5bd4b738edba74e5b538e6124
, size: 3250951555" 
time="2017-07-13T09:22:55.841672470Z" level=debug msg="Applied tar sha256:cf19831f7cead5e80c994c75812f26e8010ad4d422b1693b73cd2b06e8890913 to c6fb8d7b5c89bfb515dbc6f7ad1e3fc189319c2fb4e4255370883b186e7af36e
, size: 807" 
time="2017-07-13T09:22:55.978860870Z" level=debug msg="Applied tar sha256:092bf598ac10f3529cb9225e560c903aaae3ed524e9e793c74b5c1ea71cf26de to efb16627adf62001b66723902dcc85b58fc4972ff314120ab18185b187c08e45
, size: 7051371" 
```

When reproducing the issue with overlay2, I can confirm that the `/diff` directory of the `a697c759d873` layer in `/var/lib/docker` contains the incorrectly extracted file paths before starting any containers.

**Comment by vrevelas** [comment] 2017-07-13 12:40
One more thing I noticed was that 17.06 is unable to save the pulled image:
```
eval $(docker-machine env 1706ce)
docker save -o image.tar internal_repo/image
Error response from daemon: open /mnt/sda1/var/lib/docker/aufs/diff/b60e75153572e514ebc5fa9f6f4589a3306f42d5bd4b738edba74e5b538e6124/redacted_path/CodecMalformedException.java: no such file or directory
```
17.05 is able to save without error.

**Comment by mlaventure** [comment] 2017-07-13 13:59
ping @tonistiigi

**Comment by tonistiigi** [comment] 2017-07-13 15:18
@vrevelas Thanks for the report. Can you put together a reproducer that we could try? Also, please post `docker info` and `docker version`

**Comment by vrevelas** [comment] 2017-07-13 15:30
```
$ eval $(docker-machine env 1705ce)
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.66-boot2docker
Operating System: Boot2Docker 17.05.0-ce (TCL 7.2); HEAD : 5ed2840 - Fri May  5 21:04:09 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: 1705ce
ID: VAZ3:MM6D:UAKU:MOJE:TBTS:SCLL:2UVZ:JLZX:THFQ:FORY:IIJH:VDQV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 23
 System Time: 2017-07-13T15:25:59.43713269Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 wil.registry.dev.openbet.com
 127.0.0.0/8
Live Restore Enabled: false

$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ eval $(docker-machine env 1706ce)
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: 1706ce
ID: UEMU:HTLO:6DCI:YBO5:VQHX:2YHE:3MUA:VAVA:UCQ2:BFUU:K3SY:WCMW
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 40
 System Time: 2017-07-13T15:26:11.136316182Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 wil.registry.dev.openbet.com
 127.0.0.0/8
Live Restore Enabled: false

$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I will try and create an image for you that reproduces the issue, but that may take time.

In the meantime, are you aware of any changes between 17.05ce and 17.06ce in how dockerd extracts image layers?

**Comment by tonistiigi** [comment] 2017-07-13 15:33
@vrevelas Thanks. Could you also clarify how this image was created? One possibility is that this could be related to https://go-review.googlesource.com/c/31444/4/src/archive/tar/reader.go#b474  that changes the parsing of `GNU` tar header to ignore prefix field. I went over the packages that deal with extraction in `dockerd` and didn't notice any obvious changes between `17.05` and `17.06`.

**Comment by vrevelas** [comment] 2017-07-13 15:52
The image was created by a script that executed shell commands in a container and then committed the result. I have no details on the Docker version used at this stage. The base image used by the script was Ubuntu 12.04. When the script was decommissioned, last image it produced was flattened by exporting a stopped container and importing the tarball into a new image. This happened about 6 months ago on an Ubuntu 16.04 system, but I can't be more specific about the docker version that was used. Since then, two new layers were added to the base by manually running shell commands and committing the result, again on Ubuntu 16.04.

**Comment by tonistiigi** [comment] 2017-07-13 16:21
@vrevelas If you can access the `/var/lib/docker/tmp/GetImageBlob*` files, would it be possible for you to send (links to) them to tonis[at]docker.com so we can investigate what tar format they use.

**Comment by tonistiigi** [comment] 2017-07-13 23:47
Summary of the current findings (+ @dmcgowan @stevvooe )

With `docker-17.06.0` some images pulled do not extract properly. Some files don't appear in correct directories. This may or may not cause the pull to fail. These images can't be pushed or saved. `17.06` is the first version of Docker built with `go1.8`.

#### Cause

There are multiple updates to the `tar` package in `go1.8`.

https://go-review.googlesource.com/c/32234/ disables using "prefix" field when new tar archives are being written. Prefix field was previously set when a record in the archive used a path longer than 100 bytes.

Another change https://go-review.googlesource.com/c/31444/ makes the reader ignore the "prefix" field value if the record is in `GNU` format. `GNU` format defines that same area should be used for access and modified times. If the "prefix" field is not read, a file will only be extracted by the basename.

The problem is that with a previous version of the golang archive package headers could be written, that use the prefix field while at the same time setting the header format to `GNU`. This happens when numeric fields are big enough that they can not be written as octal strings and need to be written in binary. Usually, this shouldn't happen: uid, gid, devmajor, devminor can use up to 7 bytes, size and timestamp can use 11. If one of the records does overflow it switches the whole writer to `GNU` mode and all next files will be saved in `GNU` format.

https://github.com/moby/moby/issues/33958 reports `zigmund/pub:r8` as affected image. This image contains a lot of files that exceed the path length limit. Normally this wouldn't be a problem, but there is number overflow in UID field for certain files that makes all the files coming after that to be marked as if they were using `GNU` format.

The specific npm library that is causing this inside the tar is `path-parse@^1.0.5`. The files in the source of that package https://registry.npmjs.org/path-parse/-/path-parse-1.0.5.tgz contain very big UID values. It is unclear what may have originally caused this.

```
» tar tvf path-parse-1.0.5.tar
-rw-r--r--  1 2097789302  1758927306 667 Apr 21  2015 package/package.json
-rw-r--r--  1 2097789302  1758927306 912 Apr 21  2015 package/README.md
----
``` 

#### Extent

Currently, we have determined 2 reports that seem to be caused by this and one image that contains the UID overflow + long paths combination. Long paths are common in nodejs applications.

#### Next steps

Assuming that this is not a problem that only affects very few images, for fixing `docker-17.06.1` we have to fork the `golang` archive pkg and modify the tar reader to understand the "prefix" field again. It may be possible to determine "prefix" field from the timestamp values that may also be in same location based on content. We'll notify the upstream to see if we can have some fixes there as well. Possibly switching the whole file to `GNU` mode after one number overflow can be improved as well.

**Comment by thaJeztah** [comment] 2017-07-13 23:58
Thanks @tonistiigi ! Definitely +1 to looking at upstreaming changes

**Comment by tiborvass** [comment] 2017-07-14 00:50
@tonistiigi Agree on the fix. It's a serious issue, but not widespread.

**Comment by stevvooe** [comment] 2017-07-14 02:04
@tonistiigi Great explanation!

I have created a minimal reproduction of the issue in https://gist.github.com/stevvooe/e2a790ad4e97425896206c0816e1a882. I've filed https://github.com/golang/go/issues/21005 with the Go team.

**Comment by vrevelas** [comment] 2017-07-14 12:56
@tonistiigi In response to your [request](#issuecomment-315128978) to email you the layer blobs, I'm not able to do so as they are work-related and contain proprietary code.

In my effort to create a sanitised image that I could send, I determined that the combination of a large UID value and long file path are indeed the cause of the issue. Note that the large UID and long path don't have to belong to the same file. In our image specifically, we have a file with a UID of 1401167856 (no idea how that happened) and a short path. Other files with long paths and normal UIDs (npm is one example, maven repositories are another) then end up on incorrect paths. `chown`ing the file with the large UID fixes the problem.

Prior to discovering this, I used another workaround: I exported the root filesystem with GNU tar under docker 17.05:
```
docker run -v /home/vrevelas:/host-home -u root --rm -ti internal_repo/image tar -C / --one-file-system -cf /host-home/image.tar .
```
and then imported the tarfile into docker 17.06.

Thanks for looking into this!

**Comment by tonistiigi** [comment] 2017-07-14 16:00
@vrevelas 

> Note that the large UID and long path don't have to belong to the same file.

Yes, large `UID` changes all files coming after that to `GNU` mode. So all files with the long paths after that point are affected.

Thanks for confirming that your image had the same issue.

**Closed** 2017-07-17 07:40 UTC
Labels: area/distribution, kind/bug
