### ISSUE TITLE
install docker on alpine linux

### ISSUE THREAD

**Issue by ncc0706** [moby/moby#37006] opened 2018-05-06 13:52 UTC
![image](https://user-images.githubusercontent.com/11310593/39673966-a206b1fc-5177-11e8-834e-2a370b8cf910.png)

**Comment by thaJeztah** [comment] 2018-05-06 14:29
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)


Note that the docker packages for Alpine are not maintained here, but by the Alpine Linux community, so it's best to ask there for support.

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-05-06 14:29 UTC
