### ISSUE TITLE
Docker containers showing Exited (255) after Virtual Machine restart.

### ISSUE THREAD

**Issue by marcbak** [moby/moby#41349] opened 2020-08-13 13:13 UTC
**Description**
I'm using CentOS 7 Virtual Machine managed by vCenter. I have two containers, one running production application, the other one being willfarrell/autoheal . If I reboot or Power Off -> Power On the Virtual Machine none of the containers are running even though the restart policy is Always and Unless Stopped.

This is the output of docker ps -a
````
CONTAINER ID        IMAGE                                                          COMMAND                  CREATED             STATUS                       PORTS               NAMES
48643652104e        myimage/app:v1.0.0   "/bin/sh -c 'fake_app…"   10 minutes ago      Exited (255) 9 minutes ago                       test-test1
c830c861db07        willfarrell/autoheal                                           "/docker-entrypoint …"   10 minutes ago      Exited (255) 9 minutes ago                       autoheal_instance
````

docker logs:
````
Aug 13 10:51:34  time="2020-08-13T10:51:34.776684617Z" level=info msg="Starting up"
Aug 13 10:51:34  time="2020-08-13T10:51:34.785343317Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.785362031Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.785383987Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.785396303Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.798792683Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.798819392Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.798845432Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.798861922Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 13 10:51:34  time="2020-08-13T10:51:34.861329951Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Aug 13 10:51:35  time="2020-08-13T10:51:35.011043571Z" level=info msg="Loading containers: start."
Aug 13 10:51:35  time="2020-08-13T10:51:35.538595731Z" level=info msg="Removing stale sandbox 3f375b8c17beca5bcb1a198e0b825f729817d7c9bcf4fd09df47d3f172ae6b9d (49c8bc30ec90d5618ae1f77c75c54aa9d65d426757231d8584c72d8eb7ba9f24)"
Aug 13 10:51:35  time="2020-08-13T10:51:35.540259222Z" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint cedc0536a35d4326184ea4fc168ca9c3105f881310748cce8984be462c5490ed 0054144d3eb8609154d3e556883baa8e4f643599c5316a460d0f16f9a27b37cd], retrying...."
Aug 13 10:51:35  time="2020-08-13T10:51:35.717451639Z" level=info msg="Removing stale sandbox 7fd50911b3f98ff9a8478d718e6046026660b004ee9dc55a4f8586e71d051150 (123803282bccbf4c240acea928424bf564ef5efdcd4ed7e27dacbf0446f5fc39)"
Aug 13 10:51:35  time="2020-08-13T10:51:35.718504704Z" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint cedc0536a35d4326184ea4fc168ca9c3105f881310748cce8984be462c5490ed 68707755b5ac2dd8e713b5e60e202afeb4d7ffe43834ea9f00f05078cf950fd1], retrying...."
Aug 13 10:51:35  time="2020-08-13T10:51:35.751570846Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Aug 13 10:51:35  time="2020-08-13T10:51:35.937064698Z" level=error msg="stream copy error: reading from a closed fifo"
Aug 13 10:51:35  time="2020-08-13T10:51:35.938024598Z" level=error msg="stream copy error: reading from a closed fifo"
Aug 13 10:51:35  time="2020-08-13T10:51:35.943028389Z" level=error msg="stream copy error: reading from a closed fifo"
Aug 13 10:51:35  time="2020-08-13T10:51:35.943161510Z" level=error msg="stream copy error: reading from a closed fifo"
Aug 13 10:51:35  time="2020-08-13T10:51:35.966380814Z" level=error msg="49c8bc30ec90d5618ae1f77c75c54aa9d65d426757231d8584c72d8eb7ba9f24 cleanup: failed to delete container from containerd: no such container"
Aug 13 10:51:35  time="2020-08-13T10:51:35.966405625Z" level=error msg="Failed to start container 49c8bc30ec90d5618ae1f77c75c54aa9d65d426757231d8584c72d8eb7ba9f24: OCI runtime create failed: container with id exists: 49c8bc30ec90d5618ae1f77c75c54aa9d65d426757231d8584c72d8eb7ba9f24: unknown"
Aug 13 10:51:35  time="2020-08-13T10:51:35.973889519Z" level=error msg="123803282bccbf4c240acea928424bf564ef5efdcd4ed7e27dacbf0446f5fc39 cleanup: failed to delete container from containerd: no such container"
Aug 13 10:51:35  time="2020-08-13T10:51:35.973911061Z" level=error msg="Failed to start container 123803282bccbf4c240acea928424bf564ef5efdcd4ed7e27dacbf0446f5fc39: OCI runtime create failed: container with id exists: 123803282bccbf4c240acea928424bf564ef5efdcd4ed7e27dacbf0446f5fc39: unknown"
Aug 13 10:51:35  time="2020-08-13T10:51:35.973926346Z" level=info msg="Loading containers: done."
Aug 13 10:51:36  time="2020-08-13T10:51:36.010048484Z" level=info msg="Docker daemon" commit=48a66213fe graphdriver(s)=overlay2 version=19.03.12
Aug 13 10:51:36  time="2020-08-13T10:51:36.011352485Z" level=info msg="Daemon has completed initialization"
Aug 13 10:51:36  time="2020-08-13T10:51:36.051737921Z" level=info msg="API listen on /var/run/docker.sock"
````

**Steps to reproduce the issue:**
1. Restart or Shutdown, then Power On Virtual Machine
2. Issue docker ps
3. Verify that no docker containers are currently running

**Describe the results you received:**
Both containers show Exited (255) when docker ps -a is issued

**Describe the results you expected:**
Both containers running 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.18.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 972.4MiB
 Name: sat-oom-test-server-001
 ID: 2S6J:TJ6Z:R7J4:NHOW:YWA4:DB7L:CQHD:45RL:NLMB:QDXQ:WSUZ:DWO2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: fr24deploy
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Machine running CentOS 7 managed by vCentre.

**Comment by thaJeztah** [comment] 2020-08-13 17:32
Are you able to reproduce the problem with standard images from Docker Hub, or only with these specific images? Having exact steps to reproduce could help to verify if there's a bug or if its something in your setup/configuration.

**Comment by marcbak** [comment] 2020-08-18 09:12
Sorry for the delayed response. I created this Dockerfile to test it out
`FROM ubuntu:20.04
CMD tail -f /dev/null`
and the issue persists.

**Comment by thaJeztah** [comment] 2020-08-18 11:31
How are the containers started? Are there specific options that are set (besides a `--restart=unless-stopped`) ?


Looking at these errors, and wondering if they are related/similar to the issues being looked at in https://github.com/moby/moby/pull/41227 and https://github.com/moby/moby/pull/41341, but those are in a different area

```
49c8bc30ec90d5618ae1f77c75c54aa9d65d426757231d8584c72d8eb7ba9f24 cleanup: failed to delete container from containerd: no such container
Failed to start container 49c8bc30ec90d5618ae1f77c75c54aa9d65d426757231d8584c72d8eb7ba9f24: OCI runtime create failed: container with id exists: 49c8bc30ec90d5618ae1f77c75c54aa9d65d426757231d8584c72d8eb7ba9f24: unknown
```

So the errors are printed in reverse order, because the first error is produced if we hit the `Cleanup()` function, which would be hit if starting the container failed; https://github.com/moby/moby/blob/61b73ee714f9f4bd575377a1a0a3fa7bfd2ebceb/daemon/start.go#L126-L146

So the second error ("OCI runtime create failed: container with id exists") is the one that I think is the one that leads to an error being returned, and thuse the `Cleanup()` being called. However, if I read the code correctly, there _should be_ code in place to handle the "conflict" situation ("container with ID exists"); https://github.com/moby/moby/blob/61b73ee714f9f4bd575377a1a0a3fa7bfd2ebceb/daemon/start.go#L190-L204

So either this is a different "conflict" that cannot be resolved by cleaning up an old container object in containerd, or the `errdefs.IsConflict(err)` does not detect the containerd conflict error

I'm not sure if that's the actual problem in your case though, or only an effect of the container failing to start (there's errors from libnetwork before that)

### Trying to reproduce on the same version of docker, on CentOS 7;


```console
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.27.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.795GiB
 Name: centos-s-1vcpu-2gb-ams3-01
 ID: LCEY:ONBW:MH4T:WGWV:QYJS:YRJP:SUXN:D6SU:TWNF:74U5:FMYQ:RCCP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Reproducing by starting a container having the same command as your Dockerfile;

```bash
docker run -d --name repro-41349 --restart=unless-stopped ubuntu:20.04 tail -f /dev/null

docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
42e6cb046a3e        ubuntu:20.04        "tail -f /dev/null"   4 seconds ago       Up 3 seconds                            repro-41349
```

Reboot the machine

```bash
reboot
```

And check status of the container after rebooting and when docker is running again;

```bash
docker ps -a
CONTAINER ID        IMAGE               COMMAND               CREATED              STATUS              PORTS               NAMES
42e6cb046a3e        ubuntu:20.04        "tail -f /dev/null"   About a minute ago   Up 7 seconds                            repro-41349
```


So, I'm not able to reproduce the problem with these steps. I do notice your machine only has 1 GB of memory, which (depending on load) could be a bit low.

If you have exact steps to reproduce the problem, that would be useful to see if there's a bug at hand or not.

**Comment by marcbak** [comment] 2020-08-18 11:55
Thanks for investigating, I tried to recreate your successful scenario and to my surprise it works correctly if you reboot the VM via `reboot`.
I then tried  `shutdown -h now` and then power the VM back on via vSphere client and this also works correctly - as in, the containers are restarted successfully.
So it seems that this issue only happens when the restart is triggered via the vSphere client, or the machine is powered off by the vSphere client.

Unfortunately, apart from using the vSphere Client, I wasn't able to reproduce the scenario, perhaps there's something about the way vSphere client shuts down the VM that leaves the containers in bad state?

**Comment by thaJeztah** [comment] 2020-08-18 12:08
Code is slightly different on master compared to v19.03.12. I tried some debugging code to verify that we're able to detect the "conflict" situation in v19.03.12;

```patch
diff --git a/daemon/start.go b/daemon/start.go
index adc253d6e2..c532ae9a1b 100644
--- a/daemon/start.go
+++ b/daemon/start.go
@@ -195,6 +195,15 @@ func (daemon *Daemon) containerStart(container *container.Container, checkpoint
                }
        }

+       err = daemon.containerd.Create(ctx, container.ID, spec, createOptions)
+       if err != nil {
+               if errdefs.IsConflict(err) {
+                       logrus.WithError(err).WithField("container", container.ID).Error("DETECTED A CONFLICT ERROR")
+               } else {
+                       logrus.WithError(err).WithField("container", container.ID).Error("FAILED TO DETECT CONFLICT ERROR")
+               }
+       }
+
```

With the above, I do see the expected error logged, so looks like detection of conflict is working;

```
ERRO[2020-08-18T12:07:12.990138075Z] DETECTED A CONFLICT ERROR                     container=2e1f3bb05854448e52f0a035f3ea1af7644b2afe8582dd2a3ce232fdc5404920 error="id already in use"
```

**Comment by thaJeztah** [comment] 2020-08-18 12:10
Hmmm.. the error is different though (`id already in use` versus `container with id exists`); double checking

**Comment by thaJeztah** [comment] 2020-08-18 12:13
ok, looks like that error is coming from libcontainer / runc; https://github.com/opencontainers/runc/blob/ceefc3fe4ecb31fa89ed50ecb2bc0efc7dfac683/libcontainer/factory_linux.go#L203-L204

```go
	if _, err := os.Stat(containerRoot); err == nil {
		return nil, newGenericError(fmt.Errorf("container with id exists: %v", id), IdInUse)
	} else if !os.IsNotExist(err) {
		return nil, newGenericError(err, SystemError)
	}
```

**Comment by cpuguy83** [comment] 2020-08-18 14:01
Make sure /run is a tmpfs.

**Comment by cpuguy83** [comment] 2020-08-18 14:03
If runc is giving this error that means there is some leftover state in /run.
This is why /run should be a tmpfs. On reboot it will be cleared.

**Comment by marcbak** [comment] 2020-08-19 08:13
> If runc is giving this error that means there is some leftover state in /run.
> This is why /run should be a tmpfs. On reboot it will be cleared.

You are correct that this is not a tmpfs mount. So probably this is the root of this issue. I assume it's a confiuration error and not an actual bug in the Docker then?

**Comment by cpuguy83** [comment] 2020-08-26 18:40
This is highly distro specific.
Usually `/var/run` is a symlink to `/run`... but in any case  both locations should be a tmpfs by convention.

**Comment by sam-thibault** [comment] 2022-12-13 15:50
I don't see any recent activity on this issue.  I will close it as stale.

**Closed by sam-thibault** 2022-12-13 15:50 UTC
Labels: status/more-info-needed, version/19.03
