### ISSUE TITLE
Cannot install vmware docker volume on CoreOS

### ISSUE THREAD

**Issue by mlabouardy** [moby/moby#35106] opened 2017-10-06 08:42 UTC
**Description**

I cannot install vsphere docker volume on CoreOS machine with docker 17.06.2

**Steps to reproduce the issue:**

`docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:0.17`

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/10320205/31269983-d9b51fcc-aa82-11e7-8961-c4f78aa0d919.png)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 17:16:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 17:16:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 16
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 7uqfou6mryjhzaf04xqnf2sy2
 Is Manager: true
 ClusterID: lzn9sxbcsvfv53wciujbhgpoy
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.100.248.35
 Manager Addresses:
  10.100.248.35:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.13.3-coreos-r1
Operating System: Container Linux by CoreOS 1548.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 1.957GiB
Name: beta-manager
ID: PNOF:MENH:OYP7:FV5Q:74Z7:R7HN:VIKX:NUGJ:6JWO:HSL6:J63H:4U2H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.100.248.18:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

CoreOS version:

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1548.0.0
VERSION_ID=1548.0.0
BUILD_ID=2017-09-27-0012
PRETTY_NAME="Container Linux by CoreOS 1548.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

**Comment by thaJeztah** [comment] 2017-10-08 00:01
I'm not able to reproduce this using the official packages for Ubuntu 17.04, and Fedora 25;

```bash
$ docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:0.17
0.17: Pulling from vmware/docker-volume-vsphere
c7aff1c1fe73: Download complete
Digest: sha256:bb23058ed1e414d4345551a3d5a4f187b291a16252a25d9e6e7f39c738e87129
Status: Downloaded newer image for vmware/docker-volume-vsphere:0.17
Installed plugin vmware/docker-volume-vsphere:0.17
```

```bash
$ docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
4a1c49c3f751        vsphere:latest      VMWare vSphere Docker Volume plugin   true
```


CoreOS is not a supported distro; the Docker package for CoreOS is built and maintained by CoreOS, and it's possible it's specific to that platform; could you report it there first?

I'll close this issue here, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-08 00:01 UTC
Labels: area/plugins, version/17.06

**Comment by mlabouardy** [comment] 2017-10-08 19:18
apparently it's a bug in the plugin itself https://github.com/vmware/docker-volume-vsphere/issues/1924

**Comment by thaJeztah** [comment] 2017-10-08 19:36
Thanks for the update 👍
