### ISSUE TITLE
"No swap limit support" warning is messing with docker info parsing

### ISSUE THREAD

**Issue by bravo2zero** [moby/moby#39787] opened 2019-08-23 11:50 UTC
**Description**

When executing "docker info" on systems without swap limit support, command always appends "WARNING: No swap limit support" at the end of the output. The warning is apparently not thrown as a part of info command, but is thrown separately, which interferes with any attempt to parse the info command output automatically.

**Steps to reproduce the issue:**
1. Execute command docker info | sed -n '/Addresses/{n;p}'
2. Expected output is the first line coming after the matched "Manager Addresses:" line
3. Actual output:
```
WARNING: No swap limit support
   X.X.X.X:2377
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Suggested solution:**
Warning could be added as a part of info command output, for example:
Swap limit support: (true|false)

**Comment by thaJeztah** [comment] 2019-08-23 15:35
The `docker info` output is printed on `stdout`, and the warnings are printed on `stderr` so that they can be redirected separately. For example;


### Redirect the warnings and only get the standard `docker info` output;

(or replace `/dev/null` with a file to redirect to)

```bash
docker info 2> /dev/null

Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: rpf6pl14wqdfflld4ucnol6vv
  Is Manager: true
  ClusterID: vnvbiu5jzmnpifpuoh4fnqbv9
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.17.0.4
  Manager Addresses:
   172.17.0.4:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.131-linuxkit
 Operating System: Alpine Linux v3.10 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.945GiB
 Name: ac9582563b98
 ID: LBFO:XHBT:DDLT:U6WY:GFZO:JWWU:OUGF:FRKH:5CDH:HC5Z:SD6G:CWSI
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 35
  Goroutines: 152
  System Time: 2019-08-23T14:53:15.365416827Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Redirect regular output, and only show the warnings:

```bash
docker info > /dev/null
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Redirect the warnings, and parse the standard output with `sed`

```bash
 docker info 2> /dev/null | sed -n '/Addresses/{n;p}'
   172.17.0.4:2377
```

However, note that the output is not strictly formalised, and can change over time. Instead of trying to parse the output; a better approach would be to use the `--format` option, which allows you to get specific information from the output in a more structured format. The flag accepts a ["go template"](https://golang.org/pkg/text/template/) (some [more examples here](https://blog.gopheracademy.com/advent-2017/using-go-templates/))

(I'm using `jq` to friendly-format the JSON output examples);

### Get all information as JSON

```bash
docker info --format '{{ json . }}' | jq .
```
```json
{
  "ID": "LBFO:XHBT:DDLT:U6WY:GFZO:JWWU:OUGF:FRKH:5CDH:HC5Z:SD6G:CWSI",
  "Containers": 0,
  "ContainersRunning": 0,
  "ContainersPaused": 0,
  "ContainersStopped": 0,
  "Images": 0,
  "Driver": "overlay2",
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "SystemStatus": null,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "local",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "MemoryLimit": true,
  "SwapLimit": true,
  "KernelMemory": true,
  "KernelMemoryTCP": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "PidsLimit": true,
  "IPv4Forwarding": true,
  "BridgeNfIptables": false,
  "BridgeNfIp6tables": false,
  "Debug": true,
  "NFd": 35,
  "OomKillDisable": true,
  "NGoroutines": 152,
  "SystemTime": "2019-08-23T14:57:16.122966883Z",
  "LoggingDriver": "json-file",
  "CgroupDriver": "cgroupfs",
  "NEventsListener": 0,
  "KernelVersion": "4.14.131-linuxkit",
  "OperatingSystem": "Alpine Linux v3.10 (containerized)",
  "OSType": "linux",
  "Architecture": "x86_64",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Name": "docker.io",
        "Mirrors": [],
        "Secure": true,
        "Official": true
      }
    },
    "Mirrors": []
  },
  "NCPU": 4,
  "MemTotal": 2088243200,
  "GenericResources": null,
  "DockerRootDir": "/var/lib/docker",
  "HttpProxy": "",
  "HttpsProxy": "",
  "NoProxy": "",
  "Name": "ac9582563b98",
  "Labels": [],
  "ExperimentalBuild": false,
  "ServerVersion": "19.03.1",
  "ClusterStore": "",
  "ClusterAdvertise": "",
  "Runtimes": {
    "runc": {
      "path": "runc"
    }
  },
  "DefaultRuntime": "runc",
  "Swarm": {
    "NodeID": "rpf6pl14wqdfflld4ucnol6vv",
    "NodeAddr": "172.17.0.4",
    "LocalNodeState": "active",
    "ControlAvailable": true,
    "Error": "",
    "RemoteManagers": [
      {
        "NodeID": "rpf6pl14wqdfflld4ucnol6vv",
        "Addr": "172.17.0.4:2377"
      }
    ],
    "Nodes": 1,
    "Managers": 1,
    "Cluster": {
      "ID": "vnvbiu5jzmnpifpuoh4fnqbv9",
      "Version": {
        "Index": 10
      },
      "CreatedAt": "2019-08-23T14:53:01.27730579Z",
      "UpdatedAt": "2019-08-23T14:53:01.806494184Z",
      "Spec": {
        "Name": "default",
        "Labels": {},
        "Orchestration": {
          "TaskHistoryRetentionLimit": 5
        },
        "Raft": {
          "SnapshotInterval": 10000,
          "KeepOldSnapshots": 0,
          "LogEntriesForSlowFollowers": 500,
          "ElectionTick": 10,
          "HeartbeatTick": 1
        },
        "Dispatcher": {
          "HeartbeatPeriod": 5000000000
        },
        "CAConfig": {
          "NodeCertExpiry": 7776000000000000
        },
        "TaskDefaults": {},
        "EncryptionConfig": {
          "AutoLockManagers": false
        }
      },
      "TLSInfo": {
        "TrustRoot": "-----BEGIN CERTIFICATE-----\nMIIBaTCCARCgAwIBAgIUY4cCisXijHGc5HcFT6btvtbTKKYwCgYIKoZIzj0EAwIw\nEzERMA8GA1UEAxMIc3dhcm0tY2EwHhcNMTkwODIzMTQ0ODAwWhcNMzkwODE4MTQ0\nODAwWjATMREwDwYDVQQDEwhzd2FybS1jYTBZMBMGByqGSM49AgEGCCqGSM49AwEH\nA0IABAdOynhsRr/Vu1Tywn/DePZ3OsjTC/339ipzL3MyAjhb80YMmY/2VCSjsi6p\nSjRWoFm68vv4Ej8z5NNSKbz/21ejQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMB\nAf8EBTADAQH/MB0GA1UdDgQWBBQ7MUuKM1+AbrAMKBiY8pFpRVz3njAKBggqhkjO\nPQQDAgNHADBEAiBe0+xXXlq1Sbm04VVeKeAO2sb5KeAd4EZ2ZRlpBggV6AIgPm+e\nTNJHMSg5WAXGXj4JGkRDqJfklmvLq2y5WjdYOME=\n-----END CERTIFICATE-----\n",
        "CertIssuerSubject": "MBMxETAPBgNVBAMTCHN3YXJtLWNh",
        "CertIssuerPublicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEB07KeGxGv9W7VPLCf8N49nc6yNML/ff2KnMvczICOFvzRgyZj/ZUJKOyLqlKNFagWbry+/gSPzPk01IpvP/bVw=="
      },
      "RootRotationInProgress": false,
      "DefaultAddrPool": [
        "10.0.0.0/8"
      ],
      "SubnetSize": 24,
      "DataPathPort": 4789
    }
  },
  "LiveRestoreEnabled": false,
  "Isolation": "",
  "InitBinary": "docker-init",
  "ContainerdCommit": {
    "ID": "894b81a4b802e4eb2a91d1ce216b8817763c29fb",
    "Expected": "894b81a4b802e4eb2a91d1ce216b8817763c29fb"
  },
  "RuncCommit": {
    "ID": "425e105d5a03fabd737a126ad93d62a9eeede87f",
    "Expected": "425e105d5a03fabd737a126ad93d62a9eeede87f"
  },
  "InitCommit": {
    "ID": "fec3683",
    "Expected": "fec3683"
  },
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "ProductLicense": "Community Engine",
  "Warnings": [
    "WARNING: bridge-nf-call-iptables is disabled",
    "WARNING: bridge-nf-call-ip6tables is disabled"
  ],
  "ClientInfo": {
    "Debug": false,
    "Plugins": [],
    "Warnings": null
  }
}
```

### Outputing information about the Swarm Managers

```bash
docker info --format '{{ json .Swarm.RemoteManagers }}' | jq .
```
```json
[
  {
    "NodeID": "rpf6pl14wqdfflld4ucnol6vv",
    "Addr": "172.17.0.4:2377"
  }
]
```

Or, just the addresses;


```bash
docker info --format "{{range .Swarm.RemoteManagers}}{{.Addr}}
{{end}}"

172.17.0.4:2377
```

**Comment by thaJeztah** [comment] 2019-08-23 15:37
So, it looks like the problem you're running into is that you're trying to parse both `stdout` and `stderr`, which will fail.

Based on the above, I think this works as designed, so I'll close this issue, but I hope my examples help you further; feel free to continue the conversation after I closed the issue.

**Closed by thaJeztah** 2019-08-23 15:37 UTC
Labels: area/cli
