### ISSUE TITLE
Question: restore from backup docker folder

### ISSUE THREAD

**Issue by erguotou520** [moby/moby#34675] opened 2017-08-30 07:14 UTC
This is a usage question, not issue.
Recently my docker failed to start after I have updated my linux kernel. I searched some articles and mv `/var/lib/docker` to `/var/lib/docker.old`. Then reboot and mv `/var/lib/docker.old` to `/var/lib/docker` back. But this not solved my problem.  
Then I tried another method, `rm -rf /var/lib/docker/aufs`, and this successed. But `docker ps -a` and `docker images`  are all empty now. I have a lot important data in containers. How can I restore from the backup docker folder? The files in the backup folder are still existed.
![image](https://user-images.githubusercontent.com/7945757/29859674-cbfb21c4-8d95-11e7-8707-eae2772dd432.png)

**Comment by thaJeztah** [comment] 2017-09-25 14:21
> Recently my docker failed to start after I have updated my linux kernel.
> Then I tried another method, rm -rf /var/lib/docker/aufs, and this successed.

I suspect what happened is that you upgraded the kernel, without installing an updated version of the aufs kernel module; in that case, the daemon will refuse to start with a message that the "previously used storage driver is not supported". If the daemon fails to start, **always** read the logs before you take action; logs are there for a reason.

To resolve this, make sure you have the aufs kernel module installed, for example, as explained in the [installation docs for Ubuntu](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#recommended-extra-packages-for-trusty-1404).

> Then I tried another method, `rm -rf /var/lib/docker/aufs`, and this successed

Be aware that that directory contains your images and container's filesystem, so deleting that directory deletes all those.

>  I have a lot important data in containers

Never store important data on the containers filesystem; treat containers as "ephemeral"; you should be able to replace a container with a new version and don't loose important data. Anything that's important and should be preserved after a container is deleted should be stored in volumes (see https://docs.docker.com/engine/admin/volumes/ in the documentation).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-09-25 14:21 UTC
Labels: kind/question

**Comment by erguotou520** [comment] 2017-09-26 01:24
Thanks for your help. Finally I downgraded the kernel and copied the mysql volume.
