### ISSUE TITLE
xcopy not working when isolation is process

### ISSUE THREAD

**Issue by apetres** [moby/moby#38425] opened 2018-12-24 12:22 UTC
**Description**

When running xcopy in a windows container started with `--isolation=process` xcopy is crasing with `0xC0000139` without printing any output or copying any files.

**Steps to reproduce the issue:**
```
PS C:\> docker run --isolation=hyperv --name hyperv mcr.microsoft.com/windows/servercore:ltsc2016 xcopy
0 File(s) copied
Invalid number of parameters
PS C:\> docker run --isolation=process --name process mcr.microsoft.com/windows/servercore:ltsc2016 xcopy
PS C:\> docker ps -a
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS                               PORTS               NAMES
973775c6893c        mcr.microsoft.com/windows/servercore:ltsc2016   "xcopy"             13 seconds ago      Exited (3221225785) 11 seconds ago                       process
5b821bbae304        mcr.microsoft.com/windows/servercore:ltsc2016   "xcopy"             51 seconds ago      Exited (4) 35 seconds ago                                hyperv
```
**Expected**
The second command has the same output and exit code as the first one.

**Actual**
The second command failed with 3221225785 (0xC0000139)

**Additional information**
May be related to #24880

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:56:41 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 18.09.0
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard Evaluation Version 1607 (OS Build 14393.693)
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 7.999GiB
Name: hostname
ID: id
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by thaJeztah** [comment] 2018-12-24 20:01
@jstarks @johnstep PTAL

**Comment by olljanat** [comment] 2018-12-25 05:30
@apetres did I understand those prints right that you are running Docker CE version on Windows Server 2016?

That is very unsupported scenario. Please, uninstall that and install supported version https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server

I have no any Windows Server 2016 with latest Docker version but I quickly tested with combinations of:
* Win Srv 2016 + Docker EE 18.03
* Win Srv 2019 + Docker 18.09
and on both of them xcopy works just fine with process isolation mode.

How ever, I did not tested with latest version of servercore image so issue can be with that one too.

Please, try with Docker EE 18.03 first and then again with 18.09 but installed on official way and let us know how it looks.

**Comment by apetres** [comment] 2018-12-27 09:34
@olljanat Thanks for your response. I installed both Docker 18.03 and 18.09 the official way.
You may be right, the issue may be with the latest version of Windows Server 2016 Core because I managed to reproduce the issue with both versions of Docker.

Here are the outputs:
**18.09**
```
C:\> docker run --isolation=hyperv --name hyperv mcr.microsoft.com/windows/servercore:ltsc2016 xcopy
0 File(s) copied
Invalid number of parameters

C:\> docker run --isolation=process --name process mcr.microsoft.com/windows/servercore:ltsc2016 xcopy

C:\> docker ps -a
CONTAINER ID        IMAGE                                           COMMAND             CREATED             STATUS                              PORTS               NAMES
254cd7519312        mcr.microsoft.com/windows/servercore:ltsc2016   "xcopy"             6 seconds ago       Exited (3221225785) 4 seconds ago                       process
5d07995d374a        mcr.microsoft.com/windows/servercore:ltsc2016   "xcopy"             34 seconds ago      Exited (4) 17 seconds ago                               hyperv

C:\> docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.3
 Git commit:        33a45cd0a2
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       33a45cd0a2
  Built:            11/07/2018 00:24:12
  OS/Arch:          windows/amd64
  Experimental:     false
  
C:\> docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 18.09.0
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard Evaluation Version 1607 (OS Build 14393.693)
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 7.999GiB
Name: apetres-ws2016
ID: id
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**18.03**
```
C:\>docker run --isolation=hyperv --name hyperv mcr.microsoft.com/windows/servercore:ltsc2016 xcopy
0 File(s) copied
Invalid number of parameters

C:\>docker run --isolation=process --name process mcr.microsoft.com/windows/servercore:ltsc2016 xcopy

C:\>docker ps -a
CONTAINER ID        IMAGE                                           COMMAND             CREATED             STATUS                              PORTS               NAMES
a5d4bd0f27cb        mcr.microsoft.com/windows/servercore:ltsc2016   "xcopy"             9 seconds ago       Exited (3221225785) 6 seconds ago                       process
c65f6ac2ce4c        mcr.microsoft.com/windows/servercore:ltsc2016   "xcopy"             3 minutes ago       Exited (4) 2 minutes ago                                hyperv

C:\>docker version
Client:
 Version:           18.03.1-ee-4
 API version:       1.37
 Go version:        go1.10.2
 Git commit:        0ded23c
 Built:             Thu Oct 25 00:41:52 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.03.1-ee-4
  API version:      1.37 (minimum version 1.24)
  Go version:       go1.10.2
  Git commit:       0ded23c
  Built:            Thu Oct 25 00:56:17 2018
  OS/Arch:          windows/amd64
  Experimental:     false

C:\>docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 18.03.1-ee-4
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard Evaluation Version 1607 (OS Build 14393.693)
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 7.999GiB
Name: apetres-ws2016
ID: G5GS:id
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
cpus: 1
Total Memory: 7.999GiB
Name: apetres-ws2016
ID: G5GS:id
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2018-12-27 09:37
ping @jstarks @jhowardmsft ptal

**Comment by jhowardmsft** [comment] 2019-03-22 04:54
What exactly are you expecting to happen running xcopy with no parameters? It's not a valid command. Can you give a real-world example where this difference in output is actually an issue, or something that fails as a result? Architecturally, process and Hyper-V isolation are dramatically different. I don't think anyone will look at this without a real-world example. For that reason, I'm closing here. Please re-open if you can come up with something. Thanks

**Closed by jhowardmsft** 2019-03-22 04:54 UTC
Labels: kind/bug, platform/windows

**Comment by thaJeztah** [comment] 2019-03-22 09:16
Shouldn't it produce the same error in both cases? ("Invalid number of arguments")

**Comment by jhowardmsft** [comment] 2019-03-22 18:41
It does on master moby/moby; verified all 4 combinations on both RS1 and RS5:

```
PS E:\go\src\github.com\docker\docker> docker run --rm microsoft/nanoserver xcopy
Invalid number of parameters
0 File(s) copied
PS E:\go\src\github.com\docker\docker> docker run --isolation=hyperv --rm microsoft/nanoserver xcopy
Invalid number of parameters
0 File(s) copied
PS E:\go\src\github.com\docker\docker> docker run --rm microsoft/windowsservercore xcopy
Invalid number of parameters
0 File(s) copied
PS E:\go\src\github.com\docker\docker> docker run --rm --isolation=hyperv microsoft/windowsservercore xcopy
0 File(s) copied
Invalid number of parameters
```

**Comment by TBBle** [comment] 2021-05-28 10:32
For posterity, 0xC0000139 (`STATUS_ENTRYPOINT_NOT_FOUND`) is the same error seen when hitting the 32-bit ABI mismatch around the [February 2020 container/host version mismatch issue](https://support.microsoft.com/en-us/topic/you-might-encounter-issues-when-using-windows-server-containers-with-the-february-11-2020-security-update-release-b9a8fcae-950d-7a0b-ac7c-cb6b294cb809), e.g., https://github.com/microsoft/dotnet-framework-docker/issues/523.

So in retrospect, it's likely that this was an 'old host/new servercore image' issue, which is why it was hard to reproduce if you just grabbed a machine with an existing working container image (https://github.com/moby/moby/issues/38425#issuecomment-449804264), or tried it years later (https://github.com/moby/moby/issues/38425#issuecomment-475736245) when presumably the host was up-to-date.

I'd guess it was pivoting around [December 19, 2018—KB4483229 (OS Build 14393.2670)](https://support.microsoft.com/en-us/topic/december-19-2018-kb4483229-os-build-14393-2670-1efb3ef5-a9cb-d991-53d1-03342dcfce91) based on the report timing, but there's no logs here of the servercore image version in question. The _host_ was 14393.693, from [January 2017](https://support.microsoft.com/en-us/topic/january-10-2017-kb3213986-os-build-14393-693-95a9b52f-1357-7dbc-e956-634e8becf4ec) so this was quite likely not a heavily-tested scenario, unlike the Feb 2020 issue which seemed to get hit by a lot of people.

And if this wasn't just a before-after single version issue, but a "host older than X, with container newer than Y" issue, then the likely reproductions werre perhaps limited to people who haven't applied security updates to their server in over a year.

I'm only looking at this because a project I help with has a workaround pointing to this bug, and no further details recorded.
