### ISSUE TITLE
In Swarm Mode, can we increase stats, exec for services? 

### ISSUE THREAD

**Issue by zhengqisong** [moby/moby#36942] opened 2018-04-25 05:52 UTC
In Swarm Mode, can we increase stats, exec for services? 
eg:
docker service stats [OPTIONS] SERVICE|TASK
docker service exec [OPTIONS] SERVICE|TASK

**Comment by bsousaa** [comment] 2023-07-17 13:42
Closing this issue as a duplicate of https://github.com/moby/moby/issues/27552.

**Closed by bsousaa** 2023-07-17 13:42 UTC
