### ISSUE TITLE
registry v2 push image error: Error: Status 404 trying to push repository centos: "404 page not found\n"

### ISSUE THREAD

**Issue by jkzhao** [moby/moby#34622] opened 2017-08-24 09:57 UTC
**Push images to registry v2: Error: Status 404 trying to push repository centos: "404 page not found\n"**
```
[root@node1 ~]# docker push registry2.wisedu.com/jkzhao/centos
The push refers to a repository [registry2.wisedu.com/jkzhao/centos]
b362758f4793: Pushing [==================================================>] 192.5 MB
Error: Status 404 trying to push repository jkzhao/centos: "404 page not found\n"
```
**Steps to reproduce the issue:**
1.
```
[root@node1 certs.d]# docker login registry2.wisedu.com
Username: jkzhao
Password: 
Login Succeeded
```
2.`[root@node1 ~]# docker pull centos`
3. `[root@node1 ~]# docker tag docker.io/centos registry2.wisedu.com/jkzhao/centos:v1`
4. `[root@node1 ~]# docker push registry2.wisedu.com/jkzhao/centos`

**Describe the results you received:**
```
[root@node1 ~]# docker push registry2.wisedu.com/jkzhao/centos
The push refers to a repository [registry2.wisedu.com/jkzhao/centos]
b362758f4793: Pushing [==================================================>] 192.5 MB
Error: Status 404 trying to push repository jkzhao/centos: "404 page not found\n"
```

**Describe the results you expected:**
The images should be pushed  successfully.

**Output of `docker version`:**
```
[root@node1 ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**
```
[root@node1 ~]# docker info
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 3
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-70191505-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 869.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 26.17 GB
 Metadata Space Used: 1.827 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 4.5.2-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 3.859 GiB
Name: node1
ID: ZFVS:PY5G:6PUV:HQRQ:FDWD:JT7U:VMQE:25EB:BCDZ:NVMO:ASKA:LMPL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
virtual machine

**Comment by ripcurld0** [comment] 2017-08-24 10:09
From what I know version `1.12` is very old.
Do you mind trying to reproduce it on newer version like `17.06`?

**Comment by cpuguy83** [comment] 2017-08-25 14:28
It would appear that registry2.wisedu.com is not operating correctly.
Also note you appear running an unsupported version of docker which has changes specifically around how registries are handled.

Closing since this doesn't really look like an issue on moby/moby's side, but feel free to discuss.

**Closed by cpuguy83** 2017-08-25 14:28 UTC
Labels: area/distribution, version/1.12
