### ISSUE TITLE
Docker (machine) exits with "Result: error-code"

### ISSUE THREAD

**Issue by jacobrask** [moby/moby#33907] opened 2017-06-30 22:10 UTC
**Description**

Docker fails to start on a machine created with `docker-machine`. 

**Steps to reproduce the issue:**
run `docker-machine create --driver digitalocean --digitalocean-access-token=*** --digitalocean-region=ams2 --digitalocean-size=1gb test`

**Describe the results you received:**

```
Running pre-create checks...
Creating machine...
(test) Creating SSH key...
(test) Creating Digital Ocean droplet...
(test) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

```
root@test:~# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-machine.conf
   Active: failed (Result: exit-code) since Fri 2017-06-30 21:56:13 UTC; 38s ago
     Docs: https://docs.docker.com
  Process: 5384 ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --
 Main PID: 5384 (code=exited, status=1/FAILURE)
      CPU: 15ms
```

**Describe the results you expected:**
A working Docker machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

I did a factory reset of Docker but it made no difference.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: HY2M:BHPD:C5UX:VAWA:7W2Y:BEVP:L6IK:IIBP:4TWI:DJFA:67AH:EA3Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 36
 System Time: 2017-06-30T22:08:50.061201382Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2017-07-01 12:40
Please try with the latest docker-machine patch: https://github.com/docker/machine/releases/tag/v0.12.1

**Comment by siavash9000** [comment] 2017-07-02 20:13
I am running into the same problem, with docker-machine 0.12.1. The failure occures with the generic driver.

**Comment by thaJeztah** [comment] 2017-07-02 21:20
Did you re-create the machine? The bug in docker machine 0.12.0 was in provisioning the machine

**Comment by siavash9000** [comment] 2017-07-02 21:51
yes I did recreate the machine, the problem persists. What worked lastly was 
`--engine-storage-driver=overlay` as parameter for `docker-machine create`.
Seems to be duplicate of https://github.com/docker/machine/issues/4156

**Comment by thaJeztah** [comment] 2023-09-16 17:50
Let me close this ticket for now, as it looks like it went stale and docker machine is deprecated

**Closed by thaJeztah** 2023-09-16 17:50 UTC
Labels: version/17.06
