### ISSUE TITLE
Problem launching a container from a backedup image

### ISSUE THREAD

**Issue by stevoboy** [moby/moby#42985] opened 2021-11-02 18:05 UTC
Dear all,

probably this is a rather stupid question. I made an export of my docker iobroker container that has been running on my Synology NAS DSM 7.0. After some experimenting, I wanted to import the container again to restore it. However, I cannot make it work again. The following steps did I take:

Export:
1. Stop container
![image](https://user-images.githubusercontent.com/84937873/139920094-af50577b-b4b8-48f5-bf1c-c1933c3c811d.png)
2. Export
![image](https://user-images.githubusercontent.com/84937873/139920144-f8dc8206-1305-4346-8f72-a1c25bb1d8f5.png)
3. renaming of image file to lower case to avoid import issues
![image](https://user-images.githubusercontent.com/84937873/139920384-ce282040-acac-4692-82cb-5909a019d115.png)

Import:
1. Import
![image](https://user-images.githubusercontent.com/84937873/139920525-08d64768-8a28-4b86-9795-4640ef45a450.png)
2. Interestingly, only an image is added, no container appears which seems to be different than before.
![image](https://user-images.githubusercontent.com/84937873/139920631-1e3c0525-573a-4d71-a39f-03af5b2394ff.png)
3. Launch of image
![image](https://user-images.githubusercontent.com/84937873/139920670-a22f50f5-3e5e-4f19-ab4f-b4815bd24813.png)
4. Launching with or without settings:
![image](https://user-images.githubusercontent.com/84937873/139920764-758c4a2d-b741-4773-a0fc-13462acae741.png)
5. Error message:
![image](https://user-images.githubusercontent.com/84937873/139920829-00bd253a-d23c-40fe-928d-058a965d4000.png)
6. Log 
![image](https://user-images.githubusercontent.com/84937873/139920871-0579f443-51a5-4a1b-83c9-993d70bbec6f.png)

Can anybody tell me what I need to do? I assume it is due to the wrong execution command.

**Comment by thaJeztah** [comment] 2021-11-02 21:56
`docker container export` exports a container's `rootfs` (filesystem), so you don't get a "copy of your container", nor a full "image", but only the files (excluding any files that were stored in volumes attached to the container);

```bash
docker export --help

Usage:  docker export [OPTIONS] CONTAINER

Export a container's filesystem as a tar archive

Options:
  -o, --output string   Write to a file, instead of STDOUT
```

When "importing" the exported tar, you will have an image without any configuration, such as environment variables, the command to run, etc, etc.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

Perhaps the Synology support forums may be a good place for this, as I don't know what exact API endpoints their UI uses for these actions, and because there's no official builds for that platform, and Synology builds the version of Docker running on their systems.


I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-11-02 21:56 UTC

**Comment by stevoboy** [comment] 2021-11-03 08:00
Dear Sebastian,

thanks a lot for your help.

I am going to post my question to one of the locations above.

Strangely, the export/import procedure worked in September. In September, I exported up my docker container and managed to import it yesterday without having to set-up anything. It worked right away - an new container is being set up that can be started immediately. 
With the export I did yesterday, this didn't work anymore. When importing it, it did not create a container but only an image. Something must have changed - or I did something differently that I do not remember.
