### ISSUE TITLE
Ports not getting published for stack/service

### ISSUE THREAD

**Issue by Vacant0mens** [moby/moby#33902] opened 2017-06-30 19:14 UTC
**Description**
when running a 'docker stack deploy' for a stack, the 'ports:' node in the yaml/stack/compose file seems to get ignored. Also, when running 'docker service update --publish-add' nothing changes for the stack's service.

**Steps to reproduce the issue:**
1. run a 'docker stack deploy -c [composefile].yml --with-registry-auth [stackname]' command with a stack/compose file that has a 'ports:' config node for the service (the port i'm trying to publish is 10125:80 or 10125:10125, either will work for my needs)
NOTE - Host has 2 physical network ports, and is swarm-joined as manager.

**Describe the results you received:**
docker container inspect [container] shows no ports published under "NetworkSettings": {"Ports":} nor "HostConfig":{ "PortBindings":}, however, 'docker container list' shows only '80/tcp' under the "PORTS" column.
'netstat -ano' shows no ports listening on the ports listed in the stack/compose file

**Describe the results you expected:**
Any ports listed with proper syntax under the "ports:" node in the stack/compose file should be published and available upon deploy.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running on Windows Server 2016 Core, I stopped the docker service and replaced the 17.03-ee version of the docker.exe and dockerd.exe binaries with the version I'm currently running (see below).

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: lpiiypps4syxypp0he5xfex5d
 Is Manager: true
 ClusterID: e1t83w9bh5ipu0ellmg4gxkwf
 Managers: 4
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.0.3.233
 Manager Addresses:
  10.0.3.169:2377
  10.0.3.224:2377
  10.0.3.233:2377
  10.0.3.249:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1358.amd64fre.rs1_release.170602-2252)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 2GiB
Name: GPSDWZ-IA
ID: MF3L:JAY7:AOEM:WK7Y:BNPS:4JBG:JETJ:YWTU:AGH3:WR4S:RHCA:JDWU
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 resgistry1:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by Vacant0mens** [comment] 2017-06-30 19:25
Update: this problem does not occur with a 'docker run' command.

**Comment by thaJeztah** [comment] 2017-07-03 04:01
> docker container inspect [container] shows no ports published under "NetworkSettings": {"Ports":} nor "HostConfig":{ "PortBindings":}, however, 'docker container list' shows only '80/tcp' under the "PORTS" column.

This is expected. When publishing service ports, container ports are not published directly, but published through the built-in load-balancer.

Using this docker-compose;

```yaml
version: '3.2'

services:
  web:
    image: "nginx:alpine"
    ports:
      - "10125:80"
```

Deployg the stack:

```bash
$ docker stack deploy -c docker-compose.yml repro-33902

Creating network repro-33902_default
Creating service repro-33902_web
```

And after the stack is deployed, the container's ports are _not_ published.

```bash
$ docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
75a8f86deba0        nginx:alpine        "nginx -g 'daemon ..."   30 seconds ago      Up 28 seconds       80/tcp                 repro-33902_web.1.daahv67hx09lk5fo2wjiiogx0
```

However, inspecting the _service_ shows that the ports are published for the _service_:

```bash
$ docker service inspect --pretty  repro-33902_web

ID:		ug8y0s7ie0pfbq9apykcm3z0y
Name:		repro-33902_web
Labels:
 com.docker.stack.image=nginx:alpine
 com.docker.stack.namespace=repro-33902
Service Mode:	Replicated
 Replicas:	1
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:		nginx:alpine@sha256:13231e43f4e28866a418609a53dd7aee03442a4f8c9bdbacd5b7864a8fc52444
Resources:
Networks: repro-33902_default
Endpoint Mode:	vip
Ports:
 PublishedPort = 10125
  Protocol = tcp
  TargetPort = 80
  PublishMode = ingress
```

I don't see anything wrong there, but without the exact steps to reproduce (e.g. an example image and docker-compose file), it's difficult to tell

**Comment by Vacant0mens** [comment] 2017-07-03 14:38
Below is my compose.yml file. I built a custom nginx image (based on someone else's dockerfile), so I'll include the dockerfile for it after the compose file. Outside of the compose file, I'm not doing anything out of the ordinary other than a `--with-registry-auth` parameter so that the image can be pulled from our local registry with no problems. But every time I go to connect to the service port via browser, it either times out or gives me some kind of "could not connect" error. I did a `Test-NetConnection` in powershell also, and the tcp connect for both ports came up false also. 

Normally if nginx was working (with ports and all) it would throw up an nginx error page that saying couldn't get to the backend server, right?

`version: '3.3'
services:
#Begin application.webapi
#
  applicationweb:
    image: registry1:5000/application/web:1.2017.0628.2
# credential_spec may get ignored until it's fully supported (should be in 17.06)
    credential_spec:
      file: "gMSA-125.json"
    environment:
      - APPLICATIONSETTINGS__ENVIRONMENT=Dev
      - CONNECTIONSTRINGS__CREDENTIALSCONNECTIONSTRING=Data Source=dbserv-125;Initial Catalog=Vault;Integrated Security=True
      - ASPNETCORE_URLS=http://*:80
      - SERILOG__MINIMUMLEVEL=Verbose
      - SERILOG__WRITETO__0__NAME=Seq
      - SERILOG__WRITETO__0__ARGS__SERVERURL=http://Devlogs:5500
      - SERILOG__WRITETO__0__ARGS__APIKEY=5nNfgHm81wo09EknmmDt
      - SERILOG__PROPERTIES__INSTITUTIONID=125
      - SERILOG__PROPERTIES__ENVIRONMENT=Dev
      - BUSSETTINGS__CREDENTIALSID=Bus
      - BUSSETTINGS__HOSTNAME=MQ1.hostname.com
      - BUSSETTINGS__VIRTUALHOST=125
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.servertype==web
#End application.webapi
#Begin NGinX
#
  nginx1:
    image: registry1:5000/nginx/nanoserver
    volumes:
      - E:\Dev\125:C:\nginx\xconf
    ports:
      - "10125:10125"
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.servertype==web
         - node.labels.serverletter==a
  nginx2:
    image: registry1:5000/nginx/nanoserver
    volumes:
      - E:\Dev\125:C:\nginx\xconf
    ports:
      - "20125:20125"
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.servertype==web
         - node.labels.serverletter==b
#End NGinX
#End of file`
```
FROM microsoft/nanoserver:latest
ENV VERSION 1.11.13

SHELL ["powershell", "-command"]
RUN Invoke-WebRequest -Uri https://www.nginx.kr/nginx/win64/nginx-$ENV:VERSION-win64.zip -OutFile c:\nginx-$ENV:VERSION-win64.zip; \
	Expand-Archive -Path C:\nginx-$ENV:VERSION-win64.zip -DestinationPath C:\ -Force; \
	Remove-Item -Path c:\nginx-$ENV:VERSION-win64.zip -Confirm:$False; \
	Rename-Item -Path nginx-$ENV:VERSION-win64 -NewName nginx; \
	New-Item -Type directory C:\nginx\xconf

# Make sure that Docker always uses default DNS servers which hosted by Dockerd.exe
RUN Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters" -Name ServerPriorityTimeLimit -Value 0 -Type DWord; \
	Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters" -Name ScreenDefaultServers -Value 0 -Type DWord; \
	Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters" -Name ScreenUnreachableServers -Value 0 -Type DWord
	
# Shorten DNS cache times
RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name MaxCacheTtl -Value 30 -Type DWord; \
	Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name MaxNegativeCacheTtl -Value 30 -Type DWord

WORKDIR /nginx
EXPOSE 80
CMD ./nginx.exe -c C:\nginx\xconf\nginx.conf
`

**Comment by Vacant0mens** [comment] 2017-07-03 17:51
Is this something to do with Mesh Routing for stacks/services in Windows?

**Comment by Vacant0mens** [comment] 2017-07-03 18:39
I switched the stack file to 'long syntax' like this:
```
    ports:
      - target: 10#{Inst}
        published: 80
        mode: host
```
the 'ports' section in `docker service inspect --pretty` shows pretty much the same thing, but with 
```
Ports:
 PublishedPort = 80
  Protocol = tcp
  TargetPort = 10125
  PublishMode = host
```
But I'm still getting `ERR_EMPTY_RESPONSE` in the browser.

**Comment by thaJeztah** [comment] 2017-07-03 20:05
Note that when using `mode: host`, the routing mesh is not used, and containers are published directly, as a result, only a single instance of the service can run on each node, and the service will only be accessible on nodes where an instance is running.

However, the problem looks to be you're not using the right configuration to publish your ports. In the first example;

```yaml
    ports:
      - "10125:10125"
      - "80:80"
```

You are publishing:

- container's port `80` on port `80` on the host
- container's port `10125` on port `10125` on the host

So (unless the container is actually listening on port 10125), that won't work, because `nginx` would be listening on port `80`.

In the second example (long syntax), it looks like you swapped the ports;

```yaml
    ports:
      - target: 10#{Inst}
        published: 80
        mode: host
```

Here you publish container's port `10#{inst}` (`10125`) to port `80` on the host

Try using this;

```yaml
    ports:
      - target: 80
        published: 10#{Inst}
```

And it should probably work

**Comment by Vacant0mens** [comment] 2017-07-03 20:28
yeah, I caught that flip-flop a few minutes ago. I'm trying it out now. 
That and I built in `EXPOSE 80` into the backend container image (I noticed the 'expose' in the compose file was getting ignored). 

I meant to update before you commented.

It seems to be working now, but it seems like this should have been more clear at some point. **I don't think `expose` should be deprecated for stack/compose.**

**Comment by thaJeztah** [comment] 2017-07-03 20:36
> I don't think expose should be deprecated for stack/compose.

I haven't looked into this, but I suspect `expose` works when using `docker compose`, but not for `docker stack deploy`. `expose` / `EXPOSE` in practice is only used when using `-P` ("publish all") on `docker run`, and not supported for services (services require you to explicitly specify which ports should be published/mapped). Note that `expose` is only adding meta-data to the image/container and does not actually change the behaviour of the container (i.e., all ports of a container are "exposed" on the internal container-container network)

> It seems to be working now, but it seems like this should have been more clear at some point

Great! I'll go ahead and close this issue. Perhaps you would be willing to open an issue in the documentation issue tracker, pointing out which parts of the documentation could use improvements? https://github.com/docker/docker.github.io/issues

Also feel free to continue the conversation after I closed the issue :)

**Closed by thaJeztah** 2017-07-03 20:36 UTC
Labels: area/swarm, platform/windows, status/more-info-needed, version/17.06

**Comment by Vacant0mens** [comment] 2017-07-03 21:13
Is there a non-korean version of nginx for windows?

**Comment by thaJeztah** [comment] 2017-07-03 21:21
Looks like there is; http://nginx.org/en/download.html

**Comment by Vacant0mens** [comment] 2017-07-03 21:40
one that I can put in a nanoserver container (that will work)?
(putting those files into an image ends up with "Exited (1)" after starting.)

**Comment by friism** [comment] 2017-07-03 21:44
@Vacant0mens you can see how to build a Windows nginx image here: https://github.com/nginxinc/docker-nginx/pull/155/files

**Comment by Vacant0mens** [comment] 2017-07-03 21:49
the latest version of nginx for windows (put into a container) doesn't seem to do anything at all.

**Comment by Vacant0mens** [comment] 2017-07-05 16:25
running that version of nginx (1.12.0) works directly in windows 10, but it doesn't even bother starting in a container. :(

**Comment by Vacant0mens** [comment] 2017-07-05 22:30
Now it looks like there's a problem resolving the DNS name for my webserver container in the nginx container. Looks like it's pulling dns from the host's DNS server configuration. I got it to resolve once, but then it wouldn't resolve again. 

Any way to force DNS resolution through Docker's DNS before any others?

**Comment by thaJeztah** [comment] 2017-07-05 22:42
No, it you're running with "host" networking, the container uses the hosts network stack, so docker isn't in the middle of that (including dns resolution)

**Comment by Vacant0mens** [comment] 2017-07-05 23:04
So do I need to run it from ingress? I thought mesh routing wasn't
available in windows yet.

**Comment by Vacant0mens** [comment] 2017-07-06 14:57
`DNS Round-Robin is the only load balancing strategy supported on Windows.Routing mesh for Windows docker hosts is not yet supported, but will be coming soon.`
How are you supposed to Round-Robin with stack/service containers if you can't get to Docker's internal DNS to resolve their names?

**Comment by Vacant0mens** [comment] 2017-07-07 20:19
UPDATE: It looks like you can work around this by adding the `dns:` entry in the stack/compose.yml file. I'll have to test a little more to make sure, but it seems to be working.

**Comment by friism** [comment] 2017-07-07 23:53
> How are you supposed to Round-Robin with stack/service containers if you can't get to Docker's internal DNS to resolve their names?

If you're running a bunch of services on the same overlay network (eg. started with `docker stack deploy`) then those services can resolve one another using the service name as the hostname. Just be sure to use `--endpoint-mode dnsrr`. This will work, for example, for running a database and website on Docker swarm with the website accessing the database service using the database service name as the hostname.

For external access to services running on Swarm on Windows you should use host-mode publish. This can be done with `docker service create` and `docker stack deploy`. Details here: https://github.com/moby/moby/issues/32326#issuecomment-313526655

**Comment by Vacant0mens** [comment] 2017-07-08 00:07
I did do the host-mode publish, and I also added the `dns:` option to the stack/compose.yml file. That seems to be the winning combination. (at least until Routing Mesh is available)

**Comment by Vacant0mens** [comment] 2017-07-11 16:12
So I guess it's not really a winning combination, @friism .

Looks like it resolves the addresses properly, but then it goes out to the external/host network to connect to the IP's instead of connecting to them internally. Any way to fix that? (ingress/service subnet uses the same address space as the subnet the hosts are on)

**Comment by Vacant0mens** [comment] 2017-08-10 15:15
SOLUTION: To get around not having mesh routing, create a custom stack network and specify the subnet. Then, in the nginx service section, use host-port-mapping method (long syntax), specify the dns as the x.x.x.1 address of the subnet specified, and specify the custom network for the service. Replicate the instance of nginx to each of the web-hosting Docker hosts.

**Comment by Vacant0mens** [comment] 2017-08-23 17:45
@thaJeztah or @friism , 
I'm running into a big performance hit using nginx as a proxy into the swarm to my webservers. I'm trying to get nginx (in a windowsservercore container) to dynamically update itself with the DNS names/addresses of the current running containers upon web request (so when a service restarts and a new container gets created, I don't have to manually update the config and reload nginx).

I'm having our external load balancer (a dev-labs F5 virtual appliance) add a header to the http request. The header includes the full name of the service, which is the docker-dns name of the containers (with dnsrr enabled), but nginx keeps throwing the error: `invalid URL prefix in "http://"`

my nginx.conf file has the following lines in the `location / {` section:
```
set $server $http_x_server_select;
proxy_pass http://$server;
```
This should dynamically resolve the docker-dns names of the services to the ip's of the current running containers, right? or am I just doing it wrong?

Also, is there any word on when MeshRouting will be available on Windows?

**Comment by scyto** [comment] 2020-06-11 06:32
> Note that when using `mode: host`, the routing mesh is not used, and containers are published directly, as a result, only a single instance of the service can run on each node, and the service will only be accessible on nodes where an instance is running.
> 
> However, the problem looks to be you're not using the right configuration to publish your ports. In the first example;
> 
> ```yaml
>     ports:
>       - "10125:10125"
>       - "80:80"
> ```
> 
> You are publishing:
> 
> * container's port `80` on port `80` on the host
> * container's port `10125` on port `10125` on the host
> 
> So (unless the container is actually listening on port 10125), that won't work, because `nginx` would be listening on port `80`.
> 
> In the second example (long syntax), it looks like you swapped the ports;
> 
> ```yaml
>     ports:
>       - target: 10#{Inst}
>         published: 80
>         mode: host
> ```
> 
> Here you publish container's port `10#{inst}` (`10125`) to port `80` on the host
> 
> Try using this;
> 
> ```yaml
>     ports:
>       - target: 80
>         published: 10#{Inst}
> ```
> 
> And it should probably work

This fixed an issue i am having on the following docker platform.

alexb@SYN01:/tmp$ docker version
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

issue details https://www.reddit.com/r/portainer/comments/h0sidd/trying_to_deploy_portainer_using_a_stack_cant/

should the issue be fixed on my platform or is the some other issue with the yaml file in the linked post when being used with stack deploy?

**Comment by thaJeztah** [comment] 2020-06-11 07:12
The long syntax is documented in the compose-file v3 reference; https://docs.docker.com/compose/compose-file/#long-syntax-1
