### ISSUE TITLE
OCI runtime create failed

### ISSUE THREAD

**Issue by zhanghhuc** [moby/moby#36015] opened 2018-01-15 12:38 UTC
**Steps to reproduce the issue:**
my linux is Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

1.install docker-ce
2.docker run hello-world

then i got prompt:
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/94c768a9eed223bdf5ed0922cb18238890eb9e6c37b9233aded7935a5a0dd0f1/log.json: no such file or directory): docker-runc did not terminate sucessfully: unknown.

**Comment by ripcurld0** [comment] 2018-01-15 12:44
@zhanghhuc can you copy-paste `docker info` and `docker version` outputs here?

What happens when you do `sudo docker run hello-world`?

**Comment by zhanghhuc** [comment] 2018-01-15 12:52
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 18.01.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-101739722-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 740.6MB
 Data Space Total: 107.4GB
 Data Space Available: 11.02GB
 Metadata Space Used: 1.72MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: N/A (expected: b2567b37d7b75eb4cf325b77297b140ea686ce8f)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.5MiB
Name: localhost.localdomain
ID: 2NNZ:JJCA:TJ6U:5IT7:P4A5:7GD4:WOLO:E4GH:5Q2X:TTVB:4SF7:GRYF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://d063d17f.m.daocloud.io/
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by zhanghhuc** [comment] 2018-01-15 12:53
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:07:19 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:10:58 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by zhanghhuc** [comment] 2018-01-15 12:54
print same information when use sudo docker run hello-world

**Comment by ripcurld0** [comment] 2018-01-15 13:00
@cpuguy83 @thaJeztah could it be because of the kernel version: `3.10.0-327`.

**Comment by zhanghhuc** [comment] 2018-01-15 13:08
OK，i'm try upgrade kernel

**Comment by thaJeztah** [comment] 2018-01-15 13:18
This is a duplicate of https://github.com/moby/moby/issues/35906; you're running an obsolete version of CentOS, and likely have an outdated version of llibseccomp installed.

CentOS uses a rolling release model, which means that when CentOS 7.2 was released, CentOS 7.1 became obsolete. Docker only is able to support the current version of CentOS (which is 7.4 at this time of writing); see the [installation docs](https://docs.docker.com/engine/installation/linux/docker-ce/centos/#prerequisites);

> To install Docker CE, you need a maintained version of CentOS 7. Archived versions aren’t supported or tested.

closing this issue, because this is a duplicate, and because this version of CentOS is too old, and no longer supported, but feel free to continue the conversation

**Closed by thaJeztah** 2018-01-15 13:18 UTC
Labels: area/runtime
