### ISSUE TITLE
[Feature Request] To support passing host device path(--devices=/dev/device-name) in SWARM mode.

### ISSUE THREAD

**Issue by sudharkrish** [moby/moby#35028] opened 2017-09-29 01:03 UTC
We have a use-case, where containers part of swarm, need to access host system driver, for hardware support on the target node, where it can get deployed, as part of swarm.

This is a feature request, to support, passing --devices=/dev/device-name, just like how it is supported in docker run command.

Just like --network=host option was recently added to swarm mode, it would also make sense to add support, to leverage hardware support by allowing access to specific devices on the target node, part of swarm.

So, for example:
sudo docker service create --name new_service --device=/dev/device-name --network=host image:latest

**Comment by fntlnz** [comment] 2017-09-29 01:22
@sudharkrish there's an ongoing discussion for parameters support in service create, please refer to: https://github.com/moby/moby/issues/25303

Closing as duplicate

**Closed by fntlnz** 2017-09-29 01:22 UTC
Labels: area/swarm, kind/feature

**Comment by fntlnz** [comment] 2017-09-29 01:25
Duplicate of: https://github.com/moby/moby/issues/24865
Tracked in swarmkit as: https://github.com/docker/swarmkit/issues/1244
