### ISSUE TITLE
prevent swarm from overcommitting resources in the host

### ISSUE THREAD

**Issue by Shashwatsh** [moby/moby#34989] opened 2017-09-26 18:05 UTC
n00b question
i have 3 swarm nodes with 32G of memory each and if i deploy 128 replicas of nginx with 1G memory limit each. i would be overcommitting memory. is there any way prevent this? like setting the max limit of certain number cluster/replicas per node

P.S sorry for my english, it's not my first language

**Comment by mostolog** [comment] 2017-10-10 20:11
That’s how overprovisioning is intended to work.
Probably, if you use reservation constraints, you won’t be able to run so many nginx instances.

This QUESTION shouldn’t be here, but in docker forum. Github is intended for bugs, features...but not for asking.

**Comment by Shashwatsh** [comment] 2017-10-10 20:17
umm.. sorry about asking question here, i did not know that there is a forum. 

can you show me some examples of doing this with "reservation constraints"?

**Comment by mostolog** [comment] 2017-10-11 07:28
https://docs.docker.com/compose/compose-file/#resources ;)

**Comment by thaJeztah** [comment] 2017-10-11 09:22
The short answer is; when scheduling services, docker looks at the amount of resources that you ask to be _reserved_ for the each service's instance (using the `--reserve-memory` and `--reserve-cpu` options). For example, if you reserve 512MB of memory for a service, and the host has 1GB of memory available, maximum two instances of the service will be deployed on the host.

The memory and cpu  _limit_ options (`--limit-memory` and `--limit-cpu`) limit what each instance is allowed to use, but does not prevent the _total_ of resources to be more than what the host has. Setting the limit higher than the reservation allows you to overcommit resources. Doing so can be useful if you want to deploy more instances per host than the available resources permit, but you know those instances only use the resources _some_ of the time.

As @mostolog mentioned; keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-10-11 09:22 UTC
Labels: area/swarm, kind/question
