### ISSUE TITLE
Terminal dimensions are being swapped

### ISSUE THREAD

**Issue by hoefling** [moby/moby#34124] opened 2017-07-15 13:25 UTC
**Description**
When running a container, the terminal height and width are swapped, so it looks like this:
![screenshot_20170715_151758](https://user-images.githubusercontent.com/4455652/28239619-a406be24-6970-11e7-8641-baf453368720.png)

**Steps to reproduce the issue:**
1. 
```bash
$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:a0ee7647e24c8494f1cf6b94f1a3cd127f423268293c25d924fbe18fd82db5a4
Status: Downloaded newer image for ubuntu:latest
```
2. 
```bash
$ stty size  # term size on host
38 149
```
3.
```bash
$ docker run -ti ubuntu
root@b453e6afcab3:/# stty size  # lines and columns in container are swapped
149 38
root@b453e6afcab3:/# 
```

**Describe the results you received:**
a terminal with 38 columns

**Describe the results you expected:**
a terminal with 149 columns

**Output of `docker version`:**
```
$ docker version
Client:                                                                  
 Version:      17.06.0-ce                                                   
 API version:  1.30                                                               
 Go version:   go1.8.3                                                               
 Git commit:   02c1d87                                                                   
 Built:        Tue Jul  4 14:01:42 2017                                                       
 OS/Arch:      linux/amd64                                                                         
                                                                                                   
Server:                                                                                                 
 Version:      17.06.0-ce                                                                                         
 API version:  1.30 (minimum version 1.12)                                                                        
 Go version:   go1.8.3                                                                                                     
 Git commit:   02c1d87                                                                                                     
 Built:        Tue Jul  4 16:00:03 2017                                                                                            
 OS/Arch:      linux/amd64                                                                                                               
 Experimental: false
```

**Output of `docker info`:**
```
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-0:44-92675452-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 467MB
 Data Space Total: 107.4GB
 Data Space Available: 12.61GB
 Metadata Space Used: 1.098MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.119 (2016-03-04)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d24f39e203aa6be4944f06dd0fe38a618a36c764 (expected: cfb82a876ecc11b5ca0977d1733adbe58599088a)
runc version: 2d41c04 (expected: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4)
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.1-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: hoefling-lenovo-L440
ID: 3UMK:W6MA:7Z27:N2II:EAEI:6MTF:YP7F:QZNB:GZ3F:M7ZF:TJKW:NJJ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 registry.buildserver.devnet.local
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Comment by thaJeztah** [comment] 2017-07-15 19:06
Thanks for reporting - this is a duplicate of https://github.com/moby/moby/issues/33910, and a bug in the Gentoo packages of Docker, not in the official packages (see  https://github.com/moby/moby/issues/33910#issuecomment-315037715)

I'll close this issue for the above reason, but feel free to comment after I closed!

**Closed by thaJeztah** 2017-07-15 19:06 UTC
Labels: area/distribution, version/17.06

**Comment by hoefling** [comment] 2017-07-15 19:10
Oops, sorry for disturbing then!

**Comment by thaJeztah** [comment] 2017-07-15 19:15
No worries!
