### ISSUE TITLE
Failed to start docker.service: Unit docker.service not found.

### ISSUE THREAD

**Issue by Kuchiriel** [moby/moby#35905] opened 2017-12-30 17:11 UTC
I have installed docker but I am unable to star his service.
*Failed to start docker.service: Unit docker.service not found.*

`Linux archlinux 4.14.9-1-ARCH #1 SMP PREEMPT Tue Dec 26 00:18:37 UTC 2017 x86_64 GNU/Linux`

**Comment by thaJeztah** [comment] 2017-12-30 19:26
Arch linux is not a supported distros; there are no packages for that distro

Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to comment after that

**Closed by thaJeztah** 2017-12-30 19:26 UTC
