### ISSUE TITLE
How can I download an output of a Python file inside a container to my host machine's dedicated folder?

### ISSUE THREAD

**Issue by python1980** [moby/moby#40005] opened 2019-09-28 20:01 UTC
I have a Python file that 1. Uses an API call to request specific data 2. Formats the data into a pandas data-frame 3. downloads the data as an xls file in the folder C:/Python/Sid.xls. 
I have this Python script inside a container but when I run the container I cannot see a file created as Sid.xls in C:/Python/Sid.xls                         
 
I tried the following command but its not working
```
docker run -v C:/Python: /eia imagename
```
Following is my Dockerfile

```Dockerfile
FROM python
WORKDIR  /eia
COPY .  /eia
RUN pip install EIA-python
RUN pip install requests
RUN pip install pandas
RUN pip install xlwt
RUN python C:/Sid/EIA.py
```

Following is my Python Code.

```python
import eia
import pandas as pd
api_key = "mykey"
api = eia.API(api_key)
series_storage = api.data_by_series(series='NG.NW2_EPG0_SWO_R48_BCF.W')
df1 = pd.DataFrame(series_storage)
df1.reset_index(inplace=True)
df1.columns = ['Date', 'Value']
df1['Date'] = pd.to_datetime(df1['Date'].str[:-3], format='%Y %m%d')
df1.to_excel("C:/Python/Sid.xls")
```

**Comment by thaJeztah** [comment] 2019-09-30 14:37
I see a couple of issues in your example;

First of all, the `RUN python C:/Sid/EIA.py` line is executed when _building_ the image (so during `docker build ...`), which means that if the file is written at that point, it's stored in the _image_ at the time of `docker build`

When _running_ your image as a container, you are bind-mounting a local directory _over_ the directory in the image;

```
-v C:/Python:/eia
```

When bind-mounting a directory from the host, anything that's in the directory you're bind-mounting will be mounted in the container, and the container is given access to that path on the host machine. However, it does not copy things from inside the container/image to that path, unless the container will create files during `docker run`

If you want the `EIA.py` script to run when you _start_ the container, you'll need to set it as the containers' main command; `CMD python C:/Sid/EIA.py`, or as an `ENTRYPOINT`. Be aware though, that a container runs a single process, and will exit after that process exits.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-09-30 14:37 UTC

**Comment by python1980** [comment] 2019-09-30 15:05
Thank you for assisting with my question. I really appreciate it. Really hate to bother you as I am not a programmer by profession but if you can comment on my code below it would be helpful. Even the code below is not generating a xls file in Python/Sid folder. I read that my stating VOLUME in Dockerfile should work but sadly it isnt.

Please tell me if I am wrong anywhere below? Also, can you tell if my syntax is wrong 
#Dockerfile
FROM python:latest
VOLUME ["C:/Python/Sid"]
WORKDIR /data
COPY . /data
RUN pip install EIA-python
RUN pip install requests
RUN pip install pandas
RUN pip install xlwt
EXPOSE 8888
CMD [ "python", "EIA.py" ]

#Python File
import eia
import pandas as pd
 
api_key = "5ea67740d334c5b495e7e37e206c467c"
api = eia.API(api_key)
series_storage = api.data_by_series(series='NG.NW2_EPG0_SWO_R48_BCF.W')
df1 = pd.DataFrame(series_storage)
df1.reset_index(inplace=True)
df1.columns = ['Date', 'Value']
df1['Date'] = pd.to_datetime(df1['Date'].str[:-3], format='%Y %m%d')
df1.to_excel("C:/Python/Sid.xls")

**Comment by thaJeztah** [comment] 2019-09-30 16:22
Looks like you accidentally posted your API key in your comment; I removed it (and removed it from the comment's history), but you may want to change that key if it was actually used, as it may have leaked now.

**Comment by thaJeztah** [comment] 2019-09-30 16:25
Can't really comment on your code (I'm not a Python developer, and don't know the framework you're using to generate the XLS)

I expect this line to be writing the XLS to the `C:\Python\` directory inside the container;

```python
df1.to_excel("C:/Python/Sid.xls")
```

However, when you run the container (looking at your top comment), it looks like you're expecting the XLS to be written in the `C:\eia\` directory;

```
docker run -v C:/Python:/eia
```
