### ISSUE TITLE
Docker pull fails in rootless mode: replaceDirWithOverlayOpaque("/etc/ca-certificates") failed

### ISSUE THREAD

**Issue by schklom** [moby/moby#42073] opened 2021-02-25 04:48 UTC
**Description**

With rootless Docker, pulling some images fails.

**Steps to reproduce the issue:**
1. `$ docker pull X`
2. Error

**Describe the results you received:**
```
296c9f0bf5f2: Pull complete
84d546321c8e: Extracting [==================================================>]  10.18MB/10.18MB
f91c8ffe2198: Download complete
df8d698654f0: Download complete
eb8f7931e7aa: Download complete
6516b36f67a7: Download complete
b9cb5520639b: Download complete
5d8642486473: Download complete
6e02b2205a05: Download complete
b00c506e6264: Download complete
022d51ec0eb7: Download complete
865a0188739c: Download complete
f150bf252527: Download complete
74bd31590bff: Download complete
failed to register layer: Error processing tar file(exit status 1): replaceDirWithOverlayOpaque("/etc/ca-certificates") failed: createDirWithOverlayOpaque("/etc/rdwoo287108235") failed: failed to mkdir /etc/rdwoo287108235/m/d: mkdir /etc/rdwoo287108235/m/d: input/output error
```

**Describe the results you expected:**
No error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:29:43 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:33:02 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.9.0-0.bpo.5-arm64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.631GiB
 Name: RpiTim
 ID: JEXP:SIXA:6AG6:CMB3:C6XY:MCMO:YITL:WT7V:NYBP:3PIB:3LPR:IDF6
 Docker Root Dir: /home/schklom/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The server is a Raspberry Pi 4 running on Debian 10
```
$ uname -a
Linux schklom 5.10.0-3-arm64 #1 SMP Debian 5.10.13-1 (2021-02-06) aarch64 GNU/Linux
$ cat /etc/subuid # same for subgid
...
schklom:165536:65536
```

**Comment by AkihiroSuda** [comment] 2021-02-25 05:33
Duplicate of https://github.com/docker/for-linux/issues/1055

# Workaround: use fuse-overlayfs

```bash
curl -o $HOME/bin/fuse-overlayfs -fsSL https://github.com/containers/fuse-overlayfs/releases/download/v1.4.0/fuse-overlayfs-$(uname -m)

chmod +x $HOME/bin/fuse-overlayfs

echo '{"storage-driver": "fuse-overlayfs"}' > ~/.config/docker/daemon.json

systemctl --user restart docker
```

**Closed by AkihiroSuda** 2021-02-25 05:33 UTC
Labels: area/rootless, area/storage/overlay
