### ISSUE TITLE
level=error msg="fatal task error" error="task: non-zero exit (1)"

### ISSUE THREAD

**Issue by kaasia** [moby/moby#33397] opened 2017-05-25 12:11 UTC
i want create a mysql service ,then i got this error:
```
May 25 08:03:57 localhost dockerd: time="2017-05-25T08:03:57.464472299-04:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module="node/agent/taskmanager" task.id=tbniz8vqkue3ecpgx1wtsoj94

May 25 08:03:58 localhost dockerd: time="2017-05-25T08:03:58.354676838-04:00" level=warning msg="failed to deactivate service binding for container bb_mysql.1.lq53yrk3nf4wljq05yohrsnhg" error="network sandbox does not exist for container bb_mysql.1.lq53yrk3nf4wljq05yohrsnhg" module="node/agent"
```

```
Version:      17.03.1-c
 OS/Arch:      linux/amd64   centos7
```

parts of yml file 
```
  mysql:

    image: 192.168.51.232:5000/mysql:latest

    deploy:

      resources:

        limits:

          cpus: "0.3"

          memory: 150M

    networks:

      - webnet
```
 
command :  `docker stack deploy -c docker-compose.yml aa`

**Comment by thaJeztah** [comment] 2017-05-30 09:22
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this looks like a support question.

When providing the steps to reproduce your issue, keep in mind that if those steps require custom images or source code, that others don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Closed by thaJeztah** 2017-05-30 09:22 UTC
