### ISSUE TITLE
Provide /stack API endpoint

### ISSUE THREAD

**Issue by mavogel** [moby/moby#35912] opened 2018-01-02 12:14 UTC
**Description**
I'd appreciate the API endpoint for `/stack` at the Docker API in order to deploy a composition of service in a `docker-compose.yml` file like it is possible on the command line
```sh
$ docker stack deploy -c my-compose.file.yml myStack
```

Kubernetes support this feature with a POD spec. See [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#pod-v1-core) for details.

**Output of `docker version`:**

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment] 2018-01-02 12:27
Looks like a duplicate of https://github.com/moby/moby/issues/32781 (and https://github.com/moby/moby/issues/26876, which is the tracking issue); TL;DR yes, plans are to eventually move stacks daemon-side, but it has not been a priority, so it's still implemented client-side

Let me close this one, because it duplicates the issues I linked to, but feel free to continue the conversation

**Closed by thaJeztah** 2018-01-02 12:27 UTC
Labels: area/api, area/bundles, version/17.09

**Comment by mavogel** [comment] 2018-01-02 12:57
Thx for the hint :)
