### ISSUE TITLE
image prune: add a pretend option

### ISSUE THREAD

**Issue by asarubbo** [moby/moby#39947] opened 2019-09-18 07:13 UTC
Would be great to have a pretend option for 'docker image prune' or at least show which images will be pruned before press 'y'.

Atm I can see:
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N]

**Comment by thaJeztah** [comment] 2019-09-18 11:21
Looks like this is a duplicate of https://github.com/moby/moby/issues/30623 (and partially https://github.com/moby/moby/issues/39418). For that last one, there's a work-in-progress pull request; https://github.com/moby/moby/pull/39419

Let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2019-09-18 11:21 UTC
