### ISSUE TITLE
Docker pull through a registry mirror with DockerHub login credentail

### ISSUE THREAD

**Issue by kkrisz1** [moby/moby#33071] opened 2017-05-07 19:12 UTC
**Description**

I use Nexus3 as a registry mirror (anonymous read is not allowed) - _behind Nginx_ -.
When I take a 'pull' command I see the following:
1. docker tries to get the image as anonymous mode from registry mirror
    - it will fail with HTTP error code: 401
1. docker tries to get the image with DockerHub credentail from registry mirror
    - it will fail with HTTP error code: 401, if account does not exist on Nexus3
    - _Note: it will success if i create an account on Nexus3 with the same user/password which is on DockerHub_
1. docker tries to get the image directly from DockerHub
    - It will success

Is it feasible to pass the registry mirror credentail (e.g.: with credentail-helpers) if docker uses registry mirror instead of DockerHub one?

**Steps to reproduce the issue:**
1. Content of the `~\.docker\config.json` file
    ```
    {
      "registry-mirrors": [
        "nexus3.registry.mirror.com"
      ],
      "insecure-registries": [],
      "experimental": false
    }
    ```
1. `docker login`
    ```
    Username: dockerHubUser
    Password: ********
    Login Succeeded
    ```
1. `docker login nexus3.registry.mirror.com`
    ```
    Username: nexus3User
    Password: ********
    Login Succeeded
    ```
1. `docker pull busybox`
    - Command output
        - _Note: It will be success, because image will be pulled directly from DockerHub, instead of pull through registry mirror_
        ```
        Using default tag: latest
        latest: Pulling from library/busybox
        7520415ce762: Pull complete
        Digest: sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f
        Status: Downloaded newer image for busybox:latest
        ```
    - (_Nginx_) access log
        ```
        a.b.c.d - - [dd/mm/yyyy:hh:mm:ss +0200] "GET /v2/ HTTP/1.1" 401 113 "-" "docker/17.03.1-ce go/go1.7.5 git-commit/c6d412e kernel/4.9.13-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.03.1-ce \x5C(windows\x5C))"
        a.b.c.d - dockerHubUser - [dd/mm/yyyy:hh:mm:ss +0200] "GET /v2/library/busybox/manifests/latest HTTP/1.1" 401 0 "-" "docker/17.03.1-ce go/go1.7.5 git-commit/c6d412e kernel/4.9.13-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.03.1-ce \x5C(windows\x5C))"
        ```

**Describe the results you received:**
dockerHubUser is used after anonymous read failed

**Describe the results you expected:**
nexus3User should have been used instead of DockerHub account

**Additional information you deem important (e.g. issue happens only occasionally):**
Related issues what I found without solution:
- #1486
- #17468
- #20097
- #30880
- #33069

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: BCTH:25V3:3JVR:C74M:YPHW:4C7O:PTL6:HMAA:6PUC:YJW2:GYDS:Y72C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 21
 System Time: 2017-05-07T18:59:28.9732777Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 nexus3.registry.mirror.org
Live Restore Enabled: false
```

**Comment by cpuguy83** [comment] 2017-05-08 14:47
Seems like this is a dup of #30880?

**Comment by kkrisz1** [comment] 2017-05-08 15:03
I mentioned it as part of "Additional information you deem important (e.g. issue happens only occasionally)"

**Comment by cpuguy83** [comment] 2017-05-08 15:04
@kkrisz1 Is it ok if we close this one?

**Comment by kkrisz1** [comment] 2017-05-08 15:25
Please keep this post, because i described much more details about the issue.
Let me know if I am wrong

**Comment by kkrisz1** [comment] 2017-05-08 15:29
So, let me give you more details about the differences between the two issue:
#30880 says that "Docker is not passing auth informations when pulling from a mirror registry"
BUT
It passes with DockerHub login credentail (If it exists in the credentail store)

**Comment by cpuguy83** [comment] 2017-05-08 15:42
We need to consolidate, and I think the issue is known just that no one has fixed it yet.

**Comment by kkrisz1** [comment] 2017-05-08 21:32
Would it be opened until it was fixed?
And a PR/fix can be created based on that description.

Or what do you suggest?
Which one describes the issue the most precisely?

**Comment by cpuguy83** [comment] 2017-05-08 21:35
Let's just keep the other issue, thanks!

**Closed by cpuguy83** 2017-05-08 21:35 UTC
Labels: area/distribution, version/17.03
