### ISSUE TITLE
Support --ip for host network

### ISSUE THREAD

**Issue by isanych** [moby/moby#31041] opened 2017-02-15 12:17 UTC
Feature request inspired by https://blog.jessfraz.com/post/ips-for-all-the-things/

Currently I run services which should have stable ip address in the next way:

- modify /etc/network/interfaces adding ip alias for service (so service will work after host reboot)
- restart network service
- docker run -p <ip_alias>...

And migration of this service to other docker host look like this

- old_host: docker stop
- old_host: modify /etc/network/interfaces removing ip alias for service
- old_host: restart network service
- new_host: modify /etc/network/interfaces adding ip alias for service
- new_host: restart network service
- new_host: docker run -p <ip_alias>...

and with --ip support migration will look like:

- old_host: docker stop
- new_host: docker run --net host --ip <ip_alias> ...

and there is no need in ssh access to docker host in such case, remote access to docker will be enough

**Comment by bsousaa** [comment] 2023-01-10 11:12
This is not possible by design since it would require changing the ip address of the host. [IPvlan](https://docs.docker.com/network/ipvlan/) or [macvlan](https://docs.docker.com/network/ipvlan/) may be good alternatives for your use case

I'm closing the issue for the moment, feel free to re-open if you have further comments.

**Closed by bsousaa** 2023-01-10 11:12 UTC
Labels: area/networking
