### ISSUE TITLE
Random no route to host in docker swarm

### ISSUE THREAD

**Issue by alexpirine** [moby/moby#36797] opened 2018-04-05 16:41 UTC
**Description**

Docker swarm ingress network seems to not be properly working.

I have a simple nginx web server exposing ports 443 & 80.

Half of the requests time out.

If I connect to the worker node:

```
$ for i in {1..500000}; do curl --connect-timeout 0.5 172.18.0.2 && echo; done
curl: (7) Failed to connect to 172.18.0.2 port 80: No route to host
ok
curl: (28) Connection timed out after 500 milliseconds
ok
curl: (28) Connection timed out after 501 milliseconds
ok
curl: (28) Connection timed out after 500 milliseconds
ok
curl: (28) Connection timed out after 502 milliseconds
ok
curl: (28) Connection timed out after 500 milliseconds
ok
curl: (7) Failed to connect to 172.18.0.2 port 80: No route to host
ok
curl: (28) Connection timed out after 501 milliseconds
ok
curl: (28) Connection timed out after 502 milliseconds
ok
curl: (28) Connection timed out after 500 milliseconds
ok
curl: (28) Connection timed out after 502 milliseconds
ok
curl: (28) Connection timed out after 501 milliseconds
ok
```

Notice how half of the connections succeed (nginx responds with _ok_) and the other ones time out (if I wait long enough I get _no route to host_)

The interesting thing is that if I run this loop in the background, now most of my external requests succeed. As if the loop was keeping all the "bad" connection busy… How is it possible?

I tried to reduce number of replicas to 1 and number of worker nodes to 1, same results.

**Steps to reproduce the issue:**

I do have a bunch of other services services so I can not share a reproductible config right now, but will try to.

**Describe the results you received:**

time out / no route to host

**Describe the results you expected:**

nginx "ok" response

**Additional information you deem important (e.g. issue happens only occasionally):**

I am able to replicate the issue by creating a fresh manager node, with a fresh install, and fresh worker nodes.

**Output of `docker version`:**

```
# docker --version
Docker version 18.03.0-ce, build 0520e24
```

**Output of `docker info`:**

```
# docker info
Containers: 27
 Running: 25
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 125
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: jincab3p1i1qia66yre5zwoxr
 Is Manager: false
 Node Address: 10.135.90.45
 Manager Addresses:
  10.135.54.123:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: node10
ID: IZAT:E3YD:7HQP:M5UO:4LCO:NQX2:X3QB:KUNK:RCW5:LVFK:CNHT:4Y2Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Hosted on Digital Ocean.

**Comment by kjkuan** [comment] 2018-04-07 21:28
I had the same issue with docker-ce 18.03. I found that if I downgrade to docker-ce 17.12.0, the issue disappears!

**Comment by alexpirine** [comment] 2018-04-07 21:36
Do you use docker-machine ? How do you make sure worker nodes are installed
with this old version too?

**Comment by kjkuan** [comment] 2018-04-09 14:07
I don't use `docker-machine`. I'm running ubuntu 16.04 and I configure my machines using Ansible. To do it ad-hoc, I just run something like: `ansible all -bi path/to/my/inventory/script -m shell -a 'apt-get install -y --allow-downgrades docker-ce=17.12.1~ce-0~ubuntu'` (yes, `17.12.1` works for me too).

Could you let me know if using docker-ce 17.12 also solves your problem? Just curious.

**Comment by kjkuan** [comment] 2018-04-09 15:14
Thanks @alexpirine , Docker really needs to make the ingress overlay network more reliable! sigh.

**Comment by michaelkrog** [comment] 2018-04-12 10:52
I am experiencing the same as @kjkuan 

I am on 18.03, and moved to this from 17.09 because of other breaking issues. (CPU through the roof for dockerd).

Now we have had network issues since we moved and are only saved by our DNS round robin taking over when things are not working..

**Comment by michaelkrog** [comment] 2018-04-12 11:09
So I started downgrading the nodes one by one..  

After downgrading 3 of 5 nodes, the issue is gone..  I still have 2 nodes on 18.03 and then 3 nodes on 17.12.1.


Goes from having every 3-5 request to hit nothing, to all requests going through.

**Comment by michaelkrog** [comment] 2018-04-12 11:13
Downgrading to 17.12.1 also fixes the issues Im having with a lack of Swarm events:
https://github.com/moby/moby/issues/36834

**Comment by kylejw1** [comment] 2018-04-13 00:28
I am seeing this as well from time to time.  In the short term I can usually resolve it by removing the service and recreating.

Something I noticed last time it occurred, I ran an nslookup on tasks.[service_name] and found that there was an extra container listed.  A service with 1 replica had two entries in the internal DNS record.  The no route to host errors were on requests load balanced to the phantom entry
I don't currently have the issue so I can't add more detail unfortunately.

**Comment by trinivibes** [comment] 2018-04-19 19:52
We have also experienced this issue and have reverted from 18.03 to 17.12.1 on our clusters. In front of the docker nodes is a F5 bigip that would detect the ingress going away which exposed this issue further.

**Comment by kylejw1** [comment] 2018-04-27 03:48
@vce-xx ping probably returning one address because its the load balanced VIP, then curl fails as the request is round robined through the containers behind the vip

**Comment by vce-xx** [comment] 2018-04-27 10:57
In my case one service task had failed (exit 137), and somehow, the DNS is keeping the address on a container that isn't running anymore.

In this case the desired replicas count for ws is 1.
dig returns 2 addresses.
That explains why I get the "No route to host" error half the time.

```
root@7a88e4058dba:/# dig tasks.ws

; <<>> DiG 9.10.3-P4-Debian <<>> tasks.ws
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60683
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;tasks.ws.                      IN      A

;; ANSWER SECTION:
tasks.ws.               600     IN      A       10.0.4.147
tasks.ws.               600     IN      A       10.0.4.112

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Fri Apr 27 08:41:41 UTC 2018
;; MSG SIZE  rcvd: 74

$ docker service ps ws --format "table{{.ID}}\t{{.CurrentState}}\t{{.Error}}"
ID                  CURRENT STATE                ERROR
hjzhki1wdo2h        Running about an hour ago
u3a2hk0yn3nn        Shutdown about an hour ago
zm09hw07ovxz        Failed 23 hours ago          "task: non-zero exit (1)"
zrmbpohred84        Shutdown 2 weeks ago

$ docker ps -a --filter "name=ws" --format "table{{.ID}}\t{{.Status}}"
CONTAINER ID        STATUS
b1bf13e22312        Up About an hour
d24a67055df6        Exited (137) About an hour ago
```

**Comment by cpuguy83** [comment] 2018-04-27 13:28
ping @fcrisciani

**Comment by kylejw1** [comment] 2018-04-28 17:47
@vce-xx identical to what I was seeing.  In not sure how to investigate any further unfortunately.  One time I was able to remove a dead container and the problem resolved, another time I had to remove the service and network.

**Comment by fcrisciani** [comment] 2018-04-30 16:15
@vce-xx @kylejw1 do you guys have any steps to reproduce? I think in 18.03 there is still cases where some container remain stuck on removal, that can cause the signature that you guys see. But would be great if we can narrow down if there is other cases.

**Comment by cpuguy83** [comment] 2018-04-30 16:47
If the issue is indeed the case (fifo open blocked, particularly on execs/healtchecks, causing a container deadlock), then it *should* be mitigated in 18.03.1 which was just released.

**Comment by vce-xx** [comment] 2018-04-30 16:48
@fcrisciani Unfortunately not at this point. It happened on a release machine where the Docker stacks are deployed and redeployed as developers deliver. We use docker stack deploy and external overlay networks (services are updated but the overlay network stays around).

I understand that narrowing down to a reproductible scenario would clearly help for solving this issue. 

My env in this case : Docker 18.03.0-ce, Docker for AWS ce stable no vpc, 1 manager and 1 worker. I have recreated the cluster to have 3 managers now, hoping that this issue would not reoccur.

After more investigation, I found that the IP address of the failed container was not the additional address that was stuck in Swarm dns.

**Comment by kylejw1** [comment] 2018-05-01 11:26
@fcrisciani unfortunately not sure how to reproduce either, we deploy very frequently to our staging environment so it can be tough to catch right away and take note of any specific details. I have encountered the issue with a 17.06 cluster, as well as a split 17.06/18.03. I will look at moving to 18.03.1 next week if possible.

**Comment by arneschreuder** [comment] 2018-05-03 11:46
Hi Guys

We had a very similar issue where we deployed a MySQL container in our swarm and found that we would lose connection every 2 or 3 connections made.

I managed to resolve my issue by:

1. `docker system prune` (on all nodes in swarm, BE CAREFUL, this deletes dangling containers, volumes, networks etc).
2. `sudo reboot now`

I hope this helps.

**Comment by pstrzelczak** [comment] 2018-05-03 12:44
It seems that I am hitting this problem in my work. I started to experience this after I tried to move to 18.03.0-ce from 17.06.2-ce. This blocks me to switch to newest "stable" version of Swarm. I will give 17.12.1-ce a try.

Similarly as reporter of this bug, I don't have an isolated test case which is able to reproduce this issue but in my use-case I have a haproxy Swarm service with an http port exposed and attempt to use frequently ends up with 'No route to host' error.
I managed to catch the error with curl and record its strace but found nothing special there - it seems curl uses non-blocking sockets and fails to connect to a remote site:

```
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 4
setsockopt(4, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPIDLE, [60], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPINTVL, [60], 4) = 0
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(4, {sa_family=AF_INET, sin_port=htons(5601), sin_addr=inet_addr("10.9.4.120")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=4, events=POLLOUT|POLLWRNORM}], 1, 0) = 0 (Timeout)
poll([{fd=4, events=POLLOUT}], 1, 1)    = 0 (Timeout)
poll([{fd=4, events=POLLOUT|POLLWRNORM}], 1, 0) = 0 (Timeout)
poll([{fd=4, events=POLLOUT}], 1, 198)  = 0 (Timeout)
poll([{fd=4, events=POLLOUT|POLLWRNORM}], 1, 0) = 0 (Timeout)
poll([{fd=4, events=POLLOUT}], 1, 1000) = 0 (Timeout)
poll([{fd=4, events=POLLOUT|POLLWRNORM}], 1, 0) = 0 (Timeout)
poll([{fd=4, events=POLLOUT}], 1, 1000) = 0 (Timeout)
poll([{fd=4, events=POLLOUT|POLLWRNORM}], 1, 0) = 0 (Timeout)
poll([{fd=4, events=POLLOUT}], 1, 1000) = 1 ([{fd=4, revents=POLLOUT|POLLERR|POLLHUP}])
poll([{fd=4, events=POLLOUT|POLLWRNORM}], 1, 0) = 1 ([{fd=4, revents=POLLOUT|POLLWRNORM|POLLERR|POLLHUP}])
getsockopt(4, SOL_SOCKET, SO_ERROR, [113], [4]) = 0
close(4)                                = 0
```

**Comment by cpuguy83** [comment] 2018-05-03 13:17
As stated above, it is possible that this is fixed in 18.03.1. If you can
try that and let us know that would be helpful.

**Comment by julienfastre** [comment] 2018-05-04 20:11
I encountered similar issue in 18.03.0 and search engines drop me here. 

Upgrading to 18.03.1 seems to solve this issue.

**Comment by fcrisciani** [comment] 2018-05-04 20:14
Thanks @pstrzelczak for sharing your results

**Comment by cpuguy83** [comment] 2018-05-04 20:41
Awesome. Thanks for confirming!
Closing as this looks resolved.

**Closed by cpuguy83** 2018-05-04 20:41 UTC
Labels: area/networking, area/swarm

**Comment by pstrzelczak** [comment] 2018-05-07 08:54
@cpuguy83 @fcrisciani could you show which change introduced this critical regression in 18.03.0 and which change fixes this in 18.03.1?

**Comment by cpuguy83** [comment] 2018-05-07 17:19
@pstrzelczak I believe it is https://github.com/containerd/containerd/commit/d235ae9439c7a22b96a0d66cb15dd8808d978e8f

**Comment by kylejw1** [comment] 2018-05-15 16:34
I know this has been marked closed, but I wanted to let anyone watching know that I have been running 18.03.1 for over a week now with now issues.

Thanks for the help everyone.

**Comment by fcrisciani** [comment] 2018-05-15 21:02
@kylejw1 
> 18.03.1 for over a week now with now issues.

I hope is now with *no* issues :D

**Comment by zsyh** [comment] 2019-04-09 09:47
@arneschreuder Thank you very much.  This solved my problem.

**Comment by georgmay** [comment] 2021-04-26 11:26
Running 20.05, same issue

**Comment by jeffersfp** [comment] 2022-01-10 18:17
Running `19.03.13` and I'm having this issue

**Comment by diegito** [comment] 2022-07-18 13:04
We are still experiencing this issue on Docker `20.10.17`
