### ISSUE TITLE
docker mounts create wrong directory

### ISSUE THREAD

**Issue by Mathiasdm** [moby/moby#33563] opened 2017-06-07 08:51 UTC
**Description**

We mount several directories, some of which are located in other directories. All of these directories exist, so the expected behaviour is that no new directories are created.

This is not the case (see the steps below for an example): the wrong directories are created on the host.

**Steps to reproduce the issue:**
1. mkdir -p /tmp/dockertest/1/2
2. docker run -it -v /tmp/dockertest/1:/foo -v /tmp/dockertest/1/2:/foo/bar centos:7 echo foo
3. find /tmp/dockertest

**Describe the results you received:**

All of these directories are present:

```
/tmp/dockertest
/tmp/dockertest/1
/tmp/dockertest/1/bar
/tmp/dockertest/1/2
```

**Describe the results you expected:**
The /tmp/dockertest/1/bar directory should not exist.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 64
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-52-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.678 GiB
Name: mdemare-HP-ProBook-6470b
ID: NMRG:CFLX:SXNG:7HCU:UXFG:TCB5:ZMA4:WZWS:6JAM:YP2Z:OOYS:G7XR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.somewhere.com:8000/
No Proxy: localhost,127.0.0.0/8,::1,/var/run/docker.sock
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Ubuntu 16.10, kernel 4.8.0-52-generic.
I am seeing the same issue also on a physical CentOS 7 machine.

**Comment by thaJeztah** [comment] 2017-06-07 09:30
This is expected;

You are mounting ` /tmp/dockertest/1` as `/foo` inside your container; anything written to `/foo` inside the container will therefore be written to `/tmp/dockertest/1` on the host.

For the second bind-mount, you are mounting `/tmp/dockertest/1/2` to `/foo/bar` inside your container. To bind-mount a directory or file on Linux, a mount point has to be created, in this case `bar`. Because any change to `/foo` inside the container is actually written to `/tmp/dockertest/1` on the host, you'll see that `bar` is created there.

I'll close this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-06-07 09:30 UTC
Labels: version/1.12

**Comment by Mathiasdm** [comment] 2017-06-07 12:20
Hm, I understand what you mean. The problem for me now is that additional directories (owned by root) are being created, which is not ideal for our users.

I wonder if there are any solutions to this problem. Some ideas:

1. I can create the mount points myself before starting Docker (to make sure they are not owned by root) and remove them afterwards.
2. Perhaps these could be cleaned up automatically when the container is removed?

**Comment by thaJeztah** [comment] 2017-06-07 13:04
If the files on the host match the format that they are used in inside the container, you can probably reduce the number of mounts, and just use a single bind-mount.

While bind-mounted directories can be useful during development (bind-mount your source inside the container); there's lots of reasons to avoid them for other purposes (files created inside those to be owned by the container's user is one of them)

Would regular volumes be a solution for your case?

**Comment by Mathiasdm** [comment] 2017-06-07 13:54
Unfortunately, it's not possible for me to completely get rid of (multiple) bind-mounts. One of the things I'm trying to do is cross-machine caching of certain artifacts, which requires builds to happen in the same location consistently for us.

Docker/Moby makes this possible, but only if I stick to bind-mounts.
