### ISSUE TITLE
Docker IPv6 Port Access failed

### ISSUE THREAD

**Issue by zhangcheng1102** [moby/moby#38036] opened 2018-10-13 18:17 UTC
Containers use IPv6 address，every container has a unique IPv6 address, and it can be ping success from outside of docker, but when telnet container's IPv6 port, return Permission denied, why?

**Comment by thaJeztah** [comment] 2018-10-19 11:28
We really need more information to answer your question; please use the issue template that was shown when you opened this ticket, and provide the requested information (exact steps to reproduce, docker info and docker version output, and so on).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-10-19 11:28 UTC
Labels: kind/question, status/more-info-needed
