### ISSUE TITLE
Docker stop provisioning global service to remaining nodes when a task finish with Complete state

### ISSUE THREAD

**Issue by huaphuoctruong** [moby/moby#39551] opened 2019-07-17 18:48 UTC
**Description**

Given a docker service does not run a persistent process (ex: CMD [ "echo", "1" ]). If we do update the service, the provisioning process will stop after finish deploying the first task (with "COMPLETE" state) in the first node and the remaining nodes do not get updates.

**Steps to reproduce the issue:**
1. Create a simple global service (ex: `docker service create --mode global --name reproduce alpine echo 1`)
2. Wait for the service to be deployed successfully.
3. `docker service update reproduce`.

**Describe the results you received:**
The service `reproduce` does rolling update but it is stopped after the first task is completed.

**Describe the results you expected:**
All tasks of the service will be updated respectively

**Additional information you deem important (e.g. issue happens only occasionally):**
Nothing

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 54
 Running: 15
 Paused: 0
 Stopped: 39
Images: 30
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 Is Manager: true
 Managers: 3
 Nodes: 3
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1021-aws
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.789GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS Lightsail

**Comment by thaJeztah** [comment] 2019-07-17 19:44
It doesn't continue rolling out the service, because the first deploy wasn't successful; it creates the service, deploys a task, but the task doesn't stay running (which is a "failure").

If you run the `docker service create` with the `--detach` flag, you'll see that new tasks are created continuously until the service reconciles with the desired state ("running"). If you run `watch docker service ps reproduce`, you'll see that new containers are continuously created;

```
Every 2.0s: docker service ps reproduce

ID                  NAME                                      IMAGE               NODE                DESIRED STATE       CURRENT STATE             ERROR               PORTS
mhnmsu00op8g        reproduce.xgkle8o2y7qx1kb72ngl1gfs4       alpine:latest       docker-desktop      Ready               Ready 2 seconds ago
puebzh5zvy7l         \_ reproduce.xgkle8o2y7qx1kb72ngl1gfs4   alpine:latest       docker-desktop      Shutdown            Complete 3 seconds ago
tiab4gg6f4xa         \_ reproduce.xgkle8o2y7qx1kb72ngl1gfs4   alpine:latest       docker-desktop      Shutdown            Complete 9 seconds ago
ukcrpfas9d5e         \_ reproduce.xgkle8o2y7qx1kb72ngl1gfs4   alpine:latest       docker-desktop      Shutdown            Complete 15 seconds ago
v2f0vizn8yj1         \_ reproduce.xgkle8o2y7qx1kb72ngl1gfs4   alpine:latest       docker-desktop      Shutdown            Complete 21 seconds ago
```

You could try using `--update-parallelism=0` to deploy all tasks at the same time, and setting `--restart-policy=none` to never create a new task after the task exits

**Comment by huaphuoctruong** [comment] 2019-07-17 20:54
Yeah, I misunderstand the COMPLETE state, I guess that it is the same as
successful. The parallelism=0 is awesome which solved my problem because I
need to run a special service in all nodes to setup something and it does
not need to run persistently.

**Comment by thaJeztah** [comment] 2019-07-17 22:42
You might be interested this proposal https://github.com/moby/moby/issues/39447 - feel free to add your comment / use-case there if it isn't captured in the description

Let me go ahead and close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2019-07-17 22:42 UTC
Labels: area/swarm
