### ISSUE TITLE
"docker run" appears to rename my eth0, wreaking ifupdown/NetworkManager resolv.conf havoc

### ISSUE THREAD

**Issue by csirac2** [moby/moby#16572] opened 2015-09-25 04:45 UTC
Environment:

This is a xen-system-amd64 4.4.1 machine. Below, we are working on dom0, which is Debian jessie running with systemd, booted from btrfs on lvm on luks.

There is only one physical NIC, eth0, directly attached to dom0.

``` bash
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:05 UTC 2015
 OS/Arch:      linux/amd64
$ docker info
Containers: 5
Images: 53
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.0-2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 7.617 GiB
Name: dom0host
ID: AAAA:AAAA:AAAA:AAAA:AAAA:AAAA:AAAA:AAAA:AAAA:AAAA:AAAA:AAAA
WARNING: No memory limit support
WARNING: No swap limit support
$ uname -a
Linux dom0host 4.0.0-2-amd64 #1 SMP Debian 4.0.8-2 (2015-07-22) x86_64 GNU/Linux
```

Additional:

``` bash
$ ps auwx |grep docker | grep -v $(whoami)
root     27469  0.1  0.4 722108 34620 ?        Ssl  Sep24   1:36 /usr/bin/docker -d -H fd:// -s btrfs --dns 172.17.42.1 --dns 8.8.4.4 --registry-mirror=http://some.local.docker.mirror:5000
```

Steps to reproduce:
- 1. Check `resolv.conf`:

``` bash
$ cat /etc/resolv.conf
nameserver 8.8.8.8
```
- 2. Check Dockerfile:

``` bash
$ cat Dockerfile
FROM debian:jessie
CMD [ "/bin/echo", "hi" ]
```
- 3. Build Dockerfile:

``` bash
$ docker build -t test .
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM debian:jessie
 ---> 8c00acfb0175
Step 1 : CMD /bin/echo hi
 ---> Using cache
 ---> fb4e59dd039a
Successfully built fb4e59dd039a
```
- 4. Run:

``` bash
$ docker run test
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
hi
```
- 5. Check `resolv.conf` again:

``` bash
$ cat /etc/resolv.conf 
# Generated by NetworkManager
```

Expected: step 5 should yield the same unmodified DNS settings in resolv.conf as obtained in step 1.

Actual: step 5 yields an `/etc/resolv.conf` which has been modified by NetworkManager.

This is apparently because eth0 is renamed a couple of times during `docker run`. Although my eth0 is configured via `/etc/network/interfaces[.d]`, i.e. via ifupdown, `nm` thinks it should suddenly try to manage this "new" interface as a result of docker's interface rename shenanigans. In doing so, `nm` stomps on the existing `/etc/resolv.conf`, but that particular detail is I think, a red herring; eth0 should simply never be renamed in the first place.

Relevant syslog:

``` sh
Sep 25 14:14:50 dom0host kernel: vethb817d6a: renamed from eth0
Sep 25 14:14:50 dom0host NetworkManager[28425]: <info> (vethb817d6a): device is virtual, marking as unmanaged
Sep 25 14:14:50 dom0host NetworkManager[28425]: <info> (vethb817d6a): carrier is OFF
Sep 25 14:14:50 dom0host NetworkManager[28425]: <info> (vethb817d6a): new Veth device (driver: 'unknown' ifindex: 118)
Sep 25 14:14:50 dom0host NetworkManager[28425]: <info> (vethb817d6a): exported as /org/freedesktop/NetworkManager/Devices/84
Sep 25 14:14:50 dom0host NetworkManager[28425]: <info> devices added (path: /sys/devices/virtual/net/vethb817d6a, iface: vethb817d6a)
Sep 25 14:14:50 dom0host NetworkManager[28425]: <info> device added (path: /sys/devices/virtual/net/vethb817d6a, iface: vethb817d6a): no ifupdown configuration found
```

**Comment by csirac2** [comment] 2015-09-25 05:00
Here's a gist to all syslog lines which occur during step 4 `docker run test`: https://gist.github.com/csirac2/ce50215526723fa3441a

**Comment by cpuguy83** [comment] 2015-10-02 14:08
Is eth0 a bridge? What are your daemon flags?

**Comment by larsks** [comment] 2015-10-08 19:13
I'm seeing the same problem. I'm running:

    Client:
     Version:      1.8.2-fc23
     API version:  1.20
     Package Version: docker-1.8.2-5.gitcb216be.fc23.x86_64
     Go version:   go1.5
     Git commit:   cb688cf-dirty
     Built:        Mon Sep 21 20:21:20 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.8.2-fc23
     API version:  1.20
     Package Version: 
     Go version:   go1.5
     Git commit:   cb688cf-dirty
     Built:        Mon Sep 21 20:21:20 UTC 2015
     OS/Arch:      linux/amd64

Where docker is being run like this:

    /usr/bin/docker daemon --selinux

And my primary interface, formerly known as `enp0s25`, is suddenly
known as `veth26b0d4e`, which is wreaking havoc with NetworkManager.
I have only ever caught this after-the-fact; I'm not sure exactly when
it happens.

`enp0s25` was just a normal physical ethernet nic, not attached to a
bridge.

**Comment by csirac2** [comment] 2015-10-09 04:10
@cpuguy83 apologies for the late response. eth0 is a NIC, not a bridge. Daemon flags are in the initial report, but here they are again:

```
/usr/bin/docker -d -H fd:// -s btrfs --dns 172.17.42.1 --dns 8.8.4.4 \
    --registry-mirror=http://some.local.docker.mirror:5000
```

**Comment by thaJeztah** [comment] 2015-11-05 12:36
ping @cpuguy83 PTAL, thx

**Comment by cpuguy83** [comment] 2015-11-05 14:46
Ultimately I can't see docker doing anything with this stuff, unless you've run a container with `--net=host` and something in that container is modifying the interface...

but ping @mrjana

**Comment by mrjana** [comment] 2015-11-05 16:17
@csirac2 
```
Sep 25 14:14:50 dom0host kernel: vethb817d6a: renamed from eth0
```
This log appears to rename your host eth0, but it actually is renaming the container's eth0 back to vethb817d6a. The kernel logs normally don't show this difference i.e that this is happening in a different namespace other than the host namespace. And after renaming we move the veth interface back to  host namespace before bridge driver deletes it. So looks like your NetworkManager ifupdown script seems to pick up this new interface showing up and it is acting on it. And that action is most likely resulting in your host /etc/resolv.conf being modified. You probably need to have a look at what the NetworkManager script is doing.

**Comment by csirac2** [comment] 2015-12-01 10:29
Thanks; for what it's worth, these are standard debian installs - I haven't gone out of my way to mess with network-manager itself, but I'll try to see if there's a way I can make this easily reproducible.

**Comment by thaJeztah** [comment] 2015-12-01 13:26
Thanks @csirac2!

**Comment by danielschonfeld** [comment] 2015-12-14 17:17
FWIW we're seeing the same thing happening to us but were mostly under the impression it was Elasticsearch's marvel plugin that is causing this.  Having read the above, now I'm not so sure its limited in scope to ES causing this behavior in docker.  But we get the same log messages and same total destruction to our networking on the host machine.

For steps to reproduce reliably see https://github.com/elastic/elasticsearch/issues/15409

**Comment by aleemb** [comment] 2016-06-24 10:34
I'm having the same issue. My logs show this problem returns every couple of days/weeks. When it re-appears it persists for a couple of hours and then goes away for some time. The problem persists even if I restart my docker container.

Reported here https://github.com/docker/docker/issues/23927

**Comment by mathuin** [comment] 2016-07-07 00:17
This is also happening to me.  Ubuntu 16.04, Docker 1.11.2, additional information available, just ask.

**Comment by christopherdiehl** [comment] 2017-01-26 20:21
Same thing, exact same setup as @mathuin . Eth0 renamed docker0

**Comment by cpuguy83** [comment] 2017-01-27 00:00
ping @aboch

**Comment by hiscal2015** [comment] 2017-07-14 02:34
+1

**Comment by smit-s** [comment] 2020-03-31 19:33
I am facing the same problem how shall i revert it?

**Comment by dogmatic69** [comment] 2021-10-15 21:30
Im getting something similar running docker build on a raspberry pi. Build fails with network errors
```
---> Running in c304a8108211
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/armhf/APKINDEX.tar.gz
ERROR: fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/armhf/APKINDEX.tar.gz
https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: No such file or directory
3069924240:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069924240:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069924240:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069924240:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069924240:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
```
syslog says:
```
Oct 15 22:25:10 raspberrypi kernel: [80826.030005] eth0: renamed from vetha97f74e
Oct 15 22:25:13 raspberrypi kernel: [80829.080039] vetha97f74e: renamed from eth0
```

**Comment by rizerzero** [comment] 2022-02-14 09:56
Same for me, when I reboot my host, networking crashes sometimes and I get these messages.
Debian 11 
Docker 20.10.12

```
eb 14 10:30:29 my-staging kernel: [   12.216523] eth0: renamed from veth41dcab6
Feb 14 10:30:29 my-staging kernel: [   12.235089] br-a75af9a071b0: port 5(veth9a9e3a5) entered disabled state
Feb 14 10:30:29 my-staging kernel: [   12.235763] br-14ca4b550b74: port 5(vethc1d0789) entered disabled state
Feb 14 10:30:29 my-staging kernel: [   12.236403] br-a75af9a071b0: port 6(vethcf59192) entered disabled state
Feb 14 10:30:30 my-staging kernel: [   12.237040] br-a75af9a071b0: port 7(veth429207a) entered disabled state
Feb 14 10:30:30 my-staging kernel: [   12.237661] IPv6: ADDRCONF(NETDEV_CHANGE): veth0156ffe: link becomes ready
Feb 14 10:30:30 my-staging kernel: [   12.238274] br-a75af9a071b0: port 1(veth0156ffe) entered blocking state
Feb 14 10:30:30 my-staging kernel: [   12.238846] br-a75af9a071b0: port 1(veth0156ffe) entered forwarding state
Feb 14 10:30:30 my-staging kernel: [   12.239972] br-a75af9a071b0: port 8(vethd2c42b8) entered blocking state
Feb 14 10:30:30 my-staging kernel: [   12.240754] br-a75af9a071b0: port 8(vethd2c42b8) entered disabled state
Feb 14 10:30:30 my-staging kernel: [   12.242969] device vethd2c42b8 entered promiscuous mode
Feb 14 10:30:30 my-staging kernel: [   12.248263] br-a75af9a071b0: port 8(vethd2c42b8) entered blocking state
Feb 14 10:30:30 my-staging kernel: [   12.248896] br-a75af9a071b0: port 8(vethd2c42b8) entered forwarding state
Feb 14 10:30:30 my-staging kernel: [   12.500962] eth0: renamed from vethc62c8c4
Feb 14 10:30:30 my-staging kernel: [   12.521452] br-a75af9a071b0: port 8(vethd2c42b8) entered disabled state
Feb 14 10:30:30 my-staging kernel: [   12.522135] IPv6: ADDRCONF(NETDEV_CHANGE): veth855c16d: link becomes ready
Feb 14 10:30:30 my-staging kernel: [   12.522750] br-4ce008b29fd6: port 2(veth855c16d) entered blocking state
Feb 14 10:30:30 my-staging kernel: [   12.523333] br-4ce008b29fd6: port 2(veth855c16d) entered forwarding state
Feb 14 10:30:30 my-staging kernel: [   12.571048] eth0: renamed from veth982601e
Feb 14 10:30:30 my-staging kernel: [   12.580499] IPv6: ADDRCONF(NETDEV_CHANGE): veth6b50ea7: link becomes ready
Feb 14 10:30:30 my-staging kernel: [   12.581277] br-14ca4b550b74: port 1(veth6b50ea7) entered blocking state
Feb 14 10:30:30 my-staging kernel: [   12.581883] br-14ca4b550b74: port 1(veth6b50ea7) entered forwarding state
Feb 14 10:30:30 my-staging kernel: [   12.644891] eth0: renamed from veth825ea40
```

**Comment by akerouanton** [comment] 2023-05-05 10:53
As already said by @mrjana, logs about veth interface being renamed into eth0 is only about what happens in containers' network namespace. Docker never renames an interface in the host netns. If that happens, it's either NetworkManager, systemd-networkd, udev and the like. Maybe even cloud-init could play a role here, depending on when it's launched by systemd.

I'm afraid there's nothing we can do here, except maybe add some docs if someone get to the bottom of this. To debug that, I would review the config files and hook scripts of all the softwares I mentioned. If that's inconclusive, I would also take a look at `sudo ss -f netlink | grep rtnl` to see what other softwares might watch for interface changes.

As there's nothing we can do here, I'll close this issue but feel free to continue the discussion if you find anything interesting.

**Closed** 2023-05-05 11:30 UTC
Labels: status/more-info-needed, kind/bug, area/networking, version/1.8
