### ISSUE TITLE
docker-wait does not always exit when daemon is restarted

### ISSUE THREAD

**Issue by jperville** [moby/moby#6673] opened 2014-06-25 10:26 UTC
# The problem

When I run `service docker restart` while `docker wait`-ing on several running containers some of the containers are randomly lost (they do not show up anymore in `docker ps`).

The containers are lost because `docker wait` never returns and my (upstart) service is waiting on `docker wait` to return to attempt restarting the service. The consequence is that my (upstart) service says that the service is running while the associated container is not, which makes it a zombie.

I believe that at any time there should be no `docker wait` processes that are older than the docker daemon process.

See the (simplified) log below for the bug in action

``` sh
# we start with 2 containers named my-app-a and my-app-b
root@docker-ubuntu-1404:~# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
3ef322077333        busybox:ubuntu-14.04   /sbin/top           26 minutes ago      Up 23 seconds                           my-app-b            
252e4aeeb595        busybox:ubuntu-14.04   /sbin/top           26 minutes ago      Up 23 seconds                           my-app-a            
root@docker-ubuntu-1404:~# service docker restart
docker stop/waiting
docker start/running, process 1707
# after first restart, both containers are restarted (by the upstart service)
root@docker-ubuntu-1404:~# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS                  PORTS               NAMES
3ef322077333        busybox:ubuntu-14.04   /sbin/top           26 minutes ago      Up 1 seconds                                my-app-b            
252e4aeeb595        busybox:ubuntu-14.04   /sbin/top           26 minutes ago      Up 1 seconds                                my-app-a            
root@docker-ubuntu-1404:~# service docker restart
docker stop/waiting
docker start/running, process 2124
# the random occurrence of bug #6647
root@docker-ubuntu-1404:~# docker ps
2014/06/25 10:12:25 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
# this time my-app-a did not survive the restart, only my-app-b did
root@docker-ubuntu-1404:~# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS                  PORTS               NAMES
3ef322077333        busybox:ubuntu-14.04   /sbin/top           26 minutes ago      Up Less than a second                       my-app-b            
# upstart thinks that my-app-a is running
root@docker-ubuntu-1404:~# service my-app-a status
my-app-a start/running, process 2575
# actually it is the `docker wait` process that is running (upstart is working as expected)
root@docker-ubuntu-1404:~# ps aux | grep -v grep | grep 2575
root      2575  0.0  0.9 191288  4724 ?        Ssl  10:12   0:00 /usr/bin/docker wait my-app-a
root@docker-ubuntu-1404:~# kill 2575
# after killing the `docker wait` process, upstart has restarted our container
root@docker-ubuntu-1404:~# service my-app-a status
my-app-a start/running, process 2618
# all back to normal until the next `service docker restart`
root@docker-ubuntu-1404:~# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
3ef322077333        busybox:ubuntu-14.04   /sbin/top           27 minutes ago      Up 36 seconds                           my-app-b            
252e4aeeb595        busybox:ubuntu-14.04   /sbin/top           27 minutes ago      Up 36 seconds                           my-app-a            
root@docker-ubuntu-1404:~# 
```
# How to reproduce

Create the following `Vagrantfile`:

``` ruby
Vagrant.configure('2') do |config|

  config.vm.define :ubuntu1404 do |ubuntu1404|
    ubuntu1404.vm.box      = 'opscode-ubuntu-14.04'
    ubuntu1404.vm.box_url  = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box'
    ubuntu1404.vm.hostname = "docker-ubuntu-1404"
  end

  config.vm.provider 'virtualbox' do |vbox|
    vbox.customize ['modifyvm', :id, '--memory', 512]
  end
end
```

Boot the VM with `vagrant up`, then install docker with `wget -qO- https://get.docker.io/ubuntu/ | sudo bash -s`

Create and run enough containers to reproduce the problem:

``` sh
sudo apt-get install inotify-tools # workaround #6647

for i in a b c d e f ; do

  sudo docker run -d --name=my-app-${i} busybox:ubuntu-14.04 /sbin/top
  sudo docker stop my-app-${i}

  cat <<EOF | sudo tee /etc/init/my-app-${i}.conf 
description "Docker service for my-app-${i}"
author "Docker Chef Cookbook"

start on filesystem and started docker
stop on runlevel [!2345]

# We don't want to TERM the \`docker wait\` process so we fake the signal 
# we send to it. The pre-stop script issues the \`docker stop\` command
# which causes the \`docker wait\` process to exit
kill signal CONT

# Due to a bug in upstart we need to set the modes we consider
# successful exists https://bugs.launchpad.net/upstart/+bug/568288
normal exit 0 CONT

respawn

exec /usr/bin/docker wait my-app-${i}

pre-start script
  # Wait for docker to finish starting up first.
  FILE=/var/run/docker.sock
  while [ ! -e \$FILE ] ; do
    inotifywait -t 2 -e create \$(dirname \$FILE)
  done
  /usr/bin/docker start my-app-${i} || true
end script

pre-stop script
  /usr/bin/docker stop -t 60 my-app-${i}
end script
EOF

  sudo service my-app-${i} start

done
```

Then repeat the following until you notice that at least one container is missing from `docker ps` output:

``` sh
sudo service docker restart
sudo docker ps
```

It may take a few minutes but will eventually reproduce.
## Notes

The bug reproduces more easily on low memory VMs or using large images. Using busybox-based container is very light in memory so I use more instances to increase the chance to reproduce the bug.

**Comment by jfrazelle** [comment] 2015-02-25 19:19
@jperville can you try with the latest version of docker

**Comment by jperville** [comment] 2015-02-26 13:53
I reproduced the issue easily with 26 containers (named 'my-app-a' to 'my-app-z').

```sh
root@docker-ubuntu-1404:~# docker --version
Docker version 1.5.0, build a8a31ef
root@docker-ubuntu-1404:~# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
e7ac4e935bcf        busybox:ubuntu-14.04   "/sbin/top"         3 seconds ago       Up 2 seconds                            my-app-z            
d6490a8ce8f0        busybox:ubuntu-14.04   "/sbin/top"         4 seconds ago       Up 3 seconds                            my-app-y            
927c41a4839a        busybox:ubuntu-14.04   "/sbin/top"         4 seconds ago       Up 4 seconds                            my-app-x            
80feb5a12592        busybox:ubuntu-14.04   "/sbin/top"         5 seconds ago       Up 4 seconds                            my-app-w            
b2ae85e6b5c4        busybox:ubuntu-14.04   "/sbin/top"         6 seconds ago       Up 5 seconds                            my-app-v            
84a88ec862fd        busybox:ubuntu-14.04   "/sbin/top"         6 seconds ago       Up 6 seconds                            my-app-u            
196ae07c7ea6        busybox:ubuntu-14.04   "/sbin/top"         7 seconds ago       Up 6 seconds                            my-app-t            
ac060186a81e        busybox:ubuntu-14.04   "/sbin/top"         7 seconds ago       Up 7 seconds                            my-app-s            
685ce75d0be5        busybox:ubuntu-14.04   "/sbin/top"         8 seconds ago       Up 7 seconds                            my-app-r            
f0f001df342c        busybox:ubuntu-14.04   "/sbin/top"         9 seconds ago       Up 8 seconds                            my-app-q            
bde6e17735eb        busybox:ubuntu-14.04   "/sbin/top"         9 seconds ago       Up 9 seconds                            my-app-p            
63a89588dcd2        busybox:ubuntu-14.04   "/sbin/top"         10 seconds ago      Up 9 seconds                            my-app-o            
2b01dcd1d696        busybox:ubuntu-14.04   "/sbin/top"         10 seconds ago      Up 10 seconds                           my-app-n            
76db3971a9b0        busybox:ubuntu-14.04   "/sbin/top"         11 seconds ago      Up 10 seconds                           my-app-m            
306d2eca7583        busybox:ubuntu-14.04   "/sbin/top"         12 seconds ago      Up 11 seconds                           my-app-l            
c996ff1fda8a        busybox:ubuntu-14.04   "/sbin/top"         12 seconds ago      Up 12 seconds                           my-app-k            
388e0af9d6bd        busybox:ubuntu-14.04   "/sbin/top"         13 seconds ago      Up 12 seconds                           my-app-j            
49e6e0ef2931        busybox:ubuntu-14.04   "/sbin/top"         13 seconds ago      Up 13 seconds                           my-app-i            
e603cf9e21f4        busybox:ubuntu-14.04   "/sbin/top"         14 seconds ago      Up 13 seconds                           my-app-h            
60753c22c791        busybox:ubuntu-14.04   "/sbin/top"         14 seconds ago      Up 14 seconds                           my-app-g            
581f9924ac82        busybox:ubuntu-14.04   "/sbin/top"         52 seconds ago      Up 52 seconds                           my-app-f            
fa37937f6241        busybox:ubuntu-14.04   "/sbin/top"         53 seconds ago      Up 52 seconds                           my-app-e            
51929f5f8067        busybox:ubuntu-14.04   "/sbin/top"         53 seconds ago      Up 53 seconds                           my-app-d            
0c5f783db0c2        busybox:ubuntu-14.04   "/sbin/top"         54 seconds ago      Up 53 seconds                           my-app-c            
2af313066d8f        busybox:ubuntu-14.04   "/sbin/top"         55 seconds ago      Up 54 seconds                           my-app-b            
41eeed635837        busybox:ubuntu-14.04   "/sbin/top"         55 seconds ago      Up 54 seconds                           my-app-a            
root@docker-ubuntu-1404:~# docker ps -q | wc -l
26
root@docker-ubuntu-1404:~# sudo service docker restart
docker stop/waiting
docker start/running, process 8589
root@docker-ubuntu-1404:~# docker ps -q | wc -l
5
```

In the upstart logs (eg. '/var/log/upstart/my-app-a.log') I can see multiple lines like this one:

```
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
FATA[0000] Error: failed to start one or more containers 
```

This issue is less now that we can specify 'restart=always' but still annoying when containers are deployed as upstart services.

**Comment by jfrazelle** [comment] 2015-02-26 17:09
hmm ya unsure what the solution would be for when a supervisor is monitoring, labeled as black-belt maybe someone can find an underlying issue, don't know if there is one, thanks for trying on latest, saves us a lot of time

**Comment by duglin** [comment] 2015-05-28 17:39
Been trying to reproduce this outside of any service management system and haven't been able to. @jperville is it still an issue?

**Comment by jperville** [comment] 2015-05-28 17:58
Still happenening as of version 1.6.2, using the steps from my original post.

```sh
vagrant@docker-ubuntu-1404:~$ sudo docker --version
Docker version 1.6.2, build 7c8fca2
vagrant@docker-ubuntu-1404:~$ sudo docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED              STATUS                  PORTS               NAMES
c029ba2f32ef        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 1 seconds                                my-app-y            
0cdf831a0e3f        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 1 seconds                                my-app-z            
19b911d63489        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-x            
842ee7bac6b7        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-w            
92db923e5314        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-v            
dbfe60cfd089        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 1 seconds                                my-app-t            
b44b9e81a5f1        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-u            
066d43158342        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-s            
74d86aafaf01        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 2 seconds                                my-app-r            
8ac1a120f29b        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 2 seconds                                my-app-q            
c9ea9a635c4f        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 2 seconds                                my-app-p            
8525c3ac127f        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 2 seconds                                my-app-o            
a412a905c07a        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-n            
6276fc43ec4c        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-m            
433c1bfa0ccd        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 1 seconds                                my-app-l            
9ee80ee96c1c        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-k            
52ed45d1550f        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-j            
94efa402349a        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 1 seconds                                my-app-i            
085e5557b624        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-h            
cfec9a7bc224        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-f            
5a19e737da66        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 2 seconds                                my-app-g            
53c4ed0e98aa        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-e            
8527522b1bc7        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-d            
a6918fead07b        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 2 seconds                                my-app-c            
0988500ac0e9        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-b            
d599542698e9        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up Less than a second                       my-app-a            
vagrant@docker-ubuntu-1404:~$ sudo service docker restart
docker stop/waiting
docker start/running, process 20258
vagrant@docker-ubuntu-1404:~$ sudo docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED              STATUS              PORTS               NAMES
92db923e5314        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 4 seconds                            my-app-v            
b44b9e81a5f1        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 4 seconds                            my-app-u            
066d43158342        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 4 seconds                            my-app-s            
6276fc43ec4c        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 5 seconds                            my-app-m            
53c4ed0e98aa        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 4 seconds                            my-app-e            
8527522b1bc7        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 4 seconds                            my-app-d            
d599542698e9        busybox:ubuntu-14.04   "/sbin/top"         About a minute ago   Up 4 seconds                            my-app-a            
vagrant@docker-ubuntu-1404:~$ sudo docker ps -q | wc -l
7
```

**Comment by rdpanek** [comment] 2015-10-25 09:54
Hello everbody, and in `1.7.1, build 786b29d` too :-/

ubuntu 14.04

How next?

**Comment by vvoland** [comment] 2023-09-14 11:03
Couldn't reproduce this on a recent (24.0.6) Docker version.

Let me close this issue.

**Closed by vvoland** 2023-09-14 11:03 UTC
Labels: area/runtime, exp/expert, kind/bug
