### ISSUE TITLE
Upgrading to Docker Engine 25 breaks loading images in various Kubernetes distributions

### ISSUE THREAD

**Issue by lb7** [moby/moby#47207] opened 2024-01-24 19:41 UTC
### Description

Since updating Docker Engine to version 25, loading images into various distributions of Kubernetes has been impossible due to what appears to be mismatching hashes of manifests/images. 

Downgrading to version 24, everything works as normal

This is still happening with Minikube. I was seeing it previously with k3d but since I updated again to version 25, k3d appears to be working.

### Reproduce

1. Update `docker-ce` to version 25.x.x (in my case `sudo apt upgrade`)
2. `minikube image load <registry>.azurecr.io/<tag>:latest
3. Receive error: 
```
❌  Exiting due to GUEST_IMAGE_LOAD: Failed to load image: save to dir: caching images: caching image "/home/<user>/.minikube/cache/images/amd64/<registry>.azurecr.io/<tag>": write: unable to calculate manifest: blob sha256:6c64c88ea1f392b085bcd98099ac4a19fc5ac8653024c9f903d80f8dcb27e7ed not found
```

### Expected behavior

Minikube should successfully load the image from docker

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:25 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 2
  Paused: 0
  Stopped: 8
 Images: 141
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-1053-azure
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.34GiB
 Name: <redacted
 ID: 6APF:G4SU:ZG65:2MBU:H5OM:IWV5:BGVO:NMBG:OD33:QJTK:RT5N:MCTV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Link to issue in Minikube repo https://github.com/kubernetes/minikube/issues/18021

**Comment by AkihiroSuda** [comment] 2024-01-25 01:54
This is an issue of go-containerregistry:
- https://github.com/google/go-containerregistry/issues/1870

**Comment by lb7** [comment] 2024-01-25 02:11
> This is an issue of go-containerregistry:
> 
> * [ggcr: Docker 25.0 breaks image handling google/go-containerregistry#1870](https://github.com/google/go-containerregistry/issues/1870)

Good find, thank you! I’ll leave this open until that issue is resolved, unless maintainers suggest otherwise

**Comment by krishnakc1** [comment] 2024-01-25 10:22
This occurred immediately when we upgraded to docker-ce v25.0.0. The main image components like apiserver, controller,manager, calico all failed to start container via kubelet. We use older version of k8s 1.17. The issue that might be causing this is [https://github.com/moby/moby/pull/45469](url) 
#https://github.com/moby/moby/pull/45469
Downgrading docker-ce to v24.0.7 removes the problem.
Error that I see in kubelet logs is
_kuberuntime_manager.go:809] container start failed: ImageInspectError: Failed to inspect image "k8s.gcr.io/kube-proxy:v1.17.12": Id or size of image "k8s.gcr.io/kube-proxy:v1.17.12" is not set_

**Comment by thaJeztah** [comment] 2024-01-25 10:36
> ImageInspectError: Failed to inspect image "k8s.gcr.io/kube-proxy:v1.17.12": Id or size of image "k8s.gcr.io/kube-proxy:v1.17.12" is not set

@krishnakc1 what API version is it using? That change should not change response for existing API versions (API versions before v1.44);


```bash
docker pull busybox:latest
latest: Pulling from library/busybox
9ad63333ebc9: Pull complete
Digest: sha256:6d9ac9237a84afe1516540f40a0fafdc86859b2141954b4d643af7066d598b74
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
```

On API v1.43, the `VirtualSize` field is returned:

```bash
curl -s --unix-socket /var/run/docker.sock http://whatever/v1.43/images/busybox:latest/json | jq .VirtualSize
4261566
```

On API v1.44, the field is omitted;

```bash
curl -s --unix-socket /var/run/docker.sock http://whatever/v1.44/images/busybox:latest/json | jq .VirtualSize
null
```

The `Size` field is present in both;

```bash
curl -s --unix-socket /var/run/docker.sock http://whatever/v1.43/images/busybox:latest/json | jq .Size
4261566
root@debian-s-1vcpu-1gb-ams3-01:~# curl -s --unix-socket /var/run/docker.sock http://whatever/v1.44/images/busybox:latest/json | jq .Size
4261566
```

Note that unversioned API calls have been deprecated since docker 1.13 in 2017 (originally meant to be removed in the v17.12 release, but that's not done yet);  https://docs.docker.com/engine/deprecated/#api-calls-without-a-version

**Comment by thaJeztah** [comment] 2024-01-25 12:35
Don't know if there's an option to manually configure kubelet to use a specific API version; if it's using the docker API client, then _possibly_ it can be overridden using the `DOCKER_API_VERSION` env-var, which then would have to be set for the kubelet process; see https://pkg.go.dev/github.com/docker/docker/client#EnvOverrideAPIVersion 

But otherwise, this sounds like a bug in kubelet (not using API version-negotiation), or maybe newer versions of it do support that?

I see you also opened https://github.com/moby/moby/issues/47215, I'll copy my comments there.

**Comment by vvoland** [comment] 2024-01-25 12:40
> Don't know if there's an option to manually configure kubelet to use a specific API version; 

Should be possible by passing `DOCKER_API_VERSION` to `cri-dockerd`, but only if the dockerEndpoint is not specified explicitly:
https://github.com/Mirantis/cri-dockerd/blob/519e39ceaa7f9e00319149b9d74b243466fa3963/libdocker/client.go#L77-L89

**Comment by UgOrange** [comment] 2024-02-13 14:59
Unfortunately, I am currently experiencing this issue as well. I would like to inquire if there are any plans for a fix, or if the recommended solution at this time is to downgrade the Docker version. Any guidance or updates on this matter would be greatly appreciated.

**Comment by thaJeztah** [comment] 2024-02-13 15:39
@UgOrange depends on where the issue is you're running into; I see patches were merged in cri-dockerd, as it wasn't using the versioned API (but not sure if it was released already @neersighted ?), and was still using a deprecated field. And I saw a fix was merged in google/go-containerregistry, but I don't know what the status is for other tools.

**Comment by YunanJeong** [comment] 2024-02-28 10:21
Same issue

Docker 25.0.3
k3s v1.28.6+k3s2 
Ubuntu 22 LTS

![image](https://github.com/moby/moby/assets/26271079/1595d3b2-632e-4b98-ab06-f393c967298c)


```
 Events:                                                                                                   │
│   Type     Reason          Age                  From     Message                                          │
│   ----     ------          ----                 ----     -------                                          │
│   Warning  Failed          91m (x12 over 93m)   kubelet  Error: ImageInspectError                         │
│   Warning  InspectFailed   33m (x280 over 93m)  kubelet  Failed to inspect image "rancher/klipper-helm:v0 │
│ .8.2-build20230815": Id or size of image "rancher/klipper-helm:v0.8.2-build20230815" is not set           │
│   Normal   SandboxChanged  30m                  kubelet  Pod sandbox changed, it will be killed and re-cr │
│ eated.                                                                                                    │
│   Warning  Failed          28m (x12 over 30m)   kubelet  Error: ImageInspectError                         │
│   Warning  InspectFailed   41s (x144 over 30m)  kubelet  Failed to inspect image "rancher/klipper-helm:v0 │
│ .8.2-build20230815": Id or size of image "rancher/klipper-helm:v0.8.2-build20230815" is not set   
```

**Comment by neersighted** [comment] 2024-02-28 14:09
This is not an issue in moby/moby; I am closing this issue as a PR fixing the issue has been merged into cri-dockerd.

**Closed by neersighted** 2024-02-28 14:09 UTC
Labels: status/0-triage, kind/bug

**Comment by benjaminr-ps** [comment] 2024-02-29 10:31
@neersighted Can you please link to the release or commit of cri-dockerd, fixing that particular issue?
Thank you in advance.

**Comment by neersighted** [comment] 2024-02-29 12:34
https://github.com/Mirantis/cri-dockerd/commit/9ac80dad297335dee11d453474f8fa48ec0b0c1a is present in v0.3.10
