### ISSUE TITLE
sysctl "kern.maxfiles" is not in a separate kernel namespace: unknown

### ISSUE THREAD

**Issue by lucaszanella** [moby/moby#36640] opened 2018-03-19 23:49 UTC
I'm trying to setup some sysctl parameters on the docker-compose:

```
services:
  jscam:
    build: ./dev
    sysctls:
      - kern.maxfiles=5242880
      - kern.maxfilesperproc=524288
    image: jscam
    stdin_open: true
    tty: true
    network_mode: "host"
    privileged: true
```

I get

Error response from daemon: OCI runtime create failed: sysctl "kern.maxfiles" is not in a separate kernel namespace: unknown

I've found somewhere that I need `privileged: true` and there it is in the compose file, but I get this error above.

Note that the command works if I run it inside the container in the terminal. It just won't work if passed as a docker command, so I think it is a bug, because my kernel clearly supports these parameters

**Comment by thaJeztah** [comment] 2018-03-20 00:15
This is expected; only a limited set of sysctls can be set on a container, because many sysctls are currently not namespaced. Setting other sysctls would not change a configuration for the _container_, but for the entire _host_, and are therefore blocked.

What happens if you enable `privileged`, and set those settings inside the container, is that you're actually setting those values for the host (which is why `--privileged` is really dangerous: containers are not "contained", and effectively provide no protection).

The documentation also mentions this; https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime

<img width="925" alt="screen shot 2018-03-20 at 01 05 18" src="https://user-images.githubusercontent.com/1804568/37628825-998c0890-2bdb-11e8-8b6f-3b98ddb792b3.png">


The list of currently accepted sysctls can be found in `runc` (the container runtime that's used by docker); https://github.com/opencontainers/runc/blob/9755e0065f60651e7c7d4b1c1dcf7c88f2fad1a8/libcontainer/configs/validate/validator.go#L123-L155

Also see https://github.com/moby/moby/issues/30778, https://github.com/moby/moby/issues/4717, and https://github.com/moby/moby/pull/19265 for more details.

I'm closing this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-03-20 00:15 UTC
