### ISSUE TITLE
docker stack deploy with key --with-registry-auth force pull new image

### ISSUE THREAD

**Issue by AlexNik** [moby/moby#42286] opened 2021-04-12 13:56 UTC
**Description**

**Steps to reproduce the issue:**
I'm building an image with Dockerfile
```
FROM alpine
CMD ["sh", "-c", "echo 1 && sleep 100"]
```
with command `docker build -t alexnik/test_docker:1 .` on **PC 1**.
Then push it to my dockerhub.

docker-compose.yml:
```
version: "3.8"

services:
  test_docker:
    image: alexnik/test_docker:1
```
Deploy it to new stack: `docker stack deploy --with-registry-auth --compose-file docker-compose.yml test_stack`
```
alex@alex:~/docker_test$ docker service logs test_stack_test_docker
test_stack_test_docker.1.hbesd3b4h1hv@alex    | 1
Output:
```
It creates service. Everything OK and I remove my stack.

```
alex@alex:~/docker_test$ docker images
REPOSITORY            TAG       IMAGE ID       CREATED              SIZE
alexnik/test_docker   1         6e2b542dca19   2 minutes ago        5.61MB
```

Then I build similar image on **PC2** with this Dockerfile and push it to docker hub:
```
FROM alpine
CMD ["sh", "-c", "echo 2 && sleep 2"]
```
`docker build -t alexnik/test_docker:1 . && docker push alexnik/test_docker:1`

On **PC2**
```
alex2@alex2:~/test_docker$ docker images
REPOSITORY                                                       TAG        IMAGE ID       CREATED             SIZE
alexnik/test_docker                                              1          ffcfa8f7f756   10 minutes ago      5.61MB
```

Then I deploy it to stack: `docker stack deploy --with-registry-auth --compose-file docker-compose.yml test_stack`

**Describe the results you received:**
```
alex@alex:~/docker_test$ docker service logs test_stack_test_docker
test_stack_test_docker.1.p9sl2tgw2kmy@alex    | 2
```
```
alex@alex:~/docker_test$ docker images
REPOSITORY            TAG       IMAGE ID       CREATED          SIZE
alexnik/test_docker   <none>    ffcfa8f7f756   25 minutes ago   5.61MB
alexnik/test_docker   1         6e2b542dca19   30 minutes ago   5.61MB
```

**Describe the results you expected:**
One of these:
1) Output from first original image
```
alex@alex:~/docker_test$ docker service logs test_stack_test_docker
test_stack_test_docker.1.p9sl2tgw2kmy@alex    | 1
```
```
alex@alex:~/docker_test$ docker images
REPOSITORY            TAG       IMAGE ID       CREATED          SIZE
alexnik/test_docker   1         6e2b542dca19   30 minutes ago   5.61MB
```
2) Change tag to `<none>` for original image and download new image with tag `1`.
```
alex@alex:~/docker_test$ docker service logs test_stack_test_docker
test_stack_test_docker.1.p9sl2tgw2kmy@alex    | 2
```
```
alex@alex:~/docker_test$ docker images
REPOSITORY            TAG       IMAGE ID       CREATED          SIZE
alexnik/test_docker   1         ffcfa8f7f756   25 minutes ago   5.61MB
alexnik/test_docker   <none>    6e2b542dca19   30 minutes ago   5.61MB
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker download **NEW** image by himself without notification. And it downloads it **without tag** (see `<none>`).

**Output of `docker version`:**

```
alex@alex:~/docker_test$ docker version
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:59 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:40 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0docker info
```

**Output of `docker info`:**

```
alex@alex:~/docker_test$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 3
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: laoj39kc5lgpv9a1hqfshodt8
  Is Manager: true
  ClusterID: yknfnerf6xcgkaek0qc652zp3
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.44.92
  Manager Addresses:
   192.168.44.92:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-140-generic
 Operating System: Ubuntu 18.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.788GiB
 Name: alex
 ID: OQE4:TJOF:DDEG:SRFV:76E3:QW7B:VTYV:F647:3TRW:3GTN:AQYG:7VK2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: alexnik
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2021-04-14 14:12
This is expected; swarm services are primary targeted at deploying in a production cluster, and do not (by default) use images from the local image store. Swarm services treat the _registry_ as source of truth for images, as local images may only be available on the node itself, or could be "replaced" by a locally built image (effectively "spoofing" the image).

Instead, when deploying a service, docker will resolve the _digest_ (immutable reference) of the image you specified, pull, and use that to deploy instances; the digest/immutable reference guarantees that all instances of the service run exactly the same image.

If you want to skip resolving the image, and either use an image that's present on the node, or have it pull the image by _tag_ if not present, you can use the `--resolve-image=never` option.

Let me close this ticket, as this looks to be working as intended, but feel free to continue the conversation.

**Closed by thaJeztah** 2021-04-14 14:12 UTC
Labels: area/distribution, area/images, area/swarm, kind/question, version/20.10
