### ISSUE TITLE
Docker 18.09.1 doesn't work with iptables v1.8.2

### ISSUE THREAD

**Issue by cwrau** [moby/moby#38759] opened 2019-02-19 16:06 UTC
**Description**

When I try to deploy a container and expose it on a port it failed with this error:

```
docker run --rm -it -p 80:80 alpine

docker: Error response from daemon: driver failed programming external connectivity on endpoint unruffled_goldwasser (c99e441c46a8317bb62c99bbea46f289fe7a317b54bbe3abe51e83c21d709323):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.17.0.2:80 ! -i docker0: iptables v1.8.2 (legacy): unknown option "--to-destination"
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)).
```

**Steps to reproduce the issue:**
1. Run the above command with iptables 1.8.2

**Describe the results you received:**
```
docker run --rm -it -p 80:80 alpine

docker: Error response from daemon: driver failed programming external connectivity on endpoint unruffled_goldwasser (c99e441c46a8317bb62c99bbea46f289fe7a317b54bbe3abe51e83c21d709323):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.17.0.2:80 ! -i docker0: iptables v1.8.2 (legacy): unknown option "--to-destination"
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)).
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.2-ce
 API version:       1.39
 Go version:        go1.11.5
 Git commit:        62479626f2
 Built:             Mon Feb 11 23:58:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       4c52b901c6
  Built:            Thu Jan 10 06:50:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 32
Server Version: 18.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b.m
runc version: ccb5efd37fb7c86364786e9137e22948751de7ed-dirty
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.20-1-MANJARO
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.49GiB
Name: cwr
ID: TU5A:APOO:S4OL:RAZH:ZCRD:ZKPP:5DCX:JU56:RZH2:QH4X:NMDY:X33X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of `iptables -V`:**

```
iptables v1.8.2 (legacy)
```

**Comment by thaJeztah** [comment] 2019-03-01 10:52
ping @arkodg PTAL

**Comment by cwrau** [comment] 2019-03-01 11:28
Now after various reboots, it seems to be working again?
Maybe it was just a bad update?
If no one else got this problem, we could close this :man_shrugging:

**Comment by thaJeztah** [comment] 2019-03-01 11:57
Ah, thanks for the update!

@arkodg was looking at some related issues,  so perhaps he can try if it's reproducible.

I'll close this one for now, but we can reopen if there turns out to be an issue; also feel free to continue the conversation after I closed 👍

**Closed by thaJeztah** 2019-03-01 11:57 UTC
Labels: area/networking, kind/bug, version/18.09

**Comment by arkodg** [comment] 2019-03-01 21:08
hi @cwrau, looks like arch-linux (like Debian) has iptables-legacy as well 
https://github.com/docker/libnetwork/pull/2343
should make sure iptables rules pushed by libnetwork can coexist with rules
pushed by other firewall managers

**Comment by ymkjp** [comment] 2019-03-18 08:07
I see the same error on arch as well.
Note that arch uses [iptables](https://www.archlinux.org/packages/core/x86_64/iptables/) with legacy interface for both `iptables` and `iptables-legacy`.

```
$ uname -r
4.20.12-arch1-1-ARCH
$ iptables --version
iptables v1.8.2 (legacy)
$ iptables-legacy --version
iptables v1.8.2 (legacy)
```

```
$ docker run --rm -it -p 80:80 alpine  
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
8e402f1a9c57: Pull complete 
Digest: sha256:644fcb1a676b5165371437feaa922943aaf7afcfa8bfee4472f6860aad1ef2a0
Status: Downloaded newer image for alpine:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint tender_volhard (954d664336eb5ea7b2c7f808889b3033977b45f53f99ba38bbc66bfcf14a61ef):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.17.0.2:80 ! -i docker0: iptables v1.8.2 (legacy): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)).
```

<details><summary>Docker versions</summary>
<p>

**Output of `docker version`**:

```python
Client:
 Version:           18.09.3-ce
 API version:       1.39
 Go version:        go1.12
 Git commit:        774a1f4eee
 Built:             Thu Feb 28 20:38:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       62479626f2
  Built:            Mon Feb 11 23:55:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`**:

```
Containers: 93
 Running: 0
 Paused: 0
 Stopped: 93
Images: 558
Server Version: 18.09.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b.m
runc version: ccb5efd37fb7c86364786e9137e22948751de7ed-dirty
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.20.12-arch1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.18GiB
Name: t480arch
ID: S4PH:3NN4:QYPI:Z6MT:SMPC:E3GL:HPMX:RWT7:JPB3:BPB5:TL7T:P36V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ymkjp
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

</p>
</details>

**Comment by ymkjp** [comment] 2019-03-18 13:28
Here's a workaround for arch users:

```bash
sudo ln -s /usr/bin/iptables-nft /usr/local/bin/iptables
reboot
```

See [Arch Linux Forums](https://bbs.archlinux.org/viewtopic.php?pid=1837607) for more details.

**Comment by CollinChaffin** [comment] 2019-03-22 22:01
Surprised this is closed.  On latest docker latest PhotonOS with `iptables v1.8.0 (legacy)`, it's broken and I see no workaround above or am I missing something?

```
.....truncated....
(iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9443 -j DNAT --to-destination X.X.X.X:443 ! -i docker0: iptables v1.8.0 (legacy): unknown option "--to-destination"
Try `iptables -h' or 'iptables --help' for more information.
```

Is there any solution?

**Comment by zancas** [comment] 2019-04-26 02:12
> Surprised this is closed. On latest docker latest PhotonOS with `iptables v1.8.0 (legacy)`, it's broken and I see no workaround above or am I missing something?
> 
> ```
> .....truncated....
> (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9443 -j DNAT --to-destination X.X.X.X:443 ! -i docker0: iptables v1.8.0 (legacy): unknown option "--to-destination"
> Try `iptables -h' or 'iptables --help' for more information.
> ```
> 
> Is there any solution?

@CollinChaffin I had the same problem as you, so I upgraded iptables to 1.8.2, with that version of iptables the symlink hack:

```BASH
sudo ln -s /usr/bin/iptables-nft /usr/local/bin/iptables
reboot
```

Appears to work.

**Comment by han-so1omon** [comment] 2019-05-29 18:12
Why symlink to /usr/local/bin instead of /usr/bin? My iptables bin is in /usr/bin (Manjaro 18 xfce)

**Comment by ngortheone** [comment] 2019-08-31 19:23
Please re-open this. The workaround no-longer works for `iptables-nft` `1.8.3`
```
$ iptables-nft --version
iptables v1.8.3 (nf_tables)
```

```
$ iptables-nft --help | grep dport | wc
      0       0       0
```

**Comment by actionless** [comment] 2019-12-13 01:45
@han-so1omon to avoid overwriting `/usr/bin/iptables` owned by `iptables` package itself (which also will be rewritten by `iptables` on its next upgrade)

**Comment by BenElgar** [comment] 2020-03-17 17:40
For anyone else stumbling upon this issue, this happened to me on Arch Linux after an upgrade and was resolved by a restart—no symlink required.

**Comment by Arnie97** [comment] 2020-09-04 12:47
Try both `iptables-nft` and `iptables-legacy` if you're not sure which one works on your system. In my case I have to link `iptables-legacy` as `iptables` to fix it. Hope it helps.

**Comment by w4** [comment] 2020-09-07 14:23
This is because `iptables` is failing to load the DNAT module (because of the `-j DNAT` flag). Make sure you can `modprobe ipt_DNAT`.

**Comment by iamwwc** [comment] 2021-05-09 07:10
In my case, I have to

```
rm /usr/sbin/iptables
ln -s /usr/sbin/iptables-legacy /usr/sbin/iptables
```

**Comment by piotr-sikora-v** [comment] 2021-09-21 07:30
I have problem with `unknown option "--dport"` on Ubuntu focal

I don't know why I have on one machine installed linux-image-5.4.0-84-generic instend of linux-image-5.4.0-81-generic

in linux-image-5.4.0-84-generic i found there is a problem with xt_tcpudp module.

After downgrandign to linux-image-5.4.0-81-generic everything start works

**Comment by specious** [comment] 2021-11-14 00:38
For me it was putting `iptables-legacy` where `dockerd` would load it instead of iptables-nft:

```
sudo ln -s /usr/bin/iptables-legacy iptables
```

And `sudo dockerd` started up with no reboot.

```
$ uname -a
Linux x1 5.15.2 #1 SMP PREEMPT Sat Nov 13 13:14:18 EST 2021 x86_64 GNU/Linux

$ dockerd --version
Docker version 20.10.10, build e2f740de44

$ iptables --version
iptables v1.8.7 (legacy)
```

**Comment by specious** [comment] 2021-11-14 00:42
> Why symlink to /usr/local/bin instead of /usr/bin? My iptables bin is in /usr/bin (Manjaro 18 xfce)

So it doesn't conflict with system files. `/usr/local/bin` will take PATH precedence, and you can just remove it once it's no longer needed.

**Comment by Paraphraser** [comment] 2022-07-26 23:55
Also surprised this issue is closed because it's still a problem. Rather than the symlink to `iptables-nft` proposed above I just replaced "iptables" with "iptables-nft" in the commands.
