### ISSUE TITLE
Cannot pull image from private registry

### ISSUE THREAD

**Issue by Rukeith** [moby/moby#38104] opened 2018-10-30 01:29 UTC
**Description**
While I try to pull image from registry, I got https error. Then I add `insecure-registries` to /etc/docker/daemon.json and restart docker.
After that I try pull image again. Got error is `error pulling image configuration: unknown blob`.
Is that any way to fix this?

**Steps to reproduce the issue:**
1. push image to registry
2. edit /etc/docker/daemon.json to add registry server ip and restart docker
3. pull image from registry

**Describe the results you received:**
```
5.7: Pulling from mysql
802b00ed6f79: Pulling fs layer
30f19a05b898: Pulling fs layer
3e43303be5e9: Pulling fs layer
94b281824ae2: Waiting
51eb397095b1: Waiting
54567da6fdf0: Waiting
bc57ddb85cce: Waiting
c7c0a9c25d8a: Waiting
cce6c47ac3fc: Waiting
499b9c7376c8: Waiting
6c5e08e005ea: Waiting
error pulling image configuration: unknown blob
```

**Describe the results you expected:**

It should pull image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-136748579-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 3.205GB
 Data Space Total: 107.4GB
 Data Space Available: 31.73GB
 Metadata Space Used: 4.887MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.143GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.842GiB
Name: TWSR-WHTestServer01.garenanet.com
ID: AZIT:7GZF:YTZY:TDD3:YXVP:QGOF:T63X:5ASL:ZXP3:TRSS:45KB:ET5X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

CentOS Linux release 7.5.1804 (Core) on VirtualBox

**Comment by thaJeztah** [comment] 2018-10-30 12:18
You're likely getting the `https` error _because_ your registry is not using a secure (https) connection. Docker (by default) uses https to connect to a registry, and will fail if it cannot make a secure connection.

So, to make this work, either;

- configure your registry to use a https connection (https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry). This is really the recommended approach, you should not run a registry that's accessible over an insecure, plain http, connection
- mark the registry as "insecure" (which is what you did), which means that dockerd will allow connections to the registry, even if the certificate is invalid, or if there's no https available. This should only be used for testing, as it's highly insecure.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-10-30 12:18 UTC
