### ISSUE TITLE
No colored output for multiple nested Container

### ISSUE THREAD

**Issue by Zethson** [moby/moby#41057] opened 2020-06-02 15:11 UTC
**Description**

Even though the ENV variable TERM=xterm-256color is set for a multiply nested Docker container, colored output is disabled. It works when only a single inheriting container is used, but not when inheriting from this container again.

**Steps to reproduce the issue:**
1. 
Build the container below and tag it `mlflowcore/base:1.0.0`
```
FROM nvidia/cuda:10.2-base-ubuntu18.04

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*

# Create a working directory and set it as default
RUN mkdir /app
RUN chmod 777 /app
WORKDIR /app

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user 
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

 # Install Miniconda
RUN wget -O ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# Update Conda
RUN conda update conda
```
2.
Run the container via `docker run --rm -it --gpus all mlfcore/base:1.0.0 env TERM=xterm-256color /bin/bash`. Note that colored support is enabled.
3. Now build a second container and tag it mlflowcore/pytorch:dev .
```
FROM mlflowcore/base:1.0.0

# Install the conda environment
COPY pytorch_environment.yml .
RUN conda env create -f pytorch_environment.yml && conda clean -a

# Activate the environment
RUN echo "source activate pytorch" > ~/.bashrc
ENV PATH /home/user/miniconda/envs/pytorch/bin:$PATH

# Dump the details of the installed packages to a file for posterity
RUN conda env export --name pytorch > pytorch.yml

# Currently required, since mlflow writes every file as root!
USER root
```
Note that now, when you run this container with the environment variable you will no longer get colored output! `docker run --rm -it mlfcore/pytorch:dev env TERM=xterm-256color ls -la
`
**Describe the results you received:**

No colored terminal output.

**Describe the results you expected:**

Colored terminal output.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 19.03.10-ce, build 9424aeaee9
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 414
 Server Version: 19.03.10-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.6.15-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.53GiB
 Name: master
 ID: O5FD:E5AC:RYMK:4H5Z:SVYX:G7NF:6T5D:EHGU:6Q32:RXUI:6DAK:6E2C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Thank you very much!

**Comment by thaJeztah** [comment] 2020-06-02 15:31
Probably because it's not an interactive shell in the second case; try

```bash
# run bash non-interactive;
docker run -it --rm ubuntu:20.04 /bin/bash -c 'ls -la'

# run bash with the `-i` option (interactive)
docker run -it --rm ubuntu:20.04 /bin/bash -ic 'ls -la'
```

or, running `ls` with the `--color` option;

```bash
docker run -it --rm ubuntu:20.04 ls --color=always -la
```

I don't think think there's a bug at hand here, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-02 15:31 UTC

**Comment by Zethson** [comment] 2020-06-02 15:33
@thaJeztah The issue is persistent in an interactive shell. I just directly ran ls -la here as a shortcut.

So `docker run --rm -it mlfcore/pytorch:dev env TERM=xterm-256color /bin/bash` also reproduces the issue.

Please reopen. Thanks!

**Comment by thaJeztah** [comment] 2020-06-02 15:49
Can you reduce the reproduction steps to narrow down the changes? Docker should make no difference in this area, but I do see there's a lot of things happening in the Dockerfile. For example, does it also reproduce if you skip the `RUN echo "source activate pytorch" > ~/.bashrc` step?

```bash
docker build -t repro-41057 -<<EOF
FROM ubuntu:20.04
RUN echo "" > ~/.bashrc
USER root
EOF

docker run -it --rm repro-41057 /bin/bash
ls -la
# no colored output


docker build -t repro-41057 -<<EOF
FROM ubuntu:20.04
USER root
EOF

docker run -it --rm repro-41057 /bin/bash
ls -la
# colored output
```

**Comment by Zethson** [comment] 2020-06-02 16:07
@thaJeztah 
You were right. The problematic line is indeed `RUN echo "source activate pytorch" > ~/.bashrc`

What is the underlying issue and what can be done about it?

Thank you very much for your time and help!

**Comment by thaJeztah** [comment] 2020-06-02 16:11
Not exactly sure, but I suspect having a `~/.bashrc` unsets some defaults that would otherwise be set

**Comment by Zethson** [comment] 2020-06-02 16:12
@thaJeztah The ENV variable is still set and therefore should be available.

I don't know where to start debugging this...

**Comment by Zethson** [comment] 2020-06-02 16:21
@thaJeztah 
I was overwriting the default .bashrc instead of appending this line. Appending it fixes it.

Thank you again. Oh, and the issue on Twitter is something different and completely unrelated to this technical issue :)

Cheers
