### ISSUE TITLE
running boot2docker with CPU=4 results in kernel panic under VirtualBox and on Native Linux Box

### ISSUE THREAD

**Issue by zhang-luke** [moby/moby#20244] opened 2016-02-11 21:33 UTC
Docker version:
Client:
 Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64

Docker info:

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.764 GiB
Name: default
ID: LRFQ:OHOK:HXKD:OSDO:5NHY:5PI5:5W4K:VWZQ:LOXM:F47B:RBBM:ABUS
Debug mode (server): true
 File Descriptors: 19
 Goroutines: 38
 System Time: 2016-02-11T21:20:54.042499953Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

Description:
With cpu-count =4
After Nodejs started , it watch src directory, after a while kernel panic error is thrown out. VirtualBox crashes.

But if I run VirtualBox with CPU count = 1, it works fine.

Dockerfile:
FROM node:5.4

RUN apt-get update

RUN apt-get -y -qq install ruby ruby-dev irb rdoc ri
RUN apt-get install -y ruby-full rubygems-integration
RUN npm install --global npm-check

RUN npm install -g bower
RUN npm install grunt-cli -g

RUN gem install scss-lint
# install compass
# RUN gem install --no-rdoc --no-ri compass

ENV HOME /root
RUN apt-get install make
RUN gem install compass
RUN mkdir /app
ADD ./ui /app
COPY core /app
COPY modihosts /app
WORKDIR /app
RUN rm -rf ./node_modules
RUN npm cache clean
RUN npm install \
  && rm -rf /var/cache/yum \
  && rm -rf /usr/lib/locale \
  && rm -rf /usr/lib/gcc \
  && rm -rf /usr/share/locale

ENV PHANTOMJS_BIN=/home/pulsar/app/phantomjs/bin

EXPOSE 9000
EXPOSE 35729

ENTRYPOINT /app/core

docker-compose.yaml

ginx:
   build: ./nginx
   ports:
      - "80:80"
      - "443:443"
frontend:
    build: ./frontend
    ports:
       - "5523:3000"
    volumes:
       - ../../../app/frontend/app:/app/app
       - ./config:/usr/local/etc/sophos/
ui:
    build: ./ui
    ports:
       - "9000:9000"
       - "35729:35729"
    volumes:
       - ../../ui/src:/app/src

api:
   build: ./api-services
   ports:
     - "7072:8080"
   volumes:
      - ../../sophos-cloud/api-services/build/libs:/usr/local/etc/libs
      - ./config:/usr/local/etc/sophos/
   links:
      - mongo
      - memcache
      - redis

hub:
   build: ./hub-services
   ports:
     - "7070:8080"
   volumes:
![screen shot 2016-01-28 at 6 11 35 pm](https://cloud.githubusercontent.com/assets/16838016/12991394/0d73e694-d0dd-11e5-970c-804897c665db.png)
![screen shot 2016-01-29 at 9 06 37 am](https://cloud.githubusercontent.com/assets/16838016/12991401/12224e06-d0dd-11e5-8e24-69df67f24c92.png)

**Comment by thaJeztah** [comment] 2016-02-14 23:56
ping @tianon sounds like a kernel issue?

**Comment by unclejack** [comment] 2016-02-15 09:01
This bug is caused by the kernel, VirtualBox or both. That stacktrace doesn't look like something which has to do with the processes which were being run.

**Comment by zhang-luke** [comment] 2016-02-17 12:54
The VirtualBox version is 5.0.14. r105127. If we run the same configuration on OS X 10.9, everything works fine. But if we run the container on OS X 10.10.5 Yosemite, then starting VirtualBox with 4 CPUs, kernel panic occurs after a while. But If we start VirtualBox with 1 CPU. Then it is stable.

**Comment by unclejack** [comment] 2016-02-17 13:00
@zhang-luke Have you tried this on OS X 10.11?

**Comment by zhang-luke** [comment] 2016-02-17 13:05
No, because 10.10.5 is  standard OS in our company, we are not allowed to upgrade to 10.11.

**Comment by AkihiroSuda** [comment] 2016-02-17 13:24
@zhang-luke Can you minimize the workload to a single short Docker file?
Then someone (including me) can easily try to reproduce and analyze the issue on his/her machine.

**Comment by zhang-luke** [comment] 2016-02-17 14:49
@AkihiroSuda,  I am working on a project to simulate our cloud system on one Mac machine, so I typically run about 15-20 containers in the same time, most of them tomcat services, plus nginx server contaner, ruby rails server, and Nodejs server container. also with mongodb/redis/memcache service containers, but only Nodejs container causing this kernel panic, I bet if I only run Nodejs container , it will still produce kernel panic problem. So the Dockerfile I provided here is the actual one with our requirement. I don't know if you slim it down , it will still causing crash. I think docker-compose configuration is irrelevant to this issue, but I provide it anyway. 
     I bet if I make Dockerfile simple, this problem will go away. Because if this is general problem of Nodejs container, there must be a lot of screaming out there. So it has to do with something we afre doing.

**Comment by AkihiroSuda** [comment] 2016-02-17 16:02
@zhang-luke 
OK, I understand your situation, but I'm not sure what is your `app` and how it "watches" the `src` directory. So I think no one can reproduce your issue at the moment.
I guess you cannot publish your actual `app` code, but can you explain something specific to your `app`?
Does it use `inotify`, `ptrace`, or some "interesting" syscalls?

**Comment by zhang-luke** [comment] 2016-02-17 16:18
@AkihiroSuda, we are using standard way of Nodejs 'watches' the src files we have, the configuration is known to Nodejs server users and is well explained in Nodejs documents. Whether Nodejs uses_ inotify_, _ptrace,_ I am not knowledgeable enough to confirm that.  I don't know anything about what Nodejs does underneath. But I know this problem is caused by the fact after the Nodejs container started, we map the directory of our source code of Javascripts and web pages to those that is inside the container so that once a developer change the code, the Nodejs inside container 'watches' them and re-compile and run all those Nodejs modules right way. That ultimately causing kernel panic. I hope this information help you.

**Comment by thaJeztah** [comment] 2016-02-17 18:07
@zhang-luke note that `inotify` is not working if you're mapping a host-directory on the Mac using virtualbox; Oracle closed that as a "won't fix" https://www.virtualbox.org/ticket/10660, so Nodejs watch may not get triggered on file changes

**Comment by zhang-luke** [comment] 2016-02-17 18:14
@thaJeztah, thank you for the info, the Nodejs watch does fire and works well with VirtualBox under 1 cpu confihuation on OS.X 10.10. But panic when I run with 4-CPUs, I want to run with 4-CPUs because it run too slow with 1-CPU. 
Also, both 1-CPU and 4-CPU VirtualBox work fine on OX X 10.9.

**Comment by AkihiroSuda** [comment] 2016-02-18 01:20
@zhang-luke Perhaps lsyncd can be an alternative solution: https://github.com/axkibe/lsyncd

**Comment by davibe** [comment] 2016-02-19 10:07
I get that very same stack trace of the screenshot but for me it happens with
- latest version of yosemite 10.11.3
- virtualbox 5.0.* (including .14)
- 2 or 4 cpus it does not meatter. 1 cpu is not an option for me, too slow
- happens more often on macbook airs, but also on my mbpro retina 15

It has become a nightmare because it happens everyday to all devs and I am trying to work around it. We do share the code with the VM from the host system (and run it from there) but I don't think we have watchers listening for changes.. not that i know of.

**Comment by huvber** [comment] 2016-02-19 10:16
same condition as @davibe with docker and boot2docker to `1.10.1` versione

**Comment by zhang-luke** [comment] 2016-02-23 19:47
I used VMWare Fusion as driver fixed this problem, it happened my company already bought Fusion licenses. I am disappointed that VirtualBox does not work. BUt even if it works, it speed is nowhere to match that of VMWare.

**Comment by rapha-opensource** [comment] 2016-02-24 21:19
We are seeing the same crash with:
 VirtualBox 5.0.14 r105127 and Mac OS X 10.11.3.
Our software stack has 8 containers and is based on python. 
No NodeJS involved.
Setting --virtualbox-cpu-count to 1 fixes the problem.

**Comment by davibe** [comment] 2016-02-25 20:16
I did not try this yet but using nfs (https://github.com/adlogix/docker-machine-nfs) should fix all these problems while also leading to better performances

**Comment by cpuguy83** [comment] 2016-02-25 20:33
I don't have any issues here. Can anyone that's having issues describe their vbox settings?
Is VT-x enabled? PAE?
Have you changed any of the settings that docker-machine sets up from the vbox interface?

**Comment by zhang-luke** [comment] 2016-02-25 20:57
My Vbox setting 
On OS X. 10.10.5
version: 5.0.14.r105127
Memory 6144 MB
CPU count: 4
Type: Linux 2.6
VT-x/AMD-V: enabled
Nested Paging: enabled

Kernel panic occurs to Node.js container

**Comment by zhang-luke** [comment] 2016-03-01 21:07
We see the same problem occurs when run it on Linux (Debian ), Docker is running native on Linux, wouldn't be Docker's responsibility to fix this if Docker rely on  Linux to be successful?

**Comment by thaJeztah** [comment] 2016-03-02 00:02
> We see the same problem occurs when run it on Linux (Debian ), Docker is running native on Linux

Is that also on VirtualBox?

**Comment by zhang-luke** [comment] 2016-03-02 13:38
@thaJeztah No, this time we run the containers on a Native Linux(Debian) OS installed on PC, the same type kernel panic occurs.

**Comment by cpuguy83** [comment] 2016-03-02 13:54
@zhang-luke "same type" as in the same output or just a kernel panic?

Note that all kernel panics are bugs in the kernel. You should be using a kernel provided by the OS distro maintainer and it must be > 3.10.

**Comment by zhang-luke** [comment] 2016-03-02 14:14
@cpuguy83, yes, I did not keep the copy of output, but by reading it is looks like the same output as it occured on VirtualBox.   We are using kernel version is 3.16.0.

**Comment by huvber** [comment] 2016-03-02 15:02
we notice that if we deactivate nodemon or webpack watching the kernel panics stops. So could be something related with sync the fs from outside the VM to inside

**Comment by zhang-luke** [comment] 2016-03-02 15:14
@huvber, yes, we know the similar situation. If we stop mounting volumes from host to container, panic stops. But that is an indispensable thing for dev environment, if we don't watch, then the container is useless, we are doing it for dev, not for production. Things keep changing.

**Comment by davibe** [comment] 2016-03-06 10:32
This does not solve anything but it's a nice recap of all the existing workarounds.

http://oliverguenther.de/2015/05/docker-host-volume-synchronization/

**Comment by zhang-luke** [comment] 2016-03-10 16:03
Thanks for suggestion. With setting chipset=ICH9 on VB, we are able to calm the kernel stable, still testing

**Comment by zhang-luke** [comment] 2016-03-11 16:40
We found that the 'kernel panic' happened on Debian linux platform but did not occur to Ubuntu Linux OS.

**Comment by thaJeztah** [comment] 2016-03-11 20:01
> We found that the 'kernel panic' happened on Debian linux platform but did not occur to Ubuntu Linux OS. When we run our system on Linux.

Is this the same kernel version (3.16?) if I remember correctly there have been lots of issues with kernel 3.16 and stability (in general), so be sure to have it up to date

**Comment by zhang-luke** [comment] 2016-03-11 21:04
The Ubuntu kernel version is 3.13.0-79 64 bit. I forget Debian kernel version , but I remember it was very latest.

**Comment by zhang-luke** [comment] 2016-03-15 12:48
To conclude this thread:
Node.js + Docker container with mounted volume for dev: The OS that 'kernel panic' did not occur:
1. Mac Yosemite + VMWare Fusion : very fast , best in performance.
2. Ubuntu Linux 14.04 + docker : stable so far.
3. Will test Centos Linux

**Comment by justincormack** [comment] 2016-08-29 22:42
@zhang-luke is this still an issue? Have you tried Docker for Mac?

**Comment by joelhandwell** [comment] 2017-04-04 17:26
Getting same issue on Windows 10 with docker installed by chocolatey, virtual box boot2docker VM created via [this Vagrantfile](https://github.com/joelhandwell/dockerhost/blob/master/Vagrantfile) provisioned by docker-machine.
Following is my environment:
```
> ver
Microsoft Windows [Version 10.0.15063]
> vboxmanage -v
5.1.18r114002
> vagrant -v
Vagrant 1.9.3
> docker-machine -v
docker-machine.exe version 0.10.0, build 76ed2a6
> docker -v
time="2017-04-04T13:23:28-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Docker version 17.03.1-ce, build c6d412e
```

Following is VirtualBox GUI:
![image](https://cloud.githubusercontent.com/assets/3857152/24669944/40130b88-193a-11e7-9643-05ddda7a579d.png)

**Comment by thaJeztah** [comment] 2023-09-16 17:04
boot2docker was deprecated 
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 17:04 UTC
Labels: version/1.10
