### ISSUE TITLE
docker devicemapper data file size increasing exponentially

### ISSUE THREAD

**Issue by manojakondi** [moby/moby#22659] opened 2016-05-11 11:09 UTC
I'm running a several docker containers as Web Servers on different servers. But on one server, the size of "data" file under devicemapper folder is increasing exponentially. It has consumed 40GB of total 50GB available under 2 days. But on the other servers with same docker configuration, I didn't find any problem. Only on this one. The logs that are being generated by Webserver are consuming only 400MB. Can any one help me solve this?

```
# docker version
Client:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

```

```
# docker info
Containers: 1
Images: 69
Storage Driver: devicemapper
 Pool Name: docker-253:4-262147-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 41.6 GB
 Data Space Total: 107.4 GB
 Data Space Available: 10.45 GB
 Metadata Space Used: 24.77 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.123 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /opt/docker/devicemapper/devicemapper/data
 Metadata loop file: /opt/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
CPUs: 2
Total Memory: 3.695 GiB
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

```
# df -h
Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/rootvg-root            1.9G  474M  1.4G  26% /
devtmpfs                           1.9G     0  1.9G   0% /dev
tmpfs                              1.9G   16K  1.9G   1% /dev/shm
tmpfs                              1.9G   57M  1.8G   4% /run
tmpfs                              1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mapper/rootvg-usr             3.8G  1.7G  2.0G  46% /usr
/dev/sda1                          190M  128M   49M  73% /boot
**/dev/mapper/datavg-datalv           50G   40G  9.5G  81% /opt**
/dev/mapper/rootvg-home            1.9G  112M  1.7G   7% /home
/dev/mapper/rootvg-tmp             1.9G   23M  1.8G   2% /tmp
/dev/mapper/rootvg-var             9.5G  1.5G  7.6G  16% /var
/dev/mapper/rootvg-opt             4.7G  346M  4.1G   8% /opt
tmpfs                              379M     0  379M   0% /run/user/1596800068
tmpfs                              379M     0  379M   0% /run/user/0
tmpfs                              379M     0  379M   0% /run/user/1596900577
```

If you see the size of /opt here, 81% of the total space is being used in it.

My docker files are being saved under /opt. Please see the details of `/opt/docker/devicemapper/devicemapper/` below

```
# du -sh *
39G     data
24M     metadata
```

Can any one explain what is causing the issue and how to solve this?

**Comment by cpuguy83** [comment] 2016-05-11 13:10
Is the container writing to the container fs?

**Comment by runcom** [comment] 2016-05-11 13:17
cc @rhvgoyal also

**Comment by manojakondi** [comment] 2016-05-11 13:22
it is writing to the location that I have specified above. /opt/docker/devicemapper/devicemapper/data in the host.

**Comment by cpuguy83** [comment] 2016-05-11 13:23
@manojakondi I'm talking about inside the container.
Whatever is written inside the container is going to make the data usage go up.

**Comment by manojakondi** [comment] 2016-05-11 13:29
yeah.. I checked that.. Inside the container, the logs that are being written occupies just around 300MB and the whole application code that is being hosted there occupies 3.4GB. nothing more.

**Comment by steve-gray** [comment] 2016-05-11 22:35
We've got what appears to be the same issue, and it's crippled our Docker-in-Docker workflow for CI testing of stacks. I'd reported this as #22677 a moment ago but got directed that it was a duplicate. Basically we're getting DM exhaustion on freshly created containers and space filling up. The below results were just duplicated a minute ago using Alpine Linux 3.1 as an image instead of Centos7.

My issue data was:

------------------------------------------------------------------
We're having issues where we are unable to run even the most modest of docker-in-docker testing scenarios because even though the host volume group has 100GB+ data space, almost every operation fails with a message about free space, such as:

```
output: write /usr/lib64/libopcodes-2.23.52.0.1-55.el7.so: no space left on device
Traceback (most recent call last):
```

It appears that for some reason space is getting consumed on the host, despite us using a devicemapper storage device (you can see confirmation of this below in the docker info output). The ExecStart options we are using are:

````
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2375 -H fd:// --storage-driver=devicemapper --storage-opt dm.basesize=64G --storage-opt dm.datadev=/dev/vgDocker/lvData --storage-opt dm.metadatadev=/dev/vgDocker/lvMetadata
```

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```


**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-662217-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/vgDocker/lvData
 Metadata file: /dev/vgDocker/lvMetadata
 Data Space Used: 303.2 MB
 Data Space Total: 112.7 GB
 Data Space Available: 112.4 GB
 Metadata Space Used: 1.024 MB
 Metadata Space Total: 5.365 GB
 Metadata Space Available: 5.363 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.26 GiB
Name: dev
ID: UHUM:JHO5:LIMR:BBW7:3RLF:VECQ:VO2W:Q32W:VGKJ:FJIX:454P:G2GV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7 running in VM. 


**Steps to reproduce the issue:**
1. docker run --rm -it centos:7 df -h

**Describe the results you received:**
When running various operations inside the container, it seems that a huge amount of space is consumed on the /etc/hosts mount. For example:

````
[root@dev sgray]# docker run --rm -it centos:7 df -h
Filesystem                                                                                        Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-662217-97b5ea95167e5f153339f7489d101cd0216fb6cf35ac4d0aa075db0ee65ad52a   10G  241M  9.8G   3% /
tmpfs                                                                                              16G     0   16G   0% /dev
tmpfs                                                                                              16G     0   16G   0% /sys/fs/cgroup
/dev/mapper/centos-root                                                                            12G  1.9G  8.8G  18% /etc/hosts
shm                                                                                                64M     0   64M   0% /dev/shm
[root@dev sgray]#
````

**Describe the results you expected:**
The /etc/hosts mount should not be showing so much used space. Specifically if I do cat /etc/hosts - it shows 3 lines, which doesnt quite add up to nearly 2GB. 

**Additional information you deem important (e.g. issue happens only occasionally):**

The reason this is problematic is that when I run docker-in-docker type CI testing, we've got issues where even though we mount a volume to hold /var/lib/docker content - the /etc/hosts mount just fills up almost immediately and dies. For example, here's another machine, here's the output from the most affected machine we have. Note I'm literally just starting up a blank container and running the command to show free space. 

````
[sgray@build ~]$ docker run --rm -it centos:7 df -h
Filesystem                                                                                        Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-662217-c65cb6b4ab5c21adb37aa84505e2b7ab4653580238f5ddd06c4cc6e131368781   10G  241M  9.8G   3% /
tmpfs                                                                                              24G     0   24G   0% /dev
tmpfs                                                                                              24G     0   24G   0% /sys/fs/cgroup
/dev/mapper/centos-root                                                                            12G   10G  651M  95% /etc/hosts
shm                                                                                                64M     0   64M   0% /dev/shm
[sgray@build ~]$
````

**Comment by steve-gray** [comment] 2016-05-11 22:58
@thaJeztah - Is this another #22610 dupe?

**Comment by thaJeztah** [comment] 2016-05-11 23:04
@steve-gray could be, but let's wait until we have looked more into it

**Comment by manojakondi** [comment] 2016-05-13 06:06
@steve-gray I have update my docker from 1.8.2 to 1.9.1 and hurray!! it solved the issue. I'm not sure that was the intended fix. But it did work for me. Any insights??

**Comment by steve-gray** [comment] 2016-05-13 06:36
Not much help me me when I'm already bumped to on 11.1 on the hosts and having the same issue. Is there some version bump script that resets things to allow this to clean up the space?

**Comment by manojakondi** [comment] 2016-05-13 06:46
@thaJeztah Any idea?? Is it really the issue with version??

**Comment by thaJeztah** [comment] 2016-05-13 11:28
@manojakondi difficult to tell; what version do you have running now, is this the Red Hat package, or the official docker package? The issue you originally had installed (1.8.2 https://github.com/projectatomic/docker/commit/a01dc02) is a version of docker that contains quite a lot of changes https://github.com/docker/docker/compare/v1.8.2...projectatomic:a01dc02 compared to the "vanilla" docker versions.

**Comment by steve-gray** [comment] 2016-05-13 11:40
I'm running a vanilla variant of things: is there some specific diagnostics I can provide to help investigate the issue? 

@manojakondi - Are you, like myself, running the host's / (root) mount from an LVM volume? I had to grow the LVM volume to let my containers keep working, even though the containers were on a seperate vg.

**Comment by HackToday** [comment] 2016-05-14 01:34
@steve-gray  could you have `docker info` show ?

**Comment by steve-gray** [comment] 2016-06-26 21:50
Here it is, it spans versions (we're now @ 1.11.2 and still killing us frequently):

    Containers: 20
    Running: 2
    Paused: 0
    Stopped: 18
    Images: 65
    Server Version: 1.11.2
    Storage Driver: devicemapper
    Pool Name: docker-253:0-531958-pool
    Pool Blocksize: 65.54 kB
    Base Device Size: 10.74 GB
    Backing Filesystem: xfs
    Data file: /dev/vgDocker/lvData
    Metadata file: /dev/vgDocker/lvMetadata
    Data Space Used: 21.01 GB
    Data Space Total: 112.7 GB
    Data Space Available: 91.73 GB
    Metadata Space Used: 29.06 MB
    Metadata Space Total: 5.365 GB
    Metadata Space Available: 5.335 GB
    Udev Sync Supported: true
    Deferred Removal Enabled: false
    Deferred Deletion Enabled: false
    Deferred Deleted Device Count: 0
    Library Version: 1.02.107-RHEL7 (2015-12-01)
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
    Volume: local
    Network: bridge null host
    Kernel Version: 3.10.0-327.10.1.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    OSType: linux
    Architecture: x86_64
    CPUs: 4
    Total Memory: 31.26 GiB
    Name: <snip>
    ID: <snip>
    Docker Root Dir: /var/lib/docker
    Debug mode (client): false
    Debug mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: bridge-nf-call-iptables is disabled
    WARNING: bridge-nf-call-ip6tables is disabled

**Comment by ksylvan** [comment] 2016-07-09 02:44
I'm seeing this issue trying to do "make rpm" inside the docker-in-docker development setup.

I've identified it as /var/lib/docker/volumes/ growing and not being freed up during the process.

Running version `1.11.2` on the host and `1.12.0-dev` inside the container.

**Comment by ksylvan** [comment] 2016-07-09 02:48
My storage is devicemapper as well, with LVM backed storage:

    $ docker info
    Containers: 1
     Running: 1
     Paused: 0
     Stopped: 0
    Images: 52
    Server Version: 1.11.2
    Storage Driver: devicemapper
     Pool Name: docker-253:0-1050974-pool
     Pool Blocksize: 65.54 kB
     Base Device Size: 10.74 GB
     Backing Filesystem: xfs
     Data file: /dev/vg_ksylvan-t420/docker-data
     Metadata file: /dev/vg_ksylvan-t420/docker-metadata
     Data Space Used: 13.01 GB
     Data Space Total: 37.58 GB
     Data Space Available: 24.57 GB
     Metadata Space Used: 15.02 MB
     Metadata Space Total: 4.295 GB
     Metadata Space Available: 4.28 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Deferred Deletion Enabled: false
     Deferred Deleted Device Count: 0
     Library Version: 1.02.109 (2015-09-22)
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins: 
     Volume: local
     Network: host bridge null
    Kernel Version: 4.5.7-202.fc23.x86_64
    Operating System: Fedora 23 (Workstation Edition)
    OSType: linux

**Comment by cpuguy83** [comment] 2016-07-09 03:26
@ksylvan if /var/lib/docker/volumes is filling up and not being freed it's because you are writing to a volume and not removing it or anything stored in it.
This for is not related to devicemapper.

**Comment by ksylvan** [comment] 2016-07-09 03:58
I'm following the docker development flow here, nothing more:

https://docs.docker.com/opensource/project/set-up-dev-env/

After "make shell" and making the binaries in the container and starting "docker daemon", I do: "make rpm" and space runs out due to /var/lib/docker/volumes filling up.

**Comment by thaJeztah** [comment] 2016-07-09 04:57
`make rpm` by default builds rpms for all distros, and stores those in a volume, so  that's expected

**Comment by ksylvan** [comment] 2016-07-09 05:00
Thanks @thaJeztah Is there a way to limit it to one distro?

**Comment by thaJeztah** [comment] 2016-07-09 05:11
If you want to build only for specific distro, use the `DOCKER_BUILD_PKGS`
env-var, for example, to build a `rpm` package for CentOS 7
```bash
DOCKER_BUILD_PKGS=centos-7 make rpm
```

**Comment by ksylvan** [comment] 2016-07-09 05:14
Thank you. Is that documented somewhere and I missed it?

**Comment by ksylvan** [comment] 2016-07-09 07:32
Okay, this time I started by stopping docker, removing /var/lib/docker and restarting docker, with more than 70GB free, and `DOCKER_BUILD_PKGS=fedora-24 make rpm` still filled up the partition. How much space is expected to be needed for one distribution RPM?

**Comment by Rithwik572** [comment] 2017-01-16 18:44
Hi I am trying to pull image of DB2 (docker pull ibmcom/db2express-c) throws me error: no space left on device. I see base device size is 10 GB by default ( devicemapper)my image size is >10gb. How can I increase my base device size ???

**Comment by thaJeztah** [comment] 2017-01-16 18:47
@Rithwik572 see [Storage driver options](https://docs.docker.com/engine/reference/commandline/dockerd/#/storage-driver-options) - `dm.basesize`

**Comment by Rithwik572** [comment] 2017-01-16 19:11
@thaJeztah Hi when I type this command "sudo dockerd --storage-opt dm.basesize=50G" it throws error: sudo: dockerd: command not found.  Can you please suggest me how to workaround this issue

**Comment by thaJeztah** [comment] 2017-01-16 19:28
@Rithwik572 `dockerd` is the docker daemon, in older versions of docker it was `docker daemon`. However, GitHub is really not the place for this; Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by Rithwik572** [comment] 2017-01-16 19:32
ok thanks

**Comment by thaJeztah** [comment] 2023-06-06 07:54
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637

**Closed by thaJeztah** 2023-06-06 07:54 UTC
Labels: area/storage/devicemapper, version/unsupported, version/1.8
