### ISSUE TITLE
Multistage builds persist data from previous steps

### ISSUE THREAD

**Issue by pearofducks** [moby/moby#35774] opened 2017-12-12 13:43 UTC
When building a multistage image, artifacts from previous stages persist to later ones (when they logically shouldn't).

Quick example:

```
FROM alpine as builder
...do stuff

FROM alpine
...problem here!
```

At `problem here`, data is visible from the `builder` step, even if it wasn't copied.

**Steps to reproduce the issue:**

1. Clone and build https://github.com/pearofducks/docker-multistage-bug

Verbose version:

1. `docker build -t bug .`
2. `docker run -it bug ls`
3. Verify output is `Dockerfile  bar         baz         foo`

**Describe the results you received:**

The `/app` directory is populated with content from the first build's COPY step.

**Describe the results you expected:**

The `/app` directory should be clean (empty) since we're using `FROM` a base image.

As in - `alpine`s `/app` directory is empty, so a build step stating `FROM alpine` should have an empty `/app` directory.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.09.1-ce, build 19e2cf6
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: 2BNX:GJ22:RWF7:2PKN:H6VC:4WWY:MLB6:MTGK:EPJD:ENXS:MS2C:PNA5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 31
 System Time: 2017-12-12T13:42:59.872222193Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Comment by AkihiroSuda** [comment] 2017-12-20 08:49
Is this still issue in the master?
Could not locally reproduce.
```
Client:
 Version:       18.01.0-dev
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    2b8eb23b
 Built: Wed Dec 20 08:37:21 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      dev
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   745278d24
  Built:        Wed Dec 20 08:46:37 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

cc @tonistiigi @dnephin

**Comment by AkihiroSuda** [comment] 2017-12-20 09:04
Hmm, I once hit the issue with fresh `docker:17.12-rc-dind@sha256:548cc0286073e2fcc10c4612ab2ea1d818e776e27fe9874be80c5828d6d4871f` (docker/docker-ce@80c8033).

However, I can't reproduce the issue twice, even with `--no-cache`.

**Comment by AkihiroSuda** [comment] 2017-12-20 09:23
Note: I can hit this issue with `vfs` driver as well, so this is not overlay issue

**Comment by dnephin** [comment] 2017-12-20 16:17
Duplicate of #35641 ?

**Comment by AkihiroSuda** [comment] 2017-12-20 16:30
Yes, thx, closing this for avoiding side discussion

**Closed by AkihiroSuda** 2017-12-20 16:30 UTC
Labels: area/builder, kind/bug

**Comment by tonistiigi** [comment] 2017-12-20 18:37
@pearofducks Please see the workaround from https://github.com/docker/for-linux/issues/135#issuecomment-341864256 until this gets fixed.

**Comment by pearofducks** [comment] 2017-12-20 18:43
Will do, thanks!
