### ISSUE TITLE
docker pull  Downloading mirroring in addition to ctrl+D interrupts the download process, is there any other way (stop / resume) download?

### ISSUE THREAD

**Issue by Jack-qing** [moby/moby#38098] opened 2018-10-29 08:01 UTC
![99](https://user-images.githubusercontent.com/37032448/47636486-6ec6d500-db93-11e8-9a42-f0c89c8cba39.jpg)
I need help

**Comment by thaJeztah** [comment] 2018-10-29 17:35
I'm not sure I understand the question; could you describe what the problem is; what you saw, and what you expected?

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

**Comment by Jack-qing** [comment] 2018-10-30 01:47
Sorry, I thought Github was talking about Ping Ping. Thank you for your connection.

**Comment by thaJeztah** [comment] 2018-10-30 12:32
Let me close the issue here, but feel free to continue the conversation

**Closed by thaJeztah** 2018-10-30 12:32 UTC
Labels: area/distribution, kind/question, status/more-info-needed
