### ISSUE TITLE
inodes not freed after repeated builds - overlay

### ISSUE THREAD

**Issue by tallandtree** [moby/moby#37077] opened 2018-05-16 08:24 UTC
This seems to be a regression of #9755.
I'm seeing this issue on a Docker build server with docker 18.03.0-ce.

**Description**
The error we get during a build: "no space left on device". This is due to the number of inodes 100% in use.

**Steps to reproduce the issue:**
1. Build in Jenkins with jenkinsfile using docker agents 
2. Daily clean all unused images and containers
3. After a while all inodes are in use

**Describe the results you received:**
```
root@nldt-17836:/data/docker# df -i
Filesystem                           Inodes    IUsed   IFree IUse% Mounted on
udev                                4098065      504 4097561    1% /dev
tmpfs                               4103142      697 4102445    1% /run
/dev/mapper/ccv360--yoda2--vg-root 30736384 30484641  251743  100% /
tmpfs                               4103142        1 4103141    1% /dev/shm
tmpfs                               4103142        3 4103139    1% /run/lock
tmpfs                               4103142       16 4103126    1% /sys/fs/cgroup
/dev/sda2                            124928      309  124619    1% /boot
/dev/sda1                                 0        0       0     - /boot/efi
tmpfs                               4103142        4 4103138    1% /run/user/1001

```
I tried cleaning everything after stopping all containers:
```
$ docker container prune 
$ docker image prune --all
$ docker volume prune
```
There were still 64708689 files in /var/lib/docker/overlay. There are 6786 folders inside /var/lib/docker/overlay. A lot of those folders only contain 6 files. Some contain over 60000 files (a complete filesystem).
I need to:
```
# rm -fr /var/lib/docker 
```
And redeploy the environment again to solve the issue.

**Describe the results you expected:**
All files in /var/lib/docker/overlay would be have been removed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issues happens only on buildservers that use jenkinsfile and build on docker nodes

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:01 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:31 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.03.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-124-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3GiB
Name: nldt-17836.ccveu.local
ID: SOVT:HYKE:SNF4:E6QV:DYH3:C7YL:COGM:X54D:WAMK:2S3A:MCCU:5HUZ
Docker Root Dir: /data/docker/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 debops.ccv.architecture=Ubuntu 16.04
 debops.ccv.environment=production
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server, Ubuntu 16.04
We are using storage-driver: "overlay".
I will switch now to "overlay2" and see if this makes a difference, but it may take a while to find out..

**Comment by thaJeztah** [comment] 2018-05-16 08:51
> There were still 64708689 files in /var/lib/docker/overlay. There are 6786 folders inside 

- This is after all containers and images were removed? 
- Do the logs show any errors when removing containers or images (filesystem in use errors?)
- Do those files clean up when you restart the docker service?

> Build in Jenkins with jenkinsfile using docker agents

Just to be sure; you're not running docker-in-docker, and share the `/var/lib/docker` directory with docker-in-docker containers?


To exclude the possibility this was fixed already; can you upgrade to Docker CE 18.03.1, which is a patch release, and has various bug fixes?

Also: is there a reason you're using `overlay` instead of `overlay2`? Even under normal situations, overlay, [due to its implementation](https://docs.docker.com/storage/storagedriver/overlayfs-driver/#how-the-overlay-driver-works). The overlay2 storage driver shares all the benefits of the overlay storage driver, but without the inode exhaustion problem. In general, I would definitely recommend using overlay2 instead of overlay if your system supports it (which is the case on Ubuntu 16.04)

**Comment by tallandtree** [comment] 2018-05-16 09:11
Thanks for your fast reply.

Jenkins is able to run docker by installing the client executables and mounting /var/run/docker.sock into the jenkins container. We do not run "dind".

It was not intended to use overlay instead of overlay2, this is due to an ansible galaxy we are using to install docker. I will change it to overlay2 and upgrade docker to see if it makes any difference.

**Comment by thaJeztah** [comment] 2018-05-16 10:06
You're welcome! Keep us posted how that went

Still curious why those directories were left behind in your situation. There have been various issues (most of which _should_ be resolved now, but Linux mounts - especially if namespaces come to play - have a lot of gotchas) where containers could not be removed if the mount was in use by another process (which could be another container bind-mounting /var/lib/docker - cAdvisor being a known suspect); in such cases, the mounts won't be cleaned up until that process is stopped.

We _did_ change the behavior of docker to (in such cases) refuse to remove the actual container reference (the container would still be visible in a "removed" state), and be removed upon daemon restart.

**Comment by tallandtree** [comment] 2018-05-16 10:32
I will investigate what exactly is being done in the builds and how the containers are setup.

**Comment by tallandtree** [comment] 2018-05-18 09:56
After one day of running and removing (with -v) all stopped containers and doing a "docker image prune --all", I see a steady growth of /var/lib/docker/overlay2 on this one machine.
There are only 3 permanent containers running, but even though, the /var/lib/docker/overlay2 contains over 530 folders and a total of 1485505 files. Do you have any idea how I can search for the cause? 

There are a lot of images build on this machine. Some of the directories left over in the overlay2 contains linux filesystems that I can relate to one of the images being built. But all those images are pruned. These folders contain the following structure:

- diff
- link
- lower
- merged
- work

It is the merged folder that consumes most of the files.

**Comment by cpuguy83** [comment] 2018-05-18 13:06
Merged is the upper dir for overlay. Please make sure you are on at least Docker 17.12.1. 18.03.1 is the latest stable, but I think this should be fully resolved as of 17.12.1.

**Comment by cpuguy83** [comment] 2018-05-18 13:08
Sorry, it's not the upper dir, but rather the actual overlay which is just a mount.

**Comment by tallandtree** [comment] 2018-05-18 15:53
I'm running 18.03-1 (ce).

**Comment by cpuguy83** [comment] 2018-05-18 15:57
@tallandtree The "merged" directory is not actual data, it's only a mount (same with "work").

**Comment by tallandtree** [comment] 2018-05-24 14:38
I think we have found the cause.
Our dockerfile is:
```
FROM node:alpine AS build
WORKDIR /MY_APP/
RUN touch /MY_APP/vraag.html
FROM nginx:alpine as final
WORKDIR /app
#COPY --from=build /MY_APP/vraag.html ./
COPY --from=build /MY_APP/*.html ./
```
Our buildscript:
```
docker build -t my_app:12345 -f Dockerfile .
docker create --entrypoint="echo" --name=my_app_test my_app:12345
docker rm my_app_test
```
After running:
```
docker image prune -af
```
with the `COPY --from=build /MY_APP/*.html ./` the folders in /var/lib/docker/overlay2 are not removed. When we use COPY without a wildcard, the overlay2 folders are neatly removed.

If wildcards are not allowed in multistage COPY command, the documentation should be clear about that.

**Comment by tallandtree** [comment] 2018-05-30 09:47
@thaJeztah, can you confirm this is a bug?

**Comment by thaJeztah** [comment] 2018-05-30 11:36
Sorry for the wait; thanks for that information!

I can reproduce this issue; created a script to reproduce (note that it purges the `/var/lib/docker` directory, so use with care!);

```bash
#!/bin/sh
set -e

build_image_ok() {
	docker image build --quiet --no-cache -t my_app:$1 -<<-EOF 1> /dev/null
		FROM busybox AS build
		RUN touch /vraag.html
		FROM scratch
		COPY --from=build /vraag.html ./
	EOF

	docker image prune -af | tail -1

	printf "Directories in /var/lib/docker/overlay2: "
	find /var/lib/docker/overlay2 -maxdepth 1 -type d | wc -l
}

build_image_faulty() {
	docker image build --quiet --no-cache -t my_app:$1 -<<-EOF 1> /dev/null
		FROM busybox AS build
		RUN touch /vraag.html
		FROM scratch
		COPY --from=build /*.html ./
	EOF

	docker image prune -af | tail -1

	printf "Directories in /var/lib/docker/overlay2: "
	find /var/lib/docker/overlay2 -maxdepth 1 -type d | wc -l
}

cleanup() {
	systemctl stop docker
	rm -rf /var/lib/docker
	systemctl start docker
}

run_test() {
	cleanup
	echo "Running ok case:"
	i=1
	while [ $i -le 3 ]; do
		build_image_ok $i
		i=$(( i+1 ))
	done

	cleanup
	echo ""
	echo "Running faulty case:"
	i=1
	while [ $i -le 3 ]; do
		build_image_faulty $i
		i=$(( i+1 ))
	done
}

run_test
```

Running that script on Docker 18.03.1 on Ubuntu 16.04 shows;

```
Running ok case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2

Running faulty case:
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 5
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 7
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 9
```

I then tried to reproduce on older versions (using docker-in-docker); slightly modified script that doesn't remove `/var/lib/docker`, because we start a fresh container (and don't have systemd inside the container 😅).


```bash
#!/bin/sh
set -e

build_image_ok() {
	docker image build --quiet --no-cache -t my_app:$1 -<<-EOF 1> /dev/null
		FROM busybox AS build
		RUN touch /vraag.html
		FROM scratch
		COPY --from=build /vraag.html ./
	EOF

	docker image prune -af | tail -1

	printf "Directories in /var/lib/docker/overlay2: "
	find /var/lib/docker/overlay2 -maxdepth 1 -type d | wc -l
}

build_image_faulty() {
	docker image build --quiet --no-cache -t my_app:$1 -<<-EOF 1> /dev/null
		FROM busybox AS build
		RUN touch /vraag.html
		FROM scratch
		COPY --from=build /*.html ./
	EOF

	docker image prune -af | tail -1

	printf "Directories in /var/lib/docker/overlay2: "
	find /var/lib/docker/overlay2 -maxdepth 1 -type d | wc -l
}

run_test() {
	echo "Running ok case:"
	i=1
	while [ $i -le 3 ]; do
		build_image_ok $i
		i=$(( i+1 ))
	done

	echo ""
	echo "Running faulty case:"
	i=1
	while [ $i -le 3 ]; do
		build_image_faulty $i
		i=$(( i+1 ))
	done
}

run_test
```

( I left out the "OK test" output to keep it short)

### Docker 17.06 (OK)

```
docker run -d --name dind -v /var/lib/docker -v $(pwd):/tests --privileged docker:17.06-dind -s=overlay2 \
&& docker exec dind /tests/repro-37077.sh \
&& docker rm -f dind

Running faulty case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
```

### Docker 17.09 (OK)

```
docker run -d --name dind -v /var/lib/docker -v $(pwd):/tests --privileged docker:17.09-dind -s=overlay2 \
&& docker exec dind /tests/repro-37077.sh \
&& docker rm -f dind

Running faulty case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
```

### Docker 17.12 (OK)

```
docker run -d --name dind -v /var/lib/docker -v $(pwd):/tests --privileged docker:17.12-dind -s=overlay2 \
&& docker exec dind /tests/repro-37077.sh \
&& docker rm -f dind

Running faulty case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
```

### Docker 18.03 (KO)

```bash
docker run -d --name dind -v /var/lib/docker -v $(pwd):/tests --privileged docker:18.03-dind -s=overlay2 \
&& docker exec dind /tests/repro-37077.sh \
&& docker rm -f dind

Running faulty case:
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 5
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 7
```

Going back one version;

### Docker 18.02 (OK)

```bash
docker run -d --name dind -v /var/lib/docker -v $(pwd):/tests --privileged docker:18.02-dind -s=overlay2 \
&& docker exec dind /tests/repro-37077.sh \
&& docker rm -f dind

Running faulty case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
```


So looks like this was introduced somewhere between 18.02 and 18.03; narrowing down:


### Docker 18.03.0-rc1 (OK)

```
docker run -d --name dind -v /var/lib/docker -v $(pwd):/tests --privileged docker:18.03.0-ce-rc1-dind -s=overlay2 \
&& docker exec dind /tests/repro-37077.sh \
&& docker rm -f dind

Running faulty case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
```

### Docker 18.03.0-rc3 (KO)

```
docker run -d --name dind -v /var/lib/docker -v $(pwd):/tests --privileged docker:18.03.0-ce-rc3-dind -s=overlay2 \
&& docker exec dind /tests/repro-37077.sh \
&& docker rm -f dind

Running faulty case:
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 5
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 7
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 9
```

18.03.0-rc2 was never published as an image, but the problem seems to be somewhere between rc1 and rc3;

https://github.com/docker/docker-ce/compare/v18.03.0-ce-rc1...v18.03.0-ce-rc3

**Comment by thaJeztah** [comment] 2018-05-30 11:37
From those changes; this looks to be a strong candidate: https://github.com/docker/docker-ce/commit/6f6e5c5f2c9e5590cbf9e83e75f302ebb7541b6a#diff-6e6d19baa77a0206fbf1af5b001c025b (https://github.com/docker/docker-ce/pull/449); that one was cherry-picked from https://github.com/moby/moby/pull/36338

ping @tonistiigi PTAL

**Comment by thaJeztah** [comment] 2018-05-30 12:15
Testing on 18.03.0-rc2 (which has that commit)

```
git clone https://github.com/docker/docker-ce.git
cd docker-ce/components/engine

git checkout v18.03.0-ce-rc2
cd components/engine
make BIND_DIR=. binary shell

root@2ef401179d56:/go/src/github.com/docker/docker# make install
root@2ef401179d56:/go/src/github.com/docker/docker# dockerd --debug &> /var/log/dockerd.log &
root@2ef401179d56:/go/src/github.com/docker/docker# ./repro-37077.sh

Running ok case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2

Running faulty case:
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 5
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 7
Total reclaimed space: 0B
Directories in /var/lib/docker/overlay2: 9

exit
```

Reverting 6f6e5c5f2c9e5590cbf9e83e75f302ebb7541b6a and try again;


```
git revert 6f6e5c5f2c9e5590cbf9e83e75f302ebb7541b6a
make BIND_DIR=. binary shell

root@f2ae0696f8c7:/go/src/github.com/docker/docker# make install
root@f2ae0696f8c7:/go/src/github.com/docker/docker# dockerd --debug &> /var/log/dockerd.log &
root@f2ae0696f8c7:/go/src/github.com/docker/docker# ./repro-37077.sh

Running ok case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2

Running faulty case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
```

So looks confirmed that that is the commit that introduced this issue

- Daemon logs for 18.03.0-ce-rc2 [dockerd-18.03.0-rc2.log.txt](https://github.com/moby/moby/files/2053797/dockerd-18.03.0-rc2.log.txt)
- Daemon logs for with the commit reverted: [dockerd.log.txt](https://github.com/moby/moby/files/2053784/dockerd.log.txt)

**Closed** 2018-05-31 07:39 UTC
Labels: area/builder, area/storage/overlay, kind/bug, status/confirmed

**Comment by thaJeztah** [comment] 2018-05-31 09:43
Fixed in master through https://github.com/moby/moby/pull/37178
