### ISSUE TITLE
Devicemapper missing after upgrade to  5:18.09.0~3-0~ubuntu-bionic

### ISSUE THREAD

**Issue by Vierer** [moby/moby#38194] opened 2018-11-13 10:20 UTC
**Description**
Ubuntu 18.04, docker-ce with devicemapper
After upgrade of docker-ce (18.06.1 -> 18.09.0) using the docker apt repository, the service will not start.

**Steps to reproduce the issue:**
1. Install docker-ce 18.06.1 on Ubuntu 1804  using devicemapper:
    ExecStart=/usr/bin/dockerd --storage-driver=devicemapper --storage-opt dm.directlvm_device=/dev/sdb -H fd:// 
2. Upgrade to 18.09.0 vi apt-get update
    ExecStart=/usr/bin/dockerd --storage-driver=devicemapper --storage-opt dm.directlvm_device=/dev/sdb -H unix://
3. Restart docker service or reboot

**Describe the results you received:**
journalctl -u docker.service |grep error
level=error msg=“Failed to GetDriver graph” driver=devicemapper error=“graphdriver plugins are only supported with experimental mode” home-dir=/var/lib/docker
Error starting daemon: error initializing graphdriver: driver not supported

**Describe the results you expected:**
Working service.

**Additional information you deem important (e.g. issue happens only occasionally):**
For EE the combination Ubuntu/devicermapper is not supported but https://docs.docker.com/storage/storagedriver/device-mapper-driver/ mentions usability for CE.

Another machine using zfs shows this versions before/after same upgrade:

level=info msg=“Docker daemon” commit=e68fc7a graphdriver(s)=zfs version=18.06.1-ce
level=info msg=“Docker daemon” commit=4d60db4 graphdriver(s)=zfs version=18.09.0

Is the EE version packed in Ubuntu package docker-ce 5:18.09.0~3-0~ubuntu-bionic?-->

**Output of `docker version`:**
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Output of `docker info`:**
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM on KVM (Proxmox).

**Comment by thaJeztah** [comment] 2018-11-13 19:40
Thanks for reporting; this is a duplicate of https://github.com/docker/for-linux/issues/452, and is a packaging issue, so not something that has to be addressed in this repo.

I'll close the issue here, but you can subscribe to the other issue to stay informed on updates

**Closed by thaJeztah** 2018-11-13 19:40 UTC
