### ISSUE TITLE
Question: Deployment tasks

### ISSUE THREAD

**Issue by agalisteo** [moby/moby#35345] opened 2017-10-31 13:49 UTC
I need to run a command after a service is completely deployed in my docker swarm like:
* rake tasks (rake db:migrate)
* slack/mattermost notifications

Is it implemented? What is the best way to do?

**Comment by thaJeztah** [comment] 2017-10-31 13:53
You can add an entrypoint script to your image that performs these tasks the first time the container is started, e.g. see the entrypoint script for the official mysql image; https://github.com/docker-library/mysql/blob/86431f073b3d2f963d21e33cb8943f0bdcdf143d/8.0/docker-entrypoint.sh#L80-L200

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-31 13:53 UTC
Labels: area/swarm, kind/question

**Comment by agalisteo** [comment] 2017-11-01 17:10
if I have 6 replicas, using the entrypoint,  the script will execute in all containers, not just once
