### ISSUE TITLE
swarm service: automatic rollback does not work - "good" container gets killed, service down

### ISSUE THREAD

**Issue by nscheer** [moby/moby#37972] opened 2018-10-05 09:22 UTC
**Description**

When updating a service to a new image, an automatic rollback on health check failure does not seem to happen. Furthermore even the previous "good" container eventually gets killed, resulting in a complete service outage.

**Steps to reproduce the issue:**
1. Use the following two dockerfiles to create two images:
```
FROM alpine:3.8
RUN echo -e "#!/bin/sh\nexit 0" > /healthcheck.sh && chmod +x /healthcheck.sh
CMD sleep 10000
```

Build using ```docker build -t service:good .```

```
FROM alpine:3.8
RUN echo -e "#!/bin/sh\nexit 1" > /healthcheck.sh && chmod +x /healthcheck.sh
CMD sleep 10000
```
Build using ```docker build -t service:bad .```

2. Run service using this service.yml:

```
version: "3.7"
services:
  main:
    image: "service:good"
    #image: "service:bad"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first
```

using ```docker stack deploy --compose-file service.yml service```

3. Switch image to "bad" in yml file and run command again

**Describe the results you received:**

At first, everything seems to be alright. Swarm will start a container using the bad image. After the healthcheck fails, the container gets deleted. The service show this sequence as desired state "Running" and current state "Starting" followed by "Shutdown" and "Failed".
Afterwards another "bad" container pops up and after the failing health check, gets deleted again.

Now, the "good" container is flagged with a desired state of "Shutdown" and gets removed. The "bad" container keeps popping up.
Since the "good" container is gone, the service is gone as well.

**Describe the results you expected:**

Since the bad container can not be started, the service should rollback to the good container. Since I specified start first, the good container should be kept running - so basically a rollback would just be stopping to try to start the bad container.

**Additional information you deem important (e.g. issue happens only occasionally):**

The following gets written to the log during the process:

```
Oct 05 10:15:51 *********** dockerd[1007]: time="2018-10-05T10:15:51+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/490d183d7b64af4c59735d1a6c21fa4985128d4102fb3cf9946a8329541c73b3/shim.sock" debug=false pid=9845
Oct 05 10:16:54 *********** dockerd[1007]: time="2018-10-05T10:16:54+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/8bd91b99ee24516369cd047cfa3b854434d138dca5ccdda72251247003c02d0b/shim.sock" debug=false pid=12506
Oct 05 10:17:12 *********** dockerd[1007]: time="2018-10-05T10:17:12+02:00" level=info msg="shim reaped" id=8bd91b99ee24516369cd047cfa3b854434d138dca5ccdda72251247003c02d0b
Oct 05 10:17:12 *********** dockerd[1007]: time="2018-10-05T10:17:12.272186137+02:00" level=warning msg="deleteServiceInfoFromCluster NetworkDB DeleteEntry failed for 989042de6baaa4adea62a49e9caa9196653c67af83fcc408f5e33b578053333f bo9rg93u3v8qpa2smwabkjk3p err:cannot delete entry endpoint_table with network id bo9rg93u3v8qpa2smwabkjk3p and key 989042de6baaa4adea62a49e9caa9196653c67af83fcc408f5e33b578053333f does not exist or is already being deleted"
Oct 05 10:17:12 *********** dockerd[1007]: time="2018-10-05T10:17:12.272327061+02:00" level=warning msg="rmServiceBinding deleteServiceInfoFromCluster service_main 989042de6baaa4adea62a49e9caa9196653c67af83fcc408f5e33b578053333f aborted lb.backEnds[eid] && lb.disabled[eid] !ok"
Oct 05 10:17:12 *********** dockerd[1007]: time="2018-10-05T10:17:12.369714619+02:00" level=error msg="fatal task error" error="task: non-zero exit (137): dockerexec: unhealthy container" module=node/agent/taskmanager node.id=k6iqirser2p8jl9v6y7t16h0d service.id=0p3usia2z2xotjes46wm12wkf task.id=9zdbgtdaz31ju4tui0cpc5jlp
Oct 05 10:17:17 *********** dockerd[1007]: time="2018-10-05T10:17:17+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/7b5f30e590cd0ca6bf7cb118255fb60bb6cc25c3b9baf754a7dfb89b3aeb2f87/shim.sock" debug=false pid=13690
Oct 05 10:17:35 *********** dockerd[1007]: time="2018-10-05T10:17:35+02:00" level=info msg="shim reaped" id=7b5f30e590cd0ca6bf7cb118255fb60bb6cc25c3b9baf754a7dfb89b3aeb2f87
Oct 05 10:17:35 *********** dockerd[1007]: time="2018-10-05T10:17:35.740471474+02:00" level=warning msg="deleteServiceInfoFromCluster NetworkDB DeleteEntry failed for 8a5dee871d6af12cea14c53e381dffb5c2c3febb5fe4ce63b29302147854e526 bo9rg93u3v8qpa2smwabkjk3p err:cannot delete entry endpoint_table with network id bo9rg93u3v8qpa2smwabkjk3p and key 8a5dee871d6af12cea14c53e381dffb5c2c3febb5fe4ce63b29302147854e526 does not exist or is already being deleted"
Oct 05 10:17:35 *********** dockerd[1007]: time="2018-10-05T10:17:35.740628313+02:00" level=warning msg="rmServiceBinding deleteServiceInfoFromCluster service_main 8a5dee871d6af12cea14c53e381dffb5c2c3febb5fe4ce63b29302147854e526 aborted lb.backEnds[eid] && lb.disabled[eid] !ok"
Oct 05 10:17:35 *********** dockerd[1007]: time="2018-10-05T10:17:35.950530059+02:00" level=error msg="fatal task error" error="task: non-zero exit (137): dockerexec: unhealthy container" module=node/agent/taskmanager node.id=k6iqirser2p8jl9v6y7t16h0d service.id=0p3usia2z2xotjes46wm12wkf task.id=jceasl30q5b49dk0v0saqu98h
Oct 05 10:17:35 *********** dockerd[1007]: time="2018-10-05T10:17:35+02:00" level=info msg="shim reaped" id=490d183d7b64af4c59735d1a6c21fa4985128d4102fb3cf9946a8329541c73b3
Oct 05 10:17:35 *********** dockerd[1007]: time="2018-10-05T10:17:35.964951799+02:00" level=warning msg="rmServiceBinding a3f5650fd1a0a273dda1e875d782f0d2c931a3da7ce2bfe576d899fe1c90e826 possible transient state ok:false entries:0 set:false "
Oct 05 10:17:38 *********** dockerd[1007]: time="2018-10-05T10:17:38.703248712+02:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint bo9rg93u3v8qpa2smwabkjk3p cbe562581f71d7075e655d4a9695449b959023f12529c4f6a66679098563ca72], retrying...."
Oct 05 10:17:41 *********** dockerd[1007]: time="2018-10-05T10:17:41.179583219+02:00" level=error msg="02ed69fc8c84eb3739d1cd86b92f0a52e334e048d879f2568fccb9ff6f315c59 cleanup: failed to delete container from containerd: no such container"
Oct 05 10:17:42 *********** dockerd[1007]: time="2018-10-05T10:17:42+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/02ed69fc8c84eb3739d1cd86b92f0a52e334e048d879f2568fccb9ff6f315c59/shim.sock" debug=false pid=14818


Oct 05 10:18:00 *********** dockerd[1007]: time="2018-10-05T10:18:00+02:00" level=info msg="shim reaped" id=02ed69fc8c84eb3739d1cd86b92f0a52e334e048d879f2568fccb9ff6f315c59
Oct 05 10:18:00 *********** dockerd[1007]: time="2018-10-05T10:18:00.521656776+02:00" level=warning msg="deleteServiceInfoFromCluster NetworkDB DeleteEntry failed for 1eff3e86f35798730892924299fce9dfcb322837e14c75e67c5e0c22641a4a2b bo9rg93u3v8qpa2smwabkjk3p err:cannot delete entry endpoint_table with network id bo9rg93u3v8qpa2smwabkjk3p and key 1eff3e86f35798730892924299fce9dfcb322837e14c75e67c5e0c22641a4a2b does not exist or is already being deleted"
Oct 05 10:18:00 *********** dockerd[1007]: time="2018-10-05T10:18:00.521815223+02:00" level=warning msg="rmServiceBinding deleteServiceInfoFromCluster service_main 1eff3e86f35798730892924299fce9dfcb322837e14c75e67c5e0c22641a4a2b aborted c.serviceBindings[skey] !ok"

Oct 05 10:18:00 *********** dockerd[1007]: time="2018-10-05T10:18:00.738959086+02:00" level=error msg="fatal task error" error="task: non-zero exit (137): dockerexec: unhealthy container" module=node/agent/taskmanager node.id=k6iqirser2p8jl9v6y7t16h0d service.id=0p3usia2z2xotjes46wm12wkf task.id=zbox974k3md5aznrphdekvfwy
```

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: k6iqirser2p8jl9v6y7t16h0d
 Is Manager: true
 ClusterID: y2pwli8ucl9sw4frrgkidcnat
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: x.x.x.x
 Manager Addresses:
  x.x.x.x:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.7-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.901GiB
Name: ********
ID: ZCDN:F76R:ASTP:KMBN:Z66Y:XFCL:ZPYO:MILW:OGXN:3GNE:ZXAX:KT67
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using an elrepo kernel here, but the problem also is present when using the stock centos 7 kernel.

Hopefully I'm just too stupid to get the configuration right...

**Comment by scopev24** [comment] 2018-10-05 13:40
@thaJeztah Any ideas on this? I tried it again using a fresh install of docker 18.03.1-ce as well as 17.12.1-ce - same result (had to adjust the yml file of course).

There must be something fundamental I'm missing here :(

**Comment by scopev24** [comment] 2018-11-07 09:50
@thaJeztah Sorry to ping you again, but this is really serious to us.
I just tried 18.09.0-rc1 - the behavior is the same.

Keeping the service up when not being able to spawn a new healthy container is one of the most essential features of swarm - so there must be something wrong here (the way we use it, the way it is documented, or maybe a bug).
Either way, I'm really out of options here...

Thanks for your assistance!

**Comment by thaJeztah** [comment] 2018-11-07 13:18
@scopev24 interesting; I was actually trying your reproduction steps, and narrowing down the issue this morning; and here's what I found


Prepare images;

```bash
docker build -t service:good -<<EOF
FROM alpine:3.8
RUN echo -e "#!/bin/sh\nexit 0" > /healthcheck.sh && chmod +x /healthcheck.sh
CMD sleep 10000
EOF

docker build -t service:bad -<<EOF
FROM alpine:3.8
RUN echo -e "#!/bin/sh\nexit 1" > /healthcheck.sh && chmod +x /healthcheck.sh
CMD sleep 10000
EOF
```

docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:good"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first
EOF


docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:bad"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first
EOF


### Narrowing down the cause

I tried narrowing down what's causing this;

- tried deploying a "good" stack twice before deploying a "bad" stack (`service:good` -> `service:good2` -> `service:bad`), in case the first state was not considered a "previous" state (because it's also the _initial_ state). This did not make a difference
- remove `mode: global` - no change in behavior; the issue still reproduces
- remove `parallelism: 1` - no change in behavior; the issue still reproduces
- removing `delay: 5s` - rollback works, but some odd (presentation?) issues

So the problem looks to be around the deploy delay.

- tried reducing the delay (2s) - no change in behavior
- tried extending the delay (10s) - no change in behavior; the issue still reproduces

Only _removing_ the delay seems to resolve the issue.

## Simplifying the stack steps


Removing the settings that are not needed to reproduce the issue;

Start with a clean slate;

```bash
docker stack rm rollie
```


Deploy

```bash
docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:good"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
EOF
```

Wait for it to be converged (check `docker service ls` to reach `1/1` tasks), then update with bad image

```bash
docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:bad"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
EOF
````

Check the output of `docker service ps rollie_main`;

```bash
docker service ps rollie_main
ID                  NAME                IMAGE               NODE                    DESIRED STATE       CURRENT STATE             ERROR               PORTS
3k2mpi5segf7        rollie_main.1       service:bad         linuxkit-025000000001   Running             Starting 18 seconds ago                       
ikqjlah7d3wm         \_ rollie_main.1   service:good        linuxkit-025000000001   Shutdown            Shutdown 19 seconds ago                       
```

Wait for the service to fail, and observe that upon rollback, the `bad` configuration is used, instead of the previous configuration:

```
ID                  NAME                IMAGE               NODE                    DESIRED STATE       CURRENT STATE                      ERROR                              PORTS
zmatdkwm179i        rollie_main.1       service:bad         linuxkit-025000000001   Ready               Preparing less than a second ago                                      
3k2mpi5segf7         \_ rollie_main.1   service:bad         linuxkit-025000000001   Shutdown            Failed less than a second ago      "task: non-zero exit (137): do…"   
ikqjlah7d3wm         \_ rollie_main.1   service:good        linuxkit-025000000001   Shutdown            Shutdown 20 seconds ago                                            
```


### When no `delay` is specified (resolves issue, but incorrect "desired state")

This gives an interesting result;

Start with a clean slate;

```bash
docker stack rm rollie
```


Deploy

```bash
docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:good"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
EOF
```

Wait for it to be converged (check `docker service ls` to reach `1/1` tasks), then update with bad image

```bash
docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:bad"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
EOF
````

Possibly this is a presentation issue only, but the service fails; rolls back, but `docker service ps rollie_main` shows the desired state to be `Shutdown`;

Check the output of `docker service ps rollie_main`; here, the bad service is still starting;

```bash
ID                  NAME                IMAGE               NODE                    DESIRED STATE       CURRENT STATE             ERROR               PORTS
hb98v6c0zcns        rollie_main.1       service:bad         linuxkit-025000000001   Running             Starting 14 seconds ago                       
up1dc0et8x7g         \_ rollie_main.1   service:good        linuxkit-025000000001   Running             Running 25 seconds ago                        
```

Wait for the bad service to fail, and a rollback to be triggered. Note the `DESIRED STATE` column;

```bash
ID                  NAME                IMAGE               NODE                    DESIRED STATE       CURRENT STATE            ERROR                              PORTS
a9z8k1dt1pru        rollie_main.1       service:good        linuxkit-025000000001   Shutdown            Accepted 1 second ago                                       
hb98v6c0zcns         \_ rollie_main.1   service:bad         linuxkit-025000000001   Shutdown            Failed 1 second ago      "task: non-zero exit (137): do…"   
up1dc0et8x7g         \_ rollie_main.1   service:good        linuxkit-025000000001   Running             Running 31 seconds ago                                      
```

Deploying the service continues, but shows both `DESIRED STATE` as well as `CURRENT STATE` as `shutdown`;

```
ID                  NAME                IMAGE               NODE                    DESIRED STATE       CURRENT STATE             ERROR                              PORTS
a9z8k1dt1pru        rollie_main.1       service:good        linuxkit-025000000001   Shutdown            Shutdown 21 seconds ago                                      
hb98v6c0zcns         \_ rollie_main.1   service:bad         linuxkit-025000000001   Shutdown            Failed 23 seconds ago     "task: non-zero exit (137): do…"   
up1dc0et8x7g         \_ rollie_main.1   service:good        linuxkit-025000000001   Running             Running 53 seconds ago                                       
```


_However_ the actual state of the container is `running`;

```
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                        PORTS               NAMES
3aa9e62682ba        service:good        "/bin/sh -c 'sleep 1…"   About a minute ago   Up About a minute (healthy)                       rollie_main.1.up1dc0et8x7gaoa9lrj5gb82u
```

And `docker service ls` also shows the service state to be converged;

```
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
ozsgk8133leb        rollie_main         replicated          1/1                 service:good        
```

**Comment by thaJeztah** [comment] 2018-11-07 13:19
ping @dperny @anshulpundir @aaronlehmann ptal

**Comment by scopev24** [comment] 2018-11-07 14:46
Hi @thaJeztah !

It seems you actually forgot to remove the "delay: 5s" from your second pair of stack deploy commands.

I can confirm, that omitting the delay parameter results in the rollback being applied correctly.

On my test system (currently running docker-ce 18.09.0-rc1) the "display glitch" does not show up:

```
[nscheer@zbox docker_service_test]$ docker service ps rollie_main
ID                  NAME                IMAGE               NODE                  DESIRED STATE       CURRENT STATE                 ERROR                              PORTS
vlrybv5ntqgs        rollie_main.1       service:good        zbox.home.scheer.it   Running             Running 35 seconds ago
vblsb3ax80r7         \_ rollie_main.1   service:bad         zbox.home.scheer.it   Shutdown            Shutdown 41 seconds ago
3lnziwrfrt7d         \_ rollie_main.1   service:bad         zbox.home.scheer.it   Shutdown            Failed 43 seconds ago         "task: non-zero exit (137): do…"
ohsta0184q59         \_ rollie_main.1   service:good        zbox.home.scheer.it   Shutdown            Shutdown about a minute ago
```

Did you try adding the monitor setting? For me either one works, omitting delay or adding monitor.

So this one works as well:

```
docker stack rm rollie
```

Deploy
```
docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:good"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      update_config:
        delay: 5s
        monitor: 15s
        failure_action: rollback
EOF
```

Update to bad:

```
docker stack deploy -c- rollie <<-'EOF'
version: "3.7"
services:
  main:
    image: "service:bad"
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      start_period: 0s
      interval: 5s
      retries: 1
      timeout: 5s
    deploy:
      update_config:
        delay: 5s
        monitor: 15s
        failure_action: rollback
EOF
```

So delay and monitor somehow interact here. If both are omitted, the default of 0 seconds applies, and this somehow seems to work out (i.e. don't wait, don't monitor, just rollback).

I always thought that monitor would mean: "Even if the health check is good, continue to monitor the service, and if its health check fails during monitor time, even after a successful update, rollback as well".
But a value of 0 obviously means: "Don't watch and care about the update process at all". Which is a dangerous default...

Just made another test: If I re-add the "order: start-first" parameter, the display seems wrong:

```
[nscheer@zbox docker_service_test]$ docker service ps rollie_main
ID                  NAME                IMAGE               NODE                  DESIRED STATE       CURRENT STATE            ERROR                              PORTS
iji9k60hxl6h        rollie_main.1       service:bad         zbox.home.scheer.it   Shutdown            Shutdown 7 seconds ago
iaegyx25y18g         \_ rollie_main.1   service:bad         zbox.home.scheer.it   Shutdown            Failed 14 seconds ago    "task: non-zero exit (137): do…"
l6m4ye3bpqee         \_ rollie_main.1   service:good        zbox.home.scheer.it   Running             Running 45 seconds ago
```

I don't know, if this is expected, since the good container was never killed due to the start-first order.
But since it has converged, the first line should read "running" for desired state and current state.

**Comment by mhemrg** [comment] 2020-02-03 18:06
ping @dperny @thaJeztah ptal

**Comment by RodrigoPetter** [comment] 2020-06-16 22:32
This problem persists in version 19.03.11. Without the delay the service rolled back, but some things still seem wrong.

The `docker inspect serviceName` command reports that the update was sucessfull:

```
"UpdateStatus": {
            "State": "completed",
            "StartedAt": "2020-06-16T21:53:01.741992576Z",
            "CompletedAt": "2020-06-16T21:53:52.512924291Z",
            "Message": "update completed"
        }
```

If you use the command `docker service update --image service:bad serviceName` instead of `stack deploy` everything works as expected. Even if you add the `--update-delay` equivalent of the config from the docker-compose. And the service inspect reports the rollback as expected:

```
"UpdateStatus": {
            "State": "rollback_completed",
            "StartedAt": "2020-06-16T22:09:21.495118965Z",
            "CompletedAt": "2020-06-16T22:09:37.284428663Z",
            "Message": "rollback completed"
        }
```

I always assumed that under the hood `stack deploy` used the command `service update`, but that does not seem to be the case.

@thaJeztah can you please give any update about this? 

If there is no prediction for a fix I would like to migrate my CI/CD pipeline from `stack deploy` to `service create/update`, because today deploys are being marked as successful, when in fact they failed.

**Comment by RodrigoPetter** [comment] 2020-09-14 21:14
I was trying to track down this problem, but hit a dead end.

At the end of the call stack, is the Swarmkit the responsible for processing the commands `service update` and `stack deploy` where this behavior can be seen.

If you take a look at this line [updater.go#L352](https://github.com/docker/swarmkit/blob/d6592ddefd8a5319aadff74c558b816b1a0b2590/manager/orchestrator/update/updater.go#L352), there is nothing special that is done when setting a delay.

There is even a test file where the settings are the same as those used to reproduce this bug: https://github.com/docker/swarmkit/blob/d6592ddefd8a5319aadff74c558b816b1a0b2590/manager/orchestrator/replicated/update_test.go#L142. But the test passes. 

In this [other test suite](https://github.com/docker/swarmkit/blob/d6592ddefd8a5319aadff74c558b816b1a0b2590/manager/orchestrator/update/updater_test.go#L365) the "pause" and "continue" `FailureAction` are tested, but the "rollback" is not covered. I modified the test to include the rollback action, but the test continued to pass. Even with the delay time, the service returned to its previous state after the failure.

**Comment by rleap-m** [comment] 2021-03-05 19:47
Thank you for the commentary @thaJeztah - removing the delay helped me get past the issue as well.

Something I noticed when working through this issue - if I have multiple replicas (targeting a single node - haven't tried multi-node scenario) defined in the stack rollback works as expected on a bad service update (I used `docker service update --image`  and referenced a bad image tag to force a rollback situation) 

It's only when I have a single replica that the rollback fails.  And this makes some intuitive sense (not that it is desired behavior) because `delay` is the wait period that docker should observe between updating tasks in a service - but when there is only a single task to update, the delay is meaningless - and so perhaps that's why we see odd/undesirable behavior in the single replica case.

**Comment by awmirantis** [comment] 2021-05-13 23:48
Looking at this line of code https://github.com/docker/swarmkit/blob/5a5494a9a7b408b790533a5e4e1cb43ca1c32aad/manager/orchestrator/update/updater.go#L232 the check time.Since(startedAt) <= monitoringPeriod will always be false when Delay > MonitoringPeriod so the failed task is ignored.  The slotsLoop on L260 is completed before the task fails.  With more than 1 replica the slotsloop failedTaskWatch is hit.  If you increase parallelism to be equal to replica count the roll back is not done either because the slot loop completes before the tasks are started/errored.

**Closed** 2021-06-11 02:45 UTC
Labels: area/builder
