### ISSUE TITLE
docker kill weaveproxy hangs indefinitely

### ISSUE THREAD

**Issue by marccarre** [moby/moby#31447] opened 2017-03-01 12:19 UTC
**Description**

`docker kill weaveproxy` hangs indefinitely.

**Steps to reproduce the issue:**
1. Get a machine with Ubuntu 16.04 LTS and Docker 1.13.1, e.g. running:

        $ git clone https://github.com/weaveworks/weave.git
        $ cd weave
        $ git checkout docker-1.13.1
        $ vagrant up
        $ vagrant ssh

2. Install Weave Net:

        $ sudo -s
        # curl -L git.io/weave -o /usr/local/bin/weave
        # chmod a+x /usr/local/bin/weave
        # weave version
        weave script 1.9.1
        [...]
        weave proxy  1.9.1
        [...]

3. Start the Weave Net proxy:

        # weave launch-proxy
        [...]
        87e922f524073f268e450669ca76771616a80bfe3d16831903f7729116583d1f

4. Try to kill it. Docker hangs indefinitely.

        # docker ps
        CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
        87e922f52407        weaveworks/weaveexec:1.9.1   "/home/weave/weavepro"   3 seconds ago       Up 3 seconds                            weaveproxy
        # docker kill weaveproxy

    This last command never returns.

**Describe the results you received:**

Docker hangs indefinitely.

    # docker ps
    CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
    87e922f52407        weaveworks/weaveexec:1.9.1   "/home/weave/weavepro"   3 seconds ago       Up 3 seconds                            weaveproxy
    # docker kill weaveproxy

This last command never returns.
Following a `ctrl+c` and another `docker ps`, we can see that the uptime under `STATUS` has been reset:

    ^C
    # docker ps
    CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
    87e922f52407        weaveworks/weaveexec:1.9.1   "/home/weave/weave..."   5 seconds ago       Up 1 second                             weaveproxy

Note that this behaviour happens consistently.

**Describe the results you expected:**

`docker kill` should return and the `weaveproxy` container should disappear:

    # docker ps
    CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
    9cc6b5c28912        weaveworks/weaveexec:1.9.1   "/home/weave/weavepro"   3 seconds ago       Up 3 seconds                            weaveproxy
    # docker kill weaveproxy
    weaveproxy
    # docker ps
    CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES

If you repeat the same steps against Docker 1.11.2, this is what you will observe.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-51-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: vagrant
ID: 3IMF:IWUK:V6HP:O7ES:3H6M:UTOP:NCKX:XJ33:MLLP:XBVZ:KPDA:ULLX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox / Vagrant.

However, the same also happens under Google Cloud Platform.
Machine type: n1-standard-1 (1 vCPU, 3.75 GB memory)
CPU platform: Intel Sandy Bridge

```
# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
# docker info
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 22
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613 GiB
Name: mct-0
ID: KN3B:QQLS:ITVP:QP3T:4Z7L:RAR4:X46C:R5QQ:W64S:GLXC:TWZ5:UGMZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 weave-ci-registry:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cpuguy83** [comment] 2017-03-01 14:44
Can you send `SIGUSR1` to the daemon that is hanging like this and collect the stack trace from the logs?

**Comment by marccarre** [comment] 2017-03-01 16:14
@cpuguy83, many thanks for your reply.
Here is what I believe you asked for:

- [journalctl -r -u docker.service](https://gist.github.com/marccarre/28228483d1e2dfce402a8ea7b79d5e24)
- [daemon-data-2017-03-01T160238Z.log](https://gist.github.com/marccarre/2783b661ff6eb6b934e7116cf7168567)
- [goroutine-stacks-2017-03-01T160238Z.log](https://gist.github.com/marccarre/9811f44524a39088cdfd646c4263fe82)

which I generated using:
```
# weave launch-proxy
# docker kill weaveproxy
# kill -SIGUSR1 $(ps aux | grep dockerd | grep -v grep | awk '{ print $2 }')
# journalctl -r -u docker.service
```

**Comment by cpuguy83** [comment] 2017-04-05 21:03
ping @mlaventure 

I see this it stuck waiting on the container to stop, but do not see what exactly it's waiting on.

**Comment by mlaventure** [comment] 2017-04-24 20:29
I unfortunately don't seem to be able to get vagrant up and running to try and reproduce this.

Could you please re-run your test with the daemon in debug mode and send a SIGUSR1 to both `dockerd`and `docker-containerd` to gather some stracktrace once the hang occurs?

Thanks

**Comment by thaJeztah** [comment] 2017-06-10 14:58
ping @marccarre ^^

**Comment by marccarre** [comment] 2017-06-12 09:55
@mlaventure, @thaJeztah, apologies for missing the earlier comment from April.
Here are the exact steps to reproduce the issue, as well as the logs I gathered in the process:

Essentially following [these steps](https://docs.docker.com/engine/installation/linux/ubuntu/) under Vagrant:

```
host$ vagrant init bento/ubuntu-16.04
host$ vagrant up
host$ vagrant ssh
$ sudo -s
# apt update
# apt install -yq apt-transport-https ca-certificates curl software-properties-common
# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
# apt-key fingerprint 0EBFCD88
# add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
# apt update
# apt install docker-ce
# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

# echo '{"debug": true}' > /etc/docker/daemon.json
# docker info | grep -i debug
Debug Mode (client): false
Debug Mode (server): false
# kill -SIGHUP $(ps aux | grep dockerd | grep -v grep | awk '{ print $2 }')
# docker info | grep -i debug
Debug Mode (client): false
Debug Mode (server): true

# curl -L git.io/weave -o /usr/local/bin/weave
# chmod a+x /usr/local/bin/weave
# weave version
weave script 1.9.7
[...]
weave proxy  1.9.7
[...]
# weave launch-proxy
# docker kill weaveproxy
### Command hangs

### From some other SSH session / terminal:
# kill -SIGUSR1 $(ps aux | grep dockerd | grep -v grep | awk '{ print $2 }')
# kill -SIGUSR1 $(ps aux | grep "docker-containerd " | grep -v grep | awk '{ print $2 }')
# journalctl -r -u docker.service
```
Logs:
- [`journalctl -r -u docker.service`](https://gist.github.com/marccarre/5c5b11887c6c5002146d08895cc5a8de)
- [`/var/run/docker/goroutine-stacks-2017-06-12T093928Z.log`](https://gist.github.com/marccarre/9e64ebadf7cbda106efad2d1214458bb)
- [`/var/run/docker/daemon-data-2017-06-12T093928Z.log`](https://gist.github.com/marccarre/944b55fb8835a2985ea53234ac634985)

**Comment by thaJeztah** [comment] 2017-06-12 15:13
Thank you @marccarre 

@mlaventure 😇

**Comment by mlaventure** [comment] 2017-06-13 18:08
Thanks for the detailed steps, allowed me to reproduce it consistently.

The issue come from the fact that the container has a restart policy sets to `always` and it happens that by the time `daemon.Kill()` calls `container.waitStop()` to wait for the container to be in the `Stopped` state, the container has already restarted and is thus in the `Running` state.

Somehow the race doesn't show in the code with the changes made recently by moby/moby#32237 (which is included in 17.06).

But I can see that's there's still a possible race there. I'll try to come up with a PR to fix it.

**Comment by mlaventure** [comment] 2017-06-13 18:28
actually, killing the container should prevent it from restarting all-together. I suppose the `ExitOnNext()` wasn't taken in account due to a bug.

I am trying to find in which PR this was fixed so I can link it here before closing this issue.

**Comment by thaJeztah** [comment] 2017-06-13 18:30
@mlaventure this one? https://github.com/moby/moby/pull/33335

**Comment by mlaventure** [comment] 2017-06-13 18:32
@thaJeztah Yes, you beat me to it! :)

**Comment by mlaventure** [comment] 2017-06-13 18:34
closing via #33335

**Closed by mlaventure** 2017-06-13 18:34 UTC
Labels: area/runtime, kind/bug, version/1.13
