### ISSUE TITLE
growing reported docker container virtual memory size with java processes

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [moby/moby#15020] opened 2015-07-27 03:23 UTC
1) in various multiple different containers running java, `top/htop` tools report VIRT (virtual) memory 
as order of magnitude greater then the physical memory of RES (resident) process memory

2) processes seem to run fine for several days (did not test longer), while VIRT keeps going up and RES stays fixed (as configured by java startup parameters setting process memory limits)

3) each GC (garbage collection) request to the JVM increases reported VIRT value

4) java 8 GC type is "G1"

5) same applications with same o/s, same settings, etc - do no exhibit such behavior when run on the host

example: total physical ram 16G, java process resident ram 1.6G, reported virtual size 80G and growing

**top/htop report:**

![image](https://cloud.githubusercontent.com/assets/1622151/8897868/e39891c8-33e1-11e5-99d9-1aace8870ea0.png)

**docker stats report:** for the same procesess
![image](https://cloud.githubusercontent.com/assets/1622151/8897876/11df0a26-33e2-11e5-9102-c1d72e3b28a3.png)

```
uname -a
Linux wks002 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

```
docker info
Containers: 3
Images: 248
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 254
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-58-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.62 GiB
Name: wks002
ID: 65Y6:OAEC:KGES:X3NV:LMEH:CL5X:6XLV:WKZ3:52CB:I6AJ:J4Y4:HLM3
WARNING: No swap limit support
```

```
docker --version
Docker version 1.7.1, build 786b29d
```

series of images:
https://registry.hub.docker.com/u/carrotgarden/zinc/dockerfile/
https://registry.hub.docker.com/u/carrotgarden/java-service/dockerfile/
https://registry.hub.docker.com/u/carrotgarden/java-build/dockerfile/
https://registry.hub.docker.com/u/carrotgarden/java-8/dockerfile/
https://registry.hub.docker.com/u/carrotgarden/ubuntu/dockerfile/

typical container invocation command:

```
# container
NAME=$(basename $DIR)

# docker image
IMAGE="carrotgarden/$NAME"

docker run \
    --rm \
    --net=host \
    --pid=host \
    --env HOME \
    --env DISPLAY \
    --env TERM=xterm \
    --env NO_AT_BRIDGE=1 \
    --user $USER \
    --device=/dev/dri \
    --device=/dev/snd \
    --device=/dev/video0 \
    --volume=/etc/group:/etc/group:ro \
    --volume=/etc/passwd:/etc/passwd:ro \
    --volume=/home:/home \
    --volume=/tmp:/tmp \
    --name=$NAME \
    $IMAGE &
```

typical java execution parameters:
https://registry.hub.docker.com/u/carrotgarden/zinc/dockerfile/

```
ENV ZINC_COMMAND=" \
    java \
    -server \
    -XX:+UseG1GC \
    -XX:+DoEscapeAnalysis \
    -XX:+UseCompressedOops \
    -XX:+UseCompressedClassPointers \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:InitialHeapSize=$JAVA_HEAP \
    -XX:MaxHeapSize=$JAVA_HEAP \
    -XX:ThreadStackSize=$JAVA_STACK \
    -XX:MetaspaceSize=$JAVA_META \
    -XX:MaxMetaspaceSize=$JAVA_META \
    -XX:InitialCodeCacheSize=$JAVA_CODE \
    -XX:ReservedCodeCacheSize=$JAVA_CODE \
    -Dzinc.home=$ZINC_FOLDER \
    -classpath $ZINC_FOLDER/lib/*:. \
    com.typesafe.zinc.Nailgun \
    $ZINC_PORT $ZINC_TIMEOUT \
"
```

**Comment by joerg84** [comment] 2015-08-15 17:51
I could reproduce something similar by starting a lot of simple container
Virtual mem goes up to around 30GB, and doesn't go down even after 'docker kill' and 'docker rm'.

Script
    seq 1 1000 | xargs -iX -n1 -P 1000 docker run --net=host -d thomasr/sleep sleep 10000

    ubuntu@ip-172-31-14-77:~$ sudo docker info
    Containers: 0
    Images: 5
    Storage Driver: overlay
    Backing Filesystem: extfs
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.19.0-25-generic
   Operating System: Ubuntu 15.04
    CPUs: 1
   Total Memory: 3.66 GiB
   Name: ip-172-31-14-77
   ID: MQJQ:VLAC:BMZ7:ULF4:3WSF:U2TL:ENEN:HHZ6:GN3E:JCO5:DIAR:XIR4
   WARNING: No swap limit support

**Comment by dudehook** [comment] 2015-09-09 22:07
Seeing something similar.  I'm running a simple Scala (JVM) application which loads a lot of data into and out of memory.  I set the JVM to 8G heap (-Xmx8G).  I have a machine with 132G memory, and it can't handle more than 7-8 containers because they grow well past the 8G limit I imposed on the JVM.

docker stat shows that each container itself is using much more memory than the JVM is supposed to be using.  For instance:

CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
dave-1              3.55%               10.61 GB/135.3 GB   7.85%               7.132 MB/959.9 MB
perf-1              3.63%               16.51 GB/135.3 GB   12.21%              30.71 MB/5.115 GB

It almost seems that the JVM is asking the OS for memory, which is allocated within the container, and the JVM is freeing memory as its GC runs, but the container doesn't release the memory back to the main OS.  So... memory leak.

**Comment by kixiro** [comment] 2015-10-22 09:02
![htop_t](https://cloud.githubusercontent.com/assets/4424195/10661035/284c0310-78b4-11e5-8e90-6c229fd3dac6.png)

<pre>
# docker --version
Docker version 1.6.2, build 7c8fca2
</pre>

<pre>
# docker info
Containers: 13
Images: 164
Storage Driver: devicemapper
 Pool Name: docker-254:1-5554455-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.44 GB
 Data Space Total: 107.4 GB
 Data Space Available: 17.7 GB
 Metadata Space Used: 9.343 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 7.817 GiB
Name: stress
ID: QGL6:M4OM:F4GF:LPTC:X5Q2:GHUO:76TV:HDOS:IZZO:BFSW:47Z5:36DH
</pre>

<pre>
# htop --version
htop 1.0.3 - (C) 2004-2012 Hisham Muhammad
Released under the GNU GPL.
</pre>

<pre>
# free
             total       used       free     shared    buffers     cached
Mem:       8197204    7527808     669396       3588     363656    2642860
-/+ buffers/cache:    4521292    3675912
Swap:      4290556      18676    4271880
</pre>

**Comment by stevenschlansker** [comment] 2015-10-23 21:41
Us too.  What ran in 1.7.1 just fine will eventually trigger an OOM situation in 1.8.3
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Containers: 20
Images: 253
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 29.45 GiB
Name: mesos-slave5-prod-euwest1
ID: AFFX:JFYM:FH3D:FJYN:RQLH:KBZB:PPIC:BYYL:JC44:ENYJ:VPPS:73JK
```

**Comment by lnowak** [comment] 2016-01-29 09:23
I am seeing the same problem. I have moved from 1.6.2 to 1.9.1 and observing. Hope it helps.

Containers: 2
Images: 151
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 155
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 999 MiB
Name: ip-10-0-1-10
ID: EOJA:5WDB:TANH:M5R2:WPSM:66SA:C7XP:2GOX:2LWZ:7GQE:QM6O:NX4L
WARNING: No memory limit support
WARNING: No swap limit support

**Comment by mjaverto** [comment] 2016-01-29 14:41
I can also confirm this on Docker version 1.9.1, build a34a1d5/1.9.1

Using [JVMTop](https://github.com/patric-r/jvmtop) inside the container shows the reasonable / expected heap size for us, yet just plain top shows almost 3x as much:

![Image of JVMtop and top](https://s3.amazonaws.com/uploads.hipchat.com/59732/410273/m6C4KkQ0VPQpBVx/memory-issue.jpg)

Definitely appears to be a problem with longer running containers.

**Comment by leafknode** [comment] 2016-02-10 18:53
Would be nice to get an official response on this; I'm experiencing the same issues as all of you.  Docker 1.10 just came out, I will give that whirl to see if that addresses anything.

**Comment by dgaviola** [comment] 2016-02-10 19:24
We are having the same issue with Docker 1.6.2 and JDK 1.8.0_72.

**Comment by khuongquixey** [comment] 2016-03-09 23:58
+1 Would love to see this addressed.

We're seeing this as well. Our fix is resorting to daily reboots for our containers (Docker 1.10).

**Comment by thaJeztah** [comment] 2016-03-12 18:12
@unclejack any ideas?

**Comment by rafamonteiro** [comment] 2016-03-31 02:56
I can confirm having the some similar problem. If the container isn't restarted, it end up consuming all the machine RAM. 
The application stack consist of : 
- Amazon EC2 instance c3.4xlarge
- Oracle JVM 1.7.0_80
- CoreOS stable (899.13.0)
- Docker 1.9.1

The following is the TOP output with the container running for 24 hours approx. 
![screen shot 2016-03-30 at 11 38 04 pm](https://cloud.githubusercontent.com/assets/11823470/14164046/435f6d8a-f6d2-11e5-962a-eae336093989.png)

Immediately after using JMX to force a FULL GC in the JVM
![screen shot 2016-03-30 at 11 50 45 pm](https://cloud.githubusercontent.com/assets/11823470/14164047/4362318c-f6d2-11e5-8edc-0930631bc74a.png)

**Comment by leafknode** [comment] 2016-04-19 18:01
Really annoying that this issue has been around for so long without any official reply or acknowledgement from the devs.

**Comment by cpuguy83** [comment] 2016-04-19 18:48
It would be interesting to see the output of [pmap](http://linux.die.net/man/1/pmap)
Also a quick search on java virt mem usage brings me to tweaking `MALLOC_ARENA_MAX`, seems to be an issue with glibc >= 2.1

This is not likely to be a Docker issue but rather a misconfiguration, perhaps even something set up in "normal" environments (like in an init script) that is missing in the container.

**Comment by Jimexist** [comment] 2016-05-06 07:17
We hit the same issue using `java:jre-alpine` while setting
```sh
# omitted
java \
    -server \
    -Xms128m \
    -Xmx4096m \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+UseG1GC \
# omitted
```

and the gc details are:
[gc.txt](https://github.com/docker/docker/files/251683/gc.txt)

**Comment by cfontes** [comment] 2016-05-24 20:00
Experiencing the same issue, but on production.

Machines with 32G of ram are reporting 98% usage but my 12 containers should be using only 16Gb from the JVM allocation.

Any updates on this?

**Comment by allen13** [comment] 2016-06-09 14:33
I tried running cassandra for hawkular metrics collection on a huge 128GB baremetal using kubernetes. I spent quite a bit of time tweaking the JVM to no avail. Cassandra would quickly consume a lot of memory  then crash, sometimes within hours. I am also running Jenkins as well. It doesn't get any use but the jvm still goes memory crazy and eats everything until it crashes. It really looks like java is having problems across the board when run in a container environment.

**Comment by jmkgreen** [comment] 2016-06-10 16:43
Curious: `top` shows this memory ballooning, `csysdig` does not...

**Comment by allen13** [comment] 2016-06-13 15:35
The MALLOC_ARENA_MAX=4 seems to be working for me. Is there anyway we can get this fixed at a higher level so future developers don't fall into the same rabbit hole?

**Comment by jmkgreen** [comment] 2016-06-14 13:34
I suggest this is at least documented. Coding something to avoid the issue may fox anyone not expecting this instruction to be provided.

**Comment by aba182** [comment] 2016-06-28 00:14
Why is 4 the suggested MALLOC_ARENA_MAX value? The default for 64 bit machines is 8 * #cores. For machines I am working against they would have a default MALLOC_ARENA_MAX of 384(assuming that by cores it is counting total threads. Even if not it would be 192 arena's). 4 is a very drastic leap from either of these numbers and on reading it sounds that more pools allows for improved memory allocation for thread heavy processes. 

Has anyone trying other values yet? I will be attempting on some machines on my end but curious if others have already experimented.

**Comment by johanhaleby** [comment] 2016-06-30 15:37
Do you specify the MALLOC_ARENA_MAX environment variable in the container or at the docket host? If so do you need to restart the containers/servers afterwards for the change to take effect? 

I've tried setting it in the container without any luck.

**Comment by sunnysinghgithub** [comment] 2016-07-21 01:42
We are also facing a similar issue. I have set the max heap size to 512M and then docker container memory limit to 512-200 = 312M, just to give a buffer. But, even then, the container crashes when the docker memory hits the limit after some time. I also looked at the jvm metrics and found that the heap used never grew beyond 120M. So, in this case, when looking at the docket stats, docker mem started from 312M and then kept growing until it hit the max 512M.

**Comment by andjarnic** [comment] 2016-09-08 16:37
Could use a reply that explains how to use the MALLOC_ARENA_MAX=4 option. I just tried it, with using .bashrc on my docker host, exporting it, confirmed it is exported, and it still did not work for me. I start a JVM in docker that just sits idle and it crashes. I have a 1G Digital Ocean Droplet, and set the JVM to 768M max, I know its running up against memory, but when started it is only using 168MB of memory. I came back a couple hours later and it was crashed due to OOM. No requests made to my service, etc.

So any help on exactly how/where we put the export MALLOC.. thing would be appreciated. I figured the hose docker container is where it would need to be. That doesnt seem to work for me. I am using Docker 1.10.3. Ubuntu 16.04 (and 14.04), Java 8.

**Comment by jmkgreen** [comment] 2016-09-08 17:27
@andjarnic you need to set the environment variable as the container launches, either as a -e parameter to docker run, or an environment entry in a compose file.

**Comment by andjarnic** [comment] 2016-09-08 18:00
So just to be clear, I set up a systemd configuration to start docker on boot, the start looks like:

ExecStart=/usr/bin/docker daemon -H fd:// 

Do I add the -e option here? Or is it something I add only to the docker run call to the Java docker container?

**Comment by jmkgreen** [comment] 2016-09-08 19:12
@andjarnic environment variables has nothing to do with the daemon. Perhaps following some of the many tutorials would be of benefit. After launching experimental containers, `exec`-in to them and see what exists using `env`.

**Comment by andjarnic** [comment] 2016-09-08 20:11
@jmkgreen What I was asking is if the docker host needs the env variable exposed for the docker-machine to use, or if the individual docker container, when started, needs it. I thought it would just be the docker host env setting. 

Needless to say, I tried both approaches, and it doesnt work for me. Still getting OOM crashes. This is really too bad, I had high hopes for using Docker in production. With my docker images crashing in minutes even sitting idle running out of memory, I wonder how anyone has been able to use Java with Docker. I am now trying to see if I can roll back to an earlier version of docker... thinking 1.6.0 or something may not have this issue. Hopefully the devs know about it and fix it soon.

**Comment by cpuguy83** [comment] 2016-09-09 13:14
@andjarnic This is almost certainly an environmental issue and not related to a particular version of Docker.

**Comment by cpuguy83** [comment] 2016-09-09 13:15
That said, I've seen Java (in particular) do some seriously strange things when the backing FS is AUFS.

**Comment by jmkgreen** [comment] 2016-09-19 12:24
@andjarnic verify the environment variable is set within the running container. I've just run `docker exec -it my_container bash` and within that environment run `env` and can see:

```
...
MALLOC_ARENA_MAX=4
...
```

If I `docker inspect my_container` I can see `"Memory": 524288000` in the output which matches my `mem_limit: 500m` instruction within my `docker-compose.yaml` file for this container.

Separately, and again documented elsewhere, my JVM launch includes memory management configuration:

```
root@9eead1132c4f:/# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl   35:00 java -Xms128m -Xmx256m -jar my-program.jar
 3014 ?        Ss     0:00 bash
 3021 ?        R+     0:00 ps ax
```

If you get this far and concur that all are reporting as you expect, you may wish to attach a JVM monitor to watch what your application is actually doing, a procedure that far exceeds the remit of this GitHub issue. Hope this helps!

**Comment by Guilhermeslucas** [comment] 2017-01-03 16:41
I'm having the same issue running Jenkins on a Docker Container. Someone know how to fix it? Thanks!

**Comment by cpuguy83** [comment] 2017-01-04 22:14
These articles may be interesting to some:

http://trustmeiamadeveloper.com/2016/03/18/where-is-my-memory-java/
http://matthewkwilliams.com/index.php/2016/03/17/docker-cgroups-memory-constraints-and-java-cautionary-tale/

I don't think they relate to the original issue, but others reporting various other "java's using more than what I expect" type issues.

**Comment by Guilhermeslucas** [comment] 2017-01-06 17:57
I did what this articles mentioned, but the JVM still breaking my container. What are the arguments you are setting the JVM and the Docker Container?

Best Regards,

**Comment by megastef** [comment] 2017-01-13 15:51
FYI: https://github.com/docker-library/openjdk/issues/57#issuecomment-272475550

**Comment by Brismadsen** [comment] 2017-02-20 09:21
Did anybody succeed in finding a solution for this? (My memory is gone soo fast...)

**Comment by vimal3271** [comment] 2017-03-10 09:28
Any solution so far?

**Comment by osigida** [comment] 2017-03-10 10:05
@vimal3271, it is a JVM issue, so it should be fixed there.
You can try Java 9 and test if it's working fine: http://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/5f1d1df0ea49

**Comment by jeff303** [comment] 2017-03-29 18:22
@osigida , I believe that is a different issue.  What you have linked to is the fact that the default heap size is calculated incorrectly due to inability to handle cgroups.  If one sets max heap explicitly, that issue is no longer of any relevance.  What's being discussed here is a slow increase in resident set size of the Java process, which is happening outside of the heap.

**Comment by osigida** [comment] 2017-03-29 19:59
@jeff303 I'm well informed what we are discussing here, and observe the problem almost every day ;-).
However, it is not very clear from the PR, if you are right or not. Need to look how phys_mem is used, but i still hope jvm developers know what they are doing.

**Comment by loretoparisi** [comment] 2017-04-21 14:08
@Jimexist Did you set the `MALLOC_ARENA_MAX=4` within the `Dockerfile` like:

```
ENV MALLOC_ARENA_MAX=4
```

I'm getting this issue on latest Docker and Ubuntu 16.04 LTS.

**Comment by kopax** [comment] 2017-04-28 23:00
I have the same issue with jenkins official docker image on latest Docker and Ubuntu 16.04 LTS.

**Comment by turesheim** [comment] 2017-12-27 22:44
I was troubleshooting an issue we have with too much virtual memory being claimed for a process on our 40core/node HPC cluster and used Docker to do various experiments. It appears that Docker somehow does not respect MALLOC_ARENA_MAX and will regardless allow the amount of virtual memory to grow to a number correlating to the number of CPUs being allocated to it. Typically 1GB per two cores, which matches what I see in this article: [Linux glibc >= 2.10 (RHEL 6) malloc may show excessive virtual memory usage](https://www.ibm.com/developerworks/community/blogs/kevgrig/entry/linux_glibc_2_10_rhel_6_malloc_may_show_excessive_virtual_memory_usage?lang=en)

**Comment by thaJeztah** [comment] 2017-12-28 00:16
@turesheim docker itself does nothing with that environment variable (or memory management of the processes inside the container); it sets up namespaces and cgroups for the process, which is all part of the kernel.

You mention the container uses Centos 7; what's is running on he host? (what distro and kernel?)

**Comment by turesheim** [comment] 2017-12-28 00:47
The host is running macOS 10.13.2. I did some more tests on both Docker and the cluster, and I now believe that Docker, nor the HPC OS (CentOS 6 + some amendments) is to blame, but rather the JVM. I found some possible evidence that this has been remedied in Java 9, or possibly a late version of Java 8, but will have to do further investigations to make sure. Thank you for the swift response.

**Comment by thaJeztah** [comment] 2023-09-18 22:01
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-18 22:01 UTC
Labels: area/runtime, area/performance
