### ISSUE TITLE
COPY --chown=$ARG_UID not recognised

### ISSUE THREAD

**Issue by grooverdan** [moby/moby#36557] opened 2018-03-12 02:32 UTC
Using a ARG value as a numeric ID in a build process fails with ```COPY --chown={arg}```. Replacing {arg} with the value works.

**Steps to reproduce the issue:**

1. x/Dockerfile
<pre>FROM ubuntu
ARG BUILD_UID=1000
RUN useradd -m -u $BUILD_UID --home-dir /build build
WORKDIR /build
COPY --chown=$BUILD_UID Dockerfile ./
</pre>
2. docker build -f x/Dockerfile   x
<pre>
docker build -f x/Dockerfile   x
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM ubuntu
 ---> 2fa927b5cdd3
Step 2/5 : ARG BUILD_UID=1000
 ---> Using cache
 ---> d57b24600ac5
Step 3/5 : RUN useradd -m -u $BUILD_UID --home-dir /build build
 ---> Running in 4f2c0d14a1fb
Removing intermediate container 4f2c0d14a1fb
 ---> b4becc7eb34f
Step 4/5 : WORKDIR /build
Removing intermediate container 07b29496fd98
 ---> 0fd95e52a17d
Step 5/5 : COPY --chown=$BUILD_UID Dockerfile ./
unable to convert uid/gid chown string to host mapping: can't find uid for user $BUILD_UID: no such user: $BUILD_UID
</pre>

**Describe the results you expected:**

Build as if ```$BUILD_UID``` was 1000

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:20:00 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:22:34 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

``` Containers: 58
 Running: 1
 Paused: 0
 Stopped: 57
Images: 121
Server Version: 17.12.1-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-1050224-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 107.4GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 62.93GB
 Data Space Total: 107.4GB
 Data Space Available: 44.44GB
 Metadata Space Used: 40.8MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.107GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.144 (2017-10-06)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.15.6-300.fc27.x86_64
Operating System: Korora 27 (Marlin)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.62GiB
Name: spaceman
ID: 76KL:6KFN:HCFK:4ETT:SUDV:RIUW:DVOH:HH4O:GDYO:JHUK:EBIP:BLYB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2018-03-12 09:59
Thanks for reporting, but this is currently the expected behaviour, because Dockerfile command flags, such as `--chown` do not (yet) support variable expansion. There's a ticket tracking that enhancement: https://github.com/moby/moby/issues/35018, feel free to participate there (or perhaps you're interested in contributing and working on that feature)

I'll close this issue to prevent the discussion from diverging, but feel free to comment after I closed :+1:

**Closed** 2018-03-12 11:13 UTC
Labels: area/builder
