### ISSUE TITLE
layer preparation in daemon causes slow v2 push performance

### ISSUE THREAD

**Issue by jarus** [moby/moby#13250] opened 2015-05-15 12:31 UTC
Hi,

I build really big docker images (16GB) which contains a big application. While testing of the new docker-distribution registry I noticed that the push is much slower than a push again the old python registry. Both registry use the local file system as storage.

v2: 38min
v1: 23min

```
docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64
```

```
Containers: 4
Images: 134
Storage Driver: btrfs
 Build Version: Btrfs v3.17.1
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 4.0.3
Operating System: CoreOS 681.0.0
CPUs: 10
Total Memory: 62.93 GiB
Name: ---
ID: SBM4:4LPG:PVYM:WAH3:Q7LT:FN23:JZSL:Q6IM:7E2I:SWGT:T2RJ:LWWJ
```

Kernel: 4.0.3

Environment details (AWS, VirtualBox, physical, etc.):
The registries are on another host  (physical) and both are connected via 1Gbit and the only other application which used bandwidth was sshd. In my eyes the main time-sink is the "buffering to disk" process which consumes lot more time than before with registry v1.

How reproducible:
Push a very big docker image again v2 registry.

Actual Results:
Slower push time than before with v1 registry.

Expected Results:
Fast or equal push time with v1 registry.

Kind regards
Christoph

**Comment by cpuguy83** [comment] 2015-05-15 15:02
Can you test with a build from master?
#13059 _should_ have improved the situation.

**Comment by jarus** [comment] 2015-05-15 17:44
No I tried it with the last master build from master.dockerproject.com but there was no time improvement.
```
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 5d2ef30
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 5d2ef30
OS/Arch (server): linux/amd64
```

**Comment by LK4D4** [comment] 2015-05-15 18:49
ping @stevvooe @dmcgowan 
Looks like some `Walk` stuff again.

**Comment by stevvooe** [comment] 2015-05-15 23:31
@jarus Looking at the quoted numbers, it seems you are getting about 7 MB/s of bandwidth during the push, based on a 16GB image. Even with the read to hash the content, this is only 14 MB/s. The V1 bandwidth seems to be around 12MB/s. If we treat that as a baseline, it seems like we may be serializing a duplicated operation on a layer, such as a read from disk then a push.

Let's take a peak at the following:

Is the CPU usage encountered from the registry instance or the daemon?
How many layers make up the 16GB image?
Is there any way you can break up the image layers such that parts that don't change often end up on a separate layer?
How is the registry configured? Are you using the filesystem backend or another?

My gut feeling is that there is a bottleneck in the client somewhere. Looking at the relative bandwidth provides some hints here.

It might be interesting to note that the push API in V2 is optimized for pull over push. All data going in the registry is hashed and verified before being accepted, which has a cost. This allows for more secure distribution schemes that leverage content-addressability.

There are also a few missing optimizations in the docker daemon that may help this:
- Layers aren't yet stored by digest, requiring that the client hash them before push, hence the massive CPU and disk IO
- V2 protocol allows parallel push of layers but the docker client still pushes sequentially.

However, I don't think the protocol or the missing optimizations account for the bottleneck here.

**Comment by jarus** [comment] 2015-05-16 15:30
> Is the CPU usage encountered from the registry instance or the daemon?

The high CPU usage is from the docker daemon.

> How many layers make up the 16GB image? Is there any way you can break up the image layers such that parts that don't change often end up on a separate layer?

```
└─6cedf261cab7 Virtual Size: 249.8 MB
  └─666f8444db03 Virtual Size: 249.8 MB
    └─0a5596d2b687 Virtual Size: 876.2 MB
      └─c443d379f3b7 Virtual Size: 876.2 MB
        └─430520c2a140 Virtual Size: 880.4 MB
          └─211d34cab13b Virtual Size: 880.4 MB
            └─369e105999ec Virtual Size: 880.4 MB
              └─d67f32b875dd Virtual Size: 880.4 MB
                └─c212d2d3ac20 Virtual Size: 880.4 MB
                  └─3242cbce1679 Virtual Size: 880.4 MB
                    └─3a95e30386b1 Virtual Size: 880.4 MB
                      └─c2180923ef13 Virtual Size: 880.4 MB
                        └─8e1503c56703 Virtual Size: 880.4 MB
                          └─49f1974bbcff Virtual Size: 880.4 MB
                            └─f9e29201ddf2 Virtual Size: 880.4 MB
                              └─d30b27d7ed92 Virtual Size: 880.4 MB
                                └─dc7ce95c0ab8 Virtual Size: 880.4 MB
                                  └─e9f2fcb9d7ce Virtual Size: 880.4 MB
                                    └─f30e8ad8d43b Virtual Size: 880.4 MB
                                      └─321ba9ac68d2 Virtual Size: 880.4 MB
                                        └─7c3800f2b76b Virtual Size: 880.4 MB
                                          └─6fd7cac87947 Virtual Size: 880.4 MB
                                            └─985ade9fc707 Virtual Size: 880.4 MB
                                              └─8e92c94b7f5d Virtual Size: 880.4 MB
                                                └─ad8de63140f7 Virtual Size: 880.4 MB
                                                  └─a6ae7f746ee0 Virtual Size: 880.4 MB
                                                    └─438712f3e5f3 Virtual Size: 880.4 MB
                                                      └─f6bf44b8ce92 Virtual Size: 880.4 MB
                                                        └─fc94c9d9023b Virtual Size: 923.2 MB
                                                          └─e203e82b4781 Virtual Size: 927.9 MB
                                                            └─3dda0b4a4f0f Virtual Size: 16.33 GB
```

As you can see there are some layers but the last layer is the biggest one and at the moment it isn't possible to reduce the size. =(

> How is the registry configured? Are you using the filesystem backend or another?

Tested with filesystem backend.


Sadly I didn't measured the time but again the v1 backend the "Buffer to disk" process was much faster but the push over the wire toke much longer. With the v2 registry the "Buffer to disk" process toke much longer mostly 90% and the push over wire was very fast.

**Comment by stevvooe** [comment] 2015-05-18 18:12
@jarus From your answers, it sounds like the bottleneck is somewhere in the docker daemon when reading the data from disk (ie as you stated, during "Buffering to Disk").

Let's put together some steps to reproduce this. We can come up with images with large data sizes, but could you post the exact commands that you use, including if you change image names during the process. Please show the setup exactly, as well.

We probably want to have a benchmark to ensure that this issue is actually fixed.

**Comment by jalmansor** [comment] 2015-05-18 22:14
I wonder if this is the issue I've been running into, as most of my images are ~1gb each and it does seem to be much slower than before 1.6.0. I'll try to get some data on my setup in the next couple days and hopefully that'll help here as well.

**Comment by pwaller** [comment] 2015-05-20 13:44
I've noticed that docker push spends a pretty large amount of time in "Buffer to disk". It's CPU bound inside docker, by the looks of things. Here's a dstat output:

```
20-05 09:28:01| 46   3  50   0   1   0|   0     0 | 104B  540B| 844M  568M 2614M 3459M|1243   430 
20-05 09:28:02| 46   3  49   0   0   0|   0    32k| 104B  540B| 844M  568M 2617M 3455M|1213   343 
20-05 09:28:03| 47   4  50   0   0   0|   0     0 | 396B  874B| 844M  568M 2620M 3453M|1309   516 
20-05 09:28:04| 45   4  49   1   1   0|   0    13M| 104B  540B| 844M  568M 2623M 3450M|1547   853 
20-05 09:28:05| 45   4  50   0   0   0|   0     0 | 104B  540B| 844M  568M 2626M 3447M|1299   517 
20-05 09:28:06| 47   3  50   0   1   0|   0     0 | 104B  540B| 844M  568M 2628M 3444M|1259   461 
20-05 09:28:07| 46   4  50   0   1   0|   0     0 | 104B  540B| 844M  568M 2631M 3442M|1368   600 
20-05 09:28:08| 47   4  50   0   1   0|   0     0 | 104B  540B| 844M  568M 2634M 3439M|1316   536 
20-05 09:28:09| 45   4  48   2   1   0|   0    14M| 104B  540B| 844M  568M 2636M 3437M|1567   912 
20-05 09:28:10| 46   4  50   0   1   0|   0     0 | 132B  582B| 844M  568M 2639M 3434M|1458   796 
20-05 09:28:11| 45   5  50   0   0   0|   0     0 | 104B  540B| 844M  568M 2642M 3431M|1309   537 
20-05 09:28:12| 47   3  50   0   1   0|   0     0 | 104B  540B| 844M  568M 2645M 3428M|1275   468 
20-05 09:28:13| 44   6  49   0   0   0|   0     0 | 104B  540B| 844M  568M 2649M 3423M|1470   888 
----system---- ----total-cpu-usage---- -dsk/total- -net/total- ------memory-usage----- ---system--
     time     |usr sys idl wai hiq siq| read  writ| recv  send| used  buff  cach  free| int   csw 
20-05 09:28:14| 43   6  48   3   1   0|   0    18M| 104B  642B| 844M  568M 2653M 3419M|1821  1423 
20-05 09:28:15| 44   6  50   0   1   0|   0     0 | 312B 1470B| 844M  568M 2657M 3415M|1469   859 
20-05 09:28:16| 45   6  50   0   0   0|   0    48k| 104B  540B| 844M  568M 2661M 3411M|1516   949 
20-05 09:28:17| 46   4  50   0   1   0|   0     0 | 104B  540B| 844M  568M 2663M 3409M|1397   724 
20-05 09:28:18| 46   3  49   0   1   0|   0     0 | 104B  540B| 844M  568M 2666M 3406M|1221   407 
20-05 09:28:19| 47   4  47   3   1   0|   0    17M| 104B  540B| 844M  568M 2669M 3404M|1208   316 
20-05 09:28:20| 45   5  50   0   0   0|   0     0 | 104B  540B| 844M  568M 2672M 3400M|1293   545 
```

Note that the amount of disk write is minimal (there is no subsequent sync write activity after my excerpt either). Also note that the context switching and sys CPU % is quite low (only around 300-1000/sec and 5% respectively)

**Comment by sergeyevstifeev** [comment] 2015-05-22 08:20
Having this issue as well. Pushing to a private S3-backed v2 registry with 1.6 client is taking unreasonably long time (versus v1 with 1.5 client). Pulling is way faster though compared to v1. CPU utilization on both the client and the registry is quite low while pushing.

**Comment by stevvooe** [comment] 2015-05-22 17:58
@sergeyevstifeev You're issue is slightly different. This issue is characterized by disk buffering taking a long time and high cpu usage in the daemon. 

You're experiencing docker/distribution#478. What are your round trip times to s3?

**Comment by sergeyevstifeev** [comment] 2015-05-22 18:15
@stevvooe Thanks for the reference, it indeed seems like you're right! Looks like the roundtrip is 300 ms for me.

**Comment by jarus** [comment] 2015-06-17 20:55
I would assume the bottleneck could be the gzip process. Maybe it is possible to replace the original go gzip implementation with a parallel version like https://github.com/klauspost/pgzip

**Comment by gerrat** [comment] 2015-06-19 21:20
+1 on the push to local file system-backed private registry taking much longer than v1.  ...and I've been searching around for what exactly the "Buffering to Disk" is doing, since it always seems to be sitting at this step (never even noticed this with v1, since it was so much quicker).  Most of my images are a little under 1Gb.  I don't have actual benchmark times, as I've removed the v1 registry, and just started using the v2 one.  I have no plans on going back, but the claim [here](https://github.com/docker/distribution) that it provides **faster push and pull** would be more accurate as: **slower push and faster pull**

    Client version: 1.7.0-dev
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 5e06332
    OS/Arch (client): linux/amd64
    Server version: 1.7.0-dev
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 5e06332
    OS/Arch (server): linux/amd64

**Comment by stevvooe** [comment] 2015-06-19 22:47
I suppose it is time for an update here. We've put together an omnibus issue to address this problem #14018. The root cause is that we have to rebuild the tar layer on each push. As @jarus pointed out, this does involve gzip, but it also walks the filesystem, wrecks the buffer cache and requires re-hashing of content.

@gerrat I am not going to debate you on the claims, since you're experience is to the contrary, but the V2 _registry_ provides much faster push support, especially under concurrency. The issue is that the preparation for the push in the _docker daemon_ is implemented sub-optimally, leading to subpar performance. Once the daemon is fully optimized, these benefits will start to become more obvious.

@jarus I am going to update the title of this issue, clarifying that this is a limitation in the client and will be addressed by the efforts in #14018. Let me know if that is a problem.

**Comment by vincentwoo** [comment] 2015-07-05 08:38
Just wanted to chime in to say that while overall registry performance seems to be stronger on v2, the "Buffering to disk" phase of `docker push` definitely does peg the cpu to 100% and take an order of magnitude longer than the bandwidth transfer itself. Fixing this issue I think will be a HUGE win for perceived push performance.

**Comment by thaJeztah** [comment] 2015-07-05 10:36
@stevvooe @vincentwoo @gerrat given that that step does more than just "buffering"; perhaps that message should be a bit more descriptive?

**Comment by stevvooe** [comment] 2015-07-07 17:03
@thaJeztah The main issue is that we don't keep the layer artifact around and have to regenerate the layer on each push. #14067 is oriented towards ensuring hash stability but we should probably keep the artifact around. There is no reason to save disk space if we are trading off more expensive CPU and developer time.

That said, this bug will be fixed with ongoing work.

**Comment by Andrei-Pozolotin** [comment] 2015-08-24 18:04
+1

**Comment by stevvooe** [comment] 2015-08-24 19:37
This will also be addressed by #15493.

**Comment by thaJeztah** [comment] 2015-08-24 20:44
https://github.com/docker/docker/pull/15493 has been merged and should resolve this issue. I'm going to close this issue, but it would be great if those that encountered this issue could test if it have been resolved for them.

Builds from the current "master" can be downloaded from https://master.dockerproject.org (but obviously should *not* be used in production), and a version containing this PR should be up shortly.

Please comment here if this issue was not resolved

**Comment by cpuguy83** [comment] 2015-08-24 20:46
@thaJeztah Not merged yet :)

**Comment by thaJeztah** [comment] 2015-08-24 20:55
@cpuguy83 Oh my! How did I come to that? Did I look at the wrong tab? :blush: sorry all!

**Comment by stevvooe** [comment] 2015-08-24 23:50
@thaJeztah No worries.

Also, let's be a little careful with the language. When I say "address" that means it will help but will not solve. If it is to be closed, I would say "closes" or "resolves".

**Comment by Andrei-Pozolotin** [comment] 2015-08-25 13:54
@stevvooe #15493 is still not parallel, 
is there a reason layer compact can not be done in parallel?

**Comment by stevvooe** [comment] 2015-08-25 19:53
@Andrei-Pozolotin Without #15493, push is disk limited. Adding parallelization won't improve performance without removing the IO bottleneck.

As far as the original complaint in this ticket, #15493 should address it.

**Comment by tsuna** [comment] 2015-09-01 08:30
I'm not pushing particularly large images (~1GB ± 0.5GB) but I also noticed that the `buffering to Disk` phase is heavily CPU bound at first.  Then comes the disk I/O and network I/O.  But the docker daemon is pegging a single core for a while, and that seems to be taking most of the time.

**Comment by aaronlehmann** [comment] 2015-09-02 20:18
@stevvooe: #15493 has been merged, so should this issue be closed?

**Comment by stevvooe** [comment] 2015-09-02 20:27
@aaronlehmann The root cause for this issue is likely to be compound. The other possible cause is having to rebuild and hash layers, which would manifest is high cpu usage. @tsuna seems to be experience the latter.

I'd like to get some user confirmation before proceeding to close this issue.

**Comment by sam-thibault** [comment] 2023-08-15 13:26
This is an old issue.  I will close it as stale.
We are working on integration with the containerd image store which keeps the compressed artifacts around so it is not necessary to compress on every push.

**Closed by sam-thibault** 2023-08-15 13:26 UTC
Labels: area/distribution, version/1.6
