### ISSUE TITLE
Proposal: Create apt install package specifically for WSL use-case

### ISSUE THREAD

**Issue by kayakyakr** [moby/moby#32238] opened 2017-03-30 21:35 UTC
Docker for Windows and Windows Subsystem for Linux combos wonderfully: the docker daemon lives on windows while docker client in Ubuntu can easily connect to the daemon and any containers running can be used from linux-bound applications. It creates almost an ideal dev environment.

The one gotcha is that it was a bit more difficult to set up since the Ubuntu under WSL does not require the docker daemon (and in fact, cannot run it at all). This causes dire warnings when, in fact, it's worked just fine. I don't believe that the setup even requires `$DOCKER_HOST` to point to `tcp://0.0.0.0:2375` as `tcp://127.0.0.1:2375` seems to also work just fine. 

If the packages installed were limited to docker-compose + the docker client without any daemon setup, it would make things much simpler.

**Comment by thaJeztah** [comment] 2017-03-31 01:53
looks like a duplicate of https://github.com/docker/docker/issues/15360

**Comment by kayakyakr** [comment] 2017-03-31 06:58
Looks like that became this suggestion over the course of discussion.

**Comment by atrauzzi** [comment] 2017-04-07 02:50
Would very much like to see this happen.

**Comment by thaJeztah** [comment] 2017-04-07 11:24
ping @friism @andrewhsu

**Comment by friism** [comment] 2017-04-07 15:51
Is there are way to create a package separate from normal Ubuntu and specific to Windows Subsystem for Linux?

**Comment by kayakyakr** [comment] 2017-04-07 15:56
I don't believe there is. Under WSL, Ubuntu believes itself to be a full implementation and attempts to act as one.

I'm guessing the best approach will be to offer a different "collection" package such as `docker-remote` which installs the client and associated apps without installing the daemon and sets up an ENV for pointing to a remote server.

**Comment by thaJeztah** [comment] 2017-04-07 16:44
@friism that's why I linked https://github.com/docker/docker/issues/15360 - could be solved by having the client as a separate package

**Comment by whitecolor** [comment] 2017-06-27 09:33
I'm currently struggling to understand what is a correct way to get docker/docker-compose clients work in Windows Subsystem for Linux.

In the latest WSL release (windows creators update) instructions given in https://docs.docker.com/engine/installation/linux/ubuntu/ do not work (in previous releases it kind of worked)

Though I can install using:
$ add-apt-repository universe
$ apt-get install docker.io

But it installs version `Docker version 1.10.3, build 20f81dd` I believe it is kind of old? So how one should deal with it?

**Comment by atrauzzi** [comment] 2017-06-27 12:32
One difference worth noting is how paths are mapped during bind mounts.  The filesystem in WSL is `/mnt/c/...`

Not sure if that requires special handling or configuration when calling the docker command.

**Comment by friism** [comment] 2017-06-27 13:59
@whitecolor  why can't you just invoke the Windows Docker binaries from WSL? https://msdn.microsoft.com/en-us/commandline/wsl/interop

**Comment by whitecolor** [comment] 2017-06-27 14:08
@friism yes I'm already testing it
`docker.exe` from windows from seems to work normal in WSL, but `docker-compose` should be installed on linux using instructions in https://github.com/docker/compose/releases

**Comment by friism** [comment] 2017-06-27 16:20
> docker-compose should be installed on linux 

Why can't you just use docker-compose.exe? It's installed with Docker for Windows.

> I see many cases of work of executables that are not acceptable.

Let us know what's not working so we can figure out what's wrong.

**Comment by whitecolor** [comment] 2017-06-27 16:52
It doesn't work well
![image](https://user-images.githubusercontent.com/736697/27599670-f3ade228-5b82-11e7-9fb8-f915a5289156.png)

**Comment by thaJeztah** [comment] 2017-06-27 17:11
At this moment, I think the easiest way to obtain the docker client, is to download the static package (`.tgz`); https://download.docker.com/linux/static/, extract it, and use the `docker` binary from that (that binary is the docker cli). For example, to install docker 17.03.1-ce;

```bash
$ curl -o docker-ce.tgz -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-17.03.1-ce.tgz
$ tar -xvzf docker-ce.tgz
docker/
docker/docker-containerd-ctr
docker/docker-proxy
docker/docker
docker/docker-containerd
docker/dockerd
docker/docker-init
docker/docker-containerd-shim
docker/docker-runc

$ mv docker/docker /usr/bin

$ docker --version
Docker version 17.03.1-ce, build c6d412e
```

Docker Compose can be installed using the instructions on the releases page on GitHub; https://github.com/docker/compose/releases

**Comment by whitecolor** [comment] 2017-06-27 17:29
> One difference worth noting is how paths are mapped during bind mounts. The filesystem in WSL is /mnt/c/...

BTW for docker-compose to work in WSL it is need to make a symlinks inside MobyLinux VM. I've created the issue about it long ago https://github.com/docker/for-win/issues/371

**Comment by whitecolor** [comment] 2017-06-29 10:38
It seem that this can run `docker-compose` from windows fine
`cmd.exe /c "chcp 850 >> null && docker-compose $@"`

**Comment by whitecolor** [comment] 2017-07-07 17:19
For everything in my docker stack (`docker`, `docker-compse`, `gcloud`, `kubectl`) to work correctly I still have to use native linux versions, windows versions doesn't work in many cases.

**Comment by thaJeztah** [comment] 2023-09-16 17:51
Let me close this ticket for now, as it looks like it went stale.

**Closed by thaJeztah** 2023-09-16 17:51 UTC
Labels: platform/desktop, area/project, area/packaging
