### ISSUE TITLE
Can Docker force user enter password before enter container?

### ISSUE THREAD

**Issue by ysh329** [moby/moby#35432] opened 2017-11-08 01:28 UTC
Make sure everyone doesn't enter the other person's container accidentally or enter the password before entering the container.

**Comment by thaJeztah** [comment] 2017-11-09 16:38
No, if you have access to the docker API, you can `docker exec` into any container; `docker exec` does not "log in" to the container, it simply starts a new process in the container's namespace (which can be a shell or any other process).

Containers are not VM's, and although they "look" like a virtual machine, they are not; containers are a process "running on the host", but enclosed in a "sandbox" (using "namespaces").

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-09 16:38 UTC
