### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/

### ISSUE THREAD

**Issue by biotech25** [moby/moby#34507] opened 2017-08-14 19:17 UTC
**Description**
Hi, 

I installed Docker-ee to Redhat 7.3.  But, I can't start docker.  So, I entered 

]# docker ps
]#  systemctl status docker

And, I googled to find solution, but I couldn't find it.  Could you help me?

**Steps to reproduce the issue:**
1.[root@wang-linux1-dept-med-pitt-edu ~]# sudo docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

2.[root@wang-linux1-dept-med-pitt-edu ~]# sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-08-14 15:05:38 EDT; 19h ago
     Docs: https://docs.docker.com
  Process: 8227 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 8227 (code=exited, status=1/FAILURE)

Aug 14 15:05:37 wang-linux1-dept-med-pitt-edu systemd[1]: Starting Docker Application Container Engine...
Aug 14 15:05:38 wang-linux1-dept-med-pitt-edu dockerd[8227]: unable to configure the Docker daemon with file /etc/docker/daemon.json: invalid character '}' looking for beginning of object key string
Aug 14 15:05:38 wang-linux1-dept-med-pitt-edu systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Aug 14 15:05:38 wang-linux1-dept-med-pitt-edu systemd[1]: Failed to start Docker Application Container Engine.
Aug 14 15:05:38 wang-linux1-dept-med-pitt-edu systemd[1]: Unit docker.service entered failed state.
Aug 14 15:05:38 wang-linux1-dept-med-pitt-edu systemd[1]: docker.service failed.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@wang-linux1-dept-med-pitt-edu ~]# docker --version
Docker version 17.03.2-ee-5, build fa09039

```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by saurabh-deochake** [comment] 2017-08-14 21:06
Would you try running Docker as `sudo docker` instead of just `docker`? May be the user you are executing docker command does not have privilege to talk to `/var/run/docker.sock`.

**Comment by thaJeztah** [comment] 2017-08-14 22:29
The output of `systemctl status docker` is also truncated, so the full error message is not visible

**Comment by biotech25** [comment] 2017-08-15 14:18
Thank you Saurabh and Sebastiaan. As you guys recommended, I re-tried using sudo and posted full error message, but problem is not solved.  I checked whether I have "/var/run/docker.sock" file.  I don't have the file. I think that is the problem.  Where can I get "/var/run/docker.sock" file?

**Comment by biotech25** [comment] 2017-08-15 14:54
I am using "icgc-get" which requires docker.  As you see below, I got error in docker daemon connection.  I think it is the problem because I don't have "/var/run/docker.sock" file.  Could you send me the file? I can't get it although I googled. 

[root@wang-linux1-dept-med-pitt-edu 1_StructuralSomaticMutations_WGS]# ./icgc-get --config /root/.icgc-get/config.yaml --docker true download FI378424 -r collaboratory
************************************************************************************
Starting download(s) for files: FI378424  from: collaboratory
************************************************************************************
collaboratory client exited with a nonzero error code 125.
Error: Please check client output for error messages
**Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?**
[root@wang-linux1-dept-med-pitt-edu 1_StructuralSomaticMutations_WGS]#

**Comment by biotech25** [comment] 2017-08-15 16:31
Or, another way is removing docker and re-install it.  I tried to remove docker with this script below, but it doesn't work.  Could you teach me how I can remove the installed docker?

$ sudo yum remove docker \
                  docker-common \
                  docker-selinux \
                  docker-engine-selinux
                  docker-engine

**Comment by thaJeztah** [comment] 2017-08-15 16:43
The `/var/run/docker.sock` file is not a _file_ but it's a linux socket; the socket is created when the daemon starts; if the daemon fails to start, the socket is not created. The installation manual shows how to uninstall the `docker-ee` package; https://docs.docker.com/engine/installation/linux/docker-ee/rhel/#install-using-the-repository

```
Could you teach me how I can remove the installed docker?

$ sudo yum remove docker 
docker-common 
docker-selinux 
docker-engine-selinux
docker-engine
```

From that output it looks like you have another version of docker installed as well (the `docker-engine` package, not just `docker-ee`)?

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by biotech25** [comment] 2017-08-15 16:59
Thank you Sebastiaan!! Thanks to you. I removed docker successfully. (sudo yum -y remove docker-ee)

Could you help me one more time?  What is the correct docker package for me to install?  I downloaded docker package at here, https://download.docker.com/linux/centos/7/x86_64/stable/Packages/  

But, I can't find a right package for Redhat 7.3   

Thank you,

**Comment by thaJeztah** [comment] 2017-08-15 17:30
The Red Hat package is only available as Enterprise Edition (see the link above), which requires a subscription. You can install the CentOS package of the Docker CE (Community Edition), which generally works, but no guarantees as there may be differences between RHEL and CentOS

**Comment by biotech25** [comment] 2017-08-15 17:35
I see.  For Red Hat package, I need a subscription for Enterprise Edition of Docker...  You mean that I need to purchase the docker subscription from https://www.docker.com/ ?    I am going to subscribe it.  Thank you.

**Comment by thaJeztah** [comment] 2017-08-15 17:43
Enterprise Edition is a paid-for version yes (also see https://store.docker.com)

Let me close this issue, because this is not a bug report, but feel free to ask for more information 👍

**Closed by thaJeztah** 2017-08-15 17:43 UTC
Labels: status/more-info-needed
