### ISSUE TITLE
[Issue/RFE] Downloading/building  images bigger than base device size.

### ISSUE THREAD

**Issue by shishir-a412ed** [moby/moby#22701] opened 2016-05-12 15:19 UTC
ISSUE: If my docker daemon is running on a default configuration (docker daemon --storage-opt dm.basesize=10G). 

If I try to do a `docker pull` of an image > 10G this would FAIL, also if I try to `build` or `commit` a large image ( >10G) that would fail too. This affects docker pull / build / commit.

a simple use case would be:

a) User A is running docker daemon with base device size as 50G (docker daemon --storage-opt dm.basesize=50G)
b )User A builds a large image ~30G and pushes it to docker hub.
c )User A shares this with User B.
d) User B is running on the default configuration where the base device size = 10G.
e) User B does a docker pull.
f) Docker pull fails.

I guess the question here is, is this expected behavior ? or do we want to add a feature to allow pulling images  larger than base device size.

Shishir

**Comment by justincormack** [comment] 2016-05-12 15:53
I think this is expected. Most images are not that big, so users will have to change configuration for extreme cases.

**Comment by shishir-a412ed** [comment] 2016-05-12 16:28
@justincormack 
Changing the configuration is not that straight forward. If I change my base device size from 10G to 50G to accomodate the above use case. I would have to remove all my images and repull / rebuild them to allow all future containers to take advantage of the new base device size.

We introduced an option to increasing the device size (rootfs size) for containers at docker create / run time.
```
$docker run -it --storage-opt size:50G fedora /bin/bash
```
I guess what I am asking is do we need/want this option for images too ?

ping @rhvgoyal @calavera @thaJeztah

**Comment by thaJeztah** [comment] 2016-05-12 17:46
Starts to feel like we're adding too many knobs to facilitate this

**Comment by shishir-a412ed** [comment] 2016-05-23 16:22
@thaJeztah I agree, we should not add a knob to facilitate this.
This should be enabled by default. (The way it is for other storage drivers like overlay).

Right now, this is failing for `docker pull / build / commit`. A user would try to pull or build a large image (some size greater than the base device size) and docker would blow up :)

Shishir

**Comment by rhatdan** [comment] 2016-05-23 18:17
I don't think we should have knobs for this, since other storage backends can not prevent huge images, devmapper should not either.  Adding knobs that users will never use tends to be a waste of time.

**Comment by thaJeztah** [comment] 2016-05-23 18:38
Ok, let's close this. Thanks for suggesting though @shishir-a412ed

**Comment by shishir-a412ed** [comment] 2016-05-23 19:21
@thaJeztah Sorry I am confused. 
We are all on the same page, no one wants a knob to facilitate this feature.

By closing this issue, do you mean docker doesn't want to allow downloading bigger images (> base device size) ?
i.e docker devicemapper should not have the same functionality as other storage drivers like overlay ??

Shishir

**Comment by justincormack** [comment] 2016-05-23 20:15
@shishir-a412ed the thing is that overlay does not have a size constraint, but devicemapper does, due to how it is implemented, so I don't think it is about having the same functionality.

**Comment by rhatdan** [comment] 2016-05-23 20:30
@justincormack I am proposing that we eliminate the size requirement, by allowing the device to automatically expand, if possible.  Rather then breaking, just because admin picked a size that was too small for all container images.

**Comment by thaJeztah** [comment] 2016-05-23 20:49
oh! sorry, interpreted incorrectly, I'll reopen so that we can discuss options, my bad

**Comment by DrewRay** [comment] 2016-08-04 03:18
To add two cents, this seems like a easy fix that will make the platform easier to use for beginers.

**Comment by justincormack** [comment] 2016-10-13 09:36
@DrewRay I don't think it is that easy to implement, but feel free to try. Generally there is not much interest in working on devicemapper now, as overlay will be working properly on new versions of RHEL shortly, even with SELinux on, which was the previous issue, and overlay does not have any fixed size limits.

**Comment by shishir-a412ed** [comment] 2016-10-13 15:59
@justincormack I have an implementation which solve the problems described above with `docker build` and `docker commit`.
https://github.com/shishir-a412ed/docker/tree/commit_build_bigger_images

I am not opening a PR, since I can see a lot of reservations about this.
Saying "there is not much interest in working on devicemaper now"  is a little far fetched :)
I think devicemapper is going to be here for a while. So supporting both drivers (devicemapper, overlay) would be optimal.

@DrewRay Feel free to try it out, although testing this would not be that straightforward.

Shishir

**Comment by blaines** [comment] 2016-10-20 23:29
I ran into this issue today. The messaging was unclear and it was not apparent that the dm.basesize had a default, or that this variable was the cause of my problem. My disks had plenty of storage and inodes to download the image, yet the limit here was prohibiting me from doing so.

```
[ec2-user ~]$ docker pull blaines/project:bd789f2
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /tmp/_main_Incremental: no space left on device
```

**Comment by zrss** [comment] 2019-02-12 02:56
currently, we still use devicemapper as the storage driver of docker (17.06.1) ... and some AI
 images are larger than 10G ...

**Comment by thaJeztah** [comment] 2023-06-06 07:55
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637

**Closed by thaJeztah** 2023-06-06 07:55 UTC
Labels: area/storage/devicemapper, kind/enhancement
