### ISSUE TITLE
Suggestion: Allow docker stats to display stats of all tasks across the swarm

### ISSUE THREAD

**Issue by ascora** [moby/moby#33459] opened 2017-05-31 21:09 UTC
**Description**

This is a suggestion for a new feature:
docker stats is a very useful command but in docker swarm mode it is currently required to SSH into each node and to start docker stats on each node to check the swarm status.
The suggestion is to extend the docker stats command to display stats to consider the tasks / containers from all nodes across the swarm rather than displaying only the information from the local node.
Alternatively, a docker service stats could be implemted - just like the docker service logs.

**Comment by cpuguy83** [comment] 2017-06-01 21:23
I believe we do not plan to extend `docker stats`, but rather expose stats via the prometheus metrics endpoint.

**Comment by thaJeztah** [comment] 2017-06-01 21:29
Yes, this is close to a duplicate of https://github.com/moby/moby/issues/33024. There are no plans to extend the current stats implementation for swarm mode; the current implementation does not scale well, and would not really be suitable for a swarm.

Let me close this issue in favour of https://github.com/moby/moby/issues/27307, which is the discussion on using metrics for this

**Closed by thaJeztah** 2017-06-01 21:29 UTC
Labels: area/swarm, kind/feature
