### ISSUE TITLE
Misleading error (experimental) message for docker deploy

### ISSUE THREAD

**Issue by schmunk42** [moby/moby#34933] opened 2017-09-22 07:17 UTC
**Description**

Running the commands `docker deploy` and `docker stack deploy` show different output.

**Steps to reproduce the issue:**
1. Run `docker deploy --help`
2. Run `docker stack deploy --help`

**Describe the results you received:**

For 1.

    docker deploy is only supported on a Docker daemon with experimental features enabled

For 2.

    Usage:  docker stack deploy [OPTIONS] STACK

    Deploy a new stack or update an existing stack
    [...]

**Describe the results you expected:**

Either behaving the same way or a notice that `docker deploy` is deprecated. I don't know for sure about its current status.

**Additional information you deem important (e.g. issue happens only occasionally):**

AFAIK swarm mode is no longer experimental, so I first wondered, why the first command gives the error message. Then I wondered why the other command works without experimental flags enabled :)

**Output of `docker version`:**

```
 Version:      17.09.0-ce-rc3
 API version:  1.31 (downgraded from 1.32)
 Go version:   go1.8.3
 Git commit:   2357fb2
 Built:        Thu Sep 21 02:30:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.07.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: tcpdh8iqciseb59d0cvjr4wj5
 Is Manager: true
 ClusterID: tezaqycl6bsy5xz605pea6jgq
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: <ANONYMIZED>
 Manager Addresses:
  <ANONYMIZED>
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-3-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.5MiB
Name: <ANONYMIZED>
ID: OSLJ:QWE2:XKLX:A7BV:YZYQ:SYHI:5D57:WSHS:SRL5:TKQI:DGV4:6DRT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 master=1
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- docker swarm mode on VirtualBox with Debian Stretch

**Comment by thaJeztah** [comment] 2017-09-22 09:10
Thanks for reporting! This is a duplicate of https://github.com/docker/cli/issues/527, see the discussion there for more information.

**Closed by thaJeztah** 2017-09-22 09:10 UTC
Labels: area/swarm, version/17.07

**Comment by schmunk42** [comment] 2017-09-22 12:29
@thaJeztah Thank you for pointing to `docker/cli` - I still need to get used to the split repos :)

btw: Which issues belong to `moby/moby`, only those for the engine?
