### ISSUE TITLE
Docker exec using proxy

### ISSUE THREAD

**Issue by zjxpsetp** [moby/moby#31636] opened 2017-03-08 08:02 UTC
Hi,
We have some docker server running in a network zone (A) while our client running in another network zone(B).  We have a http/https proxy can help us access network A from B. We can run docker ps command correctly via proxy (We set proxy by enable "http_proxy" and "https_proxy" in ubuntu). But I don't know why the `docker exec`, `docker cp` can not work via this proxy. Any idea?

**Comment by tecknicaltom** [comment] 2018-02-21 00:20
I just hit this this too. If your http_proxy/https_proxy is a socks proxy, I found that a workaround is to also export all_proxy.

**Comment by franasa** [comment] 2020-01-14 14:11
how do you mean @tecknicaltom?

**Comment by thaJeztah** [comment] 2020-01-14 14:25
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug-report, but feel free to continue the conversation

**Closed by thaJeztah** 2020-01-14 14:25 UTC
Labels: area/cli, kind/question

**Comment by pschichtel** [comment] 2020-04-28 08:54
Isn't this a bug? Just faced this, that pretty much all commands work fine over an HTTP proxy with HTTP_PROXY and HTTPS_PROXY set, however docker-exec all of the sudden requires a SOCKS proxy. If not a technical bug, than this should at least be documented, right? Especially since the error message is telling you the docker socket cannot be reached, even though it is perfectly reachable for every other command

**Comment by pschichtel** [comment] 2020-04-28 10:07
it seems, that docker-run is also affected, when you run it attached. So I assume the attaching requires a SOCKS proxy for whatever reason.

What worked for me as a workaround:
```
script_container="$(docker run --rm -d -t -v /var/run/docker.sock:/var/run/docker.sock docker:19 docker exec -t "$container" sh -c "$command")"
docker logs -f "$script_container"
```
