### ISSUE TITLE
Add executable file from windows

### ISSUE THREAD

**Issue by ojhaujjwal** [moby/moby#25465] opened 2016-08-06 10:36 UTC
If I add a bash script from windows to a container using ADD or COPY, it is set as 666 on the container. I want to add a bash script as a entrypoint. But, it says permission denied.  Is there any way to change the mode of the script in the container? 

``` bash
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
```

RUN chmod +x did not work. Because, after the build, while running the container, it was set back to 666 and the entry poing was not executed

**Comment by erwinwildenburg** [comment] 2016-08-06 23:41
Isn't your chmod command changing the permissions on a different file then you are executing?

**Comment by ojhaujjwal** [comment] 2016-08-07 02:12
how is that a different file to what I am exeuting?

**Comment by erwinwildenburg** [comment] 2016-08-07 10:59
You copy the file:         entrypoint.sh
You chmod the file:     docker-entrypoint.sh

**Comment by ojhaujjwal** [comment] 2016-08-07 11:29
oops that's a typo in the issue description :D

**Comment by thaJeztah** [comment] 2016-08-07 15:09
could you add the output of `docker version` and `docker info`?

**Comment by ojhaujjwal** [comment] 2016-08-07 16:00
output of docker version:
```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```
outpur of docker info:
```
Containers: 59
 Running: 0
 Paused: 0
 Stopped: 59
Images: 813
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 562
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: moby
ID: 5LSG:YKFD:ZQVI:2XFO:EPD2:4WKK:SYQD:IRYL:BBYT:6PXQ:GER2:UIRE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2016-08-08 11:16
@ojhaujjwal how did you verify the mod changed back to 666? Did you start a container and verify the permissions, or deducted from the `permission denied`? Can you reproduce with a minimal Dockerfile?

Here's what I did to reproduce (note: this is on Docker for Mac, but the `chmod` is running in the container, so this *should* not make a difference);

My `entrypoint.sh`;

```bash
#! /bin/sh

echo "foo"
```

That file does not have `execute` permissions locally:

```bash
ls -la entrypoint.sh
-rw-r--r--  1 sebastiaan  staff  23  8 aug 13:03 entrypoint.sh
```

My `Dockerfile`

```Dockerfile
FROM ubuntu
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
```

After building the Dockerfile (`docker build -t repro-25465 .`);

```bash
docker run -it --rm repro-25465
foo
```

To verify if the permissions changed;


```bash
docker run -it --rm --entrypoint=/bin/sh repro-25465
# ls -la /usr/local/bin/entrypoint.sh
-rwxr-xr-x 1 root root 23 Aug  8 11:03 /usr/local/bin/entrypoint.sh
# exit
```

Does your `Dockerfile` contain a `USER` instruction?

**Comment by davoscollective** [comment] 2017-11-21 01:09
@thaJeztah it does make a difference that you're using mac. 

 chmodding a host mounted volume in a linux container on Docker for windows is broken. All files will keep the full permissions 0755. See https://docs.docker.com/docker-for-windows/troubleshoot/#permissions-errors-on-data-directories-for-shared-volumes 

There are some workarounds listed.

**Comment by thaJeztah** [comment] 2017-11-21 01:22
@davoscollective the issue that was reported here was during docker build, in which case there's no bind-mounted volume.

Having said that, I'm closing this issue, because no more information was added by the original reporter.

**Closed by thaJeztah** 2017-11-21 01:22 UTC
Labels: platform/desktop

**Comment by andoks** [comment] 2019-09-03 12:49
In case a script having its exec-bit unset when copied into a linux container on a windows host is considered buggy behavior; I'm having the issue too. And from the forums it seems like this is [commonly known](https://forums.docker.com/t/windows-sh-scripts-and-the-execute-bit/12203).

Below are the versions of software and scripts I used to reproduce the issue.

```
$ ls -la *
-rw-r--r-- 1 user 197121 194 Aug 29 16:13 Dockerfile
-rwxr-xr-x 1 user 197121  47 Aug 29 16:14 script.sh
```
```
$ for f in *; do echo -e "file $f>>>"; cat $f; echo -e "<<<\n"; done
file Dockerfile>>>
FROM debian:9
COPY script.sh /usr/local/bin/script.sh
RUN ls -la /usr/local/bin/script.sh
RUN chmod +x /usr/local/bin/script.sh
RUN ls -la /usr/local/bin/script.sh
RUN ./usr/local/bin/script.sh
<<<

file script.sh>>>
#!/usr/bin/env sh

echo "Hello from script.sh"
<<<
```
```
$ docker build --no-cache .
Sending build context to Docker daemon  54.78kB
Step 1/6 : FROM debian:9
 ---> f26939cc87ef
Step 2/6 : COPY script.sh /usr/local/bin/script.sh
 ---> de36697e91cc
Step 3/6 : RUN ls -la /usr/local/bin/script.sh
 ---> Running in e56bd327c9f4
-rw-rw-rw- 1 root root 47 Aug 29 14:14 /usr/local/bin/script.sh
Removing intermediate container e56bd327c9f4
 ---> 230278bdb4c8
Step 4/6 : RUN chmod +x /usr/local/bin/script.sh
 ---> Running in bf96ec11d51e
Removing intermediate container bf96ec11d51e
 ---> 76144644bdeb
Step 5/6 : RUN ls -la /usr/local/bin/script.sh
 ---> Running in 03354c9cd34a
-rwxrwxrwx 1 root root 47 Aug 29 14:14 /usr/local/bin/script.sh
Removing intermediate container 03354c9cd34a
 ---> 915a7ca7a682
Step 6/6 : RUN ./usr/local/bin/script.sh
 ---> Running in 6b8bd326474c
Hello from script.sh
Removing intermediate container 6b8bd326474c
 ---> b847220e11c3
Successfully built b847220e11c3
```

```
$ docker info
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.2.2-10-g3f18b65-tp-docker)
  app: Docker Application (Docker Inc., v0.8.0)

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 45
 Server Version: 19.03.1
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.145)
 OSType: windows
 Architecture: x86_64
 CPUs: 32
 Total Memory: 31.88GiB
 Name: MACHINE
 ID: N5QE:IGYO:MRPD:5RL4:IDFK:SYPG:4AJW:6PO3:OJW5:QHRZ:CQSU:3XOB
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 55
  System Time: 2019-08-29T16:09:33.584043+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
PS: Sorry if this is not the right place to report this, but I had a bit of a hard time navigating the many docker-related repositories and community channels to find the relevant one for docker desktop for windows.
